### ISSUE TITLE
Cursor remains on the terminal

### ISSUE THREAD

**Issue by kangni** [microsoft/vscode#122114]
Issue Type: <b>Bug</b>

Cursor remains on the terminal when I use ssh remote.

VS Code version: Code - Insiders 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1, 2021-04-23T05:12:49.229Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.5.8-1.el7.elrepo.x86_64

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|2.4.0
vsc-material-theme|Equ|33.2.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-tree-sitter|geo|0.1.26
vscode-emacs|hir|0.1.1
output-colorizer|IBM|0.1.2
dotenv|mik|1.0.1
remote-containers|ms-|0.171.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
vscode-remote-extensionpack|ms-|0.20.0
js-debug-companion|ms-|1.0.11
material-icon-theme|PKi|4.6.0
vscode-nginx|wil|0.7.2
material-theme|zhu|3.10.13
gitlens|eam|11.4.1
rest-client|hum|0.24.5
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.780948196

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletextcf:30288478
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2ct:30286873

```

</details>

**Comment by kangni** [comment]
![IMG_2192](https://user-images.githubusercontent.com/2881570/115994042-ffb58480-a607-11eb-829a-6c6f44cd664e.JPG)

**Comment by meganrogge** [comment]
please open a new issue if you're still seeing this. thanks!
