### ISSUE TITLE
View state is not restored when part of the editor is folded

### ISSUE THREAD

**Issue by anseki** [Microsoft/vscode#12210]
- VSCode Version: 1.5.2
- OS Version: Windows

When VS Code is started, the scroll position is set to a position that a cursor was put at last time.
And also, when that editor tab is activated again, the scroll position is set to a position of cursor.

I think that the first behavior is useful, but the second makes me confuse sometimes.
For example, when I'm editing a line, I want to see another line. I scroll the editor by using scroll bar because I don't want to move the cursor, and also, I switch the tab to another file.
Now I back to the tab I'm editing, then the scroll position is changed. Here is position of the cursor. It's not the position I set.

**Comment by bpasero** [comment]
@anseki that should not happen, we always try to restore the view position of the editor, so you cursor can be in some location but we restore the scroll position to where you left from. can you share more details and explain if this is not the case for you? see my video how it works for me:

![untitled](https://cloud.githubusercontent.com/assets/900690/18624979/c4507744-7e4b-11e6-97dc-d025ccb5433e.gif)

**Comment by anseki** [comment]
I found this issue occurs when a part of the code is folded.
When one or more parts of the code is folded, the scroll position of that code is changed to cursor position when the view is activated.
After I did "Unfold All" command, the issue didn't occur.

**Comment by bpasero** [comment]
I can reproduce that when a region is folded, the view state is not preserved and I end up scrolled to the top. @alexandrudima @aeschli fyi.

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/18628267/b0463b80-7e5f-11e6-8d47-3a0ebfb994e1.gif)

**Comment by bpasero** [comment]
Is fixed.
