### ISSUE TITLE
Test: improved rendering of the Remote Command Palette

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#122101]
Ref https://github.com/microsoft/vscode-remote-release/issues/4831

- [x] macOS @egamma 
- [x] windows @meganrogge
- [x] linux @deepak1556

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122101%0A%0A)

---
The labels in the remote menu no longer start with `Remote-XY`. Instead this is now shows as group label

- install all remote extensions: ssh, containers, wsl, codespaces
- click on the remote indicator to see the remote window actions
- verify that command labels are understandable and its clear for which remote they apply
- filter the list. verify that commands are always grouped by remote and that there is a group label.
- test that the remote extension labels when in a local window and when in the corresponding remote windows

**Comment by meganrogge** [comment]
👏🏼
