### ISSUE TITLE
createStatusbarItem can not run "editor. ..." commands

### ISSUE THREAD

**Issue by AnWeber** [Microsoft/vscode#12214]
- VSCode Version: 1.5.2
- OS Version: win10

I created a extension, which registers a new Statusbar Item with call to [createStatusbarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api). Setting property command to e.g 'editor.action.commentLine'. After click the message "Command 'Toggle Line Comment' can not be run from here." 
![error](https://cloud.githubusercontent.com/assets/13434739/18615003/df6e9f62-7d9a-11e6-9fac-3835f1c19c18.png)

The issue happens since v1.5.1.

Steps to Reproduce:

[comment-line.zip](https://github.com/Microsoft/vscode/files/478634/comment-line.zip)

1. Unzip extension comment-line
2. npm install
3. execute extension
4. click on created StatusBarItem 

Code needed to reproduce issue:

`export function activate(context: vscode.ExtensionContext) {
   const statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 1);
    statusBarItem.command = 'editor.action.commentLine';
    statusBarItem.text = '//';
    statusBarItem.show();
    context.subscriptions.push(statusBarItem);
}`

**Comment by jrieken** [comment]
@bpasero Is there a reasons why [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L239) is so complex and not just a call to the keybindings/commands service?

**Comment by jrieken** [comment]
@AnWeber With respect to the comment line action the behaviour makes sense to me as the command needs editor focus (as most other actions). The question if it behave like the editor is focused and if this used to work before?

**Comment by bpasero** [comment]
@jrieken no I think this code is old enough that it might have even been written before we had all actions (workbench, editor) go into the command service. I am fine changing this to a simpler call if possible 👍

**Comment by jrieken** [comment]
@alexandrudima How should be tackle the enablement challenge (comment line invoked from outside the editor)? I see that the keybinding options ask for text focus (correctly) and `action.enabled` returns false. Unsure if the last refactoring gave me another knob to control this

**Comment by AnWeber** [comment]
@jrieken According to an user of my extension [statusbar-commands](https://github.com/AnWeber/vscode-statusbar-command/issues/4) the issue happens since 1.5.1. 

By using the command palette the focus is not lost either. Is it possible to use the same methods.
