### ISSUE TITLE
VSCode totally freezes the computer when updating on MacOS 11.2.3 (M1 chipset)

### ISSUE THREAD

**Issue by nobodyindustries** [microsoft/vscode#122111]
- VS Code Version:

Version: 1.55.2 (Universal)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

- OS Version: macOS Big Sur 11.2.3 (M1)

Steps to Reproduce:

1. VSCode updates on the background
2. The computer freezes totally and can't be used unless hard reset (long pressing the power button)
3. After restarting, it asks to restart VSCode to finish updating it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Is this still an issue with latest stable `1.56.2` ? If it is, can you attach the logs from `~/Library/Caches/com.microsoft.VSCode.ShipIt/`
