### ISSUE TITLE
on reload, the first tab to be focused/selected has instance options disabled

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122161]
![recording - 2021-04-25T201604 558](https://user-images.githubusercontent.com/29464607/116024440-0c83a980-a603-11eb-8e28-71d15ddbe67b.gif)

Something wrong related to https://github.com/microsoft/vscode/pull/122148

**Comment by Tyriar** [comment]
It looks like the explorer focuses the item on right click if it is not yet selected, maybe that's what we're missing here?

**Comment by pixieaka** [comment]
@Tyriar  Still a bug !

![Animation1](https://user-images.githubusercontent.com/17777237/116134252-fa237180-a6cf-11eb-9c67-31429831e709.gif)
