### ISSUE TITLE
program stuck  with css classes cached

### ISSUE THREAD

**Issue by flyher** [Microsoft/vscode#12211]
- VSCode Version: 1.5.2 ,1.4
- OS Version: Win7 x64

Steps to Reproduce:

1. open a project include more .css or .less files
2. click in the bottom of vscode gui   ⚡  'css classes cached(click the cache again)'
![untitled](https://cloud.githubusercontent.com/assets/5570324/18614876/ea3b911e-7dc9-11e6-9fa7-cef10ad8f3a4.png)

3. the state show the message 'Looking for CSS classes on the workspace...'
![untitled](https://cloud.githubusercontent.com/assets/5570324/18614726/00b6ddca-7dc7-11e6-987d-afb1e3f3f83c.png)

4. waiting for a while, then the program stuck( IDE freezes) and alert 'The window is no longer responding '

ps:
open Windows Task Manager ,i can see many process named Code.exe
![untitled](https://cloud.githubusercontent.com/assets/5570324/18614777/237321f6-7dc8-11e6-9e3a-204fcae88f70.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
