### ISSUE TITLE
Tab titles don't show up when launching task(s) when the terminal is hidden

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122191]
Repro:

1. Close all terminals
2. Press ctrl+shift+b to trigger default build tasks
3. Ctrl+` to open terminal

![image](https://user-images.githubusercontent.com/2193314/116082698-91e17b00-a650-11eb-8939-f3335f77aa22.png)

**Comment by Tyriar** [comment]
Task must use `"isBackground": true,` for repro

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/122227

**Comment by Tyriar** [comment]
Left intentionally as bug since it has a separate repro case to verify
