### ISSUE TITLE
VS code debugger keeps pausing on start

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/vscode#122170]
- VS Code Version:
- 1.55.2
- OS Version:
- Windows 10 1909

Steps to Reproduce:

1. Create js file 
``` 
// test.js
import {isMainThread, Worker} from "worker_threads";

if(isMainThread){
    new Worker('./test.js')
} else {
    console.log('--Worker--')
}
```
2. Run it in debug by node js configuaration.

Vscode pauses on debugger statement at firs line of the code.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by niyarlatotep** [comment]
[vscode-debugadapter-3b13bf31.json.gz](https://github.com/microsoft/vscode/files/6378941/vscode-debugadapter-3b13bf31.json.gz)

**Comment by connor4312** [comment]
Thanks, this looks like a Node.js bug. I've opened https://github.com/nodejs/node/issues/38420 for them, please subscribe to that for updates.
