### ISSUE TITLE
cannot save file without extension

### ISSUE THREAD

**Issue by sKopheK** [microsoft/vscode#122183]
Issue Type: <b>Bug</b>

1) file -> save as
2) enter any filename
3) select "all files (*.*)" in "Save as type" combo
4) hit save

a wild error saying "filename is invalid" appears
https://imgur.com/a/wUgarLn

works fine in other apps, tested in firefox and notepad++

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.63GB free)|
|Process Argv|--crash-reporter-id e54b25c4-2c93-4b1e-afca-34c75c4bbbc5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.0.4
jest-snippets|and|1.8.0
openmatchingfiles|bca|0.5.0
vscode-intelephense-client|bme|1.7.0
vscode-standardjs-snippets|cap|0.8.15
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.20
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
react-native-react-redux|EQu|2.0.6
php-debug|fel|1.14.12
html-slim-scss-css-class-completion|gen|1.7.8
live-sass|gle|5.0.2
lorem-whatever|job|1.0.2
sublime-babel-vscode|jos|0.2.10
vscode-project-links|Kyl|1.1.1
vscode-scss|mrm|0.9.1
powershell|ms-|2021.2.2
vscode-typescript-next|ms-|4.3.20210425
debugger-for-chrome|msj|4.12.12
vscode-jest|Ort|3.2.0
cssreset|Ris|1.0.0
LiveServer|rit|5.6.1
html5-skelton|sha|1.0.1
html5-boilerplate|sid|1.1.1
vscode-typings|typ|0.0.5
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by bpasero** [comment]
That looks like it is entirely handled by Electron itself and/or the OS.

**Comment by bpasero** [comment]
Filed https://github.com/electron/electron/issues/28850

**Comment by bpasero** [comment]
To save without extension pick the "No Extension" entry:

![image](https://user-images.githubusercontent.com/900690/116246659-7bc7dd80-a76a-11eb-9483-34b452b3b5d6.png)
