### ISSUE TITLE
crash when moving cursor (insiders build, wayland, electron 12)

### ISSUE THREAD

**Issue by mvondomaros** [microsoft/vscode#122185]
- VS Code Version: 1.56.0-insider (aur/visual-studio-code-insiders-bin 1616574691-1)
- OS Version: Arch Linux, GNOME 40, Wayland

Steps to Reproduce:

1. `code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland --verbose`
2. wait for as long as you'd like; everything looks nice (not blurry anymore)
3. moving the cursor causes a crash with the following new log messages:
```
/dev/fd/3: No such file or directory
Server response:
```
4. everything works without the ozone/wayland flags

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash report. Thanks!

**Comment by mvondomaros** [comment]
The issue has been resolved with the latest AUR update.
