### ISSUE TITLE
Emmet doesn't work anymore 2021 April 26th

### ISSUE THREAD

**Issue by Dovtutis** [microsoft/vscode#122178]
Emmet trigger expansion on TAB for HTML tags in PHP filed does not work any more, the error message is: "Running the contributed command:'emmet.expandAbbreviation' failed"

**Comment by rzhao271** [comment]
@Dovtutis does this issue still occur on the latest Insiders? https://code.visualstudio.com/insiders/

**Comment by Dovtutis** [comment]
> @Dovtutis does this issue still occur on the latest Insiders? https://code.visualstudio.com/insiders/

With the Insiders works as it should, everything fine. So I should switch to using VSC insiders?

**Comment by rzhao271** [comment]
That's good. You can either switch to VSC Insiders, or wait approximately two weeks for the features to show up in VSC Stable (it'll be the v1.56 release).
I'll close this issue since it works in Insiders.
