### ISSUE TITLE
ctrl + z  Can undo closed files

### ISSUE THREAD

**Issue by awhlmycn** [microsoft/vscode#122158]
1. Make changes to a file, save the file, then close it.
Reopen said file, hitting ctrl + z will undo the changes that was made before closing the file
How come it's possible to undo changes to a file that has been saved and closed previously?
Feature request: once a file have been closed, ctrl + z shouldn't undo the changes that was made before the file was closed

**Comment by markkyaw** [comment]
Duplicate of issue https://github.com/microsoft/vscode/issues/122127

**Comment by alexdima** [comment]
You can configure `"files.restoreUndoStack": false` to avoid restoring the undo stack when the file is reopened.
