### ISSUE TITLE
Split terminal + should support shift-click to open split

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122117]
Terminals no longer have a split button in the panel tab bar. So, not having the terminal tabs very wide, I automatically tried to open a split terminal the same way I would open a split editor: by shift+clicking on the ➕ icon. I think we should support this action.

**Comment by Tyriar** [comment]
I think you mean alt click? Both shift+alt change the split direction in the editor's split button, but it's alt+click in the explorer?

**Comment by connor4312** [comment]
On windows for me alt+click in the explorer adds to the selection. But in ctrl+p it's alt+enter/alt+click, which is somewhat confusing 😛

**Comment by Tyriar** [comment]
@connor4312 I guess you have some setting that affects this?
