### ISSUE TITLE
Terminal don't work in VS code inside a WSL2G distro Ubuntu

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#122164]
I did install wsl --install to enable wsl in latest insider release. After enable I install vs code. VS code installed and start running.

Every time I try to open terminal it's open a new instance. The terminal feature is not working. Please look.

- VS Code Version: Latest
- OS Version: WSL2G Graphic enabled WS2 Ubuntu

Steps to Reproduce:

1. setup the install and install code from .deb file. 
2. Type CTRL + ~ to open terminal, it's open a instance rather open terminal.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
What are the errors in `Help -> Open Dev Tools -> Console`?

**Comment by anirugu** [comment]
give me sometime, I will check over weekends. Thanks

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by anirugu** [comment]
I make a small video demonstrate how it's react when I use terminal https://www.youtube.com/watch?v=SOShl3Vb4ew

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by anirugu** [comment]
I unregistered the distro in last few days. tried in new one. I install vs code in my pc so everytime I try to sync the sign in open back the vs code on windows.

the settings is showing {} but issue is still same.

**Comment by Tyriar** [comment]
@deepak1556 have you seen this where some processes in wslg will end up launching a new window because the electron executable is used?

**Comment by deepak1556** [comment]
Not aware of a similar issue, @anirugu can you launch the app like `NODE_DEBUG='child_process' code --verbose` from terminal and perform the above steps. Attach the log that is printed, thanks!

**Comment by anirugu** [comment]
I downgrade the Windows after having some issue with insider build. You can try in VM or something.
