### ISSUE TITLE
Integrated Terminal keyboard blocked

### ISSUE THREAD

**Issue by wimZ** [microsoft/vscode#122146]
[renderer4.log](https://github.com/microsoft/vscode/files/6373198/renderer4.log)
Issue Type: <b>Bug</b>

It is impossible to key any data in integrated terminal.
- disabled all extensions; no result
- restarted; no result
- rebooted; no result
 
Added renderer4.log, which has a terminal related error entry.
Hope it helps. 

VS Code version: Code - Insiders 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1, 2021-04-23T05:13:46.805Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.74GB free)|
|Process Argv|--crash-reporter-id 70fc48d0-c0e2-45d0-a96d-7dc8cefa8e0e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820:30276952
vscoreces:30290705
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by xing0713** [comment]
My situation is similar to yours. It is impossible to key any data in integrated terminal.

**Comment by incastea** [comment]
It probably the Electron 12 issue. It’ll be fixed with Monday’s Insider build.

**Comment by fedorg** [comment]
The issue is fixed in the latest build of Insiders.

Version: 1.56.0-insider (user setup)
Commit: 9a4d524f909e09079fec7abb82f2efde2172da7c
Date: 2021-04-27T06:15:26.914Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by wimZ** [comment]
Fixed it.  Thanks!!!!!
