### ISSUE TITLE
Multibyte characters are displayed out of the box when entered with non default zoom level

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#122135]
- VS Code Version: Version: 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open Editor
2. Zoom In (Ctrl +)
3. Type Japanese by using Japanese IME

Does this issue occur when all extensions are disabled?: Yes

https://user-images.githubusercontent.com/1955233/115997450-17980300-a61e-11eb-93b9-fec336ef3f05.mp4

~ok: Version: 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d)~
~ng: Version: 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1)~

**Comment by alexdima** [comment]
From my testing I think this issue is also fixed by https://github.com/microsoft/vscode/pull/139394
