### ISSUE TITLE
Extension contributions table should use text link colors

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#122108]
```js
"workbench.colorCustomizations": {
	"textLink.foreground": "#ff9d00",
	"textLink.activeForeground": "#ffd900",
}
```

![contributions_link_color_not_applied](https://user-images.githubusercontent.com/9638156/115969749-48593900-a547-11eb-82da-0450fe4c9fb3.png)

**Comment by sandy081** [comment]
/duplicate

Will handle when migrating to use table widget
