### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by naina-jain-temp** [microsoft/vscode#122174]
Issue Type: <b>Bug</b>

Whenever I am saving file, Unknow exception is coming

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.27GB free)|
|Process Argv|--crash-reporter-id 9234383a-3e7e-47df-9506-abcfab3de02c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
apex-pmd|chu|0.5.3
vscode-eslint|dba|2.1.20
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
lana|Fin|1.3.5
vscode-npm|fkn|3.3.0
gitlab-workflow|Git|3.18.0
search-node-modules|jas|1.3.0
apex-pmd-code-scanner|moh|0.0.40
vscode-commons|red|0.0.4
vscode-xml|red|0.16.0
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|51.10.0
salesforcedx-vscode-apex|sal|51.10.0
salesforcedx-vscode-apex-debugger|sal|51.10.0
salesforcedx-vscode-apex-replay-debugger|sal|51.10.0
salesforcedx-vscode-core|sal|51.10.0
salesforcedx-vscode-lightning|sal|51.10.0
salesforcedx-vscode-lwc|sal|51.10.0
salesforcedx-vscode-visualforce|sal|51.10.0
sfdx-package-xml-generator|Vig|2.0.5
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vscnewfilehidden:30288034
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
