### ISSUE TITLE
vsc not working

### ISSUE THREAD

**Issue by PV19** [microsoft/vscode#122120]
We have written the needed data into your clic:\Users\Parth Vaghasia\Desktop\cpp\practice\" ; if ($?) { g++ topmnc.cpp -o topmnc } ; if ($?) { .\topmnc }
PS C:\Users\Parth Vaghasia\Desktop\cpp\practice> pboard because it was too large to send. Please paste.

**Comment by PV19** [comment]
its asking for update but when i try to update it its showing  no updates avaiable

**Comment by iamdevvalecha** [comment]
@PV19 please close this
