### ISSUE TITLE
Test the `statusBar/remoteIndicator` menu contribution point

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#122102]
Ref https://github.com/microsoft/vscode/issues/121180

- [x] anyOS @jrieken 
- [x] anyOS @RMacfarlane 
- [x] anyOS @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122102%0A%0A)

---
The `statusBar/remoteIndicator` menu contribution point allows to contribute a command to the remote indicator menu

```
"contributes": {  
    "menu": {
        "statusBar/remoteIndicator": [
        {
          "command": "remote-wsl.newWindow",
          "when": "!remoteName && isWindows",
          "group": "remote_10_wsl_0_local@1"
        }
   }
}
```
Only menu entries are accepted `"group"` follows a specific syntax:

- For commands from remotes: `remote_${order}_${remoteName)_${internalGrouping}`
- For commands from virtual file systems: `virtualfs_${order}_${fileScheme)_${internalGrouping}`

`order` is a double digit number used to sort entries with the same supergroup (remote, virtualfs)
- remoteName is first part of the remoteAuthority (wsl, ssh,...)
- fileScheme is the URI schema of the virtual file system
- internalGrouping is of free use for each contribution

Examples:
`remote_50_wsl_1-open@1`
`virtualfs_github-fs_9-help@9`

- Test that you can contribute a menu to the remote indicator menu without the need of having 'proposedAPI' enabled
- Test that a command is only shown in the menu if `group` follows the syntax described above.
- Test that if the group has an invalid syntax, command is not shown, but there's a message is logged to the console dev tools.

**Comment by dbaeumer** [comment]
Did some additional testing after @RMacfarlane hint in #122524
