### ISSUE TITLE
Does not show typed text in Integrated Terminal

### ISSUE THREAD

**Issue by SpiderMath** [microsoft/vscode#122122]
- VS Code Version: (insiders Build) v1.56.0 
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open the VSCode Terminal
2. Try to Type in anything

Does this issue occur when all extensions are disabled?: Yes

Like in the video attached, I've literally smashed my keyboard to type but it just is not typing anything (My keyboard's fine or else I would not be able to make this Issue :man_shrugging: )
This issue has been noticed by me for last 3 days but I didn't see anything fixed.
(Sorry for the Light Theme :sweat_smile: )

https://user-images.githubusercontent.com/71999854/115986015-ff979380-a5cb-11eb-9012-3276be467ac1.mp4

**Comment by sky798** [comment]
I met same problem with your.

**Comment by incastea** [comment]
It’ll probably be fixed on today’s Insider build.

**Comment by incastea** [comment]
Sure. It’s been fixed. You can close this issue.
