### ISSUE TITLE
Better support freeform and pasting into the simple file picker

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#122197]
Context: https://github.com/microsoft/vscode/issues/121280

Things to support:
- Pasting a full path into the input box
  - Items should update
  - If a file is included in the path it should be selected.
- Better handling of invalid paths
  - Support `~` as an "escape hatch" from bad paths

**Comment by bersbersbers** [comment]
Thanks - just clarifying one element:

> Items should update

That update should check for non-existent directories, including (apparent) sub-directories and files in non-existent directories - that is certainly not working for files yet:

![eKvlUvG7Za](https://user-images.githubusercontent.com/12128514/117259722-9d058980-ae4e-11eb-8a20-784eec64a99e.gif)

Removing the items shown for non-existent directories should also fix the incorrect highlight of `dir.tmp` (which resides in `/home/bers`!) at `/home/bers/this/d`.

**Comment by piyaphart90** [comment]
[]()

**Comment by bersbersbers** [comment]
Another thing to fix: 
![xW2fgGYxbd](https://user-images.githubusercontent.com/12128514/117950114-24ea0880-b313-11eb-8d6b-ac7b741c8146.gif)

In this example, I am using Remote SSH to work on a remote Linux server. Starting from the original path,
`/tmp/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub/sub`, I do nothing else but hold <key>Ctrl</key> (on my Windows client keyboard) and hammer backspace. Two things are of note:

1. Stuff keeps reappearing
2. Even if not, I need two backspaces to remove one `sub/` (one for `/`, one for `sub`).

**Comment by bersbersbers** [comment]
Here's another one, potentially opening the wrong file when pasting a full path:

- Remote SSH/WSL into a Linux box.
- Open `/tmp` as a folder in VS Code
```
mkdir /tmp/bar
echo 1 > /tmp/foo
echo 2 > /tmp/bar/foo
```
- Put the file name "/tmp/bar/foo" into clipboard
- Ctrl-O - note that /tmp/ is prefilled.
- Ctrl-A, V to paste "/tmp/bar/foo", Enter

- File /tmp/foo is opened instead of /tmp/bar/foo.

**Comment by alexr00** [comment]
Pasting already works, just need to add the ~ escape hatch.

**Comment by alexr00** [comment]
To verify:
- Set `"files.simpleDialog.enable": true`
- `ctrl+o`
- Type stuff into the dialog input. Verify that if you type a `~` you immediately go to the home folder.
