### ISSUE TITLE
 Menu item references a command `extension.Db2createNewIndex` which is not defined in the 'commands' section.

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#122189]
- VS Code Version: 1.55.2
- OS Version: windows 10

Steps to Reproduce:

1. just declared a command with an icon.
2.Added it to the menus->view->item->context
3. Added it to the menu->commandPalette section.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/32290825/116082235-cd179480-a6b8-11eb-9e6a-f61d564d0530.png)

**Comment by akhilravuri1** [comment]
I have 6 commands which are declared in the commands section and used in the same pattern(menu,view->item->context, and CommandPalette).

Only one command returns an error.

**Comment by jrieken** [comment]
> Only one command returns an error.

I'd say you have a typo or some other error in that single instance but how would I be able to tell. You are not sharing your package.json...
