### ISSUE TITLE
If You have change Visual Code's install path,You cannot run preinstall.js:*** Invalid C/C++ Compiler Toolchain,

### ISSUE THREAD

**Issue by Qxiny** [microsoft/vscode#122131]
- VS Code Version:Next
- OS Version:Win10

Steps to Reproduce:

1.Change Visual Code's Path
2.

PS D:\个人文件\桌面\vscode-main> yarn
yarn install v1.22.10
$ node build/npm/preinstall.js
*** Invalid C/C++ Compiler Toolchain. Please check https://github.com/microsoft/vscode/wiki/How-to-Contribute.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Does this issue occur when all extensions are disabled?: Yes

if you change preinstall.js's function hasSupportedVisualStudioVersion()'s the second “if”'s vsPath to your Vs path ,it will work

sorry for I'm not an English user
Mail:3185835784@qq.com

**Comment by joaomoreno** [comment]
> 1.Change Visual Code's Path

If you want to do this, please uninstall and install in the new path.
