### ISSUE TITLE
Translation fix for Chinese

### ISSUE THREAD

**Issue by zwlxt** [Microsoft/vscode#12218]
- VSCode Version: 1.5.2
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Ctrl-Shift-X to open extension manager 
2. Click any of the extensions in the list

![image](https://cloud.githubusercontent.com/assets/19585961/18616037/6f343962-7de7-11e6-9c65-67a697afc4f2.png)

In this case "扩展名" should be "扩展". "扩展" means extension, plugin, etc. while "扩展名" means suffix of filenames e.g. ".txt", ".exe".

This seems to occur only in tabs showing detailed information of extensions.

**Comment by johnliu2016** [comment]
mistranslated string in [extensionsInput.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fextensions%2Felectron-browser%2FextensionsInput.nls.resx.lcl&version=GBmaster&_a=contents)

**Comment by lukaschal** [comment]
Waiting for linguistic input.

File: src\vs\workbench\parts\extensions\electron-browser\extensionsInput.nls.resx
ID: ".resx", 0; "extensionsInputName"
SRC: Extension: {0}
TGT: 扩展名: {0}

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\workbench\parts\extensions\electron-browser\extensionsInput.nls.resx
ID: ".resx", 0; "extensionsInputName"
SRC: Extension: {0}
TGT: 扩展: {0}
