### ISSUE TITLE
VS Code downloads a bunch of C# extension to configure react->chrome debugger launch.json

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/vscode#122142]
- VS Code Version:
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 10.0.19041

Steps to Reproduce:

1. Create a hello world react js application: 
`npm install –g create-react-app`
`npx create-react-app hello-world-example`
2. Open the folder where you created the application in VSCode
3. `ctrl+shift+d` to open the debugger settings.
4. Click on the link to create a launch.json file.
5. Wait for VSCode to download over 140+MB of stuff for C# before showing the dropdown to select "Chrome" as the debugger target. Why is C# required for this scenario?

```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (38361 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (45048 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (60477 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'
```

Does this issue occur when all extensions are disabled?: Don't know

**Comment by isidorn** [comment]
Please file this here https://github.com/OmniSharp/omnisharp-vscode
And let them know that they should activate only on C# specific activations

**Comment by Petermarcu** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/4525

**Comment by Petermarcu** [comment]
Can you please reopen based on the feedback in the omnisharp issue? They can't fix without a fix from VSCode. https://github.com/OmniSharp/omnisharp-vscode/issues/4525
