### ISSUE TITLE
Build vscode: use split terminal for build tasks

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122287]
I am always using `Cmd+Shift+B` to build VSCode and that opens 2 terminals:

![image](https://user-images.githubusercontent.com/900690/116215662-309cd300-a748-11eb-8c22-64d94a2f520c.png)

I wonder if these 2 terminals should be split terminals in 1 group given we have cool support for this now?

![image](https://user-images.githubusercontent.com/900690/116216017-75c10500-a748-11eb-8d5c-69edbc2a0ef2.png)

//cc @Tyriar @meganrogge

**Comment by alexr00** [comment]
Tasks supports this too. I'm going to push the tasks.json change for this and we'll see what the team things.

**Comment by bpasero** [comment]
👏
