### ISSUE TITLE
Revise the `NotebookCellExecutionTask` api

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122253]
Split out from https://github.com/microsoft/vscode/issues/121329

The `NotebookCellExeuctionTask` api seems easy to misuse. I wonder if we can change the api to encourage correct usage.

https://github.com/microsoft/vscode/issues/121329 originally shared a sketch of potential redesign. Splitting it into this separate issue so we can track this work better:

```ts
interface NotebookCellExecutionTask {
    ...

    execute(
        context: NotebookCellExecuteStartContext,
        run: (executor: NotebookCellExecutor) => Promise<NotebookCellExecuteResult>
    ): void;
}

interface NotebookCellExecutor {
    appendOutput(out: NotebookCellOutput | NotebookCellOutput[], cellIndex?: number): Thenable<void>;
    ...
}
```

example usage:

```ts
task.execute({}, async (builder, token) => {
    await builder.appendOutput(...)
    ...
    return { success: true };
})
```

**Comment by roblourens** [comment]
I wanted to do something like this at one point, but honestly I prefer the simplicity of what we have now.

**Comment by mjbvz** [comment]
My proposal is quite similar to the existing api except that it moves all the modification operations into a block. I find this better expresses how the API is supposed to be used

**Comment by jrieken** [comment]
We still need a decision for https://github.com/microsoft/vscode/issues/119597 but the overall agreement is to leave this "more imperative"  and not callback-wrapped.
