### ISSUE TITLE
Test: TerminalOptions.icon API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122204]
Refs #120538

- [ ] macOS 
- [ ] linux 
- [ ] windows 

Complexity: 3

Authors: @tyriar 

---

Using the `extension-terminal-sample`, create a terminal with `TerminalOptions` including an `icon` (a codicon id). Verify that this icon is used when you create that terminal and have `terminal.integrated.showTabs: true`.

Make sure you've [enabled proposed api](https://code.visualstudio.com/api/advanced-topics/using-proposed-api)

**Comment by Tyriar** [comment]
Oh this one actually isn't ready for testing, we're going to change it to take ThemeIcons/uris
