### ISSUE TITLE
VSCode not picking up global/ambient types in node_modules/@types when editing typescript

### ISSUE THREAD

**Issue by mattyork** [Microsoft/vscode#12228]
- VSCode Version: 1.5.2
- OS Version: OS X

Steps to Reproduce:

**package.json:**
```json
{
  "devDependencies": {
    "@types/jasmine": "^2.2.33",
    "typescript": "^2.0.2"
  }
}
```

**tsconfig.json:**
```json
{
    "include": [
        "./test.ts"
    ]
}
```

**test.ts:**
```ts
describe('code', () => {
    it('should know that describe and it are defined', () => {
        expect(true).toBeTruthy();
    })
})
```

**.vscode/settings.json:**
```json
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```

![gif](http://g.recordit.co/5ZCckiKVJX.gif)

Expected: vscode understands global/ambient types from `node_modules/@types` just like tsc does
Actual: vscode does not understand global/ambient types from `node_modules/@types`

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11013
