### ISSUE TITLE
The fonts not look properly 

### ISSUE THREAD

**Issue by Odol** [Microsoft/vscode#12222]
- VSCode Version: 1.5.2
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. install javascript snippet pack and restart vscode

I not think it is for this reason.
Not sure as happened this but fonts look terrible :(
It may have been for one instalation of linux package I not sure..

##notes: settings.json dont have customizations: 
    
"editor.fontFamily": "'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",
"editor.fontWeight": "normal",
 "editor.fontSize": 14

screenshot:
![fonts code problems](https://cloud.githubusercontent.com/assets/11588112/18616913/447e749a-7d9b-11e6-8374-ebacf17d8792.png)

thanks for u time!

**Comment by alexandrudima** [comment]
@Odol Do you see the same behaviour on Chromium? Can you try customizing `editor.fontFamily`. I am not using Ubuntu all the time, but I remember someone saying Ubuntu stopped shipping Droid Sans Mono in v 16. Perhaps you need to install that font by yourself?

**Comment by qalex** [comment]
Can confirm. Upgraded from 14.04.5 to 16.04.1 and there's no Droid Sans Mono font. Installed it manually and VSCode looks good again.

**Comment by alexandrudima** [comment]
@Odol as per @qalex comment please install Droid Sans Mono by yourself or customize the fontFamily to use one that ships on the distro.

@qalex @Tyriar do you have good suggestions for a new defaut `editor.fontFamily` we should ship with that hits a font intended for programmers and that ships out of the box on Ubuntu 16?

I'm thinking to change it to something like:
"'Droid Sans Mono', **NEW_FONT_HERE** 'Courier New', monospace, 'Droid Sans Fallback'"

such that folks still on Ubuntu 14 or that have installed Droid Sans Mono manually don't get broken.

**Comment by qalex** [comment]
@alexandrudima Ubuntu Mono looks good (much better than Courier New) and it exists on every Ubuntu system. But of course it is distro-dependent and I can't say if this is a good choice.

**Comment by Tyriar** [comment]
@alexandrudima @qalex  This is a duplicate of https://github.com/Microsoft/vscode/issues/5742, I'll comment over there.
