### ISSUE TITLE
No title for test outputs in terminal

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122227]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/876920/116136762-983f1980-a687-11eb-8947-dddfeb4fb622.png">

**Comment by connor4312** [comment]
It looks like you have a hover tooltip that has the title, but the tabs doesn't render it. There's no API that separates these two things in the terminal, so I think it's a tabs bug.

Code pointers for where the name/title is set

https://github.com/microsoft/vscode/blob/8b15a01d8eb362209e1a440297087d1ebc36eff2/src/vs/workbench/contrib/testing/browser/testingOutputTerminalService.ts#L97

https://github.com/microsoft/vscode/blob/8b15a01d8eb362209e1a440297087d1ebc36eff2/src/vs/workbench/contrib/testing/browser/testingOutputTerminalService.ts#L103

**Comment by Tyriar** [comment]
Perhaps the icon fallback isn't working or something, if no icon is resolved, no text will display in order to prevent text shifting from left to right.

**Comment by Tyriar** [comment]
This happens for non-testing terminals as well, repro:

1. Hide terminal
2. Press show output button

<img width="282" alt="Screen Shot 2021-04-27 at 7 40 10 AM" src="https://user-images.githubusercontent.com/2193314/116260815-e4439a00-a72b-11eb-8a85-faa62d740c58.png">

**Comment by meganrogge** [comment]
Kai saw this in today's insider's

**Comment by Tyriar** [comment]
If anyone gets details on a repro here please let me know. Something to try if you see this is to see if creating a new terminal will fix up the terminal (which would indicate a missing layout call, rather than a missing icon hiding the title).

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/116747052-385fb000-a9b2-11eb-93a9-25b4a612bf87.png)

I often see this after reloading this ssh window. Creating a new terminal, or resizing, does not fix it

**Comment by meganrogge** [comment]
Easily reproes in remote after reloading the window. 

Think it's as a result of https://github.com/microsoft/vscode/blob/9ff7c93a9b4419c1a4bab787c59f0093578bc4d7/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1070-L1070

**Comment by meganrogge** [comment]
Not sure why the aria label shows up correctly though if that's the problem

**Comment by Tyriar** [comment]
Reopening as I'd like to get rid of the icon flicker as well

**Comment by Tyriar** [comment]
Easy repro: create a terminal using extension-terminal-sample 

<img width="439" alt="Screen Shot 2021-05-06 at 3 16 17 PM" src="https://user-images.githubusercontent.com/2193314/117372269-1cf71800-ae7e-11eb-9157-59a838046b60.png">

**Comment by Tyriar** [comment]
To verifier:

Test new terminals to ensure that:
- The icon doesn't change shortly after being created
- The terminal text doesn't shift from left to right on creation (it should show up when the icon is ready)

Test the following configurations:
- No terminal profile/shell settings
- A valid defaultProfile with a non-default icon, no shell setting
- A shell setting but no defaultProfile
- Creating a terminal with https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample works
