### ISSUE TITLE
Test notebook serializer API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122210]
Refs: https://github.com/microsoft/vscode/issues/119089

- [x] anyOS @alexdima
- [x] anyOS @JacksonKearl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122210%0A%0A)

---

We have added a new notebook serializer API. It allows you to implement a simple read/write but no execute notebook in VS Code. Focus on the following two APIs

* in `package.json` use the `notebookProvider` contribution points
* in your extension use the `vscode.notebook.registerNotebookSerializer` API

If you have time write a simple extension or review the [regex notebook](https://github.com/jrieken/vscode-regex-notebook/blob/eacf37f2ee11cd556f661ee6fb145ff68d708319/src/extension/extension.ts#L55) extension. When using the API make sure that

* the API works
* the API is easy to use and properly documented

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.proposed.d.ts`

**Comment by JacksonKearl** [comment]
Wasn't able to get tit working with untitled notebooks, that seems to be a separate issue with working copy service. Other than that it's nice to use and sure beats `registerNotebookContentProvider`
