### ISSUE TITLE
action menu icon can't not click

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#122266]
版本: 1.55.2 (system setup)
提交: 3c4e3df9e89829dce27b7b5c24508306b151f30d
日期: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. install code runner
2. open a python file
![run_not_work](https://user-images.githubusercontent.com/1876302/116182933-a7899a00-a74f-11eb-8401-b5a627720694.gif)
3. can't click any popup icon

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
I've a feeling this is a result of much more than just that extension. @heartacker please use the `Extension Bisect` command to investigate https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

**Comment by heartacker** [comment]
https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar
after I disable this extension，they run well 。

**Comment by heartacker** [comment]
now it is no more problem
