### ISSUE TITLE
Remove vertical guideline in tree view

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#122285]
Can we provide a way to remove this vertical line in tree view?
![image](https://user-images.githubusercontent.com/73154171/116214411-41197180-a779-11eb-91d3-f1b01661fc24.png)

**Comment by gjsjohnmurray** [comment]
Did you try changing the `workbench.tree.renderIndentGuides` setting?

**Comment by alexr00** [comment]
@gjsjohnmurray thank you, that's the correct setting for removing the tree indent guides.

**Comment by HuihuiWu-Microsoft** [comment]
> Did you try changing the `workbench.tree.renderIndentGuides` setting?

Hi, I wonder how can I do this for my extension since I can't change user's settings.
