### ISSUE TITLE
Explorer puts a "!" next to a folder saying it is unresolved

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122276]
Steps to Reproduce:

1. run out of sources
2. open the `vscode-extension-samples/fsprovider-sample`
3. set `activationEvents` to `*`
4. register a command that has this code:

```ts
vscode.commands.executeCommand('_files.windowOpen', [
    { folderUri: vscode.Uri.parse('memfs:/folder/') }
]);
```
5. call the `memfs.init` directly from the `activate` method of the extension to have the in memory provider updated
6. launch and run the command to open a window

=> the explorer populates fine but keeps showing this !

![image](https://user-images.githubusercontent.com/900690/116202159-94200400-a73a-11eb-8a16-a919f080fec0.png)

**Comment by gjsjohnmurray** [comment]
Maybe related to #122004

**Comment by isidorn** [comment]
Yeah let's close as dup of that one https://github.com/microsoft/vscode/issues/122004
