### ISSUE TITLE
Unable to open multiple vscode editor windows

### ISSUE THREAD

**Issue by Git-Hub-User-0** [microsoft/vscode#122273]
Issue Type: <b>Bug</b>

If more than one window is opened, then the second opened window gets hanged. But if i use the second window in non-maximized mode, then it works, but not if both the windows are maximized.
Please help me with this.

Note: All the extensions are disabled.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 4.4.0-208-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (4.12GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 316f57fc-6a37-4646-92a8-2b40f2bf5126|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by bpasero** [comment]
This sounds more like an electron issue to me. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Git-Hub-User-0** [comment]
@bpasero 
It's working fine with visual studio code insider.

**Comment by Git-Hub-User-0** [comment]
@bpasero 
Thanks :)
