### ISSUE TITLE
Cannot open terminal panel when started from WSLg GUI

### ISSUE THREAD

**Issue by digitive** [microsoft/vscode#122249]
- VS Code Version: 1.55.2
- OS Version: Windows 10 Pro Build 21364.co_release.210416-1504 + WSL2 Ubuntu 20.04

Steps to Reproduce:

1. Install code on Ubuntu, start vscode by click Windows Start -> Ubuntu -> Visual Studio Code (Ubuntu) (WSLg Feature)
2. In vscode, click View -> Terminal

Expect:
Show terminal panel

Actual:
Lauched a new vscode instance with startup page.

Additional info:
Output "[error] getUnixShellEnvironment#error Failed to get environment"

This bug doesn't exist if start code directly from terminal, only happens when started from Windows Start menu

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/blob/328937e7b642e56e62ba6bce91376bc2e0035268/src/vs/platform/environment/node/shellEnv.ts#L158-L158

@digitive not sure if you're just experimenting, but you'll get a much better experience using [remote - wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

**Comment by joaomoreno** [comment]
@digitive Can you please provide a [screen recording](https://gifcap.dev/)?
