### ISSUE TITLE
Trusted domains `getRemotes` call errors in virtual folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122277]
Steps to Reproduce:

1. open a window on a virtual file system (e.g. use our extension sample for this: https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample)
2. watch for devtools errors:

```
ERR No file system provider found for resource 'memfs:/folder/.git/config': ENOPRO: No file system provider found for resource 'memfs:/folder/.git/config'
    at FileService.withProvider (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/files/common/fileService.js:106:31)
    at async FileService.exists (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/files/common/fileService.js:220:30)
    at async file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/url/browser/trustedDomains.js:113:32
    at async Promise.all (index 0)
    at async getRemotes (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/url/browser/trustedDomains.js:108:25)
console.js:104 
```

This code probably needs to wait for extensions to activate or defer until then to resolve extension provided file systems.

PS: I think the `Promise.all` usage is dangerous [here](https://github.com/microsoft/vscode/blob/27675a99be1366ca44518d380d2ad514a4acd4b3/src/vs/workbench/contrib/url/browser/trustedDomains.ts#L158-L158) because the first error will keep all other promises running. We have a `Promises.settled` utility as an alternative.

**Comment by gjsjohnmurray** [comment]
See #122004 for a similar issue involving things happening before FileSystemProvider extensions have been activated.

**Comment by JacksonKearl** [comment]
We don't want to block on FS providers activating, as that gets into weird situations where the extension needs to open a link to authenticate prior to resolving a file, but it can't open the link until the FS provider resolves, etc. 

Makes sense adopt `settled` and just swallow errors, we mainly care about `.git/config` of the local filesystem anyways.

**Comment by JacksonKearl** [comment]
Just wrapped everything in try/catch, we can safely ignore errors and gracefully fall back to remote-agnostic link protection when the git config cannot be read.
