### ISSUE TITLE
`Illegal argument: range` when using `Format Code` with HTML content

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#12221]
I've just started to get this error with current insider release. Pretty sure that was not a problem in previous versions.
- VSCode Version: Version 1.6.0-insider (1.6.0-insider) (2016-09-16T06:03:08.867Z)
- OS Version: OS X 10.11.6
- extensions disabled by startup option

Steps to Reproduce:
1.  open any properly formatted HTML file (the file should have .html extension)
2.  CMD+SHIFT+P (trigger command pallete) and type `Format Code`

Expected results:
The formatting of the file is changed

Actual results:
The VSCode display Error message:
![image](https://cloud.githubusercontent.com/assets/14539/18616838/466b20fa-7dc3-11e6-9eb1-879a58385c39.png)

The content of developer console:

```
messageService.ts:120 Illegal argument: range
e.doShow @ messageService.ts:120
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous function) @ workbench.ts:659
e.invoke @ callbackList.ts:63
e.fire @ event.ts:117
(anonymous function) @ quickOpenController.ts:475
```

Thanks!

**Comment by ZCShou** [comment]
Now must be selected to format. Before do not need

**Comment by peterblazejewicz** [comment]
> Now must be selected to format. Before do not need

Thanks! Interesting, this seems to apply to .html. Why this is not happening with .js or .ts? I can just format JS/TS without selection.

**Comment by aeschli** [comment]
This got fixes in the meantime.
