### ISSUE TITLE
Sidebar items folding

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#122224]
The folding is very inconvenient for multiple panes/items . If a pane is pushed by other, it will keep the new size .

The panes is mainly resized in long term, based on their purpose . So this behavior results in requirement to never get them pushed . That doesn't allow to use more panes than fit in the pane that is closer to the other end of the list *<sup
         title="(other than the one on side they unfolded from)" style="color:dodgerBlue;"><b>(i)</b></sup>* . And means that when any pane is temporally resized, it has to be resized back to avoid the 'sub-panes' size growing .

Please make the panes: remember their size that've been set by resizing them with the up border/end, and try to restore it always when there is free space left in relation to the other unfolded panes' setting/preference sizes .

**Comment by sbatten** [comment]
split view feature request

**Comment by irvnriir** [comment]
@sbatten i don't see how this is related to Split View
