### ISSUE TITLE
Test new notebook renderers 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122251]
Refs #116393

- [x] Mac @rzhao271
- [x] Linux @connor4312
- [x] Windows @meganrogge

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122251%0A%0A)

---

## Background
This iteration, we polished the new, extensible markdown renderers for notebooks. This allow us to render `:smile:` as emoji and math formulas in a notebook's markdown. These features are both contributed by built-in extensions

To support this new functionality, we had to completely rework how markdown is rendered in notebooks. All the rendering is now done in the notebook's backlayer webview inside of in the renderer process. The rendered markdown is also displayed in the webview instead of in the workbench editor

## Testing
For this item, please give another exploratory test pass to markdown support in notebooks. A few general areas to focus on:

- Performance. Are there cases where the contents of a notebook seem to shift around?

- UX. Does interacting with notebook cells feel normal? The markdown cells should feel like they are part of the normal editor dom

- Math support. Try a few [math formulas](https://katex.org) in the markdown and see if these cause any issues

**Comment by meganrogge** [comment]
The math formulas and emojis look great 😄
