### ISSUE TITLE
Allow hiding VCS diff decorations in gutter in Zen Mode

### ISSUE THREAD

**Issue by vwkd** [microsoft/vscode#122240]
Zen mode is great, as it allows to hide the UI and focus on the content.

However currently, the VCS diff decorations in the gutter can not be hidden yet.

<img width="598" alt="Screen Shot 2021-04-26 at 23 40 26" src="https://user-images.githubusercontent.com/33468089/116154321-d1f43c80-a6e8-11eb-93d9-5c28c776cb35.png">

They can be hidden globally using `scm.diffDecorationsGutterVisibility`.

<img width="636" alt="Screen Shot 2021-04-26 at 23 35 48" src="https://user-images.githubusercontent.com/33468089/116153926-54c8c780-a6e8-11eb-9654-983b57d5fceb.png">

I'd like to see a setting for Zen Mode to hide the VCS diff decorations in the gutter.

Thanks.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
