### ISSUE TITLE
Jupyter: Typescript IntelliSense doesn't work across cells

### ISSUE THREAD

**Issue by tennox** [microsoft/vscode#122294]
- VS Code Version: `code-insiders_1.56.0-1619504753_amd64.deb`
- OS Version: `Pop!_OS 20.10`

Steps to Reproduce:

1. Open new jupyter notebook
2. Create two typescript cells:
  1. `import _ from 'lodashl'`
  2. `_.toString(123)`
3. See this:
![Screenshot from 2021-04-27 11-38-04](https://user-images.githubusercontent.com/2084639/116220588-1b767300-a74d-11eb-9f63-ac438f6691ce.png)
First cell: `'lodash' is declared but its value is never read`  
Second cell: `Cannot find name 'lodash'`  

This used to work fine about 1-2 months ago, thought it's a temporary problem...

I'm using https://github.com/yunabe/tslab kernel

Does this issue occur when all extensions are disabled?: No - there is no jupyter extension.

**Comment by TeNNoX** [comment]
[tsserver.log](https://github.com/microsoft/vscode/files/6383578/tsserver.log)

**Comment by mjbvz** [comment]
/fixedBy 595bc1d56b9fbcd1b353a49415d12a992137aa5e

Should be working now:
![Screen Shot 2021-09-30 at 11 50 40 AM](https://user-images.githubusercontent.com/12821956/135513698-717e48c1-cc44-43d7-8d8b-a9e44815c9d5.png)

Note that this requires https://github.com/microsoft/vscode/commit/595bc1d56b9fbcd1b353a49415d12a992137aa5e (which fixed a somewhat related issue) so make sure you have a current

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/135539147-f984ccbb-3459-48de-90ca-363556a18980.png)
Verified
