### ISSUE TITLE
[JSON] Schema not found error on opening package.json

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#122279]
- Version: 1.56.0-insider (user setup)
- Commit: 9a4d524f909e09079fec7abb82f2efde2172da7c
- Date: 2021-04-27T06:15:26.914Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open `package.json`

Here is the error message

![image](https://user-images.githubusercontent.com/15051871/116204899-d35e4d00-a75a-11eb-8f47-2e3ace869dea.png)

The text version: 

> CSS contributions to package.json
> 
> Problems loading reference 'file:///c%3A/Users/sanka/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/ms-vscode.remotehub/schemas/package.schema.json': Unable to load schema from 'c:\Users\sanka\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.remotehub\schemas\package.schema.json': ENOENT: no such file or directory, open 'c:\Users\sanka\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.remotehub\schemas\package.schema.json'.(768)

Does this issue occur when all extensions are disabled?: Yes ~~/No~~

**Comment by nguerrera** [comment]
I'm seeing this too. I worked around it for now by creating `AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.remotehub\schemas\package.schema.json` with `{}` as the content. Interestingly, I still get schema completion in package.json files so I guess this (built-in) extension is not even meant to be providing that?

**Comment by aeschli** [comment]
@eamodio I guess this was fixed by https://github.com/microsoft/vscode-remotehub/commit/9d22027fe7b3395b6261a562c13c0abdddbb9d67.
