### ISSUE TITLE
Test markdown getting started contributions

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122275]
Refs: https://github.com/microsoft/vscode/issues/119709,  https://github.com/microsoft/vscode/issues/120050

- [x] anyOS @egamma 
- [x] anyOS @eamodio (remote)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122275%0A%0A)

---

Set: `"workbench.welcomePage.experimental.extensionContributions": true` (this will be a registered setting in next insiders build)

We now support markdown in both the description and media elements of walkthrough steps:
```
		"walkthroughs": [
			{
				"id": "exampleProject",
				"title": "Turn Markdown into HTML",
				"description": "Use this sample project to learn how to convert Markdown to HTML!",
				"primary": true,
				"steps": [
					{
						"id": "md-to-html.openExample",
						"title": "Open an example folder",
						"description": "To start, try opening an example folder that has been preconfigured for this tutorial. **This is optional**, but helps for following along!\n[Open Example](command:md-to-html.openExample)",
						"media": {
							"path": "media/openExample.md"
						}
					},
```

In descriptions, we use a modified version of markdown that supports `**bold**`, `__italics__`, ``` ``code`` ```, and [links](command:workbench.action.blah).

In media elements, we use the standard version of markdown, notably with support for images and code syntax highlighting.

Test: 
- In descriptions, all styling elements work as expected (bold, italics, code)
- Links work to both external resources (`https://`) and commands (`command:`), commands additionally support arguments encoded via url encoding, and a `command:toSide:workbench.action....` syntax that attempts to run the command in a new editor split if space permits. For instance: `[Open Markdown File](command:toSide:workbench.action.quickOpen?%22.md%22)`
- Providing a path to a markdown file as the media element will show that markdown file in place of the standard image media, and content in the markdown file (especially images) works correctly. The markdown visualization should be approximately equal in functionality to the extension editor's rendering if markdown readme's.

**Comment by egamma** [comment]
@JacksonKearl I'm sorry but I need more context about a getting started contribution. Do you have a link to an example? Also is there any special setup needed? Do I need to enable proposed API (I don't get Intellisense in package.json).

**Comment by egamma** [comment]
Just for other testers this is the complete contributes section

```json
	"contributes": {
		"walkthroughs": [
			{
				"id": "exampleProject",
				"title": "Turn Markdown into HTML",
				"description": "Use this sample project to learn how to convert Markdown to HTML!",
				"primary": true,
				"steps": [
					{
						"id": "md-to-html.openExample",
						"title": "Open an example folder",
						"description": "To start, try opening an example folder that has been preconfigured for this tutorial. **This is optional**, but helps for following along!\n[Open Example](command:md-to-html.openExample)",
						"media": {
							"path": "media/openExample.md"
						}
					}
				]
			}
		],
		"commands": [
			{
				"command": "hello2.helloWorld",
				"title": "Hello World"
			}
		]
	},

```
