### ISSUE TITLE
`window.title` `${remoteName}` seems to be "vscode-remote" when not in a remote

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#122213]
I have my window title set to: `"window.title": "${folderName}${separator}${remoteName}"`.

And in today's insiders I'm seeing my window title end with `- vscode-remote` for every local window.

**Comment by bpasero** [comment]
I use this:

https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L294-L294

**Comment by isidorn** [comment]
Yeah I did a change on purpose, here's the motivation https://github.com/microsoft/vscode/issues/111350
@bpasero so I suggest that the fix should be done in the titlebarPart and that you should only get the `remoteName` if you are in remote.

**Comment by bpasero** [comment]
@isidorn @aeschli please let me know how to do that given our virtual folder support. I think checking for `this.environmentService.remoteAuthority` is no longer good given I might be connected to virtual folder without remote authority?

**Comment by isidorn** [comment]
Maybe this could work 
```
const remoteEnv = await this.remoteAgentService.getEnvironment();
if (remoteEnv) {
 ....
```

@aeschli might know a better way.

**Comment by bpasero** [comment]
I follow what the remote indicator seems to be doing now but feel this is code that could be made reusable:

https://github.com/microsoft/vscode/blob/c9e8dff24c4902ef6779182bbf257350014c8739/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L285-L293

**Comment by isidorn** [comment]
@eamodio can you please verify this? Thank you

**Comment by eamodio** [comment]
Looks good!
