### ISSUE TITLE
Test: terminal tab status

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122241]
Refs #120583

- [x] macOS @egamma
- [x] linux @roblourens
- [x] windows @eamodio 

Complexity: 3

Authors: @tyriar, @meganrogge

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122241%0A%0A)

---

The terminal now has the concept of "statuses", which are states the terminal can be in temporarily. Here are the implemented statuses and how to test them:

- Relaunch needed status (⚠️)
  - Open a terminal
  - Toggle auto attach
    - verify the warning status icon appears next to tabs for which the associated terminal has had input and they're colored yellow
    - verify the tab labels are unchanged for terminals that haven't had input (which have seamlessly relaunched)
    > note that relaunching terminals manually on windows might take down the pty host, so refrain from doing that until the below section 😄 
- Disconnected (🔌), **you can only test this on Windows**, this happens when the Pty Host goes down
   - type in a terminal
   - toggle auto attach
   - manually relaunch (by hovering and clicking relaunch)
   - ~ 12 seconds later you should see a notification indicating the pty host has gone down
   - verify that the disconnected status icon appears on or as the label for the terminals and they're colored red
   - task terminals should have a message saying the process exited and you can press any key to close it
- Bell status (🔔), **you can only test this on mac or linux**
  - Enable the bell via the `terminal.integrated.enableBell` setting
  - Activate the bell on your shell, for example `tput bel` and some shells will trigger the bell when you hit the boundaries of your prompt or press tab
  - verify that the bell status icon appears when activated and disappears after `terminal.integrated.bellDuration` milliseconds and changing that value is reflected the next time

**Comment by roblourens** [comment]
I like having the actions in rows lined up vertically, so how about moving the badge to the left so it doesn't shift the actions? It could take the place of the terminal icon on the left. Just a suggestion.

**Comment by Tyriar** [comment]
@roblourens we use the decorations service, so that would be a request for Joh and apply to all trees/lists.
