### ISSUE TITLE
Link highlighting makes it hard to see underscores

### ISSUE THREAD

**Issue by entr0cks** [Microsoft/vscode#12226]
A link's underline is masking underscore symbols.
Requesting a setting to change link decoration (or to have a link's underline removed while hovering over it).

Having links highlighted in some other way would offer a better overview of link's that have one or more underscores in them.
- VSCode Version: 1.5.2
- OS Version: Windows 10 Pro 1607

Happened in a JavaScript file: request.get('http://localhost:11590/user/_design/user', next);

**Comment by alexandrudima** [comment]
@bgashler1 Do you know of some CSS trickery that might help here?

**Comment by bgashler1** [comment]
@alexandrudima there is no way to modify the offset of `text-decoration: underline` property, which is frustrating.  But what I and others will sometime do is use `text-decoration: none` and then apply a `border-bottom: 1px solid white` like so

![screen shot 2016-09-20 at 1 47 18 pm](https://cloud.githubusercontent.com/assets/11839736/18688341/cc691b32-7f38-11e6-891e-cecbfb7523d9.png)

**Comment by alexandrudima** [comment]
Using borders causes more issues than originally thought, therefore rolling back to using text-decoration:underline.

We need to think of a different approach.

**Comment by sgronblo** [comment]
Could you at least just put in an option to turn it off completely while you are coming up with the different approach?

**Comment by zo** [comment]
A future solution would be to use `text-underline-position: under`.
There is also `text-decoration-skip: ink` which look good but is probably less readable.
examples: https://codepen.io/zombectro/pen/VWOPpp

It is available without flags or prefixes in Chrome 59, which will be included in the next electron release.
https://github.com/electron/electron/pull/9946

**Comment by alexandrudima** [comment]
Since a couple of milestones, there is `"editor.links"` which can be configured to `false` to completely disable link detection.

**Comment by alexandrudima** [comment]
Let's continue tracking in #3476
