### ISSUE TITLE
"Break on uncaught exceptions" breaks in module_job instead of my code

### ISSUE THREAD

**Issue by DawnPaladin** [microsoft/vscode#122246]
Issue Type: <b>Bug</b>

Hello! I'm writing a node.js program. When I tick the "Breakpoints: Uncaught exceptions" box and run my program, VSCode opens a file named "module_job", which I didn't write and am not familiar with, and puts a breakpoint there. I would much prefer that VSCode put a breakpoint at the place in my code that caused the error. Can you help?

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7da1ab90-b9cb-48ef-898b-630929f68b9d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks-statusbar|hed|0.1.0
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by DawnPaladin** [comment]
Here's the Call Stack pane:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/5524469/116159722-58dbf180-a6b6-11eb-910c-77d84cd773c0.png">

My program has very few dependencies - just svg.js, svgdom, and xml-js. I'm running it with `node .`.

Here's the error:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/5524469/116160037-e6b7dc80-a6b6-11eb-8f5c-de487fef5eca.png">

**Comment by DawnPaladin** [comment]
Here's something weird. If I try to debug by clicking the "Launch program" button in the Debugger pane, MacOS's "Save as" dialog comes up, asking where I want to save a copy of module_job to my filesystem. I don't know why it thinks I would want to do that.

Here's a copy of my launch.json, in case that helps.

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"skipFiles": [
				"<node_internals>/**"
			],
			"program": "./index.js"
		}
	]
}
```

**Comment by connor4312** [comment]
This looks like it's working as it's intended. From the call stack I see that your code is calling into the `sentence-diagrammer` module, which in turn in throwing the error. Pause on Exceptions by default pauses on the location where the exception/rejection is initially thrown or uncaught.

If you'd like, you can add that module (or all your node modules) to the `skipFiles`. This prevents you from debugging into them and will also cause the pause location to be nearest non-skipped stackframe.

Let us know if you have any other issues.

**Comment by connor4312** [comment]
Thanks for the issue, this looks like a bug in Node.js. Please follow https://github.com/nodejs/node/issues/38439 for updates.

**Comment by DawnPaladin** [comment]
I'll watch that issue for updates. Thank you so much! 🙇
