### ISSUE TITLE
Double click to create new terminal group should focus it?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122297]
I think when I double click on the empty space below the tabs and a new terminal group opens, I would expect that group to have focus.

Unrelated: I see a `%` sign appearing for new terminals create like that:

![image](https://user-images.githubusercontent.com/900690/116222261-b9b70880-a74e-11eb-9180-231e52b8f7ab.png)

**Comment by Tyriar** [comment]
% tracked in https://github.com/microsoft/vscode/issues/119204
