### ISSUE TITLE
Test: Terminal API message

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122215]
Refs #120368

- [x] macOS @sbatten
- [x] linux @alexdima 
- [x] windows @stevencl 

Complexity: 2

Authors: @tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122215%0A%0A)

---

Using the `vscode-extension-samples/terminal-sample`, provide `message` as an argument to `createTerminal`. Verify that you see this text when you create an extension terminal.

Ensure you have [enabled proposed API](https://code.visualstudio.com/api/advanced-topics/using-proposed-api).

**Comment by alexdima** [comment]
This did not work for me. Here is what I tried:

![image](https://user-images.githubusercontent.com/5047891/116250536-18d84580-a76e-11eb-9f28-24815aebef0b.png)

I could not find `initialText` in the API, so I tried with `message`. Maybe someone else can try, I could not get this to work:

![image](https://user-images.githubusercontent.com/5047891/116251183-baf82d80-a76e-11eb-970d-65da07529822.png)
