### ISSUE TITLE
emmet snippets.json Error while parsing

### ISSUE THREAD

**Issue by asgarchitects** [microsoft/vscode#122205]
- VS Code Version:  1.55.2
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Launch VS Code 
2. Error message :  "Error While parsing the file file://..."

in 1.55.2 the following messages got reported :
Missing property "body".
Property snippets is not allowed.

`
{
    "html": {
        "snippets": {
            "??": "<?php ?>",
        }
    },
    "css": {
        "snippets": {
        }
    }
}
`

1.56.0-Insiders  build using the snippet found on https://code.visualstudio.com/docs/editor/emmet

this message is returned
"Found error PropertyNameExpected while parsing the file file:///c%3A/Users/..../AppData/Roaming/Code/User/snippets/emmet/snippets.json at offset 266"

**Comment by rzhao271** [comment]
Yep, I changed the error handling to report a more detailed message; that part is as designed.
You have an extra comma after the `"<?php ?>"` part.
I also just noticed that the `??` snippet doesn't seem to work for me even after fixing up the file, but I also don't remember seeing any default abbreviation contain the `?` character, so I'm guessing the extension currently doesn't support abbreviations containing that character right now.
