### ISSUE TITLE
[Getting Started] selectTask telemetry event stopped working

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#122256]
Probably a regression from #120050.

**Comment by JacksonKearl** [comment]
Ah, so we renamed everything from `task` to `step` as `task` is overloaded in vscode to typically refer to tasks.json tasks: https://github.com/microsoft/vscode/issues/120049

I'll go ahead and change the telemetry event back to `task` so we don't have to deal with two potential names.
