### ISSUE TITLE
Getting started images show up as blank

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122218]
![image](https://user-images.githubusercontent.com/35271042/116125219-11d00b00-a67a-11eb-8634-d27b8d8ff43a.png)

Version: 1.56.0-insider
Commit: 633562da380f9161ea2fd783e561eed508cfbbea
Date: 2021-04-26T06:57:19.868Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

**Comment by JacksonKearl** [comment]
Moved from src to srcset, having spaces in the string broke srcset.

**Comment by JacksonKearl** [comment]
Still broken, applying more targeted fix.
