### ISSUE TITLE
Terminal tabs: allow to join tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122286]
Would be nice if the context menu offered me a way to merge tabs into a group:

![image](https://user-images.githubusercontent.com/900690/116215889-5e821780-a748-11eb-8484-59a2e1cdd0c9.png)

Another solution could be to allow for drag and drop.

**Comment by Tyriar** [comment]
Drag and drop was a stretch goal for this and probably coming next month, good idea with the context menu entry though.
