### ISSUE TITLE
Test: Terminal profile improvements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122248]
Refs #119366, #120366

- [x] macOS @sandy081
- [x] linux @connor4312 
- [x] windows @rebornix 

Complexity: 3

Authors: @tyriar, @meganrogge

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122248%0A%0A)

---

[Terminal profiles](https://code.visualstudio.com/updates/v1_55#_terminal-profiles) were introduced last iteration but the "default terminal" was still powered by the `shell.platform` and `shellArgs.platform` settings. This iteration we've added the new `terminal.integrated.defaultProfile.platform` settings which allows setting of a profile name to use that profile. It's also hooked up to the select default profile command such that when you change it there it will create the profile if necessary and then set the default.

In addition to this there is also now support for `icon` and `env` in profiles.

To test:

- Experiment with various configurations of shell/profiles/defaultProfile, ensure the fallback logic makes sense (when `defaultProfile` is present, `shell`/`shellArgs` is ignored).
- Configure profile(s) in your settings and set the default profile to it.
- Set the default profile via the select default profile command, try setting to entries in both the `profiles` and `detected` and also try pressing the configure button.
- Check that icons that show up in default profiles make sense, configure your own.
- Configure `env` in profiles.

**Comment by connor4312** [comment]
I was unable to test completions due to https://github.com/microsoft/vscode/issues/122466, but otherwise lgtm
