### ISSUE TITLE
Experimental hover: hide on click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122288]
I would try to make the experimental new hover behave more like native hovers. They for example hide on click, we do not.

![image](https://user-images.githubusercontent.com/900690/116216811-5080c680-a749-11eb-85db-54ba885fb27a.png)

I think the hover should only show for when the mouse "hovers" over the item, not when anything is done with it.

**Comment by sandy081** [comment]
This is implemented already. Hence closing it.
