### ISSUE TITLE
Panel titles jump on hover in high contrast theme

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122289]
![recording (1)](https://user-images.githubusercontent.com/900690/116217133-a48bab00-a749-11eb-855d-0a5fa8a989a6.gif)

**Comment by isidorn** [comment]
I can reproduce this.
There might already be an issue for this, but @sbatten might know better
I no longer own this code, thus unassigning myself, however feel free to assign me back if you do not have time to look into this @sbatten

**Comment by sbatten** [comment]
This was introduced this milestone and I have made no changes here. However there were many changes with action hover feedback from @joaomoreno
