### ISSUE TITLE
Test restricted workspace settings

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#122209]
Ref #120860 

- [x] windows @joaomoreno
- [x] mac @lramos15
- [x] linux @deepak1556

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122209%0A%0A)

---

**Note:** Use `security.workspace.trust.enabled` setting to enable workspace trust feature.

### Test defining restricted workspace settings

- Write a simple extension that defines a configuration in its package.json and reads its value when a command is executed
Eg: 
```json
"capabilities": {
		"untrustedWorkspaces": {
			"supported": "limited",
			"restrictedConfigurations": [
				"testExtension.restricted"
			]
		}
	},
	"contributes": {
		"configuration": {
			"title": "test",
			"properties": {
				"testExtension.restricted": {
					"type": "string",
					"scope": "resource",
					"default": "defaultValue"
				}
			}
		}
        }
```

```ts
export function activate(context: vscode.ExtensionContext) {
	vscode.commands.registerCommand('testExtension.helloWorld', (arg) => {
		vscode.window.showInformationMessage(vscode.workspace.getConfiguration().get('testExtension.restricted') || '');
	});
}
```
- Validate the documentation for `restrictedConfigurations`
- Run this extension in a trusted workspace. 
  - Open workspace settings and update the value of the setting `testExtension.restricted` 
  - Make sure `testExtension.helloWorld` command prompts the workspace value
  - Make sure `vscode.workspace.getConfiguration().inspect('testExtension.restricted')` has workspace & workspace folder value

- Run this extension in an untrusted workspace (Use same workspace and change it to untrusted - by opening the workspace trust editor and removing the folder from trusted paths)
  - Make sure `testExtension.helloWorld` command does not prompts the workspace value (prompts either default value or user value if defined in user settings)
  - Make sure `vscode.workspace.getConfiguration().inspect('testExtension.restricted')` does not has workspace & workspace folder value
  - Run this extension in a multi-root workspace that includes this folder and validate all above 2 points are applied. In addition 

### Test restricted workspace settings UI in Untrusted workpsace

- Test workspace trust editor shows a link with number of workspace settings which are not applied
- Clicking on this link opens settings UI filtered with restricted settings in workspace settings
- Make sure you cannot edit them
- Validate the information shown makes sense and helpful
- Clear the filter in settings search box. Make sure those restricted settings which are modified in workspace settings are shown on top under `Workspace Trust` category
- Make sure applying the filter `@tag:requireTrustedWorkspace ` shows all list of restricted settings requiring workspace trust.
- Open workspace settings.json file and make sure a warning is shown for the restricted setting if modified in the file. You can also find a light bulb (quick fix) that provides an action to open workspace trust editor
- Make sure in workspace settings.json file you do not get IntelliSense for restricted settings
- Validate all above points are applied in a multi-root workspace that includes this untrusted folder

**Comment by deepak1556** [comment]
`vscode.workspace.getConfiguration().inspect('testExtension.restricted')` provided undefined as `workspaceFolderValue`. Had to inspect the value per folder to verify, is that the intended way to do it ?

```
let folders = vscode.workspace.workspaceFolders;
folders.forEach(folder => {
   vscode.workspace.getConfiguration('testExtension', folder.uri).inspect('restricted'); // workspaceFolderValue is defined here
});
```

**Comment by sandy081** [comment]
Yes, restricted setting value shall be undefined for each workspace folder if workspace is not trusted even if value is defined in the workspace folder.
