### ISSUE TITLE
Testing API finalization

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122208]
Separating from https://github.com/microsoft/vscode/issues/107467 to have a focused issue. These APIs will be finalized (ctrl+f for 122208 if this moves from additional changes in the file): https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L1972

**Comment by matepek** [comment]
```
export function createTestItem<T = void, TChildren = any>(options: TestItemOptions): TestItem<T, TChildren>;
```
any meant to be T I guess.

**Comment by matepek** [comment]
Feature request: 
- tags: `TestItem { tags?: string[] }`

How I imagine:
- Testsuite1
  - Test1 [tag1]
  - Test2 [tag1] [tag2]

**Comment by connor4312** [comment]
Test items have a `description` for this purpose (though it is not curently shown in UI)

**Comment by matepek** [comment]
When `TestItem` is disposed the `data` might wanna be `dispose`d too.
It can be managed in another way but it just seems convenient in case someone would like to create a disposable `data`.

**Comment by matepek** [comment]
> Test items have a description for this purpose (though it is not curently shown in UI)

Okay thats something but one point users might wanna do filtering by tags. In that case if I only use it as a string in the description:
- search should include the description
- search should treat space as `.*` because item with `[a] [b] [c]` should be a part of the result if we search for `[a] [c]`.

Well I didn't go to details. I'm just hoping it's clear. Let me know if you need clarification.

It would be a nice feature I believe.

Question: when can I modify the error, label, description, etc fields? Will they be reflected automatically?

**Comment by matepek** [comment]
Does the  `readonly uri: Uri;` in `TestItem` has to be readonly? Is there any advantage in vscode side?

**Comment by connor4312** [comment]
>  Question: when can I modify the error, label, description, etc fields? Will they be reflected automatically?

Yes

> Does the readonly uri: Uri; in TestItem has to be readonly? Is there any advantage in vscode side?

It simplifies things. We didn't find many use cases where the URI would change without tests being recreated/re-read

**Comment by matepek** [comment]
>> Does the readonly uri: Uri; in TestItem has to be readonly? Is there any advantage in vscode side?

> It simplifies things. We didn't find many use cases where the URI would change without tests being recreated/re-read

Here is one but I would say pretty rear: User moves tests from test1.cpp to test2.cpp which are bundled to the same executable. after recompilation the URI will change of course. With the current API I have to check the URI too and if there is a need for update I have to dispose and recreate. It's not a biggie though just for the record.

How about my previous question: What if I don't have URI? What should I pass? Null?

**Comment by connor4312** [comment]
URIs are required on all tests. If you don't have a specific file, you can pass in the URI to a relevant directory instead.

**Comment by matepek** [comment]
> URIs are required on all tests. If you don't have a specific file, you can pass in the URI to a relevant directory instead.

Even if the only relevant I can figure out is the workspaceFolder itself?

How will that effect the UX?

**Comment by connor4312** [comment]
Well, if you have no location for a test we will not be able to show things like editor decorations, "go to test" will not work, etc. The experience is significantly less useful without having URIs for tests.

**Comment by matepek** [comment]
Okay. As I said it is a really valid situation/use-case when I won't have URI.
Another example:
- executable without source file at all.
- google test v < 1.8 doesn't provide the info
- ...

**Comment by connor4312** [comment]
The URI is now optional

**Comment by jdneo** [comment]
Some feedback about showing the test message when I was trying the new API.
![image](https://user-images.githubusercontent.com/6193897/118236961-4d1b6800-b4c9-11eb-8f46-ccfdf9d9e831.png)

In the hover box, looks like the test message is not using all the horizontal spaces. Meanwhile, if the test message is a Markdown string, it will show as `[Object Object]` inline.

BTW, by saying  `finalization`, does that mean the listed API will go to stable VS Code?

**Comment by connor4312** [comment]
> if the test message is a Markdown string, it will show as [Object Object] inline.

Thanks, fixed

> In the hover box, looks like the test message is not using all the horizontal spaces

This uses the default VS Code hover, please open a separate issue for that!

> BTW, by saying finalization, does that mean the listed API will go to stable VS Code?

Yes

**Comment by jdneo** [comment]
Created #123927.

BTW, where can I see the test execution duration in the UI? (Maybe I missed somewhere)

**Comment by connor4312** [comment]
Currently test execution duration isn't shown, but it will be soon.

**Comment by connor4312** [comment]
Duration will be shown in the test explorer view as of the next Insiders

**Comment by Razzeee** [comment]
Will this make it into 1.57? I'm assuming we could start shipping our extensions with https://marketplace.visualstudio.com/items?itemName=ms-vscode.test-adapter-converter then?

**Comment by connor4312** [comment]
This got deferred until 1.58 due to the number of other items in flight for 1.57

**Comment by jdneo** [comment]
Is it possible to trigger a test run from file explorer? Seems like the API `test.runTests` is not ready yet?

**Comment by connor4312** [comment]
Please note the following significant changes coming to the testing API in the next Insiders; see the commit message for more details: https://github.com/microsoft/vscode/commit/186e565ec0eaee72c980ffe546ec3e4cb3ed1635

Any further breaking changes that happen will continue to be announced in this thread. (And they will be backwards-compatible over a few Insiders versions when feasible.)

cc @jdneo @luabud  @connectdotz @JustinGrote @karthik20 @mxschmitt

**Comment by luabud** [comment]
cc @karthiknadig

**Comment by JustinGrote** [comment]
@connor4312 just a quick feedback that this is a far more intuitive API, the last one took a *lot* of headscratching on my part to figure out as a typescript newbie. Thank you :)

**Comment by jdneo** [comment]
I haven't dig deep into the new APIs but so far it looks good to me, since:

- Currently it looks like a pure pushing based API, compared to previous mixed pulling and pushing, the new one is much more easy to understand.
- Now the extension just needs to maintain one tree, instead of a forest(previously, they are workspace folder roots and text document roots)

Thanks @connor4312 !

**Comment by connor4312** [comment]
Further changes can be found in https://github.com/microsoft/vscode/commit/df5cd477841c80788d881374ac906a1ed517b9ff -- adapting to these should take no more than ~20 minutes, and quite possibly less depending on complexity. Please let me know if you have questions or find things that are unclear.

**Comment by JustinGrote** [comment]
@connor4312 I was going to ask why a lot of those tokens didn't just get wired up as disposables in the extension context, guess you had same thinking :).

I think the new terminology is more clear, as in my code every time I set pending I had a comment that said "this means the controller will try to refresh the children" :)

**Comment by JustinGrote** [comment]
@connor4312 after the last update, Refresh Tests seems to be broken. I was expecting it to call resolvechildhandler on my root again but it doesn't seem to do anything. Is there a new behavior I should be looking for?

![image](https://user-images.githubusercontent.com/15258962/123315108-314fac80-d4e0-11eb-932c-be334bf4d112.png)

**Comment by JustinGrote** [comment]
For anyone else who is interacting with a program that scans best on a per-file basis, I did things a bit differently than the markdown example. I put my discovery function directly on my TestItem<TestFile> node and then processed the whole file tree from there in one go. I had to make a lookup as my adapter returns strings for parent IDs per the old API to map the test cases to their suites so I didn't have to walk the tree to find them every time.
https://github.com/pester/vscode-adapter/blob/d623ea43750b960121051d49bb16843142459457/src/pesterTestController.ts#L27-L60

Resultant Output for https://github.com/pester/vscode-adapter/blob/d623ea43750b960121051d49bb16843142459457/sample/Tests
![image](https://user-images.githubusercontent.com/15258962/123316641-ed5da700-d4e1-11eb-8822-47337baa6a86.png)

**Comment by connor4312** [comment]
> Refresh Tests seems to be broken. I was expecting it to call resolvechildhandler on my root again but it doesn't seem to do anything. Is there a new behavior I should be looking for?

Yea, I think we'll remove the built-in "refresh" action and instead let extensions do it if they want to. For example in the test adapter converter I have an inline "refresh" button shown on the first item: https://github.com/microsoft/vscode-test-adapter-converter/blob/main/package.json#L47-L52

**Comment by connor4312** [comment]
We've made change in https://github.com/microsoft/vscode/commit/6a76c62232208f54bc85f22572013b382e39cf9e to remove the `data` from test items. There is a backwards-compatibility shim in there for the moment, but it will be removed next Monday. Migration time for this should be in the range of 5-15 minutes.

**Comment by JustinGrote** [comment]
@connor4312 Is weakmap the ideal approach or is there a better way to "type" the actual managed TestItem generics coming from createTestItem, for purposes of deciding what kind of test node it is in the child resolver handler?  Maybe an additional option for a "type hint" string or something, that just gets added as a readonly property?

**Comment by JustinGrote** [comment]
@connor4312 nevermind, I didn't actually look at the changes, I think I see an approach now, thanks.

**Comment by JustinGrote** [comment]
@connor4312 I don't think testRunRequest got de-genericized in the proposed.d.ts:
![image](https://user-images.githubusercontent.com/15258962/123440657-dffaf800-d587-11eb-9a70-614c5ab7c199.png)

**Comment by connor4312** [comment]
Hm, it should be:

https://github.com/microsoft/vscode/blob/02c07de3af85f257046a0d292b3a6baf2f7f40e2/src/vs/vscode.proposed.d.ts#L1972

**Comment by JustinGrote** [comment]
@connor4312 my bad, I did npm install on my test repo but didn't do it a second time on the sample repo, it's all good.

**Comment by jdneo** [comment]
@connor4312  There is a menu item called `Show in active file only`

![image](https://user-images.githubusercontent.com/6193897/123584511-553c1800-d796-11eb-94b1-4b2b5cd6898b.png)

What's the usage for this button? It seems that nothing changes when I enable/disable it.

**Comment by connor4312** [comment]
In the next Insiders, we update the test run API to match the one proposed in https://github.com/microsoft/vscode/issues/127096#issuecomment-868839093. Expected migration time is about 5-10 minutes:

1. Instead of setting the `runHandler` on the TestController, called `createTestRunConfiguration` and set the run handler there
2. Instead of using `TestRunRequest.debug`, create a separate debug configuration that runs tests in debug mode
3. Pass in a label when calling `createTestController`

Here's an example of the conversion process: https://github.com/microsoft/vscode-test-adapter-converter/commit/197021c010f01d93ef69eb919ecc0355f75f6757

**Comment by connor4312** [comment]
We've made some further changes in https://github.com/microsoft/vscode/commit/581ff12c395d51ed45ba6280429b226293acad02, resulting from discussion in  #126987.

Migration for these changes should take about 15-20 minutes.

- `createTestItem` no longer takes a parent. Instead, it creates a free-
  floating test item, which can be added as a child of a parent.
- The `TestItem.children` is now a `TestItemCollection`, a set-like
  interface that also allows replacing items (intelligently diffing
	them internally) wholesale. This removes the need for the "generation
	counter" used in samples previously.
- There is no longer a `root` on the test controller, but instead an
  `items` property which is the same `TestItemCollection`
- The `tests` in the `TestRunRequest` has been replaced with an `include`
  property. If undefined, the extension should run all tests. (Since
	there is no longer a root to reference).

Here's some example migrations:

- https://github.com/microsoft/vscode-extension-samples/commit/3fad3d66c110107946f827daedd7759cad7c4358
- https://github.com/microsoft/vscode-selfhost-test-provider/commit/3aff74631605dfd4120b98014f54ff744f292fe0

**Comment by jdneo** [comment]
@connor4312 Some question about the new API change:

1. It says: `If undefined, the extension should run all tests. (Since
there is no longer a root to reference).`, but when triggering `Run All`, the include is not undefined, but a `implicit` root node, which seems be set by VS Code:
![image](https://user-images.githubusercontent.com/6193897/125887254-e1ec04f5-e9c6-432f-83c6-1e9d2e81074c.png)

2. Now the test controller has `items` field to hold the test items. And each test item also has the `children` to hold its children item. Then, should all the children also be added into the test controller's `items`? Or it can be decided by the extension itself

**Comment by firelizzard18** [comment]
@connor4312 How do I indicate which tests a run configuration applies to? Previously, I could set `TestItem.runnable` to false to indicate that a test item could not be executed, but it appears that is no longer possible with run configurations.

I understand that the extension controls what is and is not executed. But on the UI level, there are tests that should not have a run button next to them in the explorer.

**Comment by connor4312** [comment]
@jdneo fixed (1).  "Or the items field of test controller is just used to store the direct children of the implicit root node?" <- this

@firelizzard18 can you explain the use case that you're looking at a little more? The scenario I'm aware of where individual run actions were not relevant were mostly on "subtests" which cannot be run individually -- the thought was that for these it would be okay behavior for the extension to just run the containing unit test. Is that what you're thinking of, or do you have a different scenario?

---

There are a couple more changes coming into the next Insiders. The changes for these should take <= 5 minutes:

- "Run configurations" have been renamed to "run profiles", and the associated types and methods have been updated.
- The `TestItemCollection` has been tweaked to better match other collections. Instead of an `all` getter/setter, it now has a `set` method, a `forEach` method, and is Iterable. For example, to get an array of all items you can use `Array.from(item.children)`. The `remove` method has been renamed to `delete`
- Test IDs are no longer required to be globally unique -- only unique among the peers in their collection. This is not breaking, but fyi.

Here's an example of a migration: https://github.com/microsoft/vscode-extension-samples/commit/547dd0bb3550a556ad5ed77ab627e7ef9e0eaaf9
-

**Comment by connor4312** [comment]
There is one more small break for today, the resolveChildrenHandler may, similarly to the RunTestsRequest, be called with undefined to request the top-level items be expanded. We'll also be more conservative about calling this than we were previously.

https://github.com/microsoft/vscode/blob/cf77875d5c3aac2a7fe83e64c4310ab27213d512/src/vs/vscode.proposed.d.ts#L2034

**Comment by firelizzard18** [comment]
@connor4312 The scenario I am running into is subtests, as you describe. I disagree that "it would be okay behavior for the extension to just run the containing unit test". As a user, if I click the run button on a sub test, I expect only that sub test to run. I can think of scenarios where it might be particularly relevant, but the real argument is that the UI implies a behavior different from the actual behavior. If a sub test can't be run separately, it shouldn't be runnable in the UI.

I can also imagine a non-sub-test scenario. One of the examples involved run configurations for running tests on various browsers. If I was writing such an extension, I might choose not to expose a Firefox-specific run configuration if Firefox is not installed. In that case, any Firefox-specific tests should not be runnable.

Here's another scenario: Go has a notion of build tags that can be used to write OS- or arch-specific code. A Go project may define OS- or arch-specific tests. In that case, I may want to include tests in the UI that can't be run on the current platform. Beyond that, Go allows developers to use custom build tags, such as `gtk` or `qt`. If a project defined tests specific to a custom build tag, it would be useful to define additional run profiles for those tags. But if I'm working on such a project and I don't have GTK or QT installed, and thus don't have a run profile that includes those tags, those tests shouldn't be runnable.

**Comment by jdneo** [comment]
In Java there also have scenarios for `subtests` (parameterized tests)

As a user, I agree with @firelizzard18. If a test item is not runnable, then it should not have the run option for it. Running the containing unit test will work, but it might `surprise` the user because the wrong expectation they set when they see the run button.

**Comment by JustinGrote** [comment]
Was able to update without much issue, but this runhandler conversion hurts my brain so much.

https://github.com/microsoft/vscode-test-adapter-converter/commit/197021c010f01d93ef69eb919ecc0355f75f6757?branch=197021c010f01d93ef69eb919ecc0355f75f6757&diff=split

Did this instead:

```
        testController.createRunProfile('Run',TestRunProfileGroup.Run, this.debugHandler, true)
        testController.createRunProfile('Debug',TestRunProfileGroup.Debug, this.runHandler, true)
...

    private async debugHandler(request: TestRunRequest) {
        this.testHandler(request, true)
    }
    private async runHandler(request: TestRunRequest) {
        this.testHandler(request, false)
    }

    /** The test controller API calls this when tests are requested to run in the UI. It handles both runs and debugging */
    private async testHandler(request: TestRunRequest, debug: boolean) {
    ...
```

**Comment by JustinGrote** [comment]
Also having trouble testing, the proposed.d.ts don't seem to be in this insiders, tried a refresh, guess I'll test tomorrow.
![image](https://user-images.githubusercontent.com/15258962/126043273-4f66deb3-3eee-4c08-9136-55c3b76e1d51.png)

**Comment by connor4312** [comment]
@JustinGrote Insiders doesn't get released on Friday nights, it'll be out Monday morning.

I did it that just to force you to learn more js/ts 😉 It provided a minimal conversion, though [higher order functions](https://eloquentjavascript.net/05_higher_order.html) are more common in client-side code.

---

Thanks for the feedback on runnability. I'm considering something like this, but will continue to think it over:

> One solution to this that I think could work decently well is having a run configuration be able to define one (or more) "tag" strings, and allow tests items to have an array of tag strings. For any configuration where tags are defined, the editor would only apply that to test items that have the same tag. We had a request for tagging before as an organizational tool, but that could also work for this.
 
So for example you could have a custom "runnable" tag, and the presented Go scenario could have a "runnable-darwin" tag.

**Comment by firelizzard18** [comment]
@connor4312 That would work for me.

**Comment by connor4312** [comment]
As we near the end of the iteration, the the test APIs we intend to finalize have been moved to this section (ctrl+f for 122208 if this moves from additional changes in the file): https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L1972

Additionally there were a few changes today, mostly renames:

- `vscode.test.*` is now `vscode.tests.*` (like `vscode.notebooks.*`, which had a similar rename a while ago)
- `TestItemCollection.set` is now `TestItemCollection.replace` (`set` may lead to compile errors as reserved keyword)
- `createTestItem` is back on the controller
- `TestProfileRunGroup` is now `TestProfileRunKind` (although the UI does grouping, the intent expressed in the API is of a type or kind of profile), and the property on the profile was renamed from `group` to `kind`
- `TestRunState.Unset` has been removed, since it isn't used in our current APIs. Additionally, `TestMessageSeverity` has been removed since we've only seen these to report errors. Both these could be brought back if there's need or use case for them.

Example of a migration: https://github.com/microsoft/vscode-test-adapter-converter/commit/6805807c57e25b71797e05c2e9c0131673bbde0a

**Comment by firelizzard18** [comment]
@connor4312 For Go, I append a message for all test output that can be linked to a specific file. That means, output of the form `file.go:13: foo bar` gets appended. This is not always error messages. I only ever used a severity of info or error, but a way to mark an appended message as an error or not an error is valuable.

**Comment by jdneo** [comment]
@connor4312, is there anyway to quickly get the size of the `TestItemCollection`?

Background: when a test item needs to be removed, and its parent has no other children, I want to remove its parent as well.

**Comment by jrieken** [comment]
> This is not always error messages. I only ever used a severity of info or error, but a way to mark an appended message as an error or not an error is valuable.

The question we're having is about the relation of `TestMessageSeverity` and `TestResultState`, esp what does it mean when the result state is `Passed` but the message is `Error` and vice versa or different combinations like queued and warning etc

**Comment by connor4312** [comment]
We discussed this in our call this morning. We're looking at changing the TestRunResult to remove `setState` and the  `TestRunState` enum entirely, and instead having a method-based API like this:

```ts
export interface TestRun {
	enqueued(test: TestItem): void;
	started(test: TestItem): void;
	skipped(test: TestItem): void;
	failed(test: TestItem, message: TestMessage | TestMessage[], duration?: number): void;
	passed(test: TestItem, duration?: number): void;
```

This is similar to notebook cell execution. In this scenario, TestMessages are tied _only_ to a test failure, and are given only to tests that fail. We propose for next month adding an optional test to associate `appendOutput` with, for example:

```ts
export interface TestRun {
	appendOutput(output: string, test?: TestItem): void;
```

This allows diagnostic log output to associated with a test, regardless of its passed or failed state.

Please let me know what you think of this proposal. I plan to implement it this afternoon pending feedback.

**Comment by connectdotz** [comment]
@connor4312 if I understand your proposal correctly, wondering what would happen if a TestItem occurred in multiple of these calls? If the purpose of splitting `setState()` to multiple functions mainly to take conditional arguments by state, another alternative to consider is a typed-state, such as: 
```
type RunState = 
| {state: 'running', output?: string}
| {state: 'skipped', output?:string}
| {state: 'failed'; message: TestMessage|TestMessage[]; duration?:number; output?: string}
| {state: 'passed'; duration?: number; output?: string}
...
interface TestRun {
  setState(item: TestItem, state: RunState);
  ...
```
typescript will enforce the proper arguments while the API can remain simple and intuitive, IMHO...

**Comment by firelizzard18** [comment]
@connor4312 I want to attach output to a specific location, as in the `location` property of `TestMessage` - maybe `appendOutput(output: string, location?: Location, test?: TestItem): void`?

For more context: When I am running tests to debug a function, I often use Go's test logging facilities to give me more information. This isn't a great example (and I've removed most of the cases for clarity), but here's a screenshot of how it works with `TestMessageSeverity` and `appendMessage`:

![image](https://user-images.githubusercontent.com/879055/126558508-748145c0-47ff-4fe9-9f68-b82cf93923d5.png)

If I introduce an error, with the previous API this is what I see:

![image](https://user-images.githubusercontent.com/879055/126559648-6e2cd503-b881-4ac3-8db6-25220213d862.png)

I want to retain this. That is, I want to be able to log non-error output that is attached to a specific location (and test), as well as error output that is attached to a location.

I like the idea of message severity, and I can imagine reasons for wanting to log warning messages that do not cause the test to fail. But even if you kept that, I'm unlikely to support anything other than Info and Error, due to limitations of Go.

Personally, I prefer `TestRun.setState` over specific methods, but that's just a stylistic thing.

Side note: the UX isn't great when a bunch of test messages are stacked on top of each other:

![image](https://user-images.githubusercontent.com/879055/126562862-f94e3e1f-0032-4b99-bb21-6936c5ea9918.png)

![image](https://user-images.githubusercontent.com/879055/126563343-c7590562-297c-4438-8b0c-c3f6daee7903.png)

I would prefer to see all the messages for a given location during a given test run grouped together. I can do this myself in the extension, but I wonder how much utility there is in listing each message individually.

![image](https://user-images.githubusercontent.com/879055/126563556-d2ce6580-6fc6-4bf8-952f-bf934310fb79.png)

**Comment by connor4312** [comment]
Thanks for the feedback. Yea, the notion of stacked test messages in the peek is not particularly attractive or intuitive. That was another potential distinction we discussed when considering messages that indicate failure versus general log messages. I'll create an issue for message discussion separately from this issue. The decoration you showed in your first screenshot is an attractive experience that I'm interested in preserving to some degree, but I don't know what that will look like yet.

---

The [aforementioned changes] have now been made:

- `setState` is split to specific methods for each state
- `TestController.resolveChildrenHandler` is now just `TestController.resolveHandler`

**Comment by firelizzard18** [comment]
@connor4312 Is this something that can be tested in stable VSCode by setting `--enabled-proposed-api`? Or is this insiders-only? I ask because @hyangah, part of the team responsible for the official Go extension, was wondering if it would be possible to test with the nightly build of the Go extension https://github.com/golang/vscode-go/issues/1579#issuecomment-884532554.

**Comment by connor4312** [comment]
We only ship stable ~once per month, so the latest set of API changes will not be in stable, you can only test the old API. The next stable release where these changes are included should arrive when this comment is two weeks old.

**Comment by firelizzard18** [comment]
@connor4312 Is there any replacement for `TestResultState.Errored`? I used that if tests failed to compile.

**Comment by connor4312** [comment]
Would setting `TestItem.error` be appropriate for that use case?

**Comment by JustinGrote** [comment]
@connor4312 got a chance to implement today, conversion wasn't too bad. I did have rewrite my "tree walker" function to find all the tests included when a "header" , I really feel this is something that should be part of the API of `TestItemCollection`, either as a `recurse` boolean switch to `forEach`, or a separate method (`walk` or something), and could be applied to the new setstate methods to waterfall down if state is set on a parent testitem.

**Comment by firelizzard18** [comment]
@connor4312 That's better than nothing, but I preferred the previous UX. It showed `(!)`, which differentiated load errors from test failures: `(x)`. And displaying an error message in the tree view isn't necessarily useful. 1) Only the first line is shown, 2) Go build errors may be multiple lines, and 3) Go build errors are likely already displayed as diagnostics.

**Comment by JustinGrote** [comment]
For anyone else who struggled with the recursive stuff, here's my helper function
```typescript
/** Runs the specified function on this item and all its children, if present */
async function forAll(parent: TestItem, fn: (child: TestItem) => void) {
    fn(parent)
    parent.children.forEach((child) => {
        forAll(child, fn)
    })
}

//Example use to set all test results to running
forAll(testParentItem, run.success)
```

**Comment by jdneo** [comment]
echo to @firelizzard18. Differentiate `errored` and `failed` when setting the test state would be helpful.

The test can be failed due to:

1. The actual result is different from the expected result -- `Failed`
2. Or, the developer is not setup the tests correctly (For example, the JUnit 4 requires the `BeforeAll` method must be static, but developer might forget it) -- `Errored`

BTW, since the TestResultState has `Failed` and `Errored`, but when set the state, we can only set `Failed` looks a little bit strange.

**Comment by connor4312** [comment]
Okay, I'll bring errored back. Thanks for the feedback!

**Comment by JustinGrote** [comment]
@connor4312 the thing I'm most struggling with right now is correlating the tests in the controller with the tests that come back from my adapter. I've been using the id string as a global unique identifier, but now that is only unique to a given `testItemcollection`, so I have to walk the `testController` tree to find the matches.

Here are the util functions I made to handle this, they would be better if testItemCollection had an `every` style method in addition to `forEach`
