### ISSUE TITLE
Settings.json first and second lines not setup correctly

### ISSUE THREAD

**Issue by William1947** [microsoft/vscode#122236]
VS Code with Windows 10

Issue Type: <b>Performance Issue</b>

2 days ago, on startup , I either receive Property Expected or end of file expected, will not sync untill I fix this problem.  I have tried other settings on these two lines but it started with the first line now on both 1st. and 2nd.

**Comment by roblourens** [comment]
Can you share the lines that are giving this error? I don't totally understand.

**Comment by William1947** [comment]
"{windows}"  
"Adjust the zoom level of the window. T"
 sorry, yes the two lines that keep giving my the error's are here, in the json settings they are the first two lines. if someone can copy the two lines so I can compare with mine that would be great.

**Comment by roblourens** [comment]
Is this copied directly from your file? That is not valid json. What are you expecting this to do?

**Comment by William1947** [comment]
I know, but this is the first 2 lines in my settings.json file.  Not sure what happen but it did miss up my codding. that is funny now. I just hope that I can find out what the first two lines are to be and change it.

**Comment by roblourens** [comment]
Not sure how you got that there, but your settings file should be json and follow this pattern

```json
{
  "setting1": "value",
  "setting2": "another value"
}
```
etc

**Comment by William1947** [comment]
Thank you Rob, I will try and see what I can do with this.  Thanks again for your help.
Ron Massey


________________________________
