### ISSUE TITLE
Doesn't use my default branch

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122229]
My default branch is 'main', but I just published https://github.com/roblourens/jupyter-container through the extension, and got 'master'

**Comment by joaomoreno** [comment]
> My default branch is 'main'

How did you configure this?

This should've been fixed already back in https://github.com/microsoft/vscode/issues/105025

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/116298448-54184b80-a751-11eb-891f-507faa4dfd9e.png)

**Comment by joaomoreno** [comment]
Wait but that's the setting on GH. VS Code will pick your local git's configuration: https://git-scm.com/docs/git-config#Documentation/git-config.txt-initdefaultBranch

This now comes as `main` on newer git installations, but for older ones you have to set this up yourself.

**Comment by roblourens** [comment]
Oh, of course this just starts with git init, never mind.
