### ISSUE TITLE
weird syntax highlight with PHP inside Script tags

### ISSUE THREAD

**Issue by rlucasfm** [microsoft/vscode#122222]
- VS Code Version:  1.55.2
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS Version: Microsoft Windows Server 2019 Datacenter 1809 Build 17763.737 (Windows_NT x64 10.0.17763)

Steps to Reproduce:

1. Open any .php code with VS Code
2.  A code like: 
<script>
        let i = <?php echo "2"; ?>;
    </script>
Will break the syntax highlight for the rest of the document.

Screenshot:
![image](https://user-images.githubusercontent.com/28231563/116131011-3c35be80-a6a2-11eb-80ac-ddf692088806.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rlucasfm** [comment]
Similar to #72547, but more specific on use inside script tags

**Comment by roblourens** [comment]
Works for me.

![image](https://user-images.githubusercontent.com/323878/116186264-20e5a600-a6d8-11eb-815a-ba1e200fbc7d.png)

What theme? Share the full file please

**Comment by rlucasfm** [comment]
I'm using Dark+ theme. All extensions disabled. Besides that, The file is a .blade.php, but if I do the same with a .php file the issue persists, maybe something with the curly braces for the blade sintax.

Uploading as a .txt because of GitHub supported files , but it is a .blade.php on the project actually.
[tabela_repasses.txt](https://github.com/microsoft/vscode/files/6384128/tabela_repasses.txt)

**Comment by roblourens** [comment]
Still works for me in that file. I do see a laravel blade syntax highlighting extension. You might try using that. We don't support blade syntax by default.

![image](https://user-images.githubusercontent.com/323878/116261134-3389ca80-a72c-11eb-8dd9-a80a076a5b9f.png)
