### ISSUE TITLE
Theme got permanently reset

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#122290]
Testing #122233

I'm not 100% sure of my steps here, but I think they were:

1. Open a folder. Mine was c:\users\alros\documents\one
2. Trust the folder. My theme came back. ✔
3. File -> Add folder to workspace. I added c:\users\alros\documents\two
4. No prompt, but that's a different issue.
5. File -> Open folder. I opened the folder from step (1) again. 
6. After the reload, my theme is not applied 🐜 I checked the trust manager, and the folder is there. I had to set the theme again using Preferences: Color Theme.

**Comment by sbatten** [comment]
@alexr00 is your theme one that requires workspace trust? i.e. it has a main entry point? I'm not sure why your theme would be modified in this flow.

**Comment by alexr00** [comment]
Yes, it has a main entrypoint.

**Comment by lszomoru** [comment]
Is it expected for a theme to have a main entry point? I thought that themes don't have one.

**Comment by sbatten** [comment]
@sandy081 is resetting the theme to the default value a feature of core if a theme is disabled?

**Comment by sandy081** [comment]
> Is it expected for a theme to have a main entry point? I thought that themes don't have one.

Some themes extensions have code like `pkief.material-icon-theme` extensions. They offer some additional functionality like welcome experience or more. 

> @sandy081 is resetting the theme to the default value a feature of core if a theme is disabled?

I think so, @aeschli resets to default if theme does not exist. But I do not know if he does hard reset or in memory. Have to wait for his response

**Comment by aeschli** [comment]
The workbenchThemeService gets a 'extension removed' event and therefore decides to change to the default setting.
We remember the last theme and would use it again if the extension gets enabled. But we only remember it in memory. As here there's a window reload so this doesn't work.

Should there be a reload when the state goes from trusted to untrusted? I recall from the discussions in the API call we never go from trusted to untrusted.
Also, disabling the extension with code requires a reload. 
Given that, I think the workbenchThemeService should not get a 'extension removed' event.

**Comment by sbatten** [comment]
@alexdima did some work to make it so we no longer need a window reload, we simply reload the extension host when transitioning from trusted to untrusted.

**Comment by sbatten** [comment]
I think with the current design and public release of the features, this is no longer a common issue. any themes incorrectly requiring trust should be overridden by the user or extension author.
