### ISSUE TITLE
NotebookController asWebviewUri issues for notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122221]
From https://github.com/microsoft/vscode/issues/121981

- Need to figure out what the ID for a notebook webview is: https://github.com/microsoft/vscode/issues/121981#issuecomment-826809166
- And include the remote scheme/authority in the uris from asWebviewUri https://github.com/microsoft/vscode/issues/121981#issuecomment-826809166

**Comment by mjbvz** [comment]
I believe that we now correctly support this. To test:

1. Install the GitHub issues notebook extension locally
2. Connect to a remote workspace and open a GitHub issue notebook
3. Add some math in the notebook, such as `$x^x$` and verify it is rendered properly (the base markdown renderer is installed on the remote)
4. Now run the notebook and verify the output is rendered (this is running JS from your local machine)

So it looks like we now properly support loading both local and remote resources within a single webview

Please let me know if you notice any cases where `asWebviewUri` from notebooks is still not doing the correct thing
