### ISSUE TITLE
Customize custom view height

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#122283]
As you can see, the 'open editors' view has dynamic height according to its content. Can we customize our view( which in inside custom view container) height like that?
![image](https://user-images.githubusercontent.com/73154171/116214506-58f0f580-a779-11eb-8a11-0ec80e7eb7b7.png)

**Comment by isidorn** [comment]
Open editors has some custom code for doing this https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L418

I believe this is not possible with custom views, and I think is a feature request against custom views thus forwarding to @alexr00

**Comment by alexr00** [comment]
Notes about proposal:

https://github.com/microsoft/vscode/blob/0c00dfcc2c71caec6804178ab106b817512cca57/src/vscode-dts/vscode.proposed.contribViewSize.d.ts#L6-L19

**Comment by alexr00** [comment]
Example with the latest proposal
```
				{
					"id": "github:createPullRequest",
					"type": "webview",
					"name": "Create Pull Request",
					"when": "github:createPullRequest",
					"visibility": "visible",
					"initialSize": 2
				},
				{
					"id": "github:compareChanges",
					"name": "Compare Changes",
					"when": "github:createPullRequest",
					"visibility": "visible",
					"initialSize": 1
				},
```
