### ISSUE TITLE
[Loc] "View Problem" & "Quick Fix" not localized

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#122298]
VS Code Version: VSCode 1.55.2
OS Version: Linux ARM64

Notes:
Only Simplified Chinese & French language not be localized
 
Steps to Reproduce:
1. Install Simplified Chinese & French language package.
2. Open a  .ts file with VS Code. 
3. Add "#include<stringgggg>". 
4. Hover over the error part. 
5. Observe the information. 

Expected:
"View Problem" & "Quick Fix" be localized.
Simplified Chinese:
![CHS_expect](https://user-images.githubusercontent.com/78774400/116218821-80e25800-a77d-11eb-85eb-b927a85c7a99.PNG)
French:
![FRA_expect](https://user-images.githubusercontent.com/78774400/116218851-893a9300-a77d-11eb-8971-48a78cd89167.PNG)

Actual:
"View Problem" & "Quick Fix" not localized.
Simplified Chinese:
![CHS_actual](https://user-images.githubusercontent.com/78774400/116218400-1204ff00-a77d-11eb-8fa3-23adb1e2302d.PNG)
French:
![FRA_actual](https://user-images.githubusercontent.com/78774400/116218430-18937680-a77d-11eb-90b1-473e2888752b.PNG)

**Comment by alexdima** [comment]
@dbaeumer AFAICT the code uses `nls.localize` correctly.

**Comment by v-mholloway** [comment]
no repro - this appears translated now
![image](https://user-images.githubusercontent.com/77055370/134659507-7c94ec48-8014-4175-83d7-d4c0319ac539.png)
