### ISSUE TITLE
Add more border colors for theming

### ISSUE THREAD

**Issue by rfrkk** [microsoft/vscode#122259]
Theme style increase,
1.  border color of  "breadcrumb.border" 
2.  background color and border color of container of scrollbarSlider
3.  background color of "scrollbarSlider.hover"

![2021-04-27 09 22 05](https://user-images.githubusercontent.com/137764/116171083-b1ed6900-a73a-11eb-8dc0-b52e18a86653.png)

**Comment by rfrkk** [comment]
However, until Vscode Ver 1.55, I pointed out that these parts still don't have boder or background color, so I put the focus here, thank you.

**Comment by misolori** [comment]
I'm sorry, are you asking for these borders to be added or are you having issues with them?

**Comment by rfrkk** [comment]
I originally requested to increase these features, because i can not find these setting.
I am fortunate to find border Border of Breadcrumd today. 
< editorGroupHeader.border: Border color between editor group header and editor (below breadrcumbs if enabled). > 

Can I ask if vsocde has these theme styles setting?
2. background color and border color of container of scrollbarSlider
3. background color of "scrollbarSlider.hover"
