### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by Bugleman** [microsoft/vscode#122261]
Ok what is this 
![2021-04-26-164444_1920x1080_scrot](https://user-images.githubusercontent.com/83040443/116172367-bcfab780-a6ae-11eb-9fa8-a35a030a5579.png)

I installed vscode by using sudo apt-get code -y
works but VSCode does not load correctly
Im on 32bit raspberry pi4

**Comment by joaomoreno** [comment]
Does `code --verbose` return any interesting information?
