### ISSUE TITLE
Reduce flicker when moving cursor from one to the next custom tooltip

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#122226]
Native browser tooltips and many custom ones (Figma, Discord, Edge tabs) keep the tooltip element visible when moving between elements. Would be nice to do the same, to make mouse exploration even snappier.

Discord icon bar:
![ScreenFlow](https://user-images.githubusercontent.com/8599/116135461-05ea4600-a686-11eb-8fa2-bf29b59b4a0d.gif)

macOS dock:
![ScreenFlow](https://user-images.githubusercontent.com/8599/116135868-7db87080-a686-11eb-8b92-e8a31de4bf96.gif)

**Comment by digitarald** [comment]
cc @sandy081 as this discussion was spawned off #118077
cc @alexr00 as owner of the hover widget
cc @misolori as we talked about this a few times and he brought it up most recently in the team chat

**Comment by Tyriar** [comment]
@digitarald fyi I'm the main hover widget person 🙂 

This seems doable, needs some thinking on how this would be exposed in the API. It's also a feature of native browser tooltips when hovering from one element with `title` to another.

**Comment by sandy081** [comment]
>  fyi I'm the main hover widget person 🙂

@Tyriar Thanks for confirmation :)
