### ISSUE TITLE
Test: Resolving conversations in GHPRI

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#122243]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/339
- [x] macOS @jrieken
- [x] linux @roblourens
- [x] windows @kieferrm

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122243%0A%0A)

---

Please use the nightly version of the GitHub Pull Requests and Issues extension to test.

There is now a "Resolve conversation" button that appears on comment threads within editors. This should:
- Mark the thread as resolved on GitHub (note that you cannot resolve threads that are on pending reviews)
- Collapse the comment widget in the VS Code editor after resolving, and on future opens of the file (unless you expand it again)
- Update the comment thread title to say the thread has been resolved
- Show an "Unresolved conversation" button on comments that have been resolved

**Comment by roblourens** [comment]
I think I am blocked by https://github.com/microsoft/vscode-pull-request-github/issues/2684. I have this issue in multiple test repos. I can open files in PRs in the vscode repo, but I don't want to test this feature on a real repo.
