### ISSUE TITLE
Overwrite is truncated in dialog as overw

### ISSUE THREAD

**Issue by daniel-white** [microsoft/vscode#122235]
- VS Code Version: 1.55.2
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Attempt to close with a file that needs saved but would overwrite.
2. Notice that "overwrite" is truncated as "overw"

<img width="435" alt="Screen Shot 2021-04-26 at 4 35 33 PM" src="https://user-images.githubusercontent.com/735269/116147547-df400580-a6ad-11eb-9459-66a015de6d12.png">

Does this issue occur when all extensions are disabled?: n/a

**Comment by bpasero** [comment]
How exactly do you get into the state that this dialog opens?

**Comment by daniel-white** [comment]
Oh now I remember. This was an error message I copied out into a new buffer. Definitely had my wires crossed. haha. closing.
