### ISSUE TITLE
Visual defects

### ISSUE THREAD

**Issue by Flukas88** [microsoft/vscode#122278]
Issue Type: <b>Bug</b>

There are visual defects (green lines) in the files explorer that stops me from seeing the files list.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 6, 7|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|. --crash-reporter-id 09893abc-b220-40cd-817f-5b86df637ea0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.2
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
vscode-dash|dee|2.4.0
gitlens|eam|11.4.1
nasc-touchbar|fel|1.12.0
go|gol|0.24.2
gc-excelviewer|Gra|3.0.41
rest-client|hum|0.24.5
elixir-ls|Jak|0.7.0
vscode-phoenix-snippets|jam|1.0.7
better-cpp-syntax|jef|1.15.5
swift|Kas|0.2.0
go-prof|Max|0.0.4
vscode-language-babel|mgm|0.0.31
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
cmake-tools|ms-|1.7.1
cpptools|ms-|1.3.1
makefile-tools|ms-|0.2.0
vscode-phoenix|ped|0.6.0
gotestexplorer|pre|0.1.13
goasm|qui|0.0.5
rust|rus|0.7.8
elixir-formatter|sar|1.3.0
markdown-preview-enhanced|shd|0.5.18
ignore|Syl|0.0.4
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
JavaScriptSnippets|xab|1.8.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by Flukas88** [comment]
[Screenshoot](https://ibb.co/Wt3v1q5)

**Comment by isidorn** [comment]
Looks lie an electron issue. Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Also forwarding to @deepak1556
