### ISSUE TITLE
Enabling process reuse results in zombie extension host on Mac

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#122244]
Testing #120431

Currently, on Mac, enabling process reuse results in zombie processes being created.

Originally, the workbench process would be killed, and a new one would be restarted, and therefore, there would be no zombie process.
However, the workbench process is now being reused, and does not handle the extension host's exit signal before reloading for performance reasons. In turn, the extension host process does exit, but it stays on the system as a zombie. It continues to show up in the Process Explorer under a name like `(Code OSS - Helper)` or `(Electron - Helper)` (the latter occurs if one launches VS Code using Electron).

I have attempted to add `child_process.unref()` and `child_process.disconnect()` calls from the renderer side, but the zombie process remains. Only when I explicitly wait for the exit signal, and handle it by killing the exited extension host in `onWillShutdown`, does the extension host process get cleanly killed. However, that means the workbench must wait for up to five additional seconds before the `onWillShutdown` events finish and the reload occurs, which is too slow.

See https://github.com/microsoft/vscode/pull/120952 for more details, including the current implementation of the branch that enables process reuse.

CC @bpasero

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/commit/18cde6954293e68337f15ae14eccb798f52677ee
