### ISSUE TITLE
Test notebook controller API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122216]
Refs: https://github.com/microsoft/vscode/issues/119949

- [x] anyOS @rebornix
- [x] anyOS @bpasero

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122216%0A%0A)

---

We have added a new `vscode.notebook.createNotebookController`-API. The notebook controller is responsible for executions, e.g they make that notebooks show run buttons. Make yourself familiar with the [NotebookController](https://github.com/microsoft/vscode/blob/42754baf3a0a2bbdd6c5928c3ce76dd105f071be/src/vs/vscode.proposed.d.ts#L1549-L1549)-API and then write an extension that uses this API. A simple way to do that is to add another controller for [GitHub issue notebooks](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks). So install that the GHINB-extension and author another extension like so

```ts
    const ghc = vscode.notebook.createNotebookController('test1', 'github-issues', "BetterGH");
    ghc.executeHandler = (cells) => {
        console.log('I am running %s cells', cells.length)
    }
```

Test that:

* the API works and is documented
* the controller shows in the kernel picker of the status bar
* the `onDidChangeNotebookAssociation` event fires when the kernel is being selected (via the picker or via run)
* the `executeHandler` is invoked when running a cell or notebook
* non-readonly properties like label can be modified at any time 
* a list of supported languages can be defined. that list defines whether a cell can be run and what language new code cells have

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.proposed.d.ts`

**Comment by bpasero** [comment]
I was not sure what `NotebookKernelPreload` are, given they are not documented yet in the proposed API.

**Comment by jrieken** [comment]
Yeah, I left purposefully left them unmentioned as we are planning more tweaks and clarification around that part of the API
