### ISSUE TITLE
无法删除和恢复 JSON 文件

### ISSUE THREAD

**Issue by tengxunwangyidoushizhazha** [microsoft/vscode#122282]
I mistakenly deleted the vscode file in launch.json. I can't debug the C + + code after unloading and reloading the vscode. My computer is broken and I just need to reload it. I don't know how to set the vscode to normal. I can't find the option to restore the default settings. Visual studio 2019 has the option to restore the default settings.

**Comment by isidorn** [comment]
Sorry but this is behaing as desgined. If you find clear steps for the issue please file a new concise issue with reproducable steps
