### ISSUE TITLE
Editor override service always awaits `whenInstalledExtensionsRegistered`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122284]
It looks like we have a `*` override that always matches. As such we always await `whenInstalledExtensionsRegistered` on startup now.

**Comment by lramos15** [comment]
Fixed https://github.com/microsoft/vscode/commit/3e1a7dc6551bb801b326fb3f8558f18b7a84389d. It was because the editorOverrideService knows the Text Editor exists on `*`, but we don't want to add that to the cache as the text editor isn't bound by the ext host.
