### ISSUE TITLE
The terminal could not be enabled properly

### ISSUE THREAD

**Issue by willis728** [microsoft/vscode#122260]
Issue Type: <b>Bug</b>

The terminal could not be enabled properly
->
terminal.integrated.shell.windows
Unknown Configuration Setting
No quick fixes available

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (1.66GB free)|
|Process Argv|--crash-reporter-id 574cfd79-e2c6-4fba-8195-8a00a459b8fd --crash-reporter-id 574cfd79-e2c6-4fba-8195-8a00a459b8fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.7.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.21
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.25.1
todo-tree|Gru|0.0.212
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
smarty|imp|0.3.0
fluent-icons|mig|0.0.7
HTMLHint|mka|0.10.0
vscode-docker|ms-|1.12.1
vscode-language-pack-zh-hans|MS-|1.55.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1
sqltools|mtx|0.23.0
color-highlight|nau|2.3.0
vetur|oct|0.33.1
vscode-commons|red|0.0.6
vscode-xml|red|0.16.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.18
guides|spy|0.9.3
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
codelf|unb|11.7.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.4.0
quokka-vscode|Wal|1.0.359
vscode-import-cost|wix|2.15.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
