### ISSUE TITLE
Test: Workspace trust - supportUntrustedWorkspaces setting

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#122230]
Refs: #106488 
- [x] macOS @rebornix
- [x] macOS @jrieken
- [x] windows @deepak1556

Complexity: 3

Authors: @lszomoru, @sbatten

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122230%0A%0A)

---

Prerequisites:
- Enable workspace trust using `security.workspace.trust.enabled: true`

Steps:
- Open a new window, open a folder, and choose to stay in restricted mode
- Open the workspace trust editor with the Workspaces: Manage Workspace Trust command
- Click on the "N extensions" link in the "Restricted Mode" box and confirm that there are some extensions that are disabled
- Open the setting file using the `Preferences: Open Settings (JSON)` command
- Use intellisense to add the `extensions.supportUntrustedWorkspaces` setting
- Use intellisense to pick an extension from the list
- Set the value of `supported` to `true`. 
- Reload the window and confirm that the extension is enabled in restricted mode.
- Open settings and modify the `version` to it does not match the installed version
- Reload the window and confirm that the extension is disabled in restricted mode.
- Open settings and remove the `version` property
- Reload the window and confirm that the extension is enabled in restricted mode.

**Comment by jrieken** [comment]
Sorry, but I accidentally ran these tests on macOS
