### ISSUE TITLE
Notebooks doesn't update of changed externally

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#122328]
Testing #122033

![cast](https://user-images.githubusercontent.com/1931590/116245842-acf3de00-a769-11eb-8cfa-965debe722bf.gif)

**Comment by bpasero** [comment]
I see the notebook flickering when you save so I suspect the event goes through but the UI does not update.

**Comment by jrieken** [comment]
The problem is that we reload the notebook and that then text models for the notebook cells already exists. Since we now have "fresh" cell source we need to reset the text models with that.
