### ISSUE TITLE
Typescript constantly initializing

### ISSUE THREAD

**Issue by kokopelli314** [microsoft/vscode#122350]
Issue Type: <b>Performance Issue</b>

Typescript is stuck initializing in WSL remote repo on Windows 10, showing "Initializing JS/TS language features". Using significant CPU resources. Restarting sometimes fixes the issue, but about 60%-80% of the time VSCode hangs forever on initializing until being closed.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (14.41GB free)|
|Process Argv|--crash-reporter-id cbbf0ae3-a0ee-440a-9498-239de04b15e5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.92GB (19.52GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    80	 12564	code main
    0	    40	  1784	   utility
    0	    94	 10112	   shared-process
    0	    67	 22604	     ptyHost
    0	   254	 11580	   window (● Order.ts - web [WSL: Ubuntu] - Visual Studio Code)
    0	   157	  8960	     extensionHost
    0	    64	 10956	       electron_node wslDaemon.js 
    0	     6	 18216	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3c4e3df9e89829dce27b7b5c24508306b151f30d stable .vscode-server 0  '
    0	     6	   532	           C:\WINDOWS\system32\lxss\wslhost.exe {048d0a1d-4fae-4ee6-8c19-4817eb40afc1} 472 500 504 {669ae54f-25d6-4f1c-9fba-91315606683e}
    0	    14	 19444	             console-window-host (Windows internal process)
    0	    11	 11284	           console-window-host (Windows internal process)
    1	   172	 13112	   gpu-process
    0	    81	 13980	   window (Issue Reporter)
    0	    24	 21528	   crashpad-handler

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    4	     0	  4452	remote agent
    0	     0	  4463	   ptyHost
    0	     0	  4686	     /bin/bash
    0	     0	  4623	   watcherService
    0	     0	  4673	   extensionHost
    0	     0	  5601	     /home/nathan/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node /home/nathan/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4673
    0	     0	  6175	     /home/nathan/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/node --max-old-space-size=3072 /home/nathan/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/8c0cdb4d2831d4644dda/tscancellation-4d30f1e0c0b5529c0081.tmp* --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /home/nathan/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	     0	  6220	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6221	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (web): 12663 files|      File types: js(5354) ts(1231) tsx(617) json(103) gql(85) py(71)
|                  graphql(58) md(42) txt(40) css(21)
|      Conf files: package.json(11) tsconfig.json(10) github-actions(6)
|                  launch.json(1)
|      Launch Configs: pwa-node;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
bracket-pair-colorizer-2|Coe|0.2.0
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
code-settings-sync|Sha|3.4.3
emacs|vsc|0.1.3
Bookmarks|ale|13.0.4
gitlens|eam|11.4.1
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
vsliveshare|ms-|1.0.4131
vetur|oct|0.33.1
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
