### ISSUE TITLE
Polish UI for @trustRequired filter

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122335]
Testing #122230

* open the extensions viewlet and filter by `@trustRequired`
* there are two groups but the headers are rather cryptic 
* I suggest to insert some kind of message atop of each group that explains what this means

<img width="405" alt="Screenshot 2021-04-27 at 15 09 50" src="https://user-images.githubusercontent.com/1794099/116247842-89ca2e00-a76b-11eb-9707-73367869a40f.png">

**Comment by misolori** [comment]
I wonder if this should apply to all of our cases where we do this splitting (WSL, Codespaces, Containers, etc.) because they all can fall under that same rule as well:

<img width="400" src="https://user-images.githubusercontent.com/35271042/116291889-f16f8180-a749-11eb-9e3d-619e9c4ec670.png">

**Comment by jrieken** [comment]
> I wonder if this should apply to all of our cases where we do this splitting

+💯 It is so hard to convey the meaning of these bucket through titles only

**Comment by sandy081** [comment]
Totally agree to have more info for views - Have you thought about providing this info using our custom hovers?

**Comment by benibenj** [comment]
Closing as `@trustRequired` does not exist anymore
