### ISSUE TITLE
Enter isnt working. It starts to work at the beginning of restarting the app, and then ceases to work again. 

### ISSUE THREAD

**Issue by savvyalbanez** [microsoft/vscode#122387]
- VS Code Version: 1.55.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open the app and try to press enter -- if it works - give it 20 mins. 
2. Restarting fixes the issue temporarily 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Enter`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`Enter`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
