### ISSUE TITLE
Zen Mode does not work when using Github Codespaces as a PWA

### ISSUE THREAD

**Issue by guiherzog** [microsoft/vscode#122319]
I have a Github Codespace instance running and I have installed it as a web app.

![Screen Shot 2021-04-27 at 14 18 20](https://user-images.githubusercontent.com/3836025/116239864-73b86f80-a763-11eb-923d-c2db8e66e9fd.png)

However, when using it as an app and toggling Zen Mode with Fullscreen, it blinks for a second and then renders a black window. After that, I have to quit the app and open it again, as even reloading does not work.

![Screen Shot 2021-04-27 at 14 21 02](https://user-images.githubusercontent.com/3836025/116240162-d0b42580-a763-11eb-8c48-67d430f463a7.png)

It works normally on the browser.

I am using Chrome Version 89.0.4389.128 (Official Build) (x86_64)
And MacOS Catalina 10.15.7 (19H524)

**Comment by isidorn** [comment]
How about if you just do F1 > full screen and not zen mode? Does it work then?

**Comment by guiherzog** [comment]
It also does not work.

So, I am suddenly got it to work and tried to figure out how to reproduce this reliably.

Apparently, if you open Codespaces on the browser first, then open it using the "Open in App" link. (see image on first comment). And then, try to go into Fullscreen or Zen Mode, it does not work. I am suspecting there is something wrong with going to full screen.

However, if after that you close the app, and re-open it again directly using the App (by using CMD+Space on the Macbook + "Codespaces"), it works normally.

Let me know if you need any more info.
Thank you!

**Comment by isidorn** [comment]
All good info. Potential duplicate https://github.com/microsoft/vscode/issues/106972
fyi @bpasero @deepak1556

**Comment by guiherzog** [comment]
I provided all information asked, why has the issue been closed?

**Comment by isidorn** [comment]
I think it is a duplicate, so no action from you is needed
