### ISSUE TITLE
功能建议：文档修改状态的保存

### ISSUE THREAD

**Issue by buzhizhe** [Microsoft/vscode#12234]
- VSCode Version:1.52
- OS Version:win8.1

Steps to Reproduce:

 我需要一个简单而常用的功能，就是文档修改状态的保存。
平常随便记录些东西，在关闭时候不要提示我是否保存，如果我不保存，下次打开后仍然可看见编辑的内容，并且可以保存或不保存。 这样的目的是：只要我输入了内容，不管我是否保存都不会丢失（即使断电也不会丢失）。
sublime text是这种方式，这也是我一直用sublime的原因之一。

**Comment by bpasero** [comment]
@buzhizhe please report the issue in english

**Comment by deanmongel** [comment]
He want the feature of remembering last session and auto saving untitled files, just like 'hot exit' of sublime.

**Comment by bpasero** [comment]
Ok that is https://github.com/Microsoft/vscode/issues/101

**Comment by buzhizhe** [comment]
yes,exactly is  #101,thanks.
