### ISSUE TITLE
Process hang if preferred local display language doesn't support by OS

### ISSUE THREAD

**Issue by zhangbolong** [Microsoft/vscode#12237]
- VSCode Version: Current 1.5.2
- OS Version: Windows 10

Don't know if this is a bug.
Background: Microsoft banned installing extra language packs on Windows 10 Chinese version.

Steps to Reproduce:
1. Change the local display language in locale.json to "en_US"
2. Since there's no language pack supported in the system, processes hang after start
3. Find locale.json and change local display language back to "zh_CN", problem solved.

**Comment by bpasero** [comment]
I would be surprised if those steps can cause a hang, but @dbaeumer moving to you for comment first.

**Comment by dbaeumer** [comment]
@zhangbolong th --locale switch doesn't rely on any language pack installed. It simply relies on language bundles shipped with VS Code. How does VS Code hand. Can you open the Developer Tools (Help -> Toogle Developer Tools) to see if there are any errors in the console.
