### ISSUE TITLE
Notebook doesn't restore correctly after discard from Git

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#122327]
Testing #122033

- change note book
- save
- go to git
- discard the change

Observe: the notebook doesn't update to the previous state

![Animation](https://user-images.githubusercontent.com/1931590/116245110-e37d2900-a768-11eb-8553-455151b7c9a5.gif)

**Comment by bpasero** [comment]
I see the notebook flicker after the discard, so I suspect the UI is just not updating properly.

**Comment by jrieken** [comment]
same cause as https://github.com/microsoft/vscode/issues/122328

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/122328
