### ISSUE TITLE
Trust dialog: "Learn more" link is not functional

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122386]
Testing #122232

![image](https://user-images.githubusercontent.com/900690/116278017-5a74ea80-a786-11eb-9055-d77a58b2ea01.png)

**Comment by sbatten** [comment]
I cannot reproduce

**Comment by bpasero** [comment]
-> Linux

**Comment by sbatten** [comment]
still do not reproduce on linux

**Comment by bpasero** [comment]
Ok then feel free to close, I am in Parallels, Ubuntu 20 ARM.
