### ISSUE TITLE
Splitting custom editor that is not splitable should focus new group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122362]
Testing #122030

When you select one of the split actions from the context menu on a custom editor that cannot be split, an empty group opens but does not have focus. I think it should be active.

![image](https://user-images.githubusercontent.com/900690/116266864-2c8aa880-a77c-11eb-92cb-9d2a4267d337.png)

**Comment by lramos15** [comment]
I did this on purpose since I felt it was weird having an empty group focused especially when this is one of the few cases you would get an empty group as we normally respect the close empty group setting.

**Comment by bpasero** [comment]
I am also fine waiting for user feedback on this but it seems my main intent is to open a new group and do something with it.

**Comment by Tyriar** [comment]
This is an indication that the user wants that file in the new group, so why don't we move it there and focus it as well. So it acts move like a move to group above if splitting isn't supported?

**Comment by lramos15** [comment]
@Tyriar This is what I originally had, but pretty much got unanimous push-back to it at the UX sync.
