### ISSUE TITLE
Open recent works fine, but also shows the browser blocked message

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122326]
Testing #121763

Repro:

1. Safari/Codespace insiders
2. Open a recent project

It works fine, but the block dialog still shows in the background window

![recording (1)](https://user-images.githubusercontent.com/2193314/116243168-7ee7ad00-a71b-11eb-8d56-7a0f3592a8f8.gif)

Related: https://github.com/microsoft/vscode/issues/122324

**Comment by isidorn** [comment]
Interesting. Assigning to April to investigate more.

**Comment by isidorn** [comment]
Weird, this just works for me. Both in Codespaces and by running `resources/server/web.sh`

@Tyriar what do you different than this

Ctrl + R -> get a list of recent project
Cmd + Click on some to get in a new tab -> no popup for me it just works

**Comment by Tyriar** [comment]
That's it except I have this keybinding

```
{ "key": "ctrl+alt+o",       "command": "workbench.action.openRecent" }
```

And this setting:

```
"window.openFoldersInNewWindow": "on",
```

**Comment by isidorn** [comment]
@Tyriar even with that setting recent folders are always opened in a new tab for me. @bpasero is there some other setting that controls if recent folders are opened in new tab vs new window in browser?

**Comment by bpasero** [comment]
>  is there some other setting that controls if recent folders are opened in new tab vs new window in browser?

As far as I know, that is something the user can configure in browser settings and not something we can control.

**Comment by isidorn** [comment]
@bpasero you are right. I have changed this setting in safari. But I still can not get the dialog in the background that @Tyriar is seeing.
For now assigning to backlog and let's see if more people see it and then I can investigate into it more.

**Comment by isidorn** [comment]
We did not get more complains. Closing as I do not plan to tackle this
