### ISSUE TITLE
Files copied via file explorer don't show up in editor

### ISSUE THREAD

**Issue by gp187** [Microsoft/vscode#12230]
- VSCode Version: 1.5.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open code in any project with lots of files 
2. go to file explorer
3. copy something via explorer
4. look in code editor: new files do not show up. Even after 10-15min they don't

Only re-opening editor will update files

**Comment by bpasero** [comment]
@gp187 you mean the new files do not show up in the files explorer in vscode?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
