### ISSUE TITLE
Trust dialogs consistency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122391]
Testing #122232

I think the wording between all trust dialogs should be aligned.

**Tasks:**
![image](https://user-images.githubusercontent.com/900690/116278565-e7b83f00-a786-11eb-8b9a-bd0852854fc2.png)

**Debug:**
![image](https://user-images.githubusercontent.com/900690/116278602-ef77e380-a786-11eb-8f73-01d4c19d8d7c.png)

**Open Workspace:**
![image](https://user-images.githubusercontent.com/900690/116278688-074f6780-a787-11eb-9c40-b29ad4f29e7c.png)

It is good for debug and tasks to be specific about reasons so I would not change that. But the last dialog talks about "trusting authors" and the others about "trusting source".

**Comment by bpasero** [comment]
I also think the buttons could align? I somewhat like the "Learn More", "Cancel", "Trust Workspace & Continue" more than the other one.

**Comment by sbatten** [comment]
I think we should align the authors and folders terminology. Currently the last dialog is the most up to date with our preferred terminology.

For the buttons, the more verbose buttons are preferred in open workspace flow when you don't know about this feature and you have no context.

**Comment by sbatten** [comment]
@bpasero I did a first pass to update the titles/folder terminology across dialogs today, still not quite sure we want to change the buttons due to the context at the time of receiving the dialogs

**Comment by sbatten** [comment]
closing this as we made tweaks in response to the issue at the time, but never changed the buttons.
