### ISSUE TITLE
Terminal rendering broken

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122339]
Testing #122242

Sorry for no clear, steps this only happened once and I could not reproduce. So feel free to close if nobody else complains and you can not repro.

1. Move terminal tabs to the left
2. Move them back to the right
3. Hide them

Rendering broken.
![Screenshot 2021-04-27 at 15 27 19](https://user-images.githubusercontent.com/1926584/116249678-59838f00-a76d-11eb-9171-ddf6e8b0ecf7.png)

Bring them back by changing the setting. Rendering still broken

![Screenshot 2021-04-27 at 15 27 30](https://user-images.githubusercontent.com/1926584/116249683-5a1c2580-a76d-11eb-97dc-f263c40df986.png)

**Comment by Tyriar** [comment]
Can't repro, if you hit this again while testing can you check the console for errors?

**Comment by isidorn** [comment]
I checked the console, it was empty.

**Comment by Tyriar** [comment]
I guess a screenshot of the dom structure would be useful, seeing if the split is gone or just tiny?
