### ISSUE TITLE
Do not show tab list if only one terminal tab with multiple terminals

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122348]
Testing #122242

Currently you show the tab list if I have only one tab with multiple terminals.
I think this is wrong and by default we should only show the tab list if there are multiple terminal tabs.

Reason in the following setup space is particularly valuable

![Screenshot 2021-04-27 at 16 00 49](https://user-images.githubusercontent.com/1926584/116254576-bf721580-a771-11eb-82e4-f276772546cf.png)

**Comment by Tyriar** [comment]
I don't think we should do this as the tab contains important information that would be hidden for the non-active terminal if we went this directyion. For example if the terminal is disconnected, task status (next iteration), etc. If this is a common setup I think the narrow tab view would be ideal.

If more people point this out we could expand `terminal.integrated.tabs.hideForSingle` but I wouldn't want to change this default.

**Comment by Tyriar** [comment]
Setting change part of this is moved to https://github.com/microsoft/vscode/issues/122551
