### ISSUE TITLE
Trust editor: both options are color coded with red

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122308]
Refs: https://github.com/microsoft/vscode/issues/122228

Open trust editor:

Both trusted and untrusted are color coded red.
I suggest to use the same color coding as in the dialog:
Blue for Trusted and gray for Untrusted (disabled).

Both the outline and the icon on top

fyi @misolori 

![Screenshot 2021-04-27 at 12 33 01](https://user-images.githubusercontent.com/1926584/116227748-c3436f00-a754-11eb-9a2d-1372156e876b.png)

![Screenshot 2021-04-27 at 12 32 55](https://user-images.githubusercontent.com/1926584/116227743-c2124200-a754-11eb-826c-74c5887652b7.png)

**Comment by lszomoru** [comment]
At the moment the workspace trust editor is using the accent colour to highlight the selected option. 
I suspect that you are using the "GitHub Sharp" light theme which uses `#d64926` as the accent colour.

**Comment by isidorn** [comment]
Yes I am using the GitHub Sharp, you are correct. However I still think these two should be different colors, and the icon on top should be different colors based on that.

**Comment by sbatten** [comment]
hmm, the button color suggestion seems reasonable except I am worried that this will be difficult to tell which is selected in the disabled case as the unselected border is already grey

**Comment by isidorn** [comment]
@sbatten maybe we could increase the border width for selected and use a stronger grey
fyi @misolori

**Comment by sbatten** [comment]
I tried using the grey for untrusted (the standard secondary color), but it was too muted even with some thicker border, instead I have used the 2 colors suggested but the selected option gets the primary color while the unselected option gets the secondary grey.

https://github.com/microsoft/vscode/commit/6673ba9c46481a933fa730d40e2b77455af20714
