### ISSUE TITLE
Web: wording of link dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122354]
Testing #121763

![image](https://user-images.githubusercontent.com/900690/116262127-92753100-a778-11eb-8ec1-bc18dbf77100.png)

Something with the wording in the dialog seems a bit weird to me. When I read that I must give permission to continue, I somehow expected to get some dialog or editor to configure permissions. I think when clicking "Continue" I would have not expected that the link actually opens.

I am not sure how to change this, but I am not really giving the browser permissions to open links in general, I just allow to open that one link.

**Comment by isidorn** [comment]
Maybe we say
"You must allow this to continue"

Giving permission sounds permanent which is not the case here.

**Comment by bpasero** [comment]
Yeah, maybe ask others for opinion in UX channel.

//cc @weinand for wording

**Comment by weinand** [comment]
Yes, I share Ben's concerns.
What's about something like this:
> The browser interrupted the opening of a new tab of window. Press 'continue' if this is ok for you.

**Comment by bpasero** [comment]
Or maybe:

_The browser interrupted the opening of a new tab of window. Press 'Continue' to open it anyway._

And given we show the link below, the user can make a good choice.

**Comment by weinand** [comment]
Yes, button label "Open" is better
