### ISSUE TITLE
`document.hasFocus()` can return `true` for multiple windows being opened

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122352]
Testing #122200

* have multiple windows of VS Code open
* enable or disable `window.nativeTabs`
* 💩  each window shows a model dialog about needing to restart
* select restart in each window
* 🐛 restart doesn't happen

https://user-images.githubusercontent.com/1794099/116261066-95235680-a777-11eb-8cd0-40d6d272491e.mov

**Comment by bpasero** [comment]
We probably have this issue for any setting that the `relauncher.contribution.ts` listens to. Will see if I can just show the dialog in the active window.

**Comment by bpasero** [comment]
Turns out we already check for the window having focus or not:

https://github.com/microsoft/vscode/blob/b8a320867e57736fd617f1559eba017ff90e978b/src/vs/workbench/services/host/electron-sandbox/nativeHostService.ts#L36-L36

I cannot reproduce this but if `document.hasFocus()` returns `true` for multiple windows being opened, I suspect an Electron issue. I am open to changing the method to check for another property, but having it return sync was one of the main reasons I use `document.hasFocus()`, we use the same in web btw.

//cc @rzhao271

**Comment by bpasero** [comment]
@jrieken are you able to reliably reproduce? Any special window manager installed?

**Comment by jrieken** [comment]
Yeah, it is tricky... So, the first time I set `"window.nativeTabs": true` it works. Then I comment out this setting and the modal shows. First only for the current window and a bit later (~2sec?) for all windows. Once that happened it will always reproduce

**Comment by bpasero** [comment]
Oh yeah I can reproduce. Steps:
* (use a fresh user data dir to start clean)
* open 3 folders in 3 windows
* enable native tabs and restart
* disable native tabs

=> 🐛  each window shows the dialog

**Comment by bpasero** [comment]
Reported as https://github.com/electron/electron/issues/28897

**Comment by deepak1556** [comment]
Temporary workarounds:

1) Start the window with `show: false` and `window.show()`
2) `webContents.removeAllListeners('load-url')`

**Comment by rzhao271** [comment]
Ok I finally built electron 12 source on the Mac.
I was about to let it build overnight with goma, but for some reason I got logged out of the server. I wouldn't be surprised if this has to do with power settings on my device.

With this build, I commented out the line that initially focuses the frame.
I then opened @bpasero's Fiddle from https://github.com/electron/electron/issues/28897 with that build, and noticed that the top-most frame that showed up had focus initially `true`, and the other two frames had focus initially `false`.

I then tested https://github.com/electron/electron/issues/25287 with the build, and found out that that Fiddle still works perfectly fine, too.

Therefore, I believe we can remove most of https://github.com/electron/electron/pull/25292/files and just let Chromium handle the focusing again.

**Comment by rzhao271** [comment]
@deepak1556's upstream fix is here: https://github.com/electron/electron/pull/29204, and the backport for that fix is here: https://github.com/electron/electron/pull/29235

**Comment by bpasero** [comment]
Given https://github.com/microsoft/vscode/issues/125122 and other related issues, we will be going back to Electron 12.0.7 for recovery. Hence reopening this issue, even though technically it is fixed for insiders because we are not going back there.
