### ISSUE TITLE
Sporadic "contents on disk are newer" issues when saving to network share

### ISSUE THREAD

**Issue by KimTheFirst** [Microsoft/vscode#12232]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Work a lot on various files stored on a network share.
2. Eventually this will happen. 

Some days it won't happen at all, some days it will happen five times in a row. There appears to be a correlation with network speed / network reliability (lower speed = more errors) but I have also had it happen on very fast connections.

**Comment by bpasero** [comment]
Could you try to reproduce with our insider release? We recently had a major update of our file system library: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by KimTheFirst** [comment]
OK, I’ll give it a go and see what happens.

**Comment by KimTheFirst** [comment]
The same issue just occurred with the insider release as well. Slow connection appears to contribute to the error.

**Comment by bpasero** [comment]
@KimTheFirst ok thanks for trying.

**Comment by bpasero** [comment]
@KimTheFirst so the method we use to find out if contents on disk are newer is a simple check on the modification time. Could it be that the file when saved to the network drive changes its modification time after it has been saved?

**Comment by KimTheFirst** [comment]
There is nothing else that uses that file (no virus scanners, etc) and no one else with access to the server.

What if the file were being saved twice in quick succession? Would that set up a race condition whereby both saves had been triggered but neither had finished?

**Comment by bpasero** [comment]
@KimTheFirst we protect this by not letting 2 saves run at the same time ever. Of course I am not sure when the OS decides to tell us that a save has finished, so maybe there is a race condition after all.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/13665

**Comment by bpasero** [comment]
@KimTheFirst does it still reproduce with our latest insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
