### ISSUE TITLE
Terminal tabs: inline actions not multi selection aware

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122346]
Testing #122242

Select multiple items in the terminal tabs view. Context menu is nicely multi selection aware, thus `kill terminal` will kill multiple terminals. However if I have a multi-selection and click on the inline action (trash can icon) only one terminal will get killed.

Across VS Code we always respect multi selection for inline actions (example: Git, Open Editors) so I suggest we also respect multi selection for inline actions in the tab terminal list.

**Comment by Tyriar** [comment]
I would not have expected that since the action is attached to a single item. If we do it elsewhere we can make the change though.

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/commit/b26b993dafa0dd3774ff1da0d61e363f1a744a77, closed the wrong issue

**Comment by isidorn** [comment]
Works great now -> verified
