### ISSUE TITLE
Notebook controller: should `createNotebookCellExecutionTask` be only callable from within the `NotebookExecuteHandler`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122378]
Testing #122216

It seems to me that `createNotebookCellExecutionTask` should only be called when I am being executed from my `executeHandler`, as such should an object be passed into that handler that allows me to do things like creating cell execution tasks?

**Comment by jrieken** [comment]
> It seems to me that createNotebookCellExecutionTask should only be called when I am being executed from my executeHandler,

That's a good observation and generally true but there are cases which led to the current API (not saying it cannot be done better...)

* you might connect to a kernel that is already running a cell. in that case the execution task needs to be created with explicit user action
* you might have a collaborative kernel which is used from a different client and "run" can happen from anywhere
* when running cell B your kernel might decide that dependent cell A must also run ( GH issue notebooks does that with cells that use and define variables)
