### ISSUE TITLE
Trust: `security.workspace.trust.enabled` should show as error in workspace settings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122389]
Testing #122232

I would have expected that when I try to configure `security.workspace.trust.enabled` in workspace settings, I get an error.

![image](https://user-images.githubusercontent.com/900690/116278385-bc355480-a786-11eb-96de-bbdf3dca2332.png)

**Comment by lszomoru** [comment]
I added the application scope to the `security.workspace.trust.enabled` which should address this. Having said that, I spoke with @sandy081, and it has been a conscious decision not to show a warning squiggle, if an application setting is defined in the workspace settings file. So the setting will appear with a different cover with a hover.
