### ISSUE TITLE
"File is dirty save to reopen with encoding" should be modal dialog

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122301]
Testing #122029

1. Have some dirty file
2. F1 > reopen with encoding

There is a notification message which is easily missed and the file is not reopened with a new encoding.

Instead of this I suggest that we show a modal warning with the message and offer action to Save and Reopen. This was user initiated and I think this would make a nicer flow than an easy to miss notification.

![Screenshot 2021-04-27 at 11 54 54](https://user-images.githubusercontent.com/1926584/116223021-6a250c80-a74f-11eb-9573-e8907d7df70b.png)

**Comment by bpasero** [comment]
I think we can simply save the model before reopening with encoding. I never really liked that notification to begin with...
