### ISSUE TITLE
Install a specific version of the package

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#12238]
- VSCode Version: 1.5.2
- OS Version: OS X El Capitan

If I switch on the packages autoupdate option and some package will get broken, how do I revert it's update to the previous version. In other words, how do I install a specific version of the package from the marketplace?

This should help us if some package got broken or changed its behavior.
Autoupdate shouldn't work for the "selected version" packages.

**Comment by joaomoreno** [comment]
We don't support this. It's been our decision to keep users always up-to-date. In case of breakage, we suggest pressuring the extension developer towards a fix, possibly collaborating on it together.
