### ISSUE TITLE
Extensions viewlet doesn't work well with `@trustRequired` tag

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122331]
* open extension view
* have @trustRequired in search box
* continue to type an extension name or id
* :bug: the marketplace is search, instead the installed extension that require trust should be filtered

<img width="451" alt="Screenshot 2021-04-27 at 15 04 50" src="https://user-images.githubusercontent.com/1794099/116246479-520eb680-a76a-11eb-867b-393841a416c7.png">
Testing #122230

**Comment by lszomoru** [comment]
Fixed with dc5219000dcd16a3dd203f598753b7b76d32c1a8
