### ISSUE TITLE
No category for 'Close Remote Connection'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122305]
Testing #122101

pls see the screenshot below. The command 'Close Remote Connection' is the only one without a category, would it help to add a category to make it more clear that the command is generic and applies to the current connection? For example, the command could just be 'Close' and the category 'Connection' (not clear that this is an improvement).

![image](https://user-images.githubusercontent.com/172399/116226300-187e8100-a753-11eb-8927-d1874d62ac89.png)

**Comment by aeschli** [comment]
I tried a few: `Remote`, `Window`, but , to me, they don't look good nor useful.

I'd rather stick with the current state.

We have a similar thing in the color themes selection dialog, where the last command (Install Additional Themes)  has no Category
