### ISSUE TITLE
Terminal tab widget does not render keybindings on hover

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122336]
Testing #122242

Hover over the Split Terminal or the Delete Terminal icons. I can not see the keybinding rendered, even though I have something assigned.
To fix this you can use the `keybindingService` and ask for a keybinding label and append it to the `title`.

![Screenshot 2021-04-27 at 15 18 00](https://user-images.githubusercontent.com/1926584/116248109-d3b31400-a76b-11eb-957a-2da5f49f4547.png)
![Screenshot 2021-04-27 at 15 19 39](https://user-images.githubusercontent.com/1926584/116248273-01985880-a76c-11eb-9c93-316cbf561316.png)

**Comment by Tyriar** [comment]
We use a separate command for split and kill, eg. kill has delete bound, not the standard `.kill` command keybinding if you have one. We could just redefine the default ctrl+shift+5 here, but it wouldn't pick up customizations unless you bound to `.killInstance` as well.

**Comment by isidorn** [comment]
I think that's fair. Keybindings on hover are mostly for beginners to learn, not for people who already customised obscure commands.
