### ISSUE TITLE
White space appears below status bar on iPad PWA mode

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122390]
![image](https://user-images.githubusercontent.com/35271042/116278054-f24ce700-a73a-11eb-8859-2edb4f0c2f57.png)

When you add VS Code to the home screen (similar to PWA) you get this nice full-screen mode that removes the top Safari chrome. However there are two issues that come up:

~1. Login sessions are not persisted and you have to re-login~
2. After logging in there is a white gap at the bottom

**Comment by misolori** [comment]
@bpasero would this fall under your area?

**Comment by alexdima** [comment]
I think the login session (1.) is not under our control, but the gap at the bottom might very well be from us.

**Comment by bpasero** [comment]
//cc @rebornix

**Comment by isidorn** [comment]
Assigning to May to investigate then. Also assigning to @rebornix 
Somewhat similar issue regarding whitespace https://github.com/microsoft/vscode/issues/121206

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/61017718099fb6c4eba66c2eee07b1a5ffaaf4ef/src/vs/base/browser/dom.ts#L352-L357

**Comment by isidorn** [comment]
@rebornix thanks a lot for the pointer, I will look into this in debt week

**Comment by isidorn** [comment]
Just removing that extra code solves the issue.
Now the status bar might overlap with the ipad home indicator, which I think is actually a great experience most of the time.
