### ISSUE TITLE
"Defaults" vs "Default"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122366]
Testing #122030

Shouldn't it be "Default" and not "Defaults"?

![image](https://user-images.githubusercontent.com/900690/116268541-b38c5080-a77d-11eb-8f18-bb6a7c186e7c.png)

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/967020ff3805d9a4d24da9d2ac957f24e9994055
