### ISSUE TITLE
Ctrl+P doesn't wok.

### ISSUE THREAD

**Issue by mfarnz** [microsoft/vscode#122375]
Issue Type: <b>Bug</b>

1. Type ctrl+p

Expected: the "Go to file" search window is shown.
Actual: nothing happens.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (8.42GB free)|
|Process Argv|--crash-reporter-id abe55dc1-9719-4cb4-bf3e-29dce6d713e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
compareit|in4|0.0.2
csharpextensions|jch|1.3.1
Angular2|joh|11.0.0
vscode-csharp-snippets|jor|1.1.0
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
angular-console|nrw|17.2.0
csharp-code-snippets|Som|0.0.1
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by gjsjohnmurray** [comment]
Please run the "Start Extension Bisect" command and follow the prompts to determine if the problem is being caused by one of your extensions.

**Comment by mfarnz** [comment]
> Please run the "Start Extension Bisect" command and follow the prompts to determine if the problem is being caused by one of your extensions.

No luck after running "Start Extension Bisect". It's worth noting that this had been working fine yesterday, and I have not recently installed any new extensions.

**Comment by gjsjohnmurray** [comment]
Does the info at https://github.com/microsoft/vscode/wiki/Keybinding-Issues help you pinpoint where that keycombo is going?

**Comment by mfarnz** [comment]
Reboot and it started working again. 🤷‍♂️
