### ISSUE TITLE
Test: the controller shows in the kernel picker of the status bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122371]
Testing #122216

I am not sure where to look at but should my executor be visible somewhere here:

![image](https://user-images.githubusercontent.com/900690/116272761-7629c200-a781-11eb-9d0e-328c595d5836.png)

**Comment by jrieken** [comment]
The other status bar ⬇️ 

<img width="1038" alt="Screenshot 2021-04-27 at 17 57 45" src="https://user-images.githubusercontent.com/1794099/116273567-239cd580-a782-11eb-8a43-533a60b3e073.png">

**Comment by bpasero** [comment]
:) figured this out now

**Comment by jrieken** [comment]
I take it as a data-point to consider a more explicit controller/kernel UI

**Comment by bpasero** [comment]
I think the challenge is that changing the controller is not something I can do for a single cell, it always impacts all cell. But given we actually do have a status bar for each cell, maybe it could show closer.
