### ISSUE TITLE
Deprecated terminal settings should have a deprecation message

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#122355]
While testing https://github.com/microsoft/vscode/issues/120366, I found the `profile` settings confusing in relation to the old `shell` and `shellArgs` settings. I know about the `shell` and `shellArgs` settings, so of course I look at them first for guidance. Since they are now deprecated, the schema should show a message to that effect to help guide me to use the new settings correctly.

**Comment by MoishyS** [comment]
it's not clear how we should replace shellArgs with defaultProfile - can't see anything in the docs about defaultProfile.

how should I change my current setting?
`  "terminal.integrated.shellArgs.windows": ["-ExecutionPolicy", "Bypass"],
`

**Comment by Tyriar** [comment]
For powershell you would use either:

```js
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell",
      "args": ["-ExecutionPolicy", "Bypass"]
    }
  }
```

Then set it as your default via the new dropdown next to the + button or with this setting:

```js
"terminal.integrated.defaultProfile.windows": "PowerShell"
```

Created https://github.com/microsoft/vscode-docs/issues/4526 to fix up the docs.

Some more info in the release notes https://code.visualstudio.com/updates/v1_56#_terminal
