### ISSUE TITLE
Allign wording for two workspace trust dialogs

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122306]
Refs: https://github.com/microsoft/vscode/issues/122228

Notice how we have two workspace trust dialogs.
I think the wording should be aligned more between the two:

* Extension dialog mentions "Workspace" the other dialog does not. I suggest to not mention "Workspace" but "Folder" instead
* First dialog shows link to learn more. Second dialog shows a button. I suggest to go with the link in both (to reduce number of buttons and complexity) 

![Screenshot 2021-04-27 at 12 19 24](https://user-images.githubusercontent.com/1926584/116226508-55e30e80-a753-11eb-91f3-972c58c8cb90.png)
![Screenshot 2021-04-27 at 12 15 03](https://user-images.githubusercontent.com/1926584/116226510-567ba500-a753-11eb-8310-2452ac4a53db.png)

**Comment by isidorn** [comment]
Adding verified label since this is now better aligned. However I suggest to not have a link and a Learn More button.
I suggest to just have a link to docs. Also 4 buttons is a bit too much
@lszomoru @sbatten  let me know if you would like me to create a new issue for this

![Screenshot 2021-04-29 at 15 23 59](https://user-images.githubusercontent.com/1926584/116557705-fcb7de00-a8fe-11eb-82c4-192d1a2eaa8e.png)

**Comment by sbatten** [comment]
@isidorn actually that learn more button is supposed to say `Manage` now and take you to the trust editor page. I think you have another issue about always opening the editor in these cases so people can learn the impact, which could remove the need for that button.
