### ISSUE TITLE
Trust: if you make it easy to trust, make it easy to not trust

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122383]
Testing #122232

Here in this editor why is going back from "trust" to "not trusted" not a big blue button as well?

![image](https://user-images.githubusercontent.com/900690/116277667-feaa6180-a785-11eb-8fdc-1430d660835e.png)

**Comment by lszomoru** [comment]
If the workspace is trusted directly (and not through a parent folder), there is now a button to revoke trust.
