### ISSUE TITLE
Trust dialog has low contrast to background

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122393]
Testing #122232

I feel the trust dialog should make things behind be more faded out, here I wasn't even noticing there is a dialog on top because the contrast is so little:

![image](https://user-images.githubusercontent.com/900690/116279132-7927b100-a787-11eb-842b-75506fdbc13e.png)

//cc @misolori

**Comment by sbatten** [comment]
I got the same feedback in a user study so thank you for the issue.

**Comment by misolori** [comment]
Wouldn't this apply to all of our custom dialogs?

**Comment by sbatten** [comment]
yes I've added the dialog tag instead of workspace trust

**Comment by joaomoreno** [comment]
## Blur

![image](https://user-images.githubusercontent.com/22350/116396344-20cdcf00-a7da-11eb-80ed-ef3b20c40910.png)

## Grayscale

![image](https://user-images.githubusercontent.com/22350/116396388-2fb48180-a7da-11eb-9ed7-aa7aefa1e8b4.png)

## Blur + Grayscale

![image](https://user-images.githubusercontent.com/22350/116396253-0562c400-a7da-11eb-9258-a782cf2d4c51.png)

## Brightness

![image](https://user-images.githubusercontent.com/22350/116396501-54a8f480-a7da-11eb-9d3c-b895cdb851dc.png)

**Comment by joaomoreno** [comment]
Here's what GH does:

![image](https://user-images.githubusercontent.com/22350/116396800-a3568e80-a7da-11eb-9db0-a0b97bf60ecf.png)

**Comment by sbatten** [comment]
we actually already had dimming for the reconnect dialogs so I just applied it everywhere.

**Comment by bpasero** [comment]
Should we try to emulate the native OS dimming if possible? For example on macOS:

![image](https://user-images.githubusercontent.com/900690/116521880-d11ffe00-a8d4-11eb-9adf-95af7bd9164c.png)

vs

![image](https://user-images.githubusercontent.com/900690/116521973-ebf27280-a8d4-11eb-914f-f72977a08302.png)
