### ISSUE TITLE
Paste doesn't always preserve linebreaks

### ISSUE THREAD

**Issue by skamansam** [microsoft/vscode#122357]
Issue Type: <b>Bug</b>

Open any source file. Copy a line by moving the cursor to the leftmost column. Press shift+down. This should highlight the entire line, including the linebreak. Copy the line with Ctrl+C. Move the cursor down. Press Ctrl+V. 

Expected Results: The pasted line should include the line break, and insert the line exactly as copied. 

Actual Results: The pasted line is inserted BEFORE the text in the current line, excluding the linebreak.

Further information: When pasting the copied line multiple times, it sometimes works as expected, although I couldn't reproduce it while screen recording.

![vscode-paster-error](https://user-images.githubusercontent.com/102971/116264613-6e016080-a748-11eb-948a-3079c93f144c.gif)

VS Code version: Code - Insiders 1.56.0-insider (7ce1499d9541ba2acf66cd30a9054bd7818a8f80, 2021-04-22T05:14:13.305Z)
OS version: Linux x64 5.11.15-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 3|
|Memory (System)|15.49GB (1.45GB free)|
|Process Argv|--disable-extensions --no-sandbox --crash-reporter-id 02322043-412c-4372-a6fb-f9a7b5e9e83f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by alexdima** [comment]
@skamansam I cannot reproduce in a plain text file. Does this reproduce when using `"editor.autoIndent": "advanced"` (instead of the default `"editor.autoIndent": "full"`) ?
