### ISSUE TITLE
Cannot open binary file in text editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122360]
Testing #122030

* open `src/vs/platform/files/test/electron-browser/fixtures/service/binary.txt`
* click on "Do you want to open it anyway"
* select text editor

=> 🐛 nothing happens

(I had hex editor installed too)

**Comment by bpasero** [comment]
Actually this seems like a general issue, I cannot open a GH issues notebook with text editor either:

![recording](https://user-images.githubusercontent.com/900690/116265529-7c1ca480-a77b-11eb-89ce-15047c8889dc.gif)

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode/commit/f4ab7e822f98611f54f3972b451836750e74f65e

**Comment by rzhao271** [comment]
\closedWith f4ab7e8

**Comment by rzhao271** [comment]
According to https://github.com/microsoft/vscode/issues/122361, this fix is already in Insiders.
But, when I click on the "Do you want to open it anyway" link, it does nothing, until I click on another tab and click back. This is with the `binary.txt` file on Windows, and I don't have any other editor installed.

![recording (1)](https://user-images.githubusercontent.com/7199958/116463724-e6872080-a81f-11eb-9d43-b7346859a626.gif)

I can immediately open a GH issues notebook with the text editor, though.

**Comment by bpasero** [comment]
I can open the text editor, but clicking on Hex editor does nothing:

![recording](https://user-images.githubusercontent.com/900690/116521620-78e8fc00-a8d4-11eb-93c1-2020a8d26892.gif)

**Comment by lramos15** [comment]
Wow, this issue is really stubborn I guess.
