### ISSUE TITLE
VS Code won't open in xrdp session.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#12233]
- VSCode Version: 1.5.2 Linux deb version
- OS Version: Windows 10 Pro Insider Preview
- Remote Connection to: Ubuntu 16.04.1 LTS Desktop
- Linux xrdp: Xfce-session

Steps to Reproduce:

1.  On Windos 10, open Remote Desktop application
2.  Connect to Linux machine using IP Address provided.
3.  At the Xfec session, click on "Applications | Development | Visual Studio Code"

Results:
Nothing opens

Provide VS Code Verbose results:
maxt@orion:~$ code --verbose
Xlib:  extension "XInputExtension" missing on display ":10.0".
(4:29:39 PM) ### VSCode main.js ###
(4:29:40 PM) /usr/share/code/resources/app { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  locale: undefined,
  wait: false }
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".

Try Workaround from:
https://github.com/Microsoft/vscode/issues/3451
https://github.com/Microsoft/vscode/issues/9016
https://github.com/Microsoft/vscode/issues/11873

Changing both '/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0' and '/usr/lib/x86_64-linux-gnu/libxcb.so.1'
information: 's/BIG-REQUESTS/_IG-REQUESTS/' -> Didn't work!

This issue shouldn't be resolved with a workaround. It VS Code should work like JetBrains Python Editor "PC PyCharm" in a xrdp session. 

![pycharm_2016-09-18_18-10-30](https://cloud.githubusercontent.com/assets/19892435/18619477/8f6267fc-7dcb-11e6-9795-c89446499b68.jpg)

See attached image:
![vscode_notremoting_2016-09-18_17-43-13](https://cloud.githubusercontent.com/assets/19892435/18619445/896c6b14-7dca-11e6-99c1-57ebdfc2d4a4.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3451

**Comment by MaximoTrinidad** [comment]
Sorry! I copy/paste the information on #3451.
Thanks,
Max

**Comment by MaximoTrinidad** [comment]
In summary!  I was able to make it work in Ubuntu 16.04.1 remote session.

 There are two files I changed which I don't know which is the correct one:
    libxcb.so.1 and libxcb.so.1.1.0

Here are the steps for the workaround:
1. Using (sudo su) nautilus, Search and found files on folder "/usr/lib/x86_64-linux-gnu"

2. Backup both files to a backup folder.

3. Then, execute the following command (sudo su):
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.1
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.1.1.0

4. Copy both files to "/usr/share/code"

5. On Windows, open Remote Desktop connection, assign Linux IP-Address.

6. In Linux Remote session, click on the Applications menu, go to Development, then Visual Studio Code and the application open.

Honestly, there most be a better way to do this but it works.

**Comment by MaximoTrinidad** [comment]
OK!  Its May 27th, 2017 and I would have expect by now that VS Code (and Insiders) would already work using xrpd.  But, it isn't!!

This issue still Open as the workaround a permanent resolution as we need to manually fixed it.  
How about integrating the workaround steps into the installation steps?

![vscodexrdpissue](https://cloud.githubusercontent.com/assets/19892435/26521948/580059d2-42c3-11e7-83d3-83b4be120348.png)

**Comment by Tyriar** [comment]
@MaximoTrinidad the solution is a hack. We absolutely do not want to modify `libxcb` when installing vscode, who knows how that might impact other applications.

**Comment by MaximoTrinidad** [comment]
Hum! So, for VS Code, there are no resolution to this issue in the future to work in xrdp.
That's a little disappointing as there are Linux IDE products that can work in xrdp without any hack.
:(

Go ahead and closed this issue.

**Comment by Tyriar** [comment]
@MaximoTrinidad the root cause is an issue with the underlying platform, Electron https://github.com/electron/electron/issues/2256
