### ISSUE TITLE
Get SHA256 hash for Visual Studio Code installer file programmatically

### ISSUE THREAD

**Issue by amtadev** [microsoft/vscode#122396]
Hello,

Is there a web API (or otherwise) which would allow an automatic downloader script to fetch vscode installer's SHA256 hash, for any version of vscode including the latest? This would allow the script to verify the downloaded files automatically by comparing the hashes.

The hashes, for the **latest** version only, are currently shown in the bottom of the download [page](https://code.visualstudio.com/Download) in a folded mode (i.e. it needs to be expanded for the browser to fetch the hashes and show them). This doesn't present an easy way for an automatic script to fetch them.

Thanks

**Comment by amtadev** [comment]
@joaomoreno what was the resolution for this?

**Comment by joaomoreno** [comment]
@amtadev I was waiting for the code to be deployed.

You now have the following API available:

```
https://update.code.visualstudio.com/api/versions/commit:COMMIT_ID/PLATFORM/QUALITY
```

Examples:

```
https://update.code.visualstudio.com/api/versions/commit:c7119ae8b6390a5700f6b28f0f1511d676c96562/win32-x64/insider
https://update.code.visualstudio.com/api/versions/commit:c7119ae8b6390a5700f6b28f0f1511d676c96562/darwin/insider
https://update.code.visualstudio.com/api/versions/commit:054a9295330880ed74ceaedda236253b4f39a335/darwin/stable
```

**Comment by joaomoreno** [comment]
@amtadev, you can help us out by confirming things are working as expected in the latest Insiders release. If things look good, please leave a comment with the text /verified to let us know.

**Comment by amtadev** [comment]
This is /verified .. Thank you.

I accessed the link:
`https://update.code.visualstudio.com/api/versions/1.56.0/win32-x64/stable`
and got a json:
`{"url":"https://az764295.vo.msecnd.net/stable/cfa2e218100323074ac1948c885448fdf4de2a7f/VSCodeSetup-x64-1.56.0.exe","name":"1.56.0","version":"cfa2e218100323074ac1948c885448fdf4de2a7f","productVersion":"1.56.0","hash":"ab40232ae7fd669effe6c35ea34948349c273a11","timestamp":1620165132598,"sha256hash":"9719979567f6788bcddc675df29a028e995c2724b7a714280c1e14302c2d6faa","supportsFastUpdate":true}`
The sha256hash key gives the requested hash which is matching the hash calculated locally.

**Comment by amtadev** [comment]
@joaomoreno is there any documentation for the update.code.visualstudio.com API?

**Comment by joaomoreno** [comment]
To some extent: https://update.code.visualstudio.com/swagger.json
