### ISSUE TITLE
Workspace trust dialog should only appear once per folder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122304]
Refs: https://github.com/microsoft/vscode/issues/122228

1. Open a new worksapce -> notice the dialog. Say to not trust it
2. Close vscode
3. Open vscode. The dialog appears again 🐛 

I think showing a dialog for every untrusted workspace is a very bad user experience. I think this should only be done once and once a user makes the choice the dialog should not longer be automatically shown.

**Comment by sbatten** [comment]
i do agree, its a simple change I have not made to make my testing easier :P

**Comment by isidorn** [comment]
🕺

**Comment by sbatten** [comment]
Added a setting for this that defaults to "only the first time".

Verify with setting: `security.workspace.trust.enabled`

**Comment by isidorn** [comment]
I can look into veryfing this.
