### ISSUE TITLE
Default configured editor is not clear to me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122367]
Testing #122030

I have configured to use the hex editor for all issue notebooks but the picker does not really indicate that to me:

![image](https://user-images.githubusercontent.com/900690/116268710-dc144a80-a77d-11eb-9905-b993194ca1f3.png)

**Comment by connor4312** [comment]
Yes, I see `Defaults` on the first item all the time (I assume it's supposed to be Default) regardless of what my default editor is actually set to

**Comment by lramos15** [comment]
That was me just trying to separate sections between default and optional priorities. This is how quickpicks render separators

**Comment by connor4312** [comment]
As a random user (and a developer who hasn't touched custom editors in a while) I don't know what "defaults" and "optional" mean. They're all things I _can_ use to open the file.

**Comment by lramos15** [comment]
I can get rid of Defaults and Optional and add another thing similarly to `Currently Active` that says `Current Default`?
