### ISSUE TITLE
Can't "Open With..." from within VS Code Explorer Pane

### ISSUE THREAD

**Issue by Identifier** [microsoft/vscode#122345]
Issue Type: <b>Bug</b>

Open a folder in VS Code (I opened one by typing "code ." in the command prompt)

Right-click a file in the Explorer (presumably any file type, but I tried it on a .sln file), and then click "Open With..." in the context menu

Expected a choice to pop up with apps that can open that file (in this case I wanted to open the .sln file with the full Visual Studio instead of opening the .sln file in a VS Code editor window).

But instead, the file just opens in a normal VS Code editor on the right hand side of the window.  No choice was presented to choose a different app or even different editor type.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (3 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.98GB (23.06GB free)|
|Process Argv|. --crash-reporter-id 7b039a7a-d400-437b-9c0d-0aedc75be2b4|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.4.1
compare-folders|mos|0.21.0

</details>

**Comment by lramos15** [comment]
Open With is for opening different custom editors or notebooks for a given file within VS Code. To open a file with a different application you will have to go through your operating system's flow.

**Comment by Identifier** [comment]
Ok, can I change this to a Suggestion then to make it clearer when there is no custom editors or notebooks available to choose from?

**Comment by lramos15** [comment]
The next release will have an single option that says Text Editor, so it's clear that this is an editor picker internal to VS Code.
