### ISSUE TITLE
When picker has only one option, clicking gear opens the file

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122395]
I'd expect it to take me to the configuration
![recording - 2021-04-27T093925 099](https://user-images.githubusercontent.com/29464607/116279555-89666e80-a73c-11eb-824c-44977c0cd09c.gif)

Testing #122030

**Comment by lramos15** [comment]
This is the default behavior regardless of how many items are in the picker, but I agree that it can be confusing so I think next iteration we will be transitioning to @misolori's proposal found here https://github.com/microsoft/vscode/issues/122220
