### ISSUE TITLE
Trust workspace and install should open Trust Editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122312]
Refs: https://github.com/microsoft/vscode/issues/122228

1. Have an untrusted workspace
2. Install ESLint
3. Click on Trust Worksapce & Install

Workspace is trusted. However I think in this case we should automatically open the trust editor to educate the user what this is all about. Since all he or she wanted to do was install an extension.

As for the startup dialog I am of a different opinion, in that case we should not open the workspace trust dialog. Since that dialog provides more details, and the user was not trying to do anything else.

So my rule of thumb: if user tried to do something else and BY THE WAY said I Trust, we should open the Editor. If the dialog was only about workspace trust we should NOT open the trust editor.

**Comment by lszomoru** [comment]
> However I think in this case we should automatically open the trust editor to educate the user what this is all about. Since all he or she wanted to do was install an extension.

I think that opening the workspace trust editor automatically would get in the way of the action that the user is trying to perform. Imagine that a user is trying to debug their project, hit F5, trust the workspace, and then we automatically open the workspace trust editor. I do not think that would be a good user experience. The dialog that we show for an "action" that requires workspace trust contains a link to the documentation as well as a button to open the workspace trust editor. 

Closing the issue for now, but please feel free to reopen it if you would like to continue the conversation. Thanks!
