### ISSUE TITLE
tsc output messy code

### ISSUE THREAD

**Issue by wang37921** [Microsoft/vscode#12236]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
Win10, chinese, event change vscode local.json to locale to en, also got this problem
1. use default tsc configuration
2. CTRL+SHIFT+B
will got:
'tsc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by bpasero** [comment]
Encoding issue with tasks?

**Comment by wang37921** [comment]
yes

**Comment by dbaeumer** [comment]
Dups #3550
