### ISSUE TITLE
Enable extension in untrusted workspace should be enabled and guide to trust worksapce

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122307]
Testing #122228

1. Have an untrusted workspace, install eslint
2. Open extensions view, notice eslint is disabled
3. Context menu -> "enable" buttons are all disabled

I suggest to make these buttons enabled and that clicking on them takes the user to the workspace trust editor. I think that would be a nice flow.

![Screenshot 2021-04-27 at 12 28 28](https://user-images.githubusercontent.com/1926584/116227285-42847300-a754-11eb-9a18-bc21e223bd06.png)

**Comment by lszomoru** [comment]
This is a regression that has recently introduced and fixed today (thanks @sandy081!).
Tomorrow's insiders build will have the button to enable the extension which will prompt for trust.

**Comment by isidorn** [comment]
Thanks, I can verify this with tomorrow's vscode insiders build.
