### ISSUE TITLE
Cant remove file from editor

### ISSUE THREAD

**Issue by phedlund113** [microsoft/vscode#122377]
Issue Type: <b>Bug</b>

I had 2 instances of visual studio code running. Both had a copy of my_lib_task2.pcmd.
I updated and saved a copy in one instance of VSC then went to close the copy in the other instance. I was presented with 3 options Save, Dont Save and Cancel. 
No matter how many times i try, Don't save and Cancel act the same and I can get rid of the copy in the editor.

Open the same file in two instances of VSC
Edit one copy, save, then close that instance.
In the other instance close the same file 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (12.58GB free)|
|Process Argv|--crash-reporter-id 436f66be-c67d-4477-a1c1-3d895e42328a|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
printcode|nob|3.0.0
separators|ale|2.0.0
funclist|qrt|7.6.3
Bookmarks|ale|13.0.4
project-manager|ale|12.1.0
jupyter|ms-|2021.5.745244803
python|ms-|2021.4.765268190
cpptools|ms-|1.3.1
vscode-pylance|ms-|2021.4.2
todo-tree|Gru|0.0.213

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by phedlund113** [comment]
Upon repeating my tests with the insiders build I found the problem went away.
Whenever i saved the file in one instance of VSC, the same file in the second instance of VSC was updated automatically.


________________________________
