### ISSUE TITLE
Update status bar when output is set

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122341]
Testing #122263

> The provider is invoked when the cell content changes, when it executes, when its language changes, and when it scrolls into view

This is from the test plan and likely explains an issue that I am seeing with GHI notebooks. For them we add a status bar contribution with the number of matches and it seems I am asked for that before I know the answer and then not again. Steps are

* open GHI notebook
* run a cell
* :bug: no status bar entry
* re-run the cell
* status bar shows "Open N results"

**Comment by bamurtaugh** [comment]
I think I am seeing the same behavior.

I added a simple notebook cell status bar items provider from [here](https://github.com/microsoft/vscode/pull/121215#pullrequestreview-635049212) to Rest Book.
I ran a cell in the custom notebook, but the cell status bar remains at 0 (same count as cell that hasn't been run):
![image](https://user-images.githubusercontent.com/25310137/116284058-7efaa380-a741-11eb-9ae0-a9f2bd11f6f8.png)
On second run, it updates to 1.

I tested in a GitHub Issues notebook, and I see what seems to be the same behavior:
![image](https://user-images.githubusercontent.com/25310137/116284093-8b7efc00-a741-11eb-8fbc-9bf263227ec5.png)

![image](https://user-images.githubusercontent.com/25310137/116284098-8de15600-a741-11eb-917a-5facefee1af9.png)

I changed the cell input and got more data, and future runs also require a second run to update the status bar:
![image](https://user-images.githubusercontent.com/25310137/116284159-9c2f7200-a741-11eb-9aa0-558e4e246285.png)

![image](https://user-images.githubusercontent.com/25310137/116284313-cda83d80-a741-11eb-94f5-3c07afe1c6a8.png)

**Comment by roblourens** [comment]
It's supposed to update when outputs change, I'll check it out

https://github.com/microsoft/vscode/blob/e986377a6257c1e1d9199bb8e048867787cf7815/src/vs/workbench/contrib/notebook/browser/contrib/statusBar/cellStatusBar.ts#L109-L109

**Comment by jrieken** [comment]
> It's supposed to update when outputs change, I'll check it out

Might be some tight timing issues. When debugging, with breakpoints in the provider and at the place where execution is finished, this doesn't happen

**Comment by roblourens** [comment]
I call the provider too early, before the outputs are in the EH
