### ISSUE TITLE
Web: dialog for link opening could have a "Learn more" button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122353]
Testing #121763

This could point to some documentation such as https://code.visualstudio.com/docs/remote/codespaces#_how-do-i-allow-vs-code-to-access-my-clipboard-for-reading for how to configure the browser to never block popups for a Codespace.

**Comment by isidorn** [comment]
I like this idea. Might you know if I should create a permalink for this or I can just put the whole link in the code?

**Comment by isidorn** [comment]
And here's the wording 

![Screenshot 2021-04-29 at 14 38 44](https://user-images.githubusercontent.com/1926584/116551835-9def6600-a8f8-11eb-9b42-f0aedf9b1ef0.png)

**Comment by isidorn** [comment]
Adding bug so we get this verified
