### ISSUE TITLE
Rename and delete in explorer should have ... since they need additional info

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122316]
Related: https://github.com/microsoft/vscode/issues/122296

Both need additional info:

<img width="241" alt="Screen Shot 2021-04-27 at 4 55 10 AM" src="https://user-images.githubusercontent.com/2193314/116237173-bf8ff800-a714-11eb-8c27-4c93d26a4aea.png">

**Comment by isidorn** [comment]
Any change I do in the explorer raises a user revolt. So could do this start of next milestone.
Delete does not require additional user input (if I say do not ask again for prompt).

So I think only `Rename` should be `Rename...`
However I would wait for the editor to change `Rename Symbol` to be `Rename Symbol...` so they are aligned.
fyi @jrieken

**Comment by jrieken** [comment]
Not so sure about the `...` rules 

<img width="748" alt="Screenshot 2021-04-27 at 14 36 26" src="https://user-images.githubusercontent.com/1794099/116242174-f4786b00-a765-11eb-9e9a-ec350b9de554.png">

**Comment by Tyriar** [comment]
Finder is inconsistent; "Tags..." opens an inline pop similar to rename, but rename doesn't have the .... It might not be the best example.

**Comment by misolori** [comment]
Using ... on actions when needing user input has been a consistent pattern we've used for named actions. So we should try to keep it consistent.

**Comment by lramos15** [comment]
Will take this in start of next milestone

**Comment by lramos15** [comment]
@misolori From a UX perspective it appears `...` is used when a quick input is present but not when an inline edit widget is. So I believe that's why things like `Rename` and `Rename Symbol` do not have `...`, so is the UX guideline that inline edit widgets also should have `...`?

**Comment by misolori** [comment]
I would say that any action that requires user input should use the `...`.

I am seeing the same for toolbar actions like new file/folder in the tooltip as well while the quick pick and app menu do show it.

<img width="170" alt="CleanShot 2022-08-16 at 08 45 32@2x" src="https://user-images.githubusercontent.com/35271042/184922365-5fde173d-b6ac-4583-9d3d-e105a76cb084.png">

<img width="202" alt="CleanShot 2022-08-16 at 08 45 40@2x" src="https://user-images.githubusercontent.com/35271042/184922411-436ccd31-bb7c-4405-8e42-274068cfade9.png">

<img width="303" alt="CleanShot 2022-08-16 at 08 45 47@2x" src="https://user-images.githubusercontent.com/35271042/184922443-9d0352c0-9b1a-4bc0-964c-0b921ee18cd5.png">
