### ISSUE TITLE
Getting started should not use images/screenshots

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122397]
I feel we need consistent size/sharp schematic UX if we want to show them:

![recording (1)](https://user-images.githubusercontent.com/900690/116281002-8cd41700-a789-11eb-9345-d71fbf31fb3d.gif)

//cc @misolori

**Comment by misolori** [comment]
@bpasero are you suggesting to use illustrations instead? And if we do use images to have the size be consistent?

**Comment by digitarald** [comment]
Consistent sharpness seems to be the main issue, especially with the latest batch I added. I can fix that in the figma export step.

We have some illustrations we want to test but its hard to get them for every entry.

**Comment by bpasero** [comment]
Yes, illustrations and not actual screen shots. ideally SVGs that scale with any resolution.

**Comment by JacksonKearl** [comment]
We can support SVGs for ourselves, but there are some security concerns with rendering extension-provided SVGs, even in an iframe as far as I understand. @mjbvz may be able to fill in more info.

**Comment by digitarald** [comment]
Continued in #125877
