### ISSUE TITLE
Backup restore does not always preserve tab order

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122300]
Testing #122029

Following the steps in the test plan, create some dirty untitled files using vscode stable, open some files outside of the folder and make them dirty.
Reopen the same user data dir with vscode insiders. All the editors are properly restored but the tab order is not respected. Untitled editors seem to always be at the end, and their order is sometimes reversed.

I think this is acceptable, but wanted to let you know.

**Comment by bpasero** [comment]
@isidorn I assume this happened when you passed folder and file name from the command line?

**Comment by isidorn** [comment]
@bpasero yes, I think that was the case.

**Comment by bpasero** [comment]
Yeah that is something we can probably not easily resolve because when VSCode opens without restoring the layout we basically just open each backup editor individually and have no knowledge about the previous order. I think this is fine to keep, we always did that.

**Comment by isidorn** [comment]
Fine by me, thanks for the explanation.
