### ISSUE TITLE
Workspace trust dialog should mention parent name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122302]
Testing #122228

In the workspace trust dialog this is the current checkbox. I suggest to also include the parent folder name, for example if it is Development.

```
"Trust the author of all files in the parent folder 'Development'"
```

No need to have `I` twice

![Screenshot 2021-04-27 at 12 05 11](https://user-images.githubusercontent.com/1926584/116224501-03085780-a751-11eb-9ac3-70dc335d356b.png)

**Comment by lramos15** [comment]
@sbatten For consistency should this all go in the split button in the workspace trust view.

**Comment by sbatten** [comment]
that button doesn't give you a lot of space to render as much :/
