### ISSUE TITLE
Editor associations setting is overly verbose

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122365]
Testing #122030

Compared to `files.associations` which is just:

```json
"files.associations": {
    "*.extension": "language"
}
```

Why is the editor one so complicated?

```json
"workbench.editorAssociations": [
    {
        "viewType": "luna.editor",
        "filenamePattern": "*.png"
    }
]
```

I would suggest:

```json
"workbench.editorAssociations": {
    "*.png": "luna.editor"
}
```

**Comment by lramos15** [comment]
What are the repercussions from changing an existing setting. Also, I believe a setting such as 
```
"workbench.editorAssociations": {
    "luna.editor": ["*.png", "*.ico", "*.jpg"]
}
```
would be cleaner.

**Comment by bpasero** [comment]
> What are the repercussions from changing an existing setting

I think you can still for some milestones read the old values and/or rewrite to the new format. I would maybe ping Sandy or Rob on this matter what they suggest.

**Comment by lramos15** [comment]
@roblourens or @sandy081 Thoughts?

**Comment by Tyriar** [comment]
Can handle that with glob:

```js
"workbench.editorAssociations": {
    "*.{png,ico,jpg}": "luna.editor"
}
```

This would align better with `files.associations` as well as `files.exclude` where the key is the file pattern.

**Comment by lramos15** [comment]
I understand that in can be handled with a glob, but it's a bit more difficult I think to compute these joined globs when the user for examples configures .png and .jpg to be luna paint the gear logic would find the existing luna editor entries and then do a join on the glob pattern in a way rather than a nice simple array. Either way works for me, but just what I was thinking when thinking of an array.

**Comment by Tyriar** [comment]
This discussion was headed towards using global storage though, so you can use whatever structure you want there without worrying about editing globs. Something like this seems ideal so the extension lookup is fast:

```
{
  "ico": "luna.editor",
  "png": "luna.editor"
}
```

**Comment by lramos15** [comment]
The discussion in this thread is regarding the user setting, the storage structure could be a different argument which I haven't thought too much into

**Comment by Tyriar** [comment]
But if the storage structure changes it removes the issue you had with making `workbench.editorAssociations` consistent with the other settings.

**Comment by lramos15** [comment]
I'm sorry, I think I'm lost. There's two parts here
1. Which is what @connor4312 suggested is to preserve the "keep current" option in the storage service to not clutter your settings
2. What @bpasero suggested, which is to modify the user setting to no longer be a giant object array.

These two things are distinct in my mind currently.

**Comment by Tyriar** [comment]
> I understand that in can be handled with a glob, but it's a bit more difficult I think to compute these joined globs when the user for examples configures .png and .jpg to be luna paint via the gear logic would find the existing luna editor entries and then do a join on the glob pattern in a way rather than a nice simple array.

You don't need to do this if you use the storage service.

**Comment by lramos15** [comment]
Why wouldn't I? the user could still configure to their settings via the gear icon or configure default button. We would just be using the storage service for the "keep current" option.

**Comment by Tyriar** [comment]
Now I'm confused. If you used globs you would share the logic that the files settings/search uses to parse them out easily.

**Comment by lramos15** [comment]
So the hope is to only use the storage service for the "Keep Current" that way when new editors come around you get prompted again and we don't dirty your setting. 

As for the setting, I understand it would be different than what the others use but we already have our own glob parsing using the internal glob library. If we use an array it doesn't really require users to have an in-depth knowledge of globs and internally it's basically `editorID: set<globs>`

**Comment by Tyriar** [comment]
Consistency is important was my main point. Don't need to necessarily know how globs work as well:

```
"workbench.editorAssociations": {
    "*.ico": "luna.editor",
    "*.png": "luna.editor"
}
```

**Comment by lramos15** [comment]
I guess my argument was would it make more sense for the user to have a 1:1 mapping of glob to editor or a 1:many mapping of editorID to glob patterns. Another reason I liked the 1 to many is that it's less lines 😝

**Comment by roblourens** [comment]
The setting declares my "preferred" editor for a filetype, so it makes sense for the setting to match `files.associations` with a single entry per file type right? What happens currently if I list two different editors for `*.png`.
