### ISSUE TITLE
Should my setting be removed when I switch back to default editor?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122368]
Testing #122030

Just wondering, when I once picked a custom editor for a file and this writes to my settings and then I go ahead and pick the default text editor again, my settings file still has a change like this one:

![image](https://user-images.githubusercontent.com/900690/116269092-33b2b600-a77e-11eb-90dd-0cfd7c320879.png)

So the operation is not really idempotent.

**Comment by lramos15** [comment]
Well let's say you have two conflicting default editors, and you select the text editor to be your default for it. If we just didn't write to your setting you would continue to receive the conflicting default notification. Additionally, writing to the setting ensures no overload logic can take over. In the case above not having the setting would still open the github-issues notebook even though you asked for the text editor.
