### ISSUE TITLE
Not offered hex editor when hex editor is installed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122392]
And I right click -> open with...
![recording - 2021-04-27T093516 396](https://user-images.githubusercontent.com/29464607/116279055-f1688500-a73b-11eb-8dce-b25564e910d0.gif)

Testing #122030

**Comment by meganrogge** [comment]
The command also isn't working for me

**Comment by lramos15** [comment]
Weird. I just tried this on latest insiders on windows, mac, and linux without a repro. Did you reload the window after installing the hex editor just to make sure everything initialized correctly?

**Comment by meganrogge** [comment]
Reloading the window worked

**Comment by lramos15** [comment]
It was this issue https://github.com/microsoft/vscode/issues/122425. Fixed :)
