### ISSUE TITLE
Trust editor: no button to untrust the folder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122310]
Refs: https://github.com/microsoft/vscode/issues/122228

If you have an untrusted folder there is a nice blue button to trust it.
However if you have a trusted folder there is no button to no longer trust it Instead I have to go to the list of trusted folders, find mine and click X on it. I think this flow would be greatly improved by adding a button directly like in the `Trust` case. Also it would make the two scenarios more consistent

![Screenshot 2021-04-27 at 12 36 44](https://user-images.githubusercontent.com/1926584/116228222-449b0180-a755-11eb-8b59-ef9b57a1566d.png)
![Screenshot 2021-04-27 at 12 37 19](https://user-images.githubusercontent.com/1926584/116228255-51b7f080-a755-11eb-9719-79becc3a1aab.png)

**Comment by sbatten** [comment]
@isidorn we can only do this nicely if the folder is trusted directly. i.e. not by the parent folder. also, recall that this scenario is not a good one since once you have trusted a folder, you are already at risk

**Comment by isidorn** [comment]
Good points. Putting the button if it is trusted directly sounds reasonable to me

**Comment by bpasero** [comment]
But shouldn't the button also move? Now it is always in the "In a trusted folder" box? Or maybe move outside of it?

![image](https://user-images.githubusercontent.com/900690/116381748-7b385100-a815-11eb-9cc4-349b871a57f0.png)

**Comment by lszomoru** [comment]
Agreed. It feels odd that the button to Trust/Don't Trust is always in that box.

**Comment by sbatten** [comment]
will fix this, I was curious if the tester would think that was weird or nice, got my answer
