### ISSUE TITLE
"Configure Default" quickpick ambiguity

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122429]
Testing #122030

1. Open a png file with Luna Paint installed
2. See the notification and choose to configure the default editor
3. The quickpick is not clear:
    - The placeholder says to "select editor for <file>". It should say "select default editor for .png files"
    - There's a gear icon to set the default editor, but that's what I'm already doing -- that should be removed

**Comment by lramos15** [comment]
I agree this was confusing so I pushed a fix, next iteration we will be removing the gear entirely in favor of a "Configure Default" entry at the bottom
