### ISSUE TITLE
`NotebookCellKind.Markdown` might be too limiting

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#122492]
Testing #122210

There are two kinds of `NotebookCellKind`, `Markdown` and `Code`. But maybe in the future we would like to have HTML documentation cells or LaTeX, etc.

It might be a good idea to rename `NotebookCellKind.Markdown` to something like `Documentation`, `Meta`, `Notes` or to change the kinds to be `Executable`/`NonExecutable`.

**Comment by jrieken** [comment]
Thinking aligned: we have the suggestion to renaming this to `Markup` (see https://github.com/microsoft/vscode/issues/105933#issuecomment-824033700)

**Comment by jrieken** [comment]
closing as /duplicate
