### ISSUE TITLE
Debugging in an untrusted workspace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122487]
Testing #122232

We should align the wording in this dialog with the one that we show on startup. Right now they differ.
![image](https://user-images.githubusercontent.com/4674940/116330356-30b9c480-a782-11eb-9d4a-e1098cb9cac7.png)

I also suggest to rephrase the dialog as a confirmation rather than as re-asking the trust question. Something along the lines of: "You are about to execute files in this folder. Do you confirm you trust the authors of all the files in this folder?"

**Comment by isidorn** [comment]
I am open for suggestions here. @weinand and me created this wording with consultation from @connor4312 @sbatten and @lszomoru 

@kieferrm so your suggestion is to replace "Do you trust the files in this folder?" with 
"You are about to execute files in this folder. Do you confirm you trust the authors of all the files in this folder?"

This works for me but is a bit long

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/122426
Since that one is older
