### ISSUE TITLE
Unable to untrust a folder from manage trust content

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122416]
https://user-images.githubusercontent.com/35271042/116291145-1ca5a100-a749-11eb-92b5-1d90df3986bf.mov

Steps to Reproduce:

1. Don't trust folder
2. Open manage trust
3. Trust folder by clicking "Trust" on the left
4. Attempt to untrust by clicking on right side
5. 🐛 No button for untrusting

If there is a button on the left to trust, there should be one on the right to undo it

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/122310
