### ISSUE TITLE
Remote extensions and workspace trust

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#122446]
Testing #122252

Maybe an issue for the codespaces extension itself.

1. Add `"security.workspace.trust.enabled": true,` to settings
2. Install the GitHub codespaces extension and have some codespace that you've already created on the list, but not opened before on desktop
3. Try to connect to that codespace

The workspace trust dialog disappears, but in the background the resolver extension has already failed, which makes sense since the trust state isn't known. But clicking "Yes, I trust the authors" does not restart the resolve process again, just leaves the workspace open and disconnected

**Comment by RMacfarlane** [comment]
Actually this isn't specific to the codespaces extension, I see the same thing wish SSH and containers

**Comment by sbatten** [comment]
Closing as you currently need to override the remote extension trust requirements
