### ISSUE TITLE
Some detection decides not to upgrade a file

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#122442]
Testing #122190

I found this user's `tasks.json` with the version set to 2.0.0 but seemed to be using v1 tasks.

To get this file to upgrade properly, I first had to change the version to 0.1.0 which I can understand. But even that was not sufficient. It seems that because the file has used the deprecated `_runner` property, the file also was not upgraded. Even with `runner` and version `0.1.0`

https://github.com/dylanparry/electricfreedom/blob/master/.vscode/tasks.json

**Comment by alexr00** [comment]
Good find, thanks!

**Comment by sbatten** [comment]
assumed that marking the version explicitly to 2.0.0 even if using v1 style tasks should not auto-upgrade
