### ISSUE TITLE
Using find widget in cells and undoing causes errors in files

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122464]
Testing #122033

https://user-images.githubusercontent.com/35271042/116318569-d0b72400-a769-11eb-9c81-333b0ed7fa28.mov

1. use find widget
2. replace all instances of a variable
3. undo
4. 🐛  see errors

**Comment by jrieken** [comment]
Hm... This doesn't reproduce for me but it sounds scary. This either means the underlying text model (only buffer) is updated or that the extension host sync isn't working 

@rebornix Was there some bug in find-replace that could have caused this?

**Comment by misolori** [comment]
Hmm...I can't seem to repro today. Maybe something changed.
