### ISSUE TITLE
Editing the same file in different windows doesn't update code cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122465]
Testing #122033

https://user-images.githubusercontent.com/35271042/116319390-4b347380-a76b-11eb-91e9-3465dce54579.mov

> notebooks (only if not dirty) update when file changes externally

1. open the same file in different windows
2. edit markdown and code cells in one window
3. :bug: see the code cell changes don't update in the other

**Comment by jrieken** [comment]
Very likely a dupe of an issue I have fixed yesterday. This doesn't repro for me anymore, @misolori can you please try again

**Comment by jrieken** [comment]
close - this should be working now
