### ISSUE TITLE
Theme/syntax highlighting worse in Codespaces than in VS Code

### ISSUE THREAD

**Issue by nathancarter** [microsoft/vscode#122421]
- VS Code Version: 1.55.1
- OS Version: OS X 10.14.6

Steps to Reproduce:

1. Create a GitHub Codespace for a project.  In my case, it had JavaScript files in it.
2. Open a file and you will see little to no syntax highlighting.  However, on my Mac laptop or Windows desktop, running VS Code produces consistent and useful syntax highlighting for all source code files, including the same files in the same project.

Does this issue occur when all extensions are disabled?: Yes

(More specifically, the laptop/desktop still show nice syntax highlighting with no extensions enabled, and the Codespace has very few extensions enabled, all of which are also running on my laptop/desktop.)

How the syntax highlighting looks on my laptop/desktop when running `code --disable-extensions .`:

<img width="637" alt="Screen Shot 2021-04-27 at 2 34 05 PM" src="https://user-images.githubusercontent.com/1316622/116296334-196ddd80-a768-11eb-9da4-ef8d995f039e.png">

(In other words, it looks great.  This is using the built-in Dark or Dark+ theme.  Looks the same without the `--disable-extensions` flag.)

How the syntax highlighting looks for the same file in a GitHub Codespace for the same project:

<img width="641" alt="Screen Shot 2021-04-27 at 2 34 39 PM" src="https://user-images.githubusercontent.com/1316622/116296414-330f2500-a768-11eb-8946-8701f94b0795.png">

That's for the Dark theme.  For the Dark+ theme, it's a little better:

<img width="644" alt="Screen Shot 2021-04-27 at 2 34 56 PM" src="https://user-images.githubusercontent.com/1316622/116296433-3acec980-a768-11eb-80b1-79cc103f3b08.png">

In case it's relevant, several theme extensions I installed in the Codespace gave the error shown below if attempting to set them as the default color theme.  Perhaps it's not relevant; I just include it here since it may be useful to you.

<img width="453" alt="Screen Shot 2021-04-27 at 2 26 06 PM" src="https://user-images.githubusercontent.com/1316622/116296547-5b971f00-a768-11eb-91f5-21b2cbcea983.png">

**Comment by nathancarter** [comment]
Just to answer the bot:  The issue it suggests is not related.

**Comment by aeschli** [comment]
The loading error explains why the theme doesn't work. Can you file this against https://github.com/github/codespaces ?
Thanks a lot!

**Comment by nathancarter** [comment]
That link does not go to a public source code repository.  The closest thing I can find is a public feedback repo [here](https://github.com/github/feedback) for a variety of products that includes Codespaces.  Not sure what the next step is, sorry!

**Comment by aeschli** [comment]
Ok, I'll file it for you then.

**Comment by nathancarter** [comment]
Thanks!  Is that because the repo is private and I can't see it?  If it is not private, I would still like to follow the issue, so please drop a link here if you have time.  Thanks again!

**Comment by aeschli** [comment]
Yes, unfortunately the repo is private, so you don't see the link. I will keep you updated.

**Comment by legomushroom** [comment]
@nathancarter thanks for reporting this 👍 Was it in the web client or the desktop one? Did you capture logs by chance? If that was the browser client, you can copy all the logs from the browser devtools directly. 😊  **The logs may contain your private info** so please send it to be directly at `olsolomk@microsoft.com` or `legomushroom@github.com` to prevent exposure. 🤗
