### ISSUE TITLE
Test explorer does not render fully when not visible on launch

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122400]
Steps to Reproduce:

1. hide test explorer
2. open vscode folder
3. make text explorer visible

=> 🐛 list does not render

![image](https://user-images.githubusercontent.com/900690/116281402-fb18d980-a789-11eb-839f-a3deba68f59b.png)

![recording (2)](https://user-images.githubusercontent.com/900690/116281570-226fa680-a78a-11eb-9189-d6dde1c15c5a.gif)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/122351

You can jiggle the side of the sidebar to force a relayout for now
