### ISSUE TITLE
Edit and remove path are not keyboard accessible on workspace trust editor

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#122443]
Testing #122252

1. Add "security.workspace.trust.enabled": true to settings
2. Trust a folder
3. Run the "Workspaces: Manage Workspace Trust" to open the workspace trust editor
4. Tab through to the trusted folders list, the edit and remove buttons only show up on hover
![trusted-folders](https://user-images.githubusercontent.com/3672607/116304402-639a9300-a757-11eb-983f-884b26e6135c.gif)

**Comment by sbatten** [comment]
This follows the same behavior as the widget in settings editor, you first tab to the table, use arrow keys to select the time in the list, then tab to the actions
