### ISSUE TITLE
Long terminal title hides terminal buttons 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122454]
Testing #122242

1. Give a terminal a long name
2. Now resize the VS Code window so that the panel is small (this is easy to hit when the panel is shown to the left/right

**Bug**
The long terminal title pushes the buttons to its right off screen:

![Screen Shot 2021-04-27 at 1 47 19 PM](https://user-images.githubusercontent.com/12821956/116310607-17535100-a75f-11eb-93ab-6b1878d253b9.png)

Here for example, notice how the chevron is partially clipped. 

When this happens, I'd expect the title to be truncated so that the buttons can still be accessed

**Comment by Tyriar** [comment]
This got reverted in https://github.com/microsoft/vscode/pull/128483
