### ISSUE TITLE
Native Notebooks - Outline Broken

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#122480]
Version: 1.56.0-insider (user setup)
Commit: 9a4d524f909e09079fec7abb82f2efde2172da7c
Date: 2021-04-27T06:15:26.914Z
OS: Windows_NT x64 10.0.19042

Notebook outline broken, clicking on markdown or code does not scroll the notebook anywhere.

**Comment by jrieken** [comment]
@lramos15 this is a problem with editor override service. While my override handler return options (which are vital to reveal cells) they aren't forward to the actual editor

**Comment by jrieken** [comment]
@lramos15 I have pushed f608a090a6a which I believe fixes this but please review and double-check
