### ISSUE TITLE
Enter to edit the folder path

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122449]
Testing #122252

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/876920/116307611-639c9200-a75b-11eb-8f1c-7636b4b0d9c7.png">

We may want to support enter to edit the folder path like the file explorer.

**Comment by joaomoreno** [comment]
I say <kbd>F2</kbd> instead.

**Comment by sbatten** [comment]
this widget is currently the same as in the settings editor, that doesn't appear to have any shortcut to edit. would you expect `F2` there? I think enter or space makes more sense to me.

**Comment by lszomoru** [comment]
After adopting the table widget, one can hit `Enter` to edit the path.
