### ISSUE TITLE
'Enter' on a quick fix is not working

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12246]
_From @sandy081 on September 7, 2016 14:22_

Steps to reproduce:

- Click on a quick fix (yellow bulb)
- You see a message for eg: `Fix this "Missing Semicolon" tslint failure?`
- Press 'Enter'

Quick fix is not applied.

_Copied from original issue: Microsoft/vscode-tslint#82_

**Comment by egamma** [comment]
Actually you can also not navigate in the menu of quick fixes using the cursor keys. 
![image](https://cloud.githubusercontent.com/assets/172399/18625177/02d4602e-7e4d-11e6-953f-104d145140a1.png)

Moving to VS Code for investigation.

**Comment by jrieken** [comment]
@sandy081 @egamma Do you have more steps for this? I have a dummy code action provider and with that I can't reproduce

![sep-20-2016 11-07-52](https://cloud.githubusercontent.com/assets/1794099/18664365/9fd544da-7f22-11e6-9e0a-722a90bcd099.gif)

**Comment by egamma** [comment]
I can reproduce it in the following vscode-tslint setup:

Install vscode-tslint

`tslint.json`
```json
{
    "rules": {
        "no-trailing-whitespace": true
    }
}
```

Create a .ts file with has several trailing white spaces:
![code-action](https://cloud.githubusercontent.com/assets/172399/18675304/39eb5d46-7f52-11e6-8d37-031ffd642633.gif)

Neither the `Enter` key nor the cursor keys work in the pop-up.

**Comment by jrieken** [comment]
Thanks - I can repo. This only happens when you select the light bulb but when triggering the widget with `cmd+.`. My guess is that we don't set a context key in that case...

**Comment by sandy081** [comment]
@jrieken It's simple
- Get a tslint warning for missing semi-colon
- You see a light bulb
- Click on the light bulb
- Press down arrow
- Press Enter

Nothing happens
