### ISSUE TITLE
Add entry for workspace file instead of containing folder

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#122408]
Testing #122233

> Confirm that the workspace file is saved, and an entry for the folder storing the workspace file is added to the list of trusted folders

Following the steps in https://github.com/microsoft/vscode/issues/122233, I actually found the end result surprising. By saving my workspace to a location I haven't trusted before, I open up everything under that folder as trusted. If I save the workspace somewhere towards the root, I unintentionally trust a bunch of folders without warning. I would expect workspaces files to be treated somewhat specially, for trust to be determined based on whether the paths in them are trusted, or for the actual file name to show up in the trusted list

**Comment by lszomoru** [comment]
Fixed with 58adf722d1aac67ec043f146a85512c13a515dc0
