### ISSUE TITLE
Font issue in terminal

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122424]
Testing #122241

I haven't changed settings, but when creating a zsh on OSX from the drop down then it uses a different font and the cursor location is confused.

This is the first terminal

![image](https://user-images.githubusercontent.com/172399/116297780-ecd3b900-a79b-11eb-85c5-c253ab5742f1.png)

This is the second one

![image](https://user-images.githubusercontent.com/172399/116297678-d2014480-a79b-11eb-9402-c1329218aebb.png)

This is how a bash terminal is rendered

![image](https://user-images.githubusercontent.com/172399/116297954-23a9cf00-a79c-11eb-9bcb-6e0e0a88bbeb.png)

**Comment by nufrankz** [comment]
I'm having this problem also. On a fresh install of Windows 10 x64 with the specs below. I turned on Sync from my Macbook VSCode Insiders installation. Thanks.

Version: 1.56.0-insider (system setup)
Commit: 9a4d524f909e09079fec7abb82f2efde2172da7c
Date: 2021-04-27T06:15:26.914Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
