### ISSUE TITLE
Can't Ctrl+Enter to execute notebook cell

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#122407]
Testing #122263

Maybe I'm missing something (since I don't think I usually ctrl+enter to run notebook cells), but I can't seem to get ctrl+enter to run my cells. It either just does a normal enter if I'm focused on the code within the cell, or creates a new cell if I focus outside of it. See gif below.

![recording (13)](https://user-images.githubusercontent.com/25310137/116284996-8e2e2100-a742-11eb-80ab-9e489bb82f82.gif)

If I've missed something/this is user error, please feel free to close.

**Comment by roblourens** [comment]
But the run button works right? Is this in a VM? Sometimes for me it messes with keybindings like this. Could you try running the command "Toggle Keyboard Shortcuts Troubleshooting",  try it again, and grab the log?

**Comment by bamurtaugh** [comment]
Correct, the run button works. It's not a VM, I'm just on my Windows 10 machine.

Here are the logs:

[2021-04-28 09:10:45.226] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-04-28 09:10:45.227] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-04-28 09:10:45.227] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-04-28 09:10:45.380] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Enter, keyCode: 13, key: Enter
[2021-04-28 09:10:45.380] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Enter, keyCode: 3 ('Enter')
[2021-04-28 09:10:45.381] [renderer1] [info] [KeybindingService]: | Resolving ctrl+Enter
[2021-04-28 09:10:45.381] [renderer1] [info] [KeybindingService]: \ From 13 keybinding entries, matched editor.action.insertLineAfter, when: editorTextFocus && !editorReadonly, source: built-in.
[2021-04-28 09:10:45.630] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
[2021-04-28 09:10:45.931] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.

Here's the version info:
Version: 1.56.0-insider (user setup)
Commit: 13f1afffab09548c10ddb3bc5d5db52587876ad8
Date: 2021-04-28T04:52:06.990Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
Have you customized this keybinding? It's supposed to be ctrl+alt+enter by default

**Comment by bamurtaugh** [comment]
Looks like I still have cell execution set to the default ctrl+alt+enter, but the Jupyter extension is also registering it as ctrl+enter:

![image](https://user-images.githubusercontent.com/25310137/116449331-eaf70d80-a80e-11eb-98c4-afaf40e879d0.png)

I just tried ctrl+alt+enter, and it worked (the cell ran). 

I disabled the Jupyter extension, and now the cell reads to use ctrl+alt+enter:
![image](https://user-images.githubusercontent.com/25310137/116449869-7d97ac80-a80f-11eb-8621-5116ef41e403.png)

And I no longer have the overlapping shortcuts:
![image](https://user-images.githubusercontent.com/25310137/116449924-8ee0b900-a80f-11eb-804d-889d83695ba8.png)

In the first case, since ctrl+alt+enter was required, should the cell read to use ctrl+alt+enter to execute? I'd think other users might encounter this where they have the Jupyter extension and its keybindings contributed.

**Comment by roblourens** [comment]
Oh yeah, so that one is from the Jupyter extension, but doesn't work due to builtin keybindings, thanks.

@rebornix should extension keybindings take precedence over builtin ones? I guess I don't know how the precedence works. FYI @DonJayamanne I don't know whether this worked at some point in the past

**Comment by claudiaregio** [comment]
We have run into this same issue with users, couldn't figure out why Shift + Enter or Ctrl + Enter didn't work for them. I thought extension shortcuts took precedence but the source on the right for that notebook contribution appears to be default, not extension...

**Comment by roblourens** [comment]
Derp, it works but only in jupyter notebooks. Going back to the hardcoded keybindings for now. Same as last release.

**Comment by claudiaregio** [comment]
@roblourens Could it display a shortcut based on view-type per chance? Or allow extensions to hide? Ideally the Jupyter extension could hide since our users are very ingrained with their keyboard shortcuts. If we absolutely have to show something, could it be designed in such a way that it changes based on view-type? That way the Jupyter users aren't seeing Ctrl + Alt + Enter to run? 

We received feedback it was too many keys to run and they wanted to just be able to use Ctrl + Enter. We had to educate them that Ctrl + Enter actually was supported because upon seeing that shortcut message they believed it was not.

**Comment by roblourens** [comment]
We don't actually have a way to look up the keybinding for a command with a certain context. @alexdima I want to add this capability to the keybindings service by letting `lookupKeybinding` take a CKS like this

```ts
lookupKeybinding(commandId: string, target?: IContextKeyService): ResolvedKeybinding | undefined;
```

is that ok?

**Comment by roblourens** [comment]
Yes @claudiaregio I'll definitely support showing the right keybinding, I just didn't realize that we aren't looking it up in context, I've mostly used mac/linux where it's the same across types.

**Comment by roblourens** [comment]
Opened https://github.com/microsoft/vscode/issues/122768 for a fix for May

**Comment by bamurtaugh** [comment]
Marking as verified as I now see "Press Ctrl+Alt+Enter to execute cell" in notebooks I create, and the keybinding works properly.

![image](https://user-images.githubusercontent.com/25310137/117031547-87a92780-acb5-11eb-8e95-d303e2f37ad4.png)
