### ISSUE TITLE
Should keeping the "current" editor dismiss and no-op?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122433]
Testing #122030

I like to keep my settings file clean-ish, when possible. If the editor for a new opened file is already what I want, we could store a "dismiss" in global storage and not write anything to the settings file.

**Comment by lramos15** [comment]
The reason I avoided this is I wanted it to be easy for you to change your decision and global storage isn't very accessible. At least with the settings file you know exactly what happened and where to look to undo it.

**Comment by connor4312** [comment]
If I change my decision I can use `Reopen With`. It's not _immediately_ discoverable, but if I'm using custom editors there's a good chance I know about this menu / will have to know about it at some point.

**Comment by lramos15** [comment]
I'm still against using global storage since it's not discoverable at all, but I would love the input from people like @Tyriar , @mjbvz , @rebornix , @bpasero , and @jrieken who's work surrounds these flows.

**Comment by jrieken** [comment]
> we could store a "dismiss" in global storage and not write anything to the settings file.

I also don't like when settings are used like that. I am in favour of global state which is sync'd across machines

**Comment by Tyriar** [comment]
I'd prefer global storage as well since it supports sync.

**Comment by lramos15** [comment]
Isn't settings synced across machines as well?

**Comment by Tyriar** [comment]
Yes, but this is a mess and would make my settings file way too big:

<img width="474" alt="Screen Shot 2021-04-28 at 7 10 07 AM" src="https://user-images.githubusercontent.com/2193314/116418211-c55b0b80-a7f0-11eb-8f97-d089b98a9b5b.png">

Sure I could probably combine them as it's a pattern but most users wouldn't.

**Comment by Tyriar** [comment]
Well, it's already big, I don't want to contribute more where it could be avoided.

**Comment by bpasero** [comment]
Btw I think the setting for workbench editor associations is overly complex, I had reported that as https://github.com/microsoft/vscode/issues/122365 already and think it should be simply `pattern: editorId`.

**Comment by lramos15** [comment]
@rzhao271 When the notification pops up and you click keep current or the x button you shouldn't see a setting change in your `settings.json`, but the next time you open that file you also shouldn't see the notification.
