### ISSUE TITLE
Show errors and warnings in the files explorer

### ISSUE THREAD

**Issue by keyiis** [Microsoft/vscode#12245]
Has any plugin can hint/mark error file in resource manage?looks like below
![-1](https://cloud.githubusercontent.com/assets/7766085/18624201/3ea0420a-7e78-11e6-85f3-6d51eb9a5e7c.jpg)

**Comment by dbaeumer** [comment]
Sounds to me like error overlays in the explorer.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/782
