### ISSUE TITLE
Collapse the xml node 折叠xml节点显示错误

### ISSUE THREAD

**Issue by MyErpSoft** [Microsoft/vscode#12242]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.Open the xml file by vsCode;
打开附件的xml文件；
[ValidatorContainer.zip](https://github.com/Microsoft/vscode/files/479315/ValidatorContainer.zip)

2.  Collapse the ‘Validators’ node. show this image,It's error.(It's right in vs2015 or vs2008).
折叠‘Validators’节点，错误，‘Validators’的下一个节点应该是‘ContextDatas’而不是‘Description’
vs2015或vs2008显示正常。

**Comment by joaomoreno** [comment]
In VSCode, formatting works based on indentation. The file has a _broken_ indentation, given its contents. Collapsing works if you run the `Format Code` command.
