### ISSUE TITLE
PHP7.1.0-RC1 not supported ?

### ISSUE THREAD

**Issue by CyrilCharlier** [Microsoft/vscode#12249]
- VSCode Version: 1.6.0-insider
- OS Version: Win10

Steps to Reproduce:
Install PHP 7.1.0-RC1 and you will get this error : 

The language server needs at least PHP 7 installed and in your PATH. Version found: 7.1.0-RC1

![2016-09-19_10h02_57](https://cloud.githubusercontent.com/assets/11455745/18625652/43fdd1d6-7e50-11e6-966c-05da22141596.png)

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://github.com/felixfbecker/vscode-php-intellisense

**Comment by CyrilCharlier** [comment]
OK thanks
