### ISSUE TITLE
icon update only works after window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122470]
Testing #122248

Update the icon of "Git Bash" profile and it's still using the old icon if I don't reload the window.

```
"Git Bash": {
            "source": "Git Bash",
            "icon": "terminal-linux"
        }
```

**Comment by connor4312** [comment]
It doesn't change in realtime for me, but works for new terminals without requiring a reload

**Comment by Tyriar** [comment]
This is by design, the profile is used only to launch the terminal.
