### ISSUE TITLE
Markdown Preview Inconsistent Colors for C# Code Block

### ISSUE THREAD

**Issue by tapiester** [microsoft/vscode#122451]
Issue Type: <b>Bug</b>

Steps:

  1. Open new document, set language to Markdown, open preview
  2. Type a C# code block containing a mix of types, fields, and reserved words

Example code block:

```csharp
class MyClass
{
    int MyInt;
    MyOtherClass MyProperty;
}
```

Actual results:

The reserved words `class` and `int` are rendered in different colors, blue and green, respectively. Types are rendered in white, which is also used for members.

Expected results:

Reserved words should be rendered in a consistent color. Ideally types should be rendered in a different color than members, especially since the syntax coloration in the markdown file itself does, though I suppose it's at least not inconsistent to use white for both.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.35GB free)|
|Process Argv|--crash-reporter-id b3b52f6e-4546-44d7-8236-8b59620aefbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.40.4
mdmath|goe|2.5.1
plantuml|jeb|2.14.5
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by tapiester** [comment]
For reference, screenshots of what the code and preview window look like for me:

Code:

![image](https://user-images.githubusercontent.com/49066264/116308907-18dc4380-a776-11eb-9829-95f5ce4079c6.png)

Preview:

![image](https://user-images.githubusercontent.com/49066264/116308928-1f6abb00-a776-11eb-89b5-b1c48a1d797c.png)

**Comment by mjbvz** [comment]
We use highlight.js in the preview. Extensions can provide alternative highlighting, such as https://marketplace.visualstudio.com/items?itemName=bierner.markdown-shiki
