### ISSUE TITLE
Show an error when a media path does not exist

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122463]
Testing #122275

In the example below the media path does not exist. There is an exception shown in the console.

![image](https://user-images.githubusercontent.com/172399/116317775-1567ad00-a7b4-11eb-854c-ecf988dd35c6.png)

 It could be helpful to make the error more obvious, e.g. by rendering it into the page.

```json
		"walkthroughs": [
			{
				"id": "exampleProject",
				"title": "Turn Markdown into HTML",
				"description": "Use this sample project to learn how to convert Markdown to HTML!",
				"primary": true,
				"steps": [
					{
						"id": "md-to-html.openExample",
						"title": "Open an example folder",
						"description": "To start, **try** opening [link](http://www.eclipse.org) an ``code`` example folder that has been preconfigured for this tutorial. **This is optional**, but helps for following along!\n[Open Example](command:md-to-html.openExample)",
						"media": {
							"path": "media/example1.md"
						}
					}
				]
			}
		],
```

**Comment by eamodio** [comment]
I hit the same issue -- took me a bit to realize the path was wrong.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/117378538-85e48d00-ae8a-11eb-87ac-11104c6b0ad7.png)

**Comment by connor4312** [comment]
This works for `markdown`, but not `image`s

**Comment by JacksonKearl** [comment]
I see this when the image is missing:
![image](https://user-images.githubusercontent.com/8586769/120867111-1d9ad100-c546-11eb-8785-99103b8ff576.png)

do you?

**Comment by connor4312** [comment]
I do get that, but not the alert

**Comment by JacksonKearl** [comment]
Added the notification because broken MD links rendered completely blank. I think the native broken image icon is sufficient indication that the image path is missing.
