### ISSUE TITLE
When using CodeSpaces extension with Notebooks, I see Kernels from my local workspace

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#122409]
- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Install Insiders
2. Install codesapces Jupyter extension
3. Open code spaces in VS Code (repo https://github.com/donjayamanne/jupyter-container)
4. Open a notebook & sometimes I see kernels from the local worksapce.
Based on my understanding this is impossible, the extension should be running remotely.

Note: On the bottom left u can see that I'm connected to codespaces
See screenshot for evidence:
![Screen Shot 2021-04-27 at 10 16 43](https://user-images.githubusercontent.com/1948812/116286625-47412b00-a744-11eb-84c6-450f4b3073b3.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> Open a notebook & sometimes I see kernels from the local worksapce.

This can only happen when your extension runs as UI-extensions (e.g runs where the UI runs) and not as workspace-extension. That's defined either in your extension's package.json or in your settings file.

**Comment by DonJayamanne** [comment]
The Jupyter extension is not a ui extension. It's not confirmed in package.json, have to my knowledge it's a workspace extension.
Also after reloading vscode it will display the right kernels. Meaning vscode is doing something that it should not.
The terminal points to remote, but kernels are local.

**Comment by jrieken** [comment]
> The Jupyter extension is not a ui extension. It's not confirmed in package.json, have to my knowledge it's a workspace extension.

Do you have this overruled in your settings file? It supports the `remote.extensionKind` which is stronger than your extension's package.json

> Meaning vscode is doing something that it should not.

Well, it's the extension that creates and manages these kernels...

**Comment by DonJayamanne** [comment]
@jrieken 

> The Jupyter extension is not a ui extension. It's not confirmed in package.json, have to my knowledge it's a workspace extension.


No we don't.

Please could we reopen this. Others are expericing this issue

**Comment by SiddhanthUnnithan** [comment]
The same behaviour is seen when connected to remote compute instances in Azure Machine Learning:

![image](https://user-images.githubusercontent.com/6413608/118013209-bacb6680-b306-11eb-8df0-991b0fde7f1c.png)

Both my local and remote kernels are listed.

**Comment by DonJayamanne** [comment]
Not sure how this is possible, looks like VS Code is running the extension in both contexts.

**Comment by jrieken** [comment]
> Not sure how this is possible, looks like VS Code is running the extension in both contexts.

Run F1 > Startup Performance and check perf marks for the local and remote extension host. That will show what extension was activated where and when. 

I have also added logging for when extensions invoke `createNotebookController`. Make sure to enable trace logging (F1 > Set Log Level > Trace) and then check the output of each extension host

<img width="725" alt="Screen Shot 2021-05-12 at 19 26 46" src="https://user-images.githubusercontent.com/1794099/118018390-00644f80-b358-11eb-9b6d-1eab62dcb82e.png">

**Comment by DonJayamanne** [comment]
Can we re-open this issue, instead of commenting on close issues.
@SiddhanthUnnithan Please could you provide the logs @jrieken has asked for.

**Comment by SiddhanthUnnithan** [comment]
Oddly enough I can't repro the issue in the remote window I'm working in right now...
