### ISSUE TITLE
Parameter window.newWindowDimensions ignores "inherit" value

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#122414]
I have in the settings "window.newWindowDimensions": "inherit"
I have an open window that is maximized to full screen. I open a new folder, but the new window is at the default size. If I set in the settings "window.newWindowDimensions": "maximized" then new window will open in maximized mode. Only does not work "window.newWindowDimensions": "inherit"

- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.19042

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by AlexDev2020** [comment]
@bpasero There is no problem on the insider assembly

**Comment by bpasero** [comment]
I am not sure what fixed it but I see it broken in stable too.
