### ISSUE TITLE
Terminal freezes can't debug

### ISSUE THREAD

**Issue by karadikidd** [microsoft/vscode#122417]
- VS Code Version:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0

- OS Version:
macOS Big Sur v11.3

Steps to Reproduce:

1. Use js-debug-nightly (ms-vscode.js-debug is disabled)
2. Upgrade VS Code to latest
3. Open Debug Terminal
4. Type node/yarn and hit enter
5. Terminal freezes

Nothing is printed to the console, but maybe that's because nothing is actually being attached to the debugger? 
IOW, when I run any command, VS Code doesn't switch to debugging, just hangs...

Does this issue occur when all extensions are disabled?: Not possible to check...

Start Extension Bisect didn't help either

P.S.
After the issue started, I've also tried to downgrade vscode and the `js-debug-nightly` extension to earlier versions and still the same.

**Comment by connor4312** [comment]
Does ctrl+c work at that point or is the whole thing frozen?

**Comment by karadikidd** [comment]
> Does ctrl+c work at that point or is the whole thing frozen?

Works.

**Comment by connor4312** [comment]
Are there any errors in the Console if you run the `Toggle Developer Tools` command?

**Comment by karadikidd** [comment]
BTW, disabling the `js-debug-nightly` extension and using the built-in one works just fine.

**Comment by karadikidd** [comment]
> Are there any errors in the Console if you run the `Toggle Developer Tools` command?

Here goes (from the console):

```
console.ts:137

%c[Extension Host] %crejected promise not handled within 1 second: TypeError: a.workspace.requestWorkspaceTrust is not a function
%c[Extension Host] %cstack trace: TypeError: a.workspace.requestWorkspaceTrust is not a function
at /Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:7:323823
at i.fire (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:10038)
at t.ObservableMap.add (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:320709)
at S._startSession (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:145833)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```
mainThreadExtensionService.ts:59

TypeError: a.workspace.requestWorkspaceTrust is not a function
at /Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:7:323823
at i.fire (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:10038)
at t.ObservableMap.add (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:320709)
at S._startSession (/Users/karadikid/.vscode/extensions/ms-vscode.js-debug-nightly-2021.4.2617/src/extension.js:1:145833)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by connor4312** [comment]
Ah, I see, thanks. Nightly is targeted at VS Code Insiders, and it's expecting an API to be there that doesn't exist in stable yet. I recommend either using js-debug stable if you're in stable VS Code, or using the nightly version in in Insiders.

Regardless this'll be fixed when stable rolls out next week.
