### ISSUE TITLE
Secondary button hover broken

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122440]
Looks like this was changed recently in https://github.com/microsoft/vscode/pull/121779

**Comment by rzhao271** [comment]
@misolori I'm wondering how to test this change? Does this change affect the terminal tabs + button with the dropdown?

**Comment by misolori** [comment]
Verifications steps:
1. Enable customers hovers 
2. Create an untitled file with unsaved changes
3. Close file and see dialog with the secondary button
