### ISSUE TITLE
Cannot paste into contentEditable webview div

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#122438]
Issue Type: <b>Bug</b>

With insiders I cannot paste into a `<div contenteditable="true"></div>`. In the devtools console, I see `VM9:78 We don't execute document.execCommand() this time, because it is called recursively.` after I paste. This works in non-insiders (Version: 1.55.2). 

VS Code version: Code - Insiders 1.56.0-insider (9a4d524f909e09079fec7abb82f2efde2172da7c, 2021-04-27T06:15:26.914Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.07GB free)|
|Process Argv|--crash-reporter-id 8e6f5759-c39a-482d-b44f-c9dbe9366f31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
openmatchingfiles|bca|0.5.0
codestream|Cod|11.0.4
codestreamer|Cod|0.0.1
css-theme-completions|con|0.0.3
gitlens|eam|11.2.1
prettier-vscode|esb|5.1.3
kotlin|fwc|0.2.18
gitlab-workflow|Git|3.13.0
csharp|ms-|1.23.11
python|ms-|2020.6.90262
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
powershell-preview|ms-|2020.6.1
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
addDocComments|ste|0.0.8
footsteps|Wat|0.1.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30276952
vscoreces:30290705
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

![image](https://user-images.githubusercontent.com/834948/116300310-c185a580-a76c-11eb-866d-0dae6d520660.png)

**Comment by mjbvz** [comment]
This doesn't happen in the webview sample on MacOS. Please share a minimal example extension that causes this

**Comment by bcanzanella** [comment]
after the `</ul>` here: https://github.com/bcanzanella/vscode-extension-samples/blob/master/webview-view-sample/src/extension.ts#L102

paste this block of code:

```
<div contenteditable="true" id="d"></div>
<script nonce="${nonce}">
	document.getElementById('d').addEventListener("paste", function(e) {
		e.preventDefault();
		console.log('onPaste');
		let text = e.clipboardData.getData("text/plain");		 
		document.execCommand("insertText", false, text);
	})
</script>
```
compile, launch, and paste. There will be the mentioned error with Insiders, but not standard VSC. I can move this to my fork if that would be easier?

**Comment by mjbvz** [comment]
Thanks. I believe this is caused by how you are using  `execCommand` instead of being something inherent to `contentEditable`

The most recent VS Code versions switch webviews in desktop versions of VS Code to use normal `<iframe>` elements instead of electron `<webview>` elements. This matches how webviews are rendered on the web. I suspect your example has not been working properly on the web either

You'll need to change how you are hooking into paste to avoid this. The error message explains the issue: vscode is calling `execCommand` to implement paste, and then your code is calling `execCommand` again from inside the paste event's event handler. I'm not sure you need to cancel the event in the first place but if you do, you could try wrapping `document.execCommand` in a `setTimeout`
