### ISSUE TITLE
Show parent folder path in the modal dialog

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122410]
Testing #122252

<img width="524" alt="image" src="https://user-images.githubusercontent.com/876920/116286634-4b6d4880-a744-11eb-8cd9-943a9dca4e6e.png">

if we can put the parent folder path next to "I trust the author of all files in the parent folder" then users don't need to double check the parent folder path through terminal or finder.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/122302
