### ISSUE TITLE
Lots of untyped metadata in Notebook API

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#122495]
Testing #122210

It looks to me that many objects in the API have some sort of open-ended option-bag metadata i.e.`[key: string]: any` or `Record<string, any>`:
* `NotebookCellMetadata` is open.
* `NotebookDocumentMetadata` is open.
* `NotebookCellOutput.metadata` is open.
* `NotebookCellOutputItem.metadata` is open.

It is not clear to me what these fields are useful for. Is this a way for the extension itself to associate some piece of data to that object that the extension later reads or are these keys supposed to travel to the output renderers? If the former, then maybe a generic could be considered such that extensions can type their metadata. If the latter, then does the data need to be JSON serializable?

I also don't really like the mixture of sometimes using a `Record` and sometimes using a dedicated class for these option bags metadata. Maybe using interfaces instead of classes might simplify things?

**Comment by jrieken** [comment]
>  i.e.[key: string]: any or Record<string, any>:

👍 we should use one style

**Comment by jrieken** [comment]
>  to associate some piece of data to that object that the extension later reads or are these keys supposed to travel to the output renderers?

Yeah, we use output metadata to feed extra data into renderers, e.g a sample is the size at an image should be rendered or the format in which JSON should be shown. 

Document and cell metadata is the open-ended bag that allows extensions to store extra stuff that they need to function but what we don't

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/119936

**Comment by jrieken** [comment]
```
export type NotebookTransferableData = boolean | number | string 
  | { [name: string]: NotebookTransferableData } 
  | ReadonlyArray<NotebookTransferableData>;
```

Idea/proposal for a notebook transfer data type which basically spec the types that we can send over the wire

**Comment by jrieken** [comment]
Discussing the option to remove `NotebookCellOutputItem#metadata` and only have `NotebookCellOutput#metadata`. That's one weak-typed property less and would also enable to simplify notebook output in general.

**Comment by jrieken** [comment]
> Maybe using interfaces instead of classes might simplify things?

This is coming late but I am striving for `{ [key:string]: any }` and to drop the metadata classes. There is only input/output collapse state left as cell metadata and that's arguably a view property, not a document/model property. So, the plan (which needs to be discussed still) is

* don't have `inputCollapsed` nor `outputCollapsed` as metadata properties but as view options. Jupyter declares them as [transient properties](https://github.com/microsoft/vscode-jupyter/blob/c89cb946bd3c262721b1e0444c035bfb0ea477f2/src/client/datascience/notebook/integration.ts#L70-L71) and only uses them for expand/collapse all features. This should come from us instead. 
* replace `NotebookCellMetadata` which is then empty with `{[key:string]: any }`
* replace `NotebookDocumentMetadata` which is empty with `{[key:string]: any }`

**Comment by jrieken** [comment]
Closing as we done with the changes mentioned above

**Comment by jrieken** [comment]
@alexdima please verify - there are still these open ended types for cells, notebooks, and output but the typings should be simpler and not mixed with stuff the model knows. Also, the jsdoc should be good for the metadata
