### ISSUE TITLE
[Feature Request] Support ES6 class property type annotation by comment

### ISSUE THREAD

**Issue by bigopon** [Microsoft/vscode#12240]
Currently you can do this
```js
/**@type {number} myVar */
var myVar = something
```

👍 Very cool as sometime intellisense needs help, but we can't do this
```js
class MyClass {
    // Not working
    /**@type {number} myProp */
    myProp

    // Not working either
    /**@property {number} myProp2 */
    myProp2
}
```

Would be great if supported.

Thanks

**Comment by waderyan** [comment]
@bigopon thanks for opening this issue.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11014

**Comment by waderyan** [comment]
Closing as this is being tracked in TypeScript's repo.
