### ISSUE TITLE
Visual Studio Code not disabling format on save.

### ISSUE THREAD

**Issue by AwsomeWorkDevoloper** [microsoft/vscode#122479]
# I'm trying to work on a project and Visual Studio Code keeps auto-formatting the file
### This is very annoying and it's getting to the point where it messes up my files, for example
My React File:
```javascript
function App() {
    return ( 
      <div className = "App" >
        <header className = "App-header" >
        </header>  
       </div>
    );
}
```
What VSCode formats it to:
```javascript
function App() {
    return ( <
        div className = "App" >
        <
        header className = "App-header" >
        <
        /header>  </div >
    );
}
```
This creates errors and doesn't allow me to save it properly.
### I've gone to the settings and I've disabled format on save, yet it still continues to do it.
settings.json:
```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "liveServer.settings.donotShowInfoMsg": true,
    "files.trimTrailingWhitespace": false,
    "explorer.compactFolders": false,
    "editor.fontLigatures": true,
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Atom One Dark",
    "editor.fontFamily": "'Fira Code'",
    "editor.suggestSelection": "first",
    "editor.formatOnSave": false,
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
}
```
It also doesn't work even after disabling all extensions. I tried reinstalling vscode and the problem was still there.

**Comment by mjbvz** [comment]
Does this reproduce  with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by AwsomeWorkDevoloper** [comment]
@mjbvz it does.

**Comment by mjbvz** [comment]
Did you test in insiders?

Also, what's the language mode of the file? This is shown in the lower right corner of the status bar

**Comment by gjsjohnmurray** [comment]
@AwsomeWorkDevoloper are the settings you showed in your user-level settings.json or the one in the `.vscode` subfolder of the folder you opened in VS Code?

**Comment by AwsomeWorkDevoloper** [comment]
> @AwsomeWorkDevoloper are the settings you showed in your user-level settings.json or the one in the `.vscode` subfolder of the folder you opened in VS Code? 

No it isn't. I opened that settings.jsom by clicking **CTRL-SHIFT-P** and opened _Settings(JSON)_
