### ISSUE TITLE
Terminal tabs have odd rendering while going to/from icons only view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122431]
Testing #122242

1. In the terminal tabs view with a few split terminal tabs
2. Click and drag on the sash to collapse the tabs down so only icons are showing. Keep holding down on the sash

**Bug**
The icons aren't rendered and instead I see a `...`

![Screen Shot 2021-04-27 at 12 07 14 PM (2)](https://user-images.githubusercontent.com/12821956/116298466-57133c00-a751-11eb-9630-62646f02eeb4.png)

Another case:

1. With only icons visible, click and drag to so that labels become visible. While holding the mouse to drag the sash, only the icons are shown:

![Screen Shot 2021-04-27 at 12 07 11 PM (2)](https://user-images.githubusercontent.com/12821956/116298697-9b9ed780-a751-11eb-99ee-70dda7277ca7.png)

**Comment by Tyriar** [comment]
I can't repro, any errors in console or special settings?

![recording](https://user-images.githubusercontent.com/2193314/116299587-bb82cb00-a752-11eb-84f5-9a2506d3fdbf.gif)

**Comment by mjbvz** [comment]
Seems resolved in the insiders that just came out

**Comment by mjbvz** [comment]
Never mind, still seeing this in 19cda32aafccb88db45622e7ae9be90cb71c9744  

It seems to happen when move the tabs left/right and then collapse the tab down once. After that, I start seeing the issue on Linux

**Comment by Tyriar** [comment]
Repro:

1. Open 2+ terminals
2. Right click empty area and move to left
3. Resize sash
