### ISSUE TITLE
No intellisene for icons

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122473]
Testing #122248

It would be great if we can have IntelliSense for all available terminal-* codicons we can use.

**Comment by Tyriar** [comment]
Blocked by https://github.com/microsoft/vscode/issues/120940 so that we pick up icons that come after start up

**Comment by Tyriar** [comment]
Preview would be cooler inline: https://github.com/microsoft/vscode/issues/123786

![image](https://user-images.githubusercontent.com/2193314/118141972-cb3f1800-b3be-11eb-8efe-1e8a3d526a55.png)
