### ISSUE TITLE
Notebook themes

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122481]
We should introduce the notion of notebook themes that can combine colors and layout. As a user I can associate a viewType with a certain notebook theme. This idea came up in a discussion with @rebornix.

**Comment by gramster** [comment]
Can I give this 100 upvotes? I personally love dark themes in my code editors but light themes when working with notebooks (don't ask why, it's not necessarily rational). I would love to have separate notebook themes as a result. It might even make sense to default to a light theme for notebooks (for Jupyter notebook users benefit).

**Comment by greazer** [comment]
This could help address some of the problems I ran into personally with trying to visually process the state of my notebook at any given time. I.e. which cell is selected, which is in edit mode, etc. I know we have separate color tokens for notebook stuff, but having a notebook theme as a 1st class citizen of VS Code would help in discoverability.

**Comment by claudiaregio** [comment]
+1 from customer email I received mid March. 

![image](https://user-images.githubusercontent.com/19276747/116577614-7d59e880-a8c5-11eb-9098-f590d1c1b46c.png)

**Comment by claudiaregio** [comment]
+1 from survey monkey feedback

![image](https://user-images.githubusercontent.com/19276747/116586985-e09c4880-a8ce-11eb-967c-873385f0613b.png)

**Comment by g-simmons** [comment]
+1

**Comment by claudiaregio** [comment]
+1 customer feedback

![image](https://user-images.githubusercontent.com/19276747/117401407-62850680-aeb9-11eb-87a3-93011283481c.png)

**Comment by claudiaregio** [comment]
+1 customer feedback 

![image](https://user-images.githubusercontent.com/19276747/117401943-564d7900-aeba-11eb-96c5-6cf0fabf122e.png)

**Comment by roblourens** [comment]
Starting to think about a concept for a basic profile, there are a few parts

- A profile is a set of `notebook.*` settings/values
- VS Code probably provides some builtin profiles
- An extension can declare a profile in package.json. Example:

```json
"notebookProfiles": {
    "deepnote": {
        "notebook.cellToolbarVisibility": "hover",
        "notebook.showCellStatusBar": false
    }
}
```

- Maybe an extension can also declare a default profile when registering a content provider, not sure about that
- A user can configure a profile per-view type, like

```json
"notebook.profile": {
    "github-issues": "zenMode",
    "*": "vscode"
}
```

- A user setting will override that value in the selected profile (?)
- We need some way to override values per-profile, or customize profiles
    - We could take inspiration from `terminal.profiles` and let the user declare profiles in their settings
    ```json
    "notebook.profiles": {
        "myprofile": {
            "extends": "jupyter", // optional
            "notebook.lineNumbers": "off"
        }
    }
    ```
    - or a simpler override like
    ```json
    "notebook.lineNumbers": {
        "jupyter": "off"
    }
    ```
    - or invert it
    ```json
    "notebook.profileOverrides": {
        "jupyter": {
            "notebook.lineNumbers": "off"
        }
    }
    ```

    - We've talked about a generic solution for custom setting scopes, like language-scoped settings, but we should start by thinking about this on its own without including that complicated issue

Things to think about
- How does the user know what settings are in the profile?
- Understanding settings scopes is already complicated. This adds more places the user has to look to figure out "what is the value of setting X in notebook Y?"
- What sort of custom settings editor experience can we add to make this easier?
  - One easy idea, add a special settings editor search query like `@notebookProfile:jupyter` which filters the settings list to notebook settings. If the user edits them, they get saved in the right way. This is also a solution for language scopes that I've thought about.

**Comment by roblourens** [comment]
Since this feature just came together at the end, my current thinking for the next release is that I would like to have the profile picking task available in getting started if you have ever opened a notebook, but the getting started page

**Comment by roblourens** [comment]
The current plan for this feature, as implemented in insiders, is the following

- If the user has ever opened a notebook, a new task is available on the Getting Started page to pick a notebook "profile" (although we don't use that word in the UI)
![image](https://user-images.githubusercontent.com/323878/120393989-aec03c80-c2e7-11eb-85bf-806caff39d7d.png)
- A notebook profile is just a set of values for notebook layout settings. When the user clicks a profile option, it will apply the profile settings to their user settings
- The first time the user opens a notebook, we will open the Getting Started page with the notebook profile picker to the side (this is hidden behind a setting `notebook.experimental.openGettingStarted`, and I plan to keep it that way for this release)

Jupyter team, please take a look at the current settings for the profile labelled Jupyter, we can change them. We are still tweaking all the profiles.

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/contrib/profile/notebookProfile.ts#L29-L37
