### ISSUE TITLE
"Trust All in Parent Folder" is not intuitive

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122460]
Testing #122252

<img width="257" alt="image" src="https://user-images.githubusercontent.com/876920/116316690-2807c500-a767-11eb-9352-1127cf185980.png">

I know what it means but it seems too short and the translations for it might be hard to understand.

**Comment by sbatten** [comment]
proposed wording to make it better? its already too long imho for the menu since `Trust` is so short. Ofc, I could force `Trust Folder` to be the first items text to balance things a bit

**Comment by lszomoru** [comment]
Closing this issue as it has been addressed by adding a dedicated button to trust the parent folder.
