### ISSUE TITLE
Auto disable extensions if their dependencies are disabled

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122448]
Testing #122252

* Trust a workspace
* Remove it from the settings
* An error notification showed up

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/116306771-5a5ef580-a75a-11eb-9fd0-1d7f3cc472e2.png">

**Comment by sandy081** [comment]
Yeah seems like so.

**Comment by connor4312** [comment]
The old vscode-node-debug does not require trust since debugging goes to node-debug2 now. We can just require trust for both, the moment you do anything with node-debug you'll get a trust prompt.

**Comment by sbatten** [comment]
I think the extension enablement service should check dependencies and use most restrictive option for enablement, this probably shouldn't be on the extensions to do themselves

**Comment by sandy081** [comment]
Agreed, there is similar requirement for virtual workspaces.

**Comment by lszomoru** [comment]
@sandy081, is this something that you will address or you want me to look at?

**Comment by sandy081** [comment]
I would look into this as it is also needed for virtual workspaces.

**Comment by lszomoru** [comment]
@sandy081, have you had the chance to look into this issue? Thanks!

**Comment by sandy081** [comment]
Not yet, scheduled it for next week.

**Comment by sandy081** [comment]
Dependents are disabled when dependencies are disabled and following message is shown:

![image](https://user-images.githubusercontent.com/10746682/122932768-4c9aaa80-d36e-11eb-94c9-7e798f6dc8e4.png)
