### ISSUE TITLE
ERROR:terminal terminated with exit code 1

### ISSUE THREAD

**Issue by ajaykrishnareddy** [Microsoft/vscode#12247]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7600

Steps to Reproduce:

1.WHEN I USED TO OPEN THE CMD IN VS CODE IT SHOW ERROR THAT TERMINAL IS TERMINATED WITH EXIT CODE
2.

**Comment by Tyriar** [comment]
That typically means that your shell path is wrong. Do you set `terminal.integrated.shell.windows` to something? If not what do you have the `%COMSPEC%` environment variable to on your system?

**Comment by ZCShou** [comment]
@Tyriar  for Chinese folder name 
![1](https://cloud.githubusercontent.com/assets/8591065/18660402/ccb409bc-7f42-11e6-8a25-4837258f84cf.gif)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
