### ISSUE TITLE
Settings Sync too many requests

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#122457]
Issue Type: <b>Bug</b>

I had > 20 "synced machines", with most being old Codespaces I believe (they all referenced "Web"). I wanted to clear them out so I removed each 1 by 1.  I got down to about 5 left and was kicked out of settings sync because I had more than 100 requests.

VS Code version: Code - Insiders 1.56.0-insider (19cda32aafccb88db45622e7ae9be90cb71c9744, 2021-04-27T17:47:33.615Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.57GB free)|
|Process Argv|--crash-reporter-id 0bb8a8db-762a-449d-ba3b-6e022498d7cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.1
remotehub-insiders|ms-|2021.4.2714

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by chrisdias** [comment]
Ideally I can multi select all of the machines and remove them, not 1 by 1. And I shouldn't be penalized for cleaning things up I believe :)

**Comment by akosyakov** [comment]
How did you manage to remove them? I could fine only an action to turn off setting but it does not remove actual record.

**Comment by sandy081** [comment]
You can remove it bu turning off settings sync on that specific machine - 

![image](https://user-images.githubusercontent.com/10746682/125254006-50c94080-e2fa-11eb-8b8e-00e39a7b4832.png)

It will make sure not to sync from that machine any more. I do not think this action removes any data from the server.

**Comment by sandy081** [comment]
Add multi-select support for machines view

**Comment by sandy081** [comment]
To verify:

- Turn on Settings Sync from different machines:
  - Mac / Windows / Linux
  - insiders.vscode.dev
  - github.dev / codespaces (switch to vs code insiders before turning on sync)
- Run command `Settings Sync: Show Synced Data` and open Machines view
- Make sure you can multi-select machines and turn off sync on these machines and verify settings sync is turned off on these machines
