### ISSUE TITLE
Should icons in configuration also be wrapped with `$()`?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122474]
Testing #122248

Surprisingly, just from a quick search for `icon` in settings, it looks like this is the first configurable icon in user settings!

I wondered if we should similarly require wrapping in `$()` like we do in contributions, in the event that images are ever allowed here. However since icon packs are now customizable that may be overkill.

**Comment by Tyriar** [comment]
I'd say overkill for now and unexpected for non-extension authors, we can always make this change retroactively if needed.
