### ISSUE TITLE
Changing $$ to $ causes a flicker

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#122423]
Testing #122251

Add a markdown cell with the text `Header $$\sqrt{5} * 3$$`. The formula will go onto its own line.
Then, change the text to `Header $\sqrt{5} * 3$`, and press escape. This puts the formula as an inline one, meaning it'll go onto the same line as the text "Header".

The cell first re-renders at its previous larger size, and then suddenly shrinks as the size update comes in, causing a visual flicker.

**Comment by mjbvz** [comment]
I just tested in a GitHub issue notebook but don't really see a shift/flicker anymore

If you still see one, please share steps on how to reproduce this
