### ISSUE TITLE
Document `registerNotebookSerializer` vs `registerNotebookContentProvider`

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122456]
Testing https://github.com/microsoft/vscode/issues/122210

Based on docs in vscode.proposed.d.ts I couldn't tell when I'd use `registerNotebookSerializer` vs `registerNotebookContentProvider`, based on conversation with @rebornix it seems the former is the go-to for the cases when a notebook is derived from a single resource.

**Comment by jrieken** [comment]
Yeah, our plan is put the complex API to slumber and to focus on simpler API first

**Comment by jrieken** [comment]
We won't document the content provider part as there is no plan to finalize that
