### ISSUE TITLE
Active terminal title not updated while arrowing through split terminals

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122452]
Testing #122242

1. Set `"terminal.integrated.tabs.showActiveTerminal": "always"`
1. Split a terminal twice
2. In the first terminal run `top`
3. Now in the terminal tabs, use the arrow keys to navigate through the terminals

**Bug**
When you arrow down to the last tab and then back to the first (the one running `top`), the active terminal title is not updated:

![Screen Shot 2021-04-27 at 1 38 23 PM](https://user-images.githubusercontent.com/12821956/116309627-d73f9e80-a75d-11eb-814f-f92bb2996100.png)

This seems to work as expected if you create 3 separate terminals instead of splitting things

**Comment by Tyriar** [comment]
Good find, this will be particularly useful in the narrow view.
