### ISSUE TITLE
provide EvaluatableExpression by current document's wordpattern by default (instead of old fixed regular expression based heuristic)

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#122455]
#89084 added the option for either a language extension or a debug extension to `registerEvaluatableExpressionProvider` to work around the old fixed regular expression that led to issues because it can never match "any language". For more reasons while the old fixed regular expression is not good - see that issue.

The [Debug hover API](https://code.visualstudio.com/updates/v1_43#_debugger-extension-api) that was shipped with 1.43 is good as it allows extensions that know about the context or at least about expressions that could be evaluated to register themselves and implement something reasonable.

But the old issue stays: most documents already have, with its language definitions, a `wordPattern` - and as long as there is one I'm quite sure it is better than the general regex approach.

I therefore suggest to do the following:

* check if an `EvaluatableExpressionProvider` is registered - in this case use that (we don't break any extensions that do so)
* if this isn't the case: _internally_ do the same as [MockDebug](https://github.com/microsoft/vscode-mock-debug/blob/35e0a6c2bc69b0a1464b857ad1e6cb55ada11d87/src/activateMockDebug.ts#L98), using the existing word definition of the current document for this information [I actually suggest to also have, depending on a new `hoverInComments` setting an automated filtering on `DocumentSymbol` as [suggested by @weinand](https://github.com/microsoft/vscode/issues/89084#issuecomment-593878980))
* only if this isn't possible (is there any language definition without a `wordPattern`?), then use the old fixed regular expression

This should provide a much better "match" than the current one while still providing the option to do something "better" if there's an extension active for it.

**Comment by weinand** [comment]
Yes, I agree the word defintion would be a good default strategy. But changing this, is no longer an option because it would be a breaking change for all extension relying on the old behavior.
I suggest to file issue against those extensions that would profit from using the "word definition".

**Comment by GitMensch** [comment]
> because it would be a breaking change for all extension relying on the old behavior

I wonder if there actually _is_ one?
I'm very positive about that more extensions would benefit of this change than extensions that have an issue with that change (if any).

The point is to only use this if the "2020 new" option is not used, and if the old behavior is already deemed possibly less useful than the word definition (if it exist, if it doesn't then the old code would be used, too).

... and if you feel very strong about "possible more breaking than helping" we could have a setting `defaultToHoverByWord` that enables/disables this approach (and as those can be set language specific one could even configure it per language) - if you have that disabled by default (and therefore always use the old fallback) then there's no "external extension break" possible.
