### ISSUE TITLE
Interactions in the workspace trust editor

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122489]
Testing #122232

The transition from trusting a folder to not trusting it anymore is infrequent and I performed it more often in testing than a regular user would. However, I observed myself over and over again to click in the boxes to change the value of workspace trust and only if that didn't work I remembered to remove the entry from the list:

![image](https://user-images.githubusercontent.com/4674940/116330877-4da2c780-a783-11eb-8bbe-6cf2f4662107.png)

Also, it might make sense to highlight which list entry is responsible for the trust of the current folder.

**Comment by lszomoru** [comment]
Latest Insiders contain the button to transition from Trusted -> Restricted Mode but it is only shown if the folder that is currently opened matches an entry in the trusted folders list, meaning that the trust state is not inherited. 

> Also, it might make sense to highlight which list entry is responsible for the trust of the current folder.


This is already being tracked with https://github.com/microsoft/vscode/issues/121321
