### ISSUE TITLE
Workspace trust prevents opening codespace remote

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122458]
Testing #122252

* Try to open a codespace instance in VS Code

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/116314855-82ebed00-a764-11eb-9abf-14039da7c101.png">

An error message prompts and also choosing "No I don't trust" doesn't work at all.

**Comment by rebornix** [comment]
Trusting the workspace doesn't work either, I have to reload the window for it to work.

**Comment by sbatten** [comment]
closing as you must use `extensions.supportUntrustedWorkspaces` until remotes onboard properly

**Comment by lszomoru** [comment]
As @sbatten said, in order to unblock this scenario you need to add the following to your user settings:

```json
  "extensions.supportUntrustedWorkspaces": {
    "GitHub.codespaces": {
      "supported": true
    }
  }
```
