### ISSUE TITLE
Opening an untrusted remote workspace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122484]
Testing #122232

I tried to open an existing Remote-SSH workspace from my recent list. It also happened that the opened file was a notebook file. This is what I get:

![image](https://user-images.githubusercontent.com/4674940/116329771-e421b980-a780-11eb-89b1-42b209f10497.png)

There are three insights here:
1) Missing adoption of workspace trust by the remote extensions -> this is in our control
2) Custom editors and notebooks rely  on the adoption of workspace trust to prevent this from happening
3) For remote folders, when I choose to trust the workspace I still end up in a broken state. I have to reload the window to recover.

**Comment by sbatten** [comment]
1 & 3 are a result of the same issue. Rob updated the extension yesterday so it is no longer an issue but for any remotes, you can override their trust requirements with `extensions.supportUntrustedWorkspaces`

**Comment by roblourens** [comment]
Remaining: adopt `requiresWorkspaceTrust` on the notebook editor input, based on whether the content provider we want to use requires trust.

**Comment by roblourens** [comment]
I think this is n/a now
