### ISSUE TITLE
Wording: trust authors or files

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122426]
Testing #122252

In the first dialog it's asking me if I trust the authors

<img width="512" alt="image" src="https://user-images.githubusercontent.com/876920/116297940-ad33af80-a750-11eb-8fff-18f702f21df6.png">

while in debugging, it's asking me if I trust the files

<img width="515" alt="image" src="https://user-images.githubusercontent.com/876920/116297884-9e4cfd00-a750-11eb-8e9a-000d5773a6a2.png">

**Comment by isidorn** [comment]
Similar feedback in this issue https://github.com/microsoft/vscode/issues/122487
Assigning to April so we polish this this milestone.

**Comment by isidorn** [comment]
Fixed by either @lszomoru or @sbatten 
Thanks

![Screenshot 2021-04-29 at 13 58 04](https://user-images.githubusercontent.com/1926584/116547264-f58ad300-a8f2-11eb-9550-bfb98bffb998.png)
