### ISSUE TITLE
Download latest compatible version of extension

### ISSUE THREAD

**Issue by bastantoine** [microsoft/vscode#122517]
I recently started a new job where the version of the VS Code instance provided by the company was slightly older (1.53.2, Feb 2021) than the latest (1.55.2). This small difference in the version prevented me to install a few extensions right from the store because their latest version weren't compatible with my version of VS Code. To solve this I hade to manually try each version using the `.vsix` file until I found one that worked.

I believe it'll be a nice improvement if the instance of VSC could automatically install the latest compatible version of an extension, instead of *simply* the latest available version.

That being said, I understand that it could be quite hard to do, I didn't see anywhere a somewhat standardized way for an extension to tell which mininal version is required to work properly.

One possible less harder (I think) improvement would be to allow a user to select which version to download. This would mean that in a case similar to mine, you would still need to check each version one by one, but this wouldn't require to manually download the `.vsix` file for the source repo.

Hope this is clear, thanks !

**Comment by sandy081** [comment]
@bastantoine VSC already  does that (install the compatible version)  when you try to install the extension from extensions UI. Have you tried that?

**Comment by bastantoine** [comment]
Oh weird. Yes of course that's the first I thing I tried.
Don't know if that could be related, I saw some errors `getaddrinfo ENOTFOUND marketplace.visualstudio.com` when trying to install them from the store.

**Comment by sandy081** [comment]
So you are downloading the vsix and installing it? If so VSC cant install the vsix if it is not compatible and it is expected. Regarding issues connecting to marketplace seems you have proxy or other network issues to connect to marketplace. Please fix them so that you can install the right compatible extension from MP.

**Comment by bastantoine** [comment]
> So you are downloading the vsix and installing it?

Yes exactly.

> VSC cant install the vsix if it is not compatible and it is expected

Yes I understand that, that's quite normal.

> Regarding issues connecting to marketplace seems you have proxy or other network issues to connect to marketplace. Please fix them

I can't, I believe it's the company policy.

---

Anyway, I was able install what I wanted by hand, things are working fine now. I didn't know that VSC already had the ability to install the latest compatible version in case you're using an old version of VSC. I think I had bad luck with both an old version and a proxy blocking the requests to the marketplace.
