### ISSUE TITLE
Test launch option that allows run node project by npm script

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#12253]
Test for #2726:

- [x] any OS - @dbaeumer 

Complexity 2

A frequent feature request was to support running 'npm' scripts directly from a launch configuration.
This has now become possible by the following small tweaks of existing launch configuration concepts:
- Any program available on the PATH (e.g. 'npm', 'mocha', 'gulp', etc.) can now be used for the `runtimeExecutable` attribute and arguments can be passed via the `runtimeArgs`.
- The `program` attribute is no longer mandatory which helps if the npm script already specifies the program to launch.
- If you specify a debug port via the `port` attribute, the `--debug-brk=nnnn` attribute will no longer be automatically added because the debug port is typically specified by the npm scripts as well.

So if your package.json has a 'debug' script, e.g.:
```json
  "scripts": {
    "debug": "node --nolazy --debug-brk=5858 myProgram.js"
  },
```

the corresponding launch config could look like this:
```ts
{
	"name": "Launch via NPM",
	"type": "node",
	"request": "launch",
	"cwd": "${workspaceRoot}",
	"runtimeExecutable": "npm",
	"runtimeArgs": [
		"run-script", "debug"
	],
	"port": 5858
}
```

Verify that you can start a debug session by using your favourite tool/scripts in a 'node' launch config.

**Comment by Alanz2223** [comment]
@weinand I am trying to configure the editor with your options, but the 'program' attribute seems to still be a requirement since I am receiving the error : `Attribute 'program' is missing or empty.`.  I am using version 1.5.3 and node 5.10.0

**Comment by weinand** [comment]
@Alanz2223 alternatively you can try the Insider release to try this.
