### ISSUE TITLE
Trust button should be outside the description boxes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122532]
Testing #122252

Only just now I realised the green and red boxes are pur descriptions. And it made me realise as well that the button should not be inside the green box at all.

This GIF makes the weirdness obvious:

![recording (15)](https://user-images.githubusercontent.com/22350/116401589-44941380-a7e0-11eb-8314-bf4b460f7df5.gif)

Should we just move the button to above the boxes?

![image](https://user-images.githubusercontent.com/22350/116401722-6beae080-a7e0-11eb-8077-efb61617c1c5.png)

**Comment by sbatten** [comment]
I was trying out buttons staying in that box, but seems too weird. I was going to put the don't trust button back in the "in restricted mode" box, so its like selecting the box you want. does that make sense to you?

**Comment by joaomoreno** [comment]
I also don't like that since clicking the button actually changes text inside the boxes, so it's not like each box describes their situation but each box describes each side **per** situation. I would put the actions outside of them.

**Comment by sbatten** [comment]
@joaomoreno it does not change the text inside the boxes. The third item changes as a result of a bug that @sandy081 has since fixed. no other text changes.

**Comment by lszomoru** [comment]
The Trust/Trust Parent/Don't Trust actions in the workspace trust editor have gone through multiple interactions. The Trust and Trust Parent buttons are in the box on the left hand side, while Don't Trust is in the box on the right hand side. We have also done work to make sure that the two boxes stay the same when clicking on the various actions. Closing this issue for now.
