### ISSUE TITLE
${order} duplicates `@<order>`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122512]
Testing #122102

The `statusBar/remoteIndicator` syntax defines a portion for the ordering within a group. That duplicates the default in-group order which is done via the `@<order>` suffix.

**Comment by jrieken** [comment]
more clarification about sorting inside groups: https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups and a sample:

<img width="408" alt="Screenshot 2021-04-30 at 11 57 06" src="https://user-images.githubusercontent.com/1794099/116679799-3e9e5e00-a9ab-11eb-82b5-6663144281b6.png">

**Comment by aeschli** [comment]
The ${order} is about the order of the groups (not within the group)
We want WSL to be before SSH and before Containers.
