### ISSUE TITLE
Trust: Delay in adding a folder to the trusted folders list

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122528]
Testing #122252

There's an odd split second delay between clicking `OK` and seeing the row appear. It should simply appear directly right?

![recording (14)](https://user-images.githubusercontent.com/22350/116400105-815f0b00-a7de-11eb-96fe-e23c4bac61d8.gif)

**Comment by sbatten** [comment]
This is a problem with the settings editor widget as well

**Comment by lszomoru** [comment]
We do plan on switching to the table widget which should hopefully address this.

**Comment by lszomoru** [comment]
Closing the issue as we have adopted the table widget which resolved this problem.
