### ISSUE TITLE
Tasks upgrade in restricted mode

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#122535]
Testing #122190

I opened a folder containing tasks v1, and decided to stay in "restricted mode". They I was prompted that listing and running tasks requires workspace trust, yet I also see a notification that the tasks have been upgraded. Do we need workspace trust to perform the upgrade? If that is the case shouldn't we wait until the user responds to the dialog?

I also noticed that the `tasks` array in the `tasks.json` is empty.

![image](https://user-images.githubusercontent.com/3372902/116403467-e0983c00-a82d-11eb-8a7d-cf35b6824f3b.png)

**Comment by lszomoru** [comment]
Something is till not right here. Here is what I am seeing now:
1. Open a folder that contains v1 tasks
2. Choose the trust the folder
3. In the background I see that the tasks were upgrade but I still see this dialog:
![image](https://user-images.githubusercontent.com/3372902/116554327-574f3b00-a8fb-11eb-8186-01c04eed9914.png)

**Comment by alexr00** [comment]
Ugh. It looks like a race because tasks asks for trust before the user acks the first trust dialog. @lszomoru should workspace trust handle this, or should each user of trust try to handle this.

**Comment by lszomoru** [comment]
Good question. @sbatten, should the dialog "block" the workbench initialisation to avoid this?

**Comment by lszomoru** [comment]
@alexr00, for this milestone I wonder if we could to the following:
1. The code the upgrades the tasks should check for workspace trust but not ask for it
2. Use the event to listen to when workspace trust is given and do the task upgrade then

**Comment by alexr00** [comment]
@lszomoru seems reasonable. I will implement it.

**Comment by sbatten** [comment]
I don't think we should block the workbench in any way. That seems ripe for bugs that cause other issues. I think guidance should be that nothing on startup should ask for trust since we are already doing that. The guidance to check trust and listen to the event seems like the right thing.
