### ISSUE TITLE
C/C++ plugin crashes various operations in TypeScript (and Javascript) code

### ISSUE THREAD

**Issue by FLWrd** [Microsoft/vscode#12251]
- VSCode Version: 1.5.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Open typscript project
2. type cmd-T and start typing the name of a symbol

This resulted in a crash in Microsoft.VSCode.CPP.Extension.darwin here:

> 0   Microsoft.VSCode.CPP.Extension.darwin	0x000000010acfc264 code_store::a_store::get_structure_version() + 4
> 1   Microsoft.VSCode.CPP.Extension.darwin	0x000000010acdaf01 browse_engine::populate_filename_cache() + 49
> 2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010acdcb61 browse_engine::query_files(char const*, std::__1::vector<browse_symbol, std::__1::allocator<browse_symbol> >&) + 129
> 3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010aca1426 message_handler::workspace_symbol(vscode::WorkspaceSymbolParams) + 70
> 4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010ac9a615 vscode::handler_base<message_handler>::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, bool) + 7637
> 5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010ac98559 vscode::handler_base<message_handler>::handle_message(vscode::vscode_client_message&&) + 57
> 6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010ac9849b vscode::handler_base<message_handler>::main_loop()::'lambda'()::operator()() const + 75
> 7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010ac98410 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda'()> >(void*) + 96
> 8   libsystem_pthread.dylib       	0x00007fff955f899d _pthread_body + 131
> 9   libsystem_pthread.dylib       	0x00007fff955f891a _pthread_start + 168
> 10  libsystem_pthread.dylib       	0x00007fff955f6351 thread_start + 13

Removing the plugin restored normal functioning.

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://github.com/Microsoft/vscode-cpptools
