### ISSUE TITLE
console.log Canceled in debug console terminal

### ISSUE THREAD

**Issue by HeinzRuetschi** [microsoft/vscode#122509]
Issue Type: <b>Bug</b>

{
  let grades = [
    [12, 13, 32, 43, 42, 23],
    [11, 43, 21, 12, 43, 12],
    [43, 12, 43, 12, 45, 12]
  ];

  for(let i = 0; i < grades.length; i++){
    console.log(grades[i]);
  }
}

Shows the following result in the debug terminal
C:\Apps\nodejs\node.exe .\javaScriptTutorial.js
(6) [12, 13, 32, 43, 42, 23]
Canceled

Running the code in firefox or node in cmd results are shown correct

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.50GB free)|
|Process Argv|--crash-reporter-id 827ad1eb-8fb8-44d9-a1ba-392ecb69473b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
code-gnu-global|aus|0.2.2
vscode-django|bat|1.6.0
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
doxdocgen|csc|1.2.0
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
git-extension-pack|don|0.1.3
githistory|don|0.6.16
python-extension-pack|don|1.6.0
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.4
vscode-pull-request-github|Git|0.25.1
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.5
MagicPython|mag|1.1.0
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4131
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.6.0
platformio-ide|pla|2.3.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.12
jinja|who|0.0.8
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by connor4312** [comment]
This is because to get information about the logged data object, the debugger needs to query the app. If the program exits very quickly, we don't have the opportunity to do so.

There's a few ways you can get around this:

- In your launch.json, set `outputCapture: std` to capture raw process output instead of fancy console.logs
- Set `console: integratedTermainl` in your launch.json to run the program in a terminal where output is visible
- Use the JavaScript Debug Terminal where output is similarly shown directly
