### ISSUE TITLE
Trust: Folder name should have validation

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122530]
Testing #122252

1. Edit a folder name in the trust editor
2. Clear the input box
3. Press <kbd>Enter</kbd>

🐛 Folder gets deleted and there's no turning back 🙈

We should just have some validation like the Explorer:

![image](https://user-images.githubusercontent.com/22350/116401091-aef88400-a7df-11eb-8b53-e2418be94143.png)

**Comment by sbatten** [comment]
duplicate #122412
