### ISSUE TITLE
Trust: Where's the untrust button?

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122541]
Testing https://github.com/microsoft/vscode/issues/122209

1. Open a never before trusted folder
2. Trust it
3. Close the trust editor
4. Click the Gear icon > `Manage Workspace Trust`

🐛 `Untrust` button is gone. Instead, there's a sentence `This folder is trusted via one or more of the trusted folders below.`

![image](https://user-images.githubusercontent.com/22350/116411672-c8eb9400-a7ea-11eb-8164-b097caf626ac.png)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/122310
