### ISSUE TITLE
Publish a branch asks for credential access permission

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122555]
Testing #122243

I created a branch and committed a change to the branch. We detected correctly that there was no corresponding upstream branch and we asked whether or not I want to publish the branch. I said yes. Now I'm asked if the git extension can use the GH credentials. I already said yes, so we should not asked in this case.

**Comment by lszomoru** [comment]
I believe that this has been addressed over time so I am optimistically closing the issue.
Please feel free to reopen it in case I have missed something and you can still repro. Thanks!
