### ISSUE TITLE
[Workspace Trust] Use present tense to describe present state 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122598]
Testing #122232
![image](https://user-images.githubusercontent.com/8586769/116484880-d6326e00-a83e-11eb-9d92-4017cdfb2e8b.png)

Suggest
- Tasks *are* disabled
- Debugging *is* disabled
- 3 workspace settings *are not* applied
- 8 extensions *are disabled* or have limited functionality.

**Comment by sbatten** [comment]
@JacksonKearl do you suggest changing the wording based on the state of the workspace or just always use present tense?

**Comment by JacksonKearl** [comment]
The current state should be described in present tense and the alternative state should be described in future tense imo.

**Comment by JacksonKearl** [comment]
Up to you. IMO it'd be nice to read it and have English convey the current state, vs needing to parse the UI.
