### ISSUE TITLE
Workspace Trust layout needs work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122523]
Testing #122252

Issues:

- When the layout is too narrow, the green and red boxes are cropped by the editor itself and its contents are basically unreadable
- Also in that same scenario, the scrollbar should be completely aligned to the right margin of the editor. Currently there's some padding which feels weird.
- The scrollbar should also only be visible when the mouse is over the view. It should hide otherwise, like every scrollbar in the workbench.
- The focus border around the Trusted Folders view feels weird, do we even need it?

![image](https://user-images.githubusercontent.com/22350/116397783-de0cf680-a7db-11eb-9cda-cef59118bd67.png)

---

Should we place the green and red boxes on top of another, if the space gets too constrained?

![image](https://user-images.githubusercontent.com/22350/116397217-2e378900-a7db-11eb-94f1-baa3dfaf0966.png)

**Comment by joaomoreno** [comment]
Another minor nitpick: that internal scrollback should be visible only if the mouse is over the view. It should hide otherwise.

**Comment by sbatten** [comment]
I think the focus border makes sense so I didn't change that, addressed the rest
