### ISSUE TITLE
Improve autocompletion for `statusBar/remoteIndicator` contribution point

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#122566]
Testing #122102

In an extension `package.json` file, add
```
	"contributes": {

		"menus": {
                 }
         }
```

and start typing "status" in the menus section. A completion item for "statusBar/windowIndicator" shows up, but not "statusBar/remoteIndicator"

**Comment by aeschli** [comment]
Now `statusBar/windowIndicator` no longer is proposed, but get a warning (deprecated)
