### ISSUE TITLE
Pressing enter in the outline on a notebook doesn't navigate to the selected cell

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122595]
- Open a notebook
- Open the outline
- Arrow down to some cell. As I navigate in the list, I get the yellow background color on the cell ✅ 
- Press enter
- I expect focus in the notebook list to move to that cell, but it stays where it was before i opened the outline

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/122480
