### ISSUE TITLE
Current trusted parent should be shown more prominently in Trusted Folders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122573]
Verifying https://github.com/microsoft/vscode/issues/122310

We show

![](https://memes.peet.io/img/21-04-c0975c7c-7852-4224-af7e-1f52eaa905e1.png)

If trust is given from a parent. But then if I want to untrust it, I need to remember the path I'm in and look through my potentially-long list of folders to find the parent that affects this one. 

I think we should either have a button or just show the current parent more prominently (e.g. sorted to the top) in the list.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/121321
