### ISSUE TITLE
create fork does not work for some remote urls

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#122567]
I can reproduce it if I checkout a repo with: `git clone https://github.com/philskat/js-sort.git`

**Comment by eamodio** [comment]
Fixed in https://github.com/microsoft/vscode/commit/c8c96aae9d50cd60b1909f204a43c6692d7ed76a

**Comment by eamodio** [comment]
\closedWith c8c96aae9d50cd60b1909f204a43c6692d7ed76a
