### ISSUE TITLE
Copy + Paste file auto open 

### ISSUE THREAD

**Issue by scriptcoded** [microsoft/vscode#122549]
After a discussion in #117967 it seems the behaviour when pasting files have been changed. Previously when pasting a file it was automatically opened in a new editor tab, a feature that I've grown used to.

There is one specific scenario that I think makes it worth at least having the option to revert to the old behaviour. When duplicating a file you usually select it in the explorer - `CTRL + C` and then `CTRL + V`. The confusing thing is that the file that was initially selected is opened in preview. Since the new file is a copy of the selected one they're identical, giving no hint as to which file is opened (except for the name in the tab, but there the path might be the only thing differentiating them). Making matters even worse, the pasted file is highlighted giving it the same appearance as if it was just clicked to open a preview.

This might just be a me problem, but for the actual feature request then: I assume reverting it might not be an option, but having the option to enable the old behaviour would be nice at least.

I haven't worked in the VS Code codebase before, but looking at the commit (e2c5ff9) it shouldn't be too difficult to implement a setting for it. I could perhaps look it to raising a PR if time is sparse for you.

**Comment by manzoorwanijk** [comment]
Yes, the new behavior is frustrating. There should at least be a setting to control the behavior.

**Comment by manzoorwanijk** [comment]
Duplicate of #120882

**Comment by scriptcoded** [comment]
Closing in favor of duplicate
