### ISSUE TITLE
Not seeing markdown notebook text in codespaces

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#122564]
I'm on Codespaces on the latest Insiders, and the markdown notebook text doesn't seem to be rendering for some of the github notebooks in the vscode repo:

![nomd](https://user-images.githubusercontent.com/7199958/116436066-e166a900-a800-11eb-8fad-8e2ebb696255.PNG)

**Comment by mjbvz** [comment]
Seems to be working for me:

![Screen Shot 2021-04-28 at 3 25 45 PM](https://user-images.githubusercontent.com/12821956/116480347-07f30700-a836-11eb-9b89-46220a4c713a.png)

@rzhao271  Any errors in the codespace dev console?

**Comment by rzhao271** [comment]
I didn't see any relevant errors in the output logs or the devtools console.
Here's another recording showing how flaky the problem is:

![recording (3)](https://user-images.githubusercontent.com/7199958/116582330-1ab71b80-a8ca-11eb-9b7c-8dae4711e5e8.gif)

**Comment by mjbvz** [comment]
Still can't repro this. Will test on windows too

**Comment by mjbvz** [comment]
@rzhao271 Also don't see this on windows. Are you seeing this in the latest insiders? What if you create a new codespace?
