### ISSUE TITLE
Add command to sort JS/TS imports without removing used

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122593]
Tracks picking up https://github.com/microsoft/TypeScript/pull/43184

The main use case is for `codeActionsOnSave`. Some users may just want imports to be sorted when they save instead of also having unused imports being removed

**Comment by mjbvz** [comment]
To verify, try using the new `sort imports` code action (it requites TS 4.3+)

It should only sort imports without removing them

**Comment by meganrogge** [comment]
![recording - 2021-06-03T073221 119](https://user-images.githubusercontent.com/29464607/120662254-d5908700-c43d-11eb-8484-f3ff445c7f9a.gif)
@mjbvz Am I doing something wrong here? I'm on TS 4.4 and when I sort the imports (with an unused one, KeyMod), it's gone after sorting

**Comment by meganrogge** [comment]
Oh just noticed I'm using organize imports, not sort
