### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by sshewale** [microsoft/vscode#122529]
- Slow the terminal - not getting response in terminal - it's taking more time to show terminal log
- Also for Source control - when we tried to add stage changes - it takes more time, sometime need to click twice
- Also getting below error daily
![vs-terminal-error](https://user-images.githubusercontent.com/19758238/116400577-d5520a00-a847-11eb-86c7-270bd2bda07c.png)

**Comment by meganrogge** [comment]
Do you have extensions installed? Try running extension bisect
