### ISSUE TITLE
multi wsl version, default wsl run failed

### ISSUE THREAD

**Issue by nAnderYang** [microsoft/vscode#122519]
Issue Type: <b>Bug</b>

install multi wsl verion in windows
vscode terminal run wsl default system failed

```
C:\Windows>wsl --list
适用于 Linux 的 Windows 子系统分发版:
CentOS (默认)
Ubuntu-18.04
Alpine

C:\Windows>
```
![image](https://user-images.githubusercontent.com/28423384/116392636-3e8b4a80-a853-11eb-92a4-b25203de2a0b.png)

![image](https://user-images.githubusercontent.com/28423384/116392441-0ab02500-a853-11eb-822b-bf4cb594629c.png)

delete the extra text and run the command
```
C:\Windows>wsl -d CentOS
[root@DESKTOP-586S6SI Windows]#
```

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.04GB free)|
|Process Argv|--crash-reporter-id 5211d94d-0204-46e0-b566-c1698ce42a3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.55.2
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-wsl|ms-|0.54.6
cpptools|ms-|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by nAnderYang** [comment]
ok,i got it, thanks.
