### ISSUE TITLE
Trust: I can reset a setting's value even in restricted mode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122544]
Testing #122209

![recording (17)](https://user-images.githubusercontent.com/22350/116412980-0a307380-a7ec-11eb-8ac8-bcc8a9cbccce.gif)

**Comment by sandy081** [comment]
@roblourens I do not see a easy and nice way to disable this action and it seems you have this action available for all settings even though they are not modified. I am supposing you are not supporting disabling the action. Hence I made a fix not to update if setting is untrusted.

**Comment by roblourens** [comment]
I don't understand the problem, can you not type in settings.json?

**Comment by sandy081** [comment]
You are right, we cannot stop user if user wants to use settings.json. But the UI should not be allowing any modification action for a restricted setting. So, it would be nice if we can disable the reset action. I am reopening it to consider this request.

**Comment by rzhao271** [comment]
Closing since the direction of how we want to display restricted settings changed.
New feature request: https://github.com/microsoft/vscode/issues/141317
