### ISSUE TITLE
Inconsistent npm name compleition

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122578]
I'm not sure if this is npm or us, but verifying https://github.com/microsoft/vscode/issues/120315 I noticed some oddness.

- Type `@types/react-s` in a package.json dependencies key and trigger completion
- The only suggestion is `@types/react-s-alert`, rather than `@types/react-select`

![](https://memes.peet.io/img/21-04-18c651f8-2007-4e1d-9044-57f9075caef0.png)

This seems arbitrary, [@types/react-select](https://www.npmjs.com/package/@types/react-select) is vastly more popular than [@types/react-s-alert](https://www.npmjs.com/package/@types/react-s-alert).

**Comment by aeschli** [comment]
It's what's coming from npm. I give them a query string and they come back with matching stuff.
I could try to massage the queries, but I'm hesitating to do that.

No plans for now
