### ISSUE TITLE
Settings: List row heights get messed up

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122545]
Testing #122209

1. Open Settings
1. Narrow down the window's width, but just enough for the TOC to show
2. Split editor

🐛 The layout on the left settings editor is broken

![recording (21)](https://user-images.githubusercontent.com/22350/116413980-f1748d80-a7ec-11eb-9cb7-858e049e28a6.gif)

**Comment by roblourens** [comment]
Oh, I think this was actually the same as #128563
