### ISSUE TITLE
f2 (rename symbol) Causing new lines to be entered.

### ISSUE THREAD

**Issue by beavaman101** [microsoft/vscode#122583]
Issue Type: <b>Bug</b>

I have a saved python script with a variable `root_file_path` and am attempting to use the f2 (rename symbol functionality). There are three instances of this particular variable in my python script. However, when previewing the refactor it is highlighting every line in the file and attempting to insert a line return on a large number of those lines, even when the particular variable in question does not exist on those lines.

This is causing the formatting of the file to be skewed and un-executable in this particular case because of how arbitrary the line returns are.

![vs_code_error](https://user-images.githubusercontent.com/8357737/116473198-e3525b80-a844-11eb-8fdb-3a3f621ded83.png)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (18.29GB free)|
|Process Argv|--crash-reporter-id b1d330be-1d6a-4942-b6d4-25df80964059|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by alexdima** [comment]
Please open an issue directly against the python extension at https://github.com/Microsoft/vscode-python
