### ISSUE TITLE
[Getting Started] Signal extensions if VS Code's extension walkthroughs are enabled

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#122592]
As extensions adopt walkthrough's (#118402) we want them to cut back their setup notifications galore that is usually triggered by first activation.

VS Code extension walkthrough support will roll out in stages and with different heuristics. Extensions will need a flag from VS Code that their walkthrough was shown to the user; which can then gate first-launch notifications that have counterparts in the walkthrough.

Other considerations:

- Extensions might be interested in if the user actually read or completed the walkthrough. It seems wrong though to send more notifications to a user that already ignored the first walkthrough. Contextual notifications (like warning about missing interpreter when a user tries to build) can still help in those cases. Usertesting and experiments can then confirm if users fare better on walkthroughs or first-activation notifications.
- After walkthroughs are enabled for all users and users have an option to disable them (choosing the silent treatment); it might help to not tell extensions so those users are not hit by the old notifications wave. This would make the flag only useful during the initial rollout of walkthroughs.

**Comment by Eskibear** [comment]
Since we have `"when": false` now, it's hidden by default. Only insiders users in treatment group will see it. Has the experiment started?

For users in treatment group, we may also want to hide extension's own implementation of welcome page, so what's the name of treatment variable?

**Comment by JacksonKearl** [comment]
The experiment will need to be set up to give a treatment to both Core and the extension. @digitarald knows more about how to do this.

The original ticket is no longer needed -- with this upcoming Stable, extension contributions are enabled by default.
