### ISSUE TITLE
Find/Replace History: Don't record keystrokes, only searched strings

### ISSUE THREAD

**Issue by chambery** [microsoft/vscode#122572]
1. Type some characters into the find/replace box
2. Make adjustments based on live results
3. Cycle back through changes, all keystrokes are recorded

Find/Replace history (⌥+↑/↓) should not record keystrokes into the history.

** Record only search/replace string that have been search/replaced **

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

**Comment by gazzaf** [comment]
This makes perfect sense. "Find" must be one of the most used features of an editor, so history would be a great productivity and convenience enhancement.
