### ISSUE TITLE
Rename tab setting hideForSingle to hideCondition to allow future extensibility

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122551]
Splitting out from https://github.com/microsoft/vscode/issues/122348 for verification

**Comment by Tyriar** [comment]
Think I broke something here, this is what I see regardless of `terminal.integrated.tabs.hideCondition` value on today's insiders

![image](https://user-images.githubusercontent.com/2193314/116546004-f9dccf00-a8a5-11eb-87bb-141b497fe4d3.png)

**Comment by meganrogge** [comment]
You didn't break something I did. Fixed here

https://github.com/microsoft/vscode/commit/bdb2324c9da9381441cbf874f51758a44a6cae8f
