### ISSUE TITLE
Windows: source maps no longer working in selfhost insiders?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12250]
I am no longer able to open a TS file in the insiders build from selfhost. This could either be a build problem or the electron update...

**Comment by joaomoreno** [comment]
Works for me in the latest insiders.

**Comment by bpasero** [comment]
@joaomoreno did you try on Windows?

**Comment by bpasero** [comment]
Ah yeah, now it works for me too. Weird...
