### ISSUE TITLE
Modal dialogs should reduce noise around dialog

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122521]
Related to https://github.com/microsoft/vscode/issues/122520

We should do something to the entire workbench when a modal dialog is open: either fade out, grayscale, blur, etc. Something that indicates to the user that everything but the modal dialog should be currently ignored.

**Comment by joaomoreno** [comment]
## Blur

![image](https://user-images.githubusercontent.com/22350/116396344-20cdcf00-a7da-11eb-80ed-ef3b20c40910.png)

## Grayscale

![image](https://user-images.githubusercontent.com/22350/116396388-2fb48180-a7da-11eb-9ed7-aa7aefa1e8b4.png)

## Blur + Grayscale

![image](https://user-images.githubusercontent.com/22350/116396253-0562c400-a7da-11eb-9258-a782cf2d4c51.png)

## Brightness

![image](https://user-images.githubusercontent.com/22350/116396501-54a8f480-a7da-11eb-9d3c-b895cdb851dc.png)

**Comment by joaomoreno** [comment]
Here's what GH does:

![image](https://user-images.githubusercontent.com/22350/116396800-a3568e80-a7da-11eb-9db0-a0b97bf60ecf.png)

**Comment by isidorn** [comment]
Agree, I vote for brightness.

**Comment by bpasero** [comment]
This is https://github.com/microsoft/vscode/issues/122393

**Comment by sbatten** [comment]
closing as duplicate
