### ISSUE TITLE
Trust: Missing settings link

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122542]
Testing #122209

Follow the same steps as https://github.com/microsoft/vscode/issues/122541

🐛 There's no link to see which settings are affected by trust.

![image](https://user-images.githubusercontent.com/22350/116412020-1cf67880-a7eb-11eb-84bb-d073641cf6d7.png)

**Comment by joaomoreno** [comment]
The link comes up if I untrust the workspace. 😕

![image](https://user-images.githubusercontent.com/22350/116412211-50390780-a7eb-11eb-9634-7301dd627300.png)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/122477
