### ISSUE TITLE
I couldn't get the `statusBar/remoteIndicator` contribution point to work

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#122524]
Testing #122102

Here is what I did:

- used yo code to generate a new VS Code extension
- used the following package.json
```json
{
  "name": "122102",
  "displayName": "122102",
  "description": "",
  "version": "0.0.1",
  "engines": {
    "vscode": "^1.55.0"
  },
  "categories": [
    "Other"
  ],
  "activationEvents": [
    "onCommand:extension.helloWorld"
  ],
	"enableProposedApi": true,
  "main": "./out/extension.js",
  "contributes": {
    "commands": [
      {
        "command": "extension.helloWorld",
        "title": "Hello World"
      }
    ],
    "menu": {
      "statusBar/remoteIndicator": [
				{
					"command": "extension.helloWorld",
					"group": "remote_50_wsl_1-open@1"
				}
			]
    }
  },
  "scripts": {
    "vscode:prepublish": "npm run compile",
    "compile": "tsc -p ./",
    "watch": "tsc -watch -p ./",
    "pretest": "npm run compile && npm run lint",
    "lint": "eslint src --ext ts",
    "test": "node ./out/test/runTest.js"
  },
  "devDependencies": {
    "@types/glob": "^7.1.3",
    "@types/mocha": "^8.0.4",
    "@types/node": "^12.11.7",
    "@types/vscode": "^1.55.0",
    "@typescript-eslint/eslint-plugin": "^4.14.1",
    "@typescript-eslint/parser": "^4.14.1",
    "eslint": "^7.19.0",
    "glob": "^7.1.6",
    "mocha": "^8.2.1",
    "typescript": "^4.1.3",
    "vscode-test": "^1.5.0"
  }
}
```

- made sure the extension.ts registers a command for `extension.helloWorld`

Started the extension. The remote menu I get is:

<img width="530" alt="capture" src="https://user-images.githubusercontent.com/1931590/116398128-bc396100-a827-11eb-8bd2-b482fd437031.png">

Observe: no Hello World entry

I consulted with @jrieken who is able to get it working but we couldn't find out what is different with my setup expect that I am under Windows and he is Mac

**Comment by RMacfarlane** [comment]
I was running into the exact same thing, and then realized that the contribution point should be `menus` and not `menu`. It would be great if there was some a console.log or something for property values that don't match the schema for contribution points

**Comment by dbaeumer** [comment]
@RMacfarlane thanks a lot for the pointer. I agree an indication that `menu` is an incorrect property would have solved this.

**Comment by aeschli** [comment]
First, sorry for misspelling `menu` in the test plan item.

I looked into adding validation. 
But `menus` is directly under `contributes` and we have already have extensions (e.g. the [java debugger](https://github.com/microsoft/vscode-java-debug/blob/ef8f74c1afa2e7c4b0e13ac3169e3a154203a71d/package.json#L53)) that add custom contributions unknown to us. So I can't restrict the possible entries to only the ones we know.
So in theory `menu` could indeed be something an extension reads.
