### ISSUE TITLE
Cannot remove text on vscode web

### ISSUE THREAD

**Issue by yolofanhd** [microsoft/vscode#122506]
- VS Code Version: 1.41.1
- OS Version: Android 10 (Samsung Galaxy A70)

Steps to Reproduce:

1. Start vscode server
2. Open vscode on web using a mobile device
3. Create a new file (For example test.js) 
4. Type any code so it gets autocompleted
5. If the code is highlighted blue it cant be removed

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
How do you highlight the text to be blue at step 5.? Can you please also add a screenshot?

**Comment by yolofanhd** [comment]
It gets colored blue if I click on the autocomplete options.

![20210430_164934.jpg](https://user-images.githubusercontent.com/76175017/116712380-17a85200-a9d4-11eb-97d0-3d1aa6905d67.jpg)

**Comment by alexdima** [comment]
I think this has also been fixed by https://github.com/microsoft/vscode/pull/124288
