### ISSUE TITLE
Trust: Can't debug extension right after trusting the folder

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122536]
Testing #122252

1. Scaffold a new extension using `yo code`
2. Open that extension in VS Code
3. Choose to trust that folder
4. Hit <kbd>F5</kbd> to start debugging

🐛 Debug fails to start with the following error:

![image](https://user-images.githubusercontent.com/22350/116405648-ba9a7980-a7e4-11eb-8343-fb46410fb028.png)

Once the window is reloaded, everything just works.

**Comment by isidorn** [comment]
Assigning to April so we investigate into this tomorrow.

**Comment by isidorn** [comment]
This just works for me in latest VS Code insiders.
Here are my steps:

1. VS Code insiders open starter extension sample
2. Dialog pops up -> you say trust it
3. Click on start debugging in debug view-> all works

Even if in the dialog I say "do not trust it" and later grant trust via trust editor this works
@joamoreno can you repro with todays insiders? Are you doing something different than me?

**Comment by joaomoreno** [comment]
I can repro yes. I am in WSL, that might affect it.

**Comment by isidorn** [comment]
@sbatten @lszomoru might it be that the Trust does not flow from the remote somehow? Did you get similar issues from other remote users?

**Comment by isidorn** [comment]
Friendly ping @sbatten @lszomoru

**Comment by lszomoru** [comment]
@isidorn, sorry for the delay. I will investigate this issue today.

**Comment by lszomoru** [comment]
I had a look and based on my tests this is not specific to WSL. Debugging the issue now and will circle back with my findings.

**Comment by lszomoru** [comment]
This has been fixed, as part of some work that I have done around extension enablement.

**Comment by isidorn** [comment]
@lszomoru thanks a lot!
