### ISSUE TITLE
'Go to file...' dropdown should not close when the app loses focus

### ISSUE THREAD

**Issue by joachim-n** [microsoft/vscode#122516]
- VS Code Version: 1.55.2
- OS Version: MacOS 10.15.7

The 'Go to file' dropdown vanishes when the app loses focus. On a big project where searching for a file can take quite a while, this means the user has to stare at the screen and can't do something else while VSCode searches in the background.

Steps to Reproduce:

1. Open a large project.
2. Do CMD-P to open the 'Go to file...' dropdown
3. Type part of a file name 
4. Switch to another app while VSCode is searching
5. Switch back to VSCode

Expected behaviour: VSCode is still busy searching

Actual behaviour: the dropdown is gone and the user has to begin the search all over again

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
There is a setting for this:
![image](https://user-images.githubusercontent.com/9205389/116475169-bec4a680-a879-11eb-9939-1cc878666ac8.png)

**Comment by joachim-n** [comment]
That setting seems weird. Particularly for the file open -- why would you ever want it to do that?

**Comment by chrmarti** [comment]
It will still close when you open a file, if that is what you mean.

**Comment by joachim-n** [comment]
No, what I mean is why would you want the 'Go to File...' dropdown to close when you switch focus to another app? Switching to another app should leave the current app in its existing state, surely.

**Comment by chrmarti** [comment]
@TylerLeonhardt for consideration. Not sure how you would distinguish loosing focus to another part of the window vs. to a different window.

**Comment by TylerLeonhardt** [comment]
I can sympathize with this, though I feel the same concerns that @chrmarti has. 

*Is it possible to distinguish loosing focus to another part of the window vs. to a different window?*

I'll mark as backlog candidate to gauge interest in investigating further.
