### ISSUE TITLE
Can't disable cut-line shortcut (Ctrl+X)

### ISSUE THREAD

**Issue by EnoughSensei** [microsoft/vscode#122518]
Issue Type: <b>Bug</b>

When you `cut` (Ctrl+X) with no selection it cuts the whole line. Since this shortcut is close to `save` (Ctrl+S) I find it annoying.

Steps to reproduce:

1. Find `cut` shortcut in `Keyboard Shortcuts` menu.
2. Add [`editorHasSelection`](https://github.com/microsoft/vscode-docs/blob/main/api/references/when-clause-contexts.md#available-contexts) as a `when` clause.
3. Reopen VSCode and use `cut` with no selection.
4. It will still cut the whole line.

[StackOverflow Question](https://stackoverflow.com/questions/67286304/can-you-disable-the-cut-line-function-of-cut-shortcut-ctrlx-in-vscode)

<details>
<summary>keybindings.json</summary>

```json
[
    {
        "key": "ctrl+x",
        "command": "editor.action.clipboardCutAction",
        "when": "editorHasSelection"
    },
    {
        "key": "ctrl+x",
        "command": "-editor.action.clipboardCutAction"
    }
]
```

</details>
<details>
<summary>Troubleshooting Log</summary>

```
[2021-04-28 13:18:42.079] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-04-28 13:18:42.080] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-04-28 13:18:42.081] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-04-28 13:18:42.502] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyX, keyCode: 88, key: x
[2021-04-28 13:18:42.503] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyX, keyCode: 54 ('X')
[2021-04-28 13:18:42.504] [renderer1] [info] [KeybindingService]: | Resolving ctrl+[KeyX]
[2021-04-28 13:18:42.504] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, no when clauses matched the context.
[2021-04-28 13:18:42.669] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
[2021-04-28 13:18:42.970] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

</details>

VS Code version: Code - Insiders 1.56.0-insider (13f1afffab09548c10ddb3bc5d5db52587876ad8, 2021-04-28T04:52:56.570Z)
OS version: Linux x64 5.4.0-72-generic

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872
00j7a122:30294756

```

</details>

**Comment by EnoughSensei** [comment]
This problem dates back to 2018.
https://stackoverflow.com/questions/48554125/simple-keybind-not-working-as-expected (February 1, 2018)

**Comment by alexdima** [comment]
You can use the following setting:
```
"editor.emptySelectionClipboard": false
```

**Comment by ArturoDent** [comment]
The solution `"editor.emptySelectionClipboard": false` does have the consequence of affecting **both** copy and cut actions which may be an undesirable outcome.

**Comment by EnoughSensei** [comment]
@alexdima That does what I initially wanted (disable `cut-line`) but doesn't explain why `editorHasSelection` isn't working. Do you suggest that I make a *seperate* issue for that?

**Comment by EnoughSensei** [comment]
To be honest, this feels like a quick hack instead of a real solution.

**Comment by alexdima** [comment]
@EnoughSensei You can use the following keybindings rules. `ctrl+x` is special compared to other keybindings because it has a default behavior when it falls through our keybinding dispatching (it will trigger a browser 'cut' event):

```
[
    {
        "key": "ctrl+x"
    },
    {
        "key": "ctrl+x",
        "command": "editor.action.clipboardCutAction",
        "when": "editorHasSelection"
    }
]
```

**Comment by ArturoDent** [comment]
Wow, I tried an empty key like

    {
        "key": "",
        "command": "-editor.action.clipboardCutAction",
    }

but it didn't do anything.  I didn't know you could simply have a keybinding with no command that would disable the command.

**Comment by EnoughSensei** [comment]
@alexdima Thanks for the quick response. Unfortunately this doesn't work.

**Comment by ArturoDent** [comment]
```
    {
      "key": "ctrl+x",
      "command": "",
    },
```
seems to work.  Needs an empty command.

**Comment by EnoughSensei** [comment]
@ArturoDent Unfortunately that doesn't work on my side as well when `editor.emptySelectionClipboard` is `true`.
However when I do `"command": ";"` it works (also causes a popup).

**Comment by ArturoDent** [comment]
Yeah, I deleted that option - I still had the setting.  I think you are back to the `notifications.clearAll` suggestion.

**Comment by EnoughSensei** [comment]
Yeap.

**Comment by alexdima** [comment]
@EnoughSensei You're right, sorry about that, I didn't test what I posted earlier. I must have broken that at some point, omitting a command should have called `e.preventDefault()` on the `keydown` event, but it looks like it doesn't anymore. I will investigate that.

But you can use a command that is effectively a no-op without a selection. e.g.:

```
	{
		"key": "ctrl+x",
		"command": "editor.action.sortLinesAscending"
	},
	{
		"key": "ctrl+x",
		"command": "editor.action.clipboardCutAction",
		"when": "editorHasSelection"
	}
```

**Comment by alexdima** [comment]
> omitting a command should have called `e.preventDefault()` on the keydown event, but it looks like it doesn't anymore. 

I am wrong again. Omitting a command should not call `e.preventDefault()`. It never did, I looked it back to 2015.

`ctrl+x` is just special and needs to be bound to a no-op to stop the default. I have added a `noop` command that does nothing. So the final solution would be:
```
	{
		"key": "ctrl+x",
		"command": "noop"
	},
	{
		"key": "ctrl+x",
		"command": "editor.action.clipboardCutAction",
		"when": "editorHasSelection"
	}
```

**Comment by EnoughSensei** [comment]
Thank you for your help <3
