### ISSUE TITLE
Missing trusted domain configuration 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#122550]
Testing #122243

I tried to create a commit, and I get

![image](https://user-images.githubusercontent.com/4674940/116423367-795e9580-a7f5-11eb-8557-856439f30cd7.png)

which is good. So, I press Learn More and get

![image](https://user-images.githubusercontent.com/4674940/116423440-8bd8cf00-a7f5-11eb-8238-30d9a1ef8a83.png)

This is unexpected. You send me there. Either we think the page is good to go there or not. If not, we need our own doc for this.

**Comment by lszomoru** [comment]
Fixed with f62bfae0013f949c24befe1c615757a3286b4fb9. Switched to aka.ms links.

**Comment by jrieken** [comment]
Verified in source
