### ISSUE TITLE
No file association for .ipynb

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#122589]
## Steps to Repro:

1. Clean install of VS Code with no notebook extensions
2. Try to drag a .ipynb file into the editor
3. File opens as JSON

## Actual Behavior:
The file association in the bottom right shows Plain Text, not JSON

## Expected Behavior: 
The file association in the bottom shows JSON

**Comment by rebornix** [comment]
We can add `ipynb` to the json extensions list.
