### ISSUE TITLE
Group extensions and enable or disable a group with one click

### ISSUE THREAD

**Issue by preIdiot** [microsoft/vscode#122504]
It becomes messy when you have a lot of extensions in vscode. It will be nice if I can group extensions any way I want. 

Like to group extensions needed for javascript and react together or group theme, and configuration extensions together and then enable or disable the group with a single click.

In this way, it will look more organized and easy to enable or disable the extensions.

Thank you ✌🏻

**Comment by gjsjohnmurray** [comment]
It is already possible to create your own Extension Packs to do this.

Another approach is to save an empty window as a workspace, disable all extensions for the workspace, then re-enable only the ones you want. Optionally set the xxx.code-workspace file readonly. Now use it as a template (Save Workspace As...).

**Comment by sandy081** [comment]
/duplicate

Thanks for filling this issue. There is already a feature request for user grouping of extensions. Please search for issues with label `extensions` to find.
