### ISSUE TITLE
`windows key` doesn't work inside vscode.. it works outside

### ISSUE THREAD

**Issue by j0k4rX** [microsoft/vscode#122508]
I am using this [**better jest**](https://marketplace.visualstudio.com/items?itemName=CoachRichbart.better-jest&ssr=false) extension on visual studio code.
there are shortcut keys like: `Windows + k + r`

unlike macOS `cmd` key, there is `windows key` on windows operating system

I can't seem to use the shortcut keys on windows
when I press `windows key` it doesn't work inside the editor.
rather it works outside.

I could make other keybindings, but I have important shortcuts with this `windows key`.
so. i hope you fix this issue

- VS Code Version: 1.55.2
- OS Version: Windows 10 pro

Does this issue occur when all extensions are disabled?: Yes

**Comment by j0k4rX** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Record Keys shortcut not updating (#118765)](https://www.github.com/microsoft/vscode/issues/118765)

No, it's not the same

**Comment by IllusionMH** [comment]
/needsMoreInfo

What shortcut you are trying to use? Windows would intercept something like <kbd>Win</kbd>+<kbd>A</kbd> however I can't reproduce problems with <kbd>Shift</kbd>+<kbd>Win</kbd>+<kbd>Q</kbd>
```json
{
    "key": "shift+win+q",
    "command": "editor.action.commentLine",
}
```

Please use steps described in https://github.com/microsoft/vscode/wiki/Keybinding-Issues to see if VS Code receives these shortcuts at all.

In troubleshooting logs <kbd>Win</kbd> will be displayed as `meta` modifier e.g.
```
[info] [KeybindingService]: / Received  keydown event - modifiers: [shift,meta], code: KeyQ, keyCode: 81, key: Q
[info] [KeybindingService]: | Converted keydown event - modifiers: [shift,meta], code: KeyQ, keyCode: 47 ('Q')
[info] [KeybindingService]: | Resolving shift+meta+Q
[info] [KeybindingService]: \ From 1 keybinding entries, matched editor.action.commentLine, when: no when condition, 
```

**Comment by IllusionMH** [comment]
`Windows + k + r` I guess it's chord like `"key": "cmd+k cmd+r",` from extension.
Both <kbd>Win</kbd>+<kbd>K</kbd> and <kbd>Win</kbd>+<kbd>R</kbd> are system shortcuts that are intercepted by OS.

**Comment by j0k4rX** [comment]
@IllusionMH if i wanted the keys to work inside vscode (without `shift` key in front)
what can i do for that?

**Comment by alexdima** [comment]
@j0k4rX If the OS consumes a keybinding, there is nothing VS Code can do. You can try looking online for how to disable OS hotkeys.
