### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by zohimchandani** [microsoft/vscode#122538]
- VS Code Version: latest
- OS Version: win10

Steps to Reproduce:

1. simple print hello world program on python 
2. fails to execute the simple command 

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/60148725/116408910-3f0feb00-a82b-11eb-8163-080de903adb3.png)

**Comment by zohimchandani** [comment]
I also seem to need to run `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process` very often to activate virtual environments. Any ideas why this may be?

**Comment by alexdima** [comment]
Please ask this question on StackOverflow, this does not appear to be a problem with VS Code.
