### ISSUE TITLE
Href issue - not working

### ISSUE THREAD

**Issue by Reevka** [microsoft/vscode#122500]
Issue Type: <b>Feature Request</b>

I'm not sure why but my href links aren't working for opening email or for going to a contact page. It seems to work when placed alternatively on the page. So I'm sure something in the code is stopping it.

**Comment by Reevka** [comment]
That isn't the issue, it works in Visual Studio Code, but not in the browser.

**Comment by alexdima** [comment]
@Reevka Here we can only help with issues with VS Code itself. If you have a problem with the application you are developing, please use StackOverflow for questions.
