### ISSUE TITLE
Test External Terminal support for runInTerminal request

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#12252]
Test for #11581:

- [x] Windows - @stevencl 
- [x] OS X - @chrmarti
- [x] Linux - @octref 

Complexity 2

In this release the implementation of the 'run in external terminal' feature (`"console": "externalTerminal"`) of node-debug has been moved to VS Code (and is now available for all debug adapters.)
A benevolent side effect of this move is that it is now possible to configure the terminal program to use via the `terminal.external.windowsExec`, `terminal.external.osxExec`, `terminal.external.linuxExec` settings.

Make sure that:
- you can launch a debug target in an external terminal,
- `cwd`, env vars and arguments are passed correctly,
- you can configure a different terminal and things still work.

**Comment by octref** [comment]
@weinand On linux not working for other terminals like `rxvt-unicode` and `terminator`: #12791

**Comment by octref** [comment]
Also, restarting task doesn't get previous externalTerminal closed: #12793
