### ISSUE TITLE
Expand the set of `doneOn` clauses available to walkthrough steps

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122570]
Currently vscode only allows a step to be `doneOn` a command having been executed. This should be expanded to support:

- [x] A link being opened (via a walkthrough)
- [x] A view having become visible
- [x] A setting having been modified
- [x] An extension being installed
- [x] A context key being set
- [x] A script (in core) explicitly checking the item off
- [x] The item being selected

Maybe more?

cc @digitarald

**Comment by digitarald** [comment]
Given how flexible context keys are, that list looks good!

**Comment by digitarald** [comment]
For C++, clauses for `launch.json` and `tasks.json` set up. Potentially looking at specific types of entries.

**Comment by JacksonKearl** [comment]
Couple changes in tomorrows insiders:
- doneOn is deprecated in favor of new "completionEvents", doneOn will still work the same, but completionEvents are preferred going forward (this mirrors activationEvents)
- by default, with no doneOn or completionEvents set, the step will be checked when any of its buttons are pressed (links or commands)
  - if the step has no buttons, it will be checked when it's selected
- completionEvents accepts entries in the format: 
'onCommand:${1:commandId}'
'onLink:${2:linkId}'
'extensionInstalled:${3:extensionId}'
'stepSelected'

**Comment by JacksonKearl** [comment]
Verify by playing with the sample https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample, the steps use these completion events.

**Comment by alexr00** [comment]
I can't get `onLink` to work:

```
					{
						"id": "openlink",
						"title": "Open Link",
						"description": "This step will open a link and check off.\n[Open Link](http://bing.com)",
						"media": {
							"image": "media/image.png",
							"altText": "Empty image"
						},
						"completionEvents": [
							"onLink:http://bing.com"
						]
					}
```

**Comment by alexr00** [comment]
Also, `onSettingChanged` causes steps to always show as complete, even when a setting has never been touched.

**Comment by alexr00** [comment]
> A script (in core) explicitly checking the item off

How should this one be tested?

**Comment by JacksonKearl** [comment]
> How should this one be tested?

That's there to enable checking off on settings sync being activated. If you see 
![image](https://user-images.githubusercontent.com/8586769/120840534-3e036500-c51f-11eb-9b7f-4cc1e780d120.png)
when settings sync is activate, it is working as intended.

**Comment by meganrogge** [comment]
@alexr00 did you verify this or what are the items you didn't get to? I will do those.

**Comment by alexr00** [comment]
`onLink` needs to be verified.
This one also needs to be verified: https://github.com/microsoft/vscode/issues/122570#issuecomment-854889959.

Everything else has been verified.
