### ISSUE TITLE
Notebook cell focus indicator is wrong

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122594]
![image](https://user-images.githubusercontent.com/323878/116482679-7b971300-a83a-11eb-9fa6-a609a41eb584.png)

Just alternate pressing enter and escape several times, and 1/10 times, the indicator is on the cell while the editor has focus

**Comment by rebornix** [comment]
it's likely a race condition. I'm not confident with the editor focus code we have for cell editors.

**Comment by roblourens** [comment]
The trick is to press enter immediately after pressing escape
