### ISSUE TITLE
cmd+P brings up the print dialog when a notebook is active, in web

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122596]
- Open a codespace window in web
- Open a notebook
- Press cmd+P
- Get the print dialog instead of quick open
- If a text editor is active, I get the quick open

No clue what prevents this or why it would be different in a notebook

**Comment by roblourens** [comment]
Do you know about this @bpasero?

**Comment by bpasero** [comment]
Not sure, sounds a bit like https://github.com/microsoft/vscode/issues/82592

**Comment by mjbvz** [comment]
Reopening to investigate further. This seems to happens for any webview (tested with the markdown preview). We are somehow blocking it in the editor

**Comment by rzhao271** [comment]
The print dialog still seems to show up on Windows when using Edge:

![recording (28)](https://user-images.githubusercontent.com/7199958/120555617-2d80ac80-c3b0-11eb-9bb1-78390297f5b2.gif)

**Comment by mjbvz** [comment]
Seems to work for me on windows. @rzhao271  Can you make sure you on the insiders version of codespaces (or test on vscode.dev)
