### ISSUE TITLE
Cmd+F renders badly on special characters.

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [microsoft/vscode#122556]
Issue Type: <b>Bug</b>

Selecting any piece of text containing eitehr of characters `x0c` or `x0d` and pressing `cmd + F` renders only half of the search window.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 117ccf04-9859-4996-9a11-f31692bc4bcc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MarcinKonowalczyk** [comment]
```
Searching for any of this is fine: 	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abc...

Searching for these two characters breaks: 
```

(I'm not sure how happy will the GitHub markdown be with ascii characters below x21)

**Comment by MarcinKonowalczyk** [comment]
Also, upon further experimentation, this bug does *not* happen when searching for `x0c` and `x0d` in conjunction with other characters.

**Comment by alexdima** [comment]
I can reproduce. I think this came in via https://github.com/microsoft/vscode/pull/79329

**Comment by MarcinKonowalczyk** [comment]
Following the search box updates, i've re-tested this in the current version of vscode and the issue is gone. Closing the issue.
