### ISSUE TITLE
[contributes.menus] how to show menu only in editor not Output window

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#12263]
I have an [extension ](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) which contributes a menu in context menu of editor. However, the menu also shows in the Output window. How could I make it only show in editor. BTW, the menu shows in Output window but not in Debug Console or Integrated Terminal. Is it bug or by design?

**Comment by chrmarti** [comment]
The package.json seems to correctly target only the editor:

```
        "menus": {
            "editor/context": [
                {
                    "command": "code-runner.run",
                    "group": "navigation"
                }
            ]
        },
```

**Comment by jrieken** [comment]
@formulahendry You can use the `where` clause to limit the showings of the context menu. Our markdown extension for instances [does](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L82) that. However, we lack context keys to signal that we are in the output channel or debug repl. Maybe a good starting point for you would be to check for a selection like so `"when": "editorHasSelection"`

cc @isidorn to check if have a context key that ala `inDebugRepl`?

**Comment by formulahendry** [comment]
`editorHasSelection` is when there are selections of some text, right? However, I want the menu always to be shown in editor, but not Output window.

**Comment by isidorn** [comment]
We have the key `inDebugRepl`, however we currently do not have `inOutput` - though we could add it if needed.

**Comment by jrieken** [comment]
Assigning @isidorn for the `inOutput` context key. @formulahendry Until then you can use trick which is to check for the editor language id like so `"when": "editorLangId != Log"`but note that we will allow to set the language for an output channel in the future, breaking that trick

**Comment by formulahendry** [comment]
Hi, I use vs code 1.6 with below config but the menu still shows in output window. Any idea?

```json
        "menus": {
            "editor/context": [
                {
                    "when": "!inOutput",
                    "command": "code-runner.run",
                    "group": "navigation"
                }
            ]
        }
```

**Comment by isidorn** [comment]
@formulahendry this should work as assigning simple keyboard shortcuts with the  "when": "!inOutput" - works fine for me. 
@jrieken any suggestions?

**Comment by formulahendry** [comment]
I update the extension 
[code-runner-0.3.4.zip](https://github.com/Microsoft/vscode/files/528471/code-runner-0.3.4.zip)
with below changes:
![image](https://cloud.githubusercontent.com/assets/1050213/19372378/1ab48a98-91ee-11e6-8f7f-2c2c7b0acf72.png)

But the 'Run Code' still shows when I right-click in the Output Window area.

**Comment by formulahendry** [comment]
Seems like it only works in `keybindings` but not in `menus`
![image](https://cloud.githubusercontent.com/assets/1050213/19372509/56181b9e-91ef-11e6-9fff-9364c940dc1f.png)

**Comment by formulahendry** [comment]
Hi, any idea on this?

**Comment by jrieken** [comment]
@isidorn It depends with what context service you create the editor widget. It must be the same that manages the `inOutput` key

**Comment by isidorn** [comment]
Sorry for the slow reply - I was working on an isolated branch.

@jrieken currently I just use the scoped context key service like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputPanel.ts#L103)
This nicely works for the keybinding, however the bottom line issue is probably that scoped editor service is not used by the menu. I can not use the global context key service to manage my key since then my key will be always enabled no matter if my element has focus or not.

So it seems that I have to make the workbench create my editor using a scoped context service which I am not sure if is possible. Can investigate but let me know if I am missing something obvious here...

**Comment by jrieken** [comment]
Where/How do you pass on that scoped service instance to the editor?

**Comment by isidorn** [comment]
Well I do not pass it currently. It is enough for the scoped service to be created on the appropriate HTML element and everything seems to work just fine for the keybindings.

**Comment by jrieken** [comment]
You should because otherwise those keys aren't visible (as you see with the context menu). My knowledge might be outdated after @alexandrudima last refactoring but if you create a child context and don't pass it on the editor it's key/value entries aren't visible to the editor.
