### ISSUE TITLE
Notebook editor leakage

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122668]
* open dev tools > memory pane
* open a notebook editor
* close the notebook editor
* create a heap snapshot - size is 79MB (in my case)
* open/close the notebook editor repeatedly - like 7 times to amplify the impact of leaks
* create another heap snapshot - size is now 85MB

Analysing and comparing the heaps is tricky... I cannot work well with the compare mode but a good tactic is to fish for objects that are known to be used by the notebook editor, like `CodeEditorWidget`. For instance the first snapshot has 6 instances of the code editor, the second has 34 instances. They seems to be leaking via some cell template

<img width="716" alt="Screenshot 2021-04-29 at 16 24 00" src="https://user-images.githubusercontent.com/1794099/116566777-51f7ed80-a907-11eb-951e-23fd0d15e4dd.png">

**Comment by jrieken** [comment]
I consider myself off the hook because the `notebookEditorWidgetServiceImpl` does invoke dispose of the notebook widget but it seems that doesn't do a full cleanup

<img width="682" alt="Screenshot 2021-04-29 at 16 48 21" src="https://user-images.githubusercontent.com/1794099/116570642-b799a900-a90a-11eb-8f55-ed2e862f1344.png">

**Comment by jrieken** [comment]
I still see leakage (roughy 0.5MB per notebook open, close). I see that notebook editors itself are leaking through some notebook editor contribution...

<img width="734" alt="Screen Shot 2021-05-05 at 12 26 55" src="https://user-images.githubusercontent.com/1794099/117128085-3d02da80-ad9d-11eb-9f6f-d4e41623e3a3.png">

**Comment by jrieken** [comment]
I have pushed a change that caused leakage due to notebook editor contributions using the same identifier. With that contributions would override each other and prior one would never get disposed - fyi @roblourens for the contributions and @rebornix for stricter contribution checks

**Comment by jrieken** [comment]
With those changes there is still leakage through a listener onto the configuration service... 💧

**Comment by jrieken** [comment]
Still leaking a few thousand emitters...

<img width="559" alt="Screen Shot 2021-05-05 at 12 54 36" src="https://user-images.githubusercontent.com/1794099/117130956-0fb82b80-ada1-11eb-8acb-3544b0343db5.png">

**Comment by jrieken** [comment]
Things are better but there is still plenty leakage. I have marked the ones that seem scary and the notebook widget should use the "unref-on-dispose" strategy for "heavy" objects

<img width="622" alt="Screen Shot 2021-05-05 at 17 59 23" src="https://user-images.githubusercontent.com/1794099/117172095-c4ffd900-adcb-11eb-96cb-2057f7c4a6f9.png">

**Comment by rebornix** [comment]
Pushed changes to remove the refs to following objects on dispose

* PrefixSumComputer
* List View Renderers
* CellDragAndDropController
* CellContextKeyManager
* CellViewModels, referrenced by
  * pending layout weak map
  *  `NotebookEditorContextKeys`
  * NotebookEditor._widgetDisposableStore

With them removed, the refs to the NotebookEditorWidget is much fewer and there are two major components referencing the closed notebook editor:

* `editorControl` @jrieken @bpasero not sure why they don't un-ref the notebook editor

  <img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/117221046-5c116480-adbd-11eb-8cc6-1dfda74c54d9.png">
* List view decorators https://github.com/microsoft/vscode/issues/122999
  
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/117221141-882ce580-adbd-11eb-9b01-d189d0c651c0.png">

**Comment by rebornix** [comment]
@connor4312 figured out why we have zombie event listeners (fix https://github.com/microsoft/vscode/commit/9c4626048432cb47b67cebbb64dddadfa6cdd149), we have more than 3 event listeners for an emitter, and when we dispose the emitter, the 2nd and 3rd listener are still referencing each other (through `prev` and `next`), as long as any listener is not disposed properly, the other listener won't be gc'ed.

With this fix and disposing/unrefing objects in the notebook editor widgets, right now the notebook editor widget is mostly refer by the two components mentioned above https://github.com/microsoft/vscode/issues/122668#issuecomment-833109537 .

**Comment by bpasero** [comment]
@rebornix editor controls are not disposed from the last opened group that is there, even when empty. To see if something leaks you need to test with >1 group. The reason is a bit historic but we typically keep the editor widgets in the last group around to allow for speedy reopen.

**Comment by jrieken** [comment]
> @rebornix editor controls are not disposed from the last opened group that is there, even when empty.

@bpasero We are actually fighting against that. Our editor is so heavy that we have code to detect this special case so that we still dispose it (see [here](https://github.com/microsoft/vscode/blob/993e71e89bfe5a6ccc8c8430c0461830b8368dd4/src/vs/workbench/contrib/notebook/browser/notebookEditorServiceImpl.ts#L53))

**Comment by jrieken** [comment]
With all the fixes that have been I don't see any NoteEditorWidget leaking any. Also no code editor or model leaking. This is a great output. Opening closing a notebook editor with 6 code cells repeatedly for 10 times shows a growth of ~.5 MB (down from ~5MB) but there is nothing specific to notebook. Hence, and in celebration, I am closing this issue.
