### ISSUE TITLE
Not enough storage is available to process this command. 

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#12260]
- VSCode Version: 1.60
- OS Version: Win 10

Steps to Reproduce:

1. 
2. 
![2016-09-19_175043](https://cloud.githubusercontent.com/assets/8591065/18628198/9edd38d0-7e91-11e6-9f03-1ad8f71b714c.png)

**Comment by chrmarti** [comment]
Could me a red herring: http://stackoverflow.com/questions/8857210/not-enough-storage-is-available-to-process-this-command-after-using-the-start

**Comment by Tyriar** [comment]
I've seen this before, we also do set the title as `""`.

**Comment by ZCShou** [comment]
Only appear when i run vscode as administrator!

**Comment by CoenraadS** [comment]
It seems setting the title to anything fixes this problem.

Even `title ""` makes it go away.

**Comment by CoenraadS** [comment]
I can confirm setting the title to anything makes it go away.

**Comment by Tyriar** [comment]
This was fixed in winpty v0.3.0 (https://github.com/rprichard/winpty/issues/74), so [pty.js](https://github.com/Tyriar/pty.js) needs to be upleveled to fix this.

**Comment by Tyriar** [comment]
Pulled in the change to pty.js from upstream winpty (https://github.com/Tyriar/pty.js/commit/c75c2dcb6dcad83b0cb3ef2ae42d0448fb912642) and upleveled.

To verified:

1. Close all instances of VS Code
2. Launch VS Code as administrator
3. Open the terminal (ensure cmd.exe), the message should not be present
