### ISSUE TITLE
Typescript server crashed 5 times

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#122628]
Issue Type: <b>Bug</b>

Was editing two files side-by-side, in a docker container derived from node:14, with additional unix commandline applications installed, that don't impact the code in question, and using yarn as the package manager. 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container o3-dev-node:14-latest (/dev-connectors_pm2_1)|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (2 x 1600)|
|Memory (System)|1.94GB (0.77GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.166.1
vscode-openapi|42C|4.5.0
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
bash-ide-vscode|mad|1.11.0
mongodb-vscode|mon|0.5.0
compare-folders|mos|0.21.0
vscode-yaml|red|0.18.0

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

/needsMoreInfo

**Comment by navneetkarnani** [comment]
I haven't seen this message again yet. Will upload more data when I see it.

**Comment by navneetkarnani** [comment]
Now that I know what to look for, will open a new issue when I see this error again. Don't want to keep this around just for the sake of it.
