### ISSUE TITLE
spawn very slow on macOS

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122661]
The extension host, esp Git seems very sluggish these days. The log shows that the extension host as stalled many times and it always points to `spawn`. 

```
[2021-04-29 15:24:16.080] [renderer3] [warning] UNRESPONSIVE extension host, 'vscode.git' took 78% of 1058.568ms, saved PROFILE here: 'file:///var/folders/5t/b385jb8s4vs40mp7342_b02r0000gn/T/exthost-5da4a5.cpuprofile' 
```

<img width="759" alt="Screenshot 2021-04-29 at 15 36 08" src="https://user-images.githubusercontent.com/1794099/116559460-c8ddb800-a900-11eb-8530-f8e65a29a41f.png">

**Comment by jrieken** [comment]
[slow1.cpuprofile.txt](https://github.com/microsoft/vscode/files/6398982/slow1.cpuprofile.txt)

**Comment by deepak1556** [comment]
Can you run `sudo dtruss -ef -p <PID> -t posix_spawn` where PID is of extension host and open some files so that git creates some child processes.

**Comment by lramos15** [comment]
[posix_spawn.txt](https://github.com/microsoft/vscode/files/6399337/posix_spawn.txt)
Here's me running on a very small repo (the hex editor repo), making a single character change.
