### ISSUE TITLE
    Revert "Merge pull request #122540 from microsoft/tyriar/122104"

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122611]
Issue Type: <b>Bug</b>

28a1bc2f35e1354ab9e2f4e01553ea8b86cb6d7a reverted this change since it caused the browser integration tests to fail

VS Code version: Code - Insiders 1.56.0-insider (Universal) (13f1afffab09548c10ddb3bc5d5db52587876ad8, 2021-04-28T04:50:45.511Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (4.12GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
vscode-eslint|dba|2.1.20
typescript-notebook|don|1.2.0
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
codespaces|Git|0.9.4
vscode-pull-request-github-insiders|Git|2021.4.40200
vscode-postfix-ts|ipa|1.9.3
latex-workshop|Jam|8.17.0
template-string-converter|meg|0.4.7
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.6.792062886
remote-containers|ms-|0.172.0
remote-ssh-edit-nightly|ms-|2021.4.39780
remote-ssh-nightly|ms-|2021.4.39780
azure-account|ms-|0.9.8
hexeditor|ms-|1.6.0
vscode-github-issue-notebooks|ms-|0.0.85
debugger-for-chrome|msj|4.12.12
java|red|0.77.0
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.0
vscode-java-dependency|vsc|0.18.3
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.30.0

</details>

**Comment by mjbvz** [comment]
Example failure: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116151&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3&l=56

```
illegal state - RECURSIVELY instantiating service 'terminalProfileResolverService': _safeCreateAndCacheServiceInstance@http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:625:2044
_getOrCreateServiceInstance@http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:625:1885
_createInstance@http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:625:957
createInstance@http://localhost:8000/static/out/vs/workbench/workbench.web.api.js:625:793
...
```

I believe the cycle is:

```
RemoteTerminalService -> RemoteTerminalChannelClient -> ITerminalProfileResolverService
BrowserTerminalProfileResolverService (implements ITerminalProfileResolverService) -> IRemoteTerminalService
```

**Comment by Tyriar** [comment]
Looks like @meganrogge fixed this yesterday with https://github.com/microsoft/vscode/commit/e7c0af1137fd1788b8ba853f7351af4498f1a544#diff-38cb820e08ef9a8479ff998378fa4b33cd3a9e57461329ded57f8a4b5e8dae4a and https://github.com/microsoft/vscode/commit/033934457979b1993ae8eb9301ea9a1fcaebde39
