### ISSUE TITLE
Ability to pin folders, files by workspace to the explorer top

### ISSUE THREAD

**Issue by essuraj** [Microsoft/vscode#12266]
It would be nice to have the ability to pin folders, files by work space
small sample attached below
![Sample custom toolbar](https://cloud.githubusercontent.com/assets/1737617/18632279/430198aa-7e94-11e6-8f35-3352c9fb429b.jpg)

projects tend to become long and switching can be eased.
config can be maintained with a simple json array withing settings.json inside .vscode folder

**Comment by chrmarti** [comment]
Am I understanding correctly: You would like to have 'shortcuts' to a configurable set of folders and files within the workspace? Clicking on one of those would open a folder in the tree and a file in the editor?

**Comment by essuraj** [comment]
Yes. It would help a lot of time while switch back and forth files and folders from multiple hierarchies in a project,
for example between website,server code and routes etc.. in frameworks such a sails.js.

**Comment by chrmarti** [comment]
Trying to think of an interim solution: You probably know about the File > Recent menu, that allows you to quickly switch between recent folders / files?

**Comment by chrmarti** [comment]
Related to #396

**Comment by essuraj** [comment]
the  File > Recent menu doesn't give me the ability to (add pin/add shortcut/add bookmark) the files or folders from my current project.

**Comment by SailorMax** [comment]
Good idea, but pinned list better output in separate group "PINNED" as simple list. Between "OPEN EDITORS" and "[FOLDER NAME]" (In EXPLORER tab).

**Comment by essuraj** [comment]
@SailorMax does it matter if the pinned item is highlighted? You would rather click on the pinned item if you want to get back to it... rather than searching for the lost(opened) tab.

**Comment by SailorMax** [comment]
@essuraj It may be matter for pinned folder. It can help to remember which "project" currently opened when you trying to find to open another.
For first release developers can skip this function. Will try without it.

**Comment by gpuido** [comment]
I would use this all day long. 
Find the files I need in the tree, pin those, work, unpin some, pin some new, work, etc ....

No question about the usefulness of tabs for some workflows but my bet is that without those,
Working files, Open Editors would have become an advanced pinning system.

Anyway, now that tabs are in, a new push toward the original idea to go away from tabs would be nice.
Code is just a beauty with just the tree, editor & console.

``` json
"workbench.editor.showTabs":false,
"explorer.openEditors.visible": 0,

"explorer.pinItems.enable": true,
"explorer.pinItems.moveToFolderTop": true,
"explorer.pinItems.duplicateToExplorerTop": true
```

**Comment by gpuido** [comment]
A good complement to this work on the tree https://github.com/Microsoft/vscode/issues/11885
_shameless plug_

**Comment by GitClickOk** [comment]
In my asp.net mvc project will be like a dream if I can pin Models, Views and Controllers folders on the top of folder tree... From dozen of folders, that 3 are far 90% where is my work!

**Comment by huangxuewu** [comment]
+ 1 for pin folder.  It's nice feature if you working on the large project.  some file just use more than others (for example: the i18n folder ). In recent file list they are display the whole file directory which is not very convient to find if you break your files into smaller components.

**Comment by burtek** [comment]
pinning folders to top would be a real life saver in huge projects

**Comment by cdmihai** [comment]
Pinned directories (and why not files) would be helpful. I work in a huge repo, and my "main active directories" change every few days (these are dirs where all sorts of logs get dumped in). Right now I'm using multiple VSCode instances, but switching to the right one is a hassle. I could just open relevant log files, but I cannot pin files or tabs.

**Comment by Lubdhak** [comment]
If not pin, custom shortcuts maybe

**Comment by jaybabani** [comment]
May be tabs if not pins? Root folders as tabs at top

**Comment by cscheffauer** [comment]
+1 for pinned directories as well!

**Comment by msaspence** [comment]
Check out https://github.com/SaekiRaku/vscode-pin-up

**Comment by cmonroeEIS** [comment]
Thanks @msaspence but 
Unable to install 'saekiraku.pin-up' extension because it is not compatible with the current version of VS Code (version 1.40.2).

**Comment by bobajeff** [comment]
I'm using the Pin-up extension now but I also think this should be a builtin feature.

**Comment by micktg** [comment]
The [favorite extension](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites) works as well. It stores the reference to a favorite file inside settings.json instead of creating a new file pinned-files.json like the Pin Up extension.

**Comment by donysukardi** [comment]
has anyone found an extension that does this and keep the pinned folders live without having to refresh them manually?
