### ISSUE TITLE
terminal is borked in linux running version 1.55.2

### ISSUE THREAD

**Issue by opensas** [microsoft/vscode#122618]
- VS Code Version:
- OS Version:

All of the sudden my terminal from vscode seems broken, the font seems wrong and everything is misaligned:

![image](https://user-images.githubusercontent.com/481687/116499969-e3258080-a883-11eb-82c4-e63ddc65154a.png)

any idea what could have happened and how could I fix it???

a bit context info:

$ uname -a
Linux xps 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-73-generic

**Comment by opensas** [comment]
I downloaded a portable version of vscode and the terminal shows ok, moreover, I deleted the data folder and again the termina is broken, so I guess it could be some extension or config messing around.

I tried reloading with extensions disbled but the problem persists.

If anybody could help trouble shoot this issue it would be greatly appreciated
thanks!

**Comment by DavidePapa** [comment]
Hi, same problem.

**uname -a **
Linux ku 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**VSCode About**

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-72-generic

**temporary fix**
You can fix splitting the terminal and then merging with bin icon (if you use a debugger attached to the terminal do it the same fix)

**Comment by zkhcohen** [comment]
+1 

This is impacting four separate machines all running 1.55.2 and using a remote terminal into Ubuntu/Rancher.

**Comment by johan-w2w** [comment]
Same issue here with WSL2 with VSCode 1.55.2
