### ISSUE TITLE
Support opening links in the terminal relative to the actual cwd (not initial)

### ISSUE THREAD

**Issue by pmonajem** [microsoft/vscode#122617]
Issue Type: <b>Bug</b>

Click to open a file path from terminal doesn't work if the relative path displayed on terminal starts from above workspace root.

Workspace root is /a/b
Our file is located at /a/b/c/d.txt

These paths work if I Alt+Click on them on the terminal :
/a/b/c/d.txt
c/d.txt
d.txt

This path won't work :
b/c/d.txt

It's arguably easy to check the root path and realize that this relative path is starting from a node above. 

Use case : My compiler is printing error messages with file paths starting from a higher folder than the one added to the workspace. I can't click to open the error locations due to the path issue above.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.18.0-147.3.1.el8_1.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.60GB free)|
|Process Argv|--crash-reporter-id b7556bc8-76c5-4d1a-89ed-5ef163a08323|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sjc-ads-4989|
|OS|Linux x64 4.18.0-147.3.1.el8_1.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (16 x 3192)|
|Memory (System)|31.23GB (0.81GB free)|
|VM|100%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.5
yang|mar|0.1.3
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.3076
tdl-extension|aim|0.1.0
Bookmarks|ale|13.0.4
bgforge-mls|BGf|1.15.3
doxdocgen|csc|1.2.0
githistory|don|0.6.16
simvolio-support|hy6|0.5.26
better-cpp-syntax|jef|1.15.5
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
cmake|twx|0.0.17

(5 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
We can fetch the cwd now for the terminals but only on macOS or Linux, not Windows.

**Comment by pmonajem** [comment]
> We can fetch the cwd now for the terminals but only on macOS or Linux, not Windows.

The updated title somewhat changes from the original description, although it can still be helpful. You're suggesting to check current terminal's CWD, my thought was for the file search (Ctrl P) to be more flexible about the input path, meaning it could process the b/c/d.txt path in the example

**Comment by juliombb** [comment]
I tried reproducing this in macOS but could not (it worked)
the version in which I tried was 1.60.0

**Comment by pmonajem** [comment]
> I tried reproducing this in macOS (big sur 11.2.3) but could not (it worked)
> the vscode version in which I tried was 1.60.0

To be sure, the files I'm trying to open are not part of the workspace itself. In case the file you were trying to open was added to the workspace.
