### ISSUE TITLE
Opening the dropdown menu for creating a new terminal immediately triggers the option your cursor hovers over thereafter

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#122636]
Issue Type: <b>Bug</b>

1. Click on the dropdown next to the plus icon that would add a new terminal
2. The “Select your default terminal profile” menu appears

VS Code version: Code - Insiders 1.56.0-insider (13f1afffab09548c10ddb3bc5d5db52587876ad8, 2021-04-28T04:52:56.570Z)
OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.47GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id dbbd25fe-3f4e-426a-9c89-45e060834124|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-fish|bma|1.0.21
vscode-markdownlint|Dav|0.40.4
vscode-deno|den|3.3.0
gitlens|eam|11.4.1
vscode-pull-request-github|Git|0.25.1
haskell|has|1.2.0
discord-vscode|icr|5.6.3
latex-workshop|Jam|8.17.0
language-haskell|jus|3.4.0
powershell-preview|ms-|2021.4.2
linux-desktop-file|nic|0.0.14
java|red|0.77.0
stardog-rdf-grammars|sta|0.1.2
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.0
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by schuelermine** [comment]
@vscodebot nope

**Comment by schuelermine** [comment]
Video demonstration:  
https://user-images.githubusercontent.com/48802534/116526362-d03d9b00-a8d9-11eb-8530-594f1c762650.mp4

**Comment by meganrogge** [comment]
I can't reproduce that - are you clicking really quickly after the menu opens?

**Comment by schuelermine** [comment]
No, I’m clicking continuously.

**Comment by schuelermine** [comment]
It’s also definitely not an issue with the mouse. The same thing happens with a trackpad, whether I tap or click
