### ISSUE TITLE
View: Toggle Menu Bar not in compliance with documentation

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#122633]
We have written the needed data into your clipbo
Issue Type: <b>Bug</b>

The behaviour described in https://github.com/microsoft/vscode/issues/122094 is not implemented as such. Instead of toggle it changes the "window.menuBarVisibility" to compact. This does is currently not implemented as such. The Alt key has no effect.

Btw this has only slightlty to do with https://github.com/microsoft/vscode/issues/58377 or 
Steps to Reproduce:

1.Ctrl+Shfit+P t
2.ype search for View: Toggle Menu Bar

or
1.select View / Appearence / Show Menu Bar to toggle the menu bar visibility

In conflict with the documentation: the Alt key has not effect. Either the behviour needs correction or the documentation.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.47GB free)|
|Process Argv|--crash-reporter-id e1d6a1bb-9d8f-4f44-a55c-80319d53b841|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
php-debug|fel|1.14.12
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.1
vscode-wordpress-hooks|joh|0.5.4
vscode-github|Kni|0.30.6
gitignore|mic|1.0.1
language-gettext|mro|0.2.0
mssql|ms-|1.10.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
vsliveshare|ms-|1.0.4131
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
php-docblocker|nei|2.1.0
vetur|oct|0.33.1
phpdoc-comment-vscode-plugin|rex|1.3.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.4
sass-indented|syl|1.8.16
es6-string-html|Tob|2.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
vstes516:30244333
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

ard because it was too large to send. Please paste.

**Comment by sbatten** [comment]
@theking2 the alt key focuses the application menu in both cases, we switch between the classic style and compact style in the activity bar
