### ISSUE TITLE
Unable to reopen untitled file with notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122677]
Issue Type: <b>Bug</b>

In today's Insiders I can't reopen untitled file with notebook anymore

```
Unable to open 'Untitled-1': The file working copy resource untitled:Untitled-1 does not have an associated file system provider..
```

VS Code version: Code - Insiders 1.56.0-insider (Universal) (0123d26aaa393bccf99f31f1eac07df6c9e218ce, 2021-04-29T06:21:54.461Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|32.00GB (0.33GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Do you know if the notebook uses the `untitledDocumentData` API? I think this is working copy stuff but I'm not 100% sure.
