### ISSUE TITLE
Getting Started: Images in markdown are giant

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122680]
I'm not sure it's possible right now to provide high res images for hidpi displays, so regular mac screenshots come out giant:

<img width="860" alt="Screen Shot 2021-04-29 at 11 04 58 AM" src="https://user-images.githubusercontent.com/2193314/116597705-cc5e4880-a8da-11eb-816c-08f75665b51b.png">

I tried to do this but extra attributes get stripped out.

```html
<div style="text-align:center">
<img src="./images/2-pencil-tool.png" style="width...">
</div>
```

**Comment by Tyriar** [comment]
Perhaps introducing a convention where `_x2` at the end of an the image file is rendered at half the image's size? Not sure how much control we have over the markdown component and if that idea is even possible easily.

**Comment by JacksonKearl** [comment]
We don't want to support arbitrary inline css , but we could support the `width` attribute on images. This is what github supports: https://stackoverflow.com/a/14747656

**Comment by Tyriar** [comment]
width/height should work for me, I didn't check if it works.

It would be nice to center them as well but I think I want to do this across all documents so maybe a config on the step?

**Comment by JacksonKearl** [comment]
Verified width/height work, added `centered` attribute for `img` tags.

**Comment by Tyriar** [comment]
Margin is still not correct when using `centered`:

<img width="669" alt="Screen Shot 2021-06-03 at 7 58 56 AM" src="https://user-images.githubusercontent.com/2193314/120666565-8cdacd00-c441-11eb-9753-01041bc34206.png">

Additionally when just using img the image gets stretched to 100% of the container which isn't expected:

<img width="735" alt="Screen Shot 2021-06-03 at 7 59 37 AM" src="https://user-images.githubusercontent.com/2193314/120666704-a54ae780-c441-11eb-84ea-25d6b47eabbc.png">

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/120716904-8b2dfb00-c47b-11eb-81ba-ce9b8e2b1995.png)
