### ISSUE TITLE
Terminals tabs show full process path in switcher

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122696]
Without any particular configuration of profiles, on stable:

![](https://memes.peet.io/img/21-04-77a22959-c76b-408d-bb3f-baec297aa11a.png)

On Insiders:

![](https://memes.peet.io/img/21-04-22db67b4-c9e4-4214-9951-2a0f405c337d.png)

This can be awkward in split view

**Comment by Tyriar** [comment]
Can't reproduce, do you have `terminal.integrated.experimentalUseTitleEvent` set? This is by design if so

**Comment by connor4312** [comment]
Yes, I do
