### ISSUE TITLE
Cleanup legacy recently opened code

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122623]
Just came across this code:

https://github.com/microsoft/vscode/blob/d89e8cd27ce9a7b16c00c48886ac66aa814f7a76/src/vs/platform/workspaces/common/workspaces.ts#L443-L448

Wondering whether by now we can remove the backwards compatibility and just expect our latest interfaces.

**Comment by aeschli** [comment]
This only became legacy 2 month ago. IMO we should wait at least a year.

**Comment by bpasero** [comment]
Year approaching :D

**Comment by bpasero** [comment]
🥇
