### ISSUE TITLE
Focus doesn't fully switch to VSCode if right-clicking in the file explorer tab. Enables file renaming but input still goes to the other focused window

### ISSUE THREAD

**Issue by theolouvel** [microsoft/vscode#122625]
- VS Code Version: Version: 1.55.2
- OS Version: macOs Big Sur Version 11.3

Steps to Reproduce:

1. Open VSCode
2. Open any other window
3. **Switch focus** to the other window by clicking on it
4. While focused on the other window, **right-click on any file or folder in the explorer and select "Rename"**
5. The focus *seems* to be on the file explorer and the UI enables file renaming, but if you try to type anything your input will remain on the other window, making it impossible to rename the file.

As it is not always obvious where the focus is, it leads to mistakes such as typing in the terminal, hitting enter and then realizing you didn't rename the file.

P.S.: It is not specific to this version of Big Sur as it is happening ever since I switch to a mac mini m1 in January. Not sure if this is true with versions of macOs anterior to Big Sur though.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a long standing electron issue. I know there is a duplicate however I do not know which issue it is.
If you want to find the dupliacte I suggest you search through our exisitng issues. Thanks

**Comment by theolouvel** [comment]
I thought it might be, but I couldn't find a duplicate... Thanks for the quick response anyway!
