### ISSUE TITLE
VS Code gives error using Samba Shares.

### ISSUE THREAD

**Issue by jesko42** [microsoft/vscode#122694]
Issue Type: <b>Bug</b>

On my system:

`Linux aldebaran 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I get the following error when I simply try to start VS Code within a Samba Share:

`cannot stat path of the current working directory: Permission denied`

All other tools as well as scripts have no problems here, so it's no rights problem. Starting with "sudo" makes no difference: Same error

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.8.0-50-generic snap

**Comment by bpasero** [comment]
Does it reproduce without snap, e.g. by using the zip archive: https://az764295.vo.msecnd.net/insider/6449b6b7253b5808e2278903c82da8d59a230383/code-insider-x64-1619775740.tar.gz
