### ISSUE TITLE
Markdown cell has no line numbers with Show Cell Line Number option checked

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#122606]
Testing #122254

Version: 1.56.0-insider (user setup)
Commit: 13f1afffab09548c10ddb3bc5d5db52587876ad8
Date: 2021-04-28T04:52:06.990Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I was able to get a Markdown cell into a state where the Show Cell Line Number option is checked, but when you go to edit the cell, there are no line numbers.  This doesn't happen every time, but I found it most likely to happen when:

- Check "Show Cell Line Number" on a Markdown cell not currently in edit mode - do not enter edit mode.
- Scroll a full page length down and check "Show Cell Line Number" on 1-2 cells, try to include a code cell.
- Scroll back to the first cell (which has "Show Cell Line Number" selected), and click Edit Cell through the (...) menu.

On my setup, this will enter the edit cell mode with no line numbers, despite the option being selected in the (...) menu.

![recording (12)](https://user-images.githubusercontent.com/1389808/116488243-bacb6100-a846-11eb-984c-d795d93e16be.gif)

**Comment by rebornix** [comment]
It looks like a context key service issue, which we have fixes already recently. I'm not seeing this issue again.
