### ISSUE TITLE
Should clear cell/notebook reset error state?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122645]
* open `my-endgame.github-issues`
* repeatedly run the whole notebook so that get quota errors
* press clear notebook
* there error output goes away, the error status remains

https://user-images.githubusercontent.com/1794099/116543824-a2af1c80-a8ee-11eb-8d8e-259c2b6123f2.mov

**Comment by jrieken** [comment]
Still seeing this with insiders a348d103d1256a06a2c9b3f9b406298a9fef6898

**Comment by roblourens** [comment]
Missed the "clear all" command, just did the single cell version

**Comment by rzhao271** [comment]
I still see the error states after pressing the clear all outputs button:

<img width="800" alt="Screen Shot 2021-05-05 at 8 44 17 AM" src="https://user-images.githubusercontent.com/7199958/117169833-534d6e00-ad7e-11eb-829b-8eb1850c8728.png">

Version: 1.56.0-insider
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:55:28.605Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

**Comment by roblourens** [comment]
I can't repro that @rzhao271, does it happen every time?

**Comment by roblourens** [comment]
Oops, missed the fork, it's fixed in main
