### ISSUE TITLE
[web] expose api to customize generation of machine id and label 

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#122652]
Currently in Gitpod or Codespaces it looks like:
<img width="361" alt="Screenshot 2021-04-29 at 14 47 24" src="https://user-images.githubusercontent.com/3082655/116552880-d3488380-a8f9-11eb-87ca-9ce8f8923ef7.png">

It would be nicer if the machine label reflected the origin and machine id could point to the underlying workspace, in Gitpod case we would like to remove such records if the workspace is deleted.

I'm fine to make a PR if you are open to it.

**Comment by sandy081** [comment]
Can you please elaborate your proposal?

**Comment by akosyakov** [comment]
@sandy081 yes, I meant to add following api to `vs/workbench/workbench.web.api.ts`

```ts
interface ICurrentMachineProvider {
	readonly id?: string
	readonly name?: string
}

/**
 * Settings sync options
 */
interface ISettingsSyncOptions {

	/**
	 * A provider for the current machine info.
	 */
	readonly currentMachineProvider?: ICurrentMachineProvider;
}
```

In Gitpod case we would implement it like: 
```ts
currentMachineProvider: {
    get id(): string {
	    // encode a Gitpod workspace id into a machine id to allow associate machines with workspaces
	    return info.workspaceId + ':' + generateUuid();
    },
    get name(): string {
	    // it will display something like `silver-wren-puyfsx22 (Gitpod)` as a machine label by default in Gitpod
	    return info.workspaceId + '(Gitpod)';
    }
}
```

On implementation side I thought to refactor `serviceMachineId/common/serviceMachineId.ts` into `machine/common/currentMachineService.ts` with following api:
```ts
export interface ICurrentMachineService {
	getId(): Promise<string>;
	getName(): string;
}
```

Default implementation will do the same as for now and for web workbench there will be a subclass checking  `ICurrentMachineProvider` as well.

**Comment by akosyakov** [comment]
@sandy081 Would you consider anything like that?

**Comment by akosyakov** [comment]
I think https://github.com/microsoft/vscode/issues/122457 is related, in the sense that machines should be removed if possible automatically if the remote machine does not exist anymore.

**Comment by akosyakov** [comment]
Also related to https://github.com/microsoft/vscode/issues/114640 in sense of giving more meaningful names.

**Comment by sandy081** [comment]
I think we can customize the default label but not the machineId. Because, it is coupled with client sync state. So the id has to be unique per sync instance. If you open the same remote from multiple browsers/machine you can see it labelled as `${label} ${counter}` just like when you open VS Code instance on multiple machines.

**Comment by akosyakov** [comment]
Would it be an option to allow some additional data as a part of machine record? I wonder don't you experience an issue then machine resource data growth so big that one hits max payload error?

**Comment by sandy081** [comment]
Your consent is true and it would makes sense to limit no of machines and probably show last sync timestamp of the machine so that users can remove.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/114640

`embedderIdentifier` is used to represent the machine name.
