### ISSUE TITLE
Double-click does not select $

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/vscode#12267]
- VSCode Version: 1.5.2
- OS Version: Win 10

Steps to Reproduce:

1.  Create var $name = 'VsCode'; and double click on $name. You will see that only name is hovered, but sign $ is not
2.  ctrl+c ctrl+v will copy only name without $ sign

$ is valid char for names so I think it should be copied also.

**Comment by alexandrudima** [comment]
Please configure `editor.wordSeparators` to your liking.
