### ISSUE TITLE
Inline actions on hover obscure title/selectable area

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#122692]
When the width is below a certain threshold, we shouldn't show the inline actions.

![recording - 2021-04-29T141850 874](https://user-images.githubusercontent.com/29464607/116619822-d5104800-a8f5-11eb-9b39-37636d58e9fe.gif)

**Comment by Tyriar** [comment]
Not sure I agree with this one, let's bring it up in the UX sync

**Comment by meganrogge** [comment]
maybe it could be a setting? This was a concern Kai had.

**Comment by Tyriar** [comment]
That would make us behave differently to other trees:

![image](https://user-images.githubusercontent.com/2193314/116878823-bb605080-abd4-11eb-919c-d8809ca14840.png)

I get that tabs can be smaller than them, but I think the split and kill buttons are one of the most important things on the tabs. Perhaps we could fold them into a `...` menu when it gets too small instead, that way we could avoid an extra setting? UX sync might have other ideas.

**Comment by meganrogge** [comment]
Yeah Kai also mentioned we could delay the hover so that it would be just a bit longer. The case he's concerned about is you try to click on a tab to focus the terminal and instead end up splitting or killing it when the inline actions appear -> which looks like a bug.

**Comment by Tyriar** [comment]
@joaomoreno any thoughts on this? Have you seen feedback like this for other trees/lists?

**Comment by meganrogge** [comment]
I think this is diff't from other trees bc of the limited width we're working with.

**Comment by joaomoreno** [comment]
I don't think other trees get as narrow as this one. I agree with @meganrogge, I have hit this situation and found it odd, not knowing exacly why. Her initial GIF makes it pretty clear to me.

**Comment by meganrogge** [comment]
first pass at a fix happened in f8a40e817c0e3c25fb6fe2de5afd36481ca02722
