### ISSUE TITLE
Hex editor: open untitled file as hex should turn document dirty

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122637]
Steps to Reproduce:

1. open an untitled file and make it dirty
2. pick _Hex Editor: Open Active File in Hex Editor_ (or "Reopen editor with...")

=> 🐛 the hex editor opens but not dirty, I think it should be dirty given it is untitled and has user typed contents.

![image](https://user-images.githubusercontent.com/900690/116526918-61ad0d00-a8da-11eb-8c3a-cb82ba2a24bc.png)

**Comment by bpasero** [comment]
This is arguably data loss, so I am tempted to mark "important".

**Comment by bpasero** [comment]
![recording (1)](https://user-images.githubusercontent.com/900690/116527157-ad5fb680-a8da-11eb-8e79-9a226a213ed8.gif)

Yeah I think this is pretty bad, so marking "important".

**Comment by schuelermine** [comment]
Maybe this should be reported in [microsoft/vscode-hexeditor](https://github.com/microsoft/vscode-hexeditor) instead?

**Comment by bpasero** [comment]
Yeah I wasn't sure if this is a generic problem in VSCode or specific to the extension.

**Comment by lramos15** [comment]
How do we mark files as dirty? This is using the new `untitledDocumentData` API I added last iteration to pass a byte array to the editor.

**Comment by bpasero** [comment]
> How do we mark files as dirty?

Ideally the underlying working copy of an editor indicates dirty and the associated editor input updates accordingly:

https://github.com/bpasero/vscode/blob/2f915a24b4093a0b995a79af3578ec6dbe76c3b4/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L159-L164

and

https://github.com/bpasero/vscode/blob/2f915a24b4093a0b995a79af3578ec6dbe76c3b4/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L159-L164

**Comment by lramos15** [comment]
I assume this bug exists in notebooks as well. Will investigate ensuring the input is dirty if you have this `untitledDocumentData`.

**Comment by lramos15** [comment]
``
			// If we're loading untitled file data we should ensure it's dirty
			if (untitledDocumentData) {
				input._onDidChangeDirty.fire();
			}
```
Hmm, this didn't do it.

**Comment by bpasero** [comment]
@lramos15 really the working copy should declare it is dirty, otherwise a lot of things like backups etc will not work properly. The editor input declaring dirty should be as a consequence of the underlying working copy getting marked as dirty.

**Comment by bpasero** [comment]
I can still reproduce when I open another editor:

![recording](https://user-images.githubusercontent.com/900690/117025224-04122980-acfb-11eb-965d-a7170cc19e13.gif)

**Comment by lramos15** [comment]
Moving to May milestone as the user can at least save an untitled file when it's opened in an untitled file for now.

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/376161b915803bce7795387d2baab679c3be20ad
