### ISSUE TITLE
Terminal - Can't skip shell commands that are bound to some F keys

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12264]
OSX. Add to settings -

```
"terminal.integrated.commandsToSkipShell": [
    "workbench.action.debug.run"
]
```

When I press F5, which should start debugging, it inserts `5~` into the shell. But if I bind that command to F3, then it works. Is it possible to make this work?

**Comment by Tyriar** [comment]
@roblourens weird, I actually do this and it works fine for me.

**Comment by roblourens** [comment]
I just launched with `--disable-extensions` and a user-data-dir so my settings/keybindings aren't applied.

Then created one keybinding like 
```
    {
        "key": "f5",
        "command": "workbench.action.quickOpen",
        "when": "editorTextFocus"
    }
```

Same result

**Comment by Tyriar** [comment]
`"when": "editorTextFocus"` would stop it from working in the terminal

**Comment by roblourens** [comment]
Ugh there are a couple problems...

First, I was using `workbench.action.debug.run` when I wanted `workbench.action.debug.start`. Second I didn't notice the `when` above, apologies, that just came from the 'add keybinding' snippet.
But also, a change to the `commandsToSkipShell` setting doesn't take effect until I collapse and show the terminal. Can that be fixed?

**Comment by Tyriar** [comment]
@roblourens the config change should happen immediately, are you sure it doesn't work? Works fine for me.

**Comment by roblourens** [comment]
Oh I see the problem, this throws when I set commandsToSkipShell to be an empty array, so the change isn't applied. `"TypeError: Reduce of empty array with no initial value"`

```
	public setCommandsToSkipShell(commands: string[]): void {
		this._skipTerminalKeybindings = commands.map((c) => {
			return this._keybindingService.lookupKeybindings(c);
		}).reduce((prev, curr) => {
			return prev.concat(curr);
		});
	}
```

**Comment by roblourens** [comment]
Actually, if I start vscode with that setting as an empty array, then the terminal pane is blank.
