### ISSUE TITLE
Associate .mak file extension with the Make language

### ISSUE THREAD

**Issue by rtzoeller** [microsoft/vscode#122613]
VS Code currently associates the `.mk` extension with the Make language.

`.mak` is another common file extension for files included by `Makefile`s. It's associated with Make by [GitHub Linguist](https://github.com/github/linguist/blob/32ec19c013a7f81ffaeead25e6e8f9668c7ed574/lib/linguist/languages.yml#L3282), i.e. `.mak` files are recognized by github.com, and there are a few dozen public [`settings.json` files which already define this override](https://github.com/search?p=1&q=%22%2A.mak%22%3A+%22makefile%22+filename%3Asettings.json&type=Code).

VS Code should recognize this extension automatically.

**Comment by alexr00** [comment]
@rtzoeller could you point me to some documentation about `.mak` please?

**Comment by rtzoeller** [comment]
Hi @alexr00,

I've updated the pull request description with some additional information. Notably, [`.mak` is recognized by GitHub Linguist](https://github.com/github/linguist/blob/32ec19c013a7f81ffaeead25e6e8f9668c7ed574/lib/linguist/languages.yml#L3282), which I consider to be a fairly canonical source.

I've not added any of the other file extensions recognized by GitHub Linguist for Make, as I've not seen them in use. Anecdotally, my employer has been using the `.mak` extension internally since at least 2001.

**Comment by rtzoeller** [comment]
Here are some additional examples which demonstrate inclusion of `.mak` files by `Makefile`s: https://github.com/search?q=filename%3AMakefile+include+.mak&type=code.

**Comment by alexr00** [comment]
That's good enough for me, thank you!
