### ISSUE TITLE
[simple-browser] open to left

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#122644]
I have a use case where the simple browser should open a resource which can call code CLI to open a file on a user action. The issue is that I would like to open such file to left relative to the simple browser, but currently the file is opened in the same editor group as the simple browser.

I was thinking to implement a VS Code extension which does it instead of directly relying on code CLI, but the trouble is that the view column of the simple browser is not available to outside. Would it be possible to expose such command on the simple browser like `simpleBrowser.api.openSource` which accepts a file URI or expose the simple browser state as an API object to other extensions. I can contribute it if you are open to it.

Or maybe there is a plan to introduce the second side bar and allow the simple browser to be opened there instead in the editor area? In such case the current behaviour of code CLI will work for me.

@mjbvz I would appreciate your input, maybe i am overlooking the easier way 🙏

**Comment by mjbvz** [comment]
I'm not sure I understand? Are you trying to open the simple browser in a specific column? If so, have you tried the [`simpleBrowser.api.open` command](https://github.com/microsoft/vscode/blob/2894338f38841f58179df7ec1c9d7bf38851cce1/extensions/simple-browser/src/extension.ts#L51)?

**Comment by akosyakov** [comment]
Another way around. I have the simple browser already opened and I need to open some file to left relative to the simple browser.
