### ISSUE TITLE
NotebookController only allows for one view type

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#122689]
Last week, the `NotebookController` `selector` property [was replaced](https://github.com/microsoft/vscode/issues/93265#issuecomment-824906339) with `viewType`. In the old design with `NotebookKernels`, we only had to use one kernel where we could specify multiple view types.

With the new design, it seems we are limited to one view type per controller. Put another way, we can't have a single controller support multiple view types. Is this by design? 

I am using this in the Live Share extension to create a controller for the guest to enable coediting. Could we change this to accept a string __or__ an array? This would let us use one controller that handles all view types.

cc @jrieken

**Comment by jrieken** [comment]
>  Put another way, we can't have a single controller support multiple view types.

It's not documented because I wasn't sure about it but the `*` view type means any view type.

**Comment by alyssajotice** [comment]
Thanks!
