### ISSUE TITLE
Getting started markdown links don't work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#122622]
Testing #122275

I tried using GitLens' README.md as a getting started media file, and none of the links work -- external links, nor links within the same markdown file. Command lines also didn't work.

**Comment by JacksonKearl** [comment]
Fixed external links & commands, going to say that internal links are not supported by design.... ideally the pages wont be long enough to need them, and I'd prefer to reserve that syntax for linking to other steps in the walkthrough https://github.com/microsoft/vscode/issues/122795

**Comment by JacksonKearl** [comment]
Plus I can't even find a way to handle them... `webview.onDidClickLink` does not get called for links with only a fragment (`#my-cool-section`), yet the webview also does not scroll to the specified section.

**Comment by mjbvz** [comment]
@JacksonKearl Yes for fragment only links, we try to scroll to reveal the element with that id within the webview itself. All other links should go through `onDidClickLinks`

**Comment by JacksonKearl** [comment]
I'm finding that the webview does not scroll, try for instance going to the extension editor page for the GitLens readme, the links do not work.

**Comment by mjbvz** [comment]
They work for me in the markdown preview. I think GitLens is just using a format of links that we don't support. It works on GitHub but I'm not sure it's standard

**Comment by connor4312** [comment]
Seems to work for me. Even the "labelled" links like gitlens's readme has `[test](https://example.com 'labelled')` work, although we don't seem to support that in our markdown
