### ISSUE TITLE
f2 Rename does not work if another VSCode window is open (python)

### ISSUE THREAD

**Issue by Dividedby0KSJ** [microsoft/vscode#122648]
Issue Type: <b>Bug</b>

The rename function "F2" works as intended when using only 1 window of VScode.
Opening another window of VScode using 'Ctrl + K' Then 'O' key
The new window will not be able to use the 'F2' Rename function and will say "No Result" but the first window will still work as intended even though its the same code same file

the files are python if that is any relevance

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.93GB free)|
|Process Argv|--crash-reporter-id 4933c486-05d6-4a05-9f5c-ea522c2f2875|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color-pick|ada|0.6.2
vscode-color|ans|0.4.5
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
languague-renpy|Luq|1.0.7
MagicPython|mag|1.1.0
theme-monokai-pro-vscode|mon|1.1.19
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
powershell|ms-|2021.2.2
synthwave-vscode|Rob|0.1.8
vscodeintellicode|Vis|1.2.12
gcode|vsc|0.1.3
vscode-icons|vsc|11.4.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.10.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by alexdima** [comment]
Please report directly against the Python extension.
