### ISSUE TITLE
Can't install extensions to WSL2 while connected to VPN

### ISSUE THREAD

**Issue by otanay** [microsoft/vscode#122684]
Issue Type: <b>Bug</b>

While connected to a VPN, I'm unable to install extensions to WSL: UBUNTU-20.04
After exiting VSCode and closing my VPN connection, I restarted VSCode, and was able to install extensions to WSL Ubuntu.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (18.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/var/www/redacted.test/html --remote=wsl+Ubuntu-20.04 --crash-reporter-id 4a478a42-c231-4b98-bdc2-67d43ca7afb9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|24.88GB (23.37GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.54.6
vscode-intelephense-client|bme|1.7.0
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12
markdown-shortcuts|mdi|0.12.0
php-namespace-resolver|Meh|1.1.8
format-html-in-php|rif|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30294816
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by sandy081** [comment]
Are you seeing any errors while installing?

Can you please provide following logs while installing the extension

- F1 > Set Log Level > Trace
- Help -> Toggle Developer Tools -> Console
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
 - View -> Open View… -> Log (Window)

**Comment by otanay** [comment]
Here you go.
Thanks,
Oren.

[sharedLog.txt](https://github.com/microsoft/vscode/files/6408329/sharedLog.txt)
[shared-process-1619821574128.log](https://github.com/microsoft/vscode/files/6408331/shared-process-1619821574128.log)
[rendererLog.txt](https://github.com/microsoft/vscode/files/6408332/rendererLog.txt)
[dev-tools-console-1619821460950.log](https://github.com/microsoft/vscode/files/6408333/dev-tools-console-1619821460950.log)

**Comment by sandy081** [comment]
Seems the logs does not include any info. May be these are new ones.

Can you please try to provide logs while you are reproducing the issue? 

Can you also  please include Remote Logs - View -> Open View... -> Log (Remote)
