### ISSUE TITLE
Latest update frequently "not responding; force quit"

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#122659]
- VS Code Version:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.15-200.fc33.x86_64

- OS Version: Fedora 33

Steps to Reproduce:

1. Open VS Code
2. Wait

Does this issue occur when all extensions are disabled?: I don't know.  Since it doesn't happen right away, I cannot afford to sit and wait while I cannot use VS Code due to having no extensions installed.

After working for a while, VS Code becomes unresponsive and gnome-shell starts up it's "... is not responding.  Force Quit / Wait" processing on the process.  The only real option is to force quit and restart.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by deepak1556** [comment]
Can you also check if the issue happens with latest insiders https://code.visualstudio.com/insiders/ that has a newer runtime.

**Comment by brianjmurrell** [comment]
https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues seems to be for outright crashes.  I am experiencing non-responsiveness.  How does that correlate into a crash that the aforementioned URL can assist with?

**Comment by brianjmurrell** [comment]
Can we get this issue reopened please?  It's still happening in the latest release and it's not at all clear how https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues is supposed to work in the scenario of non-responding VS Code (rather than _crashing_ outright).
