### ISSUE TITLE
Filter button in test explorer is large

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122600]
![image](https://user-images.githubusercontent.com/323878/116484985-142f9200-a83f-11eb-96dd-6830922d316e.png)

Wondering whether this is a side effect of the button hover changes, or if it was on purpose? I think it shouldn't have a background color

**Comment by connor4312** [comment]
This copies the problem view which has a background color when any filter is active

![](https://memes.peet.io/img/21-04-74166664-1fb1-4e35-b0da-850489cc8868.png)

However that button is slightly larger than the problems button

**Comment by roblourens** [comment]
I actually didn't realize a filter was active. Not sure what I did to activate it. But yeah the background is fine.
