### ISSUE TITLE
Drag and drop files into terminal strips characters like \ " '

### ISSUE THREAD

**Issue by dengyaotriangle** [microsoft/vscode#122665]
- VS Code Version: 1.55.2
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1. Select a file with some special character in its name e.g.  \ " ' 
2. Drag&Drop it into the intergrated terminal

For example, a file with the name `test " ' \ .txt` will end up like `'/Users/dengyaotriangle/Desktop/test   \\ .txt'`, which is undesirable.

P.S. In previous versions of VSCode (1.52.1), it seems to work fine. Dragging the file above will give ` /Users/dengyaotriangle/Desktop/test\ "\ '\ \\\ .txt`

I think the behavior of previous versions are correct, since a `read` command and the dragged string will yield the actual path 
```
> read a   
/Users/dengyaotriangle/Desktop/test\ "\ '\ \\\ .txt
> echo $a
/Users/dengyaotriangle/Desktop/test " ' \ .txt
```

While now, the string clearly differs from the actual path.

If it isn't a bug but an intentional change, can an option switching between these behaviors be added in the future?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This change was made intentionally in response to a security issue, we just strip all special characters to avoid running inline commands. We should be able to properly escape them if we're really careful.

**Comment by revilowaldow** [comment]
I'm regularlay getting caught by this on the `;` character.
We work with a lot of files with filenames in the format `Author; Title.json` and there's zero chance of this convention changing.
Having to manually put the semicolon back in every command is getting frustrating.
The security fix is obviously important but we shouldn't have regressed functionality as wont-fix
