### ISSUE TITLE
Can't open files in PR

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122627]
Issue Type: <b>Bug</b>

This works in other repos so I don't know what's special about this.

- Open microsoft/vscode-remote-ssh in a local window
- Create a PR (https://github.com/microsoft/vscode-remote-ssh/pull/116)
- Click a file in the PR in the sidebar view
- Get this error notification

```
Unable to open 'README.md (Pull Request)': The file working copy resource pr:/Users/roblou/code/vscode-remote-ssh/open-ssh-remote/README.md?{"baseCommit":"196d8e6fdfa49f5ddc949ec44279f13036c70f25","headCommit":"3637dcbabd3dd5318aa874a732bcd06300515007","isBase":false,"fileName":"open-ssh-remote/README.md","prNumber":116,"status":3,"remoteName":"origin"} does not have an associated file system provider..
```

Extension version: 2021.4.37984
VS Code version: Code - Insiders 1.56.0-insider (19cda32aafccb88db45622e7ae9be90cb71c9744, 2021-04-27T17:44:21.786Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 5.4.0-1043-azure
Remote OS version: Linux x64 5.4.0-1043-azure
Fetching remote diagnostics for 'Codespaces' failed: Canceled
Fetching remote diagnostics for 'Codespaces' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id a2c1d522-e9f0-4e3f-b78a-9253f1c2d2d3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: robfast-vnc|
|OS|Linux x64 5.4.0-1043-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|Memory (System)|15.64GB (3.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: robfast-vnc|
|OS|Linux x64 5.4.0-1043-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|Memory (System)|15.64GB (3.13GB free)|
|VM|0%|

Fetching remote diagnostics for 'Codespaces' failed: Canceled

Fetching remote diagnostics for 'Codespaces' failed: Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2ct:30286873
vscorehov:30294388

```

</details>

**Comment by jrieken** [comment]
@lramos15 In my editor and diff-editor handler I need to check if the scheme of the given resource is supported by our file systems, so essentially have

```ts
if (!this._fileService.canHandleResource(resource)) {
    return undefined;
}
```

However, you don't allow we return undefined or anything that says "I actually don't handle this resource, it only looked like it at first"
