### ISSUE TITLE
Shared node terminal

### ISSUE THREAD

**Issue by TeunSpithoven** [microsoft/vscode#122654]
Issue Type: <b>Bug</b>

Go in a live share node.js project
Ask terminal write actions
When you type,  each character you enter will create a new line in de terminal, so you can't really see what you are typing.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.59GB free)|
|Process Argv|-n C:\\Users\\teun spithoven\\AppData\\Local\\Temp\\vsliveshare\\tmp-C432083C15FA6417E4ED49DDD53DDFED8FC6\\Visual Studio Live Share.code-workspace --crash-reporter-id 041973d3-604a-49c4-a09b-946a2d8f6598|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
vscode-pull-request-github|Git|0.25.1
rest-client|hum|0.24.5
dotenv|mik|1.0.1
csharp|ms-|1.23.11
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4131
debugger-for-chrome|msj|4.12.12
laravel-blade|one|1.25.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.6.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.18.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.0
quokka-vscode|Wal|1.0.361

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
