### ISSUE TITLE
serious display issue

### ISSUE THREAD

**Issue by hmxulex** [microsoft/vscode#122604]
I just installed VS code 1.55.1 on 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian

It has serious display problem, display is all messed

**Comment by alexdima** [comment]
@hmxulex Could you please add a screenshot? Does the problem reproduce when launching with `--disable-gpu` ?

**Comment by hmxulex** [comment]
Hi I started vscode with "code ."



    On Thursday, April 29, 2021, 02:56:00 AM EDT, Alexandru Dima ***@***.***> wrote:  
 
 


@hmxulex Could you please add a screenshot? Does the problem reproduce when launching with --disable-gpu ?

**Comment by hmxulex** [comment]
I have a recording file now, how can I attach the file?

**Comment by hmxulex** [comment]
![recording (6)](https://user-images.githubusercontent.com/43009311/116558276-41c31c80-a8cd-11eb-9afc-c12ba60829c9.gif)

**Comment by bpasero** [comment]
Looks like an electron issue to me.

Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/118658

You can use `"window.titleBarStyle": "custom"` as a temporary workaround. Issue is related to chromium rendering in VNC.

You can also use vscode remote development suite https://code.visualstudio.com/docs/remote/remote-overview#_getting-started for better experience.

**Comment by hmxulex** [comment]
setting --disable-gpu didn't help, I will try  "window.titleBarStyle": "custom"

**Comment by hmxulex** [comment]
window.titleBarStyle seems fixing the titleBar issue
however the display of content windows is still mess

Also, one of my colleagues runs VScode version 1.47 with same VNC, it looks fine I still think it's an issue in VScode.
