### ISSUE TITLE
Image preview labeled as (read-only)

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122605]
Issue Type: <b>Bug</b>

**Repro**
1. Open image in default image preview
1. Click away to another tab

**Bug**
The image tab gets the `(read-only)` label:

![Screen Shot 2021-04-28 at 5 16 32 PM](https://user-images.githubusercontent.com/12821956/116487760-8c995180-a845-11eb-92da-5ab0fbcc1952.png)

This should never happen since the image preview doesn't support editing

VS Code version: Code - OSS Dev 1.56.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
docs-view|bie|0.0.9
vscode-eslint|dba|2.1.20
typescript-notebook|don|1.2.0
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.25.1
latex-workshop|Jam|8.17.0
svg|joc|1.4.5
template-string-converter|meg|0.4.7
git-graph|mhu|1.30.0
vscode-language-pack-de|MS-|1.55.2
vscode-dotnet-runtime|ms-|1.0.0
vscode-edge-devtools|ms-|1.1.7
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.770905982
remote-containers|ms-|0.170.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
azure-account|ms-|0.9.8
cpptools|ms-|1.3.1
hexeditor|ms-|1.5.0
vscode-github-issue-notebooks|ms-|0.0.82
vscode-markdown-notebook|ms-|0.0.18
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
shader-toy|ste|0.10.15

</details>

**Comment by mjbvz** [comment]
@loganrosen This bug was not related to your work but labelling editors `(read-only)` would be something nice to try to moveing out out custom editors and into the new shared editor logic you have been working on

**Comment by loganrosen** [comment]
I think you meant to tag @lramos15. 🙂

**Comment by lramos15** [comment]
@mjbvz Is the marking as read only something determined on opening? As I believe the intent @bpasero and I had was for this shared service to be more of a central `EditorInputResolverService` in the end and not handle things like move etc.

**Comment by mjbvz** [comment]
@lramos15  It's something that's done on each editor input class right now, but I think this code is duplicate between custom editors and file editors (and notebooks may end up copying the code too). I wouldn't put it into the new editor service but for the future you can be thinking about if there's a way to remove this duplication

**Comment by bpasero** [comment]
Besides "readonly" there is also orphaned code duplicated across editor inputs: https://github.com/microsoft/vscode/commit/f3f4eebecbd47df5012d773fcfcadc4e65fbe79b

Would be good to consolidate maybe in a single reusable editor input. I guess the challenge is that all these editors might have different models where they get this info from.

**Comment by lramos15** [comment]
@bpasero Would looking into working copy adoption some more help with this or are we looking for a central class that contributed editors could inherit from for example

**Comment by bpasero** [comment]
Yeah, maybe through working copies, but we still have no shared editor input for this. And currently readonly / orphaned state is only something file based working copies have, but not all of the custom editors may be file based in the end.
