### ISSUE TITLE
Update path lib to match latest node.js variant

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122669]
A reminder that we should check whether any changes landed in path library of node.js that we should copy into our version given we will update to Electron 12 now.

Theirs: https://github.com/nodejs/node/blob/v14.16.0/lib/path.js
Ours: https://github.com/nodejs/node/blob/v12.8.1/lib/path.js

//cc @deepak1556

**Comment by sbatten** [comment]
changes were mostly var => let which we already had for our TS version. no notable changes, but adopted the couple added parentheses to keep us in sync.
