### ISSUE TITLE
vscode.Uri.parse handles escaped plus sign "%2B" as unescaped.

### ISSUE THREAD

**Issue by felixhao28** [microsoft/vscode#122631]
- VS Code Version: 1.56.0-insider
- OS Version: Windows 10 Build 21364

Steps to Reproduce:

```typescript
import * as vscode from "vscode";
const aa = vscode.Uri.parse("https://www.example.com?a=1+2");
const bb = vscode.Uri.parse("https://www.example.com?a=1%2B2");
// however this prints true
console.log(aa.toString() === bb.toString());
// this opens https://www.example.com?a=1+2, and + is treated as space in the browser.
vscode.commands.executeCommand("vscode.open", bb);
```

1. Use the above code in a VSCode extension project.
2. Notice `vscode.Uri.parse` parses "%2B" into "+".

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This unfortunately cannot be fixed any more: An explainer can be found here: https://github.com/microsoft/vscode/issues/83645#issue-514539421

**Comment by felixhao28** [comment]
If this is not to be fixed any time soon. It may be worth mentioning in vscode.Uri.parse's doc, right here:

![image](https://user-images.githubusercontent.com/2417391/116641967-650acc00-a9a0-11eb-879f-d1221396febb.png)
