### ISSUE TITLE
Getting started titles are off-center

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#122741]
![image](https://user-images.githubusercontent.com/35271042/116725032-456ea600-a996-11eb-9c20-43e44bc5aa4d.png)

The title appears to not be centered here

**Comment by misolori** [comment]
@JacksonKearl Yes!

**Comment by rzhao271** [comment]
It seems the icons are now too low:

<img src="https://user-images.githubusercontent.com/7199958/120556718-be0bbc80-c3b1-11eb-81cc-8f4cb027fec4.PNG" alt="screenshot showing the icons for the getting started titles are now too low" width=600px>
