### ISSUE TITLE
Snippets with Auto Import

### ISSUE THREAD

**Issue by YaduAhuja** [microsoft/vscode#122790]
Hi, I suggest a feature where we can specify the Import packages for snippets like the functionality present in eclipse.

See it in Action : 

https://user-images.githubusercontent.com/66440500/116784732-74c70500-aab3-11eb-8e46-8b8b1ffabadc.mp4

And the Template (Snippet Code) used in Eclipse is :

![Screenshot (56)](https://user-images.githubusercontent.com/66440500/116784867-236b4580-aab4-11eb-93ce-719c16f35c48.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"
