### ISSUE TITLE
Run button disappears in github issue notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#122701]
Issue Type: <b>Bug</b>

I don't have steps for reproduce, any hint for how to troubleshoot next time would be helpful. As shown below, the controller/kernel status bar item it there, but there is no run button, ctrl+enter will also not run

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/116634345-9cca3300-a910-11eb-8915-6ac77f9ee1cb.png">

VS Code version: Code - Insiders 1.56.0-insider (Universal) (b2d6cab998570dce35a80b0597758932cbfa7477, 2021-04-29T14:46:46.522Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
The Run All button disappears too.

I use RemoteHub to open `https://github.com/microsoft/vscode/blob/main/.vscode/notebooks/endgame.github-issues` and execute Run All immediately after the workspace is opened.

**Comment by jrieken** [comment]
@roblourens and I have seen this issue as well. This is when the context keys aren't proper, e.g the context says there is 0 kernels and then there are no buttons (despite having a kernel). This recovers when switching editors but I don't know how we get into this...

**Comment by roblourens** [comment]
If you see this you could use the "inspect context keys" to check which one is wrong

**Comment by rebornix** [comment]
```
notebookCellEditable: true
notebookCellEditorFocused: true
notebookCellExecutionState: "succeeded"
notebookCellFocused: true
notebookCellHasOutputs: false
notebookCellInputIsCollapsed: false
notebookCellLineNumbers: "inherit"
notebookCellListFocused: true
notebookCellMarkdownEditMode: false
notebookCellOutputIsCollapsed: false
notebookCellType: "code"
notebookEditable: true
notebookEditorCursorAtBoundary: "none"
notebookEditorFocused: true
notebookFindWidgetFocused: false
notebookHasRunningCell: false
notebookHistoryView.active: true
notebookHistoryView.canMove: true
notebookHistoryView.defaultViewLocation: false
notebookHistoryView.visible: true
notebookInterruptibleKernel: false
notebookKernelCount: 0
notebookOutputFocused: false
notebookViewType: "jupyter-notebook"
```

@roblourens `notebookKernelCount` is zero.

**Comment by DonJayamanne** [comment]
Similar issue here https://github.com/microsoft/vscode/issues/122876

**Comment by jrieken** [comment]
So, I do have steps that reproduce this (unsure if these are the only steps to reproduce...). Quite simple:

* open a text file 
* open a notebook
* drag the notebook to the side so that it gets its own column
* :bug: no run buttons...

**Comment by jrieken** [comment]
@roblourens adding you because I know that you are doing something when notebook editors moves. Unsure if that is the culprit or if `NotebookEditorContextKeys` is wrong. When the move happens, from with `NotebookEditorContextKeys` I cannot observe anything, no dispose nor re-create

**Comment by roblourens** [comment]
I can repro with those steps, I will look at it

**Comment by roblourens** [comment]
Got it, we wrote those keys to the wrong CKS
