### ISSUE TITLE
Intermittent render-glitch for certain Unicode on Terminal

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#122776]
Issue Type: <b>Bug</b>

Sometimes certain Unicode characters fail to render correctly in the terminal.

See screenshot.

🔸 and 🐠 are rendering.
But ⚠️ isn't.

Usually it does, but occasionally not.
Restarting the terminal (or VSCode) fixes.

I notice ⚠️ won't render in-editor (but 🔸 and 🐠  do). Maybe it's related...?

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 208511c2-dba0-4576-b4d0-606dd0e49428|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.2.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
php-debug|fel|1.14.12
go|gol|0.24.2
lldb-vscode|lan|0.2.3
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.2
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
cmake-tools|ms-|1.7.1
cpptools|ms-|1.3.1
terraform-advanced-syntax-highlighting|pjm|1.4.0
java|red|0.79.0
vscode-yaml|red|0.18.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.2
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
debug|web|0.25.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by p-i-** [comment]
![Screenshot 2021-05-01 at 11 49 02](https://user-images.githubusercontent.com/693495/116771175-956f6a80-aa73-11eb-8a30-0d298de4757a.png)

**Comment by IllusionMH** [comment]
May be related to #32840
