### ISSUE TITLE
Getting started markdown view is a little too tall

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122799]
There's an extra 20px or so on the bottom, see the scrollbar

![image](https://user-images.githubusercontent.com/2193314/116794518-5268c380-aa82-11eb-8588-faf6932f5352.png)

**Comment by JacksonKearl** [comment]
Unable to reproduce this... tried mac and windows
![image](https://user-images.githubusercontent.com/8586769/117373025-61cf7e80-ae7f-11eb-8bc5-2c9c4ff14bf1.png)

**Comment by Tyriar** [comment]
@JacksonKearl the large amount of padding on the bottom actually is the repro, pretty minor though.

**Comment by JacksonKearl** [comment]
Oh I thought the scrollbar wasn't taking full height.

**Comment by JacksonKearl** [comment]
Made it a bit tighter on the bottom, I think this is reasonable:
![image](https://user-images.githubusercontent.com/8586769/117377432-1ec5d900-ae88-11eb-9951-50ff6dab3908.png)
![image](https://user-images.githubusercontent.com/8586769/117377468-300ee580-ae88-11eb-8f36-08f951768325.png)
