### ISSUE TITLE
Command link doesn't work in settings description hover

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#122761]
1. Create setting description with command links in extension

```js
"extension.someSetting": {
	"type": "boolean",
	"markdownDescription": "[Terminal](command:terminal.focus)",
	"default": false
},
```

2. It works in Settings GUI, but not inside the hover of `settings.json` file.

**Comment by aeschli** [comment]
Command links in hover can only be permitted if the hover content is trusted.
However, JSON hovers are generated from schemas that can come from anywhere. 

That means we don't want don't want to implement that.

**Comment by usernamehw** [comment]
What's the difference between trusting it in Settings GUI #71295 and the exact same description in hover of `settings.json`?

**Comment by aeschli** [comment]
The Settings UI is limited to settings descriptions which can be trusted as you trust all extensions that you have installed.

The settings JSON editor is just a normal JSON editor driven by the JSON language server. The server provides language features based on the schema associations it gets and (currently) doesn't really know from what sources these come.
