### ISSUE TITLE
Custom Editors cannot be opened from CLI

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#122700]
It appears that the caching doesn't work for custom editors, but works for notebooks. 

1. Install luna paint
2. Open a png file in VS Code to ensure that the cache is fresh
3.  Run `code-insiders <YOUR_PNG>.png`. 
4. 🐛 It opens as the binary text editor and not as a custom editor

**Comment by lramos15** [comment]
@bpasero If you wouldn't mind can you take a look at the commit as it seems to be a sort of work around to get the service to register on start.

**Comment by bpasero** [comment]
Ugly, but if no-one depends on the custom editor service on startup, it will indeed not get instantiated until needed. 

What code specifically is needed to run on startup to make this work? Maybe only that code could be extracted into a workbench contrib?

**Comment by lramos15** [comment]
We need the code regarding extensions registering themselves, but the service uses this for movement. I could attempt to split the service in half but that also seemed  ugly. If you feel that would be a better way to do it though I can work on that.

**Comment by bpasero** [comment]
I don't have strong feelings, I am also not really an author of `contrib/customEditors` so I defer to your style.
