### ISSUE TITLE
Getting Started: Allow linking to other steps

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122795]
I think it would be cool to be able to link to other steps, for example if I had a step explaining the "crop tool" which references the selection tool, it could link directly to that page. Using the step ID would make sense here.

```markdown
The _crop tool_ (<kbd>c</kbd>) acts similarly to the [selection tool](#luna.selectionTool), but it will crop as soon as the selection is made.
```

**Comment by JacksonKearl** [comment]
In md: `[Select Step](command:walkthroughs.selectStep?%22md-to-html.convertToHTML%22)`

**Comment by Tyriar** [comment]
@JacksonKearl this would be a little nicer if we didn't need the %22

**Comment by JacksonKearl** [comment]
Yeah.. unfortunately that's just how command URI's work.
