### ISSUE TITLE
Source files in settings.json

### ISSUE THREAD

**Issue by JoshTRN** [microsoft/vscode#122779]
I would like to be able to put a bunch of settings in multiple files and then source those files in my `settings.json`

For example, let's say I have a bunch of editor settings, but then I also have color custommizations as well as certain extension settings.

What I'd like is something like an editor-settings.json and a token-colors.json file that I can include in my main settings.json file with something like

```json
{
    "source": [
       "./editor-settings.json",
       "./token-colors.json"
     ]
}
```

**Comment by IllusionMH** [comment]
Looks like #15909

**Comment by roblourens** [comment]
Thanks @IllusionMH
