### ISSUE TITLE
Ability to specify breakpoints in json file ...

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode#122756]
I realized that a previous request to support import/export of breakpoints was closed: https://github.com/Microsoft/vscode/issues/14314

Then I would recommend an even more generic feature: if the breakpoints are specified in a user-transparent json file (or something similar humans can edit), then we can export/import ourselves.

Please consider, it is very tedious to reestablish long lists of break-points with conditions.

Thanks.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by jasonadu** [comment]
> I realized that a previous request to support import/export of breakpoints was closed: #14314
> 
> Then I would recommend an even more generic feature: if the breakpoints are specified in a user-transparent json file (or something similar humans can edit), then we can export/import ourselves.
> 
> Please consider, it is very tedious to reestablish long lists of break-points with conditions.
> 
> Thanks.

Hi
I found one extension BreakpointIO that enables import/export breakpoints.
You can find its source code from github. Wish that will helps. 
By the way, the breakpoint in java class from jar isn't supported very well.
