### ISSUE TITLE
launch.json: outfiles broken for typescript if it contains more than one entry

### ISSUE THREAD

**Issue by stevenkramer** [microsoft/vscode#122724]
Issue Type: <b>Bug</b>

I'm debugging a simple typescript project, after upgrading to 1.55.2 from a version about a year old, the debugger couldn't find the transpiled files any longer. After some trying, I got this working again by reducing the number of entries to one catch all globbed entry.

The problem manifests even if I have only the functioning wildcarded entry and duplicate it.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.24.0
vscode-edit-csv|jan|0.5.8
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
debugger-for-chrome|msj|4.12.12
steven-xcode-keybindings|ste|1.9.0

</details>

**Comment by stevenkramer** [comment]
Seems to have been reported here: https://github.com/microsoft/vscode/issues/105626

**Comment by isidorn** [comment]
Ok, then closing as a duplicate

**Comment by stevenkramer** [comment]
@isidorn that issue is "waiting for information" and inactive for months though.

**Comment by isidorn** [comment]
fyi @connor4312 in case he wants to investigate
