### ISSUE TITLE
Ability to auto detect encoding when opening a file which is not encoded in UTF-8

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#12275]
- VSCode Version: 1.5.2
- OS Version: Windows 10 1607 64bit

Steps to Reproduce:

1. Open a file which is not encoded in UTF-8(etc, contains Chinese characters, encoded in GBK)
2. the Chinese characters are not displayed correctly.
3. Reopen with encoding, and choose Chinese(GBK), the Chinese characters are displayed correctly.

I hope VSCode can auto detect the file encoding when opening, and open with the correct encoding, not need to reopen with correct encoding manually.

Thank you.

**Comment by chrmarti** [comment]
Tracked as #5388
