### ISSUE TITLE
regex does not work in 0.10.3

### ISSUE THREAD

**Issue by karlti** [Microsoft/vscode#1227]
strange, as I read that this should be fixed, but...
when I CTRK+F or CTRL+H to find resp. replace escape sequences like '\n', '\r\n' or '\t' it does not work...
Search box gets red border and nothing happens...

please can you help.
Thank you.

/*Karl

**Comment by Tyriar** [comment]
`\t` should work in 0.10.3. Finding multi-line strings is captured in https://github.com/Microsoft/vscode/issues/313

**Comment by egamma** [comment]
@karlti can you provide a test case please.

>strange, as I read that this should be fixed, but...
To which issue are you referring to? If an issue is marked as fixed then please also check the milestone of the issue. This indicates when a fix will be published.

**Comment by karlti** [comment]
I was referring to #312. 
Maybe I misinterpreted that issue...

btw, the problem is that escape sequences are not recognized either in the pattern to be matched (Test Case 1) as well as in the "replace with" textbox... In the second case (like '\n' in the "replace with" textbox) the matched character sequence gets replaced by the *literal* escape sequence like \n (Test Case 2).

Test case 1:

- Open VSCode
- Open File that definitely contains '\n' or '\r' '\n' characters.
- Press CTRL+H.
- Activate RegEx search.
- type into the "pattern to match" textbox: "\n" (without quotes)
- in the "replace with" textbox, type any char sequence you like...
- click the "Replace All" button.

Expected Result:
All newline chars are replaced with the char sequence

Actual Result:
No pattern match, no replace action taken.
Border of "pattern to match" textbox gets red.

--------------------------------------------------------------------

Test case 2:

- Open VSCode
- Open File that definitely contains '\n' or '\r' '\n' characters.
- Press CTRL+H.
- Activate RegEx search.
- type into the "pattern to match" textbox a char seq that can be matched.
- in the "replace with" textbox, type an escaped char sequence like '\r\n' (without quotes)...
- click the "Replace All" button.

Expected Result:
All char sequence matches are replaced by a CRLF

Actual Result:
All matched char sequences are replaced by the literal replace pattern (i.e. \r\n)

This issue occurs in UTF-8 and also in ASCII type encoding like (DOS CP437).

**Comment by egamma** [comment]
>I was referring to #312. 

The milestone of the issue shows that this issue will be included in the December update.

I'll mention in #312 that your test case should be used for verifying this bug and I'm closing this one.
