### ISSUE TITLE
Editors no longer have ids

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#122755]
VS Code Version: 1.56.0-insider
OS: Windows_NT x64 10.0.19042

Live Share had previously relied on `vscode.TextEditor#id` to differentiate editors during coediting. However, `(<any>editor).id` is currently always returning `undefined`. This gives us no way to track text editors as they move across view columns. Is there some way we can identify these editors?

cc @daytonellwanger

**Comment by jrieken** [comment]
An editor is always bound to a notebook (document), also edits happen on a notebook, so I am not sure why you need to know individual editors

**Comment by alyssajotice** [comment]
This comment was in regards to vscode.TextEditors as well as vscode.NotebookEditors. Is there some internal identification property we can use for them?

**Comment by svdo** [comment]
@jrieken Just to clarify, not sure if needed: there is an editor action ("follow participant of live share session") that should only apply to that single pane. For example, when using multiple panes in split view, the "follow" function should be enabled only in the pane where the action button is clicked.

**Comment by jrieken** [comment]
> This comment was in regards to vscode.TextEditors as well as vscode.NotebookEditors. Is there some internal identification property we can use for them?

I see, we did get more strict and we checks that ensure that we don't have such accidental APIs, e.g only what's declared in the API file (vscode.d.ts) should be available at runtime. 

To your question: the object identify itself should be sufficient in both editors. So, with some WeakMap trickery you should be able create your own identifiers

**Comment by alyssajotice** [comment]
Thanks @jrieken!
