### ISSUE TITLE
Quick-button

### ISSUE THREAD

**Issue by MasterGaeX** [microsoft/vscode#122745]
I'd like to see a quick-button folder opener. I mean, it would be much faster if when right-clicking in a folder, a VSCode button appears in the menu, and then, you can click it to quick open that folder in VSCode.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you clarify your request where you'd expect this context menu to appear? Screenshot will be helpful.

On Windows (System or User installation) it provides "Open with Code" context menu in Windows Explorer and supports jump list on taskbar with recent and pinned folders.

I guess it has something similar in other OSes.

**Comment by MasterGaeX** [comment]
> /needsMoreInfo
> 
> Could you clarify your request where you'd expect this context menu to appear? Screenshot will be helpful.
> 
> On Windows (System or User installation) it provides "Open with Code" context menu in Windows Explorer and supports jump list on taskbar with recent and pinned folders.
> 
> I guess it has something similar in other OSes.
![Cattura](https://user-images.githubusercontent.com/81831281/116747169-cc0a9e00-a9fd-11eb-9411-8522a184dddd.PNG)

This is what I meant, right-click in a folder and, in that menu, a button to open VSCode, just like GIT e WizTree.

**Comment by IllusionMH** [comment]
It should be there
![image](https://user-images.githubusercontent.com/1312662/116747814-26f4c300-aa07-11eb-82f9-ed93dc0aae25.png)

How did you install VS Code? 

Checkout 
https://stackoverflow.com/questions/49094563/visual-studio-code-in-explorers-context-menu#comment114385185_49109705
and
https://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/

Looks like running fresh installation again should show step where you need to enable this menu items

**Comment by MasterGaeX** [comment]
You were right.
