### ISSUE TITLE
Collapsed markdown header doesn't expand when creating cell under it if cell is not active

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122710]
Related to https://github.com/microsoft/vscode/issues/120641

https://user-images.githubusercontent.com/323878/116648313-91d3ca80-a931-11eb-82be-c14d42a0f809.mp4

When I create a cell in an editor that isn't the active group, the markdown header parent is only expanded in the active group, not the one I clicked in.

**Comment by rebornix** [comment]
It's a mix of two features:

* click on insert toolbar will not steal focus
* changes to no focused editor will not trigger relayout if possible (in this case, the left side editor only gets a model change, so no folding/collapse change

**Comment by rebornix** [comment]
The right behavior will be:

* Clicking on the insert toolbar will focus the editor containing that toolbar
* New cell inserted in the editor and folding region expaned
* The other editor will not update
