### ISSUE TITLE
SSH Remote - 2 Windows - Wrong Git management

### ISSUE THREAD

**Issue by vivi5421** [microsoft/vscode#122716]
Issue Type: <b>Bug</b>

Hi,

I have 2 remote windows (SSH-Remote) targetting the same remote host.
First one is opened on a Git repository folder.
Second one is opened on anothe folder (no Git repository).

I can see in Source control panel the content of the first windows in the second one.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 4.12.14-122.63-default
Remote OS version: Linux x64 4.12.14-122.63-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 1212)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.52GB (0.39GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id c0ea9093-32ce-442c-b14b-6b5f42dbe7cc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: XXX|
|OS|Linux x64 4.12.14-122.63-default|
|CPUs|Intel(R) Xeon(R) CPU E5-4627 v4 @ 2.60GHz (12 x 2593)|
|Memory (System)|23.52GB (3.21GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: XXX|
|OS|Linux x64 4.12.14-122.63-default|
|CPUs|Intel(R) Xeon(R) CPU E5-4627 v4 @ 2.60GHz (12 x 2593)|
|Memory (System)|23.52GB (3.21GB free)|
|VM|100%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
private-extension-manager-remote-helper|gar|1.4.0
drools|jim|1.2.0
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
python-template-snippets|Ric|1.2.0
scala|sca|0.5.3
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.3
jupyter|ms-|2021.5.745244803
java|red|0.78.0
sonarlint-vscode|Son|1.21.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.0
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
I think as soon as a single file is opened from a git repository, we show the git repository. So if in the second window (without a git repository) you every opened a file from the other folder, then the repository would appear.

**Comment by vivi5421** [comment]
Even if no file opened in the second window, I can still see the Git Repository from the 1st window (When I say window, it is not tab, it is a new VSCode window).

**Comment by alexdima** [comment]
@vivi5421 I have just tried and I cannot reproduce:

Here I have two folders with the following layout:
* C:\source\folder1 (has no .git folder in it, it is not a git repo)
* C:\source\folder2 (has a .git folder in it, it is a git repo)

The SCM viewlet does not show a git repository for folder1 (on the left):

![image](https://user-images.githubusercontent.com/5047891/116671635-730d1c80-a9a1-11eb-8767-ecc1ef42824a.png)

**Comment by vivi5421** [comment]
Hi,

I did further investigation and I guess behavior is expected in the end.
Even if not opening a file, the simple fact of having a git repository somewhere into the folder I've opened makes it available in the sourceControl view.

Sorry for inconvenience.
