### ISSUE TITLE
[Loc] In CHS, The incorrect text for "置"

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#122705]
VS Code Version: VSCode 1.55.2
OS Version: Linux ARM64

Steps to Reproduce:
1. Install Simplified Chinese language package.
2. Navigate to the "Settings" at the bottom.
3. Observe the "置" in the settings.

Expected:
![issue14 expect](https://user-images.githubusercontent.com/78774400/116640174-db0d3400-a99c-11eb-9508-0abb2597c5f8.PNG)

Actual:
![issue14 actual](https://user-images.githubusercontent.com/78774400/116640195-e5c7c900-a99c-11eb-9e8f-755225f36309.png)

**Comment by v-mholloway** [comment]
@v-ericawu can you fill out this template so we can target the correct strings ?...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by v-ericawu** [comment]
@v-mholloway 
Culture: Chinese
String Identifier: We don't know
English String: Set
Current Translation: 
![image](https://user-images.githubusercontent.com/78774400/135069620-e5a3d7d6-9efd-4f6e-952f-f62c2e67f105.png)
Requested Translation: **置**
Screen Shot: 
![image](https://user-images.githubusercontent.com/78774400/135069608-615ae702-982d-423f-b56a-e6df24d63c02.png)

**Comment by v-mholloway** [comment]
@v-ericawu it appears as if our translation libraries already have your requested translation...
![image](https://user-images.githubusercontent.com/77055370/135073681-d062c9ee-defc-4e65-869e-01701b5bbc96.png)

can send the current translation (typed out, not as a screen shot) so I can search further?

**Comment by v-mholloway** [comment]
@v-ericawu note that in the latest language pack, this is what I'm seeing which I believe is the translation you wanted...?
![image](https://user-images.githubusercontent.com/77055370/135097256-6cbea4e3-fda3-4284-8bb4-7596f2a38c7b.png)

**Comment by danyeh** [comment]
I think this is by design as the char code point is right. It just render by the UI font in that way.
