### ISSUE TITLE
Getting Started: Step description should be optional

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122792]
Setting description to "" gives the following which looks OK when the step doesn't need a description since it's in the markdown already, this property should be optional imo.

![image](https://user-images.githubusercontent.com/2193314/116788238-6221e100-aa5d-11eb-84de-7a87848033a8.png)

**Comment by JacksonKearl** [comment]
Makes sense. Question, when (if ever) would you want to see these steps checked off? To me it would make sense to check them off on-select.

**Comment by Tyriar** [comment]
Yes on select makes the most sense for my case

**Comment by JacksonKearl** [comment]
Added to https://github.com/microsoft/vscode/issues/122570
