### ISSUE TITLE
Leaving a Live Share causes notebooks to render as plaintext

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122770]
I had this happen once and haven't been able to get Live Share notebooks working again to repro, but basic steps were:

1. Open github issues notebook in main vscode instance
1. Start liveshare session
1. Join from child instance (new window on same machine)
1. In child instance, get a notification saying that multiple editors want to be default, I forget what I clicked here but I saw #122766. 
  ![image](https://user-images.githubusercontent.com/8586769/116760466-d3b04f80-a9c9-11eb-99c0-17e800a40be7.png)
1. Leave in chid instance.
2. Try to open a github issues notebook agian (maybe after reload?), see plain text. 

My guess is that the default got set to "Live Share - Github Issues Notebook" when I joined from Live Share (🐛?), then when I was done with the session that provider was no longer available and it fell back to plain text instead of normal GitHub issues notebook?

**Comment by lramos15** [comment]
This is a tough one as I'm not sure what we should do. If you set your setting to something and it isn't a valid viewtype we always do a text fallback. I'm wondering if we should instead do a highest priority available editor fallback. /cc @rebornix as I believe this is the most common case.

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/3d221ca349937735daf756253042c5d90e228ef7

**Comment by JacksonKearl** [comment]
Unable to open live share with notebooks , will verify next iteration once https://github.com/microsoft/vscode/issues/117936#issuecomment-854229992 is resolved.
