### ISSUE TITLE
VSCODE Overrides my keymapping

### ISSUE THREAD

**Issue by MrLsts** [microsoft/vscode#122737]
Issue Type: <b>Bug</b>

As described in 
[this superuser issue](https://superuser.com/questions/1637527/how-to-make-vscode-accept-my-keymapping)
I had to swap the key mapping of Shift_R and Up_arrow in my Lenovo ideapad keyboard to make it suitable to touch typing. Idid this by editing /usr/share/X11/xkb/symbols/pc, and making.

key <RTSH> {    [ Up            ]   };
key   <UP> {    [ Shift_R       ]   };

Problem: VSCode alone consistently interprets my pressing of the UpArrow key as Shift+Up instead of Shift. This happens both in VSCode's normal edit and  Vim mode edit. Everything else works as I intended in every other application, only VSCode selects text AND moves the cursor up every time I summon the shift modifier by pressing the UP key.

I have tried other methods of remapping the keys, such as xmodmap and /usr/share/X11/xkb/keycodes/evdev. The effects are the same. I have tried using the keyboard with its odd original layout never pressing the right-shift key, but it kills my typing.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 4.15.0-142-lowlatency snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|7.64GB (0.19GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 86f0c119-614f-40cb-87c3-c645df6655e3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
svg|joc|1.4.5
vscodevimacademy|kai|1.0.18
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
pdf|tom|1.1.0
learn-vim|vin|0.0.27

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by alexdima** [comment]
Have you seen https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

> 
![image](https://user-images.githubusercontent.com/5047891/116828159-3dcd1e00-ab9d-11eb-9662-92ebece36593.png)

**Comment by MrLsts** [comment]
Clarifying what I said in the original question: I edited the following lines in `/usr/share/X11/xkb/symbols/pc`:
`key <RTSH> {    [   Shift_R     ]   };
key   <UP> {    [ Up       ]   };
`
were, respectively changed to
`key <RTSH> {    [ Up            ]   };
key   <UP> {    [ Shift_R       ]   };
`
changing `"keyboard.dipatch": "KeyCode"` in VSCode's Preferences>Settings fixed the whole thing. Now I have a keyboard that feels right even in vscode.
Thank you alexdima!
