### ISSUE TITLE
[Loc] In CHS, "格式化文档的方式..." the name and location of the shortcut option is incorrect 

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#122706]
VS Code Version: VSCode 1.55.2
OS Version: Linux ARM64

Steps to Reproduce:
1. Install Simplified Chinese language package and "Prettier - Code formatter".
2. Open a .ts file with VS Code.
3. Right click.
4. Observe "格式化文档的方式...".

Expected:
1.Manifestations： "..." is at the end, and it is "格式化文档的方式..." instead of “使用...格式化文档”.
2.Position： "格式化文档的方式..." should be under “格式化文档”.
![expect](https://user-images.githubusercontent.com/78774400/116642934-7ead1300-a9a2-11eb-8aae-f0db2ad3b5d1.PNG)

Actual([reference the link](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L280)):
1.Manifestations： "..." is in the middle, and it is “使用...格式化文档”.
2.Position： "格式化文档的方式..." is located above “格式化文档”.
![actual](https://user-images.githubusercontent.com/78774400/116643279-422de700-a9a3-11eb-959e-b2ced2e61a90.PNG)

**Comment by v-mholloway** [comment]
translation corrected, but leaving positioning for SWE

**Comment by danyeh** [comment]
Close this. No longer repro.
![image](https://user-images.githubusercontent.com/19785531/135943423-f596f221-2997-47a8-8633-00d534f5647b.png)
