### ISSUE TITLE
Confusing iconage for setting default editor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#122772]
I opened this menu and clicked the gear several times expecting it to take me to some configuration page before realizing that it would actually set the default. 

![image](https://user-images.githubusercontent.com/8586769/116765016-0e20e900-a9d8-11eb-962f-ac08bbfc2f0d.png)

When I was trying to fix #122770 I kept searching command palette for a "Set Default Editor" command, I'd prefer if something like that existed, it was hard to tell that I should choose "reopen with editor..." then click the gear icon.

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/967020ff3805d9a4d24da9d2ac957f24e9994055

**Comment by lramos15** [comment]
@JacksonKearl I'm not sure why the bot didn't pick up my request to link the commit.

**Comment by JacksonKearl** [comment]
It expects a raw SHA, not a URL... the parsing could be improved but I try to be as strict as possible b/c there have been security issues regarding that in the past.

**Comment by lramos15** [comment]
Ah, I like the URL just because it's clickable, but I understand.

**Comment by JacksonKearl** [comment]
SHA's are made clickable too -- I edited the above and it's still a link. Looking into a secure regex to allow both formats because this has come up before.

**Comment by JacksonKearl** [comment]
Pushed https://github.com/microsoft/vscode-github-triage-actions/commit/a63583963cf275943cc178fe55fe326151c9cde4
