### ISSUE TITLE
Terminal opens on Esc

### ISSUE THREAD

**Issue by TheAsda** [microsoft/vscode#122788]
Issue Type: <b>Bug</b>

For some reason when i press 'escape' key terminal opens terminal opens for some reason. This happens when i'm in editor, settings.

UPD: After switching windows it now shows warning `Cannot use 'in' operator to search for 'instanceId' in 12`. This also happens in explorer and settings.

VS Code version: Code - Insiders 1.56.0-insider (6449b6b7253b5808e2278903c82da8d59a230383, 2021-04-30T11:35:41.567Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.25GB free)|
|Process Argv|--folder-uri file:///d%3A/Andrey/Programming/JS/file-manager-v2 --crash-reporter-id d481ca45-db0e-4764-b365-d74403ffe02f|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.5.10
vscode-toggle-quotes|Bri|0.3.4
turbo-console-log|Cha|2.1.6
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
rest-client|hum|0.24.5
graphql-for-vscode|kum|1.15.3
git-graph|mhu|1.30.0
remote-containers|ms-|0.174.0
debugger-for-chrome|msj|4.12.12
angular-console|nrw|17.2.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.9
prisma|Pri|2.21.2
mdx|sil|0.1.0
js-jsx-snippets|sky|10.1.0
code-spell-checker|str|1.10.2
windows-terminal|Tyr|0.6.0
vscode-wakatime|Wak|5.0.1
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you check your keyboard shortcuts (aka keybindings) for one that may have been assigned to the Esc key.

See https://github.com/microsoft/vscode/wiki/Keybinding-Issues

Also, use the "Start Extension Bisect" to investigate whether one of your 28 extensions is causing the issue.

**Comment by TheAsda** [comment]
Oh, for some reason my brain decided that escape and delete key are the same... Sorry... I meant delete key. When i launched VS Code it was working fine. After some time it stopped. So i don't think that some extension affected at runtime.

**Comment by meganrogge** [comment]
Please check what keybindings you have assigned to the delete key

**Comment by TheAsda** [comment]
I rebooted and it fixed. I think that something affected normal flow of keybindings. I'm closing this issue but if it occurs again i'll reach out again.
