### ISSUE TITLE
Remove node.js dependency from tunnel service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122723]
The `src/vs/workbench/services/remote/electron-browser/tunnelServiceImpl.ts` is one of those few remaining things that currently require node.js in the renderer. To prepare for a sandboxed renderer, we need to start thinking how a non-node.js version would look like.

Some options:
* switch to websockets (cc @alexdima)
* create a service in the shared process that can establish the tunnel (similar to how terminals moved there)

**Comment by richardburce** [comment]
> The `src/vs/workbench/services/remote/electron-browser/tunnelServiceImpl.ts` is one of those few remaining things that currently require node.js in the renderer. To prepare for a sandboxed renderer, we need to start thinking how a non-node.js version would look like.
> 
> Some options:
> 
> * switch to websockets (cc @alexdima)
> * create a service in the shared process that can establish the tunnel (similar to how terminals moved there)

LICENSE.txt

**Comment by alexdima** [comment]
This has been done.
