### ISSUE TITLE
Allow search in markdown previews

### ISSUE THREAD

**Issue by Josee9988** [microsoft/vscode#122786]
I would love to be able to search through a markdown preview:

Now we are able to search through the actual file where we type, but sometimes you just want to have the preview in fullscreen mode and search for any occurrence in the actual markdown preview.

If I'm showing the documentation to a partner I would rather use the full markdown preview rather than the raw code, and from there it would be useful to have the ability to search for text.

**Comment by ArturoDent** [comment]
If I open a markdown preview I can search through it - <kbd>Ctrl</kbd>+<kbd>F</kbd>.  What are you using to try to search in the preview?

**Comment by Josee9988** [comment]
I can search in the actual code window but not in the preview window. I'm using the same CTRL+F command but it doesn't pop up an input to search.

**Comment by Josee9988** [comment]
Here is a [video prove](https://i.imgur.com/PxaY61g.mp4) of what I try to say
I can CTRL+F in the .md file but not in the created by vscode markdown preview.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please fill int he issue template

**Comment by Josee9988** [comment]
In the latest VSCode insiders build with any extension installed it does work as expected:
![image](https://user-images.githubusercontent.com/38838976/117188005-d56c7f80-addc-11eb-94e0-7023d4f80917.png)
I can successfully search code in the actual markdown preview! 😄

**Comment by mjbvz** [comment]
This suggests that either an extension or custom keybinding is causing this. Please try reviewing your extensions first and filing an issue against which ever one causes this

**Comment by Josee9988** [comment]
maybe that was it. Sorry for the inconvenience!
