### ISSUE TITLE
 Live Share and NotebookSerializer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122733]
Before migrating to serializers, Live Share needs a way to get a list of the available serializers, similar to the command `vscode.resolveNotebookContentProviders`. We also need a way to add viewOptions when registering a serializer so that we can add a fileNamePattern for the serializer.

_Originally posted by @alyssajotice in https://github.com/microsoft/vscode/issues/102503#issuecomment-829424697_

**Comment by jrieken** [comment]
Adding @rebornix who came with this initially. There are couple of challenges with the overall approach

1. We now encourage extension authors to use the serializer API but we will keep the `NotebookContentProvider`-API. We are "rebranding" that API as the solution for out of the ordinary use-cases, e.g a folder is a notebook. This also mean extension implementing a `NotebookContentProvider` have lots of internal knowledge and I don't see how LiveShare would ever be able to "replicate" that logic
2. The `NotebookSerializer`-API  is more "pure" and LiveShare should be able to implement a generic serializer. However, the dynamic registration of package.json-data has a twist. Today, LiveShare dynamically registers "viewOptions" but those are never removed, e.g I would assume that at the end of a LiveShare session the content provider/serializer is being disposed but the viewOptions stick (missing dispose/remove [here](https://github.com/microsoft/vscode/blob/95119a7c95ae3359619b4b2c45135e5740192eb5/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L507)). @rebornix I don't know if that's an oversight or on purpose? I can image that the down-level editor world is having trouble when a usually static contribution is now dynamic.

**Comment by jrieken** [comment]
Independent of the open questions from above I have pushed a larger change that allows to register a notebook type while registering a notebook serializer. 

The `registerNotebookSerializer` now accepts a 4th parameter of type `NotebookRegistrationData`. Also, note that the signature `registerNotebookContentProvider` for **changed**. It also accepts the `NotebookRegistrationData` as 4th argument

**Comment by alyssajotice** [comment]
I saw on the iteration plan that Notebooks is set to become stable this month. Will `contentProvider` be part of the stable API?

**Comment by jrieken** [comment]
> Will contentProvider be part of the stable API?

No, we have no plans to finalize that API in the near future

**Comment by alyssajotice** [comment]
Is support for it going to continue in the foreseeable future?

**Comment by jrieken** [comment]
Likely - there are some bigger problems with the API and esp with its implementation but we will keep things the way they currently are.
