### ISSUE TITLE
VS Code (ver 1.55 ) high CPU - UI no response

### ISSUE THREAD

**Issue by abrahamdeepu** [microsoft/vscode#122778]
- VS Code Version: 1.55
- OS Version: Redhat 7.7 

Steps to Reproduce:

1. OS Version Redhat 7.7 ( all latest updates applied). if you have code repository configured, latest code (ver 1.55) also gets installed
Tried with code-exploration (ver 1.56) and issue is there also
You see two instance of process 'code' consuming near to 100% cpu on each of them. This continues until the process is forcibly closed. To resolve , I Reverted back to old version code  and issue no longer happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/115784#issuecomment-773555103
