### ISSUE TITLE
Buggy extension can crash VS Code

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#122749]
Issue Type: <b>Bug</b>

Our nightly extension was released with a bug - we forgot null check before accessing object properties in our `DebugAdapterTrackerFactory` implementation. I just noticed this buggy version brought down all my open VS Code windows, and I had to restart it. Not log or exception info.

I observed the same failure in our extension test that uses the extension test framework - no log but the exit code. 

I can reproduce this issue with golang.go-nightly 2021.4.2917. If there is any hidden log or system error message, I am happy to share more info with you.

Updating vscode to the latest version, I saw now VS Code shows this popup unlike the previous version of VS Code, so I guess this may be already known issue. If so, please dedup and close this.

![Screen Shot 2021-04-30 at 2 17 32 PM](https://user-images.githubusercontent.com/4999471/116738174-1c630b00-a9c0-11eb-9078-e604da890c2b.png)

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 17, 18|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 38411bc0-0aef-4dfe-af9a-ad94b542ce4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
go-nightly|gol|2021.4.2917
cloudcode|goo|1.11.0
remote-containers|ms-|0.166.1
vim|vsc|1.20.2

</details>

**Comment by isidorn** [comment]
@hyangah can you please fork https://github.com/microsoft/vscode-mock-debug and make changes to it such that this issue is reproducable on VS Code insiders.
I can not reproduce this problem currently
