### ISSUE TITLE
The order of Settings-Sync settings in Settings.json

### ISSUE THREAD

**Issue by HotariTobu** [microsoft/vscode#122762]
I want to stop sync of some specific settings but it doesn't work depending on the order of settings in Settings.json.

Let's say there are statements below in Settings.json,

```
"foo.bar1": "value1",
"settingsSync.ignoredSettings": [
	"foo.bar1",
	"foo.bar2"
],
"foo.bar2": "value2",
```

"foo.bar1" will be ignored in sync but "foo.bar2" will be not.

Therefore, please enable to ignore the sync without considering the order of setting statements.
Or please let it to always put "settingsSync.ignoredExtensions"and "settingsSync.ignoredSettings" under all setting statements.

VS Code: 1.55.2
Windows10: 20H2
Mac: 11.3

**Comment by sandy081** [comment]
Order is not considered, seems like the value of ignoredSettings is not proper. You are missing comma after first value. Please fix it and try again.

**Comment by HotariTobu** [comment]
Certainly, I forgot to insert a comma but it's not the essence of this issue.

**Comment by sandy081** [comment]
Ok let me check

**Comment by sandy081** [comment]
I just checked and it seems ignored settings are not synced irrespective of the order. Is it possible to provide a repro steps?
