### ISSUE TITLE
Open then close a file restart the ubuntu panel

### ISSUE THREAD

**Issue by fahmifan** [microsoft/vscode#122767]
Issue Type: <b>Bug</b>

open any project folder (tested on go and nodejs project) using 
```
cd ~/projectdir && code .
```
open any files, then close it

tested files: `.go .js .dockerignore .json`

the issue still happend when opening vscode with all extension disabled

when tried on vscode insider, the issue seems resolved
```
Version: 1.56.0-insider
Commit: 6449b6b7253b5808e2278903c82da8d59a230383
Date: 2021-04-30T09:28:30.413Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-72-generic snap
```

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.4.0-72-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (0.22GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 36102895-9edf-4b5f-aadb-45e82446d4ca|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.1
vscode-django|bat|1.6.0
toml|be5|0.5.1
better-toml|bun|0.3.2
dart-code|Dar|3.21.1
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-front-matter|eli|1.14.0
go|gol|0.24.2
gc-excelviewer|Gra|3.0.41
vscode-commitizen|Kni|0.14.1
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.8.1
dotenv|mik|1.0.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.18.0
LiveServer|rit|5.6.1
svelte-vscode|sve|104.10.3
vscode-ruby|win|0.28.0
vscode-caddyfile-syntax|zam|1.0.4
material-theme|zhu|3.10.13
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details>

https://user-images.githubusercontent.com/19581621/116761683-7f958180-aa42-11eb-8d1c-dbd084c520d7.mp4

**Comment by deepak1556** [comment]
Given the issue does not repro with insiders which has a newer runtime than `1.55` stable, closing for now. Can revisit if the issue continues with `1.56` stable.
