### ISSUE TITLE
bug: video system not initialised in pygame in vs code

### ISSUE THREAD

**Issue by starlightknown** [microsoft/vscode#122717]
**Issue type : Bug**

I get the following error while running pygame in vs code but I don't get the error while running the same program in pycharm

![vscode](https://user-images.githubusercontent.com/74637789/116664465-22ec8500-a9b6-11eb-88e4-7cf8b4a8a215.png)
![pycharm](https://user-images.githubusercontent.com/74637789/116664473-2aac2980-a9b6-11eb-9d62-a894627115cd.png)

- VS Code Version:
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
Please open an issue directly against the Python extension at https://github.com/Microsoft/vscode-python/issues
