### ISSUE TITLE
Breakpoint can not get hit when build with ninja

### ISSUE THREAD

**Issue by tyouritsugun** [microsoft/vscode#122789]
- VS Code Version: Version: 1.55.2 (Universal)
- OS Version: Darwin x64 20.4.0

Steps to Reproduce:

1. Same as described in https://gn.googlesource.com/gn/#getting-a-binary
2. Same as described in https://gn.googlesource.com/gn/#examples
3. Start VS Code and open the directory `examples/simple_build` in the sample source code.
4. This is my tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build Project",
            "type": "shell",
            "command": "ninja -C out hello",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
5. This is my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "Build Project",
            "program": "${workspaceFolder}/out/hello",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb"
        }
    ]
}
```
6. Add a breakpoint at `hello.cc`, line 12, and press F5, but the breakpoint cannot get hit.
7.  Also happens in Ubuntu version VS Code.
Ubuntu version:20.04
XCode version: 1.55.2

Does this issue occur when all extensions are disabled?: No

**Comment by tyouritsugun** [comment]
Sorry, this is not a VS Code bug. It turns out that I need to go to ```build/toolchain/BUILD.gn``` and add ```-g``` parameter to let ```gcc``` generate debug symbols.

**Comment by isidorn** [comment]
Closing then. Thanks for letting us know that it is not VS Code related
