### ISSUE TITLE
Dragging markdown cells causes indicator to flicker

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#122750]
1. Slowly drag a markdown cell on a code cell
2. At some point it flickers

https://memes.peet.io/img/21-04-0f697226-c69b-4798-af82-0e7cbd0d174f.mp4

**Comment by mjbvz** [comment]
Should be fixed by d7f6d7e735d46b6e0a4a9a4c1c3da36b1ac0c8b9
