### ISSUE TITLE
Readonly file system providers are not honoured

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122729]
File system providers can signal that they are readonly. They can either always be readonly, but this can also be changing during a session (capabilities can always change).

A custom editor currently does not seem to be readonly when the file system provider is readonly, i.e. I can still edit:

![recording](https://user-images.githubusercontent.com/900690/116701504-44ef0300-a9c8-11eb-9962-a9601af34ce5.gif)

**Comment by lramos15** [comment]
Correct me if I'm wrong @mjbvz, but isn't this up to each custom editor to implement?

**Comment by mjbvz** [comment]
Yes that's correct @lramos15. We added `FileSystem.isWritableFileSystem` that lets custom editors check this, but its up to them to make sure their editor disables editing features on a readonly file system

**Comment by Tyriar** [comment]
Created a bug in my ext for this https://github.com/lunapaint/luna/issues/548
