### ISSUE TITLE
terminal.integrated.showTabs setting is not recognized anymore and terminal display tab

### ISSUE THREAD

**Issue by bolinocroustibat** [microsoft/vscode#122708]
- VS Code Version: 1.56.0-insider
- OS Version: MacOS 11.3

`terminal.integrated.showTabs` setting seems to be not recognized anymore. Therefore, terminal displays a subpane which cannot be removed.

<img width="777" alt="Screen Shot 2021-04-30 at 12 43 48" src="https://user-images.githubusercontent.com/4353767/116646087-2d0c8480-a9b2-11eb-8283-0bea366befb0.png">

**Comment by meganrogge** [comment]
The setting is now called `terminal.integrated.tabs.enabled`
