### ISSUE TITLE
Nodemon package isn't working in Visual Studio Code

### ISSUE THREAD

**Issue by SR-22** [microsoft/vscode#122721]
Version: 1.55.2 (user setup)
OS: Windows_NT x64 10.0.19042

Hi VS code team,
The nodemon npm package doesn't work in vs code terminal. I installed it using:
`npm install nodemon`
The installation finished but when I used it:
`server.js nodemon` (In the terminal)
I got a whole bunch of errors and it doesn't work

Does this issue occur when all extensions are disabled?: Yes/No 
Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure you used commands as you showed here?

> `npm install nodemon`
> `server.js nodemon` (In the terminal)

Because it's incorrect way - installation should be global or you need to launch it in different way. `modemon` should be before script file, not after.

See details for pacage https://www.npmjs.com/package/nodemon

A;so make sure that that command works as expected in same shell but not in VS Code.

**Comment by SR-22** [comment]
Yes I types the same commands in and the current terminal in vs code was: 1:powershell

**Comment by IllusionMH** [comment]
Follow proper steps from package description and check if they work.
And if not make sure they work outside of VS Code in standard windows Power Shell

**Comment by SR-22** [comment]
Now before I even knew that their was a code editor with the name vs code I used git command line and their it works. Why doesn't it work in vs code

**Comment by SR-22** [comment]
I forgot to mention that since I realized this problem  I use the following command in the terminal to run my ```app.js``` file:
```node app.js```
The only problem is that when we make changes in the app.js we have to use ```^C``` to stop running the file and then again I have to type the same command that is ```node app.js``` Which is quite frustrating becaz for every little change I do I have to again and again stop it and run it again that's why I use nodemon but it doesn't work in vs code

**Comment by SR-22** [comment]
It's working now idk why it wasn't working earlier
