### ISSUE TITLE
Showing warning in Extensions

### ISSUE THREAD

**Issue by kshitij-github** [microsoft/vscode#122744]
Issue Type: <b>Performance Issue</b>

Whenever I search for any Extension in Visual Studio Code it shows this type of warning: "We cannot connect to the Extensions Marketplace at this time, please try again later"
plz help me to solve this error.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows 10
![Vs Code](https://user-images.githubusercontent.com/60069835/116734023-81435300-aa0a-11eb-8d04-aa74608e20a7.jpg)

**Comment by IllusionMH** [comment]
/needsMoreInfo

> Code 1.52.1

Looks old, latest version is 1.55.2. Is it still reproducible with latest version?

Do you have any firewall or proxy rules that blocked networks access for VS Code?

**Comment by kshitij-github** [comment]
Now, I have download a latest version of visual studio code... but still it shows the same error.

**Comment by nharrer** [comment]
@kshitij-github I recently had the same error. Turned out I had a not valid proxy configured in the vscode settings.

![image](https://user-images.githubusercontent.com/8344095/120366143-95cb8180-c30f-11eb-9fcc-cc41ceab037f.png)

Just in case you have the same problem.

**Comment by sandy081** [comment]
Please check if there are errors in the following:


    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Developer Tools -> Network - Please check if requests to Marketplace succeed

**Comment by kshitij-github** [comment]
@sandy081  Sir... This type of Errors and Warning are showing in the Console...
![Errors and Warnings](https://user-images.githubusercontent.com/60069835/120818509-5059bf00-c570-11eb-8612-ea0373e2f14f.png)

**Comment by sandy081** [comment]
Seems there are proxy issues - please check your proxy settings.
