### ISSUE TITLE
VS Code closes without warning intermittently

### ISSUE THREAD

**Issue by jameswilliambell** [microsoft/vscode#122711]
Issue Type: <b>Bug</b>

VS Code closes without warning intermittently. This has happened twice this week. 
Seems random in that there are no particular steps other than perhaps not actively doing anything when this happens. i.e. - Edit / look at a file - look at some other application, not vs code OR just stop interacting with vs code - VS Code crashes with no warning or visible error. I have attached a ZIP file with the events and Report.wer
The event log shows:

Faulting application name: Code.exe, version: 1.55.2.0, time stamp: 0x6048a446
Faulting module name: explorerframe.dll_unloaded, version: 10.0.19041.844, time stamp: 0x11d27117
Exception code: 0xc0000005
Fault offset: 0x00000000000c8141
Faulting process id: 0xaf48
Faulting application start time: 0x01d73cd46571ffb9
Faulting application path: C:\Program Files\Microsoft VS Code\Code.exe
Faulting module path: explorerframe.dll
Report Id: 54a2cc95-a584-4f1d-8c55-d2c19d67c535
Faulting package full name: 
Faulting package-relative application ID: 

AND

Fault bucket 1630823749841109866, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Code.exe
P2: 1.55.2.0
P3: 6048a446
P4: explorerframe.dll_unloaded
P5: 10.0.19041.844
P6: 11d27117
P7: 00000000000c8141
P8: c0000005
P9: 0000000000000008
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER572F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER582A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER583B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5848.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5878.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Code.exe_99bf8f31553c5e3a537dc8de8b519aa8513dcc_c583a0f0_66da1755-4fce-4bdc-8f1b-ec4702b323e1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 54a2cc95-a584-4f1d-8c55-d2c19d67c535
Report Status: 268435456
Hashed bucket: d119bb0f6060ef5376a1d98f5c8cc36a
Cab Guid: 0

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.19GB free)|
|Process Argv|--crash-reporter-id d8c586d1-6f19-4663-9109-bd98b52959cd|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.12
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.46
vscode-npm-script|eg2|0.3.21
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
classic-asp|ili|0.0.4
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
atom-keybindings|ms-|3.0.9
vscode-typescript-tslint-plugin|ms-|1.3.3
team|ms-|1.161.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|17.2.0
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
quicktype|qui|12.0.46
vscode-icons|vsc|11.4.0
material-theme|zhu|3.10.13

(16 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

[vscode-crash.zip](https://github.com/microsoft/vscode/files/6403014/vscode-crash.zip)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jameswilliambell** [comment]
Switched to insider build. I will use that and will let you know what happens

![image](https://user-images.githubusercontent.com/27325897/116652110-1583ca80-a9b7-11eb-93d9-5f1cba73d9b7.png)

**Comment by bpasero** [comment]
Thanks
