### ISSUE TITLE
Preview does not render colors correctly

### ISSUE THREAD

**Issue by suryanu** [Microsoft/vscode#12274]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
Developers really want live preview on browser like dream waver beta 3
1. It not render colors correctly.
2. Need buttons for web developers with shortcuts for live preview.
![screenshot 51](https://cloud.githubusercontent.com/assets/18899052/18639121/48d9f99a-7eb0-11e6-8e0d-ae7a46511941.png)
![screenshot 52](https://cloud.githubusercontent.com/assets/18899052/18639122/4917e6b0-7eb0-11e6-8b7e-c53d449f9109.png)

**Comment by suryanu** [comment]
Adobe brackets has very good live preview

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
