### ISSUE TITLE
HTML syntax isn't colored correctly inside markdown headers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122794]
![image](https://user-images.githubusercontent.com/2193314/116789053-d5c5ed00-aa61-11eb-861e-0486c32350c3.png)

**Comment by usernamehw** [comment]
Not only tags, none of the markdown features are highlighted in headers:

```md
# `code` **bold** _italic_ [link](https://www.google.com)
```

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode-markdown-tm-grammar/commit/399ff6f608a7bef3f68713be23cdcb4c6d475804

 We can see what the feedback is. It generally looks ok in the default dark+ theme, but in other themes it makes the header more difficult to tell apart from normal text

**Comment by usernamehw** [comment]
Theme authors can still make 1-color headers with the new grammar:

```js
{
    "scope": [
        "entity.name.section.markdown",
        "markup.heading punctuation",
        "markup.heading entity.name.tag",
        "markup.heading markup.inline.raw",
        "markup.heading markup.bold",
        "markup.heading markup.italic",
        "markup.heading string",
        "markup.heading markup.underline",
    ],
    "settings": {
        "foreground": "#EE9900"
    }
},
```

It might look better in the future if vscode were to support background color #3429

**Comment by Tyriar** [comment]
@usernamehw I think that one unfortunately has some architectural issues in monaco blocking it ☹️
