### ISSUE TITLE
[feature request] Add support for SymbolKind.AnonymousMethod (or SymbolKind.UnnamedMethod, SymbolKind.Lambda?)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#12272]
- VSCode Version: `Version 1.6.0-insider (1.6.0-insider)` de7267dc4e521aa7ef4187fd6b9c98570beea540
- OS Version: `OS X El Capitan Version 10.11.6 (15G1004)`

I think it would be great if there was a `SymbolKind` for anonymous (i.e. unnamed) methods/functions etc. This would allow for extension (especially CodeLensProviders) to differentiate between the different method types. For example, in my extension [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) I ideally don't want to render CodeLens for unnamed methods.

**Comment by jrieken** [comment]
dupe of https://github.com/Microsoft/vscode/issues/2628
