### ISSUE TITLE
Extension packages

### ISSUE THREAD

**Issue by daman9999** [microsoft/vscode#122783]
Different people have the ability of making their extension packages, That package includes bunch of extension they use or useful for them and other people can rate that package this will provide help to devlopers to get the required extensions without going to the pain of installing each extension individually and turning of an on specific extension for specific projects.
Here's an idea like we must have extension packages like for example we want a project in django [python] 
there should be only one extension package that we can install and all the features like DTL,coloring of text, and other features are activated . There should be a button that can enable and disable that extension for specific project .Like next i want to make a project in flutter i can disable that extension package on a single click and install enable flutter extension package and activate it in just one click.

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup
