### ISSUE TITLE
Notebook cell execution hint doesn't show extension-contributed keybinding

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122768]
From https://github.com/microsoft/vscode/issues/122407

We don't actually have a way to look up the keybinding for a command with a certain context. @alexdima I want to add this capability to the keybindings service by letting `lookupKeybinding` take a CKS like this

```ts
lookupKeybinding(commandId: string, target?: IContextKeyService): ResolvedKeybinding | undefined;
```

is that ok?

**Comment by roblourens** [comment]
Well, this was an adventure. To properly check the jupyter keybindings and other reasonable keybinding when clauses, we need to consider the notebookViewType key, editor focus keys, and jupyter's config key (because they disable these keybindings with a setting). Long story short, the strategy is to create a fake ContextKeyService that inherits from the editor's, and sets the focus-related keybindings. Another strategy would have been just to extract the parts of the when clause that we care about (notebookViewType, config) and evaluate those parts, but I don't want to copy any code related to evaluating when clauses.

**Comment by connor4312** [comment]
@roblourens are there verification steps for this?

**Comment by roblourens** [comment]
looks like #122407 regressed

**Comment by roblourens** [comment]
Verification steps

- On windows
- Install Jupyter
- Open a non-jupyter notebook
- Verify that the hint that shows in the placeholder is `ctrl+alt+enter` not `ctrl+enter` (see https://github.com/microsoft/vscode/issues/122407)

If you have customized this keybinding, then comment out your custom keybinding

**Comment by roblourens** [comment]
- Install Jupyter
- Open a non-jupyter notebook
- Click on a code cell that hasn't been executed, and the keybinding hint text should say "Press ctrl+enter to execute cell"

**Comment by mjbvz** [comment]
@roblourens I believe that still seeing this with b4c1bd0a9b03c749ea011b06c6d2676c8091a70c

Here's with Jupyter disabled:

<img width="1219" alt="Screen Shot 2021-06-09 at 9 35 37 AM" src="https://user-images.githubusercontent.com/12821956/121394540-4b956200-c906-11eb-9781-f7d92d0877f5.png">


And then after enable Jupyter and restarting VS Code:

<img width="1178" alt="Screen Shot 2021-06-09 at 9 36 24 AM" src="https://user-images.githubusercontent.com/12821956/121394592-59e37e00-c906-11eb-953c-ab7155b3713e.png">

**Comment by roblourens** [comment]
The tooltip is a separate issue, filed https://github.com/microsoft/vscode/issues/125865
