### ISSUE TITLE
_prepareRenderWidget calculation error  in contentWidgets

### ISSUE THREAD

**Issue by shuyaqian** [microsoft/vscode#122707]
Hello, I have a problem. When I use the debugger for java plug-in, text overlap occurs:
![image](https://user-images.githubusercontent.com/6367259/116643617-08111500-a9a4-11eb-9526-b7cdddd869fe.png)
Procedure: Open file B, activate the debugger plug-in, and switch back to file A. Codelens overlaps.

I found that this is because in theia, _prepareRenderWidget is executed together with files A and B in the editor area, but in file A that is not open at this time, so the domNode.clientHeight of codelens is 0. 
![image](https://user-images.githubusercontent.com/6367259/116643943-bcab3680-a9a4-11eb-9548-eb6d88ce1994.png)
Therefore, the value of _cachedDomNodeClientHeight is incorrectly calculated, causing overlap.

I have two ideas. One is to modify the calculation logic of _cachedDomNode in vscode, the other is to trigger codelens updates when files are switched in theia，I don't know which way is more appropriate.

I tried to trigger the onDidChange event that triggered codelens when there was a change in the main area, 
![image](https://user-images.githubusercontent.com/6367259/116663954-63ee9480-a9ca-11eb-8e4d-a63b3b5b3ffe.png)
![image](https://user-images.githubusercontent.com/6367259/116664150-a6b06c80-a9ca-11eb-87f3-5dfe92710cc5.png)
but the codelens was not updated. May I ask if I write that incorrectly?

**Comment by jrieken** [comment]
> I found that this is because in theia, _prepareRenderWidget is executed together with files A and B in the editor area,

theia? this is the vscode repository. Does this reproduce with VS Code stable or insiders?

**Comment by shuyaqian** [comment]
> > I found that this is because in theia, _prepareRenderWidget is executed together with files A and B in the editor area,
> 
> theia? this is the vscode repository. Does this reproduce with VS Code stable or insiders?

[monaco-editor-core](https://www.npmjs.com/package/monaco-editor-core) is used in my project,  what I can't figure out is that using the following code to actively trigger the codelens update didn't work:
![image](https://user-images.githubusercontent.com/6367259/116663954-63ee9480-a9ca-11eb-8e4d-a63b3b5b3ffe.png)
![image](https://user-images.githubusercontent.com/6367259/116664150-a6b06c80-a9ca-11eb-87f3-5dfe92710cc5.png)

**Comment by jrieken** [comment]
I am sorry but I cannot help with this little information provided. In VS Code the onDidChange-event of a code lens provider is used to tell the UI that lenses of a controller have changed, it's not used the other way around.
