### ISSUE TITLE
Getting Started: Markdown will refresh when step completion changes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122812]
![recording (4)](https://user-images.githubusercontent.com/2193314/116816433-c05eca80-ab16-11eb-95d1-f2153bead13d.gif)

**Comment by JacksonKearl** [comment]
Changed the behavior of clicking on the main body of the tile to simply select it and not toggle completion as that had been bothering me for a bit in cases where I just wanted to focus the item.

Clicking the checkmark element itself still toggles completion, fixed the re-rendering there.
