### ISSUE TITLE
Cannot create or rename entries in Explorer on a large repo

### ISSUE THREAD

**Issue by daprahamian** [microsoft/vscode#122879]
- VS Code Version: 1.55.2
- OS Version: macOS Big Sur 11.2

Steps to Reproduce:

1. Open a git repo with a large number of files ( > 500,000)
2. In the Explorer, create a new file
3. Wait up to 10 seconds

Expected: The file name entry should continue to exist until file name is entered
Observed: The file name entry is randomly terminated, resulting in either no file (if file entry was empty) or a partially-named file (if mid-typing)

This might be a duplicate of https://github.com/microsoft/vscode/issues/114573, but as pointed out on that issue, I am still seeing this problem even though the previous issue is closed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/112293

**Comment by chrisgbaker** [comment]
I also updated to my version of VS Code today and now am seeing this issue. I don't know the cut-off, but this is only happening on a very large repo, and not in any of the smaller microservice repos I contribute to.
