### ISSUE TITLE
Add option to convert tabs to spaces

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#1228]
Would it be possible to add a VS Code command to convert tabs to spaces, and vice versa?

I copied some JSON code from GitHub into VS Code, using Google Chrome, and it's indented using tabs. I'd like to convert it to use 2 spaces.

I searched for this issue on here, and couldn't find it. I only saw references to VS Code settings for using tabs or spaces by default.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Tyriar** [comment]
This can be fairly easily achieved using find and replace with regex. This sort of functionality would probably better be captured in an extension rather than the core editor.

**Comment by hashhar** [comment]
I agree with @Tyriar.

**Comment by egamma** [comment]
+1 that this is should be done in an extension. Keeping open as a help wanted, feature request.

**Comment by xeoneux** [comment]
I do agree that this can be done via an extension however, I strongly believe that a simple option to translate tabs to spaces or vice versa should be present as it increases the editor's usability a lot. The developer's focus would remain on the code rather than on fixing such trivial issues by searching for an extension. These convenient yet lightweight additions to the editor would make it really pleasing to use.

It was one of the features of Sublime Text that I clearly remember being handy when required!

![Tabs to Spaces](https://cdn.css-tricks.com/wp-content/uploads/2014/01/tabs-to-spaces-same.gif)

**Comment by wadeanderson7** [comment]
Looks like there are a couple of extensions that do this. 

* https://marketplace.visualstudio.com/items/yuichinukiyama.TabSpacer
* https://marketplace.visualstudio.com/items/ilich8086.Untabify

**Comment by stevenmwade** [comment]
@xeoneux I agree, this should be on the core editor.

**Comment by bumpmann** [comment]
+1

**Comment by andradei** [comment]
It can be an extension, sure. But VS Code already does so many neat things that ease development (like Git integration) which are extensions on other editors. This could easily be a built-in feature.

**Comment by warpdesign** [comment]
+1

**Comment by gulshan** [comment]
+1 for this feature built into vscode

**Comment by jcurlier** [comment]
+1

**Comment by perrich** [comment]
+1

**Comment by evolutional** [comment]
Things like tab/space and line ending conversion is really a core editor feature in my mind.

**Comment by LittleBrainz** [comment]
The primary reason I switched from Atom to Code was that I would no longer need to install an extension for every little editor feature I used daily. To me, space / tab conversion is a fundamental code editing requirement that belongs in the core product.

**Comment by xeoneux** [comment]
@LittleBrainz Exactly. Code provides a lot of functionality out of the box as compared to Atom and that was my reason for the switch too.

**Comment by cthedot** [comment]
+1 

When opening "foreign" files a simple core option would be much better than ext replace or beeing forced to install an extension

**Comment by rakkarage** [comment]
:+1:
and spaces to tabs please

**Comment by fcrespo82** [comment]
+1

**Comment by allbitsnbytes** [comment]
+1

I use Untabify but agree that this should be a core feature.

**Comment by sandcastle** [comment]
There is an extension I created a while back that achieves this, it automatically updates files on save so if you touch the file it will normalize the whitespace.

- Marketplace: https://marketplace.visualstudio.com/items?itemName=sandcastle.whitespace
- GitHub: https://github.com/sandcastle/vscode-whitespace

**Comment by hworld** [comment]
+1 Would love this as a core feature, as well. It's something I missed moving from Sublime an it helps a lot when copy/pasting code from other sources.

**Comment by irrwitz** [comment]
+1
IMHO Tab<->Space conversion should be in core, like e.g. the awesome Markdown Preview (Crtl+Shilft+V) or git integration.

**Comment by isidorn** [comment]
Fixed by f01ee9854050254fa55865c6380a50f56171700b

**Comment by pcgeek86** [comment]
@isidorn Thank you sir! :)

Cheers,
Trevor Sullivan
