### ISSUE TITLE
Renaming a file in a folder in WSL

### ISSUE THREAD

**Issue by coldperformer** [microsoft/vscode#122811]
Hey Team,

I am facing an issue while creating and renaming files in the WSL remote.
Whenever I am creating a new file either it automatically stops before creating or doesn't let me create at all.
The same is happening while renaming any file in WSL.

Regards,
Mukesh

**Comment by isidorn** [comment]
I believe this is a WSL issue, thus forwarding to @aeschli and he can probably close as duplicate

**Comment by coldperformer** [comment]
Okay, will it be fixed or not? 😅

I am having some difficulty while doing my work.

Is there any fix for this issue?

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1
