### ISSUE TITLE
QuickOpenView Bug and Inconsistency

### ISSUE THREAD

**Issue by eirikpre** [microsoft/vscode#122838]
Issue Type: <b>Bug</b>

QuickOpen is showing detached items first, without the correct name.

Also, an improvement would be to follow the ordering in which items are placed on the sidebar, not some predefined order.

![image](https://user-images.githubusercontent.com/10548539/116862981-e2834600-ac05-11eb-8686-3bf441c772e7.png)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.09GB free)|
|Process Argv|--crash-reporter-id 542ae1cb-c759-43e9-be98-24ea42191fa7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cad09|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (24 x 1862)|
|Memory (System)|377.48GB (4.47GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
tcl|ras|0.1.0
jinjahtml|sam|0.16.0
gitlens|eam|11.4.1
systemverilog|eir|0.11.3
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.3
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
cursor-align|yo1|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
vstes516:30244333
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by eirikpre** [comment]
Re-opening VSCode, changing folders, merging or shuffling the sidebar does not fix nor change the issue.

**Comment by bpasero** [comment]
Looks like a (custom) view service issue to me.

**Comment by sandy081** [comment]
@eirikpre Can you please provide steps to reproduce

**Comment by eirikpre** [comment]
Hello @sandy081 
I'm sorry I didn't see the post.
It is always present in "View: Quick Open View (Ctrl+Q)"
