### ISSUE TITLE
The icon display of activity bar and menu bar doesn't look normal. I don't know why?

### ISSUE THREAD

**Issue by yzhou15** [microsoft/vscode#122803]
- VS Code Version:VS Code Version:VSCodeUserSetup-x64-1.55.2
- OS Version:win 10

Steps to Reproduce:

1.The icon display of activity bar and menu bar doesn't look normal. I don't know why?
2.
![111](https://user-images.githubusercontent.com/27675355/116798541-0b7eda80-ab23-11eb-9cf9-edb7a56ceeb4.png)

![222](https://user-images.githubusercontent.com/27675355/116798543-1174bb80-ab23-11eb-8b48-f5b480f553bc.png)

The icon display of activity bar and menu bar doesn't look normal. I don't know why?

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by misolori** [comment]
This looks a similar issue to https://github.com/microsoft/vscode/issues/85872 and https://github.com/microsoft/vscode/issues/110288. 

Do you have any special font software installed (like [mactype](https://mactype.net/))? Anything that would disable fonts from loading?

**Comment by misolori** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/122021

**Comment by yzhou15** [comment]
> This looks like a similar issue to #85872, #110288, and #122021
> 
> Do you have any special font software installed (like [mactype](https://mactype.net/))? Anything that would disable fonts from loading?

Thank you for your reminder. I saw that I installed mactype. After I tried to disable it, the display was normal.
