### ISSUE TITLE
Unable to display Folders in VSCode

### ISSUE THREAD

**Issue by octobeau** [microsoft/vscode#122882]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

Using either of the following methods to open a folder:
1) from commandline in a folder you want to open, type code . 
2) In the VSCode app, click on Open Folder, select the folder. 

In both cases, this issue just started on 5/3/2021, where the contents of the folder is not displayed. Also, the Explorer menu, select the ... menu item. It shows Foders greyed out with a check box next to it.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 4|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|. --crash-reporter-id 6eb8c031-27f2-4e49-8533-76f094634cf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
azurepolicyextension|Azu|0.1.2
armview|ben|0.4.5
bracket-pair-colorizer-2|Coe|0.2.0
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|6.3.2
azure-storage-explorer|for|0.1.2
AzureFunctionsSnippets|hha|0.1.0
vscode-nuget-package-manager|jmr|1.1.6
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestaticwebapps|ms-|0.6.0
vscode-azurestorage|ms-|0.12.0
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.3.0
vscode-bicep|ms-|0.3.255
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.0.0
vscode-aks-tools|ms-|0.0.8
vscode-kubernetes-tools|ms-|1.3.2
remote-containers|ms-|0.166.1
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell|ms-|2021.2.2
vscode-node-azure-pack|ms-|0.1.0
azurerm-vscode-tools|msa|0.15.1
vscode-react-native|msj|1.4.2
vscode-yaml|red|0.18.0
html-to-jsx|ria|0.0.1
paste-clean-diff|siv|1.1.0
application-insights|Vis|0.4.2
vscode-icons|vsc|11.4.0
WebTemplateStudio-dev-nightly|WAS|0.5.2104801
arm-params-generator|wil|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you add the `--disable-extensions`argument to your command line?
