### ISSUE TITLE
Rendering video / blob in WebView

### ISSUE THREAD

**Issue by smdsbz** [microsoft/vscode#122857]
- VS Code Version: 1.55.2
- OS Version: Win10 20H2

I'm building a WebView that has embedded video (with [`DPlayer`](https://dplayer.js.org)), its HTML looks something like this

<details>
<summary>html content</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="img-src 'self' data: https: http: blob: ${this.view!.webview.cspSource}; default-src 'unsafe-inline' 'unsafe-eval' vscode-resource: data: https: http: blob:;">
  <title>${utils.toHTMLSafe(this.title!)} - ${utils.toHTMLSafe(this.uname!)}</title>
  <script src="https://cdn.bootcdn.net/ajax/libs/flv.js/1.5.0/flv.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/hls.js/1.0.1/hls.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/dashjs/3.2.2/dash.all.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/dplayer/1.26.0/DPlayer.min.js"></script>
</head>
<body>
  <div id="live-player"></div>

  <script>
//const vscode = acquireVsCodeApi();
let display = new DPlayer({
  container: document.querySelector("div#live-player"),
  autoplay: true,
  live: true,
  video: {
    url: "http://d1--cn-gotcha105.bilivideo.com/live-bvc/828507/live_477332594_31175064_1500.m3u8?cdn=cn-gotcha05&expires=1620052398&len=0&oi=804332725&pt=h5&qn=150&trid=f96c40d458a04146a69107cc07fb5737&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=9f6d006a2666c7d78b5dd0d8d12d114d&ptype=0&src=9&sl=4&sk=59b4112a8c653bb&order=1",
    type: "hls"
  }
});
  </script>
</body>
</html>
```

</details>

I'm new to the whole Web as well as multimedia thing, but to my understanding, `DPlayer` seems to be rendering segmented video by sequentially downloading segments as `blob`, and replacing `DPlayer.video`'s `src` just-in-time. `DPlayer` is able to be doing this just fine in a normal browser, but the mechanism fails in WebView.

| ![image](https://user-images.githubusercontent.com/19503270/116888153-b4315500-ac5d-11eb-8f35-bce29af286f3.png) |
|:--:|
| Thou nothing is printed or thrown, the reassignment fails, `src` remains untouched. |

To back-up my theory, I replaced the video with a non-segmented one, e.g. an `.mp4`, the video played without an issue.

I wanted to know if VSCode is intentionally shutting down `blob`? Or it's because something else?  
And how may I fix / bypass this?

\* I'm filing this issue as a WebView feature request rather than a bug,

**Comment by mjbvz** [comment]
Please fill in the issue template

**Comment by smdsbz** [comment]
This is a duplication of #54097, closing the issue.
