### ISSUE TITLE
CI timeouts seem too aggressive

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122852]
I see tests sometimes turn red because the timeout of 7min has been reached:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=116592&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&l=15858

![image](https://user-images.githubusercontent.com/900690/116877007-a825a300-ac1d-11eb-854c-e9a2045abde7.png)

**Comment by lszomoru** [comment]
I have looked at [the pipeline analytics](https://dev.azure.com/monacotools/Monaco/_pipeline/analytics/duration?definitionId=111&contextType=build) and I see that the browser unit tests for the Mac take about `260` seconds at `80%` percentile. In the past when I have looked at this, a timeout indicated an issue with a test, as in those particular cases I tried to bump up the timeout to 10 minutes for example and the task still timed out.

**Comment by lszomoru** [comment]
Closing this issue for now. Please re-open in case this reoccurs.
