### ISSUE TITLE
Angular error logging prevents stackfraces from displaying properly

### ISSUE THREAD

**Issue by maurei** [microsoft/vscode#122870]
**Describe the bug**
I have been unable to get a debugging experience going on the way I envision it. This is occurring with a freshly generated angular app (`ng new app-name`, v11). I enabled sourcemap  in `launch.json`, see repro.

The issue is that when errors are thrown, the output in debug console is not very helpful:

<img width="1339" alt="screenshot_vscode" src="https://user-images.githubusercontent.com/9339132/116814394-12284480-ab59-11eb-82bd-b12e33f4360e.png">

Note that the file in which the error is thrown is `main.js` and clicking it doesn't lead anywhere. What I am expecting to have it the same in chrome devtools: where I get a correctly mapped stacktrace which links, in this case, to the `app.component.ts `file.

**To Reproduce**
- VS Code Version:   1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d)
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Clone https://github.com/maurei/visual-studio-debugging-angular-report
2. Run `ng serve`
3. Attach debugger
4. Notice the stack trace of the error that is thrown: it does not contain useful stacktraces

**Comment by connor4312** [comment]
This actually works in the js-debug side of things. The issue is more that the debug console doesn't support multiline strings. The `Error` line here has the stacktrace on subsequent lines, but these are hidden:

![](https://memes.peet.io/img/21-05-f57e3224-8366-4a04-9cac-f2c0b86ac29b.png)

Compared to Chrome devtools where they're visible:

![](https://memes.peet.io/img/21-05-917e0376-32b2-4d14-b8d8-1d056e7a657f.png)

@isidorn let me know if you want help with this, my debt week work is quite light. I think we should

**Comment by isidorn** [comment]
@connor4312 yeah we escape newilnes in the debug console.
This is controlled by this css property [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/media/repl.css#L31)

And [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/media/repl.css#L17)

We would need to check if this works nicely both when wordWrap for debug console is turned on and off via `debug.console.wordWrap` setting.

If you have time help is welcome, and I can provide more pointers / info if needed :)

**Comment by isidorn** [comment]
Leaving this up to you @connor4312 since you have the context. And will not assign @roblourens

**Comment by jpike88** [comment]
This is driving me and my developers insane, we have to juggle a chrome dev console constantly while this problem persists. Please can this be a higher priority, or at least have a workaround that flattens the output into a single line

**Comment by Nukiloco** [comment]
I'm also having the same issue. I really don't want to keep having to open Chrome debugger tools to get a stack trace, it would really be helpful if the debug console showed the entire stacktrace.

As for a temporary workaround, maybe there is a way to redirect chrome's console output to vscode's debug console?

**Comment by rchiodo** [comment]
/verified

On insiders I get this:

![image](https://user-images.githubusercontent.com/19672699/155434184-7a35dc97-9b31-4324-b96f-8d5533424103.png)

On stable I get this:

![image](https://user-images.githubusercontent.com/19672699/155434214-c2992c6f-e3eb-47ac-9ad0-11c85fe7cdb3.png)
