### ISSUE TITLE
Disconnect between user running cell from vscode contributed `Run Cell`  and extension contributed `Run Cell Above/Below`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#122877]
- VS Code Version: Insiders
- OS Version:Mac

Steps to Reproduce:

1. Install Jupyter
2. Open a new notebook
3. Add two cells.
4. Use the cell toolbar icons to run above or below cells.
5. Confirm cells get executed
6. Run run an individual cell, user will get prompted to select a kernel.

Basically its possible for extension to run cells and update cells, but VS Code isn't updating the kernel selection. 

I think the kernel selection & execution workflow needs to be reviewed here as theres a disconnect between the two.
Should extensions be allowed to use execution API if nothing is selected? Should extensions get a higher level API that just says `execute cell` and VS Code will prompt the user to select a kernel and then VS Code will route that request to the right controller?

@jrieken @rebornix @IanMatthewHuff /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
This is an interesting scenario... One could say that the presence of an execution is another implicit kernel selection reason (see https://github.com/microsoft/vscode/issues/122647) but that would be a "back door" for kernels to select themselves. 

For once, I believe that the run "above/below commands" should come from VS Code itself. IMO there is value in having a uniform way to perform these operations. We could maybe leaving it up to extensions to put such commands prominently into the cell toolbar or not. Nevertheless, it doesn't solve the problem of "automatically" executing cells and I believe we should simply prevent such executions from happening. "Prevent" can mean that we throw or that we ignore executions.

**Comment by DonJayamanne** [comment]
> t the run "above/below commands" should come from VS Code itself. IMO there is value in having a uniform way 

Agreed however, we still would like to run cells ourselves as well. E.g. recently we experimented with a new feature where we'd run cells that are not selected & doesn't fall into any sort of run operation we have today.

**Comment by jrieken** [comment]
> Nevertheless, it doesn't solve the problem of "automatically" executing cells and I believe we should simply prevent such executions from happening. "Prevent" can mean that we throw or that we ignore executions.

For now, I have implemented "preventing" as throws an error.

**Comment by jrieken** [comment]
> Should extensions get a higher level API that just says execute cell and VS Code will prompt the user to select a kernel and then VS Code will route that request to the right controller?

You can actually already achieve that (with 1.56 or later) using the `notebook.cell.execute` command. This is what my sample, which executes the next cells, looks like

```ts
vscode.commands.registerCommand('extension.helloCell', async (cell: vscode.NotebookCell) => {
        return vscode.commands.executeCommand(
            'notebook.cell.execute',
            new vscode.NotebookRange(cell.index + 1, cell.index + 2), // next cell
            cell.notebook.uri // notebook (defaults to active notebook editor)
        )
});
```

**Comment by jrieken** [comment]
Given that we are more strict now and given the "API-command" I think we are done here? Anything else that's missing @DonJayamanne

**Comment by DonJayamanne** [comment]
> e "API-command" I think we are done here? Anything else that's missing

Not sure the API command can be considered as a command.
As an extension author if i were to do this, now (based on what you've mentioned) and error would be thrown and I have no idea why or how to solve this.

Basically there's no documentation in the *.d.ts files that tells me the way to run a cell is to actually use `executeCommand`. I'd like to think that having an API (that's documented) is better.
E.g. there's no strong typing for `executeCommand` and the required arguments are completely unknown to an extension author.

**Comment by jrieken** [comment]
> Basically there's no documentation in the *.d.ts files that tells me the way to run a cell is to actually use executeCommand.

It is a thing, see https://code.visualstudio.com/api/references/commands

**Comment by DonJayamanne** [comment]
Oooh, i didn't know about that, then I think we can close this, 
Thanks.

**Comment by DonJayamanne** [comment]
Interesting, that command only runs one cell for me, filed an issue https://github.com/microsoft/vscode/issues/123024
