### ISSUE TITLE
Vscode wsl terminal name of distro

### ISSUE THREAD

**Issue by LucasTavernier** [microsoft/vscode#122885]
- VS Code Version:  1.55.2
- OS Version: Windows 10

Steps to Reproduce:

1. Change default terminal to distro by default of wsl
2. Try to launch the terminal

Does this issue occur when all extensions are disabled?: Yes

Hi guys, so i think i found a bug (i want to say sorry for my english to start because im french)
My problem is i can't set as default terminal my default distro wsl because it add in the name "default" like "Ubuntu (default)"
So, vscode cannot launch wsl.exe with as argument "-d Ubuntu (default)"
If i remove the "(default)" in the settings.json for "terminal.integrated.shellArgs.windows" it works.
So tell me how to change this in vscode or even in windows ? (like maybe i have to rename my distro i don't know).

Thanks for the read and the help in advance :D

![Sans titre 1](https://user-images.githubusercontent.com/58571537/116944306-83f5b080-ac75-11eb-98ef-0fdaf9597201.jpg)

**Comment by meganrogge** [comment]
Thanks this has been fixed in Insider's already
