### ISSUE TITLE
VSCode and Yarn 2 TypeScript & types not found

### ISSUE THREAD

**Issue by djbauch** [microsoft/vscode#122801]
Issue Type: <b>Bug</b>

npx create react-app --template typescript

yarn set version berry

Now VSCode can't find the type declaration files for any npm packages added. It's looking in the node_modules directory, and Yarn 2 removes them from node_modules. Approximate equivalent is .yarn/cache. Same is true for the TypeScript transpiler itself. Can't set the compiler version to the one in the project because VSCode is looking in node_modules for that too.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz (28 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (40.79GB free)|
|Process Argv|. --crash-reporter-id d1f82862-2871-4d47-bd01-26578005abee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.0
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
prettier-vscode|esb|6.3.2
yaml-plus-json|hil|1.7.0
vscode-map-preview|jum|0.5.8
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-wsl|ms-|0.54.6
cmake-tools|ms-|1.7.1
vscode-typescript-tslint-plugin|ms-|1.3.3
geo-data-viewer|Ran|2.4.0
vscode-yaml|red|0.18.0
rust|rus|0.7.8
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by djbauch** [comment]
$ **npx create-react-app bug-report --typescript**
npx: installed 67 in 5.03s

Creating a new React app in D:\lab\React\bug-report.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.22.10
... many more lines ..
Happy hacking!

$ **cd bug-report**

$ **yarn --version**
1.22.10

$ **yarn set version berry**
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into D:\lab\React\bug-report\.yarn\releases\yarn-berry.cjs...
Updating D:\lab\React\bug-report/.yarnrc.yml...
Done!

$ **yarn --version**
2.4.1

$ **yarn install**
...

$ **tsc --version**
4.2.4

$ **mv src/index.js src//index.tsx**

$ **code .**

![image](https://user-images.githubusercontent.com/2002795/116798779-d76ecf80-aab8-11eb-8c21-cd6c0b89b7e9.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Have you followed steps for editor setup
https://yarnpkg.com/getting-started/editor-sdks#vscode?

Something similar should be done for TS compiler.

**Comment by djbauch** [comment]
@IllusionMH thank you for the answer. The "pnpification" of the directory for vscode solves the problem as you described.-

The command:
**yarn dlx @yarnpkg/pnpify --sdk vscode**
