### ISSUE TITLE
Getting Started: altText warning when it's the empty string

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122813]
I have the following in package.json:

```
{
	"id": "luna.interfaceOverview",
	"title": "Interface Overview",
	"description": "Luna Paint features a canvas, several windows and a bars on the top and bottom.",
	"media": {
		"path": "getting-started/images/1-interface-overview.png",
		"altText": ""
	}
}
```

But still see this warning in console:

```
Getting Started: item Tyriar.luna-paint#exampleProject#luna.interfaceOverview is missing altText for its media element.
```

I've explicitly set the alt text to the empty string so that should not warn - the image is already explained sufficiently by the description.

**Comment by githubnew-pro** [comment]
> موارد زیر را در package.json دارم:
> 
> ```
> {
> 	"id": "luna.interfaceOverview",
> 	"title": "Interface Overview",
> 	"description": "Luna Paint features a canvas, several windows and a bars on the top and bottom.",
> 	"media": {
> 		"path": "getting-started/images/1-interface-overview.png",
> 		"altText": ""
> 	}
> }
> ```
> 
> اما هنوز این هشدار را در کنسول ببینید:
> 
> ```
> Getting Started: item Tyriar.luna-paint#exampleProject#luna.interfaceOverview is missing altText for its media element.
> ```
> 
> من به طور صریح متن alt را روی رشته خالی تنظیم کرده ام که نباید هشدار دهد - تصویر قبلاً با توضیحات به اندازه کافی توضیح داده شده است.

**Comment by githubnew-pro** [comment]
#123976 #123899 #123975
