### ISSUE TITLE
Wrong file opened in editor after copy/past

### ISSUE THREAD

**Issue by Thaldos** [microsoft/vscode#122837]
- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

![steps](http://masterofolympus.com/sites/default/files/JcFAADwCHu.gif)

Does this issue occur when all extensions are disabled?: Yes

This is a very disappointing bug : when we copy past a file, the file selected in menu is not the one opened in the editor. Intuitively we expected have the new pasted file opened in editor, not have the "old" copied file opened in editor. Please, can you fix this?

Thx

**Comment by isidorn** [comment]
Duplicate, fixed in insiders
