### ISSUE TITLE
wsl extension proxy reboot

### ISSUE THREAD

**Issue by cool-delete** [microsoft/vscode#122867]
If the extension is installed under wsl and the extension needs to use proxy access

The ip address of wsl will change every time the computer is restarted

```

**Comment by cool-delete** [comment]
At present, I have modified the content of the init.wsl file in the etc folder
to temporarily solve the problem
```sh
#/etc/init.wsl
hostip=$(awk '/nameserver / {print $2;}' /etc/resolv.conf 2>/dev/null)
sed -i "116s/http.*/http.proxy\":\"http:\/\/$hostip:[port]\",/" /mnt/c/Users/****/AppData/Roaming/Code/User/settings.json
```

**Comment by aeschli** [comment]
Can you explain how this is related to VSCode?

**Comment by cool-delete** [comment]
I think for the extension of vscode, they can't ask them to actively find the host address, right? Can vscode make the extension use the correct proxy address?

**Comment by aeschli** [comment]
If I understand yourscript correctly, it gets the IP of the Windows machine and puts it to the `http.proxy` setting.

Maybe instead of doing this with the `http.proxy` setting, can you set the `https_proxy` environment variable? That's what Linux tools typically rely on. Also VSCode uses it the `http.proxy` setting is not defined.

**Comment by cool-delete** [comment]
> If I understand yourscript correctly, it gets the IP of the Windows machine and puts it to the `http.proxy` setting.

Yes, but I don’t want to set environment variables. It seems that election will automatically read the environment variable `http_proxy`. This will cause my other election app to use proxy access by default.

**Comment by aeschli** [comment]
I was thinking about setting the environment variables just in WSL (or do you have Electron apps running in Linux?)

If you want to set environment variables just for the VSCode server, then you can use https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script

If you want to use VSCode settings, but only when inside WSL, use the Remote settings:
- Open the Settings UI and switch to `Remote [WSL: Ubuntu]` tab.

I have the feeling that your setup is quite special (I haven't heard a similar request) and I'm also not sure what exactly what has to be provided by VSCode.
Closing this issue for now
