### ISSUE TITLE
Package Not Matched?

### ISSUE THREAD

**Issue by MattMcL1221** [microsoft/vscode#122872]
For some reason I get an error that says my package 

package hw09;

does not match the expected package "" Java(536871240)

I looked at the corresponding issues on this and even googled solutions but I cant find anything that makes sense to me. This is extremely annoying to deal with as a student required to meet deadlines

**Comment by mishrarajat** [comment]
@MattMcL1221 Did it resolved for you by any chance or did you raised any other issue as mentioned above ?

**Comment by MattMcL1221** [comment]
I cant remember what I did to fix it exactly but I changed a bunch of stuff and it worked, one of the things I know I did was make  everything in the settings.json file to "" like so:
`{
    "java.project.sourcePaths": [
        ""
    ]
}`
