### ISSUE TITLE
Not finding “Terminal: Manage Workspace Shell Permissions” in command palette of VS Code Insiders

### ISSUE THREAD

**Issue by RobertCardwell** [microsoft/vscode#122800]
- VS Code Version: 1.56.0-insider (user setup)
- OS Version: Windows 10 Pro, build 19041.928

Steps to Reproduce:

1. Open the Control Palette (control + p) and start typing ">Terminal: Manage Workspace Shell Permissions" without the quotation marks and the command does not show.

2. This only happens in **Insiders**. The standard VS Code shows the command as expected.

3. I need this because it is in the documentation ( https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration ) as the way to set the permissions.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe this is what you need:

https://github.com/microsoft/vscode/issues/121470#issuecomment-828525577

**Comment by RobertCardwell** [comment]
> Maybe this is what you need:
> 
> [#121470 (comment)](https://github.com/microsoft/vscode/issues/121470#issuecomment-828525577)

Thanks. I've investigated further and found that it actually happens in both Insiders and Standard. The problem is with WSL linux terminals in VS Code. Still not sure about the cause but I'll close this issue as not really related to the original issue.
