### ISSUE TITLE
git.inputValidationSubjectLength and git.inputValidationLength not working on Manjaro Linux

### ISSUE THREAD

**Issue by Nibblesh** [microsoft/vscode#122824]
![image](https://user-images.githubusercontent.com/9124852/116844169-a95ace00-ac25-11eb-969b-58770d8bd718.png)

Steps to Reproduce:

1. add these key value pairs to vscode settings.json
```
    "git.inputValidationSubjectLength": 100,
    "git.inputValidationLength": 100
```
2. set command line editor value to use vscode in wait mode. Add to your shell initialising file (~/.zshrc ~/.bashrc)
```
export EDITOR="code --wait"
```

3. using command line `cd` into a git repository, apply some changes and run `git commit`

4. attempt to write a subject with 100 characters length.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
The settings ("git.inputValidationSubjectLength", "git.inputValidationLength") control the validation that is implemented in the commit input field in the Source Control view. These settings are not being used when the commit message is being written using the editor itself. What you should see in the editor is a ruler that is being set at 72 characters which you can use when authoring the commit message.

Hope this helps. I will go ahead and close this issue but please feel free to reopen it in case you still have some questions.
