### ISSUE TITLE
"Find in folder" doesn't work when workspace root folder has a slash in his name.

### ISSUE THREAD

**Issue by edupsousa** [microsoft/vscode#122874]
- VS Code Version: 1.56-0-insider
- OS Version:Linux Mint 20.01

Steps to Reproduce:

1. Create and save a new workspace.
2. Add a folder to the workspace (eg: my-project).
3. Go to .code-workspace file and set a name with slash (/) for the folder (eg: {"name": "mycompany/my-project", "path": "./my-project"}.
4. Right click the renamed root folder on Explorer and click on "Find in folder..."
5. "Files to include" field will show a relative path with the folder name set in workspace file (eg ./mycompany/my-project).
5. Type some search term.
6. Error "Workspace folder does not exist" is displayed.

I tracked the error to the line https://github.com/microsoft/vscode/blob/486072c4a016a432b80ed7c5c913dd9ad70954b0/src/vs/workbench/contrib/search/common/queryBuilder.ts#L420 where the const searchPathRoot is set to the first part of the "files to include" relative path (eg mycompany) and the subsequent call to this.workspaceContextService.getWorkspace().folders.filter cant match the folder name from the searchPathRoot.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/99512
