### ISSUE TITLE
Incorrect variable expansion for saved workspaces

### ISSUE THREAD

**Issue by Suven-p** [microsoft/vscode#122829]
- Version: 1.55.2
- Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
- Date: 2021-04-13T09:37:02.931Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Linux x64 5.4.0-72-generic (Ubuntu 20.04.2)

Steps to Reproduce:

1. Add new user snippet such as:
`"test_snippet": {
		"prefix": "test",
		"body": [
			"$WORKSPACE_FOLDER"
		]
	}
` 
to a workspace say "\~/test_project"
Currently "test" expands to absolute path to "\~/test_project".
2. Save workspace in another directory and relaunch vs code. (`code --disable-extensions ~/Desktop/workspace.code-workspace`). Now "test" expands to absolute path of "*.code-workspace" file ie `~/Desktop` instead of `~/test_project`.

 
Does this issue occur when all extensions are disabled?: Yes

**Comment by Suven-p** [comment]
On further digging, I think this might be the intended bahaviour? sourcing [here](https://github.com/microsoft/vscode/blob/62736de465c6091c2f516610f533bbc8e26b291f/src/vs/editor/contrib/snippet/snippetVariables.ts#L303), [here](https://github.com/microsoft/vscode/blob/62736de465c6091c2f516610f533bbc8e26b291f/src/vs/platform/workspaces/common/workspaces.ts#L150) and [here](https://github.com/microsoft/vscode/blob/62736de465c6091c2f516610f533bbc8e26b291f/src/vs/editor/contrib/snippet/snippetVariables.ts#L328)

If so could it be handled like ${workspaceFolder} for build tasks? Assuming [this answer](https://stackoverflow.com/a/58853570/10168590) is correct.

**Comment by jrieken** [comment]
> If so could it be handled like ${workspaceFolder} for build tasks?

I don't know what that means. Can you explain the differences?

**Comment by Suven-p** [comment]
It uses the first folder from the list of folders on the workspace by default.

**Comment by Suven-p** [comment]
I think that might be a problem for [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file) but don't have much experience with them.
