### ISSUE TITLE
Notebook: Unicode notebook does not render unicode text

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#122875]
Issue Type: <b>Bug</b>

A really large notebook 100MB does not scroll properly after opening.

![image](https://user-images.githubusercontent.com/19672699/116931322-b5d72a80-ac15-11eb-9a94-74d0a7156742.png)

Actually it looks like the notebook has unicode text in it. After a refresh I got this in the blank locations:

![image](https://user-images.githubusercontent.com/19672699/116931428-d0110880-ac15-11eb-8ba3-d696d0fdc639.png)

VS Code version: Code - Insiders 1.56.0-insider (4e185d8986339717e593be19bc75288905ffbb51, 2021-05-01T00:27:57.510Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (14.39GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
prettier-vscode|esb|6.3.2
python|ms-|2021.5.796837427-dev
vscode-pylance|ms-|2021.4.3
jupyter|ms-|2021.6.807730802
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehov:30295781

```

</details>

**Comment by rebornix** [comment]
@rchiodo can you please share the notebook?

**Comment by rchiodo** [comment]
It's really large. Do you want me to just message you directly?
