### ISSUE TITLE
Feature request: Sort NuGet package versions in descending order

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode#12285]
- VSCode Version: 1.5.2
- OS Version: Windows and Ubuntu, at least :)

Steps to Reproduce:

1. While editing `project.json` for a .NET project, start adding a dependency to an existing NuGet package
2. When about to enter a version number, hit ctrl+space to bring up a list of versions

It would be much more helpful if that list of versions was sorted in *descending* order, so that it's easy to find the latest version of the package.

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository. https://github.com/OmniSharp/omnisharp-vscode/issues
