### ISSUE TITLE
vscode.workspace.applyEdit applies edit to wrong document

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#122883]
Version: 1.56.0-insider (user setup)
Commit: 4e185d8986339717e593be19bc75288905ffbb51
Date: 2021-05-01T00:27:57.510Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Install the Live Share extension
2. Share a folder with two empty files, a.txt and b.txt
3. Modify a.txt's contents to 'abcd'. Don't save.
4. Modify b.txt's contents to 'efgh'. Don't save.
5. Join the session from another instance (this is the instance to debug)

![repro](https://user-images.githubusercontent.com/6383490/116943617-cf35a200-ac28-11eb-8671-00cb2f129f84.gif)

Expected:
a's edits are applied to a.txt and b's edits are applied to b.txt.

Actual:
Edits intended for b.txt are applied to a.txt.

Here are some logs:
```
vscode.workspace.applyEdit:  [
  [
    {
      "$mid": 1,
      "external": "vsls:/b.txt",
      "path": "/b.txt",
      "scheme": "vsls"
    },
    [
      {
        "range": [
          {
            "line": 0,
            "character": 0
          },
          {
            "line": 0,
            "character": 0
          }
        ],
        "newText": "e"
      }
    ]
  ]
]

vscode.workspace.applyEdit:  [
  [
    {
      "$mid": 1,
      "external": "vsls:/a.txt",
      "path": "/a.txt",
      "scheme": "vsls"
    },
    [
      {
        "range": [
          {
            "line": 0,
            "character": 0
          },
          {
            "line": 0,
            "character": 0
          }
        ],
        "newText": "a"
      }
    ]
  ]
]

ERR Error: vsls:/a.txt has changed in the meantime
  at u._validateBeforePrepare (bulkTextEdits.ts:165)
  at u.apply (bulkTextEdits.ts:224)
  at r._performTextEdits (bulkEditService.ts:103)
  at r.perform (bulkEditService.ts:84)
  at s.apply (bulkEditService.ts:199)
  at T.$tryApplyWorkspaceEdit (mainThreadBulkEdits.ts:22)
  at s._doInvokeHandler (rpcProtocol.ts:417)
  at s._invokeHandler (rpcProtocol.ts:402)
  at s._receiveRequest (rpcProtocol.ts:318)
  at s._receiveOneMessage (rpcProtocol.ts:245)
  at rpcProtocol.ts:110
  at c.fire (event.ts:622)
  at o.fire (ipc.net.ts:468)
  at i._receiveMessage (ipc.net.ts:821)
  at ipc.net.ts:660
  at c.fire (event.ts:622)
  at u.acceptChunk (ipc.net.ts:241)
  at ipc.net.ts:202
  at Socket.k (ipc.net.ts:50)
  at Socket.emit (events.js:315)
  at addChunk (_stream_readable.js:295)
  at readableAddChunk (_stream_readable.js:271)
  at Socket.Readable.push (_stream_readable.js:212)
  at Pipe.onStreamRead (internal/stream_base_commons.js:186)

onDidChangeTextDocument:  {
  "document": {
    "uri": {
      "$mid": 1,
      "fsPath": "\\a.txt",
      "_sep": 1,
      "external": "vsls:/a.txt",
      "path": "/a.txt",
      "scheme": "vsls"
    },
    "fileName": "\\a.txt",
    "isUntitled": false,
    "languageId": "plaintext",
    "version": 2,
    "isClosed": false,
    "isDirty": false,
    "eol": 2,
    "lineCount": 1
  },
  "contentChanges": [
    {
      "range": [
        {
          "line": 0,
          "character": 0
        },
        {
          "line": 0,
          "character": 0
        }
      ],
      "rangeOffset": 0,
      "rangeLength": 0,
      "text": "e"
    }
  ]
}

Done applying edit to  /b.txt . Result:  true

Done applying edit to  /a.txt . Result:  false
```

As you can see, two requests to `vscode.workspace.applyEdit` are issued in parallel and seem to get crossed up.

I've tried to reproduce this with a minimal sample extension but I'm not able to. So there's some more complex interaction here than simply making parallel requests to `vscode.workspace.applyEdit`. But I hope you'll agree this behavior is concerning enough to take a look without a minimal sample extension. I think you'll be able to make much quicker progress by observing what's going on at the renderer level than I will trying to figure out the necessary things to make this repro.

**Comment by jrieken** [comment]
> I've tried to reproduce this with a minimal sample extension but I'm not able to. So there's some more complex interaction here than simply making parallel requests to vscode.workspace.applyEdit. But I hope you'll agree this behavior is concerning enough to take a look without a minimal sample extension. I

I think you can help us here: 

* run vscode out of source (see https://github.com/microsoft/vscode/wiki/How-to-Contribute)
* and debug into [`BulkEditService#apply`](https://github.com/microsoft/vscode/blob/98b4661b0026e8b2f069d9ea5954b4b5599f0b8c/src/vs/workbench/contrib/bulkEdit/browser/bulkEditService.ts#L141)

That should enable you to craft a minimal repo or understand the issue better

**Comment by daytonellwanger** [comment]
Still no minimal repro, but I have more confidence that this is actually a VS Code bug and think I can help point you to the issue.

It looks like there are two ways an edit can make it from `vscode.workspace.applyEdit` to being applied - with a `ModelEditTask` and with a `EditorEditTask`. Call stacks for both paths are below with `*`s where the stacks are different and `(LOG)` where I put debugging logs. You can see exactly where I added logging statements in [this commit](https://github.com/daytonellwanger/vscode/commit/dcf4e5c350518c5a1957ac566ec54579758886cc).

`ModelEditTask` call stack:
```
TextModel._doApplyEdits (LOG)
TextModel.applyEdits
EditStack.pushEditOperation
TextModel._pushEditOperations
TextModel.pushEditOperation
*ModelEditTask.apply
    *Task is created
BulkTextEdits.apply
BulkEdit._performTextEdits
BulkEdit.perform
BulkEditService.apply
MainThreadBulkEdits.$tryApplyWorkspaceEdit (LOG)
```

`EditorEditTask` call stack:
```
TextModel._doApplyEdits (LOG)
TextModel.applyEdits
EditStack.pushEditOperation
TextModel._pushEditOperations
TextModel.pushEditOperation
*Cursor.executeEdits
*...
*ViewModel._executeCursorEdit
*ViewModel.executeEdits
*CodeEditorWidget.executeEdits
*EditorEditTask.apply (LOG)
    *Task is created (LOG)
BulkTextEdits.apply
BulkEdit._performTextEdits
BulkEdit.perform
BulkEditService.apply
MainThreadBulkEdits.$tryApplyWorkspaceEdit (LOG)
```

I believe the issue only occurs with `EditorEditTask`s. It appears that the editor reference is changed between the time the `EditorEditTask` is created [here](https://github.com/microsoft/vscode/blob/a07fdad46731573a5b4483fa5f4bbecca79a582c/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L182) and when the task is applied [here](https://github.com/microsoft/vscode/blob/a07fdad46731573a5b4483fa5f4bbecca79a582c/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L119). I.e. between the two consecutive LOGs in the `EditorEditTask` call stack. I don't know what is responsible for the reference being changed, but it seems to me like it's a bug.

Here are four sample runs (the output of the logging statements in the above linked commit when running through the repro in the original post), two that complete successfully and two that exhibit the bug. Note this repro is intermittent. In my experience, it repros about 50% of the time when under a debugger. It's more consistent outside of a debugger. It's almost certainly a timing issue.

Successful runs (final text for a.txt of 'abcd', final text for b.txt of 'efgh'):
```
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'e' to /b.txt
TextModel._doApplyEdits 'e' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'f' to /b.txt
TextModel._doApplyEdits 'f' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'a' to /a.txt
Creating EditorEditTask to apply 'g' to /b.txt
TextModel._doApplyEdits 'a' to /a.txt
EditorEditTask.apply 'g' to /b.txt
TextModel._doApplyEdits 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'b' to /a.txt
TextModel._doApplyEdits 'b' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'h' to /b.txt
Creating EditorEditTask to apply 'h' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'c' to /a.txt
TextModel._doApplyEdits 'c' to /a.txt
EditorEditTask.apply 'h' to /b.txt
TextModel._doApplyEdits 'h' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'd' to /a.txt
TextModel._doApplyEdits 'd' to /a.txt
```

```
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'e' to /b.txt
TextModel._doApplyEdits 'e' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'f' to /b.txt
Creating EditorEditTask to apply 'f' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'a' to /a.txt
TextModel._doApplyEdits 'a' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'b' to /a.txt
TextModel._doApplyEdits 'b' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'c' to /a.txt
TextModel._doApplyEdits 'c' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'd' to /a.txt
TextModel._doApplyEdits 'd' to /a.txt
EditorEditTask.apply 'f' to /b.txt
TextModel._doApplyEdits 'f' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'g' to /b.txt
Creating EditorEditTask to apply 'g' to /b.txt
EditorEditTask.apply 'g' to /b.txt
TextModel._doApplyEdits 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'h' to /b.txt
Creating EditorEditTask to apply 'h' to /b.txt
EditorEditTask.apply 'h' to /b.txt
TextModel._doApplyEdits 'h' to /b.txt
```

Failed Run 1 (final text for a.txt of 'eabcd', final text for b.txt of 'fgh') (`***`s indicate where the issue occurred):
```
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'a' to /a.txt
TextModel._doApplyEdits 'a' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'b' to /a.txt
TextModel._doApplyEdits 'b' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'c' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'e' to /b.txt
***Creating EditorEditTask to apply 'e' to /b.txt***
TextModel._doApplyEdits 'c' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'd' to /a.txt
TextModel._doApplyEdits 'd' to /a.txt
***EditorEditTask.apply 'e' to /a.txt***
***TextModel._doApplyEdits 'e' to /a.txt***
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'f' to /b.txt
TextModel._doApplyEdits 'f' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'g' to /b.txt
TextModel._doApplyEdits 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'h' to /b.txt
TextModel._doApplyEdits 'h' to /b.txt
```

Failed Run 2 (final text for a.txt of 'bcd', final text for b.txt of 'aefgh') (`***`s indicate where the issue occurred):
```
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'e' to /b.txt
TextModel._doApplyEdits 'e' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'f' to /b.txt
TextModel._doApplyEdits 'f' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'a' to /a.txt
***Creating EditorEditTask to apply 'a' to /a.txt***
TextModel._doApplyEdits 'g' to /b.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'h' to /b.txt
TextModel._doApplyEdits 'h' to /b.txt
***EditorEditTask.apply 'a' to /b.txt***
***TextModel._doApplyEdits 'a' to /b.txt***
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'b' to /a.txt
TextModel._doApplyEdits 'b' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'c' to /a.txt
TextModel._doApplyEdits 'c' to /a.txt
MainThreadBulkEdits.$tryApplyWorkspaceEdit 'd' to /a.txt
TextModel._doApplyEdits 'd' to /a.txt
```

Let me know if it still feels unclear whether or not this is a bug in VS Code or in the Live Share extension.

**Comment by jrieken** [comment]
@daytonellwanger Thanks for drilling so deep into this. I don't know yet what the issue is but I do have a theory...

> It appears that the editor reference is changed between the time the EditorEditTask is created here and when the task is applied here

The editor-reference cannot change but the editor might be set to a different model in the meantime. That would explain this. We do the following: for each file in an edit we create a `ModelEditTask` or an `EditorEditTask`. The latter is for files that are currently visible in an editor - it is better to use an editor for the edit because it makes sure selections and decorations stay stable. However, creating these tasks is async and it might well be that the editor that was for file A ([checked here](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L181) is now for file B. We don't check that again and are trusting the results from the "async old" check. I have no repro case but starring at the code makes this so obvious that I wonder how we have shipped this since years.


One question: When looking at your logs I sometimes see `MainThreadBulkEdits.$tryApplyWorkspaceEdit` repeated (two in a row) This tells me that your extension isn't waiting for `vscode.workspace.applyEdit` to finish before doing the next, right? It is OK that you do it like that but it would explain why you see this "sometimes"

**Comment by jrieken** [comment]
I have pushed a fix for the `EditorEditTask` confusion which became so obvious now. I do admit that I have no tests, but my confidence level is high. So please give this another try and let me know if you can still see this (last next insiders or from source).

**Comment by daytonellwanger** [comment]
Thanks for the quick turn-around! Confirmed that this is fixed on latest insiders 🎉

> One question: When looking at your logs I sometimes see MainThreadBulkEdits.$tryApplyWorkspaceEdit repeated (two in a row) This tells me that your extension isn't waiting for vscode.workspace.applyEdit to finish before doing the next, right?

We queue edits per document so they happen one at a time. But if edits are going to different documents, they can happen in parallel.

**Comment by jrieken** [comment]
Thanks for the update. Astonishing bug. We must have had this issue for years
