### ISSUE TITLE
Indentation bug

### ISSUE THREAD

**Issue by psmindmatch** [microsoft/vscode#122840]
Issue Type: <b>Bug</b>

On my VS code the indentation is nice.
But when pushing on github it's not indented properly.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.8.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2399)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|3.70GB (0.20GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 69e94f2a-2382-472d-8fc7-294568aa2804|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by psmindmatch** [comment]
![Screenshot from 2021-05-03 15-01-18](https://user-images.githubusercontent.com/82959751/116864557-abbd2800-ac25-11eb-821e-7c798f943438.png)
![Screenshot from 2021-05-03 15-01-08](https://user-images.githubusercontent.com/82959751/116864566-af50af00-ac25-11eb-9479-2909e7e4aac1.png)

**Comment by rebornix** [comment]
> On my VS code the indentation is nice.
But when pushing on github it's not indented properly.

Thanks but I don't think this is a VS Code issue then.
