### ISSUE TITLE
Clicking the building status bar item requires an extra step

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#122868]
With terminal tabs enabled and all the build tasks in one split terminal group, this quick pick seems in the way to me:

![image](https://user-images.githubusercontent.com/6561887/116922363-1d877880-ac0a-11eb-8be8-cda34085b537.png)

I'd rather you just open the split terminal and I can click the one I want. It's the same number of clicks in the worst case, and one less in the frequent case (reading the output only which doesn't require selection anymore).

**Comment by Tyriar** [comment]
Makes sense to me since the command is _show_, not _focus_, focus goes to the editor.
