### ISSUE TITLE
Option to change default behavior of cursorHome and cursorEnd

### ISSUE THREAD

**Issue by Bill-Stewart** [microsoft/vscode#12287]
Currently (1) `cursorHome` command moves to the first non-whitespace character on the current line, and (2) `cursorEnd` moves to the last non-whitespace character on the current line.

I would like if there was an option that would disable behavior (1) and always move cursor to column 1 (i.e., the actual beginning of the line). This same option could change behavior (2) and always move cursor to end of current line past all whitespace, if any (i.e., the actual end of the line).

**Comment by Pouja** [comment]
@alexandrudima is this a feature of a bug. If it is a bug then [getColumnAtBeginningOfLine](https://github.com/Microsoft/vscode/blob/8e562d6df405a9e136e3d26930515fdcfbd6bb13/src/vs/editor/common/controller/cursorMoveHelper.ts#L196) can be changed, otherwise an extra parameter should be added (I think) through the whole rabbit hole starting in [cursor.ts](https://github.com/Microsoft/vscode/blob/3fc1538d2856fb27bb29ae9cc6dc6d2134f24a6f/src/vs/editor/common/controller/cursor.ts#L963)

**Comment by Bill-Stewart** [comment]
@Pouja - would you benefit from such an option as well?

**Comment by Pouja** [comment]
@Bill-Stewart Yeah I also want to be able to go to the first column instead of the first nonwhitespace column

**Comment by alexandrudima** [comment]
I plan to add args support to keybindings.json such that we can have this be customizable through `keybindings.json`. e.g.

```
{ "key": "home", "command":"cursorMove", "args": { "to": "hard-start-of-line" } 
```

or something along those lines

**Comment by Bill-Stewart** [comment]
This is good! However: certain use cases still use the default behavior. 1) For example, `editorScroll` command--with `revealCursor` parameter set to `true`--still uses default `cursorHome` command (or at least, it behaves as if this is what it is doing). Also, 2) an editor option to ignore whitespace would be more logical, in my opinion, because an editor option changes some default editor behavior, and is more simple and sensible than creating new keymappings.

**Comment by joenoon** [comment]
I'm also interested in this.  It's the only thing that keeps me from using vscode.  Linking prior issue: https://github.com/Microsoft/vscode/issues/7229

**Comment by Bill-Stewart** [comment]
Hi @joenoon - you can work around this for now by installing an extension I wrote:

https://marketplace.visualstudio.com/items?itemName=BillStewart.extended-cursormove

**Comment by joenoon** [comment]
@Bill-Stewart amazing, thanks! working perfectly - exactly what I needed.  In addition to your keybindings.json example I also added this one:

```
  { "key": "cmd+left",   "command": "extension.extendedCursorMove.cursorHome",       "when": "editorTextFocus" },
```

**Comment by alexandrudima** [comment]
There is a good working extension filling this gap => closing this issue.
