### ISSUE TITLE
Explorer jumps back to open files folder after closing a file in another folder

### ISSUE THREAD

**Issue by imsam67** [microsoft/vscode#122815]
- VS Code Version: 1.55.2
- OS Version: Windows 10 Pro 20H2 Build 19042.964

Steps to Reproduce:

1. Have several folders in your project folder/workspace. Say, folderA, folderB, folderC, folderD, etc. The more folders you have, the easier it will be to notice this behavior because VS Code will perform a more Olympic jump!
2. Make sure you have one or two files that you can open and edit in folderA and at least one file in your bottom folder. It can be any type of file or even an empty one.
3. Go to your bottom folder and open the file as if you're editing it and make sure you leave it open
4. Then scroll up in your explorer to your folderA or whatever your top folder maybe and open one of the files there as if you're editing or just reviewing it.
5. When you close that file in folderA,  you'll notice that explorer will perform its Olympic jump down to the bottom folder where the file you opened in step 3.

This is pretty annoying if you wanted to actually keep investigating files in folderA or your top folder because you now have to first scroll back up to that folder and then find the file you wanted to investigate.

The explorer should NOT make decisions on my behalf and stay where it is until I decide to scroll up or down.

Does this issue occur when all extensions are disabled?: Yes, it does!

**Comment by gjsjohnmurray** [comment]
Take a look at the `explorer.autoReveal` setting.

**Comment by imsam67** [comment]
Thank you! Maybe I'm in the minority here but wouldn't it be better if this setting was set to `false` by default.
