### ISSUE TITLE
VS keeps compiling

### ISSUE THREAD

**Issue by lmolteni** [microsoft/vscode#122864]
Issue Type: <b>Bug</b>

My terminal keeps compilign arbitrary, i am not saving documents, even i am not touching VS and suddenly starts compiling irself

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 9|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id ad7b6f93-f5ac-46da-854e-87b2ab765aab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.12
atlascode|atl|2.8.6
codestream|Cod|11.0.5
vscode-eslint|dba|2.1.20
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
csharp|ms-|1.23.11
mssql|ms-|1.10.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.2.0
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.18.0
vsfire|tob|1.4.1
gitblame|wad|6.0.2
zeplin|Zep|2.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
vstes627:30244334
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by lmolteni** [comment]
All those compilings you can see in the terminal where fired by them self, i didnt save any change, the aplication keeps compiling even if i dont touch the visual studio

<img width="937" alt="Screen Shot 2021-05-06 at 15 24 30" src="https://user-images.githubusercontent.com/66335723/117347221-33ea3a00-ae7f-11eb-9c03-bdf1091f1a22.png">
<img width="425" alt="Screen Shot 2021-05-06 at 15 24 18" src="https://user-images.githubusercontent.com/66335723/117347233-377dc100-ae7f-11eb-97d2-093a469c257b.png">

**Comment by meganrogge** [comment]
what happens if you kill the terminal?

**Comment by lmolteni** [comment]
Its the same. I kill it and re run the app and the auto compiling start over again

**Comment by Tyriar** [comment]
This isn't anything to do with the terminal, the terminal is just running your compiler, something else is probably touching some file(s) in the folder or you have your watcher configured incorrectly.
