### ISSUE TITLE
Quick pick does not select first item for smoke test

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122850]
Only the smoke test caught this, I could not repro.

1. Linux, run smoke tests
2. Notice that when the quick pick only has one element it is not focused 
3. This makes the smoke test fail

Quick pick should always move focus to the first item.

![Screenshot 2021-05-03 at 14 24 56](https://user-images.githubusercontent.com/1926584/116875521-5b40cd00-ac1b-11eb-95ca-9453c943f63d.png)

**Comment by chrmarti** [comment]
@isidorn Any chance screenreader mode was enabled?

**Comment by isidorn** [comment]
@chrmarti yeah there's a good chance that happened.
Remind me, why do we behave different here if there was a screen reader?

**Comment by chrmarti** [comment]
@isidorn NVDA did not read the placeholder when we selected an item: https://github.com/microsoft/vscode/issues/57501

**Comment by isidorn** [comment]
@chrmarti okey. If that issue is still happening with latest VS Code (maybe we should double check) it makes sense to keep this work around.

**Comment by TylerLeonhardt** [comment]
>  If that issue is still happening with latest VS Code (maybe we should double check) it makes sense to keep this work around.

This is still true, unfortunately.

**Comment by TylerLeonhardt** [comment]
Althogh we may get closer to that goal in #122546 ... with that said, I think the assumption we should have for the smoke tests is that they run with A11y mode off.

**Comment by isidorn** [comment]
Feel free to close as far as I am concerned.
