### ISSUE TITLE
Exception printed when using <webview> based webviews

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#122818]
**Repro**
1. Make sure you don't have `"webview.experimental.useIframes"` set
2. Open a markdown preview
3. Run the `Open webview developer tools command`

**Bug**
In the console see an error about not being able to assign to `onbeforeunload`

This is caused by the workaround added in #122736. `<Webview>` based webviews have some [special code](https://github.com/microsoft/vscode/blob/069f8f39591e856872a55af9691da19ed51e847a/src/vs/workbench/contrib/webview/electron-browser/pre/index.html#L15) that tries to write this property

**Comment by mjbvz** [comment]
To verify:

1. Test the steps listed above and make sure there is not exception
2. Now open an image editor (which uses an iframe by default) and verify that there is no exception in the main developer tools (`Developer: Toggle developer tools`)
1. Now re-verify the steps listed in https://github.com/microsoft/vscode/issues/122736#issuecomment-830328364 to make sure we didn't regress it

**Comment by rzhao271** [comment]
I followed the steps here: https://github.com/microsoft/vscode/issues/122818#issuecomment-830863694
For the third step, I followed the steps here: https://github.com/microsoft/vscode/issues/122736#issuecomment-830328364, but nothing happened after I tried reloading the webview. Is that the expected behaviour?

**Comment by mjbvz** [comment]
@rzhao271 Nothing as in nothing happened and the window wasn't reloaded or you don't see the errors?

**Comment by rzhao271** [comment]
I read the last step as "try to reload the webview" rather than "try to reload the window".
That was embarrassing.
The window reloaded properly.
