### ISSUE TITLE
Error when Updating/Installing Extension: Response doesn't appear to be JSON

### ISSUE THREAD

**Issue by DaveyD** [Microsoft/vscode#12286]
- VSCode Version: 1.5.2
- OS Version: Windows 10 Pro 64bit

1. When I open VScode, it shows me that I have 3 outdated extensions. 
2. I go into the extensions panel and click on "Update" button.
3. I get the error: Response doesn't appear to be JSON
![screenshot_402](https://cloud.githubusercontent.com/assets/12707785/18648746/00a1d2c2-7e8a-11e6-9680-ffd52f9eb814.png)

What does this mean? How can I fix it?
I am behind a proxy, but it doesnt seem to be the problem because I am able to browse the available extensions, and VScode can successfully connect to tell me which one's are outdated.

Thanks,
David

**Comment by joaomoreno** [comment]
@DaveyD Can you tell me the extension that causes this error?

**Comment by DaveyD** [comment]
@joaomoreno - Thanks. 
The problem was with every extension and theme.
However, I just realized this morning that the cause was my proxy because it was blocking vsassets.io. Once I had them unblock that, everything began to work perfectly.

Does that make sense? (In any case, it's working now... I guess this can be closed?)

Thanks,
David

**Comment by joaomoreno** [comment]
Thanks for letting me know.
