### ISSUE TITLE
Cells aren't highlighted when revealing in outline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122890]
- Open a notebook
- Open the outline and use arrow keys
- Cells are revealed when selected in the outline but previously they got a yellow bg highlight, now there is no highlight

Maybe related to https://github.com/microsoft/vscode/issues/122720 somehow

**Comment by jrieken** [comment]
> Cells are revealed when selected in the outline but previously they got a yellow bg highlight, now there is no highlight

Only quick outline and breadcrumbs do that. The outline view doesn't do this - afaik never did. @roblourens what which outline do you mean? view or quick?

**Comment by roblourens** [comment]
Quick outline and breadcrumbs. Today I see that I get the background highlight on code cells but not markdown cells. I don't know whether that is different.

**Comment by jrieken** [comment]
> Quick outline and breadcrumbs. Today I see that I get the background highlight on code cells but not markdown cells. 

Yeah, I am also seeing that (and have files a dupe issue ;-))

**Comment by rebornix** [comment]
I think it's an issue with the custom markdown renderer. I fixed this before but not sure why it regressed now.

**Comment by rebornix** [comment]
it's the Shadow DOM :)
