### ISSUE TITLE
Add-PnPPage error within Visual Studio Code but not PowerShell ISE or *.ps1 script

### ISSUE THREAD

**Issue by CEStar** [microsoft/vscode#122853]
Hi 

I get an error message whenever I use Add-PnPPage. All the other PnP commands I use like Connect-PnPOnline, Get-PnPListItem, or Add-PnPHubSiteAssociation work perfectly except Add-PnPPage. The Add-PnPPage error message appears within Visual Studio Code but not PowerShell ISE. It also works perfectly when run as a *.ps1 script.

Error message:
##########################

```
Add-PnPPage : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.      
At C:\Users\User***\Desktop\Downloads\Project Scripts\3) CreateProjectSite\B3LCreateProjectSite.ps1:330 char:17
+ ...             Add-PnPPage -Name $siteTitleNoSpaces -LayoutType Home -Co ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPPage], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.AddPage
```

#########################

I hope you can help.

Many thanks
Colin

**Comment by Tyriar** [comment]
@TylerLeonhardt any insights on pwsh side? Not sure this is our problem

**Comment by TylerLeonhardt** [comment]
@CEStar looks like our bot found the issue you opened before of the same issue. Please take a look at that one:
https://github.com/microsoft/vscode/issues/120026

/duplicate 120026
