### ISSUE TITLE
--install-extension from does no show correct extension version

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#122817]
- Have VSCode 1.55
```
C:\Users\martinae>code --install-extension ms-vscode-remote.remote-wsl
Installing extensions...
Installing extension 'ms-vscode-remote.remote-wsl' v0.56.0...
```

- that's strange as 0.56.0 requires vscode 1.56

- open VSCode and check the extensions viewlet. The correct extension version (0.54.6) got installed.
- all fine, just looks like the install message is just not correct

_Originally posted by @aeschli in https://github.com/microsoft/vscode-remote-release/issues/4918#issuecomment-824880399_

**Comment by sandy081** [comment]
Fixed not to show the version while installing and version is shown after installed.

```
Installing extension 'ms-vscode-remote.remote-wsl'...
Extension 'ms-vscode-remote.remote-wsl' v0.56.4 was successfully installed.
```
