### ISSUE TITLE
Cannot send events as part of extension deactivation

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#122825]
If extensions send events as part of deactivate, awaiting disposal of the telemetry reporter exceeds the 4s shutdown limit for extensions, so these events aren't sent.

Repro extension: [repro.zip](https://github.com/microsoft/vscode-extension-telemetry/files/6250626/repro.zip)

extension.ts:
```
import * as vscode from 'vscode';
import * as fs from 'fs';
import TelemetryReporter from 'vscode-extension-telemetry';

let reporter: TelemetryReporter;
let sendEventOnDispose = true;

export function activate(context: vscode.ExtensionContext) {
	reporter = new TelemetryReporter('extension', '0.0.0', 'my-key');
}

export async function deactivate() {
	fs.writeFileSync('/start.txt', ''); 
	if (sendEventOnDispose) {
		reporter.sendTelemetryEvent('event');
	}
	await reporter.dispose();
	fs.writeFileSync('/end.txt', ''); 
}
```

If `sendEventOnDispose` is `true`, the extension never completes deactivating (end.txt isn't created). If `sendEventOnDispose` is `false`, deactivation completes.

**Comment by daytonellwanger** [comment]
> I'll take a look next milestone assuming this is not a regression.

I think this is a regression from some point in time, though not in the last few months.

It's also a blocker for us (the Live Share extension) collecting critical telemetry.

**Comment by chrmarti** [comment]
@alexdima (As discussed) Looked into this and couldn't find a way for proxyResolver.ts to check if it can still call the renderer or not. An error on an unsuccessful call would also make sense. rpcProtocol.ts would throw an error if it was disposed, but I don't see it getting disposed.

**Comment by rzhao271** [comment]
Labelling as verified for now after discussing with @daytonellwanger.
