### ISSUE TITLE
Wired error in Problems window

### ISSUE THREAD

**Issue by CorrM** [microsoft/vscode#122849]
Issue Type: <b>Bug</b>

file: 'plugin-item.component.ts' was there but i renamed it
but the error still there, for real i think the problem comes from `Angular Language Service` but it's good to report here.

![image](https://user-images.githubusercontent.com/5868825/116875954-081b4a00-ac1c-11eb-8491-abe70761bb64.png)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by jrieken** [comment]
> , for real i think the problem comes from Angular Language Service but it's good to report here.

We show whatever the language services tell us to show
