### ISSUE TITLE
window.showTextDocument Performance Problems

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode#12280]
- VSCode Version: 1.5.2
- OS Version: OSX 10.11.6

Steps to Reproduce:
1. Show a text document
2. With that document still in focus, attempt to call showTextDocument with the document object.

window.showTextDocument seems to have performance problems (1-1.5 second promise resolve) when calling it with a document that is already in focus.

Calling showTextDocument on a document that is open but not in focus for one of the editor windows does not show this performance problem.

Edit: Clarification: This seems to be a performance problem specifically for the promise resolving. You can visually see the window come into focus in a reasonable amount of time, but the promise resolving with the editor object is greatly delayed.

**Comment by jrieken** [comment]
Could be due to [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadEditors.ts#L206)

**Comment by anthonydresser** [comment]
I was looking at this when debugging the problem, however, the vscode debugger for extensions doesn't work perfectly when it starts to dig into the vscode code. One work around I was thinking of that I couldn't find a way to do, is simply check if the file is currently showing in one of the editor windows. However it appears the only related call is the getter for activetexteditor, but this only gives you the active editor for the current window in focus. 

Is there a way to get the active editors for all the open windows? I.E can you get the editor that is currently open in the other windows when you have 2 or 3 files open side by side?

**Comment by alexandrudima** [comment]
I think `visibleEditors` gives all the ones that are visible. But that one has the problem that it is lacking an event.

**Comment by anthonydresser** [comment]
It seems checking `visibleEditors` works around the problem. Thanks for the reference.

**Comment by DanTup** [comment]
This problem affects Dart Code - I was going to try and implement this workaround, but the `show` method on `TextEditor` is marked as deprecated:

```ts
* @deprecated **This method is deprecated.**
* Use window.showTextDocument instead. This method shows unexpected behavior and will be removed in the next major update.
```

Is there any other workaround for this that won't break in an upcoming update?

**Comment by jrieken** [comment]
> window.showTextDocument seems to have performance problems (1-1.5 second promise resolve) when calling it with a document that is already in focus.

@anthonydresser @DanTup Is opening the same document in the same editor column (basically a no-op) the slow case or when opening the same document in another column?

**Comment by DanTup** [comment]
@jrieken The no-op scenario is slow too. Our code is like this:

```ts
vs.workspace.openTextDocument(location.file).then(document => {
	vs.window.showTextDocument(document).then(editor => {
		let range = toRange(location);
		editor.revealRange(range, vs.TextEditorRevealType.InCenterIfOutsideViewport);
		editor.selection = new vs.Selection(range.end, range.start);
	});
});
```

We open the document then need the editor so that we can jump to the correct place. Even when everything is in one file there's a second delay between this code executing and the selection moving (inside the same file).

**Comment by jrieken** [comment]
Understood. The 1 second might come from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadEditors.ts#L194) but I was assuming `openEditor` returns the editor when it's already open...

**Comment by jrieken** [comment]
Actually, this should be easy to fix

**Comment by DanTup** [comment]
Great! Let me know if you'd like me to test with our code once it's in Insiders.

**Comment by jrieken** [comment]
Thanks - should be in insiders on Monday

**Comment by DanTup** [comment]
@jrieken this is working great in Insiders now, it's instant with no delay 👍

**Comment by ramya-rao-a** [comment]
Marking as verified as per @DanTup's confirmation
