### ISSUE TITLE
Parcel npm package isn't working in vs code

### ISSUE THREAD

**Issue by SR-22** [microsoft/vscode#122809]
Version: 1.55.2 (user setup)
OS: Windows_NT x64 10.0.19042

Hello VS code team,
I am having some trouble with parcel npm package and that's giving me a headache now seriously. It wells tells the installation failed  and then nothing happens. Please fix this problem

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please clarify steps to reproduce and how this problem related to VS Code itself.

Does it work outside of VS Code?

**Comment by SR-22** [comment]
> /needsMoreInfo
> 
> Please clarify steps to reproduce and how this problem related to VS Code itself.
> 
> Does it work outside of VS Code?

I tried in windows powershell and got the same result

**Comment by SR-22** [comment]
I realized that it works in cmd not the powershell terminal
