### ISSUE TITLE
No debugger available, can not send 'variables'

### ISSUE THREAD

**Issue by SiddharthReddyThudi** [microsoft/vscode#122821]
### **_ERROR: No debugger available, can not send 'variables'_**

- VS Code Version: latest
- OS Version: latest

I just started to learn Html5 CSS3 and JS.
I installed NODE JS and wrote a sample HTML and tried to run debugger using NODE.js.
In the debug console the error shown in the screenshot is appearing.

Steps to Reproduce:
(**NODE JS must be installed**)
1.create a basic html program like hello world.
2.save file in html format.
3.Click run.
4.Click  start debugging.
5.It will ask for environment.
6.Select Node.js.
7.check debug console in the bottom.
8.No debugger available, can not send 'variables'  error is poping in it..\

Can any explain why it is occuring and how to fix it , I am new this platform.
Thankyou in advance.

Does this issue occur when all extensions are disabled?: Yes

![Screenshot 2021-05-03 044514](https://user-images.githubusercontent.com/83499490/116831058-0f7e1d00-ab62-11eb-9209-6806f9db8b85.png)

**Comment by isidorn** [comment]
Just put a breakpoint, once a breakpoint is hit this should just work.
If not I suggest to ask this question on StackOverflow
