### ISSUE TITLE
links in markdown cells in jupiter books don't work

### ISSUE THREAD

**Issue by nacho4d** [microsoft/vscode#122892]
Issue Type: <b>Bug</b>

I hope this is the right place to report this bug. It happens in Jupiter Books with markdown cells.

## Steps to reproduce:

Create a cell markdown cell with a link:
```
[Matrix Multiplication](#matmul)
```
Then create some dummy content so scrool is becomes necesary.

Then create another markdown cell with an anchor:

```
<a name="matmul"></a>

## Matrix Multiplication
```

## Results
In Visual Code link does not work.

## Expected Results
Like in other platform clicking in the link in the first cell will scroll and show the cell with such anchor. 

## VC Code info

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|72.00GB (41.77GB free)|
|Process Argv|--crash-reporter-id 0606939a-255c-47ab-bbc0-25ae305fb9a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
java|red|0.79.1
ayu|tea|0.20.1
vscode-md|Tob|0.5.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by rebornix** [comment]
@nacho4d can you share a screen shot of the notebook you are using to help us identify which notebook editor you are using?
