### ISSUE TITLE
CTRL button stops working after some time

### ISSUE THREAD

**Issue by jsidewhite** [microsoft/vscode#122889]
- VS Code Version: 1.55.2 (user setup)
- OS Version: Windows 10 19042.928

Steps to Reproduce:

1. Use VSCode
2.  CTRL button stops working.  e.g. Cannot copy + paste

Does this issue occur when all extensions are disabled?: I don't know.  I have WaveVS enabled and that's it.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<ctrl+f>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`<ctrl+f>`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
