### ISSUE TITLE
file tab placement features 

### ISSUE THREAD

**Issue by thrainder** [microsoft/vscode#122955]
In visual studio, there are many options are available to formate the file tab like in the below image.
(Hide, Auto-Hide, Float, Dock, etc.)
--by right click
![image](https://user-images.githubusercontent.com/49704486/117060876-1c0b9c80-ad3f-11eb-9a85-c37cecd2389f.png)

This should be available in the VS Code also, as a feature that helps to increase productivity.

**Comment by sbatten** [comment]
We are currently exploring more flexible layouts in VS Code. This feedback will be considered as we improve the view container parts of the workbench.
