### ISSUE TITLE
Discord presence not working

### ISSUE THREAD

**Issue by ronitmtuha** [microsoft/vscode#122982]
So whenever I edit any file is vs code and enable discord presence it just shows connecting to discord but it never connects I tried a lot of times but still no. Pls fix this issue or help me out u can see the attached below. Thanks and regards pls acknowledge the same. Have a good day :)

![Screen Shot 2021-05-05 at 12 10 51 PM](https://user-images.githubusercontent.com/71629891/117105496-c6191200-ad9b-11eb-823e-c83ffe95588b.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Discord presence is not a standard feature of VS Code.
