### ISSUE TITLE
HTML, CSS, JSON language servers don't provide the `documentFormattingProvider` capability

### ISSUE THREAD

**Issue by kabouzeid** [microsoft/vscode#122994]
Text document formatting doesn't work when using any of the HTML/CSS/JSON language servers with a language client other than VSCode, e.g. with neovim or emacs. This is because while these language servers provide `documentRangeFormatting`, they don't provide `documentFormatting`, see: https://github.com/microsoft/vscode/blob/c8bd5b211acd8055a81654dcf40367f422bc22e0/extensions/html-language-features/server/src/htmlServer.ts#L150-L166

VSCode itself handles this by falling back to `documentRangeFormatting` when `documentFormatting` is not available: https://github.com/microsoft/vscode/blob/c8bd5b211acd8055a81654dcf40367f422bc22e0/src/vs/editor/contrib/format/format.ts#L73-L89

## Why I think this should be fixed at the language server level
1. I couldn't find any other language servers (other than the bundled HTML, CSS, JSON servers) that provide `documentRangeFormatting` but not `documentFormatting`.
2. I couldn't find any other language clients (other than VSCode) that fallback to `documentRangeFormatting` when `documentFormatting` is not available.
3. I think it's in the spirit of LSP that the language server should handle both cases, rather than expecting every language client to implement the fallback logic, which seems like a workaround.

Related: https://github.com/neovim/neovim/pull/14491#issuecomment-832292697, https://github.com/autozimu/LanguageClient-neovim/issues/498#issuecomment-402793549

**Comment by aeschli** [comment]
Verify that in JSON and HTML both formatting a document and a range still work.

**Comment by kabouzeid** [comment]
Works for me, tested document formatting and range formatting on JSON and HTML files.

```
Version: 1.57.0-insider (Universal)
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:12:30.409Z (4 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0
```

**Comment by aeschli** [comment]
Thanks @kabouzeid for the verification!
