### ISSUE TITLE
Explorer not starting after the installation of VSCode

### ISSUE THREAD

**Issue by Vitaspiros** [microsoft/vscode#122947]
- VS Code Version:1.55
- OS Version:Windows 10 Pro build 19042.928 20H2

After installing VSCode,rebooting the computer and logging in into my user I encountered a black screen.
I discovered that explorer was started but it didn't show up
![blackscreenaftervscode](https://user-images.githubusercontent.com/49318253/117050741-63356580-ad1e-11eb-84a5-3010a1e7735b.png)
I got to the event viewer and I saw this message: 

The Client License Service (ClipSVC) service terminated with the following error: 
The specified module could not be found.

I searched it on google,fixed and explorer started.
But can anyone explain to me why this is happening?

**Comment by deepak1556** [comment]
I am not sure why VSCode would utilize this service, can you clarify from where did you download VSCode ?

**Comment by Vitaspiros** [comment]
I downloaded VSCode from code.visualstudio.com (I think that's the official,isn't it?)

I'm not sure if VSCode caused this problem but this occurred after the installation of VSCode.
(Sorry for the late reply)

**Comment by deepak1556** [comment]
> I downloaded VSCode from code.visualstudio.com (I think that's the official,isn't it?)

Yup that is correct.

> I'm not sure if VSCode caused this problem but this occurred after the installation of VSCode.

Haven't seen any similar issue reported so far, if the issue happens again with VSCode installation, we can look into it. Closing for now.
