### ISSUE TITLE
Configure vscode to use custom font/fontface based on current theme.

### ISSUE THREAD

**Issue by henry-js** [microsoft/vscode#122936]
Lighter font weights are more readable on dark themes, can we get an added option to "workbench.colorCustomizations" that lets us specify the fontFace and fontWeight.

**Comment by alexdima** [comment]
cc @sandy081

**Comment by sandy081** [comment]
Seems user is asking to add option to `workbench.colorCustomizations` setting. CC @bpasero @aeschli

**Comment by henry-js** [comment]
I did initially, think it would make more sense to have `workbench.preferredLightColorFont`, `workbench.preferredDarkColorFont` and `workbench.preferredHighContrastColorFont` settings.
![image](https://user-images.githubusercontent.com/79054685/121920911-66197200-cd30-11eb-8bb6-51704fc71a94.png)
