### ISSUE TITLE
it's showing the cube of 5 is 124??

### ISSUE THREAD

**Issue by amitanshusahu** [microsoft/vscode#122934]
#include <iostream>
#include <math.h>
using namespace std;
int main() {
    int n;
    cin>>n;

    int power;
    power = pow(n, 3);

    cout<<"cube of "<<n<<" is- "<<power<<endl;

    return 0;

}

when ever i run this it shows the cube of 5 is 124, and this is making some serious computational issue.
plz help...
<img width="960" alt="Annotation 2021-05-04 204446" src="https://user-images.githubusercontent.com/83657737/117026818-b953da00-ad19-11eb-9d43-8120975242a6.png">
<img width="960" alt="Annotation 2021-05-04 204513" src="https://user-images.githubusercontent.com/83657737/117026831-bc4eca80-ad19-11eb-92e5-6bdcb3d347c8.png">

**Comment by lramos15** [comment]
Although this isn't a VS Code problem I'll help you out.

In C++ you must initialize your variables so they can have memory allocated to them. If you don't they have garbage starting values.

Try `int n = 0;` and `int power = 0;`

**Comment by lramos15** [comment]
This isn't a VS Code issue as you're running the code externally to VS Code. I also do not see the issue running that code on my Mac or an online compiler. Maybe try debugging it
