### ISSUE TITLE
"Open with..." crashes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122990]
Just selecting "Open with..." from the explorer yields this exception:

![image](https://user-images.githubusercontent.com/900690/117120252-66b70400-ad93-11eb-9971-64e961819366.png)

My settings:

```json
"workbench.editorAssociations": [
    {
        "viewType": "luna.editor",
        "filenamePattern": "*.jpg"
    },
    {
        "viewType": "luna.editor",
        "filenamePattern": "*.png"
    },
    {
        "viewType": "default",
        "filenamePattern": "git-rebase-todo"
    }
]
```

My installed extensions:

![image](https://user-images.githubusercontent.com/900690/117120374-8a7a4a00-ad93-11eb-8543-ad5c8931eb55.png)

(this is running out of sources)

**Comment by bpasero** [comment]
I pushed a workaround to unblock me because I was not able to open or reopen with anymore.

**Comment by lramos15** [comment]
Closing as the rest of the code expected this value to be undefined but I forgot about the safe de-referencing. Wish typescript would've complained.

**Comment by bpasero** [comment]
> Wish typescript would've complained.

Yeah, I want `noUncheckedIndexedAccess` too, but its another big adoption.
