### ISSUE TITLE
Opening Jupyter notebook >10MB or <10MB with embedded images crashes remote connection

### ISSUE THREAD

**Issue by ad12** [microsoft/vscode#122930]
- VS Code Version: 1.55.2
- OS Version: MacOS 11.2.3 (local), Ubuntu 20.04 (Remote)

Description:
I created and filled in a new jupyter notebook on a remote machine thru VSCode. After filling in some cells and running the notebook, the size of the notebook increased >10MB, which is expected. The notebook was functioning as is even though the size of the notebook was large.

On the following data, I connected back to the remote machine via VSCode. When I tried to open the notebook, the loading bar continued to persist as shown in the image below. After about 10 seconds, the remote session prompted me for my password again. After entering it, the remote connection restarted and tried to open the notebook. I was then stuck in a loop of entering my password and waiting for the file to open.

![image](https://user-images.githubusercontent.com/12801331/117014491-b4554300-aca5-11eb-8185-9defe282a040.png)

I do know this can happen with large files, but I have also increased the max memory in my project settings to 16GB.

```
"files.maxMemoryForLargeFilesMB": 16384,
```

Steps to Reproduce:

1. Open remote connection
2. Open a jupyter notebook >10MB or <10MB with embedded images
3. Go through cycle of entering password and waiting for vscode to try to open the notebook

Does this issue occur when all extensions are disabled?: Yes
The remote/jupyter extensions are needed to repro the bug, but all other extensions were deleted.

**Comment by rebornix** [comment]
@ad12 can you please share a screenshot of any jupyter notebook you are using so we know what version of notebook you are using in VS Code?

**Comment by ad12** [comment]
@rebornix Not sure if a screenshot has that information, but i can send the details for the jupyter notebook and jupyter extension that im using:

Jupyter and notebook in the conda environment that is active (installed via conda):
```
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.6                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py37_0  
notebook                  6.1.1                    py37_0
```

Jupyter extension (ms-toolsai.jupyter): v2021.5.745244803

Let me know if there is any other information you may need

**Comment by ad12** [comment]
The following bug may also be related:

When composing notebooks in VSCode, if the notebook becomes too large, it is no longer saveable. Instead, when Ctrl+S is pressed, the vscode window asks for login credentials into the remote server. This cycle continues indefinitely.

**Comment by rebornix** [comment]
@ad12 only with a screenshot we can know what notebook editor you are using, either a custom webview or the builtin notebook editor, please provide more info.
