### ISSUE TITLE
Bad TypeScript colorisation

### ISSUE THREAD

**Issue by karl20888** [Microsoft/vscode#12298]
- VSCode Version: 1.5.2
- OS Version: Win10

![image](https://cloud.githubusercontent.com/assets/6939070/18656400/5e3df87c-7f23-11e6-8cd9-7927c5a6598f.png)

**Comment by joaomoreno** [comment]
@waderyan Looks like a TypeScript colorisation problem.

**Comment by joaomoreno** [comment]
@karl20888 Please provide the code snippet that caused the problem.

**Comment by waderyan** [comment]
Closing. Will reopen when more info is provided.
