### ISSUE TITLE
find symbol is slower than sublime text

### ISSUE THREAD

**Issue by jeffery9** [Microsoft/vscode#12299]
- VSCode Version: 1.5.2
- OS Version: win10

Steps to Reproduce:

1.  install python extension 
2.  open the same file in the same project in vscode and sublime text,
3.  ctl+shift+o in vscode, and  ctl+r in sublime text,  vscode list all the symbol is slower than sublime text almost in 10 times.  and vscode can not list symbol in tree structure like sublime text doing.

vscode has debug tools is better than sublime text, sublime text is faster than vscode.
any improvement ?

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository. https://github.com/DonJayamanne/pythonVSCode/issues
