### ISSUE TITLE
Powershell in VS Code's terminal has vertical artifact

### ISSUE THREAD

**Issue by FaridAhamat** [microsoft/vscode#122985]
- VS Code Version: 1.55.2
- OS Version: Win10 20H2 build 19042.928. Mac Mini M1 Big Sur 11.2

Steps to Reproduce:

How it looks in VS Code:

![image](https://user-images.githubusercontent.com/11820522/117113893-b5799380-adbd-11eb-99ee-dc7f7df4a5bf.png)

How it looks in Windows Terminal:

![image](https://user-images.githubusercontent.com/11820522/117113999-d93cd980-adbd-11eb-81f2-802382f13ddd.png)

Both are using Cascadia Code Mono PL. I'm seeing the same vertical artifact in VS Code in Mac with default font.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Does changing `terminal.integrated.gpuAcceleration` fix this?

**Comment by FaridAhamat** [comment]
Not sure where's the `terminal.integrated.gpuAcceleration` is, when I tried adding it to settings.json it said that's an unknown configuration setting. 

Anyway, I've tried:
`"disable-hardware-acceleration": true` in argv.json, does not work
Start code by `code . --disable-gpu`, does not work either

**Comment by Tyriar** [comment]
This is fixed in the upcoming stable release

/duplicate https://github.com/microsoft/vscode/issues/120129
