### ISSUE TITLE
Data loss: Custom editors do not properly deal with extension host restarts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122992]
Steps to Reproduce:

1. install an extension that leverages custom editors (non-text based, like Luna paint or Hex editor)
2. open a folder
3. open a file in hex editor or luna paint
4. make the editor dirty
5. add a folder to the workspace
6. the extension host restarts
7. click on another editor
8. click back into the custom editor

=> the custom editor is gone and so is the data

![image](https://user-images.githubusercontent.com/900690/117120861-2906ab00-ad94-11eb-8c15-2881900fd90a.png)

**Comment by bpasero** [comment]
Unfortunately this can result in data loss as you can see from the video below:

![recording](https://user-images.githubusercontent.com/900690/117121203-974b6d80-ad94-11eb-8894-cdd03a043acc.gif)

**Comment by lramos15** [comment]
I can't reproduce this using luna paint.

**Comment by bpasero** [comment]
Here is how it reproduces for me with Luna paint running out of sources (auto save disabled):

![recording (1)](https://user-images.githubusercontent.com/900690/117162493-18b9f480-adc3-11eb-88e0-3752870c6c79.gif)

**Comment by lramos15** [comment]
Hmm. Seems like a race condition, I follow those exact steps and still can't repro. I would be willing to investigate with you.

**Comment by bpasero** [comment]
The more I think about it, the more I feel we really should stop restarting extension hosts: https://github.com/microsoft/vscode/issues/69335

**Comment by sbatten** [comment]
We must restart the extension host in the event the workspace is no longer trusted, so perhaps custom editors need to participate in that transition to avoid data loss

**Comment by bpasero** [comment]
Fyi, yesterday I pushed support for [`IFileWorkingCopyManager#destroy`](https://github.com/microsoft/vscode/blob/d026aff522cdc23422bc1b9c4443969d8286ecc9/src/vs/workbench/services/workingCopy/common/fileWorkingCopyManager.ts#L739-L739) which returns a `Promise` and is used for notebooks, e.g. when an extension is uninstalled or gets disabled. The gist is, this method will:
* unregister any working copy it owns
* trigger a `save` for dirty working copies
* and if that fails, will resolve any existing backup for the working copy and save that to disk instead

However, I think this issue is more tricky for (non-text) custom editors, because we do not really know how the extension has implemented the `save` method to persist the changes to disk. 

If we cannot restore the dirty editor properly after the extension host has restarted, we should at least make sure to reopen the editor with the dirty contents (= backup) after the extension host has started again.

**Comment by lramos15** [comment]
From my discussion with Matt it appears the solution to this issue revolves around persisting the model managers upon extension host restart and syncing the models and webviews to the new ext host.

**Comment by Ark-kun** [comment]
Would the issue be solved if the custom editor was just resolved again (call `resolveCustomTextEditor`) for all documents opened in custom editors?

**Comment by bpasero** [comment]
One idea from @alexdima was to introduce a participation model for extension host restarts: any component can veto the restart and thus custom editors could show a modal dialog to users in case this is needed and veto the restart.

**Comment by Tyriar** [comment]
Verified, but I think https://github.com/microsoft/vscode/issues/183778 is a core problem.
