### ISSUE TITLE
Merge extension and extension media tasks into one

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122978]
I see no reason why we cannot add the extensions media related tasks to the existing extension tasks.

![image](https://user-images.githubusercontent.com/900690/117101359-5a707e00-ad76-11eb-9973-fa10bcacfafa.png)

**Comment by joaomoreno** [comment]
Please remove this extra process @mjbvz.

**Comment by mjbvz** [comment]
Combined with 9be6a2476e32e2e8263876fba37978598586b030

**Comment by bpasero** [comment]
Thanks!
