### ISSUE TITLE
Current code will be not saved after merge - still existing  <<<<<<< HEAD   artifacts

### ISSUE THREAD

**Issue by okunahe** [microsoft/vscode#122984]
After merge and resolving merge conflicts the following  issue will be shown Line 47: Unexpected token

> 47 | <<<<<<< HEAD
  48 | =======
  49 |   contractors: {
  50 |     data: [], (47:1) 

This line doesn't exists in code after resolving of merge conflicts.
![image](https://user-images.githubusercontent.com/46608681/117113186-67976800-ad8a-11eb-9339-bda69c16350b.png)

**Comment by joshuajtward** [comment]
I am also seeing this issue

**Comment by lszomoru** [comment]
@okunahe, @joshuajtward, apologies for not getting back to you on this until now. Are you still able to reproduce this issue? Is so, would you be able to provide a repository with an isolated repro so that I can further investigate the issue? Thank you very much!

**Comment by joshuajtward** [comment]
@lszomoru I haven't seen this issue for a year or so, happy to close it from my side!

**Comment by lszomoru** [comment]
@joshuajtward, thanks for getting back to me on this.
I will go ahead and close the issue but please feel free to reopen it in case you run into this again.
