### ISSUE TITLE
Typescript syntax highlighting is not working after `typeof`

### ISSUE THREAD

**Issue by zxxc** [microsoft/vscode#122901]
Issue Type: <b>Bug</b>

Create a function like this:

```typescript
interface inter1 {
  access_token: string;
}

let const1: inter1;
export function func1(): typeof const1 {
  return {
    access_token:''
  };
}

```
return and everything below return will be white

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id b71bae33-8004-45d2-9ea4-b6c67468fd4b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
ng-template|Ang|11.2.13
rspec-focus|asu|0.2.0
rails|bun|0.17.0
vscode-gemfile|bun|0.4.0
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-postgres|cko|1.1.17
jsrefactor|cms|2.20.6
vscode-mocha|Com|0.1.1
vscode-redis-client|cwe|1.2.8
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
LogFileHighlighter|emi|2.11.0
prettier-vscode|esb|6.3.2
vscode-jest-runner|fir|0.4.34
gitlab-workflow|Git|3.19.0
ruby|gro|0.1.0
vscode-test-explorer|hbe|2.19.6
ruby-linter|hoo|1.0.0
vscode-rufo|jnb|0.0.4
refactorix|kri|0.3.6
git-graph|mhu|1.30.0
ruby-symbols|mig|0.1.8
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
rails-run-spec-vscode|nok|0.1.3
angular-console|nrw|17.2.0
indent-rainbow|ode|7.5.0
total-lines|pra|0.0.1
typescript-hero|rbb|3.0.0
ruby|reb|0.28.1
vscode-yaml|red|0.18.0
vscode-sort-json|ric|1.20.0
markdown-preview-enhanced|shd|0.5.18
slim|sia|0.1.2
vscode-fileutils|sle|3.4.5
move-ts|str|1.12.0
sort-lines|Tyr|1.9.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by mjbvz** [comment]
Seems to work fine in VS Code insiders
