### ISSUE TITLE
Select the environment picker choice should be stored per folder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122942]
The `Select the Environment` picker shows up whenever user does not have a launch.json and is starting debugging a file which has multiple debuggers interested in it.
This question makes sense, however what could drastically be improved if we simply stored the users choice per folder. That way this would only appear once and not on every debug start, thus making the whole experience much smoother.

The downside: if the user choose wrongly, how can he or she unset this?
Due to that I suggest that we only store this if debugging was started successfully?

@connor4312 @weinand what do you think?

![Screenshot 2021-05-04 at 19 18 38](https://user-images.githubusercontent.com/1926584/117043526-a3d8b300-ad0d-11eb-86bf-c3ad29a8da96.png)

**Comment by connor4312** [comment]
There's also the case that users may often have client and server code in the same folder. Maybe caching it per-file would work better?

**Comment by isidorn** [comment]
@connor4312 good point.
