### ISSUE TITLE
Perl Indented Heredoc not highlighted correctly

### ISSUE THREAD

**Issue by dboyd-usedc** [microsoft/vscode#122932]
Issue Type: <b>Bug</b>

1) Use indented heredoc support (feature introduced in perl 5.26) e.g.:

```
my $text = <<~ 'END'
     this heredoc
     is indented
     END
```

2) VS Code doesn't recognized the final 'END' which throws off the highlighting for the rest of the source file

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.25GB free)|
|Process Argv|--crash-reporter-id 49a81fea-c060-4089-b18a-d4174330a2cd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|Memory (System)|15.93GB (3.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|Memory (System)|15.93GB (3.25GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-perl-syntax|jef|1.0.14
mojolicious|kra|1.9.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vim|vsc|1.20.2
gdb-debug|Dam|1.0.7
code-runner|for|0.11.3
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
perl|ric|2.2.0
perltidy|sfo|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by JacksonKearl** [comment]
We pull grammars from https://github.com/textmate/perl.tmbundle please file an issue there, then we will pull in the fix.

**Comment by alexr00** [comment]
I'm also not able to reproduce the problem, so it could be coming from one of the extensions you have installed.

**Comment by dboyd-usedc** [comment]
Really?

Can you post your test code?

Sent from my iPhone

On May 7, 2021, at 5:20 AM, Alex Ross ***@***.***> wrote:

﻿

I'm also not able to reproduce the problem, so it could be coming from one of the extensions you have installed.
