### ISSUE TITLE
ListView leaks emitters

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122999]
branching of https://github.com/microsoft/vscode/issues/122668#issuecomment-832596456

* open/close a notebook
* take heap snapshot
* open/close a notebook 10 times (repeat to amplify eventual leaks)
* take heap snapshot
* 💧 see how thousands of `Emitter` instances have leaked

Many are from the `ListView`, the [domEvent](https://github.com/microsoft/vscode/blob/6d81daa07c091d90ff53be48e41fb020bec6a933/src/vs/base/browser/ui/list/listView.ts#L893-L893)-util creates an emitter but that's never dipsosed

**Comment by joaomoreno** [comment]
I can't reproduce this in an isolate environment anymore, so I'm pretty sure these were mostly https://github.com/microsoft/vscode/issues/123001. There are still leaks but they aren't traced back to the ListView anymore.
