### ISSUE TITLE
QuickPick doesn't fire the `onDidChangeValue` when setting value manually

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#122939]
If you set `QuickPick.value` programatically when setting up the QuickPick, it fails to trigger the `onDidChangeValue` event.

Here is my workaround hack:
https://github.com/eamodio/vscode-gitlens/blob/db5285d4ad268148dbc4a6ce9d1f284d5e18ac4e/src/commands/gitCommands.ts#L717-L727

**Comment by TylerLeonhardt** [comment]
verification steps:

Add this to an extension:

```ts
    const quickpick = window.createQuickPick();
    quickpick.title = 'Hello fam'
    quickpick.items = [{ label: "don't pick me" }, { label: 'or me' }]

    quickpick.onDidChangeValue((e) => window.showInformationMessage(e));
    quickpick.buttons = [
        {
            iconPath: ThemeIcon.File,
            tooltip: 'change value'
        }
    ];
    quickpick.onDidTriggerButton(e => {
        quickpick.value = "Changed!";
    });

    quickpick.show();
```

Type a couple characters in the filter, it should spam notifications
Click the button, it should change the value and send a notification with `"Changed!"`.

**Comment by stevenguh** [comment]
FYI, this breaks existing extension that relied on that behavior.

**Comment by TylerLeonhardt** [comment]
@stevenguh can you elaborate on how this change ended up breaking you?

**Comment by stevenguh** [comment]
Since the onDidChangeValue can't tell apart from different types of changes (programatic vs non-programatic), I had to do something like https://github.com/VSpaceCode/vscode-which-key/commit/65669b67a94f25e4fc6cc38591e6b98b4271dd93 only handle non-programatic changes.

**Comment by TylerLeonhardt** [comment]
@stevenguh, thanks for working around this change. Just for some explanation, we did this to align `.value` with `.items` and `.selectedItems`. At the end of the day, these properties now all have the same behavior which I think will be easier going forward.

**Comment by stevenguh** [comment]
Thanks for following up. That makes sense if the angle is to align with other onChange methods. Still it would be nice to have onChange methods that don't trigger on setter. That's probably a separate issue at this point.

**Comment by TylerLeonhardt** [comment]
verification steps above: https://github.com/microsoft/vscode/issues/122939#issuecomment-832201714
