### ISSUE TITLE
Block cursor doesn't match parenthesis correctly.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#12293]
- VSCode Version: 1.5.2
- OS Version: 10.10.5

A picture says a thousand words:

![screen shot 2016-09-19 at 5 53 57 pm](https://cloud.githubusercontent.com/assets/167745/18653922/38291c8e-7e92-11e6-86ff-cbf94912b977.png)

**Comment by Bill-Stewart** [comment]
Actually the behavior is consistent with the other cursor types (change `cursorStyle` to `line` to see). This request is to change bracket highlighting only if using `block` style cursor.

**Comment by alexandrudima** [comment]
It is unfortunate, that the block cursor is so far only a rendering time option and the bracket matching code is not aware of it. As far as that code is concerned, the cursor sits between two `)`, and matching any of those is OK.

**Comment by Bill-Stewart** [comment]
So perhaps this could be handled by option that says 'do not highlight matching when cursor is after one of the matched characters' (i.e., only highlight when cursor is directly on a matched character).

**Comment by FSMaxB** [comment]
Yes, the block cursor being on a character is essentially the same as the line cursor being in front of that character, so if the highlight only ever occurs for characters *after* the cursor position (in line cursor mode) and not in front, it would have the desired effect in block cursor mode.
