### ISSUE TITLE
调试BUG terminal.integrated.shellArgs.windows

### ISSUE THREAD

**Issue by asnjudy** [microsoft/vscode#122983]
在对python进行调试时，下面的配置
    "python.terminal.activateEnvironment": false, 
    "terminal.integrated.shellArgs.windows": [
        "-noexit", "-command", "conda activate ${config:python.pythonPath}\\..",
    ],
放在全局配置下有效，但是放到项目配置下的setting.json文件中无效。
即在，项目配置中，对python代码进行调试时，不读取   "terminal.integrated.shellArgs.windows" 配置选项。

**Comment by infinnie** [comment]
Translation:

# Bug in Debugger `terminal.integrated.shellArgs.windows`

When debugging the Python project, the configuration below
```
"python.terminal.activateEnvironment": false,
"terminal.integrated.shellArgs.windows": [
    "-noexit", "-command", "conda activate ${config:python.pythonPath}\..",
],
```

could work when placed in the global settings, but couldn’t when placed in the project’s setting.json, _i.e._, the configuration `terminal.integrated.shellArgs.windows` is not read when debugging Python if placed within Workspace settings.

**Comment by infinnie** [comment]
Perhaps you should put ’em in `settings.json`.
