### ISSUE TITLE
settings.json file

### ISSUE THREAD

**Issue by William1947** [microsoft/vscode#122935]
Issue Type: <b>Bug</b>

somehow my settings.json file in Visual Studio Code the first 2 lines changed and now I'm receiving an error that it cannot sync . I have the newest VS Code and using windows 10 if someone can help. the 2 files are below,
"{windows}"
"Adjust the zoom level of the window. T",

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.70GB free)|
|Process Argv|--crash-reporter-id 5ea2c942-5944-4472-89c7-fac339c58caf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
pythoncpp-debug|ben|0.2.9
jshint|dba|0.11.0
vscode-javac|geo|0.2.39
elixir-ls|Jas|0.2.26
vscode-docker|ms-|1.12.1
vscode-edge-devtools|ms-|1.1.8
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
js-debug-nightly|ms-|2021.5.317
java|red|0.79.1
snyk-vulnerability-scanner|sny|1.0.3
vscode-java-debug|vsc|0.33.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
Did you just file a duplicate of https://github.com/microsoft/vscode/issues/122236? What else do you need?

**Comment by William1947** [comment]
No, did not mean to send this out again, just really having a time with the setting.json file, sorry to bother you.
Have a great day
Ronald Massey


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
