### ISSUE TITLE
errors generated by a task with isWatching not cleared after fixing

### ISSUE THREAD

**Issue by alexdresko** [Microsoft/vscode#1229]
See http://stackoverflow.com/questions/33563049/in-vscode-errors-generated-by-a-task-with-iswatching-are-not-always-cleared-afte

The question and answer are both correct in their description. I'm having the same problem and couldn't find a corresponding issue here in the repo, so figured I'd go ahead and create one.

**Comment by dbaeumer** [comment]
Duplicated #909

**Comment by dbaeumer** [comment]
Verified as duplicate
