### ISSUE TITLE
Document new colors

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#122911]
The following colors need to be documented at https://raw.githubusercontent.com/microsoft/vscode-docs/vnext/api/references/theme-color.md
- [x] "`button.border`: Button border color." @aeschli 
- [ ] ~"`editorInlineHint.foreground`: Foreground color of inline hints" @jrieken~
- [ ] ~"`editorInlineHint.background`: Background color of inline hints" @jrieken~
- [x] "`toolbar.hoverBackground`: Toolbar background when hovering over actions using the mouse" @joaomoreno @roblourens 
- [x] "`toolbar.hoverOutline`: Toolbar outline when hovering over actions using the mouse" @joaomoreno 
- [x] "`toolbar.activeBackground`: Toolbar background when holding the mouse over actions" @joaomoreno @roblourens 
- [ ] ~"`workspaceTrust.trustedForegound`: Color used when indicating a workspace is trusted." @sbatten~
- [ ] ~"`workspaceTrust.untrustedForeground`: Color used when indicating a workspace is not trusted." @sbatten~
- [ ] ~"`workspaceTrust.tileBackground`: Background color for the tiles on the Workspace Trust page." @sbatten~
- [x] "`ports.iconRunningProcessForeground`: The color of the icon for a port that has an associated running process." @alexr00

**Comment by jrieken** [comment]
removing myself because the inlineHint colours aren't consumable yet

**Comment by sbatten** [comment]
same for me, the trust options need work

**Comment by alexdima** [comment]
FYI @jrieken @sbatten -- the endgame plan contains a bullet point that asked me to create this issue. It is very likely that the next endgame champion will ping you again (unless the tool is adjusted somehow).

**Comment by jrieken** [comment]
I know. You are not the first endgame master to ping me 😄
