### ISSUE TITLE
markdown preview fails to jump top embedded link in TOC

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#122967]
Issue Type: <b>Bug</b>

When I click on the first link in the markdown preview, it will behave strangely, sometimes it will over jump, other times it will not do anything.

If I go to the edit window and click on the link with [CTRL]+mouse-click, the jump happens and I am taken to the correct location in the document.

Here is a video demonstrating the problem: https://youtu.be/yiV9pObqK28

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.12.0-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.28GB (18.13GB free)|
|Process Argv|/home/yadav/dev/docs/guides --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-base64|ada|0.1.0
vscode-tomcat|ada|0.11.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|11.1.0
ng-template|Ang|0.1100.4
vscode-apollo|apo|1.19.0
vscode-browser-preview|auc|0.7.1
vscode-tailwindcss|bra|0.5.10
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.40.3
vscode-eslint|dba|2.1.8
java-decompiler|dgi|0.0.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.5.0
vscode-lombok|Gab|1.0.1
markdown-preview-bitbucket|hbr|1.0.0
java-properties|ith|0.0.2
vscode-peacock|joh|3.8.0
solidity|Jua|0.0.76
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.1.0
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.8
angular2-inline|nat|0.0.17
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.25.0
vscode-manifest-yaml|Piv|1.25.0
vscode-spring-boot|Piv|1.25.0
platformio-ide|pla|1.10.0
java-ide-pack|pve|1.2.1
java|red|0.59.1
vscode-yaml|red|0.17.0
vue-vscode-snippets|sdr|2.2.0
markdown-preview-enhanced|shd|0.5.18
vscode-checkstyle|she|1.4.0
java-generate-setters-getters|soh|7.0.3
sonarlint-vscode|Son|1.21.0
language-stylus|sys|1.11.0
serverless-ide-vscode|Thr|0.5.31
find-then-jump|tra|2.0.4
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.30.0
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.7.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? You have a few markdown extensions installed

**Comment by mjbvz** [comment]
Also share markdown that demonstrates the issue

**Comment by rajinder-yadav** [comment]
Looks like one of the extensions is causing the issues!
