### ISSUE TITLE
High CPU load when starting up

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode#122998]
Issue Type: <b>Bug</b>

After VSCode has started, and I guess after an unsleep, vscode is taking much CPU time for an amount of time. Sometimes even many minutes.

If I kill the consuming process in task manager it regularly is the extension host that is apparently killed. It comes back up and it again starts consuming much cpu.

Interestingly this looks like to happen only when running from the Windows file system and vscode server. As soon as I switch to WSL file system and server this happens much less frequently.

Ideally vscode should provide more diagnostics to see what are the CPU consuming processes.
In the past I have seen for example that crawling all the files in the repo takes lots of CPU. 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (2.36GB free)|
|Process Argv|--crash-reporter-id 5ed5d6f6-dfc2-4c7c-8d01-9cba6511c0a5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.91GB (16.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.91GB (16.29GB free)|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: Canceled
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
azurepolicyextension|Azu|0.1.2
gitlens|eam|11.4.1
cloudcode|goo|1.11.0
beautify|Hoo|1.5.0
file-downloader|min|1.0.10
mindaro|min|1.0.120210423
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-docker|ms-|1.12.1
vscode-dotnet-runtime|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.3.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.8
powershell-preview|ms-|2021.4.2
azurerm-vscode-tools|msa|0.15.1
vscode-yaml|red|0.18.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfilehidden:30294815
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by JacksonKearl** [comment]
This could be a problem with your extensions, please try disabling extensions then re-enabling until you fond the extensions which is causing the problem. You may find Extension Bisect https://code.visualstudio.com/blogs/2021/02/16/extension-bisect to help here
