### ISSUE TITLE
Navigation/Goto Anywhere

### ISSUE THREAD

**Issue by ToujouAya** [Microsoft/vscode#12296]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.3.9600

Actually I think it's  not issues. I just want to know.
Does vscode have any feature to navigate/go to function like keyboard shortcut CTRL + R in Sublime. 
I am web developer ,  I already tried by using keyboard shortcut CTRL + SHIFT + O, CTRL + T, but it's not working, it can't navigate.

**Comment by joaomoreno** [comment]
<kbd>Ctrl Shift O</kbd> lets you go to any type in a file. <kbd>Ctrl T</kbd> lets you go to any type anywhere. This is provided that you are using a language extension that supports these features. TypeScript and C# are good examples.

**Comment by ToujouAya** [comment]
@joaomoreno 
So there is no way to navigate to function like sublime. I have tried it with PHP or Javascript but it's not work.

**Comment by Bill-Stewart** [comment]
`ctrl+shift+o` works in JavaScript code.

**Comment by joaomoreno** [comment]
@ToujouAya It works in JavaScript. Use <kbd>Ctrl Shift O</kbd>.

**Comment by ToujouAya** [comment]
@joaomoreno  @Bill-Stewart 
oh i was wrong at Javascript.  But I think the feature isn't convenience for navigate to the symbol 
On JavaScript , it work for function name, but for prototype property method, I can only use the keyboard to navigate between the symbol. I need to write correct path of symbol like this 

![image](https://cloud.githubusercontent.com/assets/21350606/18695473/56abaece-7fdc-11e6-8ade-1dec99f0670e.png)


In Sublime I only need type the name of the prototype method and it will navigate to correct method. 

![image](https://cloud.githubusercontent.com/assets/21350606/18695503/795201a8-7fdc-11e6-8ff3-8fdaedac8a97.png)

it is just my opinion . sorry for my English

**Comment by joaomoreno** [comment]
Not a problem, being just your opinion. cc @waderyan
