### ISSUE TITLE
Cannot write new lines right now

### ISSUE THREAD

**Issue by jhoareau** [microsoft/vscode#122903]
Issue Type: <b>Bug</b>

When I try to write a new line in a python file, I get the warning message at the bottom right: `cannot read property 'rename' of undefined`.
The new line is not added to the file.

I cannot find any other log that could correspond to the error in the logs or dev tools of VSCode.

VS Code version: Code - Insiders 1.56.0-insider (4e185d8986339717e593be19bc75288905ffbb51, 2021-04-30T23:19:25.345Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.01GB free)|
|Process Argv|--crash-reporter-id 47dbb3fa-3f82-4998-ae35-049857685115|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer|ber|0.12.2
better-toml|bun|0.3.2
gitlens|eam|11.4.1
terraform|has|2.10.1
beautify|Hoo|1.5.0
vscode-docker|ms-|1.12.1
python|ms-|2021.5.791577556-dev
vscode-pylance|ms-|2021.4.4-pre.1
jupyter|ms-|2021.6.806304047
remote-containers|ms-|0.174.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
vscode-yaml|red|0.18.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehov:30295781

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<Enter>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`<Enter>`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by jhoareau** [comment]
Hi, thanks for your reply. It seems like today's nightly fixed it. Not sure exactly how or why, but I cannot reproduce now. Thanks!
