### ISSUE TITLE
Terminal doesnt acknowledge .Net

### ISSUE THREAD

**Issue by HalfApe** [microsoft/vscode#122908]
Issue Type: <b>Bug</b>

Installed: VSC with C# Extension from Microsoft and .NET 5.0.202 SDK 
.NET can only be used in the Linux Terminal if i use it in the VSC Terminal ist returns: dotnet: command not found

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.4.0-72-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.11
cpptools|ms-|1.3.1

</details>

**Comment by HalfApe** [comment]
I tested it on Windows there the combination of the VSC version and the .NET Version works perfectly fine.

**Comment by Tyriar** [comment]
This means `dotnet` isn't on your path so it depends how you set that up. Try changing the args of your terminal and/or finding how it gets added to the path
