### ISSUE TITLE
Task quick access suggests tasks that don't exist anymore

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#122972]
The github issues notebook changed some tasks recently https://github.com/microsoft/vscode-github-issue-notebooks

I opened the repo, did a git pull, opened the task menu, and saw the same bundle-watch task that I have been running

![image](https://user-images.githubusercontent.com/323878/117095677-da1d2f00-ad1b-11eb-80c0-07a4ff8b198c.png)

But, that task doesn't exist anymore, and when I try to run it, I just get this confusing error

![image](https://user-images.githubusercontent.com/323878/117095745-0933a080-ad1c-11eb-9e58-9f795d062a49.png)

**Comment by alexr00** [comment]
In the task quick pick accuracy is sacrificed in favor of speed. "recent tasks" and tasks from tasks.json can be displayed almost instantly, all other extension contributed tasks can only be displayed after asking the individual extension for tasks. That npm task was still saved as a recent task, so we save the trip to the extension and show it, even if it doesn't exist anymore.

**Comment by alexr00** [comment]
@roblourens is this super painful? I've only had a few people report this as an issue and the behavior has existed for a year. To help alleviate it, there is an "x" so you can remove recent tasks. in the task quick pick.

I think the only way to really solve this is to add more API.

**Comment by roblourens** [comment]
I'm clicking the X but it doesn't do anything

https://user-images.githubusercontent.com/323878/117179764-52213e80-ad88-11eb-9e5b-a0d853b1414e.mp4

I guess I expected that maybe it would show the first time, but we would refresh the list in the background once it's revealed, or after picking the task. It's like how recently opened files and folders will be removed from the list if you try to open it and we find that it doesn't exist anymore.

**Comment by alexr00** [comment]
The "x" not working is certainly a bug.
