### ISSUE TITLE
Breakpoints I set before a debug session get transformed into unbound breakpoints at debug runtime

### ISSUE THREAD

**Issue by msalvi96** [microsoft/vscode#122924]
I am facing a similar issue as well where the breakpoints I set before a debug session get transformed into unbound breakpoints at debug runtime and the debugger stops at compiled JS files whereas I want those breakpoints to stop at the initial TS files. Also set the trace=true property in my launch config but the breakpoints still don't stop at the desired point in TS files. 

VS Code - 1.55
OS - Windows 10 64
Language - TypeScript 4.0
Framework - Azure Bot Framework SDK

Breakpoint Screenshot (Before starting debug session)
![set-breakpoint](https://user-images.githubusercontent.com/48700772/116878086-d0e17480-abec-11eb-8881-52b2eec7edd7.PNG)
![breakpoint-list](https://user-images.githubusercontent.com/48700772/116878107-db037300-abec-11eb-81fe-6d272eef04ca.PNG)

Breakpoint Screenshot (After starting debug session)
![unbound-breakpoint](https://user-images.githubusercontent.com/48700772/116878153-efe00680-abec-11eb-9e29-924b1762faa6.PNG)
![unbound-list](https://user-images.githubusercontent.com/48700772/116878164-f40c2400-abec-11eb-9c6a-eac574e68fe5.PNG)

Breaks at JS Files
![js-break](https://user-images.githubusercontent.com/48700772/116878207-05553080-abed-11eb-9b38-9ba541a8f528.PNG)

Launch Configuration
![launch config](https://user-images.githubusercontent.com/48700772/116878329-30d81b00-abed-11eb-9d0c-66e2f7128e06.PNG)

Please find the debug log file here:
[vscode-debugadapter-69dd4811.json.gz](https://github.com/microsoft/vscode/files/6421841/vscode-debugadapter-69dd4811.json.gz)

_Originally posted by @msalvi96 in https://github.com/microsoft/vscode/issues/122580#issuecomment-831240584_

**Comment by connor4312** [comment]
It looks like you might have symbolically linked sources. If you do, follow the "Can I debug if I'm using symlinks" steps here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks

**Comment by msalvi96** [comment]
> It looks like you might have symbolically linked sources. If you do, follow the "Can I debug if I'm using symlinks" steps here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks

I have tried updating my launch config to include "preserve-symlinks" as a runtimeArgs parameter. But it still stops at the corresponding JS breakpoint post compilation.

**Comment by connor4312** [comment]
Can you collect another log with that flag set?

**Comment by msalvi96** [comment]
Sorry for the delay! Here's the log file and my launch config with "preserve-symlinks"
[vscode-debugadapter-9ed6d78a.json.gz](https://github.com/microsoft/vscode/files/6443011/vscode-debugadapter-9ed6d78a.json.gz)

![symlink-launch-config](https://user-images.githubusercontent.com/48700772/117479432-54bd9880-af2e-11eb-9e8f-b2133b9bf58b.PNG)
