### ISSUE TITLE
Scroll debug console to end

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#122910]
Issue Type: <b>Feature Request</b>

It'd be nice to be able to scroll directly to the end of the debug console on-demand. Like, when the window is focused, and I press Ctrl+End, scroll to the bottom.

VS Code version: Code - Insiders 1.56.0-insider (4e185d8986339717e593be19bc75288905ffbb51, 2021-05-01T00:27:57.510Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by isidorn** [comment]
Already possible but maybe not the most convenient: focus on debug console input, press shift + tab to focus on the debug console. press END -> the last element should be revealed.

I guess we could introduce a command just for this, thus I can leave this open as a feature request and assign to backlog. Thanks

**Comment by oliversalzburg** [comment]
I didn't really expect this to be a situation that requires a special command. I brought up Ctrl + End as an example, as that is (on my system) the key combination to set the caret to the last possible position in text input controls.

This is the behavior that is working as expected in the terminal and code editor views. The debug console behaves in many ways similarly to those views. I feel it's not unreasonable for a user to expect the same pattern to work for the debug console as well.

Naturally, this expectation goes beyond scrolling to the end of the console. Jumping to the beginning is in a similar fashion is also expected. It's just very common for the user to have to deal with the debug console not being scrolled to the end automatically.

For my personal developer experience, using your suggested approach beats scrolling the tiny scrollbar to the end. So, thanks for that 😄

**Comment by isidorn** [comment]
Debug console works just like all the other list views. The only difference is that clicking on it we move focus to the debug console input automatically. And thus the only way to focus it you have to shift+tab. However once you have focus all the keybindings should just work
