### ISSUE TITLE
Finalize notebooks API (part 1)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#122922]
This issue is tracking the finalization of the notebooks API. In the first round that should be

* the `registerNotebookSerializer`-function and its descendant types: `NotebookSerializer`, `NotebookData` etc
* the package.json contribution for serializers
* the `createNotebookController`-function and its descendant types: `NotebookController`, `NotebookDocument ` etc
* the `registerNotebookCellStatusBarItemProvider`-function and its descendant types: `NotebookCellStatusBarItemProvider`

**Comment by jrieken** [comment]
Final remaining questions (most up-to-date list is _todo@API_ in `vscode.proposed.d.ts`)

* [ ] Should we rename the namespace to _notebook**s**_. Also what should go into it? Should things like `notebookDocuments` and its events be in `workspace`, just like `textDocuments`?
* [ ] Should we rename `NotebookDocument#viewType`. It is a document type, similar to `TextDocument#languageId` and therefore `notebookType` might be better
* [ ] `NotebookCellMetadata` and `NotebookMetadata` - the latter is empty, the former only has collapse states for input/output. Should we extract what's known to use into a separate type and leave metadata all open and more raw, e.g go back to `{ [key:string]: any}` type?
* [ ] `NotebookOutput` and `NotebookOutputItem` both have `metadata` and there is still an offline discussion if both are needed. There is tendency to only have it on the former
* [ ] there is an event `NotebookCellExecutionState` changes but there is no corresponding property on the cell type. That's a misalignment. 
* [ ] should `NotebookRendererScript` already be finalized or should we wait for renderer IPC to go final, same for `asWebviewUri`

**Comment by rebornix** [comment]
>  NotebookOutput and NotebookOutputItem both have metadata and there is still an offline discussion if both are needed. There is tendency to only have it on the former

In practice (Jupyter), a `NotebookOutput` usually consists of a `NotebookOutputItem` per mime type. It's fine that we don't have `metadata` on `NotebookOutputItem` as this can be then archived by `NotebookOutput.metadata: { '$mimetype': '' }`. 

Currently I'm not seeing a need for `NotebookOutputItem#metadata` yet so +1 for only having it on `NotebookOutput`.

**Comment by jrieken** [comment]
PR for removing metadata from NotebookOutputCellItem -> https://github.com/microsoft/vscode/pull/125104
