### ISSUE TITLE
When I save, vs code will modify the content on my clipboard

### ISSUE THREAD

**Issue by 951565664** [microsoft/vscode#122931]
- VS Code Version: 1.55.2
- OS Version: macOs Catalina 10.15.7

Steps to Reproduce:

1. Using ctrl+s or cmd+s has the same function as ctrl+c or cmd+s

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
