### ISSUE TITLE
Test: Pseudoterminal.onDidChangeName event

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122945]
Refs: #114898

- [x] anyOS @rebornix
- [x] anyOS @lszomoru

Complexity: 2
Roles: Developer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122945%0A%0A)

---

There's a new API that lets Pseudoterminal's (aka "extension terminals") control the terminal's title/tab name. To test clone the [extension terminal sample](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample), implement the new event similar to how the example uses `onDidWrite` and make sure it acts as expected.

**Comment by JacksonKearl** [comment]
@Tyriar changed labels around to remove from inbox query
