### ISSUE TITLE
Settings sync emptied my settings.json file

### ISSUE THREAD

**Issue by the21st** [microsoft/vscode#122920]
- VS Code Version:  1.55.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Turn on vscode settings sync
2. Use it for a few months
3. Your settings will get deleted by the sync:
![image](https://user-images.githubusercontent.com/4610874/117004026-e1294a80-ace5-11eb-878e-d1d95ea0a4ac.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by the21st** [comment]
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

I checked, none of these are a duplicate.

**Comment by zhixiangteoh** [comment]
Faced this issue twice within a week. Similar to [this SO post](https://stackoverflow.com/questions/60077869/vscode-settings-json-is-empty).

**Info:**
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

![Screen Shot 2021-05-20 at 11 44 19 PM](https://user-images.githubusercontent.com/47135468/119079079-fca48d00-ba29-11eb-8ac6-beab6b838f31.png)

**Comment by sandy081** [comment]
@the21st Sorry for what happened. I think you could restore your settings from the activity view you have it in your screenshot.

Basically the diff in your screenshot shows the diff between remote content at that point of time with current local content. So in your screenshot remote still has all of your settings. Can you please find the remote that is empty and see which machine has pushed it?

**Comment by squaresmile** [comment]
Just have this happened today after installing the 1.57.0 update.

**Comment by mrwonko** [comment]
My settings also got reset. In the sync logs I see

```
Opening repository for path='/Users/MyUserRedacted/Library/Application Support/Code/User/sync/settings' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
```

**Comment by sandy081** [comment]
It might happen that settings got reset due to the issue - https://github.com/microsoft/vscode/issues/125970 and not by Setting Sync

**Comment by mrwonko** [comment]
Sounds likely, I think I had multiple windows open when I applied the update.

Does the sync keep a version history? Is there some way to get my settings back?

**Comment by sandy081** [comment]
I am closing this due to the lack of information.

@the21st Please check my comment here - https://github.com/microsoft/vscode/issues/122920#issuecomment-857820069 and provide the requested info.
