### ISSUE TITLE
Cleanup `imagePreview.border` color

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#122917]
The `imagePreview.border` doesn't seem to be used anywhere in our sources. We should probably delete it and remove it from the docs as well:

- https://github.com/microsoft/vscode/blob/63cbe73b2f5d363326c4bea74457edd07dc8bd63/src/vs/workbench/common/theme.ts#L254-L259
- https://github.com/microsoft/vscode-docs/blob/21032f78218fdc029a857bfe9e2e9a9e6ca5ef35/api/references/theme-color.md#preview-colors (also the wrong heading number was used here)
- https://github.com/microsoft/vscode/pull/76387/files

**Comment by mjbvz** [comment]
Since no one has complained about this not working for over a year, I think we can remove it :)

**Comment by joaomoreno** [comment]
@mjbvz Don't forget the docs: https://github.com/microsoft/vscode-docs/blob/main/api/references/theme-color.md#preview-colors
