### ISSUE TITLE
Improve the explorer view to match full VS design

### ISSUE THREAD

**Issue by JabX** [Microsoft/vscode#123]
Hello,

I use VS Code daily at work and at home since the very first preview release and I love it.

I do have a major concern though about the way the differents files are shown in the 'Working Folder' view : they're all formatted in the same, plain way, and it is actually quite hard to distinguish what is what when looking at it (especially folders vs files). In a previous release, I recall the folder names were bold. It was better but nonetheless not enough.

I think this image below can describe pretty well what I suggest:
![folderview](https://cloud.githubusercontent.com/assets/3266897/11257610/fe34751c-8e52-11e5-9a98-7d7302611ddf.png)
The same solution is opened in both Code and full VS, and obviously the latter works way better with icons and varying font weight.

Would it be possible to achieve a similar look with Code ? I don't know about reusing the full VS assets since it might be a problem with licensing and stuff though. I gave a look at the new extension API but it specifically states that it doesn't allow for DOM manipulation, so I guess it's a no-go.

If it's not in the priorities of the dev team (I understand there are way more important stuff to work on in the short term), would you accept a PR that would bring such a feature ?

Thank you for your time and your awesome work,
JabX

**Comment by bpasero** [comment]
It was our explicit UX decision to keep the explorer very light and not use icons. We might add support for extensions to add decorations to the explorer but currently this is not possible and not planned.

**Comment by bpasero** [comment]
Closing, this is not our intent with VS Code currently.
