### ISSUE TITLE
Color shades dont change in one go

### ISSUE THREAD

**Issue by kthorecha** [microsoft/vscode#123004]
Issue Type: <b>Bug</b>

So whenever there's some change in some code for eg.
1. commenting a part of code, those parts should reflect // comment color green automatically but it shows green only on some parts of commented code.
2. a new object or code if copied from any existing and pasted elsewhere it's color code freezes to brown and doesn't match for intended variables and values color.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.53GB free)|
|Process Argv|--crash-reporter-id 591a3b20-3259-45bf-ac6d-b60441c737fc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
vscode-language-babel|mgm|0.0.31
vscode-docker|ms-|1.12.1
remote-wsl|ms-|0.54.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by JacksonKearl** [comment]
Could you please provide the language in question here and screenshots of the problem cases?
