### ISSUE TITLE
Native exception when launching conpty: EBUSY: resource busy or locked, open '\.\pipe\conpty-5995336.540991683-in

### ISSUE THREAD

**Issue by lianjy357** [microsoft/vscode#123056]
Issue Type: <b>Bug</b>

error message:
A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-5995336.540991683-in')。
=========
I click to open the terminal, but it prompts me with an error message, and I can't open the terminal. I also tried to restart vscode, but still did not open the terminal normally

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.39GB free)|
|Process Argv|--crash-reporter-id b13d5e36-f07f-4470-8c1a-aacbbdb68ec1|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by swhuluwa** [comment]
I also encountered this problem.

**Comment by meganrogge** [comment]
any errors in Help => Open Developer tools -> console?

**Comment by zhongzepeng** [comment]
> 帮助=>打开开发人员工具->控制台中是否存在任何错误？

![image](https://user-images.githubusercontent.com/19171153/117744636-aa01ee80-b23b-11eb-97dc-cc0a6f306eae.png)

**Comment by zhongzepeng** [comment]
> Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
> 
> /label "needs more info" integrated-terminal

I have quit all anti-virus software, but the problem still exists, I can only roll back the version

**Comment by ffjtt** [comment]
我也是更新后出现这个问题，安装以前的版本（我的是1.52.1）就可以了

**Comment by rockbyo5** [comment]
having the same issue. Error clearly appeared once i updated to 1.52.2 as it was working fine a few minutes before and started when i restarted VSCode  for update.
everytime i open the terminal, i get the second error from this screenshot (the EBUSY: ressource busy or locked) at the bottom right notification.
Running Windows 10 64bit education N build 19042.985
![image](https://user-images.githubusercontent.com/13389884/119579303-2217fa80-bd8c-11eb-82a0-379493c398ae.png)

**Comment by lianjy357** [comment]
Version 1.57.1 is still not fixed and cannot be opened
![image](https://user-images.githubusercontent.com/38170938/122851292-493cfa00-d341-11eb-8773-8797aa60d87d.png)
![image](https://user-images.githubusercontent.com/38170938/122851307-4e9a4480-d341-11eb-9fb4-ce3ff213e035.png)
![image](https://user-images.githubusercontent.com/38170938/122851422-7ee1e300-d341-11eb-8434-7bde2afceab5.png)

**Comment by Oakington** [comment]
Same issue. v.1.55.2 works. Anything above does not. 

```
The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-1031264.3410738009-in').
```
Toggling ConPty has same issue. 
```
The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\winpty-conin-9320-1-1d7736b5d409d6e-19de1e7bb36828caf65415f6d0b86328').
```

May be local configuration dependent as my coworkers do not experience the issue. Any suggestions of what to try are appreciated.

**Comment by Oakington** [comment]
Issue is not present when machine is boot into safe mode.

**Comment by lianjy357** [comment]
It can be used and run normally in version 1.55.2 and below, and all versions after this version cannot open the terminal. It seems that some updates have been made in the next version of 1.55.2, which caused the device to fail to operate normally. I have installed multiple versions, and this problem only occurs on some devices. The problem I have already had a screenshot above, and found that some netizens have asked the same question in Google search, and the related posts are to fall back to version 1.55.2. I hope to be able to make changes on the agenda as soon as possible. Because of this version, I can’t use some new features of vscode. 

---
chinese
在1.55.2版本及其以下是可以正常使用和运行的，从这个版本之后的所有版本，全部都无法打开终端。似乎在1.55.2的下一个版本做了什么更新，导致设备无法正常运行。我安装多个版本，只在部分设备才会出现这个问题。问题我在上面已经有截图，也发现在谷歌搜索中已经有网友提出相同的问题，相关的跟帖都是让其回退到1.55.2版本。我希望能够尽快提上日程进行修改，vscode因为这个版本，一些新特性我都没办法使用。

**Comment by lianjy357** [comment]
Cannot open the terminal even after upgrading to version 1.58.0

**Comment by zzlit** [comment]
version 1.58.2 same problem

**Comment by zhongzepeng** [comment]
version 1.59 same problem，When can handle？

**Comment by vipwangtian** [comment]
1.59.1, the same problem.

**Comment by lianjy357** [comment]
1.60 the same problem

**Comment by miyuehu** [comment]
What needs to be done next ？  @meganrogge

**Comment by lianjy357** [comment]
I have operated all the above methods, but I still can’t use the terminal correctly

**Comment by lianjy357** [comment]
https://github.com/microsoft/vscode/issues/130400#issuecomment-911871155
This is another article I wrote. The content and its detailed description of my system environment and various screenshots

**Comment by miyuehu** [comment]
There was no response for a long time
Please help us
@meganrogge

**Comment by Tyriar** [comment]
We are unable to reproduce this so we cannot action it. It seems to only happen in China so maybe there is something going on with your Windows environment that is blocking it.

**Comment by Oakington** [comment]
@Tyriar I am in New Jersey and experiencing the same issue. What further information can I provide about my windows environment that would help you reproduce this issue? Is there a way to get a more helpful error message? Does the conpty/winpty have a debug mode so that we can get better visibility into what is causing this?

**Comment by Tyriar** [comment]
@Oakington do you have any anti-virus software that could be blocking access?

**Comment by Oakington** [comment]
@Tyriar Cisco AMP for Endpoints. Corporate machine. No other user in the organization has the same issue.

**Comment by Tyriar** [comment]
@Oakington does anything interesting show up when you search handles for "conpty" inside the "Resource Monitor" application?

![image](https://user-images.githubusercontent.com/2193314/133288270-0dcb69e9-31ae-4f4b-b35d-e19e6801147f.png)

**Comment by Oakington** [comment]
There are a number of entries.
In & out named pipes as well as in & out worker named pipes as in your screenshot above.
There are also a number of conhost.exe entries. PID's all go back to code.exe
![image](https://user-images.githubusercontent.com/31699883/133290330-74246293-9575-41ab-ad12-cea5c2674b32.png)

**Comment by Oakington** [comment]
Just uninstalled hyper-v, docker, and windows terminal. EBUSY still present. It's been too long with this problem and I'm going to do a re-install of windows if there's no other suggestions.

**Comment by Oakington** [comment]
Possible USVFS problem as exhibited here? https://github.com/ModOrganizer2/modorganizer/issues/1519

**Comment by Tyriar** [comment]
@Oakington oh winpty didn't work either? I see it launched pwsh on the left there. Everything looks fine, I guess try uninstalling vscode, restarting Windows and reinstalling it? I'm out of ideas after that.

**Comment by lianjy357** [comment]
@Tyriar Docker and VMware Workstation Pro software have been installed on my windows 10 computer. Will this cause registry problems, or is it related to hardware? My colleague and I use the same windows installation package and the same hardware, except that he has not installed docker and other virtual environment software

**Comment by Oakington** [comment]
@Tyriar It seems to be an issue with node-pty's implementation. I receive the same error when trying to launch [Hyper](https://hyper.is/)
![image](https://user-images.githubusercontent.com/31699883/135326124-20536f51-de5f-4f7f-9f22-3915f3e92452.png)

**Comment by PandaWei** [comment]
Is there any progress for this problem ？ I have the same problem。

终端进程启动失败: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-1153576.73404352-in')。
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
fire @ event.ts:577
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
_onProcessExit @ terminalInstance.ts:1401
async function (async)
_onProcessExit @ terminalInstance.ts:1330
(anonymous) @ terminalInstance.ts:1290
Promise.then (async)
_createProcess @ terminalInstance.ts:1288
(anonymous) @ terminalInstance.ts:373
async function (async)
(anonymous) @ terminalInstance.ts:372
Promise.then (async)
ei @ terminalInstance.ts:370
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
createInstance @ terminalInstanceService.ts:62
addInstance @ terminalGroup.ts:298
p @ terminalGroup.ts:282
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
createGroup @ terminalGroupService.ts:143
_createTerminal @ terminalService.ts:1309
createTerminal @ terminalService.ts:1273
async function (async)
createTerminal @ terminalService.ts:1227
run @ terminalActions.ts:1670
handler @ actions.ts:569
y.handler @ commands.ts:90
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
(anonymous) @ menubarControl.ts:716
run @ actions.ts:154
runAction @ actions.ts:190
run @ actions.ts:181
onClick @ actionViewItems.ts:168
(anonymous) @ menu.ts:489
setTimeout (async)
(anonymous) @ menu.ts:488

**Comment by miyuehu** [comment]
Why ？？？ Who can help us ？？？Too long 

@Tyriar If you can't solve it, you can let other colleagues solve it !!!

**Comment by DirtyJerz** [comment]
Tried insiders build today hoping the above node-pty commit would help. Issue still present. Is node-pty 0.11-beta11 included in 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e?

Version: 1.63.0-insider (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-06T21:54:39.104Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Oakington** [comment]
Tried insiders build today hoping the above node-pty commit would help. Issue still present. Is node-pty 0.11-beta11 included in 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e?

Version: 1.63.0-insider (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-06T21:54:39.104Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by vipwangtian** [comment]
I solved this problem by removing all anti-virus softwares, not only turn it off.

**Comment by yuantingting123** [comment]
I rollback version to 1.52.1,it fixed!

**Comment by Tyriar** [comment]
@yuantingting123 you're opening yourself up to security vulnerabilities and losing a year of development by doing that 😕

**Comment by lianjy357** [comment]
I changed to a new computer, from Windows to Mac, and it can be used normally. Is this a solution? I hope this problem can be tracked until it can be solved and help more friends.

**Comment by rzhao271** [comment]
I noticed that no one has directly responded to https://github.com/microsoft/vscode/issues/123056#issuecomment-947781133.

The screenshot below is from https://github.com/microsoft/vscode/issues/130400#issuecomment-912211475. I highlighted one of the lines in yellow.
![Screenshot showing highlighted line with fold marker](https://user-images.githubusercontent.com/7199958/155247074-da262eec-2c9f-4df5-9468-a88232bceeef.PNG)

Can someone facing this problem please do a trace like https://github.com/microsoft/vscode/issues/130400#issuecomment-912211475, press the triangle in the highlighted section above (within their trace) to expand it, and then screenshot or copy over the info?
