### ISSUE TITLE
terminal.integrated.cwd ignored after updating to 1.56

### ISSUE THREAD

**Issue by WyattGosling** [microsoft/vscode#123029]
I use multi-root workspaces. In my .code-workspace folder I configure the "terminal.integrate.cwd" setting. After updating to 1.56, I find this setting is getting ignore. Instead, the initial working directory for new terminals is the path of the workspace folder the most recently edited file belongs to.

I saw settings related to terminal windows were changed in 1.56, but [the current docs](https://code.visualstudio.com/docs/editor/integrated-terminal#_open-at-a-specific-folder) suggest this wasn't meant to be changed. The settings editor does not warn that this setting is deprecated nor unknown.

**Comment by WyattGosling** [comment]
I noticed while filing a separate issue that there should have been a bug-report template that simply wasn't there:

- VS Code Version: 1.56
- OS Version: Red Hat Enterprise Linux Server release 7.7 (Maipo)

I've tested on macOS version 11.2.3 and do not see the issue there. That is odd. I need to use the remote extension to try it on Red Hat, which doesn't work with --disable-extensions. I did manually try disabling all extensions except the Remote - SSH extension but the problem persisted.

Steps to Reproduce:

1. Open a multi-root workspace
2. Set "terminal.integrate.cwd" to a path in the `.code-workspace` file for the workspace.
3. Open an intergrated terminal:
    1. Using ctrl+`
    2. Using "Terminal: Create New Integrated Terminal (With Profile)" from the command palette.
    3. Using the + button in the integrate terminal UI
4. Notice in all the above cases, the path is not the path configured but instead either:
    1. The "path" of the workspace folder of the file that has been edited most recently.
    2. If no file has been edited in the current window, the "path" of the first workspace folder that is defined.

**Comment by ina6ra** [comment]
I had a similar problem.
Resolved by reverting to 1.55.2.
https://code.visualstudio.com/updates/v1_55

**Comment by ina6ra** [comment]
I'm windows10 but it seems that I'm having the same problem on mac and linux.
https://github.com/microsoft/vscode/issues/123031

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/121470#issuecomment-828525577

Set `"terminal.integrated.allowWorkspaceConfiguration": true` to get this to work

**Comment by WyattGosling** [comment]
Thanks. The workaround works.

Could this have been put in either the [release notes](https://code.visualstudio.com/updates/v1_56) or the [terminal docs](https://code.visualstudio.com/docs/editor/integrated-terminal). I get that this workaround is temporary until Trusted Workspaces come, but this was a breaking change.

**Comment by Tyriar** [comment]
@WyattGosling done, thanks. Sorry about the hassle.

**Comment by ina6ra** [comment]
@Tyriar Thank you, I solved it.
The yellow underline remains in settings.json

![image](https://user-images.githubusercontent.com/48197/117378411-4eb8bf00-af10-11eb-96f7-76186dd82359.png)
