### ISSUE TITLE
VScode window freezes after opening on Centos 7

### ISSUE THREAD

**Issue by micalcet** [microsoft/vscode#123032]
- VS Code Version: 1.56.0
- OS Version: CentOS Linux release 7.9.2009 (Core)

Steps to Reproduce:

1. run /usr/bin/code on a Centos 7 system
2. Note the window opens normally but immediately freezes.  After a few moments a system alert dialog opens;  "Application 'code' is not responding"

Additional info:  This occurred right after updating VS code to 1.56.0 from the VS code website; code-1.56.0-1620166346.el8.x86_64.rpm.  I tried this earlier on another Centos 7 system with the same result, the window freezes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose` ?

**Comment by gsutra** [comment]
Same on my centos 7.9.
I solved it by downgrading vscode to 1.52.

**Comment by deepak1556** [comment]
@gsutra what was the version of vscode you had installed before downgrading to `1.52`, please install gcc-5 or higher toolchain to fix the freezing issue.

**Comment by micalcet** [comment]
[issue_123032.log](https://github.com/microsoft/vscode/files/6438619/issue_123032.log)
The verbose output is about 62k, kinda long.  Thanks for looking at this.

**Comment by deepak1556** [comment]
@micalcet thanks for the log, you are hitting https://github.com/microsoft/vscode/issues/115784. Can you install gcc-5 or higher toolchain to fix the issue.

Also what version of vscode did you have before updating to `1.56`

**Comment by micalcet** [comment]
I'm not having luck finding a repo for gcc-5.  Looking for an rpm other spots now for gcc-5.  

Not sure but I think I had 1.52 installed and working.  I might be able to find my install logs and determine that for sure

**Comment by deepak1556** [comment]
@micalcet there are pointers to install newer gcc on your distro in https://github.com/microsoft/vscode/issues/115784, can you try that. Merging this to https://github.com/microsoft/vscode/issues/115784
