### ISSUE TITLE
The underscore on the terminal is not displayed

### ISSUE THREAD

**Issue by jeehuang** [microsoft/vscode#123077]
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-50-generic
![2021-05-06 14-22-37屏幕截图](https://user-images.githubusercontent.com/35717799/117251131-d2be6880-ae76-11eb-95f8-82a3ef97ae53.png)

**Comment by MJKirk** [comment]
I am seeing the same propblem (same versions of vscode as JankHuang).
There was an old issue with the same problem (https://github.com/microsoft/vscode/issues/35901) which got fixed a while back, so some sort of regression?

**Comment by Tyriar** [comment]
Can you open devtools and inspect the terminal's dom structure? I suspect webgl isn't supported on your platform which is causing you to revert to the canvas renderer in which case the workaround would be:

```
"terminal.integrated.gpuAcceleration": "off"
```

**Comment by JankHuang** [comment]
> I am seeing the same propblem (same versions of vscode as JankHuang).
> There was an old issue with the same problem (#35901) which got fixed a while back, so some sort of regression?
> The temporary fix from there of altering the fontsize from 14 to 13 or 15 still works.

@MJKirk Thank you very much, the problem has been solved.

**Comment by JankHuang** [comment]
> Can you open devtools and inspect the terminal's dom structure? I suspect webgl isn't supported on your platform which is causing you to revert to the canvas renderer in which case the workaround would be:
> 
> ```
> "terminal.integrated.gpuAcceleration": "off"
> ```

@Tyriar Thank you for your reply. but this is not for me.thank you

**Comment by MJKirk** [comment]
> Can you open devtools and inspect the terminal's dom structure? I suspect webgl isn't supported on your platform which is causing you to revert to the canvas renderer in which case the workaround would be:
> 
> ```
> "terminal.integrated.gpuAcceleration": "off"
> ```
Sure, I can do this. What am I looking for to see if webgl is or isn't working?
(Can you reopen this issue, or do we have to start a new one?)

**Comment by Tyriar** [comment]
@MJKirk webgl will show 3 canvases, the "canvas" renderer will show 4

**Comment by MJKirk** [comment]
Within the `<div class="xterm-screen">`, there's another `<div>` (class="xterm-screen") and then 3 `canvas` elements.
One with `class="xterm-link-layer"`, one with `class="xterm-cursor-layer"`, and the third has no class attribute. 
And I tried 
```
"terminal.integrated.gpuAcceleration": "off"
```
and it doesn't help.
Although changing that setting to "on" does makes the underscores visible (it was on auto before)

**Comment by Tyriar** [comment]
> Although changing that setting to "on" does makes the underscores visible (it was on auto before)

I think `on` and `auto` are meant to work basically the same, just the `auto` will fallback to the dom renderer (ie. `off`) when it's slow.

> Having fiddled with the gpu setting (but set it back onto auto again), there's now some strange behaviour where if I open a new terminal it looks okay there, but I can make them vanish again by switching the font size down to 13 then back to 14.

Sounds like https://github.com/xtermjs/xterm.js/issues/3280

**Comment by mirao** [comment]
Have the same issue in 1.56 with terminal font size = 14. I think it started in this version or in 1.55.
I can confirm the workaround "change font size to 13 or 15" (but those sizes are impractical for me). Disabling of GPU acceleration doesn't help.

**Used HW/SW:**
- Dell Precision 7530, NVIDIA Quadro P1000
- Ubuntu 20.04
- VSCode 1.56.0

**Comment by tknapstad** [comment]
> Can you open devtools and inspect the terminal's dom structure? I suspect webgl isn't supported on your platform which is causing you to revert to the canvas renderer in which case the workaround would be:
> 
> ```
> "terminal.integrated.gpuAcceleration": "off"
> ```

For me, the solution was to force terminal.integrated.gpuAcceleration to "on". If it is set to "auto" or "off", my underscores disappear.

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.14-200.fc33.x86_64

**Comment by kielnino** [comment]
I have the same issue with missing underscores at fontSize 14. But I think it maybe releated to the spacing at the bottom of the terminal. If I drag the terminal window larger, and then the last line is no longer rendered at the bottom of the screen, the underscore is visible again. 

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-54-generic

**Comment by FStefanni** [comment]
Hi,

I confirm the same issue on Linux (Debian Bullseye):
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.10.0-6-amd64
```

Setting the font to 13 or 15 is a valid workaround for me, even if 13 is too small and 15 too large for my tastes...

On my Windows installation, it works fine instead...

Regards

**Comment by howardjones** [comment]
I'm also seeing this with Ubuntu 18 and current VSC - got as far as reporting a bug in another package that was "generating bad IDs" before I realised that VS Code was doing this... :-/ 

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic
```

**Comment by rayfoss** [comment]
This works for me... as long as I use an **odd numbered** font size:

- **all** fonts experience this behavior, indicating it's not a font issue.
- I have a 4K monitor on an Nvidia graphics driver
- GNU bash, version 5.1.8(1)-release (x86_64-unknown-linux-gnu)
- 
```
"terminal.integrated.fontFamily": "DejaVu Sans Mono",
"terminal.integrated.fontSize": 15
```

**Comment by arash-bizcover** [comment]
> Can you open devtools and inspect the terminal's dom structure? I suspect webgl isn't supported on your platform which is causing you to revert to the canvas renderer in which case the workaround would be:
> 
> ```
> "terminal.integrated.gpuAcceleration": "off"
> ```

This not working for me, just make font a bit bigger, still Underscore invisible. 

Ubuntu 18.04

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```

**Comment by FStefanni** [comment]
Hi,

> 
> /duplicate of #123077

@meganrogge I believe there is an error... this issue has been marked as a duplicate of itself.
Please re-open it.

Regards.

**Comment by trampster** [comment]
Please don't close this issue without an actual fix!

Many duplicates of this have been closed because someone posted a work around. We shouldn't need a workaround, vscode on linux should display underscores by default without needing any work around.

**Comment by trampster** [comment]
Also occurs on Ubuntu 12.04.2 LTS

**Comment by saeedshojaee** [comment]
I had the same issue, and found some closed issues, all proposing to set a specific `fontsize` or `fontfamily`. I have to say it worked for some `fontsize`, but `fontsize` is not the culprit. The issue comes from `gpuAcceleration` set to `auto` or `canvas`. I assume for a certain font size or font family `canvas` can not render the underscore character. I solved my issue with setting ```"terminal.integrated.gpuAcceleration": "on"```

**Comment by Tyriar** [comment]
@saeedshojaee thanks for the info, there appears to be an issue with webgl not being used when it should be if that fixes it for you. Do you see any bad rendering performance or warnings in the devtools console when you use gpuAcceleration: on?

**Comment by Tyriar** [comment]
To clarify, the `"terminal.integrated.gpuAcceleration": "canvas"` by design cannot show underscore for some fonts as it appears below the allowed character cell size. Basically the fix is to use the much better in almost every way webgl renderer (auto should work, but on forces).

**Comment by Tyriar** [comment]
I've pushed a change here which no longer caches the suggested renderer across windows and instead re-evaluates it on every window. So when you're using auto if you happen to run into this problem again where you're not getting webgl but you should, restarting the window would fix it.

**Comment by trampster** [comment]
I'm confused, not having underscores was my out of box experence (I didn't change any settings), Your telling me that now having underscores is by design and I have to change the settings to get them to work.

No I'm sorry your default configuration should work and if it doesn't you should fix it. This is clearly a bug.

**Comment by trampster** [comment]
My "terminal.integrated.gpuAcceleration" is set to 'auto'. If I set it to 'on' then underscores work. But according to you 'auto' should work but it doesn't.

Do I need to raise a new issue saying that the 'auto' setting doesn't work.

If "canvas" doesn't work 'by design' then it is bad design and the design should be fixed, underscores are not an optional part of the terminal. If "canvas" cannot be fixed then, why is it the default for me when set to "auto" ie my out of the box experence is a broken terminal because of this.

**Comment by Tyriar** [comment]
@trampster Yes it is a bad design, the fix is to use webgl. Canvas is still there as a fallback for browsers that don't support webgl2 because no underscores when some fonts are used is still a better situation than the slow dom renderer. 

> Do I need to raise a new issue saying that the 'auto' setting doesn't work?

That's exactly what the linked commit fixes.

**Comment by trampster** [comment]
I hope so, will keep and eye on it to see if the next release fixes it.

**Comment by alexr00** [comment]
Are there steps I can use to verify?

**Comment by meganrogge** [comment]
I believe just using an underscore on the terminal 😄 . Works for me

**Comment by Tyriar** [comment]
FYI I'm putting together a better fix in https://github.com/microsoft/vscode/issues/130967 that will fix the underscore even on the canvas renderer.
