### ISSUE TITLE
No longer scaling toolbar icon

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#123041]
Issue Type: <b>Bug</b>

Install vscode-print from https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print and observe that the icon is clipped. This is new behaviour.

![image](https://user-images.githubusercontent.com/5498936/117230497-908a2c80-ae60-11eb-845a-8f4c5abcb583.png)

To be clear, I am the author of vscode-print and it is entirely possible that the icon asset is non-compliant in some way that historically was compensated by scaling. I could edit the asset easily; this is SVG and not a bitmap. I was about to do so when it occurred to me that this probably affects any number of other extensions.

I can change the asset to fix this and foist a gratuitous update on all my users or you could go back to scaling. Let me know which you think is appropriate.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8260U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.87GB (8.88GB free)|
|Process Argv|--crash-reporter-id 2468ae4e-d85d-44d9-beb4-ad13f8b9e08e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.3.2
vscode-sql-formatter|adp|1.4.4
markdown-mermaid|bie|1.9.2
path-intellisense|chr|2.3.0
vscode-postgres|cko|1.1.17
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
dotnet-test-explorer|for|0.7.5
mdmath|goe|2.5.1
vscode-peacock|joh|3.9.1
eml|lei|0.4.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.12.1
vscode-language-pack-fr|MS-|1.56.1
vscode-language-pack-ja|MS-|1.56.1
csharp|ms-|1.23.11
remote-containers|ms-|0.177.0
remote-wsl|ms-|0.56.1
azure-account|ms-|0.9.8
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
vscode-print|pdc|0.9.3
quicktype|qui|12.0.46
autoimport|ste|1.5.4
html-preview-vscode|tht|0.2.5
vscode-mermaid-editor|tom|0.11.0
vscode-arduino|vsc|0.4.2

</details>

**Comment by giscafer** [comment]
same issue 

```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```

**Comment by misolori** [comment]
@joaomoreno not sure if this was intentional or not, but the background size property was omitted when we made the hover feedback changes https://github.com/microsoft/vscode/commit/fca4457adaad82ea881fc52f5e5d781bdc0dbfec#diff-addd7132dee13457b17c0ce8af86416722108e69b8a60d63a865f524a8323f5f

**Comment by misolori** [comment]
@PeterWone btw our api docs specify the command icons should be 16x16 https://code.visualstudio.com/api/references/contribution-points#Command-icon-specifications

**Comment by PeterWone** [comment]
When the observed behaviour of the platform disagrees with the documentation for fifty consecutive releases the documentation is wrong.

**Comment by PeterWone** [comment]
Nice work chaps. Super fast turnaround.
