### ISSUE TITLE
Can't run NoteBooks

### ISSUE THREAD

**Issue by Urcelay97** [microsoft/vscode#123084]
Issue Type: <b>Bug</b>

1. Open a ipynb file (with julia kernel)
2. Run the file
3. Nothing happens

When I click the run button in the cell, nothing happens.

VS Code version: Code - Insiders 1.57.0-insider (fe23c2041f848d6c2f6bd27875112a37bcc82f84, 2021-05-06T05:16:25.564Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.05GB free)|
|Process Argv|--crash-reporter-id a90c1f06-d6f3-4af9-a87b-6e8ed6ff83e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|3.0.41
language-julia|jul|1.1.38
python|ms-|2021.5.815083650-dev
vscode-pylance|ms-|2021.5.1-pre.1
jupyter|ms-|2021.6.812916528

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2ct:30286873
vscorehov:30295781
3f5j7703:30294757

```

</details>

**Comment by shug1565** [comment]
same issue here. Just updated insider to the newest version and jupyter notebook stops working (no response at all when executing a cell).
