### ISSUE TITLE
Trailing comma warning in built-in `settings.json`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#123039]
- VS Code Version: v1.56.0
- OS Version: Windows

Steps to Reproduce:

1. Use `workbench.action.openGlobalSettings`
2. Warning shows up
3. Click the warning
4. The built-in `settings.json` will be opened (_note, this file is read-only, not the one under `User` folder_):    

![image](https://user-images.githubusercontent.com/28700378/117229423-93c7ed00-ae4d-11eb-9425-18fa5215d394.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
similar to #105414 and #103009 but on a different file.

**Comment by danleepw** [comment]
Having the same problem in my vscode

**Comment by roblourens** [comment]
It seems like something is off with that file, the comment is not syntax highlighted, and the file ends with ] instead of }?

**Comment by wenfangdu** [comment]
@roblourens The comment is syntax highlighted per my customization, and it's in "JSON with Comments" mode, it's a read-only file, not the one under the `User` directory, seems like a built-in file.

**Comment by roblourens** [comment]
I guess this is the default settings file then? Can you show more context of the file or tell me which extension that pdf setting is coming from?

**Comment by wenfangdu** [comment]
@roblourens It only occurred in v1.56.0, before was fine.

![image](https://user-images.githubusercontent.com/28700378/117381817-807d5600-af0f-11eb-825e-d83577aa8980.png)

The pdf extension id is `yzane.markdown-pdf`.

**Comment by danleepw** [comment]
any update?

**Comment by muuvmuuv** [comment]
Looking through the file shows that it is an auto generated config from all extensions which configs are available, looks like it is used for searching and the settings GUI. 

Possible fixes on VS Code side:

- Checking if last object is last extension config loaded to prevent last comma being set
- Allow built-in `json(c)` to remove last comma and format after generation (#76505)
- Exclude warnings for built-in files

IMO all the above should be considered.

![Bildschirmfoto 2021-05-31 um 11 12 57](https://user-images.githubusercontent.com/11534760/120170446-4139e080-c201-11eb-8a1f-d2b7b5c2df15.png)

**Comment by alexr00** [comment]
I can't get the error to show in either 1.57 or 1.58. However, on both I do still see a trailing comma in the defaults file.

**Comment by sandy081** [comment]
To verify:

- Open split-json settings editor using setting `"workbench.settings.useSplitJSON": true`
- Make sure there is no warnings in the problems view.
