### ISSUE TITLE
Version control icons became minuscule with latest update

### ISSUE THREAD

**Issue by ylefebvre** [microsoft/vscode#123036]
Issue Type: <b>Bug</b>

Go to Source Control tab and look at the icons for all source projects. The commit and other icons are tiny!

https://imgur.com/a/mmJc04T

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (24.41GB free)|
|Process Argv|--crash-reporter-id c140cd00-e08b-4c0a-8002-90bd79eae591|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
fontsize-shortcuts|fos|1.5.0
vscode-edit-csv|jan|0.5.8
vscode-wordpress-hooks|joh|0.5.4
svn-scm|joh|2.13.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vscnewfilehidden:30294815
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by gjsjohnmurray** [comment]
Mine don't seem to have been affected:

![image](https://user-images.githubusercontent.com/6726799/117232881-f69f9100-ae19-11eb-9234-fe7649ee7666.png)

Please post your screenshot.

**Comment by mhutchie** [comment]
This is also affecting users of Git Graph, which contributes a command to the `scm/title` menu.

Issue raised by a Git Graph user: https://github.com/mhutchie/vscode-git-graph/issues/502 (with screenshot)

**Comment by deepnight** [comment]
Hello,
It happened to me with latest Vscode + [GitGraph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) extension which adds an icon to the SCM bar.
For some reason, the icon added by the [GitHub Pull request](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension isn't affected.

![image](https://user-images.githubusercontent.com/1671695/117281595-1b205b00-ae64-11eb-8e58-00066d393eb0.png)

**Comment by mhutchie** [comment]
@deepnight,

I just had a look at the GitHub Pull Request Extension, they use a [Visual Studio Code Octicon](https://code.visualstudio.com/api/references/icons-in-labels) as the icon for the command ([see here](https://github.com/microsoft/vscode-pull-request-github/blob/main/package.json#L401)), as the Octicon collection contains icons for many common Git commands.

In contrast, Git Graph uses a [SVG icon](https://github.com/mhutchie/vscode-git-graph/blob/develop/package.json#L48-L51) bundled in the extension, as the extension's icon is naturally not included in the Octicon collection. The SVG's used by the command that Git Graph contributes exactly follows the Visual Studio Code [Command-icon-specifications](https://code.visualstudio.com/api/references/contribution-points#Command-icon-specifications).

**Comment by mhutchie** [comment]
For reference, I can't replicate it (even using a very similar system to @deepnight).

```
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by mhutchie** [comment]
I've been able to replicate this issue, for me it only occurs when the SCM View contains multiple repositories.

The icon is tiny with multiple repositories:
![image](https://user-images.githubusercontent.com/5315753/117288392-cc4be300-aeae-11eb-9b0f-2edfbff03a2b.png)

The icon is the standard size with a single repository:
![image](https://user-images.githubusercontent.com/5315753/117288286-ae7e7e00-aeae-11eb-9451-5fc9bb721b56.png)

**Comment by erclu** [comment]
I just updated vscode to v1.56.0 and i'm having the same issue. My screen resolution is 1920x1080, same as yours @mhutchie . 

These are the steps i followed: 

- open a folder containing a git repository
- navigate to the source control view
- if not already visible, toggle the `source control repositories` view by right clicking on the `source control` header.
- result:
![image](https://user-images.githubusercontent.com/30255227/117287204-650c3f80-ae6a-11eb-91bb-57cbdb430102.png)

Alternatively:

- open a folder containing multiple git repositories OR a multi-root workspace
- navigate to the source control view
- result:
![image](https://user-images.githubusercontent.com/30255227/117288377-b9fc8580-ae6b-11eb-9c7c-177ebfa8e146.png)

**Comment by modbw** [comment]
I have the same issue with the [GitGraph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) and [SVN](https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm) extension in a multi root workspace:

![image](https://user-images.githubusercontent.com/4498104/117290563-3ee89e80-ae6e-11eb-8431-e91e6d8f014e.png)

**Comment by WESquad-spires** [comment]
I can also reproduce the same issue with [Gitmoji](https://marketplace.visualstudio.com/items?itemName=Vtrois.gitmoji-vscode) and [GitGraph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)

![image](https://user-images.githubusercontent.com/43609804/117297110-1c5a8380-ae76-11eb-9fae-8a372a72d8ec.png)

**Comment by heartacker** [comment]
don't forget that action icon have the same problem.
