### ISSUE TITLE
Buttons have become smaller since VS code was updated to 1.56.0

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#123076]
- VS Code Version: 1.56.0
- OS Version: Windows 7

Steps to Reproduce:

1. Update VS Code to 1.56.0
2. Compare the buttons with those in the previous version.

![image](https://user-images.githubusercontent.com/8168391/117250914-807d4780-ae76-11eb-84b0-56c6ffa5ac13.png)
> Top: VS Code 1.56.0
> Bottom: VS Code 1.54.0 Insider

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
With the [improvement of hover feedback](https://code.visualstudio.com/updates/v1_56#_improved-action-hover-feedback) we have updated our icon padding/margins and they are a bit more compact but the icon itself is still the same size. So this is by design.

**Comment by infinnie** [comment]
Despite the intentions, it doesn’t look good.
