### ISSUE TITLE
Global search suggestion

### ISSUE THREAD

**Issue by dev-tvo** [microsoft/vscode#123094]
As a front-end developer, I find myself using the global search function all the time, as well as the 'files to include' input under it. When activating search, it automatically focusses the search box. Is it possible to add an option, that if I press tab, it goes to the next input right away, instead of the search options. I use a lot of keyboard shortcuts and right now I have to press tab 5 times to get to the next input. Hopefully this makes any sense. Here is a screen capture of what I mean.

https://user-images.githubusercontent.com/21953348/117277338-135eb780-ae60-11eb-9cd7-c4310276b584.mov

**Comment by roblourens** [comment]
You can press cmd/ctrl + down to move between the inputs quickly.

**Comment by dev-tvo** [comment]
@roblourens That works, but it seems counter-intuitive. I was wondering if the cmd/ctrl + down combination could be remapped to tab, or make it a toggle/switch.
