### ISSUE TITLE
Persistent Dirty Save

### ISSUE THREAD

**Issue by luketevers** [microsoft/vscode#123027]
Issue Type: <b>Bug</b>

I can't reproduce this, and I have tried everything short of nuclear weaponry. I have a file that is a 'Dirty save' no matter what I do. I've tried the 'overwrite' button, the save previous button, moved the folder, deleted the folder and re-downloaded, deleted the file with rm -rf, deleted the file with sudo rm -rf, deleted the folder with rm -rf/sudo rm -rf. I can not make the madness stop, please send help and whiskey. I did search for similar issues and I couldn't seem to find anything related.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|. --crash-reporter-id 7050aa80-2028-4c45-b814-bb4564391472|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
formatter-pug|ale|0.0.1
pug|ama|1.0.1
vscode-css-modules|and|1.2.3
vscode-custom-css|be5|5.0.2
vscode-intelephense-client|bme|1.7.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
sass-lint|gle|1.0.7
vscode-atom-sass-snippet|glu|0.0.3
vscode-react-typescript|inf|1.3.1
twig-language-2|mbl|0.9.2
vscode-language-babel|mgm|0.0.31
code-beautifier|mic|2.3.3
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
vscode-stylelint|sty|0.86.0
sass-indented|syl|1.8.16
twig|wha|1.0.2
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by luketevers** [comment]
yessir 
![dirty_save](https://user-images.githubusercontent.com/24533114/117333738-151f7f80-ae4e-11eb-8e01-14e4336d1774.gif)

**Comment by luketevers** [comment]
yessir
![dirty_save](https://user-images.githubusercontent.com/24533114/117334375-c6261a00-ae4e-11eb-8bde-a73e3399e784.gif)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by luketevers** [comment]
Hey @bpasero, I did try that. My extensions are a lot cleaner now, but nothing seems to have effected that file, still the same behavior. v strange

**Comment by luketevers** [comment]
Hey @bpasero, I sussed it out, It looks like I might have run vscode with sudo some time ago and saved that file. So it was persisting through admin privileges. I have fixed this now. I appreciate the assistance.

Thanks,
Luke
