### ISSUE TITLE
Wrong color schema for TSX files

### ISSUE THREAD

**Issue by microshine** [Microsoft/vscode#12303]
- VSCode Version: 1.5.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Here is good formated TSX code
![image](https://cloud.githubusercontent.com/assets/7333669/18660422/f6f1c612-7f18-11e6-9968-e2b6774f36c0.png)
If I add space char into `</List>`, then I've got wrong color format
2. 
![image](https://cloud.githubusercontent.com/assets/7333669/18660472/4a43e30e-7f19-11e6-84d5-7493400a8d1f.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11017
