### ISSUE TITLE
error highlight

### ISSUE THREAD

**Issue by Sentinellium** [microsoft/vscode#123064]
Issue Type: <b>Bug</b>

After the last update(i think) the errors started to highlight(python) live when before it was only on save. Auto saving with linting on save is disabled.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.29GB free)|
|Process Argv|--crash-reporter-id 1be23271-5b1f-42b1-8a26-ddb3bce8ae2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.3
kite|kit|0.142.0
MagicPython|mag|1.1.0
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.5.0
jupyter|ms-|2021.6.811652604
cpptools|ms-|1.3.1
material-icon-theme|PKi|4.6.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by Sentinellium** [comment]
it also seems to put errors in problems tab which didn`t happen before

**Comment by Sentinellium** [comment]
Also checked on the march version, it works fine

**Comment by JacksonKearl** [comment]
\extPython
