### ISSUE TITLE
Custom dialog background dimming is eye-straining

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#123080]
```js
"window.dialogStyle": "custom",
```
The background dimming (especially in light themes) does not feel good. It would be better if there were no dimming like in the native dialogs. But if this feature is 100% needs to be there, please make a transition of at least 1 second between states.

**Comment by infinnie** [comment]
Totally agree.

**Comment by bpasero** [comment]
At least on macOS that dimming seems standard:

![image](https://user-images.githubusercontent.com/900690/117263957-0edfd200-ae53-11eb-8eb9-585166c79d37.png)

**Comment by sbatten** [comment]
on windows there is no dimming with native but there is also a lot more contrast because those dialogs looks totally different. I could try out a transition on Windows to see if folks like this
