### ISSUE TITLE
Should enable syntax highlighting even if "virtualWorkspaces": false 

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#123038]
I am a contributor of [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop). The extension does not support virtual workspaces. So, we have set `"virtualWorkspaces": false` in our `packages.json`.

However, we want to enable syntax highlighting  with TextMate grammars also in virtual workspaces. The [document](https://code.visualstudio.com/updates/v1_56#_define-whether-your-extension-supports-a-virtual-workspace)  does not clarify whether the syntax highlighting is enabled even if "virtualWorkspaces": false. If it is not enabled, it should be enabled.

**Comment by aeschli** [comment]
I see what you mean, but this needs some discussion. We currently deactivate the whole extension and we renderer it like that in the extensions viewlet.

**Comment by tamuratak** [comment]
Please notice that we have to adapt to a virtual filesystem which Live Share provides with the scheme`vsls`. https://github.com/MicrosoftDocs/live-share/issues. On the guest side, we edit files on the virtual filesystem by Live Share. If the whole extension disabled, syntax highlighting is also disabled on the guest side.

**Comment by tamuratak** [comment]
Thank you for your clarification.

We would choose the following one if needed.

> Have "virtualWorkspaces": true` and use context keys to disable the functionality that can not work on virtual file systems

**Comment by gjsjohnmurray** [comment]
> We discussed this in the team. For now we don't want to stick to disabling the whole extension when` "virtualWorkspaces": false` is set

@aeschli I think the "don't" in the above sentence shouldn't be there, right?

**Comment by aeschli** [comment]
Yes, I removed the `don't` :-)

**Comment by aeschli** [comment]
Closing the issue, no changes planed on our side.
