### ISSUE TITLE
terminal's letter spacing too wide after an updating

### ISSUE THREAD

**Issue by cotitan** [microsoft/vscode#123099]
Issue Type: <b>Bug</b>

- startup vscode
- open an project
- open the terminal on the bottom tab
- the new-open terminal's letter spacing is wide, nearly the same as the width of letter.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 7, 4|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_11926367 --crash-reporter-id 0c9f1762-adcf-415f-a2f0-69ba618f4832|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
alignment|ann|0.3.0
vscode-eslint|dba|2.1.20
gc-excelviewer|Gra|3.0.41
thrift-syntax-support|mrk|0.0.6
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
cpptools|ms-|1.3.1
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by jonasgloning** [comment]
Hi cotitan,

could you have a look at the `editor.fontFamily` and `terminal.integrated.fontFamily` settings? If a missing font is set there, the terminal looks like in your description.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/34194370/117281461-f75d1500-ae63-11eb-8f8a-9b0a96104a64.png">

**Comment by Gordin508** [comment]
Had the same issue on version 1.55.2, commit 3c4e3df9e89829dce27b7b5c24508306b151f30d.
I opened the settings editor with _ctrl+,_ and found the values of `editor.fontFamily` to be `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` and `terminal.integrated.fontFamily` to be empty. Interestingly, reclearing the latter value (by typing in one character and deleting it again) fixed the issue for me, it does not reappear when restarting vscode or switching workspaces either.

**Comment by cotitan** [comment]
https://github.com/microsoft/vscode/issues/123099#issuecomment-833406907

**Comment by cotitan** [comment]
@jonasgloning Thank you, follow your description, I removed font 'Monaco', and the problem solved. But I have Monaco in my sysytem (Monaco could be found in APP `Font book`).

**Comment by cotitan** [comment]
@Gordin508 I tried your solution but it doesn't worked for me.

**Comment by rainerbird** [comment]
Setting the terminal font fixes it but if I open up a new terminal the letter spacing just comes back again. It also comes back after restart
