### ISSUE TITLE
Debug bar buttons too close

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode#123098]
- VS Code Version:
- version: 1.56.0 (user setup)
提交: `cfa2e218100323074ac1948c885448fdf4de2a7f`
date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 6.1.7601
- OS Version:
- windows 7 x64

## maybe debug bar buttons are too close? (Than the previous version)
> ![TooCloseButtons.PNG](https://i.loli.net/2021/05/06/fZXwhj1SNRvagAV.png)

**Comment by isidorn** [comment]
@joaomoreno changed this, and i actually like the change. Thus closing as designed as we do not plan to fix
