### ISSUE TITLE
Color Theme Bug in C# -greyed out values when assigning 'new' object to an index

### ISSUE THREAD

**Issue by zspada** [microsoft/vscode#123035]
Issue Type: <b>Bug</b>

comparing 4 different string arrays syntax
1. no problems

```
string[] names = {
                new string("name1"),
                new string("name2"),
                new string("name3")
            };
```

2.no problems

```
            string[] altnames = {
                ("name1"),
                ("name2"),
                ("name3")
            };
```

3.no problems

```
string[] altnames2 = new string[3];
            altnames1[0] = ("name1");
            altnames1[1] = ("name2");
            altnames1[2] = ("name3");
```

4. (BUG) values ("name1", "name2", etc) here appear greyed out through every color theme after 1.56 update;
Reproduced when a specific index is defined using keyword "new" object all together.
Most noticable when assigning values to an array of objects and "new" is used.

```
            string[] bugnames = new string[3];
            bugnames[0] = new string ("name1");
            bugnames[1] = new string ("name2");
            bugnames[2] = new string ("name3");
```

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.89GB (55.30GB free)|
|Process Argv|--crash-reporter-id 58577e01-9d7b-4f3e-807c-609d511c7cdc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.11
material-theme|zhu|3.10.14

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by alexr00** [comment]
Can you share a screen shot of the incorrect syntax highlighting?

**Comment by zspada** [comment]
Here you go, hope this is useful.

![highlightbug156](https://user-images.githubusercontent.com/83736363/117306021-519eab80-ae4d-11eb-80f7-e352c521f32b.PNG)

**Comment by alexr00** [comment]
Thank you. I'm not able to reproduce this issue. It is likely caused by one of the extensions that you have installed.
