### ISSUE TITLE
Extra hash symbols in deprecation warning in settings.json

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#123068]
- VS Code Version: 1.56.0 (user setup), Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
- VS Code Version: 1.57.0-insider (user setup), Commit: b95b73b7b074f5dddccd57e5e290617f1a767ec1
- OS Version: Windows 10 21H1

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/12128514/117244731-ded80500-ae39-11eb-8ea8-f234defc5e35.png)

Does this issue occur when all extensions are disabled?: yes

**Comment by Tyriar** [comment]
I think this is by design.

**Comment by roblourens** [comment]
Yes, in the GUI context, it turns into a link

**Comment by bersbersbers** [comment]
> I think this is by design.

Maybe the design is wrong then :) never mind, I can live with it.
