### ISSUE TITLE
LUA function colorizing error

### ISSUE THREAD

**Issue by KJanos1396** [Microsoft/vscode#12308]
- VSCode Version:1.5.2
- OS Version:Win 10 Pro

Steps to Reproduce:
1. Simple load LUA file
2. LUA function is no colorizing 
   ![image](https://cloud.githubusercontent.com/assets/18537191/18663793/4917e79e-7f20-11e6-8537-37eb053925ed.png)

**Comment by chrmarti** [comment]
Cannot reproduce:

![screen shot 2016-09-20 at 7 51 23 am](https://cloud.githubusercontent.com/assets/9205389/18675591/b2f925e2-7f07-11e6-8a7f-30af956d9552.png)

Could you paste the source you have as text so I can try with that?

**Comment by KJanos1396** [comment]
This bug only come if  theme set as Light (Visual Studio) theme.

**Comment by chrmarti** [comment]
Indeed, using the Light theme reproduces the problem also with this simple snippet:
```
function ADDON:GetProfID(profname)
    if not profname then return end
end
```

**Comment by aeschli** [comment]
The Light (Visual Studio) theme doe not highlight functions and variables by design.

I recommend you to use the Light+ theme instead.
