### ISSUE TITLE
C# syntax highlighting breaks on line-ending null-conditional operator

### ISSUE THREAD

**Issue by Bbansjkl** [microsoft/vscode#123095]
Issue Type: <b>Bug</b>

When a line-ending null-conditional operator is used (e.g. when using the C# extension's "wrap call chain" quick action), all following code in the same file is highlighted incorrectly.

Code example:
```csharp
public class A {
    public void DoNothing() {
        string s = null;
        if (true) {}
        s?
          .Trim();
        if (true) {}
    }
    public void DoMoreNothing() {}
}
```

Video of the issue:  
![vsc-highlight-bug_edit_0](https://user-images.githubusercontent.com/39167840/117278450-11492880-ae61-11eb-9d22-6d62c72c9668.gif)

Note how the "if" in the line below the wrapped call, as well as the accessibility and return type of the second function change color.

I've disabled all extensions and checked with the Insider build, the issue persists. Restarting VSC doesn't change anything either.

Data from the issue reporter:

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.90GB free)|
|Process Argv|--disable-extensions --crash-reporter-id dfcd2920-79b0-4ecd-bfd2-65c5216d6c04|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30294816
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by Bbansjkl** [comment]
... I just noticed that the code preview above is also affected, so it's not a VSC-exclusive issue. I'm unsure where to report it then, though.

**Comment by alexr00** [comment]
We get our syntax highlighting grammar from https://github.com/dotnet/csharp-tmLanguage/, so I've moved this issue there: https://github.com/dotnet/csharp-tmLanguage/issues/207

Once the issue is fixed upstream, I'll pull in the update (usually about once per month).
