### ISSUE TITLE
autoReveal, but only when a file is explicitly selected

### ISSUE THREAD

**Issue by Rich-Harris** [microsoft/vscode#123020]
This is a repeat of #38899, which I think was closed erroneously as a dupe of #23902 — I can't reopen it because I missed the window before the bot locked it. The original comment, for convenience:

> Per #3062, the `explorer.autoReveal` setting controls whether the explorer will jump to the active file whenever it changes. That's good, because autoReveal is infuriating when the active file changes as a result of a tab being closed (whether because the user hit Cmd-W or clicked the 'x', or because the file was deleted via the explorer).
>
> But autoReveal can be very useful when the active file changed because the user explicitly selected an existing tab.
>
> I'd like to propose a third option besides `"explorer.autoReveal": true` and `"explorer.autoReveal": false` — perhaps something like `"explorer.autoRevealSelected": true`? With this option, clicking on a tab in the main view (even for the currently active file) would reveal the file in the explorer.

The `"explorer.autoReveal": "focusNoScroll"` setting added since this issue was initially raised doesn't solve it: the ideal behaviour is for the explorer to scroll to a file that was _explicitly selected_ by the user, i.e. by clicking on a tab or cmd-clicking in the terminal or using Cmd-P, etc. Framed differently, the explorer shouldn't scroll to the active file (and expand all parent folders, which is very annoying!) if it only became active because a different file was closed. Thank you.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
