### ISSUE TITLE
Version 1.56 breaks html forms in webviews

### ISSUE THREAD

**Issue by PhilippeFerreiraDeSousa** [microsoft/vscode#123058]
- VS Code Version: 1.56
- OS Version: ubuntu 18.04.5

Steps to Reproduce:
1. Create an extension with a webview
2. Submitting an html form in the webview. Sample webview code reproducing the error:
```
export default class SignIn {
  public start(context: vscode.ExtensionContext /*callback: () => any*/) {
    const panel = vscode.window.createWebviewPanel (
      "signIn",
      "Sign In",
      vscode.ViewColumn.Two,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
      },
    )

    // And set its HTML content
    panel.webview.html = this.getWebviewContent()
  }

  private getWebviewContent() {
    return `<!doctype html>
            <html lang="en">
                <head>
                    <title>Example Portal</title>
                </head>
                <body>
                    <form class="form-signin">
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </form>
                </body>
            </html>`
  }
}
```
3. Click the submit button and the whole webview becomes all black and the Developer Tools web console show the JS error.
The new 1.56 version crashes with:
```
Uncaught TypeError: Cannot read property '1' of null
    at host.js:9
```
Line 9 in host.js being:
```
const id = document.location.search.match(/\bid=([\w-]+)/)[1];
```

I assume that submitting the form updates the window location which breaks the regex matching.
I think that version 1.56 must have silently broken a lot of webviews as updating the window location becomes virtually prohibited while allowing html code to mess with it.

**Comment by mjbvz** [comment]
I'm actually surprised this ever worked. We do not officially support changing the `location` of a webview (and even [try to block this](https://github.com/microsoft/vscode/blob/069f8f39591e856872a55af9691da19ed51e847a/src/vs/workbench/contrib/webview/electron-browser/pre/index.html#L15) in some cases)

**Comment by PhilippeFerreiraDeSousa** [comment]
Before we were posting the sign-in form which sends the data to our online server. It was working fine. Then we changed that to a JS listener on the submit button that gets the data to a binary on disk that signs in to the server. So the behavior from the html forms we were still using was that when you submit it clears all input fields.

So I can mimic form behaviors and go clear input fields myself in JS but I am probably no the only person that put an html form on a webview as data input

**Comment by mjbvz** [comment]
c13c6d8e468dfda249f1f1a1f755f23ed9b46993 added a more clear error message about this scenario not being supported. While this scenario may have sort of appeared to have worked before this update, after the submit I believe it would leave the webview in a weird state were features such as loading local resources would not work

Given that I haven't seen other reports of this issue and that there is not a simply workaround for the issue, I'm going to close this as unsupported
