### ISSUE TITLE
Double click and drag in terminal doesn't work as expected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123000]
https://github.com/xtermjs/xterm.js/issues/3310

`bel` below should remain selected when dragging _up_:

![115721072-86314400-a332-11eb-9a03-bcc2590c9e51](https://user-images.githubusercontent.com/2193314/117138936-83861400-ad60-11eb-92dc-d870f7095005.gif)

**Comment by lramos15** [comment]
Might not be doing it right, but mine looks exactly like your gif so reopening

**Comment by Tyriar** [comment]
It's working for me?

![recording (5)](https://user-images.githubusercontent.com/2193314/120696985-0682b300-c462-11eb-86b6-89720524994d.gif)

See the double clicked work remains selected regardless of whether the mouse is above or below.
