### ISSUE TITLE
VSCode does not recognize a folder named CVS

### ISSUE THREAD

**Issue by AlGantori** [microsoft/vscode#123034]
- VS Code Version: latest
- OS Version: Windows 7

Steps to Reproduce:

1. Try to create a folder named CVS, I use a handful of 3 letter folder names for my components.
2. VSCode will not display it or acknowledge its existence.

I don't care if CVS is another version control system out there, let me name my folder CVS

Does this issue occur when all extensions are disabled?: Yes/No
YES

CVS folder does NOT show up in VSCode
![image](https://user-images.githubusercontent.com/11699920/117224912-f07fc500-adc5-11eb-9de4-e478661a14f8.png)

CVS Folder exists
![image](https://user-images.githubusercontent.com/11699920/117224957-0b523980-adc6-11eb-9347-65c755d65a97.png)

**Comment by gjsjohnmurray** [comment]
Go to Settings and edit the `files.exclude` entries

**Comment by AlGantori** [comment]
Thank you, removing that pattern worked.

![image](https://user-images.githubusercontent.com/11699920/117241224-8841db00-ade7-11eb-9df3-9cffa66a993b.png)
