### ISSUE TITLE
Trying to get the search results from findInFiles API 

### ISSUE THREAD

**Issue by silasechegini** [microsoft/vscode#123042]
Hello,
I am currently working on an extension using the Find in Files API, and I'd like to retrieve the results from the API for different use.
Is there a way to do this? Is there an API that has been exposed for this?
Thanks in advance.

**Comment by roblourens** [comment]
> and I'd like to retrieve the results from the API for different use.

Sorry, I don't understand what you're asking for, please explain some more

**Comment by silasechegini** [comment]
I am working on a VSCODE extension and the aim is to display search result using the registerHoverProvider. Search results similar to what the command : "workbench.action.findInFiles" achieves. Right now, my extension works such that when I hover over a thing, I am able to display single strings in an array. In addition to this, I want to be able to see more information about the data that appears in the hover pop up. more information like a link to the folder where I found the data, etc.  
I will appreciate any lead on how I could achieve this in my VSCode extension. Thanks.

**Comment by roblourens** [comment]
> I want to be able to see more information about the data that appears in the hover pop up. more information like a link to the folder where I found the data, etc.

Sorry, I still don't know exactly what you are asking for. You need to tell me exactly what you want, with a specific example. You want to put a link in a hover?
