### ISSUE TITLE
Change in the optional Custom Editor makes the raw file open

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode#123057]
- VS Code Version: 1.56.0
- OS Version: win10 19042.928

Steps to Reproduce:

1. Open [Cutom Editor Sample](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample) in VSCode, and add the `"priority": "option"` of `catCustoms.catScratch` in `package.json`
2. F5 to debug, open the example file `exampleFiles/example.cscratch`
3. Press `Scratch!`, and you'll see another tab appear. That's the raw editor.

I'd like to know is that by design? This issue appears after updating to 1.56, and 1.55 works.

Does this issue occur when all extensions are disabled?: No

**Comment by lramos15** [comment]
Do you mind posting a gif or similar recording as I do not see this. You can record a gif here https://gifcap.dev/

**Comment by CsCherrYY** [comment]
![bug](https://user-images.githubusercontent.com/45906942/117385184-27192500-af17-11eb-997c-868c7321cbae.gif)

You can see after I click the `Scratch!`, a new raw editor tab appears.

**Comment by CsCherrYY** [comment]
@lramos15 Could you reproduce this issue?

**Comment by artch** [comment]
I can confirm that this is indeed an issue in 1.56.0 which also affected my custom editor extension and forced users to downgrade to 1.55 until this is fixed.

**Comment by lramos15** [comment]
@CsCherrYY I have now been able to reproduce this issue and am investigating the regression

**Comment by lramos15** [comment]
@bpasero It seems what happens here is that because it is a custom text editor it makes changes to a text document which then fires the `doEnsureDirtyTextFilesAreOpened` resulting in an open editor call when edited. Should I add logic there to check if the resource is already open then don't fire the ensureDirtyTextFilesAreOpened?

**Comment by bpasero** [comment]
@lramos15 I thought I had tested this scenario. Here is what happens: When text file models get dirty (which can happen for text based custom editors) we see if an associated editor is opened:

https://github.com/microsoft/vscode/blob/abc6cf94729d0097c0eb27373f7fe128ee033dd1/src/vs/workbench/contrib/files/browser/editors/textFileEditorTracker.ts#L71-L71

And if that fails, we open the editor:

https://github.com/microsoft/vscode/blob/abc6cf94729d0097c0eb27373f7fe128ee033dd1/src/vs/workbench/contrib/files/browser/editors/textFileEditorTracker.ts#L84-L87

Given the editor override should kick in here, wouldn't that result in the custom editor being opened which is just a no-op?

**Comment by lramos15** [comment]
> Given the editor override should kick in here, wouldn't that result in the custom editor being opened which is just a no-op?
No, because if you have an optional text based custom editor then the resource doesn't resolve to the same editor. I could have reopened a text editor as something (in this example the cat scratch sample) so you would expect the same resource being opened again is meant to be the text editor.

**Comment by bpasero** [comment]
@lramos15 my problem is that text file editor models are being used inside custom text editors and there is no easy way from the editor service to find out if an editor can deal with the text file model or not.

I have an idea for a fix maybe through the new `IWorkingCopyEditorService` I added in May, but it would not be something for recovery.

**Comment by bpasero** [comment]
Bandaid recovery fix would be to restore the code we used to have where we simply checked if an editor with the provided resource is opened:

https://github.com/microsoft/vscode/issues/123057

**Comment by lramos15** [comment]
@bpasero Do you think we should push this for recovery? The affected parties are optional custom text editors

**Comment by bpasero** [comment]
I honestly don't know how many are impacted?

**Comment by bpasero** [comment]
I think https://github.com/microsoft/vscode/tree/ben/123057 would be a fix for recovery if you want to push it through. It basically restores how the tracker used to be.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/c4f3f8f9bea635a0bd7d1aff29c55382597922fa should address this for insiders.

**Comment by lramos15** [comment]
This won't make it out into the recovery build since I don't believe it affects many users. Will just keep in insiders and release with 1.57

**Comment by lramos15** [comment]
\closedWith c4f3f8f9bea635a0bd7d1aff29c55382597922fa

**Comment by artch** [comment]
> This won't make it out into the recovery build since I don't believe it affects many users. Will just keep in insiders and release with 1.57

@lramos15 Actually, our entire team work flow is corrupted by this issue. We use custom editors extensively in editing our Markdown site contents by non-technical personnel, and the editors are barely usable since every custom editor tab opens another text tab, confusing users. In my mind, it just does not work as intended, despite how many users are affected.

We would love to get a recovery build with this fix, and until then our team will stick to 1.55 because of this issue.

**Comment by lramos15** [comment]
@artch I'm sorry that this bug is causing you so many issues. We are past the point of making it into a recovery build as it has already gone out. The next release is 1.57 at the beginning of June.
