### ISSUE TITLE
Mac OS: Return Key Not Working After Renaming Terminal

### ISSUE THREAD

**Issue by mahdi-farnia** [microsoft/vscode#123086]
- Vs Code Version: 1.56.0
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Renaming Terminal

**This issue solves after relaunching window**

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
fixed by 769afaf981c7fcc5c67f7f78caecfe6aadeebaaf
