### ISSUE TITLE
Terminal Profiles defined in a workspace file cannot be selected

### ISSUE THREAD

**Issue by WyattGosling** [microsoft/vscode#123031]
- VS Code Version: 1.56
- OS Version: Red Hat Enterprise Linux Server release 7.7 (Maipo)
- OS Version: macOS 11.2.3

Note: I'm usually use the Remote - SSH plugin to work with VS Code running on a RHEL server. But I also verified this locally on the macOS system.

Steps to Reproduce:

1. Open a multi-root workspace.
2. Configure the Workspace settings to have the following setting set
```json
"terminal.integrated.profiles.linux": {
    "aUniqueName": {
        "path": "fish"
    }
}
```
3. Try various ways of using the profile that you defined:
    1. Run "Terminal: Create New Integrated Terminal (With Profile)"
    2. Press the down arrow next + button in the integrated terminal UI which shows profiles.
    3. Run "Terminal: Select Default Profile"
4. Reload the window and try step 3 again.

Does this issue occur when all extensions are disabled?: Yes

In Step 3, I expect to find "aUniqueName" in the list of Profiles to choose from. Instead the options are the list of generically provided Profiles: bash, fish, tmux, JavaScript Debug Terminal.

Prior to 1.56, I have been setting environment variables in my `.code-workspace` files via "terminal.integrated.env.linux". There is no yellow squiggly to tell me this setting is deprecated, but after upgrading to 1.56 no longer has any effect. I saw in the release notes that the new way to do this is to define a profile and use the "env" field of the profile to configure environment variables. I cannot tell if this works or not, because I cannot find a way to use the profile I have defined in my `.code-workspace` file.

Context: We use VMs a fair bit at work. Our various commands for interacting with the VMs get the VM info from environment variables. I need these defined on a workspace-by-workspace basis, and using the "terminal.integrated.env.linux" setting in `.code-workspace` has been perfect for this.

**Comment by meganrogge** [comment]
Can you attach a screenshot of what you see when you run the `Select Default Profile` command?

**Comment by WyattGosling** [comment]
This is what I see.

<img width="604" alt="Screen Shot 2021-05-05 at 20 22 07" src="https://user-images.githubusercontent.com/381628/117237338-9b50ad00-addf-11eb-8db1-984a1c6dab67.png">

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/121470

Setting `"terminal.integrated.allowWorkspaceConfiguration": true` will let you do this, you should make sure you trust the origin of your folders though.
