### ISSUE TITLE
Cannot replace old content when pasting

### ISSUE THREAD

**Issue by KaoImin** [microsoft/vscode#123092]
Issue Type: <b>Bug</b>

Firstly, select a piece of code, and then paste some code by ctrl+v. Vscode will not replace old content when pasting, but the pasted content will be added after the selected content.

VS Code version: Code - Insiders 1.57.0-insider (fe23c2041f848d6c2f6bd27875112a37bcc82f84, 2021-05-06T05:16:25.564Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 4250)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor (16 x 4250)|
|Memory (System)|25.02GB (11.29GB free)|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
tf2snippets|cha|0.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-dash|dee|2.4.0
vscode-rust-syntax|dun|0.0.32
rust-syntax|dus|0.5.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
Lua|key|0.0.9
Lisp|mat|0.1.11
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.56.1
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.6.0
pytorch-snippets|SBS|1.0.2
vscode-autohotkey|sle|0.2.2
latex-support|tor|3.6.0
tensorflow-snippets|vah|0.3.3
vscode-icons|vsc|11.4.0
vim|vsc|1.20.2
lua-debug|act|1.37.1
markdown-toc|Ala|1.5.6
vscode-hie-server|ala|0.2.1
vscode-sqlite|ale|0.12.0
asciidoctor-vscode|asc|2.8.9
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
vscode-wasm|dts|1.3.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
code-runner|for|0.11.3
mdmath|goe|2.5.1
go|gol|0.24.2
latex-workshop|Jam|8.17.0
c-cpp-flylint|jbe|1.9.0
asciidoctor-vscode|joa|2.8.0
rust-doc-viewer|JSc|2.0.1
language-haskell|jus|3.4.0
Lua|key|0.0.9
rust-analyzer|mat|0.2.583
Lisp|mat|0.1.11
dotenv|mik|1.0.1
vscode-docker|ms-|1.12.1
vscode-language-pack-zh-hans|MS-|1.56.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.812916528
cpptools|ms-|1.3.1
vscode-typescript-tslint-plugin|ms-|1.3.3
ide-purescript|nwo|0.24.0
language-purescript|nwo|0.2.4
erlang|pgo|0.7.6
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.18.0
pytorch-snippets|SBS|1.0.2
crates|ser|0.5.9
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.8.1
tabnine-vscode|Tab|3.4.4
latex-support|tor|3.6.0
codelf|unb|11.7.0
vscode-lldb|vad|1.6.3
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.12
docker|vsc|1.0.0
yaml|vsc|1.0.0
vim|vsc|1.20.2
autocomplete-english-word|wus|0.1.7
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

(5 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@KaoImin can you please provide screen recording of the behavior you are seeing?

**Comment by KaoImin** [comment]
> @KaoImin can you please provide screen recording of the behavior you are seeing?

![code](https://user-images.githubusercontent.com/24822778/117386154-f76b1c80-af18-11eb-9b3b-679d3390720d.gif)

**Comment by rebornix** [comment]
it's caused by the Vim extension.
