### ISSUE TITLE
"terminal.integrated.shell.windows" in last update

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode#123069]
Hi, I wake up this morning and I can't work any more. I Spent 2 hours trying to find out what happened. It turns out there was a visual studio code auto update and the setting "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe" was deprecated. Instead there is some sort of powershell, i am not sure.
Anyway it doesn't behave the same way and all my compile scripts don't work any more. I had to uninstall vscode and install the march version, while disabling updates for good.
I am not sure what this is about. Do you know what you did to the shell that caused so much regression on my configuration?

**Comment by elazarcoh** [comment]
Same for me. (well, in a sense)
I migrated to use the new **"terminal.integrated.profiles.windows"** setting, but I can't configure default shell per worksapce.
previously, I could set the shellArgs per workspace, and it was good enough.

preferably, at least for me, is the option to set the new **"terminal.integrated.defaultProfile.windows"** configuration per workspace, e.g.:
have the profiles configuration either at the user-level or the workspace-level (possibly overriding by name), and let me select the default profile at the workspace-level as well.

**Comment by StasPotapenko** [comment]
I've got the same issue here as well. Default terminal per workspace no longer available. All the tasks which depend on custom(default) shell, stopped working. New terminal "features" don't help.

**Comment by AlencarGabriel** [comment]
After the april update all my profiles defined at `terminal.integrated.profiles.windows` stopped work. 
It's as if VsCode is ignoring this configuration.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by bonjourjoel** [comment]
I've tried and it doesn't work for my configuration. When you say "it's fixed", what do you mean? It behaves like before by default or i have to do something in the settings?

This is an exemple of what doesn't work:
`        {
            "label": "compile ts app ; ~ compile ts WATCH @client",
            "type": "shell",
            "command": "node",
            "args": [
                "app-dev-utils/bin/app-dev-utils/src/vsc-task-run/VscTaskRun.js",
                "~ compile ts WATCH @client",
                "tsc-watch --noClear -p app-src/$ver/.compilets/tsconfig-client-app.json --onCompilationComplete \\\"node app-dev-utils/bin/app-dev-utils/src/fix-imports-js/FixImportsJs.js -watch app-bin/app-bin-client app-src/$ver/.compilets\\\"",
            ],
            "problemMatcher": ["$tsc-watch"],
            "isBackground": true,
            "auto": true,
        },
`

This works with march version and doesn't with this version. It sends wrong command line arguments to my script, they are split into chunks because the shell is different. I have 30 scripts like this one, and each has a different bug with this new shell options. I spent 2 months writing 30.000 lines of scripting code to handle a cross platform configuration for android/ios/windows/firefox/safari and I don't really want to change it now because vscode has deprecated something (that i don't understand, i admit).

Regards

**Comment by bonjourjoel** [comment]
Let me just say (with respect) that the solution is to not deprecate something that so many people use, or to make an automatic migration to something behaving the same way. Or at least to provide a manual procedure to make our programs work like they did yesterday. This is a google practice to break developper's code, it's not Microsoft's way.

**Comment by Tyriar** [comment]
> but I can't configure default shell per worksapce. previously, I could set the shellArgs per workspace, and it was good enough

@elazarcoh workspace terminal settings now require `"terminal.integrated.allowWorkspaceConfiguration": true` to be set as a stop gap solution until we get workspace trust enabled. See https://github.com/microsoft/vscode/issues/121470

**Comment by Tyriar** [comment]
I'm guessing everyone is having problems with specifically _workspace_ profiles? The new system should be much better at handling this, but there are some caveats:

- Workspace settings don't work by default unless `"terminal.integrated.allowWorkspaceConfiguration": true` is set for hopefully just this version. After that they won't work in _restricted workspaces_ which is a new security concept coming soon.
- A workspace can no longer set the _default profile_, I could be convinced to allow this you really rely on the default terminal here and getting to it from here is too much hassle:
  <img width="255" alt="Screen Shot 2021-05-06 at 8 22 39 AM" src="https://user-images.githubusercontent.com/2193314/117324077-501cb580-ae44-11eb-9a15-8aa70d9bb463.png">
  Please let me know

---

To get the screenshot above I used:

User settings.json:

```
"terminal.integrated.allowWorkspaceConfiguration": true
```

Workspace settings.json

```
    "terminal.integrated.profiles.osx": {
      "My workspace shell": {
        "path": "bash",
        "icon": "terminal-bash"
      }
    }
```

**Comment by AlencarGabriel** [comment]
> After the april update all my profiles defined at `terminal.integrated.profiles.windows` stopped work.
> It's as if VsCode is ignoring this configuration.

I added the configuration `"terminal.integrated.allowWorkspaceConfiguration": true` and now my profiles have reappeared. My configurations was in the workspace too.

**Comment by bonjourjoel** [comment]
I don't know what is a "workspace profile". I had a normal configuration with cmd.exe shell and no settings or "profiles". The commands which are valid ms dos commands don't work anymore. The command line arguments which are a feature of `"type": "shell", "command": "node", "args"`, they don't work. Do you know why?

**Comment by Tyriar** [comment]
@bonjourjoel can you share your settings.json file? Specifically any setting with "terminal" in the key

**Comment by bonjourjoel** [comment]
I have my settings in the workspace, not in settings.json. Here they are
[keyja2.zip](https://github.com/microsoft/vscode/files/6435844/keyja2.zip)

**Comment by Tyriar** [comment]
@bonjourjoel I expect setting `terminal.integrated.allowWorkspaceConfiguration": true` in your user settings should fix your problem too (unless you have a `defaultProfile` set in your user settings)

**Comment by bonjourjoel** [comment]
Yes thanks, it seems to work. I ran a few tests and if I understand correctly, this `allowWorkspaceConfiguration` makes the deprecated value of `terminal.integrated.profiles.windows` used like before?
It says that I should use `#terminal.integrated.defaultProfile.windows#` instead. But how? There is no documentation that I can see about the possible values. And can it do the same thing ? To use cmd.exe instead of powershell for the terminal? If so how?

**Comment by Tyriar** [comment]
@bonjourjoel sorry, docs coming soon https://github.com/microsoft/vscode-docs/issues/4526.

Because of these reports, I'm going to swap the priority of `defaultProfile` and `shell`/`shellArgs` such that if `shell` or `shellArgs` is specified, that will take precedence over the profile system. Then switch it several months later: https://github.com/microsoft/vscode/issues/123159. Note that this will not change the need for `terminal.integrated.allowWorkspaceConfiguration` which will is still expected to be going away in the following stable release.

**Comment by bonjourjoel** [comment]
Please put in the doc how to use cmd.exe as vsc's shell. Thanks.
