### ISSUE TITLE
The default Monokai highlight color is displayed incorrectly

### ISSUE THREAD

**Issue by ouweiya** [microsoft/vscode#123044]
Issue Type: <b>Bug</b>

The default Monokai theme of VSCode 1.56.0 is renamed and the highlight color is displayed incorrectly.

Disable all extensions, using the stable version and insider have the same problem.

![image](https://user-images.githubusercontent.com/28357731/117231290-89a7ed80-ae51-11eb-9676-4683190e3369.png)

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.58GB free)|
|Process Argv|--crash-reporter-id d1999580-d195-48b5-9b2c-d7af31560c8b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
vscode-eslint|dba|2.1.20
prettier-vscode|esb|6.3.2
comment-translate|int|1.4.2
svg|joc|1.4.6
vscode-language-pack-zh-hans|MS-|1.56.1
copy-file-name|ouw|2.1.2
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.0
vscode-js-console-utils|wht|0.7.0
change-case|wma|1.0.0
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by pqvst** [comment]
I just noticed the same thing. Very annoying
![image](https://user-images.githubusercontent.com/4990657/117239662-c8de3a80-ae61-11eb-866e-cd28c9a165ed.png)

**Comment by nrayburn-tech** [comment]
Looks to have been broken during an electron upgrade, https://github.com/microsoft/vscode/commit/3fb483e7fff42559b5f93e8aa92d0354021ee5ff.

**Comment by nrayburn-tech** [comment]
@deepak1556 or @misolori, maybe one of you can help me see what is happening here.
What it looks like to me, is the selection color is different between the two versions.  More specifically, the same hex color and a different visual appearance.


Default build.  After update on top, before on bottom.
<img width="775" alt="default" src="https://user-images.githubusercontent.com/52075362/117556415-64240b00-b02e-11eb-9c43-d37e85d21e29.png">


Modified the color to something else in dev tools.  After update on top, before on bottom.
<img width="803" alt="modified" src="https://user-images.githubusercontent.com/52075362/117556420-6dad7300-b02e-11eb-97c6-8c4d1b8cd1df.png">

**Comment by nrayburn-tech** [comment]
The solarized light and high contrast themes have a similar issue, but not near as noticeable.  The color has shifted between the two versions.
The other versions that use the `::selection` selector may also have changed some, but I didn't visually see a difference.  I am not sure of a way to measure the color accurately for a before/after.

**Comment by aeschli** [comment]
I updated the issue title and removed the ` The default Monokai theme of VSCode 1.56.0 is renamed ` part as this seems to be a separate issue for which I need more information. @ouweiya If you could file an issue just for that. Maybe it's a translation issue.
