### ISSUE TITLE
Could you please respect my decision about telemetry?

### ISSUE THREAD

**Issue by Karmavil** [microsoft/vscode#123037]
I am tired of this behavior. VScode always finds an excuse to activate telemetry without my consent.

- Every time I open a folder I have to explicitly deactivate telemetry.
- Every time I start a workspace I have to explicitly deactivate telemetry
- **Every time I build a container in remote explorer**! I have to deactivate telemetry.

I have started to persist the .vscode folder because this is unacceptable and yet, I am not save of this inappropriate behavior.
And it is not just about privacy, I am running containers, database, applications, cache, debugging, browsers, I have no room to this expensive processes.

**Comment by JacksonKearl** [comment]
It sounds like you may be modifying your workspace/folder/remote-specific settings rather than your global ones. Can you please ensure in the Settings UI, the "User" tab is selected when you change the setting value? 
![image](https://user-images.githubusercontent.com/8586769/117247063-7b76b480-adf2-11eb-928d-8bf6a8da66ba.png)

**Comment by Karmavil** [comment]
@JacksonKearl thank you for your interest.
I am afraid there is no _rather than_ scenario here.
Just try it by yourself.. the settings apply to a workspace right? That means whenever you open a new workspace that does not have any setting set VScode will automatically enable Telemetry; crash reporter.

There are two settings for Telemetry: one that is common for User, Remote [dev container..] and Workspace.
The other is specific for the User only, that is **usage data and errors**

The problem here is with the first one (Crash Reporter) because it is not tied just to the user but also to the workspace, and to the Remote [dev container], so every time you start a new workspace, you need to set the your preferences and save it to .vscode.
The real problem starts when you are working from a container VScode will ignore you .vscode settings every time you rebuild the container.

I do not pretend to be disrespectful but I insist there is not such a thing as "**global**" settings for this thing.
Even if you save your User setting for Telemetry (usage data) in your .vscode folder in your project you get a tooltip with this message:

> This setting can be applied only in application user settings

I make this comment just to make the misconception clear: what is exactly application? VScode.. well then application will be the same as global, so _Telemetry usage data_ is the only telemetry that is possible to configure that way, but not _Telemetry crash report_

I don't want to send any crash report because that implies VScode will send 400mb, 600mb 900mb for what? Who is going to read that data? I don't care I just don't want to let VScode send any crash report

**Comment by JacksonKearl** [comment]
I think I see the confusion here... to disable telemetry, all you need to do is ensure these boxes are unchecked in the "User" tab:
![image](https://user-images.githubusercontent.com/8586769/117329983-1058cc80-ae4a-11eb-8c26-1d3d4e30194f.png)

However, even with these boxes unchecked, the remote and workspace boxes will be checked:
![image](https://user-images.githubusercontent.com/8586769/117330062-2a92aa80-ae4a-11eb-94ae-1e66866651b3.png)
![image](https://user-images.githubusercontent.com/8586769/117330083-2e263180-ae4a-11eb-96cd-feef8ff33690.png)

To the best of my knowledge (cc @sandy081 , @roblourens ), this is OK, and telemetry will still be disabled on the remote.

What's happening here, as far as I'm aware, is that while the User settings will apply to all scopes (remote, workspace), if they do not explicitly override it, the Settings Editor renders the default value for settings, rather than the value that applies at time of setting resolution. 

cc @roblourens for possibly changing the renderer to show the value that will apply rather than whatever the default it, as I agree it's a bit confusing here.

**Comment by roblourens** [comment]
Yeah, this is what the "modified in scope" hint is for. But you have to know how settings are resolved to interpret this, which I agree is not great. Tracking this in https://github.com/microsoft/vscode/issues/58038

**Comment by Karmavil** [comment]
Really? duplicate? That is so sad..
The workaround I take for this is just add the settings to .devcontainer.json :
```json
// Set *default* container specific settings.json values on container create.
"settings": {
	"terminal.integrated.shell.linux": "/bin/bash",
	"telemetry.enableCrashReporter": false
},
```

But this has nothing to do with the FEATURE REQUEST.
The feature request is to take away the independece of **Telemetry: Enable Crash Reporter** because 
## It should be up to the user!

And it is, but it has a default value that is really annoying.
Please @roblourens  reopen this issue because it is a /feature-request (for a particular setting specifically)

**Comment by JacksonKearl** [comment]
@Karmavil you do not need to change anything in the container's `settings.json`, if you simply configure a value in your User settings, it will apply to all devcontainers, folders, workspaces, and remotes you open.

**Comment by Karmavil** [comment]
@JacksonKearl  my User settings for telemetry are just fine all right? As I said before try it by yourself.
I don't want to sound rude but it is like you are not listening .. (or maybe we are on different platforms)

Please I encourage you to try it by yourself before add a new comment:
* Open VScode (new window, no projects open)
* Go to settings and check for telemetry values (only User will be available there)
* Select  Open Folder from the Explorer of form (File > Open folder)
* Create a new folder and click OK
* Go to settings and check for telemetry values (now User and Workspace are available but workspace was overrite)

You can also try with remote explorer

> Let me make it more reproducible for you:
> 
>     * Open VScode
> 
>     * In Remote Container choose Open Folder in container, open workspace, clone repository whatever
> 
>     * Go to settings and disable telemetry crash reporter
> 
>     * In remote-containers options select rebuild container
> 
>     * Check the status of telemetry

**Comment by Karmavil** [comment]
And this not only applies to **Application** it also applies to **Extensions** 
Do I have to say more?
All right: **I'm loosing control of my code editor**!

**Comment by roblourens** [comment]
Jackson is right, telemetry is actually disabled even though you see a checkmark there. The checkbox is showing you the default value for that scope, not the value that is being applied at this moment.

**Comment by Karmavil** [comment]
Well look I'm sending like a gigabyte of traffic everyday I would think that I'm making use of some malicious package but it is not the case.. just disabling Telemetry solve the problem.
> Thas is my issue

Disabling Telemetry (Application or Extensions) is not something that I want to do every time I start a project (open a new folder).. I think Telemetry should not be related to a workspace, is this so hard to understand?
> That is my feature request

@roblourens How do I prove you that is Telemetry who is causing all this traffic? Any suggestion? I am open to suggestions..

**Comment by roblourens** [comment]
How are you detecting this traffic, can you tell me anything about it like what hostnames show up?

**Comment by Karmavil** [comment]
Sorry for tag your name there.
No actually I'm not tracking the traffic for packages I'm just seeing the network traffic and all this time I tough it was internal traffic you know like from one container to others or to the host.. but just disabling telemetry change that behavior.
I mean I am using the network traffic by default that why I'm open to suggestions (I don't pretend to be a network expert)

**Comment by Karmavil** [comment]
I am using debian (and the default network traffic and cpu usage interface)

**Comment by roblourens** [comment]
You could use a tool like wireshark or tcpdump to figure out what that traffic is. But telemetry will be disabled when you have it disabled in your user settings like that. And I'm sure we don't produce a GB of traffic in telemetry from the server every day, unless there is an extension doing something very strange.

**Comment by Karmavil** [comment]
All right then I will check that out. Thanks
I will let you know if I find something with inappropriate behavior

**Comment by Karmavil** [comment]
Well.. I can confirm that someone is messing in my backyard.
I am not sure if it is from my host or the container.
Luckily I was not returning json and DRF delivered all those statistics that helped me to see the call

![20210519_161006](https://user-images.githubusercontent.com/2354060/118870684-373ce700-b8bd-11eb-9a6a-78b2da0c966f.jpg)

**Comment by Karmavil** [comment]
All right I have more thoughts:
• 1 ) I forgot for a minute how VSCode works (too much time working on my own containers), by default it will expose your development environment not only to the host but to your network, I really don't understand why but that's why most of the time I run my own environment, not .devcontainer
• 2 ) If it was an external connection I would saw a host header warning in that log so I think whatever is happening is going on in the dev environment. 

Are you still with me? Because I don't mind to open a new ticket.. but to be honest I don't have enough information I was tracking the network traffic and it's hard to say whether the traffic is legit having a lot of ports mixing ipv4/6 and mac calling the ISP, a browser with a couple tabs opened, and probably the vsc plugins also need update schemas.. It's not easy but it is weird. 

I will stop using the devcontainer by vscode but that's not a workaround. We should know if it's not safe. If you know someone with the expertise I don't mind to provide more details.

**Comment by Karmavil** [comment]
Oh BTW, the huge network traffic disappeared magically a few days after this issue (before the update)
