### ISSUE TITLE
Custom dialogs don't listen to some key strokes

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#123023]
- VS Code Version: 1.56.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Enable the custom dialogs in the settings.
2. When having a custom dialog (like the warning on closing an unsaved file) the dialog won't listen to classic key strokes.

`Escape` and `space` are respected, but `n` should select "no", likewise `y` "yes".

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/71430
