### ISSUE TITLE
Terminal tabs `hide condition` with `never` value problem

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#123062]
- VS Code Version: 1.56.0
- OS Version: Windows 10 20h2

Steps to Reproduce:

![Animation1](https://user-images.githubusercontent.com/17777237/117239176-90713900-ae2e-11eb-8f4c-c50f81c8f3ec.gif)

And when closing

![Animation](https://user-images.githubusercontent.com/17777237/117239458-15f4e900-ae2f-11eb-8c24-ca4819e78c40.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The first gif is by design, `terminal.integrated.tabs.showActiveTerminal` defines how the panel's "inline tab" displays
