### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by MarioG8** [microsoft/vscode#123011]
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
Extensions installed - 81

Restart extension host does not work for me. 
There is no issue when I remove (uninstall) live server and live sass compiler but  I need those both extension :) 
Anybody had this issue ? Could anybody You help me ?
![Screenshot (23)](https://user-images.githubusercontent.com/66386548/117185686-63933680-adda-11eb-83ad-b757cb45c228.png)

**Comment by JacksonKearl** [comment]
Could you please try filing these issues on the extension repositories? Alternatively if you provide the logs from the developer tools we may be able to provide more help here.

**Comment by MarioG8** [comment]
Thank You Very Much 😉👌 Have nice day .

**Comment by MarioG8** [comment]
Even after a complete reinstallation of VSCode and extensions, the problem appears again,;/

**Comment by JacksonKearl** [comment]
Can you include the logs from the developer tools? (In the screenshot you provided, there's a button "Open Developer Tools" on the notification))

**Comment by MarioG8** [comment]
[-1620327433634.log](https://github.com/microsoft/vscode/files/6437012/-1620327433634.log)

**Comment by JacksonKearl** [comment]
Based on the lines here:
```
localProcessExtensionHost.ts:272 Extension Host
localProcessExtensionHost.ts:273 'wc' is not recognized as an internal or external command,operable program or batch file.c:\Users\Mariusz Golik\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61v
```
and here:
```
Error: Command failed: git -C c:\Users\Mariusz Golik\Desktop\Git_Projects\Surfing_school_Responsive_Website status -s | wc -l'wc' is not recognized as an internal or external command
```

It seems  maybe`ritwickdey.live-sass-3.0.0` is expecting `wc` to exist as a CLI utility on the platform, but this does not exist on your system (it may be POSIX-only?), and this is causing the extension host to crash. 

I suggest following up with the extension repository at: https://github.com/ritwickdey/vscode-live-sass-compiler

**Comment by MarioG8** [comment]
Thank you for Help :) See you next time :)
