### ISSUE TITLE
Upgraded to version 1.56.0... Issues with terminal/Powershell

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#123066]
- VS Code Version: 1.56.0
- OS Version: Windows 10 Version 20H2 Build 19042.928

Steps to Reproduce:

1.  Start VSCode

Does this issue occur when all extensions are disabled?: Yes

**ISSUE:**

I used to depend on the below settings.json settings:
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
"terminal.integrated.shellArgs.windows": [
    "-NoLogo",
    "-ExecutionPolicy",
    "Bypass"
],
"powershell.integratedConsole.suppressStartupBanner": true
```
Now, I get 3 warning messages for the above settings:
```
This is deprecated, use `#terminal.integrated.defaultProfile.windows#` instead
This is deprecated, use `#terminal.integrated.defaultProfile.windows#` instead
This is deprecated, use `#terminal.integrated.defaultProfile.windows#` instead
```
When I go to use `terminal.integrated.defaultProfile.windows` in my settings, VScode doesn't seem to recognize that setting. It looks like it hasn't been implemented yet.

With some trial and error, the settings below seem to be valid. However, I'm not even sure they're an equivalent replacement for the depreciated settings above.  I was completely guessing; and, probably have several mistakes.  _I also added cmd.exe_:

```
"terminal.integrated.profiles.windows": {
    "PowerShell": {
        "path": [
            "${env:windir}\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
            "${env:windir}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        ],
        "source": "PowerShell",
        "icon": "terminal-powershell",
        "args": [
            "-NoLogo",
            "-ExecutionPolicy",
            "Bypass"
        ]
    },
    "Command Prompt": {
        "path": [
            "${env:windir}\\Sysnative\\cmd.exe",
            "${env:windir}\\System32\\cmd.exe"
        ],
        "icon": "terminal-cmd"
    },
    "Git Bash": {
        "path": [
            "C:\\Program Files\\Git\\bin\\bash.exe",
        ],
        "source": "Git Bash",
        "icon": "terminal-bash"
    },
    "WSL": {
        "path": [
            "C:\\WINDOWS\\System32\\wsl.exe",
        ],
        "source": "wsl",
        "icon": "terminal-wsl"
    }
},
"powershell.integratedConsole.suppressStartupBanner": true,
```
Unfortunately, the `-NoLogo` argument above is completely ignored.  Also, `"powershell.integratedConsole.suppressStartupBanner": true` is ignored as well.  So, when PowerShell starts up in the terminal, I get:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 681ms.
```
Adding "CLS" to my $profile is a pretty lame solution. I'm looking for the right way to suppress the banner/logo above same as before.

Could someone please tell me how to configure VSCode 1.56.0 to behave just like before?  Please correct any mistakes I may have in my proposed new settings.  Also, I wasn't sure what to put for the wsl icon.  I used, `"icon": "terminal-wsl"`.  However, I was completely guessing.

**Lastly, how to I force VSCode to only use `PowerShell Integrated Console` **_or_** `powershell`?**  (see below screenshot).  It seems like the terminal randomly opens one or the other or both.   I used to never have this issue in previous versions of VScode.  I just want the same powershell to open up consistently each time I start a new terminal session. 
![Screenshot 05-05-2021 at 10 25 26 PM](https://user-images.githubusercontent.com/811008/117246090-d27b8a00-adf0-11eb-9081-14ee4d206965.png)

Thank you guys for all your hard work!

**Comment by krisavi** [comment]
"terminal.integrated.shellArgs.windows" seems to be deprecated and is suggesting to use `#terminal.integrated.defaultProfile.windows#` instead, however if I set the execution policy there, then it gives me "Incorrect type. Expected one of string, null."
Also it seems to ignore terminal.integrated.profiles.windows.Powershell.args. The whole deprecation message leaves it unclear how to get to the same result as it was in previous versions.

**Comment by mkanet** [comment]
@krisavi Thank you for confirming.  I'm guessing the only way to suppress the PowerShell logo/banner is to use previous versions of VSCode.

I also noticed that this new version of VSCode loads a `powershell` tab in addition to the `PowerShell Integrated Console` tab (see below screenshot).  I only want the `PowerShell Integrated Console` to load on startup:
![pvqhz19ymjx61](https://user-images.githubusercontent.com/811008/117360261-6ab75480-ae6d-11eb-89f5-ba4431b03291.png)

I'm running VSCode on Windows 10.  I'm guessing that VSCode is also loading the PowerShell that came builtin with Windows 10 in addition to the Integrated PowerShell Console.  I'm just not sure how to prevent that from happening.  Is there a setting that prevents the second PowerShell tab from opening?

Thank you for your time.

**Comment by Tyriar** [comment]
> However, There is a separate powershell tab that also gets loaded on VSCode startup which DOES show the logo/banner (see below screenshot).

This works for me:

```
"terminal.integrated.profiles.windows": {
  "PowerShell": {
    "source": "PowerShell",
    "icon": "terminal-powershell",
    "args": ["-NoLogo"]
  }
}
```

What I think you're seeing is https://github.com/microsoft/vscode/issues/123188

> With some trial and error, the settings below seem to be valid. However, I'm not even sure they're an equivalent replacement for the depreciated settings above. I was completely guessing; and, probably have several mistakes. I also added cmd.exe:

The settings.json editor won't get that much better than it is, but we want to add an actual settings UI editor for these settings: https://github.com/microsoft/vscode/issues/123169

Here are some comments on your settings:

- You don't need `path` when you have a `source`, the purpose of `source` is to let VS Code handle fetching the path when resolving defaults is complicated.
  <img width="850" alt="Screen Shot 2021-05-06 at 2 24 42 PM" src="https://user-images.githubusercontent.com/2193314/117367258-cdf9b480-ae76-11eb-8aae-4c394276d645.png">
- There is no WSL `source`, WSL profiles are dynamic and automatically get added when you have `"terminal.integrated.useWslProfiles": true` set. This is because we want to automatically pick up newly installed distros and automatically remove uninstalled ones
- `path` can be a string if you want: `"path": "${env:windir}\\System32\\cmd.exe"`

> The whole deprecation message leaves it unclear how to get to the same result as it was in previous versions.

Good point, this is being improved in https://github.com/microsoft/vscode/pull/123174

> Lastly, how to I force VSCode to only use PowerShell Integrated Console or powershell? (see below screenshot). It seems like the terminal randomly opens one or the other or both. I used to never have this issue in previous versions of VScode. I just want the same powershell to open up consistently each time I start a new terminal session.

VS Code will always restore the default shell if the terminal is opened on start up. The PS integrated console does something similar and it doesn't have the capability to prevent the start up, it could kill other terminals on startup though that would be a bit dangerous.

> Also, I wasn't sure what to put for the wsl icon. I used, "icon": "terminal-wsl". However, I was completely guessing.

`icon` is actually optional, it can be whatever you want. Intellisense for this was deferred to https://github.com/microsoft/vscode/issues/122473 but the easiest way to do this now is to run the change icon command and find the icon ID you like:

<img width="450" alt="Screen Shot 2021-05-06 at 2 21 31 PM" src="https://user-images.githubusercontent.com/2193314/117366964-5b88d480-ae76-11eb-9cad-84fc861edf77.png">

---

Hope that was helpful, I think everything here is covered in other issues.

**Comment by mkanet** [comment]
@Tyriar Wow.  Thank you so much for taking the time to answer all my questions!  I really appreciate it.

Below, are the settings I ended up with per your suggestions.  However, unfortunately, every time I start VSCode with the terminal open, the terminal will randomly display the PowerShell logo/banner.. and, other times it won't display it on startup.  It's hit or miss.  However, at least now only 1 PowerShell tab opens when VSCode starts up.  I'm guessing it's because the default shell getting loaded randomly.

I didn't have this behavior before in previous versions of VSCode on the same PC.  Is there any way to force the Terminal to **NOT** display the banner consistently?  It's quite annoying; especially, when it wasn't doing this in previous versions on the same PC.  I'm very motivated to prevent this from happening.  

```
    "powershell.integratedConsole.showOnStartup": true,
    "terminal.integrated.useWslProfiles": true,
    "terminal.integrated.tabs.enabled": true,
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "args": ["-NoLogo"]
        },
        "Command Prompt": {
            "path": "${env:windir}\\System32\\cmd.exe",
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash",
            "icon": "terminal-bash"
        },
        "WSL": {
            "path": "C:\\WINDOWS\\System32\\wsl.exe",
            "icon": "terminal-wsl"
        }
    },
    "powershell.integratedConsole.suppressStartupBanner": true,
    "files.defaultLanguage": "powershell",
```

**Comment by Tyriar** [comment]
@mkanet the startup thing is a bug, we should fix it soon in Insiders but I don't think it meets the bad to go into a recovery build for stable #123188

Another perk with the profiles is you can leave out the default ones all together if you don't change them, so I think you could just have this for the same effect:

```json
"PowerShell": {
	"source": "PowerShell",
	"icon": "terminal-powershell",
	"args": ["-NoLogo"]
},
"WSL": {
	"path": "C:\\WINDOWS\\System32\\wsl.exe",
	"icon": "terminal-wsl"
}
```

**Comment by mkanet** [comment]
Thank you for explaining.  I think I'll just revert to the previous version of VSCode until there's a non-Insiders build with the fix.

**Comment by Tyriar** [comment]
@mkanet I think removing `"terminal.integrated.defaultProfile.windows": "PowerShell"` and avoiding switch default profile will basically give you the previous version's behavior.

**Comment by mkanet** [comment]
@Tyriar unfortunately it didn't seem to make any difference.  Actually, now the terminal consistently shows the banner\logo on startup every time  `"args": ["-NoLogo"]`  and `"powershell.integratedConsole.suppressStartupBanner": true` are completely ignored.  It seems to consistently load the default shell.

If I get lucky enough where `PowerShell Integrated Console" starts up, there is no banner\logo.

**Comment by Tyriar** [comment]
@mkanet the terminal that gets restored will use your default shell, when you do not have `defaultProfile` set, it will use `shell` and `shellArgs`. So you're probably missing:

```
"terminal.integrated.shellArgs.windows": ["-NoLogo"]
```

**Comment by mkanet** [comment]
@Tyriar Yes, that's the setting I used to use before upgrading to version 1.56.0 (when the terminal worked correctly).  If I try to use that setting now, I get the message:

`This is deprecated, use `#terminal.integrated.defaultProfile.windows#` instead` *sigh*

I just want to make sure I understand what's causing the banner to always show.  Is it because of https://github.com/microsoft/vscode/issues/123188?  Or, is there something I can fix in my settings now?

**Comment by Tyriar** [comment]
The message is a warning to indicate to move towards defaultProfile, but it'll be several months at least before we remove it.

**Comment by mkanet** [comment]
I'm not sure what's wrong.  I'm still seeing the banner/logo every time I start VSCode.  Below, are all my current settings related to the terminal.  I'm not sure what else to try.  I've never had such bad luck with VSCode before.

```
    "terminal.integrated.useWslProfiles": true,
    "terminal.integrated.tabs.enabled": true,
    "terminal.integrated.shellArgs.windows": [
        "-NoLogo"
    ],
    // "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell",
            "args": ["-NoLogo"]
        },
        "WSL": {
            "path": "C:\\WINDOWS\\System32\\wsl.exe",
            "icon": "terminal-wsl"
        }
    },
    "powershell.integratedConsole.showOnStartup": true,
    "powershell.integratedConsole.suppressStartupBanner": true,
```

**Comment by rushfan0** [comment]
Yeah, this bug is awful. The only solution for me is to disable updates with `"update.mode": "none"`, and then revert to previous version by downloading and installing [from the website](https://code.visualstudio.com/updates/v1_56) , at least for the time being! Given how many issues there are, I don't even know where to complain about it, issue  #123188 seems to be less people there.

**Comment by Tyriar** [comment]
@rushfan0 if you have issues that are not already tracked you can create an issue for it. Not much point complaining when we already know about the problems, then I spent time reading complaints instead of fixing them 🤷‍♂️

**Comment by rushfan0** [comment]
@krisavi Downgrade and [be happy they have not altered it any further!](https://youtu.be/jsW9MlYu31g)
