### ISSUE TITLE
Provide VS Code support for SSLKEYLOGFILE

### ISSUE THREAD

**Issue by sjuratov** [microsoft/vscode#123009]
I would like to capture VS Code network traffic (e.g. using Wireshark) and then de-crypt SSL traffic using SSLKEYLOGFILE

Running VS Code like follow didn't work

`code --ssl-key-log-file=%USERPROFILE%\sslkeys.log`

Running Chrome works fine

`chrome --ssl-key-log-file=%USERPROFILE%\sslkeys.log`

I was hoping VS Code leveraging Chromium, this switch might just work.

**Comment by deepak1556** [comment]
Seems to work fine with latest stable `1.74`.
