### ISSUE TITLE
Issue report window lost after lost focus

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#123082]
Issue Type: <b>Bug</b>

1. open Help / Issue report window
2. press Alt-Tab
3. press Alt-Tab

Expected: Issue report window in focus
Actual: VSCode window in focus and lost Issue report window

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx   (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.91GB (1.77GB free)|
|Process Argv|--crash-reporter-id 6b76fe32-24c1-4e87-ab59-3f8a75158efc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
Bookmarks|ale|13.0.4
gitlens|eam|11.4.1
code-runner|for|0.11.3
beautify|Hoo|1.5.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-wsl|ms-|0.56.1
debugger-for-edge|msj|1.0.15
vscode-yaml|red|0.18.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by RMacfarlane** [comment]
@deepak1556 This seems to be a regression from 1.55, is there anything from the electron upgrade or sandboxing efforts that could have impacted this?

**Comment by deepak1556** [comment]
Can you try launching with `code --disable-features=CalculateNativeWinOcclusion` and check if the issue repros.

/duplicate https://github.com/microsoft/vscode/issues/123257
