### ISSUE TITLE
Support the foam extension in a deeper way

### ISSUE THREAD

**Issue by aneeshsathe** [microsoft/vscode#123063]
Issue Type: <b>Feature Request</b>

We like taking notes, we don't want to be locked in to closed tools where our notes can be lost. Markdown is nice, but markdown isn't enough. Foam is a step in the right direction, but they need a lot more help, some of which could mean changes in VSCode.

Please support the team. :) 

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by JacksonKearl** [comment]
Do you have a specific feature request or bug report in mind?

**Comment by aneeshsathe** [comment]
I saw this: https://twitter.com/VisualStudio/status/1390032516799729677

Therefore expressed my support. No specific feature request.

**Comment by JacksonKearl** [comment]
Thanks! If you have a specific feature request in mind, please file it over at the extension's repository page: https://github.com/foambubble/foam

Happy Coding!
