### ISSUE TITLE
Custom dialogs have no access keys

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#123097]
Issue Type: <b>Bug</b>

When switching to custom dialogs (`"window.dialogStyle": "custom"`), the buttons cannot be accessed directly via the keyboard. E.g. I am used to pick "Don't Save" when closing a modified file via `Alt` + `N`, but this no longer works.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/71430
