### ISSUE TITLE
Characters when typing in Terminal have boxes around them in 1.56

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/vscode#123022]
- VS Code Version: 1.56.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Update to 1.56.0
2. Open a terminal Window (<kbd>Ctrl</kbd> + <kbd>`</kbd>)
3. Type.
4. Resizing the window makes them go away.

![Peek 2021-05-05 22-31](https://user-images.githubusercontent.com/20837086/117212020-ab718800-adf1-11eb-890d-25c3cdd29a3c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by LarnuUK** [comment]
Downgrading back to 1.55.2 does not cause the problem, so this is specific to the latest version:
![Peek 2021-05-05 22-37](https://user-images.githubusercontent.com/20837086/117212609-774a9700-adf2-11eb-9ca8-f6b84f500a44.gif)

**Comment by LarnuUK** [comment]
Noting this is still in 1.56.2 on Ubuntu.

![Peek 2021-05-14 09-38](https://user-images.githubusercontent.com/20837086/118245097-41637d80-b498-11eb-9e3a-7a090ed8ba12.gif)

**Comment by LarnuUK** [comment]
Also still the case in 1.57 and 1.58 insiders.

**Comment by meganrogge** [comment]
Does changing the `terminal.integrated.gpuAcceleration` setting help?

**Comment by LarnuUK** [comment]
> Does changing the `terminal.integrated.gpuAcceleration` setting help?

It does, yes. Changing it of "off" stops the problem occuring.
