### ISSUE TITLE
VS code is taking so much time to create one app.js file

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#123090]
-Version: 1.55.2 (user setup)
-OS: Windows_NT x64 10.0.19042

Hi Vs code team,
VS code not takes so long to create just one app.js file. When I click create new file and type ```app.js``` it keeps on loading and well it takes 3,4 min to create a file and this has started happening just 2 days ago before that it never happened

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information

**Comment by iron-coder12** [comment]
ok I''ll check it out
