### ISSUE TITLE
Using the first non-printable ASCII character in the text in the file name

### ISSUE THREAD

**Issue by 83lilax** [microsoft/vscode#123070]
Issue Type: <b>Bug</b>

Using the first non-printable ASCII character in the text in the file name results in an error: _Invalid file name_.

For example: оne RS character is entered with copy / paste (^C + ^V).
Any valid filename on the "save as" action results in an error: _Invalid file name_.

The tab name "Untitled-1" also contains the RS character.

[ASCII Character Set](http://www.robelle.com/library/smugbook/ascii.html)

**Control Characters**
```
Char:	RS
Oct:	36
Dec:	30
Hex:	1e
Control-Key:	^^
Control Action:	Record separator, block-mode terminator
```

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.17134

**Comment by JacksonKearl** [comment]
It's not clear to me what the issue here is, it seems to me that it's expected that using a non-printable character in the file name would cause it to be invalid, do you have a reason this would not be the case?
