### ISSUE TITLE
Remote drive: Execute permission removed from file on save when saving

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#12309]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. have a file on a remote drive that has execute permission on underlying linux system

```
-rwxr-xr-x  1 frantisek frantisek  2131 Sep 20 09:26 wo
```
1. edit the file in vs code, save
2. file now lacks execute permission for user:

```
-rw-r-xr-x  1 frantisek frantisek  2131 Sep 20 09:26 wo
```

**Comment by chrmarti** [comment]
Reproduced with a Windows VM on OSX editing a file that is on the OSX filesystem. There the permissions go from -rwxr-xr-x to -rw-r--r-- after saving. The Finder shows a new creation date.

Saving the file with VSCode on OSX does not change the permissions and the Finder shows the old creation date.

**Comment by bpasero** [comment]
Upstream issue which very likely reproduces with bare node.js too.

**Comment by bpasero** [comment]
@PunchyRascal @chrmarti  if you can write a node.js script which runs `fs.writeFile` to the remote file to see if that changes the executable bits?

**Comment by PunchyRascal** [comment]
Nope, running the following code, where foo.txt is on the remote drive:
```
const fs = require('fs');
fs.appendFile('z:/foo.txt', 'data to append2', (err) => {
  if (err) throw err;
  console.log('The "data to append" was appended to file!');
});
```
does not remove the execute permission. The data is written to the file.

**Comment by PunchyRascal** [comment]
Sorry, I used append instead of write. Append works fine, as mentioned before, write indeed removes the executable permission.

**Comment by bpasero** [comment]
@PunchyRascal please report this to node.js then.

**Comment by bpasero** [comment]
@PunchyRascal maybe you first try our insider build which comes with a much newer node.js release (6.3.0): 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by PunchyRascal** [comment]
(just a technical note, the link seems to be http://code.visualstudio.com/insiders)

**Comment by PunchyRascal** [comment]
Nope, still there. Anyway I reproduced this even with a script running on node 6.6. 

However, there seem to be some shenanigans concerning the file permission, see https://github.com/nodejs/node-v0.x-archive/issues/25756

I can't really tell if what they say there solves this issue ATM.

**Comment by chrmarti** [comment]
Same here. I found the following preserves the permissions (and possibly other metadata):
```
const fs = require('fs');
const fd = fs.openSync('script.sh', 'r+');
fs.ftruncateSync(fd, 0);
fs.writeSync(fd, '#!/bin/bash\n\necho yay!\n');
fs.closeSync(fd);
```

**Comment by bpasero** [comment]
@chrmarti but did you try going through the remote drive to see if it preserves executable bit there too?

**Comment by chrmarti** [comment]
@bpasero I ran that code in my Windows VM with a workspace that is on the host OSX filesystem. On OSX ls -l would show the executable bits set before and after. writeFile() would loose them.

There are no attributes shown when looking at the file from the Windows VM's file explorer (if that's what you're referring to).

**Comment by bpasero** [comment]
Ok, going via fs.write might be an option to workaround this. I still think that writeFile could be better though so I encourage to file an issue against node.js itself 👍

**Comment by bpasero** [comment]
I filed https://github.com/nodejs/node/issues/9380

Actually it works also for `fs.writeFile` but you need to run with `r+` as mode. I am not sure why though...

**Comment by PunchyRascal** [comment]
I don't know what happened, but don't experience this issue anymore. Executable files seem to keep their x right.

**Comment by bpasero** [comment]
Weird, I do not recall any change in this area for a while.
