### ISSUE TITLE
Improve tree node styles in NPM Scripts pane

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#123091]
I'd like to suggest a simple improvement to the readability and accessibility of the NPM Scripts pane.

Today the script name and package name are concatenated, reducing readability and accessibility:

![image](https://user-images.githubusercontent.com/1505561/117269932-0094b480-ae59-11eb-9712-73379f7a673a.png)

At the very least, the package name should be a semantically separate description:

![image](https://user-images.githubusercontent.com/1505561/117272935-f1fbcc80-ae5b-11eb-9d77-44ac476b1200.png)

Personally, though, rather than repeat the package name over and over, I would really rather see the script contents here:

![image](https://user-images.githubusercontent.com/1505561/117272952-f45e2680-ae5b-11eb-8db4-355f37a4101d.png)

Thanks!

**Comment by alexr00** [comment]
New appearance:
![image](https://user-images.githubusercontent.com/38270282/141325032-17e00f28-2583-43ee-93c2-ceeb0a4007e2.png)

**Comment by aaronadamsCA** [comment]
That looks SO GOOD. Amazing. Thank you!

**Comment by avxkim** [comment]
@alexr00 is there a way to disable this?
