### ISSUE TITLE
UnicodeEncodeError after printing json data from API

### ISSUE THREAD

**Issue by smacmannis** [microsoft/vscode#123006]
Code below produces error in output window in Visual Studio Code, version 1.55.2. No error is produced if code is run in the terminal. This happens with numerous APIs I have tried.
```
import json
import requests

r = requests.get(
    "https://v6.exchangerate-api.com/v6/<need a key here>/codes")

json.dumps(r.text)
dataCodeName = json.loads(r.text)
rr = requests.get(
    "https://v6.exchangerate-api.com/v6/<need a key here>

/latest/USD")
json.dumps(rr.text)
dataCodeRate = json.loads(rr.text)

for key, value in dataCodeName['supported_codes']:
    print(value)
    print(dataCodeRate['conversion_rates'][key])
```

<Output>
```
...
Pakistani Rupee
152.8558
Traceback (most recent call last):
  File "c:\Users\Stephen\OneDrive\CodenProjects\JSON\bugreport.py", line 15, in <module>
    print(value)
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 8: character maps to <undefined>
```
[bugreport_info.json.txt](https://github.com/microsoft/vscode/files/6428608/bugreport_info.json.txt)
[bugreport_info.json.txt](https://github.com/microsoft/vscode/files/6428613/bugreport_info.json.txt)
[bugreport_info.json.txt](https://github.com/microsoft/vscode/files/6428622/bugreport_info.json.txt)
[bugreport_info.json.txt](https://github.com/microsoft/vscode/files/6428627/bugreport_info.json.txt)
Sorry for the 4 copies of the file.

**Comment by aeschli** [comment]
UnicodeEncodeError is an error from the Python runtime.

Can you file this against the Python extension? https://github.com/microsoft/vscode-python
