### ISSUE TITLE
Reference code color is missing.

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#12302]
- VSCode Version: Code - Insiders 1.6.0-insider (de7267dc4e521aa7ef4187fd6b9c98570beea540, 2016-09-19T08:28:01.071Z)
- OS Version: Darwin x64 16.0.0

**Reference code color is missing.**
nodejs
<img width="1303" alt="qq20160920-2 2x" src="https://cloud.githubusercontent.com/assets/22350/18662437/ad584308-7f1a-11e6-8b72-4eba45505a31.png">

golang
<img width="1303" alt="qq20160920-0 2x" src="https://cloud.githubusercontent.com/assets/22350/18662441/b33130b4-7f1a-11e6-9f10-d77f76ebaf7d.png">

python
<img width="1303" alt="qq20160920-3 2x" src="https://cloud.githubusercontent.com/assets/22350/18662444/b82b38a8-7f1a-11e6-98b8-662060b666ee.png">

**Comment by leaxoy** [comment]
Those picture maybe a little break.  So you can find it from origin.
[nodejs](http://o8z0dg641.bkt.clouddn.com/QQ20160920-2@2x.png)
[golang](http://o8z0dg641.bkt.clouddn.com/QQ20160920-0@2x.png)
[python](http://o8z0dg641.bkt.clouddn.com/QQ20160920-3@2x.png)

**Comment by joaomoreno** [comment]
@alexandrudima fyi, this was broken by 45d383f26865432cb02d395e75a78a0525fafdca

**Comment by joaomoreno** [comment]
Setting `important` due to regression.

**Comment by alexandrudima** [comment]
@joaomoreno The problem is my refactoring missed this call site because the call site is untyped (`mode` is `any`):

https://github.com/Microsoft/vscode/blame/master/src/vs/editor/contrib/hover/browser/modesContentHover.ts#L256

```ts
return getMode(mode)
	.then(null, err => null)
	.then(mode => `<div class="code">${ tokenizeToString(value, mode) }</div>`);
```

```ts
export function tokenizeToString(text: string, languageId: string, extraTokenClass?: string): string {
```

**Comment by joaomoreno** [comment]
Dang! Didn't notice that.

**Comment by leaxoy** [comment]
Thanks!!   But there is another issue #12437.
I think it's a good idea use different color in different token(like var, method, function, property etc..)

**Comment by joaomoreno** [comment]
@leaxoy That's a completely separate issue. Let's leave the discussion over there.

Thanks @alexandrudima, looks great!
