### ISSUE TITLE
JavaScript code coloring break when using ES6 destructuring of Objects spread on multiple lines

### ISSUE THREAD

**Issue by wojtekmaj** [Microsoft/vscode#12310]
- VSCode Version: 1.5.2
- OS Version: Windows 10 14393.187

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/5426427/18665918/b6374726-7f29-11e6-9389-cc61b5594e73.png)

**Comment by chrmarti** [comment]
Tracked as #3008
