### ISSUE TITLE
Scroll issue in 'Debug Console'

### ISSUE THREAD

**Issue by Asaf-S** [microsoft/vscode#123199]
- VS Code Version: 
- OS Version:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Clearing the `DEBUG CONSOLE` area.
2. Running `npm run debug`.
3. Expected: The `DEBUG CONSOLE` scrolls down until the end.
4. Actual:  The `DEBUG CONSOLE` scrolls down a bit and then stops, without any intervention by me, forcing me to scroll all the way to the bottom manually by myself to see the last line.
This causes me not to know whether or not the build process is done or not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Asaf-S** [comment]
The project is a Typescript Node project.
These are the relevant line from the package.json file:

  "scripts": {
    "task:tslint": "tslint -c tslint.json -p tsconfig.json --fix",
    "task:typescript": "tsc -sourcemap",
    "task:typeORM_run_migrations": "typeorm migration:run",
    "build": "npm-run-all task:tslint task:typescript task:typeORM_run_migrations",
  }

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/117674
