### ISSUE TITLE
Open Github Url in VsCode

### ISSUE THREAD

**Issue by shahul01** [microsoft/vscode#123195]
Issue Type: <b>Feature Request</b>

If Github(etc) Url is given, it should open the repository in VSCode, the repo should later be saved to custom destination, if user wants to. This makes viewing/editing on the fly possible.

Source URL: Github.com, CodeSandbox.io

Thanks

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

**Comment by lramos15** [comment]
It sounds like you want this extension https://code.visualstudio.com/blogs/2021/06/10/remote-repositories

**Comment by shahul01** [comment]
Thanks @lramos15 , github later developed this github dev site which can be accessed by pressing . on repo. So that is pretty cool too.
