### ISSUE TITLE
VSCode thinks I don't have any HTML debugger extensions when I do

### ISSUE THREAD

**Issue by iSyriux2** [microsoft/vscode#123158]
- VS Code Version: 1.56.0 (User Setup)
- OS Version: Windows 10.0.1.18363

Steps to Reproduce:

1. Run a HTML file on Chrome using 'open in browser' extension and browse random websites on the web
2. Wait for stopping the debugger to not work, and then try to close a VSCode process in Task Manager

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/62969957/117330099-579f8700-ae63-11eb-8fec-2cae069d3a84.png)

Another bug I encountered was that I was unable to stop the HTML debugger, so I tried stopping it in Task Manager, which resulted in the taskbar icon turning invisible for a second. I tried **reinstalling the latest version of VSCode** but the issue still persists. Here are my extensions.
![image](https://user-images.githubusercontent.com/62969957/117330137-60905880-ae63-11eb-92cc-02158606cbe0.png)
I've tried disabling the only extension other than open in browser, but it still doesn't work

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123106
