### ISSUE TITLE
Content of the "Untitled editors hint" for locale other than en-US contains unexpected `{0}`

### ISSUE THREAD

**Issue by gnaggnoyil** [microsoft/vscode#123152]
- VS Code Version: 1.56.0
- OS Version: Archlinux 20210505

Steps to Reproduce:

1. Install any language pack other than en-US, and set this language as the display language
2. Create a new untitled editor view.

For locale en-US, the content would be "Select a language to get ...", while for any other locale other than en-US, the content contains an unexpected `{0}` like "Select a language {0} to get ..."

Does this issue occur when all extensions are disabled?: Yes with all extensions except the above language pack disabled.

**Comment by JacksonKearl** [comment]
What language pack is it that you're using?

**Comment by gnaggnoyil** [comment]
@JacksonKearl I tried zh-CN and en-GB, both of which have that `{0}` appear in the content.

I think all other locales probably have the same issue too.

**Comment by isidorn** [comment]
This is the problem with our translations which have not been updated. Forwarding to @danyeh

**Comment by v-mholloway** [comment]
I cannot find the string "Select a language to get" in our translation libraries... @gnaggnoyil  could you provide more info or a string identifier...? or screenshot?

**Comment by danyeh** [comment]
No longer repro on zh-CN. en-GB no longer in Marketplace. Close this issue.
![image](https://user-images.githubusercontent.com/19785531/134723764-d8758e1c-5512-4657-81ac-6239e8d6dfa1.png)
