### ISSUE TITLE
Can the "Check for update" resoponse popup be shown as a notification?

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#123122]
Issue Type: <b>Feature Request</b>

currently the modal popup shown in VSCode can be configured from "native" to "custom" it is great.
![image](https://user-images.githubusercontent.com/9264813/117301605-6bb1ab80-ae98-11eb-89bf-02f8dac997c7.png)

 i always get annoyed by the native modals ding sound.

is there any plan to let the user choose if they want to show these(check for update and check for extension update) modals as the tiny notification in VSCode. 
![image](https://user-images.githubusercontent.com/9264813/117301656-78360400-ae98-11eb-8588-8e913f9625b2.png)

i always thought these notification are nice and less distracting. if user is checking for the updates manually then and did choose to see them as notification then "no updates found" being shown as notification would be nice option.

VS Code version: Code - Insiders 1.57.0-insider (fe23c2041f848d6c2f6bd27875112a37bcc82f84, 2021-05-06T05:16:25.564Z)
OS version: Windows_NT x64 10.0.19042

**Comment by joaomoreno** [comment]
Closing as we've discussed this plenty beforehand:

- https://github.com/microsoft/vscode/issues/100016
- https://github.com/microsoft/vscode/issues/44714
