### ISSUE TITLE
Provide a builtin renderer for text/latex outputs

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#123144]
VS Code has a built in renderer for markdown in markdown cells
To have a consistent look and feel, I think VS Code should also provide a builtin renderer for  text/latex

Here's how users can generate latex (markdown) outputs in cells
* Install Jupyter & Python extensions
* Create an ipynb file
* Create a Python cell with the following content & run it (output mime is `text/latex`)
```
%%latex
Given : $\pi = 3.14$ , $\alpha = \frac{3\pi}{4}\, rad$
```
* Create a Python cell with the following content & run it (output mime is `text/latex`)
```
%%markdown
# Hello
```

The mime `text/latex` is not natively supported by VS Code event though `text/markdown` is.
Suggestion is to support `text/latex` just as we support `text/markdown` as VS Code supports late in mardow & text/latex is the same as `text/markdown` with latex.

FYI - Today the Jupyter extension ships with a renderer for text/latex

@rebornix @mattbierner /cc

**Comment by rebornix** [comment]
It makes perfect sense.

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/135338537-26c87a36-10f2-4a84-8c2d-cf7d4c20e328.png)

**Comment by mjbvz** [comment]
@DonJayamanne Should this be reopened since the PR was reverted? Or is being handled in some other way now?

**Comment by pammacdotnet** [comment]
Any progress? I'd like to be able to render math expressions from a Wolfram Kernel.

sol:= Integrate[1/(1 + x^3), x]
TeXForm[sol]

**Comment by rchiodo** [comment]
We should probably reopen this. We're still tracking this work here too:
https://github.com/microsoft/vscode-jupyter/issues/7801

**Comment by DonJayamanne** [comment]
@mjbvz Sorry I missed your message, yes. @rchiodo thanks for re-opening this.

**Comment by pammacdotnet** [comment]
This a graphical representation of the difference between Jupyter (default web interface) and a VS code Wolfram kernel notebook. 

![discusion_sistema_ipynb_—_Algebra_and_discusion_sistema_-_Jupyter_Notebook](https://user-images.githubusercontent.com/4954983/140274104-0926f603-1a9f-4588-abf1-51fb40a5c712.jpg)

**Comment by pammacdotnet** [comment]
Any news on the subject?
