### ISSUE TITLE
HTML files now require an extension to run

### ISSUE THREAD

**Issue by cmrss2** [microsoft/vscode#123106]
Issue Type: <b>Bug</b>

In the April release of VSC, this issue started to happen. Before, I could simply run with F5 and everything would work fine. Now, it tells me to install an extension for debugging, even if I run without debugging.

Steps to reproduce:
1. Run a HTML file, without debugging (Ctrl + F5)
There should now be a prompt to install an extension.
2. Click on it, and install any of the extensions.
3. Try again, only to keep getting the prompt with any extension enabled. I've only tried 2 extensions, but it happened with both.

Cancel only cancels the entire thing. Attached are screenshots of me attempting to run without debugging.
I understand this is only a small issue, but to run directly from VSC is a large reason I chose this code editor. Please fix this!

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.51GB free)|
|Process Argv|--crash-reporter-id 8c746a95-70ad-4816-8370-eaf9d045842f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

![VSC 1](https://user-images.githubusercontent.com/77649553/117283828-87717d80-aea9-11eb-82f6-293e2fbdbaa4.png)
![VSC 2](https://user-images.githubusercontent.com/77649553/117283833-89d3d780-aea9-11eb-8205-4686781b2479.png)

**Comment by Flavian97** [comment]
I do have this problem and I do not have any idea of how to fix this

**Comment by JacksonKearl** [comment]
Confirmed in 1.55.2, I could hit Ctrl+F5, select Chrome, and the HTML file would open in chrome. Now there's a popup telling me I need additional extensions.

**Comment by isidorn** [comment]
@connor4312 what do you think that we fix this in the Chrome extension so that the Chrome extensions says that it is interested in `html` by specifying it in the `language` field?

**Comment by isidorn** [comment]
@connor4312 that was fast. Thanks
What do you think about doing this as part of recovery?

**Comment by connor4312** [comment]
It looks like we'll have a recovery, and I think this is a safe change.

**Comment by isidorn** [comment]
Lovely, thanks!
