### ISSUE TITLE
Round buttons look ugly and dont center their content correct

### ISSUE THREAD

**Issue by Balkoth** [microsoft/vscode#123132]
Seriously who thinks this looks ok?

![image](https://user-images.githubusercontent.com/80055480/117308211-9c3a1b00-ae81-11eb-99e3-9b99989cf0b0.png)

![image](https://user-images.githubusercontent.com/80055480/117308227-a1976580-ae81-11eb-8782-d3bce950346a.png)

Version: 1.56.0 (system setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by misolori** [comment]
Thanks for the feedback. This is intentional as not every icon is aligned to the center due to pixelation, so some icons are off-center.

**Comment by Balkoth** [comment]
So there was no background for hovered buttons in the previous version. Intentionally making the product look ugly is quite a feat to accomplish!
