### ISSUE TITLE
Should we drop the minimal icon theme?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12313]
I think the minimal icon theme does not look very good compared to our seti theme. I think our original motivation to have it was because we wanted to ship with a least one icon theme. But now that we ship with seti out of the box, imho we should drop the minimal icon theme.

Thoughts?

One reasoning is that we now start to introduce icons everywhere and imho the minimal theme does not add much value in that case:

![image](https://cloud.githubusercontent.com/assets/900690/18667213/e7ea8d90-7f2f-11e6-8e95-019fa62f8c54.png)

//cc @chrisdias @seanmcbreen @egamma

**Comment by chrisdias** [comment]
@bpasero will there be an option to show icons in the tree but not in the tabs?  

I agree that they don't provide value there, but some folks may appreciate the minimalist icons in the tree still. Even with Seti in the tree, I personally don't want icons in my tabs.

**Comment by bgashler1** [comment]
I wonder how many people use the minimal icons.  I prefer the Seti one, but one advantage of the minimal is that folders are more clearly differentiated than in Seti—Seti can sometimes appear ambiguous hierarchy-wise because of this.  Perhaps we could ask @seanmcbreen could find out how many people use the minimal icons as opposed to another set before we remove it.

**Comment by bpasero** [comment]
Btw I was not suggesting to delete the minimal theme, but make it available from the marketplace as extension. 

@chrisdias I was not planning to add settings for all the places where we show icons, let's see how it goes.

**Comment by seanmcbreen** [comment]
@seanmcbreen I have no strong view here I know I pushed for Minimal first but 😍 how we arrived at seti.  That said @bpasero not sure what the benefit of removing the existing feature is.  I can do a query tomorrow if it helps LMK.

**Comment by stevencl** [comment]
Sorry for the late reply. I too am not sure what the benefit of removing the minimal theme would be. In fact, I think the fact that we have two themes that the user can choose from better indicates that there could be other themes they might be able to download from the marketplace. With just one theme it could look like the choices available are to either have icons disabled or enabled.
