### ISSUE TITLE
Tree: dragging an item no longer shows drag feedback of the item that is dragged

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12311]
- VSCode Version: insider
- OS Version: Mac OS

Steps to Reproduce:

1. open git viewlet
2. drag an item of the tree when you have outgoing changes

=> the thing you drag is just a box with background color, but no label inside

@joaomoreno looks like a regression from the electron update?

**Comment by joaomoreno** [comment]
Yup.

**Comment by joaomoreno** [comment]
Basically it broke something in the explorer, where there are children nodes that have `position: relative` in them... Couldn't find a decent way to _position_ them differently without breaking them in some other way. Too bad, ended up going with:

![image](https://cloud.githubusercontent.com/assets/22350/18717488/6043239c-8020-11e6-874b-7038b9b2276c.png)

**Comment by bpasero** [comment]
@joaomoreno this does not help for the git viewlet though?
