### ISSUE TITLE
"Go to Definition" jumps to exception instead of symbol

### ISSUE THREAD

**Issue by JeroenBos** [microsoft/vscode#123107]
- VS Code Version: 1.55.2
- OS Version: Reproduced in Win10 (19042.928) and Ubuntu 18.04
- Does this issue occur when all extensions are disabled? Yes

### Steps to Reproduce:

I've made a minimal reproducing example [repository](https://github.com/JeroenBos/vscode-jump-bug).
To reproduce:
- Enable breaking on Caught and Uncaught Exceptions in the debug panel
- Debug (in the example repo the only configuration)
- Ensure a exception is thrown 
- Navigate to another file (in example repo `main.js`)
- Trigger the command `editor.action.revealDefinition` (="go to definition") such that it triggers navigation to the file in which the debugger is currently paused on the exception

#### Expected behavior:
Jumps to the symbol definition on which you triggered "go to definition" (in example repo `class GotoDefinitionOnThis`)

#### Behavior:
Jumps to the line with the exception.

### Some more information:

This behavior is present when debugging using any of the language servers that I use (JS, Python and C#), so I think this is a vscode issue, not a language server issue. In the example repo I chose JS because it doesn't require any extensions.

This behavior interferes with the commands `workbench.action.navigateBack` and `workbench.action.navigateForward`, as in, the location with the Symbol definition _is_ injected. So I suspect the command `editor.action.revealDefinition` works fine; it's just that immediately afterwards vscode navigates to the exception. I have observed this jump occasionally.

I asked on [SO](https://stackoverflow.com/questions/67255297/vscode-useability-issue-on-goto-definition-when-exception-thrown) first but no reply.

It's not only the Go to Definition command: other commands that navigate to a file, like `workbench.action.navigateBack`, when navigating to a file with a paused exception will jump to the wrong line (the line with the exception rather than what the command intended to navigate to).

### Workaround
After this happens, trigger the command `workbench.action.navigateBack` to navigate where you intended to navigate to.

**Comment by isidorn** [comment]
Sounds like you are using go to definition, you go to a location, and that location "by accident" is also where the exception occured. And you would like the exception to not show up.
However this is currently not possible, we always show the exception location when it occured. I can leave this issue open to gather more user feedback.
Let me know if I misunderstood something.

**Comment by JeroenBos** [comment]
> you go to a location, and that location "by accident" is also where the exception occured.

What do you mean by "location"? I mean a file + a line number (and technically also the character or range in the line). 

For example if you have a file and the exception is at line 100 but your symbol definition is on line 200, then goto definition jumps to line 100, whereas I expect to go to line 200.

**Comment by isidorn** [comment]
Aha so the go to defintion jumps to the wrong location.
That sounds weird..

**Comment by isidorn** [comment]
No plans to fix atm, closing for now
