### ISSUE TITLE
"copy xpath/jsonpath" feature on right click for XML & JSON files

### ISSUE THREAD

**Issue by chrisinhim** [microsoft/vscode#123176]
Can you please provide "Copy xpath" & "copy jsonpath" feature for XML and JSON files respectively.
This is a very fundamental feature we Software Testers need as we work on XML files and JSON files to prepare data for testing purposes.

**Comment by aeschli** [comment]
There are already some extensions out there that do stuff with JSON Path. I recommend to file an issue against these extensions to provide a copy to clipboard command.
