### ISSUE TITLE
Shortcut to open "local" explorer

### ISSUE THREAD

**Issue by homoky** [microsoft/vscode#123140]
It would be great to be able to open in folder the path to quickly navigate between folders...

<img width="1067" alt="Snímek obrazovky 2021-05-06 v 16 35 30" src="https://user-images.githubusercontent.com/893917/117316758-2c2f9300-ae89-11eb-9041-71295c2dbb61.png">

**Comment by isidorn** [comment]
Ctrl + shift + e, opens explorer.
Otherwise you can customise any keybinding in the Keyboard Shortcuts

**Comment by homoky** [comment]
Yes you are right, but when explorer is hidden and you want to use this one, there is no shortcut for it, right - to just simulate click on the path?

**Comment by isidorn** [comment]
Even if the explorer is hidden Cmd + shift + e will open the explorer

**Comment by homoky** [comment]
Yes, I do know that. The question is if there is way to open "path explorer".

**Comment by isidorn** [comment]
Oh you mean the breadcrumbs on the top?
There is probably a command for that, search for "breadcrumbs" commands and attach a keybinding to it

**Comment by isidorn** [comment]
Oh you mean the breadcrumbs on the top?
There is probably a command for that, search for "breadcrumbs" commands and attach a keybinding to it

**Comment by homoky** [comment]
Yes! I found it. Thanks. It is called `Focus Breadcrumbs`.
