### ISSUE TITLE
Terminal dropdown button becomes large when editing workspace settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123145]
Repro:

Create a workspace profile, it seems to refresh the dropdown but the style isn't correct

<img width="99" alt="Screen Shot 2021-05-06 at 8 30 42 AM" src="https://user-images.githubusercontent.com/2193314/117325215-5bbcac00-ae45-11eb-8291-1b310935f459.png">

<img width="517" alt="Screen Shot 2021-05-06 at 8 31 51 AM" src="https://user-images.githubusercontent.com/2193314/117325374-83137900-ae45-11eb-87de-1652a2443db6.png">

**Comment by meganrogge** [comment]
I'm unable to add a workspace profile - when I do in `C:\Users\merogge\repos\vscode\.vscode\settings.json`, it's not reflected in the dropdown.

**Comment by Tyriar** [comment]
It seems to happen something on editing user settings too.

Workspace profiles need `allowWorkspaceConfiguration` set
