### ISSUE TITLE
High cpu usage with release 1.57 insiders

### ISSUE THREAD

**Issue by CalebEverett** [microsoft/vscode#123191]
- VS Code Version:
- OS Version:

Version: 1.57.0-insider (user setup)
Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84
Date: 2021-05-06T05:16:25.564Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/8947267/117360229-5ffcbf80-ae6d-11eb-9ae6-4c3e1ed1b286.png)

Fan is running constantly and stops right away as soon as vscode shuts down. Didn't do that yesterday.

I'm on Windows 10, working in WSL 2.

<html>
<body>
<div class="block block-system" style="box-sizing: border-box; font-size: 12px;"><div class="block-info" style="box-sizing: border-box; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: 484.492px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px; padding: 10px;">

CPUs | Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.73GB (19.68GB free)
Process Argv | --folder-uri=vscode-remote://wsl+Ubuntu/home/caleb/projects/FINM33150/carry_trade --remote=wsl+Ubuntu --crash-reporter-id f7543aed-88e3-49ba-bc08-aa9439d824e1
Screen Reader | no
VM | 0%

## System Information
</div></div><div class="block block-process" style="box-sizing: border-box; font-size: 12px;"><input class="sendData" type="checkbox" id="includeProcessInfo" checked="" style="box-sizing: border-box; font-family: inherit; border: none; margin-top: 0px; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: auto; display: inline-block; vertical-align: middle; cursor: pointer;"><span> </span><label class="caption" for="includeProcessInfo" style="box-sizing: border-box; user-select: none;">Include my currently running processes (<a href="vscode-file://vscode-app/c:/Users/Caleb/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/issue/issueReporter.html#" class="showInfo" style="box-sizing: border-box; cursor: pointer; border: 1px solid transparent; color: rgb(55, 148, 255); text-decoration: none;">hide</a>)</label><pre class="block-info" style="box-sizing: border-box; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: 484.492px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px; padding: 10px;"><code style="box-sizing: border-box;">CPU %	Mem MB	   PID	Process
    0	   112	 18436	code-insiders main
    0	   216	   540	   gpu-process
    0	    42	  2604	   utility
    2	   211	  6956	   window (utils.py - carry_trade [WSL: Ubuntu] - Visual Studio Code - Insiders)
    0	    79	 16000	     extensionHost
    0	    59	  5672	       electron_node wslDaemon.js 
    0	     7	 15000	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" fe23c2041f848d6c2f6bd27875112a37bcc82f84 insider .vscode-server-insiders 0  '
    0	     6	 19868	           C:\WINDOWS\system32\lxss\wslhost.exe {e61aa81f-94a4-4bb0-a7cf-7d780d4f5cc0} 480 508 512 {563012fe-e674-4b6b-a212-701820b039ec}
    0	    12	  7696	             console-window-host (Windows internal process)
    0	    11	 21032	           console-window-host (Windows internal process)
    0	    92	  9248	   shared-process
    0	    63	 10712	     ptyHost
    0	    79	 12556	   window (Issue Reporter)
    0	   164	 14532	   window (undefined)
    0	    24	 20528	   crashpad-handler

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	  6870	remote agent
    0	     0	  6881	   ptyHost
    0	     0	  7119	   watcherService
    0	     0	  7328	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7329	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=</code></pre></div><div class="block block-workspace" style="box-sizing: border-box; font-size: 12px;"><input class="sendData" type="checkbox" id="includeWorkspaceInfo" checked="" style="box-sizing: border-box; font-family: inherit; border: none; margin-top: 0px; background-color: rgb(60, 60, 60); color: rgb(204, 204, 204); width: auto; display: inline-block; vertical-align: middle; cursor: pointer; orphans: 2; white-space: normal; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span></span><label class="caption" for="includeWorkspaceInfo" style="box-sizing: border-box; user-select: none; color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Include my workspace metadata (<a href="vscode-file://vscode-app/c:/Users/Caleb/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/issue/issueReporter.html#" class="showInfo" style="box-sizing: border-box; cursor: pointer; border: 1px solid transparent; color: rgb(55, 148, 255); text-decoration: none;">hide</a>)</label><span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span>
</body>
</html>

## Currently running processes
CPU %	Mem MB	   PID	Process
    0	   112	 18436	code-insiders main
    0	   216	   540	   gpu-process
    0	    42	  2604	   utility
    2	   211	  6956	   window (utils.py - carry_trade [WSL: Ubuntu] - Visual Studio Code - Insiders)
    0	    79	 16000	     extensionHost
    0	    59	  5672	       electron_node wslDaemon.js 
    0	     7	 15000	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" fe23c2041f848d6c2f6bd27875112a37bcc82f84 insider .vscode-server-insiders 0  '
    0	     6	 19868	           C:\WINDOWS\system32\lxss\wslhost.exe {e61aa81f-94a4-4bb0-a7cf-7d780d4f5cc0} 480 508 512 {563012fe-e674-4b6b-a212-701820b039ec}
    0	    12	  7696	             console-window-host (Windows internal process)
    0	    11	 21032	           console-window-host (Windows internal process)
    0	    92	  9248	   shared-process
    0	    63	 10712	     ptyHost
    0	    79	 12556	   window (Issue Reporter)
    0	   164	 14532	   window (undefined)
    0	    24	 20528	   crashpad-handler

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	  6870	remote agent
    0	     0	  6881	   ptyHost
    0	     0	  7119	   watcherService
    0	     0	  7328	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7329	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
				
## Worskpace Meta Data
|  Remote: WSL: Ubuntu|    Folder (carry_trade): 57 files|      File types: csv(9) py(7) pyc(5) ipynb(4) keep(2) gitignore(2) md(2)
|                  coverage(1) coveragerc(1) env(1)
|      Conf files: github-actions(1) settings.json(1)

## Enabled extensions
<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
remote-ssh | ms- | 0.65.4
remote-ssh-explorer | ms- | 0.34.0
remote-wsl | ms- | 0.56.1
vscode-remote-extensionpack | ms- | 0.20.0
git-graph | mhu | 1.30.0
python | ms- | 2021.5.815083650-dev
jupyter | ms- | 2021.6.816326582
code-spell-checker | str | 1.10.2

</body>
</html>
			
## A/B Experiment Info
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782
3f5j7703:30294757

**Comment by JacksonKearl** [comment]
Thanks for reporting, could you please follow the steps here: https://github.com/microsoft/vscode/wiki/Performance-Issues to help us in diagnosing this problem?

**Comment by CalebEverett** [comment]
Hi - sure thing - I tried to submit from the application, but it said I had too much info and was going to open another issue in Github, so I just added the info to this one. I think I got everything, but let me know if I need to add anything.

**Comment by CalebEverett** [comment]
I think this may have been related to a virtualenv that had gone bad. After rebuilding it, the fan seems to have stopped running.
