### ISSUE TITLE
V1.56 update broke editor menu bar icons of Shortcut Menu Bar extension

### ISSUE THREAD

**Issue by GorvGoyl** [microsoft/vscode#123118]
- VS Code Version: 1.56
- OS Version: Windows 10

Hey there, I'm the author of [Shortcut Menu Bar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar). Latest VSCode release is causing problems in rendering editor menu bar icons. 

Steps to Reproduce:

1. use VSCode 1.56
2. install [Shortcut Menu Bar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar)
3. observe editor menu bar icons

**Expected behavior:**  

![image](https://user-images.githubusercontent.com/7106086/117296568-d6f87f00-ae92-11eb-9f03-21247541c6d0.png)

**Current behavior:**  

![image](https://user-images.githubusercontent.com/7106086/117296643-e972b880-ae92-11eb-86b8-01248145e816.png)
 
**Issue doesn't exist if I downgrade from v1.56.**

Related bug: https://github.com/GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension/issues/54

Let me know if you need further details.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hadi4172** [comment]
Same problem here, It broke not only the extension jerrygoyal.shortcut-menu-bar, but others also, like nanlei.save-all and panzerstadt.light-dark-toggle

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/123041

**Comment by KinanLak** [comment]
Same
