### ISSUE TITLE
i18n: incorrect strings at feedback panel

### ISSUE THREAD

**Issue by zlumyo** [Microsoft/vscode#12317]
Russian translations of strings _"character left"_/_"characters left"_ use _'left'_ as direction (e.g. turn left). It would be great to fix it using _"символ остался"_/_"символов осталось"_ respectively.

**Comment by johnliu2016** [comment]
@lukaschal 

please send this to linguistic review

[feedback.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Frus%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Ffeedback%2Fbrowser%2Ffeedback.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";character left" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[character left]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[символ слева]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>
      <Item ItemId=";characters left" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[characters left]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[символов слева]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

**Comment by Tyriar** [comment]
Verified, the last word is different but I assume it's intentional since it also seems to mean remaining.

**Comment by zlumyo** [comment]
> it also seems to mean remaining.

As native speaker I dare to claim it's wrong.
By the way thanks for quick fix.

**Comment by Tyriar** [comment]
@johnliu2016 any reason for the change in wording from that suggested by @zlumyo?

**Comment by johnliu2016** [comment]
@lukaschal can you take a second look?

**Comment by lukaschal** [comment]
@Tyriar Here is full linguistic answer. Is this acceptable ?
	
I would suggest the following translations:
 
SRC: character left
TGT: символ слева
CORRECT: символ остался
(According to the suggestion.)
 
SRC: characters left
TGT: символов слева
CORRECT: симв. осталось
(This one is different from the suggestion, because using «символов осталось» is not correct for all numbers possible.)

**Comment by zlumyo** [comment]
@lukaschal It is perfect.

**Comment by Tyriar** [comment]
Thanks @lukaschal
