### ISSUE TITLE
Feature request ? Focus follows mouse.

### ISSUE THREAD

**Issue by i-frost** [Microsoft/vscode#12319]
I have this set on my OS and I can save files when I mouse off the vscode window.

But I wonder why inside vscode the focus does not follow the mouse ie if I have the integrated terminal open I have to click inside that pane before typing, then click back on the editor window etc.

Not such a big deal but I guess I am so used to working this way and it seems like it could be a easy fix to add a setting, I did search for one but found nothing obvious.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by cu** [comment]
Bummer. I would have liked to see this as an option as well. I rarely use the built-in terminal because of it.
