### ISSUE TITLE
Is Azure Repos is going to have its own PR extension?

### ISSUE THREAD

**Issue by izacsc** [microsoft/vscode#123126]
We already have the Github PR and Issues extension. Are there any plans to provide a similar extension to Azure Repos?

**Comment by RMacfarlane** [comment]
Hey @izacsc, there are currently no plans for the VS Code team itself to develop this extension, but there is already an extension in the marketplace that adds support for this: https://marketplace.visualstudio.com/items?itemName=ankitbko.vscode-pull-request-azdo
