### ISSUE TITLE
Terminal Tabs enabled by default.

### ISSUE THREAD

**Issue by Xalior** [microsoft/vscode#123134]
- VS Code Version: 1.56
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Upgrade to latest VSCode.
2. Open more than one tab.

Expected Result:
Things are the same as before.

Actual Result:
Terminals appear in tabs now.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

This wouldn't be so bad, but when changing between tabs, keypresses now go to the terminal tab "pane", not the terminal so - for example -  up cursor key switches the highlight between tabs, not brings the last item in my command history up.  I now have to click into the tab after switching tabs for it gain event focus.

**Comment by Xalior** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Tabbing into terminal needs 2 tabs (#117353)](https://www.github.com/microsoft/vscode/issues/117353)
> * [Allow renaming terminal tabs inside the tab view (#122023)](https://www.github.com/microsoft/vscode/issues/122023)
> * [Weird visual selection state for few frames when clicking on terminal tabs (#122422)](https://www.github.com/microsoft/vscode/issues/122422)
> * [Dragging tabs should show an insertion target, not a replacement target (#118419)](https://www.github.com/microsoft/vscode/issues/118419)
> * [Terminal tabs CSS rules are not terminal tabs specific (#121258)](https://www.github.com/microsoft/vscode/issues/121258)

None of these are about the fact that this experimental feature is enabled by default, which is the exact opposite of what the release notes claim it should be.

**Comment by meganrogge** [comment]
It should be disabled by default. You can easily go back to the old way by setting `terminal.integrated.tabs.enabled: false` or by right clicking the terminal and choosing hide tabs in the context menu while we polish tabs this iteration.

**Comment by Tyriar** [comment]
Terminal tabs has seen many improvements and will be enabled in the upcoming version. You can always disable them in settings if you want.

**Comment by Xalior** [comment]
> Terminal tabs has seen many improvements and will be enabled in the upcoming version. You can always disable them in settings if you want.

I am aware of that.  What I can do, and what is _directly_ _stated_ in your onboarding readme are not the same.

The readme claimed the old behavior would be the default.  That is not what I saw.
