### ISSUE TITLE
Debug Powershell Untitled Files Not Working

### ISSUE THREAD

**Issue by SoulSeekkor** [microsoft/vscode#123179]
Issue Type: <b>Bug</b>

Unless my memory is incorrect, one of the biggest advantages to VS Code over ISE was that we used to be able to set breakpoints and debug Powershell files that were untitled and not saved yet.

With this version I've noticed that no longer works, I can set a breakpoint on an untitled tab and it does not stop, it simply runs the entire script without stopping.

![image](https://user-images.githubusercontent.com/16005426/117347861-2c229980-ae6f-11eb-9a8c-89400cc1c99d.png)

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (3.55GB free)|
|Process Argv|--crash-reporter-id 4cda4c07-a942-4082-a034-ead1f803f951|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.2.2
material-icon-theme|PKi|4.6.0
vscode-inline-values-powershell|Tyl|0.0.5

</details>

**Comment by isidorn** [comment]
@TylerLeonhardt this should just work right? Can you double check?

**Comment by TylerLeonhardt** [comment]
It should just work. Seems to be working for me:
![image](https://user-images.githubusercontent.com/2644648/117360064-2d52c700-ae6d-11eb-915c-af1ebf43917b.png)

You probably want to get an issue going in the PowerShell extension for further debugging:

/extPowershell

**Comment by TylerLeonhardt** [comment]
please bot, work your magic!
