### ISSUE TITLE
Why is auto-import never working?

### ISSUE THREAD

**Issue by ManelGonzalez-ops** [microsoft/vscode#123147]
Why do the hell I need to put "checkJs: true" in the jsconfig.json for your code editor to make auto-imports correctly?? I don't want your types, just not wasting my time and introducing bugs by manually typing imports like a monkey. Do you get the little difference?

Is some kind of joke?? We are in 2021, even a child could code that feature. Even with IntelliJ which is not a native js code editor/IDE can do that for me with no config.

**Comment by mjbvz** [comment]
Your issue is rudely worded and doesn’t provide any useful information about the problem
