### ISSUE TITLE
VsCode 1.56 - When start debuging, Windows Powershell terminal is opened instead of Git Bash 

### ISSUE THREAD

**Issue by ymouhat** [microsoft/vscode#123163]
- VS Code Version: 1.56.0
- OS Version: Windows 10

Steps to Reproduce:

1.Open Visual Studio code
2. Do CTRL + SHIFT + P  , and select "Terminal: Select Default Profile".
3. Select Git Bash.
4. Close all the terminal.
5. On the main menu, click Terminal >  New Terminal ( a bash Terminal is opened ok)
6. Click Run > Start debuging ,  the terminal switch to powershell

The only workaround is to keep using the following information in the user setting.json files 
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  But it is mentioned as deprecated
 
If I use the following setting , the same problems occurs ( windows powershell terminal opens instead of git bash)
```
   "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "path": [
                "C:\\Program Files\\Git\\bin\\bash.exe",
            ],
            "source": "Git Bash",
            "icon": "terminal-bash"
        },
        "Windows PowerShell": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
```
Thanks in advance

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think this is happening because debug depends on `ExtHostTerminalService.getDefaultShell` which uses a deprecated method to fetch the default shell that does not support the `defaultProfile` setting. We're switching the default back so shell/shellArgs take priority over `defaultProfile` in https://github.com/microsoft/vscode/pull/123174. I'd recommend sticking with `terminal.integrated.shell.windows` for now until this issue is handled.

**Comment by ymouhat** [comment]
Ok thanks @Tyriar for your quick answer.

**Comment by dweil** [comment]
Blocking issue for me, powershell is opened instead  of cmd.exe

**Comment by meganrogge** [comment]
@rzhao271 what happened here? should this have `verification-found`?

**Comment by rzhao271** [comment]
I was unable to reproduce the original issue in 1.56.2, but I did manage to notice a difference in behaviour for #124886, a potential duplicate. I'll mark this issue verified.
