### ISSUE TITLE
Run and Debug panel shows-up when stepping out multi-thread program.

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode#123164]
- VS Code Version: Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version: Windows 10

Steps to Reproduce:

I have been happily debugging lately c applications using vscode + cpp extension. I have noticed that when attaching to a non multi-threaded process, the 'Run and Debug' panel stays close if I say so; but it does not when program is multi-threaded. Steps to reproduce below:

1. Attach to multi-threaded program
2. Put a break point
3. Do something that triggers break point
4. Close the 'Run and Debug' panel
5. Do an step-out in the program
6. The 'Run and Panel' reappears automatically ... I do not like that, I want to decide when it should show up.
Thanks.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Use the following setting please 	
```
"debug.openDebug": "neverOpen",
```

**Comment by dariomx** [comment]
oh yeah, that made the trick ... not sure why it switched to that option, i guess i had it before to never open.

thanks a ton!

guaf.
