### ISSUE TITLE
Terminal stuck in "Starting..." state after restarting localhost a few times

### ISSUE THREAD

**Issue by GeorgeXCV** [microsoft/vscode#123161]
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. Node JS web project with nodemon installed
2. I started localhost a couple times, opening and closing terminal each time, worked fine until like 3rd or 4th time.

The issue persists after restarting VS Code so I can't continue work on my project.

<img width="686" alt="Screenshot 2021-05-06 17 32 24" src="https://user-images.githubusercontent.com/13811547/117333924-59803f00-ae91-11eb-81af-01052e621fa2.png">
<img width="680" alt="Screenshot 2021-05-06 17 34 04" src="https://user-images.githubusercontent.com/13811547/117333926-5a18d580-ae91-11eb-8fa3-302a1bd6eb64.png">

**Comment by Tyriar** [comment]
I believe these issues have been fixed since this was reported.
