### ISSUE TITLE
Improve terminal dropdown menu

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123128]
There are a few things here:

- There's no way to split using the default terminal, one must pick a shell
- The JavaScript Debug Terminal is missing from the `Split...` submenu
- The default terminal should be indicated maybe with a literal ` (default)` on the menu item

![image](https://user-images.githubusercontent.com/22350/117304360-83564900-ae32-11eb-9bda-c83abefdf595.png)

**Comment by joaomoreno** [comment]
On a similar note: I wonder if it was wise to remove the `Split Terminal` action from the top actions.

**Comment by Tyriar** [comment]
> There's no way to split using the default terminal, one must pick a shell

Click the "single tab" for a dropdown

<img width="241" alt="Screen Shot 2021-05-06 at 8 44 47 AM" src="https://user-images.githubusercontent.com/2193314/117327319-519bad00-ae47-11eb-8bf1-637cc92ed200.png">

alt/shift+click on + is coming soon https://github.com/microsoft/vscode/issues/122117

> The JavaScript Debug Terminal is missing from the Split... submenu

Not possible with current contribution, covered in https://github.com/microsoft/vscode/issues/120369

> The default terminal should be indicated maybe with a literal (default) on the menu item

WT doesn't do this:

<img width="268" alt="Screen Shot 2021-05-06 at 8 46 40 AM" src="https://user-images.githubusercontent.com/2193314/117327589-9c1d2980-ae47-11eb-937a-656a43d7dd5c.png">

Isn't adding the default just noise?

**Comment by joaomoreno** [comment]
> Click the "single tab" for a dropdown

Yes I know this. But why wouldn't we add it to that other dropdown?

![image](https://user-images.githubusercontent.com/22350/117431009-9114d880-aedd-11eb-801f-7ca47e84326f.png)

I know my options are already on other dropdowns but at the point that I have opened this dropdown that's already too late: I see options and I want to pick one. Now, I don't enjoy having to use my brain to pick something so obvious: `zsh` is my default and it appears right in the middle of other options. It's just fricition not to highlight it as the default both in the top menu as well as the Split submenu. I feel like this is self-evident and doesn't really require a discussion.

**Comment by Tyriar** [comment]
You're right, let's move the default to the top as well as indicate default:

<img width="414" alt="Screen Shot 2021-05-07 at 5 06 33 AM" src="https://user-images.githubusercontent.com/2193314/117447225-12766600-aef2-11eb-95e8-65fe2f614a1f.png">

**Comment by Tyriar** [comment]
Turns out this needs a decent amount of refactoring to get right, when you press + it doesn't necessarily show up in the list of profiles, for example if you have `terminal.integrated.shell.platform` assigned or if you do not have `defaultProfile` set. I'm going to make these changes:

- When you don't have `defaultProfile` set, it will try to assign an actual profile from the list as the default, instead of the current internal "Generated" profile.
- If you have `terminal.integrated.shell.platform` or `terminal.integrated.shellArgs.platform` assigned, no default will show up. These settings are deprecated and it would be a bit of work to support those showing up in the list.

**Comment by joaomoreno** [comment]
@Tyriar Not sure if this regressed but I don't see the default on the top anymore:

![image](https://user-images.githubusercontent.com/22350/119714008-30f7bf00-be17-11eb-9e73-28d03b35d6d3.png)
