### ISSUE TITLE
Debug: is there a way to terminate preLaunchTask process (when debug stops)?

### ISSUE THREAD

**Issue by yanivefraim** [Microsoft/vscode#12315]
Steps to Reproduce:

I am debugging my server (node) code and I added a "start cdn server" preLaunchTask. This task is starting an express server which serves my static files (I want to be able to open my browser and enter server code in debug mode).

While it works fine, I want to be able to kill this cdn server process when debug stops. I was expecting the prelaunch task to be a child process of the debug process, which would solve my problem, but it isn't (it is a child process of VS Code).

Is there a reasonable solution to my problem?

**Comment by chrmarti** [comment]
You could launch a wrapper.js that first starts your cdn server and then the actual debugging target. That should make the cdn server a child process of the wrapper. Would that work for you?

**Comment by yanivefraim** [comment]
Thanks @chrmarti. I was thinking about a similar solution, the problem is that I'll have to spawn `index.js` from wrapper, which I found hard to debug.

I have several scenarios which I want to start a process (watch/cdn) before debug and kill it when debug ends. It would be nice if we can have some control (in the form of event?) or have the option to run pre launch task as child process

**Comment by chrmarti** [comment]
@yanivefraim You could probably also 'require' index.js from debug.js once the cdn server has started. That should allow you to debug index.js. Would that work?

Or: Let the cdn server check if the debug target is running and exit after 10s of not seeing it?

Maybe VS Code could check if the preLaunchTask is still running when the target exits and send it a signal (as you suggest). Will mark this as a feature request for that.

**Comment by yanivefraim** [comment]
Thanks! I think this can be really helpfull

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11522
@chrmarti gives a nice workaround also
