### ISSUE TITLE
Menu actions affect wrong window/project if menu in second window is clicked while menu active in first window.

### ISSUE THREAD

**Issue by dfcowell** [Microsoft/vscode#12312]
- VSCode Version: 1.5.2
- OS Version: Windows 10 Pro Insider Preview (Fast Ring) Build 14926

Steps to Reproduce:
1. Open VSCode (let's call this Window 1)
2. Open an additional window (Window 2) via File > New Window such that the menu bars of both windows are visible.
3. Click "File" in Window 1.
4. While that menu is open, click "File" in Window 2 and select "Open." Open anything.

Expected behaviour: File opens in Window 2.

Actual behaviour: File opens in Window 1.

It doesn't appear to matter what menu item or action you select in steps 3 or 4. Whichever action it is is applied to Window 1's editor/project.

**Comment by chrmarti** [comment]
Not sure if we are in charge of that or Electron.

**Comment by bpasero** [comment]
This is an electron issue: https://github.com/electron/electron/issues/7282
