### ISSUE TITLE
Variable names that starts with switch break C# text color themes

### ISSUE THREAD

**Issue by De-Panther** [microsoft/vscode#123123]
Issue Type: <b>Bug</b>

Name a variable with a name that starts with `switch`, all the text after it will become white on dark themes.
On light themes it will become black.
Tested with all the basic themes:
Light, Light+, Quiet Light, Solarized Light, Visual Studio 2019 Light,
Abyss, Dark, Dark+, Kimbie Dark, Monokai, Monokai Dimmed, Red.

![image](https://user-images.githubusercontent.com/4749703/117300517-4ade5b80-ae82-11eb-94f9-d311b284f7fa.png)

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
shaderlabformatter|lit|0.4.0
csharp|ms-|1.23.11
cpptools|ms-|1.3.1
vetur|oct|0.33.1
unity-debug|Uni|3.0.2

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue, I suspect the problem is coming from the ms.csharp extension that you have installed.

My test code:
```c#
bool switchATest = false;
```

**Comment by De-Panther** [comment]
Thanks
