### ISSUE TITLE
Terminal layout

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#123121]
Now I updated vs code right now and I don't like the terminal layout. The terminal layout was much better before. If possible please change back

**Comment by meganrogge** [comment]
You can easily go back to the old way by setting terminal.integrated.tabs.enabled: false or by right clicking the terminal and choosing hide tabs in the context menu while we polish tabs this iteration.

**Comment by meganrogge** [comment]
Duplicate of #123134
