### ISSUE TITLE
Can't update on Mac OS Big Sur

### ISSUE THREAD

**Issue by rcrooks** [microsoft/vscode#123129]
Issue Type: <b>Bug</b>

1. Check for Updates
2. Get this message:
Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. This might mean the application was put on quarantine by macOS. See [this link](https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469) for more information.

The linked issue didn't help: the app is in /applications, not /downloads. The terminal commands failed.

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id ad7fee78-6fb1-4455-9557-06ebac287c54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-openapi|42C|4.5.1
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
auto-add-brackets|ali|0.11.0
vs-redoc-viewer|Ati|0.0.3
atlascode|atl|2.8.6
shell-syntax|bma|1.0.1
htmltagwrap|bra|0.0.7
webvalidator|Cel|1.0.9
json-tree-view|Cha|2.6.0
path-intellisense|chr|2.3.0
magpix|cra|1.1.0
textpad-icon-theme|dam|1.19.20
change-color|Dee|0.0.1
moxer-icons|Equ|5.8.0
json-tools|eri|1.0.2
auto-close-tag|for|0.5.10
duplicate|gee|1.0.1
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-pull-request-github|Git|0.25.1
gruvbox-ish|Gra|0.5.16
vscode-colorize|kam|0.11.1
string-manipulation|mar|0.5.2
rainbow-csv|mec|1.8.1
openapi-lint|mer|1.2.0
git-graph|mhu|1.30.0
vscode-json-editor|nic|0.3.0
html-fmt-vscode|Nik|0.7.0
prettier-standard-vscode|num|0.8.1
indent-rainbow|ode|7.5.0
es6-css-minify|olb|3.3.2
color-tabs-vscode-ext|ore|0.12.1
vscode-yaml-sort|Pas|4.1.0
salt-water-taffy|rad|0.3.0
htmlescape-vscode-extension|ray|0.0.7
vscode-yaml|red|0.18.0
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
pdf|tom|1.1.0
json2yaml|tux|0.2.0
alphabetical-sorter|ue|2.0.1
file-icons-mac|way|1.0.1
terminal-all-in-one|yas|1.11.16

(31 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by mcskinner** [comment]
Really? @deepak1556 you took six months to respond to the issue, and then closed it after waiting only one week for updated details?

this was still an issue for me very recently, and I suggest you actually look into it after multiple closed issues without a resolution.
