### ISSUE TITLE
Emmet selection in CDATA

### ISSUE THREAD

**Issue by elTopop** [microsoft/vscode#123136]
Issue Type: <b>Bug</b>

Selecting a section of text within CDATA in XML leads to the entire CDATA content being selected upon Wrap with Abbreviation.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:00.942Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.64GB free)|
|Process Argv|--folder-uri file:///c%3A/Brightwave/Bitbucket/kpg284 --crash-reporter-id 63fdc12f-ac50-49e9-aba4-73f222b47484|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.1
auto-close-tag|for|0.5.10
beautify|Hoo|1.5.0
vscode-peacock|joh|3.9.1
open-all-files|log|0.0.8
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
copy-file-name|nem|1.2.0
synthwave-vscode|Rob|0.1.8
vscode-multiclip|sle|0.1.5
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by rzhao271** [comment]
I'm probably misunderstanding what you're doing, but here's a screencap showing how I wasn't able to reproduce your issue:

![recording (5)](https://user-images.githubusercontent.com/7199958/117367741-6d1eac00-ae77-11eb-8c64-406489b4b69a.gif)

I'm wondering if you can attach more specific repro steps, or record a screencap (e.g. using https://gifcap.dev)?

**Comment by rzhao271** [comment]
Ok, I reproduced your issue in the following case:

1. Add the line `<![CDATA[<message>sample text</message>]]>` to an XML file.
2. Place the cursor on the opening `message` tag.
3. Run the "Emmet: Wrap with Abbreviation" command.
4. 🐛 The entire CDATA node is selected.

Is this the issue you're seeing?

**Comment by elTopop** [comment]
Hello,

Here are a couple of screengrabs to illustrate:

***@***.***D74326.E4F21E90]

…but Wrap with Abbreviation now selects the whole CDATA’d content:

***@***.***D74326.E4F21E90]

Fairly sure this is a new thing…

Hope you can help!

Cheers,
Dan

**Comment by rzhao271** [comment]
I'm unable to see the screengrabs; I think they got filtered out.
Can you paste specific examples of snippets and cursor/selection positions that cause the bug for you?

For example,

`<![CDATA[<m|essage>sample text</message>]]>` results in the entire CDATA being selected for me, whereas
`<![CDATA[|<message>|sample text</message>]]>`, or selecting the entire opening tag, is fine.

**Comment by elTopop** [comment]
Hey sure, so for example:

<example>
               <![CDATA[
               <p>Lorem</p>
               <p>Lorem [HIGHLIGHT START HERE]Text to select[HIGHLIGHT END HERE]</p>
               <p>Lorem</p>
        ]]>
</example>

Then Emmet: Wrap with Abbreviation will modify the highlighted area to:

<example>
        [HIGHLIGHT START HERE]
               <![CDATA[
               <p>Lorem</p>
               <p>Lorem Text to select</p>
               <p>Lorem</p>
        ]]>
[HIGHLIGHT END HERE]
</example>


Which is super annoying!

Any insight would be most appreciated!

Cheers,
Dan

**Comment by rzhao271** [comment]
Verifier: see https://github.com/microsoft/vscode/issues/123136#issuecomment-842173371
