### ISSUE TITLE
Can't set workspace-specific default terminal

### ISSUE THREAD

**Issue by bugadani** [microsoft/vscode#123133]
In one of my workspaces, I need to initialize the terminal with a custom script. VSCode lets me do this, but I can't set this terminal up as the default, because `terminal.integrated.defaultProfile.windows` can only be set in the application settings.

I consider this behaviour a regression since the previous solution (`terminal.integrated.shell` & `shellArgs`) worked perfectly but is now ignored (#123069).

**Comment by meganrogge** [comment]
Duplicate of #123031
