### ISSUE TITLE
Opening search editor via explorer alternates between search editor and text editor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#123192]
Moved to default but I still see this. Another oddity: if I click the file in the explorer once, it opens in search editor. If I click it again, it reopens in text editor, as I click more and more it keeps alternating, or even opening new editors.

_Originally posted by @JacksonKearl in https://github.com/microsoft/vscode/issues/121668#issuecomment-833827953_

**Comment by JacksonKearl** [comment]
cc @lramos15 is this something from your end or mine do you think?

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/0caa2af4d147655df88717d7ef89ad43ef749407
