### ISSUE TITLE
Terminal profiles: 'overrideName' is ignored for default terminal.

### ISSUE THREAD

**Issue by lujomu** [microsoft/vscode#123104]
Issue Type: <b>Bug</b>

When a
- **custom default profile** has been configured for the **integrated terminal**
- with the option `"overrideName": true` set,

and it is launched
- either **automatically** (i.e. when the terminal panel is opened for the first time after launching VSCode),
- or by pressing the **plus-button** in the terminal panel,

the `overrideName` **option is ignored** and the process name is used as the terminal label instead of the profile name.

In contrast, when launching the same profile from the terminal pane's plus-button drop-down menu, the profile name is correctly used as label.

'settings.json':
```
{
    "terminal.integrated.defaultProfile.windows": "My CMD",
    "terminal.integrated.profiles.windows": {
        "My CMD": {
            "path": "cmd.exe",
            "overrideName": true,
        },
    }
}
```

Steps to Reproduce:

1. Start VSCode with a new profile and the above 'settings.json'.
2. Open the terminal panel; the label will show `1: cmd` (instead of `1: My CMD`).
3. Press the plus-button; the label will show `2: cmd` (instead of `2: My CMD`).
4. Select 'My CMD' from the plus-button drop-down menu; the label will show `3: My CMD` (as it should).

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.42GB free)|
|Process Argv|--user-data-dir D:\\VSCode_Temp\\Data --extensions-dir D:\\VSCode_Temp\\Exts --crash-reporter-id 10dfc8ce-b5ac-4023-ba6d-1182cd49996c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vscnewfiletext:30294816
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by AlencarGabriel** [comment]
After the april update all my profiles defined at terminal.integrated.profiles.windows stopped work. 
It's as if VsCode is ignoring this configuration.

**Comment by AlencarGabriel** [comment]
> After the april update all my profiles defined at terminal.integrated.profiles.windows stopped work.
> It's as if VsCode is ignoring this configuration.


I added the configuration `"terminal.integrated.allowWorkspaceConfiguration": true` and now my profiles have reappeared. My configurations was in the workspace too.

**Comment by lujomu** [comment]
> After the april update all my profiles defined at terminal.integrated.profiles.windows stopped work.
> It's as if VsCode is ignoring this configuration.

For me, the integrated terminal profiles do work just fine after the April update (apart from the issue with `overrideName`), without any modification.

**Comment by AlencarGabriel** [comment]
> > After the april update all my profiles defined at terminal.integrated.profiles.windows stopped work.
> > It's as if VsCode is ignoring this configuration.
> 
> For me, the integrated terminal profiles do work just fine after the April update (apart from the issue with `overrideName`), without any modification.

@lujomu, My problem was related to the settings in the workspace. `The setting" terminal.integrated.allowWorkspaceConfiguration ": true` solved my problem.

**Comment by Tyriar** [comment]
I can confirm this is a bug, we don't seem to respect `overrideName` only when launching default shells, not when launching the profile via the dropdown.
