### ISSUE TITLE
terminal.integrated.defaultProfile.windows not working on startup

### ISSUE THREAD

**Issue by hosseini44444** [microsoft/vscode#123188]
Issue Type: <b>Bug</b>

Hello!

## current behavior:
From when I upgraded to this version when I set the default terminal to git bash and start VScode, for less than 2 seconds it shows `starting...` in the terminal's drop-down menu and then opens `PowerShell`  but after that when I add a new terminal `git bash` opens which is the default.

## Expected behavior:
I expect `git bash` which I have set as my default terminal profile to be opened at startup and afterward.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 270 Processor (2 x 3416)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.00GB (2.82GB free)|
|Process Argv|--crash-reporter-id 175e6498-4ca0-4d8a-815a-1ce71fc18411|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by thetrompf** [comment]
I have problems with this as well, it looks like if you simply start the terminal too quickly after a vscode project is loaded, then the defaultProfile is not loaded. If I exit the first terminal and start another one, the terminal profile is correctly loaded.

![Peek 2021-05-07 08-24](https://user-images.githubusercontent.com/1430118/117406766-ca653c80-af0d-11eb-8378-0854664dfda7.gif)

Which affects when a terminal is restored from a previous session which is also too quickly.

![Peek 2021-05-07 08-24a](https://user-images.githubusercontent.com/1430118/117406871-fc769e80-af0d-11eb-96f8-6a6a322b73ec.gif)

If I simply wait until most/all of my extensions are loaded and their respective indicators appears in the status bar, then the profile is correctly loaded - even on startup.

![Peek 2021-05-07 08-28](https://user-images.githubusercontent.com/1430118/117407112-5e370880-af0e-11eb-8bcb-46762d70008e.gif)

**Comment by shivapoudel** [comment]
@Tyriar when we can expect the next VSCode patch release? Every time, I open VSCode default bash terminal is not opened and on Windows Powershell is opened!

**Comment by 71** [comment]
In the meantime the settings `terminal.integrated.shell.{os}` and `terminal.integrated.shellArgs.{os}`, though deprecated, work fine.

**Comment by Tyriar** [comment]
> In the meantime the settings terminal.integrated.shell.{os} and terminal.integrated.shellArgs.{os}, though deprecated, work fine.

Yes this is a good workaround for now. It's happening because the "fallback profile" is evaluated on the extension host which takes some time to startup. I expect this to get fixed when we tackle this debt item https://github.com/microsoft/vscode/issues/122534
