### ISSUE TITLE
Feature Request: Zoom control UI

### ISSUE THREAD

**Issue by dg2k** [Microsoft/vscode#12318]
- VSCode Version: 1.5.2
- OS Version: 10.0.14393

Would be great to have a zoom control UI as for Visual Studio:
- On status bar with editable ComboBox of zoom percentages (note bottom-left (on LTR) corner of VS2015 as an example).
- ~~Ctrl + Mouse-wheel providing smooth zoom in/out control (btw this is supported by many apps at OS level).~~ [ **this feature exists already** - thanks @chrmarti ]

Hope this is not a dupe request.

**Comment by chrmarti** [comment]
Ctrl + Mouse-wheel zoom can be enabled in the settings: "editor.mouseWheelZoom": true

**Comment by dg2k** [comment]
Oh! Thanks, I overlooked that one while going thru Settings.

**Comment by seanmcbreen** [comment]
Oops I incorrectly close this

**Comment by seanmcbreen** [comment]
One thing to note is that it is possible to create an extension to do this,

**Comment by twlamb** [comment]
Is there a way to retrieve the current zoom from the API? I was looking at creating an extension to do this quick, and haven't found anything in the API that gives that info

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
