### ISSUE TITLE
VS Code on CentOS 8 unresponsive, code --status returns ERROR:viz_main_impl.cc(150) Exiting GPU process due to errorrs during initialization

### ISSUE THREAD

**Issue by DBAugie** [microsoft/vscode#123190]
Operating system:  Centos 8 on vm provided by aws
uname -srpo: Linux 3.10.0-1160.25.1.el7.x86_64 x86_64

VS Code: code v 1.56.0 release 1620166346.el8

code --status
[11487:0506/194429.828918:ERROR:VIZ_main_impl.cc(150)] Exiting GPU process due to errors during initialization

and it stops right there. I have to use CTRL-C to regain control of the terminal.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`

**Comment by DBAugie** [comment]
I can generate the output of code --verbose, but it is 177kb and that's a
lot of transcribing

I'll have to find assistance to send the file to you. I will try again in
the morning.


Thanks,


Gus



Sent from Mail <https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
10



*From: *Robo ***@***.***>
*Sent: *Thursday, May 6, 2021 4:48 PM
*To: *microsoft/vscode ***@***.***>
*Cc: *Gus Spier ***@***.***>; Author ***@***.***>
*Subject: *Re: [microsoft/vscode] VS Code on CentOS 8 unresponsive, code
--status returns ERROR:viz_main_impl.cc(150) Exiting GPU process due to
errorrs during initialization (#123190)



Can you provide the output of code --verbose

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vscode/issues/123190#issuecomment-833854835>,
or unsubscribe

**Comment by DBAugie** [comment]
Small correction: OS is CentOS 7, but same behavior.

Yes. Attached is output from code --verbose
[20210507_code--verbose.txt](https://github.com/microsoft/vscode/files/6443078/20210507_code--verbose.txt)

**Comment by deepak1556** [comment]
You are hitting https://github.com/microsoft/vscode/issues/115784, please install gcc-5 or higher toolchain for your distro to fix the issue. Merging to https://github.com/microsoft/vscode/issues/115784
