### ISSUE TITLE
Native notebooks is missing "run all cells above" and "run this cell and all others below"

### ISSUE THREAD

**Issue by jflam** [microsoft/vscode#123162]
- VS Code Version: 1.57.0-insider
- OS Version: 10.0.21376

Steps to Reproduce:

1. Open VS Code Insiders. I'm using Insiders Python extension - 2021.5.815083650-dev from a WSL 2 (Ubuntu 20.04 LTS) shell
2. Open a Jupyter notebook
3. The toolbar (yay for being on left!) is missing "run all cells above" and "run this cell and all others below" buttons

![image](https://user-images.githubusercontent.com/8877/117334278-aabb0f00-ae4e-11eb-9016-35a118b38db5.png)

Does this issue occur when all extensions are disabled?: No because the notebook won't load.

**Comment by rebornix** [comment]
@DonJayamanne any idea why it's not working?

**Comment by DonJayamanne** [comment]
@jflam it was hidden due to a bug, but wasn't meant to be hidden in Insiders as well.

**Comment by rebornix** [comment]
The bug @DonJayamanne referred to is https://github.com/microsoft/vscode/issues/123002 which we are troubleshooting now.

**Comment by DonJayamanne** [comment]
Apologies, the right issue is https://github.com/microsoft/vscode/issues/123024
