### ISSUE TITLE
With user snippet loosing ${}

### ISSUE THREAD

**Issue by Faq** [microsoft/vscode#123183]
```
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Version: 1.57.0-insider (system setup)
Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84
Date: 2021-05-06T05:16:25.564Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. create user snippet for JS (in javascript.json) with this content:
```
	"object for ... in loop": {
		"prefix": "obj",
		"body": [
			"for (let crewMember in spaceship.crew) {",
			"  console.log(`${crewMember}: ${spaceship.crew[crewMember].name}`);",
			"};"
		],
		"description": ""
	}
```

2. in javascript file write "obj" and run snippet. Result:

> console.log(`crewMember: ${spaceship.crew[crewMember].name}`);

In simple terms is lost first "${}", for compare:
```
console.log(`${crewMember}: ${spaceship.crew[crewMember].name}`); -- in json file
console.log(`crewMember: ${spaceship.crew[crewMember].name}`);    -- after using snippet
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
> In simple terms is lost first "${}",

Unsure what you mean? Do you want the output to contain `console.log(`${crewMember}:...`?

**Comment by Faq** [comment]
> 
> 
> > In simple terms is lost first "${}",
> 
> Unsure what you mean? Do you want the output to contain `console.log(${crewMember}:...`?

Yes, expected result is exact line what defined in json:

> console.log(`${crewMember}: ${spaceship.crew[crewMember].name}`);

**Comment by jrieken** [comment]
> Yes, expected result is exact line what defined in json:

Well... `${crewMember}` is the snippet syntax for referring to a variable called `crewMember`. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar for more details.

You need to use `\` to escape the `$` so that this isn't interpreted as variable

**Comment by Faq** [comment]
For snippet, the line should be:

> console.log(`\\${crewMember}: ${spaceship.crew[crewMember].name}`);
