### ISSUE TITLE
integrated terminal scrolls slowly when terminal output has long lines

### ISSUE THREAD

**Issue by hkiang01** [microsoft/vscode#123177]
Steps to reproduce:
1. Run the following script in an integrated terminal to generate some output:
```zsh
for i in {0..100}; do   echo "hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii $i"; done
```
2. Scroll and observe lag

I observed this in bash and zsh shells.

Some info on my installation:
  Version: Version: 1.56.0
  Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
  Date: 2021-05-04T21:58:14.757Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Linux x64 5.4.0-72-generic snap

**Comment by hkiang01** [comment]
Worth noting: I do not observe this in Insiders

Insiders installation:
  Version: 1.57.0-insider
  Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84
  Date: 2021-05-06T05:14:37.075Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Linux x64 5.4.0-72-generic

**Comment by Tyriar** [comment]
Do you have `terminal.integrated.gpuAcceleration` set in your settings? Can you share your settings.json file?

**Comment by hkiang01** [comment]
@Tyriar here is my settings.json file for my user. Note that I do not have `terminal.integrated.gpuAcceleration` set. My machine does not have a dedicated GPU

```json
{
  "autoDocstring.docstringFormat": "numpy",
  "autoDocstring.guessTypes": true,
  "editor.formatOnSave": true,
  "gitlens.mode.active": "review",
  "python.testing.pytestEnabled": true,
  "python.formatting.blackArgs": [
    "--line-length",
    "79"
  ],
  "python.formatting.provider": "black",
  "python.linting.flake8Enabled": true,
  "python.linting.pylintEnabled": false,
  "window.zoomLevel": -1,
  "workbench.editorAssociations": [
    {
      "viewType": "jupyter-notebook",
      "filenamePattern": "*.ipynb"
    }
  ],
  "sync.gist": "REDACTED",
}
```
