### ISSUE TITLE
Integrated terminal, line wrapping error

### ISSUE THREAD

**Issue by skiv71** [microsoft/vscode#123125]
Windows 10, WSL2 user, seeing this error all the time and it does my nut in.

You're typing away and for some reason, vscode / terminal decides to wrap the text output to the same line.

![image](https://user-images.githubusercontent.com/13932724/117302634-c258be80-ae73-11eb-846f-e21258d867ac.png)

**Comment by meganrogge** [comment]
Duplicate of #116174
