### ISSUE TITLE
Come up with plan to migrate dev containers off of terminal.integrated.shell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123157]
`terminal.integrated.shell.<platform>` is now deprecated, but dev containers rely on it to set the default shell. Ideally it wouldn't be needed at all, instead the `defaultProfile` would be tried and validated, and if it's not there we would fallback to `$SHELL` and then `/etc/passwd`

https://github.com/microsoft/vscode-dev-containers/issues/838

**Comment by Tyriar** [comment]
@Chuxel I just pushed in a lot of fixed to default profiles (https://github.com/microsoft/vscode/pull/123729). I think we'll still keep the shell setting to have priority for a while in VS Code (https://github.com/microsoft/vscode/issues/123171) but default profiles are ready to be moved to in dev containers, maybe after 1.57 goes out so this change lands?

I'd recommend just swapping the `terminal.integrated.shell.linux` out with the default profile and relying on the profile detection to pick up the profile's path. So if you want bash it would just be:

```
"terminal.integrated.defaultProfile.linux": "bash"
```

You can see what profiles get auto detected with the Select Default Profile command. The top ones are the profiles, the bottom ones are just detected but not "elevated to profile status" unless the user picks them, so they won't be pickable with the `defaultProfile` by default.

<img width="608" alt="Screen Shot 2021-05-13 at 7 48 28 AM" src="https://user-images.githubusercontent.com/2193314/118142841-9bdcdb00-b3bf-11eb-9252-345c1c3b7a77.png">

**Comment by Chuxel** [comment]
@Tyriar Sure we can do that.  I assume the fallback to `$SHELL` or `/etc/paswd` isn't in place quite yet so we can't remove the reference entirely?

**Comment by Tyriar** [comment]
That's there and should work, here's the current order:

- Automation shell if applicable
- shell/shellArgs if either are set
- defaultProfile
- "Fallback shell":  https://github.com/Microsoft/vscode/blob/1957af4f99b91dd95260e35f6fee4c842e99415e/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L219-L219
  - `$SHELL`
  - `userInfo().shell`
  - `sh`

**Comment by Chuxel** [comment]
@Tyriar Great! I assume this is just in insiders right now?

**Comment by Tyriar** [comment]
Have a plan for this in https://github.com/microsoft/vscode-dev-containers/pull/860, https://github.com/microsoft/vscode-dev-containers/issues/838
