### ISSUE TITLE
Attached debugging using Delve is not showing code at breakpoints

### ISSUE THREAD

**Issue by SGarno** [microsoft/vscode#123137]
I am attempting to debug a go application that is compiled and bundled prior to running the debugger.   This is done using the command line:

```guark build -rm && dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec dist\windows\Demo.exe```

Delve starts up just fine, VSCode connects to Delve and issues the proper API commands, but it doesn't display the code when the breakpoint is hit.   I can see from the Delve logs, that it is transmitting the breakpoint to VSCode, and VSCode is displaying the stacktrace, but it does not display the source code.

Attached is a Delve log and a screenshot of VSCode during a breakpoint

From the [log](https://github.com/microsoft/vscode/files/6435188/vscode-go-debug.txt) you can see:
* At [14:01:24.729 UTC] the brekpoints were verified
* At [14:01:50.444 UTC] the breakpoint was triggered
* At [14:01:50.471 UTC] Delve replied with location of breakpoint
* At [14:01:50.479 UTC] VSCode requested a stack trace

From the [screenshot](https://user-images.githubusercontent.com/8698262/117313109-d6d09300-ae42-11eb-8212-5ff3d9981523.png), you can see that the callstack is populated and showing where it is paused, however, the editor doesn't reflect the breakpoint in the code.   It remains where it was initiated at (in this case launch.json).

**Comment by isidorn** [comment]
Please file against the GO extension
