### ISSUE TITLE
Native Notebooks - General Survey Monkey Feedback

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123239]
Summarizing the common feedback: 

Performance Related: 
- Slow to load/open 
- Scrolling laggy/slow
- Scrolling speed in outputs not consistent (sometimes fast sometimes slow) 

UI Related: 
- Moving cells by drag and drop is hard to discover (asking for arrows to the left of cell to move them, saying only way to move cells is to copy and paste) 
- Collapse code is hard to discover (asking for it as feature, say it's missing)
- Toggle line numbers is hard to discover (asking for it as feature, say it's missing) 
- Table of Contents is hard to discover (asking for it as feature, say it's missing) 
- UI still too different from Jupyter ( saying UI is complex, complicated, not simple like jupyter, and explicit asks to copy jupyter layout, move kernel picker to where it is in jupyter, can it be more like jupyter lab) 

Critical Missing Features:
- Latex
- Debugging

**Comment by rebornix** [comment]
> Toggle line numbers is hard to discover (asking for it as feature, say it's missing)

may I ask how would they find this feature in Jupyter?

> Debugging

Can you elaborate a bit on this? What debugging feature they are referring to?

**Comment by claudiaregio** [comment]
@rebornix In Jupyter they have the 'L' shortcut and 'Shift + L' when in command mode. 
I have filed an issue here for Jupyter to support the shortcut: https://github.com/microsoft/vscode-jupyter/issues/5797
This should increase the discoverability, but just wanted to pass the info along in case vs code wanted to surface it in another way since this is currently being surfaced in the overflow menus at both the cell and global toolbar level.

**Comment by rebornix** [comment]
> I have filed an issue here for Jupyter to support the shortcut: microsoft/vscode-jupyter#5797
> This should increase the discoverability, but just wanted to pass the info along in case vs code wanted to surface it in another way since this is currently being surfaced in the overflow menus at both the cell and global toolbar level.

I think binding to the `L` solves the problem for Jupyter users by a lot. Another potential place for this is maybe an application-level notebook menu item.
