### ISSUE TITLE
Markdown links/paths escaping

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#123228]
For the filename accepted on Windows : ``1aA`~!@#$%^&()-_=+{},. .md`` ;

This ``1aA`~!@%23$%25%5E&()-_=+{},.%20.md`` ([Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding)) doesn't work in Preview . It works on github and other .

**Comment by irvnriir** [comment]
Also, would be good to make the Preview handle links to folders, for example open them with executable defined in settings .

I see no point in downloading another program to use it as .md viewer, adding all features to VSCode's Preview is much more logical .

**Comment by mjbvz** [comment]
@irvnriir Please open a separate issue for that feature request
