### ISSUE TITLE
vscode终端输入npm i -g @vue/cli报错，显示无法识别@

### ISSUE THREAD

**Issue by boilingEternalPoetry** [microsoft/vscode#123233]
![image](https://user-images.githubusercontent.com/50012321/117395807-4457ee80-af2b-11eb-8727-d5c57a7b6d38.png)

**Comment by infinnie** [comment]
Translation:

Command `npm i -g @vue/cli` causes an error in VS Code’s integrated terminal.

**Comment by infinnie** [comment]
Due to VS Code using PowerShell instead of Command Prompt, use `npm i -g "@vue/cli"` instead. Note that the character `@` is quoted.

**Comment by aravindvnair99** [comment]
@infinnie Set your default terminal as CMD.

Possible duplicate of / related to https://github.com/microsoft/vscode/issues/123323

**Comment by boilingEternalPoetry** [comment]
> 由于VS Code使用PowerShell而不是Command Prompt，因此请`npm i -g "@vue/cli"`改为使用。请注意该字符`@`被引号。

谢谢，按照你的这种写法，我能够正确执行这个命令了
