### ISSUE TITLE
jsonFormatter:applyEdit() could format values nicely

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12323]
See comment from @isidorn in https://github.com/Microsoft/vscode/issues/1396#issuecomment-248294777 where we see that filling in a complex object to a settings file does not format it but puts it on a single line.

I have seen this before already when storing a more complex object to settings (e.g. file associations).

**Comment by aeschli** [comment]
duplicate of #13436

**Comment by bpasero** [comment]
@aeschli thanks for fixing this !
