### ISSUE TITLE
Settings: Provide command to open settings editor on the side

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123282]
Maybe it already exists 🤔

**Comment by joaomoreno** [comment]
> If you could set a keybinding with an arg to open it to the side, would that help, or do you want it in the command palette?

Yeah that could do it!

**Comment by roblourens** [comment]
Implemented this in https://github.com/microsoft/vscode/commit/14fdf3012a8ffd802e1b820f425a14d3924800c1 and https://github.com/microsoft/vscode/commit/28f471e2dd1bab8edf164691ae916e5818800501 for all the settings open commands

**Comment by bpasero** [comment]
Didn't work for `workbench.action.openSettingsJson` for me though.

**Comment by roblourens** [comment]
Fixed that, thanks
