### ISSUE TITLE
Custom editor input labels debt

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123247]
The `CustomEditorInput` should appear like any other file editor or notebook editor because it is mainly a result of opening a file resource. 

To be able to reuse more code I now added a new type [`AbstractResourceEditorInput`](https://github.com/microsoft/vscode/blob/a2ddfc3aef5e554535fe308f67a585df1cd2abc0/src/vs/workbench/common/editor/resourceEditorInput.ts#L16-L16) that is used by all files, notebooks and untitled editors for consistent label handling.

Given the inheritance of `CustomEditoInput`, I was not able to adopt this type for it unfortunately. 

This issue is to document this debt and report some issues:
* ideally `CustomEditorInput` could extend `AbstractResourceEditorInput` somehow
  * there is a lot of code duplication for labels that could be reused (`getName`, `getDescription`, `getTitle`)
* if not, there are issues in `CustomEditorInput` that are not addressed
  * the `ILabelService` is properly used, but the labels are not updating when the formatters change ([here](https://github.com/microsoft/vscode/blob/a2ddfc3aef5e554535fe308f67a585df1cd2abc0/src/vs/workbench/common/editor/resourceEditorInput.ts#L37-L37) is how the abstract resource editor input does it)
  * the label is properly decorated for `readonly`, but I am not sure if this state can change dynamically or not ([here](https://github.com/microsoft/vscode/blob/a2ddfc3aef5e554535fe308f67a585df1cd2abc0/src/vs/workbench/common/editor/resourceEditorInput.ts#L38-L39) is how the abstract resource editor input does it by listening on provider changes)

**Comment by mjbvz** [comment]
I don't think I can easily change the inheritance structure here. It does seems like the other points have been addressed  however
