### ISSUE TITLE
Disable annoying root notification permanently

### ISSUE THREAD

**Issue by icebluey** [microsoft/vscode#123245]
![123](https://user-images.githubusercontent.com/25545175/117439051-5a03ee80-af00-11eb-9294-6520ac38e2bc.png)

VS Code Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z

"It is not recommended to run Code as root user." 
This notification pops up every time I open vs code.
How to disable this annoying notification permanently?

**Comment by bpasero** [comment]
By not running as `root` user, which is not recommended.

**Comment by icebluey** [comment]
I know the recommendation, but I run vscode as root user on purpose.
I do not want it remind me  again and again, that is annoying.
