### ISSUE TITLE
Notebook markdown cells being re-rendered on resize

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#123215]
Issue Type: <b>Bug</b>

1. Open notebook with markdown cells
1. Resize the editor window

**Bug**
The markdown cells are continiously re-rendered

You can verify this by looking in the network tab and seeing `katex.css` being re-requested 

VS Code version: Code - Insiders 1.57.0-insider (Universal) (fe23c2041f848d6c2f6bd27875112a37bcc82f84, 2021-05-06T05:50:00.296Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
test-ext|bie|0.0.1
vscode-eslint|dba|2.1.20
typescript-notebook|don|1.2.0
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
codespaces|Git|0.10.1
vscode-pull-request-github-insiders|Git|2021.5.7743
vscode-drawio|hed|1.4.0
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.17.0
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.4.7
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.5.0
jupyter|ms-|2021.6.816326582
remote-containers|ms-|0.177.0
remote-ssh-edit-nightly|ms-|2021.5.6660
remote-ssh-nightly|ms-|2021.5.6660
azure-account|ms-|0.9.8
hexeditor|ms-|1.6.0
js-debug-nightly|ms-|2021.5.317
vscode-github-issue-notebooks|ms-|0.0.89
debugger-for-chrome|msj|4.12.12
java|red|0.79.1
code-spell-checker|str|1.10.2
luna-paint|Tyr|0.5.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782

```

</details>

**Comment by mjbvz** [comment]
This seems like a recent regression

**Comment by connor4312** [comment]
🤦
