### ISSUE TITLE
Broke extension with your update

### ISSUE THREAD

**Issue by pledbetter-cvet** [microsoft/vscode#123292]
Your version 1.56 broke the Salesforce Query Editor extension.

**Comment by JacksonKearl** [comment]
Could you provide more information on what exactly has broken?

**Comment by nrayburn-tech** [comment]
Duplicate of #123281.

**Comment by AllanOricil** [comment]
@JacksonKearl  Vscode downloads the app.js from the cdn, it runs, but the app is not mounting on the iframe. And there are no error messages anywhere, which makes it impossible to debug. I shared the source code with @mjbvz and if you want to help, I can also share with you.

**Comment by JacksonKearl** [comment]
@mjbvz can handle this best
