### ISSUE TITLE
Dragging terminal tabs sash affects terminal content

### ISSUE THREAD

**Issue by g-plane** [microsoft/vscode#123221]
- VS Code Version: 1.56.0
- OS Version: Linux 5.12

Steps to Reproduce:

1. Enable terminal tabs by setting `"terminal.integrated.tabs.enabled"` to `true`.
2. Open terminal, then drag terminal tabs sash like this:

https://user-images.githubusercontent.com/17216317/117385151-12d52800-af17-11eb-901f-7b8a8657086c.mp4

Note that I'm using Zsh with [powerlevel10k](https://github.com/romkatv/powerlevel10k).

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
This is a bug we're aware of that happens when the terminal's width gets narrow and the terminal header/title gets duplicated.
