### ISSUE TITLE
Webview not working after upgrade to v1.56.0

### ISSUE THREAD

**Issue by nenadmaricic** [microsoft/vscode#123284]
- VS Code Version: 1.56.0
- OS Version: Windows 10

We are developing an extension that uses Angular 11 for generating webviews content. After upgrading VSC to 1.56, webviews stopped working.

Steps to Reproduce:

1. Open webview
2. Empty panel presented
3. Toggle developer tools, open Network tab
4. Application chunk is in the pending state and timeouts after 5 mins with error :

```
Uncaught (in promise): ChunkLoadError: Loading chunk 14 failed.
(timeout: https://24c27a8f-82d2-4d99-93c1-498285d81a5d.vscode-webview-test.com/vscode-resource/file/c%3A/Users/xxx/.vscode/extensions/xxx-extension/out/webviews/dist/14.js)
ChunkLoadError: Loading chunk 14 failed.
(timeout: https://24c27a8f-82d2-4d99-93c1-498285d81a5d.vscode-webview-test.com/vscode-resource/file/c%3A/Users/xxx/.vscode/extensions/xxx-extension/out/webviews/dist/14.js)
```
5. Subsequent reloads of the webview generates random chunks pending/timeouts

Loading of the webview VSC 1.55.2 (success):
![webview-vscode-1_55_2](https://user-images.githubusercontent.com/46957423/117454274-3fecff00-af46-11eb-95ea-2aaef7f1c73e.PNG)

Loading of the webview VSC 1.56.0 (failed):
![webview-vscode-1_56_0](https://user-images.githubusercontent.com/46957423/117454285-43808600-af46-11eb-826a-4c13246b8602.PNG)

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
Please share a minimal example extension that demonstrates the issue
