### ISSUE TITLE
Home - Go to Beginning of Line (real)

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#12326]
- VSCode Version: 1.5.2
- OS Version: Win10

Steps to Reproduce:

1. put cursor in line, which starting with tabs or spaces
2. press "Home"-key

Exp.: cursor in start of the line, as wrote in help ( https://code.visualstudio.com/docs/customization/keybindings ) - "Go to Beginning of Line"

Act.: cursor before first non space character.

Can you add setting for "Home" key to really "Go to Beginning of Line"?

thank you.

**Comment by Bill-Stewart** [comment]
See #12287 - would such an option work for you as well?

**Comment by SailorMax** [comment]
Yes :)

**Comment by Bill-Stewart** [comment]
I wrote an extension you can use in the meantime:

[https://marketplace.visualstudio.com/items?itemName=BillStewart.extended-cursormove](https://marketplace.visualstudio.com/items?itemName=BillStewart.extended-cursormove)

**Comment by SailorMax** [comment]
I found it already :) Thank you!
But hope on built-in solution ;)

**Comment by Bill-Stewart** [comment]
Agree, built-in option would be good.

**Comment by chrmarti** [comment]
Tracking as #12287 then, thanks.

**Comment by Bill-Stewart** [comment]
Thx @chrmarti
