### ISSUE TITLE
stdio.h header not found

### ISSUE THREAD

**Issue by AbhiprayaSinha** [microsoft/vscode#123264]
Issue Type: <b>Bug</b>

when i write code in C . while writing the include statement "#include<stdio.h>" it is showing that Stdio.h header not found ,clang pp file not found. what should i do?

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.14GB free)|
|Process Argv|--crash-reporter-id e532ea98-b61a-4ef5-a779-ab1e253bbbbc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.2.2
c-cpp-compile-run|dan|1.0.14
dart-code|Dar|3.22.0
code-runner|for|0.11.3
vscode-mysql|for|0.4.0
c-cpp-runner|fra|0.11.0
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.26.0
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.5
cpptask|kay|0.0.1
ccpp-extension-pack|Leo|1.1.0
vscode-clangd|llv|0.1.11
clang-format|mjo|1.10.0
csharp|ms-|1.23.11
mssql|ms-|1.10.1
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
java|red|0.79.1
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscode-java-debug|vsc|0.33.1
vim|vsc|1.20.2
vscode-ruby|win|0.28.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by JacksonKearl** [comment]
\extC
