### ISSUE TITLE
Search editor: label consistency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123250]
Search editors when saved to disk look like this (right hand side):

![image](https://user-images.githubusercontent.com/900690/117411444-d81dc080-af13-11eb-8570-e4dd149434c9.png)

As you can see on the left, files report their folder in the description part (`getDescription`), search editors currently do not. There is also a `getTitle` method mainly used to make sure a good label appears in the window title for the active editor.

To reuse the code for editor inputs that reflect a file on disk, I recently added [`AbstractResourceEditorInput`](https://github.com/microsoft/vscode/blob/a2ddfc3aef5e554535fe308f67a585df1cd2abc0/src/vs/workbench/common/editor/resourceEditorInput.ts#L16-L16) and think that search editors could extend from this type to get the same label treatment as files (and notebooks).

Besides the labels, there is also decoration treatment (readonly, orphaned = deleted states).

**Comment by eleanorjboyd** [comment]
@bpasero any idea if this still exists?
