### ISSUE TITLE
better api for command "explorer.download" 

### ISSUE THREAD

**Issue by mateuszkitlas** [microsoft/vscode#123260]
I'm making my own extension for vscode and I'm trying to make a feature that allows user to download a generated file from vscode. I was able to emulate this by the following code:
```
  await commands.executeCommand("revealInExplorer", Uri.file(fspath));
  await commands.executeCommand("explorer.download");
```
But it's hacky and not sufficient for me. As I've said - my files are generated and tend to be big. I want to enable users to download them directly. What I'm hoping for is:
```
  await commands.executeCommand("download", uri);
```

I'm using code-server, so this particular feature would come in very handy to me.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
