### ISSUE TITLE
Git: Open File doesn't work when the diff editor is opened for a staged file (because readonly?)

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12320]
Make a change in a file. Go to the Git pane, click the file to open the diff editor. Open the command palette and run "Git: Open File". This works.

Stage the file and open the diff editor. Try to run "Git: Open File" again. Nothing happens.

Maybe the difference is that in the second case, the file is readonly?

**Comment by chrmarti** [comment]
The "Switch to Editor View" toolbar action works as expected. Appears to be a problem with the command.

**Comment by joaomoreno** [comment]
Fixed.
