### ISSUE TITLE
Sub menus by extensions in explorer context menus,item menus

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#12321]
![jmhsx0hmk4ogh 5i 5u1wyr](https://cloud.githubusercontent.com/assets/3353702/18671439/a8c538bc-7f76-11e6-8e40-6f7d377f2bd0.png)
1.I want to have explorer context menus like this 。how to do？I don't know how to configure the json file

**Comment by chrmarti** [comment]
Tracked as #9827
