### ISSUE TITLE
You don't have an extension for debugging PHP. Should we find a PHP extension in the Marketplace?

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#123271]
After installing the PHP Debug extension, when I try to debug a php script this popup keeps appearing:

![image](https://user-images.githubusercontent.com/29214635/117432922-2ee2c480-af2b-11eb-9e16-ab8c698dbb00.png)

> You don't have an extension for debugging PHP. Should we find a PHP extension in the Marketplace?

- VS Code Version: 1.56
- OS Version: Windows 10

Steps to Reproduce:
1. Install PHP Debug extension
2. Open a PHP file
3. Press F5 to debug it.

Does this issue occur when all extensions are disabled?: Yes (except the PHP Debug extension)

In the VSCode version 1.55 this PHP extension works fine, but in VSCode 1.56 it doesn't.

**Comment by isidorn** [comment]
Dup of https://github.com/xdebug/vscode-php-debug/issues/568
