### ISSUE TITLE
Jupyter notebooks: "find in files" result doesn't scroll to the found line neither highlight the found string

### ISSUE THREAD

**Issue by bolinocroustibat** [microsoft/vscode#123230]
- VS Code Version: Version: 1.57.0-insider - Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84

- OS Version: MacOS 11.3

Steps to Reproduce:

1. Open a project with some .ipynb notebook files in it
2. Start a "find in files" search (cmd+shift+F) and type a string that exists in one .ipynb notebook file
3. Open one of the .ipynb notebook file found
4. File won't scroll to the found string neither will highlight it like it would do in other file types

<img width="670" alt="Screen Shot 2021-05-07 at 12 23 24" src="https://user-images.githubusercontent.com/4353767/117394371-fe9e2480-af30-11eb-99ff-6af5c94270c1.png">

**Comment by bolinocroustibat** [comment]
Could be related: when starting a simple search (cmd+F) in a file, it doesn't highlight neither show the first result number

<img width="599" alt="Screen Shot 2021-05-07 at 12 34 38" src="https://user-images.githubusercontent.com/4353767/117394316-e4644680-af30-11eb-886e-77bcbaf53d04.png">

Let me know if I should create a separate ticket about that.

**Comment by tanhakabir** [comment]
Hey @bolinocroustibat! Thanks for submitting this request! We're going through issue cleaning this month and looking at what issues to bring up again as higher priority. I also believe this is much needed functionality so I'll bring it up as a candidate to focus on after issue grooming!

**Comment by jackos** [comment]
@tanhakabir Is this currently being worked on? It's an important feature for my extension `rustnote` which uses the notebook API, I'll take a crack at this if nobody is currently working on it.

**Comment by roblourens** [comment]
We actually improved this, and have more notebook-specific search improvements on the way
