### ISSUE TITLE
Settings.json, so far no help on this.  First 2 lines changed and I do not know what they were

### ISSUE THREAD

**Issue by William1947** [microsoft/vscode#123222]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.settings.json reply can not sync making it impossible to use.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by William1947** [comment]
i have tried to ask for help on this before, I really like Visual Studio Code but with the settings.json file being not valid I can no longer use this system.

**Comment by JacksonKearl** [comment]
Could you share your settings.json file to help us diagnose the problem?

**Comment by William1947** [comment]
{"setting1": 'value',"setting2": "another value"}"java.debug.settings.jdwp.limitOfVariablesPerJdwpRequest": 100"files.autoSave": "afterDelay","editor.wordWrap": "on","editor.codeActionsOnSave": null,"workbench.editor.decorations.colors": true,"window.autoDetectHighContrast": false,"json.trace.server": "messages","editor.suggestSelection": "first","vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue","workbench.editorAssociations": [    {        "viewType": "jupyter.notebook.ipynb",        "filenamePattern": "*.ipynb"    }],"tabnine.experimentalAutoImports": true,"todo-tree.tree.showScanModeButton": false,"kite.showWelcomeNotificationOnStartup": false,"gitlens.advanced.messages": {    "suppressGitMissingWarning": true},"editor.rulers": [    120],"workbench.colorTheme": "Shades of Purple",
This is part of it, the problem is at the top 2 or 3 lines, thank you for your help.Ronald Massey
    On Thursday, May 6, 2021, 06:50:06 PM PDT, Jackson Kearl ***@***.***> wrote:  
 
 


Could you share your settings.json file to help us diagnose the problem?

**Comment by William1947** [comment]
{"setting1": 'value',
"setting2": "another value"
}
"java.debug.settings.jdwp.limitOfVariablesPerJdwpRequest": 100
"files.autoSave": "afterDelay",
"editor.wordWrap": "on",
"editor.codeActionsOnSave": null,
"workbench.editor.decorations.colors": true,
"window.autoDetectHighContrast": false,
"json.trace.server": "messages",
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
"workbench.editorAssociations": [
    {
        "viewType": "jupyter.notebook.ipynb",
        "filenamePattern": "*.ipynb"
    }
],
"tabnine.experimentalAutoImports": true,
"todo-tree.tree.showScanModeButton": false,
"kite.showWelcomeNotificationOnStartup": false,
"gitlens.advanced.messages": {
    "suppressGitMissingWarning": true
},
"editor.rulers": [
    120
],
"workbench.colorTheme": "Shades of Purple",
This is part of it, I hope it helps.  Thank you for your help with this.
Ronald Massey

________________________________

**Comment by gjsjohnmurray** [comment]
There seems to be a comma missing after the first occurrence of `100`

**Comment by William1947** [comment]
Thank you John, I put the comma in but still no clue what the first two lines are to be. I know they changed and someone else told me how they are set but don't know what the value's are.  This is giving me more gray hair.  I really like Visual Studio Code but cannot use it. Right now I be using PyCharm, not as good as Visual Studio Code but it works. If you think of something else please let my know.

Thank you for your help.
Ronald Massey


________________________________

**Comment by roblourens** [comment]
Hi @William1947, I'm not sure how it ended up like this, maybe a bad copy/paste? But you just need key/value pairs inside {}. Here's an example

```json
{
"java.debug.settings.jdwp.limitOfVariablesPerJdwpRequest": 100
"files.autoSave": "afterDelay",
"editor.wordWrap": "on",
"editor.codeActionsOnSave": null,
"workbench.editor.decorations.colors": true,
"window.autoDetectHighContrast": false,
"json.trace.server": "messages",
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
"workbench.editorAssociations": [
    {
        "viewType": "jupyter.notebook.ipynb",
        "filenamePattern": "*.ipynb"
    }
],
"tabnine.experimentalAutoImports": true,
"todo-tree.tree.showScanModeButton": false,
"kite.showWelcomeNotificationOnStartup": false,
"gitlens.advanced.messages": {
    "suppressGitMissingWarning": true
},
"editor.rulers": [
    120
],
"workbench.colorTheme": "Shades of Purple",
// ... more settings ...
// Then the file should end with }
```

**Comment by roblourens** [comment]
I'm happy to help. Let me know if you can't get it figured out.

**Comment by William1947** [comment]
I sure will, thanks again for your help.
Ronald Massey

________________________________
