### ISSUE TITLE
Jupyter notebook: Terminal tab disappears when clicking on "Jupyter variables" in the terminal pane tabs list

### ISSUE THREAD

**Issue by bolinocroustibat** [microsoft/vscode#123227]
- VS Code Version: Version: 1.57.0-insider - Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84

- OS Version: MacOS 11.3

Steps to Reproduce:

1. Open a Jupyter notebook .ipynb and launch the kernel to execute it
2. Show and launch a terminal
3. Click on the "Jupyter variables" tab of the terminal pane
4. The terminal tab disappears, can't come back to the terminal unless you close the pane/terminal and launch a new one

**Comment by sbatten** [comment]
Please right-click the panel tab bar and verify that `Terminal` is checked.
![image](https://user-images.githubusercontent.com/6561887/117491778-7bc39c80-af25-11eb-8a65-d00f8da82d0a.png)

**Comment by bolinocroustibat** [comment]
Indeed it was that! Sorry about the false issue and thank you for the answer. Can be closed.
