### ISSUE TITLE
Request: Project Templates

### ISSUE THREAD

**Issue by jay-bricksoft** [Microsoft/vscode#12322]
It would be a huge improvement if vscode had the ability of templating projects.

As there are already a lot of Variables available, it should not be that hard to create projects out of templates.

---

example structure of a template: 

/
- project.json
- readme.md
- content
  |- files of project to be populated

---

project templates could then be packed as zip or tar packages and also get cloned from repositories or something like that.

**Comment by rozzzly** [comment]
I'm pretty sure this could be achieved via the extension api. But if vscode were to provide official support, I'd suggest configurable file templates as well.

**Comment by jay-bricksoft** [comment]
yes i saw that. but it feels kind of uncomfortly to create a template _by command_.
this is one of the features i miss from vs studio.

maybe it would start with an extension of file open dialog / folder open dialog to instad provide an assistant which guides through project creation. then a template option would fit in well and round up such purpose.

**Comment by be5invis** [comment]
And the template should be able to provide compilation options, especially for C/C++.

**Comment by jay-bricksoft** [comment]
Yes, that is one of my intentions of a templating system for VSC.

**Comment by MathiasMagnus** [comment]
Providing compilation options for C++ may get very tricky, if the template wishes to address portability. In my recently closed feature request, I was aiming for templating CMake projects with and the ability to pick many capabilities for the new project from a GUI, similar to the Windows Template Studio. Providing solely files for a template is not enough, but there should be an ability to run a script that composes project stubs into something that makes sense as a whole; think of it as concatenating makefiles (or CMake scripts) for instance, but these may become more complex.

The way I imagine it, is that VS Code provides a window, which the extensions are free to populate as they like. Drop down menus, buttons, whatever makes sense in their context. This window once acknowledged by the user (click OK) creates a .json that contains the selections made in the project 'wizard' which in turn is handed to an arbitrary script, again hosted by the extension that actually does the heavy lifting of assembling the project template by whatever means. (Downloading, assembling from local resources, etc.)
