### ISSUE TITLE
SFTP extension keeps reporting 'no such file' on vscode 1.56

### ISSUE THREAD

**Issue by mpalencia** [microsoft/vscode#123249]
- VS Code Version: 1.56
- OS Version: Windows 10

Steps to Reproduce:

1. Update VScode to 1.56
2. Install SFTP by liximomo
3. setip up and make sure upload when ctrl+s is On
4. try to upload your code to the server.. it always display an error, but on vscode 1.55 version it works smoothly

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gjsjohnmurray** [comment]
Have you reported the issue to the extension developer?

**Comment by gjsjohnmurray** [comment]
Also #123240

**Comment by n3svarbu** [comment]
VSCode Node version was bumped and supposedly this issue appered because of a regression on streams in Node v14, that's been fixed in v15

**Comment by INTMIN** [comment]
I've had this problem, too

**Comment by INTMIN** [comment]
I looked at the most recent changes to this warehouse two years ago.... @mpalencia @gjsjohnmurray @n3svarbu

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/122325

`1.56` updated the node version from `12.18.3` to `14.16.0`, please ensure the extension works with this node version.
