### ISSUE TITLE
Emmet support for PHP

### ISSUE THREAD

**Issue by heckctor** [Microsoft/vscode#12325]
- VSCode Version: 1.5.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

I will like to emmet works in php! ;)

**Comment by gregvanl** [comment]
Will the emmet.syntaxProfiles setting help you? You can associate Emmet profiles like "html" and "css" with a language identifier.

{
    "emmet.syntaxProfiles": {
        "php": "html"
     }
}

**Comment by mrmlnc** [comment]
Emmet should work with PHP without settings in VS Code above 1.5.0 version. May be you have `file.associations` or `emmet.exclude`? You can provide your settings?

**Comment by heckctor** [comment]
Thanks !! :D @gregvanl

**Comment by chrmarti** [comment]
@heckctor Does this solve the issue for you?

**Comment by heckctor** [comment]
> @chrmarti Yes, thanks!

**Comment by ramya-rao-a** [comment]
From VS Code 1.15 onwards, no setting is needed to get Emmet to work in php files.

**Comment by a-eid** [comment]
@ramya-rao-a  its not working for me thou , I'm on 1.15 ( ubuntu ) ; 
tegs expand but not classes or ids .. etc

**Comment by a-eid** [comment]
@gregvanl  where do I add that ?

**Comment by ramya-rao-a** [comment]
@a-eid I think the problem is that emmet is not getting activated yet...

Can you open an html file and then go back to your php file and try again?

**Comment by a-eid** [comment]
@ramya-rao-a  `  "php.suggest.basic": false ` resolve the problem.

**Comment by a-eid** [comment]
@ramya-rao-a  

whenever I try type something (.class for example) that contain an operator (minus sign)  (col-md-8) or a number it doesn't trigger emmet . the php drop down suggestion appears 
![](https://i.imgur.com/tY6p8Vr.png) 
how to fix that ?

**Comment by jens1o** [comment]
That's a suggestion from the php-language-server by @felixfbecker And there's no way to get rid of that suggestion, yet.

**Comment by ramya-rao-a** [comment]
@a-eid

Turns out the issue is not just with the `-` sign. Any emmet abbreviation with class operator doesnt seem to show up in the suggestions. I have logged #32423 for it.

I also noticed that the ordering of emmet suggestions is different in php. Logged #32424 for that

**Comment by andremacola** [comment]
@a-eid if you put a . at the final it works.

`.col-md-8. (tab)`

**Comment by mettaworldjon** [comment]
Inside of vscode it is ".." instead of a single "."

**Comment by rodrigocarrillo94** [comment]
Hi, please translate this message to English Jeje

Al actualizar Visual Studio Code no podía auto-completar etiquetas HTML en archivos .php (en Laravel, archivos .php - Blade), para solucionar esto cambie lo siguiente:

"emmet.triggerExpansionOnTab": true (antes estaba en "false")
