### ISSUE TITLE
SCM actions not aware of selected repository

### ISSUE THREAD

**Issue by danieltodor** [microsoft/vscode#123210]
- VS Code Version: since 1.54-> (also in 1.56)
- OS Version: Archlinux, Ubuntu 20.04

Steps to Reproduce:

1. Activate the Source Control Repositories in the menu
![image](https://user-images.githubusercontent.com/42888821/117370099-30c66c80-aec6-11eb-883d-4cac57e73b09.png)

2. You need to have multiple repositories. Select a repository, and click on push, pull, from the Source Control section.
![image](https://user-images.githubusercontent.com/42888821/117371154-b1d23380-aec7-11eb-8180-44deab42cc37.png)

3. Instead of doing the push/pull on the selected repo, vscode will show a popup to select the repository. It is not aware of the selection since version 1.54
![image](https://user-images.githubusercontent.com/42888821/117371426-2a38f480-aec8-11eb-82bd-26275c57b808.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Yes, 💯 , I get this often but feel it is a bit random, maybe only on the first time?

**Comment by danieltodor** [comment]
For me it is consistent when i select an action from the Source Control section.

**Comment by axtschmied** [comment]
This always happens for me as well. It's not blocking my work, but it can get a bit annoying, when performing lots of Git operations.

**Comment by lszomoru** [comment]
@danieltodor, @bpasero are you still able to reproduce this issue? Tried it in the latest VS Insiders and I was not able to reproduce. Thanks!

**Comment by bpasero** [comment]
No, I think not lately at least.

**Comment by lszomoru** [comment]
Thanks @bpasero. Closing this issue for now, and please feel free to reopen if it reoccurs. Thanks!
