### ISSUE TITLE
Run file button in toolbar resembles tab slider tool #UI

### ISSUE THREAD

**Issue by dmcbride64** [microsoft/vscode#123216]
Issue Type: <b>Bug</b>

1.  Open many files
2. Look for one file in the row of tabs.  Maybe it's hidden to the right of the toolbar.
3. Click green arrow button that looks like a tab slider button, seen on other applications, that slides tabs to the left and brings hidden tabs into view.
4.  In actuality the tool launches a script that you didn't want to launch.
5. Spend time cleaning up the results of the inadvertent script launch.

I've now done this twice.

Suggest that you alter or move the "run file in terminal" button so that it's less likely to be mistaken for a "tab slider" button.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 02e12d1d-edfb-4535-b6e4-145f321323f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.24.2
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
text-power-tools|qcz|1.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

![Screen Shot 2021-05-06 at 4 53 56 PM](https://user-images.githubusercontent.com/11862891/117379762-0ad0a600-ae8d-11eb-8404-638267799ad8.png)

**Comment by JacksonKearl** [comment]
\extPython

**Comment by dmcbride64** [comment]
vscode-python reports that the placement of the button is controlled by a vscode API. 

So, you told me to report the issue to vscode-python, which I did, and they told me that it's a vscode issue.

**Comment by JacksonKearl** [comment]
The appearance is controlled by the Python extension.

**Comment by brettcannon** [comment]
Sorry, misunderstanding on my part; I misread what @dmcbride64 was commenting on about the arrow, thinking it was overflow behaviour, not the fact that it's an arrow itself.
