### ISSUE TITLE
Cannot choose Git Bash when installed via scoop

### ISSUE THREAD

**Issue by fritzmg** [microsoft/vscode#123205]
- VS Code Version: 1.56.0
- OS Version: Windows 10 Pro x64 20H2

Steps to Reproduce:

1. Install `git` via `scoop` with `scoop install git-with-openssh`.
2. Launch VSCode and open the terminal.
3. Choose the drop down next to the ➕.

The `Git Bash` option will not be there. 

Does this issue occur when all extensions are disabled?: Yes

How does VSCode check the availability of Git Bash? Can it be configured somehow?

When I configure my own profile (see also https://code.visualstudio.com/docs/editor/integrated-terminal)

```json
    "terminal.integrated.profiles.windows": {
        "Git Bash": {
            "path": "C:\\Users\\foobar\\scoop\\apps\\git-with-openssh\\current\\bin\\bash.exe"
        }
    },
```

it works - however, then I loose the option to choose the `PowerShell` profile for instance (apparently that setting will override all other profiles?).

**Comment by meganrogge** [comment]
Glad to see you figured out how to configure the profile. 

Not sure what you mean regarding losing the option to choose the powershell profile. You can add it to the profiles as another entry.

For example:

```
    "terminal.integrated.profiles.windows": {
        "Git Bash": {
            "path": "C:\\Users\\foobar\\scoop\\apps\\git-with-openssh\\current\\bin\\bash.exe"
        },
        "PowerShell": {
              "source": "PowerShell"
         }
    },
```

**Comment by fritzmg** [comment]
Ah ok, well I assumes that may be the custom setting should be merged with the default ones? I find it pretty odd to have to define all the default ones manually gain with

```json
        "PowerShell": {
              "source": "PowerShell"
         }
```

etc. Besides, how do I find out which default ones there actually are, so that I can re-add them again?

**Comment by fritzmg** [comment]
Cool :). I noticed another issue. With my current setup of manually defining the `Git Bash` profile, VSCode still always automatically starts with the `PowerShell`, even though I already set the `Git Bash` profile as my default one.

However, this only happens, if the terminal is open by default i.e. if it was open the last time I closed VSCode. If the terminal is not open by default and I open it after booting up VSCode, the `Git Bash` will be used by default as expected.

**Comment by fritzmg** [comment]
> We will auto-detect `"C:\\Users\\User\\scoop\\apps\\git-with-openssh\\current\\bin\\bash.exe"` going forward.

Btw. keep in mind that the path could also be 

```
C:\ProgramData\scoop\apps\git-with-openssh\current\bin\bash.exe
```

if it was installed with `--global`.

**Comment by fritzmg** [comment]
@Tyriar thx :). I should have mentioned though, that the following paths are also possible:

```TypeScript
`${process.env['UserProfile']}\\scoop\\apps\\git\\current\\bin\\bash.exe`,
`${process.env['AllUsersProfile']}\\scoop\\apps\\git\\current\\bin\\bash.exe`
```

There are two scoop packages for Git: `git` and `git-with-openssh`. The latter comes with `openssh`, which can also be installed separately (though this has some issues at the moment, so only `git-with-openssh` works currently).

**Comment by Tyriar** [comment]
@fritzmg thanks for the info

> though this has some issues at the moment, so only git-with-openssh works currently

What kind of issues? Wouldn't want to auto detect it if it's not going to work.

**Comment by Tyriar** [comment]
We could search the path for `bash`, but if it's not in a path we know of then we wouldn't know what it is exactly. For example bash.exe is used by wsl on older versions of Windows 10 and I'm sure there are other bash.exe executables available on Windows. The current mindset is we only expose the auto detected profiles for very high confidence matches since the user always has the option of manually configuring them

**Comment by fritzmg** [comment]
I see, makes sense.

Will the issue I mentioned [here](https://github.com/microsoft/vscode/issues/123205#issuecomment-835364349) also be fixed in case I still have to / want to manually configure a terminal profile?

**Comment by Tyriar** [comment]
@fritzmg yep we're definitely fixing that, has been reported a bunch: https://github.com/microsoft/vscode/issues/123188
