### ISSUE TITLE
Debug: Can't find `extensionHost` in WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123255]
I just press F5 in an extension folder and I get this, in WSL:

![image](https://user-images.githubusercontent.com/22350/117417083-da116080-aece-11eb-97c2-7b70172ffbe6.png)

**Comment by isidorn** [comment]
Might this be connected to the changes to the shared environment done by @bpasero

**Comment by bpasero** [comment]
If so, then debug forgot an adoption?

**Comment by weinand** [comment]
@isidorn what do you mean by "shared environment"?

**Comment by isidorn** [comment]
@weinand Ben mentioned in the general chat that the did some changes to the shared environment that might effect tasks and debugging. I do not know more.

**Comment by weinand** [comment]
@isidorn I do not see how Ben's "shell environment" changes (which we have adopted) can affect  the contributed debug types (like "extensionhost"). Debug types are never contributed by anything in ".bashrc" files.
Environment variables are affected by Ben's changes, but they are not used in the standard "extension debugging" lauch configs.
Please investige with Connor why the debug type is not found.

**Comment by isidorn** [comment]
@weinand I'll take a look on Friday once I am back in Zurich so I can investigate on @joaomoreno machine

**Comment by weinand** [comment]
@isidorn then it might be easier for @connor4312 to investigate.

**Comment by connor4312** [comment]
I think this would only happen if `node-debug2`, which provides the extensionHost debug type, was not activated or installed in the remote. Are you able to reproduce this / can you check the Extensions view to see its state there?

**Comment by joaomoreno** [comment]
This does not repro any more. Probably related to https://github.com/microsoft/vscode/issues/123072
