### ISSUE TITLE
Markdown cells overlapping with content

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#123217]
1. In the `ap.github-issues` notebook
2. Set the contents of the first cell to:

```
# Config

a

$\f$

$$
\f\relax{x} = \int_{-\infty}^\infty
    \f\hat\xi\,e^{2 \pi i \xi x}
    \,d\xi
$$


a
```

3. Now reload

**Bug**
![Screen Shot 2021-05-06 at 5 11 40 PM](https://user-images.githubusercontent.com/12821956/117380372-66e7fa00-ae8e-11eb-89e3-a2db7d5006f6.png)

**Comment by mjbvz** [comment]
Also happens if you start re-sizing the notebook

**Comment by mjbvz** [comment]
@connor4312 Sorry this is from my suggestion to use `initializeMarkdown` in the recent change. It is causing multiple elements with the same id to be created. Will rewrite this to use a loop of `createMarkdownPreview` instead

**Comment by mjbvz** [comment]
Oh actually `createMarkdownPreview` seems to cause this too. Taking a look

**Comment by connor4312** [comment]
@mjbvz that is most importantly called when the webview reloads, which can happen on request from code in the webview (probably uncommon) or when a controller with preloads is substituted for one without preloads
