### ISSUE TITLE
[Regression] - Tasks launched in WSL are not finding right environment 

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#123209]
- VS Code Version: Version: 1.57.0-insider (system setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Clone https://github.com/boa-dev/boa
2. Load project into WSL
3. Run the "Cargo Run" task

### Expected

It should build and execute

### Happening

Its showing.
```
> Executing task: cargo run --bin boa ./tests/js/test.js <

The terminal process failed to launch: Path to shell executable "cargo" does not exist.
```

Even though the executable "cargo" is in my path. This didn't used to happen.

### Gif

This shows the task does not find cargo. But running the same command manually in the terminal works.

![cargoNotFound](https://user-images.githubusercontent.com/936006/117372514-8ea48580-aec1-11eb-8aad-fe37be3a4350.gif)

**Comment by jasonwilliams** [comment]
This could be related to the intergrated-terminal work that @Tyriar is doing but im unsure

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/123072

Fix coming soon

**Comment by jasonwilliams** [comment]
@Tyriar this is still happening on:
Version: 1.57.0-insider (system setup)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T17:19:03.737Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I saw you closed the other issue so mentioning this in case you still need a repro
