### ISSUE TITLE
gcc fatal error while saving files with spaces in between files names

### ISSUE THREAD

**Issue by Sandeep3429** [microsoft/vscode#123248]
We have written the needed data into your clipboard because it wa
Issue Type: <b>Bug</b>

1.while saving new files (written in C) with a file name with spaces in between 
for example (File name: Q 55 assingment calculator.c) saving file in this format shows error while the program is still active in the editor and after running the code display as Fatal Error in the terminal 

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:18:39.257Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) 4 CPU 3.00GHz (2 x 3172)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|2.99GB (0.54GB free)|
|Process Argv|--crash-reporter-id ced688e5-ede7-4f8a-8ce3-895c507cc8e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.3
msys2|fou|0.8.0
csharp|ms-|1.23.11
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
cpptools|ms-|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

s too large to send. Please paste.

**Comment by JacksonKearl** [comment]
\gifPlease
