### ISSUE TITLE
Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/InRelease  500  Internal Server Error [IP: 13.81.215.193 80]

### ISSUE THREAD

**Issue by nleo** [microsoft/vscode#123266]
`apt update` can't fetch data:

`Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/InRelease  500  Internal Server Error [IP: 13.81.215.193 80]`

Linux Mint 19.3 Tricia

**Comment by Tyriar** [comment]
I forwarded this to the Linux repo team
