### ISSUE TITLE
Terminal tabs: should provide a button to kill terminal

### ISSUE THREAD

**Issue by g-plane** [microsoft/vscode#123220]
- VS Code Version: 1.56.0
- OS Version: Linux 5.12

Steps to Reproduce:

1. Enable terminal tabs by setting `"terminal.integrated.tabs.enabled"` to `true`.
2. When there is only one terminal, tabs list aren't shown:

![图片](https://user-images.githubusercontent.com/17216317/117383841-3cd91b00-af14-11eb-9172-a079a341ed05.png)

so I can't kill current terminal directly by clicking any button.
Instead, currently I must click on the terminal tab name to open context menu:

![图片](https://user-images.githubusercontent.com/17216317/117383960-790c7b80-af14-11eb-894b-496c1bc36a52.png)

then click "Kill Terminal".

I hope VS Code can provide a button on UI to let user be able to kill terminal directly even tabs list aren't shown, which behaves as previous version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
You can make this happen by reverting to the old version with:

`terminal.integrated.tabs.enabled:false`

or you can always show the tabs (and thus the inline actions on hover, including the trash can) by setting:

`terminal.integrated.tabs.hideCondition:never`

**Comment by CameronBieganek** [comment]
@meganrogge I understand the workarounds that you provided, but wouldn't it be nice to have the trash icon showing when there is only one integrated terminal, without having to revert to the old system?

**Comment by yume-chan** [comment]
> without having to revert to the old system?

Use the second setting (`"terminal.integrated.tabs.hideCondition": "never"`)

**Comment by jpike88** [comment]
please reopen, this is clearly a design issue because its totally counter-intuitive.

**Comment by CameronBieganek** [comment]
@yume-chan I normally only use one integrated terminal, so if I use the second setting, then I lose horizontal space and add noise for no good reason.

I agree with @jpike88. This issue should be re-opened (or we can use the new issue that he created).

**Comment by jpike88** [comment]
@meganrogge are you going to reopen this issue instead of just shutting down my other one and leaving it at that? Why am I bothering to give meaningful feedback if it's just going to get buried?

**Comment by jpike88** [comment]
Disregard, looks like it got reopened and I was looking at an old notification

**Comment by Tyriar** [comment]
We're tracking in https://github.com/microsoft/vscode/issues/126225 now, sorry about the lack of comment over there
