### ISSUE TITLE
Terminal scroll keybindings

### ISSUE THREAD

**Issue by MCubista1** [microsoft/vscode#123261]
- VS Code Version: 1.56.0
- OS Version: Linux x64 5.8.0-50-generic snap

April 2021 release  messed up the scroll page keybindings.
 
Steps to Reproduce:

1. Open Keyboard Shortcuts
2. Search for Terminal: Scroll Down (Page) command and change keybinding to alt+d
3. Same for Terminal: Scroll Up (Page) command, to alt+e
4. Open integrated terminal, print some thing and scroll

![Peek 07-05-2021 03-27](https://user-images.githubusercontent.com/61259839/117422430-341d2080-aee5-11eb-8e86-fb4584a43a83.gif)

Scroll bar moves but the text doesn't

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Can repro on Windows when gpuAcceleration is off, using these exact keybindings

**Comment by MCubista1** [comment]
Changed gpuAcceleration from auto (default), to on. The terminal scrolls properly

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/3323

**Comment by forky2** [comment]
Very pleased to see this fixed! I'm new to tracking vscode issues. When might this make it into stable or insiders?

**Comment by Tyriar** [comment]
@forky2 i think it's in Insiders now so 1.57
