### ISSUE TITLE
Editor crash when select multi lines and do some actions..

### ISSUE THREAD

**Issue by ifeuille** [microsoft/vscode#123256]
- VS Code Version:1.56.0(user setpup)
- OS Version:8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.Select multi lines
2.ctrl+k,ctrl+c
3.ctrl+k,ctrl+u
4.Click the selected character..

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@ifeuille I could not reproduce. Do you have additional information or maybe a screen recording to demonstrate the problem:


https://user-images.githubusercontent.com/5047891/121002278-76f44180-c78c-11eb-869f-f7c2e44de504.mp4
