### ISSUE TITLE
Need to be able to have Variable containers not just at the top level

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#1232]
Today VSCode displays top level variable containers like `Local, Global` differently than regular variables.  I want this capability inside of variable nodes.  I want to emulate the "Raw View" functionality in the Visual Studio debugger e.g.:

![rawview](https://cloud.githubusercontent.com/assets/5177512/11770751/a7f37cd2-a1c3-11e5-8fa7-be320eff25f5.png)

Now I can create a `faux` variable called `Raw View` and get the nesting but VSCode make's it look like any other property via the purple coloring and the `:` it suffixes the name with.  

What I would like is the node displayed in White as the top level variable containers are displayed and no `:` suffix.

**Comment by daviwil** [comment]
This would be great to have!

**Comment by egamma** [comment]
@weinand @stevencl fyi

**Comment by stevencl** [comment]
Thanks for the suggestion. Could you talk a bit more about the scenario in which you will use this and the problem that you are facing today? We're working on improving the debugging UX right now and I want to make sure that I fully understand how you would like this to work and what you are looking for.

For example, are you looking for some way to be able to customise the display of variables in the local and watch window? For example, by specifying which fields of an object should be displayed by default (the same way VS does with the DebuggerBrowsable attribute) or by defining a proxy to be used for displaying values in the debugger (like the DebuggerTypeProxy class in VS)?

Or is it something else?

**Comment by rkeithhill** [comment]
Nothing that fancy.  I can fake out VSCode and create a `faux` variable to act as my container.  Here's what it looks like - `Automatic Variables`:
![filteredvariables](https://cloud.githubusercontent.com/assets/5177512/11804556/13c67dc0-a2c2-11e5-969c-1953980b82cb.png)
Think of "Automatic Variables:" as a filtered view - could be called "Auto" or "My Variables".  It is not a `real` variable - it is a container like the top level `Local, Script and Global` containers.  

I want the end user to be able to **easily distinguish between these "container" nodes and real variables**.   I suggest displaying these container nodes just like the top-level nodes - using white text and not appending a `:`.

**Comment by weinand** [comment]
If a DA returns an empty string for the `value` attribute of a Variable, no ':' is appended to the `name` attribute:

![2017-11-10_12-10-01](https://user-images.githubusercontent.com/1898161/32655946-26c3b2da-c610-11e7-85b0-4c3a97417df2.png)

**Comment by weinand** [comment]
Will be tested as part of #38055.
