### ISSUE TITLE
Syntax token inspector doesn't show font-style changes caused by semantic highlighting

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#123299]
Steps to Reproduce:

1. Open a new editor
2. Write `Array`
3. Save the file with `.js`
4. Switch color theme to `Monokai`
5. Command Palette -> `Developer: Inspect Editor Tokens and Scopes`
6. Move to the beginning of the word `Array`
7. Under `font style` it shows `[object HTMLSpanElement]` instead of `italic`

---

Does this issue occur when all extensions are disabled?: Yes
VS Code version: Code - Insiders 1.57.0-insider (6bee0f2f3fea9df1ad45344f09b2a139c93b384f, 2021-05-07T08:43:06.427Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
Thanks for the guidance. Pushed a fix!
