### ISSUE TITLE
Environment Variables Issue

### ISSUE THREAD

**Issue by naman4662** [microsoft/vscode#123243]
Issue Type: <b>Bug</b>

When you set env variables using settings.json , thay are not being accessed by the integrated terminal and same thins is working fine in version 1.55

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by nitishxp** [comment]
I am too facing this issue after upgrading to 1.56.0  Needed to revert back to 1.55.2 in order to make it work.

**Comment by nitishxp** [comment]
So need to start reading the changes that are being made to vscode in each release :)
