### ISSUE TITLE
UI fail after upgrade to 1.56.0

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#123223]
版本: 1.56.0 (system setup)
提交: cfa2e218100323074ac1948c885448fdf4de2a7f
日期: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

upgrade to 1.56.0

![UX fail](https://user-images.githubusercontent.com/1876302/117386592-c3442b80-af19-11eb-9130-60a679b90610.png)

**Comment by heartacker** [comment]
same as https://github.com/microsoft/vscode/issues/121253

**Comment by heartacker** [comment]
版本: 1.56.0 (system setup)
提交: cfa2e218100323074ac1948c885448fdf4de2a7f
日期: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0

V8: 8.9.255.24-electron.0
OS: Windows_NT x64 6.1.7601
I can reproduce this issue with another win7 pc
![UX fail-win7](https://user-images.githubusercontent.com/1876302/117395845-5df93600-af2b-11eb-859a-8e7ad245df1b.png)

**Comment by gjsjohnmurray** [comment]
Also #123036

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/123036
