### ISSUE TITLE
Salesforce Query Editor extension is no longer working on V 1.56

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#123281]
- VS Code Version: 1.56
- OS Version: MacOS - M1 build

Steps to Reproduce:

1. Open `Salesforce Query Editor` (https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor) in VSCode 1.55 and verify it works
2. Now open it on VSCode 1.56 and verify that nothing is displayed

![Screenshot 2021-05-07 at 13 26 07](https://user-images.githubusercontent.com/55927613/117449380-d239d680-af37-11eb-9951-8e936f08cbc9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by AllanOricil** [comment]
No exception on the console related to the extension. And release notes don't say what I should update to make it work.


![Screenshot 2021-05-07 at 18 38 36](https://user-images.githubusercontent.com/55927613/117487884-93217a80-af63-11eb-887d-b7407a54e5a1.png)

**Comment by mjbvz** [comment]
You're extension doesn't appear to be open source so I can't debug it

This is likely a result of [switching to use service workers to load webview resources](https://code.visualstudio.com/updates/v1_56#_service-workers-now-used-to-load-resource-in-webview), which may cause problems for extensions that were hardcoding assumptions about how resources are loaded

Please start by investigating what is going wrong in your extension (such as what resources are not loading). If you feel this is a bug, then share a minimal repo that demonstrates the issue

**Comment by AllanOricil** [comment]
@mjbvz  I gave you permission to the repository. Switch to the branch `next`. The app.js is loaded in the html from this cdn `https://cdn.jsdelivr.net/npm/salesforce-query-editor-app@0.0.63/dist/_nuxt/app.js` and from the inspector I can see it is being downloaded. It actually executes part of it, because I can see it connected to a websocket that I expose in the extension. But somehow nuxt is not able to mount to this new webview.

**Comment by AllanOricil** [comment]
@mjbvz I also changed the html to load app.js from the local machine, instead of the cdn, using asWebviewUri and the result is the same.

**Comment by mjbvz** [comment]
I do see the requests to `localhost` timing out: 

- `http://127.0.0.1:5000/`
- `ws://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket`

But don't know what those are for or what should be returned from them

**Comment by AllanOricil** [comment]
> I do see the requests to `localhost` timing out:
> 
> * `http://127.0.0.1:5000/`
> * `ws://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket`
> 
> But don't know what those are for or what should be returned from them

@mjbvz  Those time out because the extension did not activate. The activation event is when you open vscode in a sfdx project. Then the extension will start an express server with Socket IO on port 5000. From my print you can see that the javascript connected to the websocket without a problem. There is a console.log saying `connected`.  
Like I told you, I did not change anything from my side. If I run the extension on VS Code 1.55.2 it works. Something you guys released broke it, but you don't have enough documentation to guide me to fix it. There is no exception and the app works without a problem even when running outside of VSCode.

**Comment by AllanOricil** [comment]
@mjbvz  I found something weird. Probably is related to the way vscode renders that Iframe. Let me try to explain what I did. 

1 - Open the extension
2 - Open the Webview Developer Tools
3 - Verify that you have the same console log messages I have in the image below, with no exceptions and with the `connected`  message displayed, to indicate the app is connected to the Websocket.
4 - Wait few minutes (I did not count) until you see the Webview rendered.


![Screenshot 2021-05-08 at 11 18 47](https://user-images.githubusercontent.com/55927613/117535873-c3aef600-afef-11eb-9558-15f95ed7a852.png)

**Comment by AllanOricil** [comment]
@mjbvz  I reproduced this bug again. Basically you can open the extension, and wait a random amount of time. Go do something else in another desktop and then come back after, maybe, one hour or two. And the extension will be there in the panel.

![Screenshot 2021-05-08 at 12 36 28](https://user-images.githubusercontent.com/55927613/117537616-0e357000-affa-11eb-8faa-a24152101f23.png)

**Comment by mjbvz** [comment]
Please put together a minimal repo that demonstrates what you believe the problem is

**Comment by AllanOricil** [comment]
@mjbvz I will create a simple project and send to you.

**Comment by AllanOricil** [comment]
@mjbvz I found the root cause and I now I need your help. I noticed that the amount of time I have to wait for the app to render is not random. Basically I have two sync requests that I do before nuxt starts rendering. When these requests timeout, nuxt finally render the page. So I need to know from you why the new Iframe does not allow my webview to connect to the local server that the extension starts? Basically when the extension is activated I start an express server on port 5000, but the Webview is no longer able to connect to it on V1.56.0. Now that I know this, could you help me to understand the reason?

**Comment by AllanOricil** [comment]
It is not a problem related to use <iframe> or <webview>. I added `enableFIndWidget:true` to force the panel to use the old <webview> and the requests to `localhost` were also not working. If I change to vscode v1.55.2 it works. So, we can finally conclude that there is something new on v1.56.0 that is blocking the Webview from issuing requests to localhost, since I did not change anything from my side.

**Comment by mjbvz** [comment]
Please put together a minimal sample

**Comment by AllanOricil** [comment]
@mjbvz did you understand the problem with the example I shared with you?

**Comment by AllanOricil** [comment]
The code is already public and it was not given any explanation about why this bug was introduced. Could anybody else from the vscode team help on this?

**Comment by mjbvz** [comment]
Again, please share the most minimal example that demonstrates the issue. When I last checked the sample, I have to spend time figuring out how your code is structure and supposed to work instead of being able to focus on identifying the potential issue

**Comment by AllanOricil** [comment]
@mjbvz this is the minimal example I shared with you privately two weeks ago, and it is now publicly. It has the instructions to Reproduce it. You even accepted the invite when I shared with you. But here it is again.

https://github.com/AllanOricil/vscode-extension-nuxt

**Comment by mjbvz** [comment]
I'll try to take a look when I have a chance but that is not a minimal example. To speed things up, please create something more akin to https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample that contains the bare minimum amount of code needed to demonstrate the issue

**Comment by AllanOricil** [comment]
@mjbvz man, common. The example I shared is extremely simple. I think you did not even read the README in the project. There is just a really small express server and a nuxt app with one component that does a request to this express server. You don;t even need to understand Nuxt at all. Just verify that axios does a request to the express server that runs on localhost and it times out, because the webview can no longer connect to a localhost server. I won't create another example.

If you really don't want to help. Just say it here and close the issue.

**Comment by AllanOricil** [comment]
@mjbvz First, sorry for the last response. Im trying to understand this for almost a month and have not get any help. My motivation to keep improving the app dropped considerably, and I also got stressed because I worked for more than a year on it to just see it getting deprecated. But again sorry, and I hope you can help.

I started to debug again and found new findings that might help you to help me. I created a really simple extension with only one webview and it uses only a simple html. For this project Im not using any framework, and the javascript to issue the request to localhost is in a script tag right in the html. When I ran this extension, my surprise was that it was able to issue requests to a local server.
Then I created the same extension but this time using Nuxt. In this Nuxt app I did the same thing as I did in project. It only issues a single request to localhost. And as expected it did not work. Then I noticed a difference in the inspector that might be related to the problem. The webview frame that wraps the nuxt app is in `pending` state and never changes, while webview frame for simpler project is in `active` state.

Extension with simple html and script:  https://github.com/AllanOricil/webview-investigations-without-bug
Extension with nuxt: https://github.com/AllanOricil/webview-investigations-with-bug

And again, Nuxt is not the problem as in VS Code 1.55.2 my extension and this example are both working without a problem.

**Comment by AllanOricil** [comment]
No. Thanks for seeing it now.

**Comment by mjbvz** [comment]
Thanks for the example repo. I just tested it but the loading is pretty instant for me in the current VS Code 1.57 insiders build (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c) using the `webview-investigations-with-bug` repo:

https://user-images.githubusercontent.com/12821956/121460215-6ea12f80-c961-11eb-91d2-38f62e231564.mov

This was on MacOS. I don't see anything odd in the developer tools either.

<img width="1206" alt="Screen Shot 2021-06-09 at 8 31 17 PM" src="https://user-images.githubusercontent.com/12821956/121460361-aad49000-c961-11eb-9d46-0b28a656a695.png">

Are you seeing this issue with the latest insiders build?

**Comment by AllanOricil** [comment]
This issue was fixed on VSCode 1.57. Thanks @mjbvz
