### ISSUE TITLE
[Bug] Duplicate git decorations

### ISSUE THREAD

**Issue by wuhkuh** [microsoft/vscode#123331]
- VS Code Version: 1.56.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

```
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Create a directory, initialize a git repository with an untracked file, and a vscode settings (`.vscode/settings.json`) file.
2. Set `git.decorations.enabled` in your **global** configuration to `false`.
3. Set `git.decorations.enabled` in your **local** configuration to `true`.
4. Open the directory with the local configuration, check your VCS view and refresh, this should work as expected.
5. Set `git.decorations.enabled` in your **global** configuration to `true`.
6. Check your VCS view again and refresh, the decorations start stacking (this is the bug).
7. If you keep flicking the **global** setting, more badges will appear.

This issue propagates throughout the interface where this badge is shown.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
@wuhkuh, sorry for not getting back to you on this until now.
Are you able to reproduce the issue with the latest version of VS Code?
