### ISSUE TITLE
visual studio code is asking me again and again to choose between typescript versions

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#12332]
- VSCode Version: 1.6 nightly
- OS Version: win 10 x64

Steps to Reproduce:

When I open my visual studio code I **ALWAYS** get this:

![image](https://cloud.githubusercontent.com/assets/5945955/18681672/66b60b7a-7f69-11e6-88f6-47f0d24c7127.png)

I say to choose the TS 2.0.2 but the next time I start Visual studio code it is asking me again and again...

How can that be saved to the hard disk?

**Comment by chrmarti** [comment]
Does your "typescript.tsdk" setting point to the 'lib' folder of the typescript 2.0.2 package?

**Comment by bastienJS** [comment]
// TypeScript

    // Gibt den Ordnerpfad mit den zu verwendenden tsserver- und lib*.d.ts-Dateien an.
    "typescript.tsdk": null,

**Comment by chrmarti** [comment]
Can you try pointing it to your typescript install. E.g., if that is in the folder VSCode has opened, you'd use:
```
"typescript.tsdk": "node_modules/typescript/lib"
```
