### ISSUE TITLE
Menu Bar Not Visible

### ISSUE THREAD

**Issue by bjelleybean** [microsoft/vscode#123386]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

The menu bar disappeared when I reinstalled VSCode today in Ubuntu 21.04 and no amount of adjusting settings per internet resources has had any effect. Don't worry about trying to resolve this as I already uninstalled VSCode and am shopping for a new code suite.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 5.11.0-16-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 1621)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|13.60GB (0.15GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 4107383c-a859-40e4-967f-631f4ba59c27|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   139	 29924	code main
    0	    42	 29926	   zygote
    0	    70	 29966	     gpu-process
    0	    42	 29927	   zygote
    0	    84	 30194	     window (Issue Reporter)
    0	    70	 29976	   utility
    0	   209	 29991	   window (Welcome - Visual Studio Code)
    0	   167	 30046	     extensionHost
    0	    70	 30126	       /snap/code/63/usr/share/code/code /snap/code/63/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=30046
    0	   125	 30032	   shared-process
    0	    70	 30067	     ptyHost
    0	     0	 30215	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 30216	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.1.0
arepl|alm|2.0.2
vscode-browser-preview|auc|0.7.1
vscode-django|bat|1.6.0
armview|ben|0.4.5
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.6.16
python-extension-pack|don|1.6.0
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
vs-code-http-server-and-html-preview|Fli|2.2.2
auto-close-tag|for|0.5.10
docker-explorer|for|0.1.7
vscode-pull-request-github|Git|0.26.0
rest-client|hum|0.24.5
vsc-python-indent|Kev|1.14.2
vscode-github|Kni|0.30.6
kite-snippets-basic|lum|0.0.2
MagicPython|mag|1.1.0
python-path|mge|0.0.11
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.12.1
vscode-dotnet-runtime|ms-|1.1.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cpptools|ms-|1.3.1
vscode-node-azure-pack|ms-|0.1.0
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
autodocstring|njp|0.5.4
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
java|red|0.79.1
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.2
vscode-qt-for-python|sea|1.0.1
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|2.5.13
ayu|tea|0.20.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
gitblame|wad|7.0.2
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(16 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353
bridgeflightcf:30299255

```

</details>

**Comment by sbatten** [comment]
@bjelleybean Sorry to hear that. If this issue can be resolved, I'd love to get more info to better help other users who might experience the same issue.

Would you be willing to share more details about your setup? Does your OS try to use a global menu bar? Can you share the contents of your `settings.json` file for VS Code?
