### ISSUE TITLE
vscode will be shutdown at once !!! (shift + tab)

### ISSUE THREAD

**Issue by chenDSEE** [microsoft/vscode#123346]
Issue Type: <b>Bug</b>

1. select many line by cursor or keyboard
2. shift + tab
3. vscode will be shutdown at once

if only select one line, vscode will not be shutdown

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.12GB free)|
|Process Argv|--crash-reporter-id 0c5cc2c9-9504-48d6-9baf-5f4d1e88149d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
ifc-syntax|Ala|0.1.4
Bookmarks|ale|13.0.4
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.2.2
c-cpp-compile-run|dan|1.0.14
vscode-markdownlint|Dav|0.40.4
LogFileHighlighter|emi|2.11.0
vsc-material-theme|Equ|33.2.0
vscode-pull-request-github|Git|0.26.0
vscode-test-explorer|hbe|2.19.6
vscode-drawio|hed|1.4.0
better-cpp-syntax|jef|1.15.5
docthis|joe|0.7.1
restructuredtext|lex|153.0.0
vscode-catch2-test-adapter|mat|3.6.26
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.6.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
text-marker|ryu|1.11.0
tabnine-vscode|Tab|3.4.4
cmake|twx|0.0.17
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352
bridgeflight:30299254

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
