### ISSUE TITLE
Dotnet commands Permission Denied

### ISSUE THREAD

**Issue by Sherwoodwt** [microsoft/vscode#123324]
Issue Type: <b>Bug</b>

When debugging a dotnet core 3.1 project through vscode I get the following error. I've checked that the project files have the correct permissions, have tried running vscode with sudo, and reinstalled vscode without fixing this issue.

Rolling back to the previous version fixed the issue, so this appears to be caused by the latest update.

```
execvp(3) failed.: Permission denied
The terminal process "dotnet 'build', '/Users/a0793132/Documents/services/broker-service/api/BrokerService.API/BrokerService.API.csproj', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1).
```

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (11.30GB free)|
|Process Argv|-psn_0_1171742 --crash-reporter-id 1b0498e7-6173-4db4-916d-dbcc45879293|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
csharp|ms-|1.23.11
material-icon-theme|PKi|4.6.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Please file against C# extension, thank you

**Comment by superman-lopez** [comment]
This issue surfaced for me when updating to Version 1.56.2 (from 1.55).  Following the response of @isidorn I tried to downgrade the C# extension (from 1.23.11 to 1.23.8) but that had no effect.

Instead I downgraded vs code to version 1.55.2 and the issue has disappeared (while using the latest C# extension version 1.23.11).
