### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by tsrdatatech** [microsoft/vscode#123313]
Issue Type: <b>Bug</b>

I was able to use breakpoints while debugging my node javascript file but now it no longers work. It worked before updating yesterday to the April release. It just basically does not respect or stop at any breakpoint I set.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 5|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id c564d970-400e-4404-b3a4-febe033b55c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
LogFileHighlighter|emi|2.11.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
git-project-manager|fel|1.7.1
Python-autopep8|him|1.0.2
beautify|Hoo|1.5.0
vscode-flake8|jay|0.0.4
restructuredtext|lex|153.0.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.12.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
vscode-yaml|red|0.18.0
markdown-preview-enhanced|shd|0.5.18
tabnine-vscode|Tab|3.4.4

(4 theme extensions excluded)

</details>

**Comment by tsrdatatech** [comment]
I noticed that now when I set a breakpoint once I start running my script it then disappears

**Comment by tsrdatatech** [comment]
Sent via email @connor4312

**Comment by connor4312** [comment]
In the log you sent, it looks like there are breakpoints in two files. One of them, `oregon_scrape`, not parsed/executed by Node, so breakpoints here will not be bound. In the `school_messenger` file, we tell Node.js to set the breakpoint on (for example) line 83, and Node.js tells us that the breakpoint resolved on line 102. This indicates that the file in a position on which V8 can't stop, such as before `function ` declaration

![image](https://user-images.githubusercontent.com/2230985/117509159-a0783e00-af3e-11eb-8cfa-4a13b77c8652.png)

From what you've shown I don't see the debugger doing anything different or odd. If this doesn't explain what you're seeing you're able to share your source / a reproduction case, I could look into it more.

**Comment by tsrdatatech** [comment]
so likely something in my code then not allowing a breakpoint to hit? I was able to hit some points but not within my function like I was trying. I'll dig deeper, thanks for checking and feel free to close this then.

**Comment by connor4312** [comment]
Ok, feel free to ping you run into more issues/have questions

**Comment by tsrdatatech** [comment]
From the log file how do you tell which line Node resolved it on?

**Comment by connor4312** [comment]
I import it into https://microsoft.github.io/vscode-pwa-analyzer/index.html You can use the grep on the right side to look for "breakpointResolved". Those are the events Node sends back when a breakpoint binds at a location. Note that line numbers in V8 are base 0, and that we intentionally set a breakpoint on line 0 (to deal with certain sourcemap cases)

**Comment by tsrdatatech** [comment]
ok got it, thanks

**Comment by connor4312** [comment]
I always be a bug in Node/V8. I notice you're on 16.1.0 which is brand new, we haven't had many users on it yet.

**Comment by connor4312** [comment]
Also, if you suspect it's an issue with the 1.56 update, you could try using a .zip of 1.55 ([link](https://az764295.vo.msecnd.net/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d/VSCode-darwin.zip)]) and seeing if that fixes it for you. If so, it's 100% my fault and I would appreciate a log on that version so I can diff them.

**Comment by connor4312** [comment]
Ok, thanks for letting me know! I'd recommend opening an issue on [Node.js](https://github.com/nodejs/node) with this information.
