### ISSUE TITLE
C# syntax highlighting incorrect in 1.56

### ISSUE THREAD

**Issue by mpearson** [microsoft/vscode#123333]
Issue Type: <b>Bug</b>

C# semantic highlighting is not working correctly in 1.56. The `new` keyword and constructor name are highlighted incorrectly when a variable is assigned after being declared. When assigned and declared in the same statement, highlighting is correct. The scope inspector reveals that the `new` keyword is interpreted differently in these two situations.

Minimal example:

```
using System.Collections.Generic;

class TestClass
{

    public List<int> ListField;

    public void TestMethod()
    {
        ListField = new List<int>();            // wrong
        
        List<int> localVar;
        localVar = new List<int>();             // wrong

        List<int> localVar2 = new List<int>();  // right
    }
}
```

Note that downgrading to 1.55 fixes the issue. I also tried reinstalling 1.56 and the bug continued to happen.

Below you can see the scope analysis tool showing different results for each case:

![Screenshot from 2021-05-07 16-05-33](https://user-images.githubusercontent.com/926478/117516873-35833300-af4f-11eb-852c-584979fae6a6.png)
![Screenshot from 2021-05-07 16-05-55](https://user-images.githubusercontent.com/926478/117516875-374cf680-af4f-11eb-807d-ff714549d55b.png)

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 4.15.0-142-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 3957)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.40GB (2.27GB free)|
|Process Argv|/home/matthew.pearson/Joby/autonomy/image_generation --no-sandbox --crash-reporter-id 341552e9-2289-46da-8b4d-81929f637f3c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
bracket-pair-colorizer|Coe|1.0.61
tslint|eg2|1.0.46
vscode-solution-explorer|fer|0.4.3
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.20
restructuredtext|lex|153.0.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
remote-containers|ms-|0.177.0
cpptools|ms-|1.3.1
code-settings-sync|Sha|3.4.3
unity-debug|Uni|3.0.2
transpose|v4r|0.0.5
vscode-arduino|vsc|0.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by Jakintosh** [comment]
I don't have much to add except for a +1, I rebooted and reinstalled both the C# plugin and vscode itself and C# was just totally messed up, couldn't find any pattern to what was broken—just big chunks of incorrect highlighting, and then other areas with no syntax highlighting at all. Ended up having to revert to 1.55.2 and the problem is completely fixed. I tried updating to 1.56 from there again and the same problems showed up, so it seems like something related directly to the 1.56 update.

**Comment by alexr00** [comment]
Did a couple things to address this:
- Reverted the update to the C# grammar that caused this. You can get this fix in the next insiders build.
- Added a test to catch the issue.
- Filed an issue with the repo that owns the grammar so that we can get a real fix later.
- Added to the April Recovery milestone so that the revert goes out in the stable recovery release.

**Comment by alexr00** [comment]
To verify:

1. Open a new file.
2. Set the language to C#.
3. Paste in this:
```cs
using System.Collections.Generic;

class TestClass
{

    public List<int> ListField;

    public void TestMethod()
    {
        ListField = new List<int>();            // wrong
        
        List<int> localVar;
        localVar = new List<int>();             // wrong

        List<int> localVar2 = new List<int>();  // right
    }
}
```
4. Verify that `new List` has the same coloring each time it is written.

**Comment by jrieken** [comment]
verified with ca15099e636b992d18b39d7fcfeef99f0c555308
