### ISSUE TITLE
All vscode windows exit when starting additional vscode instance

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode#123306]
Version: 1.57.0-insider
Commit: 6bee0f2f3fea9df1ad45344f09b2a139c93b384f
Date: 2021-05-07T08:17:31.522Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.1.0-050100-generic

Steps to Reproduce:

(this does not always repro, most days I open 3 or 4 vscode windows and never experience this bug)

1. Open vscode for any folder
2. Open vscode for another folder

All vscode processes now crash/close. When you then reopen vscode the system will later give you a small window telling you vscode was already running.

I have experienced this nuisance with vscode for the one or two years I've been using vscode. Every version, with or without extensions.

I don't lose any work, vscode is good at keep unsaved documents in its temporary buffers. When I reopen vscode, it automatically reopens all closed instances showing me the files I was working on before the crash.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Can you also attach the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by payonel** [comment]
i've updated my alias to always use this crash report parameter. so far, no crashes/unexpected closures. Will update this ticket when I have more data.

**Comment by deepak1556** [comment]
```
Crash reason:  SIGTRAP

Thread 0 (crashed)
 0  code-insiders!v8::CodeEventHandler::~CodeEventHandler() + 0x62554
 1  code-insiders!v8::HeapSnapshot::GetMaxSnapshotJSObjectId() const + 0x33294
```

Crash is seen in the v8 profiler path, we don't rely on this path in our codebase so not sure what is triggering it. @payonel couple of follow-ups,

1) How are you launching the additional vscode windows which lead to this crash, can you provide step by step info or a screencast. If launching from command line, please mention the command line parameters used.

2) Can you attach the commandline of vscode main process, 
   i) Run `code --status` or open the process explorer from with vscode
   ii) Check for process with `code main` and copy its PID
   iii) Get the commandline with `cat /proc/<PID-from-previous-step>/cmdline`

**Comment by payonel** [comment]
@deepak1556 i use an alias:
`alias code=code-insiders --crash-reporter-directory /home/payonel/.local/vscode-logs/`

`code-insiders` is not aliased, and resolved from PATH to /usr/bin/code-insiders

`file /usr/bin/code-insiders` reports:
`/usr/bin/code-insiders: symbolic link to /usr/share/code-insiders/bin/code-insiders`

`file /usr/share/code-insiders/bin/code-insiders` reports:
`/usr/share/code-insiders/bin/code-insiders: a /usr/bin/env sh script, ASCII text executable`

A sample cmdline for a code run is:
`/usr/share/code-insiders/code-insiders --crash-reporter-directory /home/payonel/.local/vscode-logs/ code/sandbox`
