### ISSUE TITLE
allow --no-check-certificate option in WSL when running code .

### ISSUE THREAD

**Issue by pawel-rozek** [microsoft/vscode#123314]
My company injects their certificates for some sites. Since I'm on Windows, and I use WSL for all my code, I use "code ." command to start vscode. Occasionally VS Code wants to update, and I get an error that I cannot update because of a self-signed certificate being encountered.
It would be nice to have the ability re-run "code ." after it fails and be able to add "code --no-check-certificate . " to bypass the injected certificates issue. Tried it, and I get a message:

$ code --no-check-certificate .
Ignoring option check-certificate: not supported for code.

Currently I have to re-download latest version manually and re-install manually.

Error I'm getting when I need to upgrade:
$ code .
Updating VS Code Server to version cfa2e218100323074ac1948c885448fdf4de2a7f
Removing previous installation...
Installing VS Code Server for x64 (cfa2e218100323074ac1948c885448fdf4de2a7f)
Downloading: 100%
Failed
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/pawel/.wget-hsts'. HSTS will be disabled.
--2021-05-07 08:37:00--  https://update.code.visualstudio.com/commit:cfa2e218100323074ac1948c885448fdf4de2a7f/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 40.64.128.224
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|40.64.128.224|:443... connected.
ERROR: cannot verify update.code.visualstudio.com's certificate, issued by ‘CN=mycompany.com,O=Mycompany Corporation,L=Dallas,ST=Texas,C=US’:
  Self-signed certificate encountered.
To connect to update.code.visualstudio.com insecurely, use `--no-check-certificate'.
ERROR: Failed to download https://update.code.visualstudio.com/commit:cfa2e218100323074ac1948c885448fdf4de2a7f/server-linux-x64/stable to /home/pawel/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f-1620391019.tar.gz
Please install missing certificates.
Debian/Ubuntu:  sudo apt-get install ca-certificates

**Comment by aeschli** [comment]
@pawel-rozek  Can you look into setting check_certificate = off in the wget config file?
