### ISSUE TITLE
Refresh env for the running processes (Windows)

### ISSUE THREAD

**Issue by wclr** [microsoft/vscode#123316]
Want to draw attention to this problem again. From time to time I find my self in the following situation:

After installing some programs on Windows, which are necessary for example for extensions (e.g., compilers), to make extensions see installed environment changes I need to close all the vscode instances and re-launch it (Reload window doesn't help). Only then env changes become effective for vscode. For integrated terminal, I could run `refreshenv` command, but for editor/extensions processes it doesn't work.

There are issues on this:

https://github.com/microsoft/vscode/issues/117627
https://github.com/microsoft/vscode/issues/29679 

There is also a discussed closed issue https://github.com/microsoft/vscode/issues/6333, last comment by @bpasero is "Ok I think this is fixed meanwhile.". But this doesn't seem to be true.

There probably should be some way to do this, for example, to handle `WM_SETTINGCHANGE` message.

- VS Code Version: 1.55.0-insider
- OS Version: Window 10

**Comment by bpasero** [comment]
Yes, I think this is expected. The only moment we would pick up new environment variables if if you launch VSCode from a terminal that has those new environment variables defined. Are you doing that?

**Comment by wclr** [comment]
> Yes, I think this is expected. The only moment we would pick up new environment variables if you launch VSCode from a terminal that has those new environment variables defined. Are you doing that?

I would like vscode extensions to become aware of new env variables without closing all the instances of VSCode and launching it again, but for example on window reload.
