### ISSUE TITLE
Pass arguments in executeCommand

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#12337]
I'm trying to pass arguments in executeCommand.
```
vscode.commands.executeCommand('extension.updateSettings',"start");
```
while in the registercommand
```
    var updateSettings = vscode.commands.registerCommand('extension.updateSettings', async (a : string) => {
```
i dont get the value Of A as "start"

How to pass arguments in register command by execute command

**Comment by chrmarti** [comment]
@shanalikhan Shouldn't make a difference, I think, but have you tried without the 'async' keyword for the command handler?

**Comment by shanalikhan** [comment]
Actually my extension has alot of usage of async await. So i must use async in the function and its not showing as expected.

**Comment by jrieken** [comment]
@shanalikhan Please provide more info like a pointer to your extension or a small extension that shows this. I have added a [test](https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/commands.test.ts#L43) that shows the normal register/execute cycle works, also large parts on the extension host rely on this making me confident this works

**Comment by shanalikhan** [comment]
I have committed the line here and i want in that simple way.
Please have a look
https://github.com/shanalikhan/code-settings-sync/commit/3f4650cc9128e380eecc68256d003060ecbfbf45

arguments length is 0

**Comment by jrieken** [comment]
When using *arrow* functions `arguments` aren't bound. See first paragraph here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
