### ISSUE TITLE
Let User change the UI Font

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/vscode#123397]
![image](https://user-images.githubusercontent.com/77537933/117568230-d521fc00-b0dc-11eb-9acd-906fae0aeb9d.png)

## I want to change the UI Font by default for windows I guess it is Segoe UI. but I want to change it I searched a lot but haven't find any answers. So please in your next UPDATE add this feature. 🚀🚀

**Comment by yume-chan** [comment]
Duplicate of #519
