### ISSUE TITLE
VSCode don't update automatically.

### ISSUE THREAD

**Issue by oscar-neiva** [Microsoft/vscode#12338]
- VSCode Version: 1.5.1
- OS Version: Ubuntu 14.04.4

The VSCode don't update the content of the folders automatically. After pull a project from git to update the folders and the codes in my computer, the VSCode don't update as the same time. So, after pull a project from git I need to close and open the program to it works.

**Comment by chrmarti** [comment]
Have you tried updating the max_user_watches as outlined here: https://code.visualstudio.com/docs/setup/linux

**Comment by chrmarti** [comment]
Possibly related: #7950

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
