### ISSUE TITLE
vscode: how to have copy filename in the right click context menu in file explorer

### ISSUE THREAD

**Issue by sant527** [microsoft/vscode#123385]
I am using visual studio

In the  explorer, how can I have option to copy filename

There is no option to copy filename when I right click on a file in explorer

The below image shows what I meant

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/HHM8f.png

**Comment by gjsjohnmurray** [comment]
Maybe try https://marketplace.visualstudio.com/items?itemName=bradzacher.vscode-copy-filename
