### ISSUE TITLE
Emmeet shortcuts do not work for VSCode

### ISSUE THREAD

**Issue by YOEL311** [microsoft/vscode#123388]
- VS Code Version:
1.5.6
- OS Version:
windows 10
Steps to Reproduce:

Emmeet shortcuts do not work for me
He always shows me no suggestions

I installed and removed the VSCode and it did not help
I disabled all the Extensions and it did not help

When I added the line
     "emmet.triggerExpansionOnTab": true,

To the settings file when I press the tab I get such an error
command 'emmet.expandAbbreviation' not found
![image](https://user-images.githubusercontent.com/39925212/117569508-b9aff480-b0ce-11eb-87fb-a8be1db66cb0.png)

This is what it looks like when I open settings

![image](https://user-images.githubusercontent.com/39925212/117561788-940cf600-b0a2-11eb-9603-6a01718171e3.png)

when I press CTRL + SHIFT  + p
emmet 
i get this
![image](https://user-images.githubusercontent.com/39925212/117569546-db10e080-b0ce-11eb-995f-35bdf341043f.png)

When I click on it - I get
![image](https://user-images.githubusercontent.com/39925212/117569576-0267ad80-b0cf-11eb-90aa-f9f7a83ae421.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
If you type (in an html file)

`a*3` and then <kbd>tab</kbd> what happens?

**Comment by YOEL311** [comment]
![image](https://user-images.githubusercontent.com/39925212/117617287-ffbf9380-b174-11eb-85e3-7629c9b4d9ef.png)

**Comment by rzhao271** [comment]
I forgot that it won't automatically show up if one searches "Emmet".
Does searching "@builtin" in the Extensions view work?

**Comment by YOEL311** [comment]
thenk you
