### ISSUE TITLE
New "terminal.integrated.profiles.windows" settings always tries to activate Python virtual environment with `.ps1`

### ISSUE THREAD

**Issue by hectormz** [microsoft/vscode#123323]
- VS Code Version: 1.57.0-insider
- OS Version: Windows 10.0.19042

Steps to Reproduce:

1. Switch to defining profiles with "terminal.integrated.profiles.windows"
2. Set non-powershell profile as default

```json
  "terminal.integrated.profiles.windows": {
    "Command Prompt": {
      "path": "C:\\WINDOWS\\System32\\cmd.exe",
      "icon": "terminal-cmd",
    },
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
  },
  "terminal.integrated.defaultProfile.windows": "Command Prompt",
```
Opening a new terminal with non-Powershell default results in:
```shell
C:\Users\hectormz\repo>& c:/Users/hectormz/repo/env/Scripts/Activate.ps1
& was unexpected at this time.
```

I originally had:
```json
"terminal.integrated.shell.windows": "cmd.exe",
```

Does this issue occur when all extensions are disabled?: No, but this is related to Python, too

**Comment by aravindvnair99** [comment]
Same issue here. I'm also facing the issue of VS Code opening PowerShell instead of CMD despite me setting it as default multiple times. It only lasts until I close VS Code.

**Comment by Tyriar** [comment]
For python activating, I suspect it's related to https://github.com/microsoft/vscode/issues/121760

For startup defaultProfile is known not to work on the initial restored terminal https://github.com/microsoft/vscode/issues/123188

/duplicate

**Comment by harooporks2** [comment]
I'm still getting this issue, I'm unable to run my python files in the integrated terminal because of it :/

**Comment by Tyriar** [comment]
@harooporks2 if it still happens in [insiders](https://code.visualstudio.com/insiders), please report to the vscode-python repo

**Comment by hectormz** [comment]
FWIW this is now resolved for me. I'm using:

* Python Extensions: v2021.6.920123138-dev
* VS Code Insiders: 1.58.0-insider

I'm not sure when this was fixed
