### ISSUE TITLE
the cursor is driving me crazy !!!

### ISSUE THREAD

**Issue by guiseek** [microsoft/vscode#123379]
Issue Type: <b>Bug</b>

changing places alone, alternating the Insert function

wow, extremely stressful

VS Code version: Code - Insiders 1.57.0-insider (a19565da7dfc739fa26e36aae96113e19fe3806f, 2021-05-07T18:11:54.098Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|/Users/guiseek/org/example/di-ts-in-practice --crash-reporter-id b413f355-ae65-4fc8-b500-65ab3bb259d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.1.0
ng-template|Ang|11.2.14
markdown-mermaid|bie|1.9.2
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
docthis-customize-tags|dwe|0.4.5
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
vscode-jest-runner|fir|0.4.34
go|gol|0.24.2
ts-barrelr|mik|1.6.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.819764235
remote-containers|ms-|0.177.0
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.4131
snippet-creator|nik|0.0.5
angular-console|nrw|17.3.0
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-xml|red|0.16.0
lit-plugin|run|1.2.1
vscode-stylelint|sty|0.86.0
vsfire|tob|1.4.1
vim|vsc|1.20.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255cf:30296410
vscgsv2:30286872
vscorehovct:30295782

```

</details>

**Comment by guiseek** [comment]
I don't know what you may have to leave it like this, nor how to reproduce

**Comment by nrayburn-tech** [comment]
Could you share a gif of what you’re experiencing?
You can record one with https://gifcap.dev/.

**Comment by KaoImin** [comment]
The same situation as #123092.

**Comment by KaoImin** [comment]
> Could you share a gif of what you’re experiencing?
> You can record one with https://gifcap.dev/.

I have already added a gif in #123092.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by rebornix** [comment]
it's caused by the Vim extension.
