### ISSUE TITLE
Add command id for exiting VS Code to bind shortcut to

### ISSUE THREAD

**Issue by lzbthlsn** [Microsoft/vscode#12333]
- VSCode Version: 1.5.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. I have two windows open. If I click File/Exit, both windows are closed instantly. If I use alt+f4, only one is closed. Why do I need to have them both closed simultaneously and VS Code exiting? So that when I open VS Code again, both windows will be reloaded.
2.

**Comment by michaeljota** [comment]
I think the title is mislabel, but I can reproduce this in Windows as well.

Is this a bug or a feature?

**Comment by michaeljota** [comment]
Oh! I misunderstood then. Ok. It's a weird behavior anyway.

**Comment by bpasero** [comment]
Since 1.8.x we have the `workbench.action.quit` command that a key can be bound to.
