### ISSUE TITLE
1.56 keeps crashing on Mac M1

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#123311]
- VS Code Version: 1.56
- OS Version: Mac OS M1

Steps to Reproduce:

It keeps crashing randomly. All instances of vscode are closed and a os pop up message appears for me to confirm. 
Is there any log file VS Code saves the issue that caused it to be closed?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by AllanOricil** [comment]
How can I get more info to you? I was running 3 vscode instances. One was with a terminal and serving a nuxt app, the other two were doing nothing. Suddenly when I ran `yarn dev` to build a project all windows crashed with a message asking for confirmation. Is there a way to get logs and give them to you?

**Comment by nrayburn-tech** [comment]
Some extra information can be found from using the issue reporter in vscode.
1. Launch vscode
2. Open command palette (cmd + shift + p)
3. Search for Report Issue
4. At the bottom, there are three checkboxes.  Click the show button next to each and copy/paste that info here.


If you can reproduce, you should also be able to get some logs with these instructions.
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by deepak1556** [comment]
@AllanOricil the issue does not have to be reproducible for a crash, if you can start the app following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and when it crashes , a report will be generated in the directory specified. Thanks!

**Comment by AllanOricil** [comment]
@deepak1556 in this guide it says "take the steps that lead to the crash" but I can't, as it crashed twice in different situations. Since I opened this bug it has not crashed again. I will close this as it is impossible to debug. I just hope it does not crash again. You could implement a form that will open once VS Code crashes that we just have to confirm that we want to send to you the reason it crashed. Some softwares/games I use have this "feature".
