### ISSUE TITLE
Workspace integrated terminal configuration is disallowed by default and terminal.integrated.allowWorkspaceConfiguration is not accessible from the UI

### ISSUE THREAD

**Issue by Senbjorn** [microsoft/vscode#123330]
Issue Type: <b>Bug</b>

0. Start vscode
1. Set up workspace settings.json
{
    "python.pythonPath": "/usr/bin/python3",
    "python.envFile": "${workspaceFolder}/.env",
    "terminal.integrated.env.linux": {
        "PYTHONPATH": "${workspaceFolder}",
        "JUPYTER_PATH": "${workspaceFolder}"
    },
    "terminal.integrated.env.osx": {
      "PYTHONPATH": "${workspaceFolder}",
      "JUPYTER_PATH": "${workspaceFolder}"
    },
    "terminal.integrated.env.windows": {
      "PYTHONPATH": "${workspaceFolder}",
      "JUPYTER_PATH": "${workspaceFolder}"
    }
}
2. open new integrated terminal window
3. $ echo $PYTHONPATH
There is no environment variable PYTHONPATH (but it is not an issue)

The actual issue is that there is no clear messages or any settings accessible from UI that help to avoid such behavior.

I have accidentally found out that there is "terminal.integrated.allowWorkspaceConfiguration" that is set to false by default.
To make terminal.integrated.env.* settings work in workspace settings I've set up "terminal.integrated.allowWorkspaceConfiguration": true in user settings. But I couldn't access it from the UI or find information on it with help of any guides or opened/closed issues on the internet.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 4.15.0-142-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2703)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|11.60GB (2.63GB free)|
|Process Argv|--disable-extensions --no-sandbox --crash-reporter-id 767f928b-fe55-4e61-b311-3a720b161f4d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by Tyriar** [comment]
It's in the settings UI, maybe you were searching within workspace settings which is prevented by design 
![image](https://user-images.githubusercontent.com/2193314/117671933-2de5a900-b15e-11eb-9a16-82473c46cd5a.png)

/duplicate https://github.com/microsoft/vscode-docs/issues/4526
