### ISSUE TITLE
Please bring back the terminal dropdown. 

### ISSUE THREAD

**Issue by CarlosBalladares** [microsoft/vscode#123377]
I would like to share my feedback on the new terminal sidebar for vscode insiders. Its confusing I'm used to having a sidebars visible all the time like the left sidebar for files/search git etc. The new one for some reason disappears when only one terminal is open.  

My suggestion is to bring back the old dropdown or make the sidebar static even when only one terminal is present.

Thanks

**Comment by nrayburn-tech** [comment]
You should be able to disable this with the setting `terminal.integrated.tabs.enabled`.

<img width="685" alt="Screen Shot 2021-05-08 at 9 19 27 PM" src="https://user-images.githubusercontent.com/52075362/117558435-1665cd80-b043-11eb-8f27-2cb0651f4f36.png">

<img width="621" alt="Screen Shot 2021-05-08 at 9 20 24 PM" src="https://user-images.githubusercontent.com/52075362/117558450-385f5000-b043-11eb-87fd-5bd1df6399d2.png">

**Comment by nrayburn-tech** [comment]
Actually, there is another setting to always show the sidebar as well. `terminal.integrated.tabs.hideCondition` set to `never`.

**Comment by CarlosBalladares** [comment]
Thanks for the info I will restore my workspace

**Comment by CarlosBalladares** [comment]
I think this can be closed thanks for the quick reply
