### ISSUE TITLE
[css] Evaluate the 2 browser rule for CSS auto-complete

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1233]
(sorry for long post)

As per #806 (for HTML), in CSS Intellisense a feature will only show up if there are two implementations. Unlike HTML this is controlled by the build script that excludes features with 1 or zero implementations.

The problem with this:

* all webkit prefixed features show up due to Chrome + Opera  (+ Safari for older features when Chrome and Safari were both using WebKit).
* the above is also the case for unprefixed features added to blink and picked up by both Chrome + Opera
* No moz prefixed features will ever show up as no other browser uses -moz-
* No ms prefixed features are included. This has changed in the latest update to the data in my PR as Edge supports a number of the same -ms- prefixes, but there are some it doesn't support or will drop, and any new feature added to Edge will show up ad IE isn't adding new features. In theory there will be no new MS prefixes as we now use flags, but it isn't impossible a prefix may need to be used. Features like the ms prefixed flex box are useful even though only implemented by IE10, as they're needed for backwards compat, and ofter difficult to remember due to the different syntax (syntax was updated just after IE10 shipped)
* Unlike with Chrome/Opera, any unprefixed feature added Edge, Safari or Firefox will not show until another browser picks it up.
* Unprefixed features will not show up when only prefixed ones are supported. This is bad as it leads devs to only use the -webkit- (or whichever) version, leading to interop issues for other browsers. We had to implement various webkit prefixes in Edge for this reason. The linter does complain when the unprefixed version is not used (at least for some properties…I've not tried all) but they're not included in the auto-complete. Flex box is a good example of where VS Code was only recommending -webkit- with the old syntax (now fixed with latest data update as browsers beyond IE now support unprefixed latest syntax). 

It will be much more difficult to codify in the generator, but there should either be some smarts built in to consider all the prefixed and unprefixed implementations as the same feature, so that if -moz- is supported by firefox and unprefixed by Edge for example, that is two implementations. It should also include the unprefixed one even if there are no implementations to help avoid vendor lock-in. The main issue I see is how to associate features that have different syntax, like how the flex box properties and values are different between old webkit/moz syntax, mid IE 10 syntax and the final unprefixed syntax.

If the rule is to stay at two implementations then Chrome and Opera should be treated as one in the generator. Safari too for older features, but that may be harder to add. Edge and IE should probably be counted as one too.

OR it could be made more simple and include if one implementation exists. This will be more fair and useful than the current situation, but it still falls foul of the fact unprefixed features will not show up for features only using prefixes in current browsers.

**Comment by egamma** [comment]
@aeschli fyi.

**Comment by aeschli** [comment]
I see your point. The 2 browser heuristic has its weaknesses and might lead to wrong conclusions on the user side. I removed the filter. For now lets show all proposals and tune from there. Maybe its better if we manually mark proposals that are deprecated and outdated.
