### ISSUE TITLE
Feature: Selective editing like KEDIT

### ISSUE THREAD

**Issue by VictorVicious** [Microsoft/vscode#12331]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by Bill-Stewart** [comment]
This is pretty vague. What specific features are you looking for?

**Comment by VictorVicious** [comment]
KEDIT has a feature called selective editing that lets you focus on a subset of the lines in a file, such as all lines containing a particular string. You can have KEDIT display only this subset of your file, and you can perform editing operations that affect only this subset. You can then return to viewing and working with the entire file, with the lines in the selected subset (as modified by your editing) remaining in their original position in the file.  For instance, from a command line you can specify "all /total/" and then all lines in the file containing the word "total" are displayed for editing (no new window is generated, no copy is made and displayed). You can then type "more /carrots/" and lines with the word "carrots" are added to the display in the same order of occurrence.  Similarly you can type "less /dollars/" and those lines displayed having the word "dollars" are removed.  All the while, you can edit these lines as desired.  You can then type "all" and the file being edited is displayed in its entirety with the edits in place.  You can define columnar zones like "zone 7 14" and you'll see vertical lines demarking the columns in the text being edited between these zones.   Then you can perform the "all, more, less" commands which with these zones defined restrict the commands to word(s) falling within the columnar zones.  These features, unique to KEDIT and the "Hessling Editor" have never shown up in other modern editors, but are extremely useful for interacting with a text document and I'm sure will set Visual Studio Code editor apart from it's competitors and be one of it's most popular features.  For reference, see KEDIT's web page http://www.kedit.com/features.ia1.html and download it.  It's based on XEDIT, the editor used with IBM's CMS system, along with having built in a large subset of IBM's REXX language. This flexible macro language makes it easy to redefine the keyboard and automate common editing tasks.

Another feature I miss from KEDIT is the ability to execute command line directives like "dir" and have the output pop directly into the editor.  Please seriously consider adding the selective editing feature that allows displaying a subset of the file in the window, rather than generating a new file containing that subset of lines, because allows direct manipulation of the original file, and is very intuitive to use.  Thanks for your replay.

Respectfully,

Victor Schmehl

KEDIT for Windows Overview<http://www.kedit.com/features.ia1.html>
www.kedit.com
KEDIT for Windows is Mansfield Software Group's text editor for both the 32- and 64-bit versions of Windows 7, 8, 8.1, and 10. It provides many powerful and useful ...




________________________________

**Comment by Bill-Stewart** [comment]
I can see selective line and/or column editing being a useful feature. Regarding command shell, you can use an extension called [Filter Text](https://marketplace.visualstudio.com/items?itemName=yhirose.FilterText) to modify selected text using a command-line filter or, if nothing selected, to insert the output of a command into the file.

**Comment by mjbvz** [comment]
Closing as this feature was opened over a year ago and no significant further interest has been expressed in it since then
