### ISSUE TITLE
extension webview reload not work

### ISSUE THREAD

**Issue by terryfeii** [microsoft/vscode#123396]
- VS Code Version: 1.56
- OS Version:Mac m1 11.2.2

Steps to Reproduce:

1.craete a extension use webview
2.in webview html add a button and bind click event to call location.reload()
3.only show a blank page

and also have a bug on Command "Developer: Reload Webviews"
1. it only effect webview on editor panel, not on sidebar or panel
2. when first call this command, page show blank, and call twice, it works

**Comment by mjbvz** [comment]
Yes we don't support modifying the `location` inside webviews. 

Split  webview-view reload issue to #124212
