### ISSUE TITLE
[Markdown] support for links to folder

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#123328]
Would be good to make the Preview handle links to folders, for example open them with executable defined in settings .

I see no point in downloading another program to use it as .md viewer, adding all features to VSCode's Preview is much more logical .

**Comment by mjbvz** [comment]
The preview already reveals links to folders in the explorer. This should work for link both in markdown editors and in the markdown preview

Being able to customize this behavior is a better fix for an extension

**Comment by irvnriir** [comment]
It started working after update . though it doesn't support cases when the folder isn't a part of the workspace .
