### ISSUE TITLE
Visual Studio Code tries to close my workspace when I open a folder

### ISSUE THREAD

**Issue by alexpirine** [microsoft/vscode#123325]
Hi,

So when I have an opened project, and I try to open a new folder (File -> Open File…), Visual Studio Code tries to close my opened files.

![image](https://user-images.githubusercontent.com/1610035/117505052-ba883f80-af83-11eb-8ae9-c6d5a7fb09d3.png)

This looks like this is intentional, but it doesn't make sense.

I ask to OPEN a folder, why does VSCode force me to close my current workspace to do that?

The only workaround I've found is to first create a new window (File -> New Window), and then open a new folder inside it. That's too many things to do for such a simple task. 😆

**Comment by alexpirine** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Open Editor closing everything (#119901)](https://www.github.com/microsoft/vscode/issues/119901)

Good job spotting the duplicate. So if this is intentional design, I am curious if anybody can explain how is this intentional behaviour helping them getting their job done, and what kind of sense it makes to trigger a "close" action when the user asks to "open" files. That seems very counter-intuitive.

**Comment by JacksonKearl** [comment]
Could you describe what you'd like to happen with your existing files and maybe I could show you a way to make that work?

**Comment by alexpirine** [comment]
> Could you describe what you'd like to happen with your existing files and maybe I could show you a way to make that work?

Sorry, I thought I already replied, but I didn't.

I don't want anything to happen to my existing files.

And I don't want to be asked what I want to happen to my existing files, since my intent to simply open a new folder (in a new window), without any side-effect whatsoever on existing files.

**Comment by alexpirine** [comment]
@JacksonKearl yes, I do get the desired behaviour. It opens a new window when I open a folder, without asking any questions.

Switching `window.openFoldersInNewWindow` to `on` solves my issue.

:)
