### ISSUE TITLE
Mouse Wheel Scroll Sensitivity FOR WORKBENCH 

### ISSUE THREAD

**Issue by nitin2953** [microsoft/vscode#123305]
There are many duplicates of this issue [#37727](https://github.com/microsoft/vscode/issues/37727), [#7640](https://github.com/Microsoft/vscode/issues/7640), etc
But I'm still posting this as it become a **BUG for me & others** 

I don't know whats wrong with my `touchpad:not(mouseWheel)`, but it scrolls tooFast, _not only in VSCode but all electron based apps_
After setting ↓ below ↓ settings to `0.04`, scrolling in editor & terminal with touchpad is **_SO GOOD_**

So Just like `editor.mouseWheelScrollSensitivity` & `terminal.integrated.mouseWheelScrollSensitivity`
A setting for **_WORKBENCH_** would be a **life saver for me & others**

🙏 PLEASE 🙏

**Comment by sbatten** [comment]
a workbench level setting would need to apply to all scrollbars and thus I believe this fits as an option to the general scrollbar used in VS Code thus leaving to @alexdima for decision

**Comment by nitin2953** [comment]
The problem is with Elan touchpad drivers on windows, here is registry setting to fix this issue everywhere

1. Open Registry Editor (regedit.exe)
2. Go to `Computer\HKEY_CURRENT_USER\Software\Elantech\SmartPad`
3. Change `ScrollControl_Mode` from `0` to `1`
