### ISSUE TITLE
JavaScript Debug Terminal When running npm test with jest it just hangs

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [microsoft/vscode#123317]
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. create multiple spec files 
2. configure `package.json` test scripts to run `"jest"`
3. Set a break point
4. from the terminal run `npm test`

I just rolled back to.

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

And everything works as expected after rolling back.

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 Is there a secure endpoint that I can upload the logs to as I prefer not to share them publicly nor email them due to it not being secure. Reviewing those logs I did not find any Levels of Error or Fatal. It just starts up and hangs.

**Comment by connor4312** [comment]
We don't have a secure endpoint, but you can encrypt the file with my [gpg key](https://github.com/connor4312.gpg). Or provide a sample repo that reproduces what you see.

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 I emailed you the logs yesterday. Just wanted to be sure they didn't get spammed.

**Comment by connor4312** [comment]
Hi, sorry for the delay.

Based on the logs, it looks like you hit a breakpoint 0.25 seconds into the debug session, and don't continue again. It should work if you click the "resume" button in the UI.

**Comment by jwyglendowski-precisionlender** [comment]
Interesting because the UI was unresponsive and there wasn't any indicator that it had stopped. So maybe that's the real issue. When I do the exact same thing in the previous version I do not have any trouble and the UI responds appropriately.

**Comment by connor4312** [comment]
Okay, that's probably the core issue -- the entire window freezes? Taking a profile using the instructions in `Profiling the Renderer Process` should help us get to the bottom of it: https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 Thanks. I am going to be out for a week starting in about 20 minutes :) So as soon as I am back I will grab that data for you. Thanks for all your help.

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 Here is the profile data and BTW this issue with the latest version of VS CODE.

Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041


[CPU-20210601T082629.cpuprofile.txt](https://github.com/microsoft/vscode/files/6576248/CPU-20210601T082629.cpuprofile.txt)

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 Interesting note. I am working on a script for my day to day work in node with just a single thread which does work with the terminal unlike when the scenario of this issue where jest runs multiple instances of node. Maybe VS Code is having an issue tracking the instances. Anyway I thought it worth providing that piece of information in case it can help.

**Comment by jwyglendowski-precisionlender** [comment]
@connor4312 Seems that latest version fixes the issue. I just tested it and it's working as expected. 

Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by connor4312** [comment]
Ok, cool. You were probably hitting https://github.com/microsoft/vscode/issues/124060
