### ISSUE TITLE
Keep order stable independent for how search is formed

### ISSUE THREAD

**Issue by sant527** [microsoft/vscode#123382]
searching for `contrib auth django` shows one kind of results

![image](https://user-images.githubusercontent.com/6462531/117559989-7b530f00-b0a7-11eb-96a8-f2a301a9c1e2.png)

while searching for `django contrib auth` shows another

![image](https://user-images.githubusercontent.com/6462531/117560008-a3427280-b0a7-11eb-8e7e-1d3c77373b37.png)

**Comment by gjsjohnmurray** [comment]
See #27317

Relevant label is `quick-open`

/label quick-open

**Comment by sant527** [comment]
is there a way i can avoid ranking
