### ISSUE TITLE
Hight consumption in ram memory

### ISSUE THREAD

**Issue by chivodev** [microsoft/vscode#123310]
Issue Type: <b>Bug</b>

The latest update of vscode is generating a high consumption of resources, exactly in ram memory, preventing it from working normally. The consumption goes up to almost 1 Gb of memory. 

Thank you.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 4.19.0-16-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3871)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 5|
|Memory (System)|15.58GB (4.28GB free)|
|Process Argv|--crash-reporter-id 560e9cc7-2d0f-43ad-898b-41b1248f664e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by diego1araujo** [comment]
> _"The latest update is causing high RAM consumption (up to 1GB) and affecting its usage."_
