### ISSUE TITLE
official support for Kotlin language.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#123369]
Issue Type: <b>Feature Request</b>

are there any plans for supporting Kotlin with official extension or out of the box?

VS Code version: Code - Insiders 1.57.0-insider (a19565da7dfc739fa26e36aae96113e19fe3806f, 2021-05-07T17:19:03.737Z)
OS version: Windows_NT x64 10.0.19042

**Comment by nrayburn-tech** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/118871.
Looks like that request needs about 15 more upvotes to be accepted.

**Comment by sanket-bhalerao** [comment]
i have upvoted already :)
