### ISSUE TITLE
Floating Sidebar

### ISSUE THREAD

**Issue by VapourDev** [microsoft/vscode#123349]
![float](https://user-images.githubusercontent.com/73135860/117526315-fce06980-afe1-11eb-9130-1f94621f8413.png)
?Floating Sidebar.

**Comment by JacksonKearl** [comment]
I don't understand the question

**Comment by VapourDev** [comment]
I am telling about Sidebar, see the sidebar in picture. that is rounded.

**Comment by JacksonKearl** [comment]
What theme are you using?

**Comment by misolori** [comment]
@VapourDev are you suggesting to provide an option to have a "floating sidebar"?

**Comment by VapourDev** [comment]
@misolori  Yes

**Comment by VapourDev** [comment]
@JacksonKearl I am using a third-party theme, but I am edited from Sidebar temporary from developer tools to show that, how that will look.
