### ISSUE TITLE
Windows 10 PowerShell Execution_Policies

### ISSUE THREAD

**Issue by maico910** [microsoft/vscode#123338]
Issue Type: <b>Bug</b>

I don't know which version was before, after update to last version, I can't run anyone script from my internal terminal (I'm using powershell)

I was this settings:

```
"terminal.integrated.shellArgs.windows": [
  "-ExecutionPolicy",
  "RemoteSigned"
 ]
```

and now is show me this is deprecated setting, so, how do I change the powershell execution policy?

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.86GB (5.36GB free)|
|Process Argv|--crash-reporter-id 50867d07-83d4-4330-9162-6dc4998d3793|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|3.3.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
githd|hui|2.2.4
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
vscode-thunder-client|ran|1.2.0
vue-vscode-snippets|sdr|2.2.0
swdc-vscode|sof|2.5.13
sass-indented|syl|1.8.16
language-stylus|sys|1.11.0
errorlens|use|3.2.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by diego1araujo** [comment]
You need to take a look at the new [Terminal Profiles](https://code.visualstudio.com/updates/v1_56#_terminal).

**Comment by maico910** [comment]
> You need to take a look at the new [Terminal Profiles](https://code.visualstudio.com/updates/v1_56#_terminal).

can you explain more about what I need to do here? I'm little confuse, I need to put like this?

```
"terminal.integrated.profiles.windows": {
  // Add a PowerShell profile that doesn't run the profile
  "PowerShell (No Profile)": {
      // Some sources are available which auto detect complex cases
      "source": "PowerShell",
      "args": [ "-ExecutionPolicy",  "RemoteSigned"],
      // Name the terminal "PowerShell (No Profile)" to differentiate it
      "overrideName": true
  }
}
```

**Comment by maico910** [comment]
> You need to take a look at the new [Terminal Profiles](https://code.visualstudio.com/updates/v1_56#_terminal).

@diego1araujo thank you very much, I don't know why, I was read about this, but I didn't understood, now is working!!!

```
"terminal.integrated.profiles.windows": {
    // Add a PowerShell profile that doesn't run the profile
    "PowerShell": {
        // Some sources are available which auto detect complex cases
        "source": "PowerShell",
        "args": [ "-ExecutionPolicy",  "RemoteSigned"],
        // Name the terminal "PowerShell (No Profile)" to differentiate it
        "overrideName": true
    }
  },
// set default terminal
"terminal.integrated.defaultProfile.windows": "PowerShell",
```
