### ISSUE TITLE
Text editing using Control + Right arrow key

### ISSUE THREAD

**Issue by AlxSts** [microsoft/vscode#123336]
Issue Type: <b>Bug Report</b>

While editing text, when the user uses Control + Right Arrow key to move to the next word in the text, cursor is positioned to the right of next word, over the previous adjacent white space. Cursor should be positioned to the left of next word, over it's first character. Every special character dividing two words should be skipped. This is the standard behavior in all text editors I have ever used.
Thanks in advance

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:18:39.257Z)
OS version: Windows_NT ia32 10.0.18363

**Comment by ArturoDent** [comment]
I see that <kbd>Ctrl</kbd>+<kbd>RightArrow</kbd> is bound to the command `cursorWordEndRight` by default. 

 It appears you want it bound to `cursorWordStartRight`.

```
{
	"key": "ctrl+right",
	"command": "cursorWordStartRight"
},
```

**Comment by AlxSts** [comment]
Hello!

Thank you Arturo ( @ArturoDent )  and Alexandru ( @alexdima ) for your support.

I would never think VSCode controls such a thing. One more reason to like it a bit more. Great tool!

But I keep wondering:
As said by Arturo "cursorWordEndRight by default." I think most of developers prefer "cursorWordStartRight". So, why should not it be set as the default setting?
