### ISSUE TITLE
Advice on how to make new untitled files non-preview in custom editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123360]
Custom editors need to create their own new untitled file commands, which means they end up showing as preview editors. This is different to untitled text files:

![recording (6)](https://user-images.githubusercontent.com/2193314/117537892-92ff9a00-afb8-11eb-96ad-5e279d922de4.gif)

When creating multiple new untitled custom editors, the new one always overwrites the old one as a result of the preview editor. It would be good if we solved this in custom-editor-sample so most extensions would get the behavior for free.

![recording (7)](https://user-images.githubusercontent.com/2193314/117537934-be828480-afb8-11eb-8c12-af59144ae3d7.gif)

This is what Luna Paint does to open untitled images: `commands.executeCommand('vscode.openWith', newImageUri, PaintEditorProvider.viewType);`

**Comment by bpasero** [comment]
I actually wonder if any editor that goes through "Open with..." or "Reopen with..." should be non-preview because of the explicit intent to open the editor by the user.

**Comment by Tyriar** [comment]
That works too 👍

**Comment by connor4312** [comment]
@Tyriar can you verify this?
