### ISSUE TITLE
Hope can automatically add files' name to csproj file. :-D

### ISSUE THREAD

**Issue by mycraftmw** [Microsoft/vscode#12336]
1.When I use visual studio code to open a c# project created by,I try to add cs files into the project,but these files' names does not be inserted to the  file automatically.Hope to add this function~

**Comment by chrmarti** [comment]
Have you tried using wildcards in your .csproj? (See for example: http://devcenter.wintellect.com/krome/wildcard-inclusions-in-c-project-files)

**Comment by mycraftmw** [comment]
Thanks a lot!The wildcards  worked!
Cool!
