### ISSUE TITLE
vscode freezes when pasting a very long text to the regex search feature

### ISSUE THREAD

**Issue by Mayhem93** [microsoft/vscode#123370]
Issue Type: <b>Performance Issue</b>

Hello,

So I accidentally copy pasted a very large string (about 100k, i was copying the contents of a file) in the search bar using the regex feature.

This caused a complete freeze of vscode. The file I was on was about 100kb and clipboard content I was pasting was **not** a valid regex.

One suggestion I could think of to prevent this is to check if it's a valid regex expression beforing processing it from the search box.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.12GB free)|
|Process Argv|--crash-reporter-id 51502e00-e574-4b88-a335-3dc1261a1799|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3593)|
|Memory (System)|25.02GB (24.69GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    75	 11380	code main
    0	    39	  1888	   utility
    0	    92	 17692	   gpu-process
    0	    96	 17864	   shared-process
    0	    65	 22192	     ptyHost
    0	    23	 19420	   crashpad-handler
    0	    81	 21272	   window (Issue Reporter)
    0	   159	 22256	   window (/home/uther/savafutd/index18 - Visual Studio Code)
    0	    80	  4608	     extensionHost
    0	    62	  4792	       electron_node wslDaemon.js 
    0	     6	  4308	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 3c4e3df9e89829dce27b7b5c24508306b151f30d stable .vscode-server 0  '
    0	    11	  2376	           console-window-host (Windows internal process)
    0	     6	 18856	           C:\WINDOWS\system32\lxss\wslhost.exe {293a77e4-718a-498d-806d-77ca77a7b72d} 472 500 504 {8bd9cb7a-feb5-4c79-b5fa-6bdc58d9b8a3}
    0	    13	 17740	             console-window-host (Windows internal process)

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	    27	remote agent
    0	     0	    38	   ptyHost
    0	     0	    62	   extensionHost
    0	     0	    88	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	    89	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu;
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
hjson|lak|0.3.2
vscode-jade-snippets|mrm|1.0.1
remote-wsl|ms-|0.54.6
chai-snippets|nwh|0.1.0
material-icon-theme|PKi|4.6.0
vscode-nginx|sha|0.6.0
vscode-todo-highlight|way|1.0.4
editorconfig-vscode-snippet|zgu|0.2.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
git-project-manager|fel|1.7.1
vscode-npm|fkn|3.3.0
guid|kos|0.0.1
split-join-text|Mat|0.0.8
powershell|ms-|2021.2.2
expresssnippet|vla|0.2.4
gitblame|wad|7.0.2
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by roblourens** [comment]
I can't repro this. The first thing we do with it is call `new RegExp` to check whether it's valid. Does it happen every time for you?

**Comment by Mayhem93** [comment]
Yes I reproduced the bug again.

I think I'll need to provide the text I have copied to my clipboard so I've uploaded this here: [http://www.razvanbotea.me/index18-copy](http://www.razvanbotea.me/index18-copy) (no worries, this is my domain so it's safe to click).

The file I had opened on which I tried searching is uploaded here:  [http://www.razvanbotea.me/index21-copy](http://www.razvanbotea.me/index21-copy)

I also went a bit further and sketched a short script:

```javascript
const fs = require('fs');
const clipboardContent = fs.readFileSync('./index18-copy').toString('utf-8');
const stringBeingSearched = fs.readFileSync('./index21-copy').toString('utf-8');

const regex = new RegExp(clipboardContent);

regex.test(stringBeingSearched);

```
Running `time node test.js` fails immediately in 38ms with `/: Regular expression too large`

**Comment by roblourens** [comment]
What I'm seeing is that the file is a valid regex, and and pasting it in will trigger a search. If I have the file open and we search in that file, vscode hangs. I have an idea of why a 100kb match might cause a hang, but wouldn't consider it a high priority issue.

**Comment by Mayhem93** [comment]
> What I'm seeing is that the file is a valid regex, and and pasting it in will trigger a search. If I have the file open and we search in that file, vscode hangs. I have an idea of why a 100kb match might cause a hang, but wouldn't consider it a high priority issue.

Stil weird that my short piece of code fails, but nonetheless I'm not sure how exactly in the vscode's code is the regex feature implemented

**Comment by roblourens** [comment]
Yeah, not sure what the difference is. I could add a length limit manually, but I don't really want to do that. Some issues with very long matches are tracked in other issues though.
