### ISSUE TITLE
Open Serial Monitor Error

### ISSUE THREAD

**Issue by jatu-studiobox** [microsoft/vscode#123319]
- VS Code Version: 1.56.0
- OS Version: Windows 10 Pro 20H2 build 19042.964

Steps to Reproduce:

1. Connect USB between Notebook and ESP8266
2. Code and upload to ESP8266.
3. Use 'Arduino: Open Serial Monitor' command at command palatte.
4. Error occur 
"Failed to open serial port COM3 due to error: + Error: The module '\\?\c:\Users\TERU\.vscode\extensions\vsciot-vscode.vscode-arduino-0.4.2\out\node_modules\usb-detection\build\Release\detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)."

Does this issue occur when all extensions are disabled?: Yes

**Comment by YuMERA** [comment]
I had the same problem and went down to the previous version VS Code 1.55.2 and now all is ok.
