### ISSUE TITLE
GoToDefinition is not available in [metadata] files

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#12334]
- VSCode Version: 1.5.2
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Have a C# project with the content:

    ```cs
    class Foo
    {
        System.Collections.Generic.List<int> bar;
    }
    ```

1. Invoke <kbd>F12</kbd> `GoToDefinition` on `List` to be taken to the metadata file for ```List`1``` (`public class List<T> : IList<T>...`

1. In this file, `GoToDefinition` is not an option on `IList<T>` and pressing <kbd>F12</kbd> on it does nothing.

Other language service things like tooltips are also not available.

**Comment by chrmarti** [comment]
Tracking as OmniSharp/omnisharp-vscode#771
