### ISSUE TITLE
wsl2 ubuntu Python django debug  question

### ISSUE THREAD

**Issue by diwangtseb** [microsoft/vscode#123354]
- VS Code Version: 1.56
- OS Version:Windows_NT x64 10.0.19042

Steps to Reproduce:

1. To connect to the WSL2 Ubuntu system with VScode, debugging a Python Django project will have to slow down and wait 5 seconds for a breakpoint to hit, but everything is fine in VScode 1.55.2

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Sounds like a duplicate of a https://github.com/microsoft/vscode/issues/123315

**Comment by isidorn** [comment]
@diwangtseb Can you reproduce if you start vscode with
`code --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>`

**Comment by diwangtseb** [comment]
@isidorn Today I downloaded the latest version of VSCODE 1.56 and no longer have this problem. Thank you very much for your reply😀
