### ISSUE TITLE
Tiling resize animation do not work on wayland

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/vscode#123359]
- VS Code Version: 1.56.0
- OS Version: Fedora 34

Steps to Reproduce:

1. Open VSCode with "code --enable-features=UseOzonePlatform --ozone-platform=wayland"
2. Press "Super+Up" to maximize the window
3. Press "Super+Right" to tile it to the right
4. The animation between the two isn't smooth like t's supposed to but is done in two steps only.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.74`
