### ISSUE TITLE
Terminal not opening

### ISSUE THREAD

**Issue by yksharan** [microsoft/vscode#123436]
Issue Type: <b>Bug</b>

Error message says, node_modules version says different.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.1.12-124.40.6.el6uek.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (17.63GB free)|
|Process Argv|--crash-reporter-id e8838afb-e7cb-4c9b-b15d-6b16bd5b46e2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev110.athenahealth.com|
|OS|Linux x64 4.1.12-124.40.6.el6uek.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (56 x 2600)|
|Memory (System)|377.52GB (3.13GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
vscode-remote-extensionpack|ms-|0.20.0
athena-monolith|Ath|0.0.5
vscode-perl|cfg|1.18.0
prettier-vscode|esb|6.3.2
perforce|mjc|4.15.2
perl-debug|mor|0.6.3
perl|ric|2.2.0
perltidy|sfo|1.3.2

</details>

**Comment by yksharan** [comment]
Additional Info. We are working on remote linux server. I get a popup error:
`The terminal process failed to launch: A native exception occurred during launch (The module '/LINUX_DIR_PATH/.vscode-server/bin/cfa...../node_modules/node-pty/build/Release/pty.node' was compiled against a different Node.js version using NODE_MODULE_VERSIOn 83. THis version of Node.js requires NODE_MODULE_VERSION 72. Please try re-compiling or re-installing the module (for instance, using 'npm rebuild' or 'npm install').).`

![image](https://user-images.githubusercontent.com/19584227/117622061-dd873f00-b18f-11eb-9443-6aa88aa3ad66.png)

Not just the terminal, even the perforce plugin and file searches have stopped working. One of my team member has reverted to older version and it has worked. So for now our whole team is planning not to update to latest version. 

Thanks in advance.

**Comment by Tyriar** [comment]
You might have seen this when we updated electron or something, I expect this to be fixed. You could try reinstalling to see if that helps.
