### ISSUE TITLE
Typescript files hangs when large code files are there

### ISSUE THREAD

**Issue by mrfambo** [microsoft/vscode#123462]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 20.4.0`
- VS Code version: `1.56.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8,
		"activateCallTime": 25,
		"activateResolvedTime": 11,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by mjbvz** [comment]
Can you please share the file/project that causes this?

You can also follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information

/needsMoreInfo
