### ISSUE TITLE
terminal is blank

### ISSUE THREAD

**Issue by geetanjalichawla** [microsoft/vscode#123471]
Issue Type: <b>Bug</b>

i cant do any thing in my terminal i tried everthing please help me out 

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (2.64GB free)|
|Process Argv|--crash-reporter-id 7e424b45-c0ed-43fe-81e0-7b5c37af7d14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.3
cpptools|ms-|1.3.1
sublime-keybindings|ms-|4.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by geetanjalichawla** [comment]
[](url)Microsoft Windows [Version 10.0.18363.1198]
i am using windows 10
i am having this problem i am a beginner so i dont know much about vs code but my terminal is not taking any input  and it is blank 
i was using a extention i removed it but still it is 
![ass4 c - learn - Visual Studio Code 5_10_2021 10_18_11 PM](https://user-images.githubusercontent.com/80254854/117695256-ac356000-b1dd-11eb-937a-2c95dc395c64.png)

>

**Comment by meganrogge** [comment]
Please go to Help -> Toggle Developer Tools -> console and let me know if you see errors there

**Comment by meganrogge** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by geetanjalichawla** [comment]
{
    "code-runner.runInTerminal": true,
    "editor.fontSize": 16,
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.sendKeybindingsToShell": true,
    "terminal.integrated.cwd": "C:\\",
    "terminal.integrated.env.windows": {
    
    },
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "terminal.integrated.experimentalLinkProvider": false,
    "terminal.integrated.splitCwd": "initial",
    "terminal.integrated.tabs.enabled": true,
    "terminal.explorerKind": "external"
}'


SETINGS I AM USING

**Comment by meganrogge** [comment]
Let me know if you're still having issues on the latest insiders

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
