### ISSUE TITLE
Markdown Preview fails to show local HTML files via iframe

### ISSUE THREAD

**Issue by orzechow** [microsoft/vscode#123451]
- VS Code Version: 1.57.0-insider
Commit: 54d33cf14cf6c0e86880b5b74a5a3628de42bce9
Date: 2021-05-10T05:14:41.869Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
- OS: Linux x64 5.4.0-72-generic

Steps to Reproduce:

1. Include a local HTML file in a Markdown file ([MWE here](https://github.com/orzechow/vscode-webview-bug))
    1. Create a local HTML file `iframe.html` with dummy content
    2. Create a Markdown file next to it and include the HTML file via iframe:
    `<iframe src="iframe.html"></iframe>`
3. Open the Markdown preview
4. The iframe fails to load ("ResourceNotFound")

The WebView Developer Tools reveal, that the link has been remapped from `iframe.html` to `https://<some-long-id>.vscode-webview-test.com/vscode-resource/file/home/user/path/to/iframe.html`. Why is that? It obviously makes no sense as it is a local link. Btw. I was surprised to see VSCode revealing my local paths to this webservice :unamused: 

Does this issue occur when all extensions are disabled?: Yes (tested with latest Insiders version without any extensions)

**Comment by orzechow** [comment]
Btw. this issue did not occur some weeks ago.

**Comment by otobrzo** [comment]
Any alternative to iframe? I have used it to insert plotly.js html figures

**Comment by orzechow** [comment]
Was the same use case for me – I'm viewing the plot in a browser now. But that might not be an option, if you have multiple plots :-/
