### ISSUE TITLE
. . . 

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#123453]
- VS Code Version:1.56
- OS Version:win10 

The vscode editor always forces the code to wrap, which is very annoying, and the setting is invalid.
"editor.wordWrapColumn": 500,
Is there any way to cancel this behavior? Let users decide for themselves whether they need to wrap.
Or is this a bug?

**Comment by alexdima** [comment]
@zhouxinghong I think you might be running into a configuration problem. Can you please share your `settings.json` ?
