### ISSUE TITLE
Expose parent session on DebugSessions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#123403]
Right now, debug session relationships are not exposed in the VS Code API. What I do in js-debug to track this is to add a `__parentId` property to the configuration so that I can maintain the tree internally. I think liveshare also needs this in order to fix https://github.com/MicrosoftDocs/live-share/issues/3515

I propose adding a new `readonly parent?: DebugSession` property to the `DebugSession` interface @weinand / @isidorn.

**Comment by weinand** [comment]
Yes, this proposal makes sense.
@connor4312 I assume you will implement this, right?

**Comment by connor4312** [comment]
Yep

**Comment by connor4312** [comment]
@swissmanu this will be available in proposed--though unguarded--in the next Insiders. Please try it out.

Moving this for finalization next month. (Or we could just finalize this month, it's a pretty simple change)

**Comment by weinand** [comment]
@connor4312 yes, I suggest to finalize this month.

**Comment by meganrogge** [comment]
@connor4312 how can I verify this?

**Comment by connor4312** [comment]
I suggest starting with a hello world extension, and listen for `vscode.debug.onDidStartDebugSession`. Then use `Debug: Open Link` to `https://code.visualstudio.com/`. It should emit a "root" session without a parent, and then a session for the page with the parent set. Open a new tab. This should cause additional sessions to be created, and verify they have appropriate parents set.

**Comment by weinand** [comment]
@connor4312 please make sure that this new API gets mentioned in the release notes in the "Extension authoring" section.
