### ISSUE TITLE
Regular expression find/find in files inconsistent replacement

### ISSUE THREAD

**Issue by Fexilus** [microsoft/vscode#123483]
- VS Code Version: 1.57.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create file with content `pattern`.
2. Find `(\w)[\w]+` (with regular expression turned on), replace with `\\left $1` results in `\left p` (as expected).
3. Find in files `(\w)[\w]+` (with regular expression turned on), replace with `\\left $1` results in `left p` (not expected).

![Image of find in file replacement](https://user-images.githubusercontent.com/29518918/117686806-82694280-b1b7-11eb-90f3-54d348deda1d.png)
The two replace methods should give the same results, and the results should be able to contain the string `\l`. Therefore the behavior of Find in files should be considered the bug.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This happens with L and U in particular because of this feature where you can use `\L` to lowercase a matching group, but we are matching too aggressively...
