### ISSUE TITLE
실행 시 메인 화면에 아무 화면도 나오지 않음

### ISSUE THREAD

**Issue by bullpae** [Microsoft/vscode#12341]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. vs code 실행
2. 메뉴 만 정상적으로 실행 된 후 메인 화면에는 검정 화면만 나옴
3. 재설치를 하면 정상 작동 함
4. 프로그램 종료 후 다시 시작하면 같은 현상이 반복됨

**Comment by chrmarti** [comment]
@Tyriar Could you help with what seems to be Korean? Thanks.

**Comment by Tyriar** [comment]
@bullpae you should try using the [latest insiders build (v1.6.0)](http://code.visualstudio.com/insiders) to see if that fixes the issue. If not could you provide a screenshot?
