### ISSUE TITLE
Keyboard stops responding after "Ctrl+O , Escape", 100% reproducible within 3 tries but usually on first try

### ISSUE THREAD

**Issue by codingthat** [microsoft/vscode#123443]
Issue Type: <b>Bug</b>

1. Run `codium --disable-extensions`
2. Press Ctrl+O
3. Once the "Open file" dialog appears, hit Escape to close it
4. The cursor is still blinking, but the app does not respond to keypresses (e.g. arrow keys) nor combinations (Ctrl+O, Ctrl+E, etc.).  I _can_, however, kill the app with Alt+F4, but I think that's because it's a system shortcut and does not even make it to the app.

The first ~10 times I tried this, it broke every time.  The next 2 times, it took 2 tries to break.  The next several tries it broke again on the first try.

Also of note: Despite the keyboard not working, the mouse works fine.  I can select text, right-click, copy, paste, bring up the command palette and pick options from it, switch between open files in the side pane, choose File→Open and close the resulting dialog box with its corner X, and also drag and drop text.  None of these actions cause the keyboard to start working again, though.

VS Code version: VSCodium 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-14T00:48:08.463Z)
OS version: Linux x64 5.4.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2438)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (0.37GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.9.1
local-history|xyz|1.8.1

</details>

**Comment by codingthat** [comment]
(Not sure if this is related somehow to #107078 but I could not reproduce that bug on my system, whereas the one I'm reporting here is quite reproducible for me.)

**Comment by codingthat** [comment]
Further, I just tried closing my normal workspace, then starting a blank, unsaved file, and adding a couple newlines to it just so I could tell quickly with the arrow keys whether this bug was occurring. The next 11 runs took the following numbers of "Ctrl+O, Esc" tries before the keyboard stopped working: 3, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1

**Comment by codingthat** [comment]
It also doesn't have to do with the file being unsaved.  Tried with a new blank file and the test being to type a single letter (and when I could, to immediately Ctrl+Z to go back to having a blank file without its "unsaved" marker.)  The results were 2, 1, 1, 2, 1.

**Comment by deepak1556** [comment]
Do you still experience this issue with latest stable `1.74` ?

**Comment by codingthat** [comment]
@deepak1556 Thanks for checking in.  I'm on the latest update available through vscodium.com, 1.73.1.  Now, this bug no longer occurs, but [a different one instead](https://github.com/microsoft/vscode/issues/168416).  Maybe whatever introduced this behavior is preventing this original bug from occurring?

**Comment by deepak1556** [comment]
Thanks for confirming.
