### ISSUE TITLE
Rethink the name of IOffProcessTerminalService

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#123480]
https://github.com/microsoft/vscode/pull/123339#discussion_r629314095

**Comment by Tyriar** [comment]
> Don't need to solve this within this PR, but I started calling this the "Primary" service somewhere, taking cues from the "primary extension host". This could use some thinking around naming since we have ITerminalService, ILocal/RemoteTerminalService and ILocal/RemotePtyService - "primary terminal service" is ambiguous, "primary off process terminal service" is too verbose.

**Comment by Tyriar** [comment]
Went with `primary off process terminal service` so it's as clear as possible. I think we're only using it in one place now.
