### ISSUE TITLE
Delete Key does not work while in editor

### ISSUE THREAD

**Issue by linqFR** [microsoft/vscode#123441]
Issue Type: <b>Bug</b>

On trying to delete with 'delete key' (not backspace) in editor, it suppresses the opened terminal  and keeps the focus on terminal.

And then when i close the terminal window and use 'delete' in editor, a message error pops up : "cannot use 'in' operator to search for 'instanceId' in 4 "

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.91GB free)|
|Process Argv|--crash-reporter-id 1ea437a2-73e8-43b4-b0b7-6094af97fadd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sublime-importer|auc|1.0.1
vscode-eslint|dba|2.1.20
vscode-npm-script|eg2|0.3.21
sublime-search-vscode|gar|0.0.1
sublime-keybindings|ms-|4.0.9
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
sublime-commands|Zar|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in the upcoming recovery release.
