### ISSUE TITLE
Reserve some space to the right of the hover to be able to grab the scrollbar

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#123448]
cc @bpasero

https://user-images.githubusercontent.com/5047891/117639751-8e87dc80-b184-11eb-8b55-fb6179ec4549.mp4

**Comment by bpasero** [comment]
👍 , typically I don't mind the hover going over the right hand side (esp. when editor is split and space is little). Only in this case the hover was in my way for grabbing the underlying scrollbar.

**Comment by andreamah** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/31675041/214958857-5f22930f-67dd-4a1e-93e4-0887a19e328c.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/31675041/214959086-1b50e620-922d-4f65-ac38-0bf49191d166.png">

I'm still sometimes getting the info box covering the scrollbar. I'm zoomed into the editor quite a bit and hovering on `trackInputBox` on `SearchView.ts:383` or `showSearchWithoutFolderMessage` on `SearchView.ts:398` in the vscode repo.

**Comment by aiday-mar** [comment]
Seems to be fixed now 

<img width="422" height="310" alt="Image" src="https://github.com/user-attachments/assets/a5ffe659-ca9f-48ff-bcc1-7d4f6a3c07eb" />

**Comment by anthonykim1** [comment]
<img width="519" height="157" alt="Image" src="https://github.com/user-attachments/assets/0b96f7da-ce0f-4b36-94b7-cf89484a1c81" /> @aiday-mar Not sure if Im testing this right, I still have some hover blocking the scroll bar
