### ISSUE TITLE
Emoji characters crashing Code

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/vscode#12343]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Use emojis on TSX files
2. Try to delete an emoji (sometimes Backspace inserts an unknown symbol (an ? inside a losang), most of the times, it just crashes)

Code:
```<a href="javascript:void(0)"><em>📚</em>Artigos<span className="count">3</span></a>```

Workaround:
1. Select and [delete] the emoji character

**Comment by seanmcbreen** [comment]
Thanks for reporting this we are working on a fix which was just committed - context in issue #12329 .

Closing this one as a dupe for now let us know if you see other issues.

Happy coding!
