### ISSUE TITLE
crash when repeatedly click installed extensions

### ISSUE THREAD

**Issue by fantacytyx** [Microsoft/vscode#12349]
- VSCode Version: 1.6.0-insider (commit: 0a0bfed)
- OS Version: Windows 10 x64 1607

Steps to Reproduce:
1. open vscode
2. change the window height made it larger than 900 pixels
3. switch to extension panel
4. repeatedly click `installed` extensions  in the extensions list
5. crash!

![animation](https://cloud.githubusercontent.com/assets/8966236/18735779/23fe35f0-80b3-11e6-9321-3f9bb3337346.gif)

![image](https://cloud.githubusercontent.com/assets/8966236/18735661/34a00e20-80b2-11e6-87ec-24a5b8341b1d.png)

![image](https://cloud.githubusercontent.com/assets/8966236/18735883/ffa922e0-80b3-11e6-898f-fdd1641f43b7.png)

**Comment by chrmarti** [comment]
Cannot reproduce. Are your referring to the "Show Installed Extensions" item in the menu? Or are you installing >=4 extensions? (Both worked for me.)

**Comment by fantacytyx** [comment]
![animation](https://cloud.githubusercontent.com/assets/8966236/18735026/ef23dcd2-80ac-11e6-85ed-0899713e2df1.gif)
Cannot reproduce too on my laptop which resolution ratio is 1280x768.
I found that fullscreen is not the trigger condition. application window of VSCode.
As long as the application's window height of VSCode is larger than 900 pixels this issue can reproduce.

**Comment by chrmarti** [comment]
Cannot reproduce on my larger screen. How did you determine that 900 pixels is the threshold?

**Comment by fantacytyx** [comment]
**900 pixels is only an approximate value**
900像素只是一个大概的值

Cannot reproduce on my laptop,so I think it could be a problem of resolution ratio.
我的笔记本上不能重现，我就想是否是分辨率的问题。

I tried to change the resolution ratio
我尝试修改分辨率。

I found it can reproduce when height >= 900 pixels .
我发现在高度大于等于900像素的时候能重现。

![image](https://cloud.githubusercontent.com/assets/8966236/18773039/e8bd6a80-817d-11e6-8fc4-5ff0b97f377a.png)

In this process, I accidentally found that not enter fullscreen can also reproduce.
在尝试的过程中，我意外的发现非全屏的时候也能重现问题。

I try to recreate the problem by modifying the window size.
我试着通过修改窗口大小重现问题。

Height is greater than 900 pixels  indeed  can reproduce this issue.
高度大于900像素的确能重现问题。

**Comment by joaomoreno** [comment]
@jrieken Webview, do you think?

**Comment by jrieken** [comment]
Unsure - when the web view crashes it shows a black hole in the editor but doesn't bring down VS Code. @joaomoreno You selecting different extension you reuse (setInput) the web view, right?

**Comment by joaomoreno** [comment]
Very likely not.

**Comment by joaomoreno** [comment]
Seems not valid anymore.
