### ISSUE TITLE
LiveShare disables code coloring with the latest update

### ISSUE THREAD

**Issue by aytunch** [microsoft/vscode#123477]
- VS Code Version:
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (5 days ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.1.0
- OS Version: Mac Os Big Sur
11.0.1 (20B29)

Steps to Reproduce:

1. Install Live-Share plugin.
2. Join a session (as a participant, not as the host)
3. You will see the code being shared as white text. The ide does not colorize the code while in a liveshare session as a participant.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JacksonKearl** [comment]
Do you see a language mode selected in the status bar as the participant?

**Comment by aytunch** [comment]
@JacksonKearl sorry for the late reply
this issue is still present
as for your question this is what I see in my status bar
<img width="446" alt="Screen Shot 2021-05-19 at 00 01 02" src="https://user-images.githubusercontent.com/6442915/118722925-6ad42e80-b835-11eb-9bee-06fd50bf7b49.png">
