### ISSUE TITLE
'vscode': '>=1.48.0 <1.56.0' is not a valid "engines" entry in package.json

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#123409]
Enable 'engines' in the Manifest (package.json) to accept this entry `"vscode": ">=1.48.0 <1.56.0"`

As described here https://stackoverflow.com/questions/51596127/node-engine-8-x-or-10-x-in-package-json

 ````json
"engines": {
    "vscode": ">=1.48.0 <1.56.0"
  },
```` 

should be a valid entry on the package.xml. But VSCode is not parsing it.

![Screenshot 2021-05-09 at 18 10 52](https://user-images.githubusercontent.com/55927613/117580901-0d800500-b0f2-11eb-92a4-d4e82b9ee6b4.png)

**Comment by ArturoDent** [comment]
Looking at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility I only see support for the `^` syntax (as your error message seems to indicate as well).

**Comment by alexdima** [comment]
We currently only support the `^1.48.0`, `>=1.48.0` and `1.48.x` syntax. What exactly is the use case you have where you would need such a syntax? Is your extension offering support for older versions of VS Code? If yes, then why? The VS Code team only supports the latest stable version.

**Comment by urvapatel** [comment]
@alexdima I was having a problem similar to this. I needed my extension to only support between version 1.41 and up, but below 1.56. This is because in April, the latest version 1.56.1 and up would cause our extension to not work.

**Comment by AllanOricil** [comment]
@alexdima my extension stopped to work on 1.56. I did everything I could to help your team to identify and fix the bug, but nothing was done. After a month waiting for a solution, I just gave up and decided to stop supporting to my extension.

https://github.com/microsoft/vscode/issues/123281
