### ISSUE TITLE
HTML Run without debugging

### ISSUE THREAD

**Issue by ralphleask** [microsoft/vscode#123467]
Issue Type: <b>Bug</b>

Tried to execute "Run without debugging" from Run menu with focus on an HTML module.  Received message, "You don't have an extension for debugging HTML.  Should we find an HTML extension in the Marketplace?".

This started after the latest update (1.56.0) and was working perfectly before.  I do not understand why I would need an extension for debugging if I am asking to run w/o debugging.  

If I select find HTML extension it comes up with a list of extension but see nothing that relates.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.23GB free)|
|Process Argv|--crash-reporter-id 7d011a4f-0129-4652-a44f-27548341bd23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.5
vscode-firefox-debug|fir|2.9.4
sandbox|jcc|1.0.1
sftp|lix|1.12.9
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
cors-browser|Wsc|1.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123106
