### ISSUE TITLE
Green background on file explorer 

### ISSUE THREAD

**Issue by superchrisho** [microsoft/vscode#123422]
Issue Type: <b>Bug</b>

When exploring a tree, some directories will cause a green background to appear that obscures text of tree directory

VS Code version: Code 1.56.0 (Universal) (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|--crash-reporter-id a528d53f-ca2c-42fc-aca5-edf2ad800627|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.2
markdown-preview-github-styles|bie|0.2.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-html-css|ecm|1.10.2
vscode-great-icons|emm|2.1.73
prettier-vscode|esb|6.3.2
nasc-touchbar|fel|1.12.0
auto-rename-tag|for|0.1.6
vscode-styled-components|jpo|1.5.2
markdown-shortcuts|mdi|0.12.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
vscode-react-native|msj|1.4.2
color-highlight|nau|2.3.0
vscode-json-editor|nic|0.3.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.6.0
java|red|0.79.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.2
svg-preview|Sim|2.8.3
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vscode-icons|vsc|11.4.0
vscode-css-variables|vun|1.4.3
codesandbox|yes|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353
bridgeflightcf:30299255

```

</details>

**Comment by isidorn** [comment]
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by superchrisho** [comment]
Tried fixes were restarting vscode, trying other repos/folders.(didn’t fix)
It gets triggered by some file icon themes like material. Goes away when I change the icon theme to “simpler” looking themes.

The issue is also mysteriously gone now. I can’t seem to bring it back. Not sure how it got fixed.


On 10 May 2021, at 3:06 PM, Isidor Nikolic ***@***.******@***.***>> wrote:



I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
