### ISSUE TITLE
Chrome and edge debugger should be interested in CSS language

### ISSUE THREAD

**Issue by kyoichishido** [microsoft/vscode#123484]
Run any file for example .css or .html using Live server extension, then it'll prompt asking me to install the debugger for that specific file I run, for example "Install CSS debugger" "Install HTML debugger"

Even I installed those extensions it is still showing me the prompt. I tried reinstalling Visual Code but problem persists

**Comment by alexr00** [comment]
> it'll prompt asking me to install the debugger for that specific file I run, for example "Install CSS debugger" "Install HTML debugger"

I can't get this to happen in stable. Are there any additional steps besides installing Liver Server, opening a css file, and going live?

**Comment by connor4312** [comment]
1. Open a CSS file in a workspace without any launch configs set up
2. Hit F5

**Comment by isidorn** [comment]
Works as expected -> verified
![Screenshot 2021-06-07 at 20 06 57](https://user-images.githubusercontent.com/1926584/121067922-ec333700-c7cb-11eb-9aa5-dde43d10ae3f.png)
