### ISSUE TITLE
search within all opened files

### ISSUE THREAD

**Issue by sy19890515** [microsoft/vscode#123425]
sometimes I open multiple files and each of them may locate in different directories, let's say I open file a1 from directory A, file b1 from directory B, etc. A and B each contains 5 files but I only need to motify one in each directory. It's difficult to specify which files I want to exclude or include. That's when "search within all opened files" comes in handy.

**Comment by roblourens** [comment]
This feature exists, see the button in the "files to include" box

**Comment by sy19890515** [comment]
> This feature exists, see the button in the "files to include" box

But I will have to specifically state the files' names, sometimes the names may not have a pattern.

**Comment by roblourens** [comment]
👉 The button 👈  😁

**Comment by sy19890515** [comment]
> 👉 The button 👈 😁

Oh I just saw the button, thanks!
