### ISSUE TITLE
I'm not able to debug

### ISSUE THREAD

**Issue by Khami-J** [microsoft/vscode#123418]
Issue Type: <b>Performance Issue</b>

I click debug and it tells me i need to download an extension and I've downloaded them but all I keep getting is a message saying to download an extension.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.99GB free)|
|Process Argv|--crash-reporter-id d7df8e83-b40a-465e-bcfc-af329bba6220|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   116	 15120	code main
    0	    24	  9068	   crashpad-handler
    0	   185	 10656	   window (table.html - Visual Studio Code)
    0	   263	  3800	     extensionHost
    0	    68	 12952	       "C:\Users\miahj\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\miahj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3800
    0	    88	 17904	       "C:\Users\miahj\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\miahj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3800
    0	    43	 12568	   utility
    0	   150	 19020	   gpu-process
    0	    84	 19320	   shared-process
    0	    61	 24008	     ptyHost
    0	    79	 21188	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.5
vscode-firefox-debug|fir|2.9.4
go|gol|0.24.2
live-html-previewer|hdg|0.3.0
elixir-ls|Jak|0.7.0
vscode-edge-devtools|ms-|1.1.8
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
LiveServer|rit|5.6.1
cors-browser|Wsc|1.0.11
eno|Wsc|2.3.53

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352
bridgeflight:30299254

```

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123106
Will be fixed soon. Thanks
