### ISSUE TITLE
unable to  open file in current window

### ISSUE THREAD

**Issue by sowillwe** [microsoft/vscode#123435]
After the last upgrade (Version:1.56.0),  when I type

```
code t.txt
```
in integrated terminal (WSL1 bash), most time it opens a new window while the `Window: Open Files In New Window` option is `off` or `default`.

Then I tried
```
code --reuse-window t.txt
```
Still got a new window.

The trouble is that's random - the setting sometimes works sometimes not. Reboot VS Code or switch between the modes (reopen in WSL or reopne in Windows, the actions provided by remote-WSL extensioni) seldom helps.  Reboot Win10 seems to change nothing. So I can hardly tell which operations may result in this. (._.)

**Comment by sowillwe** [comment]
@aeschli Emm... VS Code and WSL are both on Local Win10. The integrated terminal (which uses bash when remote-WSL installed and in "open X in WSL" mode) is the one in the local VS Code. No second physical host here.

**Comment by aeschli** [comment]
I meant whether you are in a WSL window (remote indicator in the lower left corner says `WSL`)
Something like that:
![image](https://user-images.githubusercontent.com/6461412/117978284-00515900-b332-11eb-91c7-ef1ea11b5d40.png)

**Comment by sowillwe** [comment]
@aeschli Yes. The bug occurs only in the remote window. 
And recently I found in the accidentally opened new remote window, `code t.txt` will not start a new window again.  Also, start VS Code directly in WSL (i.e. Ctrl + R to run WSL in Win10, then type `code`) works fine.
i.e. The issue only occurs when VS Code is started directly in Win10 and in the remote window.

**Comment by sowillwe** [comment]
@aeschli

>  Also, start VS Code directly in WSL (i.e. Ctrl + R to run WSL in Win10, then type code) works fine.

This is not always true.

The only solution I found to avoid more extra new windows is to use the opened new window.  And this only works for a limited period.  Say I put VS Code aside without any operation for hours, then `code --reuse-window t.txt`  will still bring me a new window.

**Comment by sowillwe** [comment]
Well, reinstalling WSL or reinstalling VS Code helps nothing.
What finally saved me is simply to remove `C:\Users\i\AppData\Roaming\Code`. 
Still thought it a strange bug <@_@>. (accidental interference in VS Code cache, perhaps.)
