### ISSUE TITLE
It Crashed

### ISSUE THREAD

**Issue by chuoke** [Microsoft/vscode#12348]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
I don't know why VScode usually fucked up, maybe I open too many files.

**Comment by srinivashappy** [comment]
Please provide more information and screenshots.

**Comment by Bill-Stewart** [comment]
Please refrain from the vulgar language; thanks.

**Comment by chuoke** [comment]
sorry for my words and slight. 
I like VScode,but it usually crash. Main issue is that the editable area can't be  edit even click and no reaction. I have to closed it and reopen. The menu is normal.

**Comment by chrmarti** [comment]
@chuoke What are the extensions you have installed? What kind of files does it crash with? Any specific kinds of actions after which it crashes?

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
