### ISSUE TITLE
New files not getting jsconfig

### ISSUE THREAD

**Issue by ricmed205** [Microsoft/vscode#1234]
When I create a new file, it does not recognize the jsconfig settings (ES6 for example). I need to go to jsconfig, make a change, dismake that change and then it the new file will be ok.

**Comment by jrieken** [comment]
@ricmed205 Any chance you file starts with `temp` or contains `js`?

**Comment by ricmed205** [comment]
I've only used .js files so far

**Comment by jrieken** [comment]
no, I meat the path, like `/coding/js/myfile.js` or `/coding/templateController.js`. Then it would be like #703 which collects a few file patterns that we have filed to understand

**Comment by ricmed205** [comment]
no, my paths are not like that. The only "special" thing in my case is that contain folder names with spaces. EG "Google Drive".

**Comment by jrieken** [comment]
and _Node**Js**_ ;-) That's what I meant, sorry if I wasn't clear enough. Closing as Duplication of #703.
