### ISSUE TITLE
check upgrade

### ISSUE THREAD

**Issue by shinestmt** [Microsoft/vscode#12347]
- VSCode Version:1.3.1
- OS Version:Win7

Steps to Reproduce:

I need "check upgrade"!

**Comment by seanmcbreen** [comment]
In Win 7 you should see this option to check:
![image](https://cloud.githubusercontent.com/assets/1051190/18695444/a7992436-7f66-11e6-804c-d622c4c64a16.png)

Closing for now but re-open if this does not help.
