### ISSUE TITLE
[Chrome OS] Huge taskbar thumbnail

### ISSUE THREAD

**Issue by mqzabin** [microsoft/vscode#123472]
**- VS Code Version:**
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.99-12983-g8b7876ab9f5e

**- OS Version:**
Chrome OS - Version 90.0.4430.100 (Official Build) (64-bit)
Crostini - Debian Buster

**- Steps to Reproduce:**
1. Install VSCode via .deb package (from vscode main website).
2. Run 2 or more VSCode instances.
3. Click on taskbar VSCode icon.
4. See a [huge thumbnail](https://imgur.com/a/fqXXwJc).

**Does this issue occur when all extensions are disabled?:** Yes

**- Description**
This started to happen on v1.56.0.

**- Question**
Should I fill a bug on Chromium OS issue tracker, or its on VSCode side only?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/122862
