### ISSUE TITLE
Default profile doesn't apply to tasks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123479]
From @alumni in https://github.com/microsoft/vscode/issues/96732#issuecomment-836798731

One more thing, after the addition of shell profiles. Currently I have the following setting:
```json
"terminal.integrated.defaultProfile.windows": "Git Bash",
```
However, NPM scripts are still running with PowerShell. I'm looking forward for this `automationProfile` to be added, but it would also be nice if `defaultProfile` would work if `automationProfile` is not set.

**Comment by capc0** [comment]
Im using ```"terminal.integrated.automationShell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"``` .  works for me.

**Comment by andrew-r-king** [comment]
Ah, so it was just renamed. Thanks!

**Comment by alumni** [comment]
Well, `automationShell` is the old setting which is deprecated (so not autocompleted) and there's no option for shell args.
If you want to use it, try not to mix it with `defaultProfile`.
If you need to customize how tasks are launched (my today's discovery includes version control too 🤦🏻😄), the best thing for now is to use the deprecated `shell` options until profiles will fully replace them.
