### ISSUE TITLE
Pin/Unpin tabs bug on drag 

### ISSUE THREAD

**Issue by HackAsh96** [microsoft/vscode#123465]
![pin_unpin](https://user-images.githubusercontent.com/42658291/117653825-31e0ed80-b195-11eb-9244-024ce134acca.gif)

- VS Code Version: 1.55.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.Pin a file on Tab and open another file without pinning it 
2. Drag the unpinned file before the pinned file, the unpinned file will be pinned automatically 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by HackAsh96** [comment]
Maybe need more infos cause it is not well explained. Is it relevant anyway ? To have files that you pin by dragging in the area of pinned tab(s), and how can we defined an area of a pinned tab? @bpasero

**Comment by bpasero** [comment]
Any suggestions?

**Comment by bpasero** [comment]
@HackAsh96 that exists as themable color, you can change it in settings: `tab.lastPinnedBorder` in `workbench.colorCustomizations`
