### ISSUE TITLE
Event utils leakage

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#123487]
We have a bunch of event-utils which internally create an Emitter. These emitters are never disposed and are therefore leaking. The following can use

* "owner" creates an event
* consumer subscribes to event and never disposes it
* owner is being disposed
* event listener is still there and leaks whatever is "connected" to the emitter

---

* [x] [domEvent](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/browser/event.ts#L15)
* [ ] [snapshot](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L112-L112)
* [x] [debounce](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L137-L137) - use `debouncedListener` or `DebounceEmitter` instead
* [ ] [buffer](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L225-L225)
* [ ] [fromNodeEventEmitter](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L335-L335)
* [ ] [fromDOMEventEmitter](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L349-L349)
* [x] [fromPromise](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/event.ts#L358-L358)

**Comment by joaomoreno** [comment]
@jrieken What do you think? https://github.com/microsoft/vscode/commit/4ed31ca457fc65eff6d0b51c686f703bd1b40c00

**Comment by jrieken** [comment]
Yeah, I like. Tho, I am afraid that `Emitter#dispose` isn't calling `onLastListenerRemove`. Tho, that should be an easy fix, let me how it goes

**Comment by joaomoreno** [comment]
Oh I just assumed that would work. Yeah let's do that.

**Comment by joaomoreno** [comment]
I have removed all usages of `domEvent` and replaced them with:

- `addDisposableListener`, whenever no events were really needed
- `DomEmitter`, whenever some event logic was in use

**Comment by connor4312** [comment]
Interesting. Let me know if you want help, I've worked a lot on [rxjs](https://rxjs.dev) which has similar semantics and requirements in its subscribers and observers.
