### ISSUE TITLE
Show a splash screen

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/vscode#123416]
So I thought about this feature because today I installed VS Code on my not so old Raspberry Pi 3B+ and it took almost 5sec for VS window to appear. Since on many other platforms this process usually takes less than 2sec I first thought that VS Code was not launching at all. 

Since start-up time can vary a lot between OS/platforms/computers I think it would be great if there was some kind of splash screen, just to inform the user that VS code is starting. This splash screen could be like a *message* which basically means (but not say) *hey we know you asked VS code to start, just give us a couple of seconds*.

Splash screen would be something similar to what we see for Microsoft Office's apps or like Android Studio or even like Arduino

**Comment by misolori** [comment]
Thanks for the suggestion. We've received similar requests in the past (#87309) and we don't have any intention on introducing this so I'll close this as out of scope.
