### ISSUE TITLE
fatal error: format: No such file or directory

### ISSUE THREAD

**Issue by HerClau** [microsoft/vscode#123461]
We
Issue Type: <b>Performance Issue</b>

3D_Data_2.cpp:3:10: fatal error: format: No such file or directory
    3 | #include <format>
      |          ^~~~~~~~

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.75GB free)|
|Process Argv|--crash-reporter-id a7784d60-886f-4cdf-ace9-54ad361b7c25|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	  7196	code main
    0	   149	   304	   gpu-process
    0	   188	   804	   window (3D_Data_2.cpp - helloworld - Visual Studio Code)
    0	   181	  4628	     extensionHost
    0	    21	 14516	       c:\Users\Hermesr\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\12.0.0\clangd_12.0.0\bin\clangd.exe
    0	    10	 10828	         console-window-host (Windows internal process)
    0	    32	 10072	     searchService
    0	    14	 15872	     watcherService 
    0	    10	 11176	       console-window-host (Windows internal process)
    0	    27	  2636	   utility
    0	    47	 12660	   window (Issue Reporter)
    0	    22	 12812	   utility
    0	    70	 14452	   shared-process
    0	    31	  2092	     ptyHost
    0	     6	  7712	       winpty-process
    0	     9	   940	         console-window-host (Windows internal process)
    0	    68	  3336	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	  8936	       winpty-process
    0	     9	  7756	         console-window-host (Windows internal process)
    0	    63	  8116	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    14	 15644	   crashpad-handler
```

</details>

 have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by JacksonKearl** [comment]
\extC++
