### ISSUE TITLE
No C# support even with C# extension installed

### ISSUE THREAD

**Issue by josalem** [Microsoft/vscode#12340]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

VSCode has stopped listing C# as an available language.  It opens all *.cs files as plain text and C# is not selectable as a file type.  I have the C# extension installed. I have attempted uninstalling and reinstalling the current extension, VSCode in its entirety, and the legacy C# extension.

Steps to Reproduce:
1. Have C# extension installed
2. `dotnet new` a new project
3. Open `Program.cs` from Explorer or via `code .` in the directory or `code Program.cs`

![image](https://cloud.githubusercontent.com/assets/20667293/18691631/a47fe978-7f49-11e6-9c77-846513000a47.png)

**Comment by chrmarti** [comment]
Tried and it works for me. I have only the current C# extension installed, not the legacy one.

Could you check the console in the dev tools (Help > Toggle Dev Tools) for errors/hints?

**Comment by josalem** [comment]
I am getting two errors concerning the thread service and extension service:
![image](https://cloud.githubusercontent.com/assets/20667293/18718377/1b50a400-7fd8-11e6-8da6-d40fa5454672.png)

`mainThreadExtensionService.ts`
![image](https://cloud.githubusercontent.com/assets/20667293/18718392/2a74eb12-7fd8-11e6-9f0d-0a7491b1d9d3.png)

`threadService.ts`
![image](https://cloud.githubusercontent.com/assets/20667293/18718408/3aacb5d2-7fd8-11e6-9aee-73068654aef4.png)

**Comment by josalem** [comment]
Fixed.

I forced VSCode to re-download and reinstall all my extensions by `rm *`-ing inside the `.vscode` directory in my user directory.  I then reinstalled the extensions and they worked correctly.

**Comment by chrmarti** [comment]
@joaomoreno Anything we can do here? Maybe improve the logging?

**Comment by josalem** [comment]
For the record, those error messages were no longer present after I cleared `.vscode/extensions`.

**Comment by joaomoreno** [comment]
Yeah @chrmarti logging is definitely something we need to tackle together pretty soon.

**Comment by ramya-rao-a** [comment]
Clearing the "bug" label as there is nothing to verify
