### ISSUE TITLE
Always "Add folder to workspace" Drag And Drop

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#123413]
When a folder is dragged from Windows Explorer to the `VSCode \ Editor`, its auto-opened as Workspace, that removes need in the pop-up dialog when its dragged to `VSCode \ Sidebar \ Folders` . Please do or add a setting to disable the dialog .

**Comment by isidorn** [comment]
This is a fair request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
