### ISSUE TITLE
RemoteHub: Continue On does not check if git is existing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#123492]
I have a brand new Windows install

- Open a repo using RemoteHub
- Run `Continue On: Clone Repository Locally`
- Nothing happens

Looking in the Dev Tools Console I realize that I don't yet Git installed

-> should show an error message

Or even, deluxe, let me open the Git webpage.

**Comment by joyceerhl** [comment]
@lszomoru Is this something that would be handled in the `git` extension since that contributes the clone command?

**Comment by lszomoru** [comment]
@joyceerhl, yes, that makes sense to me since there is already code that handles the detection of git in the `git` extension.

**Comment by joyceerhl** [comment]
Today Continue On > clone locally still silently errors out if git is missing. Talked with @digitarald this morning, he mentioned 
- Ideally we have a one click in-product install for git: https://github.com/microsoft/vscode/issues/136408
- Missing git should not be a no-op

At minimum I think we could show a dialog with a link to https://aka.ms/vscode-install-git 

https://github.com/microsoft/vscode/blob/59942f7d9604f965f2523bd7c4a8aa073da7afaf/src/vs/workbench/contrib/welcomeGettingStarted/common/gettingStartedContent.ts#L473

**Comment by joyceerhl** [comment]
The reason for this happening is that the git uri handler and most git commands are not even registered if git is missing on extension activation https://github.com/microsoft/vscode/blob/8c254bbf3e9ff5e6196d3093183252b30f909d33/extensions/git/src/main.ts#L206-L208

So the window receives focus on the protocol handler invocation but of course nothing is available to handle the uri. I opened a PR to fix this in the git uri handler specifically: https://github.com/microsoft/vscode/pull/159505

**Comment by aeschli** [comment]
I still see the problem. Nothing happens after `Clone Repository Locally and Open on Desktop`
(Remote Repositories v0.21.2022092801)


Dev tools show:

console.ts:137 [Extension Host] Git installation not found. (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: command '_codespaces.setActiveRepository' not found (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
console.ts:137 [Extension Host] stack trace: Error: command '_codespaces.setActiveRepository' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3532)
    at S.executeCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3414) (at console.<anonymous> (/home/aeschli/Downloads/code-insider-x64-1664343998/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:142292))
log.ts:313   ERR command '_codespaces.setActiveRepository' not found: Error: command '_codespaces.setActiveRepository' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3532)
    at S.executeCommand (vscode-file://vscode-app/home/aeschli/Downloads/code-insider-x64-1664343998…nux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:3414)

**Comment by joyceerhl** [comment]
@aeschli question about your setup, are you connected to a Linux remote in this case?

**Comment by joyceerhl** [comment]
This works as expected for me on a clean Windows VM with no git installed: 

![image](https://user-images.githubusercontent.com/30305945/192850352-dbeb7fe5-2d70-430a-b21b-24c81a380022.png)

**Comment by aeschli** [comment]
I tested on Linux and to test, I renamed the git symbolic link: `sudo mv /usr/bin/git /usr/bin/git2`

**Comment by joyceerhl** [comment]
Marking this issue (specifically from web to desktop) as verified based on https://github.com/microsoft/vscode/issues/162235#issuecomment-1261419680.
