### ISSUE TITLE
Suggest switching off TSServer Trace Logs if left on for a long time

### ISSUE THREAD

**Issue by EdNutting** [microsoft/vscode#123493]
If TS Server crashes 5 times, VSCode has a nice popup that suggests some action, which includes automatically turning on TSServer Trace Logs. It's very easy to forget that this option is on (or even be unaware that it was switched on at all) and very hard to diagnose the resulting performance problem in the wider IDE ("intellisense gradually gets slower over time" is difficult to diagnose down to an option you didn't know exists and that's cause by accumulating GiB of log files).

I would like that if the TSServer Enable Trace flag has been on for more than 7 days, VSCode once a week suggests turning it off. For the vast majority of users, this is likely to help them. For the small number of people who really do need this flag on all the time, a once a week popup won't hurt (or they can have some option to permanently turn off the reminder).

This would have avoided my month-long headache that eventually culminated in #123446 (and was only resolved when I used WinDirStat to find out why my system drive was full).

See also: https://twitter.com/orta/status/1391757821017010176?s=20

**Comment by EdNutting** [comment]
@nrayburn-tech / @mjbvz  Wonderful! The code changes look good from my "outsider's view". Thank you so much, this is great!

**Comment by alexr00** [comment]
I probably had logging on for 6+ months and didn't know until this feature told me.
