### ISSUE TITLE
Setting undo stops for `TextEditor.edit` doesn't work if a cursor has moved between edit

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [microsoft/vscode#123485]
- VS Code Version: 1.57 (latest Insider)
- OS Version: MacOS 11.3.1

I try to get multiple calls to `TextEditor.edit` to be treated as a single operation for undo. However, if the cursor has moved between those edits it seems that `undoStopBefore` and `undoStopAfter` settings are ignored, and there will be still an undo stop in between the edtis. 

Steps to Reproduce:

1.  Clone https://github.com/Krzysztof-Cieslak/vscode-undo-issue, open it in VSCode, and press F5 to run the extension in debug mode
2. Write anything in the first line
3. Run the `Hello World` command and observe text edits happening in the editor.
4. Try to undo operations and observe how there are undo stops in between edits despite setting `undoStopBefore` and `undoStopAfter` to false on the API calls.

![2021-05-10 18 09 44](https://user-images.githubusercontent.com/5427083/117690314-007b1880-b1bb-11eb-9b12-c4b61ed8b7a9.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@Krzysztof-Cieslak I will close this for now.
