### ISSUE TITLE
[Wayland] VSCode stops responding mouse/keyboard interactions after short range drag 'n drop (with video)

### ISSUE THREAD

**Issue by mqzabin** [microsoft/vscode#123470]
**- VS Code Version:**
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.99-12983-g8b7876ab9f5e

**- OS Version:**
Chrome OS - Version 90.0.4430.100 (Official Build) (64-bit)
Crostini - Debian Buster

**- Steps to Reproduce:**
1. Install VSCode via .deb package (from vscode main website).
2. Run it with `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags to enable Wayland protocol.
3. Do a "short and fast" drag n drop on explorer or tabs. (i.e. a slightly longer "normal click", with a short mouse movement while button is pressed)
4. Every mouse/keyboard interaction stops responding. Close and reopen VSCode is the only workaround.

**Does this issue occur when all extensions are disabled?:** Yes

**- Description**
I made [this video](https://youtu.be/dE437JeyBSk) to show the bug. Until 0:14 I checked that everything was working (including "longer" drag n drops), then I forced the bug doing a "short range" drag 'n drop (as described on "steps to reproduce") in a explorer file. After that, VSCode stoped responding to mouse and keyboard interactions (I was typing and clicking everything like crazy after 0:15).

Running it with `--verbose --log=TRACE` flags shows nothing new when the bug occurs. 
 
**- Important:** VSCode itself is not freezed, e.g. if I run a web server on terminal, it keeps responding and showing requests logs normally.

**Comment by major-mayer** [comment]
I got exactly the same issue using Manjaro Linux +  Gnome + Wayland. 
This occurs rarely but when it does I always have to completely restart VSCode.

**Comment by rei-yesreally** [comment]
Same thing is happening to me, using Kubuntu 21.04, KDE Plasma 5.21.4 + Wayland

**Comment by deepak1556** [comment]
This should be addressed with latest stable `1.74` using Electron 19.
