### ISSUE TITLE
Errors are not showing on the problems panel

### ISSUE THREAD

**Issue by SahilRaza79656** [microsoft/vscode#123412]
Issue Type: <b>Feature Request</b>

errors are not showing on the problem panel even if there are errors in the program.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by ArturoDent** [comment]
You should give a example of code that should produce an error but does not.  And did you try disabling all extensions?
