### ISSUE TITLE
Version 1.56.0 causes AREPL not to display icons anymore. 

### ISSUE THREAD

**Issue by ozippo** [microsoft/vscode#123402]
Issue Type: <b>Bug</b>

Version 1.56.0 causes AREPL not to display icons anymore. Version 1.55 does not have this problem.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.2
sftp|lix|1.12.9
vscode-language-pack-zh-hans|MS-|1.56.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.811652604
autodocstring|njp|0.5.4

</details>

**Comment by gjsjohnmurray** [comment]
/gifPlease

Maybe #123041

**Comment by kt-unzner** [comment]
Maybe related to this? https://github.com/microsoft/vscode/issues/123475

**Comment by ozippo** [comment]
Yes ，it is same。

发送自 Windows 10 版邮件应用

发件人: Hans Unzner
发送时间: 2021年5月10日 下午 9:56
收件人: microsoft/vscode
抄送: ozippo; Author
主题: Re: [microsoft/vscode] Version 1.56.0 causes AREPL not to displayicons anymore. (#123402)

Maybe related to this? #123475

**Comment by ozippo** [comment]
The problem is no longer exists. thanks.
