### ISSUE TITLE
Cannot drop a *. ply file into the window

### ISSUE THREAD

**Issue by christian-rauch** [microsoft/vscode#123496]
Issue Type: <b>Bug</b>

1. extract `tracks.ply` from [tracks.zip](https://github.com/microsoft/vscode/files/6454270/tracks.zip)
2. drag&drop file into vscode

I am getting the error: `Unable to open 'tracks.ply': P.overwrite is not a function.`

Does this issue occur when all extensions are disabled?: Yes

However, I can open the file via the the `Open File...` menu (Ctrl + O).

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 5.8.0-50-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 3707)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 4|
|Memory (System)|15.28GB (0.32GB free)|
|Process Argv|--disable-extensions --no-sandbox --crash-reporter-id 95b86372-ef65-41ed-9cdd-8712129452ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by bpasero** [comment]
Strange I cannot reproduce that. Do you have specific settings that could explain this? Does it reproduce if you try from a `code --user-data-dir <some empty folder>` run with fresh settings?

**Comment by christian-rauch** [comment]
With a fresh user session `code --user-data-dir /tmp/blaaaaa` it opens straight into the 3D viewer and does not show this error.

Is there a way I can provide a backtrace that shows the call graph for this `P.overwrite` function?

**Comment by christian-rauch** [comment]
This shouldn't be related to any extension, since this also happens with `code --disable-extensions`.

**Comment by christian-rauch** [comment]
Could you point me to where I can get the full stack trace via the devtools?

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment]
@christian-rauch 

Can you attach the contents of your settings file as JSON?

**Comment by christian-rauch** [comment]
My `~/.config/Code/User/settings.json`: [settings.zip](https://github.com/microsoft/vscode/files/6465111/settings.zip)

I guess the related bit is:
```json
{
    "viewType": "default",
    "filenamePattern": "*.ply"
},
```

**Comment by christian-rauch** [comment]
I installed the insider build and replaced the `settings.json` with:
```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.ply"
        },
    ],
}
```
and the problem shows up.

So this part of the settings is causing the issue with drag&drop-ing PLY files.

**Comment by bpasero** [comment]
@lramos15 take note of [commit](https://github.com/microsoft/vscode/commit/3c6377db03084e199cb60ddfdf5847f072746be7), we were passing untyped `IEditorOptions` to the group but internally expect `EditorOptions`. This is a bad typing issue that I can look to cleanup in debt week, I think we should drop the `EditorOptions` and `TextEditorOptions` classes entirely and only allow object bags as options without methods.

**Comment by christian-rauch** [comment]
@bpasero Thank you very much for considering and solving my edge case :-)

**Comment by lramos15** [comment]
@bpasero Nice catch, yeah this isn't the first issue we've had due to there being instanceof checks on the options and not allowing arbitrary objects.

**Comment by christian-rauch** [comment]
I tested with:
```
$ code-insiders --version
1.57.0-insider
4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
```
and configuration file: `~/.config/Code\ -\ Insiders/User/settings.json`:
```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.ply"
        },
    ],
}
```
and it asked me if I want to trust this file but then opened it.

However, after closing the window the configuration file changed to:
```json
{
    "workbench.editorAssociations": {
        "*.ply": "default"
    },
}
```

So I am not really sure if the commit fixed the issue or the changed configuration format prevented the bug.

But in any case, the new version lets me open ply files via drag&drop again.

/verified
