### ISSUE TITLE
[Getting Started] Reset Getting Started to correct state when opening workspace

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#123525]
**STR:**
1. Open an empty VS Code
2. Open a project from the _Getting Started / Setup_ flow using the last step

Another STR that should work for this would be the C++ extension, also prompting the user to open a C++ projoct folder.

**AR:** Re-opens _Getting Started / Setup_, but with first step selected.

**ER:** Select the last used step.

The STR also depends on the _Open your project folder_ from a `when` to a `doneOn` after #122570 lands; so it doesn't just go away after being triggered.

**Comment by alexweininger** [comment]
+1 for this feature. It would help us create a better walkthrough for the Azure Static Web Apps extension microsoft/vscode-azurestaticwebapps#397

**Comment by alexr00** [comment]
I verified by:

1. Open a folder in VS Code
2. Open the Help: Welcome view
3. Open a walkthrough and do a few steps
4. Close folder
5. Open the Help: Welcome view
6. From there, open the same folder I was just in from the Recents list
7. Open the Help: Welcome view
8. Open the same walkthrough from step 3
9. See that it has the same task I stopped on selected.
