### ISSUE TITLE
Unable to start Edge debugging session

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#123573]
Issue Type: <b>Bug</b>

I added a `launch.json` to my project with the following contents:

```json
{
  "configurations": [
    {
      "name": "Launch Edge",
      "request": "launch",
      "type": "pwa-msedge",
      "url": "http://localhost:8100",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

When I try to execute this configuration, Edge opens a blank page (with a popover telling me it closed unexpectedly). A short while after, Code will display a message box telling me:

```
[Window Title]
Visual Studio Code

[Content]
Unable to launch browser: "Timed out waiting for browser connection"

[Open launch.json] [Cancel]
```

As I've never used this feature before, I'm not sure what to expect, but I somewhat expected that Edge would be opened with a tab pointing to my specified URL.

I tried to switch to Chrome instead, but that results in seemingly identical behavior.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (37.92GB free)|
|Process Argv|--crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (38.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (38.56GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.16
terraform|has|2.10.2
vscode-esformatter|how|1.6.0
vscode-docker|ms-|1.12.1
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.811652604
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.32
vscode-yaml|red|0.18.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/1658949/117826447-755c5a00-b270-11eb-8e48-8facbd68eedd.png)

**Comment by oliversalzburg** [comment]
@connor4312 When I create these traces, the resulting archive will be corrupt.
```shell
╭─ ~/.vscode-server/data/logs/20210513T115731/exthost2/ms-vscode.js-debug ────────────────── ✔  system   12:02:57
╰─ gunzip vscode-debugadapter-7374b819.json.gz

gzip: vscode-debugadapter-7374b819.json.gz: unexpected end of file
```

**Comment by lucasyvas** [comment]
This is also happening to me on Big Sur with the latest Edge. Takes a few tries before it finally launches the instance and connects. Type `chrome` is fine.

**Comment by oliversalzburg** [comment]
The behavior changed. Now Edge opens and closes instantly. No feedback at all in Code itself.

**Comment by lucasyvas** [comment]
I'll upload mine if it helps too. When I try to launch it, it also hangs my entire machine :/

[vscode-debugadapter-7da2d52b.json.gz](https://github.com/microsoft/vscode/files/7138111/vscode-debugadapter-7da2d52b.json.gz)
