### ISSUE TITLE
VS Code insider is too slow after recent update

### ISSUE THREAD

**Issue by ocdex** [microsoft/vscode#123535]
Issue Type: <b>Bug</b>

Even clicks and typing is so slow that I can type ast and sit and watch it completing in few more seconds.

VS Code version: Code - Insiders 1.57.0-insider (54d33cf14cf6c0e86880b5b74a5a3628de42bce9, 2021-05-10T05:15:52.500Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.30GB free)|
|Process Argv|--crash-reporter-id 99747308-95f7-490b-ba6e-97326309214e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|Memory (System)|2.98GB (2.25GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
better-cpp-syntax|jef|1.15.5
tmux|mal|0.1.0
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.12
compulim-vscode-dictionary|Com|0.0.5
doxdocgen|csc|1.2.2
vscode-markdownlint|Dav|0.40.4
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
code-runner|for|0.11.3
shell-format|fox|7.1.0
vscode-pull-request-github|Git|0.26.0
go|gol|0.24.2
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.5
nbpreviewer|jit|1.2.2
vscode-kubernetes-tools|ms-|1.3.2
gather|ms-|2021.4.0
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.828932339
cmake-tools|ms-|1.7.2
cpptools|ms-|1.4.0-insiders
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.6.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
vscode-yaml|red|0.18.0
rust|rus|0.7.8
vscode-rustfmt|sta|0.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.13
clang-format|xav|1.9.0
dictionary-completion|yzh|1.1.0
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2ct:30286873
vscorehov:30295781

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the Start Extension Bisect command identify any of your extensions as a cause?

**Comment by Anushka11a** [comment]
I have downloaded vs code yesterday for first time and after  typing is so slow that I can type  and sit and watch it completing in few more seconds. even after clicking on files, edit tabs it take a lot of time to open

**Comment by JacksonKearl** [comment]
@Anushka11a please create a separate issue and follow this guide for diagnosing performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by Anushka11a** [comment]
I have reinstalled visual Studio Code and now its working fine. Sent from Mail for Windows 10 From: Jackson KearlSent: 21 June 2021 20:39To: microsoft/vscodeCc: Anushka; MentionSubject: Re: [microsoft/vscode] VS Code insider is too slow after recent update (#123535) @Anushka11a please create a separate issue and follow this guide for diagnosing performance issues https://github.com/microsoft/vscode/wiki/Performance-Issues—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
