### ISSUE TITLE
questionsVS Code crashing on restart

### ISSUE THREAD

**Issue by barbosaGdev** [microsoft/vscode#123572]
Issue Type: <b>Bug</b>

I have faced one critical bug on opening compiled javascript file(complied with webback).

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.58GB free)|
|Process Argv|E:\\PROJECT\\Gabriel\\notion-extension --crash-reporter-id d16c9452-7c07-49f3-b8d5-5b1bee4a7d82|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
composer|ika|0.7.1
vetur|oct|0.33.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by barbosaGdev** [comment]
Here's the screenshot for the bug:
![vscode_bug](https://user-images.githubusercontent.com/32107769/117826772-ceaf9380-b246-11eb-9356-7f069460b2ad.png)

**Comment by barbosaGdev** [comment]
[background.zip](https://github.com/microsoft/vscode/files/6497682/background.zip)
When try to open this file. The issue happening. Hope it could be resolved. 
thank you!

**Comment by JacksonKearl** [comment]
I am able to open the file without any problems. Can you try opening it with all extensions disabled (`F1 => Reload with Extensions Disabled`)? If you are able to open it with extensions disabled, you can try checking which extension is causing problems by running `F1 => Start Extension Bisect` command.

**Comment by barbosaGdev** [comment]
Still same issue..
Opening is just fine but scrolling down a bit will cause the issue. :/
![Screenshot_3](https://user-images.githubusercontent.com/32107769/118868937-2c815280-b8bb-11eb-94d2-18d733ab7a19.png)

**Comment by JacksonKearl** [comment]
Thanks for the update, can you please try following this guide from "The Renderer/Window process consumes a lot of CPU" onward to further diagnose the issue and potentially collect a profile to help us understand the issue: https://github.com/microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu

**Comment by barbosaGdev** [comment]
Anyway, it is not critical 'cause I don't have to open this file after all 'cause this file is complied one. 
Thanks anyway!

**Comment by JacksonKearl** [comment]
Sure, though VS Code should be able to open that file with your system's specs, and we'd like to diagnose why if it does not. If can provide the profile that'd help, otherwise we can just close this issue out.
