### ISSUE TITLE
Crashing: JS/TS language features

### ISSUE THREAD

**Issue by LohitakshTrehan** [microsoft/vscode#123545]
Issue Type: <b>Bug</b>

JS/TS language features keep re-initialising on their own. Still happening on latest update.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.11GB free)|
|Process Argv|--crash-reporter-id 22f20271-80f3-48d7-99a0-02840fa2f05a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.6.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
vscode-graphql|Gra|0.3.16
vscode-scss-formatter|sib|2.1.0
code-spell-checker|str|1.10.2
errorlens|use|3.2.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflight:30299254

```

</details>

**Comment by LohitakshTrehan** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

No I haven't tried it in "Insiders build"
For official build, it crashes even when all the extensions are disabled. After April update the crashes are few (once or twice every 20 minutes). Before April update they were once every 2 minutes.

**Comment by LohitakshTrehan** [comment]
Do *.dmp files created a long time after a crash still relevant? Found that *.dmp files took an hour to get created. If they are still relevant, I can attach them here.

**Comment by duanehutchins** [comment]
@LohitakshTrehan  If it helps, I was getting this same issue on Stable, too (even with extensions disabled). Found two of my settings potentially caused it to happen; after removing these from my local `settings.json`, the issue was resolved:

```
"javascript.validate.enable": false,
"typescript.disableAutomaticTypeAcquisition": true,
```

Do you have either of these same settings? If so, try removing them.

Also, the latest Insiders doesn't suffer from the same bug when I tested, even with those settings in place. So, if it's an option for you, try Insiders.

**Comment by mjbvz** [comment]
@LohitakshTrehan Please test in insiders

Also the dmp file only gets generated if VS Code itself crashes, not when a language server restarts so it's expected that none is generated in this case
