### ISSUE TITLE
intellisense not working for Javascript files stored in sharepoint document library

### ISSUE THREAD

**Issue by Wayne-Shen** [Microsoft/vscode#12350]
- VSCode Version:1.5.2
- OS Version:Windows 10

Steps to Reproduce:

1. Upload a JavaScript to a SharePoint document library
2. Open the document library within windows explorer
3. Open the Javascript file with VSCode

**4. Javascript intellisense is not working**
5. the file path is "\\servername@portnumber\DavWWWRoot\siteurl\documentlibraryurl\folder\test.js"

Please help to look at this issue, thank you!

**Comment by chrmarti** [comment]
Are you getting IntelliSense when typing `Math.`? Could you paste the content of test.js?

**Comment by Wayne-Shen** [comment]
nothing was show whatever I typed，console. Math. function even var. VSCode
behaves like notepad

2016年9月22日 上午12:04，"chrmarti" <notifications@github.com>写道：

**Comment by chrmarti** [comment]
What is the detected language shown in the lower right corner of the window?

**Comment by chrmarti** [comment]
@waderyan Any idea why a file on a SharePoint would not have IntelliSense? (I tried with a network path and that worked fine.)

**Comment by waderyan** [comment]
This may be related to https://github.com/Microsoft/TypeScript/issues/10735

@Wayne-Shen can you do the following to help us debug the issue? 

Set this flag in your settings. Then open the Output window. Send us a screen capture. 

```
"typescript.tsserver.trace": "verbose"
```

**Comment by Wayne-Shen** [comment]
Hello @waderyan ,

I followed your steps and find the error message is:

TypeScript Service: tried to cancel request with sequence number 2. But request got already delivered.
TypeScript Service: canceled request with sequence number 3
TypeScript Service: canceled request with sequence number 5
TypeScript Service: canceled request with sequence number 8
...
![output](https://cloud.githubusercontent.com/assets/3283024/18733974/48070cb2-80a2-11e6-83b0-ad224f5d9077.png)

**Comment by waderyan** [comment]
Ok thank you. This is the same thing we have seen before.

**Comment by waderyan** [comment]
Going to close this as its tracked above.
