### ISSUE TITLE
Empty groups no longer close automatically

### ISSUE THREAD

**Issue by daniel-liuzzi** [microsoft/vscode#123512]
Issue Type: <b>Bug</b>

- `workbench.editor.closeEmptyGroups` set to the default value (`true`)
- On nightly-20210428, Ctrl+W with no tabs open closed Visual Studio Code
- On nightly-20210510, this is no longer the case; VS Code stays open no matter how many times Ctrl+W is pressed
- Problem also exists on nightly-20210508

VS Code version: Code - Insiders 1.57.0-insider (54d33cf14cf6c0e86880b5b74a5a3628de42bce9, 2021-05-10T05:15:52.500Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.23GB (34.46GB free)|
|Process Argv|. --crash-reporter-id 99905682-28f9-4822-a435-25891679b69b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
vscode-nginx-conf|ahm|0.1.3
Bookmarks|ale|13.0.4
ng-template|Ang|11.2.14
unique-lines|bib|1.0.0
jsrefactor|cms|2.20.6
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
graphviz-markdown-preview|gee|0.0.8
gc-excelviewer|Gra|3.0.41
vscode-nginx-conf-hint|han|0.1.0
vscode-test-explorer|hbe|2.20.0
rest-client|hum|0.24.5
angular2-switcher|inf|0.3.4
vscode-edit-csv|jan|0.6.0
json2csv|kha|0.0.1
vscode-fix-checksums|leh|1.1.0
git-tree-compare|let|1.10.1
code-groovy|mar|0.1.2
template-string-converter|meg|0.4.7
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
python|ms-|2021.5.829140558
jupyter|ms-|2021.6.828932339
remote-containers|ms-|0.177.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.6.0
powershell-preview|ms-|2021.4.2
vscode-typescript-next|ms-|4.3.20210509
vsliveshare|ms-|1.0.4131
debugger-for-chrome|msj|4.12.12
vscode-groovy-lint|Nic|1.4.0
json-to-yaml-and-more|pet|0.0.3
nginx-formatter|ray|0.0.13
vscode-yaml|red|0.18.0
vscode-gitweblinks|red|2.5.0
synthwave-vscode|Rob|0.1.8
vscode-scss-formatter|sib|2.2.0
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
vscode-markdown-paste-image|tel|0.12.3
vscode-icons|vsc|11.4.0
quokka-vscode|Wal|1.0.363
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.4.0
markdown-editor|zaa|0.1.5
material-theme|zhu|3.10.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782

```

</details>

**Comment by yume-chan** [comment]
@bpasero The keybinding is lost in https://github.com/microsoft/vscode/commit/2126be633119f4f1f7fa3048abc874ef7760a906

old:
https://github.com/microsoft/vscode/blob/94daaf715a41d224aeca2866234335f9e8fe86ce/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L51-L60

current:
https://github.com/microsoft/vscode/blob/2126be633119f4f1f7fa3048abc874ef7760a906/src/vs/workbench/electron-sandbox/actions/windowActions.ts#L39-L44

**Comment by bpasero** [comment]
Yes, an intentional change based on feedback we got in https://github.com/microsoft/vscode/issues/54492

To get this behaviour back, configure this in keybindings:

```json
{
  "key": "cmd+w",
  "command": "workbench.action.closeWindow",
  "when": "!editorIsOpen && !multipleEditorGroups"
}
```

**Comment by daniel-liuzzi** [comment]
> Yes, an intentional change based on feedback we got in #54492

Does this change `workbench.editor.closeEmptyGroups` is effectively rendered useless now?

**Comment by bpasero** [comment]
Why do you think that? `workbench.editor.closeEmptyGroups` is unrelated to the change and was not affected.

**Comment by daniel-liuzzi** [comment]
I''m sorry, I meant `window.closeWhenEmpty`, not `workbench.editor.closeEmptyGroups `.

**Comment by bpasero** [comment]
That setting is also not impacted by the change. The change is only a removal of a keybinding.
