### ISSUE TITLE
Terminal sessions profile args does not allow to start a named tmux session

### ISSUE THREAD

**Issue by Norfeldt** [microsoft/vscode#123550]
- VS Code Version: April 2021 (version 1.56)
- OS Version: macOS Big Sur (version 11.2.3)

The new terminal profiles seems really great. However I'm having some trouble getting my tmux session to be named like the current directory. 

Steps to Reproduce:

```
  "terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh"
    },
    "tmux": {
      "path": "tmux",
      "icon": "terminal-tmux",
      "args": ["attach-session -d -t \"${PWD##*/}\" || new-session -s \"${PWD##*/}\""]
    }
  },
```

The error:

```
The terminal process "tmux 'attach-session -d -t "${PWD##*/}" || new-session -s "${PWD##*/}"'" terminated with exit code: 1.
```

As it can be seen the args are just passed as a string. Isn't that a bug?

I was expecting it to start the process without the `'`

```sh
tmux attach-session -d -t "${PWD##*/}" || new-session -s "${PWD##*/}"
```

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
You're passing in a single argument, try something like this:

```
"args": [
  "attach-session",
  "-d",
  "-t",
  "${PWD##*/}"
]
```

You won't be able to use `||` there as that's a shell thing that you can't use when spawning a regular process, you could wrap this in a .sh script and start that though.

**Comment by Norfeldt** [comment]
@Tyriar thanks a lot!

I have a .sh script and was just trying to port the parts from it to this. 

How do I start the script to run just before the tmux session? 

Then I imagine that the `args: ['a']` since it would be attaching the the session created by the script

**Comment by DougTea** [comment]
> You're passing in a single argument, try something like this:
> 
> ```
> "args": [
>   "attach-session",
>   "-d",
>   "-t",
>   "${PWD##*/}"
> ]
> ```
> 
> You won't be able to use `||` there as that's a shell thing that you can't use when spawning a regular process, you could wrap this in a .sh script and start that though.

${PWD##*/} in args is not interpolated at vscode version 1.56.1.Any help?

**Comment by Tyriar** [comment]
@Norfeldt here's an example of a script that starts tmux: https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41, it uses the old shell setting but that can be swapped out with your profile's path:

```js
"tmux": {
      "path": "/foo/bar/code-shell"
}
```

@DougTea I'm not sue what it's meant to do

**Comment by Norfeldt** [comment]
That did the trick. Thanks @DougTea @Tyriar

**Comment by vlrevolution** [comment]
I would recommend to modify it slightly to not have long and non descriptive name as the persistant tmux session name but rather use the name of the directory you run vscode from with `code .` (some might like this better):
```
#!/bin/sh
SESSION="${PWD##*/}"
tmux attach-session -d -t $SESSION || tmux new-session -s $SESSION
```
