### ISSUE TITLE
Persistent terminals only stay alive for 60 seconds after a disconnect

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123518]
It looks like the local/remote terminal refactor didn't end up injecting different grace time depending on local/remote, so remote terminal processes will only stick around for 60 seconds:

https://github.com/microsoft/vscode/blob/9ff7c93a9b4419c1a4bab787c59f0093578bc4d7/src/vs/platform/terminal/node/ptyService.ts#L329-L336

**Comment by rzhao271** [comment]
@meganrogge I'm wondering how to verify this issue?

**Comment by meganrogge** [comment]
@rzhao271 see the steps here https://github.com/github/codespaces/issues/3077#issue-901536284

**Comment by rzhao271** [comment]
I tried the following:
1. Open Codespaces
2. Run a long-running command like `ls -R`  or `yarn watch` in a terminal
3. Quit VS Code
4. Reopen VS Code

I don't see the previous terminal show up.

**Comment by meganrogge** [comment]
In codespaces web or desktop?

**Comment by rzhao271** [comment]
Desktop, updated steps above

**Comment by meganrogge** [comment]
Closing vscode will take down the terminals. They will stay alive on reload of the window

**Comment by Tyriar** [comment]
I'll try verify this one
