### ISSUE TITLE
Tooltips are cut off on HighDPI display

### ISSUE THREAD

**Issue by Balkoth** [microsoft/vscode#123547]
See the following example images:
![image](https://user-images.githubusercontent.com/80055480/117770127-de25e100-b234-11eb-8607-6f406cb1158c.png)
![image](https://user-images.githubusercontent.com/80055480/117770449-36f57980-b235-11eb-8293-6fc132f5d312.png)

My primary monitor is an 32" UHD 4K display set to 150 scaling.

**Comment by Balkoth** [comment]
This still happens on `1.59.1`,

**Comment by Balkoth** [comment]
WTF why is this issue close? The issue is still there, just no one on the dev team cares.

**Comment by yume-chan** [comment]
I can reproduce this on 150% and 175% DPI scale, but not others.

```text
Version: 1.63.0-insider (user setup)
Commit: c42793d0357ff9c6589cce79a847177fd42852ee
Date: 2021-11-29T08:08:05.585Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22499
```

![image](https://user-images.githubusercontent.com/1330321/143908289-14e5d068-60dd-40fd-8b88-263dc7e986bc.png)

I also tried Electron 16.0.2 and latest alpha

![image](https://user-images.githubusercontent.com/1330321/143908582-11c6892f-731d-48e1-9880-e0ed169114b6.png)

![image](https://user-images.githubusercontent.com/1330321/143908936-70b9ffb8-fbd3-478c-a8cb-37cc3329c978.png)

**Comment by deepak1556** [comment]
Thanks for testing with fiddle @yume-chan , I am unable to repro the bug with the above scaling on `Windows 10.0.22000`.
<img width="811" alt="Screen Shot 2021-12-03 at 0 13 26" src="https://user-images.githubusercontent.com/964386/144453949-b04b584f-0d3f-48e7-a539-d4dacf93e74d.png">

Are you able to repro the issue with chrome or edge on the same setup ?

**Comment by yume-chan** [comment]
Chrome 96.0.4664.45 (Official Build) (64-bit) has the same issue.

![image](https://user-images.githubusercontent.com/1330321/144479860-610ab691-2143-40bf-8913-2e78fd97c353.png)

(150%, most time the bottom border is missing, sometimes the right one is also missing)

---

Edge 98.0.1091.0 (Official build) canary (64-bit) have no problem on all DPI levels.

![image](https://user-images.githubusercontent.com/1330321/144478834-15484b62-9103-41dd-a7b2-a3f1bfefc08e.png)
(150%)

![image](https://user-images.githubusercontent.com/1330321/144478699-f83ea511-b14b-414f-a102-423f0504ac16.png)
(175%)

**Comment by yume-chan** [comment]
Upstream issue: https://crbug.com/997368

**Comment by deepak1556** [comment]
Awesome, thanks for linking it.

**Comment by Balkoth** [comment]
Will this ever get fixed on Windows 10?

**Comment by Balkoth** [comment]
To this day this issue still persists...

Version: 1.75.0 (system setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by Balkoth** [comment]
To this day this issue still persists...

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.83.1 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36

**Comment by Balkoth** [comment]
WHOOT seems fixed to me now? Can anyone confirm?

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z (2 wks ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.89.1 Chrome/120.0.6099.291 Electron/28.2.8 Safari/537.36
