### ISSUE TITLE
Cmd+Q doesn't auto-save workspace state

### ISSUE THREAD

**Issue by ajpinedam** [Microsoft/vscode#12357]
- VSCode Version: 1.5.2
- OS Version: Os X 10.11.6 - El Capitan

Steps to Reproduce:

1. Create a file and do not save it.
2. Hit on Cmd+Q (Quit)

Would be nice if app could just quit and when reopening just load the previous state.

This is more a Feature request than an issue.

**Comment by chrmarti** [comment]
Tracked as #101

**Comment by ajpinedam** [comment]
Gosh I spent a few hours looking for this issues in both opened and closed but couldn't find it. Sorry and thanks! will keep track on #101
