### ISSUE TITLE
can't use Windows Terminal as debug external console

### ISSUE THREAD

**Issue by isudfv** [microsoft/vscode#123541]
- VS Code Version: 1.56.0(system setup)
- OS Version: Windows 10 Feature Experience Pack 321.11803.0.3

Steps to Reproduce:

1. set "externalConsole" to be true in launch.json
2. set "terminal.external.windowsExec" to be where wt.exe is
3. when I press ctrl+shift+c (Open New External Terminal), it works fine. But when I debug, it is cmd that came out

![image](https://user-images.githubusercontent.com/70507125/117760945-17704800-b259-11eb-8764-a4a611331974.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/163409
