### ISSUE TITLE
Crash when comments with short key.

### ISSUE THREAD

**Issue by yaukeywang** [microsoft/vscode#123565]
Always crash when commenting a big block of code with short key, Visual Studio Code will CRASH!!!

**Comment by deepak1556** [comment]
Can you attach the crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

**Comment by yaukeywang** [comment]
> 
> 
> Can you attach the crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

I followed the step, but no dump files being generated, only an empty folder named "reports" and a "settings.dat” there... My code version is 1.56.2.

**Comment by deepak1556** [comment]
> I followed the step, but no dump files being generated, only an empty folder named "reports" and a "settings.dat” there

Thanks for checking, then the issue you are facing is not a crash.

Does the issue happen when you run with `code --disable-extensions` ? If it does, can you provide the output of `code --verbose`

**Comment by yaukeywang** [comment]
> 
> 
> > I followed the step, but no dump files being generated, only an empty folder named "reports" and a "settings.dat” there
> 
> Thanks for checking, then the issue you are facing is not a crash.
> 
> Does the issue happen when you run with `code --disable-extensions` ? If it does, can you provide the output of `code --verbose`

Yes, the issue still happen when i run with `code --disable-extensions`, the attachment is the output of `code --verbose`.
By the way, you can easily reproduce this issue when you are trying to comment a block of code (80 lines) with `ctrl + /`,  code will freeze and dispear。
[vscode-comment-crash.txt](https://github.com/microsoft/vscode/files/6491112/vscode-comment-crash.txt)

**Comment by deepak1556** [comment]
Don't see any issue in the logs, also I am able to repro the issue based on the above steps.

When the freeze happens are you able to run `code --status` or `code --new-window` from the terminal ?

\gifPlease

**Comment by yaukeywang** [comment]
> 
> 
> Don't see any issue in the logs, also I am unable to repro the issue based on the above steps.
> 
> When the freeze happens are you able to run `code --status` or `code --new-window` from the terminal ?
> 
> \gifPlease

No，it just freezes about 1-3 seconds and then disappeares. This issue happen before 3 times upgrade to current 1.56.2.
