### ISSUE TITLE
RegCreateKeyEx Failed Code :1021 - Error during installation

### ISSUE THREAD

**Issue by alwinaugustin** [microsoft/vscode#123539]
- VS Code Version:1.56.0
- OS Version:Windows 10 Enterprise, Version 1809, OS Build - 17763.1817

Steps to Reproduce:

1. Download latest version of  VSCode Installer from the official website (Version:1.56.0)
2. Run the installer.
3. The following error will be shown and it is not possible to continue the installation.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Have you seen https://github.com/microsoft/vscode/issues/56537?
