### ISSUE TITLE
Intellisense doesn't work and I cannot run Python files in Terminal

### ISSUE THREAD

**Issue by ruchirpadhye** [microsoft/vscode#123594]
The Jupyter Extension is Disabled and The Intellisense doen't work. Also I cannot execute any python file. I just updated Visual Studio Code to 1.56.1

**Comment by zozzz** [comment]
Same here. Some additional details:

VS intelliCode output
```
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Error while activating Python: {}
```

![image](https://user-images.githubusercontent.com/611741/117860458-9af95b80-b290-11eb-8061-650c15f7042a.png)

I try to reload / restart, but nothing changed.

**Comment by RajrupDasid** [comment]
Same issue 
It's very annoying and serious a brain gobbling matter
While in Rush hour

**Comment by egamma** [comment]
Please report the issue against the Python extension.
