### ISSUE TITLE
VS Code ignores environment variables if extension restarts

### ISSUE THREAD

**Issue by zamanzamanli** [microsoft/vscode#123508]
- VS Code Version: 1.56.0
- OS Version: macOS 11.3.1

Steps to Reproduce:
This happens during extension development.
1. Add environment variable to the "env" object in the "launch.json" file.
2. Launch extension.
3. The environment variable is accessible by the extension.
4. Open a new folder from the debug VS Code.
5. Extension gets activated again

Expected result:
The environment variable is there.

Actual result:
The environment variable no longer is there.

Run configuration:
```
{
	"name": "Run Extension",
	"type": "extensionHost",
	"request": "launch",
	"runtimeExecutable": "${execPath}",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}"
	],
	"outFiles": [
		"${workspaceFolder}/dist/**/*.js"
	],
	"env": {
		"TEST_ENV": "true"
	},
	"preLaunchTask": "npm: webpack"
},
```

**Comment by DanTup** [comment]
I'm seeing this too and it's quite a pain. Whenever I open a new workspace in the extension dev host, the environment variables to use a server-mode version of the debug adapter are lost, preventing debugging of the debug adapter.

#114063 may be the same as this?

**Comment by connor4312** [comment]
@bpasero I'd appreciate a quick 👀 to check if the fix is sane. Just reuses the userEnv from the context window, if one exists and the current open request doesn't have a userEnv.

**Comment by bpasero** [comment]
@connor4312 not sure this is the best way to fix this. We already have code inside `window.ts´ to preserve the `userEnv` in certain cases:

https://github.com/microsoft/vscode/blob/d0df79be50e2bc53e4c8ee48a0bfccb0e19c9559/src/vs/platform/windows/electron-main/window.ts#L792-L800

The rationale is that `userEnv` can only be present for a window launched from the CLI but it seems we can also have this when launched from debug as extension debugging window.

Imho a better fix would be to address the issue in the `window.ts` code by adding another condition when to preserve `userEnv`. We know exactly if a window is an extension host debug window or not:

https://github.com/microsoft/vscode/blob/d0df79be50e2bc53e4c8ee48a0bfccb0e19c9559/src/vs/platform/windows/electron-main/window.ts#L120-L120

**Comment by connor4312** [comment]
Got it, I'll try that approach tomorrow.
