### ISSUE TITLE
Korean character input glitch

### ISSUE THREAD

**Issue by bchanpark** [microsoft/vscode#123536]
When I using Korean character, there is a glitch. If you write any korean character and use any moving key(arrow key, home/end, page up/down, etc.), the last korean character is overwrited upon 1 character beside the cursor.

Here is same problem. https://github.com/microsoft/vscode/issues/114017
But not only left arrow, but also all kind of moving key after inserting korean character are problems.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/114017
