### ISSUE TITLE
Allow to always use indentation with tab

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#12352]
Every time I try to change the indentation mode of a file to use tabulation, it get back to spaces as soon as I press enter.

All I can do is convert to tab each time I make an edit in the file… It’s very frustrating.

Please allow us to set a default setting for the indentation, once and for all, globally.

Example : 

```
"editor.indentationMode": "tab" // (or "space")
```

**Comment by chrmarti** [comment]
Have you tried:
```
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
```

**Comment by EmmanuelBeziat** [comment]
It seems to work, thanks.

However, there might be a question about this point, as I couldn’t figure what was the purpose of "insertSpaces" by its name or description. If I see a "insertSpace" option, I expect it more to be the insertion of a new indent (tab or spaces) when I get a new line inside a function or a group of tags.

Control if the indentation is made by spaces or tab by default should have a name correlated to "indentation" itself, I guess. What made me think of this is that I never have to make a search (that wasn’t successful) to set this on SublimeText, Atom or Brackets. VisualStudio Code is the only one that made me read all settings description, search through internet, and finally open an issue on the project repo.

But you’ll have the last word about this, I’m just giving my thoughts. Thanks for the help!

**Comment by chrmarti** [comment]
I agree, the naming is suboptimal. "editor.spacesIndentation" might be better discoverable.

**Comment by alexandrudima** [comment]
@EmmanuelBeziat Do you have any suggestion for a better description of `editor.insertSpaces`. I would not rename the setting now, to not break everyone.

Today it reads:
```
// Insert spaces when pressing Tab. This setting is overriden based on the file contents when `editor.detectIndentation` is on.
```

**Comment by EmmanuelBeziat** [comment]
@alexandrudima I have a french version of VScode, it might be slightly different.

Anyway, I think it should be explicit, by adding something like this maybe : 

```
// Allow to switch indentation mode to spaces (true) or tab (false).
```

Thanks. :)

**Comment by wesleycoder** [comment]
I've had the same problem, but discovered that if set the indentation to tabs and switch to another file that is "space-tabbed" and come back, my indentation is set to spaces again.
Why does the indentation style is not set by file, but instead is on the whole editor?

**Comment by alexandrudima** [comment]
@wesleycoder Please see the following default options.

![image](https://cloud.githubusercontent.com/assets/5047891/19747739/c337da14-9bdd-11e6-925c-38944fdcc9e4.png)

You can tweak them as you desire.

**Comment by ashishdoneriya** [comment]
It simply doesn't work.

**Comment by EmmanuelBeziat** [comment]
No problem to me, it's okay. Check that Something like editorconfig is not getting in the way.
