### ISSUE TITLE
Проблема с доступностью NVDA

### ISSUE THREAD

**Issue by BlindMethod** [microsoft/vscode#123561]
Issue Type: <b>Bug</b>

Добрый день.
При использовании программы экранного доступа NVDA, а именно в момент, когда происходит перемещение по словам, озвучивание происходит дважды одно и тоже, что представляет большую проблему.
Примеры случаев, где прочитается дважды одно и тоже:
1. value = 5
2. value == 5
3. В случае, когда слово последнее в этой строке(дважды будет произнесено слово "world")
hello world
4. Закрывающие теги в html разметке могут прочитываться до четырех раз.
<h1>hello</h1>
Спасибо

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.30GB free)|
|Process Argv|--crash-reporter-id 75444f5b-95bd-4d08-a092-b71ce9e40262|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.56.2
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.811652604
blindjs|Sha|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.
Issue Type: <b>Bug</b>

Добрый день.
При использовании программы экранного доступа NVDA, а именно в момент, когда происходит перемещение по словам, озвучивание происходит дважды одно и тоже, что представляет большую проблему.
Примеры случаев, где прочитается дважды одно и тоже:
1. value = 5
2. value == 5
3. В случае, когда слово последнее в этой строке(дважды будет произнесено слово "world")
hello world
4. Закрывающие теги в html разметке могут прочитываться до четырех раз.
<h1>hello</h1>
Спасибо

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.30GB free)|
|Process Argv|--crash-reporter-id 75444f5b-95bd-4d08-a092-b71ce9e40262|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.56.2
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.811652604
blindjs|Sha|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by isidorn** [comment]
Thanks for letting us know and thanks for the translation.
However this is already captured in this issue thus closing as duplicate https://github.com/microsoft/vscode/issues/90578
Thus it is captured via https://bugs.chromium.org/p/chromium/issues/detail?id=1181643
Please comment on the chrome issue
