### ISSUE TITLE
[Question] auto-completion from another file

### ISSUE THREAD

**Issue by srinivashappy** [Microsoft/vscode#12356]
- VSCode Version: 1.5.2
- OS Version: windows 10 pro
  Steps to Reproduce:
1. open `variable.scss` file (example)
2. create a variable, `$fontSize: 13px`.
3. import `variable.scss` in `main.scss` file.
4. In `main.scss` file, try to use $fontSize variable .
5. issue: while typing the variable name editor is not showing auto-completion for the $fontSize variable. 
   please help.

**Comment by chrmarti** [comment]
This can be implemented in an extension. We might not do this in vscode itself.

**Comment by mrmlnc** [comment]
@srinivashappy, you have tried `SCSS intelliSense` extension?

**Comment by mjbvz** [comment]
Yes, we would expect an extension to provide this sort of whole project intellisense
