### ISSUE TITLE
vscode no longer starts in the background when launched in an msys2 or mingw shell

### ISSUE THREAD

**Issue by MoAlyousef** [microsoft/vscode#123587]
- VS Code Version: 1.56.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. type `code .` in an msys2 or mingw shell.
You get the following output. vscode launches correctly. However the shell prompt no longer returns.
```
$ code .

[main 2021-05-11T16:31:14.762Z] update#setState idle
[main 2021-05-11T16:31:44.764Z] update#setState checking for updates
[main 2021-05-11T16:31:44.944Z] update#setState idle

```
launching with `code . &` returns the shell prompt, but still gives these messages from time to time. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
What does `which code` return?

**Comment by MoAlyousef** [comment]
```
$ which code
/c/Users/may64/AppData/Local/Programs/Microsoft VS Code/code
```

**Comment by joaomoreno** [comment]
Right. Not sure how that went into your `PATH`, but the correct location should be:

```
/c/Users/may64/AppData/Local/Programs/Microsoft VS Code/code/bin
```
