### ISSUE TITLE
Have a setting to change the font settings for the tree

### ISSUE THREAD

**Issue by janraak** [microsoft/vscode#123591]
Currently the left pane of the editor has no way to change the font size.

Specially on big screens this can be inconvenient.

![Screen Shot 2021-05-11 at 10 14 46 AM](https://user-images.githubusercontent.com/12236488/117857769-fe0fd180-b241-11eb-8b46-42860791a091.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/26128
