### ISSUE TITLE
Shell Environment Failed and Terminal Unresponsive After Latest Update

### ISSUE THREAD

**Issue by jerwjones** [microsoft/vscode#123571]
- VS Code Version: 1.56.0 (Universal)
- OS Version: MacOS Big Sur 11.3.1
- MacBook Pro (Retina, 15-inch, Mid 2015)

Extensions Installed
- None

Steps to Reproduce:
1. Update to latest VS Code
2. Open a project

Problems Experienced
- Shell environment failed with all commands commented out
- Terminal window opens but is not accessible

Fixes Attempted
1. Uninstall / Re-install VS Code 1.56.0 - same issue
2. Uninstall / Re-Install VS Code 1.55.0  - no issues but auto update makes this useless after restart
2. Install VS Code Insiders - No shell environment warnings but same Terminal unresponsive behavior

Theory
- Updates to the Terminal tabs is not compatible with older generation MacBook Pro's system architecture.

VS Code 1.56.0 Screenshot
![vs-code-1-56-0](https://user-images.githubusercontent.com/12953446/117826030-70c68000-b235-11eb-899f-4c6825c6cf04.png)

VS Code Insider Screenshot
![vs-code-insider](https://user-images.githubusercontent.com/12953446/117825929-58566580-b235-11eb-8a2b-e796a3386e2f.png)

**Comment by jerwjones** [comment]
For anyone experiencing the same problem reverting back to VS Code 11.55.0 and updating Settings > Application > Update > Mode = none has me back in production.

**Comment by Tyriar** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by jerwjones** [comment]
I can't share code from a client project.

**Comment by Tyriar** [comment]
Not asking you to. You could also try the [insiders](http://code.visualstudio.com/insiders) build since we've made a lot of changes in this area since v1.56.

**Comment by jerwjones** [comment]
The insiders build fixed the terminal issues
