### ISSUE TITLE
OpenGL terminal renderer slow with tmux enabled

### ISSUE THREAD

**Issue by sashaweiss** [microsoft/vscode#123503]
In previous VSCode versions, I manually set the renderer to `canvas` rather than the default OpenGL, and I no longer noticed a slowdown. However, it appears that the newest release removed the `terminal.integrated.rendererType` setting, and now I'm back to laggy rendering when using the integrated terminal. Happy to collect additional logs/metrics if that helps!

Is there a way for me to switch back to the `canvas` renderer in the meantime?

- VS Code Version: 1.56.0
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Open an integrated terminal in VSCode
2. Launch a `tmux` session
3. Notice slow rendering performance

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
You can go back to the canvas renderer by setting `terminal.integrated.gpuAcceleration: false`
