### ISSUE TITLE
can I set a shortcut to the right click menus in workspace file?

### ISSUE THREAD

**Issue by moesakura** [microsoft/vscode#123534]
just like this
![image](https://user-images.githubusercontent.com/5019609/117753197-a9248900-b24a-11eb-91a3-5815df95313f.png)

I have search the shortcut setting and I can't find one useful

the question in StackOverflow
https://stackoverflow.com/questions/67464178/can-i-set-a-shortcut-to-the-right-click-menus-in-workspace-file

版本: 1.56.0 (user setup)
提交: cfa2e218100323074ac1948c885448fdf4de2a7f
日期: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Please add your platform and version information from the About dialog.

**Comment by moesakura** [comment]
> Please add your platform and version information from the About dialog.

I have paste it to the question content

**Comment by gjsjohnmurray** [comment]
On Windows <kbd>Shift</kbd>+<kbd>F10</kbd> will open the context menu for the focused item. And if your keyboard has a dedicated [Menu key](https://en.wikipedia.org/wiki/Menu_key) this will do the same thing.

**Comment by moesakura** [comment]
Here are three screenshots of clicking in different places
1.
![image](https://user-images.githubusercontent.com/5019609/117921112-b745d880-b322-11eb-876d-299b5e60899a.png)
2.
![image](https://user-images.githubusercontent.com/5019609/117921142-c75db800-b322-11eb-9503-8e6a628f960a.png)
3.
![image](https://user-images.githubusercontent.com/5019609/117921177-dba1b500-b322-11eb-89b5-29e1bd1874c4.png)

shift+F10 is show the context menu, like scene 3 above

but what I want is scene 1

**Comment by sbatten** [comment]
> but what I want is scene 1 probably call explorer/context

shift+f10 works when focus is in the explorer. first use `ctrl+shift+e` to focus the explorer, then shift+f10 to show the context menu.

**Comment by moesakura** [comment]
> > but what I want is scene 1 probably call explorer/context
> 
> shift+f10 works when focus is in the explorer. first use `ctrl+shift+e` to focus the explorer, then shift+f10 to show the context menu.

It works. Thank you very much ！！
