### ISSUE TITLE
After I update, the icon is bigger and abnormal

### ISSUE THREAD

**Issue by Bonoy0328** [microsoft/vscode#123554]
- VS Code Version: 1.56.0
- OS Version: win10
Steps to Reproduce:
![image](https://user-images.githubusercontent.com/42759143/117791442-eace2780-b27c-11eb-98ca-de3109b0110b.PNG)
1.After I update, the icon is bigger and abnormal

Does this issue occur when all extensions are disabled?: No

**Comment by kt-unzner** [comment]
Duplicate, see https://github.com/microsoft/vscode/issues/123475
