### ISSUE TITLE
Fail to find modules when duplicating a file

### ISSUE THREAD

**Issue by ImperadorSid** [microsoft/vscode#123567]
Issue Type: <b>Bug</b>

Actual behavior:
When duplicating a file, the new file shows the following error:
"Cannot find module '' or its corresponding type declarations.ts(2307)".

Partial Fix: 
Reloading window or restarting TS server, fixes the problem.

Expected:
Do not show this error

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2080)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.64GB (8.19GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 7b46e463-daba-4c44-8c9c-c9d19fc25eb5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
vscode-styled-components|jpo|1.5.2
vscode-colorize|kam|0.11.1
fluent-icons|mig|0.0.9
vscode-pylance|ms-|2021.5.1
vsliveshare|ms-|1.0.4131
material-icon-theme|PKi|4.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share specific steps to reproduce the issue (such as contents of the file you are duplicating)
