### ISSUE TITLE
April 2021 Recovery 2

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#123633]
- [x] Create a milestone `<Month> <Year> Recovery` **owner**
- [x] Bump the version number **owner**
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22April+2021+Recovery+2%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - **owner**
  - [x] OS X - **owner**
  - [x] Linux - **owner**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit **@connor4312**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit **@tyriar**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] Windows ARM64 **@bpasero**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal **@TylerLeonhardt**
    - [x] Intel **@TylerLeonhardt**
    - [x] Apple Silicon **@kieferrm**
  - [x] Linux - @RMacfarlane
    - [x] deb package 64-bit
    - [x] rpm package 64-bit
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux **@TylerLeonhardt**
    - [x] macOS **@TylerLeonhardt**
    - [x] Windows **@roblourens**
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by gjsjohnmurray** [comment]
Item 3 has the wrong filter for finding the candidate issues.

**Comment by TylerLeonhardt** [comment]
updated - thanks!

**Comment by githubnew-pro** [comment]
> مورد 3 فیلتر غلطی برای یافتن مشکلات نامزدها دارد.

#123757

**Comment by githubnew-pro** [comment]
> * [x] یک **مالک** نقطه عطف ایجاد کنید`<Month> <Year> Recovery` ****
> * [x] **مالک** شماره نسخه را ضربه بزنید****
> * [x]  [🔖مسائل کاندیداها](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22April+2021+Recovery+2%22+)
> * [x] مسائل مربوط به نامزدها را به **تیم** مهم بازیابی اختصاص دهید****
> * [x] مشکلات را مرور کنید `candidate`و در صورت عبور از بررسی ، آنها را به **تیم** مهم بازیابی اختصاص دهید****
> * [x] همه `candidate`اصلاحات توسط همتایان بررسی شده و تحت فشار قرار گرفته `main`و سپس به **تیم** گیلاس منتقل می شوند****
> * [x] `insiders`ساخت را از آغاز کنید`main`
> * [x] مسائل در **تیم** آزمایش می شوند`insiders` ****
> * [x] ساخت `stable`برای همه سیستم عامل ها از **صاحب** شعبه آزاد****
> * [x] مشکلات در `stable`ساخت تأیید می شوند و `verified`برچسب به **مالک** اضافه می شود****
> * [x] بررسی کنید `https://github.com/Microsoft/vscode/compare/release/<x.y>`که هیچ تعهد دیگری در **مالک** شعبه آزادی انجام نشده است****
> * [x] یادداشت های انتشار را به روز کنید و پیوندی را برای جستجوی مشکلات ثابت **gregvanl پیوند دهید**
> * [دودترین](https://github.com/Microsoft/vscode/wiki/Smoke-Test) بیت های پایدار (⚠️باید با `--stable-build`استدلال اجرا شود⚠️ )
>   
>   * [x] ویندوز - **صاحب**
>   * [x] OS X - **صاحب**
>   * [x] لینوکس - **مالک**
> * [x]  بررسی سالم بیت های قابل نصب
>   
>   * [x] ویندوز 32 بیتی **@ connor4312**
>     
>     * [x]  نصب کننده 32 بیتی را امضا کرد
>     * [x]  کاربر نصب شده 32 بیتی را امضا کرد
>     * [x]  زیپ 32 بیتی
>   * [x] ویندوز 64 بیتی **Tyriar**
>     
>     * [x]  نصب شده 64 بیتی را امضا کرد
>     * [x]  کاربر نصب شده 64 بیتی را امضا کرد
>     * [x]  zip 64 بیتی
>   * [x] ویندوز **ARM64bpasero**
>     
>     * [x]  نصب شده ARM64 را امضا کرد
>     * [x]  کاربر نصب شده ARM64 را امضا کرد
>     * [x]  zip ARM64
>   * [x]  سیستم عامل مک
>     
>     * [x] جهانی **TylerLeonhardt**
>     * [x] اینتل **TylerLeonhardt**
>     * [x] سیلیکون سیب **kieferrm**
>   * [x] لینوکس -RMacfarlane
>     
>     * [x]  بسته deb 64 بیتی
>     * [x]  بسته دور در دقیقه 64 بیتی
>     * [x]  بایگانی
>     * [x] ضربه محکم و ناگهانی ( `sudo snap install --classic --dangerous <file>.snap`)
>   * [x] سرور ( [دستورالعمل ها](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers) )
>     
>     * [x] لینوکس **TylerLeonhardt**
>     * [x] از MacOS **TylerLeonhardt**
>     * [x] ویندوز **roblourens**
> * [x] وب سایت **gregvanl را** منتشر کنید****
> * [x] انتشار **مالک** ساخت پایدار****
> * [x] یک **مالک** انتشار رسمی ایجاد کنید****
>   
>   * [x]  ایجاد برچسب: `git tag <x.y.z> release/<x.y>`
>   * [x]  برچسب را فشار دهید: `git push origin <x.y.z>`
>   * [x] ایجاد نسخه GitHub: [برچسب های GitHub را باز کنید](https://github.com/microsoft/vscode/tags) و راست کلیک کنید `... > Create Release`. از عنوان و توضیحات صحیح یادداشت های انتشار ما استفاده کنید. [مثال](https://github.com/microsoft/vscode/releases/tag/1.39.1)

Duplicate of #
