### ISSUE TITLE
omnisharp high cpu usage

### ISSUE THREAD

**Issue by deviltornado** [microsoft/vscode#123626]
Issue Type: <b>Bug</b>

omnisharp high cpu usage when Ctrl+C or Ctrl+V

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.41GB free)|
|Process Argv|E:/TheGame/UnityProject -g E:\\TheGame\\UnityProject\\Assets\\TheGame\\Script\\Mystery\\FirstEnterRelic\\FirstEnterRelicDialog.cs:1:0 --crash-reporter-id d94340ec-9c2c-4190-ad7c-864237b2da12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
docomment|k--|0.1.20
unity-code-snippets|kle|1.3.0
vscode-language-pack-zh-hans|MS-|1.56.2
csharp|ms-|1.23.8
unity-tools|Tob|1.2.12
vscode-counter|uct|2.2.2
unity-debug|Uni|3.0.2
unity-snippets|Ycl|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by deviltornado** [comment]
Thank you for your reply。

**Comment by deviltornado** [comment]
After I update today, it looks normal.

![QQ图片20210512151832](https://user-images.githubusercontent.com/49297734/117934557-5ffd3380-b335-11eb-8c9d-ed3328ec4f3e.png)This is the screenshot of the last time there was a problem。
