### ISSUE TITLE
No css class suggestions with emmet.

### ISSUE THREAD

**Issue by natecorkish** [microsoft/vscode#123662]
- VS Code Version: 

Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

- OS Version: Big sur 11.3.1 (20E241)

Steps to Reproduce:

1. Create a basic html file with a simple inline style with 1 class 

<img src="https://i.imgur.com/Q5Y8nQP.png">

2. Type .fo and no suggestions appear:

<img src="https://i.imgur.com/qx71wWN.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Actually, I wonder if the [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) extension can help with this? 
I notice that extension has a `tailwindCSS.emmetCompletions` setting.
