### ISSUE TITLE
Terminal in VSCode 1.56.1 will not run .bat file under arg when term is started.

### ISSUE THREAD

**Issue by Chris24918** [microsoft/vscode#123602]
This was in the settings.json file before upgrade:
"terminal.integrated.shell.windows": "cmd.exe",
 "terminal.integrated.shellArgs.windows": ["/k", "C:\\Users\\ADV-CON\\esp\\esp-idf\\export.bat"]

After 1.56.1 upgrade the above was labeled depreciated and will not work.

So as stated within this release I included in place of the above:
 "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe ",
        "${env:windir}\\System32\\cmd.exe "
      ],
      "args": [ "/k","C:\\Users\\ADV-CON\\esp\\esp-idf\\export.bat"],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash"
    }
  },

- VS Code Version:1.56.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.Use terminal.integrated.profiles.windows  to run batch file when term is opened.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
What happened when you included the above new settings? Any errors in the dev tools console? /needs-more-info

**Comment by Chris24918** [comment]
> What happened when you included the above new settings? Any errors in the dev tools console? /needs-more-info

Terminal opens, no errors within the console.  The new method just doesn't handle the argument entry like terminal.integrated.shellArgs.windows did in previous version.  My batch file runs the defined paths needed to compiler for the ESP-idf.  Of course I can run the batch file from the command prompt manually then use my compiler.

**Comment by Tyriar** [comment]
Did you set `"terminal.integrated.defaultProfile.windows": "Command Prompt"`?

**Comment by Chris24918** [comment]
Yes, the default profile is Command Prompt.   However, I did get it to work by using the settings.json in "the hidden directory" AppData/Roaming/Code/User/settings.json.   So apparently it has something to do with taking in the arg settings from my Workspace settings.json.

**Comment by Tyriar** [comment]
For args to work in your workspace you need to set `terminal.integrated.allowWorkspaceConfiguration` currently
