### ISSUE TITLE
Configuration: Replace `generate-vscode-configuration` with static analysis

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#123697]
In order to export the configuration options of the product we have a [gulp task](https://github.com/microsoft/vscode/blob/4eef854ab476207dbbaadfff561fb4e9e6f8294e/build/gulpfile.vscode.js#L471-L471) which launches VS Code and gets that information in a JSON file. This could be done differently by statically analysing the source code a-la [`nls.localize`](https://github.com/microsoft/vscode/blob/fc4b40b63384c9ec5f1a925e2b24d00236b43c29/build/lib/nls.ts#L174-L174).

@roblourens, is there any reason why we never did this?

**Comment by roblourens** [comment]
Yeah, config registration is dynamic code and needs to be executed. It comes from variables and function calls. nls limits what you can do in code, like you can only use string literals.

**Comment by joaomoreno** [comment]
Oh yeah that was it. 🙈 D'oh... let's close this.
