### ISSUE TITLE
Links under 'Feature Contributions' are hard to read (dark themes)

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#123661]
- VS Code Version: 1.55.2
- OS Version: checked on Linux and MacOs

Steps to Reproduce:

1. In the extensions panel, search for an extension (e.g. GitLens).
2. Go to the `Feature Contributions` tab.
3. Observe that the links do not use the user theme colors. In particular, they are hard to read with most dark themes.

![8qXiRbbwPs79Ymp](https://user-images.githubusercontent.com/485572/117963772-1276cb80-b321-11eb-99cf-456f20e1d5c5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
@sandy081 Was second selector supposed to be for `:hover` & `:active` state? Right now both CSS selectors are the same.

**Comment by sandy081** [comment]
Thanks for catching this. Fixed.
