### ISSUE TITLE
Ctrl+C close terminal rather than running process (Windows with Git Bash)

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#12367]
- VSCode Version: 1.5.2
- OS Version: Windows 10 Update 1607

Steps to Reproduce:

1.  Set `terminal.integrated.shell.windows` to the path of your git bash in settings.json
2.  Open terminal, type `ping 8.8.8.8 -t`, then press `Ctrl+C` to terminate the ping command

**Comment by stkb** [comment]
I also use Git Bash on 1.5.2 / Win10 1607 and it's working fine for me (terminates the ping command and not the terminal).

```
Steve@Surface  C:/Users/Steve                                                                                                       
$ ping 8.8.8.8 -t               
Pinging 8.8.8.8 with 32 bytes of data:                                                                                 
Reply from 8.8.8.8: bytes=32 time=26ms TTL=47                                                                                  
Reply from 8.8.8.8: bytes=32 time=27ms TTL=47  

Ping statistics for 8.8.8.8:                                                                                                                                                             
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),                                                                           
Approximate round trip times in milli-seconds:                                                                            
    Minimum = 26ms, Maximum = 27ms, Average = 26ms                                 
Control-C                                                                                                                                                                                
                                                                                                                                                                                         
Steve@Surface  C:/Users/Steve                                                                            
$  
```

In my user settings.json I have
```
"terminal.integrated.shell.windows": "bash.exe"
```

**Comment by chrmarti** [comment]
Works for me with Cygwin's bash.exe. @Tyriar Anything we could check to track this down?

**Comment by Tyriar** [comment]
@Meeeeow some questions:

- Do you get an error on the UI when this happens?
- Do you get an error in the dev tools console (Help > Toggle Developer Tools)?
- Do you have any `terminal.*` settings?

@chrmarti can't think of why this would happen, it's probably some edge case that's difficult to repro.

**Comment by Meeeeow** [comment]
@Tyriar 
I find out another bash.exe in Git\usr\bin\bash.exe, i think i have use wrong bash.exe yesterday, it place in Git\bin\bash.exe.

Sorry for this, closed.

**Comment by ollwenjones** [comment]
For me in Windows 10, changing

```
"terminal.integrated.shell.windows"
```
from
```
"C:\\devel\\apps\\Git\\bin\\bash.exe"
```
to
```
"C:\\devel\\apps\\Git\\usr\\bin\\bash.exe"
```
did the trick. Changing it to:
```
"bash.exe"
```
Also worked / solved the `ctrl+c` problem, but the readout was not as pretty, and it wasn't picking up globals for `npm`, etc.
