### ISSUE TITLE
Editor override service: `setTimeout` use is a bit weird?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123674]
I stumbled across this code:

https://github.com/microsoft/vscode/blob/0148fdfc35f22739911fb72a461d120615bc9a65/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L133-L135

That seems questionable to me as it is running outside of any context. 

We have ways to trigger notifications with a `delay` if that is the intent.

**Comment by lramos15** [comment]
Yeah ideally we want to listen to an event of the editor input opening. This is what this delay is for, gives enough time for the editor to open and load in.

**Comment by bpasero** [comment]
Can you clarify why you want to await for the editor opening and not just show the notification?

**Comment by lramos15** [comment]
I just felt it was a better UX then showing the notification before you even see anything

**Comment by bpasero** [comment]
I actually take it back, there is no `delay` option in the notification service currently. But I would just show the notification right away.
