### ISSUE TITLE
Typescript doc visible for aliased imports, but not for single ones.

### ISSUE THREAD

**Issue by Elarcis** [Microsoft/vscode#12360]
- VSCode Version: 1.5.2
- OS Version: Windows 7 Service Pack 1
- Typescript version: 2.0.2

Steps to Reproduce:

1.  have a `myClass.ts` file exporting a `MyClass` class. Write some `/** */` doc for that class.
2.  In another file, try the following two ways of importing identifiers:
```Typescript
import { MyClass } from 'myModule';
MyClass // When hovering MyClass, the written doc is not visible.
```

```Typescript
import * as myModule from 'myModule';
myModule.MyClass // When hovering MyClass, the written doc appears.
```

It seems logical that the doc should appear in both cases, is this due to Typescript 2?

**Comment by chrmarti** [comment]
Can reproduce with the given example and TypeScript 1.8 in todays insider build.

**Comment by waderyan** [comment]
Repro'd with latest TypeScript release bits - release-2.0.5 branch. 

Here is code to copy and paste. 

test.ts
```typescript
import { MyClass } from './myModule';
MyClass // When hovering MyClass, the written doc is not visible.

import * as myModule from './myModule';
myModule.MyClass // When hovering MyClass, the written doc appears.
```

myModule.ts
```typescript
/**
 * Some documentation
 */
export class MyClass {

}
```

sending to TypeScript language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11099

**Comment by ramya-rao-a** [comment]
Moving to a future milestone as this cannot be verified at the moment

**Comment by mousetraps** [comment]
Moving to a future milestone as this cannot be verified at the moment.

**Comment by alexandrudima** [comment]
LOL

Attempt no. 4 at verification failed => two options:
A) this item should be kept open with the "bug" label + "upstream" label. Then we can use it as a tracking item for the upstream bug.
B) otherwise, this item should be kept closed without the "bug" label as it was moved somewhere else.

I vote for B)
