### ISSUE TITLE
requiresMessaging flag on renderer and corresponding communication

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#123601]
See https://github.com/microsoft/vscode/issues/123160

After some discussion: this is where we landed:

- Have a `requiresMessaging: boolean | 'optional'` option on the `notebookOutputRenderers` contribution. Defaults to false, but if true then the `context` provided to the notebook renderer's `activate` will have a `postMessage` and `onDidReceiveMessage` event. If `optional`, it _may_ have these properties.
- In the extension host, there is a new API:
	```ts
	export interface NotebookRendererMessaging<T> { // mirror of the renderer API interface
		readonly onDidReceiveMessage: Event<T>;
		postMessage(message: T): void;
	}

	export namespace notebook {
		export function createRendererMessaging<T = any>(rendererId: string): NotebookRendererMessaging <T>;
	}
	```
- VS Code will only load renderers with  `requiresMessaging: true` in scenarios where they have a loadable extension entrypoint. For example, renderer extensions without a browser entrypoint will not be usable in serverless. aznb should not load renderers with side-effects.
- We should add methods for common cross-compatible operations, like file opening/reveals, to the renderer API itself. 
- There will be a new `onRenderer:<renderer id>` activation event that extensions can use to activate when a renderer becomes active. This activation happens asynchronously, and events the renderer sends before activation completes will be buffered.
- We should remove command links (after a migration period) and recommend renderers use this instead

**Q:** Does this duplicate/make redundant kernel preloads?
**A:** The kernel preloads are an extensibility mechanism that multiple renderers can use and share. They are guaranteed to be loaded and available before any renderer is loaded. Additionally, they provide declarative constraints in renderer compatibility that can be reused across productions, where simply saying a renderer has sideEffects does not provide this.

cc @vijayupadya

**Update:** in VS Code, we don't support partial activation. After talking to Alex, doing this is hard, complex, and has wide-reaching implications. So, extensions that have a renderer with `optional` messaging and an entrypoint, but are running in an environment outside of their supported `extensionKind`, will be disabled as usual. (However this does not diminish its usefulness as a flag for use in other environments)

**Comment by connor4312** [comment]
From discussion with Kai, a better phrasing would be `requiresMessaging` instead of "side effects". It's more clear where it's happening, and we use that phrasing throughout the API. Updated the issue.

**Comment by connor4312** [comment]
I've now pushed a working version of this. However, I need to figure out how to make `optional` work correctly. Currently extensions that have a `main`/`browser` entrypoint incompatible with the current environment aren't shown in the extension service or extension points.

**Comment by DonJayamanne** [comment]
@connor4312 
> VS Code will only load renderers with requiresMessaging: true in s
> For example, renderer extensions without a browser entrypoint will not be usable in serverless.

I'm not sure i understand this.
Assume we add renderer communication in one of our renderers. Does this mean in serverless scenario the custom renderer will not be loaded.
E.g. its possible one has a custom renderer with optional features in the renderer, thats not absolutely necessary. I.e. in a serverless scenario I'd prefer to have the the custom rendering, and if communication is available, then thats used.

**Comment by connor4312** [comment]
> Assume we add renderer communication in one of our renderers. Does this mean in serverless scenario the custom renderer will not be loaded.

If will not be loaded if there is a `main` entrypoint and not a `browser` entrypoint.

I swore I posted a followup for this, but we decided in VS Code to not change any of our activation logic, since that opens the pandora's box of partial extension activation. This has been considered before for themes, but it drags in a huge host of issues. So, like any other extension:

- If there is no `main` or `browser` entrypoint in the package.json, the extension and renderer will run everywhere
- If there is only a `main` entrypoint, the extension and renderer will not run in serverless
- If there is both, it will also run everywhere. Note that you could have `browser` point to a stub file.

However, these logic rules are still useful since they apply to the aznb scenario.

**Comment by jrieken** [comment]
fyi - I have moved this out to July since the next round of notebook API will be coming later
