### ISSUE TITLE
Incorrect visualising markdown table

### ISSUE THREAD

**Issue by louistsaitszho** [Microsoft/vscode#1236]
When I want to indent the table, the markdown visualisation fail. The same format works perfectly on GitHub.
![screen shot 2015-12-14 at 11 20 46](https://cloud.githubusercontent.com/assets/3873011/11772191/caaea846-a254-11e5-9b14-eed4efe5ae55.png)
![screen shot 2015-12-14 at 11 20 32](https://cloud.githubusercontent.com/assets/3873011/11772192/cb07711a-a254-11e5-9712-44a6d18045ca.png)

**Comment by bpasero** [comment]
@louistsaitszho can you attach the raw markdown please?

**Comment by louistsaitszho** [comment]
Heres the markdown. Thanks

## Status code
|Status code|Meaning                                                  |
|-----------|---------------------------------------------------------|
|`200`      |Successful                                               |
|`201`      |Something create (account, visit, patient, etc)          |
|`400`      |Somthing's wrong (Usually bugs)                          |
|`403`      |You have no permission (permission = false in role table)|
|`409`      |Some kind of conflict                                    |
|`497`      |Token does not exist                                     |
|`498`      |Token expired                                            |
|`499`      |You have not provide token to me                         |

## Permissions
### Rules on creating new permission
- nouns should be singular
- If the action are listed in the following table, it must start with their corresponding prefix

	| Action               | Prefix | Example       |
	|----------------------|--------|---------------|
	| add/create/insert    |`add`   |`add_patient`  |
	| delete/remove/revoke |`delete`|`delete_token` |
	| read/get/see/check   |`get`   |`get_inventory`|
	| modify/update/edit   |`edit`  |`edit_any_user`|
