### ISSUE TITLE
Dupllicate entry in RUN AND DEBUG

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#123639]
Issue Type: <b>Bug</b>

Create a launch.json file and see RUN AND DEBUG configurations, There are 7 in launch.json but 9 entries in UI

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:16.954Z)
OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64
Remote OS version: Linux x64 5.4.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 8, 5|
|Memory (System)|62.66GB (6.47GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d6eee9fc-6660-477a-8405-4d115a8c0351|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: r2-data_oper|
|OS|Linux x64 3.10.0-957.27.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1256)|
|Memory (System)|251.63GB (8.47GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container cent7.6:2 (/simcent3)|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|Memory (System)|62.66GB (6.47GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
language-gas-x86|bas|0.0.2
emojisense|bie|0.8.0
bracket-pair-colorizer-2|Coe|0.2.0
nightswitch|gha|1.3.0
leek-fund|gis|1.9.6
output-colorizer|IBM|0.1.2
vscode-peacock|joh|3.9.1
vscode-language-pack-zh-hans|MS-|1.56.2
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
scala|sca|0.5.3
cjk-word-handler|Sha|0.1.1
cython|tcw|0.1.0
vscode-icons|vsc|11.4.0
vuetify-vscode|vue|0.2.0
cppincludeguard|aki|1.4.0
better-toml|bun|0.3.2
code-runner|for|0.11.3
getter-setter-generator|Gab|1.4.0
vscode-test-explorer|hbe|2.20.0
path-autocomplete|ion|1.17.1
cpp-getter-setter-generator|Jul|0.0.2
language-julia|jul|1.1.40
vscode-catch2-test-adapter|mat|3.6.26
vscode-language-pack-zh-hans|MS-|1.56.2
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
vscode-gitignore-generator|pio|1.0.3
cmake|twx|0.0.17
remove-empty-lines|use|0.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353
bridgeflightcf:30299255

```

</details>

**Comment by xgdgsc** [comment]
![image](https://user-images.githubusercontent.com/1189869/117928939-d5193a80-b32e-11eb-9c7f-c9b8c55fe328.png)

See this screenshot.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/121148
You will have to do this workaround to clean the dropdown, sorry!
https://github.com/microsoft/vscode/issues/121148#issuecomment-828458208

**Comment by xgdgsc** [comment]
Thanks. I tried deleting this on my local machine, not working. Since I' m using a docker container, what' s the path to delete for vscode server?

**Comment by isidorn** [comment]
I am not sure. I think the local storage we always keep on the local machine and not on the remote
