### ISSUE TITLE
keyborad: no happens when I click the enter button and del button

### ISSUE THREAD

**Issue by warryy** [microsoft/vscode#123630]
Issue Type: <b>Bug</b>

as stated in the title, and vscode throw error: Cannot read property 'rename' of undefined

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.94GB free)|
|Process Argv|--crash-reporter-id f4e88228-e0cb-4ff1-9925-39cd2d53d3eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eden-plugin|car|3.5.1
thrift|cdu|0.0.1
npm-intellisense|chr|1.3.1
EnglishChineseDictionary|Cod|1.0.1
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.213
vscode-leetcode|Lee|0.17.0
color-highlight|nau|2.3.0
vetur|oct|0.33.1
LiveServer|rit|5.6.1
svg-preview|Sim|2.8.3
vscode-status-bar-format-toggle|tom|2.0.0
markdown-all-in-one|yzh|3.4.0
zeplin|Zep|2.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30294353

```

</details>

**Comment by warryy** [comment]
I restarted the app to fix this

**Comment by samuelms1** [comment]
I see this same issue.  I'm not sure what causes it, but after using vscode for awhile suddenly the enter key will not work.  Instead I see the message:

![image](https://user-images.githubusercontent.com/8550267/118153302-fa5f8480-b3d2-11eb-9fd7-57bfcc7bfe7c.png)

I think this occurs after about 2 hrs of developing.  I only noticed this after the last update (very recent) of vscode so I assume it's somehow related.

@warryy Is this issue still happening to you?  Restarting vscode was only a temporary fix for me.  Something causes it to bug out later.  I'm on macOS Big Sur with an intel processor on a MacBook Pro doing Node development.  I'll try to include more details as I notice, but for right now -- another restart...

**Comment by samuelms1** [comment]
Issue just occurred again -- about 60 min after my first post.

I'm not sure I did any coding as I was primarily running a service to test out some feature changes.  I'm using the new tabbed terminals (not sure if that makes a difference).  When the enter key stopped working I didn't see a warning message of any kind, just nothing happened.  I opened a different file and the enter key still wouldn't work and then a warning message "Cannot read property 'rename' of undefined" showed up.

If I use "Shift + Enter" I can still get a newline, though that's obviously annoying.

https://user-images.githubusercontent.com/8550267/118165746-e53e2200-b3e1-11eb-8356-a3d57e597a29.mov

**Comment by samuelms1** [comment]
So -- I noticed that if I ran a compound configuration (runs two node projects in two terminals) then suddenly the enter key and delete keys work again.  If I stop these processes in the terminals, things still work fine.  If I kill the terminals then shortly after the enter key and delete keys stop working.  I run the compound configuration again then things again work fine.

Given that I basically wasn't doing any code changes this morning, I think running this compound configuration somehow caused this.  I just disabled the integrated terminal tabs feature, which is a cool feature that I just barely enabled.  Maybe the issue will go away.
![image](https://user-images.githubusercontent.com/8550267/118170866-d6f30480-b3e7-11eb-9395-e4c023a5c1ff.png)

For now I restarted again to get things working again.  I also ran the compound configuration in the newly opened vscode window and terminated the terminals with no issue observed afterwards.

¯\_(ツ)_/¯

Yeah -- Had to try this out.  I re-enabled the terminal tab feature and ran the compound build.  Things were fine.  Stopped the processes.  Things were fine.  Killed one terminal -- Enter key opens up a prompt for a terminal name -- see video.  I then killed that terminal and now the enter key does nothing (no warning even -- warning seems to be kind of hit and miss).

Video after killing one of the two terminals:
https://user-images.githubusercontent.com/8550267/118171850-ec1c6300-b3e8-11eb-98e4-9c26c5044659.mov

**Comment by samuelms1** [comment]
Confirmed -- this issue only happens when the new "Terminal > Integrated > Tabs: Enabled" feature is enabled AND you open more than one terminal (only tried with 2) AND you kill one of the two terminals.  At this point the enter key has strange behavior and usually does nothing but sometimes either jumps into the open terminal or opens a prompt for naming a terminal.

https://user-images.githubusercontent.com/8550267/118173534-ee7fbc80-b3ea-11eb-9295-4a7080814682.mov

**Comment by samuelms1** [comment]
@warryy please reopen.  This needs to be addressed and I'd prefer to not open a new issue.  Also, please fix typo in the title of this issue.

**Comment by samuelms1** [comment]
@warryy fyi, I opened a separate ticket for this -- https://github.com/microsoft/vscode/issues/123808
