### ISSUE TITLE
Python webbrowser fails when script runs from VS Code integrated terminal

### ISSUE THREAD

**Issue by Miladiouss** [microsoft/vscode#123622]
- VS Code Version: 1.56
- OS Version: Ubuntu 20

Steps to Reproduce:

Run the following python script from the integrated terminal:
```python
import webbrowser
url = 'https://www.google.com'
chrome_path = '/usr/bin/google-chrome'
webbrowser.register('chrome', None, webbrowser.BackgroundBrowser(chrome_path))
webbrowser.get('chrome').open_new_tab(url)
```
The above script runs successfully when executed from Ubuntu's default terminal. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
What's the failure message/what happens? /needs-more-info

**Comment by Miladiouss** [comment]
```
[<some long number>:ERROR:browser_main_loop.cc(1386)] Unable to open X display.
```

**Comment by Miladiouss** [comment]
@Tyriar @deepak1556 - any updates on this issue? Additionally, the problem happens when making a simple Plotly. Internally, Plolty uses the same mechanism to display its plots in the web browser and system terminal can run the python file correctly while the VS Code integrated terminal fails. 

```python
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with fig.show()")
fig.show()
```

This is one instance when VS Code fails to interact with a graphical software. Here is another example when system terminal can handle while the integrated terminal fails: `git rebase -i origin/main`.

**Comment by Miladiouss** [comment]
I've documented multiple examples when VS Code integrated terminal fails to launch GUI applications:

https://stackoverflow.com/questions/71151065/vs-code-integrated-terminal-doesnt-launch-gui-applications

**Comment by Miladiouss** [comment]
Here is [the solution from Stackoverflow](https://stackoverflow.com/a/71165505/7428659):

The `DISPLAY` variable is not set in your VS code shell. Find out the value in your working system terminal:

```shell
echo $DISPLAY
```

Then set the value in VS Code via the [`terminal.integrated.env.<platform>`](https://code.visualstudio.com/updates/v1_15#_configure-environment-of-terminal-sessions) setting. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and search for `Preferences: Open Settings (JSON)`. Add the following entry to the settings file:

```json
"terminal.integrated.env.linux": {
    "DISPLAY": "<your-display-value>"
}
```

Then close and re-open VS Code's terminal. Afterwards, running `echo $DISPLAY` there should output the same value as in your system terminal. This should make GUI applications launchable.
