### ISSUE TITLE
syntax highlight can better

### ISSUE THREAD

**Issue by jiangyuan** [Microsoft/vscode#12362]
- VSCode Version: 1.5.2
- OS Version: win7

![vscode](https://cloud.githubusercontent.com/assets/2785681/18701830/4fe8a878-8011-11e6-8de7-6f36c40eadc8.png)
![webstorm](https://cloud.githubusercontent.com/assets/2785681/18701838/5da01b72-8011-11e6-99fb-f20fe7878f6c.png)

The first screen shot is vs code, and the second is webstorm, can we do it like that ?

**Comment by orta** [comment]
You could install the [Atom JS highlighter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) extension which improves a lot of the highlighting IMO

Before:
![screen shot 2016-09-21 at 13 31 35](https://cloud.githubusercontent.com/assets/49038/18710994/de745522-7fff-11e6-95b9-cf1a0ec5a7a2.png)

After:
![screen shot 2016-09-21 at 13 32 29](https://cloud.githubusercontent.com/assets/49038/18710999/e3245194-7fff-11e6-9830-4fa6ed67bd02.png)

**Comment by jiangyuan** [comment]
@orta It's better, thanks.

**Comment by chrmarti** [comment]
There are many more themes from the community to choose from: https://marketplace.visualstudio.com/vscode/Themes?sortBy=Downloads
