### ISSUE TITLE
Powershell terminal instead of default on restart

### ISSUE THREAD

**Issue by shivrick** [microsoft/vscode#123685]
Issue Type: <b>Bug</b>

I set the default terminal to "Git Bash".
I can now open a new terminal session and it starts with "Git Bash".
However, if I leave the terminal open, then close and re-open VS Code, the terminal starts with Powershell instead.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900T CPU @ 2.10GHz (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.16GB free)|
|Process Argv|. --crash-reporter-id d83701b2-cff9-47c0-9756-5e9260d8dc4e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
atlascode|atl|2.8.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
auto-rename-tag|for|0.1.6
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
vscode-jest|Ort|4.0.0
vscode-yaml|red|0.18.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by meganrogge** [comment]
will be fixed in Insider's tomorrow via https://github.com/microsoft/vscode/pull/123729
