### ISSUE TITLE
Unable to open integrated terminal 

### ISSUE THREAD

**Issue by khanhtc1202** [microsoft/vscode#123690]
- VS Code Version: 1.56.1 (Universal)
- OS Version: Darwin 19.6.0

Steps to Reproduce:
Open integrated terminal using short key (control + `) is not working, the terminal is closed right after as below.

https://user-images.githubusercontent.com/32532742/118004121-26074e00-b384-11eb-8a26-254657b941ea.mp4

Restart can resolve this but it still occurred sometimes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Does the issue reproduce on Insider's?
