### ISSUE TITLE
Default Custom Editor prompt doesn't show custom editor options for filetypes associated with ViewType and Filename Pattern 

### ISSUE THREAD

**Issue by kkukshtel** [microsoft/vscode#123617]
- VS Code Version: 1.56
- OS Version: Windows 10

Steps to Reproduce:

1. [Download Depot from Extension Marketplace](https://marketplace.visualstudio.com/items?itemName=afterschool.depot)
Depot uses .dpo by default to display its custom editor.
2. Associate a .json file with Depot by using { "viewType": "depot.data", "filenamePattern": "*.json" } in settings.json
3. When you try to open a json file for editing, Depot does not appear as an option.

I'm assuming because by Default Depot is setup only to use .dpo? Or is JSON special?

Does this issue occur when all extensions are disabled?: No (due to extension dependency)

**Comment by kkukshtel** [comment]
Also - it seems like viewType / filename pattern settings in workbench.editorAssociations aren't working at all. This was working for me to load a `.cmod` file as a depot file prior to 1.56 but now no longer works:

```
{
    "workbench.editorAssociations": [
    {
        "viewType": "depot.data",
        "filenamePattern": "*.cmod"
    }]
}
```

**Comment by kkukshtel** [comment]
Worth noting as well that the file loads properly at first when VSCode is first opened, but it seems like once it loads defaults or something it breaks and the .cmod file just displays the json content instead of the webview

**Comment by lramos15** [comment]
Ah yes this was sort of by design in the new refactor but I understand how it is confusing. So for your editor for example, you say it handled `*.dpo` but not `*.json` so when a user sets their setting to something that isn't valid for your extension, in this case `.json`, we assume that your extension cannot handle it and therefore don't pass it off. The reason I went this route was because I felt it lessoned the burden on extension authors to not have to deal with someone passing `*.md` files to your image editor for example. Although this change isn't an excuse for proper file validation. I'm willing to revert this change due to it being a change of behavior depending on feedback from you and others. /cc @mjbvz and @Tyriar

**Comment by kkukshtel** [comment]
Thanks for getting back @lramos15 !

I definitely hear where you're coming from. For Depot, because this setting is user-driven, I largely assume a user knows what they are doing when setting this setting and make no guarantees about functionality if they decide to use an incompatible format/file. However, it's important to have this setting for something like Depot that is meant to be a generic data editor, because we obviously can't add in every possible file extension a user may use to the extension's settings.

Additionally, it's crucial to have such a setting work for the primary uses/users of Depot, as it helps us disambiguate between different data types in our application at runtime. If everything was the default `.dpo`, we'd have to try parsing the file first before marshalling it to the correct load function. Having a custom extension though for the file means we know where to load the data right away. So for us we know that `.cmod` is game data, `.cscenario` is map data, etc., even though they are all "Depot" files.

Happy to provide more info here as well if you need it.

**Comment by lramos15** [comment]
If depot can truly handle any file type I would suggest a package.json of this regardless of what the changes are decided here.
```json
"customEditors": [
	{
		"viewType": "depot.data",
		"displayName": "Depot Data",
		"priority": "default",
		"selector": [
			{
				"filenamePattern": "*.{dpo,depot}"
			}
		]
	},
	{
		"viewType": "depot.data",
		"displayName": "Depot Data",
		"priority": "option",
		"selector": [
			{
				"filenamePattern": "*"
			}
		]
	}
],
```

This will say for all non `*.depot` or `*.dpo` make the Depot Editor an option. That way the user can also see the editor in the `Reopen Editor With...` quickpick.

**Comment by kkukshtel** [comment]
Oh this is interesting, but wouldn't it also make Depot feel a bit aggressive for an end-user? It's not that we support all types of files, but that the extension doesn't matter as long as the underlying data (effectively json) is in the right format. If you have another extension that uses any file format, it would prompt Depot as an option every time right? Even for normal scripting files?

**Comment by lramos15** [comment]
Well `"priority": "option"` just means it will show up as an option in the `Reopen Editor With....` command or the `Open With...` explorer context menu. This doesn't mean that there is a prompt for it. The user only gets prompted on defaults.

**Comment by Tyriar** [comment]
Yeah that seems like the way to go 👍. The hex editor for example uses `"priority": "option"` so you can basically only open it by explicitly opening it with the hex editor.

**Comment by kkukshtel** [comment]
Would this save this preference in a user settings file, or would the option have to be used any time someone wants to open a depot file?

**Comment by lramos15** [comment]
It would allow the user to switch to a depot file from any file they choose, but also would allow them to have a setting for it to be the default if they wish.

**Comment by kkukshtel** [comment]
@Tyriar @lramos15 I tried updating the package.json file here to match your suggested config changes, but Depot doesn't present itself as an option. Is there an issue where a single viewType can't have multiple entries in customEditors? The hex editor for example only uses a single entry with the suggested `"priority": "option"` value set. I can also confirm that when Depot's package.json only has the `option`  config, it does correctly appear.

However, I'd definitely like both, as Depot's native extension is `.dpo` and that should work without any extra config on the user's end.

**Comment by lramos15** [comment]
@mjbvz Do you have any ideas what the correct configuration would be in the case of defining two viewtypes for different file patterns and priorities.

**Comment by lramos15** [comment]
@kkukshtel I have reverted the new behavior and now settings will be respected regardless of package.json. You can test this out in the new insiders tomorrow :)

**Comment by kkukshtel** [comment]
Ah thank you so much @lramos15 ! Thanks for tackling this so quickly.

**Comment by kkukshtel** [comment]
Also @lramos15 — when will this make its way into the core release? Just next monthly?

**Comment by lramos15** [comment]
Yep roughly the first week and a half into June.

**Comment by kkukshtel** [comment]
Sounds great! And again, thanks for following up here!
