### ISSUE TITLE
Can't start Jupyter server

### ISSUE THREAD

**Issue by don007git** [microsoft/vscode#123686]
- VS Code Version:
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version:
Windows 10
Steps to Reproduce:

1."ctrl+shift+p".
2.type in "Jupyter: Select interpreter for Jupyter server"

Get below error:
Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('vscode-webview://c8dd3ae1-1477-42c7-a2cc-daed406c5969/') with script ('vscode-webview://c8dd3ae1-1477-42c7-a2cc-daed406c5969/service-worker.js?platform=electron&id=c8dd3ae1-1477-42c7-a2cc-daed406c5969&vscode-resource-origin=https%3A%2F%2Fc8dd3ae1-1477-42c7-a2cc-daed406c5969.vscode-webview-test.com'): ServiceWorker cannot be started.

Does this issue occur when all extensions are disabled?: Not applicable

**Comment by mjbvz** [comment]
Actually duplicate of  https://github.com/microsoft/vscode/issues/122951 based on the error

**Comment by don007git** [comment]
Thank you for reference.
