### ISSUE TITLE
macOS 11.6 latest builds crash on startup

### ISSUE THREAD

**Issue by g8kig** [microsoft/vscode#123693]
- VS Code Version: 1.57.0-insider
- OS Version: Mac OS X 10.11.6 

Steps to Reproduce:

1. Download and unpack Visual Studio Code
2. Run Visual Studio Code

Insiders build too.

Does this issue occur when all extensions are disabled?: Yes/No

Process:               Electron [5997]
Path:                  /Users/USER/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCodeInsiders
Version:               1.57.0-insider (1.57.0-insider)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [5997]
User ID:               501

Date/Time:             2021-05-12 16:48:51.090 +0100
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        638E88C7-B579-E5B5-CC91-39F0159388D3

Sleep/Wake UUID:       73BEA146-E287-481B-9F45-4B0F7EBF38DD

Time Awake Since Boot: 30000 seconds
Time Since Wake:       29000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   spdlog.node                   	0x00000001115e24c3 std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<spdlog::logger>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >,

**Comment by veriotis** [comment]
It's pretty much the same Electron based _spdlog.node_ logging crash reason as under OSX 10.11.6 (El Capitan) too.

See also this [issue here](https://github.com/microsoft/vscode/issues/123374#issue-881460738).

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/123374
