### ISSUE TITLE
Select Default Profile do not actually open gitbash. After relaunch, on startup, it just keeps open PowerShell

### ISSUE THREAD

**Issue by manolis12341234** [microsoft/vscode#123684]
Issue Type: <b>Bug</b>

1. OS: Windows 10
2. Download/Install VScode
3. Open integrated terminal (PowerShell) - ctrl+`
3. Add new Terminal: Git Bash
4. Select Git Bash Terminal
5. Select Default Profile: Git Bash
6. Go back to powershell - kill/destroy it.
7. Let terminal (git bash) open 
9.  (do not close terminal) close VS code
8. Relaunch VS code

It should launch with gitbash terminal. Instead it opens PowerShell.
If we add new terminal then it opens gitbash

The problem is when running python and there is a virtual environment, vscode runs a command to activate virtual environment through power shell and that command do not recognized through git bash. So Virtual Environment do not activated and needs to activated manually!!
The desired (expected) behaviour should be "open bash git then run activate script then (virtual enviroment)-interpreter is selected"

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.23GB free)|
|Process Argv|--crash-reporter-id 2ca24900-0b24-4633-a462-02357d811a6c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30299255

```

</details>

**Comment by meganrogge** [comment]
Will be fixed as of tomorrow on Insider's via https://github.com/microsoft/vscode/pull/123729

**Comment by msieurtoph** [comment]
Hi @meganrogge ,
This issue is not fixed. 
I am using vscode 1.57.1 (Windows_NT x64 10.0.19042) and it keeps opening powershell instead of gitbash at startup.
