### ISSUE TITLE
Search in files not working

### ISSUE THREAD

**Issue by miwel04** [microsoft/vscode#123631]
Issue Type: <b>Bug</b>

Launch Vscode (no workspace or folder active).
Drag many files into VS code. 
Ctrl Shift F to search.
Results only presented for ONE file, whichever is shown in the currently active tab.
Search will only include the rest of the files After I clicked each one of their tabs at least once.

VS Code version: VSCodium 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-09T00:50:25.642Z)
OS version: Windows_NT x64 10.0.19042

Happens with all extensions disabled? Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (41.40GB free)|
|Process Argv|--max-memory=8192|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
linehighlightbookmarkvscode|bal|0.0.1
highlight-line-vscode|cli|0.0.1
ini-for-vscode|Dav|0.0.4
vscode-icons|vsc|11.4.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you sure you don't have https://code.visualstudio.com/updates/v1_53#_search-in-open-editors enabled to search only it open editors?

Is it reproducible in official builds?

**Comment by miwel04** [comment]
> /needsMoreInfo
> 
> Are you sure you don't have https://code.visualstudio.com/updates/v1_53#_search-in-open-editors enabled to search only it open editors?
> 
> Is it reproducible in latest official builds 1.56?

Hi thanks for the reply. When I add this to my settings.json, I get it greyed out : unknown configuration setting. I am using VsCodium official release, 1.55.1.
Maybe this is not a bug, maybe this is how it is designed to work?

**Comment by IllusionMH** [comment]
Latest official VS Code builds are available here: https://code.visualstudio.com/Download and latest version is 1.56, not 1.55

This repo is for VS Code, not VSCodium which is fork of this repo.

**Comment by miwel04** [comment]
> Latest official VS Code builds are available here: https://code.visualstudio.com/Download and latest version is 1.56, not 1.55
> 
> This repo is for VS Code, not VSCodium which is fork of this repo.

Well thats true, I will close this issue and move it over there to VSCodium.
