### ISSUE TITLE
New terminal tabs do not display name of pseudo terminal

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#123634]
- VS Code Version: 1.56.1
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Enable terminal tabs:  `"terminal.integrated.tabs.enabled": true`
2. Use an extension that opens a pseudo terminal (I use [Calva](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva) then the command **Fire up the Getting Started REPL**)

Looks like so if I hover the blank line below the default `zsh` terminal.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/30010/117921839-b9dc0a00-b2f1-11eb-881f-7796f6109cfb.png">

I am a maintainer of Calva, so this could be that I am not implementing the `vscode.Pseudoterminal` API correctly, but I don't see what I could be missing.

Does this issue occur when all extensions are disabled?: Yes/No
I don't know of a way to start a pseudo terminal w/o an extension doing it.

**Comment by Tyriar** [comment]
This should be fixed in Insiders

**Comment by PEZ** [comment]
Indeed, fixed in Insiders. I should have tested that first. Thanks!
