### ISSUE TITLE
Version 1.56.1 hangs on CentOS 7

### ISSUE THREAD

**Issue by danr97070** [microsoft/vscode#123606]
Issue Type: <b>Bug</b>

The VS Code version 1.56.1 hangs when starting on CentOS 7.  Mulitple people have experienced the problem as reported online.  Microsoft keeps closing the issue; please fix!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 3.10.0-957.el7.x86_64

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/115784

Please install gcc-5 or higher toolchain as temporary workaround.

**Comment by danr97070** [comment]
That doesn’t appear to work

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose` ?

**Comment by J-M0** [comment]
This solution from another issue worked well for me: https://github.com/microsoft/vscode/issues/115784#issuecomment-817187000

>Here's a solution that worked for me ...
>
> * install ghettoforge repo for CentOS 7
>`yum --nogpg install https://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm`
> * install gcc10-libstdc++.x86_64
>`yum install gcc10-libstdc++.x86_64`
> * create link to new libstdc++ where VSCode will find it at runtime
>`ln -s /opt/gcc-10.2.1/usr/lib64/libstdc++.so.6 /usr/share/code/`
> * run code
>`code`

**Comment by danr97070** [comment]
I tried these steps.  Didn’t work for me…

**Comment by J-M0** [comment]
What happens when you run `code --verbose`?

**Comment by danr97070** [comment]
I haven’t had a chance to do that yet.  I may have a chance to try it today...

**Comment by danr97070** [comment]
The —verbose option indicated the source of the problem:  CXXABI_1.3.9 not found.  I’ve searched a number of places and it doesn’t seem straightforward to fix.  I’ve installed a newer compiler; it doesn’t fix the problem.

Apparently I’m going to have to either abandon Visual Studio Code or wait for Microsoft to fix it.  I don’t have a lot of confidence that Microsoft is suitably knowledgeable about Linux…

**Comment by J-M0** [comment]
Can you show me the output of `ls -l /usr/share/code`?
