### ISSUE TITLE
ignoreFocusOut option does not take effect in windows10+WSL(ubuntu 20) envirenment

### ISSUE THREAD

**Issue by jayzhang** [microsoft/vscode#123689]
- VS Code Version:1.56.1
- OS Version: Windows 10 enterprise 21H1
- Using `Remote WSL` to open the folder in WSL(ubuntu) environment. 

Steps to Reproduce:
In vscode extension code, 
1. create a QuickPick with option `ignoreFocusOut = true`
2. create and show another UI without close the first QuickPick, then the first QuickPick lose focus and hided. (The expected result is that the QuickPick will not disappear according the sematic of `ignoreFocusOut = true`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by TylerLeonhardt** [comment]
@jayzhang this is expected behavior.

The `ignoreFocusOut` only handles when the UI loses focus (when the user clicks outside of the quick pick, I.e. In the editor).

The `show()` APIs say:

> Makes the input UI visible in its current configuration. Any other input UI will first fire an `QuickInput.onDidHide` event.
>
> from https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E

Thus hiding the previous quick pick and showing the second one.
