### ISSUE TITLE
Intellisense: break new lines in description

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12366]
![image](https://cloud.githubusercontent.com/assets/22350/18704653/15a88ef6-7feb-11e6-8082-4d1df2606e26.png)

**Comment by joaomoreno** [comment]
Dependent on #12302

**Comment by joaomoreno** [comment]
Actually... if I make this change, all we'll see is `Syntax:`. So I will hold off until we get Markdown.

**Comment by noakup** [comment]
If possible, try to provide this fix asap. We find the current new-lines trimming behavior causes unexpected display of the text... we will accommodate required text changes on our side (btw the "syntax" title was removed already, so it won't be a problem for us.)
