### ISSUE TITLE
I am doing frequent operations in the editor and it says too many frequent settings syncs

### ISSUE THREAD

**Issue by srinathgs** [microsoft/vscode#123678]
Issue Type: <b>Bug</b>

I am changing case of a lot of variables to Pascal Case using Change all occurrences and selecting Convert to pascal case from the command palette. But, it keeps saying there are too many requests to the server and is disabling settings sync.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (2.08GB free)|
|Process Argv|--crash-reporter-id 8b6d2f66-1773-4925-b6da-cf5e84f3a68f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
string-converter|ada|0.1.2
project-manager|ale|12.1.0
toml|be5|0.5.1
vscode-tailwindcss|bra|0.6.3
better-toml|bun|0.3.2
gotemplate|cas|0.4.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
yash|dao|0.2.8
jshint|dba|0.11.0
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
LogFileHighlighter|emi|2.11.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.4.0
abnf|for|1.0.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
go|gol|0.24.2
beautify|Hoo|1.5.0
latex-workshop|Jam|8.18.0
restructuredtext|lex|153.0.0
autoconf|mae|0.1.0
VS-code-vagrantfile|mar|0.0.7
rust-analyzer|mat|0.2.591
vscode-language-babel|mgm|0.0.31
vscode-elixir|mjm|1.1.0
azure-pipelines|ms-|1.183.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-kubernetes-tools|ms-|1.3.2
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
vsliveshare|ms-|1.0.4272
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
vetur|oct|0.33.1
advanced-new-file|pat|1.2.2
proto|pet|0.0.2
material-icon-theme|PKi|4.6.0
vscode-css-peek|pra|4.2.0
text-power-tools|qcz|1.27.0
vscode-thunder-client|ran|1.2.2
fabric8-analytics|red|0.3.3
java|red|0.79.1
vscode-commons|red|0.0.6
vscode-xml|red|0.16.0
vscode-yaml|red|0.18.0
ragel|RRe|0.0.1
vscode-paste-and-indent|Rub|0.0.8
scala|sca|0.5.3
prettier-vscode|Sim|2.0.7
vscode-fileutils|sle|3.4.5
svelte-vscode|sve|104.12.1
pdf|tom|1.1.0
cmake|twx|0.0.17
vscode-bnf|Val|0.0.1
vscodeintellicode|Vis|1.2.13
vscode-svg-previewer|vit|0.7.0
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
pestfile|xor|0.0.2
ooxml-viewer|yue|1.1.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.14

(3 theme extensions excluded)

</details>

**Comment by egamma** [comment]
/needsMoreInfo

Please describe the initial setup and then the detailed steps to reproduce the problem.
