### ISSUE TITLE
Editor pane is undefined when actions get computed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123676]
Steps to Reproduce:

1. open settings editor
2. 🐛 no actions appear in the editor toolbar

This seems to be a regression from the trust editor control.

**Comment by bpasero** [comment]
It looks like the editor control is not fit for an `async` here:

https://github.com/microsoft/vscode/blob/2bcb8dfb64185e6ee8828e707f21f0d078af7fb8/src/vs/workbench/browser/parts/editor/editorControl.ts#L86-L86

If possible we should see if `requiresWorkspaceTrust` can execute `sync`.

**Comment by bpasero** [comment]
Pushed https://github.com/microsoft/vscode/commit/9553ccbe6ed0224f2168c6fe503d2f20c55c1825 as workaround to unblock our build today. This basically disables the trusted editor.

**Comment by bpasero** [comment]
The culprit is this method:

https://github.com/microsoft/vscode/blob/7bec90ca469e943090beda87c20d3f2f67e2f19c/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L983-L1014

As you can see, the `openEditorPromise` is not awaited on, the title area control is updated right away. I recall I do this for perf reasons so that e.g. clicking a file in the explorer results in the tab appearing as fast as possible without `async` code involved.

Again, I think we should then revisit the decision of having [`requiresWorkspaceTrust`](https://github.com/microsoft/vscode/blob/2bcb8dfb64185e6ee8828e707f21f0d078af7fb8/src/vs/workbench/common/editor.ts#L580-L580) be `async`.

**Comment by sbatten** [comment]
pushed https://github.com/microsoft/vscode/commit/b61721e94d61332446a911594dfcc199ad3ddc3f to try sync version. I quickly spoke to @roblourens and he thought they'd be able to do it sync in the notebook editor input, so if it also works for custom editor inputs, then we should be fine.
