### ISSUE TITLE
workspace.findfiles() always return 10 result?

### ISSUE THREAD

**Issue by Dollyn** [Microsoft/vscode#12364]
- VSCode Version: 1.5.2
- OS Version: windows10

Steps to Reproduce:

`
            vscode.workspace.findFiles("*.*", "", 20).then(value => {
                let count = value.length;
                console.log(count); // always get 10 here
                for (let _i = 0; _i < value.length; _i++) {

`

**Comment by chrmarti** [comment]
This works for me. Did you mean to search for '*' instead of '.'?

What is the list of results returned and what are the files you have in the workspace?

**Comment by Dollyn** [comment]
My fault, I should use **/* instead.
