### ISSUE TITLE
.vue  style lang

### ISSUE THREAD

**Issue by chenguo666** [microsoft/vscode#123628]
<style scoped lang="less"> ==><stylelang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang=lang="less" scoped >

**Comment by chenguo666** [comment]
![](https://ftp.bmp.ovh/imgs/2021/05/959741603841d519.gif)

**Comment by aeschli** [comment]
Sorry, please gibe details steps. The screen cast is very small.
Are you in a HTML file or a Vue file?
