### ISSUE TITLE
Unable to press commit button with tab navigation

### ISSUE THREAD

**Issue by saharso** [microsoft/vscode#123637]
Try reaching the "commit" button with the keyboard - either with tab or shift+tab, and the navigation will skip the button. I reported the issue before. It was fixed, and now I notice it again.
![image](https://user-images.githubusercontent.com/19216444/117926144-f6fbc880-b300-11eb-9905-f1d668630d21.png)

**Comment by lszomoru** [comment]
@saharso, sorry for not getting back to you on this issue.
You can reach the "commit" button using the keyboard by:
1. use tab or shift+tab to move the focus onto the action bar
2. use the left/right arrows to move the focus to the various actions in the action bar
