### ISSUE TITLE
Default profile for integrated terminal is not reliable immediately after starting (and after loading workspace)

### ISSUE THREAD

**Issue by jeffrson** [microsoft/vscode#123642]
- VS Code Version: 1.56.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Set "terminal.integrated.defaultProfile.windows": "Command Prompt",
2. Open integrated terminal => it's a command prompt
3. Close VSCode, leaving terminal open
4. Restart VSCode => terminal is Powershell Core

The same happens when the terminal shall be started via menu immediately after launching VSCode.

And it happens as well, as I open a folder or work space via MRZ list on "Gettings started" page if that folder or work space had an open terminal when accessed last.

Does this issue occur when all extensions are disabled?: Yes

It does not seem to happen (at least rather rarely) when an empty folder with extensions disabled is opened.

Looks very much like a race.

**Comment by mmontagnana** [comment]
I just came here to talk about the same behavior, I performed the same steps and had the same findings.

**Comment by meganrogge** [comment]
This should be fixed in Insider's tomorrow via https://github.com/microsoft/vscode/pull/123729
