### ISSUE TITLE
[bug] Recent Updates makes Shell Command `code .` opens incorrect folder in macOS 10.15.7

### ISSUE THREAD

**Issue by tommyZZM** [microsoft/vscode#123640]
- VS Code Version: 
```
Version: 1.56.1
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:24.325Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```
- OS Version: `macOS Catalina 10.15.7`

Steps to Reproduce:

1. `code .` always opens system root folder `/`. which is incorrect!

    But `code $(pwd)` can get the right result

2. this bug happens recently, few days ago.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aksdevac** [comment]
working fine for me on `1.56.1` & Mac OS `11.3.1`.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tommyZZM** [comment]
Hello @bpasero The insiders version `code .` works fine for me now.

I rename `Visual Studio Code - Insiders.app` to `Visual Studio Code.app` and replace the .app

**Comment by tommyZZM** [comment]
Hello @bpasero , This issue reproduce in the latest nightly insider builds toady.

**Comment by bpasero** [comment]
@tommyZZM are you starting code from the integrated terminal in VSCode itself or from an external terminal?

**Comment by tommyZZM** [comment]
Hello @bpasero ,  i m starting `code` from external terminal. The `Terminal.app`

gif here.

![www](https://user-images.githubusercontent.com/6326007/119444254-7f488780-bd5d-11eb-97eb-9fa7781c0f85.gif)

**Comment by bpasero** [comment]
Can you try to run `code . --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by deepak1556** [comment]
Can you provide the output of `NODE_DEBUG="child_process" code . --verbose`, if you think it has sensitive data, you can forward the logs to Deepak.Mohan@microsoft.com

**Comment by tommyZZM** [comment]
Hello @bpasero @deepak1556 , 

Thx, Both `code . --disable-extensions --user-data-dir ~` and `code .` seems works fine for me again today

**Comment by bpasero** [comment]
Ok, let us know when you can reproduce again somehow.
