### ISSUE TITLE
Test runner: reports success when tests can still timeout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123646]
If you run a test suite from within the editor where one or more tests fail after a 5ms timeout, the suit still shows a green mark indicating success only to later report the failure.

**Comment by connor4312** [comment]
Hm, I don't see this just adding a `timeout(6000)` to one of my tests

![](https://memes.peet.io/img/21-05-1867c91c-bd86-4f83-b9e3-e2c3e6c955e2.png)

**Comment by bpasero** [comment]
@connor4312 steps:
* open `fileWorkingCopyTest.ts`
* in the `orphaned tracking` test, change `onDidChangeOrphanedPromise` to be `new Promise(() => { })`
* run the entire suite
* notice how the suite reports green success even though one test has not finished

![recording](https://user-images.githubusercontent.com/900690/118109149-1b2ed680-b3e1-11eb-93ca-68a70f642cc2.gif)
