### ISSUE TITLE
Multiple filetype icon themes render side by side

### ISSUE THREAD

**Issue by androidu** [Microsoft/vscode#12369]
- VSCode Version: 1.5.2
- OS Version: Windows10 Pro

It's hard to reproduce but sometimes when switching icon themes, the old and the new icon theme render side by side.
It looks like the old icon theme get's cached somehow somewhere.

Steps to reproduce:
1. Download and set an icon theme. 
2. Close and reopen VSCode.
3. Go into FILE ICON THEME category and change to other icon pack theme.

I can reproduce the issue with `--disable-extensions` as well.

![icons](https://cloud.githubusercontent.com/assets/1185797/18706050/07093018-7ff9-11e6-8c7b-ec2d26287353.gif)

![screenshot_327](https://cloud.githubusercontent.com/assets/1185797/18705709/ee22b49e-7ff7-11e6-86b7-a682829af4ea.png)

![screenshot_328](https://cloud.githubusercontent.com/assets/1185797/18706311/2e316e20-7ffa-11e6-95ae-2809491440be.png)

**Comment by bpasero** [comment]
@androidu you have the vscode-icons extension installed which patches our bits. the only fix is to completly uninstall and reinstall VS Code.
