### ISSUE TITLE
"&" is automatically added in terminal command line when I click to Run Python File in terminal.

### ISSUE THREAD

**Issue by Dunroxiz** [microsoft/vscode#123654]
Issue Type: <b>Bug</b>

So after yesterday's update of Vscode Python Extension and Jupyter Extension.
I'm encountering this problem.
When I click on Run Python File in terminal. 
it automatically adds an '&'  at the start of the command. and because of it the bash terminal gives me an error. Then I have to manually remove the '&' from the command line to run the file.

```bash
Dunroxiz_GitBash(Win64):> 
$ & D:/GAMES/anaconda/python.exe "e:/Study Materials/A Levels/A Level Computer Science (9618)/Programming and Problem Solving/AS Level/Python/Task14/task14.04.py"
bash: syntax error near unexpected token `&'
```

Any help on this. and I'm new to Vscode.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (4.38GB free)|
|Process Argv|--crash-reporter-id 76f9cef9-2e52-4c95-8d7a-f0c4681dbaec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.40.4
gitlens|eam|11.4.1
latex-workshop|Jam|8.18.0
kite|kit|0.142.0
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
material-icon-theme|PKi|4.6.0
markdown-preview-enhanced|shd|0.5.18
code-spell-checker|str|1.10.2
material-theme|zhu|3.10.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by gateslm** [comment]
I have the same issue as well. Reported it on VSCode Python as well. 
https://github.com/microsoft/vscode-python/issues/16219
