### ISSUE TITLE
Update to VSCode 1,56.1 and now getting certificate errors on REST calls from my extension. V 1.55.2 works fine

### ISSUE THREAD

**Issue by urvapatel** [microsoft/vscode#123699]
- VS Code Version: 1.56
- OS Version: macOS big sur 11.3.1

I'm getting a certificate error when making a POST call using axios for a vscode extension. It was working before an update to 1.56.1. I also have rejectUnautorized set as false in the code so it should work as it was before this update.

[2021-05-12T10:56:23.412-04:00][ERROR] Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does
not match certificate's altnames: Host: cpd-tooling-2q21-cpd.apps.cpstreamsx7.cp.fyre.ibm.com. 
is not in the cert's altnames: DNS:internal-nginx-svc, DNS:*.svc.cluster.local, DNS:api-svc, 
DNS:*.api, DNS:ibm-nginx-svc, DNS:zen-core-api
    at Object.checkServerIdentity (tls.js:297:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)```

also tried changing certificate, would get this error as well. This also didnt happen before the update

<img width="1670" alt="Screen Shot 2021-05-12 at 9 26 09 AM" src="https://user-images.githubusercontent.com/66275050/118009143-cf662980-b31b-11eb-9382-12f12ebfe88a.png">

Steps to Reproduce:

1. download ibm streams extension
2. try to add an instance

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please report the issue against the ibm streams extension.
