### ISSUE TITLE
Dataloss when closing Code before it fully restored with dirty files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123636]
Steps to Reproduce:

1. open a folder and 1 file, make it dirty
2. close VSCode
3. from the command line run `code "path to folder" "path to a file in that folder (not the dirty one)"`
4. very quickly when that file opens, quit VSCode before the dirty file restored (this might need a few attempts)
5. start again

🐛 the backup is lost.

**Comment by bpasero** [comment]
To verify: ensure the backup is always restored, opening as a second editor besides the one instructed from the command line.

**Comment by lramos15** [comment]
I'm pretty sure I'm still seeing this
