### ISSUE TITLE
Terminal scrolls up when typing a command

### ISSUE THREAD

**Issue by DarkLite1** [microsoft/vscode#123641]
- VS Code Version:
Version: 1.56.1 (system setup)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:05.141Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.14393

- OS Version:` Windows Server 2016

## Steps to Reproduce:

1. Run 'Get-Process' in the terminal
2. Make the terminal panel larger by dragging the separator upwards
3. Scroll in the terminal pane so you see the prompt as the last line against the bottom edge of vscode and the output of 'Get-Process' populating the remaining terminal pane (we do this because we want to see some data at the top)
4. At the prompt, which is now located at the bottom, you type another command 'Get-Service' for example
 
6Notice the terminal prompt moves to the middle of the terminal pane and doesn't stay at the bottom.

After step 3 you see this:
![image](https://user-images.githubusercontent.com/10828570/117930225-03caed00-b2fe-11eb-8f10-1817029e4d22.png)

At step 4 when you type the first letter in the terminal you see this:
![image](https://user-images.githubusercontent.com/10828570/117930308-20ffbb80-b2fe-11eb-87a9-d5c35665ec4b.png)

This makes it really annoying if you want to see some data at the top while typing commands. You just can't see it anymore after you start typing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Thanks for the issue. Did this start happening recently? What do you have `terminal.integrated.scrollback` set to?

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by DarkLite1** [comment]
@Tyriar so we need to switch to `compty`? Is that a setting somewhere?

**Comment by Tyriar** [comment]
@DarkLite1 it's a feature of windows 10, I'm assuming the latest windows server would ship with it
