### ISSUE TITLE
Typing in editor pane wraps tabs inconsistently

### ISSUE THREAD

**Issue by ejvet-ct** [microsoft/vscode#123696]
Issue Type: <b>Bug</b>

When multiple tabs are open, with the correct length of filenames, the last tab will keep wrapping to the next row and unwrapping as you type. The outcome of this is that it is difficult to see what is being type as the content jumps up and down. 

The solution is to close a tab.

![Screen Recording 2021-05-12 at 16 58 22](https://user-images.githubusercontent.com/74912333/118007409-051f0880-b344-11eb-98f8-bf0e18a6154a.gif)

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id d63026de-a6f4-4d33-9f34-5ccb00040167|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
prettier-vscode|esb|6.4.0
vscode-styled-components|jpo|1.5.2
java|red|0.79.1
markdown-preview-enhanced|shd|0.5.18
vscode-scss-formatter|sib|2.2.0
vscodeintellicode|Vis|1.2.13
gitblame|wad|7.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352
bridgeflight:30299254

```

</details>

**Comment by bpasero** [comment]
@ejvet-ct does this reproduce if you configure `workbench.editor.decorations.badges: false` ?

**Comment by ejvet-ct** [comment]
@bpasero It would seem that it doesn't, no

**Comment by bpasero** [comment]
@ejvet-ct there is unfortunately not much to do here, if decorations come and go the size of tabs can change while typing which can result in wrapping.

**Comment by ejvet-ct** [comment]
@bpasero But, from the gif it doesn't look like the value in the tab actually changes visually, even though it causes a wrap when some sort of padding changes. It does appear however, that there is the slightest movement of the unsaved changes icon as it wraps.

**Comment by bpasero** [comment]
Yeah true there is some weird jump in the dirty icon. Do you have some steps for me how to reproduce, possibly with the same files and same window dimensions?

**Comment by ejvet-ct** [comment]
Hmm, to be honest It looks like that is because of the wrap, not the cause of it. And no I just tried to systematically reproduce, and I can't nail it down sorry.

**Comment by bpasero** [comment]
Yeah I recall a similar issue a while ago that we were not able to figure out steps to reproduce...
