### ISSUE TITLE
promptToUpdatePowerShell not work

### ISSUE THREAD

**Issue by HppZ** [microsoft/vscode#123656]
- VS Code Version: 1.56.1
![image](https://user-images.githubusercontent.com/12285582/117956313-8332dd80-b34b-11eb-9217-6b0871d8df68.png)

- OS Version: 19042.928

![image](https://user-images.githubusercontent.com/12285582/117956286-7ca46600-b34b-11eb-9163-626e7dfca7e0.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by TylerLeonhardt** [comment]
Hi @HppZ! Couple of things...

First off, that setting and feature is provided by the PowerShell extension, which can be found here:

https://github.com/PowerShell/vscode-powershell 

Additionally, that setting only controls notification that pops up in vscode. The notification your seeing in the console is from PowerShell itself.

That can be disabled by putting this in your PowerShell profile:

`$Env:POWERSHELL_UPDATECHECK = 'Off' `

If you want the extension to do more here, please open an issue on vscode-powershell.

Cheers!

**Comment by HppZ** [comment]
this `NoLogo` config disables that update tip in Windows Terminal, but not in VSCode.
![image](https://user-images.githubusercontent.com/12285582/118206066-563e1200-b494-11eb-9f1b-07ddf246ea38.png)
![image](https://user-images.githubusercontent.com/12285582/118206614-73bfab80-b495-11eb-9f53-3e893a1a8821.png)

**Comment by TylerLeonhardt** [comment]
@HppZ does your terminal tab/dropdown say "pwsh" or "PowerShell Integrated Console"?

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/118208928-36115180-b49a-11eb-86a0-81470bb7d5fc.png)

**Comment by TylerLeonhardt** [comment]
Sorry I meant in vscode @HppZ

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/118209439-3100d200-b49b-11eb-886c-4631d0326798.png)
![image](https://user-images.githubusercontent.com/12285582/118209458-39f1a380-b49b-11eb-905a-2d0d64c51bd5.png)

**Comment by HppZ** [comment]
did you mean that above?

**Comment by TylerLeonhardt** [comment]
Yeah ok that's what I wanted to see. @meganrogge args might not be being honored.

**Comment by meganrogge** [comment]
![recording - 2021-05-14T092115 842](https://user-images.githubusercontent.com/29464607/118299529-b7b2b080-b495-11eb-9048-8db7cd6e50d4.gif)
Works for me on Insider's

**Comment by Tyriar** [comment]
You're probably seeing https://github.com/microsoft/vscode/issues/123188

**Comment by HppZ** [comment]
> ![recording - 2021-05-14T092115 842](https://user-images.githubusercontent.com/29464607/118299529-b7b2b080-b495-11eb-9048-8db7cd6e50d4.gif)
> Works for me on Insider's

work for you but not for me.

**Comment by Tyriar** [comment]
@HppZ did you try it using the insiders build? https://code.visualstudio.com/insiders

**Comment by HppZ** [comment]
no insider build installed.

**Comment by HppZ** [comment]
why closed?
