### ISSUE TITLE
[macOS 11]  Command + W No Longer Closing Application Window

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode#123649]
Command + W No Longer Closing Application Window on macOS 11.3.1 (Big Sur)

- VS Code Version: 1.57.0-insider
- OS Version: macOS 11.3.1

Steps to Reproduce:

1. Command + W
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/123512#issuecomment-837870197

**Comment by conradwt** [comment]
In macOS, it standard behavior that all applications have Command + W keybinding to close the front-facing window.  For reference, one can review the following documentation:

https://support.apple.com/en-us/HT201236

**Comment by bpasero** [comment]
@conradwt yes I agree and see https://github.com/microsoft/vscode/issues/54492#issuecomment-826505242 for my analysis. But taking `Cmd+W` away to close a tab seemed like the worse solution.

**Comment by shamelesscookie** [comment]
I liked the original behavior (CMD+W closes the window when no editors are open).

I had to set the following in `keybindings.json` to get the old behavior back:

```
{
  "key": "cmd+w",
  "command": "workbench.action.closeWindow",
  "when": "!editorIsOpen && !multipleEditorGroups"
}
```
