### ISSUE TITLE
Emmet and auto suggestion don't work in VS code portable.

### ISSUE THREAD

**Issue by rafidalhaque** [microsoft/vscode#123680]
- VS Code Version:  1.56.01
- OS Version: Windows 10

Emmet and auto suggestion don't work in VS code portable.
![image](https://user-images.githubusercontent.com/68812773/117981879-466ce380-b357-11eb-8018-039b2895af7c.png)

**Comment by rzhao271** [comment]
When you open the command palette, and then search for Emmet commands, do you see all of them, or do you only see one?
If you only see one, Emmet is probably disabled. See https://github.com/microsoft/vscode/issues/123388 for details there.

**Comment by rafidalhaque** [comment]
I can fix it, thanks
