### ISSUE TITLE
Integrated terminal with zsh will not source Python virtual env correctly

### ISSUE THREAD

**Issue by jamesohortle** [microsoft/vscode#123616]
- VS Code Version: 1.56.0 (Universal)
- OS Version: macOS Big Sur 11.3.1 (20E241)

Steps to Reproduce:

1. Mac's default shell is zsh, no longer bash.
2. Create a virtual env using `python3 -m venv .venv`
3. Set Python interpreter to point to `.venv/bin/python`
4. Open integrated terminal (zsh)
5. The following output is printed 
```
source /Users/jim/specialist-spell-checker/.venv_dev/bin/activate
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? compinit: initialization aborted
complete:13: command not found: compdef
jim@192-168-1-101 specialist-spell-checker % ource /Users/jim/specialist-spell-checker/.venv_dev/bin/activate
zsh: command not found: ource
```
6. The virtual environment is not activated

Does this issue occur when all extensions are disabled?: Yes, but slightly differently: The first prompt from zsh compinit to "ignore insecure directories" is active, so you can type `y` or `n` but this still does not let the virtual environment be activated.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
