### ISSUE TITLE
Split Terminal does not keep current workspace

### ISSUE THREAD

**Issue by HadesD** [microsoft/vscode#123625]
Issue Type: <b>Bug</b>

1. Open multiple (>=2) directory workspace
2. Open Terminal for first dir
3. Open Terminal for second dir
4. Open Split for second dir
=> Current workspace moved to first dir location

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.08GB free)|
|Process Argv|--crash-reporter-id 7c5662f6-b827-4aab-9843-8d925366cea5|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer|Coe|1.0.61
vscode-react-proptypes-intellisense|cun|0.0.4
vue-peek|dar|1.0.2
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
php-intellisense|fel|2.3.14
vue-snippets|hol|1.0.4
cmake-tools|ms-|1.7.2
vetur|oct|0.33.1
react-proptypes-intellisense|OfH|1.0.3
laravel-blade|one|1.25.0
vscode-blade-formatter|shu|0.7.12
cmake|twx|0.0.17
vim|vsc|1.20.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by meganrogge** [comment]
I can't reproduce the issue in Insider's. can you try that and inclue a [gif](https://gifcap.dev/)?

**Comment by HadesD** [comment]
![recording](https://user-images.githubusercontent.com/11664992/123509700-f4d3aa80-d6b1-11eb-9d50-4fcfa9651e03.gif)

**Comment by HadesD** [comment]
@meganrogge please re-open and check the image
thanks
