### ISSUE TITLE
Regex find within a file produces different results to `Find in Files` 

### ISSUE THREAD

**Issue by colinbull** [Microsoft/vscode#12371]
- VSCode Version: 1.5.2, Node: 5.10.0, Shell 0.37.6
- OS Version: Windows 7

It appears that `find in files` produces different results when using a regex search with new lines `\n` or lookbehind `?!`. See the screenshot below for an example. I would have expected `find in files` to return a result here. 

![image](https://cloud.githubusercontent.com/assets/585546/18707646/f5a09e10-7fee-11e6-891c-d275e1eae72c.png)

I am aware that `find in files` will omit results if the result set is too large, that is fine and to mitigate this have have specified the directory, again see screenshot. 

**Steps to Reproduce:**

1. Ctrl+Shift+F to open find in files
2. Switch to regex mode
3. Enter a regex with a newline or lookbehind, there maybe others but these are the only ones I have encountered
4. Hit enter.

Depending on the regex you will either get a handful of results or non at all. However if you search in the file directly it will find all of the occurrences.

Cheers

Colin

**Comment by chrmarti** [comment]
Could not reproduce. @colinbull Does the file use Windows line delimiters?

**Comment by colinbull** [comment]
Yes the file I'm looking at does. But it has the same behaviour even if I use [\r\n]+ which is what I originally tried.

Sorry the screenshot was taken during some experimentation.

**Comment by sandy081** [comment]
@colinbull Multi-line search is not supported in `Find in Files` feature - See #13155

If I am not wrong, look behind expressions are not supported in javascript regex.

duplicates #13155
