### ISSUE TITLE
VSCode interface is over engineered

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#123719]
1) Git commit - if i click with right and would like to open the menu without comparing, it's opening the file also.
Which cause two things, slowness, the popup won't appear, until i don't open all my hundreds file.

2) Position my mouse just in the editor, always some shity popup appears suddenly (i can't position the mouse not to tocuh a popup somewhere), but i didn't want to click for that popup. So it's simply a clickbait, and doing something totally different.

It's simply counter productive.

I have also seen somewhere it's creating a "run" line where you can click, but the problem is the delay.

I would like to copy paste for example, and suddenly with a noticable delay a "run" line appears, so one line has been added to the editor.
(it would be better, if whatever lines the user is changing, don't change the position of that line - scroll instead hidden)

This is true also, when a file has been opened, use scroll instead, when you are adding even more line on the top, as i'm missing the clicks. There is noticable delays, which means 20-100 ms is noticable also, when you would like to click on something.

3) when i'm moving files here and there it's a good, but not always working feature, that changing the file, however if i have 100 files to move (by moving a folder), you can ask, whether i would like to change any of the location.

I have created a backup folder in my project, and it's not being built to the product, but the parser is picking up stupidly as it's a ts file, but it's making it very random, for some folders it works for some folders not. (pls. don't make the assumption, ask the user)

The backup folder is out of the my frontend project, it's next to my server project, which is written in kotlin - it's under the same git repo - it's easier to me to pinpoint the relevant parts between server and frontend. (so in the root there is no configuration what the VSCode can pick up - so why the hell, want to change any location - can highlight, but that's all)

4) In the mongodb plugin, when i select a $match, it's also filling up a bloatware 5 lines for me, what i don't want at all.

Some of them is nocicable in IntelliJ also, but it's a fairly bad practice, as the developers simply loosing the focus on their work.
In normal case i don't need to look for the screen or my mouse or my keyboard, but i can't predict what will happen.

5) In IntelliJ, the most annoying thing is, when i autocomplete something, if there is no space, it's removing the word, whatever is in there, but many times, i just want to add a dot, and don't want to replace, i will delete. (don't make an assumption by an environment, if AI is not built in it, and properly understand the world over there - as in many case even AI is not needed to see that that word is totally unrelated whatever list i'm choosing from) I think it's happening sometimes in VsCode also.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

"one item per issue"
