### ISSUE TITLE
Perf: renderer blocks when doing gulp watch and having many files open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12372]
Steps to Reproduce:

1. have many files open (50+)
2. run gulp watch

=> close to the end when files are being written, the UI hangs
=> seems to be a large amount of deletes hitting our checks for disposing editor models if the associated file gets deleted

/cc @joaomoreno

**Comment by bpasero** [comment]
@joaomoreno can you please attach a profile from dev tools when this happens? I just tried to reproduce with 200 open TS files and could not see this slowdown :-/

**Comment by joaomoreno** [comment]
Can't repro at home either. Let's do it in the office.

**Comment by bpasero** [comment]
We can still see to plan this for September if it turns out to be a low risk fix.

**Comment by bpasero** [comment]
I can reproduce in selfhost now. The critical path is `FileEditorInput.onFileChanges` which gets called a lot during gulp watch. Having a lot of `FileEditorInputs` around does not help either.

**Comment by bpasero** [comment]
Related to https://github.com/Microsoft/vscode/issues/13283

**Comment by bpasero** [comment]
Actually marking as duplicate.
