### ISSUE TITLE
Incorrect links in file vscode.d.ts (API reference)

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#123772]
- VS Code Version: 1.56.1
- OS Version: Windows 10 Prof 64 Bit

Steps to Reproduce:

1. change CustomDocumentProvider to CustomEditorProvider
   - line 7747
   - line 7786

2. interface TaskProvider
   line 6697: create a md link from #tasks.registerTaskProvider

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rambabugovind** [comment]
Hi, I would like to look into this issue. Could I be assigned ?

**Comment by 5150og** [comment]
I'm new to this, but I'm eager to learn!

**Comment by mzainuddin51** [comment]
Hello, can I work on this issue ?

**Comment by mjbvz** [comment]
This is a very small change so please just submit a PR
