### ISSUE TITLE
Drag&Drop is broken when several windows are open (XWayland)

### ISSUE THREAD

**Issue by sbogomolov** [microsoft/vscode#123779]
Issue Type: <b>Bug</b>

1. Open two VS Code windows.
2. Try to drag a tab to reorder. When I try to drag&drop a tab in the first window, it stays where it was plus it gets open in the second window.
3. Try to drag a file in the project browser. File does not get moved, but instead is copied to the project opened in the second VS Code window.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:16.954Z)
OS version: Linux x64 5.11.18-300.fc34.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2396)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|62.79GB (38.40GB free)|
|Process Argv|infra/whitespace-staging-manifests/ --no-sandbox --crash-reporter-id 68be423f-7426-4b5e-bd95-be619d01c366|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|sway|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|sway|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
go|gol|0.25.0
terraform|has|2.10.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.12.1
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
rust|rus|0.7.8
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.13

(1 theme extensions excluded)

</details>

**Comment by elcste** [comment]
Sounds like https://github.com/swaywm/wlroots/issues/2889?

**Comment by sbogomolov** [comment]
@elcste it does look like it indeed.

**Comment by Xyene** [comment]
Yeah, this is a 10-year-old Chromium bug that Sway exposes by not currently implementing `_NET_CLIENT_LIST_STACKING`. 

I've submitted [a fix](https://chromium-review.googlesource.com/c/chromium/src/+/2844104) upstream; I don't think there's anything VS Code can (or should) do here apart from wait for Electron to pick up the change. Separately, Sway may implement `_NET_CLIENT_LIST_STACKING` in the next release.

**Comment by deepak1556** [comment]
@Xyene thanks for upstreaming the fix, will get this backported in Electron to supported release lines.

**Comment by deepak1556** [comment]
Forgot to update here, the upstream fix was backported in May and it has been rolled into our stable release since then.
