### ISSUE TITLE
Linux: Mouse "Back" button should take back to previous file / cursor location

### ISSUE THREAD

**Issue by ronnyle** [Microsoft/vscode#12370]
- VSCode Version: 1.5.2
- OS Version: Fedora 24

This functionality exists in other IDE vendors such as IntelliJ, Sublime

**Comment by Bill-Stewart** [comment]
Do the `workbench.action.navigateBack` and `workbench.action.navigateForward` commands not work?

**Comment by ronnyle** [comment]
Those work, I was actually referring to the mouse back-button. I know this required an extension on Visual Studio (not Code).
Sorry for not being clear..

**Comment by bpasero** [comment]
This requires support from Electron. On windows this actually does work.

**Comment by Naereen** [comment]
Very useful feature, if it can be implemented in Electron.

**Comment by DJWassink** [comment]
Posting issue on electron for reference.
https://github.com/electron/electron/issues/6996

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/15561

**Comment by dtheodor** [comment]
You can work around this by mapping the mouse keys to the appropriate keyboard keys for the navigateBack/Forward actions, through a tool like `xbindkeys`
