### ISSUE TITLE
Can't view images in remote destination [insider 1.57]

### ISSUE THREAD

**Issue by CavalloneChen** [microsoft/vscode#123751]
![image](https://user-images.githubusercontent.com/28266566/118093693-65738000-b400-11eb-8d30-268eca5e5dd5.png)
Can't view png or jpg files in remote destinations (both ssh and wsl). The same image can be viewed locally.

**Comment by mjbvz** [comment]
This should be fixed by 18ea5ac15e6c109184d70eb5d15eeee1a3ca096f

Let me know if you still see this in the next insiders build
