### ISSUE TITLE
Settings button text contrast of 3.43 with its background is less than the WCAG AA minimum requirements for text of size 14px and weight of 400

### ISSUE THREAD

**Issue by nsharma1989** [microsoft/vscode#123794]
- VS Code Version: 1.51.0
- OS Version: macOS 11.2.3

Steps to Reproduce:

1.Open VS Code settings
2. use color contrast analyzer on button background and text as foreground
![Screen Shot 2021-05-13 at 12 10 50 PM](https://user-images.githubusercontent.com/18398195/118153837-541c7a80-b3e4-11eb-99fa-eb8204229cee.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I think @misolori already did a pass here so assigning first to him so he can comment

**Comment by misolori** [comment]
Our button font-size is 13px and does not fall into the "large text" category, so we need to be compliant at 4.5:1

https://webaim.org/resources/contrastchecker/
> WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders). WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
>
>Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.
