### ISSUE TITLE
Highlighted Text in dialogues unreadable

### ISSUE THREAD

**Issue by Coronon** [microsoft/vscode#123788]
### Version:
- VS Code Version: 1.56.1
- OS Version: Windows_NT x64 10.0.19042

### Issue:
Text becomes unreadable when highlighting it in dialogues. This should not be an issue with my Theme (Monokai) as everything works as expected in the main editor window (highlighting is transparent).

### Steps to Reproduce:

  With search:
  1. Strg + f
  2. Enter some text to search
  3. Select the text (highlight it)

  With command palette:
  1. Strg + shift + p
  2. Enter some text to search
  3. Select the text (highlight it)

Does this issue occur when all extensions are disabled?: Yes

### Images:
Expected (in the main editor window):
![expectedHighlight](https://user-images.githubusercontent.com/33808743/118145155-960de680-b40d-11eb-9e0a-aa259539178f.JPG)

Buggy (in the search bar):
![buggySearchHighlight](https://user-images.githubusercontent.com/33808743/118145160-98704080-b40d-11eb-8f51-2da6f6cf2de3.JPG)

Buggy (in the command palette)
![buggyCommandHighlight](https://user-images.githubusercontent.com/33808743/118145169-9c9c5e00-b40d-11eb-903c-669077fe7f41.JPG)

**Comment by gjsjohnmurray** [comment]
Please update to 1.56.2
