### ISSUE TITLE
Breaks test runners

### ISSUE THREAD

**Issue by andrewbihl** [microsoft/vscode#123743]
- VS Code Version: 1.56.1
- OS Version: macOS Catalina 10.15.7

I know this probably will get shoved aside as not-your-problem, but I cannot run my unit tests using the very-popular Jest runner extensions. I imagine this is a problem for many.

Steps to Reproduce:

1. Download jest test runner extension
2. Attempt to use
3. Fail

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by andrewbihl** [comment]
To clarify, this occurs across multiple extensions.

**Comment by egamma** [comment]
>To clarify, this occurs across multiple extensions.

Then what is the exact problem, for which extensions does the problem occur?
