### ISSUE TITLE
golang-autocompleteUnimportedPackages-Do not change the location of the original extension package

### ISSUE THREAD

**Issue by hlbbt** [microsoft/vscode#123765]
I really like use vscode. Whether i write php or golang, but now i have a problem.
My colleagues use Goland, when i write code in vscode, auto complete unimported packages causes the packages location to change. This can cause unnecessary trouble when merging code

eg.
![image](https://user-images.githubusercontent.com/52640622/118106101-d3737380-b40f-11eb-9954-bca935bb47a8.png)
![image](https://user-images.githubusercontent.com/52640622/118106300-087fc600-b410-11eb-9a6b-04cdece56ca5.png)

When i save with vscode, the extension package order is automatically changed, 
I want to import extension packs automatically without changing the order of the extension pack list.
Wants to add an option that can be set, otherwise I can only abandon my beloved vscode and follow the team to use Goland。

**Comment by egamma** [comment]
Please file the issue against the Go extension.
