### ISSUE TITLE
Bad documentation for setting `terminal.integrated.defaultProfile.linux`

### ISSUE THREAD

**Issue by jchazalon** [microsoft/vscode#123780]
- VS Code Version: 1.56.1
- OS Version: Ubuntu 20.04.2 LTS x64

Steps to Reproduce:

1. Open settings and look for the `terminal.integrated.defaultProfile.linux` setting
2. Text says  
"The default profile used on Linux. When set to a valid profile name, this will override the values of **`terminal.integrated.shell.osx`** and **`terminal.integrated.shellArgs.osx`**."  
but setting keys should be this should be `*.linux` instead.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by jchazalon** [comment]
Aw snap, I should have checked the source but didn't know where to look.
Thanks for checking and sorry for wasting your time.

Screenshot to confirm it is fixed in Insiders build:
![image](https://user-images.githubusercontent.com/6526137/118173906-776c1780-b42e-11eb-8514-244aa9a1ba5c.png)
