### ISSUE TITLE
workspace open file . pom.xml>1  create .java file  not find package  or  is null file

### ISSUE THREAD

**Issue by freedomour** [microsoft/vscode#123753]
workspace open file . pom.xml>1  create .java file  not find package  or  is null file

**Comment by freedomour** [comment]
[
![1111](https://user-images.githubusercontent.com/35318744/118095976-5d690f80-b403-11eb-957e-f29e919cd084.PNG)
](url)

**Comment by egamma** [comment]
Please file the issue against the Java extension and provide detailed steps for how to reproduce the issue.
