### ISSUE TITLE
Trailing comma warning from Code's default settings.json & workspaceSettings.json

### ISSUE THREAD

**Issue by marckassay** [microsoft/vscode#123731]
Issue Type: <b>Bug</b>

Experiencing the same as @TheWyo has mentioned in [#105414](https://github.com/microsoft/vscode/issues/105414). Unfortunately reloading VS Code doesn't clear these warnings. I believe the replication steps @TheWyo mentioned is what also caused this issue for me. 

Does this issue occur when all extensions are disabled?: Yes

Is there a workaround for this issue, such as manually deleting files? And also, does this issue indicate that settings listed in file are not being applied?

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.94GB (5.02GB free)|
|Process Argv|--crash-reporter-id 6836810c-007f-454a-bd56-71cab486725c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by marckassay** [comment]
I can't replicate this issue since I can't resolve it. And I've been thinking about this issue a little more. @TheWyo mentioned about "split JSON editor view", I think I might of had the SCM git diff editor opened instead. Just wanted to add that as a possible cause for this issue.

**Comment by marckassay** [comment]
Another update, I now suspect "split JSON editor view" is a culprit again. After uninstalling VS Code and ensuring the following folders are deleted before re-install:

- C:\Users\marckassay\\.vscode
- C:\Users\marckassay\AppData\Local\Programs\Microsoft VS Code
- C:\Users\marckassay\AppData\Local\Programs\Roaming\Code

Within a few minutes of editing settings (either User or workspace) in this new install, this issue occurred again. So I repeated what I just mentioned in this post, and set `"workbench.settings.useSplitJSON":false` in my User settings. So far, it seems stable.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/123039
