### ISSUE TITLE
Outputchannel.show() not working

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#123767]
- VS Code Version: 1.56.1
- OS Version: MacOS Big Sur 11.3.1 Mac Mini M1

Steps to Reproduce:

1 - create one outputchannel
2 - call outputchannel.show()
3 - verify that vscode does not focus on the ouputchannel

Use this extension to debug and verify the problem

https://github.com/AllanOricil/nuxt-vscode-extension

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by AllanOricil** [comment]
This is not a duplicate. The `show()` method is no longer focusing on the output channel

**Comment by isidorn** [comment]
This works just fine for me with latest vscode insiders. Here's is my `extension.ts` if you can reproduce with latest vscode insiders please let me know what is different from your `extension.ts` to this one

```
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "ts-ext-may" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		// The code you place here will be executed every time your command is executed
		const output = vscode.window.createOutputChannel('day');
		output.append('what a nice day');
		output.show();
		// Display a message box to the user
		vscode.window.showInformationMessage('Hello World!');
	});

	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}


```

**Comment by AllanOricil** [comment]
@isidorn if you have the terminal opened, and focused, when the extension activates will it change to the output channel automatically? Like for my case I try to focus on the output channel after clicking on a button. When I click on the button I call outputchannel.show() and it does display the output channel

**Comment by isidorn** [comment]
> if you have the terminal opened, and focused, when the extension activates will it change to the output channel automatically?

yes
