### ISSUE TITLE
Can't start VSCode 1.56.1 on macOS 10.10

### ISSUE THREAD

**Issue by whitebear60** [microsoft/vscode#123752]
- VS Code Version: 1.56.1
- OS Version: macOS 10.10

VSCode can't open in OS X 10.10, it says that it requires macOS 10.11, but [VSCode official site](https://code.visualstudio.com/#alt-downloads) says that macOS 10.10 is still supported.

Steps to Reproduce:

1. Open VSCode in macOS 10.10
2. See error message

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Sorry about that, the supported version in the website should be updated. The runtime version used by vscode `1.56` only supports `>= 10.11`

**Comment by mithrendal** [comment]
the latest version of vscode crashes immediatly on start on `OSX 10.11` ... when starting from cmd line it says `Illegal Instruction: 4` ... I grabbed an older Version 1.51 from another Mac and that one works ... is it possible that  your minimum supported runtime version is already higher than 10.11 ?

**Comment by veriotis** [comment]
@mithrendal This happens since VSC v**1.56.0** under MacOS 10.11.6, the previous VSC v**1.55.2** works fine instead.

Take a look at the VSC generated crash reports ...

[https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports]( https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports)

... it is most likely due to _**spdlog.node**_ in Electron.

**Comment by mithrendal** [comment]
Hi veriotis ... cool thing ... thanks for the info ...

here comes the VSC generated crash dump
[da31a834-4fb9-4569-8d67-82ae8070c7d5.dmp.zip](https://github.com/microsoft/vscode/files/6481291/da31a834-4fb9-4569-8d67-82ae8070c7d5.dmp.zip)


and here the crash log reported to the OS
[crashlog.txt](https://github.com/microsoft/vscode/files/6481297/crashlog.txt)


can we still download the older working version 1.55.2 from the official site ?

**Comment by veriotis** [comment]
@mithrendal You can find and download the working 1.55.2 version from the official site's Updates lists, see ...

[https://code.visualstudio.com/updates/v1_55](https://code.visualstudio.com/updates/v1_55)

**Comment by deepak1556** [comment]
@mithrendal for crash on `10.11` please follow https://github.com/microsoft/vscode/issues/123374 for updates, thanks!

**Comment by deepak1556** [comment]
Webpage docs has been updated and will be reflected with next release.
