### ISSUE TITLE
[Critical] Code Insiders is HORRIBLY slow (Log and Video attched)

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#123742]
- Version: 1.57.0-insider (user setup)
- Commit: 37a12c9b0846167b2f68e9e1f276149d2d8b9b27
- Date: 2021-05-12T14:14:26.024Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open the above mention version

It takes consistently at least 5 seconds for vscode to react to anything (click, input etc) and sometimes even 10 seconds.

I have attached a video here. I don't how well does it convey the slowness (Log attached at the end)

https://user-images.githubusercontent.com/15051871/118081791-ac9a4a80-b3d9-11eb-8599-2cf09e1e7fed.mp4

Does this issue occur when all extensions are disabled?: Yes

Logs:

- [renderer1.log](https://github.com/microsoft/vscode/files/6470485/renderer1.log)

**Comment by stagefright5** [comment]
Here is another one


https://user-images.githubusercontent.com/15051871/118082235-6ee9f180-b3da-11eb-8156-138f5ffcc58b.mp4

**Comment by deepak1556** [comment]
Can you check if the issue continues to happen with latest insiders based on commit: a9c5e37ea0dc020f5df3b1c82ef020627fc8cd7c

If it does, please attach the performance profile following the below steps

* Open devtools (From the command palette)
* Choose Performance tab
* Hit the reload and record button
* Perform the steps to slowdown
* Stop recording
* Attach the generated trace

**Comment by stagefright5** [comment]
This is happening in https://github.com/microsoft/vscode/commit/a9c5e37ea0dc020f5df3b1c82ef020627fc8cd7c

But, the shared logs are of no use is it?

**Comment by deepak1556** [comment]
Thanks for confirming, yeah the logs are not required.

Something to verify, when you had the issue with previous insider version,

1) Were the vscode windows setup on multiple monitors or used via virtual desktop ?
2) How was the application launched, from the explorer or command line or taskbar ?
3) Did the slowdown happen as soon as the application was launched or after certain sequence of actions for ex: minimizing the window and then restoring it, etc.

This issue has the same root as https://github.com/microsoft/vscode/issues/123257, currently we have deployed a workaround but we need a bit more data to understand your scenario. Possibly if you can create a screencast with the older insiders version with step by step action of what led to the slowdown, it would be helpful. Thanks!

**Comment by stagefright5** [comment]
> 1. Were the vscode windows setup on multiple monitors or used via virtual desktop ?
 - No
> 2. How was the application launched, from the explorer or command line or taskbar ?
- This issue occured when launched either by **commandline** or by **taskbar**. I did not try launching from the explorer.

> 3. Did the slowdown happen as soon as the application was launched or after certain sequence of actions for ex: minimizing the window and then restoring it, etc.
- It started happenening as soon as the app was launched
 
> This issue has the same root as #123257, currently we have deployed a workaround but we need a bit more data to understand your scenario. Possibly if you can create a screencast with the older insiders version with step by step action of what led to the slowdown, it would be helpful. Thanks!

Are older versions hosted somewhere the public can access?

**Comment by deepak1556** [comment]
> Are older versions hosted somewhere the public can access?
Here is the [Insiders build](https://az764295.vo.msecnd.net/insider/37a12c9b0846167b2f68e9e1f276149d2d8b9b27/VSCodeUserSetup-x64-1.57.0-insider.exe) for https://github.com/microsoft/vscode/commit/37a12c9b0846167b2f68e9e1f276149d2d8b9b27

**Comment by stagefright5** [comment]
> Here is the [Insiders build](https://az764295.vo.msecnd.net/insider/37a12c9b0846167b2f68e9e1f276149d2d8b9b27/VSCodeUserSetup-x64-1.57.0-insider.exe) for [37a12c9](https://github.com/microsoft/vscode/commit/37a12c9b0846167b2f68e9e1f276149d2d8b9b27)

Sadly, I am not facing this issue in the build you have shared. I did not do anything out of the ordinary when the original issue happened.

**Comment by deepak1556** [comment]
Thanks for checking, I will merge this to https://github.com/microsoft/vscode/issues/123257 . While we continue to investigate the root, will add better logging to track next time you might see it.
