### ISSUE TITLE
Initialize repository button doesn't reload source control view

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode#123796]
VS Code
Version: 1.57.0-insider (user setup)
Commit: 37a12c9b0846167b2f68e9e1f276149d2d8b9b27
Date: 2021-05-12T14:14:26.024Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

Jon$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

1. Open folder 
2. Click source control
3. Click initialize repository button

Nothing happens.

Expected it to load source control view

1. Open terminal and run `ls -a` and you can see .git folder
2. Reload the VS Code window

Source code is displayed correctly

**Comment by lszomoru** [comment]
Apologies for not getting back to you on this until now. I am unable to reproduce this issue in the latest Insiders release. Are you still seeing this issue? If you are, could you please share the output from the git output that you can access with the `Git: Show Git Output` command from the command palette.
