### ISSUE TITLE
terminal bar

### ISSUE THREAD

**Issue by Dugu2** [microsoft/vscode#123789]
Issue Type: <b>Feature Request</b>

my ternimal look totaly changed automatical  and I can't select powershell or cmd. PleaseHelp me out
![image](https://user-images.githubusercontent.com/76087019/118152043-1fe79080-b3c9-11eb-9e44-fc0ff77932c4.png)

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.18363

**Comment by meganrogge** [comment]
You can access all of the terminal tabs settings by pressing ctrl + comma and searching for terminal.integrated.tabs
