### ISSUE TITLE
Why does following a link in the output window toggle auto-scrolling

### ISSUE THREAD

**Issue by nickform-ost** [microsoft/vscode#123770]
Issue Type: <b>Bug</b>

When my CMake build runs it writes output into the "Output" pane. When there is an error, the output pane allows me to Cmd-click the file name to open the file. This is so useful - especially the fact that it works for any output and takes you to the right line! Thanks so much.

The issue I'm reporting is a minor aggravation for me. I don't understand why following a link from the Output pane in the manor described above should automatically turn the auto scroll setting (represented by a padlock icon) off. I never want the former action to cause the latter and I can't imagine why anyone would. Perhaps there is a good reason but just filing this in case it's simply a bug that no one has noticed. Thanks again!

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 12, 11|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|../RDFox-console --crash-reporter-id 2a71d04f-cf99-42e6-a8d6-edf3509d111d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-pipelines|ms-|1.183.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
cmake-tools|ms-|1.7.2
cpptools|ms-|1.3.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.3
vscodeintellicode|Vis|1.2.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by sandy081** [comment]
This is because of the feature smartScroll in output view. This is enabled by default. 

```
Smart scrolling allows you to lock scrolling automatically when you click in the output view and unlocks when you click in the last line.
```

You can disable it if wanted using the setting `output.smartScroll.enabled`
