### ISSUE TITLE
Canot press enter after debugging

### ISSUE THREAD

**Issue by LuisFernando14** [microsoft/vscode#123704]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I am currently working on a project with Typescript and when i debug my code and after that I try to add more code o just change code with errors i cannot press Enter.
When I press the key Enter a notification shows with the following text: "Cannot read property 'rename' of undefined".
I am using a Macbook Pro.

Thanks in advance!

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id a8f6c9a7-a825-422b-a71f-1345b47e5ba6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
vscode-graphql|Gra|0.3.16
graphql-for-vscode|kum|1.15.3
Kotlin|mat|1.7.1
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.177.2
color-highlight|nau|2.3.0
indent-rainbow|ode|7.5.0
vscode-jest|Ort|4.0.0
material-icon-theme|PKi|4.6.0
prisma|Pri|2.22.1
vscode-thunder-client|ran|1.2.2
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by xuzeshen** [comment]
I Just meet the seem problem.
