### ISSUE TITLE
jsconfig.json is not taking effect

### ISSUE THREAD

**Issue by Kyi-Moe-Min** [microsoft/vscode#123748]
- VS Code Version: 1.56.1
- OS Version: Windows 10 Pro N x64  10.0.19041

jsconfig.json is not working, it worked until yesterday. I tried downgrading vscode version to 1.55.2 and it didn't fix this issue. 

Steps to Reproduce:

jsconfig.json
```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "baseUrl": ".", // same directory level as src so I can import like "src/**/*
    "checkJs": true // even if I change it to `false` it still check js as I enable checkJs in setting
  },
  "include": ["src/types/*.js"] // this is the place I wrote RouteConfig type in jsdoc
}
```
the screenshot of vscode showing errors, non of these errors should be generated
![Screenshot 2021-05-13 125937](https://user-images.githubusercontent.com/34179716/118087234-3e5e8380-b3eb-11eb-97c8-c12494d9888b.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a complete, self-contained code example (as text)

/needsMoreInfo

**Comment by Kyi-Moe-Min** [comment]
nvm, I reinstalling vscode seems  fixed it
