### ISSUE TITLE
List does not show which element is focused when custom context menu is shown

### ISSUE THREAD

**Issue by gtteamamxx** [microsoft/vscode#123771]
I can imagine situations where someone missed right-click and deleted other file than wanted to.
To avoid this situation we can set border. Like when file is focused:

![image](https://user-images.githubusercontent.com/10392319/118113549-bbd3c500-b3e6-11eb-8d0c-31d59e83b915.png)

![image](https://user-images.githubusercontent.com/10392319/118114019-52a08180-b3e7-11eb-914e-0f366fcbeac0.png)

![image](https://user-images.githubusercontent.com/10392319/118113807-0a815f00-b3e7-11eb-81e2-cd3fdfc2e80d.png)

**Comment by isidorn** [comment]
Yes, this is the problem with List / Tree in general with the Custom menu and I can reproduce. Thus forwarding to @joaomoreno 
It seems like the focus border is only rendered when the focus is on the list, and the native context menu "steal focus"

This works nicely on macOS with native menus.
fyi @sbatten

**Comment by joaomoreno** [comment]
I have always argued for this and somehow got lost over time. I even went to great lengths to make this work in dropdown menus. Unfortunately, the list/tree doesn't know about context menus. It seems like maybe it should.

**Comment by gtteamamxx** [comment]
I'm happy that something will change with that :)

**Comment by isidorn** [comment]
This is present for all our Web experiences and Windows and I think we should fix sooner or later.
@joaomoreno Should we maybe open this up for PRs if you can provide a code pointer?

**Comment by joaomoreno** [comment]
@isidorn This is tough to fix.

**Comment by sbatten** [comment]
@joaomoreno can you leverage https://github.com/microsoft/vscode/blob/7031abadeafec54c8876231e3579c938dee6e1a5/src/vs/base/browser/contextmenu.ts#L31 ?

**Comment by joaomoreno** [comment]
@sbatten What do you mean?

This is hard to fix because:

- List focus indicators are supposed to be invisible when the list (or the app) doesn't have focus
- When a context menu comes up, it takes focus by definition, so the list focus affordance gets hidden
- For this to work, the list would need to be aware that there's a context menu open related to itself. But the list doesn't know anything about context menus: they are a construct of the list's users.

**Comment by sbatten** [comment]
I don't know how the context menus are created but if whoever creates the context menu knows the selected list item at the time, it could be used as the parent of the context menu in a shadow dom to preserve focus. this is how dropdowns work in view actions where they disappear on focus lost.

**Comment by gtteamamxx** [comment]
@joaomoreno any updates?

**Comment by roblourens** [comment]
I did notice that the highlight will stick around after I dismiss the context menu

![Dec-01-2021 16-15-20](https://user-images.githubusercontent.com/323878/144334733-562ab8b5-e7bf-4707-9f34-afc67ff18a60.gif)

**Comment by joaomoreno** [comment]
Yeah because the list is still focused at that time: press <kbd>UpArrow</kbd> to confirm.
