### ISSUE TITLE
After port forwarding allow to open the brower with https://

### ISSUE THREAD

**Issue by morganpizzini** [microsoft/vscode#123750]
When running VSCode in container I can choose to automatically open the browser by setting the code below inside _devcontainer.json_

```json
"portsAttributes": {
   "5001": {
	"label": "API port",
	"onAutoForward": "openBrowser"
   }
}
```

This will correctly open the browser at the address _http://localhost:5001_ when this port is forwarded, but my application runs on _httpS://localhost:5001_ and so far I manually add the _S_.

A possible improvement could be add a parameter
```json
"portsAttributes": {
   "5001": {
	"label": "API port",
	"onAutoForward": "openBrowser",
        "browserUrlSsl": true
   }
}
```

**Comment by alexr00** [comment]
@cmbrose, since we were just talking about this, FYI: looks like we have a feature request for http vs. https with Remote Containers!

I will optimistically add this to our May iteration and we'll see if I can get it done by then.

**Comment by alexr00** [comment]
Also adding a way to change this in the context menu:

![image](https://user-images.githubusercontent.com/38270282/118655628-0344c180-b7ea-11eb-893c-be4f80f16a8d.png)
