### ISSUE TITLE
Status icon is getting colors by the tabs icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123776]
<img width="311" alt="Screen Shot 2021-05-13 at 5 25 06 AM" src="https://user-images.githubusercontent.com/2193314/118125282-9ffefd80-b3ab-11eb-86c8-4a0b4a8edfe8.png">

**Comment by Rahulkhinchi03** [comment]
Please cloe this. I dont need any emails!

**Comment by Rahulkhinchi03** [comment]
close*

**Comment by Tyriar** [comment]
@Rahulkhinchi03 sounds like you're watching the repo, that's probably a bad idea if you want github to actually be usable.
