### ISSUE TITLE
All # disappear when I drag a file to Terminal

### ISSUE THREAD

**Issue by Antisunny** [microsoft/vscode#123775]
Issue Type: <b>Bug</b>

When dragging a file whose absolute path contains any "#", all "#" disappear

Example:

actual file path is `/Users/ryan/Desktop/re#.pdf`, which contains a `#`: drag this file to the terminal area in vscode, the result is:

    '/Users/ryan/Desktop/re.pdf'

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id c87a4a31-cbf6-4f1d-a6d3-994b09959e85|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
unique-lines|bib|1.0.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.213
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
sublime-keybindings|ms-|4.0.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflightcf:30299255

```

</details>

**Comment by meganrogge** [comment]
Yes we did this as a part of a security fix.

**Comment by Tyriar** [comment]
We are a little conservative with what you can drag in to the terminal, just in case some special trick is used to escape the string and run a command.
