### ISSUE TITLE
Active terminal not set when first terminal is killed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123709]
Repro

1. Open 2 terminals
2. ctrl+shift+b in vscode repo
3. kill the task terminals (ctrl+d)

![image](https://user-images.githubusercontent.com/2193314/118019785-3b419580-b30e-11eb-8302-39d3d967bd8a.png)

**Comment by Tyriar** [comment]
Think this is related to killing any first terminal

**Comment by Tyriar** [comment]
Actually just the first terminal, just killed one inbetween the 2 node terminals and ended up in this state:

![image](https://user-images.githubusercontent.com/2193314/118297637-483bc180-b493-11eb-88cb-070011d475ac.png)

**Comment by meganrogge** [comment]
Repro: 
- open 2+ terminals
- select the first one
- delete it

🐛 -> no active terminal is displayed
