### ISSUE TITLE
Unable to open PDF files in VS code

### ISSUE THREAD

**Issue by MKumar-12** [microsoft/vscode#123787]
- VS Code Version: 1.56.1
- OS Version: Win10 x64bit

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

![vs-error](https://user-images.githubusercontent.com/63640649/118142019-9c10c100-b427-11eb-8c86-4e1cbb0481d6.PNG)

**Comment by egamma** [comment]
To view PDF files you have to install the PDF extension https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf
