### ISSUE TITLE
File not open in editor with config    "workbench.editorAssociations"

### ISSUE THREAD

**Issue by waguirre** [microsoft/vscode#123792]
"workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    }

![variables_session](https://user-images.githubusercontent.com/2904511/118153293-59c19280-b3db-11eb-9066-35e83c5a2e43.gif)

**Comment by lramos15** [comment]
@joyceerhl Is the new jupyter change with the new setting leaking into the stable build?

**Comment by joyceerhl** [comment]
@waguirre What version of the Jupyter extension and VS Code do you have? The latest for VS Code Stable 1.56.1 is v2021.6.832593372. I'm not reproing this behavior in that setup.

**Comment by joyceerhl** [comment]
Additionally, in the recording above, it looks like you are explicitly pasting this value into your settings file:

```
"workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
}
```

That format is only supported in VS Code Insiders right now. If you are on VS Code Stable, you would want to add the following instead:

```
"workbench.editorAssociations": [{
    "viewType": "jupyter.notebook.ipynb",
    "filenamePattern": "*.ipynb"
}]
```

**Comment by lramos15** [comment]
Do you mind providing the extensions you have installed? It may be cause by https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync syncing your settings between insiders and stable. If so we recommend VS Code's built in settings sync :) https://code.visualstudio.com/docs/editor/settings-sync

**Comment by waguirre** [comment]
the problem is that the insider and stable configurations are synchronized.

**Comment by lramos15** [comment]
They're only synchronized if you enable the stable channel. Which we don't recommend as issues like this can arise. The new setting will be supported in 1.57 and you will no longer see this issue.
