### ISSUE TITLE
Icons aren't rendered in settings UI markdownEnumDescription

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123790]
<img width="1136" alt="Screen Shot 2021-05-13 at 8 30 46 AM" src="https://user-images.githubusercontent.com/2193314/118148602-95e9f880-b3c5-11eb-8438-2c414ccadc68.png">
<img width="412" alt="Screen Shot 2021-05-13 at 8 31 45 AM" src="https://user-images.githubusercontent.com/2193314/118148676-a8fcc880-b3c5-11eb-8ace-2ba2fefe5b7f.png">

**Comment by rzhao271** [comment]
This issue has been resolved, though I noticed that the js-debug terminal has its icon surrounded by $(). Will file a separate issue for that.
