### ISSUE TITLE
Markdown Preview - No automatic hyperlink for python filenames with underscore

### ISSUE THREAD

**Issue by grotewortel** [microsoft/vscode#123712]
Issue Type: <b>Bug</b>

Reproduction:
1) Create a new markdown file
2) Create content:

file_name.py - this has no hyperlink

file-name.py - this has a hyperlink

3) Open preview

Expected behaviour: Both python files should have a hyperlink
Actual behaviour: The filename with the underscore does not have a hyperlink

Possibly _ is not part of the filename recognition algorith.

Please see screenshot for an example.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by mjbvz** [comment]
This the default markdown-it linkifier behavior: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22file_name.py%20-%20this%20has%20no%20hyperlink%5Cn%5Cnfile-name.py%20-%20this%20has%20a%20hyperlink%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

You can set `"markdown.preview.linkify": false` to disable automatic link creation
