### ISSUE TITLE
Insiders opens any "settings.json" file as vscode user settings

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#123795]
```
Version: 1.57.0-insider (user setup)
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:13:18.296Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1. From Insiders, try to open any file called `settings.json` (no matter the actual content)
2. Insiders will open the User Settings json editor
3. The problem reproduces also using the Windows Explorer context menu `Open in...` or just double-click the file if Insiders is the default json editor
4. Stable works as expected

![vscode insider settings file](https://user-images.githubusercontent.com/5784415/118157868-ecf4cb00-b3cf-11eb-9dab-8306caec0677.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I think I fixed this, but @lramos15 please confirm that it's safe for me to call `createEditorInput` inside the override callback. I was worried that it would infinitely recurse but that doesn't seem to be an issue.

**Comment by lramos15** [comment]
@roblourens, should be safe. We don't override in `createEditorInput`, only on opening. Although there are some talks about making `createEditorInput` private in the future, that's not a problem right now.
