### ISSUE TITLE
terminal.integrated.profiles.windows not working in .vscode/settings.json

### ISSUE THREAD

**Issue by Mair** [microsoft/vscode#123773]
- VS Code Version:  1.56.1
- OS Version: win 10 pro 64X

Workspace settings (.vscode/settings.json) terminal settings now give deprecated warnings

>This is deprecated, use `#terminal.integrated.defaultProfile.windows#` instead

however adding 

```json
  "terminal.integrated.profiles.windows": {
    "PowerShell -NoProfile": {
      "source": "PowerShell",
      "args": ["-NoProfile","echo",]
    }
  },
```
makes no difference and does not add any option in the terminal dropdown
Steps to Reproduce:

1. remove  "terminal.integrated.shell.windows": "cmd.exe",
2. add   "terminal.integrated.profiles.windows": {
    "PowerShell -NoProfile": {
      "source": "PowerShell",
      "args": ["-NoProfile","echo",]
    }
  },

this does work in the user settings but not in the workspace settings

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by meganrogge** [comment]
You have to set `terminal.integrated.allowWorkspaceConfiguration: true`

**Comment by Mair** [comment]
> You have to set terminal.integrated.allowWorkspaceConfiguration: true

@meganrogge That doesn't help my use case or make sense. Please let me explain
 I have a template (https://github.com/Mair/create-esp32-app) that thousands of people are using, when the template is run it creates a vs-code project with the settings in place.
```
"terminal.integrated.shell.windows": "cmd.exe",
  "terminal.integrated.shellArgs.windows": ["/k", "C:\\esp\\idfv_4_2\\esp-idf\\export.bat"],
  "terminal.integrated.shell.linux": "/bin/bash",
  "terminal.integrated.shellArgs.linux": ["--init-file", "C:/esp/idfv_4_2/esp-idf/export.sh", "-i"],
  "terminal.integrated.shell.osx": "/bin/bash",
  "terminal.integrated.shellArgs.osx": ["--init-file", "C:/esp/idfv_4_2/esp-idf/export.sh", "-i"],
```
the paths to the scripts are dynamically created.
it is assumed that users will be able to run the script, create the project and it should just work without having to change other settings I cannot control. 

In other words I have a template that thousands of users are using and this is a breaking change and I have no way of fixing this because I can't get a terminal to work correctly on someone else's vs code instance.
