### ISSUE TITLE
`command:` URIs in trusted `MarkdownString` values in TreeItem tooltips don't execute commands.

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#123723]
Version: 1.56.0-insider (user setup)
Commit: 4e185d8986339717e593be19bc75288905ffbb51
Date: 2021-05-01T00:27:57.510Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Register a custom command (for example: `myextension.test`).
2. Create a VS Code extension with a custom `TreeDataProvider`, registered as a contribution in package.json.
3. Implement `TreeDataProvider.getChildren` and `TreeDataProvider.getTreeItem` to provide a single `TreeItem`.
4. For the provided `TreeItem`, set the tooltip using the following example:
    ```ts
    const mdString = new MarkdownString("[Execute Command](command:myextension.test)");
    mdString.isTrusted = true;
    const treeItem = new TreeItem("label");
    treeItem.tooltip = mdString;
    ```
5. Launch VS Code with the custom extension. In the custom tree view, hover over the tree item. 
6. Observe that the Markdown link `Execute Command` is hyperlinked, but clicking on the link does not execute the command.

This differs from how trusted markdown in a hover or decoration treats command links when the markdown is trusted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like by default command links aren't supported in the hover widget.

**Comment by rbuckton** [comment]
I thought that was the point of the `.isTrusted` property on `MarkdownString`. I know that it works when creating hovers in a hover provider.
