### ISSUE TITLE
Can not enter vietnamese characters.

### ISSUE THREAD

**Issue by mt26691** [Microsoft/vscode#1237]
Hi, I'm currently using unikey 64 bit for window 7 64 bit ultimate, you can download it here (http://unikey.vn/). And I find that I can not enter Vietnamese characters in visual studio code.
For example the register.html file in the picture below:
![image](https://cloud.githubusercontent.com/assets/10028918/11772422/b6fea928-a24e-11e5-9ff1-9d88a0a9c4ed.png)

If I enter "Hoom nay", it means "Hôm nay", but the editor only display "Hm nay".
I don't think the problem come from encoding. Because the other vietnamese chars in this picture were entered by Notepad++ and it works very well.
Thank you and sorry for my bad english too.

**Comment by bgse** [comment]
Probably related:

https://github.com/Microsoft/vscode/issues/1168

**Comment by egamma** [comment]
yes, closing as a duplicate for #1168
