### ISSUE TITLE
Issues with formatting Java code

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#123764]
In the process of formatting code in Java, line breaks are always forced. I canceled all line break settings, but the editor still enforces line breaks during formatting. This makes the code style unable to keep pace with IDEA IDE, which is very frustrating. . . . I think I can use vscode to replace Eclispe, but it seems that there is still a long way to go. . . The vscode editor always forces the code to wrap, which is very annoying, and the setting is invalid. "editor.wordWrapColumn": 500, Is there any way to cancel this behavior? Let users decide for themselves whether they need to wrap. Or is this a bug? In the process of formatting code in Java, line breaks are always forced. I canceled all line break settings, but the editor still enforces line breaks during formatting. This makes the code style unable to keep pace with IDEA IDE, which is very frustrating. . . . I think I can use vscode to replace Eclispe, but it seems that there is still a long way to go

VS Code Version:1.57
OS Version:win10

**Comment by egamma** [comment]
Please report the issue against the Java extension.
