### ISSUE TITLE
remote ssh vscode install

### ISSUE THREAD

**Issue by Madcoder8** [microsoft/vscode#123797]
Issue Type: <b>Bug</b>

My remote system does not have internet capability.  I select connect to host, specify the ip address, select linux, enter my password a couple of times.  It seems to untar several items but then fails with message below.

> tar: vscode-server-linux-arm64/extensions: time stamp 2021-05-12 22:12:36 is 162
> 0880307.34920009 s in the future
> tar: vscode-server-linux-arm64: time stamp 2021-05-12 22:12:34 is 1620880305.349
> 10621 s in the future
> ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> a021e59a6430: start
> exitCode==37==
> listeningOn====
> osReleaseId==buildroot==
> arch==aarch64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> a021e59a6430: end
> main: line 54: 2448%N/1000000: division by 0 (error token is "N/1000000")       
> main: line 62: - : syntax error: operand expected (error token is "- ")

VS Code version: Code - Insiders 1.57.0-insider (659175fa39b994fc39381b0af2874c85efeb2a01, 2021-05-13T05:13:18.296Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'SSH' failed: Failed to install the VS Code Server

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.61GB free)|
|Process Argv|--crash-reporter-id 48aae5bb-6a70-475a-95b5-b6600d0ab206|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Failed to install the VS Code Server
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30296409
vscorehov:30301224

```

</details>

[vsinsiderlog.txt](https://github.com/microsoft/vscode/files/6473999/vsinsiderlog.txt)

**Comment by Madcoder8** [comment]
Just checking in to see if I can get some traction on this issue.

**Comment by roblourens** [comment]
Sorry, I missed it somehow. I think this is the same as https://github.com/microsoft/vscode-remote-release/issues/4207
