### ISSUE TITLE
Auto focus/hide the Debugging panel

### ISSUE THREAD

**Issue by KubaP** [microsoft/vscode#123785]
When starting a debugging session, for example through the `[F5]` shortcut, it would be nice to have the ability to make the 'Run & Debug' tab come to focus.

If the panel it is part of is already open, the active tab should be switched to the debugging tab, and once the debugging session ends, it should switch back to the tab which was focused before. If the panel is not open, it should open on the debugging tab, and once the debugging session ends, it should close.

Of course, this should be a configurable feature for those who do not wish for such behaviour.

**Comment by isidorn** [comment]
Please use this setting
```
	"debug.openDebug": "openOnSessionStart",
```
