### ISSUE TITLE
Editor Semantic Highlighting stopped working (Windows 10)

### ISSUE THREAD

**Issue by richbobo** [microsoft/vscode#123717]
Issue Type: <b>Bug</b>

At some point today, Semantic Highlighting stopped working on my Windows 10 machine. I have tried disabling all extensions, switching themes, logout/login, checked for extension updates, relaunched VS Code and nothing helps.

I also use VS Code on a macOS system and that is still working fine.

Both my Windows 10 machine and my macOS machine have the latest VS Code release - 1.56.1. They also sync settings between systems.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz (64 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (43.49GB free)|
|Process Argv|--crash-reporter-id ac5fa1a5-26a7-418c-93a8-0122a4cf66c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.0.3
vscode-custom-css|be5|5.0.3
vscode-to-photoshop|bia|0.0.3
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
python-ultisnippets|eli|2.7.0
pythonsnippets|frh|1.0.2
vscode-pull-request-github|Git|0.26.0
vsc-python-indent|Kev|1.14.2
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
vscode-gitignore-generator|pio|1.0.3
vscode-yaml|red|0.18.0
mel|sat|0.1.2
vscode-smoothtype|spi|1.2.0
open-in-browser|tec|2.0.0
rst-vscode|tht|3.0.1
vscode-todo-highlight|way|1.0.4
pyqt-integration|zho|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
bridgeflight:30299254

```

</details>

**Comment by aeschli** [comment]
With what language? TypeScript?

**Comment by richbobo** [comment]
Sorry - I'm using Python.

Also, I've tried other themes, just to see if it was something that only affected the one I was using.

To check, I open the Settings window, search for "semantic", then switch the Editor > Semantic Highlighting setting from true to false to true to configuredByTheme - and nothing changes in my Python code.

**Comment by richbobo** [comment]
Just now updated to VS Code 1.56.2 and that did not change anything - still no semantic highlighting in Windows 10.

**Comment by aeschli** [comment]
Can you check whether you get semantic highlighting in TypeScript:
```
for (const arg of process.argv) {
	console.log(arg)
}
```
Use the `Developer: Inspect Editor tokens and scope` command over `arg` and you should see a section `semantic topen type`.
Try it with the default theme.

**Comment by richbobo** [comment]
I can confirm that semantic highlighting is working with TypeScript. I tried a few different themes and all seem to toggle fine.

**Comment by richbobo** [comment]
(I had to go find some TypeScript samples to use - I primarily code in Python! ;^) )

**Comment by aeschli** [comment]
Ok, then I suspect this is related to the Python extension. Can you file an issue there?
https://github.com/Microsoft/vscode-python/issues

**Comment by richbobo** [comment]
SOLUTION:

I know this issue has been closed, but I thought it might be helpful to others to know what the solution was.

I discovered through some trial and error that my Windows mapped drive was the problem. Quitting VS Code, disconnecting the mapped drive and remaking it fixed the problem!

I have no idea what the root cause was, but maybe someone else can speculate...
