### ISSUE TITLE
command+delete ，I want to delete a line of code, but terminate the terminal

### ISSUE THREAD

**Issue by wuzhenbang0930** [microsoft/vscode#123746]
Issue Type: <b>Bug</b>

版本: 1.56.1
提交: e713fe9b05fc24facbec8f34fb1017133858842b
日期: 2021-05-06T10:08:24.325Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 18.7.0

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 9, 9|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_11012736 --crash-reporter-id 98877741-5ae1-46e8-a589-78ec1e3ed3bd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.12.0
django|big|1.0.2
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
tslint|eg2|1.0.46
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
code-runner|for|0.11.3
leek-fund|gis|1.9.6
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
webpack|jer|2.2.0
docthis|joe|0.7.1
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-zh-hans|MS-|1.56.2
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.6.0
typescript-hero|rbb|3.0.0
addDocComments|ste|0.0.8
vscode-icons|vsc|11.4.0
JavaScriptSnippets|xab|1.8.0
super-translate|xue|1.0.11
material-theme|zhu|3.10.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352
bridgeflightcf:30299255

```

</details>

**Comment by meganrogge** [comment]
You must have a keybinding setup to kill the terminal
