### ISSUE TITLE
"Cannot read property 'rename' of undefined"

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#123768]
Issue Type: <b>Bug</b>

1. Create a DOCKER_HOST on an EC2 instance
2. Create and switch to the context that makes `docker compose` use that context
3. Deploy a node:14 container. Check out code.
4. Run the code (that has several ports exposed)
5. Kill the Debug session

Seen behaviour:
Open a ts file and edit. Editing fails. Editor is in readonly mode.
Also see a error popup saying "Cannot read property 'rename' of undefined"

Expected:
When the docker image was on the desktop, it worked all fine. So, assuming that the behaviour should be the same.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 4.14.231-173.361.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 10, 9|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|. --crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:b8854d2db4caeedada11a94c237950a893e96ae0144e2164d20261d6dac45a78 (/dev-pm2) @ aws-docker|
|OS|Linux x64 4.14.231-173.361.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (9.88GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.177.2
atlascode|atl|2.8.6
npm-intellisense|chr|1.3.1
regex|chr|0.4.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
bash-ide-vscode|mad|1.11.0
mongodb-vscode|mon|0.5.0
compare-folders|mos|0.22.0
vscode-yaml|red|0.18.0
vscodeintellicode|Vis|1.2.13

</details>

**Comment by niccolomineo** [comment]
Sounds like this could be related to [#123758](https://github.com/microsoft/vscode/issues/123758)

**Comment by isidorn** [comment]
Sounds like a dup of https://github.com/microsoft/vscode/issues/123040
Assigning to @meganrogge and @Tyriar and they can close as duplicate

**Comment by Tyriar** [comment]
Looks like it, please update to 1.56.2
