### ISSUE TITLE
List focus colors are too dark

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#123703]
The new bg and highlight seem very close in color
![image](https://user-images.githubusercontent.com/323878/118015398-14349500-b309-11eb-80ba-e6f992ba3711.png)

![image](https://user-images.githubusercontent.com/323878/118015626-58c03080-b309-11eb-957b-5859e5d50dae.png)

**Comment by roblourens** [comment]
Also I can barely see the TS icon. I'm sure we can't make all of them look good, but it seems like one that we could optimize for

![image](https://user-images.githubusercontent.com/323878/118017596-ab025100-b30b-11eb-9d7a-0d259ef091f2.png)

**Comment by misolori** [comment]
This is a result of https://github.com/microsoft/vscode/issues/121493 and matches the explorer focus state, however is hard to make it look good in our light theme as the highlight colors is similar to the focus color. We can't do anything about the file icons as that is the same in the explorer.

**Comment by roblourens** [comment]
Dunno if it passes the contrast check, but I like something like this
![image](https://user-images.githubusercontent.com/323878/118061881-af9a2a00-b34a-11eb-9cc8-6f5611aaf0b7.png)

**Comment by misolori** [comment]
Updated to a lighter version, thanks @roblourens!

![image](https://user-images.githubusercontent.com/35271042/118696174-dd57f680-b7c2-11eb-9f2f-cf3b72c34fdc.png)
