### ISSUE TITLE
Call stack UI for exception hover info and badge color

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode#123724]
Issue Type: <b>Bug</b>

Debug a program that throws an exception (any language).
Hover over the paused message text.

Expected: (this screenshot is from v1.49.0)
The 'Text' information to be displayed on hover.
The color of the pause message background to be 'red'.

![image](https://user-images.githubusercontent.com/6634754/118052797-5da8d280-b351-11eb-9e83-c5ae0c81ca5a.png)

Got:
The same name shown on hover.
The color of the pause message background was grey.

![Screen Shot 2021-05-12 at 4 30 33 PM](https://user-images.githubusercontent.com/6634754/118052834-74e7c000-b351-11eb-8d1f-427cf4388a9e.png)

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 10, 8|
|Memory (System)|16.00GB (2.08GB free)|
|Process Argv|. --crash-reporter-id 295c412e-1641-4463-8bfb-d64574017322|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-diff|fab|1.4.1
go-nightly|gol|2021.5.1113
cloudcode|goo|1.11.1
vscode-docker|ms-|1.12.1
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.3.3
reload|nat|0.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by rzhao271** [comment]
The information displayed on the hover now seems to be the file name rather than the Python exception type, at least within Codespaces. @suzmue is this expected behaviour?

**Comment by suzmue** [comment]
@rzhao271 are you hovering over the stopped description? I am getting the correct hover text

<img width="462" alt="Screen Shot 2021-06-04 at 9 08 51 PM" src="https://user-images.githubusercontent.com/6634754/120875343-69b33900-c579-11eb-8737-143b2c744e5a.png">
