### ISSUE TITLE
VSC use too much memory when build gatsby application

### ISSUE THREAD

**Issue by dangquang1020** [microsoft/vscode#123736]
Issue Type: <b>Performance Issue</b>

I do not know the exact way to reproduce this issue, but after updated my VSC to the latest version, it uses too much memory when I run the development server and build the web app.
Before it just use around 1.5GB - 2GB ram, but now somewhen it uses 6GB-7GB ram.
Thank you.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.36GB free)|
|Process Argv|--crash-reporter-id ecd79cf2-3abb-4126-8ec1-b055bb070f20|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    84	 13356	code main
    3	    81	  1676	   shared-process
    0	    63	  3828	     ptyHost
    0	     5	  8228	       "C:\Program Files\Git\bin\bash.exe"
    0	    10	  7576	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	     6	 15904	       console-window-host (Windows internal process)
    0	    39	  5164	   utility
    0	    24	  5500	   crashpad-handler
    0	   212	  7684	   window (_service.scss - Crucial-Logics - Visual Studio Code)
    0	    68	 14532	     searchService
    0	   162	 14748	     extensionHost
    0	   120	  5844	       electron_node index.js 
    0	    67	  7224	       "C:\Users\Ken-PC\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Ken-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=14748
    0	   193	 11936	       electron_node tsserver.js 
    0	    78	 11784	         electron_node typingsInstaller.js typesMap.js 
    0	    72	 12248	       electron_node server.js 
    0	    69	 17868	       "C:\Users\Ken-PC\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Ken-PC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=14748
    0	   102	 18924	       electron_node tsserver.js 
    0	    14	 18684	     watcherService 
    0	    10	  6440	       console-window-host (Windows internal process)
    5	    76	  8460	   window (Issue Reporter)
    0	   112	  9928	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (_service.scss - Crucial-Logics - Visual Studio Code)
|    Folder (Crucial-Logics): 2140 files
|      File types: gz(1115) js(143) tsx(73) map(67) json(53) svg(44) png(25)
|                  txt(19) scss(19) html(18)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node-terminal;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
framer-snippets-vscode|afn|0.2.2
ng-template|Ang|12.0.0
vscode-tailwindcss|bra|0.6.3
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.4.1
terminal|for|0.0.10
Angular2|joh|11.0.0
graphql-for-vscode|kum|1.15.3
vscode-scss|mrm|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
vscode-scss-formatter|sib|2.2.0
vscode-icons|vsc|11.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301300

```

</details>

**Comment by egamma** [comment]
Can you reproduce the issue when you have the extensions disabled?
