### ISSUE TITLE
Panel tabs odd behavior

### ISSUE THREAD

**Issue by 1p1eq11** [microsoft/vscode#123722]
- VS Code Version: 1.56.1
- OS Version: Windows_NT x64 10.0.19042
- Screen resolution: 1920x1080
- Windows scaling: 125%

Steps to Reproduce:

1. Drag multiple (debug) views into the Panel until the overflow menu appears
2. Drag the tabs to the side and into other tabs until some tabs are hidden

First I would expect tabs not to go into the overflow menu since there is enough horizontal space.  

Additional unexpected behavior is that once some tabs are hidden, every tab seems to have its own state, i.e. having different tabs active means a different **number** of tabs is shown.
The right-click menu shows all tabs checked; none are hidden.

First part of the issue:

[!1)](https://user-images.githubusercontent.com/43881641/118037467-2dbbf800-b36e-11eb-9c54-553f0cadad1d.mp4)

It seems like number 2 isn't reproducible without the overflow menu present.

Second part of the issue:

[!second](https://user-images.githubusercontent.com/43881641/118037505-3ad8e700-b36e-11eb-8f35-9a16e3fb7373.mp4)

Third part, even more apparent when resizing the window horizontally:

[!third](https://user-images.githubusercontent.com/43881641/118040821-58a84b00-b372-11eb-969e-961ca3a154db.mp4)

Does this issue occur when all extensions are disabled?: Yes. The first two GIFs were made with the Python extension enabled but during later tests I used Node.js and disabled all extensions.

**Comment by sbatten** [comment]
I believe this issue is now resolved with https://github.com/microsoft/vscode/commit/1f5bd257659783bc2fe4e170f69965d2311b38e6

**Comment by rchiodo** [comment]
/verified

Layout uses the whole space of my window
