### ISSUE TITLE
Can't open notebooks after installing Vibrancy extension

### ISSUE THREAD

**Issue by GarretOConnell** [microsoft/vscode#123760]
- VS Code Version: Version: 1.57.0-insider 
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Download Vibrancy from extension marketplace
2. Reload window
3. Open notebook from remote - it opens in text editor (should open in notebook). Selecting "Open with..." > "Jupyter notebook" results in notebook stuck in loading state.

Tried reinstalling vscode, removing settings files completely from local and remote.
Note: notebooks load normally with VScode regular. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@GarretOConnell can you please update to latest Insiders and see if you can reproduce.

**Comment by GarretOConnell** [comment]
@rebornix fixed now after uninstalling everything (including local and remote hidden settings directories), reinstalling latest version, and then finally using the VScode-Insiders Python build. Thank you!
