### ISSUE TITLE
Editor no longer uses "IBM Plex Mono" font

### ISSUE THREAD

**Issue by rveerd** [microsoft/vscode#123885]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

I have used "IBM Plex Mono" as the editor font for a long time.

```json
    "editor.fontFamily": "'IBM Plex Mono', Consolas, 'Courier New', monospace",
```

This used to work but it no longer works in the above version of VSCode. The font can be used in other applications, such as Notepad.exe. If I change the setting to use a different font:

```json
    "editor.fontFamily": "'Times New Roman', Consolas, 'Courier New', monospace",
```

The editor font is changed to Times New Roman.

Why is VSCode no longer able to use the font "IBM Plex Mono"?

**Comment by DmitrySokolov** [comment]
The same.

The font is present in `Windows/Fonts` folder.

WordPad and Notepad++ can use this font.

But this font is not showed in `Windows / Settings / Personalization / Fonts` and VS Code also can not use this font.

Re-installing the font helps for a while.

**Comment by rveerd** [comment]
Re-installing the font indeed helps for a while. After it stopped working again, I re-installed the font for all users. For now, it still works with VS Code.

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built with Chromium. The font rendering in the editor is delegated to Chromium, so the font lookup is unfortunately not directly under control. If you are able to reproduce this problem in a Chromium-based browser such as Edge or Chrome, then please report the issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list

**Comment by DmitrySokolov** [comment]
I can reproduce the issue both in Chrome and in Firefox. Moreover, I've already submitted the issue to MS Feedback https://aka.ms/AAct319 some time ago, but there is still no reaction (please vote).

**Comment by rveerd** [comment]
The issue has not occurred again after I re-installed the font for all users. I am closing the issue.
