### ISSUE TITLE
Getting error on debug: Couldn't find debug adaptor descriptor for debug type 'coreclr'

### ISSUE THREAD

**Issue by bdlawrence13** [microsoft/vscode#123825]
Does this issue occur when all extensions are disabled?: Yes/No Can't run program if I disable all extensions.

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open project that's always worked.
2. Run -> Start debugging
3.  Get error. Cannot run program.
4.  Also noticed on start up of VS Code, get this error: Downloading package 'Razor Language Server (Windows / x64)' Failed at stage: downloadPackage
Error: unable to get local issuer certificate

**Comment by isidorn** [comment]
Please file against the debugger extension that you are using. Once they investigate they might forward the issue to vscode with more precise details
