### ISSUE TITLE
Fetching from https://packages.microsoft.com/yumrepos/vscode is incredibly slow

### ISSUE THREAD

**Issue by why-not-try-calmer** [microsoft/vscode#123865]
Downloading VSCode updates from Fetching from https://packages.microsoft.com/yumrepos/vscode is incredibly slow by modern standards (~149Kb/sec). I am not sure whether it's on Microsoft's end or on the mirrors' end.

- VS Code Version: 1.52.6-1620838566
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Follow the steps under https://code.visualstudio.com/docs/setup/linux#_opensuse-and-slebased-distributions
2. Update: `sudo zypper dup`

**Comment by Tyriar** [comment]
Forwarded this to the repo team, thanks

**Comment by why-not-try-calmer** [comment]
Thanks!
