### ISSUE TITLE
Why VS Code should switch to CodeMirror for default text editing abilities.

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#123826]
## (Or why Monaco should be re-imeplemented using similar concepts.)

CodeMirror 6 has achieved amazing:

The new version is built on `contenteditable`, which means, even with all its text manipulation, code folding, auto-completion, etc, it works _**perfect on mobile**_.

CodeMirror allows the browser's **_native_** text editing mechanics to be in play, which means editing works on all mobile devices with all familiar features (f.e. drag the cursor or select text on mobile and you will see the magnifying glass, the full native experience).

In order to maintain as much backwards compatibility, maybe Monaco could be a wrapper around CodeMirror in order to provide a similar experience and similar APIs as much as possible. There will be breaking changes none-the-less, but it would be **_totally worth it_** because this would mean that VS Code could run on any mobile platforms (i.e. with use of touch screens) without issues.

To see what I mean, inspect the elements on the sample editor at https://codemirror.net/6/, and you'll see it uses the `contenteditable` attribute on the root of the editing area.

And for example, this is what I can do on mobile:

<img width="400" src="https://user-images.githubusercontent.com/297678/118194677-a1a5e100-b3fe-11eb-8f73-f93360abf10b.png" />

What you see in the screenshot is I am dragging the right edge of the text selection with my finger, and the native magnifying glass appears as expected.

It's the _full_ mobile editing experience.

It seems to be pretty fast. I pasted the example to create 100k lines, and it has no issues at all. I can scroll to any part of the code and edit without any slowdown.

It does virtual scrolling (like Monaco, where it only keeps enough lines in the DOM to ensure smooth scrolling, and adds/removes lines at the top bottom as needed) and despite this, if the cursor goes far off screen, and you begin editing again, the cursor position jumps back into view and the whole thing still remains `contenteditable` and continues to work as expected. Superb!

**Comment by egamma** [comment]
@trusktr thanks for your analysis. Our plan is to continue with the monaco editor and to improve the support for mobile, this will be significant less effort than to replace the entire editor implementation. 

//CC @alexdima
