### ISSUE TITLE
reopening needed

### ISSUE THREAD

**Issue by arefpz** [microsoft/vscode#123844]
Issue Type: <b>Bug</b>

Hi
Several days ago before these updates, whenever I double-clicked on the file the visual code run and brought the code very fast, but now, it's broken, and it needs several reopening to just run the code itself, and then I can double click on the file to get opened by code.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2933)|
|GPU Status|2d_canvas: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.62GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch /media/rf/Work/Programming/uOttawa/tACS/main.f90 --crash-reporter-id 174a1ab6-03f5-4e79-8b4b-828ba46962c6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
pip-packages|etm|0.4.3
terminal|for|0.0.10
shell-format|fox|7.1.0
fortran|Gim|0.2.0
linter-gfortran|krv|2.2.2
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.11.0
start-git-bash|McC|1.2.1
python|ms-|2021.5.840043038
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
vscode-ipython|pan|0.5.0
material-icon-theme|PKi|4.6.0
shellman|Rem|5.5.0
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
bash-beautify|sha|0.1.1
shellcheck|tim|0.14.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscod805:30301674

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
