### ISSUE TITLE
Sometimes compiling efficiency is low

### ISSUE THREAD

**Issue by xinxuantt** [microsoft/vscode#123861]
When I use VScode to compile, as long as the VScode is in the background process (or even it is only blocked by other windows), the compilation efficiency is low and the CPU cannot be fully loaded.

**Comment by egamma** [comment]
/needsMoreInfo  what language are you compiling when you observe the performance issue?

**Comment by xinxuantt** [comment]
Sorry I didn't describe it well.I compiled the C language, with the VC WDK compilation environment.
We didn't compile on vscode at first. There was another software. Later, we switched to vscode to compile. Both softwares are configured with the same set of compilation tools. Recently, I found that vscode compilation efficiency is poor. I tried the original software to build with the same compilation environment. There is no problem. CPU loading clock is 100%.
