### ISSUE TITLE
Option to prevent 'Untitled-1' when starting

### ISSUE THREAD

**Issue by Bill-Stewart** [Microsoft/vscode#12387]
Normally I don't need the untitled file when starting. If I want one, I can press <kbd>Ctrl</kbd>+<kbd>N</kbd>. It would be nice to have this as an option.

**Comment by mbirth** [comment]
Even with the new Welcome page, I *still* get the Untitled-1 document **and** the Welcome tab.

**Comment by chrmarti** [comment]
Only having one of the two is tracked with #19689

**Comment by Otiel** [comment]
I second this, an option would be nice. Something like `workbench.startup`, which would replace the current `workbench.welcome.enabled` with the following values:

* `none` : start empty
* `welcome` : show the Welcome page on startup
* `new-tab` : show a new 'Untitled' tab on startup

**Comment by chrmarti** [comment]
@bpasero I'm about to replace the existing `workbench.welcome.enabled` boolean with a `workbench.startupEditor` enum with `none`, `welcomePage` (default) and `newUntitledFile` as possible values.

@Tyriar suggests to instead keep the boolean and simply make the new untitled file show in a 'preview' editor that would disappear when another editor opens (if it has no content at that point).

I'm more leaning towards the enum setting with 3 values, that is more explicit than the sometimes magical preview editor and will be easy to reuse if we find more startup scenarios we want to cover. What do you think?

**Comment by deadlydog** [comment]
For what it's worth @chrmarti, I like the idea of doing both. Have an enum value with the 3 options you suggested, and also change the behavior of the `newUntitledFile` option so that it shows in a "preview" editor. Having a blank tab open at startup can be convenient, but it doesn't typically make sense to keep it around when opening other files/projects (when it has no content).

**Comment by Bill-Stewart** [comment]
What is the advantage of an blank tab vs. no tab?

**Comment by Tyriar** [comment]
> What is the advantage of a blank tab vs. no tab?

Untitled file: Can start typing immediately, needs to be dismissed explicitly before it goes away.

Untitled "preview" file: Can start typing immediately, goes away if it hasn't been touched and another file is opened.

No tab: looks nice, shows common keybindings for new users:

**Comment by Bill-Stewart** [comment]
I wasn't aware of the "untitled preview file" one. It sounds like we could have a single option with any of the 4 starting settings: Untitled-1 file, welcome screen, preview file, or nothing at all.

**Comment by Tyriar** [comment]
@Bill-Stewart I believe Untitled "preview" file would be a new concept. I'd prefer we opted on simplicity in this case, having either 2 or 3 options for the setting.

**Comment by Bill-Stewart** [comment]
I'm happy with whatever, as long as we can have a "no tab" startup, which was my original intent.

**Comment by chrmarti** [comment]
@Tyriar Sounds like we are good with the 3 options setting? If so, I would like to push that and look into making the untitled file a preview editor separately.

**Comment by Tyriar** [comment]
@chrmarti good by me if this issue is wanted by people. I created https://github.com/Microsoft/vscode/issues/29474 to follow up the untitled preview concept as it's an improvement and a separate piece of work.

**Comment by Bill-Stewart** [comment]
Sounds good to me also, thank you!
