### ISSUE TITLE
Shift+Ctrl+H searches for something NOT in the search field

### ISSUE THREAD

**Issue by aedwill** [microsoft/vscode#123821]
Issue Type: <b>Bug</b>

When I highlight text and do a Shift+Ctrl+H to replace in all files the highlighted text is placed in the Search box, cursor is in the replace box.  All is good.  The search results come back with text not in the search field.  In this current example I see a search for "Scroll", and "TextInputLayout" was typed in the search field, "TextBoxLayout" in the replace with field.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (36.01GB free)|
|Process Argv|. --crash-reporter-id bc8cdc62-8252-43a1-9fe4-91f708c1bf32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.4.0
vscode-jest-runner|fir|0.4.34
vscode-azureappservice|ms-|0.21.2
vscode-azureresourcegroups|ms-|0.3.0
csharp|ms-|1.23.11
azure-account|ms-|0.9.8
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.2
vs-code-prettier-eslint|rve|3.0.2
autoimport|ste|1.5.4

</details>

![image](https://user-images.githubusercontent.com/458410/118189119-39eb9800-b3f6-11eb-8490-06b3f3aca213.png)

**Comment by roblourens** [comment]
Works ok for me. Do you know where `Scroll` came from? Were you searching for that at some point? Does this happen every time?
