### ISSUE TITLE
Banner is visible even when not shown

### ISSUE THREAD

**Issue by onionyst** [microsoft/vscode#123858]
Issue Type: <b>Bug</b>

The upper half of the Explorer Icon has an overlap of a blue rectangle. It has lasted for a few days. 

VS Code version: Code - Insiders 1.57.0-insider (7771be8b981d4fff2c6de123dad953517253c395, 2021-05-14T05:54:04.153Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 91027eee-79e3-4f38-a2ba-971223a1c117|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscorehov:30301224
vscod805cf:30301675

```

</details>

![vsc-icon](https://user-images.githubusercontent.com/14269397/118242480-f82f2000-b4cf-11eb-882d-6e72c93313d4.png)

**Comment by sbatten** [comment]
@onionyst Are you familiar with web dev tools? Would you be able to inspect this element to see what's causing the overlap? The command to show dev tools is `Toggle Developer Tools` and can be found in the `Help` menu.

**Comment by onionyst** [comment]
I think it's `div#workbench.parts.banner`. 

![vsc-bar](https://user-images.githubusercontent.com/14269397/118295980-11a38c80-b50f-11eb-91ed-5c77a523cd31.png)

I added `style="display: none"` on this `div` and the overlap disappeared.

**Comment by sbatten** [comment]
@onionyst awesome, thanks for that info. do you have any special settings around theming?

**Comment by onionyst** [comment]
Ah. Probably caused by extension `rokoroku.vscode-theme-darcula` (v1.2.3). 

I have `"workbench.colorTheme": "Darcula"` and it seems only this theme causes the overlap.

**Comment by sbatten** [comment]
Thanks again, after investigating, it looks like this happens because the activity bar color from Darcula has a transparent activity bar color allowing the banner to peek through. Though it only happens on this theme (and possibly some other themes that do the same) it is a bug that the banner is showing anything for you at that time.
