### ISSUE TITLE
Markdown Header Incorrect Syntax Highlighting

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/vscode#1238]
When there is a valid `#` in the header, the syntax highlighter for markdown misunderstands it to be the termination of the header.

<img width="963" alt="test_md_-_workshop-materials-1-8" src="https://cloud.githubusercontent.com/assets/1282577/11777576/31e73a04-a247-11e5-8a02-0a1c91e4c8ae.png">

I would be glad to help, but would need to get pointed in the right direction in the code to understand where I can make the change and submit a PR.

**Comment by bpasero** [comment]
@kitsonk Thanks, that would be: https://github.com/Microsoft/vscode/blob/master/src/vs/languages/markdown/common/markdown.ts#L56
