### ISSUE TITLE
JavaScript `console.log` is not displayed when Debug Console panel is not visible

### ISSUE THREAD

**Issue by rveerd** [microsoft/vscode#123886]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041

1. Create a new NPM project:

```console
mkdir my-project
cd my-project
npm init -y
```

2. Add `index.js`

```js
console.log('foo');
console.log('bar');
```

3. Click "Run and Debug".

The output is shown in the Debug Console panel when the panel is active/visible when you run the application. The output **is not** shown in the Debug Console panel when the panel is not active/visible when your run the application.

Of course I can make sure Debug Console is active/visible before clicking "Run and Debug". But this does not work if I have a pre-launch task configured that switches to another panel and thereby hides the Debug Console panel.

**Comment by rveerd** [comment]
As a workaround, I can force the Debug Console to always to become visible by adding `"internalConsoleOptions": "openOnSessionStart"` to `launch.json`.

**Comment by isidorn** [comment]
Yeah that is the idea, just use `internalConsoleOptions` setting please
