### ISSUE TITLE
No support for horizontal scrolling in a notebook output cell

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#123816]
@randomQQQ commented on [Sun May 09 2021](https://github.com/microsoft/vscode-jupyter/issues/5816)

## Environment data
Issue Type: <b>Bug</b>

No scrolling in pandas dataframe output

Extension version: 2021.6.819764235
VS Code version: Code - Insiders 1.57.0-insider (a19565da7dfc739fa26e36aae96113e19fe3806f, 2021-05-07T17:19:03.737Z)
OS version: Windows_NT x64 10.0.19042

## Actual behaviour
![image](https://user-images.githubusercontent.com/63656568/117564831-ab55de80-b0b6-11eb-9fab-9c7bdd414dc0.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/63656568/117564897-1dc6be80-b0b7-11eb-809c-8f650d3660fa.png)

---

@DavidKutu commented on [Mon May 10 2021](https://github.com/microsoft/vscode-jupyter/issues/5816#issuecomment-837108315)

Thanks for the issue @randomQQQ. As a quick work around, you can use the middle mouse button to scroll.
But we'll take a look with vscode.
@rebornix

**Comment by claudiaregio** [comment]
+1 customer feedback 
![image](https://user-images.githubusercontent.com/19276747/122595683-abce8700-d01d-11eb-9a67-8f769bde653e.png)

**Comment by claudiaregio** [comment]
+1 customer feedback - Jupyter ext rating on marketplace
![image](https://user-images.githubusercontent.com/19276747/122790001-bb8fda80-d26c-11eb-98b8-3d38d9b952c2.png)

**Comment by rebornix** [comment]
Fixed in main.
