### ISSUE TITLE
cannot update

### ISSUE THREAD

**Issue by lemonlife2333** [microsoft/vscode#123852]
Issue Type: <b>Bug</b>

when i begin to update the vsode ,it will tell me it has another process

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.87GB (8.41GB free)|
|Process Argv|--crash-reporter-id e53a6827-04ab-4582-9761-e13dfc8f3b25|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
scala-lsp|dra|0.2.3
shell-format|fox|7.1.0
markdown-extended|jeb|1.0.19
vscode-language-pack-zh-hans|MS-|1.56.2
python|ms-|2021.5.840043038
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
azure-account|ms-|0.9.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
bridgeflight:30299254
vscod805cf:30301675

```

</details>

**Comment by gjsjohnmurray** [comment]
Can you try a Windows restart first?

**Comment by lemonlife2333** [comment]
> Can you try a Windows restart first?

yes,i tried

**Comment by gjsjohnmurray** [comment]
Maybe restart Windows again, launch VS Code from a command prompt using `code  - - disable-extensions ` and then check for updates.

**Comment by lemonlife2333** [comment]
> Maybe restart Windows again, launch VS Code from a command prompt using `code --disable-extensions ` and then check for updates.

thanks!I updated successfully.would you mind to tell me what happens about my vscode?is it  need to reinstall?

**Comment by lemonlife2333** [comment]
> No, the `--disable-extensions` switch only applies to the one launch. Now that it has updated can you launch it normally?

yes

**Comment by gjsjohnmurray** [comment]
Please close your issue, or say what other help you need with it.
