### ISSUE TITLE
VS Code window crashes after installing current Windows update. Anyone else experience this?

### ISSUE THREAD

**Issue by DeltaJohn** [microsoft/vscode#123814]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
Please provide detailed information what you mean by

>installing current Windows update

**Comment by DeltaJohn** [comment]
The update in question was the recent 'Feature update to Windows 10, version 20H2' however I have found that the update install had been interrupted on my individual computer. After I got the install accomplished my problem no longer occurs. Thanks you for your response though!

**Comment by deepak1556** [comment]
> After I got the install accomplished my problem no longer occurs.

@DeltaJohn can you confirm if vscode is no longer crashing ? Can we close this issue ?

**Comment by DeltaJohn** [comment]
Correct, no longer crashing. Issue may be closed. Thanks!
