### ISSUE TITLE
Test: variable substition in launch.json and tasks.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12384]
- [x] any os @gregvanl 
- [x] any os @jrieken 

complexity: 3

We have consolidated our variable substition between debug and tasks into a `configurationResolverService` - #8754. Quickly verify:
* Simple variables get replaced inside `launch.json` and `tasks.json` as descirbed [here](http://code.visualstudio.com/docs/editor/tasks#_variable-substitution)
* You can reference environment variables inside your `launch.json` and `tasks.json` by using `${env.NAME}` syntax
* You can reference vscode settings inside your `launch.json` and `tasks.json` by using `${config.NAME}` syntax
* You can reference interactive variables inside your `launch.json` by using `${command.PickProcess}`

**Comment by gregvanl** [comment]
Tested on Windows 7.
