### ISSUE TITLE
[Getting Started] walkthroughs.steps.when with isWindows/etc. gives us the local OS when we want the remote OS

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#123824]
Version: 1.57.0-insider (user setup)
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:13:18.296Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

@digitarald With our C/C++ extension we're seeing "when": "isWindows" giving results for the local machine when we need the remote machines.

```
    "walkthroughs": [
      {
...
        "steps": [
          {
            "when": "isMac",
...
```

Let me know if you need more repro info.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode/issues/118402#issuecomment-840824154_

**Comment by JacksonKearl** [comment]
This is a bit interesting because each window can have potentially many remotes. So we'd have to add context keys of the form `hasMacRemote`, `hasLinuxRemote`, `hasWindowsRemote`. I don't think there's anything like that currently available.

**Comment by sean-mcmanus** [comment]
As far as I've seen, there is only 1 remote target for the entire VS Code instance; otherwise, our extension which runs a binary locally would not be able to function, since we require remote binaries that match the target OS.

**Comment by JacksonKearl** [comment]
Okay, I see what you mean. Yeah the `when` conditions for platform are always evaluated with respect to the renderer... we could either add new when conditions for the remote's platform, or do something custom in the getting started contribution point for platform-specific entries. cc @aeschli for thoughts on adding something like a `remoteIsMac`/`remotePlatform`/etc. context key

**Comment by aeschli** [comment]
`'isMac` answers the question in which OS the VSCode UI is running, but toy want to know in what OS the workspace is running.
I don't think we have such a context variable (@alexdima @bpasero ?)
If we add one I wouldn't limit it to `remote` but something like `workspacePlatform`.


The workaround is for the extension to define it's own, fitting context key.

**Comment by sean-mcmanus** [comment]
@aeschli Oh, thanks, we'll try defining our own context key.

**Comment by sean-mcmanus** [comment]
@aeschli Actually, context keys won't work because it requires extension activation (and there's also no "when" clause to detect if our extension is already activated or not). The walkthrough owners didn't want to require extension activation.

**Comment by JacksonKearl** [comment]
@sean-mcmanus yes, I'll go ahead and add a `workspacePlatform: 'mac'|'linux'|windows'|'unknown'` context key. (`unknown` will handle cases like serverless, where there is no platform).

**Comment by aeschli** [comment]
Can we add `web` for the web extension host?

**Comment by alexdima** [comment]
@aeschli How should that work? It is possible to have at the same time the local `ui`, the local `web` and the remote `workspace` extension hosts. Which one should the `workspacePlatform` reflect?

**Comment by aeschli** [comment]
@alexdima You are right, complicated. It would only be web if there are no local or remote extension hosts.

**Comment by JacksonKearl** [comment]
Is there a way to check if the only extension host available is `web`? i.e. running in serverless.
