### ISSUE TITLE
Support switching tab with Alt+Tab (like edge chromium)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/vscode#123874]
Edge chromium browser has a delightful feature: switching tab using alt+tab. If multiple tabs are opened in edge chromium, all the tabs will show separately in the alt+tab menu, along with other windows.
![image](https://user-images.githubusercontent.com/54425948/111868650-24d62800-89b6-11eb-8993-07fdfa521df3.png)
However, if multiple files are opened in vscode, only one tab is shown in the alt+tab menu.
![image](https://user-images.githubusercontent.com/54425948/118261539-44855a80-b4e6-11eb-9cbc-6ed0eeddf338.png)
I hope that vscode can behave like microsoft edge, showing all tabs in the alt+tab menu. This feature will be very useful when I'm debugging multiple file at once, and I need to jump from another application to a certain file in vscode.

**Comment by icepaq** [comment]
You can switch tabs by hitting Ctrl+Tab.

VScode will only show you the titles of each page (no preview like what windows does), but I think that's all we really need.

**Comment by sbatten** [comment]
As @icepaq says, ctrl+tab supports switching between multiple files which is scoped to VS Code tabs. I think this is the right solution instead of polluting the alt+tab menu with lots of open code files.
