### ISSUE TITLE
`MainThreadEditorTabs` does not account for tabs moving

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#123864]
I came across `MainThreadEditorTabs` which seems to be a way for extensions to get (readonly) access to all opened editors in sequential order. Even though the complicated listening already present, when a tab moves from one index to another (e.g. via DND), the `_pushEditorTabs` method is not called because none of the listeners are firing. 

I can look into providing a single listener, possibly from `IEditorService`, along the lines of `onDidEditorsChange` maybe to avoid clients having to attach to all groups.

But I first wanted to understand how `MainThreadEditorTabs` was added and what the correlation is with https://github.com/microsoft/vscode/issues/15178 (cc @eamodio)

**Comment by jrieken** [comment]
> But I first wanted to understand how MainThreadEditorTabs was added and what the correlation is with #15178 (cc @eamodio)

It is the start of the proposal for exactly that. I went ahead with this to enable @dbaeumer's diagnostics push model

**Comment by bpasero** [comment]
Actually I think the listening is done just fine but to truly capture any change to tabs (order, label), I think more events are needed in the [`_GroupEventFilter`](https://github.com/microsoft/vscode/blob/2f500f0ce560eac073c3065b90d8f21757edcc04/src/vs/workbench/api/browser/mainThreadEditorTabs.ts#L22-L22), specifically `GroupChangeKind.EDITOR_MOVE` and `GroupChangeKind.EDITOR_LABEL`.

I would also think that a listener for `IEditorGroupsService.onDidMoveGroup` needs to be added to account for an entire group moving (which is possible via drag and drop or through some layout related commands).

One thing to note is that `GroupChangeKind.EDITOR_LABEL` will fire for untitled documents anytime a character is typed in the first line because untitled editors show the contents of the first line in their title. Before sending all tabs over from that event, I think some debouncing should be added.

**Comment by bpasero** [comment]
I added `onDidEditorsChange` because I want to use it in other places, which makes `mainThreadEditorTabs` require a lot less code to react to changes, the event covers:
* active editor changes
* any change to opened editors (editor open, editor close)
* moved editors
* moved groups
