### ISSUE TITLE
Bracket matching inside strings

### ISSUE THREAD

**Issue by Bill-Stewart** [Microsoft/vscode#12388]
I write a lot of code that contains LDAP query strings, meaning lots of expressions inside `( )` inside quoted strings. It would be nice to be able to have highlighting of matching `( )` (and also, to be able to jump to matching pairs) within quoted strings.

**Comment by chrmarti** [comment]
What programming language is the file written in? I think that language's extension would have to implement this.

**Comment by Bill-Stewart** [comment]
Ah, so this is managed exclusively by the extension for that file type? The file type is usually Windows PowerShell, although this would be handy for JavaScript and VBScript as well.

**Comment by chrmarti** [comment]
Actually the language-configuration.json has most of the information to implement this generically. 

We somehow disable matching bracket highlighting within strings, even though the language-configuration.json does not appear to specify what a string is. Maybe we could just add a setting to turn off that behavior.
