### ISSUE TITLE
Export all markers from the problem window to a file

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode#123854]
I would like to be able to export all markers from the problem window to a file. Here is my scenario: If I do a migration of an existing project to a new version, new technology or something similar, I often end up with a very long list of problems. That is expected and I just need to work through it. But if I decide to share it in a team or just get a better overview, it would be very useful to export the full list to a CSV file, which I can then open in e.g. Excel to sort, filter etc.

**Comment by sandy081** [comment]
I do not think this is a feature that is worth to be added to VS Code out of the box. I would recommend to write an extension using the api - `getDiagnostics` and implement this feature.
