### ISSUE TITLE
Option to enable breakpoints to stop when warnings are raised in the python debugger

### ISSUE THREAD

**Issue by whentheworldfallsapart** [microsoft/vscode#123889]
It would be nice if under the breakpoints drop down in the debugger if there was an option to set a breakpoints for warnings (understanding that warnings are handled completely different from exceptions in python). Numpy allows raising warnings as errors "np.seterr(all='raise')", this can be used to help locate what is causing a divide by zero warning for example. But most packages dont have this feature, and tracing down warning while looping over large sets of data can often require print statements to locate which input data is causing a warning inside a package. Having the feature in vscode debugging to add breakpoints to stop on warnings would be very helpful. (This a popular feature in MATLAB for example, allowing the user to stop on warnings).

**Comment by egamma** [comment]
Please file the feature request against the python extension so that the discussion can start over there and then propagate to the VS Code providing generic debugging infrastructure.
