### ISSUE TITLE
Command URL in debug extension ErrorResponse Message is ignored

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#123831]
Issue Type: <b>Bug</b>

If my debug extension returns an ErrorResponse with a Message in its body, and the Message specifies a url string of the form 'command:x.y' then VS Code  does not run the command when the user clicks the button in the error dialog.

I will submit a PR.

/assign @isidorn

VS Code version: Code - Insiders 1.57.0-insider (659175fa39b994fc39381b0af2874c85efeb2a01, 2021-05-13T05:13:18.296Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
@gjsjohnmurray thanks a lot for letting us know and for providing a PR.
It would be great if you could verify this from Monday once VS code insiders has your fix. Thanks a lot!

**Comment by JacksonKearl** [comment]
@gjsjohnmurray are you able to verify?
