### ISSUE TITLE
Unable to run Angular projects

### ISSUE THREAD

**Issue by zendu** [microsoft/vscode#123807]
Issue Type: <b>Bug</b>

I see following error on opening project in VS Code. This started after upgrading to latest VS Code version today.

Angular extension might not work correctly because ngcc operation failed. Try to invoke ngcc manually by running 'npm/yarn run ngcc'. Please see the extension output for more information.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (2.81GB free)|
|Process Argv|--crash-reporter-id 9a72daf1-1874-4d6f-a4f9-6a0336de31d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|12.0.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-firefox-debug|fir|2.9.4
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.6.0
rainbow-csv|mec|1.8.1
azure-pipelines|ms-|1.183.0
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.1.0
vscode-edge-devtools|ms-|1.1.8
sarif-viewer|MS-|3.0.2
jupyter|ms-|2021.6.832593372
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell-preview|ms-|2021.4.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscus158:30286553

```

</details>

**Comment by gtteamamxx** [comment]
I had similar issue today due to today's angular update from v11 to v12. I removed all ^ from packages to explicitly set version of packages. For example in package.json. Also remove package-lock.json, node_modules and run `npm install`. Then all should work fine. 
` "@angular/common": "^11.2.11"` to `"@angular/common": 11.2.11"`.
