### ISSUE TITLE
Debugger: Put "Run To Cursor" Into Breakpoint Context Menu

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#123872]
Currently, "Run To Cursor" is in a very long context menu:

![image](https://user-images.githubusercontent.com/2931520/118254090-fdc63f00-b4aa-11eb-97e0-500a917690f6.png)

I think it would make sense to add "Run To Cursor" to the context menu for adding breakpoints:

![image](https://user-images.githubusercontent.com/2931520/118253920-c9eb1980-b4aa-11eb-997b-22cd5ab4a973.png)

This new entry should be called "Run To Line".

Pro:
* That context menu is already strictly debugging related
* If a user does not know about "Run To Cursor" and manually places a breakpoint to the target location, they might discover this functionality in that context menu

Contra:
* "Run To Line" is not a breakpoint

**Comment by isidorn** [comment]
@hediet thanks for this suggestion, however please note that we show the `Run To Cursor` and `Add Inline Breakpoint` in the editor context menu only while a user is debugging. So it is not always there.

I understand you are always in debugging mode and I think we should improve the experience for "Always Debugging" mode. For this I have created https://github.com/microsoft/vscode/issues/123873

For now I would probably not change this to not anger some users that are used to it. Especially since I hope we will have customisable context menus in the future. However I am open for ideas.

fyi @connor4312 @weinand

**Comment by hediet** [comment]
> however please note that we show the Run To Cursor and Add Inline Breakpoint in the editor context menu only while a user is debugging. So it is not always there.

I wouldn't neccessarily remove it from the editor context menu, but just add it to the breakpoint context menu to improve its accessibility.

I use that feature quite often (and should probably assign a keybinding to it), but the very long context menu makes it hard to quickly execute that action (especially when my focus is on debugging the problem, not finding that context menu entry).

[The Chrome dev tools have an even more efficient approach](https://developer.chrome.com/blog/new-in-devtools-60/#continue) - while debugging, you can simply Ctrl-Click on a statement to continue to it.

**Comment by isidorn** [comment]
@hediet oh you would simply add it to the other context menu.
Yeah this could work for me.

Let's see what @connor4312  and @weinand think

**Comment by connor4312** [comment]
Adding it to the breakpoint (gutter) context menu sounds good to me. Honestly I didn't even know that context menu entry existed, I never right click in the editor 😛

**Comment by isidorn** [comment]
If we were to add it, I would put a separator after the breakpoint actions. And have the "Run to Line" at the bottom.
Let's assign to this milestone and if Andre does not object I can add it next week.

**Comment by hediet** [comment]
I can also try to implement it if we go for it! Shouldn't be that hard.

**Comment by connor4312** [comment]
Code pointer:

https://github.com/microsoft/vscode/blob/1ccd6a079463a635756f35308e290551ca135241/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L317

**Comment by hediet** [comment]
Do you think the logic in `RunToCursorAction` should be moved to `IDebugService` and its implementation (and there renamed to `RunToPosition`)?
Then there could be both a `RunToCursorAction` and `RunToLineAction`.

**Comment by isidorn** [comment]
@hediet that might work. However I try to keep the `IDebugService` as thin as possible. So I would personally just use the  `commandService.executeCommand` to execute one command from the other.
Though feel free to move the logic to the `IDebugService` if you prefer that

**Comment by isidorn** [comment]
Leaving this assigned to you @hediet as you plan to do a PR.
Feel free to ping me on a PR for a review or let me know if I can help in any way.

**Comment by heartacker** [comment]
consider add a decorate for user to click run to here, like VS2019?
![image](https://user-images.githubusercontent.com/1876302/125381088-e4b40e80-e3c5-11eb-91ce-5e20b3bdfcf6.png)

**Comment by lramos15** [comment]
There's a bit of breakpoint flashing when you do run to line but the context menu appears to work so marking this as verified
