### ISSUE TITLE
Diff editor with "centered mode" on has wrong width

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#123802]
- Open a text editor, "Toggle Centered Layout", make it narrow
- Open a diff editor with side-by-side mode enabled
- In this mode, the diff editor should take the full width, but instead it takes the narrow width of the centered layout editor

![image](https://user-images.githubusercontent.com/323878/118168941-3ef01d80-b3dd-11eb-8c43-4305c4a6543f.png)

If I resize the window, the diff editor gets sized correctly

**Comment by alexdima** [comment]
I could no longer reproduce, I think this might have gotten fixed in the meantime.

**Comment by isidorn** [comment]
Yes this got fixed by Joao. Duplicate of an existing issue. Thus closing
