### ISSUE TITLE
Terminal does not save "type" information on reload

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#123878]
Issue Type: <b>Bug</b>

1. open a Javascript Debug Terminal
2. Reload VSCode

Actual:
Terminal gets converted into bash

Expected:
Terminal should be a JS Debug terminal 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 4.14.231-173.361.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:7dbabc932f8e9e3558e3a0d98ce26505d34bde3840e60353d817988c63897107 (/nk-dev-conn_pm2_1) @ aws-docker|
|OS|Linux x64 4.14.231-173.361.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (8.10GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.177.2
vscode-openapi|42C|4.5.1
atlascode|atl|2.8.6
npm-intellisense|chr|1.3.1
regex|chr|0.4.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
bash-ide-vscode|mad|1.11.0
mongodb-vscode|mon|0.5.0
compare-folders|mos|0.22.0
vscode-yaml|red|0.19.0
vscodeintellicode|Vis|1.2.13

</details>

**Comment by navneetkarnani** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> - [Terminal (#123207)](https://www.github.com/microsoft/vscode/issues/123207) 
> 

No it does not.

**Comment by Tyriar** [comment]
Confirmed to be fixed in [insiders](https://code.visualstudio.com/insiders/)
