### ISSUE TITLE
Native Notebooks - Data Loss

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123835]
Version: 1.57.0-insider (user setup)
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:13:18.296Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

Jupyter ext: v2021.6.838387092

Working in insiders, opened up a saved notebook and **_all of the content was gone._** 

https://github.com/microsoft/vscode/issues/118592

**Comment by rebornix** [comment]
I think this one is already resolve.d

**Comment by claudiaregio** [comment]
As of recently? It just happened to me yesterday :(
