### ISSUE TITLE
Multiple device sync for Custom Snippets

### ISSUE THREAD

**Issue by asphub** [microsoft/vscode#123880]
Can we do a Multiple device sync for Custom Snippets like wise the Settings sync works.

This feature will be more easier to working different devices as a team and custom snippets for each Project Workspaces.

**Comment by asphub** [comment]
> /needsMoreInfo

Here is one example Snippet I created for React component

_**snippets\typescriptreact.json**_

```json
{
	"React Component": {
		"prefix": "rc",
		"body": [
			"import './${1:$TM_FILENAME_BASE}.scss';\n",
			"const ${1:$TM_FILENAME_BASE} = () => {",
			"  return (",
			"    <div className='${1:$TM_FILENAME_BASE}'>",
			"      $2",
			"    </div>",
			"  );",
			"};\n",
			"export default ${1:$TM_FILENAME_BASE};",
		],
		"description": "React Component with SCSS"
	}
}
```

Needs to sync these custom snippets across the devices with the Settings SYNC.

**Comment by gjsjohnmurray** [comment]
Similar to #91011, which is for user tasked.

**Comment by asphub** [comment]
Why its closed I added info in [this comment](https://github.com/microsoft/vscode/issues/123880#issuecomment-841233273)

**Comment by sandy081** [comment]
@asphub User snippets are synchronized. May I know where does your snippets located? Are you using out of of the box settings sync?

**Comment by asphub** [comment]
> 
> @asphub User snippets are synchronized. May I know where does your snippets located? Are you using out of of the box settings sync?

@sandy081 Pls see the path of snippets:

_[C:\Users\<username>\AppData\Roaming\Code\User\snippets\typescriptreact.json](C:\Users\<username>\AppData\Roaming\Code\User\snippets\typescriptreact.json)_

**Comment by sandy081** [comment]
Thanks for info. We do sync user snippets. Can you please try following?

- Enable sync on machine 1 and machine 2
- Open settings sync - synced data view - Use command `Settings Sync: Show Synced Data`
- Open settings sync log - There is an action available in the title of the view to open the log
- From machine 1, create a user snippet - Check in the settings sync log that sync is triggered and completed.
- Refresh the Sync Activity (Remote) view - Check that snippet you created is pushed to remote. Refresh the view.
- From machine 2 - open the settings sync view and logs
- Wait for a moment for sync to be triggered
- Check that snippet you created in machine 1 is synced

If any of the above steps are not happening, please share the settings sync log from machine 1 and machine 2

**Comment by asphub** [comment]
> 
> 
> Thanks for info. We do sync user snippets. Can you please try following?
> 
>     * Enable sync on machine 1 and machine 2
> 
>     * Open settings sync - synced data view - Use command `Settings Sync: Show Synced Data`
> 
>     * Open settings sync log - There is an action available in the title of the view to open the log
> 
>     * From machine 1, create a user snippet - Check in the settings sync log that sync is triggered and completed.
> 
>     * Refresh the Sync Activity (Remote) view - Check that snippet you created is pushed to remote. Refresh the view.
> 
>     * From machine 2 - open the settings sync view and logs
> 
>     * Wait for a moment for sync to be triggered
> 
>     * Check that snippet you created in machine 1 is synced
> 
> 
> If any of the above steps are not happening, please share the settings sync log from machine 1 and machine 2

Thanks for the support @sandy081

Its working after waiting for some seconds
