### ISSUE TITLE
[Getting Started] In the remote scenario, images don't appear when referenced in walkthroughs.steps.media.path

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#123820]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:Version: 1.57.0-insider (user setup)
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:13:18.296Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
- OS Version: Windows (local), Linux (remote)

Steps to Reproduce:

1. In the remote scenario, use a getting started walkthrough that references an image in the media.path.
package.json:
```
    "walkthroughs": [
      {
        "steps": [
...
          {
            "media": {
              "path": {
                "light": "walkthrough/intellisense-config-light.png",
```
Bug: The image doesn't appear. The image apperas if media.path references an .md file and the .md file references the image.

Let me know if you need more repro info.

![image](https://user-images.githubusercontent.com/19859882/118188809-d3667a00-b3f5-11eb-8216-d1cdad2c667a.png)

**Comment by JacksonKearl** [comment]
Ah, need I must not be transforming URI's correctly.

**Comment by JacksonKearl** [comment]
Thanks for the report! Should be fixed in tomorrow's insiders.
