### ISSUE TITLE
Exts can steal all focus

### ISSUE THREAD

**Issue by FallenAvatar** [microsoft/vscode#123870]
We have written the needed data into your clipboard becaus
Issue Type: <b>Bug</b>

Basically, I am using VSCode {between 2 PCs, windows both} but this issue is java related, and I think it is the Microsoft Java Dev Extention.

I don't know its name specifically, and I do not care. This Feedback window sucks. Maybe its VSCode, maybe its Redhat, maybe its Microsoft,

It sucks, with or without the "Java Project Manager" or w/e it's called

I'd guess its the Redhat "java" extension. But I just constantly run into issues' while using it. Loading and refreshing projects takes forever, not to mention I have experienced a greater than 50% failure rate of the "Java Syntaxt" server? prrocess? console? terminal?

I wish I could give you more details, but basically java hangs in such a way that VSCode does not recognize......

I will say, check my env about my adopt open jdk version(curently, due to tooling) and then some.

- Amy

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (36.29GB free)|
|Process Argv|--crash-reporter-id ca12bb2b-125d-4e00-ac8b-7edf8197f919|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.10
Bookmarks|ale|13.0.4
project-manager|ale|12.1.0
vscode-json|and|1.5.0
code-gnu-global|aus|0.2.2
toml|be5|0.5.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
task-panel|Bit|0.2.0
vscode-intelephense-client|bme|1.7.1
phpserver|bra|3.0.2
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.22.0
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
mc-json-viewer|han|1.0.6
beautify|Hoo|1.5.0
mcfdebugger|Hug|0.1.1
rest-client|hum|0.24.5
wsl-path|kgr|0.1.0
mcjson|Lev|0.4.1
code-beautifier|mic|2.3.3
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
python|ms-|2021.5.840043038
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
gradle-language|nac|0.2.3
php-docblocker|nei|2.1.0
indent-rainbow|ode|7.5.0
minecraft-essentials-extension-pack|pah|1.0.1
material-icon-theme|PKi|4.6.0
vscode-css-peek|pra|4.2.0
java|red|0.79.1
vscode-yaml|red|0.19.0
vscode-gradle|ric|3.6.1
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
vscode-checkstyle|she|1.4.0
vscode-3dviewer|sle|0.2.2
datapack-language-server|SPG|3.3.4
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
gistfs|vsl|0.2.8
eno|Wsc|2.3.53
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
cursorCharCode|zei|0.2.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30301222
vscod805cf:30301675

```

</details>

e it was too large to send. Please paste.

**Comment by Tyriar** [comment]
You'll need to report the issue to the extensions that caused the problem. If it's related to Java language services, this is definitely not the right place for it.
