### ISSUE TITLE
Clear Terminal command buggy when using Git Bash

### ISSUE THREAD

**Issue by amritRaj789** [microsoft/vscode#123801]
Issue Type: <b>Bug</b>

**Steps to reproduce :** 
1. Open a new Git Bash Terminal
![Screenshot (10)](https://user-images.githubusercontent.com/65883807/118168325-5a8f0e80-b445-11eb-8c38-6c0d974f1b3c.png)

2. Run few commands (just to populate the console)
![Screenshot (11)](https://user-images.githubusercontent.com/65883807/118168344-61b61c80-b445-11eb-8f69-8ca79d7aa1b4.png)

3.  Ctrl+Shift+P (to open command palette)
![Screenshot (12)](https://user-images.githubusercontent.com/65883807/118168367-68dd2a80-b445-11eb-83d1-8856207535ac.png)

4. Search for 'Terminal: clear' command and hit enter
![Screenshot (13)](https://user-images.githubusercontent.com/65883807/118168439-7397bf80-b445-11eb-88f7-ce22bdf78672.png)

Expected Result: _Terminal clears with prompt intact_

Actual Result: _Terminal clears with prompt missing_

**Note:** _I checked PowerShell for comparison, the clear terminal worked fine and the prompt was intact.
By prompt I refer to the prompt that includes the path of the CWD and the host name and it appears above every line of command that is entered._

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (11.58GB free)|
|Process Argv|C:\\Users\\amrit\\Documents\\testing --crash-reporter-id ea12f45e-0bb4-474e-b4b2-dd7a525b8dfe|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscorehovct:30301223

```

</details>

**Comment by Tyriar** [comment]
This is by design, the clear command will clear all non-cursor lines and move the cursor line to the top. You probably want your shell to do the clearing which would involve running `clear`, `cls`, etc.

**Comment by amritRaj789** [comment]
I see . 
I still believe having prompt intact would feel more natural as it gives us an idea of the CWD. The fact that the same doesn't happen with Powershell or CMD (ones I could test) makes this behavior inconsistent at the least. 
So in conclusion I am not sure if this now qualifies as a 'feature request' or this is how it is supposed to be.
Thank you for your reply though. Cheers!

**Comment by Tyriar** [comment]
It doesn't happen in cmd or powershell because the prompt is single line. Unfortunately there isn't any way we can do better without adding hacky/unreliable heuristics guessing where the prompt is.
