### ISSUE TITLE
Restart of the project didn't read current launch configuration

### ISSUE THREAD

**Issue by ryordanov** [microsoft/vscode#123859]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Run configuration in launch.json `"name": "xxx",
            "type": "node",
            "request": "launch",
            "console": "integratedTerminal",
            "program": "${workspaceRoot}/index.js",
            "args": [...]`
2. Modify some of the args
3. Restart the application via button "Restart (Ctrl + Shift + F5)"

The Node.JS application starts with the old configuration.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/118196
This should  work nicely with latest VS Code insiders thanks to @connor4312
