### ISSUE TITLE
Navigate to file and line in one command

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#12381]
Actually the "omnibar" is able to navigate to a file or navigate to a line number, but it is not able to do both in a single action.

For example, if I want to open `test.js` and go to line `300`, the sequence is

1. CMD + P
2. `test.js`
3. Enter
4. CMD + P
5. `:300`

It would be really great if I could simply do
1. CMD + P
2. `test.js:300`
3. Enter

Done. I'm at `test.js` file at line 300.

**Comment by XVincentX** [comment]
@chrmarti I'd love to try to contribute for this feature if you could point me to the right lines (or at least the area of code I should look for)

**Comment by chrmarti** [comment]
@XVincentX This appears to be already implemented. The code is in openAnythingHandler.ts. Your example should work, does it not?

**Comment by XVincentX** [comment]
@chrmarti 
Yes it does - let me elaborate - I did not provide enough details.

I think it would be a good idea, while searching the file, to start opening the first occurrence and scroll as I type the line number. I think that visual feedback while moving across files and lines it's a great thing!

What's your thought?

**Comment by chrmarti** [comment]
Showing the currently selected file in a temporary editor is a separate feature. I'd suggest to close this issue and open a new one for the new request.

**Comment by chrmarti** [comment]
@XVincentX Also take a look at the 'help wanted' labeled feature requests if you're looking for ways to contribute code. Thanks!

**Comment by XVincentX** [comment]
Makes sense to me. I'll create another one, thanks.
