### ISSUE TITLE
Flutter parenthesis and braces matching

### ISSUE THREAD

**Issue by josejmoran** [microsoft/vscode#123890]
Issue Type: <b>Feature Request</b>

Hi,

It will be great if you match the parenthesis based on the lines you have following the tabs. This long lines kind of tell where the matching parenthesis or ) should be. What happens is that in Flutter when you miss a ) or } is a headache to find the missing partner. Sincee you have this lines following the tabulation it may even be possible you can auto add the missing } or ).

                  },
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

**Comment by egamma** [comment]
Can you please file the issue against the flutter extension to start the discussion https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter.

Also pls give the bracket pair colorizer extension a try https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer it really helps with finding the matching bracket (but I confess, that I have no experience using this extension with Dart)
