### ISSUE TITLE
Terminal can not be opened

### ISSUE THREAD

**Issue by wengzhenyucode** [microsoft/vscode#123849]
When using ctrl +“`” ,The error that the terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\winpty-conin-20396-1-1d74886f463399d-44a6ba0bc730ad2fe95aded095bf6f14') will show
VScode version：1.56.2
platform information：windows10

**Comment by gjsjohnmurray** [comment]
@wengzhenyucode please add version and platform information from Help,/About

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

/label "needs more info" integrated-terminal
