### ISSUE TITLE
Breakpoints become unbound when start debugging - vscode 1.56.0

### ISSUE THREAD

**Issue by penny-peng88** [microsoft/vscode#123842]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Start debugging (The breakpoints all are bounded)
2. Once the scripts are executing, all the breakpoints became to unbound status.
3. Have tried with below ways to try to resolve this:
  a. set     "debug.javascript.usePreview":  as false;
  b. add "--preserve-symlinks" under "runtimeArgs";
  c. add  "sourceMaps": true,
  d: add "resolveSourceMapLocations": null
  e: remove outFiles 
  f: add sourceRoot path in tsconfig.json
4. here is the log file when set trace: true
[vscode-debugadapter-9f25fd1e.json.gz](https://github.com/microsoft/vscode/files/6476151/vscode-debugadapter-9f25fd1e.json.gz)
5. Installed extension: Cucumber (Gherkin) Full Support v2.15.1
 
Here is my current Launch.json file:
 {
            "type": "pwa-node",
            "request": "launch",
            "name": "npm launch app",
            "runtimeExecutable": "npm",
            "cwd": "${workspaceFolder}",
            "runtimeArgs": [
                "run-script",
                "penny:test"
            ],
            "trace": true,
            "skipFiles": [
                "<node_internals>/**"
            ],
            "console": "integratedTerminal",
            "sourceMaps": true,
            "program": "${workspaceFolder}/script-config/pennytest/cart-chrome.ts",
            "resolveSourceMapLocations": null
        }

i really need help, thanks!

**Comment by connor4312** [comment]
It looks like your `penny:test` scripts runs `cucumber-selenium`. This is a Java process that we can't debug. Then I'm assuming that cucumber-selenium runs the script, but it does so in a way that we don't automatically get debugging for. I suggest opening an issue on the Cucumber team to see how to make this work.

**Comment by penny-peng88** [comment]
> It looks like your `penny:test` scripts runs `cucumber-selenium`. This is a Java process that we can't debug. Then I'm assuming that cucumber-selenium runs the script, but it does so in a way that we don't automatically get debugging for. I suggest opening an issue on the Cucumber team to see how to make this work.

@connor4312  Thanks for your reply, yes, you are right, cucumber-selenium is one custom command to run one ts file, whole project is to run the feature file which is implement by typescript, the problem is , before i upgrade the vs code, i can debug the ts file as expect, after upgrade, it fail to work, even i downgrade to lower version of vs code, still fail, so i ask this question. i don's want to debug the scripts of cucumber-selenium, but i want to debug the typescripts file.

**Comment by connor4312** [comment]
Can you collect a log file using an old version of VS Code? Here's a link to a .zip of the last stable version: https://az764295.vo.msecnd.net/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d/VSCode-win32-x64-1.55.2.zip

**Comment by penny-peng88** [comment]
> Can you collect a log file using an old version of VS Code? Here's a link to a .zip of the last stable version: https://az764295.vo.msecnd.net/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d/VSCode-win32-x64-1.55.2.zip

@connor4312 Thanks, just for double confirmation, i have try with old version of vs code, but still fail on debugging. but if you need this. i will paste the log file.

**Comment by connor4312** [comment]
Okay, thanks for letting me know. Since the old version doesn't work, maybe it's something that changed in cucumber in the meantime. (Also, I haven't made any changes to the debugger that I suspect could cause this.) I recommend opening an issue for them and seeing what they say.
