### ISSUE TITLE
webview - message passing broken since 1.56.0 (extension->content window)

### ISSUE THREAD

**Issue by tintinweb** [microsoft/vscode#123822]
My extension [tintinweb.graphviz-interactive-preview](https://marketplace.visualstudio.com/items?itemName=tintinweb.graphviz-interactive-preview) used to work fine until the 1.56.0 update arrived a couple of days ago. Users started to report an issue with the webview not rendering dot graphs anymore https://github.com/ConsenSys/vscode-solidity-auditor/issues/72. 

The extension renders dot graphs in a webview by loading an `index.html` (set via `webview.html`), waiting for a `webview.postMessage({"command":"renderDot", "value":"<dotgraph>"})`.

Now, this seems to be broken since 1.56.0 for some reason and I was trying to debug it without success. I tried to keep my code very much aligned with the examples but cannot seem to find the issue.

I am using `webview.postMessage()` to send messages to the content window and `webview.onDidReceiveMessage(handler)` to receive msgs from the content window but it looks like messages that I post do not arrive at the content window's `message` eventlistener but instead appear in `webview.onDidReceiveMessage()`. This hasn't happened before 1.56.0 and I assume this may be a breaking change introduced with the latest webview changes.

https://github.com/tintinweb/vscode-interactive-graphviz/blob/master/src/features/interactiveWebview.js#L69

Would be great if someone could verify what's happening here. Either I am somehow misusing the API or this might be a bug that could affect more extensions.

Note: My extension still receives messages from the contentWindow (e.g. save dot file from the menu, initiated from within the  contentWindow), however, the contentWindow does not seem to receive any messages.

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```

This used to work

Steps to Reproduce:

1. get `tintinweb.graphviz-interactive-preview` 
2. open a graphviz dot file and hit cmd + shift + p ->  interactive graphviz preview beside
3. empty window (because content window is not receiving messages from the extension :/ they instead appear in the extensions message handler?! - see "unexpected command" in console (this is the extension not expecting the command that should have been posted to the contentwindow))
4. clicking on the toolbar menu - save dot opens a vscode saveas dialog -> message from contentwindow to extension works fine

![broken_webview2](https://user-images.githubusercontent.com/2865694/118189718-6c22e700-b442-11eb-8690-1ea34526408b.gif)

**Comment by tintinweb** [comment]
quick update: I somehow fixed it. I'll update this comment if I find out what caused the issue.

**Comment by gnmaxim** [comment]
it works now with 0.11

**Comment by jan-dolejsi** [comment]
@tintinweb, you are a genius. I was looking at this the whole week. Same issue - I had too had a convenience function `postMessage`.
