### ISSUE TITLE
shift+enter should bypass markdown cell in Native Notebook

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#123819]
@grapland0 commented on [Wed May 12 2021](https://github.com/microsoft/vscode-jupyter/issues/5866)

When press shift+enter on markdown cell, it should do no-op and skip to the next cell. 

In this way, user can press shift+enter multiple times to execute a series of continuous cells in notebook without manually skip the markdown cells in between with other shortcut keys or mouse.

The current webview vscode jupyter notebook supports this, but the native notebook does not.

**Comment by rebornix** [comment]
This makes good sense.
