### ISSUE TITLE
Native Notebooks - Global status bar items keep moving

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123827]
The items in the global status bar below keep changing positions on me depending on the scenario and it's messing with my muscle memory, I keep clicking the wrong thing. Is there a way to solidify the order of these items? 

Filed a Jupyter extension related issue here: https://github.com/microsoft/vscode-jupyter/issues/5839 

![image](https://user-images.githubusercontent.com/19276747/118194334-0f054200-b3fe-11eb-8f9b-f70fd1014c78.png)

**Comment by rebornix** [comment]
I don't think we support this in status bar.

**Comment by bpasero** [comment]
This can happen when multiple status bar entries have the same `priority` and thus the order of extension activation can matter for how the order ends up being. 

I pushed a change to take the `id` of the status entry into account for the order when priorities are the same. Currently this `id` will be the extension identifier, meaning that if an extension contributes multiple status entries, you could still end up with this issue, though less likely. With https://github.com/microsoft/vscode/issues/74972 (which I plan to finalize this month) it is possible to assign a status entry `id` and `label`.

**Comment by bpasero** [comment]
New insider builds are out that implement https://github.com/microsoft/vscode/issues/123827#issuecomment-842041647. Maybe @claudiaregio you could verify if this is improved?
