### ISSUE TITLE
Allow to paste a file path with line number to go to line in file

### ISSUE THREAD

**Issue by mateja176** [microsoft/vscode#123810]
I often find myself needing to point another developer to a specific line in a file. Usually, I would approach this by sending them a relative file path along with the line number. For example:
- relative file path `src/utils.js`
- line number `30`

Equipped with this information they could:
- copy the file path their clipboard
- raise VSCode
- execute `Go to file` command (usually bound to `ctrl+e`)
- paste 
- press `Enter`
- execute `Go to Line/Column` command (in my case it is bound to `ctrl+g`)
- type in the line number

Instead it would be convenient if the `Go to file` command input could accept a path with a symbol simplifying the above steps. Alternatively, to avoid overloading `Go to file` a new command my be introduced, possibly named `Go to line in file`.

The syntax for the enhanced file path could be `filePath:lineNumber`. In the context of the example above: `src/utils.js:30`.

**Comment by mateja176** [comment]
This [comment](https://github.com/microsoft/vscode/issues/123809#issuecomment-842956978) also applies here.

**Comment by bpasero** [comment]
We already support this, no?

**Comment by TylerLeonhardt** [comment]
Yes we already support this:

* Ctrl + P
* utils.js:30

Works
