### ISSUE TITLE
JSON Settings select bug

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#123869]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0 7771be8
- OS Version: Windows 10 20h2

Steps to Reproduce:

It's opens options and select the first option with one click.

![Animation](https://user-images.githubusercontent.com/17777237/118250669-ff8e0380-b4a6-11eb-88f1-1ba6476704e2.gif)

**Comment by roblourens** [comment]
I can repro. @sbatten what do I do to keep the context menu from showing up directly under the cursor?

**Comment by sbatten** [comment]
@roblourens you can specify the anchor and layout to the context menu service. If you pass the entire pencil element as the anchor, I think there should be no issue. If you wouldn't mind pointing me to the code where this is created, I would like to see what the current args are to see why this is happening.

**Comment by roblourens** [comment]
We pass x/y coords. But if I change it to get the HTMLElement, I have the same problem.

The code is here
https://github.com/microsoft/vscode/blob/85ed0a54d1259e0f65e4a9b79bbe554a6d105214/src/vs/workbench/contrib/preferences/browser/preferencesRenderers.ts#L825

If I change the anchor line to this, which uses the full element of the pencil codicon button, same issue

```ts
getAnchor: () => e.target.element as HTMLElement,
```

https://user-images.githubusercontent.com/323878/118753858-ae6d6f00-b81a-11eb-8990-a878cccf07bb.mp4

**Comment by sbatten** [comment]
@roblourens passing `y+10` tells the menu service that the mouse is 10 px down so when it has to draw upwards, it avoids that zone which isn't where the mouse actually is. To create that 10px buffer, you can pass `height: 10` as part of the anchor and it will draw with a buffer down. But fyi, the menu service already does this with a 2px buffer.
