### ISSUE TITLE
Having two terminal tabs & closing one of them causes Enter & Delete keys to no longer work

### ISSUE THREAD

**Issue by samuelms1** [microsoft/vscode#123808]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.1 (Universal)
- OS Version: macOS Big Sur Version 11.3.1 (20E241)

Steps to Reproduce:

1. Enable Integrated Tabs -- Code (menu) > Preferences > Settings
    - Terminal > Integrated > Tabs: Enabled
2. Open Two Terminals
3. Terminate one of the terminals
4. Open a new file
5. Hit Enter key
6. Observe Enter key does not work
7. Enter text (e.g. "foobar")
8. Try to use delete key and observe that it also does not work

Work Around

1. Disable Terminal Integrated Tabs
2. Restart Visual Studio Code
3. Issue no longer occurs

https://user-images.githubusercontent.com/8550267/118175286-2687ff00-b3ed-11eb-9ed0-297d05e4bd78.mov

Note:  This is the same issue as this closed one where I left these same details: https://github.com/microsoft/vscode/issues/123630

I opened this b/c I didn't know if OP of the other issue would reopen.

**Comment by gjsjohnmurray** [comment]
/duplicate

Fixed in 1.56.2 which released a few hours ago.

**Comment by samuelms1** [comment]
Thanks @gjsjohnmurray!  This has been driving me crazy.  I'll update and try out the fix.

**Comment by samuelms1** [comment]
Confirmed fixed.  Closing.
