### ISSUE TITLE
Support setting colors in terminal profile setting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123829]
Follow up from https://github.com/microsoft/vscode/issues/121738

**Comment by meganrogge** [comment]
How will these interact w the icon - 

will we support setting a profile's icon to a `ThemeIcon | URI | { light: URI, dark: URI }`?

**Comment by Stirfry70** [comment]
Hi

**Comment by Stirfry70** [comment]
That's what I'm saying

**Comment by Tyriar** [comment]
I think for profiles we'll probably just have `color: 'terminal.ansiRed' | 'terminal.ansiBlack' | ...`

**Comment by Tyriar** [comment]
To support any color we would need to move the below into TerminalView's style tag:

https://github.com/Microsoft/vscode/blob/514d3162bc82bc9bc50c4aba0992f1386ad3d3d4/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1953-L1960
