### ISSUE TITLE
Native Notebooks - Split cell from right click menu broken

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#123843]
- VS Code Version: 1.57.0-insider

**Steps to Reproduce:**

1. Open up notebook 
2. Place cursor inside cell
3. Right click and select split cell 

**Actual Behavior:** 
All contents from the cell get moved into a new one below, and the one above is empty (or) a new cell is being inserted above. Can't really tell the difference

*Split cell in cell toolbar works fine* 
![Split menu item broken](https://user-images.githubusercontent.com/19276747/118213262-6f0ddf80-b422-11eb-84b8-bc58d25b10f1.gif)

**Comment by rebornix** [comment]
Weird, not sure why the focus is changed on right click.

**Comment by roblourens** [comment]
Basically still https://github.com/microsoft/vscode/issues/103926. The focus will be changed for the custom context menu, and then this line 

https://github.com/microsoft/vscode/blob/dd924d774ff66846ce9911286a06f36faee711a1/src/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.ts#L911-L911

makes us not split at the selection. Assuming the actual focusing won't change, I guess the command needs to know that it's being invoked from the editor's context menu, and should act like the editor is focused?

**Comment by roblourens** [comment]
I have a related question @sbatten. If I right click in a cell editor, then dismiss the context menu by pressing esc or clicking somewhere, is there a way to get focus returned to the cell editor?

Related because I'm wondering whether something is keeping track of where focus was before the context menu was shown.

**Comment by sbatten** [comment]
@roblourens https://github.com/microsoft/vscode/blob/7031abadeafec54c8876231e3579c938dee6e1a5/src/vs/platform/contextview/browser/contextMenuHandler.ts#L50
