### ISSUE TITLE
Process explorer does not show twistie

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#123891]
Probably missing list CSS from the renderer process for this.

![image](https://user-images.githubusercontent.com/2193314/118280387-04d85780-b481-11eb-9cf5-7fcc5a01ef61.png)
![image](https://user-images.githubusercontent.com/2193314/118280425-0c97fc00-b481-11eb-856e-c2cafb5f623e.png)

**Comment by jeanp413** [comment]
Created PR #123910 fixing this
