### ISSUE TITLE
Some core output channels show no contents in latest insiders

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#123856]
Issue Type: <b>Bug</b>

OutputChannel does not show any data with newest VS Code Insiders.
Non  data of Extension Channels, and non data in any of the default Channels.

VS Code version: Code - Insiders 1.57.0-insider (7771be8b981d4fff2c6de123dad953517253c395, 2021-05-14T05:13:32.324Z)
OS version: Windows_NT x64 10.0.21376

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor            (24 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.27GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether --crash-reporter-id 1b6c6128-1a6d-47c0-a458-f1bdedd6b964|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
iconify|ant|0.0.9
icons-carbon|ant|0.2.3
parameter-hints|Dom|0.2.7
gitlens|eam|11.4.1
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.11.3
codetogether|gen|4.0.1
vscode-pull-request-github|Git|0.26.0
output-colorizer|IBM|0.1.2
vscode-todo-highlight|jgc|2.0.2
vscode-dotnet-runtime|ms-|1.1.0
vetur|oct|0.33.1
docthis|oou|0.8.2
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.6.0
vscode-commons|red|0.0.6
vscode-standard|sta|1.5.0
svelte-vscode|sve|104.12.2
even-better-toml|tam|0.12.1
vscodeintellicode-insiders|Vis|1.0.6
vscode-conventional-commits|viv|1.21.0
windicss-intellisense|voo|0.13.1
vscode-wakatime|Wak|8.0.0
footsteps|Wat|0.1.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by egamma** [comment]
Issue confirmed the following output channels are empty and are not empty in stable:
- Log (shared)
- Log (Main)

**Comment by alexanderniebuhr** [comment]
Additional most 3rd Party extension show no content in with newest VS Code Insiders.
Do not tell me that it is an issue of the 3rd Party extension, it is not since they work in VS Code stable.
This is also proven by the fact that some shipped OutputChannels are broken.

**Comment by bpasero** [comment]
I would think this is possibly a regression from the `spdylog` update?

**Comment by rzhao271** [comment]
It's definitely a regression.
Logging works for the extension host, which uses its own synchronous logger, but logging doesn't seem to work for the other processes, even when I make them use sync loggers (rather than async ones) too.
Adding a `.flush()` line to the `log` function in `spdlogLog.ts` gets the messages to show up for the other processes again. To me, this suggests that we still need to expose a `flushEvery` method that flushes the async loggers every second.

**Comment by rzhao271** [comment]
Some links for reference:
- Original task to update spdlog on vscode side https://github.com/microsoft/vscode/issues/121513
- Original node-spdlog PR https://github.com/microsoft/node-spdlog/pull/11
- Using the new spdlog on vscode side PR https://github.com/microsoft/vscode/pull/123033
- How a `setFlushEvery` method could look https://github.com/microsoft/node-spdlog/pull/11/commits/d1fe50dce9c722ba99c7bf2eee8882b78c943f36

**Comment by deepak1556** [comment]
@rzhao271 please try using `spdlog::details::registry::flush_on` which will flush whenever logs with required level are met on the sink thread. `flush_every` will call the sinks flush method from a worker thread https://github.com/gabime/spdlog/blob/be14e60d9e8be31735dd9d2d132d8a4cd3482165/include/spdlog/details/periodic_worker-inl.h#L29, async `_st` sinks are constructed with null mutex.

**Comment by alexanderniebuhr** [comment]
@rzhao271 quick update, actually your "mitigation" seems not to solve the issue with the latest Insider (the latest build commit is after your commit, by date)
Still not getting all OutputChannels back working.

**Comment by alexanderniebuhr** [comment]
the latest nightly build (version info below) restored OutputChannel behavior.
Seems that the commit a3fe790a45fa5b86fe80ce58a6e7f97b95a97afd was needed, to make it work for the API Usage aswell. 

```
Version: 1.57.0-insider (system setup)
Commit: 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
Date: 2021-05-18T05:14:15.253Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.21382
```

**Comment by rzhao271** [comment]
Thanks for the update! I'll leave this issue open until I can replace those flush calls with the `setFlushOn` API in https://github.com/microsoft/node-spdlog/pull/12.
