### ISSUE TITLE
April 2021 release v1.56 lost the toolbar icon to split terminals - please add back!

### ISSUE THREAD

**Issue by tohagan** [microsoft/vscode#123846]
This release introduced a new terminal view toolbar 
- https://code.visualstudio.com/updates/v1_56#_new-terminal-picker

However this new toolbar moved the feature to split terminal windows so that it now takes 3 clicks to spit a terminal window.   

This will really slow me up as I constantly need to run three terminals side by side to perform Firebase web development so I can watch logged output side by side.  I use this to run the (a) Firebase emulator, (b) Firebase functions Typescript compiler and (c) Vue or React dev server.  I'd expect this would be a common usage scenario for other developers who will likewise be annoyed with this lost feature.  What was once fast and smooth is now slow and clunky. 

## Split terminal toolbar icon removed

OLD Pre v1.56 toolbar 

![image](https://user-images.githubusercontent.com/301525/118225822-25c49b00-b4c9-11eb-8119-e1cf608c08ab.png)

It used to be quick to split the terminal into three side by side terminals - just two taps on on the same toolbar icon. Now it's a slow annoying process to navigate two level into the terminal menu to create the 2 extra split terminals having to carefully re-select the same terminal type on the nested submenu each time.  Please add back the icon to the terminal toolbar to split the currently active terminal type (Bash for me).

![image](https://user-images.githubusercontent.com/301525/118223736-4a1e7880-b4c5-11eb-84a7-4f29c6596b32.png)

## Terminal deletion icon removed

![image](https://user-images.githubusercontent.com/301525/118225892-412fa600-b4c9-11eb-8694-38ac4fbfadc4.png)

It also used to be quicker to delete the current terminal. Granted you can do it but it's now slower to do as you now need to hover over a mini menu on the RHS that only appears once you've created two or more split terminals - weird UI and inconsistent.  The old toolbar buttons were consistent (same behaviour to 1 .. N terminals) and more intuitive IMHO. 

![image](https://user-images.githubusercontent.com/301525/118224282-29a2ee00-b4c6-11eb-8ba3-c3467713dc7d.png)

**Comment by Tyriar** [comment]
This has [come up before](https://github.com/microsoft/vscode/issues/10546#issuecomment-827762979) and we've made a bunch of adjustments to make it easier to split/kill. Here they are, some of them are only in Insiders and some are yet to be implemented:

- You can left or right click the inline tab to get access to its regular context menu (2 clicks to kill/split), the profile switcher is a little more out of the way for splitting but it will let you use non-default terminals
- Alt+click on the plus will split, like in the explorer
- Alt+click on the single tab will split it https://github.com/microsoft/vscode/issues/123888
- Middle click on the single tab will kill it https://github.com/microsoft/vscode/issues/123887
- When the number of terminals go from 2 to 1 and the mouse is within the tabs, they will not hide it until you move the mouse out
- `"terminal.integrated.tabs.hideCondition": "never"` can be used to never hide tabs, even if there is a single terminal. The purpose of this feature it to maintain a lightweight and clean UI when users only have a single terminal. If you use this you may also want to set `"terminal.integrated.tabs.showActiveTerminal": "never"` to hide the inline tab.
- We're keeping the dropdown if you want to use that when we switch the default of `terminal.integrated.tabs.enabled`

So single click to do both will still possible and you can always go back to the old dropdown if you want. I explain the reasoning 
for not wanting to do this [in this comment](https://github.com/microsoft/vscode/issues/10546#issuecomment-827861671):

> Even little things like adding a button or 2 to the panel build up over time (first kill, then split, then clear...).

But I think it's likely in the future we will allow extensions to contribute actions to that area which will give the user ultimate control.

**Comment by tohagan** [comment]
I found that `Alt-click` on "+" icon does not split the terminal (it starts a new Terminal) but apparently `Ctrl-Shift-5` does split the current terminal solves my main concern of speed of use.

**Comment by Tyriar** [comment]
Yes it's new in Insiders, it's also a little easier to discover the split keybinding as it shows up on hover of both the + and the single tab.

**Comment by arjd** [comment]
@Tyriar for those of us who do not have mice that can middle-click but do have a lot of screen real-estate, I would _strongly_ prefer being able to add the trash icon back via a config item.
