### ISSUE TITLE
VSCode is slow since updating to ver. 1.56

### ISSUE THREAD

**Issue by alaadahmed** [microsoft/vscode#123935]
Since updating to version 1.56, it became very slow, fans always loud and spinning. Takes sometime to load any function/class definitions or colors inline tiles (ex: in tailwindcss). I thought at the begining it is one of my extensions, but when I use any other editor it runs fast like usual.

<img width="856" alt="Screen Shot 2021-05-15 at 09 06 46" src="https://user-images.githubusercontent.com/14099508/118351751-03c92800-b55e-11eb-978d-15ffc370fb91.png">

**Comment by babakks** [comment]
I'm too experiencing this on code-insiders 1.57.0.

**Comment by egamma** [comment]
/needsMoreInfo

Please follow this guide and help us to narrow down the performance issue https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by Buzut** [comment]
I can confirm. All git-related features are now painfully slow, especially with GitLens.
* pulling & pushing,
* staging & committing, 
* showing diffs.

**Comment by egamma** [comment]
@Buzut please file a separate issue for this performance problem. Please include information about the platform you are using and ideally help to narrow this problem down using this performance guide https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by JacksonKearl** [comment]
Sorry wrong issue ref.

**Comment by alaadahmed** [comment]
I am sorry I didn't have time to get more information about the issue, although I followed the guide to fill issue using the embedded form from vscode help menu. anyway I found out the issue was in Extension [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss). When I disabled it everything worked fine. I found that extension consume really high cpu and memory and slow down everything.
Here is issue about that extension and the slow down it caused. [#327](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/327)

**Comment by alaadahmed** [comment]
<img width="697" alt="Screen Shot 2021-05-31 at 17 41 16" src="https://user-images.githubusercontent.com/14099508/120216512-69443680-c237-11eb-9110-55f969c4c69f.png">

All of these high consuming running processes belong to code-renderer

**Comment by alaadahmed** [comment]
<img width="847" alt="Screen Shot 2021-05-31 at 18 57 05" src="https://user-images.githubusercontent.com/14099508/120223635-305d8f00-c242-11eb-98b3-e33ee6243d95.png">

<img width="559" alt="Screen Shot 2021-05-31 at 18 57 40" src="https://user-images.githubusercontent.com/14099508/120223656-38b5ca00-c242-11eb-9451-3afacbf62f99.png">

**Comment by Buzut** [comment]
Nothing seemed to be CPU bound. Git operations were specifically slow. I tried with all extensions disabled but no change.
I reverted to version 1.55.2 and it now works perfectly fine.

**Comment by alaadahmed** [comment]
@Buzut How could you revert to a previous version of vscode?

**Comment by carlocardella** [comment]
@alaadahmed, the monthly release notes (https://code.visualstudio.com/updates) allows you to download previous Stable versions. !.55.2 is the latest available from the March release: 

![image](https://user-images.githubusercontent.com/5784415/120391095-6acb3880-c2e3-11eb-96e7-22302fc381f3.png)

**Comment by egamma** [comment]
@alaadahmed still needs some more information, when this problem happens can you please run `code --status` as described in the performance guide and include the output from the command.

**Comment by alaadahmed** [comment]
```
Version:          Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS Version:       Darwin x64 20.5.0
CPUs:             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (0.36GB free)
Load (avg):       2, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id f6e3b91f-041e-4e40-b54f-44ac2bdc7668
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      115   22003  code main
    1       66   22006     gpu-process
    0       16   22008     utility
    0      262   22009     window (form_component.html.leex — ahram_school)
    0      131   22093       extensionHost
    0       49   22102         electron_node server.js 
    0       16   22117         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=22093
    0     1409   22907         electron_node tailwindServer.js 
    0      410   22927         /usr/local/Cellar/erlang/24.0.2/lib/erlang/erts-12.0.2/bin/beam.smp -sbwt none -sbwtdcpu none -sbwtdio none -- -root /usr/local/Cellar/erlang/24.0.2/lib/erlang -progname erl -- -home /Users/alaadahmed -- -pa /usr/local/Cellar/elixir/1.12.1/bin/../lib/eex/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/elixir/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/ex_unit/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/iex/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/logger/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra -e ElixirLS.LanguageServer.CLI.main()
    0        0   22965           erl_child_setup 10496
    0        0   23077             inet_gethost 4
    0        0   23078               inet_gethost 4
    0       49   37446         electron_node tsserver.js 
    0       82   37447         electron_node tsserver.js 
    0       16   37459           electron_node typingsInstaller.js typesMap.js 
    0       33   41739         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=22093
    0       33   22094       watcherService
    0       33   22096       searchService
    0       66   22092     shared-process
    0       33   22095       ptyHost
    0        0   22181         /bin/zsh -l
    0       82   43584           /usr/local/Cellar/erlang/24.0.2/lib/erlang/erts-12.0.2/bin/beam.smp -- -root /usr/local/Cellar/erlang/24.0.2/lib/erlang -progname erl -- -home /Users/alaadahmed -- -pa /usr/local/Cellar/elixir/1.12.1/bin/../lib/eex/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/elixir/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/ex_unit/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/iex/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/logger/ebin /usr/local/Cellar/elixir/1.12.1/bin/../lib/mix/ebin -elixir ansi_enabled true -noshell -user Elixir.IEx.CLI -kernel shell_history enabled -extra --no-halt +iex -S mix phx.server
    0        0   43868         /bin/zsh -l
    0        0   44013           bash /usr/local/bin/code --status
    2       33   44023             electron_node cli.js 

Workspace Stats: 
|  Window (form_component.html.leex — ahram_school)
|    Folder (ahram_school): 8357 files
|      File types: beam(4004) ex(975) yaml(475) po(248) fetch(163) erl(160)
|                  exs(151) jpg(124) app(97) config(94)
|      Conf files: makefile(5) package.json(4) webpack.config.js(1)
```

**Comment by alaadahmed** [comment]
By the way, for last week or so, when I work on __large file__, I always see a `.tmp` file has the same name of the current file I am working on - _appear in the same directory_ -  and I know it belong to `git` for version control and comparison. The issue is every few minutes it asks me  `overwrite` the current file or `compare` first? then I choose overwrite. Many times I find my current file I am working on ALL OF ITS CONTENT DELETED!!!!! and I have to press CTRL+Z to revert it back. Some issues with git.

**Comment by egamma** [comment]
@alaadahmed  thanks for the additional information. From the workspace stats it looks like your developing in both TypeScript and Erlang in this workspace? In the comment https://github.com/microsoft/vscode/issues/123935#issuecomment-851567384 above I see a lot of ruby activity. When does the slow down happen? What files are you then working on.

Please file a separate issue with reproducible steps on the large file issue https://github.com/microsoft/vscode/issues/123935#issuecomment-852824609, can you share the large file? what file type is it? I guess this tmp file is generated by an extension.

**Comment by alaadahmed** [comment]
I am working on Elixir files, (HTML/EEx) and no TypeScript. Maybe TypeScript runs by some extension I don't know. And all of these ruby activities when I check them, all belong to some `code-renderer` process. I confirm this issue is in VSCode itself not in extensions. Even the terminal is really very lagging. I have `fzf` installed on my mac to use it for fuzzy search in my terminal commands history, also I use it inside vscode terminal and I see it is REALLY slow and lagging. 

I have to revert back to VSCode ver. `1.55.2` and it works really smoooooth without any issues and with the same extensions that I have and I stopped auto update till next release of vscode. I am sorry I couldn't give more info because I am on deadline project and I didn't have time to investigate more, but whatever you changed since ver 1.55.2 please remove it.

**Comment by chenjau** [comment]
built from source(main 1.58 32106ee154a2a0cf6a559b15480cd330d5c20f77)
vscode start up slower than old one(1.56 main before release), same problem may be.
![截屏2021-06-07 下午9 52 11](https://user-images.githubusercontent.com/7047842/121029674-615a3880-c7db-11eb-889e-95e09b2b4f68.png)

**Comment by alaadahmed** [comment]
I upgraded to `1.57`. Everything work smooth so far and no performance issues.
