### ISSUE TITLE
VSCode overriding file’s original encoding settings

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12399]
**From Brick George:**

- VSCode Version:
- OS Version: Windows 10

I ran into a bug with some HTML/CSS files I had created in Visual Studio and then opened up to edit in Visual Studio Code. My Jekyll server threw this error:
 
```
[2016-09-21 09:49:59] ERROR Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. @ io_fillbuf - fd:6
        C:/Ruby22/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `eof?'
        C:/Ruby22/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `run'
        C:/Ruby22/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
 
After some digging around, I discovered that VSCode was overriding my file’s original encoding settings (**Unicode UTF-8 without signature**), and changing it to **Unicode UTF-8** with signature. That hidden character does some goofy things with Jekyll/Ruby on Windows. Sometimes it can stop an entire site from building correctly. I had to open the files back up in vanilla VS and use the Advanced Save Options to re-encode the file. That fixed the error message.
 
I doubt very many people are using the combination of VSCode and VS like I was, but it seems like preserving a user’s file settings should be a fairly important consideration for teams that have members on different operating systems. Barring that, VSCode needs a way to manually change the file encoding settings, similar to “Advanced Save Options” in VS. (That menu option might already exist, but I didn’t find it – clicking the “UTF-8” at the bottom of the screen pops the option to “Reopen with encoding” or “Save with encoding,” but doesn’t give me an obvious way to change the encoding.)
 
Thanks! :)

**Comment by bpasero** [comment]
@bgashler1 how is it possible for me to talk to Brick? this makes it very hard to ask questions.

**Comment by bgashler1** [comment]
@bpasero I will private message you his email on Slack (I couldn't find any GitHub profile for him).

**Comment by brickxg** [comment]
@bpasero @bgashler1 Here I am. I have a GitHub account but don't really use it for anything. :)

**Comment by brickxg** [comment]
@bpasero @bgashler1 Blah, sorry for the hassle -- I did the same thing I did Tuesday night and can't reproduce the Ruby error now. It's possible the BOM snuck in from copypasta or some other goofy thing VS did. Also, I just discovered that actually clicking on "Reopen with encoding" or "Save with encoding" gives me the change option I was looking for. (FWIW, it was not immediately apparent that clicking those links would expose additional UI.) Sorry again -- please close the bug and I'll refile if it comes back.

**Comment by bpasero** [comment]
Makes sense 👍
