### ISSUE TITLE
Terminal Toggle Panel button 'Turn Auto Scrolling On' disappears after turning on. 

### ISSUE THREAD

**Issue by ebonat** [microsoft/vscode#123984]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Click on Terminal, click on 'Turn Auto Scrolling On' icon. 
2. I want to turn it off. How?

**Comment by sandy081** [comment]
I do not see it and the action `Turn Auto Scrolling ..`  remains after clicking. Open Developer tools console (use command `Toggle Developer Tools`) and see if there are any errors. Can you please record a video and share it ?
