### ISSUE TITLE
Inline file/folder/update button

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#12397]
I find it frustrating every time I want to create a new file/folder or update the current folder. I must mark the folder I want to create a new file/folder or update. Also, marking causes collapsing of the marked folder. Also the buttons for creating file/folder is so far away.

I'm just wondering why the buttons aren't just beside the folder name?

![screen shot 2016-09-22 at 01 04 45](https://cloud.githubusercontent.com/assets/1324476/18720952/abc0555c-8060-11e6-87ad-5a8e9b8b39fe.jpg)

**Comment by chrmarti** [comment]
These actions are also available from the context menu of the folder.

**Comment by bgashler1** [comment]
@tinganho let us know if the context menu is sufficient here for you.

**Comment by tinganho** [comment]
Yes I think it is
