### ISSUE TITLE
Double click on sash between split panels should evenly size them

### ISSUE THREAD

**Issue by totkeks** [microsoft/vscode#123953]
I use split panels like can be seen in the screenshot.
![image](https://user-images.githubusercontent.com/2941389/118369571-28e08980-b5a4-11eb-8bac-20d130a251f0.png)

I would like to be able to double click the sash between `Terminal` and `Problems` so that both panels are evenly sized - 50%/50% in that case.
The same feature is already available with editor windows when splitting them vertically.

**Comment by sbatten** [comment]
I first implemented this one, but deemed the behavior described in this issue #95994 more valuable. So, hopefully this satisfies your request as well though different.

**Comment by sbatten** [comment]
Yes the difference in behavior is when there are 3 or more panes. The current implementation will only resize the adjacent expanded views (i.e. 2 view panes). My interpretation of your request was to split all visible views evenly.
