### ISSUE TITLE
Closing unsaved file that was modified by another application causes large slowdown and freeze

### ISSUE THREAD

**Issue by pfoof** [microsoft/vscode#123980]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.56.2**
- OS Version: **Linux Mint 20.1 x86_64**

Steps to Reproduce:

Real-life example.
1. Open a small JSON file (3kb is enough).
2. Use for example palette command "Format document".
3. Don't save the file.
4. Modify the same file using another editor.
5. Try closing the unsaved file in VS Code.
6. CPU usage should jump to 100% (single thread).
7. After 10~20 seconds VS Code will unfreeze.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
