### ISSUE TITLE
Bug: VSCode cannot detect `node:` protocol modules

### ISSUE THREAD

**Issue by SiddharthShyniben** [microsoft/vscode#123968]
Does this issue occur when all extensions are disabled?: Yes

Whenever I import a node built-in module using the `"node:"` format I get an error saying that typescript cannot find the module.

- VS Code Version: 1.56.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Create a new JavaScript (nodejs) file.
2. `require` the `"node:fs"` module (or any other `"node:"` module)

**Comment by IllusionMH** [comment]
Node definitions are provided by DefinitelyTyped, however they removed definitions for models with `node:` schema recently.

For more info see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52595
and related https://github.com/microsoft/TypeScript/issues/42764 https://github.com/microsoft/TypeScript/issues/43842

You either should install definitions version that includes necessary module declarations or create file with re-exports similar to removed.

**Comment by mjbvz** [comment]
Thanks @IllusionMH! Yes this is better tracked by the updates TypeScript issues
