### ISSUE TITLE
SQL Language mode incorrectly interprets a backslash as an escape character.

### ISSUE THREAD

**Issue by kavaliro** [Microsoft/vscode#12395]
- VSCode Version: 1.5.2
- OS Version: Any

Steps to Reproduce:

1.  Use a the sequence, `\'` at the end of a string literal.
2.  Observe that code following step 1. is incorrectly colorized until it hits another singlequote.

A code sample:
```
DECLARE @var nvarchar(20);

SET @var = 'C:\this\work\sok';
PRINT @var;
SET @var = 'C:\this\causes\issues\because\of\trailing\backslash\'
PRINT @var;
-- It's valid SQL, but the colorizer is puking on it, as you can see from this line and the previous;
-- the backslash is not a valid escape character in SQL.

```
![screencap](https://cloud.githubusercontent.com/assets/898803/18719883/7b89e3a0-7fe6-11e6-8454-5c4de667a252.jpg)

**Comment by kavaliro** [comment]
Or at least, not inside single-quotes.

**Comment by chrmarti** [comment]
Tracked as #5223
