### ISSUE TITLE
Can't change default terminal

### ISSUE THREAD

**Issue by Sharandeep23** [microsoft/vscode#123946]
Issue Type: <b>Bug</b>

F1 > Terminal: Select Default Profile > PowerShell 
After automatically updating to the latest version, I'm stuck with the git bash shell. Can't change terminal into PowerShell or command prompt. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (3.59GB free)|
|Process Argv|C:\\Users\\Parth\\Desktop\\Ex_Files_Learning_C_Plus_Plus\\Exercise Files\\Chapter 1 --crash-reporter-id e886beaf-43b9-4a95-8c10-9d0940117a17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
vsc-material-theme|Equ|33.2.0
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
latex-workshop|Jam|8.18.0
cpptools|ms-|1.4.0-insiders
material-icon-theme|PKi|4.6.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by lispaw** [comment]
I had the same issue. Had to remove the previous integrated terminal settings.
Although the visual default profile selector does not warn that the setting will be ignored, settings editor has information:
> This setting will currently be ignored if either `#terminal.integrated.shell....#` or `#terminal.integrated.shellArgs....#` are set.

**Comment by zachmmeyer** [comment]
I am having the opposite problem. Mine is stuck on PowerShell and I cannot change it to anything else.

**Comment by Tyriar** [comment]
We currently ignore the default profile if the shell or shellArgs settings are set, this should change soon. To move to the new world, open your settings.json file and remove the deprecated settings.

**Comment by Tyriar** [comment]
This issue tracks the migration: https://github.com/microsoft/vscode/issues/123171

**Comment by Tyriar** [comment]
@zachmmeyer yes the deprecated setting overrides the new profiles to ease migration problems. Things have gotten a lot better in insiders wrt the defaultProfile setting because this monster PR went in https://github.com/microsoft/vscode/pull/123729

**Comment by zachmmeyer** [comment]
Understood.
