### ISSUE TITLE
files.trimTrailingWhitespace not working

### ISSUE THREAD

**Issue by setuun** [Microsoft/vscode#1239]
When i enable this option like so (User Settings):
```
"files.trimTrailingWhitespace": true
```
then it does not delete whitespaces on save.

Here are my user settings:
```
{
	"editor.renderWhitespace": true,
	"files.trimTrailingWhitespace": true
}
```

OS: Windows 10 Pro

**Comment by bpasero** [comment]
@dbaeumer I cannot reproduce, could it be that you had auto-save enabled and you left the cursor on one line? in that case we do not remove trailing whitespace. But we do if auto-save is disabled and you do an explicit save.

**Comment by bpasero** [comment]
Sry, didnt know the bug as from someone else, but assigning for verification.

**Comment by dbaeumer** [comment]
Couldn't reproduce either.
