### ISSUE TITLE
Separator size

### ISSUE THREAD

**Issue by EnriqueVeguer** [microsoft/vscode#123932]
Please allow or explain how to change the width and height of the resize grips of vscode
I'm getting green hair trying to resize the different panels on vscode, I think someone believes having more space is better but I don't know if I'm the only one with this problems has something to do with that I have a 4k monitor, is extremely dificult to find the exact point where the thing will resize even if the pointer changes it will not resize until it becomes blue also but I have to fight like an hour to make the thing turn blue
I've tried modifying the file /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css as I think this can't be done directly in vscode settings but have no idea what to change
Please help me with this
![image](https://user-images.githubusercontent.com/84217786/118348374-6f37d900-b50f-11eb-8456-d1d8d1f3ac0e.png)

**Comment by misolori** [comment]
Take a look at changing `workbench.sash.size` to change the area size. The default is set to 4px.

![image](https://user-images.githubusercontent.com/35271042/118704216-bc47d380-b7cb-11eb-8662-341437ab5c32.png)

![image](https://user-images.githubusercontent.com/35271042/118704250-c23db480-b7cb-11eb-96ee-e785e8075935.png)
