### ISSUE TITLE
Close button is on the right side of the tab on macOS

### ISSUE THREAD

**Issue by carbongo** [microsoft/vscode#123999]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 (Universal)
- OS Version: macOS 11.3.1

Steps to Reproduce:

1. Open VSCode on macOS
2. Hover any tab item (file)

<img width="1092" alt="Screenshot 2021-05-17 at 10 01 44" src="https://user-images.githubusercontent.com/30941586/118420241-568b1700-b6f9-11eb-9488-1aea4a005cae.png">

Here is how should it look like: <img width="686" alt="Screenshot 2021-05-17 at 10 21 01" src="https://user-images.githubusercontent.com/30941586/118420379-acf85580-b6f9-11eb-8cb3-abce2ea17263.png">

**Comment by bpasero** [comment]
Configurable via `workbench.editor.tabCloseButton: right`.
