### ISSUE TITLE
Python debugger stopped working for no apparent reason

### ISSUE THREAD

**Issue by itzsimpl** [microsoft/vscode#123949]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0-insider
- OS Version: MacOS BigSur 11.3.1 and Ubuntu 20.04

Steps to Reproduce:

1. create help.py with line print('help')
2. try to debug code

the end result on my local machine is always
https://user-images.githubusercontent.com/4784070/118363049-d5197480-b592-11eb-9168-58dc0795387f.mov

when connected via Remote SSH to Ubuntu 20.04 the Debugger upon start shows a terminal which says `/bin/bash: : No such file or directory` and crashes in a split second with exit code 127.

I can start the terminal normally, `Run Python File in Terminal` works fine, it is just the debugger that fails to start.
 
I have filed this same issue on https://github.com/microsoft/vscode-python/issues/16250#issue-892295122, as I am unsure what could be causing it. In the meantime I have reinstalled VSCode Insiders, to no avail, removed all data in `.vscode-insiders`, and all VSCode related data in `~/Library/`, and again reinstalled VSCode Insiders, all to no avail. I have tried with various versions of Python, Pylance and Jupiter extensions, all to no avail. 

In VSCode 1.56.2 (Universal), the debugger starts normally.

**Comment by avernan** [comment]
Same issue here on Linux (Arch) with both bash and fish shells.

**Comment by csghone** [comment]
Same here - Remote SSH to Linux(Ubuntu) from Windows.

**Comment by rickstaa** [comment]
This also affects the **vscode-insiders** python debugger on my system @xsghone's workaround solves it for now:

```
Version: 1.57.0-insider
Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e
Date: 2021-05-14T20:14:19.367Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-53-generic
```
### Gif

![bug](https://user-images.githubusercontent.com/17570430/118401874-b2a55b00-b667-11eb-8f54-86ce5e28bfdc.gif)

### How to reproduce

1. Start the following script and observe the error.

```python
print("Hello there!")
```

**Comment by csghone** [comment]
The `''` seems to cause this error.

```
bash -c ''/home/csghone/miniconda3/envs/my_env/bin/python /data/home/csghone/.vscode-server-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/launcher 42475 -- my_script.py ; read -p "Press any key to continue..." -n1;''
```

Seems to originate here:
https://github.com/microsoft/vscode/blob/82767cc1d7bf8cdea0f2897276d5d15aee91f3d9/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L252

**Comment by StewartWong** [comment]
Similar issue in Windows Powershell Core 7.1.3

```bash
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe ''" terminated with exit code: 64.
onDidChangeNotification @ workbench.desktop.main.js:740
```

**Comment by csy19960309** [comment]
> Same here - Remote SSH to Linux(Ubuntu) from Windows.
> 
> ```
> Version: 1.57.0-insider (user setup)
> Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e
> Date: 2021-05-14T20:13:58.234Z (1 day ago)
> Electron: 12.0.7
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Windows_NT x64 10.0.18363
> ```
> 
> Workaround: Use `"console": "internalConsole"` in your debug configuration.

This workaround seems unable to be applied with type being "cppdbg". Moreover, when I set "externalConsole" to true the error notice disappears but I cannot find where the launching console is. It there any other workaround for cpptools?

**Comment by isidorn** [comment]
Closing this as dup of https://github.com/microsoft/vscode/issues/124007 and https://github.com/microsoft/vscode-python/issues/16250#issue-892295122

**Comment by Wakkana** [comment]
> > Same here - Remote SSH to Linux(Ubuntu) from Windows.
> > ```
> > Version: 1.57.0-insider (user setup)
> > Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e
> > Date: 2021-05-14T20:13:58.234Z (1 day ago)
> > Electron: 12.0.7
> > Chrome: 89.0.4389.128
> > Node.js: 14.16.0
> > V8: 8.9.255.25-electron.0
> > OS: Windows_NT x64 10.0.18363
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Workaround: Use `"console": "internalConsole"` in your debug configuration.
> 
> This workaround seems unable to be applied with type being "cppdbg". Moreover, when I set "externalConsole" to true the error notice disappears but I cannot find where the launching console is. It there any other workaround for cpptools?

have you found other workaround that make cpp dbg tools work?
