### ISSUE TITLE
"Welcome" tab is open in the workspace then the "File" menu button does not work correctly.

### ISSUE THREAD

**Issue by rokkky** [microsoft/vscode#123941]
Issue Type: <b>Bug</b>

При открытой в рабочей области вкладки "Приветствие", которая появляется, например, при закрытии папки с проектом, некорректно работает кнопка меню "Файл". При нажатии на нее она открывается на 1 секунду, и после этого сразу сворачивается назад. Пока не будет закрыта вкладка "приветствие", работать корректно она не начинает.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X4 640 Processor (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (4.07GB free)|
|Process Argv|--crash-reporter-id 5716667f-8d8b-458d-9f4b-c205865c8455|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
easy-less|mrc|1.7.2
vscode-language-pack-ru|MS-|1.56.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-multiclip|sle|0.1.5
sass-indented|syl|1.8.16
vscode-icons|vsc|11.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by rokkky** [comment]
If i have a open "welcome" tab on a work zone, which appears if i, to example, close the project directory, i have a incorrect menu buttons work. When i click on button, he's reveal on a 0,5 s, and hide. Its problem of all buttons on top menu. When i close a "welcome" tab, trouble is disappear.

**Comment by SiddharthShyniben** [comment]
This is what google translate says, and it looks correct:
> When the "Welcome" tab is open in the workspace, which appears, for example, when you close a folder with a project, the "File" menu button does not work correctly. When you press it, it opens for 1 second, and then immediately collapses back. Until the "welcome" tab is closed, it does not start working correctly. VS Code version: Code 1.56.2 (054a929, 2021-05-12T17: 13: 13.157Z) OS version: Windows_NT x64 10.0.19042

**Comment by JacksonKearl** [comment]
I haven't been able to reproduce this, I included a git of what happens when I try, could you please share a recording of the behavior you're seeing?
![recording (16)](https://user-images.githubusercontent.com/8586769/118928724-7b011200-b8f8-11eb-9fd3-fb944261595f.gif)

\gifPlease

**Comment by rokkky** [comment]
чт, 20 мая 2021 г. в 09:18, VS Code Issue Triage Bot <
***@***.***>:
