### ISSUE TITLE
Horizontal space is not being used fully by the test message

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#123927]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider
Commit: 40d5e6796fbc32d67dd0009e5b0027003803fd7e
Date: 2021-05-14T21:31:25.085Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0

Steps to Reproduce:

1. Use the new test API and append a markdown string as a test message
2. The horizontal space is not being used fully by the test message

![image](https://user-images.githubusercontent.com/6193897/118236961-4d1b6800-b4c9-11eb-8f46-ccfdf9d9e831.png)

// https://github.com/microsoft/vscode/issues/122208#issuecomment-841070950

**Comment by connor4312** [comment]
@mjbvz this is a bug in the hover itself (testing just uses the default hovers). Notice that the long method name/path increases the size of the hover, but its contents don't grow to fit.

`working-areas.md` says Pine still owns this--is the bot right that you're the new hover person, or is there someone else?

**Comment by mjbvz** [comment]
Maybe @alexdima or @jrieken? Not sure if there is a dedicated owner for hovers at the moment

**Comment by alexdima** [comment]
I'm maintaining the hover but would appreciate a PR / some simpler repro steps maybe with a trivial extension that just registers a hover provider with the same markdown content.

**Comment by jdneo** [comment]
@alexdima You can use this sample project: https://github.com/jdneo/vscode-extension-samples/tree/cs/vscode-issue-123927/test-provider-sample.

1. `npm i`
2. running the sample extension in **VS Code Insider.**
3. Open `test.md`
4. Click the green button for the line `2 + 2 = 5`.
5. After run finished, hover on it.

See below video:

https://user-images.githubusercontent.com/6193897/120576075-c49f4000-c454-11eb-877a-69232b0116cd.mp4

**Comment by alexdima** [comment]
Thank you for the repro. Here is a further reduced repro for an extension that can be placed in the user extensions dir:
* `package.json`:
```json
{
  "name": "123927",
  "publisher": "alex",
  "version": "1.0.0",
  "engines": {
    "vscode": "^1.22.0"
  },
  "activationEvents": [
    "*"
  ],
  "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require("vscode");

exports.activate = function () {
  vscode.languages.registerHoverProvider(
    { scheme: "file" },
    {
      provideHover: () => {
        const markdownString = new vscode.MarkdownString();
        markdownString.appendCodeblock(
          "void org.springframework.samples.petclinic.model.ValidatorTest.shouldNotValidateWhenFirstNameEmpty()",
          "java"
        );
        return new vscode.Hover(markdownString);
      },
    }
  );
  vscode.languages.registerHoverProvider(
    { scheme: "file" },
    {
      provideHover: () => {
        const markdownString = new vscode.MarkdownString();
        markdownString.isTrusted = true;
        markdownString.appendText(
          "this is just a fake lonnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnng [message](https://github.com/microsoft/vscode/issues/123927#issuecomment-853149197)"
        );
        return new vscode.Hover(markdownString);
      },
    }
  );
};
```

![image](https://user-images.githubusercontent.com/5047891/120847938-75e8c780-c574-11eb-8a4f-e222d1c1a13e.png)

**Comment by yash112-lang** [comment]
Hello @alexdima, is this issue is still open, I am new to open source and wanted to contribute.

**Comment by hpnrep6** [comment]
Removing the `max-width: 500px;` styling seems to fix this issue, but is there something I'm missing here?
 
https://github.com/microsoft/vscode/blob/5cb98db286b44e01b792ea3028473007e09f154c/src/vs/base/browser/ui/hover/hover.css#L27-L28

![Screenshot from 2021-07-01 20-59-14](https://user-images.githubusercontent.com/57055412/124205483-4f547880-daaf-11eb-8018-e9507ff07a26.png)

**Comment by connor4312** [comment]
This is a tricky situation for an edge case. I'm leaning towards closing this as *wontfix; I can't figure a way to do this in CSS and manually laying it out with JS will add a deal of complexity and is likely to be error-prone.
