### ISSUE TITLE
Multi cursor deletion not working correctly with cursors on the same line

### ISSUE THREAD

**Issue by Dahamugo** [Microsoft/vscode#12391]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 8.1

Steps to Reproduce:

1. Set multiple cursors in the same line of text
2. Press delete/backspace

For instance, in the line:

`test test`

Setting two cursors, one at the start of each word, and then pressing the delete key will result in:

`est tst`

**Comment by alexandrudima** [comment]
@dmahugh This is not the case for me. Perhaps you have installed an extension that binds the "Delete" or "Backspace" keys?

![multicursor](https://cloud.githubusercontent.com/assets/5047891/18750238/fd567c7a-80e2-11e6-87ed-3078509724eb.gif)

**Comment by alexandrudima** [comment]
@chrmarti Please don't apply bug labels unless we confirm it's a bug

**Comment by Dahamugo** [comment]
It seems like it really was an issue with a specific extension that took me too long to notice (in this case it was [this one](https://marketplace.visualstudio.com/items?itemName=jedmao.tabsanity)).

My bad.
