### ISSUE TITLE
Tab count limit

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#123909]
The new wrap tabs feature is awesome, but I've noticed that I accumulate a large number of tabs, so they limit my editor space. I usually end up just closing all of them and starting over.

It would be great if there was an auto close tab setting that closed your least recently focused/edited one when you create one beyond the tabCountLimit. 

For example, if tabCountLimit = 5, on the 6th file that I open, the least recently interacted w tab would be closed.

**Comment by jeanp413** [comment]
I think what you want are these settings: 
`"workbench.editor.limit.enabled"` , `"workbench.editor.limit.perEditorGroup"` and `"workbench.editor.limit.value"`

**Comment by meganrogge** [comment]
Thanks! @jeanp413
