### ISSUE TITLE
Increase the default size for vertical terminals

### ISSUE THREAD

**Issue by MartinGC94** [microsoft/vscode#123976]
If you open up VS code and move the terminal to the left or right you get a ridiculously small terminal that you will almost certainly want to make wider. Can the default size be increased? Or can we get an option to set the default size?

This is the default size today:
![image](https://user-images.githubusercontent.com/42123497/118399796-2858f900-b65f-11eb-9f67-8a62cfb612f6.png)
This is a much more reasonable size:
![image](https://user-images.githubusercontent.com/42123497/118399894-a0272380-b65f-11eb-9490-3dcb62beca66.png)

**Comment by meganrogge** [comment]
We decided to go with this narrow of a width by default for tabs in the vertical orientation bc of the limited width based on feedback. 

You'll notice in insider's that whatever width you set will be remembered, no need to change the default.

**Comment by MartinGC94** [comment]
@meganrogge Sorry if I was unclear, but I wasn't talking about the tabs, I was talking about the whole terminal window.  
In the first screenshot there's barely room for any output and I can't imagine anyone moving the terminal to the left/right wants such a narrow window.

The terminal window size is remembered across sessions but if you close VS code with it in any other position it will be reset to the default narrow size when you try to use it again.

**Comment by sbatten** [comment]
I have kept the default size, but have fixed the issue where it is not remembered properly.
