### ISSUE TITLE
Plan to migrate extensions (python!) off of shell and shellArgs terminal settings

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#123930]

**Comment by Tyriar** [comment]
I recommended the Python extension do this https://github.com/microsoft/vscode/issues/121760#issuecomment-840058875

> I suggest once the recovery build ships (tomorrow?), in the Python extension check if the user has set defaultProfile but not shell or shellArgs and warn them that the default profile won't be used in this case. Since #123174 will be in the recovery build, that should catch all the bad cases

This can remain until the shell/shellArgs are lower priority to profiles. Tracking that in https://github.com/microsoft/vscode/issues/123171, fyi @karrtikr I'd recommend subscribing to that issue

**Comment by Tyriar** [comment]
Python issue https://github.com/microsoft/vscode-python/issues/16175

**Comment by karrtikr** [comment]
> in the Python extension check if the user has set defaultProfile but not shell or shellArgs and warn them that the default profile won't be used in this case

Are you suggesting that we show a warning prompt?

**Comment by Tyriar** [comment]
@karrtikr yes if you think people will get confused otherwise, optional though.
