### ISSUE TITLE
Terminal font height and width spacing

### ISSUE THREAD

**Issue by dbytes** [microsoft/vscode#123901]
Issue Type: <b>Bug</b>

The terminal font height and width spacing is too tall and too wide.   If I change the value of the the terminal height or letter spacing in settings, the terminal instantly corrects itself until the next reload/restart of VSCode.  Reverting of the changes also retains the proper spacing until the next reload.

**Before changes or after a restart**
![image](https://user-images.githubusercontent.com/33239764/118290665-25a1ac80-b483-11eb-8f93-24d616e2a108.png)

**After changing height or letter spacing**
![image](https://user-images.githubusercontent.com/33239764/118290684-2afef700-b483-11eb-93ba-43ec82b9fe55.png)

The editor always has proper spacing.

This is on multiple machines after an update a month or so ago.  Tried different fonts and also with extensions disabled.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.16GB free)|
|Process Argv|--crash-reporter-id 566c3bfd-dba6-44d3-8313-c61956d39688|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.25.0
vscode-custom-css|be5|5.0.3
hungry-delete|jas|1.6.0
powershell|ms-|2021.2.2
reload|nat|0.0.6
indent-rainbow|ode|7.5.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.2.6
vscode-icons|vsc|11.4.0
better-align|wwm|1.1.6
material-theme|zhu|3.10.14

</details>

**Comment by Tyriar** [comment]
The proper fix for this is tracked in https://github.com/xtermjs/xterm.js/issues/2409
