### ISSUE TITLE
MiniMap only shows visible region on hover

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#123929]
Issue Type: <b>Bug</b>

If I hover mouse over minimap, it hilights the visible region.

However, when mouse leaves minimap, this hilight disappears.

There's no benefit to this. The visible region should ALWAYS be hilighted. Why would anyone _ever_ want NOT to see where they are in the file?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 208511c2-dba0-4576-b4d0-606dd0e49428|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.2.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
php-debug|fel|1.15.1
go|gol|0.25.0
lldb-vscode|lan|0.2.3
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.2
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
terraform-advanced-syntax-highlighting|pjm|1.4.0
java|red|0.79.1
vscode-yaml|red|0.19.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.3
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
debug|web|0.25.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by p-i-** [comment]
![Screenshot 2021-05-15 at 11 08 40](https://user-images.githubusercontent.com/693495/118347487-ee5bfa00-b56d-11eb-9648-65c44dbd311d.png)
![Screenshot 2021-05-15 at 11 08 26](https://user-images.githubusercontent.com/693495/118347488-f0be5400-b56d-11eb-80ec-bbc87fca36ec.png)

**Comment by p-i-** [comment]
Those 2 images show mouse-outside-minimap and mouse-inside-minimap

**Comment by gjsjohnmurray** [comment]
Please try setting `"editor.minimap.showSlider": "always"`
