### ISSUE TITLE
Option to not substitute anything in arg of run configurations.

### ISSUE THREAD

**Issue by miselico** [microsoft/vscode#123967]
In a launch configuration in launch.json, one can specify args. These arguments have variable substitution, and escaping before they are passed to the actual command. The issue is that in some cases one wants the exact content of the argument be passed. (Specifically, I want the '<' symbol as part of an argument to be untouched).

I was trying to achieve this by quoting the argument itself in the configuration like this `"'value_including<=*$&'"`, but this only led to the quotes being escaped themselves in on the command line.

I am running VSCode 1.56.2-1620838498 on Ubuntu Linux / bash, I am working with Python at the moment, but I think it applies more generally.

**Comment by miselico** [comment]
A potential solution which would not disrupt existing configurations could be something like this:

From
```json
"args": ["--option", "value_including<=*$&", "--option2"]
```
which currently gets passed as:
`--option value_including<=*\$& --option2` and fails with `bash: =*$: No such file or directory` `--option2: command not found`

To
```json
"args": ["--option", {"value": "value_including<=*$&", "substitute" : False}, "--option2"]
```

These arguments would then be passed as: `--option 'value_including<=*\$&' --option2` (note the quoted argument)

**Comment by isidorn** [comment]
If I am not mistaken we do not actually touch the `args` on the vscode side, this is handled by the debug extension, in your case python. So it might be best to file this against python
However I know @weinand was looking into args thus I am first forwarding to him as he might know more

**Comment by weinand** [comment]
VS Code tries to protect all characters used in `args` so that they arrive unmodified in the target program.
"Protecting" characters means that specific characters are escaped for the specific command line shell being used.

**Comment by weinand** [comment]
In July we've released has a [new feature](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_70.md#javascript-debugging) that helps debug extension authors to solve the problem. In the July release only VS Code's built-in JS debugger has adopted the new feature, but I expect Python to follow soon.
