### ISSUE TITLE
Need system installer for Coding Pack for Java

### ISSUE THREAD

**Issue by Magendanz** [microsoft/vscode#123923]
CS teachers wanting to migrate from Eclipse to VS Code as our preferred IDE are running into trouble deploying to our lab PCs because the Coding Pack for Java is a per-user install.  You already offer a system installer for the standalone VS Code setup, but could you make a similar variant available for the Coding Pack for Java?

**Comment by egamma** [comment]
The Coding Pack for Java is done by the Java extension team, please file this enhancement request against the Java extension https://github.com/microsoft/vscode-java-pack/issues/new/choose.
