### ISSUE TITLE
key binding with shortcut Ctrl+Alt+(xyz) doesn't work. Even you can't edit any key binding to Ctrl+Alt+xyz 

### ISSUE THREAD

**Issue by apoorvjaiswal** [microsoft/vscode#123952]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
<img width="748" alt="Screenshot 2021-05-15 203010" src="https://user-images.githubusercontent.com/55631115/118365957-6224f380-b5bc-11eb-8c1c-2ba21d4cd427.png">

2.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, and whether the problem still occurs if you run with all extensions disabled

Also see https://github.com/microsoft/vscode/wiki/Keybinding-Issues
