### ISSUE TITLE
Settings for default properties for tasks

### ISSUE THREAD

**Issue by denishowew** [microsoft/vscode#123974]
All my tasks have `"type": "shell"` and `"presentation": "clear"` and `"problemMatcher": []`.  I hate duplication, I'd like to be able to configure these, and other task properties, in settings as the defaults for all tasks, present and future.  Why isn't `presentation: clear` the default anyway - who wants to see old compilation errors, etc?

**Comment by alexr00** [comment]
For the problem matcher, you can use the setting `task.problemMatchers.neverPrompt`

**Comment by idanpa** [comment]
This is possible by setting properties outside of the tasks themselves:
```
{
    "version": "2.0.0",
    "problemMatcher": [],
    "options": {
        "shell": { "args": ["-l",] }, // so .bashrc will be called
    },
    "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": false,
        "panel": "shared",
    },
    "echoCommand": true,
    "type": "shell",
    "tasks": [
        {
            "label": "build all",
            "command": "build.sh",
        },
        {
            "label": "build other",
            "command": "build_other.sh",
        },
        ...
     ]
```
