### ISSUE TITLE
showInputBox: Default value not returned on ENTER

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#12392]
- VSCode Version: 1.5.2
- OS Version: Windows 10

**Steps to Reproduce:**
1. Create an extension with the following code.
```
        vscode.window.showInputBox({ value: "A default value", prompt: "Provide some information", placeHolder: "", password: false }).then((info) => {
            if (info !== undefined && info.length > 0) {
                vscode.window.setStatusBarMessage(info);
            } else {
                vscode.window.setStatusBarMessage("no value provided");
            }
        });
```
2. Invoke the command but do not change the value from the default (you want to take the default value).
3. Press ENTER.

**Result:** "no value provided" is displayed in status status bar.  In the debugger, the value of info is "".
**Expected:** "A default value" is displayed in the status bar.

I get the Expected result on VS Code 1.4.0.

If you update the value but keep it the same (e.g., delete the last 'e' and then re-type the 'e', then press ENTER), "A default value" is displayed in the status bar.  If you change the value to any other value, that other value is displayed as expected.

Perhaps related to #12246?

**Comment by jrieken** [comment]
dup of #11503
