### ISSUE TITLE
clicking explorer item on Side bar does not open the file in editor

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#123931]
Issue Type: <b>Bug</b>

reload the vscode with extensions disabled.

make sure the sidebar shows on right

open explorer window in sidebar.

double click item on explorer

REPRO: file does not launch in the editor.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by rbadapanda** [comment]
I cannot repro this on vscode insiders.

**Comment by isidorn** [comment]
Then closing as this seems to be fixed
