### ISSUE TITLE
SQL Language mode incorrectly interprets a hashtag as the beginning of a comment.

### ISSUE THREAD

**Issue by kavaliro** [Microsoft/vscode#12396]
- VSCode Version: 1.5.2
- OS Version: any

Steps to Reproduce:
1. Use a hashtag on a line.
2. Observe that everthing beyond the hashtag is colorized as a comment.

Example code:

```

--This is a comment in SQL.
/*
This, too, is a SQL comment.
*/
CREATE TABLE #temptable(sometextfield nvarchar(20))
INSERT INTO #temptable(sometextfield)VALUES('This is incorrectly colorized')
SELECT * FROM #temptable
```

![hashtag_comment_error](https://cloud.githubusercontent.com/assets/898803/18720915/2d5327d2-7feb-11e6-8784-74f9ce60a425.jpg)

**Comment by aeschli** [comment]
duplicate of https://github.com/textmate/sql.tmbundle/issues/20
