### ISSUE TITLE
Symbols missing in XML PropertyList "Outline" tree 

### ISSUE THREAD

**Issue by 4086606** [microsoft/vscode#123991]
PropertyList (`plist`) is super annoying to nagivate without an outline, let alone edit and read. This makes editing tmlanguage a complete pain. Please add outline symbol support like JSON or Yaml.

The value of each `key` tag is the symbol label. Member types can be `dict` and `array` container tag or `string` value tag.

There are open-source converters between PLIST and JSON. The only challenge is mapping symbols to a line.

**Comment by aeschli** [comment]
VSCode ships only with very basic XML support. Richer features have to come from an XML extension.
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml is the most popular out there, but doesn't support outlining.
Can you file an feature request against the extension?
