### ISSUE TITLE
Clicking Execute Cell button does not set focus to notebook editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#123990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.57.0-insider (user setup) 40d5e6796fbc32d67dd0009e5b0027003803fd7e
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open two notebooks side by side
2. Set focus to the rightmost notebook
3. Click any 'Execute Cell' button in the leftmost notebook
4. Focus remains on the rightmost notebook instead of switching to the leftmost notebook
5. Run action buttons in the cell toolbar (e.g. Jupyter extension's run above/below buttons) have the same issue

**Comment by rebornix** [comment]
@joyceerhl this is as designed, in VS Code, actions/menus won't change focus.
