### ISSUE TITLE
Explore integration of release notes and extension changelogs

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#123906]
It'd be cool to have our release notes and ext change logs on the new welcome page, but how would it look?

cc @misolori

**Comment by misolori** [comment]
This is just a quick idea, but what if we used the space below getting started and made the getting started tiles scollable?

![image](https://user-images.githubusercontent.com/35271042/118700804-e39ca180-b7c7-11eb-894a-22d8a56a7179.png)

**Comment by jahan01** [comment]
thanks for this, it can reduce notification noise. Just a feedback though - I rarely get to see Welcome page of vscode. When I open the application there is usually a workspace loaded with a file. And I switch between workspaces from there, that leaves me no chance to see Welcome page.

Also would be nice to have timestamp, read/unread indicator and way to dismiss the updates/changelog.
