### ISSUE TITLE
Make the refactor functionality refactor all instances of the same code

### ISSUE THREAD

**Issue by SiddharthShyniben** [microsoft/vscode#123947]
It would be nice if the refactor command refactored all instances of the same code. For example, If have the following code:

```js
const someArray = [];
const otherArray = [];
const condition;

if (condition) {
	someArray.push(condition ? 0 : 1);
} else {
	otherArray.push(condition ? 0 : 1);
}
```

If I select the second `otherCondition ? 0 : 1` block and refactor it to a function (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>r</kbd>), both instances of the code don't get refactored, and I get (something similar to) this: 

```js
const someArray = [];
const otherArray = [];
const condition;

if (condition) {
	someArray.push(condition ? 0 : 1);
} else {
	otherArray.push(newFunction());
}

function newFunction() {
	return condition ? 0 : 1;
}

```

The first bit stays the same. Fixing this could be great!

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
