### ISSUE TITLE
Decrease performance after update

### ISSUE THREAD

**Issue by celia3511** [microsoft/vscode#123902]
Issue Type: <b>Performance Issue</b>

After updating the vscode freezes and consumme to much memory

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.95GB free)|
|Process Argv|--crash-reporter-id ae0495da-74e0-4705-8419-15d9144028a2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	 16716	code main
    5	    82	   132	   shared-process
    0	    60	  4268	     ptyHost
    0	     7	  1544	       console-window-host (Windows internal process)
    0	     6	  5460	       "C:\Program Files\Git\bin\bash.exe" --login
    0	    11	 17156	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login
    0	     7	  9564	       console-window-host (Windows internal process)
    0	     6	 10812	       "C:\Program Files\Git\bin\bash.exe" --login
    0	    10	 15456	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login
    0	     7	 13008	       console-window-host (Windows internal process)
    0	     6	 14712	       "C:\Program Files\Git\bin\bash.exe" --login
    0	    10	 16784	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login
    1	   259	  4612	   window (ActionForm.tsx - portal-socios - Visual Studio Code)
    0	    68	  1936	     searchService
    0	   332	  5412	     extensionHost
    0	   337	  2108	       electron_node tsserver.js 
    0	    74	 13652	         electron_node typingsInstaller.js typesMap.js 
    0	    71	  2980	       "C:\Users\cguer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\cguer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5412
    0	   101	  3080	       electron_node tsserver.js 
    0	   188	 10616	       php.exe c:\Users\cguer\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:55163 --memory-limit=4095M
    0	    11	  4124	         console-window-host (Windows internal process)
    0	    71	 16040	       electron_node eslintServer.js 
    0	    15	  6104	     watcherService 
    0	    11	 19124	       console-window-host (Windows internal process)
    0	    24	  9520	   crashpad-handler
    0	   293	 13936	   gpu-process
    0	   156	 14716	   window (Welcome - api-tolber - Visual Studio Code)
    0	    14	  2500	     watcherService 
    0	    10	  2764	       console-window-host (Windows internal process)
    0	    62	 15032	     searchService
    0	   238	 16484	     extensionHost
    0	   632	 19204	       php.exe c:\Users\cguer\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:55098 --memory-limit=4095M
    0	    10	  1872	         console-window-host (Windows internal process)
    1	    82	 18040	   window (Issue Reporter)
    0	    39	 18616	   utility
```
</details>
<details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
codeigniter-extension|als|0.0.5
ci-snippets2|Ani|1.0.1
All-Autocomplete|Ati|0.0.23
vscode-intelephense-client|bme|1.7.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
macros|ctf|0.0.4
vscode-eslint|dba|2.1.20
git-extension-pack|don|0.1.3
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
sort-lines-by-selection|ear|1.0.0
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.4
fire-snippets|Gan|0.0.5
html-slim-scss-css-class-completion|gen|1.7.8
todo-tree|Gru|0.0.213
svgeditor|hen|2.9.0
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.53
monkey-patch|ioc|0.1.13
path-autocomplete|ion|1.17.1
vscode-essentials|jab|1.5.0
vscode-text-pastry|jkj|1.2.0
svg|joc|1.4.6
vscode-peacock|joh|3.9.1
better-line-select|kai|1.1.1
sftp|lix|1.12.9
vsls-whiteboard|los|0.0.12
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vsliveshare|ms-|1.0.4272
debugger-for-chrome|msj|4.12.12
gremlins|nho|0.26.0
material-icon-theme|PKi|4.6.0
polacode|pnp|0.3.4
vscode-yaml|red|0.19.0
explorer-exclude-vscode-extension|Red|1.2.0
ci-snippets|sec|0.0.2
myci-extension|Set|0.0.3
svg-preview|Sim|2.8.3
vscode-multiclip|sle|0.1.5
php-ci|sma|0.4.2
rewrap|stk|1.14.0
control-snippets|svi|1.9.1
sass-indented|syl|1.8.16
lorem-ipsum|Tyr|1.2.0
CodeIgniter-extension-pack|wal|0.0.1
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscorehov:30301222
vscod805cf:30301675

```

</details>

**Comment by egamma** [comment]
/needsMoreInfo pls follow this guide to help us track down a performance issue https://github.com/microsoft/vscode/wiki/Performance-Issues
