### ISSUE TITLE
Make intellisense recognize index.jsx

### ISSUE THREAD

**Issue by marialovesbeans** [microsoft/vscode#123998]
does anyone know how to make VSCode to intellisense 
```javascript
import Home from 'components/home'
```

where `Home`'s full path is 
```javascript
components/home/index.jsx
```

It seems VSCode intellisense only recognizes `index.js` and NOT `index.jsx`. How can I make it recognize `.jsx` as well? Thanks!

**Comment by IllusionMH** [comment]
This is node specific resolution.
You might need to create `jsconfig.json` and set `"moduleResolution": "node"` in `compilerOptions` section.
For details see https://code.visualstudio.com/docs/nodejs/working-with-javascript and https://www.typescriptlang.org/tsconfig#moduleResolution
