### ISSUE TITLE
Dealing with undefined in workspace.getConfiguration(...).get(...)

### ISSUE THREAD

**Issue by cyberbiont** [microsoft/vscode#123957]
I don't see any comfortable way of building my extension configuration in Typescript.
The problem is, I am supposed to provide a default for my option in package.json (contributes.configuration.properties.<propertyname>.default)
But the `workspace.getConfiguration(...).get(...)` function, which is used to retrieve the configuration value, seems oblivious to the default value (whether I had provided it or not) and inevitably adds `undefined` to the value type, which forces me either to use
a) type assertion, that is no good because I may actually forget to provide default in package.json and won't be notified in that case
b) provide default value in configuration file itself, something like 
`const value = workspace.getConfiguration(...).get('value') || defaultValue`

In the latter case, the problem arises, if the value for example is an array. If I add `"type": "array"` in package.json for my option (not setting the default) `workspace.getConfiguration(...).get(...)` returns empty array instead of `undefined`!
Therefore, it evaluates to `true` and my default value in the expression above does not apply.
My guess is that for consistent behaviour `getConfiguration(...).get()` should return `undefined` always if user haven't set the option in settings.json and default is not specified in package.json. 

I'm really at a loss here about how I am supposed to deal with this situation for now, other than setting the defaults twice:  in package.json AND configuration file code.

**Comment by sandy081** [comment]
I understand your point. This is because we derive default value for some types if not specified

```ts
case 'boolean':
	return false;
case 'integer':
case 'number':
	return 0;
case 'string':
	return '';
case 'array':
	return [];
case 'object':
	return {};
default:
	return null;
```

I would recommend checking for value is always good because it protects when user provides invalid values which also include null.
