### ISSUE TITLE
Problem in indent guidelines

### ISSUE THREAD

**Issue by msudgh** [Microsoft/vscode#12398]
- VSCode Version: 1.5.1
- OS Version: Ubuntu Gnome 16.04.1

Additional guidelines after `include scripts`

![screenshot from 2016-09-21 20-37-35](https://cloud.githubusercontent.com/assets/11756815/18721142/f9f1a200-803b-11e6-8131-ec24b77216b0.png)

**Comment by alexandrudima** [comment]
Minimal repro:
```jade
		.bla
			label(for)
include script
```

**Comment by Tyriar** [comment]
Still repros:

![image](https://cloud.githubusercontent.com/assets/2193314/18970891/f31f447a-8647-11e6-84f8-7380096bf08c.png)

- VSCode Version: Code - Insiders 1.6.0-insider (0f7880d7a490ba9aee2b053f3f2e46c19423e7e4, 2016-09-29T14:13:08.930Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

**Comment by alexandrudima** [comment]
@Tyriar:

* original issue -- notice the indent guides behind the text:
![image](https://cloud.githubusercontent.com/assets/5047891/19149256/375241a0-8bc1-11e6-9ebe-49bd7ca16edf.png)

* your screenshot contains no indent guides behind the text.

I have created #13288 to track this new broken case you have discovered.
