### ISSUE TITLE
Code using wrong shell profile on relaunch

### ISSUE THREAD

**Issue by crouchcd** [microsoft/vscode#123959]
Issue Type: <b>Bug</b>

Here are my settings for reference:
```json
"terminal.integrated.defaultProfile.osx": "bash",
  "terminal.integrated.profiles.osx": {
    "bash": {
      "path": "bash",
      "args": ["-l"]
    }
  }
```

## Steps to reproduce:
1. Open Code and create a new integrated terminal with the default profile.
2. Without closing the integrated terminal, quit Code.
3. Reopen Code.

## What's expected:
I expect that when I relaunch Code it should use my default profile.

## What I see:
Code uses /bin/sh instead of my default profile /bin/bash.

![Screencapture](https://user-images.githubusercontent.com/19394466/118381015-3a2d9400-b5ac-11eb-93bc-b7540a4c86df.gif)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.44GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 389d2fce-7afa-41fc-9737-4a09016058fc|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by YunHsiao** [comment]
Bumping this. Same issue on windows.
