### ISSUE TITLE
VSCode installer Windows executable contains deprecated PE flags

### ISSUE THREAD

**Issue by vid512** [microsoft/vscode#123972]
Does this issue occur when all extensions are disabled?: irrelevant

- VS Code Version tested: 1.56.0, 1.56.2
- OS Version: irrelevant

The Windows installer executable contains deprecated Portable Executable (PE) flags, which shouldn't be used according to PE format specification. There is no practical problem with this, the installer works fine, because these flags are ignored in practice. It's just that the executable doesn't conform to the standard. 

Steps to Reproduce:

1. Download VSCode windows installer executable (eg. VSCodeUserSetup-x64-1.56.2.exe) from https://code.visualstudio.com/
2. Start visual studio command line environment, or make sure you have dumpbin.exe utility in your path in another way.
3. Execute command: dumpbin /headers VSCodeUserSetup-x64-1.56.2.exe 
4. In its output, under "FILE HEADER VALUES" and "characteristics", you will see following deprecated flags: "Line numbers stripped", "Symbols stripped", and "Bytes reversed". These correspond to IMAGE_FILE_LINE_NUMS_STRIPPED, IMAGE_FILE_LOCAL_SYMS_STRIPPED and IMAGE_FILE_BYTES_REVERSED_LO. All these are deprecated and should be zero, according to https://docs.microsoft.com/en-us/windows/win32/debug/pe-format

This is probably a problem of whatever utility was used to create the installer.

**Comment by vid512** [comment]
Slight correction, "Bytes reversed" means both IMAGE_FILE_BYTES_REVERSED_LO and IMAGE_FILE_BYTES_REVERSED_HI are set.

**Comment by joaomoreno** [comment]
> There is no practical problem with this, the installer works fine, because these flags are ignored in practice. It's just that the executable doesn't conform to the standard.

Closing the issue since there's actually no issue here. It's OK not to conform to the standard.
