### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by Beat-YT** [microsoft/vscode#123992]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.55.1 (user setup)
- OS Version (From Windows Settings) : Windows 10 Home 20H2 19042.928
- OS Version (From VS code) : Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Change you User Folder Name (https://superuser.com/questions/890812/how-to-rename-the-user-folder-in-windows-10)
2. Run VS code

Everytimeyou will launch Visual Studio Code, this error will pop-up

![image](https://user-images.githubusercontent.com/66485277/118408863-6d782d80-b655-11eb-9baa-eba54c8587d9.png)

**Comment by joaomoreno** [comment]
Right. We don't support renaming the user folder, since VS Code is installed in that path. Just uninstall and reinstall VS Code.
