### ISSUE TITLE
Unable to open the database

### ISSUE THREAD

**Issue by gowdhamv** [microsoft/vscode#123900]
Issue Type: <b>Bug</b>

Im using sqlite database, by using the extension i tried to open the table. But i received the error as mentioned below. Kindly do the needful.

ERROR:
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-50-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|15.54GB (0.49GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 3ec12e8f-1c2f-4f96-92c8-4b2ed6fdb79d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.12.0
kite|kit|0.142.0
python|ms-|2021.5.840043038
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
LiveServer|rit|5.6.1
vscode-icons|vsc|11.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflightcf:30299255
vscod805:30301674

```

</details>

**Comment by egamma** [comment]
please file the issue against vscode-sqlite extension

**Comment by gowdhamv** [comment]
> please file the issue against vscode-sqlite extension

The extension worked before 2 days. Suddenly It shows the error. I haven't updated vscode or the extension.
