### ISSUE TITLE
You don't have an extension for debugging AutoLISP.

### ISSUE THREAD

**Issue by serhanbakir** [microsoft/vscode#123973]
Issue Type: <b>Bug</b>

Updated VSCode to 1.56.2 from 1.55.2 and AutoLISP extension stopped working. Now I cannot attach to AutoCAD 2021 and debug autolisp code. 
An error message states: "You don't have an extension for debugging AutoLISP" Should we find a AutoLISP extension in the market place? 
However extension is already installed and previous version 1.55.2, was working before update. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (49.17GB free)|
|Process Argv|--open-url --crash-reporter-id 4a117aef-66c6-475a-be97-0d7c883b40a0 -- vscode://autodesk.autolispext/?pid=18940|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
autolispext|Aut|1.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123881#issuecomment-842134812

**Comment by Sen-real** [comment]
@serhanbakir 
Please follow the steps in the comments here to work around it for now:
https://github.com/Autodesk-AutoCAD/AutoLispExt/issues/143
