### ISSUE TITLE
problem running nodejs on my terminal

### ISSUE THREAD

**Issue by kizzy162804** [microsoft/vscode#123970]
Issue Type: <b>Bug</b>

i am trying to check if nodejs is installed on my local machine using the VSCode terrrminal. After typing nodejs in the terminal, a ">" is shown which i don't know the meaning.

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:16.954Z)
OS version: Linux x64 5.4.0-73-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) 3805U @ 1.90GHz (2 x 1895)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|1.84GB (0.14GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 3fa7b4ae-a6fa-4389-a87d-4e89f580b54f|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Coderslang|Agi|0.3.9
prettier-vscode|esb|6.4.0
LiveServer|rit|5.6.1
code-autocomplete|svi|1.2.1
tabnine-vscode|Tab|3.4.4
vim|vsc|1.20.2
emmet-live|yse|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
bridgeflight:30302069
vscod805:30301674

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Running `node` puts you in a node repl where > is the prompt. Ctrl+C twice will let you exit.
