### ISSUE TITLE
Cannot split local terminal with docker terminal

### ISSUE THREAD

**Issue by applemonkey496** [microsoft/vscode#123926]
## Does this issue occur when all extensions are disabled?
N/A because this can't be reproduced without the Remote-Containers extension.
I understand that "Issues caused by an extension need to be reported directly to the extension publisher," but this isn't actually an issue with the extension, it's an issue with the vscode integrated terminal. 

## Specs
- VS Code Version: 1.56.2
- OS Version: Ubuntu 20.04 (x64, kernel 5.8.0)

## Steps to Reproduce
1. Open your workspace in a Docker container using a `devcontainer.json` file.
2. In the command palette, run `Terminal: Create New Integrated Terminal (Local)`
3. In the terminal click on the split icon. You will see an error message saying that your local home folder doesn't exist on the Docker container.

This error should occur so long as the user running vscode does not exist in the Docker container.

**Comment by applemonkey496** [comment]
Any update on this? 
Ping @Tyriar

**Comment by Tyriar** [comment]
I can't repro in Insiders, mac should work the same as Linux. This might have been fixed by something else?

![recording (6)](https://user-images.githubusercontent.com/2193314/120698008-4dbd7380-c463-11eb-874b-31b0082f8225.gif)

**Comment by applemonkey496** [comment]
I am able to reproduce the error. Here is a gif:
![Error](https://user-images.githubusercontent.com/55333787/120743642-4079a680-c4ae-11eb-9479-a835f1a511af.gif)

I've blacked out my username but the blacked out part is just `/home/username`.

**Comment by Tyriar** [comment]
Thanks for the gif, can repro. This affects the split command only, splitInstance works which powers the tab split button I was using.

**Comment by applemonkey496** [comment]
> This affects the split command only, splitInstance works which powers the tab split button I was using.

Out of curiosity, what is the difference between split and splitInstance?

Can I work around this issue for the moment by using a different command and triggering splitInstance instead of split?

**Comment by Tyriar** [comment]
@applemonkey496 splitInstance is an internal command that uses the selected terminal tabs in the tab view, it's what drives this context menu:

<img width="313" alt="Screen Shot 2021-06-22 at 5 38 25 AM" src="https://user-images.githubusercontent.com/2193314/122925832-116f8b80-d31c-11eb-9242-c0445e307e35.png">
