### ISSUE TITLE
Exclude files from opening in editor

### ISSUE THREAD

**Issue by bevin0708** [microsoft/vscode#124037]
I have a workspace to build docker images, and I have a few binaries in the workspace. I would like a feature to exclude these binaries (by extension or file pattern) from opening in the editor even when I accidentally click on them.

**Comment by isidorn** [comment]
Currently we only support that you exclude the by `files.exclude`.
However we do not support that we exclude them from not opening. I guess that is a fair feature request and we can leave it open and assign to the backlog.
