### ISSUE TITLE
Go To Definitaion

### ISSUE THREAD

**Issue by chahalrohit** [microsoft/vscode#124013]
Go To Definition not working most of the times in Visual  Studio Code

**Comment by egamma** [comment]
/needsMoreInfo what language are you using when this happens?

**Comment by kevin-peng-hao** [comment]
I'm facing the same issue.
It doesn't work even for c code.
The definitions are actually included in the project.
"Go to definition"/"Peek definition" actual is showing me the "References".

Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by egamma** [comment]
@kevin-peng-hao thanks for your comment, but please file a new issue with reproducible steps against the C++ extension.
