### ISSUE TITLE
Displaying and Editing Formated Text (like .docx or Open XML Document) Support (like how Wordpad or MSWord does)

### ISSUE THREAD

**Issue by Salami-Sam** [microsoft/vscode#124061]
Hi,

I love VSCode. I am a senior in a CS major at a university and also an aspiring novelist. As a writer, I see a lot of potential for VSCode to serve the writing community as the best word processor suite ever made, if only the extension was made to edit .docx or open XML document format. Basically, if it supported displaying and editing formated text. It would be worth it because VSCode has a search function for finding all references of a certain highlighted word throughout the current folder. As a writer, this functionality would be a dream that has never been offered before.

**Comment by roblourens** [comment]
Thanks for the suggestion. This is a very different use-case than what we are going for as a code editor, and it's not really practical for us to do this.
