### ISSUE TITLE
terminal progress "bash "" launch error (exit code: 127)

### ISSUE THREAD

**Issue by IntHelloWorld** [microsoft/vscode#124007]
Issue Type: <b>Bug</b>

I met this problem when I tried to debug python code on a remote linux server after I update my VSCode - Insiders and Remote-SSH.

VS Code version: Code - Insiders 1.57.0-insider (40d5e6796fbc32d67dd0009e5b0027003803fd7e, 2021-05-14T20:13:58.234Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-72-generic
Remote OS version: Linux x64 5.4.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (57.75GB free)|
|Process Argv|--crash-reporter-id 42f834fd-7f6d-44b7-af38-953220adf6b9|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: remoteQYH|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor (64 x 2193)|
|Memory (System)|251.64GB (246.02GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: remoteQYH|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor (64 x 2194)|
|Memory (System)|251.64GB (246.02GB free)|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
pythonsnippets|frh|1.0.2
leek-fund|gis|1.9.7
background-cover|man|2.2.5
vscode-language-pack-zh-hans|MS-|1.57.0
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.0
remote-ssh-edit|ms-|0.65.0
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
material-theme|zhu|3.10.14
vscode-django|bat|1.6.0
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
prettier-vscode|esb|6.4.0
pythonsnippets|frh|1.0.2
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.213
debug-visualizer|hed|2.0.6
vscode-power-mode|hoo|2.2.0
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.57.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.841665333
vscode-python-typehint|njq|1.4.1
indent-rainbow|ode|7.5.0
java|red|0.79.1
synthwave-vscode|Rob|0.1.8
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30296409
vscorehov:30301224
vscod805cf:30301675

```

</details>

**Comment by csghone** [comment]
Seems to be same as #123949

**Comment by IntHelloWorld** [comment]
> Seems to be same as #123949
TKS！Using "console": "internalConsole" in the configurations solves this question.

**Comment by csghone** [comment]
@isidorn @IntHelloWorld - can you please reopen this issue.
internalConsole is just a workaround - not a solution.

**Comment by jonfen** [comment]
https://github.com/microsoft/vscode-python/issues/16263

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/124116

**Comment by altosaar** [comment]
Also facing this issue - solved by  using "console": "internalConsole" in the configuration, from #123949
