### ISSUE TITLE
HTML Tage Intellisens not show choices

### ISSUE THREAD

**Issue by AmerShe** [microsoft/vscode#124000]
Issue Type: <b>Bug</b>

when I type any html tage I get copleting suggestions list without but all are hiden and I try to deactivate all extintions but probem still exist 

![image](https://user-images.githubusercontent.com/40256882/118427748-a0163a80-b6d6-11eb-9b1f-054ca766114d.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.87GB (40.52GB free)|
|Process Argv|--crash-reporter-id a5a0223e-ef71-4e74-a712-a9ec191d42a8|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by aeschli** [comment]
Is it just a rendering issue? If you select an entry, does it insert completion text?

**Comment by AmerShe** [comment]
Yes it insert completion text


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AmerShe** [comment]
so there is no suggestion to solve this issue?!

**Comment by jrieken** [comment]
Please try to reproduce this when starting with empty settings, e.g. start from the command line using `--user-data-dir` argument
