### ISSUE TITLE
Variables in `terminal.integrated.profiles.*`

### ISSUE THREAD

**Issue by marhoy** [microsoft/vscode#124052]
It would be nice if I could use variables in `terminal.integrated.profiles.*`. I would like to do something like:

```
    "terminal.integrated.profiles.linux": {
        "tmux": {
            "path": "tmux",
            "args": [
                "new",
                "-A",
                "-s",
                "VSC-${workspaceFolderBasename}"
            ],
        },
    },
```

This would allow me to have one (persistent) tmux-session per VS Code window / project.

**Comment by Tyriar** [comment]
This should already work, it's fine for me on [Insiders](https://code.visualstudio.com/insiders) anyway. This:

```
"terminal.integrated.profiles.windows": {
  "Test": {
    "source": "PowerShell",
    "icon": "terminal-powershell",
    "args": [
      "${workspaceFolderBasename}"
    ]
  }
}
```

Results in:

![image](https://user-images.githubusercontent.com/2193314/118540597-97892880-b705-11eb-9afb-fba7da5b83e3.png)

Arg variable resolving happens here:

https://github.com/microsoft/vscode/blob/2bf81674ee71f0f332aa65796cca8d52b9dc7261/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L287-L296

Let me know if it doesn't work for you in Insiders, lots of changes happened around profiles so it's possible this doesn't work in stable.

**Comment by marhoy** [comment]
I'm on stable (version 1.56.2), but it's good to know that support for variables is on the way :)

**Comment by Just-Insane** [comment]
Is there a difference between the Insiders builds of macOS and Windows? I can't get this working in Insiders - macOS.

With stable I can set custom profiles, but with Insiders I get an error about only supporting bash and zsh on osx.

Either way, I can't seem to get these variables working via Remote-SSH, is this expected to work with an upcoming release?

Stable:

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
```

Insiders:

```
Version: 1.57.0-insider (Universal)
Commit: 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
Date: 2021-05-18T05:12:52.309Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0
```

Error in Insiders:

```
The default profile used on macOS. This setting will currently be ignored if either `#terminal.integrated.shell.osx#` or `#terminal.integrated.shellArgs.osx#` are set.

Value is not accepted. Valid values: "bash", "zsh".
```

**Comment by Tyriar** [comment]
> but with Insiders I get an error about only supporting bash and zsh on osx.

This may have been a bug that's been fixed since.

> "vscode-${workspaceFolderBasename}"

I think that variable might have problems in remotes, tracked in https://github.com/microsoft/vscode/issues/115560
