### ISSUE TITLE
Please, add "Save" option to the opened file popup menu

### ISSUE THREAD

**Issue by Raspredval** [microsoft/vscode#124029]
Please, add "Save" option to the opened file popup menu, like shown below:
![popup_save](https://user-images.githubusercontent.com/46839056/118480513-8ad3f700-b73c-11eb-8205-cf83a8210cc1.jpg)
![popup_nosave](https://user-images.githubusercontent.com/46839056/118480862-0170f480-b73d-11eb-9047-2ee10533aa09.jpg)

**Comment by igorskyflyer** [comment]
The Save command is already available in the File menu and I personally don't even use menus, I prefer keyboard shortcuts - like I know a lot of developers do as well.

What would be the use case of such feature?
