### ISSUE TITLE
File icon with tabs disabled replaces dirty editor indicator

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12407]
Stable:
![image](https://cloud.githubusercontent.com/assets/323878/18728501/ac0934c4-804d-11e6-80de-2181905c072a.png)

Icons, editor has an unsaved change:
![image](https://cloud.githubusercontent.com/assets/323878/18728521/c90be792-804d-11e6-8380-b03b0704ba6d.png)

**Comment by roblourens** [comment]
Maybe the indicator could go to the right of the file label, like on a tab

![image](https://cloud.githubusercontent.com/assets/323878/18728551/f2042e2a-804d-11e6-8c15-75fea91fd702.png)

**Comment by bpasero** [comment]
@roblourens I moved the dirty indicator over the close button which is the same we do everywhere else in the UI:

![image](https://cloud.githubusercontent.com/assets/900690/18737735/680566d8-8095-11e6-9a7e-a9514c8d3b47.png)

**Comment by roblourens** [comment]
Ah I see it now. I agree that it's consistent but it feels far away for a notification. Maybe I should just get with it and enable tabs.

**Comment by bgashler1** [comment]
Since it would be an "X" up until a file is changed, I think it's a learnable behavior, and I don't have any objections to what @bpasero did.  @Tyriar you marked this as important.  Is there anything you would like to add here or anyone else that I'm not considering?

**Comment by Tyriar** [comment]
I was under the impression the indicator was no longer visible.

**Comment by bpasero** [comment]
I do expect some confusion with people that have tabs disabled and auto save off. On the other hand I argue that working in such a model means that you are likely less interested in dirty indicators in the editor space because all you see is the indicator for the current file you are in, not all the other dirty files in the stack. I would assume that:
* either you use the "opened editors" view as a replacement for tracking dirty files
* you do not care about the dirty indicator after all
* you have auto save enabled

Let's see how it goes :)

**Comment by chrisdias** [comment]
Regardless of my work style (tabs/no tabs, autosave on/off, etc), I think the "x" for close should be a stable UI element. I've never seen a close button turn into a dot before and I didn't initially think i could click on it. 

Why not just put the dot between the icon and the file name?

**Comment by chrisdias** [comment]
ok, now i see what you are doing... this mimics the "x" turning to a dot on tab.  

still, have you considered putting the dirty indicator to the left of the file name?

**Comment by bpasero** [comment]
That is how it was before and I moved it to the close button in the same way we show it in all the other places (opened editors, tabs).
