### ISSUE TITLE
Terminal profiles doesn't work with wsl after update

### ISSUE THREAD

**Issue by romanlex** [microsoft/vscode#124082]
After update to 1.56 terminal is disappear
![image](https://user-images.githubusercontent.com/3369304/118601487-9960f380-b7ba-11eb-81c8-502a65280d84.png)

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
