### ISSUE TITLE
Inline Completions API

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#124024]
(edited by @hediet)

We use this issue to track the progress of the Inline Completions API.

The currently proposed API can be found in [vscode.proposed.d.ts](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2567).

There is a sample extension [here](https://github.com/microsoft/vscode-extension-samples/blob/main/inline-completions/src/extension.ts).

Before this API can be finalized, we need to figure out these items at least:

* [x] How can inline completions interact with completions? (Currently, inline completions are hidden when autocomplete shows up and if there is an inline completion, autocomplete does not show up automatically)

**Comment by alexdima** [comment]
Extension:
```json
{
    "name": "ghosted",
    "author": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["*"],
    "main": "index.js",
    "enableProposedApi": true
}
```
```js
const vscode = require('vscode');

const suggestions = [
`if (n < 2) {
        return 1;
    }
    return fib(n - 1) + fib(n - 2);`
];



exports.activate = function() {
	console.log(`here I am!`);

	vscode.languages.registerGhostTextProvider({ pattern: '**' }, {
		provideGhostTextItems: (document, position, token) => {
			const textBefore = document.lineAt(position.line).text.trim();
			for (const suggestion of suggestions) {
				if (suggestion.toLowerCase().startsWith(textBefore.toLowerCase())) {
					return new vscode.GhostText(suggestion);
				}
			}
		}
	})

}
```

**Comment by hediet** [comment]
Here is a more sophisticated extension:
```js
// @ts-check
/// <reference path="C:\\dev\\microsoft\\vscode\\src\\vs\\vscode.proposed.d.ts" />

const vscode = require('vscode');

const suggestions = [
	`if (n < 2) {
        return 1;
    }
    return fib(n - 1) + fib(n - 2);`,
	`if (n < 3) {
        if (n < 2) {
            return 1;
        }
        return 1;
    }
    return fib(n - 1) + fib(n - 2);`
];

/**
 * @returns {number}
 * @param {string} a
 * @param {string} b
 */
function largestSuffixPrefixLength(a, b) {
	for (let i = Math.min(a.length, b.length); i > 0; i--) {
		if (a.substr(-i) == b.substr(0, i)) {
			return i;
		}
	}
	return 0;
}

exports.activate = function () {
	console.log(`here I am!`);
	vscode.languages.registerInlineSuggestionsProvider({ pattern: '**' }, {
		provideInlineSuggestions: async (document, position, token) => {
			await new Promise(resolve => setTimeout(resolve, 1000));

			const line = document.lineAt(position.line);
			/**
			 * @type {Array<vscode.InlineSuggestion>}
			*/
			const items = [];
			const evaluatedSuggestions = suggestions.map(s => ({
				text: s,
				largestPreSuffixLength: largestSuffixPrefixLength(line.text, s.split("\n")[0]),
			})).filter(s => s.largestPreSuffixLength > 0);

			evaluatedSuggestions.sort((a, b) => a.largestPreSuffixLength - b.largestPreSuffixLength);

			for (const suggestion of evaluatedSuggestions) {
				items.push({
					text: suggestion.text,
					replaceRange: new vscode.Range(line.range.end.translate(0, -suggestion.largestPreSuffixLength), line.range.end)
				});
			}
			return new vscode.InlineSuggestions(items);
		}
	})

}

```

**Comment by hediet** [comment]
Closing. This issue is tracked in the other repo.

**Comment by eamodio** [comment]
@hediet why is this proposal not still open? Normally for proposals, we keep them open until the api is finalized and shipped. So that users/extension authors can track the proposal more easily.

**Comment by GusSand** [comment]
Trying to copy https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2567 and get 404.  Is this link dead? This makes the sample in vscode: https://github.com/microsoft/vscode-extension-samples/blob/main/inline-completions/src/extension.ts useless as well. Can you please help?

**Comment by junghon3709** [comment]
> Trying to copy https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2567 and get 404. Is this link dead? This makes the sample in vscode: https://github.com/microsoft/vscode-extension-samples/blob/main/inline-completions/src/extension.ts useless as well. Can you please help?

@GusSand They have an updated way to get the `proposed.d.ts` file. First you have to change the `"enableProposedApi": true` to `"enabledApiProposals": [ "inlineCompletions" ]` in the `package.json` file. Then run `npm i vscode-dts` to download the latest version of [vscode-dts](https://www.npmjs.com/package/vscode-dts) and then `npx vscode-dts dev`.

See more [here](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_63.md#updated-api-proposal-structure) (if the link doesn't scroll down to the "updated api proposal structure" you have to control f it). 
```

**Comment by EricSteinberger** [comment]
@hediet @isidorn Hi folks! Is the API still likely to be released in April as mentioned in #137744?

**Comment by isidorn** [comment]
@EricSteinberger it is currently assigned to April and that is our plan. It might slip to May depending on how testing and feedback from Extensions that use this proposed API goes. I suggest to follow this issue for more details. Thanks!

**Comment by Aekalix** [comment]
> > Trying to copy https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2567 and get 404. Is this link dead? This makes the sample in vscode: https://github.com/microsoft/vscode-extension-samples/blob/main/inline-completions/src/extension.ts useless as well. Can you please help?
> 
> @GusSand They have an updated way to get the `proposed.d.ts` file. First you have to change the `"enableProposedApi": true` to `"enabledApiProposals": [ "inlineCompletions" ]` in the `package.json` file. Then run `npm i vscode-dts` to download the latest version of [vscode-dts](https://www.npmjs.com/package/vscode-dts) and then run `npx vscode-dts dev`.
> 
> See more [here](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_63.md#updated-api-proposal-structure) (if the link doesn't scroll down to the "updated api proposal structure" you have to control f it).

Hello!

While trying out the sample package (https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions). I receive the following errors. I also attempted the method you specified and the methods mentioned in the readme. In addition, I also tried the following npm commands:

- Npm install
- Npm run postinstall

Is this sample still up to date?

```[9:04:35 PM] Starting compilation in watch mode...

src/extension.ts:37:7 - error TS2352: Conversion of type '{ text: string; range: Range; someTrackingId: number; }[]' to type 'MyInlineCompletionItem[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ text: string; range: vscode.Range; someTrackingId: number; }' is not comparable to type 'MyInlineCompletionItem'.
    Object literal may only specify known properties, and 'text' does not exist in type 'MyInlineCompletionItem'.

37       text,
         ~~~~

src/extension.ts:49:16 - error TS2339: Property 'getInlineCompletionItemController' does not exist on type 'typeof window'.

49  vscode.window.getInlineCompletionItemController(provider).onDidShowCompletionItem((e) => {
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/extension.ts:49:85 - error TS7006: Parameter 'e' implicitly has an 'any' type.

49  vscode.window.getInlineCompletionItemController(provider).onDidShowCompletionItem((e) => {
                                                                                       ~

[9:04:36 PM] Found 3 errors. Watching for file changes.```

**Comment by isidorn** [comment]
@Aekalix good catch. I have tackled the outdated extension via this PR https://github.com/microsoft/vscode-extension-samples/pull/640
Once we get it approved I will merge it in and then the sample should be up to date. Thanks

**Comment by Jacobsolawetz** [comment]
Looks like this is on mainline? Any idea when it will be released beyond insiders?

**Comment by isidorn** [comment]
@Jacobsolawetz this is assigned to the May milestone. Which means it is part of our May release which usually gets shipped first 10 days of the following month. So this one should be available on Thursday.

**Comment by Jacobsolawetz** [comment]
@isidorn amazing! Thanks so much for getting back to me, I'll be deving accordingly :)

**Comment by isidorn** [comment]
I have opened this discussion for any follow up questions since we have done the finalization
https://github.com/microsoft/vscode-discussions/discussions/26
