### ISSUE TITLE
Add compare folders feature

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#124023]
I really like the [vscode-compare-folders](https://github.com/moshfeu/vscode-compare-folders) extension that was created by @moshfeu. It would be great if VsCode had a folder comparison feature directly integrated into the main program. such a feature would allow developers to select several folders and see the differences (files and code) between these folders.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks
