### ISSUE TITLE
Greek Characters error

### ISSUE THREAD

**Issue by Betsesv** [microsoft/vscode#124092]
I have made a powershell script with ISE powershell.
When open vscode the character are not recognized. 
When corrected with vs code the paths are not recognized.

**Comment by Betsesv** [comment]
Workaroud is to set encoding windows 1253

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
