### ISSUE TITLE
Improve Terminal Tabs handling by providing fly-out menu

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#124096]
Currently, it's quite a fumble to open a terminal using tabs with the default settings.

When I want to switch to another terminal sesssion, the tab item menu is always jumping in the way unexpectedly und without intention:

>   ![Terminal Tabs](https://user-images.githubusercontent.com/9283914/118640715-99bcb700-b7d9-11eb-9dac-1257653523f2.gif)

I propose to replace the current wobbly behaviour by a more stable and accustomed behaviour by providing a fly-out menu for interacting with the terminal session tabs:

> ![Terminal Tabs Suggestion](https://user-images.githubusercontent.com/9283914/118640726-9d503e00-b7d9-11eb-833f-e16a36c7924f.gif)

**Comment by Tyriar** [comment]
We ended up solving this accidental split/kill by hiding them when the tabs width is below a certain threshold (105px), below that you need to use keybindings or the context menu.'

<img width="127" alt="Screen Shot 2021-05-18 at 11 44 24 AM" src="https://user-images.githubusercontent.com/2193314/118706620-704a5e00-b7ce-11eb-8efe-a320e3450fbf.png">

<img width="191" alt="Screen Shot 2021-05-18 at 11 44 34 AM" src="https://user-images.githubusercontent.com/2193314/118706605-6b85aa00-b7ce-11eb-9910-efcd7510ea2e.png">
