### ISSUE TITLE
Suppress default 'Open launch.json' button if debug adapter returns error with command-type actions

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#124020]
Issue Type: <b>Bug</b>

Debug adapters have long been able to provide uris along with error responses, and these uris add buttons to the error dialog. Now that my PR #123833 has merged these can be command uris.

However it is not currently possible to prevent an extra 'Open launch.json' button being added to the error dialog.

In some situations there may be no point in the user opening launch.json. Instead they should use a button that the error response added.

@isidorn would it be reasonable for us to suppress addition of the 'Open launch.json' button when the error is adding its own command-type button(s)? Limiting the change in this way should minimize the chance of upsetting existing DAs which return uris with their errors. It's unlikely they have been returning command-type uris because until now these haven't been actionable.

VS Code version: Code - Insiders 1.57.0-insider (40d5e6796fbc32d67dd0009e5b0027003803fd7e, 2021-05-14T20:13:58.234Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
@gjsjohnmurray this sounds reasonable.
What is your exact use case? Just to check if other debug adapters might also profit here.

fyi @weinand

**Comment by gjsjohnmurray** [comment]
@isidorn my specific use case is that our implementation of launchRequest may determine that there is no debugging license for the target server. In this situation we want to help the user run the command which submits a request for a license. There is no point in suggesting that they edit their launch.json file.

Are you happy for me to submit a PR?

**Comment by isidorn** [comment]
Let's best wait and see @weinand feedback before you create a PR. Thanks

**Comment by weinand** [comment]
@gjsjohnmurray Yes, this request makes sense -  feel free to submit a PR.

**Comment by gjsjohnmurray** [comment]
PR submitted

**Comment by isidorn** [comment]
Lovely, thanks! Let me review it.

**Comment by isidorn** [comment]
@gjsjohnmurray Would also be great if you double check with you debugger once we have a new Insiders on Monday. Thanks!
