### ISSUE TITLE
"unable to verify the first certificate" when performing GET

### ISSUE THREAD

**Issue by alberto-bc** [microsoft/vscode#124058]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Install provided extension (rename zip to vsix)
2. Run "Hello World" command

Expected result: GET operation is successful and server response is printed to the console
Actual result: GET operation fails with the message "unable to verify the first certificate"

We were able to perform GET requests to a local server that is missing an intermediate certificate (via `new https.Agent({rejectUnauthorized:false})`. Our code was working as expected, but it recently broke in a VS Code update.

The attached extension works on VS Code 1.50.1, but it does not work with 1.50.6. 
~~removed `bug-0.0.1.zip` attachment~~

**Comment by joaomoreno** [comment]
I have removed the attached extension. Please provide issue details with code snippets, instead of an attached extension.

**Comment by chrmarti** [comment]
Does setting 'HTTP Proxy Support' in user settings to 'Fallback' make this work again?

What is the reason for letting the request ignore the certificate instead of installing the certificate (or a CA certificate for that) locally?

**Comment by alberto-bc** [comment]
> Does setting 'HTTP Proxy Support' in user settings to 'Fallback' make this work again?

Yes, this fixed the issue

>What is the reason for letting the request ignore the certificate instead of installing the certificate (or a CA certificate for that) locally?

There is no good reason, we are not in control of the server configuration

I tested and all options except "override" work for this issue (off/on/fallback). Seems the most restrictive setting is the default one, or am I missing something?

**Comment by chrmarti** [comment]
Correct, 'override' always replaces the agent you set with VS Code's agent to enable proxy support based on system configuration. 'fallback' is similar, but falls back to your agent when there is no proxy configured.

**Comment by alberto-bc** [comment]
Thanks for the explanation. Just one last question, why is `override` the default setting instead of `fallback`? The latter option handles correctly both scenarios (proxy is configured vs no proxy), while override will fail if there is no proxy.

**Comment by chrmarti** [comment]
`override` works better when the given agent applies a proxy when none should be used. This fixed https://github.com/microsoft/vscode/issues/117054.

I'm hesitant to tweak things for your case since the recommendation really is to install the required certificate locally. Is changing the setting a workable solution for you? Alternatively can extract the certificate from the server and add it locally (e.g., https://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server might help).

**Comment by alberto-bc** [comment]
Changing the user setting is a workable solution for use case. Thanks for looking into this!

**Comment by GordonSmith** [comment]
@chrmarti I have a similar issue but rather than `https.Agent({rejectUnauthorized:false})`, I am adding additional certificates via:

```
https.Agent({
    ca: [...existingCAs, ...myCAs]
})
```
Is there a better way to do this?

**Comment by chrmarti** [comment]
@GordonSmith You could add your CA certificates to the OS's root certificates.

**Comment by GordonSmith** [comment]
@chrmarti - Like I said above its already there:
![image](https://user-images.githubusercontent.com/966863/121717286-ea71b800-cad8-11eb-97cc-bef12285c42d.png)
