### ISSUE TITLE
feature: save multiple open terminal windows to the current workspace

### ISSUE THREAD

**Issue by ronffy** [microsoft/vscode#124078]

**Comment by ronffy** [comment]
![vscode](https://user-images.githubusercontent.com/13896347/118603387-6b91a400-b7e6-11eb-934f-5409331edca7.png)

**Comment by Tyriar** [comment]
We support reconnect but for creating terminal layouts that can be created in bulk we defer that to extensions like https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals to handle
