### ISSUE TITLE
Something to replace terminal.integrated.shell.*

### ISSUE THREAD

**Issue by TruongNgDac** [microsoft/vscode#124087]
With `terminal.integrated.shell.*` and `terminal.integrated.shellArgs.*` is deprecated now, there should be something new could be made to open specific terminal with specific arguments when open a specific workspace. Right now terminal profiles and terminal default profiles in user settings are not able to do that. Terminal default profiles is not even working right now.

**Comment by meganrogge** [comment]
Workspace profiles will work on hen you set "terminal.integrated.allowWorkspaceConfiguration":true. you should make sure you trust the origin of your folders though.

/duplicate #121470
