### ISSUE TITLE
新建新终端，其中字体间隔过大，设置终端字体后无效

### ISSUE THREAD

**Issue by wenxiuYang** [microsoft/vscode#124014]
Issue Type: <b>Performance Issue</b>

版本更新后，新建新终端，其中字体间隔很大，然后在  文件-> 首选项-> 设置 -> 终端 中，重新设置了终端显示的字体，重启vscode后，重新新建新终端，其中字体间隔仍然很大，（其中终端设置中字间距始终为0）,目前版本以为最新版本

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.14GB free)|
|Process Argv|--crash-reporter-id 5e5475ab-eade-4b31-b75f-ac3d07eaada3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	 18416	code main
    0	    24	  8632	   crashpad-handler
    0	    40	 12112	   utility
    3	    98	 15448	   shared-process
    0	    63	  4876	     ptyHost
    0	    71	 11500	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 13668	       console-window-host (Windows internal process)
    0	    77	 15744	   window (问题报告程序)
    0	   193	 19444	   window (无标题 (工作区) - Visual Studio Code)
    0	   132	 14284	     extensionHost
    0	    69	 15736	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=14284
    1	   383	 21828	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.6.0
path-intellisense|chr|2.3.0
regex|chr|0.4.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
tslint|eg2|1.0.46
prettier-vscode|esb|6.4.0
beautify|Hoo|1.5.0
vscode-pigments|jas|2.0.0
react-taro-snippets|liu|0.0.4
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.12.1
vscode-language-pack-zh-hans|MS-|1.56.2
vetur|oct|0.33.1
html5-boilerplate|sid|1.1.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.4.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by clawsl** [comment]
English Version using Google Translate:
 
# Issue Summary: **Create a new terminal, where the font interval is too large, and the terminal font is invalid after setting** 

After the version update, create a new terminal with a large font interval, and then reset the font displayed by the terminal in File -> Preferences -> Settings -> Terminal. After restarting vscode, create a new terminal again, where the font interval is still very large, (where the word spacing in the terminal settings is always 0), the current version is considered the latest version
