### ISSUE TITLE
Default width of terminal list is too narrow

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#124094]
Issue Type: <b>Bug</b>

The new terminal list will be too narrow to properly use. I assume this is subject to certain conditions, like my default shell having a short name like `zsh`.

![image](https://user-images.githubusercontent.com/1658949/118634174-89eda480-b7d2-11eb-9f67-1f15b4fdd1b4.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (22.76GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (33.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (33.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (33.72GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.16
terraform|has|2.10.2
vscode-esformatter|how|1.6.0
vscode-docker|ms-|1.12.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.33
vscode-yaml|red|0.19.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Just fixed yesterday 🙂 https://github.com/microsoft/vscode/issues/124048
