### ISSUE TITLE
Better bracket highlight visibility

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#12402]
From [UserVoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/10584708-bracket-highlighting) (600 votes)

The bracket highlight is too dim to easily see with most themes. In Notepad++ the brackets change color and become bold, i think that is much easier to see. Highlighting the "current bracket set" would also be really nice.

I understand the themes can be changed in a convoluted way. For such an important feature i think the feature should be default or easily accessible.

**Comment by seanmcbreen** [comment]
We do offer bracket highlighting:
![image](https://cloud.githubusercontent.com/assets/1051190/18729949/bfd1f1fc-8008-11e6-94cc-be455479eff6.png)

We also have indent guides which should help a lot here.

There are some good extensions e.g. Rainbow Brackets.
https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets

**Comment by waderyan** [comment]
@seanmcbreen the request is to improve the visibility of bracket highlighting. OP's opinion was its too dim.

**Comment by jitendravyas** [comment]
I'm looking for this feature. Do we have that ? https://github.com/facelessuser/BracketHighlighter

![image](https://cloud.githubusercontent.com/assets/77309/19923287/a8fc5736-a10c-11e6-9090-39f0489bf74d.png)

**Comment by bgashler1** [comment]
@jitendravyas That's odd, both my light theme and dark theme are not showing the same problem as your second screenshot.<img width="553" alt="screen shot 2016-11-02 at 1 31 23 pm" src="https://cloud.githubusercontent.com/assets/11839736/19948024/e29c8164-a107-11e6-8be4-e82b99186e5d.png">
Our bracket matching works when your caret is on a tag.  However, if you select the text of the tag, then it can be confusing because in addition it will highlight all text that matches the selection.  However, we will be improving color contrast to improve that scenario.

**Comment by AlexWaha** [comment]
How to change tag highlight background and foreground color?

**Comment by vvatikiotis** [comment]
HTML tag matching works in my theme, highlighting matching tags, _when there are no JSX javascript expressions within the tags_. However, tag highlighting works erratically when there are JSX javascript expressions within 2 enclosing HTML tags.

Works as intended:
![image](https://cloud.githubusercontent.com/assets/535853/20132214/877d6024-a66a-11e6-9a04-a1a4be5206a9.png)

Doesn't work:
![image](https://cloud.githubusercontent.com/assets/535853/20132234/9f3d0f20-a66a-11e6-8c2e-377addd5f347.png)

**Comment by bgashler1** [comment]
@vvatikiotis thanks for reporting that.  Since it's a different issue than being discussed here, I created a new issue for you.

**Comment by billyhoomm** [comment]
may i asked this problem has resolved？ i haven't find the extension like this :[https://github.com/facelessuser/BracketHighlighter](url)

**Comment by rwatts3** [comment]
@jitendravyas 
What theme is this ? 



![](https://cloud.githubusercontent.com/assets/77309/19923347/f007edc0-a10c-11e6-95f6-a7d34ce45f57.png)

**Comment by bpasero** [comment]
Can be done via our theming work now:

![image](https://cloud.githubusercontent.com/assets/900690/26463415/757c54d8-4184-11e7-82ce-939fd4ebe74c.png)

**Comment by kurtextrem** [comment]
I am sorry, but configuring the background or the border does not help in that case. We'd need something like "editorBracketMatch.border": "bottom #ff00ff".
See e.g. https://github.com/Microsoft/vscode/issues/23606 and https://github.com/Microsoft/vscode/issues/19534 (which was said to be tracked here).

**Comment by martinandersen3d** [comment]
And fontColor please

**Comment by loretogutierrezjr** [comment]
Hi,
It's the same problem with me.. I'm looking for some tweaks for match brackets in VS Code and I came across searching this one.. 

<a href="https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets#overview">Subtle Brackets </a>

It's working to me with the latest VS Code 1.16.1!
