### ISSUE TITLE
Disabling auto folder expand in tree view

### ISSUE THREAD

**Issue by wotta** [microsoft/vscode#124089]
I could not find any settings that allow this behavior.

Currently, I am struggling with the fact that vscode expands the complete folder when clicking on it.
I understand that many people like this behavior, but it really clutters my view when working.

If there is a setting that does prevent this behavior by any chance, I would really appreciate the setting could be shared.

**Comment by gjsjohnmurray** [comment]
`"workbench.tree.expandMode": "doubleClick"`

**Comment by wotta** [comment]
Hello @gjsjohnmurray,

This was indeed the setting I was looking for!
Thanks for the reply I really appreciate it.
