### ISSUE TITLE
vscode ignores indent settings and goes back to tabs

### ISSUE THREAD

**Issue by jiwidi** [microsoft/vscode#124056]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: 11.0.1

Steps to Reproduce:

I have some troubles with my vscode settings. I have the following settings:
```
detect indentation: false
insert spaces: True
tab size: 4
```

But anytime I focus out of vscode it will automatically change to tabs as indents for my python code!

I have recorded it and uploaded it to youtube https://www.youtube.com/watch?v=2ddf3IP8zNY. Here you can see in the bottom right corner that tabs are choosen as indent. I changed them to spaces and go into settings to check that all settings are correct to have spaces as indent but as soon as i close settings it goes back to tabs!

What am I missing?

My list of extensions:
```
be5invis.toml
DavidAnson.vscode-markdownlint
dracula-theme.theme-dracula
eamodio.gitlens
golang.go
HookyQR.beautify
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vsliveshare.vsliveshare
pnp.polacode
ritwickdey.LiveServer
skyapps.fish-vscode
vscode-icons-team.vscode-icons
yzhang.markdown-all-in-one
zxh404.vscode-proto3
```

**Comment by alexdima** [comment]
@jiwidi VS Code offers API through which an extension can change the indentation settings for files. That is for example how the `editorconfig` extension can work with VS Code. 

I believe one of the extensions you have installed is causing this behavior. You can use Extension Bisect to identify which one it is:

* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by drproteus** [comment]
I'm hitting this as well as of this morning. This is a "throw my hands up in exasperation" kind of bug. Back 2 Vim.

```
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by alexdima** [comment]
@drproteus VS Code extensions can change the indentation settings. Does this reproduce for you when disabling extensions using the steps I've shown above?

Did you configure all 3 settings `editor.detectIndentation`, `editor.insertSpaces` and `editor.tabSize` ?

**Comment by drproteus** [comment]
@alexdima Roger that-- I haven't changed my extension stacked in some years (but that's not accounting for update regressions). At first, I was suspect of the newest member of the band, Pylance. 

After stepping away and coming back, I haven't been able to get it to reproduce. All my settings seem to be in order, with the interesting bit: I have `detectIndentation` enabled but not `insertSpaces` (the help text implies its superceded by `detect`). So, possibly the detection got tripped up and it fell back to inserting a space.

If it happens again I'll see if I can get a better sample. Thanks!

**Comment by jiwidi** [comment]
I did a complete reinstall of vscode and it fixed it. Closing the issue
