### ISSUE TITLE
c++ debug failed on Ubuntu 21.04

### ISSUE THREAD

**Issue by oblind** [microsoft/vscode#124041]
Issue Type: <b>Bug</b>

after updating to Ubuntu 21.04, c++ debug failed, a message show "The terminal process "bash ''" failed to launch (exit code: 127).", I reinstalled GDB and C/C++ plugin, but still do not works.

my launch.json:
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/tire",
      "args": ["-licenseRepeat"],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb",
      "preLaunchTask": "x64",
      "setupCommands": [
        {
          "description": "为 gdb 启用整齐打印",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    },
}

VS Code version: Code - Insiders 1.57.0-insider (82767cc1d7bf8cdea0f2897276d5d15aee91f3d9, 2021-05-17T05:15:14.544Z)
OS version: Windows_NT x64 10.0.21382
Remote OS version: Linux x64 5.11.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.71GB free)|
|Process Argv|--crash-reporter-id 5ad76854-09a4-48fd-a2c1-ec352411fdb0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.11.0-17-generic|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (2 x 1799)|
|Memory (System)|4.00GB (1.98GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
vscode-apache|mrm|1.2.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
vscode-remote-extensionpack|ms-|0.21.0
Bookmarks|ale|13.0.4
vscode-intelephense-client|bme|1.7.1
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.21
php-debug|fel|1.15.1
svg|joc|1.4.6
cpptools|ms-|1.3.1
php-docblocker|nei|2.1.0
vetur|oct|0.33.1
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17
vscode-counter|uct|2.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255cf:30296410
vscorehov:30301224
vscod805cf:30301675

```

</details>

**Comment by weinand** [comment]
@oblind If you comment out the "preLaunchTask" does this problem still occur?

**Comment by nevadaperry** [comment]
I also started having this issue with Insiders for Ubuntu around the same time. It appears to have been introduced by the daily update.

```
/bin/bash: : No such file or directory
```
(and a popup about bash exit code 127)

Resetting settings, extensions, and project launch and tasks caused no improvement. Switching to Stable seems to be the only solution currently.

**Comment by oblind** [comment]
> @oblind If you comment out the "preLaunchTask" does this problem still occur?

the "preLaunchTask" is used to compile my codes before launching

**Comment by Xinyu-Wu-0000** [comment]
I also have the "The terminal process "bash ''" failed to launch (exit code: 127)." error.

**Comment by Tyriar** [comment]
Do you set `terminal.integrated.inheritEnv` to false?

**Comment by Xinyu-Wu-0000** [comment]
> Do you set `terminal.integrated.inheritEnv` to false?

It doesn't help. The problem continues.

**Comment by Tyriar** [comment]
To be clear, you should _not_ be setting that.
