### ISSUE TITLE
Splitting a centered view does not cause editor to take full width

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#124051]
1. Have a centered view
2. Split the editor
3. The editor is moved to the left side, but does not expand its width

[Video](https://memes.peet.io/img/21-05-75924b17-c3bf-4b7d-a650-34da087353b6.mp4)

**Comment by sbatten** [comment]
@bpasero this is happening within the editor part not at the workbench level. the editor part is properly full width.

**Comment by bpasero** [comment]
Centered editor layout -> Isi

**Comment by isidorn** [comment]
I can reproduce this. This works in stable so something broke in the meantime. 
Easier repro: F1 > toggle centered editor mode. F1 > toggle centered editor mode -> layout broken

And yes we try to leave centered editor mode when there is more than 1 editor.

I will bisect now....

**Comment by isidorn** [comment]
Seems like this commit https://github.com/microsoft/vscode/commit/0449a18b7bb1d8b3cf7138df63e03126ba47c21d broke centered layout. Thus also assigning to @joaomoreno 

![Screenshot 2021-05-18 at 10 02 21](https://user-images.githubusercontent.com/1926584/118615012-9832c500-b7c0-11eb-9bfe-08653c6e53e0.png)

**Comment by joaomoreno** [comment]
Good bisecting! 👌
