### ISSUE TITLE
VSCode on M1 MacBook Pro SOURCE CONTROL is slowly

### ISSUE THREAD

**Issue by pramodjayram** [microsoft/vscode#124021]
Does this issue occur when all extensions are disabled?: Yes

dialog can assist with this. -->
- VS Code Version:
- Version: 1.56.2
   Electron: 12.0.4 
   Chrome: 89.0.4389.114
   Node.js: 14.16.0
   V8: 8.9.255.24-electron.0
   OS: Darwin arm64 20.4.0

Steps to Reproduce:

1. When i use VSCode on M1 Macbook Pro, the VSCode does not start source control immediately. It takes almost 30 minutes to load the the source control. But when I use Intel based mac, then the source control opens immediately.

**Comment by deepak1556** [comment]
Can you attach the performance profile following these steps,

* Open window devtools
* Go to performance tab
* Click start profiling and reload page icon
* Perform actions indicating the slow source control
* Download the profile

**Comment by pramodjayram** [comment]
Re-installing VSCode and clearing cache solved the issue.
