### ISSUE TITLE
VSCode insider can't delete more than one file 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#124030]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57 insider
- OS Version:win

Steps to Reproduce:

1. select more than one file
2. delete those files
3. vscode delete the frist file, but can't delete other file and show a dialog

![image](https://user-images.githubusercontent.com/1876302/118483919-35eaad80-b749-11eb-94c6-d8dc100f1566.png)

**Comment by heartacker** [comment]
1.56.2 is ok

**Comment by isidorn** [comment]
I can not reproduce this.
Seems like the errors is coming from the file service. Thus forwarding to @bpasero
However I am not sure if we can do anything here. This feels like it is designed behaviour.

**Comment by bpasero** [comment]
What exact version of insiders is this?

**Comment by heartacker** [comment]
> What exact version of insiders is this?

Several versions have been like this.
And the least version of now Still has the problem.

**Comment by bpasero** [comment]
The error message seems to originate from bulk edit service though:

https://github.com/microsoft/vscode/blob/7f9835ac43382b942b57b9d8df50344e2a4737a1/src/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.ts#L238-L238

**Comment by heartacker** [comment]
after using exts bisect: it seems that this is vscode's problem
![image](https://user-images.githubusercontent.com/1876302/118575991-4129f180-b7ba-11eb-8bf5-23cbbb3b1ba1.png)
,
also, `--disable-extensions`, reproduce

**Comment by heartacker** [comment]
seem that the proble is caused by VSCode，any update for this problem?

**Comment by heartacker** [comment]
hi all. I believe this problem should be fixed in 1.57 because 1.56 is working  well.
