### ISSUE TITLE
Sometimes being unable to select text as usual when multiple row tab and multiple editor pane are enabled

### ISSUE THREAD

**Issue by computHome** [microsoft/vscode#124079]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.56.2
- OS Version: win 10

Steps to Reproduce:

1. when 2 editors are open side by side
2. multiple wrapped tab rows are enabled
3. several files are shown in the tab
4. sometimes (when the editor is positioned as certain size), when I want to double click to select some texts on the left pane from right pane which is being active at the time, I cannot, as usual by one go, select the text as the editor position jumps as illustrated in the attached video

https://user-images.githubusercontent.com/6612226/118588661-6fff9200-b7d1-11eb-85e3-b6cbb402d0ed.mp4

**Comment by roblourens** [comment]
I guess this can happen when the "wrap tabs" setting is enabled, and showing the editor buttons causes tabs to wrap another row. You can disable that setting to work around it. I think it probably isn't a bug though.

**Comment by bpasero** [comment]
This works intentionally like that due to https://github.com/microsoft/vscode/issues/113818 which @alexdima fixed.

There is https://github.com/microsoft/vscode/issues/115136 to cover the fact that tabs can jump around with wrapping.

**Comment by computHome** [comment]
It's not a bug but this side effect should better be avoided considering this editor is so popular and highly praised. This jumping behavior combining mouse click (creating behavior of selection and dragging) could possibly make change to a file unnoticeably when users switching files by clicking text between 2 sides depending on how busy the machine is and its clock speed.
