### ISSUE TITLE
Javascript Debug Terminal hangs with `nx serve my-backend` with nx + nest.js after 1.56

### ISSUE THREAD

**Issue by jesse23** [microsoft/vscode#124060]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56
- OS Version: macos 11.3.1
- nrwl 12.1.0
- nestjs 7.6.15

Steps to Reproduce:

1. Start a Javascript Debug Terminal
2. npx nx serve my-backend

Result:
- debugger hangs with:
```
 ➜ npx nx serve my-backend                                                                                                                                       Mon May 17 17:11:56 2021
Debugger attached.

> nx run my-backend:serve 
Debugger attached.
Starting type checking service...
Using 14 workers with 2048MB memory limit
Debugger attached.
Debugger attached.
Debugger attached.
Debugger attached.
Type checking in progress...
Hash: 7f7ca48a79b89d4aa340
Built at: 05/17/2021 5:12:20 PM
Entrypoint main [big] = main.js main.js.map
chunk {main} main.js, main.js.map (main) 1.53 MiB [entry] [rendered]
```

- After press Ctrl+C to terminate the process, some of the debugger processes are still alive:
![image](https://user-images.githubusercontent.com/643912/118557566-5b6cbc80-b733-11eb-9124-d9016e97b1eb.png)

**Comment by jesse23** [comment]
- It was working on last week, but after it gets upgrade automatically, it is start failing.
- But I tired to roll it back to 1.56.1 and 1.56.0, neither of them works.
- I tried to roll it back to 1.55. It works again.
  - When it works fine, looks it will attached to the main.js correctly...which is not happening in the not working case.

**Comment by connor4312** [comment]
Please collect a log on both versions so I can see the different 🙂  For the debug terminal, you can do so using the following setting:

```
  "debug.javascript.terminalOptions": {
    "trace": true
  },
```

/jsDebugLogs

**Comment by jesse23** [comment]
Thx will try to update it before next week.

**Comment by jesse23** [comment]
Mailed the log. Thx!

**Comment by jesse23** [comment]
@connor4312 Sent another mail with Google drive link. Sorry for the late.

Have a nice holiday!

**Comment by connor4312** [comment]
Thanks for the logs! This'll be fixed in the next [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by rzhao271** [comment]
@jesse23 has the issue been fixed for you with the nightly version of the extension?

**Comment by jesse23** [comment]
@rzhao271 @connor4312  Sorry didn't notice this `author-verification-request` status...

I installed `vscode-js-debug` nightly from store:  (v2021.6.1117)

- Now I got 2 `JavaScript Debug Terminal` option in create console..
- I tried both with `npx nx serve my-backend`, both of them will hang in the same step...and have the same behavior.

I will see if an OOTB nx-nestjs project can reproduce this.

**Comment by connor4312** [comment]
@jesse23 please do steps 1 and 2 here https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by jesse23** [comment]
@connor4312  Thx....with steps 1 and 2:

- Now there is only one `JavaScript Debug Terminal`.
- Yes the issue has been fixed, it could start the service correctly.
- Break point works fine.

Thanks again!!
