### ISSUE TITLE
Make VS Code Portable

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#12401]
Enable to install VS Code on portable media like USB disk. 

Request from [User Voice ](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7760061-visual-studio-code-portable)- 946 votes.

**Comment by waderyan** [comment]
Comment migration:

In the meantime here is a solution: https://github.com/garethflowers/vscode-portable

**Comment by waderyan** [comment]
Comment migration:

Yes, so far i've found several vsc folders in my windows profile directory. Atom keeps it all inside a .atom folder, and i'd be fine with that at a minimum, just not scattered as it makes it difficult to reproduce to another computer.

**Comment by waderyan** [comment]
Comment migration

I want to use it on the company PC where we are allowed to use external software but we can't install anything that requires admin access without a humongous amount of approvals - I'm not gonna go through all the hoops to install this, so I'm using notepad++ which comes installed and Crimson Editor which is portable...

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/329
