### ISSUE TITLE
navigation in sidebar, and image state memory

### ISSUE THREAD

**Issue by altruios** [microsoft/vscode#124065]
I would like to be able to use the arrow keys to navigate in the sidebar with the files...
I want to be able to hold the down arrow button and scroll through files selected, selecting the highlighted file.
in the case of images, if there was a sequence of them, I want to by scrolling through the files, as a poor man's preview of a rendering, for programmatically rendering sequences of images, having this featuer in vscode instead of another application is just one more step into pure holistic integration.

In addition to scrolling though files:
another great addition would be the basic feature of image zoom memorization, where zoom value is retained across images, on a toggle/button/menu checkbox, this is useful for debugging tiny details on large programmatically generated images.

**Comment by mjbvz** [comment]
One issue per issue please

@isidorn Assigning you since the first part of this looks explorer related

**Comment by altruios** [comment]
Aye, apologies for the two in one. They just happened to be related in the current project I am working on :)

**Comment by isidorn** [comment]
@altruios we support that you arrow down through the explorer and that you can press the `space` key to open a file in the editor and remain focused in the explorer.

Apart from that we do not plan to change that scrolling down automatically opens file in the explorer.
Though it is a fair feature request, so I can leave this open and assign to backlog.

**Comment by altruios** [comment]
aye, I was unaware of the space key's function - could it be a feature that the space key, when held down, automatically opens the file to which the arrow navigates?
