### ISSUE TITLE
[Feature Request] Super Shortcut key

### ISSUE THREAD

**Issue by hellokidder** [microsoft/vscode#124002]
hi/ Vscode is an amazing product And Thank you for your development, let me enjoy such a good product

I have an idea. I named it Super key

Vscode has so many keyboard shortcuts that it provides us with a great development experience.

But because there are so many keyboard shortcuts, we need to practice over and over again and often forget some less commonly used functions.

so I want a Feacture like the f key of the chrome plug-in vimium,

When I press the Super key, all the buttons that can be clicked will display a shortcut key，In this way, we can basically break away from mouse development.

I tried to develop vscode plug-ins to solve this problem, but I found that vscode does not allow plug-ins to access and modify DOM elements, so I really hope your team will be able to add this feature in the future.

Looking forward to reply and thanks again for such a great product.

**Comment by misolori** [comment]
We actually do provide tooltips that have the shortcut for each item, like:

![image](https://user-images.githubusercontent.com/35271042/118704902-73dce580-b7cc-11eb-98ba-d2d91093b8a1.png)

But we don't have any plans to create a "shortcut mode" so I'll be closing this as out of scope. Thanks for the suggestion, though!
