### ISSUE TITLE
terminal.integrated.shellArgs.windows no longer executed when opening console

### ISSUE THREAD

**Issue by fenchu** [microsoft/vscode#124090]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: win10 10.0.19043

Steps to Reproduce:

1. create any python venv (python.exe -m venv <directory to all venv>
in this example it is `C:\\dist\\venvs\\hso-fullstack-test`
2. add the following to ~/.vscode/settings.json
```
    "python.pythonPath": "C:\\dist\\venvs\\hso-fullstack-test\\Scripts\\python.exe",
    "python.linting.pylintEnabled": true,
    "python.terminal.activateEnvironment": true,
    "terminal.integrated.shellArgs.windows": [
        "powershell -noexit -command \"& {C:\\dist\\venvs\\hso-fullstack-test\\Scripts\\Activate.ps1}\""
    ],
```
2. press ctrl+j to open terminal, earlier it then executed the powershell command above and loaded the virtual environment
but now it is nothing. This worked fine until v 1.56
![vscode-command-no-longer-executes](https://user-images.githubusercontent.com/11349883/118615231-d03a0800-b7c0-11eb-8e23-08a98481407d.jpg)

**Comment by fenchu** [comment]
In terminal the following line used to appear:
```
PS C:\dist\work\hso-fullstack-test> C:\\dist\\venvs\\hso-fullstack-test\\Scripts\\Activate.ps1
(hso-fullstack-test) PS C:\dist\work\hso-fullstack-test> 
```

**Comment by meganrogge** [comment]
Is this in your workspace settings? If so, set "terminal.integrated.allowWorkspaceConfiguration":true if you trust the origin of your folders

**Comment by fenchu** [comment]
Thanks @meganrogge, This setting must be set in: 'C:\Users\mobj\AppData\Roaming\Code\User\settings.json'
