### ISSUE TITLE
The new version of webview failed to load resources

### ISSUE THREAD

**Issue by rumunanfeng** [microsoft/vscode#124088]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.56.2
- OS Version:

Steps to Reproduce:

1.When I was developing a plug-in, I got the data asynchronously and then loaded the html content of the webview. At this time, neither js nor css can be loaded successfully
2.My colleague did not have this problem when using version 1.54. I rolled back the version to 1.54 and it returned to normal.

Node.js: 14.16.0

**Comment by mjbvz** [comment]
Please share a minimal extension that demonstrates this issue

/needsMoreInfo
