### ISSUE TITLE
Remove the change that will copy the string the mouse is hovering over to the clipboard

### ISSUE THREAD

**Issue by queglay** [microsoft/vscode#124028]
In the VScode terminal (MacOS), I used to be able to select text, copy it and paste it reliably.  There was a recent change that I find problematic, and I now cannot rely on the clipboard when using the vscode terminal like I can elsewhere.

...Now when the mouse is hovering over a string separated by whitespace, then it will copy just that segment to the clipboard.  This is not conventional, and it reduces accuracy.  Please consider reverting this behaviour / removing it.

**Comment by Tyriar** [comment]
Did you accidentally turn `terminal.integrated.copyOnSelection` on? The only other ways to copy are via keybindings/commands or `terminal.integrated.rightClickBehavior`.
