### ISSUE TITLE
Bad Interface in VSCODE TERMINAL

### ISSUE THREAD

**Issue by marcosafonso** [microsoft/vscode#124099]
Issue Type: <b>Bug</b>

The simbols of "New Terminal"( + )  and  the simbol of "launch profile" are very close and confuse when it comes to clicking;

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (1.04GB free)|
|Process Argv|--crash-reporter-id ce8d1f3b-1757-4939-a732-59ea03e92af4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
vscode-docker|ms-|1.12.1
vscode-language-pack-pt-BR|MS-|1.56.2
mssql|ms-|1.10.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
material-icon-theme|PKi|4.6.0
autoimport|ste|1.5.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by Tyriar** [comment]
They're intentionally close as they're closely related (both create new terminals, one is advanced). This is an established pattern used elsewhere in vscode. More context on design of tabs in https://github.com/microsoft/vscode/issues/10546
