### ISSUE TITLE
Please add support to listen audio displayed using IPython on notebooks

### ISSUE THREAD

**Issue by Koushik0901** [microsoft/vscode#124091]
Issue Type: <b>Feature Request</b>

Please add support to listen audio displayed using IPython on notebooks

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic

**Comment by roblourens** [comment]
Can you tell me more about how to get audio in a notebook?

**Comment by Koushik0901** [comment]
> Can you tell me more about how to get audio in a notebook?

Using IPython library

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/111073
