### ISSUE TITLE
Revel in File Explorer shortcut select wrong file

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode#124005]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.56.0
- OS Version: 10.0.18363

Steps to Reproduce:

1. prepare file "root/file1" and "root/fodler/file2"
2. open "root" as root folder.
2. open "file2", so we could edit it
3. right click "file1" in EXPLORER, we could see "Revel in File Explorer      Shift + Alt + R"
4. use the shortcut "Shift + Alt + R"

You would see the open file explorer which selects editing file(file2) rather than the real file I want to open(file1)
And, use mouse to click could open the correct file.

The shortcut(Shift + Alt + R) has nothing to do is more consistent with other shortcuts. However, open the wrong file is a bad choice I think.

**Comment by isidorn** [comment]
@ShuiRuTian yeah, reveal in Explorer reveals the file which is focused in the explorer if the focus is in the explorer. If the focus is in the editor area than that file will be revealed.

I would not change anything here as this is how users are used to use this command. 
However I can leave this open for now to gather more feedbck
