### ISSUE TITLE
Cannot connect to a codespace with trusted workspaces enabled.

### ISSUE THREAD

**Issue by srivatsn** [microsoft/vscode#124050]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.57.0-insider (user setup)
Commit: 82767cc1d7bf8cdea0f2897276d5d15aee91f3d9
Date: 2021-05-17T05:15:14.544Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Ensure that this is checked:
![image](https://user-images.githubusercontent.com/20570/118529827-c947c280-b6f8-11eb-9a3b-95ce58df0323.png)

2. Install the GitHub Codespaces extension and try to connect to a codespace.
It fails to load the workspace and results in this error:

![image](https://user-images.githubusercontent.com/20570/118529911-e67c9100-b6f8-11eb-97dd-5ac5bee96ab3.png)

**Comment by srivatsn** [comment]
Is there anything needed from a resolver extension to support trusted workspaces? /cc @kieferrm @jkeech

**Comment by lszomoru** [comment]
@srivatsn, we have proactively reached to extension authors ([example issue](https://github.com/microsoft/vscode-eslint/issues/1245)), to evaluate the level of support that the extension would provide in an untrusted workspace. It looks like we were not able to file an issue against the Codespaces extension. Please review the information from the issue linked above and please don't hesitate to contact us if you have any questions or concerns. 

We are also working on a set of APIs that resolver extensions will be able to use to "configure" workspace trust. That work is currently in progress and we will be reaching out to resolver extension authors as soon as we have something ready to be tried out.

**Comment by jkeech** [comment]
I guess we need to decide how to handle trusted workspaces in Codespaces. I haven't given it enough thought yet about what the implications are or how we could support a limited trust mode. Given that we are a resolver, it sounds like it's not expected to work yet for resolver extensions?

Is the plan to have remote connections / workspaces be untrusted by default and prompt for trust during resolution? Or would the resolver need to handle trustiness via it's own prompts (as needed) and tell VS Code about the trustedness of the workspace?

The main issues that come to mind with our resolver are not really specific to the Codespace resolver, but would be applicable for any resolver dealing with an untrusted workspace: access to VS Code user data / settings on the client side / setting sync. We also have a GitHub OAuth token on the desktop client side via VS Code's auth provider which is potentially at risk in an untrusted remote workspace.

**Comment by misolori** [comment]
I ran into this today, opened a Codespace in desktop > Selected "Trust" and now I'm left in a broken state:

<img width="600" src="https://user-images.githubusercontent.com/35271042/118722669-451d3a00-b7e1-11eb-9247-912bc1dac60d.png">

<img width="600" src="https://user-images.githubusercontent.com/35271042/118722751-6716bc80-b7e1-11eb-851b-6325c4ada464.png">

**Comment by srivatsn** [comment]
@lszomoru until the new resolver APIs are in place, what can we do to unblock users? Should we say 

```"capabilities": {
  "untrustedWorkspaces": {
    "supported": true
  }
}
```

**Comment by sbatten** [comment]
@srivatsn yes, this will keep the extension enabled in all cases. users can also override using `extensions.supportUntrustedWorkspaces`.

**Comment by sbatten** [comment]
Main issue is resolved with codespaces supporting untrusted workspaces. When resolver API is available, we will reach out to onboard.
