### ISSUE TITLE
Confirmation on termial tab close by icon

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#124011]
Ask for confirmation to close a tab by "tab icon". Having hover icons and small tabs area it's easy to close a tab by mistake.
I'd propose a top area similar to ctrl-r to list terminals and choose among them.
First entry can also be create new terminal (showing terminal types).

**Comment by Tyriar** [comment]
There's the `terminal.integrated.confirmOnExit` setting to protect this if it's a big concern. We also made some changes to make it harder to accidentally kill the terminal in the tabs list by hiding the actions when the list is small.
