### ISSUE TITLE
Word Wrapping doesnt work

### ISSUE THREAD

**Issue by powersindustries** [microsoft/vscode#124074]
Issue Type: <b>Bug</b>

1. Install VS Code on a windows machine.
2. Go into File->Preferences->Settings and set "Editor: Word Wrap" to on.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.14GB free)|
|Process Argv|. --crash-reporter-id d29447ca-b540-4171-b028-85f1e246c6e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.11
cpptools|ms-|1.3.1
vim|vsc|1.20.2
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by yordiak** [comment]
Did you try to restart vscode? I faced a similar issue. I solved it by setting line wrapping to on, save and then restart. After that, I set again line wrapping to on
