### ISSUE TITLE
Integrated Terminal Tab is too long/truncated

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode#124032]
Does this issue occur when all extensions are disabled?: Yes/No

No, it does not, but that is because I can't figure out how to make it run PowerShell 7 without the PowerShell extension 😅

- VS Code Version: Insiders 
1.57.0-insider
82767cc1d7bf8cdea0f2897276d5d15aee91f3d9
x64

- OS Version:
Latest Windows 10 Version 2004

Steps to Reproduce:

1. Install PowerShell Extension and PowerShell 7 via the Windows Store
2. Run PowerShell 7 as an integrated tab

![image](https://user-images.githubusercontent.com/8278033/118482497-189bec00-b715-11eb-9ee4-0b82479b9861.png)

Perhaps instead of the whole path, it could just be the executable name?

**Comment by Tyriar** [comment]
Do you have `"terminal.integrated.experimentalUseTitleEvent": true` set?

**Comment by Tyriar** [comment]
This has actually been bugging me as well since I turned it on recently for my macOS and the setting got synced. I wonder if we should truncate it to exclude the whole path if it's a valid path? That way anything custom would be used as is.

**Comment by potatoqualitee** [comment]
Thank you 🙇🏼
