### ISSUE TITLE
[Getting Started] Steps with links don't have a clickable image anymore

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#124049]
#115320 fixed this before but regressed.

**Comment by JacksonKearl** [comment]
With potentially many buttons/links per step, it's hard to know what to open in general. We can either do this in markdown, or maybe only handle the situation when you have a single action in the step.

**Comment by andreamah** [comment]
Is this supposed to be resolved? Clicking on the "Lean back and learn" video for me doesn't do anything on current insiders.
I'm clicking on the image here:
![image](https://user-images.githubusercontent.com/31675041/120704103-66ce2080-c473-11eb-8c39-3fdcc7247d28.png)

**Comment by JacksonKearl** [comment]
Good catch, not sure why exactly the prior didn't work.

**Comment by andreamah** [comment]
Just a nitpick: when you hover over the video, perhaps the cursor should turn into a pointer since it's technically a link? The `Watch Tutorial` button does that, so I was expecting that the photo link also does that.

**Comment by JacksonKearl** [comment]
@andreamah we can track that in a separate issue. This was more about helping folks who were already clicking on the link.
