### ISSUE TITLE
The name "Code" for the editor makes it extremely hard to find information about the editor in search engines

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Microsoft/vscode#12405]
Please consider renaming the editor to something unique.  It's very tricky to search for issues or help or information online because searching for "code" isn't exactly limiting the results and they are mixed up with Visual Studio results often.

**Comment by seanmcbreen** [comment]
Thanks for reaching out to us about this - branding the product was a long a difficult process.  Ultimately we landed on Visual Studio Code and now this is something that's very hard to move away from.  We appreciate this makes some searches difficult - and we are looking at ways to improve that.

But one thing we are not considering is changing the products name.  Something we have done to ease this is try and have clear tags `vscode` in things like stackoverflow and we also have a search box on our own site https://code.visualstudio.com where the 'authoritative' docs are.

But this will continue to be an issue for all of the community and other blogs that have been published.

Closing this for now as we do not plan to change the product name.
Sean

**Comment by WhatFreshHellIsThis** [comment]
Hi Sean, I understand there certainly must be factors the general public doesn't know about with a large corporate chain of command getting involved and that must be frustrating.

This isn't just a search issue in my opinion it's full of ambiguity: it has nothing to do with Visual Studio at all that I'm aware of so it actually might negatively impact existing Visual Studio related searches and marketing, it's hard to search on as I pointed out earlier and using the word 'code' in the name is clearly ambiguous right on the face of it to any software developer (but not to a marketer I guess).

It certainly does help that it's been "tagged" as vscode in some areas of the web and I'll try to remember that for any future issues I run into thank you. 

Cheers!
