### ISSUE TITLE
xdebug 3.0.3 + php 7.4.9 + vscode 1.55.1 + linux / Ubuntu 20.10

### ISSUE THREAD

**Issue by davidbuzz** [microsoft/vscode#124162]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.55.1 
- OS Version: Ubuntu 20.10

Steps to Reproduce:

1.  X debug for php stopped working reliably, seemed to work for first breakpoint and then go haywire
2. Yes, i'm aware there are other issue's raised about xdebug/php issues, but I think i have more info avail.
3. By adding  "log": true   to my launch.json  i was able to review the additional plugin info in the vscode 'Debug Console' , and i found that after first breakpoint, the debug console showed a *misellaneous* string (65 chars long and quite unique/obvious) taken from some of my (not even php) code elsewhere in my project.   it was a snippet of a string from a .py file actually.   
4.   i searched my entire filesystem for all references to this 'unique string' in my code-base, and removed them from the code-base, so this unique string was no longer on-disk in my code, problem persisted.
5. searched my entire home-folder for the 'unique string' , and found it in 
~/.config/Code/User/workspaceStorage/ad0d4e1614e2ca7bda5e59da26735854/state.vscdb.backup 
and 
~/.config/Code/User/workspaceStorage/ad0d4e1614e2ca7bda5e59da26735854/state.vscdb

6. I closed vscode, deleted these two files, and re-searched my entire home folder for the uniqueue string...

7.   restarted 'vscode' , tryied to debug some php with xdebug in the usual manner, and ..
problem went away.        !

suspicion:    corrupted sqlite  file used by vscode.

**Comment by weinand** [comment]
/causedByExtension

Only the php extension knows what is being logged when using the "log" property.

**Comment by davidbuzz** [comment]
fault:   corrupted .sqlite file.
Should an extension be able to corrupt the sqlite file in vscode?  that's the real error here.

**Comment by davidbuzz** [comment]
I would very much like to re-open, as i don't believe the extension is responsible for maintaining the integrity of vscode's sqlite files..... but i cant.   i consider this issue needs to be re-opened.
