### ISSUE TITLE
Custom hovers should hide when context menu shows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124185]
At least that is what native hovers do:

![image](https://user-images.githubusercontent.com/900690/118833579-d8c63780-b8c1-11eb-9658-e3dc3d321bb6.png)

**Comment by Tyriar** [comment]
This is up to whoever is using the hover service to hide it when the context menu is triggered

**Comment by bpasero** [comment]
@Tyriar isn't that a bad design choice though, everyone would need to listen to context menu visibility to hide the hover? I would think the hover service itself should listen on context menu visibility and then hide?

**Comment by Tyriar** [comment]
:+1: I'll add a `IContextMenuService.onDidShowContextMenu` and listen to that.
