### ISSUE TITLE
Java Script Debugger terminal falsely claims running of wrong machine

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#124186]
<img width="719" alt="capture" src="https://user-images.githubusercontent.com/1931590/118836960-a79b3680-b8c4-11eb-93a3-65f22af71c07.png">

The terminal in on the WSL side on Windows :-)

**Comment by Tyriar** [comment]
@connor4312 in a remote workspace if you launch a terminal using a local cwd URI. @dbaeumer is that what's happening?

Also saw this: https://github.com/microsoft/vscode-remote-release/issues/5055

**Comment by dbaeumer** [comment]
Actually, I don't know. I simply start a Java Script Debugger terminal from the drop down.
