### ISSUE TITLE
The terminal process "zsh ''" failed to launch (exit code: 127) 

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#124173]
- VS Code Version:

Version: 1.57.0-insider
Commit: a9c5e37ea0dc020f5df3b1c82ef020627fc8cd7c
Date: 2021-05-19T08:54:30.480Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

- OS Version: macOS Catalina 10.15.7 

Steps to Reproduce:
1. Write a HelloWorld.java program, and clicking "Run" codelens will try to launch the program in a terminal.
![image](https://user-images.githubusercontent.com/14052197/118808783-6f075700-b8dc-11eb-8749-4e0caeb6153f.png)

2. Failed to launch due to the error message.
![image](https://user-images.githubusercontent.com/14052197/118808894-8d6d5280-b8dc-11eb-8dcc-eb4604e53f7b.png)

The setting `terminal.integrated.inheritEnv` is enabled.

**Comment by Xinyu-Wu-0000** [comment]
I got the following error too.

``The terminal process "bash ''" failed to launch (exit code: 127).``

Extension version: 1.4.0-insiders2
VS Code version: Code - Insiders 1.57.0-insider (4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5, 2021-05-21T05:13:19.775Z)
OS version: Linux x64 5.11.0-17-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (8.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 23cadddf-5002-4f61-9b06-032b924ce5a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by sean-mcmanus** [comment]
We have 4 or so upvotes on this in regards to the C/C++ extension, but it appears to be a regression with VS Code Insiders and not our extension (i.e. older version of our extension have the same issue).

**Comment by Tyriar** [comment]
@sean-mcmanus going to need a little help here, I created a folder with this:

```
#include <iostream>

int main() {
    std::cout << "abc";
}
```

Pressed F5 and selected g++ (macOS) and it worked fine. Any more details on the repro?

**Comment by anatolyburakov** [comment]
I can reproduce this failure for all of my projects on a remote Linux. See: https://github.com/microsoft/vscode-cpptools/issues/7551

**Comment by Tyriar** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/124116

/duplicate
