### ISSUE TITLE
encodeURIComponent has wrong description

### ISSUE THREAD

**Issue by chocolateimage** [microsoft/vscode#124188]
Issue Type: <b>Bug</b>

![image](https://i.imgur.com/LDgNkVU.png)
Description is wrong

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.37GB free)|
|Process Argv|--crash-reporter-id 299f509d-242e-4b5f-93aa-88543cc5c087|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
fivem-lua|dha|1.0.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|6.3.1
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.6
vscode-cdnjs|Jak|0.19.0
Lua|key|0.0.9
ftp-sync|luk|0.3.9
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
material-icon-theme|PKi|4.6.0
vscode-data-preview|Ran|2.3.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
es6-string-html|Tob|2.8.0
vscode-icons|vsc|11.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
How so?

**Comment by roblourens** [comment]
I guess it should be "representing an unencoded URI component" or something, is that what you are pointing out?
