### ISSUE TITLE
XML and JSP rendering problems

### ISSUE THREAD

**Issue by heliodeveloper** [Microsoft/vscode#12412]
- VSCode Version: 1.5
- OS Version: Windows 7

Steps to Reproduce:

1. <%-- this comment doesn't work on jsp files --%>
2. \<project.version\>1.0\</project.version\> renders wrong on xml files.

**Comment by chrmarti** [comment]
Please file one issue per issue 👍 

We detect JSPs as HTML, please open a new issue for that. Using this to track the XML highlighting bug:
![screen shot 2016-09-22 at 8 37 09 am](https://cloud.githubusercontent.com/assets/9205389/18755120/c85b3f80-809f-11e6-95fb-fbc42ff02cd7.png)

**Comment by aeschli** [comment]
XML issue is #13193.
I can remove the jsp association with the HTML mode, but we end up without any support for jsp.
From what I see, the html mode is still useful.

**Comment by heliodeveloper** [comment]
No, don't remove the HTML association. I just thought that would be possible to support templating languages like JSP and PHP.
