### ISSUE TITLE
a feature suggestion for exiting

### ISSUE THREAD

**Issue by FE-ng** [microsoft/vscode#124155]
I think vscode needs a detection mechanism to prevent it from exiting due to accidentally touching commad + Q (mbp), just like chrome done.
![image](https://user-images.githubusercontent.com/30992215/118755305-36935900-b89b-11eb-8e5b-903dd917301f.png)

**Comment by Tyriar** [comment]
You can use these keybindings to do something very similar:

```
{ "key": "cmd+q",            "command": "-workbench.action.quit", "when": "isMac" },
{ "key": "cmd+q cmd+q",      "command": "workbench.action.quit", "when": "isMac" },
```

**Comment by FE-ng** [comment]
Thanks for giving this solution .
It can indeed handle this problem but when the first “cmd+q” is pressed,
we didn't get feedback .
So if the exit method can be like chrome having some feedback,  it will be
more friendly to developers .
How do you think so ？

Daniel Imms ***@***.***> 于2021年5月25日周二 下午9:26写道：

**Comment by FE-ng** [comment]
On the other hand, I think that such a configuration should be in vscode by
default personally.In order to avoid misoperation like me.
Looking forward to your reply.

Eng F ***@***.***> 于2021年5月26日周三 下午1:59写道：

**Comment by Tyriar** [comment]
I've suggested this before but think it was rejected because it's still non-standard behavior on mac

**Comment by FE-ng** [comment]
I think there is no absolute standard especially for such user experience
issues .
Not only chrome but also iTerm2 has a secondary confirmation function to
exit .
Why don't we initiate a poll to ask more developers ？

I found another way to solve my problem  when I searched for similar
issues just now.
Google gave me a software for mac called SlowQuitApps ,Although I still
hope that vscode can launch such a feature.
Anyway, thank you very much for discussing this issue with me.

Daniel Imms ***@***.***> 于2021年5月26日周三 下午9:43写道：
