### ISSUE TITLE
Search icon on the sidebar not showing shortcut inside tooltip

### ISSUE THREAD

**Issue by dev-song** [microsoft/vscode#124146]
Does this issue occur when all extensions are disabled?: Yes (Insiders is checked as well)

- VS Code Version: 1.56.0
- OS Version: Windows 10 Home 20H2 19042.964

Steps to Reproduce:

1. Open VS Code
2. Hover mouse cursor on `search` icon, on sidebar

**Comment by roblourens** [comment]
I am missing it from the View menu too. Didn't we just fix that somehow?

**Comment by JacksonKearl** [comment]
Yeah..

**Comment by JacksonKearl** [comment]
Looks like this regressed way back in https://github.com/microsoft/vscode/commit/e94d5c783983fd144ce5fe74409e060169745e36. The keybinding service "forgets" any binding that is overwritten at a higher priority level... so if we have two actions, A & B, both with the same keybinding, but A is higher priority than B, then asking the keybinding registry for B's keybinding will give `null`. This feels wrong, but it's been around for a while now so I don't think it should change. 

The workaround from before (setting them both to the same priority level, but giving one a regex-based context key expression that never matches) works, but it's a bit weird to look at. cc @alexdima and @sandy081 if you have any suggestions here.

To summarize the problem... 

We have two actions: `workbench.action.findInFiles`, and `workbench.views.search`, both with Cmd+Shift+F as a keybinding. Ideally, we'd only give `workbench.action.findInFiles` the binding, as that handles the case of a user configuring `search.mode` to use a search editor by default, but the general views machinery labels the view container's title with the keybinding from `workbench.views.search`, and that's also the binding that goes in the `view=>search` menu. So we need to give them both the binding, but it should always dispatch to `workbench.action.findInFiles`. If we give `workbench.action.findInFiles` higher priority, then the keybinding service will forget that `workbench.views.search` also has the same keybinding. 

I went ahead and changed `workbench.views.search`'s `when` back to the weird regex thing, as this does not prevent it from appearing in the menus/tooltips, but does stop it from being dispatched to. If anyone has any better ideas I'd love to hear, this seems to be the only approach that does not break one of #116188, #115556, #115511, and now #124146, and the only downside is that the entry in the settings editor is a bit odd to look at.

**Comment by alexdima** [comment]
To make sure I understood it: you have two actions, `action1` and `action2` and `action1` sometimes calls `action2` in its implementation. So you would like that looking up the keybindings for `action2` would contain the keybindings for `action1`.

I don't think I've seen quite such a use-case before and we don't model this in any way in the `CommandService`...
