### ISSUE TITLE
Dart Server crash 

### ISSUE THREAD

**Issue by vmanik2k** [microsoft/vscode#124108]
Issue Type: <b>Bug</b>

Dart server on my system is crashing from past 6 days saying the same thing "Connection to server got closed. Server will not be restarted."

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.65GB free)|
|Process Argv|--crash-reporter-id 74514457-aba3-480b-a021-89543c3ff049|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
crypto-ticker|cal|1.2.0
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.21.1
flutter|Dar|3.22.0
vscode-eslint|dba|2.1.20
javascript-ejs-support|Dig|1.3.1
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|6.4.0
bloc|Fel|5.6.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.10
vscode-flutter-files|gor|3.1.2
todo-tree|Gru|0.0.213
stylelint-plus|hex|0.53.4
json-to-dart|hir|3.1.5
discord-vscode|icr|5.6.3
pubspec-assist|jer|2.2.1
vscode-gutter-preview|kis|0.27.1
flutter-intl|loc|1.15.0
flutter-tree|mar|1.0.0
vscode-language-babel|mgm|0.0.31
mssql|ms-|1.10.1
vsliveshare|ms-|1.0.4272
awesome-flutter-snippets|Nas|2.0.4
color-highlight|nau|2.3.0
dartgettersetter|Pet|1.0.2
material-icon-theme|PKi|4.6.0
java|red|0.79.1
LiveServer|rit|5.6.1
errorlens|use|3.2.6
vscodeintellicode|Vis|1.2.13
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vscode-icons|vsc|11.4.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by vmanik2k** [comment]
[Info  - 7:08:44 PM] Connection to server got closed. Server will restart.
[Info  - 7:08:56 PM] Connection to server got closed. Server will restart.
[Info  - 7:09:08 PM] Connection to server got closed. Server will restart.
[Info  - 7:09:18 PM] Connection to server got closed. Server will restart.
[Error - 7:09:30 PM] Connection to server got closed. Server will not be restarted.

**Comment by roblourens** [comment]
Please open this issue on the Dart extension repo
