### ISSUE TITLE
Lack of documentation for setting up launch.json with attach to existing process

### ISSUE THREAD

**Issue by andrei-pokrovsky** [microsoft/vscode#124123]
There's currently very little documentation and apparently no working sample on how to setup launch.json for attach to existing process. I spent hours researching the internet but am still unable to set it up even for a basic case.

**Comment by roblourens** [comment]
What language are you debugging?

**Comment by andrei-pokrovsky** [comment]
Hi, thank you for responding. It's C++.
To give you a better idea what i'm talking about i started off just searching documentation for 'attach' and the information for a complete process was not quite there. I ended up with this launch.json:

```
{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch mpi+attach",
            "type": "cppdbg",
            "request": "attach",
            //"preLaunchTask": "x",
            //"processName": "/home/apokrovsky/git/my_app",
            //"processId": "${command:PickMatchedProcess}",
            //"miDebuggerServerAddress": "localhost:4444",
            //"processId": "${command:pickRemoteProcess}",
            //"processId": 908905, 904283,//"${command:pickProcess}",
            //"processId": "${command:pickProcess}",
            "processId": "${input:myAppMatcher}",
            "program": "/home/apokrovsky/git/my_app",
            "MIMode": "gdb",
            "setupCommands": [ {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
            } ]
        }
    ],
    "inputs": [
        {
          "id": "myAppMatcher",
          "type": "command",
          "command": "process-matcher.match",
          "args": { "program": "myapp" }
        }
    ]
```

So there's quite a bit of required boilerplate to get this going properly. Just specifying processID every time you launch by itself is a rather inconvenient process. But also even things like having to specify both the application and processid are not very intuitive and there's no complete launch config example with attach that I could find in the documentation.

HTH

**Comment by weinand** [comment]
@andrei-pokrovsky thanks for providing the details.

Please note that the launch.json properties are debug-extension specific. So VS Code cannot provide a generic documentation for how to "attach to a process".

Please file this issue against the C++ extension.
