### ISSUE TITLE
Syntax highlight error in js code

### ISSUE THREAD

**Issue by ihgsm** [Microsoft/vscode#12413]
- VSCode Version: 1.5.2
- OS Version: Win10

Steps to Reproduce:

1. In any existing JavaScript code type this: `(n<<t )`. Make sure there is a space after the t.
2. Check the syntax highlighting of the rest of the code, all the text that supposed to be white are now in dark grey. (using Dark+ color theme)

**Comment by chrmarti** [comment]
![screen shot 2016-09-22 at 8 41 17 am](https://cloud.githubusercontent.com/assets/9205389/18755260/5cf3ab6e-80a0-11e6-8f1a-fec2e50664a4.png)

**Comment by staralfurbe** [comment]
I've a very similar issue, i assume the root cause is the same. 

In js code within a php file, "<" followed by any character will cause the same color problem for the rest of file.
![image](https://cloud.githubusercontent.com/assets/20887056/18844244/d251ac2e-841c-11e6-813b-ded2b9918c54.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#298
