### ISSUE TITLE
Integrated Terminal: Horizontal padding is too large in vertical orientation

### ISSUE THREAD

**Issue by mgreenw** [microsoft/vscode#124101]
Version: 1.56.1
OS: macOS 11.2.3

## Feature Request
Add a new setting to customize the integrated terminal's horizontal padding such that it can match the pre-1.56 padding.

## Background
Before 1.56, the integrated terminal had a very small horizontal padding, which matched the built-in terminal and the ever popular iTerm 2. However, 1.56 added quite a bit of horizontal padding to the integrated terminal, which (in my opinion and very subjectively) reduces the amount of space I have to work with. 

It's very possible this setting already exists, or I am missing some other configuration to change this. If so, please let me know and I will close this!

## Screenshots
VSCode 1.56:
![Screen Shot 2021-05-18 at 8 22 01 AM](https://user-images.githubusercontent.com/2615374/118650202-2fdce700-b7b2-11eb-9e45-6e25ee785e79.png)

iTerm 2 (and VSCode before 1.56):
![Screen Shot 2021-05-18 at 8 22 17 AM](https://user-images.githubusercontent.com/2615374/118650237-3703f500-b7b2-11eb-904f-45479d051494.png)

**Comment by Tyriar** [comment]
This actually looks like a regression for vertical orientation terminal panels

**Comment by Tyriar** [comment]
1.55 (10px):

<img width="320" alt="Screen Shot 2021-05-18 at 11 52 45 AM" src="https://user-images.githubusercontent.com/2193314/118707628-9ae8e680-b7cf-11eb-944c-dc03283a7b45.png">

**Comment by mgreenw** [comment]
@Tyriar thanks for the super-quick response time on this!

**Comment by Tyriar** [comment]
Thanks for the report, I wouldn't have noticed this 👍
