### ISSUE TITLE
Crash vscode tool

### ISSUE THREAD

**Issue by tuoitrexuquang** [Microsoft/vscode#12417]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Update latest version
2. Open a folder project
3. Open some file .ts  on this project
4. Wait 2~3 minutes after, it''s crash and one popup show with info
![image](https://cloud.githubusercontent.com/assets/17606940/18735333/34ab2108-80a7-11e6-9568-afe3cb2c5992.png)

Thanks

**Comment by chrmarti** [comment]
What are the extensions you have installed?

Does this occur only with specifc .ts files or with all?

**Comment by tuoitrexuquang** [comment]
Hi Chrmart. 
It's occur all files. 
And bellow is extensions i'm using
![image](https://cloud.githubusercontent.com/assets/17606940/18772404/d51119e4-8170-11e6-99ae-2fcfb36c04da.png)

**Comment by chrmarti** [comment]
That seems to be the list of built-in extensions. Which ones have you installed yourself? (You could run `code --list-extensions`.)

**Comment by tuoitrexuquang** [comment]
Bellow is all extensions installed chrmarti
abusaidm.html-snippets                                                                                                                                                                               
aeschli.vscode-css-formatter                                                                                                                                                                         
anseki.vscode-color                                                                                                                                                                                  
danwahlin.angular2-snippets                                                                                                                                                                          
dbalage.vscode-stylesheet-formatter                                                                                                                                                                  
DSKWRK.vscode-generate-getter-setter                                                                                                                                                                 
jakethashi.vscode-angular2-emmet                                                                                                                                                                     
johnpapa.Angular2                                                                                                                                                                                    
kasperkeso.es6-angular-snips                                                                                                                                                                         
lonefy.vscode-JS-CSS-HTML-formatter                                                                                                                                                                  
michelemelluso.code-beautifier                                                                                                                                                                       
mrmlnc.vscode-attrs-sorter                                                                                                                                                                           
mrmlnc.vscode-jade-snippets                                                                                                                                                                          
msjsdiag.debugger-for-chrome                                                                                                                                                                         
robinbentley.sass-indented                                                                                                                                                                           
seanmcbreen.Spell                                                                                                                                                                                    
steve8708.Align                                                                                                                                                                                      
UVBrain.Angular2                                                                                                                                                                                     
vivainio.jadeview                                                                                                                                                                                    
wcwhitehead.bootstrap-3-snippets                                                                                                                                                                     
wmaurer.html2jade                                                                                                                                                                                    
xabikos.JavaScriptSnippets                                                                                                                                                                           
Zignd.html-css-class-completion                                                                                                                                                                      
ziyasal.vscode-open-in-github 

Thanks

**Comment by mrmlnc** [comment]
Hello, @tuoitrexuquang,

Have you tried to run the editor without extensions by `code . --disable-extensions`? I think the problem is related to `Zignd.html-css-class-completion`.

**Comment by tuoitrexuquang** [comment]
Hummm, sorry, i run code . --disable-extensions and still crash

**Comment by chrmarti** [comment]
@tuoitrexuquang There is still a chance this is Zignd/HTML-CSS-Class-Completion#12. Could uninstall `Zignd.html-css-class-completion` (`code --uninstall-extension Zignd.html-css-class-completion`) and retry?

**Comment by tuoitrexuquang** [comment]
It's OK now. Thanks all,
