### ISSUE TITLE
Editor highlights across notebook cells are merged and shown in current notebook cell editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#124195]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0-insider 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create a notebook with >=2 cells with text in them, e.g. 
```python
import pandas as pd 
df = pd.read_csv('foobar')
```
and
```python
pd.read_clipboard()
```

2. Highlight `pd` in the first cell. A highlight corresponding to the column start and end of `pd` in the __second__ cell is also applied to the first cell editor:
![recording (1)](https://user-images.githubusercontent.com/30305945/118850043-325c4100-b885-11eb-83dc-e9ac4db25405.gif)

**Comment by roblourens** [comment]
I think these are coming from the language service. Are you using pylance?

**Comment by joyceerhl** [comment]
You're right, disabling Pylance fixes the problem. Thanks @roblourens :)
