### ISSUE TITLE
VS Code Browser version can't open on Chrome 86

### ISSUE THREAD

**Issue by conwnet** [microsoft/vscode#124199]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 browser version
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Open Chrome 86 (or earlier versions)
2. Open VS VS Code Browser Version

This should be a bug for earlier version's chrome:

~~~javascript
new Worker(URL.createObjectURL(new Blob([`
    var s = trustedTypes.createPolicy('test', { createScript: i => i }).createScript('() => {}');
    console.log(self.eval(s));
`])));
~~~

Above codes should print a lambda function: `() => {}`, but on chrome 86 (or earlier versions), it prints `TruestedScript {}`.

So below codes will be breaked in earlier browsers:

https://github.com/microsoft/vscode/blob/HEAD/src/vs/base/worker/workerMain.ts#L47

**Comment by roblourens** [comment]
I don't recommend using old versions of chrome

**Comment by jrieken** [comment]
Latest Chrome is 90 and we don't support old versions. Closing without code change
