### ISSUE TITLE
Add issue comment action /needsMorePerfInfo

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#124100]
I was inbox tracker last week and I several times had to add comment with a link to the performance guide, e.g., https://github.com/microsoft/vscode/issues/123935#issuecomment-841626941

What would be nice is to have a comment action `/needsPerfInfo` or label that insert this comment with a link to the performance guide for me, e.g.,

**Comment by JacksonKearl** [comment]
2b30689ab00bfcc24e2072eb1dbbe3f2a582a359

**Comment by gjsjohnmurray** [comment]
@JacksonKearl please update https://github.com/microsoft/vscode/wiki/Community-Issue-Tracking so it lists the new action instead of its current suggestion of appending a wiki link to the generic /needsMoreInfo

**Comment by gjsjohnmurray** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

Oops! I assumed action keywords only triggered at the beginning of a line.

**Comment by JacksonKearl** [comment]
Haha, yeah it's overly strict in some areas and overly loose in others.. I updated the doc, thanks for the suggestion!
