### ISSUE TITLE
Remote / dev containers tabs appear empty with integrated terminal tabs

### ISSUE THREAD

**Issue by davetapley** [microsoft/vscode#124138]
Does this issue occur when all extensions are disabled?: No (because need `remote-containers`)

- VS Code Version: 1.56.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Have `"terminal.integrated.tabs.enabled": true`
1. [Configure containers for remote host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)
2. Open folder containing a `.devcontainer.json` having a `postCreateCommand` 
3. Choose to open and clone in container
4. Observe tabs with no content:
     ![image](https://user-images.githubusercontent.com/48232/118734850-16f52580-b7f4-11eb-972a-c0b8569ea759.png)

On hover these tabs say `Dev Containers` and `Configuring...`

**Comment by davetapley** [comment]
Might be dupe of #122227

**Comment by Tyriar** [comment]
Yep this should be fixed now, there were a couple of issues we fixed related to this 👍
