### ISSUE TITLE
Auto complete ruines my code

### ISSUE THREAD

**Issue by digimbyte** [microsoft/vscode#124109]
Issue Type: <b>Bug</b>

Autocomplete has been severely degrading to my experience. Trying to create  `export default generate()` before I have programmed the function and it wants to auto-complete it to the following when I hit "(" 
```
import { generateKeyPair } from "crypto";
export default generateKeyPair
```
- I am not triggering auto-complete with `;` or `TAB`

I've also needed to insert a string before a variable in a function
I start typing and intellisense suggests the correct word, but then proceeds to DELETE the entire proceeding line of where I was trying to insert the new value

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (20.65GB free)|
|Process Argv|C:\\Firebase Me\\firebase-me-services --crash-reporter-id e53f07e8-85dc-40d0-ab99-073057a66da9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.4.0
todo-tree|Gru|0.0.213
solidity|Jua|0.0.113
ignore-files|lde|0.1.0
powershell|ms-|2021.2.2
vetur|oct|0.33.1
vscode-gitignore-generator|pio|1.0.3
json-helper|pra|1.0.1
vscode-vyper|tin|0.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by mjbvz** [comment]
Please describe the exact steps you are taking that cause this

**Comment by digimbyte** [comment]
The exact steps are typing in
`export default generate(`
as soon as I type the `(` character, it auto completes with the top suggestion

**Comment by digimbyte** [comment]
a secondary issue with autocomplete
inserting a string inside a variable will modify the text after the cursor
`myfunction (userName)`
editing the first input in a function to contain a string will delete the `userName` with intellisense 
expected `myfunction ("global.userflag", userName);`
actual result `myfunction ("global.userflag"`

**Comment by digimbyte** [comment]
https://user-images.githubusercontent.com/6645396/118963254-9c6e0680-b9a9-11eb-932c-93c9e619596e.mp4

**Comment by mjbvz** [comment]
This is because `(` is a commit character that accepts the current suggestion 

You can disable them with `"editor.acceptSuggestionOnCommitCharacter": false`

**Comment by digimbyte** [comment]
and what about not respecting the cursor position for auto-complete? where auto-complete deletes items on the right side of the cursor like variables.
is that a feature?
