### ISSUE TITLE
Python Linting errors after update to 1.56.2 on Ubuntu

### ISSUE THREAD

**Issue by vincentoconnell** [microsoft/vscode#124198]
Issue Type: <b>Bug</b>

As of update to 1.56.2 this morning, linters are not working in my workspace. No changes have been made to the workspace.

I tried recreating the venv from scratch with the latest version of pip, which did not solve the problem.

Behaviours seen:
    - pycodestyle not run at all
    - pylint missing some errors, but not all

Steps to recreate:

1. create new python file
2. type the following lines which break PEP8 standards:
import json
import json
class A():
    def doThingA(self):
        print("bad formatting")

Expected behaviour: pycodestyle should highlight the lack of blank lines before the class definition. pylint should highlight the duplicate import.
Behaviour Seen: No highlighting.

Python version:
Python 3.8.5

Running project inside a Python virtual environment

workspace settings:

{
    "python.pythonPath": "<project-path>/venv/bin/python3",
    "python.linting.pylintEnabled": true,
    "python.linting.pycodestyleEnabled": true,
    "python.linting.pycodestyleArgs": ["--E501"],
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/venv/**": true,
        "**/.aws-sam/**": true
      }
}

pip list:
Package           Version
----------------- -------
aiofiles          0.6.0
aiologger         0.6.1
aioredis          1.3.1
astroid           2.5.6
async-timeout     3.0.1
AWSIoTPythonSDK   1.4.9
hiredis           1.1.0
isort             5.8.0
lazy-object-proxy 1.6.0
mccabe            0.6.1
pip               21.1.1
pkg-resources     0.0.0
pycodestyle       2.7.0
pylint            2.8.2
setuptools        44.0.0
toml              0.10.2
wrapt             1.12.1

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 4281)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (0.71GB free)|
|Process Argv|--no-sandbox --unity-launch /home/vincent/workspace/baselink-project/baselink_iot --crash-reporter-id 745b7864-8ddf-4364-b7fb-76a10fdab9ff|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.6
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.213
git-graph|mhu|1.30.0
python|ms-|2021.5.842923320
jupyter|ms-|2021.6.832593372
vscode-yaml|red|0.19.0
gitblame|wad|7.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
