### ISSUE TITLE
VSCode uninstalled itself with Windows Update

### ISSUE THREAD

**Issue by metagrapher** [microsoft/vscode#124153]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: Edition	Windows 10 Pro
Version	Dev
Installed on	‎5/‎14/‎2021
OS build	21382.1
Experience	Windows 10 Feature Experience Pack 321.12100.0.3

Steps to Reproduce:

1. Have VS Code installed and up to date as of 5/14/2021
2. Update Windows 10 to OS build	21382.1

**Comment by metagrapher** [comment]
I would have included the VS Code Version number, but you see, the software disappeared completely from my computer all on its own, so outside of knowing it was updated, I cannot check the version number without a time machine.

I have installed the Insider Preview build now, so that if there were files left behind I might be able to find them. I'll be happy to provide any additional info.

**Comment by joaomoreno** [comment]
#52855

**Comment by metagrapher** [comment]
This does not fit my use case. VSCode was not updating nor open at all when Windows updated. I have no _ folder either. This has been inappropriately closed. 

Thank you.
