### ISSUE TITLE
workbench.editorAssociations malformed prevents files from being open

### ISSUE THREAD

**Issue by austingross** [microsoft/vscode#124140]
Issue Type: <b>Bug</b>

I can't open any files from directories. When I try to create a new file, either from menu or with keyboard shortcut, nothing happens. When double clicking on the editor pane a new file will show up.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.78GB free)|
|Process Argv|--crash-reporter-id 79309763-1636-42d6-9cc6-8d377215e1d7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscoreces:30290705
vscus158cf:30286554
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by austingross** [comment]
Insiders is working fine. I've uninstalled all my extensions and still can't open any files. When trying the shortcut for new file (ctrl + n) I get the following notification: `(this.configurationService.getValue(...) || []).filter is not a function`.

**Comment by austingross** [comment]
Fixed it! There was a bad setting in my `settings.json`. I deleted the file and things work properly now. Thanks for the help.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/124012

What was the bad setting, can you share it. Since we should still be able to open files even if you have a broken setting

**Comment by austingross** [comment]
This block here is causing a notification in the settings pane, 'Setting has an invalid type, expected "array". Fix in JSON.'
```
    "workbench.editorAssociations": {
    
        "*.ipynb": "jupyter-notebook"
    },
```

**Comment by 4310V343k** [comment]
Reproducible. Change workspace or user settings.json so it includes this setting
```json
"workbench.editorAssociations": {
			"*.$any": "$any"
		},
```
I think some update changed this setting from using dictionaries to an array of dictionaries.

**Comment by lramos15** [comment]
This is a bug in 1.56.2 that doesn't exist in 1.57. It has to do with the setting being changed and all the recovery logic not existing in 1.56.2. The only reason people see this in stable is because they have setting sync enabled to the stable channel.
