### ISSUE TITLE
Funny Text Selection Bug (or productive Hack)

### ISSUE THREAD

**Issue by liquididea** [microsoft/vscode#124197]
Does this issue occur when all extensions are disabled?: Yes
![Animation](https://user-images.githubusercontent.com/37738474/118859461-8c3b2600-b8da-11eb-8b37-3465c960d6e8.gif)

- VS Code Version: 1.56.2
- OS Version:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎06/‎05/‎2021
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

Steps to Reproduce:

1. Click on your code in VS Code with your mouse wheel (middle key pressed) 
2. Select random Text
3. Type on your keyboard

**Comment by IllusionMH** [comment]
/question

This is intended behavior for middle mouse selection https://code.visualstudio.com/updates/v1_23#_column-selection-using-middle-mouse-button
It's same as https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection
