### ISSUE TITLE
Terminal `onLineData` has unexpected line breaks

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#124113]
You can repro this with really any task on Windows, but I discovered this while building vscode:

1. Open your clone of microsoft/vscode
2. Start the build task with ctrl+shift+b
3. Open the developer tools and make your tasks terminal "small"
4. Put a break point here:

https://github.com/microsoft/vscode/blob/5246162662ffa9f16a70dc2b94f13b0d15511e64/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L804-L805

5. Make a change in a file that causes errors
6. Expected: `onLineData` will fire with wrapped lines unwrapped.
    Actual: `onLineData` fires with individual line segments, broken along where they wrap.

Line wrapped file links also appear to be broken in the terminal, possibly related?

I have `terminal.integrated.windowsEnableConpty` set to `true` and I'm on Windows build 19043.

**Comment by meganrogge** [comment]
Thanks for the issue. It is working for me with windows build number: 21376. I'm going to adjust the conditional to make sure Windows Mode is used for versions below that.

**Comment by alexr00** [comment]
Looks good, thanks!
