### ISSUE TITLE
Trailing comma error in settings.json

### ISSUE THREAD

**Issue by mosfetish** [microsoft/vscode#124141]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open settings (ctrl+,) in split view
2. Problem appears as per image
3. Close settings and reopen, second trailing comma problem is added, rinse and repeat for more errors
4. Reload Code and multiple trailing comma errors are reduced to single error

Issue seems to have occurred after updating to v1.56.2

Hover over error shows errors in files named \0\settings.json, \2\settings.json, \3\settings.json, etc. These files are not present when searching and can't be edited as they are read-only.

![image](https://user-images.githubusercontent.com/6182539/118739817-7c055580-b89e-11eb-9bb2-884a7917ecef.png)

**Comment by roblourens** [comment]
There is something wrong with this file if it ends with `]`. Can you share more context?

**Comment by roblourens** [comment]
Never mind, I see it

**Comment by roblourens** [comment]
Any idea @sandy081?

**Comment by roblourens** [comment]
Yes, thanks
