### ISSUE TITLE
Sentry sdk reports unrelated extension exceptions & promise rejection and console output 

### ISSUE THREAD

**Issue by riotrah** [microsoft/vscode#124142]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Win10 19041

Steps to Reproduce:

1. Create a vscode extension with a language server.
2. Install Sentry in the extension and language server.
3. Publish the extension.
4. Watch the Sentry.io dashboard for exceptions or console breadcrumbs that could not be from your extension, or have stack traces originating in eg. `at e.exports (~/.vscode/extensions/atlassian.atlascode-2.8.6/build/extension/extension.js:1:535294)`.

How can my extension, or Sentry within it, see exceptions thrown by other extensions or their console output? 
I know that the Sentry sdk uses `process.onUnhandledException`, `process.onUnhandledPromiseRejection` and `global.console` during installation. But shouldn't these be scoped to my extension?

What information can I provide in this issue description to better describe my problem?

**Comment by sandy081** [comment]
Not sure if we can help with Sentry sdk, can you please report issue against Sentry sdk.
