### ISSUE TITLE
ctrl+tab shortcut key to work like browser

### ISSUE THREAD

**Issue by jimmycanosa** [microsoft/vscode#124114]
Feature request to change the behavior of ctrl+tab in switching from tab to tab like switching tabs in a browser (like edge, chrome, firefox).  Just cycle the opened tabs and don't show widget of opened tabs because selecting from a list of opened tabs is quite confusing. Just switch the tabs directly in a cycle.

**Comment by abhijit-hota** [comment]
I believe <kbd>alt</kbd> + <kbd>tab</kbd> already does this.

**Comment by jimmycanosa** [comment]
I cant believe you dont know what alt+tab shortcut does.

It takes you to another opened app not in your tabs inside vscode.

**Comment by abhijit-hota** [comment]
@jimmycanosa 
Yep, I'm aware of that. But I use alt + tab on a daily basis inside VSCode for the same purpose.

Maybe I've set up a custom keybinding and has mistaken it for a default one.

**Comment by sagarpanchal** [comment]
It was a stupid decision to change the default `ctrl + tab` behavior without asking.

- press `ctrl + shift + p`
- search and open `Preferences: Open Keyboard Shortcuts (JSON)`
- add following lines in the file
```
  { "key": "ctrl+tab", "command": "workbench.action.nextEditor" },
  { "key": "ctrl+shift+tab", "command": "workbench.action.previousEditor" },
```
