### ISSUE TITLE
Select Interpreter Python VSC

### ISSUE THREAD

**Issue by francescowang** [microsoft/vscode#124107]
Issue Type: <b>Bug</b>

I can't select my virtual environment on "Select Interpreter".

So, I activated my virtual environment using:

python -m venv .venv
source .venv/bin/activate

this works until I close VSC. After reopening VSC, I can't see the Path to the virtual environment on "Select Interpreter". 

I already tried changing the python.Path on user settings.json but to no avail. 

I have to manually input ./.venv/bin/python on "Select Interpreter", which is time-consuming. Why can't I see all Python versions and Interpreters on "Select Interpreter"? Even if I click on the refresh button, it doesn't work. 

Thank you.

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 500524f1-140d-47bb-9f25-bbc30bab1c2c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
kivy-vscode|Bat|0.5.5
vsc-python-indent|Kev|1.14.2
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.832593372
indent-rainbow|ode|7.5.0
vscode-icons|vsc|11.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
