### ISSUE TITLE
Use emmet to generate "a" tags cannot wrap automatically

### ISSUE THREAD

**Issue by victory-vcc** [microsoft/vscode#124148]
Issue Type: <b>Feature Request</b>

When I write code with Emmet, the a tags generated by "a * 6" are all in one line, which can not be changed automatically, which brings great trouble to my work, but VSC1.52 can wrap lines automatically.

VS Code version: VSCodium 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-09T16:03:54.032Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rzhao271** [comment]
Hi, can you try the following:
1. Run the "workbench.action.openSettingsJson" command in the command palette
2. Paste in the following config:
```json
    "emmet.preferences": {
        "output.inlineBreak": 1
    },
```
This makes all inline tags (such as `a` and `span`) break after each occurrence of the tag.
