### ISSUE TITLE
[folding][json] show number of collapsed array items

### ISSUE THREAD

**Issue by faicalcarvalho** [microsoft/vscode#124177]
Issue Type: <b>Feature Request</b>

When the mouse hovers an ellipsis sign that represents a collapsed literal array, the editor would display a small popup window showing the number of elements in the array.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by daleyjem** [comment]
@faicalcarvalho Sorry I can only make the upvote 2 now. The only alternative I know of is to select the line of the opening bracket `[`, then <kbd>Cmd/Ctrl + F</kbd> to find the first closing bracket `]` (or prefix with the number of spaces if it's a nested array)... and finally select the last array item to see the last index here:

![image](https://user-images.githubusercontent.com/1498514/128116463-ed5174a7-a211-4da3-bf08-044c057e215e.png)

I don't know why they couldn't just put the length inside these brackets:

![image](https://user-images.githubusercontent.com/1498514/128116353-05b50ad7-88f9-40d4-8b78-a25ca55e0b28.png)

**Comment by NathanielRN** [comment]
Would be nice to see something like the GitLens "grey text" with the number of elements next to the folded array:

![image](https://user-images.githubusercontent.com/23139455/129059128-7712e35b-e40d-4146-b803-8b96c17ffa96.png)
