### ISSUE TITLE
Introduce an option to terminal options to be visible all the time.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#124103]
Can terminal options be visible all the time with option in settings? It's right now shows when mouse hover.

![image](https://user-images.githubusercontent.com/17777237/118650894-3c2e6780-b7e5-11eb-97bd-a9327a8ae66c.png)

**Comment by Tyriar** [comment]
Do you mean only the active terminal, not all of them? Note that it's on hover of keyboard focus. This was a change compared to other lists but I think we should do it there too. See https://github.com/microsoft/vscode/issues/122016

**Comment by pixieaka** [comment]
If you can add both as an option it 'll fit more users preferences.

**Comment by pixieaka** [comment]
@Tyriar If you can add both as an option it 'll fit more users preferences. But I personally prefer all of them available.

**Comment by Tyriar** [comment]
Sorry I don't think we will do this because of the additional visual noise is will cause, and I don't believe the amount of usage this will see is worth the cost of another setting.
