### ISSUE TITLE
windows terminal can't start after closing

### ISSUE THREAD

**Issue by nghiatle** [microsoft/vscode#124167]
Issue Type: <b>Bug</b>

windows terminal can't start after closing

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.21382

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.44GB free)|
|Process Argv|D:\\Lab\\Ecommerce-1\\frontend --crash-reporter-id 8727fa38-f052-4051-af93-48428b62b1f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.0.1
path-intellisense|chr|2.3.0
docs-markdown|doc|0.2.92
jquerysnippets|don|0.0.1
vscode-generate-getter-setter|DSK|0.5.0
remote-wsl|ms-|0.56.2
material-icon-theme|PKi|4.6.0
autoimport|ste|1.5.4
bootstrap4-vscode|the|6.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
