### ISSUE TITLE
Conda & vs-code

### ISSUE THREAD

**Issue by peter197321** [microsoft/vscode#124106]
After the integrated terminal is invoked with conda environment (`ctrl+shift+P`) there is a terminal and conda seems working fine but its indication (`base`) is not shown or I can't switch for another virtual environment - just `base` works... 

How can I enable another conda environment?
How can I get an indication of what the environment is active?

**Comment by roblourens** [comment]
Is this a Python feature?

**Comment by peter197321** [comment]
I use the integrated terminal of vs-code and invoking  `python interpreter` from conda tool. Its command-line tool (no vs-code) can be run `anaconda prompt` and yes it is a feature `(base) C:\Users\>`

**Comment by csghone** [comment]
Ctrl + Shift + P -> Python: Select Interpreter -> Choose from the dropdown.
Active interpreter is also shown in bottom status bar usually - If not, right click on bottom status bar and select `Python (extension)`

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
