### ISSUE TITLE
Enhance onAutoForward port attributes for devcontainer

### ISSUE THREAD

**Issue by morganpizzini** [microsoft/vscode#124160]
When running VSCode in container I can choose to automatically open the browser by setting the code below inside devcontainer.json
```
"portsAttributes": {
   "5001": {
	"label": "API port",
	"onAutoForward": "openBrowser"
   }
}
```
But this led me to an unwanted event when I run any _watch_ command like

```
dotnet watch run
```
Everytime the project re-compile a new browser window is opened, would be better to have something like

```
"portsAttributes": {
   "5001": {
	"label": "API port",
	"onAutoForward": "openBrowserOnce"
   }
}
```
In that way the browser is open just the first time I forward the port.
At the moment I run with silent option, which is perfect except for the first run

**Comment by alexr00** [comment]
`openBrowserOnce` would open the browser **once per vscode "session"**. If you reload/restart/close-reopen vscode and the port gets auto forwarded again the browser would be opened again. If you close the browser, but don't reload/restart/close-reopen vscode then the browser **will not** be opened again.

**Comment by morganpizzini** [comment]
Exactly, my issue depends on _watch_ command, when I run it inside containers, every time it re-compiles the code, the server restarts, and a new browser window is opened. Would be perfect have the "once per vscode session" or even, but I think much more complicated "once per integrated terminal session".

**Comment by alexr00** [comment]
`openBrowserOnce` will only re-open the browser if the port's local address has changed (i.e., if something else is using the matching local port so the local address ends up with a random port).
