### ISSUE TITLE
I-Beam needs enhancement

### ISSUE THREAD

**Issue by rhires** [microsoft/vscode#124133]
The I-Beam on Windows is nearly invisible. The screen shot here was taken w/ my iPhone since taking a screen shot with the cursor in it seems impossible. I would like it to be like the i-beam on my Mac, which is much more visible. 

<img width="345" alt="i-beam" src="https://user-images.githubusercontent.com/12577765/118713590-1bb7da80-b7f0-11eb-8c22-22814aad69e6.png">

**Comment by roblourens** [comment]
I don't know what determines what the cursor looks like. Does electron impact this @deepak1556?
