### ISSUE TITLE
Show last modified date for each file in the explorer

### ISSUE THREAD

**Issue by Total-Reality** [microsoft/vscode#124115]
Please add the file date in the explorer window by default or by a new option in the settings. 
It could be solved like here:
https://stackoverflow.com/questions/63381524/show-last-date-modified-in-vs-code

Alternative (luxury) variant: Adding a new option in the explorer to choose the attribute(s) which I like to see there, e.g. 
date, file size, file type. It could look like Windows 10 a little bit:

![windows-file](https://user-images.githubusercontent.com/5235894/118670651-15792c80-b7f7-11eb-86de-4174805e53b6.PNG)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by Total-Reality** [comment]
> This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

Thanks for your quick reply. 
Can you solve this in the near future please? I can't work with vscode until this feature is realized. 
I still need to work with PSPad because of this things :(
I have zero orientation in the file browser of vscode without any information about the files... I can't believe it is complicated to show the modified date and the file type e.g.

**Comment by Total-Reality** [comment]
?????????

**Comment by mattdig** [comment]
Can this be un-closed? It's a fantastic feature idea. Being able to view & sort my files by size, type, and particularly date-modified in a large code base is very helpful.

**Comment by tannerbroberts** [comment]
I especially want it because I want to be able to tell what parts of the code base are being actively developed, and what have either died, or require maintenance.

**Comment by rjalexa** [comment]
Upvote

**Comment by trendco** [comment]
I also don't understand why this is not implemented yet. This is a standard function in all other editors i know. Without this function i can't use VSC either. I mostly work directly on an ftp server in directories with hundreds of files. Without sorting by date of last edit or sometimes by file size it is impossible there to work.
Very sad...

**Comment by lindamegner** [comment]
I fully agree, please please fix it! Is is sad (and extremely odd!) that this is missing from an otherwise stellar programming environment!

**Comment by jackmcarthur** [comment]
Would further like to pile on and point out that this is a necessity for large codebases under continued maintenance :)

**Comment by Total-Reality** [comment]
Thank you for your answers :)
They will realize it in the future: https://github.com/microsoft/vscode/issues/164033

**Comment by pari2017-max** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Video Downloader and Player</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #333;
            color: #fff;
        }
        .container {
            width: 80%;
            max-width: 800px;
            text-align: center;
        }
        #player {
            width: 100%;
            max-width: 640px;
            margin: 20px 0;
        }
        input[type="text"] {
            width: 70%;
            padding: 10px;
            margin: 10px 0;
        }
        button {
            padding: 10px 20px;
            margin: 5px;
            background-color: #555;
            color: #fff;
            border: none;
            cursor: pointer;
        }
        button:hover {
            background-color: #777;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>YouTube Video Downloader and Player</h1>
        
        <input type="text" id="videoUrl" placeholder="Enter YouTube URL">
        <button id="addToPlaylist">Add to Playlist</button>
        <button id="playVideo">Play Video</button>
        <button id="stopVideo">Stop Video</button>
        <button id="nextVideo">Next Video</button>

        <div id="player"></div>

        <ul id="playlist"></ul>

        <button id="downloadMP4">Download MP4</button>
        <button id="downloadMP3">Download MP3</button>
    </div>

    
    <script src="https://www.youtube.com/iframe_api"></script>
    <script>
        var player;
        var playlist = [];
        var currentVideoIndex = 0;

        // Load the IFrame Player API code asynchronously
        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                height: '390',
                width: '640',
                playerVars: {
                    'autoplay': 0,
                    'controls': 1
                },
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
            });
        }

        function onPlayerReady(event) {
            // Player is ready
        }

        function onPlayerStateChange(event) {
            // Handle player state changes
            if (event.data === YT.PlayerState.ENDED) {
                playNextVideo();
            }
        }

        document.getElementById('addToPlaylist').addEventListener('click', function() {
            var url = document.getElementById('videoUrl').value;
            var videoId = getYouTubeVideoId(url);
            if (videoId) {
                playlist.push(videoId);
                updatePlaylistDisplay();
            }
        });

        document.getElementById('playVideo').addEventListener('click', function() {
            if (playlist.length > 0) {
                playVideo(playlist[currentVideoIndex]);
            }
        });

        document.getElementById('stopVideo').addEventListener('click', function() {
            if (player) {
                player.stopVideo();
            }
        });

        document.getElementById('nextVideo').addEventListener('click', function() {
            playNextVideo();
        });

        document.getElementById('downloadMP4').addEventListener('click', function() {
            // Implement MP4 download functionality
        });

        document.getElementById('downloadMP3').addEventListener('click', function() {
            // Implement MP3 download functionality
        });

        function getYouTubeVideoId(url) {
            var videoId = url.split('v=')[1];
            if (videoId) {
                var ampersandPosition = videoId.indexOf('&');
                if (ampersandPosition != -1) {
                    videoId = videoId.substring(0, ampersandPosition);
                }
                return videoId;
            }
            return null;
        }

        function playVideo(videoId) {
            if (player) {
                player.loadVideoById(videoId);
                player.playVideo();
            }
        }

        function playNextVideo() {
            if (playlist.length > 0) {
                currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
                playVideo(playlist[currentVideoIndex]);
            }
        }

        function updatePlaylistDisplay() {
            var playlistElement = document.getElementById('playlist');
            playlistElement.innerHTML = '';
            playlist.forEach(function(videoId, index) {
                var listItem = document.createElement('li');
                listItem.textContent = 'Video ID: ' + videoId;
                playlistElement.appendChild(listItem);
            });
        }
    </script>
</body>
</html>

**Comment by pari2017-max** [comment]
<input type="text" id="videoUrl" placeholder="Enter YouTube URL">
    <button id="addToPlaylist">Add to Playlist</button>
    <button id="playVideo">Play Video</button>
    <button id="stopVideo">Stop Video</button>
    <button id="nextVideo">Next Video</button>

    <div id="player"></div>

    <ul id="playlist"></ul>

    <button id="downloadMP4">Download MP4</button>
    <button id="downloadMP3">Download MP3</button>
</div>


<script src="https://www.youtube.com/iframe_api"></script>
<script>
    var player;
    var playlist = [];
    var currentVideoIndex = 0;

    // Load the IFrame Player API code asynchronously
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            playerVars: {
                'autoplay': 0,
                'controls': 1
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    function onPlayerReady(event) {
        // Player is ready
    }

    function onPlayerStateChange(event) {
        // Handle player state changes
        if (event.data === YT.PlayerState.ENDED) {
            playNextVideo();
        }
    }

    document.getElementById('addToPlaylist').addEventListener('click', function() {
        var url = document.getElementById('videoUrl').value;
        var videoId = getYouTubeVideoId(url);
        if (videoId) {
            playlist.push(videoId);
            updatePlaylistDisplay();
        }
    });

    document.getElementById('playVideo').addEventListener('click', function() {
        if (playlist.length > 0) {
            playVideo(playlist[currentVideoIndex]);
        }
    });

    document.getElementById('stopVideo').addEventListener('click', function() {
        if (player) {
            player.stopVideo();
        }
    });

    document.getElementById('nextVideo').addEventListener('click', function() {
        playNextVideo();
    });

    document.getElementById('downloadMP4').addEventListener('click', function() {
        // Implement MP4 download functionality
    });

    document.getElementById('downloadMP3').addEventListener('click', function() {
        // Implement MP3 download functionality
    });

    function getYouTubeVideoId(url) {
        var videoId = url.split('v=')[1];
        if (videoId) {
            var ampersandPosition = videoId.indexOf('&');
            if (ampersandPosition != -1) {
                videoId = videoId.substring(0, ampersandPosition);
            }
            return videoId;
        }
        return null;
    }

    function playVideo(videoId) {
        if (player) {
            player.loadVideoById(videoId);
            player.playVideo();
        }
    }

    function playNextVideo() {
        if (playlist.length > 0) {
            currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
            playVideo(playlist[currentVideoIndex]);
        }
    }

    function updatePlaylistDisplay() {
        var playlistElement = document.getElementById('playlist');
        playlistElement.innerHTML = '';
        playlist.forEach(function(videoId, index) {
            var listItem = document.createElement('li');
            listItem.textContent = 'Video ID: ' + videoId;
            playlistElement.appendChild(listItem);
        });
    }
</script>
styles.css CODE

**Comment by pari2017-max** [comment]
<input type="text" id="videoUrl" placeholder="Enter YouTube URL">
    <button id="addToPlaylist">Add to Playlist</button>
    <button id="playVideo">Play Video</button>
    <button id="stopVideo">Stop Video</button>
    <button id="nextVideo">Next Video</button>

    <div id="player"></div>

    <ul id="playlist"></ul>

    <button id="downloadMP4">Download MP4</button>
    <button id="downloadMP3">Download MP3</button>
</div>


<script src="https://www.youtube.com/iframe_api"></script>
<script>
    var player;
    var playlist = [];
    var currentVideoIndex = 0;

    // Load the IFrame Player API code asynchronously
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            playerVars: {
                'autoplay': 0,
                'controls': 1
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    function onPlayerReady(event) {
        // Player is ready
    }

    function onPlayerStateChange(event) {
        // Handle player state changes
        if (event.data === YT.PlayerState.ENDED) {
            playNextVideo();
        }
    }

    document.getElementById('addToPlaylist').addEventListener('click', function() {
        var url = document.getElementById('videoUrl').value;
        var videoId = getYouTubeVideoId(url);
        if (videoId) {
            playlist.push(videoId);
            updatePlaylistDisplay();
        }
    });

    document.getElementById('playVideo').addEventListener('click', function() {
        if (playlist.length > 0) {
            playVideo(playlist[currentVideoIndex]);
        }
    });

    document.getElementById('stopVideo').addEventListener('click', function() {
        if (player) {
            player.stopVideo();
        }
    });

    document.getElementById('nextVideo').addEventListener('click', function() {
        playNextVideo();
    });

    document.getElementById('downloadMP4').addEventListener('click', function() {
        // Implement MP4 download functionality
    });

    document.getElementById('downloadMP3').addEventListener('click', function() {
        // Implement MP3 download functionality
    });

    function getYouTubeVideoId(url) {
        var videoId = url.split('v=')[1];
        if (videoId) {
            var ampersandPosition = videoId.indexOf('&');
            if (ampersandPosition != -1) {
                videoId = videoId.substring(0, ampersandPosition);
            }
            return videoId;
        }
        return null;
    }

    function playVideo(videoId) {
        if (player) {
            player.loadVideoById(videoId);
            player.playVideo();
        }
    }

    function playNextVideo() {
        if (playlist.length > 0) {
            currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
            playVideo(playlist[currentVideoIndex]);
        }
    }

    function updatePlaylistDisplay() {
        var playlistElement = document.getElementById('playlist');
        playlistElement.innerHTML = '';
        playlist.forEach(function(videoId, index) {
            var listItem = document.createElement('li');
            listItem.textContent = 'Video ID: ' + videoId;
            playlistElement.appendChild(listItem);
        });
    }
</script>
script.js CODE

**Comment by pari2017-max** [comment]
<input type="text" id="videoUrl" placeholder="Enter YouTube URL">
    <button id="addToPlaylist">Add to Playlist</button>
    <button id="playVideo">Play Video</button>
    <button id="stopVideo">Stop Video</button>
    <button id="nextVideo">Next Video</button>

    <div id="player"></div>

    <ul id="playlist"></ul>

    <button id="downloadMP4">Download MP4</button>
    <button id="downloadMP3">Download MP3</button>
</div>


<script src="https://www.youtube.com/iframe_api"></script>
<script>
    var player;
    var playlist = [];
    var currentVideoIndex = 0;

    // Load the IFrame Player API code asynchronously
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            playerVars: {
                'autoplay': 0,
                'controls': 1
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    function onPlayerReady(event) {
        // Player is ready
    }

    function onPlayerStateChange(event) {
        // Handle player state changes
        if (event.data === YT.PlayerState.ENDED) {
            playNextVideo();
        }
    }

    document.getElementById('addToPlaylist').addEventListener('click', function() {
        var url = document.getElementById('videoUrl').value;
        var videoId = getYouTubeVideoId(url);
        if (videoId) {
            playlist.push(videoId);
            updatePlaylistDisplay();
        }
    });

    document.getElementById('playVideo').addEventListener('click', function() {
        if (playlist.length > 0) {
            playVideo(playlist[currentVideoIndex]);
        }
    });

    document.getElementById('stopVideo').addEventListener('click', function() {
        if (player) {
            player.stopVideo();
        }
    });

    document.getElementById('nextVideo').addEventListener('click', function() {
        playNextVideo();
    });

    document.getElementById('downloadMP4').addEventListener('click', function() {
        // Implement MP4 download functionality
    });

    document.getElementById('downloadMP3').addEventListener('click', function() {
        // Implement MP3 download functionality
    });

    function getYouTubeVideoId(url) {
        var videoId = url.split('v=')[1];
        if (videoId) {
            var ampersandPosition = videoId.indexOf('&');
            if (ampersandPosition != -1) {
                videoId = videoId.substring(0, ampersandPosition);
            }
            return videoId;
        }
        return null;
    }

    function playVideo(videoId) {
        if (player) {
            player.loadVideoById(videoId);
            player.playVideo();
        }
    }

    function playNextVideo() {
        if (playlist.length > 0) {
            currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
            playVideo(playlist[currentVideoIndex]);
        }
    }

    function updatePlaylistDisplay() {
        var playlistElement = document.getElementById('playlist');
        playlistElement.innerHTML = '';
        playlist.forEach(function(videoId, index) {
            var listItem = document.createElement('li');
            listItem.textContent = 'Video ID: ' + videoId;
            playlistElement.appendChild(listItem);
        });
    }
</script>
convert.php

**Comment by pari2017-max** [comment]
<input type="text" id="videoUrl" placeholder="Enter YouTube URL">
    <button id="addToPlaylist">Add to Playlist</button>
    <button id="playVideo">Play Video</button>
    <button id="stopVideo">Stop Video</button>
    <button id="nextVideo">Next Video</button>

    <div id="player"></div>

    <ul id="playlist"></ul>

    <button id="downloadMP4">Download MP4</button>
    <button id="downloadMP3">Download MP3</button>
</div>


<script src="https://www.youtube.com/iframe_api"></script>
<script>
    var player;
    var playlist = [];
    var currentVideoIndex = 0;

    // Load the IFrame Player API code asynchronously
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            playerVars: {
                'autoplay': 0,
                'controls': 1
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    function onPlayerReady(event) {
        // Player is ready
    }

    function onPlayerStateChange(event) {
        // Handle player state changes
        if (event.data === YT.PlayerState.ENDED) {
            playNextVideo();
        }
    }

    document.getElementById('addToPlaylist').addEventListener('click', function() {
        var url = document.getElementById('videoUrl').value;
        var videoId = getYouTubeVideoId(url);
        if (videoId) {
            playlist.push(videoId);
            updatePlaylistDisplay();
        }
    });

    document.getElementById('playVideo').addEventListener('click', function() {
        if (playlist.length > 0) {
            playVideo(playlist[currentVideoIndex]);
        }
    });

    document.getElementById('stopVideo').addEventListener('click', function() {
        if (player) {
            player.stopVideo();
        }
    });

    document.getElementById('nextVideo').addEventListener('click', function() {
        playNextVideo();
    });

    document.getElementById('downloadMP4').addEventListener('click', function() {
        // Implement MP4 download functionality
    });

    document.getElementById('downloadMP3').addEventListener('click', function() {
        // Implement MP3 download functionality
    });

    function getYouTubeVideoId(url) {
        var videoId = url.split('v=')[1];
        if (videoId) {
            var ampersandPosition = videoId.indexOf('&');
            if (ampersandPosition != -1) {
                videoId = videoId.substring(0, ampersandPosition);
            }
            return videoId;
        }
        return null;
    }

    function playVideo(videoId) {
        if (player) {
            player.loadVideoById(videoId);
            player.playVideo();
        }
    }

    function playNextVideo() {
        if (playlist.length > 0) {
            currentVideoIndex = (currentVideoIndex + 1) % playlist.length;
            playVideo(playlist[currentVideoIndex]);
        }
    }

    function updatePlaylistDisplay() {
        var playlistElement = document.getElementById('playlist');
        playlistElement.innerHTML = '';
        playlist.forEach(function(videoId, index) {
            var listItem = document.createElement('li');
            listItem.textContent = 'Video ID: ' + videoId;
            playlistElement.appendChild(listItem);
        });
    }
</script>download.php

**Comment by JPDengler** [comment]
????????

**Comment by aquaresima** [comment]
Dear developers, this thing is indeed very useful and does not seem complicated to do. At least someone responds and says why it is not implemented yet, or if it will ever be!

**Comment by projcdia2** [comment]
Please guys, work on this feature, it's so simple and easy to implement and it will make a big difference for users, cmon
