### ISSUE TITLE
Opening a Custom Editor Removes All Text Editors with Same File Open in Other Columns

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#124134]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57 - insiders
- OS Version: Windows

Related to #84520

Steps to Reproduce:

1. Open the same file in two columns.
2. Open one of them in custom editor.
3. The column containing the text editor should disappear suddenly, I believe that expected behavior is that it stays open.

**Comment by lramos15** [comment]
@andreamah This depends on what custom editor. Some custom editors specifically state that they do not support multiple documents per resource and therefore we must close it to respect the extension authors choice.

**Comment by andreamah** [comment]
> @andreamah This depends on what custom editor. Some custom editors specifically state that they do not support multiple documents per resource and therefore we must close it to respect the extension authors choice.

I see. I noticed that this happens with the markdown static preview and hex editor. As for the static preview, I notice that is it possible to have it open in two different columns and toggle between the modes in both sides. Not too sure if it is expected to do this, though.

**Comment by lramos15** [comment]
The hex editor cannot be opened more than once for the same resource. I don't think that the static preview has this same limitation

**Comment by andreamah** [comment]
I think that it is disposed here: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L137
Not too sure why it's also disposing of the editor that isn't active, though.

**Comment by lramos15** [comment]
That dispose is because we return an entirely new input to be opened. I don't think that's the issue, but does removing it fix the problem?

**Comment by andreamah** [comment]
Removing it fixes the problem, but I'm sure that doing that causes other things to go wrong?

**Comment by lramos15** [comment]
\closedWith https://github.com/microsoft/vscode/commit/a069768c9b63cef827304884306382ca28c8f599
