### ISSUE TITLE
Webview cant request to an express server running on localhost - vscode 1.56 and above

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#124121]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56
- OS Version: Mac os

Steps to Reproduce:

Opening it again since I had no update in more than week since I identified the bug. 

https://github.com/microsoft/vscode/issues/123281

**Comment by mjbvz** [comment]
Don't open duplicate issues, especially since the original is still open

If you want to get this fixed sooner, create a public repo with fewest lines of code that demonstrates what isn't working
