### ISSUE TITLE
Native Notebookks - Ability to omit output from git

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124131]
Have received significant amount of feedback from users who are using the native notebooks diffing experience. 
They would like to able to omit outputs when git committing notebooks, specifically called out this example a few times. 

I asked if using the "Clear all outputs" button in the global notebook toolbar would suffice for them but users mentioned not remembering that was up there and that they would like to be able to do it in one action not two. One user specifically called out the following extension: 
https://github.com/kynan/nbstripout

**Comment by rebornix** [comment]
This should be done by https://github.com/microsoft/vscode-jupyter/issues/4670 .
