### ISSUE TITLE
Folder Icons are displayed double

### ISSUE THREAD

**Issue by pgrm** [Microsoft/vscode#12410]
- VSCode Version: 1.5.2
- OS Version: Windows 10 x64

Steps to Reproduce:

After updating to VSCode 1.5.2 (I think I had 1.4 or earlier before that) I noticed that icons with the extension vscode-icons look weird (see 1st screenshot)

![image](https://cloud.githubusercontent.com/assets/713456/18730514/089cd250-8057-11e6-8df4-cf02eb1eeeb4.png)

When changing to a different icon theme things don't get much better. Here is minimal:

![image](https://cloud.githubusercontent.com/assets/713456/18730598/7b63c73a-8057-11e6-870b-a0567bc71697.png)

And here is Seti:

![image](https://cloud.githubusercontent.com/assets/713456/18730617/978bbd46-8057-11e6-81f1-527911194d89.png)

Granted, Seti looks ok, but it's still not great, since the hierarchy is all wrong. for instance, the folder `.meteor/local` isn't expanded. The files

- `.finished-upgraders`
- `.gitignore`
- `.id`
- `packages`
- `platforms`
- `release`
- `versions`

are all in the folder `.meteor` and **not** in the folder `.meteor/local` 

Any ideas how to get rid off the first folder icon and get the hierarchy right? It looked pretty ok, just before I restarted in order to get the update. Thx

**Comment by mrmlnc** [comment]
See https://github.com/Microsoft/vscode/issues/12003 and https://github.com/robertohuertasm/vscode-icons/issues/289.
