### ISSUE TITLE
Search doesn't start at cursor position

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#124137]
After having reached the end of all found occurances of a search term in a document, jumping to the beginning of the document and searching again doesn't jump to the first occurance but to the last:

![Search doesn't start at cursor position](https://user-images.githubusercontent.com/9283914/118727600-4e36f700-b833-11eb-81b5-eadff0638e5b.gif)

- VS Code/OS Version:
   ```
   Version: 1.56.2 (user setup)
   Commit: 054a9295330880ed74ceaedda236253b4f39a335
   Datum: 2021-05-12T17:13:13.157Z
   Electron: 12.0.4
   Chrome: 89.0.4389.114
   Node.js: 14.16.0
   V8: 8.9.255.24-electron.0
   Betriebssystem: Windows_NT x64 10.0.19042
   ```

## Steps to Reproduce

1. Open Visual Studio Code
2. Open some Markdown file
3. Hit <kbd>CTRL+F</kbd> to search in the markdown file
4. Enter a search term that will be occuring a number of times in the document
5. Hit <kbd>RETURN</kbd> to search for the first occurance
6. Hit <kbd>F3</kbd> repeatedly, until the final occurance of the search term is found
7. Hit <kbd>HOME</kbd> to jump to the beginning of the file
8. Hit <kbd>F3</kbd> to search for the next occurance

## Actual Result

The cursor jumps to the last occurance of the search term.

## Expected Result

The cursor should jump to the next occurance of the search term, beginning at the current cursor position.

Same for up-search (<kbd>SHIFT+F3</kbd>).

**Comment by amunger** [comment]
this now behaves as expected
