### ISSUE TITLE
Incorrect spacing after table, before next heading in Markdown Preview

### ISSUE THREAD

**Issue by UrsineRaven** [microsoft/vscode#124190]
Issue Type: <b>Bug</b>

1. Create a new markdown file.
For example:
```md
  # Test file
  
  ## Test Table
  
  | Col1  | Col2  |
  | ----- | ----- |
  | Test  | Stuff |
  | Other | Stuff |
  
  ## Next Section
  
  zyxwvutsrqponmlkjihgfedcba
  
  ```txt
  code block (with backslash to prevent outer markdown from being prematurely terminated in the issue report)
  \```
  
  ## Section with better spacing in front of it
```
2. Open the preview for the markdown file
3. Note that the spacing after the table and before the `Next Section` header is very small and makes it less readable. I've tried adding extra lines after the table, but they just get collapsed since it's just whitespace.

VS Code version: Code 1.56.0 (Universal) (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f5a13a15-e960-40bf-a7eb-9cb327278a77|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
bash-ide-vscode|mad|1.11.0
vscode-docker|ms-|1.12.1
mssql|ms-|1.10.1
cpptools|ms-|1.3.1
shellcheck|tim|0.14.1
pdf|tom|1.1.0
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by Spokaren** [comment]
Hi, according to the [markdown documentation (section block elements)](https://daringfireball.net/projects/markdown/syntax#block) : 

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.

>The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. This differs significantly from most other text-to-HTML formatters (including Movable Type’s “Convert Line Breaks” option) which translate every line break character in a paragraph into a \<br /> tag.

You can insert 2 newlines or else you can insert a HTML line break like this
```markdown
# Test file

## Test Table

| Col1  | Col2  |
| ----- | ----- |
| Test  | Stuff |
| Other | Stuff |

<br />

## Next Section

zyxwvutsrqponmlkjihgfedcba

```txt
code block (with backslash to prevent outer markdown from being prematurely terminated in the issue report)
\```

## Section with better spacing in front of it

```
hope that help ;)

**Comment by inidaname** [comment]
hello @mjbvz 
I will love to take a shot this, could you provide a guide on what is needed.

**Comment by mjbvz** [comment]
Here's the css file for the markdown preview: https://github.com/microsoft/vscode/blob/90b17ed1154de5337bb49c1495510280ce8c75f4/extensions/markdown-language-features/media/markdown.css

Try seeing if other elements, such as images, also need more bottom padding in this case

**Comment by inidaname** [comment]
@mjbvz 
I added a margin-bottom to table element, after checking on image the existing space seams okay, you can review the PR #124190
