### ISSUE TITLE
got to file should be a lateral button []

### ISSUE THREAD

**Issue by sombriks** [Microsoft/vscode#12415]
this is a feature request.
- VSCode Version: 1.5.2
- OS Version: fedora 24 64 bits

every time i intend to open a file i know by name i see the magnifier mnemonic at the lateral bar an press it. just too late i figure this search method will only search based on file content, not on file name (which is why ctrl+p exists)

**Comment by chrmarti** [comment]
I have seen this being an issue in one of the user testing recordings where the user clicked on the search icon in the sidebar and started searching for a file by name (not by content).
