### ISSUE TITLE
Stop and not respond

### ISSUE THREAD

**Issue by medoosama** [Microsoft/vscode#12416]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.when open the folder the VSCode is stop and not respond.
2.display in status bar this message "looking for css classes on the workspace".

**Comment by chrmarti** [comment]
@medoosama Does this reproduce? Could you attach a screenshot?

**Comment by chrmarti** [comment]
Could you in addition:
- Run and paste here: code --list-extensions
- If it reproduces consistently, try starting with: code --disable-extensions

**Comment by mistryrakesh** [comment]
I am facing the same issue, it gets stuck after status bar message `looking for css classes on the workspace`.

**Disabling** extensions fixes the problem. My list of exensions: `abusaidm.html-snippets`, `donjayamanne.githistory`, `robertohuertasm.vscode-icons`, `xabikos.JavaScriptSnippets`, `zhuangtongfa.Material-theme`, `Zignd.html-css-class-completion`

**Comment by chrmarti** [comment]
@mistryrakesh Could try uninstalling vscode-icons:
`code --uninstall-extension robertohuertasm.vscode-icons`

Does Code start with that extension removed?

**Comment by mistryrakesh** [comment]
Nope, that didn't help.

I noticed that I had a very large folder open (with around 17k files) which I believe was causing the problem. If I open a new instance of code using `code --new-window` it works just fine.

**Comment by mrmlnc** [comment]
This is problem related to `Zignd.html-css-class-completion` extension.

**Comment by mistryrakesh** [comment]
Yes, removing the extension `Zignd.html-css-class-completion` now allows me open that folder. Thanks!

**Comment by chrmarti** [comment]
Tracked as Zignd/HTML-CSS-Class-Completion#12
