### ISSUE TITLE
Settings Sync Account "stuck"

### ISSUE THREAD

**Issue by Pamalosebi** [microsoft/vscode#124170]
Issue Type: <b>Bug</b>

While trying to log-in (on Arch Linux) to activate "setting sync", the interface is stuck at "Loading...".
![screen_loading](https://user-images.githubusercontent.com/49550055/118798849-655efe80-b89e-11eb-8151-f18b9a7a8f0d.png)

This is just an example for the actual behavior with a flatpak. If installed via AUR or compiled from source (tried version 1.56.2 and Insider version 1.57.0) the result is identically.

VS Code version: Code - OSS 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-13T19:06:06.320Z)
OS version: Arch Linux x64 5.12.4-157

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|8.00GB|
|Process Argv|--extensions-dir /home/userxyz/.var/app/com.visualstudio.code-oss/data/vscode/extensions /app/share/vscode-flatpak-wrapper/first_run.txt --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by sandy081** [comment]
I do not think we have an official VS Code build for arch linux. Please reach out to the maintainers from where you got the distribution from. Sorry that I am not helpful here.
