### ISSUE TITLE
Code outline not work well for golang

### ISSUE THREAD

**Issue by pifjiang** [microsoft/vscode#124147]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Create two golang files in a golang pkg, define MyT struct and func1 method in f1.go, and then define func2 method in f2.go. 
![image](https://user-images.githubusercontent.com/22682155/118749367-ed89d780-b88f-11eb-807d-21f5241352c1.png)

2. Focus on f1.go, func2 cannot be seen in the outline.
![image](https://user-images.githubusercontent.com/22682155/118749519-40fc2580-b890-11eb-8168-c3a723b925d4.png)

In fact, whether focus on f1.go or f2.go, MyT struct, func1 and func2 should be visible in the outline.

**Comment by jrieken** [comment]
> In fact, whether focus on f1.go or f2.go, MyT struct, func1 and func2 should be visible in the outline.

Outline is designed to work with the currently selected editor, it is not designed to working with multiple editor simultaneously
