### ISSUE TITLE
VSCode constantly asks to install uninstalled extensions whenever window is opened

### ISSUE THREAD

**Issue by bduff9** [microsoft/vscode#124187]
Issue Type: <b>Bug</b>

Uninstalling an extension, causes that extension to constantly popup to install when opening any new VS Code window.  If I click cancel on this popup, an error is thrown in the developer tools (below).  If I click install, it then moves to the next uninstalled extension and asks to install that.  Etc.

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] Error: Error: Canceled: Canceled    at /Users/brianduffey/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:22293    at /Users/brianduffey/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11611    at Object.throw (/Users/brianduffey/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:11716)    at s (/Users/brianduffey/.vscode/extensions/shan.code-settings-sync-3.4.3/out/extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
m @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:734 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
```

This started about 5 or 6 months ago, and I was just dealing with it, but recently have been working on several different projects at once so this is happening more and more as I constantly close and open windows.  It is annoying, but also troublesome as the popup comes up during the window loading, so several times I was typing into my terminal in VS Code, and pressed enter to run a command, but this popup came up first and stole focus so I accidentally reinstalled the extension I didn't want.  Since I also didn't see what extension it was asking to reinstall, requires me to search through all my installed extensions to try to find the one I previously uninstalled and accidentally reinstalled so I can uninstall it yet again.

I do see this previous ticket that was closed without a solution (a suggestion to remove the extension from ~/.vscode/extensions doesn't help as the uninstalled extensions don't seem to be in this folder.): https://github.com/Microsoft/vscode/issues/45762

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 7, 6|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 05bcc196-ce8d-458a-8d20-86a2171915bd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
scss-lint|ada|0.1.10
project-manager|ale|12.1.0
aws-toolkit-vscode|ama|1.25.0
svelte-intellisense|ard|0.7.1
bettertab|are|1.0.1
vscode-browser-preview|auc|0.7.1
vscode-database|baj|2.2.3
lit-html|bie|1.11.1
simple-react-snippets|bur|1.2.3
vscode-exports-autocomplete|cap|0.5.4
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
FreeMarker|dco|0.0.9
deepcode|dee|3.0.11
git-extension-pack|don|0.1.3
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
freemarker-magnolia-snippets|fen|1.4.0
go|gol|0.25.0
css2react|got|1.0.1
gc-excelviewer|Gra|3.0.41
vscode-graphql|Gra|0.3.16
npm-dependency-links|her|1.2.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
node-module-intellisense|jhe|1.6.0
diff-tool|jin|0.0.1
svg|joc|1.4.6
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
node-module-intellisense|lei|1.5.0
duplicate-module|Leo|0.0.3
vscode-graphql|luy|0.0.4
rainbow-csv|mec|1.8.1
dotenv|mik|1.0.1
vscode-extension-auto-import|mop|1.3.3
vscode-docker|ms-|1.12.1
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
abracadabra|nic|5.3.0
vscode-jest|Ort|4.0.1
vscode-versionlens|pfl|1.0.9
ngrok-for-vscode|phi|1.9.0
project-snippets|reb|0.5.0
java|red|0.79.1
vscode-yaml|red|0.19.0
LiveServer|rit|5.6.1
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
svelte-vscode|sve|104.12.2
react-typescript-toolbox|sve|1.7.0
tabnine-vscode|Tab|3.4.4
serverless-ide-vscode|Thr|0.5.31
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.4.0
nodejs-extension-pack|wad|0.1.9
vscode-wakatime|Wak|9.0.5
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
highlight-trailing-white-spaces|yba|0.0.2
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by sandy081** [comment]
I think this is being caused by the extension you installed - code-settings-sync. Please disable it and try again. If you still reproduce it let us know.
