### ISSUE TITLE
Delay workspace recommendations as remote extensions installations are ongoing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#124119]
In remote windows such as codespaces it's possible to see the extension recommendation dialog while the extensions from the container are still installed.

<img width="490" alt="Screen Shot 2021-04-14 at 1 43 12 PM" src="https://user-images.githubusercontent.com/13760/114755556-c9365a80-9d27-11eb-888b-69d36d9b8619.png">

I reproduced this in a codespace with `devcontainer.json` and a `extensions.json` containing
```
"extensions": [
	"rebornix.ruby",
	"castwide.solargraph",
]
```
That said, I only reproduced it once.

**Comment by aeschli** [comment]
I pushed a change set that adds a delay of 5 seconds to the workspace recommendations.
Ideally there's a way to wait until ongoing installations are completed. Leaving that to @sandy081 for later.

**Comment by aeschli** [comment]
Closing as fixed.

**Comment by connor4312** [comment]
verified with code review
