### ISSUE TITLE
While installing update or downloading the hint text is "Checking for updates"

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#124102]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10 20h2

Steps to Reproduce:

While `installing update` or `downloading` the hint text is "Checking for updates"

![image](https://user-images.githubusercontent.com/17777237/118650256-86631900-b7e4-11eb-8d12-225394fc9fc3.png)

**Comment by pixieaka** [comment]
Still "Restart to update" shows as "Insiders update available"

![image](https://user-images.githubusercontent.com/17777237/118865245-0b335d00-b8e1-11eb-8a61-729e63c3926d.png)

![image](https://user-images.githubusercontent.com/17777237/118865452-3f0e8280-b8e1-11eb-8572-d88fc74518d9.png)

**Comment by joaomoreno** [comment]
That is correct. The status is _update available_. The action is _restart to update_.
