### ISSUE TITLE
Esc does not close Peek References view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#124183]
1. Trigger a Peek References view
2. Click into it
3. Press `esc`, peek is not closed 🐛

**Comment by jrieken** [comment]
@isidorn This works for me... Do you have any special setting?

**Comment by isidorn** [comment]
Works for a clean user data dir.
... Oh just figured out I had `editor.stablePeek: true` for an unknown reason

Sorry about the noise

**Comment by jrieken** [comment]
> figured out I had editor.stablePeek: true for an

YEah, works as designed ;-)
