### ISSUE TITLE
100% CPU being constantly used by VSCode

### ISSUE THREAD

**Issue by Murtaya** [microsoft/vscode#124136]
Issue Type: <b>Bug</b>

My computer is pegged at 100% CPU usage between VSCode and all the Node.js tasks being spawned by it.  If I kill VSCode it all goes away; as soon as I start it up again, the CPU becomes pegged again.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (20.75GB free)|
|Process Argv|--crash-reporter-id f53a4338-faa4-4c22-8800-ef494cfc4959|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
prettier-vscode|esb|6.4.0
vs-keybindings|ms-|0.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
team|ms-|1.161.1
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.2
vscode-jest|Ort|4.0.1
project-snippets|reb|0.5.0
code-spell-checker|str|1.10.2
save-and-run|wk-|0.0.22

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833cf:30267465
vshan820:30294714
vscoreces:30290705
vscus158cf:30286554
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Can you find the command line arguments of the processes in task manager?

Does it happen if you start with `--disable-extensions`?
