### ISSUE TITLE
Webview unexpectedly requested a remote resource

### ISSUE THREAD

**Issue by pikadun** [microsoft/vscode#124152]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.56.2 (user setup)
- Commit: 054a9295330880ed74ceaedda236253b4f39a335
- Date: 2021-05-12T17:13:13.157Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. Download and install the expansion pack:  https://1drv.ms/u/s!Arpl2o4drizxgrB04AZykzy4mBhStw?e=FdUZ6w
2. Click `Redis Explore` on sidebar
3. Click `Add` button
4. Open the `Developer Tools`
5. Check the console

There will be an error message:
``` text
Access to script at 'https://e80b34aa-e9d9-42e2-97bb-0b9d245c4aa0.vscode-webview-test.com/_snowpack/pkg/svelte.internal.v3.38.2.js' from origin 'vscode-webview://e80b34aa-e9d9-42e2-97bb-0b9d245c4aa0' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
All resources are local, why request remote resources?

**Comment by mjbvz** [comment]
This is expected as we use service workers to load local resources. `vscode-webview-test.com` is never actually hit
