### ISSUE TITLE
Blocked other in webview running on localhost

### ISSUE THREAD

**Issue by ty-d** [microsoft/vscode#124124]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57 insiders
- OS Version: Windows

Steps to Reproduce:

1. Run the sample extension: https://github.com/ty-d/WebviewBlockedOther
2. Run this simple express server: https://github.com/ty-d/SvgTestServer
     - npm install
     - node svgTest.js
3. Open the webview developer tools to the network tab
4. Run the command "Hello world" in the sample extension

This results in a status of "blocked:other" in the network tab and gives the following errors in the console:
![image](https://user-images.githubusercontent.com/54182162/118695784-91657b80-b7db-11eb-9fbc-dc6e86115b57.png)

The sample displays successfully in VS Code 1.55, but not in 1.56 and up. I tried loading the file over http and https and both failed. Occasionally the webview will load as expected on startup but reloading reproduces the error. When looking at the network traffic, the server responds successfully with the SVG file, but VS Code does not load it. Other content types such "plain/text" do not cause the "blocked:other" error.

**Comment by ty-d** [comment]
Thanks for taking a look at this issue. Unfortunately, this only fixed svgs that are loaded in an img tag. The embed, object, and iframe tags produce the same "blocked:other" issue as before. I updated my sample extension to include these extra tags: https://github.com/ty-d/WebviewBlockedOther.

**Comment by mjbvz** [comment]
Please open a new issue for that as it likely has a different root cause
