### ISSUE TITLE
No outline view

### ISSUE THREAD

**Issue by anhle82** [microsoft/vscode#124283]
Issue Type: <b>Bug</b>

Running VSCode 1.55.2. No Outline View panel available under Explorer.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.41GB free)|
|Process Argv|--crash-reporter-id bf4c7a0c-6795-46d8-a607-d9588b199303|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.6
vscode-intelephense-client|bme|1.7.1
simple-react-snippets|bur|1.2.3
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
live-sass|gle|5.0.3
sftp|lix|1.12.9
easy-less|mrc|1.7.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
LiveServer|rit|5.6.1
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by jrieken** [comment]
Did you hide it? Right click the explorer title and see if outline as the checkmark

<img width="447" alt="Screen Shot 2021-05-21 at 09 09 45" src="https://user-images.githubusercontent.com/1794099/119096766-4aae9600-ba14-11eb-945f-a3df008464d9.png">

**Comment by anhle82** [comment]
Hi @jrieken , it's not there. 

![vscode](https://user-images.githubusercontent.com/1724645/119169938-3379a380-ba28-11eb-9363-d3ae1b5f6ba3.jpg)

**Comment by jrieken** [comment]
Please do the following

* press `F1`
* erase all text and type `view outline`
* does it show the outline entry?

**Comment by jrieken** [comment]
> erase all text and type view outline

Don't have the `>` in there

**Comment by anhle82** [comment]
Sorry I missed the >. Same result though.

![vscode2](https://user-images.githubusercontent.com/1724645/119530019-3df9ad00-bd48-11eb-9844-71bebcdca331.jpg)

**Comment by jrieken** [comment]
ok, please try "F1 > Reset View Locations"

**Comment by anhle82** [comment]
Perfect. I have outline now. Thank you very much @jrieken

**Comment by jrieken** [comment]
ok, closing as question
