### ISSUE TITLE
Types not following properly for properties of a function

### ISSUE THREAD

**Issue by y-nk** [microsoft/vscode#124243]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Authoring my library.

Code is a bit big, but i'll try to narrow down. I've built a library where functions have properties attached which are functions as well. such as:

```
const getMessage = async (messageId: string) => { /* call to backend */ }
getMessage.locally = (messageId: string) => { return fromCache(...) }
```

Once compiled, the .d.ts for this method is generated and everything looks fine.

2. Using my library

In another project (imported with npm link), I can hover the function in vscode and see the .d.ts file properly:

![image](https://user-images.githubusercontent.com/411625/118966867-3aef6d00-b994-11eb-9d9a-3756d79cd2e5.png)

but when using, the auto-completion does not resolve the typing according to the .d.ts that it's able to read:

![image](https://user-images.githubusercontent.com/411625/118966997-5d818600-b994-11eb-87e9-5176057d11fa.png)

How to make VS code to read my types properly ?

**Comment by y-nk** [comment]
@mjbvz that was phrased as a question, but it's obvious from reading that there's a bug implied here...

**Comment by mjbvz** [comment]
Please share a minimal, self contained example of the problem
