### ISSUE TITLE
Set default go to definition

### ISSUE THREAD

**Issue by Godrules500** [microsoft/vscode#124251]
I have 2 extensions for angular that do completely different things, but overlap in the area of 'Go to Definition'.  The problem I'm having is, when I click 'go to definition', it pulls up the peek dialog showing the same line of code for me to decide. 

I would like the ability to set a default, so that it only uses 1 extension to go to the definition.

**Comment by jrieken** [comment]
That's what the `editor.gotoLocation.multipleDefinitions` setting is for.
