### ISSUE TITLE
Terminal tab order is wrong

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124284]
Repro:

1. Create a terminal, split twice

![image](https://user-images.githubusercontent.com/2193314/119028167-019b0b00-b95c-11eb-975a-0d09b0f0fb3d.png)

**Comment by meganrogge** [comment]
to verify, split in a bunch of ways, but primarily:

- create two split terminals
- focus the first 
- split again
- 🐛 was the terminal would be added as the rightmost in the split pane
- should be created to the right of the first (focused) terminal
