### ISSUE TITLE
[shellscript] validate end of line character

### ISSUE THREAD

**Issue by SteveLasker** [microsoft/vscode#12422]
- VSCode Version:
  Version 1.5.2
  Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
  Date 2016-09-12T13:30:03.456Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version:
  Windows 10

Steps to Reproduce:
1. create a dosomething.sh file in c:\repro\
2. place the following in the file

```
#!/bin/bash
echo hello from the cozy container
```
1. run:
   `docker run -it -v c:/repro:/src debian src/dosomething.sh`
2. Response:
   `standard_init_linux.go:175: exec user process caused "no such file or directory"`
   Which starts you down the crazy train as you know it’s there but question if you got all the Linux things right:
   Did you lean forward / lean backward \
   Did you get the ./ correct?
   Was volume mounting correct?
   Ahhhhhhhhh
3. use `Dos2Linux` to fix the file
4. learn VS Code has a nice option in the corner to switch to lf
5. `docker run -it -v c:/repro:/src debian src/dosomething.sh`
6. Response:
   `hello from the cozy container`
7. Look for a way to customize a specific language (bash)
8. log a bug hoping the VS Code team will just fix *.sh files to always use just lf
9. [blog that VS Code rocks, and hope it will fix the default](http://running-scripts-in-a-docker-container-from-windows-cr-or-crlf)

**Comment by chrmarti** [comment]
You could use an .editorconfig and the [EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension to get that:
```
[*.sh]
end_of_line = lf
```

**Comment by SteveLasker** [comment]
Thank you. That's a better workaround than having to change all or manually change everytime. Can we get this added to bash?

**Comment by chrmarti** [comment]
I'm not sure what you mean by adding to bash.

**Comment by SteveLasker** [comment]
VS Code has language support for bash. It's auto associated to .sh files. can 
```
[*.sh]
end_of_line = lf
```
be added to that language service?

**Comment by chrmarti** [comment]
The problem with this is, that it requires the EditorConfig extension, which is not bundled with VSCode.

**Comment by chrmarti** [comment]
Doing this automatically might not always be expected, but we could ask the user when we detect this case on save.

**Comment by aeschli** [comment]
Not sure what is the right approach here.
- Automatically changing a new line character is not a good idea. There could be a warning and a quick fix. That's what could already be implemented by an extension
- Provide language specific EOL character settings

**Comment by jstaelens** [comment]
It would be really nice if this was the default...
"[shellscript]": {
    "files.eol": "\n"
}

Or if it was even possible.  I'll keep using dos2unix on Bash on Ubuntu on Windows to fix my bash scripts.

**Comment by aeschli** [comment]
We have #49418 as request to make `\n` the line delimiter of all new shellscript files. I created a PR to fix that.
To also add validation is not planed but would better come from a shell language server that also does other linting.
