### ISSUE TITLE
Black/white unclickable bar on top of VS Code makes editor unusable when window is maximized

### ISSUE THREAD

**Issue by Kenya-West** [microsoft/vscode#124264]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10 20H2

Requirements:

- Have graphics card from NVIDIA or AMD (no matter which version)
- Have Windows 10 (any version newer than Anniversary Update, including this)
- Have more than two monitors (each with Full HD resolution on, but not necessary)

Steps to Reproduce:

1. Just use this from time to time
2. Maximize a window of VS Code
2. Get a bug (once a month)
3. Try to reproduce it on any Chromium app, including PWAs (Edge/Chrome) and Electron apps

### How to solve a bug:

100% helps:

- Try restarting graphics card driver: Win+Ctrl+Shift+B
- Try to restore settings in NVIDIA Control Panel (not NVIDIA GeForce Experience) / AMD Settings
- Swap monitors in Settings -> Display and then swap it back
- Unplug any of monitors and then plug it back.

Maybe help:

- Tick any of setting in above apps in hope to solve a problem
- Try "auto-adjust" function on affected monitor

**DISCLAIMER**: This bug is not related exclusively on VS Code. It is related for Chromium and (possibly) video drivers, but VS Code developers and Electron developers have highest chance to solve it.

### How does the bug look?

The bug looks like a 200px high area on top of app is not rendered and nothing helps but actions I mentioned above. It takes entire app' width. This area (usually mentioned as [black bar](https://www.bing.com/search?q=black+bar+multi-monitor+windows) or [white bar](https://www.bing.com/search?q=white+bar+windows) depended on app in search query) is totally unclickable, so you cannot operate the window except hotkeys.

### In what conditions does this happen?

This bug appears only on Windows AFAIK. It appears only on multi-monitor setup, at least three monitors should be on. You can spot it only on maximized window in _specific_ monitor. If you move the affected app to any other monitor and maximize it, then bug disappears. But 

### How does it happen?

It affects, as metioned, on every Chromium app. When any of related app gets black/white unresponsive bar, every other gets it, too, like: Microsoft Edge, Google Chrome, Skype, Authy, Facebook Messenger etc.

You cannot predict when the bug can hit! At least, based on my experience, you can not at all. It fires at least once a month.

### Are there possible solutions to resolve the problem?

My thoughts that this bug happens **because of hardware acceleration** or some incorrect API call/behaviour in Chromium/Electron.

You can disable hardware acceleration, for example, in a browser. But the problem is that the Chromium browser still uses hardware accelerations to draw its interface anyway. So, the bug happens on it, no matter what.

### A video to show the problem

https://user-images.githubusercontent.com/12271104/118992918-0691a600-b9c0-11eb-9e2d-9b6d6e654d70.mp4

**Comment by deepak1556** [comment]
Thanks for the detailed report, couple of things to check:

1) Are you running vscode as administrator ? If so, can you start with `code --no-sandbox` and check if issue persists
2) If 1) does not help, can you run with `code --disable-features=CalculateNativeWinOcclusion`

**Comment by Kenya-West** [comment]
Thanks for response @deepak1556! I try to answer these points.

1. I'm not running VS Code with admin rights, I have a setup in User scope;
2. This point requires at least a month to test (as the bug fires once a month) so probably we need to kind of "freeze" the issue in archive state or something.
