### ISSUE TITLE
Emmet in plain HTML outputs everything in one line

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1242]
Try the following emmet snippet in a `.html` file:

```
.foo>input[name="bob"]+label[for="bob"]
```

You'll notice everything will be placed in one line.

If you use it in `.jsx` or `.tsx`, though, they are nicely indented.

**Comment by egamma** [comment]
Verified that this behaviour is consistent across the different emmet integrations (sublime, atom).
