### ISSUE TITLE
Typescript service is dying after update to last version

### ISSUE THREAD

**Issue by GaboFrontDev** [microsoft/vscode#124217]
I don't know what happen but please this is a serious issue. Just updated to last version of VS Code and it stop working 

<div class="block block-system" style="box-sizing: border-box; font-size: 12px; color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="block-info" style="box-sizing: border-box; background-color: rgb(26, 28, 37); color: rgb(238, 255, 255); width: 484.492px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px; padding: 10px;">
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | &nbsp;
Memory (System) | 31.95GB (16.32GB free)
Process Argv | --crash-reporter-id 0d15c950-0e06-46ba-bbc2-4ecf7ea5a6c1
Screen Reader | no
VM | 0%

<hr style="box-sizing: border-box;">
Remote | WSL: Ubuntu-20.04
-- | --
OS | Linux x64 5.4.72-microsoft-standard-WSL2
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)
Memory (System) | 25.02GB (19.02GB free)
VM | 0%

<hr style="box-sizing: border-box;">
Remote | WSL: Ubuntu-20.04
-- | --
OS | Linux x64 5.4.72-microsoft-standard-WSL2
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)
Memory (System) | 25.02GB (19.02GB free)
VM | 0%

</div></div><br class="Apple-interchange-newline">

<div class="block block-system" style="box-sizing: border-box; font-size: 12px; color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="block-info" style="box-sizing: border-box; background-color: rgb(26, 28, 37); color: rgb(238, 255, 255); width: 484.492px; font-size: 12px; overflow: auto; overflow-wrap: break-word; margin: 5px; padding: 10px;">
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | &nbsp;
Memory (System) | 31.95GB (16.32GB free)
Process Argv | --crash-reporter-id 0d15c950-0e06-46ba-bbc2-4ecf7ea5a6c1
Screen Reader | no
VM | 0%

<hr style="box-sizing: border-box;">
Remote | WSL: Ubuntu-20.04
-- | --
OS | Linux x64 5.4.72-microsoft-standard-WSL2
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)
Memory (System) | 25.02GB (19.02GB free)
VM | 0%

<hr style="box-sizing: border-box;">
Remote | WSL: Ubuntu-20.04
-- | --
OS | Linux x64 5.4.72-microsoft-standard-WSL2
CPUs | AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)
Memory (System) | 25.02GB (19.02GB free)
VM | 0%

</div></div><br class="Apple-interchange-newline">

vsc-material-theme | Equ | 33.2.0
-- | -- | --
vsc-material-theme-icons | equ | 1.2.2
vscode-angular-html | gha | 1.7.0
Angular-BeastCode | Mik | 10.0.3
remote-wsl | ms- | 0.56.2
material-icon-theme | PKi | 4.6.0
windows-terminal | Tyr | 0.6.0
ng-template | Ang | 12.0.1
angular-schematics | cyr | 4.13.0
gitlens | eam | 11.4.1
prettier-vscode | esb | 6.4.0
angular2-switcher | inf | 0.3.4
vscode-scss | mrm | 0.10.0
vscode-typescript-next | ms- | 4.4.20210519
pdf | tom | 1.1.0

<span style="color: rgb(238, 255, 255); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(26, 28, 37); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><br class="Apple-interchange-newline">

vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
