### ISSUE TITLE
Support mapping container paths in terminal to local paths (when clicking file links)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#124244]
When running a command in the terminal via a container (for e.g docker-compose) sometimes outputs errors with filepaths. For e.g `/home/user/project1/node_modules/styled-components/dist/foo.js:81:33`

Clicking this link doesn't work as VSCode does not know im in a terminal so it goes nowhere. The real path is: `/my/host/os/project1/node_modules/styled-components/dist/foo.js:81:33`

Is it possible to provide VSCode with a mapping in the settings, so clicking this filepath can map to my local path?

**Comment by Tyriar** [comment]
The fix here is probably to just use the containers extension which is optimized for this

**Comment by jasonwilliams** [comment]
@Tyriar normally I would do that, but in this project i have multiple containers to handle different things. So i need docker-compose to orchestrate that.
I believe the containers extension would only plug VSCode into 1 container at a time. That wouldn't work for me in this scenario.

**Comment by Tyriar** [comment]
I'm that case, since this is such a niche scenario I'd say this should be up to an extension to implement using the terminal link provider api
