### ISSUE TITLE
Regex highlighting inside arrow function expressions

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#12429]
- VSCode Version: Version 1.6.0-insider
- OS Version: Windows 10 x64 with Anniversary Update

See image below, regex is not highlighted as expected:
![image](https://cloud.githubusercontent.com/assets/3898363/18741105/44c788d0-80a5-11e6-8f31-5426bd59c67e.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#297
