### ISSUE TITLE
Source control in WSL2 not recognizing file changes

### ISSUE THREAD

**Issue by mrclickbits** [microsoft/vscode#124232]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10 20H2 (Build 19042.985)

I use VS Code on my MS Windows 10 setup with WSL 2 activated.
No matter which way I open VS Code (via windows-mounted file system or via WSL bash in /home/...) I cannot get the source control panel to detect file changes.
When files are under git control and they are changed when I start VS Code it is displayed as such. But every change from there on is not being shown.

Any help is welcome!

**Comment by lszomoru** [comment]
@mrclickbits, apologies for not getting back to you on this until now.
Are you still seeing this issue with the latest version of VS Code and the Remote WSL extension?

**Comment by mrclickbits** [comment]
Hi,
thanks for getting back to me!
And yes, unfortunately I'm still encountering the described problem in VS Code. I always have the latest (stable) version running.

I appreciate any help or workarounds; my current workaround is to only rely on the git CLI diffs etc. which is often enough quite cumbersome.

Thanks and all the best,
Max

**Comment by lszomoru** [comment]
@mrclickbits, thank for getting back to me. Do you mind creating a recording using https://gifcap.dev/ as that would allow me to get additional details of your setup as well as help me in trying to reproduce the issue. Thank you very much!

**Comment by mrclickbits** [comment]
@lszomoru I was trying to setup a minimal example demonstrating the issue but I couldn't reproduce the behavior in a freshly initialized repo. Plus it also does not occur when I open a repo I cloned from github (via HTTPS) but it does still and reproducably happen if I clone bitbucket cloud repos via SSH.

I was googling again and I could make it work via the suggestion in https://github.com/microsoft/vscode/issues/116673#issuecomment-901045377
This seems to work for now, but maybe SSH aspect is of any value to you?

Let me know if I can provide you with further info. But please understand I cannot share any screenshots etc. from the real work repos due to copyright and privacy.

**Comment by lszomoru** [comment]
@mrclickbits, thanks for the update. Are you able to reproduce the same behaviour if you try to close a GitHub repository using SSH? Could you also please confirm that you were able to resolve the problem by setting `"git.autofetch": false`? Thank you very much.

**Comment by mrclickbits** [comment]
@lszomoru I couldn't manage to clone the exact same repo with SSH and HTTPS but with all those I cloned via HTTPS I could not perceive the issue.
Setting `git.autofetch` to `false` fixed it for me in the SSH cases, exactly

**Comment by lszomoru** [comment]
@mrclickbits, thanks for the update. Glad to hear that changing the setting resolved the issue.
