### ISSUE TITLE
Ability to get a `Range` from a `TextDocument` given a substring or `RegExp`

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#124213]
I'm trying to write an extension that does all sorts of pre-defined find-and-replace operations with various regex patterns. Right now it seems the only way I can do this is to get the entire contents of the file and then replace the entire contents of the file, like so:

```ts
const editor = vscode.window.activeTextEditor;

if (editor) {
    const document = editor.document;

    // Get file contents and process it
    const fileContents = document.getText();
    const processed = process(fileContents);
    
    editor.edit(editBuilder => {
        // Replace entire file contents
        var firstLine = document.lineAt(0);
        var lastLine = document.lineAt(document.lineCount - 1);
        var fullTextRange = new vscode.Range(firstLine.range.start, lastLine.range.end);

        editBuilder.replace(fullTextRange, processed);
    });
}
```

I feel like this is a really awful way to do it, but there seems to be no other way. I expected there to be some sort of method that I could pass a `string` or `RegEx` to and have it return a `Range` I could pass to `editBuilder.replace()`.

Or am I worried about nothing and this is a non-issue?

**Comment by jrieken** [comment]
Did you try to use [`getWordRangeAtPosition(position, regex)`](https://github.com/microsoft/vscode/blob/df3c2c487550e154900b7907e4f337a94afcac43/src/vs/vscode.d.ts#L225) with you custom regex?

**Comment by NSExceptional** [comment]
Hmm, this limitation is unsatisfactory to me:

> A custom regular expression will **fail to match multiline strings** and in the name of speed regular expressions **should not match words with spaces**. Use TextLine.text for more complex, non-wordy, scenarios.

I am explicitly trying to match potentially multi-line patterns. Perhaps I'm better off writing a small parser anyway?

**Comment by jrieken** [comment]
> Perhaps I'm better off writing a small parser anyway?

I would say so - your ask seems quite specific and not like it would justify a general purpose API
