### ISSUE TITLE
Visual Studio Extensions Marketplace down? 

### ISSUE THREAD

**Issue by christymcgrory** [microsoft/vscode#124278]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.0
- OS Version: MacOS Big Sur 11.2.3

Steps to Reproduce:

1. Go to extensions tab
2. search for an extension

Looks like the whole visualstudio.com domain is down, as well as microsoft ToDo (couldn't find any other services though). Any official word on this?

**Comment by PythonCreator27** [comment]
Cannot reproduce at all... The domain is up and searching works.

**Comment by christymcgrory** [comment]
Looks like this issue was resolved around 20 minutes after I noticed it, closing as non-issue.
