### ISSUE TITLE
Test terminal doesn't show icon or title in tab

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124290]
Repro:

1. Run some tests
2. Click Show Output button

![image](https://user-images.githubusercontent.com/2193314/119034408-1fb83980-b963-11eb-85e0-20bb8ee86186.png)

cc @connor4312

**Comment by connor4312** [comment]
related https://github.com/microsoft/vscode/issues/122227

**Comment by Tyriar** [comment]
@connor4312 FYI this was missing the ready event firing in the custom pty
