### ISSUE TITLE
Worksapce Trust can't Trust workspaces connected with the Remote-SSH extension

### ISSUE THREAD

**Issue by jineens** [microsoft/vscode#124210]
Issue Type: <b>Bug</b>

Workspace Trust got enabled on my vscode-insiders this afternoon. When I started vscode and connected to my remote computer & workspace, I got a "Hey this workspace is untrusted, do you want to trust it dialog" and said yes. However the remote development extensions had already disabled / disconnected. There was a notification that said "Enable Remote SSH and reload?" so I did... and I got the "do you want to trust this workspace" dialog again. (Infinite loop).

When I opened a local workspace, this flow worked fine and the workspace was trusted. Then I could look at the workspace trust settings page, which had ... no good information. But when i did look, the ssh trusted folders did not have a valid path, and I could not edit or add a non local host path. (One of the times I deleted the entries and tried again, the host was "vscode-remote" instead of "SSH")
![image](https://user-images.githubusercontent.com/44418806/118895503-24c1ae00-b8bb-11eb-8259-992df5ff388d.png)

My only current option is to disable the feature.

VS Code version: Code - Insiders 1.57.0-insider (53b58c89d44deb230dc526605561a1d42f6d1c50, 2021-05-19T13:57:29.889Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.80GB free)|
|Process Argv|--crash-reporter-id fd74811f-9620-41d2-ae87-07a493aa32bc --crash-reporter-id fd74811f-9620-41d2-ae87-07a493aa32bc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: jineens-boss|
|OS|Windows_NT x64 10.0.19042|
|CPUs|Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz (28 x 3312)|
|Memory (System)|63.71GB (34.34GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
mojom-language|Joe|0.0.1
remote-containers|ms-|0.179.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-gn|npc|1.1.0
proto|pet|0.0.2
rewrap|stk|1.14.0
vscode-instant-markdown|dba|1.4.7
githd|hui|2.2.4
chat|kar|0.35.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.2
jupyter|ms-|2021.6.856262935
cpptools|ms-|1.4.0-insiders2
powershell|ms-|2021.2.2
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
partial-diff|ryu|1.4.3
rewrap|stk|1.14.0
change-case|wma|1.0.0
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vspre833cf:30267465
vshan820:30294714
vscus158:30286553
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Sorry, the stable version of the SSH extension is missing a change that went out in the Nightly SSH extension a long time ago. I just published Remote-SSH 0.65.5 which should work for you.

**Comment by roblourens** [comment]
Let me know if you still have an issue with it, after getting the latest version of the extension

**Comment by jineens** [comment]
It looks like it works now!

Thanks 😊
Jineen
