### ISSUE TITLE
Bluetooth disconnects when opening VSCode flatpak on Pop!_OS 20.10

### ISSUE THREAD

**Issue by perused** [microsoft/vscode#124242]
Does this issue occur when all extensions are disabled?: No (but see note at bottom)

- VS Code Version: 1.56.2 - Pop!_OS (deb)
- OS Version: Pop!_OS 20.10

Steps to Reproduce:

1. Be connected to some bluetooth device (in my case, a bluetooth receiver)
2. Open VSCode (not through terminal) by clicking the icon in app bar
3. Bluetooth disconnects and I have to hold down the bluetooth button on my bluetooth receiver and reconnect from bluetooth settings, then restart spotify to continue playing music or listening through the receiver

Note: Strangely enough, this issue only occurs when clicking the app icon, it does not occur when launching from terminal either with 'code' or 'code --disable-extensions'.

**Comment by perused** [comment]
I just tested disabling from inside the app, closing it and then opening from launcher and the issue still happens, yes

**Comment by deepak1556** [comment]
Can you test with vscode deb package from https://code.visualstudio.com/#alt-downloads instead of the flatpak version.
