### ISSUE TITLE
Default PHP linting stopped working since 1.56.*

### ISSUE THREAD

**Issue by E-Haci** [microsoft/vscode#124240]
OS: Ubuntu 20.04 
Starting from 1.56 update default php linter (php -l) stopped working. 
I tried to re-install, purge all local data - but still the same. 

Then i downloaded 1.55 from your repo archive, and installed it - PHP linter works without any problem.

Please have a look.

Let me know what more information i need to provide.

**Comment by roblourens** [comment]
Apologies. It will be fixed in the next insiders build. You can work around it for now by setting the path to PHP in your workspace settings (`.vscode/settings.json`): `"php.validate.executablePath": "/path/to/php"`

**Comment by E-Haci** [comment]
Can you tell me how to solve this in stable release? 

1. Updating to the latest version didn't help - the same problem.
2. trying to modify php.validate.executablePath manually didn't help either.

**Comment by roblourens** [comment]
Did you select to trust the workspace? Should have gotten a prompt which is new this month.

**Comment by E-Haci** [comment]
> Did you select to trust the workspace? Should have gotten a prompt which is new in 1.57.

Yes of course.  Other linters works without any problem. The problem seems to be related to php linter. (1.55.2 - currently I have to use this version. Everything works OK there)

Are you sure that this fix exists in stable version of latest Viscose release ?

**Comment by roblourens** [comment]
Yeah, it's there, and works for me. Can you check for errors in the devtools console (Help > Toggle Developer Tools)?

**Comment by E-Haci** [comment]
> Yeah, it's there, and works for me. Can you check for errors in the devtools console (Help > Toggle Developer Tools)?

Thank you for the answer.
I have just updated to 1.57.0 from yesterday release, and everything seems to be working fine now.
