### ISSUE TITLE
Unbound breakpoints, Node remote

### ISSUE THREAD

**Issue by audunhy** [microsoft/vscode#124249]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
- OS Version: Linux x64 3.10.0-229.el7.x86_64   (CentOS 7)
-  Node version: v8.11.1

I am trying to remote debug a Node application running on ARM 32bit. Unable to set breakpoint, they are all unbound. If I disable the new debugger, Debug > Javascript: Use Preview, it works.

Source mappings seems to work, based on output from Diagnose Breakpoint below. Both files exists at the path. The file is also the file Node is started with so Node should have parsed it.

Debug log from setting one breakpoint is attached.
[vscode-debugadapter-aa22ca71.json.gz](https://github.com/microsoft/vscode/files/6515812/vscode-debugadapter-aa22ca71.json.gz)

**Output from Diagnose Breakpoint Problems:**
✅ This breakpoint was initially set in:

/home/efd/dev/build_scripts/dev/websites/fipr/fiprweb.js line 406 column 1

✅ In the runtime, the breakpoint was set in:

file:///efd/web/sites/fipr/fiprweb.js line 406 column 1 via this regex

❓ We sent the breakpoint, but it didn't bind to any locations. If this is unexpected:
Make sure that your program is loading or running this script. You can add a debugger; statement to check this: your program will pause when it hits it.
If your breakpoint is set in certain places, such as on the last empty line of a file, the runtime might not be able to find anywhere to place it.
Unless you run with --nolazy, Node.js might not resolve breakpoints for code it hasn't parsed yet.
If necessary, make sure your compiled files are up-to-date with your source files.

**launch.json:**
```json
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to FIPR service node",
            "address": "192.168.217.5",
            "port": 9229,
			"localRoot": "${workspaceFolder}",
			"remoteRoot": "/efd/web/sites/fipr",
			"sourceMaps": true,
			"trace": true
			
        }
	]
}
```

**Comment by connor4312** [comment]
Locally, you have a file called

```
/home/efd/dev/build_scripts/dev/websites/fipr/fiprweb.js
```

Based on your remoteRoot and localRoot, the debugger expects that to live int

```
/efd/web/sites/fipr/fiprweb.js
```

However, Node reports that it's actually coming from:

```
/media/mmcblk1p4/efd/web/sites/fipr/fiprweb.js
```

So you probably want to change your remote root. Or, if your applications is running these as linked files, you may want to add `--preserve-symlinks` and/or `--preserve-symlinks-main` ([docs](https://nodejs.org/api/cli.html#cli_preserve_symlinks)) so that Node.js keeps the linked paths and does not dereference them.

**Comment by audunhy** [comment]
Thank you for a quick response.

You are correct the host Linux machine running vscode has the file on
```
/home/efd/dev/build_scripts/dev/websites/fipr/fiprweb.js
```
On the target arm machine i run Node from
```
/efd/web/sites/fipr/
```
with the file fiprweb.js. There are symlinks involved, the `/efd` folder is symlinked to `/media/mmcblk1p4/efd/`

Node parameter `--preserve-symlinks` had no effect, `--preserve-symlinks-main` is not implemented in v8.

Skipping the symlinked and start Node directly from `/media/mmcblk1p4/efd/efd/web/sites/fipr` folder resolved the unbound breakpoint problem. But i ran into other issues. If it is more correct to open a new issue please say so.

Two issues:
1.  Red breakpoint dot not visible in vscode.
2.  When a break point is hit, a new read only file is opened, with path set to target path `/media/mmcblk1p4/efd/efd/web/sites/fipr/fiprweb.js`

Did the following:

- Open file `/home/efd/dev/build_scripts/dev/websites/fipr/fiprweb.js` in code. No breakpoints set
- Start node on target in folder `/media/mmcblk1p4/efd/efd/web/sites/fipr/` like this `node --inspect=192.168.217.5:9229 fiprweb.js`
- Setting breakpoint in code by left-click left of line number 415 i fiprweb.js
    - Red dot is visible under cursor after click, but disappear men mouse is moved.
    - Breakpoint is set according to breakpoint view in side bar.
    - See image, just after breakpoint is set:
![vscode_breakpoint](https://user-images.githubusercontent.com/7504365/119132115-96743600-ba3a-11eb-8c38-b13a4991d002.png)
- Execution reach breakpoint and stops, but code open a read only version of the same file with this path `/media/mmcblk1p4/efd/efd/web/sites/fipr/fiprweb.js`. Here the breakpoint is shown correctly.

Here is the log for above session:
[vscode-debugadapter-8bcddc9d.json.gz](https://github.com/microsoft/vscode/files/6522273/vscode-debugadapter-8bcddc9d.json.gz)

I know I run an old version of Node. If you think Node version can be the cause of this, I can try to reproduce on a new version, but that will take some time, due to the embedded target. ( I might choose to not invest that time an live with the problem)

**Comment by connor4312** [comment]
Yea, what mentioned indicates that you're probably using Node 8. I strongly recommend you update, as you are two end of life versions behind. Node 8 has not received a security update for several years now, and can be buggy with debugging in general.

However, for now, the issue you're hitting can be resolved by adding:

```
"enableContentValidation": false,
```

to your launch.json (you will need to change the type from node to pwa-node for it to appear as valid).

**Comment by audunhy** [comment]
```
"enableContentValidation": false,
```
Resolved the issue.

I am very grateful that it works at all with a old version of Node, and that you spend time on helping me. I am fully aware of that we should upgrade, but not always so easy on an embedded system.
Thank you.
