### ISSUE TITLE
Codespaces progress notification makes links not clickable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#124279]
https://user-images.githubusercontent.com/35271042/119018546-08705080-b951-11eb-8505-0e063aa81629.mp4

1. Create a new codespaces using the vscode repo
2. Try clicking on the logs link
3. :bug: Unable to click on the link

Upon inspecting the DOM, it appears that elements are being added/removed/updated every second so that may be blocking the link from being clicked on

Codespaces Extension: v0.10.2
Version: 1.57.0-insider
Commit: 29c61570a5b9a669f777bb28b5acd5c37d99edbe
Date: 2021-05-20T05:11:47.260Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by roblourens** [comment]
Following up upstream first...

**Comment by roblourens** [comment]
@bpasero what do you think about not rerendering the notification message if the content didn't change between calls to report? In the codespaces extension I send fake progress updates to smooth out the progress bar, and you can't click a link if it updates at the moment you are clicking it

**Comment by bpasero** [comment]
@roblourens good catch, indeed we should not update the DOM when contents have not changed. Is this something you would be interested in doing a PR for?

I see to locations that could benefit of a check to not emit change events when nothing changed:
* [`updateSeverity`](https://github.com/microsoft/vscode/blob/be6a9027041c6136dfdf2571fa7a5092cbbf31d2/src/vs/workbench/common/notifications.ts#L621-L621)
* [`updateMessage`](https://github.com/microsoft/vscode/blob/be6a9027041c6136dfdf2571fa7a5092cbbf31d2/src/vs/workbench/common/notifications.ts#L626-L626)

I would think for the latter, a simple check for `.raw === .raw` would be sufficient.

**Comment by roblourens** [comment]
Sure

**Comment by roblourens** [comment]
PR: https://github.com/microsoft/vscode/pull/124621

**Comment by connor4312** [comment]
It looks like "starting codespace" is no longer a link:

![](https://memes.peet.io/img/21-06-142a2ccb-4828-4c97-baa8-afca65cbca20.png)

**Comment by misolori** [comment]
@connor4312 you have to create a new codespace in order for the build logs to appear, connecting to an existing one just resumes the codespace. I can try to reproduce.

**Comment by misolori** [comment]
Verified

<img width="1024" alt="CleanShot 2021-06-07 at 11 29 00@2x" src="https://user-images.githubusercontent.com/35271042/121070443-90dd5680-c783-11eb-9c95-db727a7247b9.png">
