### ISSUE TITLE
Find in files only gives results for recently opened files

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#12427]
- VSCode Version:152
- OS Version:10Ann

Steps to Reproduce:
1. close all open files and restart vscode (opening the same folder/project)
2. use ctrl+shift+f  (or whatever your shortcut is for finding within files)
3. type in a word that is in multiple files within the current folder/project
4. press enter
5. see that the results from one or more, (or all), files are not found
6. open one of the files
7. re-run search
8. see that the results for that file are now listed
9. open all other files one by one, re-running the search each time
10. see that results are only given for files that have been opened recently

This happened for me using xml files with the searched for word between arrow brackets. (e. g. ">word<")

**Comment by chrmarti** [comment]
- Which OS is this?
- What's the path to your folder?
- Do you see results for recent files after closing the editor or only for the open ones?
- Can you open the files through Ctrl+P (Cmd+P on OSX)?

**Comment by garfieldbanks** [comment]
1. Windows 10 Anniversary

2. C:\Users\<me>\Projects\<project>
    C:\Users\<me\Projects\<project>\dir_with_xml_files

3. I just tested this and yes the xml files seem only able to be searched when I have them open in the editor.

4. Yes ctrl+p shows the files.

I was able to reproduce this again immediately after updating to vscode153.

All I did was open my project folder. Type ctrl+shift+f. Type the word that is between arrow brackets (without the brackets). A single file is found.

I then open another file where I know I can find the word. I then repeat ctrl+shift+f and it is now able to find the the file I just opened.

I continue this process and one by one the files are found.

I then close those files and try to find the word again, and they no longer show up in the results.

**Comment by garfieldbanks** [comment]
Is this a bug or is there a setting I am missing that is turning off search for xml files?

This is my exclusion list:

**Comment by garfieldbanks** [comment]
I don't even have to restart or anything. As long the xml files are open, they are searchable. When I close them they become unsearchable.

**Comment by chrmarti** [comment]
Are you seeing this with other files than xml? Could you paste your settings and a screenshot from the search form with the additional options under '...' expanded? Looks like a bug.

**Comment by garfieldbanks** [comment]
I don't know if this affects files other than xml.

I removed my all of my custom user settings and restarted vscode and I was still able to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/12904270/18804177/c822572c-81b4-11e6-8c7f-19a4cb9a5e26.png)

**Comment by chrmarti** [comment]
Are there any special characters in your folder's path?

We compare the path of the open files with the folder VSCode opened on and include those that do not (seem to) be in the folder as extra files in the search. Maybe that check is failing for some reason I can't think of yet.

**Comment by garfieldbanks** [comment]
Nope. No spaces or numbers either.

**Comment by roblourens** [comment]
Search has been rewritten twice since this was filed, so hopefully it works now.

**Comment by zzzgit** [comment]
I have got the same problem

**Comment by jrmclau** [comment]
ditto

**Comment by roblourens** [comment]
Please open another issue with details, this issue is ancient.

**Comment by Trucoto** [comment]
I don't know if this is the same issue: #33307
