### ISSUE TITLE
Allow to close an Output channel

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#12424]
- VSCode Version: 1.5.2
- OS Version: Ubuntu, Win10

As some extensions create many output channels like in the figure below, there does not exist a way to kill these windows.

![vscode_output_channel](https://cloud.githubusercontent.com/assets/9464825/18738634/0c43528e-80d0-11e6-8f32-c2dc2a98b107.png)

Steps to Reproduce:
1. Install `Runner` extension.
2. Run something multiple times.

**Comment by jrieken** [comment]
@innerlee what extension is that? I'd consider it a bug on their side

**Comment by innerlee** [comment]
```Runner```

**Comment by jrieken** [comment]
https://github.com/mattn/vscode-runner/issues/21

**Comment by innerlee** [comment]
In fact there is a behavior I didn't mention. If you right click and select ``Clear Output``, then all the outputs with title ``Runner: j a.jl`` will be cleared. Note that other channels like ``Git`` or ``Tasks`` are not affected. I think that ``vscode`` only allow one output channel with the same name, but it did not check this constraint in the name list as shown in the figure.

**Comment by jrieken** [comment]
hm, good point. cc @isidorn for the rules of output channels and name reuse?

**Comment by isidorn** [comment]
Names of output channels can be reused we use an internal id generated [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostOutputService.ts#L12)

Clearing one output channel should not clear the rest and that sounds like a bug - please create an issue if you see that.
