### ISSUE TITLE
windows opened with windowOpenNoOpenerWithSuccess hang sometimes while debugging in devtools

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#124231]
In Chrome sometimes opened window is sharing event loop with the original window, in cases like the same origin or the same parent domain. If one tries to debug one of such windows then others are hanging.

I was wondering whether it is better to rewrite like that:
```ts
export function windowOpenNoOpenerWithSuccess(url: string): boolean {
	const newTab = window.open();
	// pop-up allowed
	const success = !!newTab;
	// close immediately to avoid rendering
	newTab?.close();
	if (success) {
		// open safely with own event loop
		windowOpenNoOpener(url);
	}
	return success;
}
```

Updated: i tried with above and it does not help, Chrome blocks new windows besides first by default.

**Comment by alexdima** [comment]
To avoid sharing the same event loop or whatever, I suggest to adopt `windowOpenNoOpener`. But that one does not return true/false if the window opened.

I left in this particular place `windowOpenNoOpenerWithSuccess` to maintain the existing behavior. I think this returned boolean was added as part of the Safari/iPad work.

**Comment by isidorn** [comment]
Yes the returned boolean was added as a way for us to know if the window opened successfully. Since Safari sometimes blocks new windows / tabs.

**Comment by alexdima** [comment]
@isidorn You could invoke different methods based on the browser: the one without a return value in Chrome / the one with a return value in Safari.

**Comment by isidorn** [comment]
@alexdima this makes sense
@akosyakov we are open to a PR which implements this as @alexdima suggested.
