### ISSUE TITLE
Enable Replace in Jupyter Notebooks

### ISSUE THREAD

**Issue by abergerSRS** [microsoft/vscode#124297]
Find (Ctrl+F) works in a Jupyter Notebook, but Replace (Ctrl+H) does not. Replace is a critical tool when writing code. Could this be added to Jupyter Notebooks in VS Code? I realize there is the complication of the underlying JSON. Replace should work just on code cells, and not throughout the underlying JSON.

**Comment by abergerSRS** [comment]
I just discovered that this feature exists in the Insider's Build of VSCode.

**Comment by rebornix** [comment]
@abergerSRS this will be available once Jupyter extension ships this feature to Stable users.
