### ISSUE TITLE
Remeber tabs per branch

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#124277]
I find that the group of files (tabs) that I work on from one branch to another in a given (i.e. git) repo can differ quite a bit and find my self opening and closing files (tabs) as I switch back and forth between branches.

It would be nice if open tabs (i.e. files, but could be other tabs) were remembered per branch such that as I switch from one branch to another, the tabs for that branch are restored into the workspace from when I last switched away from that branch.

**Comment by snoozbuster** [comment]
Are there any plugins out there that can do this?
