### ISSUE TITLE
VS Code freezes after any attempt to edit or close a file opened from search view

### ISSUE THREAD

**Issue by mesquitagomes** [microsoft/vscode#124204]
VS Code freezes after any attempt to edit or close a file opened from search view. Some times when I wait long enough it backs to life.

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic

CPUs | Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 3400)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 15.41GB (3.38GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id b5a06dd1-2da5-402c-9e79-0d1df2d454c4
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
    0	   174	 28464	code main
    0	    32	 28467	   zygote
    0	   126	 28491	     gpu-process
    0	    32	 28468	   zygote
    0	    79	 35811	     window (Issue Reporter)
    0	    79	 28513	   utility
    0	   110	 28568	   shared-process
    0	    63	 28603	     ptyHost
    0	     0	 35886	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 35887	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   252	 33679	   window (● FileName.sql - backend - Visual Studio Code)
    0	   126	 33712	     extensionHost
    0	    79	 33763	       dotnet /home/mtuser/.vscode/extensions/oracle.oracledevtools-19.3.4/out/server/OracleVSCodeServer50.dll -enableLogging false -loglevel Error -LogFile /home/mtuser/.config/Code/logs/20210519T171548/exthost1/Oracle.oracledevtools/OracleVSCodeServer.log -locale en
    0	    95	 33724	     watcherService
    0	    63	 34088	     searchService

|  Window (● FileName.sql - backend - Visual Studio Code)
|    Folder (backend): 4301 files
|      File types: sql(3919) txt(11) SQL(7)
|      Conf files:

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 13.0.4
xml | Dot | 2.5.1
oracledevtools | Ora | 19.3.4
change-case | wma | 1.0.0

AB experiment info

vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

**Comment by roblourens** [comment]
Strange, does it happen with any file? And if you open the same file through the explorer or another way, it doesn't happen?

Does it happen if you start vscode with `--disable-extensions`?

**Comment by roblourens** [comment]
Are you getting a really long match from search? Maybe a multiline match? That can cause perf issues.

**Comment by mesquitagomes** [comment]
> Are you getting a really long match from search? Maybe a multiline match? That can cause perf issues.

Not that big, less then 100 matches. Looks like the complexity of the RegExp, like xxxx(msg|log)(?:.+\n*){1,5}?yyyy and the number of matched characters is impacting the perf. I have no issues when I'm using the RegExp like this '.*yyyy.

**Comment by roblourens** [comment]
A regex like that might trigger explosive backtracking which can cause freezes in vscode, as in https://github.com/microsoft/vscode/issues/30874

**Comment by mesquitagomes** [comment]
Duplicated by #30874
