### ISSUE TITLE
Python Syntax Highlight Optional Fix

### ISSUE THREAD

**Issue by adamkeinan** [microsoft/vscode#124234]
After banging my head against the wall for days, switching between themes, and hacking the Vscode settings I've found a little solution to an issue I have been trying to solve online for days: The Python Syntax Highlight(which was broken).
according to my understanding, the textMateRules is unmaintained for a while and so the alternate option is using 3rd party options or hacking the settings.

My solution is this:
Simply Add This line:
```
"workbench.colorCustomizations": {
    "[python]": {    <--- Language
<---ONLY IF YOU WISH TO EDIT--->
EXAMPLE:
    "editor.foreground": "#some_color",
    "activityBarBadge.background": "#some_color",
    "activityBar.background": "#some_color",
    "sideBarTitle.foreground": "#some_color",
    "sideBar.border": "#some_color",
    "sideBar.background": "#some_color",
    }
},
```
This Setting is of course temporary. But immediately solved my problem since the Python LSP and linter inherited the theme settings, and respected them.

**Comment by aeschli** [comment]
I'm not sure I understand. Do you have a color theme called `python` which is broken and you fixed it by customizing the colors in the settings? 
I suggest to file an issue against the theme then (it must come from an extension, you have to find out which one)
