### ISSUE TITLE
No Device Issue in VS Code

### ISSUE THREAD

**Issue by himanshu717171** [microsoft/vscode#124225]
I am not getting Device Info in VS Code. Due to this I can not use Debugger for debugging Flutter Project.
I have attached the Screen Shot in which I have highlighted with red box.
Only 2 Extensions I am using. 
Please help me out. This is really bad and frustrating issue. 

![Screenshot (213)](https://user-images.githubusercontent.com/38049620/118932874-2ac09900-b966-11eb-817d-4628bff6c04e.png)

**Comment by himanshu717171** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Regarding Device in Bottom Right Corner (#121997)](https://www.github.com/microsoft/vscode/issues/121997)

No Solved

**Comment by weinand** [comment]
Please file this against the Dart or Flutter extension
