### ISSUE TITLE
Toggle Word wrap doesn't work on mac os when cursor is on text

### ISSUE THREAD

**Issue by iDarkknight** [microsoft/vscode#124224]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: Mac OS Big Sur 11.3.1

Steps to Reproduce:

1. Focus cursor on text in editor
2. [alt]z gives print ˀ

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/41024 . The root cause is a well known Chromium issue -- https://bugs.chromium.org/p/chromium/issues/detail?id=887519
