### ISSUE TITLE
Help problem

### ISSUE THREAD

**Issue by faeizalzhafrey** [microsoft/vscode#124221]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

![Screenshot (136)](https://user-images.githubusercontent.com/77710535/118916816-44f87800-b962-11eb-8af3-8b8c73cbb8e4.png)

please help

**Comment by faeizalzhafrey** [comment]
Sorry for the late reply, i couldnt connect to my github to vscode and this error message appear

**Comment by TylerLeonhardt** [comment]
@faeizalzhafrey so that I can better understand what you're seeing, do you think you could provide a gif/video of you going through the flow that got you to this error?

If you can't do that, some step-by-step screenshots would be ok.
