### ISSUE TITLE
Intellisense not working on network drive

### ISSUE THREAD

**Issue by archonik** [Microsoft/vscode#12423]
- VSCode Version:

```
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
Date 2016-09-12T13:30:03.456Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
- OS Version: 

```
Windows 10,  1607, build 14393.187
```

Steps to Reproduce:
- Map network drive
- Open angular2 starter project
- No errors in tsc verbose mode, nothing is happening, tsc server not starting probably
- Developer console is not showing anything

**Comment by chrmarti** [comment]
Could you enable tracing in the settings and let me now what the output in the Output panel for TypeScript is:
```
"typescript.tsserver.trace": "verbose"
```

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
