### ISSUE TITLE
Cannot tab to snippet variable

### ISSUE THREAD

**Issue by dballance** [Microsoft/vscode#12420]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create snippet with multiple variables.
2. Activate snippet in editor
3. Update first variable
4. Hit tab, enter, anything -- cursor will not jump to next variable position.

Notes: 

- Tab does just that, tabs.
- Enter seems to exit snippet mode, but also doesn't jump
- The following is set in keyboard shortcuts: 
```json
{ "key": "tab", "command": "jumpToNextSnippetPlaceholder",
                 "when": "editorTextFocus && inSnippetMode" },
```

Example of expected behavior -- the below behavior does not work in 1.5.2 as far as I can tell.
![](https://github.com/johnpapa/vscode-angular2-snippets/raw/master/images/use-extension.gif)

Snippet from: https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2

**Comment by alexandrudima** [comment]
@dballance

Works for me in 1.5.2 with no settings and no extensions installed. 

![snippets](https://cloud.githubusercontent.com/assets/5047891/18750049/29412bb0-80e2-11e6-9794-95980248abca.gif)

**Comment by alexandrudima** [comment]
Maybe you can open the keybindings and search who binds "tab" in there -- perhaps some extension?

**Comment by dballance** [comment]
@alexandrudima -- dug a little more, thanks for the suggestion! 

Appears it was an extension which was binding tab for other purposes. The [author is aware](https://github.com/jakethashi/vscode-angular2-emmet#known-issues), so I'll close this. 

Thanks!
