### ISSUE TITLE
Revisit markdown having to scan over all markdown files in workspace for open symbol

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124276]
Extracted from https://github.com/microsoft/vscode/issues/124176

I find it questionable that we need to read all markdown files from the entire workspace in parallel. We should consider to add a maximum cap and also possibly debounce this and not just join all promises in parallel:

https://github.com/microsoft/vscode/blob/d5f4e119e058e1d01ec4f994f757703348c37db8/extensions/markdown-language-features/src/features/workspaceSymbolProvider.ts#L29-L33

**Comment by nrayburn-tech** [comment]
> debounce

It looks like `getAllMarkdownDocuments` is only used once on the first request for symbols.  After the initial request, the values are cached.  I don't think debouncing will help here.

> add a maximum cap

I can add a config option, similar to how the max line tokenization is.

> not just join all promises in parallel

What is meant by not joining all promises in parallel?  Something like this in a loop for a chunk of files each time?
```ts
await new Promise((resolve) => {
  setTimeout(() => {
    await Promise.all(resources.slice(i, i + 10).map(doc => this.getMarkdownDocument(doc));
    resolve();
  });
});
```

**Comment by mjbvz** [comment]
I believe @bpasero is suggesting that we use a pool to only allow a certain number of file reads to be active at a time. We'd still read all the files in the workspace, but only let a set number of files—say 20—be open at a time. I think `graceful-fs` may be doing something like this automatically behind the scenes
