### ISSUE TITLE
Jupyter notebooks' plots persist when their cells are deleted.

### ISSUE THREAD

**Issue by Adam-Antios** [microsoft/vscode#124206]
The following behaviour have been exhibited in VS Code Insiders version 1.57.0 running in both Linux (Ubuntu 20.04, Lubuntu 20.04) and Windows 10.

When I create a plot and delete the cell, then the output does not get deleted as it should but persists in the background permanently until I close the notebook. 

![output](https://user-images.githubusercontent.com/17729838/118886199-4f365a00-b901-11eb-9211-c64b24621dc7.gif)

**Comment by rebornix** [comment]
@Adam-Antios please update to the latest Insiders, which should have fixed this issue.
