### ISSUE TITLE
Do not recognize Debian's .install file as a shell script

### ISSUE THREAD

**Issue by peat-psuwit** [microsoft/vscode#124295]
Issue Type: <b>Bug</b>

Debian's `.install` files is in a Debian-specific format controlling how Debian binary packages are constructed. They are not a shell script file, and should not be recognized as such.

1. Clone any repository with a Debian packaging (e.g. https://gitlab.com/ubports/core/suru-icon-theme). Or:
    - Create a new directory.
    - Create a subdirectory called debian/.
    - Create a file called debian/something.install
2. Open VSCode inside the directory or repository.
3. In the file explorer, open the subfolder debian/, then open any file with `.install`.

Expected result: The file is recognized as a plain text file.
Actual result: The file is recognized as a shell script. If one installs the shellcheck extension, now the extension produces false positives.

VS Code version: Code - Insiders 1.57.0-insider (0b355ffc89b2020a941ce149f2704acf13a49afd, 2021-05-20T17:08:28.621Z)
OS version: Linux x64 5.11.19-051119-generic snap (Ubuntu 20.04)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 1522)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.06GB (0.75GB free)|
|Process Argv|--force-user-env --unity-launch|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805cf:30301675

```

</details>

**Comment by aeschli** [comment]
I didn't out who uses `install` as file extension so I removed it.
