### ISSUE TITLE
hover is too narrow

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12428]
My editor has all the horizontal space but the hover is still very narrow forcing me scroll which isn't a nice experience. 

![sep-22-2016 09-33-45](https://cloud.githubusercontent.com/assets/1794099/18740025/c043d4ee-80a7-11e6-812e-e892db65f88e.gif)

**Comment by joaomoreno** [comment]
I've gotten it a few times, quite ugly yes.

**Comment by jrieken** [comment]
@joaomoreno Really? You know we have no control over this and even if it's a single line of code (a method signature) which I would never wrap. This is a regression over existing behaviour, bold move backlogging this.

**Comment by alexandrudima** [comment]
:+1: with the following settings I get a horizontal scrollbar very often in the hover. It feels like a layouting bug:
```
  "editor.fontFamily": "Hack"
, "editor.fontSize": 16
```

**Comment by joaomoreno** [comment]
Alright let's put it in.

**Comment by joaomoreno** [comment]
Not same, moved to #13004.

**Comment by jrieken** [comment]
Adding 62px doesn't cut it for me. How about something that scales with the editor dimensions?

**Comment by joaomoreno** [comment]
The `break-all` also changed something. Doesn't that cut out for you?

**Comment by jrieken** [comment]
It still gives me a scroll bar even though it could take a lot more horizontal space

![sep-29-2016 17-48-18](https://cloud.githubusercontent.com/assets/1794099/18961334/fb09cbc2-866c-11e6-963a-2bc156484281.gif)

**Comment by joaomoreno** [comment]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/22350/18961553/aba151f8-866d-11e6-86d2-d6302fe9fad1.png)

**Comment by jrieken** [comment]
That's shows something different, the definition, not the reference. Also it as the preview shown. Put this code in `TrimWhitespaceParticipant` and hover in the ctor

```ts
	constructor(
		@IConfigurationService private configurationService: IConfigurationService,
		@ICodeEditorService private codeEditorService: ICodeEditorService
	) {
		// Nothing
		configurationService.onDidUpdateConfiguration(this.onConfigurationChangeEvent, this);
	}

	private onConfigurationChangeEvent(config: any): void {
		
	}
```

**Comment by joaomoreno** [comment]
I tell you man, you ain't got the latest

![image](https://cloud.githubusercontent.com/assets/22350/18969439/79ae9956-868d-11e6-83e6-8eb5afd19e58.png)

**Comment by joaomoreno** [comment]
We can still make it grow more :wink: but I think rolling with this for now isn't total crap.
