### ISSUE TITLE
Custom Editor toggleEditorType Command Only Works One Way

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#124211]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56
- OS Version: Windows

Steps to Reproduce:

1. Go to a file with a filetype that has supported custom editors installed. Switch to a custom editor view.
2. Try the `View: Toggle Editor Type` command. The editor should switch to the text editor. 
3. When doing this again, the editor does nothing. However, it should be switching to the highest-priority custom editor.

**Comment by lramos15** [comment]
\closedWith 67bd4e206961dadb4e0d5eb368f97d3a031f4d1f
