### ISSUE TITLE
Code is not getting a proper focus when opening from command line

### ISSUE THREAD

**Issue by smuuf** [Microsoft/vscode#12425]
- VSCode Version: 1.5.2
- OS Version: Windows 7
- **Not** running VSCode as administrator or with any compatibility options enabled.

I'm not sure if this is a *bug report* or a *feature request*, so please let me know if this is happening just to me / just to Windows 7 / etc.

Steps to Reproduce:

1. Use command line to open VSCode *(with or without a file being specified)*
2. Behold at the blinking Code's taskbar item and not at the Code's window, which - by my opinion - should have been thrown on the top of other windows.

**Some visual context:**

![bug](https://cloud.githubusercontent.com/assets/6860713/18738777/0ed7d596-809f-11e6-839c-9a97790fa516.gif)

This is happening when I'm trying to run Code from/using:
- WScript's `shell.exec()`
- Total Commander's command line *(as in the pic)*
- Windows' `cmd.exe`

**Comment by chrmarti** [comment]
Reproduced on Windows 10 when there is a Code window already open and I launch a second one for a different folder.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/929
