### ISSUE TITLE
No emmet snippets for the details and summary tags

### ISSUE THREAD

**Issue by a0m0rajab** [microsoft/vscode#124247]
The details/summary tag is missed from the intellisense!

**Comment by aeschli** [comment]
Please add a small code sample and a screenshot.

**Comment by a0m0rajab** [comment]
Here is the tag that I am trying to use:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

For the screenshot, it's just simple, when you type "detai" I can't get any suggestions for the tag itself, yet when I type "html" for example I got few skeletons to use.

Sent from mobile device


________________________________

**Comment by aeschli** [comment]
This html snippets come from emmet.

**Comment by a0m0rajab** [comment]
@rzhao do not you think that details and summary should be at the same emment since they both used inside each other? 

I mean when you type: details 

You should got this snippet: 

<details> <summary> CURSER1 </summary>
CURSER 2</details> 

By curser 2 I mean after pressing tab.

**Comment by rzhao271** [comment]
The detail and summary snippets should work on the latest [VS Code Insiders](https://code.visualstudio.com/insiders/) on the next update (within 48 hours).
