### ISSUE TITLE
Add preference to delete files permanently by default.

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#12426]
- VSCode Version: 1.5.2
- OS Version: Ubuntu

When running vscode on a server (``ssh -Y ...`` to that server), delete to trash bin seems not working. You will get an error msg every time when deleting a file. This is annoying.

![vscode_delete_permantly](https://cloud.githubusercontent.com/assets/9464825/18738960/bf843262-80d2-11e6-8711-5d7f913005af.png)

Steps to Reproduce:

1. login to another machine via ``ssh -Y ...`` and run ``code`` there.
2. try to delete a file.

**Comment by bpasero** [comment]
Starting with our 1.6 release you can hold the Shift key while clicking on delete in the menu and that will bypass the trash. Would that help?

**Comment by innerlee** [comment]
That's nice 😊

**Comment by bpasero** [comment]
This is now very easy in 1.6: you can either press shift when selecting the "Delete" option from the context menu or by just pressing the delete key and holding shift. I think this is good enough and typical OS behaviour. Closing.
