### ISSUE TITLE
When developing in Remote Container, Debugger "Call Stack" needs a "refresh" action

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#124371]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Create a Docker container with nodejs
- Attach to this container using Remote Containers for NodeJS development
- create multiple http servers
- create a pm2 config to launch all of them on different ports
- create a script in package.json where `debug` maps to `pm2-runtime pm2-app.config.js`
- start them using the `yarn debug`
- kill the process after VS Code has had a chance to watch them stabilise and forward the ports to those

Actual behaviour:
- Notice that the call stack stills hows the processes running, while the `ps -aef | grep node` would tell you nothing is running.

Expected behaviour:
- VS Code should detect the process died
- Give a "refresh" button, just like on the files / git sections, to force check and clean up the debug call stack

Extension version: 0.177.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0
Remote OS version: Linux x64 4.14.231-173.361.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|--crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:50d0ed8536051f0eaa14651b684d2a18bd49d1bab73eead2d11be57addf850c1 (/nk-dev-conn_pm2_1) @ aws-docker|
|OS|Linux x64 4.14.231-173.361.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (5.11GB free)|
|VM|0%|
</details>

**Comment by connor4312** [comment]
Thanks for the steps, but I'm not very familiar with pm2. If it isn't too much trouble, could you throw together a quick sample repro for us to test against to make sure we can reproduce it?
