### ISSUE TITLE
Editor overrides should work with untitled inputs (without resource)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124352]
The fact that each editor override requires a resource to work with, forces us to create instances of `UntitledTextEditorInput` for the case of untitled editors to get at the resource. We should not do that going forward because the untitled resource from these inputs is reserved exclusively for untitled text editors and nothing else.

As such I suggest that editor overrides can work without resources for the case of untitled editors. We may still need an extra property to narrow down the possible list of editor overrides to select from, maybe by providing a file extension?

**Comment by lramos15** [comment]
Closed via #126918
