### ISSUE TITLE
Add basic language support for Dart

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#124342]
Following on from @aeschli's comments at https://github.com/Dart-Code/Dart-Code/issues/3327#issuecomment-845731618, it would be good to have basic Dart language configuration as a built-in extension in VS Code, allowing things like syntax highlighting to in the case where the Dart extension is not installed (for example a Live Share client that hasn't installed it) or is disabled (for example in an Untrusted workspace).

From [the comments here](https://github.com/Dart-Code/Dart-Code/issues/3327#issuecomment-845731618):

> We don't want to own and maintain any TextMate grammars so it's important to us that we can rely on a well maintained TextMate grammar that we can import from another repo. That repo would host the latest grammar and we will forward issues to it.

There is a Dart Team-owned grammar here that can be used - it's the [same one Dart-Code uses](https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json) (except for a small bug fix that I'll file an upstream PR for shortly):

https://github.com/dart-lang/dart-syntax-highlight/blob/master/grammars/dart.json

> Migration is not an issue, you can just depend on the new extension. If you still define a grammar and language configuration, your contributions will win over the one from the basic extension. Of course the idea is that you eventually can remove the grammar and configuration.

Great! Though what's the advantage of depending on the built-in extension? I try to support a few-versions-old VS Code where possible (so wouldn't do that for a few versions) but also the extension is published to open-vsx.org for use by other clients so the dependency may complicate things (if they don't have the same built-in).

> I don't know how GitPod/Theia get to the basic language extensions of the languages we have built-in. Maybe they take it from our repo.

I'd probably do some investigation into this before removing anything from Dart-Code then (it sounds like there's no downside to having the grammar/config provided by both for a period anyway).

(fyi @devoncarew @timsneath)

**Comment by aeschli** [comment]
> Though what's the advantage of depending on the built-in extension
It also works without a dependency, but only because the extension is built-in. 

No problem if the Dart extension keeps the grammar and language configurations for a while until it is all settled. 

Do you want to look into a PR or should I?

**Comment by DanTup** [comment]
> Do you want to look into a PR or should I?

If it's easier/quicker for you to do, feel free. Otherwise I'm happy to do it but may need some pointers for how built-in extensions are set up.

**Comment by aeschli** [comment]
I pushed the PR
@alexr00 We have a new built-in language :-)

**Comment by DanTup** [comment]
Super, thanks!

For future reference - for changes to the language config I can send a PR to `extensions/dart/language-configuration.dart`, and for grammar changes I can run `npm run update-grammar` (after the changes are landed in the upstream dart-lang repo)?

**Comment by DanTup** [comment]
>  I can send a PR to `extensions/dart/language-configuration.json`

I just noticed in the `package.json` it has the path `./syntaxes/dart-language-configuration.json` but this doesn't seem to match the location of the file `./language-configuration.json`?

**Comment by aeschli** [comment]
Good catch, thanks. Pushed the fix: https://github.com/microsoft/vscode/commit/5d534b94f8372e8fc93dc96987e39da532886d90

**Comment by alexr00** [comment]
@DanTup For grammar changes, I'll pull them in about once per month so you can just rely on that if you want. If there's a change that needs to be picked up sooner than that, then feel free to make an issue an @ mention me and I'll pull in the change earlier.

**Comment by DanTup** [comment]
Perfect, thanks!

**Comment by mit-mit** [comment]
@alexr00 @DanTup is this support in the Code May Update (1.57) that just went out?

**Comment by alexr00** [comment]
Yes, you can tell what release an issue is in by looking at the Milestone.

![image](https://user-images.githubusercontent.com/38270282/121909855-9cee8880-cd2e-11eb-83c2-436f7209f9d7.png)

**Comment by DanTup** [comment]
Yep! An easy way to test it's working is to disable the Dart/Flutter extensions (accept the prompt to reload), then open a Dart file. You'll now still get syntax highlighting (note: you won't get analysis or much other editor functionality, that requires the Dart extension).

<img width="650" alt="Screenshot 2021-06-14 at 15 52 25" src="https://user-images.githubusercontent.com/1078012/121912663-aecd2d00-cd28-11eb-9335-bf4eaad18b75.png">

**Comment by mit-mit** [comment]
Yeah I just did, and it works great :-)
