### ISSUE TITLE
Seetings Sync is disabled because the current device is making too many requests.

### ISSUE THREAD

**Issue by ivanjeremic** [microsoft/vscode#124380]
Issue Type: <b>Bug</b>

I was going through my vscode themes to find a new theme, I do these very often when I get bored of my current theme so I used only key arrow up and down to go through the list I have not even selected one and got this error after 5 minutes of searching for a theme, 

```
Settings Sync is disabled because the current device is making too many requests.
```
From what I see it is making a request by simply going up and down through the list, I would find it better to only send a request out if I select a theme click/press enter. That way the issue with sending too many requests would be solved.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (3.10GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/home/inux/institut-fuer-bewegende-kuenste --crash-reporter-id d92169a2-b12d-4566-ba86-6f5d6791a589|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|Memory (System)|12.45GB (5.36GB free)|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
vscode-browser-preview|auc|0.7.1
vscode-styled-jsx|bla|2.0.0
bracket-pair-colorizer-2|Coe|0.2.0
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vsc-material-theme-icons|equ|1.2.2
vue|jcb|0.1.5
remote-wsl|ms-|0.56.2
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.6.0
mdx|sil|0.1.0
vscode-icons|vsc|11.4.0
material-theme|zhu|3.10.14
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.6
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
vscode-eslint|dba|2.1.20
vscode-wasm|dts|1.3.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
go|gol|0.25.0
vscode-graphql|Gra|0.3.16
mongodb-vscode|mon|0.5.0
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.3
cpptools|ms-|1.3.1
vscode-react-native|msj|1.4.2
reload|nat|0.0.6
color-highlight|nau|2.3.0
vetur|oct|0.33.1
vscode-thunder-client|ran|1.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
rust|rus|0.7.8
svelte-vscode|sve|104.12.2
docker|vsc|1.0.0
yaml|vsc|1.0.0
wappnode-core|Wap|0.0.1
codesandbox|yes|0.0.8

(41 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/91286
