### ISSUE TITLE
"Trust this folder" message appears when there's no folder opened

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#124392]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-insider (user setup)
Commit: 4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
Date: 2021-05-21T05:13:41.097Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
- OS Version: Windows 10

Steps to Reproduce:

1. I just launched VS Code with no folder open.

Bug: See the screenshot. It mentions "Trust this folder" but I don't have a folder open.
![image](https://user-images.githubusercontent.com/19859882/119188531-a2a6c600-ba2f-11eb-8c47-87964f4b4211.png)

**Comment by sean-mcmanus** [comment]
@vscodebot This doesn't appear to be a duplicate.

**Comment by sbatten** [comment]
Thanks @sean-mcmanus, there is a new setting for how to treat empty workspaces. 
![security.workspace.trust.emptyWindow](https://user-images.githubusercontent.com/6561887/119397054-818de180-bc8a-11eb-8e19-1fb01d916ed7.png)

I see one bug from the screenshot is that we should not say folder, but rather "workspace" or "window" in this case.

The default for this setting is to use restricted mode in an empty window, but I have seen some confusion about this, and the Out-of-the-box experience is a little fishy with this default.

**Comment by sean-mcmanus** [comment]
Yeah, I don't understand why an Empty Window can't be trusted...so I don't know how to make a decision in regards to whether I should trust it. If there's a reason, maybe that could be provided too?

**Comment by sbatten** [comment]
An empty window is not necessarily empty. It is quite common to open "loose files" in VS Code without opening a workspace/folder. In this case, extensions will be able to access these files and need to know how to treat these files with respect to trust.

**Comment by gregvanl** [comment]
I think the banner message is confusing since there isn't an open folder. 
Should the message in this case be: "Restricted mode is intended for safe code browsing. Trust this window to enable all features."

**Comment by gregvanl** [comment]
Not sure how flexible some of the other UI is but the Extensions view Workspace Trust hover also mentions a "workspace" when no folder is open and should probably say "window".

![image](https://user-images.githubusercontent.com/12818376/119600751-8d69c880-bd9c-11eb-9e88-d76b57665322.png)

This might be tricky for the limited extension provided hovers.

**Comment by sbatten** [comment]
for the OOBE issue, we are trying this commit: https://github.com/microsoft/vscode/commit/e3c8ff57849bf854e97abd0d1b78ba5a92d3a801

until a file is opened in an empty window, the banner is not shown

**Comment by sean-mcmanus** [comment]
Cool, that's a good idea.

**Comment by lszomoru** [comment]
We also fixed so that all visual elements (status bar, banner, editor) use window/folder/workspace consistently.
