### ISSUE TITLE
why do I need to press Ctrl + S to save 2 times for saving file?

### ISSUE THREAD

**Issue by shreejibawa** [Microsoft/vscode#12433]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open any file and do some changes
2. Save the file it will save not save in single save

**Comment by chrmarti** [comment]
What extensions do you have installed?

**Comment by shreejibawa** [comment]
[image: Inline image 1]

**Comment by chrmarti** [comment]
Does the JS-CSS-HTML Formatter interfere with Save? Could you retry with that extension uninstalled? (I'm guessing here, yours is the first such report I see.)

**Comment by shreejibawa** [comment]
​Yes that was the issue. Resolved now by changing its configuration. thank
you very much.​
