### ISSUE TITLE
Filename search doesn't show/follow symlinks [Explorer] [Sidebar \ Folders] [Windows Symbolic Link]

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#124341]
Issue Type: <b>Bug</b>

1. Get a folder with Windows Symbolic Link, in the `Sidebar \ Folders` (don't unfold/open it) .
2. Focus the pane and start typing name of the symlink .
3. Hover over the showed orange 'filter' and click "Enable Filter on Type" .

### Additional
after opening the folder with symlink, 1nce . such starts being shown on such search .
`settings.json \ search.followSymlinks`

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
This is not implemented and is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by irvnriir** [comment]
Its not a feature request, its obvious and serious bug .

**Comment by irvnriir** [comment]
(which in my case doesn't allow to search for file/folder-s in VSCode)
