### ISSUE TITLE
Vscode ignoring default terminal at open on windows

### ISSUE THREAD

**Issue by jsnoriegam** [microsoft/vscode#124323]
Issue Type: <b>Bug</b>

1. Set the default integrated terminal profile to command prompt
2. Open one integrated terminal leave it open and close vscode
3. Open vscode

Expected result:
vscode with CMD terminal

Actual result:
vscode with Powershell terminal

If I create a new terminal it uses the default profile, the issue is only when vs code opens

Tried running code with extensions disabled but still the same problem

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.39GB free)|
|Process Argv|--crash-reporter-id 1657d577-4e6e-43d5-b20c-ecf20b1e7f85|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.1
laravel-blade-vscode|ami|2.0.3
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-solution-explorer|fer|0.4.3
docker-explorer|for|0.1.7
kotlin|fwc|0.2.22
beautify|Hoo|1.5.0
dotnet|leo|1.3.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-pylance|ms-|2021.5.3
remote-wsl|ms-|0.56.2
notepadplusplus-keybindings|ms-|1.0.7
gradle-language|nac|0.2.3
awesome-flutter-snippets|Nas|2.0.4
vs-sequential-number|nep|1.1.0
vetur|oct|0.33.1
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
vscode-gradle|ric|3.6.1
vscode-gradle-extension-pack|ric|0.0.2
phpdoc-generator|ron|1.1.1
php-ci|sma|0.4.2
sonarlint-vscode|Son|1.22.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1

</details>

**Comment by maplion** [comment]
I am also experiencing this issue and it is quite annoying.  This seemed to begin happening with an update within the last couple of weeks.  I have always had `    "terminal.integrated.defaultProfile.windows": "Git Bash",` in my settings, but now every time I reload the window or start a new one, it opens Powershell.
