### ISSUE TITLE
[feature] Swap selection contents

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#12435]
A feature that I often used in Sublime Text is text swapping. `ctrl+T` would swap the content when you had two selections active.

**Comment by realappie** [comment]
Any status on this?

**Comment by mrmlnc** [comment]
@realappie, you can find out the current status of this project, using the `iteration-plan` label: https://github.com/Microsoft/vscode/labels/iteration-plan

**Comment by realappie** [comment]
@mrmlnc I was wondering if there is any status related to this feature. There is nothing in the iteration plans that mentions this feature, so the link you have sent me is kind of irrelevant :(

**Comment by realappie** [comment]
@ivancuric Check out [this](https://marketplace.visualstudio.com/items?itemName=v4run.transpose#review-details) extension!

**Comment by ivancuric** [comment]
Thanks :) Already forgot about this issue since I've been using the same extension for months now :)
