### ISSUE TITLE
Test setup/configuration experience

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#124328]
As mentioned in https://github.com/microsoft/vscode/issues/107467#issuecomment-728265071

> A stretch goal: In addition to standard UI, it would be great if this can also address our users' biggest pain point, which is often the test setup, env configuration, etc... how about something like a "test config", similar to a debug config, that Provider can provide snippet or even wizard to help set up in launch.json?

That's an interesting idea. Currently test extensions generally hook into your existing test setup. I have not thought about it from the perspective of the test extension actually being the entrypoint to testing, but as tests become built-in this can happen in the same way we've been pushing the VS Code (particularly JS) debugger to be the entrypoint to debugging...

----

In Java we have a very similar request. Currently the Java test runner will resolve a debug configuration, and then pass that configuration to Java Debugger to launch the tests.

Then users may want to make some configuration to leverage the debugger's settings/capability when launch the tests.

If VS Code as a platform can provide a solution to make the test configuration align with the debugger, that could be great!

**Comment by connor4312** [comment]
For the initial testing setup, you can now contribute to the testing "welcome" view, like you can in the debug view. You could also trigger a setup experience, if necessary, the first time the user tries to 'debug' a test.

**Comment by jdneo** [comment]
Thank you @connor4312 welcome view is a great idea to help user initialize test setup!

And meanwhile, in Java we have another request to make the test runner works better together with the debugger. Here is an example for illustration:

In Java the user may want to customize the JVM(Java Virtual Machine) arguments when launching the program. In Debugger, we having a field `vmArgs` in the `launch.json` to let users set the arguments there. The same request applies to the testing.

But, we don't want to persist test configurations to user's launch.json because user's project may have a lot of tests, thus, that could make a large change to the user's source control. To solve the problem, we have a VS Code setting to let user set their test configurations, and they can pick one when launching a test.

The extension configuration has its limitation -- it's static. So, when the debugger side adds a new capability in its launch configuration scheme, the test runner side cannot automatically match it unless adding that into the extension configuration in `package.json`.

I'm not sure if there is any solution to perfect solution to deal with this. I'm thinking that since now VS Code has both the Testing and Debugging API exposed to the extensions, if VS Code can provide a platform-wise solution to make testing and debugging working together, that might solve this issue.

**Comment by jdneo** [comment]
@connor4312 BTW, what's the view ID of the test view if I want to contribute a welcome view there?

**Comment by connor4312** [comment]
> I'm not sure if there is any solution to perfect solution to deal with this. I'm thinking that since now VS Code has both the Testing and Debugging API exposed to the extensions, if VS Code can provide a platform-wise solution to make testing and debugging working together, that might solve this issue.

The difference there is that debugging is and has historically been an IDE/editor-driven feature. For most languages, there is no standard 'debug configuration' file. Testing has traditionally been CLI-based, and as a result in most cases there already is configuration for how tests run. I want to avoid adding an extra generic "testing.json" if possible -- or, if we do add it, I would like it to be very well-defined to editor-specific features and functionality. That said, if a language lacks (sufficient) existing testing configuration, there's no reason why an extension could not introduce something like a `.vscode/java-testing.json`.

Another motivation behind avoiding that is the fact that the launch.json has been a hinderance to discoverability of debugging in VS Code. A JSON file and configuration options is intimidating.

> what's the view ID of the test view if I want to contribute a welcome view there?

It's a contribution like this, `contents` is markdown:

```js
"viewsWelcome": [
	{
		"view": "testing",
		"contents": "Hello world!"
	}
]
```

https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome

**Comment by jdneo** [comment]
> Another motivation behind avoiding that is the fact that the launch.json has been a hinderance to discoverability of debugging in VS Code.

😲A little surprised about this, is that because users are not willing to configure the launch configuration in a file (prefer IDE wizard)?

> "view": "testing"

Thank you, it works!

**Comment by connor4312** [comment]
> 😲A little surprised about this, is that because users are not willing to configure the launch configuration in a file (prefer IDE wizard)?

It's an extra step in the funnel. Users need to:

1. Discover the file exists, and why they want to use it
2. Figure out the format of the file and what they need to configure
3. Finally run their program

You might have noticed the JavaScript Debug Terminal and `Debug: Open Link` command in  recent version of VS Code; those are our attempts to make that one step instead of three

**Comment by jdneo** [comment]
We decide to go through the settings to persist these configurations. though there may have some duplicated schemas compared with the Java Debugger's launch configuration, but that's not a blocking issue.

**Comment by connor4312** [comment]
There will also be a new configureHandler on the test run configuration objects: https://github.com/microsoft/vscode/issues/127096#issuecomment-868839093
