### ISSUE TITLE
php 8 anon class methods with nullable returns messing up syntax highlighting

### ISSUE THREAD

**Issue by bobmagicii** [microsoft/vscode#124381]
Does this issue occur when all extensions are disabled?: yes

- VS Code Version: 1.57.0-insider and some version prior that i was using for months.
- OS Version: w10

methods with nullable returns in php 8 anonymous classes mess up the syntax highlighting for everything that happens after that. when discussing with others it was suggested this is vscode's problem who in turn should blame atom editor for some reason.

![119047988-3a4eda80-b984-11eb-8ec1-f5832706f84b](https://user-images.githubusercontent.com/881944/119173044-4ee6ad80-ba2c-11eb-9aee-a0e6cfd0365c.png)

![119047997-3cb13480-b984-11eb-8570-45edfca88231](https://user-images.githubusercontent.com/881944/119173055-51490780-ba2c-11eb-88c9-a24e5e3b0f77.png)

**Comment by roblourens** [comment]
Filed upstream https://github.com/atom/language-php/issues/429. Seems that the newline in the function definition is not parsed correctly
