### ISSUE TITLE
Workspace trust - extension enablement improvements

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#124338]
- Extension A does not support untrusted workspaces
- Extension B supports untrusted workspace
- Extension B depends on Extension A

Expected:
Extension B should not be enabled in an untrusted workspace

Actual:
Extension B tries to get activated but it cannot since Extension A is not enabled

**Comment by lszomoru** [comment]
Walking the extension dependencies also needs to be done when installing, and enabling an extension.

**Comment by alefragnani** [comment]
Hi @lszomoru , 

Why not add the `extensionDependencies` entries as another _restriction_, just like `restrictedConfigurations`? 

So, for extensions where some dependency should be disabled, would be fairly easy to manage the restriction.

**Comment by lszomoru** [comment]
I don't think it make sense to add another mechanism to manage extension dependencies since this is already available in the extension manifest file. Since the available is already available, we just need to build the dependency graph of the installed extensions and use that to enable/disable extensions.

**Comment by alefragnani** [comment]
The idea to add another `restricted` like entry, was a way let the extension developer to have control/decide which dependency must be allowed on untrusted workspaces.

But of course, if the dependency graph can be built automatically, it can be used. 

Thank you

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/122448
