### ISSUE TITLE
debug console does not auto-scroll to bottom

### ISSUE THREAD

**Issue by awa5114** [microsoft/vscode#124324]
Issue Type: <b>Bug</b>

 - create test.py:

```
import pandas as pd
import numpy as np

s = pd.Series(np.arange(40))
print('done')
```

 - Place a breakpoint on line 5. 
 - Start a debug session and select the debug console
 - enter the variable `s` in the debug console and press enter
 - enter the variable `s` in the debug console and press enter again

The debug console prints the contents of the variable correctly on the second time, but it fails to auto-scroll down, leaving it up to the user to do this manually. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (16.08GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/awa5114/code/awa5114/data-challenges/05-ML/09-Time-Series/03-SARIMA --remote=wsl+Ubuntu --crash-reporter-id 4f8672e2-c971-41d2-8af4-73166ac60f9c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|24.88GB (19.16GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.2
sublime-keybindings|ms-|4.0.9
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
Thanks for the nice steps, however dup of https://github.com/microsoft/vscode/issues/117674
