### ISSUE TITLE
Support contributing commands onto the new test explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#124329]
_// Maybe it's already supported, but I didn't find any clue in the API document._

Just like the current tree view API, extensions can contribute their commands onto the tree nodes.

**Comment by connor4312** [comment]
Yep, you can contribute them using the `menus` contribution point:

```
"menus": {
	"testing/item/context": [
		{
			"command": "helloWorld",
			"group": "inline"
		}
	]
}
```

Though I did put a fix in dc2b8f543f3

**Comment by jdneo** [comment]
Hi @connor4312 

I'm wondering since now the we are using a single tree to maintain the tests in VS Code, Could we also allow register command into the left side shortcuts? (sorry I don't know the official name for these buttons)

![image](https://user-images.githubusercontent.com/6193897/123724498-4c545080-d841-11eb-91b1-6279b5a47630.png)

**Comment by connor4312** [comment]
Sure, please open a feature request

**Comment by jdneo** [comment]
Thank you, here it is https://github.com/microsoft/vscode/issues/127385
