### ISSUE TITLE
Search doesn't auto-update when selection changes

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#124300]
The Search field doesn't update when "search within Selection" is checked and the selection changes.

So, it's impossible to replace a subsequent number of selections.

- VS Code/OS Version:
   ```
   Version: 1.56.2 (user setup)
   Commit: 054a9295330880ed74ceaedda236253b4f39a335
   Datum: 2021-05-12T17:13:13.157Z
   Electron: 12.0.4
   Chrome: 89.0.4389.114
   Node.js: 14.16.0
   V8: 8.9.255.24-electron.0
   Betriebssystem: Windows_NT x64 10.0.19042
   ```

https://user-images.githubusercontent.com/9283914/119049471-e2829480-b9c0-11eb-9f98-e733d479ad07.mp4

**Comment by rebornix** [comment]
@SetTrend the find in selection range won't update after the "Find in Selection" is toggled.
