### ISSUE TITLE
Toggle Developer tools for VSCode is not opening dev tools when VSCode is opened as Administrator

### ISSUE THREAD

**Issue by giakas** [microsoft/vscode#124383]
Issue Type: <b>Bug</b>

1.Open VSCode as Administrator by right clicking on the VSCode icon
2. Try to open Toggle Developer tools from Help Menu on the top bar.
Observed: no dev tools opened.

Can repro the issue with all extensions disabled.

Also Report Issue windown also opens as blank when VScode is in Admin mode. I am reporting this issue in Non Admin mode, just to use the report Issue popup.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.11GB free)|
|Process Argv|--crash-reporter-id ebebee8a-cbb0-466f-9ee0-63b9143e85f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
turbo-console-log|Cha|2.1.6
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.40.4
vscode-eslint|dba|2.1.20
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.4
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.92
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.7
docs-yaml|doc|0.2.6
xml|Dot|2.5.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
resxformatter|gir|1.0.1
vscode-pull-request-github|Git|0.26.0
todo-tree|Gru|0.0.213
project-tasks|hau|1.0.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
markdown-shortcuts|mdi|0.12.0
import-sorter|mik|3.3.1
azure-video-analyzer|ms-|0.1.0
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.1.0
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.4272
debugger-for-chrome|msj|4.12.12
typescript-hero|rbb|3.0.0
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
node-modules-viewer|see|0.0.5
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.14
azure-iot-edge|vsc|1.24.0
azure-iot-toolkit|vsc|2.16.6
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vscode-icons|vsc|11.4.0
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vspre833cf:30267465
vshan820:30294714
vscorecescf:30290706
vscus158cf:30286554
vscod805:30301674

```

</details>

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/122951 as it shares the same root cause.
