### ISSUE TITLE
Path autocomplete hides extension referencing .js/x and .ts/x files

### ISSUE THREAD

**Issue by silkfire** [microsoft/vscode#124315]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10, 20H2 19042.985

Steps to Reproduce:

1. Have an import path in a JavaScript or a TypeScript file, referring to a module ending in .js/x or .ts/x.
2. Ctrl + Spacebar (IntelliSense) to trigger autocomplete suggestions.

The dropdown shows any JavaScript or TypeScript files without their respective file extensions. Hitting Tab autocompletes their names without the extension, when I actually need the full name of the file.

For some reason, the tooltip in the right margin shows the full name, but this is never resolved when hitting Tab.

![image](https://user-images.githubusercontent.com/1554615/119069446-73b83200-b9e6-11eb-9b4f-84d30af6498d.png)

Expecting `index.js`, not `index`; and `webpack.dev.js`, not `webpack.dev`.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
