### ISSUE TITLE
Renaming files is broken... again

### ISSUE THREAD

**Issue by abr4xas** [microsoft/vscode#124313]
This comment is from @isidorn:

This is my stupid commit which broke it https://github.com/microsoft/vscode/commit/7ab6b3d4817c7ac7319747b6ece1935839bb9363

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/95315#issuecomment-618412364_

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-73-generic snap
```

**Comment by isidorn** [comment]
Thanks for filling this issue, I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

If yes what are your steps

**Comment by abr4xas** [comment]
Hey @isidorn the issue is only with  v1.56.2


with

```
Version: 1.57.0-insider
Commit: 4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
Date: 2021-05-21T05:13:19.775Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-73-generic
```

works good.

**Comment by isidorn** [comment]
Then I suggest that you wait for the stable release. And double check if one of your extensions is maybe breaking the flow here

**Comment by abr4xas** [comment]
@isidorn sure. Thanks for your help!!
