### ISSUE TITLE
Some areas in webview cannot get focus correctly

### ISSUE THREAD

**Issue by zgh0711** [microsoft/vscode#124318]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

I have an extension developed based on webview. It worked normally before vscode version 1.56, but after vscode was upgraded to version 1.56, the extension had some problems.

The extension is actually a custom editor for xml files, and the main body is a web program developed based on vue.js.

## Problem Description
In the main editing area of the editor, due to business needs, I have rewritten a series of events such as `mousedown` of the mouse. In the rewritten event, I used `e.preventDefault();e.stopPropagation()` to prevent the event. Default behavior and bubbling.

When I click a xml file to open the editor, I can’t move the focus away from the xml file by clicking the mouse in the main editing area of the editor. The focus is always on the xml file. There is no such problem in other areas of the editor.

At the same time, I have customized some keyboard shortcuts in the editor, such as `Delete` to delete a widget. The problem now is that when I select a widget in the main editing area and want to delete it with `Delete`, the xml file will be deleted directly. I cannot solve this problem.

![focus](https://user-images.githubusercontent.com/15401997/118974177-1c45a200-b9a5-11eb-910c-71bd067d1102.png)

## Extension and sample project
The problems mentioned above only appeared under the vscode 1.56 version, and there were no such problems before. I can't solve these problems now, and hope to tell me how to solve them.

My extension and an example project are attached below:
[NewProject.zip](https://github.com/microsoft/vscode/files/6515659/NewProject.zip)

**Comment by mjbvz** [comment]
Again, please share a minimal example extension that clearly demonstrates the issue

/needsMoreInfo

**Comment by zgh0711** [comment]
I have attached my extension and a sample project at the end of the issue, please check if they exist

**Comment by zgh0711** [comment]
@mjbvz
Please take a look at this latest zip file, this is a minimal runnable source code, please install extensions and dependencies under the web-designer folder before running.


[MiniExtension.zip](https://github.com/microsoft/vscode/files/6520389/MiniExtension.zip)

**Comment by mjbvz** [comment]
Closing as we need more information to investigate
