### ISSUE TITLE
Extensions search results not initially sorted

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#12431]
- VSCode Version: Code - Insiders 1.6.0-insider (25b370a3ebe800ac1fedc551a47b7689aa2a5c5b, 2016-09-22T06:10:29.536Z)
- OS Version: Windows_NT ia32 10.0.14926

Steps to Reproduce:

1. Open extensions panel
2. Type something to search

The results don't seem to be sorted in any way: not by name, not by rating, not by downloads.

Example:

![vscodesort](https://cloud.githubusercontent.com/assets/199648/18741887/c957c5a4-80b1-11e6-87bc-e860b00dac08.png)

**Comment by joaomoreno** [comment]
They are sorted by *relevance*, which is [the default in the Marketplace website](https://marketplace.visualstudio.com/search?term=theme&target=VSCode&sortBy=Relevance).

**Comment by joaomoreno** [comment]
That's not to say that you should definitely let us know if something obvious fails. Like searching for `python` and not seeing that extension first. But searching for `theme` is kind of generic.

Also, note that you can control the sorting.

![image](https://cloud.githubusercontent.com/assets/22350/18764811/5ac769b6-8113-11e6-851c-1ddc9c5f9237.png)
