### ISSUE TITLE
CSS overflow-x in all divs of notebookOutputRenderer

### ISSUE THREAD

**Issue by AnWeber** [microsoft/vscode#124360]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insider
- OS Version: Win10

Since commit 45aafeb, an overflow-x is automatically inserted in all div of a NotebookOutputRenderer. Was this intended?

The CSS style is very unspecific and selects all div in the NotebookOutputRenderer. This must actually be overwritten in all other NotebookOutputRender so that the display works again.
![image](https://user-images.githubusercontent.com/13434739/119136068-801ca900-ba3f-11eb-8014-9242e7064469.png)

**Comment by rebornix** [comment]
@AnWeber thanks for the report, I reverted the change.
