### ISSUE TITLE
Getting started: layout a bit broken on the iPad

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#124345]
Here's how the getting started looks like on the iPad. I see the following issues:

1. When in vertical mode the image is above the buttons. I think that is wrong, the image should be at the bottom
2. The `More` button is way too small and not vertically aligned with the `<`

![A07474D0-A97F-433D-B1DB-11583DC81BC2](https://user-images.githubusercontent.com/1926584/119115658-b4846b00-ba27-11eb-9a5c-32c7236a44f1.png)

**Comment by JacksonKearl** [comment]
Image is now at bottom. cc @misolori for ideas on why the more would be rendered differently on iOS.

**Comment by isidorn** [comment]
I think it is because of the css layouting rules you are using.
This looks like a visual bug and is maybe the first thing a user sees on the iPad, so it is very visible. Is it possible to fix this? Or at least can we put a help-wanted so maybe someone from the community has ideas on how to fix.

**Comment by JacksonKearl** [comment]
Safari overrides all buttons to `font-size: 11px;`. Added a more specific re-override.

**Comment by isidorn** [comment]
Great, thanks for fixing this 👏 
Let's add a bug label and I can verify this later
