### ISSUE TITLE
Can`t make my window title bar custom

### ISSUE THREAD

**Issue by fedorinoGore** [microsoft/vscode#124344]
Issue Type: <b>Bug</b>

1. Im choosing Title Bar Style - custom by adding 
"window.titleBarStyle": "custom" to User level settings.json
2. My title bar is still native to OS X Big Sur
What am I doing wrong?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|8, 4, 3|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|. --crash-reporter-id d664e39e-8a39-4120-a722-5d6732b125e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
icons-carbon|ant|0.2.3
vscode-tailwindcss|bra|0.6.6
vscode-toggle-quotes|Bri|0.3.4
export-index|Bru|0.0.3
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.4.0
flow-for-vscode|flo|1.5.0
workspace|Foo|1.1.1
monkey-patch|ioc|0.1.13
svg|joc|1.4.6
regexp-preview|Lou|0.1.5
ReactFlowSnippets|lsa|0.2.17
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.9
vscode-language-pack-ru|MS-|1.56.2
vscode-pylance|ms-|2021.5.3
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vscode-jest|Ort|4.0.1
vscode-versionlens|pfl|1.0.9
vscode-thunder-client|ran|1.3.0
vscode-sort-json|ric|1.20.0
json-organizer|rin|0.0.4
preview-vscode|sea|2.2.5
addDocComments|ste|0.0.8
tabnine-vscode|Tab|3.4.4
errorlens|use|3.2.6
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by sbatten** [comment]
@fedorinoGore `custom` is the default on mac os unless you have `window.nativeTabs` enabled. Do you have this conflict? Can you share a gif or screen shot?

**Comment by fedorinoGore** [comment]
@sbatten I checked in settings. And it seems that `window.nativeTabs` turned off.
Here is my VS Code screenshot:

<img width="1612" alt="VS Code no custom Title Bar" src="https://user-images.githubusercontent.com/12615892/119315377-f7e90e80-bc9f-11eb-88a9-ce9f0326c0e5.png">

**Comment by sbatten** [comment]
@fedorinoGore thanks for the added info. Can you try loading vs code with a fresh user directory and no extensions installed. You can do this without modifying your existing settings by specifying empty directories to the CLI like so:

`code --user-data-dir ~/Desktop/emptyuserdatadir --extensions-dir ~/Desktop/emptyextdir`

**Comment by fedorinoGore** [comment]
@sbatten Thanks! That worked out. The VS Code has started and now it has custom titlebar.
Please advice - how to track the setting or extension that causes the problem?
Or I need to reset VS Code and customise it from scratch?
