### ISSUE TITLE
Feature request: ability (for extensions) to perform a diff outside of source control

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#124302]
I'm aware VS Code can diff any two files you give it if you launch it from the command line, but I don't see a way to do that programmatically.

In my case, I making an extension that essentially performs an advanced find and replace algorithm for pre-determined patterns. I would like to generate a virtual document from the original document and diff it against the original so the user to can decide to accept or reject the changes instead of having to inspect the document themselves after the operation and look for changes by hand. Sort of like a dry-run.

**Comment by joaomoreno** [comment]
We have a `vscode.diff` command for this. More info in https://code.visualstudio.com/api/references/commands

**Comment by NSExceptional** [comment]
Thank you 😄 I missed this page in my searching!

**Comment by NSExceptional** [comment]
@joaomoreno Semi-related, but is there a way for me to a) check if a given resource is under source control, and b) display the source control diff?

I want to provide a setting for the behavior of my extension:
- Don't diff, apply changes right away
- Preview changes with diff (diffing a virtual document)
- Diff with source control if it is available

**Comment by joaomoreno** [comment]
> check if a given resource is under source control

You can try using the [Git extension API](https://github.com/microsoft/vscode/blob/main/extensions/git/src/api/git.d.ts). [Example](https://github.com/microsoft/vscode/blob/9cba86888c953fe4f665290462b2bd701f3cb971/extensions/github/src/extension.ts#L42).
