### ISSUE TITLE
Vs code:when setting some rare keyboard shortcut('ctrl' alone), error occurrs

### ISSUE THREAD

**Issue by zoo-k** [microsoft/vscode#124370]
Issue Type: <b>Bug</b>
<b>Problem:</b>

- Open (with command pallet) "Preferences: Open Keyboard Shortcut"
    -  1: set or add any of the shortcut as 'ctrl' or 'x+ctrl' (x can be alphabet or perhaps number key), the row of the shortcut you set will show twice. 
        - 1: In case of 'ctrl', pressing the key will have no result.
        - 2: In case of 'x+ctrl' pressing the *only* x key will activate the command!
        note: 'ctrl' can be changed to 'alt' or 'shift'. don't know if any other keys do so .
    - 2: set or add key to 'a+b'(a,b may be any alphanumeric key), this time the shortcut row doesn't repeat, pressing 'a+b' will work           fine, but pressing the key 'a' alone will have no response.
![Screenshot from 2021-05-21 22-59-24](https://user-images.githubusercontent.com/83531237/119158137-7c614480-ba88-11eb-835c-5809525660fd.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (2 x 1795)|

|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|2.94GB (0.13GB free)|
|Process Argv|--extensions-dir=/home/zook/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --no-sandbox --crash-reporter-id 8b486bdf-a571-4796-8722-65bfdc01a693|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by sandy081** [comment]
I could reproduce that entry is getting duplicated with the reported input.

Regarding following:

> In case of 'ctrl', pressing the key will have no result. | but pressing the key 'a' alone will have no response.

Are you saying that after assigning the keybinding to `ctrl` or `a` key and pressing the corresponding key is not triggering the command?
