### ISSUE TITLE
[codespaces] icons of terminals are not preserved on reload

### ISSUE THREAD

**Issue by JanKoehnlein** [microsoft/vscode#124359]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: MacOSX, Chrome

Steps to Reproduce:

1. In Codespaces, open a new terminal and switch on _Show tabs_
2. Change icon / title of the terminal
3. Reload the browser tab
-> the tabs show as empty tree items, without icon and title

My suspicion: The `IShellLaunchConfigDto` lacks the `icon` property from `IShellLaunchConfig`, such that the remote backend cannot remember it. In addition, terminals with a config that has an undefined icon are shown as completely blank.

**Comment by Tyriar** [comment]
This works in main
