### ISSUE TITLE
Tailwind @apply notation with multiple classes inline gives semi-colon-expected  scss(css-semicolonexpected) error

### ISSUE THREAD

**Issue by pranav-js** [microsoft/vscode#124331]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 (Universal)
- OS Version: macOS 11.2

Steps to Reproduce:

1. Open any tailwind integrated with the SCSS project
2. use @apply annotation and use multiple tailwind classes in one-row space-separated.

What is happening:
Vscode shows SCSS formatted error though it's correct and works fine, it irritates to see red lines across SCSS file

<img width="266" alt="Screenshot 2021-05-21 at 12 16 27 PM" src="https://user-images.githubusercontent.com/79982692/119094909-3deb6b80-ba2f-11eb-9216-2a643b910c9e.png">

every class has to be on a new line, then the error (semi-colon-expected  scss(css-semicolonexpected)) goes away

Expected Behaviour:
Should not show error for @apply notations or provide a setting to ignore custom ones

**Comment by pranav-js** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [[scss] provide hover for scss functions (#86765)](https://www.github.com/microsoft/vscode/issues/86765)

no it is not relevant

**Comment by DeekshithRajBasa** [comment]
even I'm also issue facing the same issue, thanks for reporting this @pranav-js, when is the fix @aeschli ? thanks in advance.
<img width="521" alt="Screenshot 2021-05-21 at 4 19 12 PM" src="https://user-images.githubusercontent.com/37568816/119126148-4acc8700-ba50-11eb-88b3-99bc233a2670.png">

**Comment by aeschli** [comment]
`@apply` is a css at rule that has been deprecated since.: https://tabatkins.github.io/specs/css-apply-rule/

You are coming from Tailwind which uses `@apply` with a multiple arguments.  

Unfortunately we need to focus on standardized css/scss, so I can't help you here.

**Comment by pranav-js** [comment]
@aeschli  this is not the @apply you have pointed to, it's a postcss annotation. please correct me if I'm wrong https://github.com/tailwindlabs/tailwindcss/issues/381#issuecomment-364787287

**Comment by pranav-js** [comment]
> The point is that we don't have support for `postcss` syntax, only for standard css.

alright gotcha!

**Comment by aeschli** [comment]
Fixed for May.
`@apply` is now an unknown at rule, which is ignored (unless you set the linter setting)

**Comment by pranav-js** [comment]
@aeschli  that's great.. but do you mean we still need to have custom linter for this? can you link PR please :)

**Comment by aeschli** [comment]
The linking would have to come from an extension that knows `postcss`.
The built-in css extension is only about css, and will ignore all unknown at-rules unless you configure the setting `css.lint.unknownAtRules`.

**Comment by pranav-js** [comment]
for scss folks

use 

`"scss.lint.unknownAtRules": "ignore",`
