### ISSUE TITLE
Support "short title" for commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#124355]
A command (internally `ICommandAction`) describes all UI properties of a command. Menus select some or all of those properties when rendering a command, e.g the command palette uses the `category` and `label` properties, the editor toolbar uses the `icon` property only etc.

This design sometimes makes it hard to come up with good values for these various and not yet known menus. Esp titles need to work for the "global" command palette as well as for context menus. Therefore we should make the title representation more powerful, like global and local title etc. 

A first version and an API proposal for this has been implemented with https://github.com/microsoft/vscode/commit/494e827e35134c3eb2a287f49009ddeab77c8dac

**Comment by gjsjohnmurray** [comment]
> A first version and an API proposal for this has been implemented with [494e827](https://github.com/microsoft/vscode/commit/494e827e35134c3eb2a287f49009ddeab77c8dac)

This seems to be pointing to an unrelated commit.
