### ISSUE TITLE
Reopen file in custom/notebook editor after installing a compatible custom* editor extension

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124303]
Today when a user has a fresh install of VS Code and attempts to open an existing notebook or create a new one, they are recommended to install Jupyter. After they do so, nothing happens to the JSON file they see on their screen. Closing and opening the file is the only way to get the notebook to render, reloading window does not render notebook.

**Comment by tanhakabir** [comment]
I think reloading the file to be the notebook editor ourselves is important since I'd assume most Notebook users don't know that a Notebook behind the scenes is a JSON object and they might think that we're broken.

**Comment by claudiaregio** [comment]
@tanhakabir just to double check, this would also reload for the create new file scenario when a user creates on in the file explorer tab right? 

Ex. They go to file explorer -> hit new file icon -> create file with .ipynb extension. 
That today also leads to blank script (not a notebook view user is expecting)

![image](https://user-images.githubusercontent.com/19276747/119178962-34f49d00-ba23-11eb-8a74-913a7a9256d8.png)

Thoughts around the File -> New File -> Save as -> "x".ipynb flow as well?

**Comment by rebornix** [comment]
Assigning to @lramos15 as it applies to all editors. Question is what should happen to existing text editors after users install a custom/notebook which support such file extension.

**Comment by tanhakabir** [comment]
> Question is what should happen to existing text editors after users install a custom/notebook which support such file extension.

Do you mean if a user has several .ipynb files opened and then installed the Jupyter extension?
