### ISSUE TITLE
Support "cmd+`" as a valid keyboard shortcut

### ISSUE THREAD

**Issue by bmitc** [microsoft/vscode#124379]
On both Windows and Mac OS X, "ctrl+\`" will switch to the terminal. I setup keybindings to use the same keybinding to toggle back and forth, like this:
```
    // Toggle between terminal and editor focus
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.focus"
    },
    { 
        "key": "ctrl+`",
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "terminalFocus"
    },
```

On Mac OS X, I would like to do the same thing but use "cmd+\`" since the ctrl button is not located on a convenient part of the keyboard. So in the above, I would like to add new keybindings but replacing "ctrl+\`" with "cmd+\`" to make this more convenient in Mac OS X, in particular Mac-oriented keyboards. However, "cmd+\`" is not supported as a valid keyboard shortcut. This can also be verified by the Define Keybinding tool not recognizing it. Although, something like "cmd+1" works. It's possible there's a reason why, but I couldn't find why.

**Comment by roblourens** [comment]
By default, this is the OS level keybinding for switching windows of the same application. If you unbind it at the OS level, you might be able to use it in VS Code.

**Comment by bmitc** [comment]
That was indeed it! Thank you!

For reference, I went into System Preferences -> Keyboard -> Shortcuts -> Keyboard and unchecked `Move focus to next window`. Also, I needed to restart Visual Studio Code for the "cmd+`" keyboard shortcut to be recognized after this change.
