### ISSUE TITLE
UriError while searching in open editors

### ISSUE THREAD

**Issue by mmscalemp** [microsoft/vscode#124374]
Issue Type: <b>Bug</b>

1. Open several files from workspace.
2. Open a file out of workspace, for example /home/.bash_profile
3. Click Ctrl+Shit+F to search a word in files. 
4. In the Search dialog click on "book" icon in field "files to include". 
The search field become with red frame, no search results displayed. 
When you click on search field you will see:
"[UriError]: If a URI contains an authority component, then the path component must either be empty or begin with slash ("/") character."

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.98-1.el7.elrepo.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.80GB free)|
|Process Argv|--crash-reporter-id c5aeedac-1e27-4274-9188-8d0eef997293|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: ec2-35-158-120-72.eu-central-1.compute.amazonaws.com|
|OS|Linux x64 5.4.98-1.el7.elrepo.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz (16 x 3427)|
|Memory (System)|30.36GB (6.30GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
reloaded-cpp|rel|0.1.9
material-theme|zhu|3.10.14
meld-diff|dan|1.1.0
compareit|in4|0.0.2
vscode-setting-export|jef|0.0.6
bash-ide-vscode|mad|1.11.0
vscode-cvs|mma|0.1.2
cpptools|ms-|1.3.1
ctree|Ori|0.0.1

(1 theme extensions excluded)

</details>

**Comment by Reid00** [comment]
the same error while with ssh remote. 
```sh
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by roblourens** [comment]
Sorry for the late response, missed this.

Exact same steps for you @Reid00? Including this?

> If I use Ctrl+T to open definition of some macro or variable, the file opened with real path /some-users/u/myusername
and this cause the search to fail.

I can't reproduce

Can you share a screenshot @Reid00 with the exact steps you use?

**Comment by Reid00** [comment]
sorry, I tried again, failed to reproduce, I am not sure how to reproduce it stably.
In fact, this is second time I encounter this issue when I log it here.
what is my steps:
1. ssh a server
2. open hue project git clone from https://github.com/cloudera/hue
3. ctrl + shift + F to search keyword, hue_4_4.create_role     this error shows up

**Comment by roblourens** [comment]
Please let me know if you see this coming up again
