### ISSUE TITLE
"Reopen editor with..." on untitled custom editor does not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124356]
**Steps:**
* start with an untitled custom editor (or notebook)
* select "Reopen editor with..." and pick text editor (or any other custom editor)

=> 🐛 an untitled text editor opens but empty

I think this needs a more general solution for how to transport untitled data across editors. I see the following one-off solutions for notebooks and custom editors:

https://github.com/microsoft/vscode/blob/703ca68ea6bee996ffc3d646da843bcb085cce3c/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L216-L221

https://github.com/microsoft/vscode/blob/721cdd6472b25ae5fd70a36f485bcb26beb0c96e/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L42-L42

But I do not think this solution scales because it only considers the contents of an untitled text editor for the new editor, not if you start from a custom editor.

**Comment by bpasero** [comment]
Even worse, when this happens I cannot quit anymore:

![recording (2)](https://user-images.githubusercontent.com/900690/119129000-a853da00-ba36-11eb-934d-13fa047ffd1b.gif)

**Comment by bpasero** [comment]
Related (in notebooks): https://github.com/microsoft/vscode/issues/101360

**Comment by lramos15** [comment]
I wonder if we could use backups to transfer the contents around

**Comment by bpasero** [comment]
Yes, I would think that working copy backups are the lowest common layer for transferring data around 👍

**Comment by lramos15** [comment]
I think this is too difficult to tackle to be worth the effort. I've went with a simpler solution to just disable `Reopen Editor With..` and `Toggle Editor Type` when you're in a custom untitled file.

Verifiers:
0. Have the hex editor extension installed
1. Open an untitled file
2. Reopen with Text -> Hex Editor
3.  Ensure you cannot reopen with again from untitled Hex to anything else
