### ISSUE TITLE
after each update, my python version is reset

### ISSUE THREAD

**Issue by fEyebrow** [microsoft/vscode#124330]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.1
- OS Version:  macOS Big Sur 11.2.3

Because  my laptop is m1 macbook pro. when I try to open vscode from the command line with code. I get the error ./MacOS/Electron: No such file or directory. so I change the python to python3:
![image](https://user-images.githubusercontent.com/18180417/119093970-f7077100-ba42-11eb-853f-faeeed7c44c6.png)

everything is working fine.

but when I update vscode, the file located at /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code will be reset. python3 turns back to python.
![image](https://user-images.githubusercontent.com/18180417/119094269-667d6080-ba43-11eb-8897-ab57e74ecb89.png)

how to avoid this？

**Comment by joaomoreno** [comment]
Is `python` not available in your machine? If not, you can always create a symlink pointing to `python3`:

```
ln -s $(which python3) /usr/local/bin/python
```

**Comment by fEyebrow** [comment]
I've tried sudo ln -s $(which python3) /usr/local/bin/python, and that gives me ln: /usr/local/bin/python: File exists. 

I learned that I need to turn off sip in order to delete /usr/local/bin/python.

Is there any other way to make vscode point to python3 @joaomoreno

**Comment by fEyebrow** [comment]
I have closed SIP：
![image](https://user-images.githubusercontent.com/18180417/119112861-1e683900-ba57-11eb-8dc2-f904a777cf04.png)

But when I tried ‘sudo mount -uw /’ and gain write access， that gives me this：
![image](https://user-images.githubusercontent.com/18180417/119113273-84ed5700-ba57-11eb-9a0d-234aee487b25.png)
I learned that I need to change the partition name of my hard drive to fix the problem, but this one affects future OS updates

Do you have a better idea？

**Comment by joaomoreno** [comment]
Maybe @deepak1556 can help out here?
