### ISSUE TITLE
Test: terminal icon extension API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#124398]
Refs #120538

- [x] macOS @lramos15 
- [x] linux @alexdima 
- [x] windows @bamurtaugh 

Complexity: 3

Authors: @meganrogge, @tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124398%0A%0A)

---
With proposed API [enabled](https://code.visualstudio.com/api/advanced-topics/using-proposed-api), use the extension-terminal-sample to test that you can:
- set terminal icons using all of the argument types, with and without providing a `pty` to `createTerminal`: 
`ThemeIcon | URI | { light: URI; dark: URI };`
- view the icons in the TerminalQuickPick with `Switch Active Terminal`
- view the icons in the terminal tabs list
- view the icon update as you switch active terminals in the single tab terminal view action item
- anything else you can think of

**Comment by lramos15** [comment]
I wonder if there should be a third icon option for high contrast themes, but other than that everything seemed to work well :)

**Comment by Tyriar** [comment]
@lramos15 you could follow that up as a general ext API discussion since this just copies the current recommended form for icons.
