### ISSUE TITLE
Workspace terminal sets

### ISSUE THREAD

**Issue by tohagan** [microsoft/vscode#124309]
I manually setup multiple split terminals running the same commands each time I start up development for specific workspaces.  So I think a natural extension of the new terminal profile feature would be to support named "terminal sets" that defines a list of terminals that can be started with a single command and shared with a development term via workspace version control.

Each "terminal" in a "terminalset" could define ...
- terminal profile name
- environment variables
  -  Can set a variable OR Check that it's already set (e.g. secrets)
- current working directory
- command(s) to run 

There is an [existing extension](https://github.com/ariassd/vscode-load-terminals) that implements aspects of this feature but I'm wondering if it belongs as part of VSCode?

**Comment by Tyriar** [comment]
This is the sort of thing that is perfect for extension imo in order to keep the core slim. Time would be better spent improving the API to let extensions do more.
