### ISSUE TITLE
Different kind token should has different color

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#12437]
- VSCode Version: Code - Insiders 1.6.0-insider (90dda7af651fc557d40b166f322db3f014e8f33b, 2016-09-21T06:30:11.587Z)
- OS Version: Darwin x64 16.0.0

Different kind token should has different color. Variables, function, method, property should have it's own color to easy recognize .
go
![go](http://o8z0dg641.bkt.clouddn.com/QQ20160922-3@2x.png)
nodejs
![](http://o8z0dg641.bkt.clouddn.com/QQ20160922-2@2x.png)
python
![](http://o8z0dg641.bkt.clouddn.com/QQ20160922-4@2x.png)

**Comment by alexandrudima** [comment]
@leaxoy These images do not load correctly for me, I see only the top 10-20% of them.

**Comment by joaomoreno** [comment]
I'm not sure what you mean by this. Do you mind hosting the images in GitHub? They appear broken.

**Comment by leaxoy** [comment]
My mistake.
[python](http://o8z0dg641.bkt.clouddn.com/QQ20160922-4@2x.png)
[nodejs](http://o8z0dg641.bkt.clouddn.com/QQ20160922-2@2x.png)
[go](http://o8z0dg641.bkt.clouddn.com/QQ20160922-3@2x.png)

please use those external link.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18750102/0ab2d55c-80da-11e6-9758-54eab68ee12e.png)

![image](https://cloud.githubusercontent.com/assets/22350/18750105/0de62828-80da-11e6-80a5-b179ea178ce1.png)

![image](https://cloud.githubusercontent.com/assets/22350/18750109/121c00fc-80da-11e6-9a8d-f80fb77a151d.png)

**Comment by joaomoreno** [comment]
You need to file these issues to each of the languages' extensions.

https://github.com/Microsoft/vscode-go
https://github.com/DonJayamanne/pythonVSCode

cc @waderyan @aeschli for JavaScript.

**Comment by leaxoy** [comment]
yeah. Thanks. 
Can I patch `extensions/theme-defaults/themes/*.json` files achieve this? Or other settings!

**Comment by joaomoreno** [comment]
You need to figure out whether it's a theme problem or a syntax problem. If you switch themes, does it work as you expect it to?

**Comment by alexandrudima** [comment]
@leaxoy You can affect the colors of languages with two knobs at your disposal:

First Option: install an extension that changes the grammar for a language. e.g. there is one called "JavaScript Atom Grammar" -- perhaps there are other extensions for the other languages that provide a better grammar that you like more.

Second Option: The tokens produced by the grammars then get styled by themes: there are hundreds of extensions that provide themes, perhaps you find one that you like more.

**Comment by leaxoy** [comment]
@joaomoreno @alexandrudima 
Thanks for your patient replies. I find a more fittable theme named `monokai-best` through marketplaces. 👍
