### ISSUE TITLE
vscode 'code <filename>' command now opening files in new window instead of tab within same window above terminal.

### ISSUE THREAD

**Issue by cmbrodie** [microsoft/vscode#124311]
Issue Type: <b>Bug</b>

It used to be that when i'd enter "code filename.py" in bash terminal it'd open the file in a new tab above my terminal.. Now it opens in a new window/instance of vscode. If in this new window/instance of vscode I go to the terminal and enter 'code' command followed by a filename it opens in a new tab in the same window. But when I close out and again open vscode through ubuntu, any files opened via the embedded bash terminal open in a new window still.  

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz (6 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (3.75GB free)|
|Process Argv|--remote=wsl+Ubuntu --crash-reporter-id 49ebd149-c215-4d44-b3dc-a3a8f5da1f10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz (6 x 1800)|
|Memory (System)|9.25GB (7.81GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz (6 x 1800)|
|Memory (System)|9.25GB (7.81GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.2
code-runner|for|0.11.4
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Do you have `window.openFilesInNewWindow` set?

**Comment by cmbrodie** [comment]
> Do you have `window.openFilesInNewWindow` set?

I tried setting that to off, and restarted, it didn't change anything, i tried setting it to on as well and no change either....

**Comment by cmbrodie** [comment]
SOLVED by adding `"workbench.editor.enablePreview": false` to settings.json

**Comment by RA80533** [comment]
Should the enablement of the file preview functionality cause such an issue?
