### ISSUE TITLE
Expand template variables in Run & Debug dropdown

### ISSUE THREAD

**Issue by harrismirza** [microsoft/vscode#124364]
When using the run and debug dropdown, any templates used in the name field are not expanded.

As an example, I have a launch config to run the tests for the current file and the name for this in the JSON is: 'Test current file - ${fileBasename}', I would expect this to appear with the filename in the dropdown, e.g. 'Test current file - xyz.ts', but instead it shows 'Test current file - ${fileBasename}'.

This screenshot also illustrates the difference, at the top, we see ${fileBasename} and underneath is the actual filename:
![image](https://user-images.githubusercontent.com/6362456/119147295-5a919e80-ba43-11eb-8416-e2dfad5bbe7a.png)

Once the test is run it appears with the fully expanded name in the Call Stack menu. 

I'm not familiar with the codebase but will take a look and see if I can work out how to achieve this myself but if there is any reason this might not be feasible please let me know.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
