### ISSUE TITLE
Localizations for Getting Started are not updated to the latest format and don't have buttons

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#124396]
Using any other language than `en` causes _Getting Started_ walkthroughs (setup and fundamentals) to have **no buttons**, rendering it useless:

![image](https://user-images.githubusercontent.com/8599/119195085-e651fd80-ba38-11eb-963e-fa9fd12fc5fe.png)

The advanced walkthrough is not affected, as it didn't get translated.

Maybe the localization does not pick up the string changes that applied a new format, or they didn't want to translate the markdown formatted.

cc @JacksonKearl

**Comment by JacksonKearl** [comment]
cc @dbaeumer The translated strings seem to be derived from a prior version of the original english that didn't have the buttons. Is is sufficient to simply change the english to trigger new translations or should I change the keys as well?

**Comment by dbaeumer** [comment]
@JacksonKearl the English strings are always taken from the data extracted during build time. They don't come from a language pack. So there is no need to change a key to get a value re-translated.

**Comment by digitarald** [comment]
@dbaeumer given that Getting Started is broken in release for all non-en users, are there any next steps we should take or is it just a matter of waiting?

**Comment by dbaeumer** [comment]
I don't know how the getting started experience is implemented but non localized strings using nls.localize can't break a UI. The core loader infrastructure will use an English version of the string when it can't find a key in a language bundle. So it is not a matter of waiting. You should check if your English strings makes it into the `nls.metadata.json` which is produced during a build. You can find that file in the installation directory (e.g. `Microsoft VS Code Insiders\resources\app\out`)

**Comment by JacksonKearl** [comment]
I do see the correct content in nls.metadata.json... I think the problem could be with the markdown formatting. 
![image](https://user-images.githubusercontent.com/8586769/119559685-dba8a880-bd57-11eb-95e4-1abe4ccad760.png)

Do you have suggestions for how we might format this better for the localization team? Either a comment or splitting out the button titles and description then combining them in code

**Comment by dbaeumer** [comment]
The nls.localize function allows to provide comments to the translation team to give them hints on how to localize the string. See https://github.com/microsoft/vscode/blob/main/src/vs/base/common/keybindingLabels.ts#L104 as an example.

**Comment by JacksonKearl** [comment]
\closedWith 6075e48f3cb8d8a054f5c9d562b671b8b27cf276
