### ISSUE TITLE
Renaming WSL profiles in new terminal dropdown

### ISSUE THREAD

**Issue by jerrylususu** [microsoft/vscode#124397]
Hi! I am using a laptop with 2 WSL distros (one in WSL1 and one in WSL2). Normally I would prefer to use the WSL1 one as it don't need a VM thus better for my battery life, and I will only use the WSL2 one if there is something that requires a full fat Linux environment. However, currently there is no indication of WSL versions in the new terminal dropdown of the integrated terminal, thus it's not easy to differentiate which one is the WSL1 one when I am using VSCode. As a workaround, I would like to rename their profiles, and add the version information manually, as what I have done in Windows Terminal. Changing the `terminal.integrated.profiles.linux` doesn't seems to work, and change the `terminal.integrated.profiles.windows` doesn't feels right to me, as there is no WSL distros shown when I try to edit it. It would be great if I can rename WSL profiles.

Screenshot from Windows Terminal
![image](https://user-images.githubusercontent.com/17522475/119195282-12976980-ba8d-11eb-9f60-95d095c10327.png)

Screenshot from VSCode
![image](https://user-images.githubusercontent.com/17522475/119195356-322e9200-ba8d-11eb-92c4-7cc4857d7c6c.png)

**Comment by Tyriar** [comment]
The intent here is that you're meant to be able to set a profile to null and redefine it like this:

```
"terminal.integrated.profiles.windows": {
  "Debian (WSL)": null,
  "Debian (WSL2)": {
    "path": "C:\\WINDOWS\\System32\\wsl.exe",
    "args": [
      "-d",
      "Debian"
    ]
  }
},
```

You can get that scaffolded out for you by configuring the terminal profile:

![image](https://user-images.githubusercontent.com/2193314/119343522-6bacfc00-bc4b-11eb-9c8a-cf209e4eeead.png)

I notice that something has gone wrong though in insiders which we'll fix up in https://github.com/microsoft/vscode/issues/124504
