### ISSUE TITLE
Search: has a tooltp with a keybinding

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124335]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=119617&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           has a tooltp with a keybinding:
     Error: Expected search tooltip to contain keybinding but got undefined
      at Context.<anonymous> (out/areas/search/search.test.js:21:23)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by meganrogge** [comment]
@JacksonKearl have you gotten a chance to look into this?

**Comment by JacksonKearl** [comment]
Yes, the test is now disabled.

**Comment by bpasero** [comment]
I do not understand the course of action here? The issue is closed, yet the test is still there but disabled. Then remove it?
