### ISSUE TITLE
Log Level not preserved across reloads

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#124347]
Noticed in 1.57-insiders and 1.56.

**Comment by bpasero** [comment]
Works for me.

**Comment by chrmarti** [comment]
Version: 1.57.0-insider
Commit: 4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
Date: 2021-05-21T05:12:10.032Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0

🤷‍♂️
