### ISSUE TITLE
Can't copy/paste version from VS Code about window

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#12430]
- VSCode Version: See below
- OS Version: Windows 10 x64 with Anniversary Update

See screenshot:
![image](https://cloud.githubusercontent.com/assets/3898363/18741167/8adc9ed2-80a5-11e6-9fc0-d73d3b615b6f.png)

I can't copy paste my version from there to enter it into the VSCode Version above when creating GitHub issues.

It would be better if it displayed my OS version too so I could copy paste that too.

And what would be super duper awesome is if when I clicked the smiley face in the bottom right corner of the editor and clicked "Submit a bug" it would automatically populate these things inside the issue for me. Something like this:
http://stackoverflow.com/questions/34146618/pre-populate-the-github-new-issue-form-using-the-querystring

That would be super slick! Go VSCode team!

**Comment by Bill-Stewart** [comment]
Have you tried pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> in the "About" dialog, then paste? (Works for me)

**Comment by massimocode** [comment]
Ctrl+C works fine for me too. I had no idea!

**Comment by chrmarti** [comment]
You can also use Help > Report Issues to get an issue with version and OS pre-filled.
