### ISSUE TITLE
Explore extension contributions to the "New..." item

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#124304]
## Overview
We've seen feedback from users that creating custom files, i.e. non text files like Notebooks, is difficult to find. Right now the only way to create a new custom file is through the command palette but users are not aware of this. They often looked in the menus and on the welcome page. This issue aims to address this issue.

### Option 1
This proposal simply appends the item under the "New File" item, because new file is for text files, and this item would be for a custom file.

![image](https://user-images.githubusercontent.com/35271042/119055868-9878bf00-b97e-11eb-9f3d-e35c134ff87f.png)

### Option 2
We could alternatively combine the items into single row if there are too many and use the split button:

![image](https://user-images.githubusercontent.com/35271042/119055947-b6462400-b97e-11eb-9f77-a27a5f15311d.png)

### Option 3
This would make clicking on "New File" open a quick pick with the list of options:

![image](https://user-images.githubusercontent.com/35271042/119173820-9c5b1e80-ba1c-11eb-887e-b2b8eb0d3dd9.png)

**Comment by misolori** [comment]
Based on discussions with the team, we'll go with the `New File...` pattern and introduce a new command that replaces the new file item in the getting started page and also adds it to the global `File` menu. 

@JacksonKearl not sure if this is something that falls under your area?

**Comment by JacksonKearl** [comment]
Yeah, that sounds neat. Though I wonder if the "new java project" should be part of something besides a "new file..." entry point. File vs Project?

**Comment by misolori** [comment]
In that case we can simply do `New...` as a generic jump-off point for all new things regardless of type. What do you think?

**Comment by digitarald** [comment]
Chatting about this with @chrisdias, we should clarify that this flow both covers new file and but also **new projects**; so putting it all behind "New File" seems a bit confusing. One idea was to use the separators that the theme picker has to have both in one list.

**Comment by misolori** [comment]
@digitarald see my comment above about combining into a `New...` instead (so removing "file"). Not sure whether we need a separator for projects as this would include all items and what other extensions would also use "projects"?

**Comment by digitarald** [comment]
Ha, missed that last dialog!

> Not sure whether we need a separator for projects as this would include all items and what other extensions would also use "projects"?

Java contributes a "Create New Project" and C++ is thinking about a wizard as well.

**Comment by Stirfry70** [comment]
Just wanted to see if I could get any tractionSent using the mobile mail appOn 6/9/21 at 4:52 PM, Harald Kirschner wrote:
                
            
            
                
                    From: "Harald Kirschner" ***@***.***>Date: June 9, 2021To: "microsoft/vscode" ***@***.***>Cc: "Subscribed" ***@***.***>Subject: Re: [microsoft/vscode] Explore extension contributions to the "New File..." item (#124304)
                
                
Ha, missed that last dialog!

Not sure whether we need a separator for projects as this would include all items and what other extensions would also use "projects"?

Java contributes a "Create New Project" and C++ is thinking about a wizard as well.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/microsoft/vscode/issues/124304#issuecomment-858174525",
"url": "https://github.com/microsoft/vscode/issues/124304#issuecomment-858174525",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chrisdias** [comment]
ha - i missed "project" in both lists too :)  

We can probably drop the "New" from the quick pick list, its duplicative and will make it easier to scan for your favorite langauge.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/122504105-69ba2c80-cfae-11eb-9cb3-07fba801f774.png)

**Comment by misolori** [comment]
I originally thought the "New" would be reserved for files and not window management. Maybe it's just me but it seems like it takes a lot more time to process the options and slows you down.

I also thought that when there are no items contributed it would be the default "New File" and when there are more items it would morph into the "New..."?

**Comment by JacksonKearl** [comment]
Agree the above is loud, but I do think there's value in bringing some of the new window commands into the spotlight... even some our own team members don't know about window duplication commands, yet window duplication is one of the most requested features of all time. One thing that I think helps is grouping by category and removing detail text where not needed (in Insiders today), and also sorting the items so files and notebooks are at the top (currently in `main`): 
![image](https://user-images.githubusercontent.com/8586769/122803198-2516e580-d27b-11eb-95cd-4f09ae2ec41a.png)

(note I don't necessarily think *all* of those items should exist in the menu, just trying to get a feel for what the menu will look like once many extensions contribute... I made https://marketplace.visualstudio.com/items?itemName=jakearl.demo-create-new-entries to help with exploring the feel)
