### ISSUE TITLE
não estou conseguindo adicionar imagens no meu site

### ISSUE THREAD

**Issue by vitoria2002campos** [microsoft/vscode#124312]
Nós escrevemos os dados necessários em sua ár
Issue Type: <b>Bug</b>

Bom estou muito nervosa porque já faz dois dias que estou tentando colocar imagens no meu projeto que tenho que entregar (um dos) que no caso ja estou atrasada. Seguinte... criei uma pasta chamada img para armazenar minhas imagens e assim colocar no meu site. Só que quando vou digitar o nome não aparece nenhum arquivo relacionado ao que eu quero ,  sendo que coloco os codigos corretos
<img scr="img/imagem1.pgn"> Por gentileza me retornem porque tenho que terminar esse projeto que mal comecei e já era pra eu ter terminado!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.06GB free)|
|Process Argv|--crash-reporter-id add9319d-3333-4846-aff1-ee6dafa8bc69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
live-html-previewer|hdg|0.3.0
vscode-language-pack-pt-BR|MS-|1.56.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

ea de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by RLThomaz** [comment]
Esse não é o lugar certo para pedir ajuda com projetos, procure seu professor ou algum colega para te auxiliar. Caso acredite que o problema seja com o VSCode, seja mais específica com o problema e como podemos reproduzi-lo.

---

This is not the right place to ask for assistance on assignments, look out for your Professor or colleagues to help you out. In case you believe this is an issue strictly related to VSCode, please, detail the issue and how we can reproduce it.
