### ISSUE TITLE
Welcome page not loading

### ISSUE THREAD

**Issue by Charlie-Sumorok** [microsoft/vscode#124386]
Issue Type: <b>Bug</b>

- Attempt to open welcome page
- See error appear saying that a file was not found

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv|--crash-reporter-id 664964bd-d748-4598-b834-0db5f9508abf|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
emoji-log-vscode|ahm|1.0.0
css-snippets|Aji|1.0.1
arepl|alm|2.0.2
sort-imports|ama|6.2.6
electron-snippets|ant|1.0.3
filewatcher|App|1.0.3
vscode-linux-binary-preview|bet|1.1.2
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-yaml-preamble|bie|0.0.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
codestream|Cod|11.0.7
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.21
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|6.4.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.26.0
mdmath|goe|2.5.1
vscode-test-explorer|hbe|2.20.0
output-colorizer|IBM|0.1.2
useful-react-snippets|igo|3.0.0
search-node-modules|jas|1.3.0
react-component|jer|1.0.4
node-module-intellisense|lei|1.5.0
vscode-python-test-adapter|lit|0.6.8
vscode-regexp-preivew|Lul|1.0.0
vscode-github-actions|me-|3.0.1
python-path|mge|0.0.11
pack-apache|mpt|0.1.1
vscode-apache|mrm|1.2.0
vscode-json5|mrm|1.0.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
hexeditor|ms-|1.6.0
vsliveshare|ms-|1.0.4272
nextjs-snippets|Pul|0.0.3
qub-xml-vscode|qub|1.2.8
quicktype|qui|12.0.46
new-file-by-type|Rec|1.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
nextjs-vscode-snippets|ret|0.1.1
LiveServer|rit|5.6.1
vscode-open|san|0.1.0
js-jsx-snippets|sky|10.1.0
snippets|tah|1.2.0
markdown-links|tch|0.8.0
vscode-gitmoji-snippets|thi|3.2.0
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.14
vscode-svg-previewer|vit|0.7.0
vscode-icons|vsc|11.4.0
gitmoji-vscode|Vtr|1.0.6
nodejs-extension-pack|wad|0.1.9
caniuse-query|Wil|0.0.1
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by JacksonKearl** [comment]
Thanks for the report, are you referring to this welcome page: 
![image](https://user-images.githubusercontent.com/8586769/119184254-00d0aa80-ba2a-11eb-9e49-33d8141ecf85.png)
?

What does the error message say exactly?

**Comment by Charlie-Sumorok** [comment]
Yes, I am referring to that welcome page.


Here is the error message
```
Unable to open 'vs_code_welcome_page': Unable to resolve resource walkThrough:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D.
```

**Comment by tntc4** [comment]
same
![Screenshot_1](https://user-images.githubusercontent.com/3246834/119470716-44d8ed80-bd51-11eb-8301-fbd9f32d432c.png)

**Comment by nagarjunr** [comment]
I have same issue too!

**Comment by JacksonKearl** [comment]
Tried a bunch of different platforms and still haven't been able to reproduce this. Is there anything special about your user names that might cause path problems? (special characters/spaces/etc.)?

**Comment by tntc4** [comment]
lul my username is TNT

**Comment by Charlie-Sumorok** [comment]
No, I don't think there are any characters in my username that would cause path problems.

**Comment by Charlie-Sumorok** [comment]
There is a different error when there is no folder open.
`Unable to open '': Unable to resolve resource walkThrough://vscode_getting_started_page.`

**Comment by nagarjunr** [comment]
This is the error, I get on startup:

![image](https://user-images.githubusercontent.com/7522071/120876557-fb579080-c5e3-11eb-909a-6e93a4fb7e85.png)

Even when I manually try to open Welcome screen, I get the similar error as follows:

![image](https://user-images.githubusercontent.com/7522071/120876587-2a6e0200-c5e4-11eb-8839-a59eacd19a9d.png)

**Comment by JacksonKearl** [comment]
The resource is in the main workbench bundle, so it's expected that you won't see it on disk, the loader should take care of finding it in the bundle. If you try on the latest [insiders](https://code.visualstudio.com/insiders/) do you still have this error?

**Comment by Charlie-Sumorok** [comment]
Yes, the error only occurred after copying settings over

```json
{
	"editor.fontSize": 16,
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"name": "One Dark italic",
				"scope": [
					"comment",
					"entity.other.attribute-name",
					"keyword",
					"markup.underline.link",
					"storage.modifier",
					"storage.type",
					"string.url",
					"variable.language.super",
					"variable.language.this"
				],
				"settings": {
					"fontStyle": "italic"
				}
			},
			{
				"name": "One Dark italic reset",
				"scope": [
					"keyword.operator",
					"keyword.other.type",
					"storage.modifier.import",
					"storage.modifier.package",
					"storage.type.built-in",
					"storage.type.function.arrow",
					"storage.type.generic",
					"storage.type.java",
					"storage.type.primitive"
				],
				"settings": {
					"fontStyle": ""
				}
			}
		]
	},
	"editor.accessibilitySupport": "off",

	"emmet.excludeLanguages": [
		"markdown"
	],
	"editor.suggestSelection": "first",
	"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
	"vetur.format.options.tabSize": 4,
	"editor.insertSpaces": false,
	"emmet.showSuggestionsAsSnippets": true,
	"emmet.triggerExpansionOnTab": true,
	"editor.fontFamily": "Fira Code",
	"editor.tabCompletion": "on",
	"typescript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
	"typescript.implementationsCodeLens.enabled": true,
	"diffEditor.codeLens": true,
	"python.languageServer": "Pylance",
	"editor.wordWrap": "on",
	"python.analysis.typeCheckingMode": "basic",
	"xo.enable": true,
	"workbench.preferredLightColorTheme": "Atom One Light",
	"workbench.preferredDarkColorTheme": "Atom One Dark",
	"window.autoDetectColorScheme": true,
	"workbench.editorAssociations": [
		{
			"viewType": "default",
			"filenamePattern": "*"
		},
		{
			"viewType": "default",
			"filenamePattern": "*.gif"
		},
		{
			"viewType": "default",
			"filenamePattern": "*.html"
		},
		{
			"viewType": "jupyter.notebook.ipynb",
			"filenamePattern": "*.ipynb"
		}
	],
	"svg.preview.transparencyGrid": false,
	"svg.preview.boundingBox": false,
	"editor.smoothScrolling": true,
	"workbench.list.smoothScrolling": true,
	"editor.mouseWheelZoom": true,
	"prettier.useTabs": true,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"prettier.singleQuote": true,
	"python.pythonPath": "/usr/local/bin/python3",
	"terminal.integrated.copyOnSelection": true,
	"terminal.integrated.cursorBlinking": true,
	"terminal.integrated.cursorStyle": "line",
	"terminal.integrated.sendKeybindingsToShell": true,
	"editor.fontLigatures": true,
	"codeQL.telemetry.enableTelemetry": false,
	"workbench.colorTheme": "Atom One Dark",
	"workbench.iconTheme": "vscode-icons",
	"window.titleBarStyle": "native",
	"window.nativeTabs": true,
	"pythonPreview.code.fontSize": "16",
	"terminal.integrated.fontSize": 16,
	"debug.console.fontSize": 16,
	"workbench.editor.enablePreview": false,
	"ACReactComponentGenerator.mainFile.extension": "tsx",
	"ACReactComponentGenerator.indexFile.extension": "ts",
	"ACReactComponentGenerator.styleFile.type": "standard (.css)",
	"liveServer.settings.host": "localhost",
	"git.autofetch": true,
	"snippets.snippetsLocation": "/Users/charlie/Library/Application Support/Code/User/globalStorage/tahabasri.snippets/data.json",
	"markdown.extension.print.theme": "dark",
	"markdown.extension.toc.slugifyMode": "vscode",
	"[markdown]": {
		"editor.wordWrap": "on",
		"editor.quickSuggestions": false,
		"editor.useTabStops": false,
		"editor.insertSpaces": true,
		"editor.tabSize": 2
	},
	"editor.renderControlCharacters": true,
	"editor.formatOnSave": true,
	"workbench.editor.highlightModifiedTabs": true,
	"files.autoSave": "afterDelay",
	"files.autoSaveDelay": 5000,
	"todo-tree.general.tags": [
		"BUG",
		"HACK",
		"FIXME",
		"TODO",
		"XXX",
		"[ ]",
		"[x]"
	],
	"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",
	"editor.formatOnPaste": true,
	"workbench.startupEditor": "welcomePage"
}
```

**Comment by JacksonKearl** [comment]
Thanks, that helps. The issue is in this line:

```
{"workbench.editorAssociations": { "*": "default" }}
```

If this is present Welcome and Getting Started break. It seems the glob is picking up the `walkThrough` scheme URI's we use to identify the editors and trying to open them in the native text editor. cc @lramos15 for ideas on next steps here.

**Comment by mrxiaozhuox** [comment]
I have edit the `workbench.editorAssociations` to `{ "*": "default" }`.
but the problem remain.

```
“vs_code_welcome_page”: Unable to resolve resource walkThrough:/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D。
```

**Comment by lramos15** [comment]
> I have edit the `workbench.editorAssociations` to `{ "*": "default" }`.

This is exactly what you don't want. If you delete that setting it should work.
