### ISSUE TITLE
$getTunnels does not expose public although it is available on vscode.TunnelDescription api

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#124334]
https://github.com/microsoft/vscode/blob/2fae6ffacd478a0cab2ca40df5067cda9b51db67/src/vs/workbench/api/browser/mainThreadTunnelService.ts#L131-L138

**Comment by roblourens** [comment]
Sorry I don't understand what you are asking for

**Comment by akosyakov** [comment]
- `TunnelDescription` has `public` property: https://github.com/microsoft/vscode/blob/5319757634f77a050b49c10162939bfe60970c29/src/vs/vscode.proposed.d.ts#L101
- one can fetch current tunnels with `vscode.workspace.tunnels`: https://github.com/microsoft/vscode/blob/5319757634f77a050b49c10162939bfe60970c29/src/vs/vscode.proposed.d.ts#L207
- underling implementation never provide `public` property: https://github.com/microsoft/vscode/blob/2fae6ffacd478a0cab2ca40df5067cda9b51db67/src/vs/workbench/api/browser/mainThreadTunnelService.ts#L131-L138

**Comment by alexr00** [comment]
`public` has since been deprecated. Added the new `privacy`, which replaces `public`, instead.

**Comment by jrieken** [comment]
verified in code
