### ISSUE TITLE
The console will print exception information every time an extension developed based on webview is activated

### ISSUE THREAD

**Issue by zgh0711** [microsoft/vscode#124320]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

I have an extension developed based on webview. It worked normally before vscode version 1.56, but after vscode was upgraded to version 1.56, the extension had some problems.

The extension is actually a custom editor for xml files, and the main body is a web program developed based on vue.js.

Every time I click the xml file to open the editor, I can see several errors on the console. I don't know how to solve these errors.

```text
Error: Unable to read file 'e:\Projects\VsCode\PersimWear-Studio\web-designer\dist\' (Error: Unable to read file 'e:\Projects\VsCode\PersimWear-Studio\web-designer\dist\' that is actually a directory)
    at o.doReadFileStream (fileService.ts:529)
    at async w (resourceLoading.ts:98)
    at async p.loadResource (baseWebviewElement.ts:487)
index.html:1 GET https://de00ca1f-770f-46e4-a744-c28e285a70b7.vscode-webview-test.com/vscode-resource/file///e%3A/Projects/VsCode/PersimWear-Studio/web-designer/dist/ 404
vscode-webview://de00ca1f-770f-46e4-a744-c28e285a70b7/index.html?id=de00ca1f-770f-46e4-a744-c28e285a70b7&extensionId=RT-Thread.mini-studio&purpose=undefined&serviceWorkerFetchIgnoreSubdomain=undefined&platform=electron&vscode-resource-origin=https%3A%2F%2Fde00ca1f-770f-46e4-a744-c28e285a70b7.vscode-webview-test.com#/editor:1 Access to font at 'https://de00ca1f-770f-46e4-a744-c28e285a70b7.vscode-webview-test.com/file///e:ProjectsVsCodePersimWear-Studiopersim-sdkplatformspersimwear-2%0FontsHYQIHEI-55J.TTF' from origin 'vscode-webview://de00ca1f-770f-46e4-a744-c28e285a70b7' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
fonts.css:1 GET https://de00ca1f-770f-46e4-a744-c28e285a70b7.vscode-webview-test.com/file///e:ProjectsVsCodePersimWear-Studiopersim-sdkplatformspersimwear-2%0FontsHYQIHEI-55J.TTF net::ERR_FAILED
```

## Extension and sample project
The problems mentioned above only appeared under the vscode 1.56 version, and there were no such problems before. I can't solve these problems now, and hope to tell me how to solve them.

My extension and an example project are attached below:
[NewProject.zip](https://github.com/microsoft/vscode/files/6515659/NewProject.zip)

**Comment by zgh0711** [comment]
I will upload a debug extension later. Please wait

**Comment by mjbvz** [comment]
The uploaded zip doesn't seem to contain any extension code

Closing this as we need more information to investigate this
