### ISSUE TITLE
Consider to add a property to editor inputs to get at the editor that was used

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124354]
As discussed, we currently probe onto a `viewType` in editor inputs to figure out the editor that was used when the opening was overridden (e.g. custom editors, notebooks). We should think about making this a general concept going forward. 

Some rough notes from our discussion:
* how does this correlate with the existing `typeId`?
* should this be a required property for all editors (even e.g. welcome editor? extensions editor? that are typically never overridden)
* can we find a name that makes it clear the value of this "thing" can be used in the `override` option to enforce this editor?
* does it make sense to call a text editor `default` for this property, or should that change too? what does `default` really mean here?

**Comment by bpasero** [comment]
Given https://github.com/microsoft/vscode/pull/124394#pullrequestreview-666598251, not sure this is needed anymore.

**Comment by lramos15** [comment]
This was added by #126410
