### ISSUE TITLE
Incorrect syntax highlighting for .properties files

### ISSUE THREAD

**Issue by csnv** [microsoft/vscode#124348]
Single quote characters hold no special meaning in .properties files, however, vscode highlighting tries to match a second quote even on different lines.
.properties files follow the syntax [key]=[value] where the value is simple text and can contain any character.

How to reproduce:
- Create a new .properties file
- Add a key-value pairs with random single quote as per the attached image

![image](https://user-images.githubusercontent.com/890582/119120549-b270db00-ba2c-11eb-9363-d06e06b4b868.png)

**Comment by alexr00** [comment]
Can you please share a copy/pastable sample?
