### ISSUE TITLE
Tests will run 2 times when lazy-load and autorun are enabled

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#124333]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (user setup)
Commit: 0b355ffc89b2020a941ce149f2704acf13a49afd
Date: 2021-05-20T17:07:35.142Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Given a project which may have multi-level test items, and only the root node is resolved.
2. Turn on auto-run
3. A test run request triggered with the root node
4. The children of the root node are resolved because we need to append test results to them
5. Because new test items(those children) are added into the tree, another test run request triggered with those children. This is redundant because they have just update the result.

It would be helpful if VS Code can eliminate these 'duplicated' run request, or VS Code can have any APIs that extensions can use to eliminate them.

**Comment by connor4312** [comment]
Good find

**Comment by jdneo** [comment]
Hi @connor4312, I noticed that if the test results are skipped, the tests will be triggered again for 1 time. Is that by design?

**Comment by connor4312** [comment]
Thanks, fixed that as well

**Comment by jdneo** [comment]
Hi @connor4312, I tried the insider with version:

Version: 1.57.0-insider (user setup)
Commit: c7119ae8b6390a5700f6b28f0f1511d676c96562
Date: 2021-06-08T09:17:55.672Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Seems it's still having the issue. You can try with the `test-provider-sample` project and always set the test status to `Skipped` and then enable auto run in test explorer.

**Comment by connor4312** [comment]
Hm, I don't see this on the latest build, are there additional steps for this?

![](https://memes.peet.io/img/21-06-72220173-6813-4b5b-8789-1a8567f39811.gif)

**Comment by jdneo** [comment]
I just tried with 

Version: 1.57.0-insider (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T11:49:36.076Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

It works properly now!
