### ISSUE TITLE
Clean-up `foo: SomeType | undefined` vs `foo?: SomeType`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#124362]
When defining optional values in object we generally prefer the question-mark notation but it seems that we aren't consistent with this. Ideally, we always use one way, min-bar should be to consistency per type, not like this

https://github.com/microsoft/vscode/blob/4c1474b458de0316a015b875fe9b0b4d95b9089e/src/vs/vscode.d.ts#L5600-L5611

**Comment by jrieken** [comment]
Might also be worth to add a API-lint rule for this

**Comment by mjbvz** [comment]
These have subtly different meanings:

- `property?: type` — You can simply omit the property / argument. You can also pass in `undefined` if you want to be explicit

- `property: type | undefined` — The must explicitly specify the property or argument by setting it to `undefined`

We can review places where these occur in our d.ts, but coming up with a lint rule for this is probably not possible

**Comment by mjbvz** [comment]
With TS 4.4, there's another complication: [Exact Optional Property Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#exact-optional-property-types)

This means that `?` is no longer automatically equivalent to `| undefined`

**Comment by mjbvz** [comment]
Here's a draft of guidance around this:

## For function/method parameters:

- Use `| undefined` when you always want to consumers to consider the parameter. 
- Use `?` when you want to allow users to omit the parameter. 
- Never use `?` and `| undefined` on a parameter. Always use `| undefined` instead as it is the more strict version of the two
- When implementing a function that uses `?`, omitting the optional parameter must have the same behavior as explicitly passing in `undefined`


## For properties

- Use `| undefined` when you always want consumers to have to consider the property.
- Use `?` when omitting the property is ok
- Do not write code that treats the absence of a property differently than a property being present but set to `undefined`
    - This can sometimes hit you on spreads or iterating through objects, so just something to be aware of
- If using `?`, always also add `| undefined` unless:
    - The property is readonly (but it doesn't hurt to add it in this case either)
    - You want to allow the property to be omitted during initialization, but never allow users to explicitly set it to `undefined` afterwards. I don't think we have many cases where this will be needed

**Comment by mjbvz** [comment]
For November, let's review classes that use `readonly property?: type`. I think almost all of these should be changed to `readonly property: type | undefined` instead because this makes it more clear that the property exists but is set to `undefined`.

Assigning owners per class:

- [ ] `ThemeIcon` @aeschli 
- [ ] `EvaluatableExpression` @weinand 
- [ ] `InlineValueVariableLookup` @weinand 
- [ ] `InlineValueEvaluatableExpression` @weinand 
- [ ] `SemanticTokens` @alexdima 
- [ ] `SemanticTokensEdits` @alexdima 
- [ ] `SemanticTokensEdit` @alexdima 
- [ ] `LinkedEditingRanges` @aeschli 
- [ ] `StatusBarItem` @jrieken 
- [ ] `TaskGroup` @alexr00 
- [ ] `Task` @alexr00 
- [ ] `DebugAdapterServer`  @weinand 
- [ ] `Breakpoint` @weinand 
- [ ] `TestRunRequest` @connor4312 
- [ ] `TestRun` @connor4312 
- [ ] `TestItem` @connor4312 

Let me know if you have any questions about fixing these cases

**Comment by alexdima** [comment]
@mjbvz IIRC I did mine a couple of weeks ago. Is there something more to do?

**Comment by aeschli** [comment]
With [exact-optional-property-types}(https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#exact-optional-property-types) extension authors will have to provide all properties of type `readonly property: type | undefined`.
Wouldn't that be a breaking change? 
For that reason I think it makes sense to keep `readonly property?: type` for optional properties.

**Comment by weinand** [comment]
Since the constructors of all my assigned classes are public, changing `readonly property?: type` into `readonly property: type | undefined` would be breaking. So no changes on my side.

**Comment by mjbvz** [comment]
@aeschli Not if the type is maintained by VS Code. It would be breaking if you make this change to an options bag object

@weinand You should not change the constructor arguments but change the property. For example, `DebugAdapterServer`

```ts
	export class DebugAdapterServer {
		readonly port: number;
		readonly host?: string;
		constructor(port: number, host?: string);
	}
```

Should become:

```ts
	export class DebugAdapterServer {
		readonly port: number;
		readonly host: string | undefined;
		constructor(port: number, host?: string);
	}
```

Using `| undefined` is more consistent in this case and also matches how these classes are implemented: https://github.com/microsoft/vscode/blob/042a6e36a495db9830029d87c12dd9b65c7e3b47/src/vs/workbench/api/common/extHostTypes.ts#L2463

**Comment by mjbvz** [comment]
@weinand and @aeschli Can you please quickly revisit your classes and update any cases that are similar to the above example

**Comment by weinand** [comment]
@mjbvz sorry Matt that I did not made myself clear:
since the constructor is not private, objects of class DebugAdapterServer can be created as `{ port: 1234 }` (which is actually done in some extensions. Changing `host?: string` to `host: string | undefined` breaks that code.

**Comment by aeschli** [comment]
@mjbvz Same for ThemeIcon, `const themeIcon : ThemeIcon = { id: 'zap' };` would no longer compile. 
If we don't encourage creating objects like that, I'll make the change (or feel free to make it yourself)

**Comment by mjbvz** [comment]
Thanks for the additional context

With typescript in general, if something is typed as `class`, we expect instances of that class. If you only care about the properties, use `interface` instead. However we do often use classes + constructors as quick ways to create simple objects with a few properties

So there are two options here:

1. If you want extensions to always create an instance of the class, change the properties to `readonly prop: type | undefined`

2. If you instead want to allow extensions to pass in objects with the same shape as the class, change the property on the class to: `readonly prop?: type | undefined`. That is ugly but I think makes the types correct for `strictOptionalProperties`

These change will not break the runtime behavior of extensions. However option `1` may break compilation for extensions that don't create instances of the class

**Comment by aeschli** [comment]
Thanks @mjbvz for looking into this and coming up with guidelines.
I went with `color?: ThemeColor | undefined;` for `ThemeIcon` as I expect some extensions to use the `{ id: 'zap' }` notation. We happen to do it in [our sample](https://github.com/microsoft/vscode-extension-samples/blob/116b0aa1ade25bfd3c6f3df0847200089b82b72f/decorator-sample/src/extension.ts#L30).
For `LinkedEditingRanges` I went with the recommended way.
Feel free to change this if you prefer to have this consistent.

**Comment by weinand** [comment]
@mjbvz thanks for your suggestions.

Since option 1 is breaking, we cannot use it. So I've [applied option 2](https://github.com/microsoft/vscode/commit/1a65006ff43d5760fd86f68ede3e34dc0f9fd06a) in all my cases.

**Comment by mjbvz** [comment]
Thanks. I'm going to close this and move the API guidance to a wiki

I believe `vscode.d.ts` mostly gets  `strictOptionalProperties` correct now. We can handle any other issues with it on a case by case basis since making a complete and thorough pass through the api doesn't seem worthwhile at this time
