### ISSUE TITLE
Handling of "repeated" mime types in notebook output

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#124357]
The notebook output API is very flexible and allows that a cell can have multiple `NotebookCellOutput`-objects with each having multiple `NotebookCellOutputItem`-objects. It esp. can lead to "repeated mime types"

```ts
// (A) separate output, same MIME type
task.replaceOutput([
    // output 1
    new vscode.NotebookCellOutput([
        // item 1.1
        vscode.NotebookCellOutputItem.text(rndOut, 'application/foo')
    ]),
    // output 2
    new vscode.NotebookCellOutput([
        // item 2.1
        vscode.NotebookCellOutputItem.text(rndOut, 'application/foo')
    ])
])

// (B) single output, repeated MIME type
task.replaceOutput([
    // output 1
    new vscode.NotebookCellOutput([
        // item 1.1
        vscode.NotebookCellOutputItem.text(rndOut, 'application/foo'),
        // item 1.2
        vscode.NotebookCellOutputItem.text(rndOut, 'application/foo')
    ]),
])
```

We handle the "separate output, same MIME type"-case correctly because we show both outputs at the same time, but for the "single output, repeated MIME type"-case we are not as good: 

1. for webview rendering we seem to pick the [first item that matches the desired mime-type](https://github.com/microsoft/vscode/blob/494e827e35134c3eb2a287f49009ddeab77c8dac/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L1483)
2. for built-in rendering we do our best to "merge" them, e.g we could [string-concat multiple data pieces](https://github.com/microsoft/vscode/blob/79e642a5ddbef877dd15651f0cedca69a01b7e1c/src/vs/workbench/contrib/notebook/browser/view/output/transforms/richTransform.ts#L140) for the `'text/x-javascript'` MIME-type 

What should be the correct behaviour? Should we restrict these cases in the API? Should we render each item individually or let renderer decide?

**Comment by kieferrm** [comment]
While A makes sense to me, my view of B is that this is an invalidly formed output because it boils down how we define the meaning of the array of output items. I think the meaning should be that each item in the array represents the same information. That's why we can switch renderers. If we consider duplicates mime times as a valid thing and even think about joining the item of the same time (if we'd know how to) then I believe that would switch the meaning of the array from "multiple representation of the same piece of information" to "a representation of one piece of information consisting of multiple different parts of the same or different media types" which would be incompatible with our renderer story.

**Comment by roblourens** [comment]
I agree that B is invalid, it also makes me think about how `new vscode.NotebookCellOutput([])` should be invalid too. Don't know whether we should filter them out or throw to the extension.

**Comment by jrieken** [comment]
>  it also makes me think about how new vscode.NotebookCellOutput([]) should be invalid too. Don't know whether we should filter them out or throw to the extension.

I believe the UI is good for that


For "repeated" mime types I have added a few checks

* in the UI we always pick the first - basically what was already happening for custom renderers
* in the ext host we drop repeated types and warn when using the constructors and execution API

**Comment by jrieken** [comment]
There is [agreement to remove](https://github.com/microsoft/vscode/issues/122922#issuecomment-851791942) metadata from `NotebookCellOutputItem` which means only `mime` and `data` is left.  This somehow makes it thinkable to remove the whole `NotebookCellOutputItem`-type and replace with function on its container type, e.g

```ts
class NotebookCellOutput {

  // set/replace data
  // insertion order
  set(data: Uint8Array, mime: string): void;

  // text overload
  set(text: string, mime: string = 'text/plain'): void;

  // JSON overload
  set(obj: any, mime: string = 'application/json'): void;

  entries(): [string, Uint8Array][];
}
```
