### ISSUE TITLE
Sort Breakpoints by Creation date

### ISSUE THREAD

**Issue by izacsc** [microsoft/vscode#124399]
Issue Type: <b>Feature Request</b>

I have many breakpoints setted in my environment. I would like to sort my breakpoints by Creation Date because it would make it easier to see the most recents.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by izacsc** [comment]
@isidorn Thanks! It also would be good if we could group the breakpoints by filename or even a label, but I understand that this may be much more complex.
