### ISSUE TITLE
How can I fix This?

### ISSUE THREAD

**Issue by Rahulkhinchi03** [microsoft/vscode#124365]
Issue Type: <b>Bug</b>

Missing artifact net.sf.saxon:Saxon-HE:jar:10.5
This is missing in my pom.xml file
File Link:  https://github.com/Rahulkhinchi03/checkstyle/blob/master/pom.xml

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.00GB free)|
|Process Argv|--crash-reporter-id f58d33ee-608c-415a-9610-f2cc7519b41c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
code-runner|for|0.11.4
cpptools|ms-|1.4.0-insiders
fabric8-analytics|red|0.3.3
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-java-checkstyle|ria|0.2.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by Rahulkhinchi03** [comment]
No this is different

**Comment by roblourens** [comment]
Is this an issue with the Java extension? If so, please file this on the repo for the Java extension
