### ISSUE TITLE
Pylance language server getting error due to User config file not found in remote server

### ISSUE THREAD

**Issue by palladiun** [microsoft/vscode#124452]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Connect to a remote system via ssh
2. Use Python

[error.txt](https://github.com/microsoft/vscode/files/6527869/error.txt)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
