### ISSUE TITLE
Confusing document for QuickPick API

### ISSUE THREAD

**Issue by Semperia** [microsoft/vscode#124484]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Darwin x64 19.6.0

I was confused by the QuickPick API as `activeItems` and `selectedItems` were commented "This can be read and updated by the extension." while `items` wasn't. Then I was trying to dispose QuickInput and create a new one to update items, but after I read the source code I found `items` can be directly updated by extensions
https://github.com/microsoft/vscode/blob/5319757634f77a050b49c10162939bfe60970c29/src/vs/base/parts/quickinput/browser/quickInput.ts#L514-L518

**Comment by TylerLeonhardt** [comment]
verification: look at the PR. It updated a vscode.d.ts comment.
