### ISSUE TITLE
The VSCode terminal uses the system Python interpreter rather than the active conda env interpreter to execute code in the terminal

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode#124425]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Darwin x64 19.6.0

From the VSCode terminal, I create a conda environment, activate it and install a package:
```
conda create -n myenv python=3.6
conda activate myenv
conda install pandas
```
I restart VSCode, so that I can select the corresponding Python interpreter as the current interpreter:

![image](https://user-images.githubusercontent.com/8233615/119232260-e3ccd200-bb24-11eb-8bfb-ffa7e94c2188.png)

and I successfully activate the corresponding conda env in the VSCode terminal:
```
(base) xxx:~ xxx$ conda activate myenv
(myenv) xxx:~ xxx$ 
```
I create a script `test.py` which uses pandas
```
import pandas as pd
print(pd.__version__)
```
and I try to run it from the VSCode terminal:
```
(myenv) GC02WC0GVHTDFE:~ andreapanizza$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pandas as pd
ImportError: No module named pandas
```
Apparently, VSCode terminal continues to use the system installation of Python even though I selected the interpreter corresponding to the conda environment:
```
(myenv) GC02WC0GVHTDFE:~ andreapanizza$ python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

This is really annoying. Can you fix the terminal so that when one selects a conda env, the terminal uses the corresponding Python interpreter?

**Comment by Stig124** [comment]
It seems that it is a known issue, it does work on ZSH (OpenSUSE) (with the `venv` oh-my-zsh plugin) though
See https://code.visualstudio.com/updates/v1_36#_launch-terminals-with-clean-environments

**Comment by AndreaPi** [comment]
Thanks @Stig124 but I'm on MacOS, not OpenSUSE. I had a look at your link: are you suggesting that I set `terminal.integrated.inheritEnv: false`?

**Comment by Stig124** [comment]
> Thanks @Stig124 but I'm on MacOS, not OpenSUSE. I had a look at your link: are you suggesting that I set `terminal.integrated.inheritEnv: false`?

This is the link suggested by the Python ext itself when I opened my conda env., it works well with that option on for me (surely because I use the python oh-my-zsh module as it autloads venvs and bypass app shells)


And the zsh method work well on mac too, installing [oh-my-zsh](https://ohmyz.sh) and adding the `pylint` and `python` plugins
