### ISSUE TITLE
Is it possible to insert cursors anywhere using a keyboard only?

### ISSUE THREAD

**Issue by septsea** [microsoft/vscode#124461]
I knew I could insert cursors anywhere using Alt + Click, but I still wonder how I can do this without a mouse. I have difficulty using a mouse.

I cannot find a related command in the Command Palette.

**Comment by alexdima** [comment]
There are multiple commands for adding cursors with the keyboard. Please see our documentation -- https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by septsea** [comment]
@alexdima 
Thanks for your reply. I knew shortcuts such as `Ctrl+Alt+Arrow` and `Ctrl+D`. I wonder what I am supposed to do to insert multiple cursors _arbitrarily_. In other words, is there any way to do what `Alt + Click` does without a mouse?

**Comment by alexdima** [comment]
> In other words, is there any way to do what `Alt + Click` does without a mouse?

There is no way.
