### ISSUE TITLE
pytest test discover failed

### ISSUE THREAD

**Issue by browncrane** [microsoft/vscode#124459]
Issue Type: <b>Bug</b>

Now sure how to reproduce it, however, the error message like "
Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+/root/.config/Code/User/settings.json')"

The error didn't go away, after restart vscode.

The condition here is,vscode with remote connect to a CentOS server. It was all right for about one day. No clue how it comes to this way.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-1160.15.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.43GB (12.95GB free)|
|Process Argv|--crash-reporter-id 5e114898-d158-426e-a385-5eb43db098c9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: MagiDev|
|OS|Linux x64 3.10.0-1160.15.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (4 x 1699)|
|Memory (System)|7.64GB (6.03GB free)|
|VM|100%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
fluent-icons|mig|0.0.11
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
vscode-icons|vsc|11.4.0
vim|vsc|1.20.3
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vsc-python-indent|Kev|1.14.2
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
vetur|oct|0.33.1
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by roblourens** [comment]
What did you do to show this error? How is pytest involved?
