### ISSUE TITLE
By default, trust domain don't support: portal.azure.com

### ISSUE THREAD

**Issue by 1openwindow** [microsoft/vscode#124487]
By default, trust domain don't support: portal.azure.com. I suppose portal.azure.com should supported by default.

![image](https://user-images.githubusercontent.com/26411726/119310448-56af8780-bca2-11eb-9ed3-60b623cfb8a4.png)

**Comment by roblourens** [comment]
Even microsoft.com isn't there by default. I don't think azure should be.
