### ISSUE TITLE
Mardown preview not correctly rendering charecters following a reserved character

### ISSUE THREAD

**Issue by depascalis** [microsoft/vscode#124430]
Issue Type: <b>Bug</b>

If there is a reserved character in a .md file, the charecters directly following the reserved charecter does not render correctly.

Steps to reproduce: Copy and paste the snippet bellow into a .md file, run `markdown.showPreview`

```markdown
[&#x1F5F8;](/	"Check Mark")	

[&#x1D50B;](/	"<reserved>")
[&#x1F5F8;](/	"SAME CHARACTER AS ABOVE")

Reserved character -> 𝔺

Reserved character followed by a checkmar -> 𝔺🗸

Same checkmark by its own 🗸
```

![image](https://user-images.githubusercontent.com/33980634/119235700-221dbd80-bb34-11eb-9fe2-a60d45811b71.png)

Edit: I see now when posting the report that the same issue is present here on GitHub. The issue is probably in the markdown language itself.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by mjbvz** [comment]
Our markdown rendering is powered by markdown-it. If there appears to be a bug, please file an issue against markdown-it
