### ISSUE TITLE
tooltip text grabbing broken

### ISSUE THREAD

**Issue by netanel-haber** [microsoft/vscode#124457]
Issue Type: <b>Bug</b>

Hover over any tooltip generating text. Grabbing text with mouse doesn't work.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.0.0-32-generic

**Comment by roblourens** [comment]
Which tooltips are you looking at? Native OS tooltips have never been copiable.

**Comment by netanel-haber** [comment]
The issue is with vscode hover tooltips - such as shown in this attachment:
![image](https://user-images.githubusercontent.com/58652339/119473558-f2e59700-bd53-11eb-9ffb-28c6e7d59ec3.png)
I've always been able to copy from them, and now grabbing doesnt work at all.

**Comment by roblourens** [comment]
Check that you didn't disable `editor.hover.sticky`

**Comment by netanel-haber** [comment]
Can confirm that editor.hover.sticky was (and is enabled) - I should clarify that the issue I described wasn't that hovering over the tooltip makes the tooltip disappear - the tooltip remains visible when hovering over it with the mouse - it just doesn't allow for grabbing the content.

**Comment by netanel-haber** [comment]
Hi - it seems that the problem was my chosen theme (the vscode solarized light) highlight color just didn't indicate that text was being grabbed with the grayish overlay color usually present - this has never been a problem. I assume this means that this wouldn't be considered an issue with vscode? If so, where should I submit issues with builtin vscode themes?

**Comment by alexdima** [comment]
@misolori @aeschli Do you know who owns this theme and its color for selected text? It looks like the selected text color (not the editor selected text color) is the same as the hover background:

https://user-images.githubusercontent.com/5047891/120210337-f5eaf680-c22f-11eb-9761-8c2f1c75cce5.mp4

**Comment by aeschli** [comment]
Same reason as #123044. Looks like the workbench selection color defined by the theme is now used by Electron, but wasn't before. Fixing the color...

The color id is `"selection.background"`
