### ISSUE TITLE
Support for Python requirements.txt

### ISSUE THREAD

**Issue by Ben-Faessler** [microsoft/vscode#124431]
Can you please add support for python requirements.txt? I imagine it like this:
I open a directory in VS Code.
VS Code recognises the requirements.txt, checks the set python for the modules, if not installed ask if you want to install them, if yes install.
I would be very happy about this feature.

**Comment by joyceerhl** [comment]
This request is tracked in https://github.com/microsoft/vscode-python/issues/4606 and would likely be addressed in the Python extension for VS Code.
