### ISSUE TITLE
terminal is not working so please help me fast ..

### ISSUE THREAD

**Issue by Bharti180567** [microsoft/vscode#124447]
Issue Type: <b>Feature Request</b>

pls help my teminal is not warking ..
\

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19043

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
