### ISSUE TITLE
There is a "title" attribute of the configuration property schema that doesn't do anything

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#124438]
Issue Type: <b>Bug</b>

sdfsdf

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|-psn_0_30354673 --crash-reporter-id 8a1dca50-bfd2-4ed7-8721-07dc12b8f52d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
Bookmarks|ale|13.0.4
npm-intellisense|chr|1.3.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.20
tsl-problem-matcher|eam|0.4.0
vscode-html-css|ecm|1.10.2
graphviz-preview|EFa|1.3.3
vscode-npm-script|eg2|0.3.21
lex-flex-yacc-bison|fau|0.0.3
php-intellisense|fel|2.3.14
vscode-mysql|for|0.4.0
triggertaskonsave|Gru|0.2.17
reg|ion|1.0.3
latex-workshop|Jam|8.18.0
mediawiki|jas|0.0.4
swift|Kas|0.2.0
favorites|kdc|2.4.5
vscode-phpfmt|kok|1.0.30
logos|NSE|0.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
syntax-project-pbxproj|mar|0.1.3
vscode-clang|mit|0.2.4
perl-debug|mor|0.6.3
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
objective-clean|obj|1.0.0
psi-header|psi|1.15.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
perl|ric|2.2.0
vscode-paste-and-indent|Rub|0.0.8
vscode-autohotkey|sle|0.2.2
tmlanguage|Tog|0.9.0
clang-format|xav|1.9.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

Screenshots below of example property and the resulting UI

<img width="490" alt="Screenshot 2021-05-22 at 8 27 04 PM" src="https://user-images.githubusercontent.com/8371943/119245148-88a6d980-bb3c-11eb-961a-10ae3bfae5df.png">
<img width="320" alt="Screenshot 2021-05-22 at 8 30 58 PM" src="https://user-images.githubusercontent.com/8371943/119245158-a5431180-bb3c-11eb-99a8-a5c9af0c6528.png">

**Comment by roblourens** [comment]
Yeah, this and many other properties come from JSON schema, but not all JSON schema properties are used for something in our GUI. There is another issue to give extensions more control over their setting display, I think https://github.com/microsoft/vscode/issues/70589. Maybe I would use it for that. Currently it does show up if you hover the setting in the json editor.

**Comment by NSExceptional** [comment]
I would love it to be used for the final path component of the setting name, since it can be difficult to get it to display properly if you want it to be something complex like `NSArray` or `initWithFoo: → +new`
