### ISSUE TITLE
Terminal: An environment variable for when ConPTY is enabled on Windows

### ISSUE THREAD

**Issue by andrew-r-king** [microsoft/vscode#124427]
I'm writing a terminal application (in C++) that does various checks for when a terminal on windows supports ANSI escape codes. I found an interesting nuance where if `"terminal.integrated.windowsEnableConpty"` is set to either true or false, there's no way to really detect it from the application since the environment variables don't differ. In C++ land, I think I can only see if the ConPTY api is available on the system at all, not whether the parent process is using it (although I could be wrong). 

Anyway, I could check for this very easily with an environment variable.  It looks like VS Code already does stuff like this (like the ones below, grabbed via SET), so I figured this would be an easy/useful addition.

```
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.56.2
LANG=en_US.UTF-8
COLORTERM=truecolor
VSCODE_GIT_IPC_HANDLE=...
GIT_ASKPASS=...
VSCODE_GIT_ASKPASS_NODE=...
VSCODE_GIT_ASKPASS_MAIN=...
```

**Comment by Tyriar** [comment]
I'd prefer not to add yet another environment variable for this as it's such a niche thing. If you need to detect if it's conpty I'd recommend checking for `winpty-agent.exe` in the process tree

![image](https://user-images.githubusercontent.com/2193314/119339676-51245400-bc46-11eb-8210-c1c4337774b2.png)

**Comment by andrew-r-king** [comment]
> 
> 
> I'd prefer not to add yet another environment variable for this as it's such a niche thing. If you need to detect if it's conpty I'd recommend checking for `winpty-agent.exe` in the process tree
> 
> ![image](https://user-images.githubusercontent.com/2193314/119339676-51245400-bc46-11eb-8210-c1c4337774b2.png)

Ah yeah, that's so much easier than reading an environment variable set by the process that owns the responsibility of the feature. 🙄

**Comment by Tyriar** [comment]
Never said it was easier, I don't think it's worth cluttering the environment further when you may be the only consumer of it.

**Comment by andrew-r-king** [comment]
Right, but this would be literally describing the environment. You could fetch it from any language. How is that not useful?

**Comment by Tyriar** [comment]
Whether it's winpty or conpty is not meant to matter, plus winpty support is deprecated. Any extra variables are clutter, we set the absolute bare minimum so that the terminal works well (colorterm, term, term_program*, lang). There are the `VSCODE_GIT_*` ones but they aren't added by the core but the git extension and can be disabled if desired, plus they enable the very useful git auth feature.

Just like with extension APIs, we don't add them if they aren't generally useful to multiple consumers.

If I was you I wouldn't even bother trying to make the experience good on winpty, it's a legacy component only sticking around to support < Windows 10. But I told you how to detect it yourself too.

**Comment by andrew-r-king** [comment]
Thanks for that explanation. That makes more sense. I'll just check for one of the other variables (COLORTERM I guess) and be done with it.

The winpty-agent.exe check just isn't realistic sadly. This is meant to be a small check to run on startup, The parent Code.exe process does not seem to own winpty-agent.exe, which means it's under one of the other Code.exe processes. The idea of iterating through them all each time for this check seems ridiculous.

>
> If I was you I wouldn't even bother trying to make the experience good on winpty, it's a legacy component only sticking around to support < Windows 10. But I told you how to detect it yourself too.

I guess, but someone in windows 10 can turn that setting to false and get a rough terminal experience with ANSI escape codes everywhere.

**Comment by Tyriar** [comment]
> I guess, but someone in windows 10 can turn "terminal.integrated.windowsEnableConpty" to false and get a rough terminal experience with ANSI escape codes everywhere.

There's basically no reason to do this after the upcoming version comes out since it fixes the issue where conpty hangs (https://github.com/microsoft/vscode/issues/71966), it should be better in every way. If they chose to opt in to the degraded experience it's kind of on them.

**Comment by andrew-r-king** [comment]
That's fair. Thanks!
