### ISSUE TITLE
`Cursor Redo` and `Cursor Undo` don't have the same `when` condition

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#124448]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.56.2
- OS Version: Windows 10

`Cursor Redo` and `Cursor Undo` don't have the same `when` condition:

![image](https://user-images.githubusercontent.com/28700378/119252542-8053aa80-bbdf-11eb-8c44-3d2c3de50ce1.png)

![image](https://user-images.githubusercontent.com/28700378/119252551-8d709980-bbdf-11eb-98fd-622eb8c727f4.png)

**Comment by alexdima** [comment]
@wenfangdu The reason the `when` context is not rendered is because the Cursor Redo action does not have a keybinding by default.

**Comment by wenfangdu** [comment]
@alexdima Indeed, I just checked out the commands which don't have default keybindings, and they all have an empty `When` clause, I guess that's normal then?

![image](https://user-images.githubusercontent.com/28700378/120559776-387d2080-c434-11eb-80f2-edc552d35c7c.png)

**Comment by alexdima** [comment]
Yes, the `when` field describes the associated keybinding, it is not an inherent property of the command/action.
