### ISSUE TITLE
CSS background image link wrong

### ISSUE THREAD

**Issue by mtlewis71** [microsoft/vscode#124444]
I have an image clearly placed in an image folder. I have verified the url location in several places and VSCode reads an additional file location that doesn't exist. This section between /css resume/ and /images/ doesn't exist. I can't figure out where it came from.

[Follow link](file:///c:/Users/Owner/OneDrive/Coding/GitHub Repos/mtlewis71.github.io/css resume/css/images/writing.jpg) (ctrl + click)

![2021-05-23](https://user-images.githubusercontent.com/45251201/119247834-e6e2b500-bb5a-11eb-96d9-7ea74199ae96.png)
![2021-05-23 (1)](https://user-images.githubusercontent.com/45251201/119247850-11cd0900-bb5b-11eb-9276-a0d8f779a659.png)

**Comment by aeschli** [comment]
I believe this is doing the right thing. The URL is relative and is resolved against the location of the stylesheet.

https://stackoverflow.com/questions/940451/using-relative-url-in-css-file-what-location-is-it-relative-to.

Please speak up if I misunderstood the issue.

**Comment by mtlewis71** [comment]
No, it's not working correctly. I have other images in the same format without issue. The link is incorrect. I do not have a subfolder named /images/css. The image is only in the /images/ folder.

**Comment by aeschli** [comment]
Your css file is in `../css/styles.css`. It contains a relative reference to `images/writing.jpg`. So the expected image location is `/css/images/writing.jpg`.

Maybe you have a packager or server that places the files differently at runtime. But from a static css document perspective, `/css/images/writing.jpg` is where the image is expected.
