### ISSUE TITLE
The auto-activation of the environment doesn't work with the new Terminal profiles settings

### ISSUE THREAD

**Issue by FitRiver** [microsoft/vscode#124418]
Does this issue occur when all extensions are disabled?: No - the feature doesn't work without extensions

- VS Code Version: 1.56.2
- OS Version: Ubuntu 21.04 / Windows 10 Pro 20H2

Steps to Reproduce:

1. Configure the workspace settings to auto-activate the environment using the new syntax (introduced in VS Code 1.56):

https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles

Linux:

    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "args": [
                "/path/to/activate.sh",
            ],
        },
    },

Windows:

    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "args": [
                "-noexit",
                "-command",
                "\"& {cd $env:VSCODE_CWD; . C:/.../Scripts/Activate.ps1}\"",
            ]
        }
    },

2. Open VS Code with the project that has these workspace settings

3. Activation script is not executed. The environment is not active.

Additional information:

This configuration has been working without any issues for a long time in previous versions of VS Code:

Linux:

    "terminal.integrated.shellArgs.linux": [
        "/path/to/activate.sh",
    ],

Windows:

    "terminal.integrated.shellArgs.windows": [
        "powershell -noexit -command \"& {cd $env:VSCODE_CWD; . C:/.../Scripts/Activate.ps1}\""
    ],

When using these workspace settings the environment was activated right away.

These settings were deprecated in the latest version: https://code.visualstudio.com/updates/v1_56#_terminal

There are specific scenarios when the new settings work. When a different tab is open after the start of VS Code (e.g. the "OUTPUT" tab) and the tab is switched to the Terminal afterward, the activation script is actually launched and the environment is activated. This doesn't work at the startup of the VS Code.

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/123295#issuecomment-846968485

**Comment by FitRiver** [comment]
@Tyriar Thank you for pointing out the difference. I tried to adjust the settings as you suggested:

    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "args": [
                "powershell -noexit -command \"& {cd $env:VSCODE_CWD; . C:/.../Scripts/Activate.ps1}\""
            ]
        }
    },

Unfortunately, it didn't help. The issue is still the same. The environment is not activated upon VS Code startup.

**Comment by Tyriar** [comment]
What happens? Can you test using the [insiders version](http://code.visualstudio.com/insiders) as well since a lot of profile improvements have happened there in the last few weeks.

**Comment by Tyriar** [comment]
You can also do a trace log to see exactly how the terminal is launched, and compare that to the old behavior https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by FitRiver** [comment]
@Tyriar 

I have performed various tests and I found out that the issue is not in the syntax. I tried the insiders version 1.57.0 and it worked with the deprecated syntax:

    {
        "python.pythonPath": "C:\\Users\\test\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-project-8uLzQQ0M-py3.9\\Scripts\\python.exe",
        "terminal.integrated.shellArgs.windows": [
            "powershell -noexit -command \"& {cd $env:VSCODE_CWD; . C:/Users/test/AppData/Local/pypoetry/Cache/virtualenvs/test-project-8uLzQQ0M-py3.9/Scripts/Activate.ps1}\""
        ],
    }

In the version 1.56.2, the auto-start of the environment is blocked for some reason.

I captured the logs and also recorded the screen to demonstrate the issue:

https://github.com/FitRiver/vscode-issue-124418

Let me know if I should perform any other tests or if the issue is already solved in future versions.

**Comment by Tyriar** [comment]
For Python the extension handles environment activation for you, is there any reason you're not using that?

Am I understanding the insiders mp4 that it's fixed there?

**Comment by FitRiver** [comment]
> For Python the extension handles environment activation for you, is there any reason you're not using that?

AFAIK the Python Extension activates the environment only when using the Run commands. It's inactive upon startup. For example, if I would like to install some dependency in the terminal or run some other command-line scripts I would first need to launch the app to activate the environment.

> Am I understanding the insiders mp4 that it's fixed there?

It only works with the deprecated syntax. I couldn't make it work with the new syntax.

**Comment by Tyriar** [comment]
@TylerLeonhardt trying to reproduce this, it seems to be working on my end but the args might be the wrong format:

![image](https://user-images.githubusercontent.com/2193314/121032244-f4558d00-c75f-11eb-9cb6-300a96d331e9.png)

Any ideas what the issue is with the command?

```json
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
        "source": "PowerShell",
        "args": [
            "powershell -noexit -command \"& D:/GitHub/microsoft/vscode/test.ps1\""
        ]
    }
  },
```

**Comment by TylerLeonhardt** [comment]
@Tyriar my guess is that this is a quoting issue. From your json, you're running PowerShell inside of PowerShell which is odd to me.

**Comment by Tyriar** [comment]
That works for me:

```
    "PowerShell": {
      "source": "PowerShell",
      "args": [
          "-command",
          "powershell -noexit -command \"& D:/GitHub/microsoft/vscode/test.ps1\""
      ]
    }
```

![image](https://user-images.githubusercontent.com/2193314/122388250-8d389500-cf24-11eb-915e-da9e19952dad.png)

Can't reproduce the issue unfortunately, probably just needs some tweaking of the args.

**Comment by FitRiver** [comment]
> That works for me:
> 
> ```
>     "PowerShell": {
>       "source": "PowerShell",
>       "args": [
>           "-command",
>           "powershell -noexit -command \"& D:/GitHub/microsoft/vscode/test.ps1\""
>       ]
>     }
> ```

Thank you for your suggestion. This syntax works for me as well.
