### ISSUE TITLE
Native Notebooks - Gutter indicator for command mode thin/hard to see

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124432]
The banner indicating command mode is thin and a bit hard to see and has a white gap between the blue lines. Could it possibly be filled to solid blue? 

![image](https://user-images.githubusercontent.com/19276747/119238464-4313ed80-baf7-11eb-82b1-9e39d7e03325.png)

Even harder to see if the side panel is closed

![image](https://user-images.githubusercontent.com/19276747/119238504-7a829a00-baf7-11eb-968b-55c949c2a9dc.png)

**Comment by misolori** [comment]
@rebornix maybe another configuration addition could be focus border width?

**Comment by rebornix** [comment]
@misolori we can probably try that.

**Comment by rebornix** [comment]
Fixed.
