### ISSUE TITLE
Access the Activation Events of Extension through VSCode Extension API

### ISSUE THREAD

**Issue by YaduAhuja** [microsoft/vscode#124476]
I want that activation event should also be available in VSCode Extension API. This feature will help the extension developers to provide more control to the user whether the extension runs or not.

I am currently working on a feature in the code-runner extension which will give the user to change whether to run the extension for specific files or not but I am not able to implement it as it will require me to change the activation events through extension settings and I read the documentation and still not got any help.

If there is this kind of feature present in VSCode Extension API then please guide me. If it is not present in the API then kindly add it as it will be a great help.

**Comment by alexdima** [comment]
For missing activation events, our current recommended pattern is to create a very small main `extension.js`. This can activate eagerly, like on `*`. The `extension.js` could consist of a simple piece of code that uses vscode API and finds out when the full extension needs to be loaded.

**Comment by YaduAhuja** [comment]
Could you please explain more about that pattern or give me a link to a repository where this pattern is implemented.

**Comment by alexdima** [comment]
@YaduAhuja Here is an example:
* `package.json`:
```json
{
    "name": "test",
    "author": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["*"],
    "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    // use vscode API to determine conditions when `loadEntireExtension` should be called
};

let loaded = false;
function loadEntireExtension() {
    if (loaded) {
        return;
    }
    loaded = true;
    require('./complete');
}
```

**Comment by YaduAhuja** [comment]
Thanks for the help
