### ISSUE TITLE
Markdown preview doesn't interact at all with editor

### ISSUE THREAD

**Issue by nic-hartley** [microsoft/vscode#124433]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Arch (up to date)

Steps to Reproduce:

0. Confirm the following settings match:

    ```
    "markdown.preview.scrollPreviewWithEditor": true,
    "markdown.preview.scrollEditorWithPreview": true,
    "markdown.preview.doubleClickToSwitchToEditor": true
    ```

1. Open any Markdown file long enough to be scrolled in your window
2. Open the preview through any means
3. Scroll in either the preview or the editor; notice the other does not update
4. Double click on any element in the preview; notice the cursor does not update

When closing and restarting VS Code, the preview breaks entirely:

![Picture showing the "Preview README.md" tab, where the only contents of the tab are "An error occurred while loading view: markdown.preview](https://user-images.githubusercontent.com/4331760/119239047-4c5f8300-bb14-11eb-8985-4d4d4d128961.png)

Closing and reopening makes the preview display a preview again, but the broken behavior can still be reproduced.

**Comment by nic-hartley** [comment]
Well, it's good to see the bot didn't find anything I didn't. I think it's self-explanatory why this issue is different.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nic-hartley** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

It doesn't, but I'm not sure how that helps me get it working in non-Insiders? Unless the answer is to just wait for the change to eventually be released.

**Comment by mjbvz** [comment]
Insiders always track the next stable release of VS Code. So the current insiders will become the June VS Code release

**Comment by nic-hartley** [comment]
Oh, gotcha. Thanks!
