### ISSUE TITLE
why ?? i can t installe  extension from vs code .. always i installle from vsix , how can i make the internet work in vs

### ISSUE THREAD

**Issue by OumaimaYum** [microsoft/vscode#124456]
![Capture](https://user-images.githubusercontent.com/60439272/119259763-aa00d780-bbc7-11eb-9045-531b386a31b1.PNG)

**Comment by OumaimaYum** [comment]
ok thanks

**Comment by sandy081** [comment]
@OumaimaYum May I know if you are still seeing this issue. If so, please provide us following information:

- Open developer tools - `F1 > Developer: Toggle Developer Tools`
- Retry the operation
- See if there are any errors in the console and share it with us
