### ISSUE TITLE
Markdown scroll sync not work

### ISSUE THREAD

**Issue by kv-gits** [microsoft/vscode#124489]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
Version: 1.56.2
- OS Version:
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open folder with md files
2. Open md file
3. Open preview
4. Scroll md file
5. Preview not scrolling
6. Settings for syncing are enabled

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by kv-gits** [comment]
> Does this reproduce in the latest VS Code insiders build with all extensions disabled?

Works fine on this version
