### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by aiman-mumtaz** [microsoft/vscode#124466]
I tried to install the prettier extension Prettier and it fails. When I try to install it manually from the vsix, this error pops up
`Corrupt ZIP: end of central directory record signature not found`
 I can install and update some of the other extensions. I recently noticed that updatating the Python extension throws the same error. I don't know what is the complete list of extensions that causes this but there are not all of them

**Comment by sandy081** [comment]
You are seeing this error when installing the VSIX? If so it seems VSIX is not complete or valid. Please check the VSIX.
