### ISSUE TITLE
Unable to change Extension  settings 

### ISSUE THREAD

**Issue by jayeshjs007** [microsoft/vscode#124449]
Issue Type: <b>Bug</b>

I installed code runner extension  and wanted to make some ammendments i sextension settings but when every i click on checkbox it shows the error mentioned below . 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.98GB (0.77GB free)|
|Process Argv|C:\\Users\\JAYESH\\OneDrive\\Desktop\\Starting with C --crash-reporter-id 61bb0203-b0fa-4a8a-831e-a8f582f50f0d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.4
cpptools|ms-|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by marckassay** [comment]
@jayeshjs007 What error, exactly?
