### ISSUE TITLE
the text of window need to be copiable

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#124475]
![Captura de tela_2021-05-23_15-23-48](https://user-images.githubusercontent.com/38570195/119273932-3668c580-bbdb-11eb-85f3-643a49730c2f.png)

the text "Could not establish connection to "34.123.124.86": Permission denied (publickey)" need to be copiable.

**Comment by roblourens** [comment]
Native OS dialogs are out of our hands, but you can switch to the custom ones with `"window.dialogStyle": "custom"`
