### ISSUE TITLE
'Backslash' \ does not work in Windows Integrated Terminal

### ISSUE THREAD

**Issue by karlti** [Microsoft/vscode#12444]
- VSCode Version: Code - Insiders 1.6.0-insider (25b370a3ebe800ac1fedc551a47b7689aa2a5c5b, 2016-09-22T06:10:29.536Z)
- OS Version: Windows_NT ia32 10.0.14926
German Keyboard/US English Keyboard

Steps to Reproduce:

1. Open an integrated terminal window
2. Type '\' - a system sounds is played, Backslash character is not displayed

**Comment by chrmarti** [comment]
Which shell are you using, cmd.exe?
Did this work previously?

**Comment by karlti** [comment]
I use the default windows terminal option cmd.exe. I cannot say if it ever worked.
Today, after having updated my insider build, Backslash works, strange....
( Insiders 1.6.0-insider (d81ee41c51cae93a5cac967e42a28660a3a7e005, 2016-09-23T06:10:40.972Z) )

Actually I would like to use VSCode as my Haskell IDE....
But when starting the Haskell Interactive ghci via "stack ghci", it does not accept Backslashes. 
So no Lambda can be defined interactively.....

starting "stack ghci" in cmd directly, lets my input backslashes.
