### ISSUE TITLE
Incorrect Type, expected array with terminal

### ISSUE THREAD

**Issue by CoffeeCecil** [microsoft/vscode#124474]
Issue Type: <b>Bug</b>

At any time go into settings, edit user settings in settings.json.

Write the following:
"terminal.integrated.profiles.windows": {
 //automatically generated code here, remove comma below if necessary
        ,
        "DevPowerShell64": {
            "path": "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": "-noe -c &{Import-Module \"\"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"\"\"; Enter-VsDevShell efd669b9}",
            //
        }
    }
}

What this does:

Uses the incorrect type of string, creating a warning, but that isn't the cool part. The cool part is that you can spawn a developer powershell with this code, if you have visual studio community edition installed. In theory, this should work for any visual studio edition.

Why this is cool: It summons msbuild ect. into your integrated terminal, you simply have to redirect the terminal to the directory you want to use it in. I used this to build a cmake project. Less windows, more clean.

Why this isn't cool: Presumably at some point someone could patch out taking literal strings like this for any reason.

Why don't I just use 'args' as intended, with an array to get this behavior: The array of arguments ("args") are supplied as a string literal to powershell, presumably after some work is done on the array to make them a single string. For some reason, this causes -c to be understood as some kind of program.

It also raises the question of whether code would pass backtick wrapped text to every terminal it was using... I imagine that'd cause some kind of bug somewhere eventually.

Workarounds if patched so it forces the use of an array: make it clear why the patch occurred somewhere and a solution could be. A simple workaround is just to run an external terminal started in developer mode of course!

What might be cool: If there was an extension, addon, or set of instructions to put the VS Developer command prompt into the integrated terminal by default if you had it. Maybe just a button you could click somewhere that pasted the right command into integrated terminals? This is primarily a bug because it's clearly not taking the right type, unfortunately.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment]
Array is also supported and it is the main way of doing args. String is allowed on Windows because some sets of arguments cannot be expressed with the standard escaping mechanism.

Not totally understanding the not cool part, opening developer consoles seems fine. We allow whatever the user wants to configure here to give power, while protecting them by preventing its usage in workspace settings without an opt in.
