### ISSUE TITLE
All Data lost when renaming open Jupiter notebook

### ISSUE THREAD

**Issue by rishisaikia** [microsoft/vscode#124454]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Mac OS Big Sur 11.3.1

Steps to Reproduce:

1. Create any Jupiter Notebook
2. Rename while open

**Comment by rebornix** [comment]
@rishisaikia sorry for responding late, are you still able to reproduce this issue?
