### ISSUE TITLE
Emmet snippets should also tab stop at the end of the snippet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1244]
When using emmet, it would be nice to also get a snippet tab stop at the end of the snippet, so I can continue writing more emmet commands.

For example, the snippet `.foo` has the following tab stops:

```
<div className="foo">[HERE]</div>
```

It would be helpful to have one at the end too:

```
<div className="foo">[HERE]</div>[HERE]
```

**Comment by egamma** [comment]
The tab stops are defined by the emmet snippets and not by the emmet integration. So this would be a good enhancement request for emmet and its snippets.

Closing.
