### ISSUE TITLE
New keyboard shortcut settings are more of a hindrance than a help.

### ISSUE THREAD

**Issue by marcio1002** [microsoft/vscode#124437]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.56
- OS Version: Ubuntu 20.04

These new shortcut settings are being useless, they are more of a hindrance than a help 😠. Why change what works well? The shortcut settings from previous versions were very useful. This version is all messy.

**Comment by roblourens** [comment]
> new shortcut settings are being useless

Can you explain more?

**Comment by marcio1002** [comment]
> Can you explain more? Which keyboard shortcuts?

Most of the shortcuts, mainly the selection with the mouse. The changes to the shortcuts did not fit well in the functions and were not quite intuitive in terms of facilitating development.
But I updated it and it looks like it was resolved, thank you very much 🙂🙂.

**Comment by roblourens** [comment]
I'm not sure which changes you are referring to, but it sounds like it's all good now
