### ISSUE TITLE
[JS/TS] Inconsistent highlighting when Ctrl + hovering on functions

### ISSUE THREAD

**Issue by ImRodry** [microsoft/vscode#124450]
Issue Type: <b>Bug</b>

When you hold ctrl and hover over a function, it gives you a preview of the first few lines of that said function, however, if you have constants in that part of the code, they become light blue when they're not followed by the word "const", instead of the usual darker blue. This is also the case with other special highlightings such as using constructors on a class.

Example:
![image](https://user-images.githubusercontent.com/38259440/119254698-bb3dea00-bbaf-11eb-84a3-3d758c167006.png)
Expexted highlighting:
![image](https://user-images.githubusercontent.com/38259440/119254725-e6283e00-bbaf-11eb-937b-e3e8d5796afb.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.89GB (8.55GB free)|
|Process Argv|D:\\Users\\rodri\\Documents\\GitHub\\hypixel-translators-bot --crash-reporter-id 1aa51578-c79e-468f-b062-c24334e21918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-lombok|Gab|1.0.1
vscode-graphql|Gra|0.3.16
discord-vscode|icr|5.6.3
vscode-env|Iro|0.1.0
csharp|ms-|1.23.11
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
vscode-typescript-next|ms-|4.4.20210522
vsliveshare|ms-|1.0.4272
vsliveshare-pack|ms-|0.4.0
gradle-language|nac|0.2.3
vetur|oct|0.33.1
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
minecraft-lang-colorizer|zz5|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by aeschli** [comment]
The color differences you are seeing are coming from the semantic highlighting.
The hover only does syntax highlighting, while the editor also does semantic highlighting.

That's expected. There are no plans to bring semantic highlighting also to the hover.
