### ISSUE TITLE
 Error: Can not add index to parent of type number

### ISSUE THREAD

**Issue by kushagra2901** [microsoft/vscode#124417]
Whenever i try to make changes in the settings i get this error msg .
[error] Error: Can not add index to parent of type number
    at P (file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:2080)

**Comment by kushagra2901** [comment]
no its a different error here..

**Comment by roblourens** [comment]
Can you tell me which setting you are editing, and what the contents of your settings.json currently are? Do you see any errors in your settings.json file?

**Comment by kushagra2901** [comment]
The following are the contents of setting.json file but none of them is working.
{
    "folders": [],
    "settings": {},
    "editor.formatOnSave": true,
}
when i try to change any settings it shows that msg be it theme ,font size.
also i am not able to sync my account 

the following are the errors on trying to sync 
[2021-05-26 07:33:45.170] [settingssync] [error] Error: Can not add index to parent of type number
    at P (file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:14:2080)
    at Object.k [as edit] (file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:27866)
    at y (file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:101756)
    at D.getMergeResult (file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:110235)
    at async file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:56717
    at async file:///C:/Users/kushagra sharma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:58224

**Comment by roblourens** [comment]
That looks like it might be a code-workspace file? Or if it is your settings file, it should not have the folders/settings nodes, can you check whether removing those fixes it?

What is the path to that file?

**Comment by kushagra2901** [comment]
the path to that file is .vscode>settings.json and on removing that folder and settings nothing changed

**Comment by roblourens** [comment]
Settings sync is working on your user settings, not your workspace settings. So I think you are looking at the wrong file. You can open the settings editor on "User", then click the "Open Settings (JSON)" button in the top right corner

**Comment by kushagra2901** [comment]
in the user settings.json there is only 15 written there  nothing else.

**Comment by kushagra2901** [comment]
i can even use prettier on auto save pls help

**Comment by roblourens** [comment]
Not sure what you mean

> 
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTA1MDIxNA==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTA1MDIxNA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0OTA1MDIxNA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-849050214" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists" data-body-version="0fcda1f63a24e97cb00968def98252b4c1a28d051024ebbdd81b1286d2220043" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">in the user settings.json there is only 15 written there nothing else.</task-lists></div><form class="js-comment-update" id="issuecomment-849050214-edit-form" action="https://github.com/microsoft/vscode/issue_comments/849050214" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTA1MDUzNw==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0OTA1MDUzNw==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0OTA1MDUzNw==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><br class="Apple-interchange-newline"></div></div>
