### ISSUE TITLE
Can't format CSS anymore

### ISSUE THREAD

**Issue by JPtenBerge** [Microsoft/vscode#12445]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Just now, I tried to format my CSS, but VS Code doesn't seem to support formatting CSS. Formatting JS and HTML works superb, but CSS simply doesn't anymore. It used to work didn't it?

Steps to Reproduce:

1. Open VS Code.
2. Open folder to a random folder.
3. Add a CSS file.
4. Type some random CSS:

```
body{
background:blue;
}
```

When I try formatting it with Alt+Shift+F, no spaces or indenting are added. I then tried to do it through the right mousebutton click menu, but the option 'Format code' is not present. If I create a JavaScript file and type some random JavaScript in there:
```
if(1==1){
console.log('yay');
}
```
Then the format code shortcut works. The menu item 'Format code' on right mouse button click is present as well.

No errors/warnings in the console.

JP

**Comment by chrmarti** [comment]
@aeschli Not sure, was that removed?

**Comment by aeschli** [comment]
CSS formatting was never supported out-of-the box. But there are extensions that provide it.

**Comment by JPtenBerge** [comment]
@aeschli Ah, ok. Would it be a nice feature to have out-of-the-box?
