### ISSUE TITLE
visual studio code getting freezed

### ISSUE THREAD

**Issue by devanshsadhotra** [Microsoft/vscode#12440]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.dowble click on VS code icon on desktop to open it 
2.after 2-4 seconds it freezes.

**Comment by chrmarti** [comment]
Could you:
- Run and paste here: code --list-extensions
- Try starting with: code --disable-extensions

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
