### ISSUE TITLE
Support for `DOMRectList` iteration typings

### ISSUE THREAD

**Issue by danBamikiya** [microsoft/vscode#124479]
VSCode doesn't support DOMRectList iteration in typings. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) the return of `getClientRects` is a "collection" of `DOMRect` objects. I can iterate through it but when I switched to typescript VSCode was giving this error:
![image](https://user-images.githubusercontent.com/58262528/119281539-fda60c00-bc2d-11eb-807b-373128e1f6fd.png)

**Comment by nrayburn-tech** [comment]
The types are available in typescript/vscode.  Your tsconfig probably just needs some modifications to work as you expect it to.

What is your typescript version and `tsconfig.json` settings?

If your `compilerOptions.target` is set to es5, then you need to add `DOM`, and `DOM.Iterable` to your `compilerOptions.lib`.
If your `compilerOpions.target` is es2016 or newer, then this should work without any changes from the default typescript config.

**Comment by danBamikiya** [comment]
Hi @nrayburn-tech thanks for your help! It worked by setting `compilerOptions.target` to `es2015` and adding `DOM` and `DOM.Iterable` to `compilerOptions.lib`
