### ISSUE TITLE
Be more resilient when one of the last opened folders is on a unavailable network share

### ISSUE THREAD

**Issue by aisbergde** [microsoft/vscode#124497]
Issue Type: <b>Bug</b>

I spent several hours to get VSC to open again. restarting windows, uninstalling, and reinstalling VSC, nothing helped. Finally, I found that I need to rename the `%AppData%\Code\storage.json` to disable it. And I think the reason for the issue was an entry to a currently not existing folder in the section

```
        "openedWindows": [
```

a folder like

```
                "folder": "file://192.168.178.22/config",
```

It should be possible to restart VSC also in the case if a folder is not available. Or there should be a warning like "trying to open the folder, can't open. Do you want to skip?"

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (18.90GB free)|
|Process Argv|--crash-reporter-id 6108c108-7f45-4866-9ad0-d4e6ebe004a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
asciidoctor-vscode|asc|2.8.9
markdown-image-size|bie|0.0.4
markdown-yaml-preamble|bie|0.0.4
gotemplate|cas|0.4.0
excel-to-markdown-table|csh|1.2.2
vscode-markdownlint|Dav|0.41.0
languagetool-linter|dav|0.18.0
githistory|don|0.6.16
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
graphviz-preview|EFa|1.5.0
vscode-front-matter|eli|1.16.0
prettier-vscode|esb|6.4.0
vscode-pull-request-github|Git|0.26.0
go|gol|0.25.0
plantuml|jeb|2.14.5
vscode-graphviz|joa|0.0.6
vscode-insertdatestring|jsy|2.3.0
favorites|kdc|2.4.5
vscode-gutter-preview|kis|0.27.1
vscode-markdown-notes|kor|0.0.24
vscode-dbml|mat|0.3.5
rainbow-csv|mec|1.8.1
vscode-bicep|ms-|0.3.539
vscode-dotnet-runtime|ms-|1.1.0
mssql|ms-|1.10.1
sqlops-debug|ms-|1.3.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
azure-account|ms-|0.9.8
powershell|ms-|2021.2.2
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.3.0
sql-prompt|Red|0.2.5
java|red|0.79.2
vscode-yaml|red|0.19.2
explorer-exclude-vscode-extension|Red|1.2.0
datetime|rid|2.0.3
code-settings-sync|Sha|3.4.3
jstool|sun|1.2006.0
c4-dsl-extension|sys|2.2.3
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
graphviz-interactive-preview|tin|0.0.11
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-svg-previewer|vit|0.7.0
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-nested-tags|vsc|1.7.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
@aisbergde and what happens with such an entry when you try to start VSCode?

**Comment by bpasero** [comment]
I cannot reproduce, when a folder cannot be resolved, we fallback to an empty window.

https://github.com/microsoft/vscode/blob/b3ed595dde705c83648f8b963485fc5a30eea86e/src/vs/platform/windows/electron-main/window.ts#L809-L809

**Comment by aisbergde** [comment]
the issue happens with a Samba share on a Raspberrypi running HomeAssistant if this share is not available, but when it was opened in the last session. Maybe, this is different from other network folders. Maybe VSC is waiting for Windows and Windows is trying to long to connect.
https://www.home-assistant.io/installation/raspberrypi/

I don't program in ts. I don't understand what happens here:

```
configuration.workspace = await this.validateWorkspace(configuration);
```

**Comment by bpasero** [comment]
> Maybe VSC is waiting for Windows and Windows is trying to long to connect.

Yeah possible, we just do a file system call to figure out if the path exists and if that never returns, it will just hang.
