### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by qidong02** [microsoft/vscode#124414]
Issue Type: <b>Bug</b>

界面总是出现一片白色 很花 ，别的应用都没事 就 vsCode 出事

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.32GB free)|
|Process Argv|--crash-reporter-id f164d388-73c3-48f1-88ed-6cb7d719e6dd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.3.1
jsrefactor|cms|2.20.6
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.5.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-exec-node|mir|0.5.4
vscode-docker|ms-|1.12.1
vscode-language-pack-zh-hans|MS-|1.56.2
csharp|ms-|1.23.11
js-atom-grammar|ms-|0.1.14
JavaScriptSnippets|nat|0.2.0
vscode-vue2-snippets|Nic|1.0.0
vetur|oct|0.33.1
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.2.0
code-spell-checker|str|1.10.2
vscode-status-bar-format-toggle|tom|2.0.0
vscode-icons|vsc|11.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
vuter|yoy|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by qidong02** [comment]
![HFY0TMC19DT X1DR4UMFCC3](https://user-images.githubusercontent.com/56099665/119220792-cc8ae600-bb1e-11eb-9cc5-d39671ef45cc.png)
Look at the left

**Comment by qidong02** [comment]
The screen is always white, other application are fine

**Comment by roblourens** [comment]
Does starting with the `--disable-gpu` flag help?

**Comment by qidong02** [comment]
> Does starting with the `--disable-gpu` flag help?

This works, thank you
