### ISSUE TITLE
Editor windows will not add new line

### ISSUE THREAD

**Issue by ehackett00** [microsoft/vscode#124442]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

1. Launch VS Code.
2. Open a script or code file.
3. Try to create a new line.
==> New line can not be created.
5. open a new file from the file menu.
6. Select a language from the drop down menu.
==> I selected Shell script
==> not only can I not create a new line; I can not type #!/bin/bash

Help!!!

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.31GB free)|
|Process Argv|--crash-reporter-id dd9896a9-49e2-4a58-b174-1bb0739bccfa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
cocos-debug|Chu|0.0.1
zsh-completion-script|dua|1.0.0
vscode-npm-script|eg2|0.3.21
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.4
cloudcode|goo|1.11.1
cocotools|jas|0.0.7
file-downloader|min|1.0.11
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.3
remote-containers|ms-|0.177.2
cpptools|ms-|1.3.1
debugger-for-chrome|msj|4.12.12
vscode-janus-debug|otr|1.3.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
zsh-debug|rog|0.1.3
vim|vsc|1.20.3
quokka-vscode|Wal|1.0.368

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
Please tell me exactly what you're doing when you try to "create a new line"

**Comment by ehackett00** [comment]
Hello,

It is just like I said.

I open an existing file or create a new file.  Then I try to type something or just hit return on my Mac.  I get no new line or no text.  

The only new thing I added was to cut off the Kubernets extension because I was getting errors.  I never used it anyway.  Also I added Oh My zsh as my default shell in iTerm.
VS Code is  is unusable.

I am not very experienced..  I’m using Code Runner to write scripts.

Ed

**Comment by ehackett00** [comment]
Hello,

I finally found out what was going on.

I installed Vin, a emulation editor on VS Code.  It was waiting for me to turn on insert mode.  I once tried to use the vi editor back in the 90’s.  It gave me problems then too.
Code editor is not editing.

Thanks,

Ed Hackett

PS  How do I add this to bug log?

**Comment by roblourens** [comment]
Ok, glad you figured it out, I don't understand what you are asking for now


> Code editor is not editing.
> PS  How do I add this to bug log?

**Comment by ehackett00** [comment]
Sorry,

This problem killed VS Code for me.  The problem was so bad I had to revert to another code editor.  I just thought this knowledge should be understood by others.  I was asking how to put the solution in with the bug report.  That way others would not fall into the same pit fall!

I am new to all of this Git stuff and I probably could use a tutorial.  For example, if a bug is closed, canons someone still add a solution?

Sincerely,

Ed

**Comment by ehackett00** [comment]
This problem was solved by uninstalling the Vim extension!  Please close.

**Comment by ehackett00** [comment]
Solved by uninstalling Vim!
