### ISSUE TITLE
Visual Studio crashing 5 times!

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#124453]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Hi vs code team,
ever since I last updated vs code it has crashed 5 times in 3 days and just 5 mins ago the moment I opened vscode my pc hanged and crashed

**Comment by hasban121138** [comment]
me too 
mine
version: 1.56.2 (user setup)
commit:054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
