### ISSUE TITLE
Untrusted file prompt appears with trust disabled when opening file from command line

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#124470]
Issue Type: <b>Bug</b>

1. Set “security.workspace.trust.enabled” to False.
2. Open a file using `code-insiders`.

VS Code version: Code - Insiders 1.57.0-insider (4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5, 2021-05-21T05:13:19.775Z)
OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2975)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 2|
|Memory (System)|7.64GB (0.43GB free)|
|Process Argv|--unity-launch --crash-reporter-id dbbd25fe-3f4e-426a-9c89-45e060834124|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-fish|bma|1.0.22
vscode-markdownlint|Dav|0.40.4
vscode-deno|den|3.4.0
gitlens|eam|11.4.1
vscode-pull-request-github|Git|0.26.0
haskell|has|1.4.0
discord-vscode|icr|5.6.3
latex-workshop|Jam|8.18.0
language-haskell|jus|3.4.0
hexeditor|ms-|1.6.0
powershell-preview|ms-|2021.5.0
vscode-github-issue-notebooks|ms-|0.0.93
linux-desktop-file|nic|0.0.14
java|red|0.79.2
stardog-rdf-grammars|sta|0.1.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.33.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
There have been multiple issues that were fixed with **2021-05-21** (version used to report the issue), and I can confirm that I am unable to reproduce this issue with the latest Insiders version. I am closing the issue for now, and will reopen if we regress.
