### ISSUE TITLE
Progress bar during uploading a very big file

### ISSUE THREAD

**Issue by JalinWang** [microsoft/vscode#124505]
Claim:  I've tried to search " big file upload " and "progress bar upload" in issues, but found nothing useful. If something is missed, please remind me or close this issue directly.

I think it might be better if there's a progress bar instead of just a simple indicator while uploading big files.

e.g. when uploading a 3.2GB file,  I have no way to know how much it has already transferred and how long it will take:
![image](https://user-images.githubusercontent.com/20621784/119341112-fdf1e600-bcc5-11eb-9fe4-544942441ec0.png)
![image](https://user-images.githubusercontent.com/20621784/119341442-57f2ab80-bcc6-11eb-8214-3ccee7138d47.png)
Progress bar or speed indicator could ease my nervousness if any.

What's more, vscode will alert annoyingly as it is configured to open the uploaded file the moment transfer is finished.  A judgement of file size before opening, i.e. judge whether the file is larger than a certain threshold, can improve user experience.
![image](https://user-images.githubusercontent.com/20621784/119341754-b750bb80-bcc6-11eb-8af1-be498b95a5cc.png)

**Comment by isidorn** [comment]
I agree this could be improved. 
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by JalinWang** [comment]
Got it. Thanks for your quick response :)
