### ISSUE TITLE
vs-code for mac memory bug

### ISSUE THREAD

**Issue by samikot** [microsoft/vscode#124518]
Issue Type: <b>Bug</b>

When I use vs-code for mac to edit a file which is shared by other devices in LAN (the devices' system can be ubuntu or windows or macos or centos), my mac's memory will be run out by vs-code, but this problem never show up in my windows-pc when I also use vs-code for windows to edit the same file on the same device in LAN. So, the bug seems like just bother macos-users. One more thing, the file-size can be very small (1KB).

VS Code version: Code 1.54.1 (Universal) (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (5.69GB free)|
|Process Argv|--crash-reporter-id 46999597-5b9d-4016-b8a9-e33028e3cf1a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.54.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by roblourens** [comment]
You have a slightly old version of vscode, please update fully and try again
