### ISSUE TITLE
I don't get autocompletion with remote packages

### ISSUE THREAD

**Issue by LeGeRyChEeSe** [microsoft/vscode#124554]
Hello, like the title said i can't access to all functions of a python file when i'm using ssh connection to my Raspberry Pi.
Here is the ssh connection:
![image](https://user-images.githubusercontent.com/64637517/119442963-0d564b00-bd29-11eb-8fa8-56a3b3564d92.png)

And Here is the same file located locally:
![image](https://user-images.githubusercontent.com/64637517/119442933-ff082f00-bd28-11eb-8d17-df38481c162a.png)

How can i have this with files located on remote server ?

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
