### ISSUE TITLE
Extensions doesn't work in virtual workspace

### ISSUE THREAD

**Issue by j0k4rX** [microsoft/vscode#124590]
- **Extensions like C/C++, GitLens doesn't work in virtual workspace**

When I open a remote repository from github, it shows
`This extension has been disabled because it doesn't support virtual workspace`

I tried enabling the extensions from ellipsis but it still doesn't work
the extensions are dimmed in color

![Screenshot 2021-05-25 170024](https://user-images.githubusercontent.com/71499522/119524274-4fba6f00-bd9f-11eb-82f2-c10e103fc85c.jpg)

- VS Code Version: 1.57.0-insider
- OS Version: windows 10 pro

Steps to Reproduce:
1. fix support of top extensions for virtual workspace
2. fix the bug which prevents extensions to work smoothly in virtual workspace

**Comment by gjsjohnmurray** [comment]
I think these extensions probably specify that they don't work in virtual workspaces, so VS Code is right to disable them. In which case, please raise the issue with the extension authors, asking them to add support for virtual workspaces.
