### ISSUE TITLE
No file system provider found for resource 'vscode-notebook-cell:/

### ISSUE THREAD

**Issue by AnWeber** [microsoft/vscode#124530]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insider
- OS Version: Win10

Steps to Reproduce:

1. open file in Notebook Editor 
![image](https://user-images.githubusercontent.com/13434739/119404147-b24c3600-bcdf-11eb-9675-b3ee900e6751.png)
2. load relative file (`./intellij.js`) and try to access the stats of file

```
try {
      const uri = cell.document.uri;
      this.log.info(uri);
      const joinedUri = vscode.Uri.joinPath(uri, '../intellij.js');
      this.log.info(joinedUri);
      const stat = await vscode.workspace.fs.stat(joinedUri);
      this.log.info(stat); // not reached
    } catch (err) {
      this.log.error(err);
    }
```
Log Output
```
INFO: {
  "$mid": 1,
  "fsPath": "c:\\Users\\weber\\Desktop\\httpyac\\httpyac\\examples\\intellij\\intellij.http",
  "_sep": 1,
  "external": "vscode-notebook-cell:/c%3A/Users/weber/Desktop/httpyac/httpyac/examples/intellij/intellij.http#ch0000005",
  "path": "/c:/Users/weber/Desktop/httpyac/httpyac/examples/intellij/intellij.http",
  "scheme": "vscode-notebook-cell",
  "fragment": "ch0000005"
}
INFO: {
  "$mid": 1,
  "path": "/c:/Users/weber/Desktop/httpyac/httpyac/examples/intellij/intellij.js",
  "scheme": "vscode-notebook-cell",
  "fragment": "ch0000005"
}
ERROR: Unavailable (FileSystemError) - No file system provider found for resource 'vscode-notebook-cell:/c%3A/Users/weber/Desktop/httpyac/httpyac/examples/intellij/intellij.js#ch0000005'
Unavailable (FileSystemError): No file system provider found for resource 'vscode-notebook-cell:/c%3A/Users/weber/Desktop/httpyac/httpyac/examples/intellij/intellij.js#ch0000005'
	at _handleError (c:\Users\weber\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:157130)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async HttpNotebookKernel.provideCellStatusBarItems (webpack-internal:///./src/extension/notebook/httpNotebookKernel.ts:41:26)
	at async u.$provideNotebookCellStatusBarItems (c:\Users\weber\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:207099)
```

How to load the relative file correctly?

**Comment by jrieken** [comment]
The `uri` of cell document is "virtual" and doesn't exist on disk - its scheme is always `vscode-notebook-cell`. For fs-gymnastics you need to use the `uri` of the notebook (not cell)

**Comment by AnWeber** [comment]
Too bad but thanks for the help

**Comment by AnWeber** [comment]
@jrieken Just one more little question. Couldn't this behavior cause problems for CodeLens providers for languages in the cell that rely on file access. These don't necessarily need to know about NotebookEditor and vscode-notebook-cell scheme. 

In my case I created the extension [vscode-httpyac)(https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) which provides a CodeLens extension for *.http files (Intellij Http Client). With this the referencing of relative files is possible (import request body). A third person could have created the notebook editor now and caused the error in the first place. 

The case is only theoretical but I just wanted to point it out.

**Comment by jrieken** [comment]
> Couldn't this behavior cause problems for CodeLens providers for languages in the cell that rely on file access. These don't necessarily need to know about NotebookEditor and vscode-notebook-cell scheme.


Yes - extensions that assume that documents are always stored on disk (e.g. the `file` scheme) will have problems. However, that problem isn't new because "virtual documents" exists since the beginning. Extensions that rely on fs-access need to express that via `vscode.DocumentFilter.scheme`

**Comment by AnWeber** [comment]
Thank you for the explanation.
