### ISSUE TITLE
Can you please add percentage of zooming?

### ISSUE THREAD

**Issue by alexander-lamdan** [microsoft/vscode#124563]
When I start to zoom the code, after that I forget what is the default zoom I was used.
It will be really good for users who zoom out and zoom in, but wan't to know in what zoom I now.

Like 10%, 20%, 50%, 100%, 150% in bottom bar will be good. Thank you

**Comment by sbatten** [comment]
actually i see there is already such an extension https://marketplace.visualstudio.com/items?itemName=wraith13.zoombar-vscode
