### ISSUE TITLE
can't run html

### ISSUE THREAD

**Issue by Mouli14-git** [microsoft/vscode#124525]
Issue Type: <b>Performance Issue</b>

i can't run a html file in open browser tho i installed open in browser.

Extension version: 2.0.0
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 4.15.0-30deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 1632)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.74GB (0.13GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 11028	code main
    0	    11	 11041	   zygote
    0	   192	 11100	     window (Extension: open in browser - Downloads - Visual Studio Code)
    0	     0	 11148	       /bin/bash
    0	    57	 11152	       extensionHost
    0	    57	 11220	         /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=11152
    0	    54	 11685	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=11152
    0	    19	 11168	       watcherService
    0	    46	 11167	     shared-process
    0	   111	 15043	     window (undefined)
    1	    92	 15525	     window (Issue Reporter)
    0	    50	 11084	   gpu-process
    0	     0	 15593	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 15594	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: open in browser - Downloads - Visual Studio Code)
|    Folder (Downloads): 58 files
|      File types: pdf(39) c(3) deb(2) html(2) m(2) out(1) exe(1) sh(1) cpp(1)
|                  png(1)
|      Conf files:;
```

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Please check that you have proper setup according to extension requirements (which look very limited, and no mention of linux support), have proper file selected and it's saved. If you still have issues - please report them in extension repository.
Looks like there are already few similar issues https://github.com/SudoKillMe/vscode-extensions-open-in-browser/issues

> VS Code version: Code 1.33.0 (0dd516d, 2019-04-04T15:08:57.775Z)

Another problem might be because you use old version - current one is 1.56
