### ISSUE TITLE
Screen cheese: redundant animation of getting started steps

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#124531]
Issue Type: <b>Bug</b>

After reloading the window, the steps expand/collapse multiple times

https://user-images.githubusercontent.com/876920/119410035-0a157d80-bc9d-11eb-9152-39d0b506c73d.mov

VS Code version: Code - Insiders 1.57.0-insider (Universal) (5319757634f77a050b49c10162939bfe60970c29, 2021-05-24T05:12:43.831Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (1.36GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andreamah** [comment]
I'm still getting a bit of jittering upon reload; not sure if it's expected?

[![Image from Gyazo](https://i.gyazo.com/ad9697efa2d6631d6bf3a18e364b4933.gif)](https://gyazo.com/ad9697efa2d6631d6bf3a18e364b4933)

**Comment by JacksonKearl** [comment]
Good catch, thanks.

**Comment by rzhao271** [comment]
Another case

![recording (29)](https://user-images.githubusercontent.com/7199958/120847259-15cc3400-c528-11eb-9aa2-5533b52ba913.gif)

**Comment by JacksonKearl** [comment]
I am no longer able to reproduce.
