### ISSUE TITLE
asExternalUri throws error 'Could not resolve external URI: http://localhost:11111/'

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#124507]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-insider (user setup)
Commit: 5319757634f77a050b49c10162939bfe60970c29
Date: 2021-05-24T05:14:19.500Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19043

Our extension is configured to work in trusted and untrusted workspaces. When running with VSCode version 1.56.0 the code
```
        const kernelUri = vscode.Uri.parse(`http://localhost:${transport.httpPort}`);

        try {

            let externalUri = await vscode.env.asExternalUri(kernelUri);
...
        }
        catch (e) {
            vscode.window.showErrorMessage(e.message);
        }
```
Works without any problem. This fails with 1.57.0.Insider.
The stack trace is 
```
'Error: Could not resolve external URI: http://localhost:56631/\n    at d.resolveExternalUri (file:///C:/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:628:21916)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async w.$asExternalUri (file:///C:/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1799:41768)'
```

**Comment by rebornix** [comment]
@joaomoreno can this be related to recent changes on `asExternalUri` https://github.com/microsoft/vscode/commit/a6f7aa5e4c5832c3d788ab9a8146ac69a6e5a77f ?
