### ISSUE TITLE
Kernel not remembered due tot he fact that the kernel ids are no longer the same

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#124535]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Its not easy to repro, but i'll mention the issue.
Assume we have a user who wishes to run Python notebooks and has Python installed but not the Python extension.

Requirement: Display a prompt that blocks users from running cells, until they install the Python extension.

Solution: Add a dummy `Python` kernel (controller) to the list of kernels (kernelId = dummy).
When a user opens a notebook and attempts to run a cell, the dummy controller will handle this cell execute event and display a modal dialog prompting the user to install Python extension & returns (without any changes to notebook).

Next, user installs the Python extension, at this point, when the user runs a cell, the same controller is used. Lets assume some how the Jupyter extension used a real kernel at this point & output is displayed.

Next, user re-loads VS Code.
At this point jupyter extenson sees Python extension and gets all of the kernels, and each kernel will have a unique id such as `python1`, `python2`, etc.
Now the user will have to re-select a kenrel all over again, as the kernel `dummy` that was originally created no longer exists.

Hence the problem now is, the user gets prompted to select a kernel again.

FYI - This is the same solution we're planning on implementing to ensure user has a `Python` kernel in the kernel picker when opening a notebook. As discussed here https://github.com/microsoft/vscode/issues/122860. I.e. users running new notebooks could run into this same problem.

@jrieken @rebornix /cc

**Comment by DonJayamanne** [comment]
Basically using dummy kernels to optimize pre-loads or handle situations such as validation of environment can present a few challenges, such as user being prompted to select a kernel even after they've successfull executed a cell against this same notebook earlier.

**Comment by DonJayamanne** [comment]
FYI - I've tried disposing the kernel, however this doesn't seem to do anytihng.
Would it be possible to remove the kernel from the list and get the user to re-select a kernel once the active kernel has been disposed?

I believe that would resolve one of the issues (first example mentioned). 
Second example I'm referring to is adding a dummy kernel to work around the delay in loading/fetching of kernels.

**Comment by IanMatthewHuff** [comment]
> FYI - I've tried disposing the kernel, however this doesn't seem to do anytihng.

Oh, that's interesting, it stays in the list after dispose? I would have thought that would clean it up.

**Comment by jrieken** [comment]
> Solution: Add a dummy Python kernel (controller) to the list of kernels (kernelId = dummy).

I don't think that's a solution because kernels are remembered by their id. The dummy approach cannot be as simple as having a single dummy kernel with a constant id, instead a "shallow" notebook controller should be created for each existing kernel spec. These shallow controllers should "all wait" in their execute handler for something to happen but the they should not be thought of as throw-away controllers but as "partial controllers"

**Comment by jrieken** [comment]
Closing after discussion - dummy kernels should not come and go but come early and be incrementally completed after that
