### ISSUE TITLE
Rendering issue after awakening on Linux

### ISSUE THREAD

**Issue by EntnyJill** [microsoft/vscode#124586]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Run VS Code.
2. Go to sleep mode.
3. Wake from sleep mode.

Issue disappears If I disable hardware acceleration using 
`"disable-hardware-acceleration": true`
I'm using Unity desktop and Nvidia-340 driver.

![Rendering issues](https://user-images.githubusercontent.com/80616110/119517243-1fafa380-bd80-11eb-8b8b-ef4eb349e44f.png)

**Comment by 1raghavmahajan** [comment]
I am also facing similar issues with my system after waking up from sleep (although with less severity). 
In my case the terminal does not render correctly and restarting the terminal window fixes the issue.

**Comment by deepak1556** [comment]
Closing as GPU issue in the runtime is not actionable, please continue to disable hardware acceleration in VSCode.
