### ISSUE TITLE
VS Code taskbar icons not grouping

### ISSUE THREAD

**Issue by rimjieun** [microsoft/vscode#124537]
1. Pin VS Code to taskbar.
2. Click VS Code on taskbar to open a new window.
3. New window icon is not grouped together with originally pinned icon.

I would like all VS Code windows to be collapsed/grouped together when open.
<img width="391" alt="vscode_taskbar" src="https://user-images.githubusercontent.com/24310357/119417276-73a88280-bcc3-11eb-93af-abcac1a64ca4.PNG">

**Comment by dbaeumer** [comment]
Works for me. 

<img width="261" alt="capture" src="https://user-images.githubusercontent.com/1931590/119454782-31ba2380-bd39-11eb-9f99-04481c82a20c.png">

Any additional steps to reproduce?

**Comment by rimjieun** [comment]
Hi, thank you for responding! Didn't realize this was a thread.

I'm not sure if this will help but here are the details of the version I installed:
<img width="287" alt="vscode_details" src="https://user-images.githubusercontent.com/24310357/119498514-b1dd8a80-bd33-11eb-851b-4aeef7d4d648.PNG">

This is the installer I used:
<img width="308" alt="vscode_installer" src="https://user-images.githubusercontent.com/24310357/119498590-c883e180-bd33-11eb-9f92-7f94ec444a4f.PNG">

These are the options I chose on installation:
<img width="445" alt="vscode_options" src="https://user-images.githubusercontent.com/24310357/119498626-d174b300-bd33-11eb-8aa6-78e6feb8e15c.PNG">

And these are my OS details:
<img width="205" alt="windows_specs" src="https://user-images.githubusercontent.com/24310357/119498666-dc2f4800-bd33-11eb-955e-55f26104ace5.PNG">

Other than that, I just did the steps I mentioned on my first post.

**Comment by spnraju** [comment]
I have the same thing on Windows 10.

Here are the details.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.74`
