### ISSUE TITLE
Invisible underscore (_) in built-in terminal

### ISSUE THREAD

**Issue by kshnyakin** [microsoft/vscode#124580]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Launch terminal inside VS Code
2. Try to write smth string with underscore (_) but it's should be invisible
![image](https://user-images.githubusercontent.com/40332024/119500901-faffff80-bd70-11eb-8359-2c77800016f3.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it still reproducible in Insiders builds?

If reproducible: What font are you using for terminal? Do you have changed `terminal.integrated.fontSize` and/or `window.zoomLevel`?

/assign Tyriar
