### ISSUE TITLE
VSCode hangs on invalid keybindings.json

### ISSUE THREAD

**Issue by steveoh** [Microsoft/vscode#12457]
- VSCode Version: 1.5.2
- OS Version: macOS 10.12

Steps to Reproduce:

1. open keyboard shortcuts
1. clear it out
1. paste in  

 ```json
{ "key": "cmd+d",           "command": "editor.action.addSelectionToNextFindMatch",
                                     "when": "editorFocus" },
 ```
1. receive error about not bing an array. Try to use arrow keys and backspace to fix but they don't work. 
1. save and restart.
1. enjoy brick

referenced [issue](https://github.com/Microsoft/vscode/issues/9566#issuecomment-248884528)

**Comment by ata87** [comment]
Gulyás Attila






On Thu, Sep 22, 2016 at 4:56 PM +0200, "steveoh" <notifications@github.com> wrote:











VSCode Version: 1.5.2
OS Version: macOS 10.12




Steps to Reproduce:


open keyboard shortcuts
clear it out
paste in 


{ "key": "cmd+d",                 "command": "editor.action.addSelectionToNextFindMatch",
                                     "when": "editorFocus" },


receive error about not bing an array. Try to use arrow keys and backspace to fix but they don't work. save and restart.
enjoy brick




referenced issue

**Comment by chrmarti** [comment]
Here is where you can find your keybindings.json, you'll need to fix (or rename) it: https://github.com/Microsoft/vscode/issues/11790#issuecomment-246321827

**Comment by steveoh** [comment]
duplicate of #11868
