### ISSUE TITLE
Text file editor tracker might open dirty untitled before extension can open it

### ISSUE THREAD

**Issue by mbreslav** [microsoft/vscode#124539]
Issue Type: <b>Bug</b>

An extension I am developing uses `showTextDocument` which behaves **differently** when running on a **remote** VM through the Remote - SSH extension (v 0.65.4).

The behavior of the code below when run **locally** is as I expect. For example when the user has a single editor open and clicks a link I observe the results (Untitled-1) being opened in ViewColumn 2 as expected.

![image](https://user-images.githubusercontent.com/55714174/119425286-f3325380-bcbb-11eb-83ff-9e68faf1224b.png)

**However**, when run on a remote VM the behavior observed was: 
![image](https://user-images.githubusercontent.com/55714174/119424595-a00bd100-bcba-11eb-9634-86c2fd3f506e.png)

That is, the results (Untitled-1) showed both in ViewColumn 1 as a **tab** **AND** in ViewColumn 2. The tab in ViewColumn 1 is unexpected!

Reproduce:

Run an extension which uses this code both locally and on a remote through the SSH - remote extension. 

```
const doc: TextDocument = await workspace.openTextDocument({
			'content':formatted_contents,
			'language':'python'});

		const current_view_column = window.activeTextEditor?.viewColumn;
		
		let results_view_column;
		
		if (current_view_column == ViewColumn.One) {
			results_view_column = ViewColumn.Two;
		} else {
			results_view_column = current_view_column;
		} 

		const editor = await window.showTextDocument(doc, results_view_column);
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.15.0-1108-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|Memory (System)|31.59GB (16.22GB free)|
|Process Argv|--crash-reporter-id c98fa9d2-a0e5-4d4f-803e-ad72970695ec|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: abc|
|OS|Linux x64 4.15.0-1108-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (24 x 2596)|
|Memory (System)|220.39GB (202.32GB free)|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mbreslav** [comment]
I was able to reproduce the problem with Insiders (with Remote-SSH 0.65.6):

![image](https://user-images.githubusercontent.com/55714174/119542805-cd04c600-bd44-11eb-916d-930d2e867bad.png)


Version: 1.57.0-insider (user setup)
Commit: 286b643ecd231f66f3f2e67e1456f3c601838b46
Date: 2021-05-25T05:24:28.413Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by bpasero** [comment]
This is partially working as designed, here is what happens:
* an extension creates a untitled document with data
* VSCode tracks all documents with changes that occur and ensures every document has an associated editor the data shows with
* the extension takes a bit of time to open the editor
* VSCode gives a bit of time before starting to open the editor to ensure the data is visible

Normally this is not a problem because the editor group that the editor opens in is the same and not to the side, but in this case, the editor opens to the side so it appears twice.

I think we have been behaving like this for the longest time.

**Comment by mbreslav** [comment]
Would it be accurate for me to say that once `openTextDocument` is triggered, `showTextDocument` needs to execute within a small delay, and if it does not then we see this phenomenon? It also appears that having this extension run on a remote is causing the delay to exceed some threshold. 

Unfortunately in my use case the user may need to open multiple temporary documents which means they will have 2x the number of editors to close, which will be annoying.

Any suggestions for how I could get `showTextDocument` to happen with less delay after `openTextDocument`? Thanks

**Comment by kieferrm** [comment]
I haven't been able to reproduce the issue myself, but based @bpasero 
 comment https://github.com/microsoft/vscode/issues/124539#issuecomment-850288633 it seems that the below could work, i.e. only dirty the document once it's shown. Pls try:


```ts
const doc: vscode.TextDocument = await vscode.workspace.openTextDocument({ 'content': '', 'language':'python'});

const current_view_column = vscode.window.activeTextEditor?.viewColumn;
const results_view_column = current_view_column === vscode.ViewColumn.One ? vscode.ViewColumn.Two : current_view_column; 

const editor = await vscode.window.showTextDocument(doc, results_view_column);
await editor.edit(edit => edit.insert(new vscode.Position(0,0), formatted_contents));
editor.selection= new vscode.Selection(0,0,0,0);
```

**Comment by bpasero** [comment]
I like that approach 👍

**Comment by mbreslav** [comment]
Thanks @kieferrm! Your workaround worked for me.

**Comment by bpasero** [comment]
Then I will go ahead and close as designed.
