### ISSUE TITLE
[Insiders] Cannot change fs provider capabilities dynamically in read-only session for Live Share 

### ISSUE THREAD

**Issue by setaskin** [microsoft/vscode#124524]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0 insider
- OS Version: Windows 10

The bug only repro on VS Code insiders for Live Share, it doesn't repro on VS Code stable. So, I believe it is caused by VS Code fs provider. 

Steps to Reproduce:

1. Install Live Share extension on VS Code insiders
2. Go to Live Share tree view and click on Share with "read-only" permissions
2. From another vs code insiders instance click on join session.
3. Go back to host instance and right click on guest name and select "make read-write"

Expected : Guest should be able to edit the shared file , after they gain read-write access. 

Actual : Guest still cannot edit the file. 

![access level toggle](https://user-images.githubusercontent.com/37163639/119391625-6f5c7500-bc83-11eb-9de9-d6413cbd81e0.gif)

**Comment by setaskin** [comment]
Hi  @jrieken ,  since initially you provided changing  fs provider capabilities dynamically I wanted to tag you :) Please ignore if it is not your area

**Comment by bpasero** [comment]
Maybe my changes...

**Comment by bpasero** [comment]
A regression from https://github.com/microsoft/vscode/issues/73122.
