### ISSUE TITLE
Multiple Save dialogs when pressing Save multiple times

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#12450]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open New File
2.  Press Ctrl + S many times

---
Many windows to save open. It is expected that only one window open, even if I press several times

**Comment by chrmarti** [comment]
Reproduced on Windows 10 by pressing multiple times before the first dialog opens. There is always only one dialog open at a time. When that closes the next opens.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11928
