### ISSUE TITLE
Pending cell edits (possibly) not handled by VS Code when saving

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#124534]
* Open a notebook (assume auto save is turned on)
* Add a new cell (at this point VS Code will trigger cell creation event and then attempt to save).
* Extension author handles the cell creation even and attempts to update cell metadata ta for the newly created cell
* VS Code will save notebook without waiting for pending edit to complete

FYI - I haven't tried this out, however I doubt VS Code is/will be waiting for pending cell edits to complete before performing the save.

Requirements:
* VSCode should wait for pending cell edits to complete prior to saving.

@rebornix @jrieken

**Comment by jrieken** [comment]
> FYI - I haven't tried this out, however I doubt VS Code is/will be waiting for pending cell edits to complete before performing the save.

There is no concept of pending cell edits, e.g all edits are discrete and separate. 

Is this something you would expect from the existing API (e.g is the API misleading) or is this a request for an `onWillSaveNotebookDocument`-event?
