### ISSUE TITLE
Can't cancel terminal action with cmd+c on OS X

### ISSUE THREAD

**Issue by lopugit** [microsoft/vscode#124542]
This used to work just fine, but now it seems when I hit cmd+c to cancel a line in the integrated terminal, nothing happens, but the edit -> copy shortcut is activate, even though I have set this to `when !terminalFocus` ? 

Pressing the actual control+c buttons on the mac keyboard does clear the line, but not cmd+c.

I have made a GIF of the behaviour, I have also made sure that all other cmd+c shortcuts include the `!terminalFocus` where statement.

https://i.gyazo.com/54b693d89e4f291e32384eb77c928a56.mp4

Kindly,
Nikolaj Frey

Version: 1.56.0-insider
Commit: 4e185d8986339717e593be19bc75288905ffbb51
Date: 2021-04-30T23:19:25.345Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
cmd+c always acted like this by default. You can configure it to send ctrl+c if you want by adding this keybinding:

```json
{
	"key": "cmd+c",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u0003" },
	"when": "terminalFocus"
}
```

**Comment by lopugit** [comment]
> cmd+c always acted like this by default. You can configure it to send ctrl+c if you want by adding this keybinding:
> 
> ```json
> {
> 	"key": "cmd+c",
> 	"command": "workbench.action.terminal.sendSequence",
> 	"args": { "text": "\u0003" },
> 	"when": "terminalFocus"
> }
> ```

Cheers yeah you're right lol, same in iTerm 2.

Sorry for wasting your time and thanks for a nice solution!
