### ISSUE TITLE
ExtensionHost took a long time to finish when the autocomplete is triggered.

### ISSUE THREAD

**Issue by deftomat** [microsoft/vscode#124528]
`ExtensionHost` took a long time to finish when the autocomplete is triggered in new TS file.

As you can see in video, when I trigger the autocomplete, `ExtensionHost` and `tsserver` will spin up. In 11. second, `tsserver` CPU usage will drop to 0 but `ExtensionHost` keeps doing its stuff until 20. second.

The strange thing is that all the items in autocomplete list looks like from `tsserver`. So, I'm wondering what has `ExtensionHost` been doing for these 9 seconds. I have all other extensions disabled.

https://user-images.githubusercontent.com/5549148/119401382-b5ddbe00-bcdb-11eb-97f3-e4ec545ebabc.mov

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: macOS Big Sur 11.3.1 x64

Steps to Reproduce:

1. Open VSCode
2. Wait until TS is initialised
3. Create new TS file and request autocomplete

**Comment by mjbvz** [comment]
Hm, I'm guessing this is because the file is part of a large TS project. 

Could you please try collecting the TS Server logs to help us investigate this:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by deftomat** [comment]
Sure, there it is: https://github.com/deftomat/tsserver.log (its private, so please accept the invitation)
