### ISSUE TITLE
modifying "files to include" in search editor does not update scroll position correctly

### ISSUE THREAD

**Issue by zsalzbank** [microsoft/vscode#124541]
Issue Type: <b>Bug</b>

1. Open a search editor tab.
2. Expand the options to display "files to include".
3. Search for something, using the "files to include" option.
4. Note that there are results.
5. Modify "files to include" to be something that will not return results.
6. Note that there are no results displayed.
7. Change "files to include" back to the same value as in step 3.
8. Note that there are still no results displayed, but you can scroll and see the results. I'd expect to be able to see the results without scrolling.

https://user-images.githubusercontent.com/939977/119432529-7c5c8100-bce2-11eb-90f0-6a8705c1bf92.mov

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv|--crash-reporter-id 726080a9-504a-4ce7-82e2-a7fc09b1cb07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-nginx-conf|ahm|0.1.3
reorder-lines-by-length|ara|1.0.2
docs-view|bie|0.0.9
pgformatter|bra|1.17.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-diff|fab|1.4.1
shell-format|fox|7.1.0
go|gol|0.25.0
postgresql|JPT|0.0.2
rainbow-csv|mec|1.8.1
render-crlf|med|1.5.18
template-string-converter|meg|0.4.8
debugger-for-chrome|msj|4.12.12
nbsp-vscode|pos|0.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
final-newline|sam|0.3.2
vscode-hexdump|sle|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythonvspyl392:30304724
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscorehov:30302759
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by sam-stanford** [comment]
Looking to take this on as my first issue, but I'm struggling to recreate the problem on Win10. Does anyone know if this is solely a Darwin OS issue?

**Comment by laveenaBachani** [comment]
Able to reproduce, looking into it.

**Comment by TylerLeonhardt** [comment]
@laveenaBachani is a part of Grace Hopper Open Source Day and verified (along with myself) that this issue is fixed. Thanks @laveenaBachani!! 🥳
