### ISSUE TITLE
Cannot toggle the test hide status

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#124544]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (user setup)
Commit: 5319757634f77a050b49c10162939bfe60970c29
Date: 2021-05-24T05:14:19.500Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

@connor4312 Please correct me if I missed anything. Currently, if a test is set to hide, I didn't find a way to toggle that status, is this by design?

**Comment by connor4312** [comment]
There are two ways to unhide the test:

1. With the "Unhide all Tests" command, available in the command palette and the filter button
2. If "Show Hidden Tests" is toggled on, via the "Unhide Tests" context menu action

**Comment by jdneo** [comment]
I cannot see the "Unhide Tests" context menu action


https://user-images.githubusercontent.com/6193897/119440990-e5caa700-bd57-11eb-9f4c-d10955a33b96.mp4

**Comment by connor4312** [comment]
Oop, that's a bug, good catch
