### ISSUE TITLE
Duplicating file: Editor not opened for the new file even if it has focus in the explorer (confusing)

### ISSUE THREAD

**Issue by thwoe** [microsoft/vscode#124565]
If I duplicate file (Ctrl+c/v) in file explorer, the new file will gain focus (highlighted) but the editor shows the original file, which is confusing because I think I edit the new file instead. 

- VS Code Version: 1.55.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create file and add some content
2. Duplicate (Ctrl+c/v)
3. (Optional) Rename the duplicated file (F2)
4. Edit the content of opened editor
5. Click on new file in the explorer

Here is the video:
https://www.awesomescreenshot.com/video/3873645?key=61fc7b55a2436a0d2f24ec851b0222b0

**Comment by isidorn** [comment]
Fixed in latest stable, please update
