### ISSUE TITLE
Blocked loading svg from localhost in webview using embed, iframe, and object tags

### ISSUE THREAD

**Issue by ty-d** [microsoft/vscode#124526]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57 insiders
- OS Version: Windows

Steps to Reproduce:

1. Run the sample extension: https://github.com/ty-d/WebviewBlockedOther
2. Run this simple express server: https://github.com/ty-d/SvgTestServer
    - npm install
    - node svgTest.js
3. Open the webview developer tools to the network tab
4. Run the command "Hello world" in the sample extension

This results in three requests with a status of "blocked:other", each corresponding to the embed, iframe, and object tags in the webview html.

**Comment by mjbvz** [comment]
I just tested this in VS Code insiders but it seems to work for me. Note that I had to update the webview html to use:

```html

<embed type="image/svg+xml" src="http://localhost:3000/test"/>
<object type="image/svg+xml" data="http://localhost:3000/test"></object>
<iframe src="http://localhost:3000/test"></iframe>
```

Without the closing `</object>`, I believe the iframe becomes part of the `object` element

Are you still seeing this in VS Code insiders?

**Comment by ty-d** [comment]
I am not seeing this issue in insiders now. Thanks!
