### ISSUE TITLE
Display top-level stop reason when StoppedEvent specifies no threadId

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#124532]
In Go sometimes we do not have a user thread id to specify in the stopped event. But if we issue a stopped event with a missing thread id, vscode will not show our stop reason at all.

```{"seq":0,"type":"event","event":"stopped","body":{"reason":"pause","allThreadsStopped":true}}```

Instead it would be great if the stop reason was either applied to all threads or even better displayed at the top level in line with CALL STACK like when there is only a single thread.

![image](https://user-images.githubusercontent.com/51177946/119410543-df77f480-bc9d-11eb-8cad-c84b11ec71ef.png)

**Comment by isidorn** [comment]
Ok, so the request is to introduce a rule: if a stopped event has not `threadId` then the reason should be shown top level or at the session level if there are multiple sessions.
This in general makes sense to me. Let's see what @weinand thinks

Also if we agree to change this I would be open to a PR that fixes this.
Here's a code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/callStackView.ts#L166

**Comment by weinand** [comment]
Since the `threadId` property of the `stopped` event is optional, we should not ignore showing the reason in that case.
I like @polinasok's proposal.

**Comment by isidorn** [comment]
Let's assign to June to investigate.
Adding help wanted. If nobody jumps on this I can look into it end of June

**Comment by isidorn** [comment]
Thanks @suzmue for tackling this via a PR 👏
