### ISSUE TITLE
Not opening interactive session for ipynb

### ISSUE THREAD

**Issue by vineet8588** [microsoft/vscode#124527]
Issue Type: <b>Bug</b>

Open ipynb file with vscode

Extension version: 2021.6.832593372
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.60GB free)|
|Process Argv|D:\\VineetSAMA\\Padhai Likhai\\CSE 6th Sem\\DMA\\LAB\\UE183119-Exercise-6.ipynb --crash-reporter-id 8f62f0b5-6ca9-45e7-b663-9df87e8662ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by claudiaregio** [comment]
Dupe of https://github.com/microsoft/vscode/issues/121029?

**Comment by rebornix** [comment]
@vineet8588 can you check your user settings and see if have `workbench.editorAssociations` set and share the value?

**Comment by vineet8588** [comment]
> @vineet8588 can you check your user settings and see if have `workbench.editorAssociations` set and share the value?

"workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ]

**Comment by vineet8588** [comment]
> Dupe of #121029?

Yes except it shows the interactive session normally if I drag and drop the ipynb file. 
But the other two conditions mentioned there are true : 

From file explorer when I right-click -> open with VS Code Insiders:

It shows the notebook experience if VS Code Insiders was already open before I did right-click -> open with VS Code Insiders
It shows the raw JSON file experience if VS Code Insiders was closed before I did right-click -> open with VS Code Insiders

**Comment by vineet8588** [comment]
@rebornix any updates? I shared the info u needed, can you change the label now?

**Comment by rebornix** [comment]
@claudiaregio do you know why the view type is different from `jupyter-notebook`?

**Comment by rebornix** [comment]
@vineet8588 can you please update this to 

```
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook",
    },
```

and see if it fixes the problem?

**Comment by vineet8588** [comment]
> @vineet8588 can you please update this to
> 
> ```
>     "workbench.editorAssociations": {
>         "*.ipynb": "jupyter-notebook",
>     },
> ```
> 
> and see if it fixes the problem?

That fixed the issue but it changed the UI completely, and I'm not sure but it looks like an older version of the jupyter editor?

**Comment by vineet8588** [comment]
Closing this issue since it now works fine in the latest version of python/jupyter extensions.
