### ISSUE TITLE
VsCode files encoding problem 

### ISSUE THREAD

**Issue by Franz333** [microsoft/vscode#124588]
Hello,

I am working on automation testing with RobotFramework (.py and .txt files). 
Some texts are in french so we are asked to use Windows1252 encoding.

Though I have had problems with file encoding / reading / interpreting with VsCode. Colleagues are using other IDE because  VsCode is not "working properly" regarding this. 

I would like to keep on using VsCode, but I am now losing a huge amount of time trying to sort out encoding problems.. When it's sorted out on my side, I send the files to my colleagues and they can get it to function.

I really don't know where it comes from..

ps... I do know about the "filesEncodingGuessAutomatic" or the ReOpen/Save With Encoding command but it does not help

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by Franz333** [comment]
Hi @bpasero 
thank you for answering.. 
yes I know those options.. it looks like vscode is having trouble managing encoding when the user changes from one code to another..
I will try to create a blank project later and detail the problem precisely
have a good day

**Comment by bpasero** [comment]
Thanks
