### ISSUE TITLE
`with` method in NotebookCellMetadata and NotebookDocumentMetadata is destructive

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#124555]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

The expectation in Jupyter extension was that `with` will preserve the existing cell metadata when applying the new edits using `with`.
Right now `with` just blows away what ever is in the current metadata, making it equivalent to `new Metadata`.

Looking at the tests this seems to be by design:
```typescript
	test('NotebookCellMetadata - with custom', function () {
		const obj = new types.NotebookCellMetadata(true, true);
		const newObj = obj.with({ inputCollapsed: false, custom: { display: 'hello' } });
		assert.ok(obj !== newObj);
		const sameObj = newObj.with({ inputCollapsed: false });
		assert.ok(newObj === sameObj);
		assert.strictEqual(obj.inputCollapsed, true);
		assert.strictEqual(newObj.inputCollapsed, false);
		assert.deepStrictEqual(newObj.custom, { display: 'hello' });

		const newCustom = newObj.with({ anotherCustom: { display: 'hello2' } });
		assert.strictEqual(newCustom.inputCollapsed, false);
		assert.deepStrictEqual(newCustom.mycustom, undefined); // I believe this is incorrect.
		assert.deepStrictEqual(newCustom.anotherCustom, { display: 'hello2' });
	});
```

See the last line.

However if this is by design, then why not just remove `with` and always new up the objects.

I believe the test is incorrect and `with` is meant to apply changes to the current object (at least that what I understand `with` to be, also thats what the docs seem to indicate as well `Derived a new document metadata from this metadata.`).

**Comment by DonJayamanne** [comment]
@rebornix /cc

**Comment by rebornix** [comment]
Good catch, I wonder if it's a recent regression.

**Comment by jrieken** [comment]
`assert.deepStrictEqual(newCustom.mycustom, undefined); // I believe this is incorrect.`

@DonJayamanne did you mean to write `mycustom` or `custom`. I don't see the former (`mycustom`) being defined anywhere and in that case it is expected to be undefined

**Comment by DonJayamanne** [comment]
Sorry, the tests in the code is more accurate.

**Comment by jrieken** [comment]
roger - also note that I have created https://github.com/microsoft/vscode/pull/125106 to remove all of that ;-) If that proposal is accepted we are good anyways

**Comment by jrieken** [comment]
this is now obsolete
