### ISSUE TITLE
vscode.executeDocumentRenameProvider command gives error for virtual document

### ISSUE THREAD

**Issue by william-xiang** [microsoft/vscode#124591]
We are trying to support embedded SQL in the main language using request forwarding. For now we already did this for `completion` and `hover`, but have some trouble with `rename`. The problem is the snippet below always gives us this error: 
`Running the contributed command: 'vscode.executeDocumentRenameProvider' failed.` It seems like the reason is that the document is not opened in the editor.
```typescript
provideRenameEdits: async (document, position, newName, token, next) => {
    const vdocUri = this.getVirtualDocumentUri(document);
    return await commands.executeCommand<WorkspaceEdit>('vscode.executeDocumentRenameProvider', vdocUri, position, newName);
}
```
Is there any way to support rename for virtual document?

---
VS Code version: 1.56.2
vscode-languageclient: 7.0.0

**Comment by jrieken** [comment]
>  It seems like the reason is that the document is not opened in the editor.

I don't believe so - the command will open the document for rename (tho not show it in an editor). The error is likely because the underlying language extension to which you are delegating doesn't support the virtual document. Tho, you need to check the logs for more info

**Comment by william-xiang** [comment]
> > It seems like the reason is that the document is not opened in the editor.
> 
> I don't believe so - the command will open the document for rename (tho not show it in an editor). The error is likely because the underlying language extension to which you are delegating doesn't support the virtual document. Tho, you need to check the logs for more info

**Comment by william-xiang** [comment]
> > It seems like the reason is that the document is not opened in the editor.
> 
> I don't believe so - the command will open the document for rename (tho not show it in an editor). The error is likely because the underlying language extension to which you are delegating doesn't support the virtual document. Tho, you need to check the logs for more info

Thanks for the reply, @jrieken. Unfortunately, it does not give me any info in the log regarding this. When I debug it, got this exception info:
