### ISSUE TITLE
Messes up quoted text

### ISSUE THREAD

**Issue by isambi** [microsoft/vscode#124540]
Issue Type: <b>Bug</b>

While editing HTML code, when you try to correct some quoted text, by removing or adding a double quote it messes up all quoted string below that edit point. IT ADDS A SINGLE SPACE BEFORE END QUOTE  - THIS MESSES UP THE NAMES AND IDS AND PROGRAM STARTS CRASHING. 

IT IS A PAIN CORRECTING ALL THOSE ADDED SPACES ONE BY ONE AS YOU CAN NOT DO A GLOBAL CHANGE.

I may not have configured my auto formating, but no matter what, the above behavious is very bad and should not happen.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.33GB free)|
|Process Argv|--crash-reporter-id e1abad41-da77-4e73-8b8b-ed9adf154fe1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
vscode-html-css|ecm|1.10.2
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.23.11
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
pdf|tom|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by aeschli** [comment]
Can you add a small code sample an steps to illustrate that? Also check whether it reproduces with extensions disabled.

**Comment by aeschli** [comment]
Thanks @isambi
I think I understand the problem, but not sure how this should be tackled. Yes, formatting incomplete may result in strange formats. It depends on the actual formatter and how the formatter deals with incomplete code.
I tried to reproduce it with the built-in HTML formatter but was not able to get extra spaces. Which formatter do you use for HTML? Maybe

**Comment by isambi** [comment]
Hi Martin:

I had reset all my settings by editing the settings.json and now it is not
happening.

It is something to do with a combination of settings. The frustrating part
was that even if I removed the space manually, it was putting it back right
away !!!

I will keep an eye and if it happens again, I will send you more info.

Sorry, I wasn't much help.

Inderjit

**Comment by isambi** [comment]
Thanks
