### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Harshnigam9009** [microsoft/vscode#124538]
Issue Type: <b>Feature Request</b>

I'm not able to see error while writing wrong code.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by dbaeumer** [comment]
@Harshnigam9009 please provide detailed steps (language used, sample file, user interaction, ...) on how to reproduce the problem you are seeing.
