### ISSUE TITLE
Have way to filter settings page to only show changed settings that are different from defaults

### ISSUE THREAD

**Issue by varnk** [microsoft/vscode#124521]
I would like to be able to filter the Settings page to only show settings that have been modified from the defaults.

**Comment by nrayburn-tech** [comment]
Type into the search `@modified` and it will filter to only the modified settings.

**Comment by IllusionMH** [comment]
/question

Or use item in ... menu which will add same filter that @nrayburn-tech (thank you) suggested.
![image](https://user-images.githubusercontent.com/1312662/119385945-8b860380-bccf-11eb-9ae1-82bd4a936f47.png)
