### ISSUE TITLE
Git integration not working when VSCode from binary

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#12456]
## Informations 
- VSCode Version: 1.5.2
- OS Version: macOS Sierra 10.12

I use SourceTree to have all my repositories listed, and a feature for opening a repo directly into VScode (see steps below).
But when I open it this way, the Git panel tells me that Git isn’t installed on the system. However, if I just open VSCode normally by clicking on the icon and drop the repository folder in it, it works perfectly fine.
I think it’s since the last update of VSCode, but I’m not sure. It seemed to be ok before. SourceTree hasn’t been updated recently, but VSCode did.

## Steps to Reproduce
1. You must use SourceTree, and set a custom command :
![](http://files.italic.fr/Monosnap_2016-09-22_16-32-05.jpg)
2. Then, open a repository with the custom command
![](https://files.not.live/Capture_decran_2016-09-22_a_16.39.49.jpg)
3. Go in the Git tab and let the sadness flow in your mind. 😢 
![](http://files.italic.fr/BlogPost.vue_-_emmanuelbeziat_2016-09-22_16-41-16.jpg)

I have no way to see if the problem come with another app than SourceTree, but again I think it’s coming from the last update of VScode.

Thanks!

**Comment by chrmarti** [comment]
VSCode checks for the git executable on the PATH (using `which git`). I guess when starting from SourceTree that PATH ends up not being the same as otherwise.

If you Help > Toggle Dev Tools, what does `process.env.PATH` evaluate to in the two cases?

**Comment by EmmanuelBeziat** [comment]
I just updated to VSCode 1.5.3, and it seem to work… That’s strange. I’ll check deeper tomorrow.

**Comment by EmmanuelBeziat** [comment]
I confirm this is not an issue anymore. Thanks!
