### ISSUE TITLE
CSS color decorators shown erroneously in a number of places

### ISSUE THREAD

**Issue by afeinman** [microsoft/vscode#124515]
Issue Type: <b>Bug</b>

We have a map which stores our GUI colors by name, e.g.

```const Colors = { "Our Blue": "#400080", "Dark Yellow": "#884400" };```

1. When accessing this map, VSCode incorrectly parses the code and offers a color picker for the color "Blue" (#0000FF) at ⌧ below.

```
const pageColors = {
   bgColor: Colors["Our ⌧Blue"],
}
```

This appears to require the space in the key name ("Our Blue") to trick the parser.

2. key names that are colors will also get an erroneous picker. Changing this key would lead to bugs.

```
  ⌧black: Colors["Black"]
```

3. Color pickers don't show for color strings when the line also contains other color-ish colors:

```
const Colors2 = { "Our Blue": "⌧#400080", "Dark Yellow": "#884400" };
```

A picker appears before #400080 but not before #884400.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sql-formatter|adp|1.4.4
quote-flipper|all|0.0.1
vscode-apollo|apo|1.19.1
bracket-pair-colorizer-2|Coe|0.2.0
styco|Dan|0.2.2
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.4.0
vscode-todo-plus|fab|4.18.3
file-icons|fil|1.0.29
docker-explorer|for|0.1.7
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.16
vscode-test-explorer|hbe|2.20.0
helium-icon-theme|hel|1.0.0
banner-comments|hey|0.3.0
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
vscode-styled-components|jpo|1.6.1
rainbow-csv|mec|1.8.1
indent-rainbow|ode|7.5.0
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.1
vscode-coverage-gutters|rya|2.7.3
svg-preview|Sim|2.8.3
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.4.0

(16 theme extensions excluded)

</details>

**Comment by afeinman** [comment]
Screenshot of all cases listed above.

<img width="633" alt="highlights" src="https://user-images.githubusercontent.com/561248/119373461-7042d600-bc86-11eb-8a31-b4368b1525fb.png">

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Most likely some extension (my bet is on `vscode-styled-components`) incorrectly adds these pickers or marks areas as `css` language.

**Comment by afeinman** [comment]
Correct! Reloading with no extensions shows no color pickers at all (didn't know that one-liner). I'll contact the vscode-styled-components developer.

...and may open a feature request to add color decorations to more syntax groups, for example, string constants used inside appropriate JSX style elements.

**Comment by IllusionMH** [comment]
To make sure it's that extension you can check with only that extension disabled. If reproducible with `vscode-styled-components` disabled you can use extensions bisect to find extension that causes this trouble https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
