### ISSUE TITLE
Linting recommendations showing TS recommendations in addition to ones from eslint.

### ISSUE THREAD

**Issue by Seefer** [microsoft/vscode#124509]
Issue Type: <b>Bug</b>

Should VS Code be showing both ts linting recommendations in addition to eslint ones? How do I tell VS Code to use eslint in place of tslint?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.26GB free)|
|Process Argv|--crash-reporter-id 39706a1d-47ad-4451-8289-40dab0b1bf44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
armview|ben|0.4.5
htmltagwrap|bra|0.0.7
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
docs-markdown|doc|0.2.92
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.4.0
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.4.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.1.0
vscode-edge-devtools|ms-|1.1.9
python|ms-|2021.5.842923320
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-ssh-explorer|ms-|0.55.0
remote-wsl|ms-|0.56.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cpptools|ms-|1.3.1
powershell|ms-|2021.2.2
typescript-javascript-grammar|ms-|0.0.55
vs-keybindings|ms-|0.2.1
vscode-node-azure-pack|ms-|0.2.1
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.4.4
ms-teams-vscode-extension|Tea|1.2.3
windows-terminal|Tyr|0.6.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

![Screenshot 2021-05-24 145933](https://user-images.githubusercontent.com/129484/119358628-b5740180-bca0-11eb-9f82-930dacf4c1c6.png)

**Comment by Seefer** [comment]
I have since discovered there are Typescript setting entries in VS Code and found I had to deselect Enable/disable Javascript validation.

![image](https://user-images.githubusercontent.com/129484/119359605-b6596300-bca1-11eb-8ada-43f9d3efce22.png)

**Comment by mjbvz** [comment]
The `TS` in the error message is not tslint, it is VS Code's builtin TypeScript extension which is also used for JavaScript IntelliSense 

As you discovered, you can disable these by disabling javascript validation
