### ISSUE TITLE
Graphical bug in integrated terminal

### ISSUE THREAD

**Issue by Tesohh** [microsoft/vscode#124519]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Use the integrated terminal

This is the issue i'm getting. A visual bug where lines appear in the middle of text.
![Screenshot 2021-05-24 183851](https://user-images.githubusercontent.com/45905658/119379082-4e197a00-bcbf-11eb-9aa9-abe92fd29816.png)

**Comment by IllusionMH** [comment]
Did you change `window.zoomLevel` value?

**Comment by Tesohh** [comment]
Yes, i put zoom level 0 and now it's fine. Thanks, i didn't think of that

**Comment by IllusionMH** [comment]
Probably duplicate of #106981
Upvote and track that issue to be notified when it's fixed.
Also there were couple of suggestions.
