### ISSUE TITLE
force:auth:web:login is not a sfdx command

### ISSUE THREAD

**Issue by ashish2889** [microsoft/vscode#124502]
Issue Type: <b>Bug</b>

 Warning: force:auth:web:login is not a sfdx command.
Did you mean force:apex:log:get? [y/n]: 
 »   Error: Run sfdx help force for a list of available commands.
17:10:12.632 sfdx force:auth:web:login --setalias rishiOrg --instanceurl https://test.salesforce.com --setdefaultusername
 ended with exit code 127

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to author of the Salesforce extension that you are using.
