### ISSUE TITLE
Couldnt Connect To Github and Microsoft

### ISSUE THREAD

**Issue by faeizalzhafrey** [microsoft/vscode#124668]
![Screenshot (137)](https://user-images.githubusercontent.com/77710535/119643498-62d84800-be4e-11eb-9bb1-eb00c07ed827.png)

Havent solve the problem for a week, need to connect to my github so i can use the repo to clone and edit the code using vscode, sadly because i couldn't logged in i couldn't edit the coding

**Comment by joaomoreno** [comment]
That `my.proxy.com` seems to be a bad configuration on your system. I suggest you fix that.
