### ISSUE TITLE
babel.config.json language mode should be 'jsonc'

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#124683]
Babel recommends using `babel.config.json` since a while back. Their JSON is parsed as JSON5, which supports comments. As such `babel.config.json` should have the language identifier `jsonc`. In addition the file `.babelrc.json` should also be get the same language id.

See https://babeljs.io/docs/en/config-files#supported-file-extensions

The change should be done here:
https://github.com/microsoft/vscode/blob/1cce707eb8ef2b22c6f33846367e1eb70547c3fe/extensions/json/package.json#L45-L63

Note that `.babelrc` is still valid and should continue being identified as `jsonc`.

**Comment by aeschli** [comment]
There will be validation errors when using JSON5. JSONC does not support the same syntax as JSON5.

There are JSON5 extensions out there, so the proper thing would be to assign `babel.config.json` with `json5`

**Comment by nicolo-ribaudo** [comment]
Ideally yes it should be `json5`, but `jsonc` is already a big improvement because `99%` of the Babel configs I have seen that are not plain JSON are just JSON + comments (to be honest, I have _never_ seen a Babel config that uses other json5 features).

**Comment by aeschli** [comment]
If we already know that `jsonc` is not correct,  I'd leave it up to the users to finetune the file association then (setting: `files.associations`).

**Comment by nicolo-ribaudo** [comment]
Then `.babelrc` should be removed from the predefined `jsonc` associations, in https://github.com/microsoft/vscode/blob/1cce707eb8ef2b22c6f33846367e1eb70547c3fe/extensions/json/package.json#L45-L63, since it's json5 too.

**Comment by thernstig** [comment]
@aeschli but there are already `.babelrc` mapped to `jsonc` as @nicolo-ribaudo and I already pointed out. Why were you so fast to close this. It is a valid concern to update this, or rather the best option to add these two new formats.

Using babel is **_very_** common in the Node.js echo-system. I don't see a reason for these not being there. I can even make the PR myself to fix this.

**Comment by aeschli** [comment]
I made the change as you proposed. Ideally these associations come from a babel extension, and even better they would be to `json5`.

**Comment by thernstig** [comment]
At least `jsonc` as the default is very good as that is probably what most users would use, as @nicolo-ribaudo pointed out.
