### ISSUE TITLE
Terminal cursor doesn't support proportional symbols

### ISSUE THREAD

**Issue by sevenc-nanashi** [microsoft/vscode#124653]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.57.0-insider
- OS Version:Windows_NT x64 10.0.17134

### Steps to Reproduce:

1. Open PowerShell Terminal 2 times
2. Run `function prompt{write-host "It glitches: " -NoNewline; return " "}` (It's just an example)
3. Type something

### Result
![image](https://user-images.githubusercontent.com/59691627/119620957-872d2800-be40-11eb-8b00-f2b45f72e0c9.png)
You will see that cursor isn't matched.

**Comment by Tyriar** [comment]
Can you elaborate what the problem is exactly?

**Comment by sevenc-nanashi** [comment]
https://user-images.githubusercontent.com/59691627/119724913-48cc5300-beaa-11eb-8f76-b295500e7859.mp4
I took a video, please see terminal

**Comment by Tyriar** [comment]
Does changing the `terminal.integrated.unicodeVersion` setting help?

**Comment by Tyriar** [comment]
Actually this looks like a problem with winpty, you'll need to update Windows 10 to get on the new system which is build by the Windows Terminal team.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
