### ISSUE TITLE
thr cursor is not insert

### ISSUE THREAD

**Issue by shibaprasadsahu943** [microsoft/vscode#124697]
Issue Type: <b>Bug</b>

when i am create a new file the cursor is not insertes and  i am typing what is not get in editor in vs code, also when i am after run edit code, my cursor is not able to work

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (4.18GB free)|
|Process Argv|--crash-reporter-id a5169baf-4864-4331-a3e9-0ccd992643ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.1
code-runner|for|0.11.4
vscode-pull-request-github|Git|0.26.0
better-cpp-syntax|jef|1.15.5
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.3
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0-insiders3
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vim|vsc|1.20.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by alexdima** [comment]
@shibaprasadsahu943 I am sorry, but I do not understand exactly what you mean. Could you please provide additional information. What do you mean the cursor is not working?
