### ISSUE TITLE
VSCode Insiders 1.57.0 Jupyter Notebooks invalid mime type must not be empty or falsy

### ISSUE THREAD

**Issue by JosephKarpinski** [microsoft/vscode#124698]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.57.0
- OS Version:MacOS 11.3

Steps to Reproduce:

1.Latest VSCode Insiders update downloaded and installed 
2.Can no longer open Jupyter Notebooks
3.Get Unable to open INVALID mime type, must not be empty or false

**Comment by dbaeumer** [comment]
Dups #124660
