### ISSUE TITLE
Control for items in right click menus

### ISSUE THREAD

**Issue by Summer-Shen** [microsoft/vscode#124651]
I wonder if we can actually control the items that would show up each time we right click on a file in the _EXPLORER_ side bar, or on some code in the editor. 

I'm using VS Code for a variety of projects, including `Maven`+`Java`, `Vue`, and `Angular` projects, etc., and have installed a number of extensions. Chances are I'd find unintended menu items in the right click menu, and it would take slightly more time and effort to navigate to the right menu item.

Thanks in advance!

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"menus"
