### ISSUE TITLE
版面的字體有點小

### ISSUE THREAD

**Issue by HY-SHEN** [microsoft/vscode#124659]
Issue Type: <b>Feature Request</b>

您好,請問這個程式可以放大嗎?
因為,如果不能放大的話,這樣眼睛看得很吃力

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by guobing1993** [comment]
windows 平台可以使用 "ctrl +/-"  进行界面缩放。
或者单独在设置里设置字体大小 "editor.fontSize": 16
![image](https://user-images.githubusercontent.com/22333388/119649956-d6318800-be55-11eb-9445-4cc8859f116e.png)

**Comment by HY-SHEN** [comment]
Morning!
thanks!

guobing ***@***.***> 於 2021年5月26日 週三 下午7:09寫道：

**Comment by dbaeumer** [comment]
Looks like you got the answer. There is a zoom level setting as well.
