### ISSUE TITLE
A single command line to update extensions in the extension pack to latest version

### ISSUE THREAD

**Issue by hanct** [microsoft/vscode#124670]
Hi,

I have extensions installed under an extension pack. But now, some of the extensions of this pack are outdated. is there a command line for me to update those extensions (under the extension pack) to the latest version?
I know i can force an extension to be updated to latest version using
      Code --force --install-extension=<ext id>

But instead of executing this command for each and every extensions under an extension pack,  is there a single command for me to request all extensions under a particular extension pack to be updated to latest version

**Comment by sandy081** [comment]
There is not any such command or ui feature.
