### ISSUE TITLE
Ctrl + left click(Mouse) is not working.

### ISSUE THREAD

**Issue by mong87suk** [Microsoft/vscode#12464]
- VSCode Version: 1.5.0
- OS Version: Raspbian GNU/Linux 8.0 (jessie)

Steps to Reproduce:
I worte follwoing codes in _test.c_ file 

```
1  #include <stdio.h>
2
3  int test(void) {
4
5    }
6
7    int main (void) {
8     printf("Hello\n");
9     test();
10   int a = 3;
11   return 0;
}
```

I did  _Ctrl + left click(Mouse)_  at the 9 line  but the cursor hasn't been moved to the 3 line.
I didn't know why it wasn't moved.
Could you fix this issue?

Thank you.

**Comment by chrmarti** [comment]
- Do you have the C/C++ extension installed?
- Does 'test' change its color and get an underline when you ctrl + hover?

**Comment by mong87suk** [comment]
Hi @chrmarti 
Thank you for your support.

- Do you have the C/C++ extension installed?
  Yes, I have. I have installed it.  the version is 0.9.1

- Does 'test' change its color and get an underline when you ctrl + hover?
   No, the color was not changed when I did _ctrl + hover_

Thanks

**Comment by chrmarti** [comment]
@mong87suk What does the Output panel show in the C/C++ channel?

**Comment by mong87suk** [comment]
Hello @chrmarti 
Thank you for your supprot.
I didn't know exactly what I have to show you.
I posted the picture which is captured on vs code.


![screen](https://cloud.githubusercontent.com/assets/6234666/18808678/8d005d16-82a3-11e6-9625-45975ac602d8.png)

Thank you

**Comment by chrmarti** [comment]
You can open the Output panel through the menu View > Output. There used to be a C/C++ channel in its top-right channel switcher, though it doesn't show for me currently, it might have been removed, could you check in your set up?

Another thing to try is to run Go to Definition from the context menu on line 9. Does that position the cursor on line 3?

**Comment by mong87suk** [comment]
Hello @chrmarti 
Thank you for your support.
I checked the _Output_ panel.  it is as follows.
![2016-09-27-091354_1225x715_scrot](https://cloud.githubusercontent.com/assets/6234666/18856146/60877ea8-8493-11e6-8a64-5fbfb01a2c21.png)

When I selected _C/Cpp Languase Server_ on _OUTPUT_,  The error happended.the error message is as follows.
**Connection to server is erroring. Shutting down server**
I don't know why this error happens. 
Dose this error cause that cursor is not moved?
Could you explain it?

I checked the _Default Keyboard Shortcuts_ to find _Go to Definition_ key.
it's _F12_  so I tried _F12 key_ : _'Go to Definition'_ but cursor has not been moved.

![2016-09-27-091443_1225x715_scrot](https://cloud.githubusercontent.com/assets/6234666/18856367/11bddb1c-8495-11e6-8c23-88ff27087498.png)


Thank you

**Comment by chrmarti** [comment]
Seems to be a problem with the extension.

@waderyan could you move this issue over to Microsoft/vscode-cpptools (or let me know how to do that myself)?

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#320
