### ISSUE TITLE
Show Popular Extensions shortcut Ctrl+J does nothing

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12467]
- VSCode Version:1.5.3 (does not display Ctrl+J shortcut hint on 1.5.2)
- OS Version:Windows 10

Steps to Reproduce:

1. Open Extension View
2. Ctrl+J                   nothing happens
3. Show Recommended Extensions
4. Try Ctrl+J again    nothing happens

Status bar shows "(Ctrl+J) was pressed. Waiting for second key of chord..."

According to Default Keyboard Shortcuts Ctrl+J is bound to togglePanel.

{ "key": "ctrl+j",                "command": "workbench.action.togglePanel" }

This appears to be a new shortcut displayed in 1.5.3.  There is no shortcut for Show Popular Extensions on 1.5.2. Could this have been brought in when the translation resources were added?

**Comment by chrmarti** [comment]
Still have 1.5.2 around and workbench.extensions.action.showPopularExtensions is not bound to any keys.

**Comment by gregvanl** [comment]
Interestingly I see it on one 1.5.3 install but not another.
![showpopularctrlj](https://cloud.githubusercontent.com/assets/12818376/18764911/4857faac-80c8-11e6-8c41-cb5734c4f731.png)

**Comment by gregvanl** [comment]
Silly me.  I had explicitly added Ctrl+J to my keybinding.json for Show Popular Extensions.
Nothing to see here, citizens. More along.
