### ISSUE TITLE
Extensions can't create 2 different sessions of the same provider

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#124643]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Have an extension that does this:

```
const session1 = await vscode.authentication.getSession('microsoft', ['499b84ac-1321-427f-aa17-267ca6975798/.default'], { createIfNone: true });
console.log(session1);
const session2 = await vscode.authentication.getSession('microsoft', ['Tasks.ReadWrite'], { createIfNone: true });
console.log(session2);
const session3 = await vscode.authentication.getSession('microsoft', ['499b84ac-1321-427f-aa17-267ca6975798/.default'], { createIfNone: false });
console.log(session3);
const session4 = await vscode.authentication.getSession('microsoft', ['Tasks.ReadWrite'], { createIfNone: false });
console.log(session4);

```

2. You'll notice that `session3` is `undefined`...even though it should exist because we created it on line 1.

This is because we cache the session id based on the provider id & extension name but _really_ we should be caching them based on provider id, extension name, AND SCOPES. This will allow `getSession` the 3rd time to find the session created in the first line.

**Comment by TylerLeonhardt** [comment]
Verification steps:

The code above...but session3 should not be undefined.

**Comment by polarweasel** [comment]
@TylerLeonhardt is your solution to this issue the reason that the Insiders builds have started bugging me at least once a day to sign into GitHub?

With four windows open, each with two extensions that want a GitHub token (_GitLens_ and _GitHub Issues and Pull Requests_), I have to generate 8 tokens to make VS Code stop bugging me... at which point it almost always discovers a VS Code update, and often we do the dance again after it restarts.

**Comment by polarweasel** [comment]
(And never mind, I see it was, and I see you fixed it!)

**Comment by TylerLeonhardt** [comment]
Reopening this because I reverted the change that fixed it.

**Comment by monil-patel** [comment]
@TylerLeonhardt just checking to see if there were any updates on this issue?

**Comment by TylerLeonhardt** [comment]
@monil-patel haven't had a chance to revisit this. You can take a look at my commit if you'd like. The problem I needed to address is migrating from the old storage keys to the new storage keys and my commit didn't handle that.

Unfortunately, I have some other work I'm working on at the moment so I won't be able to look at this this month.

**Comment by TylerLeonhardt** [comment]
This appears to be fixed. Closing now
