### ISSUE TITLE
Show a split view to allow navigation/inspection of different test messages

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#124626]

**Comment by connor4312** [comment]
Added in https://github.com/microsoft/vscode/commit/57af60a7b7f4774f007c78997763af5e2c67ceaa

![](https://memes.peet.io/img/21-05-9320d862-b63d-42ab-8e83-fc095adba42a.png)

**Comment by meganrogge** [comment]
@connor4312 What should I see if this is working correctly? Sorry, not too familiar with the test explorer 😅

**Comment by connor4312** [comment]
- The split view allows you to view/browse test messages for any retained run. (Runs without messages will be shown with a green ✔️ icon and no children)
- It's an extension of the previous message peek; it should show when any test fails.
- You should be able to click on messages to navigate to them and peek.
- There are context menu actions on the runs and test messages, which should work as their tooltips/labels indicate
