### ISSUE TITLE
Confusing trust message in banner for new empty window

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#124692]
* enable workspace trust
* open new empty window
* the banner message mentions "this folder" which is confusing

![image](https://user-images.githubusercontent.com/5047891/119680781-c6a84400-be41-11eb-8fc0-a3f7e3c9581c.png)

**Comment by sbatten** [comment]
this issue mentioned here https://github.com/microsoft/vscode/issues/124392#issuecomment-847278461
