### ISSUE TITLE
Jupyter Notebooks not working after last update

### ISSUE THREAD

**Issue by dmi-github** [microsoft/vscode#124660]
Issue Type: <b>Bug</b>

After applying the last update i cannot open my previously working jupyter notebooks anymore. (in the new native notebook editor)

The error message says: "INVALID mime type, must not be empty or falsy"

I can however create a new notebook, save it - close - and reopen it without problems.

Tried to copy the metadata from the new notebook to the old, but didn't help. Seems that this is related to some already existent cells.

Best regards,
Dominik

VS Code version: Code - Insiders 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269, 2021-05-26T05:14:06.346Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.86GB free)|
|Process Argv|--crash-reporter-id ad23a1ab-b7c1-4394-8035-03720f954fab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.864643163-dev
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.870847776
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by jrieken** [comment]
@DonJayamanne looks like a missing or wrong API adoption with the output changes. Note the the argument order of the `NotebookCellOutputItem` ctor has changed

**Comment by jrieken** [comment]
It looks like this announcement wasn't clear enough: https://github.com/microsoft/vscode/issues/93265#issuecomment-847723682
