### ISSUE TITLE
Feature request: tab to cycle through auto-complete options (like sublime text)

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#12462]
Currently VSCode's autocomplete just selects the first option if you press Tab or Enter.  In order to select a different option you have to use the arrow keys.  Tab is a much easier key to hit, and it's already redundant since Enter does the same thing in this context... I suggest changing it (or giving the option to) so it cycles through autocomplete options a-la Sublime Text style.

**Comment by joaomoreno** [comment]
I would not change this for most users, since <kbd>Tab</kbd> is often used for **selecting** the currently focused suggestion.

But you can customize this yourself in your keybindings. Here's the default:

```
{ "key": "down",                  "command": "selectNextSuggestion",
                                     "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible" },
```
