### ISSUE TITLE
Add "Open in vscode" finder extension.

### ISSUE THREAD

**Issue by redblue9771** [microsoft/vscode#124625]
Add "Open in vscode" finder extension for faster operation experience.

![2031621990930_ pic_hd](https://user-images.githubusercontent.com/32461741/119587682-bf614600-be01-11eb-91bc-82dd1ec583aa.jpg)

**Comment by roblourens** [comment]
What do you want a finder extension for vscode to do?

**Comment by redblue9771** [comment]
> What do you want a finder extension for vscode to do?

<img width="197" alt="WeChat39cdd53c9d560f12903ec9fce727f647" src="https://user-images.githubusercontent.com/32461741/119594003-95158580-be0d-11eb-8538-7e906d7340d1.png">

With it, I can right click on the file directory of the project. The right-click menu will display "Open this project in vscode". It’s faster than using the ‘code .’ command.

**Comment by roblourens** [comment]
I guess we have https://github.com/microsoft/vscode/issues/1223 for this request
