### ISSUE TITLE
Spinner wheel in Python Debugger / similar to Jupyter notebook (currently no moving visual indication that a debug command is running)

### ISSUE THREAD

**Issue by altosaar** [microsoft/vscode#124609]
Steps to reproduce:

1. Use Python VS Code extension to launch a new jupyter notebook
2. Execute a cell with `import time; time.sleep(20)`
3. Notice the spinner icon that moves, denoting that something is running (below the cell with current runtime in seconds):
![image](https://user-images.githubusercontent.com/5317244/119547583-490e0680-bd63-11eb-95fd-28506ca0fe7b.png)

Now switch to the python debugger: 

1. Use ctrl + shift + D to launch debug the current python file
2. Notice that the only visual affordance for seeing that something is running is the 'RUNNING' text in the bottom right in the call stack. 
![image](https://user-images.githubusercontent.com/5317244/119547601-4f03e780-bd63-11eb-9639-c01f63512454.png)

Just a thought, but adding a spinner icon besides 'running', or in the play/pause/stop on top while a debugging process is running, along with the timing info in seconds could be very helpful as a visual cue (I've found myself restarting processes frequently, unnecessarily)

Also posted on the extension page, but they don't control the debugger UI and recommended I post here (https://github.com/microsoft/vscode-python/discussions/16296#discussioncomment-782524).

Thanks! Please upvote if this something that would also help you!

**Comment by weinand** [comment]
The debug toolbar and the orange status bar are already indicators that a debug session is running.

What exactly should a spinner show for a multi-process/multi-threaded program?

**Comment by altosaar** [comment]
Got it, thanks! 

Not sure about multi-process, this was just an observation when switching to VS Code and comparing the ease of debugging in jupyter notebook to python. 

(On a 30+ inch monitor, it is hard to see whether the "Running" text is displayed; compared to the visual spinning icon like in a jupyter notebook on VS Code or a dynamic toolbar that might be possible)

**Comment by isidorn** [comment]
Fair feature request, but we have no plans to change anything here -> backlog
Let's leave open so we collect more user feedback, so far nobody complained about this.

Having a running spinner might be weird since debugging can be stopped and then nothing is in progress...
