### ISSUE TITLE
cant push in my own project via vscode

### ISSUE THREAD

**Issue by peterlymo** [microsoft/vscode#124657]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. add new update
2. when commit i get the error and i already login
![git](https://user-images.githubusercontent.com/30964644/119630979-238f0480-be18-11eb-9206-94b3494a6a9b.PNG)

**Comment by joaomoreno** [comment]
What if you push from the terminal? `git push`.
