### ISSUE TITLE
Regression after update - unable to use 2 Unity projects at once

### ISSUE THREAD

**Issue by isonil** [microsoft/vscode#124680]
Issue Type: <b>Bug</b>

After updating Visual Studio Code it's no longer possible to use 2 Unity projects at the same time (using Visual Studio Code on Mac). This happens:

1) The previously opened project works correctly - I can right-click a class name, and options like "Go to definition" appear.
2) The newly opened project doesn't work correctly - after right-clicking a class name only options like "Change all occurrences" appear (and the search bar doesn't show any class names, only files).

This is a regression - this used to work correctly before updating.

This is 100% reproducible.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Users/ison/Repos/RimWorld -g /Users/ison/Repos/RimWorld/Assets/Scripts/RimWorld/Game/ResearchManager.cs:1:0 --crash-reporter-id 4e73036e-b485-4a9b-bce7-8fed33e8316f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
csharp|ms-|1.23.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by dbaeumer** [comment]
VS Code out of the box doesn't provider Unity / C# support. I assume that you see this behavior in a C# file. If so please file the issue against the corresponding C# extension.

**Comment by isonil** [comment]
> VS Code out of the box doesn't provider Unity / C# support. I assume that you see this behavior in a C# file. If so please file the issue against the corresponding C# extension.

There are no VS Code extensions involved here, but Unity does something magic to open such projects in VS Code indeed (and there's no "sln" project I can just open outside of Unity). But you're right, perhaps it's an issue with Unity. I guess something just broke somewhere.

**Comment by dbaeumer** [comment]
All language smartness comes from an extension. So there must be an extension involved if feature are missing (e.g. Go to Definition).

**Comment by isonil** [comment]
> All language smartness comes from an extension. So there must be an extension involved if feature are missing (e.g. Go to Definition).

Oh, I see now. Sorry for the confusion!
