### ISSUE TITLE
Add option to disable animations for low-perf devices

### ISSUE THREAD

**Issue by natejgardner** [microsoft/vscode#124644]
I'd like a setting to disable animations completely in VS Code. On low performance devices (I'm running on a Helio P60T), Code's renderer often uses more than 90% of all cores whenever animations are triggered, especially loading animations at the top of the navigation column. It would be great to be able to configure VS Code to run smoothly on low-end devices in some sort of lightweight graphics mode. Code runs fine on this device with the exception of rendering tasks, so I think simply creating a setting to remove as many animations (and any other non-critical intensive rendering tasks) as possible would make it very usable. Additionally, if markdown were not rendered by default in this mode, but instead users could trigger markdown rendering with a button, that would improve performance where some extensions automatically open their markdown description pages, which also eat up performance.

**Comment by GeekyMonkey** [comment]
This is a big problem for me working from a remote desktop connection over a weak internet connection.  When I mouse over a red squiggly, the box describing the problem fades in, which can take 10 seconds before it fully renders.

**Comment by konradsa** [comment]
Important feature to make Vscode more usable via weak RDP connection, for instance mobile connections.
