### ISSUE TITLE
Markdown & Notebook markdown are missing files in web

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#124685]
With https://github.com/microsoft/vscode/pull/124557/files we started using notebook renderers on the web. But the web bits are missing the `notebook-out` folders, since the web build is completely separate from our regular build.

cc @mjbvz

**Comment by joaomoreno** [comment]
@mjbvz This over-customization of extensions build further complicates our already-complicated build. It would be good to have synced on this beforehand. I am now refactoring `gulpfile.extensions.js` and `lib/extensions.ts` to accomodate for the code reuse with `gulpfile.web.js`. This was already a big mess due to the past introduction of `gulpfile.web.js` (cc @aeschli), and with the introduction of different build entry points to extensions, it unfortunately adds another dimension to the mess.

**Comment by mjbvz** [comment]
Ok, let me know if you have questions about the current structure. Some parts probably need to remain unique to the webview extensions build stage. For example, we use esbuild instead of webpack so that we can output native modules

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/commit/d77799165664786807e9b439751a550ccfec3e27
