### ISSUE TITLE
Cannot launch VS Code from a shell

### ISSUE THREAD

**Issue by seawolf42** [microsoft/vscode#124676]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: 11.4

Steps to Reproduce:

1. Install VS Code
2. Install `code` to path using the command pallet
3. Open Terminal
4. Type `code .`

### Expected Result:

VS Code opens with the current directory as the current context

### Actual Result:

```sh
% code --disable-extensions
/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory
~ %
```

### Additional Context:

This started happening 3 days ago; at that time I was using the previous version of MacOS (11.3.?). Since then I have upgraded to MacOS 11.4 and the problem persists.

I have attempted uninstalling and reinstalling the CLI command using the command pallet but the problem still persists.

This could be the same problem as #89037, but that issue never had a resolution other than "it magically started working again for me". In testing things, I did discover that `realpath` does not exist on my system. I then performed a `brew install coreutils` and can see `realpath` working as expected, but VS Code continues to exhibit the same issue.

**Comment by joaomoreno** [comment]
What does `which python` return from your terminal?

**Comment by seawolf42** [comment]
That's a good question. I run python within Docker containers, and have been doing so using an alias:

```sh
% which python                                                                                                                          8:23:08
python: aliased to docker run --rm -ti -v ${PWD}:/data -w /data python:3.9.4-buster python
~ %
```

This has been working just fine and has had no effect on VS Code. I recently (about the time this issue occurred) switched from an alias to a script that is early in my `$PATH`:

```sh
#!/bin/sh
docker run --rm -ti -v ${PWD}:/data -w /data python:3.9.4-buster python $@
```

This appears to be what broke things.

**Comment by joaomoreno** [comment]
If you inspect our launcher, you'll see that we depend on Python, unfortunately: `cat $(which code)`. You can hardcode your system Python in that script and that'll fix it for you.

**Comment by seawolf42** [comment]
OK, that makes sense. I believe hardcoding a change in the launcher will break every time I upgrade Code, but I can work around that by switching back to the alias I was using.
