### ISSUE TITLE
Emmet snippets not loading, gets stuck on "loading"

### ISSUE THREAD

**Issue by AutomatedTester** [microsoft/vscode#124675]
Issue Type: <b>Bug</b>

When working in a python I am trying to use snippets but they have stopped loading. They were working but now it gets stuck on "loading" when I press `tab`

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 8|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id 82d11234-e97f-4a29-a061-9f1002a73fae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.4.1
vscode-markdownlint|Dav|0.41.0
csharp|ms-|1.23.11
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
atom-keybindings|ms-|3.0.9
debugger-for-chrome|msj|4.12.12
vscode-starlark|phg|0.3.1
bash-debug|rog|0.3.9
rust|rus|0.7.8
vscode-pets|ton|1.8.0
vscode-icons|vsc|11.4.0
vim|vsc|1.20.3
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by rzhao271** [comment]
\gifPlease
