### ISSUE TITLE
Extensions sharing common settings?

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#124662]
Some background:
we (Red Hat) publish quite a [number of extensions](https://marketplace.visualstudio.com/publishers/redhat) on the VS Code Marketplace. We started to enable anonymous, opt-in telemetry collection a few months ago, via a `redhat.telemetry.enabled` setting. Since this setting is shared/respected by multiple extensions, we found the best way to register it was to use a [common extension that would be responsible for that setting](https://github.com/redhat-developer/vscode-commons/blob/021b0165bb5ba05e107ee7e31d1e59a7a73f473c/package.json#L29-L33), that Red Hat extensions could depend on (as a required dependency). This technically works fine, and the rollout was totally successful for the first ~900k installs, until vscode-yaml telemetry was rolled out. We then started getting some [heavy flak](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-commons&ssr=false#review-details) from users complaining about that extension dedicated to telemetry, being automatically forced on them. We decided to rollback yaml telemetry collection until we find a better way to do it, that doesn't involve depending on a dedicated telemetry extension.

Unsatisfying solutions we considered:
- define 1 dedicated setting per extension: doesn't scale, we'd need to show as many opt-in popups as extensions we publish
- do not register `redhat.telemetry.enabled`: can not be updated via API (throws an error), also doesn't provide documentation, content assist, shows as unknown in json editor. 
- duplicate the same `redhat.telemetry.enabled` setting in all our extensions. That will probably work but then we'll see as many duplicates in the settings UI. That would be our last resort.

A potential solution might be to allow 3rd party extensions to programmatically register settings (if they don't exist). That probably comes with other issues, but this is where the discussion starts ;-)

cc @gorkem @deboer-tim

**Comment by deboer-tim** [comment]
IMHO the two most obvious solutions are:
1. Allowing a common parent extension to be marked as such, hidden in the extension UI, and automatically uninstalled when all of its children are.
2. A mechanism for extensions to have some shared settings.

The first might make more sense for this case but I don't know how many other extensions would use it outside of the biggest providers. The second could be more generally useful, e.g. in cases where a set of extensions have similar options or don't want to create a new setting where one exists in another extension.

**Comment by sandy081** [comment]
Regarding following workaround:

> duplicate the same redhat.telemetry.enabled setting in all our extensions. That will probably work but then we'll see as many duplicates in the settings UI. That would be our last resort.

Have you tried this? I do not think we will be showing duplicates as we validate during registering for duplicates. I am not recommending this but it seems worth trying out if it works.

**Comment by fbricon** [comment]
Oh yes I tried it
<img width="569" alt="Screenshot 2021-06-08 at 19 19 25" src="https://user-images.githubusercontent.com/148698/121229614-793ec480-c88e-11eb-8e9f-0ec355b1bf9f.png">

**Comment by sandy081** [comment]
Ok, thanks for confirming. This shall not happen, will investigate.

**Comment by fbricon** [comment]
my guess is you could have 2 extensions contributing the same preference key but with different descriptions. In that case which one to display?
But if settings are 100% identical, then only 1 entry should be shown

**Comment by sandy081** [comment]
Description shall not matter. We cannot register duplicate keys.

**Comment by sandy081** [comment]
Just investigated and it seems there is a bug in detecting duplicates. Fixed it. Now you will see only one setting even if you register more than one settings with same id. The first one always wins.

Please let me know it this unblocks you.

**Comment by fbricon** [comment]
Excellent news. That should make things much better for us. Do you know when it'll be released?

**Comment by sandy081** [comment]
Insiders will be released today/tomorrow. But stable takes one month as this goes in June milestone.
