### ISSUE TITLE
Diff decorators not showing in gutter

### ISSUE THREAD

**Issue by Mr-Smarty** [microsoft/vscode#124645]
Issue Type: <b>Bug</b>

I cannot accurately pinpoint the cause and steps to reproduce. Last time I used VS Code, they were there, and now they are not. I have gone through many issues claiming this to be fixed through updates, but could not find a similar one for the latest version (1.56). Sorry if I've done something wrong in this issue, still sorta new to me :)

1. Init new repository or clone existing repository.
2. Make a change to a file.
3. Watch as diff decorators do not appear but the rest of git continues to function. Should be seeing something like this: 
![image](https://user-images.githubusercontent.com/69656599/119603202-bb5e0580-bdba-11eb-96db-86ecb4ed80cc.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.99GB free)|
|Process Argv|--crash-reporter-id f49753b1-2c31-498a-926b-66012f216a78|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by Mr-Smarty** [comment]
Update: the issue does not appear across all repositories. It appears in one repository but not another located within the same directory.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are there any changes to settings starting with `scm.diff` in workspace settings for this folder?

**Comment by Mr-Smarty** [comment]
Settings for both user and workspace are default.
![image](https://user-images.githubusercontent.com/69656599/119667675-824a8300-be04-11eb-970f-71746ac57a06.png)

**Comment by Mr-Smarty** [comment]
Update: The issue appears to be with a certain file. I tested making changes in other files within the project, even files within the same path as the file with the issue. Diff decorators in the gutter seem to work for every file but one. Some sort of bug?

**Comment by IllusionMH** [comment]
Do you see this file in Changes section of SCM view or when you run `git diff`?

Maybe this file is just ignored in Git?

**Comment by Mr-Smarty** [comment]
Yeah, changes are there in SCM view and I get the yellow/orange M symbol next to it in the file viewer when I make changes.

**Comment by Mr-Smarty** [comment]
Any updates? I would not like this to close for inactivity haha

**Comment by Mr-Smarty** [comment]
This issue is still marked with needs-more-info. If I read correctly, issues with this label are closed after a week with inactivity. Is there any more information I can give to help solve this issue?

**Comment by limon4ikas** [comment]
@Mr-Smarty It might be related to #103444, possible solution [stackoverflow](https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git).

**Comment by Mr-Smarty** [comment]
Thank you, I will check that out and report back on the results soon. Much appreciated 👍

**Comment by Mr-Smarty** [comment]
That issue and the solution are definitely related as when I rename the file to be lowercase with `git mv` it works. However when I rename again back to how it should be, it breaks again. @limon4ikas Any ideas?

**Comment by Mr-Smarty** [comment]
Just tried deleting and recreating the file. It did not fix it.

**Comment by limon4ikas** [comment]
@Mr-Smarty What worked for me was making a commit after each step: rename, commit, rename to what you need, commit again

**Comment by Mr-Smarty** [comment]
That is what I tried. Rename, commit, rename, commit. Sorry for so many comments in a short span of time, but here is yet another update. I deleted the local repository and cloned the branch from Github again and everything is now working. This is a solution but obviously not the most preferred. I do not know if this is now a VS Code problem or an OS problem with windows having a case insensitive file system. I will leave this open because I do not know whether the issue regards VS Code or Windows and I do not know what you devs want to do next.

**Comment by alicanyuksel** [comment]
Having the same issue, that what I tried too and <ins>**it did not fix it :**</ins>

- [x] Delete the file from git and local repository and create the file again, commit and push it
- [x] Uninstall Vscode and reinstall 
- [x] Clear all of the Vscode caches : 
Press **Ctrl + Shift + P**
Type command **Clear Editor History** and press enter 
or
Another option for Mac users : go to _~/Library/Application Support/Code/Cache_ and _~/Library/Application Support/Code/CachedData_ and delete them.

- [x] git config core.ignorecase _**true or false**_
- [x] Remove all files, add them again, commit and push them
    `git rm -r --cached .`
    `git add --all .`
    `git commit -a -m "Versioning untracked files"`
    `git push origin master`

### The solution as @Mr-Smarty wrote above is : 
* Delete the local repository and clone the branch from Github again

After that, <ins>**I confirm everything is working**</ins> without problems. 

I find it hard to believe that the problem is with the operating system (MacOS or Windows) because I tried with Atom, Sublime, Pycharm, all of them were able to detect changed lines but VSCode was not. 

Hope this will be resolved soon.

**Comment by lramos15** [comment]
Will close for now, but thanks for the detailed documentation as it will help others who hit a similar issue
