### ISSUE TITLE
Issue when loading webviews : ERR_ABORTED 404

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#124678]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.57.0-insider (user setup) Date: 2021-05-26T05:14:06.346Z
- OS Version: Windows 10 x64

Hello guys,
I do have an issue with webviews using VS Code 1.57 Insiders. This issue does not appear on VS Code 1.56.2 and before.

GET https://file+.vscode-resource.vscode-webview.net/c%253A/debug-extension/debug-extension/Extensions/debug-tools/out/vendor.js net::ERR_ABORTED 404
(anonymous) @ main.js:687
setTimeout (async)
L @ main.js:685
(anonymous) @ main.js:716

Steps to Reproduce:

1. Open VS Code Webview
2. Error occured

Part of code to open this webview
```ts
    private openPanel(context: vscode.ExtensionContext) {
        this.panel = vscode.window.createWebviewPanel(
            'WebView',
            'Webview Browser',
            vscode.ViewColumn.Two,
            {
                enableScripts: true,
                localResourceRoots: [ vscode.Uri.file(path.resolve(context.extensionPath, 'out'))],
                retainContextWhenHidden: true
            }
        )
        context.subscriptions.push(this.panel);

        this.panel.webview.onDidReceiveMessage(message => this.onDidReceiveMessage(message));

        this.panel.webview.html = `
            <html>
                <head>
                    <meta charset="utf-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                </head>
                <body>
                    <div id="app"></div>
                    ${this.loadScript(context, 'out/vendor.js')}
                    ${this.loadScript(context, 'out/MemoryBrowser.js')}
                </body>
            </html>
        `;
    }
```

**Comment by mjbvz** [comment]
What does `this.loadScript` do? Please share a self-contained, minimal example extension that demonstrates the issue

**Comment by yannickowow** [comment]
Here is `this.loadScript`
```ts
    private loadScript(context: vscode.ExtensionContext, path: string) {
        return `<script src="${vscode.Uri.file(context.asAbsolutePath(path)).with({ scheme: 'vscode-resource'}).toString()}"></script>`;
    }
```

It looks like I was doing it wrong here, I need to generate an URI using webview method `asWebviewUri` instead... 

Sorry for the inconvenience

**Comment by mjbvz** [comment]
Yes definitely switch to `asWebviewUri` instead. It is the only officially supported way to load resources in webviews now

However to support existing extensions, we have logic that should rewrite any old, hardcoded `vscode-resource` URIs to use the new uri scheme instead. Let me see if that's broken

**Comment by yannickowow** [comment]
Ok, I was not aware about this "rewrite" logic. 
Is it worthy to reopen this issue ?

**Comment by mjbvz** [comment]
Rewriting seems to work on MacOS. Taking a look on windows

**Comment by mjbvz** [comment]
This is also appears to be working for me on Windows with the latest VS Code insiders build. Please let me know if there's some specific case where it doesn't work (I only tested on the `c:` drive for example)

**Comment by yannickowow** [comment]
I can reproduce an issue with CatCoding extension (webview-sample)
Replace `scriptUri` with
```ts
		const scriptUri = vscode.Uri.file(scriptPathOnDisk.fsPath).with({scheme: 'vscode-resource'});
```
You will see counter not increasing on VS Code 1.57 Insiders, and counter working correctly on VS Code 1.56.2.

Webview will open but will not work correctly, and you will see ERR_404 as well.

For information, my VS Code installation PATH contains a space, if it can help...

**Comment by mjbvz** [comment]
To verify 

1. Using the [webview sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample)
2. Rename `media/main.js` to `media/ma in.js`
3. Apply the following diff:
```diff
diff --git a/webview-sample/src/extension.ts b/webview-sample/src/extension.ts
index d2b6e26..5c59a05 100644
--- a/webview-sample/src/extension.ts
+++ b/webview-sample/src/extension.ts
@@ -168,10 +168,10 @@ class CatCodingPanel {
 
        private _getHtmlForWebview(webview: vscode.Webview, catGifPath: string) {
                // Local path to main script run in the webview
-               const scriptPathOnDisk = vscode.Uri.joinPath(this._extensionUri, 'media', 'main.js');
+               const scriptPathOnDisk = vscode.Uri.joinPath(this._extensionUri, 'media', 'ma in.js');
 
                // And the uri we use to load this script in the webview
-               const scriptUri = webview.asWebviewUri(scriptPathOnDisk);
+               const scriptUri = (scriptPathOnDisk).with({ 'scheme': 'vscode-resource' });;
 
                // Local path to css styles
```

4. Build and run the extension
5. Run the `Cat Coding: start cat coding` command
6. Verify the counter is incrementing properly

**Comment by JacksonKearl** [comment]
Was not able to reproduce the original bug in Stable on MacOS or Windows.
