### ISSUE TITLE
Vs code integreted terminal is not responding when using the arrow keys in MacOS 11.4

### ISSUE THREAD

**Issue by Tekh-ops** [microsoft/vscode#124673]
Does this issue occur when all extensions are disabled?: YES sure

- VS Code Version: 1.56.2
- OS Version: 11.4 (20F71)

Steps to Reproduce:

1.  When I use the up and down arrows to navigate between commands in Vs integrated terminal, the terminal just froze and stops to respond 
2. But I don't get any screenshots

**Comment by meganrogge** [comment]
1. Have you run extension bisect?
2. Please provide a [gif](https://gifcap.dev/) with screencast mode enabled
3. Please turn on escape sequence logging and provide me with the output of that

**Comment by Tekh-ops** [comment]
Sure, but need some time for testing that bug again. Thanks for listing this issue

**Comment by Tyriar** [comment]
Also more specific OS information would be good.

**Comment by Tekh-ops** [comment]
Ummm it may be a system problem with the terminal, but it is a little bit tricky to figure it out, let's wait for some mac update for the terminal. It is basically the terminal fault. I may wait some time , or maybe close the issue.

**Comment by Tyriar** [comment]
Let us know if you get more info
