### ISSUE TITLE
Open same folder in a separate window regression

### ISSUE THREAD

**Issue by jjr2527** [Microsoft/vscode#12465]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open a folder
2. Open a new window
3. Open the same folder in this new window
4. The folder does not open

This was working before the latest update.

**Comment by chrmarti** [comment]
The -n command line switch also no longer works.

**Comment by bpasero** [comment]
You can NOT (and could NEVER) open the same folder in multiple windows. There are other issues asking for this feature request.

@chrmarti please file a separate bug if you find that "code -n" does not open a new empty window.

**Comment by chrmarti** [comment]
Nah...I misunderstood what -n is supposed to do. Works fine for me.
