### ISSUE TITLE
create ability to redirect Console.log to a physical file

### ISSUE THREAD

**Issue by CNA-Prv-Rec** [microsoft/vscode#124669]
When building an application in node.js there may be a large volume of information output by npm, it is not always possible to see all of this because the console only allows a limited number of lines to be visible and data is lost once you have reached the limit. I would like to redirect what is in Console.log to a physical file so that when the console has lost the data I can still see it, also if it is in a physical log file I will be able to search and query the data which will be very useful in finding the information I need. e.g. would like to output any npm vulnerability reports to a searchable file so we can identify improvements.

**Comment by weinand** [comment]
@CNA-Prv-Rec how and where are you running your npm build scripts?
