### ISSUE TITLE
Smoke test: Flaky `Multiroot - shows results from all folders`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#124674]
This specific test is failing more often than not, on macOS. It failed on every single red cross in the screenshot below. The location test also failed, but let's fix this one first to see if that also fixes the localization test. cc @dbaeumer

It's surprising that it succeeds sometimes. What's especially strange is that an exception still appears in the logs, even [when it succeeds](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=120308&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab).

![image](https://user-images.githubusercontent.com/22350/119653589-5d421a00-bddc-11eb-825d-4df8fd78dded.png)

**Comment by bpasero** [comment]
@TylerLeonhardt related to recent changes maybe? The smoke test looks for this:

```
Error: Active element not found. Current active element is 'HTML > BODY.mac > DIV.file-icons-enabled.monaco-workbench.mac.chromium.nopanel.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element.mac > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.monaco-scrollable-element.mac > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.monaco-scrollable-element.mac > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.monaco-scrollable-element.mac > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-instance > DIV.gettingStartedContainer.width-semi-constrained.animationReady'. **Looking for .quick-input-widget .quick-input-box input**
```

**Comment by bpasero** [comment]
Wait, this smells:

```
gettingStartedContainer.width-semi-constrained.animationReady
```

@JacksonKearl ?

**Comment by bpasero** [comment]
Maybe related to https://github.com/microsoft/vscode/issues/122317

**Comment by joaomoreno** [comment]
I wonder what's different between Linux/Windows and macOS, which makes the latter fail *very* often.

**Comment by bpasero** [comment]
Startup editor is now `empty`, via https://github.com/microsoft/vscode-smoketest-express/commit/a65be2a6b5b65536550e901b7ea33b384d73ff63 and https://github.com/microsoft/vscode/commit/4cda850edf57f244260b7b534cbb8d7c3717f58a

I suspect we run some random getting started experiment only in built form.

**Comment by JacksonKearl** [comment]
Thanks, we could also disable experiments entirely, `"workbench.enableExperiments": false`

**Comment by bpasero** [comment]
👍  pushed that too.
