### ISSUE TITLE
launch.json generation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12460]
- [x] any os @egamma 

Complexity: 2

We have changed the way how we get the content for the initial 'launch.json'. More details #9061. 
Have a workspace with no 'launch.json' file and verify:
* A proper 'launch.json' gets generated for the following debug types: node, extension host, go...
* For node debugging the content of the 'package.json' is read and the generated 'program' attribute in 'launch.json' points to the one referenced there (example: use [vscode-smoketest-express](https://github.com/Microsoft/vscode-smoketest-express) workspace)

**Comment by chrmarti** [comment]
Related #8937

**Comment by Skamau** [comment]
![screenshot 2017-03-15 16 24 24](https://cloud.githubusercontent.com/assets/26254540/23950447/0fafec7a-099c-11e7-8729-b9f826b1a814.png)
this is not working for me..please help
