### ISSUE TITLE
Add option to always use single file mode (syntax only mode) for JS/TS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#124649]
On web, we support running the TypeScript server in syntax-only mode. This limits IntelliSense to the current file (and also disabled some features such as renaming). The benefit is that it starts up almost instantly and doesn't require parsing the user's entire workspace

We'd like to add an option to enable this mode on desktop too. This would be a very specialized setting for a few use cases:

- For users in massive projects that are running into major performance issues, this mode would be an escape hatch so they can continue getting some IntelliSense while working

- Helping us test serverless mode

/cc @amcasey

**Comment by HaoboGu** [comment]
does [standalone tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29) support this feature?

**Comment by mjbvz** [comment]
Yes, it's already used while loading projects and on serverless cases on web

**Comment by amcasey** [comment]
Any chance we can change the string "loading..." in this mode?  There isn't more info coming later.

**Comment by mjbvz** [comment]
@amcasey I've added an undocumented `"typescript.tsserver.useSeparateSyntaxServer": "forAllRequests"` setting that should let you test this on desktop

Could you please test it out and let me know if you notice any bugs. Also let me know if it's something we want to officially document in the future

**Comment by amcasey** [comment]
@mjbvz The option does what I wanted.  Thanks!
