### ISSUE TITLE
Wrong German translation of "Open Editors"

### ISSUE THREAD

**Issue by Fahrradflucht** [Microsoft/vscode#12479]
- VSCode Version: 1.5.3
- OS Version: OSX 10.11.6

The German translation of vscode has a similar issue to the ones described in #12478 where the translator obviously hadn't enough context.

The explorer "Open Editors" heading was interpreted as a verb by the translator and therefor translated to "Editoren Öffnen" which means something along the lines of "to open editors" or "open the editors". A better translation would be "Offene Editoren".

**Comment by johnliu2016** [comment]
@lukaschal Please have the "Open editors" fully reviewed in German translations with this contextual info and correct as appropriate.

/Localize/deu/vscode/src/vs/workbench/parts/files/browser/views/openEditorsView.nls.resx.lcl
/Localize/deu/vscode/src/vs/workbench/browser/ui/parts/editor/editor.contribution.nls.resx.lcl
/Localize/deu/vscode/src/vs/workbench/electron-browser/main.contribution.nls.resx.lcl
/Localize/deu/vscode/src/vs/workbench/parts/files/browser/files.contribution.nls.resx.lcl
/Localize/deu/vscode/src/vs/workbench/parts/files/browser/fileActions.nls.resx.lcl

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.
