### ISSUE TITLE
Enable math rendering in comments API markdown

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#124784]
## Feature request

We now ship support for rendering math equations inside of markdown for notebooks. However this is currently disabled for markdown that is rendered as part of the comments API 

If we do this in a generic way like we did for notebook books, this would require a quite involved change since we'd have to move the rendered markdown into an isolated context (such as an iframe). However if there's enough demand just for math, we could consider adding this as a feature to core instead of trying to develop it as a built-in extension

**Comment by mjbvz** [comment]
Closing as this would require fairly substantial work to implement properly

To add math rendering to markdown in notebooks, we had to move all md rendering from core to the extension host so that extensions can extend the md renderer with new syntax/features. We don't currently have enough use cases to justify doing this for comment rendering too

**Comment by LunarLanding** [comment]
Given that vscode is widely used by data scientists ( https://visualstudiomagazine.com/articles/2021/02/09/kaggle-survey.aspx?m=1 ) and that these users frequently use libraries that include math notation in their documentation, I think this single use case justifies it. 

Together with the DocView ( https://marketplace.visualstudio.com/items?itemName=bierner.docs-view ) extension this could avoid a lot of alt-tabbing to online docs.

**Comment by shrinktofit** [comment]
It would be nice if the following comment could have math rendering when hovering on it :)

<img width="568" alt="image" src="https://user-images.githubusercontent.com/28807867/192131540-439b4f40-8ab3-4578-934f-cbf1aece9898.png">


The github's markdown has already enable the rendering. 👇

Finds a point on ellipse which has the shortest orthogonal distance to the input point $(x_t, y_t)$. The ellipse is represented by the standard ellipse equation $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$.

**Comment by sahilmtayade** [comment]
I think the use case for this feature is growing at a rapid rate. VScode is used by data scientists and AI, and this field is growing a lot. Therefore, I would really like to see this feature moved up in priority.

**Comment by andyabateagility** [comment]
@mjbvz could this be implemented if I said "pretty please"? Math is all over numpy/scipy, and having just basic mathjax/katex dollarsign typesetting would be huge.
