### ISSUE TITLE
undo stack LOST.

### ISSUE THREAD

**Issue by jbovone** [microsoft/vscode#124700]
Since this problem was caused for particular no reason because i was normally using vscode, i can not provide any insights to reproduce this. 

But since THIS IS HAPPENING, probably would be a good idea to mount an operation to figure it out, you know. Losing your work because of an undo not working properly isn't ideal scenario for a code editor and i probably will switch this editor for another because this is mind-boggling, seriously. 

The so was Ubuntu 20.04.2 LTS. 
The file subject to the data lost was renamed shortly before the "malfunction".
Have a nice day.

**Comment by alexdima** [comment]
@jbovone I am sorry that you have lost the undo stack. This should never happen. Can you please provide some steps to reproduce?
