### ISSUE TITLE
Enable math rendering in standard markdown preview

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#124783]
## Feature request
We now ship support for rendering math equations inside of markdown for notebooks. However this is currently disabled for normal markdown source code

It would be great to enable this rendering for the normal markdown preview too. A few notes:

- There needs to be a simple way to turn off this feature
- We also need a bit more testing of the rendering in insiders to make sure it doesn't cause any weird issues (specifically we want to make sure markdown with `$` that should not be part of a math equation doesn't do weird things)

**Comment by rzhao271** [comment]
@mjbvz can you provide some verification steps for this issue?
Using the experimental iframe, the results seem off:

![mathpreviewweird](https://user-images.githubusercontent.com/7199958/123849298-7ce1cc00-d8cd-11eb-9ec7-3a906877e60e.PNG)

**Comment by mjbvz** [comment]
Try gabbing an equation from the katex docs: 

```
$$
c = \pm\sqrt{a^2 + b^2}
$$
```

Should be working in the next insiders (Thursday)

**Comment by weinand** [comment]
Works fine for me:

<img width="1254" alt="2021-06-30_15-45-27" src="https://user-images.githubusercontent.com/1898161/123971472-5c437000-d9ba-11eb-9aa2-2578c69ae243.png">

**Comment by Yue-Zhengyuan** [comment]
Will VS Code natively support KaTeX custom macros [see this documentation](https://katex.org/docs/options.html) in near future? (Although there exists 3rd party extensions [like this one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) providing this feature.)
