### ISSUE TITLE
repeated Luna Paint entries in open with quick pick menu

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#124779]
![recording - 2021-05-27T115859 392](https://user-images.githubusercontent.com/29464607/119882146-ed6a8700-bee2-11eb-9c57-8e7a5cd57af2.gif)

**Comment by Tyriar** [comment]
Likely due to custom editors that can handle multiple file types:

```json
		"customEditors": [
			{
				"viewType": "luna.editor",
				"displayName": "Luna Paint Image Editor",
				"priority": "default",
				"selector": [
					{ "filenamePattern": "*.bmp" },
					{ "filenamePattern": "*.ico" },
					{ "filenamePattern": "*.png" },
					{ "filenamePattern": "*.jpg" },
					{ "filenamePattern": "*.jpeg" }
				]
			}
		],
```

**Comment by lramos15** [comment]
Do you have anything in your setting for luna paint? I'm trying to reproduce this using the latest version of luna paint and a similar image file in vscode-docs but I only seem to get one entry.

**Comment by Tyriar** [comment]
<img width="638" alt="Screen Shot 2021-06-01 at 7 45 36 AM" src="https://user-images.githubusercontent.com/2193314/120343182-5b30fd00-c2ad-11eb-9cda-6080ed9715c0.png">

Here are my settings:

```
  "workbench.editorAssociations": {
    "*.{bmp,ico,jpg,jpeg,png}": "luna.editor",
    "*.webp": "luna.editor",
    "*.jpe": "luna.editor"
  }
```
