### ISSUE TITLE
Open recent file option

### ISSUE THREAD

**Issue by EthraZa** [Microsoft/vscode#12475]
I would like to see an "Open recent file" (within folder/project). 
I got used to use the Git tab for this, but just until commit, after commit, I'm sold.

After commit and close all opened files, if I need to make a quick fix, I got remember the files I was messing with. If we had an "Open recent file" or "Recent Activity" that would be very handy.

**Comment by chrmarti** [comment]
There is File > Open Recent. Does that not address your case?

**Comment by EthraZa** [comment]
"File > Open Recent" opens a project folder. I was thinking more like an "Open Recent Tab". Something like browsers reopen recent closed tab feature, so I can reopen recently edited files.

The git tab kind of give me this, the recent edited files, but after commit, it's gone, so a more permanent menu under File, that tracks the last opened/edited files inside a project folder would be awesome.

**Comment by chrmarti** [comment]
The list includes recent files outside of any opened folder, but not recent files within an opened folder. We'll track this as a feature request for that. Thanks.

**Comment by bpasero** [comment]
@EthraZa there is File > Open Recent > Reopen Closed Editor to restore one by one and then there is the global history of editors every opened which might come in more handy for you (Cmd+P):

<img width="648" alt="screen shot 2016-10-05 at 18 26 27" src="https://cloud.githubusercontent.com/assets/900690/19122086/3ff94760-8b29-11e6-8963-8407681734c2.png">

I believe this should cover that request, closing.
