### ISSUE TITLE
& added to command to run python code in terminal

### ISSUE THREAD

**Issue by mnrao2001** [microsoft/vscode#124763]
Latest version of VS CODE with Python Extension
Issue: 
(base) C:\dock_python>& C:/<directory>/python.exe c:/<directory>/server.py
& was unexpected at this time.

Reproduce step:
Click on play button "Run Python File in Terminal"

**Comment by IllusionMH** [comment]
/extPython

Also duplicate of https://github.com/microsoft/vscode-python/issues/16175
