### ISSUE TITLE
c file automatically changing to c++ while saving

### ISSUE THREAD

**Issue by Youvan-Kumar-E** [microsoft/vscode#124777]
Issue Type: <b>Bug</b>

While saving a C file named "Problem33" it is automatically changing to C++ file. It is not saved as a c file even if i give the extension as '.c' . It is changing to a C++ file automatically. This problem arises only when the file name is "Problem33" and not happening with any other name.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.08GB free)|
|Process Argv|--crash-reporter-id ca07d241-1a6a-481a-a25a-20869ea100ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.4
cpptools|ms-|1.4.0-insiders3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30302759
bridgeflight:30302069
vscod805cf:30301675

```

</details>

![WhatsApp Image 2021-05-27 at 23 36 56](https://user-images.githubusercontent.com/77888726/119876592-ae215200-bf45-11eb-87f9-e36f0d0d9d20.jpeg)
![WhatsApp Image 2021-05-27 at 23 37 35](https://user-images.githubusercontent.com/77888726/119876598-b083ac00-bf45-11eb-818e-62f16f593452.jpeg)
![WhatsApp Image 2021-05-27 at 23 44 46](https://user-images.githubusercontent.com/77888726/119876608-b1b4d900-bf45-11eb-8061-da0db9e75d25.jpeg)

**Comment by dbaeumer** [comment]
@isidorn you once demoed some auto mode suggestion. Could this be caused by this. If no, please forward to the C++ team.
