### ISSUE TITLE
Consider to rename `registerContributionPoint`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124762]
I find the name `registerContributionPoint` a bit misleading because to me it sounds like I would register a new contribution point to the workbench that others can contribute to?

How about `IEditorOverrideService#registerOverride`?

**Comment by bpasero** [comment]
Or to be future proof, `IEditorOverrideService.registerEditor`.

**Comment by lramos15** [comment]
I got rid of the idea of a contribution completely. Let me know if you like the new names

**Comment by bpasero** [comment]
Yeah I like that. still a few "contributed..." things though:

![image](https://user-images.githubusercontent.com/900690/121127127-99886800-c829-11eb-97ed-0d9cc00a3d40.png)

**Comment by lramos15** [comment]
I kind of liked those ones but I can rename them as well to be Registered instead of Contributed

**Comment by bpasero** [comment]
Yeah I like "registered" 👍
