### ISSUE TITLE
Cannot disable font ligatures

### ISSUE THREAD

**Issue by Jeffrey-kerson** [microsoft/vscode#124718]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: MacOS BigSur 11.2.2

Steps to Reproduce:

1. Install and set the font Iosevka Extrabold

Even though I have turned the option `"editor.fontLigatures": false` to false and have restarted my VSCode several time the font ligatures still appear for all symbols, meaning they are not disabled as specified.

**Comment by Jeffrey-kerson** [comment]
@alexdima this didn't help me unfortunately

**Comment by alexdima** [comment]
@Jeffrey-kerson 

When you configure `"editor.fontLigatures": false`, we actually define `"editor.fontLigatures": "'calt' off, 'liga' off"`. Some fonts have more font features on by default. You can try:
```
"editor.fontLigatures": "'calt' off, 'dlig' off"
```
You can experiment by yourself and turn off font features until you turn off the one that is bothering you. You can find all the font features supported by the font here -- https://github.com/be5invis/Iosevka
