### ISSUE TITLE
API findFiles exclude argument default value is not clear

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#124724]
The default exclude of `vscode.workspace.findFiles` when the value is `undefined` isn't clear.
> When `undefined` only default excludes will apply

Is it a user setting?  Pre-defined value in the code somewhere?
Reading some of the git blame, and mentioned issues, it looks like `default` means the users `files.exclude` setting.  I didn't look at the actual implementation to confirm this.

Could the doc be updated to be more understandable?

https://github.com/microsoft/vscode/blob/e3c8ff57849bf854e97abd0d1b78ba5a92d3a801/src/vs/vscode.d.ts#L10489-L10506

**Comment by roblourens** [comment]
There are some folders that we exclude by default (like `.git`), and the user's excludes will also be applied here. Tweaked the description a little to include that.
