### ISSUE TITLE
delay before window paint on X11 when changing workspaces

### ISSUE THREAD

**Issue by JasonWoof** [microsoft/vscode#124744]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Debian unstable

Steps to Reproduce:

1. run vscode under X11 (linux's old/standard display server). This bug is not reproducible under Wayland. You might need to run this in some sort of session with no compositor. I'm not sure. I run dwm with no compositor.
2. use keyboard shortcuts to switch between workspaces, ie between a workspace with the vscode window in it and one without.

What happens: There is a delay before the vscode window is drawn. Normally this delay is 100ms - 500ms. If it was always within that range, I would have just assumed that vscode is just slow, but occasionally I'll get a delay in the 1s-5s range, and on rare occasion I get delays in the 10s-30s range (yes, it's lasted over 20 seconds before).

To be clear, when I say that it's not drawing it's window, I don't mean that the window is blank or showing outdated vscode pixels, I mean that vscode has not put pushed any pixels to the display for it's window rectangle, and so that rectangle shows whatever pixels where in that part of the framebuffer in from the previous workspace.

During some of the rare occurrences where I got an excruciatingly long delay, I was able to do some experiments and discovered that:

Clicking in the window doesn't seem to get it to paint.

I checked `top` and vscode doesn't appear to be using any appreciable amount of CPU power during the delays (at least during the big ones).

If you have any trouble reproducing this issue, please let me know if there's anything I can do to help with reproducing, experiments I could to to narrow it down to what's causing this, additional info I could gather, etc.

Thanks!

**Comment by JasonWoof** [comment]
Additional info:

This has been happening for several months, across multiple versions of vscode.

I've just done some experimenting with window sizes and focus.

Normally I have the window drawn with no decorations/border, and the dimensions of the window are exactly the same as the size of my screen, so it looks very much like a fullscreen mode, except I can still have floating windows on top of it.

Normally I run vscode in its own workspace, so when I'm reproducing this bug, it has keyboard focus (because it's the only window, it's the active window.)

I tried resizing the window slightly smaller, so some of the desktop background showed through, and this produces no change.

I tried opening up another window in tiling mode so vscode only got half the screen. In this mode vscode drew acceptably fast.

Now here's the super interesting one:

I tried leaving vscode in the usual whole-screen size, and put a tiny terminal window floating above it (only enough space for three rows and 10 characters wide). then with my workspace switching tests: When the keyboard focus is on the tiny terminal window, vscode paints its window right away. But when the keyboard focus is on vscode, then this bug rears it's ugly head consistently.


I've created some logs with `xev` that I hope will give some clues!

First to put xev in place of vscode in the configuration that makes this bug reproducible:

When xev has keyboard focus, and I switch workspaces away and then back, I get the following output with xev:

```
FocusOut event, serial 32, synthetic NO, window 0x5a00001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 32, synthetic NO, window 0x5a00001,
    mode NotifyWhileGrabbed, detail NotifyAncestor

VisibilityNotify event, serial 32, synthetic NO, window 0x5a00001,
    state VisibilityUnobscured

Expose event, serial 32, synthetic NO, window 0x5a00001,
    (285,0), width 1635, height 1080, count 0

ConfigureNotify event, serial 32, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (-3840,0), width 1920, height 1080,
    border_width 0, above 0x6800001, override NO

VisibilityNotify event, serial 32, synthetic NO, window 0x5a00001,
    state VisibilityFullyObscured

LeaveNotify event, serial 32, synthetic NO, window 0x5a00001,
    root 0x7a5, subw 0x0, time 869531922, (4066,575), root:(226,575),
    mode NotifyNormal, detail NotifyAncestor, same_screen YES,
    focus YES, state 64

FocusIn event, serial 32, synthetic NO, window 0x5a00001,
    mode NotifyWhileGrabbed, detail NotifyAncestor

KeymapNotify event, serial 32, synthetic NO, window 0x0,
    keys:  29  16  0   0   0   0   0   0   4   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

ConfigureNotify event, serial 32, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (0,0), width 1920, height 1080,
    border_width 0, above 0x6800001, override NO

VisibilityNotify event, serial 32, synthetic NO, window 0x5a00001,
    state VisibilityUnobscured

Expose event, serial 32, synthetic NO, window 0x5a00001,
    (0,0), width 1920, height 10, count 3

Expose event, serial 32, synthetic NO, window 0x5a00001,
    (0,10), width 10, height 58, count 2

Expose event, serial 32, synthetic NO, window 0x5a00001,
    (68,10), width 1852, height 58, count 1

Expose event, serial 32, synthetic NO, window 0x5a00001,
    (0,68), width 1920, height 1012, count 0

EnterNotify event, serial 32, synthetic NO, window 0x5a00001,
    root 0x7a5, subw 0x0, time 869532587, (226,575), root:(226,575),
    mode NotifyNormal, detail NotifyAncestor, same_screen YES,
    focus YES, state 64

KeymapNotify event, serial 32, synthetic NO, window 0x0,
    keys:  68  16  0   0   0   0   0   0   4   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

VisibilityNotify event, serial 32, synthetic NO, window 0x5a00001,
    state VisibilityPartiallyObscured

ConfigureNotify event, serial 32, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (0,0), width 1920, height 1080,
    border_width 0, above 0x6000001, override NO

ConfigureNotify event, serial 32, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (0,0), width 1920, height 1080,
    border_width 0, above 0x6000001, override NO

FocusOut event, serial 32, synthetic NO, window 0x5a00001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 32, synthetic NO, window 0x5a00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 32, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   0   4   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```



Second, I put xev in place of vscode in the configuration that vscode behaves bug-free:

When I have a terminal window floating above vscode, and the terminal window has focus when I switch workspaces away and back I get this:


```
ConfigureNotify event, serial 33, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (-3840,0), width 1920, height 1080,
    border_width 0, above 0x6800001, override NO

VisibilityNotify event, serial 33, synthetic NO, window 0x5a00001,
    state VisibilityFullyObscured

ConfigureNotify event, serial 33, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (0,0), width 1920, height 1080,
    border_width 0, above 0x6800001, override NO

VisibilityNotify event, serial 33, synthetic NO, window 0x5a00001,
    state VisibilityPartiallyObscured

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (0,0), width 1920, height 10, count 6

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (0,10), width 10, height 58, count 5

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (68,10), width 1852, height 58, count 4

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (0,68), width 1920, height 1, count 3

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (0,69), width 291, height 948, count 2

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (1822,69), width 98, height 948, count 1

Expose event, serial 33, synthetic NO, window 0x5a00001,
    (0,1017), width 1920, height 63, count 0

ConfigureNotify event, serial 33, synthetic NO, window 0x5a00001,
    event 0x5a00001, window 0x5a00001, (0,0), width 1920, height 1080,
    border_width 0, above 0x6400001, override NO
```

I hope seeing the contrast between those event lists is helpful. The only thing that jumps out at me is that in the first log (which is probably similar to what vscode gets when it's bugging) there are no `Expose` events after the final `VisibilityNotify` event.

**Comment by deepak1556** [comment]
Window painting is performed by Chromium, closing as not actionable.
