### ISSUE TITLE
Error when trying to run `code` from within terminal on Remote-Container

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#124747]
Issue Type: <b>Bug</b>

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.vscode-server/data/User/workspaceStorage/c2d18fd137868c0d2343f327e8b88e4b/ms-vscode.js-debug/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0
Remote OS version: Linux x64 4.14.231-173.361.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|16.00GB (0.91GB free)|
|Process Argv|--crash-reporter-id 264c6684-aed1-41ee-b66d-1798647db0f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:b0047e733f773189295fe8a0decceb3ee86252ec4fac0f323b54fd82d6334aed (/nk-dev-conn_pm2_1) @ aws-docker|
|OS|Linux x64 4.14.231-173.361.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (8.10GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.177.2
vscode-openapi|42C|4.5.1
atlascode|atl|2.8.6
npm-intellisense|chr|1.3.1
regex|chr|0.4.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
bash-ide-vscode|mad|1.11.0
mongodb-vscode|mon|0.5.0
compare-folders|mos|0.22.0
vscode-yaml|red|0.19.2
vscodeintellicode|Vis|1.2.14

</details>

**Comment by connor4312** [comment]
You should be able to fix this by running the `Toggle Auto Attach` command and setting it to `Disabled`.

I'm not sure how to reproduce the problem, though. Is this a new VM you connected to, or did you connect to it before in a different way or on a different version of VS Code?

**Comment by navneetkarnani** [comment]
I had to delete all of my VS Code settings, and the installation, to get rid of this. Essentially, back to factory reset.
