### ISSUE TITLE
Add InlineValueProvider for TS/JS

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#124721]
https://github.com/microsoft/TypeScript/issues/43449

**Comment by connor4312** [comment]
Adding you Matt since the TS team implemented this and is pending review into VS Code

**Comment by mjbvz** [comment]
TS is targeting this for TypeScript 4.5 right now so moving this out to September

**Comment by mjbvz** [comment]
Closing as upstream. Will continue tracking on TS side
