### ISSUE TITLE
Custom editor and maximized panel

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#124766]
Issue Type: <b>Bug</b>

1. Have no editor opened
1. Open panel (Terminal, for instance) and maximize it
1. Reload window
1. Click on any image file in file explorer to open custom editor

![__](https://user-images.githubusercontent.com/9638156/119863519-51607000-bf22-11eb-9ce5-75d46afde819.png)

VS Code version: Code (1.56.2), Code - Insiders 1.57.0-insider (1082913dd012e21cc5f35a06f15c480ca447f67f, 2021-05-27T06:55:24.593Z)
OS version: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
Hm, I can't see to reproduce this in 1.57. Clicking on the image always forces the terminal out of maximized mode

Are you seeing still this in current insiders builds?

**Comment by usernamehw** [comment]
Yes. Perhaps it only works when no editor was opened. Updated the steps.

![Animation](https://user-images.githubusercontent.com/9638156/121767616-efc71500-cb61-11eb-83d3-e2d68a3a5444.gif)

**Comment by usernamehw** [comment]
@mjbvz

**Comment by usernamehw** [comment]
Can't reproduce exactly as in gif in current insiders 7dea6d7402b55671410a129661cad24b55aed9f4 but with the same repro steps it doesn't load image at all.

**Comment by usernamehw** [comment]
Doesn't reproduce anymore in Insiders.
