### ISSUE TITLE
Developing for multi-core and heterogeneous devices

### ISSUE THREAD

**Issue by onyx22574** [microsoft/vscode#124773]
Hello guys,

is there a possibility to use vs-code as IDE for multi-core and heterogeneous devices? So I could use a single IDE for Cortex-M, Cortex-A for heterogeneous devices such as [arm-development-studio](https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/heterogeneous-made-easy-arm-development-studio)

**Comment by IllusionMH** [comment]
VS Code doesn't support C and C debugging out of the box, however it's extensible and you can look for corresponding extensions in Marketplace: https://marketplace.visualstudio.com/vscode

Also check https://code.visualstudio.com/docs/languages/cpp for more info

**Comment by dbaeumer** [comment]
Closing the issue since this as @IllusionMH mentioned is an extension opportunity.
