### ISSUE TITLE
Native Linux repository packages?

### ISSUE THREAD

**Issue by tromlet** [microsoft/vscode#124708]
It’d be rad if you guys could put those fancy, pre-packaged .deb and .rpm files into appropriate repositories so that we could just download them onto our systems without having to manually download them to get updates. :>

The Snap option is nice, but Snap doesn’t play that nicely with the native environment of almost any Linux system OTHER than Ubuntu… and I mean… I figure if you’re ALREADY creating the .deb and .rpm packages… like, how hard could it be to throw those up on a repo and make it so that RHEL / Debian users could get updates through their package manager :?

**Comment by joaomoreno** [comment]
Both deb and rpm are in repositories already. Just follow the docs: https://code.visualstudio.com/docs/setup/linux
