### ISSUE TITLE
PHP Syntax highlight wrong

### ISSUE THREAD

**Issue by jpenna** [microsoft/vscode#124761]
Issue Type: <b>Bug</b>

It is apparently fixed in the nightly release.
Could you send a minor release to fix this issue, please?

> After the `... AS c';` everything is highlighted as a heredoc

<img width="454" alt="Screen Shot 2021-05-27 at 11 38 14 AM" src="https://user-images.githubusercontent.com/16005946/119846197-4e449000-bee0-11eb-9af6-58d933903651.png">

Reproduce (copy to a PHP formatted file):

```
<?php

namespace My;

class MyClass
{
	protected function count()
	{
		$sql = 'SELECT FOUND_ROWS() AS c'; // `c;` works and `select` lower case too
		$result = $this->database->fetchArraySingle($sql);
		return $result['c'];
	}

	public function doSomething($past, $new)
	{
		$sql = <<<SQL
			UPDATE online_gift
			SET individual_id = :past
			WHERE individual_id = :new
		SQL;

		return $this->database->execute($sql, [
			':past' => $past,
			':new' => $new,
		]);
	}
}
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id b8a0d0d7-4b5b-43ca-841e-088dca241915|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cucumberautocomplete|ale|2.15.1
vscode-apollo|apo|1.19.3
vscode-intelephense-client|bme|1.7.1
vscode-toggle-quotes|Bri|0.3.4
path-intellisense|chr|2.3.0
postcss|css|1.0.9
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
restore-editors|eam|0.2.1
vscode-npm-script|eg2|0.3.21
vscode-great-icons|emm|2.1.74
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
vscode-pull-request-github|Git|0.26.0
vscode-graphql|Gra|0.3.16
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
path-autocomplete|ion|1.17.1
mysql-syntax|jak|1.3.1
cypher-query-language|jak|1.0.2
git-graph|mhu|1.30.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
vscode-typescript-tslint-plugin|ms-|1.3.3
color-highlight|nau|2.3.0
ruby|reb|0.28.1
jinjahtml|sam|0.16.0
mdx|sil|0.1.0
code-spell-checker|str|1.10.2
mako|tom|0.2.0
alphabetical-sorter|ue|2.0.1
vscode-icons|vsc|11.4.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by jpenna** [comment]
Seems related to this one from 1 year ago https://github.com/microsoft/vscode/issues/48096

**Comment by roblourens** [comment]
> It is apparently fixed in the nightly release.
> Could you send a minor release to fix this issue, please?

Thanks for verifying that it's fixed in Insiders. We won't do a new stable release for this issue, but the next stable release will be in a couple weeks.
