### ISSUE TITLE
Test: Terminal profile contributions API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124793]
Refs: https://github.com/microsoft/vscode/pull/120369

- [x] macOS @sandy081
- [x] linux @JacksonKearl
- [x] windows @connor4312 

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124793%0A%0A)

---

There's a new proposed API that allows contributing terminal profiles, note that this is replacing the old terminal "types" API that js-debug uses. To test, use the [terminal-sample](https://github.com/Microsoft/vscode-extension-samples/tree/main/terminal-sample) and [external-terminal-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample) APIs to contribute new profiles, they should show up in the terminal's new terminal dropdown and and `Create New Terminal Integrated Terminal (With Profile)` command. For example:

```ts
context.subscriptions.push(vscode.window.registerTerminalProfileProvider('my-ext.terminal-profile', {
	provideProfileOptions(token: vscode.CancellationToken): vscode.ProviderResult<vscode.TerminalOptions | vscode.ExtensionTerminalOptions> {
		// Try out several options, as well as contributing { name, pty } options
		return { name: 'Profile from extension', shellPath: 'cmd.exe' };
	}
}));
```

When a profile is activated it will fire a new `onTerminalProfile` activation event:

```json
"activationEvents": [
	"onTerminalProfile:my-ext.terminal-profile"
],
"contributes": {
	"terminal": {
		"profiles": [
			{
				"title": "Profile from extension",
				"id": "my-ext.terminal-profile"
			}
		]
	},
}
```

**Comment by sandy081** [comment]
Fixed the `activationEvent` in the description to use the profile id.

**Comment by connor4312** [comment]
Tested by adopting it in js-debug 🙂
