### ISSUE TITLE
Output for Code Settings Sync keeps stealing focus

### ISSUE THREAD

**Issue by bcardarella** [microsoft/vscode#124720]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Mac OS 11.2.2

Steps to Reproduce:

1. I have settings sync enabled, and I prefer to have the `TERMINAL` tab be in focus
2. periodically the `OUTPUT` tab will steal focus from `TERMINAL` with the result of a Settings Sync
3. This continues to happen over and over

**Comment by sandy081** [comment]
It does not happen to me - Settings Sync output view is not stealing focus. Can you please try disabling installed extensions ?
