### ISSUE TITLE
Ability to add custom context menu extension to documents opened using OpentTextDocument

### ISSUE THREAD

**Issue by SteveCurran** [Microsoft/vscode#12471]
I am looking to add a custom context menu item to a json document I create using OpenTextDocument. It seems that the context are only available for editor files and the explorer window. 
Thanks.

**Comment by jrieken** [comment]
You control that with the `when`-clause. Check out [this](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L74) which add buttons to explorer context menu and editor title. For the editor context menu use the `editor/context` menu. Last, there is this doc: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by SteveCurran** [comment]
Yes I tried all that and it works in an editor window but not in a json file displayed using OpenTextDocument. These documents are set to read only could that be the problem? It appears we very limited on what we can do with documents displayed using OpenTextDocument.

**Comment by jrieken** [comment]
> displayed using OpenTextDocument. 

Not sure what you meant by that? The API [openTextDocument](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3713) doesn't display anything but just loads a document into memory

**Comment by jrieken** [comment]
Also, it would help if you can provide a pointer to your `package.json` which declares the contribution

**Comment by SteveCurran** [comment]
Sorry for the confusion. I am using openTextDocument and then displaying the in memory document with showTextDocument.

```
"contributes": {
        "commands": [
            {
                "command": "extension.spremoteapi",
                "title": "SPRemoteAPI"
        }],
        "menus":{
            "editor/context":[{
            "when":"resourceLangId == json",
            "command":"extension.spremoteapi"}
        ]
        }
    }
```

**Comment by jrieken** [comment]
hm, looking not to bad. Can to try without the `when`-clause? It should always show. Also any warnings on the developer tools console?

**Comment by SteveCurran** [comment]
Yes it shows up after removing the when clause. Nothing in the console. I am using the TextDocumentContentProvider. It would be nice to be able to send in a custom resourceLangId to use in the when clause. Unfortunately you can only send in the content.

**Comment by jrieken** [comment]
The resource lang id is derived from the filename (so the URI) or/and the contents. So, a `foo:bar.json` URI should be associated with `json`. Also, you can define your own languages as shown here: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages. Last, you might wanna use the `resourceScheme` like [so](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L82)

**Comment by SteveCurran** [comment]
Below is some example code of what I am doing to create content and show it. 

```
vscode.workspace.registerTextDocumentContentProvider("remotescheme",
        {provideTextDocumentContent(uri){
            return "{'prop1':'whatever'}";
        }
        });

let uri = vscode.Uri.parse('remotescheme:///properties.json');        
        vscode.workspace.openTextDocument(uri).then(doc=>{
        vscode.window.showTextDocument(doc,vscode.ViewColumn.Two);  
             return;
        });

```
The only context menu shown when calling showTextDocument is "Copy". This will not pickup any when clause.
