### ISSUE TITLE
Collapse or grey out settings options unrelated to the user's OS

### ISSUE THREAD

**Issue by damian66** [microsoft/vscode#124798]
### Environment
VSCode version: **1.56.2**
Operating system: **macOS Big Sur 11.2.3**

### Description
My suggestion is to **grey out, collapse or even hide editor settings** that will not make any changes to the **current environment**. I noticed that under the **Terminal** section, there are settings for different operating systems. Making changes should not make any difference.
It could improve the editor's user experience if settings options that do not make any difference in the current environment could be greyed out. This would allow the developer to focus on settings that he is mostly interested in.

I understand that settings can be shared between computers or even operating systems so I do not suggest hide them from the UI but rather reduce text opacity or collapse them (so that users can expand and view or modify).

### Screenshot
Take a look at the screenshot from the Settings view. I am using macOS and please notice settings for other operating systems.

<img width="420" alt="Screenshot 2021-05-28 at 04 38 22" src="https://user-images.githubusercontent.com/2499935/119922310-dde54f80-bf6f-11eb-8403-2f73934ca6ea.png">

**Comment by cburnett707** [comment]
> ### Environment
> VSCode version: **1.56.2**
> Operating system: **macOS Big Sur 11.2.3**
> 
> ### Description
> My suggestion is to **grey out, collapse or even hide editor settings** that will not make any changes to the **current environment**. I noticed that under the **Terminal** section, there are settings for different operating systems. Making changes should not make any difference.
> It could improve the editor's user experience if settings options that do not make any difference in the current environment could be greyed out. This would allow the developer to focus on settings that he is mostly interested in.
> 
> I understand that settings can be shared between computers or even operating systems so I do not suggest hide them from the UI but rather reduce text opacity or collapse them (so that users can expand and view or modify).
> 
> ### Screenshot
> Take a look at the screenshot from the Settings view. I am using macOS and please notice settings for other operating systems.
> 
> <img alt="Screenshot 2021-05-28 at 04 38 22" width="420" src="https://user-images.githubusercontent.com/2499935/119922310-dde54f80-bf6f-11eb-8403-2f73934ca6ea.png">
