### ISSUE TITLE
Need to more highlight a tab for a file which is open and selected.

### ISSUE THREAD

**Issue by dhara15101991** [microsoft/vscode#124746]
Issue Type: <b>Feature Request</b>

Hello,

I am using visual code from last 4 months and I loved it. It is so smooth. I loved all things about it. I only have one issue about the file highlight when it is selected. Currently If there is 5 files are open then it is hard to identify which file is currently selected on tab. Active Tab color is so matched with others then cannot identify easily.

Please either lighten the other tabs color which is not selected or do something else.

Thanks

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 4.15.0-142-generic

**Comment by IllusionMH** [comment]
You can set colors you prefer for active tab using
```json
"workbench.colorCustomizations": {
    "tab.activeBackground": "#660000",
    "tab.activeForeground": "#00FF00",
}
```
and other `tab.*` properties

/cc @bpasero @aeschli

**Comment by dhara15101991** [comment]
Thanks. It worked
