### ISSUE TITLE
Crashpad Major Disk Usage

### ISSUE THREAD

**Issue by kroseRipen** [microsoft/vscode#124713]
Issue Type: <b>Performance Issue</b>

I'm using:
MacBook Pro (15-inch, 2018)
CPU: 2.2 GHz 6-Core Intel Core i7
Memory: 16 GB 2400 MHz DDR4
OS: Big Sur 11.3.1 (20E241)

I started getting warnong messages of low hard drive space. After running a scan with a tool Disk Inventory X it was discovered there was SIGNIFICANT (80Gbs) disk usage under path: /Library/Application Support/Code/Crashpad.
completed - 48gb
pending - 31.9gb

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id aa9d5fb2-1faa-4863-a68d-5269674de962|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   115	 79203	code main
    2	    49	 79249	   gpu-process
    0	     0	 79257	   utility
    2	    49	 79548	   shared-process
    0	     0	 79573	     ptyHost
    0	     0	 32400	       /bin/zsh -l
    0	     0	 33130	       /bin/zsh -l
    0	     0	 65439	       /bin/zsh -l
    0	     0	 96898	       /bin/zsh -l
    0	     0	 97430	       /bin/zsh -l
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (.editorconfig — alp)
|  Window (ConvertCampaign.js — scent-beauty-discount-app)
|  Window (ripenCart.js — scent-beauty-shopify)
|    Folder (scent-beauty-discount-app): 231 files
|      File types: js(127) scss(22) json(5) example(4) gitignore(3) md(3)
|                  html(3) nvmrc(2) png(2) ts(2)
|      Conf files: package.json(3)
|    Folder (scent-beauty-shopify): 957 files
|      File types: liquid(533) js(108) png(86) scss(75) svg(50) jpg(20) css(8)
|                  json(7) DS_Store(5) woff(2)
|      Conf files: package.json(1)
|    Folder (alp): more than 20305 files
|      File types: php(8260) xml(2395) js(664) phtml(281) csv(272) html(215)
|                  css(208) png(147) json(108) md(85)
|      Conf files: settings.json(2) eslint.json(1);
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
atlascode|atl|2.8.6
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
magento2-extension-pack|jer|0.1.0
magento2-snippets|jer|0.1.2
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.3
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
php-docblocker|nei|2.1.0
language-liquid|nei|0.1.1
vetur|oct|0.33.1
material-icon-theme|PKi|4.7.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
shopify-liquid|sis|2.3.0
svelte-vscode|sve|104.13.0
twig|wha|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by pascallapradebrite4** [comment]
I have the exact same problem.

My `completed` folder is 20.43 GB in size and with the rest of my hard drive content, by the end of my workday, this was enough to get down to 72mb of disk space remaining, forcing me to kill everything, restart. I then investigated what would take so much IO and found `~/Library/Application Support/Code/Crashpad` to be the culprit.

There are 105,780 `.dmp` files, all created the same day (today). That would be more than 10,000 dmps per hour.

My specs are similar to the original poster:

MacBook Pro (15-inch, 2019)
CPU: 2,3 GHz 8-Core Intel Core i9
Memory: 16 GB 2400 MHz DDR4
OS: Big Sur 11.4 (20F71)

VS Code version: Code 1.57.1
OS version: Darwin x64 20.5.0

I have the following extensions in common with the original poster:

- vscode-eslint
- vscode-intelephense-client
- gitlens

**Comment by deepak1556** [comment]
Please attach some of the recent crash dumps generated, it will help identify what is causing these. Thanks!

**Comment by pascallapradebrite4** [comment]
Hi @deepak1556 , thanks for your help!

Here are some that I saved (tell me if you need more! I still have ~700 of them around, though they're pretty much around the same time, I deleted the rest to get back some disk space):

12 .dmp files: [dmps.zip](https://github.com/microsoft/vscode/files/6736435/dmps.zip)

**Comment by deepak1556** [comment]
@pascallapradebrite4 based on the logs, the issue you are facing is same as https://github.com/microsoft/vscode/issues/127392. Please follow the next steps attached there. Thanks!

**Comment by deepak1556** [comment]
@kroseRipen can you also attach the latest crash dumps, as I don't see dotnet extension in your list. You might be having a different issue. Thanks!

**Comment by pascallapradebrite4** [comment]
@deepak1556 Awesome, thanks!

Turned off crash reports for the time being, and I'll open a report in the `vscode-dotnet-runtime` extension repo tomorrow if #127392 's OP didn't do it yet.

**Comment by winzig** [comment]
@pascallapradebrite4 Opened an issue here: https://github.com/dotnet/vscode-dotnet-runtime/issues/252

**Comment by deepak1556** [comment]
Closing as issue is outside vscode core.
