### ISSUE TITLE
cout is ambigous

### ISSUE THREAD

**Issue by saralouk** [microsoft/vscode#124781]
Issue Type: <b>Bug</b>

Error: cout is ambiguos

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.42GB free)|
|Process Argv|--crash-reporter-id 4103e2c0-420d-4a09-931c-ad1fdd2d2f31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.4
cpptools|ms-|1.4.0-insiders3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by IllusionMH** [comment]
/question

Most likely this is an error in your code. Try to search by error message.

However if it's not an issue with code - this error comes from C++ extension so it should be reported in extension repo.
