### ISSUE TITLE
Refactor > Rename (F2) causes system wide instability

### ISSUE THREAD

**Issue by sameera** [microsoft/vscode#124730]
Issue Type: <b>Bug</b>

1. Run VS Code disabling all extensions (to isolate this issue to the VS Code core and not extensions)
2. Open an Angular project (I have/can test only with Angular)
3. Press F2 to rename a class/interface/variable

### Observed result
1. Clicking on any symbol in the code editor brings up the refactor prompt.
2. It also keeps flashing "you cannot rename this element" message
3. Outside of VS Code, iTerm starts beeping if you try to interact with it.
4. Even OSX menus behave erratically. 

In the attached video this happens on the 2nd attempt of renaming. Almost of the time, it is reproducible on first attempt.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 5df7e9fe-b0e7-48cf-a722-9e9c9b94bfe0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
vscode-great-icons|emm|2.1.74
simple-new-file|fay|1.1.2
vscode-pull-request-github|Git|0.26.0
vscode-test-explorer|hbe|2.20.1
Angular2|joh|11.0.0
docomment|k--|0.1.20
vscode-jest-test-adapter|kav|0.8.1
git-graph|mhu|1.30.0
csharp|ms-|1.23.12
azure-account|ms-|0.9.8
powershell|ms-|2021.2.2
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.3.1
advanced-new-file|pat|1.2.2
explorer-exclude-vscode-extension|Red|1.2.0
ms-teams-vscode-extension|Tea|2.0.1
todo-list|Tza|1.6.0
colonize|vms|2.2.2
vscode-icons|vsc|11.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by sameera** [comment]
Recording of the issue:

https://user-images.githubusercontent.com/208470/119761639-cb183f80-bec9-11eb-8625-cafa0449dd68.mp4

**Comment by mjbvz** [comment]
Does this also reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by sameera** [comment]
I will test and update within the day.

https://github.com/microsoft/vscode/issues/124750 may also be related to this one.

**Comment by sameera** [comment]
@mjbvz I was unable to repro this under the following config:

Version: 1.57.0-insider (Universal)
Commit: 4f3d865a6b46a4ead49cf83fe1c30d95d0a34220
Date: 2021-05-31T05:12:28.387Z (1 day ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by sameera** [comment]
This is still reproducible on the following config:

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by sameera** [comment]
@mjbvz Please reopen.
