### ISSUE TITLE
Visual Studio Code randomly crashing with "just-in-time debugging exception"

### ISSUE THREAD

**Issue by CastratedWalrus** [microsoft/vscode#124767]
Issue Type: <b>Bug</b>

I am unable to to provide the steps to reproduce the error as it seems completely random. It happens when running, opening folders, opening the app and getting extensions. vscode freezes for around 15 seconds the "Visual Studio Code is not responding" error. It then gives the option to debug, when I hit it, a window (in the screenshot) pops up.

apparently it had something to do with just-in-time debugger. but everytime I search for it, everyone is talking about visual studio, not visual studio code. therefore I am unable to follow the steps in order to disable it because the option isn't available

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E2-7110 APU with AMD Radeon R2 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.46GB (0.31GB free)|
|Process Argv|--crash-reporter-id 598f353a-ee21-425c-b7da-4979df166e41|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.4
go|gol|0.25.1
beautify|Hoo|1.5.0
kite|kit|0.143.0
theme-monokai-pro-vscode|mon|1.1.19
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.3.1
vscode-react-native|msj|1.5.0
vetur|oct|0.33.1
java|red|0.79.2
LiveServer|rit|5.6.1
pytorch-snippets|SBS|1.0.2
html5-boilerplate|sid|1.1.1
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.10.14

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30302760
bridgeflight:30302069
vscod805:30301674

```

</details>

![ERROR SCREENSHOT](https://user-images.githubusercontent.com/66955967/119859830-a2199e00-bf0d-11eb-8f9f-908934c9a6a9.png)

**Comment by CastratedWalrus** [comment]
Come to think of it, it might have something to do with the extensions. I doubt vscode would throw this error by itself, probably an extension is trying to activate a feature that doesn't exist. I'll look into it later

**Comment by deepak1556** [comment]
Can you attach the crash report following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
