### ISSUE TITLE
Remember chosen Environment per workspace / file

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#124770]
1. Have no `launch.json`
2. have a `hello.js` file with a simple `console.log` statement
3. Press F5
4. Notice the Environment picker, choose js-debug everything works
5.  Stop debugging.
6. Press F5 again. The picker shows again 🐛 

I think we should improve this. If debugging / running was successful we should remember the previous environment choice.
I think we should store this per workspace for the active file. Or even more aggressivly for the whole workpsace.

Point of this: reduce number of prompts and make debugging flow smoother.

@connor4312 @weinand what do you think?

![Screenshot 2021-05-27 at 18 09 16](https://user-images.githubusercontent.com/1926584/119860590-c5951680-bf16-11eb-9d4c-1729f9b66f8b.png)

**Comment by connor4312** [comment]
I think per-file is good. I don't think it's so good per workspace, e.g. lots of CS students have all their coursework in a single folder/workspace which might includes multiple languages/projects

**Comment by isidorn** [comment]
Good point. Per-file is a safe choice and a good start.

**Comment by weinand** [comment]
I like this idea - do we need a UI for resetting the remembered choice?
If users picked the wrong environment how can they fix that?

**Comment by isidorn** [comment]
@weinand workaround for picking the wrong env is creating a launch.json file which is a bit heavy but at least it would work.
Alternative is that we introduce a command which would clear this. Though I think the command would be hard to discover and in the end might not give us enough benefit.
Ideas welcome.

Anyways let's assign to this milestone so we think about this more and try to do it.

**Comment by luabud** [comment]
we can't add checkboxes to quick-picks, right? I was thinking maybe adding a "reuse configuration" option that could be enabled/disabled there might help? But figured it's likely not currently possible 

![image](https://user-images.githubusercontent.com/45497113/122813555-edfb0100-d287-11eb-9032-699b529ace0c.png)

**Comment by isidorn** [comment]
@luabud makes sense, but not currently possible with the quick pick api, and it also looks a bit alien compared to the other items. We can tune this "wrong choice" experience if we see users hitting this.

So I have done what we mentioned above: I am storing the selected environment per active editor only if debugging started successfully. This makes starting debugging smoother.
Here's how it looks in practice. Try it out and let me know what you think.

![recording](https://user-images.githubusercontent.com/1926584/123461039-d2c22580-d5e8-11eb-878b-28bdbaffe082.gif)

**Comment by isidorn** [comment]
I did not add a command to clear this. If somebody feels strongly about this let me know and I can add it. But I think it will be hardly discoverable and will only help people who complain on GitHub and we tell them how to clear...

**Comment by luabud** [comment]
@isidorn I have a Python Flask app open in VS Code and I got the environment options again after I hit run and debug for the second time, like in the GIF below 🤔  is it because I had  no file open? It's very much an edge case, so I'm not concerned, just figured I'd ask 😊 I was also able to verify that it works for JavaScript. 

![NewVSCodeRememberConfigBehavior2](https://user-images.githubusercontent.com/45497113/123719012-5d976000-d835-11eb-8a2a-0ab940af9795.gif)

**Comment by isidorn** [comment]
@luabud thanks for trying it out 👏 
Yeah it is because you had no file open. Our current strategy is to remember it per file. Motivation [here](https://github.com/microsoft/vscode/issues/124770#issuecomment-849775822)
If there is no active file then we do not remember anything.

If we want to improve this, we can say we also remember what is chosen for no file case. Though I would maybe add that later.

**Comment by rchiodo** [comment]
Verified it works as designed. But I immediately wanted the clear or someway to know what the value was. Maybe I picked the wrong the debugger the first time?

**Comment by luabud** [comment]
> If we want to improve this, we can say we also remember what is chosen for no file case. Though I would maybe add that later.

Agreed, I don't think it's a widespread use case anyway 😊

> But I immediately wanted the clear or someway to know what the value was. 

I had that feeling too and my natural instinct was to reload the window, and that did the trick! Not sure if others would have the same instinct, though.

**Comment by isidorn** [comment]
@rchiodo https://github.com/microsoft/vscode/issues/124770#issuecomment-855912045 and https://github.com/microsoft/vscode/issues/124770#issuecomment-868712331

p.s reload will not clear this. There was a bug which caused this that I fixed.
As mentioned above: I can add a command to clear this, but let's see if this actually happens in practice to our users.

**Comment by bersbersbers** [comment]
I am happy that remembering debug environments is finally being tackled. This implementation is far for a complete solution, though, as it seems to concern only the "no `launch.json`" case.

I have a workspace-specific `.vscode/launch.json` file, as well as two general launch configs in my `settings.json`, and there are two long-standing issues related to not remembering the last debug configuration in this setup (specifically, https://github.com/microsoft/vscode/issues/90216, the "second problem", and also https://github.com/microsoft/vscode/issues/100451) that could be solved using a very similar per-file memory.

When reading the most recent VS Code release notes:
> Sticky debug environment choice - Debugger remembers your previous environment choice.

I had hoped that these issues are also resolved - but it seems they are not. So:
1. Is there an open issue that tracks remaining issues with "remembering debug environments"?
2. Is my setup so unusual that the issues above will probably never be resolved? Should I change my setup?
3. Or will these issues be dealt with at some point?

**Comment by isidorn** [comment]
@bersbersbers thanks for feedback. Can you please create a new issue for your use case? Thanks

**Comment by bersbersbers** [comment]
> @bersbersbers thanks for feedback. Can you please create a new issue for your use case? Thanks

Thanks, done: https://github.com/microsoft/vscode/issues/129425
