### ISSUE TITLE
Migrate from gtk2 to gtk3 on Linux

### ISSUE THREAD

**Issue by peterwu** [microsoft/vscode#124727]
Currently, on at least Fedora Linux, the provided rpm has a dependency on `gtk2` and `ibus-gtk2`. With the introduction of gtk4, please consider migrating to at least `gtk3` as dependency for the vscode rpm. 

In terms of technical feasibility, the relevant packages in Arch Linux has gtk3 as dependency. So, I guess it should be relatively painless to do the same for rpm-based Linux distros.

Here is the AUR package for reference:
https://aur.archlinux.org/packages/visual-studio-code-bin

**Comment by deepak1556** [comment]
@Tyriar wasn't this completed as part of https://github.com/microsoft/vscode/issues/47158 ? Where is the gtk2 dependency declared ?

**Comment by peterwu** [comment]
The gtk2 dependency is pulled in because of `libgdk-x11`.

Here is a snippet from `dnf deplist code`:

```
  dependency: libgdk-x11-2.0.so.0()(64bit)
   provider: gtk2-2.24.33-4.fc34.x86_64
```

**Comment by deepak1556** [comment]
thanks for the clarification, looks like it was missed in the previous update. Marking as a bug, should switch to `libgdk-3`
