### ISSUE TITLE
Allow to escape icon syntax in extension labels

### ISSUE THREAD

**Issue by The-Compiler** [microsoft/vscode#124703]
For labels in extensions, using e.g. `$(rocket)` [results in an icon being displayed](https://code.visualstudio.com/api/references/icons-in-labels).

However, there seems to be no way to show the literal text `$(rocket)` in a label, i.e. escaping the icon syntax. This is relevant for the Vim extension, as it makes it impossible to e.g. search/replace icon codes using the Vim commandline input when developing an extension:

![image](https://user-images.githubusercontent.com/625793/119696915-f52d1b80-be4f-11eb-98e0-40407ee20638.png)

See https://github.com/VSCodeVim/Vim/issues/6655

**Comment by sandy081** [comment]
May I know where/which view in VS code this is being rendered?

**Comment by The-Compiler** [comment]
In the screenshot it's a `StatusBarItem`, but according to [the docs](https://code.visualstudio.com/api/references/icons-in-labels) the same would apply to hovers and QuickPickItems too

**Comment by bpasero** [comment]
`status.text = '\\$(rocket)';` should do it.

**Comment by The-Compiler** [comment]
Hm, that seems to work indeed. I thought I had tried that, but apparently not?

Thanks, closing this then. I opened https://github.com/microsoft/vscode-docs/pull/4603 to document this.
