### ISSUE TITLE
Getting Started page incorrectly references the Welcome Page

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#124794]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest Insiders
- OS Version: Windows (probably others)

Steps to Reproduce:

1. View the Help->Getting Started page

Bug: It shows 2 references to "Welcome Page" but that is a different page/UI (Help->Welcome).

![image](https://user-images.githubusercontent.com/19859882/119910529-2ec35c80-bf0c-11eb-8672-a62b32464503.png)

**Comment by sean-mcmanus** [comment]
I don't believe this is a duplicate of those issues.

**Comment by JacksonKearl** [comment]
Thanks, this is part of the general naming concern of deprecating Welcome in favor of Getting Started, then renaming Getting Started to "Welcome". So in the end this is the correct naming, but agree that it's out-of place right now.
