### ISSUE TITLE
Investigate adopting Prettier for VS Code

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#124765]
Prettier is an opinionated code formatter. Over the base TypeScript formatting, the primary advantage is that it removes almost all decision-making from the formatting process, which makes writing and reviewing code easier.

Adopting it wholesale in VS Code could be disruptive. We could make it smoother by adopting prettier for subsets of VS Code gradually across an iteration or two. This requires some work in our formatting settings and the prettier extension to apply and format a subset of code. If we decided not to implement prettier globally, we could have a permanent state where some folders are opted-in or opted-out of formatting.

aside: until I get around to finishing my PR to make prettier parallel by default, we can use https://github.com/microsoft/parallel-prettier for faster formatting

**Comment by hediet** [comment]
Some thoughts:

* Prettier with single quotation marks, tabs and semicolons is almost a strict specialization of our current style guide, i.e. everyone is free to use prettier for new code already.
    * Exceptions are single and double quotation marks - Prettier normalizes all of them to one or the other. This collides with our convention that `"foo"` is localizable whereas `'foo'` is not.
        * Maybe we can use `'` for all strings and mark localizable strings in a different way, e.g. with a function call?
* Prettier's only-format-modified-lines feature is broken in VS Code. It sometimes inserts random semicolons.
    * We can fix that.

**Comment by connor4312** [comment]
> Maybe we can use ' for all strings and mark localizable strings in a different way, e.g. with a function call?

Localization happens through the `localize` function. I think the usage of double quotes is just a convention to avoid having to escape apostrophes, which can also be avoided by using template literals instead (would need to make sure our loc pipeline picks up on this)

> everyone is free to use prettier for new code already. 

The annoying thing is that this can only be done (as far as I know) by manually choosing Format Document With > Prettier

**Comment by JacksonKearl** [comment]
IMO Prettier often is more like "Lengthener". There are a whole lot (10,000+) of lines that are over 140 chars in vscode repo, but if you run a search and look through them all, in the vast majority of cases the decision to make a line long was intentional on the part of the author because the stuff at the end really does not matter.  Applying prettier succeeds at making the line smaller, but severely reduces the information density of any given scroll-position, and thus dramatically increases the amount of scrolling around to see the various things you want to see, often fully prohibiting seeing the set of things you want to see all in the same scroll-position.

Take for instance our:

```ts
/**
 * Definition of the editor colors
 */
export const editorLineHighlight = registerColor('editor.lineHighlightBackground', { dark: null, light: null, hc: null }, nls.localize('lineHighlight', 'Background color for the highlight of line at the cursor position.'));
export const editorLineHighlightBorder = registerColor('editor.lineHighlightBorder', { dark: '#282828', light: '#eeeeee', hc: '#f38518' }, nls.localize('lineHighlightBorderBox', 'Background color for the border around the line at the cursor position.'));
export const editorRangeHighlight = registerColor('editor.rangeHighlightBackground', { dark: '#ffffff0b', light: '#fdff0033', hc: null }, nls.localize('rangeHighlight', 'Background color of highlighted ranges, like by quick open and find features. The color must not be opaque so as not to hide underlying decorations.'), true);
export const editorRangeHighlightBorder = registerColor('editor.rangeHighlightBorder', { dark: null, light: null, hc: activeContrastBorder }, nls.localize('rangeHighlightBorder', 'Background color of the border around highlighted ranges.'), true);
export const editorSymbolHighlight = registerColor('editor.symbolHighlightBackground', { dark: editorFindMatchHighlight, light: editorFindMatchHighlight, hc: null }, nls.localize('symbolHighlight', 'Background color of highlighted symbol, like for go to definition or go next/previous symbol. The color must not be opaque so as not to hide underlying decorations.'), true);
export const editorSymbolHighlightBorder = registerColor('editor.symbolHighlightBorder', { dark: null, light: null, hc: activeContrastBorder }, nls.localize('symbolHighlightBorder', 'Background color of the border around highlighted symbols.'), true);

export const editorCursorForeground = registerColor('editorCursor.foreground', { dark: '#AEAFAD', light: Color.black, hc: Color.white }, nls.localize('caret', 'Color of the editor cursor.'));
export const editorCursorBackground = registerColor('editorCursor.background', null, nls.localize('editorCursorBackground', 'The background color of the editor cursor. Allows customizing the color of a character overlapped by a block cursor.'));
export const editorWhitespaces = registerColor('editorWhitespace.foreground', { dark: '#e3e4e229', light: '#33333333', hc: '#e3e4e229' }, nls.localize('editorWhitespaces', 'Color of whitespace characters in the editor.'));
export const editorIndentGuides = registerColor('editorIndentGuide.background', { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces }, nls.localize('editorIndentGuides', 'Color of the editor indentation guides.'));
export const editorActiveIndentGuides = registerColor('editorIndentGuide.activeBackground', { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces }, nls.localize('editorActiveIndentGuide', 'Color of the active editor indentation guides.'));
export const editorLineNumbers = registerColor('editorLineNumber.foreground', { dark: '#858585', light: '#237893', hc: Color.white }, nls.localize('editorLineNumbers', 'Color of editor line numbers.'));
```

versus Prettier's:
```ts
/**
 * Definition of the editor colors
 */
export const editorLineHighlight = registerColor(
  "editor.lineHighlightBackground",
  { dark: null, light: null, hc: null },
  nls.localize(
    "lineHighlight",
    "Background color for the highlight of line at the cursor position."
  )
);
export const editorLineHighlightBorder = registerColor(
  "editor.lineHighlightBorder",
  { dark: "#282828", light: "#eeeeee", hc: "#f38518" },
  nls.localize(
    "lineHighlightBorderBox",
    "Background color for the border around the line at the cursor position."
  )
);
export const editorRangeHighlight = registerColor(
  "editor.rangeHighlightBackground",
  { dark: "#ffffff0b", light: "#fdff0033", hc: null },
  nls.localize(
    "rangeHighlight",
    "Background color of highlighted ranges, like by quick open and find features. The color must not be opaque so as not to hide underlying decorations."
  ),
  true
);
export const editorRangeHighlightBorder = registerColor(
  "editor.rangeHighlightBorder",
  { dark: null, light: null, hc: activeContrastBorder },
  nls.localize(
    "rangeHighlightBorder",
    "Background color of the border around highlighted ranges."
  ),
  true
);
export const editorSymbolHighlight = registerColor(
  "editor.symbolHighlightBackground",
  { dark: editorFindMatchHighlight, light: editorFindMatchHighlight, hc: null },
  nls.localize(
    "symbolHighlight",
    "Background color of highlighted symbol, like for go to definition or go next/previous symbol. The color must not be opaque so as not to hide underlying decorations."
  ),
  true
);
export const editorSymbolHighlightBorder = registerColor(
  "editor.symbolHighlightBorder",
  { dark: null, light: null, hc: activeContrastBorder },
  nls.localize(
    "symbolHighlightBorder",
    "Background color of the border around highlighted symbols."
  ),
  true
);

export const editorCursorForeground = registerColor(
  "editorCursor.foreground",
  { dark: "#AEAFAD", light: Color.black, hc: Color.white },
  nls.localize("caret", "Color of the editor cursor.")
);
export const editorCursorBackground = registerColor(
  "editorCursor.background",
  null,
  nls.localize(
    "editorCursorBackground",
    "The background color of the editor cursor. Allows customizing the color of a character overlapped by a block cursor."
  )
);
export const editorWhitespaces = registerColor(
  "editorWhitespace.foreground",
  { dark: "#e3e4e229", light: "#33333333", hc: "#e3e4e229" },
  nls.localize(
    "editorWhitespaces",
    "Color of whitespace characters in the editor."
  )
);
export const editorIndentGuides = registerColor(
  "editorIndentGuide.background",
  { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces },
  nls.localize("editorIndentGuides", "Color of the editor indentation guides.")
);
export const editorActiveIndentGuides = registerColor(
  "editorIndentGuide.activeBackground",
  { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces },
  nls.localize(
    "editorActiveIndentGuide",
    "Color of the active editor indentation guides."
  )
);
export const editorLineNumbers = registerColor(
  "editorLineNumber.foreground",
  { dark: "#858585", light: "#237893", hc: Color.white },
  nls.localize("editorLineNumbers", "Color of editor line numbers.")
);
```

In our case, I can see pretty much all the important information at once on my 15" MBP, and if I'm in a width constrained-case I can scroll to see column-slices of similar information in the same screen. In the Prettier case there are three full page-heights to scroll through to see the info, and all of the existing parallel constructs missing.

**Comment by connor4312** [comment]
While you can [ignore code](https://prettier.io/docs/en/ignore.html), you can also change the print width. Normally (and for js-debug) I prefer to set the width at 100 characters. Ultimately though this is a matter of taste, I dislike the long lines in vscode since I almost always use a split view with a width of ~120 characters if I don't have the minimap on.

**Comment by JacksonKearl** [comment]
Even 120 would make that section less comprehensible IMO:

```ts
/**
 * Definition of the editor colors
 */
export const editorLineHighlight = registerColor(
  "editor.lineHighlightBackground",
  { dark: null, light: null, hc: null },
  nls.localize("lineHighlight", "Background color for the highlight of line at the cursor position.")
);
export const editorLineHighlightBorder = registerColor(
  "editor.lineHighlightBorder",
  { dark: "#282828", light: "#eeeeee", hc: "#f38518" },
  nls.localize("lineHighlightBorderBox", "Background color for the border around the line at the cursor position.")
);
export const editorRangeHighlight = registerColor(
  "editor.rangeHighlightBackground",
  { dark: "#ffffff0b", light: "#fdff0033", hc: null },
  nls.localize(
    "rangeHighlight",
    "Background color of highlighted ranges, like by quick open and find features. The color must not be opaque so as not to hide underlying decorations."
  ),
  true
);
export const editorRangeHighlightBorder = registerColor(
  "editor.rangeHighlightBorder",
  { dark: null, light: null, hc: activeContrastBorder },
  nls.localize("rangeHighlightBorder", "Background color of the border around highlighted ranges."),
  true
);
export const editorSymbolHighlight = registerColor(
  "editor.symbolHighlightBackground",
  { dark: editorFindMatchHighlight, light: editorFindMatchHighlight, hc: null },
  nls.localize(
    "symbolHighlight",
    "Background color of highlighted symbol, like for go to definition or go next/previous symbol. The color must not be opaque so as not to hide underlying decorations."
  ),
  true
);
export const editorSymbolHighlightBorder = registerColor(
  "editor.symbolHighlightBorder",
  { dark: null, light: null, hc: activeContrastBorder },
  nls.localize("symbolHighlightBorder", "Background color of the border around highlighted symbols."),
  true
);

export const editorCursorForeground = registerColor(
  "editorCursor.foreground",
  { dark: "#AEAFAD", light: Color.black, hc: Color.white },
  nls.localize("caret", "Color of the editor cursor.")
);
export const editorCursorBackground = registerColor(
  "editorCursor.background",
  null,
  nls.localize(
    "editorCursorBackground",
    "The background color of the editor cursor. Allows customizing the color of a character overlapped by a block cursor."
  )
);
export const editorWhitespaces = registerColor(
  "editorWhitespace.foreground",
  { dark: "#e3e4e229", light: "#33333333", hc: "#e3e4e229" },
  nls.localize("editorWhitespaces", "Color of whitespace characters in the editor.")
);
export const editorIndentGuides = registerColor(
  "editorIndentGuide.background",
  { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces },
  nls.localize("editorIndentGuides", "Color of the editor indentation guides.")
);
export const editorActiveIndentGuides = registerColor(
  "editorIndentGuide.activeBackground",
  { dark: editorWhitespaces, light: editorWhitespaces, hc: editorWhitespaces },
  nls.localize("editorActiveIndentGuide", "Color of the active editor indentation guides.")
);
export const editorLineNumbers = registerColor(
  "editorLineNumber.foreground",
  { dark: "#858585", light: "#237893", hc: Color.white },
  nls.localize("editorLineNumbers", "Color of editor line numbers.")
);
```

And adding `// prettier-ignore` before every line is moving backwards before. There's no range-ignore (https://github.com/prettier/prettier/issues/5287), so that'd be the only option.

**Comment by JacksonKearl** [comment]
All that being said I do use and enjoy Prettier in [VSCode GitHub Triage Actions](https://github.com/microsoft/vscode-github-triage-actions/blob/main/.prettierrc) (no semi ftw), so it's not like I'm totally against it. There are just a lot of common "legacy" constructs in VS Code core that I think would be decidedly less comprehensible post-Prettier.

**Comment by rebornix** [comment]
regarding of "Lengthener", when Prettier can't fit a long line into print width, it will still try and end up with more lines but still long lines, for example

setting print width to 100

```ts
		styleSheets.push(`.monaco-workbench .notebookOverlay .output .cell-output-toolbar { left: -${cellRunGutter}px; }`);
```

will be converted to

```ts
		styleSheets.push(
			`.monaco-workbench .notebookOverlay .output .cell-output-toolbar { left: -${cellRunGutter}px; }`
		);
```

It's still longer than 100, but we end up with 3 lines.

**Comment by Tyriar** [comment]
I would prefer we didn't do this:

- Prettier or any auto format on save annoys me since it throws away my redo stack, disrupting how I work
- While it's nice that prettier defines a single correct way of doing things, I think generally it's too aggressive in enforcing that style and goes against how the lint rules were initially set up for the project which is why code style varies somewhat across the codebase. Wrapping as mentioned above is a big part of this, sometimes a single line `if () return`, very long single line, etc. is called for
- The current formatting seems sufficient

> All that being said I do use and enjoy Prettier in VSCode GitHub Triage Actions ("semi": false, "trailingComma": "all", ftw)

If we can all agree on a rule like this, it should be a hygiene step imo.

**Comment by JacksonKearl** [comment]
> If we can all agree on a rule like this, it should be a hygiene step imo.

If we all agree on `"semi": false` I'll eat my hat.

**Comment by rebornix** [comment]
> Prettier or any auto format on save annoys me since it throws away my redo stack, disrupting how I work

@Tyriar if I interpret this correctly, it means the typescript auto formatting currently we enforced in the core doesn't bother you

```
	"[typescript]": {
		"editor.defaultFormatter": "vscode.typescript-language-features",
		"editor.formatOnSave": true,
	},
``` 

If that's true, and we have hygiene check for missing semicolon, I'll suggest we add `"typescript.format.semicolons": "insert" first.

**Comment by Tyriar** [comment]
@rebornix it bothers me, I think we should remove that too. I only just discovered that was what was annoying me recently and I don't think I have a way to override it just for me. Format on save is a user preference imo, not a project setting, unless it's done as part of a pre-commit hook.

**Comment by hediet** [comment]
Maybe we can make prettier work just for those who want to use it. If only modified lines are formatted on save (which currently does not work for prettier), there shouldn't be much noise in commits, especially if we all have code areas that we own.

**Comment by jrieken** [comment]
I think we should selfhost on the formatters that ship with VS Code (like JS/TS etc) but for other language we could give this a try, like CSS or JSON. There also aren't many of those files which means that conflicts are less likely to occur

**Comment by hediet** [comment]
I opened an issue regarding automatic line break insertion (https://github.com/microsoft/TypeScript/issues/44504).

I cannot find much docs about the typescript formatter though.
There is the inofficial [`typescript-formatter`](https://github.com/vvakame/typescript-formatter) to run the tsc formatter from the command line, but it has not been updated for years.
Also, the `tsfmt.json` in the vscode repository root is only read by vscode-internal-tooling.

**Comment by hediet** [comment]
Even @RyanCavanaugh recommends to use prettier when we want to have automatic line breaks:

> This is an intentional design choice to err on the side of preserving user linebreaks/lack-of-linebreaks. I'd encourage the use of prettier or other tools if you want something that takes a more prescriptive approach to formatting; we are very much "hands off" when it comes to linebreaks and other things likely to raise hackles.

**Comment by connor4312** [comment]
Prettier's big secret sauce/value prop was handling of line breaks, which other formatter tools (like typescript or eslint-based tools like xo) either don't do or do in a very primitive way.

**Comment by Tyriar** [comment]
Key point from the quote 😉 

> we are very much "hands off" when it comes to linebreaks and other things likely to raise hackles.

**Comment by hediet** [comment]
> Key point from the quote 😉

But then lets please investigate how the few people who want to use prettier on the VS Code codebase can do so. Currently this is not possible due to the mentioned reasons.
