### ISSUE TITLE
Add "File > Exit" keyboard shortcut?

### ISSUE THREAD

**Issue by frederikhors** [microsoft/vscode#124764]
Often in my daily work I have many projects open in different instances of VSCode.

And I often find myself quitting using mouse and "File > Exit" to get all the windows back as soon as I reopen it tomorrow.

I can't find a way to add a keyboard shortcut for "File > Exit". It's possible?

If not possible today can you add this feature?

Thank you.

**Comment by IllusionMH** [comment]
/question

It's existing action `workbench.action.quit`.
You can add shortcut that is convenient for you using [Keyboard Shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor)
