### ISSUE TITLE
How to ship an opt-in extension update?

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#12476]
We want to ship opt-in bug fix updates to our extension without annoying users by pushing too frequent updates. How can we do this? I'm not sure yet if it already behaves this way. We don't want the update info message box to appear. We want the updated version to appear in the @outdated list and for people who don't already have the extension installed.

If some property could be added to the packages.json or some option in the publishing tool that would be great.

**Comment by joaomoreno** [comment]
We don't support it. It's been our choice so far to keep users always on the latest versions, so they will get an update notification.

**Comment by sean-mcmanus** [comment]
Okay, I'm not seeing an info pop up message about extensions now, just the notification in the extensions window, so that seems okay.
