### ISSUE TITLE
Bad positioning for inline completion

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#124742]
* create a TS file:
```ts
class C {
    public _member(): void {
    }
    private m() {
        this_member
    }
}
```
* place cursor after `this` and press `.`
* wait for inline completions to render
* press arrow right

https://user-images.githubusercontent.com/5047891/119787844-ebe49300-bed1-11eb-9976-b14ed76853d2.mp4

**Comment by hediet** [comment]
Interesting, I cannot reproduce this on main:

![eba70bcf-f49c-4ae4-8e42-ea71b5619490](https://user-images.githubusercontent.com/2931520/119788922-dcb21500-bed2-11eb-9e74-100dd70fcfde.gif)

**Comment by alexdima** [comment]
@hediet Can you try to unbind the keybinding that arrow right accepts the completion ?

**Comment by hediet** [comment]
Oh I misread the issue description. But what should be the expected outcome?
You can either only position the cursor directly before the decoration or directly after it, but not both. We explicitly want to set the cursor directly before it.

**Comment by alexdima** [comment]
@hediet I think the problem is that the view model updates only on document content change events and on suggest widget focus events and doesn't re-evaluate the common prefix on cursor position change events.
