### ISSUE TITLE
theme background rendering problem

### ISSUE THREAD

**Issue by GRRK** [Microsoft/vscode#12474]
- VSCode Version: Version 1.5.3 
- OS Version: macOS Sierra 10.12

Since upgrading to Sierra I see the rendering glitch in all themes except those with solid black or white background.  ##

<img width="1017" alt="screen shot 2016-09-22 at 20 18 53" src="https://cloud.githubusercontent.com/assets/22377822/18760570/f2e74aca-8101-11e6-8b77-ea6121dcafaa.png">

**Comment by chrmarti** [comment]
Tracked as #12473
