### ISSUE TITLE
Weird or wrong translations in Spanish locale

### ISSUE THREAD

**Issue by RobertoMD** [Microsoft/vscode#12478]
- VSCode Version: 1.5.3
- OS Version: 10

Some spanish localizations are "weird" according to MS standards, or even wrong. So far I've found these:
- "**About**" > currently "**Sobre**", usual MS string on other products: "**Acerca de...**". 
- "**Format code**" (right click menu), currently "**Código de formato**". The translator interpreted "**Format**" as a name, not as a verb. Looks like a direct translation from a translation tool. Right translation would be "**Dar formato al código**".
- Right click menu , "**Cambiar todas las repeticiones**", should be "**Cambiar todas las ocurrencias**".

All the rest seems to be fair accurate.

**Comment by johnliu2016** [comment]
@lukaschal please review both instances

/Localize/esn/vscode/src/vs/editor/contrib/format/common/format.nls.resx.lcl
/Localize/esn/vscode/src/vs/editor/contrib/format/common/formatActions.nls.resx.lcl

both "Format Code" strings are interpreted to "Código de formato"

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by Tyriar** [comment]
Are these changes meant to already be in Insiders? About is still "Sobre"?
