### ISSUE TITLE
random message 'Element can't be renamed' on refactor

### ISSUE THREAD

**Issue by v1d3rm3** [microsoft/vscode#124750]
Does this issue occur when all extensions are disabled?: **Yes**/No
When this error happened, i tried to disabled all extensions, but the error remains happening.

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Start coding in typescript
2. Randomly, when try to refactor an element, it not allow giving "The element can't be renamed"
3. When vscode is restarted, things are solved.

Steps:

![Animação](https://user-images.githubusercontent.com/16581931/119822547-26e2c880-beca-11eb-98d0-a1d1e0c59ac7.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by v1d3rm3** [comment]
@mjbvz i'll test these days.

**Comment by v1d3rm3** [comment]
I'm having no issues anymore with insiders.
