### ISSUE TITLE
Test: TerminalOptions.message Stable API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#124712]
Refs #120368

- [x] macOS @egamma 
- [x] linux @jrieken
- [x] windows @eamodio  

Complexity: 2

Authors: @tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124712%0A%0A)

---

Using the `vscode-extension-samples/terminal-sample`, provide `message` as an argument to `createTerminalFromOptions`. Verify that you see this text when you create a terminal. Note that you need to use `TerminalOptions`, not `ExtensionTerminalOptions`.

**Comment by eamodio** [comment]
FYI, I couldn't get this to work at all, see #125181
