### ISSUE TITLE
Trusting an empty workspace should trust all empty workspaces

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#124867]
<img width="1450" alt="CleanShot 2021-05-28 at 14 23 01@2x" src="https://user-images.githubusercontent.com/35271042/120043111-3a705b00-bfc0-11eb-8fbe-21003e357456.png">

Steps to Reproduce:

1. Open an empty window
2. Click on `🔒 Restricted Mode` in the status bar
3. Click on `Trust`
4. Open a new window
5. :bug: empty window is untrusted

I would expect that trusting an empty workspace would trust all empty workspaces

Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T10:00:38.762Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by sbatten** [comment]
that would be bad, you are explicitly trusting the window, and we have a separate setting for the default. if you open a few files and decide that you want to trust the window to allow some notebook stuff to run, that doesn't mean you want every new empty window to open with trust.

 I think if we want to allow that it should be similar to the Trust parent folder button in the drop down. "Trust" and "Trust All Empty Workspaces" or something to that effect
