### ISSUE TITLE
Cannot rename directory: file lock

### ISSUE THREAD

**Issue by cdalexndr** [microsoft/vscode#124862]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: win 10

Steps to Reproduce:

1. File - Open a folder
2. Copy a directory containing a git repository inside that folder
3. Try to rename the newly added folder
4. The action can't be completed because the folder or a file in it is open in another program

This is annoying because I use VSCode as a text editor, and to search files in folder. I have to close VSCode to rename the folder.

**Comment by isidorn** [comment]
This is expected behavior and nothing vscode can do about it. The FS does not allow us to rename the directory because some other process is using it

**Comment by cdalexndr** [comment]
@isidorn you could release the file locks instead of keeping them open permanently while VSCode is opened, and open them as required...

**Comment by isidorn** [comment]
VS code does not keep a lock on the folder as far as I know.
@eamodio might have more details if we do something special for a git repository folder

**Comment by eamodio** [comment]
I'm not aware of any lock that we hold on the .git folder, but Git itself can in certain circumstances -- e.g. any "write" calls and `status` calls, though later version of Git allow us to tell Git to avoid holding a lock on `status` calls, which we do.
