### ISSUE TITLE
Codespaces terminal showing too many ⚠️

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#124861]
<img width="786" alt="CleanShot 2021-05-28 at 13 26 24@2x" src="https://user-images.githubusercontent.com/35271042/120038557-54a63b00-bfb8-11eb-9c74-77ac5d9abf56.png">

Steps to Reproduce:

1. Create a new codespace in desktop using the vscode repro
2. :bug: the terminal shows multiple ⚠️ (single tab, insider terminal, terminal tab list)

I'd expect to not see the single tab nor the insider terminal warning

GitHub Codespaces: v0.10.4
Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T10:00:38.762Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by meganrogge** [comment]
I think this is as-designed, though I thought we had gotten rid of the one in the terminal contributed by js debug?

**Comment by Tyriar** [comment]
The config terminal should probably be able to opt out of the warning somehow since this looks broken.
