### ISSUE TITLE
Multiple Versions of "Go" in top title bar

### ISSUE THREAD

**Issue by brread** [Microsoft/vscode#12485]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:22:54.636Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:

Not sure. Most likely cause is splitting the viewing window into three separate panes. I was viewing the diff of two files.

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by brread** [comment]
Ah darn, I took a screenshot when this was happening, but I didn't have my mouse in the correct place so the top bar isn't showing correctly.

I'll be on the lookout for if it happens again and post here if I can see it (hopefully with a repro)

Sorry that I'm not giving any useful information here. Also, I don't think this should matter, but it was being done through Hyper-V.

![screenshot from 2016-09-22 12-30-46](https://cloud.githubusercontent.com/assets/22242556/18766244/2621ab08-80ce-11e6-9b9c-7545097f0d6f.png)

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
