### ISSUE TITLE
Double clicking viewlet sash no longer optimizes explorer width

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12482]
- VSCode Version: Code - Insiders 1.6.0-insider (90dda7af651fc557d40b166f322db3f014e8f33b, 2016-09-21T06:24:51.376Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

After double clicking the sash:

![image](https://cloud.githubusercontent.com/assets/2193314/18762400/7b83e590-80bd-11e6-8181-3bcfcf344b39.png)

**Comment by bpasero** [comment]
Likely a regression from the icon work.
