### ISSUE TITLE
Native Notebooks - Resize outputs with Math rendering

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124872]
Sometimes the rendering for math is quite small depending on the elements in it and there is no way to enlarge this output today. Would be great if there was some way to make this larger. 

![image](https://user-images.githubusercontent.com/19276747/120048035-f040a700-bfca-11eb-8607-55a9fd7f0494.png)

**Comment by Queuecumber** [comment]
Just to give some more context:

In my case, the editor font size and output font sizes all look fine but the markdown is really small for some reason: 

![markuphero-4zRacRnMAp92uSoD1B2U-1](https://user-images.githubusercontent.com/5865387/119748284-8e652d80-be62-11eb-9bdd-82136e193914.png)

I've tried changing the "Markdown > Preview: Font Size" setting but it seems like that isnt being used here. It would be great if the font size for the markdown (including equations) could be changed or if it at least respected the size setting that's already in the markdown renderer extension

**Comment by misolori** [comment]
@mjbvz I've noticed that the markdown render font size is different from the markdown preview. We should probably along these so that the markdown preview font size setting works in notebooks as well.

**Comment by allefeld** [comment]
I don't there even needs to be a separate setting, the important thing is that code/output font size and markdown font size match (or, if you want to get fancy, that x-height matches).

**Comment by coxackie** [comment]
@mjbvz I understand that this may not reach the required (20) upvotes, but if it is as easy a fix as to align markdown renderer and markdown preview, could this be implemented anyway? The sizing can be quite off, as the post from @Queuecumber above shows. I use jupyter notebook in classroom teaching and like to use vscode for that - markdown font too small makes the students' eyes squint to nothingness, in order to make out what is written...

**Comment by coxackie** [comment]
@greazer many thanks for reopening this - I got worried it will be abandoned. Does this mean it will be considered for a fix?

**Comment by spinicist** [comment]
I also would very much like to see this fixed. Currently mixed Markdown & Code notebooks are very hard to read in VS Code, which is a great shame. I would have upvoted this in October if I had found this issue then. Please do not abandon this.

**Comment by mjbvz** [comment]
Resizing the rendered markdown is covered by #126294 and is now adjustable in the insiders using `notebook.markup.fontSize`

Leaving this issue open to cover just math outputs (inline math in markdown scales with  `notebook.markup.fontSize`)

**Comment by spinicist** [comment]
@mjbvz Thank you! I'm looking forward to this filtering through to the general release.
