### ISSUE TITLE
Test: `StatusBarItem` properties `id` and `name`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124843]
Refs #74972

- [x] anyOS @roblourens 
- [x] anyOS @weinand 
- [x] anyOS @chrisdias (Optional) 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124843%0A%0A)

---

You can now pass a `id` to the `createStatusBarItem` method for the item and set a `name` property dynamically.

**Test:**
* write a simple extension that adds a `StatusBarItem` to the window
* verify you can use this new API without enabling proposed API
* the `name` you pick appears as name in the context menu on the status bar for your entry (see example below)
* if you access `id` property of `StatusBarItem` from extension code, the value will be the extension identifier unless you specify an identifier when creating the item
* if you access `name` property of `StatusBarItem` from extension code, the value will be `undefined` unless you specify it and once specified will match what you were assigning it to

![status-menu](https://user-images.githubusercontent.com/900690/120007497-423cf900-bfda-11eb-8ae5-6b001fd0cc3c.png)

**Comment by weinand** [comment]
@bpasero if the `id` of a `StatusBarItem` is not explicitely specified, accessing the property gives a `undefined_publisher.statusbar`, not `undefined`.

<img width="491" alt="2021-06-01_14-09-35" src="https://user-images.githubusercontent.com/1898161/120321170-42dbd500-c2e3-11eb-85c9-852489268666.png">

Let me know if this is an error and if you want me to create a bug...

**Comment by bpasero** [comment]
Thanks I updated the test plan, for `id` this is expected.

**Comment by roblourens** [comment]
Looks good, but why allow changing the name? Seems like this is something that would be static

**Comment by bpasero** [comment]
It is a display property and all the other display properties can be changed as well. We had a API discussion about it.
