### ISSUE TITLE
ES Lint Rule For Copyright Header

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#124891]
Currently, we have to add this copyright header manually to every new file:
```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
```

An ES Lint rule that has an auto fix would be really nice.

What are your thoughts @joaomoreno @jrieken?

![recording](https://user-images.githubusercontent.com/2931520/120067345-4bca6d80-c07b-11eb-8d58-3ab8b066e7cc.gif)

(using [this rule](https://github.com/Stuk/eslint-plugin-header))

**Comment by jrieken** [comment]
I like. The closest that we have today is this snippet https://github.com/microsoft/vscode/blob/3ab955068633f1b1b8831bb5fdfca02e90c0c1f1/.vscode/shared.code-snippets#L8

**Comment by joaomoreno** [comment]
Let's do it!
