### ISSUE TITLE
Unable to read registry key with property function

### ISSUE THREAD

**Issue by theknut** [microsoft/vscode#124808]
I'm developing a NuGet package which contains a *. target file. In this target I'm reading several registry keys using `$([MSBuild]::GetRegistryValueFromView(...))` ([see MSDN](https://docs.microsoft.com/en-US/visualstudio/msbuild/property-functions?view=vs-2019#:~:text=the%20msbuild%20getregistryvaluefromview%20property%20function%20gets%20system%20registry%20data%20given%20the%20registry%20key%2C%20value%2C%20and%20one%20or%20more%20ordered%20registry%20views.%20the%20key%20and%20value%20are%20searched%20in%20each%20registry%20view%20in%20order%20until%20they%20are%20found.)). I'm testing my package in VS Prof and VS Community and it works flawlessly. However, when using my package in VS Code V1.56.2 it will **not** work. I was unable to find anything on Google. How can I make this work?

`<RegTest>$([MSBuild]::GetRegistryValueFromView(``HKEY_CLASSES_ROOT\vscode\shell\open\command``, ``, ``Not found``, RegistryView.Registry64, RegistryView.Registry32))</RegTest>`

In VS I get the expected path and in VS Code I get "Not found".

More Info:
`Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363`

Using the following extensions
![extensions](https://user-images.githubusercontent.com/6503243/119937680-7f2dcf00-bf8b-11eb-9aae-71d404c78165.png)

**Comment by dbaeumer** [comment]
This looks like a problem that needs to be addressed by the C# extension.
