### ISSUE TITLE
Readonly doesn't show up in custom editor tabs until they are made inactive

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124860]
Repro:

1. Delete an image
2. Open the image with Luna Paint (or any custom editor?), readonly doesn't show
3. Switch away from the image tab, readonly shows

![recording](https://user-images.githubusercontent.com/2193314/120035840-127afa80-bfb4-11eb-803e-ecd99513ba77.gif)

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/b2f203113c155f81a92fa5448b69b6170d16b2f7

**Comment by Tyriar** [comment]
Actually this works for git/luna paint but not for image preview yet:

![image](https://user-images.githubusercontent.com/2193314/120890675-31334f80-c5b9-11eb-8666-ca5086fc6827.png)

The readonly custom editor case might not be done right?

**Comment by bpasero** [comment]
@Tyriar I cannot reproduce with your original steps:

![recording (1)](https://user-images.githubusercontent.com/900690/120897630-742c0c00-c627-11eb-8bf1-1c3203f6cd84.gif)

**Comment by Tyriar** [comment]
@bpasero this file isn't deleted in my most recent comment, this might be on @mjbvz for readonly custom editors but the repo is almost exactly the same as this.

**Comment by bpasero** [comment]
@Tyriar can you give updated steps then what you were doing that lead to the issue you see?

**Comment by Tyriar** [comment]
@bpasero uninstall luna paint, open a png image

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/121018971-48339680-c79f-11eb-8b1b-d955d46cad45.gif)

I cannot reproduce.

**Comment by Tyriar** [comment]
@bpasero open via the explorer, don't delete

**Comment by Tyriar** [comment]
Thanks 👍
