### ISSUE TITLE
Remove italics in untitiled text editor hint

### ISSUE THREAD

**Issue by joeparis** [microsoft/vscode#124855]
VS Code 1.56 introduced [Untitled editors hint](https://code.visualstudio.com/updates/v1_56#_untitled-editors-hint) feature which I believe will be valuable to many people such as my beginning programming students. In the same month, Cascadia Code version 2105.24 was released and added [cursive letterforms](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-9-release/#cascadia-code-updates). Because I use Cascadia Code as my font in VS Code (as I believe many people do) when I open a new editor, the prompt to "Select a language to get started." appears in cursive.

![untitled-editor](https://user-images.githubusercontent.com/2662123/120028460-94195b00-bfa9-11eb-9fe0-122fa0cc79f3.png)

Personally, I *really* do not like this. However, I do not want to disable the cautionary text because it is what my students will see (and it's a good reminder for them). I would very much like a way to make this text appear in a regular typeface.

Many VS Code themes, such as [Tokyo Night](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night), allow for disabling italicized text by setting options in `settings.json` like:

```json
"editor.tokenColorCustomizations": {
    "[Tokyo Night]": { // or "[Tokyo Night Storm]"
        "textMateRules": [{
            "scope": [
                "comment",
                "meta.var.expr storage.type",
                "keyword.control.flow",
                "keyword.control.return",
                "meta.directive.vue punctuation.separator.key-value.html",
                "meta.directive.vue entity.other.attribute-name.html",
                "tag.decorator.js entity.name.tag.js",
                "tag.decorator.js punctuation.definition.tag.js",
                "storage.modifier"
            ],
            "settings": {
                "fontStyle": ""
            }
        }]
    }
}
```

With this, I have been able to disable the cursive font everywhere in VS Code *except* in a new, untitled editor. Is there a way to add the cautionary text to the scope for the formatting rule shown above? Is the formatting for the text surfaced in some other way? Can it be? I very much want to remove the cursive font shown above. Any help would be *greatly* appreciated.

@isidorn

**Comment by isidorn** [comment]
This is currently not possible, the untitled text is respecting the editor font. We initially had it designed to use the non editor font but that got negative feedback since then it would also not respect the editor font size.
So it is always following the editor font and we do not want to allow to specially customise it.
However it seems that you have special rules to disable this everywhere except untitled hint. The reason for taht is probably that the untitled hint text does not use textMate grammers and rules and you seem to be using that for customisation.

If you do not like it I suggest you simply disable it using the option 
`"workbench.editor.untitled.hint": "hidden"`

Sorry that I was not of more help.

For now we can leave this open and we can see if somebody from the community has ideas on how to fix.

**Comment by joeparis** [comment]
OK, at least I can feel better knowing the problem wasn't me simply failing to find the setting.

The italics are applied via CSS in `untitledTextEditorHint.ts`, does it have to be italicized? What's the reasoning behind the font style?

**Comment by isidorn** [comment]
Yeah it is applied [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts#L146)

As for why? It was just a design decision to make sure it is different from the regular code.
If more users do not like it I can think about adding a setting, but would not add it yet.

**Comment by nickdepinet** [comment]
I also recently noticed this change... It makes it much harder for me to read anything italic in the terminal (comments seem to be italicized by default for me as well) using cascadia code (although I like the font otherwise). Is my only option for accessibility to not use this font at all?
