### ISSUE TITLE
feat: show the actual type information when type aliases are used in the hint popup

### ISSUE THREAD

**Issue by AoDev** [microsoft/vscode#124884]
I'd like to see proper type information for type aliases in the hint popup. This would improve the developer experience. Especially when types come from a 3rd party library.

The example below is with Typescript but I'd expect it to be a general feature. 

**Example: a random type with proper info bubble**

<img src="https://user-images.githubusercontent.com/1526150/120060745-c84c5480-c059-11eb-98a4-119b13708926.png" width="300"/>

**What VS Code shows now when the type alias is used somewhere**

<img src="https://user-images.githubusercontent.com/1526150/120060738-be2a5600-c059-11eb-8e8d-e8c22af2935b.png" width="320"/> 

**What I'd like to see**

<img src="https://user-images.githubusercontent.com/1526150/120060802-2d07af00-c05a-11eb-8804-e442924b5717.png" width="320"/>

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/35601
