### ISSUE TITLE
"Reveal in Explorer" hotkey doesn't work

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#124825]
Issue Type: <b>Bug</b>

Using the key combination (Shift+Alt+R) for "Reveal in Explorer" does nothing.

Using the context menu entry works as expected.

The troubleshooter output looks like it works:
```
[2021-05-28 12:12:37.602] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched revealFileInOS, when: !editorFocus, source: built-in.
[2021-05-28 12:12:37.602] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift,alt], code: KeyR, keyCode: 82, key: R
[2021-05-28 12:12:37.602] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift,alt], code: KeyR, keyCode: 48 ('R')
[2021-05-28 12:12:37.602] [renderer1] [info] [KeybindingService]: | Resolving shift+alt+R
[2021-05-28 12:12:37.602] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched revealFileInOS, when: !editorFocus, source: built-in.
[2021-05-28 12:12:37.769] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord alt.
[2021-05-28 12:12:38.070] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (33.75GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (34.43GB free)|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (34.43GB free)|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.16
terraform|has|2.11.0
vscode-esformatter|how|1.6.0
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.33

(1 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
@isidorn I didn't expect the hotkey to work when I have the editor in focus. I expected it to work when the file explorer panel is in focus. That expectation was and is not met.

For clarification: I click on a file in the file explorer panel. Then I press the key combination. Nothing happens.

I can click the file as many times as I want (in case the focus was moved elsewhere) and it does not work.

If my approach is not right, please let me know the right way.

**Comment by isidorn** [comment]
@oliversalzburg ok. Can you reproduce with VS Code insiders?

**Comment by oliversalzburg** [comment]
@isidorn For me the behavior is identical in Insiders. I should have noted that earlier.

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by oliversalzburg** [comment]
I just noticed this works as intended on Windows. I'm experiencing the issue when working in WSL.

**Comment by isidorn** [comment]
Ok, so the gist of the issue seems to be "Reveal in Explorer does not work for WSL". Let me reopen...
