### ISSUE TITLE
Terminal in new usr data directory fails to open

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#124866]
<img width="1018" alt="CleanShot 2021-05-28 at 14 12 55@2x" src="https://user-images.githubusercontent.com/35271042/120042415-def19d80-bfbe-11eb-81a2-30378cc3c216.png">

1. Open insiders with a fresh usr data & ext directory (I use this little script on mac: `$ rm -fr ~/code_profiles/empty/ && mkdir -p ~/code_profiles/empty/data/User && code-insiders --user-data-dir ~/code_profiles/empty/data/User --extensions-dir ~/code_profiles/empty/extensions`)
2. Open the terminal
3. :bug: See error `The terminal process failed to launch: Path to shell executable "zsh" is not a file of a symlink.`

When I open Insiders normally I don't see any errors and can open the terminal. I don't have any terminal specific settings.

Version: 1.57.0-insider
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T10:00:38.762Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0

**Comment by meganrogge** [comment]
@bpasero i see you've changed something related to this https://github.com/microsoft/vscode/blob/949f60498aecf6f78f63aa587999589a8f65c3ac/src/vs/platform/terminal/node/terminalProcess.ts#L204-L204

**Comment by bpasero** [comment]
That change is to avoid using `fs.promises.*` APIs and use the traditional callback based `fs.*` API instead to enable our [`graceful-fs`](https://github.com/isaacs/node-graceful-fs) library to work.

**Comment by Tyriar** [comment]
@misolori can you get the output of `ls -la $(which zsh)`?

**Comment by Tyriar** [comment]
Ping @misolori

**Comment by misolori** [comment]
`lrwxr-xr-x  1 misolori  admin  25 Sep 25  2020 /usr/local/bin/zsh -> ../Cellar/zsh/5.8/bin/zsh`

**Comment by Eld0ud** [comment]
same issue here

> @misolori can you get the output of `ls -la $(which zsh)`?

I have the same result :
`lrwxr-xr-x  1 eldoud  admin  25 Sep 21  2020 /usr/local/bin/zsh -> ../Cellar/zsh/5.8/bin/zsh`

**Comment by Eld0ud** [comment]
adding this (as mentioned [here](https://github.com/microsoft/vscode/issues/125959#issuecomment-859605127)) in my user settings worked for me:
```
  "terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "/usr/local/bin/zsh"
    }
  },

**Comment by Tyriar** [comment]
I think this is the same as https://github.com/microsoft/vscode/issues/124968
