### ISSUE TITLE
Test: sandbox ready splash screen

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124838]
Refs #122828

- [x] anyOS @kieferrm 
- [x] anyOS @alexdima

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124838%0A%0A)

---

The code responsible to rendering a splashscreen before the workbench UI appears was rewritten to be sandbox ready.

**Test:**
* when you start VSCode (not in fullscreen) or reload the window you briefly see the layout as a shape reflecting the sidebar width and editor size as it was left (see screenshot below)
* change your theme from light to dark or vice versa and verify the splash is also reflecting this (might require a few seconds after changing the theme to persist due to debouncing)

![image](https://user-images.githubusercontent.com/900690/120003727-4cf58f00-bfd6-11eb-8ea7-d400f7f8f6d4.png)

**Comment by kieferrm** [comment]
Works as expected.  It seems to me that the splash screen now is rendering noticeably faster (at least on my Windows machine) which makes the effect more pronounced. Nice work!

**Comment by bpasero** [comment]
Oh nice 👍
