### ISSUE TITLE
window.showErrorMessage: returned item is undefined if close is selected

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1248]
- use window.showErrorMessage with a custom message.
- when the message appears press the close button

Observe: the resolved value for the item is undefined. IMO it should be an item representing the close button

**Comment by jrieken** [comment]
@dbaeumer Is this only for close, when being the default, e.g the absence of other items?

**Comment by dbaeumer** [comment]
@jrieken no, I my example I had a custom button and the default close button. When the user presses the default close button the item is undefined. My code looks like this:
```typescript
				Window.showErrorMessage(error.message, { title: 'Retry', id: "retry"}).then(item => {
					if (item.id === 'retry') {
						this.initialize(connection);
					}
				});

```

**Comment by jrieken** [comment]
I see. Challenge is that it's spec'd to return `<T extends MessageItem>` which I cannot fulfil for the close item.

**Comment by jrieken** [comment]
Giving more thought, this is something we cannot do because of the afore mentioned restriction. I will change to doc to not only mentioned `undefined` but also how that happens
