### ISSUE TITLE
Test: untitled notebooks

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124844]
Refs #121974

- [x] macOS @roblourens
- [x] linux @gregvanl 
- [x] windows @lszomoru 

Complexity: 3

Authors: @bpasero, @jrieken, @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124844%0A%0A)

---

Untitled notebooks now leverage the file working copy workbench API and thus reuse most of the code that is also used by untitled text files.

**Note:** You can do this test with the `ms-vscode.vscode-github-issue-notebooks` extension.

**Test:**
* use the command `New GitHub Issue Notebook` to open a new untitled notebook
* verify this works for multiple untitled notebooks and each has a distinct label
* verify the notebook get's dirty when you make changes
* verify contents are restored after a restart (aka "hot exit")
* verify that saving the notebook asks you for a file path and then replaces the editor with the saved file
* verify you can close a dirty untitled notebook and get asked to save or revert
* verify both save or revert work as expected when closing an untitled notebook
* verify you can run `code-insiders <path to non existing GH issue notebook>` and that opens a new untitled notebook dirty that will save to the path once saved without asking

**Comment by roblourens** [comment]
The github issues untitled notebook is dirty when it opens, I assume that's because it has this default content and is expected?

**Comment by bpasero** [comment]
@roblourens I would say so, that matches text files as well when they have initial contents.
