### ISSUE TITLE
After enabling VS Code Ozone Wayland a "code-insiders" tab opens on startup

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#124890]
Issue Type: <b>Bug</b>

There is a code-insiders tab with text "Select a language to get started. Start typing to dismiss, or don't show this again." which shows each time i start VS Code. Previously the Welcome page was shown instead.

The issue appeared after i added --enable-features=UseOzonePlatform --ozone-platform=wayland to the command line of VS Code.

I tried clicking on "don't show this again", but the same tab named "code-insiders" shows up, just this time it's empty.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.11.0-17-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.41GB free)|
|Process Argv|--no-sandbox --unity-launch code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland --crash-reporter-id 9cc3662d-ccfb-4569-83fb-26560f111f8b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
laravel-extra-intellisense|ami|0.6.1
html-class-suggestions|And|1.1.1
vscode-intelephense-client|bme|1.7.1
vs-code-semicolon-insertion|chr|0.0.6
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.27.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.3
vscode-remote-extensionpack|ms-|0.21.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.12.0
vscode-versionlens|pfl|1.0.9
bash-debug|rog|0.3.9
laravel-artisan|rya|0.0.27
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
indenticator|Sir|0.7.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.4.0
vscode-jumpy|wma|0.3.1
local-history|xyz|1.8.1
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30307461
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by isidorn** [comment]
This is expected behavior to show the untitled editor hint. I have no clue what is UseOzonePlatform flag.
Closing as no action planned to change
