### ISSUE TITLE
[json] Completions provided in json comments

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/vscode#12489]
[JSON doest not allow comments](http://stackoverflow.com/questions/244777/can-comments-be-used-in-json) but [some json](https://github.com/Microsoft/vscode/blob/master/.vscode/launch.json#L98-L102) in the vscode repo itself uses comments. I'm unsure what the expected editing experience should be in this case, but perhaps it is worth clarifying a bit. The colorization should clarify that comments are forbidden, or allow them. If it is the latter, its is counter-intuitive that comments behave like normal json, and offer auto-completion.

In any event, text inside (illegal) comments triggers autocompletion.

![json_completion](https://cloud.githubusercontent.com/assets/3226984/18768411/d1795e78-80d9-11e6-8e03-2051a3d6f692.PNG)
- VSCode Version: 1.5.3 (commit 5be409)
- OS Version: Win10
  Steps to Reproduce:
1.  Open a *.json file
2.  Type a comment.
3. Type a non-whitespace character in the comment (eg: ':')
4. Observe completions

**Comment by chrmarti** [comment]
The grammar we use allows for comments. There shouldn't be regular completions in comments though.
