### ISSUE TITLE
Terminal dont work,wenn folder is open .maestrotwors@gmail.com

### ISSUE THREAD

**Issue by Maestrotwors** [Microsoft/vscode#12483]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14926

**Terminal dont work,wenn folder is open**

Steps to Reproduce:

Roman Rakzin
maestrotwors@gmail.com

**Comment by chrmarti** [comment]
Could you be more specific about the steps you take to reproduce this?

**Comment by Maestrotwors** [comment]
http://prntscr.com/clg8ir     
http://prntscr.com/clg9lq
http://prntscr.com/clgaqd
http://prntscr.com/clgbe9

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727

**Comment by Maestrotwors** [comment]
@Tyriar i have not found  -> #7727 , what write? Can you help me?

**Comment by Tyriar** [comment]
@Maestrotwors it's a known issue tracked there, there is currently no work around other than using folders without these characters.
