### ISSUE TITLE
Luna paint allows to edit even when readonly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#124888]
Not sure if this is an issue with VSCode or the extension, but while looking at https://github.com/microsoft/vscode/issues/124860 I noticed that I was still able to draw into the editor even though the editor is readonly.

**Comment by Tyriar** [comment]
Just fixed this in the extension yesterday. It might be a good idea to include checking if readonly file system in the custom editor sample as I had no idea until it was reported in the vscode repo @lramos15 @mattbierner
