### ISSUE TITLE
Crash when network unreachable

### ISSUE THREAD

**Issue by Fildefer3103** [microsoft/vscode#124882]
Issue Type: <b>Crash when shared folder is closed</b>

Hello,
I've exprienced some crash when some network shared ressource is going down : i currently work on some code stored on a nas, shared via smb protocol. When the nas is shutting down, and i keep the folder i'm working on open, vscode crashes.

Best regards, Phil.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:25.642Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 1ac4a03f-4b5a-412b-81f8-edb514cc8888|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
Thanks for the report, merging to https://github.com/microsoft/vscode/issues/106879
