### ISSUE TITLE
vscode-icons extension not enabled in remote windows on trusted folders

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#124818]
They work in a non remote instance

<img width="580" alt="capture" src="https://user-images.githubusercontent.com/1931590/119952550-6d552780-bf9d-11eb-9425-e221d799f1ae.png">

**Comment by aeschli** [comment]
Reproduced with the TestResolver:

- install `vscode-icons-team.vscode-icons` extension
- verify it works in a local window on a trusted folder
- open a new test resolver window
- open a trusted remote folder
- open the extensions view:  the `vscode-icons-team.vscode-icons` extension is grayed out in the extensions view, no explanation why, no button to install in remote

Set `security.workspace.trust.enabled": false`

- open the test resolver window again on the same folder, now the extension is enabled

**Comment by aeschli** [comment]
The vscode-icons extension is a UI extension: https://github.com/vscode-icons/vscode-icons/blob/c7a9e3c69a2af799d9ba8693819794718e194956/package.json#L127
It hasn't changed since April.

**Comment by dbaeumer** [comment]
Friendly ping since this is pretty annoying for me :-)

**Comment by lszomoru** [comment]
@dbaeumer sorry about that. I will try to get to this tonight as I am investigating another issue related to workspace trust.

**Comment by lszomoru** [comment]
@dbaeumer, until I investigate the root cause of the issue, you can add the following to your user settings as a workaround:

```
  "extensions.supportUntrustedWorkspaces": {
    "vscode-icons-team.vscode-icons": {
      "supported": true
    },
  }
```

**Comment by dbaeumer** [comment]
@lszomoru thanks!

**Comment by lszomoru** [comment]
@dbaeumer, the underlying bug has been fixed, so you can remove the entry from your user settings.
