### ISSUE TITLE
Stable->Insider->Stable with sync: (this.configurationService.getValue(...) || []).filter is not a function

### ISSUE THREAD

**Issue by tkazik** [microsoft/vscode#124897]
Issue Type: <b>Bug</b>

- Error: `(this.configurationService.getValue(...) || []).filter is not a function`
- Consequence: unable to open/edit files

Steps to reproduce:
1. Sync data on
2. switch from stable channel to insider channel
3. switch back to stable channel

How to fix:  `settings.json`
```
"workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ],
```

For completeness, the original version, being responsible for the error:
```
"workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
}
```

Credits/also reported here: https://www.reddit.com/r/vscode/comments/ndjjjy/cant_create_new_file_nor_open_new_file_in_vscode/

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-73-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.03GB (15.66GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id d9785aa6-ec20-4517-b0a8-f347e4c09c00|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.2
gltf-vscode|ces|2.3.10
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.41.0
xml|Dot|2.5.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
matlab|Gim|2.0.1
vscode-pull-request-github|Git|0.26.0
gc-excelviewer|Gra|3.0.42
vscode-test-explorer|hbe|2.20.1
latex-workshop|Jam|8.18.0
plantuml|jeb|2.14.5
kite|kit|0.143.0
vscode-github|Kni|0.30.6
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.13.0
vscode-ros|ms-|0.6.8
python|ms-|2021.6.864643163-dev
vscode-pylance|ms-|2021.5.5-pre.1
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
postscript|mxs|1.0.1
vscode-3dviewer|sle|0.2.2
qtvsctools|ton|0.8.3
cmake|twx|0.0.17
vscode-icons|vsc|11.4.0
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by lramos15** [comment]
See #125288, #123993, #123792, #123749. Basically just remove the setting for now and turn off insiders -> stable sync. We make no guarantees about their compatibility but once the new version goes out next week they should both be compatible again.
