### ISSUE TITLE
importModuleSpecifierEnding = js doesn't apply for autocomplete within import paths

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124898]
I have this workspace setting which works great for auto import:

```json
"typescript.preferences.importModuleSpecifierEnding": "js"
```

But when auto completing the path it still does .ts which requires manually changing:

![image](https://user-images.githubusercontent.com/2193314/120075258-62f66480-c055-11eb-8c8e-45ff1a4b54b3.png)

**Comment by worstpractice** [comment]
@Tyriar was the screenshot taken in a `.js` file by any chance?

I ask since VSCode also has the equivalent setting for JS files:
```json
"javascript.preferences.importModuleSpecifierEnding": "js"
```

**Comment by Tyriar** [comment]
It was a ts file

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

(excluding `.ts` is intentional but if you can explain your use case, they can probably offer guidance)
