### ISSUE TITLE
VS Code version 1.56 MacOs Touchbar debug buttons only visible in debug session when the debug tool bar is selected

### ISSUE THREAD

**Issue by nehemming** [microsoft/vscode#124840]
Issue Type: <b>Bug</b>

Macos VSCode start a debug session (replicated issue in c# and a go session)

The touchbar display in the previous versions showed the debug buttons (run, step over etc).   Since version 1.56 the buttons do not display once a debug session has been sarted unless you mouse click on the floating debug toolbar.

After clicking they appear and work.  If focus is moved else where the buttons goo agaiin.

This is repeatable

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.39GB free)|
|Process Argv|--crash-reporter-id c705fc35-9ae7-4b67-92f4-fb842ebeadb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.1
vscode-database-client2|cwe|3.8.5
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
auto-using|Fud|0.7.15
go|gol|0.25.1
terraform|has|2.11.0
rest-client|hum|0.24.5
vscode-edit-csv|jan|0.6.0
vscode-go-template|jin|0.2.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.20
git-graph|mhu|1.30.0
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
open-html-in-browser|pea|2.1.6
quicktype|qui|12.0.46
vscode-yaml|red|0.19.2
vscode-coverage-gutters|rya|2.7.3
code-spell-checker|str|1.10.2
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by nehemming** [comment]
Issue 104208 does not sound the same as this issue.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123105
This is fixed in insiders
