### ISSUE TITLE
Code-OSS hang while running with the debugger attached

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#124873]
- Start the "Launch VS Code" debug config
- Reload the window, repeat a couple times, and it will hang
- Start `./scripts/code.sh`
- Reload the window, repeat forever, no hang

Reminds me of issues like https://github.com/microsoft/vscode/issues/83994. I saw this on Linux but only rarely. Now on Mac I see it very often.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/103124
