### ISSUE TITLE
Word Wrap not working as expected with emojis

### ISSUE THREAD

**Issue by iamCristYe** [microsoft/vscode#124876]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: 19042.985

Steps to Reproduce:

1. Copy this string to Code: `👮‍♀️👮👮‍♂️👷‍♀️👷👷‍♂️💂‍♀️💂💂‍♂️🕵️‍♀️🕵️🕵️‍♂️👩‍⚕️👨‍⚕️👩‍🌾👨‍🌾👩‍🍳👨‍🍳👩‍🎓👨‍🎓👩‍🎤👨‍🎤👩‍🏫👨‍🏫👩‍🏭👨‍🏭👩‍💻👨‍💻👩‍💼👨‍💼👩‍🔧👨‍🔧👩‍🔬👨‍🔬`
2. Enable Word Wrap
3. You would see Word Wrap not working as expected:
![image](https://user-images.githubusercontent.com/12642018/120053021-9d163500-c05a-11eb-8cf5-d789a9350352.png)
4. Moreover, if you resize the window, you will notice some emoji separated into two, like `👨‍🌾`\u{1F468}\u{200D}\u{1F33E} separated to `👨`\u{1F468} and `🌾`u{1F33E}
![image](https://user-images.githubusercontent.com/12642018/120053027-a30c1600-c05a-11eb-9170-8c6962fe2600.png)

**Comment by alexdima** [comment]
By default, we use a very fast wrapping algorithm that makes assumptions about characters being monospace, etc. By configuring `"editor.wrappingStrategy": "advanced"`, you can switch to a much slower algorithm, but one which does not have such assumptions.
