### ISSUE TITLE
'Search files by name' does not handle '..' in paths

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#124863]
Issue Type: <b>Bug</b>

to repro:
- open folder
- create sub-directory `a`
- create file `a/foo.h`
- in vscode `ctrl-p`, search for `a/foo.h`: file is found
- search for `../a/foo.h`, file is not found
- search for `a/../a/../a/foo.h`, file is not found

it may seem stupid, but paths like this are generated by gcc if you `#include "../a/foo.h"`, these paths are included in the error output, and ctrl-clicking those paths fails to open file.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (26.92GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (25.23GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (25.23GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.3
vscode-nginx-conf|ahm|0.1.3
gitlens|eam|11.4.1
php-debug|fel|1.15.1
autoscrolldown|fox|1.1.1
cpptools|ms-|1.4.0
nginx-formatter|ray|0.0.13
edit-with-shell|ryu|1.3.0
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30307505
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by roblourens** [comment]
If you are clicking these paths in the terminal, then I think we just implemented it in https://github.com/microsoft/vscode/issues/96715. In that discussion, it sounds like we don't want to implement this for the quick open in general, though.
