### ISSUE TITLE
Killing a non-active terminal tab with middle click should not change the active terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124849]
Repro:

1. Open multiple terminals
2. Select a terminal in the middle
2. Middle click the end one, the active terminal will change

**Comment by meganrogge** [comment]
This code was responsible for setting the active instance (incorrectly) on middle click. To avoid this, I now will check if e.editorOptions.pinned and return before the active instance gets changed. https://github.com/microsoft/vscode/blob/c4da8f4ab15c7a6cace7d1ba508737c5da08a3f8/src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts#L155-L167

With the above in place, now this is the code responsible for incorrectly selecting the first list item when the selection was on a middle element and the bottom one is deleted with middle click.

https://github.com/microsoft/vscode/blob/3099c6f1c1bcf50cbbfbf7e6f6056c04e04574b6/src/vs/base/browser/ui/list/listWidget.ts#L612-L646

**Comment by meganrogge** [comment]
confirmed that returning early in onViewPointer fixes this problem
