### ISSUE TITLE
Search not work properly with auto guess encoding

### ISSUE THREAD

**Issue by opensharp** [microsoft/vscode#124806]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.56.2 (user setup)
- Commit: 054a9295330880ed74ceaedda236253b4f39a335
- Date: 2021-05-12T17:13:13.157Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Set "files.autoGuessEncoding": true
2. The encoding of source file is "GB 2312"
3. When I open the source file, search works fine
4. Otherwise, I can't search Chinese text

**Comment by roblourens** [comment]
Search doesn't support this setting. You will need to set `files.encoding`
