### ISSUE TITLE
Mac vsc cannot be moved or clicked on 

### ISSUE THREAD

**Issue by YifanL9** [microsoft/vscode#124827]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When the vsc windows overlaps with safari(bascially just part of the screen coding with vsc and the other half of the screen checking the html output in the web browser), sometimes neither safari nor vsc can be clicked on, moved. To exit this state, I can only use three fingers to swipe up the track pad and move one of vsc or safari into another desktop. I run into this issue several times recently. I am not sure if this is the problem with safari or vsc. But due to the fact that I only use vsc rencently and safari has never ran into this issue before with other app, I think this might be the issue of vsc. 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 10e362b9-25bb-49ea-8a96-fddbae7b4e26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.4.0
code-runner|for|0.11.3
vscode-auto-open-markdown-preview|hnw|0.0.4
cpptools|ms-|1.3.1
java|red|0.79.2
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.15.0
vscode-java-test|vsc|0.29.0
vscode-maven|vsc|0.30.1
vim|vsc|1.20.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.74`
