### ISSUE TITLE
Add build version to Windows installer to match winget manifest

### ISSUE THREAD

**Issue by gmeligio** [microsoft/vscode#124817]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10 21H1 (19043.1023)

Steps to Reproduce:

1. Update VSCode to latest version `winget upgrade Microsoft.VisualStudioCode`
2. Check for outdated packages `winget upgrade` and VSCode is listed because the build version exists on manifest but no in the installed version. There is a version mismatch because of this.

Maybe *build version* is not the right term. I mean the part after the minor version. Image example: `054a929533`

![image](https://user-images.githubusercontent.com/22875166/119949619-57923300-bf9a-11eb-9b4c-4eea90b2ec03.png)

**Comment by lszomoru** [comment]
This has been addressed.
