### ISSUE TITLE
Test: migration notification from shell/shell args to profile

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#124836]
Refs #123171

- [x] macOS @egamma 
- [x] linux @TylerLeonhardt 
- [x] windows @eamodio 

Complexity: 2

Authors: @meganrogge, @tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124836%0A%0A)

---
Set `terminal.integrated.shell.<platform>` and/or `terminal.integrated.shellArgs.<platform>` AND `terminal.integrated.defaultProfile.<platform>`. Create a terminal. You should see a notification that allows you to migrate the shell/shellArgs to a profile and set it as your default one. 

If the shell/shellArgs are identical to the path and args of a profile you've set and the profile name is the same, this migration won't happen. Otherwise, test that this new default is used when you next create a terminal.

**Comment by DemChing** [comment]
There's something strange when VS Code is dealt with `terminal.integrated.shell.windows`.

I was using Git Bash as default shell. Some days before, extra spacing is added after every letter.

I was thinking a font problem but it turns out setting `terminal.integrated.defaultProfile.windows` fix it.

**Comment by eamodio** [comment]
Apparently I needed to read better and needed to set `terminal.integrated.defaultProfile.<platform>` to show up -- which seems kind of odd to me, since I'm not sure who would have both versions set.

From talking with @meganrogge it seems like this is intentional behavior, but seems of limited use.
