### ISSUE TITLE
Request Feature to Open Terminal for specific Splited Plane

### ISSUE THREAD

**Issue by Ayush-Chugh-2006** [microsoft/vscode#124880]
Hi, Vs code theme,
thanks for the great text editortor,

I have an idea to be introduced in a new update, that if we split our window but when we open terminal it's of full width 
but there should be an option to open our terminal for a specific plane 
for eg.
![Eg screens shot without terminal](https://user-images.githubusercontent.com/69336518/120059537-dc9b4c00-c06f-11eb-9d2b-9a852829352d.png)

In this screenshot I have my code on one side and my HTML preview extension on another side but when I open the terminal it opens like this 
![Screenshot from 2021-05-29 11-21-47](https://user-images.githubusercontent.com/69336518/120059575-153b2580-c070-11eb-82eb-fa008852b499.png)

But I want here is that terminal's width should be according to my preview extension so that i will have more space to write and view code

There should be an option for the user to open a terminal for a specific plane as in the above example terminal should be opened only for my preview plane

I am waiting to see this feature in future updates

Regards,
Ayush Chugh

**Comment by Tyriar** [comment]
The panel may at some point be able to move around but it will never be able to enter the editor area. We'll be adding the ability to move terminals into the editor area soon though which will essentially let you accomplish what you're after. Tracked in https://github.com/microsoft/vscode/issues/10546

/duplicate
