### ISSUE TITLE
new terminal not activating conda base

### ISSUE THREAD

**Issue by perdigao1** [microsoft/vscode#124875]
Issue Type: <b>Feature Request</b>

When writting a python file.
Do "Create a new terminal"
At the bottom of the window and new terminal will appear (powershell or cmd) but, it tries to run 'conda activate base' but it fails, "'conda' is not recognized as an internal or external command, operable program or batch file."

But, if user clicks on the little arrow on the plus button (+) and choses command prompt, another new terminal will appear. But on this one it runs a command: "C:/Users/<user>/anaconda3/Scripts/activate " and then "conda activate base" which is successful.

How to set by default to run "C:/Users/<user>/anaconda3/Scripts/activate" everytime user creates a new terminal?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

**Comment by Tyriar** [comment]
/extPython

This may be related to setting the `terminal.integrated.inheritEnv` setting
