### ISSUE TITLE
Switch function key roles on MAC when visual studio code is in focus

### ISSUE THREAD

**Issue by Digital-Nomad** [microsoft/vscode#124826]
Could we possibly switch the function keys to their standard mappings when visual studio is in focus?

The default/regular keybindings is for the typical OS functions like increasing screen brightness and search function while the user has to press the fn key to switch to the regular function keys. 

I noticed that starcraft 2 actually switches the function keys to their standard mapping just as if you changed the settings like [here](https://support.apple.com/en-us/HT204436) and switches it back to normal when you exit the application. Could we possibly do the same thing while visual studio is in focus?

**Comment by redmer** [comment]
If you have a Mac with a Touch Bar, this is already possible to configure via 

- Open System Preferences.app > 
- Panel ‘Keyboard’ > 
- Tab ‘Shortcuts’ > 
- List Item ‘Function Keys’ >
- You can add VS Code.app there from the file picker behind the `+`-button.

Unfortunately, it doesn’t appear like such a setting is available for non-Touch Bar keyboards.
