### ISSUE TITLE
Insiders: cat.exe won't start, MSVCP140.dll is missing

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12481]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 7

Steps to Reproduce:

1. "code-insiders ."

Windows dialog box appears title "cat.exe - System Error" and message "The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem."

After clearing the dialog box, code-insiders appears to work fine.

Not sure why cat.exe is included in code-insiders and called in code-insiders.cmd.  This started after applying some Windows updates.

**Comment by chrmarti** [comment]
@bpasero Could this be related to the electron update? (Note that this is on Windows 7.)

**Comment by bpasero** [comment]
@gregvanl great catch. I did 2 things to fix this:
* compile cat.exe for 32 bit systems
* use static linking so that DLLs do not have to be installed on the target system

Downside is a size incrase to 200kb :-/
