### ISSUE TITLE
Inconsistent default syntax in changing Terminal Default Shell

### ISSUE THREAD

**Issue by datvuong** [microsoft/vscode#124805]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Microsoft Windows [Version 10.0.19043.985]

Steps to Reproduce:
I want to use cmd in the terminal instead of PowerShell. So, I proceeded as guided in the official docs by using `Select Default Profile`. There are 3 issues that occur. 
1. When I restart the VSC, it doesn't capture CMD as the default shell but PowerShell instead. 
2. Given that and an environment interpreter is used. When I click the `new terminal` button, a new terminal is opened but with a PS command to activating the virtual environment. 
3. When I run a line of code from editor by using 'ctrl + enter'. It also doesn't get the correct syntax for cmd.

I believe there is a setting to resolve this but I can't find that on the official docs page. Even so, the setting should be changed accordingly with the default profile selected. 

![image](https://user-images.githubusercontent.com/15795627/119933137-b319ec00-bfad-11eb-90f0-bca60b979d45.png)

One more thing, there is a new option to display terminals by `show tabs`. It looks nice. However, after I switch to that, there is no way to switch back from the UI. I need to navigate to the settings.json file to change the value to 'false'.

**Comment by meganrogge** [comment]
>One more thing, there is a new option to display terminals by show tabs. It looks nice. However, after I switch to that, there is >no way to switch back from the UI. I need to navigate to the settings.json file to change the value to 'false'.

Right clicking in the empty space of the tabs panel offers a hide tabs option

Please provide a [gif](https://gifcap.dev/) of you running `Select Default Profile` and your settings

**Comment by githubnew-alt** [comment]
#111396 #10759 #123368 #124911 #124910

**Comment by datvuong** [comment]
Sorry for my late response. Following is the gif of the default shell and `show tabs`.
![recording](https://user-images.githubusercontent.com/15795627/120773402-833d8c00-c54b-11eb-97ec-c4af340d7c22.gif)
![recording (1)](https://user-images.githubusercontent.com/15795627/120773972-019a2e00-c54c-11eb-9010-383a258d2621.gif)

**Comment by Tyriar** [comment]
This looks like an issue with whatever extension the play button comes from, probably code runner or python extensions

**Comment by datvuong** [comment]
@Tyriar Can you elaborate? I am not clear how to fix this? The python extension is from Microsolf.

**Comment by meganrogge** [comment]
@datvuong please file an issue in the repo of that extension.

**Comment by datvuong** [comment]
I just installed the insider version. Look like it is fixed. So, I assume it is not the extension issue.
