### ISSUE TITLE
VSCode "deleted" itself / failed update / unexpected uninstallation

### ISSUE THREAD

**Issue by odaruc** [microsoft/vscode#124869]
Issue Type: <b>Bug</b>

Have not used it for a week. Tried to open. Shortcut no longer valid at this location.
C:\Users\owner\AppData\Local\Programs\Microsoft VS Code
The folder was still there, but it was mostly empty until I manually reinstalled VSC.

My computer has Malware Bytes Premium on it. It doesn't show anything was quarantined.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.65GB free)|
|Process Argv|--crash-reporter-id 4361cabf-8268-4ea6-9b7e-1be3412cd7f5|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
mssql|ms-|1.10.1
python|ms-|2021.5.842923320
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.0
powershell|ms-|2021.2.2
platformio-ide|pla|2.3.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by joaomoreno** [comment]
Strange. Is everything working after reinstallation?
