### ISSUE TITLE
Terminate all processes in debug stack with keyboard shortcut

### ISSUE THREAD

**Issue by demortes** [microsoft/vscode#124951]
A quick search did not provide results. Please link if already requested.
VSCode can launch multiple processes with configurations + compounds. We should be able to terminate all running processes spawned from that with a keyboard shortcut.

**Comment by isidorn** [comment]
For that you should add a `stopAll` flag to the compound configuration.
Here's an example how VS Code does it for our launch configuration https://github.com/microsoft/vscode/blob/main/.vscode/launch.json#L542
After you do that any `stop` command will stop all.

However I do agree that we do not have a `Stop All` command that would stop all the running debug sessions. I guess that is a fair feature request and I can leave this open for now to gather more user feedback.
Thanks
