### ISSUE TITLE
Arch Linux Microsoft Extensions Not Showing Up

### ISSUE THREAD

**Issue by SamPro910** [microsoft/vscode#124940]
Does this issue occur when all extensions are disabled?: Extension related Issue

- VS Code Version: Latest
- OS Version: Latest Arch Linux w/ 5.12.8-arch1-1 kernel

Steps to Reproduce:

1. Go to extensions
2. Search for any Microsoft Extension (except Python support)
3. It's nowhere.

My Workaround: 
Go to https://marketplace.visualstudio.com/vscode
Download .vsix file
Install from VSIX in Vscode

**Comment by SamPro910** [comment]
Whoops! Accidentally Closed it!

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178
