### ISSUE TITLE
`vscode.ShellExecution` fails to properly escape arguments

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#124988]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.10.37

I am using `vscode.ShellExecution` API which takes an array of arguments:

```ts
        const fullCommand = [...cargoCommand, ...args];
        log.output.appendLine(JSON.stringify(fullCommand));
        exec = new vscode.ShellExecution(fullCommand[0], fullCommand.slice(1), definition);
```

Here's the logging of the arguments I am using: 

```
["cargo","test","--doc","--package","poloto","--","Plotter<D>::line_fill","--nocapture"]
````

As you can see, the `Plotter<D>` arguments needs escaping. However, no escaping happens, here's the retminal output upon spawining this task:

```
> Executing task: cargo test --doc --package poloto -- Plotter<D>::line_fill --nocapture <

warning: An error occurred while redirecting file 'D'
open: No such file or directory
The terminal process "/run/current-system/sw/bin/fish '-c', 'cargo test --doc --package poloto -- Plotter<D>::line_fill --nocapture'" failed to launch (exit code: 1).
```

**Comment by alexr00** [comment]
Does specifying the shell quoting for your arguments work?

https://github.com/microsoft/vscode/blob/902bb43b3b1472d66c621d255e157c7e84d68744/src/vs/vscode.d.ts#L6527-L6540

**Comment by matklad** [comment]
I haven't tried that -- from reading the API docs, i would expect the invocation I use to properly escape everything. The API which takes an array of arguments and then just concats them, being vulnerable to shell injection, feels very odd to me. 

I solved my immediate issue by switching from ShellExecution to ProcessExecution.

**Comment by matklad** [comment]
This is tagged as "needs more info", but I don't think I have anything else to add. To sum up:

The current [API signature and docs](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L6626-L6667) can be read as implying that the proper escaping is done, while this isn't the case

This is a much bigger deal than the usual "docs are unclear" -- this functionality is security sensitive, and opens the user up to shell injection attacks. If an extension passes user input as one of the arguments, then an attacker can craft a malicious string and execute arbitrary code.

**Comment by alexr00** [comment]
Shell quoting is complex, which is why the API gives you freedom to know better than we know. 

Using bash, I see the following work well using `ShellQuoting`:
```
		const task = new vscode.Task({ type: 'shell' }, vscode.TaskScope.Workspace, 'Shell quotes', 'test',
			new vscode.ShellExecution('echo', ["cargo", "test", "--doc", "--package", "poloto", "--", { value: "Plotter<D>::line_fill", quoting: vscode.ShellQuoting.Strong }, "--nocapture"],
			));
		vscode.tasks.executeTask(task);
```

This is as designed.

**Comment by matklad** [comment]
I still believe that this warrants at least a `**Security:**` note in the docs. I've written a long-form reasoning in this post: https://matklad.github.io//2021/07/30/shell-injection.html

**Comment by shoffmeister** [comment]
Sounds as if "**insecure by default**" should be added to the API, left right up down? Perhaps also in red font face?

If that ... really ... is what the API designer has in mind.

(Back in the good ol' days, there was a tool - Microsoft Visual Basic - that took a somewhat similar approach: By default, it was in "shoot yourself into a valuable body part" mode (well, it was the one and only mode). And most people did. Of course there is that subset of users who tended to understand the implications of that mode and used all their individual competence to still make very good use of that product. But then ....)
