### ISSUE TITLE
Language specific tokenColorCustomizations

### ISSUE THREAD

**Issue by Enzodtz** [microsoft/vscode#124997]
Hey,

I would like to change a token for a specific language of my editor, something such as: 

```
[dart]: {
  "editor.tokenColorCustomizations": {
        "keywords": "#FF0000"
  },
}
```

But it says that the feature is not supported for language specific.

I saw the discussion on #20652 where they say that you can't use theme specifically for a language because themes have effect on more than the editor, but I think that the token colors does not have effect more than the editor.

Thanks

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/20652#issuecomment-409862378 describes how to define language specific tokenization rules.

**Comment by aeschli** [comment]
Of course your syntax would be more intuitive, but will be difficult to implement right.
