### ISSUE TITLE
filename w/ space in front under the EXPLORER does't display correctly 

### ISSUE THREAD

**Issue by StrongNitPicker** [Microsoft/vscode#12496]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:22:54.636Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:

1. g++ -o formattest in tasks.json will create the executable named " formattest" (one space before f)
    but g++ -oformattest in tasks.json will create the executable named "formattest" (no space before f)
2. these both executables are displayed with no difference under the EXPLORER -> foldername, so
    I can't distinguish both different executables.
   the former executable " formattest" should be displayed one indent on screen because it has one
   space before f character in filename.
   many developers make mistake when building c/c++ program using -o option with g++/gcc
   some people use it with one space after -o like -o formattest, in this case, it will create " formattest" executable filename.
   
anyway, Linux OS can have a executable filename w/ space in front.
But, VSCode may overlook this...

**Comment by bpasero** [comment]
This has been fixed in our insider release. 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
