### ISSUE TITLE
Allow User Input in Command Palette (Quick Open) via Tasks

### ISSUE THREAD

**Issue by Kenobi-the-2nd** [microsoft/vscode#124907]
I use VS Code for almost all my work and make consistent use of macros, tasks, keyboard shortcuts, and so forth to help speed up my workflow. So far I have been very pleased with the options VS Code offers for streamlining the development process; however, there is one obstacle that has continued to leave me short of a fully task-oriented solution in many instances. This obstacle is the inability to enter text in the command palette (quick open) via tasks or macros. 

I have searched online for answers over the course of time I have spent trying to make this work but haven't yet been able to solve the issue. For example, the following simple task seems like it should pre-populate the quick open input field with the text given in args. It only opens the quick open but does not enter the text. 

`{
    "label": "inputText",
    "command" : "${command:workbench.action.quickOpen}", 
    "args": ["input 123"]
}`

Another option is to use the type command in a task: 

`{
    "label": "typeText",
    "command" : "${command:type}", 
    "args": ["input 123"]
}`

This does not enter any text (either in the quick open or in the editor). Also--just as a side note--I tried executing the type command from a macro (from a macros extension that I installed). It will enter text in the editor, but not in the quick open (using the same `type` command.

There is one way that I have found will enter text into the quick open, but it is based around a keybinding, which (as far as I am aware) cannot be used in a task:

`    {
        "key": "ctrl+shift+q",
        "command" : "workbench.action.quickOpen", 
        "args"   : "input 123",
        "when"   : "editorTextFocus"
        }`

Perhaps I am just missing something. Is it possible to automate text input to the quick open via tasks? If not, I would like to have this feature added. I feel that being able to have a task to automate text input should be essential in VS Code's task framework (or really any other task oriented system). 

I know that I am not the only developer that has encountered this issue. As I mentioned, it has set me back from developing a completely task-based solution on several occasions, leaving me to do some of the work manually. As one example, for some of my tasks, I would like to switch the language mode to a different language. The following command will allow me to open the switch language quick open:

`workbench.action.editor.changeLanguageMode`

But if I try to execute either of the top 2 input/type commands after this in a task sequence, it will not enter the text into the quick open input field. 

My OS is Microsoft Windows 10 Pro, Version	10.0.19043 Build 19043 (64 bit system).
My VS Code is Version: 1.56.2.

Please let me know if more information is needed. I would be happy to assist where I can. 

Thanks

**Comment by TylerLeonhardt** [comment]
this is interesting because the `workbench.action.quickOpen` does take an arg... for example:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/emmet/src/emmetCommon.ts#L127

but it seems like it's not working for tasks... @alexr00 any thoughts here?

**Comment by alexr00** [comment]
@Kenobi-the-2nd have you seen the `input` variable type for tasks? I sounds like exactly what you're looking for: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

Maybe `workbench.action.quickOpen` doesn't return a string? Tasks relies on any `${}` variables to return a string. However, I think `input` variables are perfect for this situation so it shouldn't matter.

**Comment by Kenobi-the-2nd** [comment]
Yes, I use input variables frequently in both my tasks and debug launch configurations. 

Drawing from my example above, I created a simple task to open 'Select Language Mode' in the quick open, then passed in 'SQL' as the argument:

`        {
            "label": "Change Language Mode",
            "command": "${command:workbench.action.editor.changeLanguageMode}",
            "args": ["SQL"]
        },`

I also tried it with an input variable (though I am not sure this is the correct way to go about it):

`        {
            "label": "Change Language Mode",
            "command": "${command:workbench.action.editor.changeLanguageMode}",
            "args": ["${input:stringSQL}"]
        },`

`    "inputs": [
        {
            "type": "command",
            "id": "stringSQL",
            "command": "${command:type}",
            "args": {"text": "SQL"}
        }
    ]`


The promptString and pickString input types work fine. My issue is that I can't write a task to automatically enter the text into the quick open field (so that I don't have to type it in manually each time).

**Comment by alexr00** [comment]
Thanks for the further elaboration. This is what `command` `inputs` are meant to solve. The reason it doesn't work for `workbench.action.editor.changeLanguageMode` is because that command doesn't actually accept any arguments. A working example with `workbench.action.quickOpen`:

Task:
```
        {
            "label": "Emmet Quick Open",
            "type": "shell",
            "command": "${input:quickOpenEmmet}",
            "problemMatcher": []
        }
```

Input:
```
        {
            "id": "quickOpenEmmet",
            "type": "command",
            "command": "workbench.action.quickOpen",
            "args": ">Emmet: "
        }
```

To get a command input variable with `args` working, you need to look at exactly what arguments the command can actually handle. In this case, `workbench.action.quickOpen` will accept a string. `workbench.action.editor.changeLanguageMode`, on the other hand, does not accept a starting language as an argument.

**Comment by Kenobi-the-2nd** [comment]
Yes, this makes sense. This helped me understand why some scenarios where I needed to enter text have not worked. Many of the cases have involved commands from other extensions. I see now that the inability to pass text as an argument was a limitation of the extension's command and not an issue with VS Code. 

I did some experimenting with the `workbench.action.quickOpen` command in both tasks and macros and it worked as described. So it appears the issue is just with `workbench.action.editor.changeLanguageMode`. Yes, I'd like to have the ability to pass a string as an argument to this command. I use this command frequently in my tasks and macros (for example, when scripting out a database table, or after formatting a JSON record split between multiple lines). Doing it manually is just an extra step that I have to think about, so it would definitely be nice to be able to automate it.

**Comment by Kenobi-the-2nd** [comment]
Also, is this the correct page for VS Code command documentation: https://code.visualstudio.com/api/references/commands? I checked there but could not find the `workbench.action.editor.changeLanguageMode` command.

**Comment by alexr00** [comment]
Yes, that's the correct page for VS Code command documentation, it contains documentation for all command that we consider to be API (they won't get breaking changes). `workbench.action.editor.changeLanguageMode` isn't one of our API commands, which is why it isn't listed there. Since we've had quite a bit of tasks and variable discussion in this issue, I'll open a new one to track the requested changes to `workbench.action.editor.changeLanguageMode`.

**Comment by alexr00** [comment]
New issue for the feature request: https://github.com/microsoft/vscode/issues/125486
