### ISSUE TITLE
Colourful tasks panel output

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#12499]
- VSCode Version: 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b)
- OS Version: Linux version 4.7.4-1-ARCH (builduser@tobias) (gcc version 6.2.1 20160830 (GCC) ) #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016

Steps to Reproduce:

1. Define some task in tasks.json - probably good if gives colorful output in term
2. Execute task to see plain colorless output which gets unreadable with size :sigh:

**Comment by chrmarti** [comment]
Tracked as #243
