### ISSUE TITLE
Breakpoints not vertically centered wity line number

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1249]
Linux
Version 0.10.4
Commit 18c4a65cb26517c25ce0f487feb6d169145bc647
![image](https://cloud.githubusercontent.com/assets/6461412/11779164/abaca40c-a259-11e5-86c9-348b6a5afd07.png)

The breakpoints could be nicer aligned with the line numbers

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/11809641/912d8086-a328-11e5-8240-47c6b40e4cf6.png)

**Comment by isidorn** [comment]
I do not see it on my linux -> sending back to backlog

@alexandrudima on Martin's machine I see that the line number is not centered inside its div, it goes to the upper right (as shown in the screenshot). My glyph is centered nicely thus the original misalignment Martin noticed.

**Comment by alexandrudima** [comment]
@aeschli Is this with out of the box settings on Linux?

**Comment by aeschli** [comment]
@alexandrudima Yes, no user/workspace configuration for any of the editor settings

**Comment by isidorn** [comment]
Alex forwarding this to you since I think it has to do with how we render line numbers.
Feel free to give back to me 😊
