### ISSUE TITLE
Add Copy Cell Output button or context menu in .NET Interactive

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#124917]
Due to this reply from https://github.com/dotnet/interactive/issues/862 issue. I just realized that this suggestion have to report to vscode repo.  I would like to suggest two options for the .NET Interactive extension:

1. Add a **Copy Cell Outputs** button in the context menu when right-click on the cell output

    ![image](https://user-images.githubusercontent.com/88981/120089202-9e169780-c12a-11eb-9347-9fb315997a85.png)

2. Add a **Copy** button on the top-right corner just like GitHub's code fence did.

    ![image](https://user-images.githubusercontent.com/88981/120089276-31e86380-c12b-11eb-8065-8e0e745aa932.png)

**Comment by DonJayamanne** [comment]
I vote for the ability to have some sort of a concept of commands in Output items.
This way we can have commands to:
* Copy output item (generic for text & images)
* Save output item (done in Jupyter for images)
* Open output item in plot viewer (done in Jupyter for Plots)

**Comment by amunger** [comment]
this was implemented
