### ISSUE TITLE
Line Decoration Width setting not working properly

### ISSUE THREAD

**Issue by Enzodtz** [microsoft/vscode#124983]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Linux x64 5.4.0-73-generic (Mint distro)

Steps to Reproduce:

1. Open VSCode with default settings and without extensions
2. Open `settings.json`
3. Add `"editor.lineDecorationsWidth": 0` into it.
4. Notice that VSCode marks it as `Unknown Configuration Setting`
5. Save the file
6. See the line numbers on the file change its width
7. Remove the line you've added
8. Save the file 
9. See that it doesn't turn back to default, leaving your VSCode bugged
10. Reload the window
11. See that the error persists

Please if possible I would like to know the default value of it to  update my settings with the default value, since it doesn't make it by itself.

Thanks

**Comment by alexdima** [comment]
`editor.lineDecorationsWidth` is an internal setting so that is why it shows "Unknown Configuration Setting" and commenting it out in `settings.json` results in no change. But internal settings pass through (so the behavior you are seeing is intentional). The default value is 10.

**Comment by Enzodtz** [comment]
I'm sorry, I didn't know it. I found this [here](https://stackoverflow.com/a/58114056/10659353). Changing it to the default value fixed it. Thanks
