### ISSUE TITLE
VSCode not recognising module "readline-sync" in NodeJs.

### ISSUE THREAD

**Issue by AnikNath114911** [microsoft/vscode#124936]
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 6.1.7601

This is my VS Code configuration and it shows me a error in **Node.js** that it cannot recognize module "readline-sync" but when I run normally (i.e. from the notepad and terminal) it works correctly.

PLS reply me that if it is my user configuration problem or bugs problem.

Regards.

**Comment by IllusionMH** [comment]
/needMoreInfo

What language are you using JS or TS.
Do you have this module installed in local `node_modules` folder?

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language are you using JS or TS.
Do you have this module installed in local `node_modules` folder?

**Comment by AnikNath114911** [comment]
I didn't wanted to say this but many of my problems are solved in windows 7 when i installed Microsoft .NET runtime 4.8
