### ISSUE TITLE
Extra letter spacing in terminal when open a directory

### ISSUE THREAD

**Issue by DemChing** [microsoft/vscode#124934]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open VS Code normally (by default, open with the directory that I was working)
2. Open a terminal

Expected:
![image](https://user-images.githubusercontent.com/62481633/120094740-cadfa480-c154-11eb-8eb2-6449702e71e9.png)

Actual:
![image](https://user-images.githubusercontent.com/62481633/120094704-9370f800-c154-11eb-8ff3-1f59c8ba2b62.png)

When I open VS Code without directory, the terminal works as normal.
Once I open a directory, the problem comes back.

Also, when I edit the setting and save it, all extra space removed immediately.
But it didn't solve the problem because any newly open terminal still have that problem.

Ways I tried but didn't solve it:
Disable all extensions
Changing the terminal to `PowerShell` or other shells

**Comment by IllusionMH** [comment]
/duplicate #120004

Should be fixed in Insider build https://code.visualstudio.com/insiders/
