### ISSUE TITLE
Right-clicking on text editor will sometimes instantly select one of menu options (without movement of the mouse)

### ISSUE THREAD

**Issue by dhiegomaga** [microsoft/vscode#124902]
Does this issue occur when all extensions are disabled?: No

Version: 1.56.2
OS: Linux x64 5.8.0-53-generic snap (Ubuntu 20.04)

**Description**: 

I really like that on Linux I can right-click and hold to select a menu option upon releasing the RMB, because it saves me one click. However...

When right-clicking on the text editor area, sometimes it will automatically select one of the menu options when releasing the RMB, without moving the mouse at all. That is because the menu is placed a little to the left of where it should, so that it is spanwed underneath the mouse pointer, and upon releasing the RMB, it wrongly selects one of the menu options. 

**Steps to Reproduce**:

0. Have the python extension (also happens in various other programming languages when using their extension). Also, possibly needs 2 monitors to work. 
1. Open a blank file, select python language, and put various new lines (or just open a python file with text)
2. Increase the zoom a little using Ctrl+'+', maybe 125% or 150%. I found it doesn't work with 100% zoom (no zoom).
3. Position the cursos more or less where is it positioned on this image (or maybe lower on the screen)

![Screenshot from 2021-05-29 18-08-15](https://user-images.githubusercontent.com/25873377/120077630-a380cd00-c0ab-11eb-92fc-1ac8504e12b6.png)

4. Right click to open the selection menu
5. Notice that it will automatically choose a menu option when you release the RMB, even without moving the mouse.

I know it's not the end of the world, but it is annoying that I can't right click without selecting any option, and sometimes this can really mess up coding by unintentionally selecting something that changes the code, etc.

**Comment by sbatten** [comment]
#113175
