### ISSUE TITLE
Terminal Tabs Can Have No Name

### ISSUE THREAD

**Issue by ColeSquared** [microsoft/vscode#124952]
Issue Type: <b>Bug</b>

When using the roblox-ts extension to start the rbxtsc process, it will create a new terminal tab, as expected. When the `terminal.integrated.tabs.enabled` setting is enabled, a new tab will be created. This tab will not display a name or an icon. When selecting rename, it will show that it has the name "roblox-ts" but attempting to rename it will not solve the issue. This issue does not occur with the `terminal.integrated.tabs.enabled` setting disabled. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 16f3a2f4-e39e-442b-803b-a856bd7f2de6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
pocketmine-ide|Ad5|0.0.6
aerogameframework|aer|0.0.24
vscode-rbxlua|Ama|0.5.0
stories|bar|2.23.0
vscode-django|bat|1.6.0
VSinder|ben|1.19.0
lit-html|bie|1.11.1
vscode-tailwindcss|bra|0.6.6
roblox-output-sync|cor|0.2.0
discord-tools|Dar|1.4.2
dart-code|Dar|3.22.0
flutter|Dar|3.22.0
vscode-eslint|dba|2.1.20
javascript-ejs-support|Dig|1.3.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
eJS-win|eJS|0.11.0
prettier-vscode|esb|6.4.0
roblox-api-explorer|eva|1.1.0
vscode-rojo|eva|1.13.3
vscode-firefox-debug|fir|2.9.4
vscode-pull-request-github|Git|0.26.0
glitch|gli|0.1.8
vscode-redux-devtools|jin|1.0.2
vscode-peacock|joh|3.9.1
roblox-lua-autofills|Kam|1.7.1
selene-vscode|Kam|1.1.0
edge|luo|0.3.2
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-wsl|ms-|0.56.3
azure-account|ms-|0.9.8
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.3076
waves|Mul|1.0.3
jsflowchart|MUL|0.1.6
vetur|oct|0.33.1
a-frame-for-vscode|pas|1.2.5
vue-beautify|pea|2.0.4
pixelbyte-love2d|pix|0.1.22
ejs-language-support|Qas|0.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
vscode-roblox-ts|rob|1.2.0
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.18
lua|sum|1.21.2
svelte-vscode|sve|105.0.0
vsfire|tob|1.4.1
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.2.14
WebTemplateStudio-dev-nightly|WAS|0.6.2113301

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30307505
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
