### ISSUE TITLE
BUG: "debug" button inside Jest unit tests files broken when using type:pwa-node... does not provide testNamePattern flag to the Jest CLI.

### ISSUE THREAD

**Issue by monarchwadia** [microsoft/vscode#124912]
# Affected component

This debug component.

![image](https://user-images.githubusercontent.com/4856944/120088640-b9e55380-c0c0-11eb-8bca-008bc0350f46.png)

# Expected behaviour:
Both of these statements should be true:
1. ✅  When my `launch.json` entry is configured with `type: node`, the "debug" button runs only the current test and ignores all other tests and suites.
2. ✅  When my `launch.json` entry is configured with `type: pwa-node`, the "debug" button runs only the current test and ignores all other tests and suites.

# Actual behaviour:
1. (✅  as expected) When my `launch.json` entry is configured with `type: node`, the "debug" button runs only the current test and ignores all other tests and suites.
2. (❌  NOT as expected) When my `launch.json` entry is configured with `type: pwa-node`, the "debug" button runs ALL the tests in my project, not just the selected test.

# Additional info
When observing behaviour in the terminal, it turns out that `type:node` DOES pass the following flags to jest, but `pwa-node` does NOT pass them in.

```bash
--testNamePattern "Successfully confirms an account with a confirmationToken" --runTestsByPath /Users/___/___/projectRoot/src/auth/auth.test.ts 
```

Here is the configuration i'm using:
```json
    {
      "type": "pwa-node",
      "runtimeExecutable": "node",
      "name": "vscode-jest-tests",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["--runInBand", "--no-cache", "--watchAll", "--forceExit", "--detectOpenHandles", "--colors"],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "env": {
        "MB_ENV_FILE": "dev/test.env"
      },
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest"
      }
    },
```

# OS details

Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

**Comment by githubnew-alt** [comment]
#124911 #124805
