### ISSUE TITLE
Is not possible to expand to "tab" character in bat, cmd files

### ISSUE THREAD

**Issue by johncze** [microsoft/vscode#124939]
Issue Type: <b>Bug</b>

It is not possible to expand to "tab" character in bat and cmd script files. The file uses tab indentation and I unchecked detect indentation and insert spaces options in settings and it doesn't still work, the tab is still expanded to 4 spaces. But I tested the mentioned options for other file types for example *.reg file and options work well so the tab is expanded or not expanded according to the settings of the mentioned options BUT it doesn't work for bat and cmd file types.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.82GB (12.40GB free)|
|Process Argv|--crash-reporter-id 1113e8e4-b9a9-4df5-8d80-931efc3c1b69 --crash-reporter-id 1113e8e4-b9a9-4df5-8d80-931efc3c1b69 --crash-reporter-id 1113e8e4-b9a9-4df5-8d80-931efc3c1b69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
bat-snippets|bat|0.2.0
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-language-pack-cs|MS-|1.56.2
rech-editor-batch|rec|0.0.19
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by alexdima** [comment]
When pressing <kbd>Tab</kbd>, the editor will insert the current configured value (tab or spaces) depending on the current opened file. The current configured value is rendered in the status bar:
* e.g. For indenting with tabs:
![image](https://user-images.githubusercontent.com/5047891/120157727-9b33a980-c1f3-11eb-8153-26a6f2ea3286.png)
* e.g. For indenting with spaces:
![image](https://user-images.githubusercontent.com/5047891/120157764-a4bd1180-c1f3-11eb-9d0b-d3c15a698807.png)


The indentation settings can be controlled by 3 options:
```js
// The number of spaces a tab is equal to. This setting is overridden based
// on the file contents when `editor.detectIndentation` is on.
"editor.tabSize": 4,
// Insert spaces when pressing `Tab`. This setting is overridden based on 
// the file contents when `editor.detectIndentation` is on.
"editor.insertSpaces": true,
// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be 
// automatically detected when a file is opened based on the file contents.
"editor.detectIndentation": true,
```

The indentation settings can also be controlled by extensions, so please make sure to disable all extensions before trying.

**Comment by johncze** [comment]
Hi, thank you for your response. Yeah, I know the settings about indentation, but here really doesn't work it. Nevertheless, the issue was in the extension "Rech Batch", so I disabled it and it works fine. So you are right that it can be caused by some extensions. So you can close the issue. Thank you
