### ISSUE TITLE
Integrated Terminal "bash: sudo command not found"

### ISSUE THREAD

**Issue by yearmfew** [microsoft/vscode#124935]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Linux Mint 20.1 x86_64

Steps to Reproduce:

1.
2.

I cannot use any command in vscode terminal. I can only use cd and ls. 
"sudo, npmi apt-get, install, root" neither of these are working. 
I cannot  launched with "code --disable-extensions" because it does not work.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
