### ISSUE TITLE
My VSCode not update automatically anymore, now i get a warning at the bottom in VSCode it self?

### ISSUE THREAD

**Issue by AngelinoVerhaeghe** [microsoft/vscode#124929]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
![update-warning](https://user-images.githubusercontent.com/84619396/120093149-9817bb00-c118-11eb-8c2f-494f6d98b248.PNG)

**Comment by AngelinoVerhaeghe** [comment]
![Version](https://user-images.githubusercontent.com/84619396/120093305-9e5a6700-c119-11eb-86d5-ad2ab4fe2067.PNG)

**Comment by ArturoDent** [comment]
Is your `Update: Enable Windows Background Updates` still enabled?

**Comment by joaomoreno** [comment]
What's the current value of the `Update: Mode` setting?
