### ISSUE TITLE
Add an option in the settings to avoid the creation of a new icon link after an update

### ISSUE THREAD

**Issue by Signum21** [microsoft/vscode#124909]
I have a folder in the start menu with Visual Studio Code and other programs. Every time I update Visual Studio Code, it automatically creates a new folder in the start menu with his icon and the icon in my folder gets hidden cause windows doesn't accept duplicates. 
Can you add an option in the settings to avoid this?

**Comment by joaomoreno** [comment]
Unfortunately, VS Code will do exactly what you have chosen the first time you installed it.

The fix for this is to uninstall VS Code (no worries, your settings and extensions won't be deleted) and reinstall choosing different options for the desktop shortcut.
