### ISSUE TITLE
Make notificiations less obtrustive for extension errors

### ISSUE THREAD

**Issue by fongandrew** [microsoft/vscode#124965]
Sometimes an exception in an extension leads to multiple notification alerts like so:

![image](https://user-images.githubusercontent.com/179327/120154131-62201880-c1a4-11eb-88b8-a0b0b62780d7.png)

I'm all for surfacing exceptions so they get fixed, but it'd be nice if this type of notification was less in your face. Or if there was an option to temporarily hide them. In many cases, the the extension remains mostly usable despite the exception -- in this particular case, only a single ESLint rule is throwing an exception while I type incomplete code. All the other rules are working. And once I finish typing, this rule works fine too. That is, the extension + lint rule are still 99% effective despite the bug. Except now I have a bunch of notification boxes covering up my screen that I have to dismiss.

I understand the logic of surfacing extension errors -- but as someone who is just the consumer of an extension and a lint rule, it's not necessarily easy for me to fix these (downgrading to an older version of an extension or rule might not be option for a given rproject). A more subtle error state would be nice.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-eslint/issues/1238
