### ISSUE TITLE
Markdown, angle brackets in table not shown in preview mode.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#12491]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:

1. Use the following snippet inside a markdown file (README.md):

|Method|Usage|Description|
|------|-----|-----------|
|ex<T>|test.ex<MyException>(lambda)|Check exception of type T is thrown.|
|ex_not<T>|test.ex_not<int>(lambda)|Check exception of type T not thrown.|
|ex_any|test.ex_any(lambda)|Check any exception is thrown.|
|ex_none|test.ex_none(lambda)|Check no exception is thrown.|

2. Press Shift+Ctrl+V to preview markdown, notice the < > brackets are missing. So far I've notice this is only broken for tables.

When I view this markdown README.md file online in BitBucket the angle bracket are shown correctly.

**Comment by rajinder-yadav** [comment]
After pasting looks like github has the same problem(rats!).
Please see attached pic for what you should see, bitbucket seems to do the right thing (below).

![bb](https://cloud.githubusercontent.com/assets/439226/18769254/8f157c04-80f9-11e6-84f3-645c7df9d366.png)

**Comment by chrmarti** [comment]
Using GitHub-like syntax seems to make sense.

**Comment by rajinder-yadav** [comment]
I disagree, making sense and have inconsistent behavior of angle bracket it a bug! 
This should be reopened and corrected, and let the github people know they have a bug!

**Comment by chrmarti** [comment]
To elaborate a bit: Markdown has several different syntaxes in use, we seem to be using one that is close to the GitHub one. You could file a feature request for VS Code supporting multiple syntaxes. The one a user needs depends on which other application (and their Markdown syntax) the user works with.

**Comment by rajinder-yadav** [comment]
Like the sound of this, do I just create a new bug asking for an feature enhancement?

**Comment by chrmarti** [comment]
@rajinder-yadav Yes, that would be great. Thanks. (Also, I just learned that we are using [CommonMarkdown](http://commonmark.org).)

**Comment by rajinder-yadav** [comment]
Sweet good to know! I'll file the enhancement :+1:
