### ISSUE TITLE
Only show custom editor context menu when relevant

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#124900]
Follow up from https://github.com/microsoft/vscode/issues/123301

Would it be possible to check the click target and only show the context menu when relevant? Including disabling the options when they aren't relevant

- Menu enablement: The target should be on a selection or an element that can accept input (textarea, input, contenteditable?)
- Copy/Cut: There should be a selection where clicked
- Paste: There should be text in the clipboard and the target should be able to accept input

The reason I ask is that this context menu can often do nothing and it's a bit of a pain to go through everything and prevent default to suppress the context menu.

**Comment by mjbvz** [comment]
In browsers, if there isn't a selection they try expand it to the clicked word. Should see if we can do this webviews too

**Comment by Tyriar** [comment]
The expand to selection behavior is mac only.

**Comment by mjbvz** [comment]
I'm closing this since we haven't see other extension authors also hitting this issue. If needed, I believe they can use `preventDefault` to block the default context menu

**Comment by Tyriar** [comment]
@mjbvz maybe we should have a list of things in the docs that outlines where webviews behaves differently to regular browsers to save extension authors from figuring this stuff out themselves (workers, context menus, etc.)?
