### ISSUE TITLE
Should I reinstall vscode?At this moment?Appear timestamp strange.

### ISSUE THREAD

**Issue by tisttsf** [microsoft/vscode#124950]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Reinstall windows
2.Updates may fil due to anti-virus software and/or runaway processes. Please try restartin your machine before attempting to update again. Please read the log file for more information:

C:\Users\*\AppData\Local\Temp\vscode-ino-updater-1622424376.log
C:\Users\*\AppData\Local\Temp\vscode-ino-updater-1622424376.log

vscode-ino-updater-1622424376.log
vscode-ino-updater-1622424376.log
vscode-ino-updater-1622424376.log
vscode-ino-updater-1622424376.log
vscode-ino-updater-1622424376.log
vscode-ino-updater-1622424376.log

Appear timestamp strange.
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by joaomoreno** [comment]
If you reinstalled Windows, I suggest to reinstall VS Code as well, yes.
