### ISSUE TITLE
Ubuntu running in WSL2 is not shown in settings sync synced data

### ISSUE THREAD

**Issue by fkromer** [microsoft/vscode#124962]
Does this issue occur when all extensions are disabled?: Yes/No

It seems like settings (extensions) of Ubuntu running in WSL2 are not synced with Settings Sync (Ubuntu not listed in synced machines).

![ex](https://user-images.githubusercontent.com/10199742/120150993-0a0d0480-c1ec-11eb-9ff6-77fb848909ab.PNG)

![ss](https://user-images.githubusercontent.com/10199742/120151023-14c79980-c1ec-11eb-8e0c-c53472d7fa45.PNG)

- VS Code Version:

Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

- OS Version:  Microsoft Windows 10 Pro (10.0.19042 Build 19042)

Steps to Reproduce:

1. install WSL2
2. install Ubuntu
3. install VSCode extension into Ubuntu
4. Settings Sync: Show Synced Data

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/90968
