### ISSUE TITLE
Add SVG support to built-in image preview

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#124901]
Adding the option of viewing a changed SVG as an "rich" image diff instead of the source diff.

**Comment by bpasero** [comment]
This is probably an extension candidate because imho we do not support SVG display in the core.

**Comment by 4086606** [comment]
It's supported on Github, that's my logic for requesting it anyway 😄

**Comment by lramos15** [comment]
You are welcome to submit a PR to add SVG support to the image preview. Otherwise I would recommend checking out the marketplace for some really nicely done SVG extensions.

**Comment by 4086606** [comment]
Ah, well I already have jock's SVG preview extension. I want to see a visual preview of SVG diffs in the working tree for VSC's Git integration. There is only code previews atm.

**Comment by 4086606** [comment]
I'm starting preliminary work on this because it seems too niche for engineer time 😄 I think your experimental Markdown Preview gives a good UX for this feature. Will ask questions here if I get confused

**Comment by lramos15** [comment]
My first step would be enriching the built in image preview to support SVGs if you want to explore that.

**Comment by 4086606** [comment]
Yeah good shout, I've already mapped nonexistent commands for SVG in `extensions/image-preview`

**Comment by 4086606** [comment]
@lramos15 some SVGs might be missing key view attributes (`viewBox`, `height` and `width`).
Should I make `getWebviewContents` produce a sanitised SVG container and add fallback view data?
This would mean pulling in the `dompurify@^2.2.9` NPM package, of course

**Comment by lramos15** [comment]
I think it's fine to come up with some defaults if one isn't provided, but I would avoid adding any additional npm packages as we want to limit the possible dependencies. You could of course show a failed to load message similar to what we do with images now if they cannot be loaded.

**Comment by 4086606** [comment]
If the file is missing a `viewBox`, the preview might not show the bounding box (which is a broken experience imho). The default for <img> with an SVG source is 300x by 150y. However, SVGs without a viewBox are canvas drawings and sketches that usually go >1000px.

I suppose I could prevent centering of SVGs without a `viewBox` - bind them to the top left and let them take the entire webview box. That's not broken entirely but is inconsistent with other previews.

**Comment by lramos15** [comment]
How do other previews go about doing it? They must create a viewbox of some sort? Sorry I'm not well versed in SVG viewing.

**Comment by 4086606** [comment]
Normally, the browser can use the SVG attributes to assign an intrinsic size. Without that data, the <img> renders exactly like a <iframe> (starting from the top left)

**Comment by 4086606** [comment]
@thunder-coding did you mean to 👍🏾 instead of 👎🏾

**Comment by lramos15** [comment]
@mjbvz Assigning you as you're better equipped to provide guidance here since you wrote the image preview.

**Comment by lramos15** [comment]
> Normally, the browser can use the SVG attributes to assign an intrinsic size. Without that data, the `<img>` renders exactly like a <iframe> (starting from the top left)

From my understanding that's all the image preview is doing. It just slaps an image tag inside the iframe. I assume including a default reasonable size if one wasn't included would be the way to go.

**Comment by 4086606** [comment]
https://user-images.githubusercontent.com/82655227/123811672-5af74200-d8eb-11eb-8eaf-d0fbd67cc963.mp4

This is the display behaviour I'm going for in the custom editor. I actually based this behaviour on the viewing behaviour of SVGs without a viewBox attribute in Chrome 91.

**Comment by 4086606** [comment]
I'm sorry to say this @mjbvz, but because the VSC repo doesn't use Github Discussions, this issue is likely to never get any real tangible feedback. I can crosspost this on Reddit and see what that does, but it's not likely

**Comment by mjbvz** [comment]
As the bot noted, this issue is a candidate for the backlog ( https://github.com/microsoft/vscode/issues/124901#issuecomment-851833135 ) so we are waiting for organic feedback to gauge how many people are interested before considering this

**Comment by 4086606** [comment]
I've demoed the reflow mode , what do you think?

https://user-images.githubusercontent.com/82655227/124367100-5cf33500-dc4c-11eb-9543-205d43474897.mp4

**Comment by 4086606** [comment]
@mjbvz is there a way I can elevate this to the default SCM diff editor for `*.svg`?

**Comment by 4086606** [comment]
@mjbvz Are staff that firm about the 20 likes? If so may I post this as an extension and credit this repository for `SVGPreviewManager`?

**Comment by SNDST00M** [comment]
Now that the new version's out, I hope this can get released soon.
I can publish this as an extension otherwise, seeing as Matt has some marketplace extensions with a similar scope.
What would you prefer @mjbvz @lramos15 @misolori?

**Comment by SNDST00M** [comment]
Alright extension it is, thanks for your patience and explanation

**Comment by Tyriar** [comment]
The bot misbehaved and didn't close this after 2 months and it's now been 4 and still hasn't reached the threshold.

I use https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer personally which works great for me and definitely text is the right default for SVGs as the preview cannot be edited (plus VS Code is primarily a text editor). So SVGs are a little different to raster images where a text editor can't be the default.

**Comment by SNDST00M** [comment]
Unfortunately the other SVG preview extensions didn't meet my needs, though I liked lishu's. I'm looking into publishing the PR I made as my own repo then baking in feature parity with lishu's svg-2 preview.

**Comment by SNDST00M** [comment]
Right, I've extracted #127388 into a separate SVG extension. Development will continue over the next few months until it combines the feature set of all extensions at the Marketplace.

https://marketplace.visualstudio.com/items?itemName=sndst00m.vscode-native-svg-preview
