### ISSUE TITLE
startup performance `code/willOpenNewWindow` duplicated on reload

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#124924]
Issue Type: <b>Bug</b>

Every time vscode is reloaded, an extra `code/willOpenNewWindow` is added to the startup performance raw perf marks: main.

1. Open vscode.
2. Open the startup performance editor.
3. Reload window
4. `code/willOpenNewWindow` is added again on each reload.

I would expect that this only shows the information from the most recent reload.

VS Code version: Code - OSS Dev 1.57.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
> I would expect that this only shows the information from the most recent reload.

No, the window reload is triggered from the main process which loads and reloads many windows and therefore it is expected that these marks show up repeatedly. Notice how it is under the `Raw Perf Marks: main`-heading, and _not_ under `Raw Perf Marks: renderer`
