### ISSUE TITLE
Native Notebooks - Can't save a newly created notebook

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#124918]
Version: 1.57.0-insider
*Note: The following below acts as expected in stable* 

### Steps to Reproduce:
1. Create new notebook
2. Save (Ctrl + S or File -> Save or File -> Save As) 

### Expected Behavior 
File type automatically set to "Jupyter" 

### Actual Behavior
File type is automatically set to "JSON"

**Comment by rebornix** [comment]
We added the `ipynb` to the file extension for `json` so we can get right colorization when they are opened in text editor, but then it's seen as JSON when saved.

**Comment by claudiaregio** [comment]
Oh dang hmm 
I guess my assumption is that if it's rendering as a JSON, the customer expectation would be to show colorization for JSON, but if it renders as notebook the customer expectation would be it would save as notebook. Sounds like these two things are mutually exclusive?

**Comment by roblourens** [comment]
Was this the right scenario @rebornix? 

![image](https://user-images.githubusercontent.com/323878/126842844-7e13d0f0-9e06-43c2-9e71-f5bb3a80c266.png)

This is reverting your change, still seems to work fine for me

**Comment by roblourens** [comment]
Was the issue just with showing JSON in the second box here? It still puts in .ipynb by default and saves correctly 
![image](https://user-images.githubusercontent.com/323878/128458218-cdf98749-b418-4f7c-80cc-7a625c01f4c1.png)

**Comment by roblourens** [comment]
Maybe seeing JSON there is confusing, also I think if you start typing and replace the file extension then it tries to save with JSON... better to just have a custom jupyter language here I think

**Comment by rebornix** [comment]
> Maybe seeing JSON there is confusing, also I think if you start typing and replace the file extension then it tries to save with JSON... better to just have a custom jupyter language here I think


Yes, I think this is the confusing part (especially if users delete the `ipynb` part from the file name).

**Comment by roblourens** [comment]
I added a new language with JSON highlighting 👍
