### ISSUE TITLE
Test: Inline Completion Provider API

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#124979]
* [x] anyOS @TylerLeonhardt
* [x] anyOS @alexr00

Complexity: 5

Authors: @hediet, @alexdima

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124979%0A%0A)

---

A proposed API to provide inline completions has been added.

![image](https://user-images.githubusercontent.com/2931520/120202270-b53aaf80-c226-11eb-8131-0c1c36762a89.png)

## Preparation
* Setup an empty extension that has `enableProposedApi` enabled and `*` as activation event.

## Test
* Ensure that `"editor.suggest.showInlineCompletions"` is not configured (= default settings).
* Implement and register an inline completion provider using [`languages.registerInlineCompletionItemProvider`](https://github.com/microsoft/vscode/blob/1e57955c798f88b6c44c84190875f97f71f4595a/src/vs/vscode.proposed.d.ts#L3674). [See here for a sample implementation.](https://github.com/microsoft/vscode-extension-samples/tree/f5e95b0e18899b0cf4779b5461b24c2511769472/inline-completions) Suggest at least two inline completions when suitable.
    * Setup an editor, fill in some text, position the cursor and invoke the command *Trigger Inline Completions*.
    * Verify that your inline completion item shows up iff your extension provides a completion item for the given context, but only if the suggest widget is not active.
    * Verify that the hover shows up when hovering on an (uncommitted) inline suggestion.
    * Verify that the next/previous actions in that hover menu work.
* Set `"editor.suggest.showInlineCompletions": true`
    * Verify that inline completions automatically show up as you type

**Comment by alexr00** [comment]
Works well! I converted the issue completion provider from GHPRI into an inline completion provider without any trouble.

**Comment by TylerLeonhardt** [comment]
I would have expected the InlineCompletionItemsProvider to have more functions on it... like one to handle:
* when a CompletionItem is accepted
* when the user asks for a different CompletionItem
* when the user cancels out of the InlineCompletionItems experience

But maybe it's too early?

**Comment by hediet** [comment]
In general, extension should just provide data. VS Code UI state should not be directly exposed to the extension host.

> when a CompletionItem is accepted

You can use the command for it.

> when the user asks for a different CompletionItem

We don't really want to expose that. For now there is window.getInlineCompletionsController. But we will iterate on that.

> when the user cancels out of the InlineCompletionItems experience

It was not requested yet.
