### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by SYW-JS** [microsoft/vscode#124932]
Issue Type: <b>Feature Request</b>

I hope that there would be ***settings about the sorting modes of the resources***,such as sorting by **the document type**.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
/needsMoreInfo

Sorting in explorer?
There is `explorer.sortOrder` and `type` should group files by type.

Is it what you expected or you are suggesting something else? If later - please provide more details.

**Comment by isidorn** [comment]
As @IllusionMH points out this is already possible. For more sorting options we have other issues, thus closing this as duplicate
