### ISSUE TITLE
Tabs are always replaced!

### ISSUE THREAD

**Issue by dahankzter** [Microsoft/vscode#12498]
- VSCode Version: 1.5.3 - 5be4091987a98e3870d89d630eb87be6d9bafd27
- OS Version: Mac OS Sierra 10.12

Steps to Reproduce:

1. No steps it just always replaces the current open file with the newly opened
workbench.editor.showTabs does not work either in user nor workplace settings.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by dahankzter** [comment]
Thx!

It seems the behaviour changed though. Perhaps making it clearer in the docs what a "preview" actually is. Maybe it is obvious if you are a heavy VS user but for me it was totally obscure.

**Comment by bpasero** [comment]
Did not change for ~3 months when we introduced tabs.

**Comment by dahankzter** [comment]
Well my vscode just suddenly started to do this.
I never used any custom settings at all yet this started to happen.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/18781372/b7b4d2a8-8181-11e6-832d-d8ec047680b8.png)

**Comment by dahankzter** [comment]
Not a miracle just vscode not being stable.
