### ISSUE TITLE
terminal.integrated.startIn

### ISSUE THREAD

**Issue by artagnon** [Microsoft/vscode#12494]
We can have it start it:
1. Project root.
2. Current directory (which is usually much deeper inside the project root).

This issue is a feature request for the second.

**Comment by Elarcis** [comment]
Tested on Windows 7, VSCode 1.5.3, you can right-click on the desired folder and open the terminal with it as the working directory.

**Comment by Tyriar** [comment]
@artagnon I put together an extension a few days ago for just this https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

@Elarcis that uses the external terminal, not the integrated terminal.

**Comment by gandhis1** [comment]
Does it really make sense for this functionality to be provided by an extension and not available built-in?

**Comment by Tyriar** [comment]
@gandhis1 eventually you will be able to set whether you want to the context menu open terminal action to use the integrated or external terminals https://github.com/Microsoft/vscode/issues/8132 after this work is done it would be trivial to add it.

In the meantime,  using the new terminal API it took 10 minutes from concept to published extension which covers the requirements. Doing it properly in the editor will take a few hours and then take 2-4 weeks to release.
