### ISSUE TITLE
Show recently opened folders from windows taskbar

### ISSUE THREAD

**Issue by jbsulli** [Microsoft/vscode#12492]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Home (1607)

Steps to Reproduce:

1. Have Windows OS
2. Pin VSCode to taskbar
3. Open and close multiple folders
4. Right click VSCode taskbar icon
5. Notice no recently opened folders/files :(

And it would be cool if shift-clicking the taskbar icon would open another instance. But that's even more minor than this minor feature request.

Great Job on it so far though! Loving it!

**Comment by bpasero** [comment]
This should work with https://github.com/Microsoft/vscode/issues/241
