### ISSUE TITLE
Find: Replace text field clipped

### ISSUE THREAD

**Issue by artagnon** [Microsoft/vscode#12495]
<img width="998" alt="screen shot 2016-09-22 at 9 12 56 pm" src="https://cloud.githubusercontent.com/assets/37226/18771028/85306f0e-8109-11e6-9ecb-dd9f7337b8e3.png">

**Comment by chrmarti** [comment]
Reproduced in todays insiders by expanding the replace part and then reducing the window's horizontal size to the point where the actions wrap.

**Comment by alexandrudima** [comment]
Dup of #2338
