### ISSUE TITLE
Add an option leading to Github page of vscode.

### ISSUE THREAD

**Issue by Siddhant-Jha** [microsoft/vscode#124938]
Please add an option in the **'Help'** menu on the title bar that will lead to the **Github Page of "vscode"**.
We can name that option **'Github'** or **'Contribute'**.

Do let me know if I can work on this feature.

![Screenshot (32)](https://user-images.githubusercontent.com/60434913/120107592-3b9bb680-c17f-11eb-9d67-ce322e25da81.png)

**Comment by JacksonKearl** [comment]
Thanks for the feedback! I believe the "Search Feature Requests" link does a good gob of linking back to the GitHub repo, and I'm not sure that a link for "Contributing on GitHub" really belongs in the Help menu. As such I'm going to close this out. 

Happy coding!
