### ISSUE TITLE
Test: Workspace trust - empty window

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#124984]
Refs: https://github.com/microsoft/vscode/issues/106488

- [x] anyOS @bpasero 
- [x] anyOS @deepak1556

Complexity: 4

Authors: @lszomoru, @sbatten 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124984%0A%0A)

---

This milestone we have added the capability to set the default trust state of the empty window, and to trust the empty window.

## Empty window
* Verify that the `security.workspace.trust.emptyWindow` is set to `false`
* Open a new empty window
  * verify that no workspace trust modal dialog is being shown 
  * verify that no banner is being shown at the top of the workbench
  * verify that the status bar container the "Restricted Mode" item
  * verify that the hover on the status bar item is using the "window" terminology
* Click on the "Restricted Mode" status bar item to open the workspace trust editor
  * verify that the trusted box on the left hand side is using the "window" terminology
  * verify that the links in the "restricted mode" box on the right hand side are working as expected
* Click on the "Trust" button
  * verify that the window successfully transitioned to a trusted window
    * A "Don't Trust" button is being shown in the "Restricted Mode" box on the right hand side
    * "Restricted Mode" status bar item is not shown
    * All extensions that were waiting for trust were activated
  * verify that no entry has been added to the list of "Trusted Folders & Workspaces" at the bottom of the editor
* Click on the "Don't Trust" button
  * verify that the window successfully transitioned to "Restricted Mode"
    * A "Trust" button is being shown in the box on the left hand side
    * "Restricted Mode" status bar item is shown
    * All extensions that require workspace trust have been disabled
  * verify that no entry has been removed to the list of "Trusted Folders & Workspaces" at the bottom of the editor

## Window reload
* Open a new empty window
* Open the workspace trust editor by clicking on the "Restricted Mode" in the status bar
* Click on the "Trust" button again to switch to a trusted environment
* From the command palette choose to "reload the window"
  * verify that the new window is in the "Restricted Mode"
    * A "Trust" button is being shown in the box on the left hand side
    * "Restricted Mode" status bar item is shown
    * All extensions that require workspace trust have been disabled

## Setting - security.workspace.trust.emptyWindow
* Update your user settings with `"security.workspace.trust.emptyWindow": true`
* Open a new window after the setting has been updated:
  * verify that the window is not in "Restricted Mode"
    * A "Don't Trust" button is being shown in the "Restricted Mode" box on the right hand side
    * "Restricted Mode" status bar item is not shown
    * All extensions that were waiting for trust were activated
* Click on the "Don't Trust" button
  * verify that the window successfully transitioned to "Restricted Mode"
    * A "Trust" button is being shown in the box on the left hand side
    * "Restricted Mode" status bar item is shown
    * All extensions that require workspace trust have been disabled
  * verify that no entry has been removed to the list of "Trusted Folders & Workspaces" at the bottom of the editor
* From the command palette choose to "reload the window"
  * verify that the window is not in "Restricted Mode"
    * A "Don't Trust" button is being shown in the "Restricted Mode" box on the right hand side
    * "Restricted Mode" status bar item is not shown
    * All extensions that were waiting for trust were activated

**Comment by bpasero** [comment]
> Verify that specifying the setting as a workspace setting does not have any effect

I think that you cannot configure this in an empty window because there are no workspace settings.
