### ISSUE TITLE
Goto Symbol doesn't show all functions defined inside the file.

### ISSUE THREAD

**Issue by khalilravanna** [Microsoft/vscode#125]
Using "Go To Symbol..." (⇧⌘O) it seems to only recognize certain ways of declaring functions in javascript.

<img width="607" alt="screen shot 2015-11-18 at 5 49 37 pm" src="https://cloud.githubusercontent.com/assets/1890516/11258194/d1923174-8e1c-11e5-9b2e-a17ba30a97bc.png">

All three functions should show up when you search "searchable", right? Only "searchable" and "alsoSearchable" show up however.

In this case it looks like these cases work:

1. Anonymous function assigned as a property on and object when the object is instantiated.
2. Named function assigned as a property on an object after it's instantiated.

And this case doesn't work:

1. Anonymous function assigned as a property on an object after it's already been instantiated.

This works in Sublime Text and I'd love if it could work in VS Code as well as it's one of the main ways I navigate my javascript code (especially the thousands of lines of code for my game).

**Comment by yupal** [comment]
This issue is present in this case too:
When I have a fuction defined with

`var testFunction = function() {}`

Here is a screenshot with the issue:
[http://imgur.com/wS66ROM](http://imgur.com/wS66ROM)

**Comment by egamma** [comment]
Can you please try to reproduce using the new Salsa JS infrastructure: https://code.visualstudio.com/updates/#_javascript-salsa-preview

**Comment by yupal** [comment]
Using Salsa JS on the same example as I wrote before I get IntelliSense knowing the function, but now when I try to go to symbol I got no suggestion ( the go to symbol ( @ ) is empty ).

**Comment by egamma** [comment]
Moving to salsa for investigation

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7003
