### ISSUE TITLE
Test: Suggestions Inline Preview

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125001]
* [x] anyOS @jrieken 
* [x] anyOS @kieferrm

Complexity: 2

Authors: @hediet, @alexdima

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125001%0A%0A)

---

The inline preview previews the currently selected completion item in the suggestion widget.

## Preparation
* Configure `"editor.suggest.showSuggestionPreview": true`

## Test
* Trigger the suggestion widget
    * Verify that the currently selected completion item is previewed as inline text if there is a perfect prefix match
    * Verify that multi-line snippets are previewed with the correct indentation
    * Verify that the suggestion widget list is rendered to the top when previewing multi-line snippets
* Verify that you can configure `"editor.suggest.ghostTextExpanded": false` to show completions in a single line. 
* @jrieken Some programming languages use some overwriteAfter logic (I think you mentioned Dart). It would be great to have a bit of coverage of some edge cases that you might be aware of.

**Comment by jrieken** [comment]
> @jrieken Some programming languages use some overwriteAfter logic (I think you mentioned Dart). It would be great to have a bit of coverage of some edge cases that you might be aware of.

Will do. btw - this can also be done with TypeScript and `con|sole`-suggestions

**Comment by kieferrm** [comment]
Overall, this works as announced. Good work. I struggle a bit with the suggest widget appearing above or below depending on whether or not there is a multiline completion. Combining this with the precise prefix match and imprecise typing, I sometimes get it on top and sometime below looking for the same completion because I typed one character more or less.
