### ISSUE TITLE
缺失功能

### ISSUE THREAD

**Issue by yongzhidai** [Microsoft/vscode#12509]
1. 打开文件时，不能根据文件编码来显示，导致出现乱码，需要手动设置编码
2. 不能将文件拖拽到窗口自动打开文件
3.临时未保存的文件，不能像notepad++那样，关闭重新打开后依然存在
4.点击资源管理器里的文件，是重用之前的tab，而不是新开tab

**Comment by vilic** [comment]
1. 请用英文... 我不确定 vscode 团队里有人懂中文, 并且用中文不便于和社区其他人交流. Please write in English... I'm not sure if any one in the vscode team understands Chinese, and using Chinese will make it harder to communicate with others in this community.
2. 提交新 issue 前尽量先进行搜索, 看看是否有重复的. Please try your best to make sure there is no duplicate of the idea/report before creating a new issue.
3. 一个 issue 通常只对应一个问题, 方便跟踪. A single issue should usually describe a single idea/report, this will make tracking progress easier.

**Comment by chrmarti** [comment]
Please create separate issue for each.
