### ISSUE TITLE
Cannot drag and drop files to upload them in web

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125041]
Testing #124839

* drag a file from Finder
* drop it in the Explorer to upload it
* it does not get uploaded

https://user-images.githubusercontent.com/5047891/120295645-9f30fb80-c2c7-11eb-9250-0222810fd57a.mp4

**Comment by alexdima** [comment]
Also folders do not work for me.

**Comment by bpasero** [comment]
@isidorn any clue why the drop feedback is gone?

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/e7b775adebfbefde74f9797957cc23b34fde65fb

**Comment by isidorn** [comment]
Thanks @bpasero for fixing
