### ISSUE TITLE
Double Clicking On A Word Does Select The Entire String, Not Just The Word

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125052]
Testing #125023

Usually, double clicking on a word selects the entire word (with `/` being treated as word separator).
This is the default behavior for most text inputs in VS Code (search bar / command bar).
(Triple clicking the entire line & Quadruple clicking everything)

However, in the Workspace Trust table, when editing a path, double clicking does always select the entire path. This makes it difficult to replace a path segment.

**Comment by sbatten** [comment]
ah, looks like an artifact of the activate method for the row overriding the double click behavior of the text box

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/195477a0e9671d42d68ef140f4f3ebc71543de96
