### ISSUE TITLE
Deleting a terminal tab is too easy

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#125069]
Testing #124716

Windows

I was able to delete a terminal tab by selecting it and pressing the delete key, or by pressing it and clicking the middle mouse button. This seems like something that would be quite easy to do by mistake (imagine the user thinks that focus is on some other element but it is on a terminal tab for example). Deleting a tab is quite destructive (command history is gone for example). Perhaps the user should be required to press delete + ctrl (or some other chord) and the middle mouse button should not delete the tab. Either that, or the user should be prompted to ask if they really do want to delete that terminal.

**Comment by Tyriar** [comment]
Let's make sure we respect `terminal.integratedf.confirmOnExit` for tabs, I still think the default should not prompt though, just like the existing behavior.
