### ISSUE TITLE
Allow to drag groups when there is not enough space next to tabs

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125062]
Testing #124848

I often have many editors open. If there is no free space in the editor group, I cannot start the drag operation.
Impressive what else I can drag though, nice work!

![image](https://user-images.githubusercontent.com/2931520/120306254-f50aa100-c2d1-11eb-8b31-d0bad6ab500a.png)

**Comment by bpasero** [comment]
Fair. We actually always allowed you to drag groups within the grid, so this is a somewhat existing issue with the way the tabs lay out in a group. 

As a workaround: with tabs wrapping enabled (`workbench.editor.wrapTabs: true`) there will be enough space after the last tab to drag:

![image](https://user-images.githubusercontent.com/900690/120324684-2f326d80-c2e7-11eb-99f7-643a2245bf7c.png)

**Comment by hediet** [comment]
I have too many tabs, wrapping them would not make things more clear :D

I'd be fine with an area that is just a few couple of pixels wide, but large enough to drag the editor group. That is also not the best UX, but at least it makes the feature usable.

**Comment by bpasero** [comment]
//cc @misolori for UX brain power. I would not be a big fan of a solution though that always takes horizontal real estate away permanently only to enable this feature.

**Comment by hediet** [comment]
>  I would not be a big fan of a solution though that always takes horizontal real estate away permanently only to enable this feature.

I agree! This much additional space would already be enough imho (maybe even less):

![image](https://user-images.githubusercontent.com/2931520/120327152-bda7ee80-c2e9-11eb-9dc0-987f833b48de.png)

**Comment by misolori** [comment]
Maybe I'm missing something, but can't you hover over the last item and it will scroll to the end when there is overflow?

**Comment by hediet** [comment]
@misolori the problem is dragging the entire editor group to a different window, not dragging tabs inside a group. If there are too many tabs, there is no free space that could be grabbed to trigger dragging the editor group.

**Comment by misolori** [comment]
@hediet ah, i see the problem now! I do think adding some extra space to the left would help there, right now it looks like the two sides of the editor toolbar are not even. I would also maybe suggest to make the empty area around the toolbar draggable as well (just like grabbing a title bar in Chrome/Other apps). Below, clicking + dragging anywhere around the red area would initiate the drag:

![image](https://user-images.githubusercontent.com/35271042/120358723-afdb7480-c2bb-11eb-8d66-bb967ececca6.png)

**Comment by bpasero** [comment]
I think that is worth a try and the padding inconsistency is a good finding as well, maybe both can be fixed. Setting help wanted for a reasonably small PR in this area.

Code pointers:
* `src/vs/workbench/browser/parts/editor/tabsTitleControl.ts` renders tabs
* [here](https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/browser/parts/editor/titleControl.ts#L254-L254) we enable group dragging

**Comment by byehack** [comment]
this problem can solve by adding `workbench.editor.scrollBeyondLastTab` like `editor.scrollBeyondLastLine` & `editor.scrollBeyondLastColumn`
