### ISSUE TITLE
Workspace setting for default filter text for Debug Console

### ISSUE THREAD

**Issue by mikeesouth** [microsoft/vscode#125035]
I frequently use the debug console in VS Code to get output from my application but it's often cluttered with various log messages from services that I cannot control. These unwanted entries are easily filtered in the text field "Filter (e.g. text, !exclude)" box. I would like a setting to configure this default filter text per workspace. Currently I have to manually configure this filter each time I start VS Code.

I could not find this in either default settings or through an extension.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
I would actually prefer if we would just preserve the filter across vscode reloads.
I am open to Pull Requests that solve this. Code pointer
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/repl.ts#L681

**Comment by mikeesouth** [comment]
Great. I would be fine with it being preserved through reloads 👍

**Comment by jeanp413** [comment]
Created PR #125221 fixing this

**Comment by isidorn** [comment]
@jeanp413 thanks a lot for that 👏  I have commented on the PR.

**Comment by andreamah** [comment]
I am trying to verify this feature right now, but it isn't persisting upon reload on my side (running off of latest commit on main).

Steps:
1. Debug extension
2. Add filter to debug console
3. Stop debugging
4. Use command palette to reload
5. Debug console's filter is empty again.

Is my flow correct?

**Comment by isidorn** [comment]
@andreamah thanks for trying to verify this. However this fix is not yet released. Sorry for not specifying. Though we have this `unreleased` label that should help with that.
So I will close this issue, and it would be great if you can try it out again tomorrow. Thank you!
