### ISSUE TITLE
Confusing ports attributes settings

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125077]
Testing #124976

I find this pair of settings quite confusing:

- Why are there two at all?
- Why does the `other` appears first?
- Why does the `other` have a nice `Add Item` button, but the regular setting doesn't?

![image](https://user-images.githubusercontent.com/22350/120325383-6fb8c980-c29c-11eb-896d-e6f72b77fcd0.png)

**Comment by joaomoreno** [comment]
Having changed the protocol via the table UI, I now understand the syntax:

![image](https://user-images.githubusercontent.com/22350/120325944-05ecef80-c29d-11eb-97ed-748148eb036b.png)

Couldn't we simply have a `"*"` key in the `remote.portsAttributes`, instead of a `remote.otherPortsAttributes` setting?

**Comment by alexr00** [comment]
We allow port numbers (`"3000"`), port ranges (`"3000-3005"`), and regular expressions to match command lines(`".+\\/server.js"`) to be properties of `portsAttributes`, which means `*` would be overloaded. Originally I had used `"others"` as a keyword in the `remote.portsAttributes` properties instead of it's own setting, but that received negative feedback.

**Comment by alexr00** [comment]
I think this is considerably improved now that there are better snippets.

@sandy081 is there a way I can influence the ordering of settings in the settings editor?

**Comment by sandy081** [comment]
AFIK You can define order only for settings sections and not for settings. @roblourens correct me if I am wrong about settings editor.

**Comment by roblourens** [comment]
Alphabetical order :(

**Comment by roblourens** [comment]
> Why does the other have a nice Add Item button, but the regular setting doesn't?

We only have a control for flat objects. Not sure how we would display one like this.

**Comment by alexr00** [comment]
This is already improved with better snippets. Closing since we cannot control the order.
