### ISSUE TITLE
Fallback to chokidar on Windows when .NET 4.5 not installed

### ISSUE THREAD

**Issue by mesaamesa** [Microsoft/vscode#12504]
- VSCode Version: 1.5.2
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce: open a file
1. I do not have administrator rights.
2. Annoying warning message asking for Microsoft .NET Framework 4.5 necessary.

how to disable this warning message?

**Comment by chrmarti** [comment]
We could add a 'Don't Show Again', I guess.

**Comment by bpasero** [comment]
@mesaamesa the impact of not having .NET 4.5. is that all file watching will be disabled on Windows. That means a considerably worse experience compared to when file watching is available. We could however maybe just fallback to using chokidar in that case...

**Comment by bpasero** [comment]
For October I added a way to ignore this message per workspace. It is still strongly recommended to install .NET 4.5 though.

**Comment by mjbvz** [comment]
We now use the node system file watcher (#28947). I do not believe this issue is relevant anymore
