### ISSUE TITLE
Ignore updates for built-in extensions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12507]

**Comment by sgtoj** [comment]
I assume this issue is causing this GUI issue:

![No Extension to Update](http://i.imgur.com/YhNNgki.png)

**Comment by joaomoreno** [comment]
@sgtoj Yes, exactly!

**Comment by isidorn** [comment]
Adding verified by code review - and yesterday I updated node-debug and I was not notified about  the update in extensions viewlet.
