### ISSUE TITLE
Quotes issue.

### ISSUE THREAD

**Issue by spacekestrel** [microsoft/vscode#125008]
I recently went into vs code and tried typing quotes. Usually, when you click on the button of quotes, they immediately appear and you can write something in them. But now, for some reason, you need to press the quotes key twice and then you need to additionally press the quotes inside to write something inside. My only extensions are Dart, flutter and color brackets.
Disabling extensions does not help.

Version: 1.56.2 (user setup)
Fixation: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by alexdima** [comment]
@spacekestrel This depends on the programming language, on your settings and on your keyboard layout.

Could you close all instances of vscode and launch `code --user-data-dir <specify-some-absolute-directory-path-here>` and then open a `.js` file and type `"` ?

**Comment by spacekestrel** [comment]
> 
> 
> @spacekestrel This depends on the programming language, on your settings and on your keyboard layout.
> 
> Could you close all instances of vscode and launch `code --user-data-dir <specify-some-absolute-directory-path-here>` and then open a `.js` file and type `"` ?

It is the same. I am working with Dart language, settings are unchanged and keyboard layout is en.

**Comment by alexdima** [comment]
@spacekestrel In a fresh vscode installation, without any extensions and without any settings, typing `"` on an English US keyboard will insert `"|"`. 

To double check that, could you please create a screen recording showing:
- your empty user settings, 
- your empty workspace settings (if you open a workspace),
- your empty folder settings (if you open a folder)
- your extensions all being disabled
- opening a single `.js` file
- typing `"`
 

Here is me doing it:

https://user-images.githubusercontent.com/5047891/120905483-9be49980-c652-11eb-9b21-ec539b70d3ae.mp4

**Comment by spacekestrel** [comment]
> 
> 
> @spacekestrel In a fresh vscode installation, without any extensions and without any settings, typing `"` on an English US keyboard will insert `"|"`.
> 
> To double check that, could you please create a screen recording showing:
> 
>     * your empty user settings,
> 
>     * your empty workspace settings (if you open a workspace),
> 
>     * your empty folder settings (if you open a folder)
> 
>     * your extensions all being disabled
> 
>     * opening a single `.js` file
> 
>     * typing `"`
> 
> 
> Here is me doing it. I don't have any keybinding customizations. Do you?:
> Kapture.2021-06-05.at.23.05.51.mp4

Nevermind. I only now noticed that i have uk english layout instead of us or international. Switched to us and all start working just fine.
