### ISSUE TITLE
Align hover with status bar entry

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125090]
Testing #125005

Hover should be left-aligned with the status bar area. Pulling the mouse upwards will make the hover disappear because the hover isn't right above the mouse.

![recording (4)](https://user-images.githubusercontent.com/22350/120443029-1ce21f00-c33b-11eb-8b50-e0a34350a5c8.gif)

**Comment by Tyriar** [comment]
I reverted the fix here, IHoverDelegate is used implicitly elsewhere. I'm not sure why this is needed also, can you do a PR for this? I'd prefer not to have another mandatory property if it can be avoided to keep things simple.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/commit/60a36219813374a06ea2c08160e9963e60c1b62c

**Comment by aeschli** [comment]
@Tyriar Sorry for the breakage, `yarn watch` didn't catch the implicit use in terminal.
I discussed the option prior with @alexr00. Sorry, didn't know you also had a stake in it.

I made the placement optional.

**Comment by Tyriar** [comment]
@aeschli does this belongs more in `IHoverDelegateOptions` as it's defining the positioning of the hover like `HoverPosition`?

**Comment by aeschli** [comment]
The  `IHoverDelegateOptions` is an input for the hover delegate. (Used when the hover delegate is asked to show the hover `hoverDelegate.showHover`)

What could be done that each hover delegate does the positioning itself in `hoverDelegate.showHover`. But that would duplicate the positioning code `(hoverOptions.target)x = mouseX + 10;` at many places. Right now `hoverDelegate.showHover` is just a forward to the hover service.
