### ISSUE TITLE
Trust banner: appears a bit hectic

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125096]
It seems to me that opening an empty window with a file first opens the file and then renders the banner. Can we not eagerly show the banner on startup when we know that we open an editor?

Now it feels like something is pushing down the UI after I had opened VSCode:

![recording](https://user-images.githubusercontent.com/900690/120333751-4d509b80-c2f0-11eb-8ae3-de4bd8c4bef8.gif)

**Comment by sbatten** [comment]
Currently we optimize for the trusted flow which does not show the banner. When in restricted mode, we want to avoid slowing down the rest of the workbench so we do not delay anything just to wait for restricted mode (trust status, which takes some time to fully calculate). The current restricted mode flow IMO optimizes for perceived performance.
