### ISSUE TITLE
Why has NotebookExecuteHandler a this and a controller of type NotebookController

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#125053]
Testing #124993

I assume they are the same instance so to avoid confusion this might be enough.

**Comment by jrieken** [comment]
Yeah, the `this: NotebookController` only exists for TS and is our way to say that we invoke the function on the controller itself. Basically we allow these two styles

```
// use "typed this"
kernel.executeHandler = function (cells) {
     this.createNotebookCellExecution(cells[0]);
}

// use controller argument
kernel.executeHandler = function (cells, _document, controller) {
      controller.createNotebookCellExecution(cells[0]);
}
```

**Comment by jrieken** [comment]
We could remove the `this` - it would make reading simpler but TS wouldn't know what this inside the function refers to

**Comment by dbaeumer** [comment]
What I always do in these cases is `(this: void, ...)`. Makes it clear to TS that this has no methods and is less confusing.

**Comment by jrieken** [comment]
We remove the `this: ...` part because other were confused by this as well
