### ISSUE TITLE
Dropping a terminal tab into an editor tab results in error message

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#125064]
Testing #124716

Open a trusted workspace
Drag a terminal tab into editor area - see affordance indicating that this is a valid drop target
Drop the tab into the editor area
Get an error message : Unable to open '2': Unable to resolve resource vscode-terminal:2.

I'm not a big fan of moving terminal tabs into the editor area because we have to make sure we treat these differently to files (e.g., when dropping into the editor area when working with a trusted workspace, before the error message is shown, the prompt asking the user if they trust these files is shown, which doesn't make sense since the terminal is not a file).

I would consider not showing the drop target when dragging over the editor area.

**Comment by Tyriar** [comment]
The drop target is wrong for now, but we're adding this feature next month so we can close out the 2nd highest voted request https://github.com/microsoft/vscode/issues/10546

**Comment by stevencl** [comment]
I'm all for terminal tabs, just cautious about terminal tabs being treated the same UX wise as editor tabs since the content is different.

Should I open another issue about the trust prompt when dropping a terminal in the editor area or will that be covered here too?

**Comment by Tyriar** [comment]
This issue can track making the drop feedback doesn't show which should prevent the trust prompt

**Comment by jeanp413** [comment]
This issue also happens for elements in the debug watch view, see #124946.
