### ISSUE TITLE
Test renderer messaging API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125016]
Refs: microsoft/vscode#123601

- [x] anyOS @isidorn
- [x] anyOS @andreamah

Complexity 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125016%0A%0A)

---

Renderers do not use standard webview messaging, so we created a new messaging channel for them to talk to the extension. Messaging must be requested statically and is opt-in, since renderers which have a hard dependency on messaging will not be usable in aznb.

You can test this functionality with an existing renderer-bearing extension, like github-issues-notebooks, or create your own renderer via `npm install -g generator-code && yo code --insiders`

**Comment by isidorn** [comment]
Link to API to be reviewed: https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L1471
Link to github-issues-notebooks extension (which can be installed to try this out) https://github.com/microsoft/vscode-github-issue-notebooks

**Comment by isidorn** [comment]
I reviewed this API and used it very basically. I think it would be more useful if potential clients of the API also provide their real world feedback.

**Comment by andreamah** [comment]
I also tested it pretty basically in the github-issues-notebook extension, so I agree with the comment above that it would be helpful if potential users are to try it.
