### ISSUE TITLE
VS code not responding

### ISSUE THREAD

**Issue by bugMaker-237** [Microsoft/vscode#12502]
- VSCode Version: Code 1.5.3 
- OS Version: Windows 10

Hi, have a problem with my vs code after i've done this.
Steps to Reproduce:

1. Install HTML CSS completion
2. Cache css classes on workspace.

 Vs code completely stops working. Does any one has an idea??

**Comment by mrmlnc** [comment]
This is bad extension. See https://github.com/Microsoft/vscode/issues/8889, https://github.com/Microsoft/vscode/issues/8904, https://github.com/Microsoft/vscode/issues/8924, https://github.com/Microsoft/vscode/issues/9200, https://github.com/Microsoft/vscode/issues/11563 and  https://github.com/Microsoft/vscode/issues/12416.

**Comment by chrmarti** [comment]
Tracked as Zignd/HTML-CSS-Class-Completion#12
