### ISSUE TITLE
Double-click delimiter in terminal should select whole contents

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#125006]
In Apple Terminal, double-clicking a delimiter searches for a matching delimiter, and if it find it, selects it. This is super helpful, and probably an easy/fun feature to add.

It checks the direction the delimiter is facing, starts going through each cell, and keeps count of recursive matching delimiters to skip them. This simple logic works for 99% of real-world cases.

**Comment by Tyriar** [comment]
Can you clarify what you mean by delimiter and provide an example where we don't do as well?

**Comment by sdegutis** [comment]
```
{
  foo: 'bar',
  bar: { 'qux' },
}
```

Double-click the first `{` and the entire thing is selected.

Double-click the second `{` and `{ 'qux' }` is selected.

**Comment by sdegutis** [comment]
I just took this for granted that you'd know what I mean, but it just occurred to me, I'm talking about using Apple Terminal and you're a Microsoft employee...

**Comment by sdegutis** [comment]
Also double-clicking the closing-delimiters does the same thing. It works with all directional delimiters. (Quotes don't make sense, the algorithm couldn't figure out which way to look.)

**Comment by Tyriar** [comment]
Oh I didn't know this was a feature. We could potentially support this although we'd need to be careful for it not to conflict with the double-click to select the underlying link logic.

**Comment by sdegutis** [comment]
If the expectation is for me to somehow alert people to this feature request to garner upvotes, just close the issue now. I know no one and have no influence in the software world, and this issue will remain completely unknown.

**Comment by aeo000000** [comment]
Support your idea, I have been looking for a solution to this problem。
I believe it is not difficult to solve,  but to study the code of vscode  in a short while......
It is estimated that the author who wrote vscode to change it, spend less than 5 minutes。
