### ISSUE TITLE
No intellisense for `remote.portsAttributes` setting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125081]
Testing #124976

The `remote.otherPortsAttributes` does have correct Intellisense, tho.

![image](https://user-images.githubusercontent.com/22350/120325734-cde5ac80-c29c-11eb-8527-b7be15b35dbe.png)

**Comment by alexr00** [comment]
I'm not sure that there's anything that can be done to help this. There's already a default snippet, and the properties can be a port number, a port number range, or a string for matching to a process command line.

**Comment by joaomoreno** [comment]
> There's already a default snippet

I'm actually very thrown off by the textual suggestions, which often tells me there's no good suggestion at all. Is the default snippet the `${issueNumberLabel}` one?

**Comment by alexr00** [comment]
The default snippet is 
```
		"3000": {
			"label": "Application",
			"onAutoForward": "openPreview"
		}
```
but it's at the level of the whole setting. I will see if I can add the same snippet in the properties to so that no one ends up with the bad suggestions you see.

**Comment by alexr00** [comment]
Found the right place to improve this.
