### ISSUE TITLE
[FR] Copy Command Title

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#125092]
Currently, for copying a command like `Add Cursor Above` on the "Keyboard Shortcuts" page, there're two options:

1. Copy

   Copies

   ```json
   {
     "key": "ctrl+alt+up",
     "command": "editor.action.insertCursorAbove",
     "when": "editorTextFocus"
   }
   ```

2. Copy Command ID

   Copies `editor.action.insertCursorAbove`

But really, quite often, we just want to copy `Add Cursor Above`, and there's no option for that.

Therefore, I'm making a feature request for it.

**Comment by timfenney** [comment]
@wenfangdu I hope this works for you? :smile_cat: :

**Comment by wenfangdu** [comment]
@timfenney Sorry for the late response, but I don't know how to test this though.

**Comment by sandy081** [comment]
Planning to look at this PR in July milestone.

**Comment by sandy081** [comment]
Thanks @timfenney for the PR - I did some small fine tunings after. 

![image](https://user-images.githubusercontent.com/10746682/124615030-251b0600-de75-11eb-9697-8861818f461e.png)

**Comment by sandy081** [comment]
To verify:

- Open Keyboard Shortcuts editor
- Right click on an entry and make sure you have an action to copy the command title
- Make sure this action works as expected
