### ISSUE TITLE
Snippet variables overriding previous text

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#12506]
When you create a snippet where Variables are directly connected the last variable overrides parts of the first one.

- VSCode Version: 1.5.3
- OS Version: Microsoft Windows [Version 6.1.7601]

Steps to Reproduce:

1. Use the attached snippet for C#
2. In a C# file type example and press TAB
3. For the ${eg} variable enter test
4. For the ${var} variable enter variables

As you can see the text *test* of the second appearance of ${eg} will partly be overriden by the second appearance of ${var}

![snippet](https://cloud.githubusercontent.com/assets/7260053/18781440/037b890c-8182-11e6-9361-3abb19eb171e.gif)

```` json
{
	"Example": {
		"prefix": "example",
		"body": [
			"// This is an ${eg} what happens when two ${var}",
			"// are directly connected: ${eg}${var}"
		]
	}
}
````

**Comment by jrieken** [comment]
This is a good bug report. Thanks
