### ISSUE TITLE
Trust: should the dialog talk about "windows" and not "workspaces" in empty window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125057]
Testing #124991

Here I had an empty window opened but the dialog talks about workspaces:

![image](https://user-images.githubusercontent.com/900690/120304680-4a45b300-c2d0-11eb-9558-d74a8a4d7526.png)

**Comment by sbatten** [comment]
Workspaces is the correct term here because the decision applies to any workspace. Not just empty windows.

I could see "... all windows and workspaces" to be generic. please let me know if you think that's worth it. otherwise, closing for now.
