### ISSUE TITLE
Select Folder To Trust Is Buggy For Remotehub

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125055]
Testing #125023.

![recording](https://user-images.githubusercontent.com/2931520/120303932-98a68200-c2cf-11eb-8aba-db0b815188eb.gif)

* `..` does not always work
* I cannot select `/hediet/vscode-drawio/`

**Comment by sbatten** [comment]
@alexr00 @eamodio issue with the extension or the picker?

**Comment by eamodio** [comment]
Yeah, this is an issue with the simple file dialog. I talked to @alexr00 about it a while ago, but I forgot to open an issue to track it.

Basically we need a way to "anchor" the dialog to a root.

**Comment by alexr00** [comment]
The bug is that there shouldn't be a ".." to go back in the picker. Then, once that's been chosen everything gets messed up.
