### ISSUE TITLE
Enter doesn't finish terminal tab rename

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125039]
Testing #124716

* rename terminal tab
* type its new name
* press `Enter`, nothing happens but it should finish the rename

**Comment by Tyriar** [comment]
I can repro, also there's a weird margin for me:

<img width="240" alt="Screen Shot 2021-06-01 at 7 57 33 AM" src="https://user-images.githubusercontent.com/2193314/120345101-07271800-c2af-11eb-85f1-ee30c1175d21.png">

**Comment by meganrogge** [comment]
Enter works for me on Windows.
![recording - 2021-06-01T112329 838](https://user-images.githubusercontent.com/29464607/120372252-c689c780-c2cb-11eb-8875-bd4fe816f3f5.gif)

**Comment by Tyriar** [comment]
It might be triggering the rename command again?

**Comment by meganrogge** [comment]
Yep that's what it looks like when I debug
