### ISSUE TITLE
Explorer: New File/Folder actions not disabled in readonly file system

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125026]
Steps to Reproduce:

1. run an extension that registers a readonly file system (e.g. our [memfs extension](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) with some tweaks)
2. open a workspace with a folder from that file system that is readonly (memfs does that)

=> 🐛 the explorer actions for new file/folder are not disabled and silently fail when clicked

![image](https://user-images.githubusercontent.com/900690/120273850-579e7580-c2af-11eb-85a0-60eea011dd53.png)

**Comment by isidorn** [comment]
@bpasero the memfs extension for me does not start readonly. I can delete and change files.
What are the tweaks needed to make it readonly?

**Comment by bpasero** [comment]
@isidorn when the provider is registered you can set `isReadonly: true`

**Comment by bpasero** [comment]
Actions are still enabled when I click into the empty space though:

![recording](https://user-images.githubusercontent.com/900690/120498563-991e4600-c3bf-11eb-85d5-992c5b39260c.gif)

**Comment by isidorn** [comment]
I have looked into a fix and I would prefer to do it start of next week.
The thing which I plan to change as part of this fix:

In a multi root workspace, when the user context menus on the empty space at the bottom that will be like he is acting on the last workspace. I think that makes sense, I just do not want to do it in endgame week.
