### ISSUE TITLE
Rename terminal tab is cropped

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125038]
Testing #124716

* macos
* have terminal tabs
* rename a tab
* :bug: the rename input seems to high, its upper/lower border aren't visible

<img width="328" alt="Screen Shot 2021-06-01 at 10 45 38" src="https://user-images.githubusercontent.com/1794099/120294554-9986e600-c2c6-11eb-809d-beccbb1ab77a.png">

**Comment by meganrogge** [comment]
fixed 1a8bd7b260f71577e693ad0ff238544517bcb694
