### ISSUE TITLE
Open Folder Has No Cancel Button

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125051]
![image](https://user-images.githubusercontent.com/2931520/120301653-6005a900-c2cd-11eb-95d8-e1aa994572a6.png)

There is no easy way to close this dialog with the mouse (like an `X` or a cancel button).
The dialog appears when opening a remote repository and then clicking on `File` -> `Open Folder...`.

**Comment by eamodio** [comment]
This AFAIK, the design of the vscode simple file dialog (which is what is used in that image).

**Comment by alexr00** [comment]
@chrmarti do you still own the quick pick? The simple file dialog uses the property `ignoreFocusOut`, and if we say that the simple file dialog should have a cancel button, then every quick pick that uses `ignoreFocusOut` should also probably have a cancel button.

**Comment by eamodio** [comment]
I believe @TylerLeonhardt owns the quickpick now

**Comment by TylerLeonhardt** [comment]
>  if we say that the simple file dialog should have a cancel button, then every quick pick that uses ignoreFocusOut should also probably have a cancel button.

I agree with this statement. However, I don't like the idea of a cancel button cluttering quick picks that don't have a title bar when hitting `Esc` is available.

**Comment by TylerLeonhardt** [comment]
That said... it looks like we may need to do something for this because of https://github.com/microsoft/vscode/issues/125284#event-4831907037

**Comment by TylerLeonhardt** [comment]
Let's dupe this to #125284
