### ISSUE TITLE
renderer messaging wording feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125085]
Testing #125016

Just some personal preference:
1) I find the word `messaging` a bit weird, especially since we have never ever used it in `vscode.d.ts` so far.
2) We have `postMessage` and `onDidReceiveMessage`. For me `send` and `receive` are better pairs. Thus I suggest `sendMessage` and `onDidReceiveMessage`

**Comment by connor4312** [comment]
The reasoning behind the current wording is to match the underlying DOM APIs. Although renderer messaging is all encapsulated in our own wrappers, and the verbiage matches the `Webview` API (which also uses the postMessage/onDidReceiveMessage pair) and avoids introducing a new word/verb for this flow.

**Comment by isidorn** [comment]
I was not aware this is matching DOM APIs. In this case if you are happy with the current wording feel free to close this issue. Thank you
