### ISSUE TITLE
Mention "notebookRenderer" contribution to be more precise

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125082]
Testing #125016

Code pointer https://github.com/microsoft/vscode-github-issue-notebooks/blob/main/src/extension/vscode.proposed.d.ts#L1544

In the comment we say:
`"requiresMessaging is set in its contribution"`
Instead I suggest to use the following:
`"requiresMessaging is set in its notebookRenderer contribution"`

**Comment by isidorn** [comment]
Also be more precise and say if `optional` works in this case.

**Comment by connor4312** [comment]
Fixed but forgot to tag in commit
