### ISSUE TITLE
Notebook renders might not work in remote setup

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#125073]
Testing #124993

I was using the example in WSL. When trying to render a regexp cell I get

<img width="668" alt="capture" src="https://user-images.githubusercontent.com/1931590/120323214-918a6e80-c2e5-11eb-854c-298c266058dd.png">

**Comment by dbaeumer** [comment]
Seems to be independent of WSL. Pure Linux

<img width="745" alt="capture" src="https://user-images.githubusercontent.com/1931590/120323478-ceeefc00-c2e5-11eb-9aac-79533d787136.png">

**Comment by jrieken** [comment]
@dbaeumer the prelaunch task of that repo isn't the best. Make sure run `npm run compile` once. That should webpack the renderer

**Comment by dbaeumer** [comment]
Works. Closing issue.
