### ISSUE TITLE
Trust: opening a file from the "File > Open" dialog that is already opened should not prompt?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125058]
Testing #124991

![recording](https://user-images.githubusercontent.com/900690/120305127-b58f8500-c2d0-11eb-9db1-940586afc00b.gif)

**Comment by lszomoru** [comment]
@bpasero, should this condition be detected by the editor service and not even send the workspace trust service the resource?

**Comment by bpasero** [comment]
This is tough actually because the editor service can only figure out if the tab is opened but not whether the tab has been loaded or not. So we may wrongly not show the dialog and open the editor even though it was not loaded before.

**Comment by lszomoru** [comment]
I see. Should we then go ahead and close this issue?

**Comment by bpasero** [comment]
Yeah fine by me, let's wait for complaints.
