### ISSUE TITLE
Revisit name of editor.suggest.showSuggestionPreview

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125034]
Testing #125001

The `editor.suggest.showSuggestionPreview` name repeats "suggest" and I would suggest to drop one, e.g. just have  `editor.suggest.showPreview`

**Comment by hediet** [comment]
Should the inline completion settings live in the suggest namespace? (e.g. the setting that controls if inline completions are enabled)

**Comment by alexdima** [comment]
The outcome of the discussion:
* rename `editor.suggest.showSuggestionPreview` to `editor.suggest.preview`
* rename `editor.suggest.showInlineCompletions` to `editor.inlineSuggest.enabled`
* rename command ids, context keys and command titles to inline suggest
* for the menu contribution point, check for proposed API via the schema
