### ISSUE TITLE
Jump to matching bracket shorcut not working

### ISSUE THREAD

**Issue by santiagohdzb** [Microsoft/vscode#1250]
When editor's cursor is over a bracket and I press Ctrl+Shift+J, I expect the cursor to jump over the matching bracket but it does not happen. Actually nothing happens.

In my Default Keyboard Shorcuts I have this:
```
{ "key": "ctrl+shift+]", "command": "editor.action.jumpToBracket", "when": "editorTextFocus" },
```

I haven't override that value in keybindings.json.
I'm using VS Code 0.10.3 on Windows 8.1 x64

**Comment by alexandrudima** [comment]
@santiagohdzb It is `]` not `j`:

![image](https://cloud.githubusercontent.com/assets/5047891/11780243/c8680008-a260-11e5-94a4-f770a7eb9137.png)

**Comment by santiagohdzb** [comment]
@alexandrudima wow, I guess I need glasses, thank you!

**Comment by alexandrudima** [comment]
:heart:

**Comment by santiagohdzb** [comment]
actually, `ctrl+shift+]` didn't worked either :(.

But, hey! I found the reason why: VS Code is not detecting my ES keyboard distribution, because if I press this combination:

![captura](https://cloud.githubusercontent.com/assets/8533075/11789512/1d4e16c8-a254-11e5-9293-f156b409a221.PNG)

VS Code triggers the `ctrl+shift+]` shorcut command

**Comment by alexandrudima** [comment]
We have done work in December to improve the keyboard layout support. And I plan to do more this week. See #713

**Comment by santiagohdzb** [comment]
Awesome! thanks a lot @alexandrudima
