### ISSUE TITLE
Notebook renderer documentation should say that there is a required compiler option

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125095]
Testing #124995

Looks like the typescript compiler options `"skipLibCheck": true,` must be set in your `tsconfig.json` to successfully build when you include `@types/vscode-notebook-renderer` in your `devDependencies`. 

I looked at https://github.com/microsoft/vscode-docs/blob/notebook/api/extension-guides/notebook.md#output-renderer, but I didn't see anything that indicates that the compiler option is needed.

**Comment by alexr00** [comment]
Actually, looks like I was missing `"dom"`:
```
	"compilerOptions": {
		"lib": [
			"ES2019",
			"dom"
		],
```

**Comment by jrieken** [comment]
Yeah, that makes more sense. Renderer do run in a dom context and the API spec for them uses dom-types, like HTMLElement and Blob

**Comment by mjbvz** [comment]
Was this for the renderer template generated with `yo code`?

**Comment by alexr00** [comment]
No, I started with the hello-world sample from Microsoft/vscode-extension-samples.

**Comment by mjbvz** [comment]
I'm going to close this as by-design. The `yo` notebook renderer template seems to have the correct project setup. The notebook doc page also doesn't cover project setup too much. If we find a lot of people confused about this, we can add a note to the docs in the future
