### ISSUE TITLE
Terminal tabs don't use native tool tip

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125042]
Testing #124716

* hover over a terminal tab
* the custom tool top shows, not the native tool tip

I don't wanna take sides and say what tool tip is better but I see inconsistency, e.g my assumption is that we use the custom tooltip for rich content and the native tool tip else. 

<img width="274" alt="Screen Shot 2021-06-01 at 10 54 25" src="https://user-images.githubusercontent.com/1794099/120295782-c4256e80-c2c7-11eb-9612-3f1e9de3c07d.png">

**Comment by jrieken** [comment]
//cc @misolori for advice when to use what

**Comment by Tyriar** [comment]
They show rich content:

<img width="347" alt="Screen Shot 2021-06-01 at 7 56 01 AM" src="https://user-images.githubusercontent.com/2193314/120344941-e65ec280-c2ae-11eb-8a51-0d42075dccaf.png">


<img width="874" alt="Screen Shot 2021-06-01 at 7 56 28 AM" src="https://user-images.githubusercontent.com/2193314/120344907-dfd04b00-c2ae-11eb-8368-e3fa06c4ff9c.png">

**Comment by misolori** [comment]
We should probably have some guidance on when to use what, I do think in the cases where we are repeating the same content that is visible that it is not very helpful.

**Comment by Tyriar** [comment]
@misolori I agree but I don't think you can detect whether the text is truncated without measuring the text with JS and we definitely want to show it then.
