### ISSUE TITLE
Option to hide (and order) tasks in the Run Task menu with tasks.json

### ISSUE THREAD

**Issue by Alejandro-FA** [microsoft/vscode#125065]
This feature was already requested some time ago (#116892). I would like to request it again, since I think it could be very useful to keep the **task menu tidy** for users that have lots of tasks (but some of them are just **dependencies of other tasks**). Furthermore, it would be interesting to add the possibility of **sorting the tasks** too, although I don't think that it is as important.

As an implementation suggestion, I think it would be great to do something similar to what it is already implemented in `launch.json` files with the `"presentation"` option, for example:

```json
"presentation": {
    "hidden": false,
    "group": "C++",
    "order": 1,
}
```

The `tasks.json` `"presentation"` option affects the output behavior of the terminal panel instead, so I guess that it would be easier to call the requested feature differently (such as `"menu"`, `"menuPresentation"`, `"menuOptions"` or something similar) to avoid conflicts with previous versions.

EDIT: @herrberk, @nextgentm1, @matiasg77,  @CarlPer, @mickare, @IllusionMH, @idanpa, @derekmckinnon, @omer-musa-battal, @Kirdock, @tmsampson, @HelloCore I don't know if you're still interested or you have any other suggestion.

**Comment by Azrideus** [comment]
Also something like task item color would be nice,
for example it would be nice to have all your build based tasks colored green or cleanup tasks colored blue
