### ISSUE TITLE
Bash shell overwrites itself when window set to half screen

### ISSUE THREAD

**Issue by ChrisGibson1982** [Microsoft/vscode#12500]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14931

Steps to Reproduce:
1. Open code
2. Set bash as your terminal, then laun terminal window
3. pin code to half of your screen (drag to right of window)
4. Start typing a line of code i.e. bash -n debug_03.sh one two
5. The last part of the line of text will overwrite the start of the line of text..  i.e. root@g.. become one two@...

This is only intermittent :(

**Comment by bencooper222** [comment]
![image](https://cloud.githubusercontent.com/assets/9143563/23451916/a3b39730-fe27-11e6-903a-0bc3050315e4.png)

Just an image to further document this: I was trying to write "cd website"

**Comment by Tyriar** [comment]
I believe the OP's issue has been resolved.
