### ISSUE TITLE
Trust: experience differs from test plan item

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125070]
Testing #124991

Assignment:

![image](https://user-images.githubusercontent.com/900690/120314525-9ea26000-c2db-11eb-91b7-d7464283739d.png)

Result:

![image](https://user-images.githubusercontent.com/900690/120314494-9518f800-c2db-11eb-9e59-6d3b7d2622ec.png)

I think the experience is fine, but wanted to post here that I see no dialog.

**Comment by lszomoru** [comment]
Thanks! Yeah, we kept on tweaking the logic for showing the modal dialog. I have updated the test plan item.
