### ISSUE TITLE
Renderer messaging: do not use generics

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125086]
Testing #125016

Currently in the renderer messaging api we use `<TSend = any, TReceive = TSend>`. I suggest to instead simply use `any` since we already use that in other messaging api we have: debug protocol and for the `WebView`.

**Comment by mjbvz** [comment]
I think the generics make sense in this case. Having them lets you optionally enforce typings on the messaging object

Webviews use `any` because `postMessage` belongs to the entire `WebView` object instead of a dedicated messaging class like we have here
