### ISSUE TITLE
Test new notebook renderer API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125015]
Refs: https://github.com/microsoft/vscode/issues/123540

- [ ] anyOS @aeschli
- [ ] anyOS @andreamah

Complexity: 4

Authors: @connor4312, @mjbvz 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125015%0A%0A)

---

The issue provides a good description of the problems and features. You can test this with an existing extension, like [github-issues-notebooks](https://github.com/microsoft/vscode-github-issue-notebooks), or create your own renderer via `npm install -g generator-code && yo code --insiders`

Verify that the API and described typings work as expected. Note that messaging is separate (https://github.com/microsoft/vscode/issues/123601)

**Comment by mjbvz** [comment]
I believe that Joh created a test for this: #124995

Closing as a duplicate

**Comment by mjbvz** [comment]
Ah the bot snuck in while I was  leaving the comment. Instead of running assignments again, please be available to help out on other test items
