### ISSUE TITLE
State does not seem to be preserved when moving file from explorer view to different window

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125063]
Testing #124848

> you can drag and drop files from the VSCode explorer to another window to open all editors there and **view state is preserved** if any editor was opened in the source window

State does not seem to be preserved:

![recording](https://user-images.githubusercontent.com/2931520/120307675-8d555580-c2d3-11eb-88a2-ee918f4e6dfa.gif)

I like this behavior though.

**Comment by bpasero** [comment]
> I like this behavior though.

Yeah I think so too. The explorer is a drop target that will strictly take the file on disk to upload it into the workspace and it will not care about view state. Only when you drop into the editor area we restore view state and contents, so closing as designed.
