### ISSUE TITLE
how to set different font for  Latin and CJK

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#125019]
hi, I‘m CJK language user, and I used to develop with English and simple Chinese.
I'm using `Cascadia Code` as the Frist font, and how can I set the CJKMono font as `宋体`。
![image](https://user-images.githubusercontent.com/1876302/120255665-18782080-c2bf-11eb-8e9c-954b9ad8c9da.png)

thanks very much

**Comment by dbaeumer** [comment]
The setting to control the editor font is `editor.fontFamily`

**Comment by heartacker** [comment]
@dbaeumer no, I mean that I need to  control the font of english and chinese with two fonts, eg. english use `Cascadia Code`, and chinese use `songti`.

now the editor.fontFamily just accept one font, when the frist front is `Cascadia Code`, the chinese words are not mono.
`Cascadia Code, 宋体,  Fira Code Retina, YaHei Consolas Hybrid, Consolas, Courier New, monospace`
please.

**Comment by dbaeumer** [comment]
I think that this is not possible.
