### ISSUE TITLE
Bug in compiling

### ISSUE THREAD

**Issue by harshitmathur2000** [microsoft/vscode#125072]
Issue Type: <b>Bug</b>

#include <iostream>
#include <cmath>
using namespace std;
int main(){
    int n;
    cin>>n;
    int sum=0;
    int originaln=n;
    while(originaln!=0){
        int lastdigit= originaln%10 ;
        sum=sum+pow(lastdigit,3);
        cout<<pow(lastdigit,3)<<endl;
        originaln=originaln/10;
    }
    cout<<sum<<" "<<n;
    if(sum==n){
        cout<<"Armstrong Number"<<endl;
    }
    else{
        cout<<"Not an Armstrong Number"<<endl;
    }
    return 0;
} 
I am running this code its giving wrong output for 153. It's not adding 1 to the sum and not giving 153 as armstrong number. But it's giving correct output for 371. I don't know why it is particularly giving wrong output for 153.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.01GB free)|
|Process Argv|--crash-reporter-id ea9246f7-91ea-48fa-8464-c421c16269aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
pip-packages|etm|0.4.3
code-runner|for|0.11.4
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.0
java|red|0.79.2
catalyst|Rud|1.5.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by IllusionMH** [comment]
/question

This is issue tracker for VS Code editor itself and it doesn't provide C/C++ functionality out of the box.

You can debug this program using steps from https://code.visualstudio.com/docs/cpp/cpp-debug
If it's issue reproducible only when running from VS Code - you should report it in extension repo
