### ISSUE TITLE
Notebook editor does not turn readonly properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125027]
Steps to Reproduce:

1. use a file system that registers readonly (e.g. [memfs sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) with some tweaks to register as readonly)
2. open a notebook

=> 🐛  you can still type in the cells

![recording](https://user-images.githubusercontent.com/900690/120274256-ddbabc00-c2af-11eb-81e8-4a875f711e09.gif)

**Comment by connor4312** [comment]
Unable to verify due to https://github.com/microsoft/vscode/issues/125550
