### ISSUE TITLE
Takes to much space in C:\ Drive

### ISSUE THREAD

**Issue by Param-01** [microsoft/vscode#125043]
Issue Type: <b>Performance Issue</b>

It keeps increasing space in c drive.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.39GB free)|
|Process Argv|--crash-reporter-id e25118b3-7097-49fa-8379-5fd72cb97355|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    80	 10180	code main
    0	   165	  2984	   window (Main.js - Demo - Visual Studio Code)
    0	    82	   416	     extensionHost
    0	   103	  5468	       electron_node tsserver.js 
    0	   175	 13136	       electron_node tsserver.js 
    0	    85	 11564	         electron_node typingsInstaller.js typesMap.js 
    0	    15	  5692	     watcherService 
    0	    12	 17040	       console-window-host (Windows internal process)
    2	    78	  4624	   shared-process
    0	    43	 15840	     ptyHost
    0	    39	  8964	   utility
    1	    76	  9628	   window (Issue Reporter)
    0	    24	 11064	   crashpad-handler
    2	   154	 15384	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Main.js - Demo - Visual Studio Code)
|    Folder (Demo): 1206 files
|      File types: so(256) json(126) xml(124) flat(122) dex(16) bin(10)
|                  png(10) js(9) class(9) properties(8)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
react-native-react-redux|EQu|2.0.6
prettier-plus|svi|4.2.2
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

aste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What files takes space in C drive?
