### ISSUE TITLE
Incorrect behavior of AltGr+é/è in Terminal on AZERTY layout

### ISSUE THREAD

**Issue by Alex131089** [microsoft/vscode#125068]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Win 10 19042

Steps to Reproduce:

1. Enable NumLock (not able to reproduce without)
2. In the Terminal, type `AltGr` + `é` followed by `space` to obtain `~`
3. Get `é~` instead

I found that this is a dup of (all closed) #88156, #73876, #68262, #59438 (_2018_) and related to uptream https://github.com/xtermjs/xterm.js/issues/2151 / https://github.com/xtermjs/xterm.js/issues/2479, but as this bug is still affecting VSCode (no workaround included in VSCode to make it usable), shouldn't an issue be kept opened here? Maybe a known issues entry?

Please note that using an enhanced layout like https://s.twb.fr/mirror-kbdfrac/kbdfrac.htm (kbdfrac2.exe), with `´` on the `&` key, produces the same behavior (`&´`).

As workaround, we can:
* Disable NumLock
* Define a custom mapping as described in https://github.com/xtermjs/xterm.js/issues/2151#issuecomment-805632690 / https://superuser.com/questions/414405/pressing-the-tilde-key-waits-for-a-second-key-stroke-how-do-i-disable-this (but I guess this prevent writing `ñ` or `È`)

Hope you'll have time to fix this :) (and sorry if I only wasted your time)

**Comment by Tyriar** [comment]
We maintain the xterm.js repo so we track it over there to try keep the total issue count I need to manage down.
