### ISSUE TITLE
Support explicitly setting the canvas renderer

### ISSUE THREAD

**Issue by ejose19** [microsoft/vscode#125007]
Issue Type: <b>Performance Issue</b>

After latest update, integrated terminal performance is greatly degraded, previously I was using `"terminal.integrated.rendererType": "canvas"` in order to archieve good performance, but now that option is removed and replaced with `"terminal.integrated.gpuAcceleration"`, yet neither `auto` | `on` | `off` seems to give previous performance as when using `"terminal.integrated.rendererType": "canvas"` (`"terminal.integrated.gpuAcceleration": "off"` was the fastest option, but still slow)

VS Code version: Code - OSS 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-16T15:21:33.370Z)
OS version: Arch Linux

<details>
    <summary>System Info</summary>

```
CPUs	AMD Ryzen 9 3900X 12-Core Processor (2 x 3792)
GPU Status	2d_canvas: unavailable_software gpu_compositing: disabled_software multiple_raster_threads: disabled_off oop_rasterization: disabled_off opengl: disabled_off rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: unavailable_software webgl2: unavailable_software
Load (avg)	1, 0, 0
Memory (System)	3.18GB (1.79GB free)
Process Argv	disown --no-sandbox
Screen Reader	no
VM	100%
```
</details>

<details>
    <summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   157	  8566	code-oss main
    0	    82	  8577	   zygote
    0	    91	  8734	     gpu-process
    0	    82	  8578	   zygote
    2	    95	 16253	     window (Issue Reporter)
    0	   101	  8721	   utility
    0	   274	  8776	   window (settings.json - Code - OSS)
    0	   143	  9037	     extensionHost
    0	   111	 15408	       /usr/lib/electron/electron /usr/lib/code/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9037
    0	   147	  9070	   shared-process
    0	    95	  9213	     ptyHost
    0	     3	 11566	       /bin/bash
    0	     0	 16269	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```
</details>

Extensions: none

**Comment by Tyriar** [comment]
Let's add `canvas` as an option to `gpuAcceleration` that prevents fallback from happening.

**Comment by ejose19** [comment]
Sure, let me know once that option is available to test and I'll check it out.

**Comment by ejose19** [comment]
I tested from dev build and now it's working great, thanks @meganrogge!
