### ISSUE TITLE
Empty window trust: reloading a trusted window removes trust

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125049]
Testing #124984

An empty window that is trusted looses that trust after a window reload. In my case I noticed an extension update and clicked the "Reload required" button. Then I saw the trust of the empty window gone again.

**Comment by bpasero** [comment]
Oh, the test plan item seems to suggest that this is expected behaviour but I find that weird, especially when I reload the window because I updated an extension.

**Comment by lszomoru** [comment]
Reloading the empty window should maintain the trust state. This was a bug and it has been fixed.
