### ISSUE TITLE
Test notebook profile

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125014]
Refs: #122481

- [x] macOS @egamma
- [x] linux @connor4312
- [x] windows @eamodio

Complexity: 2
Authors: @rebornix @misolori @roblourens 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125014%0A%0A)

---

- Open VS Code with a fresh user data dir
- Set `"notebook.experimental.openGettingStarted": true`
- Before you open a notebook in this user data dir, open Getting Started > Get Started with VS Code > check that no notebook-related task appears in the list
- Open any notebook
- The Getting Started page should be opened to a new notebook customization task that lets you pick a notebook profile
- Pick one
- See that some corresponding notebook settings are applied to your user settings
- After opening a notebook, the notebook profile task will always appear in Getting Started if you go back to it
- The Getting Started page only auto-opens the _first_ time you open a notebook (per user-data-dir)

Some UI cleanup will happen here. The preview screenshots of the profiles and the exact contents of them will change, so you don't need to comment on that. Just test the flow of auto-opening the getting started page, and clicking the different profiles.

**Comment by roblourens** [comment]
Seems that the images didn't make it into the real product build. Please wait for the next one

**Comment by egamma** [comment]
@roblourens Changed the order of the steps in the description to

- Open VS Code with a fresh user data dir
- Set `"notebook.experimental.openGettingStarted": true`

Images are missing in Version: 1.57.0-insider
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:12:30.409Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0
