### ISSUE TITLE
Trust editor: alternating background color for table widget?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125099]
Most of our tables chose to use alternating background colors, e.g. keybindings:

![image](https://user-images.githubusercontent.com/900690/120334862-4bd3a300-c2f1-11eb-86af-23ac71b2b076.png)

This somehow makes it easier for me to understand that I am looking at tabular data, wondering if we should do the same for trusted paths:

![image](https://user-images.githubusercontent.com/900690/120334938-5d1caf80-c2f1-11eb-99b2-82e7ad85c3e6.png)

**Comment by bpasero** [comment]
@alexr00 would this make sense for the ports view as well? Just realised ports also do not apply such a background color pattern:

![image](https://user-images.githubusercontent.com/900690/120335298-a79e2c00-c2f1-11eb-8083-4e729e7732af.png)

Arguably this raises the question if such a pattern should be used for tables only, or lists in general which would probably look too noisy.

**Comment by bpasero** [comment]
//cc @misolori

**Comment by alexr00** [comment]
@joaomoreno if we adopt this, maybe it should be for all table views.

**Comment by misolori** [comment]
I like the update of using alternate bg colors 👍

**Comment by joaomoreno** [comment]
@alexr00 I thought we did this for the ports view as well?

**Comment by alexr00** [comment]
@joaomoreno I think I remember us looking at it and deciding not to have it. But I'm happy to go with the majority.

**Comment by misolori** [comment]
@joaomoreno 🙏 thanks for pulling in the colors from https://github.com/microsoft/vscode/pull/135018
