### ISSUE TITLE
Upgrading to 1.5.3 throw JS error message

### ISSUE THREAD

**Issue by fredrikredin** [Microsoft/vscode#12501]
Upgrading to 1.5.3 throw JS error message (OS: Windows 10 Pro)
See attached image. Restarting VSCode does not repeat the error message. 

![visual_studio_code_error_1 5 3](https://cloud.githubusercontent.com/assets/2992687/18778341/2884b164-8174-11e6-8ebf-1ef4e8c09508.png)

**Comment by mrmlnc** [comment]
I see two ways:

  * Reinstall VS Code from binary
  * Manually update VS Code
    * Download `.zip` for Windows from https://code.visualstudio.com/Download.
    * unzip `resources` directory to `c:\Program Files (x86)\Microsoft VS Code\`.
 
Also related to https://github.com/Microsoft/vscode/issues/11717

**Comment by joaomoreno** [comment]
Please don't do the suggested _Manually update VS Code_, but simply reinstall it: https://code.visualstudio.com/Download
