### ISSUE TITLE
Revisit name of editor.suggest.ghostTextExpanded

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125037]
Testing #125001

related to https://github.com/microsoft/vscode/issues/125034

The `ghostTextExpanded` name is quite special... How about folding it into the `showSuggestionPreview`-setting and have a value of off, one for on+single, and one for on+multiple, like: `editor.suggest.showPreview: 'singleLine' | 'multiLine', 'off'`

**Comment by hediet** [comment]
The `ghostTextExpanded` setting also applies to inline completions though. Would you have separate settings for inline completions / suggestion previews?

**Comment by jrieken** [comment]
Yeah, maybe two settings. I am kinda surprised that this setting applies to both features (suggest and ghost text)... Alternatively, move the this setting out of the `.suggest.` namespace and move it into its own

**Comment by hediet** [comment]
@isidorn's feedback was to get rid of this setting altogether and just using local storage and some kind of a toggle command.

However, I think it maybe should remain a synchronizable explicit setting - I like the multiline expansion, but I can see why you would not like them.

**Comment by isidorn** [comment]
@hediet my intuition tells me that we can get the right thing without the setting.
We should start with not expanded. If the user expands we remember the choice and show things expanded, once she collapses we show things collapsed and so on. We just preserve the last state in local storage.

Bottom line this feels just like a UI state. And should not be a setting.
Same as panel hidden / shown for example

**Comment by alexdima** [comment]
For now, we don't include the setting in the JSON schema.

**Comment by hediet** [comment]
I think this setting and the UX around expansion / collapsing should be discussed as part of the Inline Completion UX story in #125289.

**Comment by alexdima** [comment]
**To the verifier**: please check that the setting `editor.suggest.ghostTextExpanded` has been removed.
