### ISSUE TITLE
Empty window trust: appearance of banner is a bit inconsistent?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125032]
Testing #124984

We do not seem to show the banner initially for empty windows but it will appear once you open a file and then seems to "stick". Is this intentional to reduce the visual overhead in empty windows or an oversight?

![recording](https://user-images.githubusercontent.com/900690/120282557-853cec00-c2ba-11eb-80c5-4154ad072008.gif)

**Comment by sbatten** [comment]
This is intentional to reduce the weight of empty windows and especially the first run experience.
