### ISSUE TITLE
Test Edge Tools debugger integration

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125017]
* [ ] macOS @sandy081
* [x] windows @stevencl

Complexity: 3

Authors: @connor4312, @codepo8

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125017%0A%0A)

---

This iteration, we worked with the Edge Tools team to have integration of their extension into VS Code. To test this:

0. Use [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) (stable coming in a day or two)
1. Create a `pwa-msedge`-type launch config (you can rename any Chrome config to the pwa-msedge type and it'll work)
2. F5. You should see an "Inspect" icon in the debug toolbar after the browser launches
3. Click on it.
    - If you don't have the extension installed, the Extensions view will open and search for the extension to tell you to install it
    - If you have the extension installed, you should see the edge devtools open to the right 
4. Verify the devtools, opening, closing, and general lifecycle management and functionality work as you'd expect

**Comment by stevencl** [comment]
I'm not an expert on using edge devtools so I can't say that I tested everything extensively.

**Comment by sandy081** [comment]
I could open devtools and only elements and network tabs are available and they seem to work as expected. I am assuming other tabs are not available is expected.
