### ISSUE TITLE
Random freeze when reopening the editor with previous .ts file open

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#12503]
- VSCode Version: 1.5.3 and 1.6.0
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Open the editor
2. Open a .ts file with 251 errors
3. Close the editor
4. Reopen it

It will randomly freeze and ask to keep waiting, close, etc. All extensions are disabled. 

I can't open the editor anymore, it will freeze as soon as I open it, how can I reset it? I'm locked out of both insiders and stable editors (they both have the same file open)

**Comment by chrmarti** [comment]
Try starting with `code -n`. Can you paste the file? Does it happen only with one file? Or always when there are many errors?

**Comment by pocesar** [comment]
I've sent the file to @waderyan, i think it's related to #12375, it's the same file

**Comment by chrmarti** [comment]
@waderyan Could you forward the file to me?

**Comment by pocesar** [comment]
@chrmarti sure, where should I send it? (it's in a private repo)

**Comment by chrmarti** [comment]
@pocesar I cannot reproduce it, but then I also don't have all the source. To further track this down, could you run a profile:

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

Thanks.

**Comment by pocesar** [comment]
I tried that, it froze the editor =.= (was trying in stable)

**Comment by pocesar** [comment]
after a few tries, managed to save it [CPU-20160927T150208.zip](https://github.com/Microsoft/vscode/files/496340/CPU-20160927T150208.zip)

**Comment by dbaeumer** [comment]
@pocesar it would also be helpful to start code with --verbose from a terminal  and pipe the output to a file. The file contains information about what happened in VS Code.

**Comment by pocesar** [comment]
First one didn't freeze: 
[out.txt](https://github.com/Microsoft/vscode/files/496405/out.txt)

Second one did freeze: 
[out2.txt](https://github.com/Microsoft/vscode/files/496406/out2.txt)


got this error on the console as well "Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError"

**Comment by dbaeumer** [comment]
Adding @bpasero: does that ring a bell. The freeze happens in the render. I also looked at the CPU trace and that only show most of the activity in program.

Also this happens in TS I am pretty sure this is not caused by the tsserver. The server run in a separate process and communicates with the extension host.

**Comment by pocesar** [comment]
if it helps at all, I'm running on a 8GB RAM (667Mhz DDr2) old CPU (Q9550) system with a GTX 970 GPU

**Comment by dbaeumer** [comment]
I was not able to reproduce this with the file sent to @waderyan by mail. @pocesar one question: do you have a laptop with touch screen ?

**Comment by pocesar** [comment]
nope, my workstation is a desktop, and I don't have any touch devices

**Comment by dbaeumer** [comment]
@pocesar overlapped with your last comment. Doesn't sound like a laptop :-)

**Comment by dbaeumer** [comment]
Just to be sure. You see high CPU load when the editor freezes. And it only happens in the file you sent to @waderyan.

**Comment by pocesar** [comment]
yes, most of the times the freeze happened when I was either trying to open that file, or was reopening the editor that had this file already opened

**Comment by dbaeumer** [comment]
@pocesar could you share the whole project?

**Comment by pocesar** [comment]
@dbaeumer I'm afraid I can't, it's in a private repo and I'm responsible for it's maintenance hehe

**Comment by chrmarti** [comment]
@pocesar Could you attach a screenshot of when it freezes? Maybe that gives us a clue.

**Comment by pocesar** [comment]
![clipboard03](https://cloud.githubusercontent.com/assets/461084/18897237/c5061144-84fe-11e6-9673-6af1d1771966.png)

**Comment by bpasero** [comment]
The error `Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError` is coming ever since we updated to Electron 1.3.x. Since this is reported against 1.5.3 I would think it is unrelated.

@pocesar if you take the contents of that folder and copy it to another location, does it still reproduce?

**Comment by pocesar** [comment]
@bpasero that error happened in stable, not insiders. I wasn't able to get CPU profile in insiders. 

and you mean, rename the folder to something else?

**Comment by bpasero** [comment]
@pocesar yes

**Comment by pocesar** [comment]
@bpasero didn't change anything, still freezing (on stable as well)

**Comment by pocesar** [comment]
Haven't had this problem again (been using insiders all along)
