### ISSUE TITLE
Test js-debug `names` support

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125018]
Refs: https://github.com/microsoft/vscode/issues/12066

- [x] anyOS @weinand
- [x] anyOS @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125018%0A%0A)

---

Identifiers in JavaScript can be renamed during compilation. We now support dealing with these renames, provided the tool emits them correctly:

0. Use [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) (stable coming in a day or two)
1. Compile or minify some code that can rename and remap names (you can check this since there should be a non-empty "names" array in the sourcemap). Terser is one tool that works, [here's an example](https://github.com/microsoft/vscode-js-debug/blob/main/demos/node/package.json#L4) of a command for it.
2. Debug it. You should be able to use renamed variables by the original name in:
   - The variables view (it should show variables' original name), including the "copy" context menu action
   - The Watch view
   - The Debug Console/repl

There are some caveats:
- If you test with a minifier, these will often reuse renames between scope. We don't deal with this.
- This is not supported in breakpoint conditions or logpoints (since we don't statically know what scope they will be hit in until it happens)

**Comment by weinand** [comment]
@connor4312 "name" mapping is very cool!
 
And it works for hovers and inline values too:

<img width="1774" alt="2021-06-01_16-22-38" src="https://user-images.githubusercontent.com/1898161/120342100-c1427200-c2f7-11eb-9093-cdd069425395.png">
