### ISSUE TITLE
JavaScript: Typing "process.ex" should suggest "exit", not "execArgv"

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#125009]
I've never meant `execArgv` ever. Not once. 100% of the time, I was trying to type "exit".

**Comment by mjbvz** [comment]
Closing as this is not really actionable feedback

**Comment by sdegutis** [comment]
You can't change the algorithm to prioritize "exit" over "execArgv" in the completion suggestions list for "process.ex"?

**Comment by mjbvz** [comment]
Some people will want `execArgv` instead of `exit`. Trying to guess what the user wants falls under https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

**Comment by sdegutis** [comment]
99% of the time people type "process.ex", they intend "it". Even "e" will be "xit". I've been annoyed by this so many times in the past few years that I finally created this issue to fix it. To me this doesn't seem like an AI question but a simple matter of prioritizing certain fields as *far* more likely than others, to be intended. But anyway whatever, your project, deal with it as you see fit.
