### ISSUE TITLE
to debug a simple HTML + JavaScript, through the v Code - the Debugger for Chrome, standard configuration file

### ISSUE THREAD

**Issue by Cyclone77** [Microsoft/vscode#12505]
### Goal: to debug a simple HTML + JavaScript, through the v Code - the Debugger for Chrome, standard configuration file.

> 1. Through the Attach to Chrome, with sourcemaps added
>    This way must be IIS configuration on the website, start the server, in order to debug;And Debugger for Chrome plug-ins is inside said, the trouble is that a small have to configure the demo site.
> 2. Through the Launch of Chrome against localhost, with sourcemaps such as but not start the IIS,
>    "Url" : "http://localhost:8080 how access? Therefore, how to debug?
>    If start the iis more can't debugging, deserves to be good, because the website http://localhost:8080 is equal to the normal visit website, can't debugging

**Comment by chrmarti** [comment]
@Cyclone77 Sorry, I don't understand. What's your first language?

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
