### ISSUE TITLE
Terminal tab item doesn't seem to do anything 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125045]
Testing #124716

* have a single terminal 
* the terminal is rendered in the panel's toolbar
* :bug: the terminal is render as command (hover feedback, cursor style) but doesn't seem to do anything

<img width="385" alt="Screen Shot 2021-06-01 at 11 00 30" src="https://user-images.githubusercontent.com/1794099/120296619-97be2200-c2c8-11eb-8815-5622f7180369.png">

**Comment by stevencl** [comment]
I saw the same. I expected clicking that button to add another terminal, since alt-clicking it adds a new terminal and splits the two terminals. Maybe it shouldn't be clickable? Does it need to be shown when there is only one terminal? Is it possible to support alt+click on the + button to add a new split terminal?

**Comment by Tyriar** [comment]
Left click used to open the dropdown menu, now it focuses the terminal to align more with how the normal tabs behave. Supporting the dropdown menu on left click was also overly complicated. Alt+click and middle+click also match the behavior of the regular tabs.

**Comment by jrieken** [comment]
> now it focuses the terminal to align more with how the normal tabs behave. 

But it's not a tab, it's a button...

**Comment by Tyriar** [comment]
@misolori any thoughts?

**Comment by misolori** [comment]
I do agree that having the hover feedback is odd when left click does nothing. So I think we have to make it clickable and either show a menu or create another terminal. Alternatively we could show the single tab in the list but we already went that route. Disabling it would not help as there are multiple actions you can do on a single terminal.

**Comment by Tyriar** [comment]
@misolori left click does focus the terminal, it's just not very noticeable (or useful?), this aligns with single or double left click in the full tab view (depending on focusMode). I can bring the menu back on left click though.

**Comment by jrieken** [comment]
> ...alternatively we could show the single tab in the list but we already went that route. 

😢 I still miss that...

**Comment by misolori** [comment]
@Tyriar yea that is too subtle and not very useful since you only have a single terminal so the view doesn't change.

**Comment by Tyriar** [comment]
@jrieken if you want that:

```
"terminal.integrated.tabs.hideCondition": "never",
"terminal.integrated.tabs.showActiveTerminal": "never"
```

After feedback from the team we went with a more lightweight single terminal approach.

**Comment by Tyriar** [comment]
Action item: Make left click open the menu again
