### ISSUE TITLE
Setting `protocol` in `otherPortsAttributes` does nothing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125079]
Testing #124976

From the description of both settings, it feels like it should work, but the `Open in Browser` action keeps opening in `http`.

![image](https://user-images.githubusercontent.com/22350/120325383-6fb8c980-c29c-11eb-896d-e6f72b77fcd0.png)

**Comment by alexr00** [comment]
Not correctly responding to the setting change here.

**Comment by rzhao271** [comment]
Looks like it's still http for me:

![still-http](https://user-images.githubusercontent.com/7199958/120860405-7c5a4d80-c53a-11eb-8dcc-c6a1cf45561f.PNG)

**Comment by alexr00** [comment]
@rzhao271 the `https` is only visible to you when you use the "open in browser" and "open in preview" actions.
