### ISSUE TITLE
requiresMessaging: true | false | "optional" is funky

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125078]
Testing #125016

The `requiresMessaging` field is either `true`, `false` or "optional". I find this strange because it seems like `"optional"` is not in the middle of this gradation. Instead `optional` -> false -> true is the gradation.
If not for backwards compatibility can we just have 3 string values and not a boolean and a string?

![Screenshot 2021-06-01 at 14 44 16](https://user-images.githubusercontent.com/1926584/120325409-e5965280-c2e7-11eb-983b-a389469b996b.png)

**Comment by connor4312** [comment]
I swapped to strings. Opened an issue for an ask to let us customize sorting.
