### ISSUE TITLE
Can't import * from vscode-notebook-renderer

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125100]
Testing #124995

To quickly see `vscode-notebook-renderer` provides, I wanted to do `import * as nbRenderer from 'vscode-notebook-renderer';`. However, this doesn't work and I must individually import what I need.

**Comment by mjbvz** [comment]
I believe we should also always use `import type` here too. There's no actual `vscode-notebook-renderer` module to be imported, so we don't want TS to ever generate a real import

**Comment by mjbvz** [comment]
If you're using the `yo code --insiders` template, I think it is still on an older version of the api  /cc @connor4312 

However `import *` does seem to work for me. The restriction is that the package only contains types, so you will only see suggestions in valid type locations

```ts
import type * as nbRenderer from 'vscode-notebook-renderer';
const a: nbRenderer.;
```

<img width="1237" alt="Screen Shot 2021-06-01 at 1 53 52 PM" src="https://user-images.githubusercontent.com/12821956/120389111-d6f86d00-c2e0-11eb-8a37-6e520d71963c.png">

**Comment by connor4312** [comment]
I just published an update to the generators
