### ISSUE TITLE
Trust: does it make sense to ask for trust for recently opened folders?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125103]
I am testing the scenario of existing users running VSCode with trust enabled (e.g. after applying the update) which are now suddenly faced with this dialog right on startup:

![image](https://user-images.githubusercontent.com/900690/120336884-1760e680-c2f3-11eb-9b92-d4fc85c3dc56.png)

I wonder how much sense it makes to ask for trust for folders/windows we restore from a previous session or that have been opened in the past. Those workspaces/windows already were running with extensions enabled, so wouldn't asking for trust be weird at this point?

My proposal would be to only ask for trust in new windows/workspaces opened after VSCode had been updated to be trust enabled.

**Comment by sbatten** [comment]
I feel we would need to confirm with users that we add their recently opened workspaces to the list. Weird is better than unsafe imo.
