### ISSUE TITLE
Detect line break in notebook cell content

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125132]
Issue Type: <b>Bug</b>

* Open a notebook which uses `\n` as line break on Windows
* Edit a cell, undo, save
* The document becomes dirty on SCM

What happens under the hood is now the cell is saved with `\r\n`.

VS Code version: Code - Insiders 1.57.0-insider (1e446dfadf588ec28b3fdba7ac083bfa1d45df3c, 2021-06-01T05:13:48.346Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.22GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
This is actually handled by the serializer (which gives the core `value: string`).

**Comment by roblourens** [comment]
Is there some historical reason that the serializer normalizes cell source newlines @DonJayamanne?

**Comment by roblourens** [comment]
ping

**Comment by roblourens** [comment]
Actually, did we do something for this already?

**Comment by DonJayamanne** [comment]
Sorry I totally missed this.

> Is there some historical reason that the serializer normalizes cell source newlines

Not sure what you mean by this.

We've had this issue for a while now, its here https://github.com/microsoft/vscode-jupyter/issues/4576
Basically the TLDR is i think we should drop the CR and only use LFs on all OS.

I can submit a PR for that

**Comment by rchiodo** [comment]
/verified already in https://github.com/microsoft/vscode-jupyter/issues/4576
