### ISSUE TITLE
Feature request: Copy reference/relative path

### ISSUE THREAD

**Issue by z-ax** [Microsoft/vscode#12518]
Pretty useful and implemented in IDEs like IntelliJ IDEA: ability to **copy reference/relative path** to the file in project tree, or to current line/definition in editor.

At this point there's a "Copy Path" menu item, which is pretty useless to me, always have to paste it, modify and then send to colleagues.

What I expect is actually a path like `src/app.js` instead of `/Users/.../Repo/.../src/app.js`. And `src/app.js:123` when copied from editor, pointing to specific line.

Mostly switched to VSCode, so hope it'll be even more convenient.
Thanks!

**Comment by bpasero** [comment]
Sounds like an extension candidate 👍

**Comment by bgse** [comment]
@z-ax Something along these lines exists in marketplace, though it doesn't really satisfy your requirement I guess:

https://marketplace.visualstudio.com/items?itemName=alexdima.copy-relative-path

**Comment by z-ax** [comment]
Well, I added it as feature request because I'd even replace current (barely used) "Copy Path".
Not sure about the most.

Also, often need a reference to the line as well.

**Comment by bgse** [comment]
@z-ax Fully agree on the line reference, that would be a very useful feature for pointing colleagues to a specific code line.

I'd have started an extension for this, just was a bit reluctant on flooding the marketplace with dozens of extensions that more or less do the same thing.

But your proposal seems different enough compared to the existing ones to warrant its own extension.

**Comment by bgse** [comment]
@z-ax Give this a spin, maybe it helps:

https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line

Certainly not ideal, but at least provides a way to quickly copy some file/line reference suitable for quickopen.

If using Linux, you need xclip installed, not sure about Windows/OSX.

**Comment by z-ax** [comment]
@bgse thanks, will get this, with hope that it'll become a part of IDE some time :)

**Comment by canda** [comment]
@bgse great extension, thks
Is there a way to add those commands to the right click menu?

**Comment by bgse** [comment]
@canda I already had context menu integration in mind, definitely for file explorer, but your idea sounds very interesting too.

Repo is here, in case you want to open an issue for your suggestion or make a PR:

https://github.com/bgse/relative-path-and-line

**Comment by henryJack** [comment]
+1 on this. It can be an absolute time sink if you restructure your files within a project and need to adjust all the relative imports.

**Comment by z-ax** [comment]
What? Are you serious?

**Comment by henryJack** [comment]
For heaven's sake, please reopen this. This is clearly a core feature which needs to be addressed before we can take VSCode seriously

**Comment by henryJack** [comment]
*Dot Net Core
