### ISSUE TITLE
filenamePattern with capital letters doesn't work on macOS

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125156]
Testing #124992

using (notice the capital `N` in notebook):
```json

				"viewType": "pwshnb",
				"displayName": "PowerShell Notebook",
				"selector": [
					{
						"filenamePattern": "*.Notebook.ps1"
					}
				]
```

It opens in the default text editor (notice the file name has `N`):
![image](https://user-images.githubusercontent.com/2644648/120375779-081c7180-c2d0-11eb-9ef6-6af22209d3e4.png)

Now try with lowercase:
```json
                                  "viewType": "pwshnb",
				"displayName": "PowerShell Notebook",
				"selector": [
					{
						"filenamePattern": "*.notebook.ps1"
					}
				]
```
works even with capital letters:
![image](https://user-images.githubusercontent.com/2644648/120376019-3d28c400-c2d0-11eb-8e99-240c3ec0342f.png)

**Comment by jrieken** [comment]
This happens somewhere in the editor override service and/or glob matching. Actually unsure what the rules for glob and casing are. 

<img width="737" alt="Screen Shot 2021-06-02 at 12 20 34" src="https://user-images.githubusercontent.com/1794099/120464224-fd7bde00-c39c-11eb-8d0e-1b7265b0c140.png">


forwarding to @lramos15 and @bpasero, feel free to move out for May

**Comment by bpasero** [comment]
Our `glob` is case sensitive (see https://github.com/microsoft/vscode/issues/10633). But if you lowercase both sides it should be fine.

**Comment by lramos15** [comment]
I have made glob matching in this case case-insensitive. I don't know if that should be the case, but it is what I have gone with. I understand where #10633 but on Linux and Mac filesystems are case sensitive I believe. While we would alter behavior based on operating system that would be even more confusing (that's what python's glob module does). According to this blog, https://jpearson.blog/2020/04/08/tip-case-insensitive-glob-patterns/, a user could make a case insensitive blog using grouping i.e. `*.[nN]otebook.ps1`

**Comment by TylerLeonhardt** [comment]
> HFS+ (the Mac filesystem) is usually configured to be case insensitive but case preserving. This means that the file system will consider foo and FoO to be the same, but when you create a new file it will remember which letters where capitalized and which were not.

https://apple.stackexchange.com/a/22304

Just an FYI.
