### ISSUE TITLE
Collapse control fade in is too slow

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125175]
Testing #125013

Currently the fade when `showFoldingControls` is set to `mouseover` is 500ms. This is slow for that interaction. For reference, [material design](https://material.io/design/motion/speed.html#duration) suggests a 100ms duration for small controls.

Fade out can be longer.

**Comment by rebornix** [comment]
Inherit this latency from editor folding icon, we can probably update both.

**Comment by rebornix** [comment]
nvm, I think it makes good sense.
