### ISSUE TITLE
Shrinking terminal tabs should not show single terminal

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#125131]
https://user-images.githubusercontent.com/35271042/120357817-b2899a00-c2ba-11eb-9838-0bd91feb04a2.mov

Steps to Reproduce:

1. Have multiple terminal tabs open
2. Shrink view so only the icons appear
3. :bug: Single terminal tab appears

I would not expect for the single tab to appear as the point to shrink the view is to reduce the visual noise.

Version: 1.57.0-insider
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:12:30.409Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by Tyriar** [comment]
This is a feature, it's super useful as it shows the active terminal's title there which can often contain useful info. `terminal.integrated.tabs.showActiveTerminal` allows you to tweak this.

**Comment by misolori** [comment]
I'll use the setting, but I still think don't think it's useful as the user is intentionally shrinking the view and doesn't want to see it.
