### ISSUE TITLE
Trust: issue reporter does not mention trust

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125108]
When I report an issue from our issue reporter from an untrusted workspace, there is no info about this in the GH issue.

**Comment by bpasero** [comment]
Marking as important to make sure we care about this before enabling trust by default.

**Comment by TylerLeonhardt** [comment]
Two examples:
https://github.com/microsoft/vscode/issues/125533
https://github.com/microsoft/vscode/issues/125535

in an effort to make the smallest change this late in the game, I’ve put it in **System Info** however when you report a performance issue, we also have a section called “Workspace Info” that shows up that gives details on the workspace (like number of files, etc). I think it should eventually go there

**Comment by TylerLeonhardt** [comment]
lol jk @sbatten sent a PR putting it next to the OS which I don't love... but the change is small and it means the user can't _not_ tell us their WT situation which is good.
