### ISSUE TITLE
Selection in console on double click

### ISSUE THREAD

**Issue by shanimal** [microsoft/vscode#125142]
Issue Type: <b>Bug</b>

Double clicking on console text that has a soft wrap included will not select the last character.

VS Code version: Code - Insiders 1.57.0-insider (4f3d865a6b46a4ead49cf83fe1c30d95d0a34220, 2021-05-31T05:12:28.387Z)
OS version: Darwin x64 18.7.0

Last character on soft-wrapped line is not selected on double click:
<img width="956" alt="last character on soft wrap lines" src="https://user-images.githubusercontent.com/283957/120367134-5b3cf700-c2c5-11eb-8ca1-ae90f41f8993.png">

Last character on non-wrapped line is selected on double click as expected:
<img width="957" alt="last character on  non-wrapped lines works fine " src="https://user-images.githubusercontent.com/283957/120367312-90494980-c2c5-11eb-9de3-7b015af0d5db.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.41GB free)|
|Process Argv|--crash-reporter-id 451718aa-c85b-47e7-b213-cb5e640c7c47|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/3358
