### ISSUE TITLE
html file interfers with js file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1251]
- two files
```javascript
class A {
	
}

let x = 10;

const z = 10;
```
```html
<script type="text/javascript">
var i = 10;
if (i < 5) {
  // some code
}
class A {
	
}

let x = 10;

const z = 5;
z = 10;
</script>
```

JavaScript file shows errors about double symbols. Is this expected.

**Comment by jrieken** [comment]
Yeah, they both define it in the same (global scope. It's just unhappy cos we don't load html upfront when bringing up the language service. And worst it will going away with salsa.
