### ISSUE TITLE
showCellStatusBar false still shows status bar

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#125133]
Testing #125013

If the status bar contains the green check and run spinner, toggling show cell status bar is not removing that.

![recording - 2021-06-01T093453 036](https://user-images.githubusercontent.com/29464607/120359625-bd452e80-c2bc-11eb-9cdd-068ba83bc6f8.gif)

**Comment by roblourens** [comment]
This is because you also have the "afterExecute" setting enabled, which does this by design.
