### ISSUE TITLE
Cannot drag in the gutters of markdown cells

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125169]
Testing #125013

The drag cursor shows up in markdown cell gutters, but you can only actually drag on the contents

**Comment by roblourens** [comment]
Works for me

**Comment by connor4312** [comment]
Video:

![](https://memes.peet.io/img/21-06-14231734-44d8-41fb-aa94-80963b4993e8.gif)

**Comment by roblourens** [comment]
Oh, I think it's just the spot where the folding button would go, the DOM is weird there I remember fighting this in the past

**Comment by mjbvz** [comment]
Thanks @connor4312. 

Yes we previously had this for https://github.com/microsoft/vscode/issues/117489

I think it's fine to not support dragging and dropping on the folding indicator itself, but in this case it looks like the folding indicator is hidden so we should allow dragging
