### ISSUE TITLE
Contributing a PTY profile causes two terminals to be spawned

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125183]
Testing #124793

I tried contributing:
![image](https://user-images.githubusercontent.com/8586769/120389685-9ea55e80-c2e1-11eb-861c-8c2e13cbf930.png)
(Sorry no shared clipboard on my ubuntu VM 🙁)

And whenever I try to run that profile in the extension it opens two terminals, one with the write event properly firing, the other just a normal terminal:
![image](https://user-images.githubusercontent.com/8586769/120389843-ceecfd00-c2e1-11eb-8b3d-589b4d9e3973.png)
![image](https://user-images.githubusercontent.com/8586769/120389854-d4e2de00-c2e1-11eb-999a-273f552c179d.png)

**Comment by JacksonKearl** [comment]
Same thing on the other sample: 
![image](https://user-images.githubusercontent.com/8586769/120391395-ceedfc80-c2e3-11eb-8923-9471cb5385c8.png)

**Comment by Tyriar** [comment]
Can repro, it's specific to pty ones.
