### ISSUE TITLE
Context menu offscreen

### ISSUE THREAD

**Issue by mjruggiero** [microsoft/vscode#125140]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When I have the VSCode window half off screen, and right click on a file near the bottom of the screen, the context menu shows up mostly off screen.
 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.77GB free)|
|Process Argv|--crash-reporter-id e06f5a1a-ff57-4251-85de-e215b412ea53|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-wsl|ms-|0.56.4
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by sbatten** [comment]
can you provide a screenshot?

**Comment by mjruggiero** [comment]
Not a problem.
[image: vscode-issue.png]

**Comment by sbatten** [comment]
hmm, i don't think the screenshot made it through the email

**Comment by mjruggiero** [comment]
Sorry, I tried attaching it this time.

**Comment by sbatten** [comment]
unfortunately, I'm still not seeing the screenshot

**Comment by mjruggiero** [comment]
This appears to be working in the latest version, so I am closing this issue.
