### ISSUE TITLE
Trust: banner should consistently show in empty windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125115]
It now only seems to appear when a file is opened? But check this case out which makes it appear on save which is rather strange:

![recording (1)](https://user-images.githubusercontent.com/900690/120341808-7e809a00-c2f7-11eb-81a8-319836d7885f.gif)

**Comment by lszomoru** [comment]
This has now been addressed. Since we have switched the default trust state of the empty window to `trusted`, we are now showing the "restricted mode" visual affordances consistently in the empty window than the empty window is in "restricted mode".
