### ISSUE TITLE
Disabling an extension leads to "unsupported workspace"

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#125162]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.57.0-insider
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:12:30.409Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. From extensions viewlet, right click on an extension like CodeRunner and disable it.
2. Click to reload. 
3. Window reloads, but the extension viewlet is empty and reads "unsupported workspace". 

Only happens with a couple of extensions (i.e. CodeRunner, CodeLLDB) that show the "reload" tag when you disable.

![recording](https://user-images.githubusercontent.com/9721254/120377297-cdb3d400-c2d1-11eb-8ace-d07e3949b974.gif)

**Comment by paulw2u** [comment]
I've also started to see recently this after updating and reloading an extension related to python but all of my files within the workspace are plain text files (*.txt extension).

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/125047
