### ISSUE TITLE
Newly created terminal from profile is not focused after creation

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125125]
Testing #124793

- Create a new terminal using the profile contributed by the extension from the dropdown or from command pallette - `Create New Terminal Integrated Terminal (With Profile)`

🐛 Newly created terminal is not focused.

**Comment by sandy081** [comment]
It is still not getting focused when created from dropdown action in the terminal.

**Comment by Tyriar** [comment]
@sandy081 I can't repro, can you show a gif and check for console errors?

**Comment by sandy081** [comment]
Here you go

![Kapture 2021-06-03 at 19 12 10](https://user-images.githubusercontent.com/10746682/120685072-bf1b1780-c49f-11eb-9e85-ccb4be942bbf.gif)

I do not see any console errors

Here is the code snippet to register terminal profile provider

```ts
context.subscriptions.push(vscode.window.registerTerminalProfileProvider('my-ext.terminal-profile', {
		provideProfileOptions(token: vscode.CancellationToken): vscode.ProviderResult<vscode.TerminalOptions | vscode.ExtensionTerminalOptions> {
			return {
				name: 'Profile from extension',
			};
		}
	}));
```
