### ISSUE TITLE
Black line in code editors when compact view is off

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125168]
Testing #125013

![](https://memes.peet.io/img/21-06-75a03c9e-0076-4116-b55b-94d98959bb48.png)

**Comment by roblourens** [comment]
What theme? I don't see it

**Comment by connor4312** [comment]
This one: https://marketplace.visualstudio.com/items?itemName=connor4312.codesong. It does seem to be a rendering glitch, only happens on Linux and without the globalToolbar turned on. It seems like the black-ish background on this element is peeking out

![](https://memes.peet.io/img/21-06-16262151-a6f6-4c06-95ef-c1de7856e274.png)

**Comment by connor4312** [comment]
Er, maybe. Not sure. Seems to appear/disappear randomly. Probably some electron bug.
