### ISSUE TITLE
Right-Click Go To Type Definition - jump to user type not array or other system type

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/vscode#125148]
If I have a variable like:
`exampleArray : IStructure[];`
when I click on a reference to exampleArray and right-click  Go To (Peek) Type Definition I get peeks of `Array<T>` from various system-provided .d.ts files.  I would prefer to see a peek of `IStructure`.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
