### ISSUE TITLE
First attempt to change Notebook renderer mime type doesn't do anything

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125111]
Testing #124995

Here's what's happening in the following gif:
1. Run the cell.
2. Use the ... next to the output to change the output's mime type.
3. Choose my new Test Renderer to render the output.
4. Nothing happens. If I run through steps 2 and 3 again, it works.

![recording (57)](https://user-images.githubusercontent.com/38270282/120339704-9f47f000-c2f5-11eb-900c-9b442a249265.gif)

**Comment by connor4312** [comment]
I changed `notebookService.getMimeTypeInfo` to return the "preferred" renderer first, but the CellOutputViewModel was storing the _index_ of the renderer which was outdated. I pushed a fix that seems to work, please give it a quick 👀 @rebornix
