### ISSUE TITLE
Consolidated run button context menu renders behind cell output

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#125188]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0-insider 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Execute a cell to produce some cell output
2. Click on consolidated run button chevron
3. 🐛 Run action context menu renders behind cell output:
![image](https://user-images.githubusercontent.com/30305945/120392248-14f79000-c2e5-11eb-95f1-91c3f8428822.png)

**Comment by rebornix** [comment]
We need the help of God of z-index.

**Comment by roblourens** [comment]
I don't see this...

![image](https://user-images.githubusercontent.com/323878/120733567-554d3e80-c49c-11eb-8f6a-23dc541011d4.png)

**Comment by joyceerhl** [comment]
Definitely still seeing this on Windows and Insiders a62df5d6c53e844bfdc50694f943c3f34b6ff50e. Interestingly I can't repro this on macOS. @roblourens what's your setup?

![image](https://user-images.githubusercontent.com/30305945/120733765-9c3b3400-c49c-11eb-81d3-63246b0b4abe.png)

Output renderer is the built-in one:
![image](https://user-images.githubusercontent.com/30305945/120734077-208db700-c49d-11eb-83e2-b1f68239a19f.png)
