### ISSUE TITLE
Should provide option for "Set next statement" to set the current debug point.

### ISSUE THREAD

**Issue by rocksthehouse** [Microsoft/vscode#12514]
Should be able to set the current statement to execute when in the debugger from the context menu like you can do in Visual Studio. This allows you to skip code that you don't want to execute which is often valuable when it is time consuming to have to change the code, maybe rebuild and restart the debugger. Would go nicely with [4993](https://github.com/Microsoft/vscode/issues/4993).

**Comment by jawn** [comment]
Any news on this topic?

**Comment by weinand** [comment]
@jawn for what language/debugger?

**Comment by jawn** [comment]
Tried it in Powershell.

Also interested in C#/javascript, don't know if it's a gap there as well.

**Comment by weinand** [comment]
We will add the (generic) frontend UI for this feature only if enough debugger backends are actually able to support this. So far interest for the feature and support from the debugger extension authors is small.

**Comment by jawn** [comment]
@weinand thanks for the clarification!

**Comment by daviwil** [comment]
@weinand As far as I know, PowerShell's debugger does not support this feature (though it could in the more distant future).

**Comment by jonathann92** [comment]
Hi guys, when do you think this will be implemented? I find this feature very helpful when debugging code

**Comment by leechen** [comment]
+1 for C# or should this issue be created in C# plug-in?

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
