### ISSUE TITLE
message something like this is seen in my terminal

### ISSUE THREAD

**Issue by Yugalkoirala** [microsoft/vscode#125141]
Issue Type: <b>Performance Issue</b>

'stdio.h' file not found
Expected identifier or '('

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.37GB (2.31GB free)|
|Process Argv|--crash-reporter-id 09b71cbf-be8c-454b-8ac1-ca63e06caeed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  1564	code main
    0	    77	 10636	   window (Issue Reporter)
    0	    82	 11904	   shared-process
    0	    65	 23124	     ptyHost
    0	    54	 12824	   crashpad-handler
    0	    60	 13412	   utility
    0	   192	 19748	   gpu-process
    0	   169	 22084	   window (Untitled-1 - Untitled (Workspace) - Visual Studio Code)
    0	   200	  8660	     extensionHost
    0	    20	  8560	       c:\Users\Yugal\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\12.0.0\clangd_12.0.0\bin\clangd.exe
    0	    11	  1344	         console-window-host (Windows internal process)
    0	    67	 10016	     searchService
    0	    14	 15616	     watcherService 
    0	    10	 24416	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-1 - Untitled (Workspace) - Visual Studio Code)
|    Folder (PRACTICE): 12 files
|      File types: c(5) json(3) exe(3)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
c-cpp-compile-run|dan|1.0.14
code-runner|for|0.11.4
c-cpp-runner|fra|0.14.1
vscode-pull-request-github|Git|0.26.0
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.5
ccpp-extension-pack|Leo|1.1.0
vscode-clangd|llv|0.1.11
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4272
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943:30300582
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
