### ISSUE TITLE
notebook.showCellStatusBar and notebook.showCellStatusBarAfterExecute should be one setting

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125173]
Testing #125013

There are four combinations of settings for status bar visibility:

- always
- never
- never except for after execute
- always and after execute

The last state is invalid, as the documentation on `showCellStatusBarAfterExecute` indicates. It would make more sense to combine these into a single setting with three enum values.

**Comment by roblourens** [comment]
That makes perfect sense...
