### ISSUE TITLE
Editor override should support case-insensitive extensions

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#125198]
Testing #122367

I currently have these settings:

```json
"workbench.editorAssociations": {
        "*.png": "luna.editor",
        "*.txt": "default",
        "*.ipynb": "jupyter-notebook",
        "*.PNG": "imagePreview.previewEditor"
    },
```

I opened a file named `200.PNG`, and Luna Paint showed up. When I tried adjusting the default editor, the Luna Paint option showed up multiple times:

![luna-dup](https://user-images.githubusercontent.com/7199958/120396458-715dae00-c2eb-11eb-8591-1e092b597516.png)

Also, the image never loaded up in Luna Paint, but I'm not sure if that's a separate issue.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/124779
