### ISSUE TITLE
iPad: Quick open matches are illegible

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125116]
Light theme

![IMG_6115104D0ACA-1](https://user-images.githubusercontent.com/22350/120342124-57e94180-c2ac-11eb-8494-193ff94e040a.JPEG)

**Comment by misolori** [comment]
🤔 Hmm...temporary bug? Looks syntax highlighting in your image hasn't kicked in yet.

![image](https://user-images.githubusercontent.com/35271042/120398825-c6032800-c2ef-11eb-9f10-788b6f0be02c.png)

**Comment by joaomoreno** [comment]
Can't repro today 😕
