### ISSUE TITLE
Expose NPM's Pre & Post Scripts to Extension Developers

### ISSUE THREAD

**Issue by rbrisita** [microsoft/vscode#125191]
Currently, VS Code offers [vscode:prepubllish](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prepublish-step) and [vscode:uninstall](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook) for extension developers to use. I would find it helpful if NPM's native support for [pre and post scripts](https://docs.npmjs.com/cli/v7/using-npm/scripts#pre--post-scripts) were exposed as well. For my specific needs a `vscode:postinstall` would be helpful to extract platform and architecture detection to a bootstrap script rather than that code live in `extension.js`.

**Comment by sandy081** [comment]
> For my specific needs a vscode:postinstall would be helpful to extract platform and architecture detection to a bootstrap script rather than that code live in extension.js.

Does your extension need platform specific binaries before activating?

**Comment by rbrisita** [comment]
Yes, checks type and proceeds to check if the tools it needs to work are available. One of the packages also relies on 'install' from it's own 'package.json' file which I manually call if file is not found.

**Comment by sandy081** [comment]
/duplicat

We are working on platform specific extensions feature for this specific use case - https://github.com/microsoft/vscode/issues/23251
