### ISSUE TITLE
Solarized dark theme has the same color for occurrence-highlight and selection highlight

### ISSUE THREAD

**Issue by michalvankodev** [Microsoft/vscode#12515]
- VSCode Version: 1.5.3
- OS Version: Fedora 24

Basically I am unable to see what I have selected because the theme has the same color for highlight for line as for the actual selection. Very annoying

**Comment by chrmarti** [comment]
Which language is this? Please attach a screenshot.

**Comment by michalvankodev** [comment]
[Screenshot](http://imgur.com/a/9Wg1i)

It's typescript.
As you can see I am on selecting a part of the variable on line 7. But i cant see what I'm selecting on that line I have to always look around. 

The behavior of selecting text also differs when selecting from variables or from function calls.

**Comment by chrmarti** [comment]
The line-highlight disappears, but there is the occurrence-highlight that remains and indeed has the same color as the selection. A bug in the theme.

**Comment by Strate** [comment]
Related to this: almost invisible text under selection with solarized light:
![image](https://cloud.githubusercontent.com/assets/392644/22819369/dbf089fe-ef82-11e6-872f-40e8932d687d.png)

**Comment by tobynet** [comment]
Me too. (@Strate)

`Markdown` too. See below.
The words can **not** be viewed at all.

![image](https://cloud.githubusercontent.com/assets/20859/25152268/6a9986c2-24c3-11e7-9b0c-f581ffaeea98.png)

Plain text:

    # About Java

    * Java+You, Download Today

      あなたとJAVA, 今すぐダウンロード

    > JAVA 与您, 立即下载

    ```java
    Console.WriteLine("Hello Not Java");
    ```

    **JAVA** EN U, NU DOWNLOADEN

    _JAVA + UTENTE_, SCARICA OGGI


Environments: 

```text
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

**Comment by bpasero** [comment]
I think this issue is no longer present given our theming work.

Occurences:
![image](https://cloud.githubusercontent.com/assets/900690/26281473/ebf1bf08-3df7-11e7-917c-7ab7fbae9503.png)

Selection:
![image](https://cloud.githubusercontent.com/assets/900690/26281474/f80903dc-3df7-11e7-90c9-99191f95a7ae.png)

**Comment by alexandrudima** [comment]
@bpasero :+1: I think this got fixed in the meantime
