### ISSUE TITLE
Generated template for custom notebook renderers won't compile

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#125196]
Testing #125016

When I generate the template extension code using `npm install -g generator-code && yo code --insiders`, I get an error in `client/index.ts`
![image](https://user-images.githubusercontent.com/31675041/120395457-4165d900-c2f2-11eb-8f3d-c500ec83d3b0.png)

**Comment by andreamah** [comment]
Following up on this, there are also some issues with `extension/sampleProvider.ts` when I download the template including the kernel.
![image](https://user-images.githubusercontent.com/31675041/120402449-7c223e00-c2ff-11eb-95a1-52896f0edfb4.png)

**Comment by connor4312** [comment]
thanks, looks like several updatees are needed. I recommend using the github-issues-notebook as a sample/starter for verification purposes

**Comment by jrieken** [comment]
@tanhakabir Where do those template come from?

**Comment by tanhakabir** [comment]
generator-code, I haven't pushed an update for the serializer/kernel yet since we'll be pushing the API onto stable soon, but the renderer should work. I can check

**Comment by connor4312** [comment]
@tanhakabir I think you resolved this with the onboarding work last iteration?

**Comment by connor4312** [comment]
Looks like it https://github.com/microsoft/vscode-generator-code/commit/4da9eda7fdb6cd0ea2045de3ca6ff86948b1d3e9

**Comment by TylerLeonhardt** [comment]
Looks fixed:

![image](https://user-images.githubusercontent.com/2644648/127560386-4a651c72-16b6-47ad-8859-1a82a42380f0.png)

One question... I noticed that it has a `main` entry point. This isn't needed right? This also blocks the generated extension to be installed on Web because of that `main` entry point without a browser one.

I think we probably want to either remove the main or add a browser.

**Comment by connor4312** [comment]
@TylerLeonhardt I think that's a good idea, the trouble is that if the user doesn't have a notebook capable of outputting the given mimetype already then they can't see their renderer. I know we're talking about having a built-in ipynb deserializer, though it looks like that doesn't exist yet. @rebornix is that still the plan? If so we can include a `sample.ipynb` and know that it'll work.

**Comment by rebornix** [comment]
>  I know we're talking about having a built-in ipynb deserializer, though it looks like that doesn't exist yet. @rebornix is that still the plan? If so we can include a sample.ipynb and know that it'll work.

We have the ipynb serialzier shipped with the coming VS Code Stable.

**Comment by connor4312** [comment]
Oh, sweet! I see it now, I was a couple Insiders behind on my home PC.
