### ISSUE TITLE
Extension viewlet shows (1) but nothing to update

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#12516]
Today's insiders:

![image](https://cloud.githubusercontent.com/assets/5047891/18786421/75dd4930-81a6-11e6-9e1e-9740c1599a6a.png)

![image](https://cloud.githubusercontent.com/assets/5047891/18786413/6c4a3752-81a6-11e6-8897-4c3684a9ac56.png)

**Comment by alanwei0** [comment]
me too

**Comment by joaomoreno** [comment]
#12507
