### ISSUE TITLE
Live server preview: Preview the current editor like in Markdown

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#125170]
Testing #124865

- open the vscode repo and open `extensions/theme-seti/icons/preview.html` in an editor
- to see the preview I have to: start the server, open the preview (which shows the `index of /`), navigate to my page

I'd like to suggest a similar experience as with the Markdown preview, where I click on the preview button.
<img width="303" alt="image" src="https://user-images.githubusercontent.com/6461412/120380113-0929bf00-c321-11eb-8a31-ff5ff357cd6e.png">

That preview is part of the editor, which has some advantages, such as it doesn't open a second column where other editors are opened as well.

Would be nice if starting and stoping the server should is handled in the background, maybe by shutting down if there's no longer a browser looking at a page (assuming you have a connection from the page to the server)

Alternative: The [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) has a `Go Live` entry in the status bar.

**Comment by andreamah** [comment]
Issues already mentioned in  #125854 and #125775
