### ISSUE TITLE
[Feature request] I would like to exclude workspace folders from search when I press `Ctrl` + `P`

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#125190]
On a workspace, I would like to exclude workspace folders to find quickly the only file of a folder during the search when I press <kbd>Ctrl</kbd> + <kbd>P</kbd>. For example:

![example](https://user-images.githubusercontent.com/2257024/120392659-2fdafc00-c307-11eb-9034-040e346a0a25.png)

You can see three files with the same name of different three apps of two folders. I would like to exclude the folder `Django` so I can click that only file once in a millisecond, I would not need to move my mouse to click `gusbemacbe.co.nz` folder's file `settings.py` or would not need to jump three times in few seconds. 

The settings `files.exclude` does not solve because it excludes all three files with the same name. And `search.exclude` does not exclude that folder `Django`, maybe because it is a workspace.

**Comment by roblourens** [comment]
It sounds like maybe you want to configure `files.exclude` for that file just in one workspace folder by setting it in `.vscode/settings.json` for that workspace

**Comment by gusbemacbe** [comment]
No, I want to exclude the folders from the search. 

I have Django and gusbemacbe.co.nz folders added to the workspace, but I need to exclude Django, even if it continues being added to the workspace.

**Comment by roblourens** [comment]
You can configure `files.exclude` with `*` (maybe `**/*`) in that folder to exclude it. Not an elegant solution. You can also type few characters from the folder name that you want to include in the search in quick open to filter to that folder.
