### ISSUE TITLE
Left-hand cell toolbar overlaps markdown content

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125167]
Testing #125013

![](https://memes.peet.io/img/21-06-af7938ba-39bf-491c-877b-eed59fd7f350.png)

**Comment by roblourens** [comment]
My personal view is that it's fine

**Comment by misolori** [comment]
This is an effect of the compact mode and I think will be a problem. Let us not forget https://github.com/microsoft/vscode/issues/114730

**Comment by kieferrm** [comment]
For me personally, the overlay of the cell toolbar with the content of markdown cells makes the left cell toolbar position unusable.

**Comment by roblourens** [comment]
Image is gone, but I think we have shifted things so that this isn't an issue anymore
