### ISSUE TITLE
Xubuntu: InvalidOperationException when debugging with .NET Core Launch (web) 

### ISSUE THREAD

**Issue by Auersberg** [Microsoft/vscode#12517]
- VSCode Version: 1.5.3
- OS Version: Xubuntu 16.04

Steps to Reproduce:
1. Create ASP.NET Core app
2. Start debugging with ".NET Core Launch (web)".

Every time a request hits the server, the exception is thrown. The browser gets no response (blank screen). Note: There is no exception when attaching to the server (dotnet) process with ".NET Core Attach".

Exception::
<pre>
Hosting environment: Development
Content root path: /home/osboxes/Coding
Launching browser (xdg-open http://localhost:5000)
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.1/System.Threading.Tasks.Extensions.dll'. Cannot find or open the symbol file.
[...]
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.1/System.Resources.ResourceManager.dll'. Cannot find or open the symbol file.
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.ni.dll
</pre>

Project: https://github.com/blackcity/backload
web: https://www.backload.org

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#781

**Comment by weinand** [comment]
@chrmarti this is a problem of the C# debugger. Moving to their repo.
