### ISSUE TITLE
Proposed API d.ts file contains invalid references

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#125161]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Main branch
- OS Version: N/A

Steps to Reproduce:

1. The proposed API has referenbce to `import { URI } from 'vs/base/common/uri';`
2. Hence this file cannot be used in extensions
Added here https://github.com/microsoft/vscode/issues/125137

Basically extensions fail to compile due to this missing type/ref (extensions that use `vscode-dts dev` will pull from main branch right now).

**Comment by DonJayamanne** [comment]
@meganrogge /cc

**Comment by meganrogge** [comment]
Thanks, I reverted that
