### ISSUE TITLE
Trust banner: links loose underline on hover?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125110]
Typically links show an underline when I hover over them with the mouse but in the trust banner it seems the opposite happens: the underline removes on hover.

**Comment by lszomoru** [comment]
In order to distinguish the "actions" (ex: Manage Learn More) in the banner from the text we settled on using the underline.
I am happy to tweak the hover style so that the underline is kept when the user hovers over the action. 

@misolori, any other thought on this?

**Comment by misolori** [comment]
Yea we can keep the hover, because on hover the pointer already changes that satisfies the accessibility requirement for links.
