### ISSUE TITLE
`createTerminal` with `message` option doesn't seem to work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125181]
Testing #124712

I tried modifying the terminal sample to specify a `message` in `TerminalOptions`:

```ts
	// vscode.window.createTerminal
	context.subscriptions.push(
		vscode.commands.registerCommand('terminalTest.createTerminal', () => {
			vscode.window.createTerminal(`Ext Terminal #${NEXT_TERM_ID++}`, {
				message: 'Hello World',
			} as any);
			vscode.window.showInformationMessage('Hello World 2!');
		})
	);
```

But I couldn't get it to output anything

**Comment by meganrogge** [comment]
calling `vscode.window.createTerminalFromOptions` with a message works. not sure if it should also work for `vscode.window.createTerminal`

**Comment by eamodio** [comment]
Ugh, I knew I was doing something wrong, was specifying the name in addition to the args. Thanks! :)
