### ISSUE TITLE
terminal.integrated.env.windows does not work from .code-workspace

### ISSUE THREAD

**Issue by nunoperalta** [microsoft/vscode#125164]
> We've removed workspace shell permissions in main due to the upcoming workspace trust feature. This is no longer needed

In the comment in https://github.com/microsoft/vscode/issues/103415#issuecomment-668130384 , it was suggested this "workspace shell permissions" in https://github.com/microsoft/vscode/issues/80674 as a fix for the `terminal.integrated.env.windows` not working.

I have:

```
		"terminal.integrated.env.windows": {
			"COMPOSE_DOCKER_CLI_BUILD": "0",
			"DOCKER_BUILDKIT": "0"
		},
```

And the terminal (PowerShell) isn't getting those envs:

```
PS > echo $env:DOCKER_BUILDKIT
PS > echo $env:COMPOSE_INTERACTIVE_NO_CLI
PS > [Environment]::GetEnvironmentVariable("COMPOSE_INTERACTIVE_NO_CLI")
PS > [Environment]::GetEnvironmentVariable("DOCKER_BUILDKIT")  
```

If the workaround no longer exists, what can I do?

If the new trusted workspaces feature isn't released yet, this will be broken until that's released?

Thank you.

**Comment by Tyriar** [comment]
There is the setting `terminal.integrated.allowWorkspaceConfiguration` as a workaround until trusted workspaces ships.
