### ISSUE TITLE
The linter for PowerShell is running for markdown cells 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125160]
Testing #124992

![image](https://user-images.githubusercontent.com/2644648/120377037-70b81e00-c2d1-11eb-8ac6-f8ff20f8edbd.png)

For some reason the PowerShell linter is being run on markdown cells even though they are clearly marked markdown. Let me know what other info would be useful.

**Comment by TylerLeonhardt** [comment]
This appears to be the fault of the Language Server so we probably want to have some kind of call out for this and maybe how the cell Uri is constructed?

**Comment by jrieken** [comment]
> and maybe how the cell Uri is constructed?

The uri of cell text document is constructed following these rules

* give a notebook `file:///my/happy/notebook.ps1`
* a cell uri is `vscode-notebook-cell:///my/happy/notebook.ps1#0000001` (for the first cell etc)

My guess is that the pwsh language server doesn't check the languageId of documents but goes by the path (which is the same for all cells)

**Comment by TylerLeonhardt** [comment]
Yeah I think that's right based on this code:
https://github.com/PowerShell/PowerShellEditorServices/blob/3274c230cc6675859d5c89d6c176219c2c9430f7/src/PowerShellEditorServices/Utility/LspUtils.cs#L16

Some docs around this would be nice. Maybe there's some way for them to work around this?

**Comment by jrieken** [comment]
> Maybe there's some way for them to work around this?

Check the `languageId`. That's the truth and the filepath is more or less arbitrary
