### ISSUE TITLE
`"files.autoSave": "onFocusChange"` causes issues with virtual file systems

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125124]
Virtual file system is not available notification when restoring opened editors

![notification](https://user-images.githubusercontent.com/641685/120351957-4d3fa400-c2ce-11eb-9e6e-8484368829ad.gif)

Steps:

1. Ensure you have RemoteHub insiders installed (and ensure RemoteHub stable is disabled).
2. Open a remote repository, via _Open Remote Repository..._ from the command palette
3. Open a file from the remote repository
4. Now reload the window or close and re-open the remote repository

It seems to only happen we the `"files.autoSave": "onFocusChange"` set, if I remove that it works normally.

Here is the call stack of where it happens too:
![image](https://user-images.githubusercontent.com/641685/120352485-cf2fcd00-c2ce-11eb-87f1-3694afa374d4.png)

**Comment by eamodio** [comment]
Another instance of this can be reproduced with Git or GitLens, but has a slightly different behavior.

Steps:

1. Edit a file, and in the SCM view, right-click on the edited file and choose `Open File (HEAD)`
2. Reload the workspace
3. :bug: you will now see a save dialog for that file

**Comment by bpasero** [comment]
A regression from `EditorInputCapabilities` I added a few days ago. Apparently `FileEditorInput` can be `untitled` too 🐙

**Comment by eamodio** [comment]
@bpasero With today's insiders (which should have this fix), I'm still seeing the same behavior.

**Comment by bpasero** [comment]
Ok, I don't see it 🤷

**Comment by eamodio** [comment]
With the 2nd insiders release that came out today, I'm not longer seeing it. Not sure why I was before.
