### ISSUE TITLE
Is there a way to use VSCode for building a browser based IDE?

### ISSUE THREAD

**Issue by viralmodi** [microsoft/vscode#125199]
I am looking to develop a browser based IDE using VSCode. I came across this feature request https://github.com/microsoft/vscode/issues/55917 which did not answer my question. I am also aware of Theia framework. However, I am looking to actually use VSCode itself, if possible. I have the following questions:
1. Is it possible to use VSCode to build a web based IDE? If yes, any pointers as to what needs to change and how to integrate it?
2. Would there be any licensing issues in doing this?

**Comment by weinand** [comment]
@viralmodi suggestion: search for "run vscode in browser"?

**Comment by viralmodi** [comment]
I did post this on StackOverflow - https://stackoverflow.com/questions/67796819/is-it-possible-to-use-vscode-to-create-a-webbased-ide. However, I wanted to get an answer from MSFT VSCode engineers :)

@weinand. Thanks for your input. I had done such google searches before posting here. Had also found this https://github.com/cdr/code-server and a few other articles. What I am looking for is to understand how to go about doing this using existing VSCode source code. (not ready-made code). I couldn't find anything that explains this. I will search for "ios" in existing issues to see if they explain what I want to learn.

**Comment by viralmodi** [comment]
@weinand The ios thread talks about using code-server. Is that the solution that MSFT is recommending for using VSCode for a browser based IDE?
