### ISSUE TITLE
Live Server: Reload doesn't properly set forward and back buttons

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#125151]
Testing #124865
1. Have an index.html file open in preview
2. Reload window
3. The forward and back buttons show as not disabled
4. Click refresh
5. 🐛 Now they're disabled. They should always have been disabled.

**Comment by andreamah** [comment]
I can't seem to replicate this issue. :(  Can you try using the new vsix from https://github.com/andreamah/VS-Code-LiveServer-V2-Extension/releases/tag/0.2 and see whether it still happens?

**Comment by lramos15** [comment]
I tried to reproduce it but now it seems more broken in that I lose what page I was on upon reload. 
![recording](https://user-images.githubusercontent.com/4544166/121250455-bba6d800-c873-11eb-9e38-51a80812a7ae.gif)

**Comment by andreamah** [comment]
Ohhh oops, I thought that you meant that you pressed the reload button within the preview. #125775 should cover this issue (keeping the file when reloading the vscode window) and it's being addressed now :')
