### ISSUE TITLE
Improve cellToolbarLocation documentation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125165]
Testing #125013

I have no idea what the "item" here is

![image](https://user-images.githubusercontent.com/2230985/120378867-d3aab480-c2d3-11eb-8585-3507149aedc3.png)

**Comment by sandy081** [comment]
Same with me - not sure what Add Item does and what as a user I can add.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/125129
