### ISSUE TITLE
Webview not loading scripts in html when extension is used in codespace

### ISSUE THREAD

**Issue by preetriti1** [microsoft/vscode#125251]
Does this issue occur when all extensions are disabled?: Yes/No Did not try, My extension requires one more extension to be installed so those are the only ones

- VS Code Version: Latest codespace version
- OS Version: Linux OS in codespace

Steps to Reproduce:

1. Install Azure Logic Apps (Standard) extension.
2. Sign in to Azure and create a new project, add a workflow and navigate to workspace.
3. Right click on workflow.json and click overview.

**Issue: this shows blank page**, on inspecting network calls it gets stuck in loading script files in webview html.

If I use experimental extension and do breakpoints while the command is in execution, i can see the webview loaded, but with marketplace extension this never works. Not sure if this is a timing issue, but from network logs it looks like scripts get loaded fine when I have breakpoints set.
Please help taking a look at this issue, this completely blocks our codespace experience.

@cmbrose @alexr00 @mattbierner @bec-lyons

**Comment by mjbvz** [comment]
Please share a minimal example extension that demonstrates the issue

Also make sure to test using codespaces insiders
