### ISSUE TITLE
Addes indentation while saving

### ISSUE THREAD

**Issue by falcon-Z** [microsoft/vscode#125268]
Issue Type: <b>Bug</b>

I use ESLint to indent with 2 paces and when i format document or fix with ESLint the formatting works and once i hit save the document  reformats indents everything with more spaces and a extra line for indicating blocks appears unnecessarily. Same happend with python code and I also tried the same without Eslint and had the same issue

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5500  @ 2.80GHz (2 x 2793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.74GB free)|
|Process Argv|--crash-reporter-id 8f2b9258-0ac0-42a6-b217-38fc960fbcf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.12.0
vscode-apollo|apo|1.19.3
vscode-django|bat|1.6.0
vscode-eslint|dba|2.1.20
vscode-npm-script|eg2|0.3.21
vscode-graphql|Gra|0.3.16
vscode-edge-devtools|ms-|1.1.9
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-react-native|msj|1.5.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by rebornix** [comment]
@falcon-Z do you have auto format on save turned on?
