### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by davi-mbatista** [Microsoft/vscode#12523]
- VSCode Version: Version 1.6.0-insider (1.6.0-insider)
- OS Version: macOS Sierra 10.12 (16A323)

Steps to Reproduce:

1. Open the app
![screen shot 2016-09-23 at 10 55 23](https://cloud.githubusercontent.com/assets/13774283/18788169/473da69e-817c-11e6-9095-96ed88a39b89.png)

2.

**Comment by mrmlnc** [comment]
See https://github.com/Microsoft/vscode/issues/12473

**Comment by bpasero** [comment]
Hm, I start to wonder if everyone on Sierra is seeing this issue?

**Comment by mrmlnc** [comment]
@bpasero, unfortunately, it seems to me, yes. I see same result with macOS Sierra in VirtualBox (clean installation). But only in maximize window mode for VS Code (stable/insider). Also I see same result with Chrome 53.*

<details>
  <summary>Chrome</summary>
![2016-09-23_23-38-43](https://cloud.githubusercontent.com/assets/7034281/18800732/3ca90816-81e7-11e6-8b8a-0a5293017c69.gif)
</details>

<details>
  <summary>Safari</summary>
![2016-09-23_23-39-23](https://cloud.githubusercontent.com/assets/7034281/18800744/49cbf7d8-81e7-11e6-8500-20955abf4924.gif)
</details>

<details>
  <summary>VS Code insiders (without maximize window mode)</summary>
![2016-09-23_23-33-43](https://cloud.githubusercontent.com/assets/7034281/18800795/a1a667e0-81e7-11e6-8259-e02234e0544a.gif)
</details>

<details>
  <summary>VS Code insiders (with maximize window mode)</summary>
![2016-09-23_23-27-14](https://cloud.githubusercontent.com/assets/7034281/18800777/8ad20560-81e7-11e6-9cb2-30c158471c1d.gif)
</details>

**Comment by bpasero** [comment]
@mrmlnc are you saying this is only an issue when running Sierra inside a VM?

**Comment by mrmlnc** [comment]
@bpasero, nope, users sometimes write about it on Twitter after upgrade to final release.

**Comment by bpasero** [comment]
@mrmlnc also could be related to using a custom color profile if I read the chrome bug correctly.

**Comment by davi-mbatista** [comment]
I'm not running on VM. @bpasero this happens right after startup. It's always there. But I can confirm that changing my color profile to the "default" one of macOS Sierra seams to mitigate the bug. But the case is, this is not the right profile for my monitor and this wasn't happening on El capitan or Yosemite.

**Comment by bpasero** [comment]
@davi-mbatista and you see the same issue with Chrome 53?

**Comment by davi-mbatista** [comment]
@bpasero Yes. The same issue with chrome 53

**Comment by mrmlnc** [comment]
@bpasero,

> also could be related to using a custom color profile if I read the chrome bug correctly.

I found two users and tested it on two laptops (macOS Sierra GM & Release) and it's true. When I turn the color profile to the default - everything works fine.

> Does this happen right after startup or only when using for a while?

After startup.

**Comment by davi-mbatista** [comment]
Guys... this is still a issue. Changing the color profile ONLY mitigates it. If you change your contrast you'll still se the bug. But, if I run vscode with:

 /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --force-gpu-rasterization

Everything looks normal.

**Comment by bpasero** [comment]
We should release note this as a workaround. Though I am not certain what the drawbacks are from using `--force-gpu-rasterization`, it might have a performance impact.
