### ISSUE TITLE
nable to open 'XXXX.ipynb': i.NotebookCellMetadata is not a constructor.

### ISSUE THREAD

**Issue by narukisosu** [microsoft/vscode#125248]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (system setup)
Chrome: 89.0.4389.128
Node.js: 14.16.0
OS: Windows_NT x64 10.0.21390

Steps to Reproduce:
1.Jupiter is no longer available due to an update (run)
Worked fine until a few days ago.
I had this problem a few months ago, but it came back.
2.Unable to open 'XXXX.ipynb': i.NotebookCellMetadata is not a constructor.

**Comment by rebornix** [comment]
this is caused by API update of VS Code and extensions update is not picked up yet. Reloading the windows should fix the problem.
