### ISSUE TITLE
Consider make it possible to show the test message again after closing it

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125240]
Currently, if the user closes the test message view by mistake and make some changes to the file. Then, the user cannot see the message again if the user wants to see them.

I think it's a common case when the user wants to check the test messages multiple times when he/she wants to correct it. Especially in Java, the stack traces are important clues for diagnostic. 

https://user-images.githubusercontent.com/6193897/120453447-a2121600-c3c5-11eb-9cd1-9ae238cb87f3.mp4

**Comment by connor4312** [comment]
This is possible with the `Test: Peek Output` command (bound to `ctrl+; m` by default) or by clicking on the test in the explorer. We could add an additional context menu item on the test decoration, and/or code lenses when those eventually come in.

**Comment by jdneo** [comment]
Sorry I was not aware of the command `Test: Peek Output`.

Agree that an additional context menu item for peeking the output would be very helpful!
