### ISSUE TITLE
Cell action toolbar is shown on top of suggestions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125235]
Testing #125013

![image](https://user-images.githubusercontent.com/10746682/120443568-11b4e080-c387-11eb-9e8c-794f047ca4bd.png)

**Comment by roblourens** [comment]
Just when it goes across editors, interesting

**Comment by rebornix** [comment]
Similar issue https://github.com/microsoft/vscode/issues/129769. The suggest widget apparently is not globally closer to the user.

**Comment by rebornix** [comment]
I bumped the zindex to 50 to fix https://github.com/microsoft/vscode/issues/119732. In the issue, I said I will make it 36, but for whatever reason, I did 50. And the Suggest Widget is 40 :)

**Comment by stuartleeks** [comment]
Verified on Windows
