### ISSUE TITLE
Consider rebinding `ctrl+shift+~` to creat terminal with profile in instead of default

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#125263]
after the new version of vscode is supported terminal with profile. we are strongly recommend that we should rebinding the short cut `ctrl+shift+~` to `workbench.action.terminal.newWithProfile` in stead of `workbench.action.terminal.new`
```
    {
        "key": "ctrl+shift+oem_3",
        "command": "workbench.action.terminal.newWithProfile",
        "when": "terminalProcessSupported"
    },
    {
        "key": "ctrl+shift+oem_3",
        "command": "-workbench.action.terminal.new",
        "when": "terminalProcessSupported"
    },
```

**Comment by Tyriar** [comment]
We still want as few prompts available for the default keybinding to make it easy to create terminal(s), but the command is available for just this sort of customization.
