### ISSUE TITLE
Would you like to consider adding an snippets editor ?

### ISSUE THREAD

**Issue by hua03** [microsoft/vscode#125242]
Hi, I've noticed that both configuration and shortcuts add an interactive UI. Does snippets add similar features ?

**Comment by movermeyer** [comment]
Have you looked for extensions that might do this?

I haven't tried them, but both [Snippets Ranger](https://marketplace.visualstudio.com/items?itemName=robole.snippets-ranger) and [Easy Snippets](https://marketplace.visualstudio.com/items?itemName=inu1255.easy-snippet) seem to do this.

**Comment by hua03** [comment]
Thanks, It fulfills my needs.
