### ISSUE TITLE
Does the setting notebook.insertToolbarPosition shall be called notebook.insertToolbarLocation

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125231]
Testing #125013

Setting `notebook.insertToolbarPosition` is to configure the location of insert toolbar. So I think `notebook.insertToolbarLocation` fits well similar to  `notebook.cellToolbarLocation`

**Comment by rebornix** [comment]
Fixed via 9bd7cbd1403eadbcd12eb9b6d0a1610996454423
