### ISSUE TITLE
Refine CellInfo-type

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125269]
Today, the `CellInfo` type that is passed into `renderCell` is bit of a mix. It contains the actual output, the element to render onto, and metadata. I think a little more structure would be better. Suggestions

* make the HTMLElement a dedicated argument of the renderCell-function
* rename `CellInfo` to `OutputItem` or just `Output` 
* rename `bytes()` to `data()`
* make id the last argument of renderCell?

**Comment by connor4312** [comment]
> make id the last argument of renderCell?

This can be passed when `requiresMessaging` is set, since (as far as I know) it's not useful internally.

**Comment by mjbvz** [comment]
1. How about moving the `id` into `CellInfo`? `renderCell(element, cellInfo)`
1. `OutputItem` is ok with me but feels a little weird for markup cells (I guess for those you can think of them as being their own output)

    If we make this change though, we should also rename `renderCell` to `renderOutputItem`

1. `data` sounds good. It's closer to the `fetch` api

**Comment by mjbvz** [comment]
I'll go ahead and prep a PR that makes the code changes but will hold off on merging anything until you take a look @jrieken

**Comment by mjbvz** [comment]
Checkin to code with #125351. Types and samples should be updated now too
