### ISSUE TITLE
Pressing Ctrl-R twice will open a folder unexpectedly

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode#125238]
Issue Type: <b>Bug</b>

1. Open a VSCode window
2. Press and hold Ctrl-R, then VSCode will pop out a scrolling list of recent opened folders.
3. Release Ctrl-R, and nothing will happen. This is fine.
4. Keep the scrolling list open, then press and hold Ctrl-R again. The next item in the scrolling list will be selected (strange behavior but acceptable).
5. (Issue!) Release Ctrl-R, then VSCode will open the selected item in current window.

This experience is quite strange because the same key is used to
- pop out a list
- select an entry
- enter the selection

Pressing Ctrl-R twice is the shortcut of renaming variable in Visual Studio, so it's annoying when I press it by mistake and then current window is reloaded to open another folder.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.02GB free)|
|Process Argv|D:\\(TopSecret)KubeConfigV7Clusters --crash-reporter-id e562f803-0647-49e2-8b05-490928911d2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
unique-lines|bib|1.0.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.41.1
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
gc-excelviewer|Gra|3.0.42
kite|kit|0.146.0
vscode-idl|kur|0.1.2
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
vscode-dotnet-runtime|ms-|1.1.0
mssql|ms-|1.10.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
cpptools|ms-|1.4.0
powershell|ms-|2021.5.1
team|ms-|1.161.1
azurerm-vscode-tools|msa|0.15.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
bash-debug|rog|0.3.9
vscode-open|san|0.1.0
trailing-spaces|sha|0.3.1
vscode-hexdump|sle|1.8.1
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833cf:30267465
vshan820:30294714
vscorecescf:30290706
vscus158cf:30286554
vscod805cf:30301675

```

</details>

**Comment by bpasero** [comment]
This can be configured in keybindings:

```json
{
    "key": "ctrl+r",
    "command": "-workbench.action.quickOpenNavigateNextInRecentFilesPicker",
    "when": "inQuickOpen && inRecentFilesPicker"
}
```
