### ISSUE TITLE
Stop / disconnect of child session should always respect the parent session

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125230]
We got feedback from  @luabud @karthiknadig @int19h that in the python scenario case the sub sessions should not have the `disconnect` button but should always respect the parent and thus have the `stop` button.

@weinand had a very pragmatic solution that all child sessions should always have the `stop` button, even if they are the `attach` configuration.
If we can not do it in such a practical way we should introduce an [`DebugSessionOptions`](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L12948) attribute so this can be controlled

Let me know what you think @connor4312

**Comment by luabud** [comment]
Thank you for filing this!

**Comment by int19h** [comment]
See https://github.com/microsoft/vscode/issues/101140 for the previous discussion on this.

**Comment by isidorn** [comment]
Decided to change that if session has a parent that it is an `attach` session only if it's parent session is also an attach session.
Let's see how this works in practice. Try it out with vscode insiders and let me know what you think.
Thanks

**Comment by luabud** [comment]
@isidorn I tried it with a Flask application and I still see the disconnect button:
![image](https://user-images.githubusercontent.com/45497113/121605603-8def9980-ca01-11eb-9d6b-3f41b495ca2e.png)

but I'm not sure if that's expected or if it'll be in tomorrow's Insiders 😅

FWIW this is the sample I'm using: https://github.com/luabud/pvscc-logo, with this launch.json configuration file:

```json
    {
      "name": "Python: Flask 2",
      "type": "python",
      "request": "launch",
      "module": "flask",
      "env": { "FLASK_APP": "logo_app.webapp.py", "FLASK_ENV": "development" },
      "args": ["run", "--no-debugger"],
      "jinja": true
    },
```

**Comment by luabud** [comment]
@isidorn it was my bad for forgetting that and not noticing the label 🤦‍♀️ sorry about that! 
but I can verify it now 🥳🥳🥳

![image](https://user-images.githubusercontent.com/45497113/121717376-f38d6580-ca95-11eb-97cb-2958c7f8dfe0.png)

**Comment by isidorn** [comment]
Great, thanks for letting us know, adding verified label
