### ISSUE TITLE
Can not Open file in Vs code (Stuck on main page)

### ISSUE THREAD

**Issue by Ayush-Chugh-2006** [microsoft/vscode#125288]
Does this issue occur when all extensions are disabled?: Yes/No - YES

- VS Code Version: 1.56
- OS Version: Ubuntu 20.10

I was using vs code stable version but then I shifted to insiders which is working fine.
after few days I reopened my stable version but it was having bug that it's not opening any files 

This is a screenshot of the problem
![Vs code issue](https://user-images.githubusercontent.com/69336518/120497243-ddb7da80-c3db-11eb-9c8a-5fa7eefb674f.png)

When I double click or single click any file it's not opening. Page is stuck here
I tried reinstalling vs code but the problem is still there

Recording of issue
![recording](https://user-images.githubusercontent.com/69336518/120594509-a9393280-c45e-11eb-84ca-8205cd325df1.gif)

Some Errors in Console
1) 
![Screenshot from 2021-06-03 15-17-00](https://user-images.githubusercontent.com/69336518/120625457-5754d480-c47f-11eb-9eed-9f252566597f.png)

2) 
![err1 vscode](https://user-images.githubusercontent.com/69336518/120625482-5cb21f00-c47f-11eb-86fc-4dc85b96fb25.png)

The output of code --verbose command

[main 2021-06-03T09:53:36.190Z] Starting VS Code
[main 2021-06-03T09:53:36.192Z] from: /usr/share/code/resources/app
[main 2021-06-03T09:53:36.193Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '71b64f34-2951-4c97-8872-4b206b6d4576',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/ayush/.config/Code/logs/20210603T152336'
}

**Comment by Ayush-Chugh-2006** [comment]
> /gifPlease

![recording](https://user-images.githubusercontent.com/69336518/120594569-c3731080-c45e-11eb-8477-a68df73bf74a.gif)

**Comment by Ayush-Chugh-2006** [comment]
You can check that i have updated in git hub

**Comment by bpasero** [comment]
Yeah looks weird, I assume you ruled out that double click also doesn't work?

Is there anything in the console as error message. 
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Ayush-Chugh-2006** [comment]
> Yeah looks weird, I assume you ruled out that double click also doesn't work?
> 
> Is there anything in the console as error message.
> 
> * run `code --verbose` from the command line and attach the output
> * in Code select **Help | Toggle Developer Tools** and select the **Console**
> * attach any output you see in the **Console** you can find
> 
> Thanks!

These are some errors in console
1) ![Screenshot from 2021-06-03 15-17-00](https://user-images.githubusercontent.com/69336518/120625040-ec0b0280-c47e-11eb-8fb4-058b97ea3f9c.png)

2) 
![err1 vscode](https://user-images.githubusercontent.com/69336518/120625110-ffb66900-c47e-11eb-9fd6-404008119065.png)

**Comment by Ayush-Chugh-2006** [comment]
No, it doesn't. I have updated issue comment with some error images please
check them

**Comment by bpasero** [comment]
Looks like an editor override issue, @lramos15

**Comment by Ayush-Chugh-2006** [comment]
How can i solve it

**Comment by lramos15** [comment]
This happens when you sync insiders into stable and we have changed a setting. We make no guarantee of the sync compatibility between the two versions. You will need to remove the `workbench.editorAssociations` setting from your settings.json

**Comment by Ayush-Chugh-2006** [comment]
This Worked Thanks

And is there any way to stop syncing between insiders and stable release
