### ISSUE TITLE
Integrated terminal deletes scrollback when it encounters a clear

### ISSUE THREAD

**Issue by pjlsergeant** [microsoft/vscode#125254]
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (2 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

Run: 
```
perl -e 'for ( 1 .. 100 ) { print "$_\n" }; print `clear`'
```

in the integrated terminal. Scroll up. Numbers will have been removed (on my machine, they start at 75). In a most shells, you'll get all the numbers. This is a problem when using libraries and tooling that tries to pretty-print its output.

**Comment by paulcarroty** [comment]
Can reproduce on Linux - 88 is the last number; same VSC version.
