### ISSUE TITLE
Test: Picker to switch between opened windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12522]
Test for #11671:

- [x] any OS - @egamma 
- [x] any OS - @bgashler1 

Complexity: 1

There is a new command to quickly switch between the opened windows: `Switch Window`

Verify this command works as you would expect with multiple windows or one window.

**Comment by seanmcbreen** [comment]
OK I fell bad - I'm not up on the goal of the feature.

that said - I did read the related issues.  

But it did not work the way I expected it to. In fact I was not sure what it was meant to do. I

In each case I was not sure what would happen and in my scenario nothing actually happened when I switched.

So for now not a pass.

**Comment by bpasero** [comment]
@seanmcbreen maybe drink a coffee with @bgashler1 later today who seemed to manage to test it ;)?

**Comment by seanmcbreen** [comment]
Deal

**Comment by bgashler1** [comment]
@seanmcbreen I just opened the command palette and typed "Switch..." and then you can execute it.  It worked great for me.  I had 3 windows open and could switch to each one easily in the command palette by the name of the current file or folder that was opened in each window.  Works as expected for me.
