### ISSUE TITLE
Test: file associations and auto save automatic configuration

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12527]
Test for #11974:

- [x] Windows - @stevencl 
- [x] OS X - @octref 
- [x] Linux - @Tyriar 

Complexity: 2

With the new configuration editing API, we adopted it in some places in the workbench:
* verify you can toggle auto save from the file menu and this setting is being updated in the global settings file
* verify you can store file associations in settings by bringing up the mode picker and selecting the option to configure the association

**Comment by chrmarti** [comment]
@bpasero @jrieken Does this also cover #8937 and #1396? If not, could you create additional test items? Thanks.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8937 should be covered by a new test plan item that @isidorn should create for filling in node.js debug configuration. 

I would think we should have an explicit testplan item for https://github.com/Microsoft/vscode/issues/1396

**Comment by isidorn** [comment]
There is already a test plan item for creating the node.js debug configuration https://github.com/Microsoft/vscode/issues/12460

**Comment by octref** [comment]
@bpasero 
For `Files with Path`, it seems to be using global path, even if I'm configuring a workspace setting.

I imagine this setting would be useful project wise and relative path to project root makes more sense. Use cases can include `"src/**/*.jsx": "js"`, etc.

**Comment by bpasero** [comment]
@octref please clarify what steps you did, what you did expect and what you saw. it is very hard to understand your issue without that. I am fine opening it as separate issue.

**Comment by octref** [comment]
@bpasero 
Reported in #12805 as it's a setting problem, not automatic configuration problem.

Here is a problem for toggling `files.autosave` though: #12802
