### ISSUE TITLE
Description of notebook.showCellStatusBarAfterExecute setting can include link to notebook.showCellStatusBar setting

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125232]
Testing #125013

Description of notebook.showCellStatusBarAfterExecute setting can include link to notebook.showCellStatusBar setting. See example below

![image](https://user-images.githubusercontent.com/10746682/120441868-517ac880-c385-11eb-883a-42f9234a1c1c.png)

![image](https://user-images.githubusercontent.com/10746682/120441918-5f304e00-c385-11eb-8f3f-682d28228771.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/125173
