### ISSUE TITLE
No code complete for jsconfig.json files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1252]
Title says it all :-)

**Comment by dbaeumer** [comment]
Works for tsconfig. User error.

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/11780538/e8e8a6c8-a262-11e5-9787-a64590f66d1a.png)

**Comment by aeschli** [comment]
duplicate of #1246
