### ISSUE TITLE
资源管理器侧边栏的克隆存储库按钮未显示

### ISSUE THREAD

**Issue by Merlin-Wilde** [microsoft/vscode#125220]
Issue Type: <b>Bug</b>

启用Git后在简体中文语言下，左侧  [ 资源管理器侧边栏->无打开的文件夹 ]  下，第二个按钮未能显示出来，在法语，英语下则可以显示。

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 4.19.0-16-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3587)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|23.44GB (19.59GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id bb995318-8a2a-4db4-a6f6-626e0a6ed236 --crash-reporter-id bb995318-8a2a-4db4-a6f6-626e0a6ed236 --crash-reporter-id bb995318-8a2a-4db4-a6f6-626e0a6ed236 --crash-reporter-id bb995318-8a2a-4db4-a6f6-626e0a6ed236|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
code-runner|for|0.11.4
vscode-pull-request-github|Git|0.26.0
vscode-drawio|hed|1.4.0
better-cpp-syntax|jef|1.15.5
vscode-language-pack-fr|MS-|1.56.2
vscode-language-pack-zh-hans|MS-|1.56.2
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4360
vsliveshare-audio|ms-|0.1.91
vshaxe|nad|2.23.2
cmake|twx|0.0.17
vim|vsc|1.20.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30307505
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by Guyutongxue** [comment]
Duplication of #120557.
