### ISSUE TITLE
Show list of builtin extensions in the sidebar

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12524]
Builtin extensions don't show up in the sidebar by default unless you search for them - which is good, because it should only show user-installed extensions at first. But it might be useful to browse a list of the builtin extensions, for discoverability, and to emphasize that vscode is an extensible editor that happens to ship with a set of extensions enabled by default. Only a couple will show up at the moment but I understand we plan to move the rest of our extensions to this  model where they live in the marketplace.

**Comment by roblourens** [comment]
And I didn't finish my thought - I'm suggesting another option under the '...' dropdown, "Show built-in Extensions", next to "Show Recommended Extensions" etc

**Comment by waldyrious** [comment]
@joaomoreno can this now be closed given [February 2018 (version 1.21) § Manage built-in extensions](https://code.visualstudio.com/updates/v1_21#_manage-builtin-extensions)?

Btw, I couldn't find a issue / PR covering specifically the *display* of built-in extensions, among the ones listed in the [Feb 2018 milestone](https://github.com/Microsoft/vscode/milestone/59?closed=1), but #44626 seems to be the relevant umbrella issue. (Please correct me if I'm wrong.)

**Comment by roblourens** [comment]
Yes, this is now a duplicate, thanks.
