### ISSUE TITLE
Consider having provideInlineCompletionItems return an array

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125264]
Testing #124979

The existing `CompletionItemProvider` API has `provideCompletionItems`, which returns `ProviderResult<T[] | CompletionList<T>>`.

The new `InlineCompletionItemProvider`, API has `provideInlineCompletionItems`, which returns ` ProviderResult<InlineCompletionList<T>>`. To better match the existing API, the `Inline` version could return `ProviderResult<T[], InlineCompletionList<T>>`

**Comment by hediet** [comment]
That's a good idea! I've opened a PR for this, feel free to have a look if you like.
