### ISSUE TITLE
Notebook renderer inline docs should explain why I would care about additional properties in RendererApi

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125255]
Testing #124995

I am a bit of a notebooks noob, so I have no idea why I would ever care about the additional properties that I can set in `RendererApi`. A short sentence giving an example for why I would want others to consume these properties would help.

```ts
    /**
     * Additional properties may be returned for others to consume in
     * {@link RendererContext.getRenderer}.
     */
    [key: string]: unknown;
```

**Comment by mjbvz** [comment]
Fixed by DefinitelyTyped/DefinitelyTyped#53589

**Comment by alexr00** [comment]
Looks like something is missing. There's a "For example," that doesn't have a following example. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e816fb5bc134b509c00e15429156f34ca2bc6cbd/types/vscode-notebook-renderer/index.d.ts#L127-L134

**Comment by mjbvz** [comment]
Remove extra words with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53625
