### ISSUE TITLE
Create setting to disable terminal hovers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125282]
Forking off the setting part off from https://github.com/microsoft/vscode/issues/113913

PR: https://github.com/microsoft/vscode/pull/124926

**Comment by yash112-lang** [comment]
Hello, @Tyriar is this issue is still open.  I am new to open source and wanted to contribute.

**Comment by Tyriar** [comment]
@yash112-lang there's a PR open already for this one https://github.com/microsoft/vscode/pull/124926
