### ISSUE TITLE
locate file:$line:$col in IntegratedTerminal

### ISSUE THREAD

**Issue by boltyu** [microsoft/vscode#125260]
Issue Type: <b>Bug</b>

![rp](https://user-images.githubusercontent.com/10321820/120467331-a98bec00-c3d2-11eb-8730-b3f60d46a08e.png)
by ctrl+leftclick to open a file in Terminal, 
a path like xx/xxx/xx/xx.c could be open
and xx.c:13:3 could be open because recently opened, and auto jump to line/col
but a path with line/col number like xx/xxx/xx/xx.c:13:3 can't be open

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (11.07GB free)|
|Process Argv|--crash-reporter-id 294b004d-0584-4bbe-931c-088a29372ec5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (2 x 2808)|
|Memory (System)|3.84GB (3.27GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vim|vsc|1.20.3
githistory|don|0.6.16
cpptools|ms-|1.4.0
hexeditor|ms-|1.6.0

</details>

**Comment by Tyriar** [comment]
Links of that form work, your issue is because you have the `codec` folder opened and files are only resolved relative to the root folder. So it would work fine if you opened the parent folder of `codec`. I guess we could special case this to remove the first path segment if it matches the opened folder (ie. the initial cwd of the terminal).

**Comment by Tyriar** [comment]
Code pointer: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts

**Comment by mghalayini** [comment]
@Tyriar I suppose I can work on this. From what I understand, all I have to do is check if the prefix of the search query matches the root folder directory. If it does, we erase that first part and resume the code as usual, right?

**Comment by Tyriar** [comment]
@mghalayini pretty much yep, make sure it's a folder (link contains /, or \ on windows) and a test would be good too which should be fairly easy to write in the existing test file.

**Comment by mghalayini** [comment]
@Tyriar I checked the code pointer that you sent above, but it doesn't seem like it points to the right place (this is my first time navigating the VS Code repository so there's a good chance that I'm wrong). I did some research and ended up in "anythingQuickAccess.ts", specifically `getFileSearchResults`. I added one line that logs a message to the console whenever the user enters a new character in the quick open search bar (the one you get by doing Ctrl+P), and it worked. Is that where I am supposed to be working?

**Comment by mghalayini** [comment]
@Tyriar I checked the code pointer that you sent above, but it doesn't seem like it points to the right place (this is my first time navigating the VS Code repository so there's a good chance that I'm wrong). I did some research and ended up in "anythingQuickAccess.ts", specifically `getFileSearchResults`. I added one line (just to make sure I'm in the right place) that logs a message to the console whenever the user enters a new character in Quick Open, and it worked. Isn't that where I should be working? How is the terminal related to this issue?

**Comment by Tyriar** [comment]
@mghalayini we wouldn't want to change the quick access code but what the terminal sends to it:

https://github.com/microsoft/vscode/blob/c5bbe0a35eae2d294c041076a65c8ea127d90245/src/vs/workbench/contrib/terminal/browser/links/terminalWordLinkProvider.ts#L149

**Comment by mghalayini** [comment]
Thanks @Tyriar! I just wrote the code for it and it looks like it's working. I'm gonna have to do some extra stuff before submitting the PR (adding a test, linting, etc.)
