### ISSUE TITLE
Consider better show the test result when the result belongs to other files instead of current one

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125224]
In Java, we have suite test cases, which looks like this:

```java
@RunWith(Suite.class)
@SuiteClasses({TestAnnotation.class})
public class RunWithAnnotation {

}
```

You can see that, this is just an empty class, but it uses annotation `@SuiteClasses` to declare the classes contained in this suite.

Currently, after triggering this test in the editor, users cannot see any obvious signals about the final results. Only if go to the test explorer can see that. See below video:

https://user-images.githubusercontent.com/6193897/120438448-f6ac9580-c3b3-11eb-9fc2-f2bff34c6e41.mp4

Maybe we can at least automatically toggle out the first failed test message?

> Meanwhile, you can see another issue in this video, when the test explorer is expanded at the first time, the state of `TestAnnocation` is `Unset`, but when user clicks on it, the right state is set to it.

_// cc @connor4312_

**Comment by connor4312** [comment]
Can you share your code or a vsix for this so I can see what's happening?

**Comment by jdneo** [comment]
Ok will share code and reproduce steps a few days later. (maybe early next week, I am OOF for the following days this week)

**Comment by jdneo** [comment]
I made some changes to the implementation, so it's now a little different from the previous statement. Now the main problem is that, when the user trigger the `@SuiteClasses` tests from editor, how to let users know the final result. Below are the steps to better understand the problem

### Setup the Java environment
1. Install [Java extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)
2. Install [vscode-java-test-1.0.0-alpha.3.vsix.zip](https://github.com/microsoft/vscode/files/6607615/vscode-java-test-1.0.0-alpha.3.vsix.zip)
3. Trigger `Java: Configure Java Runtime`, and install Java 11 (Optional if you already have JDK runtime on you machine)

### Run Tests
1. The repo containing test code is here: https://github.com/jdneo/suite-test, where the file to test is: https://github.com/jdneo/suite-test/blob/main/src/test/java/com/example/RunWithAnnotation.java. And the actual test cases of this suite class is: https://github.com/jdneo/suite-test/blob/main/src/test/java/com/example/TestAnnotation.java
2. After cloning the repo, open it `code-insiders.cmd . --enable-proposed-api`
3. Try to run tests in `RunWithAnnotation.java` from editor and from test explorer

**Comment by connor4312** [comment]
Thanks for the details and repro steps! I found your fork of the extension and pulled it down to test with. For me, on the latest Insiders and commit on the `cs/new-test-api-investigation` branch, it looks like it works: https://memes.peet.io/img/21-06-b2c1c172-bfee-4b31-93a7-a1b8deb51798.mp4

Are you still running into this issue?

**Comment by jdneo** [comment]
Thank you @connor4312,

It's more like a UX issue now I guess. As you can see, if user runs the tests from the **editor**, he can see the final result but cannot quickly see the details, unless he navigates to the contained test class of this suite class. Things will be much worse if multiple classes are contained by the suite class.

Do you have any suggestion on this?

**Comment by connor4312** [comment]
Ah, I see. In this case the test that failed is located in a different file, but is a child of a test in _this_ file. Today we only show peek messages if the test that failed is in an open editor, though this is configurable via the `testing.automaticallyOpenPeekView` setting.

I'll change this to instead be if any test or its parent is open. This feels like it's probably sufficient for this edge case.

**Comment by jdneo** [comment]
Thank you @connor4312
