### ISSUE TITLE
NotebookEditor#selection should be writable

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125275]
We have `NotebookEditor#selections` but it is defined as `readonly`. This means extension don't have the ability to set the selection of notebook editors...

**Comment by jrieken** [comment]
@rebornix I have added the skeleton and mechanics for this but I actually don't know how to set the selection... There is `editor#getSelections` but no counter part: https://github.com/microsoft/vscode/blob/76fe0c90b04f3bded4c8031c3e34a7244fb0cc48/src/vs/workbench/api/browser/mainThreadNotebookEditors.ts#L194

**Comment by rebornix** [comment]
`NotebookEditorWidget.setSelections` was added quite a while but I forgot to update this one.
