### ISSUE TITLE
%node2.label%

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#12526]
- VSCode Version: Code - Insiders 1.6.0-insider (d81ee41c51cae93a5cac967e42a28660a3a7e005, 2016-09-23T06:05:08.016Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Start with no debug config
2. Press F5

![image](https://cloud.githubusercontent.com/assets/1723815/18788710/eef8ef12-8175-11e6-97a5-d2b58edb2ede.png)

**Comment by chrmarti** [comment]
@isidorn Is this ours? I see it in my install too.

**Comment by isidorn** [comment]
@roblourens I think the translation is missing for your node 2 adapter

**Comment by roblourens** [comment]
This should be fixed in today's Insider build -

![image](https://cloud.githubusercontent.com/assets/323878/18841193/c4ec6bac-83c5-11e6-9f3a-07316e3d4758.png)
