### ISSUE TITLE
packaging macos installer

### ISSUE THREAD

**Issue by yinhunfeixue** [microsoft/vscode#125215]
after run 
`yarn gulp vscode-darwin-x64` 

Only JS files are packaged,  How can I packaging  .app or.dmg?

**Comment by nrayburn-tech** [comment]
After running `yarn gulp vscode-darwin-x64`, the `.app` file will be inside of a sibling folder to the `vscode` folder.

I don't believe there is any current setup for a `.dmg` or `.pkg`, you would have to do this yourself.  You can use https://github.com/microsoft/vscode/pull/105448 to reference making a `.pkg`, but it is likely to not be a perfect solution and will require you to do some research on your own.


Screenshot of the directories after building.
<img width="410" alt="Screen Shot 2021-06-01 at 10 30 09 PM" src="https://user-images.githubusercontent.com/52075362/120419899-edc2b200-c328-11eb-82b5-81f8614f12b7.png">

**Comment by yinhunfeixue** [comment]
> After running `yarn gulp vscode-darwin-x64`, the `.app` file will be inside of a sibling folder to the `vscode` folder.
> 
> I don't believe there is any current setup for a `.dmg` or `.pkg`, you would have to do this yourself. You can use #105448 to reference making a `.pkg`, but it is likely to not be a perfect solution and will require you to do some research on your own.
> 
> Screenshot of the directories after building.
> <img alt="Screen Shot 2021-06-01 at 10 30 09 PM" width="410" src="https://user-images.githubusercontent.com/52075362/120419899-edc2b200-c328-11eb-82b5-81f8614f12b7.png">

Thank you very much！
Thank you very much！
Thank you very much！

Important things are said three times

I've been looking in the vscode directory
