### ISSUE TITLE
Unlocalised string during setup

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#12529]
I saw this while watching a video of a user installing VS Code. This is on a machine set to Spanish language (but I don't know which locale as I couldn't see the full screen)

Notice that the second last option is not localised

![image](https://cloud.githubusercontent.com/assets/1704059/18789977/ee0e7ade-81a4-11e6-9d52-6a0f87512426.png)

**Comment by dbaeumer** [comment]
@stevencl do you know which version of VSCode he demoed. The only fully localized version we have is 1.5.3. which we shipped last week.

**Comment by stevencl** [comment]
Sorry, all I know is that he installed it on September 9th.


________________________________

**Comment by johnliu2016** [comment]
Also verified from loc side, loc string is in e.g. Spanish, 

/Localize/esn/vscode/build/win32/i18n/messages.en.resx.lcl

      <Item ItemId=";AssociateWithFiles" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Register %1 as an editor for supported file types]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Registrar %1 como editor para tipos de archivo admitidos]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by dbaeumer** [comment]
1.5.3 got released after September 9th. Closing
