### ISSUE TITLE
VS Live Server v2 - Fix external links

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#125200]
External links to non-embeddable webpages are causing the preview to go blank. Fix this to show an error message or some warning in the preview.

**Comment by andreamah** [comment]
resolved in https://github.com/andreamah/VS-Code-LiveServer-V2-Extension/pull/7

**Comment by andreamah** [comment]
For verifier: 
- Preview an html file containing a link to an external site (ie: google). 
- Open it in the embedded preview and try clicking the link. You should be prompted a modal window asking to open the page in an external browser
  - The page you were previously on should remain under the window.

**Comment by lramos15** [comment]
Note if you forget the https:// or http:// it seems to get upset.
