### ISSUE TITLE
vscode open source builds can not connect wsl

### ISSUE THREAD

**Issue by iiaauu** [microsoft/vscode#125225]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56
- OS Version: windows 10 x64

**Comment by aeschli** [comment]
Do you you mean you can not use the WSL-Remote extension from an OS build? 
That's correct, WSL-Remote extension and it's component (e.g. the VSCode server) are not open source. See here: https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source

Please reopen if I misunderstood.

**Comment by zhaoyin88** [comment]
> Do you you mean you can not use the WSL-Remote extension from an OS build?
> That's correct, WSL-Remote extension and its components (in particular the VSCode server) are not open source. See here: https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source
> 
> Please reopen if I misunderstood.

I use the open source vscode，the WSL-Remote is not open source,now I put the WSL-Remote to the builded vscode ,the fuction of WSL-Remote can't work
