### ISSUE TITLE
Where is renderer ID used

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125257]
Testing #124995

In the `RendererContext` there is this:

```ts
    /**
     * Gets the return value of an already activated renderer. It returns
     * undefined if the specified renderer is not available or has not been
     * activated yet.
     */
    getRenderer(id: string): RendererApi | undefined;
```

What ID should I be passing in here? Would this be the ID from the package.json of another renderer? If yes, and if this is used for communicating between different renderers, then a short sentence explaining that you can use `getRenderer` to get access to another renderer to get information from it would be helpful.

**Comment by jrieken** [comment]
> es, and if this is used for communicating between different renderers, then a short sentence explaining that you can use

Yeah, that's the gist of it. Renderers can offer API to other renderer

**Comment by mjbvz** [comment]
Yes needs better documentation
