### ISSUE TITLE
Browser integration test failure - Notebook API multiple tabs: two dirty tabs and switching

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125218]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=121261&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=c55167a9-8752-5898-67fa-9d7c918c61b3 on Windows

```
  231 passing (3m)
  44 pending
  1 failing
  1) Notebook API tests
       multiple tabs: two dirty tabs and switching:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by jrieken** [comment]
Very likely fishy test because it relies on commands and not API...

**Comment by rebornix** [comment]
I skipped this test for now, it would be flaky since we are also experimenting getting started dialog, so any test that relies on commands to open notebook editors can fail sometimes.

**Comment by rebornix** [comment]
We got rid of this test already.
