### ISSUE TITLE
Notebook getting started - scroll area for customisation previews is unpleasant

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#125246]
Testing #125014

The image preview for default has too much space at the bottom so that there is a gap before the 'Default' label
![image](https://user-images.githubusercontent.com/172399/120454704-6b6fd780-c394-11eb-889d-a29cd19a89af.png)

Can the renderings be abstracted more so that they become more compact and no scroll bar is needed? For example emphasise the key differences between the options: toolbar/no toolbar, cell focus bar/no focus bar. 

![image](https://user-images.githubusercontent.com/172399/120453688-8beb6200-c393-11eb-8613-9c82b74f5092.png)

**Comment by narukisosu** [comment]
I have the same impression. This height is too lean.

**Comment by JacksonKearl** [comment]
The issue here is that the images themselves have excess content, correct? Or is the rendering introducing more padding?

**Comment by roblourens** [comment]
I think the first part is addressed by changing the images, but I still see a scrollbar when it feels like there is room. This is a split in a window the size of my laptop screen.

![image](https://user-images.githubusercontent.com/323878/120689705-3d080000-c459-11eb-8bd4-2697fb0970f8.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/120696775-cde2d980-c461-11eb-874a-2a0b47a833b0.png)

**Comment by JacksonKearl** [comment]
Well thats weird.
