### ISSUE TITLE
Test: Release notes in the product

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12520]
- [x] any os @dbaeumer 
- [x] any os @Tyriar 

complexity: 2 bananas (out of 5 fruits)

Use the dev tools to control when to show the `New version` message at startup:

![image](https://cloud.githubusercontent.com/assets/22350/18788000/78c3e542-81a5-11e6-8b24-adc9ab848a93.png)

1. Change the `storage://global/releasenotes/lastversion` value to an older version
2. Reload. You should get the popup asking whether you'd like to read the release notes

The release notes now show in-product. Make sure they look OK and display images. If for any reason they fail to load, a browser window should open to the release notes link, just as before.

**Comment by Tyriar** [comment]
@joaomoreno how do I test this in Insiders? I tried setting the version in package.json but it didn't make a difference. See #12792

**Comment by joaomoreno** [comment]
If you set the version in `package.json` to `1.5.0` and get the message, it should work. In **any** error case (no internet, firewall blocking, etc) you'll get redirected to the browser just as before.

**Comment by Tyriar** [comment]
K, got it to work. The problem is 1.6.0 doesn't have notes I assume.
