### ISSUE TITLE
Slow startup performance

### ISSUE THREAD

**Issue by TorbenJ** [microsoft/vscode#125219]
Issue Type: <b>Performance Issue</b>

Happens on every startup, doesn't matter if any files/folders are open or any extensions are enabled. I tried to close any files/folders to get a clean startup, I also tried to disable all extensions including the default ones not shown in the extensions pane. I tried to clear all recently opened files because maybe there are some checks going on that slow down startup performance. I also tried to install the latest insider build, repeated all steps above and looked at the startup performance.

Anything I mentioned didn't improve the situation. Unfortunately my colleagues don't have these issues and I only got these on my machine at work, VSCode starts quite fast on my private machine.

Reinstalling VSCode didn't help either.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.41GB free)|
|Process Argv|--crash-reporter-id b8757a72-3773-4ae2-a31e-94510c8b3c09|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   102	 20340	code main
    0	    75	  2384	   window (Issue Reporter)
    0	    84	 21204	   shared-process
    0	    62	 24880	     ptyHost
    0	    57	 22428	   crashpad-handler
    0	   157	 27100	   window (Startup Performance - Visual Studio Code)
    0	   100	  7848	     extensionHost
    0	   185	 28060	   gpu-process
    0	    61	 29044	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

<details>
<summary>Startup performance output</summary>

## System Info

* Code - Insiders: 1.57.0-insider (1e446dfadf588ec28b3fdba7ac083bfa1d45df3c)
* OS: win32(10.0.19042)
* CPUs: Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz(20 x 2808)
* Memory(System): 31.79 GB(15.37GB free)
* Memory(Process): 162.87 MB working set(122.44MB private, 0.10MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 909      | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 1        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 45       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 866      | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 1        | [main]                    | initial startup: true                                       |
| create window                                                   | 38       | [main]                    | initial startup: true, state: 0ms, widget: 11ms, show: 27ms |
| app.isReady => window.loadUrl()                                 | 119      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 2568     | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 205      | [renderer]                | cached data: YES, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 14       | [renderer]                | -                                                           |
| init workspace service                                          | 12       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 1785     | [renderer]                | -                                                           |
| restore viewlet                                                 | 10       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 22       | [renderer]                | 1: workbench.runtimeExtensions.input                        |
| overall workbench load                                          | 135      | [renderer]                | -                                                           |
| workbench ready                                                 | 3953     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 361      | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 5775     | [renderer]                | -                                                           |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1622623839057	0	0
code/didStartMain	1622623839112	55	55
code/willStartCrashReporter	1622623839123	11	66
code/didStartCrashReporter	1622623839989	866	932
code/mainAppReady	1622623840021	32	964
code/willGenerateNls	1622623840023	2	966
code/didGenerateNls	1622623840024	1	967
code/willLoadMainBundle	1622623840025	1	968
code/fork/willLoadCode	1622623840035	10	978
code/registerFilesystem/file	1622623840068	33	1011
code/didLoadMainBundle	1622623840070	2	1013
code/willStartMainServer	1622623840074	4	1017
code/didStartMainServer	1622623840075	1	1018
code/willCreateCodeWindow	1622623840098	23	1041
code/willRestoreCodeWindowState	1622623840098	0	1041
code/didRestoreCodeWindowState	1622623840098	0	1041
code/willCreateCodeBrowserWindow	1622623840098	0	1041
code/didCreateCodeBrowserWindow	1622623840109	11	1052
code/willMaximizeCodeWindow	1622623840109	0	1052
code/didMaximizeCodeWindow	1622623840136	27	1079
code/didCreateCodeWindow	1622623840136	0	1079
code/willOpenNewWindow	1622623840140	4	1083
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1622623840140	0	0
code/didStartRenderer	1622623842704	2564	2564
code/willWaitForWindowConfig	1622623842704	0	2564
code/didWaitForWindowConfig	1622623842704	0	2564
code/willShowPartsSplash	1622623842704	0	2564
code/didShowPartsSplash	1622623842704	0	2564
code/willLoadWorkbenchMain	1622623842708	4	2568
code/didLoadWorkbenchMain	1622623842913	205	2773
code/registerFilesystem/file	1622623842914	1	2774
code/registerFilesystem/vscode-userdata	1622623842914	0	2774
code/willInitWorkspaceService	1622623842915	1	2775
code/willInitStorage	1622623842915	0	2775
code/didInitWorkspaceService	1622623842927	12	2787
code/didInitStorage	1622623842929	2	2789
code/willStartWorkbench	1622623842930	1	2790
code/LifecyclePhase/Ready	1622623842931	1	2791
code/registerFilesystem/trustedDomains	1622623842959	28	2819
code/willRestoreEditors	1622623843042	83	2902
code/willRestoreViewlet	1622623843044	2	2904
code/didRestoreViewlet	1622623843054	10	2914
code/didRestoreEditors	1622623843064	10	2924
code/LifecyclePhase/Restored	1622623843064	0	2924
code/didStartWorkbench	1622623843065	1	2925
code/didRemovePartsSplash	1622623843065	0	2925
code/willConnectSharedProcess	1622623843073	8	2933
code/willLoadExtensions	1622623843102	29	2962
code/willHandleExtensionPoints	1622623844843	1741	4703
code/didHandleExtensionPoints	1622623844885	42	4745
code/didLoadExtensions	1622623844887	2	4747
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1622623844804	0	0
code/fork/start	1622623844867	63	63
code/fork/willLoadCode	1622623844881	14	77
code/extHost/willConnectToRenderer	1622623845039	158	235
code/extHost/didConnectToRenderer	1622623845040	1	236
code/extHost/didWaitForInitData	1622623845052	12	248
code/extHost/didCreateServices	1622623845056	4	252
code/extHost/willWaitForConfig	1622623845058	2	254
code/extHost/didWaitForConfig	1622623845066	8	262
code/extHost/didInitAPI	1622623845066	0	262
code/extHost/didInitProxyResolver	1622623845067	1	263
code/extHost/ready	1622623845067	0	263
```

### cached data used

* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\clone-6d04ced460624ab4df85968640d77938.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\graceful-fs-1448cdd0835121eaddbbf150b4bb8df5.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\legacy-streams-56ce215ac9814eacb75f9def87ede288.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\main-9f4b3ff8270cc00641c2e320bf75440f.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\main-c44319fb7316c926d3b118adfa9d7552.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\polyfills-1df2b465e1a09cde25fc8de631e84aa4.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\tas-client-umd-716cfdba16e1d45246aeb021406e7812.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\workbench.desktop.main-38f8588718240aca4236b9ff609ffe28.code
* C:\Users\tjonas\AppData\Roaming\Code - Insiders\CachedData\1e446dfadf588ec28b3fdba7ac083bfa1d45df3c\workbench.desktop.main.nls-2512f8d3bb799bcf283bd86064333bc6.code

### cached data created (lazy, might need refreshes)
</details>

[prof-fec8.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6583355/prof-fec8.extHost.cpuprofile.txt)
[prof-fec8.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6583356/prof-fec8.main.cpuprofile.txt)
[prof-fec8.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6583357/prof-fec8.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by jrieken** [comment]
Seems like it takes a long time spawn some processes...

<img width="430" alt="Screen Shot 2021-06-02 at 11 25 21" src="https://user-images.githubusercontent.com/1794099/120455632-39ab4080-c395-11eb-9498-9d0776fbc66e.png">

<img width="509" alt="Screen Shot 2021-06-02 at 11 25 18" src="https://user-images.githubusercontent.com/1794099/120455659-3e6ff480-c395-11eb-9afd-6e1eb393d975.png">

**Comment by TorbenJ** [comment]
> This is sometimes caused by AV software - can you try to exempt VS Code from your AV software and retry?

I checked this with my colleagues and this seems to indeed be the reason.  
I was able to install VSCode to a whitelisted directory and this solved the issue.

Thanks for your help :)
