### ISSUE TITLE
some commands are not working

### ISSUE THREAD

**Issue by rushikesh01499** [microsoft/vscode#125216]
Issue Type: <b>Feature Request</b>

some commands are not working such as display flex,etc plese resolve it

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

**Comment by rushikesh01499** [comment]
i am using vs code.some commands like display flex and many other commands are not working.what to do?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post detailed steps to reproduce the issue. Paste screenshots if you want.

**Comment by sandy081** [comment]
@rushikesh01499 Your reply does not contain any info - please provide the necessary required info. Thanks.
