### ISSUE TITLE
Part of the activity bar is not displayed

### ISSUE THREAD

**Issue by Butachaan** [microsoft/vscode#125258]
Issue Type: <b>Bug</b>

I don't see the source control bar.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2660)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.99GB (6.57GB free)|
|Process Argv|--crash-reporter-id 7f432869-5256-40f6-bc53-b959705c2029|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
tellraw-preview|act|0.2.1
vscode-sqlite|ale|0.12.0
language-mcfunction|arc|0.17.0
vscode-intelephense-client|bme|1.7.1
githistory|don|0.6.16
vscode-phpmd|eco|1.3.0
php-debug|fel|1.15.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-pull-request-github|Git|0.26.0
discord-vscode|icr|5.6.3
phpcs|ika|1.0.5
php-cs-fixer|jun|0.1.158
vscode-github|Kni|0.30.6
vscode-language-pack-ja|MS-|1.56.2
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
datapack-json|SPG|2.0.16
datapack-language-server|SPG|3.3.5
local-lua-debugger-vscode|tom|0.2.1
scm-buttons-vscode|tom|0.1.1
minecraft-lang-colorizer|zz5|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see it in list if you right click on Activity Bar?
Do you see it if you run <kbd>F1</kbd> and `> View: Show Source Control`

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
