### ISSUE TITLE
Custom editor diff editor doesn't render until resize event

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125202]
1. Edit image in Luna paint, save.
2. Click on entry in SCM viewlet to see diff
3. Wait
4. Wait some more
5. Grab a drink
6. Wait
7. Try to resize the window
8. The diff editor loads

Haven't tried in other custom editors, don't know if this is an issue with custom editor openers or in Luna.

**Comment by Tyriar** [comment]
Seems like a core issue, also happens with hex editor with:

```
"workbench.editorAssociations": {
  "*.ts": "hexEditor.hexedit"
}
```

**Comment by mjbvz** [comment]
This seems like an important regression. No idea what changed in custom editor land

**Comment by mjbvz** [comment]
This seems to have been caused by 0449a18b7bb1d8b3cf7138df63e03126ba47c21d /cc @joaomoreno

The current `layout` calls causes the webviews to end up with `0` height in this case. Looking to see what that proper fix would be

**Comment by joaomoreno** [comment]
I get the following error with these steps, unfortunately: 
![image](https://user-images.githubusercontent.com/22350/120617723-3eacd600-c40f-11eb-831e-2fe9ae102da2.png)

**Comment by joaomoreno** [comment]
I hit the same exception when following @Tyriar's hex editor alternative steps.

**Comment by bpasero** [comment]
Maybe https://github.com/microsoft/vscode/issues/125290 is the same and has easy steps to reproduce.

**Comment by joaomoreno** [comment]
Thanks @bpasero, the lack of milestone was hiding that issue from me!

**Comment by bpasero** [comment]
@joaomoreno btw the `editorControl` is storing the dimensions and applies them here already:

https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/browser/parts/editor/editorControl.ts#L133-L133

**Comment by lramos15** [comment]
@joaomoreno That exception you see I receive in the official build of insiders, but not when running out of sources. It implies that the resource URI is undefined which shouldn't be possible. If you have any ideas or would like to help me discover what is causing this let me know

**Comment by mjbvz** [comment]
For the hex editor, I had trouble reproducing this until I set `"hexeditor.dataInspector.autoReveal": false`. The data inspector (usually) seems to trigger a relayout for me

My reliable repo:

1. Set `"hexeditor.dataInspector.autoReveal": false,`
2. set `"workbench.editorAssociations": {  "*.ts": "hexEditor.hexedit" }`
3. Change a TS file and open the diff

**Comment by joaomoreno** [comment]
Thanks @mjbvz, I can repro with those steps! I will look into this tomorrow if you don't figure it out today. 👌
