### ISSUE TITLE
[Test API] Parent test should be fail if its child is failed

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125222]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (user setup)
Commit: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c
Date: 2021-06-01T05:13:48.346Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. In project `test-provider-sample`, make changes like this commit: https://github.com/jdneo/vscode-extension-samples/commit/d7c109fa8760f87441c3a7334a22a26c64a22ef1
> The change here will add 2 test items as children to a `TestCase` when running the test, commonly seen for repeated tests or parameterized tests. For the two children, the first one will fail and second one will pass.

#### Expected behavior:
Since one child failed, the result for parent TestCase should be fail

#### Actual behavior:
parent TestCase should is passed.

#### demo:

https://user-images.githubusercontent.com/6193897/120435744-b1d32f80-c3b0-11eb-849a-e49460d72b06.mp4

_//cc @connor4312_

**Comment by connor4312** [comment]
You're setting the state of `this.item` to passed. Did you mean to apply these state changes to the children?

https://github.com/jdneo/vscode-extension-samples/commit/d7c109fa8760f87441c3a7334a22a26c64a22ef1#diff-6d3df1a8a42967b8f381f8442eaa1fb472f2c9db87368bcce3fdc8eec02e1619R332

**Comment by jdneo** [comment]
Sorry for the mistake I made. Yes I should set the state to `child1` and `child2`.

Please check the new commit: https://github.com/jdneo/vscode-extension-samples/commit/569e8157a7f70a7491fa35f88d4695fa758b5f33

In this commit, test states are set correctly to `child1` and `child2`. Meanwhile, they have the same `uri` and `range` as their parent, then the issue can be reproduced.


https://user-images.githubusercontent.com/6193897/120573816-ccf57c00-c450-11eb-86da-905bb59134b6.mp4

Also please notice that when hover the mouse on the green mark, there are three duplicated tips: `Click to run tests,...`

**Comment by connor4312** [comment]
Ah, I see! I've refactored the decorations to support the scenario of multiple tests per line. Results are now shown correctly:

![](https://memes.peet.io/img/21-06-0e04c7d2-977f-4706-b831-4871cbaa942b.png)

 additionally, clicking on the gutter will run on tests on that line, and right clicking allows you to see and run tests individually

![](https://memes.peet.io/img/21-06-9f9b5fb1-3aee-4e39-a297-ab635fa5ca2c.png)
