### ISSUE TITLE
Make cell collapsed state a UI properly

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125274]
We have done some last minute clean-up and removes collapse states from cell metadata. This was an API only change and needs further clean-up. We

* define collapsed state as a view property (not a model property)
* expose the view state via the NotebookEditor API (set/get property and event)

**Comment by tanhakabir** [comment]
Do we still need this? @jrieken

**Comment by jrieken** [comment]
Yes, pretty sure because at the time we made this an API only change, e.g the data is still there and used wrongly. Tho @roblourens will know best.

**Comment by roblourens** [comment]
Not actually sure what we want to do with this, because I think we still might want to support Jupyter's feature of persisting this state to share.

@rebornix should I assume that even if we do that, we definitely don't want to use our metadata for that?
