### ISSUE TITLE
VC doesn't debug python files

### ISSUE THREAD

**Issue by dsgon** [microsoft/vscode#125212]
Hi!

I can't debug python files on my VC, I recently uninstall and re install it, but the issue still present.

My current lauch.json settings is:

```
"version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
```

I don't know what's happening.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform and which Python extension(s) you have installed.

**Comment by dsgon** [comment]
Hi @gjsjohnmurray @weinand , I add the information requested.

Visual Studio Code 
```
Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

Extensions:
Pylance by Microsoft: v2021.6.0
Python by Microsoft: v2021.5.842923320
Jupyther by Microsoft: v2021.6.832593372

All versions all the latest.
