### ISSUE TITLE
Enrich VS Code Extension API doc comments with gifs/screenshots

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125271]
JS documentation comments fully support markdown, including images and gifs. VS Code renders them already nicely.

I think it would be nice to include gifs/screenshots in the extension API doc comments to visually communicate what you can do with that API:

![recording](https://user-images.githubusercontent.com/2931520/120478958-b0ecce80-c3ad-11eb-9745-f6776520b053.gif)

These gifs/screenshots should be hosted statically (e.g. on github pages) and all have the same size. Gifs are cool, but I think I would actually prefer simple screenshots (maybe even with red standardized markers to point to stuff) to reduce noise.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"feature-request"

**Comment by hediet** [comment]
Sorry, I could not find the duplicate either. But #94747 might be related.
