### ISSUE TITLE
Ill-aligned, barely formatted dataframes

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#125299]
## Environment data

-   VS Code version: 1.57.0 insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.892431424
-   Python Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: macOS 11.3.1
-   Python and/or Anaconda version: python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

A dataframe output is reasonably formatted like this (jupyterlab):

![image](https://user-images.githubusercontent.com/2845433/120425039-e8269580-c343-11eb-80ef-bc6655a70ab1.png)
1. Numbers are right aligned.
2. Columns have width according to their contents
3. Font size is like the overall font size of the document
4. Style is like the overall style of the document

## Actual behaviour

![image](https://user-images.githubusercontent.com/2845433/120424963-c5947c80-c343-11eb-98fa-af720d7aa0af.png)

Given that this is intended for scientific/numerical computing, the fact that numbers are left aligned is a deal breaker. Am I doing something wrong? I'm a bit surprised this is so.

Then minor quirks: larger fonts of a different family, background in harsh contrast with the rest of the document, 100% width even with one or two columns. This is like the raw HTML output I get in vanilla nbconvert documents. It needs considerable polish.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

```python
import pandas as pd

pd.DataFrame(dict(x=[1, 10, 100, 1000], y=[2, 20, 200, 2000], z=[3, 30, 300, 3000]))
```

**Comment by rebornix** [comment]
@misolori I wonder if we should remove our css styles for tables.

**Comment by misolori** [comment]
We could, we'd just need to remove this:

https://github.com/microsoft/vscode/blob/26cd18321bd7ad322177b1af74e42a93b3c72424/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L758-L760

![image](https://user-images.githubusercontent.com/35271042/120555550-1477fb80-c3b0-11eb-9f6a-f8ee07e764e7.png)

but we'd also need to check how this affects table with long tables

**Comment by memeplex** [comment]
This surely looks nicer. A CSS rule for right alignment would be much appreciated also, even if still heuristic it would be right with greater probability in a DS context and it's what jupyter notebooks have been doing forever.

**Comment by misolori** [comment]
For right-aligned we should also check the various table types:

<img width="302" alt="CleanShot 2021-06-02 at 15 17 01@2x" src="https://user-images.githubusercontent.com/35271042/120559278-a0d8ed00-c3b5-11eb-8ec0-0085cfcf3201.png">

<img width="806" alt="CleanShot 2021-06-02 at 15 20 04@2x" src="https://user-images.githubusercontent.com/35271042/120559557-19d84480-c3b6-11eb-820f-3c9fa9acc4e3.png">

**Comment by rebornix** [comment]
since we are here talking about alignment and styles, I wonder if this is an opportunity for renderers.

**Comment by misolori** [comment]
While I think renders can provide a richer experience (sorting, filtering, etc) I think we should have a solid experience out of the box.

**Comment by misolori** [comment]
Assigning to next month where we can have more time to investigate.

**Comment by memeplex** [comment]
Thanks!
