### ISSUE TITLE
Feature Request: Find & Replace Between Line Numbers

### ISSUE THREAD

**Issue by aacitelli** [microsoft/vscode#125356]
I often use the find and replace tool (accessible via Ctrl-F, then hitting the dropdown arrow) to rename a given variable. However, using this tool replaces *every* instance of whatever you search for. This often isn't ideal - for instance, if you are copy pasting a code block and need to rename a certain variable in each of the code blocks, but only in that specific code block, you can't use find and replace on the whole file, as that would replace things you don't want. This leaves you manually replacing variable names in each of them rather than in a single bulk operation. 

I figured this could be addressed by adjusting the "Find and Replace" tool so that you could specify line numbers to act as "bounds" to what gets replaced. I'm not sure the best way to accomplish this from a UI perspective, but I'd think the main way would be to add fields to the Ctrl-F form where you can input line numbers to bound the selection. Maybe if the user already has a certain number of lines highlighted when they hit Ctrl-F it could default to those; that may make it more complicated, though. 

My apologies if this was already suggested somewhere - just figured I'd write it out, as I couldn't find anything from a brief Google.

**Comment by weinand** [comment]
Did you try to use the "find in selection" feature?
Just select the lines of text where the replace should take place and then press the "lines" icon on the Find widget:

![2021-06-03_11-23-02](https://user-images.githubusercontent.com/1898161/120621356-17c9c080-c45e-11eb-95c9-a1aa233257a4.png)

**Comment by aacitelli** [comment]
Yep, this fits my use case perfectly. My apologies for not doing my due diligence - thank you!
