### ISSUE TITLE
Cell toolbar action enablement causes flicker

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125336]
It's hard to see in the recording but you see it at least once. When going back and forth between a rendered markdown cell and a code cell using the arrow keys the update of run actions happens after the cell toolbar is fully rendered on the target cell. This causes a distracting flicker effect.

![HyywYlTfxS](https://user-images.githubusercontent.com/4674940/120549549-99f7ad80-c3a8-11eb-9355-fd6831080145.gif)

**Comment by roblourens** [comment]
Those execute actions should not show on markdown cells at all. I assume they did when they were coming from jupyter though
