### ISSUE TITLE
Ability to configure the acceptance for completions to be something other than tab

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125325]
Testing #124979

In other apps I use, Right Arrow is the way you accept Inline Completions: Outlook, shells like PowerShell, zsh, fish, etc. Ideally the way you accept inline completions should be configurable.

**Comment by hediet** [comment]
You can define your own shortcut!

```json
{ "key": "tab",                   "command": "commitInlineCompletion",
                                     "when": "inlineCompletionsVisible  && !inlineCompletionSuggestsIndentation" },
```
