### ISSUE TITLE
Notebook getting started selection boxes are hard understand

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125346]
Testing #125014

As mentioned in other issues, I think it is a bit hard to understand what you are actually supposed to do in this UI (especially when its stacked -- which is probably likely in this split scenario. But beyond that, The units don't looks selectable, and I feel like the labeling is off too

![image](https://user-images.githubusercontent.com/641685/120562659-d3461280-c3d4-11eb-982f-cfa12f0018d2.png)

Like in this image -- is the selection Jutyter or Colab. I think the label should be on top and maybe also be called `<name Layout` or `<name> Style` or something to help you understand what you are looking at.

**Comment by roblourens** [comment]
We got rid of the empty space which helps. I also like the label suggestions.

**Comment by tanhakabir** [comment]
Closing this issue since I believe we've decided against having a layout selection like this with these difficult to distinguish images
