### ISSUE TITLE
LSP - VSCode doesn't treat MarkupKind.PlainText as plain text

### ISSUE THREAD

**Issue by pedro-w** [microsoft/vscode#125323]
Issue Type: <b>Bug</b>

I'm writing an extension using LSP. In response to a hover request I am returning a MarkupContent with a `kind` of `'plaintext'`. VSCode is not displaying what it interprets as HTML tags, i.e. words between angle brackets. For example the response
```
[Trace - 7:37:56 PM] Received response 'textDocument/hover - (6)' in 8ms.
Result: {
    "contents": {
        "kind": "plaintext",
        "value": "main :: <string>"
    }
}
```
is displayed as "main :: " instead of "main :: \<string\>".

In the spec it says that "clients might sanitize the return markdown. A client could decide to remove HTML from the markdown to avoid script execution." but I understand this to apply to markdown only, plain text should not be sanitized in this way. An alternative explanation is that the UI is treating text as HTML and  the 'tags' are not visible as per normal HTML rules.

Expected behavior: plain text is rendered as-is in the UI
Actual behavior: plain text is displayed with (potential) HTML tags missing

Further to this, emacs-lsp _does_ display plain text as plain text, making it more complicated to work around this (e.g. by converting \< to \&lt; in the extension, before returning it.)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (2.78GB free)|
|Process Argv|--crash-reporter-id e850835a-7eaa-4a29-b661-4b517d57784d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
calva|bet|2.0.198
clj-kondo|bor|2021.6.1
vscode-eslint|dba|2.1.20
vscode-dylan|dyl|0.2.0
html-preview-vscode|geo|0.2.5
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
vscode-standard|sta|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
vshan820:30294714
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by pedro-w** [comment]
Example screen shot:
![Screenshot 2021-06-02 at 20 01 47](https://user-images.githubusercontent.com/22172519/120537647-6f741780-c3dd-11eb-83a0-30bd2b7b2b7a.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-languageserver-node/issues/768
