### ISSUE TITLE
python扩展安装不上

### ISSUE THREAD

**Issue by fengwuxie7** [Microsoft/vscode#12530]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by fengwuxie7** [comment]
一直显示正在安装

**Comment by vilic** [comment]
1. 请用英语. Please write in English.
2. 这种问题建议到 segmentfault.com/stackoverflow.com 询问 (多半是网络太慢原因). 除非你认为是一个 bug, 但请提供更详细的信息. 比如控制台是否有错误输出, 网络环境, 具体重现步骤等. Questions like this are expected to be asked via segmentfault.com/stackoverflow.com (as it would probably be a result of slow connection). If you think this is a bug, please provide detailed information. E.g., whether there is any error log in the developer console, your network environment, reproducing steps and so on.

**Comment by chrmarti** [comment]
Are you behind a firewall? Have you configured any of the proxy settings?

**Comment by fengwuxie7** [comment]
Thank you, I have done

**Comment by Emeryao** [comment]
@vilic :+1: 
@fengwuxie7 提issue真的请用英文 Do use English when opening an issue PLEASE

**Comment by chrmarti** [comment]
@fengwuxie7 Please clarify: Did adding proxy settings fix the issue?

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
