### ISSUE TITLE
Show list of useful commands in watermark

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12534]

**Comment by odytrice** [comment]
I noticed that the watermark doesn't show up even after the update. Any Idea why?

**Comment by odytrice** [comment]
I needed to delete the Code folder in `C:\Users\[User]\AppData\Local\Roaming\Code`

**Comment by chrmarti** [comment]
@odytrice We run it as an 'experiment', showing it only with half of all installations. Deleting that folder made it roll the dice again.

**Comment by odytrice** [comment]
Hmm.. I see. Really Love it BTW
