### ISSUE TITLE
Definitions for keyworks

### ISSUE THREAD

**Issue by herbievine** [microsoft/vscode#125370]
This feature would be focusing on easing the learning curb of programming by adding definitions to keywords, similar to how you get definitions on variables. As an example, say you're programming in TypeScript, you can hover over the `interface` keyword and get info on how to use it, when or when not to use it, when to use `type` instead, and a link to the documentation. I don't think this should be incredibly hard to implement and would help new or even intermediate/advanced developers to thoroughly understand what these keywords mean.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
