### ISSUE TITLE
Workspace Trust Editor loads slowly and changes state during loading

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#125319]
Reloading workspace editor on a trusted project, 50% slower:

https://user-images.githubusercontent.com/8599/120531936-04522300-c394-11eb-8aa8-db6296202629.mp4

Main issues in the recording, apart from the slow loading:

1. Loads in restricted mode for a long time, then suddenly toggled to trusted
2. Main trust/restricted panels take long to load and cause significant layout shift; even though they only contain few dynamic elements

**Comment by sbatten** [comment]
I think to smooth this out without much change, for now, we just will wait to render until workspace is fully initialized (this is how the workbench indicators operate)

**Comment by digitarald** [comment]
As the UI layout itself is mostly predictable in a rough shape, maybe using css grid could allow building a skeleton loading indicator; so the page doesn't stay blank for multiple seconds.

**Comment by sbatten** [comment]
until the workspace trust state is resolved, nothing except the list of entries at the bottom is truly correct. while I agree we can do more polish on this, I don't think its worth doing this week.
