### ISSUE TITLE
Unable to launch Terminal

### ISSUE THREAD

**Issue by ManiKBSM** [microsoft/vscode#125396]
Issue Type: <b>Bug</b>

Unable to launch terminal
Select 'New Terminal' option from terminal menu and it fails with error code 1920

"The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 1920)"

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.53GB free)|
|Process Argv|. --crash-reporter-id 0159d655-b5ec-4310-84c2-701494ddb3a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.26.0
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30307505
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by gs271** [comment]
Hi,
I am unable to launch the terminal since morning.
it doesn't open up every time I open it get below error.

![image](https://user-images.githubusercontent.com/84413640/121010179-b7ff4c80-c7b2-11eb-9351-1559d3b638a5.png)
![image](https://user-images.githubusercontent.com/84413640/121010219-c188b480-c7b2-11eb-87f6-5841d897bf40.png)

**Comment by meganrogge** [comment]
Does this issue happen with all extensions disabled (run extension bisect)?

**Comment by meganrogge** [comment]
File an issue on that extension's repo to get it fixed so you can then re-enable the extension
