### ISSUE TITLE
Test: Workspace Trust Documentation

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#125353]
- [x] anyOS @JacksonKearl 
- [ ] anyOS @rzhao271

Complexity: 3

---

Please review the workspace trust documentation at https://aka.ms/vscode-workspace-trust

As part of this: review the initial dialog and workspace trust editor wording which points to the docs.
- Open a new folder that is not trusted to see the dialog
- Gear Icon > Manage workspace trust to see the editor

**Comment by JacksonKearl** [comment]
Made a couple small tweaks to the md, but overall looks good.

**Comment by rzhao271** [comment]
Should "See our docs to learn / more." be on its own line in the dialog? The way it currently is with the newline makes it easy to miss.
