### ISSUE TITLE
Markdown inline code not rendering correctly?

### ISSUE THREAD

**Issue by RMeli** [microsoft/vscode#125300]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: macOS 10.15.7
-   Python and/or Anaconda version: Python 3.8.10 | conda 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

I expect `inline code` in Markdown cells to render correctly.
 
## Actual behaviour

`inline code` in Markdown cells renders as standard text.

## Steps to reproduce:

![vscode](https://user-images.githubusercontent.com/11348981/120453884-b1786b80-c393-11eb-8822-1687270efc11.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) ?

Also what color theme are you using?

**Comment by RMeli** [comment]
@mjbvz I'm using the GitHub Dark color theme. 

I don't have VSCode Insiders installed, I will give it a try later today.

If that helps, the UI for Jupyter Notebooks changed to the new UI after I installed [Thinking in Data](https://marketplace.visualstudio.com/items?itemName=dynamicwebpaige.thinking-in-data), which I now realize recommends to use the Insider version.

**Comment by RMeli** [comment]
@mjbvz I can confirm that this happens also with the latest version of VS Code Insiders (Version: 1.57.0-insider (Universal), bf84ee619e0b67443d0307c04348fa575bc3c363)

**Comment by mjbvz** [comment]
Do you see this with other themes, specifically some of the built-in ones like Dark+?

**Comment by RMeli** [comment]
@mjbvz With Dark+ the code is highlighted (in pale yellow/orange), but the font matches the text font (as opposed to the code cells) and the `inline code block` is also missing. Is this a problem with themes?

**Comment by mjbvz** [comment]
Yes, it's up to each theme to provide these color. Please file an issue against the GitHub theme to add a new color for this

I confirmed that there is a bug with the font though not being monospace. Will fix that in our code
