### ISSUE TITLE
GitHub auth `getSessions` throws when adding a folder to an empty workspace

### ISSUE THREAD

**Issue by JoaquindeCastro** [microsoft/vscode#125391]
- Extension version: 1.56.2
- VSCode Version: 0.26.0
- OS: Windows

Steps to Reproduce:

1. Install extension
2. Log in to Github
3.  Add existing Github repository via "Add Folder"
4.  Type `// TODO @`

Notes:
- Hovering over @username in `// TODO @username` also does not show a Github style hover card.
- Typing `@` outside or inside of a comment without `TODO` yield different autocompletion suggestions.
- 'Show fixes' to Create a Github Issue is working.

**Comment by alexr00** [comment]
@TylerLeonhardt I think this is an issue with auth somewhere. Detailed steps:

1. Open an empty vscode window and have GHPRI installed.
2. Sign in for GHPRI if you haven't already.
  2a. At this point, GHPRI has called `getSessions` **successfully:** https://github.com/microsoft/vscode-pull-request-github/blob/239e6c36de35c6938a15a2e82c204ac4f77a3050/src/github/credentials.ts#L72-L73
3. Command -> Workspaces: Add Folder to Workspace and choose a folder that has a GH repo.
  3a. When the folders change, GHPRI calls `getSessions` again with the same parameters.
4. `getSessions` throws:
```
Error: No authentication provider 'github' is currently registered.
    at M.getSessions (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2000:11965)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async m.$getSession (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2001:3041)
```

**Comment by TylerLeonhardt** [comment]
@alexr00 yep and it looks like this part:

> Open an empty vscode window and have GHPRI installed.

doesn't have to be empty. Basically adding _any_ additional folder to the workspace throws this error.

**Comment by TylerLeonhardt** [comment]
I just tried this again and it appears to be working. My guess is that it was a Workspace Trust bug that has been fixed.
