### ISSUE TITLE
Don't allow the Git extension to work in an untrusted workspace

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125350]

**Comment by misolori** [comment]
@eamodio are there any verification steps? I'm able to open a repo and make commit changes while in an utrusted workspace but not sure what's expected.

**Comment by eamodio** [comment]
Sorry this change was reverted, so I'll re-open and push this off.

**Comment by lszomoru** [comment]
The git extension now only works in a trusted workspace. Closing this issue.
