### ISSUE TITLE
Terminal Error 

### ISSUE THREAD

**Issue by iron-coder12** [microsoft/vscode#125383]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I get this error every time I close the terminal

![image](https://user-images.githubusercontent.com/79589166/120640888-a0f9eb00-c490-11eb-8655-4da625ea230b.png)

**Comment by meganrogge** [comment]
Can you turn on trace logging and provide me with the logs? /needs-more-info

**Comment by iron-coder12** [comment]
> Can you turn on trace logging and provide me with the logs? /needs-more-info

How do I turn on trace logging?

**Comment by meganrogge** [comment]
Cmd Shift P -> Developer Set Log level -> Trace -> Open dev tools and copy what's there when you delete a terminal

**Comment by iron-coder12** [comment]
I just hit ctrl + shift + and choose developer set log level then trace and nothing happens

**Comment by meganrogge** [comment]
Then you have to open developer tools and view the console, where there will be output

**Comment by iron-coder12** [comment]
ok lemme give it a shot

**Comment by iron-coder12** [comment]
![image](https://user-images.githubusercontent.com/79589166/120666722-7026af80-c4aa-11eb-9d4a-62e1f61e1f3d.png)
I just did that and got this stuff

**Comment by meganrogge** [comment]
I need a log that says #dispose. Search for that please and if you can't find it, delete a terminal.

**Comment by iron-coder12** [comment]
hmm ok lemme see

**Comment by iron-coder12** [comment]
Hi @meganrogge sorry for the delay. I couldn't find the log you want
![image](https://user-images.githubusercontent.com/79589166/120885038-5305f400-c604-11eb-8f79-3fa795fcdf90.png)

**Comment by meganrogge** [comment]
You have to turn on trace logging (ctrl shift p -> set log level: trace) then delete a terminal
