### ISSUE TITLE
Notebook getting started profiles

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125348]
Testing #125014

Instead of setting a whole set of settings individually, why not introduce a new setting that is a profile, that could evolve more easily. Users can still override specific behavior with individual settings, but the profile will becomes the base. IMO, it would declutter the all the changes made here and allow more flexibility going forward.

**Comment by roblourens** [comment]
This is one possibility for evolving https://github.com/microsoft/vscode/issues/122481

**Comment by roblourens** [comment]
We experimented with this in the past, have moved away from it for now, may revisit at some point in the future though.
