### ISSUE TITLE
VS Code Linux Terminal won't scroll with PowerShell

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#12532]
**System Details**

- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1 LTS Desktop
- PowerShell: v6.0.0-alpha.10

**Issue Description**

Just discover, when executing PowerShell with Integrated Terminal, it won't scroll Up/Down.  When it's using BASH is working fine.

**Steps to Reproduce:**

1. Go to Integrated Terminal (ctrl-`)
2. in Bash, type powershell
3. run dir multiple times
4. Try to scroll up.

Note: even when using "terminal.integrated.shell.linux":"/opt/microsoft/powershell/6.0.0-alpha.10/powershell",

![vscodeterminalbug](https://cloud.githubusercontent.com/assets/19892435/18790473/e41305fe-817c-11e6-8926-e6f36220dc5f.png)

**Comment by Tyriar** [comment]
Can you try in the latest insiders build? https://code.visualstudio.com/insiders

Also does the scroll bar appear at all as it does with `bash`?

**Comment by MaximoTrinidad** [comment]
Hi Tyriar,

I'm using the latest version 1.5.3 as I documented in this incident,  Also, this only happens in Linux. Windows version works fine. Apparently the scroll bar looses the focus when opening PowerShell from Bash.

Ubuntu normal Terminal application works OK.

:)
Max

**Comment by Tyriar** [comment]
This is happening because xterm.js disables the scroll bar when it enters application mode https://github.com/sourcelair/xterm.js/issues/286

In the meantime you should be able to use ctrl+shift+page up/down

**Comment by MaximoTrinidad** [comment]
Thanks Tyriar!  using the ctrl+shift+PageUp or Down works.

:)

**Comment by Tyriar** [comment]
This should be fixed in latest insides along with scrolling and scroll bar in oh-my-zsh (#7817).
