### ISSUE TITLE
May spam issues accidentally

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode#125380]
Issue Type: <b>Bug</b>

May spam issues accidentally by click the `Create on GitHub` botton multi times.

VS Code version: Code - Insiders 1.57.0-insider (c324c61ad572be43a8696780e1aba3c1a2c46eee, 2021-06-02T17:38:06.906Z)
OS version: Linux x64 5.11.0-18-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (0.43GB free)|
|Process Argv|--unity-launch --crash-reporter-id d8e457ee-3d19-4321-8076-83a194659376|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.1.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.9.2
vscode-pull-request-github|Git|0.26.0
mdmath|goe|2.5.1
google-translate|han|1.2.1
language-julia-insider|jul|1.2.2
python|ms-|2021.6.897246044-dev
vscode-pylance|ms-|2021.6.1-pre.1
jupyter|ms-|2021.6.898847129
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
cmake-tools|ms-|1.7.3
cpptools|ms-|1.3.1
platformio-ide|pla|2.3.2
vscode-markdown-paste-image|tel|0.12.3
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
00j7a122:30294756
vscod805cf:30301675
vscextlangct:30310089

```

</details>

![image](https://user-images.githubusercontent.com/57612792/120633235-7c0b7500-c49c-11eb-89e9-bad7227053c6.png)

**Comment by gjsjohnmurray** [comment]
Maybe #115857 which claims to be fixed in Insiders
