### ISSUE TITLE
showInlineCompletions and TabCompletions don't work well together

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125328]
Testing #124979

Apply these settings:
```json
"editor.suggest.showInlineCompletions": true,
"editor.tabCompletion": "on"
```

with this code:

```ts
import * as vscode from 'vscode';

export class LoremInlineCompletionItemProvider implements vscode.InlineCompletionItemProvider {
    public static documentSelector: vscode.DocumentSelector = {
        pattern: "**"
    };

    private static allSuggestions = [
		'arguments ipsum ',
		`arguments foo`,
		`arguments bar`,
	];

    provideInlineCompletionItems(document: vscode.TextDocument, position: vscode.Position, context: vscode.InlineCompletionContext, token: vscode.CancellationToken): vscode.ProviderResult<vscode.InlineCompletionList<vscode.InlineCompletionItem> | vscode.InlineCompletionItem[]> {
        const text = document.getText(document.getWordRangeAtPosition(position));
        if (!text || !text.startsWith('a')) {
            return [];
        }

        return LoremInlineCompletionItemProvider.allSuggestions.map(s => { return <vscode.InlineCompletionItem>{ text: s }});
    }
}
```

Here's what I see. There's no way to accept an inline completion:
![no-way-to-accept](https://user-images.githubusercontent.com/2644648/120542072-83008d80-c39f-11eb-834c-326da6b5cbe2.gif)

**Comment by hediet** [comment]
Thanks for reporting this! Yes, this scenario is currently not supported.

**Comment by hediet** [comment]
It seems like a simple weight adjustment did the trick. I thought there was some complicated interaction causing problems.

**Comment by TylerLeonhardt** [comment]
Doesn't this flip the problem though @hedie? Now tab completion won't work with inline completion?

**Comment by hediet** [comment]
Tab completion will not work if an inline completion is visible, that is right. However, if no inline completion is visible, tab completion will work.

I think it is fair to give the inline completion precedence, since it is visible and can be canceled with escape (and then tab completion would have precedence). What are your thoughts?

**Comment by TylerLeonhardt** [comment]
I think that's fine so long as 2 things happen:
* ghost text should take a second or 2 to show up (so that I can hit tab tab tab and only get tab completion until I'm on the suggestion that I want ghost text to show up on
* if I ESC ghost text, hitting Tab should trigger tab completion I think.

Alternatively, and maybe harder, have the suggest widget pop up in tab completion...because it's my understanding that the suggest widget and ghost text can't be displayed at the same time?

**Comment by hediet** [comment]
> Alternatively, and maybe harder, have the suggest widget pop up in tab completion...

Don't you get this behavior when enabling quick suggest?

> if I ESC ghost text, hitting Tab should trigger tab completion I think.

This should work already.

> ghost text should take a second or 2 to show up (so that I can hit tab tab tab and only get tab completion until I'm on the suggestion that I want ghost text to show up on

Hmm, you could also disable inline suggestions and trigger them manually (there is a command for that). I'm not a huge fan of making the 1-2 seconds delay default (or even a default when tab completion is on). Though it could make sense to have a setting to set a delay value.

**Comment by TylerLeonhardt** [comment]
> Don't you get this behavior when enabling quick suggest?

I wasn't clear there, my bad. I meant that the suggest widget would stay open after you hit tab and then when you hit Tab again it would change the text in the editor and the suggest widget would move the cursor down to the second option, and then tab again would change the text in the editor and move the cursor down to the third option, etc.

I thought I saw other editors do this, but I can't seem to get it working that way again so maybe I dreamt it 😆 

in any case, ignore that point.
