### ISSUE TITLE
Code Helper (renderer) consuming 300-400% cpu

### ISSUE THREAD

**Issue by krsinghshubham** [microsoft/vscode#125367]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Just opening a rails-ember folder trigger the cpu throttling taking the whole system down. The mac activity monitor shows its code helper(renderer) and the vscode process show its watcherServices.
I am very bad to execute the commands from github issue pages as none is promising and i dont want to mess up with anything unnecassrily.

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id bdc44446-94b8-4d2c-a254-75d195e62cbd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.1
TabOut|alb|0.2.0
Bookmarks|ale|13.0.4
vscode-erb-beautify|ali|0.2.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
solargraph|cas|0.23.0
bracket-pair-colorizer|Coe|1.0.61
erb|Cra|0.0.1
dart-code|Dar|3.23.0
flutter|Dar|3.23.0
vscode-faker|dee|1.5.0
githistory|don|0.6.16
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
codespaces|Git|0.10.4
vscode-pull-request-github|Git|0.26.0
ruby|gro|0.1.0
ember-snippets|Hri|1.0.0
better-cpp-syntax|jef|1.15.5
vscode-rufo|jnb|0.0.4
vscode-gutter-preview|kis|0.27.1
vscode-leetcode|Lee|0.17.0
vscode-ember-unstable|lif|2.0.24
cpptools|ms-|1.4.0
cpptools-extension-pack|ms-|1.0.0
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.3.0
live-server-preview|neg|0.1.4
material-icon-theme|PKi|4.7.0
heroku-command|pko|0.0.8
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
LiveServer|rit|5.6.1
swdc-vscode|sof|2.5.15
code-spell-checker|str|1.10.2
bootstrap4-vscode|the|6.1.0
errorlens|use|3.2.7
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.4.0
bootstrap-3-snippets|wcw|0.1.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by rebornix** [comment]
@krsinghshubham can you follow the wiki https://github.com/microsoft/vscode/wiki/Performance-Issues to help provide more info about what's going on? We would like to know more info about that particular process

**Comment by krsinghshubham** [comment]
code --status is not working for me , why it can't be simply exported in logs while registering a bug from vsc extension.
Although i already mentioned its coming from watcherService, which is troubling when the project folder is too big.
If anyone want to know more , please mail me at shubhamk604@gmail.com, will share a meeting link to show live demo.

**Comment by krsinghshubham** [comment]
@bpasero this is not done man, atleast provide the refrence to the duplicated issue or more specifically a solution for the issue. Yes i saw many similar issue but those were because of extensions, mine is with vscode itself. 
And if no solutions exist then you should not mark it as closed.

**Comment by krsinghshubham** [comment]
Also i noticed that in each of those issue pages you guys are asking for additional information , what additional information is required if the bug is being posted from issue reporter too ? I can't find a working solutions anywhere .

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/3998
