### ISSUE TITLE
The states of the two sides are out of sync

### ISSUE THREAD

**Issue by zhangenming** [microsoft/vscode#125384]
as the figure shows
when we open two editor,
I select right editor a variable, `aaaaa`
but left editor  does not highlight it ,
thanks 
![image](https://user-images.githubusercontent.com/21235555/120641974-e2959080-c4a6-11eb-955e-62ea816f9438.png)

**Comment by rebornix** [comment]
Selection states are not synced between editors.

**Comment by zhangenming** [comment]
> Selection states are not synced between editors.
Why don't they, thanks
