### ISSUE TITLE
Opening a new window shows a prompt that GitHub extension cannot be activated

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125395]
Steps to Reproduce:

1. Open a new window. Following prompt is shown

![image](https://user-images.githubusercontent.com/10746682/120658806-0d232180-c486-11eb-88cd-48c53b0344ed.png)

**Comment by sandy081** [comment]
This is because Git extension is disabled because of workspace trust and GitHub extension is enabled (as it supported). Actual fix is to disable GitHub extension which will be taken care here - https://github.com/microsoft/vscode/issues/122448.

Did a pragmatic fix here:

- Fixed the prompt in this case by providing appropriate message and no actions are shown.
- In order to provide better experience OOB ie., not to show these error prompts, made GitHub extension to not to support untrusted workspaces as its dependency Git extensions does not.

**Comment by lszomoru** [comment]
@sandy081, in case that we detect that the dependency is not loaded due to workspace trust, could we be more specific in the message - _Cannot activate the X extension because it depends on the Y extensions which is not supported in Restricted Mode._ Could we also add an action called `Manage Workspace Trust` which would open the workspace trust editor?

**Comment by sandy081** [comment]
Done

**Comment by chrmarti** [comment]
Cloning a Repository Container now fails in a new empty window (and untrusted workspaces in general): https://github.com/microsoft/vscode-remote-release/issues/5134. Is there a way to make the repository picker available when the workspace is not trusted yet?

**Comment by sandy081** [comment]
It seems @eamodio changed back to support git & GitHub extensions to be supported in untrusted workspaces. So @chrmarti your scenario shall work now.
