### ISSUE TITLE
Preview opening on rename

### ISSUE THREAD

**Issue by MGlolenstine** [microsoft/vscode#125377]
Does this issue occur when all extensions are disabled?: No
I think it's not related to an extension though, as it happens with `editor.action.rename`.

- VS Code Version: 1.56.2
- OS Version: `Linux x64 5.11.15_1`

Steps to Reproduce:

1. Open a file in a language you have support for (Happened with rust-analyzer).
2. Select an element and press F2 to rename the element.
3. The popup says `Press ENTER to rename; SHIFT+ENTER to preview`.
4. No matter what you click, it's going to open the preview.

**Comment by jrieken** [comment]
> No matter what you click, it's going to open the preview.

These things can't be clicked, it's just a status message.

**Comment by MGlolenstine** [comment]
> > No matter what you click, it's going to open the preview.
> 
> These things can't be clicked, it's just a status message.

You can click `ENTER` or `SHIFT+ENTER`.

**Comment by jrieken** [comment]
Any special keybinding, setting, or extension can affects this? Can you try with the `--disable-extensions` flag and also with `--user-data-dir <empty-folder>`?

**Comment by MGlolenstine** [comment]
`--disable-extensions` doesn't cause this problem, as I mentioned in the OP.
`--user-data-dir <empty-folder>` does work, however.
It could be some keybinds going awry, but I don't think that would be the case, as it does the same on a default keybind setting.

**Comment by MGlolenstine** [comment]
After running the above command and reopening the `code` normally, the "bug" is gone...
I'm not really sure what was going on, but it appears to be solved.
