### ISSUE TITLE
iPad: don't show debug commands in command palette

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#125311]
Since debugging is not supported on iPad (and the Run menu is empty), debug commands should not be offered in the command palette either.

**Comment by alefragnani** [comment]
Hi @weinand ,

I’m wondering what do you mean about _debugging is not supported on iPad_, because I’m able to debug console apps using Go, JS, C#, and would love to be able to keep using my iPad on those 😕 .

Or is it relative to debugging VS Code extensions (which I reported in #118383), or other projects that requires port forward (reported in #85254 -> https://github.com/MicrosoftDocs/vscodespaces/issues/728)?

Thank you

**Comment by weinand** [comment]
@alefragnani currently no debug extension exists that runs in a browser, because they all require node.js and a native runtime.

**Comment by alefragnani** [comment]
But in this case we are talking about Codespaces on iPad, right? Because the debug extension runs on the _remote_.

**Comment by isidorn** [comment]
You are both correct.

We will simply not register the debug commands when there is no debug extension registered. That way we shoul cover all cases.

**Comment by isidorn** [comment]
We are actually already doing the right thing.
The only visible commands are the test one. Thus forwarding this to @connor4312 
@connor4312 maybe you could introduce some context keys such that when there is no test provider that these commands are not registered

@weinand let me know if you were seeing something else and if you can still reproduce this

![Screenshot 2021-06-09 at 16 09 56](https://user-images.githubusercontent.com/1926584/121370812-50293d00-c93d-11eb-9ac3-cc558a0f84fb.png)

**Comment by weinand** [comment]
@isidorn yes, most likely I was seeing the test actions and a few others like the "Focus on Xxx View".
I think the "Run and Debug: Focus on Xxx View" are somewhat OK, because they actually work even if no debuggers are available (I remember that some users are using breakpoints as bookmarks ;-)

**Comment by connor4312** [comment]
I've scoped these so that the mentioned commands will only appear when at least 1 test provider is registered.
