### ISSUE TITLE
All notebook profiles (even default) add `notebook.undoRedoPerCell: true`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125316]
Testing #125014

1. Start at the default profile
2. Switch to another one
3. Back to default
4. notebook.undoRedoPerCell: true is left in the settings

Since it seems like all profiles 'want' this to be true, should it be on by default?

**Comment by roblourens** [comment]
FYI @rebornix, if you add a setting to a profile, you have to add it to all profiles. I need to make TS help us here

**Comment by rebornix** [comment]
Fixed through https://github.com/microsoft/vscode/commit/60dd761211bb3f744eb5f591e5643f2fddb55bf6
