### ISSUE TITLE
Crash when backspace

### ISSUE THREAD

**Issue by iNViTiON** [Microsoft/vscode#12537]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. type this code `count = '🏆🏅🥇';`
2. the third one will show as square box (on Windows 10 AU) press backspace to delete the third emoji require 2 times of backspace. But the app crash when I press the 3rd times of backspace to delete the second emoji.

**Comment by chrmarti** [comment]
Reproduced in 1.5.3, appears to be fixed in the current insider build.
