### ISSUE TITLE
Extension View icon shows outdated but no extensions are outdated.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12535]
- VSCode Version:1.6 insiders
- OS Version:Windows 10

Note: This is a recent regression and only showed up with the latest insiders build. d81ee41c51cae93a5cac967e42a28660a3a7e005

Steps to Reproduce:

1. With just two extensions installed (DavidAnson.vscode-markdownlint-0.5.0 and seanmcbreen.Spell-0.8.6), look at Extension View icon

![outdatedext](https://cloud.githubusercontent.com/assets/12818376/18793708/e5378d12-8170-11e6-96ef-ecf512a77a11.png)

The "Show Outdated Extensions" query also doesn't show any results. 

The installed extension versions match the latest Marketplace versions.

**Comment by gregvanl** [comment]
Uninstalled both extensions and now the Extension View outdated count is 2.  Both extensions appeared to be successfully removed from .vscode-insiders\extensions.

![uninstalledandoutdated](https://cloud.githubusercontent.com/assets/12818376/18794409/43f8b382-8174-11e6-9a7d-9d73d43f4aff.png)

**Comment by gregvanl** [comment]
Reinstalling the two extensions still shows Extension View icon outdated count. 
![reinstallandoutdated](https://cloud.githubusercontent.com/assets/12818376/18794519/ad236186-8174-11e6-8bab-f14b904efb98.png)

**Comment by Sidneys1** [comment]
Same here - mine shows one extensions outdated. Haven't tried uninstalling all of my extensions though.

**Comment by sandy081** [comment]
Related to #12507
