### ISSUE TITLE
Get editor line height (px) and character space-width (px) by VSCode API

### ISSUE THREAD

**Issue by leodevbro** [microsoft/vscode#125341]
Hi, I wrote VSCode extension, took me 6 months to build. It's a visual helper, it highlights nested code blocks. You can change block colors, depth, turn on/off focus, curly/square/round brackets, tags, python indentation and more.....

**Supports:** Python, PHP, JavaScript, JSX, TypeScript, TSX, C, C#, C++, Java, HTML, CSS and more... 

It has already more than **1000** installs.
https://i.ibb.co/ZTkQKgR/blockman-view-extension333d.png

https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman

<p align="center"><img
  src="https://raw.githubusercontent.com/leodevbro/vscode-blockman/main/demo-media/still-image/infograph/intro-before-after---png.png"
  alt="alt text testing"
/></p>

The main problem is calculating or finding editor line height (px) and character space-width (px) of monospace font, I cannot find such function in the VSCode API. I need these two values to render blocks properly.

**So currently the only solution is to manually adjust line height and character space-width.**
For simplicity, font must be monospace, so block width will be just multiplication of char count and char space-width (px).
<p align="center"><img
  src="https://raw.githubusercontent.com/leodevbro/vscode-blockman/main/demo-media/video/height-width---c2-apng.png"
  alt="alt text testing"
/></p>

**So, in order to avoid manual adjustment of these two values, please provide a function to get these two values programmatically with VSCode API.**

Thanks...

**Comment by leodevbro** [comment]
I maybe looks like a duplication of this issue:

https://github.com/microsoft/vscode/issues/118994

But, I believe it needs a separate issue.

**Comment by LeoKac** [comment]
Would love to see this feature in action!

**Comment by alexdima** [comment]
Very nice! Have you tried using `ch` instead of `px` for the decorations?

**Comment by leodevbro** [comment]
> Very nice! Have you tried using `ch` instead of `px` for the decorations?

Wow, thanks @alexdima, I think `ch` is working, even when zooming with mouse-wheel. You are a life saver. I will update Blockman soon. And, what about line height? I think it must be even easier.

**Comment by alexdima** [comment]
The line height can be straight forward computed by you. You can read the setting `editor.lineHeight` and then mimmic what the editor [is doing internally](https://github.com/microsoft/vscode/blob/8d87a664274d23477388e750d40d4ab942c83751/src/vs/editor/common/config/fontInfo.ts#L54-L58):


```ts
/**
 * Determined from empirical observations.
 */
const GOLDEN_LINE_HEIGHT_RATIO = platform.isMacintosh ? 1.5 : 1.35;
const MINIMUM_LINE_HEIGHT = 8;

if (lineHeight === 0) { // 0 is the default
	lineHeight = Math.round(GOLDEN_LINE_HEIGHT_RATIO * fontSize); // fontSize is editor.fontSize
} else if (lineHeight < MINIMUM_LINE_HEIGHT) {
	lineHeight = MINIMUM_LINE_HEIGHT;
}
```

**Comment by leodevbro** [comment]
Wow, seems promising. There is one problem, how can I import `platform`?
![image](https://user-images.githubusercontent.com/54504880/120827205-41710d80-c56c-11eb-9306-bb4741ff8930.png)

I add this line: `import * as platform from 'vs/base/common/platform';`
but it says: Cannot find module 'vs/base/common/platform' or its corresponding type declarations.ts(2307)

**Comment by alexdima** [comment]
`platform.isMacintosh` is only available in our core. It is true if the OS is macOS. You can use `node`'s `process` to find out the OS.

**Comment by leodevbro** [comment]
Ok, and one more question. It is not crucial for now, but it would be nice to find solution. I'm getting line height correct until I zoom with mouse.

![image](https://user-images.githubusercontent.com/54504880/120830796-ed682800-c56f-11eb-800b-d9ff55b09802.png)

I can see `editor.mouseWheelZoom` config value which is true/false, but I could not find the current zoom level value, so maybe if zoom level is 2x, then I can just multiply lineHeight with 2.

![image](https://user-images.githubusercontent.com/54504880/120831094-3d46ef00-c570-11eb-91dd-159a0d983469.png)

There is zoom level of editor and also zoom level of window which also effects the editor zooming. So, can I always get the correct pixel value somehow? Yeah, now things are getting complicated a bit maybe.

![image](https://user-images.githubusercontent.com/54504880/120831559-b5adb000-c570-11eb-8563-3d4200187278.png)

**Comment by alexdima** [comment]
I'm sorry, unfortunately the editor font zoom is not exposed in any way to the API.

**Comment by leodevbro** [comment]
Thanks for everything. I updated Blockman already, the latest version is 1.1.1 (2021-06-05).

Also, maybe this is outside of the topic of this issue, but please check it out:

<p>VSCode Color Decorators of styles causes wider text line, some situations are handled, some situations are not handled yet, because I managed to find some decorators with custom regex but not all.</p>
<p align="center"><img
  src="https://raw.githubusercontent.com/leodevbro/vscode-blockman/main/demo-media/video/color-decorators---c2-apng.png"
  alt="alt text testing"
/></p>

Is there any way to get all the locations (**line index & char index or global position**) of all the color decorators? So Blockman will make certain blocks wider if necessary.

**Comment by leodevbro** [comment]
Now I know the solution to get the locations (**line index & char index**) of all the **color decorators**.
```typescript
const dataArr: any[] | undefined = await vscode.commands.executeCommand(
    "vscode.executeDocumentColorProvider",
    document.uri,
);
```

Thanks **rioV8** from **stackoverflow**:
https://stackoverflow.com/questions/68020444/how-to-get-positions-of-all-css-color-decorators-with-vscode-api

**Comment by leodevbro** [comment]
@alexdima, any ideas why Blockman not available in VS Code Web?

![image](https://user-images.githubusercontent.com/54504880/130336720-6a4b9543-4537-48ff-bf87-c6b683b3909a.png)

I think it's because Blockman is using node to detect OS:

![image](https://user-images.githubusercontent.com/54504880/130336766-a5890bcf-57d6-4630-b5f3-dffa0633aba2.png)

So, maybe it is not working in web version of vscode, because web version does not have such Node support, am I right?

**Comment by aeschli** [comment]
Documentation on how to write extensions for VS Code Web is in the works. Tracked in https://github.com/microsoft/vscode/issues/130628.
