### ISSUE TITLE
Investigate making current status (selected box in workspace trust) more clear

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#125305]
Steps to Reproduce:

1. I trusted a folder before. When re-opening the folder, I wasn't aware if I trusted it or not and Monokai Pro's highlighting also didn't help.
2. I clicked to see which extensions would be disabled/limited.
3. The empty results looked broken and I refreshed a few times until I realized the folder is trusted.

![image](https://user-images.githubusercontent.com/8599/120511807-9865bf80-c37f-11eb-82fb-f6e18eb2a182.png)

Related thoughts:

- What's the expected outcome for the links when restricted mode isn't enabled?
- Could there be more indication of the current state than color-coding and updating the header? cc @misolori 
- All the copy in the restricted box sounds like it applies right now. Maybe wording can help to highlight the non-selected box as "if you choose to select this"?

**Comment by misolori** [comment]
We could add a check to the top left to indicate that state a bit better:

![image](https://user-images.githubusercontent.com/35271042/120524439-eaacdd80-c38b-11eb-8be8-73283e5a3e9a.png)

Which could theme better:

![image](https://user-images.githubusercontent.com/35271042/120524460-f00a2800-c38b-11eb-9e1e-82b8897b234e.png)

Also in the past we did explore turning the button into a status and disabling it like:

<img width="719" alt="CleanShot 2021-06-02 at 10 21 21@2x" src="https://user-images.githubusercontent.com/35271042/120524836-58590980-c38c-11eb-96ff-e318613ae666.png">

**Comment by sbatten** [comment]
When the view was specific to workspace trust, we showed them regardless of the current state. Now, since the view covers virtual workspace extensions and the label is to cover extensions that are not supported only. 

The checkbox is a nice idea, but the theme color is based on button colors which in @digitarald's theme are notably low contrast.
