### ISSUE TITLE
InputBox busy property not working

### ISSUE THREAD

**Issue by youngmg1995** [microsoft/vscode#125326]
Setting the "busy" property to true for an InputBox should display a progress bar under the input box. This doesn't appear to be working though, and no progress bar is displayed.

To reproduce, create an extension command with the following:

```
let input = vscode.window.createInputBox();
input.busy= true;
input.show();
```

**Comment by TylerLeonhardt** [comment]
@youngmg1995 the "busy" indication should really only happen _after_ you show an input because the assumption is that when you show an input, it should have all the initial data you want to show...

If you really want to trigger a busy indication at the start of a quick pick, you should set it _after_ the `show()`:

```ts
let input = vscode.window.createInputBox();
input.show();
input.busy = true;
```

Because `busy` is usually set after a quick pick is visible.

I believe `show()` clears busy status which is why your example doesn't work.

**Comment by youngmg1995** [comment]
@TylerLeonhardt, even in that order I still do not get the expected result (a progress bar showing on the input box). And indeed this is the order in which I handled it, as it is given in the [quickinput-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample), which also does not work as expected.

**Comment by TylerLeonhardt** [comment]
@youngmg1995 can you send a gif or video? It's working for me in the latest insider build:

![proof](https://user-images.githubusercontent.com/2644648/120691687-9c670f80-c45b-11eb-8fc5-1b4a2ab74a0b.gif)

I just added another quick input sample with this:

```ts
import { ThemeIcon, window } from 'vscode';

export async function simpleMultiStepInput() {
	const quickpick = window.createQuickPick();
    quickpick.title = 'Hello fam'
    quickpick.items = [{ label: "don't pick me" }, { label: 'or me' }]

    quickpick.onDidChangeValue((e) => {
        window.showInformationMessage(e);
    });
    quickpick.buttons = [
        {
            iconPath: ThemeIcon.File,
            tooltip: 'change value'
        }
    ];
    quickpick.onDidTriggerButton(e => {
        quickpick.value = "Changed!";
    });

    quickpick.show();
    quickpick.busy = true;
}
```

**Comment by TylerLeonhardt** [comment]
It also could be your theme if you use something custom. Give insiders a try... or wait a week since stable will be released within a week.
