### ISSUE TITLE
Options autocompletion with Intellisense for string literal and union types 

### ISSUE THREAD

**Issue by MohamedLamineAllal** [microsoft/vscode#125394]
```ts
export type TInstrument = ('option1' | 'option2' | 'option3' '') | string;
```
As listed by the typescript issue here https://github.com/microsoft/TypeScript/issues/29729

Having trhe feature where intelisense  handle the provided options and show them (string literal)! Will be of big efficiency and user experience! Less mistakes! Higher speed! And profiting from intellisense and autocompletion...

The new typescript feature for type preservation can be helpful for an implementation!

https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-rc/#smarter-type-alias-preservation

In the newest version of typescript the hack in the thread above is no more functional!

And intelisense doesn't support the autocompletion! When the union resolve to string!

Implementing the feature that support that! Will be too beneficial!

**Comment by mjbvz** [comment]
Closing this as upstream
