### ISSUE TITLE
Support current Insert mode in Suggestions Inline Preview

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#125302]
Related to #125001

If user has `"editor.suggest.insertMode": "insert"` and holds <kbd>Shift</kbd> button it would be great to see actual result of completion (`1..toExponential()`), instead of both parts (`1..toExponentialPrecision()`) as shown on the screenshot below.
![image](https://user-images.githubusercontent.com/1312662/120506962-13a29200-c3cf-11eb-8ae7-27f85fa437e9.png)

It's probably trickier for `"editor.suggest.insertMode": "replace"` but may be useful as well. Need more feedback of users with this mode.

@jrieken  Is is same suggestion as in https://github.com/microsoft/vscode/issues/125001#issuecomment-851881986 ?

**Comment by hediet** [comment]
Oh, I did not even know about Shift+Enter (I didn't enable this status bar).
Nice finding!

**Comment by IllusionMH** [comment]
@hediet Looks like it works great in case when suggestion matches current value but is longer, however not in other cases. So no idea how text will be transformed in this case.

`|` - cursor position, observer results assumes that user holds <kbd>Shift</kbd>

```js
const sameFirst = () =>{};
const sameFirstButLonger = () =>{};
const sameSecond = () =>{}

same|First();  // will show grayed out ButLonger if user select sameFirstButLonger, but nothing visible if user selects sameSecond

same|FirstButLonger() // nothing visible if user selects sameFirst or sameSecond
```

**Comment by hediet** [comment]
> Is it expected behavior? Because it's same with toExponential and toPresision - not clear what will change.

Yes. What should be the expected result?
If ghost text is shown, it should reflect the exact same state as if the completion item was accepted. This is difficult, if accepting an item is not a strict text insert operation.

**Comment by IllusionMH** [comment]
I would expect to see ghost text replacing existing text if it's going to be overridden - end goal to see result when I accept suggestion.

**Comment by hediet** [comment]
> I would expect to see ghost text replacing existing text if it's going to be overridden

I think simply hiding text would confuse users, especially for inline suggestions that the ghost text was originally designed for.
Maybe it might not be that confusing for the preview of items selected in the suggestion widget.

Feel free to open a separate issue about also showing the preview when it would delete text (which is independent of this issue, as it can happen for both insert modes).

**Comment by hediet** [comment]
Verification steps:
* Set `"editor.suggest.preview": true,`
* Trigger autocomplete at `win|do` (`|` being the cursor position) in a `.js` file.
* Notice how `window` is shown in the completion and the ghost text is `win[dow]do`.
* Hold shift.
* Notice that the ghost text is now `windo[w]`
