### ISSUE TITLE
Add "Duplicate" option to Explorer context menu

### ISSUE THREAD

**Issue by augnustin** [microsoft/vscode#125386]
Yes, this is a duplication of #36113 and #14449 as both conversations are closed (why?).

I miss the "duplicate" feature all the time.

@bpasero suggests it should be an extension but I don't agree. Here's why:

1. I would have never though of looking for an extension for this feature, as extensions are here to add fancy features while this definitely **feels core**. I only found it by searching for a related issue (which I was sure existed), and still can't believe it is there.

2. Actually, the related extension doesn't work as expected (sublime's behavior), as the only thing that can be edited is filename, while on sublime, the whole path can be edited.

![image](https://user-images.githubusercontent.com/1970156/120641190-9b41dc80-c473-11eb-82ec-e4196d8318d5.png)
*Eg. If I need to duplicate to `/home/augustin/Workspace/my_project/other/test/example.js` it is possible.*

3. The suggested alternate solution (copy/paste) requires all those steps:
    - Right click -> Copy (2 clicks)
    - Scroll to containing folder (this can be tedious if many files + error-prone with no textual confirmation)
    - Right click -> Paste (2 clicks)
    - Right click -> Rename (2 clicks)
    - Edit filename with the extra `copy` to remove **anyway** as it will *never* make sense
    - Done! :sweat_smile: 

While duplicate simply requires 2 clicks and textual editing with no useless step.

4. The above compares duplication in the same folder, but if it implies folder creation, it is even more steps to add. (Eg. `my_project/other` doesn't exist in the above example)

5. Using Copy/Paste messes up the clipboard, while duplicate doesn't.

6. This is clearly would not surcharge the UI as this would be one entry on right click, juste bellow Copy/Paste

Please consider the **UX improvement** here. I know that one *can* do it already, but UX is not about what the user *can* do, but what he **does**. And the user doesn't start by installing extensions, but coding.

Thanks for your consideration

**Comment by IllusionMH** [comment]
> both conversations are closed (why?)

Both are marked as extension candidate because there might be different needs for duplication - right to this folder, to some specified path, with or without rename etc. so there isn't single solution.

With extension users who need specific functionality can install extension and use it and those who don't  - won't have another unused entry to context menu (which is already big).
