### ISSUE TITLE
Strange line in editor for tsconfig.json file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1253]
See screen shot and notice the line behind compileOptions.

I have no steps how I got there.

![capture](https://cloud.githubusercontent.com/assets/1931590/11780481/85d1ab48-a262-11e5-8dec-ed298a7092bd.png)

**Comment by alexandrudima** [comment]
@dbaeumer if you have the window still open, we can inspect together what's going on.

**Comment by dbaeumer** [comment]
@alexandrudima sorry, no. And I didn't see it again. No objections if you want to close it.
