### ISSUE TITLE
Untitled notebooks - remove dirty indicator

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#125329]
Testing #124844

**Repro steps:**
* Turn off "Auto Save"
* Create a new untitled notebook
* Save the untitled notebook
* Add some contents -> dirty indicator appears
* Undo the contents -> dirty indicator is removed
* Add some contents again
* Remove the contents manually without using undo

**Expected:** 
Dirty indicator should be removed

**Actual:**
Dirty indicator remains

**Comment by bpasero** [comment]
This matches the behaviour for untitled text files, we only remove dirty indicator for undo operations but never for something the user types.
