### ISSUE TITLE
Getting Started: add a new step when git is not installed

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125349]
This could include platform specific instructions. Curious to know which platforms we're talking about here... Windows for sure but what else? Does Raspbian ship git?

**Comment by Ayonijakaushik19** [comment]
Hi, @TylerLeonhardt @JacksonKearl I would like to work on this please assign this to me.

**Comment by JacksonKearl** [comment]
@Ayonijakaushik19 thanks! We cannot assign you as you are not a member of this issue, but please feel free to submit a PR. The relevant code is here: https://github.com/microsoft/vscode/blob/920303b974e9ac5b9f7d30d5bc354db5a849c793/src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts#L314

**Comment by heptapod42** [comment]
@JacksonKearl @Ayonijakaushik19 I can take this up if it's not already done. Could you elaborate on what new step needs to be added?

**Comment by louis-nwosu** [comment]
hello guys, i'm really trying to get started in contributing to open source...can how i get started here?

**Comment by vighnesh192** [comment]
Hello @TylerLeonhardt @JacksonKearl, this is my first time contributing to an open source project and I'm willing to work on this issue. I just set this repo up on my machine and its working. I had a look at the file you've shared and there are conditions for few steps which checks if git is missing. So, I tried simulating the inexistence of git just by disabling it in vs code settings. Is that fine?

And also, should there be a button which says "Install Git"? If yes, what should it be linked to?
![Screenshot (40)](https://user-images.githubusercontent.com/64535868/128671994-ce18f02c-595d-4f9d-80b3-a6e10bae672e.png)

**Comment by JacksonKearl** [comment]
We can use https://aka.ms/vscode-install-git. I recommend testing this by fully removing git if at all possible, otherwise there my be unexpected behaviors when a new users is actually running this for the first time.

**Comment by jayeshmann** [comment]
Is this complete, or I can still work on this?

**Comment by JacksonKearl** [comment]
I am not aware of any work done here.

**Comment by jayeshmann** [comment]
Could you assign it to me? I would like to work on this quickly.

**Comment by vighnesh192** [comment]
> We can use https://aka.ms/vscode-install-git. I recommend testing this by fully removing git if at all possible, otherwise there my be unexpected behaviors when a new users is actually running this for the first time.

Hello, I'm sorry I should've kept you updated but I've made those changes and I just have to test it by uninstalling git.

**Comment by jayeshmann** [comment]
@vighnesh192 I have tested with uninstalling git. Can I take this?

**Comment by vighnesh192** [comment]
Omg I just did that too...ready to push. What do we do?😅😂

**Comment by stuartleeks** [comment]
Just tested this on Windows, and the "Install Git" item is marked as ticked when you click on the "Install Git" button regardless of whether you have actually installed Git - is this expected? Or would it be better to only tick the button when an installation of git is detected?

The screenshot below shows that I clicked the button but didn't actually install Git. The item is ticked but attempting to run git in the terminal (or git pane) fails

![image](https://user-images.githubusercontent.com/1824461/130758667-b00a549a-f38d-45a4-93e6-033dcdd1f7bf.png)

**Comment by vighnesh192** [comment]
Can we have `setInterval()` which checks if **git** is installed when we reach this step? 
@JacksonKearl

**Comment by JacksonKearl** [comment]
No, it should work based on context keys, which have change events.

**Comment by vighnesh192** [comment]
Ohh okay

**Comment by bhavyaus** [comment]
Updated step to include link to `Reload window`.
