### ISSUE TITLE
hover on the test item shows it's failed when the item has no test result

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125358]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (user setup)
Commit: c324c61ad572be43a8696780e1aba3c1a2c46eee
Date: 2021-06-02T17:38:06.137Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/6193897/120577131-77bc6900-c456-11eb-847c-c209c2c3bbd0.png)

_//cc @connor4312_

**Comment by connor4312** [comment]
I think this got fixed with the refactor around multiple tests per line

**Comment by isidorn** [comment]
Can not repro with latest -> verified
