### ISSUE TITLE
Select multiple tabs via shift key

### ISSUE THREAD

**Issue by mayafrog** [microsoft/vscode#125333]
Hi,

I am reopening this as the previous feature requests did not receive enough attention to be put into the backlog.

I think the addition of the feature of being able to select multiple tabs, and then moving them as a group to another editor or right clicking for a context menu to close / move to another editor will significantly help myself, and many other's workflow. Basically all modern browsers have this feature now, and I think its about time that Visual Studio Code gets it too.

Thankyou very much!

**Comment by IllusionMH** [comment]
/duplicate of #119327

Upvote that issue and if there are some usecases that are not mentioned in that issue - leave a comment there.
