### ISSUE TITLE
File not uploading output to output.txt file immediately

### ISSUE THREAD

**Issue by eRuaro** [microsoft/vscode#125355]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Have g++ compiler installed (I have it installed on both WSL2 and windows)
2. Have a 2 column layout with the source file, and txt file. Wherein the txt files are split horizontally in their column.
![Screenshot (246)](https://user-images.githubusercontent.com/69240261/120575362-83f2f700-c453-11eb-88aa-dbb58d00ea02.png)
3. Have a C++ file with the following code.
```
#include <iostream>

int main() {
    #ifndef ONLINE_JUDGE
        freopen("input.txt", "r", stdin);
        freopen("output.txt", "w", stdout);
    #endif

    std::string x;
    std::cin >> x;
    std::cout << x << "\n";
}
```
4. Run C++ file.

Expected output:
1. Output from file will immediately be shown to the output.txt file in realtime.

Actual output:
1. Output isn't shown immediately. I had to close the output file and open it again for it to show.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.81GB (4.33GB free)|
|Process Argv|--crash-reporter-id 6ad8f37c-cd05-438a-9b26-5b95219347c5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|Memory (System)|9.18GB (8.63GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
bracket-pair-colorizer-2|Coe|0.2.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
better-cpp-syntax|jef|1.15.5
remote-wsl|ms-|0.56.4
awesome-flutter-snippets|Nas|2.0.4
material-icon-theme|PKi|4.7.0
errorlens|use|3.2.7
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
vscode-pull-request-github|Git|0.26.0
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehovct:30309550
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by bpasero** [comment]
Seems to be file watching in remote related.

**Comment by aeschli** [comment]
Is the file located on a Windows drive mount? e.g. `/mnt/c/...`

**Comment by eRuaro** [comment]
> Is the file located on a Windows drive mount? e.g. `/mnt/c/...`

Yep!

**Comment by aeschli** [comment]
It's a known WSL issue that file events are not reported on `/mnt/...`. We are waiting for a fix in WSL. Tracked in https://github.com/microsoft/vscode-remote-release/issues/5000.

It's recommended, also for performance reasons, to place projects on Linux file system (e.g. the home folder)
