### ISSUE TITLE
QuickFix (context menu) is losing focus (closing) automatically 

### ISSUE THREAD

**Issue by Tanato** [Microsoft/vscode#12531]
- VSCode Version: 1.5.3
- OS Version: Windows 10 AU
- Tested in C# code

Steps to Reproduce: 

1. Open QuickFix (Ctrl + .) right after a code is marked with red squiggly line.
2. Navigate between context options with arrows (the problem occour even without navigation).
3. Suddenly the context menu closes.

The problem don't occour if you wait a few seconds before open context menu.

[bug]

**Comment by chrmarti** [comment]
Reproduced by opening QuickFix before the error decoration is shown.

**Comment by jrieken** [comment]
Yeah - problem is that the fixes update on type (more precise marker updates) and that triggers a 'reshow' (which is hide). In now updates the menu in place:

![sep-26-2016 16-00-01](https://cloud.githubusercontent.com/assets/1794099/18836962/642f4ed2-8402-11e6-8915-f9ea748dc77e.gif)
