### ISSUE TITLE
Ability to trust all Remotehub repos

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#125399]
Currently a user can trust a parent folder making it unlikely that they see the workspace trust prompt very often. However, when using RemoteHub there is no concept of a parent folder and therefore the user receives the workspace trust dialog every time they open a new repo with no way for them to reduce the number of occurrences.

TL;DR Some version of Trust Parent for remotehub repos. Maybe trust all `user/` or `org/` repos? For example `microsoft/*` would be trusted.

**Comment by sbatten** [comment]
We are working to have the `getCanonicalUri` option on filesystemproviders which will turn remotehub uris into their github https uris. At that point you will be able to trust `/microsoft`

**Comment by sbatten** [comment]
@alexr00 @eamodio right now, when connected to a remote repo with remotehub, we can actually trust the parent path due to canonical uri support for remotehub. however, the simple file dialog will not let this happen as it says the file path does not exist. can that be overidden or fixed?

**Comment by sbatten** [comment]
@alexr00 I saw the change to fix #125055... unfortunately, that means that the picker cannot be used to trust parent organisations such as `/sbatten` or `/microsoft`. should I avoid using the picker then for remotehub? @eamodio  thoughts?

**Comment by sbatten** [comment]
@alexr00 if that's easy enough, that would useful, but I think the benefit of the picker is the inherent validation, @eamodio thoughts on being able to indicate if a path exists?

**Comment by sbatten** [comment]
We've opted for a simpler option which provides validation using the basic text input.

To verify:
1) Trust a repo using the button in the workspace trust editor
2) Use the pencil icon to edit the path of the trusted repo
3) Try trusting an organisation or user
4) Try trusting '/'
