### ISSUE TITLE
Unable to paste more than small snippets

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/vscode#125361]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2 (Current Stable)
- OS Version: ChromeOS 91, VSCode running inside Crostini

Steps to Reproduce:

1. Copy more than small snippet of text
2. Cannot paste into other files

This may or may not be related to a [similar issue raised today](https://github.com/microsoft/vscode/issues/125301), but basically if I try to copy and paste more than a small snippet pasting fails entirely.

It isn't a problem with copy (or the OS paste) as I am able to copy from VSCode and paste into gedit or into Chrome as per usual. Only pasting into VSCode fails.

This might be related to the fact that ChromeOS 91 has just been released which integrates Crostini copy-paste support with the ChromeOS native clipboard. ([Article on change](https://marketresearchtelecast.com/chrome-91-stable-linux-on-chromebooks-better-copy-paste/54551/))

**Comment by deepak1556** [comment]
Please check if the issue persists with latest stable `1.73`

**Comment by Jamesernator** [comment]
> Please check if the issue persists with latest stable `1.73`

No, this was fixed pretty quickly that I had forgotten I even submitted the issue.
