### ISSUE TITLE
Notebook getting started images don't seem to match the experience

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#125347]
Testing #125014

Jupyter

![image](https://user-images.githubusercontent.com/641685/120562934-6f701980-c3d5-11eb-9577-313dabf06f1e.png)

Colab

![image](https://user-images.githubusercontent.com/641685/120562883-52d3e180-c3d5-11eb-9fb9-3aa23cdec678.png)

**Comment by roblourens** [comment]
You can ignore the actual images, they are changing
