### ISSUE TITLE
Markdown layout issues in notebooks

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125393]
When using the default layout:

- depending on the font size / header type the folding indicator shows up with different offsets from the centerline/baseline of the font
- there should be sufficient spacing between the folding indicator and the first letter of the header so that the first letter of the header is align with the left border of a code cell

![image](https://user-images.githubusercontent.com/4674940/120656707-b4796780-c438-11eb-9033-4f23cd6b911c.png)

**Comment by kieferrm** [comment]
Ok, this one was weird because eventually I realized that I saw it in some windows and not in others. Turns out that I had `"notebook.experimental.useMarkdownRenderer": false` in my settings which caused this effected when a window with a notebook editor was restored. Once we get rid of old markdown rendering code, this issue is fixed.

**Comment by rebornix** [comment]
We don't use the builtin markdown renderer anymore, the webview based markdown renderer is turned on for all
