### ISSUE TITLE
Paste doesn't seem to take the latest copy

### ISSUE THREAD

**Issue by danchaseCTS** [microsoft/vscode#125301]
I'm having issues in vscode where if I try to copy/paste some code, it does not seem to take the latest copy all the time.

My actions: I use Ctrl-F to find the function I want to copy from, highlight the block with the mouse, and press-ctrl-c. I then use Ctrl-F to find the function I want to paste into, and hit Ctrl-V.

Expected result would be that it pasts what I copied onto the clipboard, but instead it pastes something *old* (as in, prior to the previous copy).

I tried to inspect the clipboard using an extension to show the clipboard entries, and the new item was definitely in it, but it was "skipping it". 

Yesterday it happened twice in a row, and did not resolve until I pasted into Notepad before the search step. I did this because I got tired of searching code again and finding my copy text for the third time, but amazingly enough, from that point on, copy/paste worked fine in the application!

This is happening more and more. I've disabled extensions, and have experienced the issue on multiple PC's (PC and work Laptop) and multiple versions of Windows (10 and 7). I assume it has something to do with the "Find" function, maybe something is moving the clipboard pointer somehow? 

I initially suspected key bindings until I was able to reproduce it using Right-Click/Copy. Also I find it strange that I could see the clipboard item in the stack and it had skipped it, and was doing this behavior until I pasted something into notepad, then it all cleared up?

I've edited this question a few times just to organize and clarify for you, also, as a developer I'm happy to help if anyone else is experiencing this, or can point me where to start looking!

**Comment by rebornix** [comment]
@danchaseCTS can you try run command Toggle Keyboard Shortcut Troubleshooting and share the log of both "copy" and "paste"/ctrl+v in the find input box?

**Comment by rebornix** [comment]
> Yesterday it happened twice in a row, and did not resolve until I pasted into Notepad before the search step. I did this because I got tired of searching code again and finding my copy text for the third time, but amazingly enough, from that point on, copy/paste worked fine in the application!



When you have a stable repro, does it mean

* ctrl+c in editor
* ctrl+v in find widget pastes wrong stuff

* ctrl+c in editor
* ctrl+v in notepad always pastes right stuff

if above two are what you are seeing, what did you see when

* ctrl+c in editor
* ctrl+v in find widget pastes wrong stuff
* ctrl+v in notepad, does it paste wrong entry or the correct one?

**Comment by danchaseCTS** [comment]
The related issue about small snippets is interesting, because in my case I'm normally copying a decent amount (1/2 screen or more) of text, but will use that to experiment. It seems the issue does not occur always, yesterday I went all day without a single (mis-paste?). The other thing to clarify is the keyboard from a ctrl-c perspective doesn't seem to be related at least, because it occurred to me the 2nd time when I right clicked and hit copy from the context menu. Perhaps paste Ctrl-V is affected somehow.

**Comment by Iqigai** [comment]
I have noticed a related issue with copy and paste on Windows 10: using the mouse right click option to copy and paste does not work in most elements including the jupyther console or the plugin information tabs for instance. However on the jupyter console the keybord shortcuts (Ctrl C, Ctrl V) work.
