### ISSUE TITLE
C structures autocomplete

### ISSUE THREAD

**Issue by felkar123** [Microsoft/vscode#12538]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

In C language:
>1. Autocomplete should offer just the variables that are in the structure, after typing a period (".") or an arrow ("->") for pointer structure instances.
2. When you in a .c file, autocomplete should show up with variables, definitions and structures that are declared in that file (and in its header file) first in the list and then these in include librarys

**Comment by chrmarti** [comment]
This is contributed by the C/C++ extension you have installed. Please file an issue with them.
