### ISSUE TITLE
While debugging cannot continue a process that is not in focus

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#125327]
Issue Type: <b>Bug</b>

Python extension developer here 👋. This seems to be a UI issue with VS Code.

Clicking on continue on a process that is not in focus (does not work). Note, the continue is not on the process that is currently in focus. Hitting continue on the process that is currently in focus works fine.
![image](https://user-images.githubusercontent.com/3840081/120373344-19b04a00-c2cd-11eb-8453-1a73e9964669.png)

## Steps to reproduce:
1. Create pyton file with code below:
```py
from concurrent.futures import ProcessPoolExecutor
from math import factorial

values = [2, 3, 4, 5, 6]


def fact_square(x):
    return factorial(x) ** 2 # break here


if __name__ == "__main__":
    result = []
    with ProcessPoolExecutor(max_workers=5) as executor:
        result = executor.map(fact_square, values)
```
2. Set breakpoint where it says "break here".
3. Start debugging.
4. When the breapoint hits check the Debug view > Call stack. Try to "continue" a process that is not currently in focus.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (46.93GB free)|
|Process Argv|C:\\GIT\\design\\discovery --crash-reporter-id 8a06823c-8219-469b-a5be-5ad36c5c7a1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-pull-request-github|Git|0.26.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.5.4
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vscode-remote-extensionpack|ms-|0.21.0
vscode-github-issue-notebooks|ms-|0.0.99
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
Thanks for steps. Looks like an issue on the VS Code side. Unassigning @weinand and I can investigate next week.

**Comment by isidorn** [comment]
@karthiknadig thanks again for filling this great issue. I have just pushed a fix, so you can try it out from Monday and let us know if it is indeed fixed for you.
Also let us know if there are more debug issues you are hitting, it is highly appreciated 👏
