### ISSUE TITLE
Consider triggering also on `deleteLeft`, `deleteRight`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125478]
https://github.com/microsoft/vscode/blob/d6db1362ea41df87a744fc75872c4ab2bfd8c3d8/src/vs/editor/contrib/inlineCompletions/inlineCompletionsModel.ts#L38

As a follow-up debt item, we should extract those ids into constants instead of copying them.

**Comment by hediet** [comment]
verification steps: Compile & Install sample Inline Suggestion extension [from here](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions).

* Type `if` and press Esc to close the suggest widget.
* Verify that an inline suggestion appears.
* Press Esc to hide the inline suggestion.
* Press backspace (delete left) to trigger the inline suggestion again.
* Verify the inline suggestion appears again.
