### ISSUE TITLE
Improve horizontal screen real-estate

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#12543]
- VSCode Version: Code - Insiders 1.6.0-insider (0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0, 2016-09-20T06:11:03.267Z)
- OS Version: Windows_NT ia32 10.0.14915

Steps to Reproduce:
1. Open code in left and right side editors
2. Observe the following real-estate usage. Suggestions follow.

![image](https://cloud.githubusercontent.com/assets/494055/18796085/8799463a-817c-11e6-9241-39deb27b5a90.png)

The blue lines mark the edges of the non-code sidebar for the right-side editor. The line numbers are rendered in dark grey in the same font as the code which is a good thing, no wasted space there. The light grey line to the left of the left blue line is the boundary of the scrollbar. No complaints there -- we can even see code through the scrollbar which is a major plus.

Problem areas are outlined by the red bars. Nothing seems to go in that space (that I've seen so far). The gap between the breakpoint markers and the code folding buttons is unnecessarily large. They are so different in appearance from the numbers there's no chance of confusing them. They can be closer together. When my view is three panels wide I'm losing what feels like a ton of screen space compared to other editors.

Another view which makes this problem more clear:

Set `"editor.lineNumbers": false`

![image](https://cloud.githubusercontent.com/assets/494055/18796404/f3ca7f08-817d-11e6-96ad-d19d22c3ed18.png)

Blue: 50 px for the activity bar (being discussed [here](https://github.com/Microsoft/vscode/issues/1105))
Green: 45 px for each of the editor's left margin areas - when they are not even displaying line numbers! There's nothing to see there. I'd assert we should not be using all of that horizontal real estate when there's nothing to see.

Let's assume side-by-side editing with two editor panels is a common scenario. Right now there is about 140px of Nothing-To-See-Here space (except when mousing over the margin, where you get the option to fold code and set breakpoints).

Some of this space can be saved as a no-brainer (it's just unnecessary padding):

![image](https://cloud.githubusercontent.com/assets/494055/18796857/00968004-8180-11e6-8647-c4384d1b8d1c.png)

Red bars above are unnecessary padding: 4px, 12px, 5px respectively. Zoomed view:

![image](https://cloud.githubusercontent.com/assets/494055/18796931/5d31024e-8180-11e6-890f-a2cd75482446.png)

Being able to [hide the activity bar](https://github.com/Microsoft/vscode/issues/1105) would save 50px for those who want to hide it.

Some languages don't support breakpoints. We can save another 10-12px per editor margin for those languages by not reserving that space for the breakpoint icons.

Maybe I'm not interested in folding any code? Add a configuration option or Command to toggle that ability and remove that part of the margin when it won't be used. This saves another 10-11px.

Thanks for listening! :)

**Comment by bgashler1** [comment]
May also help with this issue #8871 (placing caret difficult in some cases)

**Comment by alexandrudima** [comment]
```
"editor.glyphMargin": false,
"editor.folding": false,
"editor.lineDecorationsWidth": 0, // undocumented
"editor.lineNumbersMinChars": 0,  // undocumented
```

<img width="315" alt="image" src="https://user-images.githubusercontent.com/5047891/33169850-749e0826-d046-11e7-92b6-8953996a21a2.png">

Also, `"workbench.activityBar.visible": false` can be used.

**Comment by dilijev** [comment]
Copying those undocumented settings into my config didn't fix the issue for me.

![image](https://user-images.githubusercontent.com/494055/33285647-cb1241e4-d367-11e7-8812-5f7d83a63426.png)

**Comment by dilijev** [comment]
I found that these settings got rid of most of the margin space:

{
    "editor.lineNumbers": "off",
    "editor.glyphMargin": false,
    "editor.folding": false
}
