### ISSUE TITLE
Add a reference point feature

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#12549]
Could you add something like the main visual studio editor for debugging, but instead have it for reference points in code.  

*  123   <code>

123 = line number
*= reference to code on page to come back.

You already create reference points for searching for code or highlighting code.  This would just make it awesome!

**Comment by chrmarti** [comment]
Not sure I understand. Are you asking for a kind of bookmarks?

**Comment by soljohnston777** [comment]
Bookmarks is a way to describe it.  But a temporary place marker.  In C# you have a red dot for debugging.  I notepad++ you have a blue dot on the left for a placemarker to come back.

So you mark next to the code on the left and on the right side it shows a color to reference the line you are working on.  That way when you are fixing code and the code that you are fixing may be affect by a code a hundred lines above it, then you don't lose your place.

**Comment by chrmarti** [comment]
Thanks for clarifying.

**Comment by Bill-Stewart** [comment]
Here is a handy extension that may meet your needs: https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

**Comment by soljohnston777** [comment]
That extension works great!  Exactly what I was looking for!

**Comment by chrmarti** [comment]
Closing as this provided by an extension. Thanks guys!
