### ISSUE TITLE
can't delete multi-selected files 1.57.0

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#125464]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.57.0-insider (system setup)
提交: a62df5d6c53e844bfdc50694f943c3f34b6ff50e
日期: 2021-06-03T17:38:02.890Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. selection multi file
2. delete them
3. just delete the frist selected file and report an error
4. disable all exts and reload windows,
5. repeat step 1~3.

![delete_disable_all_exts](https://user-images.githubusercontent.com/1876302/120733459-cf6fd880-c519-11eb-8415-fd57c1dc4078.gif)

![delete](https://user-images.githubusercontent.com/1876302/120733465-d1399c00-c519-11eb-82ea-f1fe68aaa321.gif)

**Comment by heartacker** [comment]
BTW, stable version is working well

**Comment by isidorn** [comment]
This works just fine for me.
Can you repro if you disable all your extensions?

**Comment by heartacker** [comment]
> This works just fine for me.
> Can you repro if you disable all your extensions?

yes .it repro  when  disable  all ext

**Comment by heartacker** [comment]
so, nobody believes that this is an issue of v1.57?

**Comment by heartacker** [comment]
today， I update my stable version to 1.57.0. this issue reproduce. I still believe that this is an issue related version-1.57.0, not only the conflict with exts.
![image](https://user-images.githubusercontent.com/1876302/121617386-63e8b680-ca97-11eb-8115-f48cf5699320.png)

**Comment by heartacker** [comment]
run with `--disable-extensions` ,still broken.

版本: 1.57.0 (system setup)
提交: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
日期: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.14393

also, delete one file will show the same dialog

**Comment by heartacker** [comment]
HI, my workmate can reproduce this issue, and seems that we have the same windows version `1607 LTSB`
and my another workmate‘s PC works well with windows version `1809 LTSC`.

**Comment by heartacker** [comment]
after upgrading to 1.58.0,this issue still alive at    `Windows 1607LTSB`，
1. delete a file or multifiles
2. the only file or frist selected file will be deleted
3. show the messagebox that `We can't move to recycle_bin`

![image](https://user-images.githubusercontent.com/1876302/125195519-8fbeae00-e288-11eb-97ee-2911c9d3ee59.png)

4. recommand me to Permanently delete, click delete, show a messagebox that file does not exit

![image](https://user-images.githubusercontent.com/1876302/125195525-95b48f00-e288-11eb-8da4-dffcc0189d0c.png)

**Comment by 363797271** [comment]
I also had this problem after vscode was updated to version 1.58.

**Comment by heartacker** [comment]
no，it's bug!!!!

**Comment by wsytlzdh** [comment]
> after upgrading to 1.58.0,this issue still alive at `Windows 1607LTSB`，
> 
> 1. delete a file or multifiles
> 2. the only file or frist selected file will be deleted
> 3. show the messagebox that `We can't move to recycle_bin`
> 
> ![image](https://user-images.githubusercontent.com/1876302/125195519-8fbeae00-e288-11eb-97ee-2911c9d3ee59.png)
> 
> 1. recommand me to Permanently delete, click delete, show a messagebox that file does not exit
> 
> ![image](https://user-images.githubusercontent.com/1876302/125195525-95b48f00-e288-11eb-8da4-dffcc0189d0c.png)

the same problem， now it is bother me 

![image](https://user-images.githubusercontent.com/54626202/130717143-ae339242-468a-490d-a734-d13d72bef856.png)
```
版本: 1.60.0-insider (system setup)
提交: 5f19eee5dc9588ca96192f89587b5878b7d7180d
日期: 2021-08-24T19:41:58.784Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
```
```
版本: 1.59.1 (system setup)
提交: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
日期: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.14393
```
