### ISSUE TITLE
Long text wraps in debug console cuts CJK strings

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1254]
![image](https://cloud.githubusercontent.com/assets/5047891/11780431/272e576c-a262-11e5-96fe-7332afa29ebf.png)

Test file:
```javascript

var str1 = "三代之時，天下有國千萬，言語不通。周既王，始有雅言。諸子著作，皆以雅言。及周道微，天下紛亂，言語異聲，文字異形。尤是楚語至不同也。秦始皇帝混一車書，獨用秦篆，各地方言日合。然至於許慎之世，說文解字之所錄，亦有同義而音異之字，多有「某地曰某為某」之訓。蓋天下文字雖一，而言語未統也。此上古音也。古語於語法異於今音，可見諸尚書。"


var str2 = "Chinese (汉语 / 漢語; Hànyǔ or 中文; Zhōngwén) is a group of related but in many cases mutually unintelligible language varieties, forming a branch of the Sino-Tibetan language family. Chinese is spoken by the Han majority and many other ethnic groups in China. Nearly 1.2 billion people (around 16% of the world's population) speak some form of Chinese as their first language."

console.log(str1);
console.log(str2);

console.log('DONE');
```

Cheap solution (done in terminals for example):
 * measure also a typical wide character width. e.g. : https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/config/configuration.ts#L70
 * when computing the width of the string use the wide character width where applicable. e.g. : https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/viewModel/characterHardWrappingLineMapper.ts#L174
 * this will of course not help with all languages (like arabic, thai), but would be a first improvement.

**Comment by isidorn** [comment]
@alexandrudima thanks for the great pointers! Should we somehow reuse these utility methods? Or is it easier that I just mimic what you are already doing?

**Comment by alexandrudima** [comment]
@isidorn I have extracted `isFullWidthCharacter` in https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L420 . I suggest we share at least that, I wouldn't try to share the measuring code, as I need to do quite some tricks in the editor case.

**Comment by isidorn** [comment]
Awesome, thanks!
