### ISSUE TITLE
Trace statements are not shown in the logs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125419]
- Open Window log
- Enable log level to trace
- Execute some commands

🐛 Trace statements are not shown 

Stable:

![Kapture 2021-06-03 at 19 40 54](https://user-images.githubusercontent.com/10746682/120688944-dc51e500-c4a3-11eb-9788-c2a795b7c220.gif)

Insiders:

![Kapture 2021-06-03 at 19 42 19](https://user-images.githubusercontent.com/10746682/120688976-e542b680-c4a3-11eb-9cba-0137dac0efd4.gif)

This seems to be a regression caused by https://github.com/microsoft/vscode/issues/123856
We are now flushing only when info statement is logged:

https://github.com/microsoft/vscode/blob/49187c4e7854e427dac8fa0128622b935530cb83/src/vs/platform/log/node/spdlogLog.ts#L14-L14

Hence the trace statements are not getting flushed and hence not shown in the logs

**Comment by rzhao271** [comment]
I guess an issue is that there are no info statements coming in, so nothing is being flushed.
I'll switch it to flush on trace for now.

**Comment by rzhao271** [comment]
\closedWith 062401745a22d0bda7f4b9a560838f238438df1b

**Comment by deepak1556** [comment]
Since we rely on level based flushing on the internal implementation, we should always keep the lowest level as default to avoid similar issues.
