### ISSUE TITLE
tsconfig.json options not applied if files section doesn't use extensions

### ISSUE THREAD

**Issue by nomaed** [Microsoft/vscode#12547]
- VSCode Version: 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

- Create an empty directory
- Run `npm init` and then `npm i --save-dev typescript`
- Run `tsc --init` (or `./node_modules/.bin/tsc --init`)
- Create `test.ts` and add code that's using `Map` and `Set`:
```typescript
const foo = new Map();
const bar = new Set();
```
- Edit `tsconfig.json`, set `target` to be `es2015`, and add `files` section with the test script (`test`) without its extension:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "files": [ "test" ]
}
```
- Run `tsc` (or `./node_modules/.bin/tsc`), see that `test.js` is created with exactly the same code, as expected, and no warnings or errors have been seen.

At this point, `tsc` compiled the file `test` while adding the default `.ts` extension when resolving.

Now adding VSCode into the picture:

- Run `code .` to open VSCode with the current testing directory loaded. Either that, or from GUI go to `Files > Open` and loaded the current directory.
- Open `test.ts` file. At this point VSCode may ask about TypeScript version, if TypeScript 2.0 was installed by npm. It doesn't matter whether you choose TS 2.0 or TS 1.8, both produce the same behavior.
- Observe `Map` and `Set` being unrecognized:
<img width="583" alt="screen shot 2016-09-23 at 22 31 53" src="https://cloud.githubusercontent.com/assets/9551921/18800492/93defa6e-81dd-11e6-8511-992ec277e43e.png">

The observed behavior is inconsistent with `tsc`.

Now, to "fix" it:
- Open `tsconfig.json` and change the `files` section to have the full file-name with its extension `test.ts`.
- Reload TypeScript project or reload VSCode, and open `test.ts`. Everything is fine now.
<img width="612" alt="screen shot 2016-09-23 at 22 30 14" src="https://cloud.githubusercontent.com/assets/9551921/18800457/56e30d9e-81dd-11e6-858d-291a121c4b5b.png">

However, I would expect vscode behavior in this to be the same as of `tsc`.

**Comment by waderyan** [comment]
@nomaed thank you for opening this issue and for providing a thorough issue description. 

@dbaeumer I have verified this issue with Insiders. Please advise next steps.

**Comment by dbaeumer** [comment]
@waderyan the errors are produced by the tsserver. I would ask the TS team what the expect in this case. There is API that we can define the ScriptKind for files that don't have an extension however test.ts does have one and is clearly treated as a TS file inside the tsserver. However the tsconfig.json is not applied which I think is a bug in the tsserver itself.

**Comment by waderyan** [comment]
ping @mhegazy

We have a question about this issue. See @dbaeumer's comment above and the OP's description of the problem.

**Comment by mhegazy** [comment]
This looks like a tsserver bug.

**Comment by waderyan** [comment]
@mhegazy recommend moving it over?

**Comment by mhegazy** [comment]
yes please.

**Comment by waderyan** [comment]
Closed and migrated to https://github.com/Microsoft/TypeScript/issues/11194
