### ISSUE TITLE
In the 6/3 build of VSCode - Insiders Notebook Show Cell Status Bar setting defaulting to 'hidden'

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#125403]
Does this issue occur when all extensions are disabled?: No (Jupyter extension required)

- VS Code Version:
![image](https://user-images.githubusercontent.com/812783/120667741-a16b9500-c442-11eb-9509-306407ff5948.png)

- OS Version: MacOS 11.3.1

Steps to Reproduce:

1. Open a notebook with the jupyter extension
2. Execute a cell

Expected: See Cell Status Toolbar (green check / execution time)
Actual: Cell Status Toolbar is hidden

This change seemed to hit just in this build. I've not customized the Show Cell Status Bar setting, but it is now defaulting to hidden for me. 
![image](https://user-images.githubusercontent.com/812783/120668332-379fbb00-c443-11eb-9b56-8621db0994f6.png)

**Comment by brettfo** [comment]
Hiding the status bar by default is particularly detrimental to polyglot notebooks (e.g., .NET Interactive) because the language picker isn't shown so the user has no way to change the cell language from C# to F#, etc.  The discoverability of this is very low.

**Comment by roblourens** [comment]
This wasn't intentional
