### ISSUE TITLE
Initial size of the table in the trust editor is incorrect

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#125406]
- Open a New Window
- Open the Trust Editor

Notice that the Path column is clipped. Also when you have many entries in the table the table cannot be scrolled.

![image](https://user-images.githubusercontent.com/172399/120673683-af95d180-c493-11eb-8701-56585d136c0b.png)

**Comment by sbatten** [comment]
fixed via https://github.com/microsoft/vscode/commit/df59dc8470a442cb781101ed74a94f2274ca14b2
