### ISSUE TITLE
Missing Accept action in inline completion hover

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125472]
IMHO we should add an "Accept" action to make <kbd>Tab</kbd> discoverable as an accept keybinding:

![image](https://user-images.githubusercontent.com/5047891/120757602-0beb0680-c511-11eb-8fe0-821dd42d9119.png)

**Comment by hediet** [comment]
verification steps: Compile & Install sample Inline Suggestion extension [from here](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions).
* Configure `"editor.inlineSuggest.enabled": true` in your settings
* Type `if`.
* Hover on the inline suggestion.
* Verify that "Accept" is shown.
* Click on it & verify that the inline suggestion is accepted.

**Comment by isidorn** [comment]
Works fine, opened this related issue -> https://github.com/microsoft/vscode/issues/125524
