### ISSUE TITLE
Custom hover pointer overlaps with element

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#125495]
I'm using the hover service with pointer = true

![image](https://user-images.githubusercontent.com/6461412/120790576-6d23d180-c533-11eb-8c8f-4bc5a40de411.png)

I wonder if it weren't better if the arrow does not overlap with the element

**Comment by sandy081** [comment]
Its same with activity bar hovers

![image](https://user-images.githubusercontent.com/10746682/120792160-639b6900-c535-11eb-8667-6be1a0b464fe.png)

Also similar in Slack

![image](https://user-images.githubusercontent.com/10746682/120792348-ad844f00-c535-11eb-8feb-affbfc9adabb.png)

![image](https://user-images.githubusercontent.com/10746682/120792394-c260e280-c535-11eb-84b7-922b6d6abd6e.png)

@misolori Your suggestion would be helpful

**Comment by misolori** [comment]
I think it's fine if overlaps

**Comment by bpasero** [comment]
I find this a bit weird, wouldn't expect the beak to bleed into the item:

![image](https://user-images.githubusercontent.com/900690/122234630-4fecec80-cebd-11eb-87ef-59773ac5d52b.png)

**Comment by joaomoreno** [comment]
100% agree, it breaks the hover illusion.

**Comment by misolori** [comment]
Given the feedback here + in our ux channel, let's try to tweak the positioning.

**Comment by Tyriar** [comment]
Fixed in cc39291fd96787a0d4dd5cbc1c42b25d671ff337
