### ISSUE TITLE
Allow opening the same folder in the explorer view as another instance of VS Code

### ISSUE THREAD

**Issue by todddeweerd** [Microsoft/vscode#12541]
- VSCode Version:1.5
- OS Version: Windows 10

Steps to Reproduce:

1. Open the explorer window to a folder location
2. Open a new instance of VS Code. Attempt to open the same folder in explorer and VS Code activates the previous instance.

This behavior isn't desired if I'm trying to do a find in files and I need to compare the results. A setting to disable this behavior would be nice. I would like to have two instances of VS Code open to explore the same folder location.

**Comment by rozzzly** [comment]
Would be very nice to spawn a second window fore the _same_ workspace session thats composed of just the editor(s) (only one sidebar is needed imho). 

This would be great for multi-monitor setups

**Comment by chrmarti** [comment]
Tracked as #2686
