### ISSUE TITLE
Checkbox to preserve opened editors (always open the next editor in a new tab)

### ISSUE THREAD

**Issue by AlexHelmes** [microsoft/vscode#125492]
One checkbox to open the editor ALWAYS in a new tab - either from Explorer, or from Ctrl+P, or from search results. Sometimes it opens in a new tab, sometimes replaces the current editor. All the checkboxes Open files in new Window are set, I've tried with and without tab preview enables - actually, it's annoying me for years in VsCode and it would be great to have a definite possibility to preserve the opened editors. Thanks

**Comment by isidorn** [comment]
```
"workbench.editor.enablePreview": false
```

**Comment by AlexHelmes** [comment]
Thanks a lot!
