### ISSUE TITLE
Notebook layout action names

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125452]
Right now, as a user I'm not quite sure what the difference between the two actions is. To make it more clear I propose the following renames:

`Select Notebook Layout` -> `Select between Notebook Layouts`

`Configure Notebook Layout Settings` -> `Customize Notebook Layout`

**Comment by misolori** [comment]
Verified
<img width="325" alt="CleanShot 2021-06-04 at 16 07 49@2x" src="https://user-images.githubusercontent.com/35271042/120870877-06141600-c54f-11eb-84fb-a6843e09ced9.png">
