### ISSUE TITLE
Default Shell Always Powershell even when set

### ISSUE THREAD

**Issue by mooseh** [microsoft/vscode#125483]
- VS Code Version: 1.56.2
- OS Version: Windows 10 Pro 10.0.19042 Build 19042

Steps to Reproduce:

1. Open VSCode
2. press ctrl + '  (powershel will open)
3. press ctrl +shift + P and type "select default terminal"
4. Choose anything other than powershell
5. close VSCode
6. repeat steps 1 and 2 (it will be powershell again even though you set it to something else)

**Comment by datvuong** [comment]
Related issue #124805

**Comment by tylov** [comment]
Two additional notes:
- It may open the chosen default terminal profile once or twice after reopening vscode, but will eventually open the PS profile.
- It does remember the default profile when pressing + (New Terminal).

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by tylov** [comment]
I cannot reproduce it with Insiders build on neither my laptop or desktop, so it definitely seems fixed.

Note, I only had this bug on my new laptop (R5 4700U cpu) in V1.56.2 (user setup),  but not on my desktop (Ryzen 7 2700x).
