### ISSUE TITLE
"notebook.cellBorderColor" colors output backgrounds?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125459]
![image](https://user-images.githubusercontent.com/8586769/120727651-ef5aba00-c48f-11eb-8788-d23e21b68118.png)

**Comment by JacksonKearl** [comment]
I guess `"notebook.outputContainerBackgroundColor"` defaults to the border color? Changing that resolves the issue so I'm not sure if this is expected.

**Comment by rebornix** [comment]
Yeah this is as designed but we should definitely consolidate them.

**Comment by rebornix** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/125549
