### ISSUE TITLE
Debugger not closing eveb after clicking disconnect

### ISSUE THREAD

**Issue by iamraghav** [microsoft/vscode#125471]
After running the debugger (connect to remote) option, when I am clicking on disconnect it doesn't close.

![image](https://user-images.githubusercontent.com/29648128/120756143-82e1c880-c52c-11eb-9fe6-e0eddfd51a0b.png)

**Comment by weinand** [comment]
What debugger are you using?

**Comment by iamraghav** [comment]
> What debugger are you using?

the default one which is provided by VS Code

**Comment by weinand** [comment]
/jsDebugLogs

Please provide reproducible steps and the js-debug logs
