### ISSUE TITLE
Extension Icon showing incorrect count

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12540]
- VSCode Version: 1.6.0 Insider
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open VSCode with some extension installed
2. All of them are up to date, but VSCode is showing 2 in the extension icon

![image](https://cloud.githubusercontent.com/assets/4033249/18795535/e423fd62-8179-11e6-9b76-72856dcbeaeb.png)

**Comment by sandy081** [comment]
Related to #12507
