### ISSUE TITLE
ctrl+up or down should move cursor 5 lines up or down

### ISSUE THREAD

**Issue by biermeznicolas** [microsoft/vscode#125491]
**current behavior :** 
ctrl+up or down move the editor view of one line

**expected behavior :** 
ctrl+up or down move the cursor five lines up or down

**Comment by alexdima** [comment]
This can be done using the following in `keybindings.json`:
```
[
{
    "key": "ctrl+down",
    "command": "cursorMove",
    "args": {
        "by": "wrappedLine",
        "to": "down",
        "value": 5
    },
    "when": "editorTextFocus"
}
]
```
