### ISSUE TITLE
Trusting LiveShare session causes '/' to be trusted

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125453]
1. Start LiveShare of msft/vscode in one window
2. In different window, join the session
3. See request for trust, Manage Trust, then click the Trust button
4. See that `/` has been trusted

I note that when I open the workspace folder config file, I see:
```
{"folders":[{"uri":"vsls:/","name":"vscode"}],"settings":{"vsliveshare.join.reload.workspaceId":"A47ECCA424D135C1535B3F600E6CD66174B0","vsliveshare.join.reload.workspaceFolder":"/var/folders/4x/stmrc1tj4wx8j31phlphkvvh0000gn/T/vsliveshare-tmp-A47ECCA424D135C1535B3F600E6CD66174B0","files.hotExit":"off"}}
```

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/120721380-920c3c00-c482-11eb-9acd-b172f133180b.png)

**Comment by sbatten** [comment]
fixed with trusting of VFS paths
