### ISSUE TITLE
Workspace trust dialog learn more link can be on its own line

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#125429]
Repasting from https://github.com/microsoft/vscode/issues/125353#issuecomment-854052401:

Should "See our docs to learn / more." be on its own line in the dialog? The way it currently is with the newline makes it easy to miss.

**Comment by sbatten** [comment]
Hmm, for the dialog? I don't think we want to overload with more lines of text. A button was the alternative but it means the user cannot open the docs without closing the dialog.

**Comment by rzhao271** [comment]
Current dialog LGTM
