### ISSUE TITLE
Overall run or execute keyboard shortcut

### ISSUE THREAD

**Issue by claell** [microsoft/vscode#125401]
When using extensions like the Python extension, there is a button to execute open files. However, at least in case of the Python extension there is no default keyboard shortcut for this often used action.

I created an issue about this for the extension (https://github.com/microsoft/vscode-python/issues/16340) and a reason for them to not provide a default shortcut is to avoid interference with shortcuts from VS Code or other extensions.

Since I assume that there are multiple extensions offering something like the run button of the Python extension, it might help to have a global (and default) shortcut for this.

**Comment by isidorn** [comment]
There is, Ctrl + F5.
Here's the command id in case you want to customise the keybinding `workbench.action.debug.run`

**Comment by claell** [comment]
Interesting, I wasn't aware of that. However, it doesn't exactly do the same as normally running the Python file with the button from the extension. Apparently, there is no shortcut for a normal run (compared to the debug run)?

**Comment by luabud** [comment]
@isidorn how about for commands added to new play button API from VS Code? Would that need to be defined on the extension's end?

**Comment by isidorn** [comment]
@luabud yes these command also need to be defined on the extension's end and to have a keybinding.

@jrieken @weinand I believe we do not have a unified keybinding story for the Editor Title Play Button. But it might make sense to have something which would always run the last one selected by the user?

**Comment by weinand** [comment]
@isidorn yes, having a keybinding for a "default run" would make sense. I will create an issue for this.

**Comment by isidorn** [comment]
@weinand thanks

**Comment by claell** [comment]
(in theory we could use this issue for it, since that is what it was about, at least in spirit)

**Comment by weinand** [comment]
My plan is to propose a run button UI that has a notion of a "default run action" (and a way to change that). 
Only if we have such a thing we can introduce a keybinding for the "default run action".

**Comment by weinand** [comment]
OK, I found #117722 which covers already what I wanted to propose.
