### ISSUE TITLE
Perf improvement

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#125427]
Consider doing something like this:
https://github.com/microsoft/vscode/blob/0f8c499d1014b9079f01a63c097cc2354400e9ed/src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts#L51-L55

instead of:
https://github.com/microsoft/vscode/blob/8f3a47cc88c2745feed8c1506e93c8dae2082e62/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L370-L376

**Comment by Tyriar** [comment]
The slight perf benefit probably isn't worth the extra variable member var on terminal service.
