### ISSUE TITLE
Getting Started: Cannot scroll to bottom of content

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125400]
This is the lowest I can scroll to:

<img width="1117" alt="Screen Shot 2021-06-03 at 7 59 57 AM" src="https://user-images.githubusercontent.com/2193314/120666817-bf84c580-c441-11eb-9493-cc37cc9c9505.png">

When I increase the size of the webview I can see more, but it should still have a little bit of a margin:

<img width="701" alt="Screen Shot 2021-06-03 at 8 00 44 AM" src="https://user-images.githubusercontent.com/2193314/120666885-cf040e80-c441-11eb-8dc1-6691e52041af.png">

**Comment by rzhao271** [comment]
@JacksonKearl I'm unable to see some of the preview images when going through the later steps in the Luna Paint getting started.

Here's a pic of what I'm seeing:
![noprev](https://user-images.githubusercontent.com/7199958/144500582-2f3b2079-44b9-4f00-91e9-9e873857a518.PNG)
