### ISSUE TITLE
Bad workspace trust layout

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#125435]
1. Reload the window (seems to only happen the first time I open trust)
1. Have a split view
2. Manage Workspace Trust
3. The folders are truncated with the "Actions" area being giant. I can't resize the "Path" column, nor is there a tooltip for me to see what the paths are, so I'm stuck

![](https://memes.peet.io/img/21-06-1aeb9f04-cfe0-466a-b85d-f7b09fb91046.png)

+ I think we should always have a tooltip on the folder, since truncation is possible for any sufficiently-long path.

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/125406
