### ISSUE TITLE
Provide ability to disable Notebook start page when running tests

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#125436]
Currently this steals editor focus and our tests fail as a result of this (window.activeNotebookEditor is undefined after we open notebooks).
The tests are complex and we can't just rely on a return value of `openNotebookDocument or the like`, these are end to end tests in Jupyter extension.

Is there a way way to disable this start page?

@rebornix /cc

![image0](https://user-images.githubusercontent.com/1948812/120703758-90367e80-c46a-11eb-90a6-ad156efde5f3.jpg)

**Comment by roblourens** [comment]
We are disabling this for the release so we don't have to worry about it for now.

In the future we can keep the setting or add a CLI flag that you can pass

**Comment by joyceerhl** [comment]
Just to confirm @roblourens did you mean the notebook start page is being disabled for the upcoming release?

**Comment by roblourens** [comment]
Yesterday I meant just the auto-open, but this morning we decided to not show the profile picker on the getting started page at all for this release. It will be back next month.

**Comment by roblourens** [comment]
Not sure whether the auto-open is coming back. I'll close this. If it comes back we would definitely need a way to disable it.
