### ISSUE TITLE
Allow theming notebook output borders

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125462]
I'd like to have the output borders be black to match the rest of my theme.

![image](https://user-images.githubusercontent.com/8586769/120728375-9db32f00-c491-11eb-94fc-9aabdc0ec0ea.png)

**Comment by rebornix** [comment]
We need some design for this to conslidate the theme colors, as it's not clear yet what color should the border between editor and output use.

**Comment by rebornix** [comment]
Unassigning myself for this to help me keep my inbox short, but we track this in https://github.com/microsoft/vscode/issues/125549

**Comment by misolori** [comment]
Verify that you can set `notebook.outputContainerBorderColor` and that the left/right/bottom borders appear:

![image](https://user-images.githubusercontent.com/35271042/133165171-eb262ffb-4e0b-4742-a610-a7d91341e1b5.png)

**Comment by DonJayamanne** [comment]
@misolori Doesn't seem to work for me, the setting `notebook.outputContainerBorderColor` is not a valid configuraiton item (no intellisense either).

Tried the following settings:
```json
	"notebook.outputContainerBorderColor": "#ff0033"
    "notebook.outputContainerBorderColor": {
        "dark":"#ff0000"
    }
```
![Screen Shot 2021-09-28 at 11 01 41](https://user-images.githubusercontent.com/1948812/135141266-a0a75366-03e8-43de-b48c-31ed8bc40271.png)

**Comment by misolori** [comment]
@DonJayamanne you actually have to use the `workbench.colorCustomizations` setting to customize the color token:

```json
  "workbench.colorCustomizations": {
    "notebook.outputContainerBorderColor": "#ff0000",
  }
```
