### ISSUE TITLE
Terminal sticks to sidebar

### ISSUE THREAD

**Issue by Akshaykoushik06** [microsoft/vscode#125499]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-insider (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Open side bar (Ctrl + B by default)
2. Open terminal (Ctrl + ` by default)
3. Set the terminal panel to right (right click on terminal -> select 'Move Panel Right')
4. Resize the terminal - drag it completely to left so that only the side bar and terminal occupy the screen
5. Release the left mouse button
5. Now try to drag the terminal to right again
6. Terminal still sticks to the sidebar and hence not revealing the code area

**Comment by sbatten** [comment]
It's unclear that we should undo this "sticking"... If you don't release the mouse you can undo by moving back to the right, however, once you've released, we assume you want a maximized terminal (no editor) and there is no maximum width for the side bar. You can however, unstick the panel by using the chevron in the top right to "Toggle Maximized Panel"
