### ISSUE TITLE
Ubuntu us-colemak keyboard layout not working CapsLock(Backspace) in code

### ISSUE THREAD

**Issue by rayshoo** [microsoft/vscode#125467]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: 18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021

Steps to Reproduce:

1. install Ubuntu 18.04 LTS Gnome Desktop X11
2. Set Keyboard Layout colemak US
3. install visual code with snap
4. other process works CapsLock(Backspace), but code doesn`t

**Comment by alexdima** [comment]
Could you please take a look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings and see if any of those situations apply to you?

**Comment by rayshoo** [comment]
Thank you so much!
I installed Ubuntu on bare metal, not a virtual environment, but the link you gave me helped me to solve this problem.
> solution: use "keyboard.dispatch": "keyCode" in your settings and restart VS Code.
