### ISSUE TITLE
VSCode automatic update fails 

### ISSUE THREAD

**Issue by sev3ryn** [Microsoft/vscode#12544]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Click Update Now in prompt "Visual Studio Code will be updated after it restarts."
2. After VSCode restarted prompt "Visual Studio Code will be updated after it restarts." appears again and in "About Visual Studio Code" neither version nor related commit has been changed. 

Are there any update logs? And does Visual Studio Code store files outside of ~/Application Support/Code - maybe filesystem permissions are missing.

**Comment by fibric** [comment]
I don't have this issue. Neither Code nor Code-Insiders behaved that way.

macOs 10.12.1 Beta (16B2327e)
Version 1.6.0-insider (1.6.0-insider)
Version 1.5.3 (1.5.3)

I don't need to authorize myself when putting apps in `/Applications` no changing files in `~/Library/**`

**Comment by joaomoreno** [comment]
Me neither... but some users do...

#3520
