### ISSUE TITLE
ctrl+shift+E should be a toggle

### ISSUE THREAD

**Issue by biermeznicolas** [microsoft/vscode#125488]
**current behavior :** 

- ctrl+shift+E :  open the explorer and focus on the explorer
- ctrl+shift+E a second time :   focus the editor

**expected behavior :** 

- ctrl+shift+E :  open the explorer and focus on the explorer
- ctrl+shift+E a second time :   close the exporer and focus the editor

expected behavior should work for all the elements in the side bar and the panel

**Comment by isidorn** [comment]
We will not change this. Please use Ctrl + B to toggle the side bar

**Comment by biermeznicolas** [comment]
The panel work like that so it would be consistent for the side bar to have the same behavior but ok :(
