### ISSUE TITLE
Better/shorter name for changing renderer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125490]
* have a notebook with output
* select the `...`
* this doesn't read easy: "Chose a different output mimetype" 

How, about: "Change Presentation"

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1794099/120785054-0a2f3c00-c52d-11eb-97a8-79e025accef1.png">

**Comment by roblourens** [comment]
Have no idea how we describe this to the user

**Comment by IanMatthewHuff** [comment]
FWIW I don't believe that Jupyter and JupyterLab actually let you configure this from the UI, pretty sure it's just a priority order thing. JupyterLab had a request for this type of UI here.
https://github.com/jupyterlab/jupyterlab/issues/3038#issuecomment-351443367
Naming does seem tricky. My guess is from the Jupyter world anyone who would actually know or care to change this might understand mimetypes, but the current naming also doesn't work for a scenario like this:
![image](https://user-images.githubusercontent.com/812783/120862243-7d40ae80-c53d-11eb-849b-34cdd39cab21.png)
Here one of my options is not changing the mime type, but instead changing the renderer used to handle the same mimetype. So maybe something more generic like @jrieken suggested could be good? "Change Presentation" could encompass changing the selected mimetype, changing the renderer for the same mimetype and also would better hint to a user who does not know what a mimetype is what this might do. "Change (or Select) Output Rendering"  might be another option.

**Comment by roblourens** [comment]
I'm not crazy about the word "mimetype" as a user-facing word. I like 

- "change presentation"
- "change renderer"
- "select output renderer"

etc

**Comment by jrieken** [comment]
:+1: for "Change Presentation"

**Comment by tanhakabir** [comment]
"choose output representation" for me

**Comment by rchiodo** [comment]
+1 on "choose output presentation". Feels like that's what the user is trying to choose.
