### ISSUE TITLE
restricted trust status bar item should use rich hover  

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#125408]
The restricted trust status bar item should use a similar rich hover as is used in the remote indicator

This is the current hover
![image](https://user-images.githubusercontent.com/172399/120676000-e240c980-c495-11eb-9506-87e5f1dd038b.png)

This is the remote indicator hover for remote repositories
![image](https://user-images.githubusercontent.com/172399/120676383-3f3c7f80-c496-11eb-82cd-5a80ea6436e4.png)

**Comment by aeschli** [comment]
@lszomoru @sbatten FYI

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/120790220-ef5fc600-c532-11eb-88dd-b973ab06e01e.png)

**Comment by aeschli** [comment]
I filed https://github.com/microsoft/vscode/issues/125495 to ask if there should be more space between hover and statusbar.

**Comment by aeschli** [comment]
Added a link to manage trust:

![image](https://user-images.githubusercontent.com/6461412/120793718-8b8bcc00-c537-11eb-9fcd-67d7b0930f23.png)

There are now many possibilities to design the hover. Codicons, even a action toolbar. @misolori
