### ISSUE TITLE
Bring back onDidCloseNotebookDocument

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#125409]
Some notebooks like the [Kusto Notebooks](https://github.com/notebookPowerTools/vscode-kusto) depends on `onDidCloseNotebookDocument` to clean up any connections and dispose of anything important for the Notebook opened.

This isn't possible now and the closest workaround is to use `onDidSaveNotebookDocument` and maybe in the extension `deactivate` function to do any leftover clean up which isn't ideal.

**Comment by DonJayamanne** [comment]
I think the Kusto notebooks extension hasn't been updated to use the latest API.

**Comment by tanhakabir** [comment]
@DonJayamanne I was working on that now

**Comment by jrieken** [comment]
It's not gone, it has been moved to the `workspace` namespace: `vscode.workspace.onDidCloseNotebookDocument`
