### ISSUE TITLE
Consider moving profile detection to renderer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125443]
@meganrogge found an [issue ](https://github.com/microsoft/vscode/issues/125440)when verifying https://github.com/microsoft/vscode/issues/121470 where the root cause seems to be that `IConfigurationService` as run on the shared process (common/configurationService.ts) does not depend on workspace trust, which means the workspace profiles aren't being detected properly.

We're going to workaround this by passing whether the workspace is trusted and then inspect `userValue`/`workspaceValue` like we used to but it would be much easier and less error prone if things just worked as expected on the shared/server processes. A solution could be to have a barebones workspace trust service on these processes that just mirrors the information on the renderer and fires events as needed.

**Comment by sandy081** [comment]
`IConfigurationService` does not have access to workspace settings in shared process as it does not have access to workspaces. It has access to only user settings. Same with `IConfigurationService` in main process. So, I do not think it needs to be aware of workspace trust.

> We're going to workaround this by passing whether the workspace is trusted and then inspect userValue/workspaceValue

I am wondering how you are accessing workspace values in shared process? They shall be always undefined.

**Comment by Tyriar** [comment]
I guess that's actually the issue we're seeing then, is there any reason why they would not have access to workspace settings? Otherwise we need to do a bunch of stuff manually to pass it through to the shared proc/server.

**Comment by sandy081** [comment]
> is there any reason why they would not have access to workspace settings? 

As you know, shared process is not per window and it is common for all windows and so there can be multiple workspaces. 

Can you please elaborate your use case?

**Comment by Tyriar** [comment]
Yeah I can see how that would get complicated.

Terminal profiles get evaluated on the shared process or server right now, it moved over from the extension host recently. I'm thinking maybe we should now move it to the renderer and use the file service and fetch the environment via IPC if needed, then evaluate each profile async with Promise.all to avoid waiting for many round trips to the server. I'll reassign this to us as a debt item, thanks for the info.

**Comment by Tyriar** [comment]
We're consolidating more and more of this sort of thing in the pty host, not the renderer, so I think the current way it's done is good for now.
