### ISSUE TITLE
Split terminal lacks scrollbar

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#125460]
Issue Type: <b>Bug</b>

**Repro**
1. On MacOS
1. Open terminal
1. EDIT: Move tabs to left
1. Run a comment with lots output so it scrolls
1. Split the terminal
1. Make the split terminal scroll too with lots of output

**Bug**
For me, the original terminal (the one on the left) now no longer has a scrollbar 

<img width="1228" alt="Screen Shot 2021-06-03 at 5 17 05 PM" src="https://user-images.githubusercontent.com/12821956/120727674-feda0300-c48f-11eb-998e-6974b9f7731c.png">

Hovering over the terminal or interacting with it does not make the scrollbar show up

VS Code version: Code - Insiders 1.57.0-insider (Universal) (a62df5d6c53e844bfdc50694f943c3f34b6ff50e, 2021-06-03T17:36:36.265Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--log trace --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
Can repro only with tabs on left

**Comment by wcerfgba** [comment]
Ah I have a similar issue, although I am on Linux and the scrollbars are visible on all _additional_ split terminals (not the first terminal) but only if the tabs pane is visible: if I close the tabs (which I have been doing because they take up space) then I have no scrollbars on any of my terminals.

**Comment by Tyriar** [comment]
@wcerfgba it's fixed in the next version
