### ISSUE TITLE
Can't set statusbar item ID

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125416]
Testing #124843

```ts
const item = vscode.window.createStatusBarItem({ name: 'my name 1', id: 'itemid' });
console.log(item.id);
```

I get this log

```
roblourens.robtestext3
```

Same as if I don't pass the options. Am I missing something?

**Comment by bpasero** [comment]
That does not seem like the right use of the API:

![image](https://user-images.githubusercontent.com/900690/120689609-96e1e780-c4a4-11eb-916d-db3e30676d3b.png)

**Comment by roblourens** [comment]
Didn't notice that I had an old proposed dts
