### ISSUE TITLE
Notebook cell focus issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#125432]
When I select the editor of one cell, there should be no other cell that shows the focus border. But there are. Lengthly gif but you see multiple focussed editors/cells

![cudX1FeZI5](https://user-images.githubusercontent.com/4674940/120701068-4ac48200-c467-11eb-9432-ae34bc973f2b.gif)

**Comment by rebornix** [comment]
I think this is an issue @roblourens recently have fixes for.

**Comment by roblourens** [comment]
Should be fixed now

**Comment by roblourens** [comment]
Actually probably https://github.com/microsoft/vscode/issues/129639 which is not fixed yet
