### ISSUE TITLE
[Go to File] Cannot find renamed file in current project

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#125455]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: macOS 11.4

I have a repository opened in vscode, in which the **README** file was renamed from **README.VER** in certain recent commits. After pulling the latest commits, I could no longer reach to the renamed README file via <kbd>Cmd + P</kbd>, even though the file is clearly there as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/610161/120720159-2b2c6880-c4fe-11eb-88fd-1f4ba46e4fcb.png)

The repository is actually https://github.com/gwsw/less, but I think it doesn't really matter, maybe you even do not need a repository, instead have a project open and have the concerned file renamed outside of vscode.

Steps to Reproduce:

1. outside of vscode, clone https://github.com/gwsw/less, and checkout commit 4a8a5cc
2. open the cloned repository in vscode, 
3. open the README.VER file from vscode file explorer view on the left
4. open "Go to File..." by typing <kbd>Cmd + P</kbd>, then type in "README.VER", you should be able to find it.
4. checkout the latest commit, say fcd5d8f, at which point the README.VER had already been renamed to README
5. now try again via <kbd>Cmd + P</kbd>, then type README, the file can't be found even though you can see it's right there in the file explorer view in vscode.

**Comment by TylerLeonhardt** [comment]
@ryenus this is because you have `README` in your [`.gitignore`](https://github.com/gwsw/less/blob/master/.gitignore#L7-L8). I think to simplify search results, we ignore what is inside of you .gitignore by default. You can configure this behavior with the following setting:
![image](https://user-images.githubusercontent.com/2644648/121411461-830d0a00-c918-11eb-84be-5b5e4366b87c.png)

**Comment by ryenus** [comment]
Oops. indeed, what happened was that in the past the README file as a generated file, but that changed due to the recent renaming. @TylerLeonhardt  Thank you so much for clearing things up in such a bizarre case! 👍
