### ISSUE TITLE
Git clean changes, cleaned file just shows up blank.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#12542]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:

1. Make some changes
2. From toolbar for git, select to clean the changes.
3. The file shows up empty in editor.
4. Close the file form editor and reopen, it's still blank.

Need to restart vscode to correct, so far I've notice this problem 2 times already.

**Comment by alexandrudima** [comment]
@rajinder-yadav I do this almost daily, and so far I have never seen something like what you describe.

Do you:
* create a new file or modify an existing file?
* if you modify a file, is the file you modify staged in the git index before you make the modifications?
* do you have a diff displaying when you say the file shows up empty in editor?

Can you perhaps capture a screenshot when this happens or perhaps give more detailed steps such that we can reproduce?

**Comment by rajinder-yadav** [comment]
I'v done this on an existing project where I've made changes to a file that's already tracked.

I've made some changes and then after saving them I've done a clean (I might have edited other file and or checked in other files? not recall the exact steps.)

It took me a while to repro, something seeing is believing :) ... so here is a screen-cast. In the video each time I delete, I save the file and them edit and save if you see me typing!

https://youtu.be/cCjoifvf4Og

You might have to do it a few times, it took me several tries even with a fresh load of vscode.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by rajinder-yadav** [comment]
Attached
[git-clean-bug.log.gz](https://github.com/Microsoft/vscode/files/493280/git-clean-bug.log.gz)

**Comment by bpasero** [comment]
@rajinder-yadav 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by rajinder-yadav** [comment]
Unfortunately it's not, I used "code --disable-extensions --verbose ."

After a few tries, I got into the reported state.

Log below:

<pre>
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/FETCH_HEAD
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/FETCH_HEAD
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/FETCH_HEAD
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/FETCH_HEAD
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/templates/source.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/templates/source.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/templates/title.trb
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:36 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
ipc.cp.ts:139 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/templates/source.trb
ipc.cp.ts:139 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
ipc.cp.ts:139 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/templates/source.trb
ipc.cp.ts:139 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
ipc.cp.ts:139 [IPC Library: Watcher] [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
ipc.cp.ts:139 [IPC Library: Watcher] [ADDED] /home/yadav/dev/cpp/rmake/.git/index.lock
ipc.cp.ts:139 [IPC Library: Watcher]  >> normalized [CHANGED] /home/yadav/dev/cpp/rmake/.git/index
ipc.cp.ts:139 [IPC Library: Watcher]  >> normalized [ADDED] /home/yadav/dev/cpp/rmake/.git/index.lock
ipc.cp.ts:139 [IPC Library: Watcher] [DELETED] /home/yadav/dev/cpp/rmake/.git/index.lock
ipc.cp.ts:139 [IPC Library: Watcher]  >> normalized [DELETED] /home/yadav/dev/cpp/rmake/.git/index.lock
</pre>

**Comment by bpasero** [comment]
@rajinder-yadav do you still see this in 1.6.0?

**Comment by rajinder-yadav** [comment]
Thanks for checking back, I went through a few trails and looks like it's been fixed.
Super work guys :D

**Comment by ramya-rao-a** [comment]
Marking as verified as the OP has mentioned that this is fixed
