### ISSUE TITLE
Shows number on extensions icon when no extensions installed

### ISSUE THREAD

**Issue by byroniac** [Microsoft/vscode#12545]
- VSCode Version: Code - Insiders 1.6.0-insider (d81ee41c51cae93a5cac967e42a28660a3a7e005, 2016-09-23T06:10:40.972Z)
- OS Version: Windows_NT ia32 10.0.14393

I had two extensions which needed updating on the Insiders Build. I updated them, but skipped the "Enable" and restart part to install the new Insider build. When I did that, it still has the number 2 on the extension icon (updates?). I've tried uninstalling all extensions, and even completely uninstalling Insiders (do not have regular version even installed), and also deleted the .vsinsiders-code folder in my home folder and the one under AppData\Roaming\Microsoft. So I don't know what this number means unless it is bug. Also tried reinstalling both extensions (C# and PowerShell) after, no good. Shows no extensions need updating but still has number "2" on extension icon.

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
Related to #12516
