### ISSUE TITLE
Adding a folder to an Empty workspace seems to try to re-activate every extension

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125430]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.57.0-insider
Commit: 20df87725d3ce4a501187f0240c2f159aa0ad2a5
Date: 2021-06-03T06:00:36.788Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

1. Open an _empty_ workspace
2. Add a folder to the workspace via: `Workspace: Add folder to workspace...`
3. Open dev tools and see a sea of red:
![image](https://user-images.githubusercontent.com/2644648/120696481-76446e00-c461-11eb-8943-524c30568e3e.png)

This doesn't repro if the workspace is just a normal folder.

**Comment by lszomoru** [comment]
@TylerLeonhardt, I am unable to reproduce the issue in Insiders and OSS. 
Could you record a GIF as I have the feeling I am missing something. Thanks!

**Comment by TylerLeonhardt** [comment]
I am adding a workspace that is trusted to an Empty Workspace… maybe that’s the key?

**Comment by sbatten** [comment]
I could reproduce this with a trusted folder being added to a restricted mode empty workspace. However, I could only do so in Insiders but not in OSS. Did anything change in the last 24h?

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues/69335

**Comment by lszomoru** [comment]
@bpasero, I am not seeing any commit from the last 24 hours linked on that issue.

**Comment by bpasero** [comment]
@lszomoru yeah just wanted to point out why the extension host restarts. This has been like that since the beginning of multi root workspaces.

**Comment by lszomoru** [comment]
Got it. I was aware of the extension host restart. 
Trying to figure out what changed in the last 24 hours that fixed the issue reported by @TylerLeonhardt

**Comment by lszomoru** [comment]
I got it to repro in Insiders but it does not repro in OSS. Will investigate the issue and try to get to the bottom of it.
