### ISSUE TITLE
A tutorial

### ISSUE THREAD

**Issue by Endereyes29** [Microsoft/vscode#12548]
- VSCode Version:1.5
- OS Version:
- pls make a tutorial
Steps to Reproduce:

1. step 1 make a tutorial (make sure it is very very basic)   pls
2. make it easy to use

**Comment by Bill-Stewart** [comment]
Have you looked at the intro videos (http://code.visualstudio.com/docs/introvideos/overview)?

**Comment by waderyan** [comment]
@Endereyes29 please provide more information on what you are looking for. We have created a [series of intro videos](http://code.visualstudio.com/docs/introvideos/overview) for VS Code. Closing until more information is given.
