### ISSUE TITLE
Webview 404 error

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode#125485]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 1.56.2
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Clone my repo: https://github.com/sketchbuch/vsc-workspace-sidebar
2. try and run the extension (either using the debug panel with the code from my repo in step 1 or if you package a vsix file and install that)
3. If you try and use my extension the web view will sometimes not load the resources - especially after searching and then clearing the search.
4. Sometimes if you then leave the view and go back there is nothing at all rendered. 

This never used to happen. I have been using the webview for a while and have never noticed this issue before.

I use "asWebviewUri" to generate my urls to resources. Please let me know if you need more info.

![vscode webview error](https://user-images.githubusercontent.com/16445037/120778366-8f632280-c526-11eb-9b81-bcac1971e95a.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by sketchbuch** [comment]
@mjbvz Hi, yes css/js is no longer loading in my webview in insiders (1.57.0-insider)

**Comment by mjbvz** [comment]
Thanks for testing

The exception in `host` suggests that your extension is trying to navigate the webview page. This isn't supported (it previously sort of half worked on desktop, but a lot of webview functionality doesn't work once you navigate)

Please try coming up with a different approach in your extension

**Comment by sketchbuch** [comment]
@mjbvz What exactly do you mean navigate? I'm not navigating anywhere. You mean changing the iframe url? I'm not doing this.

**Comment by mjbvz** [comment]
Anything that causes the page's location to change. This could be a form for example

**Comment by sketchbuch** [comment]
I think maybe the clear button is added to type="search" inpurts. I shall try changing this

**Comment by sketchbuch** [comment]
OK, I fixed it. It was my form.
