### ISSUE TITLE
Snippets won't expand instantaneously 

### ISSUE THREAD

**Issue by Congstarrr** [microsoft/vscode#125410]
I have been just switching to VSCode and noticed that, contrarily to Vim, snippets in VSCode don't expand instantaneously, i.e. without having to press tab but right away when you have fully typed out the trigger word. 

More specifically, it would be nice to have the following options:

1. Snippet will be triggered automatically, when condition matches, i.e. you don't have to press a tab for the snippet to expand
2. Define contexts for each individual snippet, e.g. if I want a certain snippet only to instantly expand when in math zone (latex)

All these requested features are present in the vim extension [UltiSnips](https://github.com/microsoft/vscode/issues/125410) for a reference.

**Comment by Jeffrey-kerson** [comment]
I have been trying to exactly achieve that behaviour, but I'm not using vim but emacs. You should maybe specify the feature request a bit further, i.e. add more details and make it more precise.

**Comment by MuningerRudolf** [comment]
The vim extension you are referring to is probably Ultisnips, just for a reference.
https://github.com/SirVer/ultisnips
