### ISSUE TITLE
IntelliSense not working 

### ISSUE THREAD

**Issue by Mohancmd2531** [microsoft/vscode#125589]
Issue Type: <b>Performance Issue</b>

i cannot use IntelliSense, suggestion feature, autocomplete feature in using HTML and CSS

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.65GB (2.26GB free)|
|Process Argv|--crash-reporter-id 60b5379a-b5f5-4356-8c21-8eedc293f7c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 20204	code main
    0	    55	 10784	   crashpad-handler
    1	   161	 14236	   window (trycss.html - html programs - Visual Studio Code)
    0	    14	 10864	     watcherService 
    0	    11	 12336	       console-window-host (Windows internal process)
    0	    68	 13160	     searchService
    0	   224	 19972	     extensionHost
    0	    61	 18072	   utility
    0	    74	 18624	   window (Issue Reporter)
    0	    88	 20144	   shared-process
    0	    65	 21856	     ptyHost
    0	    68	  9748	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 14916	       console-window-host (Windows internal process)
    0	   221	 21956	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (trycss.html - html programs - Visual Studio Code)
|    Folder (html programs): 9 files
|      File types: html(5) json(2) css(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-django|bat|1.6.0
doxdocgen|csc|1.3.2
python-extension-pack|don|1.6.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.4.0
mithril-emmet|Fal|0.7.6
code-runner|for|0.11.4
vscode-pull-request-github|Git|0.26.0
better-cpp-syntax|jef|1.15.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4360
vsliveshare-audio|ms-|0.1.91
inline-html|pus|0.3.3
java|red|0.79.2
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
jinja|who|0.0.8
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by Mohancmd2531** [comment]
it didn't work

**Comment by aeschli** [comment]
Please add a small sample code that shows what's not working.
Please also add a screenshot. Make sure the editor in HTML mode.
