### ISSUE TITLE
I have git in my computer but not in C:/ ,but the vscode cannot find it ? Is git must put in C:/ ?

### ISSUE THREAD

**Issue by Chinazhouwy** [Microsoft/vscode#12559]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by Emeryao** [comment]
absolutely nope.
just make sure that git directory is in your `PATH` of your enviroment variables ie. make sure you can use `git

**Comment by chrmarti** [comment]
Indeed, thanks.
