### ISSUE TITLE
Cannot set to open the current html file in default browser on gnu/linux.

### ISSUE THREAD

**Issue by supersede** [Microsoft/vscode#1255]
The only explanation on how to define default browser to be launched on ctrl+shift+b I found was this http://stackoverflow.com/questions/30039512/how-to-view-my-html-code-in-browser-with-visual-studio-code and it doesnt work for gnu/linux.
Am I missing something here or this feature is only available for windows and mac ?

**Comment by dbaeumer** [comment]
@supersede in the tasks.json configure a browser that is install on your machine. See https://code.visualstudio.com/docs/editor/tasks for a detailed description how task work.
