### ISSUE TITLE
http media markdown links don't open from Getting Started contributed steps.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125507]
Testing https://github.com/microsoft/vscode/issues/122570

1. Open the getting start sample. 
2. Add test.md to the folder root.
3. Add the following in test.md: `[test](http://bing.com)`
4. Change one of the sample steps to have the following media:
 ```
 						"media": {
							"markdown": "test.md"
						},
```
5. Run the sample, look at the step, and click on the link. The link doesn't open. If you change it to https it will open.

**Comment by JacksonKearl** [comment]
Good catch thanks.
