### ISSUE TITLE
Getting Started's "Start" section is missing spaces in the command tooltips

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125503]
Testing https://github.com/microsoft/vscode/issues/106717

All of the links in the start section hat have a command + keybinding association are missing a space before the "("

![image](https://user-images.githubusercontent.com/38270282/120794388-75324000-c538-11eb-85ba-50d5b924b948.png)

**Comment by JacksonKearl** [comment]
Thanks!
