### ISSUE TITLE
PowerShell extension make js and json Syntax Highlighting Broken

### ISSUE THREAD

**Issue by jackchoumine** [microsoft/vscode#125596]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:

 1.55.0
提交: c185983a683d14c396952dd432459097bc7f757f
日期: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0

- OS Version:
mac  os Darwin x64 20.4.0

Steps to Reproduce:

1. install  PowerShell extension
2. "workbench.colorTheme": "PowerShell ISE", in settings.json
3.  set other color theme, dont work. then unistall  PowerShell
4.  js and json Syntax Highlighting Broken

I have searched it but no answer that resolved this problem.

**Comment by jackchoumine** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> * VS Code Version:
> 
> 1.55.0
> 提交: [c185983](https://github.com/microsoft/vscode/commit/c185983a683d14c396952dd432459097bc7f757f)
> 日期: 2021-03-30T16:01:05.981Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin x64 20.4.0
> 
> * OS Version:
>   mac  os Darwin x64 20.4.0
> 
> Steps to Reproduce:
> 
> 1. install  PowerShell extension
> 2. "workbench.colorTheme": "PowerShell ISE", in settings.json
> 3. set other color theme, dont work. then unistall  PowerShell
> 4. js and json Syntax Highlighting Broken
> 
> I have searched it but no answer that resolved this problem.

I disabled all builtin them.  I enable one , it works well.

**Comment by aeschli** [comment]
@jackchoumine Is the problem solved?
