### ISSUE TITLE
For Notebooks global toolbar allow for showing just the icons, not icon + text

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#125551]
When the Notebook global toolbar is turned on it shows both icons + text. Just as a personal preference (so just logging as a feature request / suggestion) I would want this to show just the icons or to have a setting to change this.
![image](https://user-images.githubusercontent.com/812783/120851136-482c6000-c52d-11eb-86f8-4d74b300ae61.png)
It feels visually busier with the text, and once I've moused over an icon once to see the tooltip I would not want or need to see the text any more. Plus it would put the mouse hit targets all in a single grouped location. + Code and + Markdown would need distinct icons for this.

**Comment by misolori** [comment]
I do think an option for only icons would be nice, though we'd need to figure out an alternative for the`+ Code` and `+ Markdown`.

**Comment by rebornix** [comment]
This setting can be useful for Jupyter which contributes actions to the global toolbar.

**Comment by joyceerhl** [comment]
Currently if there are lots of contributions to the notebook toolbar, the overflow strategy for the toolbar is to scroll, so remaining entries in the toolbar get cut off, and the scrollbar only appears on hover.

Overflow + no hover over toolbar:
![image](https://user-images.githubusercontent.com/30305945/120854425-03ef8e80-c532-11eb-8053-316f50744cc1.png)

Overflow + hover over toolbar:
![image](https://user-images.githubusercontent.com/30305945/120854251-bffc8980-c531-11eb-87da-2715536affb1.png)

One possibility here could be to only show icons when the shortTitle + icons exceeds the available horizontal space in the toolbar.

**Comment by IanMatthewHuff** [comment]
The scrollbar seems like it might be an issue there in general. It's a pretty small hit target, I wouldn't want to try to click a thin scrollbar handle when it's right on top of my "restart kernel" icon, too easy to miss and trash my kernel. Right now it's pretty easy to get the scrollbar with the default set of icons + text. I get it on my MacBook screen just by making VS Code like 85% of full screen size.

**Comment by misolori** [comment]
_(The scrolling issue could be separated out to its own issue.)_

The Outlook web app (Fluent) does a nice job of moving items that don't fit into the overflow `...` menu:

<img width="707" alt="CleanShot 2021-06-08 at 10 51 39@2x" src="https://user-images.githubusercontent.com/35271042/121233548-956b4300-c847-11eb-9afa-cf08cb2ba8b1.png">


https://user-images.githubusercontent.com/35271042/121233574-9c925100-c847-11eb-9a32-f58a6f705fbd.mp4

**Comment by misolori** [comment]
_Posting from another issue:_

I think we should either make the toolbar responsive, just like in the panel when the view is smaller, and move items into the ...

<img width="663" alt="CleanShot 2021-07-08 at 15 44 17@2x" src="https://user-images.githubusercontent.com/35271042/124999610-60e3d600-e003-11eb-9b80-330f8569f72c.png">


Or go into a no-label version:

<img width="662" alt="CleanShot 2021-07-08 at 15 45 00@2x" src="https://user-images.githubusercontent.com/35271042/124999652-7a851d80-e003-11eb-8f58-077c966b85fa.png">

**Comment by DonJayamanne** [comment]
Based on the issue we have'nt really addressed the feature request.
I'm tagging as verified as the associated PR adds an overflow option for menus.
