### ISSUE TITLE
Clicking on rating icon doesn't open Rating & Review section on Marketplace

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125500]
![Screenshot (26)](https://user-images.githubusercontent.com/9638156/120793277-5edbb280-c53f-11eb-8fc6-d841d7a2d0be.png)

Goes to: https://marketplace.visualstudio.com/items?itemName=bierner.emojisense#review-details

`Rating & Review` opens at https://marketplace.visualstudio.com/items?itemName=bierner.emojisense&ssr=false#review-details

**Comment by sandy081** [comment]
@prashantvc / @SaiKanth007 is the link to reviews page can be computed from main extension page?

**Comment by prashantvc** [comment]
Sure, it makes sense to redirect to Ratings tab.
@sandy081 Could you make this issue to Marketplace repo?

**Comment by usernamehw** [comment]
Lastest vscode includes `&ssr=false` in the link address so it works now.
