### ISSUE TITLE
WebViewPanel regression starting with 1.56 -- race condition causes postMessage to get dropped

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#125546]
Does this issue occur when all extensions are disabled?: Yes (repros is with the C/C++ extension)

- VS Code Version: 1.56.2 or latest Insiders, but doesn't repro with 1.55.2
- OS Version: Windows

Steps to Reproduce:

1. Install the C/C++ extension preferably 1.3.1 (1.4.0 has a retry that attempt to workaround this bug, but it doesn't work reliably).
2. Configure Display Language and select one of the two Chinese languages -- this step isn't 100% required, but it increases the repro probability. Using the remote scenario also appears to increase the repro probability.
3. Use C/C++: Edit Configurations (UI) command. Using the command earlier during the extension activation appears to increase the repro probability. Reload Window and/or Configure Display Language can be used again try another repro.

Bug: The webview drops postMessage calls, leading to the UI fields being "blank" (they normally should be populated). There appears to be some race condition in which calls to postMessage that occur "too soon" in response to a onDidChangeViewState callback get dropped and no onDidReceiveMessage gets sent. (code is around https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/settingsPanel.ts#L217)  Multiple users have reported this as a bug against our C/C++ extension since 1.56 was released, but it is a VS Code regression. We added a 2nd postMessage on a 500ms delay in 1.4.0 to try to workaround this bug, but it doesn't work reliably since a longer delay up to 3 seconds or so may be required and the re-updates cause the UI to revert to an earlier state, causing user input to be reset. It's possible we may be able to add a workaround that detects when postMessage isn't received (not sure yet).

![image](https://user-images.githubusercontent.com/19859882/120846511-12847880-c527-11eb-9bbc-a2e7f09bc087.png)

**Comment by sean-mcmanus** [comment]
I implemented a workaround that resends the webViewPanel.postMessage in 500ms if doesn't detect an onDidReceiveMessage response: https://github.com/microsoft/vscode-cpptools/pull/7647 . However, the delay can be up to 6 seconds -- ideally postMessage could be received earlier on, not sure if that's the root bug or not.

**Comment by mjbvz** [comment]
Please put together a minimal webview example extension that demonstrates the issue. You can use the webview sample extension as a starting point

**Comment by sean-mcmanus** [comment]
I'm thinking a minimal repro may not repro the issue, because it seems like the race condition may require a big enough html file or something. Are you able to just use 1.3.1 of our extension as a minimal repro? https://github.com/microsoft/vscode-cpptools/archive/refs/tags/1.3.1.zip

**Comment by tamuratak** [comment]
You cannot call `Webview.prototype.postMessage` before `window.addEventListener("message", ...)` called on the webview. If you call it too early, the send messages are dismissed.

https://github.com/microsoft/vscode-cpptools/blob/20954f7f752def061d63d048dcdb06306322b68d/Extension/src/LanguageServer/settingsPanel.ts#L128

The following steps work well with the internal PDF viewer for [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop).

1. Register a callback to be called when the `initialization finished` message recieved, on the extension host.
2. Assign the HTML content to `WebView.prototype.html`
1. After the initialization of scripts on the webview finished, send  the `initialization finished` message from the webview to the extension host with `vsCodeApi.postMessage`.
2. Then, the registered callback will be called on the extension host.

https://github.com/James-Yu/LaTeX-Workshop/blob/a3adc13d833e171c4914c0cefd947a0198fc5134/src/components/viewer.ts#L303-L310

**Comment by sean-mcmanus** [comment]
@tamuratak Thanks a lot for the info. It turns out VS Code is invoking the webViewPanel onDidChangeViewState with 
WebviewPanelOnDidChangeViewStateEvent.webviewPanel.active set to true before our constructor is invoked, which is the root "regression" compared with 1.55 (or possibly an initialization performance regression?), but I don't know if that's a "by design" change or not, and we can workaround that via sending an initialization finished message as you suggested, which avoids the repeated update retries we were doing previously: https://github.com/microsoft/vscode-cpptools/pull/7656

So VS Code could close this issue if the changed behavior is as intended.

**Comment by mjbvz** [comment]
Thanks for the investigation @tamuratak!

@sean-mcmanus This doesn't sound unexpected to me, but if you provide more details about the code I would be able to say for sure. The webview contents are created asynchronously so you do generally need to use some kind of `ready` message to confirm that a webview is ready for messages

**Comment by sean-mcmanus** [comment]
@mjbvz So our pending 1.4.1 update has the fix so that our panel will eventually update, but there is still a ~4-8x performance regression with VS Code's loading of our webViewPanel on the 1st run, i.e. after changing the display language to one of the two Chinese languages, as if some expensive language pack caching is being done.

1.55.2: Takes 1-5 seconds (usually 2 seconds).
1.56.2: Takes 8-40 seconds (usually 8 seconds).

I don't see any API to somehow preload it to avoid the delay.

I guess we can just wait till more users complain about it, since it's fast (1-2s) after the 1st load.

**Comment by mjbvz** [comment]
Hm, that sounds bad but I haven't seen other reports of big performance regressions. Can you try putting together a minimal repo? This may help identify potential problems in your codebase too

**Comment by sean-mcmanus** [comment]
I don't think I have time to create a minimal repro, but I ran VS Code's profiler and found out that the cause is networking-relating. e.g. below is the cause of the 8 second delay:

Network request
URLsettings.js
Duration3.99 s (3.99 s network transfer + 0.41 ms resource loading)
Request MethodGET
PriorityHigh
Mime Typeapplication/javascript
Encoded Data15.6 kB (from service worker)
Initiatormain.js:116

Network request
URLLanguageCCPP_color_128x.png
Duration4.04 s (3.99 s network transfer + 56.78 ms resource loading)
Request MethodGET
PriorityLow
Mime Typeimage/png
Encoded Data4.8 kB (from service worker)
