### ISSUE TITLE
Feature request: API to open document in a non-persistent tab

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#125541]
I am creating an extension to interact with reverse engineering tools like IDA Pro and Hopper. My extension will provide a list of functions in the sidebar, and when clicked they will open a document of the disassembly or pseudocode for that function.

I would like it to behave the same way the file explorer does: when clicked, a "non-persistent" tab is opened. And when a new function is clicked, it replaces the old non-persistent tab with its own contents, etc. Currently, calling `window.openTextDocument()` opens a persistent document.

**Comment by ArturoDent** [comment]
`showTextDocument(document: TextDocument, options?: TextDocumentShowOptions): Thenable<TextEditor>`

One of the `TextDocumentShowOptions` is `preview`.

**Comment by NSExceptional** [comment]
I am truly dumb. I had recently refactored my code so that the call to `openTextDocument` was entirely separate from my own call to `showTextDocument` with `preview` explicitly set to `false`. Pretty embarrassed about this; sorry again. And thank you.
