### ISSUE TITLE
C++ User Snippet Problem

### ISSUE THREAD

**Issue by Rajsharma9593** [Microsoft/vscode#12556]
- VSCode Version: 1.5.3
- OS Version: WinDows 7

Steps to Reproduce:

1. I think there is a problem on adding more than one snippet on "C++ User Snippet".
2. It gives a red underline with an error "End of File Expected" even if the file is ended.
3. Please solve this issue if there is any if not Sorry for causing inconvenience to you.

Thank You,
Your Happy User.

**Comment by chrmarti** [comment]
C++ snippets are contributed by an extension you have installed. Please open a bug report for that extension. Thanks.
