### ISSUE TITLE
Clicking New File opens a New Window instead

### ISSUE THREAD

**Issue by kyleflett** [microsoft/vscode#125553]
Issue Type: <b>Bug</b>

Whenever I actually click file>new file, oftentimes it opens a new window and not a new file. This does not seem to happen when I use the keyboard shortcut, and only seems to happen once. I am not accidentally clicking on the new window button.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 12, 10|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 20b0e250-a431-4587-9e60-7a1950f5a498|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer|Coe|1.0.61
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4360
vsliveshare-pack|ms-|0.4.0
indent-rainbow|ode|7.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30307505
vscorehov:30309549
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kyleflett** [comment]
I've been using it for 3 days now and have not been able to reproduce it.
