### ISSUE TITLE
[Insiders] Terminal tooltip staying after task terminal killed

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#125565]
When build task fails and the terminal is killed, if the user was hovering the terminal title, the tooltip remains if there are still 2+ terminals still open.

Quick steps to reproduce:
- Open a project with no `watch` script in its `package.json`
- Open up two terminals (not split)
- `Tasks: Run Build Task` command,
- Hover over the title of the task terminal.
- When it fails, the tooltip should remain 🐛

Video:
https://user-images.githubusercontent.com/31675041/120865939-3b6b3480-c54c-11eb-84b1-b21330563226.mp4

**Comment by Tyriar** [comment]
Alt repro:

- Create a task that finished
- Click into terminal
- Hover tab
- When the task finished, press any key to close the terminal, the tooltip remains 🐛

**Comment by Tyriar** [comment]
Should be fixed: https://github.com/microsoft/vscode/pull/125667#issuecomment-858075259
