### ISSUE TITLE
VSCode Extensions aren't available and json file fix doesn't work

### ISSUE THREAD

**Issue by frontrunnersoftware** [microsoft/vscode#125593]
Issue Type: <b>Bug</b>

PlatformIO extension doesn't work with VSCodium even after installation from a vsix file.  The Marketplace workaround detailed on Github using a json file doens't work either.
If VSCodium won't work with the same extensions as VSCode then it's pretty pointless and I may as well install VSCode and just block the telemetry with my hosts file.  I've moved back to VSCode so am not looking for a fix for this for myself but perhaps it should be addressed for others with more patience.

VS Code version: VSCodium 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-14T00:21:57.363Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (11.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Is it supposed to be in VS Code repo? Looking at text it's looks like issue for VSCodium repo

**Comment by sandy081** [comment]
Yeah seems to be related to VSCOdium. Hence closing.
