### ISSUE TITLE
.NET Command Line Tools in cmd 

### ISSUE THREAD

**Issue by androllen** [Microsoft/vscode#12558]
- VSCode Version:1.5.3
- OS Version:Win10  10.0.14393

Steps to Reproduce:

1. i cant update .NET Command Line Tools to latest update
2. the tool always display .NET Command Line Tools (1.0.0-beta-001661)
3.when i had uninstall ，.NET CLI tools faile uninstall 
thanks

**Comment by Emeryao** [comment]
Do you mean the CLI for `.NET Core` ?
兄弟 你说的是`.NET Core`的命令行工具吗？如果是的话，可能走错门了，那个更新不了跟VS Code好像没关系吧

**Comment by chrmarti** [comment]
Please file against the command line tools. VS Code does not come with these.

**Comment by androllen** [comment]
see: https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk
