### ISSUE TITLE
I can use an extension when a workspace transitions from trust -> untrusted

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#125526]
1. Have a trusted workspace, notice all extensions enabled
2. Say you do not trust the workspace
3. Notice some extensions are disabled
4. You can still use those extensions until you reload 🐛

**Comment by lszomoru** [comment]
@isidorn, revoking trust on a workspace should restart the extension host, hence unloading all extensions that do not support trust.
Could you please illustrate what do you mean by you can still use those extensions until you reload?

**Comment by isidorn** [comment]
1. Install the following extension by Alex https://marketplace.visualstudio.com/items?itemName=alexdima.open-in-github
2. Do the steps from my firs t comment
3. Notice how now the workspace is untrusted, the extension is rendered as disabled
4. I can still use the command `Open in GithHub: File` that is contributed by that extension

**Comment by isidorn** [comment]
Upon further inspection the issues seems to be also in the rendering of the extension
Notice how on the hover it says it is disabled, but the extension is not actually greyed out like it should be

![Screenshot 2021-06-04 at 18 33 02](https://user-images.githubusercontent.com/1926584/120834474-572e0500-c563-11eb-9bda-79ef170505a0.png)

**Comment by lszomoru** [comment]
Thanks @isidorn. Tracked down the issue and pushed a fix!

**Comment by isidorn** [comment]
Thanks for fixing @lszomoru 
Let's add a bug label so I verify this later today

**Comment by isidorn** [comment]
Great job, works nicely now -> verified
