### ISSUE TITLE
The 'workbench.action.terminal.sendSequence' command stops working after running a task.

### ISSUE THREAD

**Issue by yohan-pg** [microsoft/vscode#125573]
Issue Type: <b>Bug</b>

The 'workbench.action.terminal.sendSequence' is very useful for sending commands to the integrated terminal with keyboard shortcuts. When tasks run, they open a new terminal on top of the existing one, along with the message "Terminal will be reused by tasks, press any key to close it". However, sending a key using the 'sendSequence' command no longer works while the "task terminal" is open. Neither does it close it, which it should according to the displayed message. This is very annoying as the whole point of these keyboard shortcuts is to avoid manually manipulating terminals.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id 3e7d515b-b0fd-42e3-b8d6-159f0162d735|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@yohan-pg our May release, which will probably release this week, has a new task presentation property `close`:

https://github.com/microsoft/vscode/blob/b7009c5b546acbe7ee57d3e875dc490a84249182/.vscode/tasks.json#L198-L206

You can try it out in our Insiders build already.

**Comment by alexr00** [comment]
My understanding of why `workbench.action.terminal.sendSequence` doesn't close task terminals is because the terminal is literally waiting for a _key press_, which is different from a sequence of characters that doesn't originate from a key press. @Tyriar in case I am getting that wrong.

**Comment by Tyriar** [comment]
sendSequence doesn't do this since it bypasses the terminal and passes the sequence directly through the pty. As designed seems right.

**Comment by yohan-pg** [comment]
@alexr00 Thanks. While that makes perfect sense logically, from a usability point of view it is very disappointing!  I really feel like using a command like `sendSequence`, should never just fail silently and do nothing.
