### ISSUE TITLE
Unable to format a plaintext file

### ISSUE THREAD

**Issue by Entolurgy** [microsoft/vscode#125594]
It seems that VSCode has absolutely no chance to format plain text ("plaintext" as it says itself).
Create a .txt file with some arbitrary contents inside, open it with VSCode and try to format the contents using the standard keystroke (Alt+Shift+F). You will get an error message: "There is no formatter for 'plaintext' files installed".
I tried to install third-party formatters, even setting them as editor default ones, but had no luck: the mentioned error continues to pop up. I had also tried to set the built-in "vscode.html-language-features" as the default formatter for plaintext through settings.json:
```
    "[plaintext]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    }
```
... - no effect.
What "plain text formatting" am I looking for? In fact, I need just to automatically wrap the text to a specified column using linebreaks (in the exactly same manner like the built-in HTML formatter does). But I have neither built-in plaintext formatter/wrapper nor possibility to set another formatter to be used against plaintext.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.82GB free)|
|Process Argv|--crash-reporter-id a74e8650-cef4-4aac-96d3-19b84d775c7c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by aeschli** [comment]
Each formatter is designed for specific languages. Setting the HTML formatter to a plain text document doesn't work.

If your plaintext document happens to be valid HTML, then you can change document language to HTML: 
Click on `Plain Text` in the status bar and change it to `HTML`. Then you can use the formatter.

But there are also extensions for wrapping lines: Check out https://marketplace.visualstudio.com/items?itemName=stkb.rewrap
