### ISSUE TITLE
Debugger shows me contents of array twice

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12554]
- VSCode Version: 1.6 Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. have a node.js script like this:

```javascript
var tree = require("process-tree");

tree(32583, function (err, children) {
    console.log(JSON.stringify(children));
})

```

2. fill in a PID of a process that exists
3. npm install process-tree
4. set a breakpoint into the the console log function
5. expand children

![image](https://cloud.githubusercontent.com/assets/900690/18806576/8b4fb876-8231-11e6-9212-afad7c64713d.png)

**Comment by isidorn** [comment]
The content of the array is coming from the debug adapter, thus unassigning myself.
I tried this for other example programs and it works fine, so this seems to be a corner case.

**Comment by isidorn** [comment]
Some details about my investigation can be found in #12989
