### ISSUE TITLE
IndexDB: why is transaction.oncomplete not used?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125586]
I came across our index DB file system provider, specifically these codes:

https://github.com/microsoft/vscode/blob/41163014f8c9cdb32b030cfa5ce20197b91bed72/src/vs/platform/files/browser/indexedDBFileSystemProvider.ts#L405-L405

https://github.com/microsoft/vscode/blob/41163014f8c9cdb32b030cfa5ce20197b91bed72/src/vs/platform/files/browser/indexedDBFileSystemProvider.ts#L419-L419

Instead of resolving the promise via `request.onsuccess = () => c();`, why not resolve it via `transaction.oncomplete`?

I think this ensures that we are really waiting for the transaction to having finished.

Refs: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#adding_data_to_the_database

![image](https://user-images.githubusercontent.com/900690/120892359-2fe04200-c60e-11eb-8db0-d8fa84e9d7e6.png)

**Comment by sandy081** [comment]
Agreed. It's (transaction) the right way to use. Thanks.
