### ISSUE TITLE
Long freeze when open a file

### ISSUE THREAD

**Issue by Sumoren** [microsoft/vscode#125513]
Issue Type: <b>Bug</b>

Since last update when VS Code is already running and I open a file in VS Code from windows explorer VS Code freeze for 10-15 sec before displaying the file.

It's faster to kill VS Code and reboot VS Code to open the file.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.73GB (94.00GB free)|
|Process Argv|c:\\Temp\\p4v\\QUE-WKS-AC072_p4-ac2-rawdata.mtl.ubisoft.org_2226\\orpheus-rawdata\\Textures\\Substance\\SBS\\Config\\Library#1.sbsprj --crash-reporter-id 7493547f-b1c9-4bf5-aa6a-5f2ef7f05b5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.18.3
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
vetur|oct|0.33.1
text-power-tools|qcz|1.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Sumoren** [comment]
I have used the Insider build for two day and I not the issue so far.
