### ISSUE TITLE
Leading "/" missing in path "usr/include/c++/5"

### ISSUE THREAD

**Issue by NealAbq** [Microsoft/vscode#12551]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.2.0-42-generic

Default user-config file: **c_cpp_properties.json**

Problematic contents (abridged):
`{
    "configurations": [
        {
            "name": "Linux",
            "includePath": ["/usr/include", "usr/include/c++/5"]
        }
}`

Fix: change  "usr/include/c++/5" to  "/usr/include/c++/5"

**Comment by chrmarti** [comment]
This belongs to the C/C++ extension, please file an issue for them at https://github.com/Microsoft/vscode-cpptools/issues
