### ISSUE TITLE
Opening links in markdown preview tries to open the browser to vscode-webview-test.com

### ISSUE THREAD

**Issue by dewinterjack** [microsoft/vscode#125595]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Mac OS 11.4

Steps to Reproduce:
1. Same steps as this issue: https://github.com/microsoft/vscode/issues/115812
2. Open markdown preview and press a link

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by riccardoferretti** [comment]
Regular markdown links ( `[test](./path.md)`) do work.

What is no longer working is navigation for wikilinks provided by the [Foam extension](https://github.com/foambubble/foam).
Foam parses wikilinks in the markdown document and creates proper links in the html preview.
This was working without problems up until 1.55.2, but it no longer works afterwards.
Has something changed between those versions in how preview links are handled?

You can see https://github.com/foambubble/foam/issues/648 for more details.

**Comment by gdalle** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Hi,
Just tried it in VSCode insiders without any other extension. The wiki-links in the preview whose path is the same as the link itself do work, but as soon as a wiki-link points to a file that is not in the same folder as the previewed one, clicking the link results in the opening of my default browser.

**Comment by riccardoferretti** [comment]
hi @mjbvz, is there anything that could have caused this issue in the latest releases? I haven't found anything glaring, but maybe there is something else might I might have missed?

**Comment by kevinslin** [comment]
> hi @mjbvz, is there anything that could have caused this issue in the latest releases? I haven't found anything glaring, but maybe there is something else might I might have missed?

vscode update broke Dendron wikilinks as well. we ended up using command urls to open links instead. see [here](https://github.com/dendronhq/markdown-preview-enhanced/commit/5fe28560be02bf09b7ff26ff76be69f1fcddd124) for what we did
