### ISSUE TITLE
Workspace trust - empty window trust is not remembered

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#125576]
Steps to Reproduce:

1. Open an empty window
2. Open the trust editor, and trust the window
3. Reload the window

Expected:
Window is trusted

Actual:
Window is not trusted

**Comment by misolori** [comment]
This is also repros when you have the setting `security.workspace.trust.emptyWindow` enabled:

<img width="1024" alt="CleanShot 2021-06-08 at 08 17 39@2x" src="https://user-images.githubusercontent.com/35271042/121212467-3c44e480-c832-11eb-93a8-22725bb30a9b.png">

**Comment by lszomoru** [comment]
Pushed a fix for this issue into `main`, in case we will want to take this as a candidate for the June release.
