### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by anddreza** [microsoft/vscode#125530]
Issue Type: <b>Bug</b>

Não consigo acessar o terminal, o terminal simplesmente não funciona, sempre que digito qualquer letra ele simplesmente não aparece nada 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.50GB free)|
|Process Argv|--crash-reporter-id ff01f3be-d6bf-4f8c-bec4-d4d551d77b6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
php-debug|fel|1.15.1
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
csharpextensions|jch|1.3.1
vs-color-picker|lih|1.0.0
mp-starter-vscode-ext|Mic|0.2.6
vscode-exec-node|mir|0.5.4
vscode-language-pack-pt-BR|MS-|1.56.2
csharp|ms-|1.23.12
cpptools|ms-|1.4.0
debugger-for-chrome|msj|4.12.12
live-server-preview|neg|0.1.4
live-preview|pro|0.0.3
vscode-thunder-client|ran|1.4.0
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-microprofile|red|0.2.0
vscode-quarkus|red|1.8.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-spring-initializr|vsc|0.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30312182
vscod805:30301674

```

</details>

**Comment by tsleal29** [comment]
> Não consigo acessar o terminal, o terminal simplesmente não funciona, sempre que digito qualquer letra ele simplesmente não aparece nada

I can't use the terminal, it simply doesn't work. When I type a letter nothing happens.


The rest of the description is already in english. I hope that helps.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
