### ISSUE TITLE
vscode taking long to open when opening for first time after boot in vs code in apple silicon

### ISSUE THREAD

**Issue by premkumar5012002** [microsoft/vscode#125588]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version:  Mac os 11.4 on apple silicon

Steps to Reproduce:

1.After system is booted and open vs code for first time
2.it will take long time to open and it shows shell is taking long to loaded

**Comment by deepak1556** [comment]
Can you repro the issue and attach the data following these steps https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers

**Comment by premkumar5012002** [comment]
Sorry, it is problem with my shellinitialization it takes some time to initialize after boot up
