### ISSUE TITLE
Windows File Explorer context menu "Open with Code" does not work

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#125568]
Issue Type: <b>Bug</b>

Windows File Explorer context menu "Open with Code" does not work, and there's no way to fix this using VS Code itself.

![image](https://user-images.githubusercontent.com/6047296/120867609-d7d11d80-c5c4-11eb-943d-6d578c4627e4.png)
![image](https://user-images.githubusercontent.com/6047296/120867623-e15a8580-c5c4-11eb-906c-45bff2ccd9c4.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (4.64GB free)|
|Process Argv|--crash-reporter-id 38c0c73b-2ac9-41c1-8092-f95b3478669c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
gitignore|cod|0.6.0
githistory|don|0.6.16
gitlens|eam|11.3.0
emberjs|emb|1.0.1
vscode-ember|emb|0.2.0
vsc-ember-cli|fel|0.3.3
code-runner|for|0.9.5
ember-related-files|jos|1.3.1
vscode-liquid-snippets|kil|1.1.1
shopify-liquid-preview|kir|1.0.2
language-liquid|nei|0.1.1
vetur|oct|0.12.6
EmberES6Snippets|pha|2.3.3
vscode-jsp|pth|0.0.2
java|red|0.30.0
sass-indented|rob|1.4.9
vscode-java-debug|vsc|0.16.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.13.0
vscode-maven|vsc|0.12.1
vscode-icons|vsc|11.2.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by ADTC** [comment]
I guess I'll try that. But is reinstalling the only way to fix this?

**Comment by isidorn** [comment]
Since reinstall fixed this I am closing this issue
fyi @joaomoreno if you would like to act on this
