### ISSUE TITLE
Why is there a "Help: Welcome" when we have this great new "Help: Getting Started" command?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#125502]
I was testing https://github.com/microsoft/vscode/issues/106717, and my first reaction was to run the "Help: Welcome" command, which shoes the old welcome UI. Is the new Getting Started page ready for prime time? If so, we should delete the old "Help: Welcome" command or at least make it show the Getting Started page.

**Comment by misolori** [comment]
I believe the plan is to eventually replace the Welcome screen content with the one from Getting Started, so there'd be no "Getting Started" command. @JacksonKearl can clarify though.

**Comment by digitarald** [comment]
Yes, the clean-up items that didn't make it into this iteration is renaming Getting Started to Welcome and removing the old Welcome page.

**Comment by JacksonKearl** [comment]
Yes, hoping to get feedback about any missing functionality before removing it entirely, at which point we'll reclaim the "Welcome" name.

**Comment by misolori** [comment]
I believe this is already fixed as we've replaced the Welcome command with the new getting started page:

<img width="355" alt="CleanShot 2021-06-28 at 12 25 05@2x" src="https://user-images.githubusercontent.com/35271042/123692631-e7323800-d80b-11eb-9af2-fb6ea9ce0a75.png">
