### ISSUE TITLE
Getting Started: Scrolling experience in smaller windows can be confusing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125584]
There appears to be a min height or something for the webview which is unexpected, additionally a large list of steps makes a second scroll bar which makes things more confusing:

![recording (8)](https://user-images.githubusercontent.com/2193314/120890878-54123380-c5ba-11eb-961e-8ddeb855eab7.gif)

How about preventing a page scroll bar by confining the steps on the left to its own container using something like:

```css
max-height: 80%;
scroll: auto;
``` 

It may also be good to make the walkthrough title/description sticky since the topic isn't mentioned in the tab's title:

<img width="488" alt="Screen Shot 2021-06-05 at 4 58 51 AM" src="https://user-images.githubusercontent.com/2193314/120890945-b9febb00-c5ba-11eb-83d5-f2e2a9b31160.png">

Related: https://github.com/microsoft/vscode/issues/125400

**Comment by Ashray123** [comment]
Hello,@JacksonKearl I want to work on this issue, any guide from your side on how to reproduce this issue and how to fix this will be great . :)

**Comment by JacksonKearl** [comment]
@Ashray123 sure, it seems to be that when the list is longer than a screen height the list cell's grid row expands to be larger than the screen height too. Instead, perhaps the cell for the list should not be allowed to expand that large, instead the list itself should scroll. In other words, the overall grid should never be larger than the screen height, instead the items within the grid should scroll. 

The CSS defining the grid structure is here:
https://github.com/microsoft/vscode/blob/cab9e56390ea85e5bf6add5d6f823dbb27732b03/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.css#L404-L461

Let me know if you still want to work on this! It will require some knowledge of [CSS-grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout).

**Comment by Ashray123** [comment]
@JacksonKearl Any suggestions on how to reproduce this issue will be great.

**Comment by JacksonKearl** [comment]
@Ashray123 you could either install Daniel's [Luna Paint](https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint) extension, or just use the [getting started sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample) and add a large number of steps to the contributed walkthrough. From there, it should be that a step whose media element is a markdown component scrolls strangely in small windows.

**Comment by JacksonKearl** [comment]
Can you try with tomorrow's insiders? There are still two scrollbars (one for item list, one for markdown), but it seems generally smooth imo.

**Comment by Tyriar** [comment]
Seems good now
