### ISSUE TITLE
Git does not recognise the right version

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#125504]
Issue Type: <b>Bug</b>

I am connected to my docker container using Remote-Containers. The git version on my host machine is 2.31 and on the container ( node:14 ) is 2.11.

When I try to stash my changes, I see the following error, because 2.11 does not support the "push" command.

git stash push -m my-message
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0
Remote OS version: Linux x64 4.14.232-176.381.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container sha256:54b8e50e61c66f503ac280c78973b8ea89fd4ad6370a95261bcbc3935c916a7b (/nk-dev-conn_pm2_1) @ aws-docker|
|OS|Linux x64 4.14.232-176.381.amzn2.x86_64|
|CPUs|AMD EPYC 7571 (4 x 2199)|
|Memory (System)|15.53GB (5.01GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
vscode-openapi|42C|4.5.2
atlascode|atl|2.8.6
npm-intellisense|chr|1.3.1
regex|chr|0.4.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
bash-ide-vscode|mad|1.11.0
mongodb-vscode|mon|0.5.0
compare-folders|mos|0.22.1
vscode-yaml|red|0.19.2
vscodeintellicode|Vis|1.2.14

</details>

**Comment by navneetkarnani** [comment]
Nope. None of those match the problem.

**Comment by lszomoru** [comment]
@navneetkarnani, apologies for not getting back to you on this until now. The git extension that provides the git functionality in VS Code is [a workspace extension](https://code.visualstudio.com/docs/remote/remote-overview) hence it runs in the container. As such, it will be using the version of git that is available in the container. In order to use the "push" command you would have to update the version of git in the container to a version that supports the command.
