### ISSUE TITLE
Extension grouping and sharing

### ISSUE THREAD

**Issue by dewinterjack** [microsoft/vscode#125597]
Create groups of vscode extensions. Groups can be created by a user and shared with other users, they are stored in a separate json file to settings. 

It would be good if you could list a group on the marketplace instead of an extension. You could then install a group, installing all the extensions from the group that aren't already installed.

Groups can be within a group. That way public groups can be encouraged to be as specific as possible, meaning you can have a personal group that uses the 'note taking' group.

I have some more ideas for things like shared settings however I think this is a big enough feature request already!

This idea is based on emacs distributions like [spacemacs](https://www.spacemacs.org/) and [doom](https://github.com/hlissner/doom-emacs). I'm not sure if groups is the right name for this, if I built this as an extension I would call them distributions/distros.

This is an idea I have wanted to develop myself, I was going to build it as a standalone extension however I thought it would be good to bring it up here as if it is built in to vscode that would be far better. I would be interested in contributing and attempting this if it is approved as a feature.

This issue https://github.com/microsoft/vscode/issues/49826 is related. As mentioned in the thread, the solution is an extension that uninstalls and reinstalls other extensions as the Extensions API doesn't support enabling and disabling other extensions.

**Comment by dewinterjack** [comment]
I have just found https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup which is a good way of installing a group of extensions however the pack is not known to vscode once installed so you can't enable/disable and do other things

**Comment by gjsjohnmurray** [comment]
I think if you disable an extension pack all the member extensions get disabled.

**Comment by dewinterjack** [comment]
I tried this and it didn’t seem to work properly, I don’t think uninstalling affects the installed extensions either

**Comment by sandy081** [comment]
>  tried this and it didn’t seem to work properly, I don’t think uninstalling effects the installed extensions either

Can you please provide an example?
