### ISSUE TITLE
Search: add a ability to save multiple "files to include" lists

### ISSUE THREAD

**Issue by jan-revay** [microsoft/vscode#125599]
Hi,

there is a text-box "files to include" here:
![Screenshot from 2021-06-05 22-45-17](https://user-images.githubusercontent.com/65253638/120905047-c2ed9c00-c64f-11eb-93d9-82a9de87a896.png)

I use multiple search filters (search in headers: .h,.hh,.H,.hp,.hxx,.hpp,.HPP,.h++,.tcc ; C++ sources: .cc,.cp,.cxx,.cpp,.CPP,.c++,.C,.ii,.CC,.ixx ... python files, .xml files etc..) and currently I have to copy/paste them to the text-box.

As those filters get quite long sometimes, it would be nice if there was a possibility to save those lists in VSC and chose them from a drop-down menu. Same would be nice for the "files to exclude" field.

Thanks for this great code editor!

**Comment by gjsjohnmurray** [comment]
Did you try pressing the cursor-up key when focused in that field?

**Comment by jan-revay** [comment]
Great, that works!

Pressing UpArrow key while having a cursor in the "files to include" field does the trick. Entries are added to the list automatically on every search. This issue can be closed.

I did not find this info in documentation however, so maybe it would be nice to add it there as well.

Thanks for the quick reply.
