### ISSUE TITLE
Go To Symbol takes me to the wrong line when navigating to some symbols

### ISSUE THREAD

**Issue by berlunt** [microsoft/vscode#125575]
Issue Type: <b>Bug</b>

1) Use 'Show All Commands' interface or a mapped keyboard shortcut or type the '#' or '@' symbols in the top bar to initiate the 'Go To Method..." command. 
2) Begin typing "WinMain", when function signature appears in the top bar, use the arrow keys to navigate to it and press enter
3) The cursor will jump a line in the middle of another, unrelated function.
4) Expectation is that the cursor would jump to the function signature of the function selected. 
5) This seems to be broken for most functions in this file but some do seem to work. 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (10.42GB free)|
|Process Argv|. --crash-reporter-id 88d64c34-a0f1-4e14-b0a1-34fcca6e9972|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
todo-tree|Gru|0.0.213
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.5
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.0
gruvbox-material|sai|6.4.5
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by gjsjohnmurray** [comment]
Which language? Providing the symbol information is the responsibility of the relevant language extension, so you probably need to report a reproducible issue to the extension author.

**Comment by berlunt** [comment]
@gjsjohnmurray Issue is in C++
