### ISSUE TITLE
Add a button for toggling *Find in Code* (find outside of comments and string literals).

### ISSUE THREAD

**Issue by 7ombie** [microsoft/vscode#125532]
I often need to search through code, usually for variable names, and really wish the Find tool had a way of only searching actual code, ignoring comments and string literals.

Being able to individually disable searching within comments and/or within string literals would be slightly more flexible, and you could imagine the ability to be more specific still, only searching for a given variable or keyword, or only *within* string literals *et cetera*, but a single button that toggles a distinction between code and not code would be simple, and would go a long way towards.

**Comment by roblourens** [comment]
We have considered this before, but we consider language-specific search features out of scope currently

**Comment by 7ombie** [comment]
Ok, thanks. No problem.
