### ISSUE TITLE
Do not reopen already opened file in other group

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#12552]
- VSCode Version: 1.5.3
- OS Version: win 10

Steps to Reproduce:
1. open two files in two split editor 
2. press ctrl+p twice to jump to last editor
3. rather than jumping to my already opened file in one editor, vscode opens the file in its own editor, it makes my same file opened in two editor and unable to work splitted editors.

**Comment by netwerkz** [comment]
My issue might be related to this one so I will just add it here:
I don't understand why VSCode opens the same file twice(in the same group or not), and it would be nice if we could turn this off if it is a feature.
![screenshot_228](https://cloud.githubusercontent.com/assets/1185797/20642005/c9e00fde-b40c-11e6-87e8-6a355012b51e.png)
![screenshot_227](https://cloud.githubusercontent.com/assets/1185797/20642006/c9e164ce-b40c-11e6-8b90-18ee7e4a4a4d.png)
Is this a bug? If not how can it be turned off?
Should I open a new issue or is it related to the OP's issue?


- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.2|

**Comment by martincohen** [comment]
This is getting really extreme with the files opened twice, especially if the files do not share the same contents, so each is considered as separate file, therefore any changes made to one, are not automatically shared to the other. This leads to being not able to save, hence have to compare and merge every time this happens (and it happens a lot when I use *problems view* to show error location).

Happens in 1.8.1.

**Comment by bpasero** [comment]
You can control this via `"workbench.editor.revealIfOpen": true`

**Comment by victorgarciaesgi** [comment]
@bpasero thanks that's what I wanted!
