### ISSUE TITLE
Launching a debug session with an untitled file results in unattended save prompt

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#125520]
Hello,
I open this issue reported from some users on my team and myself. 

Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.57.0-insiders
- OS Version: Win10 x64 (Windows_NT x64 10.0.18363)
- Date: 2021-06-04T12:21:40.077Z

Steps to Reproduce:

1. Create an untitled file or open a view from a `TextDocumentContentProvider`
2. Focus the editor containing this file
3. Launch a Debug Session

Expected:
- Launch a debug session

Results:
- Launch a debug session and open a prompt to save an untitled file

This behaviour can be annoying for views from `TextDocumentContentProvider` since you might not want to save them but rather use them when debugging.

It is also quite annoying for some users since, for example, when you are updating your `launch.json` file and you didn't save it earlier, VS Code will save it but will use older launch configurations (for example: you edit `program` field with good content but your file is not saved, you launch a debug session, VS Code will save  your `launch.json` but will use previous `program` field and might not work)

Regards.

**Comment by isidorn** [comment]
Please use the following setting 
```
	"debug.saveBeforeStart": "nonUntitledEditorsInActiveGroup"
```

Your extension could set that setting as a language setting default for all of your file types.
Powershell does the same, example https://github.com/PowerShell/vscode-powershell/issues/3338

**Comment by yannickowow** [comment]
Cool, thanks for this reply and sorry for the inconvenience

**Comment by isidorn** [comment]
No problemo. This is not so obvious 😊 
Glad you asked.
