### ISSUE TITLE
Reveal File in Explorer

### ISSUE THREAD

**Issue by duckimann** [microsoft/vscode#125598]
Issue Type: <b>Bug</b>

The default keystroke for reveal file in explorer is "Shift + Alt + R" right? But when i pressed it, it open the Menu Bar instead of reveal the file in explorer.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (9.73GB free)|
|Process Argv|--crash-reporter-id 3e4147c4-6854-43ef-93ba-fbf05e32d734|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
alignment|ann|0.3.0
bracket-pair-colorizer-2|Coe|0.2.0
transformer|dak|1.11.1
vscode-eslint|dba|2.1.20
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
vscode-angular2-emmet|jak|2.0.3
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
sort-lines|Tyr|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by isidorn** [comment]
Please use Preferences > keyboard shortcuts and set that command to whatever shortcut you want
I do not know what is the default on your platform

**Comment by duckimann** [comment]
Thanks for the advice :)
And here is the default on my machine/platform:

![image](https://user-images.githubusercontent.com/46382253/121032257-500e2d80-c7d5-11eb-8f15-e8b192d56e52.png)
