### ISSUE TITLE
Open Remote Repository is missing in the lates Insiders

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#125561]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.57.0-insiders - commit fe1eafc80c07608de52a2f9c99fee103dea77f5e
- OS Version:MacOS Big Sur

Steps to Reproduce:

1. Update VS Code Insiders (June 4th)
2. The `Remote` icon in the Status Bar is missing
3. Even if you install any previous `Remote` extension (Remotes or Codespaces) the icon appears, but no more `Open Remote Repository` option

**Comment by gjsjohnmurray** [comment]
It's there for me:

![image](https://user-images.githubusercontent.com/6726799/120866641-4e9bf580-c588-11eb-9711-33078b26381d.png)

but not after I run `Developer: Reload With Extensions Disabled` from Command Palette:

![image](https://user-images.githubusercontent.com/6726799/120866855-a33f7080-c588-11eb-9d47-a7382a690089.png)

**Comment by alefragnani** [comment]
That's great to hear it is still available. 

Which one should be used? It appears to be the GitHub one, because it has content on Readme.

BTW, do you know this extraction will affect, in any way, how extensions adopt/support Virtual Workspaces? As described here https://github.com/microsoft/vscode/wiki/Virtual-Workspaces?

Thank you
