### ISSUE TITLE
Getting started: completing a setup step should move to next step?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125578]
When I complete in one step in the getting started editor, I would have expected that the next step that was not done yet automatically becomes active.

![image](https://user-images.githubusercontent.com/900690/120885453-4fb13f00-c5e9-11eb-9cbb-405abe5a732c.png)

**Comment by JacksonKearl** [comment]
In many cases you might want to check back on the description or the markdown content at-side even after the "checked" condition is met. For instance in Luna Paint, items are checked on-open, but you still want to read the MD. In theme picker, the item is checked as soon as you try a theme, but you might want to try more. In the C++ walkthrough, some items are checked upon testing the environment, but there's still MD content that might be useful. 

Going to mark this as-designed, happy to hear if you have any thoughts on making certain cases better.
