### ISSUE TITLE
Debug unit test in VS Code fail to attach randomly

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125567]
Issue Type: <b>Bug</b>

4 out of 5 times debug unit test directly in VS Code fails to attach

[vscode-debugadapter-14b70e1f.json.gz](https://github.com/microsoft/vscode/files/6601425/vscode-debugadapter-14b70e1f.json.gz)

VS Code version: Code - Insiders 1.57.0-insider (fe1eafc80c07608de52a2f9c99fee103dea77f5e, 2021-06-04T12:21:40.077Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.97GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
It works fine in the morning and then all of a sudden, it never attaches

**Comment by connor4312** [comment]
In the particular log you attached it looks like there were no tests to run; the runner didn't load any files outside of those included in unit.js. Maybe this is because the compilation was out of date, or the grep didn't find anything.

**Comment by connor4312** [comment]
Fixed it so we wait for breakpoints to verify, not just the session. Still get renderer crashes, but this fixes the particular issue.
