### ISSUE TITLE
Getting started: picking the same theme should also be accepted as done criteria

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125577]
Otherwise I can only see the step completed if a pick a different theme, but maybe I like the one that is active?

![recording](https://user-images.githubusercontent.com/900690/120885428-22649100-c5e9-11eb-89bf-c5736a19b8a3.gif)

**Comment by rzhao271** [comment]
@JacksonKearl if I manually uncheck the box, and then re-select the theme, and then repeat the process, the box doesn't re-check. At that point, I'm also unable to manually check it.

![recording (43)](https://user-images.githubusercontent.com/7199958/123711434-549e9280-d825-11eb-9fa3-f06c3e437783.gif)

**Comment by JacksonKearl** [comment]
Haven't been able to repro the cannot-check bug listed above, this was verified last iteration so will close out and reassign the milestone as no new work has been done.
