### ISSUE TITLE
run

### ISSUE THREAD

**Issue by akash510** [microsoft/vscode#125580]
Issue Type: <b>Bug</b>

run without debugging is not working 

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.62GB free)|
|Process Argv|--crash-reporter-id e9ea65f1-230b-4969-a194-92593bfa85a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.23.0
flutter|Dar|3.23.0
code-runner|for|0.11.4
dart-import|lua|0.3.1
flutter-tree|mar|1.0.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
salesforcedx-vscode-apex|sal|51.16.0
salesforcedx-vscode-apex-replay-debugger|sal|51.16.0
salesforcedx-vscode-core|sal|51.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by gjsjohnmurray** [comment]
What language? What are the steps to reproduce the issue?
