### ISSUE TITLE
Jupyter notebook cell insertion shortcut

### ISSUE THREAD

**Issue by yehdihouldanna** [microsoft/vscode#125642]
Issue Type: <b>Bug</b>

Hello,
I'am working with jupyter notebook on vscode,
i'm having trouble inserting new cells using shortcuts for instance when i press "esc" then "B" , a notebook gets inserted at the top of the notebook and note after the cell I was selecting. the same behavior occurs with "esc A".
My impression is that the pointer to the cell selected gets lost/reseted when pressing esc.
NB : I had a previous version of vscode and everything was fine, but after installing Azure ML extension the GUI of jupyter notebook in vscode changed and this unwanted behavior came with it.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.56GB free)|
|Process Argv|--crash-reporter-id d6af058e-11eb-439c-a70c-869972924612|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
simple-react-snippets|bur|1.2.3
keras-snippet|dev|1.0.0
python-extension-pack|don|1.6.0
prettier-vscode|esb|6.4.0
semantic-data-model-language|fan|0.0.1
MagicPython|mag|1.1.0
identical-sublime-monokai-csharp-theme-colorizer|max|1.0.5
rainbow-csv|mec|1.8.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
vscode-ai-remote|ms-|0.3.0
remote-wsl|ms-|0.56.4
azure-account|ms-|0.9.8
cpptools|ms-|1.4.0
pytorch-snippets|SBS|1.0.2
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by yash112-lang** [comment]
Hello @yehdihouldanna, is this issue is still open, I am new to open source and wants to contrinute.
