### ISSUE TITLE
Cannot view output to stderr in Debug Console for Python.

### ISSUE THREAD

**Issue by kyu-sz** [Microsoft/vscode#12566]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

Seems like this function is not provided or hard to find the option to enable it.
This is crucial to debugging Python using C++ tools like Caffe.

**Comment by chrmarti** [comment]
@DonJayamanne I believe this might be on your side?
