### ISSUE TITLE
Integrated terminal is slow until I change any "terminal.integrated" option

### ISSUE THREAD

**Issue by iFreilicht** [microsoft/vscode#125671]
Issue Type: <b>Bug</b>

# Preface (not that important)

I'm having issues with the integrated terminal in vscode being very slow. This is annoying but also weird, because the rest of vscode actually is very responsive.

I tried launching without extensions, that didn't change anything. Tried a few different rendering options in argv.json, those didn't change anything either.

Then I found  #108590, where the most upvoted solution is to add a few values to the user `settings.json`.  This did work, but only for one terminal. After a bit of investigation, this is what I found:

# What happens

Every newly opened terminal is laggy and very slow to respond, until I change any line in the user `settings.json` that starts with `"terminal.integrated`. Once I add, remove or change the value of any such line and save the file, the terminal starts to speed up and is almost as fast as the system's native terminal. 

This has to be repeated for every additional terminal that is opened, but once a terminal is open and was sped up this way, it stays fast.

# Steps to reproduce

1. Open vscode
2. Open an integrated terminal
3. Start any terminal app that re-draws a lot of lines quickly to really see the difference
4. Open the user `settings.json`
5. Add a line `    "terminal.integrated.not_a_real_option": false,`
6. Notice how the terminal speeds up

You can repeat all these steps and modify the last one to change the value, change the key or remove the line again, and it still works exactly the same way.

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T21:58:14.757Z)
OS version: Linux x64 5.4.0-73-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (5.64GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 01bd49d6-c0f6-4960-a83b-c3e9b850dcb4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by Tyriar** [comment]
Does setting `terminal.integrated.gpuAcceleration` to `"off"` fix it?

**Comment by iFreilicht** [comment]
@Tyriar No, it actually breaks the "fix" as well. Interestingly, setting it to `"on"` also does. It only "works" (meaning it stops lagging once I change any `terminal.integrated.*` option) when `terminal.integrated.gpuAcceleration` is either not set or set to `"auto"` manually.

So I did a few more experiments and wrote down every step as I did it:

1. Remove all `terminal.integrated.*` options from `~/.config/Code/User/settings.json`
2. Reload with extensions disabled
3. Open an integrated terminal
4. Start a terminal app that re-writes a lot of lines -> very laggy
5. Add the line `"terminal.integrated.gpuAcceleration": "off"` and save -> Very slight speed up, but still quite laggy
6. Change the line to `"terminal.integrated.gpuAcceleration": "on"` -> Very laggy again
7. Change the line to `"terminal.integrated.gpuAcceleration": "auto"` -> **No lag, terminal is very responsive**
8. Remove the line again -> Very laggy again
9. Add the line  `"terminal.integrated.asdf": "asdf"` -> **No lag, terminal is very responsive**
10. Remove the line again -> **No lag, terminal is very responsive**
11. Add the line `"terminal.integrated.gpuAcceleration": "auto"` -> **No lag, terminal is very responsive**
12. Stop the terminal app
13. Close the integrated terminal (by typing `exit` so it actually properly closes)
14. Open an integrated terminal again
15. Start the terminal app again -> *Very laggy* (so the `"auto"` value doesn't actually change anything)
16. Remove the line  `"terminal.integrated.gpuAcceleration": "auto"` -> **No lag, terminal is very responsive**

This is so extremely weird. It seems like somehow, the integrated terminal enters some weird loop or state that delays the rendering, and:

1. it breaks out of this loop/leaves that state as soon as a change in its configuration is made
2. the `"terminal.integrated.gpuAcceleration"` option being either `"off"` or `"on"` prevents this from happening

I'll try to reproduce this on my other PC in the evening to make sure it's not just one machine this happens on. This is probably the weirdest bug I ever encountered in vscode :D

**Comment by Tyriar** [comment]
@iFreilicht could you try doing a performance profile via the Help > Toggle Developer Tools? Hopefully the lagginess would show up in the profile.

**Comment by iFreilicht** [comment]
@Tyriar I did. The steps I took were like this:

1. Start the integrated terminal
2. Type in `tree /`
3. Start profiling
4. Click inside the terminal and press Enter to start the command
5. Wait for ~10 seconds
6. Stop profiling
7. Stop tree with Ctrl+C
8. Exit terminal with Ctrl+D
9. Repeat, but change `settings.json` once before starting profiling, and once during profiling

And it does indeed show up:

![image](https://user-images.githubusercontent.com/9742635/121328439-9d44e900-c914-11eb-9fd1-75c8584dc911.png)

You can see that a lot of frames show a warning, and all of those seem to be the same "Long task took {60-80}ms", which in most cases is caused by "System", not the actual rendering or scripting. In a few instances, there's also about 20ms spent on scripting. In those cases, the offending function seems to be `texImage2D`:

![image](https://user-images.githubusercontent.com/9742635/121329720-c154fa00-c915-11eb-9e29-64e63beb2144.png)
![image](https://user-images.githubusercontent.com/9742635/121329777-cb76f880-c915-11eb-882e-bff0635ab106.png)

But in most cases, System is to blame:

![image](https://user-images.githubusercontent.com/9742635/121330045-024d0e80-c916-11eb-9699-b8eb8cb5c4bb.png)
![image](https://user-images.githubusercontent.com/9742635/121330153-142eb180-c916-11eb-8bf5-d2afa105936f.png)

Meanwhile, after changing a single value, the profile looks much better:

![image](https://user-images.githubusercontent.com/9742635/121328577-ba79b780-c914-11eb-8791-ddd4fcc93474.png)

No warnings, reasonable time spent in scripting and system.

I also made a profile where I started the tool, (I used `tree /`, which outputs a LOT of lines) and then changed the `settings.json`.
You can very clearly see the change:

![image](https://user-images.githubusercontent.com/9742635/121333567-3544d180-c919-11eb-8e2d-665caa7221f4.png)

I saved those three profiles as a full dump, so you can have a look around:

[Profile-20210609-full.zip](https://github.com/microsoft/vscode/files/6622948/Profile-20210609-full.zip)

**Comment by KaeLL** [comment]
There's something really wrong with the terminal. Ever since Oct/20 or something, an update made the terminal ridiculously slow to respond. Just do anything that outputs data to the terminal relatively fast, like `cat`ing a big file, or capturing serial port data through minicom even at 921600 baudrate or something, and compare it to gnome-terminal or Konsole, or other native terminal. The serial test is my favorite, because you can just tell that the terminal is slow because it keeps spitting logs even after tens of seconds after I turned off the serial device.

**Comment by Tyriar** [comment]
Sorry about the delay here, bit overwhelmed with notifications.

Looking at that profile where you're running tree and switch it seems like the system problem is specific to the webgl renderer. So you seem to be on one of the problem hardware/OS/driver combinations where the webgl renderer has issues, switching a setting seems to I'm not sure we can detect a problem like this because it's system causing the problems, not JS code. For the renderer fallback with gpuAcceleration auto we rely on the canvas not being able to generate a webgl2 context by throwing, but it seems like it's getting the context fine in your case as I see `texImage2D` calls in the profile.

Here are some things to look at:

- Main fix: You can now set `"terminal.integrated.gpuAcceleration": "canvas"` to workaround this exact issue which forces the canvas renderer (not as fast as webgl but much faster than the dom renderer)
- Try updating your graphics drivers or complain to the vendor
- If you're in a VM try disabling gpu acceleration

I'm open to ideas on how to detect this reliably but closing this as I don't think we can do anything about this and we added the ability to use the canvas renderer explicitly back.

**Comment by iFreilicht** [comment]
Thanks! It seems like `"terminal.integrated.gpuAcceleration": "canvas"` fixes this sufficiently on one of my machines. I'll try it on the other once I have access to it.
