### ISSUE TITLE
Only seeing a `pwsh (2)` but not a `pwsh` 1?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125683]
Testing #124836

I chose "Select default profile" and got:
![image](https://user-images.githubusercontent.com/2644648/121061271-7a7dcd80-c778-11eb-81b1-8f7a64c4939e.png)

Notice the `pwsh (2)`? Where's `pwsh` one? 🤔 

This is the important configuration I had set when I started this:
```json
"terminal.integrated.shell.osx": "/Users/tyleonha/.powershell-daily/pwsh",
    "terminal.integrated.shellArgs.osx": [
        "-Login"
    ]
```

**Comment by Tyriar** [comment]
We don't show the legacy pwsh in the profile picker, it looks like that's what's being detected as 1. Going to close this since it should only happen when using the old settings where you get nagged to move off them via the notification and settings warnings
