### ISSUE TITLE
I am not seeing extension error/warnings indication in status bar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1256]
I tried the following scenarios on mac:
* causing an error in an extension by making its package.json invalid
* installing the same extension twice with different name so that one overrides the other

I get errors and warnings for both in the dev console, so I assume that the status bar indicator does just not work for me.

![image](https://cloud.githubusercontent.com/assets/900690/11781514/aa642d0c-a26a-11e5-90e0-a75dae2913ab.png)

**Comment by isidorn** [comment]
@bpasero I will check with @alexandrudima why those errors do not get triggered in the place I am listening to.
In the meantime in order to get some UI, try to duplicate an extension and just have a different publisher there.

**Comment by bpasero** [comment]
@isidorn still no luck, that guy is just remaining silent:

![image](https://cloud.githubusercontent.com/assets/900690/11784723/3daec60e-a27e-11e5-8279-f83677033ea5.png)
