### ISSUE TITLE
Put structure into Doc, And Show into Hover

### ISSUE THREAD

**Issue by WingDust** [microsoft/vscode#125648]
When I write a huge Interface , Mostly that  write be a  Tree structure Interface
like animal family this
```ts
interface Animal{
  felidae:{ // 猫科动物
    acinonyx:{ // 猎豹亚科
      "acinonyx jubatus":string // 猎豹
    },
    tiger:string 
    lion:string
  },
}
```
When I use like this type Object,will be
```ts
let a: Animal = {
  felidae: {
    acinonyx: { "acinonyx jubatus": "111" },
    tiger: "222",
    lion: "333",
  },
};
a.felidae.acinonyx["acinonyx jubatus"] = "444";
```
this put all into Object ,that make  **Mental burden small but code red tape**. 
if Interface like this 
```ts
interface Animal {

  //#region felidae

  //#region acinonyx
  "acinonyx jubatus": string; // 猎豹
  //#endregion

  lion:string
  tiger:string;

  //#endregion

}
```
Use will be 
```ts
let a :Animal = {"acinonyx jubatus":"111",tiger:"222",lion:"333"}
a["acinonyx jubatus"] = "444";
```
this way make code level Reduced , but **Mental burden big ,code clear** . 

The Mental burden is big ,Because When Interface-attribute's counter is huge , attribute is difficult to find .
In old way use structure classify to find ,It's mean When we write code  we only need to  think about dotout what . 
Old way thinks  only one thing.
New way need to  think more than one things .
Although  we still make mistakes. So We have another action ,that is proving the Type is right .In VSCode mostly use Mouse Hover var (also show the tsdoc). 

However Why not we put A small piece of a line in a tree structure  into Mouse Hover Tip ?

Each line in the tree structure is unique ，So  A small piece of a line in a tree structure can prove which line 
 A small piece of a line  just be her father will be fine 

definition:
![image](https://user-images.githubusercontent.com/45911286/120982521-62737180-c7ab-11eb-923f-753fd90c8264.png)
Use:
![image](https://user-images.githubusercontent.com/45911286/120982756-9cdd0e80-c7ab-11eb-9134-fe74442293fa.png)
tsdoc:
![image](https://user-images.githubusercontent.com/45911286/120983269-1f65ce00-c7ac-11eb-9afc-2e6f9e463f79.png)
Same Use:
![image](https://user-images.githubusercontent.com/45911286/120983648-7a97c080-c7ac-11eb-9348-e55c336ddfd1.png)

More Design for Code complement：
Code complement allow Object dotout  region name ,When structure line finished ,clean region name turn one attribute .

![image](https://user-images.githubusercontent.com/45911286/120985767-83899180-c7ae-11eb-81d1-17b30bc25a27.png)

**Comment by mjbvz** [comment]
I'm having trouble understanding this issue but believe it may be something an extension could try to implement, potentially using a TypeScript service plugin
