### ISSUE TITLE
Blank Terminal on Ubuntu

### ISSUE THREAD

**Issue by indrajitb** [microsoft/vscode#125662]
Issue Type: <b>Bug</b>

The terminal window/screen/tab goes completely blank after logging in from a laptop locked state. I have to open a new terminal tab to proceed, so it's completely unknown what's happening on the original terminal tab.
This happens quite regularly, after logging in, say after 1-2 hours.

Attaching screenshot.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 3231)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.41GB (0.67GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id db06431f-875e-42b1-86cb-d330c9830f07|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.12.0
aws-toolkit-vscode|ama|1.25.0
aws-amplify-vscode|aws|0.0.4
prettier-vscode|esb|6.4.0
vscode-pull-request-github|Git|0.26.0
go|gol|0.25.1
vscode-docker|ms-|1.13.0
remote-containers|ms-|0.177.2
vscode-typescript-next|ms-|4.4.20210606
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.25.1
vscode-manifest-yaml|Piv|1.25.1
vscode-spring-boot|Piv|1.25.1
dynamodb-vscode-snippets|raf|0.0.6
java|red|0.79.2
velocity|sod|0.2.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

![Screenshot from 2021-06-07 17-34-03](https://user-images.githubusercontent.com/5278021/121015533-b9cc0e80-c7b8-11eb-8000-e4a66708407b.png)

**Comment by meganrogge** [comment]
any errors in the dev tools console?
