### ISSUE TITLE
Rust grammar: Doc comments in Rust are actually not comments, therefore shouldn't be marked as such

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/vscode#125623]
Comments are pieces of code that is usually ignored and can be placed anywhere. Doc comments in most languages are usually ignored by the compiler/interpreter. But Rust's so-called "doc comments" are different from normal comments:
* Under every outer doc (`/// ...`, `/** ... */`, or `#[doc = "..."]`) must be a language item. Otherwise, it is a syntax error.
* Every inner doc (`//! ...`, `/*! ... */`, or `#![doc = "..."]`) must be placed within a language item. Otherwise, it is a syntax error.
* Doc comment is just syntactic sugar for the `#[doc]` attribute.

## Suggestion

Doc comment in Rust is a flavor of Markdown, therefore it should be highlighted as a Markdown code snippet.

**Comment by alexr00** [comment]
Moved to the repo that we get our rust grammar from: https://github.com/dustypomerleau/rust-syntax/issues/20

**Comment by KSXGitHub** [comment]
Why didn't the VS Code team just create an organization to host all vscode repos?

**Comment by alexr00** [comment]
https://github.com/dustypomerleau/rust-syntax is owned by a community member who isn't affiliated with vscode. We don't have any control over that project and are very happy that there's a community member out there who wants to make a rust grammar!
