### ISSUE TITLE
My Comment codes were gone.

### ISSUE THREAD

**Issue by mengjiangtao** [Microsoft/vscode#12567]
- VSCode Version:1.5.3
- OS Version:windows 10 x64 

`
class Human {
        public static void Sleep(){
            Console.WriteLine("Human sleep");
        }

        public static void Eat(){
            Console.WriteLine("Human Eat");
        }
    }

    public delegate void Doing();
    class Program{
        static void Main(String[] args){
            // Item[] tt = {
            //     new Item(100),
            //     new Item(10),
            //     new Item(1),
            //     new Item(-1),
            // };

            // BubleSorter.Sort(tt,Item.CompareID);
            // foreach(var ts in tt){
            //     Console.WriteLine(ts.ToString());
            // }
            Actiot op = Human.Sleep;
            op += Human.Eat;
            op();

        }
    }
`
Steps to Reproduce:
1.Comment these codes,above Actiot op = Human.Sleep;  in Main method.
2. I write Action to Actiot,that's wrong,so the system will show me a tips.
3.when i use ctrl + .   and choose "Change Actiot to Action",all the comment codes will be clear.

**Comment by chrmarti** [comment]
Thanks for the detailed report. Since this functionality is provided by the C# extension, please file it with them.
