### ISSUE TITLE
[Feature] Remove Duplicate Lines

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#125628]
Would be good to add `Remove Duplicate Lines` quick action.

This is similar to `Sort Lines Ascending` or `Sort Lines Descending`.

**Comment by ArturoDent** [comment]
There are extensions that will do this, such as [Transformer](https://marketplace.visualstudio.com/items?itemName=dakara.transformer#overview).  See https://stackoverflow.com/a/51645258/836330
