### ISSUE TITLE
[FEATURE] Cross Save Plugins & Settings Through Github/Microsoft Accounts

### ISSUE THREAD

**Issue by Brayan2134** [microsoft/vscode#125629]
As a first-year Computer Science student who's always jumping from computer-to-computer (whether it be at work or home), I find it incredibly frustrating that even though I sign into Github or my Microsoft account for VSC, none of my theme settings, plugins, or personal preferences are saved across accounts. 

Granted there's probably a more technical way to solve this issue, but my idea would be to simply have a JSON file uploaded and linked to our GH/Microsoft account that contains every plugin and setting change we wish to have. Once we sign in and authenticate, we receive a prompt asking us if we'd like to sync our preferences from our accounts onto the local computer.

**Comment by IllusionMH** [comment]
VS Code has Settings Sync functionality but you need to enable it. But it's saved not across different accounts, but same account on different machines.

See https://code.visualstudio.com/docs/editor/settings-sync for details.

Is there anything left in your reqests?
