### ISSUE TITLE
npx create-react-app new project crashing Intellisense

### ISSUE THREAD

**Issue by richieReact** [microsoft/vscode#125672]
Issue Type: <b>Bug</b>

Making a new project and Intellisense not working.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 6, 4|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 247c18b3-120a-4e95-a547-079a855af1b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
material-icon-theme|PKi|4.6.0
material-theme|zhu|3.10.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by richieReact** [comment]
Well I don't know, I'm using regular old VSCode on Mac. One interesting thing though is that Intellisense is still working on other projects, just not this new one. Should I give that Insiders Build a shot?

**Comment by mjbvz** [comment]
Yes please try the insiders build

**Comment by richieReact** [comment]
I tried with the Insider's build and the same action happened.

**Comment by richieReact** [comment]
This might help: This error has only come since using npx create-react-app since 3 days ago. All of my other windows with projects have Intellisense working.

**Comment by richieReact** [comment]
Anything else I could try?

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by richieReact** [comment]
As soon as I set the log to verbose Intellisense stopped crashing and now it works on both the Insider's build and regular one. Thank you so much!

**Comment by mjbvz** [comment]
Ok, let me know if you see this again
