### ISSUE TITLE
problem with php help please! 

### ISSUE THREAD

**Issue by lucalquemist** [microsoft/vscode#125636]
when touching serve project this happens:

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required 'c:\Users\lucas\.vscode\extensions\brapifra.phpserver-3.0.2\src\server\logger.php' (include_path='.;C:/laragon/etc/php/pear') in Unknown on line 0

**Comment by IllusionMH** [comment]
/causedByExtension

Please report in extension repo or more likely its duplicate of https://github.com/brapifra/vscode-phpserver/issues/93 so it make sense to add info there
