### ISSUE TITLE
able to replace extended characters (\n) like notepad++

### ISSUE THREAD

**Issue by tins820** [microsoft/vscode#125675]
Issue Type: <b>Feature Request</b>

able to replace extended characters (\n) like notepad++

VS Code version: Code - Insiders 1.57.0-insider (fe1eafc80c07608de52a2f9c99fee103dea77f5e, 2021-06-04T12:21:40.077Z)
OS version: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
/needsMoreInfo

How are you truing to do that?
You should be able to do that by enabling RegEx mode for search/replace

**Comment by tins820** [comment]
@vscode-triage-bot  sorry. i was just using the "Report Issue" right on the Visual Studio Code, i have no idea that there are some guidelines. 

@IllusionMH i do not think it is working by enabling RegEx mode.
for example, i want to replace "\r\n" to , (comma).
it works in reverse but not in the above case

**Comment by sandy081** [comment]
@tins820 Are you trying this in the Search view or in Editor find functionality?

**Comment by IllusionMH** [comment]
VS Code editor normalizes line endings and doesn't keep separate CR characters in files with CRLF EOLs.
Just use `\n` in Find widget (in editor) to replace it to `,` - this will replace both characters CRLF.

Find in files will match both characters separately as it doesn't do normalization and searches on disk (if file is not in open tab)

**Comment by sandy081** [comment]
@tins820 FYI - please check the comment 

> Are you trying this in the Search view or in Editor find functionality?
