### ISSUE TITLE
Link to Learn More of virtual workspace leads to Bing website

### ISSUE THREAD

**Issue by ayatokura** [microsoft/vscode#125620]
Issue Type: <b>Bug</b>

1. Open Code-Insiders
2. A notification will appear on the screen with "Manage Trust" and "Learn More" links.
[Notification Message]
Some features are not available because the current folder is backed by virtual file system and is note trusted. You can trust this folder to enable some of there features." 
3. Click "Learn More" link.
4. The browser automatically launched and displayed the Bing site (https://www.bing.com/?ref=aka&shorturl=vscode-virtual-workspaces)

VS Code version: Code - Insiders 1.57.0-insider (fe1eafc80c07608de52a2f9c99fee103dea77f5e, 2021-06-04T12:19:25.391Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 24e3eab7-335d-452f-bf6a-00d061debdb0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.26.0
gc-excelviewer|Gra|3.0.42
vscode-language-pack-ja|MS-|1.57.0
remote-containers|ms-|0.182.0
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare-pack|ms-|0.4.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by ayatokura** [comment]
Add the screen shot
![VSCode_Insiders_LearnMore](https://user-images.githubusercontent.com/12283147/120922144-74e5a080-c702-11eb-828e-a9766f49b148.png)

**Comment by gjsjohnmurray** [comment]
I think PR #125512 by @aeschli means that this banner no longer appears, in which case the issue can be closed.

**Comment by aeschli** [comment]
Yes, we no longer use the banner for virtual workspaces.
