### ISSUE TITLE
Ghost text in dark theme is too bright

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125646]
This came in as feedback from @eamodio 

* configure `"editor.suggest.preview": true`
![image](https://user-images.githubusercontent.com/5047891/120983476-03493900-c77a-11eb-819f-073c91268a72.png)

Using https://webaim.org/resources/contrastchecker/ I believe the color can be made darker on the dark theme, as the current contrast is very high:

![image](https://user-images.githubusercontent.com/5047891/120983994-81a5db00-c77a-11eb-8d64-7d91ddfbdf27.png)

**Comment by isidorn** [comment]
Just make sure to have a larger contrast ratio than the required `3:1` for accessibility. More details for those interested can be found [here](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html).

Thank you

**Comment by hediet** [comment]
I reduced it to 3.1:1 for dark theme:

![image](https://user-images.githubusercontent.com/2931520/121005769-6fcf3280-c790-11eb-85bc-777048e1fa53.png)

It is 3.6:1 for light theme: (personally, I would not reduce it to 3:1 here)

![image](https://user-images.githubusercontent.com/2931520/121005844-84132f80-c790-11eb-8f63-1f0a0ec919c2.png)


Btw. [this](https://www.tpgi.com/color-contrast-checker/) tool is amazing.
