### ISSUE TITLE
Terminal tabs transition to 1 tab polish

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#125680]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider
Commit: bf84ee619e0b67443d0307c04348fa575bc3c363
Date: 2021-06-07T12:43:59.742Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

Start with 2 tabs:
![image](https://user-images.githubusercontent.com/2644648/121060594-b6646300-c777-11eb-80a3-632caefc0b98.png)

Delete one gets you this:
![image](https://user-images.githubusercontent.com/2644648/121060631-c1b78e80-c777-11eb-8719-68db88e38d95.png)

Move the cursor out of tabs location gets you this:
![image](https://user-images.githubusercontent.com/2644648/121060670-cf6d1400-c777-11eb-8954-3ce8867bb8fb.png)

I would expect _either_:
* (Preferred) The `pwsh` above the tabs (single tab location) wouldn't show up until you mouse out of tab location
* ~When going to one tab the tabs disappear instantly and only shows `pwsh` in the usual single tab location~

**Comment by meganrogge** [comment]
Your expectation is what we had originally. We decided to go with the mouse out approach bc when you're deleting terminals with the inline trash icon, it feels jumpy/annoying to have to then navigate to the single tab to dispose of it.

**Comment by Tyriar** [comment]
I think going for the preferred option would get complicated, it shows up based on a context key based on the number of terminals, probably not worth it. The second point is how it used to be and we changed it by design.

**Comment by TylerLeonhardt** [comment]
> Your expectation is what we had originally.

> The second point is how it used to be and we changed it by design.

I 100% agree with this change. Less jumpy.

> In that case, I agree with you - we shouldn't show the single tab item until the mouseout.

> I think going for the preferred option would get complicated, it shows up based on a context key based on the number of terminals, probably not worth it.

Yeah this is ideal. Didn't know if you had a context key around tab section (as in 2+ tabs) being visible. If it's too complicated we can close this.

**Comment by Tyriar** [comment]
I think to do this properly we'd need yet another context key just for this, and then make this beast even more complicated:

https://github.com/microsoft/vscode/blob/d8f27065a795d17a5a6eb174c3b32dbfc4af3ec6/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L354-L375
