### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by hshuldberg** [microsoft/vscode#125688]
Issue Type: <b>Performance Issue</b>

My terminal was working just fine until a couple of days ago.  Now when I try to run in the terminal none of the codes or prompts work.  In my previous files, I have saved I was finally able to get them running in the terminal but now all the

 new files I create and have been working on no longer will run and show in the terminal.  I don't get an error code per se but it shows where the file is saved but does not go on further to run the code.  I have been searching the internet for the last few days to try to fix this issue with no luck finding an answer.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.56GB (5.41GB free)|
|Process Argv|--crash-reporter-id 85693102-2673-4c0c-bbdc-d712e97b1d1a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 18044	code main
    0	   336	   436	   gpu-process
    0	    21	 13920	   crashpad-handler
    0	   148	 16128	   window (week7group1.py - Coding_with_Stan - Visual Studio Code)
    0	    76	 18992	     extensionHost
    0	    58	  4368	       "C:\Users\hshul\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\hshul\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18992
    0	    63	 18160	       electron_node bundle.js 
    0	    10	 19360	     watcherService 
    0	     5	  2172	       console-window-host (Windows internal process)
    0	    38	 18620	   utility
    0	    78	 18636	   shared-process
    0	    58	 16308	     ptyHost
    0	    46	  7328	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
   13	    14	 15168	         "C:\Users\hshul\AppData\Local\Microsoft\WindowsApps\python3.9.exe" c:/Users/hshul/Desktop/coding/Coding_with_Stan/week7group1.py
    0	    70	  9360	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 13220	       console-window-host (Windows internal process)
    0	     6	 23372	       console-window-host (Windows internal process)
    0	    83	 19268	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (week7group1.py - Coding_with_Stan - Visual Studio Code)
|    Folder (Coding_with_Stan): 68 files
|      File types: jpg(37) py(19) png(7) json(1) jfif(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by hshuldberg** [comment]
The first image I can get all those codes to work.  The second image when I go to run the code stops right were it shows where the file is located.
<img width="721" alt="helloworld" src="https://user-images.githubusercontent.com/82780973/121095704-0f4eee00-c7ae-11eb-9e33-2a8516ee81f0.png">
<img width="722" alt="week7" src="https://user-images.githubusercontent.com/82780973/121095713-1544cf00-c7ae-11eb-842a-df12471b981c.png">

**Comment by hshuldberg** [comment]
I have already searched and haven’t found a solution to this issue!  I have
even tried some in hopes it might work but nothing I’ve tried has worked!
I’ve uninstalled everything in hopes to reset it all and it still doesn't
work!
