### ISSUE TITLE
Cursor blinking issue

### ISSUE THREAD

**Issue by BookmDan** [microsoft/vscode#125681]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: 10.15.6 (19G2021)

Steps to Reproduce:

1. When I type in ".card-body" a div is formed.
2. Then for example, sometimes I will type and automatically I am within the div "> <"
3.  This does not happen and instead there is a blinking cursor. The only way to get out of it is to click to end of line and smash keys. Otherwise, I risk deleting a random set of codes. 
4. This also happens when I sometimes go away from VS Code and come back to it, there is the broad cursor again. When it is a slim cursor, I am able to type. But usually this is not the case. 

<img width="1440" alt="Screen Shot 2021-06-07 at 10 07 28 AM" src="https://user-images.githubusercontent.com/8926023/121061105-4bfff280-c778-11eb-8f75-1324bca4f2cd.png">

**Comment by alexdima** [comment]
@BookmDan It looks like you have installed the vim extension and you might not have wanted to use vim input for vscode. So simply disable or uninstall the vim extension.

**Comment by BookmDan** [comment]
I did disable all extensions. 
Now I'm trying to figure out how to enable the extensions...
But yes.
