### ISSUE TITLE
Cannot touchpad scroll horizontally in notebook error output

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125698]
Here:
![image](https://user-images.githubusercontent.com/8586769/121089947-b9257f00-c79c-11eb-9d68-e465d78195dc.png)
I cant use my touchpad to scroll. I have to click on the scrubber and drag it. MacOS

**Comment by rebornix** [comment]
Tested with latest Insiders, horizontal scrolling now works.
