### ISSUE TITLE
iPadOS: Can't tap notification icon on the status bar 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125686]
Tap on the notification icon on the status bar on iPadOS doesn't work.

**Comment by isidorn** [comment]
This works fine for me with latest Safari.
I am just tapping on the 🔔  icon and the notification area gets nicely opened.

@rebornix do other status bar items work for you? Only the notification bell does not work?

**Comment by rebornix** [comment]
@isidorn right, so weird that all others work fine, so it has nothing to do with the home indicator.

**Comment by isidorn** [comment]
@bpasero can you maybe give it a try? Is there something special how we handle the notification status bar item? I think it should be the same as all the other?

**Comment by isidorn** [comment]
Aaaa I can now also repro. I could not repro because the keyboard was popped out for me, so the notification was not in the exact bottom right corner. Which proves that there is a bottom right zone that you cannot touch...
As a workaround maybe we put a stupid Smile face in the corner? Which I removed for the iPad...

**Comment by bpasero** [comment]
Btw when I tried today, turns out I cannot click any of the status entries via touch. I get hover feedback though, so it seems to me that the area is sensitive to touch, but does not react to it properly.

**Comment by isidorn** [comment]
Yeah I see the same. 
Clicking with the external mouse works nicely though.
The problem seems to be that the bottom area is reserved for touch to drag out the dock.

Only fix would be that we render the whole workbench pushed some pixels to the top, which I think we were previously doing. However I really dislike this solution since we loose on screen real estate.

So I suggest to not do anything for now. Workaround: external mouse.

**Comment by rafrafek** [comment]
I have Android tablet and I can't change telemetry settings on vscode.dev opened in Chrome using touch. External mouse works.
![obraz](https://user-images.githubusercontent.com/23004737/140503303-e2dc5291-c114-4311-9abe-e4e09a741db6.png)

**Comment by isidorn** [comment]
@rafrafek  Can you please file a new issue for this? Thank you

**Comment by fotiDim** [comment]
I am using the Flutter extension on a Surface Pro and in the status bar I would normally select the device that I want to deploy to. Due to this bug I cannot select a device right now. Issues happens both using touch and stylus but does work using the mouse.

**Comment by isidorn** [comment]
@bpasero previously every HTML element would listen on a global `tap` event and would then try to figure out if the `touch` event happened on that element. This was firing too many events and was not performant. 
So we introduced the `Gesture` helper, such that only element that are interested in touch would go to the `Gesture` and register there. `Gesture` would be a central place to listen to the global `tap` event and then re-send events to the right registered clients.

Having said all of that it seems like the status bar is not properly listening on onTap events coming from gesture.
Example how it should be done https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L78

**Comment by bpasero** [comment]
No, I tried listening to the `Tap` event, and it did not work for me. I wonder if adding the listener to `this.labelContainer` is right or wrong, not sure.

**Comment by bpasero** [comment]
Looks like it needs `Gesture.addTarget` on any element you listen on. The combination of both seems to work, see https://github.com/microsoft/vscode/commit/fcbf1eb903ad019fbd003d754067d0728d79d498

The original issue still persists.

**Comment by isidorn** [comment]
@bpasero great, thanks for fixing this 👏
