### ISSUE TITLE
Custom keyboard repeat rate not honored under Wayland

### ISSUE THREAD

**Issue by mikeroll** [microsoft/vscode#125666]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2, 1.57.0
- OS Version: Arch Linux

Steps to Reproduce:

0. Use Sway with a non-default keyboard repeat rate configured (pretty fast in my case).
1. Run vscode with `--enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Press and hold keys, observe that the repeated characters are inserted much slower than in the rest of the system. This includes all keys and affects everything from the editor to the terminal to the command pallete etc.

**Comment by mikeroll** [comment]
Seems to be an Electron thing - I've installed Slack to test this and the behavior is the same.

**Comment by vipulmathur** [comment]
I can confirm this behavior. Keyboard repeat with Wayland works properly everywhere except Electron apps like Slack, VSCode.

**Comment by univerz** [comment]
doesn't work with `kwin` too.

**Comment by mikeroll** [comment]
The cause is deep down in chromium, [right here](https://github.com/chromium/chromium/blob/617d5121d3596f9f57660d963d17f86aa109567d/ui/ozone/platform/wayland/host/wayland_keyboard.cc#L198):
```
keyboard->auto_repeat_handler_.SetAutoRepeatRate(
      base::TimeDelta::FromMilliseconds(delay),
      base::TimeDelta::FromMilliseconds(rate));
}
```
So they treat the rate (== characters per second) as the interval (== time between key repeats). The faster you set your repeat rate, the slower it goes.

I'm yet to file a chromium bug about this - if someone beats me to it, kindly link it here.

**Comment by mikeroll** [comment]
Reported upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1238517

**Comment by mikeroll** [comment]
Quick update - this have been fixed (validated) in Chromium 94, which is the base for Electron 15. Now to wait until VSCode is updated to use Electron 15+.

**Comment by JasonWoof** [comment]
WORKAROUND for sway users:

`swaymsg -t subscribe -m '[ "window" ]' | jq -r --unbuffered .container.app_id | while read x; do if [ "$x" = Code ]; then rate=14; else rate=70; fi; swaymsg "input type:keyboard repeat_rate $rate"; done`

where 70 is your desired rate (events per second) and 14 is 1000 divided by that number.

You could get all fancy and make it into a shell script:

```
#!/usr/bin/env bash

prevRate=70
while read x; do
    if [ "$x" = Code ]; then
        rate=14;
    else
        rate=70;
    fi
    if [ "$rate" != "$prevRate" ]; then
        swaymsg "input type:keyboard repeat_rate $rate"
        prevRate="$rate"
    fi
done < <(swaymsg -t subscribe -m '[ "window" ]' | jq -r --unbuffered .container.app_id)
```

and run it from your ~/.config/sway/config by adding: 

`exec /path/to/above/script`

**Comment by mikeroll** [comment]
This was finally resolved quite a while ago.
