### ISSUE TITLE
TypeScript - tsconfig.json paths resolve wildcards

### ISSUE THREAD

**Issue by beckend** [Microsoft/vscode#12563]
- VSCode Version: 1.5.3
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:

1.  tsconfig.json
```json
{
  "compilerOptions": {
    "strictNullChecks": false,
    "noEmitHelpers": true,
    "listFiles": true,
    "target": "es2015",
    "outDir": "./tmp",
    "module": "commonjs",
    "moduleResolution": "node",
    "pretty": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "removeComments": false,
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "*": [
        "app/*"
      ]
    }
  },
  "files": [],
  "include": [
    "custom-typings/index.d.ts",
    "app/**/*.{ts,tsx}",
    "shared/**/*.{ts,tsx}",
    "test/**/*.{ts,tsx}"
  ],
  "exclude": [],
  "filesGlob": [
    "custom-typings/index.d.ts",
    "node_modules/@types/**/*.d.ts",
    "app/**/*.{ts,tsx}",
    "shared/**/*.{ts,tsx}",
    "test/**/*.{ts,tsx}"
  ],
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker":  true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

```

2. Does not resolve: 
<img width="741" alt="screen shot 2016-09-24 at 23 28 01" src="https://cloud.githubusercontent.com/assets/6056334/18811411/c564d6b8-82ae-11e6-89c2-53af90257827.png">

A sidenote: it does not seem to include `custom-typings/index.d.ts` which will declare the webpack require correctly either...

I'm using this tsconfig in `atom` editor and everything works fine.

**Comment by beckend** [comment]
Ran `tsc` with `--traceResolution` and it seems like it does not respect paths at all.
```json
"paths": {
      "*": [
        "app/*"
      ]
    }
```
Always trying to resolve with "node_modules" in prefix and ultimately will fail.
Then maybe this issue is better suited in typescript issue tracker, if it's not intended behaviour.

**Comment by beckend** [comment]
Another debug phase, stumbled upon [#10321](https://github.com/Microsoft/TypeScript/issues/10321).
So in order for this to work at the moment, I had to remove all 3 properties from `compilerOptions`, 1 or two did not cut it.
These are:
`files`, `include`, `exclude`

**Comment by waderyan** [comment]
@beckend thank you for opening this issue and for helping us identify the crux of the issue so we can fix it. 

1. Can you provide me with code I can copy and paste or clone on my own machine? The smaller and simpler the code example the better for isolating the issue. 
2. Can you reduce what you have in `tsconfig.json` to get to the smallest configuration that reproduces the issue?

**Comment by beckend** [comment]
Here is the minimal [repo](https://github.com/beckend/typescript-tsconfig-paths-issue).
For vscode the culprits props are `include` and `files`, I have no idea what logic hierarchy applies and would love to know their priorities where they apply.


VSCODE:
* `tsconfig.json` is the only working one 
* the rest of tsconfigs will all fail.

TSC:
`tsc app/index.ts  --outDir ./trace --traceResolution > ./trace/tsconfig.txt`
* None of the configs was able to resolve

**Comment by waderyan** [comment]
Hmm... seems to be working in the latest bits (VS Code Insiders 1.6). 

1. I cloned the repo
2. I opened index.ts and expected to see errors highlighted for the modules as you indicated in your screenshot. Instead I see:

![image](https://cloud.githubusercontent.com/assets/2449568/18892565/d3d8ca62-84be-11e6-9e5d-9467107c5f02.png)

I can also cmd+click into the module and am navigated to the correct location.

**Comment by beckend** [comment]
There are several tsconfig.json(s).
The default one is demonstrating a working one. Simply use any other ones included in the repo by renaming them.

**Comment by waderyan** [comment]
This seems to be the intended behavior. If `includes` or `files` is empty than the TypeScript project is empty. `tsconfig.json` is indicating that the files in the workspace are not part of the TypeScript project and so they should not be included in the TS language service's code navigation, linting, intellisense, etc. 

@mhegazy can you correct me if I am misunderstanding? OP has a minimal repo you can pull down and test really simply [here](https://github.com/beckend/typescript-tsconfig-paths-issue)

**Comment by mhegazy** [comment]
You are correct @waderyan. an tsconfig.json with empty `files` or empty `include` loads no files. a quick way to diagnose that is using `tsc --listFiles`. so:

```cmd
c:\test\12563\typescript-tsconfig-paths-issue>tsc --listFiles --p tsconfig-include.json
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts

c:\test\12563\typescript-tsconfig-paths-issue>tsc --listFiles --p tsconfig-files.json
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
```

**Comment by beckend** [comment]
Then we are done here, thanks for the clarifications.
