### ISSUE TITLE
能不能加个设置

### ISSUE THREAD

**Issue by langren1353** [Microsoft/vscode#12568]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.想要有个设置[Hoping to have a setting]
OLD：打开任意新建文件都是纯文本格式，没有代码高亮[Open a new file is just plain text]
NOW：打开任意新建文件都是JAVA编码格式，具有代码高亮，或者其他格式也行[Open a new file with JAVA encoding【Or Other encoding】]
Hope I can change it myself.

**Comment by 0915240** [comment]
in my impression , vscode will associate highlight style with different files(which has suffix) automatic.

if you want to change the highlight style you can select language mode(beside the emoji face) manually.

**Comment by Emeryao** [comment]
关了吧兄弟 新建的文件save一下就有格式了 你这个需求有点吹毛求疵了 个人觉得完全没必要

**Comment by langren1353** [comment]
我只是觉得在notepad2上都能搞定的东西，vscode上还没有，我只是刚来的，以为vscode很强大而已 @Emeryao 新建文件并不一定就想要保存的，有时候只是作为temp文件存在的，用完就不用了的

**Comment by Emeryao** [comment]
@langren1353 那可以按 @0915240 的说法做啊 新建个文件 然后点一下格式就行了 也不是很麻烦啊

**Comment by langren1353** [comment]
@Emeryao 我是众多很懒的程序员中的一个~

**Comment by Emeryao** [comment]
@langren1353 呵呵 反正我觉得没必要啦 让他们决定吧 
另外，在Github上提issue最好最好用英文，写一堆中文人家又看不懂。

**Comment by langren1353** [comment]
@Emeryao 所以我用中英混合的，你用中文回我的O_O

**Comment by chrmarti** [comment]
Anything left to do here? Thanks.

**Comment by Emeryao** [comment]
@chrmarti I don't think so dude 🎉
