### ISSUE TITLE
Suggestion: TypeScript sourcemap in generated .json files should default to true

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#12561]
- VSCode Version:  1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1.   Create a simple app.ts file in a new directory
2.   Set a breakpoint in it by pressing F9
3.   Press F5 (working through the prompts to create launch.json

Expected: breakpoint should be effective 

Actual:  Two different configuration files need to be created/edited to enable TypeScript source debugging.

**Comment by isidorn** [comment]
@weinand the initial launch.json content is coming from the node debug adapter, thus assigning to you. Or am I missing something here?

**Comment by weinand** [comment]
@isidorn you've touched the code in the node extension that generates the launch.json, so you own it now ;-)

**Comment by isidorn** [comment]
`'sourceMaps':true` does not have any negative effect if it is a pure javascript session. So now we always generate the inital 'launch.json' with `'sourceMaps':true`

**Comment by weinand** [comment]
@isidorn Why couldn't you only set sourceMaps to true if you detect TypeScript (or other well known extensions)?
Since we are trying to simplify 'launch.json', I would prefer to always use minimal launch configs. So for JavaScript we should not include anything source map related.

**Comment by isidorn** [comment]
@weinand so for javascript we would omit both outDir and sourceMaps attributes, correct?
However not sure what other scenarios this might affect that rely on sourceMaps. For instance coffeeScript - should we also check for those extensions and not only typescript?

**Comment by weinand** [comment]
@isidorn yes, coffeescript is another transpiled language we should support here.
Please note, the extension code tries to guess good values for the launch config by using some heuristics. It will never be perfect, but we can try to improve it as we learn.

**Comment by isidorn** [comment]
Thanks for the list - very useful 😂
