### ISSUE TITLE
[themes] import text-based theme files directly with ease (no extra special tools required)

### ISSUE THREAD

**Issue by Tcll** [microsoft/vscode#125641]
currently theme customization seems to require the use of npm with yeoman for some reason which is not easy to set up.

I currently have no npm installation nor do I have internet on the target machine running the IDE...
Is there a simple way already to import an XML/JSON based file already (similar to IDEA's .icls themes)?
If so, please disregard this request for vscode, but consider updating the documentation to describe this process clearly, only recommending yeoman as an alternative (if at all).

I can easily create an .icls file in mousepad and import it in IDEA without any special tools...
I should be able to do the same for vscode. :)

**Comment by aeschli** [comment]
The easiest way is to customize colors in the settings. Once you are ready, create a theme.
https://code.visualstudio.com/api/extension-guides/color-theme#workbench-colors

We have currently no plans for import a theme from file.

**Comment by Tcll** [comment]
looks like I figured it out

I had a friend follow your directions and create a custom .vsix which he installed

all that's needed are 2 json files in a custom theme directory: `~/.vscode-oss/extensions/mytheme/`
- `theme.json`: I found the command palette decent enough to generate a custom theme file from, though it's not exactly straight forward if it can be expected to work properly or not...
- 'package.json`: this is needed to make the theme actually appear in the "Color Theme" menu:
```
{
    "name": "mytheme",
    "displayName": "My Theme",
    "description": "",
    "version": "0.0.1",
    "publisher": "username",
    "engines": {
        "vscode": "^1.56.0"
    },
    "categories": [
        "Themes"
    ],
    "contributes": {
        "themes": [
            {
                "label": "My Theme",
                "uiTheme": "vs-dark",
                "path": "./theme.json"
            }
        ]
    }
}
```
alternatively if you're building a light theme `"uiTheme": "vs-light",` should be used instead.

simply create those files and restart VSCode to load the extension
then select your theme and enjoy :)


it shouldn't be this difficult and convoluted to manage custom themes
please look at how IDEA handles and edits themes, and please improve VSCode to match. :)

**Comment by Tcll** [comment]
please excuse the typo I made with `package.json`
I'm afraid I'm unable to edit due to the menu not loading.

**Comment by Tcll** [comment]
that's a shame, it looks like this won't be added then... u.u

I guess my request makes things too easy for the user, and the devs don't like that...
No the devs prefer users hassle themselves with npm just for creating custom syntax themes...

I'm sorry you guys prefer your users go through pain
I personally don't like pain, and I know many others don't as well

so to anyone who wants to select a custom theme for syntax colors, 
don't hassle yourself with installing npm just for a utility for building your theme,
just create a few simple text files using my template above
that'll make things much easier for you ;)
