### ISSUE TITLE
Auto-focus Terminal on selection

### ISSUE THREAD

**Issue by fians4k** [microsoft/vscode#125631]
Issue Type: <b>Feature Request</b>

When I have multiple terminals in the tab stack, and I select one, I have to then click again inside the terminal itself to have focus and start typing comands.

It gets very annoying very fast, is there a way to auto-focus on the terminal to start typing commands when I select a terminal from the stack of terminals? It would be quite faste to select the terminal and start typig right away.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

**Comment by meganrogge** [comment]
Yes, double click the tab to focus the terminal

**Comment by Tyriar** [comment]
You can change this to single click to focus with this setting:

```
"terminal.integrated.tabs.focusMode": "singleClick"
```

**Comment by fians4k** [comment]
Awesome, thanks @Tyriar and @meganrogge
