### ISSUE TITLE
Drag & drop with multiple folders, some of which are compact folders, always moves the leaf folders of the compact folders

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#125616]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-insider fe1eafc80c07608de52a2f9c99fee103dea77f5e
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. create a folder structure as below
2. open/close folders, such that `projects` shows `sub1`, `sub2\subA`, `sub3`
3. select `sub1` till `sub3` and drag & drop them into `new-projects

Folder structure:
* new-projects
* projects
  * sub1
    * foo.txt
  * sub2
    * subA
      * bar.txt
  * sub3
    * baz.txt

Expected: the whole subtree of `projects` is moved into `new-projects` (note that this is the behavior when doing Cut/Paste instead of using drag & drop)
Actual: instead of moving `sub2`, its subdirectory `subA` is moved

Demo: 
![demo](https://user-images.githubusercontent.com/15714253/120917145-cadc2900-c6ad-11eb-9b65-8d86461d2d3a.gif)

**Comment by isidorn** [comment]
So you would like the drag and drop of a compact folder to drag the upmost parent..

**Comment by anthonyvdotbe** [comment]
Imho this is a bug, not a feature request, because when I want to move everything in `projects` into `new-projects` using DnD, the intuitive course of action (click first folder, Shift+click last folder, do DnD) has an unintuitive outcome. The presence of a compact folder is an accidental detail that shouldn't influence what's moved (even more so because I didn't explicitly select neither `sub2` nor `subA`).

In fact, there's no way to do what I want with DnD at all because, as the demo below shows, even if I use Ctrl+click to explicitly select `foo`, DnD still attempts to move `bar`. So DnD doesn't honor the folders that were selected by the user & just copies the leaf folder no matter what.
![demo](https://user-images.githubusercontent.com/15714253/121009615-ae66ec00-c794-11eb-992d-677bcb4d87d5.gif)

**Comment by anthonyvdotbe** [comment]
@isidorn please consider classifying this as a bug. Imho the mere fact that DnD is inconsistent with cut/paste is sufficient argumentation to do so
