### ISSUE TITLE
[FR] Support navigation commands for two sides of the diff editor

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#125604]
Currently, when using diff editor, commands like `workbench.action.navigateUp`, `workbench.action.navigateDown`, `workbench.action.navigateLeft` and `workbench.action.navigateRight` etc. won't work, they're treating the two sides as the same view, it'll be a productivity booster if these commands are supported for the diff editor as well.

![image](https://user-images.githubusercontent.com/28700378/120911858-18ac5d80-c6bd-11eb-933c-48e30a3c88ca.png)

**Comment by bpasero** [comment]
@wenfangdu these command exist for a long time, see https://github.com/microsoft/vscode/issues/95068

**Comment by wenfangdu** [comment]
@bpasero Thanks for pointing them out!
