### ISSUE TITLE
Make suggest widget inherit editor.letterSpacing

### ISSUE THREAD

**Issue by alexdreptu** [microsoft/vscode#125622]
I set my `editor.letterSpacing` on negative to make the font more condensed, but the suggest widget doesn't inherit the value and the text looks wider than the editor text, which depending on the font also makes it look uglier. I would like to be able to make the font look the same in both.

**Comment by lapaz17** [comment]
Can I get this one?

**Comment by rzhao271** [comment]
I'm wondering why the suggestions seem cut off at the end?
![Screenshot showing that some suggestion text is clipped at the end](https://user-images.githubusercontent.com/7199958/171474883-12d6f48d-f87c-4fc1-9e0d-97d07ca285a1.PNG)
