### ISSUE TITLE
settings sync crached after macbook awaking

### ISSUE THREAD

**Issue by drakulavich** [microsoft/vscode#125685]
Issue Type: <b>Bug</b>

The report is autogenerated from vscode.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|. --crash-reporter-id 7526507e-7f19-4605-83cd-4a98beee9d61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
gc-excelviewer|Gra|3.0.42
hive-sql|jos|0.0.4
VS-code-vagrantfile|mar|0.0.7
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
vsliveshare|ms-|1.0.4360
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
geo-data-viewer|Ran|2.4.0
hl7tools|Rob|1.13.2
code-settings-sync|Sha|3.4.3
quokka-vscode|Wal|1.0.374
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by sandy081** [comment]
Have you seen any errors to recognize the crash? If so can you please provide those?

**Comment by drakulavich** [comment]
Sorry, the only thing that vscode displayed is the message like:
```
vscode detected many requests to settings sync
```

**Comment by sandy081** [comment]
Ok, but that should not crash vs code. It shall just disable settings sync. Can you please elaborate what happened and if there are any crash reports? May I know where did you see this message?
