### ISSUE TITLE
Icon in webview can't be displayed

### ISSUE THREAD

**Issue by luhc228** [microsoft/vscode#125640]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version:macOS 10.15.6

Steps to Reproduce:

1. Install AppWorks extension pack
2. Open a new VSCode window
3. Press `Cmd + Shift + P`，input `> Appworks: Select Scaffold to Create Application`
4. We can see the below webview

![image](https://user-images.githubusercontent.com/44047106/120953936-a9983d00-c780-11eb-994d-cdfbc653bc5e.png)

When I use VSCode@1.55.2，the icons can be displayed.
![image](https://user-images.githubusercontent.com/44047106/120981860-ac0f8c80-c7aa-11eb-9693-ccd09a4b010b.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please provide a minimal example extension that demonstrates the issue

**Comment by luhc228** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> If so, please provide a minimal example extension that demonstrates the issue

OK. Thank you for your reply. I can't reproduce the problem in the latest VS Code insiders. I am so excited. Does the [Electron](https://github.com/electron/electron/issues/28528) cause of this problem? 

So when will [the stable VS Code](https://code.visualstudio.com/updates/v1_56) will be released to solve this problem?
