### ISSUE TITLE
Improve settings sync trouble shooting

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#125687]
Data is very important to trouble shoot settings sync issues, especially logs (current and previous sessions) and other data. Currently Settings Sync data activity views (local & remote) provide very good information to diagnose issues. Sometimes it requires to ask more information. So would be adding a troubleshoot view that provides

- All settings sync logs
- Last sync resource states

and actions to download them

**Comment by sandy081** [comment]
To verify:

- Make sure settings sync is enabled
- Run command `Settings Sync: Show Synced Data`
- Enable Troubleshoot view from `...` menu
- Make sure you can access settings sync logs and last sync states.
- Also verify it in web.

**Comment by sandy081** [comment]
Please wait until following fix is available to verify this 

https://github.com/microsoft/vscode/issues/127480

**Comment by rzhao271** [comment]
On Windows:

![missing-log](https://user-images.githubusercontent.com/7199958/123993057-f981b280-d980-11eb-874d-a77189843027.PNG)

I'm not sure whether the file is actually gone, or if it's somewhere else?

**Comment by sandy081** [comment]
Are you seeing the same for all files or just for that particular entry?

Can you please open the logs folder on the disk and check?

**Comment by rzhao271** [comment]
The log folders exist, but the log file for that entry doesn't.
The log files for the later entries such as the one labelled Current in the picture above exist. Maybe it's amore recent change?

**Comment by connor4312** [comment]
Yea same, new logs are fine, old ones are not. I was a few versions of Insiders behind on my desktop before this morning.

Works fine otherwise, so I will leave the label.

**Comment by sandy081** [comment]
I know why, it seems I am assuming the log files exist always. It might happen that the sync log file is not created due to some reasons. So I shall better check and add it to the list.
