### ISSUE TITLE
Live Share not working

### ISSUE THREAD

**Issue by chrissyalbert** [microsoft/vscode#125694]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Installed VS Code on MacBook Pro 2019 11.4 OS, new computer for work
2. Installed Live Share Extension Pack
3. Click on Live Share from left menu, when I click on Share or Join it does nothing. When I click on the link that my colleague sends when they initiate a live share, it freezes with "loading file tree" and I can't access the live share they started.

thank you for any help you may have with this

**Comment by chrissyalbert** [comment]
VS Code version  1.56.2
Mac OS version 11.4

**Comment by olegoid** [comment]
@chrissyalbert, I'm transferring this ticket over to Live Share public repo.

**Comment by sandy081** [comment]
Closing this as Live Share team is investigating it. Please reopen if there is a bug in VS Code with necessary information
