### ISSUE TITLE
Syntax highlighting is enabled for text outside curly braces when adding logpoints

### ISSUE THREAD

**Issue by fredriklengstrand** [microsoft/vscode#125619]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: macOS Big Sur (11.2.3)

Steps to Reproduce:

1. Add a logpoint
2. Write some text to log

<img width="280" alt="screenshot" src="https://user-images.githubusercontent.com/10126466/120921884-59f53b00-c6c6-11eb-9886-f6c6d035faf5.png">

Shouldn't it only be enabled inside the curly braces as only expressions within them are interpolated?

**Comment by weinand** [comment]
@fredriklengstrand yes, syntax coloring only makes sense within curly braces

**Comment by isidorn** [comment]
Yes, good point.
Implementation wise it might be hard to only get syntax highlighting inside the curly brackets
But we can easily disable syntax highlighting for Log Messages in total

**Comment by weinand** [comment]
Yes, disabling syntax highlighting for Log Messages seems reasonable
