### ISSUE TITLE
Live preview request

### ISSUE THREAD

**Issue by er1shivam** [Microsoft/vscode#12569]
- VSCode Version:1.5.3
- OS Version: windows 8.1

Can you please write extension for live preview in vscode . It's a feature in adobe brackets and i want  
to use it in vscode. sometimes i have to  switch to brackets for using that feature. 

thanks

**Comment by chrmarti** [comment]
VS Code's approach is to delegate specialized functionality to other tools working alongside the editor. I believe https://www.npmjs.com/package/gulp-livereload or something could be used to achieve something like you request.

**Comment by waderyan** [comment]
Hi @er1shivam - I am doing a short user research study on this issue. If you have time tomorrow or Tuesday can you sign up? https://calendly.com/waderyan/try-vscode
