### ISSUE TITLE
Can't open folder from terminal when there's an instance of VS Code already open

### ISSUE THREAD

**Issue by andr3medeiros** [microsoft/vscode#125764]
Issue Type: <b>Bug</b>

If you have VS Code open and via terminal, you try to open a new folder using "code folder-name-or-file", it opens on the "/" folder.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 4b3ff754-5bb3-49cb-b5da-c32dd1c2ff89|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-lombok|Gab|1.0.1
svg|joc|1.4.6
vscode-docker|ms-|1.13.0
remote-containers|ms-|0.177.2
vsliveshare|ms-|1.0.4360
debugger-for-chrome|msj|4.12.12
java|red|0.79.2
partial-diff|ryu|1.4.3
vscode-scss-formatter|sib|2.2.1
code-spell-checker|str|1.10.2
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-wakatime|Wak|12.0.0
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by bpasero** [comment]
@andr3medeiros make sure you do not have a `VSCODE_CWD` variable set in your shell environment.

**Comment by andr3medeiros** [comment]
> @andr3medeiros make sure you do not have a `VSCODE_CWD` variable set in your shell environment.

This is a continuation of [Can't open folder from terminal](https://github.com/microsoft/vscode/issues/124500)

**Comment by bpasero** [comment]
Ah ok, let's continue in that issue then.
