### ISSUE TITLE
Add command to focus git commit message

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#125784]
I would like to be able to focus on the git commit message text box using a shortcut.
It seems like this used to be possible, #44602 mentions being able to focus using `cmd` + `shift` + `G`. But this doesn't work for me.
I suspect this regressed in #108073 though I didn't verify this.

**Comment by Binly42** [comment]
workaround via `multi`: https://stackoverflow.com/a/70861125/7860292

**Comment by yellowtailfan** [comment]
After opening the source control panel with `Ctrl+Shift+G`, if one of the changed files has focus, you can press `Home `then `Enter` to focus the commit message box.
