### ISSUE TITLE
Task has errors in insider version

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode#125725]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.0-insider
- OS Version: win10 19043.985

I'm an extension developer and I just find the tasks in my contributed extension show errors in the insider version. I tried the [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) and find the same issue.

Steps to Reproduce:

1. Open [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) with insider version
2. Click `Terminal -> Configure Tasks...` , select `custombuildscript: 32` and `custombuildscript: 32 incremental`
3. Run these two tasks, and you'll see they have errors.
![tasks](https://user-images.githubusercontent.com/45906942/121142234-5e5c5800-c86e-11eb-85c2-e5fe15d8b692.png)

Expect Result:
1. Open [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) with stable version, follow the remaining steps above
2. You'll see no errors

Is there something I miss in insider version, which results in this issue? Or is there a way to see the error of this task? (`Tasks` of `Output` shows nothing)

**Comment by alexr00** [comment]
@CsCherrYY have you pulled the latest commits for the task-provider-sample? I wasn't able to repro, but I think I know what's happening. There was a bug in that sample. Details: https://github.com/microsoft/vscode/issues/119311#issuecomment-802904918

Commit that fixed the bug: https://github.com/Microsoft/vscode-extension-samples/commit/0839a5dd8e7c3df07428352b0a701fbd323676e0

I suspect you haven't pulled that commit yet. In order for a task to be considered successful, it must fire that close event with `0`.

**Comment by CsCherrYY** [comment]
I just tried fire close event with 0 and it works, thank you @alexr00 !
