### ISSUE TITLE
Intellisense doesn't extract export details from JSX files

### ISSUE THREAD

**Issue by landisdesign** [microsoft/vscode#125752]
Issue Type: <b>Bug</b>

When a React Component is saved in a file ending in `.js`, mouseovers on its references show the property arguments to that component. Its properties are added to Intellisense menus when adding the tag to another component.

<img width="1203" alt="Screen Shot 2021-06-08 at 7 31 45 AM" src="https://user-images.githubusercontent.com/44303132/121206051-ffc2ba00-c82c-11eb-8ade-382e514a18bb.png">

When the file extension is changed to`.jsx`, all references to the arguments of the component disappear, replaced by a simple `export Component` statement.

<img width="812" alt="Screen Shot 2021-06-08 at 7 28 03 AM" src="https://user-images.githubusercontent.com/44303132/121206048-fe918d00-c82c-11eb-9621-c416d76a8a70.png">

### Expected Behavior
Files ending in `.jsx` provide the same Intellisense experience as files ending in `.js` when referenced in other files.

### Actual Behavior
Files ending in `.jsx` provide no information about their signature and provide no options for populating properties in files where they are imported.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|20, 20, 17|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 63330695-c671-494d-acae-76dedaa0109b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-flow-ide|gca|1.2.0
macros|ged|1.2.1
vscode-nginx-conf-hint|han|0.1.0
vscode-language-babel|mgm|0.0.31
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
errorlens|Phi|1.1.3
scala|sca|0.5.3
markdown-preview-enhanced|shd|0.5.18

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by mjbvz** [comment]
Are the imports being resolved? You can test by running `go to definition`

If they are, please share a small example project that demonstrates the issue

**Comment by landisdesign** [comment]
They are, when using the `.js` extension, but not when using `.jsx`.

I'll see if I can put something together quickly.

**Comment by landisdesign** [comment]
Alright, the repo is at https://github.com/landisdesign/no-intellisense-import.

Another piece to the puzzle: In this new repository, it worked fine -- until I added `jsconfig.json` with the following contents:

```json
{
  "compilerOptions": {
    "module": "es6",
    "moduleResolution": "node"
  }
}
```

Adding this file borked the JSX resolution.

**Comment by mjbvz** [comment]
Try also adding `"jsx": "preserve"` in `compilerOptions`. Support for jsx is enabled by default in files that aren't part of a jsconfig project, but an explicit `jsconfig` will override this

**Comment by landisdesign** [comment]
Excellent! Thank you for pointing this out to me.
