### ISSUE TITLE
Selecting text in Debug Console unduely difficult

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/vscode#125797]
Issue Type: <b>Bug</b>

When attempting to select the first line of output in the Debug Console, it's unduely difficult to start the selection at the first character at any line.

1. place mouse over second character of the debug console
2. attempt to select characters 2 thru 5 by pressing mouse down, dragging right, and mouse up. observe this functions correctly.
3. now, place mouse over the first character of the debug console.
4. repeat step 2, but now attempting to select characters 1 thru 4

expected:
successfully selected 4 characters

actual:
unable to select any text at all when starting from first character in a line.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.79GB free)|
|Process Argv|..\\.. --crash-reporter-id 6c9e6d37-6dcc-4ddc-a83b-db31b939969d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vspre833cf:30267465
vshan820:30294714
vscoreces:30290705
vscus158:30286553
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/2163
The whole selection is not the best in debug console and needs rework.
