### ISSUE TITLE
Read-only preview of available shortcuts and keybindings

### ISSUE THREAD

**Issue by NikiforovAll** [Microsoft/vscode#12577]
I mean the keybindings system is already pretty good and convenient. But wouldn't it be great to have another section in _panel_ (e.g _OUTPUT_, _Integrated Termial_) that allows you to preview (in read-only mode) currently available shortcuts in **human-readable** way.  The representation is negotiable. General idea is to provide the way to open preview of shortcuts and corresponding actions without looking to json files.

**Comment by dobegor** [comment]
Gosh, please do it. That's really needed to quickly dive in.

**Comment by alexandrudima** [comment]
For a subset of the keybindings, actions (i.e. commands that have a title), there already exists `F1` that does this.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/26463473/baf609d2-4184-11e7-9738-c885fcf3f300.png)
