### ISSUE TITLE
Go To Definitaion can't work on json

### ISSUE THREAD

**Issue by HonestQiao** [microsoft/vscode#125715]
Issue Type: <b>Bug</b>

```
//file: config.json
{"x":1,"y":2}
```

```
//file: test.js
const cfg = require("./config");
console.log(cfg);
```

**Go To Definitaion can't open config.json on "./config"**

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.33GB free)|
|Process Argv|trunk --crash-reporter-id c3f66079-f5ef-4bb0-b1b6-8d3dd323174d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-nvm|abu|0.0.1
Bookmarks|ale|13.0.4
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.7.1
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
vscode-svn|eli|0.1.0
naive-definitions|Fal|0.0.8
php-debug|fel|1.16.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.4
go|gol|0.25.1
Python-autopep8|him|1.0.2
beautify|Hoo|1.5.0
svn-scm|joh|2.13.6
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.20
sftp|lix|1.12.9
vscode-quickxdev|lon|0.1.0
ninja-syntax|mel|1.0.0
vscode-language-pack-zh-hans|MS-|1.56.2
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
cpptools|ms-|1.4.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.1
vscode-gn|npc|1.1.0
indent-rainbow|ode|7.5.0
vscode-sftp|sun|1.1.1
ninja|sur|0.0.1
vscode-lldb|vad|1.6.4
vscode-icons|vsc|11.4.0
luaide-lite|wel|0.2.3
vscode-rainbow-string|wk-|18.3.7
code-debuger|wow|0.0.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by mjbvz** [comment]
You need to enable `"resolveJsonModule": true` in your tsconfig/jsconfig

**Comment by HonestQiao** [comment]
> You need to enable `"resolveJsonModule": true` in your tsconfig/jsconfig

<img width="1411" alt="iShot2021-06-09 20 27 02" src="https://user-images.githubusercontent.com/696708/121354025-0f431f80-c961-11eb-9c03-4dac24b87451.png">

**Comment by mjbvz** [comment]
https://github.com/microsoft/TypeScript/issues/24357
