### ISSUE TITLE
F12 go definition not work in Objective-C project. 

### ISSUE THREAD

**Issue by simson2010** [Microsoft/vscode#12576]
- VSCode Version:1.5.3
- OS Version: Windows 7

Steps to Reproduce:

1. open folder contains a Objective-C (iPhone) project.
2. open a .m file in editor.
3. click on a OC method, then press F12 or choose Go Definition from menu.

I've installed CPPTool.

**Comment by chrmarti** [comment]
Please file with the extension providing support for Objective-C.
