### ISSUE TITLE
Extend support for CancellationError to FoldingRangeProvider

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#125799]
In [this locked issue](https://github.com/microsoft/vscode/issues/93686), a CancellationError type was added for semantic tokens providers.  The purpose of using this exception when rejecting a cancelled promise is to suppress the error message that was being logged, as cancelling is a valid scenario when a new request is received before the previous one can be completed.

The folding range provider would seem to benefit from the same support.  If a new folding range request is received prior to completing the previous one, a similar scenario occurs in which it's desirable to cancel the previous one and only process the latest one.  VS Code does appear to be cancelling our prior request, so should not log an error when that promise is rejected.

I had assumed the addition of the new type would extend to the folding ranges provider, but it does not appear to:

```
[exthost] [error] Canceled: Canceled
	at FoldingRangeProvider.<anonymous> (......\.vscode\extensions\ms-vscode.cpptools-1.4.0\dist\main.js:35700:23)
	at Generator.next (<anonymous>)
	at fulfilled (........\.vscode\extensions\ms-vscode.cpptools-1.4.0\dist\main.js:35674:58)
	at runMicrotasks (<anonymous>)
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
```
(Reported in: https://github.com/microsoft/vscode-cpptools/issues/7646 )

**Comment by aeschli** [comment]
You folding provider already supports null and `undefined` as result to signal that the server has cancelled the computation.
As a result, no folding ranges are updated (but also not removed).
```
		 * Returns a list of folding ranges or null and undefined if the provider
		 * does not want to participate or was cancelled.
```

Looking in the code, the CancellationError is currently only handled for semantic token provider (but doesn't seem to be documented).

@Colengms are you also ok with the existing mechanisms (null and `undefined`)?

**Comment by Colengms** [comment]
@aeschli I can switch to resolving/returning undefined.  Thanks.  :)

**Comment by aeschli** [comment]
I close the issue then, I hope that's ok.
