### ISSUE TITLE
Word wrap do not change if modify .md to .txt

### ISSUE THREAD

**Issue by crclz** [microsoft/vscode#125795]
Issue Type: <b>Bug</b>

1. create a .md file, and type many words to make it trigger word wrap.
2. change .md to .txt using the file tree on the left side.
3. You will find that the state of the word warp did not change.
4. Close the editor tab, and reopen the .txt file. You will find that the word wrap do not happen.
I do not know whether this is a feature, or indicates bugs in somewhere.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.23GB free)|
|Process Argv|E:\\personal\\学习\\大三下\\互联网营销\\大作业 --crash-reporter-id ccd0220a-609e-4010-adbd-62d2dee4804f|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.0.4
markdown-table-prettify|dar|3.4.0
gitlens|eam|11.4.1
go|gol|0.25.1
latex-workshop|Jam|8.18.0
vscode-scss|mrm|0.10.0
vscode-language-pack-zh-hans|MS-|1.56.2
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
hexeditor|ms-|1.7.0
powershell|ms-|2021.5.1
vscode-commons|red|0.0.6
markdown-preview-enhanced|shd|0.5.18
vscode-scss-formatter|sib|2.2.1
sass-indented|syl|1.8.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by alexdima** [comment]
I can reproduce. @bpasero here is what I tried:
```patch
diff --git a/src/vs/editor/browser/widget/codeEditorWidget.ts b/src/vs/editor/browser/widget/codeEditorWidget.ts
index 977e55d180b..8dd03464de3 100644
--- a/src/vs/editor/browser/widget/codeEditorWidget.ts
+++ b/src/vs/editor/browser/widget/codeEditorWidget.ts
@@ -382,6 +382,7 @@ export class CodeEditorWidget extends Disposable implements editorBrowser.ICodeE
        }

        public updateOptions(newOptions: Readonly<IEditorOptions>): void {
+               console.log(`updateOptions: ${JSON.stringify(newOptions)}, ${new Error().stack}`);
                this._configuration.updateOptions(newOptions);
        }

```

I see the following code path setting `{"quickSuggestions":false,"wordWrap":"on"}`:
```
    at CodeEditorWidget.updateOptions (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:207:74)
    at NativeTextFileEditor.updateEditorConfiguration (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:229:36)
    at vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:93:71
    at Emitter.fire (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/base/common/event.js:490:38)
    at CodeEditorWidget.setModel (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:275:36)
    at NativeTextFileEditor.setInput (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/contrib/files/browser/editors/textFileEditor.js:103:28)
    at async EditorControl.doSetInput (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:156:17)
    at async EditorControl.openEditor (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:65:35)
    at async vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:752:40
    at async EditorGroupView.replaceEditors (vscode-file://vscode-app/c:/Alex/src/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1319:17)
```

**Comment by bpasero** [comment]
Pushed a fix to handle `.txt` files specifically. If you end up renaming a `foo.md` to `something` we preserve the markdown language mode though. The rationale is that we preserve the original language mode before the rename and restore it after the rename if the renamed file does not have any specific language mode.
