### ISSUE TITLE
F10 and F11 grayed out in Run menu and these keys do not work

### ISSUE THREAD

**Issue by youngr137** [microsoft/vscode#125744]
Issue Type: <b>Bug</b>

After installation a few days ago all worked as expected however on shutdown or hibernate the PC attempted a reboot. Visual Studio was running but not running a program. These reboots did not occur if I shutdown Visual studio before shutting down the PC. (This is just background info). The problem I have now is that the F10 and F11 keys don't work the code runs and stops at a breakpoint but I don't get the highlighted line in the code. F5 works and program continues (to next breakpoint). The terminal output does change to a > prompt on stopping at the breakpoints.
Presumably something has changed in config somewhere but I can't see anything obvious that I can change to 'fix' the issue. I guess I can uninstall and reinstall but that would be a rather long winded workaround.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.45GB (1.52GB free)|
|Process Argv|--crash-reporter-id cc2fbe3a-453b-48fb-bcc6-2cf02677e213|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.5.1
vim|vsc|1.20.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2:30307504
vscorehovct:30309550
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by weinand** [comment]
what debugger are you using?

**Comment by youngr137** [comment]
Hi Andre,
Sorry for the slow response. I was debugging powershell code using the
VisualStudio IDE
Roger

**Comment by youngr137** [comment]
Just a bit more digging. If I start and set a breakpoint at pretty much the
first line of code and run the debugger it stops on the breakpoint. At this
point F10, etc are enabled and I can step through the code. If I press F5
to jump to a breakpoint further down the code then the Terminal window
shows a prompt (rather than my debug log  output) but the F10 key no longer
works (and is grayed out in the Run menu)
Hope this helps.
Roger

**Comment by youngr137** [comment]
I have updated to the most recent PowerShell extension and restarted VisualStudio. No better sadly.

**Comment by youngr137** [comment]
Here is a very simple example of where it goes wrong (for me). The script does pretty much nothing but if I set a breakpoint on the line 14 ($contextFilmStripAlbumPictureBoxMenuStrip = New-Object System.Windows.Forms.ContextMenuStrip) or just step through the code using F10 on stepping onto (F10) to line 14 Visual Studio grays out F10, F11, F5 in the Run menu.

param(
    [string]$testDir
)

if (!$testDir) {
    "`n No picture path was given in start parameter `n"
    "Usage:`n$PSCommandPath [-testDir] full_path_to_image_file`n"
    break
}
Add-Type -AssemblyName 'System.Windows.Forms'

$debug = $true
$contextFilmStripAlbumPictureBoxMenuStrip = New-Object System.Windows.Forms.ContextMenuStrip
Write-Host 'Hello world'
