### ISSUE TITLE
Empty window should be trusted by default

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#125747]
Windows 10 with WSL
Version: 1.57.0-insider (user setup)
Commit: fe1eafc80c07608de52a2f9c99fee103dea77f5e
OS: Windows_NT x64 10.0.19043

- open a new WSL window from the remote menu
- try to install a new remote extension, e.g. C++
- open the extension view, it opens in `@workspaceUnsupported`. That's strange, wasn't clear I was in restricted mode
- select the C/C++ extension.

Dialog comes up: `Do you trust the authors of the files in this workspace?`

There are no files in this workspace

**Comment by aeschli** [comment]
I hope we can reconsider the decision to not trust empty workspaces. It's just confusing.
Yes, I know there's a setting, but we need good defaults.

Normally I continue to open a folder or workspace from an empty window, and there I get prompted anyways. 
On for the cases where a single file is opened, show the dialog and reload if the user decides the file can not be trusted. As I just explicitly opened that file, I believe the chance is big that it can be trusted.

**Comment by isidorn** [comment]
I am 100% agreeing with @aeschli here
Renaming issue to better reflect the general problem.
I actually feel so strongly about this that I suggest that we do this change as a **candidate**. It is only a default setting change.

If the empty window is trusted we will prompt once a new file is being added. So there is no need at all for it to not be trusted by default. By having it untrusted by default a lot of our users that just use VS Code to scribble around and create empty files will get the banner at top. We should not spam these users that just want to scribble what a banner that introduces workspace trust concepts.

After discussing with @lszomoru we decided to bring this up in tomorrow's standup.
