### ISSUE TITLE
Separate themes for separate windows

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#12579]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Anniversary Update

## Symptom

Changing the theme in one VSCode window changes the theme for all open windows.

## Steps to Reproduce

1. Open two or more Visual Studio Code windows (keyboard: `CTRL + SHIFT + N`)
2. Change the VSCode theme in one of the windows
3. Notice that all of the windows change colors

## Expected Behavior

Only the current window's theme changes, when changing the theme.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by chrmarti** [comment]
#7358 will allow for changing the theme per workspace/folder.

**Comment by odsail** [comment]
Did this feature not make into a current release?  I'm not seeing the capability.  If is can someone point me to it?  If it's not can it get added to the feature list?

Thank you.
Scott

**Comment by Yugloocamai** [comment]
I'd like to see this too please!

**Comment by esutton** [comment]
+1 

**Use case:**  

1 - When opening different versions of a directory in two different VSCode instances it is easy to lose track of where you are sense VSCode appearances are identical.

2 - Changing the color theme of one instance helps visually remind user where he is at.

**Comment by Mark-L6n** [comment]
https://github.com/Microsoft/vscode/issues/7358#issuecomment-281312985 says it can be configured using `Workspace Settings`.  At least in the Mac version, access this by a drop-down for User Settings \ Workspace Settings in the top right of the settings page.

**Comment by adammcgrade** [comment]
Under User Settings select Workspace Settings from the dropdown in the top right hand corner of the screen. Then you can use the key "workbench.colorTheme" to change the theme for that window.
