### ISSUE TITLE
Option to hide banner for all workspaces

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#125785]
Currently the banner is shown for every workspace in restricted mode. You can dismiss it for the workspace, but not for all workspaces.

**Comment by sbatten** [comment]
To Verify:

Test the new setting: `security.workspace.trust.banner`

Read its 3 values, ensure you can understand them, and make sure each one functions as described.

**Comment by alexr00** [comment]
Going from "never" to "always" in an untrusted workspace doesn't show the banner until reload, but I can see how that might be intentional.
