### ISSUE TITLE
Support Context Menu/Actions for Values in the Debug Hover

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125763]
This is the debug hover:

![image](https://user-images.githubusercontent.com/2931520/121225735-1cd9a600-c88a-11eb-880f-9c9a7eeb8b61.png)

I think it would be great if each value has a context menu (or inline buttons) to trigger (contributable) actions.

Built-in actions could be:
* copy value
* copy expression
* watch

Actions contributed by extensions could be:
* visualize 😉

This is already supported in the sidebar:

![image](https://user-images.githubusercontent.com/2931520/121227682-2401b380-c88c-11eb-9e3a-6d74fb56be5c.png)

**Comment by isidorn** [comment]
@hediet good overall idea and I like it. I think we could implement it fairly easily by adding a new menu type to the hover tree. We can even open it for extensions as you suggested.

However I would be interested in what other apps do you know that have a context menu on the hover? Might this be a sort of an anti pattern? I know that the debug hover is a bit heavy and a context menu might fit well there, but I would be interested in how other products do it. Maybe try out Visual Studio, Chrome Dev Tools and others...

fyi @misolori

**Comment by misolori** [comment]
I do believe that's using the tree widget, which supports inline actions:

<img width="334" alt="CleanShot 2021-06-08 at 10 46 42@2x" src="https://user-images.githubusercontent.com/35271042/121232812-d1ea6f00-c846-11eb-9197-fe3d7f61bfc4.png">


I'd assume either a `ellipsis` (though there is quite a bit already in these views) or`gear`:

<img width="652" alt="CleanShot 2021-06-08 at 10 48 01@2x" src="https://user-images.githubusercontent.com/35271042/121232994-03633a80-c847-11eb-9baa-23570063358d.png">

<img width="659" alt="CleanShot 2021-06-08 at 10 48 46@2x" src="https://user-images.githubusercontent.com/35271042/121233100-21309f80-c847-11eb-833b-b33628477365.png">

**Comment by hediet** [comment]
> @hediet good overall idea and I like it. I think we could implement it fairly easily by adding a new menu type to the hover tree. We can even open it for extensions as you suggested.
> 
> However I would be interested in what other apps do you know that have a context menu on the hover? Might this be a sort of an anti pattern? I know that the debug hover is a bit heavy and a context menu might fit well there, but I would be interested in how other products do it. Maybe try out Visual Studio, Chrome Dev Tools and others...
> 
> fyi @misolori

VS has quite a few nested context menus :D 
![](https://docs.microsoft.com/en-us/visualstudio/debugger/media/dbg-tour-data-tips.png?view=vs-2019)

**Comment by hediet** [comment]
> I'd assume either a `ellipsis` (though there is quite a bit already in these views) or`gear`:
> 
> <img alt="CleanShot 2021-06-08 at 10 48 01@2x" width="652" src="https://user-images.githubusercontent.com/35271042/121232994-03633a80-c847-11eb-9baa-23570063358d.png">
> 

I like that really much! Would be awesome if extensions could introduce top level actions (that would be useful for a "visualize" action :D), but I understand if that is costs too much space.

**Comment by misolori** [comment]
I think that would be possible since it's a toolbar, we do show more inline actions in peek/diff views:

<img width="157" alt="CleanShot 2021-06-08 at 10 57 38@2x" src="https://user-images.githubusercontent.com/35271042/121234240-5a1d4400-c848-11eb-8909-446a953afa00.png">

**Comment by isidorn** [comment]
Cool ideas. Maybe just a right click context menu might work best. 
But an additional gear on the end to make it discoverable will help. Ellipsis look good in the example you provided but in practice we have a lost of overflowing text and it is all shown with ellipsis, so I think it would be very confusing, as some ellipsis would be clickable and some not...

@misolori is right, it can be made possible if we make it a toolbar, however I would be worried about opening inline actions to extensions since horizontal space is already limited. I would first only open secondary actions - the one behind a context menu. Though I am flexible.

**Comment by connor4312** [comment]
@hediet can you verify this one? 🙂
