### ISSUE TITLE
Finalize notebook API (part 2)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125758]
There is more API to be finalized

* the `NotebookEditor` API and its friends
* IPC for controllers and renderers
* various event for when notebook change etc

**Comment by bxantus** [comment]
Could you provide us with some updates regarding this issue?
It's really unconfortable for our users to use Insiders and opt-in for proposed APIs, so we use only the finalized APIs.

But without the `NotebookEditor` API I can't change metadata associated with the cells. Prepopulating the metadata from the NotebookSerializer when opening documents works, but only for existing cells...
I personally can't see why editing JSON compatible metadata can't be added to the final API. As I see it, the proposed API hasn't changed in a while in this regard...

**Comment by gjsjohnmurray** [comment]
The proposed API keyed on `notebookEditor` must also be enabled if an extension wants to contribute to the `interactive/toolbar` and `interactive/cell/title` menus, despite these being [documented](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) amongst finalized menu contribution points.

Also, the comment in vscode.proposed.notebookEditor.d.ts points to a stale closed issue. It would do better pointing here.

**Comment by mjbvz** [comment]
Now tracked by #149861
