### ISSUE TITLE
Terminology when merge conflict

### ISSUE THREAD

**Issue by Jeje2201** [microsoft/vscode#125736]
When you merge stuff and there is a conflict, you can chose 

**"accept current"** or **"accept incomming"**

Wouldn't it be more clear to tell the user "keep current" as if you chose "accept current" it's to keep the current version you have

Thanks o7

**Comment by chrmarti** [comment]
These appear to be the commonly used terms.

**Comment by Jeje2201** [comment]
But is it really ok to say like "accept current" as you didn't make any change to the current ?
Like, the question isn't to "accept" the current but more likely to "keep" it

**Comment by chrmarti** [comment]
I agree with your observation. Also "current" and "incoming" can be misleading depending on whether you merge, cherry-pick or rebase.
