### ISSUE TITLE
Diplaying Blicking Block Cursor

### ISSUE THREAD

**Issue by puneetgaur1977** [microsoft/vscode#125710]
Issue Type: <b>Bug</b>

Hi Team,

I am using VS Code in Macbook and facing issues with block cursor in VS code editor. I have gone through some open bugs on the same issue and validated it from my end like Vim Extension, Insert mode etc. But it's not working and getting nervous me with such type of issues.

Regards,
Puneet Gaur

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin arm64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 5088e724-f073-4d4c-a90e-6042b89d6665|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
salesforce-snippets|aji|1.2.1
salesforce-soql-editor|all|1.6.2
apex-debug|chu|1.0.3
vscode-eslint|dba|2.1.20
vscode-salesforce-toolkit|dro|1.2.3
lana|Fin|1.3.5
sfdx-autoheader|Hug|0.7.1
forcecode|Joh|3.22.11
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.5
salesforcedx-vscode|sal|51.16.0
salesforcedx-vscode-apex|sal|51.16.0
salesforcedx-vscode-apex-debugger|sal|51.16.0
salesforcedx-vscode-apex-replay-debugger|sal|51.16.0
salesforcedx-vscode-core|sal|51.16.0
salesforcedx-vscode-lightning|sal|51.16.0
salesforcedx-vscode-lwc|sal|51.16.0
salesforcedx-vscode-visualforce|sal|51.16.0
quick-salesforce-apex-class|San|0.0.1
lwccoder|San|1.0.6
lightning-component-snippets|Ter|1.0.8
snippets-for-salesforce-devs|vic|2.0.1
sfdx-package-xml-generator|Vig|2.0.6
vim|vsc|1.20.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by alexdima** [comment]
@puneetgaur1977 What do you mean you are facing issues with block cursor? Can you please give precise steps / explanation about what the issues you are facing ?
