### ISSUE TITLE
Exception message in UI

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#125722]
Not sure if this is a German only problem

<img width="440" alt="capture" src="https://user-images.githubusercontent.com/1931590/121137911-7795e200-c837-11eb-85a7-95e80a147089.png">

**Comment by TylerLeonhardt** [comment]
This is probably a generic issue. Command should not get translated. Is there a way to ignore a substring of the localization string so that it doesn't get translated?

**Comment by TylerLeonhardt** [comment]
This is a generic problem. Here's pseudo language:
![image](https://user-images.githubusercontent.com/2644648/121228513-b2047c80-c841-11eb-8461-5e7ce93e3c50.png)

**Comment by mjbvz** [comment]
Any specific verification steps? I tried changing my display language (to German) but the workspace trust page doesn't seem localized yet:

![Screen Shot 2021-06-09 at 10 07 44 AM](https://user-images.githubusercontent.com/12821956/121398817-9d3feb80-c90a-11eb-9491-d0d58344e7f3.png)

**Comment by TylerLeonhardt** [comment]
Verified this by looking at the language packs in the vscode-loc repo. It's currently in English but translations take some time.
