### ISSUE TITLE
Please add the function of adjusting the size of intelligent prompt panel

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode#125707]
add the function of adjusting the size of intelligent prompt panel
I can not Adjust the size of smart prompt panel, it is really not sutiable for reading
![image](https://user-images.githubusercontent.com/33288114/120258495-bcb09600-c2c4-11eb-8ab8-b8750bf2650e.png)

**Comment by yash112-lang** [comment]
Hello @CatNofishing, is this issue is still open. I want to work on this issue. I am new to open source and want to contribute.

**Comment by CatNofishing** [comment]
@yash112-lang Thanks your reply！😁

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"editor-parameter-hints"

**Comment by CatNofishing** [comment]
please reopen this issue， this issue has not been completely resolved, i find
 the duplicate issue ,but it is differnt with my issue  https://github.com/microsoft/vscode/pull/109094

**Comment by CatNofishing** [comment]
> Hello @CatNofishing, is this issue is still open. I want to work on this issue. I am new to open source and want to contribute.

This issue still exited, any plan to fix it?
