### ISSUE TITLE
node 16.3.0 + async + destructor params = fail (jumpy) breakpoint

### ISSUE THREAD

**Issue by icetbr** [microsoft/vscode#125740]
Issue Type: <b>Bug</b>

Add breakpoint where instructed, it won't work. Tested on 1.54, 1.55, 1.56, 1.57.

WORKS WITH
- removing the desctructured param
- node 15.14.0 or less
- no async/await

```js
const x = {
    async a({ b }) {
        console.log(b) // BREAKPOINT HERE FAILS
        return b;
    }
}

void async function main() {
    await x.a({ b: 1 })
}()
```
Use nvm and change runtimes to test
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/a.js",
            "request": "launch",
            "type": "node",
            "runtimeExecutable": "/home/user/.nvm/versions/node/v16.3.0/bin/node"
        }
    ]
}
```

VS Code version: Code - Insiders 1.57.0-insider (bf84ee619e0b67443d0307c04348fa575bc3c363, 2021-06-07T12:39:04.297Z)
OS version: Linux x64 5.4.0-74-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 4024)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.51GB (3.49GB free)|
|Process Argv|--crash-reporter-id e07d7919-ae8c-4fef-8816-038dc0b9b9ed|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXDE|
|XDG_SESSION_DESKTOP|Lubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by connor4312** [comment]
Thanks for the issue, please see https://github.com/microsoft/vscode-js-debug/issues/1017#issuecomment-853170700

/duplicate

**Comment by icetbr** [comment]
Thank you. As a side note, is it clear / can it be made more clear when opening a new bug which are the major vscode projects? I suspected debug is a separate project, but I wasn't sure, and I let the Report Issue take the wheel.

**Comment by connor4312** [comment]
Opening an issue on the main vscode repo never hurts, it'll get to the right place
