### ISSUE TITLE
Disable "Clear Recently Opened" menu item

### ISSUE THREAD

**Issue by mikejpoole** [microsoft/vscode#125727]
It is easy to inadvertedly click on the menu item residing at `File > Open Recent > Clear Recently Opened` and lose a list containing many projects.

The proposed feature would be a setting to disable or remove that option.

**Comment by gjsjohnmurray** [comment]
Alternatively, add an "Are you sure?" modal dialog.

**Comment by mikejpoole** [comment]
Yes, I'd wondered about that too. It was a bit of a shock when all the projects disappeared when I missed the `More...` row above the `Clear Recently Opened` row.
