### ISSUE TITLE
'There is a task running' warning after developping a extension

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#1257]
- open a folder that contains code of an extension
- debug the extension
- close the extension window (debugger connection correctly gets closed)
- in the window switch to a different folder 
Warning appears
'There is a task running. Do you want to terminate it'

It is not clear to me what task that is. At the very least it could show the name of the task.

**Comment by bpasero** [comment]
Imho it would be nice to tackle this for December, I think the solution in https://github.com/Microsoft/vscode/issues/1194 would help!

**Comment by dbaeumer** [comment]
See also #1194.

**Comment by dbaeumer** [comment]
Duplicates #1194
