### ISSUE TITLE
Editor feels slow when zoom level is set in negative.

### ISSUE THREAD

**Issue by shekhars094** [microsoft/vscode#125776]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56
- OS Version: MacOS : 11.3.1

Steps to Reproduce:

1. add the zoom level in negative.
2. try to do scrolling in general in editor. it will feel slow.

**Comment by alexdima** [comment]
@shekhars094 Could you please try to create a CPU profile of the renderer process using the steps [documented here](https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process). Other than that, is it critical for you to use a negative zoom level? Why do you need to do that?

**Comment by shekhars094** [comment]
@alexdima I am using negative zoom level because on my monitor icons looks big.
[CPU-20210614T184918.txt](https://github.com/microsoft/vscode/files/6648561/CPU-20210614T184918.txt)

**Comment by alexdima** [comment]
@shekhars094 Thank you, I have taken a look at the CPU profile and there is nothing that jumps to me going wrong on the renderer process side. Most of the frames seem to render (from JS's points of view) in 5-10ms which looks about right. Could you please try to close all instances of vscode (quit) and then launch it with `code --disable-gpu` ?
