### ISSUE TITLE
Rename Symbol focus change lag results in unexpected behavior

### ISSUE THREAD

**Issue by IanBellomy** [microsoft/vscode#125745]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: 11.4

**Steps to Reproduce**:

1. Select symbol
2. Right click
3. Click 'rename symbol'
4. Start typing

**Encountered behavior**: 
Keystrokes interrupt the switch to 'rename symbol' mode and overwrite the originally selected text.

**Expected behavior**:
Keystrokes should not interrupt the switch to 'rename symbol' mode -- they should take place _within_ the rename-symbol mode. 

**Example**:
The video includes an example of waiting for the pop-up to appear and then an example of the described issue. 

https://user-images.githubusercontent.com/17239616/121190807-677f0200-c839-11eb-9e20-6d97b15aac03.mp4

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"rename"

**Comment by IanBellomy** [comment]
@jrieken 
FWIW, I did do a cursory search on several terms but did not find anything and am not seeing anything similar using the search you proposed...

**Comment by IanBellomy** [comment]
Ah, it was closed (out-of-scope)... 
https://github.com/microsoft/vscode/issues/101749

Pity.
