### ISSUE TITLE
Debugging issues

### ISSUE THREAD

**Issue by munna2025** [microsoft/vscode#125709]
Issue Type: <b>Bug</b>

previous code debug current code not debug

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.55GB free)|
|Process Argv|G:\\practice HTML --crash-reporter-id f0e4b184-9676-4086-9c38-f8fc4db41913|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by weinand** [comment]
/needsMoreInfo

What debugger are you using?
Please provide reproducible steps.

**Comment by matt123491** [comment]
If I debug my code it shows the code instead of the website. So if I made a list, the debug would show  <li> for each one. If this is not a bug how do I fix this?
![Help](https://user-images.githubusercontent.com/40703994/123563353-0330cd80-d769-11eb-814c-be53540ea613.PNG)

**Comment by weinand** [comment]
@matt123491 this issue is closed. Please create new issue with reproducible steps.
