### ISSUE TITLE
Windows: integration tests often fail with `CodeWindow: failed to load workbench window (reason: <unknown>, code: -3)`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125733]
Lately I often see our Windows integration tests fail (e.g. https://dev.azure.com/monacotools/Monaco/_build/results?buildId=122214&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&l=1052):

```
[main 2021-06-08T08:51:23.804Z] CodeWindow: failed to load workbench window (reason: <unknown>, code: -3)
Exec: 
At D:\a\1\s\build\azure-pipelines\win32\exec.ps1:22 char:3
+         throw ("Exec: " + $errorMessage)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exec: :String) [], RuntimeException
    + FullyQualifiedErrorId : Exec:
```

With the new support of Electron 12 to indicate the exit code, I added this and it seems to be `-3` which somewhat looks like the requests are aborted, similar to our handling here:

https://github.com/microsoft/vscode/blob/100a70731dbf4b811744b5153e45ebc11c37b93d/src/vs/platform/protocol/electron-main/protocolMainService.ts#L97-L97

Curious though what the origin of this issue could be. Is there a way to figure out if we are triggering this from our protocol handler?

**Comment by DanTup** [comment]
I've started seeing this too (on GitHub actions for Dart-Code's integration tests). Only on Windows and with Insiders builds.

It seems reliably broken for me though, so if it's not for you and there's anything I can do that might get more useful info to help track it down, lmk!

```
Found insiders matching latest Insiders release. Skipping download.


Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2021-06-08T12:05:54.227Z] update#setState idle

[main 2021-06-08T12:06:01.956Z] CodeWindow: failed to load workbench window: 

Failed
Exit code:   1
Done
```

**Comment by bpasero** [comment]
@DanTup do you recall from which insiders build this began happening to you so we can identify the day of changes?

**Comment by DanTup** [comment]
I can see a few test runs 21 hours ago that all passed. The first one I saw the issue in was 14 hours ago. It's possible it _is_ flakey for me (unfortunately I've had a few other issues in dev SDKs this week that have meant most of the overall statuses are fails so it's not so easy to check all of them) but if there was an Insiders build between 14 and 21 hours ago, that could be the culprit.

Do you keep historical insiders builds and if so, can vscode-test use them? (If so, I might be able to run the last few a few times to confirm)

**Comment by bpasero** [comment]
Doing a bit of research in our build history, I feel the first time this occured is 6d ago with https://github.com/microsoft/vscode/commit/6f0ce2e750894f53376dbc8166189a17308abfe3

**Comment by DanTup** [comment]
Hmm, perhaps it is more flakey than I realised - there are some bots that are also running windows/insiders that are passing. It's possible it's some specific tests that are causing it (the failures I see are all in my debugger tests) but if the failure is before my tests ran, then it's likely just coincidence.

**Comment by deepak1556** [comment]
> Is there a way to figure out if we are triggering this from our protocol handler?

This failure is not from our protocol handler atleast based on the attached logs, as we also log which urls we abort from the handlers.

There are not many log points that would clarify which failure case we are hitting, a trace event capture would help in this case. If you can start the app with `--enable-tracing="navigation,net,loading,rail"` it will generate a `chrometrace.log` file in the current working directory after the app exits. If you upload the file as a pipeline artifact, can investigate further.

**Comment by bpasero** [comment]
Ok, trying it out in https://github.com/microsoft/vscode/commit/41a93b95fb11e6f53450e116738bd4bd6d5ecafb, I hope the `chrometrace.log` file is top level.

**Comment by JacksonKearl** [comment]
This appeared consistently after enabling getting started by default (which means showing an embedded webview by default), I went through the smoke tests to close out the editor prior to some operations, like the colorization test, which hammer onDidChangeTheme (causes the webview to rerender). After that I no longer saw it repro, but it may still be flakey. 

I will go though and remove from more smoke tests, or possibly better we could try to figure out why loading the webview is causing the whole renderer to hang on testing machines.

**Comment by deepak1556** [comment]
In that case it would very well be related to https://github.com/microsoft/vscode/issues/122951 , service workers used for WebView resource loading are currently not working in elevated environment on windows with sandbox enabled. 

@bpasero as a quick test can you run those failing tests with `--no-sandbox`

**Comment by bpasero** [comment]
@JacksonKearl maybe a command line argument could be added to not open any editor on startup and we use that for tests and smoke tests to always ensure the test window is empty when starting up. I think that would be a good strategy anyways.

@deepak1556 can you clarify: do you mean adding `--no-sandbox` on Windows for the integration tests?

**Comment by deepak1556** [comment]
>  do you mean adding --no-sandbox on Windows for the integration tests?

Yup

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/71490cd84c99d916d518ad8ef01ef25648609010

**Comment by bpasero** [comment]
@deepak1556 the `--no-sandbox` thing did not help as indicated by later failures, e.g. in https://github.com/microsoft/vscode/runs/2779465604

I will push the tracing changes to `main` to capture it once.

**Comment by bpasero** [comment]
@deepak1556 tried to run with `--enable-tracing="navigation,net,loading,rail"` on Windows to see where the log file goes and the output suggests the file is created:

```
  vscode API - workspace
    √ rootPath
    √ workspaceFile
    √ workspaceFolders
    √ getWorkspaceFolder
  4 passing (212ms)
[11012:0609/071804.117:INFO:startup_tracing_controller.cc(270)] Completed startup tracing to chrometrace.log
```

But I cannot find it anywhere on disk. If the file is not created in the current working dir, I fear I cannot upload it from the build machine. Is there a way to set the path?

Also, we do support the `--trace` command line argument, how does that differ from using `--enable-tracing`?

**Comment by deepak1556** [comment]
>  Is there a way to set the path?

`--enable-tracing="navigation,net,loading,rail" --trace-startup-file="<absolute-path>/<filename>.log"`

> Also, we do support the --trace command line argument, how does that differ from using --enable-tracing?

Last time I checked, the trace option only captures till the window loads are completed. The underlying tracing mechanism is same for both just the above command lines are flexible for my use case.

**Comment by bpasero** [comment]
I cannot get that to work. Looks like the file path has to exist, even when I create the parent folder:

```
  vscode API - workspace
    √ rootPath
    √ workspaceFile
    √ workspaceFolders
    √ getWorkspaceFolder
  4 passing (276ms)
[9876:0609/184213.033:ERROR:startup_tracing_controller.cc(251)] Startup tracing failed: couldn't open file: C:\GitDevelopment\monaco\scripts\\..\.build\traces\chrometrace.log
[9876:0609/184215.364:INFO:startup_tracing_controller.cc(270)] Completed startup tracing to C:\GitDevelopment\monaco\scripts\\..\.build\traces\chrometrace.log
```

**Comment by IanMatthewHuff** [comment]
For Jupyter extension we have one suite of integration tests that we use to test webviews and we've just started to get this as well. Actually though, this title refers to Windows and our tests are running on Linux. Should I file a new issue? I can help investigate the issue from our side if any logs need to be pulled here.

**Comment by bpasero** [comment]
Does that reproduce when you configure a global or workspace setting `"webview.experimental.useIframes": true` for the test run?

**Comment by bpasero** [comment]
@deepak1556 we have a failing run with attached trace log!

Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=122652&view=logs&j=97f8f42f-c235-5edb-a4bf-6fc679fb1093&t=8d5b9cbe-0084-5439-c65e-6fc11dfe9f8f&l=1080

Traces: 
[chrometrace-11.log.zip](https://github.com/microsoft/vscode/files/6630534/chrometrace-11.log.zip)

**Comment by IanMatthewHuff** [comment]
@bpasero I've actually not seen our test failing in a few runs now. Is that useIframes setting recommended for webview integration tests?

**Comment by bpasero** [comment]
That setting simulates what we will be shipping in the future, we are in the process of removing the `webview` component of Electron and replace that with `iframe`. It may help for this issue too, not sure.
