### ISSUE TITLE
Configure notebook layout action is still visible when the experiement is off

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125702]
When `notebook.experimental.openGettingStarted` is `false`, we should not show the "Select between Notebook Layouts"

![image](https://user-images.githubusercontent.com/876920/121095941-1a058500-c7a6-11eb-98cd-4bc5216959c1.png)

**Comment by rebornix** [comment]
Merged to release branch.

**Comment by meganrogge** [comment]
@rebornix I don't see that setting - adding it to my settings.json results in `Unknown Configuration Value`. What should I do to verify this?
