### ISSUE TITLE
VSCode and Github Codespaces are missing button to copy code fences to the clipboard in markdown preview.

### ISSUE THREAD

**Issue by kev-ms** [microsoft/vscode#125756]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.49.1
- OS Version: MacOS 11.3.1

Steps to Reproduce:

1. Open a markdown file with bash/code snippet in VSCode or Github Codespaces.
2. Open the markdown preview window (F1, Markdown: Open Preview)
3. Click on any command/code in markdown and observe that there is no copy button.

Expected Behavior:
Markdown Preview in both VSCode and Github Codespaces should have copy fence button like Github repo.

Github Repo:
![image](https://user-images.githubusercontent.com/71272427/121212962-6e127700-c843-11eb-92a6-ab2e37b9cf9b.png)

VSCode:
![image](https://user-images.githubusercontent.com/71272427/121218004-f98e0700-c847-11eb-9d07-741e971703c5.png)

Github Codespaces: 
![image](https://user-images.githubusercontent.com/71272427/121217555-9308e900-c847-11eb-8725-95e49e7781b7.png)

**Comment by mjbvz** [comment]
This feature can be added by an extension. If it proves popular enough, we could consider adding it to core vs code

**Comment by kev-ms** [comment]
@mjbvz Could you point us to specific extension that has this feature?
