### ISSUE TITLE
Cannot publish my Extension to Sandbox

### ISSUE THREAD

**Issue by AndreasRatzRBS** [microsoft/vscode#125731]
Issue Type: <b>Bug</b>

Trtied to publish my Extension to the Sandbox environment sind the extensions are deleted after every update of the BC Version. Have changed nothing in the AL Code. 

Get this error: 

"[2021-06-08 10:21:32.26] The request for path /v2.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Sie verfügen nicht über die folgenden Berechtigungen für TableData Published Application: IndirectInsert.

Details über Ihre Berechtigungen finden Sie auf der Seite 'Effektive Berechtigungen'. Wenn Sie ein Problem melden möchten, beziehen Sie sich auf die folgende Serversitzungs-ID: '19106'."

Please help urgent!
Best 
Andreas

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.94GB free)|
|Process Argv|--crash-reporter-id 7e7d3e5d-dc09-4e67-80c2-ffee6052713b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
al|ms-|7.1.453917
createGUID|nwa|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by sandy081** [comment]
I do not think VS Code has this feature. Can you please elaborate how you are doing this?

**Comment by AndreasRatzRBS** [comment]
Ok. Give you more context. We are a Power BI Partner and have developed a solution based on Microsoft Business Central. To connect Power BI with Business Central you create Web Services from the Object Type "Query". This done by VS Code. And it worked for one year now. I have changed nothing and since the last release of Business Central, I get this error. Every update of the Business Central Sandbox environment deletes the Webservice. So I have to create it again and againn

**Comment by sandy081** [comment]
> We are a Power BI Partner and have developed a solution based on Microsoft Business Central. To connect Power BI with Business Central you create Web Services from the Object Type "Query". This done by VS Code.

I do not think we have done this. Can you please check if you have an extension installed that does it?

**Comment by AndreasRatzRBS** [comment]
The VS Code generates the entries in the Business Central Web Services. I do not need an extension

**Comment by AndreasRatzRBS** [comment]
Have updated to the newest BC Version 18.2 and now it is working again!
