### ISSUE TITLE
VSCode on mac, having numerous issues

### ISSUE THREAD

**Issue by justisGipson** [microsoft/vscode#125772]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Big Sur 11.4

Steps to Reproduce:

1. Open Process Explorer to see nothing
<img width="824" alt="Screen Shot 2021-06-08 at 2 16 22 PM" src="https://user-images.githubusercontent.com/42194039/121236826-5d262d80-c864-11eb-9806-d041ed209c47.png">

2. Issue Reporting in app shows nothing
<img width="741" alt="Screen Shot 2021-06-08 at 2 15 56 PM" src="https://user-images.githubusercontent.com/42194039/121236893-73cc8480-c864-11eb-980b-4eaa3e823f1c.png">

result of `code --status`:

```
Version:          Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS Version:       Darwin x64 20.5.0
CPUs:             Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)
Memory (System):  8.00GB (0.09GB free)
Load (avg):       2, 2, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 3474dd48-b45a-442a-86df-1c84bf954c23
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   106	  2502	code main
    0	    57	  2506	   gpu-process
    0	    16	  2508	   utility
    0	    66	  2792	   shared-process
    0	    16	  2794	     ptyHost
    0	   180	  3498	   window (lib.js)
    0	   164	  3499	     extensionHost
    0	    74	  3503	       electron_node tsserver.js
    0	   279	  3504	       electron_node tsserver.js
    0	    25	  3510	         electron_node typingsInstaller.js typesMap.js
    0	    49	  3506	       electron_node server.js
    0	    25	  3507	       electron_node serverMain.js
    0	    90	  3515	       electron_node server.js
    0	    74	  3522	       electron_node eslintServer.js
    0	    16	  3500	     watcherService
    0	    25	  3501	     searchService

Workspace Stats:
|  Window (lib.js)
|    Folder (codeliciousJr): 844 files
|      File types: svg(361) png(245) js(61) json(34) wav(24) css(17) txt(11)
|                  sjr(10) html(8) db(7)
|      Conf files: package.json(1) settings.json(1) webpack.config.js(1)
```

also tried running the below command from an older thread of the same issue
`/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command= | grep Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

result - 

```
 4080     1   0.0  1.5 /Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions
 4173   500   0.0  0.0 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Applications/Visual Studio Code.app/Contents/MacOS/Electron
```

**Comment by justisGipson** [comment]
Updated Code just now, tested what was broken... It's still broken.

`code --version` output, again
<img width="244" alt="Screen Shot 2021-06-10 at 1 52 11 PM" src="https://user-images.githubusercontent.com/42194039/121573269-10249180-c9f3-11eb-9abb-7cbcd596c195.png">

**Comment by Tyriar** [comment]
Can you hit cmd+option+i while these are open? It should open devtools which will probably have an error in its console.

**Comment by justisGipson** [comment]
Process Explorer:
<img width="589" alt="Screen Shot 2021-06-11 at 10 21 38 AM" src="https://user-images.githubusercontent.com/42194039/121701404-dd37d780-ca9e-11eb-92f3-f3051215a09d.png">

Issue Reporter:
<img width="598" alt="Screen Shot 2021-06-11 at 10 21 48 AM" src="https://user-images.githubusercontent.com/42194039/121701473-f04aa780-ca9e-11eb-849c-83ca9881e8af.png">

Appears to be the same invalid script error for both processes

**Comment by Tyriar** [comment]
@deepak1556 any ideas where this `code-file://vscode-app` comes from and whether it's meant to be working here?

**Comment by deepak1556** [comment]
Issue is same as https://github.com/microsoft/vscode/issues/121237, @justisGipson do you have `Monkey Patch` extension installed ?

@Tyriar it is actually `vscode-file://vscode-app`, process explorer and issue reporter are loaded over this custom protocol. In our current insiders, the workbench is also loaded over the same scheme.

**Comment by justisGipson** [comment]
@deepak1556 I do have it installed. 

I did disable the extension before opening this issue - it persists

**Comment by deepak1556** [comment]
I don't know how monkey patch works exactly but based on its description https://github.com/iocave/monkey-patch#what-does-it-do it is touching code in vscode application that should not be changed. Can you uninstall the app and also remove `~/.vscode/extensions`, try with a fresh install.
