### ISSUE TITLE
Pseudoterminal has invalid name in insider version

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode#125729]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.0-insider
- OS Version: win10 19043.985

Steps to Reproduce:

1. Open [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) with insider version
2. Add some code to get the terminal name. In `customTaskProvider.ts`, add the following code in the beginning of `open()` of the `CustomBuildTaskTerminal` (line 91)
```typescript
const terminals = vscode.window.terminals;
const terminalNames: string[] = [];
for (const terminal of terminals) {
	terminalNames.push(terminal.name);
}
```
3. Add a breakpoint after this part and start debugging.
4. Configure and run task `custombuildscript: 32 incremental`, VS Code will stop at the breakpoint, we can see the current terminal names, in the insider version, it's an empty string (see the red square):
![insider](https://user-images.githubusercontent.com/45906942/121149342-299fcf00-c875-11eb-900c-44ccafec82ee.png)
5. Reopen [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) with stable version, follows the steps 2 and 3 above
6. Configure and run task `custombuildscript: 32 incremental`, VS Code will stop at the breakpoint, we can see the current terminal names, in the stable version, it's a valid string (see the red square):
![stable](https://user-images.githubusercontent.com/45906942/121149357-2c022900-c875-11eb-8dab-a26f87a487d6.png)

Scenario: I'm developing an extension which might use `terminal.show()` by filtering the terminal names. If a terminal's name is empty the feature to show the terminal will not work.

**Comment by Tyriar** [comment]
I see the name is available shortly after initialization:

<img width="430" alt="Screen Shot 2021-06-08 at 5 02 52 AM" src="https://user-images.githubusercontent.com/2193314/121181365-c7b07c80-c816-11eb-8a09-466c7fced48f.png">

**Comment by Tyriar** [comment]
Marking candidate since this breaks at least one extension and it's a regression. I investigated it and the fix is also very low risk.

**Comment by CsCherrYY** [comment]
Thank you @Tyriar !
