### ISSUE TITLE
[Testing API] Cannot read property 'removePeek' of null

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#125711]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0-insider (user setup)
Commit: bf84ee619e0b67443d0307c04348fa575bc3c363
Date: 2021-06-07T12:46:22.208Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Use the `test-provider-sample` and open the test explorer
2. Test navigation is working now in the test explorer
3. Run `2 + 2 = 5`
4. Every time changing the focus from the `2 + 2 = 5` to o another node from test explorer, you can see the navigation is not working, ang an error message `Cannot read property 'removePeek' of null` can be observed in the developer tools

https://user-images.githubusercontent.com/6193897/121110626-737bad00-c7c2-11eb-8fdb-b38458233cee.mp4

_//cc @connor4312_

**Comment by connor4312** [comment]
this is fixed already in the upcoming vs code insiders
