### ISSUE TITLE
Theme color is messed up

### ISSUE THREAD

**Issue by robotboy** [Microsoft/vscode#12571]
- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: macOS Sierra Version 10.12 (16A323)

I'm using Monokai on screenshot but the problem exists on every theme.

![screenshot 2016-09-25 16 18 29](https://cloud.githubusercontent.com/assets/5630520/18814399/44933bfe-833c-11e6-9354-9ee7850d5105.jpg)

**Comment by mrmlnc** [comment]
See #12473.

> **Temporary solution**
> /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --force-gpu-rasterization

**Comment by robotboy** [comment]
Thanks @mrmlnc
