### ISSUE TITLE
report an issue in vscode through `help` then vscode crash

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#125891]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.57.0-insider (system setup)
提交: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
日期: 2021-06-09T11:49:36.076Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.14393
Steps to Reproduce:

1. report an issue
2. crash when done
3. issue was created successfully
4. vscode exit automaticly

**Comment by TylerLeonhardt** [comment]
@heartacker unfortunately, I can't repro this. Do you think you can share a gif/video of what you're seeing?

**Comment by heartacker** [comment]
today I try to reproduce this issue, maybe the network env is different with my work env, so I can't reproduce. I will try again when on work
