### ISSUE TITLE
Clicking the cog icon to customise a task fails if there's no .vscode/tasks.json file

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#125862]
Clicking this cog icon to customise the task fails when there's no existing `tasks.json` file. I'd expect it to create the file and populate it with this task automatically.

<img width="1547" alt="Screenshot 2021-06-09 at 17 43 19" src="https://user-images.githubusercontent.com/1078012/121395489-65f12f00-c94a-11eb-944f-b50cacee010b.png">

**Comment by alexr00** [comment]
Only applies to recently used tasks.
