### ISSUE TITLE
CI: Integration tests should provide access to our logs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#125815]
We had integration test failures (like https://github.com/microsoft/vscode/issues/125665) that only occur on the build machines and when running on the browser. When this happens you are in the dark because there is no way to inspect logs or anything similar. This usually means that these integration tests are disabled in browser - which defeats the purpose and eventually means we don't run any test in the browser anymore. 

/cc @rebornix @mjbvz

**Comment by bpasero** [comment]
> there is no way to inspect logs or anything similar

@jrieken what would you expect? and what do the native integration tests provide that the browser ones don't?

**Comment by jrieken** [comment]
Provide access to log files

**Comment by sandy081** [comment]
> maybe you could advise, is there a way to pass a CLI option to tell VSCode where to persist logs? 

There is not. It can be done but since logs location is scoped to VS Code and passing the log location from CLI when vscode is already open can be a no-op.

**Comment by bpasero** [comment]
Yeah that is fine, we do the same with the `crash-reporter-directory` which will also only work if no other instance is running
