### ISSUE TITLE
Settings links to other settings

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125837]
Not rendered links to other settings (missed markdownDescription?):

- `editor.codeLensFontSize`
- `editor.inlayHints.fontSize`

Probably intended to use link to other setting:

- `editor.cursorSurroundingLinesStyle`

![Screenshot (36)](https://user-images.githubusercontent.com/9638156/121358158-0ccdcf00-c93b-11eb-9e15-b5ab911a8ed5.png)

**Comment by roblourens** [comment]
Thanks!
