### ISSUE TITLE
Use cmd+k as default keybinding for terminal clear

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12585]
Splitting out this from #6603 as the keybinding is coming later.

This is blocked on https://github.com/Microsoft/vscode/issues/12187

**Comment by ramya-rao-a** [comment]
Verified in Mac and Windows

**Comment by ericclemmons** [comment]
Just tried <kbd>Cmd+K<kbd> in `Version 1.8.1 (1.8.1)` and still getting:
> Waiting for second key of chord...

**Comment by Tyriar** [comment]
Do you have the terminal focused at the time?

**Comment by prietoguy** [comment]
I am also getting the same issue.

Running VSCode 1.8.1 on OSX 10.11.6

**Comment by ragingwind** [comment]
I am also facing the same issue and I found something. Shortcut for terminal clearing doesn't work  when I have defined own keybindings with `cmd+k $another-key`, For example,

```
// keybindings.json
{ "key": "cmd+k cmd+l",       "command": "workbench.action.focusNextGroup" },
{ "key": "cmd+k cmd+k",        "command": "workbench.action.focusPreviousGroup" },
```

Clearing is working when I commented above defines

**Comment by Tyriar** [comment]
@ragingwind yes, that's because those two "chord" keybindings override the cmd+k keybinding, this is expected. You will need to add the inverse `when` clause of the standard clear keybinding:

```js
{ "key": "cmd+k cmd+l",       "command": "workbench.action.focusNextGroup",
  "when": "!terminalFocus" },
{ "key": "cmd+k cmd+k",        "command": "workbench.action.focusPreviousGroup",
  "when": "!terminalFocus" },
```
