### ISSUE TITLE
Adding an untrusted local folder to a virtual workspace produces conflicting information

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#125857]
Issue Type: <b>Bug</b>

1. Install the MemFS sample extension.
2. With no workspace open, run the MemFS command to initialize the workspace.
3. Run the MemFS command that creates its files.
4. From context menu of MemFS root folder, add an untrusted local folder to the workspace.
5. When the trust dialog appears, opt NOT to trust the folder.

Status bar now reports Restricted Mode, but if you click on this and open the Workspace Trust editor it indicates that the window is trusted "by nature of the workspace that is opened".

![image](https://user-images.githubusercontent.com/6726799/121385119-c11e2400-c940-11eb-9889-5b12a1faec76.png)

VS Code version: Code - Insiders 1.57.0-insider (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T11:49:36.076Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

**Comment by lszomoru** [comment]
This seems to be related to the way we handle virtual file system providers.
We are planning on making improvements to that scenario in the June 2021 milestone.

**Comment by sbatten** [comment]
The issue seems to be resolved for 2 reasons:
1) The UI no longer allows you to add local folders to a virtual workspace.
2) If you manually create this flow by editing the workspace file directly, the messaging is removed correctly.
