### ISSUE TITLE
"terminal.integrated.defaultProfile.windows" not working

### ISSUE THREAD

**Issue by youngwoods** [microsoft/vscode#125831]
I set some new terminal profiles in user settings like this:

```
    "terminal.integrated.allowWorkspaceConfiguration": true,
    "terminal.integrated.profiles.windows": {
      "MINGW64": {
        "path": "e:\\app\\msys32\\usr\\bin\\bash.exe",
        "args": [
          "--login"
        ]
      },    
      "wsl": {
        "path": "C:\\WINDOWS\\System32\\bash.exe"
      },
      "aaaa": {
        "path": "C:\\WINDOWS\\System32\\cmd.exe",
        "args": []
      }
    },
    "terminal.integrated.defaultProfile.windows": "MINGW64"
```

but it open a powershell terminal always from menu "Terminal" - "New Terminal". But I can startup "MINGW64", "wsl", "aaaa" terminal from terminals dropdown list in internal terminal panel. I'm sure to delete setting for terminal.integrated.shell.windows. "terminal.integrated.defaultProfile.windows" seems invalid?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
