### ISSUE TITLE
Error while turning on Settings Sync. No authentication providers are available

### ISSUE THREAD

**Issue by KrishnaWadhwani** [microsoft/vscode#125880]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest One
- OS Version: Ubuntu 20.10

![Screenshot from 2021-06-09 23-05-18](https://user-images.githubusercontent.com/61587047/121434783-72ea3e80-c99b-11eb-9f84-da2c028e0c1c.png)

```Error while turning on Settings Sync. No authentication providers are available.```
I am facing this error from when I disabled all extensions please help me I am not able to use git and sync my settings 
Thanks, And Regards
Krishna Wadhwani

**Comment by KrishnaWadhwani** [comment]
@sandy081 
please help

**Comment by KrishnaWadhwani** [comment]
Will anybody help me??

**Comment by sandy081** [comment]
Can you please check if following built in extensions are enabled?

`vscode.github-authentication`
`vscode.microsoft-authentication`

**Comment by KrishnaWadhwani** [comment]
No, they are not how can I Enable These

**Comment by KrishnaWadhwani** [comment]
??

**Comment by KrishnaWadhwani** [comment]
@sandy081

**Comment by KrishnaWadhwani** [comment]
no

**Comment by KrishnaWadhwani** [comment]
shall I open anydesk you do it

**Comment by KrishnaWadhwani** [comment]
> Don't you see enable buttons when you open the extension?

Help Sandy!!

**Comment by KrishnaWadhwani** [comment]
I AM NOT ABLE TO USE LIVE SHARE ALSO

**Comment by KrishnaWadhwani** [comment]
@sandy081

**Comment by KrishnaWadhwani** [comment]
VS Code Team Is Not Interested In Resolving Error In Their Own Product

**Comment by sandy081** [comment]
Sorry for not responding soon. Can you please open your extensions view and share the screenshot, it seems extensions are not running. Do you see any errors in dev tools?

**Comment by KrishnaWadhwani** [comment]
I have resolved it on my own
