### ISSUE TITLE
Remember search popup size in the edit field

### ISSUE THREAD

**Issue by Alex-302** [microsoft/vscode#125868]
Issue Type: <b>Feature Request</b>

Hi
Please allow to remember searching popup size after closing app.
The part of popup which can be dragged for resize is narrow, and sometimes it is hard to catch it(I have poor eyesight, but it's difficult to do it with glasses)

Or, search bar may be static above edit field, not as popup.

Thanks

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
This is the find widget @rebornix
