### ISSUE TITLE
Install Marketplace extensions from command line

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#12580]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Anniversary Update

## Feature Request

It would be great if there were a way to automate the installation of Visual Studio Marketplace extensions from the command line. There is already a [method of installing extensions](https://code.visualstudio.com/docs/extensions/install-extension) from local `.vsix` files, however this capability doesn't currently exist for installing directly from the Visual Studio Marketplace.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by chrmarti** [comment]
This is already supported, see: `code --help`
