### ISSUE TITLE
Cells leave behind output_container elements

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#125867]
- Execute a cell to get a webview output
- Clear the output
- See that the output_container is still there and taking up space
- Click to focus a markdown cell under this output, nothing happens when I click it because it's covered up by the leftover output

![image](https://user-images.githubusercontent.com/323878/121404214-961bdc00-c910-11eb-9e02-bf6da31f4f74.png)

**Comment by mjbvz** [comment]
I'm refactoring this area of the code quite a lot for debt week and will try fixing this

**Comment by mjbvz** [comment]
I believe this is fixed by dcc66098d5a379d53bdfdc977ee9b04248d92eab
