### ISSUE TITLE
[Bug] `shift/ctrl+insert` shortcuts are still taking effect even after they are removed

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#125887]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.56.2
- OS Version: Win 10

Steps to Reproduce:

1. Remove `shift/ctrl+insert` keybindings:

```json
[
  {
    "key": "shift+insert",
    "command": "-editor.action.clipboardPasteAction"
  },
  {
    "key": "ctrl+insert",
    "command": "-editor.action.clipboardCopyAction"
  }
]
```

2. They are still taking effect when used in the editor panel.

**Comment by alexdima** [comment]
when removing the keybindings completely, `shift/ctrl+insert` will **fall through our keybinding dispatching logic** and will not be handled by our keybindings system, but they will execute the default action of Electron/Chromium would do. I think that would be to paste/copy.

So I suggest instead:
```
[
  {
    "key": "shift+insert",
    "command": "noop"
  },
  {
    "key": "ctrl+insert",
    "command": "noop"
  }
]
```

which will make it that our keybindings system handles those keybindings and prevents the Electron/Chromium default.
