### ISSUE TITLE
tasks.json should be saved before running a task, not after

### ISSUE THREAD

**Issue by Bu11etmagnet** [microsoft/vscode#125821]
Issue Type: <b>Bug</b>

1. Create a task with the command `echo Hello`
2. Run the task. `Hello` is printed
3. Edit the command  in tasks.json to `echo Hello1` ; do not save tasks.json
4. Run the task. The "not saved" marker disappears from tasks.json. `Hello` is printed instead of `Hello1`. This is the bug.
5. Run the task. `Hello1` is printed, as expected

It appears that tasks.json is saved after it is read for running the task, or there is a race condition between saving and running.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
(same thing happens on Linux)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.64GB free)|
|Process Argv|--crash-reporter-id 4afd6182-af66-42ab-aa7b-71f53011d0b8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0

</details>

**Comment by alexr00** [comment]
This is intended. We save all files after the task is chosen but before the task is run. You can disable the save behavior entirely if you want with the setting `task.saveBeforeRun`.

**Comment by Bu11etmagnet** [comment]
> We save all files after the task is chosen but before the task is run.

This appears not to be the case, because when the task is run, it sees the old content, not the new content.

I doubt very much that using old, unsaved content is the intended behavior.
