### ISSUE TITLE
Update crash from 1.4 -> 1.5

### ISSUE THREAD

**Issue by stignity** [Microsoft/vscode#12586]
- VSCode Version: 1.4 -> 1.5
- OS Version: macOS Sierra

Steps to Reproduce:
1. Be on mac.
2. Launch VSC and start coding.
3. Get info message: "Visual Studio Code will be updated after it restart.".
4. Click update now.
5. Either nothing happens and it just closes, or it crashes.

If you have the "Keep in dock" option enabled for VSC, it will disappear shortly, and then return as a question mark. You then have to remove it and launch it from the folder. Nothing has been updated.

**Comment by joaomoreno** [comment]
Can't reproduce.

Can you look for errors in the macOS Console.app? Does it reproduce after downloading it manually?

**Comment by steveoh** [comment]
happens for me from 1.4 to 1.5 and again to 1.6. I have to delete the app and download. I am an admin on this machine.

**Comment by joaomoreno** [comment]
@steveoh Are there any errors in `Console.app`?

**Comment by steveoh** [comment]
Can you provide some quick instructions on how to check?

**Comment by joaomoreno** [comment]
Open Console.app (`/Applications/Utilities/Console.app`) and check for Code messages in there.

**Comment by steveoh** [comment]
Thanks. I've never had to use this app before. There is nothing when I
search in devices for my machine name. There is one hit in The diagnostics
and usage data but that looks unhelpful. There are a bunch of Code
Helper.diag in the system reports. A couple Code Helper.crash in the user
reports.

This looks helpful from the `system.log`
```
Oct 11 14:55:07 skinnybox ShipIt[32042]: Installation error: Error
Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request"
UserInfo={NSLocalizedDescription=Could not read update request,
NSUnderlyingError=0x7fb3a6600e00 {Error Domain=NSCocoaErrorDomain Code=260
"The file “ShipItState.plist” couldn’t be opened because there is no such
file." UserInfo={NSFilePath=/var/root/Library/Application
Support/com.microsoft.VSCode.ShipIt/ShipItState.plist,
NSUnderlyingError=0x7fb3a6600c50 {Error Domain=NSPOSIXErrorDomain Code=2
"No such file or directory"}}}}
Oct 11 14:55:07 skinnybox com.apple.xpc.launchd[1]
(com.microsoft.VSCode.ShipIt[32042]): Service exited with abnormal code: 1
Oct 11 14:55:07 skinnybox com.apple.xpc.launchd[1]
(com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing
respawn out by 2 seconds.
```

**Comment by joaomoreno** [comment]
Definitely #7426
