### ISSUE TITLE
Notebook Cell Statusbar items are always re-created, ending up with duplicates (including built-in items)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#125810]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Basically when i have a statusbar item (extension that contributes statusbar items), VS Code re-creates all of the statusbar items for all cells.
This causes ALL statubar items in all cells to flicker (as its destroyed and re-created) & we also end up with duplicates.

@rebornix @roblourens /cc

* Flickering UI
* Duplicate statusbar items

See below (from latest VS Code Insiders, can also replicate in latest main branch)
Note how we end up with two language pickers in statusbar.

![statusbarIssues](https://user-images.githubusercontent.com/1948812/121306382-9e91f980-c8b3-11eb-91ff-cc5e629676dc.gif)

After the fix (re-use instead of re-creating & only create what we need):
![fixedStatus](https://user-images.githubusercontent.com/1948812/121306581-e284fe80-c8b3-11eb-9a34-16e0b5180dae.gif)

**Comment by roblourens** [comment]
Thought I had squashed all of these. Thanks for the PR!

**Comment by lramos15** [comment]
The power tools don't seem to provide line numbers anymore so I tried switching the language mode around to repro and couldn't so I'm not sure if that's good enough for verification

**Comment by roblourens** [comment]
I think it's sufficient to mess around with it and not see any dupes. And there were random reports of dupes earlier and I haven't heard that in awhile.
