### ISSUE TITLE
[Getting Started] Walkthrough opens on sync-installed extension

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#125885]
Extensions installed via syncing are opening their walkthroughs on sync-install, which is not expected. cc @sandy081 is there a way I can determine if an extension was installed by an explicit user action versus just sync?

**Comment by sandy081** [comment]
Extension getting installed by sync means that user has installed the extension manually in some other machine and would have seen the walkthrough. Do you maintain any state that walkthrough was shown for an extension? For eg., if I uninstall and install the extension again I shall not be seeing the walkthrough right? If so, shall we sync that state?
