### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: 

### ISSUE THREAD

**Issue by huangxinrui** [microsoft/vscode#125851]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 3.7.2

**Steps to reproduce crash**
1.open a typescript file;
2.copy a piece of code; eg: "// this.test()"
3.ctrl + n,create new file, then paste;

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Verbose Debug Information: {"fileName":"^untitled:Untitled-2","currentDirectory":"d:/work/code/iTrial%20Node.JS","hostCurrentDirectory":"D:/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
Error: Debug Failure. False expression: 
Verbose Debug Information: {"fileName":"^untitled:Untitled-2","currentDirectory":"d:/work/code/iTrial%20Node.JS","hostCurrentDirectory":"D:/Microsoft VS Code","openKeys":[]}
Dynamic files must always have current directory context since containing external project name will always match the script info name.
    at ProjectService.getOrCreateScriptInfoWorker (\node_modules\typescript\lib\tsserver.js:137724:30)
    at ProjectService.getOrCreateScriptInfoOpenedByClientForNormalizedPath (\node_modules\typescript\lib\tsserver.js:137710:29)
    at ProjectService.getOrCreateOpenScriptInfo (\node_modules\typescript\lib\tsserver.js:138113:33)
    at ProjectService.applyChangesInOpenFiles (\node_modules\typescript\lib\tsserver.js:138332:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (\node_modules\typescript\lib\tsserver.js:139212:46)
    at \node_modules\typescript\lib\tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (\node_modules\typescript\lib\tsserver.js:140861:28)
    at IOSession.Session.executeCommand (\node_modules\typescript\lib\tsserver.js:140870:33)
    at IOSession.Session.onMessage (\node_modules\typescript\lib\tsserver.js:140893:35)
    at Interface.<anonymous> (\node_modules\typescript\lib\tsserver.js:142208:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.81GB free)|
|Process Argv|--crash-reporter-id 673e2bb2-61f2-4a39-8a1c-320b7d966e86|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-json|and|1.5.0
vscode-browser-preview|auc|0.7.1
vscode-django|bat|1.6.0
genymotion|Beh|1.0.10
launch-tool|che|0.0.3
mapfile|chi|0.1.1
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
python-preview|don|0.0.4
githistory|don|0.6.16
python-extension-pack|don|1.6.0
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
react-native-react-redux|EQu|2.0.6
vscode-postman|eri|2.0.0
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
vscode-angular-html|gha|1.7.0
lintlens|ghm|3.0.0
vscode-test-explorer|hbe|2.20.2
vscode-power-mode|hoo|2.2.0
vscode-react-typescript|inf|1.3.1
create-migration|Iva|0.0.1
RelativePath|jak|1.4.0
latex-workshop|Jam|8.18.0
Angular2|joh|12.0.0
svn-scm|joh|2.13.6
conda-cheatsheet|joj|1.2.7
vscode-commitizen|Kni|0.14.1
vscode-python-test-adapter|lit|0.6.8
eslint-rules-zh-plugin|mag|0.1.0
MagicPython|mag|1.1.0
python-path|mge|0.0.11
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.13.0
vscode-language-pack-zh-hans|MS-|1.56.2
mssql|ms-|1.10.1
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
sublime-keybindings|ms-|4.0.9
test-adapter-converter|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
jspm|Neo|3.0.4
vetur|oct|0.34.1
view-in-browser|qin|0.0.5
minapp-vscode|qiu|2.2.2
csharp2ts|raf|0.0.26
java|red|0.79.2
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
nestjs|rub|1.5.0
open-in-browser|tec|2.0.0
python|tht|0.2.3
react-redux-es6-snippets|tim|2.1.0
go-to-method|tri|0.2.0
python-extended-snippets|tus|0.0.1
codelf|unb|11.7.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
jinja|who|0.0.8
nativescript-ng2-snippets|www|2.0.1
visual-snake-code|Zho|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by mjbvz** [comment]
Closing as this is a pretty old TS version. Let us know if you see this with TS 4.3+
