### ISSUE TITLE
Letter "S" before buttons in help window

### ISSUE THREAD

**Issue by lexthedev** [microsoft/vscode#125830]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Win 10 Pro 18363.1556

Steps to Reproduce:

1.  dont install .net Core SDK
2.  create csharp file

have a nice day!

![image](https://user-images.githubusercontent.com/44236172/121335867-a8ebdc00-c923-11eb-8bab-1eb1632d5db7.png)

**Comment by sandy081** [comment]
Please file issue against C# extension
