### ISSUE TITLE
Extention Update number tips

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#12589]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  What's the meaning of three?

![2016-09-26_081100](https://cloud.githubusercontent.com/assets/8591065/18819433/86214778-83c3-11e6-9330-829f9ee307d0.png)

after i updated 
![2016-09-26_084152](https://cloud.githubusercontent.com/assets/8591065/18819547/177572e8-83c5-11e6-9b76-2b84a8e57b5d.png)

**Comment by chrmarti** [comment]
@ZCShou What version of VSCode and what OS is this?

**Comment by joaomoreno** [comment]
Please ask the question in the appropriate extension repository.

https://github.com/robertohuertasm/vscode-icons/issues

**Comment by ZCShou** [comment]
@chrmarti 
VSCode Ver : 1.60-insider 2016-9-26  
OS : Win10

**Comment by chrmarti** [comment]
@joaomoreno I think the question is about the (3) decorator on the 'extensions' icon that decreases to (2) after updating the only outdated extension. I don't see how this is related to vscode-icons.

**Comment by joaomoreno** [comment]
Ah!!! Thanks @chrmarti, my bad!

Duplicate of #12507.
