### ISSUE TITLE
Side bar SEARCH symbole disapeared

### ISSUE THREAD

**Issue by joseph-pollacco** [microsoft/vscode#125882]
Issue Type: <b>Bug</b>

Hallo,

Thanks for improving the VSCODE and making it a joy to work with.
Unfortunately the SEARCH symbole on the side bar disapeared.

Many thanks for helping me to get this usefull feature,
Joseph

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (49.07GB free)|
|Process Argv|--crash-reporter-id b3b4f589-237e-41c2-93a9-18d84a199c8c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
readable-indent|cno|1.2.2
bracket-pair-colorizer-2|Coe|0.2.0
markdown-julia|col|0.0.1
vscode-markdownlint|Dav|0.42.0
vscode-great-icons|emm|2.1.77
vscode-edit-csv|jan|0.6.0
rainbow-end|jdu|0.7.7
language-julia|jul|1.2.2
markdown-math|koe|0.1.0
git-graph|mhu|1.30.0
vscode-stable-sort|sgr|1.1.0
markdown-editor|zaa|0.1.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by tharbakim** [comment]
If you right click on the sidebar, do you see the option to re-enable it?

**Comment by joseph-pollacco** [comment]
Thanks for your reply when I right click on the toolbar I see the following options:

- Explorer
- Source control
- Run and debug
- Extensions
- Julia

But to my greatest regret no the SEARCH at I had in the previous versions

**Comment by gjsjohnmurray** [comment]
Have you accidentally moved it from the side bar into the panel, where PROBLEMS and OUTPUT are typically sited? Right-click on one of those and review the list of items.

There is also a command to reset the layout.

**Comment by joseph-pollacco** [comment]
Thanks after resetting the layout the problem got solved, I could see now the search button.

That is really kind of you,
Joseph
