### ISSUE TITLE
Cannot Debug VS Code Anymore

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125841]
I'm on main, ran yarn and the `VS Code - Build` task, and I permanently get this error on Windows 10:

![image](https://user-images.githubusercontent.com/2931520/121366053-7351ed80-c939-11eb-9d56-5ea67af77e2e.png)

Sometimes I also get this error:

![image](https://user-images.githubusercontent.com/2931520/121366298-a7c5a980-c939-11eb-8877-a4607a2b7b51.png)

I don't know how to debug this. Please reach out if you want to debug on my machine.

**Comment by connor4312** [comment]
The crash issue probably duplicates https://github.com/microsoft/vscode/issues/122225

For the first error, can you confirm that you don't have an existing OSS window running when you try to do that? The inspect arguments are only applied for new sessions.

**Comment by hediet** [comment]
> For the first error, can you confirm that you don't have an existing OSS window running when you try to do that? The inspect arguments are only applied for new sessions.

I restarted my computer, still does not work.

**Comment by connor4312** [comment]
That sounds like we are actually connecting now. @lramos15 mentioned this popped up today.

@bpasero I know we had this a while ago when you were tweaking how scripts are loaded, did something change here again?

**Comment by lramos15** [comment]
Yes I'm seeing this as well today. None of my sourcemaps load and my entire OSS window often crashes with the debugger attached. I have no other OSS windows open and tried `git clean -xfd && yarn && yarn compile` with no luck.

**Comment by bpasero** [comment]
@connor4312 since a few days, `vscode-file` is the default scheme for anything served in the workbench (previous it was `file` scheme). But I thought @deepak1556 fixed the sourcemap lookup in https://github.com/microsoft/vscode/issues/120663

**Comment by deepak1556** [comment]
How does the debugger load sourcemaps ? Does it delegate to the client to perform the network request or the does debugger perform the network request ? Custom protocols are only valid within the client, so request outside the client will not understand the protocol.

**Comment by hediet** [comment]
I tried `"enable-browser-code-loading": false` in the debuggee (before insiders notices it cannot attach to it and kills it). Unfortunately, it still does not work.

I'm open for a screensharing session, this is really blocking me.

**Comment by connor4312** [comment]
The debugger makes an HTTP request to the URL. Loading on the client side is only possible [very recently](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-loadNetworkResource) and I expect to see a performance degradation versus making the requests externally, which'll affect vscode where we load thousands of individual files.

**Comment by connor4312** [comment]
I've made a chance to use inline sourcemaps during watch builds. This will also make the debugger launch slightly faster.
