### ISSUE TITLE
Invalid regular expression in search field cause procedure to fail

### ISSUE THREAD

**Issue by andrewrump** [microsoft/vscode#125825]
Issue Type: <b>Bug</b>

1) Press Ctrl+F in Visual Studio Code
2) Enter an invalid regular expression
3) Select Use regular expression 
4) Click outside the Search window
5) Press Ctrl+F - this time an Invalid regular expression error message pops up but the focus does not move to the Search window, i.e., whatever you type (for seaching) goes into whatever has the focus.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.86GB free)|
|Process Argv|--crash-reporter-id 6aac769e-eee4-4204-8415-72a6b2a07f99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
gitlens|eam|11.4.1
mysql-syntax|jak|1.3.1
csharp|ms-|1.23.12
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-wsl|ms-|0.56.4
powershell|ms-|2021.5.1
printcode|nob|3.0.0
vscode-print|pdc|0.9.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by rebornix** [comment]
I'm not able to reproduce this issue anymore. Can you please help double check?
