### ISSUE TITLE
OSX: Cannot fullscreen when opening from tmux cli.

### ISSUE THREAD

**Issue by jimah** [Microsoft/vscode#12587]
- VSCode Version: 1.5.3
- OS Version: OSX 10.11.6
- Tmux Version: 2.2 (Via brew)

Steps to Reproduce:
1. Navigate to project folder
2. `code .`
3. Press fullscreen or the keyboard shortcut
4. App produces a system beep and doesn't resize

I have tried tunning tmux without any configuration, the issue still persists.

I saw this before: https://github.com/Microsoft/vscode/issues/8771 however it has been closed.

Fullscreen works in Atom when I open from the cli in the same manner.

No errors are present in the developer console. The issue also persists when I run with the --disable-extensions flag.

Thank you for your time :)

**Comment by chrmarti** [comment]
F11 is taken by the OS on OSX. You might want to use the default keybinding Ctrl+Cmd+F.

Did you change your keybinding for fullscreen? Does the menu View > Toggle Full Screen work?

**Comment by jimah** [comment]
I have not changed the keybinding for fullscreen, both Ctrl+Cmd+F and the View > Toggle Full Screen methods produce the same result.

**Comment by bpasero** [comment]
@jimah when you click the fullscreen button of the Mac OS X window, does it not go fullscreen? Can you share a screenshot or video how this behaves?

**Comment by jimah** [comment]
I have uploaded a video of the issue occuring here: https://dl.dropboxusercontent.com/u/51560120/VS%20Code/vscode_tmux_issue_720.mov.

Additionally, it appears as though my font is not being loaded when opened through tmux yet the computed property is showing as using my custom font.

<img width="1916" alt="screen shot 2016-09-29 at 22 45 45" src="https://cloud.githubusercontent.com/assets/1707411/18973655/80bb2a8a-8696-11e6-95c8-db9a4ae9e73d.png">

**Comment by bpasero** [comment]
@jimah thanks, good video. I do believe though that this is an issue with Mac OS and not VS Code. I think you have some kind of extension installed, at least I see some buttons popping up when you hover over the fullscreen button? Maybe this extension is causing issues?

**Comment by jimah** [comment]
The extension is called Moom and is found here: https://manytricks.com/moom/ it doesn't cause issues full screening other electron applications such as Atom.

I disabled it and repeated the steps again to double check, the results were unfortunately the same.

**Comment by jimah** [comment]
Interestingly, if vs code is first launched from outside of tmux, then another window is opened from tmux the issues aren't present. It may be something to do with the first launch?

The steps:

* Open a directory using the code command when not running tmux.
* Run tmux in terminal, navigate to another directory.
* Open the directory using the code command.
* Fullscreen works & no font issues.

See video: https://dl.dropboxusercontent.com/u/51560120/VS%20Code/vscode_tmux_issue_2.mov
(I first demonstrate it not working again).

**Comment by nilstgmd** [comment]
I experience the same issue.

Looking into the Console.app brings up this error message:
```
09/11/16 16:10:07,353 Electron[40936]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.iconservices" UserInfo={NSDebugDescription=connection to service named com.apple.iconservices}
```

HTH

**Comment by sean-clayton** [comment]
I'm getting this exact same behavior.

tmux: 2.3
OS: macOS Sierra - 10.12.1 (16B2555)
vscode: ![image](https://cloud.githubusercontent.com/assets/1108160/21056914/819d2a7e-be05-11e6-856e-01180c2c2405.png)

**Comment by mikelduffy** [comment]
Same problem on El Capitan 10.11.6, tmux v.2.3. When opening VS Code outside of tmux first (either through the CLI or opening the app directly), then running code inside of tmux it works just fine. When opening VS Code directly from tmux, it is unable to enter fullscreen.

**Comment by shaypal5** [comment]
I have the exact same problem. El Capitan 10.11.6, byobu v.5.108 (kind of a tmux). When opening VS Code outside of tmux first (either through the CLI or opening the app directly), then running code inside of tmux it works just fine. When opening VS Code directly from tmux, it is unable to enter fullscreen.

**Comment by jefferph** [comment]
Looking at the errors in the console, it seems it may be related to the issues highlighted here:
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

Following the instructions found in the link solved the issue for me, e.g.:
```bash
brew install reattach-to-user-namespace
# add the following to ~/.tmux.conf:
# set-option -g default-command "reattach-to-user-namespace -l bash"
```

**Comment by sean-clayton** [comment]
@jefferph's solution worked for me. After doing those steps, kill your tmux with `tmux kill-server` and then start it back up—should be good to go!

**Comment by nilstgmd** [comment]
Solved it for me as well. Thanks @jefferph

**Comment by bpasero** [comment]
Closing. See https://github.com/Microsoft/vscode/issues/12587#issuecomment-280681178
