### ISSUE TITLE
Add (F5) to tooltip when hovering over start debugging button in the debug view

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#125883]
Hi there!

This is a _tiny_ issue request that showed up in a user study. When you have a launch.json file and you hover over the play button, you can see a tooltip with "Start Debugging" (unfortunately it doesn't show up in screenshots).  The participant looking really hard for the shortcut associated to it, but they couldn't find it in the tooltip. So the suggestion they made was to add it there. So in this case the tooltip would become "Start Debugging (F5)". 

![image](https://user-images.githubusercontent.com/45497113/121445288-055ff300-c946-11eb-8355-c4b61153bd4a.png)

**Comment by isidorn** [comment]
Good catch, thanks for filling. Not sure how we missed that one...

![Screenshot 2021-06-10 at 09 38 06](https://user-images.githubusercontent.com/1926584/121485091-29681680-c9d0-11eb-8554-e7201e8560b3.png)

**Comment by luabud** [comment]
Verified! 🥳🥳
