### ISSUE TITLE
Data Viewer sort and filter features failing

### ISSUE THREAD

**Issue by G-S-Paris** [microsoft/vscode#125860]
unfortunately I can't share the data causing this issue, but when using the Data Viewer tool sometimes sorting columns will lead to out of order data. In addition to this / on the same column I see this anomaly, filtering for values does not work as expected. That said, when I do a df.loc[df['col'] == val] I can find what I'm looking for. I included a screenshot of the filter / sort interface below
![image](https://user-images.githubusercontent.com/14115363/121389266-375b6000-c91a-11eb-849d-d135ec2b171b.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension - AFAIK there is no Data Viewer tool built in to VS Code.
