### ISSUE TITLE
Terminal font appears in split screen and is offset in Mac OS Big Sur

### ISSUE THREAD

**Issue by didionconsult** [microsoft/vscode#125845]
#### Issue: Bug

- Text in any terminal appears wide and off-set
- Text appears split screen
-  The cursor/caret appears over the existing text
Only after clicking and re-sizing the terminal screen to the smallest frame does the font reset to its default type.

This issue occurs with multiple files and after closing and re-opening VSCode.

Does this issue occur when all extensions are disabled?: Yes/No
- Yes

VS Code Version: Version: 1.56.2 (Universal)
OS Version: Mac OS Big Sur 11.2.3

Steps to reproduce:
- Open terminal on VSCode. Have terminal set at approx. 30% or more of the window height.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
