### ISSUE TITLE
Consider using background for inline code in markdown preview

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125833]
Majority of websites seems to be using background color for inline code. I think it would be better if markdown preview added a color for background and some styling: minimal padding + border radius. And used it as default (foreground color the same as text, background - slightly highlighted).

![Screenshot (31)](https://user-images.githubusercontent.com/9638156/121341735-a12f3600-c929-11eb-8e2c-e6b090ec89c3.png)

<p align="center">⏬⏬⏬</p>

![Screenshot (32)](https://user-images.githubusercontent.com/9638156/121341765-a8eeda80-c929-11eb-9c2f-db50e0d20076.png)

---

![Screenshot (33)](https://user-images.githubusercontent.com/9638156/121343385-47c80680-c92b-11eb-828a-d5d4f44f4b3c.png)

<p align="center">⏬⏬⏬</p>

![Screenshot (34)](https://user-images.githubusercontent.com/9638156/121343400-4d255100-c92b-11eb-9494-748dd7b8a75c.png)

If both `background` & `foreground` colors available - it would still be possible to return to the old style.

**Comment by usernamehw** [comment]
Extension style won't be applied to extension preview.

**Comment by mjbvz** [comment]
Extensions can contribute css to the markdown preview: https://code.visualstudio.com/api/extension-guides/markdown-extension#changing-the-look-of-the-markdown-preview-with-css 

Not sure we want to add a new `textPreformat.background` style since we don't currently have anything similar for other inline elements

**Comment by usernamehw** [comment]
> Extensions can contribute css to the markdown preview

Yes, that style is not applied in extension details or changelog:

![Screenshot (38)](https://user-images.githubusercontent.com/9638156/121427334-432c3e00-c97d-11eb-902b-5158eca20f56.png)

---

> Not sure we want to add a new `textPreformat.background` style since we don't currently have anything similar for other inline elements

Other inline elements usually don't use background (on web).

There is an example of using a background: `textCodeBlock.background` is applied to inline code in hover:

![Screenshot (39)](https://user-images.githubusercontent.com/9638156/121427933-f137e800-c97d-11eb-8c58-ec890018769b.png)
