### ISSUE TITLE
Wrong bash colors

### ISSUE THREAD

**Issue by willi84** [microsoft/vscode#125836]
Issue Type: <b>Bug</b>

I am using git bash integration in vscode and when I set up my text highlighting I get wrong colors.

e.g. orange background is shown as gray.

reproduce
1) integrate git bash as terminal 
2) type in the following test
echo -e '\033[48;5;208mTEST\033[00m'

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.57GB free)|
|Process Argv|U:\\portale\\strato-sass|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
scss-lint|ada|0.1.10
ng-template|Ang|11.2.14
perl-html-template|bia|1.1.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.16
prettier-vscode|esb|5.8.0
vscode-pull-request-github|Git|0.22.0
vscode-peacock|joh|3.9.1
markdown-shortcuts|mdi|0.12.0
vscode-scss|mrm|0.9.1
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.65.6
angular-console|nrw|17.4.1
material-icon-theme|PKi|4.7.0
vscode-scss-formatter|sib|2.1.0
iconfont-preview|stx|0.0.4
html-validate-vscode|Tob|0.2.0
vscode-import-cost|wix|2.15.0

</details>

**Comment by Tyriar** [comment]
This might be a result of git bash filtering colors, does it happen in Windows Terminal? Also the color are driven by the theme, did you try changing the active theme?
