### ISSUE TITLE
Proritize .style.ts file inside component folder

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#125844]
Proritize .style.ts file inside component folder and use some special color or label for local styled component if there is some simular named styled components in projects (its very common case when user use same naming for styled components among app components)

/Component/index.tsx
/Component/style.ts

Now if we add emotion css styled component to style.ts file inside component folder and then try to import it in component inside index.tsx VS code show us Styled component from another folders (from /Component2/style.ts for example) on top and not from our component folder. Its very annoing. Now I need manualy import styled component ... Thank you!

Example

![image](https://user-images.githubusercontent.com/28058268/121374713-cbdcb700-c948-11eb-87f7-fea98c23c311.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
