### ISSUE TITLE
Visual Studio crash after create class

### ISSUE THREAD

**Issue by Ahmed0Ghaith** [microsoft/vscode#125888]
I thought this issue was in V 16.10.0 and V 16.10.1 solve it
note  (I have installed 16.11 Preview 1)
![Screenshot 2021-06-10 035115](https://user-images.githubusercontent.com/61051522/121452776-500e5900-c9a0-11eb-9757-c975d177c675.png)

- VS Code Version: 16.10.1
- OS Version: 21H1

**Comment by mjbvz** [comment]
Please file an issue against Visual Studio (this repo is for VS Code)
