### ISSUE TITLE
Auto remove quote pair is broken

### ISSUE THREAD

**Issue by aminpaks** [microsoft/vscode#125834]
Issue Type: <b>Bug</b>

1. Create a new Javascript file
2. Write `console.log(`
3. Press single or double quote key so VScode adds a pair of quotes
4. Write anything like `check` and move the caret to the next line
5. Go back at the end of the word `check` and remove the whole word including the first quote
6. Closing quote remains

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|32.00GB (4.60GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 0022c47a-4f46-441d-a819-669ad7e02cc7|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by alexdima** [comment]
@aminpaks By default, the editor will only delete the quotes it inserted if your cursor stays within. Once you leave that area (like doing arrow down), the quotes are considered "committed" and will no longer get deleted. I think you want to use `"editor.autoClosingDelete": "always"`.

**Comment by aminpaks** [comment]
@alexdima Thanks for clarification. I'm wondering when this feature was added, I clearly remember this was done by default not long ago.

**Comment by alexdima** [comment]
:+1: You have a very good memory. The default [was changed in 1.55](https://code.visualstudio.com/updates/v1_55#_editor)
