### ISSUE TITLE
Linux: Electron instance hangs on Exit

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#125850]
I've updated to the latest Windows 10 Insider build which has native WSL2 GUI support, which works great. But all of a sudden I'm seeing this:

1. Start `./scripts/code.sh`
2. In Code, go `File > Exit`

Here, the app disappears but the CLI doesn't return before approx. 10 seconds. When it does, it spits out this:

```
terminate called after throwing an instance of 'Napi::Error'
  what():  
http://: Invalid host name.

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
[1]    11040 abort      ./scripts/code.sh
```

@deepak1556 Let me know if you need more info.

**Comment by deepak1556** [comment]
Based on the error before the crash seems more like https://github.com/microsoft/vscode/issues/116690, but lets confirm.

Can you get the crash dumps following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by joaomoreno** [comment]
Here it is:

[crash.zip](https://github.com/microsoft/vscode/files/6625921/crash.zip)

**Comment by deepak1556** [comment]
Crash due to exception thrown from keytar module, this is tracked in https://github.com/microsoft/vscode/issues/111288.

You can use `--disable-keytar` for temporary workaround.
