### ISSUE TITLE
Colum selection and SHIFT+HOME

### ISSUE THREAD

**Issue by alexisfrjp** [microsoft/vscode#125804]
Select columns:

![image](https://user-images.githubusercontent.com/6713988/121295375-e0f61d80-c929-11eb-9fb6-bf689c60935b.png)

I want to remove everything before til the start of line: (SHIFT+HOME)
![image](https://user-images.githubusercontent.com/6713988/121295326-c8860300-c929-11eb-8172-021be213e91a.png)
It doesn't select everything, once more: (SHIFT+HOME)
![image](https://user-images.githubusercontent.com/6713988/121295335-cde34d80-c929-11eb-8eb9-4848239b7605.png)

Is that expected?

**Comment by ArturoDent** [comment]
I'm pretty sure that is as designed.  The <kbd>Shift</kbd>+<kbd>Home</kbd> command (`cursorHomeSelect`) selects back to that first character after any leading whitespace.

You can get the behaviour you want with this keybinding:

```jsonc
	{
		"key": "shift+home",
		"command": "cursorLineStartSelect"
	},
```

Now <kbd>Shift</kbd>+<kbd>Home</kbd> will act as you expect.

**Comment by alexisfrjp** [comment]
Perfect, thank you!
