### ISSUE TITLE
XMLHttpRequest for local resource fails with NAME_NOT_RESOLVED on Insiders

### ISSUE THREAD

**Issue by Vtec234** [microsoft/vscode#125802]
Issue Type: <b>Bug</b>

I'm trying a simple extension which proxies a local resource (`cat.jpg`) using `asWebviewUri` to the webview. The resource works fine when loaded through `<img>`. However when I try to make an `XMLHttpRequest` to get it, the request fails with
```
GET https://file+.vscode-resource.vscode-webview.net/c%3A/Users/t-wnawrocki/cat.jpg net::ERR_NAME_NOT_RESOLVED
```

To reproduce, create a webview panel
```typescript
this.webviewPanel = window.createWebviewPanel('myWebviewId', '[DEV] Webview',
                    { viewColumn: ViewColumn.Beside, preserveFocus: true },
                    {
                        enableFindWidget: true,
                        retainContextWhenHidden: true,
                        enableScripts: true,
                        enableCommandUris: true,
                        localResourceRoots: [ Uri.file('C:/Users/t-wnawrocki/') ]
                    });
let catPath = this.webviewPanel.webview.asWebviewUri(Uri.file('C:/Users/t-wnawrocki/cat.jpg'));

this.webviewPanel.webview.html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>[DEV] Webview</title>
</head>
<body>
    <img src="${catPath}"> </img> <!-- This works. -->
    <script type="text/javascript" charset="utf-8">
        const xhr = new XMLHttpRequest();
        xhr.open("GET", "${catPath}", false); // Fails
        xhr.send();
        if (xhr.status === 200) { console.log("GOOD"); } else { console.log("FAIL"); }
    </script>
</body>
</html>
`
```

Btw, the same attempt fails due to a missing CORS header response from the server on Stable.

CC @mjbvz 

VS Code version: Code - Insiders 1.57.0-insider (c7119ae8b6390a5700f6b28f0f1511d676c96562, 2021-06-08T09:17:55.672Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.72GB (37.68GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 980c8360-18e2-4223-9c5f-935d0f2e2260|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscus158:30286553
vscod805:30301674

```

</details>

**Comment by mjbvz** [comment]
Seems that sync XMLHttpRequest requests are not intercepted by service workers in Chrome (service workers are how we load local resources):  https://bugs.chromium.org/p/chromium/issues/detail?id=602051

Closing as upstream since we can't work around this and need an upstream fix
