### ISSUE TITLE
getDocumentSymbols with flat parameter is unstable

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125840]
If a parent symbol and a child symbol have the same start offset, this sort does not guarantee to keep their order:

https://github.com/microsoft/vscode/blob/b5d6d7e62e3c2ae4faec100a81f7ba16e1418b7c/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L463

This is probably the reason for https://github.com/microsoft/monaco-editor/issues/2517.

**Comment by jrieken** [comment]
> this sort does not guarantee to keep their order

Not sure what you mean, `Array.sort` is spec'd to be stable

**Comment by hediet** [comment]
Sorry, my bad. [Array.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility) is indeed stable.
