### ISSUE TITLE
IntelliSense

### ISSUE THREAD

**Issue by kholdarboev** [microsoft/vscode#125894]
Issue Type: <b>Performance Issue</b>

how can i make my IntelliSense make faster? it used to suggest whenever i type something but now i have to wait al least 5-10 seconds. not that great experience. can you tell me whats wrong with my setting ?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (1.30GB free)|
|Process Argv|. --crash-reporter-id 80985f58-70af-4ec7-9605-38e1c18abf06|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
undefined
```

</details>
<details>
<summary>Workspace Info</summary>

```
undefined;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.22
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
keyframes|hyp|1.0.1
vscode-styled-components|jpo|1.6.4
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
vscode-css-peek|pra|4.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
fast-arrow|vin|1.0.8
emmet-live|yse|1.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by kholdarboev** [comment]
as soon as I open the vs code Intellisense working find and after a while coding, autosuggestion is lagging. it is suggesting after 5-10 sec. tried  Extension Bisect but couldn't resolve the issue

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
