### ISSUE TITLE
View Toggle Zen Mode

### ISSUE THREAD

**Issue by scofined** [microsoft/vscode#125827]
Issue Type: <b>Bug</b>

1. Set Keybinding "Alt + Z" for View Toggle Zen Mode;
2. Press "Alt + Z",vs code enter zen mode
3. Press "Alt + Z",vs code can not exit zen mode,except you click editor in vscode

VS Code version: Code - Insiders 1.57.0-insider (c7119ae8b6390a5700f6b28f0f1511d676c96562, 2021-06-08T09:17:55.672Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-67-generic
Remote OS version: Linux x64 5.4.0-67-generic

 --disable-features=RendererCodeIntegrity

**Comment by scofined** [comment]
no duplicate
this is a new problem

**Comment by isidorn** [comment]
Works for me. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
