### ISSUE TITLE
Please enable update throught apt/ppa instead of downloading in browser in linux distros like Ubuntu.

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#125812]
Issue Type: <b>Feature Request</b>

Currently vscode will constantly prompt users to update when there is an update.
But when we clicked the update button, we will be redirect to a downloading page.
And we have to open a browser and open that page and click to download and wait that package to be downloaded and download again if the the downloading is failed.
And then we have to click the packed to install it. 
And if can be failed if the we don't have a proper package installer.

So I would like to suggest that vscode enable automated installation with linux distrobutions.
i.e.  use apt/ppa for deb package distros (Debian/Ubuntu)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.11.0-17-generic

**Comment by tristan957** [comment]
https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

**Comment by calidion** [comment]
@tristan957 

The problem is not that we cannot update with deb packages.
But the prompt can not smoothly update vscode with apt/ppa.

**Comment by tristan957** [comment]
yes it does. There are instructions for adding a repository on that webpage.

```sh
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg

sudo apt update
sudo apt install code
```

**Comment by calidion** [comment]
It has nothing to do with this instruction.
But the deb package didn't add the ppa instruction to apt source list and update with apt.
And prompt again and again to redirect to the downloading page.

**Comment by tristan957** [comment]
I disagree with packages adding repos automatically. If I want the repo, I can follow the instruction to add the repo.

**Comment by Tyriar** [comment]
The deb actually does install a repo, the main issue here is that we show download at all instead of pinging apt
