### ISSUE TITLE
Terminal: Clicking some links (domains) leads to open the File in the "Debug URL" mode

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#125875]
Issue Type: <b>Bug</b>

We have a project which is named `playwright.dev`. This sometimes produces stack traces during development which contain the folder name. For example: 

`/home/max/development/playwright.dev/src/generator.js:483:46`

When I click on the file to open it, it leads when I click on the right part (starting with playwright.dev) to open the URL and wants to debug it with Chrome, because it thinks its an URL.

/home/max/development **/playwright.dev/src/generator.js:483:46**

See here the left and right part, split by bold vs. normal.

When I click on the left part, the file gets opened.

Expected: It does prioritize that its a file and does not open the URL even when I click on the right part.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.12.4-051204-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (1.07GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id b2cdfcc9-53c7-4474-98fc-e8e63e194d2c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|3.2.1
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.8
vscode-markdownlint|Dav|0.42.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.4.1
github-actions|for|0.0.1
codespaces|Git|0.10.5
vscode-pull-request-github|Git|0.26.0
go|gol|0.25.1
vscode-peacock|joh|3.9.1
vscode-clangd|llv|0.1.11
dotenv|mik|1.0.1
language-gettext|mro|0.2.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.0
jupyter|ms-|2021.6.832593372
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
azure-account|ms-|0.9.8
cpptools|ms-|1.4.1
vsliveshare|ms-|1.0.4360
idl|myt|0.3.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
mdx|sil|0.1.0
pdf|tom|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by mxschmitt** [comment]
Verified that its fixed in 1.58.2.

**Comment by mxschmitt** [comment]
Another example when it leads to the "Debug URL" feature when clicking it:

![image](https://user-images.githubusercontent.com/17984549/128413076-5dcad7dc-7933-47bd-9761-4fb2cc3de51a.png)

When pressing it, it takes a few seconds, then a browser opens and the user is confused.

**Comment by Tyriar** [comment]
Links with `Debug URL` would be an extension issue.
