### ISSUE TITLE
Custom fonts don't work well in Safari

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#125968]
* open https://vscode-web-test-playground.azurewebsites.net/?enter=true in Safari
* configure `"editor.fontFamily": "Fira Code"`
* observe that the font is not rendered even if the font is installed

It would be good if the editor would detect this and fall back to a monospace font.

cc @jrieken

**Comment by Cryrivers** [comment]
Since Safari 12, it no longer displays text using user-installed fonts as part of their efforts to curb fingerprinting.

> It would be good if the editor would detect this and fall back to a monospace font.

Other than this, is it possible to fall back any cloud-hosted web fonts on web? I think I can work on this and send a PR.

**Comment by connor4312** [comment]
Verified using a built-in font, since custom fonts don't work due to the aforementioned Safari behavior. Glorious Times New Roman

<img width="272" alt="image" src="https://user-images.githubusercontent.com/2230985/135694373-7874240a-4896-4d37-935b-3d754a18efb5.png">
