### ISSUE TITLE
click on disabled breakpoint , option to enable instead of removing

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#125904]
Issue Type: <b>Feature Request</b>

Now clicking on a disabled breakpoint would remove it. I need an option to enable it first instead of removing.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic
Remote OS version: Linux x64 5.4.0-73-generic

**Comment by isidorn** [comment]
I think this suggestion makes sense in general and would make for a smoother UI.
Click on disabled breakpoint enables it. Click again to remove it (since it would be enabled).

**Comment by isidorn** [comment]
To verify:
1. Add a breakpoint
2. Disable the breakpoint (context menu -> disable)
3. Click on the breakpoint in the glyph margin. Make sure the breakpoint is enabled
4. Click again on the now enabled breakpoint. Make sure it is removed.
