### ISSUE TITLE
formatOnSave appears to not apply when editors are saved by running workbench.action.tasks.build

### ISSUE THREAD

**Issue by tsondergaard** [microsoft/vscode#125901]
Issue Type: <b>Bug</b>

formatOnSave appears to not apply when editors are saved by running workbench.action.tasks.build. formatOnSave does apply when editors are saved by running workbench.action.debug.start.

I am using prettier as my formatter. I have tried enabling debug logging in prettier and there is no debug log output from it at all when running workbench.action.tasks.build.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.12.9-300.fc34.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 2389)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.26GB (8.14GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 73dd0c86-f665-47e6-a0fb-cc9144fdbf1d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
clipboard-manager|Edg|1.4.2
prettier-vscode|esb|6.4.0
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
rpm-spec|Lau|0.3.2
vscode-azureappservice|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.13.0
azure-account|ms-|0.9.8
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
vsliveshare|ms-|1.0.4360
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>
<details>
<summary>Configuration files</summary>
Workspace .vscode/settings.json:

```
// Place your settings in this file to overwrite default and user settings.
{
    "editor.codeActionsOnSave": {
        "source.fixAll": false,
        "source.organizeImports": true,
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/dist": true,
        "**/coverge": true
    },
    "tslint.ignoreDefinitionFiles": false,
    "tslint.autoFixOnSave": false,
    "tslint.exclude": "**/node_modules/**/*",
    "cSpell.words": [
        "csrf",
        "definitelytyped",
        "promisified"
    ],
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "cmake.configureOnOpen": false,
    "files.trimTrailingWhitespace": true,
    "typescript.tsdk": "node_modules/typescript/lib",
    "editor.formatOnSave": true
}
```

~/.config/Code/User/settings.json (slightly redacted and cleaned up)
```
{
  "breadcrumbs.enabled": true,
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  "workbench.tree.indent": 16,
  "yaml.schemas": {
    "file:///home/ts/.vscode/extensions/atlassian.atlascode-2.8.6/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
  },
  "gitlens.defaultDateFormat": "YYYY-MM-DD HH:mm:ss",
  "gitlens.currentLine.enabled": false,
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.hovers.enabled": false,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "launch": {
    "version": "0.2.0",
    "configurations": [
    ]
  },
  "terminal.integrated.scrollback": 10000,
  "gitlens.advanced.abbreviatedShaLength": 12,
  "gitlens.blame.compact": false,
  "gitlens.blame.format": "${id} ${author} ${date}",
  "editor.minimap.enabled": true,
  "editor.renderWhitespace": "none",
  "editor.formatOnSave": true,
  "atlascode.bitbucket.issues.explorerEnabled": false,
  "atlascode.bitbucket.pipelines.explorerEnabled": false,
  "atlascode.jira.statusbar.enabled": false,
  "editor.autoClosingQuotes": "never",
  "extensions.ignoreRecommendations": false,
  "atlascode.jira.enabled": true
}

```

</details>

**Comment by ZYinMD** [comment]
A near duplicate of #102304
