### ISSUE TITLE
Lockup on load due to Workspace Trust

### ISSUE THREAD

**Issue by Jason3S** [microsoft/vscode#125925]
Issue Type: <b>Bug</b>

VS Code Insiders gets stuck showing the Workspace Trust messsage.

See Image:
![image](https://user-images.githubusercontent.com/3740137/121521271-297a0d80-c9f4-11eb-8d17-4de606daa8a3.png)

This seems to be the interaction between two Extensions.
- Extension A needs Extension B
- Extension A does NOT have the trust settings configured
- Extension B does have the trust settings configured to not run in
  an untrusted environment.

Note: In my case, the workspace is trusted or at least should be.

It seem like Extension A is getting loaded and requesting Extension B, but the trust settings do not seem to be loaded yet, causing things to get stuck.

If I disable Extension A, then it is possible to load the Insiders eddition.

Example Extesions:
1. Extension A - [Russian - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-russian)
2. Extension B - [Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
  Note: Version 2+ is needed. That can be found here: [Release Release v2.0.1-alpha.2 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v2.0.1-alpha.2)

Note: The file explorer is stuck and will not load.
It is not possible to open any files or workspaces.

It was possible to disable the Russian extension and restart VS Code. At that point, things started to work.

Re-enabling the Russian extension does not seem to be an issue.

Note: All of this happened after Updating Insiders.

VS Code version: Code - Insiders 1.57.0-insider (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T10:41:06.148Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 8a187fff-41be-45e7-828b-45e2d22eebd7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.22
prettier-vscode|esb|6.4.0
language-haskell|jus|3.4.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
code-spell-checker|str|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
3f5j7703:30294757
vscod805:30301674
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by sbatten** [comment]
@Jason3S I have tested with the extension links you provided but am not able to reproduce this issue. Is this something that you can reproduce reliably?

**Comment by Jason3S** [comment]
@sbatten,

Thank you for trying it out. I was not able to reproduce it either.

It happened when I restarted VS Code Insiders. I think the order of the extensions matters. Because I had gotten a message that said something like "Russian extension is dependent upon another extension that cannot run because the workspace is untrusted".

Might as well close this. If it happens again or to someone else, then it can be re-opened.

Note: accessing files is very slow with the Insiders edition. The explorer can take minutes to update.

**Comment by sbatten** [comment]
Thanks for getting back about this, one additional question: Were you always on the last Insiders from the time you saw the issue? Or were you potentially a few days behind on the initial repro?

**Comment by Jason3S** [comment]
I was a few days behind. From mid-last week to today.

**Comment by Jason3S** [comment]
Even so. I was not able to get the latest version of the Insiders to work until I disabled the Russian extension. After restarting, things worked. Re-enabling the extension didn't seem to be an issue.

**Comment by Jason3S** [comment]
I have not seen it again. I'll open a new issue if it happens again.
