### ISSUE TITLE
Downloading/updating vscode extremely slow

### ISSUE THREAD

**Issue by shoeper** [microsoft/vscode#125954]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: any 1.57.0-1623259809.el8
- OS Version: Fedora

Steps to Reproduce:

1. Install vscode repo
2. cat /etc/yum.repos.d/vscode.repo 
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

3. Downloads and updates are very slow

```
Downloading Packages:
code-1.57.0-1623259809.el8.x86_64.rpm           317 kB/s | 101 MB     05:26    
--------------------------------------------------------------------------------
Total                                           317 kB/s | 101 MB     05:26  
```

Speedtest is fine:
```
   Speedtest by Ookla

     Server: fdcservers.net - Frankfurt (id = 10010)
        ISP: Vodafone Germany Cable
    Latency:     9.91 ms   (2.40 ms jitter)
   Download:   901.17 Mbps (data used: 1.3 GB)                               
     Upload:    47.86 Mbps (data used: 22.3 MB)                               
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/7d3a8eb2-bf64-48c9-9b96-373d11b72261
```

My ISP AS: 3209

I observed something similar with Microsoft Teams download via flatpak. Everything else is mostly fine and way faster.

**Comment by shiftgeist** [comment]
Download is also slow on `Debian`. Downloading with 36.9 kB/s - took `36min 44s`.

![image](https://user-images.githubusercontent.com/30648730/121658959-1e7db680-caa2-11eb-9230-f5483bbdd7b5.png)

![image](https://user-images.githubusercontent.com/30648730/121659074-39e8c180-caa2-11eb-9171-90820f82ae5e.png)

**Comment by shoeper** [comment]
Today its even slower. @shiftgeist although it looks like the whole mirror is overloaded, which is your AS?

```
wget -O/dev/null https://packages.microsoft.com/yumrepos/vscode/code-insiders-1.58.0-1623389224.el8.x86_64.rpm
--2021-06-11 11:32:09--  https://packages.microsoft.com/yumrepos/vscode/code-insiders-1.58.0-1623389224.el8.x86_64.rpm
Resolving packages.microsoft.com (packages.microsoft.com)... 40.114.136.21
Connecting to packages.microsoft.com (packages.microsoft.com)|40.114.136.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105701190 (101M) [application/x-redhat-package-manager]
Saving to: ‘/dev/null’

/dev/null             1%[                    ]   1,88M  34,9KB/s    eta 48m 8s
```
from AS3209


36.6KB/s from AS9145
34KB/s from AS24940
54KB/s from AS12876

**Comment by shiftgeist** [comment]
@shoeper from AS8075

fyi for anyone as confused as I was `AS` stands for `Autonomous System`

**Comment by Tyriar** [comment]
I reported to the repo team, thanks

**Comment by shoeper** [comment]
Still the case. The whole mirror is completely overloaded, even download dnf repo information takes minutes and blocks updating all software.

```
Visual Studio Code           30% [========                   ]  44 kB/s | 4.8 MB     04:12 ETA
```

**Comment by copygirl** [comment]
I'm getting a similar (?) issue when trying to install the C# extension.

> Downloading package 'OmniSharp for Linux (x64)' (35903 KB).

It's not progressing at all. Sometimes it doesn't even print the size to download.
Is this related? Or where should I be asking for advice? (VS Code 1.57.1)
