### ISSUE TITLE
Extension host terminated unexpectedly on macOS < 10.12 (in version 1.57.0)

### ISSUE THREAD

**Issue by zihengCat** [microsoft/vscode#125989]
### Workaround: none today, you can go back to `1.56.2` via [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin-universal.zip) and configure `update.mode` to `none` or `manual`.

---

Extension host terminated unexpectedly in the latest VSCode version `1.57.0`. All extensions break down...
![Screen Shot 2021-06-11 at 11 31 21](https://user-images.githubusercontent.com/19472493/121626916-ec238780-caa8-11eb-8e3c-4e67ae21ed52.png)
![Screen Shot 2021-06-11 at 11 30 58](https://user-images.githubusercontent.com/19472493/121626948-02c9de80-caa9-11eb-958b-5594b87aeff0.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.57.0`
- OS Version: OS X `10.11.6`

Steps to Reproduce:

1. Open the VSCode.
2. Pop up a dialog in the bottom-right.

**Comment by Hemant-Git911** [comment]
Please Help 
Extension host terminated unexpectedly

Give technical Solution

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to find out which extension is causing the problem. Then report it to the extension author.

**Comment by zihengCat** [comment]
@gjsjohnmurray 
I run `Start Extension Bisect` command, all extensions were disabled, but the problem already exist.
![Screen Shot 2021-06-11 at 15 52 26](https://user-images.githubusercontent.com/19472493/121651310-10915b00-cacd-11eb-8fda-ec19ad90168b.png)

**Comment by gjsjohnmurray** [comment]
That information should help one of the VS Code team investigate further. They might want more information from you. But if you urgently need to get VS Code working again I suggest you revert to your previous version. Assuming that was 1.56 you can do this from a link near the top of https://code.visualstudio.com/updates/v1_56

**Comment by alexdima** [comment]
@deepak1556 I think this might have something to do with dynamic libraries. Zooming in on one of the errors:

![image](https://user-images.githubusercontent.com/5047891/121681201-cef7b480-caba-11eb-9d47-cfe7363ee71d.png)

This is similar to https://github.com/microsoft/vscode/issues/104525

cc @digitarald

**Comment by deepak1556** [comment]
Thanks for the ping @alexdima 

We now use `pthread_chdir_np` to support the cwd option in child_process module https://github.com/microsoft/vscode/issues/118267 but this api is not available for mac os < 10.12. Will add a guard in the internal implementation to fix it.

**Comment by zihengCat** [comment]
@deepak1556  
Officially it says VSCode support macOS 10.10+. But VSCode use a `pthread_chdir_np` API which does not available in macOS under `10.12` in the latest `1.57.0` version. We figured out!
Could VSCode team apply some compatible technicals? Or just level up macOS minimal requirement?
![Screen Shot 2021-06-12 at 09 32 22](https://user-images.githubusercontent.com/19472493/121761234-31a38b80-cb61-11eb-9745-d08d22737293.png)

**Comment by alexdima** [comment]
@bpasero Also assigning you to please investigate if an Electron downgrade would also fix this issue.

**Comment by alexdima** [comment]
Also giving candidate and May so we can investigate since more dups are coming in.

**Comment by daiyam** [comment]
FYI, if VSCode is built via Github Actions and on `macos-10.15`, it might not suffer from this issue. At least, VSCodium doesn't have this issue.

**Comment by deepak1556** [comment]
Downgrading to `12.0.7` will not fix this, I will see if a build can be made with the fix for recovery.

**Comment by deepak1556** [comment]
Fix has been made https://domoreexp.visualstudio.com/Teamspace/_git/electron-build/pullrequest/368087 but getting build on time for recovery might be difficult.

**Comment by daiyam** [comment]
@deepak1556 I'm not able to see the fix...

**Comment by Souk21** [comment]
Thank you a lot for staying compatible with older OSes!

**Comment by santi-diazl** [comment]
Bot referred me to this, I am running mac 10.11. I see it is closed though, what is the current solution?

**Comment by daiyam** [comment]
@santi-diazl You will have to wait for the next update or try the Insiders version (https://code.visualstudio.com/insiders/)

**Comment by santi-diazl** [comment]
@daiyam got it. Thank you Baptiste.

**Comment by santi-diazl** [comment]
@daiyam FYI Insiders version has been working fine so far. Thanks for the suggestion.

**Comment by daiyam** [comment]
@santi-diazl Thx but you should also thank @Souk21 since he's the one who suggested the Insiders version 😉
