### ISSUE TITLE
Codicons stopped working in webview in 1.57

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125965]
Issue Type: <b>Bug</b>

1. Clone https://github.com/microsoft/vscode-extension-samples/tree/main/webview-codicons-sample
2. Codicons are not loaded

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by mjbvz** [comment]
I believe the sample is incorrect. It's using the full resource path in the content security policy.  Not sure how this ever worked actually

Will push fix to samples
