### ISSUE TITLE
error command

### ISSUE THREAD

**Issue by Mzyx19** [microsoft/vscode#125947]
Issue Type: <b>Bug</b>

Hello
I'm writing to you because I have a problem.
When I use " .NET : Generate Assets for Build and Debug " it says that it found an error.
I'm new and I want to now why it's doing this.
Thank You !

**Comment by jacany** [comment]
what's the error

**Comment by Mzyx19** [comment]
> what's the error

I don' know, its just telling me 

Command '.NET: Generate Assets for Build and Debug' resulted in an error (command 'dotnet.generateAssets' not found)
