### ISSUE TITLE
VS Code slowed down and loses connection with large number of errors / problems

### ISSUE THREAD

**Issue by CatherineGasnier** [microsoft/vscode#125929]
Does this issue occur when all extensions are disabled?: Yes/No

Disclaimer: this is hard for me to reproduce in Vanilla VS Code. We use some in-house flavour of VS code with Nuclide. Without this, it's hard to have hack running properly, which is what produces all the errors.

- VS Code Version: 1.50.2021051101
- OS Version: macOS Big Sur 11.3.1

Steps to Reproduce:

1. Make a breaking change in your code base that produces 18k+ errors

Actual Result:
VS Code is super slow. I've tried things like go to definition and hovering.
Ultimately I lose the connection with the remote server.

Expected Result: 
I can keep working.

Note that Hack LSP currently submits all the errors at once once it's done checking. Perhaps this would work better if errors were streamed.

**Comment by sandy081** [comment]
Do you have problems view open when this happens?
