### ISSUE TITLE
Getting started: links should use hover color

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125956]
Similar to #121536, #121521

```js
"workbench.colorCustomizations": {
	"textLink.foreground": "#ffae00",
	"textLink.activeForeground": "#00a2ff",
}
```

1. Open Getting Started
2. Hover over any link
3. Link color is not using `textLink.activeForeground`

**Comment by JacksonKearl** [comment]
Thanks! Links (start menu entries, recent entries, back button, inline links in step descriptions) should now follow the theme. Buttons (walkthrough tiles, step tiles, full-width buttons in step descriptions) should not.
