### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.  Latest Update Error.

### ISSUE THREAD

**Issue by gunjeet210** [microsoft/vscode#125972]
#Version: 1.57.0 (user setup)
OS: Windows_NT x64 10.0.19043

**Comment by gunjeet210** [comment]
> Roll back to version 1.56.2 for now if you can.
> 
> Noticed this error too only after updating to 1.57.0 and based on the output, a command for python.intellicode.loadLanguageServerExtension is missing in the update, so while the python language is still supported and vscode can still use the interpreter you select, the intellisense extension for the code is not able to start the pylance language server so you won't get proper code completions until it's fixed.

Rolling back created more problems in the Python extension. So I just synced my settings and reinstalled the 1.57 version. Worked for me.

**Comment by stacynoland** [comment]
> > Roll back to version 1.56.2 for now if you can.
> > Noticed this error too only after updating to 1.57.0 and based on the output, a command for python.intellicode.loadLanguageServerExtension is missing in the update, so while the python language is still supported and vscode can still use the interpreter you select, the intellisense extension for the code is not able to start the pylance language server so you won't get proper code completions until it's fixed.
> 
> Rolling back created more problems in the Python extension. So I just synced my settings and reinstalled the 1.57 version. Worked for me.

I don't think syncing settings and re-updating to version 1.57 fixed your issue. Do you have extensions set to update automatically? They pushed an update for the Python extension specifically which fixed the issue.

I had updated again to 1.57 after your comment thinking they pushed a bug fix, but still got the error, and then noticed Python extension had an update and like magic now there is no error. How about that lol.

**Comment by gunjeet210** [comment]
> > > Roll back to version 1.56.2 for now if you can.
> > > Noticed this error too only after updating to 1.57.0 and based on the output, a command for python.intellicode.loadLanguageServerExtension is missing in the update, so while the python language is still supported and vscode can still use the interpreter you select, the intellisense extension for the code is not able to start the pylance language server so you won't get proper code completions until it's fixed.
> > 
> > 
> > Rolling back created more problems in the Python extension. So I just synced my settings and reinstalled the 1.57 version. Worked for me.
> 
> I don't think syncing settings and re-updating to version 1.57 fixed your issue. Do you have extensions set to update automatically? They pushed an update for the Python extension specifically which fixed the issue.
> 
> I had updated again to 1.57 after your comment thinking they pushed a bug fix, but still got the error, and then noticed Python extension had an update and like magic now there is no error. How about that lol.

Yeah that may be the case. Thankyou.
