### ISSUE TITLE
vscode ctrl shift F not seeding selection if search result list is focused

### ISSUE THREAD

**Issue by pr3tori4n** [microsoft/vscode#125953]
### Issue Type: <b>Bug</b>

1. Open a file with some text in it.
2. Select a word in that file.
3. Use hotkey Ctrl + Shift + F to "find in files" and seed the currently selected word in the search field. (have search.seedOnFocus enabled).
4. Hit Enter to search project.
5. Select an item in the search results.
6. Use mouse to move focus back to the editor.
7. Select a new word from the editor.
8. Use hotkey Ctrl + Shift + F to "find in files" and seed the currently selected word in the search field. (have search.seedOnFocus enabled).

### Expected Result:
Latest highlighted word in the editor is seeded to the search field.

### Actual Result:
The Search Results List is focused.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.67GB free)|
|Process Argv|--crash-reporter-id 6df35bee-5108-4858-a1b8-8e2479131af3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-svgviewer|css|2.0.0
css-variables-autocomplete|dan|0.0.3
vscode-eslint|dba|2.1.22
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vue|jcb|0.1.5
theme-by-language|jsa|1.1.1
vscode-gutter-preview|kis|0.27.1
vscode-simple-icons|Lau|1.14.0
vscode-scss|mrm|0.10.0
language-gettext|mro|0.2.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
cpptools|ms-|1.4.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.34.1
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-scss-formatter|sib|2.2.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.4

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

![vscode-bug-report](https://user-images.githubusercontent.com/12614215/121581484-bc11b100-c9e2-11eb-8cfd-73bddca74e33.gif)

**Comment by pr3tori4n** [comment]
Seems I have to clear the search result in order to get the focus on the search field working again. I've tried adjusting some settings, and have not been able to disable or override the behavior of the hotkey `CTRL + SHIFT + F` to focus on the search results bar once it's been focused.

**Comment by JacksonKearl** [comment]
I am not able to reproduce this, do you have any extensions installed or keybindings defined that might affect this? You can try running a fresh install: `code tmp --user-data-dir=tmp --extensions-dir=tmp` and see if it reproduces there.
![recording (27)](https://user-images.githubusercontent.com/8586769/122309069-77928380-cec2-11eb-994d-30bb0e84e328.gif)
