### ISSUE TITLE
New Font Suggestion (Comic Sans)

### ISSUE THREAD

**Issue by Djbrl** [microsoft/vscode#125975]
Issue Type: <b>Feature Request</b>

Hi VSC team !

I recently had a dream of a world where I could code in Comic Sans MS, and talked about that vision on Twitter where your Twitter account agreed that it could be an interesting addition!
I am now following up on that tweet and officially submitting this Feature Request for Comic Sans to be one of the available fonts for VSC.

Hoping to you'll consider my request !

Cheers,

Jibril (@jibdraws)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 6.3.9600
Fetching remote diagnostics for 'SSH' failed.

**Comment by scherii** [comment]
@Djbrl The [Comic Code](https://www.myfonts.com/fonts/tabular-type-foundry/comic-code) font by [Toshi Omagari](https://tosche.net/fonts/comic-code) might be interesting for you. An Open Source alternative is [Comic Mono](https://dtinth.github.io/comic-mono-font/).

**Comment by Djbrl** [comment]
Awesome thank you!!
