### ISSUE TITLE
Smoother scrolling for terminal

### ISSUE THREAD

**Issue by Vaccano** [microsoft/vscode#125950]
I really like the PowerShell integration for writing PowerShell scripts.  The one frustration I have is with the Terminal.  When it is at a quarter of my screen it can only fit 25 lines on the screen.  

This makes the scrolling with the mouse wheel is super frustrating.  Each "unit" of mouse scroll moves 9 lines!  That means the smallest scroll I can do moves my output by 36%.  That is HUGE!!!

**Please allow for smoother scrolling in the PowerShell terminal window.**  (Similar to the code editor.)

**Comment by Tyriar** [comment]
Smooth scrolling is tracked upstream in https://github.com/xtermjs/xterm.js/issues/1140

Note you can customize scrolling sensitivity with the `terminal.integrated.mouseWheelScrollSensitivity` setting.
