### ISSUE TITLE
Entire settings file got erased on new latest update. Just FYI

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#125970]
When I recently updated VS-Code Insiders Edition,  

Version: 1.57.0-insider (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T11:49:36.076Z

it deleted the entire 600+ lines of code I had in the settings code within the settings file,
it placed only 9 lines of new code on its own, leaving my entire settings 600+ lines of code empty.
I am lucky I made a backup on the settings file on a thumb-drive, otherwise I would have lost all my settings.

Just wanted to point that out to you guys.
It took me a couple of hours to realize what happened & fix, I thought it was an extension as I was hunting for the problem. 
But, When I finally looked at my settings file, everything was gone. Settings was empty except for 9 new lines I did not write.

**Comment by bdougherty** [comment]
This happened to me when I just updated to version 1.57.0 (regular, not insiders).

**Comment by aardvarkk** [comment]
Same just happened to me today on Linux. And my coworker on a Mac M1.

**Comment by roblourens** [comment]
@RobFosterNYC what were the 9 lines? May be a clue. And do you update Insiders regularly or did you just do a big update jump?

Are you all using settings sync?

@aardvarkk Was this when you installed the stable 1.57 update?

**Comment by squaresmile** [comment]
It happened when I updated from stable to stable 1.57. I'm using settings sync.

**Comment by RobFosterNYC** [comment]
@roblourens  No sorry I did not save the 9 lines of code. I'm sorry.  stupid me, :(    I should have  :(
Anyways, yes I update regularly because I'm most of the time using Insiders.
I also was NOT logged on settings sync and have not synced for a bit of time.
The problem happened when I updated from a previous Insiders version on to v1.57 as posted in OP.

**Comment by JacksonKearl** [comment]
`Settings Sync: Open Local Backups Folder` might help here, it should have a backup of your recent configs, though if Sync was never enabled in the first place this might not help.

**Comment by Yurunsoft** [comment]
This update caused the entire setting to be messed up, causing great inconvenience to my work

**Comment by sandy081** [comment]
Very sorry for what happened. I would like to request to let us know what settings are there after getting replaced. It will help us to diagnose what would have caused the issue.

**Comment by atombender** [comment]
Data point: My settings got messed up (see #126038 for details), but I'm not using settings sync.

**Comment by jtegtmeier** [comment]
For what it's worth, after my `settings.json` was replaced I had:
```json
{
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "json.schemas": [
        {
            "name": "vscode-expo-manifest",
            "url": "file:///Users/myuser/Library/Application%20Support/Code/User/globalStorage/bycedric.vscode-expo/manifest-41.0.0.json",
            "fileMatch": [
                "app.json",
                "app.config.json"
            ]
        }
    ]
}
```

Using extensions:
```
bierner.color-info
bungcip.better-toml
byCedric.vscode-expo
CoenraadS.bracket-pair-colorizer-2
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
dunstontc.dark-plus-syntax
eamodio.gitlens
formulahendry.code-runner
foxundermoon.shell-format
gimenete.github-linker
GitHub.vscode-pull-request-github
GraphQL.vscode-graphql
hashicorp.terraform
mads-hartmann.bash-ide-vscode
mikestead.dotenv
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
msjsdiag.vscode-react-native
njpwerner.autodocstring
oouo-diogo-perdigao.docthis
RandomFractalsInc.vscode-data-preview
rogalmic.bash-debug
streetsidesoftware.code-spell-checker
sysoev.language-stylus
VisualStudioExptTeam.vscodeintellicode
yzhang.markdown-all-in-one
zhuangtongfa.material-theme
```

**Comment by meowjesty** [comment]
Don't know if this is related, but I'm on 1.56.2 (Linux, have **not** updated yet) and some of my settings changed, my `editor.tabSize` was previously set to `4`, but then changed to `8`, and my `editor.wordSeparators` also changed.

Settings sync is enabled, but I'm not logged into any account. And the weirdest part is that I have not synced settings since 2021-05-20. I don't quite recall if `editor.tabSize` was actually set to `4` or if it was left as the default, but the `editor.wordSeparators` definitely changed, I had a backup with it set to `~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?_`. 

I also had the `editor.wordSeparators` setup inside a language config block, and this one remained ok, only the general `editor.wordSeparators` one changed.

**Comment by aardvarkk** [comment]
@roblourens This happened to me *before* the 1.57.0 update. I'm on Linux, and when I got the notification that there was a new version available I checked the Issues list and saw https://github.com/microsoft/vscode/issues/126027 so I didn't upgrade. I'm still on 1.56.2 and lost my settings.

**Comment by sandy081** [comment]
Here is why this is happening:

Updating user settings file is done by VS Code window. Underneath, file service uses node API to write into the file. Reads and writes to this file are handled to avoid race conditions in the window. But, it is not safe guarded when the writes and reads happen from multiple windows. As a result, we have this issue that is causing weird behaviors when multiple windows try to write into user settings. It is not new and has been like this from beginning. This got surfaced now because of the change we did last milestone - migrating `workbench.editorAssociations` setting. Hence it appears in the replaced settings file which helped me in understanding and debugging the issue.

**Fix**

I am working on fixing this race condition that can happen across windows - by moving user settings writes into our main process and queuing there.

**Comment by NiklasGollenstede** [comment]
FWIW, I had this too, last Saturday, now I am on <details><summary>VS Code 1.57.0 </summary>Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.0-1029-oem snap</details>

Before I had a whole lot of stuff in the settings, afterwards it was just the `workbench.editorAssociations` (correctly) transformed:
```js
{
	"workbench.editorAssociations": {
		"*.png": "luna.editor",
		"*.ipynb": "jupyter.notebook.ipynb"
	}
}
```
I may have opened a `.png` at the time, most likely not a `.ipynb`, though.
I also still have a full backup of `~/.config/Code` from just before and after, in case anyone needs additional information.

**Comment by sandy081** [comment]
@lramos15 Is there some tactical fix we can do for 1.57 (release) as a candidate to prevent this situation for users? For eg., if you can handle both syntaxes for June, mean while I would be fixing this from my end?

**Comment by lramos15** [comment]
@sandy081 I made the guarantee to the Jupyter team going forward that they would only have to support the new format. As by supporting both on our end we're also requiring every extension who reads this setting to support both formats as well. I believe they're ones most affected by this change. @joyceerhl Would know more about the work required on their end for us not to break them again if we revert.

**Comment by sandy081** [comment]
Thanks for additional info. Breaking extensions is also not good. Any idea how many extensions read this setting and in which milestone new syntax was added.

Or another option - is it possible to do the migration only in active window?

**Comment by lramos15** [comment]
New syntax was added during the May milestone, we just do very aggressive conversion to prevent requiring both to be supported.

This layer is in browser so I could do migration if the window has focus? Would that be a good bandaid fix?

**Comment by sandy081** [comment]
> This layer is in browser so I could do migration if the window has focus? Would that be a good bandaid fix?

Yeah that would help.

**Comment by sandy081** [comment]
Verification steps:

- Please download/downgrade to 1.56 stable version of VS Code and open it
- Open multiple windows (say around 10)
- Have some settings updated in your user settings (say around 5) 
- Have following setting in your user settings file
```json
"workbench.editorAssociations": [{
		"filenamePattern": "*.ipynb",
		"viewType": "jupyter-notebook"
	}],
```
- Shutdown VS Code
- Download and replace with recovery stable VS Code build
- Start VS Code and make sure above setting is migrated to following
```json
"workbench.editorAssociations": {
		"*.ipynb": "jupyter-notebook"
	},
```
- Make sure none of your settings are lost.

**Comment by roblourens** [comment]
I reproed this once in .0, and never in .1, so marking verified. 

I tried the upgrade flow and didn't repro it in either. Then I tried a faster flow which should be pretty much the same process:

- Have .0 or .1 installed
- Close vscode
- Open settings.json in vim, set the old setting
- Launch vscode
- See that it migrates the setting

And with this flow, .0 deleted settings once and .1 never did
