### ISSUE TITLE
Folder tree can't display folder's name with \n correctly

### ISSUE THREAD

**Issue by MondoGao** [microsoft/vscode#125906]
Does this issue occur when all extensions are disabled?: ✅Yes

- Version: 1.56.2
- Commit: 054a9295330880ed74ceaedda236253b4f39a335
- Date: 2021-05-12T17:44:30.902Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Darwin x64 20.3.0

Steps to Reproduce:

1. `node -e "fs.mkdir('{\n folder', console.log)"`
2. Folder name will be truncated to only "{" in vscode folder tree:
![image](https://user-images.githubusercontent.com/3753893/121491970-04dc6080-ca09-11eb-95d5-08f1cfd226e3.png)
rather than in `ls`
![image](https://user-images.githubusercontent.com/3753893/121492042-1a518a80-ca09-11eb-8322-434f3d3c60e0.png)

> `mkdir '{\n'` or `mkdir {\<new-line>` won't produce the same result as node!

**Comment by isidorn** [comment]
This is a fair bug in the explorer. When displaying file names we should escape newlines.
For now assigning to backlog and we might tackle in the future
