### ISSUE TITLE
Escaping of `runInTerminal` with spaces and single quotes makes launch fail

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#125934]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Linux (Ubuntu 18.02) 
- BASH_VERSION:4.4.20 (1)-release 

Note: this was initially reported in the python debugger (https://github.com/microsoft/debugpy/issues/641), but after investigating, it appears to be an issue in VSCode itself (it may be a duplicate of https://github.com/microsoft/vscode/issues/84235, but I'm not exactly sure that this is the case as that report is on Windows and this is on Linux).

Note: steps below on how to reproduce with the Python extension:

1. Create a directory `test's test`.
2. Add a file `hello.py` with the line `print('test')` within that directory
3. Try to debug `hello.py` with a launch configuration such as:

```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
        }
```

Note: putting the absolute path to the file instead of using `${file}` also reproduces the issue.

Apparently the issue is that VSCode escapes `'` to `\'` and then surrounds with `"` due to spaces in the path and that makes the launching fail as it'll try to search for a file in a `test\'s test` instead of `test's test`.

**Comment by roblourens** [comment]
This should now be fixed in latest Insiders
