### ISSUE TITLE
Syntax highlighter color change on latest update

### ISSUE THREAD

**Issue by FMalerba** [microsoft/vscode#125963]
Issue Type: <b>Bug</b>

I just updated to 1.57.0, and the moment after updating and rebooting all my colors for syntax highlighting were off and I don't know why. My theme has not changed and I'm not sure how much it has to do with the theme rather than whatever is parsing my code to set those colors. I've already gone through tens of updates without anything like this ever occurring so I don't know what could be the issue here.

I've highlighted just a couple of the main differences I can immediately see in the pic below.
![Immagine 2021-06-10 221637](https://user-images.githubusercontent.com/44475525/121591887-518c5f80-ca3a-11eb-8d85-c512e5a67baf.png)

Note that the IDE does not seem to have problems parsing the code and figuring out what is what; if I hover over classes and functions I get the popup with their definitions and all other features like this seem to work properly.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (9.86GB free)|
|Process Argv|C:\\Users\\maler\\Google Drive\\Lavoro\\Zuse Institute\\Code\\ZIB.code-workspace --crash-reporter-id 9eb0e297-9d77-403a-8252-44309888e869|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
todo-tree|Gru|0.0.213
language-cython|guy|0.0.6
vsc-python-indent|Kev|1.14.2
git-graph|mhu|1.30.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.7.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by lilanxiao** [comment]
I got a similar issue with the default Dark+ theme. After the recent upgrade, it doesn't work properly with Python. I think it's a Python-specific issue, as this color theme works fine with C/C++. Also, my system info is similar to yours, the only difference is that I'm using Ubuntu and installed VSCode with apt. 
![Screenshot from 2021-06-10 23-03-59](https://user-images.githubusercontent.com/44202004/121596772-30c70880-ca40-11eb-8f41-6308efd28039.png)
Interestingly, the third-party One Dark Pro theme works for me. So if you need syntax highlighting now, you could switch to this theme before the issue gets fixed.
![Screenshot from 2021-06-10 23-04-47](https://user-images.githubusercontent.com/44202004/121596836-489e8c80-ca40-11eb-93f8-774d4575c563.png)

**Comment by DennisC-Jacobs** [comment]
> Interestingly, the third-party One Dark Pro theme works for me. So if you need syntax highlighting now, you could switch to this theme before the issue gets fixed.

This does fix some of it, but the imports are still not quite there. For now, though, this is a good help.

**Comment by zlalvani** [comment]
I am also seeing this, and there's some concerning stuff in the Python output that may be related (truncated by me): 
`We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-10 17:10:57: Failed to activate language server, Class name = a, completed in 6ms, has a falsy return value`

**Comment by FMalerba** [comment]
I also think it might have to do with the language server, When I try to set the language server to Microsoft and restart it I get the errors in this txt file: (coing from the python output console)

[python_output.txt](https://github.com/microsoft/vscode/files/6634801/python_output.txt)

**Comment by JenusL** [comment]
This has now been fixed here https://github.com/microsoft/pylance-release/issues/1428
Just restart VS Code so that the Python extension gets updated and then reload the extension.
