### ISSUE TITLE
Feature to lock folders(unclickable) and pin folders to top of the Folders section.

### ISSUE THREAD

**Issue by sneharghya-pathak** [microsoft/vscode#125922]
Folders like node_modules are a pain in vs-code if opened by mistake. If the folders are sufficiently big, it is painful and time consuming to scroll up/down all the way to close the folders. 
I would like to get these folders out of the way by pinning these folders to the top, or having an option to disable opening the folders.
Pinning to top can also be helpful in locating frequently used folders in a large codebase.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks
