### ISSUE TITLE
Don't spam my github feed

### ISSUE THREAD

**Issue by PhilipSkinner** [microsoft/vscode#125951]
I would ask that you keep your marketing messages for vscode releases off my github feed.

I had all notifications ignored for this repo but someone has decided to ignore that and have spammed my feed.

**Comment by misolori** [comment]
This is a GitHub feature and not something VS Code controls. Please send your feedback to the [GitHub Team](https://support.github.com/contact).

**Comment by PhilipSkinner** [comment]
Incorrect, normally these show up if you have notifications turned on for a repo - I turned notifications off on this repo a long time ago and I have never had a notification appear on my feed since then until today.

Something has changed - I don't get notifications on other repos I have starred yet silenced notifications for.

I can evidence this with a simple screenshot of my feed, see the notification today:

![Screenshot_2021-06-10_22-14-25](https://user-images.githubusercontent.com/879532/121598299-99f74d80-ca39-11eb-9e05-fc7f43e17166.png)

; now compare that to a screenshot of my feed that overlaps with your release from 28 days ago:

![Screenshot_2021-06-10_22-16-02](https://user-images.githubusercontent.com/879532/121598303-9bc11100-ca39-11eb-83dc-a825fe010bbc.png)

The previous releases are missing from my feed, but your most recent one is sitting there at the top.

**Comment by PhilipSkinner** [comment]
Am I jumping to conclusions that somebody within Github and/or Microsoft decided to ignore notification statuses on purpose in order to further push out a microsoft product? Yes.

Why? Because I see no other releases in my feed from projects I follow yet have silenced notifications for.

I'm tempted to star some other microsoft repos and silence them to see if the same behaviour occurs on them.

**Comment by misolori** [comment]
I think this answers the question:

<img width="587" alt="CleanShot 2021-06-10 at 14 34 56@2x" src="https://user-images.githubusercontent.com/35271042/121600267-0ef66300-c9f9-11eb-885d-628a301e94d6.png">


But you really need to contact GitHub about this issue because we don't control what appears in your feed.

**Comment by PhilipSkinner** [comment]
Nope - it definitely doesn't.

Why didn't I get notifications for this repo in the past? I starred this repo many years ago.

The sooner you accept the fact that someone is playing funny buggers with the notifications coming out of your repository the better.

I've unstarred this now, every time I try to start to like things microsoft are doing I soon end up with a sour taste in my mouth.
