### ISSUE TITLE
Extension `Feature Contributions` missing notebooks

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#125961]
1. Open extension tab `Feature Contributions` for extension from `@category:"notebooks" `
2. Notebook contributions are not rendered

![Screenshot (41)](https://user-images.githubusercontent.com/9638156/121589592-ecd40380-ca3f-11eb-99d1-4ee8544a3a7f.png)

**Comment by rebornix** [comment]
@sandy081 do you know what we potentially miss?

**Comment by sandy081** [comment]
It makes feature contributions incomplete and users will not be aware of missing ones. It is easy to add contributions there. Ref:  https://github.com/microsoft/vscode/blob/4168941deec97e4416493daf844e516740c716b3/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L1308-L1308

Please let me know if you need any help.

**Comment by rebornix** [comment]
@sandy081 thanks for the guidance, it's well structured and intuitive to extend.
