### ISSUE TITLE
Webview ServiceWorker throws exception on HEAD requests

### ISSUE THREAD

**Issue by Vtec234** [microsoft/vscode#125980]
Steps to Reproduce:

1. Make a `HEAD` request for a local resource proxied through `asWebviewURI`.
2. `Cache.put` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/webview/browser/pre/service-worker.js#L240) throws `TypeError`.

This behaviour is expected as per the ServiceWorker spec which [only allows `GET` requests](https://w3c.github.io/ServiceWorker/#cache-put) in `Cache.put`. The worker code should probably check that the method is `GET` before caching. However it would ideally still allow `HEAD` requests (just not cache them) as these are useful to extensions.

CC @mjbvz

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows_NT x64 10.0.19043

**Comment by mjbvz** [comment]
Good find

To verify:

1. At the top of your workspace, create markdown 
2. Also create an image called `img.png`
1. In markdown preview, add the content:

```js
<script>
  fetch('img.png', {
    method: 'HEAD'
}).then(async (e) => {
    console.log(e.status);
    console.log(e.headers.get('content-type'));
})
</script> 
```

3. Open the markdown preview and make sure scripts are enabled (there should be a warning if they are not)
4. Now open the developer tools and confirm you see `200` and `image/png` printed and no errors related to the service worker
