### ISSUE TITLE
Allow to customize the application icon per workspace

### ISSUE THREAD

**Issue by dermoth** [microsoft/vscode#125990]
I started using VS Code at work and because I often work on multiple projects with different languages/settings/extensions I always end up with multiple open windows. VSCode should provide a way to differentiate between them by allowing per-workspace setting for the application icon, ideally with the options of choosing between a set of stock icons or using one from the workspace directly.

This is a dup of #99415; it's been over a year and a lot has changed such as remote ssh capability and I think we should revisit this.

**Comment by rtllxndr** [comment]
Here is my solution https://github.com/rtllxndr/update-icons/
