### ISSUE TITLE
Search improvement - search in symbols and string literals in all files of project.

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#125988]
We have text search for now. It's works fine.
And we have search symbols in the current activated file.

But It's a common case that we want to search something in symbols (or string literal) in all files in the project.
It's might not only an editor feature but also need language service ‘s support.

**Comment by roblourens** [comment]
We have the command "Go to symbol in workspace", `cmd+T` by default, that sounds like what you are looking for

**Comment by Kingwl** [comment]
Well, Looks cool. Thanks!

What about search in the string literals?

**Comment by roblourens** [comment]
We have looked at that in the past but language-specific text search features are currently not practical for us to do, sorry.
