### ISSUE TITLE
Debugging with integratedTerminal ignores defaultProfile

### ISSUE THREAD

**Issue by ozendelait** [microsoft/vscode#125918]
Does this issue occur when all extensions are disabled?: No
vscode-python issue was closed as this is a problem with vscode itself (see issue https://github.com/microsoft/vscode-python/issues/16363 )

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. set "terminal.integrated.defaultProfile.windows" (to e.g. bash) in user settings
2. File / Open Folder / (select folder with python file)
3. Run and Debug (Ctrl + Shift +D) 
4. Click "Open a file" / (select any python file)
5. Click "Run and Debug" Button (select "Python" from drop-down)

## Expected behaviour

debugging with "console": "integratedTerminal" should use the Terminal selected by "terminal.integrated.defaultProfile.windows"

## Actual behaviour

PowerShell is used

**Comment by weinand** [comment]
@Tyriar we are using [this code](https://github.com/microsoft/vscode/blob/be58d5f771671a39cfd6e8dc9a2485da3ba4a11b/src/vs/workbench/api/node/extHostDebugService.ts#L83-L111) to determine the shell to use in the integrated terminal.

This does not seem to work with the new "defaultProfile" feature.
Please advise how to fix this.

**Comment by Tyriar** [comment]
@weinand did you try this out in 1.57? I believe it's fixed there in https://github.com/microsoft/vscode/pull/123729

**Comment by weinand** [comment]
@ozendelait does this now work in  VS Code 1.57?

**Comment by ozendelait** [comment]
No; "terminal.integrated.defaultProfile.windows" and "terminal.integrated.profiles.windows" still show no effect (PowerShell is used instead).
I'm currently using the legacy "terminal.integrated.shell.windows" and "terminal.integrated.shellArgs.windows" as a fallback

**Comment by weinand** [comment]
@Tyriar please advise how I should proceed

**Comment by Tyriar** [comment]
This works fine for me on Insiders:

![image](https://user-images.githubusercontent.com/2193314/124915837-da011000-dfa6-11eb-9f27-f5257193b001.png)

I did fix this I believe in 1.57.

> I'm currently using the legacy "terminal.integrated.shell.windows" and "terminal.integrated.shellArgs.windows" as a fallback

Note that if you set this the default profile setting will be ignored, maybe that's the issue?

**Comment by weinand** [comment]
@ozendelait could you please remove the legacy settings and try again

**Comment by Tyriar** [comment]
This could have actually been an issue in the Python extension that has since been fixed also, I believe they use `env.shell` to get the default shell here and they had some wrong assumptions around that API until recently.

**Comment by ozendelait** [comment]
Yes, I have tested v1.58 with the "terminal.integrated.shell.windows" and "terminal.integrated.shellArgs.windows" commented out and settings through "terminal.integrated.defaultProfile.windows" are now being observed.
Thanks!

**Comment by weinand** [comment]
@ozendelait great, thanks for verifying.
