### ISSUE TITLE
Update deleted/messed up my settings

### ISSUE THREAD

**Issue by fredg1** [microsoft/vscode#125991]
Issue Type: <b>Bug</b>

Unknown.

I updated, and when the update was over, there was a notification saying that VScode couldn't write in my settings. I open the linked file, and the content was

{
	"workbench.editorAssociations": {
		"*.ipynb": "jupyter-notebook"
	}
} k"
}

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.57GB free)|
|Process Argv|--crash-reporter-id 88dd0741-be1d-4270-b1d6-4a2867d9f4ad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
markdown-checkbox|bie|0.1.3
codestream|Cod|11.0.10
gitignore|cod|0.7.0
vscode-github-actions|csc|0.18.0
macros|ctf|0.0.4
vscode-kolmafia-ash|dan|0.5.1
vscode-eslint|dba|2.1.22
xml|Dot|2.5.1
gitlens|eam|11.4.1
code-runner|for|0.11.4
macros|ged|1.2.1
vscode-pull-request-github|Git|0.27.0
xtend-lang|Gra|0.2.3
xtext-lang|gra|0.4.0
todo-tree|Gru|0.0.213
monkey-patch|ioc|0.1.13
vscode-essentials|jab|1.5.0
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.9.1
svn-scm|joh|2.13.6
pretty-formatter|mbl|0.2.2
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.2
dotenv|mik|1.0.1
escape-quotes|mil|1.10.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
remote-wsl|ms-|0.56.4
color-highlight|nau|2.3.0
gremlins|nho|0.26.0
fabric8-analytics|red|0.3.3
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
control-snippets|svi|1.9.1
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
codetour|vsl|0.0.56
gistfs|vsl|0.2.8
cursorCharCode|zei|0.2.0
svn-helper|Zlo|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by gjsjohnmurray** [comment]
Looks like #125970

**Comment by fredg1** [comment]
yeah, seems like it.
