### ISSUE TITLE
[css] CSS completion by writing value first

### ISSUE THREAD

**Issue by Drarig29** [microsoft/vscode#125913]
Imagine I want to space evenly my flex box items. And I don't remember the name of the property which value can be `space-evenly` or simply I want to write it quicker.

I would write "spaceevenly" and <kbd>Tab</kbd> and it would autocomplete: `justify-content: space-evenly;`

**Comment by aeschli** [comment]
It's an interesting idea, not sure it fits well in code completion, which is mostly about completing what you have already typed.
If someone want to work on this, I would suggest to do it in an extension.
