### ISSUE TITLE
PHP HTML Auto indent and tag completion not working.

### ISSUE THREAD

**Issue by TK-4217** [microsoft/vscode#125983]
When editing HTML in a .php file, html's auto indent and tag completion stop working. I tested it on another computer, same issue. For instance:
``` 

When I type <p, and then > it should autocomplete the tag i. e. <p></p>. Then when my cursor is in the middle, <p>|</p> where | is the cursor, and I press enter, it should turn into

<p>
    |
</p>
It doesn't.
Instead, no autocomplete, and when i press enter as shown above it turns into this:
<p>
|</p>

```
I have installed numerous extensions, none of which worked (all disabled now).
This cropped up yesterday afternoon, before which it worked fine.
It works as intended in .html files, unfortunately those don't support php.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.56.2 and 1.57 have the issue
- OS Version: Windows 10 Home 20H2

Steps to Reproduce:

1.Open a .php file in vscode
2.Type <html
3.Type >
4.Observe it not working.
5.Type</html>
6.Go back in between the open and closing tags
7.Press enter

**Comment by roblourens** [comment]
I don't think this has ever been supported in php. https://github.com/microsoft/vscode/issues/76800 Maybe there is an extension that does this.
