### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/vscode#125945]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.4

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:158009:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:159079:46)
    at /home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:160954:28)
    at IOSession.Session.executeCommand (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:160963:33)
    at IOSession.Session.onMessage (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:160989:35)
    at Interface.<anonymous> (/home/misamoto/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/extensions/node_modules/typescript/lib/tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (7.49GB free)|
|Process Argv|--crash-reporter-id b1db9ef2-a6cc-4a91-b491-fed307cca03f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|5.80GB (1.90GB free)|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
es7-react-js-snippets|dsz|3.1.1
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.6
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.7.0
jenkinsfile-support|sec|0.1.0
ejs-snippets|Tao|0.1.0
errorlens|use|3.2.7
vscode-icons|vsc|11.4.0
vscode-css-formatter|aes|1.0.1
vscode-apollo|apo|1.19.3
atlascode|atl|2.9.0
close-all|ben|1.0.2
vscode-expo|byC|0.6.0
gitignore|cod|0.7.0
meld-diff|dan|1.1.0
vscode-markdownlint|Dav|0.42.0
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|6.4.0
copy-relative-path-and-line-numbers|ezf|0.3.1
vscode-diff|fab|1.4.1
vscode-jest-runner|fir|0.4.39
vscode-monorepo-workspace|fol|1.3.1
auto-rename-tag|for|0.1.6
shell-format|fox|7.1.0
lintlens|ghm|3.0.0
vscode-pull-request-github|Git|0.26.0
gc-excelviewer|Gra|3.0.42
vscode-mocha-test-adapter|hbe|2.12.0
vscode-test-explorer|hbe|2.20.2
vscode-guid|hea|1.4.20
lorem-whatever|job|1.0.2
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
vscode-jest-test-adapter|kav|0.8.1
vscode-home-assistant|kee|1.18.0
vscode-gutter-preview|kis|0.27.1
vscode-fix-checksums|leh|1.1.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
test-adapter-converter|ms-|0.0.9
vsliveshare|ms-|1.0.4360
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
color-highlight|nau|2.3.0
angular-console|nrw|17.4.1
vscode-versionlens|pfl|1.0.9
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.7.0
heroku-command|pko|0.0.8
prisma|Pri|2.24.1
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
synthwave-vscode|Rob|0.1.8
jenkinsfile-support|sec|0.1.0
ahoy-ipsum|tal|0.0.2
ejs-snippets|Tao|0.1.0
vscode-pets|ton|1.8.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-conventional-commits|viv|1.21.0
vscode-icons|vsc|11.4.0
docker|vsc|1.0.0
yaml|vsc|1.0.0
copy-with-line-numbers|yas|0.0.4
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|3.4.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by Faithfinder** [comment]
Hey, sorry, I seriously thought I bailed out of creating this issue. 

It was a one-time error and didn't happen since then, so I don't see a point in investigating any more on my side. Feel free to close this.
