### ISSUE TITLE
Losing user settings and workspace settings with reloading a folder

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#12591]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1.  Right Click to Open New Window
2.  Open a folder you have already been working on
3.  All your tabs will show, but you will lose your user settings and workspace settings in preferences.

**Comment by chrmarti** [comment]
Please clarify:
- Is the same folder already open in a different window at that time?
- Does this reproduce consistently?
- Any more detailed steps to reproduce? (It works for me.)

**Comment by soljohnston777** [comment]
I go between 2 folders htdocs then to htdocs/folder and back.  It doesn't do it all the time.  But it seems to do it when I go from htdocs to htdocs/folder the most.

**Comment by bpasero** [comment]
@soljohnston777 can you clarify what kind of setting in particular you are loosing? keep in mind that workspace settings are dependent on the folder you are open as workspace.

**Comment by soljohnston777** [comment]
With this last update it hasn't been doing it now.
