### ISSUE TITLE
Stop auto resizing panes when focused

### ISSUE THREAD

**Issue by smitbarmase** [microsoft/vscode#125997]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Fedora 34

Steps to Reproduce:

1. After splitting the panes, try dragging the divider all the way to the left.
2. Now focus on the larger pane, and back to the smaller one.
3. You will see a smaller pane automatically resizes.

![preview](https://user-images.githubusercontent.com/37347831/121639519-483adb80-caaa-11eb-8a94-c542139426ea.gif)

**Comment by ArturoDent** [comment]
I don't think there is a setting to stop doing that (I could be wrong).  But notice if you back off like one pixel from completely minimizing one split, the maximizing on focus will no longer happen.

**Comment by smitbarmase** [comment]
Yes. It works. Also, I have checked all setting regarding panes, I don't see any option to turn this behaviour off. It should be there as this behaviour is annoying if I just want panes to stay as they are.

**Comment by carlocardella** [comment]
The command is `Maximize editor view` (command id `workbench.action.minimizeOtherEditors`), try to toggle it: 

![image](https://user-images.githubusercontent.com/5784415/121778624-8be62180-cb4c-11eb-85df-fc4979a2b605.png)

**Comment by smitbarmase** [comment]
Not working. It shows "Unknown configuration setting".

![image](https://user-images.githubusercontent.com/37347831/121778798-42322100-cbb6-11eb-9d06-671a85603603.png)

**Comment by ArturoDent** [comment]
I think that setting was removed when the maximization on focus was made automatic.

**Comment by carlocardella** [comment]
It is a command, not a setting, it's still available from the command palette (I have added a keybinding to it). I still use this to toggle the zoom effect (both in Insiders and Stable): 

![image](https://user-images.githubusercontent.com/5784415/121780542-affa3080-cb55-11eb-86f1-54de67be30f9.png)


![maximize editor group](https://user-images.githubusercontent.com/5784415/121780538-ab357c80-cb55-11eb-807f-78b305f60302.gif)

**Comment by smitbarmase** [comment]
I see. But you are actually resizing (resetting) the views. I don't want to resize them.

**Comment by carlocardella** [comment]
Use `Reset Editor Group Size`, then resize the editors and they keep their size: 

![reset editor group](https://user-images.githubusercontent.com/5784415/121792221-13f91500-cba7-11eb-9228-e6377dbfed9e.gif)

**Comment by smitbarmase** [comment]
Try dragging that to the all the way left. It works if we drag inbetween somewhere, but as you drag it all the way left so that there is no more space to drag, that's where all the problem lies.

After that, it will not work as expected.

**Comment by carlocardella** [comment]
You're right, in that case I can reproduce the behavior, this looks like a bug to me, I'll let @joaomoreno comment on it then: 

![editor max size bug](https://user-images.githubusercontent.com/5784415/121829962-c816a080-cc78-11eb-9547-b414faa0b22e.gif)

**Comment by joaomoreno** [comment]
@bpasero We should introduce a setting for this behavior.
