### ISSUE TITLE
Support Checkboxes in markdown.showPreviewToSide

### ISSUE THREAD

**Issue by neelkarma** [microsoft/vscode#125921]
When using checkboxes in markdown files, e.g.
```md
- [ ] Task 1
- [ ] Task 2
- [x] Task 3 (completed)
```
Using `markdown.showPreviewToSide` doesn't display them properly, as shown below:

![image](https://user-images.githubusercontent.com/59462098/121517359-9f9d6500-ca32-11eb-9261-02dbd4a40f01.png)

It would be nice if they were displayed correctly.

Edit: For reference, here's how checkboxes are displayed in GitHub:
- [ ] Task 1
- [ ] Task 2
- [x] Task 3 (completed)

**Comment by mjbvz** [comment]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by neelkarma** [comment]
Oh, my bad.
