### ISSUE TITLE
Linux: cannot run as `sudo` anymore

### ISSUE THREAD

**Issue by ccieliu** [microsoft/vscode#125982]
[vscode_crashed.zip](https://github.com/microsoft/vscode/files/6635468/vscode_crashed.zip)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:   code/stable,now 1.57.0-1623259737 amd64 [installed]
- OS Version:

NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@uisee-Vostro-5402:/var/log# uname -a
Linux uisee-Vostro-5402 5.8.0-050800-generic #202008022230 SMP Sun Aug 2 22:33:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. sudo code --user-data-dir /usr/local/etc/vscode/
2.

root@xxxx:/var/log# tailf apport.log
ERROR: apport (pid 8699) Fri Jun 11 10:26:42 2021: called for pid 8698, signal 5, core limit 0, dump mode 1
ERROR: apport (pid 8699) Fri Jun 11 10:26:42 2021: executable: /usr/share/code/code (command line "/usr/share/code/code --user-data-dir /usr/local/etc/vscode/")
ERROR: apport (pid 8699) Fri Jun 11 10:26:42 2021: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 8699) Fri Jun 11 10:26:42 2021: this executable already crashed 2 times, ignoring

Issue description:
- vscode cannot bootup when using sudo.
- vscode can bootup in other user

**Comment by ccieliu** [comment]
I was downgrade to "code/stable,now 1.56.2-1620838498 amd64 [installed,upgradable to: 1.57.0-1623259737]"  bypassed the issue.
The issue  only occur on 1.57.0, both stable and insiders as test out. 
Any body can fix the issue?

**Comment by bpasero** [comment]
One change that did happen in this release is the removal of `--no-sandbox`, cc @deepak1556 

Does it work if you add `--no-sandbox`?

**Comment by ccieliu** [comment]
> One change that did happen in this release is the removal of `--no-sandbox`, cc @deepak1556
> 
> Does it work if you add `--no-sandbox`?


Upgrade to 1.57.0 again, and test out.
working fine with a warning as below, thanks for your help. and have a good day.

fyi:

```
root@xxxxx~# code --user-data-dir /usr/local/etc/vscode/  --no-sandbox
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by bpasero** [comment]
I think this is "as designed", but I let Deepak speak up.

**Comment by alestor123** [comment]
[Electron Issue](https://github.com/electron/electron/issues/18265)

**Comment by kalsan** [comment]
Another way to reproduce it is running VS Code from Snap (no user interaction with sudo involved), see #126007

**Comment by bpasero** [comment]
I reopened https://github.com/microsoft/vscode/issues/126007 to keep that specifically for snap, thanks for pointing that out.

**Comment by deepak1556** [comment]
This is expected behavior of the user namespace sandbox used by chromium. 

@ccieliu why are you opening vscode with sudo ?
