### ISSUE TITLE
Quick Open View- keyboard go back to Open editors/Editor groups (main text editor panel) (accessability)

### ISSUE THREAD

**Issue by mwoz123** [microsoft/vscode#125940]
UDPATE: **scroll down for Slideshow**

When switching between VSCode panels (_using keyboard only_) Quick Open View is very helpful.

Unfortunately when you use it to switch from text editor panel to eg. Explorer or Search you cannot go back (to text editor) using the same Quick Open View.

Workaround for this is to use Crtl+tab but then you're not in last edited file but rather previously edited file :( 

Could you add "Main text editor" panel to Quick Open View ?

**Comment by TylerLeonhardt** [comment]
@mwoz123 do you think you could provide some screenshots? I'm not quite following what you're describing. Thanks!

**Comment by mwoz123** [comment]
Let me explain that on slideshow ;) - with **red rectangle** marked **current** active panel

![image](https://user-images.githubusercontent.com/4487025/121661145-322a1c80-caa4-11eb-97c9-ab06d328fd0b.png)


then press CRTL+Q to activate e.g. Source Control

![image](https://user-images.githubusercontent.com/4487025/121661255-4e2dbe00-caa4-11eb-8963-cec0c015d9aa.png)

Active panel is Source Control now:
![image](https://user-images.githubusercontent.com/4487025/121661397-72899a80-caa4-11eb-9e77-93226fa9ffdb.png)


You commit your files and want to go back to editing previous file (`package.json` here, from 1st slide). 

How you do that with keyboard ?  
Opening again `Quick Open View` again?  
No luck there's no "Text editor panel" or whatever it's called 

![image](https://user-images.githubusercontent.com/4487025/121662205-55a19700-caa5-11eb-934e-80d66e1f9ae7.png)

Workaround is to press CTRL+TAB twice, but that's not the best UX ...

**Comment by mwoz123** [comment]
Could you add option to `Quick Open View` to activate panel from 1st slide ? 

Would be great if it could be first item on list when something else than text editor panel is active.

**Comment by TylerLeonhardt** [comment]
@mwoz123 excellent explanation :) this makes a ton of sense.
