### ISSUE TITLE
Serial port disconnect + connect don't reset Arduino

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode#125911]
Issue Type: <b>Bug</b>

When doing 'disconnect' then 'connect' on the Serial port, the attached Arduino Nano (FTDI) does not reset.

When doing the same with the serial port from a C# program it is possible to reset the Arduino by controlling the DTR line.

Seems like the VS-Code serial port controls does not control DTR line correctly.

Maybe it should be an option to be able to select if DTR and/or RTS should be controlled when disconnecting/connecting the Serial port.

In my mind, this is not caused the Arduino plugin, as the serial port is a VS-Code feature.

Preferrebly a setting to enable DTR/RTS control should be a project/workspace settting.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (16.21GB free)|
|Process Argv|--crash-reporter-id 937b32ac-d42d-4d5c-8600-a5390f81789c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color-pick|ada|0.6.2
vscode-base64|ada|0.1.0
Bookmarks|ale|13.0.4
ignoregit|And|1.0.1
css-theme-completions|con|0.0.4
doxdocgen|csc|1.3.2
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-pull-request-github|Git|0.26.0
output-colorizer|IBM|0.1.2
hex-fmt|ker|1.0.0
quick-notes|Lia|1.9.0
linecounter|lyz|0.2.7
git-graph|mhu|1.30.0
cpptools|ms-|1.4.0
hexeditor|ms-|1.6.0
powershell|ms-|2021.2.2
text-power-tools|qcz|1.27.0
calc|rai|2.0.1
vscode-hexdump|sle|1.8.1
vscode-multiclip|sle|0.1.5
vscode-arduino|vsc|0.4.3
gitblame|wad|7.0.6
hex-ascii-converter|yrp|0.0.3
vscode-asciiflow2|zen|0.2.0

</details>

**Comment by iqapps** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Select Serial Port not allowing to select Serial Port (#123603)](https://www.github.com/microsoft/vscode/issues/123603)

Not the same issue...

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Arduino support comes from an extension you installed. Your issue needs to be investigated by the extension author.

**Comment by iqapps** [comment]
Issue created in Arduino extension issues:

See [vscode-arduino/issues/1285](https://github.com/microsoft/vscode-arduino/issues/1285)
