### ISSUE TITLE
Provide Last-Modified and Content-Length information for webview local resources

### ISSUE THREAD

**Issue by Vtec234** [microsoft/vscode#125992]
Since the only way to access local resources in a webview is via web requests proxied through `asWebviewUri`, it would be nice if the ServiceWorker handling these provided additional metadata in the headers, namely `Content-Length` and `Last-Modified`, whenever possible. With this feature, webview extensions can allocate buffers of the right size (length) and do some caching (mtime).

CC @mjbvz

**Comment by mjbvz** [comment]
See  steps in https://github.com/microsoft/vscode/pull/125994 for verification
