### ISSUE TITLE
Linux: numpad_decimal is "unknown"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1259]
Looks like we fail to resolve only this one, the others work nicely on Linux.

**Comment by alexandrudima** [comment]
@bpasero I get `numpad_decimal` when pressing the numpad `.` (`Del`) key under Lubuntu based on Ubuntu 15.10 and under Ubuntu 14.04.3 LTS.

Can you please try `lsb_release -a` and add the version you have.

**Comment by bpasero** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

Maybe this is a parallels issue?
