### ISSUE TITLE
Can create illegal file end with '.'

### ISSUE THREAD

**Issue by niltok** [microsoft/vscode#125919]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Window 10 20H2 (19042)

Steps to Reproduce:

1. Create a folder named with 'cpp.' using file manager of vscode.
2. Vscode will create it and can read files inside but powershell and file manager of windows cannot open the folder.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/117426
Fixed in latest insiders, soon in stable, thus closing
