### ISSUE TITLE
improve auto importations

### ISSUE THREAD

**Issue by mablue** [microsoft/vscode#125935]
why when there is two class with same name it get the far one automaticly?it will ask me which i want .
https://github.com/freqtrade/freqtrade-strategies/pull/196#discussion_r648845476

**Comment by mablue** [comment]
its a bot named freqtrade and when I want to write an strategy and want to import this packages (Intparameter,DecimalParameter, CatagoricelParameter) vscode auto import a thing from a far place to my code! instade of the standard one you can see on my file.it will ask me to do that befour adding automaticly I think

**Comment by mjbvz** [comment]
Please fill in the issue template and provide an example of the expected behavior

**Comment by mablue** [comment]
> Please fill in the issue template and provide an example of the expected behavior

ok just I will first test with all extensions disabled.and so I will post the templete

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate
