### ISSUE TITLE
Don't show `x` for currently opened files under "recently opened" in file quick access

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125977]
Repro:

1. Dirty an editor
2. Switch tabs
3. Ctrl/cmd+p
4. Click the x, it disappears from the list but the editor does close - it should prompt

![recording (10)](https://user-images.githubusercontent.com/2193314/121611835-03616700-ca0e-11eb-9255-3da3f3580dc3.gif)

**Comment by TylerLeonhardt** [comment]
@Tyriar is this a regression? Did it ever work this way?

**Comment by Tyriar** [comment]
Yes it's a regression, I wouldn't say it's particularly important though

**Comment by bpasero** [comment]
Actually works as designed. The behaviour for seeing the close dialog works fine when using the editors picker.

![recording](https://user-images.githubusercontent.com/900690/121709338-bc8c7380-cad8-11eb-810f-111f4207a65e.gif)

**Comment by Tyriar** [comment]
Oh I see now, it's removing the recently opened entry, not closing the file. Ambiguity could be removed here by just removing the ability to remove the item for _currently opened editors_, since clicking the x doesn't remove it from recently opened as it's currently open.

**Comment by bpasero** [comment]
I am not really convinced this is worth it. I also do not agree with what you are saying, I can remove entries, even when they are opened if e.g. I close editors afterwards:

![recording](https://user-images.githubusercontent.com/900690/121766224-dbc6e780-cb50-11eb-9069-10c62fcc0874.gif)

Given you can have tons of editors open I think a user might not really understand why suddenly some entries in the list cannot be closed while others can. Imho this adds more complexity than being helpful.
