### ISSUE TITLE
Virtual Workspace - operable extention's disabled on VScode restart

### ISSUE THREAD

**Issue by Cascade-Media** [microsoft/vscode#125939]
Issue Type: <b>Bug</b>

**About**
This report is to showcase and replicate the effects of extensions that worked previously over virtual workspaces that are being request to be disable or are disabled by VScode.

**Process Full**
1. When loading up a clean instance of VScode “no open folders or workspaces” I navigated to the extension icon for “SSH FS”, this extension allows me to remotely access a server’s files and folder structure.
To connect to a remote server you must have a remote server configuration, after which you can select the server name and connect to it by the folder icon that says on hover “Add as Workspace folder”

2. On triggering the Add as workspace folder, if successful will load the files and folder structure on the Remote server.

3. To test that PHP IntelliSense extension is operating we can try and call a function name that the extension will attempt to autocomplete.
Test preformed: typed in .php file_ "in attempt to discover file_get_contetns()"
Test result: the extension is operating as expected.

    3.1 Checking the extensions menu shows a pending "reload required" on some plugins that are currently in use.
 
4. If we either close VScode and restart or perform the action “reload required” on a specified plugin, the extensions will be disabled, rendering a previously operable extension inoperable.

the reason behind this is apparently due to the extension lacking support for virtual workspaces, however shown in section 1 – 3 that it should be operable.
Test preformed: typed in .php file_ "in attempt to discover file_get_contetns()"
Test result: PHP IntelliSense no longer functioning after VScode restart.
 
5. Re-enabling the extensions for virtual workspaces is possible, however requires the full closure of a workspace, followed with the process of step 1.

**Process Minified**
1. Load VScode in fresh state "no folders or workspaces"
2. Open the SSH FS, select a configuration and "Add as Workspace folder"
3. Check extensions requesting "reload required" and test the functionality of the extension e.g. in my case it was PHP Intellisense and it was operating as intended.
4. Either close VScode or Reload the extensions, the previously working extension that required a restart should now be disabled. The extension will no longer work for virtual workspaces.
5. Re-enabling the extensions for virtual workspaces is possible, however requires the full closure of a workspace, followed with the process of step 1.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
apacheconf-snippets|eim|1.3.0
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
html-slim-scss-css-class-completion|gen|1.7.8
vscode-sshfs|Kel|1.20.1
twig-language-2|mbl|0.9.2
php-namespace-resolver|Meh|1.1.8
vscode-apache|mrm|1.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
sass-indented|syl|1.8.16
ayu|tea|0.20.1

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem still occur after you update to 1.57, which shipped today?

**Comment by sandy081** [comment]
@egamma User claims that the extension `felixfbecker.php-intellisense` works in virtual workspaces and it looks like we have configured this to be disabled in virtual workspaces. 

@Cascade-Media You can override VS Code decision and enable this extension in virtual workspaces using following setting
`extensions.supportVirtualWorkspaces`

Here is the doc for virtual workspaces - https://code.visualstudio.com/blogs/2021/06/10/remote-repositories

@bamurtaugh @eamodio I think it would be useful to mention about above setting and let users enable their extensions.

**Comment by Cascade-Media** [comment]
> Does the problem still occur after you update to 1.57, which shipped today?

The issue is still occurring with the latest update (1.57.0) on both my primary machine and also on laptop.

**Comment by Cascade-Media** [comment]
@sandy081
I managed to override the extension and get it enabled for virtual workspaces using the following in settings.json.
`"extensions.supportVirtualWorkspaces": {
    "felixfbecker.php-intellisense": true
},`

However like before, the extension itself is not functioning after restarting VS Code with the workspace open.

**Comment by egamma** [comment]
No longer disabling felixfbecker.php-intellisense for virtual workspaces.
