### ISSUE TITLE
plugin upgrade bug

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#12592]
- VSCode Version:1.5.3
- OS Version: mac

Steps to Reproduce:

1. publish two version of my plugin in one hour
2. go to extensions tab
3. update plugin
4. press `enable` to restart
5. go to extensions tab and `update` is still warning.

![image](https://cloud.githubusercontent.com/assets/227713/18821808/32991342-83dc-11e6-91cf-37c7293534fc.png)

![image](https://cloud.githubusercontent.com/assets/227713/18821826/52e55034-83dc-11e6-94cd-5402bd43d939.png)

**Comment by joaomoreno** [comment]
#12011
