### ISSUE TITLE
Terminal 

### ISSUE THREAD

**Issue by rahulprogrammer0** [microsoft/vscode#125999]
Issue Type: <b>Bug</b>

why not showing my vs code terminal if i type anyting in the  terminal it's woking ! please let me know how can i fix my problems 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4000 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.91GB free)|
|Process Argv|--crash-reporter-id 49385ad4-831b-4e5e-8641-7a86ff5e8a8e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
emojisense|bie|0.8.0
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.42.1
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.11.0
vscode-eslint|dba|2.1.22
githistory|don|0.6.16
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|6.4.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.4
git-extensions-for-vs-code|for|1.1.3
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
vscode-github|Kni|0.30.6
MagicPython|mag|1.1.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
cpptools|ms-|1.4.1
vsliveshare|ms-|1.0.4360
debugger-for-chrome|msj|4.12.12
fix-json|oli|0.1.2
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
