### ISSUE TITLE
formatDocumentRangesWithProvider: cts.dispose is called multiple times

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#125942]
This looks fishy:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/editor/contrib/format/format.ts#L189

I guess the try finally should be moved to the outside?

Also, `await provider.provideDocumentRangeFormattingEdits(...)` could be called in parallel.

**Comment by jrieken** [comment]
Yeah, nice one. The `try-finally` should be around the whole loop

**Comment by connor4312** [comment]
Verified in code review
