### ISSUE TITLE
Test explorer doesn't detect suite.only

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#125936]
Issue Type: <b>Bug</b>

it detect `suite` but not `suite.only`

VS Code version: Code - Insiders 1.57.0-insider (Universal) (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T10:41:06.148Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.27GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
Code pointer if you feel like putting in a PR :) https://github.com/microsoft/vscode-selfhost-test-provider/blob/7a021e1e005de3d97757b28b6557ee97cdc094d7/src/sourceUtils.ts#L11
