### ISSUE TITLE
v1.57: Linux integrated terminal broken: "bash is not a file of a symlink"

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/vscode#125959]
Issue Type: <b>Bug</b>

The "troubleshooting steps" at https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch are useless, and provide no practical recommendation as to how to resolve this.

All I know is that I updated VS Code and now it can't load bash.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.8.0-55-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3123)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.30GB (18.00GB free)|
|Process Argv|--new-window --crash-reporter-id 61757f9f-adfa-4308-9443-71069ec82334|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tsserver-debug|and|1.3.0
vscode-apollo|apo|1.19.3
toml|be5|0.5.1
vscode-tailwindcss|bra|0.6.8
better-toml|bun|0.3.2
postcss|css|1.0.9
vscode-eslint|dba|2.1.22
javascript-ejs-support|Dig|1.3.1
prettier-vscode|esb|6.4.0
vscode-graphql|Gra|0.3.16
jbockle-format-files|jbo|3.3.0
solidity|Jua|0.0.120
vscode-phpfmt|kok|1.0.30
twig-language-2|mbl|0.9.2
git-graph|mhu|1.30.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
vscode-typescript-next|ms-|4.4.20210609
debugger-for-chrome|msj|4.12.12
tsserver-live-reload|rbu|1.0.1
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-yaml|red|0.19.2
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
svelte-vscode|sve|105.1.0
vscode-markdown-paste-image|tel|0.12.3
twig|wha|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by ctjlewis** [comment]
Downgrading to 1.56.2 resolved this for now, but the uselessness of the linked article really cannot be overstated. It actually instructs you to *make sure you're on the latest version*, even though it was a bleeding-edge release that caused this issue.

I could've easily been tricked into 3-4 hours of debugging by that guidance, when it was really just a bad update.

**Comment by ctjlewis** [comment]
On 1.56.2, I can open the terminal, but I cannot open files in the editor.

I'm gonna have to keep going back incrementally through releases until I find the previous version I was on. Unit testing is clearly a lie.

**Comment by ctjlewis** [comment]
I had to go all the way back to the March 2021 v1.55 release to work around both of these issues. You can download the installer for your OS here: https://code.visualstudio.com/updates/v1_55

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/124866

If you could give some info on where/what bash is in that issue it would be handy `ls -la $(which bash)`

**Comment by ctjlewis** [comment]
Yeah, I will—90% sure it's just /usr/bin/bash.

**Comment by Tyriar** [comment]
@ctjlewis does adding this setting help?

```
"terminal.integrated.defaultProfile": "bash",
"terminal.integrated.profiles.linux": {
  "bash": {
    "path": "/usr/bin/bash"
  }
}
```

**Comment by ctjlewis** [comment]
I don't know. I downgraded to 1.55 and confirmed it's clearly something in the codebase. I will try this later.

**Comment by dennisleung** [comment]
> @ctjlewis does adding this setting help?
> 
> ```
> "terminal.integrated.defaultProfile": "bash",
> "terminal.integrated.profiles.linux": {
>   "bash": {
>     "path": "/usr/bin/bash"
>   }
> }
> ```

only `bash.path` is needed. It does work for me on v1.57.0! 
thanks a lot.

**Comment by ctjlewis** [comment]
@dennisleung, yes it does.
