### ISSUE TITLE
Show folder in Workspace Trust dialog

### ISSUE THREAD

**Issue by martinthomson** [microsoft/vscode#125984]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.57.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install 1.57.0

What happens:
The new Workspace Trust dialog is shown.  This is modal.  This is OK.

What is missing:
The dialog doesn't show what folder the question relates to, so I can't answer it with any confidence.  I have a few windows open, some of which have multiple folders.

It might be better to just suggest that if people aren't sure, they can choose the safe option and enable the trusted option later.

**Comment by martinthomson** [comment]
> Please also check if it is already covered by an existing one [...]
None of those are directly applicable, but a solution to this might involve a larger change that would address more than one related issue.

**Comment by lszomoru** [comment]
Thank you very much for your feedback! We are exploring including additional details of the folder (location on disk, in case of a git repository - origin, branch, commit, etc.) both in the modal dialog that is being on startup as well as the workspace trust editor.

**Comment by bmcdonnell-fb** [comment]
Indeed, when I saw the dialog asking me if I wanted to trust "this folder", I thought "what folder"?

Please name the candidate paths for the trusted list in the dialog itself.

**Comment by sbatten** [comment]
To Verify:
1. Open an untrusted folder to get the prompt about workspace trust
2. Verify that a monospaced file path to the current workspace file or single workspace folder is shown at the end of the dialog

**Comment by rzhao271** [comment]
I verified that opening a fresh untrusted folder gets the prompt about workspace trust with a monospaced path to the folder I want to open.
I'm unable to see the monospaced path when I try opening a fresh untrusted file in an empty workspace, and I don't see the prompt at all for non-fresh folders.
Fresh in this case means it's a new file/folder that I never opened before.

**Comment by sbatten** [comment]
@rzhao271 sounds as-intended
