### ISSUE TITLE
Terminal hanging on kill command (Ctrl+C)

### ISSUE THREAD

**Issue by jbu4github** [microsoft/vscode#125912]
This is intermittent, but frequent. I use the kill command (Ctrl+C) on my local server in the attached terminal (bash) to VS-code. It hangs for (I dont know how long, but over 10 seconds) and I have to open another terminal instance to put the server back up quickly.

At first I thought it was an open connection closing issue on kill, but I have made sure thats not the case to the best of my ability, and this issue is not reproduced in gitbash at all.

I only have an express server, a mongodb connection, and a nodemailer transport connection, all of which I close manually and promise resolution wait before process.exit(), exit is called and it logs successfully to the terminal, thats when it hangs for no discernible reason.

**Comment by meganrogge** [comment]
What version of vscode are you using?

**Comment by jbu4github** [comment]
I try to keep it updated, its been happening for a while also.

![image](https://user-images.githubusercontent.com/32129753/121722214-10995700-cadd-11eb-91cb-b93fa0a6a375.png)

**Comment by Tyriar** [comment]
Does it hang the whole window - can you type in the editor?

**Comment by jbu4github** [comment]
To be perfectly honest, I don't think I've ever tried, I am reasonably confident its just the terminal instance, because my solution is to open another instance with the + and just run the command there, which works. Terminal 1 releases at some point, but I don't notice because I'm on terminal 2 now. When 2 gets frozen, I go back to 1, which I expect to be unfrozen. I never need more than 2.

**Comment by meganrogge** [comment]
Can you try and let us know if you're able to type in the editor when this happens?

**Comment by jbu4github** [comment]
I am able to type into the editor when it happens. When I click on the editor the terminal cursor turns from a solid bar into a hollow bar, but stays in the same position.

![image](https://user-images.githubusercontent.com/32129753/121903885-a4a73080-cd20-11eb-9cc6-0eb7bd5e5fbc.png)

**Comment by jbu4github** [comment]
This is now happening for me with a simple webpack serve script (no custom backend)

**Comment by Tyriar** [comment]
Do you by chance have text selected when you hit ctrl+c? On Windows if you do it will copy the selection instead of sending ctrl+c to the terminal. You could enable escape sequence logging to see if ctrl+c is getting sent over to the process https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by jbu4github** [comment]
No, I can see a clear difference when I have text selected, the terminal copies the text, as you say, and no kill command is registered.

I have turned on all the logs there, and I'm inspecting Main and Window logs, nothing hugely out of the ordinary appears on those logs when the issue reproduces. 

The first time I reproduced it tonight I got these:

```[2021-07-06 22:35:43.519] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Joe\AppData\Roaming\Code\User\globalStorage
[2021-07-06 22:35:43.519] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\Joe\AppData\Roaming\Code\User\globalStorage
[2021-07-06 22:35:43.720] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\Joe\AppData\Roaming\Code\User\globalStorage```

And thought that writing this file might somehow be causing it to lock, but nothing like that printed out on the subsequent reproduces.

It is interesting how much more difficult it is to reproduce it when I'm trying to. This problem happened around 10 times throughout the day today, starting up the server and immediately closing it doesn't seem to reproduce it at all, It "seems" saving and changing files, then waiting a bit, then killing it appears to do the trick most often. but its not by any means systematically reproducible. 

I have a strange feeling its something to do with file watching / webpack / typescript / git, and the way that vs code observes these events and responds. But thats just an educated hunch at this point :(

**Comment by Tyriar** [comment]
Trace logging is different to escape sequence logging:

![image](https://user-images.githubusercontent.com/2193314/124925775-a5468600-dfb1-11eb-9690-28e64fc7730e.png)

With that enabled you should see something like this when you hit ctrl+c in the devtools console:

![image](https://user-images.githubusercontent.com/2193314/124925848-ba231980-dfb1-11eb-81bc-d1459d622800.png)
