### ISSUE TITLE
Terminal: Rendering error when background colour flows over multiple lines

### ISSUE THREAD

**Issue by eddyashton** [microsoft/vscode#125916]
Issue Type: <b>Bug</b>

There is a rendering error in the VSCode terminal when a background highlight colour is active, and this colour flows over multiple lines in the terminal display. The colour extends to the empty space at the end of the line, when it should only cover the selected colours. This rendering error goes away if the terminal window is resized.

1) Open a Terminal window, in bash or similar.

2) Execute `printf "This text isn't highlighted. \033[48;5;1mThis text is highlighted.\033[0m\n"`, see it renders correctly.
![image](https://user-images.githubusercontent.com/6000239/121508853-f7f64780-c9dd-11eb-9e71-3159f6e8ebcb.png)

3) Execute `printf "This text isn't highlighted. \033[48;5;1mThis text is highlighted and also long, long enough that it causes a line wrap in the highlighted text.\033[0m\n"` (may need to resize your terminal window to be narrower so that this is reflowed over multiple lines.
![image](https://user-images.githubusercontent.com/6000239/121508898-06dcfa00-c9de-11eb-87b4-3e39a3022d5d.png)

4) Observe the rendering error. The highlight should not include the blank space to the right of the text on the second line.

5) Resize the terminal window, and see that the rendering error is removed
![image](https://user-images.githubusercontent.com/6000239/121509019-22e09b80-c9de-11eb-8a27-6b1a962f92fe.png)

~I'm seeing this in an SSH-Remote session, running bash on a remote VM, but not a local VSCode session in WSL. So perhaps its a specific bash version problem, or related to how the remote extension retrieves characters for display.~ _See comments below - this behaviour is present on a local VSCode session, you just need to fill the terminal enough so that it scrolls._

This is present even when the background colour is clearly explicitly terminated before the end of the line, as subsequent text on the line is _not_ highlighted:
![image](https://user-images.githubusercontent.com/6000239/121509335-73f08f80-c9de-11eb-8e41-e049d8676503.png)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.0-1048-azure
Remote OS version: Linux x64 5.4.0-1048-azure
Remote OS version: Linux x64 5.4.0-1048-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.27GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bedashton.uksouth.cloudapp.azure.com/data/src/CCF --crash-reporter-id c77ad9c0-286a-4013-a4af-5cb561cc6186|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: edashton.uksouth.cloudapp.azure.com|
|OS|Linux x64 5.4.0-1048-azure|
|CPUs|Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz (8 x 3696)|
|Memory (System)|31.36GB (17.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: edashton.uksouth.cloudapp.azure.com|
|OS|Linux x64 5.4.0-1048-azure|
|CPUs|Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz (8 x 3696)|
|Memory (System)|31.36GB (17.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: edashton.uksouth.cloudapp.azure.com|
|OS|Linux x64 5.4.0-1048-azure|
|CPUs|Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz (8 x 3696)|
|Memory (System)|31.36GB (17.99GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
close-tabs-to-the-left|ctf|0.0.2
LogFileHighlighter|emi|2.11.0
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
code-sum-up|art|0.1.0
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
svg|joc|1.4.7
azure-pipelines|ms-|1.183.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
azure-account|ms-|0.9.8
cpptools|ms-|1.4.1
cmake|twx|0.0.17
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vshan820:30294714
vscus158cf:30286554
vscod805:30301674

```

</details>

**Comment by Tyriar** [comment]
Can you try enabling escape sequence logging to see what the terminal gets sent? This will identify if it's an issue with ssh/bash or the terminal https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by eddyashton** [comment]
> Can you try enabling escape sequence logging to see what the terminal gets sent? This will identify if it's an issue with ssh/bash or the terminal https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

@Tyriar: Here's the devtools console output for the repro steps above:
![image](https://user-images.githubusercontent.com/6000239/121704584-cd82b800-cacb-11eb-9e02-643387ea1a3c.png)

**Comment by Tyriar** [comment]
@jerch any idea what's happening here? I think the sequences look good.

**Comment by jerch** [comment]
Yes, that behavior results from the BCE setting (background color erase) we automatically apply to newly created lines. Imho most TEs do it that way, some have a settings, whether to apply it the the full line (as we do) or just the actively overwritten cells. There are arguments for both ways, basically there is no proper solution for this, it is under-specced in the terminal interface (if you one way you'll lose expected behavior at other ends and vice versa).

I'd call this "as designed", or, if we care enough, we could make it it customizable as others do.

**Comment by eddyashton** [comment]
@jerch Thanks for the context. That led me to a few interesting discussions around this, notably a [VTE bugzilla comment](https://bugzilla.gnome.org/show_bug.cgi?id=754596#c10) that clearly outlines the case _for_ this behaviour, and how these conventions affect [something like ncurses](https://unix.stackexchange.com/a/237374).

My instinct is that _not_ colouring to the end would be more natural for a few reasons: the terminal is usually displaying lines of text, where the user-model is that parts of that _text_ are coloured, whatever you do behind the scenes to scroll/render shouldn't affect me, you do it right when you resize, putting the onus to debug/work around this on apps that are deliberately fiddling with the terminal display+trying to colour whole lines seems acceptable. But I understand this is in opposition to a few decades of existing terminal convention.
