### ISSUE TITLE
Wrong debug configuration gets stopped

### ISSUE THREAD

**Issue by chrissyast** [microsoft/vscode#125924]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Run multiple debug configurations at the same time
2. Stop one of the running debug sessions by hovering over it within the "Call Stack" section and clicking the stop sign icon

Expected behaviour:
Chosen debug session ends

Actual behaviour:
A different debug session ends

I haven't been able to reproduce this consistently but it seems to be more likely to happen after sessions have been running for a while.

![stopping services](https://user-images.githubusercontent.com/31564153/121522617-33e4d900-c9ed-11eb-9a05-5e851a9b82c3.gif)

**Comment by isidorn** [comment]
Sounds like a potential duplicate of https://github.com/microsoft/vscode/issues/125327
If not, can you please provide reproducable steps?

**Comment by chrissyast** [comment]
@isidorn having had a chance to review, my issue doesn't happen if the correct config has focus so I'd say it is indeed a duplicate

**Comment by weinand** [comment]
@chrissyast thanks for your confirmation
