### ISSUE TITLE
1.57.0 (Linux): does not launch anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126027]
Increasing number of users report that VSCode is no longer launching on Linux, a regression from https://github.com/microsoft/vscode/commit/e2954beb4b0fccb7c034f1444e4b76c23fa6ae0b it seems.

**Workaround:** for existing users facing this, you can pass `--no-sandbox` to the startup or go back to `1.56.2`:
* Linux Deb [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/code_1.56.2-1620838498_amd64.deb)
* Linux RPM [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/code-1.56.2-1620838566.el8.x86_64.rpm)
* Linux Snap [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/code-stable-x64-1620839189.snap)

//cc @deepak1556

**Comment by alestor123** [comment]
open a pr on the issue

**Comment by sohancms** [comment]
after getting the upgrade vibrancy extension is not working. for resticted mode it's not working . Now what can i do ?
