### ISSUE TITLE
vscode v1.57 doesn't work with AltTab v6.21.2

### ISSUE THREAD

**Issue by rbajaj1997** [microsoft/vscode#126005]
Issue Type: <b>Bug</b>

The new update doesn't work with AltTab. It was working fine before the update. I downloaded v1.56 and it is still working fine there. Submitting this issue from the older version.

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 580f3fb2-5b98-4196-a937-6cc412fb03cd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Can you clarify what you mean?

**Comment by rbajaj1997** [comment]
@bpasero, [AltTab](https://alt-tab-macos.netlify.app/) helps us switch between different applications. So if I am on vscode and press `alt + tab`, I should be able to switch to a different application. 
After this update (v1.57), on pressing the key combination above, it's not working as expected. However it's still working on v1.56.

**Comment by bpasero** [comment]
I would think this is another Electron update regression on macOS, similar to https://github.com/microsoft/vscode/issues/126013

**Comment by vu-dinh-hung** [comment]
Same issue, switching to VS Code works but switching away doesn't work.

**Comment by deepak1556** [comment]
Thanks for the report, merging to https://github.com/microsoft/vscode/issues/126013
