### ISSUE TITLE
Repo root's .vscode files have no effect when subdirectories are opened

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#126080]
- VS Code Version: 1.57.0
- OS Version: Windows 10 version 21H1 build 19043.985

Steps to Reproduce:

Using https://github.com/Azure/azure-sdk-for-rust as an example:

1. In a repo root, create .vscode/settings.json with workplace setting like `"formatOnSave": true`.
2. Open a subdirectory like sdk/core in Code
3. Edit some code in a way that a formatter like `cargo fmt` won't like.
4. Save.

Expected: the file is formatted automatically.

Actual: the file is not formatted.

If I open the repo root this work as expected. If I create a .code-workspace file in the repo root formatting does not happen. Even if I add the .vscode folder to the .code-workspace file no formatting occurs.

To support monorepos, it would be great if VSCode - when opening or adding a folder - would look up the directory structure for a .vscode folder.

**Comment by heaths** [comment]
I searched for duplicates prior to opening this but didn't find one. @sandy081 do you have the dup bug ID handy so I can follow it?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/32693
