### ISSUE TITLE
`command+w` could not close vs code window on macos

### ISSUE THREAD

**Issue by maxwellzh** [microsoft/vscode#126021]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Darwin x64 20.5.0

Steps to Reproduce:

1. Open vscode
2. Using `command+w` to close all the tabs and the window.

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_57#_removed-cmdw-ctrlw-keybinding-to-close-window-when-no-editor-is-opened
