### ISSUE TITLE
Search tool is broken when excluding a folder from the search

### ISSUE THREAD

**Issue by RLThomaz** [microsoft/vscode#126003]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Ubuntu 18.04 (same issue on Docker Ubuntu 16.04 using Remote Development Containers).

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic snap
```

I believe this is a bug introduced in the newest version release (as I literally didn't change anything in my workspace besides upgrading VSCode).

Disclaimer: I'm not sure what's the source of this bug, but it doesn't seem to affect the new "Remote Repositories" extension, as I  tested it out to create an "anonymous" version for this ticket using this same repository.

Steps to Reproduce:

1. Create a multi-root workspace (I think this is related as the error cites one of my workspaces "/^Workspace/C++")
2. Search for anything using the Search tool (CTRL + SHIFT + F)
3. Add some exclusion criteria - the all should work but excluding other workspaces - e.g. "./Documentation"
4. Watch a "regular expression" error pop-up in the search bar citing one of the multi-root workspace folders.

![vscode_bug_exclude](https://user-images.githubusercontent.com/11475657/121643543-83e29f00-cac4-11eb-9dfe-8c0c1a46a1de.gif)

**Comment by roblourens** [comment]
Oops, regression from https://github.com/microsoft/vscode/issues/99512, if your workspace name has other regex characters in it (like `+` here)
