### ISSUE TITLE
When entering Chinese, the cursor position is between the input text, and the text is incomplete

### ISSUE THREAD

**Issue by jiangbo0216** [microsoft/vscode#126001]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: May 2021 (version 1.57)
- OS Version: macOs Big Sur

Steps to Reproduce:

1. lanuch vscode
2. make sure editor font setting is ‘’
3. When entering Chinese, the cursor position is between the input text, and the text is incomplete
4. code --disable-extensions no help and same in vscode insider
5. change font to other will be ok, eg ‘Menlo’

here is a gif for this

![Kapture 2021-06-11 at 14 37 00](https://user-images.githubusercontent.com/18640629/121642415-0ff3c700-cac3-11eb-98b7-0c106d935f74.gif)

**Comment by rebornix** [comment]
@jiangbo0216 may I ask what input method you are using?

**Comment by jiangbo0216** [comment]
> @jiangbo0216 may I ask what input method you are using?

![image](https://user-images.githubusercontent.com/18640629/122166346-0f38a780-ceac-11eb-8f3c-894c87614b5f.png)

简体中文 - 简体拼音

**Comment by jiangbo0216** [comment]
Is there any progress that can be repeated?
