### ISSUE TITLE
Node.js 16 breakpoints bind to the end of the block, not the line specified

### ISSUE THREAD

**Issue by kyrylkov** [microsoft/vscode#126008]
Issue Type: <b>Bug</b>

With Node.js 16 try to set a breakpoint on any line of an async function.  In multiple cases the breakpoint doesn't bind to the line but instead to the end of the block.

This is confirmed to happen in 1.55, 1.56 and 1.57 without any extensions installed.  This is also confirmed to haven only with Node.js 16.x.  Everything works fine with Node.js 15.x.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.48GB free)|
|Process Argv|--crash-reporter-id 4acc6120-99e9-4aab-bee8-564be7e04f5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.22
gitlens|eam|11.4.1
svelte-vscode|sve|105.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/1017
