### ISSUE TITLE
Output panel

### ISSUE THREAD

**Issue by mkumm079** [microsoft/vscode#126033]
Issue Type: <b>Bug</b>

The output panel keeps popping up whenever my work auto-saves and it is very annoying. This only seems to happen when I work in my javascript files and not my html files nor my css files for some reason.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.89GB free)|
|Process Argv|--crash-reporter-id eacb0fb1-e7a2-4d18-862d-2188f7052f1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
beautify|Hoo|1.5.0
fontawesome-autocomplete|Jan|1.1.2
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30311221
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by gjsjohnmurray** [comment]
Is it being caused by one of your extensions? Please use the Start Extension Bisect command to investigate.

**Comment by mkumm079** [comment]
Thank you, that seems to have helped my figure out the problem. It was one of my extensions, it would seem.
