### ISSUE TITLE
Anchor links in the Markdown Preview window are now case-sensitive, whereas they weren't in previous versions of VSCode.

### ISSUE THREAD

**Issue by ashelleyPurdue** [microsoft/vscode#126082]
Issue Type: <b>Bug</b>

As of version 1.57.0 of VSCode, anchor links in the Markdown Preview window have become case-sensitive, whereas they previously were not.

# To Reproduce:

1. Create a new Markdown file and paste this into it:
```markdown
# The Problem
In previous versions of VSCode, anchor links [did not care](#i-aM-a-hEAdeR)
what kind of casing you used; you could use any combination of capital/non-capital
letters, and the markdown preview window would still scroll to the header when
you clicked it.  This was useful, because it allowed you to have the link's
capitalization match the header's capitalization.

You were also able to substitute spaces with [%20](#i%20%am%20%20header), rather
than dashes.  That wasn't really useful, and it looked kind of ugly, but it
worked nonetheless.

Now, as of version 1.57.0, anchor links will only work if you use
[kebab-casing](#i-am-a-header) in the link.  This breaks any existing markdown
files that used other kinds of casing.

# I am a header
```

2. Click the "Open preview to the side" button, to open a markdown preview tab.

3. Click on the link titled "did not care".  The expected behavior is for the preview window to scroll down to the header titled "I am a header".  It does not.

4. Click on the link titled "%20".    The expected behavior is for the preview window to scroll down to the header titled "I am a header".  It does not.

5. Click on the link titled "kebab-casing".  This link works exactly as expected, scrolling you down to the "I am a header" header.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.41GB free)|
|Process Argv|E:\\source\\projects\\TDDPokemon --crash-reporter-id 8797c644-5036-4f84-b818-253500b861a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
shaderlabvscodefree|aml|1.2.8
spellright|ban|3.0.58
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.22
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|6.4.0
dotnet-test-explorer|for|0.7.5
papyrus-lang-vscode|joe|2.23.1
angular-essentials|joh|12.0.0
vscode-peacock|joh|3.9.1
docomment|k--|0.1.20
gml-support|lia|1.7.4
git-graph|mhu|1.30.0
csharp|ms-|1.23.12
remote-wsl|ms-|0.56.5
cpptools|ms-|1.4.1
hexeditor|ms-|1.7.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.4.1
inline-html|pus|0.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
rewrap|stk|1.14.0
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|11.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehovct:30309550
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by ashelleyPurdue** [comment]
Nope, not a duplicate.  The linked issue is specific to notebooks, and doesn't have anything to do with case-sensitivity.

**Comment by michael-hawker** [comment]
Also seems like it won't link to other named HTML anchors like:

```
[My link to header](#generators)

## <a name="generators"></a> Some Other Long Header Name
```

In 1.58.2

**Comment by Lemmingh** [comment]
77ff6eb03bcfb11d3bad26346f0b5ed593cb2a99 (#124400) modified the `addLinkNormalizer()` method.

But I think **the old behavior was actually a bug**. VS Code should not overwrite the default logic here, that's, being **case-sensitive is correct**.

Applying case conversion to fragment is wrong, according to the URI standard (RFC 3986) Section 3.5, 6.2.

The fragment must exactly match ("equal") the `id` when scrolling can be performed, according to the HTML Standard Section 3.2, 7.11.

**Comment by mjbvz** [comment]
Thanks for the detailed writeup @Lemmingh! Based on the lack of much additional feedback on this issue since it was opened, I'm going to close this for now but we'd take PRs that want to revisit this
