### ISSUE TITLE
Microsoft Team needs to Clean Up The VS-Code Extensions Store Please...!!

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#126096]
When either on the website or within VS-Code looking for extensions, a person finds themselves immersed within
thousands of deprecated rotting extensions that are either outdated, no longer maintained or completely deprecated by the author.
Or if an author stopped development/maintenance because the extension conflicts with VS-Code itself or other extensions etc etc.
The store tends to build up a massive amounts of junk that hinders users from getting actual extensions that would benefit them.
In particularly with new users along with everyone else in the ecosystem. 

Why do these old outdated, deprecated and useless extensions still exist in the extensions store ?
Its time for the entire **Microsoft Team** to go through all the extensions and start cleaning out the closet.
And also setting new rules for the extensions store, forcing authors of extensions to completely remove their extension,
if its been posted that their extension is either no longer maintained, deprecated, outdated or the feature has been implemented within vs-code by Microsoft.
Hundreds and hundreds of extensions should no longer remain in the store as it massively clogs the store with useless outdated extensions
that either are deprecated, maintained, outdated, feature been implemented within vs-code or no longer in use in 2021 going on 2022.

I also find that a lot of extensions features & ideas where already implemented within the official release of VS-Code by Microsoft,
and therefore the extension itself should no longer remain within the store clogging up the store with useless items that is rotting away within the store.  Basically there are too many cob-webs in the store and Microsoft seriously needs to clean the closet.

Thanks for reading...   :)

**Comment by sandy081** [comment]
We clean up deprecated / outdated extensions on restart of VS Code. Can you please restart VS Code and check?

**Comment by RobFosterNYC** [comment]
Hi sandy,   I am talking about the store itself. Not what's installed. 
even though it is nice :) to know that what's installed you clean up...
But I am talking about the store itself.

**Comment by sandy081** [comment]
I am guessing by Store you mean the Marketplace that hosts extensions? If so please file issue against - https://github.com/microsoft/vsmarketplace
