### ISSUE TITLE
Test: Integration of vscode-tslint with a gulp

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12604]
Microsoft/vscode-tslint#89

- [x] Any platform @sandy081 

Complexity - 2

### Setup
- install the vscode-tslint extension and its prereqs `tslint` and `typescript`
- Follow the documentation in the [README](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) to setup a task runner and a vscode task.

### Test
- Run the task runner to lint the entire project and then fix the warnings. 
  - Verify that you see no duplicate warnings in the problems view

**Comment by sandy081** [comment]
Ref : https://github.com/Microsoft/vscode-tslint/issues/100
