### ISSUE TITLE
TrustedWorkspace is always asking when using just a document

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#126070]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. Install .NET Interactive notebook extension
2. Open a new vscode window without opening a workspace or folder
3. using command palette ask to create a new untitled notebook
4. Workspace is not trusted

**Comment by sbatten** [comment]
By default, empty windows are trusted so I am not able to reproduce this issue without modifying settings. Can you clarify your repro. Perhaps with a screen shot or gif?

**Comment by colombod** [comment]
Sorry is working correctly.  Closing this issue
