### ISSUE TITLE
Javascript in html is executed twice in notebooks

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#126074]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58-insiders
- OS Version:

generating html that contains script tag gets the javascript executed twice

Steps to Reproduce:

1. Create a .NET Interactive notebook
2. Create a javascript cells
3. Write code `console.log(1);`
4. evaluate the cell
5. the output is printed twice

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/8b674fee2c51db9bee33581e39d5e3b8f8d0ea53/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L601-L603

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/commit/56c9243bb298fb75002488c19588a6bb14ba3dfc
