### ISSUE TITLE
Git Bash is not visible when try to select default terminal profile

### ISSUE THREAD

**Issue by rafid149** [microsoft/vscode#126023]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

After updating VsCode I couldn't see git bash when I tried to select the default terminal profile.
This is my setting.json

<a href='https://postimg.cc/PLww4Gcr' target='_blank'><img src='https://i.postimg.cc/k5jv7qv8/Vs-Code-Settings.png' border='0' alt='Vs-Code-Settings'/></a><br />

After that, I thought bc of some reasons the `Git Bash` is not counted as a profile.
So I tried to create a new profile by pressing `ctrl+shift+p` then `terminal: select default profile` then I pressed configure button of Powershell. And after that when I try to type Git Bash they said I already have a profile with `Git Bash` name. So I went to my settings.json and I commented the git bash part. But when I tried again to configure PowerShell and type `Git Bash` they again said `A terminal profile already exists with that name`!!!
I can't take the screenshot because when clicking another place the command palette disappears
After that, I deleted the Code folder from the `C:\Users\User\AppData\Roaming\Code`
And I opened VsCode again, But it is still saying I don't have git bash in terminal profile and when i click configure buttons of the profile or try to add it from settings.json they say `A terminal profile already exists with that name`

Oh, yes when I change settings.json into this code ---

<a href='https://postimg.cc/3yqWztsf' target='_blank'><img src='https://i.postimg.cc/bJybDM3P/Vs-Code-Settings-Weird.png' border='0' alt='Vs-Code-Settings-Weird'/></a><br />

It works fine. I can select bash as my default profile!!!!!

It didn't happen in the previous version so I think it is happening because of the Latest version glitch. (Btw I just signed up in Github) So maybe I broke some rules. Sorry if I break :disappointed:

**Comment by phamgiahung1368** [comment]
Same issue after upgrade to the new version (vscode 1.57.0)

**Comment by monk-time** [comment]
I had the same issue after updating to 1.56.0, VSCode couldn't see the installed Git Bash on W7. I fixed it by hardcoding a new terminal profile with an explicit path to Git Bash (this might be related to me having a non-default path to my Git Bash install). 

And after updating to 1.57.0 Git Bash terminal profile disappeared again. I managed to fix that by renaming "Git Bash" profile to "Git_Bash".

**Comment by rafid149** [comment]
But after deleting cache when I try to type `terminal.integrated.defaultProfile.windows` and then Git_Bash, I couldn't see Git_Bash in suggestions. Also, there was a yellow underline on `Git_Bash`. After that, I deleted the `Git_Bash` word And saved it, and tried to type Git_Bash, there was `Git_Bash` in the suggestions. After that, there was no yellow underline on the `Git_Bash` word. Its also a settings.json bug I think.

**Comment by DGCK81LNN** [comment]
I have the same issue. Existing issues and [an answer on stackoverflow](https://stackoverflow.com/a/68140594/16999608) seem to suggest that this problem occurs only when your Git Bash is **not** installed at the standard location (`C:\Program Files\Git\bin\bash.exe`) **and** the profile is named **exactly** `"Git Bash"`.

**Comment by meganrogge** [comment]
We will improve the info provided on hover of the `source` property.

**Comment by arwhyte** [comment]
Moving my report from #158627 to here:

- VS Code Version: 1.70.2
- OS Version: Windows 11 Home version 21H2 OS build 22000.856 Windows Feature Experience Pack 1000.22000.856.0

Steps to Reproduce:

1. Install gitforwindows (git version 2.37.2.windows.2)
2. CTL-SHIFT-P to activate the control palette
3. Select Terminal: Select Default Profile
4. Git Bash is not listed in dropdown
5. File > Preferences > Settings > terminal.integrated.profile.windows
6. Git Bash "source" is listed but is ignored.

```json
"Git Bash": {
    "source": "Git Bash"
}
```

Issue discussed on stackoverflow: https://stackoverflow.com/questions/68068359/gitbash-not-showing-up-as-a-terminal-option-in-visual-studio-code

Workaround:

I replaced the key-value pair above with the following key-value pair (note that the path could vary if a different git for windows install location was chosen):

```json
"GitBash": {
    "path": [
        "C:\\Program Files (x86)\\Git\\bin\\bash.exe"
    ],
    "args": [],
    "icon": "terminal-bash"
}
```

Restarted VS Code, activated the command palette, selected Terminal: Select Default Profile and Git Bash appeared as a dropdown option.  Selected Git Bash as the default terminal.  Ran python file.  Terminal pane opened Git Bash and code executed successfully.

Context: I teach at the University of Michigan School of Information and we use VS Code to introduce students to programming fundamentals.  For new students this is a non-trivial workaround. Class starts next week. :)

**Comment by Tyriar** [comment]
Thanks for the follow up @arwhyte, we don't look in `%PROGRAMFILES(X86)%` currently but should:

https://github.com/microsoft/vscode/blob/e55863c5c1fc4515bd99e9cd4fb415788000a8b1/src/vs/platform/terminal/node/terminalProfiles.ts#L206-L213

**Comment by arwhyte** [comment]
You are welcome @Tyriar.  I was a bit surprised that `C:\\Program Files (x86)\\Git\\bin\\bash.exe` would be considered a non-standard git for windows install location as is implied by the additional language added in #158805.

Anyways, enjoy teaching Python here at the University of Michigan using VS Code.  Go Blue, Go VS Code.
