### ISSUE TITLE
Tab order with dependsOn not consistent

### ISSUE THREAD

**Issue by capc0** [microsoft/vscode#126004]
Issue Type: <b>Bug</b>

Starting a task defined in the `tasks.json` that has e.g. 3 depending tasks (defined in `dependsOn`) will create the 3 depending tasks terminals in a random order.

This used to be consistent/match with the order of the definition before the May Update.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.66GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Simon/Documents/Development/api --crash-reporter-id 5d36760e-78a0-4b30-852c-89e284a8e7d8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by alexr00** [comment]
`dependsOn` tasks have always been all fired off at the "same" time, meaning that actual order is arbitrary. If you want a specific order, you can set `"dependsOrder": "sequence"` on your task.

**Comment by capc0** [comment]
Thanks for the quick reply. The `sequence` option does not fit our needs, because all tasks are running in the background (will never finish) and should start at the same time.

To be clear: I only want the terminals to have the correct order (as it used to be in the previous version).  Otherwise it is sometimes confusing if the tasks are not at the same position every time they are executed.

![image](https://user-images.githubusercontent.com/27284008/121651621-1a9a6600-ca9b-11eb-99ad-e776201e9a23.png)
