### ISSUE TITLE
Most of the extensions that I daily use stopped working (today)

### ISSUE THREAD

**Issue by RVFET** [microsoft/vscode#126018]
Issue Type: <b>Bug</b>

I did not do anything special than my everyday use.
Just opened visual studio code as usual and worked for a while. Then "most" of the extensions were no longer working. First I noticed "Beautify" don't formats and googled it out, basically found nothing.
Also today visual studio was updated and its kind of suspicious to this two happen same day.
I tried disabling the extensions that Im not sure about but it didn't help.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.62GB free)|
|Process Argv|--crash-reporter-id 70f8157b-03d0-44f7-8c6e-48b887e71ec1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
increment-selection|alb|0.2.0
html-end-tag-labels|ant|0.6.0
regex-copy-or-cut|ara|1.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|1.10.2
fold-unfold-all-icone|Fer|0.0.3
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
selectline-statusbar|tom|0.0.2
highlight-matching-tag|vin|0.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by sandy081** [comment]
Can you please check if extensions those are not working are enabled or not? Please go to extensions view and provide a screenshot of them? Please check if there are any errors seen in the developer tools console.

**Comment by zihengCat** [comment]
https://github.com/microsoft/vscode/issues/125989
Did you see the `Extension host terminated unexpectedly` pop-up dialog ?

**Comment by RVFET** [comment]
> 
> 
> #125989
> Did you see the `Extension host terminated unexpectedly` pop-up dialog ?

No I didn't

**Comment by RVFET** [comment]
> 
> 
> Can you please check if extensions those are not working are enabled or not? Please go to extensions view and provide a screenshot of them? Please check if there are any errors seen in the developer tools console.

Its working now but didn't worked at the time that I faced with the issue. I still don't know what did happen, also I restarted my computer before opening issue but it didn't help. Some random stuff happening to vscode lately
