### ISSUE TITLE
Value cannot be null. (Parameter 'provider') Could not connect to debug target

### ISSUE THREAD

**Issue by deepaksahu-perficient** [microsoft/vscode#126078]
I had developed a Service bus trigger app in node.js which was running fine but after some days as i opened it, it throws error message 

"Value cannot be null. (Parameter 'provider').
Could not connect to debug target at http://localhost:9229: Promise was canceled. "

I reinstalled everything still i am getting error. 
Below are my versions details:
Visual Studio : 1.56.2 (user setup) 
Node Js : 14.16.0 
Azure function : 1.4.0 
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit) 
Function Runtime Version: 3.0.15828.0
.NET Core 3.1 SDK (v3.1.410) - Windows x64 Installer
[vscode-debugadapter-84776df2.json.gz](https://github.com/microsoft/vscode/files/6640028/vscode-debugadapter-84776df2.json.gz)

**Comment by connor4312** [comment]
I'm not sure what the "provider" error you see is, and it's not present in the logs. What I do see is a connection refused trying to hit the debug port 127.0.0.1:9229, which means there's no process listening on that port. If you think this is not the case or something else is going on, please share reproduction steps and I can dig into it more.
