### ISSUE TITLE
Suggest preview doesn't show for lowercase where the match was uppercase

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126076]
Related: https://github.com/microsoft/vscode/issues/126075

This only happens when the match was an uppercase and there is no lower case letter:

![recording (16)](https://user-images.githubusercontent.com/2193314/121722000-bc20b800-ca99-11eb-89a3-3662f496435f.gif)

**Comment by hediet** [comment]
The default mode of suggestion previews is node "prefix" again, which does not has this issue.

The "subwordDiff" mode still has this problem. However, it is unclear what should happen if a character of the suggestion abbreviation is matched with a character in the suggestion name that differs in casing: Ghost text is only inserted and cannot change existing text (such as making an existing text upper/lower case).

**Comment by hediet** [comment]
This is only relevant for the mode `"editor.suggest.previewMode": "subword",`.
However, the default is `subwordSmart`, which does not show any ghost text before the cursor.

Since it is not trivial to fix this, I'd suggest to wait until there is more demand for this feature/bug-fix.
