### ISSUE TITLE
Executing indicator on collapsed notebook cells

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#126091]
Issue Type: <b>Feature Request</b>

Collapsing cells should save time but provide the same execution information.

I collapsed massive queries that take seconds to scroll through (and a few minutes to run). Collapsed cell don't show the execution progress spinner, stop button or the time; and I already struggle to tell if and how far a notebook executed.

VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:12:17.675Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

**Comment by roblourens** [comment]
Good point. I think this could be considered with the general issue of telling where execution is https://github.com/microsoft/vscode/issues/124193
