### ISSUE TITLE
The terminal process "zsh '-l'" failed to launch (exit code: 1).

### ISSUE THREAD

**Issue by a1tern4tive** [microsoft/vscode#126017]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.57.0 Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
- OS Version: macOS Big Sur 11.3.1

Hi,

After today's update I get an error when I try to open Integrated Terminal (**zsh**)

> execvp(3) failed.: Permission denied

> The terminal process "zsh '-l'" failed to launch (exit code: 1).

Screenshot:
![Screenshot 2021-06-11 at 10 21 31](https://user-images.githubusercontent.com/12602510/121655443-e88b0300-ca9e-11eb-88ab-6f79a81a22da.jpg)

_settings.json_:
`"terminal.integrated.defaultProfile.osx": "zsh",`
`"terminal.integrated.cwd": "${workspaceFolder}",`
`"terminal.integrated.cursorStyle": "line",`
`"terminal.integrated.cursorBlinking": true,`
`"terminal.integrated.fontSize": 12,`
`"terminal.integrated.fontWeightBold": "600",`
`"terminal.integrated.cursorWidth": 2,`
`"terminal.integrated.tabs.location": "left",`

Tried to remove my settings for this - same error.

**Bash** works.

Please help :-)
Thanks

**Comment by Xcalizorz** [comment]
I have the exact same issue and same setup.

**Comment by meganrogge** [comment]
I can't reproduce this. It seems like a permissions issue maybe. @a1tern4tive what happens if in the bash terminal you type "zsh -l"?

**Comment by a1tern4tive** [comment]
> I can't reproduce this. It seems like a permissions issue maybe. @a1tern4tive what happens if in the bash terminal you type "zsh -l"?

It just normally changes to _**zsh**_

**Comment by meganrogge** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by meganrogge** [comment]
Also, when you run `zsh` in an external terminal, what happens?

**Comment by a1tern4tive** [comment]
Nah, no anti-virus.

That just worked perfectly before the update.

In external terminal works good too.

**Comment by Tyriar** [comment]
Can you run `ls -la $(which zsh)`?

**Comment by Tyriar** [comment]
@Xcalizorz are you also using homebrew?

**Comment by Xcalizorz** [comment]
> @Xcalizorz are you also using homebrew?

@Tyriar I tried with VS Code from Homebrew and also the version downloaded on the VS Code homepage.

Both show me the same error since yesterday after the update.

**Comment by Xcalizorz** [comment]
It works again after removing the homebrew version of zsh.

```shell
brew uninstall zsh
```

Since Mac already provides a zsh installation in `/bin/zsh` everything works as before for now.

**Comment by a1tern4tive** [comment]
Thanks to everybody!

**Comment by rattrayalex** [comment]
I ran into this as well, and `brew uninstall zsh` succeeded as a workaround. 

However, I don't think VS Code should require a non-homebrew zsh install; there may be reasons that the homebrew version is preferred (eg; a later version may include bugfixes or features).

Can this issue be reopened?

**Comment by kipz** [comment]
On my Ubuntu system, this solution doesn't work of course. I'm using `bash` from `apt`, and AFAICT, the only changes has been the VSCode update - which is coming in via `snap` - I suspect it's related to that in my case?

**Comment by kipz** [comment]
FWIW - I've installed the latest `deb` manually and the problem persists:

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```

**Comment by kipz** [comment]
FWIW - adding the following setting fixed things for me:

```json
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/bin/bash"
        },

    },
```

Which by default just points to `bash` - without a path.
