### ISSUE TITLE
remote ssh: wrap line is broken after some control chars.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#126037]
1. connect to remote computer by remote ssh.
2. type some letters (see video). Line wrap is working.
3. cat test.log
4. see that output of 
"[KERNEL PANIC]:  assertion "end > base" failed: file "/nvm/work/prod_analyzeqt/build/toolchain/kernel/kos/image/i686_kos/src/os/core/hal/x86/mmu.c", line 438, function: HalCreatePageTablesEx"

was sripped.
5. type some leeeters (see video again). Line wrapping is NOT working anymore.  new line begins at the same Y position as previous, ans re-write existing letters

remote computer:
Ubuntu 20.04 (x86_64)

local computer:
Windows 10 (64.bit) 20H2
vscode: 
Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
remote-ssh: 0.65.4

![remote_ssh_wrapline](https://user-images.githubusercontent.com/801951/119940090-63c8c100-bf97-11eb-9f5b-986f2e877ab9.gif)

 [test.log](https://github.com/microsoft/vscode-remote-release/files/6558769/test.log)

**Comment by dibalavs** [comment]
[console.log](https://github.com/microsoft/vscode/files/6642850/console.log)

attached.

**Comment by dibalavs** [comment]
Hello, 
I checked on 
**Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043**

Issue exists.
reproduces only on remote ssh. 
on wsl - absent.

**Comment by Tyriar** [comment]
There are indeed sequences in the file and these are what's causing the buffer to get stripped since `esc 2 J` is the instructed to clear the whole buffer:

![image](https://user-images.githubusercontent.com/2193314/136963581-7136450f-df0c-4696-8531-a54b63dbb1c6.png)

`esc ? 7 l` will disable auto-wrap mode, that's the cause of the latter point.
