### ISSUE TITLE
Test: assist user in setting up eslint

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12601]
See ESLint extension (see https://github.com/Microsoft/vscode-eslint)

- [x] any OS - @octref 

Complexity: 2

Setup:

- Install eslint-extension@latest
- create a new workspace and change dir into it
- npm install eslint
- open workspace

Test: 

- create JS file with an unused variable.
- no ESLint error and no window message should appear.
- the ESLint output channel should contain a message like:
```
[Warn  - 3:14:29 PM] No ESLint configuration (e.g .eslintrc) found for file: extension.js
File will not be validated. Consider running the 'Create .eslintrc.json file' command.
```
- Run F1 > 'Create .eslintrc.json file'
- Ensure that the JS file is validated and a warning is shown for the unused var.

**Comment by octref** [comment]
Other than #12808 works great!
