### ISSUE TITLE
Error: Could not find renderer for new markdown cells

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126069]
The way I reproduced this issue is 

* create a code cell
* change it markdown
* double click to edit
* escape
* the markdown cell is blank

```
notebookWebviewPreloads.js:3 Uncaught (in promise) Error: Could not find renderer
    at Object.render (notebookWebviewPreloads.js:3)
    at K.updateContentAndRender (notebookWebviewPreloads.js:3)
    at new K (notebookWebviewPreloads.js:3)
    at Object.createMarkupCell (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
    at Array.map (<anonymous>)
    at Object.ensureMarkupCells (notebookWebviewPreloads.js:3)
    at notebookWebviewPreloads.js:3
```

**Comment by mjbvz** [comment]
I can't repo this follow those steps in a new GitHub issues notebook. What type of notebooks were you using? Any more details on how to reproduce this?

**Comment by rebornix** [comment]
@mjbvz I'm seeing this constantly in OSS. Do you convert the code cell to markdown cell? If you use Jupyter, you can press `m` when focusing on the cell container, which will convert the cell to markdown. Based on my debugging, we sent a request the webview but the cell id doesn't exist in the view model in the webview, I wonder if the view model is out of date in this case.

**Comment by mjbvz** [comment]
Thanks. Yes using `m` causes the issue for me. I wasn't able to see this when manually changing the language mode

**Comment by mjbvz** [comment]
My work to support generic markup rendering caused this. We also need to change the language mode of the cell when covering it to markup (previously this command would end up creating a markup cell with the language mode of `python`)

**Comment by mjbvz** [comment]
I don't think this happens in 1.57 so should be ok just fixing in insiders
