### ISSUE TITLE
Tasks shell using default terminal arguments

### ISSUE THREAD

**Issue by rmyamaguchi** [microsoft/vscode#126052]
Issue Type: <b>Bug</b>

1. Select a default terminal which is called with arguments (e.g. Git bash `--login`)
2. Create a task in tasks.json using another shell as option (e.g. Powershell)
3. Execute the task (to see Powershelll being called with `--login` as first argument)

Expected results would be tasks running the chosen shell without the default terminal arguments.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.43GB free)|
|Process Argv|--crash-reporter-id 288f6a89-909b-47e4-8462-ff25114ae6e8 --crash-reporter-id 288f6a89-909b-47e4-8462-ff25114ae6e8|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
@rmyamaguchi can you share the setting you set for step 1 and the task that you used for step 2?

**Comment by rmyamaguchi** [comment]
Sorry, I forgot this:

1. Setting: `Terminal > Integrated > Default Profile: Windows` is set to Git Bash.
![image](https://user-images.githubusercontent.com/17730885/123979652-4d979180-d997-11eb-952a-397efb2db594.png)
Neither `Terminal > Integrated > Shell: Windows` nor `Terminal > Integrated > Shell Args: Windows` are set:

2. In the example, I mentioned powershell. My current task uses WSL, but the problem happens anyways:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "mkdir -p ${input:dir} && cd ${input:dir} && cmake .. && cmake --build . && ./main",
            "args": [],
            "problemMatcher": {
               "pattern": {
                    "regexp": "^(\\/mnt\\/c)(.*):(\\d+):(\\d+):\\s+(warning|.*error):\\s+(.*)$",
                    "file": 2,
                    "line": 3,
                    "column": 4,
                    "severity": 5,
                    "message": 6
                },
                "fileLocation": ["relative", "C:"]
            },
            "group": {
               "kind": "build",
               "isDefault": true
            },
            "options": {
               "cwd": "${workspaceFolder}",
               "shell": {
                  "executable": "C://Windows//System32//wsl.exe"
               }
            }
        }
    ],
    "inputs": [
        {
            "type": "promptString",
            "id": "dir",
            "description": "Build directory name",
            "default": "build"
        }
    ]
}
```

**Comment by alexr00** [comment]
@rmyamaguchi thank you for the additional details!
