### ISSUE TITLE
Out of memory allocating some bytes

### ISSUE THREAD

**Issue by ArjunSeeker** [microsoft/vscode#126079]
I'm compiling a simple code in c++, the code is to print the string "hello" on the screen but the code is not getting compiled rather it is showing the memory issues. Everything was perfectly working till yesterday. 
My laptop has a lot of free space available and it has 4GB of ram.
Please give the solution for this as soon as possible.
Thanks in advance.
![image](https://user-images.githubusercontent.com/65021030/121727112-19078700-cb09-11eb-8f08-32dcc078d0bd.png)

**Comment by sandy081** [comment]
Please file the issue against the c++ extension for initial inspection - https://github.com/Microsoft/vscode-cpptools/issues
