### ISSUE TITLE
VSCode wrongfully says I do not have permission to send a push request

### ISSUE THREAD

**Issue by XFaonAE** [microsoft/vscode#126094]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Create a brand new GitHub account
2. login with GitHub in VSCode
3. Clone a repository
4. Make changes and try to push
5. VSCode says permission denied

**Comment by XfaonAE** [comment]
PS: WebStorm doesn't seem to be having any issues with this at all.  Note: running git push in VSCode terminal also says permission denied.

**Comment by lramos15** [comment]
@XFaonAE If running in the VS Code terminal also says permission denied it's unlikely a problem with VS Code and more to do with your local git machine config. Webstorm may set up things differently and not use your local config to avoid these issues.
