### ISSUE TITLE
No way of spliting terminal

### ISSUE THREAD

**Issue by SebastianK1999** [microsoft/vscode#126081]
Issue Type: <b>Bug</b>

When you have one terminal, you have no way of spliting it. In order to achive it, you need to open a new second terminal, then the temilnal list pops up. At first, you may think you still can't split, but it's hidden for some reason. You need to hover over one of terminal on the list, and only then you can split. Of coure the split creates third terminal, while the second one is unnecessary. Please, just bring back the old layout, the list may look some how "cool" but it takes too mutch space and in my opinon i'ts kind of unintuitive. Old layout wasn't bad, it looked good, it was easy to use.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.10GB free)|
|Process Argv|D:\\Studia\\SysWbud\\arm --crash-reporter-id ebf6eb1c-b85e-43f6-be6d-f3fe39f265ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
bracket-pair-colorizer|Coe|1.0.61
arm|dan|1.5.1
code-runner|for|0.11.4
reg|ion|1.0.3
bash-ide-vscode|mad|1.11.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.13.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
remote-containers|ms-|0.183.0
remote-wsl|ms-|0.56.4
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
powershell|ms-|2021.5.1
material-icon-theme|PKi|4.7.0
avr-support|roc|0.0.1
markdown-preview-enhanced|shd|0.5.21
cpp-compile|tch|0.0.2
vscode-make|tec|1.0.2
cmake|twx|0.0.17
makefile-creator|zen|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30307505
vscorehovct:30309550
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by lazyoracle** [comment]
Clicking on the drop-down arrow next to the `+` for new terminal tab lets you split a terminal tab without the need for opening a new one in between.
## Action
![image](https://user-images.githubusercontent.com/11018951/121735912-6806e980-cb14-11eb-8461-84f63fc6dae0.png)

## Result
![image](https://user-images.githubusercontent.com/11018951/121735959-7a812300-cb14-11eb-924d-4cefa510d09d.png)

That said, it is indeed extremely annoying to not have a single click to split the current terminal and it is a much desired feature that needs to be brought back. Related to #126032 (and now closed #126086).

**Comment by lukepighetti** [comment]
<img width="523" alt="Screen Shot 2021-06-11 at 5 28 41 PM" src="https://user-images.githubusercontent.com/666539/121750524-8bad3e00-cada-11eb-9d76-70737cf15478.png">

Can someone please tell the design team to stop hiding commonly used tools under collapsed buttons. It's starting to get kind of ridiculous.

**Comment by misolori** [comment]
You can right-click on the terminal item to bring up the additional actions:

<img width="212" alt="CleanShot 2021-06-11 at 16 22 45@2x" src="https://user-images.githubusercontent.com/35271042/121757114-53edc880-cad1-11eb-8d83-2275320dfb11.png">

Please see https://github.com/microsoft/vscode/issues/126032 for bringing back the split action

**Comment by meganrogge** [comment]
Please see the many ways we support splitting the terminal https://code.visualstudio.com/docs/editor/integrated-terminal#_grouping

**Comment by Tyriar** [comment]
Also alt+click on the + will split it, we'll likely bring the old one back in #126032.

If you preferred the old layout we're supporting it as well, it's just not the default. You can switch off terminal tabs in settings. If you switch it back everything will be as it was before.

**Comment by lukepighetti** [comment]
Why not give us a list of new features we can try in the welcome tab? I just ignore it and close it, but if it had cool things for me to try out then I would pay more attention to it. I would much prefer that over just ninja swapping features on next release.

**Comment by Tyriar** [comment]
@lukepighetti that's what the release notes are for which show up after an update: https://code.visualstudio.com/updates/v1_57. In the previous version we did mention you can try it out before making it the default, and we had a month of time to gather feedback and polish. This feedback/decision just came in late 🤷‍♂️ 

We are also looking into adding showing what's new in core/extensions via the new welcome page fwiw.
