### ISSUE TITLE
Restarting for update messed up settings.json

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#126038]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.57.0
- OS Version: macOS 11.2.2

I selected "Restart to Update", VSCode restarted, and immediately complained that my settings were invalid. Open the settings as JSON showed why:

![Screen Shot 2021-06-11 at 13 52 16](https://user-images.githubusercontent.com/50314/121682313-f2eed200-ca89-11eb-906e-43fb90896e08.jpg)

Obviously I have no idea what happened. Maybe a plugin, maybe VSCode. I bet two pieces of code were rewriting the settings at the time, which should of course be guarded against.

* Invalid settings:
[settings.json.zip](https://github.com/microsoft/vscode/files/6638125/settings.json.zip)
* Original settings: 
[settings.json.zip](https://github.com/microsoft/vscode/files/6638133/settings.json.zip)

**Comment by lazyoracle** [comment]
Related to #125970
