### ISSUE TITLE
Full Screen on MacOs

### ISSUE THREAD

**Issue by AndreaMolinari** [microsoft/vscode#126006]
Issue Type: <b>Bug</b>

While in full screen mode, pressing cmd + maiusc + n will result in multiple macos virtual desktops instead of the usual tab view.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 8, 6|
|Memory (System)|16.00GB (3.25GB free)|
|Process Argv|--crash-reporter-id 77b993e7-e470-46ff-813b-eb747c216c46|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-nginx-conf|ahm|0.1.3
laravel-extra-intellisense|ami|0.6.1
ng-template|Ang|12.0.5
swagger-viewer|Arj|3.0.1
touch-bar-display|bla|1.5.0
vscode-intelephense-client|bme|1.7.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.16
gitlens|eam|11.4.1
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.6
vscode-mysql|for|0.4.0
mysql-syntax|jak|1.3.1
vscode-gutter-preview|kis|0.27.1
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
easy-less|mrc|1.7.3
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.13.0
vscode-language-pack-it|MS-|1.57.1
csharp|ms-|1.23.12
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4360
vscode-react-native|msj|1.5.1
nativescript|Nat|0.12.3
indent-rainbow|ode|7.5.0
laravel5-snippets|one|1.12.0
material-icon-theme|PKi|4.7.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
laravel-artisan|rya|0.0.27
vscode-scss-formatter|sib|2.2.1
vscodeintellicode|Vis|1.2.14
vscode-conventional-commits|viv|1.21.0
vscode-icons|vsc|11.4.0
better-align|wwm|1.1.6

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30311220
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by bpasero** [comment]
Likely https://github.com/microsoft/vscode/issues/126013

**Comment by deepak1556** [comment]
Do you have `"window.nativeTabs": true` ?

**Comment by deepak1556** [comment]
I was able to repro with native tabs, merging to https://github.com/microsoft/vscode/issues/126016. Let me know if you are not using native tabs.
