### ISSUE TITLE
Test: Align functionality of node-debugger and chrome debugger

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12600]
Test for Microsoft/vscode-node-cdp-debug#7

**Comment by roblourens** [comment]
Complexity: 4

See notes in the [release notes](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#experimental-nodejs-v63-debugger) for an overview, especially the note about Windows support.

See [this bug](https://github.com/Microsoft/vscode-node-debug2/issues/7) for an overview of what's implemented.

Most existing issues are filed in [vscode-chrome-debug-core](https://github.com/microsoft/vscode-chrome-debug-core/issues), node-specific ones are in [vscode-node-debug2](https://github.com/Microsoft/vscode-node-debug2/issues).

- [ ] - OSX
- [ ] - Windows
- [ ] - Linux

There are a million scenarios we need to support, so the most valuable thing you can do is grab any random Node project that you might have debugged with VS Code in the past, change "type" to "node2", and see what happens. If anything happens that isn't the same as "node", is it obvious to figure out what's wrong?

More specific things to try, don't need to do every single one:
* Try some things that are checked off at https://github.com/Microsoft/vscode-node-debug2/issues/7
* Attach config with a running process (start with `--inspect=9229`)
* Ensure it kills the process when terminating a launch config, but not an attach
* Set breakpoints before launching, and ensure they bind
  * In the main script, and in scripts that are loaded later
* Look in the variables pane at different types and compare it to what you'd expect
* Test very large arrays and other stress cases
* Test with and without sourcemaps
