### ISSUE TITLE
Output context menu is partially covered by insert toolbar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126087]
Issue Type: <b>Bug</b>

It makes clicking the "Switch Mimetype" action really hard

![image](https://user-images.githubusercontent.com/876920/121735670-4aea0080-caab-11eb-92e0-1c1f0c743d45.png)

VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:14:11.473Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (6.49GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
The original fix caused the text output cover the insert toolbar

![image](https://user-images.githubusercontent.com/876920/127243045-a2c2d213-2201-44d2-9a3d-aab627cae809.png)

**Comment by roblourens** [comment]
I don't see it, thanks though

**Comment by rzhao271** [comment]
I'm still getting blocked a bit by the insert toolbar, such as if I try clicking on the item from the top of the letter "C".

**Comment by rebornix** [comment]
@rzhao271 can you share a screenshot?

**Comment by rzhao271** [comment]
I am seeing the opposite issue now, where I'm unable to figure out how to add a new cell, unless that's been moved to the code cell's overflow menu?

![Screenshot showing the issue is fixed but some buttons seem to have gone missing](https://user-images.githubusercontent.com/7199958/127579548-bc943304-5e8d-4e76-bb70-14a1e3f89595.PNG)

**Comment by roblourens** [comment]
You add a cell with the menu in Peng's screenshot. Maybe you can call me to work through this and figure out if there's a new issue

**Comment by roblourens** [comment]
You add a cell with the menu in Peng's screenshot. Maybe you can call me to work through this and figure out if there's a new issue

**Comment by roblourens** [comment]
Seems like @rzhao271 saw the original issue regress so I'll look at it next month

**Comment by DonJayamanne** [comment]
No longer able to repro.
