### ISSUE TITLE
show a warning dialog when delete file from vscode

### ISSUE THREAD

**Issue by wsytlzdh** [microsoft/vscode#126000]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.57.0 (system setup)
提交: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
日期: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. delete a files
2. show warning

**Comment by wsytlzdh** [comment]
![image](https://user-images.githubusercontent.com/54626202/121653088-e771ca00-cace-11eb-83c7-f1bbbb3476c5.png)

**Comment by isidorn** [comment]
As designed
You can control via the following settings:
 `"explorer.confirmDelete": false`
