### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Vivek-K-Sharma-2020** [microsoft/vscode#126059]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by Vivek-K-Sharma-2020** [comment]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: Version: 1.57.0 (user setup)
OS: Windows_NT x64 10.0.19042
![Untitled](https://user-images.githubusercontent.com/69891256/121710257-03479100-cb0c-11eb-9b9d-59bb70584f18.jpg)

**Comment by sandy081** [comment]
These logs are printed by Python extension, please file the issue against the extension first - https://github.com/Microsoft/vscode-python/issues
