### ISSUE TITLE
JS highlight on text variable

### ISSUE THREAD

**Issue by ehidoz** [microsoft/vscode#126060]
Hey everyone,

Anyone knows how to remove that highlight on vscode, when i select a text variable?

![VSCODE](https://user-images.githubusercontent.com/67163336/121710174-f2146b00-ca9e-11eb-8489-217aa2961c6f.jpeg)

**Comment by IllusionMH** [comment]
AFAIK only with `"editor.occurrencesHighlight": false`, but it will affect not only strings.

There is existing issue for multiline template literals https://github.com/microsoft/TypeScript/issues/43292 so you can add your feedback there or it make sense to add your feedback there or create new in TS repo

**Comment by ehidoz** [comment]
that´s all i need, thanks for your help
