### ISSUE TITLE
Suggestion preview: not working in json files?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#126061]
```js
"editor.suggest.preview": true,
```

Open suggest widget in `package.json` file:

<img src="https://user-images.githubusercontent.com/9638156/121710558-67555f80-cae2-11eb-90aa-7200b7cb889a.png" width="350px" />

**Comment by mkoeppen** [comment]
It isnt working for several file types. I miss the support in twig files. Is the filetyp-list somewhere configurable?

**Comment by hediet** [comment]
The problem is that the suggest item `description` wants to replace `"desc"` with `"description"`.
We are currently exploring to properly diff the strings or use the same character mapping logic that the suggest widget uses to support such scenarios.

**Comment by hediet** [comment]
In the current Insider build, you can set the preview mode to 'subwordDiff'
```
"editor.suggest.previewMode": "subwordDiff",
```

![image](https://user-images.githubusercontent.com/2931520/123782287-78211600-d8d5-11eb-81cc-648ab239ea50.png)


This is the default in todays build, but tomorrow the default will be `prefix` again.

**Comment by hediet** [comment]
Instead of `subwordDiff`, there is now `prefix`, `subword` and `subwordSmart`. `subwordSmart` is the new default (previously `prefix`).

`subwordSmart` enables subword based diffing, but only if no ghost text would be shown before the cursor. This is already the default for inline suggestions.
