### ISSUE TITLE
Trust which folder?

### ISSUE THREAD

**Issue by JosuaKrause** [microsoft/vscode#126067]
Upon installing the latest version I get prompted whether I trust "this folder".
However, the message doesn't indicate which folder it is referring to. I am assuming it is the base folder of the current project. However, there is no indication about this whatsoever.

<img width="679" alt="Screen Shot 2021-06-11 at 12 17 56 PM" src="https://user-images.githubusercontent.com/533142/121717635-65be7400-caaf-11eb-9c43-77af72114db2.png">

Here is a screenshot of the message.

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57
- OS Version: MacOS 11.3.1 (20E241)

Steps to Reproduce:

1. Open VSCode after updating

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/125984
