### ISSUE TITLE
"Trailing comma jsonc(519)" Appearing in Problems!

### ISSUE THREAD

**Issue by JLChamberlain** [microsoft/vscode#126024]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 10 Pro (Version	10.0.19043)

Steps to Reproduce:

1. Open settings to alter user settings
2. Problem appears listed

**Additional Information:**
I have `"workbench.settings.editor": "json"` & `"workbench.settings.useSplitJSON": true` in my user settings configuration. If I change them back to `"workbench.settings.editor": "ui"` & `"workbench.settings.useSplitJSON": false` the issue no longer appears after restarting the program and viewing settings. Problem is since the default settings file is read only I'm unable to remove the comma it constantly appears when opening the settings.

**Screenshot:**

![Screenshot (187)](https://user-images.githubusercontent.com/22307144/121665806-7fa48a80-caa0-11eb-8ad5-ed9537462cc2.png)

**Comment by sandy081** [comment]
#123039
