### ISSUE TITLE
VS Code 1.57 no longer picks up environment from ~/.bashrc on Linux

### ISSUE THREAD

**Issue by dlech** [microsoft/vscode#126066]
Does this issue occur when all extensions are disabled?: No

But this is a red herring! To run with extensions disabled, I had to launch VS code from a terminal which affects the environment `code` was launched in.

- VS Code Version: 1.57
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1.  Add this line to `~/.bashrc`:

        export GCC_10_ARM_NONE_EABI_BIN=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/

2. Install VS Code using the debian package.
3. Launch VS Code using the GNOME *Activities* menu or some other launcher - *not* from a terminal.
4. Start a new workspace and add this to the workspace settings:

    ```json
    "terminal.integrated.env.linux": {
        "CROSS_COMPILE": "${env:GCC_10_ARM_NONE_EABI_BIN}arm-none-eabi-"
    },
    ```

5. Restart VS Code and open the workspace again.
6. Open a terminal in VS Code
7. Run `echo $CROSS_COMPILE` in the VS Code terminal. The result is `arm-none-eabi-`. Prior to VS Code 1.57, the result was `/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-`
8. Close VS Code
9. Launch VS Code from an external terminal.
10. Repeat steps 5 to 7. The result is `/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-` as expected. This is because the external terminal set the environment from `~/.bashrc` and `code` inherited it.

**Comment by dlech** [comment]
I'm guessing this is fallout from #108804? e.g. the config options are now resolved before the user environment is resolved. Maybe a solution is to reevaluate config options after that?

**Comment by Tyriar** [comment]
Do you set the `terminal.integrated.inheritEnv` setting?

**Comment by dlech** [comment]
Yes, `terminal.integrated.inheritEnv` is enabled in my user settings.

**Comment by Tyriar** [comment]
Variable resolution may be working off the wrong environment

**Comment by Tyriar** [comment]
Report of `"args": [ "new-session", "-A", "-s", "${workspaceFolderBasename}" ]` not working in https://github.com/microsoft/vscode/issues/120667#issuecomment-875182389
