### ISSUE TITLE
Test: Commands in watermark

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12607]
Test for #12534 

- [x] Windows - @gregvanl 
- [x] Linux - @jrieken 

Complexity: 2

- Check whether or not you are shown the watermark on the empty editor area (the part of the experiment you are in)
  - Verify it stays the same when restarting (optionally: updating)
- If shown, verify:
  - it displays correctly
  - shows the correct keybindings
  - updates when changing keybindings
- If not shown, verify:
  - the logo displays all centered (as before)
- Repeat with the hidden setting `"telemetry.experiments.showCommandsWatermark"` set to the opposite

**Comment by gregvanl** [comment]
Suggestions https://github.com/Microsoft/vscode/issues/12797 and https://github.com/Microsoft/vscode/issues/12800

**Comment by gregvanl** [comment]
Couldn't get the telemetry.experiments.showCommandsWatermark switch to work https://github.com/Microsoft/vscode/issues/12807
