### ISSUE TITLE
Using a CodeLens to call a command which opens an Open File Dialog makes the dialog unresponsive Linux

### ISSUE THREAD

**Issue by datho7561** [microsoft/vscode#126088]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
- OS Version:
Fedora Linux 34

Similar to #62704

Steps to Reproduce:

1. Make an extension that creates a CodeLens which, when clicked, executes a command which opens a file dialog. [Here is a gist](https://gist.github.com/datho7561/275be3f5c91a2d8ef9509cce38604765) with the code for an extension that can reproduce this. The demo extension creates a CodeLens at the beginning of any XML file.
2. Make sure that `"files.simpleDialog.enable": false`
3. Run the extension, click on the CodeLens
4. The open file dialog opens, but nothing in the dialog can be clicked on
5. Like in #62704, the dialog still responds to typing
6. If you click on the title bar of VS Code, then back to the dialog, everything works again.

**Comment by alexr00** [comment]
This sounds like an electron problem. @deepak1556 does this sound familiar to you?

**Comment by deepak1556** [comment]
Can you check if the issue persists with latest stable `1.73`

**Comment by deepak1556** [comment]
Thanks for confirming.
