### ISSUE TITLE
skipFiles in launch.json still hits one file at <node_internals> at the end of execution. usage with "Type Script"

### ISSUE THREAD

**Issue by saran-surya** [microsoft/vscode#126064]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install node JS
2. Initialize a folder with npm init -y
3. Install typescript
4. Create a tsconfig as mentioned
    ```json
      {
        "compilerOptions": {
          "target": "esnext",                                
          "module": "CommonJS",                           
          "noEmitOnError": true,
          "sourceMap": true,                      
          "outDir": "./dist",                             
          "rootDir": "./src",                           
          "strict": true,                                 
          "moduleResolution": "node",             
          "skipLibCheck": true,                         
          "forceConsistentCasingInFileNames": true        
        },
      }

   ```
4. create an app.ts file
    ```ts  
      function foo(){
          console.log("this is logged from foo")
      }

     function bar(){
         console.log("This is logged from bar")
     }

     foo()
     bar()
     console.log("This is the ending")
    ```
5. Add a breakpoint at the last line, 
6. build the TS file and debug with the launch json config as mentioned below.
    ```json
      {
        "version": "0.2.0",
        "configurations": [
    
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "skipFiles": [
                    "<node_internals>/**",
                    "${workspaceFolder}/node_modules/**",
                ],
                "program": "${file}",
                "outFiles": [
                    "${workspaceFolder}/dist/test/*.js"
                ]
            }
          ]
      }
    ````
7. Now start the debug session in the app.ts file
8. Everything works fine as expected, but it hits the location ```<node_internals>\internal\per_context\primordial.js``` at the end of the execution.
9. As you can see this is the ```<node_internals>\internal\per_context\primordial.js``` is open, and it is mentioned in the skipped files section.
![image](https://user-images.githubusercontent.com/59312489/121711237-ff117880-caf7-11eb-9b21-2edc9344f77a.png)
10. As the below images describe that the file is listed in skipped files.
![image](https://user-images.githubusercontent.com/59312489/121711492-4b5cb880-caf8-11eb-9ff9-c44c793055d1.png)
![image](https://user-images.githubusercontent.com/59312489/121711656-77783980-caf8-11eb-813d-df6c5df400af.png)

### Expected behaviour : 
- Should not go into the files inside <node_internals>

### Actual Behaviour : 
- Hits only this file  ```<node_internals>\internal\per_context\primordial.js```  while the end of execution.

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/980
