### ISSUE TITLE
kill terminal command not working

### ISSUE THREAD

**Issue by preIdiot** [microsoft/vscode#126002]
Issue Type: <b>Bug</b>

I have keybinding to close a terminal 
```
 {
  "key": "ctrl+w",
  "command": "workbench.action.terminal.kill",
  "when": "terminalFocus"
 },
```
But it is not working after the update.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.8.0-55-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.52GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4dc39271-63cd-49ac-89e8-c42f5dd599e0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
bracket-pair-colorizer-2|Coe|0.2.0
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|6.4.0
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.213
node-module-intellisense|lei|1.5.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
indent-rainbow|ode|7.5.0
advanced-new-file|pat|1.2.2
extension-pack-for-vscode|pre|0.0.1
frontend-dev-extension-pack|Pre|0.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
js-jsx-snippets|sky|10.1.0
vscode-fileutils|sle|3.4.5
vscode-icons|vsc|11.4.0
quokka-vscode|Wal|1.0.374
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by meganrogge** [comment]
That exact keybinding is working for me. Check in the keybindings editor where you might have a keybinding that conflicts/competes with it.
![recording - 2021-06-11T094510 869](https://user-images.githubusercontent.com/29464607/121721969-b32fe680-ca99-11eb-85a7-392188aedf82.gif)
