### ISSUE TITLE
doc: update integrated terminal doc to avoid mention of deprecated settings

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#126047]
https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed suggests use of `terminal.integrated.shellArgs` 

> The other fix is to no longer run a login shell in the terminal by setting "terminal.integrated.shellArgs": []. If you go with this fix, you will want to make sure any aliases in your profile scripts are moved over to your ~/.bashrc/~/.zshrc file since aliases only apply to the shell they're set in.

I guess this setting is deprecated or soon-to-be-deprecated (sorry, if I am wrong - I was guessing based on the 1.57 release note and discussion like #123171) and the doc needs update.

**Comment by meganrogge** [comment]
thanks, moved to our docs repo
