### ISSUE TITLE
Key Bindings Command-1 etc. no longer work in macOS

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#126035]
Issue Type: <b>Bug</b>

Key bindings Command-1, Command-2, etc. no longer switch tabs. Pressing these keys does nothing. Previous versions of v1.56 did not have this problem. I was automatically upgraded to 1.57.0 which is broken because the extension host quits. When I downgraded to 1.56 I got 1.56.2. I don't know what version I had one hour ago because of the ridiculous automatic upgrading which i have disabled now but the one-hour-ago version honored the Command-number keys and did not break all of my extensions.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 5, 5|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_20005651|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.38.0
ada|Ada|22.0.8
Bookmarks|ale|13.1.0
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
project-manager|ale|12.2.0
rtf|ale|2.3.0
show-unsaved-changes|ctf|0.0.9
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.42.1
vscode-great-icons|emm|2.1.77
ada-snippets|Ent|0.3.0
vscode-faust|gle|1.1.0
vscode-lyx|gyt|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.19.2
svn-scm|joh|2.13.6
language-julia|jul|1.2.3
keen-neutral-icon-theme|kee|1.0.8
linter-gfortran|krv|2.2.2
octave|lea|0.1.1
eps-preview|mkv|0.1.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
cpptools|ms-|1.4.1
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.15
bib|phr|0.3.0
seti-icons|qin|0.1.3
ipf|qms|1.0.1
lualint|sat|0.0.5
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.21
octave|toa|0.0.3
pdf|tom|1.1.0
vscode-lua|tri|0.12.4
vscode-icons|vsc|11.4.0
vscode-icons-mac|way|7.25.3
debug|web|0.25.0
txt-syntax|xsh|0.1.5
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by oscarrutt** [comment]
I got the June 12, 2021 insiders build. I have not set Cmd+1 etc. to switch window within an editor group in the Insiders version so I can't directly test this. I could do this but...

...After posting the ticket and fiddling around for a while including multiple restarts of VSC, for some reason I rebooted my computer and the problem was gone. IIRC this is the only time since Apple switched to Unix that rebooting my computer has fixed a problem except a couple of times  for a cranky WiFi that rarely doesn't automatically reconnect after waking from sleep.

I will note in passing that I have had other Command-something keystrokes quit in VSC before also, notably Command-v for pasting. This occurred a number of times a few weeks ago and was cured by restarting VSC. I haven't noticed it recently.

Since my problem is gone and I can't replicate it I suppose you should close this one.
