### ISSUE TITLE
MacOS native tabs: use vscode terminal open un-trust workspace getting wrong display when fullscreen vscode

### ISSUE THREAD

**Issue by Aliveing** [microsoft/vscode#126016]
Issue Type: <b>Bug</b>

Here is reproduce steps: 
step 1: fullscreen vscode
step 2: show terminal
step 3: run `code [any path with no workspace-trust]` to open a new vscode window
step4: new window will create at a new desktop, sometimes your "run terminal window" being all black, and new window has no title bar

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 5, 4|
|Memory (System)|16.00GB (1.94GB free)|
|Process Argv|--crash-reporter-id eea790c0-136d-4c1b-a29e-c7866504675e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
z-reader|aoo|1.0.3
color-info|bie|0.6.0
vscode-gemfile|bun|0.4.0
simple-react-snippets|bur|1.2.3
turbo-console-log|Cha|2.1.6
gitignore|cod|0.7.0
erb|Cra|0.0.1
vscode-taro-snippets|crp|0.0.4
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.22
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
remotehub|eam|0.5.0
vscode-html-css|ecm|1.10.2
LogFileHighlighter|emi|2.11.0
prettier-vscode|esb|6.4.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.213
vscode-drawio|hed|1.4.0
vue-snippets|hol|1.0.4
minify|Hoo|0.4.3
rest-client|hum|0.24.5
iceworks|ice|1.0.3
iceworks-app|ice|1.0.0
iceworks-config-helper|ice|0.5.5
iceworks-doctor|ice|1.0.0
iceworks-material-helper|ice|1.0.4
iceworks-project-creator|ice|1.0.0
iceworks-refactor|ice|1.0.0
iceworks-style-helper|ice|1.0.0
iceworks-time-master|ice|1.0.1
iceworks-ui-builder|ice|0.3.4
comment-translate|int|1.4.2
path-autocomplete|ion|1.17.1
vue|jcb|0.1.5
polacode-2019|jef|0.5.2
endwise|kai|1.4.2
kite|kit|0.147.0
evermonkey|mic|2.4.5
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.57.1
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.6
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.1
color-highlight|nau|2.3.0
live-server-preview|neg|0.1.4
korofileheader|OBK|4.8.12
vetur|oct|0.34.1
remote-vscode|raf|1.1.0
vue-vscode-snippets|sdr|2.2.0
code-settings-sync|Sha|3.4.3
slim|sia|0.1.2
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
polacode-fork|Tox|0.6.0
codelf|unb|11.7.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.4.0
vim|vsc|1.21.1
codetour|vsl|0.0.56
vscode-wakatime|Wak|12.0.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by bpasero** [comment]
Likely #126013

**Comment by bpasero** [comment]
@Aliveing do you have native macOS tabs enabled?

**Comment by Aliveing** [comment]
![image](https://user-images.githubusercontent.com/11768879/121665514-f8c0d380-cada-11eb-8dbf-4cadcfa8b436.png)
Yes, I enabled it.

**Comment by ryenus** [comment]
@bpasero see also my comment here: 
https://github.com/microsoft/vscode/issues/125122#issuecomment-859403189

**Comment by Aliveing** [comment]
1.57.1 works fine, thanks a lot.

**Comment by deepak1556** [comment]
Reopening as we still haven't addressed the issue in insiders.
