### ISSUE TITLE
[Test Explorer] Cannot see the added test item in the explorer when it's overflow the explorer height

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#126163]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.58.0-insider (user setup)
Commit: 012b14606f75ec4fed90d7ab4154f63dffab9503
Date: 2021-06-11T05:14:11.473Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. In the project `test-provider-sample` add a test child in the `run()` method of `TestCase`
```ts
if (actual === this.expected) {
   ...
} else {
    const child1 = vscode.test.createTestItem<TestCase>({
        id: `mktests/${this.item.uri!.toString()}/${this.item.label}#1`,
        label: this.item.label,
        uri: this.item.uri!,
    });
    child1.range = this.item.range;
    this.item.addChild(child1);
    const message = vscode.TestMessage.diff(`Expected ${this.item.label}`, String(this.expected), String(actual));
    ...
}
```
2. Add some more tests in the markdown file and shrink the height of the vs code window
3. Run a markdown file
4. The newly added test case will be overflow and cannot be seen in the test explorer
5. The scroll bar will get updated when the height of vs code is changed

https://user-images.githubusercontent.com/6193897/121801044-26487280-cbea-11eb-83a2-131925d356e2.mp4

//cc @connor4312 for awareness, but this might be an issue of explorer view

**Comment by connor4312** [comment]
cc @joaomoreno it seems that adding a child via `setChildren` doesn't trigger the tree ti check scroll height. Resizing the window by 1px fixes it. Is there guidance on what should happen here?

**Comment by joaomoreno** [comment]
> Resizing the window by 1px fixes it.

This usually means we haven't called `tree.layout()` every time we should've.

This looks very suspicious: https://github.com/microsoft/vscode/blob/274cbd8e0541b02a71ddcd3a7f043e9291a47a69/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts/#L432-L437

We should be forwarding those dimensions down to the tree here instead: https://github.com/microsoft/vscode/blob/274cbd8e0541b02a71ddcd3a7f043e9291a47a69/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts/#L205-L212

**Comment by connor4312** [comment]
Ah, nevermind, I found the issue 🙂 It's this message. Initially it's hidden, but then when we show it later we don't adjust the height of the tree to compensate for it.

![](https://memes.peet.io/img/21-06-ed06315e-a2ad-46fd-8f68-0492bf74c1b9.png)
