### ISSUE TITLE
Non-english language not handled correctly in terminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12612]
- ~~VSCode Version: 1.6 Insider~~
- VSCode Version: 1.5
- OS Version: OS X 10.11.6

![language](https://cloud.githubusercontent.com/assets/4033249/18823977/b0a8d5d8-8373-11e6-8266-2c512c5a59ac.gif)

**Comment by Tyriar** [comment]
Can you repro on stable?

**Comment by octref** [comment]
@Tyriar Yep.

Sample text you can test against:

- Bücher
- こんにちは
- 你好

**Comment by rmunn** [comment]
I can't reproduce this on Ubuntu Linux 14.04: Bücher, こんにちは and 你好 all print out correctly for me in the Terminal.

Version 1.6.0-insider
Commit d81ee41c51cae93a5cac967e42a28660a3a7e005
Date 2016-09-23T05:58:22.484Z
Shell 1.3.5
Renderer 52.0.2743.82
Node 6.3.0

**Comment by octref** [comment]
Doesn't happen on Windows too.

**Comment by Tyriar** [comment]
Cannot repro either, maybe an issue with the mac IME?

**Comment by octref** [comment]
Sorry, seems I was using 1.5 when reporting. Just downloaded the Insider build 3 days ago and can't repro this.
