### ISSUE TITLE
how to load fixture && trigger plugin's activationEvents?

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#12613]
had read https://code.visualstudio.com/docs/extensions/testing-extensions and look into some plugin source, but can't found a complete real test example.

**Comment by chrmarti** [comment]
@jrieken You've done some integration tests, right?

**Comment by bpasero** [comment]
@atian25 if you install the code generator it will produce a sample with tests:
* npm install -g generator-code
* yo code
* pick either the TS or JS extension

**Comment by bpasero** [comment]
You can also look how other extensions do it, e.g. the famous VIM extension has many integration tests: https://github.com/VSCodeVim/Vim/blob/master/test/extension.test.ts

**Comment by atian25** [comment]
thanks @bpasero .

I know about `yo` and `mocha` and had do that, but the boilerplate is very simple, do not contain any guide for integration test. And had do a lots google search.

sorry for disturb, I will take a look at vim, thanks.

**Comment by bpasero** [comment]
@atian25 basically our integration tests are all mocha tests, it is just different how to execute them. you can either run them from within Code from the debug viewlet or from the command line.
