### ISSUE TITLE
Scrolling on mouse click

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#126178]
Issue Type: <b>Bug</b>

I have been using 
```
"editor.cursorSurroundingLines": 5,
```
for a long time. Currently I end up with a LOT of inadvertant selections when working in two side-by-side editor groups and switching back and forth between them using the mouse.

The reason is that the editor scrolls 5 lines **every time** I click into it. 

VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:22:19.992Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1046-azure

**Comment by alexdima** [comment]
@kieferrm I cannot reproduce. Does this reproduce for you when disabling all extensions? I have recently also got https://github.com/microsoft/vscode/issues/126146 which seems incredibly similar, but I am having a hard time reproducing any of the jumping that is described. Here I am trying two side-by-side editor groups:


https://user-images.githubusercontent.com/5047891/121919406-489bd680-cd37-11eb-984c-a57671662574.mp4

**Comment by alexdima** [comment]
This reproduces only when the language mode of the files are set to markdown.

@mjbvz I think this has to do with how the markdown extension is using the `revealRange` vscode API. But I think it should not use that API at all if no markdown preview is rendered. But it would also be interesting to test what the experience is when the preview is rendered.

**Comment by mjbvz** [comment]
@andreamah Could you please take a look at this since you were looking into markdown syncing last iteration?

**Comment by andreamah** [comment]
It seems like it's a bug coming from the scroll syncing between the static and text editor changes that I made a while ago. I'll try to make a PR to fix this soon.
