### ISSUE TITLE
Run code missing

### ISSUE THREAD

**Issue by f-lima** [Microsoft/vscode#12610]
- VSCode Version: 1.5.3
- OS Version: macOS Sierra

Missing a button to RUN the code.

The extension Code Runner can do run the code but you need to press a set of keys or press F1 and type run. A simple button could be introduced to let us run the code edited like the Code Runner App available on Mac App Store.

**Comment by chrmarti** [comment]
You could set up a launch config or a task to do that.

**Comment by f-lima** [comment]
Yes. I use CodeRunner and a key combination to run the code, but I miss the button that make it more visual and is the standard at any IDE to run any code.
Having the RUN button you know that the IDE can do that. When it is not present appear that we are working on a text editor only.
In fact, the best is have 3 buttons: one button to RUN and another to STOP and one to RUN SETTINGS. Because we can need to change the run settings and params passed for each run to test different parts of software, then this 3 buttons are missing.

**Comment by chrmarti** [comment]
There is a run button and 'launch settings' button in the Debug viewlet. You get to that by clicking the debug icon in the top left of the window. Once you have an application running in debug mode you'll also have a stop button. See: https://code.visualstudio.com/docs/introvideos/debugging

**Comment by f-lima** [comment]
Found it, thanks.

**Comment by f-lima** [comment]
This button doesn't run the code calling CodeRunner extension to run.
When I try do this I get the following message "Cannot find runtime 'node' on PATH."

**Comment by chrmarti** [comment]
I guess I misunderstood. You cannot launch CodeRunner from launch.json. You can however use it to launch an entire application. It complains about not finding `node` because "type": "node" and nodejs is not on your PATH. Depending on what language you are working with you need to choose a different "type" in your launch.config, it might be easiest to look up an example for your programming language and stack.

**Comment by f-lima** [comment]
Is it possible integrate this debug tab with Code Runner extension as a solution to we have the desired buttons to control the process of run an application, in a future version of VSCode?

**Comment by chrmarti** [comment]
Using this to track the request for a "Run selected code snippet" action.

**Comment by f-lima** [comment]
Debug tab don't work with Code Runner extension.
Is it possible make it work in a future VSCode version?

**Comment by f-lima** [comment]
Thank you
