### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by Xiaolong375** [microsoft/vscode#126162]
Issue Type: <b>Performance Issue</b>

Unable to resolve resource walkThrough://vscode_getting_started_page

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.33GB free)|
|Process Argv|--crash-reporter-id dd14aa37-e326-4ef2-a060-002acccabec3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	 14904	code main
    0	    82	   316	   shared-process
    0	    69	 14300	     ptyHost
    0	     6	  5552	       console-window-host (Windows internal process)
    0	    67	 12268	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   190	  3100	   window (vue-admin-template-master - Visual Studio Code)
    0	   109	  3348	     extensionHost
    0	    70	 12172	       "E:\VS Code\Code.exe" "e:\VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3348
    0	    70	  4064	     searchService
    0	    12	 10224	     watcherService 
    0	    11	  8528	       console-window-host (Windows internal process)
    0	   102	  3500	   gpu-process
    0	    25	 12416	   crashpad-handler
    0	    81	 13160	   window (问题报告程序)
    0	    50	 14384	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (vue-admin-template-master - Visual Studio Code)
|    Folder (vue-admin-template-master): 151 files
|      File types: js(40) vue(25) svg(17) json(8) scss(7) yml(2) md(2) png(2)
|                  editorconfig(1) development(1)
|      Conf files: jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.22
gitee|g8u|0.0.6
vscode-language-pack-zh-hans|MS-|1.57.1
cpptools|ms-|1.4.1
vetur|oct|0.34.1
LiveServer|rit|5.6.1
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by JacksonKearl** [comment]
Looks like https://github.com/microsoft/vscode/issues/124386. Have you set `{"workbench.editorAssociations": { "*": "default" }}`?

**Comment by Xiaolong375** [comment]
“vs_code_welcome_page”: Unable to resolve resource walkThrough:/e%3A/VS%20Code/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D。
| |
赵小龙
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/14/2021 23:08，Jackson ***@***.***> wrote：

Looks like #124386. Have you set {"workbench.editorAssociations": { "*": "default" }}?

**Comment by JacksonKearl** [comment]
This should be fixed in next release, until then you can make sure you do not have `{"workbench.editorAssociations": { "*": "default" }}` set in your `settings.json`
