### ISSUE TITLE
Windows 7: Seeing 2 times "Define Keybinding" even for readonly side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1261]
Testing on Windows 7, I get the green UI for both sides:

![image](https://cloud.githubusercontent.com/assets/900690/11782057/c350e4fa-a26e-11e5-912e-029e0cef15ee.png)

**Comment by bpasero** [comment]
Maybe it is also related to the fact that here I did not open a workspace?

**Comment by alexandrudima** [comment]
Steps to repro:
* new window (ctrl+shift+n)
* open keyboard preferences
