### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ChrisRothove** [microsoft/vscode#126192]
Issue Type: <b>Bug</b>

since the update to VSC My extensions are no longer working when I open up a new instance of VSC connected to my WSL: Ubuntu server. I am not sure why this is but it is incredibly inconvenient. 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.47GB free)|
|Process Argv|--crash-reporter-id d22e6b40-25af-45e6-8c79-311e4c8aa295|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (22.84GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (22.84GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
auto-rename-tag|for|0.1.6
remote-wsl|ms-|0.56.5
debugger-for-chrome|msj|4.12.12
swdc-vscode|sof|2.5.15
dark-synthwave-vscode|Aar|0.0.14
suggested-fullstack-bootcamp-extension-pack|Aar|1.0.0
TabOut|alb|0.2.0
turbo-console-log|Cha|2.1.6
vscode-eslint|dba|2.1.22
prettier-vscode|esb|6.4.0
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.213
vscode-duplicate|mrm|1.2.1
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
reload|nat|0.0.6
indent-rainbow|ode|7.5.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by alexdima** [comment]
@ChrisRothove We have recently seen problems with resolving the shell environment that could lead to a deadlock of sorts in launching the extension host (https://github.com/microsoft/vscode-remote-release/issues/5129). Could you please try our Insiders build which contains a mitigation to give up on resolving shell env variables after 10s ?
