### ISSUE TITLE
Word Separators no longer work with Powershell

### ISSUE THREAD

**Issue by JoeBrunsTR** [microsoft/vscode#126110]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
- Version: 1.57.0 (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

- OS Version:
Version: 1.57.0 (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.  Set Word Separators to `~!@#%^&*()=+[{]}\|;",.<>/?'
2.  The separator above removes the $ sign and the : colon
3.  Open a powershell script
4.  Type $global:somevar = 'abc'
5.  Double click on $global:somevar

Normal behavior should highlight the entire $global:somevar string so a person can copy easily.

The bug arrived sometime on or after 1.56 and the double click will only highlight the $global.

**Comment by JoeBrunsTR** [comment]
It would appear that the Powershell extension is the culprit.  If I disable it, the problem goes away.  If I reload and enable, problem comes back.

I am running this version of the Powershell extension:

PowerShell
ms-vscode.powershell
Microsoft
4,069,920
Repository
License
v2021.5.1

**Comment by alexdima** [comment]
@JoeBrunsTR It looks like the PowerShell extension defines language specific default settings [here](https://github.com/PowerShell/vscode-powershell/blob/88f9688488ae6751eb95c406eafd5f9a9d2aea65/package.json#L898-L904). Language specific default settings are "stronger" than regular user settings so to effectively define a "stronger" setting you need to also write a language specific setting. e.g. in your `settings.json`
```
"[powershell]": {
  "editor.wordSeparators": "`~!@#%^&*()=+[{]}|;",.<>/?'"
}
```

@sandy081 This issue is about UX confusion that stems from language specific default settings being "stronger" than regular user settings, it is not a problem with the editor. I believe we should improve our settings UX, like with a hover at the right place warning that "This setting will not apply to [powershell]", etc.

**Comment by JoeBrunsTR** [comment]
Prior to 1.56, I never had any issues.

**Comment by alexdima** [comment]
@JoeBrunsTR You're right. But this is something the PowerShell extension defines, so this doesn't have anything to do with the VS Code version. If the PowerShell extension released an update at the same time as the VS Code update, then that was a coincidence. This was added by the PowerShell extension very recently -- https://github.com/PowerShell/vscode-powershell/commit/c6085977431878118c5dc28a5e51e05c8947be0f

Again, you can override what they are defining using the following in your `settings.json`:
```
"[powershell]": {
  "editor.wordSeparators": "`~!@#%^&*()=+[{]}|;",.<>/?'"
}
```

**Comment by JoeBrunsTR** [comment]
Is there a quick way to get to that setting using preferences?

**Comment by alexdima** [comment]
@JoeBrunsTR `F1 > Preferences: Open Settings (JSON)` and then you can paste the snippet I've shown earlier in the other settings. e.g.
```js
{
  // ... other settings
  "[powershell]": {
    "editor.wordSeparators": "`~!@#%^&*()=+[{]}|;",.<>/?'"
  }
  // ... other settings
}
```

**Comment by JoeBrunsTR** [comment]
Thanks for that.  Will someone be contacting the authors of the Powershell extension or do I have to start a thread someplace else?

**Comment by JoeBrunsTR** [comment]
Unfortunately, the editor in vscode does not like the data.

"[powershell]": {
        "editor.defaultFormatter": "ms-vscode.powershell",
        "editor.wordSeparators": "`~!@#%^&*()=+[{]}|;",.<>/?'"
    },

Starting with the dot after the comma, it is being flagged red.

![2021-06-14 12_51_06-● settings json - build2019 - Visual Studio Code](https://user-images.githubusercontent.com/67018945/121936501-50e01b80-cd0f-11eb-8cfd-0f0a0fc4892d.png)

**Comment by carlocardella** [comment]
The string is not properly escaped, there is a `"` after the semicolon that is closing the string and all characters after that are not properly enclosed. 

Escaping the double-quote after the semicolon removes the problem: 

```json
"editor.wordSeparators": "`~!@#%^&*()=+[{]}|;\",.<>/?'"
```

**Comment by roblourens** [comment]
You can escape the `"` with a backslash so it doesn't end the JSON string

**Comment by JoeBrunsTR** [comment]
That worked great.  Is there anything we need to ask of the Powershell extension developers?

**Comment by roblourens** [comment]
I think the only issue here is just that this is unfortunately not obvious in the settings editor GUI. Have https://github.com/microsoft/vscode/issues/58995 for that.
