### ISSUE TITLE
Letter spacing in Terminal bugs

### ISSUE THREAD

**Issue by Leonardo1807** [microsoft/vscode#126166]
Does this issue occur when all extensions are disabled? Yes.

- VS Code Version:    1.56.2
- Artix Linux Version:  Linux surface 5.12.10-artix1-1 x86_64 GNU/Linux

Steps to Reproduce:

1. When I open a Terminal or I run a program the letter spacing is very ugly (see picture 1)
2. After I set the Font-size from 14 to 13 (and then back to 14) my Terminal looks normal again (see picture 2).

Why is that?

Picture 1:
![picture_1](https://user-images.githubusercontent.com/76753869/121805898-93412400-cc4d-11eb-8cc9-4193ce12bc21.png)

Picture 2:
![picture_2](https://user-images.githubusercontent.com/76753869/121805900-96d4ab00-cc4d-11eb-8b43-a9570bdc5c67.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it still reproducible in latest stable version 1.57.0?
Should be fixed there

**Comment by Leonardo1807** [comment]
> Is it still reproducible in latest stable version 1.57.0?
> Should be fixed there

It is fixed there. Thank you very much!
