### ISSUE TITLE
Having issues with VBScript Debugger and Debug Console 

### ISSUE THREAD

**Issue by Lovejones411** [microsoft/vscode#126151]
Hello. I am using Visual Studio Code (not VS 2019) and I can not seem to get the debugger to work. I have tried adding multiple extensions for specifically VBScript, but none of them seem to work.  Also, previously, I was able to print my code to the Debug Console, but now that has stopped completely as well. Probably is a pretty easy issue to clear up, but I didn't see an answer for this specifically on the site. Thanks. 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.51GB free)|
|Process Argv|--crash-reporter-id 07cf838d-a872-40ba-9375-f9426be0ee46|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.25.0
vscode-django|bat|1.6.0
vbscript|Dar|1.0.4
python-extension-pack|don|1.6.0
json-tools|eri|1.0.2
php-debug|fel|1.16.0
code-runner|for|0.11.4
godot-tools|gee|1.1.2
cloudcode|goo|1.12.1
realtime-debugging|hed|0.1.0
mcfdebugger|Hug|0.1.1
elixir-ls|Jak|0.7.0
vscode-codeception|joe|1.2.0
intellij-idea-keybindings|k--|1.4.5
MagicPython|mag|1.1.0
json|Mee|0.0.1
vscode-ros|ms-|0.6.8
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
cpptools|ms-|1.4.1
vscode-typescript-next|ms-|4.4.20210612
cordova-tools|msj|2.2.2
MVONdebugger|ong|0.16.0
colorful-comments|Par|0.6.2
java|red|0.79.2
vbsvscode|Ser|1.2.1
c-cpp-flag-debugging|uts|0.0.1
vbb-debug|vir|0.1.12
vscodeintellicode|Vis|1.2.14
vms-ide|VMS|1.5.41
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
jinja|who|0.0.8
eno|Wsc|2.3.53
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

![image](https://user-images.githubusercontent.com/80616042/121794000-9094ef00-cbb9-11eb-9220-94a2aaebc0b6.png)

**Comment by Lovejones411** [comment]
Also, when I try to  run the code and debug, I get the following error. 

![image](https://user-images.githubusercontent.com/80616042/121801944-c607ff80-cbee-11eb-8f6f-f172f0d30da3.png)

![image](https://user-images.githubusercontent.com/80616042/121801967-e1730a80-cbee-11eb-81b9-97ba2bbe866e.png)

**Comment by Aminadav** [comment]
There is no VBScript debugging in VSCode. The best you can get is symbols, problems and so on.

**Comment by weinand** [comment]
@Lovejones411 I'm not aware of any VS Code extension that provides VBScript debugging support.
