### ISSUE TITLE
The window has crashed (reason: 'oom')

### ISSUE THREAD

**Issue by AidanTomcy** [microsoft/vscode#126127]
I had installed Visual Studio Code and it was working fine. Then, I cleared my computer and all files were deleted. When I installed Visual Studio Code again,  it opens, but when I start typing, it shows the following message: 'The window has crashed (reason: 'oom')'

![Error](https://user-images.githubusercontent.com/80614206/121773213-025c4100-cb98-11eb-94db-34d3c2afc734.JPG)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
