### ISSUE TITLE
Ctrl+C in command line closes VS Code

### ISSUE THREAD

**Issue by aldonunez** [microsoft/vscode#126101]
Issue Type: <b>Bug</b>

1. Run cmd
2. In cmd, run `code`
3. In the same instance of cmd, press Ctrl+C.

It doesn't matter whether you press Ctrl+C right away, or after running an internal command like dir, or even inside another program running in cmd like python. Nor does it matter whether you run cmd inside Powershell.

This problem also happens directly in Powershell. But in this case it happens only while Powershell executes a command. For example, when you press Ctrl+C during `dir -re C:\Windows\*.exe`

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (23.02GB free)|
|Process Argv|--crash-reporter-id 7b4af775-1c83-468d-92da-7f2456dfae63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.7.3
cmake|twx|0.0.17

</details>

**Comment by meganrogge** [comment]
I can't reproduce this.  What are the keybindings you have associated with Ctrl+C? 

Was this happening in prior versions?

**Comment by aldonunez** [comment]
It's a new installation of Windows and Windows Terminal. I haven't changed any key bindings.

**Comment by aldonunez** [comment]
I just tried it with two more machines, and got the same result.

**Comment by Tyriar** [comment]
This is related to the attached console; running the `code` cli within an external cmd window, ctrl+c will close VS Code.

**Comment by deepak1556** [comment]
Can you provide the output of `Get-Command code` or any other similar ones depending on your shell to print what `code` aliases to ? The console attachment should not happen if the alias was pointing to our cli wrapper.

**Comment by aldonunez** [comment]
```
C:\Users\Aldo>where code
C:\Users\Aldo\AppData\Local\Programs\Microsoft VS Code\Code.exe
```
