### ISSUE TITLE
Content jumps on editor switching

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#126146]
Issue Type: <b>Bug</b>

1.
```js
"editor.cursorSurroundingLines": 4,
```

2. Open multiple editors with any text:

<details><summary>Lorem</summary>

Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil iusto a autem, deleniti vel at laborum cum consectetur ex, beatae impedit molestiae! Beatae, culpa pariatur perspiciatis error ratione animi ad.
Deleniti mollitia numquam repudiandae corrupti, necessitatibus at consequuntur minus reiciendis quas quos corporis nisi? Recusandae odit ullam animi dicta accusamus assumenda ratione. Rem dolorum, amet vel magnam ab iusto facilis!
Molestias tempore laborum eum non at nesciunt, voluptas iste aspernatur atque fuga quibusdam repellendus praesentium, expedita, itaque fugiat corporis explicabo beatae? Consequuntur cupiditate rem repellat eligendi cum illo necessitatibus dolorum.
Optio voluptatum, perspiciatis libero iusto alias enim omnis eveniet rem eius excepturi rerum accusantium, ad assumenda dolorum delectus, aut officia culpa! Ullam ab repellendus a ad placeat corporis tempore! Odit.
Illum nemo minus velit doloribus dolorem excepturi pariatur minima adipisci odit illo assumenda debitis ducimus exercitationem ipsa nulla, ipsam doloremque iure facilis. Eos molestiae facere distinctio accusamus autem totam veritatis.
Molestias maxime natus in aliquid velit eius quasi labore totam placeat rem explicabo obcaecati itaque id fuga quo doloremque neque incidunt amet, quae quod nostrum consectetur sunt. Enim, cumque blanditiis!
Odio enim nostrum unde beatae, recusandae atque sed, nemo nisi voluptatem, optio veniam! Ipsam quasi praesentium iure dicta cupiditate officia exercitationem voluptas facere! Autem, cumque? Fuga quibusdam sint ipsa facilis.
Fugit deserunt enim saepe, inventore, quia blanditiis nesciunt minima omnis, cumque ad sit id dolores aspernatur earum numquam rem impedit odit molestiae ipsa est! Neque quos reprehenderit repudiandae possimus exercitationem.
Dolores, quasi. Eum quasi dolores culpa, quos asperiores maiores perferendis praesentium tenetur, similique corporis, error dolor earum enim rem! Dignissimos magni illum quasi nam quis culpa laborum sequi natus? Et?
Nam magnam repellat provident harum saepe voluptatibus debitis a numquam temporibus ratione quod dignissimos expedita et cumque commodi odio natus laborum, labore blanditiis! Impedit exercitationem accusamus nemo eos minima! Debitis.
Saepe, illum facilis voluptatibus, perferendis maiores molestias rerum accusamus aliquam sed aperiam laboriosam iure earum dicta dolorem nemo itaque eligendi, ea neque ratione id fugit. Deserunt sunt pariatur commodi iusto!
Nihil provident magnam, consequatur debitis dolorem omnis dignissimos libero enim quisquam laborum, consectetur dolores nesciunt commodi ipsa recusandae assumenda doloremque iure voluptate necessitatibus sunt ullam ut labore? Explicabo, maiores unde?
Veritatis velit distinctio, rerum facilis praesentium molestiae, animi vero aut, quaerat accusamus voluptas iure unde ipsam. Ab, dolorem! Fugiat architecto odio quasi at ut? Voluptas perspiciatis maxime veniam dolorem facilis!
Assumenda eaque impedit debitis. Eveniet reiciendis at expedita blanditiis velit libero sunt quas laudantium alias aliquid vero illo, ad autem, architecto quo facilis assumenda molestiae. Minus recusandae fuga perspiciatis nisi.
Necessitatibus tempore, reprehenderit illum dolor quibusdam dignissimos quidem! Minima eaque quibusdam, molestias nemo tempore inventore. Fuga, ad corporis quam necessitatibus earum rem sit voluptate ab est numquam nemo laudantium facere.
Non incidunt ab tempora harum amet suscipit eos nulla libero blanditiis laborum, ut deleniti nisi beatae maxime labore eaque consectetur! Nisi consequatur officiis excepturi, labore atque rem possimus voluptatem in?
Asperiores pariatur distinctio sapiente ducimus molestiae aliquid enim voluptate expedita maxime perferendis necessitatibus accusantium ab, exercitationem reiciendis. Illo similique error explicabo voluptatem aperiam nisi! Tenetur voluptates accusamus modi a eos?
Eveniet iste esse illum sint eaque numquam temporibus nesciunt exercitationem optio, fugiat dolores qui repellat cum nam. Ipsam, repellendus odio sequi dignissimos, a enim explicabo dolorem eum ea, ipsum saepe.
Ea aut reprehenderit odio neque ab assumenda incidunt quia pariatur voluptate repellat quae, et, vitae reiciendis cumque amet eligendi alias sequi tempore quos culpa, perferendis excepturi. Porro reiciendis natus ex.
Tempora architecto, aspernatur assumenda voluptatem accusantium ab aliquid cum. Dolore architecto, tempora consequatur repudiandae quos numquam est ab obcaecati doloremque recusandae error delectus qui et soluta nam eius quae pariatur!
Obcaecati voluptatum ducimus eum alias eaque similique! Perspiciatis porro hic vero, reprehenderit tempore officia nisi aut ratione consequuntur minima excepturi nesciunt magnam in eaque modi saepe dignissimos quasi sit nulla!
Eum quae quas natus culpa dicta incidunt dignissimos dolorum tempora sapiente laudantium? Ducimus nisi porro cupiditate itaque voluptatem minus natus, temporibus fuga veritatis, quia totam! Voluptate molestias libero saepe quod!
Suscipit corrupti fugit et unde aspernatur repellendus repellat perferendis. Eaque quis corrupti nam quam esse dolorem, nemo libero ad! Cumque perferendis quam ea eum maiores debitis voluptatem nostrum ipsum saepe.
Maiores voluptatum ipsa, voluptatibus enim tempora rerum recusandae, fuga culpa earum corrupti dicta quidem beatae. Id sint sit aliquam quaerat. Iusto, consequuntur harum? Magni sed tenetur quidem, minus iusto explicabo!
Voluptates velit facilis atque numquam, quibusdam explicabo quidem hic eius veniam corrupti, distinctio nostrum! Esse similique optio quam omnis itaque eius quas veritatis eaque earum dolores, blanditiis, consequuntur suscipit nisi.
Natus quisquam quod error sunt. Perferendis incidunt eligendi explicabo id doloremque, praesentium voluptas rerum reiciendis omnis fugit similique earum corporis eos ullam! Nisi, sequi nesciunt iusto mollitia ratione voluptate enim.
Minus, repellat, ipsam assumenda harum temporibus architecto eius fugit repellendus tempora iusto, numquam velit. Ad fuga totam facere repudiandae tempora, quisquam quam dicta exercitationem, officiis, dolore illum voluptate odit magni.
Vel praesentium asperiores laboriosam esse aliquam autem quas repellat, ullam optio aut magni quidem ratione voluptas similique fugiat aspernatur ea corporis exercitationem sequi provident ad ex suscipit. Quos, quo libero.
Ducimus excepturi deleniti asperiores voluptates fuga rerum adipisci rem quod repudiandae temporibus soluta, ipsum amet quas. Officia facilis fugiat, voluptatum tenetur, sint modi voluptate dolore cupiditate maiores cumque distinctio nemo?
Id deserunt autem rerum? Esse sed aut, dolorum distinctio asperiores eligendi ex atque provident et explicabo eius adipisci nisi accusantium maiores nihil at ab eos perspiciatis. Natus id omnis quaerat?
Laborum aperiam quibusdam et rem sint eveniet dolorum enim, consectetur aut voluptatum. Possimus, similique? Eveniet tempore ducimus laudantium, voluptatem dicta quas iste? Omnis, facere quos autem magnam eligendi accusamus labore?
Excepturi nobis impedit est unde corrupti optio omnis hic, quibusdam adipisci atque voluptatem vero quas soluta magni vel ipsam. Similique asperiores at est amet, illo adipisci sunt excepturi molestias deleniti.
Harum itaque distinctio porro, explicabo quis ad culpa eveniet pariatur magni sint cum dolores. Sint, neque. Quisquam, corrupti voluptatibus aut quas neque ipsam dolor dolore aliquam molestiae deserunt delectus iure.
Quod in aliquam aperiam voluptatum nihil fuga et magnam necessitatibus? Cumque soluta veritatis quod fuga, corrupti accusantium, error porro odit natus ex, nostrum quidem animi? Earum debitis tempore qui rem.
Eius cum soluta, recusandae, laborum natus voluptatum autem ipsum minus maiores dolores placeat ipsa perspiciatis similique consequuntur? Voluptatum possimus, deserunt sed mollitia suscipit consectetur itaque rem magni praesentium temporibus incidunt.
Quibusdam soluta nemo saepe provident cum deserunt nihil eaque iusto. Vero dignissimos autem rem, molestias commodi dolores corporis minus placeat ad modi, architecto, aperiam eum error odio ea quam sed?
Quo facilis nesciunt assumenda. Iste atque quisquam animi quaerat enim molestiae, asperiores itaque blanditiis assumenda illo, eos minus quasi dolorum cum sit sapiente officiis quia accusantium ducimus. Fugit, veritatis vitae!
Voluptatum, architecto? Pariatur quo blanditiis sunt, quod voluptas omnis illo et consequuntur placeat qui laboriosam quia iste facilis labore tempora, aut voluptate at tempore expedita recusandae culpa sint deleniti. Quam!
Aliquid facilis qui molestias quod unde deserunt, harum officia voluptate, rem dolorem ipsa fuga eveniet a molestiae reprehenderit, cum vero consequuntur. Assumenda accusamus sequi error aut fugit quod, tempore quo?
Minus magni, consequuntur illo deleniti sit provident ipsum totam, quia ratione iste vitae cupiditate deserunt vero ea dicta. Et recusandae voluptatum mollitia, eius sed perspiciatis consequuntur nostrum consequatur eos laboriosam.
Ratione cumque tempora labore, fugiat accusamus, soluta similique aperiam officia sit eius enim beatae voluptas impedit mollitia quisquam. Blanditiis nulla molestias quae a animi asperiores, maiores adipisci ex libero veritatis.
Enim debitis culpa error officia consequuntur nihil, mollitia deleniti maiores dolores eaque nobis, animi sint laboriosam, harum fugiat quo cum quod repudiandae earum dolorum illo. Velit labore officiis pariatur quam.
Culpa tenetur dolor consequatur necessitatibus enim, doloremque ea quam, exercitationem praesentium repellendus earum, voluptatibus labore aliquam rem excepturi omnis in. Magnam, assumenda aut. Unde, laborum ad nulla totam officia molestiae.
Recusandae rerum voluptatem exercitationem voluptatibus omnis nihil id quidem ratione doloremque enim voluptas quaerat, velit maxime minus architecto quas. Earum doloribus alias dicta, quas saepe assumenda tenetur cum provident. Inventore.
Cum, vero. Sit dolores illum aliquam, voluptas autem officiis delectus libero animi, natus ad velit explicabo! Dicta fugit excepturi doloremque, molestiae laudantium amet molestias fuga quam, veniam magni quis minus.
Provident dolorum non nam, consequuntur ipsa repellat nemo voluptatum, laudantium unde animi aliquid! Nobis quis eius labore alias hic cum accusantium ipsam aperiam, autem sunt excepturi deserunt quas ipsa repellat?
Dolorum nobis facere vel provident optio consequuntur quae. Ipsam dolorem aut sapiente, illo veniam voluptas in ratione dolor molestias doloremque. Incidunt, quia iure aut porro voluptatem molestiae ad nisi. Amet!
Eaque, laudantium harum? Magnam similique quidem facere sint tempore, nulla reiciendis dolor ab debitis aspernatur non porro vel esse ipsum placeat iusto voluptatibus asperiores, odio animi! Dignissimos modi totam adipisci.
Minima praesentium impedit ullam, error vero incidunt quam facere doloremque ut corporis consectetur facilis! Vel consectetur quaerat temporibus animi. Asperiores rerum voluptate laborum quibusdam sunt eum aspernatur cumque, perspiciatis ratione.
Odit similique aut debitis pariatur, dignissimos voluptatibus harum incidunt consectetur? Quasi minima illum odio quibusdam ipsa impedit qui suscipit velit, facilis provident asperiores, odit quia sit vitae vero eveniet numquam?
Nesciunt iusto velit nam temporibus atque, vitae quae consequatur iure odio labore numquam libero expedita nobis sequi laborum? Totam tempora praesentium cupiditate unde voluptates! Ipsam in ea nulla expedita veritatis.
Eius voluptatum quas ratione accusamus at, quis veniam neque tenetur dolor libero, vel consectetur, molestias aliquid dolorum! Cumque veniam ex corporis quod ipsum. Eaque saepe recusandae assumenda officia voluptates aut?
Fugiat officia adipisci eius rerum molestiae. Accusantium dolore, maxime quasi natus sit quae? Quae ipsam ea hic inventore. Fugiat delectus voluptatibus asperiores maxime explicabo aliquam, consequatur sequi. Pariatur, similique fugit.
Quam animi harum, quibusdam ipsam totam reiciendis eaque incidunt rerum dolores assumenda ut repudiandae corporis nam nulla illum, accusantium asperiores beatae? Excepturi id dolorem provident repellat earum harum magni soluta!
Neque laboriosam voluptatem sunt dolorem reiciendis? Cum accusamus natus illum reiciendis cumque iusto repudiandae ut eveniet alias, in tenetur similique aspernatur, voluptas velit consequuntur sequi corrupti itaque sapiente quasi consequatur.
Dolor ullam expedita voluptas nemo cum. Aut adipisci delectus deserunt est ut placeat quod magni amet dolor deleniti itaque, modi voluptatibus perspiciatis architecto quaerat ratione quibusdam ex! Excepturi, itaque blanditiis.
Eum vel hic quas, neque deleniti veniam debitis iure quisquam numquam. Non nostrum voluptate voluptatibus similique itaque consequatur necessitatibus ipsam aspernatur, architecto perferendis fugit, porro laudantium esse officiis saepe nesciunt.
Expedita et maxime numquam nihil cum doloribus laborum ex voluptate nesciunt! Perspiciatis eum, molestiae enim impedit voluptas provident excepturi illum veniam? Ut dolor in assumenda, veniam voluptates ducimus ullam deleniti.
Adipisci, voluptate autem nobis sint deserunt harum necessitatibus commodi quis voluptates consectetur ad corporis magnam ea quisquam, earum molestiae hic eos nam quos fugit nemo fugiat! Eum labore reprehenderit autem!
Eaque blanditiis sequi quaerat quasi voluptatibus nulla saepe voluptatem error nisi, libero id, cumque, pariatur sunt illo qui beatae in laboriosam tenetur magni. Maxime velit temporibus ipsa placeat natus sit!
Delectus nostrum amet accusamus ullam vitae dolorem inventore vel. Quibusdam, sit! Tempore nisi voluptate illum alias accusantium? Doloribus, nulla quis, saepe ipsa quas, dicta laudantium officiis quae minima deserunt numquam.
Iusto illum molestiae perferendis natus hic quaerat veniam! Magni iusto maiores nulla, voluptate blanditiis repudiandae ducimus saepe quisquam beatae earum eligendi doloribus totam? Reprehenderit culpa odio nemo illo, dolor ipsa.
Nostrum expedita necessitatibus neque in temporibus, optio autem itaque? Omnis quae reprehenderit voluptatum voluptatibus, sint magnam dicta? Dignissimos odit doloribus fugit! Atque velit eum autem error? Sint quo quia dolore?
Modi eum dolorum voluptatibus ex aliquam rem corporis dignissimos distinctio cupiditate dolores dolore incidunt est necessitatibus possimus dolor beatae rerum, optio laboriosam, exercitationem hic dicta esse, nulla vero officia. Veritatis.
Cumque voluptatum perspiciatis atque officiis repellat error libero rerum architecto maxime odit assumenda mollitia quibusdam natus quam harum voluptates nesciunt in ipsam, quis, dolore, vitae delectus reiciendis quisquam molestias. Perspiciatis?
Fugit pariatur aliquid totam, beatae amet natus tempore nisi cum unde expedita animi quas, voluptatem repudiandae, ullam provident tempora adipisci! Reiciendis doloribus nostrum consequuntur quod placeat quam nemo at minima.
Nesciunt culpa temporibus quia praesentium veritatis, deleniti atque? Expedita at ipsam, nulla laudantium odit distinctio delectus nobis quas a obcaecati labore fugit maiores, amet vitae magnam numquam eveniet. Eligendi, ab?
Veniam voluptatum facere vitae numquam vero eum ab, quam voluptatem fugiat labore totam quo cumque, cum, ex unde possimus eaque. Repudiandae consectetur atque pariatur architecto alias odio veritatis natus culpa?
Eveniet, tempore dolor dolorum culpa magni ratione omnis? Excepturi sint nisi totam, aperiam inventore eveniet cupiditate vel incidunt nam porro quo natus nobis quos. Eligendi a dolore alias quam accusamus?
Praesentium debitis soluta repudiandae repellat accusantium, expedita harum! Quis mollitia eveniet possimus dolorem vitae eligendi asperiores optio, placeat praesentium ab provident aspernatur nobis fugit aut sed. Reiciendis doloremque laudantium deserunt!
Nesciunt animi esse veritatis, maxime, dignissimos facere quos aliquid deserunt illum enim expedita perferendis eos, corporis omnis molestiae nulla odio? Perferendis ad cupiditate mollitia sed dolor eius molestiae nobis quia.
Deserunt quaerat, nihil praesentium sint qui reiciendis enim odit atque veniam, commodi optio voluptatem ad fuga error iure saepe inventore vel harum perferendis. Consectetur natus autem, labore earum culpa enim.
Minima, quasi deserunt consequatur quis cupiditate ullam facere error, veniam velit ipsa molestiae. Assumenda nemo possimus accusamus nostrum totam dolor voluptatum quisquam tempora voluptatem iure corporis, molestias minus officiis esse.
Error nam mollitia rerum porro nesciunt corporis dolore provident nemo, illo tempora libero nobis ducimus, tenetur officia sequi commodi. Repellat sint, dolor deserunt provident mollitia quia expedita sunt omnis consectetur!
Eos et perferendis corrupti qui, accusantium ad deserunt, eligendi porro dolorem quibusdam, nulla voluptatibus ratione libero possimus unde voluptates odio ducimus veniam ipsum facere rerum? Blanditiis, iste perspiciatis. Cupiditate, dolor.
Corrupti veritatis odio ad alias accusamus quidem inventore, rerum vitae reprehenderit praesentium sed ea provident molestias, deleniti, fugiat impedit optio amet excepturi incidunt! Provident itaque delectus vitae? Obcaecati, velit aperiam.
Provident libero cum odit nihil, enim hic atque voluptatum corrupti beatae porro dolore id eveniet fugiat quo quasi facilis eius neque accusantium molestiae eum eos natus illo dolorem quisquam? Reiciendis!
Fuga quaerat sit ea commodi officiis cumque? Qui et accusamus voluptatem veritatis molestias asperiores, inventore ea illum amet praesentium id, facere ex ut nostrum deserunt quod excepturi quis voluptate hic?
Quod voluptatum deserunt soluta vel corporis alias. Non, aperiam officiis facilis ex, assumenda, nulla dolorum et ab id ea est provident! Voluptate beatae natus quod excepturi corporis commodi temporibus nemo.
Rerum dolore cum ipsa repellendus sunt, dolores libero a nulla ducimus illum consequatur facilis ipsam, eos officiis quae eum harum aliquid! Reiciendis enim unde inventore quasi cumque eveniet, fugit placeat!
Rem tempore tenetur dolores voluptate laudantium eius atque voluptatem est provident! Architecto, repellat corrupti! Aut adipisci delectus similique nulla, ipsam asperiores dolores placeat iusto est numquam quidem facere officia dolorem!
Delectus impedit quibusdam, praesentium ut neque odio nemo expedita, dignissimos, sapiente commodi distinctio placeat voluptatem? Ducimus quae accusamus, neque atque aut magnam praesentium reiciendis quisquam voluptates voluptate distinctio magni excepturi.
Maxime doloremque, harum quibusdam distinctio at rerum laborum asperiores aliquam consectetur laudantium reprehenderit quae dicta odit, ullam, qui nostrum deleniti cupiditate suscipit praesentium accusamus dolor. Reprehenderit neque repellendus iure cum.
Iste asperiores aut, nam enim nobis eius recusandae commodi harum at! Beatae aliquam eligendi quaerat ipsum in nisi rerum. Recusandae temporibus, voluptas minima quae veritatis sit ad sed. Atque, exercitationem!
Quibusdam consequatur, aliquam similique eum veritatis dolorem architecto, quas delectus repellendus quaerat nesciunt. Eos, possimus, omnis ea deleniti perspiciatis rem quisquam esse vel similique nesciunt nihil in sed quae animi?
A dolores corrupti, soluta, excepturi beatae accusamus consequatur tempora voluptas in quod repudiandae perferendis quisquam sit eum vero aspernatur illo itaque laborum similique placeat at. Aspernatur recusandae id rem quae!
Praesentium consequatur facilis aliquam doloribus at provident quibusdam, blanditiis eveniet odit aspernatur rem, commodi nam eligendi magni? Amet vitae mollitia, aspernatur animi sit illo odio ex! Quos doloribus aut cumque?
Aliquam quam autem veniam sapiente natus perspiciatis, tempora cupiditate, voluptatibus cumque saepe facere! Doloremque saepe mollitia quam pariatur hic, temporibus dicta iure recusandae, voluptatum ea aut. Blanditiis deserunt nihil incidunt.
Quam perferendis rerum, vitae delectus at molestiae accusamus, aspernatur, accusantium placeat aliquid vero. Corrupti unde fugiat quis quae numquam laboriosam. Accusamus reprehenderit maiores beatae dignissimos officia ad alias, esse ut!
Odio similique, cupiditate architecto numquam omnis suscipit rerum sed, soluta praesentium placeat officia pariatur eveniet minus aliquid veniam illum! Neque minima exercitationem rerum et aspernatur, fugiat necessitatibus eaque. Voluptas, odio.
Voluptatum dolores delectus tempora sed modi sit iste doloribus dolorem nostrum totam veniam libero repellendus cum cumque, debitis perspiciatis earum veritatis voluptates ad placeat autem minus similique distinctio! Soluta, vitae!
Adipisci perferendis consectetur dolore dolores tenetur, commodi earum ab inventore quae, repudiandae sapiente provident expedita illo, amet mollitia quasi recusandae itaque debitis eaque sed animi. Saepe sapiente quae ipsa harum!
Soluta atque reprehenderit repellat quae itaque sequi labore dolor. Nemo debitis, delectus aliquam, minima iure ullam veritatis, exercitationem suscipit quasi asperiores fugiat error dolorum sequi iste at. Omnis, officiis unde?
Beatae et corrupti quisquam voluptate dolor eos nulla dignissimos eum tenetur vitae magni quo ipsa exercitationem delectus expedita, magnam, eveniet illum? Placeat a adipisci sit temporibus id at error voluptas.
Quam nesciunt voluptatem iure culpa ex rerum obcaecati neque voluptatum maiores possimus qui eos saepe, a soluta molestiae quae aspernatur fugit! Harum optio alias neque? Doloribus eos architecto qui natus!
Possimus pariatur qui illum porro velit sequi dolor eaque, corporis odio tempora impedit non minima repellat perferendis eum atque recusandae quia exercitationem mollitia, quasi quam. Architecto sunt perspiciatis eveniet earum.
Optio, non? Eaque voluptates autem asperiores tenetur excepturi sunt ratione ipsa ipsum officia optio eos voluptatum culpa in, quae necessitatibus. Reprehenderit corrupti asperiores animi assumenda molestias neque. Similique, ducimus? Deleniti!
Repellat nisi unde quidem neque facilis. Est nisi tempore repudiandae, veniam cum fugit quo nihil laudantium numquam dolor ex quisquam fugiat perspiciatis deleniti impedit a, vitae dolorum labore quasi sint.
Eligendi, ipsa! Optio, accusamus. Mollitia soluta aliquam nesciunt sint ipsa ea facilis? Incidunt, tenetur repellat at distinctio ullam facere, reprehenderit animi laboriosam temporibus eaque quod tempora ex hic! Modi, dolorum.
Blanditiis laborum accusamus facere, fugiat minima minus qui explicabo nostrum unde natus, amet consequuntur vel odio ullam cum dolorum beatae ea quisquam omnis quia excepturi labore hic tempora cumque? Rerum.

</details>

3. Put cursor outside of viewport
4. Switch editors
5. It's jittery

![Animation](https://user-images.githubusercontent.com/9638156/121790334-05325280-cbe7-11eb-95cc-1a9068a8a5a7.gif)

A regression from **1.56.0**.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alexdima** [comment]
In a strange coincidence, I've also gotten #126178 recently. However I cannot reproduce. VS Code exposes a `revealRange` API to extensions, so I wonder if this reproduces when disabling extensions? Here I am switching between two word wrapped files and I've placed one cursor outside the viewport in one file, and one cursor at the top of the viewport in the other file:

https://user-images.githubusercontent.com/5047891/121918817-b398dd80-cd36-11eb-91c5-827184f91d72.mp4

**Comment by usernamehw** [comment]
It reproduces with all extensions disabled. Both cursors are out of viewport (at the end of the file).

**Comment by alexdima** [comment]
@usernamehw Are you perhaps also using markdown files? We figured this was the only missing step in https://github.com/microsoft/vscode/issues/126178

**Comment by usernamehw** [comment]
Yes. I think all of them were markdown.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/126178
