### ISSUE TITLE
Slow startup om m1 mac

### ISSUE THREAD

**Issue by Asim-A** [microsoft/vscode#126157]
Hi,
I have the MacBook Air 2020 8 gb m1 apple silicon. I experience that the startup time of vscode is inconsistent and in some cases rather slow. I have not done any proper start up time benchmarking, it seems like sometimes it starts up in 2 seconds, other time it uses 15+ seconds. All my tests are done with opening the same project and the computer does not have any additional load during the tests. It seems when it is the first time starting the app (after reboot, or waking up the pc) it is the slowest, but it is not limited to first time starting up. It happens also after some inactivity (~15 min).

Summary - slow startup occurs:
- after reboot
- inactivity
- if you close and re-open several times. By close I mean right click vscode icon in dock and press quit/exit. 

I would like to add that Jetbrains Intellij w/ project starts up faster than vscode for me on my M1 Mac. On my windows pc this does not happen, ever. Both are installed on the same drive. 

Additional Info:
- I have less extensions on my m1 mac than I have on my windows pc, and the ones I have on my mac are a subset of the ones I have on my windows pc. 
- My settings file is less than 30 lines on both computers. 
- I am opening the same project on vscode and intellij.
- I am using version: 1.53, january 2021

I am glad the vscode team made vscode available for apple silicon so fast, good job 🎉. Hopefully you could look into my issue and find something resolvable.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
