### ISSUE TITLE
Settings > Extensions - Dropdown/select shown instead of text entry field

### ISSUE THREAD

**Issue by patrickhlauke** [microsoft/vscode#126177]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.0-insider
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Install the Code Spell Checker extension
2. Choose "Add Item" (e.g. for excluded words)
3. Note that instead of a text field, a select/dropdown is shown instead

This used to work as expected in the past. Not sure at which point this behavior changed. This may be a change in how extensions are handled/supposed to expose their settings.

x-ref https://github.com/streetsidesoftware/vscode-spell-checker/issues/943

**Comment by patrickhlauke** [comment]
![The 'add item' form, showing a select rather than a text entry field](https://user-images.githubusercontent.com/895831/121802897-c9bf7480-cc36-11eb-9a68-e346db280d30.png)

**Comment by roblourens** [comment]
@rzhao271 seems that any string array is getting this now

**Comment by rzhao271** [comment]
Confirmed the bug occurs with `emmet.extensionsPath`.
