### ISSUE TITLE
Intergated terminal crash

### ISSUE THREAD

**Issue by xen** [microsoft/vscode#126124]
Issue Type: <b>Bug</b>

I want to open an integrated terminal window. 

1. Select menu View - Terminal or press Command + J
2. Terminal windows try to open for a sec and then closes.
3. Before windows closes, I see text `execvp(3) failed.: Permission denied`
4. A toaster show up with text `The terminal process "zsh '-l'" terminated with exit code: 1.`

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 56308f85-4b0b-488b-a47f-1645ae929235|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by xen** [comment]
Problem doesn't exist before I updated VS Code from previews version.

**Comment by kipz** [comment]
Same problem here but with Linux and Bash:

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic snap
```

**Comment by rattrayalex** [comment]
This may be a dup of https://github.com/microsoft/vscode/issues/126017

In my case the workaround was to `brew uninstall zsh`, though I hope VSCode fixes this problem.

**Comment by xen** [comment]
Unfortunately, I don't use brewed zsh. But in #126017 I found a solution. For anyone who will be concerned, put this lines in settings file:

```
"terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "/bin/zsh",
      "args": [
        "-l"
      ]
    }
  },
```
