### ISSUE TITLE
after update vscode,  Press the View Git History button and the result is blank

### ISSUE THREAD

**Issue by remainfox** [microsoft/vscode#126104]
Issue Type: <b>Bug</b>

Upgrade to the latest version of VS Code: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09 T17: caused. 354 z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node. Js: 14.16.0
V8:8.9.255.25 - electron. 0
OS: Windows_NT x64 10.0.18363

**As a result, vscode's git history is completely blank, and i can view the git log in xshell**

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-210-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.79GB free)|
|Process Argv|--crash-reporter-id ff76a998-0900-4a80-8831-51afa0b687a5|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: 虚拟机|
|OS|Linux x64 4.4.0-210-generic|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2 x 2592)|
|Memory (System)|2.92GB (0.26GB free)|
|VM|100%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.57.1
remote-ssh|ms-|0.65.7
githistory|don|0.6.16
cpptools|ms-|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the extension author
