### ISSUE TITLE
Loading Status for Terminal Tabs is Distracting

### ISSUE THREAD

**Issue by hjrdave** [microsoft/vscode#126197]
I really like the new Terminal Tab UI, but the loading indicator is very distracting when running programs like web pack watchers and linters during Create React App development. I suggest changing the animated icon to a non animated icon. I ended up having to turn the tabs off because it got to distracting.

**Comment by Tyriar** [comment]
We've always had the animating "Building" status bar item, do you hide that as well out of curiosity?

![image](https://user-images.githubusercontent.com/2193314/121880707-2e281580-ccc3-11eb-94ee-c86d029ed7d1.png)

**Comment by Tyriar** [comment]
@alexr00 maybe the terminal should have an option that disabled tab animations outright by removing ~spin?

**Comment by alexr00** [comment]
@Tyriar that sounds good to me. Could the terminal profiles be used for this? Should there be a task terminal profile that lets users specify their own icons? Or maybe just a setting to disable all terminal status?

**Comment by Tyriar** [comment]
Hiding all statuses is probably a bit far since it's the only place how some important information is shown like when the terminal is disconnected. Could potentially have a setting to map statuses to icon overrides but seems overkill to me.

**Comment by hjrdave** [comment]
I think if we have a less active loading indicator, then that might help. The endless spinner animation seems a little too much when we are dealing with linters and other terminal programs that are running throughout development. Maybe instead of a spinner we could have an ellipsis that bounces or something else less active. You can see some examples [here](https://nzbin.github.io/three-dots/).

**Comment by hjrdave** [comment]
> I think if we have a less active loading indicator, then that might help. The endless spinner animation seems a little too much when we are dealing with linters and other terminal programs that are running throughout development. Maybe instead of a spinner we could have an ellipsis that bounces or something else less active. You can see some examples [here](https://nzbin.github.io/three-dots/).

something like the dot-pulse or dot-flashing seem a lot less invasive

**Comment by Tyriar** [comment]
cc @misolori on loading indicator feedback

**Comment by hjrdave** [comment]
> > I think if we have a less active loading indicator, then that might help. The endless spinner animation seems a little too much when we are dealing with linters and other terminal programs that are running throughout development. Maybe instead of a spinner we could have an ellipsis that bounces or something else less active. You can see some examples [here](https://nzbin.github.io/three-dots/).
> 
> something like the dot-pulse or dot-flashing seem a lot less invasive
@misolori

**Comment by macromaniac** [comment]
>We've always had the animating "Building" status bar item, do you hide that as well out of curiosity?

Not OP, but I do actually lol (I use a different mechanism for building just so I don't get distracted by that wheel)

Eyes are drawn towards movement, this is why the carat blinks. Additionally the loading wheel gives me the expectation that something is going to happen, but nothing ever does. No clue how to fix it though, the loading wheel is a pretty universal indicator.

**Comment by hjrdave** [comment]
@macromaniac I think if the color and animation was more subtle it would help the issue a lot. The macOS terminal has a decent loading indicator.
![pic](https://user-images.githubusercontent.com/13001933/122108232-9240fb80-cde1-11eb-82fe-21dd3403971d.png)

**Comment by Tyriar** [comment]
Plan:

Introduce a new setting `terminal.integrated.tabs.enableAnimation` which is true by default, when false the `play` codicon will be used instead since the static loading codicon doesn't look good.
