### ISSUE TITLE
xsl auto-complete Unexpected characters “|”！

### ISSUE THREAD

**Issue by zwfengineer** [microsoft/vscode#126153]
Issue Type: <b>Bug</b>

自动补全
xs元素补全后多出一个“|”！

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.04GB free)|
|Process Argv|--crash-reporter-id dfa2d84b-c8c3-46d6-a664-77745fa2a592|
|Screen Reader|no|
|VM|60%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
vscode-language-pack-zh-hans|MS-|1.57.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
hexeditor|ms-|1.7.0
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-hexdump|sle|1.8.1
vscode-xsl-transform|Was|1.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

https://user-images.githubusercontent.com/33892516/121795358-823ee580-cc42-11eb-8f00-d010c22b343d.mp4

**Comment by pgfearo** [comment]
You just need the language extension for VS Code: [XSLT/XPATH for VS Code](https://marketplace.visualstudio.com/items?itemName=deltaxml.xslt-xpath) . (The built in XSL extension does not really do anything for XSLT apart from making it impossible to write an extension that can co-exist with other XML extensions)
