### ISSUE TITLE
No entiendo que paso

### ISSUE THREAD

**Issue by nana-html** [microsoft/vscode#126109]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.
no entiendo que es lo que pasa con el html.
cuando lo intento poner para utocompletar solo me queda de esta manera:
<html
y de la unica manera que puede autocompletarse es si le pongo > pero sigue quedando de otra forma
<html></html>
en ves del formato tradicion endonde pone body, head, etc.

**Comment by aeschli** [comment]
Sorry, I'm not sure what you mean. Can you add a small code sample, describe the steps, what you see and what you expect?
Also screenshots are helpful. Thanks!
