### ISSUE TITLE
Custom View Container not updating visibility

### ISSUE THREAD

**Issue by frantp** [microsoft/vscode#126175]
Issue Type: <b>Bug</b>

I have created a custom Tree View for my extension with the following when clause: `"resourceExtname == .custom-extension"`. Furthermore, I have included a custom View Container in the Activity Bar with this single view.

Based on this, the container should be displayed only when a file with the provided extension is open, and should update its visibility every time an item in the tabs above the editor is selected.

However, the visibility is only updated if the Explorer tab is active in the Activity Bar. If any other tab is active, such as SCM, nothing happens when I switch between tabs with different file extensions.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by frantp** [comment]
I think this is not a duplicate of the suggested issue. It's also happening using the Insiders build:

VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:14:11.473Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by sandy081** [comment]
It seems that when clause you are using is not meant for your purpose. I do not know if there is a context available for your scenario but you can create one like in our sample here - https://github.com/microsoft/vscode-extension-samples/blob/7b9a0a8c4c631e393862c3e767c7be26bb2233b2/tree-view-sample/src/jsonOutline.ts#L56-L56

**Comment by alexr00** [comment]
@frantp are you trying to make your view gain focus or just show in the activity bar? The `when` clause also only impacts whether the view container is added to the activity bar. It won't cause your view container to get focus when the `when` is true. To cause the view to get focus, you can use the extension API to call `executeCommand` with the id of your view(ex. `myViewId.focus`.

If you are trying to control whether your view container is added to the activity bar, then I would recommend making your own context as @sandy081 suggested.

**Comment by frantp** [comment]
Ok, I thought it would have the same behavior as in the "editor/title" contribution point. I'll have a look at the custom context, thank you both!
