### ISSUE TITLE
Missing confirmation prompt for opening links

### ISSUE THREAD

**Issue by KyleRAnderson** [microsoft/vscode#126108]
Issue Type: <b>Bug</b>

Prior to the June 2021 update, whenever I Ctrl+Clicked on links in the terminal (and elsewhere such as markdown files) for untrusted domains, I would be prompted to confirm that I wanted to open this link.

As of the June 2021 update, this no longer occurs. I know that Workspace Trust shipped in this iteration, however after reading its documentation I don't see an indication anywhere that this is expected behaviour for trusted workspaces.

## Steps to reproduce:
1. Open any VSCode Window.
1. Open the integrated terminal
1. Type a link to an untrusted domain into the terminal and then CTRL+Click it.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.82GB free)|
|Process Argv|-n --crash-reporter-id 732ba2ab-8246-4b39-aa91-70d245f12e42|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
todo-tree|Gru|0.0.213
latex-workshop|Jam|8.19.2
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.4.1
debugger-for-chrome|msj|4.12.12
vscode-commons|red|0.0.6
vscode-yaml|red|0.19.2
slim|sia|0.1.2
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by levi-tate** [comment]
Following this. I've been using the popup to copy URLs instead of opening them in the default browser, and it doesn't look like this is possible anymore.

**Comment by JacksonKearl** [comment]
Yes, this is by design but it was a small change in a busy iteration and I forgot to add it to release notes. To address @levi-tate's feedback we could perhaps have a setting to enable it in trusted workspaces. 

See: https://github.com/microsoft/vscode/issues/124325

**Comment by chupocro** [comment]
I was using that option not to launch the links in the default browser but now that isn't anymore possible.

I have described the problem [here](https://community.platformio.org/t/vs-code-copy-link-to-clipboard-option-after-ctrl-click-removed/21978) in the PlatformIO forum.

**Comment by JacksonKearl** [comment]
Added the config `workbench.trustedDomains.promptInTrustedWorkspace`, defaults to false, when true domain trust prompts will appear even in trusted workspaces.
