### ISSUE TITLE
Launch VSCode into devcontainer session

### ISSUE THREAD

**Issue by BitPatty** [microsoft/vscode#126132]
([Repost from StackOverflow](https://stackoverflow.com/questions/67771546/launch-vscode-into-devcontainer-session))

It appears that the only way to run devcontainers locally is by following these steps:

- Open your codebase in VSCode
- Reopen VSCode / The application in a devcontainer via command or the "Reopen in Container" popup

I would like to skip step 1 and launch VSCode directly into a container session. Is this currently possible?

**Comment by BitPatty** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [vscode crash and logout on ubuntu when starting devcontainer (#118736)](https://www.github.com/microsoft/vscode/issues/118736)

No

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/4684
