### ISSUE TITLE
Command shortcuts on the welcome screen need ux love

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12617]
Close all vscode windows, notice we now show shortcuts on the emtpy editor area.
When the screen is small these shorcuts are covering the vscode logo.

IMHO this looks out of style and needs more ux love.
Why was this not discussed in a UX meeting since this feels like a perfect topic for those?

Not sure if this is our plan on how to make vscode more discoverable or just an exploration to get feedback. Either way I give it a -1 since it is ruining the minimalistic feel of vscode

ping @stevencl @bgashler1 @bpasero @joaomoreno @chrisdias @seanmcbreen 

![screen shot 2016-09-26 at 10 28 18](https://cloud.githubusercontent.com/assets/1926584/18827648/35536356-83d4-11e6-86d7-7a1639a2d1f8.png)
![screen shot 2016-09-26 at 10 29 14](https://cloud.githubusercontent.com/assets/1926584/18827649/35536ee6-83d4-11e6-8707-715bad1307fd.png)

**Comment by waderyan** [comment]
Just my $0.02.

I actually like the single pro tip concept from Atom. IMO aesthetically better than the multiple tips (inspired by WebStorm). 

![image](https://cloud.githubusercontent.com/assets/2449568/18844894/284e860e-83d4-11e6-9cb1-b6f684c8a3ce.png)

**Comment by seanmcbreen** [comment]
Hi,

This is the start of a set of experiments to increase discoverability of key features.  We looked at WebStorm, Sublime, Atom and others - this is closest in experience to WebStorm.  We will leverage data for the users who get this and see if it in fact helps them use some of the key features.  This will help us determine if we should do more or less in this area.

There are four variations we will test:

1. Open with untitled file, no panel open (as-is in 1.5)
2. Open with untitled file, Explorer open
3. Open without any file open, add watermarks, no panel open
4. Open without any file open, add watermarks, Explorer open

The main use case is for the new user who installs the product for the first time.  But this is also relevant for existing/established users as many users are not finding critical features in the product and simply don't know where to start.  

The only reason this missed the UX meeting is that it came in a little late - thats my fault.  Brad and I will bring in a discussion this week.  I agree it could do with a little more polish and Brad is working on that now.

Sean

**Comment by isidorn** [comment]
@seanmcbreen I see the reasoning behind this but please make this look nice or do not ship it. 
I agree with @waderyan that Atom is doing this better with one random tip at a time which is nicely styled. What is the upside of showing multiple of these instead of just showing a random one?
We can all this discuss this on wednesday but then there will be little time to implement all this so consider moving this to october imho.

**Comment by chrmarti** [comment]
Having this in will allow us to ship a refined (and/or alternate) version of it in October based on the results of the experiment. Deferring it would just let us continue to go oblivious to the effect this particular approach has.

There are other approaches (as you've mentioned) and we might just let them compete against this one in the October release using experiments to understand what our users prefer.

**Comment by chrisdias** [comment]
It feels like i have a file open that isn't mine. I want to copy/paste it and the close it.  Atom's hints are grey, they blend into the tool while these look like they are a file

The text is not centered horizontally or vertically, why not?

![image](https://cloud.githubusercontent.com/assets/1487073/18849600/8ac5e35e-83e8-11e6-8460-c0bafd81d809.png)

Would some sort of title help explain what these things are?  Maybe a "Tips and Tricks"?  Or something more hip?

**Comment by seanmcbreen** [comment]
Hey all @bgashler1 is working on this and no we should not ship if it does not look good.  We have discussed alignment, font weight, improving separation, ...  

I think we will get there it's pri0 for Brad.  Lets see what he comes up with.   For existing users one option we will also be considering is the ability to dismiss.  But we need to get started first and find out how this assists users or not.

**Comment by bgashler1** [comment]
Addressed in #12704
