### ISSUE TITLE
Letter spacing is weird

### ISSUE THREAD

**Issue by MohamedAliRashad** [microsoft/vscode#126107]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.57
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1.  All i did was adding the Arabic font to the system (i followed this [tutorial](https://discourse.ubuntu.com/t/request-better-arabic-font-for-ubuntu-20-04/14573)) 

![Screenshot from 2021-06-12 02-06-24](https://user-images.githubusercontent.com/26205298/121758709-cf2b9a80-cb22-11eb-85b5-d01a76b1d4ab.png)

The problem doesn't show up on my system terminal

**Comment by ArturoDent** [comment]
A possible fix reported elsewhere is to set `Terminal > Integrated: Letter Spacing` to `1`.
