### ISSUE TITLE
New terminal tabs: name is reset once you run a command

### ISSUE THREAD

**Issue by domokos-lorant** [microsoft/vscode#126145]
Issue Type: <b>Bug</b>

I am renaming a terminal tab to "Orders". I run docker build, during which time the terminal tab name changes to docker and once docker is done, the terminal tab name ends up being "bash" again. I am using WSL2.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (45.83GB free)|
|Process Argv|--crash-reporter-id 02afb505-c2ba-4d25-b913-26473b29dd6a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (4 x 2304)|
|Memory (System)|7.77GB (0.90GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
remote-wsl|ms-|0.56.5
vs-keybindings|ms-|0.2.1
debugger-for-chrome|msj|4.12.12
ejs-language-support|Qas|0.0.1
vscode-eslint|dba|2.1.22
gitlens|eam|11.4.1
vscode-graphql|Gra|0.3.16
auto-insert-semicolon|liz|0.0.2
vscode-docker|ms-|1.13.0
vs-code-prettier-eslint|rve|3.0.4
vscode-surround|yat|1.1.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by meganrogge** [comment]
I can't reproduce this issue. What are your settings?
