### ISSUE TITLE
Can't jump to the line when Ctrl+Click a normal file path in the integrated terminal

### ISSUE THREAD

**Issue by yaoxinliu** [microsoft/vscode#126138]
Issue Type: <b>Bug</b>

My vscode is started from wsl2. In the previous versions of vscode, I can jump to the correct line of the target file in the editor.

However, after I upgraded vscode to 1.57.0, Ctrl+Clicking a normal file path in the integrated terminal no longer jumps and reports "No matching results".

I noted that, after I ctrl+clicked the link, but before jumping, the normal file path, say `/path/to/my/file:123:456`, was implicitly changed to `\path\to\my\file:123:456`. If I manually change `\path\to\my\file:123:456` back to `/path/to/my/file:123:456` in the error-report's edit-box and press enter, jumping works as expected.

So, I think this is a regression bug in 1.57.0.

**Is there a workaround to prevent vscode implicitly convert the path separator from `/` to `\`?**

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (50.66GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/data/media_build/cloud_recording_sdk/third_party/include/utl --remote=wsl+Ubuntu-20.04 --crash-reporter-id f30bd3cd-39f8-4267-9496-2840bf71f95c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|Memory (System)|50.14GB (47.60GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
jinja|who|0.0.8
go-outliner|766|0.1.20
python-extension-pack|don|1.6.0
go|gol|0.25.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
cpptools|ms-|1.4.1
go-doc|msy|1.0.1
python|tht|0.2.3
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

![vscode-bug](https://user-images.githubusercontent.com/34788154/121782926-9b15af80-cbde-11eb-8095-49c79eae8ab9.png)

**Comment by flinkk** [comment]
This also happens to me when I remote from Linux to a Windows box via Remote SSH. A Ctrl+Click on 'c:\temp\t.txt:3:2' opens a file dialog with the correctly parsed line and column (like above). But confirming the file does not jump to line:column as expected. 

When I remote from Linux to another Linux, the dialog does not show and line:column is correctly jumped-to
