### ISSUE TITLE
Image-preview is not working with Remote-SSH

### ISSUE THREAD

**Issue by cg31** [microsoft/vscode#126135]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Ctrl-Alt-P -> Remote-SSH: Connect to host... (Update: this is actually working, the problem happens when opening remote with command line, see below)
2. Open a folder with PNG images on a Linux server
3. Click a PNG image
4. A message will show "An error occured while loading the image"

Notes:

1. If the PNG image are copied to local, vscode will show it. So PNG image is valid
2. Before Version: 1.57.0, vscode could show PNG on remote host correctly

**Comment by mjbvz** [comment]
Seems to work fine for me going from windows to Ubuntu:

<img width="920" alt="Screen Shot 2021-06-15 at 4 24 39 PM" src="https://user-images.githubusercontent.com/12821956/122135884-40ef3700-cdf6-11eb-9ea8-ca8667cc7286.png">


What specific type if linux server are you connecting to?

**Comment by cg31** [comment]
The remote machine is running  Ubuntu 20.04.2 LTS.

**Comment by cg31** [comment]
Now it seems the issue is caused by how I open the remote project.

It works if I use 'Ctrl-Alt-P -> Remote-SSH: Connect to host'.

But it I open a remote project in command line, using --folder-uri:
code --folder-uri vscode-remote://ssh-remote+cg31@127.0.0.1/home/cg31/test
(it is WSL, with ssh server installed)

the image can't be opened.

So the behavior of '--folder-uri' has changed.

**Comment by nachifur** [comment]
I have a similar problem.

**Comment by YEFANBOSS** [comment]
I have a similar problem in 1.57.0.
1、Open a project inside WSL2
2、Open an image
3、Error appears (An error occured while loading the image)
![image_error](https://user-images.githubusercontent.com/43435013/123222284-5d7c2500-d502-11eb-9d7f-ce31984a93f1.png)
@mjbvz

**Comment by mjbvz** [comment]
What about in VS Code insiders?

**Comment by cg31** [comment]
I found a solution (or workaround).

When I use this command to open remote project
code --folder-uri vscode-remote://ssh-remote+cg31@127.0.0.1/home/cg31/test

the image will be failed to open.

But, if I omit user ID, and open it like this:
code --folder-uri vscode-remote://ssh-remote+127.0.0.1/home/cg31/test

it will work. It seems to do with ssh authentication.
