### ISSUE TITLE
vs code crashed when open a minify file

### ISSUE THREAD

**Issue by javidabedian** [microsoft/vscode#126122]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57
- OS Version: windows 10 build x64 19042.928

When I opened a minify css or js file , vs code crashed
I got this  message as error : Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.
and my cpu useage go to 80% and ram useage go to 50% when vs code open minify files ( cpu i7 , ram 16GB )
I set Max Tokenization Length setting to 20000 and didnt work

**Comment by IllusionMH** [comment]
/needsMoreInfo

From description it's not clear - did it crashed and whole app is gone or you just get notification each time you open that file?

Later is not crash - it's just editor opted out from highlighting extremely long lines.
What is file size? Because 20k doesn't looks like big value for minified bundle.

**Comment by javidabedian** [comment]
> /needsMoreInfo
> 
> From description it's not clear - did it crashed and whole app is gone or you just get notification each time you open that file?
> 
> Later is not crash - it's just editor opted out from highlighting extremely long lines.
> What is file size? Because 20k doesn't looks like big value for minified bundle.

The editor still open but error message show and other extentions like live server and live sass cant work any more
I must exit from the vscode and re-open the workspace again to active those extentions

I tested bootstrap.min.css and other minify files , when I opened that minify files in the editor that problem happen again

**Comment by aeschli** [comment]
Any chance you can share that file for us to reproduce?

**Comment by javidabedian** [comment]
> Any chance you can share that file for us to reproduce?

I tested this file :

https://raw.githubusercontent.com/twbs/bootstrap/main/dist/css/bootstrap.min.css

**Comment by aeschli** [comment]
I'm not able to reproduce
- open https://github.com/twbs/bootstrap by using `Open Remote Repository`
- open `bootstrap.min.css` in the editor
- edior opens, shows notification `Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.`
- do some code completion at the top of the file. Mote that the css language service is still running

@javidabedian It's possible that one the extension crashes with the large file. To verify run with all extensions disabled (`Reload with Extensions Disabled`). If this solves the problem , then you can use the `Extension Bisect` command to find out which extension is the cause.

**Comment by javidabedian** [comment]
@aeschli Thanks for your guide , I think that was for conflict between code completion extention and built-in code completion from vscode , I disabled that extention and now working fine

**Comment by aeschli** [comment]
Thanks for reporting back!
