### ISSUE TITLE
Recursive types highlight error unless narrowed down by using `as` keyword

### ISSUE THREAD

**Issue by khooz** [microsoft/vscode#126128]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042
- Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
- Date: 2021-06-09T17:18:42.354Z
- Electron: 12.0.9
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0

Steps to Reproduce:

1. Write a recursive interface, eg.
```typescript
interface SomeType {
   key: string,
   value: string
}

interface RecursiveType {
   [x : string] : RecursiveType | SomeType
}
```
2. Define a value of the type:
```typescript
const test : RecursiveType = {
   testKeyOne: {
      nestedOne: {
         key: 'test',
         value: 'test'
      }
   },
   testKeyTwo: {
      nestedOne: {
         nestedTwo: {
            key: 'test',
            value: 'test'
         }
      }
   }
};
```
3. Use the variable
```typescript
test.testKeyOne.nestedOne.key;
/* red squiggly line stating:
Property 'nestedOne' does not exist on type 'RecursiveType | SomeType'.
  Property 'nestedOne' does not exist on type 'SomeType'.ts(2339)
*/

(test.testKeyTwo as RecursiveType).nestedOne.nestedTwo.key;
/*
red squiggly line shifts a level deeper stating:
Property 'nestedTwo' does not exist on type 'RecursiveType | SomeType'.
  Property 'nestedTwo' does not exist on type 'SomeType'.ts(2339)
*/

((test.testKeyTwo as RecursiveType).nestedOne as RecuriveType).nestedTwo.key;
/*
red squiggly line goes away and understands that nestedTwo is of type SomeType
*/
```

I am not sure if this is the limitation of Typescript itself since documentation uses this kind of recursion and the code works without narrowing; but the error highlighting is a nuisance when the code is right. Maybe resolution ordering is the issue at hand, instead of going deep, it should rise up from the deepest possibility.

### Screenshot

![image](https://user-images.githubusercontent.com/8382714/121773795-7cd69200-cb93-11eb-8790-a642b4555212.png)

**Comment by IllusionMH** [comment]
This is not an issue with editor itself so should be reported in VS Code repo.

Snd it's also works as expected in TS - your types declared that it's a union and you are trying to access property that may not be available on one of union members. See https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types

**Comment by mjbvz** [comment]
Thanks @IllusionMH 

Closing this as a question / upstream
