### ISSUE TITLE
Color theme "Monokai" version light

### ISSUE THREAD

**Issue by kythuatwebso** [microsoft/vscode#126112]
Hello,

vscode have features auto switch theme "light" and "dark" is perfect. but when use monokai theme is only dark.
Please can add color Monokai for light on vscode :)

Thanks !

![image](https://user-images.githubusercontent.com/57938377/121763659-138d5980-cb68-11eb-94e6-5eb27c350c92.png)

**Comment by AnsonH** [comment]
There are existing Monokai Light color schemes available in the Marketplace

[Monokai Light](https://marketplace.visualstudio.com/items?itemName=zoxon.monokai-light)

**Comment by kythuatwebso** [comment]
> There are existing Monokai Light color schemes available in the Marketplace
> 
> [Monokai Light](https://marketplace.visualstudio.com/items?itemName=zoxon.monokai-light)

I using this theme, but it bug 

![image](https://user-images.githubusercontent.com/57938377/121828872-1e242c00-cceb-11eb-8f11-5b482d5320ef.png)

**Comment by aeschli** [comment]
Sorry, we don't want t add another built-in theme. 
Maybe file an issue against Monokai Light?
