### ISSUE TITLE
Java: toString is not... auto completed

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#12619]
Hi,

- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Java file which has `toString` phrase.
2. Try auto completion, that phrase is... not in the list  `:-(`

Would you please check?

Thank you,

**Comment by joaomoreno** [comment]
Code has no native support for Java. It comes through extensions. Here's one for example: https://marketplace.visualstudio.com/items?itemName=redhat.java

Have you given it a try? Any issues related to it should be filed in the extension's repository. Previous example: https://github.com/gorkem/vscode-java/issues

**Comment by mac-pro** [comment]
Thanks,

I used some other Linux editors like Gedit, Kate, Geany... They _all_ had options to puts _all_ the phrases in the file into auto-completion list. That's why I thought it was weird when I found no `toString` in VSC auto-completion list.

I'll file new issue...
