### ISSUE TITLE
Unable to update deb 

### ISSUE THREAD

**Issue by rdgh8** [microsoft/vscode#126103]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

[See video](https://imgur.com/a/P7id51I)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (1.01GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6b82ee80-278d-4af8-8882-ac11417c1eeb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
crystal-lang|cry|0.8.2
nim|kos|0.6.6
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30307505
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by tristan957** [comment]
What issue are you seeing? You gave 0 details.

**Comment by rdgh8** [comment]
Despite VS Code showing an update available, I am unable to update it using the .deb downloaded from the website. It just shows that I can uninstall or downgrade. The version name on the deb is higher than the version I have installed.

**Comment by rdgh8** [comment]
Fixed on the latest update
