### ISSUE TITLE
macOS TouchBar Button Swapped

### ISSUE THREAD

**Issue by 0f3eacd3** [microsoft/vscode#126195]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Tap icon on the right, code will run w/o debugger (tested for Python, Java and LLDB)
2. Tap icon on the left, code will run w/ debugger

Looks like the "Start Debugging" button and "Run Without Debugging" button swapped in latest version, but the icon apperance didn't swap.

![image](https://user-images.githubusercontent.com/71917767/121836165-d4562a00-cc87-11eb-83c0-8286b44f5af0.png)

Context: https://github.com/vadimcn/vscode-lldb/issues/462

**Comment by weinand** [comment]
@isidorn I can reproduce this issue, so the buttons seem to be swapped.

**Comment by weinand** [comment]
Actually the contents of the icons got updated:
the icon "continue-without-debugging-tb.png" became:
![run-with-debugging-tb](https://user-images.githubusercontent.com/1898161/121920140-0921ba00-cd38-11eb-8d9e-677868904e88.png)
which is clearly wrong.

**Comment by weinand** [comment]
@isidorn I've renamed the icon to "run-with-debugging-tb.png" and fixed the code referencing the icons.

@0f3eacd3 you can try the fix in the next Insider build.

**Comment by isidorn** [comment]
@weinand thanks for fixing this 👏 
fyi @misolori since this was probably caused by accident when we added color to our touch bar icons

**Comment by misolori** [comment]
Thank you, @weinand!
