### ISSUE TITLE
High CPU usage when settings UI is opened

### ISSUE THREAD

**Issue by psycha0s** [microsoft/vscode#126126]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 10 Pro Version 20H2 (OS Build 19042.1052)

As you can see in the attached screenshot, as soon as I open the Settings UI, one of my CPU cores is always busy doing something. This activity migrates from core to core but it never stops. It's totally unusable since I can't even scroll this page without huge lags.

Steps to Reproduce:

1. Open settings UI
2. Look at the CPU usage
3. Try to scroll the page, it will scroll with lags

[![Screenshot-1.png](https://i.postimg.cc/yYSxJTgB/Screenshot-1.png)](https://postimg.cc/N5BBSmkP)

**Comment by roblourens** [comment]
Which process is it? Also can you get a perf trace? Help > Toggle Developer Tools > Performance. Record, repro the issue, stop recording, save and upload it here.

**Comment by psycha0s** [comment]
@roblourens this is one of vscode threads. 7.8% for a 12-core cpu means one core is fully loaded:
![image](https://user-images.githubusercontent.com/8014057/122097444-5aa17600-ce18-11eb-9386-4ee242eb0c99.png)

Here is the profile of the issue:
[Profile-20210615T202214.zip](https://github.com/microsoft/vscode/files/6657555/Profile-20210615T202214.zip)

**Comment by roblourens** [comment]
Hey @sandy081 any idea what is going on here? This is repeated many times

![image](https://user-images.githubusercontent.com/323878/122110000-e0023780-cdd2-11eb-9f8a-93438aa10012.png)

Rendering the settings tree is kinda slow due to dynamic heights in the list, we know that, but it seems like we are repeating `deregisterConfigurations`/`registerConfigurations` over and over, what does that mean?

**Comment by sandy081** [comment]
This is coming from `_refreshPlatformConfig` - which is to update http configurations scopes properly. It shall be called only once when extension host is getting started in the window - 
https://github.com/microsoft/vscode/blob/a36051efae287fb45342b053359fc3dd5c331767/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L326-L326

**Comment by psycha0s** [comment]
I've already provided information you asked about. Can I provide something else?

**Comment by Tyriar** [comment]
I don't see `_refreshPlatformConfig` causing lag for me, it's the list view rerendering that's causing the lag on mine:

![image](https://user-images.githubusercontent.com/2193314/123421246-74a62b80-d571-11eb-8df0-3644fdb35a00.png)

As for refreshing the config being slow (which should only happen when profiles change), I think supporting targeted config updating would cover that: https://github.com/microsoft/vscode/issues/120940

**Comment by psycha0s** [comment]
Okay, it seems like I found what causes this issue on my machine. I have [MSYS2 ](https://www.msys2.org/)installed to `D:\Programs\msys64`. I set up my terminal to use bash from msys2 environment like this:

```
	"terminal.integrated.profiles.windows": {
		"MinGW64": {
			"path": [
				"D:/programs/msys64/msys2_shell.cmd"
			],
			"args": ["-defterm", "-no-start", "-mingw64"]
		},
	},
	"terminal.integrated.defaultProfile.windows": "MinGW64",
```

As soon as I comment out or remove these lines everything goes back to normal. I also noticed, that it affects not only the settings ui, but all comboboxes in vscode. They close automatically after a random delay (0-500ms), like it's related to the caret flashing period or something. I hope this information will shed some light on this issue for you guys.

**Comment by thanhph111** [comment]
@psycha0s I had the same issue but today I checked and it's already gone. Can you confirm it? This is my version info:
```
Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by sandy081** [comment]
@Tyriar Added support for #120940. Please let me know if there is anything else needed.

**Comment by vxna** [comment]
> Okay, it seems like I found what causes this issue on my machine. I have [MSYS2 ](https://www.msys2.org/)installed to `D:\Programs\msys64`. I set up my terminal to use bash from msys2 environment like this:
> 
> ```
> 	"terminal.integrated.profiles.windows": {
> 		"MinGW64": {
> 			"path": [
> 				"D:/programs/msys64/msys2_shell.cmd"
> 			],
> 			"args": ["-defterm", "-no-start", "-mingw64"]
> 		},
> 	},
> 	"terminal.integrated.defaultProfile.windows": "MinGW64",
> ```
> 
> As soon as I comment out or remove these lines everything goes back to normal. I also noticed, that it affects not only the settings ui, but all comboboxes in vscode. They close automatically after a random delay (0-500ms), like it's related to the caret flashing period or something. I hope this information will shed some light on this issue for you guys.

I have the exact same setup and just reproduced all this (and `_refreshPlatformConfig` causes huge lag, indeed). Commenting out the profile fixes the issue.
```
 "terminal.integrated.profiles.windows": {
    // "zsh": {
    //   "path": "C:/tools/msys64/usr/bin/bash.exe"
    // },
  },
```

Although I can say this is not only about Settings UI. VS Code itself goes unresponsive after some hours and also causes https://github.com/microsoft/vscode-eslint/issues/1337. As of myself, I never have seen all this prior to 1.60.1 update.

Version: 1.60.1 (system setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment]
Unassigning myself from this, if it's still a performance issue it's related to either the settings editor consuming events wrong and updating the whole list, the list being slow, or the config service not firing lighter weight events saying that only a small amount of configs changed.

**Comment by rzhao271** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/136509
@psycha0s are you still seeing the issue on the latest Stable? (v1.63)

**Comment by psycha0s** [comment]
@rzhao271 I restored the terminal settings that caused the issue for me earlier and tried it. It looks like the issue is gone, everything is smooth in the settings UI.
