### ISSUE TITLE
Command to expand/focus open file in explorer

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#126121]
I could not find that specific command, while auto-reveal would do the trick, I would like to keep it off and when I need the specific file's siblings call a command that jumps to the file in the explorer and expands the tree.

**Comment by ArturoDent** [comment]
I made these keybindings, is one of these what you want:

```jsonc
	{
		"key": "alt+r",     // whatever keybinding you want
		"command": "workbench.files.action.showActiveFileInExplorer"
	},
	{
		"key": "alt+e",
		"command": "revealInExplorer"
	}
```

To tell you the truth I don't know the difference between them...

**Comment by muuvmuuv** [comment]
@ArturoDent YES! Thanks, `workbench.files.action.showActiveFileInExplorer` did it. :)
