### ISSUE TITLE
Terminal background color looks broken

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#126100]
<img width="756" alt="CleanShot 2021-06-11 at 16 09 57@2x" src="https://user-images.githubusercontent.com/35271042/121756605-8eeefc80-cacf-11eb-921a-e11711edc7a7.png">

It's a lot more noticeable in other themes:

<img width="533" alt="CleanShot 2021-06-11 at 16 10 56@2x" src="https://user-images.githubusercontent.com/35271042/121756623-a0d09f80-cacf-11eb-909a-d5a3529e2475.png">

Version: 1.58.0-insider (Universal)
Commit: 012b14606f75ec4fed90d7ab4154f63dffab9503
Date: 2021-06-11T05:12:17.675Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

**Comment by ArturoDent** [comment]
Same issue?  see https://github.com/microsoft/vscode/issues/126014

**Comment by tridlever** [comment]
This also happens in previous versions when GPU acceleration was implemented. It's when `terminal.integrated.gpuAcceleration` is `auto` or `on`. It doesn't respect the alpha parameter assigned in the `terminal.background`.

`"terminal.integrated.gpuAcceleration": "auto" or "on"`

![terminal_background_auto_on](https://user-images.githubusercontent.com/20564316/121783469-c5368580-cb7c-11eb-93f2-fd7838f8e829.png)

`"terminal.integrated.gpuAcceleration": "off"`

![terminal_background_off](https://user-images.githubusercontent.com/20564316/121785319-282d1a00-cb87-11eb-9a22-a6089e7abdf1.png)
