### ISSUE TITLE
Badge on problems view is hiding the icon

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#12618]
![image](https://cloud.githubusercontent.com/assets/10746682/18829078/f679350a-83da-11e6-8a10-450395dc7d4c.png)

**Comment by isidorn** [comment]
This is due to the fact that we are using smaller icons than in the viewlet.
The badge should not change size since it should be consistent with that we have in the viewlets

Assigning this to @bgashler1 to take into account the badge size when designing the icons

**Comment by isidorn** [comment]
No longer applicable, we have removed the panel icons from the activity bar
