### ISSUE TITLE
Make terminal instances animate smoothly when resizing

### ISSUE THREAD

**Issue by newtykins** [microsoft/vscode#126142]
As you can see, when you resize the terminal the content jumps around a lot whereas the resizing animation is incredibly smooth. Pairing this with the other smooth animations is mildly infuriating. It's not that big of a deal, but it would be nice if we could make the animation for re-rendering the terminal a lot smoother to fit with all of the other choices we have been provided.

![GIF](https://user-images.githubusercontent.com/19301186/121786495-05672980-cbb8-11eb-83ee-296d45629c9b.gif)

**Comment by Tyriar** [comment]
The slow rendering is actually a feature because if we re-rendered the terminal on each frame it would slow the framerate down, potentially a lot with a full terminal buffer.
