### ISSUE TITLE
vscode crached on ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by miladezzat** [microsoft/vscode#126168]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
`
- OS Version: ` ubuntu 20.04.2 LTS`

Steps to Reproduce:
1. when I open vscode my laptop fane speed and laptop crashed, I can do anything without power off my laptop by power button

@vscode-triage-bot

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by miladezzat** [comment]
The same issue, I don't know why my laptop crashed when I used vscode. @bpasero

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by miladezzat** [comment]
Still the same issue, I don't know why?. But I think there are some updates in vscode that made this issue
I changed my OS and now it's working well.
Thanks for your time @bpasero
