### ISSUE TITLE
Version 1.56 & above freezes after launching in Linux mint 20 

### ISSUE THREAD

**Issue by DaniyalDolare** [microsoft/vscode#126174]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code_1.56.2-1620838498_amd64
- OS Version: Linux mint 20 

Steps to Reproduce:

1. Launching vs code from software menu.
2. App opens but gets freezed.
3. The window is no longer responding occurs after some time.
![Screenshot from 2021-06-13 20-54-33](https://user-images.githubusercontent.com/61370392/121813516-ef299e00-cc89-11eb-84e4-bdea0a9d7bd8.png)

Below is the output of  `code --verbose`
[output.log](https://github.com/microsoft/vscode/files/6644179/output.log)

**Comment by prashanthwagle** [comment]
Did you try opening after disabling the extensions? You cann navigate to ~/.vscode and move the extensions folder to somewhere else (instead of deleting) and open VSCode after that. If the problem doesn't get solved, replace the extensions folder as it may not be the fault of one of your extensions.

**Comment by DaniyalDolare** [comment]
Not working even after disabling extensions...already mentioned above in issue

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DaniyalDolare** [comment]
Same issue with VS Code insiders....

- VS Code Version: 1.58.0-insider
- OS Version: Linux mint 20

Steps to Reproduce:
1. Launching VS code insiders from software menu.
2. App opens but gets freezed.
3. The window is no longer responding occurs after some time.

The output of `code-insiders --verbose ` is
[insiders.log](https://github.com/microsoft/vscode/files/6646949/insiders.log)

**Comment by DaniyalDolare** [comment]
I just found out that when I use --disable-gpu flag while opening vs code from terminal it works , both vs code and insiders version works.
So is this gpu driver issue?

**Comment by DaniyalDolare** [comment]
Any fix on this issue?

**Comment by deepak1556** [comment]
Are you running on any vm ?

**Comment by DaniyalDolare** [comment]
No. It's dual boot system (linux mint 20 + windows 10)

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash dumps.

Based on the log pasted above, the gpu process is crashing due to out of memory.

**Comment by DaniyalDolare** [comment]
@deepak1556  Here are the dump files generated after `code --crash-reporter-directory <absolute-path>`
[errorlogs.zip](https://github.com/microsoft/vscode/files/6683945/errorlogs.zip)

**Comment by DaniyalDolare** [comment]
Yeah the issue has been resolved.
