### ISSUE TITLE
Requires support for extensions grouping (需要支持扩展插件编组的功能)

### ISSUE THREAD

**Issue by LadenxxxxD** [microsoft/vscode#126140]
当我使用VSCode在多种语言的项目中切换着开发，一个个启用和禁用插件太过于麻烦，希望可以提供插件编组的功能，方便一键启用一组扩展插件。

When I use VSCode to switch between projects in multiple languages, it's too tedious to enable and disable plugins one by one, so I hope to provide a group of plugins to enable a group of extensions with one click.

**Comment by au-top** [comment]
请问有没有对应的插件可以解决
Is there a corresponding plug-in to solve this problem
