### ISSUE TITLE
quickSuggestions Sometimes failure it`s unstable in mac

### ISSUE THREAD

**Issue by kinop112365362** [Microsoft/vscode#12611]
- VSCode Version: 1.5.3
- OS Version: os x 10.11.6

Steps to Reproduce:
1. open a js file
2. the quickSuggestions Sometimes failure it`s unstable

**Comment by chrmarti** [comment]
Could you be more specific on how it fails? Please attach a screenshot showing the problem.

**Comment by chrmarti** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
