### ISSUE TITLE
Last update breaks "extension host" on macOS 10.11.6

### ISSUE THREAD

**Issue by elder-n00b** [microsoft/vscode#126196]
Issue Type: <b>Bug</b>

I just allowed the automatic update, now it's "extension host terminated unexpectedly" again and again, and of course extensions do not work anymore. 
This is the error message from the dev console:
```
dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _pthread_chdir_np
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework
  Expected in: /usr/lib/libSystem.B.dylib
```

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8335  @ 2.66GHz (2 x 2660)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 3, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|-psn_0_28490538|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
crystal-lang|cry|0.8.2
vscode-jq-playground|dav|4.1.0
EditorConfig|Edi|0.16.4
vscode-extempore|ext|0.2.10
copy-relative-path-and-line-numbers|ezf|0.3.1
rest-client|hum|0.24.5
jq-syntax-highlighting|jq-|0.0.2
language-julia|jul|1.2.3
fossil|koo|0.1.0
ruby-rubocop|mis|0.8.5
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
text-power-tools|qcz|1.27.0
ruby|reb|0.28.1
partial-diff|ryu|1.4.3
zig|tie|0.2.5
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by elder-n00b** [comment]
Yes, looks like the same issue, thanks. Got sent here from Help > Report Issue.

**Comment by alexdima** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/125989


**Workaround:** none today, you can go back to `1.56.2` via [download](https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin-universal.zip) and configure `update.mode` to `none` or `manual`.

**Comment by elder-n00b** [comment]
Yes, duplicate. And I apologize for having been polemical. Thanks for the link, that's good.
