### ISSUE TITLE
"Filtering in Document Tree" not working in latest release

### ISSUE THREAD

**Issue by huili80** [microsoft/vscode#126137]
Does this issue occur when all extensions are disabled?: Yes/No

The functionality described at https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree no longer works.

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Type in document tree and nothing happens.
2.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform, and whether the problem still occurs if you run with all extensions disabled.

Also, please confirm that you have focused on the tree before you start typing the filtering characters.
