### ISSUE TITLE
Ability to configure workbench.action.toggleEditorWidths screen percentage

### ISSUE THREAD

**Issue by naymsgeoff** [microsoft/vscode#126188]
I used to use a plugin in Atom called Heypane that automatically resized editor groups so that the focused group occupied a certain screen percentage. Using `workbench.action.toggleEditorWidths`, VSCode already has the logic for this implemented it seems. Clicking, or navigating by hotkey, between groups after toggling that setting will auto-resize the focused group to take up most of the screen

The problem is, I can't tweak what screen percentage the focused group occupies. I'd like to be able to set the focus to 55-65% as opposed to the ~90% it currently is, as that allows most code in the periphery to still be visible while a little extra width/height is available for what's in focus.

**Comment by lonix1** [comment]
+1 This has been requested many times over the years because it's so useful.

My use case: I would like to set an editor group to 0% width, to "collapse" it. I often have two or three groups open, and even at minimum width they are too wide - I want them out of the way.
