### ISSUE TITLE
 MSEdge inspector missing in docked debug toolbar

### ISSUE THREAD

**Issue by chinfeng** [microsoft/vscode#126129]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Windows

MSEdge inspector missing in `{"debug.toolBarLocation": "docked"}` mode

![image](https://user-images.githubusercontent.com/7575491/121774123-51639f80-cbb3-11eb-8a85-359013ffaae2.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/115945
