### ISSUE TITLE
Easy window close keyboard shortcut on Windows (like Ctrl + Q)

### ISSUE THREAD

**Issue by claell** [microsoft/vscode#126263]
This is related to https://github.com/microsoft/vscode/issues/15261.

Basically, I suggest adding an easy keyboard shortcut on Windows to close VS Code. This got more important now that `Ctrl + W` does not close the window anymore when no editor is open.

`Alt + F4` is a rather inconvenient shortcut for me. Also streamlining keyboard shortcuts between operating systems is a sensible thing imho (I am using both Linux and Windows and ideally want applications to behave the same on both).

**Comment by ArturoDent** [comment]
Can you just reassign that command?

```
	{
		"key": "ctrl+w",                    // to whatever you want
		"command": "workbench.action.closeWindow"
	},
	{
		"key": "alt+f4",
		"command": "-workbench.action.closeWindow"
	},
```

Works for any number 0,... of opened editors.  Or is there some other issue with assigning a keybinding to this command?

**Comment by bpasero** [comment]
I could not find a standard keybinding in https://docs.microsoft.com/en-us/previous-versions/windows/desktop/dnacc/guidelines-for-keyboard-user-interface-design for quitting the application that maps to `Ctrl+Q` or `Ctrl+W`, but keybindings are user configurable.
