### ISSUE TITLE
MacOS maximing windows leaves empty screen or tiny window after last update

### ISSUE THREAD

**Issue by msuntharesan** [microsoft/vscode#126266]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: MacOS Big Sur 11.4

Steps to Reproduce:

1. Open new vscode.
2. Maximize window
3. `cmd+shift+n` new window.
4. Try switching desktop.

I've attached a screen recording of this happening.

https://user-images.githubusercontent.com/1296183/121929398-28f0b800-cd0f-11eb-975d-960ebc6bba18.mov

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/126025
