### ISSUE TITLE
"Trust a workspace" not granular enough

### ISSUE THREAD

**Issue by afeinman** [microsoft/vscode#126273]
Issue Type: <b>Feature Request</b>

"Trust a workspace" not granular enough. 

I trust the files in the folder that I wrote, but not necessarily every file in my node_modules directory (which may contain many thousands of packages). I don't know that npm has implemented "VS Code extension hacking" as one of their package audit checks.

This will be true for all my projects. However, I don't seem to be able to exclude subdirs or subdirs by pattern. The pattern repeats across other package management situations (e.g. pyenv).

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by jsoref** [comment]
I'm looking for a middle ground between "I don't care about anything" and "I want a readonly viewer"

I don't trust most extensions not to do reckless things with content from the repositories i'm looking at. And I understand that VSC has decided that it can't warrant that most extensions won't be reckless.

That said, I'd like to be able to use the Terminal (mostly to run a handful of my own scripts) with lots of repositories that I don't directly trust. I do trust my own tooling (and if my tooling is broken, that's my problem, a problem I need to fix, independently of VSCode encouraging me to run that tooling in a window not labeled VSC).

In terms of granular features that I want to be able to use, I have just two:
1. Terminal
2. Being able to use the git staging gui tool (which I also can't use without enabling trust) -- It's shinier than `git add -i`. I'm fine w/ not being able to use the `git commit` features of the VSC gui (there are enough quirks about it that it's not really great for my use cases).

Obviously, I could imagine eventually identifying a handful of other items I'd want in intermediate trust.

Note: I do have a larger set of extensions that I actually use for repositories that I do trust, so it isn't simply a matter of "just uninstall everything you think is reckless".
