### ISSUE TITLE
What a Terrible Update!

### ISSUE THREAD

**Issue by aamuzakii** [microsoft/vscode#126245]
Issue Type: <b>Bug</b>

this update is terrible for 2 reason:

1. I cannot scroll my terminal. no scroll bar!!! how can I see the log when the bug happen???!!!

2. my terminal space is reduced when I open multiple terminal. Previously, adding new terminal didnt reduce anything.
Now I will never open multiple terminal since it will remove available space of my terminal

Those are what I found so far. Hopefully I will not found another terrible feature in this new update

Or if it is possible, I will to go back to previous update

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.80GB free)|
|Process Argv|--crash-reporter-id aa9d64c0-5953-414c-9774-9c6ab49c4071|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
codesnap|adp|1.3.2
synthwave-vscode|Rob|0.1.8
block-travel|sas|0.0.2
learn-vim|vin|0.0.27
vscode-wakatime|Wak|12.0.0
quokka-vscode|Wal|1.0.375

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by IllusionMH** [comment]
You can see what other new features are in May release checking https://code.visualstudio.com/updates/v1_57 to see if you want to proceed.
Also can find terminal tabs description and how to turn it off via https://code.visualstudio.com/updates/v1_57#_terminal-tabs

If you want to download previous versions - they are available via links at the top of previous update posts.

**Comment by Tyriar** [comment]
You should disable terminal tabs if you don't like them. The scroll bar problem is likely https://github.com/microsoft/vscode/issues/125460 which didn't meet the bar for a recovery fix.
