### ISSUE TITLE
I can't rename or create new file throught files explorer view

### ISSUE THREAD

**Issue by eofferma** [microsoft/vscode#126277]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Ubuntu 20.04.2 LTS

Confirmación: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Fecha: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
Sistema Operativo: Linux x64 5.4.0-74-generic snap

Steps to Reproduce:

![Peek 14-06-2021 14-02](https://user-images.githubusercontent.com/475810/121939156-ac63d680-cd1a-11eb-9b65-499efa36271b.gif)

**Comment by ArturoDent** [comment]
Related?: https://github.com/microsoft/vscode/issues/111652

**Comment by eofferma** [comment]
@ArturoDent Yes, same issue, thank you. Apparently the issue was fixed but same problem remains on 1.57 version.

**Comment by isidorn** [comment]
Dup of an open issue. You are having file events in the background

**Comment by eofferma** [comment]
> Dup of an open issue. You are having file events in the background

Yes, that is correct, thank you!. Some process are touching the folder ".git" and I don't know what is it.

**Comment by eofferma** [comment]
It was the oh-my-zsh theme
