### ISSUE TITLE
Copy/Paste from multiple selection.

### ISSUE THREAD

**Issue by miguelmello** [microsoft/vscode#126284]
Hi there,

When you select multiple identical text and copy/paste something diferent, only the first selection changes. 

Regards,

Miguel Mello

Issue Type: <b>Bug</b>

When you select multiple identical text and copy/paste something diferent, only the first selection changes. 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.12.9-200.fc33.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 1744)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (0.39GB free)|
|Process Argv|--unity-launch --crash-reporter-id 7ee9d8f9-0ac7-42a3-a8ed-e4806a565c28|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
vscode-json|and|1.5.0
random-string-password-generator|bib|1.0.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.22
git-extension-pack|don|0.1.3
githistory|don|0.6.16
gitlens|eam|11.5.0
vscode-npm-script|eg2|0.3.22
php-intellisense|fel|2.3.14
search-node-modules|jas|1.3.0
json2csv|kha|0.0.1
kite|kit|0.147.0
save-from-context-menu|kos|0.1.0
node-module-intellisense|lei|1.5.0
vscode-fileheader|mik|0.0.2
ruby|reb|0.28.1
vscode-uppercase|rui|1.0.1
html5-boilerplate|sid|1.1.1
tabnine-vscode|Tab|3.4.5
nodejs-extension-pack|wad|0.1.9
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
vscode-detect-charset|yel|0.0.1
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by rebornix** [comment]
@miguelmello can you please provide some screen recording of what you were seeing to help us troubleshoot?

**Comment by miguelmello** [comment]
https://user-images.githubusercontent.com/3941761/122050791-36af4780-cdba-11eb-88e1-8e2787c2f1a5.mp4
