### ISSUE TITLE
Fast kill button on terminal is gone

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#126225]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: 1.57.0
OS Version: macOS Big Sur
Steps to Reproduce:

<img width="972" alt="Screenshot 2021-06-14 at 5 13 13 PM" src="https://user-images.githubusercontent.com/9585787/121876546-ceb61e00-cd33-11eb-875b-aea4c052d1c6.png">

There used to be a little trash icon that would kill that process, now I have to right click the process name and kill it that way. It's time consuming, please bring back the fast kill button

**Comment by lbdorrou** [comment]
![image](https://user-images.githubusercontent.com/5875320/121927865-2b4e1480-cd05-11eb-9d4e-bb7b15b8a399.png)
If you set this to never you will get a little tab list which has the tashcan and split button. It's not the same but it's still quick

**Comment by yume-chan** [comment]
Prior discussion: #123220

**Comment by yume-chan** [comment]
Note: middle click on the terminal name will kill it. Although obviously not applicable for touchpad users.

**Comment by Tyriar** [comment]
We'll consider this, just like with the split button in #126032

**Comment by Tyriar** [comment]
I added a new setting `terminal.integrated.tabs.showActions` which defaults to `singleTerminalOrNarrow`:

![image](https://user-images.githubusercontent.com/2193314/122390268-a80c0900-cf26-11eb-9a4e-b6010800b4dc.png)
![image](https://user-images.githubusercontent.com/2193314/122390282-acd0bd00-cf26-11eb-983c-5508f98839ae.png)
![image](https://user-images.githubusercontent.com/2193314/122390303-b1957100-cf26-11eb-88fa-3ea36b234e7b.png)

If you use middle and alt+click to kill/split then you can always disable it by setting it to `never`.

**Comment by Tyriar** [comment]
9d728bdda8693f4a113b7d93b8216afa11f39b1b
