### ISSUE TITLE
Multi-Root Workspace: Exclude Subfolders

### ISSUE THREAD

**Issue by stratboy** [microsoft/vscode#126235]
Since vscodebot states:

_We look at the number of votes the issue has received and the number of duplicate issues filed_

I'm asking this again even if there's already this feature request.
We should be able to have the ability to hide subfolders in workspaces settings. Possibly on a directory basis.

Just like this:

``` js
{
  "folders": [
    {
      "path": "foo",
      "ignore": [
        "baz/"
      ]
    },
```
Sublime Text allow this kind of configuration. Can't believe we cannot do on vs code.

Thank you

**Comment by sandy081** [comment]
You can use `files.exclude` setting for excluding sub folders.

cc: @isidorn
