### ISSUE TITLE
Workspace trust - workspace editor is empty

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#126240]
Steps to Reproduce:

1. run from sources
2. in the settings set "testresolver.startupError": true,
3. open a testresolver window
4. the resolver fails (as configured), a dialog shows up, press ignore
5. Open Workspace trust editor

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/124194225-08e62600-da7d-11eb-816f-11be450c6e47.png)

Looks good.... but should it be trusted?

**Comment by lszomoru** [comment]
yes, as by default the empty window is trusted.
