### ISSUE TITLE
Changes to the problemMatcher only recognized after restart

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#12627]
- VSCode Version: 1.5.3
- OS Version: Linux 4.7.4-200.fc24.x86_64

Steps to Reproduce:
1. Run build task with a custom `"problemMatcher" -> "pattern" -> "regexp"` specified
2. Change the regexp
3. VSCode still uses the old one, even when starting the build task multiple times

**Comment by dbaeumer** [comment]
@jhasse I can only reproduce this if the build task is a watching task and runs in background. In that case the problem matcher gets updated only if the task is stopped and restarted.

**Comment by jhasse** [comment]
You're right, I also can't reproduce this now :/

Maybe it was a problem with 1.5.3. I didn't use a watching task though.

I'll reopen if I encounter this again :)

**Comment by dbaeumer** [comment]
There is one thing to keep in mind. If you tweak regexp then it is adviced to give the problem matcher an owner attribute. Otherwise it is hard to clear old problems since we use generated UUID as an owner if omitted which makes the value change when the tasks.json file changes.
