### ISSUE TITLE
vscode evaluate expression on debug console is very poor compare to idea's

### ISSUE THREAD

**Issue by luorixiangyang** [microsoft/vscode#126218]
I like vscode, but the evaluate expression is very poor than idea's. 
e.g: I want to check more attribute's value of object when debug project. but there have 2 poor points:
1. we need to open the **debug console** by hot-key. it can't expand whole infos when get the result, i need change the mouse to click the result for check.  it's a very low efficient action for my job. 
2.  there has no auto-completed feature when we input the object , we need to make sure each method of the object first, i think need refer to IDEA supply the auto-completed feature here. 

I think maybe some plugins implementation the feature about above, if so please notice me, thanks.

**Comment by luorixiangyang** [comment]
Sorry for this issue request. Just i got some approaches to fix it. It's ok now.

**Comment by isidorn** [comment]
Closing as no changes are planned for this particualr issue.
Thanks for providing feedback though we have other issue that track some concerns in this area
