### ISSUE TITLE
Searching in folders with dash in the name broken

### ISSUE THREAD

**Issue by quamis** [microsoft/vscode#126202]
Issue Type: <b>Bug</b>

In a multiroot workspace, select a folder and search for a text. If the selected folder contains a dash ("-") then the whole workspace gets searched, ignoring my input.

Might be related to https://github.com/microsoft/vscode/issues/126003

![ssr-2021-06-14_09 16 39](https://user-images.githubusercontent.com/2966084/121848155-4d8a6700-ccf2-11eb-978d-b1369cca4fec.gif)

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.4.0-74-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2829)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.47GB (1.96GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2c5c4072-32f6-484b-a5c1-2e2e09c41800|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitflow-actions-sidebar|ard|0.5.2
vscode-intelephense-client|bme|1.7.1
transformer|dak|1.11.1
githistory|don|0.6.16
gitlens|eam|11.4.1
smarty|imp|0.3.0
vscode-todo-highlight|jgc|2.0.2
git-graph|mhu|1.30.0
formate|Mik|1.1.6
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
hexeditor|ms-|1.7.0
phpdoc-generator|ron|1.1.1
vscode-multiclip|sle|0.1.5
vscode-terminal-here|Tyr|0.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by quamis** [comment]
Doesn't seem to be related to https://github.com/microsoft/vscode/pull/122022, as it doesn't involve extensions or publishers

**Comment by roblourens** [comment]
Should be fixed in Insiders already by f7dd0d964837a5371b3ba4c645de7b79401a8134

**Comment by quamis** [comment]
This is still not fixed in latest version.

The same behavior is present. If I select a folder with a dash in it's name, the whole workspace will get searched, even if the "files to include" field is filled in correctly.


Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic

**Comment by roblourens** [comment]
It's fixed in Insiders, not released to stable yet
