### ISSUE TITLE
Workspace Trust unclear message

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [microsoft/vscode#126207]
Issue Type: <b>Feature Request</b>

Hi,

VSCode asked me about Workspace Trust for a folder after update and startup. It was unclear to me what folder I'm giving the trust permissions, as it was not part of he message.

There was only "Projects" parent folder mentioned in a optional checkbox.

Please show the full path of the project in question in the trust question.

Thank you

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/125984
