### ISSUE TITLE
auto moves the input to other line

### ISSUE THREAD

**Issue by SHy353** [microsoft/vscode#126239]
Issue Type: <b>Bug</b>

I don't know why but if I'm on a line and do not press any keyboard key for less than a sec, it automatically changes input line to other line. That's so annoying, pls fix.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 2992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.31GB free)|
|Process Argv|C:\\Users\\hasee\\3D Objects\\AccSysv2.0\\scripts\\main.nut --crash-reporter-id b94dd3d0-ddcb-459c-9d4d-1e67b0717814|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|5.6.3
vscode-squirrel|mar|0.0.12
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible in latest stable version 1.57? https://code.visualstudio.com/Download

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
