### ISSUE TITLE
VSCode merge conflicts in Source Control

### ISSUE THREAD

**Issue by SayanHON** [microsoft/vscode#126217]
So I am trying to resolve the conflicts on my code files for which I use Visual Studio code to run all those git commands and then resolve the conflicts.
When I do this action between two small branches(like 10 files in each) the VSCode UI does show me the merge changes ,staged changes but when the same action is done between high volume branches(i.e. it has more number of file in both or one branch) it does show the conflicted files over terminal but not on the sidebar section as Merge changes.
I have shared the snapshot for better understanding let me know if you need further inputs.
It should show the data in conflict just like the below snapshot but actually it shows like the next snapshot
 
[Doc1.docx](https://github.com/microsoft/vscode-docs/files/6645822/Doc1.docx)

**Comment by weinand** [comment]
@SayanHON I've moved this issue to the VS Code repo since it is not related to vscode-deoc.
And please paste screenshots directly into comments (instead of attaching .docx files).

**Comment by egamma** [comment]
In particular this information is missing:

>Make sure the issue can be reproduced without extensions. Either disable all extensions (see the docs for how to do this) or use start extension bisect via "F1 > Start Extension Bisect". If you find the issue is caused by an extension you have installed please file an issue on the extension. The Report Issue option can help you route the report to the correct place.
