### ISSUE TITLE
ctrl + shift + L should select the previous line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1262]
ctrl + I selectes the current line and then selectes the following lines, one by one.
ctrl + shift + I could select the previous line from the current selection.

**Comment by alexandrudima** [comment]
Interestingly, other editors do not have a select previous line

**Comment by Bill-Stewart** [comment]
You can work around this by using `cursorUpSelect` (default <kbd>shift</kbd>+<kbd>up</kbd>) then use `expandLineSelection` (default <kbd>ctrl</kbd>+<kbd>i</kbd>) to select the lines. This repositions the cursor at the end of the selection, though, rather than the beginning, which might be expected.

**Comment by jaqra** [comment]
![CTRLL](https://user-images.githubusercontent.com/48099350/55670816-82d4d800-5891-11e9-914b-57dce58cae08.JPG)

@isidorn @alexandrudima Is that shortcut changed? If so, we can close this issue?

**Comment by isidorn** [comment]
Yeah the keyboard shortfuct is now taken.
Nobody else asked for this. Let's close the issue
