### ISSUE TITLE
fix gitbash terminal

### ISSUE THREAD

**Issue by RushiIgeek** [microsoft/vscode#126230]
Issue Type: <b>Bug</b>

gitbash terminal not working good

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.05GB free)|
|Process Argv|D:\\sendatradieClome\\api|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.22
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
auto-rename-tag|for|0.1.6
vscode-language-babel|mgm|0.0.31
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.7.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
