### ISSUE TITLE
VS Community 2019 version 16.10.1 - Intellisense is not working

### ISSUE THREAD

**Issue by Shroculus** [microsoft/vscode#126282]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Community - 16.10.1
- OS Version: Windows 10 Enterprise - Version 2004 - Build 19041.1052

Steps to Reproduce:

1. Install the visual studio community version 16.10.1
2. This script is created through Unity and hence the unity engine namespace. Enter the below code

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Testing : MonoBehaviour
{
    public Light myLight;

    void Awake()
    {
        int myVar = AddTwo(9, 2);
        Debug.Log(myVar);
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

3. The MonoBehaviour is also not color coded.
4. When I type, AddTwo or Debug.Log it does not suggest anything.

**Comment by mjbvz** [comment]
Please report this issue against Visual Studio. This repo is for VS Code
