### ISSUE TITLE
Slow Vs Code

### ISSUE THREAD

**Issue by Ayush-Chugh-2006** [microsoft/vscode#126201]
- VS Code Version: Latest (1.57)
- OS Version: Windows 10 Latest (20H2)

After updating to vscode version 1.57 vscode is slow it is taking time to change the color of the theme

![recording](https://user-images.githubusercontent.com/69336518/121845977-e07fcd00-cd03-11eb-96ad-2836f573ff54.gif)

As you can see colors are taking time to update the color of the return statement it was ok with version 1.56 but after 1.57 it is  slow

another example

![recording (1)](https://user-images.githubusercontent.com/69336518/121846352-86333c00-cd04-11eb-8226-fe4419a05a16.gif)

Color of 'required' and 'email' should be updated instantly

Task Manager report
![recording (2)](https://user-images.githubusercontent.com/69336518/121847087-a57e9900-cd05-11eb-9d0c-78aac1b35aaf.gif)

System Specs:- 
- Ram - 8 GB
- Processor - i5 5th generation

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Ayush-Chugh-2006** [comment]
didn't tried it

**Comment by Ayush-Chugh-2006** [comment]
i am not seeing this issue again so i am closing this
