### ISSUE TITLE
Sometimes the 'scroll' class is not removed from tabs container after dropping

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#12623]
When closing a tab with middle click in the tabbar, if there are enough tabs, VS Code will close the tab and begin a middle-click scroll operation.  This is very annoying as I just want to close the tab.  There should be an option to disable the middle-click scrolling in the tabbar.

**Comment by bpasero** [comment]
@jez9999 not for my mouse, can you share a video? I wonder what kind of scrolling "middle click scrolling" is on your OS and hardware?

**Comment by jez9999** [comment]
How do I share a video on Github?

**Comment by bpasero** [comment]
@jez9999 produce a gif? On Mac liceap is good.

**Comment by jez9999** [comment]
OK I made a screenshot where I close 2 tabs with the middle click and tab scrolling is triggered. 
![middleclicktabclose](https://cloud.githubusercontent.com/assets/793830/18840448/89aa1814-8406-11e6-9cee-f68ddbaa175d.gif)

**Comment by bpasero** [comment]
Got it. Marking help wanted because I am not sure how to disable this OS native feature. It might not be possible after all.

**Comment by jez9999** [comment]
It's obviously possible to disable middle-click scrolling.

**Comment by bpasero** [comment]
@jez9999 yes in mouse settings I guess, but I was referring to a solution where we could disable it in VS Code only in this particular case.

**Comment by jez9999** [comment]
You can just disable middle click scrolling in the application.  I have plenty of applications installed where middle click scrolling can be switched on or off.  One example is Pale Moon.

**Comment by bpasero** [comment]
@jez9999 well but what if you want middle click scrolling for the editor? I do not think disabling it for the app solves it...

**Comment by jez9999** [comment]
I'd be happy to have an option to disable it for the editor too.  I never want middle-click scrolling. :-)

**Comment by bpasero** [comment]
@jez9999 I see. this sounds like a Mouse configuration you should check on Windows, I do not think we control this from within the application easily.

**Comment by jez9999** [comment]
No, this is an application-level thing, I can assure you.  My mouse is sending the "middle click" event to the window.  The application does not have to initiate middle-click scrolling.

**Comment by romaindurand** [comment]
The function bound to the mouseclick event should return false in order to prevent the scroll behaviour
http://jsfiddle.net/PKpBN/3/

**Comment by bpasero** [comment]
@romaindurand sounds like a pull request chance 👍

**Comment by jez9999** [comment]
OK I have figured out how to recreate this bug.

So, VS Code is not meant to have this behaviour.  It is a bug.  What is meant to happen is that the "scroll" class gets added to the "tabs-container" DIV element during a drag/drop operation (so that the tabbar can scroll right/left when you're dragging a tab), but when the drag operation ends, the "scroll" class gets removed.  See tabsTitleControl.ts lines 129-154 (starting "// Drag over").

This seems to work OK if you slowly drag/drop a tab.  However, for some reason (at least on my Win7 machine), if you drag/drop a tab really quickly, the "drag end" function (DOM.EventType.DRAG_END) doesn't get fired.  It doesn't hit my breakpoint at all.  This means that the "scroll" class stays on tabs-container, meaning that middle-click will trigger scrolling.

I'm not sure yet why DRAG_END doesn't get triggered in this case.  But it explains the buggy behaviour.

**Comment by jez9999** [comment]
@bpasero I see you actually added this "prevent bubbling" behaviour on purpose in commit 383dc0ce2665ec2f28d54a71b0f6e5f8adda8f84 - could you tell me why?  I don't see any good reason to do so, and it introduces this bug.

**Comment by bpasero** [comment]
I have to check again but yes there were very good reasons to do it like that and I doubt we can just remove it.

**Comment by bpasero** [comment]
@jez9999 I propose a simpler fix by just adding

`DOM.removeClass(this.tabsContainer, 'scroll');`

as last line to the onDrop() method of a tab (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L539). 

Can you see if that also fixes it?

This is how the function would then look like:

```typescript
	private onDrop(e: DragEvent, group: IEditorGroup, targetPosition: Position, targetIndex: number): void {

		// Local DND
		const draggedEditor = TabsTitleControl.getDraggedEditor();
		if (draggedEditor) {
			DOM.EventHelper.stop(e, true);

			// Move editor to target position and index
			if (this.isMoveOperation(e, draggedEditor.group, group)) {
				this.editorGroupService.moveEditor(draggedEditor.editor, draggedEditor.group, group, targetIndex);
			}

			// Copy: just open editor at target index
			else {
				this.editorService.openEditor(draggedEditor.editor, { pinned: true, index: targetIndex }, targetPosition).done(null, errors.onUnexpectedError);
			}

			this.onEditorDragEnd();
		}

		// External DND
		else {
			this.handleExternalDrop(e, targetPosition, targetIndex);
		}

		DOM.removeClass(this.tabsContainer, 'scroll');
	}
```

**Comment by jez9999** [comment]
@bpasero Yeah I guess that would work but I'm interested why you're stopping event propagation.  I'd say it's generally a bad idea to do that unless there's a good reason to because it stops things from happening that you'd expect, like the event bubbling up to the tab container in this case.  Allowing propagation seems like the more natural way to get it working.

**Comment by bpasero** [comment]
@jez9999 one reason to stop bubbling of the event is to prevent Electron from opening a dropped file as actual website to open. This is just something to keep in mind when dealing with drag and drop in Electron windows. 

I think it is fine to let the drop event bubble to the tabs container but I think the tabs container should after all prevent bubbling to prevent side effects from happening. Also the tabs container then needs to guard against the wrong target (but it already does by checking for the target being the tabs container to prevent duplicate work).

Also, there are two places where the bubbling is prevented, once for local DND and once for external (e.g. from the desktop).

**Comment by jez9999** [comment]
So which solution do you want to go for; your original one, or allowing the bubbling?

**Comment by bpasero** [comment]
Let me think about it more for a while. Meanwhile we can treat this as a bug.

**Comment by aeschli** [comment]
Verified in Windows 10 and Linux
