### ISSUE TITLE
I want to disable URL underlining in Visual Studio Editor

### ISSUE THREAD

**Issue by 4Juan** [microsoft/vscode#126291]
Issue Type: <b>Feature Request</b>

When writing html code and writing URLs the editor shows them with an underline and I don't like to see underlines in the code.
(it's not about the underline in the web browser but I'm talking about the underline in Visual Studio Code)
There should be the option to disable that underline

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by ArturoDent** [comment]
There is an `editor.links` setting that controls this.  If you want to disable link underlining in `html` files only:

```jsonc
"[html]": {
    "editor.links": false
  },
```

**Comment by aeschli** [comment]
@4Juan Let me know if that fixes your issue. Some color themes also use underline, but in that case just use a different theme.

**Comment by 4Juan** [comment]
If it worked, In configuration option Text Editor option links you can disable and enable interactivity with links. Just uncheck the box and the underline stops showing.
Thank you very much for your help ArturoDent and aeschli
