### ISSUE TITLE
Test API: createWorkspaceTestRoot is called twice for the same workspace if createDocumentTestRoot method is not defined on the TestController

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#126290]
Issue Type: <b>Bug</b>

When adapting the markdown test sample, createWorkspaceTestRoot is being called twice by the API for the same workspace in my adapted example:
https://github.com/JustinGrote/vscode-pester-test-adapter/commit/aeefebfc0e8ae6ad42a8788d9672bec7268c72a1

While this in and of itself seems "fine", it leads to duplicate event handlers getting registered for the create action, and the create action fails when the second one gets fired.

I could have duplicate event registration detection I suppose but seems it's better to just find out why its getting called twice when the root document should still be in "resolved" state.

## Stack Trace for First and Second Calls (second appears to be from an additional anonymous method)
![image](https://user-images.githubusercontent.com/15258962/121954726-f0071200-cd13-11eb-91bb-35bde37cbbe4.png)

VS Code version: Code - Insiders 1.58.0-insider (e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80, 2021-06-14T05:13:55.029Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (4.51GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30319630
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by connor4312** [comment]
Yea, if you don't have a `createDocumentTestRoot` function, it'll be called when get the root in order to provide document tests. This should be deduplicated.

**Comment by JustinGrote** [comment]
@connor4312 OK thanks, I read these docs as meaning the existing `workspacetestroot` call would be used, not that a net-new call would occur. I'll go ahead and implement a `documenttestroot` for now, I'm baby stepping my way through it :)

```
		 * If the test system is not able to provide or estimate for tests on a
		 * per-file basis, this method may not be implemented. In that case, the
		 * editor will request and use the information from the workspace tree.
```

**Comment by JustinGrote** [comment]
@connor4312 also possibly related, if I start my debug extension host and have no documents open, it causes a MainThreadWindow fault. If I have at least one document open in the editor window it is fine.

I'll implement the createDocumentTestRoot method and see if this goes away as a result.


```
stack trace: Error: Unknown actor MainThreadWindow
    at s._doInvokeHandler (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:11717)
    at s._invokeHandler (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:11597)
    at s._receiveRequest (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:10259)
    at s._receiveOneMessage (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:9062)
    at vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1697:7166
    at o.fire (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at l._deliverMessages (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16315)
    at Immediate.<anonymous> (vscode-file://vscode-app/c:/Users/JGrote/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16060)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by connor4312** [comment]
Not sure what that is or whether it's related to testing

**Comment by JustinGrote** [comment]
It happens even in your test provider, so I don't think it's related, will file separate issue, maybe a recent insiders regression.

**Comment by JustinGrote** [comment]
@connor4312 FYI adding a dummy `createDocumentTestProvider` that doesn't return anything did the trick.
```typescript
    createDocumentTestRoot(document: vscode.TextDocument, token: vscode.CancellationToken){
        // TODO: Implement for on-the-fly pester tests in an unsaved document
        if (false) {
            return vscode.test.createTestItem<TestData, TestData>({
                id: 'todo',
                label: 'todo',
                uri: document.uri
            })
        }
        return
    }
```

**Comment by connor4312** [comment]
Should be fixed in tomorrow's build

**Comment by JustinGrote** [comment]
@connor4312 thank you!

**Comment by JustinGrote** [comment]
@connor4312 I'm on today's insiders and while I no longer see the double call when commenting out the createDocumentTestRoot, the document nodes stay stuck in pending and do not resolve.

The full resolvehandler tree appears to get called and all my test objects get created (my "leaf" testcases do not have a resolvehandler defined ATM), and createworkspaceroot completes without issue.

![image](https://user-images.githubusercontent.com/15258962/122260024-aa6b5600-ce87-11eb-862a-5f52258a4be2.png)

My related code:
https://github.com/JustinGrote/vscode-pester-test-adapter/tree/refactor/nativeTestApi/src
(At this commit, createDocumentTestRoot isn't commented out but I commented it out for testing. It's just an empty return)

Do you have a branch of the sample markdown API or something that you tested with? Maybe I can compare and see if I'm doing something wrong.

**Comment by connor4312** [comment]
We'll actually be reworking the API a little bit and removing these methods soon. Watch https://github.com/microsoft/vscode/issues/122208 for details. (Don't worry, the migration should not be very hard, and there'll be a short guide.)

**Comment by JustinGrote** [comment]
@connor4312 OK, I'll leave createDocumentTestRoot as an empty return for now. I've noticed that I don't get the green arrows next to my tests, I'm assuming those arrows come from the documentTestRoot and not the workspaceTestRoot?
![image](https://user-images.githubusercontent.com/15258962/122264606-91b16f00-ce8c-11eb-9089-78589630202b.png)

**Comment by connor4312** [comment]
> I'm assuming those arrows come from the documentTestRoot and not the workspaceTestRoot?

Yep

**Comment by jrieken** [comment]
verified since code doesn't exists anymore

**Comment by connor4312** [comment]
The best kind of verification

**Comment by jrieken** [comment]
no code is the best code
