### ISSUE TITLE
Debugger Hangs on "Variables Tab"

### ISSUE THREAD

**Issue by sovrinbloc** [microsoft/vscode#126297]
Issue Type: <b>Bug</b>

When Debugging (F5), when the "Variables" tab is open, the debugger hangs and is frozen indefinitely until I stop the debugging. This means I cannot use ANY of the features of debugging while the Variables tab is open. Also, that means I cannot see any variables, whatsoever, and therefore debugging is useless.

If I have the variables tab closed, and only have the "Call Stack" tab open, it will run properly, and all features are accessible (except for utilizing the Variables tab).

VS Code version: Code 1.57.0 (Universal) (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 4|
|Memory (System)|128.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 27d8364e-c7d2-491a-8c91-3777001ffb9a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.13.0
cpptools|ms-|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by mjbvz** [comment]
What language are you debugging?

**Comment by sovrinbloc** [comment]
C++
