### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by r3habb99** [microsoft/vscode#126200]
- Issue Type: `Bug`
- Extension Name: `emmet`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rzhao271** [comment]
@r3habb99 can you provide some steps to help me reproduce the issue?

**Comment by r3habb99** [comment]
@rzhao271  No need, I solved by reinstalling extension.
