### ISSUE TITLE
Unable to launch VS Code tests in VS Code Insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#126265]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders 1.58.0-insider
- OS Version: Mac

Steps to Reproduce:

1. Create a new Extesnion using `yo code`
2. Try to run tests in  VSCode Insiders using the debug configuration UI.
3. Nothing happens

**Comment by roblourens** [comment]
Debugging or launching through terminal? And as a temporary workaround, if one is broken,  the other might work

**Comment by DonJayamanne** [comment]
> Debugging or launching through terminal? A

debugging

**Comment by connor4312** [comment]
This works for me just giving the [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample) a spin. Any other details you can provide here? Any console errors?

**Comment by DonJayamanne** [comment]
Ok, thats very weird, now it works. Didn't work in any repo (even a new code base) for me & now it works.
Not sure what happened earlier.
Apologies for the confusion.

**Comment by connor4312** [comment]
Ok, let us know if you hit it again and are able to capture any more info
