### ISSUE TITLE
search.exclude stopped working!

### ISSUE THREAD

**Issue by artagnon** [Microsoft/vscode#12624]
- VSCode Version: 1.5.3 or Insiders
- OS Version: Darwin tip

Steps to Reproduce:
1. Fill in a huge number of directories into files.exclude or search.exclude.
2. Cmd+P yields no results.
3. Symlink just the directory that aren't excluded in another directory tree.
4. Search works as expected.
5. Note that this is a regression from 1.4 (not sure exactly: a few weeks ago).

**Comment by artagnon** [comment]
I just downloaded 1.4 and can confirm that this is a very real regression, despite your claims to have sped up quick-open 2~3x.

Is there a way I can use 1.4, forcing it not to update on restart?

**Comment by bpasero** [comment]
@chrmarti fyi (not verified yet)

**Comment by chrmarti** [comment]
@artagnon What do your exclusions look like? (Using a setting `"update.channel": "none"` seems to disable updates.)

**Comment by artagnon** [comment]
```
"**/foo/bar/" : true,
"**/baz/quux/" : true
```
... About 200 lines like that.

**Comment by chrmarti** [comment]
The trailing / and the multiple path segments in the patterns make them bypass one of the optimizations I have put into insiders. If you can simplify the patterns to many `"**/foo": true`, that should work around the issue in insiders. I'll look into improving the optimization.

**Comment by artagnon** [comment]
Wow, it's blazing fast now! Thanks. Please look into supporting more complex patterns.

**Comment by chrmarti** [comment]
Thanks @artagnon. I have a fix in for the tailing slash "**/foo/". Will look into including multiple path segments after 1.6.
