### ISSUE TITLE
No authentication providers are available

### ISSUE THREAD

**Issue by KrishnaWadhwani** [microsoft/vscode#126274]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: Latest One
OS Version: Ubuntu 20.10
Screenshot from 2021-06-09 23-05-18
![Screenshot from 2021-06-09 23-32-40](https://user-images.githubusercontent.com/61587047/121937137-fd4dec00-cd67-11eb-9ca0-fcda6d380725.png)

Error while turning on Settings Sync. 
```No authentication providers are available.```
I am facing this error from when I disabled all extensions please help me I am not able to use git and sync my settings
Thanks, And Regards
Krishna Wadhwani

**Comment by TylerLeonhardt** [comment]
@KrishnaWadhwani can I ask why you have disabled all extensions?

**Comment by KrishnaWadhwani** [comment]
@TylerLeonhardt Cause My VS Code Is Not Working Properly
Please Help Me With This I Am Not Able To Use Git, Setting Sync, Live Share

**Comment by TylerLeonhardt** [comment]
We need to understand why it's not working with extensions disabled first. Can you please open a new issue why you are forced to disable extensions? You shouldn't be forced to use VS Code with extentions disabled.

Now as for the other things you've mentioned:

* live share is an extension so it will not work if you disable extensions. That's by-design.
* git should work as long as you mean the built-in source control extension and not the GitHub Pull Request extension. Can you provide an screenshot/gif of "git not working?"
* settings sync should work if extensions are disabled. I just tried this and it worked for me so I'm going to need more information like screenshots and gifs of you going through the flow as well.

It's important to provide as much information as possible to us so that we can have the best chances of helping you. Saying "it doesn't work" doesn't give enough enough information to do anything actionable. We wanna help, but you have to help us help you.

**Comment by KrishnaWadhwani** [comment]
# About Discussion
- Let's Continue The Discussion Here Cause, The More Issue The More Hard It Is To Find This, Other Thread
# Why I Disabled Extensions
- Cause My VS Code Stopped Working Well And Fine It Started To Hang In My PC With 8 Gb Ram i3 Processor
# Git Not Working Image
![Screenshot from 2021-06-09 23-32-40](https://user-images.githubusercontent.com/61587047/122431200-de429a80-cfb1-11eb-8434-6de198ab42be.png)

**Comment by KrishnaWadhwani** [comment]
And At The Bottom Right Here It Is Showing The Error

**Comment by TylerLeonhardt** [comment]
> Cause My VS Code Stopped Working Well

Can you elaborate? Was it running but slower than expected?

> Git Not Working Image

Do you have a folder open in vscode? Can you show me the explorer? Is this folder a git repository? Does it have a `.git` folder in it (run `ls -a .git` in the root of the folder to check)

**Comment by KrishnaWadhwani** [comment]
> Can you elaborate? Was it running but slower than expected?
- Java Extension, Whole VS CODE
> Do you have a folder open in vscode? Can you show me the explorer? Is this folder a git repository? Does it have a .git folder in it (run ls -a .git in the root of the folder to check)
- No, I don't

**Comment by TylerLeonhardt** [comment]
> Java Extension, Whole VS CODE

If you disabled _just_ the Java extension, does VS Code run faster? If so you should open a performance issue on:
https://github.com/redhat-developer/vscode-java

which is owned by RedHat, not our team.

> No, I don't

Then that's why you don't see anything in the Source Control view. You have to open a folder that has a `.git` (sometimes hidden) folder it for anything to show up in that view. That's expected.

**Comment by KrishnaWadhwani** [comment]
But I am also not able to use Microsoft Login And Sync My Settings:
```Error while turning on Settings Sync. No authentication providers are available.```
After Disable Of All Extensions

**Comment by KrishnaWadhwani** [comment]
Let Me Init Git Here

**Comment by KrishnaWadhwani** [comment]
I have Initialized Git Here
![Screenshot from 2021-06-17 23-20-18](https://user-images.githubusercontent.com/61587047/122448683-a7c14b80-cfc2-11eb-8ed7-5300cdc00b3d.png)
But the Same Issue:
![Screenshot from 2021-06-17 23-20-34](https://user-images.githubusercontent.com/61587047/122448738-b6a7fe00-cfc2-11eb-9d63-d318b586584a.png)
Please Explain to Me How To Restart This Github And Microsoft Login Extension

**Comment by TylerLeonhardt** [comment]
Please share a screenshot of your explorer pane and prove to me that you `git init` in the same folder

**Comment by KrishnaWadhwani** [comment]
ok

**Comment by KrishnaWadhwani** [comment]
![Screenshot from 2021-06-17 23-49-36](https://user-images.githubusercontent.com/61587047/122452269-b578d000-cfc6-11eb-8103-b41ca216f595.png)

**Comment by KrishnaWadhwani** [comment]
See This Is In The Same Folder

**Comment by TylerLeonhardt** [comment]
this is the explorer I meant:
![image](https://user-images.githubusercontent.com/2644648/122452340-056f7c80-cf5e-11eb-94ef-bf104dc6f5c2.png)

**Comment by KrishnaWadhwani** [comment]
In Linux .git is hidden so it is not showing there

**Comment by KrishnaWadhwani** [comment]
![Screenshot from 2021-06-17 23-52-21](https://user-images.githubusercontent.com/61587047/122452644-199b9400-cfc7-11eb-8b3f-053828220fce.png)
![Screenshot from 2021-06-17 23-53-07](https://user-images.githubusercontent.com/61587047/122452721-3041eb00-cfc7-11eb-8e53-29dcf7de4c9a.png)

**Comment by KrishnaWadhwani** [comment]
See These

**Comment by TylerLeonhardt** [comment]
what is this icon?
![image](https://user-images.githubusercontent.com/2644648/122453120-dad1f380-cf5e-11eb-91fa-5836f2a2855e.png)

**Comment by KrishnaWadhwani** [comment]
This Is In-Browser Preview For Web Dev

**Comment by TylerLeonhardt** [comment]
that's from an extension though... how do you have that showing up.... but also have extensions disabled...?

How did you "disable extensions"? What settings do you have set?

**Comment by KrishnaWadhwani** [comment]
I Have started the extensions I need but I am not able to start the git, ms login

**Comment by TylerLeonhardt** [comment]
wait you put the `.git` folder in the `src` folder but opened the `450DSA` folder in VS Code.

Either:

* `git init` in `450DSA` and delete the other `.git` folder
* open the `src` folder in VS Code

**Comment by KrishnaWadhwani** [comment]
please help me through anydesk

**Comment by KrishnaWadhwani** [comment]
![Screenshot from 2021-06-18 00-23-06](https://user-images.githubusercontent.com/61587047/122456679-7600b280-cfcb-11eb-859e-eb0a7fdb6132.png)

**Comment by TylerLeonhardt** [comment]
Looks like git is working now?

**Comment by KrishnaWadhwani** [comment]
NO

**Comment by TylerLeonhardt** [comment]
Please provide your settings.json

**Comment by KrishnaWadhwani** [comment]
ok

**Comment by KrishnaWadhwani** [comment]
I am sharing but Let me tell you something
I reinstalled vscode in my pc now also this error is coming

**Comment by KrishnaWadhwani** [comment]
I Have Resolved It Thanks @TylerLeonhardt
