### ISSUE TITLE
javascript,typescript template string HTML,CSS etc... color,Supplementation(I can't write English.)

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/vscode#12620]
japanese title:
js,tsのテンプレート文字列でHTML、CSS等の色付け、補充に対応してほしい

**Comment by joaomoreno** [comment]
@Tyriar any help here?

**Comment by Tyriar** [comment]
Looks like HTML/CSS syntax highlighting within JavaScript/TypeScript template files.

**Comment by octref** [comment]
@kgtkr 

ここで英語を使ってください。パーフェクトな英語じゃなくでも大丈夫です。

Are you using this kind of string
```
const s1 = `<div>string</div>`;
const s2 = "<div>string</div>";
```
And want syntax highlighting for them?

@aeschli 

He's saying he wants syntax highlighting and intelliSense for HTML/CSS template strings in JS/TS.

**Comment by kgtkr** [comment]
分かりにくい英語ですみません…
翻訳ありがとうございます

**Comment by octref** [comment]
文字列の内容が HTML/CSS じゃない可能性もありますから、JS ファイルで色付き、補充をイネーブルするのは無理です。
[pug](https://github.com/pugjs/pug), [handlebars](http://handlebarsjs.com/) のようなテンプレートを使った方がいいと思います。VSCodeはそれに対応する色付きと補充の機能があります。

**Comment by kgtkr** [comment]
下みたいな感じの特殊なコメントで種類を指定したりすることで出来たらなと思いました
/// <hoge type="html" />
`
<div>
    Hello World
</div>
`

テンプレート使ってみます。ありがとうございました
