### ISSUE TITLE
Copy value in debug copies as string instead of object [NODE]

### ISSUE THREAD

**Issue by Voldemorten** [microsoft/vscode#126228]
Issue Type: <b>Bug</b>

EDIT: The environment is NODE

When I copy a value from the "Run and Debug" menu, it copies the string representation of the object.

This is how it looks like in the debug menu:
![Screenshot 2021-06-14 at 12 26 18](https://user-images.githubusercontent.com/8776117/121879072-bb438c80-cd0c-11eb-8241-d043673e8ce5.png)

When I right click the the object, and press "Copy Value", I get the following object: 
```{179275832: Array(1)}```
Where as I would expect to get 
```{179275832: [1]}```

I don't know how to simplify the issue, or why it happens. When I try to reproduce, by just creating an object and immediately inspect it: 
```
const filters = {179275832: [1]}
```
I don't have any problems. 

A few examples more:
![Screenshot 2021-06-14 at 12 40 38](https://user-images.githubusercontent.com/8776117/121880001-c8ad4680-cd0d-11eb-9bf2-023110845b6d.png)
Which copies as `(6) [{…}, {…}, {…}, {…}, {…}, {…}]`

![Screenshot 2021-06-14 at 12 42 04](https://user-images.githubusercontent.com/8776117/121880129-ee3a5000-cd0d-11eb-860f-e00b9f340bab.png)
which copies as `(1) [{…}]`

Please let me know, if you need me to try something out. 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 03577f79-08d3-4d96-b2b0-2643a982df88|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by isidorn** [comment]
@Voldemorten It would be great if you can provide a reproducable sample or if you F1 > developer tools > put a breakpoint here
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/variablesView.ts#L422
And trigger your copy value action, the breakpoint will be hit and try to inspect what is going on.

The difference is probably is the value is evaluated by the debugger or not, and that causes the difference.

**Comment by Voldemorten** [comment]
@isidorn how do i debug without using the minified version. I found where to put the breakpoint, but only in the minified version. 

The error is a syntax error:
![image](https://user-images.githubusercontent.com/8776117/122984816-b9796900-d39d-11eb-84c0-20894ac19e08.png)

The error

![image](https://user-images.githubusercontent.com/8776117/122984963-e463bd00-d39d-11eb-94c1-693a5a1819b7.png)

**Comment by Voldemorten** [comment]
Maybe I can fix it myself, if I figure out how to break in the unminified file

**Comment by isidorn** [comment]
@voldermorten make sure source maps are enabled and you should be able to debug Typescript files which should be a nicer experience.

**Comment by Voldemorten** [comment]
Alright. Did that. Still couldn't solve it. Can't find out where the exception is thrown because the error's stack trace still refers to the minified file.
