### ISSUE TITLE
Unlucky choice of cursor color for python intellisense

### ISSUE THREAD

**Issue by neilyoung** [microsoft/vscode#126279]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
1.57.0
- OS Version:
macOS 11.4

Steps to Reproduce:

1. write any line of code
2. wait for the intellisense popup

Blue on blue makes the choice partly invisible

![image](https://user-images.githubusercontent.com/731020/121943022-7130ca00-cd51-11eb-9fed-ad43e289979d.png)

**Comment by misolori** [comment]
@neilyoung can you share what theme you are using and any user settings you've made? I am not able to repro:

<img width="362" alt="CleanShot 2021-06-14 at 15 28 21@2x" src="https://user-images.githubusercontent.com/35271042/121967408-2a2cdf80-cd25-11eb-8012-9ac68c3588c6.png">

**Comment by neilyoung** [comment]
Oh sh... I realized I was using some obscure "Verdigris light" theme. Wasn't aware. No issue with a default theme. Thanks

**Comment by misolori** [comment]
No worries, if you want to keep using that theme you can override the theme's token via:

```json
"workbench.colorCustomizations": {
    "[Verdigris Light]": {
      "list.focusHighlightForeground": "#9DDDFF"
    },
}
```

Closing since this is related to your theme.

**Comment by neilyoung** [comment]
Works perfectly. Thanks
