### ISSUE TITLE
Mouse wheel scroll not working when mouse is not moved

### ISSUE THREAD

**Issue by peterzeller** [Microsoft/vscode#12626]
- VSCode Version: 
```
Version 1.5.3 
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27 
Date 2016-09-22T08:40:08.699Z 
Shell 0.37.6 
Renderer 49.0.2623.75 
Node 5.10.0 
```
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Open a file
2. Hover the mouse over the editor, after 2-3 seconds the mouse cursor becomes invisible
3. Try to scroll the editor using the mouse wheel (editor does not scroll)
4. After moving the mouse the mouse cursor is visible again and scrolling works

**Comment by alexandrudima** [comment]
@Tyriar you are using Ubuntu daily, have you ever seen this?

@peterzeller Is this something that happens in Chromium too when going to https://microsoft.github.io/monaco-editor/ for example ?

Is this perhaps some OS setting you have enabled?

**Comment by Tyriar** [comment]
I've never seen this, I'd also guess it's related to some OS-level setting.

**Comment by peterzeller** [comment]
You are right, it seems to come from the unclutter package in Ubuntu: http://askubuntu.com/questions/648288/how-to-disable-mouse-cursor-autohide
