### ISSUE TITLE
Provide an onTask:foo activation event

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#126238]
When trying to run a task of type `foo` when the extension that contributes the relevant task provider _not activate_ the task fails with:

> There is no task provider registered for tasks of type "foo"

There's a suggestion at https://github.com/microsoft/vscode/issues/103942#issuecomment-669098534 that the extension should use an activation event of `onCommand:workbench.action.tasks.runTask`, but this seems too eager - it will result in the extension being activated for unrelated workspaces and using up resources (eg. spawning language servers, etc.).

I personally find it quite infuriating when I'm working in a workspace of one language type and some random action triggers the activation of a bunch of extensions that do expensive work (for example when the C# extension suddenly activates and starts downloading SDKs, which block some VS Code actions until it completes!). I'd prefer not to have my own extensions have that sort of behaviour.

**Comment by DanTup** [comment]
It seems unlikely this issue is going to get 20 upvotes because a typical user doesn't really understand what this is for. Without this, it's just going to encourage more extensions to eagerly activate and result in other complaints (like performance, or extensions downloading SDKs when they were never supposed to be active, etc. - of which there are already many raised issues).

**Comment by alexweininger** [comment]
> It seems unlikely this issue is going to get 20 upvotes because a typical user doesn't really understand what this is for. Without this, it's just going to encourage more extensions to eagerly activate and result in other complaints (like performance, or extensions downloading SDKs when they were never supposed to be active, etc. - of which there are already many raised issues).

:100:

This is a much needed feature for extensions that provide tasks.
