### ISSUE TITLE
Notebook touch scroll does not work on MD output fields

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#126212]
Have a notebook with some markdown files.
Open it on a touch device (in my case iPad). 
Scroll using the touch. Notice how the scroll is nicely works. However once you use touch scroll while you are over a markdown output the scroll is ignored.
This makes reading markdown notebook output on a touch device troublesome.

Let me know if I can help with this. Thanks!

**Comment by rebornix** [comment]
thanks for the report, we didn't have any handling for touch at all now for elements in the webview. We registered `scroll` event listener in the webview and populate that to the list view in the renderer process if no one is handling it so it will scroll the notebook properly. However we didn't have any touch scroll handling for markdown preview and outputs.
