### ISSUE TITLE
Show full path in Title Bar

### ISSUE THREAD

**Issue by NotepadPlusUser** [Microsoft/vscode#12625]
- VSCode Version: 1.5.3
- OS Version: Windows 1607 V10.0.14393.187

When a file is opened in VSCode, the full path of the file should be shown in the Title Bar.  At the moment, only the filename shows in the title bar, and I cannot find any option to turn on the full path.    

This can be particularly dangerous when one is editing two files of the  same name in different diferectories, but it is always useful to see the directory clearly at the top.  The space is otherwise unused.

(I know that the path is displayed when I hover on the filename on the tab just above the code, but this means mucking about with the mouse when I am keyboarding, and is therefore a real nuisance.)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3119
