### ISSUE TITLE
VSCode causes resize cursor to not show for apps in front

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#126286]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Put a window above VSCode
2. Move the cursor into that window

As you can see here, the cursor shows correctly over Finder, but not over VSCode:

https://user-images.githubusercontent.com/11315492/121950564-16e83700-cd5a-11eb-96fe-3675a0b93d3b.mp4

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.44GB free)|
|Process Argv|--crash-reporter-id ae7777ee-c64c-4b3e-aa57-8ec8dc4c2a8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
stylus|Ala|0.0.4
git-rename|amb|1.2.0
svelte-intellisense|ard|0.7.1
markdown-preview-github-styles|bie|0.2.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
dart-code|Dar|3.23.0
flutter|Dar|3.23.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.22
githistory|don|0.6.16
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|6.4.0
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.27.0
sass-lint|gle|1.0.7
go|gol|0.25.1
gc-excelviewer|Gra|3.0.42
svgeditor|hen|2.9.0
vscode-edit-csv|jan|0.6.0
eml|lei|0.4.0
node-module-intellisense|lei|1.5.0
coffeelinter|lky|1.4.0
rust-analyzer|mat|0.2.637
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
remote-wsl|ms-|0.56.5
cpptools|ms-|1.4.1
hexeditor|ms-|1.7.0
debugger-for-chrome|msj|4.12.12
gradle-language|nac|0.2.3
color-highlight|nau|2.3.0
vetur|oct|0.34.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.7.0
color-manager|roy|0.6.2
crates|ser|0.5.9
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
svelte-vscode|sve|105.1.0
sass-indented|syl|1.8.16
vscodeintellicode|Vis|1.2.14
vscode-meteor|vuh|0.1.1
HCL|who|0.0.5
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/97864
