### ISSUE TITLE
Terminal style is different on other Monitor

### ISSUE THREAD

**Issue by Pascal-Klinkenbergh** [microsoft/vscode#126216]
If I start vs code initially on my monitor, not the screen of my MacBook (MacBook is closed), the first opened terminal looks different (first img). 

If I start vs code on the screen of my MacBooks without a monitor connected everything works fine. 

![Screenshot 2021-06-13 at 21 57 00](https://user-images.githubusercontent.com/41929781/121820434-002add00-cc93-11eb-837c-ab95d4a9a6bc.png)
![Screenshot 2021-06-13 at 21 57 10](https://user-images.githubusercontent.com/41929781/121820436-01f4a080-cc93-11eb-8e48-92064d7cdd00.png)

_Originally posted by @Pascal-Klinkenbergh in https://github.com/microsoft/vscode/issues/125087#issuecomment-860263004_

**Comment by meganrogge** [comment]
This likely has to do with the setting `terminal.integrated.gpuAcceleration`. Experiment w that and let me know

**Comment by Pascal-Klinkenbergh** [comment]
I tested with and without the monitor and came the the following conclusion:

**Behaves the same with and without monitor. But is hard to see on MacBook.**

### `terminal.integrated.gpuAcceleration=off`
Behaves the same for all created terminals:
![monitor-off-first](https://user-images.githubusercontent.com/41929781/122066956-76deec00-cdf3-11eb-875e-e2cd0f9b956c.png)


### `terminal.integrated.gpuAcceleration=on`
Also behaves the same for all created terminals:
![monitor-on-first](https://user-images.githubusercontent.com/41929781/122067129-9bd35f00-cdf3-11eb-913c-ec7beb8f1111.png)


### `terminal.integrated.gpuAcceleration=auto`
Background colour is different for the first and all other terminals created afterwards.
The first created terminal has a darker background. All other terminal created after that have the correct background but different font settings.

**on monitor:**
first terminal:
![monitor-auto-first](https://user-images.githubusercontent.com/41929781/122069471-82cbad80-cdf5-11eb-946c-64e1c51f7c99.png)

all other terminals:
![monitor-auto-second](https://user-images.githubusercontent.com/41929781/122069508-895a2500-cdf5-11eb-9647-60820865f3be.png)


**on Macbook**
first terminal: (hard to see, but via color picker visible)
<img width="808" alt="macbook-auto-first" src="https://user-images.githubusercontent.com/41929781/122069731-b60e3c80-cdf5-11eb-9e0b-36acc61be9e4.png">

all other terminals: (correct background)
<img width="807" alt="macbook-auto-second" src="https://user-images.githubusercontent.com/41929781/122069780-be667780-cdf5-11eb-9059-d790e57bc646.png">

**Comment by widersky** [comment]
Having the same issue on Mac Mini M1 - on both of connected monitors.

![CleanShot 2021-06-24 at 15 36 36](https://user-images.githubusercontent.com/45122321/123272442-070ee680-d502-11eb-98a1-bf6036c52b04.png)

**Comment by Tyriar** [comment]
I believe this is fixed with https://github.com/microsoft/vscode/issues/127645, let me know if you still see it on Insiders and include the version
