### ISSUE TITLE
Node process started via debugger is not killed when quitting VSCode

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#126211]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Press CMD+Q to quit VSCode while an active debug session is running, using the node configuration.

Configuration looks like this:

```
{
				"type": "node",
				"request": "launch",
				"name": "Server",
				"windows": {
					"program": "${workspaceRoot}\\server\\dist\\app.js",
					"cwd": "${workspaceRoot}\\server"
				},
				"outputCapture": "std",
				"program": "${workspaceRoot}/server/dist/app.js",
				"cwd": "${workspaceRoot}/server",
				"env": {
					"FORCE_COLOR": "true",
					"LOCAL_DEVELOPMENT": "true"
				},
				"sourceMapPathOverrides": {
					"server/src/*": "${workspaceRoot}/server/src/*"
				},
				"resolveSourceMapLocations": ["!**/node_modules/**"]
			}
```

2. Sometimes (about 30% of the time), I will later find that the above process had never been killed when quitting VSCode.

This bug is beyond frustrating, it makes using VSCode a chore. Please can this be fixed. Thanks

**Comment by jpike88** [comment]
an attempt to help workaround this issue (but not solving it):

I'm using a preLaunchTask that runs this script:

```kill $(ps aux | grep dist/app.js -m1 | awk '{print $2}')```

This ensures if I want to run the process next time I open VSCode, I don't need to check for and kill the previous process.

**Comment by weinand** [comment]
I can reproduce: the debuggee node.js disappears, but the debug adapter's node.js stays around.

**Comment by isidorn** [comment]
@jpike88 thanks a lot for creating this great issue 👏 
I was listening on `lifecycleService.onDidShutdown` to shutdown the node sesion, now I changed to `lifecycleService.onWillShutdown` which happens a bit earlier and I am blocking the VSCode shutdown until I send the proper `disconnect` request - this should be fine since sending the request should not take a long time. I tried this out and works nicely on my machine. Though it would be great if you can also try it out with VS Code insiders from tomorrow and let us know how it goes.

fyi @bpasero for `lifecycleService` usage

**Comment by bpasero** [comment]
That sounds good to me:
* `onBeforeShutdown`: can be used if you need to prevent the shutdown
* `onWillShutdown`: can be used to join the shutdown with a long running op
* `onDidShutdown`: cannot be async and should typically not be used

Note: in web, there is no long running shutdown so you might see a warning appearing.

**Comment by isidorn** [comment]
@bpasero great! Maybe we should create a debt issue to go through all the `onDidShutdown` usage and change to `onWillShutdown` if possible. What do you think?

**Comment by bpasero** [comment]
I think I made that pass some time ago when I added these distinct events, but yeah wouldn't hurt.

**Comment by weinand** [comment]
@isidorn what had changed in VS Code that resulted in this breakage?

**Comment by isidorn** [comment]
@weinand timing. We did not change code on our end. I am not sure when this broke exactly.

**Comment by weinand** [comment]
So your use of the `lifecycleService.onDidShutdown` was not a recent change?

**Comment by isidorn** [comment]
Correct. It was like that for more than a year.

**Comment by connor4312** [comment]
I've had trouble reproducing this on stable, and also didn't see it on Insiders. @jpike88 please let us know if you see this happening [on Insiders](https://code.visualstudio.com/insiders/).
