### ISSUE TITLE
macOS smoketest failure: unable to open file

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#126221]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=123076&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4

```
  1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Editor
           shows correct quick outline:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (/Users/runner/work/1/s/test/automation/out/code.js:176:19)
      at async Code.waitForElements (/Users/runner/work/1/s/test/automation/out/code.js:253:16)
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
      at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:42:9)
```

**Comment by bpasero** [comment]
@joaomoreno any hints what we would do here to strengthen the test?

**Some thoughts:**
* can we attach a screenshot of the running app when this happens as build artefact to help diagnose what is going on in the test (didn't we explore this once?)
* should we print the current active element (I think we do this in the native smoke tests but not browser based ones?), this could hint if maybe a dialog has focus at that time

**Comment by bpasero** [comment]
Oh wait, this is not the quick outline test failing, this is actually failing to open a file:

```
at async QuickAccess.openFile (/Users/runner/work/1/s/test/automation/out/quickaccess.js:42:9)
```

This is a very basic operation that needs to succeed for smoke tests to function...

**Comment by joaomoreno** [comment]
No, the failure is in Quick Open to show the results:

```
      at async QuickInput.waitForQuickInputElements (/Users/runner/work/1/s/test/automation/out/quickinput.js:25:9)
```

The smoke test opens quick input, types some text and waits for results. They never come. My suspicion is **always** the same: some other UI piece steals focus away from Quick Open and thus Quick Open hides.

My suggestion for the entire smoke tests: we disable _hide on blur_ for Quick Open, for the entire duration of the smoke test.

**Comment by bpasero** [comment]
True 👍 

Oh no, this is not good, the getting started page is back:

![image](https://user-images.githubusercontent.com/900690/122008864-c99bb200-cdb9-11eb-8a01-05c4c7cb549e.png)

It is disabled in native tests but not web. This could be an explanation...

**Comment by joaomoreno** [comment]
I love it. I actually have a branch now in which I run the smoke tests on Windows and I keep hitting some issue. That might be it as well!

**Comment by bpasero** [comment]
This is just web though, in desktop we have a CLI arg to disable welcome `--skip-welcome`

**Comment by joaomoreno** [comment]
Yeah they only fail on web 😆
