### ISSUE TITLE
Jump IntelliSense

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12632]
See attached gif

![sep-26-2016 14-47-32](https://cloud.githubusercontent.com/assets/1794099/18834808/396e4fe0-83f8-11e6-9dd0-03b7beaa5276.gif)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
