### ISSUE TITLE
Debugger var watching - Breakpoint where any value changes

### ISSUE THREAD

**Issue by josexlito** [microsoft/vscode#126358]
It may be very interesting that execution stops (like a breakpoint) when an expression or any variable change hosted in Watch section.

Something like this: https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2019

![databreakpoint](https://docs.microsoft.com/en-us/visualstudio/debugger/media/managed-data-breakpoint.png)

**Comment by weinand** [comment]
@josexlito are you suggesting a feature request for Visual Studio Code?

**Comment by josexlito** [comment]
Yes, I guess this is a new feature, I don't know if is possible do that now in VSCode (with/out extensions).

**Comment by weinand** [comment]
@josexlito VS Code already supports "data breakpoints". See https://code.visualstudio.com/docs/editor/debugging#_data-breakpoints.

However, most debug extensions do not support this feature.
Please file a feature request against the debug extension you are using.
