### ISSUE TITLE
FiraCode ligatures dissappeared with a recent update.

### ISSUE THREAD

**Issue by asibahi** [Microsoft/vscode#12634]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Anniversary update

Steps to Reproduce:

No steps really. I opened VS Code one day and the ligatures were gone. I think it was the "August Release" or the 1.5.1 where it started.

I am filing an issue even though this seems like a local bug, as [one of the developers advised me to file an issue](https://twitter.com/ErichGamma/status/780368789510782976)

This is how it looks like for me:
![capture](https://cloud.githubusercontent.com/assets/17417266/18835828/c96130a6-8405-11e6-83da-6919a850f52a.JPG)

**Comment by zgoda** [comment]
Same on Ubuntu 16.04.1 amd64.

**Comment by joaomoreno** [comment]
This moved to a setting: `"editor.fontLigatures": true`
