### ISSUE TITLE
how to use cascadia code italic in vscode?

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#126370]
Issue Type: <b>Feature Request</b>

Today i came across Cascadia Code with Italics and fell in love with it.
![image](https://user-images.githubusercontent.com/9264813/122049160-b90e2a80-cdff-11eb-85f1-2309cc8afa5f.png)

is there any possibility of changing the editor font style to italics? I tried with several forums and it seems that individual tokens can be changed and throughout style can not be changed.
if there is some setting i missed?

VS Code version: Code - Insiders 1.58.0-insider (e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80, 2021-06-14T05:12:28.099Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by sanket-bhalerao** [comment]
for some reason my macBook shows the italics but windows 10 machine does not. i have installed the latest Cascadia Code fonts (ttf) on both of them.
![image](https://user-images.githubusercontent.com/9264813/122051797-9d585380-ce02-11eb-8f39-ea47adcd0d2f.png)

**Comment by IllusionMH** [comment]
For Windows you either should install only Italic version e.g. `CascadiaCodePLItalic.ttf`, then add `'Cascadia Code PL'` (font name should correspond to font you picked) in front or `"editor.fontFamily"` value. Works in case when you don't need regular version.

In other case you need to install both - install both Regular and Italic version, add `'Cascadia Code PL'` (font name should correspond to font you picked) in front or `"editor.fontFamily"` value.
And now you need to override syntax highlight styles for all scopes.

Follow steps from https://stackoverflow.com/questions/41320848/how-do-i-get-visual-studio-code-to-display-italic-fonts-in-formatted-code but specify `"fontStyle": "italic"` for all scopes you need.
I guess that full list of top level scopes is `["comment", "constant", "emphasis", "entity", "invalid", "keyword", "markup", "meta", "storage", "string", "strong", "support", "variable"]`

**Comment by sanket-bhalerao** [comment]
thank you for the details. i will try it.
is there any plan or future possibility of having a shortcut setting like `"editor.fontStyle": italic` ?
