### ISSUE TITLE
Can't continue debugging React Native TypeScript app once breakpoint is hit

### ISSUE THREAD

**Issue by canpoyrazoglu** [microsoft/vscode#126354]
Does this issue occur when all extensions are disabled?: Inapplicable (can't test the debug flow without extensions in the first place)

- VS Code Version: 1.57 
- OS Version: macOS 11.3.1

Steps to Reproduce:

1. Have a React Native app using the TypeScript template
2. Check "caught exceptions" breakpoint
3. Make your code throw any error and hit the breakpoint
4. Try to continue from breakpoint

Nothing is happening when I try to continue from the breakpoint once it's hit. It's as if I'm not hitting the continue button, stuck as-is. I need to close and reopen Vscode and it's impossible to debug this way. This issue started with the 1.57 update, is present on Insiders 1.58 update too, and got resolved when I reverted back to 1.56.2, so it's definitely something that broke exactly at version 1.57.

**Comment by lukaspechar** [comment]
I can confirm this as well. I've tried to downgrade to the previous version of the ReactNative tools as well still no luck. This has started since the latest update of VSCode.

**Comment by canpoyrazoglu** [comment]
@connor4312 I can't add `"trace": true` to my `launch.json`. Linter says it must be one of "verbose", "log", "warn", "error", "stop":

![Screen Shot 2021-06-15 at 20 53 10](https://user-images.githubusercontent.com/4348413/122100354-c0dbc800-ce1b-11eb-8761-2960cc1dbc74.jpg)

If I ignore the linter and try to run anyway I get `Cannot read property 'toUpperCase' of undefined` error:

![Screen Shot 2021-06-15 at 20 54 55](https://user-images.githubusercontent.com/4348413/122100552-fa143800-ce1b-11eb-88d5-48042bcb3cce.jpg)

**Comment by lukaspechar** [comment]
Any update on this issue?

**Comment by connor4312** [comment]
Please open an issue over on the vscode-react-native project: https://github.com/microsoft/vscode-react-native

**Comment by maartenvandillen** [comment]
Hi @canpoyrazoglu, I found this other issue you filed https://github.com/microsoft/vscode-remote-release/issues/4787 but I can't comment on that since it's closed. I'm having the same problem, debug console stops logging after redux logs a lot at app startup and clear button also stops working. Did you ever find a fix for this? Is it maybe related to this issue?

**Comment by canpoyrazoglu** [comment]
@maartenvandillen I've reverted back to the old version as each version of Vscode tends to be buggier than ever, breaking everything that's working perfectly.

**Comment by canpoyrazoglu** [comment]
@maartenvandillen and about the redux logger, I've noticed that it's not necessarily redux, but anything that logs "a lot" into the console. Unfortunately I don't know a solution for that too, hoping for a fix.
