### ISSUE TITLE
Remote ssh extension cannot switch terminal by mouse click

### ISSUE THREAD

**Issue by saurabhrb** [microsoft/vscode#126318]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.0 (user setup)
- OS Version: Windows_NT x64 10.0.17763

when using remote-ssh to open a directory over a remote host (Remote-SSH extension v0.65.6)
the new terminal panel browser, doesn't switch on click, have to sue arrow keys in the panel browser part to switch between opened terminals
Steps to Reproduce:

1. remote-ssh to a host (Remote-SSH extension v0.65.6)
2. create multiple terminals in terminal panel
3. try switching by clicking on the panel browser (right pane inside terminal panel), it won't switch

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
