### ISSUE TITLE
Issue with running html programming with and without debugging

### ISSUE THREAD

**Issue by TakingJester766** [microsoft/vscode#126368]
Issue Type: <b>Performance Issue</b>

Whenever I attempt to run my html code (with or without debugging) I get a prompt from chrome telling me "This site can't be reached. localhost refused to connect." I have never had any problems in the past with this, however now every single time I try to run my html code this prompt comes up. 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.39GB free)|
|Process Argv|--crash-reporter-id 131bc1b3-163a-440e-92cd-49fbd65acc41|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    76	 16104	code main
    0	    80	  2544	   shared-process
    0	    71	 20620	     "C:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-chrome "{\"common.vscodemachineid\":\"d8c4d6362bc554f5f4d2094cb348e90808c85e2eac71de7c5c7ce0850e85b229\",\"common.vscodesessionid\":\"800efa7f-5998-4a4e-a58c-51975a5341841623756633668\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    68	 21428	     ptyHost
    0	     6	 17528	       console-window-host (Windows internal process)
    0	    61	 23360	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    23	  4572	   crashpad-handler
    0	    38	  8492	   utility
    0	    76	  9584	   window (Issue Reporter)
    0	   155	 15312	   window (Dad's Band.html - Coding stuff - Visual Studio Code)
    0	   101	  5696	     extensionHost
    0	    90	  7420	       "C:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=5696
    0	    68	 23900	       "C:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Zimme\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=5696
    0	    12	 23748	     watcherService 
    0	    10	 15688	       console-window-host (Windows internal process)
    0	   232	 23516	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Dad's Band.html - Coding stuff - Visual Studio Code)
|    Folder (Coding stuff): 10 files
|      File types: html(2) css(2) json(1) txt(1) jpg(1)
|      Conf files: launch.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.5
vscode-html-css|ecm|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by TakingJester766** [comment]
> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

![recording](https://user-images.githubusercontent.com/85938969/122140290-e0bdbc80-ce18-11eb-97d2-cc49f8f7fc01.gif)

**Comment by TakingJester766** [comment]
> /gifPlease

![recording](https://user-images.githubusercontent.com/85938969/122140310-eddaab80-ce18-11eb-9fa0-4ab967962a2e.gif)

**Comment by connor4312** [comment]
@TakingJester766 what are the contents of your launch.json? If you have anything in there, F5 will default to that; I'm guessing you'e trying to hit localhost:8080 in here.

**Comment by TakingJester766** [comment]
> @TakingJester766 what are the contents of your launch.json? If you have anything in there, F5 will default to that; I'm guessing you'e trying to hit localhost:8080 in here.

Hey, looks like that worked! Thanks for your help!
