### ISSUE TITLE
Switching terminals in tabs not possible when list open mode = doubleClick

### ISSUE THREAD

**Issue by chumbalum** [microsoft/vscode#126381]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 10, 19042.1052

Steps to Reproduce:

1. Set List Open Mode to doubleClick
2. Open multiple terminals
3. Switching terminals is not possible (neither with double click, nor single click)
4. Set List Open Mode to singleClick (default)
5. Switching terminals is working via single click

![grafik](https://user-images.githubusercontent.com/486034/122055909-64f84b80-cde9-11eb-8cc0-d25f73b3bde0.png)

**Comment by Hezkore** [comment]
This was driving me insane.
I've noticed that dragging the terminal a few pixels will still switch to it when using `doubleClick`.

**Comment by kennysong** [comment]
Same problem! I love the tabs UI but can't actually click them to switch tabs.

Another temporary workaround is to use the [keyboard shortcuts for switching tabs](https://github.com/microsoft/vscode/issues/37937#issuecomment-343231679).

**Comment by Tyriar** [comment]
@meganrogge FYI I removed the `editorOptions.pinned` check added in https://github.com/Microsoft/vscode/issues/124849, it seems to work fine without it and that was causing this since double click always causes pinned
