### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by ytx222** [microsoft/vscode#126396]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.57.0
- OS Version:windows 10 20H2
extension: https://github.com/ytx222/novel-look
Steps to Reproduce:

1. This code, before the 1.57.0 release, worked fine
```
<meta http-equiv="Content-Security-Policy" content="script-src filesystem @./webView.js; style-src filesystem @./style.css" />
<link rel="stylesheet" href="@./style.css" />
<script src="@./webView.js"></script>

async function getWebviewContent(url) {
	let s = "";
	// reader file get html string
	s = await file.getWebViewHtml();
	// replace "@."
	let result = s.replace(/(@)(.+?)/g, (_m, _$1, $2) => {
		return panel.webview.asWebviewUri(vscode.Uri.file(path.join(url, $2)));
	});
	return result;
}
```
2. When the version is updated, the address obtained through the 'asWebviewUri' becomes 'https://file+.vscode-resource.vscode-webview.net/c:/Users/Administrator/AppData/Roaming/Code/User/globalStorage/ytx222.novel-look/static'
3. This address is not resolved by vscode, so the following error appears
4. "he source list for Content Security Policy directive 'script-src' contains an invalid source: 'https://file%2B.vscode-resource.vscode-webview.net/c%3A/Users/Administrator/AppData/Roaming/Code/User/globalStorage/ytx222.novel-look/static/webView.js'. It will be ignored."
5. Then my page will not load properly into the resource files in the extended cache directory

**Comment by mjbvz** [comment]
You should not be using full file urls in your content security policy. Instead use the `Webview.cspSource` property instead (it should be something like `https://*.vscode-webview.net`, although always use the property instead of  hardcoding this)
