### ISSUE TITLE
terminal.external.windowsExec not working

### ISSUE THREAD

**Issue by peter31990** [microsoft/vscode#126333]
"terminal.integrated.defaultProfile.windows": "Git Bash",
"terminal.external.windowsExec": "C:\\Programy\\Git\\bin\\bash.exe"

Terminal is still powershell

**Comment by ajdev6** [comment]
Change the "terminal.explorerKind": "external" to external

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
