### ISSUE TITLE
Disable "trust folder" feature

### ISSUE THREAD

**Issue by katsar0v** [microsoft/vscode#126348]
Is there an options to disable this feature from the update or should I mark `/` as trusted?

**Comment by gjsjohnmurray** [comment]
See the "Settings" subsection at the end of https://code.visualstudio.com/updates/v1_57#_workspace-trust

**Comment by lszomoru** [comment]
@katsar0v, you can use the following setting to suppress the modal dialog that is being shown when opening a folder/workspace:
```
"security.workspace.trust.startupPrompt": "never"
```

If you still want to disable the feature, you can do that using the following setting (requires a restart):
```
"security.workspace.trust.enabled": false
```

**Comment by katsar0v** [comment]
Awesome, thank you @lszomoru !

**Comment by lszomoru** [comment]
@katsar0v, setting that value to `always` will result in always seeing the prompt on startup for untrusted workspaces.
