### ISSUE TITLE
Window Opacity Setting

### ISSUE THREAD

**Issue by adrwstn** [microsoft/vscode#126392]
Electron provides an opacity option to be passed to the BrowserWindow method, please allow this to be specified by the user in settings so we can set manually or build an extension around it! 

Link to Electron documentation on option: https://www.electronjs.org/docs/api/browser-window#winsetopacityopacity-windows-macos

**Comment by bpasero** [comment]
We try to keep API use from Electron that is likely less used and less tested to a minimum. See https://github.com/microsoft/vscode/wiki/How-to-Contribute#introducing-usage-of-new-electron-api-with-a-pr for reasoning. I feel this property falls under that category.
