### ISSUE TITLE
Test: TypeScript 2.0.3 upgrade

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12633]
Tests https://github.com/Microsoft/vscode/issues/10136

- [x] Windows - @waderyan 
- [x] Linux - @isidorn 
- [x] Mac OS - @chrmarti

Complexity: 4

We upgraded TS to 2.0.3. In addition VS Code's source code got adapted to TS 2.0.3. We need to test the TS functionality on a test workspace. Do the following:

## Upgrade info:
- create a new workspace and open VS Code. 
- you should see a message informing you about the fact that we upgraded to TS 2.0.3. We only show the message once so you might have already seen it. If so open the Dev tools and delete the following entry from local store:

![capture](https://cloud.githubusercontent.com/assets/1931590/18836265/8d64bb28-83ff-11e6-9c88-13fcc7109558.png)

- try again.

## Feature testing

- create a new workspace or take an existing workspace and upgrade it to TS 2.0.3 if you use a local typescript install update it to TS 2.0.3 (e.g. if you use typescript.tsdk).
- test all TS functions like: error reporting, intellisense, goto definition, find references, format, format on type, hover, rename. ...
- try things...
- if the error is an 'obvious' TypeScript problem file the issue directly against the TS repository: https://github.com/Microsoft/TypeScript. Otherwise file it against vscode.

**Comment by waderyan** [comment]
- [ ] Create a new workspace. Open VS Code. See a prompt indicating TS 2.0.3. 

IntelliSense
- [ ] Browser IntelliSense.
- [ ] Single file IntelliSense.
- [ ] Multiple file IntelliSense. Requires jsconfig.json. 
- [ ] Third party IntelliSense. Requires jsconfig.json and typings. 

Code Navigation
- [ ] Code navigation within first party workspace. 
- [ ] Code navigation to third parties.

Linting
- [ ] Obvious syntax error.
