### ISSUE TITLE
`onCompletion` can not trigger with `CompletionTriggerKind.Invoked` in markdown

### ISSUE THREAD

**Issue by Amour1688** [microsoft/vscode#126328]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: >= 1.4.3
- OS Version: MacOS Big Sur 11.4

Steps to Reproduce:

1. Repo https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample
2. add language markdown here https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/src/extension.ts#L41
```ts
let clientOptions: LanguageClientOptions = {
  // Register the server for plain text documents
  documentSelector: [
    { scheme: 'file', language: 'plaintext' },
    { scheme: 'file', language: 'markdown' },
  ]
};
```

3. add break point here https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts#L195
4. types characters can not trigger

**Comment by dbaeumer** [comment]
@Amour1688 what do you mean with `types characters can not trigger` ?

If you want to make code complete auto trigger you need to specify the trigger characters on server registration. The sample doesn't provide any trigger characters. See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion

**Comment by Amour1688** [comment]
I type character `c` in markdown，callback of `connection.onCompletion` can not be triggered. But it will be triggered in plaintext.

**Comment by Amour1688** [comment]
https://user-images.githubusercontent.com/31695475/122064417-bcb3a880-ce23-11eb-81f5-d502cae03b88.mp4

**Comment by dbaeumer** [comment]
This is IMO controlled by the word definitions for the languages. VS Code auto triggers code completion if the user types an identifier inside the code. I think normal words in markdown will not trigger this behavior.

@jrieken is this correct ?

**Comment by Amour1688** [comment]
But normal words trigger code completion  in plaintext.

**Comment by Amour1688** [comment]
Is there any way to solve this problem? @dbaeumer

**Comment by dbaeumer** [comment]
Markdown by default disables quick suggests on normal words. It can be re-enabled using

```
	"[markdown]": {
		"editor.quickSuggestions": {
			"other": true,
			"comments": true,
			"strings": true
		}
	}
```

I will close the issue since this is not related to LSP nor to the VS Code API.
