### ISSUE TITLE
Test format on save

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12639]
Test for #12449

- [x] any os @bgashler1 
- [x] any os @kieferrm 

Complexity 2

We added support to format a document on save. Please test that

* there is a setting `editor.formatOnSave` and that the setting is documented and a good fit
* format on save won't work when auto save is on
* format on save works with all the other save options (focus lost etc)
* format on save produces the same result as the format action from the context-menu would

**Comment by chrmarti** [comment]
@jrieken I'm assuming this also covers #239.

**Comment by jrieken** [comment]
@chrmarti I have added https://github.com/Microsoft/vscode/issues/12640 for that

**Comment by kieferrm** [comment]
#12827 is the only "issue" I found with this feature.

**Comment by bgashler1** [comment]
Small thing, I would just put a comma after the conjunction "and" so it's not a run-on sentence.
![image](https://cloud.githubusercontent.com/assets/11839736/18893949/f68e108e-84c4-11e6-9780-66fc5603d5af.png)
