### ISSUE TITLE
Error: invalid marker service state

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12635]
- VSCode Version: 1.6.0-insider
- OS Version: Windows

Sorry, no steps:

![capture](https://cloud.githubusercontent.com/assets/1931590/18836222/4c6ac216-83ff-11e6-9014-4c855f49f395.png)

**Comment by VladimirAmiorkov** [comment]
+1

**Comment by PinkyJie** [comment]
I also have this issue when using `monaco-editor`.

**Comment by aeschli** [comment]
verified through #13548
