### ISSUE TITLE
Alphabetical Order of Lists in the List drop downs of Settings Workspace please.  :)

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#126364]
Alphabetical Order of Lists in the List drop downs of Settings Workspace & other settings area of editor please.  :)

If you look at this drop down list, nothing is in alphabetical order, making it difficult to find anything.
One has to spend a great deal of time searching for a specific thing within the drop down list.

.
![Request Feature - Alphabetical Order](https://user-images.githubusercontent.com/18384135/122040654-0fe71600-cda6-11eb-93a3-a9d2042ffa02.png)

.

**Comment by roblourens** [comment]
The settings editor does not reorder enum items because the order is sometimes useful to customize. But the `editor.defaultFormatter` setting registration could sort these if it wanted to.

**Comment by jrieken** [comment]
Extensions that use the `Formatter` or `Programming Languages` category are sort atop and alphabetical order is used to sort inside these buckets
