### ISSUE TITLE
Save-All greyed-out

### ISSUE THREAD

**Issue by IgnacioHR** [microsoft/vscode#126353]
- VS Code Version: 

Versión: 1.57.0
Confirmación: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Fecha: 2021-06-09T17:22:31.215Z (hace 5 días)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
Sistema Operativo: Darwin x64 20.5.0

- OS Version:

Big Sur 11.4

Steps to Reproduce:

1. Open a project
2. Modify more than one file so they become "dirty"
3. Try so save all them

I notice this is a very common (still unresolved) problem. So I'm trying to provide feedback and push for a quick resolution

Hope this information is useful!

Installed extensions:

![Window](https://user-images.githubusercontent.com/16385090/122017786-91e53800-cdc2-11eb-9cfc-a6dffc42ead5.jpg)

![Archivo_y_Window](https://user-images.githubusercontent.com/16385090/122017127-fce23f00-cdc1-11eb-80dc-1d0e1e67843b.jpg)

**Comment by IgnacioHR** [comment]
There is a workaround that consist of clicking in another application so vscode lost focus and click back on vscode. Then the menu option to Save All becomes active

**Comment by davidbfrogman** [comment]
I'm having the same issue after updating
