### ISSUE TITLE
Alt-click to move cursor in Git Bash terminal not working

### ISSUE THREAD

**Issue by adamerose** [microsoft/vscode#126342]
When using the Git Bash terminal in VS Code, alt-clicking often moves the cursor between the beginning and end of the line instead of to my cursor location. It works with cmd just not Git Bash.

Video: https://www.screencast.com/t/s1nbUZAu

I found [this issue](https://github.com/microsoft/vscode/issues/26401) on initially implementing cursor movement with the mouse, but not sure if Git Bash is unsupported or this is a bug.

```
Does this issue occur when all extensions are disabled?: Yes
Version: 1.57.0 (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by ArturoDent** [comment]
I am not able to replicate this on W10 Stable or Insiders.  

![altClickTerminal](https://user-images.githubusercontent.com/31813701/122118429-3d06e900-cde5-11eb-8de7-0f0786d7d09a.gif)

Can you try Stable v1.57 to see if it still doesn't work for you.  And try disabling all extensions first too.

Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.21390

**Comment by adamerose** [comment]
@ArturoDent I updated to the latest release and disabled all extensions, it still happens. I edited my post with new details and video. I also reinstalled Git Bash with the latest version and default settings, here are the settings https://imgur.com/a/O5rW0Pa

**Comment by Tyriar** [comment]
It's working fine for me, note that the alt+click feature is a little unreliable by design though as we're just sending over a bunch of arrow key presses
