### ISSUE TITLE
Typo in 1.57 release notes

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode#126385]
In the release notes for 1.57 (https://code.visualstudio.com/updates/v1_57#_debugging), the sentence starting "If you aren't already using Microsoft Edge for browser debugging, you can switch to it be replacing..." should actually say "...switch to it _by_ replacing...".

PS Are the release notes in a repo somewhere where I could have submitted the above as a simple PR?

**Comment by lramos15** [comment]
I have fixed the typo in the repo thanks for pointing it out! The repo for all our documentation is https://github.com/microsoft/vscode-docs
