### ISSUE TITLE
`code .` opens new window at root folder in macOS

### ISSUE THREAD

**Issue by cdbattags** [microsoft/vscode#126399]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: macOS 11.4 (20F71)

Version verbose:

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (5 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Steps to Reproduce:

1. navigate in shell to folder (i.e. `cd /Users/<user>/projects/<project>`)
2. run `code .`
3. opens new window at root folder (see screenshot)

![image](https://user-images.githubusercontent.com/4399055/122092188-a2ec7400-cdd7-11eb-9b28-e1a34d3aee92.png)

I also checked `$(which code)` against https://github.com/microsoft/vscode/blob/main/resources/darwin/bin/code.sh and there is no diff.

**Comment by bpasero** [comment]
@cdbattags are you using the integrated terminal or OS terminal? Can you see if you have an environment variable called `VSCODE_CWD` defined before launching VSCode in the terminal? And if yes, do you have steps how to reproduce reliably?

**Comment by cdbattags** [comment]
I'm using OS terminal.

```
echo $VSCODE_CWD
```
gives me an output of

```
/
```

**Comment by bpasero** [comment]
As I fail to understand how a environment variable we define inside a node.js script ends up defined in external terminals, I have just removed our support for defining the current working directory via `VSCODE_CWD`. I think if we want to support something like this going forward, it should be a command line argument.

//cc @joaomoreno (not sure whether you added this initially or me)

**Comment by joaomoreno** [comment]
@bpasero It's from `Hello Code` 🙈: https://github.com/microsoft/vscode/blame/9f9aa618acd2d5c4e5695410116205ae5ff71ce0/src/vs/workbench/electron-main/bootstrap.js#L17

I forgot what the reason for introducing that was.

**Comment by bpasero** [comment]
Yeah nevermind, it is gone now.

**Comment by cdbattags** [comment]
@bpasero thanks for jumping in on this! I fail to understand as well. How on Earth could an env variable set leak into the shell?

**Comment by rzhao271** [comment]
I repeated the original steps, and it says that I have not yet opened a folder. `$VSCODE_CWD` doesn't seem to be set to anything.

**Comment by bpasero** [comment]
@rzhao271 to clarify, you typed `code .` into a native macOS terminal and it opened only an empty window and no other windows?

**Comment by rzhao271** [comment]
Correct @bpasero

**Comment by bpasero** [comment]
@rzhao271 
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by rzhao271** [comment]
Verified. It seems to work even with just `code-insiders .` now. Might have been something flaky.
