### ISSUE TITLE
Unable to update the Visual Studio Code on MAC

### ISSUE THREAD

**Issue by CherukuriVinod** [microsoft/vscode#126316]
<img width="401" alt="Screen Shot 2021-06-14 at 8 30 47 PM" src="https://user-images.githubusercontent.com/76539497/121975347-6aa15300-cd4f-11eb-9da4-fdf00ec8b63a.png">
 Type: <b>Performance Issue</b>

Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 3822cc77-62db-427a-a164-9be4d3da6794|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	    90	 49299	code main
    1	    33	 49302	   gpu-process
    0	    16	 49303	   utility
   14	   164	 49305	   window (Welcome)
    0	     0	 49309	     /bin/bash -l
    0	    90	 49312	     extensionHost
   91	   139	 49314	   shared-process
    0	     0	 49324	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	    57	 49321	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.5.3
vscode-eslint|dba|2.1.16
vscode-pull-request-github|Git|0.22.0
dx-code-companion|Moh|0.4.7
salesforce-vscode-slds|sal|1.4.6
salesforcedx-vscode|sal|51.17.0
salesforcedx-vscode-apex|sal|51.17.0
salesforcedx-vscode-apex-debugger|sal|51.17.0
salesforcedx-vscode-apex-replay-debugger|sal|51.17.0
salesforcedx-vscode-core|sal|51.17.0
salesforcedx-vscode-lightning|sal|51.17.0
salesforcedx-vscode-lwc|sal|51.17.0
salesforcedx-vscode-visualforce|sal|51.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by japrozs** [comment]
This happens because your `VSCode` is not in the `Applications folder. To fix this, move your VScode install to the Application folder and restart it. After this, it will work just fine.

**Comment by joaomoreno** [comment]
The notification also has a link pointing to a resolution. Please let me know if that doesn't work.
