### ISSUE TITLE
Wrong icon for bash console

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#126379]
Vscode new terminal tabs sometimes use wrong 'console' icon for bash instead of expected 'bash' icon. This issue is from the following comment: https://github.com/microsoft/vscode/issues/10546#issuecomment-861445060

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Debian bullseye

Steps to Reproduce:

1. Open vscode
2. Create new terminal
3. See wrong icon:
![изображение](https://user-images.githubusercontent.com/22894169/122055445-4dbd5c00-cdf1-11eb-8df0-058a1ca2f6f4.png)

**Comment by Tyriar** [comment]
Repro is to opening bash on Linux without changing settings.

**Comment by stuartleeks** [comment]
Verified on Windows:

![image](https://user-images.githubusercontent.com/1824461/127466397-474131d6-8e76-4a1e-97f2-993f6c443852.png)

```
Version: 1.59.0-insider (user setup)
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:47.114Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

and Linux:

```
Version: 1.59.0-insider
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:02.250Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-80-generic
```
