### ISSUE TITLE
Download button asks folder for each file ignores last used path

### ISSUE THREAD

**Issue by ranieuwe** [microsoft/vscode#126346]
Issue Type: <b>Bug</b>

When downloading multiple files from a WSL/remote workspace, the download pop up comes up for each and every file. Additionally the save dialog does not utilize the last used/known path which is probably more of a feature request than a bug. 

![image](https://user-images.githubusercontent.com/2513121/122009128-a0096900-cd6e-11eb-94e8-e8dc08a8b282.png)

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (2.69GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/roeland/architecture-center-pr --remote=wsl+Ubuntu-20.04 --crash-reporter-id b6e94902-db78-40e1-8ed7-c647314ef2e0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.17GB (9.94GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.17GB (9.94GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.5
material-theme|zhu|3.10.14
vscode-sidebar|Acr|1.2.0
docs-changelog-generator|Ada|0.6.0
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.42.1
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.5
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.95
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.8
docs-yaml|doc|0.2.6
go|gol|0.25.1
csharp|ms-|1.23.12
vscode-yaml|red|0.19.2
code-spell-checker|str|1.10.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30267464
vsdfh931:30280409
vshan820:30294714
vscus158:30286553
vscod805:30301674

```

</details>

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
