### ISSUE TITLE
is the bug caused by trailing comma in settings.json released in the main build?

### ISSUE THREAD

**Issue by siraj-samsudeen** [microsoft/vscode#126330]
It is June 2021 and I am still getting this error whereas as per this thread, it was fixed and released in insiders build 2 years back. Has it gotten released in the release build? 

_Originally posted by @SHxKM in https://github.com/microsoft/vscode/issues/80419#issuecomment-538323487_

**Comment by NatoBoram** [comment]
The bug got released in the main builds, indeed. I'm using `Version: 1.57.0` right now and the bug is here.

**Comment by sandy081** [comment]
It shall be fixed in latest insiders and will be available in next stable (1.58.0) release.

**Comment by NatoBoram** [comment]
I'd like to confirm but VSCode Insiders recently broke

![image](https://user-images.githubusercontent.com/10495562/122479607-5fd9fe80-cf99-11eb-9a48-a3d4cab771ba.png)

Is there an issue about this one? Thanks!

**Comment by sandy081** [comment]
No. Please file a separate issue for that with necessary information to diagnose.
