### ISSUE TITLE
open new project when full screen error

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode#126355]
mac:11.4
vscode:  1.57.0

open project `1 ok` full screen and then `cmd+shift+n` to open new window, there two windows on mac, it should be one window, use tab switch projects.

![image](https://user-images.githubusercontent.com/7554917/122026595-f1f8d000-cdfc-11eb-9eba-f190c6a69d2b.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/126025
