### ISSUE TITLE
[Test API - UI]  "Show Result Output" should expand terminal output window if minimized

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#126324]
Issue Type: <b>Bug</b>
@connor4312 
Related to: https://github.com/microsoft/vscode/issues/107467

# Expected
Clicking `Show Result Output` will reveal the raw output of the test
# Actual
When clicking "Show Result Output" and the terminal window is minimized, the output displays but the terminal window is not restored, giving the appearance it does nothing. This may be confusing/frustrating to users who don't know it's being opened in a "pop under" fashion, so it should just provide focus since that is the intent of the user to view the output.

https://user-images.githubusercontent.com/15258962/121988829-e8655e80-cd4f-11eb-84c4-c855ddc0392e.mp4

VS Code version: Code - Insiders 1.58.0-insider (e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80, 2021-06-14T05:13:55.029Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (4.29GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/JGrote/Projects/vscode-pester-test-adapter --crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell-preview|ms-|2021.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
vscgsv2:30305091
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by connor4312** [comment]
fyi @Tyriar this is also a problem with the `Focus Terminal` command (where I borrowed this code from)

**Comment by connor4312** [comment]
I updated `terminalService.showPanel` to automatically expand the view if needed. Let me know if you have any concerns with this, I think this behavior is what's intended.

**Comment by TylerLeonhardt** [comment]
@JustinGrote do you wanna verify this one too?

**Comment by JustinGrote** [comment]
@TylerLeonhardt LGTM
