### ISSUE TITLE
Revisit global atomic reads and writes from user settings

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#126376]
Related - https://github.com/microsoft/vscode/issues/125970

Revisit global atomic reads and writes from user settings.

Ideally:

- it wouldn't be the main service doing the writes but some child process / shared process
- it wouldn't require to loop in a polling interval to detect empty reads

**Comment by bpasero** [comment]
Fyi, file service (local) is now implemented by the `electron-main` file system provider. So any write from any window is going into the same process. This does not apply to shared process, which is still node.js enabled and can write on its own.

**Comment by sandy081** [comment]
@bpasero Can we make Shared Process to go through main for fs, even though it is a node process?

**Comment by bpasero** [comment]
I would rather not want to put more load on the main process if we can avoid that.

**Comment by sandy081** [comment]
It means, I would have to manually redirect settings reads/writes from shared to main to achieve this (just like how I am doing now but going forward this manual redirection happens only in shared).

**Comment by bpasero** [comment]
Hm, if today all writes go through shared process, then we already have a single process, no? Maybe we should expose a `atomicWrite` method from the shared process?

**Comment by sandy081** [comment]
Just to clarify, today, all configuration writes are happening on main process. I am redirecting all renderers and shared process to main process. So, with file service moving to main process, I gain removing my redirections from renderers. But my redirection from shared process to main has to remain to achieve atomic writes for settings file. 

In addition, I also gain atomic reads for renderers which I am using following work around:

https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/services/configuration/browser/configuration.ts#L134-L141

It would be great if I can get atomic reads & writes also in shared process for settings file instead of me redirecting to main.

**Comment by bpasero** [comment]
@sandy081 

> I am redirecting all renderers and shared process to main process

Can you share where you do that in code?

To clarify: nothing really "moved" to the main process. We always had a `IFileService` in `electron-main` and a `DiskFileSystemProvider` for `file` protocol. The only thing that changed is that the renderer no longer creates a `DiskFileSystemProvider` but uses a "remote" file system provider (similar to remote server) that talks to the one in `electron-main`.

**Comment by sandy081** [comment]
> Can you share where you do that in code?

At present, I am queuing all settings file writes to main process through [IUserConfigurationFileService](https://github.com/microsoft/vscode/blob/51f636f90c112e975625d95657600a6bc6eafece/src/vs/platform/configuration/common/userConfigurationFileService.ts#L29) to avoid race conditions because settings file can be written from renderers and shared process (settings sync). I already shared code in my previous comment for preventing read race conditions and this is applied only in renderers.

> To clarify: nothing really "moved" to the main process. We always had a IFileService in electron-main and a DiskFileSystemProvider for file protocol. The only thing that changed is that the renderer no longer creates a DiskFileSystemProvider but uses a "remote" file system provider (similar to remote server) that talks to the one in electron-main.

Got it. If I understand correctly then all renderers will be connecting to the same file system provider instance on `electron-main`. In this case, can I expect using `atomic` flag will prevent the race conditions while reading the content of the same file from multiple processes?  Can I also expect writing into this file from multiple processes throws `FILE_MODIFIED_SINCE`   when there are parallel writes with same eTag for eg., 

My use case is that, I would be reading & writing into Settings file from multiple processes (renderers/shared process). So if I get above functionality from the file service, I can simply depend on file service read and write with atomic flag and `FILE_MODIFIED_SINCE` error respectively in these processes. So shared process also using remote fsp that talks to the one in `electron-main` for file protocol would serve my purpose.

**Comment by bpasero** [comment]
Hm, actually things will not work as I had thought originally: because atomic writes are only implemented within `IFileService` and not in the file system provider, the `atomic` option is pretty useless right now because it does not travel to the main process. In other words, it is only the file system provider that is now used shared across all windows and not the file service...

So even with my move to main process, `options.atomic` works exactly as before, it only guarantees write locking per renderer but not across all processes.

That brings me back to my idea of exposing a new method maybe in the `INativeHostService` or even a new `IFileService` for locked writing/reading that you could then use? It would only work for local file scheme though.

**Comment by sandy081** [comment]
> That brings me back to my idea of exposing a new method maybe in the INativeHostService or even a new IFileService for locked writing/reading that you could then use? It would only work for local file scheme though.

Yeah that will work for me, expecting this new service or method is also available in shared process.

**Comment by bpasero** [comment]
@sandy081 can you check if the new methods `INativeHostService#writeAtomic/readAtomic` would work for you? That service is available in workbench windows and shared process. I pushed that to branch `ben/126376` via https://github.com/microsoft/vscode/commit/1ca43c5a0900c28c44ba55e6051abee08d2604bb

**Comment by sandy081** [comment]
These methods are good to me but is it possible to have these atomic methods in `IFileService` by making atomic as a capability that only native fsp supports and redirects to `electron-main` ? This will make it easy to consume, otherwise I have to split my code which needs these methods into native & browser and also check for the scheme before calling.

**Comment by bpasero** [comment]
Well, arguably a file system provider should always ensure atomic reads/writes and it should not be an explicit capability. Now that the disk provider in the main process is used, I can probably add some protection to prevent a race between writing and reading, however this comes at the possible risk that a hanging write will cause a read to hang too. I think that was the original reason why `atomic` was made optional and I didn't want to add that for every file read...

**Comment by sandy081** [comment]
> I can probably add some protection to prevent a race between writing and reading

I like this and it will be useful in general for all resources. How about instead of blocking the read always, read it without waiting and if the contents are empty wait until write on the same file is finished and read? I think we are trying to prevent a specific case ie., file being read during truncation and scoping the protection to that specific scenario might be good enough. It is not often that a truncated file is read and also it is not often that reading an empty file and writing into the same file happens at the same time.

**Comment by bpasero** [comment]
Yeah I like that. The reason the file can be empty is the truncation that always happens in the beginning. From then on you would only get partial file contents if the file is larger the chunk size (which I think for us will be 8kb). Not sure about settings, but you might still then end up in corrupt reads.

**Comment by ryenus** [comment]
Or maybe use a lock file? like index.lock in Git?

**Comment by sandy081** [comment]
> Maybe a workaround for settings in general would be to retry reading if the file is not parseable as JSON?

It might be cumbersome as I read settings at multiple places.

**Comment by bpasero** [comment]
Let me investigate a bit further, but probably not before December milestone. I am not a big fan of lock files because they tend to stick around when the process crashes.

**Comment by ryenus** [comment]
> Let me investigate a bit further, but probably not before December milestone. I am not a big fan of lock files because they tend to stick around when the process crashes.

@bpasero, for Git and its lock file issue, you are right, since git processes are mostly short lived, so sometimes when there's one running longer than expected, people might become impatient and kill the process, ending up with a dangling lock file.

But VSCode processes are typically long lived, so there should be much less chance to have a lock file left over. Even if it does maybe VSCode can try to cleanup if one is found on startup?

**Comment by sandy081** [comment]
> remove atomic from file service and make it an implementation detail of the user data file system provider

We decided not to remove the last bullet. As other points have been taken care of. Closing this.

**Comment by bpasero** [comment]
Should there be a test plan item for this or verification needed? I wonder how to best test this.

**Comment by sandy081** [comment]
Agreed - its good to have a test plan item for this. I am not sure what is the best way to test it but I would atleast expect the basic features work. So will write a test plan item with some sanity testing.
