### ISSUE TITLE
Allow to switch workspaces from the explorer

### ISSUE THREAD

**Issue by baymaxhuang** [Microsoft/vscode#12631]
- VSCode Version: 1.5.3
- OS Version: windows 10

Steps to Reproduce:
1. If the opened directory (workspace) can be switched freely in the explorer, it will be more convenient.

**Comment by joaomoreno** [comment]
For `Open Recent`, try <kbd>Ctrl R</kbd>.

**Comment by schmuli** [comment]
You could try using [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension.

**Comment by mjbvz** [comment]
Closing as possibly resolved using the `Open Recent` command or the Project Manager extension
