### ISSUE TITLE
Node js auto attatch doesn't work on linux

### ISSUE THREAD

**Issue by DanielVenable** [microsoft/vscode#126322]
Issue Type: <b>Bug</b>

Create a file named "server.js". Inside the file, write:

    const { createServer } = require('http');

    createServer((req, res) => {
        res.statusCode = 200;
        res.end();
    }).listen(8000);

Set Auto Attach to "Smart".
In the embedded terminal, type "node server.js"

What should happen: the debugger should attach to the process.

What actually happens: the server runs, but the debugger does not attach.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.4.0-74-generic
Restricted Mode: No

**Comment by connor4312** [comment]
Do you see a ⚠️ icon in the upper right of the terminal? If so, that indicates that you need to restart the terminal to apply the environment variable changes necessary for auto attach.

**Comment by DanielVenable** [comment]
No.

**Comment by connor4312** [comment]
Can you share your bashrc/zshrc, and/or the value of the NODE_OPTIONS environment variable?

We've seen a few cases where users have had code in an rc file which overwrote NODE_OPTIONS which prevents auto attach from working.

**Comment by DanielVenable** [comment]
How do I find those?

**Comment by connor4312** [comment]
`echo $NODE_OPTIONS` will print the value of that variable. If you use bash, your bashrc is traditionally in `~/.bashrc`. If you use zsh, in `~/.zshrc`. Likewise for other shells.

**Comment by DanielVenable** [comment]
NODE_OPTIONS is "--require /home/daniel/.config/Code/User/workspaceStorage/eebbe9a1386482cd2481e43076b4f1b1/ms-vscode.js-debug/bootloader.js"

my bashrc file is [here](https://github.com/microsoft/vscode/files/6744047/bashrc.txt).

(I pasted it into a txt file because .bashrc files aren't supported.)

**Comment by connor4312** [comment]
Okay that looks right. Can you grab a gif so I can see what your setup looks like?

/gifPlease

**Comment by DanielVenable** [comment]
![recording](https://user-images.githubusercontent.com/37315423/124364229-e7a84580-dbf4-11eb-9773-8c0cee12b2e2.gif)

The debugger should attach to the process, but it doesn't.

**Comment by connor4312** [comment]
Hm, okay. Can you try toggling its status to "Disabled" and then back to "Smart", then running the `Developer: Toggle Developer Tools` command and letting me know if there are any errors in the Console view?

**Comment by DanielVenable** [comment]
I have a warning: "Overwriting extension
/usr/share/code/resources/app/extensions/ms-vscode.node-debug with
/home/daniel/.vscode/extensions/ms-vscode.node-debug-1.44.28."

Could that be it?

**Comment by connor4312** [comment]
That shouldn't affect anything

**Comment by DanielVenable** [comment]
It still doesn't work. What should I do now?

**Comment by connor4312** [comment]
Hm, can you confirm what `node --version` outputs?

**Comment by DanielVenable** [comment]
v14.15.4

**Comment by connor4312** [comment]
You may have hit https://github.com/microsoft/vscode-js-debug/pull/1107. Let me know if it still happens on the [nightly build](https://github.com/microsoft/vscode-js-debug/blob/main/.ci/nightly.yml). Thanks!

**Comment by DanielVenable** [comment]
It still doesn't work.
