### ISSUE TITLE
Command palette shows only the first OS keybinding listed in package.json for a given command

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode#126306]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0-insider
- OS Version: Linux x64 5.10.41-1-MANJARO snap

Steps to Reproduce:

1. Open command palette (`ctrl+shift+p`)
2. See a command with a keybinding for a different OS than the one you're running, indicated next to the command name

If a keybinding is defined with different bindings per OS in the package.json, it seems that only the first one defined is shown to the user in the command palette, rather than showing the correct keybinding for the user's OS. This has caused confusion with an extension I maintain.

With the below keybinding defined in Calva's package.json, it seems only the "mac" shortcut is shown in the command palette, regardless of the user's OS.

```json
{
    "command": "paredit.forwardSexp",
    "mac": "alt+right",
    "win": "ctrl+right",
    "linux": "ctrl+right",
    "when": "calva:keybindingsEnabled && editorLangId == clojure && editorTextFocus && paredit:keyMap =~ /original|strict/ && config.calva.paredit.hijackVSCodeDefaults && !calva:cursorInComment || calva:cursorAfterComment"
}
```

**Comment by ArturoDent** [comment]
Just for testing - because if I make a keybinding in vscode itself it complains if it is missing the `key` field and associated value - what happens if you add a `"key": "alt+right"` to your `package.json`?  Does it make a difference as to whether the correct one is shown in the Command Palette?

**Comment by bpasero** [comment]
@alexdima do I use this wrong?

https://github.com/microsoft/vscode/blob/dc4b317192d606fd244e6d7723b18249054ed13a/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L127-L127

That is how command palette get's to know the keybinding to render.

**Comment by bpringe** [comment]
If I add a `"key": "alt+right"` to the package.json for that binding, it still shows the Mac binding. Just to test another case since in the previous case the `key` value and the `mac` value are the same, I also added `"key": "ctrl+right"` to that binding (in place of the `key` value just mentioned), and it still shows the Mac binding.

**Comment by PEZ** [comment]
Here's some more info that I've copied over here from PR #126760 which I think I should close and maybe reopen when I have a better understanding of how things are wired.

Here's is the code from `keybindingResolver.ts` that eventually gets called when the command palette is summoned:

```typescript
	public lookupPrimaryKeybinding(commandId: string, context?: IContextKeyService): ResolvedKeybindingItem | null {
		let items = this._lookupMap.get(commandId);
		if (typeof items === 'undefined' || items.length === 0) {
			return null;
		}

		const itemMatchingContext = context &&
			Array.from(items).reverse().find(item => context.contextMatchesRules(item.when));
		return itemMatchingContext ?? items[items.length - 1];
	}
```

When the bug happens `context.contextMatchesRules()` fails to match any of te bindings that are returned from `this._lookupMap.get()`. Which leads to a ”best guess” fallback, which does not have enough information for making an informed guess. I saw somewhere that it should go in specificity order. And when both alternatives available for the fallback are equally specific, all bets are off.

Here are the two bindings defined for the case mentioned in OP:

```json
            {
                "command": "paredit.forwardSexp",
                "mac": "alt+right",
                "win": "ctrl+right",
                "linux": "ctrl+right",
                "when": "calva:keybindingsEnabled && editorLangId == clojure && editorTextFocus && paredit:keyMap =~ /original|strict/ && config.calva.paredit.hijackVSCodeDefaults && !calva:cursorInComment || calva:cursorAfterComment"
            },
            {
                "command": "paredit.forwardSexp",
                "mac": "ctrl+right",
                "win": "alt+right",
                "linux": "alt+right",
                "when": "calva:keybindingsEnabled && editorLangId == clojure && editorTextFocus && paredit:keyMap =~ /original|strict/ && !config.calva.paredit.hijackVSCodeDefaults && !calva:cursorInComment || calva:cursorAfterComment"
            },
```

They are equally specific, only differing in wether `config.calva.paredit.hijackVSCodeDefaults` should be true or false, giving the command palette and other call sites an arbitrary binding alternative.

However, whatever is translating the actual keyboard events successfully interprets the context and the `when` clauses of the alternatives. So we shouldn't have to be guessing at all here.

I notice that `editorTextFocus` is false in some cases where I expect it to be true. Could it be that when the command palette is rendered, `editorTextFocus` is no longer true, causing both `when` clauses to fail, and that is why we are down to guessing?

**Comment by PEZ** [comment]
No, it is not about the `editorTextFocus`. I tested with a version of Calva that only checks `config.calva.paredit.hijackVSCodeDefaults` for the `paredit.forwardSexp` command. 

```json
            {
                "command": "paredit.forwardSexp",
                "mac": "alt+right",
                "win": "ctrl+right",
                "linux": "ctrl+right",
                "when": "config.calva.paredit.hijackVSCodeDefaults"
            },
            {
                "command": "paredit.forwardSexp",
                "mac": "ctrl+right",
                "win": "alt+right",
                "linux": "alt+right",
                "when": "!config.calva.paredit.hijackVSCodeDefaults"
            },
```

I'm on a Mac and have left the `hijackVSCodeDefaults` settings with its default value of `true`.

*Expected:* Command Palette shows binding `⌥→` (The active binding.)

*Actual:* Command Palette shows shows binding `⌃→` (A non-active binding.)

**Comment by PEZ** [comment]
OK. So the when clause is never taken into account for this command, afaict. I can catch the call to here:

https://github.com/microsoft/vscode/blob/60ad49e4dce16291018e8f02438769ab54b5bc89/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L127

And since there is no `context` provided, `itemMatchingContext` in `keybindingResolver.ts` will always evaluate tp false.

**Comment by bpasero** [comment]
I wonder if - at least for the editor provided commands - we should pass the context key service of the active editor control. somewhere here: 

https://github.com/microsoft/vscode/blob/317a9388d4d09131d569bf374ac0b5c3f39e96e9/src/vs/editor/contrib/quickAccess/commandsQuickAccess.ts#L33-L33

**Comment by PEZ** [comment]
It might not be the whole story. When using the same lookup function from `developerActions` I provide a context, but then the match fails.

https://github.com/PEZ/vscode/blob/9a8791ab8cd27fcbaa23588a2165a976ba63c3ca/src/vs/workbench/browser/actions/developerActions.ts#L233

But, of course, without a context it will never get a chance to fail. 😄

**Comment by PEZ** [comment]
@bpasero, just because this one intrigues me (and that Calva is suffering quite bad from it) I spent some little more time based off of your hint about passing the context key service of the active editor control. That control does not have a context key service, afaict. I tried some different ways to pass it along, but after a while it gets ridiculous. So far I only seem to find how to grab the context from the accessor, quite early in the call chain. Am I missing something obvious?

**Comment by bpasero** [comment]
@PEZ can we isolate this to a easier repro? Here is what I try: I configure platform specific keybindings in my keybindings file:

```json
{
    "key": "ctrl+b",
    "command": "editor.action.addSelectionToNextFindMatch",
    "when": "editorFocus && isWindows"
},
{
    "key": "cmd+b",
    "command": "editor.action.addSelectionToNextFindMatch",
    "when": "editorFocus && isLinux"
},
{
    "key": "alt+b",
    "command": "editor.action.addSelectionToNextFindMatch",
    "when": "editorFocus && isMac"
}
```

When I see the command palette, the keybinding actually seems to be correct for my platform (macOS):

![image](https://user-images.githubusercontent.com/900690/122892626-d6824d80-d345-11eb-867b-78c86a604f85.png)

From all the users of `IKeybindingsService.lookupKeybinding` none is passing in a context key service, so I doubt this would be the right fix unless I misunderstand things.

Do you have a more isolate smaller example based on user settings?

**Comment by PEZ** [comment]
Good idea, @bpasero! Contrast these two settings:

A:

```json
    {
        "key": "alt+b",
        "command": "editor.action.addSelectionToNextFindMatch",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+b",
        "command": "editor.action.addSelectionToNextFindMatch",
        "when": "!editorFocus"
    },
```

B:

```json
    {
        "key": "alt+b",
        "command": "editor.action.addSelectionToNextFindMatch",
        "when": "!editorFocus"
    },
    {
        "key": "ctrl+b",
        "command": "editor.action.addSelectionToNextFindMatch",
        "when": "editorFocus"
    },
```

If you summon the palette from an editor with focus, you'd expect that `alt+b` was displayed for setting **A**. And at the very least you'd expect that if you have settings **B**, it would change what is displayed. Instead `ctrl+b` is displayed both times.

I'm a bit puzzled why your example does not expose the error, even if I move the mac-binding to the beginning...

**Comment by alexdima** [comment]
Hey, apologies for responding slowly, as I did not have a Linux machine immediately ready to test, but I cannot reproduce. I am trying with the original steps and have created an extension with the following `package.json`:

```
{
    "name": "126306",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.22.0"
    },
    "contributes": {
        "commands": [{
            "command": "paredit.forwardSexp",
            "title": "My command"
        }],
        "keybindings": [{
            "command": "paredit.forwardSexp",
            "mac": "alt+right",
            "win": "ctrl+right",
            "linux": "ctrl+right",
            "when": "calva:keybindingsEnabled && editorLangId == clojure && editorTextFocus && paredit:keyMap =~ /original|strict/ && config.calva.paredit.hijackVSCodeDefaults && !calva:cursorInComment || calva:cursorAfterComment"
        }]
    }
}
``` 

On Linux, when triggering the command palette, `ctrl+right` is rendered as the keybinding next to the `My command` command:

![image](https://user-images.githubusercontent.com/5047891/122933066-9388a000-d36e-11eb-993a-0a5d80b56666.png)

**Comment by PEZ** [comment]
@alexdima see my previous comment for a repro.

In Calva the users can configure how ”aggressive” the hi-jacking of ”standard” keyboard bindings should be in favour of structural editing, via the `calva.paredit.hijackVSCodeDefaults` setting. Some users thinks it makes perfect sense that the standard behaviour of `alt+left/right` (on mac) and `ctrl+left/righ` (on windows and linux) behave structurally in a LISP language. Others think it is super weird that those shortcuts don't behave non-structural.

Let's take the Mac as the example. The former group will leave`calva.paredit.hijackVSCodeDefaults` at its default. They then use `alt+right` to move forward by sexpression. But in the command palette `ctrl+right` is displayed. Which causes major confusion and support time. And similarly for Windows users, they will see `alt+right in the palette, when the real binding is `ctrl+right`.

**Comment by PEZ** [comment]
This also gets weird for my PR #126742 (displaying command titles for shortcuts) which uses the same function to get the bindings for the command. Here I have just pressed `alt+right`:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/30010/122959534-5e3a7d00-d383-11eb-8ce0-be0228a8d347.png">

**Comment by alexdima** [comment]
> If you summon the palette from an editor with focus, you'd expect that `alt+b` was displayed for setting **A**. And at the very least you'd expect that if you have settings **B**, it would change what is displayed. Instead `ctrl+b` is displayed both times.

I can see that you might expect that, but that is not what we have built. Our displayed keybindings do not reflect the current context. The reverse keyboard lookup is meant to be context-free. The idea of the reverse lookup is that it is supposed to help people discover what keybindings could trigger an action, and it is not meant to be a precise indicator of what keybindings are active in the current focused dom element (in the current context).

Here is a default shortcut that VS Code ships with:
```
{ "key": "cmd+/",     "command": "editor.action.commentLine",
                      "when": "editorTextFocus && !editorReadonly" },
```
We want to display <kbd>cmd</kbd>+<kbd>/</kbd> next to this action in all cases, even when the cursor is not blinking in the editor, even if the editor is read only. We want to display this keybinding even if there is no editor. That is because the intent is to help users discover the keybindings:

![image](https://user-images.githubusercontent.com/5047891/122963622-bd4dc100-d386-11eb-8ce9-b26d8c225329.png)

**Comment by PEZ** [comment]
@alexdima, I see. It defeats its purpose to discover the wrong keybinding, though, wouldn't you agree? It seems to me that in this case we can both eat the cake and have it.

The way this code is written:

```typescript
		const itemMatchingContext = context &&
			Array.from(items).reverse().find(item => context.contextMatchesRules(item.when));
		return itemMatchingContext ?? items[items.length - 1];
```

In the case the context is matched the command palette would display the right keybinding and in the case it does not match it would fall back on the current behaviour, so the bindings would always be discoverable.

**Comment by bpringe** [comment]
This way of relating an OS to a keybinding might work for us (using the when clause): https://github.com/microsoft/vscode/issues/126306#issuecomment-865739722

That's not, however, the original issue, which is specifically about using the OS keys like `"mac"`, etc.

**Comment by alexdima** [comment]
>  It seems to me that in this case we can both eat the cake and have it.

You're absolutely correct! I'm sorry about that, I just got myself up to speed with the changes from https://github.com/microsoft/vscode/commit/450e5d164e40334d599a17ccb0e47e9cb92c5e27#diff-1bea564a53de9969cb7e8758c4a6d68e3f57fbcd6302f4761338f63cd4fc1f42 , I must have missed the notification for those. 

It is possible that this would take a performance hit, but I have pushed a change to use the global `IContextKeyService` when a context key service is not passed in. 

To verify, configure in `keybindings.json`:
```
  { "key": "cmd+shift+A", "command": "actions.find", "when": "config.specialValue == 'A'" },
  { "key": "cmd+shift+B", "command": "actions.find", "when": "config.specialValue == 'B'" },
  { "key": "cmd+shift+C", "command": "actions.find", "when": "config.specialValue == 'C'" },
```
And in `settings.json`:
```
  "specialValue": "B",
```
And then open the command pallette and search for `Find`. Observe how out of the 3 possible keybindings, `cmd+shift+B` is preferred:

![image](https://user-images.githubusercontent.com/5047891/123277105-17c15b80-d506-11eb-85c6-8624fa8ae9d0.png)

cc @eamodio I remember you were asking for something similar.

**Comment by eamodio** [comment]
Awesome! I can't wait to try this out.

Here is that other issue for reference: https://github.com/microsoft/vscode/issues/40389

**Comment by eamodio** [comment]
@alexdima 😢 -- this doesn't help my case, since some of the context keys in the `when` clause are not available in the global service -- which causes the whole expression to be false.

As a hack, I tried adding a new code path that would evaluate the `when` and keep track of the number of items that evaluated to `true` before a `false` value  as a way of ranking them -- more `true`'s = better match (since I always have the first item as the config value that controls the overall binding). But since we normalize and reorder the expressions, it doesn't help either, unless we evaluate all the parts individually -- which we definitely don't want to do that because of the perf impact.

**Comment by PEZ** [comment]
You think it is the same issue that I run into here, @eamodio? #126742
