### ISSUE TITLE
Tasks suggestions

### ISSUE THREAD

**Issue by japrozs** [microsoft/vscode#126338]
HI, I'm new to the VScode OSS community. Can one of the maintainers please assign me a task as I want to contribute to VSCode and become a contributor.

**Comment by mjbvz** [comment]
[This document covers contributions]( https://github.com/microsoft/vscode/wiki/How-to-Contribute)

A good place to start are issues tagged `Help wanted` or `good first issue`. For larger changes/fixes, make sure to post a comment on the issue double checking that a PR would be  accepted
