### ISSUE TITLE
Unable to close terminal while running notebook

### ISSUE THREAD

**Issue by bkuriach** [microsoft/vscode#126369]
Issue Type: <b>Bug</b>

While running jupyter notebooks, I tried to close the terminal to save more space. But each time I close, it opens again within few seconds. I was able to close it until yesterday. Using VSCode pointing to AML compute.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1047-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/bkuriachan/Projects --remote=wsl+Ubuntu-20.04 --crash-reporter-id bb5a6bf5-d714-48a5-9eba-811de0544190|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: bkuriachan-cpu|
|OS|Linux x64 5.4.0-1047-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|13.67GB (4.46GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ai-remote|ms-|0.3.0
remote-containers|ms-|0.183.0
remote-wsl|ms-|0.56.5
notepadplusplus-keybindings|ms-|1.0.7
vscode-icons|vsc|11.5.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
vscode-ai|ms-|0.6.23
vscode-ai-remote|ms-|0.3.0
azure-account|ms-|0.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805cf:30301675

```

</details>

**Comment by rebornix** [comment]
@bkuriach can you share more details like a screen recording, or how you close the terminal, etc?

**Comment by bkuriach** [comment]
I had multiple vscode IDEs opened that moment. Looks like issue got resolved after restarting. In case if I face it again, will raise separately.

Thank you!
