### ISSUE TITLE
Upgrade breaks style and setup

### ISSUE THREAD

**Issue by icfly2** [microsoft/vscode#126386]
Issue Type: <b>Bug</b>

Upgrade to latest version of VS code.

This changes the theme from light to dark.
Changes the side of the command bar to the left.
Makes autoformating in html files break jinja2 templates.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (8.05GB free)|
|Process Argv|--crash-reporter-id cdb5c926-84a2-49e0-80d4-80a09e554208|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|SSH: thebeast.sxp.saxopayments.com|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (40 x 2399)|
|Memory (System)|226.73GB (61.28GB free)|
|VM|4%|

|Item|Value|
|---|---|
|Remote|SSH: thebeast.sxp.saxopayments.com|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (40 x 2399)|
|Memory (System)|226.73GB (61.28GB free)|
|VM|4%|

|Item|Value|
|---|---|
|Remote|SSH: thebeast.sxp.saxopayments.com|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (40 x 2399)|
|Memory (System)|226.73GB (61.28GB free)|
|VM|4%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cypher-query-language|jak|1.0.2
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
mssql|ms-|1.10.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999230701
azure-account|ms-|0.9.8
vscode-yaml|red|0.19.2
sql|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by lramos15** [comment]
By any chance did your settings get cleared? Read https://github.com/microsoft/vscode/issues/125970 for more info

**Comment by icfly2** [comment]
I'm assuming it has the same cause / are related so yeah, another victim of the same bug / behaviour.
