### ISSUE TITLE
Tasks close despite "presentation": {"close": false}

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#126352]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Windows 10

Steps to Reproduce:

1. Launch a task with the new  `"presentation": {"close": false}`
2. Observe that the task closes after finishing, same as with `"presentation": {"close": true}`. It does not close when you remove `"close": false`. 7a92985cde8232f6fc9c72ae5d7ad30e273ad67d may be related.

**Comment by alexr00** [comment]
Thank you for filing this issue. For now, simply deleting the `"close": false` will prevent the task from closing.

**Comment by bersbersbers** [comment]
Thanks!
