### ISSUE TITLE
Get Underlying Shell Exit code or get child process pid

### ISSUE THREAD

**Issue by YaduAhuja** [microsoft/vscode#126397]
Currently, I am working on an extension that enables the user to generate the compile and run command which is then passed in the integrated terminal by the `Terminal.sendText` method.

Problem is that extension is not able to know whether the program is running or not. I want to know if there is any way to get the child process id or we can implement a callback function that will be called when the child process stops executing.

**Comment by Tyriar** [comment]
`Terminal.exitStatus` now exists on the latest version:

https://github.com/microsoft/vscode/blob/eccf1354a9d22ca73619c4a1786f541dcbc27e58/src/vs/vscode.d.ts#L5759-L5759

You could also potentially use tasks.

If you want the exit code of a program running within the shell via `sendText` that's not possible
