### ISSUE TITLE
Right Click in Explorer to Open Folder Causes Error

### ISSUE THREAD

**Issue by niallermoran** [microsoft/vscode#126378]
![vscodeissue](https://user-images.githubusercontent.com/9823154/122055443-899bf580-cde0-11eb-9f06-618f7cec89fd.PNG)
Issue Type: <b>Bug</b>

In windows explorer in any folder right click
Click open with code
receive error message about missing module

This only started to happen today after using VS code for quite a while. Opening VS code from the executable works fine.

I have checked folder C:\Program Files\Microsoft VS Code\resources\app\out and no main folder or file exists there

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (18.01GB free)|
|Process Argv|--crash-reporter-id e501de35-245d-4f79-a4f8-627e442c4bd5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
cloudcode|goo|1.12.1
vscode-azureappservice|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.13.0
remote-wsl|ms-|0.56.5
azure-account|ms-|0.9.8
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.5.1
java|red|0.79.2
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
markdown-all-in-one|yzh|3.4.0
![vscodeissue](https://user-images.githubusercontent.com/9823154/122054992-17c3ac00-cde0-11eb-9f6c-bac25a8b2f46.PNG)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vspre833:30321513
vshan820:30294714
vscorecescf:30290706
vscus158:30321503
vscod805cf:30301675

```

</details>

**Comment by heartacker** [comment]
me too

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
