### ISSUE TITLE
Terminal cannot show character '_' when reaches the bottom of vscode terminal view

### ISSUE THREAD

**Issue by ComradeProgrammer** [microsoft/vscode#126350]
how to reproduce the bug:
update your vscode to latest version(vscode for linux, i am using ubuntu 20.04)
just open a bash terminal via vscode and input some command
when the command line reach the bottom of vscode terminal view
the character '_' will be shown as a ' '(space)
for example if I input cp libINET_dbg.so  ~/workspace/copy/myndn/
i actually see cp libINET dbg.so  ~/workspace/copy/myndn/
but if I press enter( this line leaves the bottom of the terminal)
i can see _ again

system info:

PUs | Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3797)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 1, 2, 2
Memory (System) | 15.57GB (1.28GB free)
Process Argv | --unity-launch --crash-reporter-id 6b29594c-6277-49d1-bc74-b7e435987bb3
Screen Reader | no
VM | 0%

extensions:

Extension | Author (truncated) | Version
-- | -- | --
python | ms- | 2021.5.926500501
vscode-pylance | ms- | 2021.6.1
jupyter | ms- | 2021.6.999230701
remote-ssh | ms- | 0.65.7
remote-ssh-edit | ms- | 0.65.7
cmake-tools | ms- | 1.7.3
cpptools | ms- | 1.4.1
omnetpp-ned | sch | 0.0.4
cmake | twx | 0.0.17

a/b experiment info
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

**Comment by paketb0te** [comment]
This is actually not a duplicate - I was able to fix the issues described in #123077 with the provided workaround (setting `terminal.integrated.gpuAcceleration` to "on"), but when reaching the bottom of the terminal, the underscores are hidden again :disappointed:
