### ISSUE TITLE
Visual Studio Code only runs from Administrator command prompt

### ISSUE THREAD

**Issue by hickford** [Microsoft/vscode#12636]
- VSCode Version: 1.5.3
- OS Version: Windows 7

Whenever I open Visual Studio Code, it immediately crashes "The window has crashed". Clicking the 'Reopen' button just repeats the error.

The only way I can get Visual Studio code to work is to launch `"C:\Program Files (x86)\Microsoft VS Code\Code.exe"` from an Administrator command prompt.

![image](https://cloud.githubusercontent.com/assets/105314/18836349/88eb2332-83f7-11e6-8a59-10523611836e.png)

**Comment by bpasero** [comment]
Does it reproduce using our insider release? !!! PLEASE DO NOT RUN IT AS ADMINISTRATOR !!!

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by hickford** [comment]
@bpasero Yes I can reproduce with `VSCode-win32-insider.zip` from http://code.visualstudio.com/insiders

**Comment by bpasero** [comment]
@hickford when you run "code -n" from the command line, does that work? Not as administrator I mean.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
