### ISSUE TITLE
Feature request - Icon set - PowerShell icons

### ISSUE THREAD

**Issue by Makovec** [Microsoft/vscode#12638]
I like the new Icon set feature a lot. I was looking to Set UI if will be able to extend it to PowerShell but I failed.

Would be nice if there will be new icon for PowerShell language for following extensions:

- ps1
- psm1
- psd1
- ps1xml

Thanks
David

**Comment by joaomoreno** [comment]
Which Icon Theme are you referring to?

**Comment by Makovec** [comment]
To File Icon Theme Seti.

**Comment by aeschli** [comment]
Our Seti theme is created from https://github.com/jesseweed/seti-ui. We'd like to not have our own fork. Please create the request there. Once your request has been accepted there, I'll happily update the Seti theme.
