### ISSUE TITLE
A switch that can set `index` file on the top of all files on current folder.

### ISSUE THREAD

**Issue by HuberTRoy** [microsoft/vscode#126349]
I often write an index file to descript something for all other files in this folder or just be a re-export file, when the files increates more and more, the index file will also more and more hidden and finanlly invisible in the files ocean.

I know vscode has search feature but I often often often forget to use it....

**Comment by yume-chan** [comment]
Another request same as #108452

> Closing as duplicate of more explorer sorting options.
> Thouhg we will probably not tackle this exact request.

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/108452#issuecomment-712869222_

**Comment by HuberTRoy** [comment]
@yume-chan sadlly...
