### ISSUE TITLE
style of href in <a> tag

### ISSUE THREAD

**Issue by alanwei0** [Microsoft/vscode#12641]
i have a html template file, when i set the `href` attribute with a variable which contains underlines like `$product_center_url`, the underline can hardly be seen.

![image](https://cloud.githubusercontent.com/assets/3991105/18838273/730a4ccc-8439-11e6-8f65-c3430c42fcfd.png)

- VSCode Version: 1.6.0-insiders
- OS Version: macos 10.12

**Comment by joaomoreno** [comment]
By _underline_, the user means **underscore** (`_`).

**Comment by alanwei0** [comment]
haha, my weak english......

**Comment by alexandrudima** [comment]
Let's track in #12226
