### ISSUE TITLE
Local directory mapped to a drive - cannot find in Admin mode

### ISSUE THREAD

**Issue by azriels** [microsoft/vscode#126409]
Issue Type: <b>Bug</b>

I mapped local directory to a drive letter:
    subst K: C:\sql\k

When VSC in 'normal' mode:
    PS C:\> cd k:\
    PS K:\>

When VSC in Admin mode:
    PS C:\> cd k:\
    Set-Location: Cannot find drive. A drive with the name 'k' does not exist.
    PS C:\> 

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.22GB free)|
|Process Argv|--crash-reporter-id e61c7657-b1c0-402b-8d77-3464af6a593c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
how does this related to vscode? isn't that a bug to report against windows?

**Comment by azriels** [comment]
You are right - I did not think about it, just came across this problem using vscode. I tried command prompt, admin and regular, and admin has the same issue.
