### ISSUE TITLE
Add file association icons for easy viewing, Thank you! Something like that

### ISSUE THREAD

**Issue by dylumian** [microsoft/vscode#126480]
![association ](https://user-images.githubusercontent.com/37278466/122230165-f8b24080-ceeb-11eb-9f31-feebbcc5b777.png)

**Comment by isidorn** [comment]
We already have icons in the product, just pick a file icon theme.
If you mean icons in the native OS finder, we can not control that nicely from VS Code as far as I know. Though @joaomoreno can correct me here

Closing
