### ISSUE TITLE
Provide a way to add tasks to the status bar

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#126447]
Some things to consider:
- Should this be configurable via setting?
- How should multiple tasks be displayed?
- Should this be configurable through the "Run Task" command, similar to the gear?
![image](https://user-images.githubusercontent.com/38270282/122171860-7c364800-ce80-11eb-894a-658380e7d1c0.png)

**Comment by alexr00** [comment]
@hediet I know you also put tasks in the status bar. How do you configure that?

**Comment by hediet** [comment]
@alexr00 [I created an extension for this](https://marketplace.visualstudio.com/items?itemName=hediet.tasks-statusbar&ssr=false).

This extension has a configurable regex that can be set to filter tasks. I usually have a `dev` task for all my projects, so a global `dev` filter is a nice default for me.

I think configuration which tasks to show there should not be checked in into SCM - at least it should be overridable per user.

**Comment by hediet** [comment]
![image](https://user-images.githubusercontent.com/2931520/122182121-472ef300-ce8a-11eb-809c-991e2d537db3.png)

Personally, I even put the "Kill" task into the status bar, so I can quickly restart the build deamon. If the main build task would be already configured in workspace settings in the vscode repo, could I add this "Kill" task without touching the workspace config?

I like that the most important tasks can be put into the status bar by the opened repository, but it would be important for me that users can override/customize that without needing to change the workspace setting.

**Comment by hediet** [comment]
> I think for multiple tasks I would prefer that they be in a quick pick with only one status bar entry.

I understand the reasoning, and I guess this is just personal preference, but I found it really nice to start/stop the task with a single click and to see if the task is active by looking at the status bar entry - without having to go to some different menu.

---

Unrelated: It would be nice to get rid of the `Kill VS Code - Build` Task. This could be done if tasks could be killed explictly (if the user explictly asks VS Code to kill the task) or implicitly (if the user restarts VS Code/closes the terminal the task runs in) and if a task can distinguish between both kill-modes.

**Comment by alexr00** [comment]
The `Kill VS Code - Build` task is needed because that `VS Code - Build` task runs the npm script is `deemon yarn watch`, which very specifically doesn't let itself be killed (intentionally). If you don't like the task that needs to be explicitly killed like that you can run the `npm: watch` task instead, which doesn't have this behavior.
