### ISSUE TITLE
Synchronizing settings

### ISSUE THREAD

**Issue by youra-h** [microsoft/vscode#126496]
Issue Type: <b>Bug</b>

The home laptop was syncing with Github. I came to a new place of work. I thought that synchronization would happen now and I would start working. He tried to load 32 extensions. Downloaded legacy extensions that I removed 2 years ago. But I didn't download the main ones I use. As a result, only 24 out of 32 remained, some of which are outdated.
I was hoping it hadn't had time to sync the current settings with Github. I deleted everything, cleaned all the folders. Reinstalled VS Code. I activate my account and it loads 24 extensions. Bitch! Among which all are the same deleted 2 years ago.
For the sake of experiment. VS Code only managed to install 16 extensions, I clicked the Restart button. VS Code rebooted and synced the 16 current extensions and finished syncing.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Turion(tm) II Ultra Dual-Core Mobile M620 (2 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.94GB free)|
|Process Argv|--crash-reporter-id 51cbf438-ca0f-4a68-805e-6e18c51b3df5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-eslint|dba|2.1.23
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
yii2-snippets|ima|0.1.2
easy-icons|jam|0.3.1
php-cs-fixer|jun|0.1.158
php-namespace-resolver|Meh|1.1.8
vscode-language-pack-ru|MS-|1.57.1
vscode-typescript-tslint-plugin|ms-|1.3.3
fix-json|oli|0.1.2
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805:30301674

```

</details>

**Comment by sandy081** [comment]
@youra-h It was not clear to me what was not synced. Can you please explain more clearly what is not working, may be by mentioning which extensions did not get sync?
