### ISSUE TITLE
Test: panels in sidebar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12643]
- [x] Any os @bpasero (would like to test it)
- [x] Any os @seanmcbreen 

Complexity: 2

We are trying to make panels more discoverable and more connected between them, more details: #12277
This feature is currently experimental, thus enable it via setting `workbench.panels.showInSidebar`. Verify:

* All panels are shown as collapsed in the sidebar when the panel is hidden. If the panel is visible all panels are visible in the sidebar
* Problems view notifications are shown in the sidebar (even if the panel is hidden)
* All interactions via the sidebar makes sense and makes for a smooth ui (focus passed, active panel highlighted, automatic expansion / collapse based on panel visibility)

Current icons are temporary and all icon feedback should be sent to @bgashler1 
@bpasero

**Comment by seanmcbreen** [comment]
Works as expected
