### ISSUE TITLE
Settings sync sign-in with microsoft redirects to localhost

### ISSUE THREAD

**Issue by harshvchawla** [microsoft/vscode#126400]
Issue Type: <b>Bug</b>

Just installed VSCode; trying to enable settings sync using Microsoft sync but it redirects to localhost and nothing happens

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.66GB free)|
|Process Argv|--crash-reporter-id 486c08de-f17f-4f17-b994-ae2943698731|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.4.0
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
remote-containers|ms-|0.183.0
notepadplusplus-keybindings|ms-|1.0.7
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.1
vscode-yaml|red|0.19.2

</details>

This recording shows the issue
https://user-images.githubusercontent.com/6857593/122093363-df13da80-cdbf-11eb-859b-c753ce2fe5b2.mp4

**Comment by harshvchawla** [comment]
This link gets opened: https://localhost:62992/signin?nonce=<some nonce code>

**Comment by yume-chan** [comment]
Related: #114055

Redirecting to `localhost` is expected, Code spawns an HTTP server to receive your Microsoft Account login result (although I don't know why it doesn't use custom protocol handler, as I remember Microsoft Graph login API does support custom schema as redirect url). Anyway, it should be `http://`, not `https://`.

My guess is that Chrome, or some browser extension, automatically redirected `http://localhost:XXXX` to https. Do you have such an extension?

**Comment by TylerLeonhardt** [comment]
@yume-chan nice catch. I'm suspicious of that lock in @harshvchawla's chrome titlebar:

![image](https://user-images.githubusercontent.com/2644648/122259498-1a2d1100-ce87-11eb-8065-1a4844d2161d.png)

**Comment by harshvchawla** [comment]
I agree how chrome mandatorily converts to https now; firefox saved the day
thanks @yume-chan
