### ISSUE TITLE
intellisense not working and does not take automatic values

### ISSUE THREAD

**Issue by oneshhh** [microsoft/vscode#126453]
i installed js node 17. something and after that my vscode is not working correctly i dont get suggestion based on what i write and aslo the tab + suggestion is also not working it happened suddenly and now i can find a way to fix it please help.
heres the error message.
electron/js2c/renderer_init.js:65 The vm module of Node.js is deprecated in the renderer process and will be removed. vscode

**Comment by oneshhh** [comment]
electron/js2c/renderer_init.js:65 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:65
workbench.desktop.main.js:sourcemap:62 [Extension Host] (node:640) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
S @ workbench.desktop.main.js:sourcemap:62
workbench.desktop.main.js:sourcemap:2943 Extension Host
workbench.desktop.main.js:sourcemap:2943 dyld: lazy symbol binding failed: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylibdyld: Symbol not found: _pthread_chdir_np  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/../../../Electron Framework.framework/Electron Framework  Expected in: /usr/lib/libSystem.B.dylib
workbench.desktop.main.js:sourcemap:2938 Extension host terminated unexpectedly. Code:  null  Signal:  SIGTRAP
_onExtensionHostCrashed @ workbench.desktop.main.js:sourcemap:2938
workbench.desktop.main.js:sourcemap:627   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.emmet, vscode.html-language-features, vscode.debug-auto-launch, vscode.git, ritwickdey.LiveServer
workbench.desktop.main.js:sourcemap:741 Extension host terminated unexpectedly.
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:741
workbench.desktop.main.js:sourcemap:627   ERR Error: No authentication provider 'microsoft' is currently registered.
    at O.getSessions (workbench.desktop.main.js:sourcemap:2000)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async bi.getAccounts (workbench.desktop.main.js:sourcemap:2417)
    at async bi.update (workbench.desktop.main.js:sourcemap:2417)
    at async bi.initialize (workbench.desktop.main.js:sourcemap:2417)
    at async bi.waitAndInitialize (workbench.desktop.main.js:sourcemap:2417)
workbench.desktop.main.js:sourcemap:627  WARN Settings Sync: Accounts are not initialized
workbench.desktop.main.js:sourcemap:568 IPC "Search" crashed with exit code null and signal SIGTRAP
(anonymous) @ workbench.desktop.main.js:source map:568


this are the all the info i know, please help! i can't find any solutions

**Comment by mjbvz** [comment]
Please fill in the issue template and provide steps to reproduce the issue
