### ISSUE TITLE
Notebook doesn't show as dirty when it is dirty

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#126460]
from https://github.com/microsoft/vscode/issues/120284

* open a notebook file
* open an untitled file
* reload
* while the unititled file shows, run an extension command as shown below
* the notebook editor isn't mark as dirty

I have debugged this till [here](https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/services/workingCopy/common/storedFileWorkingCopy.ts#L696) and everything seems correct, e.g dirty states are `true`

```ts
const docUri = vscode.Uri.file('/pathToVscode/vscode/.vscode/notebooks/api.github-issues');
const cellUri = docUri.with({ scheme: 'vscode-notebook-cell', fragment: 'ch0000001' });
const cellDoc = await vscode.workspace.openTextDocument(cellUri);
await vscode.languages.setTextDocumentLanguage(cellDoc, 'css');
```

**Comment by bpasero** [comment]
@jrieken my guess would be that the working copy for notebooks gets created and works just fine, but the notebook editor input does not connect to that working copy and does not report dirty state. The editor area only considers a tab dirty when the editor input reports that.

In file land I solve this like so:
* [listen](https://github.com/microsoft/vscode/blob/e47d24f0a773999a51597def6b4cc7d00f7a6ebf/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L116-L116) to file models becoming alive from within the editor input
* [accept](https://github.com/microsoft/vscode/blob/e47d24f0a773999a51597def6b4cc7d00f7a6ebf/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L129-L129) the model into the input when created
* [register](https://github.com/microsoft/vscode/blob/e47d24f0a773999a51597def6b4cc7d00f7a6ebf/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L135-L135) model listeners (that you probably already do)

**Comment by jrieken** [comment]
I see. Thanks for the explanation, pushing a fix that listens to notebook coming to life and auto-resolving inputs

**Comment by bpasero** [comment]
Thanks. 

When I implemented my text area editor, I actually felt that this kind of code is easy to miss and ideally could be reused, but I wasn't really able to figure out how. There is somewhat of a gap between the nice working copy world where everything is reused and the editor input world where parts are reused (like label rendering) but e.g. working copy handling is entirely not and everyone is writing the same code to listen to changes of the working copy and re-emitting them through the editor input.

Maybe something like a working-copy-aware-editor-input could be added, but then again, there are editors that already extend another editor input, so inheritance would not work for them.

**Comment by bpasero** [comment]
Oh and for notebooks this is even more complicated, because the underlying model is not always a file working copy, but sometimes the old one. If we could get rid of the old one, that would make this a bit easier.

**Comment by connor4312** [comment]
This still seems to happen: 

https://user-images.githubusercontent.com/2230985/124199387-a0507680-da87-11eb-8e51-617f9bc6ffa7.mp4

**Comment by bpasero** [comment]
I cannot reproduce with the built in command to create a new GH Issue Notebook:

![recording](https://user-images.githubusercontent.com/900690/124230021-c66d2980-db0e-11eb-86fd-3054a30b0a37.gif)

What is the code for the hello world command you trigger?

**Comment by bpasero** [comment]
Not even Jos steps in https://github.com/microsoft/vscode/issues/126460#issue-922385305 reproduce for me now, I see the notebook show as dirty after reload.
