### ISSUE TITLE
Hover the mouse over the secondary option, there is no selection bar (blue background color)

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#126465]
VS Code Version: VS Code 1.56.2
OS Version: Linux VM 

Steps to Reproduce:
1. Open a .ts file with VS Code.
2. Right-click a symbol and click Peek->Peek Definition.
3. Observe secondary options.

Actual:
Hover the mouse over the secondary option, there is no selection bar (blue background color)
![image](https://user-images.githubusercontent.com/78774400/122205167-85e89b80-ced2-11eb-82de-2c0e613c0209.png)

Expected:
Hover over the secondary option with the selection bar (blue background color)
![image](https://user-images.githubusercontent.com/78774400/122205212-939e2100-ced2-11eb-9e23-4427a70ae440.png)

**Comment by sbatten** [comment]
the issue is reprod with native menus

**Comment by deepak1556** [comment]
Can you check if the issue persists with latest insiders https://code.visualstudio.com/insiders/

**Comment by v-ericawu** [comment]
@deepak1556 Using the latest version of VSCode also reproduces the issue:
![126465](https://user-images.githubusercontent.com/78774400/122718277-53a6b780-d29f-11eb-9131-3f647fa6f0b0.gif)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/113630
