### ISSUE TITLE
Update is not working

### ISSUE THREAD

**Issue by Kwooda** [microsoft/vscode#126422]
Issue Type: <b>Bug</b>

I am unable to update from version 1.56.2 to version 1.57. It keeps prompting to restart to update, but after restart, it is always still on 1.56.2, and the cycle repeats.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.49GB free)|
|Process Argv|--crash-reporter-id 623933ec-bcc4-41a0-8edf-ed969322b176|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.20
git-extension-pack|don|0.1.3
githistory|don|0.6.16
gitlens|eam|11.4.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
markdown-preview-enhanced|shd|0.5.21
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674

```

</details>

**Comment by joaomoreno** [comment]
Can you completely remove and reinstall VS Code?
