### ISSUE TITLE
Mouseover hidden behind debug controls

### ISSUE THREAD

**Issue by Hex052** [microsoft/vscode#126421]
Does this issue occur when all extensions are disabled?: I don't know how you can get debugging started without an extension.

![image](https://user-images.githubusercontent.com/10149479/122132389-39746180-cde7-11eb-8f8e-e22708f806a1.png)

- VS Code Version: 1.57.0
- OS Version: Windows 10

Steps to Reproduce:

1. Start a debug session
2. Hover over a variable
3. Observe the mouseover is hidden behind the debug controls

**Comment by weinand** [comment]
You can move the debug controls with the mouse out of the way.
