### ISSUE TITLE
Can't open files from the File Explorer with regular click and double click.

### ISSUE THREAD

**Issue by ccokee** [microsoft/vscode#126430]
Does this issue occur when all extensions are disabled?: Yes

The file explorer on the left side isn't working properly. I can't edit files unless I click them with the right button and select "Open with" then the I choose de default text editor. It's like clicking and double clicking were disabled.

- VS Code Version: 1.56.2
- OS Version: Gentoo/Linux

Steps to Reproduce:

1. Open any folder
2. Try to open any file in the explorer

**Comment by varora1406** [comment]
Try updating to latest version @ccokee

**Comment by varora1406** [comment]
Fixed for me when updated to 1.57

**Comment by lramos15** [comment]
This is a bug with some setting changes in 1.56.2 please update to 1.57.
