### ISSUE TITLE
`Save Workspace As...` defaults to remote filesystem

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#126476]
Issue Type: <b>Bug</b>

1. Build and run fsprovider-sample
2. Run the commands to initialize the workspace and create the files.
3. From the File menu pick Save Workspace As...

Previously we would have been given the native file dialog for choosing where to save the new workspace file, whose name defaults to workspace.code-workspace

Now we get the VS Code file dialog. This defaults to listing the folders in the MemFS filesystem.

![image](https://user-images.githubusercontent.com/6726799/122218355-473cec00-cea6-11eb-876f-2b82652b49e0.png)

But saving workspace.code-workspace there only makes sense if I can subsequently browse the MemFS filesystem from the Open Workspace dialog from the File menu of a new VS Code window. That dialog only browses the local filesystem. So I have no way of ever re-opening the workspace I just saved.

Yes, at the Save Workspace stage I can click the "Show Local" button and save workspace.code-workspace locally. But it may not be obvious to users of my FileSystemProvider extension that they must do this.

Perhaps a FileSystemProvider capability should be added which lets the FSP indicate its degree of support for storage of workspaces.

Related: #126278

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alexr00** [comment]
@bpasero are you the owner of the file system provider API? What do you think should happen here?

**Comment by bpasero** [comment]
@alexr00 the API is from @jrieken 

I thought this was maybe a regression but if not then we can turn it around into a feature request.

**Comment by jrieken** [comment]
I fail to understand how this is a question of the file system provider API. Workspace files are just files and those are supported by the API. My understanding is that VS Code cannot read workspace files from contributed file systems and that makes it a limitation of VS Code, not an API thing. So, I believe when saving workspace files we should just be smart and only offer the schemes (file, vscode-remote?) from which we can read workspace files

**Comment by bpasero** [comment]
Yeah I like that 👍

**Comment by bpasero** [comment]
@alexr00 just adding a line here should do it right:

https://github.com/microsoft/vscode/blob/89157c1a87ad67e59f147ef7a169d32b9ddb9d6a/src/vs/workbench/services/workspaces/browser/abstractWorkspaceEditingService.ts#L55-L61

```
availableFileSystems: [Schemas.file, Schemas.vscodeRemote],
```

**Comment by aeschli** [comment]
yes, file and vscode-remote. Remote workspaces are supported.

**Comment by bpasero** [comment]
Probably then also needs adjustment in the call to `defaultUri: await this.fileDialogService.defaultWorkspacePath(undefined, UNTITLED_WORKSPACE_FILENAME)`

**Comment by alexr00** [comment]
👍 I wasn't aware of the limitation of reading workspace files from contributed file systems. I agree then that this isn't related to contributed file systems at all. I will make the changes as Ben suggested.
