### ISSUE TITLE
"show fixes" should behave like suggestion/intellisense with regards to position and mouse

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/vscode#126493]
When using "Show Fixes" a popup window might open under the current mouse position, leading to preselection of the item at the mouse position.

![image](https://user-images.githubusercontent.com/29799350/122249706-5bdeab80-cec9-11eb-80f3-66c434a1a5bb.png)

It would be nice if the show fixes popup behaves like the auto suggestion/intellisense popup, not preselecting an item because of a mouse hover.

**Comment by yume-chan** [comment]
Duplicate of #110594
