### ISSUE TITLE
Opening raw output data in text editor causes VSCode to crash

### ISSUE THREAD

**Issue by rohitsathish** [microsoft/vscode#126466]
Issue Type: <b>Bug</b>

Using Jupyter Notebooks in VSCode Insiders.

When the text output is too large to display, an option appears stating - 'show more (open the raw output data in text editor)'. Selecting this option is causing VSCode to crash.

Already checked:
1. "editor.largeFileOptimizations": true
2. files.maxMemoryForLargeFilesMB = 4096

VS Code version: Code - Insiders 1.58.0-insider (b79d23d3568db6c926c5ac428457c31f4dfc1c00, 2021-06-15T15:27:03.967Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.44GB free)|
|Process Argv|--crash-reporter-id ae5030a7-252e-4fae-a3f4-65ef8037ef50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.1
python-preview|don|0.0.4
prettier-vscode|esb|6.4.0
pythonsnippets|frh|1.0.2
gc-excelviewer|Gra|3.0.42
vscode-test-explorer|hbe|2.20.4
RelativePath|jak|1.4.0
vscode-python-test-adapter|lit|0.6.8
python|ms-|2021.6.920123138-dev
vscode-pylance|ms-|2021.6.2-pre.1
jupyter|ms-|2021.7.942275039
test-adapter-converter|ms-|0.0.10
reload|nat|0.0.6
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.6
vscode-icons|vsc|11.5.0
vscode-import-cost|wix|2.15.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by rebornix** [comment]
@rohitsathish do you mind sharing the notebook you are using to help troubleshoot?

**Comment by rohitsathish** [comment]
@rebornix Sure, sharing a minimal example with requests.

```
import requests as req
text = req.get('https://www.techradar.com/in').text
print(text)
```
