### ISSUE TITLE
integrated terminal can not handle uppercase keys, such as alt+shift+h

### ISSUE THREAD

**Issue by aeiouaoeiuv** [microsoft/vscode#126442]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Ubuntu 20.04 (5.4.0-42-generic)
- Bash Version: 5.0.17(1)-release
- Zsh Version: 5.8

Steps to Reproduce:

1. Open ubuntu terminal and start vscode: `code --disable-extensions`.
2. Open vscode terminal with `bash` or `zsh`.
3. Input `cat` command and enter.
4. Press `alt+shift+h` keys, and it shows up `^[h`.

What I expected to see is `^[H` with `alt+shift+h` pressed.
And ubuntu terminal shows the correct keys codes.

This is `ubuntu terminal` reproduce picture:
![ubuntu_terminal](https://user-images.githubusercontent.com/18081173/122165312-9d139300-ceaa-11eb-8b39-86483ff05a41.png)

This is `vscode terminal` reproduce picture:
![vscode_terminal](https://user-images.githubusercontent.com/18081173/122165318-a270dd80-ceaa-11eb-867d-6613cfe8fd61.png)

**Comment by Tyriar** [comment]
Moved upstream: https://github.com/xtermjs/xterm.js/issues/3382
