### ISSUE TITLE
Not possible to have SyncActionDescriptor with an Action constructor with more arguments

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12642]
All our global actions contributed from the workbench need to have exactly 2 arguments: ID and label. This makes it hard to contribute parameterized actions that take a context as argument (imagine you have 1 base class of action to toggle viewlets and you want to pass in the viewlet ID).

Tracing down the code it ends up in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L176 where we have `IConstructorSignature2<string, string, Action>`

I am not really sure who added this code to begin with but cc'ing some folks ( @joaomoreno @alexandrudima @jrieken ).

My proposal would be that you can pass in the `SyncDescriptor<Action>` into the `ctor` so that you can create any kind of descriptor before hand:

```typescript
export class SyncActionDescriptor {...
   constructor(descriptor: SyncDescriptor0<Action>, id: string, label: string, keybindings?: IKeybindings, keybindingContext?: ContextKeyExpr, keybindingWeight?: number);
   constructor(ctor: IConstructorSignature2<string, string, Action>, id: string, label: string, keybindings?: IKeybindings, keybindingContext?: ContextKeyExpr, keybindingWeight?: number);
   constructor(arg1: any, id: string, label: string, keybindings?: IKeybindings, keybindingContext?: ContextKeyExpr, keybindingWeight?: number) {
	this._id = id;
	this._label = label;
	this._keybindings = keybindings;
	this._keybindingContext = keybindingContext;
	this._keybindingWeight = keybindingWeight;
	this._descriptor = arg1 instanceof SyncDescriptor ? <any>arg1 : createSyncDescriptor(arg1, this._id, this._label);
}
```

Challenging part is that both `SyncDescriptor0` and `IConstructorSignature2` are interfaces so I cannot really do an instanceof check.

Ideas?

**Comment by jrieken** [comment]
I think the debt is deeper - we should stop using actions but migrate to commands - as @alexandrudima did for the editor. That fact all actions needs to be constructed with id and label tell the problem - we want to decouple the representation (label) from the actual functionality and action are the opposite of that as they combine both.

**Comment by joaomoreno** [comment]
OMG pls yes

**Comment by bpasero** [comment]
+1 for the real solution.
