### ISSUE TITLE
Close All Tabs [Feature]

### ISSUE THREAD

**Issue by Yasir900aslam** [microsoft/vscode#126454]
- [x] I have read Rules of Conduct  
- [x] I have searched issues for this feature but there is none.

During Development, I often Open around 30 code files, then closing these files are one by one is so much time consuming and if all of the 30 code files have unsaved data, I need to click Save in the Backdrop window, To automate this behavior, 

### Inspiration
1. IOS/Andriod Clear All Notifications Functionality for VScode.

### Feature details (Just my opinions, Implementation is upto Maintaners)
1. User can press CTRL + P to search files in a command window. _(See picture Reference Command Window)_ 
2. Add a new button to the top of the files row , with a button (close all files) then we can ask users in a backdrop window to (Save - Cancel or Don't Save) all files, then all file should be cleared from the window. 

### Picture Reference
_Command Window_
1. ![Screenshot from 2021-06-16 13-14-47](https://user-images.githubusercontent.com/26070254/122183912-21fbae00-cea5-11eb-9407-2693c990cc8e.png)

**Comment by bpasero** [comment]
We have commands for that?

![image](https://user-images.githubusercontent.com/900690/122192268-caa11200-ce93-11eb-9f28-2b77b3bfd1aa.png)

**Comment by Yasir900aslam** [comment]
Thanks for your time, it solves my use case.
