### ISSUE TITLE
Not able to change terminal profile

### ISSUE THREAD

**Issue by mbastidasluis** [microsoft/vscode#126478]
Issue Type: <b>Bug</b>

Terminal profile dropdown tooltip does not show other configured options (git bash). 
Neither can be changet interactively in the command palette. It simple does nothing.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.16299
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.57GB free)|
|Process Argv|--crash-reporter-id 9f043ec4-11de-4987-b94d-95eb00e7afb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
git-graph|mhu|1.30.0
cpptools|ms-|1.4.1
reload|nat|0.0.6
gitblame|wad|7.0.6

</details>

**Comment by meganrogge** [comment]
/duplicate #121722. try setting `terminal.integrated.useWslProfiles: false`
