### ISSUE TITLE
"Restart (R)" shortcut key does not work

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#126461]
VS Code Version: VS Code 1.56.2
OS Version: Linux VM and Linux ARM64

Notes:
Install Simplified Chinese language package

Steps to Reproduce:
1. Open VS Code and press F1 to open command palette.
2. Choose the “Configure Display Language”->zh-cn->restart(Use the shortcut key “R” to restart).

Actual:
Shortcut key does not work

Expected:
Project restart

**Comment by alexdima** [comment]
@v-ericawu When you say `Use the shortcut key “R” to restart`, what do you mean? What keybinding do you press?

**Comment by v-ericawu** [comment]
@alexdima When you switch the VS Code language, you need to click "Restart" to restart the VS Code and change the display language.
Note: The "Restart" shortcut is an uppercase "R".
Screenshots with specific steps are shown below:
![image](https://user-images.githubusercontent.com/78774400/122324905-3353c180-cf5c-11eb-98e8-ceaaf4c6b1da.png)
![126461](https://user-images.githubusercontent.com/78774400/122324927-3d75c000-cf5c-11eb-9635-17cb51e70e53.gif)

**Comment by alexdima** [comment]
I don't think `R` is supposed to activate the `Restart` button in this dialog:
> ![image](https://user-images.githubusercontent.com/5047891/122351105-1d3f0480-cf4e-11eb-9f52-1abe7a694c4e.png)


I think I know what you mean, in the menus on Windows there appears an underscore sometimes under certain characters of the menus, but I don't think that underscore shortcut thing works in dialog boxes in Windows. @bpasero please correct me if I'm wrong.
