### ISSUE TITLE
Docker daemon can't be accessed.

### ISSUE THREAD

**Issue by Bovey0809** [microsoft/vscode#126433]
Issue Type: <b>Bug</b>

remote docker extension filed to show running containers.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (24.78GB free)|
|Process Argv|--crash-reporter-id 4fffc1da-6386-458c-8ff3-4909e7e0af7b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 46|
|OS|Linux x64 4.4.0-142-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 1295)|
|Memory (System)|251.81GB (125.69GB free)|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
grammar-color|Ant|0.0.2
mermaid-markdown-syntax-highlighting|bpr|1.2.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-dash|dee|2.4.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
pythonsnippets|frh|1.0.2
remotehub|Git|0.10.1
better-cpp-syntax|jef|1.15.6
vscode-peacock|joh|3.9.1
vscode-cudacpp|kri|0.1.1
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.7.0
pytorch-snippets|SBS|1.0.2
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
vscode-icons|vsc|11.5.0
material-theme|zhu|3.10.14
markdown-mermaid|bie|1.9.2
cmake-format|che|0.6.11
path-intellisense|chr|2.3.0
doxdocgen|csc|1.3.2
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.22
shell-format|fox|7.1.0
vscode-pull-request-github|Git|0.27.0
cloudcode|goo|1.12.1
vscode-test-explorer|hbe|2.20.4
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
path-autocomplete|ion|1.17.1
vscode-gutter-preview|kis|0.27.1
vscode-emacs-friendly|lfs|0.9.0
marp-vscode|mar|1.0.2
file-downloader|min|1.0.11
mindaro|min|1.0.120210615
vscode-docker|ms-|1.13.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999406279
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
cpptools-extension-pack|ms-|1.0.0
test-adapter-converter|ms-|0.0.10
resourcemonitor|mut|1.0.7
autodocstring|njp|0.5.4
psi-header|psi|1.15.2
vscode-yaml|red|0.12.0
vscode-yaml|red|0.19.2
python-init-generator|See|0.0.10
markdown-preview-enhanced|shd|0.5.3
code-spell-checker|str|1.10.2
vscode-readme-pattern|tho|1.3.0
cmake|twx|0.0.17
vscode-mermaid-preview|vst|1.6.2
markdown-all-in-one|yzh|3.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805cf:30301675

```

</details>

**Comment by chrmarti** [comment]
Could you provide the steps you took to see the problem? (Is this the Docker or the Remote-Containers extension?)
