### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by MeghanshBansal** [microsoft/vscode#126450]
Issue Type: <b>Feature Request</b>

Show opened editors marks in explorer

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
