### ISSUE TITLE
Enable extension based on project type

### ISSUE THREAD

**Issue by sultanmyrza** [microsoft/vscode#126448]
I enjoy using vscode now I use vscode for my (flutter, python+django, JS/TS [react, firebase]) projects

for flutter I was using Android Studio but gradually switched to vscode.

to enable extensions based on projects (dart+flutter or python+django or js+react) I used [profile switcher](https://marketplace.visualstudio.com/items?itemName=aaronpowell.vscode-profile-switcher) (seems inactive recently, last commit 7 month ago)

I like the way profile switcher works 
From user's standpoint I create profile (flutter-env), (django env) 
for each profile I install vscode extension, and settings.json

later I just switch profile and it automagically installs extensions and setup settings.json
So it feels like dedicated ide for my environment

## vscode + profile switcher seems like dedicated ide (example intelij ides)

![Screen Shot 2021-06-16 at 2 52 50 PM](https://user-images.githubusercontent.com/12681781/122171644-c67bf100-cea1-11eb-9b90-b59726e632ec.png)

**Comment by sandy081** [comment]
I do not understand your request here. Can you please let us know if you are requesting a feature from VS Code and if so what is it?
