### ISSUE TITLE
Auto Import not woking anymore for React components

### ISSUE THREAD

**Issue by BraisC** [microsoft/vscode#126467]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57 and Insiders
- OS Version: macOS 11.2.2

Steps to Reproduce:

1. Create two React components
2. Write the name of one of them inside the other
3. Ctrl+Space to open the suggestions
4. Auto Import not showing, the option showing does nothing.

The same project worked perfectly days ago, now it doesnt work in any of my projects, not even with clean install, I even downloaded the Insiders version, same thing.

Current Behaviour: Not showing the option to autoimport on suggestions.
Expected Behaviour: Showing Autoimport

`{
  "compilerOptions": {
    "baseUrl": "src",
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
`

![Captura de pantalla 2021-06-16 a las 12 54 10](https://user-images.githubusercontent.com/12214486/122208367-7f8efb00-cea3-11eb-816b-9437c658ad72.png)

**Comment by mjbvz** [comment]
Please share code (as text) that demonstrates the issue
