### ISSUE TITLE
Unusual line delimiter dialog doesn't tell me which file

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#126456]
Version: 1.58.0-insider
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:18:57.982Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-18-generic

After starting up VS Code I got a modal dialog telling me about an unusual line delimiter.
It didn't tell me about the file this is about.

![image](https://user-images.githubusercontent.com/6461412/122187086-fd94d700-ce8e-11eb-95ca-7173196a091f.png)

After accepting to fix, I saw where the problem was

![image](https://user-images.githubusercontent.com/6461412/122187563-6da35d00-ce8f-11eb-93ab-88d99ac26a19.png)

I find the dialog too heavy, especially on startup. 
I would need to see the code to find out what's the issue here. E.g. in our case, this is in a test, so might be intended

Maybe have a warning triage next to 'LF' in the status bar?

When I click ignore for this file, how can I unignore the file?

**Comment by alexdima** [comment]
@aeschli I agree this is pretty weird. The `Detected unusual line terminators` prompt comes from a code editor contribution which executes **only when a code editor widget is instantiated and shows the problematic file**. I think that this normally works fine, but in this case I believe the problematic file was opened, the dialog was shown, and then the "Release Notes" editor **opened under** the prompt and changed the active editor from under the prompt.

@bpasero I agree with the feedback here, but I'm not sure what to do. Maybe we could make the "Release Notes" editor wait until all confirm dialogs have been closed before showing itself or that the workbench starts directly with that editor after a release?

Regarding converting this to a passive indicator in the status bar: I don't think that would be wise. Having this unusual line terminator will lead to semantic tokens, jump to definition and all kind of language features to become off. Here is the background: https://github.com/microsoft/vscode/issues/96142

**Comment by bpasero** [comment]
Maybe instead of a modal dialog this could be shown somewhere in the editor area?

Almost like the trust banner but instead of showing to the top of the window, showing right above the editor but still inside the editor?

![image](https://user-images.githubusercontent.com/900690/122230020-8c1e4e00-ceb9-11eb-9b65-8971582232e0.png)

As for release notes, I think we are investigating to move away from using an editor and using something else but I cannot find the issue now. 

Arguably this can happen in other cases too I guess, e.g. when I open a file which loads slow and I manage to open another editor over it?

**Comment by bpasero** [comment]
Well, easiest fix is to add the file name into the dialog, I would argue then it doesn't really matter which editor is active.

**Comment by bpasero** [comment]
PR is up to change the dialog just a bit (https://github.com/microsoft/vscode/pull/126650):

![image](https://user-images.githubusercontent.com/900690/122518637-bedb5a00-d011-11eb-8297-38e67b984603.png)
