### ISSUE TITLE
terminal new version

### ISSUE THREAD

**Issue by bigcven** [microsoft/vscode#126437]
Issue Type: <b>Feature Request</b>

how to back to old version of terminal, this new is very very inconvenience

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by yume-chan** [comment]
`"terminal.integrated.tabs.enabled": false`
