### ISSUE TITLE
跳转到引用

### ISSUE THREAD

**Issue by darKing2018** [microsoft/vscode#126435]
当引用当前变量的文件关闭时，无法跳转到变量的引用

**Comment by TheColdPot** [comment]
> 当引用当前变量的文件关闭时，无法跳转到变量的引用

此句的英文翻译是 / The English translations for this sentence is:

Cannot jump to a reference to a variable, when the file that references the current variable is closed.

> _Actually, I don't understand how to broke this sentence_

**Comment by TheColdPot** [comment]
> 当引用当前变量的文件关闭时，无法跳转到变量的引用

*This is a LOCALZATIONED MESSAGE for issue opener*



> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

工作人员不了解到底发生了什么，请用一个屏幕录制（最好是GIF）让他们知道，你可能需要基于web的gif录制器：<https://gifcap.dev>

**Comment by bpasero** [comment]
Waiting for input.
