### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by plaanupam** [Microsoft/vscode#12646]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Configure launch.json for debugger and start it.

Issue:
I've been using the VSCode debugger for past few months and since last 2 weeks, it stopped working. It shows debugger listening at port but does not give any output or event start the application. I can start it using node command in terminal and VSCode easily attaches to that process for debugging, but not able to debug directly running application from VSCode.

Below is my launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
                        "cwd": "${workspaceRoot}",
			"program": "${workspaceRoot}/adminapp.js",
			"stopOnEntry": false,
			"args": [],
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"console": "internalConsole",
			"sourceMaps": false,
			"outDir": null
		},
    {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "processId": "${command.PickProcess}",
      "port": 5858,
      "sourceMaps": false,
      "outDir": null
    }	]
}
```

**Comment by isidorn** [comment]
Is it possible that you share your project or a small reproducable setup on GitHub so we can further look into this issue?
When you say output or event start the application what exactly are you expecting to happen that is not happening? More output in the debug console?

**Comment by plaanupam** [comment]
For any project, like even a file with a simple console.log() was not running. It was just showing debugger listening to port. This happened for around 2 weeks but I tried debugger again and it is working. If anything of that sorts happen again, I'll give more information. Thank you. I will close this issue now.
