### ISSUE TITLE
VSCode 1.57 hangs on linux with a message "Select a language to get started. Start typing to dismiss, or don't show this again."

### ISSUE THREAD

**Issue by SrikrishnanS** [microsoft/vscode#126489]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57
- OS Version: Linux 4.1.12-124.46.4.1.el7uek.x86_64 #2 SMP x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Downloaded Visual Studio Code 1.57 tar file (.tar.gz 64 bit) from https://code.visualstudio.com/download
2. Extracted the tar: tar -xf 
3. Used  bin/code binary

**Comment by SrikrishnanS** [comment]
Here's a screenshot
![snapshot1](https://user-images.githubusercontent.com/8472187/122275740-e78c1400-ce98-11eb-92cb-2ddceade0671.png)

**Comment by bpasero** [comment]
@SrikrishnanS you cannot click into the editor and start typing or use anything from the application?

**Comment by ladouxs** [comment]
Hi,
I encountered the same issue on Linux CentOS 7.4 64 bits.
![2021-06-17 12_19_31-Window](https://user-images.githubusercontent.com/34418936/122378663-6f8c1f80-cf66-11eb-823f-e00c33cb9e24.png)

Virtual machine VMWare
[team@localhost Documents]$ uname -r
3.10.0-693.el7.x86_64

I think this issue is easy to reproduce on a CentOS 7 VM.
In the past I had no problem installing VS Code on various Linux systems.
Best Regards.

**Comment by bpasero** [comment]
The linux issue can be solved by running `code --no-sandbox`

**Comment by ladouxs** [comment]
Running "code" with --no-sandbox argument did not solved the problem, but as mentioned before, previous versions tagged "el7" are working correctly (i.e. keyboard responsive) on CentOS 7.

**Comment by SrikrishnanS** [comment]
> @SrikrishnanS you cannot click into the editor and start typing or use anything from the application?

Yes, I can't click or work with vscode.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by SrikrishnanS** [comment]
`--no-sandbox` didn't work:
`Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
`
`--disable-gpu` didn't work either, had no effect - window still frozen.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by SrikrishnanS** [comment]
Past the earlier screen, but freezes with a different home screen now

![snapshot1](https://user-images.githubusercontent.com/8472187/122437743-d998ca80-cf4e-11eb-90e3-b2ce17c149ef.png)

**Comment by bpasero** [comment]
Anything special about your setup? What Linux distro is this?

**Comment by ladouxs** [comment]
Hi @bpasero,

I installed your nightly insider builds as mentioned.
Running `code-insiders --no-sandbox --verbose` gave me the stack trace in attachment.
[code_stack.txt](https://github.com/microsoft/vscode/files/6677185/code_stack.txt)

**Comment by bpasero** [comment]
Thanks, this seems like the culprit:

```
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1185:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:698)
```

I let Deepak continue the investigation, I think there maybe duplicates.

**Comment by SrikrishnanS** [comment]
@bpasero @deepak1556 
OS:  Linux 4.1.12-124.46.4.1.el7uek.x86_64 x86_64
System:  Red Hat Enterprise Linux Server release 7.4 (Maipo)
KDE:  4.14.8

**Comment by deepak1556** [comment]
Merging this to #115784

This is a known issue that versions higher that 1.52 don't work on RHEL 7 systems, there is workaround to install newer gcc toolchain mentioned in the linked issue until we work on a fix.

**Comment by SrikrishnanS** [comment]
When will a fix be available?
