### ISSUE TITLE
Test: Extension installation dependencies

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#12649]
Test for #11937 

- [ ] Any OS

Complexity - 4

### Set up
- Make sure you can publish an extension. Ref - http://code.visualstudio.com/docs/tools/vscecli
- Use the [sample test extensions](https://github.com/Microsoft/vscode-extension-samples/tree/master/extension-deps-sample)
- This repo has 3 extension packs (1, 2, 3) which are already published
- Each has some dependencies - Look at it's package.json for dependencies
- Use these extensions for testing following scenarios (You can also come up with your own if you want to  :) )
- Also do play around with changing dependencies and bumping the versions to test different scenarios for installing and updating.

**Note:** Publishing the extension takes a while to get reflected in the market place.

### Extensions with dependencies
- Search for one of the above extensions and install
- A prompt appears asking for confirmation to install its dependencies also
- `Yes` action - Installs the extension and all its dependencies and sub dependencies (transitive closure).
- `No` action - Install the extension alone.
- `Cancel` action - Cancels the installation.

### Installing with dependencies
- It's status shows `installing` and is finished only after itself and all dependencies are installed
- If any of the dependencies is visible in the Extensions view, then it's status also shows `installing` and is finished only after all are installed
- If the installation fails in between, installed extensions are rolled back / uninstalled.

### Updating an extension with dependencies
- If it was installed with dependencies, then update should also install any new added dependencies 
- Otherwise, update should update only update itself
- Make sure that prompt was not shown during update
- `Update All` and `Auto update` should have the same behavior

**Comment by chrmarti** [comment]
@sandy081 Did you close this by accident?

**Comment by sandy081** [comment]
@chrmarti Nopes, This is TPI for #12647. I saw you created a new TPI for the same and hence I closed this.
