### ISSUE TITLE
Terminal stoped working since 1.57 update

### ISSUE THREAD

**Issue by edolly2** [microsoft/vscode#126424]
Issue Type: <b>Bug</b>

whenever i try and open the terminal is vs code i get this message "The terminal process failed to launch: Path to shell executable "bash" is not a file of a symlink." the only way i have been able to get around this is to degrade my vscode version to 1.56 or use VScodium

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.12.0-10.2-liquorix-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|13.64GB (7.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id cea120e3-98d7-4e26-9628-730cd22d9804|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
vscode-javascript-snippet-pack|aka|0.1.6
svelte-intellisense|ard|0.7.1
vscode-database|baj|2.2.3
better-phpunit|cal|1.5.3
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.11.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
file-icons|fil|1.0.29
vscode-svelte-snippets|fiv|0.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
terminal|for|0.0.10
vscode-mysql|for|0.4.0
live-sass|gle|5.0.3
jsx-beautify|gog|0.0.5
beautify|Hoo|1.5.0
jquery-snippets|Hri|1.0.0
rest-client|hum|0.24.5
icon-fonts|idl|2.5.2
backbone-js-snippets|ioa|0.0.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
vscode-styled-components|jpo|1.6.4
vscode-colorize|kam|0.11.1
vscode-phpfmt|kok|1.0.30
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.31
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-scss|mrm|0.10.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.999406279
js-debug-nightly|ms-|2021.6.1117
vscode-react-native|msj|1.5.1
sqltools|mtx|0.23.0
indent-rainbow|ode|7.5.0
vscode-html-scss|P-d|0.0.42
vscode-css-peek|pra|4.2.0
ruby|reb|0.28.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
vscode-scss-formatter|sib|2.2.1
mdx|sil|0.1.0
js-jsx-snippets|sky|10.1.0
svelte-vscode|sve|105.1.0
sass-indented|syl|1.8.16
vscode-babel-repl|t-s|0.1.2
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
pdf|tom|1.1.0
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.14
quokka-vscode|Wal|1.0.379
vscode-ruby|win|0.28.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
vscode-preview-server|yui|1.3.0
material-theme|zhu|3.10.14
html-css-class-completion|Zig|1.20.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674
binariesv615cf:30321889

```

</details>

**Comment by MarianAlexandruAlecu** [comment]
On the latest version of VS Code I cannot open the external terminal anymore (`cmd + shift + c` or command):
```
[error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at It.spawnTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:31:151)
    at It.openTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:30:79128)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7775)
```
<img width="1085" alt="Screenshot 2021-06-16 at 10 48 53" src="https://user-images.githubusercontent.com/5826632/122179832-8b24f680-ce90-11eb-8962-0ec884f6e6b5.png">

**Comment by Tyriar** [comment]
Can you do a trace log to see how the terminal is launched? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

Also run `ls -la $(which bash)` to see what bash is.
