### ISSUE TITLE
Creating a terminal editor in a new group detaches the other terminal editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126469]
Repro:

1. Toggle terminal
2. Run move from terminal view to editor
3. Move the terminal editor to the right side
4. Run create terminal editor command

<img width="1123" alt="Screen Shot 2021-06-16 at 4 35 40 AM" src="https://user-images.githubusercontent.com/2193314/122212157-60b94600-ce5c-11eb-8001-4617667b3bf5.png">

**Comment by meganrogge** [comment]
One more step needed to repro this - after step 3, focus the left editor.

**Comment by meganrogge** [comment]
This works for me now off of main

**Comment by rzhao271** [comment]
Original issue still occurring in today's Insiders.

![Screencap showing original issue still repros](https://user-images.githubusercontent.com/7199958/124162844-c9efaa80-da53-11eb-9924-df80c2195800.gif)

**Comment by meganrogge** [comment]
investigating

**Comment by meganrogge** [comment]
Interesting to note - if you then drag the terminal editor that looks blank into a new group, the terminal appears

**Comment by meganrogge** [comment]
Removing this line resolves this issue. might cause other problems though https://github.com/microsoft/vscode/blob/da144f6280c47e908fd9f57099a6de1f5380fc39/src/vs/workbench/contrib/terminal/browser/terminalEditor.ts#L89-L91

**Comment by meganrogge** [comment]
That fix breaks reconnect occasionally

**Comment by meganrogge** [comment]
It is clear that we need a conditional within `setInput` to decide when it's appropriate to `detachFromElement`.

Some things I tried:
- `detachFromElement ``onBeforeShutdown` 
- check if the `activeEditor `is a terminal editor and if not, do not `detachFromElement ` - this fixes the bug, but then that editor does not get re-attached on reload
- a combo of the above

for now, the following fixes the bug and does not impact the persistence of the editors:

setting `group` within `openEditor` to `SIDE_GROUP`

**Comment by sbatten** [comment]
@meganrogge I've shared with you offline what I think the right fix is here (removing the pointer to the terminalEditorinput in the old re-used editor pane). As a test, I've verified that even with the SIDE_GROUP fix, you can repro this bug.

Repro Steps:
1. Open 2 side by side untitled editors
2. Create terminal in panel
3. Move terminal to editor (will be in the right group)
4. Move terminal editor to left group
5. Ensure focus is in left group
6. Create terminal editor (will open in right group and left editor will be blank)
