### ISSUE TITLE
Test: Install a set of extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12647]
Test for #11937 

- [ ] Windows @mjbvz
- [x] macOS @roblourens 
- [x] Linux @Tyriar

Complexity - 4

### Set up
- Make sure you can publish an extension. Ref - http://code.visualstudio.com/docs/tools/vscecli
- Use the [sample test extensions](https://github.com/Microsoft/vscode-extension-samples/tree/master/extension-deps-sample)
- This repo has 3 extension packs (1, 2, 3) which are already published
- Each has some dependencies - Look at it's package.json for dependencies
- Use these extensions for testing following scenarios (You can also come up with your own if you want to  :) )
- Also do play around with changing dependencies and bumping the versions to test different scenarios for installing and updating.

**Note:** Publishing the extension takes a while to get reflected in the market place.

### Extensions with dependencies
- Search for one of the above extensions and install
- A prompt appears asking for confirmation to install its dependencies also
- If the dependencies are already installed, then no prompt is shown
- `Yes` action - Installs the extension and all its dependencies and sub dependencies (transitive closure).
- `No` action - Install the extension alone.
- `Cancel` action - Cancels the installation.

### Installing with dependencies
- It's status shows `installing` and is finished only after itself and all dependencies are installed
- If any of the dependencies is visible in the Extensions view, then it's status also shows `installing` and is finished only after all are installed
- If the installation fails in between, installed extensions are rolled back / uninstalled.

### Updating an extension with dependencies
- If it was installed with dependencies, then update should also install any newly added dependencies 
- Otherwise, update should only update itself
- Make sure the `install with dependencies` prompt is not shown during update
- `Update All` and `Auto update` should have the same behavior

### Others
- Uninstalling an extension (with dependencies) is atomic - uninstalls only itself.
- Behavior of Install / update / uninstall an extension with out dependencies is not changed

**Comment by joaomoreno** [comment]
@chrmarti @sandy081 This issue is **big**, it definitely need more than one tester and needs testing across platforms... I added two more checkboxes and split them according to OS.

**Comment by jrieken** [comment]
@chrmarti I was unable to test this today. It would be good if redmond can jump in

**Comment by chrmarti** [comment]
@jrieken Will do, thanks.

**Comment by mjbvz** [comment]
I see this error when trying to install the published test-extension-pack-2 on Windows and selecting "Yes":

![image](https://cloud.githubusercontent.com/assets/12821956/18925395/b472d4a6-8568-11e6-89df-d3efba09b19a.png)

When I hit this error, I'd already mucked around with these extensions quite a bit by installing them and uninstalling them, and doing the same for the individual extensions in the packs, so I'm not sure exactly what caused this. I'm also having trouble getting a repo.

Anyone else hitting an issue like this? I'll see if I can get consistent repo steps.

**Comment by Tyriar** [comment]
@mjbvz I'd guess it's probably a problem with that particular extension.

**Comment by roblourens** [comment]
Does that file exist?

**Comment by Tyriar** [comment]
@mjbvz actually I'd file a bug, .vscode/Icon is probably part of the extension install code to cache the icon.
