### ISSUE TITLE
Rounded Corners On Windows 10 Please Add

### ISSUE THREAD

**Issue by Adatta1276** [microsoft/vscode#126439]
**_The app's cool, but can you please add rounded corners for it on Windows 10 ?_**

**Comment by TheColdPot** [comment]
VSCode are based on electron, which means, you can add a CSS file to customize it.

**And also, rounded corners are not very fits the software like code editor**

_While rounded Corners provides a sense of friendship, Square Corners provides a sense of technology. Therefore, Square Corners rather than rounded Corners is generally used in professional computer software_

> Not from Microsoft.
> No promise.

**Comment by Adatta1276** [comment]
__> VSCode are based on electron, which means, you can add a CSS file to customize it.
> 
> **And also, rounded corners are not very fits the software like code editor**
> 
> _While rounded Corners provides a sense of friendship, Square Corners provides a sense of technology. Therefore, Square Corners rather than rounded Corners is generally used in professional computer software_
> 
> > Not from Microsoft.
> > No promise.

Didn't quite get you @TheColdPot . How exactly do I customize VSCode using CSS ? 

_*I'm not very experienced with VSCode_

**Comment by TheColdPot** [comment]
> __> VSCode are based on electron, which means, you can add a CSS file to customize it.
> 
> > **And also, rounded corners are not very fits the software like code editor**
> > _While rounded Corners provides a sense of friendship, Square Corners provides a sense of technology. Therefore, Square Corners rather than rounded Corners is generally used in professional computer software_
> > > Not from Microsoft.
> > > No promise.
> 
> Didn't quite get you @TheColdPot . How exactly do I customize VSCode using CSS ?

well, I don't know this part too much. But you can go to the official site of VSCode, and go to *documentation*, then you can maybe found some content that can help you

**Comment by Adatta1276** [comment]
@TheColdPot I know JS

**Comment by misolori** [comment]
The OS handles rounded corners for each application and currently is only enabled on macOS. Rounded corners should be supported in Windows 11 since the OS will introduce this but because this is handled by Electron, I'll be closing this issue as out of scope. Thanks.

**Comment by Adatta1276** [comment]
_**Thanks**_

**Comment by Genius398** [comment]
ummmmmm... you are here also?

> _**Thanks**_

**Comment by Adatta1276** [comment]
@Genius398 yes 🤣 how did you find me

**Comment by Genius398** [comment]
> @Genius398 yes 🤣 how did you find me

I just checked your contributions on your profile. it showed this there
