### ISSUE TITLE
command 'geeebe.duplicateText' not found

### ISSUE THREAD

**Issue by Alberto-Beguerie-RT** [microsoft/vscode#126404]
Issue Type: <b>Bug</b>

Hey guys, 

When I press Control + Shift + D on a line of code, I expect VSCode to duplicate that line below the current one. Instead, I'm getting a warning message box in the lower right hand corner of the screen that reads: "command 'geeebe.duplicateText' not found". I noticed this moments ago; I believe yesterday it was working as expected.

Thank you in advance!

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.15GB free)|
|Process Argv|--crash-reporter-id 7317fd7d-d3e0-43c1-beee-1bd5b22cc608|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
vscode-test-explorer|hbe|2.20.4
jupyter|ms-|2021.6.999230701
test-adapter-converter|ms-|0.0.10

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by mjbvz** [comment]
This is either caused by an extension or by a custom keybinding that you have setup. Try double checking the keybindings first
