### ISSUE TITLE
vscode-resource://file urls don't work in Markdown preview anymore

### ISSUE THREAD

**Issue by svsool** [microsoft/vscode#126402]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Install [memo](https://marketplace.visualstudio.com/items?itemName=svsool.markdown-memo)
2. Open [help](https://github.com/svsool/vscode-memo/tree/master/help) folder as workspace
3. Open Embed files.md
4. Run "Markdown: Open preview" from command palette

Urls like `vscode-resource://file///<path_to_workspace>/<image_name>.png` used as part of `<img src="<url>" ... />` used to be rendered fine in preview but not anymore with the last update.

Related code: https://github.com/svsool/vscode-memo/blob/ab6ddbe9b43a4e0e32a2e9edda3d5ccb518744fc/src/features/extendMarkdownIt.ts#L39-L47.

Preview fails with:

![image](https://user-images.githubusercontent.com/1452141/122100535-f84a7480-ce1b-11eb-8265-d98acaf0a4d8.png)

Any workaround?

Related issue: https://github.com/svsool/vscode-memo/issues/401

**Comment by mjbvz** [comment]
`vscode-resource` is an implementation detail so there were no guarantee that hardcoded `vscode-resource` urls will work in the markdown preview. I'm not sure why you doing this originally but you'll need to come up with a different approach

**Comment by svsool** [comment]
Which approach wouldn't be an implementation detail in vscode context? 

I just wonder what are other options to render an image in markdown preview without using relative paths.

**Comment by mjbvz** [comment]
Try looking at the `<base>` url in the preview (or using an absolute path: `/path/to/img`)

**Comment by svsool** [comment]
Thanks! I managed to get it working by providing `data-src` attribute along with `src` attribute for image, otherwise it wasn't working. 👍
