### ISSUE TITLE
Improve notebook rendering jitter

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#126432]
Things to look into

- Can the viewmodel on the webview side be smarter and anticipate layout changes?
- How long do layouts on both sides take?
- Are sending messages slow?

**Comment by roblourens** [comment]
I have a stash with a bunch of changes that shift some things around but do not really make the user perception better. Let's talk about this @rebornix and you can help me figure out whether any of this can go anywhere.

**Comment by rebornix** [comment]
@roblourens yup, let's meet some time to discuss them. Maybe with little bit tweaks Yu our changes can improve the layout by a lot.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/d99e352bb628b144f24576a741c228c2b2c91a76 .

**Comment by rzhao271** [comment]
What are some steps to verify this issue?

**Comment by alexr00** [comment]
If setting stable and insiders side-by-side and scrolling through the ".vscode\notebooks\my-endgame.github-issues" file in each and deciding that insiders looks better counts as verifying then I've verified it 😁
