### ISSUE TITLE
new service worker registration on each webview instance

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#126444]
VS Code registers a new service workser for each webivew instance. Won't it be enough to register a single service worker and pass only minimal information as part of search to it, i.e. `vscode-resource-base-authority`?

Just to clariy: in our case we don't deploy each instance on own origin, but all webviews on a single dedicated origin to separate from top-level window origin. It is not most secure, but we are constrained for now.

cc @mjbvz

**Comment by mjbvz** [comment]
Yes this is intentional. We host every webview in a unique origin for security reasons
