### ISSUE TITLE
Typescript ? property doesn't work

### ISSUE THREAD

**Issue by hansyulian** [microsoft/vscode#126440]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.0
- OS Version: Windows 10

Steps to Reproduce:

1. I dont know how to reproduce, just every single property that uses ```?``` just doesn't counted as ``` T | undefined```

![image](https://user-images.githubusercontent.com/10959546/122160607-6df52580-ce9a-11eb-8276-bb44157794f7.png)

**Comment by yume-chan** [comment]
See microsoft/TypeScript#44421
