### ISSUE TITLE
Remove createConcatTextDocument-proposal

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#126485]
We have a proposal for a notebook concat document. We had some initial excitement for this but didn't find a true use-case. Remove its removal is planned.

**Comment by jakebailey** [comment]
I can't comment on the thread saying to speak up if you use this, but AFAIK this is still used to make Python's LS notebook integration work.

https://github.com/microsoft/vscode-python/search?q=createConcatTextDocument

**Comment by jrieken** [comment]
Thanks for that.
