### ISSUE TITLE
TerminalPanel focus() does not get called when terminal panel first shown

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12648]
1. Click on a terminal icon in the sidebar
2. Notice how the focus is not passed to the terminal (it is passed to all other panels properly)

This is due to the fact thet TerminalPanel.focus() does not get called. Not sure if the terminal panel gets constructed for a long time or is there some other timing issue which might be the root cause.

ping @Tyriar

**Comment by Tyriar** [comment]
No focus using ctrl+j keybinding to toggle either

**Comment by Tyriar** [comment]
This is a regression probably after the big refactor.
