### ISSUE TITLE
Terminal tab names should not allow newlines

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#126521]
1. Add the following profile:
```json
 "terminal.integrated.profiles.windows": {
        "test\nhere\nyeah": {
            "path": "cmd.exe",
            "overrideName": true,
            "args": []
        }
    },
```
2. Add a new terminal tab with that profile.
3. 🐛 The split and remove actions do not show up.

Potential code pointer:
In the schema, `pattern` and `patternErrorMessage` can be used.

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/122769601-88901b80-d259-11eb-8ab0-5bc31d382e43.png)

![image](https://user-images.githubusercontent.com/2193314/122769565-81690d80-d259-11eb-952b-c29d73ad1b43.png)
