### ISSUE TITLE
Custom hover sometimes causes the hovered element to blink

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#126547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 7

Steps to Reproduce:

1. Ensure that Use Custom Hover is enabled.
2. Set focus to the Explorer panel.
3. Move the mouse to near the right edge of an activity bar item (where the tooltip arrow will be placed to).
4. The underneath item will blink between hovered and un-hovered states.

https://user-images.githubusercontent.com/8168391/122320887-91c97180-cf55-11eb-9544-7896e01e6a8b.mp4

Related: #125495

**Comment by Tyriar** [comment]
Fixed by https://github.com/microsoft/vscode/issues/125495
