### ISSUE TITLE
Git push not pushing code into repo

### ISSUE THREAD

**Issue by Elliot-codling** [microsoft/vscode#126539]
I'm new to GitHub and how it works. But I cannot seem to get this working, at least on Windows.
I'm doing the GitHub repository "Contribution #2".
In VScode, in windows, I cannot seem to push the code into the repository as it seems to go into an endless cycle of 'pushing'.
I've tried this on multiple Windows laptops and it does the same thing.

However, with a Raspberry Pi, I did the same thing but it worked just fine in VScode.
Could this issue be resolved for Windows?

**Comment by Just-Rea** [comment]
Currently going through the same issue.

**Comment by lramos15** [comment]
Please update your git and try again. Old versions of git often cause this issue.
