### ISSUE TITLE
Searching from highlighted text clears search box history

### ISSUE THREAD

**Issue by ishanchho** [microsoft/vscode#126520]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.50.1
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Open search panel and type in some words
2. cmd+z undoes modifications made in the search box
3. highlighting some text in a file then cmd+f replaces the search box content with highlighted text
4. cmd+z does nothing

Same thing happens for searching within file and searching globally (replace cmd+f with shift+cmd+f).

**Comment by roblourens** [comment]
The history is still there, you can use the arrow keys to access it. But I think that when we programmatically set the value of the text input (when you press cmd+f and we pull in text from the editor), we wipe out the undo stack :(

**Comment by ishanchho** [comment]
FYI adding this to `keybindings.json` fixes what I was complaining about:
```json
{
    {
        "key": "cmd+z",
        "command": "history.showPrevious",
        "when": "historyNavigationEnabled && historyNavigationWidget"
    },
    {
        "key": "shift+cmd+z",
        "command": "history.showNext",
        "when": "historyNavigationEnabled && historyNavigationWidget"
    }
}
```
