### ISSUE TITLE
[Test API] Cannot multi-select tests that are in Pending status

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#126509]
Issue Type: <b>Bug</b>

Seems to also have issues in other scenarios

Seems to work OK if you select a node with non-pending and then select other nodes. Once you have a pending as the "selected" node then it starts not working again.

Repro in comments.

VS Code version: Code - Insiders 1.58.0-insider (3e0c442a8ee9fdc037d627d70fe291f72af04cfd, 2021-06-16T05:17:51.956Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (3.11GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell-preview|ms-|2021.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by JustinGrote** [comment]
https://user-images.githubusercontent.com/15258962/122265453-9f1b2900-ce8d-11eb-973b-af3b84d87c0a.mp4

**Comment by TylerLeonhardt** [comment]
@JustinGrote can you verify that this is fixed?

**Comment by JustinGrote** [comment]
@TylerLeonhardt @connor4312  LGTM
![image](https://user-images.githubusercontent.com/15258962/124182948-64f47e80-da6c-11eb-9c92-4806305ea6af.png)
