### ISSUE TITLE
Web playground is broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126569]
https://vscode-web-test-playground.azurewebsites.net/?enter=true

```
workbench.web.api.js:2788 Extension 'vscode.vscode-web-playground cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ workbench.web.api.js:2788
workbench.web.api.js:2788 [vscode.vscode-web-playground]: statusBar/windowIndicator is a proposed menu identifier and is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.vscode-web-playground
_logMessageInConsole @ workbench.web.api.js:2788
workbench.web.api.js:2316 Activating extension 'vscode.vscode-web-playground' failed: [vscode.vscode-web-playground]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.vscode-web-playground.
```

//cc @joaomoreno

**Comment by bpasero** [comment]
I am not sure if my changes broke this, that were mainly around improving web smoke tests. Not sure if something changed in the remote indicator?

**Comment by bpasero** [comment]
Maybe then https://github.com/microsoft/vscode-web-playground needs an update?

**Comment by sandy081** [comment]
Yes, we no longer allow external extensions to be builtin and they shall be considered as normal extensions. So we need to enable vscode-web-playground extension to use proposed api.

**Comment by sandy081** [comment]
I can add this extension to our `extensionAllowedProposedApi` list in `product.json`

**Comment by bpasero** [comment]
I removed everything what I think makes the playground use proposed API and I still get this error:

![image](https://user-images.githubusercontent.com/900690/122413038-5abf8400-cf86-11eb-8460-3cec1b3851c7.png)

I think I need to hand this off to you Sandy. 

**Instructions:**
* push changes to https://github.com/microsoft/vscode-web-playground
* make sure to also update the version in `package.json` and update it for `yarn web` [here](https://github.com/microsoft/vscode/blob/9ce9551a8b9f8024b4537334f647cc5d41b6217e/resources/web/code-web.js#L40-L40)
* to test this on the online playground you will have to manually delete the cache folder in `/home/site/wwwroot/.build`

**Comment by sandy081** [comment]
@bpasero Following are still under proposed

```
workspace.registerFileSearchProvider(MemFS.scheme, this),
workspace.registerTextSearchProvider(MemFS.scheme, this)
```

Any insights about these?

**Comment by bpasero** [comment]
Yeah you are right, I removed all traces. I hope its fine now.

**Comment by sandy081** [comment]
Added the extension to `extensionAllowedProposedApi` list
