### ISSUE TITLE
command 'html-css-class-completion.cached' Overlapping CTRL+BREAK

### ISSUE THREAD

**Issue by adamkeinan** [microsoft/vscode#126512]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.0 (system setup)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

I've noticed that on most of my python projects there's an irritating problem when I try to stop the server: CTRL+C simply doesn't work. After researching the problem and trying several solutions, I simply debugged the vscode editor and noticed that the "command 'html-css-class-completion" has a command shortcut that overlaps CTRL+C.

Steps to Reproduce:

1. removing\changing the "command 'html-css-class-completion.cached'" Key Shortcut.
2.  Re-running the Server

**Comment by aeschli** [comment]
The `html-css-class-completion` command comes from an extension: https://github.com/Zignd/HTML-CSS-Class-Completion

Looking at the code there, I don't see any key shortcut assignment, but I don't know the history. Are you sure you didn't inadvertently configure that at some point, e.g. when playing with the shortcuts editor?
