### ISSUE TITLE
VS Code only produces an empty window on Raspberry Pi OS bullseye

### ISSUE THREAD

**Issue by spl237** [microsoft/vscode#126565]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0-1623259096
- OS Version: Raspberry Pi OS bullseye

Steps to Reproduce:

1. Attempt to launch VS Code either from menu or by typing "code" into terminal

One of three things happens. Either no window appears at all, or a blank white window appears which closes a few seconds later, or a white window appears which then turns black and remains on the screen, but is never populated by any contents. Disabling extensions makes no difference. Screenshots attached.
![2021-06-17-090002_1920x1080_scrot](https://user-images.githubusercontent.com/10401149/122357501-bae50480-cf4b-11eb-913b-94e0f7f5d1eb.png)
![2021-06-17-090537_1920x1080_scrot](https://user-images.githubusercontent.com/10401149/122357517-bddff500-cf4b-11eb-84e9-91423f05f52b.png)

**Comment by spl237** [comment]
Further information - this looks like an Electron sandboxing issue. When I run the code app directly from the command line without the shell file wrapper, this is the output:

pi@raspberrypi:/usr/share/code $ ./code resources/app/out/cli.js 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[main 2021-06-17T12:47:26.611Z] update#setState idle
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Server response: 
Server response: 
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[4268:0617/134730.890809:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Server response: 
Server response: 
Trace/breakpoint trap
pi@raspberrypi:/usr/share/code $

**Comment by spl237** [comment]
And I can get the application to run correctly by appending the flag "--disable-seccomp-filter-sandbox" to the "code" command line.

**Comment by spl237** [comment]
https://github.com/electron/electron/issues/22291 looks to be the issue - it seems Electron version 7.1.14 or later is required to fix the problem.

**Comment by spl237** [comment]
It also seems some later versions of Electron are affected - see https://github.com/electron/electron/issues/26760, which is the same problem.

**Comment by bpasero** [comment]
Can you try to run `code --no-sandbox`?

**Comment by deepak1556** [comment]
Reopening as this issue is different from https://github.com/microsoft/vscode/issues/126019

The layer-2 [seccomp-bpf](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md#The-sandbox-1) sandbox is actually failing here

**Comment by deepak1556** [comment]
This is fixed by https://chromium-review.googlesource.com/c/chromium/src/+/2785131 and is available since chromium `91.0.4459.0`

Our insiders https://code.visualstudio.com/insiders are on chromium 91 and next stable release `1.59` will carry this fix as well.
