### ISSUE TITLE
Double clicking a result in a Search Editor opens a new editor when one already exists

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#126594]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57
- OS Version: Win 10

Steps to Reproduce:

1. Open a file.
2. Search for something that has results in that file and open the results in a search editor.
3. Drag the search editor to an editor group below the file that you just searched.
4. Clicking results in the search editor will open a new editor in the same group as the search editor, that is a duplicate of the file editor you already have open.
5. The `Search Editor: Double Click Behaviour` setting can be configured to open the editor in a new group to the side, reusing an existing editor to the side, but any editors already opened in any other editor group are ignored.

It seems to me that that `Search Editor: Double Click Behaviour` to locate the search result in any already open editor would have been the most useful and obvious thing to have implemented in the first place.

**Comment by Neutrino-Sunset** [comment]
So why can't I update my issue anymore to add some screenshots?

**Comment by Neutrino-Sunset** [comment]
![image](https://user-images.githubusercontent.com/18445931/122412856-d406a900-cf7d-11eb-99ad-777fa61bc8b5.png)

![image](https://user-images.githubusercontent.com/18445931/122413047-f993b280-cf7d-11eb-8aca-616c9fb2ae0b.png)

**Comment by Neutrino-Sunset** [comment]
Had to add screenshots to separate comment. Github not letting me add then to original issue for some reason.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What value do you have for `workbench.editor.revealIfOpen` setting? In it's `false` and you have different groups it will be in group with search editor.

**Comment by Neutrino-Sunset** [comment]
`workbench.editor.revealIfOpen` was `false`, although I've never changed it and would have thought `true` would be the more obvious default setting.

Setting it to `true` solves my problem. Thanks!
