### ISSUE TITLE
Some unknown extension freezes VS Code on startup

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#12656]
VS Code: 1.5.3, Win10.

I installed a bunch of extensions, and now VS Code permanently freezes on startup. The title bar menu still works (everything below is frozen). So far, it only repros when I open the folder that contains the code for our C/C++ extension, so I can get to the Extensions menu, but I don't know which extension to uninstall to get rid of the freeze.

Can you make it so that extensions can't cause VS Code to freeze or unload any extensions that cause VS Code to freeze?

Or report which extensions is causing the freeze so I can uninstall it? If I can see output of which extensions are activating that might help.

Before I had this 100% freezing issue, I was getting random freezes from some other extension (or VS Code itself, I can't tell).

**Comment by sean-mcmanus** [comment]
Via manually uninstalling extensions, I discovered that the "Auto import 1.0.1" extension is causing at least 1 of the permanent freezes on startup. It's possible other extensions could cause the same freeze or random freezes. I think these freezing issues are the most severe issues I've had with VS Code.

**Comment by Bill-Stewart** [comment]
You should probably inform the author of that extension - [https://github.com/soates/Auto-Import](https://github.com/soates/Auto-Import)

**Comment by sean-mcmanus** [comment]
It's no longer freezing with that extension, seems to be freezing with another unknown extension now.

**Comment by sean-mcmanus** [comment]
It looks like that extension may be causing a freeze, but not 100% of the time, and there are other extensions that are freezing too when that extension is uninstalled. Due to the random nature of the repros, uninstalling extensions doesn't work too well.

It seems like VS Code itself should prevent these freezing issues from happening somehow.

**Comment by sean-mcmanus** [comment]
How can an extension writer modify their extension to permanently freeze VS Code or avoid that? I tried and wasn't able to do this with our extension or figure out if our extension was the cause. Whether or not that is possible, it seems like VS Code should prevent that. I type 13 characters and VS Code permanently freezes and I can't tell who is to blame. I attached a debugger to the Code.exe that is hogging all the CPU on one core, and it said node.js was on the call stack (how do I get the pdb?), and when debugging our extension it also gave error messages about node.js not responding. Can someone fix node.js or the usage so it doesn't permanently freeze the VS Code UI so much?

**Comment by joaomoreno** [comment]
First, make sure you _**can't**_ reproduce when running with `--disable-extensions`.

Then, are you behind a proxy or firewall?

Finally, can you run a CPU profile?

* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get VS Code frozen
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by egamma** [comment]
From #12661  it looks like @sean-mcmanus  is running with an extension that patches VS Code.

**Comment by bpasero** [comment]
@sean-mcmanus does it reproduce using our insider build?

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sean-mcmanus** [comment]
The freezes don't repro without extensions and were caused by at least 2. On my laptop, I was hitting a freeze that used CPU, but on my desktop the freezes used 0 CPU (seemed like deadlocks in node.dll). I'll try the CPU profiler later and preview builds later, but I suspect I'd need to build code.exe/node.dll or somehow get symbols.

I'm back on a higher priority Visual Studio work, so I'm not  using VS Code till I'm done with that.

**Comment by bpasero** [comment]
@sean-mcmanus you say 2 extensions cause this? can you isolate which one is causing it?

**Comment by sean-mcmanus** [comment]
The AutoImport extension seemed to be one of the freezers, but I couldn't isolate the other extension. The problem is that the freezing is random and can stop reproing after a certain unknown conditions. One hypothesis put forth from the AutoImport thread that matches my observations is that certain parallel file searches are being done that lead to the freeze, but after the file searching is done and has created an output database file, then the bug no longer repros, which makes isolating the offending extension difficult.

**Comment by bpasero** [comment]
You should bring this up with the extension developers to see if they hard about it before.

**Comment by g33kywatchdog** [comment]
i am also experiencing this annoying freeze...at times, my cursor won't even work again and i will have to force shut down my pc...this happens only when i start visual studio code. I notice this freeze after i downloaded two extension.....a python extension and html snipet. i can't recall the actual name

**Comment by joaomoreno** [comment]
@g33kywatchdog Please create a new issue for your problem. 👍 

Closing this one due to lack of inactivity.

**Comment by mehas** [comment]
@sean-mcmanus Same issue here, on 1.9. Freezes on first run. Does not occur after closing and opening a second time.

**Comment by kaicataldo** [comment]
I know this is closed, but in case anyone encounters this, this was the cuplrit for me: https://github.com/zignd/HTML-CSS-Class-Completion/issues/52
