### ISSUE TITLE
IntelliSense: Property windows is not allowed in launch.json

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode#126585]
**Description**
Since the upgrade to VSCode 1.57, IntelliSense complains about my platform specific launch configuration options (see screenshot). VSCode 1.56 did not show this warning.

![grafik](https://user-images.githubusercontent.com/1696102/122393884-a7e72a00-cf75-11eb-8eba-62dad72d4d27.png)

The configuration executes as expected. I found no mentions of any syntax changes in the update notes, so I'm assuming that this is not supposed to show a warning.

**Files**
[launch.zip](https://github.com/microsoft/vscode/files/6670022/launch.zip)

Minimal launch configuration showing the issue:
```
       {
            "name": "Electron launcher",
            "type": "pwa-node",
            "request": "launch",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            }
        }
```

**Versions**
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Does this issue occur when all extensions are disabled?: Yes

**Comment by elahehrashedi** [comment]
I am getting the exact same error on the properties `"windows"` and etc in `launch.json`.
I also get a similar error in `tasks.json`, where I have defined some properties for a custom task in `package.json`. The property was allowed before, but now it is not. 
![image](https://user-images.githubusercontent.com/16143955/123009805-49092280-d372-11eb-92f0-484e877e614a.png)

**Comment by weinand** [comment]
@isidorn if a similar problem shows up in task.json, then this problem might not come from our schema refactoring.
@aeschli have there been recent changes in JSON schema validation?

**Comment by aeschli** [comment]
No recent change... Look out from `additionalProperties: false` in the schema.

**Comment by isidorn** [comment]
Thanks @aeschli 
Due to the change of our debug json schema this seems to be the way to go since we use the `allOf` syntax.
Unfortunately now we will no longer receive warnings for unknown attributes..
