### ISSUE TITLE
Console wrapping during editing

### ISSUE THREAD

**Issue by richtera** [microsoft/vscode#126589]
Issue Type: <b>Bug</b>

In pretty much all recent versions of visual studio, the terminal has problems with line wrapping and editing. Going back in history and editing commands pretty much never works. There is some kind of offset between where the text/cursor is and where it's actually editing. So most of the time it's off by one or two characters and therefore you end up deleting or inserting characters in the wrong place.
For example I just typed
```
$ (cd ..;gh repo clone stripe/stripe-firebase-extensions
> )
unknown command "clonestripe/stripe-firebase-extensions.git" for "gh repo"
```
Note the line feed and the missing space between clone and stripe.
Then trying to go back up and fixing it.
```
$ (cd ..;gh repo clonestripe/stripe-firebase-extensions)
unknown command "clonestripe/stripe-firebase-extensions" for "gh repo"

Usage:  gh repo <command> [flags]
```
This time it indicates the missing space correctly.
So editing history is not working most of the time and even multi line commands are not always working. It's probably just one off, but it's very annoying, is this something that might be an easy fix?

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (27.55GB free)|
|Process Argv|--crash-reporter-id db2c49a0-c178-4fe7-b9ea-930397e91764|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.36GB (15.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.36GB (15.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.36GB (15.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.36GB (15.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|31.36GB (15.69GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
quokkasyntax|aid|1.2.3
project-manager|ale|12.2.0
language-hugo-vscode|bud|1.3.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-edge-devtools|ms-|1.1.9
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
fish-vscode|sky|0.2.1
vscode-nvm|abu|0.0.1
project-manager|ale|12.2.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.23
git-extension-pack|don|0.1.3
githistory|don|0.6.16
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
go|gol|0.25.1
go-nightly|gol|2021.6.1517
gc-excelviewer|Gra|3.0.42
vscode-docker|ms-|1.13.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
cpptools|ms-|1.4.1
prettier-vscode|pre|3.14.1
markdown-preview-enhanced|shd|0.5.21
vsfire|tob|1.4.1
pdf|tom|1.1.0
har-viewer|unc|0.0.1
docker|vsc|1.0.0
yaml|vsc|1.0.0
clang-format|xav|1.9.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30319631
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by Tyriar** [comment]
Does setting `"terminal.integrated.localEchoLatencyThreshold": -1` help?

**Comment by richtera** [comment]
Yes this seems to make a big difference, thank you.

**Comment by richtera** [comment]
No longer occurs as of now
