### ISSUE TITLE
Support "Postfix completion" type in Snippets

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#126549]
There is a code completion method called "Postfix Completion﻿". It lets you add template code around an expression you’ve just typed. A template expands when you type its abbreviation (postfix) after a dot and press the expansion key (`Tab` by default) or when you select the abbreviation in the code completion popup. For example, the `.if` postfix applied to an expression wraps it with an `if` statement.

I'd like to suggest VSCode have this feature built-in and add it to the Code Snippets syntax. This will lower the barrier when user want to write their own Postfix Completion﻿ snippets.

Here is the usage video clip:

![114612163-c5df9800-9c6f-11eb-959c-8fe529018a21](https://user-images.githubusercontent.com/88981/122326066-45366400-cf5e-11eb-9266-5f32550f18f7.gif)

**Comment by jrieken** [comment]
Yes - there is an extension for that: https://marketplace.visualstudio.com/items?itemName=ipatalas.vscode-postfix-ts

**Comment by janosimas** [comment]
I don't see how the extension solves the issue, @jrieken 
There are language specific extensions for this but the base toolbox of vscode lacks it.
If I want to add my own snippets, do I need to write an extension? Even if they are project specific?
