### ISSUE TITLE
iMac cannot save my code, version 1.57

### ISSUE THREAD

**Issue by HuanBaby1314** [microsoft/vscode#126561]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57
- OS Version: macOS Big Sur 11.1 (20C69)

Steps to Reproduce:

1. code code code 
2. command + S 
3. cannot save

**Comment by davidbfrogman** [comment]
Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 mo ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

Downgraded to Version: 1.56.2 (Universal) fixed the issue for me

**Comment by HuanBaby1314** [comment]
![recording (1)](https://user-images.githubusercontent.com/28698252/122918287-89c46400-d391-11eb-9495-69d00eb2605c.gif)
GIF come！just edit one file and save it. The content keeps shining。

**Comment by bpasero** [comment]
So what action do you run for saving? File > Save? Does it work using keyboard?

**Comment by HuanBaby1314** [comment]
> So what action do you run for saving? File > Save? Does it work using keyboard?

yes, keyboard & mouse click both try, no effect. so I use v1.56 now.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
