### ISSUE TITLE
Restricted mode can't be disabled for remote path

### ISSUE THREAD

**Issue by ababak** [microsoft/vscode#126558]
Issue Type: <b>Bug</b>

I am connecting to my Windows machine and my path starts with "D:/". VS Code adds this path as "SSH: ababak /d:/..." and then it is not recognized as trusted.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: Yes
Fetching remote diagnostics for 'SSH: ababak' failed: Canceled
Fetching remote diagnostics for 'SSH: ababak' failed: Canceled
Fetching remote diagnostics for 'SSH: ababak' failed: Canceled
Remote OS version: Windows_NT x64 10.0.18363
Remote OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id 6b07c24f-9000-4ee2-8c83-e060f2be359f|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH: ababak' failed: Canceled

Fetching remote diagnostics for 'SSH: ababak' failed: Canceled

Fetching remote diagnostics for 'SSH: ababak' failed: Canceled

|Item|Value|
|---|---|
|Remote|SSH: ababak|
|OS|Windows_NT x64 10.0.18363|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3702)|
|Memory (System)|63.94GB (54.44GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ababak|
|OS|Windows_NT x64 10.0.18363|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3702)|
|Memory (System)|63.94GB (54.44GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
gitlens|eam|11.5.1
jupyter|ms-|2021.6.999406279
hexeditor|ms-|1.7.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674
vscextlang:30322306

```

</details>

**Comment by ababak** [comment]
P.S. This happened on an unsaved workspace. After saving a workspace, the problem has gone.

**Comment by sbatten** [comment]
@ababak can you clarify the exact repro steps including the start of the connection, when you granted trust, and when you saved the workspace?

**Comment by ababak** [comment]
I tried to reproduce it from scratch and couldn't get the same result. But I still have several windows that show that I am not crazy. I tried to delete the highlighted (active) entry and recreate it by pressing "Trust" for this window and after a third attempt and automatic window reload it eventually became trusted. So it seems to be a rare bug and I can't help to catch it :(

**Comment by sbatten** [comment]
I think this is an artifact of https://github.com/microsoft/vscode/issues/126015, let me know if I'm mistaken
