### ISSUE TITLE
Expose API to provide expandable message in notifications

### ISSUE THREAD

**Issue by nelango** [microsoft/vscode#126526]
Expose API to provide expandable message in notifications (`showInformationMessage` / `showWarningMessage` / `showErrorMessage` ). The API could be something like: `showInformationMessage(summaryMessage: string, fullMessage: string, ...items: string[])`

Currently, if actions are present in these notification messages, the view is automatically expanded. Instead:
- minimize it and display a summary message by default
- make it expandable and display the full message exposed through API when expanded

**Comment by bpasero** [comment]
//cc @jrieken

**Comment by jrieken** [comment]
dupe of https://github.com/microsoft/vscode/issues/125750?

**Comment by bpasero** [comment]
Yeah maybe, if we end up implementing the new `detail` option like that for notifications, an extension could use `message` for the brief variant and add additional content to `details`. Let's move into that issue, @nelango maybe comment there.
