### ISSUE TITLE
Enh req: Need to be able to specify a scope which is not expensive but should be hoverable

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#12651]
- VSCode Version: 1.5.3
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Install PowerShell extension
2. Open folder C:\Users\{username}\.vscode\extensions\ms-vscode.PowerShell-0.7.2\examples
3. Open file DebugTest.ps1
4. Set breakpoint on line 10
5. Press F5 to start debugging
6. Hover over variable $I on line 2, 4 10.  Notice there is no debug hover
7. Notice that upon the breakpoint being hit, the `Auto` pseudo-scope was open by default.

We really like that `Auto` opens by default.  This seems to happen because we mark the `Auto` scope as not expensive.  However, we also mark the `Local` scope as not-expensive.  Because the built-in VSCode debug hover doesn't work with duplicate variables, we lose debug hover.  That's painful.  Note: the variables in `Auto` are by definition duplicates of variables in `Local`.  The problem with `Local` is that PowerShell has a ton of built-in local variables.  With `Auto` we attempt to show the local variables that the user created.

We can fix debug hover by setting `Auto` back to expensive and then debug hover has only `Local` to search through but that causes `Auto` to not be open by default during debugging which is a bummer.  

BTW we can't use supportsEvaluateForHovers because we can't make that impl side-effect free.

I guess we could make `Local` expensive and `Auto` not expensive but then we lose debug hover on any of the built-in variables the user may use in their script.

One idea is that somehow we could inform VSCode that the `Auto` pseudo-scope is just another "view" (a filtered view) of the `Local` scope and therefore the "don't display debug hover for duplicate variables" rule does not apply.  Another idea, is that VSCode could manage an `Auto` filtered variables view and then there would be a "displayInAuto" field on variable to determine if the variable should be displayed in Auto.  Then when applying the duplicate variable rule for debug hover, you wouldn't count the variables in `Auto` as duplicate.

**Comment by isidorn** [comment]
Assigning first to @weinand since this requires protocol additions
I have expressed my opinion in a related issue that we should tackle this via having more ast information. However if that is unreachable then this feature request makes sense imho

**Comment by weinand** [comment]
I suggest that we lift the safety measure that results is the "Because the built-in VSCode debug hover doesn't work with duplicate variables, we lose the debug hover."

Currently if we find a variable more than once, we do not show the hover because we are not sure about the correct scope. But if the the values of all the found variables in different scopes are identical, then there is no need to suppress the hover.

**Comment by isidorn** [comment]
@weinand awesome idea! Let's do exactly that. It should solve the powershell issue and other adapters might profit as well!

**Comment by isidorn** [comment]
@rkeithhill our insiders build is frozen for a couple of more days, but once the next one is out can you please verify how this behaves now for powershell?
Thanks!

**Comment by rkeithhill** [comment]
Will do.

**Comment by rkeithhill** [comment]
Just installed 1.7.0 insiders.  Debug hover is back for the PowerShell extension without me making any changes!  That is good because we also get the Auto variables container open by default during debugging. Thanks.  cc @daviwil

**Comment by weinand** [comment]
@rkeithhill great, thanks for the update!

**Comment by daviwil** [comment]
Awesome news, thanks a lot guys!
