### ISSUE TITLE
Unable to expand/collapse the directory with the Enter key

### ISSUE THREAD

**Issue by refcell** [microsoft/vscode#126555]
Issue Type: <b>Bug</b>

step:
1. set option `"workbench.tree.expandMode": "doubleClick"`.
2. open any floder with vscode, select any directory below the resource manager.
3. press the "Enter" key, but the directory is not exposed/collapsed.

I hope that when the focus is on a directory, pressing the "Enter" key to expand/collapse the directory. This is more in line with intuition.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.23GB free)|
|Process Argv|C:\\Users\\Admin\\Desktop\\环保三期\\EP-WEB3 --crash-reporter-id 6631c424-1def-42af-b361-c4021e379dd1|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805cf:30301675
binariesv615:30321888

```

</details>

**Comment by joaomoreno** [comment]
This is on purpose: changing that mode will make Enter select it only, but leave Space to toggle expansion state. Does that make sense?

**Comment by refcell** [comment]
using ENTER to toggle expansion state after selected, is it better?

**Comment by joaomoreno** [comment]
I wouldn't want to make Enter do different things depending on the node's state. Closing this for now.
