### ISSUE TITLE
Missing tasks for distinct options cwd

### ISSUE THREAD

**Issue by panayot-cankov** [microsoft/vscode#126522]
When I hit "Ctrl + Shift + B" I see only one of my tasks. Further my launch.json can not find all task just the last on in the list. It seems the tasks are somehow unique by type and script and only the last from the tasks.json attached below is visible. If I change the `script` fields to `watch1`, `watch2`, `watch3` all three tasks appear. Now these execute npm scripts in different directories and if I comment out 2 out of 3, the one remaining works fine.

I have the following tasks.json:
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Kendo Extension Watch",
      "type": "npm",
      "script": "watch",
      "problemMatcher": "$tsc-watch",
      "isBackground": true,
      "presentation": {
        "reveal": "always",
        "panel": "dedicated"
      },
      "group": "build",
      "options": {
        "cwd": "${workspaceFolder}/kendo-vscode-extensions/src/extension"
      }
    },
    {
      "label": "Blazor Extension Watch",
      "type": "npm",
      "script": "watch",
      "problemMatcher": "$tsc-watch",
      "isBackground": true,
      "presentation": {
        "reveal": "always",
        "panel": "dedicated"
      },
      "group": "build",
      "options": {
        "cwd": "${workspaceFolder}/blazor-vscode-extensions/src/extension"
      }
    },
    {
      "label": "ASP.NET Core Watch",
      "type": "npm",
      "script": "watch",
      "problemMatcher": "$tsc-watch",
      "isBackground": true,
      "presentation": {
        "reveal": "always",
        "panel": "dedicated"
      },
      "group": "build",
      "options": {
        "cwd": "${workspaceFolder}/aspnet-core-vscode-extensions/src/extension"
      }
    }
  ]
}
```

I would expect `Ctrl + Shift + B` to list all three, and to be able to use them in the launch.json. The temporary workaround is to make unique npm script names in each of the subfolders.

**Comment by alexr00** [comment]
This is intended. An `npm` task is identified by the `script` and `path` properties. The `path` property is the path to the folder containing the `package.json` that the script is in.

Perhaps you could use [inputs](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables)?

```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Kendo Extension Watch",
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "always",
				"panel": "dedicated"
			},
			"group": "build",
			"options": {
				"cwd": "${workspaceFolder}/${input:locaion}/src/extension"
			}
		}
	],
	"inputs": [
		{
			"id": "location",
			"type": "pickString",
			"description": "Select which location to build",
			"options": [
				"kendo-vscode-extensions",
				"blazor-vscode-extensions",
				"aspnet-core-vscode-extensions"
			]
		}
	]
}
```

**Comment by panayot-cankov** [comment]
@alexr00 Thank you,
Adding `path` seems to work and now all my tasks appear in the list. Path's tooltip says it is the path to the folder containing the package.json, but if I don't set the options.cwd as well it seems VSCode still resolves the package.json file located at the root open folder in the IDE.
