### ISSUE TITLE
I don't like the new terminal controls

### ISSUE THREAD

**Issue by neilgilmour** [microsoft/vscode#126590]
Issue Type: <b>Feature Request</b>

I guess this is more of a feature rollback request. I really don't like the new terminal controls. It's harder to split panes, it's harder to tell which of the icons of split panes will delete which pane. Not a fan I'm afraid.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
You can switch to old functionality as described at the end of section
https://code.visualstudio.com/updates/v1_57#_terminal-tabs

Could you please clarify why you think it's hard to split (except first split before you have tabs) and delete?

**Comment by plus-** [comment]
I too found it's easier to close a pane with the old view, just click the pane you want to close and then click the delete icon.

You don't need to think about which item in the vertical list correspond to the tab you want closed

**Comment by Tyriar** [comment]
I just added the split and kill buttons back by default https://github.com/microsoft/vscode/issues/126032, this will be in next months version but in the meantime you can always switch back to the dropdown by setting `terminal.integrated.tabs.enabled` to `false.

<img width="251" alt="Screen Shot 2021-06-17 at 8 26 51 AM" src="https://user-images.githubusercontent.com/2193314/122427205-c59c9b00-cf45-11eb-8193-8f50855e29ba.png">
