### ISSUE TITLE
Support monospace and syntax highlighting in quick fix dropdown

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode#126597]
Originally suggested in https://github.com/microsoft/pylance-release/issues/367 but since vscode does not support this I'm requesting this feature here:

![image](https://user-images.githubusercontent.com/179599/93078914-95a92a00-f68b-11ea-86cc-d6d6e73a1df9.png)

If that dropdown used the editor font (likely a monospace one), and ideally even syntax highlighting, it would be much easier to see what name is being imported from where.

Take an editor line like this for example - it's super clear what you are importing from where:

![image](https://user-images.githubusercontent.com/179599/93079155-f9cbee00-f68b-11ea-9cf9-142844db2728.png)

**Comment by IllusionMH** [comment]
On screenshot it doesn't look like autocomplete, more like Quick fix which is regular menu(same as context menu etc. IIRC).
Doubt it is possible to highlight there.

**Comment by ThiefMaster** [comment]
yes, quick fix is what I meant. and atm it's indeed not possible which is why I opened this feature request :)

**Comment by sbatten** [comment]
I do not believe there is a way to do this through electron API with native menus.
