### ISSUE TITLE
terminal cant use .vimrc config

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode#126574]
mac:11.4
vscode: 1.57.0

on the terminal, `set mouse=""` in `.vimrc`  cant disable the mouse scroll.
```
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.env.osx": {
        "GO111MODULE": "auto"
    },
    "terminal.integrated.macOptionIsMeta": true,
    "terminal.integrated.copyOnSelection": true,
    // "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "terminal.integrated.confirmOnExit": true,
    "terminal.integrated.cursorBlinking": true,
    // "terminal.integrated.cwd": "${relativeFileDirname}",
    "terminal.integrated.inheritEnv": true,
    "terminal.integrated.fontFamily": "menlo",
    "terminal.integrated.rightClickBehavior": "default",
```

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
