### ISSUE TITLE
Are there some restrictions for `provideDocumentHighlights`?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#126575]
Trying to provide document highlights for a `markdown` file. But the function is not always executed.

```md
#one #two #three
```

✅ Triggered `provideDocumentHighlights`:

```md
#|o|n|e| #|t|w|o| #|t|h|r|e|e|
```

🟥 Not triggered `provideDocumentHighlights`:

```md
|#one |#two |#three
```

```ts
languages.registerDocumentHighlightProvider(
	{
		scheme: 'file',
	},
	{
		provideDocumentHighlights(document, position) {
			console.log('✅  triggered', position);
			return [];
		},
	},
);
```

Is there something that I'm missing?

**Comment by usernamehw** [comment]
Probably word separators. Works with changed language configuration:

```ts
languages.setLanguageConfiguration('markdown', {
	wordPattern: /\S+/g,
});
```

Is it documented somewhere?

**Comment by alexdima** [comment]
>Probably word separators

Yes, `provideDocumentHighlights` is [only triggered on words](https://github.com/microsoft/vscode/blob/9d20e9ff569a65bbbe2b4be5e19308b9abb5cfff/src/vs/editor/contrib/wordHighlighter/wordHighlighter.ts#L351-L355).

> Is it documented somewhere?

A PR to improve the documentation would be most welcome.

**Comment by usernamehw** [comment]
> A PR to improve the documentation would be most welcome.

Nah, it's probably common knowledge and used in other providers.
