### ISSUE TITLE
Extremely slow services in the presence of `paths` option

### ISSUE THREAD

**Issue by evmar** [Microsoft/vscode#12655]
- VSCode Version: 1.5.3
- OS Version: Ubuntu Linux

Steps to Reproduce:
1. create a `foo.ts` with contents like:

```js
import * as ts from 'typescript';

ts.SyntaxKind;
```

2. create a `tsconfig.json` with contents like this.  (this is what "tsc --init" produces with additional `baseUrl` and `paths` properties.)

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "baseUrl": ".",
        "paths": {
            "typescript": [
                "/path/to/typescript/source/typescript.d.ts"
            ]
        }
    },
    "exclude": [
        "node_modules"
    ]
}
```

4. hover on the "ts" symbol and notice it takes six seconds to resolve.  if it's fast, ctl-click on it once, then close the tab, and then hover it again.

Note: /path/to/typescript/source/typescript.d.ts in my case is a very deep path into a network filesystem that is decently fast (it caches locally) but slower than an SSD.

The trace (from the `"typescript.tsserver.trace": "verbose"` setting) shows six seconds for the response to come back.

```
[Trace - 9:40:22 AM] Sending request: quickinfo (22). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/.../t/foo.ts",
    "line": 1,
    "offset": 14
}
[Trace - 9:40:28 AM] Response received: quickinfo (22). Request took 5820 ms. Success: true 
Result: {
    "kind": "alias",
    "kindModifiers": "",
    "start": {
        "line": 1,
        "offset": 13
    },
    "end": {
        "line": 1,
        "offset": 15
    },
    "displayString": "import ts",
    "documentation": ""
}
```

I used `strace` to trace the file system accesses of the tsserver subprocess and it seems to be looking at hundreds of paths, maybe even stuck in a loop.  Unfortunately the log contains filenames that work probably doesn't want me to publish on a bug tracker, otherwise I'd publish it here.

But it looks like it's looking for node_modules/ and files like package.json, index.d.ts, typescripts.tsx, and so on, for every possible directory mentioned in that `paths` variable, despite us telling it where exactly to look.

Specifying a filename in 'paths' seems consistent with the module documentation written here:

http://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by waderyan** [comment]
@evmar thank you for opening this issue. This is very interesting. I cannot reproduce this behavior on my machine however there seems to be a perf issue we can address here. 

Can you provide additional specs on your machine?

**Comment by waderyan** [comment]
@mhegazy this is interesting. Can you take a look at this and advise on next steps testing?

**Comment by mhegazy** [comment]
I do not think there is any thing special about `path`. so if i were to guess, there is something else going on here. additional context would be appreciated.

**Comment by evmar** [comment]
I recreated my repro from scratch, and found that the ".d.ts" suffix on my import doesn't actually work with TS 2.0.5.  So I think I was using a funky version of TypeScript?  I will reopen this if I can reproduce it again more reliably.

**Comment by rkirov** [comment]
One can reproduce something like Evens' original issue without 'path', by the following program:

```ts
import * as fs from 'fs';
```

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "baseUrl": "."
    },
    "files": [
       "foo.ts",
       "typings/node.d.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

TypeScript will do a full node resolution looking for 'fs.ts', 'fs.d.ts', etc, on each level of the current project path, resulting in many os stats. Then 'node.d.ts' has internal 'declare module' imports, which are also looked against the file system first, before the module declarations is used. Moreover, this search is redone for every file that imports 'fs'. As far as I can tell VSCode doesn't cache any file stats (probably correctly given the file might reappear later).

I think this is purely TypeScript resolution issue and we have a proposal for fixing it here: https://github.com/Microsoft/TypeScript/issues/11979.
