### ISSUE TITLE
VSCode Ubuntu package update link may be broken

### ISSUE THREAD

**Issue by jounghoolee** [microsoft/vscode#126543]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64

- OS Version: Ubuntu 18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Steps to Reproduce:

1. sudo apt update
2. sudo apt upgrade

Output : 

Error:1 http://packages.microsoft.com/repos/code stable/main amd64 code amd64 1.57.0-1623259737
  404  Not Found [IP: 40.83.79.38 80]
Error:2 http://packages.microsoft.com/repos/code stable/main amd64 code-insiders amd64 1.58.0-1623821803
  404  Not Found [IP: 40.83.79.38 80]

E: http://packages.microsoft.com/repos/code/pool/main/c/code/code_1.57.0-1623259737_amd64.deb Fail to download files  404  Not Found [IP: 40.83.79.38 80]
E: http://packages.microsoft.com/repos/code/pool/main/c/code-insiders/code-insiders_1.58.0-1623821803_amd64.deb Fail to download files  404  Not Found [IP: 40.83.79.38 80]

When I manually access that URL, I could see vcode package directory structure has been changed since 16, June. I have no idea whether VScode updater should automatically find .deb file under changed directories. I found that deb file is available here. http://deb.rug.nl/ppa/mirror/packages.microsoft.com/repos/vscode/pool/main/c/code/ 

I guess I am the first one report this issue, and please let me know this is not common issue. I have not tried much more things such as reinstalling VScode.

**Comment by kafuuchino-desu** [comment]
got same problem here, can confirm that url does not exist

**Comment by iamCristYe** [comment]
https://github.com/dotnet/core/issues/6381

**Comment by joaomoreno** [comment]
Seems to have been some temporary networking issue in the Deb repo service. Seems OK to me now, can you try again?

**Comment by jounghoolee** [comment]
It works well now! Thank you!!
