### ISSUE TITLE
'Check for Updates...' should not download and apply update

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode#126580]
Clicking 'Check for Updates' should not EVER just download and apply at next reboot. NEVER.

It should only display an information box if an update is available and give user an option to download and apply it. Never just install it.
If you feel you need to make it so you should have to option buttons. One that says 'Check for Updates' and one that says 'Check for Updates and apply if available'

This is not how its supposed to be.

**Comment by joaomoreno** [comment]
This is how it's been since the product's inception and it suits the vast majority of the users. Sorry about that, but we'll keep it this way.

**Comment by HenrikHolmIT** [comment]
Just because this is how VSCode as always done it doesn't mean it's the most user-friendly solution.

And Im not suggesting you to remove or change anything existing. For those who like the way it works now can just keep clicking the 'I dont care about my productivity' button and update without knowing what has changed.

And then with a NEW button give users the option of reading the release page before they update VSCode.

Maybe add some telemetry and have a contest at see which button is most popular.
