### ISSUE TITLE
Make Clicking in Scrollbars Move By Page

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#126587]
Please stop locking issue comments so people aren't forced to create duplicates to ask questions about something an issue has already been created for!!!

[Make Clicking in Scrollbars Move By Page](https://github.com/microsoft/vscode/pull/104923)

Is this implemented yet?

If so how do I enable it?

If not why is it closed?

**Comment by alexdima** [comment]
@Neutrino-Sunset Here are the steps to enable it:
* `F1 > Preferences: Open Settings (JSON)`
* paste `"editor.scrollbar.scrollByPage": true`
* `F1 > Developer: Reload Window`

**Comment by Neutrino-Sunset** [comment]
That works, but it isn't listed in the default configuration (which is why there is no way to find it) and it's displayed in the config file as an `Unknown Configuration Setting`.

**Comment by ArturoDent** [comment]
And in my testing, it requires a reload after editing the settings file, which is strange.

**Comment by alexdima** [comment]
> And in my testing, it requires a reload after editing the settings file, which is strange

And this is the reason why the setting is not documented. The implementation requires more work in order to work like all other editor settings (to be applied while an editor is instantiated). That is tracked in https://github.com/microsoft/vscode/issues/123985
