### ISSUE TITLE
Add method/procedure name to search results

### ISSUE THREAD

**Issue by chrisafl** [microsoft/vscode#126505]
Sometimes I have to perform an impact analysis before making a modification to a certain element or column, which requires searching the codebase to determine what functionality will be impacted by the change.

Currently when searching in VSCode, VSCode will list the filename, and then the search matches in the results pane. I am requesting the ability to add another layer (grouping) in between that shows the method/function/procedure/etc from the Code Outline (and optionally disable the individual search results). This would allow me to quickly generate a high level overview of functionality impact which is useful when giving development estimates, etc.

Already, there is extra configuration available when you expand the search results by clicking the "Open in editor" button which allows you to customize the number of lines of context for each search result. I think the editor pane could contain other configuration items like search grouping as well. Maybe this could be expanded upon to be similar to IntelliJ which has a "Group By" button in their search results as well that allows multiple levels of grouping including directory, file, module, package, test/production, and usage type options. In this, I would just request the ability to group by "Outline" as well.

This would allow a robust solution to group search results according to user preference.

Search box:
"search term"

Current:
- file1.sql
  - **_search term_** here
  - also here is **_search term_**

Request:
- file1.sql
  - prc_get_results
     - **_search term_** here
  - prc_edit_item
    - also here is **_search term_**

**Comment by chrisafl** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Search doesn't start at cursor position (#124137)](https://www.github.com/microsoft/vscode/issues/124137)

I can confirm this is not the same issue. My request is not regarding how VSCode performs the search, but instead adding an additional layer of output to the search results for the sake of organization and analysis.

**Comment by roblourens** [comment]
Thanks for the request, we have thought about language-specific search features before, but it's not practical for us to do a feature like this right now
