### ISSUE TITLE
Custom hover not correctly placed when in window corner

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#126584]
Version: 1.58.0-insider
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:18:57.982Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-18-generic

Move the mouse over the notification status bar entry.
The tooltip appears at the wrong place

![image](https://user-images.githubusercontent.com/6461412/122393687-6e162380-cf75-11eb-906d-3179f537fbd8.png)

**Comment by Tyriar** [comment]
FYI @sandy081

**Comment by Tyriar** [comment]
@sandy081 I looked into this and I'm a little lost why this is happening just for only the pointer one, it works fine for the regular hover still:

![image](https://user-images.githubusercontent.com/2193314/122400923-0342f900-cf31-11eb-9f47-4c66a762c827.png)

**Comment by sandy081** [comment]
Will take a look. It works when sidebar is on right.

**Comment by sandy081** [comment]
![Kapture 2021-06-18 at 11 24 24](https://user-images.githubusercontent.com/10746682/122539626-171d5680-d028-11eb-9273-6e6d87dce809.gif)
