### ISSUE TITLE
Revisit workbench editor associations migration

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126581]
After having reviewed the code in https://github.com/microsoft/vscode/pull/126577, here are some thoughts:
* should we just remove it now given it has been run for a while and we have a fallback coming in from the PR to respect the old format
* if not, can we make sure that only the window that has focus writes to settings and not potentially all windows at the same time

There is also a couple of times code like this repeated that can probably be extracted to a reusable method:

```ts
// Make the correctly formatted object			
const newValue = Object.create(null);			
  for (const association of rawAssociations) {				
    if (association.filenamePattern) {					
      newValue[association.filenamePattern] = association.viewType;				
    }			
}
```

**Comment by lramos15** [comment]
> should we just remove it now given it has been run for a while and we have a fallback coming in from the PR to respect the old format
I would say no, we want everyone to be on the new setting and remove the fallback for the old setting
> if not, can we make sure that only the window that has focus writes to settings and not potentially all windows at the same time
I believe Sandeep is fixing this issue and ensuring that even if it triggers the update in all windows we won't have any race conditions
> There is also a couple of times code like this repeated that can probably be extracted to a reusable method:
I think that's only for the PR since if we convert like we've been doing there really won't be the old setting so we only have that code in the conversion function

**Comment by bpasero** [comment]
Hm, I didn't know that we are not taking the changes over to `main` though I do think there are some nice changes in that PR that I would preserve. For example:
* only reacting on config changes for the setting in question
* returning `{}` instead of `[]` when the setting is not defined to prevent unnedeed work

I suggest you hand pick some of the fixes over.
