### ISSUE TITLE
Notebook controller is not associated to notebook

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#126534]
Version: 1.58.0-insider (user setup)
Commit: 3e0c442a8ee9fdc037d627d70fe291f72af04cfd
Date: 2021-06-16T05:17:51.956Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

While developing Live Share, I am frequently running into the error "'notebook controller is NOT associated to notebook: vsls:/empty.github-issues'". I need to create notebook execution tasks outside of the `controllerHandler` function. However, when I do this, I get the following error message. 

![image](https://user-images.githubusercontent.com/22576531/122296442-452b5b00-ceaf-11eb-8647-1a4696805d8d.png)

I declared my controller with a notebookType of  `*` so that it would work with all notebook files the guest opens. How can I avoid this error? 

```
            const controller = vscode.notebooks?.createNotebookController(
                'LiveShare-Controller',
                '*',
                'Live Share Controller',
                (cells: vscode.NotebookCell[], notebook: vscode.NotebookDocument, controller: vscode.NotebookController) => this.controllerHandler(cells, notebook, controller)
            );
            this.notebookController = controller;
```

cc @rebornix

**Comment by alyssajotice** [comment]
According to Peng, this is a race condition that appears more frequently in Live Share sessions. @jrieken, please keep me updated on this.

**Comment by jrieken** [comment]
> According to Peng, this is a race condition that appears more frequently in Live Share sessions.

I am ignoring that because there is zero information about this...

What is very likely to happens is that the controller isn't selected yet, e.g when a notebook has multiple controllers users must explicitly select one. It's a user gesture. Please confirm that the `onDidChangeSelectedNotebooks` event fired on your controller and for the given notebook. Only then you can create executions.

**Comment by alyssajotice** [comment]
I understand what you're saying about selecting the controller. What user action will select a controller? Is there any way to do it programmatically?

Here's my repro extension in case that can be of help:

```
import * as vscode from 'vscode';

let notebookController : vscode.NotebookController;

export function activate(context: vscode.ExtensionContext) {
	const controller = vscode.notebooks.createNotebookController(
		'test-controller',
		'*',
		'Test Controller Label',
		(cells: vscode.NotebookCell[], notebook: vscode.NotebookDocument, controller: vscode.NotebookController) => controllerHandler(cells, notebook, controller)
	);   
	notebookController = controller;
	context.subscriptions.push(vscode.notebooks.onDidChangeCellOutputs((e)=> _onDidChangeCellOutputs(e)));
}

function _onDidChangeCellOutputs(e: vscode.NotebookCellOutputsChangeEvent) {
	const cell = vscode.window.visibleNotebookEditors[0].document.getCells()[0];
         try {
                 const task = notebookController.createNotebookCellExecution(cell); 
          } catch (e) { 
                 //fails
          }
	task.start();
	task.appendOutput([...e.cells[0].outputs]);
	task.end(true);

}

export function deactivate() {}
export async function controllerHandler(cells: vscode.NotebookCell[], notebook: vscode.NotebookDocument, controller: vscode.NotebookController) {
       // ...
}
```
I hard coded the cell indices, so you can test by running the second cell in this notebook:

```
[
  {
    "kind": 2,
    "language": "github-issues",
    "value": ""
  },
  {
    "kind": 2,
    "language": "github-issues",
    "value": "assignee:@me"
  },
  {
    "kind": 2,
    "language": "github-issues",
    "value": ""
  }
]
```

**Comment by jrieken** [comment]
> Is there any way to do it programmatically?

Not really. That's why I said "user gesture". It's the user selecting a kernel from the kernel picker or pressing execute cell when a kernel has been suggested. There is an internal command to force kernel selection but we are likely taking that away because it allows extensions to suppress other extensions. 

For LS it might need something specific/hackish where we simply expect your kernel to come

**Comment by alyssajotice** [comment]
Thanks for the explanation. I was previously unaware of the command. Changing this fixed the problem: 

![image](https://user-images.githubusercontent.com/22576531/122574348-6baeda80-d004-11eb-8261-c432cea33e14.png)

I'm unblocked now, but will need to find a permanent solution to the problem. I don't remember having this issue when we were using the vscode.KernelProvider API. We were able to set an `isPreferred` flag so that we always used the Live Share kernel. Could we do something similar with controllers?

**Comment by jrieken** [comment]
> We were able to set an isPreferred flag so that we always used the Live Share kernel. Could we do something similar with controllers?

We have kept a similar notion with notebook affinity but the problem is that you need an answer for the case of having two preferred controllers

**Comment by alyssajotice** [comment]
I will set the affinity to preferred, which is something I haven't been doing. Perhaps it uses the more recent controller that was set to preferred? Again, I didn't notice this as a problem with the kernel API so this may fix the problem.

**Comment by jrieken** [comment]
Today, the affinity doesn't auto-select a controller (not even when it's the sole controller) so for now you need to rely on the "magic" command

**Comment by alyssajotice** [comment]
Thanks so much for the info. Do you have any plans to add features to this part of the API? I am not sure how common this will be for users but it would be great to have a workaround.

**Comment by alyssajotice** [comment]
This is still an issue for Live Share.
