### ISSUE TITLE
No hover in project.json files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1265]
![capture](https://cloud.githubusercontent.com/assets/1931590/11782441/5e7a545a-a271-11e5-9e48-bc903d3550c4.png)

**Comment by aeschli** [comment]
The schema comes from http://json.schemastore.org/project.
`commands` does not have a description

**Comment by aeschli** [comment]
I created https://github.com/SchemaStore/schemastore/pull/68
