### ISSUE TITLE
terminal text note showing up in Ubuntu 20.04

### ISSUE THREAD

**Issue by abulfazl-haidary** [microsoft/vscode#126500]
Does this issue occur when all extensions are disabled?: Yes

- VS Code : 1.57.0
- OS Version: Ubuntu 20.04

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
