### ISSUE TITLE
Spinner wheel in Python Debugger / similar to Jupyter notebook (currently there is no visual indication that a debug command was launched)

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#126536]
Steps to reproduce:

1. Use Python VS Code extension to launch a new jupyter notebook
2. Execute a cell with `import time; time.sleep(20)`
3. Notice the spinner icon that moves, denoting that something is running (below the cell with current runtime in seconds):
![image](https://user-images.githubusercontent.com/5317244/119143591-c2c98b80-ba15-11eb-8548-728216111a6f.png)

Now switch to the python debugger: 

1. Use ctrl + shift + D to launch debug the current python file
2. Notice that the only visual affordance for seeing that something is running is the 'RUNNING' text in the bottom right in the call stack. 
![image](https://user-images.githubusercontent.com/5317244/119143862-1a67f700-ba16-11eb-8dda-7c6969d21656.png)

Just a thought, but adding a spinner icon besides 'running', or in the play/pause/stop on top while a debugging process is running, along with the timing info in seconds could be very helpful as a visual cue (I've found myself restarting processes frequently, unnecessarily)

_Originally posted by @altosaar in https://github.com/microsoft/vscode-python/discussions/16296_

**Comment by isidorn** [comment]
@brettcannon this is a fair request. However a spinner constantly moving would be a bit too nervous for my taste.
An additional decoration in the Call Stack view might help and I am open for ideas here.

**Comment by altosaar** [comment]
Just a thought - the spinner that runs when launching a new windows subsystem linux window or 'opening remote' for many seconds, would be great! Probably easy to re-use. 

![image](https://user-images.githubusercontent.com/5317244/123672882-d7b3ee80-d80d-11eb-9bc6-6881bde95ac1.png)

**Comment by brettcannon** [comment]
@isidorn just to be clear, this is an ask from @altosaar , I just opened the issue from our Discussions on their behalf.

**Comment by altosaar** [comment]
:'(
