### ISSUE TITLE
WrapTabs closing icon too far

### ISSUE THREAD

**Issue by gruvw** [microsoft/vscode#126532]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0

Steps to Reproduce:

1. `"workbench.editor.wrapTabs": true,`
2. Open multiple tabs

Is this an expected behavior?
I found the closing icon way too far away from the file name:
![Screenshot from 2021-06-16 23-03-41](https://user-images.githubusercontent.com/63407038/122293619-7e87b900-cef7-11eb-90db-e23286bed6b8.png)

**Comment by bpasero** [comment]
I do not see that:

![image](https://user-images.githubusercontent.com/900690/122343733-52475900-cf46-11eb-8b3f-31f8e33c3418.png)

**Comment by gruvw** [comment]
It has nothing to do with the "running extensions" tab.
It is about the last tab on the first line which is taking the whole space left till the right border of the window, making the closing icon too far.

**Comment by bpasero** [comment]
This is intentional to prevent a display like this one: 

![image](https://user-images.githubusercontent.com/900690/122346688-88d2a300-cf49-11eb-8975-7c2f0f7b7a01.png)

You can see my suggestion in https://github.com/microsoft/vscode/issues/113801#issuecomment-754495248 for how to improve this.

**Comment by gruvw** [comment]
What about having something like this instead ?
![Screenshot from 2021-06-17 08-50-59](https://user-images.githubusercontent.com/63407038/122348059-0519b600-cf4b-11eb-87b7-5d13b089717e.png)

**Comment by bpasero** [comment]
That results in the zig-zag pattern from the image above.

**Comment by gjsjohnmurray** [comment]
@bpasero using Developer Tools to add `style="flex: none;"` to an element of the last tab in the row I was able to get the Close action button to appear in a more useful place:

![image](https://user-images.githubusercontent.com/6726799/122358423-8887d700-cf4c-11eb-97be-4aa4a425c5dd.png)

I'll submit a PR that does this for all tabs, since it seems to be harmless to have this also on tabs that aren't at the end of a row.

**Comment by gruvw** [comment]
Perfect, this is exactly what I wanted. Thank you.

**Comment by gruvw** [comment]
Another screenshot, it feels wrong to have this kind of UI...
![Screenshot from 2021-06-18 13-45-32](https://user-images.githubusercontent.com/63407038/122556384-b7c94180-d03b-11eb-9aa9-0bf79ef4f55a.png)

**Comment by gjsjohnmurray** [comment]
@gruvw I agree. And the more action buttons get added to the right-hand end of the last row (e.g. by extensions) the more whitespace appears to the right of the final tab of previous row(s), visually detaching the Close button and status letter (M in your example above) further and further from the tab label. See the PR for ongoing discussion about this between @bpasero and me.

**Comment by bpasero** [comment]
Another workaround is to configure `workbench.editor.tabCloseButton: left` to have close buttons on the left.

**Comment by gruvw** [comment]
Yes but it still leaves the active tab line and the status letter till the end:
![Screenshot from 2021-06-18 14-28-29](https://user-images.githubusercontent.com/63407038/122560949-85bade00-d041-11eb-8a34-409b91c8c816.png)
