### ISSUE TITLE
VS Code crash if empty folder is tried to be open

### ISSUE THREAD

**Issue by Pakorasu** [microsoft/vscode#126548]
Issue Type: <b>Bug</b>

- Create an empty folder
- Open VS Code
- Click "File -> Open Folder"
- Select the empty folder
- VS Code Crash

This happen just after the May 2021 update, and selecting "Yes I trust the publisher of the files" prompt.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.90GB free)|
|Process Argv|--crash-reporter-id c7cd6371-aafd-40d5-8f0b-2e6ab27b502b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
vscode-html-css|ecm|1.10.2
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
vscode-test-explorer|hbe|2.20.4
vscode-ebnf|igo|1.0.3
vscode-python-test-adapter|lit|0.6.8
csharp|ms-|1.23.12
python|ms-|2021.2.633441544
vscode-pylance|ms-|2021.3.2
jupyter|ms-|2021.2.576440691
remote-wsl|ms-|0.56.5
test-adapter-converter|ms-|0.0.10
java|red|0.78.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.30.1

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
fyi @lszomoru @sbatten for potential duplicates
