### ISSUE TITLE
VScode often crashing after update

### ISSUE THREAD

**Issue by matthmit** [microsoft/vscode#126556]
Issue Type: <b>Bug</b>

Since the last update (1.57.0)  my vscode  is crashing all the time,today for example it crashed 4 times,i tried to reinstall it and also uninstalled some extensions i thought might be causing the crash but didn't work, my OS is W10 Pro.
![Screenshot (7)](https://user-images.githubusercontent.com/48168571/122342119-9a508680-cf1a-11eb-9eb2-93ae594dabd1.png)

Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.32GB free)|
|Process Argv|--crash-reporter-id a7f47140-0a95-4f50-95ed-8d630a1f1ad7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|6.4.0
code-runner|for|0.11.4
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.4.6

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805cf:30301675

```

</details>

**Comment by kettek** [comment]
Also getting this same problem while writing benign Svelte code.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1500X Quad-Core Processor           (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.94GB (4.66GB free)|
|Process Argv|--crash-reporter-id 7d31d56a-9dd1-4da0-95bf-9e34e8233de1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
dotjs|all|0.0.6
gotemplate|cas|0.4.0
xml|Dot|2.5.1
vscode-solution-explorer|fer|0.4.3
go|gol|0.26.0
polacode-2019|jef|0.5.2
sln-support|log|0.0.1
vscode-marko-peek|mar|1.1.1
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.23.12
remote-wsl|ms-|0.56.5
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
vscode-wren|nel|0.1.1
marko|pca|0.4.0
shader|sle|1.1.5
datapack-language-server|SPG|3.3.6
svelte-vscode|sve|105.1.0
umlet|the|1.0.4
cmake|twx|0.0.17
vscode-icons|vsc|11.5.0
vim|vsc|1.21.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlang:30322306
binariesv615cf:30323120

```

</details>

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash dump.

**Comment by matthmit** [comment]
Two days ago I've installed update 1.57.1  seems like the crash was fixed in this version.

**Comment by deepak1556** [comment]
Closing this for now based on above comment, can reopen if the issue persists.
