### ISSUE TITLE
TypeScript and JavaScript Language Features adds big delay before snippet apply

### ISSUE THREAD

**Issue by shchypylov** [microsoft/vscode#126562]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.57.0** 
- OS Version: **macOS 11.4**

Steps to Reproduce:

1. Launch VS Code
2. Wait until **Initializing JS/TS Language Features** ends
3. Open `.js` file and try to use snippet (e.g. `log`)

My `log` snippet:

```
"Print to console": {
	"scope": "javascript,typescript",
	"prefix": "log",
	"body": [
		"console.log('$2 --- ', $1);",
		"$3"
	],
	"description": "Log output to console"
},
```

In my case there is delay between type ending of `log` and appearing snippet suggestions dropdown.
If I type `log`, don't wait till suggestions dropdown appear and press `tab` it just adds  tab after `log` (I would expect that after pressing `tab` I would get `console.log()`)
If I type `log`, wait until Snippet suggestions appear and press tab - I get `console.log()`.

If I disabled build-in `TypeScript and JavaScript Language Features` plugin this problem disappears (even if snippet suggestions dropdown is not visible).

Thanks!

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"
