### ISSUE TITLE
Why have backslashes changed direction?

### ISSUE THREAD

**Issue by carriegitgraham** [microsoft/vscode#126538]
Issue Type: <b>Bug</b>

Automated relative path is now installing backslashes in the wrong direction when I use the "relative path" feature, so now I'm having to manually input all my file paths.
I don't know why this is.  Since the last update, when I try to automate filepaths from "relative" feature, it puts all the slashes in the wrong direction so I'm having to manually update them. This began after the last update.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.94GB free)|
|Process Argv|--crash-reporter-id 3ff2a802-7f73-4786-ab49-7059e0e306c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
prettier-vscode|esb|6.4.0
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

Also does this happen  with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by carriegitgraham** [comment]
Css. Sorry, forgot that bit.  Not sure what happened?

**Comment by mjbvz** [comment]
Do you see this with extensions disabled?

**Comment by carriegitgraham** [comment]
Ah - I have NO idea why that fixed it, but when I turned off/on, it worked.
Thank you. I feel like a noob, and thank you :-)
