### ISSUE TITLE
Cannot unset `editorSuggestWidget.selectedForeground`.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#126557]
When updated to VS Code 1.57, I tried to revert to the previous behavior that the selected item in editor suggestion uses the icon color and text color that are identical to the respective colors in their unselected state.

However, in 1.57, icons and text can only be set to the same single color, _i.e._ `editorSuggestWidget.selectedForeground`, in the selected item of the editor suggestion widget.

1.54 Insider
![image](https://user-images.githubusercontent.com/8168391/122344235-26919680-cf79-11eb-8c91-d2aa7c2238ba.png)

1.57
![image](https://user-images.githubusercontent.com/8168391/122343853-bdaa1e80-cf78-11eb-99a1-c0e2ca7d4571.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.0
- OS Version: Windows 7

Steps to Reproduce:

(n/a)

**Comment by misolori** [comment]
Please see https://github.com/microsoft/vscode/issues/126498#issuecomment-862659306 you'll have to either use different list style/color or create a new theme as our Default light theme has overwritten the `list.activeSelectionIconForeground`.

**Comment by wenfangdu** [comment]
This change is so unnecessary, I thought it was a bug, had to revert to `v1.56.2`.

**Comment by wenfangdu** [comment]
@misolori Any way to keep the icons' original colors? The current design is basically unusable for me.

**Comment by wenfangdu** [comment]
@misolori Any way to keep the icons' original colors?

The white icon is distracting and weird:

![image](https://user-images.githubusercontent.com/28700378/122661135-ca698500-d1b9-11eb-83f0-64bd7279c747.png)

**Comment by wenfangdu** [comment]
@misolori Any way to keep the icons' original colors? The white icon is distracting and weird:

![image](https://user-images.githubusercontent.com/28700378/122661135-ca698500-d1b9-11eb-83f0-64bd7279c747.png)

**Comment by infinnie** [comment]
> Please see [#126498 (comment)](https://github.com/microsoft/vscode/issues/126498#issuecomment-862659306) you'll have to either use different list style/color or create a new theme as our Default light theme has overwritten the `list.activeSelectionIconForeground`.

This has nothing to do with `list.activeSelectionIconForeground`. The icon color follows the color set in `editorSuggestWidget.selectedForeground`.

**Comment by misolori** [comment]
Please try again on the latest insiders as we've been tweaking this. The plan is, if you want to theme the active selected icons you can use `list.activeSelectionIconForeground`. This is useful if you have a strong contrasting active selection like our default dark/light themes. Previously, we were inheriting the icon from foreground, which may not be desirable depending on the theme.

**Comment by infinnie** [comment]
> Please try again on the latest insiders as we've been tweaking this. The plan is, if you want to theme the active selected icons you can use `list.activeSelectionIconForeground`. This is useful if you have a strong contrasting active selection like our default dark/light themes. Previously, we were inheriting the icon from foreground, which may not be desirable depending on the theme.

Can this value be unset too?

**Comment by misolori** [comment]
For other themes, you can definitely override the default. Unfortunately for our default dark/light, there is no way to unset it. That's why I linked to other issue where someone else tried to do a similar thing. Your best bet is to create a new theme where you have more control.

**Comment by infinnie** [comment]
> For other themes, you can definitely override the default. Unfortunately for our default dark/light, there is no way to unset it. That's why I linked to the other issue where someone else tried to do a similar thing (and has some suggestions). Your best bet is to create a new theme where you have more control.

Maybe a boolean to control whether to have that behavior set?
