### ISSUE TITLE
When  a new window is opened , a blank window getting opened along with it in mac

### ISSUE THREAD

**Issue by g1itsme** [microsoft/vscode#126588]
Issue Type: <b>Bug</b>

1. open VS with a repo ,click on new window from the top bar 
2. new window gets opened beside the existing window along with it a blank full window is opened

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id af3d72f5-31d8-48e5-bd59-9bdaeec30b06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.0
spellright|ban|3.0.58
jsonviewer|cci|1.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
githistory|don|0.6.16
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
prettier-vscode|esb|6.4.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
gc-excelviewer|Gra|3.0.42
excel-to-html-table|hon|1.1.1
beautify|Hoo|1.5.0
start-git-bash|McC|1.2.1
prettify-json|moh|0.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
errorlens|use|3.2.7
gitblame|wad|7.0.6
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805cf:30301675

```

</details>

**Comment by backto2020** [comment]
I have the same question after updating. When vscode starts, a blank window is also opened. So I have two windows when it starts. You have had the same problem before, like #70006 
![recording](https://user-images.githubusercontent.com/53009917/122941702-36a9db80-d3a8-11eb-916c-dd403e660c81.gif)

**Comment by backto2020** [comment]
I have set `"window.restoreWindows": "all"`, and also tried `"window.restoreWindows": "preserve"`, which didn't work. There may be bugs in this update.

**Comment by bpasero** [comment]
@backto2020 you might suffer from https://github.com/microsoft/vscode/issues/126725 which also lists a workaround
