### ISSUE TITLE
Allow to provide Walkthrough media in AsciiDoc format

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#126566]
https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs

There is a media field which allows currently only markdown (if i'm not mistaken); it would be nice to allow other formats such as AsciiDoc for instance.

Reason, I woudl expect that the getting started can be written by Technical Writer, not developer. AsciiDoc is a widespread language among them.

I think AsciiDoc renderer is not part of core VS Code, so I guess it could be an extension mechanism to provide. it will be more generic and allow also some othe rpotential languages.

**Comment by JacksonKearl** [comment]
Thanks for the feature request! Unfortunately we do not have any support for rendering AsciiDoc in core and we aren't going to open up an extension contribution point for this narrow yet complex use case.
