### ISSUE TITLE
:e! to be remapped (workbench.action.files.openFile failed)

### ISSUE THREAD

**Issue by danielb2** [microsoft/vscode#126504]
https://github.com/microsoft/vscode/issues/5437
touches on this but I can't comment since it's closed.

using `:e!` to discard changes to the current buffer (reverting the file) doesn't work, but gives an error with:
```
workbench.action.files.openFile failed, args: [] error: command 'workbench.action.files.openFile' not found
```

However, the fix is rather simple:
```
if exists('g:vscode')
    " e! should reload the file in vscode
    command! -bang -nargs=? Edit call VSCodeNotify('workbench.action.files.revert'>
endif
```

It seems reasonable this should be the default. Is there any reason it's not?

**Comment by bpasero** [comment]
I have no idea what you are talking about :-/. What is that script?

**Comment by danielb2** [comment]
oops, this was meant for the neovim vscode plugin

**Comment by bpasero** [comment]
Ah that is what I thought, thanks for clarifying!
