### ISSUE TITLE
Issue in Search Bar with Thunder Client

### ISSUE THREAD

**Issue by yashrajbothra** [microsoft/vscode#126654]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57
- OS Version: Mac OS 11.4

Steps to Reproduce:

1. Install Thunder Client Ext. (https://github.com/rangav/thunder-client-support)
2. Create New Request
3. Add Header Name 
4. Open Search Bar and Paste anything

https://user-images.githubusercontent.com/47683556/122523741-fa3b5000-d034-11eb-8192-c3821a2291d0.mov

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please report this on the extension repo. If the extension author believes the problem lies within VS Code (e.g. a regression on a recent release) they should raise an issue here.

**Comment by rangav** [comment]
This is vscode bug - #127881
