### ISSUE TITLE
vscode stopped working; crashes in main function

### ISSUE THREAD

**Issue by shashankram** [microsoft/vscode#126628]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: Windows 10

Steps to Reproduce:

vscode suddently stopped working for me, and refuses to start even after a system restart:

```
>code --version
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

![image](https://user-images.githubusercontent.com/21697719/122474610-54c2a680-cf78-11eb-9f1a-e55b1dd83c2f.png)

**Comment by JakeShirley** [comment]
Getting the same thing here locally.  Just started this morning.

**Comment by JakeShirley** [comment]
Another interesting bit, if I invoke `code .` in a terminal I get this:
```
PS C:\src> code .
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by joaomoreno** [comment]
This feels like a broken update, unfortunately, /duplicate #47841

Can you uninstall and reinstall VS Code?

**Comment by shashankram** [comment]
This happened without any update being performed on my end. I had to uninstall vscode and install the latest version to resolve this.

**Comment by JakeShirley** [comment]
That's true for me too (I think).  I came back to my computer the next day and:
- I could no longer open new fresh windows of Code
- My existing open window did seem to work
- If I opened a new window from my existing window I got an "empty" window that was just frozen.

Installing a fresh build fixed it.
