### ISSUE TITLE
Failed to set git-bash as terminal

### ISSUE THREAD

**Issue by xshi3x** [microsoft/vscode#126649]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: windows 10.0.19042

Steps to Reproduce:

This is my setting.json
![image](https://user-images.githubusercontent.com/84755372/122518222-83598380-d043-11eb-9458-7d340be1d292.png)
Before restarting vscode, a fault was reported directly.
![image](https://user-images.githubusercontent.com/84755372/122518401-b9970300-d043-11eb-8f79-4132b9735c41.png)
After restarting vscode, this problem will still be reported, and git-bash is not added to vscode.
The question helps to configure #terminal.integrated.shell.windows# or #terminal.integrated.shellArgs.windows#, but both of them seem to be no longer supported.

**Comment by meganrogge** [comment]
I'd suggest deleting the entry you have for "Git Bash". I suspect that path is invalid.

**Comment by icyi2i** [comment]
@meganrogge Not sure but this is related to VSCode restricting from setting any terminal name other than "Command prompt" and "Powershell". I had the same problem and bypassed it by setting the path of bash with name of Command prompt.

![image](https://user-images.githubusercontent.com/50752561/122679150-679eda80-d207-11eb-86e7-b7da455f13ca.png)

![image](https://user-images.githubusercontent.com/50752561/122679178-83a27c00-d207-11eb-8b61-4ca922ed6bbb.png)

Also the option to edit is only available in OSX and linux, and a dropdown is available in Windows.
Please check the images once. Thanks!

**Comment by xshi3x** [comment]
I tried to install git in the C:\Program Files\Git path, and VScode can use git-bash. This bug seems a bit ridiculous, why can't git be installed in a custom directory!

**Comment by Tyriar** [comment]
This warning and it not showing up in the dropdown means that the profile failed validation which likely means the path is wrong as @meganrogge mentioned. The reason it worked when you reinstalled to the default path is we have a pretty extensive list of paths to check for the default path:

https://github.com/microsoft/vscode/blob/c4f332d5e642cd702e79ff74489095f6eda536dd/src/vs/platform/terminal/node/terminalProfiles.ts#L196-L209

So chances are you just had the path wrong, if you have more info/proof that the path is correct we could try repro though.
