### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by ZeKap** [microsoft/vscode#126676]
We already have some extensions to connect to a server by FTP, but these extensions are hard to use and have some bugs. I think it could be very cool of we could connect to a server by default without having to install extensions.

**Comment by bl-ue** [comment]
Well @ZeKap that's a lot of work — and the VS Code team are allready quite busy 😆

**Comment by ZeKap** [comment]
Yes, I know they already have a lot of work. I'm just saying that if they have time to do it someday, it could be really cool, to improve VSCode.
