### ISSUE TITLE
Native Notebooks - Drag and Drop area very small 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#126615]
While I love having the markdown cells inline with the code cells, having the new compact setting makes the area to drag and drop cells small (especially when they aren't long or have the cell status bar set to hidden). It's especially hard when I try to move the cell but end up clicking run. I actually wish the setting had brought the markdown cells to the code line, not the other way around. 

![image](https://user-images.githubusercontent.com/19276747/122453039-c3930600-cf5e-11eb-81c1-889f0af146ea.png)

![image](https://user-images.githubusercontent.com/19276747/122453215-f806c200-cf5e-11eb-9094-9230241e57ad.png)

I've taken a screenshot of a cell in my notebook where the code reaches the farthest right. All the other cells in the notebook reach up to this point, or further to the left. There is a lot of white space to the right. 

![image](https://user-images.githubusercontent.com/19276747/122452342-056f7c80-cf5e-11eb-813e-cc33e0039f41.png)

Could we potentially add some breathing room on the left side so everything doesn't feel so tight? 

![image](https://user-images.githubusercontent.com/19276747/122453492-44ea9880-cf5f-11eb-8c80-2772a9d2fbbf.png)

**Comment by misolori** [comment]
Marking this is a feature request in case we want to add a setting to adjust the gutter width (just like the tree indent setting).

**Comment by roblourens** [comment]
Personally, I am not such a big fan of the "compact mode" that removes space from the left gutter and would prefer just having a little more space there normally

**Comment by roblourens** [comment]
We could also close this saying that people like me can just disable compact mode. Wouldn't implement a setting for a custom number of pixels of space

**Comment by claudiaregio** [comment]
Would there be another way to achieve having all cells aligned without having compact mode?

**Comment by roblourens** [comment]
I think this is baked as-is
