### ISSUE TITLE
Long lines in output view overwrites the vertical scrollbar

### ISSUE THREAD

**Issue by michael-hillmann** [microsoft/vscode#126661]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Long lines in output window overwrites the vertical scrollbar.
Non critical, but looks ugly.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (9.48GB free)|
|Process Argv|--crash-reporter-id 3fdd18c5-c819-4548-bc4d-55655bb8daf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.6.11
doxdocgen|csc|1.3.2
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|6.4.0
vscode-open-in-application|fab|1.0.6
vscode-projects-plus|fab|1.23.3
todo-tree|Gru|0.0.213
vscode-drawio|hed|1.5.0
terminal-git-mergetool|hun|0.3.0
output-colorizer|IBM|0.1.2
jenkinsfile-support|ivo|1.1.0
c-cpp-flylint|jbe|1.9.3
vscode-text-pastry|jkj|1.2.0
graphql-for-vscode|kum|1.15.3
cortex-debug|mar|0.3.12
git-graph|mhu|1.30.0
perforce|mjc|4.15.2
vscode-docker|ms-|1.13.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
vscode-drawio-plugin-mermaid|nop|0.1.4
vscode-drawio-plugin-rtl|nop|0.0.7
vscode-drawio-plugin-wavedrom|nop|0.0.1
vetur|oct|0.34.1
vscode-print|pdc|0.9.4
platformio-ide|pla|2.3.2
prisma|Pri|2.25.0
vscode-yaml|red|0.20.0
explorer-exclude-vscode-extension|Red|1.2.0
wordcount|rid|0.1.33
LiveServer|rit|5.6.1
vscode-zipexplorer|sle|0.3.1
character-count|ste|0.1.1
pdf|tom|1.1.0
latex-support|tor|3.7.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.5.0
vscode-nginx|wil|0.7.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30323119

```

</details>

**Comment by isidorn** [comment]
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
Can you please attach a picture
