### ISSUE TITLE
use some webviews in sidebar position bug

### ISSUE THREAD

**Issue by johnsen-zhang** [microsoft/vscode#126639]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. create multi-webviews in sidebar
2. change visible or collapsed some times, webview sidebar iframe’s parent(div) position not change

![image](https://user-images.githubusercontent.com/14013459/122502430-32d52c80-d029-11eb-9fed-838ae350c281.png)

after operate

![image](https://user-images.githubusercontent.com/14013459/122502648-96f7f080-d029-11eb-884c-e96335ddecab.png)

![image](https://user-images.githubusercontent.com/14013459/122502721-c60e6200-d029-11eb-9fa1-0bdb06b2527f.png)

**Comment by boltex** [comment]
Same as https://github.com/microsoft/vscode/issues/127204 ?

**Comment by johnsen-zhang** [comment]
> Same as #127204 ?

yes! it's same

**Comment by boltex** [comment]
I think this bug is tracked originally from https://github.com/microsoft/vscode/issues/110450
