### ISSUE TITLE
debug.log again

### ISSUE THREAD

**Issue by flipchart** [microsoft/vscode#126664]
VSCode writing debug.log in random directories in my workspace. A line from one of them:

[0618/120800.320:ERROR:registration_protocol_win.cc(102)] CreateFile: The system cannot find the file specified. (0x2)

Version: 1.57.0 (system setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Further info: it happened in this instance due to low system resources - mem and cpu (Visual Studio has become a hog lately)

Some files can be deleted immediately, some remain locked and can't be deleted (I imagine they can after closing VSCode)

**Comment by ldrick** [comment]
I installed vscode 1.59 today on Windows 10 machine and having `debug.log` in nearly every directory created.
It started after updating vscode immediately and happens in directories, whenever I safe a *.ts file. I closely watched, it does not happen in folder, where only *.md files recide.

It can be reproduced with my Repo here, by just editing any *.ts file:
I am using vscode extensions from recommended section in my repo.
https://github.com/ldrick/trade-indicators

Most of the files can be deleted, but they get regenerated again, only the debug.log in root folder is locked until vscode is closed.

**Comment by deepak1556** [comment]
@ldrick can you share a gif starting from a fresh state demoing the issue. Thanks!

**Comment by ldrick** [comment]
@deepak1556 Firstly thank you, but I am sorry, the problem vanished on my local over night. I started my Notebook this morning and it is not happening at all. As for now, I am sorry, I can't give more information. If I ever see it again, I will record immediately.

**Comment by thany** [comment]
Same problem here. These debug.log files appear seemingly randomly. No idea how to reproduce.

Here's a thought: just *never* write a debug.log. There has *got* to be some function somewhere in VScode that says to write a debug.log file. Remove that please 😀

**Comment by weinand** [comment]
There is nothing in VS Code's source that writes a "debug.log". Either this comes from an extension or from some underlying technology (e.g. Electron).

**Comment by deepak1556** [comment]
We had reports before and that was from our crash reporter, details of which are in https://github.com/microsoft/vscode/issues/115874#issuecomment-776406845.

It is hard to say where the problem is without a reliable repro, but one thing that can help confirm is do check if the issue happens when run with `--disable-crash-reporter`
