### ISSUE TITLE
Consider to make editor override service the editor resolver / registration service?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126603]
The more the editor override service grows the more I think it should not have any "override" in its name, because it will eventually be used for all editors (ideally) and then it is not about overrides anymore, but rather resolving an untyped editor to an editor input based on rules.

Another related thing is: today we require you to register an editor for an editor input, e.g.:

https://github.com/microsoft/vscode/blob/eebf8e876ab99688b167b98874ca2b3c17822e4f/src/vs/workbench/contrib/files/electron-sandbox/files.contribution.ts#L14-L24

I wonder how this correlates with the editor resolver service and whether this should also move somehow into the service. Because logically it doesn't make so much sense to me that I need to register an editor resolver in one way and my editor in a completlely different way.

**Comment by lramos15** [comment]
Maybe a nice balance to not overfill the editor resolver service is we have everyone register with the resolver service and internally it pipes through and registers the necessary info with the `EditorInputResolverService` or whatever we would call it.

**Comment by bpasero** [comment]
I pushed some renames so that the registration code now is:

```ts
Registry.as<IEditorPaneRegistry>(EditorExtensions.Editors).registerEditorPane
```

**Comment by lramos15** [comment]
Does it make sense to merge the registration now? Because one is for panes and one is for editorInputs

**Comment by bpasero** [comment]
Yeah can we maybe open a new issue for that to discuss, or leave this one open specifically for this? I am not entirely sure if we can do this already now before all editors have adopted untyped inputs...
