### ISSUE TITLE
Reconcile file changes between restarts

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12665]
- VSCode Version: 1.6 Insiders
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Create a git repo. Do a commit in `master` branch with two files, `hello.ts` and `README.md`.
2. Make branch `test`, remove `hello.ts` and commit.
3. Switch back to `master` and open the project in VSCode. Open both files.
4. Close VSCode. 
5. `git checkout test`
6. Reopen project in VSCode.
7. Although `hello.ts` is not there, it is present in Open Editors, Tabs and Quick Search:

![image](https://cloud.githubusercontent.com/assets/4033249/18845602/39bedf26-83d7-11e6-9380-bdbbd95ba6fb.png)

![image](https://cloud.githubusercontent.com/assets/4033249/18845644/5d8403d2-83d7-11e6-967a-8daedfca7e65.png)

Trying to open `hello.ts` will show Error, but I think VSCode should store branch info in cache and check against it in startup.

**Comment by joaomoreno** [comment]
This should easily reproduce without `git`: it has nothing to do with `git`.

**Comment by bpasero** [comment]
I have updated the title: We currently do not detect file changes that happen between restarts of VSCode.

**Comment by octref** [comment]
The thing is as git operations in VSCode is still very limited, people would do a lot of things on command line/their GUI tools.
And each branch might be very different. Notable examples include `gh-pages`.
I think Code could store branch information on exit and selectively use cached info to restore workspace.
