### ISSUE TITLE
Eslint not working

### ISSUE THREAD

**Issue by ktjd123** [microsoft/vscode#126624]
Issue Type: <b>Bug</b>

Eslint doesn't anymore working after updating? (maybe, doesn't work even I didn't do anything).

The other projects of mine is not working anymore so I don't think it's problem of my project's code.

```js
[Info  - 5:01:47 AM] Failed to load plugin 'import' declared in '.eslintrc.js': Cannot find module '../5/CheckObjectCoercible' Require stack: 
```

The first log is this, and when I resovle this another error comes out until I remove all eslint configs.

Thank you and always appreciate your works.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 7|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id e50cd7f9-a9f4-4de8-946e-977bac5d39f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|6.4.0
HTMLHint|mka|0.10.0
vscode-scss|mrm|0.10.0
vscode-language-pack-ko|MS-|1.57.1
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
even-better-toml|tam|0.12.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615cf:30323120

```

</details>

**Comment by dbaeumer** [comment]
@ktjd123 does validation happen correctly in the terminal using the eslint command? If yes, can you provide me with a GitHub repository I can clone that demo what you see.

**Comment by ktjd123** [comment]
Sorry for wrong issue. executing command have also error, so it seems to be eslint's problem.
