### ISSUE TITLE
Custom hover should hide when typing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126657]
I think a hover should not remain open when I type somewhere.

![recording](https://user-images.githubusercontent.com/900690/122532192-8e4eec80-d020-11eb-9dd6-4bef57450c55.gif)

**Comment by kashishmadan** [comment]
Hi, can you please share more details on how to exactly reproduce the issue and what version/OS? I would like to work on this issue.

**Comment by Tyriar** [comment]
To repro:

1. Open search side bar
2. Click into text box
3. Hover an icon in the side bar to get the hover to show
4. Type some letters, the hover stays visible

You might need to use the [insiders version](https://code.visualstudio.com/insiders/) to get the new style hovers to show up
