### ISSUE TITLE
Short cut to copy relative file path doesn't work

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#126604]
Issue Type: <b>Bug</b>

The `copy active file's relative path` default shortcut is: cmd + alt + shift + c.

Pressing this combination of keys doesn't nothing on my Mac.

Using the command palette or right clicking on the file's tab works as expected.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_2687632 --crash-reporter-id 8a62a4ff-e416-46c8-bdf6-c66057d5ae5c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(3 theme extensions excluded)<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30319631
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by ArturoDent** [comment]
There is a `when` clause for that command of `!editorFocus`.  Are you using the command with focus somewhere besides the editor?  Works fine on W10 where the keybinding os Ctrl+K Ctrl+Shift+C.

**Comment by warpdesign** [comment]
Yes, the editor is active. Here is a video showing the problem:
 - I first paste to show that clipboard contains the `test` string
 - then I use the `copy relative path` context menu and press `cmd+v`: it pastes `foo.ts` as expected
 - then I copy `test` to the clipboard again
 - finally I press `cmd+alt+shift+c` and then `cmd+v` and it pastes `test` instead of `foo.ts`, as if nothing happened with the `cmd+alt+shift+c` shortcut

https://user-images.githubusercontent.com/199648/122543575-34542400-d02c-11eb-9fc9-c3aff2e7fe1b.mov

**Comment by ArturoDent** [comment]
The keybinding will not work because it has a default `when` clause restriction of `!editorFocus`.  (Note the `!` indicating not or false).  So the function will NOT work when an editor is in focus.  You could easily remove that restriction:

```jsonc
	{
		"key": "cmd+alt+shift+c",
		"command": "copyRelativeFilePath",
		// "when": "!editorFocus"
	},
```

**Comment by warpdesign** [comment]
Ooops, I don't know why but I thought the editor had to be active, but it's the opposite.

So actually it works as expected when the editor is not active.
