### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by AhmadEvangelista** [microsoft/vscode#126688]
Issue Type: <b>Performance Issue</b>

when i command npm start my computer turn blue screen.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (4.86GB free)|
|Process Argv|-n --crash-reporter-id 938469f7-b6f2-4890-937c-61d6de2df057|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	  1556	code main
    0	    30	  1940	   crashpad-handler
    0	    95	  3976	   gpu-process
    0	    46	  5148	   utility
    0	    81	  5672	   window (Issue Reporter)
    0	    80	 11368	   shared-process
    0	    62	 11596	     ptyHost
    0	   147	 12092	   window (Visual Studio Code)
    0	   121	  2400	     extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.4.0
vscode-icons|vsc|11.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615cf:30323120

```

</details>

**Comment by meganrogge** [comment]
Does it happen if you run this in an external terminal too?
