### ISSUE TITLE
I hope that the text contrast can turn off the text background

### ISSUE THREAD

**Issue by Zz-886** [microsoft/vscode#126672]
Issue Type: <b>Feature Request</b>

I hope that the text contrast can turn off the text background
I hope that the split editor can synchronize up and down sliding

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by IllusionMH** [comment]
It looks like 2 separate requests (contrast and split editors) and should be in separate issue. At least it's not clear how contrast related to split editors.

Also could you clarify what "text contrast can turn off the text background" means end examples of how it should behave.
