### ISSUE TITLE
Expose API to know current theme (light/dark)?

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#12668]
I'd like to propose that the API which is used to determine whether the current theme is light/dark be made public (if possible) so that extensions can use it to style their components. I've felt the need for this while redesigning the [git history](https://github.com/DonJayamanne/gitHistoryVSCode) extension where the plugin itself is hosted within a webview, and thus can't access the parent's classes to determine whether the vscode editor has dark or light theme.

**Comment by jrieken** [comment]
dup of #10010
