### ISSUE TITLE
[Test API] Pass the test item instance when triggering contributed command from the test explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#126646]
Currently we can contribute the command to the test explorer nodes via:

```
"testing/item/context": [
    {
	"command": "helloWorld",
	"group": "inline"
    }
]
```

This is great!

Here is a feedback from this contribution point. When I play with this contribution point, I found that the param passed to the command is a string, looks like the id of the node. Can we the node instance(test item) as the param? Just like what the current tree view api does.

Because by passing the id string, the test runner itself needs to store the mapping from id to test items, and then do some further operations. meanwhile, if other extensions want to register commands to the test explorer, the test item can provide more information compared to just having the id.

// cc @connor4312

**Comment by connor4312** [comment]
This can be done, but note that the item will be a generic `TestItem<void>` -- a different instance than created by the extension, and without `data`. The reason is that any extension in any extension host can contribute items to the context menu, and the `data` is not serializable between them.

**Comment by jdneo** [comment]
Thank you @connor4312. It's fine without data, having information like uri is good enough
