### ISSUE TITLE
Debugging node w/ source maps in linked code in node_modules doesn't work

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#12664]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Use `npm link` to link to a dependency in a node app
2. Put a debugger statement in code in the dependency
3. Debug the node application with `"sourceMaps": true`

The debugger pauses on this stack frame:

    (anonymous function) <error: base path missing>

Clicking on the frame:

    Source Unknown: Source is not available

Switching to `"sourceMaps": false` in launch.json shows the code/break point correctly (but of course no source map). I do this pretty often and it used to work so this seems like a regression issue.

Seems like this kind of error should pretty much never happen, even if there's a problem with the source map, the compiled JS should show per https://github.com/Microsoft/vscode-node-debug/issues/23

**Comment by isidorn** [comment]
I know @roblourens fixed some issue with the base path missing thus forwarding to him to assess this issue.

**Comment by roblourens** [comment]
@jamietre This sounds like https://github.com/Microsoft/vscode-node-debug/issues/96, and should be fixed in Insiders now. Please let me know if it still reproes.
