### ISSUE TITLE
[Test Explorer] failed test items seem to be excluded from explorer sorting

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#126620]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 
   ```
    Version: 1.58.0-insider (Universal)
    Commit: a81fff00c9dab105800118fcf8b044cd84620419
    Date: 2021-06-17T05:16:15.391Z (14 hrs ago)
    Electron: 12.0.11
    Chrome: 89.0.4389.128
    Node.js: 14.16.0
    V8: 8.9.255.25-electron.0
    OS: Darwin x64 20.5.0
   ```
- OS Version: MacOS 11.4

Not sure if this is an intended design, the test explorer sorting didn't seem to apply to the failed items, which are always displayed on the top within its level. If there is a "status" based sorting, then it probably should be explicitly listed as a 3rd sort option?

Steps to Reproduce:

1. create 2 test items, make the first one pass and the second fail.
2. test explorer will always show the failed ones first, regardless of their locations or names

**Comment by connor4312** [comment]
This is intentional; items always get sorted by status first

**Comment by connectdotz** [comment]
hmm... let me try a use case illustrating why sometimes it might be desired not to sort by status...

Sometimes we write tests a bit like a "story", it carries some context and "narrative", for example, a test file like this:
```
describe('when user select sort by locations', () => {
  test('all items should be sorted by their locations', () => {...});
  test('and the unknown-location items will be at the bottoms', () => {...});
  test.each([['pass'], ['fail']]))('item status change to "%s" should not alter display order', () => {...}); // this will generate 2 tests results
});
```
this will generate the following test items:
```
when user select sort by locations 
  all items should be sorted by their locations
  and the unknown-location items will be at the bottoms
  item status change to 'pass' should not alter display order 
  item status change to 'fail' should not alter display order (fail)
```

Now if we move the failed item to the top it kind of breaks the flow and the grouping of the 2 last parameterized tests. I understand sometimes test status might the preferred sorting order, just like sometimes locations or names might be the desired sorting option... 

Therefore, the question is why not make "sort by status" just another sorting option instead of hard-code and forced it on all users for all use cases?

**Comment by Bilalh** [comment]
Would also be useful for Behavior-driven development (or BDD) test frameworks such as [behave (python)](https://behave.readthedocs.io/en/stable/tutorial.html) which also make tests who ordering tell a story.

**Comment by connor4312** [comment]
It sounds people don't care about "sort by name"/alphabetically, and want either declaration order or status. I'll swap the sorting to do that -- just having two criteria avoids a tri-modal sorting which we don't do elsewhere in the UI yet.
