### ISSUE TITLE
Add me to the 'Microsoft' organization

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/vscode#126651]
I request the admin of this organisation to add me to the 'Microsoft' organization.

**Comment by vedantmgoyal2009** [comment]
Please add me

**Comment by Mlocik97** [comment]
Please send me here You credit card number with expiration date, CVE, also other account info and password for it.

**Comment by vedantmgoyal2009** [comment]
Why do you want credit card number for adding to the organisation, just invite me.. 
My GitHub Username: vedantmgoyal2009
