### ISSUE TITLE
MacOS Touchbar "Run without debugging" / "Start debuging" are mapped incorrectly

### ISSUE THREAD

**Issue by PashaPash** [microsoft/vscode#126675]
Issue Type: <b>Bug</b>

Arrow button without bug icon works as "Start debuging"
Arrow button with bug icon works as "Run without debugging"

That is quite confusing. Could you please fix up the mapping?

VS Code version: Code 1.57.0 (Universal) (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id d031a4cc-97b3-4f0f-95bf-7a9047dc5e4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.24.5
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
remote-containers|ms-|0.183.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674
binariesv615:30323119
vsccppwtct:30322537

```

</details>

**Comment by bl-ue** [comment]
@PashaPash why notopen a PR yourself?

**Comment by weinand** [comment]
Already fixed in Insiders.
