### ISSUE TITLE
Feature flag/setting for Panels in Activity Bar buttons UI

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12662]
The new UI to switch to a particular panel is a good step forward, but it needs more cooking and at the same time we want to get feedback. Therefore add a setting for enabling the new UI, the setting should be off by default.

The plan is that we announce the feature in the release notes and invite users to provide feedback.

**Comment by isidorn** [comment]
This is done 2 hours ago ;)
The setting is called `workbench.panels.showInSIdebar`
