### ISSUE TITLE
keyof不提示详细信息

### ISSUE THREAD

**Issue by see7788** [microsoft/vscode#126652]
Issue Type: <b>Bug</b>

偶然配置了tsconofig.json.keyofStringsOnly=true，再取消，悬停keyof就不在提示具体参数(应该是never，不应该是这样提示//只是偶然这样)
<img src="http://see7788.com/static/test88/3.JPG">
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.43GB free)|
|Process Argv|--crash-reporter-id da5a8d6f-aa03-4207-a1df-d322721ffce9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
githistory|don|0.6.16
gitlens|eam|11.5.1
vscode-mysql|for|0.4.0
githd|hui|2.2.4
git-graph|mhu|1.30.0
vscode-docker|ms-|1.13.0
vscode-language-pack-zh-hans|MS-|1.57.1
remote-github|niu|0.3.0
gitblame|wad|7.0.6
vscode-import-cost|wix|2.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615cf:30323120

```

</details>

**Comment by xisui-MSFT** [comment]
Trying to translate:
1. Set 'keyofStringsOnly=true' in tsconfig.json
2. Cancel the change in (1)
3. Details wouldn't show when hovering on 'keyof' after.

**Comment by yume-chan** [comment]
> 请您直接编辑此问题，不要提交回复或新问题。

**Comment by xisui-MSFT** [comment]
@yume-chan I'm not the author of this issue so unfortunately I can't edit the original description.

**Comment by yume-chan** [comment]
> @yume-chan I'm not the author of this issue so unfortunately I can't edit the original description.

Sorry, didn't see that.

**Comment by mjbvz** [comment]
Closing this as it sounds like a TypeScript issue instead of a VS Code specific problem

Please [file a bug upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
