### ISSUE TITLE
vscode.workspace.openTunnel problem for codespaces

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#126630]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: N/A
- OS Version: Windows 10, 19043.1052

I opened a bug several months ago: #112774 (Internal: https://github.com/microsoft/vssaas-planning/issues/2262). While the original issue is resolved, seems like there are still problems with openTunnel or codespaces.

When connected to a codespace, in a UI extension, do 'await vscode.workspace.openTunnel()'. Although the connection can be established, looks like the connect may be reset or disconnected unexpectedly the **first time**. Subsequent runs succeed reliably.

GDB error:
Unable to start debugging. Unexpected GDB output from command "-target-select remote localhost:36549". Remote communication error. Target disconnected: Connection reset by peer.

GDB server output:
Listening on port 2345
Remote debugging from host 192.168.35.1, port 21622
Remote side has terminated connection.  GDBserver will reopen the connection.
Listening on port 2345

**Comment by alexr00** [comment]
@xisui-MSFT There events that can cause VS code and/or Codespaces to close a tunnel and re-open it with slightly different properties, and that's what it sounds like is happening here. Have you tried using the proposed api `onDidChangeTunnels` to listen for changes to the tunnels? `openTunnel` was never really intended to be called by arbitrary extensions that want to hold on to the tunnel. Rather, it is intended to be used as a way to tell VS Code to create a tunnel that will be visible to the user in the Ports view. 

The `asExternalUri` is the API that extensions should consider using when the extension itself needs the URI.

**Comment by xisui-MSFT** [comment]
Thanks for the suggestion. I will try onDidChangeTunnels event.

We wasn't able to use asExternalUri because we it only supports http/https, but we need to forward TCP ports.

**Comment by xisui-MSFT** [comment]
I looked at onDidChangeTunnels event, and seems like the tunnel is removed from the tunnel list and added back. So I guess that's what you meant by "close and re-open".

However, knowing this doesn't actually resolve our issue. The actual connection is done by the debug adapter (MIEngine), using commands like "gdb target remote". Disconnecting makes the debug session fail entirely and looks like there's no way we can prevent that. @weinand What do you think would be the best way to resolve this issue? Do you think asking MIEngine to have a "retry" function makes sense?

**Comment by weinand** [comment]
@xisui-MSFT

Yes, a debug adapter could "internally" retry a connection attempt if the connection was failing and there is a chance that it will eventually succeed. 

Alternatively the retry could be done "externally" (outside of the debug adapter). The Debug Adapter Protocol has a way to ask the client (e.g. VS Code) to restart a debug session. For this a debug adapter can specify a `restart` property on the `Terminated` event. See https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated.

Typically a DA only sets the `restart` property on the `Terminated` event if the DA's launch configuration has a corresponding `restart` property that a user can set.
The idea is that users can configure a debug session to be "auto-restarting": if a debug session fails for a good reason (e.g. a source code change), VS Code will restart the session automatically.

**Comment by xisui-MSFT** [comment]
@alexr00 Hi Alex, before we get started with the debug adapter approach, may I ask why it now behaves differently than before, and why it is hard to keep the old behavior?

**Comment by alexr00** [comment]
@xisui-MSFT in a Codespace, the Codespaces extension essentially provides the implementation for `openTunnel`. If it used to work differently then the Codespaces folks must have changed something there. `openTunnel` is also proposed API, which means there is zero guarantee that it will exist or work the same tomorrow.
