### ISSUE TITLE
Activate extension if found a specific file in a specific location

### ISSUE THREAD

**Issue by rbalet** [microsoft/vscode#126645]
I would like being able to have somewhere a config, in my extension list, where I'm able to choose when the extension should be loaded.

Example : 
If I'm opening a file, and I have in the root folder a file named `angular.json` then load the [angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) and [Angular Schematics](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics) extension

If not, then let them disable.

If I found a `.gitignore` file, then add the [git Blame](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame) extension

If I found a `src/assets/i18n/de.json` then load the [German - Code spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-german) extension, ...

I think, the may help a lot since, sometime, we do not find it useful to take time to enable / disable specific extension for small project that we will be working on for 2 weeks or so.

I would see this settings under the `Add to Workspace Recommendations`
![image](https://user-images.githubusercontent.com/44493964/122511846-2db3b580-d008-11eb-8632-4a3383be9cce.png)

**Comment by yume-chan** [comment]
Currently, extension authors can control when their extensions activate (inactive extension doesn't consume CPU or memory).

Angular Schematics extension already has this: https://github.com/cyrilletuzi/vscode-angular-schematics/blob/f3b9eca983d303333c7ea36d326f3418b2c99483/package.json#L41-L46 . 

You can request other extensions to adopt if that "activation file" is universally enough. For example, lacking of a `.gitignore` file doesn't 100% mean it's not a Git repository.
