### ISSUE TITLE
Only absolute urls are supported

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#12660]
- VSCode Version: 1.5.3
- OS Version: OS X 10.10.3

Intermittently I keep receiving "only absolute urls are supported". Sometimes, the command execution works and sometimes it can't even find a command. If it finds a command then execution intermittently keeps displaying this error. 

Any thoughts? Below is the code snippet where debugger throws exception (index.js line 54).

``` 
// build request object
		var options = new Request(url, opts);

		if (!options.protocol || !options.hostname) {
			throw new Error('only absolute urls are supported');
		}
```

**Comment by isidorn** [comment]
@riteshatsencha can you please provide reproducable steps?
What index.js are you refering to? Are you trying to debug?

**Comment by riteshatsencha** [comment]
Yes. Trying to debug. BTW, the index.js I am referring to is in node-fetch module.

**Comment by isidorn** [comment]
Can you please provide nice reproducable steps? Thank you

**Comment by riteshatsencha** [comment]
Actually, seems like an issue at my end. I will be closing this thread. Issue is with node-fetch index.js not receiving a proper url. 

Thank you.
