### ISSUE TITLE
RTL word wrap broken

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#126618]
Issue Type: <b>Bug</b>

I entered text in Hebrew. The text was a long line and so I enabled word wrap, but it was not wrapping correctly. Some of the text is hidden outside the right margin.

First analysis: It seems like the hebrew font is slightly wider, but the wrapping is occuring at the point where the same number of characters in english would have wrapped.

To reproduce, copy this text into a new document and enable word wrap:

```
aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa
אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא אאאאא
```

This text is just 20 groups of the same 5 characters in English and then in Hebrew, to simplify counting.

Now try resizing the window to different sizes and you should see the wrapping issue. If you are unsure just count how many groups and how many characters in a group are visible.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.01GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bmews7748/homes/baruchb/work/main/ME.Develop --crash-reporter-id 6949b6e9-d952-4b8f-a136-284374926c80|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 1599)|
|Memory (System)|15.54GB (0.18GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
ini-for-vscode|Dav|0.0.4
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.5.1
vscode-test-explorer|hbe|2.20.4
vscode-autohotkey-plus-plus|mar|2.8.1
vscode-catch2-test-adapter|mat|3.6.26
git-graph|mhu|1.30.0
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.4.1
hexeditor|ms-|1.7.0
test-adapter-converter|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.3.3
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
vt100-syntax-highlighting|Tob|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674
vscextlang:30322306
binariesv615:30323119

```

</details>

![image](https://user-images.githubusercontent.com/1149432/122460694-1dc1b480-cfbb-11eb-8621-b9a2c0669f11.png)

![image](https://user-images.githubusercontent.com/1149432/122460831-48ac0880-cfbb-11eb-87d9-18d446b855d7.png)

**Comment by alexdima** [comment]
@BMBurstein Please configure `"editor.wrappingStrategy": "advanced"`. The default wrapping algorithm is quite fast and can deal with very large files, but it is fast because it assumes that all characters are monospace. The advanced wrapping algorithm delegates wrapping point computation to the browser, but is a lot slower.
