### ISSUE TITLE
Frozen screen on Redhat 7.7 using version 1.55.2

### ISSUE THREAD

**Issue by jgaer** [microsoft/vscode#126601]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.55.2 and 1.5.7
- OS Version: Redhat 64 bit 7.7

Steps to Reproduce:

1.install vscode from rpm
2.code --disable-extensions
3. vscode window opens, but no operations on the screen work. Can not expand files, can not select from menus.

Note do not have this problem with version vscode 1.5.2

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by jgaer** [comment]
tried running with the code --disable-gpu option and no change. When I try to close the window I get a message visual studio code is not responding. (not unique to running with --disable-gpu). Have also tried running with extensions disabled. I had read on stack trace that as of 1.53 centos 7 was not supported. I was wondering if this also applies to redhat.

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/115784
