### ISSUE TITLE
Rounded corners on jupyter notebooks (and VS code in general)

### ISSUE THREAD

**Issue by pietrodantuono** [microsoft/vscode#126698]
As Microsoft seems fast going back to rounded corners (as it was until Windows 7), a nice-to-have feature would certainly be introducing them in VSCode as well! mean, notebook cells/notification area/settings/etc...

**Comment by DonJayamanne** [comment]
Closing this feature as not planned due to lack of upvotes.

**Comment by pietrodantuono** [comment]
Sad that this issue has been closed since, for instance, fabric notebooks, implement this simple functionality and they look way better integrated in the new Microsoft look and feel philosophy.
