### ISSUE TITLE
[Test API] A newly added test will be triggered again in auto-run mode

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#126653]
Version: 1.58.0-insider (user setup)
Commit: a81fff00c9dab105800118fcf8b044cd84620419
Date: 2021-06-17T05:17:34.858Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. In `test-provider-sample` project, in `run()` method of the `TestCase` class, change the else block to:
```ts
if (actual === this.expected) {
  ...
} else {
  const child1 = vscode.test.createTestItem<TestCase>({
    id: `fakeTest/${this.item.uri!.toString()}/${this.item.label}#1`,
    label: this.item.label,
    uri: this.item.uri!,
  });
  child1.range = this.item.range;
  child1.runnable = false;
  child1.debuggable = false;
  child1.status = vscode.TestItemStatus.Resolved;
  this.item.addChild(child1);
  const message = vscode.TestMessage.diff(`Expected ${this.item.label}`, String(this.expected), String(actual));
  message.location = new vscode.Location(this.item.uri!, this.item.range!);
  options.appendMessage(child1, message);
  options.setState(child1, vscode.TestResultState.Failed, duration);
}
```
_This is to imitate the case that when running parameterized tests, a test method will be triggered multiple times with different parameters during execution. So each invocation will be a added as a child of the test method during the execution._
2. Turn on the autorun mode
3. `runTests()` will be triggered twice, for the second time, only the newly added test item `child1` is contained in the tests array.

There are two reasons why I think the second `runTests()` should not be triggered:
1. The test state of `child1` has just been set for the last run
2. The test item `child1` is not runnable neither debuggable

// cc @connor4312

**Comment by connor4312** [comment]
This is actually expected _if_ child1 doesn't have a "state" set. To the editor it's indistinguishable to if the user created a new test. If you call `options.setState(child1, vscode.TestResultState.Passed)`, for example, then it won't happen. I think this should be fine for your scenario, since when running tests you wouldn't leave the child in an unset state.

There's actually a race with this where creating and then immediately setting the state without changing it again can requeue it, but it'll be fixed in the next Insiders.

Let me know if that makes sense to you

**Comment by jdneo** [comment]
Makes sense. If a test item doesn't have a state set, it should be requeued. Otherwise, if it's just set the state, then it should not.

**Comment by connor4312** [comment]
Okay, thanks.

Verifier, please confirm the fix for this:

> There's actually a race with this where creating and then immediately setting the state without changing it again can requeue it, but it'll be fixed in the next Insiders.

**Comment by TylerLeonhardt** [comment]
@jdneo would you like to verify that this is fixed?
