### ISSUE TITLE
Terminal crashes on startup

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12663]
OS X

Run vscode out of source
Have the terminal open
Notice exceptions in console

I do not get these exceptions when running the bulit vscode version 
<img width="857" alt="screen shot 2016-09-26 at 19 42 21" src="https://cloud.githubusercontent.com/assets/1926584/18845278/6266ca7a-8421-11e6-8161-6489e9a920a6.png">

**Comment by Tyriar** [comment]
Delete `./node_modules/xterm` and run `./scripts/npm.sh install`
