### ISSUE TITLE
Use Workspace Typescript causes settings to be ill-formatted

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12669]
- VSCode Version: 1.6 Insiders
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Open a TS project and receives this notification
   ![image](https://cloud.githubusercontent.com/assets/4033249/18844463/2d3f7210-83d2-11e6-85f6-06b3a80e1623.png)
   Then click "Use Workspace Typescript"
2. Diff for `settings.json`

![image](https://cloud.githubusercontent.com/assets/4033249/18844491/4ae130a6-83d2-11e6-9ca5-4c486338316a.png)

**Comment by octref** [comment]
@aeschli 

This still happens. Particularly any setting added right after a setting of list `[]` is ill-formatted.

**Comment by aeschli** [comment]
duplicate of #19136
