### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by PickaxeHit** [microsoft/vscode#126686]
> C:\Users\Windows\Documents\vscode>yarn watch
yarn run v1.22.10
$ npm-run-all -lp watch-client watch-extensions
[watch-client    ] $ node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js watch-client
[watch-extensions] $ node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js watch-extensions watch-extension-media
[watch-client    ] [22:58:13]
[watch-extensions] [22:58:13] Using gulpfile ~\Documents\vscode\gulpfile.js
[watch-client    ] Using gulpfile ~\Documents\vscode\gulpfile.js
[watch-client    ] [22:58:14]
[watch-extensions] [22:58:14] Starting 'watch-extensions'...
[watch-client    ] Starting 'watch-client'...
[watch-extensions] [22:58:14] Starting 'watch-extension-media'...
[watch-client    ] [22:58:14] Starting clean-out ...
[watch-extensions] [22:58:14] Starting clean-extension-configuration-editing-build ...
[watch-extensions] [22:58:14]
[watch-client    ] [22:58:14] Finished clean-out after 53 ms
[watch-extensions] Starting clean-extension-configuration-editing ...
[watch-client    ] [22:58:14] Starting watch-client ...
[watch-extensions] [22:58:14] Starting clean-extension-css-language-features-client ...
[watch-extensions] [22:58:14] Starting clean-extension-css-language-features-server ...
[watch-extensions] [22:58:14] Starting clean-extension-debug-auto-launch ...
[watch-extensions] [22:58:14] Starting clean-extension-debug-server-ready ...
[watch-extensions] [22:58:14] Starting clean-extension-emmet ...
[watch-extensions] [22:58:14] Starting clean-extension-extension-editing ...
[watch-extensions] [22:58:14] Starting clean-extension-git ...
[watch-extensions] [22:58:14] Starting clean-extension-github-authentication ...
[watch-extensions] [22:58:14] Starting clean-extension-github ...
[watch-extensions] [22:58:14] Starting clean-extension-grunt ...
[watch-extensions] [22:58:14] Starting clean-extension-gulp ...
[watch-extensions] [22:58:14] Starting clean-extension-html-language-features-client ...
[watch-extensions] [22:58:14] Starting clean-extension-html-language-features-server ...
[watch-extensions] [22:58:14] Starting clean-extension-image-preview ...
[watch-extensions] [22:58:14] Starting clean-extension-jake ...
[watch-extensions] [22:58:14] Starting clean-extension-json-language-features-client ...
[watch-extensions] [22:58:14] Starting clean-extension-json-language-features-server ...
[watch-extensions] [22:58:14] Starting clean-extension-markdown-language-features-preview-src ...
[watch-extensions] [22:58:14] Starting clean-extension-markdown-language-features ...
[watch-extensions] [22:58:14] Starting clean-extension-merge-conflict ...
[watch-extensions] [22:58:14] Starting clean-extension-microsoft-authentication ...
[watch-extensions] [22:58:14] Starting clean-extension-npm ...
[watch-extensions] [22:58:14] Starting clean-extension-php-language-features ...
[watch-extensions] [22:58:14] Starting clean-extension-search-result ...
[watch-extensions] [22:58:14] Starting clean-extension-simple-browser ...
[watch-extensions] [22:58:14] Starting clean-extension-testing-editor-contributions ...
[watch-extensions] [22:58:14] Starting clean-extension-typescript-language-features-test-workspace ...
[watch-extensions] [22:58:14] Starting clean-extension-typescript-language-features ...
[watch-extensions] [22:58:14] Starting clean-extension-vscode-api-tests ...
[watch-extensions] [22:58:14] Starting clean-extension-vscode-colorize-tests ...
[watch-extensions] [22:58:14] Starting clean-extension-vscode-custom-editor-tests ...
[watch-extensions] [22:58:14] Starting clean-extension-vscode-notebook-tests ...
[watch-extensions] [22:58:14] Starting clean-extension-vscode-test-resolver ...
[watch-extensions] [22:58:32] Finished clean-extension-configuration-editing-build after 18546 ms
[watch-extensions] [22:58:32] Starting watch-extension:configuration-editing-build ...
[watch-extensions] [22:58:42] Starting compilation extensions...
[watch-extensions] [22:58:42] Finished clean-extension-configuration-editing after 28182 ms
[watch-extensions] [22:58:42] Starting watch-extension:configuration-editing ...
[watch-extensions] [22:58:42] Finished clean-extension-css-language-features-client after 28459 ms
[watch-extensions] [22:58:42] Starting watch-extension:css-language-features-client ...
[watch-extensions] [22:58:42] Finished clean-extension-css-language-features-server after 28656 ms
[watch-extensions] [22:58:42] Starting watch-extension:css-language-features-server ...
[watch-extensions] [22:58:43] Finished clean-extension-debug-auto-launch after 28938 ms
[watch-extensions] [22:58:43] Starting watch-extension:debug-auto-launch ...
[watch-extensions] [22:58:43] Finished clean-extension-debug-server-ready after 29061 ms
[watch-extensions] [22:58:43] Starting watch-extension:debug-server-ready ...
[watch-extensions] [22:58:43] Finished clean-extension-emmet after 29180 ms
[watch-extensions] [22:58:43] Starting watch-extension:emmet ...
[watch-extensions] [22:58:43] Finished clean-extension-extension-editing after 29626 ms
[watch-extensions] [22:58:43] Starting watch-extension:extension-editing ...
[watch-extensions] [22:58:43] Finished clean-extension-git after 29776 ms
[watch-extensions] [22:58:43] Starting watch-extension:git ...
[watch-extensions] [22:58:44] Finished clean-extension-github-authentication after 30111 ms
[watch-extensions] [22:58:44] Starting watch-extension:github-authentication ...
[watch-extensions] [22:58:44] Finished clean-extension-github after 30276 ms
[watch-extensions] [22:58:44] Starting watch-extension:github ...
[watch-extensions] [22:58:44] Finished clean-extension-grunt after 30442 ms
[watch-extensions] [22:58:44] Starting watch-extension:grunt ...
[watch-extensions] [22:58:44] Finished clean-extension-gulp after 30553 ms
[watch-extensions] [22:58:44] Starting watch-extension:gulp ...
[watch-extensions] [22:58:44] Finished clean-extension-html-language-features-client after 30689 ms
[watch-extensions] [22:58:44] Starting watch-extension:html-language-features-client ...
[watch-extensions] [22:58:45] Finished clean-extension-html-language-features-server after 30981 ms
[watch-extensions] [22:58:45] Starting watch-extension:html-language-features-server ...
[watch-extensions] [22:58:45] Finished clean-extension-image-preview after 31333 ms
[watch-extensions] [22:58:45] Starting watch-extension:image-preview ...
[watch-extensions] [22:58:45] Finished clean-extension-jake after 31466 ms
[watch-extensions] [22:58:45] Starting watch-extension:jake ...
[watch-extensions] [22:58:45] Finished clean-extension-json-language-features-client after 31588 ms
[watch-extensions] [22:58:45] Starting watch-extension:json-language-features-client ...
[watch-extensions] [22:58:46] Finished clean-extension-json-language-features-server after 31810 ms
[watch-extensions] [22:58:46] Starting watch-extension:json-language-features-server ...
[watch-extensions] [22:58:46] Finished clean-extension-markdown-language-features-preview-src after 31970 ms
[watch-extensions] [22:58:46] Starting watch-extension:markdown-language-features-preview-src ...
[watch-extensions] [22:58:46] Finished clean-extension-markdown-language-features after 32107 ms
[watch-extensions] [22:58:46] Starting watch-extension:markdown-language-features ...
[watch-extensions] [22:58:46] Finished clean-extension-merge-conflict after 32447 ms
[watch-extensions] [22:58:46] Starting watch-extension:merge-conflict ...
[watch-extensions] [22:58:46] Finished clean-extension-microsoft-authentication after 32665 ms
[watch-extensions] [22:58:46] Starting watch-extension:microsoft-authentication ...
[watch-extensions] [22:58:47] Finished clean-extension-npm after 32853 ms
[watch-extensions] [22:58:47] Starting watch-extension:npm ...
[watch-extensions] [22:58:47] Finished clean-extension-php-language-features after 33061 ms
[watch-extensions] [22:58:47] Starting watch-extension:php-language-features ...
[watch-extensions] [22:58:47] Finished clean-extension-search-result after 33220 ms
[watch-extensions] [22:58:47] Starting watch-extension:search-result ...
[watch-extensions] [22:58:47] Finished clean-extension-simple-browser after 33344 ms
[watch-extensions] [22:58:47] Starting watch-extension:simple-browser ...
[watch-extensions] [22:58:47] Finished clean-extension-testing-editor-contributions after 33502 ms
[watch-extensions] [22:58:47] Starting watch-extension:testing-editor-contributions ...
[watch-extensions] [22:58:47] Finished clean-extension-typescript-language-features-test-workspace after 33656 ms
[watch-extensions] [22:58:47] Starting watch-extension:typescript-language-features-test-workspace ...
[watch-extensions] [22:58:48] Finished clean-extension-typescript-language-features after 33789 ms
[watch-extensions] [22:58:48] Starting watch-extension:typescript-language-features ...
[watch-extensions] [22:58:48] Finished clean-extension-vscode-api-tests after 34621 ms
[watch-extensions] [22:58:48] Starting watch-extension:vscode-api-tests ...
[watch-extensions] [22:58:49] Finished clean-extension-vscode-colorize-tests after 34879 ms
[watch-extensions] [22:58:49] Starting watch-extension:vscode-colorize-tests ...
[watch-extensions] [22:58:49] Finished clean-extension-vscode-custom-editor-tests after 34984 ms
[watch-extensions] [22:58:49] Starting watch-extension:vscode-custom-editor-tests ...
[watch-extensions] [22:58:49] Finished clean-extension-vscode-notebook-tests after 35097 ms
[watch-extensions] [22:58:49] Starting watch-extension:vscode-notebook-tests ...
[watch-extensions] [22:58:49] Finished clean-extension-vscode-test-resolver after 35244 ms
[watch-extensions] [22:58:49] Starting watch-extension:vscode-test-resolver ...
[watch-client    ] [22:59:30] Starting compilation...
[watch-client    ] error Command failed with exit code 3221226505.
[watch-client    ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "watch-client" exited with 3221226505.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> C:\Users\Windows\Documents\vscode>

My system is Windows10 x64, and the node's version is 12.22.1
Should I use the admin account to build it?

**Comment by joaomoreno** [comment]
How much RAM do you have?
