### ISSUE TITLE
'osx' is used as the name for the Mac platform settings, should we consider using 'mac' or 'macos'

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12666]
'osx' is used in settings and schema:
terminal.external.osxExec
terminal.integrated.shell.osx
launch.json
tasks.json
With the Apple switch to "macOS" and the release of Sierra 10.12, should we consider using 'mac' instead and deprecating 'osx' after some number of releases?

**Comment by isidorn** [comment]
The deprication would be painful since we would have to support both. So -1 on my side
Adding @weinand to get his opinion

**Comment by weinand** [comment]
-1
