### ISSUE TITLE
if delete file op fails, will refuse to exit

### ISSUE THREAD

**Issue by johngrabner** [microsoft/vscode#126684]
Issue Type: <b>Bug</b>

Using visual studio code remote ssh.
Delete a massive file in the left panel.
Do not know why, but delete fails and code keeps trying.
If I try to exist code, it give warning, but if i close anyway,
it ignors me.
Only way to cleanup is the task manager kill code

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-73-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (45.69GB free)|
|Process Argv|--crash-reporter-id 4c66366a-4560-4371-be80-7236c872b55f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: docker_23_designare|
|OS|Linux x64 5.4.0-73-generic|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor (64 x 2194)|
|Memory (System)|251.65GB (218.85GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
vscextlangct:30322307
binariesv615cf:30323120
vsccppwtct:30322537

```

</details>

![bug code 1](https://user-images.githubusercontent.com/8209285/122579567-a7549f00-d01a-11eb-9353-bfce3e40ba40.JPG)
![bug code 3](https://user-images.githubusercontent.com/8209285/122579569-a7ed3580-d01a-11eb-9659-3683575a3401.JPG)
![bug code 2](https://user-images.githubusercontent.com/8209285/122579570-a7ed3580-d01a-11eb-8f33-810c0612ec99.JPG)

**Comment by isidorn** [comment]
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
