### ISSUE TITLE
Markdown preview sometimes brings jumping by markdown.previewScripts contribution

### ISSUE THREAD

**Issue by yhatt** [microsoft/vscode#126640]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 / 1.58.0-insider
- OS Version: Darwin arm64 20.5.0 (macOS Big Sur 11.4)

Steps to Reproduce:

1. Make the extension with `markdown.previewScripts` contributed point to be brought reflow
   ```javascript
   document.head.insertAdjacentHTML(
     'beforeend',
     `<style>p{font-size:30px !important;}</style>`
   )
   ```
2. Open preview with simple Markdown like this:
   ```markdown
   0000000000
   
   1111111111
   
   2222222222
   
   3333333333
   
   4444444444
   
   5555555555
   
   6666666666
   
   7777777777
   
   8888888888
   
   9999999999
   ```
3. Scroll into the middle of Markdown (`5555555555`) with enabled scroll sync
4. Edit Markdown by removing any character with <kbd>Backspace</kbd>
5. _Sometimes_ bring scroll jumping

https://user-images.githubusercontent.com/3993388/122497806-f7d2f900-d028-11eb-966c-44e8538f69a2.mov

## Details

If brought reflow due to change of DOM or style by contributed preview script, Markdown preview may update with the wrong scroll position by editing. Probably it is same as #69467, and I've recieved the bug report to my extension in marp-team/marp-vscode#248.

The scroll stabilizer provided by markdown-language-features is working in the same context of other contributed scripts. They are injected by `<script async>` so the execution order of them is not predictable. 

It works correctly if the stabilizer was executed after other contributed scripts. If not, may be stabilized with the wrong position because it has not calculated based on the final result of preview.

Several possible solutions are following:

- Delay execution timing of the stabilization logic to after executed other contributed scripts.
- Add option to allow synchronized script execution to the extension that may bring reflow.

Related?: #119370

**Comment by mjbvz** [comment]
Should be improved in simple cases by 8f672cac62d52f47439a4afc014c63bd8aba97bd

Not possible to fix all cases though since this api is intentionally very open ended in the types of modifications is permits
