### ISSUE TITLE
VS Code for Mac: composer.json schema validation fails; URL incorrect

### ISSUE THREAD

**Issue by wp4nuv** [microsoft/vscode#126699]
Issue Type: <b>Bug</b>

When creating a new composer.json file, the JSON extension fails to validate with the following message:
{
	"resource": "/Users/pedro/Projects/sql-updates/composer.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'http://json.schemastore.org/composer': Unable to load schema from 'http://json.schemastore.org/composer': Request vscode/content failed unexpectedly without providing any details.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
Navigating to that URL directly shows the following error:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

The schema validates correctly per "composer validate" command.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.89GB free)|
|Process Argv|--crash-reporter-id fa700cc6-3cb1-4c7a-a5df-dc68ab6ad5eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
phptools-vscode|DEV|1.4.6762
gitlens|eam|11.5.1
vscode-test-explorer|hbe|2.20.4
composer|ika|0.7.1
syntax-project-pbxproj|mar|0.1.3
file-downloader|min|1.0.11
mindaro|min|1.0.120210615
vscode-docker|ms-|1.13.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
remote-containers|ms-|0.183.0
cpptools|ms-|1.4.1
test-adapter-converter|ms-|0.0.10
vscode-yaml|red|0.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615cf:30323120

```

</details>

**Comment by aeschli** [comment]
The schema URL comes from the composer extension. I created https://github.com/ikappas/vscode-composer/issues/19
