### ISSUE TITLE
background extension is not uninstallable

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#12661]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Install the "background" extension.
2. Uninstall it.
3. Restart VS Code.

Bug: The background is still modified from the background extensions, even though the settings are gone and it says the extension is uninstalled. It seems like the extensions install makes some permanent change that isn't reversible.

**Comment by joaomoreno** [comment]
The `background` extension **patches** VS Code. This is not supported.
