### ISSUE TITLE
无法打开“vs_code_welcome_page”

### ISSUE THREAD

**Issue by Xiaolong375** [microsoft/vscode#126638]
Issue Type: <b>Bug</b>

无法打开“vs_code_welcome_page”: Unable to resolve resource walkThrough:/e%3A/VS%20Code/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D。

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Thanks for reporting, do you have `editorAssociations: {'*': 'default'}` set anywhere in your settings by chance?
