### ISSUE TITLE
rg.exe CPU 100%

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#126634]
Issue Type: <b>Bug</b>

I've tried what found, but didn't find a way to find what causes this .

in ``Output\Log (Window)`` i have this non-stop all over opened folders

![Screenshot](https://user-images.githubusercontent.com/13949704/122490851-6cc71400-cfd2-11eb-8838-5d564a6c3254.png)

i don't like this too, but it happens even without rg.exe process/-es and with low CPU load .

Other ``Output\Log (..)`` doesn't seem to have anything useful .

I can't work without extensions, and it happens occasionally, so bisect doesn't help .

Next after #43847, #56328, #55649 .

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
This process is doing a search. It might be a search that you started, or that an extension started. See if any tips on this page help https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by ananiy** [comment]
![image](https://user-images.githubusercontent.com/33290601/122524138-5d83ad00-d04a-11eb-85b9-1e9647ec2ea6.png)

----
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
----

after upgrade to 1.57.1

**Comment by omar-zakaria** [comment]
I've had the same issue this morning. 
Fixed after disabling the extension :

> Name: Ember Cli in Visual Studio Code
> Id: embertooling.vsc-ember-cli
> Version: 0.3.3

vscode: version 1.57.1
OS: windows 10 pro build 19041.985

**Comment by irvnriir** [comment]
@roblourens i never did run search when this happened .

**Comment by irvnriir** [comment]
For me it also seem to be from 1.57, but i'm not sure .

**Comment by roblourens** [comment]
This process is doing a search. It might be a search that you started, or that an extension started. See if any tips on this page help https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by irvnriir** [comment]
@roblourens I've posted this in the Issue's description . I can't post the whole log because the issue happens occasionally, but am pretty sure that there were none `SearchService#search` . Next time i'll try Debug Log Level .

**Comment by roblourens** [comment]
You need to use "trace" log level

**Comment by irvnriir** [comment]
@roblourens
![Screenshot](https://user-images.githubusercontent.com/13949704/122490851-6cc71400-cfd2-11eb-8838-5d564a6c3254.png)
> there were none `SearchService#search`

**Comment by roblourens** [comment]
Are you in a remote window?  It will be there somewhere. Possibly earlier or it could have been triggered before you bumped up the log level.

**Comment by irvnriir** [comment]
Possibly `git-graph.maxDepthOfRepoSearch` from 0 to 1 helped .

**Comment by irvnriir** [comment]
N, this still happens . I've found
```
[2021-07-02 23:02:56.614] [renderer1] [trace] [File Watcher (nsfw)]  >> normalized [CHANGED] 
[2021-07-02 23:02:56.618] [renderer1] [trace] SearchService#search: 55817ms
[2021-07-02 23:02:57.039] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] c:\Users\<<..>>\AppData\Roaming\Code\User\globalStorage
[2021-07-02 23:02:57.345] [renderer1] [trace] [text file model] dispose() git:/<<.md file which i've interacted with [1]>>.git?{"path":"<<[1]>>","ref":""}
[2021-07-02 23:02:57.345] [renderer1] [trace] [backup tracker] discarding backup git:/<<[1]>>.git?{"path":"<<[1]>>","ref":""} 
[2021-07-02 23:02:57.347] [renderer1] [trace] [File Watcher (nsfw)] [CHANGED] c:\Users\admin\AppData\Roaming\Code\Backups\ea6724e88d8365b76339a1786612f4ce\file\-7e9918f4
```
