### ISSUE TITLE
String autocomplete issue with dots

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#12667]
- VSCode Version: Code - Insiders 1.6.0-insider (be5e8d5733c1c012d7e3a6c7e049b59d67c13978, 2016-09-26T06:05:01.421Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Trying to change `../Error` to `../../Error` (by typing quickly `..`) - it puts one dot and autocompletes with first intellisense word
2. 
![cu5bb2zvvm](https://cloud.githubusercontent.com/assets/1723815/18846813/a77807ea-83f5-11e6-8fba-277b3d705bee.gif)

**Comment by joaomoreno** [comment]
`.core` should not be a suggestion in there.

**Comment by wallverb** [comment]
`core` is one of my folders - I think that it just shouldn't autocomplete when pressing dots (in path)

**Comment by wallverb** [comment]
Just an update - that this is an issue with strings in general (and has nothing to do with path)

Here I really wanted to type `c.c.c.c.c.c.c.c.c.c.c.c`string:

![rz2sojq4ca](https://cloud.githubusercontent.com/assets/1723815/18917858/fcd94a38-8566-11e6-8974-7f44143d7629.gif)

PS. Thats in `TS` file
Thanks

**Comment by waderyan** [comment]
@wallverb thank you for opening this issue. 

I'm not seeing the same behavior. I created a blank `.ts` file and started typing. Can you share a minimal repo where you are seeing this behavior? Maybe there is something going on with your setup. 

![stringdotbugs](https://cloud.githubusercontent.com/assets/2449568/18934699/1627386e-8590-11e6-930f-8367513fa37c.gif)

**Comment by DanielRosenwasser** [comment]
This is a mixture of issues.

```ts
var x: {
    a: {
        b: {
            c: 10;
        }
    }
}
x./*$*/
```

`.` is both a completion commit character and a completion prompt character.

So above, if you hit `.` twice it'll prompt completion and then it'll complete to `x.a.`

Recently TypeScript started giving you completions for paths. In a path, `..` is a valid sequence to go up one level, however `..` will prompt and immediately complete on the first entry you have. Clearly `.` shouldn't be a commit character here, so there needs to be some indicator for whether a completion entry should be committed on. That way editors could adjust their commit behavior (like with `isNewIdentifierLocation`).

**Comment by waderyan** [comment]
@DanielRosenwasser thank you for your comments. Why am I not seeing this in my case?

**Comment by DanielRosenwasser** [comment]
You're not seeing the issue because you're dotting in an import specifier (the string in an `import` statement).

**Comment by waderyan** [comment]
My example is a response to OP's comment

> Just an update - that this is an issue with strings in general

It seems he was seeing the issue with strings in general. His animation shows the issue happening with a string in addition to the import statement. 

I am also not seeing the issue in an import statement.

**Comment by DanielRosenwasser** [comment]
That seems related to a bug in the language service

![image](https://cloud.githubusercontent.com/assets/972891/18935814/618cc114-8597-11e6-8781-d0d9d247e0b6.png)

**Comment by wallverb** [comment]
yea - initially i thought it was related to path, but is more generally

here was my repro:

```ts
interface Test {
    aTest: string
}

const a : Test = {
    aTest: ''
}
```

![ngm3f5a9gs](https://cloud.githubusercontent.com/assets/1723815/18935891/230a9e42-85b1-11e6-9a5b-7ade5e30ffa9.gif)

**Comment by DanielRosenwasser** [comment]
I opened up https://github.com/Microsoft/TypeScript/issues/11232 for the other issue.

**Comment by waderyan** [comment]
@wallverb thank you for the simple example. I was able to recreate. 

@dbaeumer this is a good candidate to fix on our end, I believe. 

See @DanielRosenwasser's [comment](https://github.com/Microsoft/vscode/issues/12667#issuecomment-250323318) to clarify the issue above.

**Comment by waderyan** [comment]
Looks like I found a [duplicate](https://github.com/Microsoft/TypeScript/issues/11044).

**Comment by Seikho** [comment]
Is this a VSCode issue or a TypeScript issue? The duplicate refers to a TS issue.

**Comment by waderyan** [comment]
@Seikho TS provides the JavaScript language service for VS Code, so the duplicate is valid despite the different repos. This issue would have been migrated to TS once we determined it needed to be fixed.
