### ISSUE TITLE
Untrust all subfolders in a folder

### ISSUE THREAD

**Issue by ravshansbox** [microsoft/vscode#126670]
Issue Type: <b>Feature Request</b>

We have option to trust all subfolders in a folder (there is a checkbox 'trust all' when trusting a subfolder), but we do not have an option to untrust all subfolders in a folder. I'd recommend to rename that checkbox as "All" and save the action (trust/untrust) for all subfolders.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: Yes

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/126311
