### ISSUE TITLE
Auto Import don't work properly on 1.57

### ISSUE THREAD

**Issue by GenAmnesia** [microsoft/vscode#126602]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57
- OS Version: Windows 10 Pro 20H2

Steps to Reproduce:

1. Install 1.57
2. Try to import some Material-UI module in a tsx or jsx file
3. It don't display the proper auto import suggestion
4. Install 1.56
5. It works as intended again

**Comment by sgcuber24** [comment]
The same issue is persistent for custom components too.

**Comment by Besuf** [comment]
Any news guys? or should we rollback to previous version of vscode

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/44657
