### ISSUE TITLE
Messed up with Keyboard map in vscode

### ISSUE THREAD

**Issue by abadeus-g** [microsoft/vscode#126683]
Issue Type: <b>Bug</b>

Shortcuts as ctrl+a/ctrl+c/ctrl+v are not working correctly,when i tap them instead of selecting all,copying or paste,something else happened,i tried to change my own keyboard map,but nothing changed but when i change editor,shortcuts works fine

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.10.0-6parrot1-amd64
Restricted Mode: No

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Ctrl+A`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by abadeus-g** [comment]
Hi thanks for answering me
After trying your instructions i noticed that VS Code detects something differents from what i tapped,after a bit research i find out the source of my problem.
It was **Vim Extension** which was causing this trouble.After uninstalling it 
Everything looks fine for now...!!!

PS:: I don't know why it's was the source of the problem but glad to find the solution

Thanks for your instructions  @alexdima
