### ISSUE TITLE
[Test API] `vscode.TestRun.setState` not respect the request scope

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#126756]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
```
Version: 1.58.0-insider (Universal)
Commit: 7dea6d7402b55671410a129661cad24b55aed9f4
Date: 2021-06-18T13:57:55.970Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```
- OS Version: macOS 11.4

---

While testing the Test API, bumped into this issue that `vscode.TestRun.setState` did not ignore the update for items outside of the request item branch. 

According to the API doc in vscode.proposed.d.ts:
```
                /**
		 * Updates the state of the test in the run. Calling with method with nodes
		 * outside the {@link TestRunRequest.tests} or in the
		 * {@link TestRunRequest.exclude} array will no-op.
		 *
		 * @param test The test to update
		 * @param state The state to assign to the test
		 * @param duration Optionally sets how long the test took to run, in milliseconds
		 */
		setState(test: TestItem<T>, state: TestResultState, duration?: number): void;
```

For example, a test item tree like below, if I run the test-item 'B', would expect only 'B' and 'C' could be updated, even if I call the setState method for every item in the tree... However, in reality, looks like every item did get updated.

```
A - B - C
|
  - D
```
Not sure if this is a bug? the API documentation is wrong? or maybe I misinterpreted the doc?

Steps to Reproduce:

1. create a test item tree like above
2. then run test for item 'B'
3. update every item in the `runTest` method
4. see all items state changed. (while expecting only B and C changed)

**Comment by connor4312** [comment]
Yea, the docs need updating. We allow this since the process of running tests might result in discovery of previously-unknown tests

**Comment by connor4312** [comment]
Actually, with the new API changes (https://github.com/microsoft/vscode/issues/122208#issuecomment-865391103) we can now enforce this, so I'll do so unless I hear any complains.

**Comment by connectdotz** [comment]
I assume the enforcement does allow any item along the "tree-branch" to be updated, i.e. the item's children as well as its parent/grand-parent items?

**Comment by connor4312** [comment]
It does not allow parents of the item to be updated, only the item and its children

**Comment by connectdotz** [comment]
Hmmm... Why not? It's most certainly the parent state would change if the children have changed, right? You are already aggregate them probably but maybe some provider would like to use its own aggregation logic so needs to update the parent itself...

Just a thought, if not too difficult, would be nice not to exclude that use case.

**Comment by connor4312** [comment]
Yea, the general idea is to let the editor do the state "aggregation" (called state computation internally). If there are requests for this I'm fine opening it up.

**Comment by connectdotz** [comment]
ok, that's fair.

**Comment by TylerLeonhardt** [comment]
@connectdotz can you verify that this is fixed for you?
