### ISSUE TITLE
Application crash upon removing emoji

### ISSUE THREAD

**Issue by dkondratovych** [Microsoft/vscode#12677]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Open *.go file
2. Go to Edit -> Emoji $ Symbol 
3. Choose any emoji
4. Delete emoji from the file using delete button

**Comment by alexandrudima** [comment]
This has been fixed in 1.6.x

**Comment by alexandrudima** [comment]
See #12537 #12343 #12329
