### ISSUE TITLE
Indicate why a empty window restores from backups if they cannot restore

### ISSUE THREAD

**Issue by rxngui** [microsoft/vscode#126725]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1 (user setup)
- OS Version: WIN 10 version 21h1, Compilation: 19043.1052

Steps to Reproduce:

1. Every time I open it the vscode or open a new window with right click, it opens 10 or more empty windows with the last opened.
2. I need a resolution please, this is annoying and discouraging me from using this editor.

**Comment by rxngui** [comment]
![vscode-multiple-windows-bug](https://user-images.githubusercontent.com/54865573/122631258-ed544600-d0a0-11eb-8a66-4cb3d565a16f.gif)
Follow the gif and understand my problem

**Comment by bpasero** [comment]
What is the contents of these windows? And closing them one by one would always restore them?

**Comment by rxngui** [comment]
> What is the contents of these windows? And closing them one by one would always restore them?

The contents of one window are the last open workspace, and the other nine windows are all empty. And after closing all windows, when I try to open the editor again the same ten windows open again.

**Comment by bpasero** [comment]
Are there maybe dirty files in them that restore? Or do the empty windows somewhere read "Untitled Workspace" in explorer or title?

**Comment by rxngui** [comment]
There is no junk being restored in the windows, they all open as "Untitled workspace" or no title in the window title or in the vscode file explorer. As in the gif below:
![recording_vscode_bug_multiple_windows_opne](https://user-images.githubusercontent.com/54865573/122653733-0d294f80-d11d-11eb-845e-164c3440e5b9.gif)

**Comment by bpasero** [comment]
@rxngui in one of those empty windows, can you:
* hit `Ctrl+Shift+P`
* execute the `Developer: Log Working Copies` command
* open dev tools (from the Help menu)
* click on `Console` if not already opened
* copy the output

It is possibly looking somewhat like this:

```
INFO 
[Working Copies]
<none>

[Backups]
untitled:Untitled-1?typeId=textAreaWorkingCopy (typeId: textAreaWorkingCopy)
```

**Comment by rxngui** [comment]
My console its this:
![image](https://user-images.githubusercontent.com/54865573/122677475-c852f680-d1b8-11eb-859b-ac93220f5190.png)


My output its this:

```
[Working Copies]
<none>

[Backups]
vsls:/admin/classes/classUpload.php (typeId: <no typeId>)
```

**Comment by rxngui** [comment]
And what can i do now?

**Comment by bpasero** [comment]
@rxngui do you recall having had installed a extension (possibly PHP related?) that would provide a custom editor where you maybe left dirty changes?

Bottom line: this indicates there is a backup of a custom editor that we enforce to restore from a previous session. 

I will see if I can make the experience better, e.g. show a notification when the extension is no longer installed.

As a last resort, you can go into `%APPDATA%\User\` and delete the `Backups` folder. CAUTION: if you have any other dirty or untitled files, they would be gone then.

**Comment by rxngui** [comment]
I remember installing a PHP related extension, but it was in another vscode installation. But I just deleted the Backups folder and everything is back to normal. But I couldn't access it through `%APPDATA%\User\,` I searched in the file explorer on the disk that has VSCODE installed for `Backups`.
I accessed the folder and permanently deleted everything inside, just in case.
Thank you so much for supporting Benjamin Pasero, and congratulations on the incredible work you've been doing in supporting the users of this wonderful Editor. 😊

**Comment by KoreaGD** [comment]
> * hit `Ctrl+Shift+P`
> * execute the `Developer: Log Working Copies` command
> * open dev tools (from the Help menu)
> * click on `Console` if not already opened
> * copy the output
> 
> It is possibly looking somewhat like this:



My console returns this output:

```
 INFO 
[Working Copies]
<none>

[Backups]
<none>
```

**Comment by bpasero** [comment]
Hm, can you check for contents in that `Backup` folder or rename it to see if that helps?

**Comment by KoreaGD** [comment]
This works, thanks!

**Comment by abhishekadhikari23** [comment]
Removing **Backups** folder works.

**Comment by bpasero** [comment]
I pushed a fix for this to allow to close the empty window and have it not restore anymore and https://github.com/microsoft/vscode/issues/127163 is the real solution with nice UI.

**Comment by bpasero** [comment]
Anyone suffering from this issue, please try out our insiders release and report back if that helped:

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

You may see the empty windows open once more, but closing them should stop restoring them.
