### ISSUE TITLE
Less than 10.10 mac versions

### ISSUE THREAD

**Issue by nesmahamada** [microsoft/vscode#126766]
i have mac 10.9.5 and i can't download vscode if the version is less than 10.10
i hope you would make a 10.9.x version so that more people can use it.

**Comment by yume-chan** [comment]
Electron requires macOS 10.11 (https://www.electronjs.org/docs/tutorial/support#macos) so I don't think that's possible.

**Comment by deepak1556** [comment]
https://github.com/microsoft/vscode/issues/126766#issuecomment-864545670 is the reason we can't support it.
