### ISSUE TITLE
Support Other Markdown Variants  

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#12676]
Hello, it would be nice to be able to select support for other markdown in the viewer, other than common-markdown.

I personally would like to see: bitbucket markdown supported, they actually escape angle brackets < >, so it's nice keeping them in if you're just reading the text format.

In github markdown and common-markdown angle brackets must be escaped which can make for some ugly plain text reading. If not escaped, the text becomes invisible since it's incorrectly taken to be an html tag.

Thank you!

**Comment by mjbvz** [comment]
We've decided to standardize on commonmark for the built in markdown extension since it provides a good baseline experinace, but other extensions are free to change enhance markdown support and support other markdown variants.
