### ISSUE TITLE
[Bug] Can't open VSCode in admin mode using the installer

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#126721]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make `Code.exe` always run in admin mode.
2. Run the VSCode installer.
3. After finishing the installation, check the open VSCode option.
4. An error message shows up: "Can't execute Code.exe, CreateProcess failed, error code is 740, needs permission elevation".

**Comment by joaomoreno** [comment]
This is not supported with the User Setup, since that doesn't run with Admin rights, so it won't be able to spawn Code as Admin. You can probably achieve what you want to do if you use the System Setup.

**Comment by wenfangdu** [comment]
@joaomoreno The installer doesn't even have the privilege to prompt the user to choose to run as admin?

**Comment by joaomoreno** [comment]
That's also unsupported unfortunately.

Also note that running Code as an admin is actually a pretty bad idea for security reasons. There are usually workarounds for whatever it is that you're trying to do, other than running as Admin.

**Comment by wenfangdu** [comment]
@joaomoreno I'm curious how do you solve the problem in [this question](https://stackoverflow.com/q/37700536/7881859) without running Code.exe as admin?

**Comment by joaomoreno** [comment]
Option 2 of the correct answer (`More like Sudo`) is pretty good.
