### ISSUE TITLE
Setting description with \n characters breaks highlighting

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#12678]
- VSCode Version: 1.5.3
- OS Version: Windows

Steps to Reproduce:

1. Add a settings with a description that contains `\n`:

	```json
	"configuration": {
	    "title": "Test config",
	    "properties": {
	        "test.test": {
	            "description": "\nnewline"
	        }
	    }
	}
	```

2. Open the Default Settings page:

	![](http://i.imgur.com/sZX2ab6.png)

Possible solutions:

- strip `\n` from descriptions
- add `\t// ` before each `\n` character

**Comment by aeschli** [comment]
Why do you add '\n' to your description? I'd rather suggest you don't do that.
Won't fix.
