### ISSUE TITLE
VS Code Settings only opens to a JSON file every time

### ISSUE THREAD

**Issue by deberohprentice** [microsoft/vscode#126775]
Issue Type: <b>Bug</b>

Hello,
I can't open my settings.  It goes straight to a JSON file every time.  I don't know what to do with that JSON file when I want to add settings to my prettier extension.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.36GB free)|
|Process Argv|--crash-reporter-id 373fe651-b867-4590-bd82-e6ac35b00bbe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|12.36GB (11.40GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer-2|Coe|0.2.1
html-snippets|gey|0.2.3
vscode-picture|Jak|1.0.0
quickstart|lol|0.1.0
remote-wsl|ms-|0.56.5
html5-boilerplate|sid|1.1.1
ejs-snippets|Tao|0.1.0
html-snippets|abu|0.2.1
prettier-vscode|esb|6.4.0
html-snippets|gey|0.2.3
vscode-picture|Jak|1.0.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
mkanet-theme-v2|MKA|0.3.4
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
ejs-snippets|Tao|0.1.0
HTML5-extension-pack|wal|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615cf:30323120

```

</details>

**Comment by yume-chan** [comment]
Check your `"workbench.settings.editor"` setting is not set to `"json"`.

You can always open settings editor from <kbd>F1</kbd>, `Preferences: Open Settings (UI)`

**Comment by deberohprentice** [comment]
Good morning Simon.  I have enclosed a pic of what VS Code looks like when I open the settings editor using F1, Preferences: Open Settings or using the Command Palette.  I don't know how to get out of this and get to my settings.  Please help.  
dp
    On Sunday, June 20, 2021, 08:09:39 AM EDT, Simon Chan ***@***.***> wrote:  
 
 


Check your "workbench.settings.editor" setting is not set to "json".

You can always open settings editor from F1, Preferences: Open Settings (UI)

**Comment by yume-chan** [comment]
Note: GitHub comments doesn't include pictures from emails. Please upload using web interface or mobile Apps.

**Comment by deberohprentice** [comment]
"workbench.settings.editor" setting is set to "json".  Should I change it to something else?  Thanks.

**Comment by roblourens** [comment]
You can delete that setting to get the default behavior of opening the gui
