### ISSUE TITLE
Settings not available on new workspace folder.

### ISSUE THREAD

**Issue by jasonNXP** [microsoft/vscode#126757]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.57.0
- OS Version:Win10 2H20

Steps to Reproduce:

1. Create settings contribution - resource in package.json
2. Create a command in package.json
3. Use command to call vscode.workspace.updateWorkspaceFolders to add a new folder to the workspace from the extension. 
3. Check if the folder was added, if so, run vscode.workspace.getConfiguration
4. The settings object that is returned will display the proper key from package.json, but the value will not be populated.

There seems to be some race condition between the the new folder is added and when the configuration settings are updated. The settings data is also not available in the onDidChangeWorkspaceFolders event, as the value of the key is still empty. 

When do the configuration values get updated post new workspace folder addition?

**Comment by sandy081** [comment]
Can you please provide the code snippet that reproduces the issue?

**Comment by jasonNXP** [comment]
@sandy081 Here's the snippet that can illustrate the behavior that I'm seeing. Let me know if I need to create a new issue or if you can just open this one back up. The updateSetting() function, when called from a command will properly update the resource based setting. Calling the same command after adding the folder to the workspace does not work. 


```
function updateSetting(){
	vscode.workspace.getConfiguration('', vscode.workspace.workspaceFolders![vscode.workspace.workspaceFolders!.length-1].uri).update("settingsIssue.isAnIssue", "commandSetting", vscode.ConfigurationTarget.WorkspaceFolder);
}

function addfolder() {
	var settings;

	let newUri = vscode.Uri.file(path.join(__dirname,"..", "folder1"));

	if (vscode.workspace.updateWorkspaceFolders(vscode.workspace.workspaceFolders ? vscode.workspace.workspaceFolders.length : 0, null, { uri: newUri, name: "test_name"})) {
		if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0) {
            let newWorkspaceFolder = vscode.workspace.workspaceFolders[vscode.workspace.workspaceFolders.length];
			vscode.workspace.getConfiguration('', vscode.workspace.workspaceFolders![vscode.workspace.workspaceFolders!.length-1].uri).update("settingsIssue.isAnIssue", "newFolderSetting", vscode.ConfigurationTarget.WorkspaceFolder);
        }
	}
}
```

**Comment by jasonNXP** [comment]
@sandy081 It would appear as though the folder based configuration updates are only available once the onDidChangeWorkspaceFolders event fires. 

It would be nice if there was a way to pass data into the onDidChangeWorkspaceFolders event callback. I'm forced to hackily store off some temporary data and then read it in on the event fire.

**Comment by sandy081** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/73353
