### ISSUE TITLE
Settings API doesn't work if no .vscode folder exists

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12679]
Use the settings API on a fresh workspace (one that has no .vscode folder). Observer that the setting is not stored in a .vscode/settings.json file. The call is simply a NOOP.

**Comment by bpasero** [comment]
@dbaeumer to clarify, you are writing to `Target.WORKSPACE` in this case right?

**Comment by dbaeumer** [comment]
Yes.
