### ISSUE TITLE
"workspaceStorage" grows large with outdated project files

### ISSUE THREAD

**Issue by pearson** [microsoft/vscode#126706]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.57.0 (system setup)
- OS Version: Windows_NT x64 10.0.19042

Some data is stored by extensions into folders within `%APPDATA%\Code\User\workspaceStorage`. The problem is that some extensions (such as cpp-tools) can create large files, and these storage folders do not appear to get cleaned out.

In my case, having gone through many projects while experimenting with VSCode and cpp-tools, there are almost 100 directories (dating back to when VSCode was installed) in `%APPDATA%\Code\User\workspaceStorage`. Each of these directories contains an ~1GB cpp-tools `.BROWSE.VC.DB` file. That totals ~100GB of mainly unused data which would be significant on any system.

The issue appears to be a general VSCode issue given that other extensions can store data in `%APPDATA%\Code\User\workspaceStorage`. The cpp-tools example simply highlights the problem.

Steps to Reproduce:

1. Work with an extension that generates large files in `%APPDATA%\Code\User\workspaceStorage`, such as `cpp-tools`.
2. Examine the size of `%APPDATA%\Code\User\workspaceStorage`.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode/issues/32461
