### ISSUE TITLE
Command line `code .` not working

### ISSUE THREAD

**Issue by brunolm** [microsoft/vscode#126702]
Issue Type: <b>Bug</b>

`code-insiders .` is not opening the current dir. It opens the path to code insiders instead

VS Code version: Code - Insiders 1.58.0-insider (7dea6d7402b55671410a129661cad24b55aed9f4, 2021-06-18T13:58:43.903Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
tinypng|and|1.0.0
ng-template|Ang|12.0.5
path-intellisense|chr|2.3.0
regex|chr|0.4.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.16
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-pull-request-github|Git|0.27.1
gc-excelviewer|Gra|3.0.42
vscode-graphql|Gra|0.3.16
rest-client|hum|0.24.5
reg|ion|1.0.3
vscode-styled-components|jpo|1.6.4
classic-asp-html|jtj|0.1.2
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
compare-folders|mos|0.22.2
vscode-azureappservice|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.13.0
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.7.949309867
remote-containers|ms-|0.183.0
remote-wsl|ms-|0.58.1
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell|ms-|2021.5.1
powershell-preview|ms-|2021.6.1
vsliveshare|ms-|1.0.4419
debugger-for-chrome|msj|4.12.12
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-pg|mtx|0.2.0
vscode-paste-image|mus|1.0.4
language-liquid|nei|0.1.1
vetur|oct|0.34.1
material-icon-theme|PKi|4.7.0
ejs-language-support|Qas|0.0.1
format-code-action|roh|0.1.0
partial-diff|ryu|1.4.3
mdx|sil|0.1.0
addDocComments|ste|0.0.8
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.5.0
change-case|wma|1.0.0
vscode-caddyfile-syntax|zam|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by microhobby** [comment]
Same behavior here

**Comment by iaaanz** [comment]
here too

**Comment by microhobby** [comment]
Interesting that running it with `--verbose` shows:

```
[main 2021-06-19T04:44:01.536Z] Starting VS Code
[main 2021-06-19T04:44:01.537Z] from: c:\Users\<myuser>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app
[main 2021-06-19T04:44:01.538Z] args: {
  _: [
    'C:\\Users\\<myuser>\\AppData\\Local\\Programs\\Microsoft VS Code Insiders'
  ],
````

It's being started always from the `\\AppData\\Local\\Programs\\Microsoft VS Code Insiders`
