### ISSUE TITLE
can't load .png file in the remote connection

### ISSUE THREAD

**Issue by Kimtaehung123** [microsoft/vscode#126786]
click a .png file, blank,don't show the picture

**Comment by Kimtaehung123** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Image-preview is not working with Remote-SSH (#126135)](https://www.github.com/microsoft/vscode/issues/126135)

No. When I open the picture on my local computer, there is no problem.But when I connect to the remote Linux system, the problem shows.

**Comment by mjbvz** [comment]
Please fill in the issue template

/needsMoreInfo
