### ISSUE TITLE
Unable to paste into VS Code search when any extension-contributed Webview is visible

### ISSUE THREAD

**Issue by mhutchie** [microsoft/vscode#126716]
Unable to paste into Visual Studio Code search when any extension-contributed Webview is visible.

Users of my extension (Git Graph) have reported this to me (https://github.com/mhutchie/vscode-git-graph/issues/528), I've been able to replicate it, and observe that it occurs whenever any extension-contributed Webview is visible (it affects numerous extensions, not just Git Graph).

Does this issue occur when all extensions are disabled: N/A

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19042, Ubuntu 20.04

Steps to Reproduce (via Git Graph):
1. Install the "Git Graph" extension
2. Open a git repository
3. Copy some text to the clipboard (e.g. from a file in the vscode workspace)
4. Click into the Visual Studio Code search box - focus is obtained
5. Paste it in the search box (CTRL + V) - works OK
6. Clear the Visual Studio Code search box
7. Open the Git Graph View via the "Git Graph" Status Bar Item (which is an extension-contributed Webview)
8. Click into the Visual Studio Code search box - focus is obtained
9. Paste it in the search box (CTRL + V) - no longer works

Steps to Reproduce (via Edit csv):
1. Install the "Edit csv" extension
2. Copy some text to the clipboard (e.g. from a file in the vscode workspace)
3. Click into the Visual Studio Code search box - focus is obtained
4. Paste it in the search box (CTRL + V) - works OK
5. Clear the Visual Studio Code search box
6. Open a CSV File in the workspace
7. Click the "Edit csv" button in the top right of the editor (which opens an extension-contributed Webview)
8. Click into the Visual Studio Code search box - focus is obtained
9. Paste it in the search box (CTRL + V) - no longer works

Looping in @mjbvz

**Comment by lanxuexing** [comment]
Not that I know of, but I'm slightly relieved I'm not the only one experiencing this. 

### Issue
I also had the same problem, copy the image file name in image preview mode and couldn't paste it into the VS Code search

### VS Code Version Info
```vim
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0
```

Please help me with this, I'll be grateful.

**Comment by stephan-nordnes-eriksen** [comment]
I can confirm that I have the same issue. It also affects the `go to file` / `command pallet` (`ctrl+p` / `ctrl+shift+p`). It also seems that the issue can happen when the extension isn't in focus, but this seems a bit sporadic, and I can't predictably reproduce it however it seems that `ctrl+tab` influences it. Ubuntu 20.04

**Comment by mjbvz** [comment]
Same root cause as #126458
