### ISSUE TITLE
Python function decorator not collased properly when multiline string is in the arguments

### ISSUE THREAD

**Issue by developomp** [microsoft/vscode#126700]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Linux x64 5.10.42-1-MANJARO

Steps to Reproduce:

1. Open a python script with a multiline string in a function decorator.
example:
```python
@a_decorator(
    value="""Multiline
String
Here"""
)
def a_function():
    pass
```

2. collapse function decorator by pressing the `﹀` button

Expected result: the collapsed decorator should only show the decorator name
![expected](https://user-images.githubusercontent.com/40858122/122593710-052bca00-d0a1-11eb-9c1e-5dcf65bb0549.png)

Actual result: The collapsed decorator still shows multiline string
![collapsed](https://user-images.githubusercontent.com/40858122/122593705-04933380-d0a1-11eb-96be-3f7077d55ca9.png)

**Comment by aeschli** [comment]
Are you using the Python extension? Without the python extension, we only do indentation based folding.

The Python extension adds language aware folding.
Issues against the language aware folding need to be filed against  https://github.com/Microsoft/vscode-python/issues.
