### ISSUE TITLE
Startup Terminal profile is always powershell

### ISSUE THREAD

**Issue by miladashrafi** [microsoft/vscode#126732]
Issue Type: <b>Bug</b>

Startup Terminal profile is always powershell, but I setted the default profile to Command Prompt.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3402)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.11GB free)|
|Process Argv|--crash-reporter-id fd7b1dcb-e889-4906-84d8-3a3ac71aff35|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.0.5
emojisense|bie|0.8.0
xml|Dot|2.5.1
Angular2|joh|12.0.0
csharp|ms-|1.23.12
remote-wsl|ms-|0.56.5
LiveServer|rit|5.6.1
sass-indented|syl|1.8.16
Web-VSCode-Extensions|Syn|19.1.63
vscode-icons|vsc|11.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805:30301674
binariesv615:30321888

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
