### ISSUE TITLE
Cannot copy selected text in Markdown preview. Will always take the whole line despite the highlight.

### ISSUE THREAD

**Issue by hbina** [microsoft/vscode#126739]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Ubuntu 20.04 focal

```
~/git 
❯ screenfetch -n
 hbina@komputa
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.12.9-051209-generic
 Uptime: 1h 52m
 Packages: 2240
 Shell: bash 5.0.17
 Resolution: 1920x1080
 DE: GNOME 3.36.5
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11
 Disk: 150G / 475G (34%)
 CPU: AMD Ryzen 7 4800U with Radeon Graphics @ 16x 1.8GHz
 GPU: AMD/ATI
 RAM: 7029MiB / 31584MiB

~/git 
❯ code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```

Steps to Reproduce:

1. Open a view for Markdown file.
2. Attempt to copy/pase a C code to the terminal.

Please see video:

https://user-images.githubusercontent.com/6733660/122643858-bfc0d880-d144-11eb-8652-17bd051d0dab.mp4

**Comment by mjbvz** [comment]
Are you still seeing this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? I fixed a similar issue recently and no longer am able to reproduce this
