### ISSUE TITLE
Failed to support CUDA syntex

### ISSUE THREAD

**Issue by JiaRu2016** [microsoft/vscode#126768]
I have a file named foo.cu which is a cuda cpp file

![Screen Shot 2021-06-20 at 14 44 40](https://user-images.githubusercontent.com/17561508/122664791-11657380-d1d6-11eb-94e0-0f919fbf75a1.png)

 but It seems can not recognize the cuda styntex:
![Screen Shot 2021-06-20 at 14 46 58](https://user-images.githubusercontent.com/17561508/122664856-6dc89300-d1d6-11eb-94d3-187481b7a137.png)

the file is with `.cu` extension and did parsed as cuda cpp file:
![Screen Shot 2021-06-20 at 14 45 03](https://user-images.githubusercontent.com/17561508/122664872-83d65380-d1d6-11eb-9025-8c4e242db082.png)

Also the extentsion `Nsight Visual Studio Code Edition` is installed, and in `task.json` I'v write to use nvcc as compiler:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "echoCommand": true,
    "tasks": [
        {
            "label": "cuda_programming build and run",
            "type": "shell",
            "command": "/usr/local/cuda-10.2/bin/nvcc",
            "args": [
                "foo.cu",
                "-o",
                "out",
                "&&",
                "./out"
            ],
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceFolder}/cuda_programming"
            }
        }
    ]
}
```

- VS Code Version: Version: 1.57.0
- OS Version: Ubuntu 18.0.4

**Comment by alexr00** [comment]
Can you please share a copy/pasteable code snippet that reproduces this issue?

**Comment by JiaRu2016** [comment]
> Can you please share a copy/pasteable code snippet that reproduces this issue?

Here is a copy-pastable code, can be build and run succesfully using `nvcc foo.cu -o out`

```cu
#include <stdio.h>
#include <assert.h>

#define VECTOR_LENGTH 10000 
#define MAX_ERR 1e-4

__global__ void vector_add(float *out, float *a, float *b, int n) 
{
    for(int i = 0; i < n; i++)
    {
        out[i] = a[i] + b[i];
    }
}

int main()
{
    float *a, *b, *out;
    float *d_a, *d_b, *d_out; 

    // Allocate memory on CPU
    a = (float*)malloc(sizeof(float) * VECTOR_LENGTH);
    b = (float*)malloc(sizeof(float) * VECTOR_LENGTH);
    out = (float*)malloc(sizeof(float) * VECTOR_LENGTH);

    // data initializtion
    for(int i = 0; i < VECTOR_LENGTH; i++)
    {
        a[i] = 3.0f;
        b[i] = 0.14f;
    }

    // Allocate memory on GPU
    cudaMalloc((void**)&d_a, sizeof(float) * VECTOR_LENGTH);
    cudaMalloc((void**)&d_b, sizeof(float) * VECTOR_LENGTH);
    cudaMalloc((void**)&d_out, sizeof(float) * VECTOR_LENGTH);

    // copy operator to GPU
    cudaMemcpy(d_a, a, sizeof(float) * VECTOR_LENGTH, cudaMemcpyHostToDevice);
    cudaMemcpy(d_b, b, sizeof(float) * VECTOR_LENGTH, cudaMemcpyHostToDevice);

    // GPU do the work, CPU waits
    vector_add<<<1,1>>>(d_out, d_a, d_b, VECTOR_LENGTH);

    // Get results from the GPU
    cudaMemcpy(out, d_out, sizeof(float) * VECTOR_LENGTH, cudaMemcpyDeviceToHost);
 
    // Test the result
    for (int i = 0; i < VECTOR_LENGTH; i++)
    {
        assert(fabs(out[i] - a[i] - b[i]) < MAX_ERR);
    }
    printf("out[0] is %f\n", out[0]);
    printf("PASSED\n");
    
    // Free the memory
    cudaFree(d_a);
    cudaFree(d_b);
    cudaFree(d_out);
    free(a);
    free(b);
    free(out);
}
```

besides the original figure, there are more linting error:
![Screen Shot 2021-06-21 at 4 00 00 PM](https://user-images.githubusercontent.com/17561508/122727577-bf8e1d80-d2a9-11eb-9250-5cf55294821b.png)

**Comment by alexr00** [comment]
I'm not able to reproduce the issue by just using your CUDA C++ file, which indicates to me that this is likely caused by one or more of your installed extensions.
