### ISSUE TITLE
Can't open vscode with sudo --user-data-dir

### ISSUE THREAD

**Issue by thang1160** [microsoft/vscode#126747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: CentOS Linux 8

Steps to Reproduce:

1. I ran vscode as superuser with `sudo code --user-data-dir --verbose`, It work fine on my Ubuntu but can't run on CentOS

Log from verbose mode:
```
[10117:0620/003538.082293:ERROR:appcenter_api.cc(53)] expecting appcenter url prefix
No protocol specified
[10117:0620/003538.082958:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
The futex facility returned an unexpected error code.
```

**Comment by AshuKV** [comment]
I want to work on this issue.Please assign this issue to me.

**Comment by deepak1556** [comment]
CentOS had crashes due to https://github.com/microsoft/vscode/issues/115784, which should be fixed in latest stable. Try running with `--no-sandbox` if you need to run application as sudo.
