### ISSUE TITLE
Search Editor Does Not Reuse Prior Search Configuration

### ISSUE THREAD

**Issue by gardner-bp** [microsoft/vscode#126712]
Issue Type: <b>Bug</b>

Enable User Setting Search > Search Editor: Reuse Prior Search Configuration
Possibly relevant: Search: Mode = view
Assume two or more tab regions (window split)
Open Find and Replace (Ctrl+H)
Enter parameters set case, one word, etc. to taste
Replace All
Focus a different tab region
Ensure cursor is on an empty line (to avoid seed override of find parameter)
Open Find and Replace (Ctrl+H)
Expected: Find and Replace configuration matches last instance
Actual: Find and Replace configuration is blank

Note different tab regions always seem to maintain separate configurations, which means if you want to do the same thing you just did in another tab zone, you have to type it all over again. I can see how there might possibly be a use case for the current behavior, but I have a very hard time imagining that it would be the more commonly desired use case.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (17.11GB free)|
|Process Argv|-n --crash-reporter-id 8a1dddce-7958-411f-a3ff-d960b4de06ac|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
To be clear, you aren't using the Search Editor at all here? This is all taking place in the search view?

**Comment by gardner-bp** [comment]
Good question. I'm not sure what the difference between them is.
There's a search side-bar that opens when you click the magnifying glass (I'm guessing that's the Search Editor)?
There's also a thin popup search that appears at the top of the current tab zone when I press Ctrl+F or Ctrl+H
I'm guessing that's the Search View? In any case, it's this second one that the issue was created for.

I think I probably got the "Search Editor" wording from something I found in the Settings.

**Comment by JacksonKearl** [comment]
The search editor is this view:
![image](https://user-images.githubusercontent.com/8586769/124042963-db3aa780-d9be-11eb-8622-76eb3735f32c.png)

which you get when you click "Open in Editor" in the search view, here:
![image](https://user-images.githubusercontent.com/8586769/124042986-ebeb1d80-d9be-11eb-8b11-0cbdfd272a9a.png)

For the original question, `Setting Search > Search Editor: Reuse Prior Search Configuration` only applies to the search editor, search views play by their own rules, @roblourens might be able to say if this is expected or not.

**Comment by gardner-bp** [comment]
Good to know. Neither one of those is the one I was talking about.
The Search Editor looks kind of close except that it seems to have its own tab and is searching across multiple files.

The one I was talking about is searching text within only the current file:
![vscode-search](https://user-images.githubusercontent.com/25256622/124043857-340f3d80-d9c9-11eb-8e30-c1c5bacbfb49.png)

**Comment by JacksonKearl** [comment]
Ah, thanks for the clarification. In that case @rebornix would know best, though I expect this is expected, as the find widget is tied to a particular editor.
