### ISSUE TITLE
Add Folder to Workspace seems to conflict with Trust Security feature

### ISSUE THREAD

**Issue by aminchoroomi** [microsoft/vscode#126740]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open a folder in VSCode for the first time
2. Trust the folder's author
3. Add another folder (it has to be untrusted yet) to the workspace
4. Then the Trust Security modal pops up and window reloads at the same time before you get a chance to authorize the folder
5. You will end up with a reloaded window showing only the first folder and no sign of the second one.

I tried it a few times and every time I got the same result. Not sure it's a bug, but I felt reporting it might help.

I opened the second folder separately in VSCode, authorized it, closed it, and then came back and added the folder to the workspace with no issues.

**Comment by aminchoroomi** [comment]
I checked both links. I don't think it's a duplicate. Those are different issues

**Comment by sbatten** [comment]
I believe this is the duplicate https://github.com/microsoft/vscode/issues/126015... it applies to remote workspaces in general.
