### ISSUE TITLE
Too hard to tell which extension is giving errors/warnings/info messages in the Problems window

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#12675]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Install a bunch of extensions that add messages to the Problems window (warnings/errors/info).
2. Open some workspace that gives messages.

Bug#1: For extensions that don't include their output with the name of the extension, like "[css]" or "[Spell Checker]" it's too hard to tell which extension is causing the message. For example, people have complained about our C/C++ extension giving error messages, when it's another C++ extension and the user has to manually disable every possible extension to figure out which is causing the error message.

Bug#2: And I can't filter based on the extension.

Maybe all extensions should include an identifier with their messages?

Bug#3: In general, it'd be great if I could more easily tell which extension is providing a feature. For example, when I do "Format Code" with multiple format providers installed, I have no idea which one is actually be used. If VS Code could add the name of the extension handler, such as "Format Code [C/C++]" that would be really great. If you think this is too annoying for user who don't care, having optional diagnosis mode/setting would be nice. People have reported bugs for the wrong extension, because they didn't know another extensions was actually handling the functionality, particularly when an existing extensions adds capabilities in an update and it causes another extension from not being executed.

**Comment by joaomoreno** [comment]
@sean-mcmanus Please file separate **concise** issues for each bug.

**Comment by sandy081** [comment]
@sean-mcmanus Problems view shows who is the source of the problem if provided. Please check the following screenshot

![screen shot 2016-10-03 at 12 53 26](https://cloud.githubusercontent.com/assets/10746682/19035229/909654be-8968-11e6-8654-bf3892b098a3.png)

This information should be provided by the extension generating these markers. So, I would suggest to add this information when generating the markers. Also file issue on other extension where the markers are not having this info.

Thanks
