### ISSUE TITLE
Markdown hover in status bar: not working without specified `command`

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#126753]
#126258

Custom hover is not shown if status bar item doesn't have a command (works only after uncommenting one line).

```ts
const __ = window.createStatusBarItem(StatusBarAlignment.Left, -9999);
__.text = 'test';
// __.command = '';// <<<<<
const md = new MarkdownString('[$(github)](https://github.com)', true);
md.isTrusted = true;
__.tooltip2 = md;
__.show();
```

Commit: 7dea6d7402b55671410a129661cad24b55aed9f4
OS: Windows_NT x64 10.0.19043

**Comment by aeschli** [comment]
@bpasero `pointer-events: none` is set on the label container if a status bar entry has no command.
That prevents also hovers (including the native hover (title)

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css#L109
