### ISSUE TITLE
Test: Yeoman vscode extension generator

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12670]
Tests #10136

- [x] Windows - @ramya-rao-a
- [x] Linux - @octref
- [x] Mac OS - @roblourens 

Complexity: 3

### Setup

- run npm install -g yo generator-code

### Test TS extension

- run yo code
- create a TS extension
- in the generated code verify that:
  - the code compiles and Ctrl+Shift+B works
  - errors are detected while you type
  - code complete works (for vscode & es6 features)
  - no DOM is available
- test that you can launch the extension
- test that you can debug the extension
- test that you can execute the extension test cases

### Test JS extension

- same as the TS extension but for a JS extension (minus building and TS error reporting)
- in addition test that eslint works correctly (for example add unused var). 
- if eslint extension is not installed vscode should recommend it.

**Comment by octref** [comment]
@dbaeumer Can you clarify a bit what you meant by "no DOM is available"?

**Comment by dbaeumer** [comment]
@octref You don't get code assist on Browser window and you don't see any DOM types in code assist

**Comment by octref** [comment]
@dbaeumer Confirmed to work. Thanks!
