### ISSUE TITLE
Consider to use `touch-action: manipulation` on touch devices?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126726]
I recently came across `touch-action: manipulation` CSS rule. According to the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action):

> Enable panning and pinch zoom gestures, but disable additional non-standard gestures such as double-tap to zoom. Disabling double-tap to zoom removes the need for browsers to delay the generation of click events when the user taps the screen. This is an alias for "pan-x pan-y pinch-zoom" (which, for compatibility, is itself still valid).

I do not think we want the panning and zooming, but the removal of the 300ms delay sounds great to get a more snappy UI when using touch for e.g. action bars.

Maybe worth a try?

**Comment by bpasero** [comment]
I wonder if `touch-action: none` would even be the right thing, but not sure it removes the 300ms delay:

> Disable browser handling of all panning and zooming gestures

**Comment by bpasero** [comment]
Interesting, I see we use this property already, e.g. in the list:

https://github.com/microsoft/vscode/blob/97a719dd9b6f56ae724df1beb79944596d998eb6/src/vs/base/browser/ui/list/list.css#L41-L44

**Comment by isidorn** [comment]
Worth experimenting with.
@joamoreno do you remember why you added that css property for the list?

For now assigning to June, might push out due to lack of time.

**Comment by isidorn** [comment]
Did not have time, pushing out to August, since in July I am on vacation

**Comment by joaomoreno** [comment]
> @joaomoreno do you remember why you added that css property for the list?

Probably for the 300ms removal.

**Comment by isidorn** [comment]
Adding bug, so we get this verified. Steps:
1. Use ipad. 
2. Make sure the touch behaves as expected in the editor and some views
3. Long touch triggers context menu
