### ISSUE TITLE
`Trusted folders` handles symlinks inconsistently with `Open folder`

### ISSUE THREAD

**Issue by jpetkau** [microsoft/vscode#126746]
Issue Type: <b>Bug</b>

Possibly Windows-specific.

1. Have a project folder and a symlink to it.

    Directory of C:\
    07/11/2020  02:00 PM    <SYMLINKD>  proj  [C:\Users\bob\etc\etc]

2. Go to "manage workspace trust / add folder", and try to add `C:\proj`. It will replace the symlink with the full name, e.g. `C:\Users\bob\etc\etc`.

3. Open the symlink (`C:\proj`) via 'Open folder'. Or 'Open workspace' or any other way of opening a file via the symlink. Note that vscode preserves the symlink name, e.g. `C:\proj\file.md`, not `C:\Users\...\`.

4. Note that the folder is not recognized as trusted because of the name mismatch.

Workaround: if you trust the folder via the checkbox in the popup, it keeps the symlink in the name and works.

In short: the "workspace trust / add folder" dialog replaces symlinks with absolute paths, but other ways of opening files keep the symlink, and the actual trust check doesn't understand that the referenced paths are the same.

Ideally, the "workspace / add folder" dialog would keep the path as you entered it, *and* the actual trust check would compare resolved paths rather than strings. That way you could e.g. trust `C:\Users\bob\trusted`, and it would work whether the file was opened via a symlink or not, and stop trusting if the symlink changed to point elsewhere. Or you could trust the symlink, and folders under that symlink would be trusted regardless of whether you opened them that way. (But that might be harder; just trusting the latter by string compare would be sufficient.)

VS Code version: Code - Insiders 1.58.0-insider (7dea6d7402b55671410a129661cad24b55aed9f4, 2021-06-18T13:58:43.903Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
vspre833:30321513
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by sbatten** [comment]
Unfortunately after investigation, I see that since all of our logic lives in the render process there does not seem to be a way for us to resolves symlinks to do the necessary checks for this. Perhaps we have something that I missed or we need to add something... @bpasero do you know about anything that would help?

**Comment by bpasero** [comment]
I suggest to allow people to edit the paths not only with a native dialog (that seems to resolve symlinks) but also just pasting in a path so that the symlink can be added.

**Comment by jpetkau** [comment]
After more experimentation it looks like my original description was wrong. The inconsistency isn't been the file open dialogs for "open folder" vs. "trusted folders"; it's whether you *stop* at a symlink or at a child of one.

E.g. in my example above, entering `C:\proj` in either dialog box will resolve the symlink to `C:\Users\bob\etc\etc`. But if you enter `C:\proj\subproj` in either box, it will keep the symlink in the path.

So the reason that I saw this problem only with trusted folders was because I was trying to navigate to the root of my projects folder (the symlink), rather than one of the non-symlink projects within it, not because the trusted folder dialog was doing anything differently.

But it is still surprising behavior, and unlike with project setup there doesn't seem to be a an easy way to edit the trusted folders list without going through the dialog at all.

As a workaround, you can enter `C:\proj\.` and it the dialog will navigate to the folder without resolving it, and then delete the `.` from the name field.

**Comment by sbatten** [comment]
@misolori, thoughts on a good UX for allowing 2 ways to select the folder. right now, for local folders we always use the native file picker. you can also double click the entry in the list to edit but we also use the dialog. one idea i have is to make the double click behavior to edit it the text directly and the pencil for using the dialog.

**Comment by misolori** [comment]
How about the pencil allows you to edit the path inline, like you suggest, and then add a `folder` icon that allows you to open the folder picker dialog?

**Comment by sbatten** [comment]
And what should double click do? still folder?

**Comment by misolori** [comment]
I think typically double click is for the default behavior, which is the folder picker in this situation?
