### ISSUE TITLE
typescript intellisense import is not supported in <script lang="ts"> block

### ISSUE THREAD

**Issue by dbwhddn10** [microsoft/vscode#126770]
typescript intellisense import is not supported in <script lang="ts"> block

when ts file extension
![ts_vscode](https://user-images.githubusercontent.com/1523570/122665705-bf2b4f00-d1e3-11eb-9e7c-2b32e45f0ac2.png)

when vue file extension and use in <script lang="ts"> block
![vue_vscode](https://user-images.githubusercontent.com/1523570/122665699-b63a7d80-d1e3-11eb-9072-2deaea25f3b2.png)

**Comment by usernamehw** [comment]
/causedByExtension You should file this issue for Vetur extension
