### ISSUE TITLE
Code info not visible when it's on the top of the window

### ISSUE THREAD

**Issue by bvanrijn** [Microsoft/vscode#12674]
- VSCode Version: 

```
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:40:08.699Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Hover over an item at the top of your screen with a large hint
2. You will see that part of the hint is obfuscated by the top border of the screen

Pictures (and screenshots) speak a thousand words:
![screenshot from 2016-09-26 21-54-27](https://cloud.githubusercontent.com/assets/11941174/18849599/fa210f94-8433-11e6-933f-994a3b60065e.png)
![screenshot from 2016-09-26 21-56-39](https://cloud.githubusercontent.com/assets/11941174/18849638/20a2377e-8434-11e6-8d54-23ccd9b31bf3.png)

**Comment by joaomoreno** [comment]
First, this seems to be the old hover. Second, the widget seems to overflow the view.

**Comment by joaomoreno** [comment]
Damn dude, you sure like to go dig out those dust-covered issues. 🚚 

This widget has changed considerably since.
