### ISSUE TITLE
Incorrect Window Focused on Cmd-Tab

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode#126779]
Issue Type: <b>Bug</b>

First of all, thanks for all of your work on VS Code, really amazing project and editor! 💯 🙌

I use VS Code with a lot of projects open at the same time (in different editor windows, **across multiple screens**).

One thing that I've noticed for a few VS Code releases is that the topmost (last focused) window on one screen is no longer respected when using cmd-tab on macOS to switch back to VS Code.

1. Work in a certain editor window on screen 2
2. Cmd-tab to a different application
3. Cmd-tab back to VS Code -> different editor window on screen 1 is focused, causing me to type in a different editor in the wrong project 😫

cc @bpasero 

---

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 19d08aca-002b-40e2-9fbe-5ab2d1646bf8|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615cf:30323120

```

</details>

---

Maybe related to https://github.com/microsoft/vscode/issues/126013

**Comment by karlhorky** [comment]
**Workaround:** Minimize all other editors in VS Code, then `cmd-tab` works.

**Comment by karlhorky** [comment]
Testing this a bit more, it seems like it makes a difference that I am using VS Code on multiple monitors.

It always focuses the topmost editor window on screen 1, instead of focusing the last editor window (which was on screen 2)

I've added this to the original issue description

**Comment by bpasero** [comment]
That sounds more like an electron issue to me.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by karlhorky** [comment]
Tried with version: `1.58.0-insider` (Commit: 7dea6d7402b55671410a129661cad24b55aed9f4) and the issue still seems to be present...

**Comment by bpasero** [comment]
Anything special about your setup?

**Comment by karlhorky** [comment]
The only thing that comes to mind so far is just the two monitors (one is the built-in MacBook M1 monitor, the other is an external). I tried already disabling all extensions (and no extensions installed in Insiders).

**Comment by karlhorky** [comment]
@deepak1556 @bpasero I can check whether 3caebff71e514ece73b125468881d102e767ee4d fixes this as soon as I'm back at my dual monitor setup

**Comment by karlhorky** [comment]
Looks like the new Insiders edition fixes it when switching between VS Code Insiders and a non-Chromium product (eg. Safari):

If you follow the start of these instructions, there is a small behavior that is now fixed:

1. Prepare VS Code as described in [the original description](https://github.com/microsoft/vscode/issues/126779#issue-925581135) (at least two windows, one on each monitor)
2. Focus the editor in the VS Code window on the secondary monitor (not the laptop screen)
3. <kbd>cmd</kbd>-<kbd>tab</kbd> to another application and interact with a window **on the 2nd monitor**
4. <kbd>cmd</kbd>-<kbd>tab</kbd> back to VS Code - focus is in the correct editor in the window on the secondary monitor! 🎉

However... if you <kbd>cmd</kbd>-<kbd>tab</kbd> between VS Code Insiders and Chrome (when Chrome also has a window on each of the monitors), then the bug remains.

This leads me to believe that the bug is actually in Chromium... Wonder if there's an open bug on the Chromium bug tracker for this...

So I would close this - unless either of you object @deepak1556 @bpasero ?

**Comment by karlhorky** [comment]
Ah, and the Chrome bug also seems to be fixed in Chrome Canary. So should be gone in the some of the next stable releases, yay!

Closing...
