### ISSUE TITLE
Settings UI: value not updated visually

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#126782]
Issue Type: <b>Bug</b>

Configuration:

```js
"someFilePath": {
	"type": "string",
	"markdownDescription": "[**Specify file path**](command:specify)",
	"default": ""
}
```

Code:

```ts
commands.registerCommand('specify', () => {
	const settings = vscode.workspace.getConfiguration(undefined, null);
	settings.update('someFilePath', 'NEW FILE PATH', vscode.ConfigurationTarget.Global);
});
```

You can see that the modified border appeared but the value did not change until it lost focus.

![demo](https://user-images.githubusercontent.com/9638156/122676079-f77f5d00-d1e4-11eb-8dd6-60706bd3bc04.gif)

---

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by roblourens** [comment]
This is tricky. We purposely don't pull in updates until the user has stopped editing (focus leaves the setting) because it will conflict with the user's text editing

**Comment by usernamehw** [comment]
Specifying the file path with OS dialog: `window.showOpenDialog()`

**Comment by usernamehw** [comment]
If it's not a bug, then I'm closing it.

**Comment by roblourens** [comment]
I'd like to provide that built-in https://github.com/microsoft/vscode/issues/56834 and we have recently been looking at settings editor issues again, so good to know that you would find that one useful
