### ISSUE TITLE
Terminal tabs list click to activate doesn't work sometimes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126776]
Flaky repro:

Clicking a terminal tab sometimes doesn't make that terminal active. It ends up working when clicking around a  few times and then it works consistently, so maybe a context key isn't getting set right.

**Comment by sexta13** [comment]
This also happens to me. OnClick doesn't change the tab....but if I kind of drag it opens...

**Comment by Tyriar** [comment]
![recording (22)](https://user-images.githubusercontent.com/2193314/122756015-b15ce480-d24a-11eb-8184-1b82d86b54eb.gif)
