### ISSUE TITLE
PrintArgs

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode#126764]
必要なデータが送信するには大きすぎたため、クリップボードに書き込みました。貼り付け
![image](https://user-images.githubusercontent.com/77566899/122658641-afdbdf80-d1aa-11eb-9334-9356f58e8fca.png)
てください。

**Comment by hiroshi-nakajima345** [comment]
A.Original
PrintArgs &Commanline Arguments Probrem.
❶
public static void main(String[] args) {
		// TODO Auto-generated method stub
		//class PrintArgs {
			//public static void main(String[] args) {
				for (int i = 0; i < args.length; i++)
					System.out.println("args[" + i + "] = " + args[i]);
			}
		
}
VSC  does not work by only above.code
②
java PrintArgs Turbo NA DOHC
	//String[] sx = new String[3]
	sx[0] = "Turbo";
	sx[1] = "NA";
	sx[2] = "DOHC";

         if I add ②(for example) code to❶、is it possible to show in my IDE.
        how to make it.


B.Next Probrem 

❶
//(1)my code plan
public class PrintArgs2_ArrayFormIn {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		/int i = 0;
		String sx = String.valueOf(i);  
		String[] sx = 0;
		//String [] sx = new String ("%d",i);
		  sx[0] = "Turbo";
		  sx[1] = "NA";
	          sx[2] = " DOHC";

	          for ( int i = 0; i < args.length; i++)
	  			System.out.println("args[" + i + "] = " + args[i]);

	
	


	}
}
②
//(1)boyo.java.L16_10.no4.2021.6.20.eclipse
import java.util.Arrays;
import java.util.*;
public class Turbo {

	//private static final String[] String = null;
	//private static int i;

	public static void main(String[] args)  throws Exception{
		
	for (int i =0; i<args.length; i++)
	  System.out.println("args[" + i + "] = " + args[i]);
   int intSample =0;
   int intSample1 =1;
   int intSample11 =2;
   String intString =Integer.toString(intSample11);
  
  String sx = new java.lang.String();
String[] sx1 = new String[3];
 
   sx1[0] = "Turbo";
   sx1[1] = "NA";
   sx1[2] = "DOHC";
   
	}

	
	}
⁂　in this cace 
a.part of under code may be deleted better

//private static final String[] String = null;
	//private static int i;

	public static void main(String[] args)  throws Exception{
		
	for (int i =0; i<args.length; i++)
	  System.out.println("args[" + i + "] = " + args[i]);
   int intSample =0;
   int intSample1 =1;
   int intSample11 =2;
   String intString =Integer.toString(intSample11);
b.more problem.
convert int to String.
I tried it but could not   solve.
<exapmle>
import java.util.*;
 
public class Main {
    public static void main(String[] args) throws Exception {
 
        int intSample = 1;
        
        String intString = Integer.toString(intSample);
        
        System.out.println("int型をtoStringメソッドで変換 = " + intString);
    }
}




//(2)<the reason why_why VSC does not initialize?>
❶in the code of above is mistake.
②VSC rsfuse  may my mesage .
③My message consist of japanese.~if so,i want to improve in the future.

(3)//Enhanced for statement_naming do not correct?
this may be one of the way to resolve.
<example>

import java.util.*;
 
List<String> list = Arrays.asList(
	"foo", "bar", "hoge"
);
 
for (String s: list) {
	System.out.println(s);
}

(4)another way to resolve PrintArgs .commandlin Arguments  problem.
❶<main.code>
public class ArrayForTurbo {

	public static void main(String[] args) {
		int[] nums;
		// TODO Auto-generated method stub
	/*	nums[0] = 2;
        nums[1] = 3;
        nums[2] = 5;
        nums[3] = 7;
        nums[4] = 11;

        for (int i = 0; i < nums.length; i++) {
            System.out.println("要素番号：" + i + " 値：" + nums[i]);
        }
*/
        // 配列の初期化、拡張for文を使った出力
        String[] names = {"Turbo", "HA" ,"DOHC"};
        for (String name : names) {
            System.out.println("名前：" + name);~ contain japnese  
        }

    }

}

②run~by.eclipse :success
名前：Turbo
名前：HA
名前：DOHC
(5)another probrem.2
❶WER.Fault was discover
②error of commandlineargument(PrintArgs) ~how can I solve this?
VSC show <PrintArgs is a non-project file,only syntax errors are reported.java 16[1.1］>

*my explain may be very poor.
forgive. me.
&
I thank you for your kindness.

----- 元のメッセージ -----
From: "VS Code Issue Triage Bot" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Author" ***@***.***>
送信済み: 2021年06月20日 午前 9:37
件名: Re: [microsoft/vscode] PrintArgs (#126764)

>  この問題を作成してくれてありがとう!しかし、説明は英語ではないため、私たちはそれに取り組むのが難しいです。もし、可能であれば、英語で行くように編集してください。新しいコメントを追加したり、新しい懸案事項を作成したりするのではなく、既存の懸案事項を編集してください。残念ながら、自動翻訳サービスはソフトウェアの問題について効果的にコミュニケーションを取るために必要な技術言語を扱うことはできないので、翻訳を支援する技術に精通している人の翻訳者を見つけることをお勧めします。それ以外の場合、この問題は翻訳が必要であるとマークされており、コミュニティメンバーが翻訳を支援できる場合があります。Thanks for creating this issue!Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.Otherwise, we have marked this as needing translation and a community member may be able to help out.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bpasero** [comment]
What is there for VSCode to fix here?
