### ISSUE TITLE
Can highlight line numbers by right clicking

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12673]
Right click on line numbers -
![image](https://cloud.githubusercontent.com/assets/323878/18849455/ede9a43a-83e7-11e6-82cb-a1054c492112.png)
Doesn't look that great

Also reproes in stable, I wouldn't say it's high priority.

**Comment by alexandrudima** [comment]
I can't reproduce on windows

**Comment by alexandrudima** [comment]
I have just tried on the mac mini in the office and I cannot reproduce.

**Comment by ramya-rao-a** [comment]
Removing the bug label as this is not reproducible. @roblourens re-open if this is still an issue

**Comment by roblourens** [comment]
Yeah I think it was fixed awhile back at some point
