### ISSUE TITLE
Sash highlight isn't working on panel and sidebar when hovering their intersection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126777]
I think it used to, now it only happens when clicking:

![recording (21)](https://user-images.githubusercontent.com/2193314/122671146-24e2f100-d17a-11eb-8914-c27e4d3677ed.gif)

**Comment by joaomoreno** [comment]
I also noticed this last Friday and fixed it then: https://github.com/microsoft/vscode/commit/fe160b35e58209de2fa5f3c6847385f9baf1d527
