### ISSUE TITLE
Copy a Plot from "Plot Navigator" to clipboard for pasting into a document

### ISSUE THREAD

**Issue by Peter-Jolly** [microsoft/vscode#126885]
The new Plot Navigator window in the latest release of Vscode is very useful but it would be more useful if you could copy the plot to the clipboard and hence past into other documents. Is this possible? If so how? I use MS Windows 10. Thanks Peter

**Comment by weinand** [comment]
@Peter-Jolly VS Code has no "Plot Navigator". I think you are talking about a feature of the Julia extension.
