### ISSUE TITLE
In Remote for SSH , Forwarding Ports cannot via Host IP access

### ISSUE THREAD

**Issue by junhwong** [microsoft/vscode#126812]
Does this issue occur when all extensions are disabled?: Not working

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

In Remote for SSH , Forwarding Ports cannot via Host IP(eg. 192.168.1.87) access， just localhost.

![image](https://user-images.githubusercontent.com/8044424/122744501-9c1f9e80-d2ba-11eb-9a69-e494f1ca268c.png)

I don’t know if it’s the newly updated security policy. If it is, I hope it can be customized in the port setting. 

eg.

![image](https://user-images.githubusercontent.com/8044424/122745188-544d4700-d2bb-11eb-9d7e-372ab2034493.png)

**Comment by alexr00** [comment]
@junhwong you can change the default local host using the setting `remote.localPortHost`.

**Comment by junhwong** [comment]
@alexr00 thk for your reply. I didn’t find it on the setting side before （⊙＿⊙；）…
