### ISSUE TITLE
Integration test: flaky git smoke test

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126813]
https://github.com/microsoft/vscode/runs/2874052635?check_suite_focus=true#step:15:1020

```
git smoke test
[4572:0621/101418.852:INFO:CONSOLE(196)] "%c INFO color: #33f [logs cleanup]: Starting to clean up old logs.", source: vscode-file://vscode-app/d:/a/vscode/vscode/out/vs/platform/log/common/log.js (196)
[4572:0621/101438.854:INFO:CONSOLE(196)] "%c INFO color: #33f [storage cleanup]: Starting to clean up storage folders.", source: vscode-file://vscode-app/d:/a/vscode/vscode/out/vs/platform/log/common/log.js (196)
    1) "before all" hook for "reflects working tree changes"
  23 passing (1m)
  1 failing
  1) git smoke test
       "before all" hook for "reflects working tree changes":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\git\out\test\smoke.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by bpasero** [comment]
Since I pushed changes related to processing file change events today, this could be on me as well. But I would think my changes should not have any impact because they were only around throttling file events if the number of changes is very high (e.g. > 500) which I would not think the git smoke test exercises?

**Comment by joaomoreno** [comment]
The error happens in the `before all` hook:

https://github.com/microsoft/vscode/blob/78946a0204256e9c65c13d7bc25cc40988e6d601/extensions/git/src/test/smoke.test.ts/#L43-L66

I bet one of those two async statements is hanging forever:

- https://github.com/microsoft/vscode/blob/78946a0204256e9c65c13d7bc25cc40988e6d601/extensions/git/src/test/smoke.test.ts/#L55
- https://github.com/microsoft/vscode/blob/78946a0204256e9c65c13d7bc25cc40988e6d601/extensions/git/src/test/smoke.test.ts/#L59

I bet on the second one, especially if there were changes in file events. Let's wait and see if it's flaky or consistently failing.

**Comment by bpasero** [comment]
The tests passed on the Azure CI:

![image](https://user-images.githubusercontent.com/900690/122748192-35838c00-d28c-11eb-8181-90014afb9dbd.png)

Flaky it seems, but not sure if more flaky now than before.

**Comment by bpasero** [comment]
Oh btw, any test that relies on file events is flaky by definition :)

**Comment by joaomoreno** [comment]
They have been very reliable in the past:

![image](https://user-images.githubusercontent.com/22350/122749270-ff211f00-d241-11eb-8bb3-ca523b4e94b3.png)

Today there's definitely a drop in success rate. Something's fishy.

**Comment by bpasero** [comment]
Let me test on windows...

**Comment by joaomoreno** [comment]
Confirmed: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=124068&view=logs&s=27eddb93-7805-576c-c80f-37b2176e40f7&j=672276a2-8d3a-5fab-615d-090c51352f92 🙈

**Comment by bpasero** [comment]
I can reproduce btw on Windows, running out of sources. What's there in the setup method that needs file events to work?

**Comment by bpasero** [comment]
Adding some log messages I can confirm that it seems to hang at `onDidOpenRepository`

**Comment by bpasero** [comment]
Yeah seems flaky, when I run e.g. with `--verbose` I cannot reproduce even with my changes.

I suggest for this test to not assume file events are working and try to e.g. refresh the git repository manually through some command.

**Comment by bpasero** [comment]
Wth it can only be my change but it is impossible for me to explain. First instance seems to be this change actually:

https://github.com/microsoft/vscode/commit/a102b4478e7a2c289b1e8aadefef8158d6e3acb5

But that shouldn't really change anything...
