### ISSUE TITLE
npm commands are too slow

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#126810]
The npm start command is too slow to open react server

**Comment by weinand** [comment]
How is this related to VS Code? Neither "npm" nor "react server" are part of VS Code.

**Comment by tymsai** [comment]
In vscode terminal it is slow

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" terminal
