### ISSUE TITLE
Help uninstall old vsc app

### ISSUE THREAD

**Issue by SailorCode29** [microsoft/vscode#126876]
Issue Type: <b>Bug</b>

This error Message open app vsc 1.26.1 

Process:               Electron [11557]
Path:                  /Users/USER/*/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.26.1 (1.26.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [11557]
User ID:               501

Date/Time:             2021-06-22 10:43:42.942 +0700
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        CE392D95-C03D-DBE4-EEA5-6C76B604B10C

Sleep/Wake UUID:       7F458E51-62A4-4531-BF22-1E4C5E359FE2

Time Awake Since Boot: 8200 seconds
Time Since Wake:       2900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/*/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Users/4rch29/.vscode/extensions/spoonscen.es6-mocha-snippets-0.2.2/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/Users/4rch29/.vscode/extensions/spoonscen.es6-mocha-snippets-0.2.2/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

Binary Images:
       0x107ab0000 -        0x107ab0fff +com.microsoft.VSCode (1.26.1 - 1.26.1) <D1F248EA-3916-382F-A28E-9E60D78F3737> /Users/USER/*/Visual Studio Code.app/Contents/MacOS/Electron
       0x108b47000 -        0x108be2fff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld
    0x7fff2e276000 -     0x7fff2e397fff  com.apple.Bluetooth (8.0.5 - 8.0.5d7) <7630620F-575C-37A6-ACAA-3B9443127E88> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

Model: MacBookPro15,2, BootROM 1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0), 4 processors, Quad-Core Intel Core i5, 2,4 GHz, 8 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 4 GB, LPDDR3, 2133 MHz, Samsung, K4E6E304EC-EGCG
Memory Module: BANK 2/ChannelB-DIMM0, 4 GB, LPDDR3, 2133 MHz, Samsung, K4E6E304EC-EGCG
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 16 2021 02:10:42 version 9.30.444.10.32.5.67 FWID 01-a00c1314
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id d9f38843-c764-45b0-967e-465387cae670|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (119)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
codesnap|adp|1.3.2
vscode-css-formatter|aes|1.0.1
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.1.0
vscode-color|ans|0.4.5
svelte-intellisense|ard|0.7.1
vscode-node-readme|ben|3.0.2
color-info|bie|0.6.0
lit-html|bie|1.11.1
turbo-console-log|Cha|2.1.6
node-snippets|chr|1.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
regex|chr|0.4.0
jsrefactor|cms|2.20.6
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
angular-schematics|cyr|4.13.0
angular2-snippets|dan|1.0.21
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
vscode-dash|dee|2.4.0
vscode-faker|dee|1.5.0
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.22
vscode-great-icons|emm|2.1.77
react-native-react-redux|EQu|2.0.6
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|7.1.1
vscode-todo-plus|fab|4.18.3
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.4
vscode-svelte-snippets|fiv|0.5.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
vscode-google-translate|fun|1.4.13
html-slim-scss-css-class-completion|gen|1.7.8
vscode-pull-request-github|Git|0.27.1
javascript-complete-packs|Gul|1.3.1
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
vscode-k3d|ine|0.0.10
path-autocomplete|ion|1.17.1
vscode-cdnjs|Jak|0.19.0
search-node-modules|jas|1.3.0
Angular2|joh|12.0.0
google-search|kam|0.0.1
vscode-simple-icons|Lau|1.14.0
node-module-intellisense|lei|1.5.0
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.14.0
vscode-kubernetes-tools|ms-|1.3.3
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vsliveshare|ms-|1.0.4419
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
angular-console|nrw|17.5.1
vetur|oct|0.34.1
indent-rainbow|ode|7.5.0
csv-to-table|php|1.2.3
material-icon-theme|PKi|4.7.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
inline-html|pus|0.3.3
gitlink|qez|0.7.0
quicktype|qui|12.0.46
vscode-yaml|red|0.20.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
gi|rub|0.2.11
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|2.2.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.21
vscode-fileutils|sle|3.4.5
vscode-multiclip|sle|0.1.5
es6-mocha-snippets|spo|0.2.2
code-spell-checker|str|1.10.2
svelte-vscode|sve|105.2.2
open-in-browser|tec|2.0.0
es6-string-html|Tob|2.10.0
todo-list|Tza|1.6.0
errorlens|use|3.2.7
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
codetour|vsl|0.0.56
gistfs|vsl|0.2.9
quokka-vscode|Wal|1.0.381
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
vscode-surround|yat|1.1.2
markdown-all-in-one|yzh|3.4.0
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.10.14
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

**Comment by deepak1556** [comment]
Can you clarify what do you mean by help with uninstall ?

You should be able to remove the app with `rm -rf <path-to>/Visual Studio Code.app`, for a complete cleanup you should also remove `~/Library/Application Support/Code` and `~/.vscode`
