### ISSUE TITLE
Incorrect null check after await

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126854]
After `await` call, the `_editorModelReference` is possible to be `null` and the type should still be `IReference<IResolvedNotebookEditorModel> | null` other than `never`.

![image](https://user-images.githubusercontent.com/876920/122830056-a7fc6800-d29c-11eb-8288-dc768900853e.png)

**Comment by usernamehw** [comment]
Maybe a typo: `this._editorModelReference` was used instead of `editorModelReference`?

`this._editorModelReference` was checked in the `if` above that it's falsy, then it was checked again if it's truthy without changing the variable value. `never` seems to be the right type in that case.

**Comment by rebornix** [comment]
@usernamehw this function can be called multiple times, and the async task `resolve` takes a long time to finish, so for all calls the first `this._editorModelReference` is `null` and then stop and wait for the promise the resolve. When the promise resolves, the first call continues, and it sets `this._editorModelReference` to an object; for the second calls, the `this._editorModelReference` is no longer `null` ;(

**Comment by yume-chan** [comment]
It's a common pitfall of TypeScript's control flow analysis, see Microsoft/TypeScript#9998 (it's opened in 2016!).

TypeScript can't dig into every function to check whether they change any field (due to performance reason), so it assumes all function to have no side effects.

**Comment by rebornix** [comment]
@yume-chan thanks for the pointer, yes it's definitely a limitation of TypeScript.

**Comment by mjbvz** [comment]
Closing as upstream
