### ISSUE TITLE
Can not switch between terminals when terminals are shown as tabs

### ISSUE THREAD

**Issue by padurean** [microsoft/vscode#126849]
Issue Type: <b>Bug</b>

1. Open 2 terminals.
2. From the terminal context-menu choose "Show Tabs".
3. Try to switch from one terminal to the other by (double-)clicking on terminal tabs - not working.
4. From terminal tabs pane context-menu choose "Hide Tabs" - terminals can be switched again from the combo-box.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
githistory|don|0.6.16
gitlens|eam|11.5.1
go|gol|0.26.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
search-editor-apply-changes|jak|0.1.1
go-prof|Max|0.0.4
rainbow-csv|mec|1.8.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
indent-rainbow|ode|7.5.0
gotolastedit|plr|0.6.4
vscode-thunder-client|ran|1.4.1
LiveServer|rit|5.6.1
code-snapshot|rob|0.2.1
iferrblocks|rst|1.1.1
partial-diff|ryu|1.4.3
vscode-open|san|0.1.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
octave|toa|0.0.3
vscode-icons|vsc|11.5.0
change-case|wma|1.0.0
txt-syntax|xsh|0.1.5
vscode-proto3|zxh|0.5.4

(1 theme extensions excluded)

</details>

**Comment by joelsand** [comment]
Same issue here, exactly as described, but on Windows 10.

VS Code version: 1.57.0
OS: Windows 10 (Windows_NT x64 10.0.19042)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by vasilev-alex** [comment]
@meganrogge still reproducible in the Insiders Build

**Comment by Tyriar** [comment]
I can't repro in Insiders with and without `"workbench.list.openMode": "doubleClick"` set

**Comment by vasilev-alex** [comment]
@Tyriar yep, sorry, it works. 

I use `singleClick` normally and didn't realize that all of my settings have synced in Insiders.

**Comment by Tyriar** [comment]
@vasilev-alex phew 😅
