### ISSUE TITLE
integrated terminal doesn't refresh when change branch by UI 

### ISSUE THREAD

**Issue by longtth** [microsoft/vscode#126891]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

## **Steps to Reproduce:**

1. clone a project from remote repo 
2. click on bottom-left icon to checkout to new branch (eg: standing in `main`, check out to `1-feature-01` ) 

![image](https://user-images.githubusercontent.com/1010849/122900608-09910500-d377-11eb-9dc8-820e5cc2a69a.png)

![image](https://user-images.githubusercontent.com/1010849/122900583-039b2400-d377-11eb-9c8e-77e363b44a10.png)

## Expect 

Integrated terminal should "refresh" to show that it has been "switch" to new branch

## Problem 

Although, if you run `git branch`, it will return that it has been switched to `1-feature-01`, but before that, the intergrated terminal still show as it still in `main` 

```console 
$ git branch
* 1-feature-01
  main
```

**Comment by yume-chan** [comment]
Where in integrated terminal shows current branch name? Do you have some plugins like oh-my-posh?

**Comment by longtth** [comment]
> Where in integrated terminal shows current branch name? Do you have some plugins like oh-my-posh?

thanks for you reply, 
I'm using git bash on Windows,
Seem not vscode problem
