### ISSUE TITLE
Splitting terminal editor will break the original editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126836]
Repro

1. Create terminal
2. Drag from panel to editor
3. Press the split editor button

![image](https://user-images.githubusercontent.com/2193314/122797451-5809ab00-d274-11eb-90b7-8d64731d758a.png)

**Comment by Tyriar** [comment]
I think this is related to the same "terminal resource"/input being used for both editors

**Comment by Tyriar** [comment]
Look into https://github.com/microsoft/vscode/issues/126469 first, it might not be related to the same uri?

**Comment by yume-chan** [comment]
I wonder whether "split editor" should duplicate the current terminal (like a normal editor), or create a new terminal editor in another editor group (like in terminal panel)?

**Comment by Tyriar** [comment]
@yume-chan were making it create. Anew one like in the panel

**Comment by meganrogge** [comment]
This is working for me
