### ISSUE TITLE
NotebookEditorModel leak on hot reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126853]
* Turn off auto save
* Open a GitHub issue notebook, tweak the content to make it dirty
* Reload the window
* After reload, save the document and then close
* Take a memory snapshot

<img width="517" alt="image" src="https://user-images.githubusercontent.com/876920/122829532-fa895480-d29b-11eb-8a06-cd31cca10e24.png">

https://github.com/microsoft/vscode/blob/e79612d1589f2da18ce260cfc8defe3bb7796fc3/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L57-L61 seems to contribute to this. 

`NotebookEditorInput#resolve` was called twice and in both calls

* `if (!this._editorModelReference) {` is true, so both calls will continue into the block
* however after `await this._notebookModelResolverService.resolve(this.resource, this.viewType);`, we got two `IReference<IResolvedNotebookEditorModel>` and one of them is not referenced by anyone or disposed

https://github.com/microsoft/vscode/blob/e79612d1589f2da18ce260cfc8defe3bb7796fc3/src/vs/workbench/contrib/notebook/common/notebookEditorInput.ts#L211-L214

Tweak the code to below and we can get a console warning in dev tools

```
		if (!this._editorModelReference) {
			const ediotrModel = await this._notebookModelResolverService.resolve(this.resource, this.viewType);

			if (this._editorModelReference) {
				console.warn('already initialized');
			}
```

**Comment by bpasero** [comment]
Since the second `resolve` originates from backups, let's continue in #125211

![image](https://user-images.githubusercontent.com/900690/122871373-2f92b700-d32f-11eb-83b6-f2c16aea8f80.png)
