### ISSUE TITLE
uninstall leaves junk behind

### ISSUE THREAD

**Issue by Madpeterz** [microsoft/vscode#126858]
When uninstalling the following folders are left behind
```
C:\Users\*USER*\AppData\Roaming\Code
```
![image](https://user-images.githubusercontent.com/57852827/122840202-8f6a6d00-d2f1-11eb-9f4e-dd0b557cddc6.png)
```
C:\Users\*USER*\AppData\Local\Temp\vscode-update-user-x64
```

OS: Windows 10 Pro
Version: 20H2
Build: 19042.1052

**Comment by joaomoreno** [comment]
#66837
