### ISSUE TITLE
Bug in TERMINAL window when copy and paste

### ISSUE THREAD

**Issue by luweiqianyi** [microsoft/vscode#126803]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Win10 19042.1052

Steps to Reproduce:

1. copy something
2. right-click in visual studio code's TERMINAL window
3. Then which I copied will be shown in TERMINAL window, I think it's a bug.

**Comment by meganrogge** [comment]
you can change that w `terminal.integrated.rightClickBehavior`
