### ISSUE TITLE
Action to reset IndexDB should move into developer actions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126881]
We have a place for developer actions here: `src/vs/workbench/browser/actions/developerActions.ts`

Please move this action there:

https://github.com/microsoft/vscode/blob/27b2434631bc9e253c30f3d55b837fea41a7c170/src/vs/workbench/browser/web.main.ts#L301-L301

**Comment by sandy081** [comment]
Its placed there because it uses internals 

https://github.com/microsoft/vscode/blob/27b2434631bc9e253c30f3d55b837fea41a7c170/src/vs/workbench/browser/web.main.ts#L322-L326
