### ISSUE TITLE
Search in directory in multi root workspace totally broken

### ISSUE THREAD

**Issue by linsui** [microsoft/vscode#126883]
Issue Type: <b>Bug</b>

Creat a workspace.
Add directory a.
Add directory a/b.
Search in b.
See results in a.

VS Code version: VSCodium 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-13T03:20:25.029Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
Please try with an official vscode build, not vscodium

**Comment by linsui** [comment]
I reproduce it in vscode. It seems the folder name is important.

This is the directory structure. In both a.txt is `test`.

```
test
    - testaaa
        - a.txt
    - a.txt
```

Add `test` and `testaaa` to workspace. Then search `test` in `testaaa`. I got results from two files.

**Comment by linsui** [comment]
![sshot-002](https://user-images.githubusercontent.com/36977733/123038399-d9318100-d3df-11eb-8b7f-1fb9b4e6a939.png)

**Comment by roblourens** [comment]
Open files will be searched even if they don't match the "files to include" query https://github.com/microsoft/vscode/issues/31819

**Comment by linsui** [comment]
No. It's not needed to reporoduce this bug.

**Comment by roblourens** [comment]
Actually, there was another issue fixed recently that allowed 'include' to match a different workspace folder if it started with the same substring. You can try in Insiders or check after the next release - should be fixed

**Comment by linsui** [comment]
Sounds like it's that bug. Thanks!
