### ISSUE TITLE
vs code is not working

### ISSUE THREAD

**Issue by Shubham9t** [microsoft/vscode#126893]
We have written the needed data into your clipboard because it 
Issue Type: <b>Bug</b>

after updating vs code 1.57.1 version its giving error like extension host terminated unexpectedly and search is not working ( i am searching file in my folder not getting any result )

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.36GB free)|
|Process Argv|--crash-reporter-id daece736-6d8b-4804-bcc1-597d3c79b20c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
HTMLHint|mka|0.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Does the problem still happen after you run the command to reload with all extensions disabled?
