### ISSUE TITLE
The autocomplete syntax highlighting is all jacked up in the most recent release

### ISSUE THREAD

**Issue by swilliams-a3digital** [microsoft/vscode#126864]
I think its best explained by looking at these screenshots:
<img width="284" alt="Screen Shot 2021-06-21 at 5 59 12 PM" src="https://user-images.githubusercontent.com/24925563/122846612-13edc900-d2bb-11eb-84ec-f751472694c5.png">
<img width="573" alt="Screen Shot 2021-06-21 at 5 02 38 PM" src="https://user-images.githubusercontent.com/24925563/122846624-1a7c4080-d2bb-11eb-9fa1-674c3f3cae4f.png">
<img width="547" alt="Screen Shot 2021-06-21 at 5 02 30 PM" src="https://user-images.githubusercontent.com/24925563/122846645-27009900-d2bb-11eb-9f38-173b8ad080be.png">

Part of the completed text is above the other, it looks awful and is confusing.  How to get the old style back?

**Comment by misolori** [comment]
@swilliams-a3digital can you please share your version/system info + any theme customizations in your settings? I am not able to reproduce:

<img width="644" alt="CleanShot 2021-06-22 at 06 25 41@2x" src="https://user-images.githubusercontent.com/35271042/122932544-af665480-d322-11eb-8b6b-4c65023ae9b0.png">

<img width="525" alt="CleanShot 2021-06-22 at 06 26 00@2x" src="https://user-images.githubusercontent.com/35271042/122932601-bab98000-d322-11eb-8940-a003b17bffd8.png">

Version: 1.58.0-insider (Universal)
Commit: d54f7e1f6c1290fe27e2397eca509d0e0728272e
Date: 2021-06-22T07:14:39.120Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

**Comment by swilliams-a3digital** [comment]
Version info:

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (5 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by swilliams-a3digital** [comment]
My Color theme is Visual Studio 2019 Light:
<img width="600" alt="Screen Shot 2021-06-22 at 4 03 36 PM" src="https://user-images.githubusercontent.com/24925563/123010443-77d3c880-d373-11eb-8763-4de9c736037e.png">

**Comment by swilliams-a3digital** [comment]
It looks like a problem with the Visual Studio 2019 Light theme.  I've had that theme for a while, and I think it was just the "LIght Theme" when I originally chose it.  I tried switching to the newer Light Theme and autocomplete syntax highlighting works fine with that.  I don't mind switching to the newer theme, so you can close the ticket if you want.  Maybe that 2019 Theme should be deprecated.

**Comment by misolori** [comment]
Ah, thanks fir that info. I'll update the VS one to match the new updates from our default light.

**Comment by misolori** [comment]
I just double checked and our built-in themes are all correct, it looks like your theme that you are using is created by someone else (I thought you were talking about our `Light (Visual Studio)` theme). I'd suggest for you to file an issue with that extension as we don't control that. Let me know if you've got any other questions.
