### ISSUE TITLE
Potential EditorInput leaks from history

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#126855]
Ran into this while exploring Interactive Window and adding hot reload support. The interactive window editor input is using a virtual scheme `vscode-interactive` and it implements an `IEditorInputSerializer`. When the interactive editor input is dirty and users reload the window, what happens then is

* On window shutdown
  * Dirty `InteractiveEditorInput` is stored in backup
  * `HistoryService` will persist the editor inputs in history. Since `InteractiveEditorInput` doesn't meet the criteria in https://github.com/microsoft/vscode/blob/4da81059653e0c0c2d61ca92da89e8b1d498afa7/src/vs/workbench/services/history/browser/history.ts#L569-L584, the input is serialized and stored, instead of just saving `resource: URI`
* Window reload
  * Restore backup, `InteractiveEditorSerializer#deserialize` is called first to restore the editor input in the editor group. An `InteractiveEditorInput` is created
  * Active editor change, will trigger `HistoryService#onActiveEditorChanged --> handleEditorEventInHistory --> ensureHistoryLoaded`. This will create another `InteractiveEditorInput ` and store it in `HistoryService#history` but we pop it out since it's the "same" as active editor.

The `InteractiveEditorInput#history` no longer holds a reference to the `InteractiveEditorInput` it restores, and no one calls `dispose` on the object, so the object will always live as long as there are listeners registered in the editor input.

**Comment by rebornix** [comment]
My attempt to fix this is https://github.com/microsoft/vscode/commit/4da81059653e0c0c2d61ca92da89e8b1d498afa7 but not sure if I should actually remove the `if` condition. @bpasero we can have an offline chat if the issue description is not clear enough (esp why it leads to leaks).

**Comment by rebornix** [comment]
The right fix is probably https://github.com/microsoft/vscode/issues/126728

**Comment by rebornix** [comment]
Reverted my changes as it might break untitled file scenario.

**Comment by bpasero** [comment]
As a workaround I suggest we add more special cases to the history to simply not persist the history for inputs of your kind. If you let me know the `typeId` to ignore, I can add it.
