### ISSUE TITLE
I have this weird terminal glitch, please someone help

### ISSUE THREAD

**Issue by mohitsrivastavazzz** [microsoft/vscode#126846]
![1](https://user-images.githubusercontent.com/71134823/122806618-2e8a6700-d2e8-11eb-9953-d43f32a02115.png)
**Whenever I run a program for the first time I get normal results in terminal**
![2](https://user-images.githubusercontent.com/71134823/122806753-58438e00-d2e8-11eb-8144-8a21cd33070f.png)
**But on the second run and on I get this weird space and things seems really off**
![3](https://user-images.githubusercontent.com/71134823/122806765-5b3e7e80-d2e8-11eb-8e58-8fefccf344ca.png)
**and then if I turn vscode to window mode and then back to fullscreen it fixes it but what's causing the **issue?**

**Comment by meganrogge** [comment]
Does changing the `terminal.integrated.gpuAcceleration` setting help?
