### ISSUE TITLE
Make line distance for creating history stop configurable

### ISSUE THREAD

**Issue by dowel** [microsoft/vscode#126830]
Does this issue occur when all extensions are disabled?: No

Question above is somewhat irrelevant code navigation only works with language specific extension.

- VS Code Version:
Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (4 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

I also tried this with insiders build. Same problem.

- OS Version: 
MacOS Big Sur 11.4

Steps to Reproduce:

1. Navigate to function or a method. 
2. Move the cursor around to a different function. 
3. Navigate back - navigation will follow cursor movement.

Searching similar issue, I found at least two bug reports:
https://github.com/microsoft/vscode/issues/92669 and https://github.com/microsoft/vscode/issues/29027
Both issues have been resolved. I genuenly wish the problem has been fixed and this is something wrong in my setup. 

As a side note, I think there is value having both modes of navigation - i.e. one that ignores cursor movement and one that does not. However, I personally find the mode that ignores cursor movement more useful. 

Thank you!

**Comment by bpasero** [comment]
> navigateBack follows cursor movement

Yes, for any language. There is no other way of navigation implemented for "Go Back", "Go Forward".

Should this be rebranded as feature request then?

**Comment by dowel** [comment]
It seems like there are two options:

1. We say that current behavior is a bug and "Go Back" and "Go Forward" should ignore cursor movement. And perhaps if there is interest in variation that follows cursor movement, we file a feature request. I am personally not interested in variation that follows cursor movement. 

2. We say that current behavior is fine and we need new variation of "Go Back" and "Go Forward" that ignore cursor movement. In this case we need a feature request. 

I am curious how people feel about this. Given the other two tickets, it seems that I am not the only person interested in that. 

The end goal seems to be having two variations of both commands. What can I do to facilitate this work?

**Comment by yume-chan** [comment]
To resolve #29027, `Go Back` and `Go Forward` commands now ignore cursor moves within 10 lines, do you want this value to be configurable? And want this configuration to accept infinity?

**Comment by dowel** [comment]
@yume-chan Yes, this seems like a good idea.

**Comment by dowel** [comment]
Not sure this is something I can do myself, but just in case, instead of waiting for VS code team to fix this, can I submit a patch with a fix myself?
