### ISSUE TITLE
C# Extension installed but visual studio code isn't detecting it

### ISSUE THREAD

**Issue by Glow-Bunny** [microsoft/vscode#126800]
When I try to run C# file, it will say "You don't have an extension for debugging C#. Should we find a C# extension in the Marketplace?" and when I click OK, it will redirect me to the C# extension which I already installed. I tried to create a launch.json but the environment doesn't show C# and if I search it, it will say "Intall extension for C#" which again will redirect me to the extention.

**Comment by weinand** [comment]
@Glow-Bunny
What platform?
What VS Code version?

What is the status of your C# extension in the extensions view? Here is how it should look:

<img width="1359" alt="2021-06-21_09-54-20" src="https://user-images.githubusercontent.com/1898161/122726933-c9e2f400-d276-11eb-96b8-b59e10308eb4.png">

**Comment by stevencl** [comment]
I'm seeing the same thing. Here's what happens on my machine:

![cannotruncsharp](https://user-images.githubusercontent.com/1704059/122912978-d471bc00-d350-11eb-85a0-61032d26c2b9.gif)


Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Also saw this on a participant's machine during a UX study yesterday.

**Comment by isidorn** [comment]
Probably dup of https://github.com/OmniSharp/omnisharp-vscode/issues/4599
Let's see what @wardengnaw has to say and if any change is needed on the vscode side
