### ISSUE TITLE
Auto detect color scheme not working after reload window

### ISSUE THREAD

**Issue by vicary** [microsoft/vscode#126823]
Issue Type: <b>Bug</b>

`window.autoDetectColorScheme` setting is not respected after running "Reload Window" from the command palette, it always fall back to whatever value in `workbench.colorTheme` after reload.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id d551408c-e011-484b-b16f-64ba39c5e720|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.0.1
markdown-mermaid|bie|1.9.2
better-toml|bun|0.3.2
mustache|daw|1.1.1
vscode-faker|dee|1.5.0
emulate|Die|1.4.0
gitlens|eam|11.5.1
prettier-vscode|esb|6.4.0
vscode-jest-runner|fir|0.4.44
graphql-for-vscode|kum|1.15.3
vscode-apache|mrm|1.2.0
hexeditor|ms-|1.7.1
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.12.12
uuid-generator|net|0.0.4
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
vscode-yaml|red|0.20.0
velocity|sod|0.2.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30323119

```

</details>

**Comment by climaxu** [comment]
great release

**Comment by aeschli** [comment]
What `window.autoDetectColorScheme` does is that when a OS color scheme change is detected, it changes the `workbench.colorTheme` to the the preferred theme: Either `workbench.preferredDarkColorTheme` or `workbench.preferredLightColorTheme`.

 OS color scheme change are detection happens while VSCode is open or if VSCode is restarted and the OS theme is different from when VSCode was closed.

So a reload will not change the theme, and also should not.

**Comment by vicary** [comment]
Do you mean that the value of `workbench.colorTheme` will be modified daily based on OS sunset schedules, hence synchronized to my other machines?

Every time I called "Reload Window" in the evening, it shows the light theme when it should be dark. So it is basically doing what it shouldn't.

Shall I attach a screen recording as a proof?

**Comment by aeschli** [comment]
Yes, it will be synchronized to other machines, which might not be what you want.

What is the settings before you click reload?

**Comment by vicary** [comment]
The only settings that is not default is `window.autoDetectColorScheme`.

When trying to reproduce this, I noticed that when launching VS Code at the evening, reloading window retains the dark theme.

It only resets to light theme upon reload if VS Code was launched in the morning and didn't closed once until evening.

**Comment by aeschli** [comment]
Sorry if I'm not familiar with this feature, is the OS switching the light/dark scheme depending on the day time? 

I know that some VS Code extensions do that, but looking at your extensions list, I don't see any related extension?

**Comment by vicary** [comment]
> Sorry if I'm not familiar with this feature, is the OS switching the light/dark scheme depending on the day time?

Yes. It usually defaults to the universal sunset of current timezone, for example [SunCalc](http://suncalc.net). Most operating systems also let you set your own daily schedule to switch your `prefers-color-scheme` twice a day.

> I know that some VS Code extensions do that, but looking at your extensions list, I don't see any related extension?

I believe it is a built-in feature, the configuration key is `window.autoDetectColorScheme`.

<img width="1057" alt="Screenshot 2021-06-27 at 3 53 02 PM" src="https://user-images.githubusercontent.com/85772/123536998-f22f8e80-d75f-11eb-8bc5-674abe09f831.png">

**Comment by rben01** [comment]
I am seeing this issue too (on a Mac). Steps to reproduce are:

1. Set computer to dark mode
2. Open VSCode
3. Enable the "Window: Auto Detect Color Scheme" setting -- you should see the window adopt the dark color scheme
4. Run VScode's "Developer: Reload Window" command
5. Wait for the window to reload

The bug is now apparent: the window has the light theme applied even though 1. your computer is in dark mode and 2. "Window: Auto Detect Color Scheme" is enabled. This bug only happens after reloading the window; the bug doesn't reproduce if you actually quit and reopen the VSCode app.

This bug can be temporarily fixed by simply unchecking and rechecking the "Window: Auto Detect Color Scheme" setting, which will get things back in sync (without needing to restart VSCode). But the bug will pop up again the next time you reload the window when your computer is in dark mode.
