### ISSUE TITLE
Open a hidden directory

### ISSUE THREAD

**Issue by muthianikev** [microsoft/vscode#126882]
Add ability to be a able to open a hidden directory (e.g. a hidden repository) as the base folder of the window explorer

**Comment by muthianikev** [comment]
The feature requested is to be able to open a "." folder. I have a ".example" folder within my "demo" folder and it does not appear on the "open folder" dialogue window. Attached are some screenshots to paint a picture.
![Screenshot 1](https://user-images.githubusercontent.com/39836985/122942826-28939500-d37f-11eb-8929-bc2286cb588f.png)
![Screenshot 2](https://user-images.githubusercontent.com/39836985/122942843-2c271c00-d37f-11eb-8f6a-476e48a709a1.png)

**Comment by isidorn** [comment]
This is a native dialog of the OS, you should be able to control on the OS level if hidden directories are shown or not.
VS Code can not fix this so closing this as no action is planned

**Comment by muthianikev** [comment]
@isidorn My OS settings allow showing hidden directories. I do not get the same problem on Pycharm. You can try replicate it and see what i mean (Ubuntu 20.04 LTS)
