### ISSUE TITLE
Built-in scss language basic lack of syntax highlight of :host-context() and other experimental pseudo-classes

### ISSUE THREAD

**Issue by nickbanana** [microsoft/vscode#126886]
Does this issue occur when all extensions are disabled?: Yes/No Yes

- VS Code Version: 1.55.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. insert experimental pseudo-class in scss like :nth-col

it lacks of syntax highlight but when same experimental pseudo-class is presented in css file it's been syntax highlighted.
Comparison in attached image

![image](https://user-images.githubusercontent.com/7685505/122878212-0fccb480-d36a-11eb-957c-fd1486917026.png)

**Comment by alexr00** [comment]
Can you please provide a full copy/pastable example?

**Comment by nickbanana** [comment]
```css
:host-context(.template_025) .custom_07 h2 span {
  font-weight: bold;
}
```

**Comment by alexr00** [comment]
Thanks! Moved to the repo where we pull our scss grammar from: https://github.com/atom/language-sass/issues/286
