### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by KurahaSho** [microsoft/vscode#126879]
Issue Type: <b>Bug</b>

I'm working with flutter, and when i open a random file (any file) the editor block the delete, i cant delete any char, with backspace or supr, i cant delete but i can write any other char.
It usually happens after opening 2 or more files, but ocassionally it happens before.
I have to close the current instance of vs code and open a new instance.

I can delete after a few minutes without close the tab.

VS Code version: Code - Insiders 1.58.0-insider (6afedfdad59d1f1ba4b614341d21c67775e158a9, 2021-06-21T05:15:13.618Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (2.20GB free)|
|Process Argv|--crash-reporter-id 1c35cf00-56ba-4224-b9ec-79d2fc243b99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-intelephense-client|bme|1.7.1
codestream|Cod|11.0.10
dart-code|Dar|3.23.1
flutter|Dar|3.23.0
blockman|leo|1.2.0
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Backspace`. When `Backspace` is acting up, could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
