### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by Mehdi-Momenpoor** [microsoft/vscode#126815]
Issue Type: <b>Feature Request</b>

hi
In the last update of VSCode, there is a problem to import modules automatically.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by judehunter** [comment]
+1, looks like using the built-in typescript version 4.3.2 causes that behavior. Switching to workplace's 4.2.4 fixes it.
