### ISSUE TITLE
FSP root folder in workspace retains '!' error indicator after successful refresh

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#126842]
Issue Type: <b>Bug</b>

1. Use an extension that implements a FileSystemProvider for which you can alter conditions so that it may or may not resolve. For example, an FTP provider connecting over a VPN that you can disable.
2. Have a workspace that uses the FSP.
3. Be able to resolve the workspace folder and see its contents.
4. Change environment state to make the target unreachable (e.g. disconnect VPN)
5. Use the 'Refresh Explorer' button. The Explorer correctly displays the root folder with a '!' indicator and colour, plus a hover tip saying 'Unable to resolve workspace folder'
6. Change environment state to make the target reachable again (e.g. connect VPN)
7. Use the 'Refresh Explorer' button.

:bug: the root folder retains its error indicator, colour and tip even though the folder now resolves and expands.

I will submit a PR

VS Code version: Code - Insiders 1.58.0-insider (6afedfdad59d1f1ba4b614341d21c67775e158a9, 2021-06-21T05:15:13.618Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
@isidorn this is in the same area as #122004 which was assigned to you.

**Comment by isidorn** [comment]
Thanks for the issue. However I just came back from vacation and have limited time this milestone, thus I am pushing this out to July for now.

**Comment by gjsjohnmurray** [comment]
Fair enough, but I'd been hoping to continue my run of having at least one PR in every release since October 2020, and this bug has been affecting users of a couple of extensions I work on 😞

**Comment by isidorn** [comment]
Hehe that's a good reason. If I find time I will try to tackle it this week, but no promises...

**Comment by isidorn** [comment]
Whole milestone I was on vacation -> moving to August to merge in hopefully start of next wek.

**Comment by isidorn** [comment]
Adding bug label so we verify this this milestone.
@gjsjohnmurray also once there is an insider end of this week with this change it would be great if you try it out. Thanks!
