### ISSUE TITLE
welcome.showNewEntries ctrl+alt keybinding warning

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#126816]
![image](https://user-images.githubusercontent.com/2193314/122755798-5dea9680-d24a-11eb-8df2-3a59f1bca9eb.png)

**Comment by Tyriar** [comment]
@JacksonKearl I don't think that commit fixes it? That's still ctrl+alt+ on windows https://github.com/microsoft/vscode/commit/60ad49e4dce16291018e8f02438769ab54b5bc89

**Comment by JacksonKearl** [comment]
Code seems to say it's fine so long as metaKey (same as winCtrl on non-macOS) is present. 
https://github.com/microsoft/vscode/blob/596a96ec7a5ccf417b1ba2ee630f4aff64ee7fa5/src/vs/platform/keybinding/common/keybindingsRegistry.ts#L211

**Comment by Tyriar** [comment]
@JacksonKearl isn't ctrlKey === winCtrl on non-macOS?

**Comment by JacksonKearl** [comment]
I see it as:
```ts
	const ctrlCmd = (keybinding & BinaryKeybindingsMask.CtrlCmd ? true : false);
	const winCtrl = (keybinding & BinaryKeybindingsMask.WinCtrl ? true : false);
	const shiftKey = (keybinding & BinaryKeybindingsMask.Shift ? true : false);
	const altKey = (keybinding & BinaryKeybindingsMask.Alt ? true : false);

	const ctrlKey = (OS === OperatingSystem.Macintosh ? winCtrl : ctrlCmd);
	const metaKey = (OS === OperatingSystem.Macintosh ? ctrlCmd : winCtrl);
``` 

Which would imply `ctrlKey === winCtrl` *only* on macOS. And including both `ctrlCmd` and `winCtrl` means both `ctrlKey` and `metaKey` are true on all platforms. 


https://github.com/microsoft/vscode/blob/7bbc15a60e0adfdeae901bf149f56c72c83a9a65/src/vs/base/common/keyCodes.ts#L433-L439
