### ISSUE TITLE
It is extremely hard to move the mouse into a custom tooltip of a status bar item to click a command

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#126888]
The custom hover offers the ability to add clickable commands. However it is extremely hard to move the mouse into it. In 99% of the cases the tooltip disappears before the mouse can make its way into it.

<img width="341" alt="capture" src="https://user-images.githubusercontent.com/1931590/122881691-b6e62780-d33b-11eb-8d86-532d1e63d084.png">

**Comment by Tyriar** [comment]
This is because I shifted it up to improve the alignment, didn't realize there were links in some
