### ISSUE TITLE
Panel should close when no group terminals remain

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#126840]

**Comment by Tyriar** [comment]
Repro:

1. Open 2 terminals
2. Drag the bottom terminal to the editor
3. Close the terminal editor via the `x` tab button
4. Close the panel terminal by clicking on the inline tab and hitting kill

![image](https://user-images.githubusercontent.com/2193314/122819017-ba6fa500-d28e-11eb-8efd-5935cda20ee0.png)

**Comment by meganrogge** [comment]
Noticed this also happens when there actually should be terminals in the panel. For example, clicking the plus button will result in the panel displaying 2 terminals when formerly it was blank like this.
