### ISSUE TITLE
Options to put projects in explorer as separate sections

### ISSUE THREAD

**Issue by sonhanguyen** [microsoft/vscode#126872]
When you open multiple projects, they are put into the same "section" in explorer, with shared scrollbar. It becomes frustrating if you frequently have to alternate between 2 file trees because you have to scroll pass the first project to get to the second.

It would be better if there was a setting that allows each project to appear as an independent section, with its own scrollbar.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
