### ISSUE TITLE
ConsoleApp template error with DotNet SDK 5.0.300

### ISSUE THREAD

**Issue by regolas** [microsoft/vscode#126851]
Issue Type: <b>Bug</b>

Create a new ConsoleApp - dotnet new console
type dotnet run - Errors with CSPROJ in use
restart VS Code
type dotnet run
Following error occurs - 
C:\Code\consoleCurLoad>dotnet run
System.ComponentModel.Win32Exception (193): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

dotnet build and dotnet restore report no errors

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.54GB free)|
|Process Argv|--crash-reporter-id 76df2635-ca30-4301-99ca-ae16a119dd9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
csharp|ms-|1.23.12
mssql|ms-|1.10.1
debugger-for-chrome|msj|4.12.12
indent-rainbow|ode|7.5.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30324779
binariesv615:30323119

```

</details>

**Comment by meganrogge** [comment]
what happens if you try this in an external terminal?

**Comment by regolas** [comment]
Not getting notifications from Github. Sorry for delay. 
Running from external terminal makes no difference

**Comment by Tyriar** [comment]
It looks like you downloaded the wrong architecture binary for your machine, regardless you would want to follow up with the .NET team not us
