### ISSUE TITLE
Connection refused debugging extension host

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#126826]
Issue Type: <b>Bug</b>

* pull latest
* build using `yarn watch`
* select VS Code as launch target
* press `F5`

![image](https://user-images.githubusercontent.com/5047891/122771380-aa63bf80-d2a6-11eb-8cf9-46741f10fa82.png)

VS Code version: Code - Insiders 1.58.0-insider (6afedfdad59d1f1ba4b614341d21c67775e158a9, 2021-06-21T05:14:03.949Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by connor4312** [comment]
I notice now that you're paused while the renderer is starting up, before the extension host was actually launched, so this resulted in a timeout when trying to attach to it. I think we should just have an infinite timeout here -- it's quite expected that VS Code developers might work on things that happen before the extension host exists.

**Comment by connor4312** [comment]
I notice now that you're paused while the renderer is starting up, before the extension host was actually launched, so this resulted in a timeout when trying to attach to it. I think we should just have an infinite timeout here -- it's quite expected that VS Code developers might work on things that happen before the extension host exists.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/commit/fd14f3ebc07f338d785979fd4fb01b3692a9e8b3
