### ISSUE TITLE
Cannot install tools such as goreturns, golint, guru, gorename

### ISSUE THREAD

**Issue by TarasLavrenyuk** [Microsoft/vscode#12681]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 3.19.0-58-generic

Steps to Reproduce:

1. 
2.

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go
