### ISSUE TITLE
After installing 1.57, executing Terminal while connected to remote server gives "execvp(3) failed. permission denied vscode"

### ISSUE THREAD

**Issue by yakumoklesk** [microsoft/vscode#126806]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Install version 1.56. Test remote connection. Then upgrade to 1.57
2. Running terminal when connected to remote, should fail with "execvp(3) failed. permission denied vscode"

The only thing that I can have that may affect to the run of the "bash" comand, is the contents of the .bashrc, that uses another files to source them, like .git_bash_prompt, to control a prompt showing git statuses.

**Comment by meganrogge** [comment]
Are you in a trusted workspace?

**Comment by yakumoklesk** [comment]
Yes, I am in a trusted workspace. I suspect, (but I have not checked yet), that the problem is that the .bashrc calls others scripts, like the git_bash_prompt, which defines some extra environment variables and may do some other work that might cause a failure due to execution outside the workspace. My check would be just to not source any other external script from my basic .bashrc and check that this works. At the moment I am sticking wiht 1.56.2, because I have some urgent work to do. Whenever I check this, I'll post it here.
