### ISSUE TITLE
split/kill on terminal panel should only disappear when inline actions are on tabs 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#126847]
so that we never encounter the state without buttons
![recording (1)](https://user-images.githubusercontent.com/29464607/122807624-a91f9c00-d280-11eb-8fb8-d3907e58818d.gif)

**Comment by Tyriar** [comment]
Not sure it's worth this level of granularity since you can use `"terminal.integrated.tabs.showActions": "always"` and we'd need to add yet another context key?

**Comment by meganrogge** [comment]
What do you think @Tyriar ?

**Comment by Tyriar** [comment]
This will be more work than it's worth imo, if users want the buttons they can use narrow or increase the width slightly
