### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by yahyaefendy** [microsoft/vscode#126884]
I open my vscode, but this error for me "Extension host terminated unexpectedly"
I try close and open again, but this return problem

- VS Code Version: 1.57

**Comment by alexdima** [comment]
@yahyaefendy Does this reproduce when disabling all extensions? `F1 > Developer: Reload With Extensions Disabled` ?

**Comment by yahyaefendy** [comment]
@alexdima i can try

> F1 > Developer: Developer: Reload With Extensions Disabled

But i had same problem

**Comment by alexdima** [comment]
@yahyaefendy Can you please open developer tools from the menu `Help > Toggle Developer Tools` and share the contents of that when the extension host crashes? Also, what OS are you on?
