### ISSUE TITLE
Insanely slow dev experience

### ISSUE THREAD

**Issue by Manubi** [microsoft/vscode#126922]
Vscode is getting that slow that I can't work anymore. Meaning I am experiencing a typing delay of +1.0 seconds. The more you type the bigger the delay becomes. 

It's the Code Helper Renderer if I look at the activity monitor that runs crazy.

Does this issue occur when all extensions are disabled?: Yes. I suspected that the Vim-plugin would be the problem, but with every plugin disabled the problem still exists. 
- VS Code Version:  1.57.1 I also downgraded to version 1.56.2 but same bug.
- OS Version: macOS Big Sur v11.4

If I look at the Process Explorer I can see the tsserver.js go up above 150% cpu. I am working on a next.js app and create-react-app with typescript. 

I just did a test and wrote some lines in a .txt file. Which works fine. 
Did another test with using vim and .mdx which also works fine. 

So I get the impression that something is going on with tsserver.js an server.js. Any ideas? Even the Settings lag, if I am inside a typescript/javscript project.

Steps to Reproduce:
I honestly don't know how to reproduce it. 

Any other tips I can try?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also does it happen in all projects or just one in particular?

**Comment by Manubi** [comment]
Hey,
I didn't try to fix it anymore but I had the problem with all extensions disabled. What I think was the problem, the temperature here in Austria got to high (+30C) and the macbook couldn't handle it anymore. Which is a bit wired as it is a mac pro 2.6GH 6-core intel core i7 with 32 gig ram. 

The problem is kinda gone if it's not to warm. 🙄

**Comment by mjbvz** [comment]
Were other apps similarly slow when this was happening?

**Comment by Manubi** [comment]
No.

**Comment by mjbvz** [comment]
If you are still seeing the issue, please collect the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 


 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
