### ISSUE TITLE
Opening multiple windows on startup

### ISSUE THREAD

**Issue by Rajdeep2121** [microsoft/vscode#126951]
When I open a new vscode session, multiple windows open with my previous projects loaded. This is an issue as it opens multiple unwanted previous projects. 

Pls fix

**Comment by bpasero** [comment]
Can you see if https://github.com/microsoft/vscode/issues/126725 applies?

**Comment by Brian-M-Lopez** [comment]
i'm having the same issue and couldn´t solve it. Vs code opens 4 empty windows when ever i open vs code or a proyect, this is happening over 2 weeks now
