### ISSUE TITLE
Editor tabs are not refreshed with changes leading to misleading updates

### ISSUE THREAD

**Issue by Shahid-Roofi-Khan** [microsoft/vscode#126955]
Issue Type: <b>Bug</b>

When you do a git pull, files are updated, however opened tabs don't refresh or don't even show that files could have been updated.

This can lead to disaster because you will be editing older verson of file and when you update, you will loose all the important changes from git PULL !!!!

This does not happen in Visual Studio.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.72GB (9.48GB free)|
|Process Argv|--crash-reporter-id 1addf5e8-22f8-41a7-8c9e-6337590961d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|15.41GB (14.15GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|Memory (System)|15.41GB (14.15GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
troff|ban|1.0.22
bracket-pair-colorizer-2|Coe|0.2.1
algorithm-mnemonics-vscode|dav|1.0.3
selinux-policy-languages|Goo|0.1.0
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.6
autoconf|mae|0.1.0
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
propertylist|zho|0.0.2
c-cpp-runner|fra|0.17.1
cpptools|ms-|1.5.0-insiders2
makefile-tools|ms-|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

**Comment by aeschli** [comment]
re you working on a Windows mount? (`/mnt/....`)?
