### ISSUE TITLE
Allow one color theme per vscode instance

### ISSUE THREAD

**Issue by SylvainFI** [microsoft/vscode#126993]
Hi,

I'd like to have a better way to identify vscode instances. Often I can't distinguish projects at first glance when alt-tabbing. Plus having a single (but still big 34") screen doesn't help as I have to move windows frequently.

Currently, changing the color theme changes it for all the open vscode instances.

Feature request: changing the color theme only changes the current instance (or all instances through option).

Thank you!

**Comment by IllusionMH** [comment]
VS Code allows to apply `workbench.colorCustomizations` in workspace settings and [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extensions makes it even easier.

**Comment by aeschli** [comment]
Thanks @IllusionMH , that's the answer.
