### ISSUE TITLE
Code is already running over and over again.

### ISSUE THREAD

**Issue by leet0rz** [microsoft/vscode#126947]
This was reported back in 2020 but it is still an issue, after running codes for a little while vscode will tell the user that the code is already running over and over even though its not running forcing us to shut down the terminal.

- VS Code Version: Newest

Steps to Reproduce:

1. Run code a few times

**Comment by meganrogge** [comment]
I can't reproduce this. Please include a gif (https://gifcap.dev/)

**Comment by leet0rz** [comment]
[image: recording.gif]

**Comment by meganrogge** [comment]
That upload did not work

**Comment by leet0rz** [comment]
![recording](https://user-images.githubusercontent.com/29175192/123822411-8c2c3e00-d8fc-11eb-9e10-27c85c79c22b.gif)
