### ISSUE TITLE
Unexpected prompt to reload for Pylance after installing Python

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#126930]
- VS Code Version: v1.57

(Focusing this issue on the Pylance error notification)

Steps to Reproduce:

1. Install Python from a recommendation prompt to make a python file work
2. Got a Pylance error that asks me to reload.

![image](https://user-images.githubusercontent.com/8599/122974613-6674c700-d347-11eb-90e3-accecdc7ce9a.png)

**Expected**: There should be one prompt when installing one or many extensions requires a reload. "Pylance" comes without context for new users. The user got never told that "Python" is actually an extension package.

**Comment by isidorn** [comment]
Yeah this is bad flow that makes me sad.
I can reproduce when I take a fresh user data dir and just install python.

Shouldn't everything just work here. I opened a python file, python extension gets activated, and if pylance is depending on Python it should activate after it, right @sandy081 
Or is it a strange dependency cycle that the python extension does?

I see the error is coming from here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/browser/mainThreadExtensionService.ts#L103

**Comment by digitarald** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/124870
