### ISSUE TITLE
Update Emmet to be compatible with v 2.2.0

### ISSUE THREAD

**Issue by RedX2501** [microsoft/vscode#126963]
I'd like to ask if it possible to update the emmet plugin to support Emmet v2.2.0. This version brings a new feature that allows to reference previous repeater.

See this Stackoverflow question on why it's useful: <https://stackoverflow.com/questions/24202111/can-you-retain-number-value-across-generated-siblings-with-emmet-in-sublime-text>
and the commit: <https://github.com/emmetio/emmet/commit/03748b1100da7c0a7dc0bd3afa519d621bb78635>

**Comment by rzhao271** [comment]
Emmet v2.2.0 should already be merged in. Are you using the latest version of VS Code?
If yes, can you paste an example snippet that is not working?

**Comment by RedX2501** [comment]
It seems to be available and my error was copying the wrong example from the emmet commit I linked. Sorry about that.

Btw I'm using version 1.56.2 in case anybody else is wondering.
