### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by evtu-cmck** [microsoft/vscode#126977]
Issue Type: <b>Bug</b>

Slow  repsonse to keys

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.75GB free)|
|Process Argv|--crash-reporter-id e1406b7d-1b27-442e-8170-c24b4a6ee6b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
azure-pipelines|ms-|1.188.1
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.0
vscode-bicep|ms-|0.4.63
vscode-cosmosdb|ms-|0.16.0
csharp|ms-|1.23.12
vscode-dotnet-runtime|ms-|1.1.0
mssql|ms-|1.10.1
remote-wsl|ms-|0.56.5
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.1
debugger-for-edge|msj|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by rebornix** [comment]
@evtu-cmck can you provide more details? Do you reproduce the issue if disabling all extensions/
