### ISSUE TITLE
Find widget text invisible when text box is in focus

### ISSUE THREAD

**Issue by BobMoirIGT** [microsoft/vscode#126984]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0-insider
- OS Version: Windows_NT x64 10.0.19042

The text field for the find widget does not show any text while it is in focus. Clicking away from the widget will show the text again.

Steps to Reproduce:

1. Open any text file.
2. Press ctrl+F to bring up the widget
3. Type some text into the "find" or "replace" text fields
4. Result: No text is shown
5. Click away from the search bar
6. Result: The text appears.

![image](https://user-images.githubusercontent.com/60506799/123081406-d6518300-d415-11eb-8c12-3b10e0a7f928.png)

![image](https://user-images.githubusercontent.com/60506799/123081464-e36e7200-d415-11eb-8aff-85a5e378503c.png)

**Comment by gjsjohnmurray** [comment]
/duplicate

Are you using the latest Insiders?
```
Version: 1.58.0-insider (user setup)
Commit: 9744231fc12f1aed21089180b3f0394d694bd2a2
Date: 2021-06-23T05:13:08.071Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0

```
