### ISSUE TITLE
Rename `variable.other.enummember` to `variable.other.enum-member`

### ISSUE THREAD

**Issue by 4086606** [microsoft/vscode#126957]
Rename `variable.other.enummember` to `variable.other.enum-member` would be nice.
The hyphenation is a Textmate convention that makes it much more readable.

**Comment by 4086606** [comment]
Some of your extension grammars use `variable.other.enummember` to highlight enum members in Textmate. That doesn't fit [Sublime](https://www.sublimetext.com/docs/scope_naming.html) and [Textmate](https://macromates.com/manual/en/language_grammars#naming_conventions) conventions, which use a hyphen to separate words in a token subtype

**Comment by 4086606** [comment]
We will need to contact [extension code owners](https://github.com/search?p=3&q=variable.other.enummember&type=Code) if this feature goes through. I am happy to co-ordinate such work

**Comment by alexr00** [comment]
We get all of our grammar from other OSS repos and just pull the grammar into this repo. This change would need to be adopted in each of those repos, all of our built-in themes, and all extension authors who make a theme.

**Comment by 4086606** [comment]
Alright. Bit of a bummer but the concern for extension compatibility is great to see
