### ISSUE TITLE
Python Notebook can't open:  infinite loop

### ISSUE THREAD

**Issue by FlorianG-dev** [microsoft/vscode#126904]
Issue Type: <b>Bug</b>

Hello VS Code team, 

Since the last update I'm not able to open any python notebook (ipynb). 
I've found a similar situation here : https://stackoverflow.com/questions/63856340/vs-code-cant-open-ipynb-file
My issue is exactly what is described. 
---
I've unistalled and reinstalled VSC and each extension individually, nothing changed. 
---
Visual code version : the last one (I've just checked update) 
ms-python.python installed in VSCODE : v2021.6.944021595
ms-toolsai.jupyter version installed in VSCODE : v2021.6.999406279
ms-python.vscode-pylance installed in VSCODE : v2021.6.2

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.92GB (13.66GB free)|
|Process Argv|--crash-reporter-id 024c1bf0-f233-431a-9cd1-deebb1f2966b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30323119

```

</details>

**Comment by rebornix** [comment]
@FlorianG-dev can you check if you have `workbench.editorAssociations` in your user setting?
