### ISSUE TITLE
Plugins not working if open vscode NOT from terminal

### ISSUE THREAD

**Issue by Loggy** [microsoft/vscode#126991]
Issue Type: <b>Bug</b>

- open vscode from Applications folder
- see plugins such as Prettier, Activitus Bar, GitLense etc., not working

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.46GB free)|
|Process Argv|work/3c-rnd/gridex --crash-reporter-id ec4bf259-0491-4573-b3f6-32ed73c9f920|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-apollo|apo|1.19.3
rails|bun|0.17.3
vscode-gemfile|bun|0.4.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.6
activitusbar|Gru|0.0.46
vscode-styled-components|jpo|1.6.4
rust-doc-viewer|JSc|2.0.1
solidity|Jua|0.0.121
haml|kar|1.3.1
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
ruby|reb|0.28.1
rust|rus|0.7.8
slim|sia|0.1.2
pretty-json|sup|0.0.4
tabnine-vscode|Tab|3.4.9
even-better-toml|tam|0.12.3
jump-to-alias-file|wan|1.0.9
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
vscextlangct:30322307
binariesv615:30325510

```

</details>

**Comment by meganrogge** [comment]
any errors in the dev tools console?
