### ISSUE TITLE
Can not open file after rename in mac OS case sensitive filesystem

### ISSUE THREAD

**Issue by tongjun741** [microsoft/vscode#126945]
Issue Type: <b>Bug</b>

Rename file from "CreateForm.tsx" to "createForm.tsx" in left resource manager，then I can not open this file。I have change the first letter of this file only。 

OS: mac OS 10.14.6 (18G6032)

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (12.00GB free)|
|Process Argv|--crash-reporter-id 28b5c527-b8c2-4b75-933b-ec168329770e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.13.0
vscode-eslint|dba|2.1.23
vscode-language-pack-zh-hans|MS-|1.57.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

![image](https://user-images.githubusercontent.com/6827111/123023414-e95e5600-d409-11eb-97d8-43e8660f8c7d.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
