### ISSUE TITLE
Bash terminal scroll bar

### ISSUE THREAD

**Issue by sbrickner** [microsoft/vscode#126900]
Using the bash terminal after the update for splitting terminals (should be optional btw) there is no longer a scroll bar. Steps to reproduce would be just to open the terminal and do something like npm install that would make the window require a scroll bar.

**Comment by Carbaz** [comment]
Noticed the same, I guess, bug; to be more detailed:

* When terminals panel is on the bottom:

  When you split terminals only the rightmost one of them retains its  **vertical scrollbar**.
  All them have the ability to scroll up and down using mouse wheel, just the slider is gone.
  Once leftmost terminal is closed or a new one is created, next/new rightmost one gets the slider.

* When terminals panel is on the side, left or right no matters:
  None of them have a vertical scrollbar, no matter they are splitted or not.

Showing or not *Tabs* makes no difference.

Reproduce:  As said, any command with a long output, as `ls -R`, then play with splits and/or panel positions will reproduce.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
