### ISSUE TITLE
Terminal with Remote - SSH is terribly slow for some outputs

### ISSUE THREAD

**Issue by dharrington** [microsoft/vscode#126937]
Does this issue occur when all extensions are disabled?: Yes/No

No, it requires the Remote-SSH extension

- VS Code Version:
- 1.57.1
- OS Version:
Linux 5.10.28
Steps to Reproduce:

1. Connect to a remote SSH host
2. Maximize the terminal (it's slower with a larger pane)
3. Configure git to use the 'delta' pager: https://github.com/dandavison/delta
3. Navigate to a git repo, and do:> git show (some commit hash with a bunch of diffs)

It takes almost 5 seconds to scroll a single page. 

Some things to note:
* A gnome-terminal SSH-ing to the same host can scroll a page with no visible delay. 
* A local vscode terminal session doesn't seem to have the same problem.
* Paging through a diff without the 'delta' pager is only a bit sluggish in comparison.

**Comment by meganrogge** [comment]
Did this performance issue start happening recently?

**Comment by dharrington** [comment]
I just tested some old versions. It's always been a bit sluggish, but 1.54.0 and before was significantly faster than 1.55.0

**Comment by dharrington** [comment]
Changing terminal.integrated.gpuAcceleration from the default value(auto?) to "on" speeds things up considerably.

**Comment by Tyriar** [comment]
There is also the new `canvas` value you can set that to in the upcoming version to see if that helps. Looks like you've worked around the problem though, it was likely due to a linux/chromium/driver problem.
