### ISSUE TITLE
Missing title bar and menu bar

### ISSUE THREAD

**Issue by rmdelossantos** [microsoft/vscode#126983]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows 10

Steps to Reproduce:
What I did before this occurred.
1. Open a new window
2. Close the previous window of VS Code
2. Open Folder

![image](https://user-images.githubusercontent.com/26576675/123079296-60b5d900-d44e-11eb-95c8-27570c3b54f4.png)

**Comment by sbatten** [comment]
Is it a persisted issue? Unfortunately I cannot repro with the above steps. Can you please try launching code from command line:

With fresh user settings:
`code-insiders.cmd --user-data-dir C:\Users\lenovo\Desktop\user1`

With no extensions:
`code-insiders.cmd --extensions-dir C:\Users\lenovo\Desktop\ext1`

**Comment by rmdelossantos** [comment]
I tried uninstalling and reinstalling a few hours ago and it didn't work. Nevertheless, I tried it again and it fixed the problem. Still don't know what was the cause but I think we can close this. Thank you.
