### ISSUE TITLE
Builtin TypeScript Extension Slow Performance and Crashes

### ISSUE THREAD

**Issue by agrattaqrypt** [microsoft/vscode#126934]
Issue Type: <b>Bug</b>

The builtin JS/TS extension frequently crashes and restarts for no apparent reason. When it isn't crashing, my relatively small TypeScript project takes 5 seconds or more to load intellisense results. 

I've tried disalbing ESLint and other extensions, opening this project both locally and remote, changing around .tsconfig settings, installing VS Code Insiders edition, etc. Nothing seems to improve performance except reducing my project to a single file with a few lines of code. (There are maybe 20-30 relatively small files in my project normally).

I have a 16-core machine with 64 GB of RAM, so there should be no performance issues whatsoever. When running in my dev container, the com.docker.hyperkit process is what shows up as over 100% CPU utilization. When running locally on the host, it is the VS Code Helper (Renderer) that shows over 100% CPU utilization.

I attempted to enable TS Server performance tracing ("typescript.tsserver.enableTracing": true), but couldn't find any documentation on where to find the trace file.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (28.58GB free)|
|Process Argv|--crash-reporter-id 1ad900db-7ca2-415f-a351-33a08f9b1272|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: container-files|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (8 x 3200)|
|Memory (System)|7.77GB (2.67GB free)|
|VM|0%|
</details>

**Comment by agrattaqrypt** [comment]
Update: I was able to greatly improve performance by deleting some of my code and then closing and reopening VS Code. Restoring my original code did not degrade performance.

Note that I had previously restarted the TS Server, reopened VS Code, and even installed a fresh copy of VS Code Insiders with no improvement to performance. I shouldn't need to temporarily delete code to fix performance issues.

This indicates to me that there must be some sort of cache that got cleared when reopening the project without some files. Either that or I just got lucky.

**Comment by luisoc2** [comment]
I have the same issue. I enabled the tsserver tracing and I found his line multiple times in the Log(Shared) output

`[2021-06-24 22:45:25.627] [sharedprocess] [warning] Resolved variables received without matching request 18006
`

There is one of this line every second

**Comment by mjbvz** [comment]
Can you share the project the causes this (or at least a stripped down version)?
