### ISSUE TITLE
Let users pick from installed debuggers before sending them to the Marketplace

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#126962]
Simulate the scenario:
> user has an installed debugger (that wasn't updated to include a "language" contribution) by pressing F5 on a single file and without a launch.json 

with these steps:

- use Mock debug project
- remove the `"languages": ["markdown"],` contribution from package.json
- launch Mock debug with F5
- in new window remove the `.vscode/launch.json`
- open `test.md`
- press F5

Observe:
<img width="1046" alt="2021-06-23_09-17-06" src="https://user-images.githubusercontent.com/1898161/123055512-45bf7680-d406-11eb-824d-7ee6af2b6479.png">

Previously we would get the "debug environment" Quickpick in this situation (which IMO makes more sense).

I suggest the following:
- as a fallback use the `breakpoints` contribution in a debugger's package.json as a strong indication for whether the debugger can handle the file type, and if that doesn't help
- show a debugger Quickpick to let the user select one of his debugger extensions, and only if there is none let the user search on the Marketplace (IIRC this is more or less the old behavior).

**Comment by isidorn** [comment]
I like your idea to use the `breakpoints` as hint.
So I went with that, in short: 
* if we can set breakpoints in the current file we behave as before (show a debugger Quickpick)
* If we can not -> we have the new "Marketplace" dialog (in this case I do not want to show the quick pick first to make the flow simple)

Try it out and let me know what you think. Thanks

**Comment by connor4312** [comment]
Hmm, I followed Andre's suggested steps:

1. Installed mock debug
2. Removed the `languages` from its package.json
3. Reloaded, verified I could set breakpoints, F5'd, then got this dialog:

![](https://memes.peet.io/img/21-07-258c5045-b95a-4b50-855c-bf9c00902f09.png)

Am I doing something differently?

**Comment by isidorn** [comment]
@connor4312 good catch. I made a rookie mistake. Pushed a fix and verified it is good now. Thanks!
