### ISSUE TITLE
Replace/Find - text not visible

### ISSUE THREAD

**Issue by LeonFretter** [microsoft/vscode#126968]
Issue Type: <b>Bug</b>

The text in the replace-panel and the rind-panel is not visible while typing.
Once leaving the input-field it becomes visible again.

![image](https://user-images.githubusercontent.com/40633983/123060215-d304ca00-d40a-11eb-8df6-1f6c0a8ef712.png)

As you can see I have "InventoryComponent" entered inside the input-field, but while I am inside that field, the text is not visible.

The bug also occured when I tried starting with --disable-extensions

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:15:45.422Z)
OS version: Linux x64 4.19.0-17-amd64 snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 1529)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.68GB (10.08GB free)|
|Process Argv|--no-sandbox ../ --crash-reporter-id 19f1e032-02d3-43eb-b007-e6d02f0242db|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.19.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.7.960048241
cpptools|ms-|1.4.1
platformio-ide|pla|2.3.2
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by yume-chan** [comment]
Duplicate of #126896

**Comment by LeonFretter** [comment]
sorry, didn't find that one on a google-search. Closing then.
