### ISSUE TITLE
Icon alignment is different now

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126965]
**Stable:**

![image](https://user-images.githubusercontent.com/900690/123059369-fed38000-d409-11eb-8de6-fa7ae5f1d52b.png)

**Insiders**

![image](https://user-images.githubusercontent.com/900690/123059410-0a26ab80-d40a-11eb-8cbf-a0558d9ea5d9.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/commit/b459881b36f0db01cd88aefb1300c714ad114ae0

**Comment by joaomoreno** [comment]
cc @eamodio
