### ISSUE TITLE
File > Revert File should be disabled for untitled schemes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126999]
Because that is a no-op.

**Comment by bpasero** [comment]
//cc @isidorn for how I use context keys, I gave it a brief test and it seems to work fine

**Comment by isidorn** [comment]
This looks good.
However I am not 100% sure @alexdima supports `A or (B and C)`
I believe some time ago for this to work it must have been decomposed into `(A or B) and ( A or C)`

**Comment by alexdima** [comment]
The distribution is done in code in `ContextKeyExpr.and`, so this should work fine. This distribution was introduced via https://github.com/microsoft/vscode/commit/350a3c69f5bf38c58bfcf6ffe4da0faa7a8fd591

**Comment by lramos15** [comment]
File > Revert File is still enabled for untitled schemes

**Comment by bpasero** [comment]
It looks like the `ResourceContextKey` cannot really be used globally.

**Comment by isidorn** [comment]
@bpasero yeah, that one depends on the explorer focus. I should have caught this earlier...
