### ISSUE TITLE
XML attribute associated to wrong type from XSD

### ISSUE THREAD

**Issue by Nerpson** [microsoft/vscode#126998]
Issue Type: <b>Bug</b>

I created an XML schema containing a complexElement with two attributes. The first one is just a simple string, the second one has a custom simpleType inheriting from string but having an additional minLength=1 restriction.

When trying this schema, the first attribute is wrongly associated to the second's custom type.

You can easily reproduce this issue with the linked ZIP archive. It contains a simple schema and an XML file using it and having the described issue.

[VSCode_XSD_Bug.zip](https://github.com/microsoft/vscode/files/6702363/VSCode_XSD_Bug.zip)

In `test.xml` you'll see that two errors are highlighted where only one should exist, on the `Some_Restricted_Value` attribute.
![image](https://user-images.githubusercontent.com/9705025/123110044-06ac1800-d43c-11eb-9ec3-25b45b0c0d09.png)

The helper popup even tells the wrong type.
![image](https://user-images.githubusercontent.com/9705025/123110352-4ecb3a80-d43c-11eb-814a-d7842b7d9928.png)

When writing a value in the restricted attribute, both of the errors disappear.
![image](https://user-images.githubusercontent.com/9705025/123111347-209a2a80-d43d-11eb-9523-fb9ef67aaf07.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.19GB free)|
|Process Argv|--crash-reporter-id 911c2726-6c6e-4a5a-ae4b-433ecadb690e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30324779
binariesv615cf:30323120
vsccppwt:30322536

```

</details>

**Comment by aeschli** [comment]
The XML validation must come from an extension, as we don't provide that out-of-the-box.

Are you sure you have no extensions installed?

Maybe https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml ?

**Comment by Nerpson** [comment]
Indeed, I disabled every extension to test it out but the "Reload required" was not shown to me or some reason. I'll redirect the issue to Red Hat.

**Comment by Nerpson** [comment]
See https://github.com/redhat-developer/vscode-xml/issues/524 for people interested in this issue.
