### ISSUE TITLE
Editor override: opening same input does not pass options in

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#126923]
Steps to Reproduce:

1. uncomment https://github.com/microsoft/vscode/blob/be2ddfaad6db9a87de5ddc40f838b3456cf2f267/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L977-L977
2. run smoke tests
3. they fail

Another way to reproduce:
* open an editor
* focus terminal
* bring up quick open and select the top editor in the list

=> focus remains in terminal

I think the reason for this is that somewhere in the code when `override` is defined, we no longer call [`setOptions`](https://github.com/microsoft/vscode/blob/f2b1f78ad45d5b19fe220e4533356efb31f4dcc1/src/vs/workbench/browser/parts/editor/editorPane.ts#L134-L134) on a pane.

**Comment by bpasero** [comment]
Actually it is different, I am not even seeing `openEditor` being called in that case.

**Comment by bpasero** [comment]
@lramos15 please have a look at the change, it seems to work nicely and does what we had previously: if the editors match, just pass them into the group.

**Comment by lramos15** [comment]
Well now that we use untyped inputs it would create a typed input and pass it in. Although I'm not sure how this flow would work in the untyped case since we wouldn't be passing typed editor inputs forward into the override service.

**Comment by bpasero** [comment]
I am not sure I understand your last comment, is there an issue with that?
