### ISSUE TITLE
Code not respecting the suggestion delay and parameter hint settings

### ISSUE THREAD

**Issue by dgh1000** [microsoft/vscode#126956]
Issue Type: <b>Bug</b>

This issue shows for me in editing C++ files. However, when I filed it on the C++ Intellisense extension issue tracker, I was told it's a VS Code issue and it repros on TypeScript as well. 

I'm on Mac using clang with the C++ Intellisense extension. In the Code settings, I specified a suggestions delay of 2000 ms and turned off parameter hints. Yet there are at least two situations in which suggestions appear immediately and parameter hints appear immediately as well even though I've turned them off.

Note that I find both immediate suggestions and parameter hints intrusive. There's a perfectly good solution possible with suggestions which is to default to not showing them, but you can force them to show up with ctrl-space. With this solution you get the best of both worlds.

One situation I'm reporting is when I type a field of a struct or class. Let's say the struct is `foo` with fields `x` and `y` I create a `foo` variable named `f`. I type `f.` and as soon as I type the period, a list of suggested completions appears as well as a parmeter hint box.

The other case is when I typing an `#include` file name. Right after typing `#include <` a list of completions and a parameter hint both appear.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id 27fb3f16-f2a8-4227-a414-59f8fe52e689|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
cpptools|ms-|1.5.0-insiders2
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
java|red|0.79.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by jrieken** [comment]
> I type f. and as soon as I type the period, a list of suggested completions appears as well as a parmeter hint box.

There is two settings for automatic triggering of suggestion

* `editor.quickSuggestions` which is about suggestions when typing at word ends
* `editor.suggestOnTriggerCharacters` which about suggestions when hitting extension defined characters

You need to turn off both when you want to disable automatic completions entirely

**Comment by dgh1000** [comment]
Well, I don't want to turn them off completely. I want Code to respect the suggestion delay. By the way, this is defective behavior. It respected the suggestion delay with `#include` lines previously. I also consider that I'm reporting a defect. If VS Code has a quick suggestions delay, then why is it not following it in some situations? It should follow it in all situations.

**Comment by dgh1000** [comment]
I'm also reporting that parameter hints show even after I've turned them off completely. This is also a bug or at least defective behavior.
