### ISSUE TITLE
Render invisibles with replacement characters in diff editors

### ISSUE THREAD

**Issue by AfsalInovicsTech** [microsoft/vscode#126950]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Check these strings 
```
let update_consultation_api = this.baseUrl + `​/appointments​/${appointment_id}​/consultations​/${consultation_id}​/`
let read_consulatation_api = this.baseUrl + `/appointments/${appointment_id}/consultations/${consultation_id}/`
```
2. When i compare both these strings it was not matching
3. Then i paste this on sublime text it was different text it show a '​<ox200b>' character
4. I think this is a serious issue please check

**Comment by bpasero** [comment]
> When i compare both these strings it was not matching

How?

**Comment by AfsalInovicsTech** [comment]
Hi Microsoft/Vscode,

The code I was using is below:


*let update_consultation_api =
`/appointments/${appointment_id}/consultations/${consultation_id}/`let
read_consulatation_api =
`/appointments/${appointment_id}/consultations/${consultation_id}/`\t*
*console.log(update_consultation_api == read_consultation_api)*

The result of this code was false.Then I pasted this code on sublime text
which gave a different result.
I have attached a screenshot for your reference.


I think this is a bug with vs code. Kindly look into it.

Thanks and Regards,
Afsal MS

**Comment by bpasero** [comment]
?

**Comment by AfsalInovicsTech** [comment]
What do you mean?

**Comment by yume-chan** [comment]
There is a `\u200b` (zero width space) after the first <code>`</code>

**Comment by AfsalInovicsTech** [comment]
Yes that is visible in sublime text but not showing on VS code that is the
issue.
I don't know how it get appended to that string

**Comment by bpasero** [comment]
@AfsalInovicsTech 

> I have attached a screenshot for your reference.

No, you didn't.

> The result of this code was false.

You still did not explain what you do exactly, step by step so that I can reproduce.

**Comment by yume-chan** [comment]
Note: GitHub doesn't accept image uploads from emails, please upload from web interface or mobile Apps.

**Comment by yume-chan** [comment]
#116939

**Comment by AfsalInovicsTech** [comment]
Hi Microsoft/Vscode,

I will share screen recording shortly

**Comment by thebinarysearchtree** [comment]
I believe they are referring to the fact that when you have the first string in one file, and the second string in another file, comparing the two files does not highlight the zero width character.

<img width="660" alt="Screen Shot 2021-06-23 at 4 42 40 pm" src="https://user-images.githubusercontent.com/960753/123048736-13cc0580-d442-11eb-8bbf-6849b314ff64.png">

**Comment by thebinarysearchtree** [comment]
There will be a lot more than just the zero width space that don't show up. It will also depend on what font is being used. For example, the variant selectors may either show up as a variant of an emoji, or an invisible character, depending on the font and the current state of Chrome in terms of whether they have fixed font rendering issues related to emojis. Other characters that are zero width include zero width joiners, etc.
