### ISSUE TITLE
Yield keyword is not coloured in JavaScript

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1269]
![image](https://cloud.githubusercontent.com/assets/22350/11782623/458b351c-a272-11e5-8bf2-ca1dc66c6560.png)

**Comment by aayushkapoor206** [comment]
@joaomoreno It seems to be colouring the yield keyword. Which version of Code are you using?
Did you install a theme using an extension? Try changing to the default ones.

**Comment by aeschli** [comment]
@joaomoreno Please always paste the code snippet as well...

**Comment by aeschli** [comment]
It's a problem of the grammar

**Comment by joaomoreno** [comment]
Sorry!

```
yield 123;
```

:+1:

**Comment by bpasero** [comment]
I think that is not the full snippet from the screenshot...

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#29
