### ISSUE TITLE
Typescript continues to crash when saving file

### ISSUE THREAD

**Issue by applyinnovations** [microsoft/vscode#126903]
Typescript crashing on file save. Unable to resolve type errors in my code base, sometimes takes a minute or two after file save, other times it just crashes.

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should fill issue template that includes version and extensions list.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by applyinnovations** [comment]
Hey thanks for the prompt response. After disabling the extensions as you have mentioned, it still takes 60-90 seconds to compile and provide the syntax highlighting / error checking.

**Comment by applyinnovations** [comment]
Actually upon writing that response I am no longer receiving syntax checking , however a restart of vs code brought it back after waiting ~30 seconds after launch.

**Comment by applyinnovations** [comment]
I have just noticed that it is also error checking my node_modules folder. I assume this is what is causing such delay?

**Comment by applyinnovations** [comment]
Another update: I just received the "TypeScript language service died unexpectedly 5 times in the last 5 Minutes" error again after disabling all my extensions and continuing to use the editor.

**Comment by mjbvz** [comment]
Please fill in the issue template. There is currently not enough information to investigate this issue
