### ISSUE TITLE
Font rendering is blurry on chromebook (crostini)

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#126926]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.58.0-insider
Commit: d54f7e1f6c1290fe27e2397eca509d0e0728272e
Date: 2021-06-22T07:15:45.422Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.109-26091-g577602338376 (Linux on Chrome OS)

Font is blurred on Crostini on Chromebook. 

![image](https://user-images.githubusercontent.com/44866753/122967631-aa23fc80-d358-11eb-9378-a54c5f8f4d1e.png)

**Comment by deepak1556** [comment]
Can you try launching with `--force-device-scale-factor=1` and see if the issue persists ?

**Comment by kuelumbus** [comment]
That didn't fix it for me. Still blurry

**Comment by kuelumbus** [comment]
Seems like the issue was the display size setting on chrome OS. The font looks good after setting it to 100%.
