### ISSUE TITLE
Search editor: input disappears after deleting the value

### ISSUE THREAD

**Issue by pustovalov** [microsoft/vscode#126917]
Issue Type: <b>Bug</b>

1. Open Search editor
2. Remove value for `show number of lines` input

Video:
https://monosnap.com/file/xiWp8S7FoZBr5Hx0ibYj76dTukf682

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id 550c5a70-fcc2-4aa0-b4d7-5a7b71453d59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
better-toml|bun|0.3.2
turbo-console-log|Cha|2.1.6
bracket-pair-colorizer|Coe|1.0.61
cjsx|cri|0.0.6
vscode-svgviewer|css|2.0.0
vscode-faker|dee|1.5.0
es7-react-js-snippets|dsz|3.1.1
remotehub|eam|0.5.0
mithril-emmet|Fal|0.7.6
nasc-touchbar|fel|1.12.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-flow-ide|gca|1.2.0
remotehub|Git|0.10.1
vscode-pull-request-github|Git|0.27.1
gc-excelviewer|Gra|3.0.42
search-editor-apply-changes|jak|0.1.1
svelte-vscode|Jam|0.9.3
dupchecker|jia|0.1.7
vscode-styled-components|jpo|1.6.4
haml|kar|1.3.1
ruby-syntax-replacer|Kos|1.0.11
node-module-intellisense|lei|1.5.0
restructuredtext|lex|153.0.0
prettify-json|moh|0.0.3
remote-containers|ms-|0.183.0
atom-keybindings|ms-|3.0.9
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.7.0
text-power-tools|qcz|1.27.0
vscode-commons|red|0.0.6
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
indenticator|Sir|0.7.0
vscode-fileutils|sle|3.4.5
tabnine-vscode|Tab|3.4.8
lodash-snippets|tom|1.0.0
remove-empty-lines|use|0.0.6
vscode-icons|vsc|11.5.0
vscode-wakatime|Wak|12.0.0
quokka-vscode|Wal|1.0.381
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.10.14
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30324779
vscextlangct:30322307
binariesv615cf:30323120

```

</details>

**Comment by JacksonKearl** [comment]
Are you in a remote repository environment?

**Comment by pustovalov** [comment]
this is reproducible for remote and not remote environment

**Comment by JacksonKearl** [comment]
Ah, I see the issue. Surprising that this hasn't come up before.

**Comment by wsmelton** [comment]
Windows, with the system installer of Insiders I don't see the text from the start. It is not until I expand it to get find/replace fields that I can see the text.

![image](https://user-images.githubusercontent.com/11204251/122998838-2aeff200-d373-11eb-85f6-527312549f01.png)

![image](https://user-images.githubusercontent.com/11204251/122998913-3ba06800-d373-11eb-8fd5-eb325b7fa15b.png)

**Comment by JacksonKearl** [comment]
@wsmelton that's https://github.com/microsoft/vscode/issues/126896, we have a fix and will be releasing a new Insiders in the coming hour or so.
