### ISSUE TITLE
editor.wordSeparators is not honoring $ in Powershell

### ISSUE THREAD

**Issue by daisy613** [microsoft/vscode#126920]
Issue Type: <b>Bug</b>

To reproduce:
1. Remove '$' from editor.wordSeparators
2. Doubleclick on a word that starts with $
3. The selection does not include $

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.78GB free)|
|Process Argv|--crash-reporter-id e26138dd-e53b-4453-8aec-6b164157feb7|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remotehub|Git|0.10.1
vscode-test-explorer|hbe|2.20.4
vscode-ansi|ili|1.1.2
thinking-in-code|los|0.0.7
vscode-pylance|ms-|2021.6.2
powershell-preview|ms-|2021.6.1
test-adapter-converter|ms-|0.0.10
vscode-github-projects|Pod|1.0.0
vscode-thunder-client|ran|1.4.1
vscode-commons|red|0.0.6
run-in-powershell|tob|1.1.0
vscode-inline-values-powershell|Tyl|0.0.5
vscode-pester-test-adapter|Tyl|0.0.23
better-align|wwm|1.1.6

</details>

**Comment by JustinGrote** [comment]
@daisy613 This is Powershell extension specific, the behavior was recently changed. recommend refiling the issue there if you still have problems.
https://devblogs.microsoft.com/powershell/powershell-for-visual-studio-code-may-2021-update/

**Comment by daisy613** [comment]
FYI, I fixed it by copying the editor.wordSeparators line into the  this line inside the [powershell] section, like so:

```
    "[powershell]": {
        "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
        "editor.defaultFormatter": "ms-vscode.powershell-preview"
    },
```

**Comment by menees** [comment]
It looks like vscode-powershell put $ back into powershell's default editor.wordSeparators a few days ago according to [this thread](https://github.com/PowerShell/vscode-powershell/issues/3378#issuecomment-860993280). So the blog post about the May 2021 update is out-of-date.

The v2021.6.1 update of the PowerShell extension is using its own wordSeparators that _include $ and override the default wordSeparators_. So even if you previously had the global editor.wordSeparators set to exclude $, now you have to change the PowerShell-specific settings to exclude $ too. And there's no UI for the PowerShell-specific setting, so you have to edit it in the JSON settings as @daisy613 mentioned above (but you don't have to set the editor.defaultFormatter).

This vscode issue can be closed. The PowerShell extension team caused this problem by adding a language-specific override to editor.wordSeparators and then flip-flopping on how it's configured. :-(
