### ISSUE TITLE
Using GAP in Vscode

### ISSUE THREAD

**Issue by anindyadas140** [microsoft/vscode#126919]
![Screenshot (53)](https://user-images.githubusercontent.com/86313543/122958647-897f9500-d3a0-11eb-9f92-6f282fc4b3b1.png)
Issue Type: <b>Feature Request</b>

I have seen that GAP is supported in VScode but i can not use it there & not able to find where exactly the problem is, so i request you to guide me in this regard.It would be very helpful if you look in this regard..

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by IllusionMH** [comment]
VS Code doesn't support this language out of the box, but you can search for extension that can provide support: https://marketplace.visualstudio.com/search?term=gap&target=VSCode&category=Programming%20Languages&sortBy=Relevance

**Comment by anindyadas140** [comment]
I have installed these Extensions but still the problem exists, Did i miss
any settings regarding the environment variables or something else.

**Comment by IllusionMH** [comment]
/question

Do you have this folder as trusted?
Looks like extension wasn't updated to run in untrusted workspaces.
See https://code.visualstudio.com/updates/v1_57#_workspace-trust and **Enabling extensions** section on how to handle it.
Or mark workspace as trusted.

Also it make sense to submit issue in extension repo to add support for untrusted workspaces.
