### ISSUE TITLE
Workspace settings for integrated terminal profiles are not picked up from workspace settings

### ISSUE THREAD

**Issue by reflash** [microsoft/vscode#126985]
Issue Type: <b>Bug</b>

Hi!
I was trying to configure terminal profiles for my workspace and it worked if I put those in user settings file, but if I transfer them to workspace settings - nothing is shown.
I've tried reloading VS to check if it reads settings on load and even tried to rebuild devcontainer (my workspace is running in one)

Is it a known issue? Should I do anything extra to see profiles displayed?

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|-psn_0_114716 --crash-reporter-id a379c72b-eb4c-4afe-97e4-e40ee402ba3d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (2 x 1598)|
|Memory (System)|3.84GB (0.71GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
ts-snippets|chr|1.1.0
bracket-pair-colorizer-2|Coe|0.2.1
fluent-icons|mig|0.0.12
dotenv|mik|1.0.1
vscode-azurevirtualmachines|ms-|0.4.0
remote-containers|ms-|0.177.2
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1
errorlens|use|3.2.7
vscode-icons|vsc|11.5.0
vscode-todo-highlight|way|1.0.4
vscode-apollo|apo|1.19.3
highlight-line-vscode|cli|0.0.1
gitlens|eam|11.4.1
prettier-vscode|esb|7.1.1
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
azure-account|ms-|0.9.8
js-debug-nightly|ms-|2021.5.2717
vscode-js-profile-flame|ms-|0.0.21
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4419
prisma|Pri|2.25.0
typescript-hero|rbb|3.0.0
vscode-icons|vsc|11.5.0
codetour|vsl|0.0.56
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30324780
binariesv615:30325510
vsccppwt:30322536

```

</details>

**Comment by meganrogge** [comment]
Are you in a trusted workspace? You'll need to be in order to use workspace settings.

**Comment by Tyriar** [comment]
You need to upgrade to 1.57 and then trust the workspace
