### ISSUE TITLE
 Cannot read property 'child' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12699]
Issue Id: <b>0aa8075c-0fd5-24b2-66d1-97552723858e</b><br /><br />*Versions* <br />- 1.5.3<br />-  66f37fd2a99eb9d628dd374d81d78835b410c39b<br />*Stack* <br />TypeError: Cannot read property 'child' of undefined<br />[/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1694:30 (child)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1694:30 (child))<br />[/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1686:14 (getFromContainer)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1686:14 (getFromContainer))<br />[/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1707:9 (getProgressBar)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1707:9 (getProgressBar))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L453:25 (updateProgress)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/workbench/browser/parts/editor/editorPart.ts#L453:25 (updateProgress))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L430:15 (doHandleSetInputError)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/workbench/browser/parts/editor/editorPart.ts#L430:15 (doHandleSetInputError))<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (onError)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/base/common/winjs.base.raw.js#L1209:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L901:0 (_notify)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/base/common/winjs.base.raw.js#L901:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1031:0 (_run)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/base/common/winjs.base.raw.js#L1031:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L736:0 (_chainedError)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/base/common/winjs.base.raw.js#L736:0 (_chainedError))<br />

**Comment by Tyriar** [comment]
@bpasero any easy steps to verify?

**Comment by ramya-rao-a** [comment]
I don't see this in the error telemetry anymore. Marking as verified

**Comment by bpasero** [comment]
@Tyriar @ramya-rao-a we typically do not verify error telemetry bugs (at least we used to). but if any, I think doing a code review on the linked change is always the easiest.
