### ISSUE TITLE
Extension debugging: stopping debug session doesn't close window

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#126911]
Issue Type: <b>Bug</b>

- debug "Mock Debug" extension
- stop debug session by pressing red button in debug toolbar

Observe: extension window doesn't close

This problem doesn't occur with a simple "hello world" extension.

---

VS Code version: Code - Insiders 1.58.0-insider (6afedfdad59d1f1ba4b614341d21c67775e158a9, 2021-06-21T05:14:03.949Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 785023c0-aeb7-4708-b29f-2c6aa9e59a8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.45.8
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.23
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
vscode-pull-request-github-insiders|Git|2021.6.30916
csharp|ms-|1.23.12
jupyter|ms-|2021.7.960048241
remote-containers|ms-|0.184.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
cpptools|ms-|1.5.0-insiders
js-debug-nightly|ms-|2021.6.1617
vscode-github-issue-notebooks|ms-|0.0.102
java|red|0.79.2
vscode-lldb|vad|1.6.4
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
gitblame|wad|7.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by isidorn** [comment]
This works just fine for me. I can not repro.
Here are my steps:

1. Latest vscode insiders, latest mock debug
2. Choose "Extension" launch config. Press F5 to start debugging
3. Press red button -> window closes

Let me know what you are doing differently than me in this gif:

![recording (1)](https://user-images.githubusercontent.com/1926584/122966297-71e8e200-d389-11eb-877c-a2230ebe378a.gif)

**Comment by weinand** [comment]
@isidorn thanks for trying this.

Since I could reliably reproduce this problem, I tried all kinds of things: uninstalling all extensions, changing settings, restarting my computer ;-)

What helped in the end was deleting the `Code - Insiders` folders in `~/Library/Application Support/` which basically wipes all settings and browser state and caches. After doing this the problem no longer occurs.

Then I was looking into the other new issue https://github.com/microsoft/vscode/issues/126924.
Since you saw that problem when running out of source, I did the same and ran Mock Debug in VS Code out of source. Icould not reproduce your problem but I again saw the issue that the extension window would not close when stopping the debug session.

And again deleting the `code-oss-dev` folders in `~/Library/Application Support/` made the problem disappear.

So there seems to be an issue with persisted state...

**Comment by isidorn** [comment]
@weinand if you can reproduce it would be interesting to understand if the signal to close the window is sent or not. I forgot if we send this from the debug session, or from the debug adapter.

**Comment by weinand** [comment]
@isidorn no, we don't close EH windows from the debug session. The window is closed because the extension host process is terminated.

**Comment by Jason3S** [comment]
I have this issue too.
Although reloading using 
![image](https://user-images.githubusercontent.com/3740137/123510673-1a928c80-d67d-11eb-9b1a-641b1aeddb81.png)
seems to work.

When using a reload, I get an unhandled rejected promise in `extensionHostProcess.js`
```js
return y.apply(b,h)}_remoteCall(a,p,h){if(this._isDisposed)return Promise.reject(k.canceled());
```
This is rather recent and is most likely unrelated.

**Comment by weinand** [comment]
@bpasero before giving up on this issue I would like to get your insights.
Could you please read my https://github.com/microsoft/vscode/issues/126911#issuecomment-866742308 from above? Do you have an idea what is going on?

And another persisted storage related issue from today: https://github.com/microsoft/vscode/issues/130490

**Comment by bpasero** [comment]
@weinand 

> no, we don't close EH windows from the debug session. The window is closed because the extension host process is terminated.

Trying to find that code again, can you point me to it?

If you have a reliable repro for this, can you try running with `--verbose` and check for main logs and window logs (maybe also devtools of that window) to see if an exception is raised or any veto?

**Comment by bpasero** [comment]
Isn't it this code, which would suggest the window is closed based on an event from debug?

https://github.com/microsoft/vscode/blob/d18e54f820f87df1fa9f9bdd658b7f824c756f8d/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L131-L135

//cc @isidorn

**Comment by bpasero** [comment]
Ah and it seems like also this one:

https://github.com/microsoft/vscode/blob/2a82df9437f5c1d3e0302ff4910a5e7f51ea1756/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L461-L472

**Comment by bpasero** [comment]
The latter seems the one that works here, the former seems to be used only in remote extension host scenarios.

**Comment by weinand** [comment]
When pressing the Stop button VS Code sends a DAP "disconnect" request to js-debug which in turn terminates the node process (EH). Some workbench code then gets an event that the node.js child process has terminated. If this happens as part of a "reload command", a new EH is started. Otherwise the enclosing window is closed.

**Comment by isidorn** [comment]
Thanks. So for me it seems like js-debug is not able to terminate the EH.
I can always reproduce this with VS Code Insiders with my user data dir. It is 800mb, I have shared it with you via my OneDrive, so please try to download it and repro.
With a fresh user data dir I can not reproduce this.

@connor4312 could you double check from the js-debug side if the extension is successful in shutting down the EH. Or if the process is left lying around?

fyi @alexdima

**Comment by bpasero** [comment]
I was not able to reproduce even with your user data folder, so I wonder if it is the associated data specifically for the workspace that is being debugged?

**Comment by Jason3S** [comment]
It happens to me after I have done a reload of the debug session. 

1. Launch debugger
2. Make a change to the code and build. 
3. Reload the debugger 
4. Repeat 2
5. Stop debugging 
6. Notice the process does not stop. 

Note: I'm using Mac OS 11.5

**Comment by weinand** [comment]
@connor4312 above Isi said:
> .... So for me it seems like js-debug is not able to terminate the EH.

Could you please check it what situations this could happen?

**Comment by connor4312** [comment]
Sorry I missed this notification. I don't believe js-debug ever terminates the extension host itself; that is normally done by core. Though I could always add code to do so...

**Comment by isidorn** [comment]
@connor4312 I could not find the code in core that terminates the EH, I thought it was being done by the js-debug.
Could you maybe try to add code for that and than I can try to repro this issue with js-debug insiders to see if it is fixed?

**Comment by connor4312** [comment]
Added and it seems to work for me. Mark verified if it does for you too, please 🙂

**Comment by weinand** [comment]
Yes, VS Code core does not do anything special when debug's stop button is pressed. So the Stop button just uses regular DAP protocol.
And the DA needs to terminate the debuggee because EH debugging starts with a "launch" (and the fact that there are subsequent "attach" request should not change that).

**Comment by isidorn** [comment]
I have verified that this indeed fixes the issue on my machine with the js-debug-nightly.
@connor4312 thanks a lot 👏

**Comment by connor4312** [comment]
Interesting. No idea how this was working before 😛

**Comment by weinand** [comment]
Good question - I do not have an explanation either...

BTW, does js-debug's extension debugging supports DAP's "terminate" request? In that case VS Code will send a "terminate" on first press of the Stop button. Could you pleas check with Rob what was done in node-debug2.
