### ISSUE TITLE
vscode: "the folder currently open doesn't have a git folder" (but it does have) 

### ISSUE THREAD

**Issue by vincent-cm** [microsoft/vscode#126971]
Issue Type: <b>Bug</b>

1. Open a project with a git repo
2. Observed the source control is empty that it cannot detect the git repo.

This is only happening after a VSCode version update.

There is a similar issue closed in 2020 but it seems happens again.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|64.00GB (2.12GB free)|
|Process Argv|/xxxxxxxxxx --crash-reporter-id 2d4a0446-8d6b-4172-9f0b-82b607412f1b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.7.1
language-postcss|cpy|1.1.0
xml|Dot|2.5.1
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
shell-format|fox|7.1.0
vscode-nginx-conf-hint|han|0.1.0
Angular2|joh|12.0.0
perltidy-more|Kak|0.6.1
perl-debug|mor|0.6.3
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.4.1
vscode-groovy-lint|Nic|1.4.0
nginx-formatter|ray|0.0.13
jenkinsfile-support|sec|0.1.0
language-stylus|sys|1.11.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30324780
binariesv615:30325510

```

</details>

**Comment by vincent-cm** [comment]
Not a subfolder, the .git folder is in the root folder. And `git status` shows correctly.

**Comment by leolusoli** [comment]
+1

**Comment by vincent-cm** [comment]
A fresh install works for me

**Comment by leolusoli** [comment]
Reopen. The problem persist even with a fresh install for me.
