### ISSUE TITLE
all colors are just washed away and no highlighting

### ISSUE THREAD

**Issue by vhbit** [microsoft/vscode#126931]
<img width="563" alt="Screenshot 2021-06-22 at 20 55 56" src="https://user-images.githubusercontent.com/140199/122975784-65ba5000-d39c-11eb-8b1a-62f353c26895.png">
Issue Type: <b>Bug</b>

- open the app
- there are no colors and no highlighting and everything looks extremely weird
- happens on all workspaces and on all file types
- switching themes doesn't help much, light theme is a bit more readable, but still no colors

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using Source Code Pro font? Most likely duplicate of #100840

**Comment by vhbit** [comment]
@IllusionMH ohh, yes, indeed it was related to `Source Code Pro`, switching to other font fixed it
Thank you!
