### ISSUE TITLE
CPU 100% being used by Code Helper without running anything. Code 1.57.1

### ISSUE THREAD

**Issue by vincent-cm** [microsoft/vscode#126982]
Issue Type: <b>Performance Issue</b>

100% CPU as you can see on macOS - Activity Monitor  
No job is running include 'tasks', 'extensions' or 'window'. Command line top -F -R -o cpu shows as

![image](https://i.imgur.com/vJS6B5z.png)

It does not seem to stop until manually killing all the vscode process.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|64.00GB (1.75GB free)|
|Process Argv|./ --crash-reporter-id 2d4a0446-8d6b-4172-9f0b-82b607412f1b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   131	 82248	code main
    0	    66	 82252	   gpu-process
    0	     0	 82254	   utility
  145	   262	 82260	   window (Getting Started — frontend)
   60	   131	 82262	     extensionHost
    0	    66	 82263	     watcherService
    0	   131	 82261	   shared-process
    0	    66	 82264	     ptyHost
    0	     0	 82265	       /bin/zsh -l
    0	     0	 82751	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 82748	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Getting Started — frontend)
|    Folder (frontend): 8420 files
|      File types: php(2160) js(1472) png(507) ts(503) gif(408) tpl(366)
|                  css(332) scssc(315) scss(298) txt(159)
|      Conf files: tsconfig.json(2) launch.json(1) settings.json(1)
|                  package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.7.1
language-postcss|cpy|1.1.0
xml|Dot|2.5.1
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
shell-format|fox|7.1.0
vscode-nginx-conf-hint|han|0.1.0
Angular2|joh|12.0.0
perltidy-more|Kak|0.6.1
perl-debug|mor|0.6.3
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.4.1
vscode-groovy-lint|Nic|1.4.0
nginx-formatter|ray|0.0.13
jenkinsfile-support|sec|0.1.0
language-stylus|sys|1.11.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30324780
binariesv615:30325510

```

</details>

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by ehowey** [comment]
I can confirm I am seeing something similar. I tried all the common fixes, e.g. disabling plugins, etc. What seemed to work was a total new install of VS Code.

**Comment by bpasero** [comment]
We need to identify the process that spins high CPU to continue.

**Comment by ehowey** [comment]
> We need to identify the process that spins high CPU to continue.

Sorry I can't help more - it seems fixed now by a fresh install for me.

**Comment by vincent-cm** [comment]
Yes, a fresh install also works for me. I remember if you view the Log (window) there will be many exceptions with Render process populates frequently. But I did not take any screenshot, sorry.
