### ISSUE TITLE
Search input value is not displayed

### ISSUE THREAD

**Issue by bmark88** [microsoft/vscode#126990]
Issue Type: <b>Bug</b>

1. Enter a file
2. Within the file, do a search (ctrl/cmd + F)
3. Type a search value

Expected result:
- Search should work, and the value that was put into the search should also be displayed.

Actual result:
- Search works, but the value that was put into the search is not displayed.

Additional note:
- When clicking another button, the state gets updated and the search value does become visible

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:14:39.120Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 737a1816-199c-4c90-8169-ad5ad1e37aaf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
flow-for-vscode|flo|1.5.0
vscode-styled-components|jpo|1.6.4
chat|kar|0.35.0
vscode-azureappservice|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.14.0
azure-account|ms-|0.9.8
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
team|ms-|1.161.1
code-settings-sync|Sha|3.4.3
errorlens|use|3.2.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by cmario92** [comment]
Search box input text is not showing, when is focused.

**Focused**
![image](https://user-images.githubusercontent.com/5765285/123092166-dd3abe80-d432-11eb-8a30-b873acd3fa17.png)

**Losing Focus**
![image](https://user-images.githubusercontent.com/5765285/123092233-f3487f00-d432-11eb-970e-95cf942f3f3f.png)

This is not related to themes, or any extension. 

**Can confirm this on latest insiders build:**

Version: 1.58.0-insider
Commit: d54f7e1f6c1290fe27e2397eca509d0e0728272e
OS: Linux x64 5.11.0-22-generic snap

**Comment by gjsjohnmurray** [comment]
/duplicate and already reported fixed in today's Insiders
