### ISSUE TITLE
Please Help, I cannot restore Menu Bar no matter what I do... 

### ISSUE THREAD

**Issue by briankim13** [microsoft/vscode#126935]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

I don't have Menu Bar any more. 
File, Edit, View, ... all that stuff is gone. 

Steps to Reproduce:
I forgot what I did, probably hit some random F1~F10 button somewhere and it went to full screen or whatever. But now I am stuck in a state where I can't get them back :( 

I tried pressing Alt (apparently this is the solution that is passed around). 
I tried reinstalling (no luck, same issue). 

Could you please help me?

Thanks

**Comment by sbatten** [comment]
maybe you have the same issue as this person https://github.com/microsoft/vscode/issues/126983 ... Please see the suggested steps there so I can investigate (note the user name in the paths should be updated for your machine)
