### ISSUE TITLE
Version 1.56+ breaks WSL2 extensions and terminal

### ISSUE THREAD

**Issue by foxbird** [microsoft/vscode#127041]
Issue Type: <b>Bug</b>

I'm running latest as of today (6/23/2021). When I start VSCode from WSL2 using `code .` in a directory, the application loads and shows me my code as expected. However, chosing 'Terminal > New Terminal' shows the terminal pane, but there is nothing in it and it is unresponsive. Additionally, extensions do not seem to load properly. For example, OmniSharp, golang, and others do not provide any sort of intellisense output. I noticed that several of the extensions on linux were out of date, so I clicked to upgrade them. However, the progress indicator continues to cycle around, never making any progress. Likewise, installing new plugins fails as well.

There is no proxy or other situation here, and network communication is fine. I have also tried turning off workspace trust (`security.workspace.trust.enabled` to `false`), but that seems to have no impact on the overall situation.

I turned off automatic updates and downgraded to 1.55.2 and it appears to work again. So, something between 1.55.2 and 1.56.1 broke the functionality. Worthy of note, when I do downgrade to 1.55.2 I have to reinstall the Remote WSL extension. So, while I filed this with VSCode, it may totally be an issue with the WSL extension.

I've tried this on multiple machines as well all with same result. I have also removed the entire .vscode-server directory as well, just in case some items were bad on the server.

Ubuntu in WSL2 is Ubuntu 20. 

The remote extension log seems to provide no error/warning, but when set to Trace, it does provide a stack dump periodically complaining about resolveProxy, right after a ProxyResolver#resolveProxy debug entry, as in the output below:
``` 
Error: Error for stack trace
	at resolveProxy (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:105:69)
	at c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:293:54)
	at _PacProxyAgent.<anonymous> (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:71:37)
	at Generator.next (<anonymous>)
	at c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:4:12)
	at _PacProxyAgent.callback (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\agent.js:53:16)
	at _PacProxyAgent.addRequest (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\node_modules\agent-base\dist\src\index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched [as request] (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:297:24)
	at Function.e.makeRequest (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:1:9726)
	at Timeout.s [as _onTimeout] (c:\Users\Test User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:1:11380)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (39.49GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/foxbird/sandbox/MetaParser --remote=wsl+Ubuntu --crash-reporter-id a2c66583-1701-4aa6-831d-8b883090f104|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|Memory (System)|50.11GB (43.05GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-wsl|ms-|0.56.5
xml|Dot|2.5.1
go|gol|0.26.0
beautify|Hoo|1.5.0
rainbow-csv|mec|1.8.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30324780
binariesv615:30325510

```

</details>

**Comment by DominicH247** [comment]
also experiencing the same issue on 1.57.1 (WSL2 Ubuntu 20).

**Comment by NicholasTaylor** [comment]
Also experiencing this. Like @foxbird this has started for me since v1.56. v.1.55.2 is the last known version where I can get Remote - WSL and Terminal to work fine.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (1.92GB free)|
|Process Argv|--crash-reporter-id 07e52d71-b664-4752-a21d-c2ef67b2b001|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|12.44GB (7.50GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.5
ayu|tea|0.20.1
vscode-intelephense-client|bme|1.7.1
better-toml|bun|0.3.2
prettier-vscode|esb|7.1.1
vscode-graphql|Gra|0.3.16
prettier-php|kar|0.0.3
vscode-mjml|mjm|1.0.4
vscode-docker|ms-|1.14.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.5.745244803
vscode-fileutils|sle|3.4.5
php-formatter|Sop|0.2.4
docker|vsc|1.0.0
yaml|vsc|1.0.0
vscode-proto3|zxh|0.5.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30329804
binariesv615:30325510
vsccppwtct:30329789

```

</details>

**Comment by meganrogge** [comment]
can you try turning off `useWslProfiles`?

**Comment by foxbird** [comment]
I agree with @NicholasTaylor here. I disabled it on both WSL Remote, and also locally as well. No change, even after restarting. 

I also noticed that if I start VSCode with a remote as my last session (or if I click the connection button and select new WSL window), I get a clock on the 'Extensions' as panel, telling me something is going on. That was there previous to the setting change, I just hadn't noticed that before.

**Comment by Tyriar** [comment]
Do you set the `terminal.integrated.inheritEnv` setting? You could do trace logging to find out more information about how the terminal is being launched: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by foxbird** [comment]
The UI said the feature was enabled locally. Disabling it seems to fix the terminal not appearing, but the extensions (which is generally my problem) are still broken and do not install, update, or function. Below are my settings (without the inheritEnv). I generally don't change any settings as the default usually works for me. So there's only a few here. (I also don't normally disable updates or trust, but as above I'm trying different things to see what breaks.

```
{
    "workbench.startupEditor": "newUntitledFile",
    "files.maxMemoryForLargeFilesMB": 40960,
    "terminal.integrated.fontFamily": "Cascadia Mono PL",
    "json.maxItemsComputed": 50000,
    "workbench.editor.untitled.hint": "hidden",
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.useWslProfiles": false,
    "security.workspace.trust.enabled": false,
    "update.mode": "manual",
}
```

I'll also read up on the trace logging and see if anything useful comes out of it and post here.

**Comment by NicholasTaylor** [comment]
FYI, issue resolved for me when I upgrade VS Code. I can't recall if it was 1.58, 1.58.1, or 1.58.2, but I now have a working integrated terminal in Remote WSL. 

One idiosyncrasy I noticed - when running Bash through integrated terminal on a Remote WSL session, it looks like it reads from `~/.bashrc`, but not `~/.bash_profile`. So, if your $PATH variable is off or you're missing aliases, my workaround was just to move everything to bashrc.

**Comment by foxbird** [comment]
Looks like `1.5.82` (or before) fixed it. I can get my terminal and add/remove extensions again.

I'll close this since it seems to have been mysteriously fixed.

Thanks to whoever took care of it!
