### ISSUE TITLE
Can't search extensions marketplace

### ISSUE THREAD

**Issue by kcorey** [microsoft/vscode#127058]
Issue Type: <b>Bug</b>

How completely frustrating.

Install vscode 1.57.1 from scratch on MacOS 11.4 Big Sur.

Run it.  It updates a few things, and install gitlens.

Go to extensions, try to start typing (I want to install Calva).

See the "We cannot connect to the Extensions Marketplace at this time, please try again later."

As this error isn't transient, I'd suggest that the error gets reported back to the developers, rather than suggesting to the user that they beat their heads on this particular wall again.

Looking in the console, I see "Cannot read property 'toLowerCase' of underfined" in extensionsViews.ts:323.

In one bug report, it was suggested that we hit a url to download the image of a python icon to test for DNS issues.  I could see the image, but still have the problem.

FWIW, I use NextDNS as my DNS provider as it cuts out a lot of cruft.  Could vscode be breaking because of that?

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id b674d1f4-dd50-4df4-8c10-932557115dd4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-vlang|0x9|0.0.4
rainbow-brackets|2gu|0.0.6
output-colorizer|IBM|0.1.2
lorem-ipsum|Tyr|1.2.0
html-class-suggestions|And|1.1.1
path-intellisense|chr|2.3.0
jsrefactor|cms|2.20.6
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|8.0.1
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
vscode-javac|geo|0.2.39
go|gol|0.26.0
rest-client|hum|0.24.5
vscode-jetbrains-keybindings|isu|0.1.9
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Kotlin|mat|1.7.1
terminal-runner|mig|0.0.2
cpptools|ms-|1.4.1
vscode-react-native|msj|1.5.1
color-highlight|nau|2.3.0
peep|nwa|0.0.5
java|red|0.79.2
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
v|N/A|0.0.1
vscode-icons|vsc|11.5.0
gitblame|wad|7.0.6
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/119375
