### ISSUE TITLE
"Save All" not available

### ISSUE THREAD

**Issue by jbritzke** [microsoft/vscode#127029]
Issue Type: <b>Bug</b>

Rename Symbol for a function name used in multiple files.
Function is renamed properly in all files.
Each file is marked with indicator that file has been modified and not yet saved.
However, "Save All" is grayed out (disabled) and each modified file must be saved individually.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
oracle-jet-core|Ora|2.3.1

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/126133
