### ISSUE TITLE
TreeItem State None to Expanded

### ISSUE THREAD

**Issue by vincentjocodes** [microsoft/vscode#127035]
Issue Type: <b>Bug</b>

We, [Cloud Code](https://github.com/GoogleCloudPlatform/cloud-code-vscode) have a use case where a TreeItem could transition from `vscode.TreeItemCollapsibleState.None` to `vscode.TreeItemCollapsibleState.Expanded`. Currently, this functionality doesn't seem to work on a dynamic setting. 

I have created a simple repro here: https://github.com/vincentjocodes/vscode-tree-state-issue. Steps to repro the problem with the sample app are: 

1) Run Extension
2) Open the Explorer and see 2 nodes:
![image](https://user-images.githubusercontent.com/13400593/123178491-29d6c780-d43c-11eb-8afe-d735403e03c7.png)
3) Run `Event: Expand` command from the command palette
4) See that the items are collapsed:
![image](https://user-images.githubusercontent.com/13400593/123178556-4b37b380-d43c-11eb-9480-97d462f68df0.png)

I expect the items to be expanded, per [this line of code in the sample](https://github.com/vincentjocodes/vscode-tree-state-issue/blob/main/src/extension.ts#L74). There are no places in my code where I set `vscode.TreeItemCollapsibleState.Collapsed`. 

Please help. 

Thank you. 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv|--crash-reporter-id ed7a5a7f-6e02-4080-a6f9-795012ddb483|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30324779
binariesv615:30325510

```

</details>

**Comment by TylerLeonhardt** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/2644648/124188244-dc79dc00-da73-11eb-88d0-4865ea467da6.png)

**Comment by vincentjocodes** [comment]
@TylerLeonhardt @alexr00 Just downloaded the Insider's today but couldn't get dynamic expansion working from `vscode.TreeItemCollapsibleState.None` to `vscode.TreeItemCollapsibleState.Expanded`.

**Comment by alexr00** [comment]
@vincentjocodes I reverted this change since not reflecting such changes to `collapsibleState` is by design. If tree data providers can change the expand state of trees like this then it can get extremely confusing for users when their tree expansion states change. The `collapsibleState` is an initial value only. To expand a tree item, you should use the [reveal](https://github.com/Microsoft/vscode/blob/55868691efbc657fff97af72732e4d8482e11450/src/vs/vscode.d.ts#L9233-L9234) API.

**Comment by vincentjocodes** [comment]
> @vincentjocodes I reverted this change since not reflecting such changes to `collapsibleState` is by design. If tree data providers can change the expand state of trees like this then it can get extremely confusing for users when their tree expansion states change. The `collapsibleState` is an initial value only. To expand a tree item, you should use the [reveal](https://github.com/Microsoft/vscode/blob/55868691efbc657fff97af72732e4d8482e11450/src/vs/vscode.d.ts#L9233-L9234) API.

Shouldn't user experience be within the developer's control, rather than the a strict restriction on the platform? I think programatically it's confusing for developers to provide a new instance of `TreeItem` with a different `collapsibleState` from previous iterations of `getTreeItem` and get the wrong results. 

Using the `reveal` API creates indirection. In the data provider, we need to cache all object to be revealed, and on the upper hierarchy create a function that takes the `TreeView` item we created along with the data explorer to reveal based on a condition. Say an event outside triggers the `expand` action, then you have even more indirection because the said function will have to listen for this event as well.
