### ISSUE TITLE
 Assertion failed (item already registered:

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12702]
Issue Id: <b>479996f1-d919-855f-5e8e-02eff2cbc0f5</b><br /><br />*Versions* <br />- 1.6.0-insider (9/20/2016 6:06:54 AM)<br />*Stack* <br />Error: Assertion failed (item already registered: <br />[/vs/base/common/assert.ts#L12:8](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/base/common/assert.ts#L12:8)<br />[/vs/editor/contrib/linesOperations/common/moveLinesCommand.ts#L84:56 (model)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/linesOperations/common/moveLinesCommand.ts#L84:56 (model))<br />[/vs/editor/contrib/linesOperations/common/sortLinesCommand.ts#L95:12 (getSortData)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/linesOperations/common/sortLinesCommand.ts#L95:12 (getSortData))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L150:9 (prototype)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L150:9 (prototype))<br />[/vs/editor/common/core/range.ts#L320:23 (startColumn)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/common/core/range.ts#L320:23 (startColumn))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L103:22 (push)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L103:22 (push))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L175:10 (_snippet)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L175:10 (_snippet))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L211:10 (Number)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L211:10 (Number))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L165:8 (placeHolder)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L165:8 (placeHolder))<br />[/vs/editor/contrib/snippet/common/snippet.ts#L302:2 (placeHolders)](https://github.com/microsoft/vscode/blob/0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0/src/vs/editor/contrib/snippet/common/snippet.ts#L302:2 (placeHolders))<br />

**Comment by ramya-rao-a** [comment]
Some test case?

**Comment by joaomoreno** [comment]
@ramya-rao-a The error message is impossible with that stack. That message comes from the tree world:

![image](https://cloud.githubusercontent.com/assets/22350/18903190/f49e2924-8557-11e6-8914-3e4beff3e9ca.png)

The stack seems to have nothing to do with the tree.
