### ISSUE TITLE
Cancel from quickpick of debug configurations provided by extension does not reset list choice

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#127093]
Issue Type: <b>Bug</b>

1. Clone, build and run microsoft/vscode-mock-debug 
2. Switch to 'Run and Debug' activity.
3. From the dropdown choose 'Mock Debug...' to trigger the call to `provideDebugConfigurations`
4. When the quickpick offers the provided configurations, press Esc to dismiss.
5. :bug: observe that the dropdown still shows 'Mock Debug...' as the selected item, but in fact the item previously selected before step 3 is what gets used when the 'play' button is clicked. Only at that point does the item shown in the collapsed dropdown update to the correct value.

![junk](https://user-images.githubusercontent.com/6726799/123300311-607f1180-d512-11eb-88a7-039229477476.gif)

A side effect of the step 4 escape not having reset the list selection is that I can only re-trigger the quickpick by first picking one of the known configurations (above the horizontal line), then re-selecting 'Mock Debug...'

This also happens in 1.57.1 so it is not a regression.

VS Code version: Code - Insiders 1.58.0-insider (3caebff71e514ece73b125468881d102e767ee4d, 2021-06-24T05:13:30.907Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isidorn** [comment]
Thanks for filling this issue and for this PR, however this code is a bit delicate and I would not be comfortable to change it before we start the endgame.
Thus I am assigning to next milestone, August since July I am on vacation.
