### ISSUE TITLE
Cannot read property 'toCustomLabel' of undefined

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#12709]
- VSCode Version: Code - Insiders 1.6.0-insider (be5e8d5733c1c012d7e3a6c7e049b59d67c13978, 2016-09-26T06:05:01.421Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Started vscode
2. Hit Cmd+Shift+F

Got this:

![image](https://cloud.githubusercontent.com/assets/1723815/18858799/b8e824fa-843c-11e6-9644-3f9549132fb8.png)

**Comment by wallverb** [comment]
Turns out that Rest Client extension was causing this. Wondering if there is any way VSCode could know which extension is causing an issue and present that information

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by carmanchris31** [comment]
I'm guessing Rest Client offers a keybinding that overwrites one of the new bindings for project search options. This error apparently crops up when there's not an available keybinding for each of the functions (whole word, exact case, regex). See: https://github.com/Microsoft/vscode/issues/13447

**Comment by lypscan** [comment]
No, it's not a problem with Rest Client, I uninstalled that extension and I still can't use the search in project feature anymore. It's frustrating, and it happened right after the 1.6.0 official vs Code update.

**Comment by jrieken** [comment]
@sandy081 I believe this is the search viewlet issue, right?

**Comment by sandy081** [comment]
@jrieken Yes which is being tracked here #13447
