### ISSUE TITLE
Weird backspace handling in terminal/pwsh

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#127098]
Issue Type: <b>Bug</b>

I'm only seeing this in integrated terminal but not the windows terminal: when the cursor is at the start backspace will always move to the left and then restore the whitespace

![recording (11)](https://user-images.githubusercontent.com/876920/123308311-59d3a880-d4d8-11eb-9ce7-73fec9146cf1.gif)

VS Code version: Code - Insiders 1.58.0-insider (3caebff71e514ece73b125468881d102e767ee4d, 2021-06-24T05:13:30.907Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by Tyriar** [comment]
Probably local echo

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/126209
