### ISSUE TITLE
 Cannot read property 'configuration' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12700]
Issue Id: <b>fefbfd38-09c9-1fea-e522-93833c8f3d9c</b><br /><br />*Versions* <br />- 1.5.3<br />-  66f37fd2a99eb9d628dd374d81d78835b410c39b<br />*Stack* <br />TypeError: Cannot read property 'configuration' of null<br />[/vs/code/electron-main/windows.ts#L1129:8 (sendToFocused)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/code/electron-main/windows.ts#L1129:8 (sendToFocused))<br />[/vs/editor/common/modes/linkComputer.ts#L29:18 (/)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/linkComputer.ts#L29:18 (/))<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L88:30 (lexer)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L88:30 (lexer))<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L240:36](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L240:36)<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L193:31 (substituteMatches)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L193:31 (substituteMatches))<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L338:34](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L338:34)<br />[/vs/editor/common/modes/monarch/monarchCommon.ts#L19:1](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCommon.ts#L19:1)<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L240:36](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L240:36)<br />[/vs/editor/common/modes/monarch/monarchCompile.ts#L209:33](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/monarch/monarchCompile.ts#L209:33)<br />[/vs/editor/common/modes/linkComputer.ts#L73:40 (charCodeAt)](https://github.com/microsoft/vscode/blob/5be4091987a98e3870d89d630eb87be6d9bafd27/src/vs/editor/common/modes/linkComputer.ts#L73:40 (charCodeAt))<br />

**Comment by bpasero** [comment]
Invalid stack. @ramya-rao-a fyi those linenumbers and callstack do not make sense to me when I follow the traces.

**Comment by ramya-rao-a** [comment]
@bpasero agreed, I'll follow up
