### ISSUE TITLE
Terminal defaultLocation editor causes panel's + button to create in the editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127099]

**Comment by meganrogge** [comment]
The terminal commands `NewWithProfile `and `Split `are used for both the panel buttons and the commands in the CP (that we do want to use the defaultLocation for). Not sure how to differentiate between them - don't think we want to duplicate the actions.

**Comment by Tyriar** [comment]
Let's wait until after https://github.com/microsoft/vscode/issues/126256 is done since that will likely add target support to the create commands

**Comment by meganrogge** [comment]
Other reproes:

- Ctrl / Cmd J to open the panel -> 🐛 terminal editor is created
- focus the terminal editor, click the trash can on the panel , close the editor tab -> 🐛 a bunch of errors in the console
