### ISSUE TITLE
Allow to install more then one extensions and enable all together

### ISSUE THREAD

**Issue by carloscds** [Microsoft/vscode#12703]
- VSCode Version: 1.5.3
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open Extensions
2. Type, for example: Java
3. Now we need to install: Java Debug, Java Properties and Java Snippets
4. I need to install each one and restart VS Code, seach extension again and repeat this process

My sugestion is: I can install more then one extension and after this I can restart VSCode. Like Visual Studio Extensions.

**Comment by joaomoreno** [comment]
Tip: install all tree and just enable one. They will all be enabled. Enabling (for now) simply reloads the window, which causes to load all installed extensions.

**Comment by carloscds** [comment]
@joaomoreno Thanks Joao.
