### ISSUE TITLE
Reopen editor with context key is based on active not selected editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127083]
Repro:

1. Open welcome page
2. Right click tab, notice there is no reopen editor with option
3. Click another tab
4. Right click the welcome page, reopen editor with is there

<img width="425" alt="Screen Shot 2021-06-24 at 6 44 17 AM" src="https://user-images.githubusercontent.com/2193314/123273721-c0949a00-d4b7-11eb-86f9-4e9792fd2371.png">
<img width="355" alt="Screen Shot 2021-06-24 at 6 44 22 AM" src="https://user-images.githubusercontent.com/2193314/123273738-c2f6f400-d4b7-11eb-8b1b-b9e58ed81d54.png">

**Comment by lramos15** [comment]
It's interesting as the reopen with is actually being performed on the untitled file even though you have the welcome page selected

**Comment by Tyriar** [comment]
Looks like it shows up based on the _active editor_, not the selected editor:
 https://github.com/Microsoft/vscode/blob/97d576cb08586d33e30419c91da05a80acf8cf8f/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L308-L308

**Comment by bpasero** [comment]
@lramos15 when implementing context menu actions for editor tabs, you need to look at the passed in context instead of just going to the active editor. Here is an example how the "Close Others" action knows what the editor is under the mouse:

https://github.com/microsoft/vscode/blob/75aa22e7d99b6353bfc4543218d50d04fbbe04cf/src/vs/workbench/browser/parts/editor/editorCommands.ts#L814-L814

If a method there is not exported but you need it, we can see to export it maybe from `editor.ts`.

**Comment by bpasero** [comment]
Similar for commands that are shared between explorer and tab: 

https://github.com/microsoft/vscode/blob/853f91719012c16d1cbfa6f55678e54700d61c7f/src/vs/workbench/contrib/files/electron-sandbox/fileActions.contribution.ts#L39-L40

**Comment by lramos15** [comment]
@bpasero Thanks for the pointers I have gone ahead and implemented this. The last remaining issue is that the context key for showing the command is based on the active editor and I didn't seem to find an example of one based on the selection. Should we just no-op in that case similar to if you select the last editor tab and click `Close to Right`

**Comment by bpasero** [comment]
Yeah true, we might not have a context key for that yet. I am fine doing a no-op then.

**Comment by lramos15** [comment]
Do we think this is good to close? There's no context key for selected editor which this is the scenario which I can cover; if a user selects another tab and does reopen with, operate on that if possible. If an editor can't be reopened such as Welcome then No-op. The downside is that if the user has the welcome tab active the enablement is based on the active tab and therefore other tabs would be disabled from being selected and reopend with. This was the same as before and not new behavior.

**Comment by bpasero** [comment]
This seems to work OK, but I would expect the editor to become active when I picked "Reopen with...". Currently the editor seems to stay inactive.

**Comment by lramos15** [comment]
I'm going to disagree just because no other actions like pin, or split make the editor which is acted upon active.

**Comment by bpasero** [comment]
Yeah but this action is specifically saying "Re-Open", isn't that a hint that the user wants to see the contents?

**Comment by lramos15** [comment]
Adding focus isn't an easy implementation right now. File #134131 for underlying problems. Closing this one
