### ISSUE TITLE
Linked editing bug when using frameworks

### ISSUE THREAD

**Issue by kwiksilver3441** [microsoft/vscode#127003]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
- OS Version: Windows 21H1

Steps to Reproduce:

1. Enable linked editing
2. Create a vue app, 
3. Linked editing doesn't natively work for framework apps.
4. Change any html element in the template and it doesn't auto edit.

**Comment by IllusionMH** [comment]
/duplicate of https://github.com/vuejs/vetur/issues/565 for Vue and #85707 for JSX

It's not a bug. Linked editing only supported in HTML out of box at this moment.
