### ISSUE TITLE
Correctly format jsdoc/tsdoc @tags in hover popup

### ISSUE THREAD

**Issue by antoinep92** [microsoft/vscode#127002]
Issue Type: <b>Feature Request</b>

VS Code version: Code - OSS 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-16T15:21:33.370Z)
OS version: Linux x64 5.12.10-arch1-1

Currently for jsdoc/tsdoc comments in javascript/typescript files are shown in the tooltip when hovering the described symbol. This is really useful to get contextual documentation.

This problem is that the tooltip could be smarter. Currently, it handles most tags as a newline + italics + dash, which is not appropriate for many tags:
![image](https://user-images.githubusercontent.com/1839108/123121620-9b674380-d445-11eb-8acd-2d1b44276cc0.png)

I found [this](https://github.com/microsoft/tsdoc/issues/198) related issue, but thought it would be interesting to mention it here, because it isn't clear if this should be implemented as an extension or in vscode core ?

**Comment by mjbvz** [comment]
Please fill in the issue template

/needsMoreInfo

**Comment by antoinep92** [comment]
> Please fill in the issue template

Sorry about that, but I'm not sure what you mean. I didn't remove any comment from the github template. I added the version information and copy-pasted elements from the builtin issue reporter, if that helps :thinking:

**Comment by mjbvz** [comment]
Thanks. Yes we mainly want the version info.

Can you check if this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by antoinep92** [comment]
@mjbvz Thanks for the suggestion.
Works a lot better with insiders build !
Disabling extensions has no effect though.

So I guess this has already been implemented in master, and I'll wait for the next release.
