### ISSUE TITLE
Enable WebCodec support in VS Code (electron)

### ISSUE THREAD

**Issue by koush** [microsoft/vscode#127023]
WebCodec is a new API that allows hardware/software decoding of video codecs to be exposed to Window and Workers. I need this feature to enabled in electron to bring Vysor (https://vysor.io) to VS Code as an extension.

```js
app.commandLine.appendSwitch('--enable-blink-features', 'WebCodecs');
```

**Comment by koush** [comment]
It seems that there's only a specific list of electron args that can be passed through:

https://github.com/microsoft/vscode/blob/400a80796db7433c05a1e5377e8e07ec683d12ca/src/main.js#L142

Ideally though, it should just be enabled by default.

**Comment by bpasero** [comment]
This is unlikely to happen given the security advice here: https://github.com/microsoft/vscode/pull/127024
