### ISSUE TITLE
 Cannot read property 'body' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12707]
Issue Id: <b>2cef3fdb-c032-eece-902a-e3d208d0f5c5</b><br /><br />*Versions* <br />- 1.5.2<br />-  5be4091987a98e3870d89d630eb87be6d9bafd27<br />*Stack* <br />TypeError: Cannot read property 'body' of null<br />[/vs/workbench/parts/debug/electron-browser/debugService.ts#L1038:50 (body)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1038:50 (body))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L747:0 (then)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L747:0 (then))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1052:0 (_run)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1052:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1209:0 (_setCompleteValue)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1209:0 (_setCompleteValue))<br />

**Comment by ramya-rao-a** [comment]
Occurs in 1.5.3 and in 1.6 insiders too.
1 other place with same error, same file but slightly different call stack narrows down the issue to the below line
https://github.com/Microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L1038

**Comment by isidorn** [comment]
Fixed in latest

**Comment by roblourens** [comment]
@isidorn @ramya-rao-a I can verify if either of you have repro steps?

**Comment by ramya-rao-a** [comment]
@roblourens you can check kusto for error events and make sure this error with similar callstack does not appear

**Comment by isidorn** [comment]
We do not verify error-telemtry usually. If it is not fixed it will just come back again.
Though if you would like to verify just do a code review - check that part of the code and you will see it is now imposible for that field to be null
