### ISSUE TITLE
auto refrsh task output should refresh the main screen too

### ISSUE THREAD

**Issue by jeffery9** [Microsoft/vscode#12706]
VSCode Version: 1.5.3  with pythonVScode
OS Version: win10
Steps to Reproduce:

use vscode to run any python server application, like Odoo
open file in main screen, and show the command output. move the mouse cursor to any lines, when the command output refresh, the main screen should be refresh too. 

see  ref. to #12300 
![animation 9](https://cloud.githubusercontent.com/assets/1404460/18858477/f62e84be-849e-11e6-9ab2-4155339f7520.gif)

**Comment by dbaeumer** [comment]
@jeffery9 please file the issue to the owner of the Python plugin you use. I assume you couldn't reproduce this behavior with --disable-extensions as outline in #12300.
