### ISSUE TITLE
[themes] Dark theme uses much more colors than light theme for both JS and TS

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1270]
Compare the two screenshots. We use much more colors in the dark theme. This is not consistent since those two are the default themes and they should be symetric imho. Both for Typescript and Javascript
@stevencl @bgashler1 opinions welcome

<img width="462" alt="screen shot 2015-12-14 at 14 57 28" src="https://cloud.githubusercontent.com/assets/1926584/11782726/0ed57fe0-a273-11e5-9d65-0960c1aaf337.png">
<img width="535" alt="screen shot 2015-12-14 at 14 58 04" src="https://cloud.githubusercontent.com/assets/1926584/11782734/1a960dfe-a273-11e5-8371-fb02d4b601ab.png">

**Comment by aayushkapoor206** [comment]
@isidorn Could this be the issue for #1269 ?

**Comment by stevencl** [comment]
Agreed, this should be consistent (in terms of what gets coloured that is, not in terms of the specific colours). What is the reason for the param name or function name not being coloured in the light theme? Do we just not have good colours specified for the light theme? If so, could @bgashler1 suggest something?

**Comment by bgashler1** [comment]
I agree this is a problem with consistency, and it needs to be addressed.  I'll try out some colors that can make up for the missing ones in the light theme.

**Comment by aeschli** [comment]
fix delivered, I removed the yellow and turquise. The goal is to stay as close as possible to the original Visual Studio light and dark themes. For users that like more colors we have custom themes even from extensions.

**Comment by isidorn** [comment]
But turquise we still use in light theme. Maybe bring back turquise, since now interface names are colored in dark theme but not in light -> inconsistent

**Comment by aeschli** [comment]
I removed turquise from the light theme as well. We are now consistent to what we had in 0.9.0.
