### ISSUE TITLE
cannot use `⌘ - '` as keyboard shortcut 

### ISSUE THREAD

**Issue by dmiracle** [microsoft/vscode#127089]
Issue Type: <b>Bug</b>

On Mac OS 

1. Open keyboard shortcuts
2. Try to assign `⌘ - '` to a shortcut

I am unable to assign it and previous shortcut with that assignment does not work.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 092f7002-6078-42ba-b658-ccef5fe0bd26|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by dmiracle** [comment]
For what it's worth I am unable to reproduce this on another computer but reinstalling vscode on this machine does not remedy the problem

**Comment by alexdima** [comment]
@dmiracle I don't think I understand exactly your keybinding `⌘ - '`. 

Do you mean you want to define a chord keybinding i.e. `⌘ -`, `⌘ ''?

**Comment by dmiracle** [comment]
Sorry for the confusion. I mean the chord `⌘ '`

**Comment by dmiracle** [comment]
Sorry for the confusion. I mean the keybinding for `⌘ '`

**Comment by alexdima** [comment]
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`cmd + '`).
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by dmiracle** [comment]
This works now, I don't know what the problem was.
