### ISSUE TITLE
Typescript Server not validating userdefinded type guards correctly

### ISSUE THREAD

**Issue by saschaB91** [microsoft/vscode#127095]
Issue Type: <b>Bug</b>

This error is only shown when using the TypeScript-Server not when compiling code.
When using an generic class with a method as type guard, it will only be validated correctly if you do not extend the generic type.
The first class is ok but the second shows an error on "this.f(val)" even though nothing changed

```
class TestClass<T> {
    typeguard(val: unknown): val is T {
        return true;
    }
    f(v: number): void {}
    h(v: T): void {}
    func(val: T | number): void {
        if (this.typeguard(val)) {
            this.h(val);
            return;
        }
        this.f(val);
    }
}
```

```
class TestClass2<T extends Date> {
    typeguard(val: unknown): val is T {
        return true;
    }
    f(v: number): void {}
    h(v: T): void {}
    func(val: T | number): void {
        if (this.typeguard(val)) {
            this.h(val);
            return;
        }
        this.f(val);
    }
}
```

edit: I finally figured out how code highlighting worked -.-

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.55GB free)|
|Process Argv|--crash-reporter-id 018d5f0a-4f0e-441f-bcd3-64bd2451c4cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
project-manager|ale|12.2.0
ng-template|Ang|12.0.5
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.13.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.0.1
vscode-pull-request-github|Git|0.27.1
gitlab-workflow|Git|3.23.3
angular2-switcher|inf|0.3.4
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|12.0.0
csharp|ms-|1.23.12
powershell|ms-|2021.6.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
sort-lines|Tyr|1.9.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30324779
binariesv615:30325510
vsccppwtct:30322537

```

</details>

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by saschaB91** [comment]
Sorry for the wrong repo :(

New issue filed:
https://github.com/microsoft/TypeScript/issues/44814
