### ISSUE TITLE
Terminal Integrated  Font Size  not change dynamically

### ISSUE THREAD

**Issue by oshriPP** [microsoft/vscode#127069]
Issue Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: <b>Yes</b>

After the last update, changing the terminal font size ("terminal.integrated.fontSize") taking place only in the next time I open a new terminal and not on the actives terminals.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (1.24GB free)|
|Process Argv|. --crash-reporter-id edc7bfca-3e2d-4741-9a96-f93d13f00048|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.1.0
preview-pdf|ana|1.0.0
cform|aws|0.0.24
spellright|ban|3.0.58
vscode-markdownlint|Dav|0.42.1
gitlens|eam|11.5.1
fontsize-shortcuts|fos|1.5.0
shell-format|fox|7.1.0
go|gol|0.26.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
haskell|has|1.4.0
vscode-drawio|hed|1.5.0
haskell-linter|hoo|0.0.6
nbpreviewer|jit|1.2.2
golang-tdd|joa|0.0.9
vscode-graphviz|joa|0.0.6
language-haskell|jus|3.4.0
copy-github-url|mat|0.6.0
brittany|Max|0.0.9
dotenv|mik|1.0.1
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.5.4
hide-gitignored|npx|1.1.0
phoityne-vscode|pho|0.0.26
quicktype|qui|12.0.46
vscode-data-preview|Ran|2.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
ispy|Ric|0.0.4
addDocComments|ste|0.0.8
auto-correct|syg|0.2.2
shellcheck|tim|0.14.3
serverless-snippets|Tim|0.1.0
stylish-haskell|vig|0.0.10
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by arkady** [comment]
A workaround until the bug is fixed: You can make an existing terminal pick up the new font size by resizing it -- for some reason _that_ makes it realize that the setting has changed.
