### ISSUE TITLE
Debug AdapterManager/DebugService has recursive instatiation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127016]
I don't have repro steps for this, but I've been hitting this pretty constantly in OSS on ~80% of refreshes. This breaks the extension host too:

![](https://memes.peet.io/img/21-06-42593eab-58a4-47a8-bb79-9415fd587a32.png)

The context key change that triggers the visibility of the REPL view to update is `debuggersAvailable` being set to `true` here: https://github.com/microsoft/vscode/blob/a24a10dbd244f340509e6a15deab53d70e95e4b3/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L63

Maybe if the extension host comes up too fast this happens?

**Comment by weinand** [comment]
yes, I've noticed this this week too. I'm not aware of any changes in debug land.

**Comment by isidorn** [comment]
Sorry about this, I will fix it today
Dup of https://github.com/microsoft/vscode/issues/126339
