### ISSUE TITLE
Spread Opperator False Error

### ISSUE THREAD

**Issue by Doopdon** [microsoft/vscode#127018]
I am trying to get a red line to go away on a .ts file in an angular application.

The application builds and compiles just fine so I see no reason why this error should be shown.

I have updated all my "tslib" refferences to "^1.10.0" and have tried using "moduleResolution": "node" in the tsconfig file. but it was already set to "node".

At this point I am fairly confident it is an issue with the vscode ide itself.  Here is a screen shot
![typescriptbug](https://user-images.githubusercontent.com/9811290/123159257-0a36a380-d42a-11eb-9883-cee1d2d58163.png)

**Comment by mjbvz** [comment]
Please fill in the issue template and share minimal example code that demonstrates the issue

/needsMoreInfo
