### ISSUE TITLE
Can't paste file name text when rename image file

### ISSUE THREAD

**Issue by klueless-io** [microsoft/vscode#127042]
Issue Type: <b>Bug</b>

This issue is probably related to a [Can't Copy](https://github.com/microsoft/vscode/issues/126458), it has all the same problems that are reported in that bug, but instead of being related to the Copy `Ctrl/Command+C` key binding, it is related to the Paste `Ctrl/Command+V` key binding.

Reproduction Steps

1. Select some text and press `command+c`
![image](https://user-images.githubusercontent.com/2956762/123190219-796fce80-d4e2-11eb-8b79-1e4cdd65049e.png)

2. I can paste in to the text editor without issues

![image](https://user-images.githubusercontent.com/2956762/123190279-999f8d80-d4e2-11eb-8e04-8a2e058b72a5.png)

3. I can paste into a the file name for regular .rb file name

![image](https://user-images.githubusercontent.com/2956762/123190352-be940080-d4e2-11eb-80b1-a503bef49d80.png)

4. I can't paste into a the file name for a.png file name

> Warning Will Robinson

`command+v` is not working

![image](https://user-images.githubusercontent.com/2956762/123189748-b5566400-d4e1-11eb-82ff-f1c0832c61be.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.63GB free)|
|Process Argv|-psn_0_794818 --crash-reporter-id 5534e9ef-10e0-4b4d-848e-f05cde38340f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by isidorn** [comment]
Dup of a known issue assigned to @lramos15 @mjbvz
