### ISSUE TITLE
Snap packages fail validation

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127081]
Snap packages are now failing validation with the following two errors:

- found errors in file output: unusual mode 'rwsr-xr-x' for entry './usr/share/code-insiders/chrome-sandbox' security-snap-v2_squashfs_files
- checksums do not match. Please ensure the snap is created with either 'snapcraft pack <DIR>' (using snapcraft >= 2.38) or 'mksquashfs <dir> <snap> -noappend -comp xz -all-root -no-xattrs -no-fragments' (using squashfs-tools >= 4.3). If using electron-builder, please upgrade to latest stable (>= 20.14.7). See https://forum.snapcraft.io/t/automated-reviews-and-snapcraft-2-38/4982/17 for details. security-snap-v2_squashfs_repack_checksum What does this mean?

Very likely broken by https://github.com/microsoft/vscode/commit/92999c339e2666998bd45d13fa355cecc7947b8b, specifically https://github.com/microsoft/vscode/commit/92999c339e2666998bd45d13fa355cecc7947b8b#diff-74c4ea7e8a7229121137b67faf75b6808d948fbbd120adb7b0f763a52b975dedR30-R32

**Comment by joaomoreno** [comment]
Related: https://github.com/electron-userland/electron-installer-snap/issues/74

**Comment by deepak1556** [comment]
Where does the validation happen in our ci pipeline ? I was only checking the publish steps here https://dev.azure.com/monacotools/Monaco/_build/results?buildId=124711&view=results

**Comment by rzhao271** [comment]
@joaomoreno has the issue been fixed now? I'm not sure how one verifies this issue.

**Comment by deepak1556** [comment]
To verify locally `SNAP_ENFORCE_RESQUASHFS=1 snap-review <path-to>/code-insiders.snap`. I have verified this, marking accordingly.
