### ISSUE TITLE
Make NotebookController.notebookType optional

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#127048]
My extension, [Go Notebook Kernel](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.go-notebook-kernel), defines a kernel and creates a notebook controller for that kernel. The type of notebook is irrelevant to this kernel, but the notebook type parameter is required, so it specifies `markdown-notebook`. I would rather not specify a type, because the kernel will happily execute any Go kernels in any notebooks, so this is an artificial restriction.

**Comment by jrieken** [comment]
You can use `*` as value to signal that your controller support all types
