### ISSUE TITLE
Tasks problemMatcher is getting truncated lines

### ISSUE THREAD

**Issue by ababak** [microsoft/vscode#127073]
Issue Type: <b>Bug</b>

The lines are truncated on terminal window width and my regular exression that ends with "$" matches incomplete lines.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Windows_NT x64 10.0.18363
Remote OS version: Windows_NT x64 10.0.18363
Remote OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
vscode-usda-syntax|ani|0.2.0
gitlens|eam|11.5.1
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999660014
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.0-insiders2
hexeditor|ms-|1.7.1
autodocstring|njp|0.5.4
psi-header|psi|1.15.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
vscextlang:30322306
binariesv615:30325510

```

</details>

**Comment by ababak** [comment]
```
"pattern": {
    "regexp": "^(?:C:)?\\\\(.*)\\((.+)\\):\\s+(warning|error) (\\w{1,2}\\d+):\\s+(.*)$",
    "file": 1,
    "location": 2,
    "severity": 3,
    "code": 4,
    "message": 5
}
```
<img width="871" alt="Screenshot 2021-06-24 at 14 11 09" src="https://user-images.githubusercontent.com/11334363/123253668-623adc00-d4f6-11eb-8f03-ba3217847a66.png">

<img width="870" alt="Screenshot 2021-06-24 at 14 11 35" src="https://user-images.githubusercontent.com/11334363/123253572-4b948500-d4f6-11eb-8289-4f58c2797097.png">

**Comment by alexr00** [comment]
@ababak can you please share any terminal related settings you have set?

**Comment by ababak** [comment]
@alexr00 that's all I've found
```
"terminal.integrated.rendererType": "experimentalWebgl",
"terminal.integrated.fontSize": 14,
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.scrollback": 10000,
```

**Comment by ababak** [comment]
The output is coming from Python script that runs a Windows docker container that performs the build, if it matters.

**Comment by alexr00** [comment]
@ababak are you using the Remote SSH extension when you're seeing this issue?

@Tyriar and @meganrogge this kind of issue usually stems from a terminal line wrapping issue. Any ideas?

**Comment by ababak** [comment]
Yes, I am using Remote SSH on a Mac to connect to my work Windows PC.
I've just tested this directly on target PC and it seems that the problem is only with the Remote SSH.

**Comment by Tyriar** [comment]
@alexr00 the hack is fixed and removed for newer versions of Windows (build 21376+) https://github.com/microsoft/vscode/issues/91898. I don't think there's anything we can do other than wait.

**Comment by alexr00** [comment]
@Tyriar it's just a bit strange that the issue would occur only when SSHing into the PC, but not when using VS Code locally on the PC without SSH. 

@ababak since your PC is a work PC it seems likely you're unable to update it. @Tyriar is there anything else we can suggest users do in this case other than wait until their work decides its time to update?

**Comment by ababak** [comment]
@alexr00 Thanks for the suggestion, I'll speak with our IT guys about the updates.

**Comment by Tyriar** [comment]
@alexr00 winpty used to be forced for remotes but I believe that restriction is removed now after https://github.com/microsoft/vscode/issues/71966 was fixed, I couldn't find anywhere special casing remotes. Regardless only Windows Insiders are on the build that enables wrapping support yet. I can't explain why it's just happening on remotes for @ababak.

**Comment by alexr00** [comment]
Ok, I will leave it up to you @Tyriar to decide what you want to do with this issue then.

**Comment by Tyriar** [comment]
Don't think we can do anything but wait for Windows to update, the good new is I expect it to be fixed and work well in Windows 11.
