### ISSUE TITLE
Long waiting time for debugging

### ISSUE THREAD

**Issue by 569890172** [microsoft/vscode#127052]
Operating system: macOS Catalina 10.15.4
Version: 1.57.1
Submit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.4.0
Problem description: Debugging react-native mode Attach to packager, breakpoint debugging has been waiting for a long time
<img width="977" alt="WX20210624-141023@2x" src="https://user-images.githubusercontent.com/5674114/123212415-58fe3f00-d4f7-11eb-9812-51df8068271c.png">

**Comment by isidorn** [comment]
Seems like that scope is very slow to expand. This is coming from the debug extension you are using, which one is that?
Can you please provide exact repro steps?

**Comment by 569890172** [comment]
> Seems like that scope is very slow to expand. This is coming from the debug extension you are using, which one is that?
> Can you please provide exact repro steps?
Debugging plugin: React Native Tool
Steps: 1. Run Debug iOS
                     2. Run Attach to packager
                     3. Click single point debugging on any line of code, there will be a long waiting process, after a long time waiting for success, you can debug normally.
                     
<img width="1029" alt="WX20210624-171448@2x" src="https://user-images.githubusercontent.com/5674114/123237127-f5ccd680-d50f-11eb-8b04-e073b77f42bc.png">

Note: I have installed the vscode version to version 1.52, and this will not happen. I have tried to restart the computer.

**Comment by isidorn** [comment]
Yeah that does not really answer my question...
