### ISSUE TITLE
visual studio code frozen after some idle time and process cant be killed

### ISSUE THREAD

**Issue by thinkInbit** [microsoft/vscode#127014]
I deleted my previous app which was working fine and installed latest **visual studio code (VSCode-darwin-universal 1.57.1).**
It worked fine for couple of hours and after some time when I was using my IntelliJ app and came to it, I found it **unresponsive**.

1. When I found, I tried quitting the application from doing right +click on visual studio code icon and quit- nothing happened.
2. Then I tried force quit -still nothing happened.
3. opened activity monitor-saw electron(not responding)- tried quit and force quit- still nothing.
4. then tried everything from this post How to [How to “killall” Visual Studio Code in Terminal?](https://apple.stackexchange.com/questions/291328/how-to-killall-visual-studio-code-in-terminal?newreg=e161c24c4c714106838b9795514c23b9) - still nothing.

Also in the mac taskbar, the icon is not present but if I try to relaunch I get an error message saying
"**Another instance of Code is running but not responding
Please close all other instances and try again.**"

below are my system details and please let me know if extra information is needed.

**visual studio code**
package name: VSCode-darwin-universal.zip
version : 1.57.1

**system**
mac Os catalina
version 10.15.7

**Comment by bpasero** [comment]
Steps to reliably reproduce?

**Comment by thinkInbit** [comment]
it only happened once after fresh installation when application was idle and few files were edited before that.
Not sure what caused. It's working fine after mac system restart.
If  I can help with some log files , please let me know?
