### ISSUE TITLE
Changing integrated terminal to other terminals like kitty terminal

### ISSUE THREAD

**Issue by j0k4rX** [microsoft/vscode#127051]
**Describe the feature you'd like.**
I want to change my vscode integrated terminal (from deafult one) to kitty terminal

**Comment by Tyriar** [comment]
This isn't possible, we can't embed another terminal in VS Code.

**Comment by j0k4rX** [comment]
Ok. Got it.
May i ask what is the default integrated terminal?
is it gnome-terminal?

**Comment by Tyriar** [comment]
It uses xterm.js+node-pty which is what powers hyper, fluent terminal, etc.
