### ISSUE TITLE
 Cannot read property 'startLineNumber' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12701]
Issue Id: <b>290174b7-3f67-d10a-8ec2-ae06f4fc55e8</b><br /><br />*Versions* <br />- 1.6.0-insider (9/21/2016 6:31:53 AM)<br />*Stack* <br />TypeError: Cannot read property 'startLineNumber' of undefined<br />[/vs/editor/common/model/textModel.ts#L231:2 (this)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModel.ts#L231:2 (this))<br />[/vs/editor/common/model/textModelWithMarkers.ts#L39:7 (oldColumn)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModelWithMarkers.ts#L39:7 (oldColumn))<br />[/vs/workbench/parts/files/common/textFileServices.ts#L88:3](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/workbench/parts/files/common/textFileServices.ts#L88:3)<br />[/vs/editor/common/model/textModelWithMarkers.ts#L60:8 (prototype)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModelWithMarkers.ts#L60:8 (prototype))<br />[vs/workbench/workbench.main.js#L56545:46](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/srcvs/workbench/workbench.main.js#L56545:46)<br />[/vs/base/common/mime.ts#L205:3](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/base/common/mime.ts#L205:3)<br />[/vs/base/common/objects.ts#L227:2 (arr)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/base/common/objects.ts#L227:2 (arr))<br />[/vs/editor/common/model/textModelWithMarkers.ts#L208:9 (result)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModelWithMarkers.ts#L208:9 (result))<br />[/vs/editor/common/model/textModelWithMarkers.ts#L34:1](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModelWithMarkers.ts#L34:1)<br />[/vs/editor/common/commonCodeEditor.ts#L140:7 (_contextKeyService)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/commonCodeEditor.ts#L140:7 (_contextKeyService))<br />

**Comment by ramya-rao-a** [comment]
The trace doesn't make sense to me. The below has no reference to "startLineNumber"

>[/vs/editor/common/model/textModel.ts#L231:2 (this)](https://github.com/microsoft/vscode/blob/90dda7af651fc557d40b166f322db3f014e8f33b/src/vs/editor/common/model/textModel.ts#L231:2 (this))

This was seen only in the insider build dated 9/21 and not seen later.

Feel free to close
