### ISSUE TITLE
Codicons for Git when browsing commits that are indexed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#127070]
We added support to remote hub that moves a user automatically to a commit that is indexed to get enhanced code navigation features (e.g. go to declaration, find all references, ....). 

Technically the user is still browsing the branch but certain actions might behave differently. For example syncing might only move the user to the next best indexed commit. To indicate that in the UI the tooltip already contains a corresponding hint:

<img width="278" alt="capture" src="https://user-images.githubusercontent.com/1931590/123246472-1d0eae00-d4e6-11eb-9a8a-a7143b33433e.png">

However it would be cool to also indicate that in the corresponding icon (e.g. git-branch) with a corresponding overlay. This could be for example a little database icon to indicate the index. 

@misolori any other ideas? And could we add these to the set of codicons?

**Comment by dbaeumer** [comment]
@joaomoreno @eamodio FYI.

**Comment by misolori** [comment]
This was already fixed via https://github.com/microsoft/vscode-codicons/issues/71 & https://github.com/microsoft/vscode/commit/b78904a19ac4b7191cfdeb512a9367b5afa593b4

**Comment by rzhao271** [comment]
@misolori can you provide some verification steps for this issue? I tried opening a repo that I've opened before, but I don't think I ended up on an indexed commit.

**Comment by misolori** [comment]
This is mainly about verifying that the icons can be used. For verification:

Create a status bar item via an extension or use tasks to reference a codicon in the label (see snippet below). You should be able to set the following codicons:

```json
    "tasks": [
        { "label": "$(layers) layers", "command": "echo" },
        { "label": "$(layers-dot) layers-dot", "command": "echo" },
        { "label": "$(layers-active) layers-active", "command": "echo" },
        { "label": "$(compass) compass", "command": "echo" },
        { "label": "$(compass-dot) compass-dot", "command": "echo" },
        { "label": "$(compass-active) compass-active", "command": "echo" },
    ]
```
- `layers-dot`
- `layers-active`
- `compass`
- `compass-dot`
- `compass-active`

**Comment by stuartleeks** [comment]
Created an extension to add the icons to the statusbar and they all show up fine: 
![image](https://user-images.githubusercontent.com/1824461/127460274-fa7a8f77-b5b9-4aac-8135-25e801efc35c.png)
