### ISSUE TITLE
Can't change setting 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#127017]
Version: 1.58.0-insider
Commit: 9744231fc12f1aed21089180b3f0394d694bd2a2
Date: 2021-06-23T05:12:34.290Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

When clicking the checkbox in the following situation, nothing happens. There are no errors in the settings file. I haven't tried if other settings types are effected.

![image](https://user-images.githubusercontent.com/4674940/123153902-11a28080-d41b-11eb-972f-df65631d8d04.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/126514

**Comment by misolori** [comment]
@roblourens I don't think this is the same as #126514 as that is specific to the focus state.

When looking at the colors for `settings.checkboxForeground` it points to `dropdown.foreground` which is `null` on light theme:

https://github.com/microsoft/vscode/blob/fb551dd655c8d3e01c70230b64241aa3a846e736/src/vs/platform/theme/common/colorRegistry.ts#L232

**Comment by misolori** [comment]
Nope, totally my fault [when I removed this](https://github.com/microsoft/vscode/commit/8c8c9bed36a2e804eb9efb271b086a4a7346fc92#diff-801e50c74128b6c6b04770806cc949a365a4f62aa7d122be2f485ee64b7f8ecc). Will push a change to fix.
