### ISSUE TITLE
Scrolling distance

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#127088]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Load up a project with a big enough source tree that it becomes scrollable
2. Scroll

The scroll distance is about 6 lines, which is more than I have configured. The default (and config for me) in Windows is 3 lines per tick, so it goes too far. Not every mouse has a smooth-scrolling wheel (in fact, probably almost no mouse) and so it's not possible to use the wheel to scroll less than what is already too much.

This is especially annoying in small panels, like Timeline, which I like to keep small.

This illustrates the issue perfectly:
![Animation2](https://user-images.githubusercontent.com/152227/123280739-51e02c80-d509-11eb-9dde-0149ef869b60.gif)

See how it's impossible to keep track of where I was, because it scrolls a whole "screen" at a time. Yes, I could make it bigger, but I'm not going to. And no *I will not enable smooth scrolling* for accessibility reasons (another thing VScode still hasn't solved and still requires a hack). Well, kudos to you if you can follow where the scroll position goes, but I really can't.

In bigger panels it's less of a problem, but the problem is still there: it mismatches my setting. And should I set the scroll distance to 3 lines *consciously* (rather than leaving it at its default), it's no longer a mismatch but rather it disrespects a systemwide preference.

This problem exists in Insiders as well. And I'm pretty sure this problem has existed in some form or another since the very first releases of VScode. Sometimes I'm frankly just really annoyed not to be able to scroll correctly, so I have to grab the scrollbar and drag that around. I can't believe no one has picked up this issue in the past, seeing how bleedingly obvious is that scrolling distance is way too much.

Guys and gals, blokes and birds, it is time to get this issue FIXED.
So the question is: what needs to happen for this issue to get fixed, and how do we make that happen?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/102261

**Comment by thany** [comment]
@joaomoreno Thanks for closing this issue with not even a single word, even though I took so much time to prepare it, and explain it as well as I could 🤨

On top of that, to quote myself:
>  So the question is: what needs to happen for this issue to get fixed, and how do we make that happen?

Remains unanswered 😑

**Comment by joaomoreno** [comment]
Given it's in the Backlog, there are currently no plans to allocated time to implement it. The good news is that there are two very cool labels attached to it: `help wanted` and `good first issue`. This means that we're willing to accept a PR for it and it's actually not a very hard issue to work on.

Please refer to our Wiki for more information on all of this:

- https://github.com/microsoft/vscode/wiki/How-to-Contribute#contributing-to-visual-studio-code
- https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
- https://github.com/microsoft/vscode/wiki/Development-Process
