### ISSUE TITLE
[Insiders] Updates seem to be losing Signed In Account Info Again

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#127060]
Issue Type: <b>Bug</b>

See below:
![image](https://user-images.githubusercontent.com/15258962/123223111-785c8400-d485-11eb-9790-ba84445a967d.png)

VS Code version: Code - Insiders 1.58.0-insider (3caebff71e514ece73b125468881d102e767ee4d, 2021-06-24T05:13:30.907Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (2.03GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
vscode-opennewinstance|chr|0.0.7
bracket-pair-colorizer-2|Coe|0.2.1
esbuild-problem-matchers|con|0.0.2
gitlens|eam|11.5.1
filter-lines|ear|1.0.0
remotehub|Git|0.10.1
vscode-pull-request-github|Git|0.27.1
todo-tree|Gru|0.0.213
vscode-test-explorer|hbe|2.20.4
vscode-drawio|hed|1.5.0
change-case|hjd|1.0.2
git-graph|mhu|1.30.0
remote-containers|ms-|0.184.0
remote-ssh-nightly|ms-|2021.5.29700
powershell-preview|ms-|2021.6.1
test-adapter-converter|ms-|0.0.11
vscode-paste-image|mus|1.0.4
indent-rainbow|ode|7.5.0
docthis|oou|0.8.2
quicktype|qui|12.0.46
vscode-yaml|red|0.20.0
vscode-sort-json|ric|1.20.0
vscode-inline-values-powershell|Tyl|0.0.5
errorlens|use|3.2.7
vscode-icons|vsc|11.5.0
codetour|vsl|0.0.56
gistfs|vsl|0.2.9
gitmoji-vscode|Vtr|1.0.7
better-align|wwm|1.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by JustinGrote** [comment]
@TylerLeonhardt I can't find the specific issue but this is one you fixed about a month ago as I recall.

**Comment by gjsjohnmurray** [comment]
/confirm

This happened to me after yesterday's Insiders update, and again just now when I updated to today's

**Comment by JustinGrote** [comment]
Yes it happened to me yesterday too, there were a lot of commits and nothing jumps out at me.

**Comment by TylerLeonhardt** [comment]
Shoot! Ok. @sbatten and I have a suspicion on this... but more data is always better.

Can you provide what's inside the `GitHub Authentication` Output Pane?

**Comment by JustinGrote** [comment]
@TylerLeonhardt what's different this time is that it only happens after an insiders update, it's totally fine after we go to sign in, so I don't have a repro in the output pane unfortunately. I'll try to capture after the nightly update tomorrow.

![image](https://user-images.githubusercontent.com/15258962/123291079-a31afc80-d4c6-11eb-9cd8-a0088f718662.png)

**Comment by IllusionMH** [comment]
@TylerLeonhardt After update yesterday _I think_ I haven't logged in with GitHub Authenticator.

Logs before update today:
```
[Error  - 08:16:17.529] Getting token failed: Error: Decryption failed
[Info  - 08:16:36.908] Logging in...
[Info  - 08:17:02.393] Exchanging code for token...
[Info  - 08:17:02.899] Token exchange success!
[Info  - 08:17:02.899] Getting user info...
[Info  - 08:17:03.209] Got account info!
[Info  - 08:17:03.226] Login success!
```

right after update + reload today:
```
[Info  - 08:24:13.75] Getting user info...
[Info  - 08:24:13.457] Got account info!
```

Both MS Auth and GH Auth remained signed in during updated to 
Version: 1.58.0-insider (user setup)
Commit: 49e1f9919880c1c96004f9b6ad91bcee7a94a1bd
Date: 2021-06-25T05:14:20.119Z

**Comment by gjsjohnmurray** [comment]
Perhaps a coincidence, but yesterday I received an email from GitHub about new authentication token formats. It linked to https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

Like for @IllusionMH, today's update didn't require a fresh login.

**Comment by JustinGrote** [comment]
My insiders was clean today too, maybe a transient thing.

**Comment by TylerLeonhardt** [comment]
Have you all experienced this recently? I think it's resolved. Although it could happen in the future... I need to chat more with @sbatten if we should try to spend time to prevent it from happening.

**Comment by gjsjohnmurray** [comment]
> Have you all experienced this recently?

Hasn't happened for me again so far.

**Comment by IllusionMH** [comment]
Haven't seen reported problem for about 5 days on 2 devices.

**Comment by JustinGrote** [comment]
I want to say I saw a sign-in prompt yesterday *just before* I updated insiders but it didn't lose my info, I just had to click it and it SSO'd me in. Otherwise been good.
