### ISSUE TITLE
Pasting text causes garbled result and error Code -32603

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#127054]
Issue Type: <b>Bug</b>

I am using the Ada Language Support extension so it is possible the problem is there, but I don't think so.

When pasting text, either code or comments, I frequently get an error like this but with a different time stamp:

[Error - 11:07:08 PM] Request textDocument/rangeFormatting failed.
  Message: Incorrect code can't be formatted
  Code: -32603

The paste proceeds but with a garbled result. For example, the above message appeared when pasting this comment, immediately after another single-line comment:

    -- Put_Line_S is a cobbled-together thing to redirect Put_Line a predefined string by switching
    -- a global boolean, for sending the wave data to Igor as a note. Some decorative lines are left
    -- as Put_Line because the Igor command line seems limited to maybe 1000 characters.

What I got instead was this:

    -- Put_Line a predefined string by switching a global boolean, for sending the wave data to Igor
    -- as a note. Some decorative lines are left as Put_Line because the Igor command line seems
    -- limited to maybe 1000 characters.

Note the missing text. Note also that the live pretty-printer changed the line breaks for me to account for the missing text.

Pasting this line of code

            f          : Long_Float := Set_Nan;

worked but was not garbled because I suspect it did not cause a line wrap. However, it did cause this error:

[Error - 11:38:14 PM] Request textDocument/rangeFormatting failed.
  Message: Incorrect code can't be formatted
  Code: -32603 

I would be happy to report this to the Ada Language Support list if that is more appropriate.

The attached log file was recorded after the first example above and after two more errors including the second one above.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.39.0
ada|Ada|22.0.8
Bookmarks|ale|13.1.0
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
project-manager|ale|12.2.0
rtf|ale|2.3.0
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.42.1
vscode-great-icons|emm|2.1.79
ada-snippets|Ent|0.3.0
vscode-faust|gle|1.1.0
vscode-lyx|gyt|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.19.2
svn-scm|joh|2.13.6
language-julia|jul|1.2.5
keen-neutral-icon-theme|kee|1.0.8
linter-gfortran|krv|2.2.2
octave|lea|0.1.1
eps-preview|mkv|0.1.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.2
jupyter|ms-|2021.6.999406279
cpptools|ms-|1.4.1
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.17
bib|phr|0.3.0
seti-icons|qin|0.1.3
ipf|qms|1.0.1
lualint|sat|0.0.5
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.21
octave|toa|0.0.3
pdf|tom|1.1.0
vscode-lua|tri|0.12.4
vscode-icons|vsc|11.5.0
vscode-icons-mac|way|7.25.3
debug|web|0.25.1
txt-syntax|xsh|0.1.5
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30325510

```

</details>

[Log file.log](https://github.com/microsoft/vscode/files/6706858/Log.file.log)

**Comment by alexdima** [comment]
It looks like the issue is caused by one of your installed extensions. To narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
