### ISSUE TITLE
Renaming from Title

### ISSUE THREAD

**Issue by cihanisma** [microsoft/vscode#127087]
- Sometimes you need to compare two responses or texts with `vscode`.
- For this, you create two new files and paste your contents.
- But it can be confusing as they are both named with the first lines of content.
- Therefore, it will be useful to be able to rename the title on the tab by double-clicking it or from the right-click menu.
<img width="1314" alt="titles" src="https://user-images.githubusercontent.com/59100702/123280658-412fb680-d509-11eb-8a61-3c9375c5e4dd.png">

**Comment by cihanisma** [comment]
@bpasero It is needed an interface or a web page that shows the requests waiting for voting in order of votes so that these requests do not go unnoticed by the user community.

**Comment by cihanisma** [comment]
@bpasero It is needed a simple interface or a web page that shows the requests waiting for voting in order of votes so that these requests do not go unnoticed by the user community. Github's sort by label screen is not understandable to the casual user. Even most of the users are unaware of such a voting system.

**Comment by cihanisma** [comment]
@bpasero It is needed a simple interface or a web page that shows the requests waiting for voting in order of votes so that these requests do not go unnoticed by the user community. Github's sort by label screen is not understandable to the casual user. Even most of the vscode users are unaware of such a voting system.

**Comment by cihanisma** [comment]
> @bpasero It is needed a simple interface or a web page that shows the requests waiting for voting in order of votes so that these requests do not go unnoticed by the user community. Github's sort by label screen is not understandable to the casual user. Even most of the vscode users are unaware of such a voting system.

As I said above, since a simplified interface was not designed, I also found my own solution to mention under other topics. I hope you will attempt a simplified interface work to get feature requests noticed. In fact, this screen can be provided within the vscode itself.

**Comment by pd93** [comment]
@cihanisma, you can view [issues sorted by +1 reaction on the issues page in github](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). I'm 100% sure that the VSCode team know this and regularly check what the most upvoted issues are. This is one of the ways most projects of this size prioritise work.

You do not need to post a link to this issue in other popular issues. In fact, please do not do this. If everyone did, then issues would be filled with spam and unrelated comments and its much less likely that a healthy conversation about the feature can be had. Ultimately, there are nearly 6000 open issues at the moment, all of which are submitted by people like you that think their idea/problem should be fixed. You just need to be patient.

**Comment by bpasero** [comment]
An extension such as https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils provides utilities to do file operations. Extensions are also free to contribute to the tabs context menu.
