### ISSUE TITLE
getState()/setState() persists across reboots in WebviewView, does not have retainContextWhenHidden flag

### ISSUE THREAD

**Issue by Xenomega** [microsoft/vscode#127006]
Issue Type: <b>Bug</b>

Currently I am trying to use `getState(...)` and `setState(...)` inside of a Webview View. I wanted to use these functions to store/restore state, since the UI refreshed every time I change tabs so it is hidden/shown. 

[Documentation states](https://code.visualstudio.com/api/extension-guides/webview#getstate-and-setstate) `This state is persisted even after the webview content itself is destroyed when a webview panel becomes hidden. The state is destroyed when the webview panel is destroyed.`. 

However, I am fully ending the VSCode process on my machine and restarting it, and `getState(...)` is undeniably returning my state from the last run. This forces me to instead create my own state storing/restoring methodology by sending messages to the extension and back (to temporarily store the data in the extension, which is not ideal).

Also, the flag `retainContextWhenHidden` exists in the Webview API, but not in the WebviewView API, so I cannot leverage this.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by mjbvz** [comment]
Destroyed generally means closed by the user. If you feel the documentation is unclear, please submit a pr to clarify this

Also `retainContextWhenHidden` can be passed to `registerWebviewViewProvider`

**Comment by Xenomega** [comment]
Ah sorry, I missed the `retainContextWhenHidden` somehow.. hmm.

That said, the rest is understandable, but your documentation definitely does not indicate that what you mentioned is the intended behavior. The idea that "destroyed" only means manually closed while the process remains alive and doesn't include otherwise being freed/killed/restarted/torn down is counterintuitive and ambiguous. I'd recommend updating it, although I don't have time to make PRs for documentation right now ;P

Thanks for the clarification!
