### ISSUE TITLE
[SSH] Provide Reconnect SSH button along with the Reload Window button

### ISSUE THREAD

**Issue by abhijithda** [microsoft/vscode#127011]
Provide an option to retry reconnecting to SSH along with "Reload Windows" option.

![image](https://user-images.githubusercontent.com/10643271/123143945-fa11ca80-d40f-11eb-8d4b-fbd676a90133.png)

Situtation:
At the end of the day, when we close the laptop, the VPN session gets disconnected, and the next morning when we connect to VPN again, the vscode display's a dialog with the reload button option. I would like to see "Reconnect SSH" or "Reconnect Now" (like the one in below image) option so that I can retain all the split terminals and their content (https://github.com/microsoft/vscode/issues/95183).

Since the remote linux machine is only used by me, and the reconnect works well when the VPN is disconnected for more than 10 mins, I think, that should be possible!

![image](https://user-images.githubusercontent.com/10643271/123178256-aae18f00-d43b-11eb-88e9-44d9a30113ec.png)

**Comment by roblourens** [comment]
Once you have become disconnected, you need to reload the window and start a new session. The remote session will have timed out at some point so you can't necessarily reconnect to it in the same window.

You probably are interested in this feature request https://github.com/microsoft/vscode-remote-release/issues/3096

**Comment by abhijithda** [comment]
@roblourens ,
Even though I disconnect it, and connect it again like in about 15 mins or so to the VPN, it retries and automatically connects... And, I'm able to resume the work without actually having to reload the windows. So, is it not possible to do the same the next day when the laptop is resumed? Retry may not make sense after so long (like 10 hrs), so was asking for Reconnect option similar to Reload option (that way I can retain the split terminals and the text on them along with coding jumps/navigation).
