### ISSUE TITLE
Exclusive editor types allow reopening editor with

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127084]
Repro:

1. Open a terminal editor
2. Right click tab, reopen editor with shouldn't be there and the backing command should be a no-op

![image](https://user-images.githubusercontent.com/2193314/123274594-82e44100-d4b8-11eb-9907-f567f632621c.png)
![image](https://user-images.githubusercontent.com/2193314/123274605-85df3180-d4b8-11eb-8a3f-597cdf6a64ec.png)

**Comment by lramos15** [comment]
Had to revert this due to https://github.com/microsoft/vscode/issues/127583. Will come up with a better solution.

**Comment by rzhao271** [comment]
"and the backing command should be a no-op"
I'm not sure what this refers to, but I can confirm that the context menu entry doesn't show up for me now, and even if I try to run `workbench.action.reopenWithEditor` in the command palette, nothing happens.
