### ISSUE TITLE
Code Reference Indicator

### ISSUE THREAD

**Issue by Ad4mJ** [microsoft/vscode#127092]
Display the references count for methods, properties & interfaces. This functionality already exists in Visual Studio,. See here: https://dailydotnettips.com/find-the-references-easily-code-reference-indicator-in-visual-studio-2013-preview/

**Comment by gjsjohnmurray** [comment]
For JavaScript and TypeScript these settings are available:

![image](https://user-images.githubusercontent.com/6726799/123301411-8822a980-d513-11eb-8b25-9992e8f1559f.png)

A suitable extension would be needed for other languages.
