### ISSUE TITLE
Notificatio popups block sidebar when sidebar is moved to right

### ISSUE THREAD

**Issue by leon-paul-hart** [microsoft/vscode#127065]
Issue Type: <b>Feature Request</b>

Currently when the Sidebar is moved to the right hand side of the screen, all the notification that pop up block the content of the side panel, could the notifications be flipped or moved elsewhere on the screen when right aligned sidebar is selected so it does not block the sidepanel content?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/103829
