### ISSUE TITLE
ctrl + p keybinding which used to pull up file and methods with @ annotation does not work anymore? 

### ISSUE THREAD

**Issue by sunnyBhattacharjee** [microsoft/vscode#127061]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Also see https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+p`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
