### ISSUE TITLE
Tab key focus movement is always applied

### ISSUE THREAD

**Issue by m-misa** [microsoft/vscode#127040]
Tab key focus movement is always applied.
Does not change even if the function is turned off.
I'm having trouble moving the cursor when using snippets.
Is there a way to force it to be disabled?

**Comment by isidorn** [comment]
F1 > Tab Key Moves Focus

**Comment by m-misa** [comment]
Even if you make that setting, it will not change.
Is there a solution?
OS: win10 Pro

**Comment by m-misa** [comment]
I tried the following
・Erase the plug-in
・re-install
But the problem is not solved
It's very troubled.

**Comment by m-misa** [comment]
https://user-images.githubusercontent.com/86388242/123338400-bdff7680-d583-11eb-832e-f62327064b45.mp4

**Comment by m-misa** [comment]
https://user-images.githubusercontent.com/86388242/123339516-b4770e00-d585-11eb-83cc-7a09362f7ca9.mp4

**Comment by isidorn** [comment]
Please do not open duplicate issues on purpose.
As for the tab key please read this https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by m-misa** [comment]
I'm sorry I don't know how to use it because it's my first time writing.

I have already tried what I was told and have not solved it
I will try to find a solution a little more

Thank you for your support
