### ISSUE TITLE
`activeEditor.document.save()` causes the editor to be closed

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/vscode#127094]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.57.1
- OS Version: windows 10 - 21H1

Steps to Reproduce:
I'm working on an extension that needs to save an `untitled` file before doing some operation on it. but after calling `save()` method the editor closes.

```javascript
let isSaved;
if (isUntitled) {
	isSaved = await vscode.window.activeTextEditor!.document.save();
}
// in this line of code the editor is closed. why?
// do the rest
```

**Comment by bpasero** [comment]
This is as designed, because the untitled document changes to a different document.

//cc @jrieken

**Comment by MohammadMD1383** [comment]
Well..., but when user saves it e.g. by pressing <kbd>CTRL</kbd>+<kbd>S</kbd> it doesn't get closed.
