### ISSUE TITLE
web content keeps reloading when switching tabs

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#127036]
Issue Type: <b>Bug</b>

For example, the "Release Notes: 1.57.1" tab. When I switch tabs and come back to the release notes, it is blank and reloads. This happens every time. If I am reading examples in the release notes, and switching back and forth with a file I'm trying to use the example in, it keeps reloading and losing my position. Extremely frustrating.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.11.0-7614-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.09GB (3.30GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id eb1c688b-c4e3-4232-85a1-c01025d91995|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.3
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
restore-terminals|Eth|1.1.6
vscode-firefox-debug|fir|2.9.4
gauge|get|0.0.20
vscode-docker|ms-|1.14.0
remote-containers|ms-|0.183.0
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.34.1
prisma|Pri|2.25.0
indenticator|Sir|0.7.0
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by mjbvz** [comment]
The reload is by design. Otherwise you're keeping around what amounts to a browser tab in the background of the editor

We try to restore the scroll position but depending on how fast the images load, this may not always be entirely accurate

Try opening the release notes in a browser instead if you want them to be persisted

**Comment by Hadakajime** [comment]
What's the issue with keeping it alive in the background?
I have considerable more than 640kb.

If having a browser tab alive in the background was an issue for me, then I would close it. Otherwise, I am obviously keeping it around for a reason.
