### ISSUE TITLE
Trouble debugging a VS Code extension in WSL

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#127082]
Does this issue occur when all extensions are disabled?: not applicable

- VS Code Version: 1.57.1
- OS Version: Win 20H1

Steps to Reproduce:

1. Open a folder in VS Code using the WSL remote mode.
2. Follow the steps from https://code.visualstudio.com/api/get-started/your-first-extension to create a VS Code extension up to debugging the extension using <kbd>F5</kbd>
3. When pressing <kbd>F5</kbd> while the `extension.ts` is opened, I always get the following error **(first issue):** 

   > Errors detected while running the preLaunchTask "npm: watch"
   > [Debug anyway] [Show error] [Cancel]

   At the same time, the terminal for the npm watch task shows:

   > Starting compilation in watch mode...
   > Found 0 errors. Watching for file changes.

   - If I press "Show error", I am redirected to the empty problem pane
   - If I press "Debug anyway", the remote extension host is opened in a second WSL window (very cool that this works!) and I'm able to run my "Hello world" command there. It's even possible to set breakpoints in the `extension.ts`.
   - However, after closing the remote extension host window, the file `remoteExtensionHostProcess.js` is opened in my main editor window and shows a never-ending loading bar **(second issue).** The debugger does not stop and any attempts to use the Stop, Pause, or Restart buttons are fruitless. The only way to escape from the debugger or to debug the extension again that worked for me is to reload the window.

**Comment by LinqLover** [comment]
Workaround for the second bug (unstoppable debugger) is to stop the debugger _before_ closing the remote extension host window.

**Comment by LinqLover** [comment]
Same issue when I reload the remote extension host window (which is necessary to open a different folder).

**Comment by LinqLover** [comment]
Ha! Fixed it (partially) by disabling "Halt on uncaught breakpoints" in the debugger. This is not ideal, though ... :-)

**Comment by isidorn** [comment]
There is a known limitation that task errors are not tied to the current preLaunchTask. This has been discussed in the past and you can find it in older issues.
For now let's keep this issue open.

**Comment by LinqLover** [comment]
I don't have enough background on the `preLaunchTask` thing, but does this also explain the other point I mentioned (debugger loads infinitely in `remoteExtensionHostProcess.js` when "Halt on uncaught breakpoints" is enabled)? Or should I open a second issue for that? :)
