### ISSUE TITLE
Change checkbox "Register VS Code to be the editor for associated file types" to be checked by default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127075]
After discussing with John Falcone and @joaomoreno we have decided to change the checkbox Register "VS Code to be the editor for associated file types" to be turned on by default.

Since we are wrapping up the June milestone, and July I am out on vacation we will do this start of the August milestone.

Related discussion https://github.com/microsoft/vscode/issues/8687#issuecomment-234303525

Main motivation for this: improve user experience on windows to more easily open associated file types in VS Code.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1926584/123257730-d6738080-d4f2-11eb-8053-59ec1d2c4a0b.png)

**Comment by isidorn** [comment]
To make sure nothing gets broken:
- [ ] put the change in a branch and create a build from it
- [ ] in a fresh VM, install Code before your change with all defaults (no association)
- [ ] in that same fresh VM, install the new Code with the change the same way the update does it. from a command line, run VSCodeSetup.exe /silent confirm that the associations were not set and that the user's decision at install time was preserved

**Comment by xandfis** [comment]
Adding some details on why this is important - in the new File Explorer context menu, Open With is moved to the top of the menu and supplants or replaces the need to use a separate context menu verb in most cases. It also makes it easier to establish VS Code as the default when there are multiple editors. 

When VS Code is only registered for *, and not for each of the individual file types it supports, it takes more clicks as you need to open the actual Open With dialog, as opposed to a single click in the context menu.

![image](https://user-images.githubusercontent.com/69924000/123695459-6e34df80-d80f-11eb-9c91-503119f34601.png)

**Comment by isidorn** [comment]
@xandfis thanks for elaborating. We will keep this in mind in August when we flip the default.

**Comment by JacksonKearl** [comment]
Could this be scoped out to also include adding VS Code as a folder opener? This would be helpful for not getting into the "broken" case of having only single files open as opposed to project folders.

Either here:
![image](https://user-images.githubusercontent.com/8586769/127926057-ae986e3c-f839-475a-a92e-540b23491b1e.png)

Or here:
![image](https://user-images.githubusercontent.com/8586769/127925973-7dda8582-683a-4007-be5a-f10d45fc2a26.png)

**Comment by isidorn** [comment]
@JacksonKearl can you please create a new issue for that? 
This milestone I want to do a minimal change (to minimise risk of breaking users) to only add more associated file types and to change the default.
