### ISSUE TITLE
Allow notebook kernel to be set per-cell

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#127047]
Previously mentioned here: https://github.com/microsoft/vscode/issues/119949#issuecomment-811385963.

Notebooks can contain code cells in any language. Kernels can be notebook type agnostic. Notebook serializers are not necessarily tied to a specific kernel. Specifically, [Markdown Notebook](https://github.com/microsoft/vscode-markdown-notebook) provides a serializer but no kernel, and [Go Notebook Kernel](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.go-notebook-kernel) provides a kernel but no serializer (and could work with any notebook type).

I want to be able to set the notebook kernel per cell. This would allow one notebook to contain code in multiple languages, executed by different kernels.

**Comment by dynamicwebpaige** [comment]
Thank you for the feature request, @firelizzard18!

Have you had a chance to play with [.NET Interactive Notebooks](https://devblogs.microsoft.com/dotnet/net-interactive-preview-3-vs-code-insiders-and-polyglot-notebooks/), by any chance? Users can select different language sub-kernels for each cell, or by using magics. Current languages supported are SQL, C#, F#, JavaScript, and TypeScript -- though we are in the process of adding support for both Python and R.

cc: @claudiaregio @ladynagagga @tanhakabir

**Comment by claudiaregio** [comment]
Hi @firelizzard18, what languages would you like to be able to use in the same notebook?

**Comment by firelizzard18** [comment]
@dynamicwebpaige @claudiaregio I am not interested in specific languages. I want to be able to use multiple kernels in the same notebook without those kernels being hard coded to work together. I have written a few kernels; given that they serve different purposes, they should be (and are) separate extensions. I want to be able to write a notebook with cells in different languages, each handled by the appropriate kernel.
