### ISSUE TITLE
Can't see debug actions or detail on focused callstack row

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#127034]
If I focus the callstack row, I can't read "Paused on breakpoint" or see the debug command buttons with the new list focus color
![image](https://user-images.githubusercontent.com/323878/123178646-7b7f5200-d43c-11eb-9b78-401f09ccad57.png)

**Comment by isidorn** [comment]
Thanks for fixing @misolori 👏

**Comment by misolori** [comment]
For verification: start a debug session and verify that selecting a call stack row shows the icons correctly in dark/light. Also ensure the icons in the toolbar (docked and floating) appear correctly.
