### ISSUE TITLE
Workspace Trust dialog should show full name of folder being queried

### ISSUE THREAD

**Issue by jimbobmcgee** [microsoft/vscode#127013]
The very first thing I saw in VSCode after updating to 1.57 was the Workspace Trust dialog.  I had to intuit that it was asking about the folder containing files I had open when I allowed VSCode to restart.

It would be very useful (to me) if the Workspace Trust dialog could tell me *what* I am being asked to trust.  The only clue I have initially is the checkbox which asks if I want to trust the parent, which at least supplies the local name -- even that wouldn't be enough in many cases.

Granted, if we are being asked to trust something *virtual* (if that's even a *thing*), then it might be difficult to identify a suitable descriptor, but a folder or URL should be plainly displayed where it is known, and a best-effort identifier should be displayed everywhere else.

If I've missed something, then it's non-obvious,and that should be fixed too...

Obligatory screen mock is obligatory:
![image](https://user-images.githubusercontent.com/12205864/123145620-ef2d5900-d454-11eb-8cd4-0aecf4ac3f2c.png)

**Comment by sbatten** [comment]
Duplicate https://github.com/microsoft/vscode/issues/125984

**Comment by jimbobmcgee** [comment]
@sbatten - apoligies -- I did *try* to find similar before posting, but there's obviously a lot of foot-traffic in this repo!
