### ISSUE TITLE
Remote SSH: Adding additional folder to workspace reloads window

### ISSUE THREAD

**Issue by aviadb** [microsoft/vscode#127106]
Issue Type: <b>Bug</b>

1. Open remote connection to host in current/new window
2. Add first folder to workspace
3. Add additional folder to workspace
4. Window is reloaded, and new folder is not added to workspace

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-1036-azure
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|39.96GB (29.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 13.92.120.35|
|OS|Linux x64 5.8.0-1036-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (12 x 2596)|
|Memory (System)|110.04GB (104.77GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4199)|
|Memory (System)|31.33GB (31.00GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurevirtualmachines|ms-|0.4.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-azureresourcegroups|ms-|0.4.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
azure-account|ms-|0.9.8

</details>

**Comment by aviadb** [comment]
The window reloading also drops the Azure login session.

**Comment by roblourens** [comment]
What are you doing to add the folder, are you running the "Add Folder to Workspace" command?

**Comment by vikramjit-sidhu** [comment]
I am facing the same issue on a Mac OS 11.4 after the latest VS code update.
Remote OS version: Ubuntu 10.04.
I try to add the folder using the 'Add Folder to Workspace' command.
