### ISSUE TITLE
Code Fomatting  

### ISSUE THREAD

**Issue by sudheer-creator** [microsoft/vscode#127136]
Issue Type: <b>Feature Request</b>

My code formatting options in vs code is not working. What should I do ? I have tried all the options  using mouse and shortcut keys but it does'nt work at any time.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by mjbvz** [comment]
What language is this for?
