### ISSUE TITLE
YAML recognized at Plain Text

### ISSUE THREAD

**Issue by SturmB** [microsoft/vscode#127159]
Issue Type: <b>Bug</b>

Opening a `.yml` file in VS Code Insiders (latest as of this writing), VS Code only sees it as Plain Text. I can manually change it to YAML per file, of course, but upon the next start of VS Code Insiders, that assignment is gone.

VS Code version: Code - Insiders 1.58.0-insider (49e1f9919880c1c96004f9b6ad91bcee7a94a1bd, 2021-06-25T05:14:20.119Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (10.99GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu-20.04/home/sturm/dotfiles.code-workspace --remote=wsl+Ubuntu-20.04 --crash-reporter-id 1dd0de06-bef1-4fe2-b677-dcb8d4096755|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|25.03GB (17.33GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
auto-rename-tag|for|0.1.6
remote-wsl|ms-|0.58.2
ansible-vault|dho|0.1.3
auto-rename-tag|for|0.1.6
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.7.970869158
vscode-yaml|red|0.20.0
gitmoji-vscode|Vtr|1.0.7
local-history|xyz|1.8.1
vscode-ansible|zbr|0.4.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you anything set in `files.associations` in User, Workspace, or Remote settings?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by SturmB** [comment]
I already tried disabling extensions with `--disable-extensions` but I cannot because I need Remote-WSL. For the record, this problem does not exist when not running in Remote WSL mode.

There is nothing set in `files.associations` at all. This is a mostly out-of-the-box installation of Insiders and I haven't changed any settings in it yet.

I'm pretty sure this is related to the [many](https://github.com/microsoft/vscode-remote-release/issues/5129) [other](https://github.com/microsoft/vscode-remote-release/issues/5010) [reports](https://github.com/microsoft/vscode/issues/126192) of problems with WSL.

**Comment by aeschli** [comment]
To see if one of the remote extension causes this:
- close VS Code
- open a WSL terminal, `cd ~/.vscode-server-insiders`, `mv extensions extensions1`
- restart VS Code , opemn a remote WSL window, check the extensions view that there are no remote extensions present
- move `extensions1` back to `extension` to get your old set of extensions back

To see if one of the remote machine setting causes this:
- open a WSL terminal, `cd ~/.vscode-server-insiders`, `mv data data1`

To see if your workspace settings causes this, open a new folder.

**Comment by SturmB** [comment]
I just renamed the `extensions` dir and the `data` dir, then started up insiders. Indeed, there are no extensions loaded, but it still is not recognizing a `.yml` file as anything but Plain Text.

![image](https://user-images.githubusercontent.com/6216224/123640067-cc04ff80-d7ee-11eb-948d-7c829d5e7b41.png)

**Comment by aeschli** [comment]
In the extension view, when you enter `@builtin yaml`, can you verify that the YAML Language Basics extension is enabled?

**Comment by SturmB** [comment]
I just updated stable to v1.58.0 and this issue still persists in Remote WSL. Has there been any headway made here?

I'll be leaving this company after next week and won't have access to this PC anymore, so I may have to abandon this issue then unless I can reproduce it on my home PC or my new company's PC.

**Comment by aeschli** [comment]
I have no idea what could be the cause. I can't reproduce the issue and the issue hasn't been reported by anyone else.
I think we have to abandon the issue. 
Thanks a lot for the efforts. Sorry for that.
