### ISSUE TITLE
Simple Browser not working

### ISSUE THREAD

**Issue by paperluigis** [microsoft/vscode#127141]
Issue Type: <b>Bug</b>

Simple Browser is using <iframe>, engine refuses to display it because of X-Frame-Options.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
<details>
<summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/72666727/123411718-30934500-d5ca-11eb-88a4-20d86057e38b.png">
<img src="https://user-images.githubusercontent.com/72666727/123411929-705a2c80-d5ca-11eb-8c8f-c7a4178176b1.png">

</details>
OS version: Linux x64 5.11.0-22-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-9120 RADEON R3, 4 COMPUTE CORES 2C+2G (2 x 2495)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.72GB (0.29GB free)|
|Process Argv|--crash-reporter-id 2c63594e-543c-4192-b4ae-bd6cf5e9ef3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
vs-media-player|mkl|3.1.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
hexeditor|ms-|1.7.1
live-server-preview|neg|0.1.4
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30329803
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by mjbvz** [comment]
This is a security feature of iframes. We can't work around it

**Comment by paperluigis** [comment]
> This is a security feature of iframes. We can't work around it.
Even sites that **allow** embedding are not working (e.g. remote devtools)

**Comment by ohAitch** [comment]
Are there any header-rewriting extensions you would recommend? Short of that, would it be possible to rename the extension to something like "Local Webpage Preview" - if it's designed not to work on common websites(https://google.com, https://github.com, https://code.visualstudio.com), it is not a "web browser".
Contrast https://github.com/skandasoft/browser-plus, or the admittedly very laggy https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview
