### ISSUE TITLE
Test: Supporting iframe search

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#127173]
Refs: #96307

- [x] windows @bamurtaugh
- [x] macOS @jrieken
- [x] linux @lramos15

Complexity: 3

Authors: @rzhao271, @deepak1556

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127173%0A%0A)

---

1. Add `"webview.experimental.useIframes": true` to the settings file.
2. Create a markdown file, or open an existing markdown file.
3. Run the "Markdown: Open Preview to the Side" command.
4. Press Ctrl+F to reveal the find widget, and try searching in the iframe.

Some things to try for step 4:
- How well does searching work with an IME?
- How well does searching work with a screenreader/a11y tool?
- Are there any issues if one tries to change the markdown file content, or close and re-open the markdown preview while a find session is in place?
- Does reloading during a find session cause an issue?

**Comment by bamurtaugh** [comment]
Hey @jrieken - I finished up my testing and checked off my name / assignment yesterday. Is it safe to check off yours and close out this issue too? Or was there a reason you assigned it back to me? Thanks!

**Comment by jrieken** [comment]
Yeah, forgot my checkbox here...
