### ISSUE TITLE
Visual Studio Code Issue

### ISSUE THREAD

**Issue by SumedhaSahdev** [microsoft/vscode#127187]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Downloaded Visual Studio Code from https://code.visualstudio.com/ for Windows 10. 
2. After installing, try to launch it. It is showing a black screen.
Please find the screenshot attached.
![image](https://user-images.githubusercontent.com/69587974/123479225-3fa3e280-d61e-11eb-8aee-8ae053a6f2e7.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
If insiders also result in the same issue, please provide the output of `--verbose`

**Comment by SumedhaSahdev** [comment]
![insider](https://user-images.githubusercontent.com/69587974/123627015-1a39f300-d82f-11eb-8fe3-bc588176577e.PNG)

**Comment by SumedhaSahdev** [comment]
C:\WINDOWS\system32>code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64

C:\WINDOWS\system32>code --help
Visual Studio Code 1.57.1

Usage: code.exe [options][paths...]

To read output from another program, append '-' (e.g. 'echo Hello World | code.exe -')

Options
  -d --diff <file> <file>           Compare two files with each other.
  -a --add <folder>                 Add folder(s) to the last active window.
  -g --goto <file:line[:character]> Open a file at the path on the specified
                                    line and character position.
  -n --new-window                   Force to open a new window.
  -r --reuse-window                 Force to open a file or folder in an
                                    already opened window.
  -w --wait                         Wait for the files to be closed before
                                    returning.
  --locale <locale>                 The locale to use (e.g. en-US or zh-TW).
  --user-data-dir <dir>             Specifies the directory that user data is
                                    kept in. Can be used to open multiple
                                    distinct instances of Code.
  -h --help                         Print usage.

Extensions Management
  --extensions-dir <dir>
      Set the root path for extensions.
  --list-extensions
      List the installed extensions.
  --show-versions
      Show versions of installed extensions, when using --list-extensions.
  --category <category>
      Filters installed extensions by provided category, when using --list-extensions.
  --install-extension <extension-id[@version] | path-to-vsix>
      Installs or updates the extension. The identifier of an extension is always `${publisher}.${name}`. Use `--force` argument to update to latest version. To install a specific version provide `@${version}`. For example: 'vscode.csharp@1.2.3'.
  --uninstall-extension <extension-id>
      Uninstalls an extension.
  --enable-proposed-api <extension-id>
      Enables proposed API features for extensions. Can receive one or more extension IDs to enable individually.

Troubleshooting
  -v --version                       Print version.
  --verbose                          Print verbose output (implies --wait).
  --log <level>                      Log level to use. Default is 'info'.
                                     Allowed values are 'critical', 'error',
                                     'warn', 'info', 'debug', 'trace', 'off'.
  -s --status                        Print process usage and diagnostics
                                     information.
  --prof-startup                     Run CPU profiler during startup.
  --disable-extensions               Disable all installed extensions.
  --disable-extension <extension-id> Disable an extension.
  --sync <on> <off>                  Turn sync on or off.
  --inspect-extensions <port>        Allow debugging and profiling of
                                     extensions. Check the developer tools for
                                     the connection URI.
  --inspect-brk-extensions <port>    Allow debugging and profiling of
                                     extensions with the extension host being
                                     paused after start. Check the developer
                                     tools for the connection URI.
  --disable-gpu                      Disable GPU hardware acceleration.
  --max-memory <memory>              Max memory size for a window (in Mbytes).
  --telemetry                        Shows all telemetry events which VS code
                                     collects.


C:\WINDOWS\system32>

C:\WINDOWS\system32> --verbose
'--verbose' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>

C:\WINDOWS\system32>

**Comment by SumedhaSahdev** [comment]
Attached a screenshot of the launch of VSC insider version and the output of --verbose command.

**Comment by deepak1556** [comment]
Sorry for not being clear, the flag should be used alongside the application cli.

`code --verbose` or `code-insiders --verbose`

**Comment by SumedhaSahdev** [comment]
C:\Users\cc\Downloads>code --verbose

[main 2021-06-28T12:04:10.874Z] Starting VS Code
[main 2021-06-28T12:04:10.875Z] from: c:\Users\cc\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2021-06-28T12:04:10.875Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '75d2efe9-1b35-41d1-ad56-caed3a6ad355',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\cc\\AppData\\Roaming\\Code\\logs\\20210628T173410'
}
[main 2021-06-28T12:04:10.877Z] Deleting Chrome cached data path: c:\Users\cc\AppData\Roaming\Code\Code Cache
[main 2021-06-28T12:04:10.880Z] Resolving machine identifier...
[main 2021-06-28T12:04:10.880Z] Resolved machine identifier: 9680b9bb1084ff942dbf514736430835c8a78800dda9c1750b091a95f1dc62a9
[main 2021-06-28T12:04:10.885Z] Main->SharedProcess#connect
[main 2021-06-28T12:04:11.444Z] StorageMainService: creating global storage
[main 2021-06-28T12:04:11.445Z] lifecycle (main): phase changed (value: 2)
[main 2021-06-28T12:04:11.446Z] windowsManager#open
[main 2021-06-28T12:04:11.446Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\cc\\AppData\\Roaming\\Code\\Backups\\1624878052245',
    remoteAuthority: undefined
  }
]
[main 2021-06-28T12:04:11.447Z] IPC Object URL: Registered new channel vscode:5db648ca-e6a7-45c4-8868-651f37612eb3.
[main 2021-06-28T12:04:11.447Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 201, y: 30, width: 1024, height: 728 }
[main 2021-06-28T12:04:11.448Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1366, height: 728 }
[main 2021-06-28T12:04:11.448Z] window#ctor: using window state { mode: 1, x: 201, y: 30, width: 1024, height: 728 }
[main 2021-06-28T12:04:11.448Z] window#ctor: vscode-file:// protocol is explicitly disabled
[main 2021-06-28T12:04:11.530Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-06-28T12:04:11.530Z] lifecycle (main): phase changed (value: 3)
[main 2021-06-28T12:04:11.537Z] update#setState idle
[main 2021-06-28T12:04:11.537Z] resolveShellEnv(): skipped (Windows)
[main 2021-06-28T12:04:11.712Z] resolveShellEnv(): skipped (Windows)
[14656:0628/173411.732:INFO:CONSOLE(61)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (61)
[14656:0628/173411.749:INFO:CONSOLE(1)] "[uncaught exception]: Error: ENOENT: no such file or directory, open 'c:\Users\cc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js'", source: file:///C:/Users/cc/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/bootstrap-window.js (1)
[14656:0628/173411.749:INFO:CONSOLE(1)] "Error: ENOENT: no such file or directory, open 'c:\Users\cc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js'", source: file:///C:/Users/cc/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/bootstrap-window.js (1)
[main 2021-06-28T12:04:11.819Z] [File Watcher (node.js)] [CHANGED] c:\Users\cc\AppData\Roaming\Code\User\globalStorage
[main 2021-06-28T12:04:11.820Z] [File Watcher (node.js)] [CHANGED] c:\Users\cc\AppData\Roaming\Code\User\globalStorage
[main 2021-06-28T12:04:12.020Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\cc\AppData\Roaming\Code\User\globalStorage

**Comment by deepak1556** [comment]
It looks like the resource files shipped with the application are not found. Can you check if an Anti-virus software on your machine is quarantining the application files `c:\Users\cc\AppData\Local\Programs\Microsoft VS Code`.

**Comment by SumedhaSahdev** [comment]
I don't think so.
I've filtered the items with Quarantined Files in Protection History. Can't
find any such items here.
Is there any alternative to check for the same ?

[image: image.png]

Thanks & regards,
Sumedha Verma

**Comment by SumedhaSahdev** [comment]
Is there an alternative to this  ?
