### ISSUE TITLE
Improve letterpress shortcuts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12716]
First:

- What does `Open File in Folder` mean? Why not `Quick Open`?
- Why is `Move Lines Up/Down` in there? As a matter of fact, why are `Add Cursors` and `Open Terminal` too? We should just give the user the essential to get started, not random commands that make us look cool.

Finally, a little bit of styling care goes a long way:

![image](https://cloud.githubusercontent.com/assets/22350/18863811/98ecf598-8493-11e6-81f4-f45263969f07.png)

**Comment by chrmarti** [comment]
Is this Windows? (The keybindings display better on OSX, will need to check why.)

`Quick Open` seems at least as opaque to new users if not more than `Open File in Folder`. We should still try to think of a better name. The command palette uses `Go to File...`.

We picked the commands by looking at which are used the most, yet not trivial like clipboard actions.

**Comment by joaomoreno** [comment]
Also on OS X it looks odd as the format is something like: _this **or** that **or** these_. It would look much better if each shortcut is isolated visually instead of grammatically.

`Go to File` is a good alternative.

**Comment by bgashler1** [comment]
@joaomoreno you mentioned style; what would you like to see different?

**Comment by bgashler1** [comment]
For new users, it would be nice to have the most essential commands up front.  Chances are they are not going to remember about the moving lines up/down right away and stuff.  It would be cool if down the road we could progressively introduce more advanced commands that may keep this area fresh and useful.

**Comment by joaomoreno** [comment]
@bgashler1 Notice the screenshot in the first post.

Something like <kbd>Ctrl Shift P</kbd> <kbd>F1</kbd>

is much better than something like Ctrl+Shift+P, F1.

**Comment by bgashler1** [comment]
@joaomoreno ah, I see.  I personally like the kbd tag as well.  We had something kind of like that an earlier draft.  Not sure what you think...

<img width="423" alt="screen shot 2016-09-27 at 10 08 47 am" src="https://cloud.githubusercontent.com/assets/11839736/18883995/67c258da-849a-11e6-9f9b-5e0f0975a22f.png">

But I think some of the team preferred just the text.

Maybe your darker approach would be more appealing to them, though.

On a side note, shouldn't it be <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> or <kbd>F1</kbd>?

**Comment by joaomoreno** [comment]
I really don't think it should. I would save separation for chording.

**Comment by chrmarti** [comment]
- On Windows: That is just how the keybindings are spelled out, also in the command palette.
- _this **or** that **or** these_: Tracked as #12797 and #12862 
- The UX meeting hasn't brought forward a clear winner for the shortcut styling. I would keep it as is, @bgashler1 ?
- I will update the text from "Command Palette" to "Go to File" as part of this issue.

**Comment by joaomoreno** [comment]
Please don't keep it as is. At least use a monospace font...

**Comment by bgashler1** [comment]
IMO, I don't think the monospaced font looks quite right.
<img width="358" alt="screen shot 2016-09-28 at 4 11 07 pm" src="https://cloud.githubusercontent.com/assets/11839736/18935648/448c4fcc-8596-11e6-80f6-c2e90c80ba75.png">

Also we are using Segoe UI font in the command palette
<img width="342" alt="screen shot 2016-09-28 at 4 12 37 pm" src="https://cloud.githubusercontent.com/assets/11839736/18935668/6aa6d6dc-8596-11e6-835d-c454686b15e4.png">

Which also is partly why we ended up not including the block background behind the keys in the initial implementation of this (even though it was designed as such).


However, here's what it looks like with the block decorations.
<img width="359" alt="screen shot 2016-09-28 at 4 30 18 pm" src="https://cloud.githubusercontent.com/assets/11839736/18936017/dfa42f82-8598-11e6-848d-aa6578cb343d.png">

If so, I would need @chrmarti to put some logic to put spans around each keybinding (not the "/"s) and this class could be named say "keybinding-block".

Then the decoration CSS is
```


:hov


.cls

element.style {
}
.keyblock {
    background: #171717;
    padding: 3px;
    border-radius: 2px;
    display: inline-block;
}
```
And we would adjust the table's border spacing to `border-spacing: 13px 13px`

**Comment by joaomoreno** [comment]
Right about monospace! Love your last screenshot!

**Comment by chrmarti** [comment]
The contrast between block decorations and keybindings is too low for me to be useful. If we want to add these, I'd suggest to find a way to increase that.

**Comment by joaomoreno** [comment]
Make sure you try it in all the themes. And there are other ways to show contrast, like a border.

**Comment by bpasero** [comment]
Imho the spacing now looks bad on Windows:

![image](https://cloud.githubusercontent.com/assets/900690/18943910/c27083a4-8622-11e6-8fe3-35cde2c5bb95.png)

**Comment by chrmarti** [comment]
Fixed the letter-spacing on Windows and Linux. No further action planned for September. Thanks.
