### ISSUE TITLE
Ability to disable extensions

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#12710]
- VSCode Version: Code - Insiders 1.6.0-insider (be5e8d5733c1c012d7e3a6c7e049b59d67c13978, 2016-09-26T06:05:01.421Z)
- OS Version: Darwin x64 16.0.0

It would be great if one could disable extension (as opposed to uninstalling it)

Something similar to how Chrome allows to Disable or Uninstall extension
![image](https://cloud.githubusercontent.com/assets/1723815/18858912/ab02ce84-843d-11e6-833e-613a1e5f6a38.png)

**Comment by joaomoreno** [comment]
#2882
