### ISSUE TITLE
`s` and `k` bug in regex search

### ISSUE THREAD

**Issue by Keillion** [microsoft/vscode#127146]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.54.3 (system setup)
- OS Version: win10

Steps to Reproduce:

See image:

![图片](https://user-images.githubusercontent.com/15797718/123422518-eb363e00-d5f0-11eb-9f91-7f1cd7d9a114.png)

`\u017f` is <code>&#383;</code>.

`k` and `K` have similar bug as well.

![图片](https://user-images.githubusercontent.com/15797718/123424185-191c8200-d5f3-11eb-8110-8cb32096d177.png)

**Comment by Keillion** [comment]
Temp walk around:
![图片](https://user-images.githubusercontent.com/15797718/123424819-efb02600-d5f3-11eb-9ee5-f709630d9786.png)

**Comment by alexdima** [comment]
We actually convert this to a JS regex i.e.:

```js
/\u017f/giu.test('s')
```

And it looks that's how the JS regexp engine behaves.

**Comment by Keillion** [comment]
> 
> 
> We actually convert this to a JS regex i.e.:
> 
> ```js
> /\u017f/giu.test('s')
> ```
> 
> And it looks that's how the JS regexp engine behaves.

Thx. So it looks like by design. [`ſ` is `s` in latin](https://www.fileformat.info/info/unicode/char/17f/index.htm).

Should I close it? @alexdima

**Comment by alexdima** [comment]
:+1: Let's close, there's nothing we can really do on our side.
