### ISSUE TITLE
Numerous bugs on debug console window

### ISSUE THREAD

**Issue by CptJackSparrow7** [microsoft/vscode#127116]
1. Rt-Click -> Clear Console
doesn't work
2. console.log(....)
doesn't even come up in the console window.

**Comment by CptJackSparrow7** [comment]
![image](https://user-images.githubusercontent.com/62038258/123343366-9ecefd80-d51f-11eb-92eb-44f2f1816961.png)

launch.json
{
        "version": "0.2.0",
        "configurations": [
            {
                "type": "chrome",
                "request": "launch",
                "name": "Launch Chrome",
                "url": "http://localhost:1750",
                "webRoot": "${workspaceFolder}/ApmsCore/wwwroot",
                "breakOnLoad": true
            }          
        ]
    }

**Comment by CptJackSparrow7** [comment]
And just an added note - 
This -> "outputCapture": "std"

comes up as an error -
Property outputCapture is not allowed.

**Comment by isidorn** [comment]
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Forwarding to @connor4312 since it looks like a chrome config. Though I think this can not easily be reproduced...

**Comment by CptJackSparrow7** [comment]
I installed VSC Insiders and I have the same problem.

For both IDEs, the console.log statements will appear in the browser.

What I do get in the Debug window is this ->
![image](https://user-images.githubusercontent.com/62038258/123417096-59ddb200-d585-11eb-98b2-c78cb1cd2e6f.png)

But the clear console button and the rt-click sortcut to clear the console don't work.

**Comment by CptJackSparrow7** [comment]
One more observation
Obviously when I open VSC the debug window is blank.  When I run the web app, it freezes at a random point.  So another time the debug window looks like this ->
![image](https://user-images.githubusercontent.com/62038258/123418814-84c90580-d587-11eb-9e8f-68a56314d95a.png)

Even thought the web app runs normally, the debug window in VSC is frozen.  So you can't clear it, and if I stop and re-run the web app, the debug window won't change, it is completely frozen.  

The other thing I notice is that even though I can't clear it or won't clear on its own, and nothing else can be added, I can click on the > to look at the content of the objects ->
![image](https://user-images.githubusercontent.com/62038258/123419525-4e3fba80-d588-11eb-8336-285f395b4659.png)

If I type something at the bottom of the debug window, nothing will be added to the debug window.

The terminal window, no problems there.  Even with the debug window frozen, the terminal window works fine.

**Comment by CptJackSparrow7** [comment]
If I install an earlier version of VSC, it works with no problems.
![image](https://user-images.githubusercontent.com/62038258/123421022-53056e00-d58a-11eb-9e86-614d0fb4dce7.png)

During the process of uninstalling, I notice the latest was installed on 6/23/2021.

I still have VSC Insiders installed, so we can keep at it if you want.

**Comment by connor4312** [comment]
Sounds like the user is reporting that the clear button doesn't work
