### ISSUE TITLE
Jupyter Notebook Markdown error

### ISSUE THREAD

**Issue by sravanpannala** [microsoft/vscode#127186]
Jupyter notebooks show an error message when changing a cell from python code to markdown. To reproduce:
1. Create a new code cell
2. Type a sentence
3. Change the cell to markdown by pressing M.
4. The cell converts to markdown but shows an error message "No renderer found for "text/plain" a"
This error doesn't show when directly creating a new markdown cell.

**Comment by sravanpannala** [comment]
![image](https://user-images.githubusercontent.com/57152030/123478209-245cb700-d5cd-11eb-87b2-caa61bca51ce.png)

**Comment by mjbvz** [comment]
Please fill in the issue template 

/needsMoreInfo

**Comment by rebornix** [comment]
@mjbvz I can reproduce this by press M in a github issue notebook with jupyter extension installed.

**Comment by sravanpannala** [comment]
I filled the issue template here. I did it using the bug reporting feature in VSCode.
https://github.com/microsoft/vscode/issues/127798

**Comment by mjbvz** [comment]
Duplicate of #127363
