### ISSUE TITLE
Multiple instances of vscode open on launch even from the command prompt

### ISSUE THREAD

**Issue by sambit-git** [microsoft/vscode#127103]
Issue Type: <b>Bug</b>

I'm getting a very weired behaviour from the VSCode quite recently.
If I've not opened any folder in vscode it opens one instance of VSCode(no issue and expected behaviour),
but if I open any folder in VSCode; the next time I open it, it launches 2 instances of itself(one with the folder opend that I'd opened earlier and one fresh instance where no folder is opened).
I've even tried to open VSCode from windows command prompt to cross verify if the issue is with my mouse but getting the same weired behaviour

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.45GB free)|
|Process Argv|--crash-reporter-id f23a760b-b910-4bbb-a86f-cbf41645ca3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.23.1
flutter|Dar|3.23.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by bpasero** [comment]
Can you check if https://github.com/microsoft/vscode/issues/126725 helps

**Comment by sambit-git** [comment]
Yes, that resolution helped to resolve the issue.
But in my case the **Backup** folder was inside **_%APPDATA%\\Code\\_** which I deleted and the issue was gone. Thank you so much.
