### ISSUE TITLE
Git diffs are displayed offset when PR review are displayed inline

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#127133]
- Extension version: v0.27.1
- VSCode Version: v1.57.1
- OS: Win 20H1

Steps to Reproduce:

1. Create a PR
2. Add a comment somewhere to file A
3. Change the file locally in VS Code
4. Open the git diff of the file:

   ![image](https://user-images.githubusercontent.com/38782922/123001529-1e8a8a00-d3b1-11eb-9188-b1340060720b.png)

As you can see, everything after the first comment is vertically shifted because of the comment. Instead, left to the comment there should be a gap. See also how GitHub & GitLab are solving this in their online views.

Expected behavior: The selected lines in the left and the right pane should be displayed next to each other.

**Comment by alexr00** [comment]
@rebornix I think this is an issue with how the comments widget and the diff view interact. Is that correct, or is there some way for me to control this as a consumer of the comments API?

**Comment by rebornix** [comment]
I wonder if it's related to word wrap, @LinqLover can you try turn off word wrap and see if you see the same issue?

**Comment by LinqLover** [comment]
Unfortunately, I cannot reproduce this issue at the moment, but I always have turned on word-wrap in my git diffs. I will report back if I am able to reproduce the issue again ...

**Comment by LinqLover** [comment]
Closing this until I or someone else is able to reproduce. I use this extension pretty seldom, though ...
