### ISSUE TITLE
Test: Terminal editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127192]
Refs: #10546 #125514

- [x] macOS @lszomoru
- [x] linux @weinand
- [x] Windows @andreamah

Complexity: 5

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127192%0A%0A)

---

Terminals can now be moved to editor groups, there are a few ways to do this:

- Drag a terminal tab into an editor group
- Right click a terminal tab and select move into editor group
- Run either `Create Terminal Editor` or `Move Terminal into Editor Group` commands
- Set `"terminal.integrated.defaultLocation": "editor"`
Before creating issues please read the [philosophy section of the plan item](https://github.com/microsoft/vscode/issues/125514) to get an understanding of what's expected - feedback is welcome of course.

Please do some exploratory testing around the editors, here are some things to get you started and keep an eye on:

- During development we ran into these issues a few times
  - Reloading the window would sometimes shuffle the terminals randomly
  - The terminal panel would be empty when terminal editors were used
  - Some terminal commands wouldn't work as expected in editors and/or the panel
- Does the terminal extension API work in terminal editors and are events fired correctly?
- Editor tab icon, color and status show up correctly
- Terminal status information shows up when hovering editor tabs
- Terminal editors should always be pinned
- Does ctrl+w close the tab as expected on Windows and Linux? It's meant to close the tab and not send ^w to the terminal by default
- Does split editor work?
- Does the add terminal editor action button and dropdown work?
- Does process reconnection work after reload?
- Different environments:
  - Remote extensions
  - Codespaces
  - Live share

**Comment by weinand** [comment]
The term "Terminal Editor" sounds rather strange.
Is there a functional difference between an "Integrated Terminal" and a "Terminal Editor" (other than its container)? Since terminals can be freely moved between the panel area and the editor area, I don't think so, right?
It would make more sense to me if the "Create Terminal Editor" command would be called "Create Terminal in Editor area"

**Comment by Tyriar** [comment]
@weinand sounds good to me, "Terminal Editor" is the internal term and that was the first command we added to get started. We're using this "in editor area/group" in this command and the context menus already:

<img width="298" alt="Screen Shot 2021-06-29 at 8 51 45 AM" src="https://user-images.githubusercontent.com/2193314/123829345-3c775380-d8b7-11eb-8da5-ac0214b8e76c.png">
