### ISSUE TITLE
Search in Notebook keeps looking for incorrect term

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#127198]
Issue Type: <b>Bug</b>

- Started typing `editorop`.
- Search kept going through `ed` results, and highlighted them.
- Cleared out search and tried again.
- Search for `ed` continued 

![image](https://user-images.githubusercontent.com/8599/123491015-85cf5680-d5ca-11eb-8006-e6d89cd278d4.png)

VS Code version: Code - Insiders 1.58.0-insider (49e1f9919880c1c96004f9b6ad91bcee7a94a1bd, 2021-06-25T05:14:06.587Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (12.38GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|1.94GB (0.14GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
tsl-problem-matcher|eam|0.4.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
codespaces|Git|0.10.7
remotehub-insiders|Git|2021.6.2502
fluent-icons|mig|0.0.12
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-es|MS-|1.58.5
vscode-edge-devtools|ms-|1.2.0
remote-containers|ms-|0.184.0
debugger-for-edge|msj|1.0.15
msft-todo-unofficial|tyl|0.0.11
gitlens-insiders|eam|2021.6.2201
vscode-language-pack-es|MS-|1.58.5
python|ms-|2021.7.922878407-dev
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.7.970869158
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693

```

</details>

**Comment by rebornix** [comment]
@digitarald are you able to reproduce this issue recently?

**Comment by digitarald** [comment]
@rebornix yes, just tested in a Kusto notebook. Plain text file works fine.

**Comment by rebornix** [comment]
@digitarald do you mind share the notebook you have?

**Comment by rebornix** [comment]
@digitarald thanks, this is a good bug catch.
