### ISSUE TITLE
Shortcut, Shortcut Tooltip for "Replace Next" "Replace All "

### ISSUE THREAD

**Issue by name2name2** [Microsoft/vscode#12715]
- VSCode Version:1.5.3
- OS Version:win 10

I hope for Replace there is keyboard shortcut to use,  for "replace next ", "replace all" function,

besides, when mouse hover on the replace Button, the tooltip will show what the shortcut is.

Thanks.

reference img:
http://i.imgur.com/PbWbwKY.png

(In fact I think this function is similar to visual studio which is Alt R and Alt A, but i wonder why vscode didn't inherit it)

**Comment by sandy081** [comment]
@name2name2 Tool tip for keyboard shortcut is also shown for these actions. Please check below:

![oct-03-2016 12-49-39](https://cloud.githubusercontent.com/assets/10746682/19035141/f6326548-8967-11e6-8336-aeadc9450c05.gif)
