### ISSUE TITLE
[Welcome Page] Mark newly contributed walkthroughs as `new` 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#127196]
When an extension has newly contributed a walkthrough, it should be shown as `New` on the welcome page. It should remain `New` until it gets manually opened (not auto-opened via the install), or some number of days have passed (7?).\

Additionally, if an existing walkthrough adds new steps, it should be marked as having `New Items`, and should remain like this until it is opened.

**Comment by JacksonKearl** [comment]
\closedWith e03f9bd93a82f20c5b3cb2239315b65a3f8499ea

**Comment by rzhao271** [comment]
I clicked on the new Luna Paint walkthrough, and then went back to the welcome view.
I noticed the new label was still there.
I repeated the process and the same thing occurred.
I resized the window to try and take a gif with gifcap, and then noticed the new label was gone by then.
I'm not sure how to reset the process.
