### ISSUE TITLE
openEditor SIDE_GROUP isn't working as expected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127191]
Repro:

Replace [TerminalEditorService.splitInstance](https://github.com/microsoft/vscode/blob/49f5aba877a5b5e2d339425881dd45e84b30f2af/src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts#L162-L168)'s implementation with:

```ts
	splitInstance(instanceToSplit: ITerminalInstance, shellLaunchConfig: IShellLaunchConfig = {}): ITerminalInstance {
		const instance = this._terminalInstanceService.createInstance(shellLaunchConfig, TerminalLocation.Editor);
		this._editorService.openEditor(this.getOrCreateEditorInput(instance), SIDE_GROUP);
		return instance;
	}
```

Try split a terminal using the + dropdown editor action:

<img width="489" alt="Screen Shot 2021-06-25 at 1 47 31 PM" src="https://user-images.githubusercontent.com/2193314/123483629-e4410880-d5bb-11eb-8f0a-aac790998804.png">

**Comment by bpasero** [comment]
```ts
splitInstance(instanceToSplit: ITerminalInstance, shellLaunchConfig: IShellLaunchConfig = {}): ITerminalInstance {
	const instance = this._terminalInstanceService.createInstance(shellLaunchConfig, TerminalLocation.Editor);
	this._editorService.openEditor(this.getOrCreateEditorInput(instance), undefined, SIDE_GROUP);
	return instance;
}
```

**Comment by bpasero** [comment]
Btw we will eventually deprecate passing in typed (heavy) editor inputs to `IEditorService` so please consider using untyped inputs: `{ resource... }`

**Comment by Tyriar** [comment]
Plan:

- Adopt proper `SIDE_GROUP` call
- Assign the shell launch config to a resource before the terminal when requested, when the editor input is initially, use the stored shell launch config

**Comment by Tyriar** [comment]
Deferring untyped adoption to https://github.com/microsoft/vscode/issues/129183
