### ISSUE TITLE
Tab key focus movement is always applied

### ISSUE THREAD

**Issue by m-misa** [microsoft/vscode#127112]
#127040
Tab key focus movement is always applied.
Does not change even if the function is turned off.
I'm having trouble moving the cursor when using snippets.
Is there a way to force it to be disabled?

>F1 > Tab Key Moves Focus

Even if you make that setting, it will not change.
Is there a solution?
OS: win10 Pro

**Comment by m-misa** [comment]
https://user-images.githubusercontent.com/86388242/123340427-2734b900-d587-11eb-886a-3a8321e11e95.mp4

**Comment by isidorn** [comment]
dup of https://github.com/microsoft/vscode/issues/127040
