### ISSUE TITLE
[Test UI] Sort by Location does not work

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#127122]
Issue Type: <b>Bug</b>

Sometimes tests should be presented in a specific order, such as modeling the same tree that the tests are defined in. Currently it appears the tests are sorted regardless of what order they are added via CreateTestItem even if "Sort by Location" is selected.

![image](https://user-images.githubusercontent.com/15258962/123356499-b1940300-d51c-11eb-953c-c6a2dd1c5da6.png)

VS Code version: Code - Insiders 1.58.0-insider (3caebff71e514ece73b125468881d102e767ee4d, 2021-06-24T05:13:30.907Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (4.40GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/JGrote/Projects/vscode-adapter --crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell-preview|ms-|2021.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by connor4312** [comment]
Thanks for the issue,

/duplicate https://github.com/microsoft/vscode/issues/126620

**Comment by JustinGrote** [comment]
@connor4312 I don't think it's a dupe, see "Context Test". I would expect that to come after "basic" (which has failed tests) but instead Describe Nested Foreach Cactus comes next, and the remaining entries are in alphabetical order. I fed them to createTestItem in the order shown in the source file.

**Comment by connor4312** [comment]
Oh, yea, that seems like a bug

**Comment by connor4312** [comment]
This seems to work now... However I also notice you don't have gutter decorations, which would indicate to me that you don't have `range`s on your TestItems, which would prevent the decorations from being displayed.

**Comment by JustinGrote** [comment]
@connor4312 I do now that was before documentTestRoot etc. got merged. Will take at insiders tomorrow.

**Comment by roblourens** [comment]
It looks like "Sort by name" is gone, I assume that's expected, and now I see "Sort by Status/Location" which both work as expected

**Comment by connor4312** [comment]
yep. Seems like people didn't really like/need alphabetical sorting (at least within a file.)
