### ISSUE TITLE
Bold cursor

### ISSUE THREAD

**Issue by richardklavins** [microsoft/vscode#127102]
Issue Type: <b>Bug</b>

Hello, 
my CURSOR is "BOLD".
I tried: Insert, Fn+Insert, Shift+Ctrl+I - did't help...
Say to me please: how can I fix it?
Thank you.
Richard

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.36GB free)|
|Process Argv|--crash-reporter-id c13155d5-8d3e-40e7-86c0-74af0a26cd01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.42.1
ecsstractor-port|diz|0.0.3
githistory|don|0.6.16
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|8.0.1
git-project-manager|fel|1.7.1
live-pug-compiler|jah|1.0.1
kite|kit|0.147.0
HTMLHint|mka|0.10.0
vscode-apache|mrm|1.2.0
vscode-css-navigation|puc|1.10.6
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlang:30322306
binariesv615:30325510
vsccppwtct:30322537

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have any of these 2 settings changed: `editor.cursorStyle` and `editor.cursorWidth`?
Screenshot would be helpful.

**Comment by richardklavins** [comment]
Fixed. Settings - Search: cursor - Editor: Cursor Style - Changed "Block" to "Line".
Thanks to all
