### ISSUE TITLE
Terminal URI link providing failes when including brackets ("[", "]")

### ISSUE THREAD

**Issue by Elias-Graf** [microsoft/vscode#127138]
Issue Type: <b>Bug</b>

The issue is only present with local files (e.g. `https://example.com/[id].html` works).

Enter a local URI into the terminal, for example:
```
test/some/sub/[id].spec.tsx
```
The link will not show up at all in most cases, and when pressing `ctrl` it will only "provide" a link for parts of the URI. E.g. "test/some/sub" or "id" or ".spec.tsx".

VS Code version: Code - Insiders 1.58.0-insider (d54f7e1f6c1290fe27e2397eca509d0e0728272e, 2021-06-22T07:15:45.422Z)
OS version: Linux x64 5.11.0-22-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2931)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.33GB (17.27GB free)|
|Process Argv|--force-user-env --unity-launch --crash-reporter-id bb42f7f6-b338-4930-b746-ce15c0be7b83|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
todo-tree|Gru|0.0.213
vscode-docker|ms-|1.14.0
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by Elias-Graf** [comment]
![Peek 2021-06-25 11-53](https://user-images.githubusercontent.com/46671625/123407233-06328f00-d5ac-11eb-9f51-16f7dd9396d5.gif)

**Comment by Tyriar** [comment]
We currently treat `[` and `]` as word separators for validated links here:

https://github.com/microsoft/vscode/blob/637403c1d57125ed9eb78eb527d16d721fc221a8/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L23-L23

I'm hesitant to change this as then it would break the `[link.ext]` format which would be much more common.

I'm going to close this as designed but you can work around it by excluding `[` and `]` from the _word_ link provider with this setting:

```
"terminal.integrated.wordSeparators": " (){}',\"`─"
```

Which should result in this:

![image](https://user-images.githubusercontent.com/2193314/124654906-00fafd00-de54-11eb-9695-5f7f5240d02a.png)

**Comment by Elias-Graf** [comment]
@Tyriar I have never heard of the `[link.ext]` format but I agree that having brackets in a URI is uncommon. I just stumbled across it because NextJs used it for dynamic routing. https://nextjs.org/docs/routing/dynamic-routes

**Comment by Tyriar** [comment]
This is probably important enough to revisit.

**Comment by jasonwilliams** [comment]
> I'm hesitant to change this as then it would break the [link.ext] format which would be much more common.

I've never heard of this format, could you give some examples of where that's used?

**Comment by arxpoetica** [comment]
SvelteKit also uses it for dynamic routing.

**Comment by benmccann** [comment]
To clarify the last comment, SvelteKit has directory names with brackets in them, which currently breaks terminal links. I believe Next.js is the same. This is an argument for changing the current behavior and not maintaining the status quo

**Comment by Elias-Graf** [comment]
My two cents, not even considering it breaks my project: 

> We currently treat [ and ] as word separators for validated links here:

I would argue that no characters should "create new works". If it's allowed in an URI, it should be treated as an URI. Everything else is basically language/framework-specific, and should be in an extension, right?

**Comment by arxpoetica** [comment]
> If it's allowed in an URI, it should be treated as an URI

I'm no expert, but [here's the RFC section](https://datatracker.ietf.org/doc/html/rfc3986#section-2) which called `[` and `]` "gen-delims." I'm not 100% sure what it all means over there. I'll leave that up to someone more expert here.

**Comment by Elias-Graf** [comment]
> The purpose of reserved characters is to provide a set of delimiting characters that are distinguishable from other data within a URI. **[...]** Thus, characters in the reserved set are protected from normalization and are therefore safe to be used by **scheme-specific and producer-specific** algorithms for delimiting data subcomponents within a URI.

If I'm interpreting "scheme-specific" and "producer-specific" correctly, this is arguably exactly what NextJs and (apparently) the [link.ext] format, as well as SvelteKit are doing.

**Comment by arxpoetica** [comment]
@Elias-Graf you're right! In other words applications should respect these as safe URIs.
