### ISSUE TITLE
Problems tab shows deleted file

### ISSUE THREAD

**Issue by lucademian** [microsoft/vscode#127185]
Issue Type: <b>Bug</b>

I have a file that was deleted when switching branches, and it was open when it was deleted and had some debugging problems, but the problems won't disappear from the problems tab and the debugger recognizes them as build errors, and clicking on them in the problems tab opens a dialog saying that the file couldn't be found so there's no way to get rid of them stuck in the problems tab.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 085ee7dd-53be-4a79-9d29-74d6c8b98a5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ccs-flutter-color|cir|1.0.1
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.23.1
flutter|Dar|3.23.0
gitlens|eam|11.5.1
bloc|Fel|5.6.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
awesome-flutter-snippets|Nas|3.0.0
color-highlight|nau|2.3.0
pdf|tom|1.1.0
vscode-conventional-commits|viv|1.21.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615cf:30323120
vsccppwtct:30322537

```

</details>

**Comment by sandy081** [comment]
Please file the issue against the extension that generates these problems. It has to reconcile and regenerate problems.
