### ISSUE TITLE
Test: Detach and attach terminal sessions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127195]
Refs: #118276

- [x] macOS @egamma
- [x] linux @TylerLeonhardt
- [x] Windows @DavidKutu

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127195%0A%0A)

---

Previously we've had the feature to attach to remote terminal session for example in a codespace and a window was closed. This iteration we implemented manual detaching from a session and support in local windows via the command palette.

![image](https://user-images.githubusercontent.com/2193314/123871899-271b1d00-d8e9-11eb-9326-1b69b5ec690d.png)

Test that it's possible to detach and reattach terminal processes in both local and remote and that you can detach in one window and reattach the terminal in a different window.

**Comment by DavidKutu** [comment]
Works on windows, both locally and remotely. Tyler's issue doesn't seem to repro on Windows.
