### ISSUE TITLE
Support untyped side by side editor input

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127131]
We currently cannot express a untyped side by side editor input. Going forward we should support it if we have clients for it.

Related: I see how `SideBySideEditorInput.matches` checks on `isResourceDiffEditorInput` which imho is wrong because that untyped input is for `DiffEditorInput` only.

https://github.com/microsoft/vscode/blob/66de74f58cdefe164f114093a735902aa5c95517/src/vs/workbench/common/editor/sideBySideEditorInput.ts#L135-L137

**Comment by lramos15** [comment]
Something I realized when working on this is then you get the annoying inheritance which means you must add `primary` and `secondary` to the untyped diff editor inputs repeating the same information twice.

**Comment by bpasero** [comment]
I see the issue and wonder if maybe the 2 editor inputs should merge into 1? The fact that an editor is a diff editor imho is not so important, rather that it has 2 sides (left and right).

**Comment by lramos15** [comment]
> I see the issue and wonder if maybe the 2 editor inputs should merge into 1? The fact that an editor is a diff editor imho is not so important, rather that it has 2 sides (left and right).

@bpasero Do you mean the two untyped inputs or the two typed inputs? I guess my concern is how do we know to render a diff view vs just a side by side view?

**Comment by bpasero** [comment]
That's a good point and maybe this get's easier when the editor pane registration is handled alongside the editor resolver registration: the inputs can easily be just side by side, we don't need to distinguish diff from side by side. But when it comes to how to render the inputs, we need to distinguish because the editor panes are obviously different. Then we could simply pick the right editor pane based on the editor id of the input right?

**Comment by bpasero** [comment]
I went down the pragmatic route and left the inheritance of side by side and diff as it is. There is now a way to use:

```json
{
  primary: ...
  secondary: ...
}
```

As a untyped side by side input and have that be resolved.

@lramos15 in the PR the interesting code is mainly around how the resolver should create the side by side input:

https://github.com/microsoft/vscode/blob/c942ef31601a108743de8cfb0cedf8cfd7f9efaa/src/vs/workbench/services/editor/browser/editorResolverService.ts#L372-L383

Instead of requiring registered resolvers to implement a `createSideBySideInput` method, I am simply resolving both sides and create the input myself.

**Comment by bpasero** [comment]
Oh, I just figured out that the code in resolver service was not doing the right thing, this needs to happen earlier, pushed more changes:

https://github.com/microsoft/vscode/blob/939daed2be4d541909f7f36edaa2cbd9e500a60a/src/vs/workbench/services/editor/browser/editorResolverService.ts#L120-L136

**Comment by lramos15** [comment]
> Oh, I just figured out that the code in resolver service was not doing the right thing, this needs to happen earlier to resolve the right editor per side, pushed more changes but they are a bit ugly...
> 
> https://github.com/microsoft/vscode/blob/939daed2be4d541909f7f36edaa2cbd9e500a60a/src/vs/workbench/services/editor/browser/editorResolverService.ts#L120-L136

Is it worth still returning something or is it weird if you passed in an untyped side by side and had the chance of getting just a normal editor input back?

**Comment by bpasero** [comment]
Yeah I wasn't sure what to return if one of the sides does not resolve. Thats an interesting idea to return half side if one fails but might be unexpected. Because in the end the request is explicitly to create a side by side input.

**Comment by lramos15** [comment]
Well isn't that what you're currently doing based on the above code? It seems like you are returning half if one side doesn't resolve

**Comment by lramos15** [comment]
So why wasn't it doing the right thing? Can you not do this?

```js
 	const primaryInputWithOptions = await this.doResolveEditor(editor.primary, group, selectedEditor); 
 	const secondaryInputWithOptions = await this.doResolveEditor(editor.secondary, group, selectedEditor); 
 	if (!isEditorInputWithOptionsAndGroup(primaryInputWithOptions) || !isEditorInputWithOptionsAndGroup(secondaryInputWithOptions)) { 
 		return; 
 	} 
```

**Comment by bpasero** [comment]
Yeah actually just wanted your feedback on that part, I can do anything you suggest. Wasn't sure if returning `undefined` is fine in that case.

**Comment by lramos15** [comment]
> Yeah actually just wanted your feedback on that part, I can do anything you suggest. Wasn't sure if returning `undefined` is fine in that case.

I would assume we want to return undefined since that's what we do when we don't support diffs. I would call this an unsupported case

**Comment by bpasero** [comment]
The API does not allow me to return `undefined` so I return `ResolvedStatus.NONE`:

https://github.com/microsoft/vscode/blob/919d4dd22c23f6cff42008069046cb069bbba4bb/src/vs/workbench/services/editor/browser/editorResolverService.ts#L198-L204
