### ISSUE TITLE
Test: editor history and reopening

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127172]
Refs: 

- [x] anyOS @sbatten
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127172%0A%0A)

---

Editor history and reopening closed editors was rewritten to run with untyped editors and not heavyweight editors.

![image](https://user-images.githubusercontent.com/900690/123460785-765f0600-d5e8-11eb-8ec8-8eed9abd5a8d.png)

**Verify Reopen Close Editors**
* open a few editors including custom ones like notebooks, Luna paint or HEX
* close them
* trigger reopen closed editor (`Cmd+Shift+T`) and verify these editors restore

**Note:** the list of recently closed editors is global across all editor groups and not specific for a editor group.

**Verify History**
* open a few editors including custom ones like notebooks, Luna paint or HEX
* verify the list of recently opened grows in file picker with the most recently opened editors appearing to the top
* verify you can open entries from the recently opened by clicking them in the picker
* verify dirty editors appear as such in the picker as well as untitled editors
* reload the window and verify the list of recent editors is still there as it was before
* close a file editor and a untitled editor
* verify only the file editor is still showing up in the picker as recently opened but the untitled one is gone and that you can open the file again when selecting the entry
* open a custom editor as text (e.g. notebook -> open with -> text editor) and verify that the history entry when opened uses that picked editor until you open it with a notebook again

**Comment by hediet** [comment]
> verify the list of recently opened grows in file picker with the most recently opened editors appearing to the top

Do you mean *File -> Open Recent*? I don't see a picker there, it is just a submenu.

**Comment by bpasero** [comment]
Please verify in both.

**Comment by hediet** [comment]
I still don't get it. `File -> Open Recent` only shows files that have been opened recently with the native file picker dialog. It does not show untitled files.

However, `Quick Open Least Recently Used Editor` only shows active editors, not closed ones.
I'm missing something.

I'm also confused what the difference is between those two:

![image](https://user-images.githubusercontent.com/2931520/123793565-229f3600-d8e2-11eb-9fe0-5937971ed3d0.png)

They seem to do the same for files.

**Comment by bpasero** [comment]
There is a history for the workspace which is Cmd+P and then there is File Open Recent which only lists files opened from the outside or via native file picker as well as workspaces. There is a picker too ("more...").

**Comment by hediet** [comment]
Ah, now I understand. I never used that one and there is no command that opens it, I also did not know about what Ctrl+P does.
But it seems like F1 -> DeleteLeft is the same thing.

**Comment by bpasero** [comment]
I bind the "File - Open Recent" to a key allowing me to quickly switch workspaces but I never use it to access files in there, only workspaces. For navigating files, I use "Go - Go to File" which conveniently tracks recently opened files of the workspace. 

I would say, the fact that files appear in "File - Open Recent" is just some standard behaviour all editors, or even all apps that can open something provide, but I felt that putting every file in there that is ever opened in VSCode is overkill. Though I have had users complaining about that...

**Comment by bpasero** [comment]
My keybinding: 

```json
{
    "key": "cmd+shift+r",
    "command": "workbench.action.openRecent"
}

{
        "key": "cmd+shift+r",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    }
```

With this I can switch workspaces and even opened windows with 1 picker.
