### ISSUE TITLE
Remove deprecated auth api proposals

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127144]
There is a bunch of proposed auth API which is [deprecated](https://github.com/microsoft/vscode/blob/6a76c62232208f54bc85f22572013b382e39cf9e/src/vs/vscode.proposed.d.ts#L19-L59) since almost a year. We should remove this proposal now.

**Comment by bpasero** [comment]
Reverted since it caused compile errors.

**Comment by TylerLeonhardt** [comment]
Thanks @bpasero!

**Comment by TylerLeonhardt** [comment]
no more compile errors this time
