### ISSUE TITLE
[html] HTML colors angle brackets wrongly in dark theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1271]
Angel brackets should be blue not orange in this screenshot.

<img width="376" alt="screen shot 2015-12-14 at 15 06 15" src="https://cloud.githubusercontent.com/assets/1926584/11782942/85b4c4da-a274-11e5-8215-192af4271568.png">

**Comment by aeschli** [comment]
fix delivered

**Comment by isidorn** [comment]
I guess you should assign it to me for verification :hamster:
