### ISSUE TITLE
LineNumber config variable in launch.json and tasks.json

### ISSUE THREAD

**Issue by gerich-home** [Microsoft/vscode#12714]
Launch.json and tasks.json currently support several config variables (https://code.visualstudio.com/docs/editor/tasks#_variable-substitution)
However I could not find the ability to know the currently selected line in the current file.
Adding this variable will allow such tasks as running the test under cursor with external command without writing a full blown extension for it.

As I understood the file responsible for adding config variables is the following: https://github.com/Microsoft/vscode/blob/62d4b783965fcabc431c786146917593a2772b3d/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L77
I could also find a code from vscode-go that allows running test under the cursor:
https://github.com/Microsoft/vscode-go/blob/0e5a97fa5cfd4e3b37e5b2fbfbf9c788f0381878/src/goTest.ts#L44

**Comment by Shamwow16** [comment]
Please to this. Makes running test at point impossible without.

**Comment by dbwest** [comment]
Is this supported yet?

**Comment by isidorn** [comment]
No, but PRs are welcome.
Code pointer -> https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L19

**Comment by kinnrot** [comment]
+1
@isidorn - where is the current line number is being stored currently ?

**Comment by isidorn** [comment]
You can use something in the likes of `editorService -> getActiveEditor -> getSelection -> lineNumber`

**Comment by isidorn** [comment]
ping @michelkaporin
