### ISSUE TITLE
VS code opens an extra empty window when started

### ISSUE THREAD

**Issue by watch24hrs-iiitd** [microsoft/vscode#127152]
Issue Type: <b>Bug</b>

When started VS Code opens an unintended extra empty window on its own. Even for an empty window, I have enabled the "welcome" page, but this unintended extra empty window doesn't even show the "welcome" page. No matter how many times I close it, it pops up back again on restarting vs code.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3083)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 2, 1|
|Memory (System)|7.56GB (1.92GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id e672c25f-4d9f-4748-bf1a-50db2dfa97c8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
preview-pdf|ana|1.0.0
markdown-checkbox|bie|0.1.3
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
mdmath|goe|2.7.4
gc-excelviewer|Gra|3.0.42
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
vscode-typescript-next|ms-|4.4.20210624
vscode-icons|vsc|11.5.0
json|Zai|2.0.2
material-theme|zhu|3.10.14

(7 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/126725

There are instructions within how to resolve this.
