### ISSUE TITLE
Test: transient workspaces

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127170]
Refs: https://github.com/microsoft/vscode/issues/119695

- [x] anyOS @gregvanl
- [x] anyOS @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127170%0A%0A)

---

A workspace is transient when it has a `"transient": true` property inside the contents, e.g.:

```json
{
    "folders": [
        {

        }
    ],
    "transient": true
}
```

**Verify:**
* a transient workspace can be opened e.g. from the command line or file picker
* reloading the window brings you back into an empty window
  * no UI state from the workspace remains (e.g. opened editors are gone)
  * you are being asked to save dirty files when reloading to not loose that state
* closing VSCode and restarting does not restore the transient workspace (may just open an empty window)
* once you have reloaded or restarted VSCode, you do not see an entry in the File > Open Recent list for that transient workspace

**Comment by alyssajotice** [comment]
From my own testing, it seems all of the verification steps work except for `closing VSCode and restarting does not restore the transient workspace (may just open an empty window)`.

**Comment by alyssajotice** [comment]
Also, about 50% of the time, I see the open file hang in the empty VS Code after reloading. 

![hanging-file](https://user-images.githubusercontent.com/22576531/123470996-029e0880-d5aa-11eb-8dfa-222d87bbab7f.gif)

**Comment by bpasero** [comment]
I appreciate you testing this already ahead of endgame because that takes a bit of the pressure away from fixing these issues 👍 

> From my own testing, it seems all of the verification steps work except for closing VSCode and restarting does not restore the transient workspace (may just open an empty window).

Can you try that again with a fresh user data dir (run `code-insiders --user-data-dir <some empty folder>`) just to rule out any settings? And if so, give me steps how to reproduce?

My test is always like this:
* open a workspace file that is transient
* File > Quit
* start again
* => an empty window opens

> Also, about 50% of the time, I see the open file hang in the empty VS Code after reloading.

I think you refer to the fact that the editor from the previous session restores? I can see if I can also fix that and make sure there is no workspace state restored.

**Comment by bpasero** [comment]
That case where we restore UI state, I think `reload` should really work different in transient workspaces: instead of literally reloading the workspace I would rather suggest that we do the same as File > Close Workspace, which is to open a fresh empty window.

**Benefits:**
* this would not restore any UI state
* if the user has unsaved data, we would ask to revert or save that data (prevents data loss)

Thoughts?

**Comment by bpasero** [comment]
I just pushed that solution and it works nicely. The remaining unknown is how you managed to restart and have such transient workspace restore. Did you maybe have untitled or files with dirty changes in it?

**Comment by alyssajotice** [comment]
Your solution fixed both of the problems I discussed above. For me, all of the verification criteria are working 👍 

I think that for transient workspaces overall, having reload actually be a close workspace command is a great idea and makes sense.

**Comment by gregvanl** [comment]
@bpasero I was initially confused by the last verification step. 
If I open the workspace in VS Code and change the `transient` state, the workspace entry is shown in the Open Recent list.
However, and this may be how this is designed, if I create a workspace outside VS Code with `transient` set to true or rename an existing workspace, then I don't see it in the Open Recent list.
