### ISSUE TITLE
Editor override service: stop the need for group to resolve an input

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127137]
There cannot be a need to know the group to resolve the editor for. It should be removed from the override service. If needed internally, use `activeGroup`.

**Comment by bpasero** [comment]
After our discussion I am not sure this is still needed, and maybe you cannot address this...

**Comment by lramos15** [comment]
I don't think this is easily addressable and our current solution seems like a good compromise point so I'm going to close this for now. We can revist it if the group continues to be an issue.
