### ISSUE TITLE
Commenting out with Mac with Cmd+/ not working

### ISSUE THREAD

**Issue by Alpdog14** [microsoft/vscode#127125]
I just upgraded my Mac VS Code to v1.57.1, and seems like the Cmd+/ shortcut is not working. I have tested disabling other extensions I have, but nothing seems to be causing this except the VS Code version update. It was working in previous version, and this shortcut is very very help with code development and testing, please apply a patch ASAP

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `cmd+/`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
