### ISSUE TITLE
Folding annotation "#region" must be in the line-start?

### ISSUE THREAD

**Issue by LonHon** [microsoft/vscode#127127]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.

### When I want to fold part of the code, the annotation "// #region" must start the line.
![image](https://user-images.githubusercontent.com/19330620/123363517-4b9f8e00-d5a5-11eb-9d11-6ecd7d43b964.png)

### I got the error from the indent rule.
![image](https://user-images.githubusercontent.com/19330620/123364481-0e3c0000-d5a7-11eb-9b9e-1aca3dbe39e3.png)

### when i change the indent space/tab, folding arrow does not appear ↓↓↓↓↓↓
![image](https://user-images.githubusercontent.com/19330620/123364330-cb7a2800-d5a6-11eb-9d8c-8147dcf467fe.png)

# What should i Do ?

2.

**Comment by aeschli** [comment]
The TypeScript LS creates all folding ranges here.

**Comment by mjbvz** [comment]
Please share the text of the code that demonstrates the issue

**Comment by mjbvz** [comment]
Closing as we need a self contained example to investigate
