### ISSUE TITLE
Drag selected text to move it

### ISSUE THREAD

**Issue by miladghiravani** [Microsoft/vscode#12718]
- VSCode Version: 1.5.3
- OS Version: Windows 8.1 Enterprise 64-bit

Steps to Reproduce:

Please enable drag selected text to move it (See this: http://stackoverflow.com/questions/33858029)
For exmaple this feature is in notepad++.
![gwuaic9](https://cloud.githubusercontent.com/assets/5067331/18864389/fc30b1bc-84a2-11e6-9b53-255a77c408d0.gif)

**Comment by miladghiravani** [comment]
@alexandrudima @bpasero Hi, please check this issue. Thank you.

**Comment by bpasero** [comment]
I did.

**Comment by miladghiravani** [comment]
There is the possibility to add this feature?

**Comment by batamire** [comment]
You can move selected text in Sublime with cmd+alt+left/right/up/down. I'd like to see the same in VSC.

**Comment by JTorresConsulta** [comment]
I cant understand why we cant drag selected text in VSC... I will return to sublime :(

**Comment by JTorresConsulta** [comment]
I cant understand why we cant drag selected text in VSC... I will return to sublime :(

**Comment by alexandrudima** [comment]
Duplicate of #1046. Please upvote there.
