### ISSUE TITLE
Test: file events

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127169]
Refs: 

- [x] macOS @sana-ajani
- [x] linux @joaomoreno
- [x] windows @joyceerhl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127169%0A%0A)

---

File events are now throttled but only when a large number of events is coming in. This test plan item is not for testing the throttling but making sure normal amount of file events are still properly reported because quite a bit of code was refactored and changed during the milestone.

**Testing:**
* open VSCode file explorer and editor on a folder side by side with an external tool that allows to do changes
* verify file modifications visualise in the explorer and editor (change, delete, create)
* verify the same steps opening a multi-root workspace (a different file watcher is used in that case)

**Comment by sana-ajani** [comment]
Works well!
