### ISSUE TITLE
Test: Finalized terminal APIs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127194]
Refs: #114898, #120369, #120538

- [x] macOS @jrieken
- [x] linux @TylerLeonhardt
- [x] Windows @JacksonKearl

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127194%0A%0A)

---

Several terminal APIs have been finalized this version, do a quick sanity check of them as they were tested thoroughly last month. They are:

- Contributed terminal profiles (contributions -> terminal -> profiles)
- `TerminalOptions.icon` API
- `Pseudoterminal.onDidChangeName` API

**Comment by JacksonKearl** [comment]
I don't see `TerminalOptions.icon`, using `TerminalOptions.iconPath`. I might prefer `TerminalOptions.icon` naming, as you can pass a `ThemeIcon` object which isn't really a path

**Comment by Tyriar** [comment]
@JacksonKearl `iconPath` is the standard that the API is moving towards for historical reasons.
