### ISSUE TITLE
Could not run python files -command 'python.execinterminal-icon' not found

### ISSUE THREAD

**Issue by purush** [microsoft/vscode#127142]
Installed new version of vscode for Mac .

Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 15.6.0

Installed  Extensions :
Python for VScode
Python
Pylance
Jupyter

When I click run button I get this Error "command 'python.execinterminal-icon' not found " - No idea what this mean ?  Can you let me know how ti fix it ?

**Comment by RakhulKumar** [comment]
Fix: Make sure you have selected the correct version of Python as the interpreter. You will get this error if you have more than one version of Python installed. The current Python interpreter version is mentioned at the bottom left corner in VS Code

**Comment by flutterq2** [comment]
[[Already Solved] command ‘python.execInTerminal-icon’ not found in VS Code](https://exerror.com/command-python-execinterminal-icon-not-found-in-vs-code/)
