### ISSUE TITLE
Patched bits: issue reporting should mention it

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12712]
When reporting an issue from a corrupt installation.

**Comment by bpasero** [comment]
@alexandrudima @chrisdias let me know what text the issue should have when the bits are patched.

**Comment by bpasero** [comment]
Going with:

![image](https://cloud.githubusercontent.com/assets/900690/18879150/8c4299ac-84d3-11e6-8d2e-4e0aca6832bd.png)

**Comment by alexandrudima** [comment]
@bpasero Thank you! Sweet! -- Just a heads up the `isPure` promise will now resolve at a minimum after 10s (I've delayed it, since it takes 50ms on my machine).

**Comment by bpasero** [comment]
@alexandrudima ok, just fyi when the user invokes the "Report Issue" action, this action needs to wait for the result of the `isPure` check, so if you manage to be very fast you might end up waiting a bit before the action does something.

**Comment by alexandrudima** [comment]
I suppose it's a fair trade-off, the page will open eventually. Worst case folks might click it multiple times (possibly enough time to click it twice in 10s)... I don't think it is something to worry more about except to be aware of it :)
