### ISSUE TITLE
Marketplace connection error after waking from hibernation

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#12724]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393
- error text: getaddrinfo ENOENT marketplace.visualstudio.com:443

Steps to Reproduce:
1. open VScode
2. hibernate PC
3. wake PC
4. ![image](https://cloud.githubusercontent.com/assets/821272/18865021/6201c616-8499-11e6-96f3-49e098d5588b.png)

**Comment by PaluMacil** [comment]
(confirming, all same details)

**Comment by PunchyRascal** [comment]
As for me, I haven't seen this error for a long time now. Maybe it has been fixed?

**Comment by joaomoreno** [comment]
It might've been with other changes. Closing it, will reopen if people still see it. Thanks for the update.

**Comment by PaluMacil** [comment]
I also can confirm I haven't seen it in a while. Not sure what fixed it, but seems good.

**Comment by roblourens** [comment]
I think there was another issue around the same time that fixed it.
