### ISSUE TITLE
Issues with extensions under an enterprise proxy

### ISSUE THREAD

**Issue by BenoitPingris** [microsoft/vscode#127299]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.57.1 (user setup)
- Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
- Date: 2021-06-17T13:28:07.755Z
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19042

I have a lot of issues regarding extensions under an enterprise proxy. As you can see on this image, images of the extension's description can't load. 
![image](https://user-images.githubusercontent.com/29386109/123603217-f27c6800-d7f9-11eb-8c3b-f667217d1782.png)

This is a minor issue but it's not the only one:
- I can't use extensions that need to fetch external resources once they are downloaded (live share, remote container etc.) it will fail (for instance when using the remote container here the issue I have: `Failed to download VS Code Server (https://update.code.visualstudio.com/commit:507ce72a4466fbb27b715c3722558bb15afa9f48/server-linux-x64/stable): HTTP 407 - authenticationrequired`)
- VSCode can't auto-update by itself, I need to re-download the installer each time I want to update it

*But* for some unknown reasons, extensions' miniatures will show up normally

![image](https://user-images.githubusercontent.com/29386109/123604563-3d4aaf80-d7fb-11eb-836a-7862d9f70e24.png)

Steps to Reproduce:

1. Go to the extensions section
2. Select one that has images in its description
3. Images can't load

Regarding the proxy settings, the first time I launched VSCode, it asked me to enter my credentials to setup the proxy, which I obviously did but still, I have the errors I mentionned just above.

I also tried to setup the proxy directly in the settings:
```json
"http.proxy": "http://my.proxy.address:8080",
"https.proxy": "http://my.proxy.address:8080",
```
and it did not solve the issue.

Am I missing something obvious here? If not, what could I try to fix this?

Thanks!

**Comment by deepak1556** [comment]
This is very likely a situation where the auth flow is not triggered for extension view and update scenarios. Auth credentials will be cached per socket pool group which depends on the origin, hence some connections sharing the same pool continue to work fine after the initial auth. Lets confirm this,

@BenoitPingris can you start the app with `code.cmd --log-net-log=netlog.json` and perform the steps in the extension view and update view, once the failure is seen quit the app and you should see a file `netlog.json` in the vscode installed directory. Attach the file to this issue.

**Comment by BenoitPingris** [comment]
Unfortunately I am not working anymore in this company.

Thus I cannot reproduce the issue as on my personnal machine I never encountered such issue.

**Comment by deepak1556** [comment]
Thanks for checking back, closing based on non-repro.
