### ISSUE TITLE
Markdown links rendered unreadable in dark theme

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12728]
- VSCode Version: 1.6.0-Insider
- OS Version: Windows

Steps to Reproduce:

1. Open a markdown file in dark theme (here the in place readme)
2. Observe the links are hard to read

![capture](https://cloud.githubusercontent.com/assets/1931590/18865937/ff755328-849d-11e6-9e95-a72b7cae897d.png)

**Comment by dbaeumer** [comment]
@kieferrm @joaomoreno told me to file this against markdown.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18867993/d20de090-84a6-11e6-9388-4447a117d494.png)

**Comment by mjbvz** [comment]
I also don't see this either. @dbaeumer Are you using any `markdown.styles`? 

Inspecting the preview html, I see this css rule is applied to links: https://github.com/Microsoft/vscode/blob/master/extensions/markdown/media/markdown.css#L19 Another explanation could be that the `markdown.css` file is not being loaded properly.

**Comment by dbaeumer** [comment]
@mjbvz no special mark down style. Interesting using it today on a md file in the docs repository shows correct rendering. Will close and assume it works now.
