### ISSUE TITLE
App crashed when using nativeTabs

### ISSUE THREAD

**Issue by expormz** [microsoft/vscode#127276]
Issue Type: <b>Bug</b>

set "window.nativeTabs" to true, and open more than one projects, when restart vscode ,  app will crash immediatly

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:50.042Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id bef0f521-e712-43ef-ab07-d036e009b98f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-tomcat|ada|0.11.3
project-manager|ale|12.2.0
separators|ale|2.1.0
icons-carbon|ant|0.2.4
docs-view|bie|0.0.9
path-intellisense|chr|2.3.0
vue-peek|dar|1.0.2
vscode-dash|dee|2.4.0
java-decompiler|dgi|0.0.2
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|8.0.1
nasc-touchbar|fel|1.12.0
auto-rename-tag|for|0.1.6
vscode-lombok|Gab|1.0.1
remotehub|Git|0.10.1
java-properties|ith|0.0.2
vscode-search-everywhere|kby|1.0.9
ignore-files|lde|0.1.0
vue-discovery|maa|1.4.0
jetbrains-icons|mar|1.0.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.14.0
vscode-language-pack-zh-hans|MS-|1.57.1
vscode-edge-devtools|ms-|1.2.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
hexeditor|ms-|1.7.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
back-n-forth|nic|3.1.0
vant-helper|Nor|0.0.2
vetur|oct|0.34.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-manifest-yaml|Piv|1.26.0
vscode-spring-boot|Piv|1.26.0
material-product-icons|PKi|1.0.4
vscode-css-peek|pra|4.2.0
java-ide-pack|pve|1.2.1
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.5.0
java|red|0.79.2
vscode-commons|red|0.0.6
vscode-xml|red|0.16.1
LiveServer|rit|5.6.1
vscode-checkstyle|she|1.4.0
vue-helper|she|2.4.7
java-generate-setters-getters|soh|7.0.3
sonarlint-vscode|Son|2.0.0
element-ui-snippets|SS|0.7.2
prop2yaml|tan|0.1.0
rest-book|tan|2.2.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
vscode-icons|vsc|11.5.0
prettier-config|who|0.2.0
vscode-nginx|wil|0.7.2
terminal-all-in-one|yas|1.11.17
vscode-java-saber|You|0.1.2
material-theme|zhu|3.10.14
html-css-class-completion|Zig|1.20.0

(9 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
