### ISSUE TITLE
Native Notebooks - Outline (aka Table of Contents or TOC) has low discoverability

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#127200]
Customer survey feedback shows that the discoverability of the outline view for notebooks is still low. 

Could we potentially automatically open the outline view when a notebook is opened for the first x (5?) times to help discoverability?

**Comment by claudiaregio** [comment]
https://github.com/microsoft/vscode-jupyter/issues/6650

**Comment by digitarald** [comment]
Related, UI hints/callouts could also help here if we want to actively point users to the Outline. Might make sense in a context for when a user hasn't seen it before and uses a long file with many headers: https://github.com/microsoft/vscode/issues/120147 .

This UI feature is in the backlog, so add your 👍 and thoughts if you think this could help with this and other notebook discovery issues.

**Comment by IanMatthewHuff** [comment]
If we had something like @digitarald  mentioned I could see that working really well for this. Opening it automatically after X times seems dicey to me, at least as my personal dev preferences go. Messing with a users layout just seems wrong. 

We could put a button in the notebook toolbar (like variables) that only shows when there is markdown headers in the file and if the outline view is not visible. Then it could make the outline view visible. Though that does seem like a big ticket item (top level toolbar icon) that's only really valuable for initial discoverability.

**Comment by claudiaregio** [comment]
@IanMatthewHuff related to: https://github.com/microsoft/vscode-jupyter/issues/7305

**Comment by IanMatthewHuff** [comment]
@claudiaregio Ahh nice, you already had the issue. Would you like me to implement it with the "unordered list" icon that Miguel suggested here: https://github.com/microsoft/vscode-codicons/issues/80#issuecomment-908617990 ? I could always implement it then swap the icon later.

**Comment by claudiaregio** [comment]
@IanMatthewHuff Sure! I think that's really close and should get the job done especially with the hover tip

**Comment by Yoyokrazy** [comment]
Closing this as completed, as I'm not sure what more there is to be done here. Right now the outline of the notebook is exposed via the view in the side panel explorer view by default, and there is also a TOC icon in the notebook global toolbar. In addition there are now sticky scroll elements that can be enabled for notebooks, which will give users information on the outline of their notebook, along with the ability to execute cells, and toggle other outline related features.
