### ISSUE TITLE
Editors: revisit need for `populateEditorId` and `doResolveEditor`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127209]
Looking at `doResolveEditor`, I find that part of it's duty should really move into the editor override service, specifically:
* `populateEditorId` is a weird workaround for not being able to do this within the override service
* which is evident by the fact that `conflictingDefaults` needs to be carried over into the `resolveEditorInput` method again

I would try to clean the method up by adding the override specific things into the editor override service. Maybe this becomes easier when the override service doesn't need the editor group as much anymore, not sure. We can also extract that functionality into a reusable method.

Besides, I find methods that mutate the object passed in less than ideal. If any, I would expect `populateEditorId` to be `resolveEditorId` and return the results.

**Comment by lramos15** [comment]
The only way I think we could do this is with something like `IEditorGroup | GroupFactory` and then we pass the `findTargetGroup` in as a callback. Do you think that's a cleaner solution?

**Comment by bpasero** [comment]
@lramos15 I think I can look into moving the logic of resolving a group into the editor group service and then it can be used in those places. Maybe something for debt week.

**Comment by bpasero** [comment]
PR is up to make that method reusable.

**Comment by lramos15** [comment]
Thanks, I'll take a look on Tuesday and start adding the functionality to move it over there. This should also get rid of `populateEditorId` since we can now merge that back into the old method like before
