### ISSUE TITLE
Not able to edit the code

### ISSUE THREAD

**Issue by githubdkg** [microsoft/vscode#127244]
Issue Type: <b>Performance Issue</b>

I have also re-installed VS Code. But encountering same problem. It is not accepting any code to be wriiten from keyboard. Backspace also not working when I want to open already written code file and clear a part of the same.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	  3048	code main
    0	    38	  3208	   utility
    0	   157	  3240	   window (Untitled-1 - Visual Studio Code)
    0	   104	  5624	     extensionHost
    0	    66	  1652	       "C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=5624
    0	    23	  5556	   crashpad-handler
    0	   148	  7208	   gpu-process
    1	    75	 12156	   window (Issue Reporter)
    0	    73	 12408	   shared-process
    0	    58	 11144	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5
material-icon-theme|PKi|4.7.0
java|red|0.79.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vim|vsc|1.21.3

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Backspace`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
