### ISSUE TITLE
Find, Move Cursor on Type should not record each step in jumplist / back history

### ISSUE THREAD

**Issue by sql-koala** [microsoft/vscode#127236]
To Repro/describe the feature, let's have this in an editor,
```
| cursor

fo

foo

fooba

foobar

foobaz
```
Have setting "editor.find.cursorMoveOnType": true,
1. then start Find (Ctrl+F) 
2.  type "foobaz" to navigate there.  Cursor will move 3 intermediate steps.
3.  Now use Go Back (Ctrl+O) to go back to start. This will take 4 steps.

**Feature**: It would be nice, if Go Back was smart to do this as one step, as these intermediate cursor movements are mostly random. As user, each time I type one more char in Find, I am telling: no, this is not yet what I am interested.

Conversly, triggering editor.action.nextMatchFindAction (Ctrl+N) while using Find should be recorded, as it is.

Technically one could describe this as: a push to jump stack caused by "Move Cursor on Type" should replace/merge with the last jump, if it was also caused by "Move Cursor on Type".
This is a pathological showcase of course, but i noticed this recently working with real code.
Feature Move Cursor on Type itself is nice, so i dont want to disable it.

Oh, and thanks for vscode, its quite awesome ;-)

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/20435
