### ISSUE TITLE
[Feature Request]: Command Palette `:` line number shortcut allow relative traversal

### ISSUE THREAD

**Issue by tallguyjenks** [microsoft/vscode#127238]
Ran a search on issues and didn't see anything titled similar to what I was thinking of. 

When using the palette `CTRL + P` and then the line number jump symbol `:` if Im on line 500 but i want to go to line 505 the feature i'd like to see is typing something into the line jump pallete akin to: `:+5` to go 5 lines deeper into the code. a relative jump instead of being forced to hardcode the number i want to traverse to `:505` depending on code lines this is less keystrokes and a similar mental model for vim users too who may use relative line number in VSCode and may want to switch off between vim mode and just using the palette

**Comment by yume-chan** [comment]
#65539
