### ISSUE TITLE
Javascript object method with state change via increment not highlighted

### ISSUE THREAD

**Issue by scottdrichards** [microsoft/vscode#127294]
My understanding is that vscode will highlight object methods that modify the state (`this.x = ...`) different than those that do not. However, the increment operator `++`, decrement operator, `delete` operator, and (I assume) other modifiers that do not use an `=` sign, do not seem to be identified as ones that modify state.
![image](https://user-images.githubusercontent.com/28912482/123597823-d0ff8a00-d7c1-11eb-99c6-0f59b8cd413d.png)

**Comment by yume-chan** [comment]
> My understanding is that vscode will highlight object methods that modify the state

Not exactly. `assignment` has been classified as a class constructor thus the different color.

![image](https://user-images.githubusercontent.com/1330321/123611715-781d0980-d834-11eb-8350-46a43fbc53a9.png)

---

Same as the `a` function in following code:

```js
function a() {
  this.a = 1;
}
function b() {
  return 1
}
```

![image](https://user-images.githubusercontent.com/1330321/123612102-d5b15600-d834-11eb-9770-6e4b5e7dc295.png)

![image](https://user-images.githubusercontent.com/1330321/123611907-a69ae480-d834-11eb-9629-0712528a401d.png)
