### ISSUE TITLE
VScode does not run/load without internet. New window crashes when No connectivity.

### ISSUE THREAD

**Issue by sathish-kumar-s** [Microsoft/vscode#12727]
- VSCode Version: 1.5.3 
- OS Version: Windows-7 Professional

Steps to Reproduce:

1.  Open VScode without Internet connectivity.(No wifi or Lan connectivity). It does not run.
2.  Open VScode, disable lan connectivity. Open new VScode window (Ctrl+shift+N). VScode crashes.
![vscode_crash](https://cloud.githubusercontent.com/assets/13175348/18865914/3f5528b6-84bb-11e6-886c-f16cec662610.jpg)

**Comment by bpasero** [comment]
Please contribute to https://github.com/Microsoft/vscode/issues/7570

**Comment by bpasero** [comment]
Btw worthy to mention that I cannot reproduce this on my Windows 7 with internet connections disabled.
