### ISSUE TITLE
can't go to definition with project opened on network driver

### ISSUE THREAD

**Issue by zobin** [microsoft/vscode#127285]
Issue Type: <b>Bug</b>

1.I used sshfs-win to mount linux file system to driver z:
2.vsc open the project fold z:/home/zobin/test
3.the include file path in "z:/home/zobin/test/include", and set include path
	"C_Cpp.default.includePath": [
			"z:/home/zobin/test/include/**"
		]
4.open source file, F12 can't go to definition.But, F12 works well while i open the fold on local drive like e:, and with the same include path

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.93GB free)|
|Process Argv|--crash-reporter-id 5671e8ce-50a4-4331-a9fe-8fde3415bad6|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
cpptools|ms-|1.5.0-insiders2
vscode-icons|vsc|11.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510
vsccppwtct:30329789

```

</details>

**Comment by aeschli** [comment]
Can you file this against the cpp extension? https://github.com/Microsoft/vscode-cpptools.
Thanks!
