### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by 1774298958** [microsoft/vscode#127242]
Terminal console, Chinese garbled problem

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
