### ISSUE TITLE
unable to detect shell in vscode when launched by icon in fedora LINUX

### ISSUE THREAD

**Issue by Aerma7309** [microsoft/vscode#127241]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. install fedora linux 34
2. install vscode
3. open vscode from icon in app drawer
4. BOOM vscode is now stuck in finding shell you use
![Screenshot from 2021-06-27 11-26-24](https://user-images.githubusercontent.com/47671638/123534398-93a3e980-d73a-11eb-9bf5-0b94e86ba5e3.png)

Step to Solve the error:
1. every time we update the code.desktop file is overwritten by this data  below:
2. 

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --no-sandbox --unity-launch %F
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --no-sandbox --new-window %F
Icon=com.visualstudio.code

3. here executable path is set as Exec=/usr/share/code/code the problem is with this variable it opens the code but does not finds the shell 
4. if i change Exec=/usr/share/code/bin/code the vscode works perfectly as this executable is shell script that finds the shell and opens code with that
5. whenever i update i have to do these steps manually i thought that it will be corrected in updated versions but no luck so i created this bug report
6. Thats all from my side hoping it will be fixed in next update.
7. HAVE A NICE DAY, HAPPY CODING

**Comment by Tyriar** [comment]
When you login to your system your `.profile` script should run that may set up your shell, also you can use `chsh` to set up `$SHELL` correctly. If these are done in your shell rc file then it may not work.

Do you have any errors in your devtools console? (Help > Toggle Developer Tools)

**Comment by Aerma7309** [comment]
default shell on fedora is bash and i havent any other shell installed also the $SHELL var is set to /bin/bash confirmed after echoing it.
![Screenshot from 2021-06-28 20-41-10](https://user-images.githubusercontent.com/47671638/123660341-33ec3200-d851-11eb-9c25-3bf4394ccd92.png)

**Comment by Tyriar** [comment]
Could you do a trace log to see how the terminal is being launched? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

This will tell us whether it's trying to run bash or something else.

**Comment by Aerma7309** [comment]
/usr/share/code/code --log trace
[main 2021-07-07T04:57:36.906Z] Starting VS Code
[main 2021-07-07T04:57:36.907Z] from: /usr/share/code/resources/app
[main 2021-07-07T04:57:36.908Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: false,
  log: 'trace',
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'ddd91704-5c7d-4ed6-9115-80885d6bcac8',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/abhimanyu/.config/Code/logs/20210707T102736'
}
[main 2021-07-07T04:57:36.909Z] Deleting Chrome cached data path: /home/abhimanyu/.config/Code/Code Cache
[main 2021-07-07T04:57:36.912Z] Resolving machine identifier...
[main 2021-07-07T04:57:36.912Z] Resolved machine identifier: 271487f64dc0e3a8a9bfd901235fd3f871f8a06e576b1018c0af625110f3dfb0
[main 2021-07-07T04:57:36.917Z] Main->SharedProcess#connect
[main 2021-07-07T04:57:36.940Z] StorageMainService: creating global storage
[main 2021-07-07T04:57:36.940Z] lifecycle (main): phase changed (value: 2)
[main 2021-07-07T04:57:36.940Z] windowsManager#open
[main 2021-07-07T04:57:36.940Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '20385a2e56c22139c8999ecb0d050a6b', uri: [m] },
    exists: true
  }
]
[main 2021-07-07T04:57:36.941Z] IPC Object URL: Registered new channel vscode:b2f0f2af-8caa-4c9e-a5e4-b7347a51e7be.
[main 2021-07-07T04:57:36.941Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 164, y: 28, width: 1040, height: 864 }
[main 2021-07-07T04:57:36.942Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1536, height: 864 }
[main 2021-07-07T04:57:36.942Z] window#ctor: using window state { mode: 0, x: 164, y: 28, width: 1040, height: 864 }
[main 2021-07-07T04:57:36.942Z] window#ctor: vscode-file:// protocol is explicitly disabled
[main 2021-07-07T04:57:36.985Z] StorageMainService: creating workspace storage (20385a2e56c22139c8999ecb0d050a6b)
[main 2021-07-07T04:57:36.985Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2021-07-07T04:57:36.987Z] lifecycle (main): phase changed (value: 3)
[main 2021-07-07T04:57:36.988Z] update#setState idle
[main 2021-07-07T04:57:36.988Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-07-07T04:57:36.988Z] getUnixShellEnvironment#runAsNode undefined
[main 2021-07-07T04:57:36.988Z] getUnixShellEnvironment#noAttach undefined
[main 2021-07-07T04:57:36.989Z] getUnixShellEnvironment#env {
  SHELL: '/bin/bash',
  LSCOLORS: 'Gxfxcxdxdxegedabagacad',
  SESSION_MANAGER: 'local/unix:@/tmp/.ICE-unix/4090,unix/unix:/tmp/.ICE-unix/4090',
  COLORTERM: 'truecolor',
  LESS: '-R',
  HISTCONTROL: 'erasedups:ignoreboth',
  XDG_MENU_PREFIX: 'gnome-',
  HISTSIZE: '500000',
  HOSTNAME: 'fedora',
  SSH_AUTH_SOCK: '/run/user/1000/keyring/ssh',
  XMODIFIERS: '@im=ibus',
  DESKTOP_SESSION: 'gnome-xorg',
  SSH_AGENT_PID: '3953',
  OSH: '/home/abhimanyu/.oh-my-bash',
  EDITOR: '/usr/bin/nano',
  PWD: '/home/abhimanyu',
  LOGNAME: 'abhimanyu',
  XDG_SESSION_DESKTOP: 'gnome-xorg',
  XDG_SESSION_TYPE: 'x11',
  SYSTEMD_EXEC_PID: '4115',
  XAUTHORITY: '/run/user/1000/gdm/Xauthority',
  WINDOWPATH: '2',
  GDM_LANG: 'en_IN.UTF-8',
  HOME: '/home/abhimanyu',
  USERNAME: 'abhimanyu',
  LANG: 'en_IN.UTF-8',
  LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
  XDG_CURRENT_DESKTOP: 'GNOME',
  VTE_VERSION: '6402',
  GNOME_TERMINAL_SCREEN: '/org/gnome/Terminal/screen/daf389d8_aab8_4896_aa2e_a1581947d2f1',
  COMP_WORDBREAKS: ` \t\n"'><=;|&(`,
  MOZ_GMP_PATH: '/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed',
  XDG_SESSION_CLASS: 'user',
  TERM: 'xterm-256color',
  LESSOPEN: '||/usr/bin/lesspipe.sh %s',
  USER: 'abhimanyu',
  GNOME_TERMINAL_SERVICE: ':1.165',
  DISPLAY: ':0',
  SHLVL: '1',
  PAGER: 'less',
  QT_IM_MODULE: 'ibus',
  LC_CTYPE: 'en_IN.UTF-8',
  XDG_RUNTIME_DIR: '/run/user/1000',
  which_declare: 'declare -f',
  XDG_DATA_DIRS: '/home/abhimanyu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/',
  PATH: '/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/abhimanyu/Dropbox/bin:/home/abhimanyu/platform-tools:/home/abhimanyu/bin',
  HISTIGNORE: '&:[ ]*:exit:ls:bg:fg:history:clear',
  GDMSESSION: 'gnome-xorg',
  DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus',
  MAIL: '/var/spool/mail/abhimanyu',
  _: '/usr/share/code/code',
  CHROME_DESKTOP: 'code-url-handler.desktop',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'GNOME',
  VSCODE_CWD: '/home/abhimanyu',
  GDK_BACKEND: 'x11',
  NO_AT_BRIDGE: '1',
  VSCODE_NLS_CONFIG: '{"locale":"en-gb","availableLanguages":{},"_languagePackSupport":true}',
  VSCODE_NODE_CACHED_DATA_DIR: '/home/abhimanyu/.config/Code/CachedData/507ce72a4466fbb27b715c3722558bb15afa9f48',
  VSCODE_IPC_HOOK: '/run/user/1000/vscode-8f1af129-1.57.1-main.sock',
  VSCODE_PID: '273670',
  ELECTRON_RUN_AS_NODE: '1',
  ELECTRON_NO_ATTACH_CONSOLE: '1'
}
[main 2021-07-07T04:57:36.990Z] getUnixShellEnvironment#shell /bin/bash
[main 2021-07-07T04:57:36.990Z] getUnixShellEnvironment#spawn ["-ilc"] '/usr/share/code/code' -p '"63cb6c74455a" + JSON.stringify(process.env) + "63cb6c74455a"'
[main 2021-07-07T04:57:37.119Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-07-07T04:57:38.038Z] menubarService#updateMenubar 1
[main 2021-07-07T04:57:38.047Z] menubarService#updateMenubar 1
[main 2021-07-07T04:57:38.233Z] SharedProcess: on vscode:createSharedProcessMessageChannel
[main 2021-07-07T04:57:38.233Z] IPC Object URL: Registered new channel vscode:3e582b82-c690-4f25-b9dd-3e068e2634fb.
[main 2021-07-07T04:57:38.329Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-07-07T04:57:38.352Z] menubarService#updateMenubar 1
[main 2021-07-07T04:57:38.459Z] SharedProcess: IPC ready
[main 2021-07-07T04:57:38.462Z] Main->SharedProcess#connect: connection established
[main 2021-07-07T04:57:38.482Z] SharedProcess: Overall ready
[main 2021-07-07T04:57:38.625Z] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/stable/507ce72a4466fbb27b715c3722558bb15afa9f48
[main 2021-07-07T04:57:38.625Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-07-07T04:57:38.956Z] menubarService#updateMenubar 1
[main 2021-07-07T04:57:39.435Z] menubarService#updateMenubar 1
[main 2021-07-07T04:57:46.988Z] Resolving your shell environment is taking more than 10s. Please review your shell configuration. Learn more at https://go.microsoft.com/fwlink/?linkid=2149667.
[main 2021-07-07T04:57:57.616Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:06.988Z] update#checkForUpdates, state =  idle
[main 2021-07-07T04:58:06.989Z] update#setState checking for updates
[main 2021-07-07T04:58:06.989Z] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/stable/507ce72a4466fbb27b715c3722558bb15afa9f48
[main 2021-07-07T04:58:06.989Z] resolveShellEnv(): running (macOS/Linux)
[main 2021-07-07T04:58:15.894Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:49.806Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:50.043Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:51.174Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:57.640Z] menubarService#updateMenubar 1
[main 2021-07-07T04:58:59.659Z] Lifecycle#window.on('close') - window ID 1
[main 2021-07-07T04:58:59.659Z] Lifecycle#unload() - window ID 1
[main 2021-07-07T04:58:59.662Z] Lifecycle#unload() - no veto (window ID 1)
[main 2021-07-07T04:58:59.739Z] StorageMainService: closed workspace storage (20385a2e56c22139c8999ecb0d050a6b)
[main 2021-07-07T04:58:59.741Z] Lifecycle#onBeforeCloseWindow.fire() - window ID 1
[main 2021-07-07T04:58:59.743Z] IPC Object URL: Removed channel vscode:b2f0f2af-8caa-4c9e-a5e4-b7347a51e7be.
[main 2021-07-07T04:58:59.744Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-07-07T04:58:59.744Z] Lifecycle#onWillShutdown.fire()
[main 2021-07-07T04:58:59.745Z] IPC Object URL: Removed channel vscode:3e582b82-c690-4f25-b9dd-3e068e2634fb.
[main 2021-07-07T04:58:59.749Z] Lifecycle#app.on(window-all-closed)
[main 2021-07-07T04:58:59.749Z] Lifecycle#app.on(before-quit)
[main 2021-07-07T04:58:59.750Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-07-07T04:58:59.750Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: 'file:///home/abhimanyu/Dropbox/LeetCode',
    backupPath: '/home/abhimanyu/.config/Code/Backups/ff9a73437a355f1eb9837aa91c8a5ae7',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 0,
      x: 164,
      y: 28,
      width: 1040,
      height: 864
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-07-07T04:58:59.751Z] Lifecycle#app.on(will-quit)
[main 2021-07-07T04:58:59.754Z] StorageMainService: closed global storage

**Comment by Aerma7309** [comment]
from the above log it is obvious that vscode is able to get the shell environment 
ref:=
[main 2021-07-07T04:57:36.990Z] getUnixShellEnvironment#shell /bin/bash

but it is not openning the terminal with the shell found above and taking unlimited time 
ref:=
[main 2021-07-07T04:57:46.988Z] Resolving your shell environment is taking more than 10s. Please review your shell configuration. Learn more at https://go.microsoft.com/fwlink/?linkid=2149667.

**Comment by Tyriar** [comment]
@Aerma7309 when you do a trace log you can toggle the shared process via the command palette to get what environment the process actually gets spawned with:

![image](https://user-images.githubusercontent.com/2193314/124924932-cd81b500-dfb0-11eb-82af-f7bc41d98de0.png)

![image](https://user-images.githubusercontent.com/2193314/124924886-c0fd5c80-dfb0-11eb-9b7e-61ecf1756e3a.png)

Can you verify whether `env` there is empty or nearly empty? I'm guessing you need to look into your shell launch scripts not ending (do you launch tmux or something there? Is it idempotent?), but maybe we can handle this better with a little more information.

**Comment by Aerma7309** [comment]
unable to get what you want closing this because it seems nothing is going to happen.
