### ISSUE TITLE
Styles are sometimes / inconsistently copied to rich text editors

### ISSUE THREAD

**Issue by justingolden21** [microsoft/vscode#127246]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Chrome OS 91.0.4472.102 (Official Build) (64-bit)

Steps to Reproduce:

1. enter text in an unsaved file, then copy it to a rich text editor such as google docs
2. the pasted text will not be formatted with syntax highlighting
3. try the same with a file such as test.js, test.html, etc.
4. the pasted text *will* be formatted correctly
5. try the same with an unknown file format such as .postcssrc, or a text format such as .txt
6. the pasted text *will not* be formatted correctly

I'm guessing someone will tell me this is intentional behavior, but is it really intentional to only copy styles from some files and not others? Is there a setting for this? Should this really be the default behavior if it is changeable? In my opinion, the intended behavior would be to copy with formatting every time. Secondarily, it would be to copy every time except with .txt files or unsaved files without an extension. But as an IDE, VS code should assume the file extension if not known, is for code and should therefore copy to clipboard with syntax highlighting.

Obviously this is a very, very minor bug, but I figured it was worth mentioning, every little thing to help :) (love VS code btw)

Priority for this should be the lowest possible priority.

**Comment by IllusionMH** [comment]
Do you change language mode for Untitled files? I think you have it as Plain Text, and therefore no highlight copied. Same for unknown files

**Comment by justingolden21** [comment]
I haven't changed any of those settings.

I was just saying whether or not it's intended, I would suggest making the default behavior to be consistent with all file types, text or code. I doubt that the majority of users would prefer it to copy only known code files with rich text styles, but not other files.

Just my two cents.

**Comment by rebornix** [comment]
@justingolden21 it would be helpful if you can share snippets to help troubleshoot.

**Comment by justingolden21** [comment]
@rebornix sure:

This code does not have syntax highlighting when copied:

netlify.toml
```toml
[build]
	publish = "dist/"
	command = "npm run prod"
```
This code has syntax highlighting when copied:

index.html
```html
   <body class="text-center m-4 text-gray-900">
```

When pasted into google docs:
![image](https://user-images.githubusercontent.com/30274440/124072705-d258ce80-d9dc-11eb-9545-186636d7ba03.png)

**Comment by IllusionMH** [comment]
Do you have **Text Plain** Language mode in status bar for toml files?
![image](https://user-images.githubusercontent.com/1312662/124091767-d4637180-da5e-11eb-95e2-aef65027a4ec.png)
