### ISSUE TITLE
[less] "} expected" error with ">" in selector within @media query

### ISSUE THREAD

**Issue by qbasic16** [Microsoft/vscode#12720]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Pro x64

The problem is if you have a media query with containing selector with ">" at the beginning, the LESS linting will show the error "} expected".
It doesn't matter if the "> ..." selector is at the beginning of the media block or somewhere else as long as it's a direct child of the media query it will always show the error.
This is only a problem with a @media surrounding it.

The whole LESS file will transpile to CSS without any problems, but it's a bit strange that it shows this error.

Steps to Reproduce:
1. insert this code into a .less file

``` Less
@media (min-width:@min-width-mobile) {
    > div {
        bottom: 1.1em;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/13191383/18864545/26e30f56-8497-11e6-9a65-09409a5787b5.png)

So I guess LESS linting is just not recognizing the ">" part of the selector when in a @media block.

**Comment by qbasic16** [comment]
I just forked [vscode-css-languageservice](https://github.com/Microsoft/vscode-css-languageservice) and will try to find out more about the parsing.
If I'm right, the parsing happens in _lessParser.ts_.
I'll try some stuff out and if it works I will submit it.
```TypeScript
	public _tryParseMixinReference(atRoot = false): nodes.Node {
		...
		if (!this.hasWhitespace() && this.accept(TokenType.ParenthesisL)) {
			this.accept(TokenType.Delim, '>');
			if (node.getArguments().addChild(this._parseMixinArgument())) {
				while (this.accept(TokenType.Comma) || this.accept(TokenType.SemiColon)) {
					if (this.peek(TokenType.ParenthesisR)) {
						break;
					}
					if (!node.getArguments().addChild(this._parseMixinArgument())) {
						return this.finish(node, ParseError.ExpressionExpected);
					}
				}
			}
			if (!this.accept(TokenType.ParenthesisR)) {
				return this.finish(node, ParseError.RightParenthesisExpected);
			}
			identifier.referenceTypes = [nodes.ReferenceType.Mixin];
		} else {
			identifier.referenceTypes = [nodes.ReferenceType.Mixin, nodes.ReferenceType.Rule];
		}
		...
	}
```
Greetings 😉

**Comment by aeschli** [comment]
Are you sure this is valid LESS code? I see that LESS doesn't complain and transpiles this but the result is not valid CSS3.
Do you have any pointers to some examples or more documentation?
