### ISSUE TITLE
code . command has a bug

### ISSUE THREAD

**Issue by huangguanbin** [microsoft/vscode#127291]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1(user setup)
- OS Version: Windows_NT x64 10.0.1.19041

Steps to Reproduce:

Your friend and you share a remote machine and a same docker container. Both of you are online.

1. You cd to some dir which you want to be your working space, and you type in code .
2.  Not only you but also your friend's vsocde pop out your wokring space, which is annoying. Because this will bother other user to use vscode.

**Comment by bpasero** [comment]
Is this using any of the remote extensions from VSCode?

**Comment by aeschli** [comment]
Are you running `code .` in the integrated terminal or a remote window?
Maybe it is a duplicate of https://github.com/microsoft/vscode/issues/121926
