### ISSUE TITLE
In Zen Mode, Add Flag to only show active pane and hide inactive panes

### ISSUE THREAD

**Issue by sahil48** [microsoft/vscode#127231]
When using Zenmode, when I have split the editor into multiple panes (some files on the left half and some in the right half of the window), I would like to be able to only show the active document in the active pane in Zenmode. For me, that is truely a distraction free writing experience.

For reference, Zen Mode Documentation is here: https://code.visualstudio.com/docs/getstarted/userinterface#_zen-mode

**Comment by sahil48** [comment]
This is not a duplicate of the experimental duplicate detection issue. That you for the suggestion bot! 😄

**Comment by isidorn** [comment]
So you would like to also hide the non active editor groups. This is a fair feature request, however not currently on the plan -> backlog

**Comment by sahil48** [comment]
Thanks for tagging it. That's what I am looking for.
