### ISSUE TITLE
Plugin Grouping Manage 

### ISSUE THREAD

**Issue by au-top** [microsoft/vscode#127205]
I have a lot of plug-ins and will add them in the future,

I also have a lot of projects and use a lot of different languages

I don't want to start CPP / py / dart / flutter / db / SSH or other plug-ins when I write Vue. All of these make my vscode slow, and I have many projects. Setting up workspace for each project will waste a lot of time

I want to have a plug-in group management function

For example, I can group plugins and choose to load the specified groups

And multiple groups can be enabled at the same time

**Comment by au-top** [comment]
> /duplicate

Can I specify the duplicate issue?

**Comment by sandy081** [comment]
Please search issues labelled with extensions

**Comment by au-top** [comment]
thanks 
mention  https://github.com/microsoft/vscode/issues/40239
