### ISSUE TITLE
Debug Bug Report

### ISSUE THREAD

**Issue by matt123491** [microsoft/vscode#127277]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.57.1
- OS Version: Windows 10 10.0.19043 Build 19043

When I start the debug I see the code instead of the website.
![Help](https://user-images.githubusercontent.com/40703994/123564006-81db3a00-d76c-11eb-8060-05434e3a2c32.PNG)

**Comment by weinand** [comment]
What language are you debugging?
How do you start debugging?
