### ISSUE TITLE
multiple debuggers can be registered with the same type

### ISSUE THREAD

**Issue by zt1106** [microsoft/vscode#127283]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Windows

Description:
In Extension API doc, above the function  registerDebugAdapterDescriptorFactory(), It says that "Registering more than one DebugAdapterDescriptorFactory for a debug type results in an error." But that error doesn't pop up when two debugger with same type are registered.

Steps to Reproduce:

1. install any debugger extension (like cpptools)
2. package and install my own debugger extension with same type "cppdbg" (if my own extension is launched directly, that error will pop up correctly, the only way to reproduce is to install from .vsix)
3. two extensions are both activated successfully without error
4. when launch a debug with type "cppdbg", the actual debugger used is my own extension

Expectation:
No matter what circumstance, that error should pop up. Right now we have two extensions with same debug type, and we rely on this mechanism to force our custumers to migrate from the old one to the new one. Without this error, our custumers would install both extensions and only the old one would be used.

**Comment by isidorn** [comment]
There seems to be code that is handling this here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostDebugService.ts#L335

For now leaving this up to @weinand since he added that code.
Feel free to assign back to me if you would like me to investigate more.

**Comment by isidorn** [comment]
Moving out to backlog since we do not plan to tackle this in Endgame.
