### ISSUE TITLE
Visual studio code open 2 windows 

### ISSUE THREAD

**Issue by santhoshunt** [microsoft/vscode#127243]
Issue Type: <b>Bug</b>

While opening visual studio code using command line / via file manager , It opens two windows one with the directory I opened and another window on root directory of my computer. The issue continues even when I open empty folders with vs code

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (5.11GB free)|
|Process Argv|D:\\github\\WEB development\\scss\\sass-playlist-master --crash-reporter-id c1f1ffe6-aa24-46bb-99a0-c9bb5a1cbaba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
xd|ado|1.2.3
vscode-css-formatter|aes|1.0.1
vscode-django|bat|1.6.0
vscode-intelephense-client|bme|1.7.1
exe-runner|bra|0.1.0
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.0.1
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
csharp-format-usings|gao|0.0.4
ftp-simple|hum|0.7.6
pubspec-assist|jer|2.2.1
solidity|Jua|0.0.122
vscode-gutter-preview|kis|0.27.1
vscode-phpfmt|kok|1.0.30
vscode-language-babel|mgm|0.0.31
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5
cpptools|ms-|1.5.0-insiders2
vscode-typescript-next|ms-|4.4.20210626
vsliveshare|ms-|1.0.4419
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
java|red|0.79.2
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510
vsccppwtct:30329789

```

</details>

![image](https://user-images.githubusercontent.com/50547679/123535827-285f1500-d744-11eb-8604-9d60e6b3e9ce.png)
![image](https://user-images.githubusercontent.com/50547679/123535840-4462b680-d744-11eb-8a6a-b1c3958ae864.png)

**Comment by santhoshunt** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [opening directory in vscode using "code ." from terminal opens root directory (#124223)](https://www.github.com/microsoft/vscode/issues/124223)

Nope this is not the same issue

**Comment by peterbud** [comment]
I have similar experience, and I have a hunch it might to do something with the given settings, in my case VS Code starts now in 3(!) separate instances.

Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by santhoshunt** [comment]
Yeah it works, Thanks
