### ISSUE TITLE
Attempting to delete multiple files in VS Code Explorer after deselecting a single file from them deletes the file

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#127219]
Issue Type: <b>Bug</b>

1. Select all files in VS Code Explorer by using Ctrl + A shortcut.
2. Click with mouse while holding Ctrl button to deselect one of the already selected files.
3. Press "Del" button to delete just the selected/unneded files while leaving the single file you deselected intact.

What happens:
Instead of the selected files being deleted, the file that you just deselected gets deleted.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.11.0-18-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.40GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --unity-launch --crash-reporter-id 9cc3662d-ccfb-4569-83fb-26560f111f8b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
laravel-extra-intellisense|ami|0.6.1
html-class-suggestions|And|1.1.1
vscode-intelephense-client|bme|1.7.1
path-intellisense|chr|2.3.0
vs-code-semicolon-insertion|chr|0.0.6
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|7.1.1
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.2
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.27.1
vscode-jumpy|krn|1.0.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.12.0
vscode-versionlens|pfl|1.0.9
LiveServer|rit|5.6.1
bash-debug|rog|0.3.9
laravel-artisan|rya|0.0.28
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
indenticator|Sir|0.7.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.5.0
local-history|xyz|1.8.1
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510
vsccppwtct:30329789

```

</details>

**Comment by mystiquewolf** [comment]
The mentioned duplicate bug has been closed incorrectly. I am pretty much able to delete multiple (selected) files, like it can be seen from the screenshot. Also, i am not on Insider 1.57 but on stable 1.56.

![vs code delete](https://user-images.githubusercontent.com/16529989/123512628-2b4cfd80-d691-11eb-91d2-9d5cf41cd99d.png)

**Comment by mystiquewolf** [comment]
To be even more precise - my issue IS NOT the following:

1. I select multiple files
2. I press Del
3. One file gets deleted
4. I am asked to delete each of the remaining files

My issue IS THE FOLLOWING:

1. I select all files
2. I deselect one of them
3. I press Del key
4. I am incorrectly asked if i want to delete the file i just deselected. The reason i deselected it was that i did not want to delete it along with the other files which were selected for deletion.

**Comment by mystiquewolf** [comment]
@isidorn Could you please mention the id of the duplicated issue so i can follow up? Thanks!

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/108885
