### ISSUE TITLE
Override the setting for Simple File-Dialogs

### ISSUE THREAD

**Issue by igorskyflyer** [microsoft/vscode#127201]
Hello, I've created an extension that uses the ```vscode.window.showSaveDialog``` function and [it] would really benefit the ability to ignore the global ```files.simpleDialog.enable``` setting and always use built-in Simple Dialogs and not use the OS/native Save Dialogs. Is it possible to override this behavior when calling```vscode.window.showSaveDialog```?
If not, are there any plans for such feature?

**Comment by alexr00** [comment]
The user made the choice to set `files.simpleDialog.enable`, so if we provided a way way for extensions to choose which file picker to show then we would be ignoring an explicit user choice. It is intentional that we stick to the user's chosen setting here!

**Comment by igorskyflyer** [comment]
Got it, I guess I'll resort to making my own UI for the folder dialog. 👍

**Comment by alexr00** [comment]
@igorskyflyer if there is something that the simple file picker is missing and that you think would have broad usefulness you can also open an issue with a feature request for us to consider.
