### ISSUE TITLE
Tests should ensure that Disposables/Event subscriptions are disposed properly

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127250]
Forgetting to dispose disposables (most importantly those returned when registering an event listener) seems to be a common problem:

* Inline Suggestion Provider is called multiple times when switching active editor (fixed by https://github.com/microsoft/vscode/commit/f9f0798c530c0caf0d98e6398a04c61ae38ddb48)
* CodeRendererContrib leaks editors & models #123667 (fixed by https://github.com/microsoft/vscode/commit/64e707842e612b18edb346a676808bad614c30ce)
* Listener leak in Ports view https://github.com/microsoft/vscode/issues/118544 (fixed by https://github.com/microsoft/vscode/commit/b2e10eb61799f9d63e9a5e3a77dd26f5544d5337)
* FoldingController leaks local disposables https://github.com/microsoft/vscode/issues/117687 (fixed by https://github.com/microsoft/vscode/commit/ebdf30f0887f5923aa03e626d4a6072fd30883f3)
* IMenu must be disposed after use https://github.com/microsoft/vscode/issues/126365
* Inline Suggestion Items are sometimes not disposed https://github.com/microsoft/vscode/commit/4132f13058fca1389a6c14c4385fdcb451108c1f#diff-27c94c02d2dd78955f1df3ed059f7a419b5305575c9b93227b0559af51f662dcR373

It is very easy to forget calling dispose on cleanup:
* You must be aware that the object you obtained is now in your ownership
* You must be aware that the object needs to be disposed
* Sometimes, it is not possible to ensure that an object will be diposed on construction through some `this.registerDisposable(new MyDisposableModel())` call (in particular when the lifetime is not a simple composition like here https://github.com/microsoft/vscode/commit/4132f13058fca1389a6c14c4385fdcb451108c1f#diff-27c94c02d2dd78955f1df3ed059f7a419b5305575c9b93227b0559af51f662dcR373)

Unfortunately, leaking disposables usually aren't discovered in smoke tests, as they don't cause an immediatly visible effect. After longer usage they can severly impact performance though.

## Suggestion: Tests should ensure that all created Disposable's are disposed

I suggest to improve the Disposable/Event subscription infrastructure so that tests can ensure that all disposables are cleaned up.

Some `ensureNoDisposablesAreLeaked` method could be of great help to write such tests:

```ts
async function ensureNoDisposablesAreLeakedAsync(fn: () => Promise<void>): Promise<void> {
	const tracker = new DisposableTracker();
	setDisposableTracker(tracker);
	const r = await fn();
	if (tracker.allDisposables.size > 0) {
		throw new Error(`These disposables were not disposed: ${[...tracker.allDisposables.values()].join(', ')}`);
	}
	return r;
}
```

With the actual test looking like this:
```ts
test("Test Inline Completions", async () => {
    await ensureNoDisposablesAreLeaked(async () => {
        await withAsyncTestCodeEditor(text, options, async (editor, editorViewModel, instantiationService) => {
            const model = new InlineCompletionsModel(editor);
            // ...
            model.dispose();
        });
    });
    // `ensureNoDisposablesAreLeaked` makes sure all resources allocated by `new InlineCompletionsModel` are disposed
});
```

Unfortunately, event subscriptions are not tracked by the disposable tracker currently.
I suggest to use `markTracked`/`trackDisposable` for tracking event subscriptions too.

What are your thoughts? Would this efficiently prevent this kind of bug? With proper test coverage, it would have spotted all the places where I forgot to call `dispose`.
@alexdima @jrieken @joaomoreno @alexr00 @mjbvz (pinging you since you were involved in some leaking disposable discussions/PRs 😉)

**Comment by jrieken** [comment]
Maybe a use-case for decorator. I am not a fan of the looks for the extra nesting. 

```ts
@assertNoLeaks
test("Test Inline Completions", async () => {
    await withAsyncTestCodeEditor(text, options, async (editor, editorViewModel, instantiationService) => {
        const model = new InlineCompletionsModel(editor);
        // ...
        model.dispose();
    });
});
```

**Comment by hediet** [comment]
> I am not a fan of the looks for the extra nesting.

Me neither, but I would put it in my `withInlineCompletionsModel` helper anyway.

> Maybe a use-case for decorator

Afaik you can only apply decorators to classes and methods of classes...

**Comment by hediet** [comment]
I came up with this which I like quite much:

```ts
suite('My Suite', () => {
    // Call this helper to ensure that all disposables are disposed after every test in this suite.
    // Internally, setup and teardown are used.
    ensureNoDisposablesAreLeakedInTestSuite();

    test('My Test 1 (succeeds)', () => {
        // This test succeeds, since all disposables are disposed.
        toDisposable(() => { }).dispose();
    });

    test('My Test 2 (fails)', () => {
        // This test fails, as the following disposable leaks.
        toDisposable(() => { });
    });
});
```
