### ISSUE TITLE
VSCode has trouble rendering unicode combining character on macOS

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode#127270]
Issue Type: <b>Bug</b>

I have code that looks like the following:

```julia
struct ∂⃖rrule{N}; end
struct ∂⃖recurse{N}; end
```

This fails to render properly in VSCode on macOS:

![Screen Shot 2021-06-27 at 3 35 41 PM](https://user-images.githubusercontent.com/1291671/123557347-7719a880-d75e-11eb-8c2b-1a0ef1e1182f.png)

However, it renders fine in VSCode on Linux, as well as most other applications on macOS:

Sublime Text:
![Screen Shot 2021-06-27 at 3 35 48 PM](https://user-images.githubusercontent.com/1291671/123557352-7b45c600-d75e-11eb-8e9b-832f8098e0fc.png)

iTerm2:
![Screen Shot 2021-06-27 at 3 36 21 PM](https://user-images.githubusercontent.com/1291671/123557361-86005b00-d75e-11eb-9a3a-ca204fb0fa87.png)

Safari:
![Screen Shot 2021-06-27 at 3 39 54 PM](https://user-images.githubusercontent.com/1291671/123557364-8b5da580-d75e-11eb-9210-6b259c8ee37b.png) 

VS Code version: Code - Insiders 1.58.0-insider (Universal) (49e1f9919880c1c96004f9b6ad91bcee7a94a1bd, 2021-06-25T05:14:06.587Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-42-generic
Remote OS version: Linux x64 5.4.0-42-generic
Remote OS version: Linux x64 5.4.0-42-generic
Remote OS version: Linux x64 5.4.0-42-generic
Remote OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 834c4ccc-3f7e-48c3-9194-d82f695b059e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: [redacted]|
|OS|Linux x64 5.4.0-42-generic|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (40 x 799)|
|Memory (System)|376.59GB (211.48GB free)|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh-edit-nightly|ms-|2021.5.29700
remote-ssh-nightly|ms-|2021.5.29700
toggle-excluded-files|eam|1.7.0
go|gol|0.26.0
juliahub|Jul|0.3.6
language-julia|jul|1.2.5
cpptools|ms-|1.5.0-insiders2
sublime-keybindings|ms-|4.0.9
vscode-scheme|sjh|0.4.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692

```

</details>

**Comment by backermanbd** [comment]
@Keno you are right
also vscode integrated terminal doesn't render unicode character correctly
I faced this issue in windows

**Comment by alexdima** [comment]
@Keno The VS Code editor delegates all font rendering to the underlying browser engine, i.e. Chromium. I have created a test page at https://jsfiddle.net/y843pavc/ and can confirm that Chromium is not rendering that the same way as Safari:

#### Safari
![image](https://user-images.githubusercontent.com/5047891/123817754-b7ad2980-d8f8-11eb-801e-4a09fb784901.png)

#### Chrome
![image](https://user-images.githubusercontent.com/5047891/123817796-bf6cce00-d8f8-11eb-84ef-2ff098e85409.png)

#### Firefox
![image](https://user-images.githubusercontent.com/5047891/123817956-e0cdba00-d8f8-11eb-861f-13da00eb9032.png)


Could you please create an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

**Comment by Keno** [comment]
Confirmed that the same issue exists in Chrome. Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=1225037.

**Comment by Keno** [comment]
The upstream issue was WONTFIXED for being a font coverage issue. Given that this works elsewhere on macOS though, can VSCode ship a font that has this fixed?

**Comment by alexdima** [comment]
@Keno Thank you for following up. The workaround is to explicitly define the font family fallbacks i.e. configure:
```
"editor.fontFamily": "Monaco, StixGeneral",
```
