### ISSUE TITLE
Workspace trust: provide an option to restrict by default and don't prompt that often

### ISSUE THREAD

**Issue by yw662** [microsoft/vscode#127218]
type: feature request

I like the idea of restricted mode, but it sometimes prompts too much when working with untrusted workspaces.
<del>It would be great if there is an option for "restrict by default unless trusted", so that it won't prompt that often.</del>
Sorry I didn't find it at that time, it is at `security.workspace.trust.startupPrompt`.

and maybe also a list for "untrusted folders & workspaces" so that vscode can just go restricted without asking.

**Comment by yw662** [comment]
No it is not covered.

**Comment by yw662** [comment]
Like we can set ~/Downloads, or /mnt, or /media as untrusted, so that vscode will gladly go restricted without ask.

**Comment by sbatten** [comment]
I think your feature request is covered with the setting you discovered plus https://github.com/microsoft/vscode/issues/126311
