### ISSUE TITLE
Extension doesn't show in preferences after switching workspace trust (?)

### ISSUE THREAD

**Issue by cceckman** [microsoft/vscode#127266]
Issue Type: <b>Bug</b>

I haven't explicitly repro'd this, but noticed something a little weird that might be a bug.

- Opened a workspace
- Initially selected "don't trust this workspace"
  - Rust extension is disabled in this mode
- Later enabled trust for the workspace
  - Rust extension is enabled; started showing some compile errors, etc.
- Wanted to change a Clippy stting; opened Preferences tab; searched for "Rust", "clippy", "rls"
  - Got no results.
  - Used tree view to expand "extensions"; didn't see one for Rust.
- Ctrl+Shift+P, reloaded window
- Searched again
  - Rust preferences were available

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (22.26GB free)|
|Process Argv|--crash-reporter-id 7332d1a3-5c43-4619-9e22-13ef15a54134|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3600)|
|Memory (System)|25.01GB (22.46GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
vim|vsc|1.21.3
linkerscript|Zix|1.0.2
vscode-bazel|Baz|0.4.1
prettier-vscode|esb|8.0.1
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
cpptools|ms-|1.4.1
rust|rus|0.7.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by sbatten** [comment]
I tried to repro with the following steps:
1. Install Rust Extension
2. Open untrusted repo
3. Search for rust settings (verify it is disabled and no settings appear)
4. Trust repo
5. Check settings again. in my case rust settings are present

Anything I am missing?

**Comment by sbatten** [comment]
@sandy081 should we show settings for disabled extensions that are only disabled via trust?

**Comment by sandy081** [comment]
> should we show settings for disabled extensions that are only disabled via trust?

Whats the use case?

**Comment by sbatten** [comment]
Making it easier to manage settings for extensions in any window or prior to enabling them via trust.

**Comment by cceckman** [comment]
Interesting - I was able to reproduce (on Chrome OS) - 

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.109-26092-g9d947a4eeb73
```

Which, conveniently, has a screen recorder! So [this](https://drive.google.com/file/d/1H36-0MyrBkl6HWhkjY__xFGPZ9ZcqVpk/view?usp=sharing) is what I'm seeing that strikes me as weird.

In text, starting from the the Crostini shell:

- `cargo init --lib` in an empty directory
- `code .` to open the directory as a workspace
- Opens in restricted mode; leave it (and leave the "workspace trust" tab open). Sidebar shows "Rust" extension (0.7.8) is present in the sidebar, but disabled.
- Ctrl+Shift+P -> "> Open Settings (UI)"
- Search for "clippy"; after a second, "Editor: Empty Selection Keyboard" comes up
- *Close* the settings window
- "Trust" in workspace trust window
- Ctrl+Shift+P -> "> Open Settings (UI)"
- Search for "clippy"; same matches as before, no other matches (none from the extension)

- I closed VS Code and reopened (`code .`)
- Workspace trust tab is still open (and reports "trusted")
- Preferences (UI) --> search "clippy"; Rust extension shows up

**Comment by sandy081** [comment]
> Making it easier to manage settings for extensions in any window or prior to enabling them via trust.

I would say that is confusing. Applying a setting and nothing happens in the current window.

**Comment by cceckman** [comment]
@sbatten I see this got auto-closed; did you need more info beyond https://github.com/microsoft/vscode/issues/127266#issuecomment-871012096 ?
