### ISSUE TITLE
"Run and Debug" doesn't work when "configurations" is an empty array in launch.json

### ISSUE THREAD

**Issue by zt1106** [microsoft/vscode#127284]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows

Description:
When launch.json's "configurations" is an empty array, "Run and Debug" doesn't add a debug object to the "configurations" array.

Steps to Reproduce:

1. install any debugger extension (like cpptools)
2. create a launch.json, with it's "configurations" array empty
3. open a C++ file
4. click "Run and Debug" button, and click "C++ gdb"
5. nothing happens, no configuration would be added

Expectation:
click "Run and Debug" button should add a debug configuration to launch.json's "configurations" array.

**Comment by isidorn** [comment]
Yes this is a known limitation. When there is no launch configuration in the `configurations` array that usually means that the user manually modified the `launch.json` and he or she knows what is doing.
I agree that it would be nice if we were to cover this case as well. However I would prefer if the C++ would implement dynamic configurations and hopefully this case would just work without any automatic modification to the launch.json

**Comment by weinand** [comment]
I agree with @isidorn: since there is no direct way in VS Code to create a launch.json with an empty array, we can be certain that such an launch.json must be the result of a user edit operation.

**Comment by zt1106** [comment]
If not a problem for you, this can be closed. I think It would be nice to treat no launch.json same as a launch.json with empty array.

**Comment by isidorn** [comment]
For now let's leave it open, maybe other users also hit this. And after some time if no new ideas come up we can close this.
