### ISSUE TITLE
Extension Debugger does not connect when launching from macOS Touchbar

### ISSUE THREAD

**Issue by lorthirk** [microsoft/vscode#127221]
Does this issue occur when all extensions are disabled?: Yes

Issue Type: <b>Bug</b>

1. Launch Debug with the default "Start Command" button in Touch bar (green "Play" icon with bug in the lower left corner). A new VSCode window starts but the debugger is not connected (VSCode bar still blue)

On the other hand, starting debug with F5 actually connects the debugger (VSCode status bar is orange, and I can see debugging messages in the Output panel)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (9.20GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 59b05d36-f41b-41a2-b7fe-a23f9df2009d|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30329804
binariesv615:30325510

```

</details>

**Comment by weinand** [comment]
Please try the other "Play" icon (without the bug symbol in the corner).
The icons are swapped in the 1.57 release.

**Comment by lorthirk** [comment]
Yes, I can confirm that the Play icon without the bug starts the debugger.

I guess this is a known issue then?

**Comment by weinand** [comment]
Yes, and it's fixed in Insiders (and soon stable).
