### ISSUE TITLE
Add right-click Duplicate to file explorer

### ISSUE THREAD

**Issue by rofrano** [microsoft/vscode#127256]
### Problem statement

Quite often developers start writing code from existing code. Especially for templated code like test cases or REST apis. It currently takes 4 steps to do this in VSCode (copy, paste, find, rename). In macOS finder you can _right-click_ on any file and select `duplicate` and the file will be copied/duplicated with the suffix `-copy` added to the name. It would be great to have this functionality as a context menu item in the explorer of VSCode.

### Existing workflow

If you want to make a copy of a file in VSCode today, you must right-click and select `copy` but you cannot right-click and select paste. No, you have to find an empty area of the explorer window or the folder name that you want the file in to right-click and select `paste`. Then you need to find the file that just got pasted, and right-click a third time and select `rename` to rename the file. This is four (4) steps just to duplicate one file. This is an extremely clumsy user experience.

### Proposed workflow

A developer can highlight any file in the explorer and right-click and select `duplicate`. The command pallet prompt area would open up with the name of the file requesting the name of the new file. The developer would name the file and press enter and have a new file with a new name with the contents of the original file. I believe this is a much better user experience.

### Benefit to developers

Developers can duplicate a file with a new name in a single interaction instead of having to perform four steps (copy, paste, find the file, rename)

**Comment by gjsjohnmurray** [comment]
On Windows I can drag a file, press and hold <kbd>Ctrl</kbd> and then drop it to create a copy.

**Comment by rofrano** [comment]
@gjsjohnmurray Oh wow, Option+Drag does the same on Mac. THANKS! (Ctrl brings up the context menu). 

Hmmm... I still need to use the context menu to rename the file after option+drag. Still would like a single consistent way to do it on both platforms.  (I hate key combos because I can never remember them and they are not intuitively obvious)

Thanks for pointing that out though. I appreciate it. I will definitely start using it.
