### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by Feugueur71** [microsoft/vscode#127216]
Nous avons écrit les données nécessaires dans votre presse-papiers, car elles étaient trop volumineuses à envoyer. Veuillez les coller.

Issue Type: <b>Bug</b>

Il y a une erreur : End of file expected ! pourquoi ?
{
    "workbench.colorTheme": "gckn",
    "workbench.statusBar.visible": false,
    "emmet.triggerExpansionOnTab":true,
    "files.associations": {"*html" : "html"},
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
}
{End of file expected

            "tag": "!",
            "color": "#FF2D00",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
            }
        
        {
            "tag": "?",
            "color": "#3498DB",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "//",
            "color": "#474747",
            "strikethrough": true,
            "underline": false,
            "{backgroundColor}": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "todo",
            "color": "#FF8C00",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "*",
            "color": "#98C379",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        }

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 4405U @ 2.10GHz (4 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.62GB free)|
|Process Argv|--crash-reporter-id 900ca596-0f14-44ac-ae5f-9ac799214073|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-standardjs-snippets|cap|0.8.15
emmet-jss|car|1.0.0
turbo-console-log|Cha|2.1.6
vscode-standardjs|che|1.4.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.23.1
flutter|Dar|3.23.0
moxer-icons|Equ|5.8.0
prettier-vscode|esb|8.0.1
mithril-emmet|Fal|0.7.6
auto-rename-tag|for|0.1.6
terminal|for|0.0.10
vscode-angular2-emmet|jak|2.0.3
vscode-language-pack-fr|MS-|1.57.1
getcodingknowledge-pack|nox|0.14.0
vscode-gitignore-generator|pio|1.0.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
errorlens|use|3.2.7
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30329803
binariesv615:30325510

```

</details>

**Comment by roblourens** [comment]
Your settings.json file is not valid. It looks like maybe something tried to write to your setting.json file. Just delete all the content after the error
