### ISSUE TITLE
Opening a file containing Korean that was created in Eclipse has encoding issues

### ISSUE THREAD

**Issue by isugar150** [Microsoft/vscode#12722]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:
1. 이클립스에서 작성한 .java파일을 불러오면 한글이 깨져보입니다.
   <img width="1440" alt="2016-09-27 4 54 26" src="https://cloud.githubusercontent.com/assets/13088077/18864848/30589b6e-84d3-11e6-827c-3f352232946f.png">

**Comment by joaomoreno** [comment]
@Tyriar a little help?

**Comment by alexandrudima** [comment]
@isugar150 It appears we open the source file as UTF8. Is this correct? Do you save the file encoded as UTF8?

fyi @bpasero

**Comment by bpasero** [comment]
If the file is not using UTF-8, it has to be either changed from the status bar encoding picker or globally configured. For UTF-16 all you need to do is include a BOM and we will pick it up.

**Comment by alexandrudima** [comment]
Closing after a number of days without a response
