### ISSUE TITLE
Spotlight on Mac doesn't respond to vscode

### ISSUE THREAD

**Issue by unknownconstant** [microsoft/vscode#127245]
Issue Type: <b>Bug</b>

Searching for "vscode" on spotlight on a mac doesn't find vscode, it does find the application if writing the application name in full "Visual Studio Code" or just "code". "vscode" should be added as an alias.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by joaomoreno** [comment]
I don't know whether this is possible. @deepak1556 Would you know?

**Comment by deepak1556** [comment]
We cannot add spotlight aliases, it depends on what value an application provides for `CFBundleDisplayName` property in the `info.plist` file. The property only accepts a single value, so we have to choose between `code` and `vscode` if we were to make this change.

**Comment by joaomoreno** [comment]
I suggest to close as won't fix, then.

**Comment by unknownconstant** [comment]
Fair thank you for the input. I would suggest 'vscode' is the name of the application consistent with branding and repo name "microsoft/vscode". I've seen the application referred to as 'code' in a couple of places, but this seems ambiguous as an end user.
