### ISSUE TITLE
High CPU Usage - File watcher & renderer logs ad nauseum

### ISSUE THREAD

**Issue by awerlang** [microsoft/vscode#127203]
Issue Type: <b>Bug</b>

The logs look like this line ad nauseum:
`
[22:0626/005735.759736:INFO:CONSOLE(627)] "%cTRACE color: #888 [File Watcher (node.js)] [CHANGED] /home/user/.config/Code - Insiders/logs/20210626T035552/renderer1.log", source: vscode-file://vscode-app/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
`

Javascript profiler mainly points to this trace call, no other useful information. The file `renderer1.log` contains the very same information. I attempted to disable file watcher with `**/**` but still getting these logs. Probably wouldn't fix the underlying issue anyway, but could stop this mutual reference.

This VS Code is running in a container with no GPU -- as details below can tell. This has been working fine until/including May release.

VS Code version: Code - Insiders 1.58.0-insider (49e1f9919880c1c96004f9b6ad91bcee7a94a1bd, 2021-06-25T05:13:13.023Z)
OS version: Linux x64 5.12.12-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.52GB (3.66GB free)|
|Process Argv|--verbose --disable-telemetry --no-sandbox --disable-gpu --no-xshm --disable-dev-shm-usage --disable-features=VizDisplayCompositor --crash-reporter-id 1ce82692-46e5-4d41-9f85-2740344190e4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693

```

</details>

**Comment by awerlang** [comment]
Hello. What info can I add to this bug report? I used the Report Issue screen from VS Code, which advised to copy and paste to a new issue, as it couldn't do automatically for some reason.

**Comment by awerlang** [comment]
This happens before a workspace/directory is loaded.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by awerlang** [comment]
I found this wiki page but it's not helpful. It's not a startup/extensions/workspace issue.

It looks like it's a recent defect:

/duplicate 126477
