### ISSUE TITLE
High CPU usage caused by activity indicator animation in terminal tabs

### ISSUE THREAD

**Issue by mn4367** [microsoft/vscode#127235]
Issue Type: <b>Bug</b>

The spinning indicator for a running task in a terminal tab causes an unusual high CPU usage.

CPU load with animation:

![terminal-animation-on](https://user-images.githubusercontent.com/6379696/123525177-227b1c80-d6cf-11eb-8b01-661450c4a49a.png)

CPU load with animation turned off by setting CSS visibility to `hidden`:

![terminal-animation-off](https://user-images.githubusercontent.com/6379696/123525187-2f980b80-d6cf-11eb-8e37-f6d26214572c.png)

The CPU load of the task itself has no influence on this phenomenon, it's present even when the task is idle. If VS Code is started with `--disable-gpu` the CPU load decreases but is still too high in my opinion.

While it's nice to have an indicators for running tasks I'm one of the users which are distracted by running animations in the workbench (this has already been mentioned by users in other issues). Ideally there would be a configuration option for turning the animation off or change the appearance to something static like a red dot or a background color for the terminal tab.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:50.042Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 08839393-42d4-484e-a20c-52fc5dbd5656|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
git-extension-pack|don|0.1.3
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.5.1
vscode-command-runner|edo|0.0.118
insert-file|esp|0.0.2
dummytextgenerator|gur|1.0.1
reflow-markdown|mar|2.1.0
vscode-language-pack-de|MS-|1.57.1
hexeditor|ms-|1.7.1
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by mn4367** [comment]
Sorry, can you please reopen this? Mentioning the distraction the animation causes for *me* is just a side note. If you like, I can remove this part (since it's really a duplicate), but the main problem with high CPU usage is still relevant and not even mentioned in #126197.

**Comment by Tyriar** [comment]
@mn4367 disabling the animation will fix the CPU problem. This is just how much CPU is costs chromium to display the rotating icons.

**Comment by mn4367** [comment]
@Tyriar thanks, yes, I know that and I'm doing that already all the time although it's tedious to use the developer tools for it.

I haven't tested that on an Intel machine so maybe it's an M1 specific problem with Chromium/Electron. What do you think, is it worth opening an issue there (in memory of the infamous blinking cursor performance problem back then)?

**Comment by Tyriar** [comment]
@mn4367 if you can refine down an example that shows really bad CPU performance when it shouldn't you could create an issue for Chromium, I'd guess there's already an issue tracking it though. It looks like we do use CSS animations here so it's the same as the blinking cursor issue you mention 😛 

```
animation: 1.5s steps(30) 0s infinite normal none running codicon-spin;
```
