### ISSUE TITLE
Not able to write anything in the editor

### ISSUE THREAD

**Issue by githubdkg** [microsoft/vscode#127247]
Issue Type: <b>Bug</b>

I have tried both the user version and the system version of VS Code. Both are having the same problem:
Each version was carefully installed only after restarting the computer, but inspite of that, I'm not able to write or edit anything in the VS Code. This problem is for both the new files and the already existing files on my Lenovo IdeaPad S540 laptop/machine. Happening for all file types or prog. languages.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (3.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5
material-icon-theme|PKi|4.7.0
java|red|0.79.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vim|vsc|1.21.3

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled? Especially `vim`
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by githubdkg** [comment]
> /needsMoreInfo
> 
> Is it reproducible with all extensions disabled? Especially `vim`
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`

Thank You Sir for pointing out about disabling Vim extension! Now it is working fine after uninstalling the same.
But why Vim is having issues with VS-Code? [I'm a newbie to Vim!]
