### ISSUE TITLE
VSCode Multiple Windows on Launch

### ISSUE THREAD

**Issue by Giov12** [microsoft/vscode#127271]
Issue Type: <b>Bug</b>

The issue really is just launching the application, whether it be by clicking on the application or opening it using the command line. Everytime I launch VSCode, two additional windows are opened as well.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.12GB (21.20GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 16b12185-86a6-478e-8f7d-e6359d891d3b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-makefile-project|adr|1.1.0
atlascode|atl|2.9.1
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.5.1
vscode-great-icons|emm|2.1.79
git-extensions-for-vs-code|for|1.1.3
code-runner|for|0.11.4
vscode-gitbuild|grz|1.0.1
github-repository-manager|hen|0.6.1
r|Iku|2.0.0
vscode-git-add-and-commit|iva|2.1.1
vscode-sshfs|Kel|1.20.1
share-git-url|lia|0.0.8
vscode-checkpoints|mic|1.3.2
syncfusion-gitlab-management|moh|0.0.3
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
cpptools|ms-|1.4.1
vscode-yaml|red|0.20.0
github-links|rit|2.0.0
pdf|tom|1.1.0
vscode-git-remote|ves|0.0.12
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by carlocardella** [comment]
Do you have multiple VSCode windows open, say before a reboot? You can control how windows are reopened after a reset/restart: 

![image](https://user-images.githubusercontent.com/5784415/123561714-ea231f00-d75e-11eb-997f-e1ad15fc454f.png)

**Comment by Giov12** [comment]
Thank you for the quick response. I have set the option to _one_ and after a full shutdown and reboot, two extra windows still pop up.
