### ISSUE TITLE
markdown is not showing correctly in hover

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/vscode#127220]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.57.1
- OS Version: windows 10 - 21H1

![image](https://user-images.githubusercontent.com/69088224/123513162-cac5bc80-d6a0-11eb-9045-1bb6fee579d2.png)

as you see, the markdown in the hover is not shown correctly

**Comment by mjbvz** [comment]
Please share steps + code to reproduce this

/needsMoreInfo

**Comment by MohammadMD1383** [comment]
I'm building a vscode extension and when I hover some functions or variables, the documentation is showing like what I posted.

No further information about that.

**Comment by mjbvz** [comment]
Please share the code that causes this

**Comment by MohammadMD1383** [comment]
no code causes this.
just create a new extension project (`yo code` in terminal) and hover some function e.g. `vscode.workspace.findFiles()` and then you will see the information containing markdown is not showing correctly

**Comment by MohammadMD1383** [comment]
![image](https://user-images.githubusercontent.com/69088224/123956889-6e281180-d9c0-11eb-979c-c6fdac6a5355.png)

**Comment by MohammadMD1383** [comment]
By now the problem is solved. I think it solved after 1.58.2 update...
