### ISSUE TITLE
[json] Expand Selection in JSON in strings does not work as expected

### ISSUE THREAD

**Issue by AlansCodeLog** [microsoft/vscode#127264]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.58.0-insider (system setup)
Commit: 49e1f9919880c1c96004f9b6ad91bcee7a94a1bd
OS: Windows 10

Steps to Reproduce:

For example, in a tasks.json I might have:
```json
{
	"command": "%SOMETHING%/path/OTHER_PATH/SOME_OTHER_PATH/toSomewhere"
}
```
And here's some of the weird selections I'm getting when I try to expand:
```
"%SOME|THING%/path/OTHER_PATH/SOME_OTHER_PATH/toSomewhere"
"%SOMETHING%/pa|th/OTHER_PATH/SOME_OTHER_PATH/toSomewhere"
"%SOMETHING%/path/OTH|ER_PATH/SOME_OTHER_PATH/toSomewhere"
=> %SOMETHING%/path/OTHER_PATH/SOME_OTHER_PATH/toSomewhere

"%SOMETHING%/path/OTHER_PAT|H/SOME_OTHER_PATH/toSomewhere"
=> PATH/SOME
"%SOMETHING%/path/OTHER_PATH/SOME_OTHER_PA|TH/toSomewhere"
=> PATH/to
"%SOMETHING%/path/OTHER_PATH/SOME_OTHER_PATH/t|oSomewhere"
=> PATH/to

"%SOMETHING%/path/OTHER_PATH/SOME_OTHER_PATH/toSome|where"
=> Somewhere"

This works (on the first expand):
"%SOMETHING%/path/OTHER_PATH/SOME_OTH|ER_PATH/toSomewhere"
=> OTHER
```

Strangely double clicking works fine, and so does `Ctrl+Shift+Left/Right`.

I initially thought maybe expand selection wasn't meant to respect the word separators setting (is it?), but then I noticed the above. It's almost like it's only respecting `_` and `-` but even then it's all over the place, for example `"SOME_WHE|RE"` -> `WHERE"` but `"S|OME_WHERE"` -> `SOME_WHERE`.

**Comment by aeschli** [comment]
The ranges that you see come from a generic WordRangeSelectionProvider that only looks at underscore and CamelCasing and uses the JSON word rules which are quite special (they are the while literal).
Not easy to fix due to the various other dependencies on the word rules.

**Comment by zardoy** [comment]
@aeschli Does this behaviour relate to this issue?

If I create empty file with the following content, it expands correctly:

`-env VI|TE_P` → `VITE`

But with the quote at the start:

`"-env VI|TE_P` → `env VI`

Do you know why does it take space in selection instead of a word?

**Comment by zardoy** [comment]
Furthermore, if you change `VITE` to `vite` it would expand and the word itself and the `env`:

`"-env vi|te_P` →  `env vite`

**Comment by aeschli** [comment]
Yes this is related. The JSON language server considers the full string a 'word' (as this is what you completions would work).
The word selector makes it's own assumptions what a word is (letters and '_')
