### ISSUE TITLE
Inconsistent loading feedback

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12729]
The hover loading indication is the trustworthy *Loading...* label while IntelliSense shows a flashy animation of chasing dots. Both should be aligned - and yes, my preference would be the `Loading...` label because it's less nervous.

![sep-27-2016 10-33-45](https://cloud.githubusercontent.com/assets/1794099/18865960/11025d98-849e-11e6-9caa-4ed49d97e00a.gif)

**Comment by joaomoreno** [comment]
Me too actually... 👍  Just wanted to roll with it for a while...
