### ISSUE TITLE
Rename Korean character doesn't work correctly

### ISSUE THREAD

**Issue by dohun-toss** [microsoft/vscode#127286]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

![2021-06-28 13 51 31](https://user-images.githubusercontent.com/70137461/123582108-33837500-d818-11eb-82f3-03e13f345437.gif)

Steps to Reproduce:

1. Input some Korean characters
1. Open rename input with `Fn + F2` 
2. Rename another korean characters -> Vscode renames a last Korean character with line feed(? I'm not sure)

**Comment by jrieken** [comment]
@dohun-toss I am not entirely sure what's being input. Do you press Enter to finish actually start the rename or does that happen somehow by itself? Or is this a bad rename operations, e.g can I copy-paste the value that you have entered and does that result in a bad rename?

**Comment by dohun-toss** [comment]
@jrieken 

1. I pressed `Enter` to finish rename. It didn't happen on its own. It's bad rename operation.
2. I checked that it works fine when I copy-and-paste Korean characters. this only happens when typing Korean characters.

**Comment by jrieken** [comment]
What language is this? Can you reproduce with a simple sample and share that here?
