### ISSUE TITLE
Written content in Debug Console is deleted after a Panel switch

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#127288]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: RHEL7

Hello,
I would like to submit an issue related to `Debug Console`
Steps to Reproduce:

1. Write in Debug Console without sending your request
2. Switch to Terminal View
3. Switch to Debug Console. Content to evaluate is empty

I think this content should be saved before a panel switch.

Regards.

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders, if yes can you attach a picture? https://code.visualstudio.com/insiders/

**Comment by yannickowow** [comment]
Using 1.58 Insiders on Windows 10 x64

https://user-images.githubusercontent.com/45362067/123595177-e344ec80-d7f0-11eb-86b7-8a41ee4e685d.mp4

As you can see, I typed "info breakpoints" in the Debug Console. After a panel switch, content is now empty

**Comment by isidorn** [comment]
@yannickowow good catch, thanks for letting me know.
I have pushed a fix you can try it out from Tuesday and let me know if this is indeed fixed for you know. Thanks!

**Comment by yannickowow** [comment]
It works perfectly on my side, thanks a lot!
It looks like this fix does more than that. I was experiencing some issues regarding to Debug Console completion (with first debug run) and with Output Events (not printed if I switch from a panel too quickly).
