### ISSUE TITLE
What's the `When` condition for checking if the debug console is active?

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#127255]
I'm trying to bind `Clear Console`(`workbench.debug.panel.action.clearReplAction`) to a shortcut, the problem is what's the `When` condition for checking if the debug console is active?

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/api/references/when-clause-contexts

**Comment by wenfangdu** [comment]
@gjsjohnmurray Thanks, could you please have a look at [this question](https://github.com/microsoft/vscode/issues/127254) as well?
