### ISSUE TITLE
Zoom not working with mouse wheel+ctrl

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#127228]
open any code on vscode and try to adjust the zoom with ::  ctrl + scroll ; it has stopped working
* Code: 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c)
* OS: win32(10.0.19043)

**Comment by ArturoDent** [comment]
Is your `Editor: Mouse Wheel Zoom` setting enabled?

**Comment by tymsai** [comment]
Thanks its now working
