### ISSUE TITLE
Debug current typescript file does not work from VS code

### ISSUE THREAD

**Issue by pIIrash** [microsoft/vscode#127312]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: **1.57.1**
- OS Version: **Windows 10 Enterprise 20H2 19042.1052**

### Steps to Reproduce:

1. Run and Debug: Select Debug Test: Current ts File
2. Only the _Process exited with code 1_ message appears in Debug console and does not stop at breakpoints.

```
**Debug console**
_C:\Program Files\nodejs\node.exe .\node_modules\mocha\bin\_mocha -r dotenv/config --color -r ts-node/register shared\src\impl\portable\nats-message-publisher.spec.ts_

_Process exited with code 1_
```

3. Run the same command from command prompt
```
X>"C:\Program Files\nodejs\node.exe" .\node_modules\mocha\bin\_mocha -r dotenv/config --color -r ts-node/register/index.js shared\src\impl\integration-tests\nats-message-publisher-subscriber.integration-test.ts

  NATS IMessagePublisher and IMessageSubscriber Integration Tests
[winston] Attempt to write logs with no transports {"labels":{"class":"NATSConnectionFactory","correlationId":"","tenant":""},"level":"info","message":"NATS options {\"debug\":false,\"verbose\":false,\"name\":\"pds\",\"reconnect\":true,\"servers\":[\"0.0.0.0:4222\"]}"}
[winston] Attempt to write logs with no transports {"labels":{"class":"NATSConnectionFactory"},"level":"info","message":"NATS client connected to 0.0.0.0:4222."}
...
[winston] Attempt to write logs with no transports {"labels":{"class":"NATSConnectionFactory","correlationId":"","tenant":""},"level":"info","message":"Closing NATS client and drain subscriptions."}

  5 passing (126ms)
```

_This error applies to all tests._
There is the same issue on my colleague's computer too.

For tests we are using **Mocha**.

**launch.json**
    {
      "name": "Debug Test: Current ts File",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "args": ["-r", "dotenv/config", "--color", "-r", "ts-node/register", "${relativeFile}"],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "env": {
        "NODE_PATH": "."
      }
    },

**Comment by connor4312** [comment]
You want to set the console or outputCapture options, see [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes)

**Comment by pIIrash** [comment]
> 
> 
> You want to set the console or outputCapture options, see [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes)

Thank you. This could help to find the real issue in _launch.json_:
      `"args": ["-r", "dotenv/config", "--color", "-r", "ts-node/register", "${relativeFile}"],`
It was necessary to change it to
      `"args": ["-r", "dotenv/config", "--color", "-r", "ts-node/register/index.js", "${relativeFile}"],`
