### ISSUE TITLE
Go to File (ctrl+p) with selected editor text

### ISSUE THREAD

**Issue by angrypro** [microsoft/vscode#127335]
If current editor have a selected text and the user pressed (ctrl+p), that text could be automatic copied to the search box to find a file that correspond with selected file.

If has no text selection on current editor, open as it is today.

Example: When you have a text on your source code that represents one or more files. I have to copy that name, open go to file, and paste that name.

**Actual command list walk through:**
1. Select text
2. Ctrl+c
3. Ctrl+p
4. Ctrl+v

**To improve our user performance could be only:**
1. Select text
2. Ctrl+p

![image](https://user-images.githubusercontent.com/6818431/123660834-60c92680-d80a-11eb-9d00-038100e62334.png)

Tkx

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=colch.quick-open-prefill-selection

**Comment by angrypro** [comment]
> https://marketplace.visualstudio.com/items?itemName=colch.quick-open-prefill-selection

Tkx, cool extension that work exactly like I need.
But I think that extension behavior could be default for everyone.

**Comment by TylerLeonhardt** [comment]
Considering this would be a behavior change, and folks are very particular with muscle memory, I think I could give this feature, at best, a setting to toggle behavior where it wouldn't be the default.

but then I think ... well.. if it wouldn't be the default behavior and then user would have to explicitly opt-in for it, then that "opt-in" behavior should just be the extension that @usernamehw mentioned above.

I'll mark it as a backlog candidate to gauge interest in this feature but I don't think we need it when an extension is available for those that do want this.

**Comment by angrypro** [comment]
> Considering this would be a behavior change, and folks are very particular with muscle memory, I think I could give this feature, at best, a setting to toggle behavior where it wouldn't be the default.
> 
> but then I think ... well.. if it wouldn't be the default behavior and then user would have to explicitly opt-in for it, then that "opt-in" behavior should just be the extension that @usernamehw mentioned above.
> 
> I'll mark it as a backlog candidate to gauge interest in this feature but I don't think we need it when an extension is available for those that do want this.

Thanks Tyler,

I suggested to be the default behavior because who migrated from Eclipse or IntellyJ have this behavior as default and if you don't select any text, current behavior will not change.

**On eclipse** ctrl+shit+r (open resource) -> It opens with selected text
![image](https://user-images.githubusercontent.com/6818431/123690292-97af3480-d82a-11eb-9db3-f03ccaafd6c7.png)

**On IntelliJ** ctrl+shift+n (open files) -> It open with selected text
![image](https://user-images.githubusercontent.com/6818431/123691192-af3aed00-d82b-11eb-829c-0bac4c655990.png)

I also use Android Studio that's based on IntelliJ with that same behavior, so when I select a text and press ctrl+p on vscode, I feel like my muscle memory failed.
