### ISSUE TITLE
Test: Editor Service with untyped inputs

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127355]
Refs: #124351

- [x] anyOS @sbatten
- [x] anyOS @connor4312
- [x] anyOS @chrmarti

Complexity: 5

Authors: @bpasero, @lramos15

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127355%0A%0A)

---

A large refactor was completed surrounding the `EditorService` and the `EditorOverrideService`. This focused on improving the lifecycle of `IEditorInput`s by reserving them for open editors only. Internally both services now operate on untyped inputs only and for now convert the few consumers of typed inputs left to untyped. This change also involved removing the `DelegatingEditorService` which was used by the explorer. These changes should not have produced any functionality change and this testing is focused on ensuring there are no regressions as the underlying logic has changed significantly.

### Prerequisite
Ensure you have multiple custom editors and notebooks installed (luna paint, hex editor, rest notebooks, github issue notebooks, and markdown notebooks is a good sample set). 

### Testing
- Test Reopen With... and Open with... to ensure those still work for notebooks and custom editors.
- Test built-in custom editors such as welcome page, search editor, split json settings editor.
- Test built-in special editors such as untitled editors, diff editors (e.g. from SCM or compare action)
- Ensure breadcumbs still work
- Try setting a different custom editor or notebook as the default through the `Configure Default` option in the reopen with quickpick. Make sure that your setting is respected
- Ensure drag and drop across windows still works
- Test opening from the explorer
- Test opening from the recent history
- Test opening from the command palette
- Test opening from the search results panel
- Test opening from the problems panels
- Test actions that replace the opened editor such as "Save As..." or "Save All" with many untitled dirty editors
- Test dropping N files into the opened window
- Test from the command line opening N files into the current window
- Test other miscellaneous opening avenues

**Comment by chrmarti** [comment]
How can I open the built-in split JSON settings editor?

**Comment by lramos15** [comment]
> How can I open the built-in split JSON settings editor?

`"workbench.settings.useSplitJSON": true` and then reopen settings.json
