### ISSUE TITLE
term quick access shows closed terminal editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127307]
From @g3offrey in https://github.com/microsoft/vscode/issues/10546#issuecomment-869564274

Hello,

First of all I want to thank you @meganrogge and @Tyriar about the awesome job on terminal editors. This is literally a game changer for me 😍 

I tried this feature a lot these last days, and I encountered an issue that I think is not mentioned here.
When I close terminal editors, they are not deleted from the listing when typing `term` in CMD+P palette.

I share you a gif that shows this issue.

![screen](https://user-images.githubusercontent.com/11151445/123620421-7fc7b880-d80a-11eb-9aec-76d3522bd800.gif)

Steps to reproduce : 
1. Open clean and up-to-date "Code Insiders" instance
2. Create a bunch of terminal editors (either via command palette or drag and drop)
3. Close them using the bin / closing the editor or via "kill" command
4. Open CMD+P palette and type `term `
5. ⚠️ Closed terminal still appears here

If I can help you on this issue, don't hesitate to reach me. 

Again, thank you for your work on this feature. ✌️

**Comment by Tyriar** [comment]
This can still happen, repro:

1. Drag a terminal into editor
2. Split it
3. Close the right side

1 terminal editor:

<img width="316" alt="Screen Shot 2021-06-28 at 9 10 08 AM" src="https://user-images.githubusercontent.com/2193314/123669146-a4169b80-d7f0-11eb-8b95-a2475ca3c8cc.png">

Showing 2:

<img width="604" alt="Screen Shot 2021-06-28 at 9 09 12 AM" src="https://user-images.githubusercontent.com/2193314/123669117-9e20ba80-d7f0-11eb-9262-620fc0652f42.png">

**Comment by g3offrey** [comment]
Hi !

I just tested the fix and it works fine for the use cases mentioned here. Thank you !

However I found another weird use case when splitting a terminal editor using the button at the top right corner (the one used to split editors). Indeed if you close both terminal after splitting then using this button, you will still find one in the term listing 😅

**Comment by Tyriar** [comment]
Thanks a bunch for the follow up @g3offrey, I can repro. Hopefully this'll catch all the cases 🙂
