### ISSUE TITLE
[Test API] Allow register command into the run button in the editor

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#127385]
It would be great if we can allow registering command into the run button in the editor

![image](https://user-images.githubusercontent.com/6193897/123724498-4c545080-d841-11eb-91b1-6279b5a47630.png)

**Comment by gifhuppp** [comment]
goodnight

**Comment by jdneo** [comment]
Not sure if I did anything wrong about this contribution.

With this change https://github.com/jdneo/vscode-extension-samples/commit/189d5000531de392326923fdcdf36c4ba096a926

when the command triggered, I cannot get the test item instance.

![image](https://user-images.githubusercontent.com/6193897/127419303-a32d20d9-01d4-4730-a913-900f707d05af.png)

**Comment by connor4312** [comment]
Thanks, fixed in the next Insiders @jdneo
