### ISSUE TITLE
Terminal editors don't respect right click behavior

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127341]
Repro:

1. Set `"terminal.integrated.rightClickBehavior": "paste"`
2. Try right click to paste in a terminal editor

Repro 2:

1. Set `"terminal.integrated.rightClickBehavior": "selectWord"` (default on macos)
2. Try right click, it should select word and show the context menu, but it only selects the word - the context menu may be completely broken in terminal editors

**Comment by meganrogge** [comment]
Currently right clicking is displaying the editor menu on windows

![recording (7)](https://user-images.githubusercontent.com/29464607/123671611-52bbdb80-d7f3-11eb-903c-b5eff27b7cd1.gif)

**Comment by Tyriar** [comment]
Terminal context menu code is within TerminalTabbedView:

https://github.com/Microsoft/vscode/blob/fc9962bc887a5ed8327287a5896ed2b0547b7ae9/src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts#L345-L348

Needs to come to TerminalEditor
