### ISSUE TITLE
Linked editing with text containing a hyphen does not work in XML

### ISSUE THREAD

**Issue by datho7561** [microsoft/vscode#127323]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
- OS Version:
Fedora Linux 34
Kernel: 5.12.12-300.fc34.x86_64

Steps to Reproduce:

1. Write an extension which provides `linkedEditing` for XML documents that does not return a `wordPattern` in the response (the redhat.vscode-xml snapshot build provides this feature and is available [here](http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D))
2. Set `editor.linkedEditing` to `true`
3. Make an element with a hyphen in the name (eg. `<web-app></web-app>`)
4. Place the cursor in the opening tag
5. `web-app` in the opening and closing tag will be highlighted red
6. Modify the opening tag
7. The closing tag doesn't change to match the opening tag

**Comment by datho7561** [comment]
The version of vscode-xml with linked editing support is now available from the marketplace, so you don't need to download the snapshot build if you are going to test using it.

**Comment by aeschli** [comment]
I see our XML word pattern doesn't include the `-`.
Thanks for the PR!
