### ISSUE TITLE
Can't launch debug target via npm

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12737]
- VSCode Version: 1.6.0-Insider
- OS Version: Windows 10

Steps to Reproduce:
1. Follow the steps in https://github.com/Microsoft/vscode/issues/12253
2. Try to launch. I get

![capture](https://cloud.githubusercontent.com/assets/1931590/18868903/3280617a-84aa-11e6-9307-d3e8db059e84.png)
1. Running npm run debug from the terminal works as expected.

![capture](https://cloud.githubusercontent.com/assets/1931590/18868940/5353b8de-84aa-11e6-89a3-6dfa4902850a.png)

I use nvm to manage my node installs. Don't know if this makes a difference.

**Comment by roblourens** [comment]
Works on OSX but not Windows. Workaround - change your runtimeExecutable to `"npm.cmd"` on Windows.

**Comment by roblourens** [comment]
I guess in general this won't work if your runtimeExecutable is a .bat/.cmd and you don't include the extension.

**Comment by weinand** [comment]
The problem is that on Windows both a 'npm' and a 'npm.cmd' exist on the PATH but only the latter works on Windows. If a launch config specifies `npm` VS Code will use that but fails because `npm` is a shell script for linux/macOS.
I've added this to the release notes.

**Comment by weinand** [comment]
This has made its way into the documentation. See note at the end of https://code.visualstudio.com/docs/editor/node-debugging#_launch-configuration-support-for-npm-and-other-tools

**Comment by aeschli** [comment]
Verified that this is in the documentation.
