### ISSUE TITLE
compilation sass raises stop app without error

### ISSUE THREAD

**Issue by macifree** [microsoft/vscode#127306]
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

i run "life sass compiler" it generates css. but as soon as I make any changes to sass, then raises stop app without error. Hangs up.

**Comment by aeschli** [comment]
Can you file this against the life sass compiler extension? https://github.com/ritwickdey/vscode-live-sass-compiler/issues
Thanks you!
