### ISSUE TITLE
White spots and net like appeared on vscode

### ISSUE THREAD

**Issue by Dr-Crab** [microsoft/vscode#127390]
![Screenshot (1)](https://user-images.githubusercontent.com/84935908/123740810-a4816600-d8c6-11eb-9526-0c088f984809.png)
![Screenshot (2)](https://user-images.githubusercontent.com/84935908/123740837-ae0ace00-d8c6-11eb-8078-947acc1e3764.png)

I have uploaded the screenshots my screen is totally fine, I have installed VScode from the Microsoft vs code website.

**Comment by Azrideus** [comment]
Im no expert but have you installed latest version of netframework and your graphic card drivers?
also do you meet the [minimum system requirements ](https://code.visualstudio.com/docs/supporting/requirements) ?

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/124226

Can you check if running with `--disable-gpu` helps ?

**Comment by Dr-Crab** [comment]
Thanks, It is working fine now.
