### ISSUE TITLE
Consider changing the default value of `editor.suggest.previewMode`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#127347]
I personally find `"editor.suggest.previewMode": "subwordDiff"` to be very jumpy and it feels like it interferes with my typing. I have changed it to `"editor.suggest.previewMode": "prefix"` in my settings, but wanted to drop you a note that you might consider `"prefix"` as the default.

**Comment by hediet** [comment]
I agree. However, sometimes it is nice, especially in TypeScript where the completion automatically adds the question mark in `variable?.field` if `field` is autocompleted and `variable` can be null or undefined.
