### ISSUE TITLE
Hidden by default `Watch` and `Call Stack` in debugger tab

### ISSUE THREAD

**Issue by karolzlot** [microsoft/vscode#127348]
I rarely use `Watch` and `Call Stack` in debugger tab. Most of the time I hide them to have better view of variables.

But vscode doesn't remember this. I would like to save it, make this layout default.

<img src="https://user-images.githubusercontent.com/11590960/123679894-5463be80-d848-11eb-9f5c-e8d1dedc8e73.png" width="300">

<img src="https://user-images.githubusercontent.com/11590960/123679942-62b1da80-d848-11eb-94a8-2d336044e155.png" width="300">

**Comment by isidorn** [comment]
The collapse state is remembered per workspace
You can right click -> hide that is remembered for user across all workspaces.

I think this is a desired behaviour. So closing this as designed
