### ISSUE TITLE
`vscode.env.shell` doesn't report correctly terminal when a new shell of different type is opened without changing the default setting

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#127374]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 (user setup)
- OS Version:Windows_NT x64 10.0.19043

Hi Python extension dev here 👋

Steps to Reproduce:

1. Open a different type of terminal directly (for eg. git bash) using the icon.
<img src='https://user-images.githubusercontent.com/13199757/123701186-6298e700-d816-11eb-9c77-555612256afa.png' width=200 />

2. Subscribe to the `vscode.window.onDidOpenTerminal` event. Try to get the active terminal type using `vscode.env.shell`. It still reports the default shell. This leads to us sending the wrong activation commands.

3. Even if we wait a little, the API always reports the default shell instead.

We can also replace step 1 with `vscode.window.createTerminal(undefined, 'C:\\Windows\\System32\\cmd.exe')` instead of using the icon, and notice `'C:\\Windows\\System32\\cmd.exe'` is not reported via the API.

cc @Tyriar

**Comment by Tyriar** [comment]
`vscode.env.shell` always returns the default by design. To find what the shell is you should look at the `Terminal` object on `vscode.window.onDidOpenTerminal`

**Comment by karrtikr** [comment]
I see. Just so I understand correctly, we should first look at `Terminal.creationOptions.shellPath`, and if it's not set, then fallback to `vscode.env.shell` API, correct?

**Comment by Tyriar** [comment]
Yes if the `creationOptions` aren't set then it will use `vscode.env.shell` since an undefined value for the shell means it uses the default.
