### ISSUE TITLE
Intellisense partially not working

### ISSUE THREAD

**Issue by Nitikk** [microsoft/vscode#127376]
Issue Type: <b>Bug</b>

Hello microsoft, my issue in Visual Studio Code v1.57.1 is that my Intellisense with C# extension enabled is partially not working. I can use all the variables (bool, float, int etc.) but not methods (start, update, oncollisionenter etc.). Please help

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.49GB free)|
|Process Argv|E:/Projectt/New Unity Project (1) -g E:\\Projectt\\New Unity Project (1)\\Assets\\Scripts\\TriggerEvents.cs:1:0 --crash-reporter-id f7c96171-8542-42f1-b16f-e60d4add7997|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
extbundles-csharp|Fel|2.0.1
auto-using|Fud|0.7.15
docomment|k--|0.1.20
csharp|ms-|1.23.12
vscode-versionlens|pfl|1.0.9
csharpextensions|tda|1.4.1
msbuild-project-tools|tin|0.3.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805:30301674
binariesv615:30325510
vsccppwtct:30329789

```

</details>

https://user-images.githubusercontent.com/73529766/123705115-20a68a00-d884-11eb-8ff7-74814f1c67e7.mp4

**Comment by sbatten** [comment]
This issue is regarding the C# extension. Please start by filing an issue with them to investigate. https://github.com/OmniSharp/omnisharp-vscode/issues
