### ISSUE TITLE
Consider adding an active tab line to the terminal tabs list

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127360]
One annoyance I've had with tabs is that it's sometimes difficult to tell what the active item is because we rely so much on the selection which can change (plus bugs can slip in like https://github.com/microsoft/vscode/issues/127357). 

How about using the editor's selected tab border color and overriding with a terminal-specific one if present?

![image](https://user-images.githubusercontent.com/2193314/123689454-19419b00-d808-11eb-8b54-c086a8dd47bd.png)

@misolori what do you think? Note that I have it overlapping the sash right now which should be fine as long as it ignored pointer events.

**Comment by misolori** [comment]
yea this looks great. Also similar in notebooks, we also show a slightly thicker and offset indicator:

<img width="240" alt="CleanShot 2021-06-28 at 12 09 40@2x" src="https://user-images.githubusercontent.com/35271042/123690843-b94bf400-d809-11eb-8dcb-71b4cab99c97.png">

but i think what you show better mirrors the active panel/editor border

**Comment by Tyriar** [comment]
Unfortunately it wasn't really doable without a bunch of hacks to replace the existing sash line:

![image](https://user-images.githubusercontent.com/2193314/124750839-cc7e5400-deda-11eb-9698-88b819207502.png)
