### ISSUE TITLE
Test new testing APIs

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127386]
Refs: https://github.com/microsoft/vscode/issues/122208 (last comment is the design)

- [x] anyOS @joaomoreno
- [x] anyOS @joyceerhl

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127386%0A%0A)

---

This iteration involved some significant changes to the testing API as we approached finalization. Namely, the TestController is now a managed object with its handlers attached.

- Play with the new API for the TestController and TestItem. Note any comments, concerns, or problems.
- Read the docs and make sure things make sense.

There are two existing test provider implementations you can use as a good basis:

- The selfhost test provider https://github.com/microsoft/vscode-selfhost-test-provider
- The test provider sample https://github.com/microsoft/vscode-extension-samples/tree/master/test-provider-sample

**Comment by connor4312** [comment]
If you feel hungry for more after verifying this testplan, you're also in a good position to verify https://github.com/microsoft/vscode/issues/126646

**Comment by JustinGrote** [comment]
@connor4312 here is my current implementation, I've pretty much mostly been able to get rid of "data" altogether and work off the properties of the managed testItems themselves. I put tags in the description.

https://github.com/pester/vscode-adapter/tree/initialCommit

**Comment by jdneo** [comment]
#126646 works well in

Version: 1.58.0-insider (user setup)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Test implementation: https://github.com/testforstephen/vscode-pde/pull/33


https://user-images.githubusercontent.com/6193897/123933228-071a4680-d947-11eb-959f-d4b8069962b8.mp4
