### ISSUE TITLE
chrome_crashpad_handler consuming cpu and generating 100K dmp files

### ISSUE THREAD

**Issue by winzig** [microsoft/vscode#127392]
Issue Type: <b>Bug</b>

Last week or so I noticed fans running quite a bit and often see chrome_crashpad_handler process consuming high CPU when vscode in use. When I double-click on it in Activity Monitor, the "Open Files and Ports" points to vscode:

`/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler`

Digging into it further, looks like it's generating hundreds of thousands of .dmp files in `~/Library/Application Support/Code/Crashpad/pending/` and also seeing tens of thousands in `~/Library/Application Support/Code/Crashpad/complete/`. 

Looked around for a viewer for these .dmp files, but not seeing anything obvious. Any tips for digging into what is triggering these dumps?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id 7fa3914a-6723-4a59-8df2-d01755446466|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
Bookmarks|ale|13.1.0
aws-toolkit-vscode|ama|1.25.0
unique-lines|bib|1.0.0
codestream|Cod|11.0.11
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.20
swift|Kas|0.2.0
vscode-cfn-lint|kdd|0.19.0
vs-color-picker|lih|1.0.0
auto-dark-mode|Lin|0.1.7
prettify-json|moh|0.0.3
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
vscode-dotnet-runtime|ms-|1.1.0
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
hexeditor|ms-|1.7.1
js-debug-nightly|ms-|2021.6.1117
powershell|ms-|2021.6.2
debugger-for-chrome|msj|4.12.12
printcode|nob|3.0.0
vetur|oct|0.34.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.5.21
swiftlint|shi|0.1.3
vscode-stripe|str|2.0.2
sourcekit-lsp|unp|0.0.1
code-navigation|vik|0.2.0
vscode-icons-mac|way|7.25.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
pythonvspyt200:30329803
binariesv615:30325510

```

</details>

**Comment by winzig** [comment]
Note that originally I was seeing this high CPU behavior when using Code Insiders, so switched to regular Code this week and no change, so suspect a problem with an extension. It's not always easy to duplicate the problem so difficult to run for extended periods with no extensions and get anything done, so looking for another way to debug this.

**Comment by deepak1556** [comment]
Can you attach a couple of those crash dumps, it will be easier to see what they point to.

**Comment by winzig** [comment]
@deepak1556 Attached the latest 3 from right now (just started happening again). 

Hopefully they don't reveal sensitive info, which is why I hesitated to attach to the original report. :trollface:
[dmps.zip](https://github.com/microsoft/vscode/files/6736443/dmps.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, all of them point to crash in the dotnet runtime specifically a call from `libcoreclr.dylib` leads to `libsystem_c.dylib!abort` case. Since I don't have symbols for this extension binary, I can't specifically say why.

Next steps,

1) Report the crash with `vscode-dotnet-runtime` extension along with the logs
2) Until the issue is fixed you can disable the crash reporter in vscode via:

```
* Open the Command Palette (⇧⌘P).
* Run the Preferences: Configure Runtime Arguments command.
* This command will open a argv.json file to configure runtime arguments. You might see some default arguments there already.
* "enable-crash-reporter": false.
* Restart VS Code.
```

**Comment by winzig** [comment]
Will do, thanks!

**Comment by winzig** [comment]
FYI I adjusted that setting to disable crash reporting, restarted code, and then after an hour noticed a new influx of thousands of .dmp files in pending. ¯\_💩_/¯

**Comment by winzig** [comment]
I take it back, I disabled crash telemetry through the usual code preferences area. I see now you described a different method, with runtime argument changes, so trying that now.
