### ISSUE TITLE
Go to File (ctrl+p) open at once multiple files selected

### ISSUE THREAD

**Issue by angrypro** [microsoft/vscode#127337]
When pressing ctrl+p we can open only one file today, correct? To open several files with similar names we have to Go to file searching for file name multiple times.

It would be nice if Go to File shortcut be a multiple select list with "shift+arrows", "shift+arrows", "ctrl+shit+arrows", "ctrl+space", "ctrl+left-click", "ctrl+a", "ctrl+shift+home", "ctrl+shift+end" shortcuts to select multiple files and open with <enter>.

**Example:**
When files are listed, could press shift+arrow-down to select both lines and <enter> to open both files.
![image](https://user-images.githubusercontent.com/6818431/123663046-66277080-d80c-11eb-8bbd-4b1b6ce6cc8e.png)

**Comment by TylerLeonhardt** [comment]
I like the idea. I've added to the backlog candidates to gauge interest. I will say that this would be different then a lot of other quick picks because multi-select in the quick pick is usually the checkbox experience.
