### ISSUE TITLE
Test: Allow `vscode.env.asExternalUri` to return valid results for workspace URIs

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127367]
Refs: https://github.com/microsoft/vscode/issues/124263

- [x] anyOS @rebornix 
- [x] anyOS @weinand 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23124263%0A%0A)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127367%0A%0A)

---

Up until now, the  `vscode.env.asExternalUri` API has been limited to `http:`, `https:` and `${appScheme}:` URIs. It would throw an error if you give it any other URI. With https://github.com/microsoft/vscode/issues/124263, any other URI is assumed to be a workspace URI and VS Code should return a system-openable URI which opens that workspace. For example, give it `file:///path/to/existing/folder` and you get something which you can paste on a browser location bar and it should open that folder in VS Code.

This API just went stable, so please test you can successfully use it *without* having `enableProposedApi: true`.

Create a sample extension. Then invoke that API and:

- Test that using `http:`, `https:` and `${appScheme}:` works just as before
- Test that it never throws for schemes which VS Code can open as a workspace, eg `file:`. A good sample is `vscode.env.asExternalUri(vscode.workspace.workspaceFolders[0]!.uri)`, which should produce a system-wide URI which opens the current workspace.
- Test that it throws for schemes unknown to VS Code, eg `asdf:`

**Comment by weinand** [comment]
Minor doc issues in vscode.d.ts:
- "Resolves a uri to form that is accessible externally." -> "Resolves a uri to **a** form ..." 
- "Extensions should not make any assumptions about the resulting uri and should not alter it in anyway." -> "... any way."

**Comment by weinand** [comment]
@joaomoreno `asExternalUri`-generated links (e.g. `vscode-insiders:workspace?file%3A%2F%2F%2FUsers%2Fweinand%2FDesktop%2Furitest`) work fine in Chrome, Edge, and Firefox. But Safari just googles for them. Do you know why?

**Comment by joaomoreno** [comment]
Unsure... The right way to test on macOS might just be on the Terminal with `open URL`.

**Comment by weinand** [comment]
@joaomoreno good idea, thanks!
