### ISSUE TITLE
can't open and can't uninstall

### ISSUE THREAD

**Issue by fekfoq259** [microsoft/vscode#127382]
Issue Type: <b>Bug</b>

After install few day later can't open and can't uninstall in Setting.
Install again can solve this problem.
It happen twice.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.57GB free)|
|Process Argv|--crash-reporter-id 10f8b094-0f51-407e-b292-0dbd7e56ce7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
alignment|ann|0.3.0
zh-hans-tt-hant-vscode|cip|1.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-simpler-icons|dav|1.6.5
vscode-autohotkey2|dud|0.2.0
prettier-vscode|esb|8.0.1
code-runner|for|0.11.4
pangu|hal|0.1.6
vscode-insertdatestring|jsy|2.3.0
vscode-language-pack-zh-hant|MS-|1.57.1
powershell|ms-|2021.6.2
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
sort-lines|Tyr|1.9.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> can't uninstall in Setting

Is there an error?

**Comment by fekfoq259** [comment]
> > can't uninstall in Setting
> 
> Is there an error?

No error.
And in "C:\Users\username\AppData\Local\Programs\Microsoft VS Code" folder some file disappear e.g. "unins000.exe".
But "Code.exe" exist but just can't open.

**Comment by joaomoreno** [comment]
OK, can you completely uninstall and remove VS Code? Then install it. Then, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by fekfoq259** [comment]
> OK, can you completely uninstall and remove VS Code? Then install it. Then, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

Done.

**Comment by fekfoq259** [comment]
> OK, can you completely uninstall and remove VS Code? Then install it. Then, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

Hi. I Set `update.enableWindowsBackgroundUpdates` to `true`. same issue happen again.

C:\Users\username\AppData\Local\Programs\Microsoft VS Code\ many file disapper.
still exist file :

- chrome_100_percent.pak
- chrome_200_percent.pak
- Code.exe
- d3dcompiler_47.dll
- ffmpeg.dll
- icudtl.dat
- libEGL.dll
- libGLESv2.dll
- resources.pak
- v8_context_snapshot.bin

still exist folder :
- locales
- resources

**Comment by joaomoreno** [comment]
Given that you've installed the latest Stable, and there hasn't been any updates yesterday or today... I asusme there wasn't any update flow. So you might have some other software in your system messing with Code's files.
