### ISSUE TITLE
Cursor only works correctly on Basic Multilingual Plane

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1273]
Paste the following into the editor:

```
abc 𠮷 def
```

Using the <kbd>Left Arrow</kbd> key, navigate from the beginning of the line to its end. As you jump over the Chinese character, you'll notice that it takes two key presses to get away from it. Additionally, if you type some latin text between those two jumps, the content of the line from that position until the end fully disappears. You are creating bytes from within the double-byte Chinese character, effectively generating invalid Unicode sequences.

**Comment by alexandrudima** [comment]
All the cursor operations are character index based and not unicode point based. So, any Unicode point outside the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)) (i.e. needing more than 16bits) can be corrupted by editor operations such as delete, etc.

**Comment by alexandrudima** [comment]
This has been fixed in the sense that we now navigate by code points. We do not navigate by graphemes, which is an entirely different cookie.
