### ISSUE TITLE
Debug does not step into function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127397]
![recording (1)](https://user-images.githubusercontent.com/900690/123755834-9a5a6a00-d8bc-11eb-984f-04ed3530eebd.gif)

Maybe related: https://github.com/microsoft/vscode/issues/127345

**Comment by bpasero** [comment]
(I will point to the code once I checked it in)

**Comment by bpasero** [comment]
Oh, this reproduces in devtools too!

**Comment by bpasero** [comment]
First breakpoint:

https://github.com/microsoft/vscode/blob/5dc800432622c38031975631df21e6e3eb762ea0/src/vs/workbench/services/editor/test/browser/editorService.test.ts#L1027-L1027

Second breakpoint:

https://github.com/microsoft/vscode/blob/ff2022a0a36a039527ce795e73eaeecca28c29f4/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L128-L128

**Comment by connor4312** [comment]
This is fixed in the latest Chromium versions: https://bugs.chromium.org/p/chromium/issues/detail?id=1035072 -> https://bugs.chromium.org/p/chromium/issues/detail?id=782461

Duplicates https://github.com/microsoft/vscode-js-debug/issues/179
