### ISSUE TITLE
Workspace Trust popup monospace font should inherit editor's

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127304]
![image](https://user-images.githubusercontent.com/22350/123617432-856fcf00-d807-11eb-88e4-1b1594ce1469.png)

**Comment by sbatten** [comment]
Should we? I know we do that for hovers and stuff but that's close to the code. We don't do that in the settings editor for example and this feels similar.

**Comment by joaomoreno** [comment]
At least pick something not incredibly ugly like the default font which happens to be Courier New with an eye-bleeding antialiasing algorithm.
