### ISSUE TITLE
Problems: Activity for panels not updated 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12738]
Testing https://github.com/Microsoft/vscode/issues/12643

I had 2 errors but the hover was still reading "No Problems" in the sidebar.

**Comment by isidorn** [comment]
I do not think the hover should show the number of errors at all, it should just show 'Problems'.
If you agree this is a dup of https://github.com/Microsoft/vscode/issues/12508

**Comment by bpasero** [comment]
Makes sense.
