### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127395]
- [x] Windows @JacksonKearl
- [x] macOS @sana-ajani
- [x] Linux @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127395%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/main/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by JacksonKearl** [comment]
Windows search smoke test failed on first try, green on attempt 2.
