### ISSUE TITLE
[theming] Allow `inherit` theme color

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#127380]
<img width="700" src="https://user-images.githubusercontent.com/35271042/123300980-fa719a80-d4cf-11eb-9799-6b1e11c84309.png">

<hr>

Compared to a regular list item where a suffix overrides the default styles:

<img width="300" src="https://user-images.githubusercontent.com/35271042/123300760-be3e3a00-d4cf-11eb-9b00-576717b33172.png">

<hr>

So my thinking was if we introduced a way to cause the overrides to take a "inherit" property (or whatever name you'd want), it could fix these issues:

<img width="700" alt="CleanShot 2021-06-24 at 09 41 20@2x" src="https://user-images.githubusercontent.com/35271042/123301830-eda17680-d4d0-11eb-8270-a9d09489c3f6.png">

_Originally posted by @misolori in https://github.com/microsoft/vscode/issues/126514#issuecomment-867794960_

**Comment by misolori** [comment]
Created a new issue to track this.

**Comment by joaomoreno** [comment]
This is specific to themeing, not the list widget.

@aeschli Could we have a unique identifier in the core which lets us specify that a specific color value should literally be `inherit`?

**Comment by aeschli** [comment]
Is this like 'undefined' or 'null'? We allow the color defaults to have that value
(we don't allow users to set it though)

**Comment by joaomoreno** [comment]
No, it's an actual value. We want the `.toString()` on that color to return `inherit`, such that the CSS would look like:

```css
color: inherit;
```

**Comment by aeschli** [comment]
The actual CSS is created by you:
https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/base/browser/ui/checkbox/checkbox.ts#L207

I don't think adding a color `inherit` should be in a color theme.

**Comment by aeschli** [comment]
Can you point me to the actual place where one would want to use the 'inherit' color?

**Comment by joaomoreno** [comment]
This is the issue: https://github.com/microsoft/vscode/issues/126514#issuecomment-867794960

**Comment by misolori** [comment]
Another issue that is coming up because of this is https://github.com/microsoft/vscode/issues/128798 so we have to manually patch the css for icon issues as they come up

**Comment by aeschli** [comment]
After more discussions with @misolori we agreed that we lack a way to express to not use the [default list style color](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/list/listWidget.ts#L954).

Let's add a new value, but not overgeneralize but add this in the IListStyles where it is needed, I don't think 'inhert' is a good name. Maybe "undefined". Or '"inheritFromParent? (Do we know the parent?) We culd also use 'null' as as allowed value to signal that no color should be defined.

@misolori I suggest you make the needed changes so you can test that out right away,

**Comment by misolori** [comment]
I had already attempted to add a custom value but didn't get far with it. If you have any code pointers that would be great.

**Comment by aeschli** [comment]
Since a while we support `default` as color value. It sets the color to the colors default which can be null.
