### ISSUE TITLE
Test: [Welcome] Mark newly contributed walkthroughs as new

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#127384]
Refs: https://github.com/microsoft/vscode/issues/127196

- [x] anyOS @rebornix
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127384%0A%0A)

---
This iteration we added support for classifying walkthroughs as "New" when an extension providing them is newly installed. Test:
- These `New` walkthroughs should be sorted higher in the list than non-new walkthroughs (excepting the "featured" builtin ones), with the newest being sorted to the top.
- After reading a walkthrough, future times opening the Welcome page will not show the walkthrough as `New`, and if applicable some other newer walkthrough takes their place
- If an extension is updated to provide new items in its walkthrough, it will be labeled `New Items`, again until the walkthrough has been viewed. 

![image](https://user-images.githubusercontent.com/8586769/123724467-3e9ecb00-d841-11eb-8575-a2af606f819e.png)

**Comment by JacksonKearl** [comment]
Thanks to @misolori for opening https://github.com/microsoft/vscode/issues/127379 regarding the theming of the badges

**Comment by dbaeumer** [comment]
@JacksonKearl can you provide me with an example of how to test 

> if an extension is updated to provide new items in its walkthrough

**Comment by JacksonKearl** [comment]
@dbaeumer yes, you can start with https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample. Run the sample, and open the walkthrough. Then, close out of that window, add another step to the extension's contribution point, and run the sample again

**Comment by dbaeumer** [comment]
@JacksonKearl thanks!
