### ISSUE TITLE
Open Preview on the side of Markdown documents

### ISSUE THREAD

**Issue by MuffinLover42** [microsoft/vscode#127354]
Add an "Open Preview to the side" interaction menu to right-clicked Markdown files (.md), and similar formats where you are often checking the preview, that allows you to open a preview on the side without having to drag it there yourself.

**Comment by igorskyflyer** [comment]
Have you tried using the already available keyboard command `⌘ + K   +   V` for macOs and `Ctrl + K   +   V` for others or do you want a mouse command for that as well?

**Comment by MuffinLover42** [comment]
I didn't know there was a keyboard shortcut but I suppose a mouse command would be nice

**Comment by mjbvz** [comment]
There's a button in the toolbar of markdown files:

![Screen Shot 2021-06-29 at 10 25 31 AM (2)](https://user-images.githubusercontent.com/12821956/123841428-6420e880-d8c4-11eb-93a2-3bcbf81f060c.png)
