### ISSUE TITLE
jupiter notebook

### ISSUE THREAD

**Issue by s-e1** [microsoft/vscode#127364]
Issue Type: <b>Bug</b>

I tried opening up a jupiter notebook like I have done many times, but it is stuck loading it. 
It also gives a message about that:
"Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information." I ran that, but didn't see what the problem is.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.90GB (16.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|12.0.5
vscode-intelephense-client|bme|1.7.1
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.832593372
LiveServer|rit|5.6.1

</details>

**Comment by rebornix** [comment]
@s-e1 can you please share the logs from the Dev Tools?

**Comment by s-e1** [comment]
> 
> 
> @s-e1 can you please share the logs from the Dev Tools?

electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61

workbench.desktop.main.js:62 [Extension Host] (node:21024) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
b @ workbench.desktop.main.js:62
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_CONNECTION_RESET
workbench.desktop.main.js:2943 Extension Host
workbench.desktop.main.js:2943 Debugger attached.
workbench.desktop.main.js:741 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ workbench.desktop.main.js:741
workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:682923)
	at Object.t.resolveInstance (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:238445)
	at c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:237650
	at Object.t.resolve (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:237913)
	at c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:229010
	at e._get (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:228776)
	at e.get (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:227488)
	at a.get (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:508810)
	at c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:52:271101
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:37:823700
	at async t.activate (c:\Users\USER\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:37:823387)
	at async Promise.all (index 0)
b @ workbench.desktop.main.js:62
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/507ce72a4466fbb27b715c3722558bb15afa9f48/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

**Comment by s-e1** [comment]
> 
> 
> The described behavior is how it is expected to work. If you disagree, please explain what is expected and what is not in more detail. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!
The expected behavior is that the file should open, not just to be stuck in loading it.
I forgot to mention that I recently updated vsc, and only since then does this happen. Before the update it opened the file without any problem.

**Comment by s-e1** [comment]
The jupyter notebook extension just got an update and it now works again.
