### ISSUE TITLE
Getting started star badges look odd in light theme

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#127379]
<img width="435" alt="CleanShot 2021-06-28 at 15 41 04@2x" src="https://user-images.githubusercontent.com/35271042/123712518-50737480-d827-11eb-98b7-eeaf46a03e7e.png">

The star + "New" badges look broken. We don't typically use white on gray as it creates low contrast. Is there a reason why we didn't stick with the same styling from extension recommendations?

<img width="367" alt="CleanShot 2021-06-28 at 15 42 22@2x" src="https://user-images.githubusercontent.com/35271042/123712580-70a33380-d827-11eb-8dd1-1af22c5139ef.png">

## Suggestion

I suggest we use the button background/foreground as those are paired nicely, and make the `new` badge a little smaller w/ more padding. Left-aligned feels a bit better than floating on the right IMO.

<img width="454" alt="CleanShot 2021-06-28 at 15 46 34@2x" src="https://user-images.githubusercontent.com/35271042/123712859-08a11d00-d828-11eb-95eb-f8ee5c7d3fba.png">

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/124044938-69b12800-d9c3-11eb-8d49-fcd880147de1.png)
