### ISSUE TITLE
Clicking a png file can open it twice, toggling between the two editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127310]
This was happening over the weekend too, not just today's build

Repro:

1. Copy and paste an image via explorer
2. Click the image, it will open a new preview editor that doesn't use the custom editor
3. Click the image, it will switch back to the working editor

![recording](https://user-images.githubusercontent.com/2193314/123629592-4cb10500-d7c9-11eb-8c56-c4ea355651c9.gif)

**Comment by bpasero** [comment]
Confirmed, it looks like `OverrideStatus.NONE` is returned in the `openEditor` call but we then still create an editor input:

![image](https://user-images.githubusercontent.com/900690/123648443-3dfa3a80-d829-11eb-9351-de82af3b6115.png)

That one is obviously ignoring any override handling and thus opens normally.

Leaving it up to @lramos15 how to handle this better.

**Comment by bpasero** [comment]
With the original fix, https://github.com/microsoft/vscode/issues/126923 happens again, thus smoke tests stop working which rely on this functionality.
