### ISSUE TITLE
Wrong terminal tab is selected after reload window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127357]
Repro:

1. Open several terminals
2. Change their color
3. Show active terminal always via setting
4. Reload, notice how the active terminal (red below) is not selected in the tabs list

<img width="770" alt="Screen Shot 2021-06-28 at 11 52 48 AM" src="https://user-images.githubusercontent.com/2193314/123688830-5ce7d500-d807-11eb-9fad-90bea1ac358e.png">

**Comment by meganrogge** [comment]
This is working for me, I think you fixed it with https://github.com/microsoft/vscode/commit/8ab8d2ae9515bfdb563d809d9be2a0cd41e462aa

**Comment by Tyriar** [comment]
Still repros on today's build:

![image](https://user-images.githubusercontent.com/2193314/123793231-53f21480-d896-11eb-9069-0cca1a302c66.png)

**Comment by meganrogge** [comment]
Yep happens for me in today's build but not yesterday's, so the change that caused this was very recent

**Comment by Tyriar** [comment]
Confirmed it's the inline tab that's wrong

<img width="448" alt="Screen Shot 2021-06-29 at 9 23 37 AM" src="https://user-images.githubusercontent.com/2193314/123833901-b01b5f80-d8bb-11eb-8557-df27a22fb845.png">
