### ISSUE TITLE
2 feature addition to "Search" section.

### ISSUE THREAD

**Issue by SandeepGamot** [microsoft/vscode#127332]
Hey guys, searching across the repo is almost a daily task and vscode does a decent job but there are 2 use cases that I wish vscode can add in

### First one: 

**Current Problem :** The search section search bar always searches across the repo, there's no option to narrow your search to some files.

**Proposed Solution:**
Let's say I have 100 files in my repo and I search for `FooBar` across the repo, I get 30 odd files for that search.
Now I'd like to search for let's say `BazFred` only in the files that showed up in the search list for `FooBar`, so basically we want to filter out the files for search term `FooBar` and then search for `BazFred` within those files. 

We want to search through some files instead of across the repo all the time. 
So maybe something like a checkbox "Search within the listed files only"

This is kind of similar to https://github.com/microsoft/vscode/issues/118128

### Second one: 

**Current Problem :** Sometimes in some complex refactor we wish to switch between different recent searches we did across the repo typing them out everytime becomes an unnecessary hassle.

**Proposed Solution:** In the search section have a collapsible tab  exactly how we have in extensions (installed / recommended) maybe called "Recent Search Profiles" 
This will contain a list of recent search's data i.e search keyword, files to include and files to exclude. 
And clicking on one of them should bring up the search result again. 
Not every search should go into the search profile by default, a handy button "Add to search profile" would be great. 

I hope this is clear to understand, please let me know otherwise. I would also love the opportunity, if any, to work on a PR for these. 
Thank you.

**Comment by gjsjohnmurray** [comment]
Perhaps you haven't already discovered that the cursor-up key in the Search field will recall previous entries.

**Comment by roblourens** [comment]
The first sounds like the issue that you linked. The second sounds like you want search history, and as @gjsjohnmurray pointed out, you can get that with the arrow keys
