### ISSUE TITLE
use new readonly modifier

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12732]
- VSCode Version: 1.6.0-Insider
- OS Version: Windows

Added the following code to the TS extension when a diagnostic result comes back from the tsserver

``` ts
        if (window.activeTextEditor) {
            window.activeTextEditor.options.lineNumbers = 'relative';
        }
```

Debugged it and the code gets executed but the line numbering doesn't change for the active editor.

**Comment by alexandrudima** [comment]
@jrieken We should consider adopting `readonly` in `vscode.d.ts`. AFAIK `activeTextEditor.selection.start.line` has a similar issue

**Comment by jrieken** [comment]
related to  #6907

**Comment by jrieken** [comment]
depends on https://github.com/TypeStrong/typedoc/issues/234

**Comment by jrieken** [comment]
Moving this out...

**Comment by alexandrudima** [comment]
just fyi this is no longer an issue for `editor.options`, starting with 19291ef2c1dc7fc20d521f32b8dbe279de413a0c it is possible to use `editor.options.tabSize = 3` and it'll work.

**Comment by jrieken** [comment]
ok. good to know

**Comment by jrieken** [comment]
will happen in https://github.com/Microsoft/vscode/pull/13863
