### ISSUE TITLE
compose down - mapping values are not allowed in this context

### ISSUE THREAD

**Issue by rpa275** [microsoft/vscode#127349]
Issue Type: <b>Bug</b>

Receiving this error message when right clicking on the root node and clicking `Compose Down`.  This only works now when I right click on the actual docker-compose.yml file and run `compose down` there. Just updated to the Docker Desktop 3.5.1 version on MacOS

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.29GB free)|
|Process Argv|-psn_0_139298 --crash-reporter-id 80bfa16f-e5b5-41b5-88d2-88c154596371|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.25.0
ng-template|Ang|12.0.5
php-debug|fel|1.16.0
phpcs|ika|1.0.5
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
angular-console|nrw|17.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwt:30329788

```

</details>

![image](https://user-images.githubusercontent.com/71098918/123681761-32524800-d818-11eb-837e-e5aa83dd47bb.png)

**Comment by rpa275** [comment]
The YAML file shows as valid, checking through the http://www.yamllint.com/.  Also, the YAML file was fine with this compose down feature prior to updating the docker desktop from 3.3.3 to 3.5.1

**Comment by sbatten** [comment]
This issue is regarding the docker extension.
