### ISSUE TITLE
Source Control Pane shows the same view on different windows / workspaces

### ISSUE THREAD

**Issue by harmony5** [microsoft/vscode#127324]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/18639388/123652401-438c5c00-d7fa-11eb-8ba9-05218cc5c891.png)

# Steps
1. Open multiple files from wsl (Ubuntu) on non-workspace, local vscode window.
2. Open project workspace from local on another local vscode window, without closing first window.
3. Go to Source Control Pane on 2nd window (if project workspace has git setup).

# Actual result
The non-workspace window also shows the same Source Control view (same files and changes) from the workspace window, even though the non-workspace window does not have any Source Control setup.

# Expected result
The Source Control Pane should only be active (show changes) for those workspaces that have some source control setup, and shouldn't be active when editing multiple files on a non-workspace window.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.39GB free)|
|Process Argv|\\\\wsl$\\Ubuntu\\home\\jc\\.bashrc --crash-reporter-id a87aaaf2-bf57-4158-93fd-7e664f1af8ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
xd|ado|1.2.3
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
python-ultisnippets|eli|2.7.0
prettier-vscode|esb|8.0.1
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.6
remotehub|Git|0.10.1
vscode-codeql|Git|1.5.1
vscode-pull-request-github|Git|0.27.1
vscode-test-explorer|hbe|2.20.4
vscode-codemetrics|kis|1.24.0
bash-ide-vscode|mad|1.11.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.12
dotenv|mik|1.0.1
vscode-docker|ms-|1.14.0
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
test-adapter-converter|ms-|0.0.10
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.5.0
mdx|sil|0.1.0
addDocComments|ste|0.0.8
unique-window-colors|stu|1.0.51
tabnine-vscode|Tab|3.4.10
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
vscode-mdx-preview|xyc|0.3.0

(5 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
@harmony5, apologies for not getting back to you on this until now. Please use the `git.autoRepositoryDetection` setting to customise the repository discovery behaviour. You can set the setting to `subFolders` in order for VS Code not to open git repositories for the loose files that are being opened.
