### ISSUE TITLE
Ability to collapse and expand all files in search results

### ISSUE THREAD

**Issue by hilel** [microsoft/vscode#127336]
It may help to find what I am looking for when got results in many files.

Thank you!

**Comment by gjsjohnmurray** [comment]
Try focusing on one of the file headers in the results then pressing Ctrl+LeftArrow (probably different modifier on macOS).

**Comment by ArturoDent** [comment]
Thyere are two commands (unbound to any keybinding) you can use from the Command Palette or make your own keybinding:

`Search: Expand All`      `search.action.expandSearchResults`
`Search: Collapse All:`  `search.action.collapseSearchResults`

**Comment by roblourens** [comment]
Yes, and the expand/collapse actions are in the search view toolbar. Thanks @gjsjohnmurray and @ArturoDent

**Comment by hilel** [comment]
Found it, 
Thanks
