### ISSUE TITLE
Debugging a PR is not pleasant when comments are there

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127316]
![recording](https://user-images.githubusercontent.com/900690/123642290-6848f980-d823-11eb-8e87-83cb2a251493.gif)

The currently debugged line is not visible because comments jump in momentarely after opening the file.

**Comment by alexr00** [comment]
I'm not sure what the best thing to have happen here is. I don't want the comments to hide by default when debugging, because what it someone has a debugging code tour. 

GHPRI could provide a command to hide all comments. Or, VS Code could provide a way to hide all comments in a file.

**Comment by bpasero** [comment]
Slightly related: I actually find my own comments not very useful to see in a PR. Here I am on a branch that I created as a PR and provided some comments as help for the reviewer but I constantly have to collapse my own comments. Can I disable comments entirely?

**Comment by alexr00** [comment]
Neither VS Code not GHPRI provide a way to hide all comments. I could certainly add that in GHPRI.

**Comment by bpasero** [comment]
I was hoping for a way to switch between "review" mode and "working" mode of a PR. When I review code, I don't mind the comments but when I work on a PR and make changes, they are often in my way.

**Comment by alexr00** [comment]
Various related requests:
https://github.com/microsoft/vscode-pull-request-github/issues/2492
https://github.com/microsoft/vscode-pull-request-github/issues/2186
https://github.com/microsoft/vscode-pull-request-github/issues/665
https://github.com/microsoft/vscode-pull-request-github/issues/408

**Comment by isidorn** [comment]
@alexr00 in case you want to add a setting to hide all comments maybe consider having a three state:
visible, hidden and auto
Auto being the default and meaning we automatically hide them when we think it is not needed (for example while debugging)

**Comment by bpasero** [comment]
No matter how comments get hidden or not, I think the original issue is still that something is off with revealing a line when comments expand. Probably a timing issue?

**Comment by isidorn** [comment]
@bpasero it looks like debug first reveals the right line and then the PR extension decides to reveal the line with comments.. Maybe we could improve that

**Comment by alexr00** [comment]
There is now a command and a setting for hiding comments: https://github.com/microsoft/vscode-pull-request-github/issues/665
