### ISSUE TITLE
Test auto disabling extensions if its dependencies are disabled

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#127368]
Ref: https://github.com/microsoft/vscode/issues/122448

- [x] anyOS @kieferrm
- [x] anyOS @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23127368%0A%0A)

---

Extensions are now automatically disabled if they have dependencies which get disabled. To test it:

- Install remote repositories extension and open a remote repository (virtual workspace)
- Have following setting in your user settings - This is to define builtin Git extension to not to support virtual workspace and builtin GitHub extension to support. Note that GitHub extension depends on Git extension.
```json
"extensions.supportVirtualWorkspaces": {
		"vscode.git": false,
		"vscode.github": true
	}
```
Please reload after updating above setting to take the effect.

- Make sure both extensions are disabled - Go to disabled view in extensions view and check
- Make sure Git extension shows info icon and provide tooltip/message that it is not supported in virtual worksapces
- Make sure Github extension shows warning icon and provide tooltip/message that it is disabled because its dependency is disabled.
- Make sure Github extension is automatically enabled when Git extension is enabled using above configuraiton.

**Comment by joaomoreno** [comment]
With this feature, it becomes strange that I can't disable an extension which had dependants without forcefully disabling those as well. The problem with that is that enabling the original extension won't enable the dependants. So... is there any other way to test this other than using the `extensions.supportVirtualWorkspaces` setting?

**Comment by sandy081** [comment]
I do not think this can happen when user tries to disable an extension from our UI. With introduction of virtual/trusted workspaces features, we auto disable those extensions which do not support these workspaces. It can happen that dependencies of these extensions can support and can be enabled and break while activation (as you see in the original issue). 

So with this feature we auto disable extensions if its dependencies are disabled.

**Comment by joaomoreno** [comment]
So this entire TPI is about a new feature: **automatic extension enablement/disablement**. This new feature is purely automatic given other features like virtual or trusted workspaces. Correct?

**Comment by sandy081** [comment]
Correct
