### ISSUE TITLE
keep the space when formatting

### ISSUE THREAD

**Issue by leonz3** [Microsoft/vscode#12733]
- VSCode Version: 1.5.3
- OS Version: win10

Steps to Reproduce:

1. before format

![image](https://cloud.githubusercontent.com/assets/8253850/18866617/5ecf3a5c-84d3-11e6-8795-5b5e3b219611.png)
2. after format

![default](https://cloud.githubusercontent.com/assets/8253850/18867028/211f75a8-84d5-11e6-9394-a4e48545e96d.jpg)

**Comment by waderyan** [comment]
Tried this with VS Code Insiders 1.6 and could not reproduce. 

Can you try this with [VS Code Insiders 1.6](http://code.visualstudio.com/insiders)? This has the latest TypeScript language service so this should solve your issue. 

![formatcodespacing](https://cloud.githubusercontent.com/assets/2449568/18934812/dfd388ac-8590-11e6-86f7-9b2ab5136026.gif)

I'll reopen if the problem persists for you.

**Comment by leonz3** [comment]
it used! thank you!😊😊😊
