### ISSUE TITLE
Debug tests: often first click to "Debug Test" does nothing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127396]
Very often I right click > Debug Tests and my breakpoints are not hit. It always works the second time though, haven't figured out what this could be.

![image](https://user-images.githubusercontent.com/900690/123755065-d4773c00-d8bb-11eb-92b1-c85204ab1fef.png)

**Comment by bpasero** [comment]
![recording (2)](https://user-images.githubusercontent.com/900690/123794393-136cb800-d8e3-11eb-981f-96b068737017.gif)

**Comment by connor4312** [comment]
I think is fixed now, please let me know if not.
