### ISSUE TITLE
Settings Sync: Settings merge editor is not opening 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#127328]
- Make sure you have some settings
- Turn on settings sync
- Choose to merge manually - which opens merge view
- Click on settings entry

🐛 Merge diff editor is not opening. 

It works when opening other resources like keybindings.

Seems like following has hijacked the editor for this resource:

https://github.com/microsoft/vscode/blob/d0ca6c7003063cd07a85bef42eab61f92797de8a/src/vs/workbench/contrib/preferences/common/preferencesContribution.ts#L62-L100

**Comment by roblourens** [comment]
`if (!!this.configurationService.getValue(USE_SPLIT_JSON_SETTING)) {`

Only if you have `useSplitJson` right?

**Comment by sandy081** [comment]
Seems like so

**Comment by roblourens** [comment]
I don't think there is any way around this, right @lramos15?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/blob/dc4b317192d606fd244e6d7723b18249054ed13a/src/vs/workbench/contrib/userDataSync/browser/userDataSyncMergesView.ts#L317-L328

**Comment by lramos15** [comment]
We could just ignore the split json editor in this case and add `EditorOverride.DISABLED` to always force the textual diff if you think that's fine

**Comment by sandy081** [comment]
Also had to add the same in above commit.
