### ISSUE TITLE
Comments API: resolved/unresolved comments

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#127473]
The comments API doesn't have the concept of resolved/unresolved threads, although most code review tools distinguish them. The current API allows us to surface this to the users, see https://github.com/microsoft/vscode/issues/122243

However, this seems pretty limited. I find it difficult to identify all my unresolved comments. It's very easy to miss some of them. If the API had a boolean for unresolved comments, we could surface them in multiple ways:

- In the Comments panel, surface the number of unresolved comments, similar to what is done with Problems: ![comments number](https://user-images.githubusercontent.com/485572/123806379-2be2cf80-d8ef-11eb-9bfe-246487cc261c.png)
- In the Comments panel, highlight the unresolved comments (or put them in bold), so that it's obvious to the user what comments they still have to go through.
- In the Comments panel, have a way to hide/filter the resolved comments.
- In the Editor, consider consider using a different background color for unresolved comments. I currently use a different label for unresolved comments, but this is very subtle.
- In the gutter, use a different symbol for unresolved comments (e.g. or a diamond of another color).
- In the Editor, provide a way to go to the next unresolved comment (an alternative to `Go to Next Comment Thread`).

**Comment by laurentlb** [comment]
Let's discuss the API change.

IMO, the information should be part of a [CommentThread](https://code.visualstudio.com/api/references/vscode-api#CommentThread).

On many levels, Comments seem similar to [Diagnostic](https://code.visualstudio.com/api/references/vscode-api#Diagnostic)s. A diagnostic is a comment provided by a tool such as a compiler. A comment is typically provided by a human. Diagnostics have a severity field, which indicates how important is the problem. We need an equivalent for Comments, something that tells the user if an action is expected (e.g. they need to resolve it) or not. Once the user addresses the comment, the importance is reduced.

1. A simplistic solution is to add a boolean, e.g. `isResolved: boolean`.
2. Similar to `collapsibleState`, we can go for a two-state enum instead: `resolvedState: resolved | unresolved`
3. Or to be more general: `importance: high | low`.

We might consider having more fields here. In a code review, multiple users interact with the comments. The current VSCode user is not necessarily the person who needs to do something. For example, the user has just updated the comment and they wait for a response. So the third value could be used to mean "it's not my turn" or "acknowledged, I'll come back later". The benefit is that the user can use the list of "unresolved" issues as a TODO-list and publish the comments once it's empty. 

3. `resolvedState: resolved | pending | unresolved`

**Comment by isidorn** [comment]
@laurentlb Thank you very much for your proposal.
@rebornix, @alexr00 and me have quickly discussed this and we believe this proposal makes good sense.
We plan to start looking into it next milestone. Though no promises yet when this will land, we will know more in December when we start our investigation.

**Comment by alexr00** [comment]
All of the proposals in https://github.com/microsoft/vscode/issues/127473#issuecomment-974201448 have merit. In a perfect world I would choose one of options 2 or 4; however, we have users of the comments API who's comments don't have a resolved/unresolved state. Option 3 circumvents that, but then we have the issue of what to show in the UI: a GitHub PR comment isn't high or low priority.

Another proposal, similar to how comment reactions work:

https://github.com/microsoft/vscode/blob/143578fcb27a3ee0336e44fbe75896e18fe656b8/src/vscode-dts/vscode.proposed.commentsResolvedState.d.ts#L10-L47

**Comment by laurentlb** [comment]
I see than @hermannloose left comments on the commit (https://github.com/microsoft/vscode/commit/6197a2dce87c3d87b9b26f408a7055d9bf428827#diff-1dfb341fde2874ea77bfad0b6f93fe906baf50642c07905158906ec33116d888).

I like the approach of having an object for the state (instead of the proposed boolean/enum), it gives more flexibility and lets user create their own states. In my proposal, the information was attached to a thread, not to a single comment. Do we have use-cases where we want this information per comment?

We might also want to control the gutter icon:

```ts
readonly gutterIconPath?: string | Uri;
```

**Comment by alexr00** [comment]
> Do we have use-cases where we want this information per comment? 

GitHub comments are resolved per-thread, so no, no cases were we want it per comment. I'll move it to the thread.

**Comment by alexr00** [comment]
After much discussion, we have decided to proceed with the following:

https://github.com/microsoft/vscode/blob/1712a239c036f1ceb973eb3378575e40d957c899/src/vscode-dts/vscode.proposed.commentsResolvedState.d.ts#L10-L17

The main reasoning behind this is that resolved vs. unresolved comments should look the same to the user across a GitHub PR extension, an Azure Dev Ops PR extensions, and any other PR extension. 

There original concern around using "resolved" and "unresolved" is that maybe not all comment provider have those states (maybe they have "viewed" and "unviewed" states for example). To alleviate this, we'll see if we can avoid using "resolved"/"unresolved" language in the UI. If additional states are needed later, we can always add more to the API.

**Comment by alexr00** [comment]
🚀 awesome, looking forward to reviewing it!

Generally, we try to avoid introducing a new color entirely for something like this. The best practice would be to look through the existing color values where we use yellow then use the same yellow, just like is done here where `problemsWarningIcon.foreground` uses the same color as `editorWarning.foreground`:

https://github.com/microsoft/vscode/blob/57174fdbd0813d311e93957532e1e233043dd0a2/src/vs/platform/theme/common/colorRegistry.ts#L525-L526

We'll also do a UX review of this, so the color may end up changing anyway.

**Comment by hermannloose** [comment]
I went for new colors as the comments are conceptually something different than e.g. editor warnings. Currently the comments in the editor use `peekViewBorder` (default blue), so a theme, an extension, or the users themselves would not be able to style comments independently of peek views. I think it makes sense to _base_ the default on another color like `editorWarningForeground` as in your example, so that themes which omit the new colors receive a reasonable default, but it seems like we would give up a lot of flexibility and also clarity if comment widget colors _directly_ used something like `editorWarningForeground` internally?

**Comment by alexr00** [comment]
Yes, basing the color on another is what I meant! I agree that we don't wan to directly use another theme color.

**Comment by alexr00** [comment]
If anyone is eager for this API to be finalized then please comment and let me know how it's working for you. Otherwise, I will plan to finalize later in 2022.

**Comment by circlesmiler** [comment]
This would be very nice to have. We are using Github and especially larger PRs are hard to manage, if there are many comments (in Github as well as in VSCode)

**Comment by violetbrina** [comment]
So is there currently a way to filter resolved/unresolved comments in the sidebar? If not what can I modify currently to provide a visual distinction between resolved/unresolved?

**Comment by alexr00** [comment]
@violetbrina there's a color difference on the icon, but that's currently it. This is the feature request you're looking for https://github.com/microsoft/vscode/issues/150958
