### ISSUE TITLE
Getting started: switching themes is not smooth

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127425]
Getting started view, go to the "Choose the look you want" section:
Click on a couple of themes, notice the following:
* once you click on a theme there is a visual glitch above the theme secion
* the whole theme section jumps a bit up and down

This is particularly visible on the iPad (even though I can reproduce on vscode desktop).
Also on the iPad the theme transition is very slow.

**Comment by JacksonKearl** [comment]
Fixed as #134214
