### ISSUE TITLE
StatusBarItem.tooltip2 codicon don't work in rich hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127433]
Testing #127372

It's called out in the test that it's meant to work but doesn't:

![image](https://user-images.githubusercontent.com/2193314/123789540-1d19ff80-d892-11eb-8a7a-986cbef3938e.png)

Enabling this might just be flipping a switch in the hover code?

Version: 1.58.0-insider (user setup)
Commit: cc528230987ce3ac61fc4f094ae247d5ff24db3c
Date: 2021-06-29T06:27:32.843Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
@Tyriar When creating the MarkdownString, did you set `supportThemeIcons` ?

https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/vscode.d.ts#L2599

**Comment by Tyriar** [comment]
Oh, I looked for that:

![image](https://user-images.githubusercontent.com/2193314/123791768-b21df800-d894-11eb-9285-5ed9e9d341d2.png)

Can we bump the vscode engine version of the status bar example if that's the issue?

**Comment by Tyriar** [comment]
Works with that 👍

**Comment by aeschli** [comment]
Thanks
