### ISSUE TITLE
Enum array setting editor UX

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#127424]
Testing #127176

I don't think that the current UX is ideal. An alternative UX would be one where each option has a checkbox:

![image](https://user-images.githubusercontent.com/1704059/123783983-de566a80-d8ce-11eb-87cd-84aaf547faca.png)

If there are more than 10 options (or some threshold where there would be too many to show) you could use a drop down to show all options with checkboxes.

Any thoughts @misolori?

**Comment by roblourens** [comment]
The order also matters here, would you have a way to reorder them?

**Comment by rzhao271** [comment]
Due to the order mattering, I'm deciding to render the setting as a list of dropdowns, still, but with the following changes:

- Enabling drag and drop while not editing an item
- Not showing values already in the array, noted by the duplicate issue #127414
