### ISSUE TITLE
misleading wording for error message from "vscode.env.openExternal"

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127471]
Testing #127367

I was using `vscode.env.openExternal` to open a file URI with a typo.
As a result I got this alert:

<img width="362" alt="2021-06-29_15-31-54" src="https://user-images.githubusercontent.com/1898161/123806401-3309dd80-d8ef-11eb-86cb-c90a66b22956.png">

IMO the word "anymore" in the detail message is misleading since it implies that the file once existed but now is gone.
And "does not seem" sounds a bit fuzzy given that the computer surely knows better...

**Comment by bpasero** [comment]
@weinand happy for suggestions how to improve the wording 👍

**Comment by weinand** [comment]
Why not just:
> The path '/foo/bar' does not exist on disk.

And if the path can actually be a network path, then we could either broaden "disk":
> The path '/foo/bar' does not exist on this computer.

or leave it out:

> The path '/foo/bar' does not exist.

**Comment by bpasero** [comment]
I think the reason for the original wording was that the dialog would only show when picking a file via File > Open Recent and thus the "anymore on disk" makes a bit more sense. But I have removed that and the details message is now:

`The path '{0}' does not exist on this computer.`

For the remote case, I think @aeschli already changed the wording, which imho is a bit technical:
* title: `URI can not be opened`
* details: `The URI '{0}' is not valid and can not be opened.`
