### ISSUE TITLE
LivePreview.openPreviewTarget duplicates command behavior

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127469]
Testing https://github.com/microsoft/vscode/issues/125855

The setting `LivePreview.openPreviewTarget` appears to duplicate the functionality of the commands "Live Preview: Show Preview", "Live Preview: Show Preview (External Browser)", "Live Preview: Show Preview (External Browser)".

Why do we need a setting and 3 commands?

I think this would make sense to me if the "Live Preview: Show Preview" command was hidden from the command palette (this is the command that is used in menus and such, right?), so that when you run the command from the command palette, you always make an explicit choice about which browser to use. The, the setting can just be about non-command palette entry points.

**Comment by andreamah** [comment]
> I think this would make sense to me if the "Live Preview: Show Preview" command was hidden from the command palette (this is the command that is used in menus and such, right?), so that when you run the command from the command palette, you always make an explicit choice about which browser to use. The, the setting can just be about non-command palette entry points.

Hmm that's a good point! Will make that change.

**Comment by alexr00** [comment]
Thanks for making all these changes!
