### ISSUE TITLE
File -> Open Recent toggles between text editor/custom editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127443]
Testing #127172

When opening a custom file editor with `File -> Open Recent`, it opens a text editor if the custom file is already opened in a custom editor.
When opening the file again, it switches focus back to the custom editor.

![image](https://user-images.githubusercontent.com/2931520/123791565-e5d23f80-d8df-11eb-8579-bfb4f9e13fbf.png)

**Comment by lramos15** [comment]
I believe this was fixed by https://github.com/microsoft/vscode/commit/a651ea4be5bafc9c4d7faf674c799bd35d068582
