### ISSUE TITLE
StatusBarItem tooltip2 consider to introduce max length

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127408]
Testing #127372

Currently there is no max length on the `StatusBarItem.tooltip2`. Also it is not possible for extension authors to influence the line breaks via `\n`. This might be fine, but we could introduce a max length so layouts like this do not happen.

![Screenshot 2021-06-29 at 11 11 53](https://user-images.githubusercontent.com/1926584/123770891-ef9d7800-d8ca-11eb-82be-b2fd17fa963c.png)

**Comment by usernamehw** [comment]
I think markdown hover requires `\n\n` for newlines same as markdown hover in editor/trees.

**Comment by isidorn** [comment]
@usernamehw you are correct, I just tried it out and works as expected. Thanks

**Comment by aeschli** [comment]
In Edge, the native hover is cut after 2000 characters using ellipses. I guess we can do that too.
Probably right in the hover service @Tyriar, what do you think?

**Comment by Tyriar** [comment]
I think we could also truncate based on the size of the container, for example restrict it to a max-height of the min(windowheight, 500px) or something?

**Comment by aeschli** [comment]
@Tyriar That makes sense! The hover can't get bigger than the window anyways, right?

**Comment by Tyriar** [comment]
I don't think the height case was ever covered

**Comment by aeschli** [comment]
Assigning to you as this could be solved for all hovers in the hover service
