### ISSUE TITLE
Test VS Live Server/Preview - toolbar navigation

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#127437]
Testing #127164

In order to reduce the number of tab stops in the workbench, the toolbar of the embedded preview should use the same navigation patterns as other elements of the workbench. Rather than using "tab" to navigate through the toolbar buttons we should be using the left/right arrows. Hitting tab should move to the next tab stop.

**Comment by meganrogge** [comment]
Tab is working for me, but the left and right arrow keys are not.
