### ISSUE TITLE
can't type anymore `«` on a Japanese keyboard with american layout.

### ISSUE THREAD

**Issue by karlcow** [microsoft/vscode#127417]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (1 wk ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Steps to Reproduce:

1. on a macOS with a macbook with a Japanese keyboard. 
2. Choosing the american keyboard.
2. Finder Menu, display the keyboard
3. Open VSCode
4. Open an empty text file
5. Type `Option` + `]` (see on the keyboard visualizer the characters. the key with `]` should display `«`) 

Expected:
The character `«` is added to the text file in vscode

Actual:
Nothing.

PS: 
1. `Option` + `shift` + `]` correctly adds the character `»`
2. Same thing is happening with `Option` + `[` which should add the character `‘` but instead nothing is added.
3. This reproduces with `code --disable-extensions`
4. This started to happen recently, probably at the last update or n-2.

**Comment by karlcow** [comment]
Also the character is perfectly added in all other applications of macos.

**Comment by karlcow** [comment]
It seems to have been captured by "Show Next inline Suggestion"
<img width="836" alt="Capture d’écran 2021-06-29 à 18 52 52" src="https://user-images.githubusercontent.com/505230/123777580-4e82e180-d90b-11eb-8d38-4e4f4d71cc2c.png">

**Comment by karlcow** [comment]
<img width="604" alt="Capture d’écran 2021-06-29 à 18 55 19" src="https://user-images.githubusercontent.com/505230/123778196-d36dfb00-d90b-11eb-87c2-8095c99dd566.png">

**Comment by karlcow** [comment]
ok this is a regression introduced by @hediet

https://github.com/microsoft/vscode/commit/098dfd56e3cbdf406d5207bd522e2604dfa3b0e6

**Comment by hediet** [comment]
Thanks for reporting, I'm sorry for having caused this bug!

It has already been fixed in the latest VS Code Insider build, which will be released as Stable in the next week.

As a workaround, you can redefine these particular shortcuts to trigger the `type` command:
```json
{
    "key": "option+shift+oem_6",
    "command": "type",
    "args": { "text": "«" }
},
{
    "key": "option+shift+oem_4",
    "command": "type",
    "args": { "text": "»" }
}
``

@alexdima I thought this was only problematic when using monaco directly?

**Comment by karlcow** [comment]
Thanks a lot. Wonderful to know that it has been fixed.
