### ISSUE TITLE
Extension debugging: no debug toolbar on second start

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127418]
- open hello world extension in VS Code
- select "Run Extension" from debug dropdown
- press F5
- stop extension by pressing red "Stop" button on debug toolbar
- press F5

Observe: extension starts but no debug toolbar shows up and statusbar doesn't turn orange.
But CALL STACK view shows debug session.

**Comment by isidorn** [comment]
I can reproduce, will investigate today into a fix.

**Comment by weinand** [comment]
some more findings:

after the steps from above:
- set a breakpoint in the hello world extension
- execute the "Hello world" action

Observe:
The debug toolbar comes back:
<img width="540" alt="2021-06-29_15-55-04" src="https://user-images.githubusercontent.com/1898161/123810068-69952780-d8f2-11eb-831c-150eeeed23a7.png">

But it shows a dropdown menu (with one session). This is an indication that there were more than on debug session before.

**Comment by lramos15** [comment]
I see this when debugging vs code too

**Comment by weinand** [comment]
@isidorn do we need to git bisect this?

**Comment by isidorn** [comment]
I did not have time yesterday since I was testing, I will investigate today and provide more details.
Bisect is not needed atm since I have two commits that I think might have caused this. Thanks

**Comment by isidorn** [comment]
This was timing related, I went back to the old shutdown timing, making sure that https://github.com/microsoft/vscode/issues/126211 is still fixed.

**Comment by weinand** [comment]
@isidorn seems to be fixed, thanks!

**Comment by isidorn** [comment]
@weinand thank you
