### ISSUE TITLE
Parsing lots of files asynchronously and in parallel seems to be freezing my extension and VS Code to death. Looking for some help

### ISSUE THREAD

**Issue by Zignd** [Microsoft/vscode#12748]
- VSCode Version: 1.5.3
- OS Version: Windows 10 64-bit

Hi there, I'm the developer behind [HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) and it seems to be causing trouble for lot of people and the reason for that is an issue that I'm failing to find a solution, I come here to ask for help or assistence to resolve this issue. I have been reported several time in many issues here on VS Code repository, but @AurelioDeRosa managed to reproduce the issue and documented the steps [here](https://github.com/Zignd/HTML-CSS-Class-Completion/issues/12#issuecomment-246828941).

I've managed to identify what could might be causing the issue, it basically happens here:

[**src/extension.ts#L36-L63**](https://github.com/Zignd/HTML-CSS-Class-Completion/blob/master/src/extension.ts#L36-L63)

    return async.each(uris, async (uri, callback) => {
        try {
            Array.prototype.push.apply(definitions, await ParseEngineGateway.callParser(uri));
            callback();
        } catch (error) {
            failedLogs += `${uri.path}\n`;
            failedLogsCount++;
            callback();
        }
    }, (error) => {
        if (error) {
            console.error('Failed to parse the documents: ', error);
            return reject(error);
        }

        uniqueDefinitions = _.uniqBy(definitions, (x) => x.className);

        // ...removed to shorten the post

        notifier.notify('zap', 'CSS classes cached (click to cache again)');

        return resolve();
    });

At this point the extension parse the found CSS files in asynchronously and in parallel. During debugging I managed to identify that at the beginning some files manage to get parsed, but then VS Code and the extension freezes. I'd like to understand what I'm doing wrong, so that I can fix the issue, but I have run out of ideas on how to resolve it.

Thanks in advance.

**Comment by mrmlnc** [comment]
Well, I see several ways:

  * Use `fs.readFile` or `fs.createReadStream` instead of `vscode.workspace.openTextDocument`, because it's not needed here.
  * Use `Promise.all` instead of `async/await` and `async.each`, because when I wrote the one-way synchronization of directories module (https://github.com/mrmlnc/syncy), I found out that `Promise.all` faster.

Now I can break your plugin using 160 files (bootstrap + bootstrap.min + foundation + foundation.min + copy).

I can try to solve your problem today.

**Comment by Zignd** [comment]
Oh I see, for some reason I got blind and tried to use only what the API provided to handle the files. I think I can manage to resolve the issue by myself but y will have to wait until I get back from work. Thank you for your suggestions @mrmlnc, I should have asked for help earlier.

**Comment by Zignd** [comment]
I will leave the issue openned until I get it fixed, there's any problem with that?

**Comment by jrieken** [comment]
> extension parse the found CSS files in asynchronously and in parallel

So what do you mean by *in parallel*? In understand you can trigger many async operations (that in parallel at the OS level) but there is no way can process (read parse) their result in parallel as the extension host is a single threaded environment. 

If you have computational intensive work (like parsing) to do, you should *not* do it in the extension host but consider writing a language server.
