### ISSUE TITLE
Can't copy/paste filenames in Explorer

### ISSUE THREAD

**Issue by bodydisplaynone** [microsoft/vscode#127426]
Up until recently I was able to copy/paste anything into explorer view (while renaming).

I mostly used this as follows:
1. Start renaming file with F2
2. Copy file name
3. Paste file name wherever

It worked the other way around too, pasting from a file or any text source into the file name on rename.

However now I get no response and I'm wondering why. Nothing happens.

I tried to use the "Copy file name" extension but it does nothing either. Seems like VS Code has no access to the clipboard when using the explorer, but the editor works fine. Any ideas?

**Comment by isidorn** [comment]
Dup of an issue assigned to @mjbvz 
https://github.com/microsoft/vscode/issues/126458

**Comment by bodydisplaynone** [comment]
Thanks!
