### ISSUE TITLE
Clicking the Port: <number> status bar entry should show a picker with some Live Preview commands

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127472]
Testing https://github.com/microsoft/vscode/issues/125855

I didn't realize I needed to kill the server, I thought just closing the embedded browser would be enough. I tried clicking on the "Port: 3000" status bar entry, but there was no guidance on how to make that status bar entry go away.

It would be nice if clicking on that status bar entry offered to stop the server or showed a picker with "Live Preview" commands.

**Comment by andreamah** [comment]
Good idea! Probably should allow the user to stop the server by closing the status bar entry.

**Comment by alexr00** [comment]
Works great, thank you!
