### ISSUE TITLE
Save All is disabled

### ISSUE THREAD

**Issue by teq-vunguyen** [microsoft/vscode#127481]
Issue Type: <b>Bug</b>

I can't click Save All in File. In spite of I change multi files. This is very inconvenient when you have to save files one by one. Thanks so much.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 8bf36191-6b70-46bc-a860-15b949469e3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-erb-beautify|ali|0.2.0
icons-carbon|ant|0.2.4
unofficial-material-icon-theme|art|0.0.6
beardedicons|Bea|0.11.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
erb|Cra|0.0.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
el-vsc-product-icon-theme|ElA|0.1.8
vscode-great-icons|emm|2.1.79
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.0.1
evondev-snippets|evo|0.2.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
mayukaithemevsc|Gul|2.1.0
helium-icon-theme|hel|1.0.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
easy-icons|jam|0.3.1
vue|jcb|0.1.5
vscode-simple-icons|Lau|1.14.0
vscord|Leo|3.2.3
vscode-language-babel|mgm|0.0.31
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.14.0
remote-containers|ms-|0.183.0
cpptools|ms-|1.4.1
debugger-for-chrome|msj|4.12.12
one-dark-theme|msk|1.9.0
vuejs-extension-pack|mub|1.2.1
file-and-folder-icons|nex|1.0.4
vetur|oct|0.34.1
vue-beautify|pea|2.0.4
material-icon-theme|PKi|4.7.0
material-product-icons|PKi|1.0.4
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
try-material-icon-theme|raf|3.9.0
LiveServer|rit|5.6.1
bootstrap-product-icons|rub|1.0.2
vue-vscode-snippets|sdr|2.2.0
background|sha|1.1.28
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.5.16
autoimport|ste|1.5.4
best-dark-themes-pack|the|1.0.2
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
vscode-import-cost|wix|2.15.0
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3
material-theme|zhu|3.10.14
html-css-class-completion|Zig|1.20.0

(34 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by isidorn** [comment]
This is already covered by an issue assigned to @sbatten
