### ISSUE TITLE
Allow dragging extension from the extension viewlet into the extensions.json file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12745]
- VSCode Version: 1.6.0 - Insider
- OS Version: Windows

Dragging an extension would be cool to add it to the extensions.json. Even copy & paste would help. I now have to know the id which is hard to find and copy. The only place I found for the id was the URL in the browser.

**Comment by dbaeumer** [comment]
I propose doing something here for September. This is very hard to use right now.

**Comment by sandy081** [comment]
Duplicates #12132
