### ISSUE TITLE
Save All does not work with search editors

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127486]
Testing #127355

Opened a few new untitled search editors, did some search in each and tried to Save All. Nothing happens. As if they don't seem to be recognized as changed.

**Comment by bpasero** [comment]
I think this works as designed, a search is only dirty when you change the contents I think.

**Comment by JacksonKearl** [comment]
Yes, a search without changes is still clean. However, running "Save" on it even while clean should still prompt.

**Comment by chrmarti** [comment]
I did search for something in each and each showed some results. Save works, Save All doesn't.

**Comment by JacksonKearl** [comment]
Did you edit the contents of the result buffer? If the results have not been modified it's expected that the editor is not dirty and thus does not participate in the Save All action. Otherwise you get prompted way too much in practice.

**Comment by chrmarti** [comment]
I did not change the result buffer.
