### ISSUE TITLE
Find Next becomes disabled

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127458]
Testing #127173

* preview README.md from our repo
* search for "the"
* press the "next match" repeatedly
* :bug: at one point the command become disable, yet still work

https://user-images.githubusercontent.com/1794099/123802165-461aae80-d8eb-11eb-9419-307b4ecf882e.mov

**Comment by bamurtaugh** [comment]
I also experience this - it perhaps gets triggered more often when I reach the beginning/end of search results:

![recording (24)](https://user-images.githubusercontent.com/25310137/123837073-48671380-d8bf-11eb-95cb-27ec5bf11ead.gif)
