### ISSUE TITLE
"Detected Unusual Line Terminator"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127455]
Testing #127355

Opened a new search editor and searched for foo:

![image](https://user-images.githubusercontent.com/9205389/123801316-7746af00-d8ea-11eb-9db5-4374d4213cd1.png)

It seems unexpected that a dialog would open. Also: It mentions `file ''` which might be a bug with untitled files.

**Comment by chrmarti** [comment]
This is with the VSCode repo open. (It doesn't happen when searching for `bar`, so it might depend on the workspace content.)

**Comment by JacksonKearl** [comment]
@alexdima is there a way I can disable this for a `CodeEditorWidget`?

**Comment by alexdima** [comment]
@JacksonKearl Yes, you can instantiate a `CodeEditorWidget` without the `UnusualLineTerminatorsDetector` contribution (`editor.contrib.unusualLineTerminatorsDetector`). [example](https://github.com/microsoft/vscode/blob/e01106b4ced189ebdb53342c4d4d7e31425c4084/src/vs/workbench/contrib/preferences/browser/preferencesEditor.ts#L1019)

But I would also just recommend that you avoid using `/[\u2028\u2029]/` (`LINE SEPARATOR (LS)` or `PARAGRAPH SEPARATOR (PS)`) intentionally.

**Comment by JacksonKearl** [comment]
Thanks!

I believe the separators are coming from the raw text of the results, so not much I can do about that. I could theoretically filter out the values, but I'd rather keep the results exact in so far as possible.
