### ISSUE TITLE
Rich hover focus outline shows under status bar hovers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127431]
Testing #127372

![image](https://user-images.githubusercontent.com/2193314/123789092-9fee8a80-d891-11eb-860e-bb7db4da2b2d.png)

Caused by padding added in https://github.com/microsoft/vscode/commit/96e6d1c933c315fd98fa1d5f0e96211fcb150124

**Comment by jeanp413** [comment]
Created PR #127603 fixing this
