### ISSUE TITLE
Backspacing Iframe search quickly still highlights a result

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127479]
Testing #127173
1. Search for something
2. Backspace quickly
3. 🐛 The search widget will be empty but the last letter of your search will be highlighted
<img width="750" alt="Screen Shot 2021-06-29 at 10 16 38 AM" src="https://user-images.githubusercontent.com/4544166/123813917-469f4f00-d8c3-11eb-9878-4b2750d4943a.png">

**Comment by bamurtaugh** [comment]
I experienced this as well:

![image](https://user-images.githubusercontent.com/25310137/123837823-24f09880-d8c0-11eb-9945-f468c28b3f3f.png)

I also wasn't typing or backspacing very quickly.

**Comment by bamurtaugh** [comment]
LGTM, marking as verified. LMK if we should change the labels in any other way.
