### ISSUE TITLE
Getting started: "More" button wrong name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127427]
Currently there is a More button at the top of the getting started. This name is misleading because it is not providing anything More to the user, but instead just takes them back to the welcome view.
So I would suggest to rename it to either:
* Back
* Welcome view

Or something other. 

![Screenshot 2021-06-29 at 13 01 14](https://user-images.githubusercontent.com/1926584/123786618-3181ea80-d8da-11eb-97b7-c58790637116.png)

**Comment by JacksonKearl** [comment]
👍 Using "Welcome"
