### ISSUE TITLE
vscode is listerning on port 4001

### ISSUE THREAD

**Issue by myFree** [microsoft/vscode#127496]
Issue Type: <b>Bug</b>

This is quite likely something I've introduced with some setup I've done and forgotten about; but a `code` process is listerning on port 4001; and I'm not aware why, or how to stop it.

```
brent@brent:~$ lsof -i :4001
COMMAND    PID  USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
code    964045 brent   69u  IPv4 11949102      0t0  TCP localhost:4001 (LISTEN)
brent@brent:~$ ps -Flww -p 964045
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
0 S brent     964045   18246  0  80   0 - 12249210 futex_ 312092 16 jun28 ?     00:04:16 /snap/code/67/usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --field-trial-handle=60299279306097406,2622156020567025702,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --disable-gpu-compositing --lang=en-US --enable-crash-reporter=f46eefc0-32cb-4f1f-9fc1-efc9175eff28,no_channel --global-crash-keys=f46eefc0-32cb-4f1f-9fc1-efc9175eff28,no_channel,_companyName=Microsoft,_productName=VSCode,_version=1.57.1 --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --app-path=/snap/code/67/usr/share/code/resources/app --no-sandbox --no-zygote --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=47 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100 --vscode-window-config=vscode:796c000b-63ff-48fb-b142-2118cf151fa7
brent@brent:~$ 
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-77-generic
Remote OS version: Linux x64 5.4.0-77-generic
Remote OS version: Linux x64 5.4.0-77-generic
Remote OS version: Linux x64 5.4.0-77-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3131)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|62.75GB (32.22GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 205183f6-0566-4829-8349-b40996aca137|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container v7labs-darwinpy-localdev (keen_spence)|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3131)|
|Memory (System)|62.75GB (32.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container v7labs-graphotate-backend-localdev (serene_khorana)|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3131)|
|Memory (System)|62.75GB (32.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container v7labs-busybee-localdev (youthful_bardeen)|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3131)|
|Memory (System)|62.75GB (32.22GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container v7labs-wind-localdev (stupefied_blackburn)|
|OS|Linux x64 5.4.0-77-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3131)|
|Memory (System)|62.75GB (32.22GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
vscode-firefox-debug|fir|2.9.4
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
idl|myt|0.3.1
gitlens|eam|11.5.1
elixir-ls|Jak|0.7.0
vscode-docker|ms-|1.14.0

</details>

**Comment by alexr00** [comment]
Do you have something listening on 4001 on your remote machine? We auto forward ports that we detect on your remote. You can see if that's what this 4001 is by opening the Ports view (command Focus: Focus on Ports View).

**Comment by myFree** [comment]
Sorry for taking so long to update. Thanks for the suggestion and indeed that seems to be whats happening. I'm running all my docker containers with `--network=host` - could that be what is causing vs-code to have to use 4001 instead of 4000?

What is the port forwarding needed for?

![Screenshot from 2021-07-22 17-24-07](https://user-images.githubusercontent.com/476578/126674374-8e936186-9447-4cf3-ad3a-ccf0134b26da.png)

**Comment by alexr00** [comment]
The port forwarding is for you so that you can access your remote services locally 😄 you can turn if off if you don't like it (setting `remote.autoForwardPorts`, or just block 4000 by using `remote.portsAttributes`). 

As to why it would use 4001 instead of 4000: there could already be something running on 4000, in which case VS Code will try another port.
