### ISSUE TITLE
Advertise F1 instead of Ctrl+Shift+P to trigger the Command Palette

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127429]
@alexdima told me `Ctrl+Shift+P` is displayed since it is defined after `F1` and the latest keybinding wins.
I think `F1` is much easier to use/learn than `Ctrl+Shift+P`, so it should be shown instead.

![image](https://user-images.githubusercontent.com/2931520/123784378-adc6fe80-d8d7-11eb-8c0e-48af2d840723.png)

I guess this is personal preference though, so I'm fine for keeping it as is if there is a preference for `Ctrl+Shift+P`.

Pinging @isidorn as this is accessibility related.

**Comment by isidorn** [comment]
Yeah I agree here. F1 is much easier to remember and access. This is not personal preference, it is less keys.
Let's assign to @JacksonKearl since he owns the welcome view and that one should advertise simplicity.

Also fyi @sandy081 is it possible that the `keybindingsService` for lookup keybindings returns a keybinding which is string shorter (that is a good signal that it is less complex)

**Comment by IllusionMH** [comment]
While <kbd>F1</kbd> looks much easier it has many different meanings in various applications including editors.
On the other hand <kbd>Сtrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> is more specific for palette in Sublime-like editors and Chromium DevTools.

Also does VS Code intercept <kbd>F1</kbd> in Codespaces?

Not sure if shorter means better, what about `preferred` or `promoted` flag that will mark shortcut that should be displayed in menu or other places?

**Comment by hediet** [comment]
@IllusionMH good points. But I guess advanced users already know about Ctrl+Shift+p and they don't need the hint. I think new users might find F1 easier to use.

> Also does VS Code intercept F1 in Codespaces?

Yes.

**Comment by alexdima** [comment]
> Also fyi @sandy081 is it possible that the `keybindingsService` for lookup keybindings returns a keybinding which is string shorter (that is a good signal that it is less complex)

@isidorn To clarify, I will not tweak this in the keybindings service lookup. The action registration literally has two fields called `primary` and `secondary` so their name are completely semantic. The registration needs to change if `F1` is to be considered the primary keybinding. i.e. https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/workbench/contrib/quickaccess/browser/commandsQuickAccess.ts#L160-L170

**Comment by isidorn** [comment]
@alexdima I thought these are two unrelated registrations, if they are in one place great.
Then we should just change what is `primary` and what is `secondary`.
@TylerLeonhardt  do you mind if we change what is primary and what is secondary keybinding for quick access?

Also fyi @bpasero since he probably introduced it initially

**Comment by bpasero** [comment]
No feelings either way, but F1 is typically to show help and not bring a list of commands.

**Comment by TylerLeonhardt** [comment]
I'm cool with this. I think we should also let our advocates know to advertise F1 over Cmd/Ctrl+Shift+P as well so we don't cause too much confusion.

**Comment by JacksonKearl** [comment]
I'm just asking the keybinding service for the label, I'll receive any changes to the action's registration. cc @bpasero for the change if we decide to go that route. 

One consideration is that in my experience Mac folks with touchbars generally don't know how to use F keys, or if they do it's significantly more of a hassle than Cmd+Shift+P, unless they've enabled F keys by default in touchbar, which most people haven't (again, in my experience).

**Comment by bpasero** [comment]
@hediet ok to close?

> I guess this is personal preference though, so I'm fine for keeping it as is if there is a preference for Ctrl+Shift+P.

👍
