### ISSUE TITLE
Add Item shouldn't propose an item already present in the list

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#127414]
Testing #127176

<img width="631" alt="capture" src="https://user-images.githubusercontent.com/1931590/123772580-3d66b000-d8cc-11eb-8149-eaae90adcd31.png">

**Comment by dbaeumer** [comment]
Same when editing an item

<img width="654" alt="capture" src="https://user-images.githubusercontent.com/1931590/123772805-6be48b00-d8cc-11eb-9871-ac68402c0f49.png">

**Comment by stevencl** [comment]
Agreed. It shouldn't be possible to get to this state:
![image](https://user-images.githubusercontent.com/1704059/123774169-122c9280-d8c5-11eb-8876-0f0527cd7edd.png)

Shouldn't this just be three checkboxes, one for each option?

**Comment by rzhao271** [comment]
The order of the items matters for this setting. Something I plan on doing is adding up/down buttons to the side next to the edit button, which users can use to rearrange the items. Afterwards, I can change the proposals to not repeat.
Otherwise, rendering the items as a list of checkboxes works.

**Comment by rzhao271** [comment]
Closing in favour of #127424.
