### ISSUE TITLE
Search editor's not in recent history

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127468]
Testing #127355

Open and close a `.code-search` file and it is not listed in the recent files history.

**Comment by chrmarti** [comment]
Same for GitHub issue notebooks. `.png` opened with Luna Paint do show up.

**Comment by bpasero** [comment]
We only add to the list of File > Open Recent when you use a file dialog. Did you in all cases?

**Comment by chrmarti** [comment]
Retried when opening from the Explorer and now it works. Not sure what happened. Ok to close for me unless you think there is something to go after still.
