### ISSUE TITLE
Goto line and relative line numbers. Usability issue

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12741]
- VSCode Version: 1.6.0 - insider
- OS Version: Windows

Steps to Reproduce:
1. Enable relative line numbers
2. Press Ctrl+G
3. I expect the line numbers to become non relative right away

**Comment by BillDenton** [comment]
How do you enable relative line numbers?
Shouldn't relative numbers into goto line numbers to directly available. Couldn't <line number> go to that absolute line number, +<number> go <number> lines further down the file, -<number> go <number> lines up the file.
