### ISSUE TITLE
Unclear Terminology: Settings / Preferences / Configure / Customize

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127419]
Testing #127319.

We now use the terms `Settings`, `Preferences`, `Configure` and `Customize` in commands.
They all refer to the same thing, which makes searching for the right Command hard.

Also see #95202.

**Comment by sbatten** [comment]
Similar to https://github.com/microsoft/vscode/issues/127303

**Comment by sbatten** [comment]
probably needs a solution with better command palette search since the names are what they are for a while
