### ISSUE TITLE
Debug Map: weird value changed indication

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12746]
Windows 10

See the little blue in the picture below:

![image](https://cloud.githubusercontent.com/assets/900690/18870685/2054fd82-84b2-11e6-8b75-44ab3937547a.png)

I was expanding a large Map and noticed the changed decoration appearing. The code is:

```
        var myMap = new Map();

        var keyString = "a string",
            keyObj = {},
            keyFunc = function () { };

        // setting the values
        myMap.set(keyString, "value associated with 'a string'");
        myMap.set(keyObj, "value associated with keyObj");
        myMap.set(keyFunc, "value associated with keyFunc");

        for (var i = 0; i < 100000; i++) {
            myMap.set(i, "this is entry with: " + i);
        }
```

**Comment by isidorn** [comment]
September to investigate

**Comment by isidorn** [comment]
Can not reproduce both on win10 and both on OS X.
Do you see this regularly?

**Comment by bpasero** [comment]
@isidorn also do not see it anymore, fine to close for nw.
