### ISSUE TITLE
Bad experience editing complex setting in settings.json

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127452]
I see a few paper-cuts in this whole thing:

- The bogus `"pub.name": false` key-value pair gets inserted.
- The suggestions are text-only so they should not come up at all.
- The indentation on line 160 is wrong.

![recording](https://user-images.githubusercontent.com/22350/123800397-1c876600-d89e-11eb-92d8-ef53612efa36.gif)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/101822
