### ISSUE TITLE
Changing content in iFrame search cancels search

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127482]
Testing #127173

1. Search for a word in an iframe
2. Change the iframe (in this case the markdown underlying the markdown preview)
3. 🐛 All results are cleared. To match text it should keep the results and run the search again

**Comment by lramos15** [comment]
This occurs as well if you switch from one markdown preview to another one

**Comment by rzhao271** [comment]
It's worse than I expected. If I type in the text editor to change the content, and re-start another search as the content changes, because the search currently depends on focusing the iframe, focus is pulled away from the text editor to the preview iframe.

**Comment by rzhao271** [comment]
Labelling this issue as a feature request, since the behaviour is the same right now for webviews.

**Comment by bpasero** [comment]
I would actually close this as wontfix or mark as upstream because the same behaviour can be seen in Chrome as well.

**Comment by rzhao271** [comment]
@bpasero can you provide an example gif? I don't have a Fiddle for replicating the issue on Chrome.

**Comment by bpasero** [comment]
@rzhao271 I just played around with using devtools to literally change the text of an element in the page while search was active and it cleared the search.

**Comment by rzhao271** [comment]
Closing as a wontfix.
