### ISSUE TITLE
Global search stops working after a while

### ISSUE THREAD

**Issue by janhancic** [Microsoft/vscode#12743]
- VSCode Version: 1.5.3
- OS Version: OS X 10.11.6 (El Capitan)

Steps to Reproduce:

1. Open search sidebar
2. Enter search term
3. do a search

Sometimes vscode will do a search, you can see the progress bar progressing, but then it stops about 10 pixels before the end and no results show up. If I restart vscode and perform the same search again it finds things just fine.

I've also noticed that search is really slow in general (I have a beefy mac book pro), which is really annoying with quick open (`cmd+p`) as it can take more than half a minute to find a file that way. Even if I type in the exact filename (sublimetext is instantaneous on the same project (with less folders excluded) and I feel it does better fuzzy matching).

Our project is relatively big, but I've excluded almost everything so I'm only dealing with about 3000 files (mix of JS, python, java, protobufs, less, images, etc).

Happy to provide more details if you need them.

**Comment by adamshone** [comment]
I'm experiencing the same issue but on Ubuntu 14.04, same vscode version.

**Comment by adamshone** [comment]
I had a look into this, and it seems like every time you do a search VS Code kicks off a `find` process in the root folder:

```
[:~/core] master+* $ ps -ef | grep find
adam     28586 26265  2 10:06 ?        00:00:08 find -L . -type f
adam     29087  3728  0 10:10 pts/10   00:00:00 grep --color=auto find
```
If you do multiple searches you end up with many of these processes...
```
[:~/newcore/core] master+* $ ps -ef | grep find
adam     28586 26265  2 10:06 ?        00:00:08 find -L . -type f
adam     29148 26265 10 10:11 ?        00:00:01 find -L . -type f
adam     29149 26265 12 10:11 ?        00:00:01 find -L . -type f
adam     29150 26265 15 10:11 ?        00:00:01 find -L . -type f
adam     29154 26265 17 10:11 ?        00:00:01 find -L . -type f
adam     29155 26265 34 10:11 ?        00:00:02 find -L . -type f
adam     29156 26265 26 10:11 ?        00:00:01 find -L . -type f
adam     29157 26265 38 10:11 ?        00:00:02 find -L . -type f
adam     29158 26265 30 10:11 ?        00:00:01 find -L . -type f
adam     29159 26265 39 10:11 ?        00:00:01 find -L . -type f
adam     29161 26265 55 10:11 ?        00:00:01 find -L . -type f
adam     29165  3728  0 10:11 pts/10   00:00:00 grep --color=auto find
```
I haven't yet checked if these processes ever terminate, but in my repo at least they will take a very long time, due to all the files in `node_modules` etc which exist on the filesystem but are excluded in the editor.

One interesting thing is that after a while the quick search does start working, and although it still kicks off a `find` process it returns the results almost instantly - I guess it has the `find` result cached and does not need to wait for the process to return?

There seem to be a number of bugs here:

* it would be much more efficient if the `find` command respected the exclude patterns rather than find everything and apply the exclude patterns afterwards.
* the editor probably should not leave the previous `find` processes running if you do a new search, could it kill the previous `find`?
* if the quick search is going to use the cached result, there is no need to kick off a `find` process.

**Comment by janhancic** [comment]
On my system (OSX) it kick offs several (identical) `find` processes every time I hit `cmd+P` which also seems like a bug.

**Comment by chrmarti** [comment]
@adamshone These issues should be fixed in 1.6-insders. Let me know if you give that a try.

**Comment by adamshone** [comment]
@chrmarti yep, seems to work fine in that version! We can close this if @janhancic is happy with it.

**Comment by chrmarti** [comment]
Thanks @adamshone. @janhancic is reporting a different issue. I will keep this issue open to track that.

**Comment by janhancic** [comment]
Been using the insiders version for a couple of hours now and haven't experienced the same problem. Feel free to close, and I'll re-open if it starts happening again.

Thanks @chrmarti !

**Comment by chrmarti** [comment]
Thanks @janhancic

**Comment by janhancic** [comment]
I'm afraid I have to reopen this as it started happening again. I'm using the latest insiders version. Restarting fixes the problem, but after a while search stops working.

**Comment by chrmarti** [comment]
@janhancic What are your "files.exclude" and "search.exclude" patterns?

**Comment by janhancic** [comment]
I've obfuscated project names just in case, otherwise this is directly from my workspace config (I don't have anything in my user settings):

```
"files.exclude": {
      "**/.git": true,
      "**/.DS_Store": true,
      ".plz-cache/**": true,
      "sub_project1/**": true,
      "sub_project2/**": true,
      "sub_project3/**": true,
      "logs/**": true,
      "sub_project4/**": true,
      "sub_project5/**": true,
      "sub_project6/**": true,
      "sub_project7/**" : true,
      "sub_project8/**": true,
      "plz-out/**": true,
      "sub_project9/**": true,
      "sub_project10/**" : true,
      "sub_project11/**": true,
      "sub_project12/**": true,
      "**/.history/**": true,
      "**/.vscode/**": true,
      "common/go/**": true,
      "common/java/**": true,
      // stuff I might need
      "sub_project13/**": true,
      "config/**": true,
      "sub_project14/**": true,
      "sub_project15/**": true,
      "sub_project16/**": true,
      "sub_project17/**": true,
      "sub_project18/website/react_native/**": true,
      "sub_project18/website/frontend/apps_native": true
  }
```

I don't have `search.exclude` as I understand it inherits from `files.exclude`.

**Comment by chrmarti** [comment]
That's correct. Your patterns by-pass one of our optimizations, I will look into improving that. In the meantime you could try updating all `"sub_project8/**"`-like exclusion patterns to `"**/sub_project8"` (if that doesn't exclude more than you want in your particular case). Let me know if that makes a difference.

**Comment by janhancic** [comment]
I'll change my config and run with that for a while. Unfortunately I can't do it for all of them (one of the projects is imaginatively called "notifications").

**Comment by janhancic** [comment]
Hi @chrmarti unfortunately this is still happening. I have to restart my editor every couple of hours to get proper search support (love it otherwise).

**Comment by chrmarti** [comment]
@janhancic Are you referring to the global search or QuickOpen or both?

**Comment by janhancic** [comment]
Both.

**Comment by chrmarti** [comment]
Could you, when this happens again, open the Dev Tools from the Help menu and copy their console's content here?

**Comment by janhancic** [comment]
Ok I think we can close this again, as it hasn't happened in a few days now ... :)
