### ISSUE TITLE
Newly installed C++ extension doesn't provide a walkthrough

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#127401]
Testing #127384

I installed the C++ extension assuming it provides a walkthrough from the screenshot in the test plan item. However it doesn't  present a walk through

<img width="978" alt="capture" src="https://user-images.githubusercontent.com/1931590/123767608-e5c64580-d8c7-11eb-9d34-60d799aa5ba9.png">

**Comment by dbaeumer** [comment]
Worked with Luna Paint.

**Comment by JacksonKearl** [comment]
C++ walkthrough is still controlled by an experiment.
