### ISSUE TITLE
Does the "don't show again" action on the loose file notification need to be followed by another notification?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127465]
Testing https://github.com/microsoft/vscode/issues/125855

I opened a non-workspace file and started a preview. I got the loose file notification ✅

Then I got this notification:
![image](https://user-images.githubusercontent.com/38270282/123805089-11f4bd00-d8ee-11eb-864b-33303414fda6.png)

Is this a pattern we follow elsewhere? @isidorn you might know this.

**Comment by isidorn** [comment]
Please no multiple notifications :)
There should be another way to achieve this.

**Comment by andreamah** [comment]
I can just omit the second notification if that's better UX

**Comment by isidorn** [comment]
@andreamah I am not 100% sure what is the scenario here, but in general in VS Code we try not to notify users that something got saved, or there has been a modification in settings. Most of the time this just works automatic and users should not be notified. So removing the notification seems like the way to go here.
