### ISSUE TITLE
Goto line with relative line numbers renders wrong lines

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12742]
- VSCode Version: 1.6.0 - insider
- OS Version:

Steps to Reproduce:
1. enable relative line numbers
2. go to the end of a big file
3. Ctrl+G
4. type 8
   Observer: line 8 is revealed, but the line numbers show:

![capture](https://cloud.githubusercontent.com/assets/1931590/18869862/7fbf62d4-84ae-11e6-971e-500b4ff086e6.png)

which is very confusing.

**Comment by dbaeumer** [comment]
Could be fixed by turning into absolute lines numbers when Goto line is activated. Alternatively Goto line could behave relative for relative line numbering. For example -200 to go 200 lines up.

**Comment by alexandrudima** [comment]
Let's track the relative go to line feature request in the comment in #14162

This issue is resolved with the fix for #12741 .i.e. it no longer is confusing to use go to line when having relative line numbers configured.
