### ISSUE TITLE
Disable suggestions in debug console

### ISSUE THREAD

**Issue by adchan11** [microsoft/vscode#127492]
Is there a way to disable these suggestions in the debug console when you type?

![image](https://user-images.githubusercontent.com/82629083/123824945-77d04d00-d8cc-11eb-8513-8fbb95c07101.png)

**Comment by isidorn** [comment]
No this is currently not possible.
However this is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by weinand** [comment]
In the July release suggestions will not automatically be inserted when pressing "Enter" (only on "Tab"). Maybe that helps already...

**Comment by isidorn** [comment]
Yes this should behave better now, since the suggestions are not so aggressive (you can hit enter to evaluate and not accept them). Closing this as no action is planned here
