### ISSUE TITLE
StatusBarItem tooltip2 overwrite tooltip

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127402]
Testing #127372

Have the following extension code snippet

```
myStatusBarItem.tooltip2 = 'zurich';
myStatusBarItem.tooltip = 'hello';
```

Run your extension and hover over you status bar item and notice how only "zurich" is shown, not "hello".
So we should either merge the two, or improve the `vscode.d.ts` docs since now it says that it will be "merged". We should say "overwrite" if that is what is happening.

**Comment by aeschli** [comment]
In the future there will only be `tooltip: string | MarkdownString`.

`tooltip2` is only there for technical reasons as in `vscode.proposed.d.ts` you can redefine an existing property.

**Comment by isidorn** [comment]
Then this makes good sense, feel free to close as designed.
