### ISSUE TITLE
Description for "startEntries" has backticks in it

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#127400]
Testing #127383

![image](https://user-images.githubusercontent.com/38270282/123767349-ae579900-d8c7-11eb-891d-4549864e56cd.png)

Since "Welcome: New..." isn't code, it seems like it should be in double quotes, not backticks (and if you did want to go with backtick then it should probably be displayed as markdown).

**Comment by JacksonKearl** [comment]
\closedWith 055ac27d6cd8f63e98770205ffced9f473fffd8e

**Comment by alexr00** [comment]
Added labels so that I remember to verify this :)
