### ISSUE TITLE
Code complete in empty extensions.json not very helpful

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#12740]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1.  Create empty recommendation file
2.  Activate code complete
3. You get

![capture](https://cloud.githubusercontent.com/assets/1931590/18869607/584e580a-84ad-11e6-9b0b-c33597f9b416.png)

We should either show proper code assist or put an example in as a comment. Only having the link to the documentation is not very useful.

I know that the json schema supports snippets. So we can add a snippet as well for a 'default' extension

**Comment by sandy081** [comment]
We already show the example when hovering on `recommendations` property. I agree it is not enough. 

- Added an example as comment 
- Also a default example snippet 

But IMO, providing intelli-sense / completion proposals for extensions would be lot helpful. This can also be used in the extension package.json.
