### ISSUE TITLE
StatusBarItem.tooltip2 command links don't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127435]
Testing #127372

```
(myStatusBarItem as any).tooltip2 = new vscode.MarkdownString('([test](command:vscode.newWindow)) $(zap) blah');
```

Results in:

![image](https://user-images.githubusercontent.com/2193314/123789722-53577f00-d892-11eb-80dc-eaf6a9062583.png)

**Comment by aeschli** [comment]
@Tyriar Note that the Markdown string needs to be trusted..
https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/vscode.d.ts#L2586

**Comment by Tyriar** [comment]
Works, thanks
