### ISSUE TITLE
StatusBarItem custom hover: click on hover produces UI glitch

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127413]
Testing #127372

Have an extension that adds a statusBarItem with a tooltip2. 
Run the extension
Hover over your item, click on the hover -> notice small black lines (visual glitch) below the hover

Bonus bug: right click on hover selects words using native selection.

![Screenshot 2021-06-29 at 11 16 26](https://user-images.githubusercontent.com/1926584/123771625-80745380-d8cb-11eb-8ca0-06ac4a13f187.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/127431

If you're on mac I think the right click thing is OS standard behavior I think?

**Comment by isidorn** [comment]
@Tyriar you are right regarding right click
