### ISSUE TITLE
Binary and octal numbers are not coloured

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1274]
![image](https://cloud.githubusercontent.com/assets/22350/11783064/5a20e41a-a275-11e5-85c1-d4a1aa7feb46.png)

**Comment by aeschli** [comment]
Problem of the grammar.
The scopes we get for the 3rd and 4th number is `token block decl function meta js`

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#28
