### ISSUE TITLE
VS Code's maximize button doesn't trigger Snap Layouts in Windows 11

### ISSUE THREAD

**Issue by just1a-person** [microsoft/vscode#127449]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Microsoft Windows [Version 10.0.22000.51]

Steps to Reproduce:

1. Open VS Code in Windows 11 with above mentioned build.
2. Hover over the maximize button

*Snap Layouts doesn't get triggered because VS Code is using a custom title bar*

![Hovering over maximize button, screenshot](https://user-images.githubusercontent.com/75578443/123795731-f09dcc00-d901-11eb-82cd-8faf4012bdf5.png)

**Comment by sbatten** [comment]
@deepak1556 if electron adopts the windows controls overlay and I adopt it in the titlebar, we could handle this I think

**Comment by deepak1556** [comment]
Depends on https://github.com/electron/electron/pull/29600

**Comment by Navpan18** [comment]
Snap layout is working when i switched my title bar type from custom to native in vs code

**Comment by esimkowitz** [comment]
Any update on this issue now that the upstream electron issue is merged and released circa 13.x.x?

**Comment by sbatten** [comment]
While the upstream branch was merged, the implementation of window-controls-overlay on Windows still has issues. e.g. a persistent bottom border, the icons do not match system icons on Windows 11, and the color is not dynamically settable.

![image](https://user-images.githubusercontent.com/6561887/139699336-eeb3c99f-b79e-4f83-9362-86d9b0520f3c.png)

**Comment by yume-chan** [comment]
@sbatten The bottom border was reported in electron/electron#31025.

The background color can be changed dynamically  by set `titlebarOverlay.color` to transparent and put a div underneath it.

![image](https://user-images.githubusercontent.com/1330321/140006241-adfcbe64-3608-4d86-b7bc-09f8c3b67690.png)

The symbol (_□×) color truly can't be changed dynamically, and Electron doesn't correctly draw hover color for transparent buttons now

![image](https://user-images.githubusercontent.com/1330321/140006417-43d33cfb-4c93-4547-95c0-6a98b8c23bee.png)

**Comment by 401-Unauthorized** [comment]
In VS code on Windows 11 snap layouts

Works normally with - "window.titleBarStyle": "native"
Does not work with   - "window.titleBarStyle": "custom"

Refer to:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu

**Comment by zhiyong80** [comment]
@401-Unauthorized This worked on my setup.

**Comment by nonintanon** [comment]
@401-Unauthorized thanks! it works.

**Comment by JorisWijgert** [comment]
Also, if you still prefer to use the custom title bar style, you can also use <kbd>Win</kbd> + <kbd>Z</kbd> to open the Snap Layouts

**Comment by sanamhub** [comment]
Yes, I was going to create this issue, eventually I find it here while searching is created already.

**Comment by Teknath-jha** [comment]
> Yes, I was going to create this issue, eventually I find it here while searching for duplicate

save me
