### ISSUE TITLE
scroll horizontally with mouse not working in debian gnu/linux fluxbox

### ISSUE THREAD

**Issue by ZiTAL** [microsoft/vscode#127475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 507ce72a4466fbb27b715c3722558bb15afa9f48 x64
- OS Version: Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
window manager: Fluxbox 1.3.5

Steps to Reproduce:

1. try to scroll horizontally with mouse
2. https://i.imgur.com/MeUPbIM.mp4 (sorry can't upload video to github)

**Comment by rebornix** [comment]
@ZiTAL can you try open https://microsoft.github.io/monaco-editor/ in chromium or firefox and see you can reproduce this issue in the standalone monaco editor?

**Comment by ZiTAL** [comment]
In firefox and chromium works fine

**Comment by ZiTAL** [comment]
in 1.60.1 still not working, What kind of information can help?

**Comment by ZiTAL** [comment]
I'm sorry but the problem persists in 1.63.2 version, I don't know what else I can add.
