### ISSUE TITLE
Bad defaults for media object in step of a walkthrough contribution

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#127450]
https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStartedExtensionPoint.ts#L54 and https://github.com/microsoft/vscode/blob/339ff8d463fd9ecd769138bd9f23f1887da627aa/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStartedExtensionPoint.ts#L76 insert two deprecated properties of the media object of a walkthrough step.

**Comment by JacksonKearl** [comment]
Good catch thanks! 

\closedWith 09f318ac357548c4b3212fb50c894dbf6cfb6b30

**Comment by TylerLeonhardt** [comment]
@gjsjohnmurray would you like to verify this one?
