### ISSUE TITLE
No separation between label and detail

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#127494]
Testing #127333

Using:

```
const simpleCompletion = new vscode.CompletionItem({ label: 'label', description: 'description', detail: 'detail'});
```

I expected there to be a space between the label and detail. 
![recording (10)](https://user-images.githubusercontent.com/29464607/123827848-d4743d80-d8b5-11eb-86ae-475abcfd0298.gif)

**Comment by meganrogge** [comment]
I see this is specified in the docs, so probably is as-designed. Why was this choice made?

**Comment by jrieken** [comment]
Yeah, closing as designed
