### ISSUE TITLE
StatusBarItem.tooltip2 hovering the status bar item again results in the hover re-rendering

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127436]
Testing #127372

See the flickering:

![recording (29)](https://user-images.githubusercontent.com/2193314/123790088-c7922280-d892-11eb-9ce5-ccb52c0dbf99.gif)

Related to composite mouse tracker:

https://github.com/microsoft/vscode/blob/96e6d1c933c315fd98fa1d5f0e96211fcb150124/src/vs/workbench/services/hover/browser/hoverWidget.ts#L423-L423

**Comment by bpasero** [comment]
I think this doesn't happen anymore for me, at least when trying with the new language status indicator.

**Comment by Tyriar** [comment]
Might still happen for extension API.
