### ISSUE TITLE
Syntax Highlight w/ Perl, Comment Not Detected After 'sub'

### ISSUE THREAD

**Issue by mebouck** [microsoft/vscode#127467]
Issue Type: <b>Bug</b>

A comment after a subroutine definition isn't detected, for example:

    sub getPi  # calculate and return the value of pi

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.10GB free)|
|Process Argv|--crash-reporter-id 6d724ebe-c32e-4348-8853-6a2057864cf0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
kixtart|cya|0.0.1
autoit|Dam|1.0.6
perl-syntax|jac|0.0.7
vscode-dotnet-runtime|ms-|1.1.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
powershell|ms-|2021.6.2
azurerm-vscode-tools|msa|0.15.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by alexr00** [comment]
Moved to the upstream repo that we pull our perl syntax highlighting grammar from: https://github.com/textmate/perl.tmbundle/issues/48
