### ISSUE TITLE
Can't format typescript code with tabs (latest insider build)

### ISSUE THREAD

**Issue by mainnika** [Microsoft/vscode#12747]
- VSCode Version: Code - Insiders 1.6.0-insider (1dccf027b24d3b83f471c3cc9d938af6c27e764e, 2016-09-27T06:09:54.324Z)
- OS Version: Windows_NT ia32 10.0.14931

Steps to Reproduce:

1. Open any of .ts file, that already uses tabs for indentation
2. Choose «Format Code (Alt Shift F)»

Expected behaviour: code must be formatted using tabs
Actual behaviour: spaces are used instead of tabs

GIF: http://i.imgur.com/qW3mBaF.gifv

**Comment by mrmlnc** [comment]
Confirm.

<details><summary>GIF</summary>![2016-09-27_14-20-04](https://cloud.githubusercontent.com/assets/7034281/18871308/852fb4f8-84bd-11e6-89af-99de1b7a2646.gif)</details>

**Comment by dbaeumer** [comment]
@waderyan pretty sure I addressed this today. If you try it use master or a build from tomorrow.

**Comment by waderyan** [comment]
Confirmed this is fixed in the build today.
