### ISSUE TITLE
Unable to type after attaching to terminal

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#127582]
Testing #127195

I'm testing on Ubuntu client using PowerShell as my shell.

Steps:
* run this code:
```pwsh
Start-Sleep -s 5
```
or using the sleep native command (but still in PowerShell):
```
sleep 5
```
* Detach the session immediately
* wait 6 seconds to give sleep the chance to be done
* Reattach the session
* I can no longer type at the prompt 

Notes:

This doesn't repro in bash.

**Comment by Tyriar** [comment]
I can't repro in wsl/ubuntu, I don't see why this would happen tbh. Can you enable escape sequence logging to see if anything is sent/received when typing?

**Comment by TylerLeonhardt** [comment]
Also repro's on macOS with PowerShell.

![image](https://user-images.githubusercontent.com/2644648/124034432-0c5fab80-d9b0-11eb-978f-3558d78dfed3.png)

* I typed `Start-Sleep -Seconds 5`
* cleared the dev tools 
* hit ENTER (all the contents of dev tools was spit out)
* detached
* waited
* attached

same issue as above

**Comment by TylerLeonhardt** [comment]
Doesn't repro in zsh on macOS both using sleep and a really long loop

**Comment by Tyriar** [comment]
I could repro on macOS too just now, the curious thing is parsing data in response to the typing but  it's not resulting in anything:

<img width="282" alt="Screen Shot 2021-07-06 at 12 10 50 PM" src="https://user-images.githubusercontent.com/2193314/124654370-508cf900-de53-11eb-8451-554e96e07321.png">
<img width="458" alt="Screen Shot 2021-07-06 at 12 11 43 PM" src="https://user-images.githubusercontent.com/2193314/124654389-5551ad00-de53-11eb-9a35-5d9ff5c94aa4.png">

**Comment by Tyriar** [comment]
I can only reproduce this when I have devtools opened.

This is what is sent from the ptyhost when it works (no reload):

<img width="418" alt="Screen Shot 2021-07-23 at 7 16 02 AM" src="https://user-images.githubusercontent.com/2193314/126795284-03cd4320-8b59-46c8-b6ee-8915e8c421b5.png">

And this when it doesn't work (devtools opened, reload):

<img width="447" alt="Screen Shot 2021-07-23 at 7 16 36 AM" src="https://user-images.githubusercontent.com/2193314/126795324-547bf572-f25d-44d0-aaa5-5e752a9dfc3c.png">

**Comment by Tyriar** [comment]
Writes end up reaching the pty host still, just onData doesn't fire

**Comment by Tyriar** [comment]
I looked into this and it appears to be some weird interaction with pwsh/electron where the socket stops writing when reloaded but only when devtools is open. I don't think there's anything to fix this on my end plus no other reports
