### ISSUE TITLE
**Bug** Change keyboard shortcut for multi Select Modifier

### ISSUE THREAD

**Issue by ProgrammerAuditore** [microsoft/vscode#127584]
When I change the keyboard shortcut like this:
"workbench.list.multiSelectModifier": "Ctrl+Shift"
It does not work.

**Comment by joaomoreno** [comment]
We only support two values here:

![image](https://user-images.githubusercontent.com/22350/123920062-d7d6fa00-d985-11eb-85e3-31f92753d419.png)
