### ISSUE TITLE
Terminals don't re-appear when closing and re-opening workspace

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#127506]
Testing #127192

1. Open an editor terminal.
2. Close the current folder.
3. Re-open the folder.
4. The editor terminals are present for a second, then disappear.

https://user-images.githubusercontent.com/31675041/123838232-0347df00-d8c9-11eb-8250-7b642dafecfa.mp4

**Comment by Tyriar** [comment]
This is working as designed, supporting reconnect across restarts or folder closes would be new feature work
