### ISSUE TITLE
I can't use format!

### ISSUE THREAD

**Issue by thunderning** [Microsoft/vscode#12753]
- VSCode Version:

Steps to Reproduce:

I use the C/C++ extension but the function "Format code" can't be used! I have set the right path in the user setting , but it still can't work. And I have tried Ubuntu Linux as well, but nothing happened. In addtion, this extension  makes the other format extension unusable. Please fix it soon

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.
