### ISSUE TITLE
Centered layout fixed width

### ISSUE THREAD

**Issue by JSRossiter** [microsoft/vscode#127569]
When using centered layout it would be nice to have the option to keep a fixed width. I switch my window between maximized, 1/2 screen width and 1/3 screen width regularly and it's not possible to set a width that is usable at 1/3 and accomplishes the purpose of centering when maximized.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by akbyrd** [comment]
Dupe of https://github.com/microsoft/vscode/issues/54731 which is still open and has more traction.
