### ISSUE TITLE
default light colors `list.focusHighlightForeground` too close to `list.activeSelectionBackground`

### ISSUE THREAD

**Issue by maxwell719** [microsoft/vscode#127597]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 and Insiders
- OS Version: Windows 10

Hi, I'm writing an extension contributing a theme.

package.json
```json
"themes": [
      {
        "label": "my theme",
        "uiTheme": "vs",
        "path": "./themes/my-color-theme.json"
      }
]
```
my-color-theme.json
```
{
  "name": "my theme",
  "semanticHighlighting": true,
  "semanticTokenColors": {
    "keyword": { "foreground": "#00f" }
  }
}
```

I only want to provide some semantic token colors and don't have any workbench colors. It works well inheriting default light theme until 1.57, probably by #122893

I know I can add `list.focusHighlightForeground` in my theme to bypass this. But I'd like to simply inherit all default colors.

Steps to Reproduce:

1. Open command palette and type to filter
![image](https://user-images.githubusercontent.com/52692178/123897782-0925da80-d932-11eb-8ec7-a819242354fb.png)

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/commit/97a719dd9b6f56ae724df1beb79944596d998eb6 added `"list.focusHighlightForeground": "#9DDDFF"` to `light_vs.json`. I think this should have gone directly in the default for `list.focusHighlightForeground`

Note, `light_vs.json` should not contain much colors, as our light defaults already reflect our light theme.

**Comment by misolori** [comment]
> I think this should have gone directly in the default for list.focusHighlightForeground

This was intentionally only added to our light theme (and not as the default) because this broke with nearly all light themes in the marketplace.

**Comment by aeschli** [comment]
Currently all light theme that don't define `l









ist.highlightForeground" (or `list.focusHighlightForeground

**Comment by aeschli** [comment]
Here's what I see when changing the light default of listHighlightForeground to `9DDDFF`

![recording](https://user-images.githubusercontent.com/6461412/124293281-c98c0800-db56-11eb-8b99-26d30e00f3bf.gif)

**Comment by aeschli** [comment]
Need to look at this with @misolori.
There's no easy restoring of the old state, and we need to discuss what's the direction forward.

**Comment by aeschli** [comment]
New attempt:

![recording (1)](https://user-images.githubusercontent.com/6461412/124632574-c3629800-de84-11eb-954d-68a21f04149a.gif)

The default of `list.focusHighlightForeground` is now:
- if the theme defines `list.activeSelectionBackground` it is `list.highlightForeground`
- else `#9DDDFF`

This comes from the observation that existing themes that modified `list.activeSelectionBackground` made it work with `list.highlightForeground`.
