### ISSUE TITLE
Handlebars: if-else-statements no longer colored

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12751]
Testing #12100 

I am no longer seeing if-else-statements colored any different using handlebars:

![image](https://cloud.githubusercontent.com/assets/900690/18873542/43f540f4-84c0-11e6-9d19-f8222c20ef79.png)

**Comment by bgashler1** [comment]
<img width="242" alt="screen shot 2016-09-28 at 5 41 39 pm" src="https://cloud.githubusercontent.com/assets/11839736/18937195/e70d8f84-85a2-11e6-84cc-2aec77c84078.png">
Block helpers in general aren't getting highlighted.  If and else are examples of those.

**Comment by aeschli** [comment]
{{ and }} are no longer colorized. They were colorized by accident (due to the flattening of scopes, now fixed (#3008).

The #if #else words are marked as support.constant, which we don't colorize.
