### ISSUE TITLE
Running task with "terminal.integrated.defaultLocation": "editor" does show task terminal

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#127509]
Testing #127192

Steps:
1. Set `"terminal.integrated.defaultLocation": "editor"` in settings
2. Run the `custombuildscript 32` task from the task extension sample (or any custom task).
3. The pseudoterminal does not appear anywhere.

It seems that the task is still running since the live server turns on with the live server task, but I'm not seeing any terminal popping up.
https://user-images.githubusercontent.com/31675041/123839537-7867e400-d8ca-11eb-8ee7-cb83bc800385.mp4

**Comment by Tyriar** [comment]
It looks like it is being created still, just not in the editor. Tasks just don't respect this setting currently. fyi @alexr00

**Comment by TylerLeonhardt** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/2644648/124198007-9c6f2500-da84-11eb-98b4-47fe9e4316be.png)
