### ISSUE TITLE
Updating machine settings does not update ports view

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#127579]
Testing #127331

Similar to #127577, updating the machine settings does not update the ports view. Here I changed port `8000` to `9000` in the machine settings, and then also added another port from the port view.

![image](https://user-images.githubusercontent.com/35271042/123873199-fcca5f00-d8ea-11eb-8e47-838a4a1a7e7d.png)

**Comment by alexr00** [comment]
The `portsAttributes` setting just sets properties for ports and doesn't actually cause them to be forwarded. They are properties to be applied if/when the port is forwarded.
