### ISSUE TITLE
No coloring of JavaScript in HTML/Razor/Handlebars

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12750]
Testing https://github.com/Microsoft/vscode/issues/12100

I am not seeing coloring when typing JavaScript inside script tags in HTML/Razor/Handlebars.

![image](https://cloud.githubusercontent.com/assets/900690/18873502/0adf4b16-84c0-11e6-82c3-ab40df756e84.png)

Marking as important because I think this will make many people unhappy.

@alexandrudima fyi since @aeschli is out of office.

**Comment by alexandrudima** [comment]
hmm, appears to be a problem when having the `type` attribute:

![image](https://cloud.githubusercontent.com/assets/5047891/18886633/5f5a8a32-84f9-11e6-92e4-9ed2cfb0ed43.png)

**Comment by alexandrudima** [comment]
It also works if there's a space between `"` and `>`:

![image](https://cloud.githubusercontent.com/assets/5047891/18886856/658c9f16-84fa-11e6-99dc-1836314eb0bc.png)

**Comment by alexandrudima** [comment]
It is caused by this rule in the JavaScript grammar:

`JavaScript.tmLanguage.json:500 - (?<=(?:'|"|})>)`

```json
				{
					"begin": "(?<=(?:'|\"|})>)",
					"end": "(?=</)",
					"name": "meta.jsx.children.js",
					"patterns": [
						{
							"include": "#jsx-children"
						}
					]
				}
```

As soon as HTML includes JavaScript, the JavaScript grammar does a look behind and decides to enter into a jsx children state.

**Comment by alexandrudima** [comment]
To replicate my analysis please use:
```
c:\Alex\src\vscode-textmate>npm run inspect ..\vscode\extensions\html\syntaxes\html.json ..\vscode\extensions\javascript\syntaxes\JavaScript.tmLanguage.json test-bad.html >out-bad.txt
c:\Alex\src\vscode-textmate>npm run inspect ..\vscode\extensions\html\syntaxes\html.json ..\vscode\extensions\javascript\syntaxes\JavaScript.tmLanguage.json test-good.html >out-good.txt
```

Where test-bad is:
```html
<script type="text/javascript">
var x = 3;
console.log('hello world!');
</script>
```

And test-good is:
```html
<script type="text/javascript" >
var x = 3;
console.log('hello world!');
</script>
```

And then compare the two files. The first signficant diff points to the culprit:

![image](https://cloud.githubusercontent.com/assets/5047891/18887590/611d7218-84fd-11e6-932e-a85b10f103d0.png)

**Comment by alexandrudima** [comment]
I suggest the following fix to the rule in `JavaScript.tmLanguage.json:500`:

![image](https://cloud.githubusercontent.com/assets/5047891/18887743/025e27e4-84fe-11e6-981f-ea0a4eb2e1f1.png)

Change the rule `(?<=(?:'|\"|})>)` to `(?<!javascript\">)(?<=(?:'|\"|})>)`

This means to still match all text with look-behind `">`, but not text with look-behind `javascript\">`.

**Comment by alexandrudima** [comment]
@bpasero Please discuss in the standup and let me know if I can help further.

**Comment by sandy081** [comment]
JSX is a mix of Javascript and HTML. If there are JSX specific colors for javascript and html then those wont get applied. But writing JSX code with type `text/javascript` is not correct. 

So, this fix LGTM.

**Comment by bpasero** [comment]
@sandy081 you wanna take this? might need to review if our colorization tests fail with this change.

**Comment by sandy081** [comment]
@bpasero Sure I can take it up. Will check the tests too.

**Comment by sandy081** [comment]
After further investigation I am not in favor of doing the fix in `JavaScript.tmLanguage.json`. Because this file  is derived from [TypeScriptReact.tmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.tmLanguage). It would be good not to customize this.

I see this grammar is for `js` and `jsx` code.  It makes sense only if it is used to parse the code between the `<script>` tags. But, I do not understand why is this grammar is being used in parsing html `<script>` tags also. So, I am assuming that the fix should go into the place where we parse html and delegate the script code to the `js` language parser.

**Comment by bpasero** [comment]
@sandy081 I was thinking that this place would be here: https://github.com/Microsoft/vscode/blob/master/extensions/html/syntaxes/html.json#L180

But I am not so sure anymore how the JS language gets pulled in.

**Comment by bpasero** [comment]
Ok it gets pulled in via TM import: /Users/bpasero/Development/Microsoft/monaco/extensions/html/syntaxes/html.json

**Comment by sandy081** [comment]
@bpasero I went with the fix from @alexandrudima (made it more explicit). Pushed it as it is a regression and might make people unhappy. As this fix is a workaround and safer.
