### ISSUE TITLE
xml tag auto completion produces malformed tag

### ISSUE THREAD

**Issue by bj0rj0h** [Microsoft/vscode#12758]
- VSCode Version: 1.5.3
- OS Version: Ubuntu

Steps to Reproduce:
1. press < vs-code weill generate <>
2. enter name of tag i.e <case>
3. double press tab to auto complete
4. vs-code generates `<case><case>>` instead of `<case><case>` That is one to many '>' at the end

**Comment by aeschli** [comment]
That's emmet.
If I remember right, we fixes this for HTML where we check if there's already a `>` and replace it.

**Comment by ramya-rao-a** [comment]
I am not able to repro this

![e71dg8](https://cloud.githubusercontent.com/assets/16890566/22529107/0201a01e-e88b-11e6-861a-27deffc4848a.gif)

@bj0rj0h Is this still an issue for you?

**Comment by bj0rj0h** [comment]
@ramya-rao-a 

Sorry for the later reply. Works great now thanks.

**Comment by ramya-rao-a** [comment]
@bj0rj0h Thanks for getting back!
