### ISSUE TITLE
TestRunner `createTestController` does not accept `runHandler`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#127566]
Testing #127386

The `notebooks` namespace provides `createNotebookController` with the following signature: 
``` typescript
export function createNotebookController(id: string, notebookType: string, label: string, handler?: (cells: NotebookCell[], notebook: NotebookDocument, controller: NotebookController) => void | Thenable<void>): NotebookController;

```

Having used the notebooks API, I expected the `test` namespace's `createTestController` to also accept the `runHandler` as an optional parameter. Its current signature is 
```typescript
export function createTestController(id: string): TestController;
```

**Comment by connor4312** [comment]
Thanks for the issue, however I will close this as a duplicate since this method will be going away with some changes to the runner API in: https://github.com/microsoft/vscode/issues/127096#issuecomment-868839093 These changes are staged and will be merged after this endgame.
