### ISSUE TITLE
Programmatically created terminals are not automatically respecting the "defaultLocation" setting

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127515]
Testing #127192

- set "terminal.integrated.defaultLocation" to "editor"
- create a simple node program and a corresponding launch.json
- add `"console": "integratedTerminal"` to the launch config
- F5

Observe: new terminal is created in panel, not in the editor group

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/127357

**Comment by weinand** [comment]
@Tyriar Is there anything in my code to make the terminal respecting the default location?

**Comment by Tyriar** [comment]
I think this is something we can control completely, solving the problem generally so tasks and debug and any future terminal use just works. At the most it would be an extra arg in debug which I can add.
