### ISSUE TITLE
Interactive window: No intellisense

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127529]
Testing #127378

Open a python file with cells in it
Bring up the IW
Try typing in the input box at the bottom

No intellisense appears. Colorization works but intellisense doesn't.
[kernel.log](https://github.com/microsoft/vscode/files/6735620/kernel.log)

**Comment by rchiodo** [comment]
[python_kernel.log](https://github.com/microsoft/vscode/files/6735714/python_kernel.log)

**Comment by joyceerhl** [comment]
We can close this. @rchiodo just needed the daily Python build (it wasn't downloading the latest for some reason).

**Comment by rchiodo** [comment]
Perhaps we should transfer this to the python team to see why their insiders daily wasn't downloading?
