### ISSUE TITLE
Notebook cell output menu shows under panel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127576]
Testing #127378

Click on the ```...``` on the last cell in the scrollbar

![image](https://user-images.githubusercontent.com/19672699/123873007-aeb55b80-d8ea-11eb-9bb5-1a663267638d.png)

**Comment by rebornix** [comment]
I'm seeing the same in the notebook, and the run button sub menu behaves correctly.

**Comment by rebornix** [comment]
It's caused by `transform: translate3d(0px, 0px, 0px);` which will crop anything overflows.
