### ISSUE TITLE
Javascript Error when trying to launch Exploration version

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#127585]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Latest Exploration Version 
- Version 1.58.0-exploration (1.58.0-exploration)
- e2f8e14895669fd22065879145825338f4c19cf5
- 2021-06-29T14:33:19.229Z

- OS Version: MacOS 11.4

Steps to Reproduce:

1. Attempt to launch latest Exploration version after update
2. Crash dialog:
```
Uncaught Exception:
Error: submitURL must be specified when uploadToServer is true
at CrashReporter.start (electron/js2c/browser_init.js:41:472)
at configureCrashReporter (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/main.js:2:1779)
at Object.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/main.js:1:851)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:193:3441)
at __webpack_require__ (electron/js2c/browser_init.js:1:128)
at electron/js2c/browser_init.js:1:1200
at electron/js2c/browser_init.js:1:1267
at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
at Module._load (internal/modules/cjs/loader.js:747:15)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47
```

**Comment by aliofwind** [comment]
same problem in windows x64

**Comment by deepak1556** [comment]
Thanks for the report, please start with `--disable-crash-reporter` as temporary workaround.

**Comment by JacksonKearl** [comment]
Verified with the unreleased build on 3f6294b50e.

**Comment by 18392152392** [comment]
I have the same problem, how to do?

**Comment by JoshStrobl** [comment]
Issue persists in 1.59.0. Not sure why this is closed.

**Comment by jtsom** [comment]
```
Version: 1.58.0-exploration
Commit: e2f8e14895669fd22065879145825338f4c19cf5
Date: 2021-06-29T14:33:19.640Z (1 mo ago)
Electron: 13.1.4
Chrome: 91.0.4472.106
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
```
is the latest version ... checking for updates shows no updates available.

**Comment by JoshStrobl** [comment]
So...is this going to be taken a look at?

**Comment by JacksonKearl** [comment]
cc @deepak1556 do we need a new release of Exploration? I do not know the typical cadence.

**Comment by deepak1556** [comment]
I scheduled a build with the fix but looks it partially failed release https://monacotools.visualstudio.com/Monaco/_build/results?buildId=130317&view=results, will look into it.

To clarify, exploration builds are only used for testing newer electron versions and during the adoption phase we will release nightly builds but otherwise it is not meant to be used in production. Please either use our [stable builds](https://code.visualstudio.com/) or [insider builds](https://code.visualstudio.com/insiders).

**Comment by JoshStrobl** [comment]
Again, I am on a stable build. I am on 1.59.0. It is still an issue on the latest stable release.

**Comment by deepak1556** [comment]
@JoshStrobl where did you install the stable from ? Yes this should be fixed in `1.59`. Please also provide the contents of `~/.vscode/argv.json`

**Comment by 18392152392** [comment]
ok, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] Javascript Error when trying to launch Exploration version (#127585)





 
@JoshStrobl where did you install the stable from ? Yes this should be fixed in 1.59. Please also provide the contents of ~/.vscode/argv.json
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fcabralpacheco** [comment]
@deepak1556
It is still an issue in latest stable release.
At first I was using the "--disable-crash-reporter" workaround. Then I digged a little more and found the exact reason. I made a PR with a fix for fesh installs, in an old installations it is necessary to edit the argv.json.

**Comment by JoshStrobl** [comment]
> @JoshStrobl where did you install the stable from ? Yes this should be fixed in `1.59`. Please also provide the contents of `~/.vscode/argv.json`

I build code-oss from source.

```
// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelihood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
    // Use software rendering instead of hardware accelerated rendering.
    // This can help in cases where you see rendering issues in VS Code.
    // "disable-hardware-acceleration": true,

    // Enabled by default by VS Code to resolve color issues in the renderer
    // See https://github.com/microsoft/vscode/issues/51791 for details
    "disable-color-correct-rendering": true,

    // Allows to disable crash reporting.
    // Should restart the app if the value is changed.
    "enable-crash-reporter": true,

    // Unique id used for correlating crash reports sent from this instance.
    // Do not edit this value.
    "crash-reporter-id": "REDACTED FOR GITHUB"
}
```

**Comment by JoshStrobl** [comment]
@fcabralpacheco Will be trying with your PR :+1:

**Comment by fcabralpacheco** [comment]
@JoshStrobl the PR works for fresh installs (with no argv.json) (it prevents the crash reporter auto-enable behavior). For old installations just change `"enable-crash-reporter": true` to `"enable-crash-reporter": false`.

**Comment by JoshStrobl** [comment]
> @JoshStrobl the PR works for fresh installs (with no argv.json) (it prevents the crash reporter auto-enable behavior). For old installations just change `"enable-crash-reporter": true` to `"enable-crash-reporter": false`.

Sure, I can change that manual. But this shouldn't break across installs and prevent users from launching without the flag.

**Comment by fcabralpacheco** [comment]
> Sure, I can change that manual. But this shouldn't break across installs and prevent users from launching without the flag.

this was the intention with PR, mainly to prevent it from break again (if argv.json was removed (or new install)).

@deepak1556  I'll test the official builds and make the requested changes in the PR, with it it will still be necessary to disable the default values in a build from source (however this is something very small if compared to the initial issue, and easier to maintain, other builds already do that)
