### ISSUE TITLE
Intellisense not showing by default

### ISSUE THREAD

**Issue by anubra266** [microsoft/vscode#127588]
Issue Type: <b>Bug</b>

Intellisense suggestions don't show when I start typing, only snippets, they then show if I backspace a character.

Here the intellisense suggestions do not show, only snippets come out.
![image](https://user-images.githubusercontent.com/30869823/123885509-83138f00-d945-11eb-907b-5e6f50f82ef3.png)

Then after I delete a character
![image](https://user-images.githubusercontent.com/30869823/123885569-9c1c4000-d945-11eb-9b2c-6a17fb85d042.png)

VS Code version: Code - Insiders 1.58.0-insider (cc528230987ce3ac61fc4f094ae247d5ff24db3c, 2021-06-29T06:28:55.086Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 13a959c6-5c61-4b75-ba2d-8acf14f3ef71|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
commit-message-editor|ada|0.18.1
codesnap|adp|1.3.2
laravel-extra-intellisense|ami|0.6.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
vscode-intelephense-client|bme|1.7.1
turbo-console-log|Cha|2.1.6
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
vscode-todo-plus|fab|4.18.3
php-debug|fel|1.16.0
auto-rename-tag|for|0.1.6
remotehub|Git|0.10.1
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
randomeverything|hel|0.0.3
vscode-peacock|joh|3.9.1
php-cs-fixer|jun|0.2.2
chat|kar|0.35.0
php-namespace-resolver|Meh|1.1.8
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-dotnet-runtime|ms-|1.1.0
remote-containers|ms-|0.185.0
vsliveshare|ms-|1.0.4498
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
indent-rainbow|ode|7.5.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.12.0
material-icon-theme|PKi|4.7.0
material-product-icons|PKi|1.0.4
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
markdown-preview-enhanced|shd|0.5.21
mdx|sil|0.1.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.11
teamhub|Tea|12.1.5
luna-paint|Tyr|0.6.0
errorlens|use|3.3.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode-insiders|Vis|1.0.6
gitmoji-vscode|Vtr|1.0.7
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"
