### ISSUE TITLE
Interactive window doesn't allow scrolling past the end 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127578]
Testing #127378

![image](https://user-images.githubusercontent.com/19672699/123873108-d6a4bf00-d8ea-11eb-853c-01b86ac193fc.png)

Old IW allowed the user to have a full page of blank space at the bottom.

**Comment by rebornix** [comment]
Should be as easy as enabling scroll beyond last line.

**Comment by joyceerhl** [comment]
@rchiodo This may be a silly question but why is it helpful for a user to be able to scroll to blank space at the bottom?

**Comment by rchiodo** [comment]
Same reason a text document or a notebook allows it. It allows you to put the cell where you want it I guess.

**Comment by rchiodo** [comment]
In this case it also eliminates the problem where the ```...``` menu is hidden by the editor.

**Comment by gjsjohnmurray** [comment]
@amunger is it your opinion that the PR I submitted to resolve this should not be merged?

**Comment by amunger** [comment]
whoops, missed that you had a PR open for this

**Comment by gjsjohnmurray** [comment]
@amunger thanks for looking at the PR. You are correct, it is no longer needed and in fact makes things worse. I have closed it unmerged. Please close this issue.
