### ISSUE TITLE
Native Notebooks - Drag and drop movement have low discoverability 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#127524]
Customer feedback on our survey indicates that cell/markdown folding and drag and drop movement have low discoverability. 

Would be great if we could find a way to increase discoverability for these two capabilities in notebooks

**Comment by rebornix** [comment]
> Would be great if we could find a way to increase discoverability for these two capabilities in notebooks

Not sure if we want to increase their discoverability significantly, I personally see them as secondary actions which might not be used by majority of users, especially drag and drop.

**Comment by tanhakabir** [comment]
I think drag and drop is fine since most UIs don't have much of a visual cue for drag and drop beyond the cursor changing which we have but hmm for folding I agree isn't that obvious. @misolori do you have any ideas for UI indications for folding?

I wouldn't think to double click here: 
![image](https://user-images.githubusercontent.com/12758612/124171043-0b914d00-da76-11eb-961d-e1b0829fe422.png)

**Comment by claudiaregio** [comment]
Ah @tanhakabir, sorry if I wasn't clear, the feedback actually indicates markdown folding, not output folding. People don't seem to be discovering the chevron to the left of markdown cells that appears on hover that then collapses cells under the markdown. 

![image](https://user-images.githubusercontent.com/19276747/124176201-71c0a480-da63-11eb-8066-823e2266ad69.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/125534846-35de642f-69da-4ce6-b31f-f7020f9fc927.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/125534934-b1d99532-8ed6-4999-9fcd-926187bed161.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/125534961-eef308ba-bfd6-424b-be5c-098caec08f09.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/125534985-d9b22e38-d081-4498-bce5-cf3b96b7ca0d.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134440942-1e72276e-68aa-44ef-867c-bf1d1b77ea90.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441219-83cac230-7dae-44b9-b313-88e7cf8eff66.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441267-2dfcbd71-2353-4543-ad30-b5d9caa33baa.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441293-9695df94-99e7-4a44-8894-f33e96c1de24.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441309-ee98494a-ee55-4c9f-a0bd-82831d7836ec.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441333-d1114cce-4ed4-4d28-9ff3-d1344b326824.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441407-6931b84d-67b3-49db-bd37-ae083445561c.png)

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/134441944-b78a0316-20f5-456c-8b4b-9d81cdcf7090.png)

**Comment by roblourens** [comment]
I acknowledge an issue based on those reviews but I have no clue how to make dnd more discoverable. We use the grabbing hand cursor on all dnd regions. I'm open to suggestions. There is another issue to allow users to have the ⬆️ ⬇️ buttons in the cell toolbar, and I wouldn't mind doing that although it wouldn't be on by default. If that would address the issue, then I'd close this in favor of that.

**Comment by claudiaregio** [comment]
@roblourens I agree with you that increasing discoverability is hard. I'd love to close this in favor having up and down buttons to move the cells instead. (Even if discoverability is improved, I ran into #145605 quite often, it isn't a very smooth experience). 

When you say "it wouldn't be on by default" do you mean DND would be the experience a new user would get, and to get the arrows a user might have to change a setting?

**Comment by roblourens** [comment]
> to get the arrows a user might have to change a setting?

Yeah, that's what I would expect off the top of my head. I feel that there's a lot of stuff in the toolbar already, and adding too many buttons on the screen can increase confusion too.

**Comment by roblourens** [comment]
I will close this in favor of having arrow buttons in the toolbar

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/168954
