### ISSUE TITLE
"Reopen Editor With Text Editor" is present when the editor is already a text editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127533]
Testing #127355

Seems redundant

**Comment by lramos15** [comment]
You could say this about any custom editor and the reopen with picker. It no-ops so I don't think it's a huge deal and allows you to see the active and default options in the list. Not mutating the list is also nice because you can guarantee that the entries will be the same for the same resource.

**Comment by lramos15** [comment]
For consistency sake I'm closing that as wont fix as having the `active` helps teach the user the editor names and adds value to the open with picker
