### ISSUE TITLE
Terminal profile codicons don't seem to apply?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#127572]
Testing #127194
Contribution like:
![image](https://user-images.githubusercontent.com/8586769/123870782-b1628180-d8e7-11eb-81a8-89197fb08e8f.png)

Gets me:
![image](https://user-images.githubusercontent.com/8586769/123870703-96900d00-d8e7-11eb-8ab9-a3967d3ec5a9.png)

**Comment by Tyriar** [comment]
I guess we could set the icon in the terminal to the contributed one if it's not provided in the icon

**Comment by TylerLeonhardt** [comment]
Yeah I was also confused as to how to set the icon to a codicon. I tried `cloud` and `$(cloud)` in the package.json and it didn't seem to apply.

**Comment by Tyriar** [comment]
Let's pass the contributed icon in here alongside the `id` and set it on `profile.options` is icon is not specified:

https://github.com/Microsoft/vscode/blob/855d764df58f3f53c41e4a9dd9e3093e678a5574/src/vs/workbench/api/common/extHostTerminalService.ts#L602-L616

**Comment by meganrogge** [comment]
I've made it so that you can pass in a valid codicon name without the `$(...)` syntax because I think a lot of people will try that (similar to Jackson's example above).

```
icon: law
```

works. It still works though with the `$(...)` syntax
