### ISSUE TITLE
The 'request workspace trust' dialog should be better aligned with the 'startup trust' dialog

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#127546]
The startup trust dialog

![image](https://user-images.githubusercontent.com/172399/123853277-8dba2e00-d91d-11eb-9720-5dc6e09e06b2.png)

And the request workspace trust dialog

![image](https://user-images.githubusercontent.com/172399/123853514-d4a82380-d91d-11eb-9014-691d09f769a3.png)

Should be better aligned:
- Different button styles
- Cancel vs. 'No I don't trust'
- '... we recommend to continue in restricted mode' vs. 'we do not recommend to continue...'

**Comment by sbatten** [comment]
At least some of the differences here I feel are justified. In the startup flow, the user is just opening a folder and we need a little more UX to provide context. In the request flow, the user is trying to do a specific action so the buttons reflect the effect on the action.
