### ISSUE TITLE
Live Preview will run a server on the same port as something else

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127505]
Testing #124865

Start a react app
Startup simple browser and point it at http://localhost:3000

Open a new workspace with other html
Set live preview to external
Preview an html file.

It will start on the same port as the react app.

Go back to the react app and change something - you get the preview from the index.html instead of the react changes.

**Comment by andreamah** [comment]
React apps and other frameworks that start their own server are currently not supported by Live Preview.

**Comment by rchiodo** [comment]
I wouldn't expect them to be supported. The bug here is that the live preview is not checking that the port is in use.

**Comment by andreamah** [comment]
oops, read the bug a little too quickly, thanks for pointing that out!
