### ISSUE TITLE
Native Notebooks - Allow users to hide cell status hint

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#127559]
Survey Customer Feedback: 
![image](https://user-images.githubusercontent.com/19276747/123860197-70b03b80-d8da-11eb-9f5b-940e88b9f836.png)

Request given feedback: 

After users learn the shortcut to run cells from the cell status bar they may no longer want to see it, however find other information in the cell status bar to be useful (time to execute, check mark when execution is complete, language for polyglot scenarios etc) so hiding the entire status bar with the setting available may remove information they do want to see. 

Would be nice if users could hide the keyboard tip within the cell status bar. 
![image](https://user-images.githubusercontent.com/19276747/123858311-36de3580-d8d8-11eb-8e18-5cd1c621887e.png)

**Comment by roblourens** [comment]
Makes sense to add a setting for this

**Comment by claudiaregio** [comment]
Closing since it has been removed completely
