### ISSUE TITLE
Add an inline X button to our filter/search input boxes to quickly clear it

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#127570]
I would love to have an `x` inside many of our filter/search-type input boxes to quickly clear the input. I do this SO often and I always go looking for the non-existent button 😄 

A few examples:

1. Extensions search
2. Search input
2. Debug Console filter box
3. Problems filter box
4. Settings filter box

**Comment by misolori** [comment]
Don't we already do this in most places? It looks like debug + problems are the only ones that don't (debug only clears the results)

## Extensions
![image](https://user-images.githubusercontent.com/35271042/123872476-fbe4fd80-d8e9-11eb-9d15-375402f0e202.png)


## Search
![CleanShot 2021-06-29 at 14 51 08@2x](https://user-images.githubusercontent.com/35271042/123872143-824d0f80-d8e9-11eb-847d-53f658a1b4cc.png)

## Settings
![CleanShot 2021-06-29 at 14 55 43@2x](https://user-images.githubusercontent.com/35271042/123872591-25058e00-d8ea-11eb-9970-20d0ce950e3c.png)

**Comment by eamodio** [comment]
Wow, never noticed that in the tool bar before. I still think it should be in the input -- like in the settings UI. When I said settings search, I apparently meant the split JSON settings search box (but since that is getting removed, no need)

**Comment by misolori** [comment]
Adding @roblourens for thoughts. I think making it inline for the search input can get confusing with the search options that get toggled there.

**Comment by misolori** [comment]
Bringing this back up, after playing around with the test view I actually do like the filter inline and wonder if there is a way to combine these two as you suggest like:

## No text

When there is no text we can show the filter button but clear

<img width="500" src="https://user-images.githubusercontent.com/35271042/125662246-49fa199d-359a-4e76-95dc-0cb1da487f9b.png">


## With text

With text we then show  the clear button

<img width="500" src="https://user-images.githubusercontent.com/35271042/125662255-025f1c28-f14d-4ed9-b0d8-4b52d80931fc.png">

The exception would probably be the search fields as that has lots of search options already (filter wouldn't apply but clear would). I'll post in our ux channel to see what people think.

**Comment by roblourens** [comment]
What goes in the filter button? We have this in the editor toolbar

![image](https://user-images.githubusercontent.com/323878/125672183-23b6d4a6-004e-4a7f-99e7-d722f72dc622.png)

would those move? I don't think they are used often enough to be promoted

**Comment by misolori** [comment]
yea my though was that all filters would go there. I personally use the modified settings query often but maybe i'm in the minority. We could also add to the list to bring more discoverability to these filters:

<img width="497" alt="CleanShot 2021-07-14 at 11 31 30@2x" src="https://user-images.githubusercontent.com/35271042/125674095-71860ce0-d709-47bb-aeb6-64b5829d38a2.png">

**Comment by roblourens** [comment]
I feel like most of these input boxes have too many icon buttons as it is, and I don't think this is needed
