### ISSUE TITLE
no open with action for notebook files

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#127583]
Issue Type: <b>Bug</b>

No open with action from file explorer or editor title to open a notebook in text editor.

VS Code version: Code - Insiders 1.58.0-insider (cc528230987ce3ac61fc4f094ae247d5ff24db3c, 2021-06-29T06:27:32.843Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.26GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Appears to be caused by the user having something in their settings.json

**Comment by rebornix** [comment]
```
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook",
        "*.github-issues": "github-issues"
    },
```

reproduced with above settings.
