### ISSUE TITLE
Keyboard: Widget not showing correct values

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1275]
I am on a Mac with a german keyboard layout and some keys are not showing a preview as expected:
* < : unknown (key right to shift)
* ^ : backslash
* ? : [
* ´ : ]
* * : = 
* # : /
* ü : ;
* ö : `
* ä : '

I wonder if the keyboard layout is correctly detected after all?

Btw I am seeing similar results on Mac and Linux.

**Comment by alexandrudima** [comment]
@bpasero We render in there the key codes (i.e. the rule you have to write in keybindings.json). I will make a change to also render in there a UI label. Please see #713
