### ISSUE TITLE
TerminalProfile: new TerminalProfile vs plain options object?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#127556]
Testing #127194

The `TerminalProfileProvider` allows for returning either a raw options dict like:
![image](https://user-images.githubusercontent.com/8586769/123859019-02b74480-d8d9-11eb-8605-62d5613b2f7c.png)

Or constructing and returning an `TerminalProfile` object like:
![image](https://user-images.githubusercontent.com/8586769/123859221-414cff00-d8d9-11eb-8945-f5c906a8532d.png)

This seems a bit confusing, traditionally when we have exported classes it's because the constructor does some work in managing a large number of field initializations, but here there's only the one, so why not just an interface, or alternatively unpacking the options field into it's constituant fields (via just extending TerminalOptions and TerminalExtensionOptions)

**Comment by Tyriar** [comment]
The classes also provide validation which was the main reason here:

https://github.com/Microsoft/vscode/blob/45eea1f87bbb1e98e78ec61268b6b36dcaaa56a3/src/vs/workbench/api/common/extHostTypes.ts#L1726-L1734

We could potentially build that validation out in the future as well. It was originally an interface but changed at Joh's request.
