### ISSUE TITLE
Comparing notebooks results in empty cells being added to first notebook

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127537]
Testing #127355

1. In the vscode repo, open my-endgame.github-issues
2. Compare Active File With endgame.github-issues
3. Close the compare editor
4. Scroll down and back up In my-endgame.github-issues
5. Things are broken 🐛 

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/2230985/123851794-79037900-d8d0-11eb-804d-9ff017a3cc00.png">

**Comment by rebornix** [comment]
let's merge this into  https://github.com/microsoft/vscode/issues/127738 with more details.
