### ISSUE TITLE
Add a default shortcut for duplicating line

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#127558]
tl;dr: Add a default shortcut for duplicate line that is close to existing shortcuts in popular text editors.

- Textmate, Atom and Sublime have the shortcut `Cmd-Shift-D`. Brackets has `Cmd-D`
- This specific shortcut is highlighted in a recent [CSS Tricks](https://css-tricks.com/on-switching-code-editors/) article as important custom shortcut.
- Anecdotally, it is also the only custom entry I added in my shortcuts even though I have used VS Code for years.

As `Cmd-Shift-D` is taken, would `Cmd-D` be a good stand-in and close enough to most users' muscle memory?

**Comment by AlexTelon** [comment]
So your suggestion is to add `cmd+d` as an **alternative** to the already existing keybind to `copy line down`?  Which I'm pretty sure now defaults to `Shift+Alt+DownArrow`.

**Comment by digitarald** [comment]
I mapped Cmd-D to _Duplicate Selection_, as I was unaware of copy line down. Seeing that this one already has a shortcut, this might make less sense (apart from discovering that the similar command exists with a different name).
