### ISSUE TITLE
TestController `createTestRun` docstring missing info

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#127557]
Testing #127386

![image](https://user-images.githubusercontent.com/30305945/123860234-7c9bfd80-d8da-11eb-957a-45d82484603b.png)

**Comment by connor4312** [comment]
@mjbvz it looks like the hovers omit the new `{@link` format:

https://github.com/microsoft/vscode/blob/f0c2301c32a5d5e88df697ca992b7f389ff18b1b/src/vs/vscode.proposed.d.ts#L1945

**Comment by mjbvz** [comment]
@connor4312 Try removing the generic from the `@link` symbol name. It works without it.

I'll open a TS issue about parsing symbols with generics too (although I'm not sure if other JSdoc engines support it or not)
