### ISSUE TITLE
contributes=>terminal=>profiles=>icon vs TerminalOptions.iconPath?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#127575]
Testing https://github.com/microsoft/vscode/issues/127194

Not clear how `contributes=>terminal=>profiles=>icon` and `TerminalOptions.iconPath` are supposed to work together. I tried setting `contributes=>terminal=>profiles=>icon` to `law` and I didn't see it apply anywhere, I tried additionally setting `TerminalOptions.iconPath` to `new vscode.ThemeIcon('law')` and now I see the icon in some places, but missing from others (notably, the `Create New Terminal (with Profile)`  picker): 
![image](https://user-images.githubusercontent.com/8586769/123871794-05219a80-d8e9-11eb-9911-372c2ae1ddbb.png)

**Comment by Tyriar** [comment]
Some of this is covered in https://github.com/microsoft/vscode/issues/127572, specifically the icon not showing up when you set it in the contribution but not the options.

For this issue let's cover making sure `TerminalOptions.iconPath` set to `new vscode.ThemeIcon('law')` shows up everywhere:

- Create with profile quick pick
- Terminal tabs list
- `term` quick access
- Inline tab
- Terminal editor

**Comment by meganrogge** [comment]
Fixed with https://github.com/microsoft/vscode/commit/e2fe066ff144db4000e87e81d932c4256db7bbc0 the profile quick pick was the one that wasn't working
