### ISSUE TITLE
Interactive window suddenly has dupe tabs and loses input box

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127539]
Testing #127378

Not sure how this happened
![image](https://user-images.githubusercontent.com/19672699/123851993-acde9e80-d8d0-11eb-8167-91e12db30874.png)

But there's two tabs for each IW and for each one, the one with a * has no input box

![image](https://user-images.githubusercontent.com/19672699/123852081-c41d8c00-d8d0-11eb-82bb-8068c4a5d409.png)

**Comment by joyceerhl** [comment]
Looks like the NotebookDocument got opened in a NotebookEditor
