### ISSUE TITLE
Drag and drop into editor does not work for notebook or custom editor

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127543]
Testing #127355

1. Have a text file open in one window, and a notebook or custom editor in enother
2. Try to drag the text file into the editor area of the notebook or custom editor
3. It does not work 🐛

**Comment by bpasero** [comment]
See https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Awebview+label%3Aworkbench-dnd
