### ISSUE TITLE
extensions.autoUpdate makes uninstalling extension impossible

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#12759]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Set `extensions.autoUpdate: true`
2. Uninstall extensions

you will get:
![image](https://cloud.githubusercontent.com/assets/1723815/18875135/6f23e772-8492-11e6-9e5d-c9a487de4584.png)

3. Restart Now (to deactivate)

You can see that extensions just got auto installed
![image](https://cloud.githubusercontent.com/assets/1723815/18875153/89466a58-8492-11e6-8ec5-04fc9c1c2b54.png)

If you are fast enough you will see green button with (Installing...) after that restart to deactivate

**Comment by joaomoreno** [comment]
I can no longer reproduce this, let me know if you still can.
