### ISSUE TITLE
<img> tags do not render in markdown cells

### ISSUE THREAD

**Issue by Treit** [microsoft/vscode#127593]
Issue Type: <b>Bug</b>

Using .NET Interactive Notebooks or Jupyter notebooks, img tags in markdown cells or HTML cells do not render.

For instance, create the following test.dib file:

    #!markdown

    <h1>Hi</h1>
    <img src="snail1.jpg" />

Then render the cell. This should display an image of the "snail1.jpg" file that is found in the same folder as the .dib file.

I have tried explicitly passing the full path to the file and that does not help either.

The cell above renders as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/8271812/123894379-eafcb200-d912-11eb-9df9-72ac3c90e16f.png)

In the non-insiders version of VSCode, I cannot get any HTML content at all to render inside markdown cells; however, in the insiders build I see things like &lt;h1&gt; tags being rendered, but not images.

VS Code version: Code - Insiders 1.58.0-insider (cc528230987ce3ac61fc4f094ae247d5ff24db3c, 2021-06-29T06:27:32.843Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.44GB (34.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-interactive-vscode|ms-|1.0.2325011
jupyter|ms-|2021.7.982069998
remote-wsl|ms-|0.58.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vsdfh931cf:30280410
vshan820:30294714
vscus158:30321503
vscod805cf:30301675

```

</details>

**Comment by Treit** [comment]
Some additional information:

If I completely uninstall vscode and remove all traces of it (for instance, also removing the 'Code' folder from %appdata%, then I am able to reinstall vscode and the Jupyter extension and successfully render HTML, including images, in markdown cells.

If, however, I install the interactive notebooks extension then image rendering breaks. Even if I then uninstall the interactive notebooks extension, the Jupyter notebook experience remains the different one that lights up after first installing that extension, going from this:

![image](https://user-images.githubusercontent.com/8271812/124027492-cd2d5c80-d9a7-11eb-89ae-be219d9e29b8.png)

to this:

![image](https://user-images.githubusercontent.com/8271812/124027786-1aa9c980-d9a8-11eb-90b0-6e4ace1912f7.png)

Therefore, installing and then uninstalling the .NET Interactive Notebooks extension seems to permanently alter the notebook experience even for regular Python Jupyter notebooks, and results in img tags not being able to render.

**Comment by Treit** [comment]
@mjbvz isn't this a bug and not a feature request?

**Comment by Treit** [comment]
Update: this issue appears to affect local files. URLs to images on the internet do work.

## Example input
![image](https://user-images.githubusercontent.com/8271812/124198447-8d3ca700-da85-11eb-984f-d1d3d56f55a7.png)

## Example output
![image](https://user-images.githubusercontent.com/8271812/124198479-9ded1d00-da85-11eb-8bad-79e21e6b545e.png)

**Comment by rhelenagh** [comment]
@Treit Hello, that is interesting, except for the use of file: // path and regular windows path, all the options of rendering images using Markdown in the .net interactive notebook work for me.

**Input**
![image](https://user-images.githubusercontent.com/7809022/125171884-f4a9d380-e1b6-11eb-8a45-1f3827db3ceb.png)

**Output**
![image](https://user-images.githubusercontent.com/7809022/125171925-1f942780-e1b7-11eb-8996-a97efb864886.png)

**Comment by Treit** [comment]
@rhelenagh, might be useful to know what your version information looks like and compare it to mine:

```
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z (3 wks ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```

(From the Help | About window in VS Code.)

**Comment by Treit** [comment]
Update: I just tried this on a second machine and I see exactly the same behavior as on my main machine.

Here is the version info for the second machine:

```
Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z (2 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by mjbvz** [comment]
I just tested this on windows and MacOS and I believe images with relative paths are now working properly. We don't support `file://` uris or absolute paths, but we also don't support these in the markdown preview

Please open a new issue if there's a specific case where image aren't working as expected inside notebooks and I'll take a look
