### ISSUE TITLE
Why is a window reload necessary after picking a live server workspace?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127519]
Testing #127164

1. In a new multi-root workspace, show the live preview
2. A notification comes up suggesting to pick a folder to use
3. If you pick one, you're prompted to reload the window

Can we cause the setting to go into effect without a full window reload? Generally VS Code _rarely_ requires window reloads for anything, I think language packs are the only thing that does.

**Comment by andreamah** [comment]
I implemented it that way so that it would prevent external previews from suddenly not being able to access certain pages and stuff from the changes in server root, but if that seems unecessary, I can try implement it without the reload.
