### ISSUE TITLE
Creating a new terminal in editor area doesn't focus it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127518]
Repro 1:

1. Focus terminal panel
2. Run Create terminal editor/in editor area command, the new terminal isn't focused

Repro 2:

1. Set default terminal location to editor
2. ctrl+shift+`, the new terminal isn't focused

**Comment by Tyriar** [comment]
It might be safer to focus it at the end of the actions so we don't confuse active vs focus. I'm not sure right now if there are any cases we have atm where we can activate a terminal editor and not focus it.

**Comment by meganrogge** [comment]
Is there ever a case when we want to set the active terminal editor and not focus it? I couldn't think of one.

**Comment by Tyriar** [comment]
Creating a terminal to the side if we allowed that may not necessarily want focus, not sure if editors can do this atm. Opening multiple terminals in multiple groups? 🤔

**Comment by meganrogge** [comment]
I was trying to avoid having the call to focus all over `terminalActions`, but it's fine with me if you think that's better

**Comment by Tyriar** [comment]
Let's leave it like this as we're both aware, it might come up later is all
