### ISSUE TITLE
Terminal editors: splitted terminal is not preserved as terminal editor

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127532]
Testing #127192

- in a panel split a terminal
- shift select the two terminal tabs that comprise the spitted terminal
- drag them to the editor group

Observe:
there is no longer a splitted terminal. Instead both halves show up as individual terminal editors

**Comment by Tyriar** [comment]
This is actually by design and I think trying to do this would end up leading to some weird behavior as well, like when dragging from multiple groups.
