### ISSUE TITLE
LiveView Preview cannot open index.html without workspace

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#127504]
Testing #127165

I have an index.html and set live preview to open external. Opening the index.html by itself (no workspace) and opening the live preview gives me this:

![image](https://user-images.githubusercontent.com/19672699/123836154-38026900-d8be-11eb-884e-77793cec39cc.png)

**Comment by rchiodo** [comment]
This might be by design, there was a popup in the bottom left telling me that something was risky. After clicking the popup, the problem went away.

**Comment by andreamah** [comment]
I believe that this has to do with the external preview opening before the server is ready. I will look into it, thanks!

**Comment by andreamah** [comment]
This is likely linked to #127642

**Comment by andreamah** [comment]
Verification steps:
1. Download [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server)
2. Change the settings to use an external preview (see [here](https://github.com/microsoft/vscode/issues/127165) to see how to do this)
3. Open the external preview by clicking the preview editor title icon or from the context menu of an html file.
4. The browser window should open after the server is open, thus correctly loading the content.
