### ISSUE TITLE
Copy file in context menu cuts the file

### ISSUE THREAD

**Issue by webJose** [microsoft/vscode#127596]
Issue Type: <b>Bug</b>

1. Have two VS Code's open with two different projects.
2. Copy from one project one or more files to the other project by selecting the file(s) in the file explorer sidebar, then right-clicking and selecting Copy with the mouse.
3. Paste the copied files to the other project in the other VS Code.
4. Go back to the first project and see how the files were cut.

**NOTE**:  I did this with two projects under GIT source control.  I am unsure if this has anything to do with this or not.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.81GB (7.87GB free)|
|Process Argv|--crash-reporter-id 37523a58-380d-4622-bd74-6c65a65eefa1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.5.1
vscode-guid|hea|1.4.20
vscode-drawio|hed|1.5.0
docomment|k--|0.1.20
git-graph|mhu|1.30.0
csharp|ms-|1.23.12
remote-wsl|ms-|0.56.5
uuid-generator|net|0.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510

```

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by webJose** [comment]
> I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

As Murphy's Law would have it, now that I want to verify, I cannot reproduce either, but the day I posted, it happened 4 times in a row. :-(  I may be missing a step or condition that I did not notice, it is one of those things that go away with an app/computer restart.

**Comment by isidorn** [comment]
Closing and if you find good repro steps with insiders let me know and I can reopen this.
