### ISSUE TITLE
Test VS Live Server/Preview - Open preview side by side

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#127531]
Testing #127164

The readme shows the extension working on two editors groups side by side, but when you open the preview it opens in the same editor group and takes all the space.

It would be nice to have the preview open on a second editor group by default to work as recommended on the readme (making changes and seeing them in real time, etc.). Or at least make it a setting.

My vote would be to make it the default.

**Comment by andreamah** [comment]
@DavidKutu are you running the new version of insiders? My previews are opening to the right, but I noticed a bug yesterday where it was opening in the same editor group.

**Comment by DavidKutu** [comment]
I can't remember what I had :(

But I just tried it again with the latest insiders, and it opens on a second editor group. So I guess you can close this.
