### ISSUE TITLE
Clicking on search results alternates between editor types

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#127551]
Testing #127355

Repro:

1. Create a notebook, e.g. GH issue notebook or MD notebook
2. Global search some text that will return results in that notebook
3. Click the result multiple times

🐛 => clicking alternates between opening the result in a text editor and notebook

**Comment by lramos15** [comment]
I believe this is already fixed in insiders by https://github.com/microsoft/vscode/commit/a651ea4be5bafc9c4d7faf674c799bd35d068582
