### ISSUE TITLE
Terminal editors: VI's edit mode is lost on reload

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127527]
Testing #127192

- in a terminal editor start "vi" on a text file
- enter "insert" mode by typing 'i'
- type some characters and observe that they are inserted
- run "reload window" command
- type more characters

Observe: characters are not inserted because insert mode was ended (like pressing ESC).

**Comment by weinand** [comment]
Actually, the same happens when a terminal is moved from editor group to panel.

**Comment by Tyriar** [comment]
This is unexpected, will investigate

**Comment by meganrogge** [comment]
>Actually, the same happens when a terminal is moved from editor group to panel.
This doesn't repro for me when moving to/from the panel
![recording (14)](https://user-images.githubusercontent.com/29464607/123868767-fcc76080-d8e4-11eb-9edb-07487eaf31f0.gif)

**Comment by meganrogge** [comment]
Also works fine for me on reload of the window

![recording (15)](https://user-images.githubusercontent.com/29464607/123869042-5891e980-d8e5-11eb-82b0-bdce333f87f2.gif)

**Comment by Tyriar** [comment]
I can't repro either, I tried:

- Open a terminal with vim and enter insert mode
- Verify input works
- Reload window with it in the editor, verify input works
- Reload window with it in the panel, verify input works
- Swap between editor -> panel, panel -> editor and make sure input works

**Comment by weinand** [comment]
I was using vi (not vim) on linux and macOs - will try again tomorrows

**Comment by Tyriar** [comment]
Same with vi for me

**Comment by weinand** [comment]
I can still reproduce:

![2021-06-30_09-46-21 (1)](https://user-images.githubusercontent.com/1898161/123922634-867c3a00-d988-11eb-9cc4-fca73feaa69c.gif)

Please note: since "Screencast mode" is reset after the window reload, you cannot see that I was typing `worldl` and I would have expected that the typing `worldl` appears after the `hello`.

But since I was back in vi's command mode, the `w` has no effect and the `o` switched vi back into insert mode.

**Comment by weinand** [comment]
Oh, I understand why VI's edit mode is lost: I'm using `F1` to open the Command palette in order to find the "reload window" command and vi exits edit mode with that.
Sorry, for making you waste time on this...

**Comment by Tyriar** [comment]
> I'm using F1 to open the Command palette in order to find the "reload window" command and vi exits edit mode with that.

Hmm this still shouldn't be sending anything to vi though as it gets handled by vscode to open the command palette. Could you try launch using --verbose so we get logs in the terminal and then toggle escape sequence logging? This will print anything send to/from xterm.js which should include whatever is causing it to exit.

**Comment by weinand** [comment]
Before providing the logs, here is another even simpler case: just switching the focus makes vi return to command mode.

![2021-06-30_14-07-45 (1)](https://user-images.githubusercontent.com/1898161/123958019-d4a33480-d9ac-11eb-88b5-77553a81510b.gif)

Please observe how the block cursor moves from the 'F' to 'c' when clicking in the editor area.

**Comment by Tyriar** [comment]
On focus some things happen in the terminal for me as there's a focus VT sequence that can be listened to:

![image](https://user-images.githubusercontent.com/2193314/123959641-40f94600-d963-11eb-88a5-e5d2a023590c.png)

I'm guessing your vi here is configured to reset the state. I still can't repro though 🤔

**Comment by weinand** [comment]
Ok, this is a "feature" of ubuntu 21.04 LTE !

I just verified that the problem **does not** occur in ubuntu 20.10 LTE.

And I can reproduce the issue even outside of VS Code:
Running vi in a terminal on ubuntu 21.04 shows the same behavior: a click on the desktop makes vi leave insert mode.
On ubuntu 20.10 this does not happen.

So I think you are off the hook ;-)

**Comment by Tyriar** [comment]
Great, TIL 🙂
