### ISSUE TITLE
UI state not preserved when moving codespaces from stable => insiders => stable

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#127580]
Testing #127166

@bpasero From my reading of the test plan I was not sure if this was expected to work or not. So just close if it's off base. But when moving from stable to insiders the single DB was converted to the multiple DBs and the UI state was preserved in that transition. But then from then on the extra DB entries were there regardless of if I swapped back to stable and UI state was no longer preserved when moving from stable to insiders.

Given that this was a migration this might be expected. But I was a bit unsure because if we bothered to preserve UI state when moving from stable to insiders the first time why would we not on subsequent times?

Steps:

1. Open a new codespace in stable (1 DB entry)
2. Open fileA
3. Use the gear icon to move to insiders (3 DB entries)
4. fileA is open in insiders just as it was in stable
5. Open fileB in insiders
6. Use the gear icon to move to stable (3 DB entries)
7. Nothing is open in stable (3 DN entries)
8. From now on stable / insiders are independent for UI state and changes are not preserved moving from one to another.

**Comment by bpasero** [comment]
We only migrate once and I think anything else would be very unpractical because once migrated we don't track the old state anymore and wouldn't know how to migrate that over.
