### ISSUE TITLE
Arrow "nub" shows up earlier than the whole hover tip on the activity bar hover

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#127666]
Looks like an issue with the CSS animation on the hover

**Comment by sandy081** [comment]
Do you mean the beak? Is it the same everywhere in status bar?

**Comment by eamodio** [comment]
Yeah, the beak -- and it seems to happen everywhere, though most noticeable on the activity bar (because of the contrast difference)

![beak](https://user-images.githubusercontent.com/641685/124072051-452e6d80-da0e-11eb-9f8d-97781bdf06e7.gif)

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/pull/127603
