### ISSUE TITLE
Drag and drop from terminal editor to panel instance sometimes doesn't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#127653]
Not sure on repro, happens and I drag back and forth and make splits. It seems to be because the terminal editor's `onRequestAddInstanceToGroup` event isn't being listened to by TerminalService in this case.

**Comment by Tyriar** [comment]
Repro:

1. Open a terminal editor
2. Split via the editor action button
3. Try to drag that new terminal into the panel

Terminal editor instances created via TerminalEditorInput.copy don't get their TerminalService listeners setup:

https://github.com/microsoft/vscode/blob/855d764df58f3f53c41e4a9dd9e3093e678a5574/src/vs/workbench/contrib/terminal/browser/terminalEditorInput.ts#L32-L36

Needs to call:

https://github.com/microsoft/vscode/blob/1d3a7b6bc0ad09c1320e929ef70bef600cbeb094/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L703-L737

**Comment by Tyriar** [comment]
I think the fix will register the listeners multiple times for most terminals due to other calls to `_initInstanceListeners`

**Comment by meganrogge** [comment]
I did some logging and didn't see that

**Comment by Tyriar** [comment]
The fix was on https://github.com/microsoft/vscode/compare/merogge/profileIcon, and we'll need to remove TerminalService.createInstance so all instances go through the same creation flow
