### ISSUE TITLE
Visual treatment of the icon indicating the reason for disablement

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#127693]
Testing #127368

I realized that because the icon is "disabled" I would not have hovered over the icons indicating the reason for disablement in the extension view if the test plan item would not have told me to. Also, in the details editor this piece of information is important but is presented in a subdued fashion. This is less of an issue for non-built-in extension since they have buttons for enabling/disabling. 

![image](https://user-images.githubusercontent.com/4674940/124014192-0fe73880-d998-11eb-80a6-849ec509e5b8.png)

It's also strange that I can actually click the disabled icons and get a visual click response.

**Comment by sandy081** [comment]
@misolori Any recommendations?

**Comment by sandy081** [comment]
First step - changed the info/warning icon from disabled to enabled mode

![image](https://user-images.githubusercontent.com/10746682/124483922-27b12900-ddab-11eb-90f0-d6adf8b18dd3.png)

**Comment by misolori** [comment]
What about adding the warning/info colors on the icon? We do that in the terminal and it looks good.

**Comment by sandy081** [comment]
Good idea. Updated

![image](https://user-images.githubusercontent.com/10746682/124569531-529c8b00-de46-11eb-9157-250e2a785bfd.png)

**Comment by sandy081** [comment]
Seems it got the necessary visual treatment. Hence closing.
