### ISSUE TITLE
Trusted uri list: Add Folder button raw should not be selectable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#127616]
Testing #127549

Select the row with the Add Folder button
Notice how it is now impossible to figure out where the Add Folder button is and where to click.

IMHO Add Folder button should not be just in the left part, but should take the whole row. If that is not possible we should at least make this row not selectable so we do not have this contrast problems.

![Screenshot 2021-06-30 at 10 56 59](https://user-images.githubusercontent.com/1926584/123932722-ffcc5a80-d991-11eb-93c4-7b63aa95c457.png)

**Comment by sbatten** [comment]
Will investigate moving the button out of the table widget

**Comment by sbatten** [comment]
Button has been moved out of the table widget
