### ISSUE TITLE
Test: Terminal editors - Split terminal does not work

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#127633]
Testing #127192

Repro steps:
1. Open VS Code, and click on "New Terminal" which will open the terminal in the panel
2. Use the "Move Terminal into the Editor Area" command from the command palette
3. In the Editor toolbar click on the "Split Editor Right" button 
4. In the Terminal on the right, use the dropdown menu to try to split the terminal
  <img width="502" alt="image" src="https://user-images.githubusercontent.com/3372902/123952800-ca7e3780-d9a6-11eb-9ae6-40a4b3f3cd8c.png">

Expected behaviour: 
Terminal would be split

Actual behaviour:
Nothing happens

What I have noticed is that after step 3) if you select the Terminal on the left, then switch back to the Terminal on the right, and try to do step 4) it seems to work as expected.

**Comment by Tyriar** [comment]
I can repro unexpected split location because the left most item is focused not the new right one (which is active 🤯).

**Comment by meganrogge** [comment]
I can't repro this using the above steps or other combinations - I think @Tyriar fixed this with https://github.com/microsoft/vscode/commit/cae22b8826afa58be54e99bd5c49e6340441616c
