### ISSUE TITLE
Add setting for TypeScript's `includeCompletionsForModuleExports`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#127663]
The TS server has an option called `includeCompletionsForModuleExports`. I would like to disable this to workaround performance issues (https://github.com/microsoft/TypeScript/issues/44826) however it's not possible because VS Code doesn't expose it as an option. Could we add a setting for it?

**Comment by andrewbranch** [comment]
It should be effectively wired up to `typescript.suggest.autoImports`. It’s passed into CompletionInfo requests as an argument, which is deprecated, but should work and continue to work forever. It’s possible that TS Server is mishandling that argument somewhere along the way. @OliverJAsh can you double check that `typescript.suggest.autoImports` really has no effect?

**Comment by OliverJAsh** [comment]
> @OliverJAsh can you double check that `typescript.suggest.autoImports` really has no effect?

I just double checked, I can still reproduce https://github.com/microsoft/TypeScript/issues/44826 with that setting set to `false`. In the TS server log I still see `collectAutoImports` taking a long time:

```
Info 1988 [18:51:28.550] collectAutoImports: done in 973.8930490016937 ms
```

**Comment by andrewbranch** [comment]
This is _probably_ a TypeScript bug, then.

**Comment by OliverJAsh** [comment]
Want me to file a TS bug or should we track it from https://github.com/microsoft/TypeScript/issues/44826 (in addition to the other TS bug mentioned there)?

**Comment by andrewbranch** [comment]
I’ll investigate while I look at #44826. Thanks!

**Comment by OliverJAsh** [comment]
See https://github.com/microsoft/TypeScript/issues/44826#issuecomment-885431264
