### ISSUE TITLE
Test: Terminal editors - moving terminal to editor group

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#127632]
Testing #127192

I have tried to move the terminal into the editor group but the following fails:
* Dragging and dropping the terminal tab does not move the terminal into an editor group
* Right clicking on the Terminal tab does not show the "Move into editor group" menu item
  <img width="245" alt="image" src="https://user-images.githubusercontent.com/3372902/123951539-319aec80-d9a5-11eb-9438-2a99ce4f3abc.png">
* The menu item does appear when I click on the Terminal title
  <img width="172" alt="image" src="https://user-images.githubusercontent.com/3372902/123951659-53946f00-d9a5-11eb-9a0d-0e8aaa6ca029.png">

**Comment by Tyriar** [comment]
This is by design and would be a separate feature of being able to move the terminal _panel_ into the editor.
