### ISSUE TITLE
Keep crashing when opening from cmd prompt

### ISSUE THREAD

**Issue by babul101** [microsoft/vscode#127659]
We have writ
Issue Type: <b>Bug</b>

when I try to open the project from cmd prompt using code .
it hungs for a while and crashes the whole application.
I have tried opening several times  but it gives the same error.
I have found this recently.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (2 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.52GB free)|
|Process Argv|--disable-extensions --max-memory=12288mb --crash-reporter-id 4bccac9c-001b-4083-8222-45a5cdc2ca93|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510
aatestflight:30331711

```

</details>

ten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sbatten** [comment]
Please see this information https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
