### ISSUE TITLE
code running issue

### ISSUE THREAD

**Issue by Suraj1089** [microsoft/vscode#127660]
Issue Type: <b>Performance Issue</b>

when I am running c++ code for printing simple hello word string it takes more than 10 sec. (I have downloaded limited extention not more than 10 to 12.)

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (3.18GB free)|
|Process Argv|C:\\Users\\Suraj\\vs code\\c++practice.cpp --crash-reporter-id 7abea1f4-46b2-4685-8f60-dd4ee8859494|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   125	 18344	code main
    0	   216	  3840	   gpu-process
    0	    25	  6528	   crashpad-handler
    0	   215	 11952	   window (c++practice.cpp - vs code - Visual Studio Code)
    0	    75	  9672	     searchService
    0	    15	 14444	     watcherService 
    0	    11	 17044	       console-window-host (Windows internal process)
    0	   235	 18152	     extensionHost
    0	    73	 17288	       "C:\Users\Suraj\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Suraj\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18152
    0	    43	 18040	       c:\Users\Suraj\.vscode\extensions\ms-vscode.cpptools-1.5.0-insiders2\bin\cpptools.exe
    0	    10	 12016	         console-window-host (Windows internal process)
    0	    19	 13756	         c:\Users\Suraj\.vscode\extensions\ms-vscode.cpptools-1.5.0-insiders2/bin/cpptools-srv.exe 18040 {BEFC09DD-A7E8-416C-9335-693BF846F5C0}
    0	    82	 13144	   shared-process
    0	    62	 15572	     ptyHost
    0	     5	 13720	       C:\WINDOWS\System32\cmd.exe
    0	     7	 14836	       console-window-host (Windows internal process)
    0	    43	 13944	   utility
    1	    84	 18216	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (c++practice.cpp - vs code - Visual Studio Code)
|    Folder (vs code): 213 files
|      File types: obj(20) txt(16) cmake(14) json(10) log(8) exe(7) xml(5)
|                  ipch(5) cpp(4) bin(4)
|      Conf files: cmake(14) makefile(1) sln(1);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.5.1
code-runner|for|0.11.4
better-cpp-syntax|jef|1.15.6
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5
cpptools|ms-|1.5.0-insiders2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4498
leaper|Onl|0.6.0
material-icon-theme|PKi|4.7.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510
vsccppwtct:30329789
aatestflightcf:30331712

```

</details>

![image](https://user-images.githubusercontent.com/85509795/123985278-f7504000-d9e2-11eb-8ade-bb0ce2f32fe8.png)

**Comment by sbatten** [comment]
This is about the C++ extension, but I expect that this is not an issue with VS Code or the extension. You can verify by copying the command being run above into a separate terminal
