### ISSUE TITLE
Bash syntax highlighter incorrectly parses Parameter Expanded Variable

### ISSUE THREAD

**Issue by JamesAllen16** [microsoft/vscode#127630]
Issue Type: <b>Bug</b>

write a small bash script:

```bash
#!/bin/bash
echo "Args: ${*}"
IFS=" " read -r -a arg_array <<< "${@//[^([:alnum:]|[:space:]=\"\-)]/}"
echo "Args in array: ${arg_array[*]}"
cat /dev/null
```
The parameter expanded variable - $@ is filtered using a replace regex to remove non-standard characters passed on the command-line.

The syntax highlighter does not manage to escape the double-quote in the replace pattern `\"` and treats it as the end of the string, causing the syntax highlighter to fall apart on any following lines of code 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.83GB (53.20GB free)|
|Process Argv|--file-uri file:///c%3A/Users/jallen16/repos/RTE.code-workspace --crash-reporter-id 4c2cba38-6c9c-4b64-a2e8-eb805446b881|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
cucumberautocomplete|ale|2.15.1
spellright|ban|3.0.58
vagrant|bbe|0.5.0
armview|ben|0.4.5
markdown-preview-github-styles|bie|0.2.0
vscode-markdownlint|Dav|0.42.1
whitespace-plus|dav|0.0.5
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
terraform|has|2.13.0
reg|ion|1.0.3
pre-commit-vscode|Mar|0.0.8
render-crlf|med|1.5.19
azure-pipelines|ms-|1.188.1
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.0
vscode-bicep|ms-|0.4.63
vscode-cosmosdb|ms-|0.17.0
vscode-docker|ms-|1.14.0
vscode-dotnet-runtime|ms-|1.1.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.1
tcl|ras|0.1.0
ruby|reb|0.28.1
jumptocolumn|sal|1.1.0
code-spell-checker|str|1.10.2
shellcheck|tim|0.14.4
vscode-ansible|vsc|0.6.0
jinja|who|0.0.8
vscode-ruby|win|0.28.0
ascii-unicode-escape|yar|0.1.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119

```

</details>

**Comment by JamesAllen16** [comment]
as a side-note, it appears the Github syntax highlighting also has the same issue 😄 

I presume this needs forwarding to whatever syntax highlighting tool is used for both products, but i'm not sure where or what that is!

**Comment by alexr00** [comment]
Thanks for reporting this! We get our syntax highlighting grammar from https://github.com/atom/language-shellscript; however, they are no longer supporting their textmate grammar and have moved to a different grammar format. Because of that, we have an open issue for adopting a new shell script grammar if a better one is provided by the community: https://github.com/microsoft/vscode/issues/77675

I recognize that this isn't a very satisfying answer, but the VS Code team isn't that large and we aren't experts in every language that we support. I'll dupe this issue to the new grammar feature request so that it can be easily found if/when a better grammar is provided.
