### ISSUE TITLE
Windows: terminal crashes when created with shellPath

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12765]
Testing https://github.com/Microsoft/vscode/issues/12595

Windows: have an extension that creates a terminal with custom `shellPath`, I see the following error: The terminal process terminated with exit code: 1

**Comment by Tyriar** [comment]
Could not reproduce with the following:

```ts
terminalStack.push((<any>vscode.window).createTerminal(`Ext Terminal #${terminalStack.length + 1}`, 'powershell.exe', ['-l']));
```

I'm assuming you ran the command in the example as it was which is expected to fail since `/bin/zsh` doesn't exist on Windows.

**Comment by bpasero** [comment]
Yup, works.
