### ISSUE TITLE
Splits

### ISSUE THREAD

**Issue by eddiemonge** [microsoft/vscode#127678]
Issue Type: <b>Bug</b>

Splitting tabs, terminals etc should split the current selection, using up its available space instead of redistributing all splits equally.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 93267229-6426-430f-84db-cdda41fe8251|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.1.3
markdown-preview-github-styles|bie|0.2.0
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.0.1
todo-tree|Gru|0.0.213
dotenv|mik|1.0.1
remote-wsl|ms-|0.56.5
vsliveshare|ms-|1.0.4498
debugger-for-chrome|msj|4.12.12
indent-rainbow|ode|7.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30329803
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot to help explain your idea?

**Comment by eddiemonge** [comment]
![image](https://user-images.githubusercontent.com/127535/124645453-4c0f1300-de48-11eb-8678-8044e5b9d6da.png)

![image](https://user-images.githubusercontent.com/127535/124645658-8bd5fa80-de48-11eb-846f-16b5b2f9d419.png)

**Comment by joaomoreno** [comment]
This is a choice done by the grid user: the workbench.

**Comment by sbatten** [comment]
I believe the grid user in this is example is the editor part, not the entire workbench, and I believe @bpasero has already added a setting for this `workbench.editor.splitSizing`

**Comment by eddiemonge** [comment]
Ah, it does. I did not know about that setting. Thank you.
