### ISSUE TITLE
Input doesn`t work

### ISSUE THREAD

**Issue by janisbunkss** [microsoft/vscode#127624]
For the following CODE, OUTPUT stucks (reflects text, but doesn`t allow to write in an input  :
CODE:
class Person:
    def __init__(self):
        self.firstname = input('Enter first name:  ')
        self.lastname = input('Enter last name:  ') 
    def show_full_name(self):
        return self.firstname + ' ' + self.lastname
#creating an object with the class
person2 = Person()
person2.show_full_name()
OUTPUT:
[Running] python -u "c:\Users\Python\trenins.py"
Enter first name: |

**Comment by janisbunkss** [comment]
For the following CODE, OUTPUT stucks (reflects text, but doesn`t allow to write in an input :
CODE:
class Person:
def init(self):
self.firstname = input('Enter first name: ')
self.lastname = input('Enter last name: ')
def show_full_name(self):
return self.firstname + ' ' + self.lastname
#creating an object with the class
person2 = Person()
person2.show_full_name()
OUTPUT:
[Running] python -u "c:\Users\Python\trenins.py"
Enter first name: |

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill in issue template with proper info about versions, extensions etc.
Also specify how VS Code editor itself related to this issue with Python code. How do you launch it and related configs.
