### ISSUE TITLE
"Command xxx not found"

### ISSUE THREAD

**Issue by HarryAdney** [microsoft/vscode#127646]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0-insider
- OS Version: Windows 11 version 21H2 build 22000.51

Steps to Reproduce:

1. Open any html page in VS Code
2. Click on any command on the toolbar or from the command bar

Just reinstalled VS code Insiders build, but the issue remains.
Reinstalling extensions doesn't fix the issue either.

**Comment by sbatten** [comment]
Some additional info will be helpful:

- Can you provide more info on the specific commands you are trying to run?
- Can you try with a fresh user/ext directory `code-insiders --user-data-dir C:\Users\username\Desktop\ext1 --extensions-dir C:\Users\username\Desktop\ext2`
- Providing a screen recording would also be helpful

**Comment by HarryAdney** [comment]
> Some additional info will be helpful:
> 
> * Can you provide more info on the specific commands you are trying to run?
> * Can you try with a fresh user/ext directory `code-insiders --user-data-dir C:\Users\username\Desktop\ext1 --extensions-dir C:\Users\username\Desktop\ext2`
> * Providing a screen recording would also be helpful

Thanks for getting back to me. Due to work commitments, I've installed the generic version of VSC rather than the insiders version. I'll update this with more info as soon as I get a chance.

**Comment by ChriFo** [comment]
I updated today to 1.58.0. 

Some extensions using the following executables found via PATH variable: `node`, `direnv` and `gpg`. 
Echoing PATH in the terminal is showing all needed folders to find them.

But executing once `code-insiders --user-data-dir ./tmp/foo --extensions-dir ./tmp/bar` (and delete it afterwards) (seems) fixed it for me.
