### ISSUE TITLE
[json] should color string values red in light theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1276]
IMHO colors should be reversed in this screenshot. We always use red for strings, and we should use a special color blue for keys in JSON. Also dark theme is doing the same, values are shown in the string color, and keys in the new color.
<img width="391" alt="screen shot 2015-12-14 at 15 13 29" src="https://cloud.githubusercontent.com/assets/1926584/11783056/4c732db4-a275-11e5-921b-f3b95aa7af7f.png">

**Comment by aeschli** [comment]
The colors are the same as we had it 0.9.0 and older.

**Comment by isidorn** [comment]
Just because it was the same since the beginning of time does not mean this is not valid.
Feel free to leave it closed if you disagree with the points I make. But if you agree leave it open and put it to backlog please.

**Comment by aeschli** [comment]
I checked what VS does and you are right, we are inconsistent here.
Fix delivered
