### ISSUE TITLE
Live preview: page refreshes when some other file is modified

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#127631]
Testing #127165

- install Live Preview and configure External Browser Preview for Live Preview
- open the VS Code repo in a folder
- open extensions\theme-seti\icons\preview.html in the live preview.
- make changes in some unrelated `package.json` file. Live preview browser refreshes

**Comment by andreamah** [comment]
The current reason that this happens is because we aren't sure what file is linked to the current preview that would alter how it looks. We can maybe look into a setting that allows you to choose the file endings for triggering a refresh, though.

**Comment by aeschli** [comment]
Would the server know what files have been accessed? It could filter the change events to all other files.

**Comment by andreamah** [comment]
Oh, that's a really good idea. I guess the server would need to keep state, but it should work I believe.

**Comment by rzhao271** [comment]
I still see the issue with the original steps.

**Comment by andreamah** [comment]
Oops, this functionality has been removed in favour of refreshing everything to support watch scripts: https://github.com/microsoft/vscode-livepreview/issues/51
