### ISSUE TITLE
Live preview: Address conflict in multi root workspaces 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#127639]
Testing #127165

- install Live Preview and configure External Browser Preview for Live Preview
- have a multi root workspace with folders `folder1` and `folder2`, both with a html file in it
- open live preview on the first folder: browser opens up with `http://127.0.0.1:3004/index.html`
- open live preview on the second folder: browser opens up with `http://127.0.0.1:3004/endpoint_folder2_0/index.html`
- in folder1 create a folder `endpoint_folder2_0` with an html file in it
- browser also comes opens up with `http://127.0.0.1:3004/endpoint_folder2_0/index.html`

**Comment by andreamah** [comment]
Is the issue that the second workspace creates an endpoint? Because that is the expected behavior when the server root lies with the first workspace.

**Comment by aeschli** [comment]
It's costrctred, of course, but isn't there now a conflict what `http://127.0.0.1:3004/endpoint_folder2_0/index.html` points to?
Can be `folder1/endpoint_folder2_0/index.html` and `folder2/index.html` 
What I observed was that showing the preview of `folder2/index.html` would show me the content of `folder1/endpoint_folder2_0/index.html`

**Comment by andreamah** [comment]
Oh, I see the issue now. It's pretty difficult to create an endpoint name that will have no collisions. Do you suggest that we use something like a randomized string to be the endpoint instead?

**Comment by aeschli** [comment]
Maybe use endpoint names for all folder (including the first) when in a workspace.

**Comment by andreamah** [comment]
That could work, although the expected behavior when hosting a directory in a workspace seems to be that the file that is relative to the server root can be accessed without an endpoint of some sort?

I'm just worried that this would make the experience for single-root users worse.

**Comment by aeschli** [comment]
For single root, nothing needs to change. Just for multi root, you have that extra segment in the URI.
Alternative is to try to find a common root of all folders and server the files from there.
