### ISSUE TITLE
Property enable-browser-code-loading is not allowed.

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#127677]
Testing #127168

![image](https://user-images.githubusercontent.com/2644648/124000138-21284900-d988-11eb-97bf-9c19a58e993e.png)

Steps

* F1 > Configure Runtime Arguments
* adding , `"enable-browser-code-loading": false`

**Comment by bpasero** [comment]
Thanks, I really didn't want to advertise this flag because it will go away in 1 month.
