### ISSUE TITLE
'Toggle control characters' - not specific enough

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12760]
Maybe rename it to 'Toggle indentation control'
Toggle control characters is not very clear as to what it does

![screen shot 2016-09-27 at 15 20 58](https://cloud.githubusercontent.com/assets/1926584/18875522/6e4938e6-84c6-11e6-8673-779c26c07786.png)

**Comment by Bill-Stewart** [comment]
Actually that is a good question. What does that option do, precisely?

**Comment by alexandrudima** [comment]
It toggles the rendering of control characters using Unicode control pictures (it basically substitutes characters in the view).

https://en.wikipedia.org/wiki/Control_character#In_ASCII
![image](https://cloud.githubusercontent.com/assets/5047891/18890635/9f97d03a-850a-11e6-9d99-6a898673ee81.png)


https://en.wikipedia.org/wiki/Unicode_control_characters#Control_pictures

![image](https://cloud.githubusercontent.com/assets/5047891/18890595/71c08df0-850a-11e6-9326-9dd766139c70.png)
