### ISSUE TITLE
task spinner won't stop spinning

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#127684]
![recording (18)](https://user-images.githubusercontent.com/29464607/124007698-7405fe80-d990-11eb-9e2f-a651bcb04bec.gif)

**Comment by meganrogge** [comment]
fyi @alexr00

**Comment by Tyriar** [comment]
Might be windows/wrapping/problem matcher related?

**Comment by Tyriar** [comment]
I haven't seen this in weeks, how about you @meganrogge?

**Comment by meganrogge** [comment]
Nope, closing
