### ISSUE TITLE
Terminal renders during process reconnect (aka. replay)

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#127638]
Testing #127192

https://user-images.githubusercontent.com/3372902/123956140-a290d300-d9aa-11eb-90cc-846aaf727b53.mov

**Comment by Tyriar** [comment]
This is probably an existing issues, we could potentially attach to the element only after the replay is finished to avoid watching long writes happen.

**Comment by Tyriar** [comment]
Related to https://github.com/microsoft/vscode/issues/116113, when I run `tree` the replay ends up taking about 300ms _for a single terminal_:

![image](https://user-images.githubusercontent.com/2193314/126642336-6946a270-e0f1-496c-b358-f4479f6657de.png)

Renders may happen in-between this parsing which would cause flickers like above, this depends on the shape of the replay events.
