### ISSUE TITLE
Version control icon not displaying in the side bar

### ISSUE THREAD

**Issue by deepak-personal** [microsoft/vscode#127658]
Issue Type: <b>Bug</b>

The version  control icon is not displaying in the side bar but it displaying the source control section in the file explorer and also in the bottom or status bar.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6310 APU with AMD Radeon R4 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|6.96GB (1.96GB free)|
|Process Argv|--crash-reporter-id 2c5fb3f1-7231-4b5d-8641-8203fc930f6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-browser-preview|auc|0.7.1
apex-javadoc|bta|1.2.1
codefriar-s-pack|cod|0.1.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.0.1
lana|Fin|1.3.5
vscode-pull-request-github|Git|0.27.1
plantuml|jeb|2.15.1
gitignore|mic|1.0.1
apex-code-coverage-visualizer|mod|0.9.6
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vsliveshare|ms-|1.0.4498
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
polacode|pnp|0.3.4
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
salesforce-vscode-slds|sal|1.4.6
salesforcedx-vscode|sal|52.2.0
salesforcedx-vscode-apex|sal|52.2.0
salesforcedx-vscode-apex-debugger|sal|52.2.0
salesforcedx-vscode-apex-replay-debugger|sal|52.2.0
salesforcedx-vscode-core|sal|52.2.0
salesforcedx-vscode-expanded|sal|52.2.0
salesforcedx-vscode-lightning|sal|52.2.0
salesforcedx-vscode-lwc|sal|52.2.0
salesforcedx-vscode-visualforce|sal|52.2.0
gitconfig|sid|2.0.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.12
errorlens|use|3.3.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30329803
binariesv615:30325510
aatestflightcf:30331712

```

</details>

e have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by deepak-personal** [comment]
![VS Code bug](https://user-images.githubusercontent.com/59723017/123986367-dfc58700-d9e3-11eb-9b0d-c0e4bc4c948d.png)

**Comment by gjsjohnmurray** [comment]
It looks like you dragged it onto the Explorer view. Try dragging it back onto the Activity Bar.

**Comment by deepak-personal** [comment]
It is resolved.

Thanks,
Deepak
