### ISSUE TITLE
Use regular expressions in Visual Studio: Named capture groups

### ISSUE THREAD

**Issue by edu8rio** [microsoft/vscode#127657]
Issue Type: <b>Bug</b>

Replacement works on Visual Studio 2015.
It does not work on Visual Studio Code.
https://docs.microsoft.com/en-us/visualstudio/ide/media/named-capture-group.png?view=vs-2019

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.91GB free)|
|Process Argv|censuredxxxxx.xml --crash-reporter-id 7c4d36f7-e593-48ca-b4f5-ebca14d910ad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
csharp|ms-|1.23.12
cpptools|ms-|1.4.1
notepadplusplus-keybindings|ms-|1.0.7
shader|sle|1.1.5
vscode-icons|vsc|11.5.0

(5 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Seems to work for me, can you give an example?

**Comment by ArturoDent** [comment]
The find works for me but not the replacement.

Find: `(?<repeated>\w+)\s\k<repeated>`
Replacement: `${repeated}`
Text: `the the what what`

![repeatedRegex](https://user-images.githubusercontent.com/31813701/124167925-b0555f80-da61-11eb-9b39-f5cbf8a9d6b9.gif)

Info: https://www.regular-expressions.info/named.html

Version: 1.58.0-insider (user setup)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by edu8rio** [comment]
That's the problem I was referring to. Thanks.
