### ISSUE TITLE
Some unknown extension causes backspace to no longer works in json files

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#12769]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:
1. I installed a bunch of extensions, excluding vim/emacs ones which I know mess up the keyboard.

Bug: Backspace and tab keys no longer works in json files (other file type seem to work). I can't tell which extension is causing this. I looked at the Contributions and I didn't see backspace being overridden. If you can provide an easier way to find out which extension is causing this problem that would be great.

Bug#2: Also, auto-complete no longer works in settings.json...could be a different root cause.

**Comment by joaomoreno** [comment]
Please file separate issues for separate bugs.

Can you show me a screenshot of the file which appears _locked_?

**Comment by sean-mcmanus** [comment]
Sure, I'll file a separate bug and attach a screenshot later (back to using VS), but the screenshot wouldn't show anything but a json file. I need somehow find the extension that is messing up backspace and tabs...I'll try searching the package.json later.

**Comment by joaomoreno** [comment]
This was the backspace extension for sure.
