### ISSUE TITLE
Embedded feedback panel similar to Notepad

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#127644]
Notepad has a feedback hub where you can search and +1 existing feedback requests.
You can also see help pages on ["what Microsoft doees with this feedback"](https://blogs.windows.com/windows-insider/2015/06/12/how-windows-insider-feedback-influences-windows-10-development/).

<img alt="Notepad " src="https://user-images.githubusercontent.com/82655227/123962246-2649c000-d9a9-11eb-888f-aee286e28b9a.png" height="401" />

I'd love to see this feature in VSC (Basically a custom `vscode-github-issues-prs` view).
This would be built in to VSC instead of being a separate program
Maybe my feedback requests would get more traction?

**Comment by sbatten** [comment]
possible issue reporter improvement

**Comment by TylerLeonhardt** [comment]
I think this is a neat idea. That screenshot looks nice! I've added it to the backlog candidates. Let's see how the community feels.

**Comment by YoussefBouzekri** [comment]
why not use github discussions for that ? I prefer to run as little microsoft products as possible on my linux machine.

**Comment by SNDST00M** [comment]
I don't believe github discussions solves the issue - in fact, there's less filtering options

**Comment by SNDST00M** [comment]
@YoussefBouzekri I think theres been a misunderstanding - I'm not suggesting a separate program, although the screenshot example/state-of-the-art is a separate program for reasons I don't comprehend
