### ISSUE TITLE
We need an overflow design for the activity bar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12767]
Especially now that we put more icons there:

![image](https://cloud.githubusercontent.com/assets/900690/18876986/0a205bdc-84cc-11e6-97f7-03dc45691711.png)

/cc @isidorn

**Comment by stevencl** [comment]
As agreed in the UX meeting we are going to step back and review this overall design. Closing this for now.

**Comment by bpasero** [comment]
I am happy we don't need an overflow design 👍
