### ISSUE TITLE
Inconsistent top-left "go back" control on Welcome walkthroughs

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#127625]
Issue Type: <b>Bug</b>

1. Have a window with no folder open.
2. Select a walkthrough from the Welcome page.
3. Observe the "More" label alongside the "<" icon top-left.
![image](https://user-images.githubusercontent.com/6726799/123937525-2be5dc80-d98e-11eb-824c-bd0d02efe524.png)

4. Repeat on a window with a folder open and observe that there is no "More" label.
![image](https://user-images.githubusercontent.com/6726799/123937687-55066d00-d98e-11eb-9eb7-d42e842d341b.png)

Personally I find "More" a weird label for what is fundamentally a "back" button. But at least the two cases should be consistent. I prefer the one without a label.

VS Code version: Code - Insiders 1.58.0-insider (57930758db9e2c83f59b9ee1851400bd16192d32, 2021-06-30T05:14:00.370Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by JacksonKearl** [comment]
The rendering is controlled by the window size, in narrow/short windows the text hides to not clutter the view. 

#127427: Existing issue for More => Back.

**Comment by gjsjohnmurray** [comment]
Ah now I see it. When I have a folder open the Panel is also open, reducing the height available for the Welcome page enough to trigger the layout without the label.

I think that's fine, so I'm closing this issue.
