### ISSUE TITLE
Option to make certain tasks run only once?

### ISSUE THREAD

**Issue by Azrideus** [microsoft/vscode#127650]
I have the following tasks created in vscode

   

    {
    "version": "2.0.0",
    "tasks": [
        {
            "label": "InstallDeps",
            "type": "shell",
            "command": [
                "echo 'making sure all dependecies are installed ...'",
                "exit;"
            ],
            "presentation": {
                "showReuseMessage": false,
                "clear": true,
                "panel": "dedicated"
            }
        },
        {
            "label": "Test",
            "type": "shell",
            "command": ["echo 'testing...';", "exit;"],
            "dependsOn": ["InstallDeps"],
            "presentation": {
                "showReuseMessage": false,
                "clear": true,
                "panel": "dedicated"
            }
        },
        {
            "label": "Build",
            "type": "shell",
            "command": ["echo 'builiding...'", "exit;"],
            "dependsOn": ["InstallDeps", "Test"],
            "presentation": {
                "showReuseMessage": false,
                "clear": true,
                "panel": "dedicated"
            }
        },
        {
            "label": "Publish",
            "type": "shell",
            "command": ["echo 'publishing...'", "exit;"],
            "dependsOn": ["InstallDeps", "Test", "Build"],
            "presentation": {
                "showReuseMessage": false,
                "clear": true,
                "panel": "dedicated"
            }
        }
    ]
    }

But when I use Publish task, the *InstallDeps* tasks will run three times because its also
needed for *Build* and *Test* tasks,

is there anyway to force a task to run only once ?
Also those two extra tasks dont seem to finish/exit (see image)

Im not sure if its a bug or should be a feature request

[![Image][1]][1]

  [1]: https://i.stack.imgur.com/3v54Z.png

**Comment by alexr00** [comment]
The only way to accomplish this is to make more tasks. Example:

```
{
"version": "2.0.0",
"tasks": [
    {
        "label": "InstallDeps",
        "type": "shell",
        "command": [
            "echo 'making sure all dependecies are installed ...'",
            "exit;"
        ],
        "presentation": {
            "showReuseMessage": false,
            "clear": true,
            "panel": "dedicated"
        }
    },
    {
        "label": "Test-Internal",
        "type": "shell",
        "command": ["echo 'testing...';", "exit;"],
        "presentation": {
            "showReuseMessage": false,
            "clear": true,
            "panel": "dedicated"
        }
    },
    {
        "label": "Test",
        "type": "shell",
        "dependsOn": ["InstallDeps", "Test-Internal"],
		"dependsOrder": "sequence"
    },
    {
        "label": "Build-Internal",
        "type": "shell",
        "command": ["echo 'builiding...'", "exit;"],
        "presentation": {
            "showReuseMessage": false,
            "clear": true,
            "panel": "dedicated"
        }
    },
    {
        "label": "Build",
        "type": "shell",
        "dependsOn": ["InstallDeps", "Test", "Build-Internal"],
		"dependsOrder": "sequence"
    },
    {
        "label": "Publish",
        "type": "shell",
        "command": ["echo 'publishing...'", "exit;"],
        "dependsOn": ["InstallDeps", "Test", "Build"],
		"dependsOrder": "sequence",
        "presentation": {
            "showReuseMessage": false,
            "clear": true,
            "panel": "dedicated"
        }
    }
]
}

```
