### ISSUE TITLE
Privacy statement link leads to a 404 page

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12763]
1. Help menu > privacy statement
2. Taken to a 404 page

https://www.visualstudio.com/en-us/dn948229

**Comment by waderyan** [comment]
Strange. We saw this yesterday on the website link, but then LCA fixed it. 

https://github.com/Microsoft/vscode-website/issues/500

Is the link behind a forward link? Here is another location we could send people to. 

https://www.microsoft.com/EN-US/privacystatement/OnlineServices/Default.aspx

**Comment by waderyan** [comment]
@seanmcbreen with @chrisdias out can you weigh in here? 

As this is labeled "important" and "bug", if we need to get a fix in my recommendation is we switch the product URL product URL to this [updated URL](https://www.microsoft.com/EN-US/privacystatement/OnlineServices/Default.aspx). Chris has asked LCA but haven't heard back from them yet..

**Comment by seanmcbreen** [comment]
Is the link today a static link - if so the first thing we should do is make this a fwd link so we can decide later.  @wade your link looks better but this will allow us to change it outside of the release.

**Comment by waderyan** [comment]
@seanmcbreen do you know how to create a fwd link? @chrisdias has kept how to do it a state secret ;)

**Comment by waderyan** [comment]
Note privacy statement resolves now. Making a new issue for getting this behind a FWD link.
