### ISSUE TITLE
Sometimes bug after enter keycode "Ctrl" +  "-" and press rightclick

### ISSUE THREAD

**Issue by B-O-T-L-Y** [microsoft/vscode#127611]
Issue Type: <b>Bug</b>

Sometimes was bug after enter keycode "Ctrl" +  "-" and press rightclick: not load context menu.

https://imgur.com/juDIgY4

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 3825U @ 1.90GHz (4 x 1895)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (0.21GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 72a5aaf8-361c-4fe3-b6b0-5335e40dbd3a|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
bemhelper|Box|1.4.2
vscode-tailwindcss|bra|0.6.12
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
webpack|jer|2.2.0
sftp|lix|1.12.9
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
vetur|oct|0.34.1
vscode-thunder-client|ran|1.6.1
open-in-browser|tec|2.0.0
twig|wha|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
binariesv615:30325510

```

</details>

**Comment by sbatten** [comment]
sounds like this might be your issue which tends to happen at different zoom levels https://github.com/microsoft/vscode/issues/113175

**Comment by sbatten** [comment]
please comment if I have misidentified
