### ISSUE TITLE
vs Code problem

### ISSUE THREAD

**Issue by mayankjain00** [microsoft/vscode#127640]
we cannot connect to the extensions marketplace at this time please try again later
i get this error everytime i try to install extensions

**Comment by sandy081** [comment]
Can you please provide following logs while you get this error?

    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

It would be also helpful if you can provide the screenshot of the error in VS Code
