### ISSUE TITLE
Animations make me nervous and distract me from debugging

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#127668]
Testing https://github.com/microsoft/vscode/issues/127362

To be honest, I believe this is a VS Code core issue, but the TPI asks to create all issues here 🤷‍♂️ .

Notice how the progress bar is animated on top of the cell and how the time is rotating and updating every .1s. This is making me feel like I need to hurry up with my debugging and gives me an uncomfortable feeling:

https://user-images.githubusercontent.com/5047891/123930117-b975fc00-d98f-11eb-9f4f-e7ad0d116ab4.mp4

**Comment by roblourens** [comment]
This was fixed on Monday, maybe it missed yesterday's Insiders? @DavidKutu said it works today

**Comment by alexdima** [comment]
You're right, sorry about the noise!
