### ISSUE TITLE
Autodetect tasks for subfolders containing .vscode/tasks.json

### ISSUE THREAD

**Issue by JeremyGrieshop** [microsoft/vscode#127683]
I often open a root folder or project workspace, containing multiple repositories.  Each repository may have a .vscode/tasks.json describing tasks particular to its project.

```
.
├── projA
│   ├── .vscode/tasks.json
│   ├── src
│   └── tsconfig.json
├── projB
│   ├── .vscode/tasks.json
│   ├── src
│   └── tsconfig.json
└── workspace.code-workspace
```
The autodetect tasks feature already hunts around for Gulp, Grunt, Jake and NPM build rules.  It would be awesome if it also looked for .vscode/tasks.json definitions.

The alternative is to hoist these tasks up to the top-level, or into the workspace definition, which requires running something to copy and transform the paths to make them runnable from the top.

**Comment by alexr00** [comment]
@JeremyGrieshop we sort of have a way you can do this already with multi-root workspaces. Here's how that would work:
1. Don't open your root folder. Instead, open one of your subfolders.
2. Run the "Save Workspace As" command. Can be found in the File menu or the command palette. Save your workspace file somewhere.
3. Run the "Add Folder to Workspace" command and add one of your other subfolders. Repeat for each of your subfolders. 

From a multi-root workspace like this, we will discover your tasks.json tasks in each of your folders.

**Comment by JeremyGrieshop** [comment]
@alexr00 That's a great suggestion, thank you!  I didn't realize multi-root workspaces would autodetect the tasks.
