### ISSUE TITLE
Allow onAutoForward to open a browser in debug mode

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#127697]
Testing https://github.com/microsoft/vscode/issues/124160 I saw we added an openBrowser action, it would be cool to also have a `debugBrowser` action, like how the [serverReadyAction](https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program) works for debugging servers.

**Comment by alexr00** [comment]
I like it! @connor4312 do you know if there is some internal debug API that I would be able to call that would let the user choose a debugger to use (or even better, that will choose the best debugger for a browser)? All I have is the the URL that will be opened.

**Comment by connor4312** [comment]
Probably the easiest way would be to use the `extension.js-debug.debugLink` command and pass the link string as the argument. That'll find the user's default browser (Edge/Chrome) and open it in debug mode.

**Comment by alexr00** [comment]
Marking as out of scope since I don't think we'll address this any time soon and there hasn't been much interest in it. @connor4312 if you feel otherwise, please re-open!
