### ISSUE TITLE
`DiffEditorInput.toUntyped` does not set `options: override`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127637]
I am not sure the implications, but I noticed how `DiffEditorInput` does not define any `override` options:

https://github.com/microsoft/vscode/blob/5b29adfa24daf111d35367e9e23ddd4557ec363a/src/vs/workbench/common/editor/diffEditorInput.ts#L140-L154

While for example the `NotebookDiffEditorInput` does, but only top level, not in the resource inputs for each side:

https://github.com/microsoft/vscode/blob/ca4bf8a05616559b00f864352619e00d3948d6e6/src/vs/workbench/contrib/notebook/browser/notebookDiffEditorInput.ts#L94-L102

I am not sure a change is needed, just noticed while looking at the methods.

**Comment by lramos15** [comment]
I assume we would want something like 
`modifiedResourceEditorInput.options.override ?? originalResourceEditorInput.options.override ?? 'default'`

**Comment by bpasero** [comment]
Well in a way I am not sure what to do actually:
* should the override happen based on the top level `options.override`?
* should each side of the input's override be respected and resolved and then a diff input constructed with both sides?

In a way, the one override that is top level somewhat competes with the ones on each side.

**Comment by bpasero** [comment]
Given how our factory methods work I would assume that only the top level override is looked at and not the individual overrides within and if that is true I think the diff input should not do any magic but only set the top level override without looking at the inputs inside.

**Comment by lramos15** [comment]
Yeah it's a bit confusing, I think we normally have just taken the modified input as the source of truth. That's the resource we use. Hence why I suggested that weird null cascading

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/issues/127131 moving forward I think we should figure out a solution for this as well. 

Whats the latest and best proposal for this?

**Comment by lramos15** [comment]
The more I think about #127131 I still think that my original proposal albeit weird is the best option. We want to support side by side editors with possibly different type editors on each side which means that each untyped input will have to have its own override option. With diff they can never be different so we can just take one side and since we always take modified as the source of truth for resource I would start there then probe the other locations if one isn't found.

**Comment by bpasero** [comment]
How about this:
* side by side: agree, the override is in each input
* diff: we add a top level `override` to the diff input and ignore the one within

Or does this mess with what we have today?

**Comment by lramos15** [comment]
It would just be weird because it would be the only untyped editor of that kind making the pattern of where overrides are normally located different

**Comment by bpasero** [comment]
Yeah agree, alternative is to just document this properly and ensure we are doing this. I assume the resolver is picking the editor from the modified side to decide which registered editor to use it with?

**Comment by bpasero** [comment]
@lramos15 given your work in #132035 I wonder if a change here is actually needed. We could just say: any variant of a side by side editor (diff or normal) does not define the `override` top level. Rather, we:
* side by side: respect both sides `override`
* diff: take the "primary" (modified) one and only use it if the registered editor can also deal with the "secondary" (original) one

If so, I think we don't need to make changes?

**Comment by bpasero** [comment]
Interesting, if I make a change to `IResourceDiffEditorInput` adding this to the interface:

```ts
readonly options?: IEditorOptions & { override?: undefined };
```

There are a few compile errors that hint to existing uses over top level `override` that we either need to revisit or decide that a top level `override` is still supported.

For example this one:

https://github.com/microsoft/vscode/blob/2a82df9437f5c1d3e0302ff4910a5e7f51ea1756/src/vs/workbench/contrib/notebook/browser/diff/notebookDiffActions.ts#L50-L59

**Comment by lramos15** [comment]
I think we have to support top level overrides in all cases because that's where we check for DISABLED and PICK. So maybe it's best to say side by side is the outlier because it resolves each half independently

**Comment by bpasero** [comment]
@lramos15 hm maybe we can do this then:

```
readonly options?: IEditorOptions & { override?: EditorResolution.DISABLED | EditorResolution.PICK };
```

Specifically for diff and side by side inputs to allow to set this top level.

**Comment by lramos15** [comment]
It will still complicate things. Is there a reason to not say we always allow top level override except in the case of side by side because side by side halves can be different for each half therefore the override must be unique to that editor side? That's the current implementation of everything

**Comment by lramos15** [comment]
Is it possible to reflect it via Typescript typing rules since SideBySide is a supertype to Diff but more strict?

**Comment by bpasero** [comment]
Ah yeah, I cannot type it due to the inheritance...

I pushed a change to clarify this in the JSDoc for diff and side by side (untyped) inputs.

We close this issue then?

**Comment by bpasero** [comment]
Spend more time thinking about this and feel we should leave the current `toUntyped` methods as they are: it does not make a lot of sense that the generic diff or side by side input apply any top level `override` in the `options` because they are most likely not the right editor to resolve. Rather the primary/modified side should be used always.
