### ISSUE TITLE
Error loading preloads when showing image in native notebook on remote

### ISSUE THREAD

**Issue by seyuboglu** [microsoft/vscode#127665]
Issue Type: <b>Bug</b>

When I run the following in a native Jupyter notebook on a Kubernetes pod...
```
import numpy as np
import matplotlib.pyplot as plt
plt.imshow(np.zeros((10,10)))
```
...I get: 
```
Error loading preloads:
Failed to execute 'fetch' on 'Window': Failed to parse URL from https://vscode-remote%2Bk8s-container%2Bcontext%3Dgke_hai-gcp-fine-grained_us-west1-a_cluster-1%2Bpodname%3Dpod-sabri-t4-4%2Bnamespace%3Ddefault%2Bname%3Dpod-sabri%2Bimage%3Dgcr.io%252fhai-gcp-fine-grained%252fdefault.vscode-resource.vscode-webview.net/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client_renderer/renderers.js
```

The problem is not limited to Matplotlib. I also run into the same issue when trying to use `tqdm.notebook`.  

I am not running into this issue locally. 

Extension version: 2021.6.999662501
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.89+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 3253bfa9-f4f2-4dc6-9afe-91a2465ce2f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|pod-sabri in pod-sabri-t4-4 (gcr.io/hai-gcp-fine-grained/default)|
|OS|Linux x64 5.4.89+|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (32 x 2199)|
|Memory (System)|117.94GB (92.71GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30322307
binariesv615:30325510

```

</details>

**Comment by seyuboglu** [comment]
Moving to vscode-jupyter repo https://github.com/microsoft/vscode-jupyter/issues/6487

**Comment by rchiodo** [comment]
This is a VS code issue, not a jupyter extension problem. Reopening here.

**Comment by rchiodo** [comment]
VS code is loading the jupyter extension preloads and failing to find them.

**Comment by seyuboglu** [comment]
Looks similar to https://github.com/microsoft/vscode/issues/126845

**Comment by sbatten** [comment]
duplicate #126845
