### ISSUE TITLE
Open Terminal As Tab

### ISSUE THREAD

**Issue by eustas** [microsoft/vscode#127608]
Currently terminal opens in drawer section and could be maximized.
But that is inconvenient - I have to maximize terminal every time I want to use it.
If terminal could be opened as "tab" this problem would not exist.

@Tyriar this is not dupe of #10546. I do not need multiple terminal tabs - I've just tired of maximizing the terminal every so often.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/125514

Already in Insiders and expected to release next week.

**Comment by eustas** [comment]
Thanks
