### ISSUE TITLE
Infinite loop saved modified

### ISSUE THREAD

**Issue by altreze** [Microsoft/vscode#12762]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1.  Install EditorConfig for VSCode version 0.3.3
2. add a .editorconfig file with
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = 0
trim_trailing_whitespace = false

3. Create a html file with no final_newline
4. Then save it

Result: the file loop between save and modified [adding final new line].

**Comment by joaomoreno** [comment]
Please file this in the appropriate EditorConfig extension repository.
