### ISSUE TITLE
Terminal editors have no context menu on linux

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127619]
Testing #127192

Terminal editors have no context menu on linux:

![2021-06-30_10-59-36 (1)](https://user-images.githubusercontent.com/1898161/123933349-9731ad80-d992-11eb-9fe7-d59da563d8db.gif)

Please note: I'm running ubuntu 21.04 in Parallels.

**Comment by Tyriar** [comment]
@weinand are you on the latest as the context menu was fixed yesterday, and does changing the `rightClickBehavior` setting change things?

**Comment by weinand** [comment]
I'm on:
<img width="575" alt="2021-06-30_13-53-09" src="https://user-images.githubusercontent.com/1898161/123956016-8a20b880-d9aa-11eb-88f5-d9a67a9b0eea.png">

Changing the setting "rightClickBehavior" to "copyPaste" makes the right mouse button paste immediately. But setting it to "default" does not enable the context menu.

**Comment by Tyriar** [comment]
Thanks for the extra info, I was having problems getting my linux vm running

**Comment by Tyriar** [comment]
Let's copy closer when TerminalView does, in particular remove the e.button check in the ctx menu event handler, remove the other contextmenu event handler and make sure `this._cancelContextMenu` is checked.
