### ISSUE TITLE
Environment variables in cmd different than in integrated terminal

### ISSUE THREAD

**Issue by rukaelin** [Microsoft/vscode#12774]
- VSCode Version: 1.5.3
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. type ```echo %ProgramFiles%``` in cmd -> ```C:\Program Files```
2. type ```echo %ProgramFiles%``` in integrated terminal -> ```C:\Program Files (x86)```

Why do the two commands not yield the same result?

**Comment by Tyriar** [comment]
This is because your `%COMSPEC%` environment variable is set to the 32-bit version of `cmd.exe`. If you want it to run the same shell you will want to use the `sysnative` version of `cmd.exe` as per the config docs https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

**Comment by rukaelin** [comment]
Thanks for the clarification
