### ISSUE TITLE
More language should support auto-closing of multiline comments.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#127779]
When writing typescript, typing `/**` automatically adds a closing `*/` - this is also the case in javascript, java and php.
https://github.com/microsoft/vscode/blob/main/extensions/typescript-basics/language-configuration.json#L18

Should auto closing of multiline comments be consistent across more languages?

The auto block comments extension adds this to a few other languages but should this already existing in the core extensions.
https://github.com/kevb34ns/auto-comment-blocks/tree/master/language-configuration

**Comment by aeschli** [comment]
`/** */`are doc comments that are a well-defined syntax in Java and JavaScript.

However, they are not established in languages like css. I'd rather not promote them for languages that don't have the concept, just for the sake of typing convenience. Users who want that, can install the auto-comment-blocks extension.

If `/** */`is used and well defined in a language, please add a link to a spec or example and I would add it.
