### ISSUE TITLE
Center watermark commands

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12779]

**Comment by bgashler1** [comment]
For anyone else who is interested, this is a very difficult problem to solve in CSS, if it's possible at all.  We will most likely need to use a script to do this.

CSS isn't so good at auto widths under circumstances like this, which is required to get this centered.  I can explain more if there are any questions.

**Comment by chrmarti** [comment]
@bgashler1 Would a table layout work? E.g.: http://codepen.io/anon/pen/xEAJJE

**Comment by bgashler1** [comment]
@chrmarti yes, actually that does it nicely.  The only gotcha is that we're now throwing away some of the nice semantics of having all the definition list items in one definition list.  But this visually addresses what some people were wanting to be addressed.

Could you put this in the code?

**Comment by chrmarti** [comment]
@bgashler1 Yes, will do. Thanks.

**Comment by chrmarti** [comment]
@bgashler1 Pushed a fix, could you take a look?

**Comment by bgashler1** [comment]
Looks great!

**Comment by octref** [comment]
@bgashler1 
Verified this but just wondering, isn't this trivial to solve with flexbox?

**Comment by bgashler1** [comment]
@octref I thought that might be a good solution at first, but couldn't seem to find a way to make it work the way we wanted.  Would love to learn what you would do for future reference.  Let's catch up sometime.
