### ISSUE TITLE
[loc][Query][VSCode] More context for string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#12775]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Built-in

File Name:
src\vs\workbench\parts\extensions\electron-browser\extensionsActions.nls.resx

Resource ID:
".resx", 0; "builtin"

Query:
Please clarify context here. What is built in?	CnE_Developer_Moravia_ITA1@hotmail.com	9/27/2016 12:42:39 PM

**Comment by joaomoreno** [comment]
An extension is _built-in_, which it comes contained within the product.

**Comment by mkyjakova** [comment]
hi @joaomoreno , Thanks! If I understand correctly then, in this case, the string refers to an extension. I'll let the translator know.
