### ISSUE TITLE
vscode extension Spark & Hive Tools incorrect gov cloud uri 

### ISSUE THREAD

**Issue by seamusa** [microsoft/vscode#127718]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

Issue Type: <b>Bug</b>

I am following the tutorial at: https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse

1) Install the Spark & Hive Tools
2) Login using Azure: Sign in to Azure Cloud
3) Set the default pool: Synapse: Set default Spark pool
4) You get the error below, as you can see the request uri is invalid for gov cloud. It should be login.microsoftonline.us and [.com]

{
    "error": {
        "0": "i",
        "1": "n",
        "2": "v",
        "3": "a",
        "4": "l",
        "5": "i",
        "6": "d",
        "7": "_",
        "8": "g",
        "9": "r",
        "10": "a",
        "11": "n",
        "12": "t",
        "statusCode": 400,
        "requestId": "-----"
    },
    "response": {
        "statusCode": 400,
        "body": "{\"error\":\"invalid_grant\",\"error_description\":\"AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified.\\r\\nTrace ID: 90a5109e-547a-4a78-9394-16c6a4483900\\r\\nCorrelation ID: 94a9c3c7-973e-4b63-88c7-cfeff43ef671\\r\\nTimestamp: 2021-06-30 22:03:07Z\",\"error_codes\":[90051],\"timestamp\":\"2021-06-30 22:03:07Z\",\"trace_id\":\"-----\",\"correlation_id\":\"-----\"}",
        "headers": {
            "cache-control": "no-store, no-cache",
            "pragma": "no-cache",
            "content-type": "application/json; charset=utf-8",
            "expires": "-1",
            "strict-transport-security": "max-age=31536000; includeSubDomains",
            "x-content-type-options": "nosniff",
            "p3p": "CP=\"DSP CUR OTPi IND OTRi ONL FIN\"",
            "x-ms-request-id": "-----",
            "x-ms-ests-server": "2.1.11829.9 - EUS ProdSlices",
            "set-cookie": [
                "fpc=AjymYtInl0xCtAy_7D2b-p0; expires=Fri, 30-Jul-2021 22:03:07 GMT; path=/; secure; HttpOnly; SameSite=None",
                "x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly",
                "stsservicecookie=estsfd; path=/; secure; samesite=none; httponly"
            ],
            "date": "Wed, 30 Jun 2021 22:03:06 GMT",
            "connection": "close",
            "content-length": "434"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "login.microsoftonline.com",
                "port": 443,
                "hostname": "login.microsoftonline.com",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/-----/oauth2/token",
                "path": "/-----/oauth2/token",
                "href": "https://login.microsoftonline.com/-----/oauth2/token"
            },
            "method": "POST",
            "headers": {
                "Content-Type": "application/x-www-form-urlencoded",
                "user-agent": "Azure-SDK-For-Node.js/0.9.20",
                "content-length": 1386
            }
        }
    }
}

Extension version: 1.1.15
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by TylerLeonhardt** [comment]
Can you open this over in https://github.com/microsoft/Spark-Hive-Tools ? Thanks!
