### ISSUE TITLE
Allow disabling starting multiple instances of a launch config

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#127721]
I'd like a setting to disable the ability to start a launch config multiple times.

Also, @isidorn mentioned that it might be possible to start multiple instances accidentally by pressing F5 twice quickly, and we could fix that independently of a setting.

**Comment by isidorn** [comment]
I would not like to introduce a setting for this case, and ideally we could figure out a solution which works for everybody. Maybe we should simply prompt: "Are you sure you already have the same session running.."

Pressing F5 quickly should ideally not be a problem because we disable starting debugging while another session is in the `INIT` phase.

**Comment by weinand** [comment]
Yes, I still like the prompt (because that was my initial proposal).

**Comment by isidorn** [comment]
I have added a prompt. Feedback on the wording is very welcome. Thanks!

![Screenshot 2021-08-04 at 20 27 24](https://user-images.githubusercontent.com/1926584/128234870-45f11e53-8cb5-4562-a18c-351b6012a7b2.png)

**Comment by roblourens** [comment]
It's more like "Start a second instance" right? This sounds like I am restarting it

**Comment by weinand** [comment]
My proposal:
> 'Launch Program' is already running. Do you want to start another instance?

**Comment by isidorn** [comment]
@weinand @roblourens thanks! I like that wording as it makes it more clear. I have updated it.

**Comment by iamwwc** [comment]
How I can disable this? https://github.com/microsoft/vscode/issues/132201

It's annoying. I don't want vscode to stop me to press f5 twice

**Comment by weinand** [comment]
@iamwwc do you really want to start multiple concurrent debug sessions or do you just want to restart your session?

**Comment by iamwwc** [comment]
I'm developing some rust app, restart just restart previous binary, don't recompile it. So I use macros to `first stop and then start`, which make sure lldb rebuild my project.

But I found `stop and then start` cause showing confirm dialog. After some discovery, It seems executeCommand will run commands concurrently

Could you follow this steps to reproduce the issue?
https://github.com/microsoft/vscode/issues/132446

**Comment by mccambria** [comment]
I agree with iamwwc. In my case I really do want multiple concurrent debug sessions running. A "don't ask again" button would be great.
