### ISSUE TITLE
Bad option error

### ISSUE THREAD

**Issue by bodydisplaynone** [microsoft/vscode#127771]
Issue Type: <b>Bug</b>

When rebasing and trying to commit I get an issue that says "bad option --wait" and after that terminal is the only option to commit and continue the rebase. This happens every single time if there are commits to be done during rebase.
![image](https://user-images.githubusercontent.com/22660372/124124434-b571d900-da78-11eb-9727-9fd240973585.png)

Git log:
![image](https://user-images.githubusercontent.com/22660372/124124502-c91d3f80-da78-11eb-91b2-571c75f5af4d.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.94GB free)|
|Process Argv|--crash-reporter-id d5644348-7098-4b1a-b15e-7d9fb6b0462d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
quitcontrol-vscode|art|3.2.1
vscode-log-viewer|ber|0.12.2
vscode-intelephense-client|bme|1.7.1
run-cy|cor|0.1.1
dart-code|Dar|3.23.1
flutter|Dar|3.23.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
phpunit|ema|4.1.1
vscode-env|Iro|0.1.0
svn-scm|joh|2.13.6
inline-parameters|lia|0.2.1
vscode-pastery|max|0.0.4
rainbow-csv|mec|1.8.1
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
vsliveshare|ms-|1.0.4498
php-docblocker|nei|2.1.0
copy-file-name|nem|1.2.0
vetur|oct|0.34.1
material-icon-theme|PKi|4.7.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
LiveServer|rit|5.6.1
php-debug|rob|1.14.0
vscode-cy-helper|She|1.2.2
vuetify-vscode|vue|0.2.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30322306
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by lszomoru** [comment]
@bodydisplaynone, are you able to reproduce the same behaviour with the latest version of VS Code? Thanks!

**Comment by bodydisplaynone** [comment]
Oh my god sorry for the super late reply. Also, I did not use rebase for a while now, but apparently yes, it's still showing this issue even with the latest version.

![image](https://user-images.githubusercontent.com/22660372/150127099-bcd2a934-6758-4fbe-8912-b12c60732e3b.png)

Console:

![image](https://user-images.githubusercontent.com/22660372/150127250-2e70ac93-6c03-4b51-a890-b4ec80d6e11f.png)

**Comment by lszomoru** [comment]
Related to https://github.com/microsoft/vscode/issues/114461
This issue should be fixed in today's Insiders release (2022-07-21) or later.
Please give it a try and let me know if you are still experiencing the issue. Thank you!

**Comment by bodydisplaynone** [comment]
Hi sorry for not replying earlier, the email got lost in my inbox. :)
Thanks for the update, I think probably that's why I forgot about it
totally since it seems to be working now.

Ladislau Szomoru ***@***.***> ezt írta (időpont: 2022. júl.
21., Cs, 15:52):
