### ISSUE TITLE
Input history is not retained on reload

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#127701]
Testing https://github.com/microsoft/vscode/issues/127378

- Execute some instructions from input editor in interactive window
- Reload VS Code
- Interactive window retains the executions but the input editor does not retain the history

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/6460, we have disabled hot exit for the built-in interactive window for now
