### ISSUE TITLE
Can we make [[functionLocation]] a clickable link? (within Breakpoint Hover)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#127795]
Sometimes I need to go deep into library code, thanks to the debugger i'm able to find the function to investigate. However I always find it quite fiddly to go directly to this function. Below you'll see what I mean.

In this gif the path is long, and I need to keep it selected whilst moving the horizontal scroll bar. It can become a right chore.
![functionLocation](https://user-images.githubusercontent.com/936006/124036634-38058480-d9f6-11eb-90c3-56b12bdb11bf.gif)

Is it possible to make that path a clickable link which opens a new tab?

**Comment by isidorn** [comment]
I think it is not realistic to improve the link detection this milestone with the other things planned. Moving out to On Deck. Feel free to move back to August if somebody considers this crucial.
