### ISSUE TITLE
Debug, Run File, Run Selection no longer working with 1.57.1

### ISSUE THREAD

**Issue by beanboyrjs** [microsoft/vscode#127712]
Issue Type: <b>Bug</b>

I updated to 1.57.1 and all "Run" functionallity has stopped working. I cannot Start Debugging, Run Active File..., or Run Selection... at all. If I try the Start Debugging, the Debug panel shows, and the debug toolbar shows, but nothing else happens. When I try either of the Run options, nothing happens. I have attempted restarting VSCode and my computer with no change. I have tried multiple versions of PowerShell (what I am trying to debug/run) with no change. I was able to do all debug/run actions immediately prior to updating.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.11GB free)|
|Process Argv|--crash-reporter-id 0e4ff37e-88e8-450a-b009-f2dd3973e336|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-profile-switcher|aar|0.3.3
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
vscode-color|ans|0.4.5
vscode-custom-css|be5|5.0.3
emojisense|bie|0.8.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.1
vbscript|Dar|1.0.4
xml|Dot|2.5.1
gitlens|eam|11.5.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vs-code-xml-format|fab|0.1.5
vscode-pull-request-github|Git|0.27.1
todo-tree|Gru|0.0.213
vscode-test-explorer|hbe|2.20.4
vscode-git-tags|how|1.4.4
rest-client|hum|0.24.5
powershellprotools|iro|5.28.7
vscode-peacock|joh|3.9.1
powershell-extension-pack|jus|0.0.5
vscode-home-assistant|kee|1.19.0
vscode-gist|ken|3.0.3
wrapSelection|kon|0.10.0
regexp-preview|Lou|0.1.5
MagicPython|mag|1.1.0
vscode-autohotkey-plus-plus|mar|2.8.1
rainbow-csv|mec|1.8.1
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2021.6.2
test-adapter-converter|ms-|0.0.10
vsliveshare|ms-|1.0.4498
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
vscode-json-editor|nic|0.3.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.7.0
vscode-github-projects|Pod|1.0.0
psi-header|psi|1.15.2
vscode-data-preview|Ran|2.3.0
vscode-thunder-client|ran|1.6.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
vscode-sort-json|ric|1.20.0
synthwave-vscode|Rob|0.1.8
platform-settings|run|1.0.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.21
vscode-zipexplorer|sle|0.3.1
vba|spe|1.7.1
tabnine-vscode|Tab|3.4.12
vscode-inline-values-powershell|Tyl|0.0.5
vscode-pester-test-adapter|Tyl|0.0.23
errorlens|use|3.3.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
codetour|vsl|0.0.56
gistfs|vsl|0.2.9
gitdoc|vsl|0.0.8
better-align|wwm|1.1.6
vscode-surround|yat|1.1.2
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30322307
binariesv615:30325510
vsccppwt:30329788
aatestflight:30331711

```

</details>

**Comment by weinand** [comment]
What debugger are you using?

**Comment by beanboyrjs** [comment]
I am using the VSCode debug feature.


At Your Service,

Randy

**Comment by weinand** [comment]
There are hundreds of VS Code debuggers... What language are you debugging?

**Comment by beanboyrjs** [comment]
Sorry, I misunderstood what you meant. I am trying to debug PowerShell, as I mentioned in the original report. I have the latest versions of VS Code, PowerShell, Windows PowerShell, the PowerShell extensions for VS Code.


At Your Service,

Randy
