### ISSUE TITLE
No debug toolbar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127774]
Seem flaky (as soo often unfortunately) and without clear repo steps... I have been making some attempts to debug those lines and now I am connected but also not?

<img width="1225" alt="Screen Shot 2021-07-01 at 14 49 02" src="https://user-images.githubusercontent.com/1794099/124126973-7ee98d80-da7b-11eb-94a1-6d0f2be7f091.png">

**Comment by isidorn** [comment]
This will be fixed in insiders once we release it today. 
Closing as dup of https://github.com/microsoft/vscode/issues/127418
And if you see it again after the update please let me know and I will investigate further
