### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by charanvinay** [microsoft/vscode#127768]
Issue Type: <b>Feature Request</b>

where can i login in visual studio

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

**Comment by IllusionMH** [comment]
/question

See https://code.visualstudio.com/docs/editor/settings-sync
