### ISSUE TITLE
vscode shows 'not responding' alert when opening a context menu and waiting

### ISSUE THREAD

**Issue by Eksrow** [Microsoft/vscode#12771]
I'm not even sure if this is even worth fixing as I've **never** seen this during normal usage.
I found out about it when I was thinking about adding an action to a context menu and staring at it for a while. Vscode will show an alert about 30 seconds in about the window not responding when it is in fact still fine.

- VSCode Version: 1.5.3
- OS Version: Windows 10-14393

Steps to Reproduce:

1. Open any project.
2. Right click on any file.
3. Wait.

Here's a video: https://docs.google.com/uc?id=0B3gaEinIV1dCeEZVaEdzMG9vVnc (skip to :30)

**Comment by bpasero** [comment]
This has been fixed in our insiders build. 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
