### ISSUE TITLE
Insiders Build fills up memory of server in Remote SSH

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode#127728]
- VS Code Version: 
```
Version: 1.58.0-insider (user setup)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000
```
- OS Version: Windows 11

Steps to Reproduce:

I noticed that the latest VSCode insiders build fills up the server's memory completely when doing Remote SSH (Windows 11 Host, Ubuntu 20.04 Server) - It had 15 GB free memory and doing remote SSH filled up all of the 15GB. We noticed that it was the node process which is run by VSCode which is consuming the memory when debugging it.

This does not happen in the stable build though.

**Comment by tvvignesh** [comment]
The interesting thing though is that this does not happen in all servers with the same insider build and same set of extensions. So, I am assuming its something to do with `..vscode-server-insiders` in the server - not sure how to identify it though.

**Comment by roblourens** [comment]
Which process? Which extensions are installed? Does it happen immediately or when you take some action?

**Comment by tvvignesh** [comment]
@roblourens Thanks for your response. These are the extensions I have in `.vscode-server-insiders`

![image](https://user-images.githubusercontent.com/1165845/124210021-5360b480-db08-11eb-9dd2-bce10d055b09.png)

This happens immediately after I do remote ssh filling up the RAM (and RAM fills up in 30 seconds or so after doing Remote SSH and running no other process). I do definitely think that its because of one of these extensions because `.vscode-server` does not have any extensions installed and it works great.

I could have filed an issue against the respective extension causing this issue after figuring it out, but my concern here is that, since VSCode acts as a platform where all the extensions run, shouldn't VSCode enforce memory limits to the extensions which run on top and the child processes it runs, be it remote ssh or direct on host? Cause the memory jump is way too high (from 1GB to filling up 16GB be it due to probable orphan processes created by the extensions).

How can we avoid situations like these considering it is difficult for a user to know this behavior in advance until they try out the extensions. In this case, since the RAM got filled up when doing remote ssh, the server actually crashed thrice which is when we figured out the cause of issue. Thanks 🙂

**Comment by roblourens** [comment]
> shouldn't VSCode enforce memory limits to the extensions which run on top and the child processes it runs, be it remote ssh or direct on host

Our extension model doesn't really allow this. Extensions have full access to node APIs and aren't running in a sandboxed vscode environment. We do offer the command `Start Extension Bisect` which will disable your extensions in several rounds to help you figure out which extension is causing the bad behavior.
