### ISSUE TITLE
specify shell in operating system specific properties (vscode tasks)

### ISSUE THREAD

**Issue by abdennourzahaf** [microsoft/vscode#127719]
I would like to specify the shell to use on windows.
Following this: https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties does not work and results in:

![image](https://user-images.githubusercontent.com/62243290/124042293-730cb580-da00-11eb-8b0b-1b088f5d7f6d.png)

And following this: https://code.visualstudio.com/docs/editor/tasks-appendix#_schema-for-tasksjson does not work also

**Comment by alexr00** [comment]
I'm not able to reproduce this.
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Run Node",
			"type": "process",
			"command": "node",
			"windows": {
				"options": {
					"shell": {
						"executable": "powershell.exe"
					}
				}
			}
		}
       ]
}
```

Does this issue occur if you disable all your installed extensions? What version of VS Code are you using?

**Comment by abdennourzahaf** [comment]
@alexr00 Your code works fine, and it pointed out what I was doing wrong. Thank you so much.
