### ISSUE TITLE
Auto complete brackets not working on .js files

### ISSUE THREAD

**Issue by yashweblife** [microsoft/vscode#127731]
Issue Type: <b>Bug</b>

Info:
autoCompleteBrackets is set to the default setting and has been tried with always,
VS Code was reloaded on each attempt,
Computer was restarted on each attempt,
Works on .html and .css as intended

Reproduction:
If you enter
var x = [
Expected Result:
var x = []
Actual Result:
var x = [

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.37GB (2.73GB free)|
|Process Argv|--crash-reporter-id 40c1a99e-c4ea-4987-addb-bf7832d1942d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|8.0.1
copilot|Git|1.1.1899
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
vsliveshare|ms-|1.0.4498
vetur|oct|0.34.1
platformio-ide|pla|2.3.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by yashweblife** [comment]
Problem Solved, I uninstalled the GitHub copilot extension and it seems to have fixed the issue, Im not a member yet so i think it just ran its settings anyway

**Comment by utopictown** [comment]
uninstalled Github copilot resolved mine too
