### ISSUE TITLE
Auto split strings by "+" if press enter in a string literal. (Or allows language service to specify)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode#127752]
From https://github.com/microsoft/TypeScript/issues/44528. But I think it's might need vscode support.

```ts
let str = 'a very very /*cursor*/very long string'
```

Press Enter at `/*cursor*/`.

```ts
let str = 'a very very ' +
    'very long string'
```

**Comment by mjbvz** [comment]
I think we should test this in an extension initially. If the extension/feature is popular enough, we could add it to VS Code core

**Comment by Kingwl** [comment]
It's might need language service support. But AFAIK we cannot use (for example: TypeScript) service in our own extension.

Should we start a new ts server? Or we may register some command like `typescript.forwardRequest` ?
