### ISSUE TITLE
Questionable implementation of getProcessId

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12770]
Testing https://github.com/Microsoft/vscode/issues/12595

See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTerminalService.ts#L44

```typescript
public get processId(): Thenable<number> {
	this._checkDisposed();
	if (this._processId) {
		return Promise.resolve<number>(this._processId);
	}
	setTimeout(() => {
		return this.processId;
	}, 200);
}
```

First of all, if you reach the `setTimeout`, there is no return value after all (just `undefined`). And then, how do you know that the process id is there after 200ms?

**Comment by Tyriar** [comment]
Inside the promise it recurses as it returns the getter not the backing value, I was planning on removing the `setTimeout` in October https://github.com/Microsoft/vscode/issues/12434

Fixing the bug now though.

**Comment by bpasero** [comment]
And the 200ms is just a guess?

**Comment by Tyriar** [comment]
Yes, it likely only needs much less than that thought. I'll improve it in October.
