### ISSUE TITLE
`TreeItem`s that start expanded do not retain their current state upon refresh

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#127711]
When a `TreeItem` is expanded by default, collapsed, and then refreshed, it's replaced by an expanded `TreeItem` (i.e. it's former collapsed status is not respected).  This does *not* happen when a `TreeItem` is collapsed by default.  (In that case, if expanded, the replacement `TreeItem` will continue to be expanded after a refresh.). It's not clear if this asymmetry is intentional or not.

Does this issue occur when all extensions are disabled?: N/A (as it involves an extension API)

- VS Code Version: 1.58.0-insider
- OS Version: Windows 21H2 (OS Build 22000.51)

Steps to Reproduce:

1. Create and register a tree view (i.e. `vscode.TreeDataProvider<T>`)
2. Have the provider return children which themselves return children.
3. Have the "parent" `TreeItem` start expanded (i.e. specify `vscode.TreeItemCollapsibleState.Expanded` in their constructor).
4. Collapse one or more of the "parent" `TreeItem`s.
5. "Refresh" the tree view by returning an equivalent set of children (e.g. `TreeItem`s with the same label/IDs).

Expected Result:

The tree view is identical to the tree view prior to the refresh.

Actual Result:

The collapsed parent `TreeItem`s are now expanded.

**Comment by alexr00** [comment]
The fix is a simple revert of https://github.com/microsoft/vscode/commit/c683180c66370823c5218bd20de6942035fbbc87
