### ISSUE TITLE
Base cell text model npe

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#127738]
Issue Type: <b>Bug</b>

* Shift+Click on two github issue notebook files, right click, compare selected
* Close the diff editor
* Open one of the notebook

```
Cannot read property 'onDidChangeContent' of undefined: TypeError: Cannot read property 'onDidChangeContent' of undefined
    at CodeCellViewModel.resolveTextModel (vscode-file://vscode-app/c:/Users/rebor/code/vscode/out/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.js:389:47)
```

VS Code version: Code - Insiders 1.58.0-insider (57930758db9e2c83f59b9ee1851400bd16192d32, 2021-06-30T05:14:00.370Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (5.38GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|25.01GB (13.80GB free)|
|VM|0%|
</details>

**Comment by rebornix** [comment]
The `this.textModel` can be `undefined` and resolve model reference will not set `textModel`

https://github.com/microsoft/vscode/blob/cd08aa00815d3f0086ed4b9d3174c5eba1a72e15/src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts#L496-L507

It was introduced by https://github.com/microsoft/vscode/commit/5b6f939eb2a43c34129dbab45c269af96e1f0f6b and before the change, `textModel` will be valid after calling `this._textModelRef = await this.model.resolveTextModelRef();`.

**Comment by rzhao271** [comment]
I followed the steps in the original issue by comparing notebooks A and B. However, I already had notebooks A and B open in their own tabs, and when I closed the diff editor, the editor for notebook A showed up with the NPE.

![](https://user-images.githubusercontent.com/7199958/124320639-178e1500-db31-11eb-92d1-f999c8d8c93f.PNG)

**Comment by rebornix** [comment]
@rzhao271 thanks, good catch. It's related to adopting the `DiffEditorInput`. Now `NotebookDiffEditorInput` inherits from `DiffEditorInput` and we resolve the editor models for original and modified resource by the `NotebookEditorInput`, which holds a `ref` to the underlining text model. In the `dispose` of `NotebookDiffEditorInput`, we should not dispose editor models ourselves, instead they should be handled by `NotebookEditorInput`'s lifecycle (which will dispose `ref` correctly).
