### ISSUE TITLE
paste a file with existing file name in vscode cause them to rename instead of replace existing file

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode#127746]
I am not sure what happened to the replace file dialog, but it's not working when I copy a file from inside the the vscode. 

I tried to find a config but google is not giving any good result back. I also asked the question in [SO](https://stackoverflow.com/questions/68177191/paste-a-file-with-existing-file-name-in-vscode-cause-them-to-rename-instead-of-r) but no one answered it. 

when I copy a file to a folder that a file with the same name exist, the new file get renamed instead of showing the replace dialog box.

for example, if I copy a file `abc.jpg` from one folder into another folder that `abc.jpg` exist. i will end up with two files that the old one is `abc.jpg` and new one is `abc copy.jpg`

it's new feature and wasn't like this before. previousley, if I paste a file into its origin folder it get renamed, but when I copy into another folder, it asked for replacement, but now it's just renaming, even if the source and destination folder is different. 

Unfortunately, I can't find any configuration to change it, also keywords such as "copy", "file", "replace" is too generic that I can't find a solution for this problem by just googling it. 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/xca1t.gif

**Comment by isidorn** [comment]
I believe this was always behaving like this. If you think this was behaving differently before can you please provide the vscode stable version when it was offer to overwrite.

**Comment by mhamri** [comment]
this is from SO answer, but I am not sure what version he is using also I faced this dialog box before.

![](https://i.stack.imgur.com/EIZut.png)

**Comment by isidorn** [comment]
That is when you drag and drop from outside of vscode...

**Comment by isidorn** [comment]
This is a fair request to have that a bit more unified. However nothing we have plans to change -> backlog.
Once we receive more feedback we might jump on this.

**Comment by mhamri** [comment]
this is a very minimal task to bring a more predictable result to the vscode. please reconsider as it helps alot when moving files from one project to another project

**Comment by chandu-007** [comment]
Yes i agree with @mhamri

**Comment by JC-LGMS** [comment]
me too

**Comment by mhamri** [comment]
@chandu-007  @JC-LGMS  please like the original thread, if we reach 10 like probably we can reopen it

**Comment by muhfiz** [comment]
please consider it

**Comment by kbtganesh** [comment]
C'mon man.. You expect us to paste it and manually delete the existing file & rename the pasted file again? At least you should have a setting to choose what to do when pasting the file with same filename.
As a workaround, use windows file explorer to do paste & replace files.

**Comment by kbtganesh** [comment]
> That is when you drag and drop from outside of vscode...

And what's the reason for having replace at that scenario alone? Don't you think it will be useful if we do the same in vscode itself?

**Comment by mhamri** [comment]
@isidorn this feature request has 10 likes, could we reopen it?

**Comment by zhuweiyou** [comment]
I also want to overwrite the confirmation instead of creating a new file.

**Comment by b10102016** [comment]
Recently, face this problem too. Please consider to reopen this.

**Comment by okorieebube** [comment]
Reopen this issue please. I believe this feature is helpful and very intuitive to how users use the software

**Comment by dJani97** [comment]
Someone recommended to just open the explorer and copy-paste files. But it's not so easy.

For example, in vscode, I can see which files have changes in them, so I may want to copy-paste only those files.

On any conflict, there should be a popup with overwrite and rename options.

**Comment by mhamri** [comment]
look like it is resloved with the latest vscode ` explorer.incrementalNaming: disabled`. please give it a try and update

**Comment by okorieebube** [comment]
> look like it is resolved with the latest vscode ` explorer.incrementalNaming: disabled`. please give it a try and update

Hi, why does it throw this warning though? `Value is not accepted. Valid values: "simple", "smart".(1)`

**Comment by mhamri** [comment]
@okorieebube it's a value just added in vscode 1.72.0. please see if your vscode is updated to the latest or not

**Comment by mhamri** [comment]
so I tested it and if you paste a file that another file with the same name exists in the folder it will take one of these action based on your setting

simple -> add -copy to end of the file name 
smart -> file name get an incremental number 
disabled -> ask to replace the file

**Comment by okorieebube** [comment]
> so I tested it and if you paste a file that another file with the same name exists in the folder it will take one of these action based on your setting
> 
> simple -> add -copy to end of the file name smart -> file name get an incremental number disabled -> ask to replace the file

It works now, Thanks Mhamri.

**Comment by chandu-007** [comment]
Yes I have tested it is working now.

**Comment by anthonyvdotbe** [comment]
Exactly as @Tony-Sol says. I opened #165217 some time ago (as a feature request, since technically the behavior is correct, but it's really a usability bug).

**Comment by tirathsharma098** [comment]
@isidorn 
I don't think this is fine to rename the file without even developer or user knowledge that folder is renamed, which will lead us in an errors and bugs, at least @VSCodeTriageBot should show a pop up or dialog box that folder with same name already exists with options like rename,  overwrite.

**Comment by tirathsharma098** [comment]
> @isidorn I don't think this is fine to rename the file without even developer or user knowledge that folder is renamed, which will lead us in an errors and bugs, at least @VSCodeTriageBot should show a pop up or dialog box that folder with same name already exists with options like rename, overwrite.

Please reopen this issue

**Comment by fiterV** [comment]
Issue is still present on 1.92.1 version
