### ISSUE TITLE
Tabs: clicking on inactive tab no longer makes group active

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127773]
Maybe a regression from our work to prevent focus going into the editor when clicking a tab. Steps:
* open 2 editors side by side
* click the tab of the inactive editor group

=> 🐛 that group is not becoming active

**Comment by isidorn** [comment]
Yeah, this is part of our change that tap on the tab does not focus the editor.
I still think this change makes sense.

So I have pushed a fix, to explicitly focus the group if we are not passing focus to the editor.

**Comment by isidorn** [comment]
@bpasero yeah that is neater, thanks for pointing it out! Tackled it.
