### ISSUE TITLE
Cropped/crippled telemetry event worries

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127789]
There is places where telemetry events contains large data, often it's about sending JSON-strings as property value. This can yield to problems because property values are simply cut at 1023 characters. This is problematic because

* it is wrong, apparently the limit is 8192 character (https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#limits)
* it is silent! there is no way to tell how much data we loose because of that. no exeception, no error log, no meta telemetry event
* there is apparently so solution for sending large amounts of data...

**Comment by jrieken** [comment]
fyi @alexdima

**Comment by jrieken** [comment]
Adding a sample to make this more real: We have performance marks that anyone can add to the source anywhere, like [here](https://github.com/microsoft/vscode/blob/98892391922d7e065ae20d1696cd278095de9843/src/vs/workbench/electron-sandbox/splash.ts#L43) or [here](https://github.com/microsoft/vscode/blob/98892391922d7e065ae20d1696cd278095de9843/src/vs/workbench/electron-sandbox/splash.ts#L43).

All performance marks can be retrieved in a single call and it would be helpful to send them as one event but that doesn't work because the data is too large. Instead, each event is send individually which makes this a kusto nightmare because these event must all be correlated on a session id.

**Comment by lramos15** [comment]
I don't see anywhere we truncate telemetry events on our end. Maybe this was rewritten with all the refactors, but I believe whatever size appinsights handles we do as well. @sbatten Are we truncating somewhere in the pipeline?

**Comment by lramos15** [comment]
Updated the length to 8192 and added a warning to note when properties are getting truncated

**Comment by jrieken** [comment]
I have even seen the warning!
