### ISSUE TITLE
Improve Inline Value Debug View

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127751]
These rendered inline values are not really helpful.
It would be nice if the parameter values were shown (in particular `modelLineNumber`).

![image](https://user-images.githubusercontent.com/2931520/124099066-6f5b4c00-da5d-11eb-9573-0f65cd82b9ac.png)

**Comment by isidorn** [comment]
I agree this could be improved but I think this will be tackled via https://github.com/microsoft/TypeScript/issues/43449 once Typescript is able to provide exact inline values. Then we will not use a limited regex heuristic that we have on the vscode side

@weinand probably knows more on the timing on the TS side

For reference inline values on the vscode side are computed here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L593

**Comment by weinand** [comment]
Yes, we will need https://github.com/microsoft/TypeScript/issues/43449 before we can fine tune what gets shown as inline values. You might want to add a comment there...

**Comment by hediet** [comment]
Thanks!

Quick question: Does this middle of line inline values or are they always rendered at the end of the line (like they currently are)?

For parameter values, I think it makes a lot of sense to render numbers/booleans in the middle of the line (potentially with injected text 😉)

**Comment by weinand** [comment]
Showing inline values at the end of a line is an implementation detail of VS Code. The extension API for inline values does not stipulate that. From the API VS Code knows the source range of the variable/parameter, so we could easily show the value next to the parameter.
