### ISSUE TITLE
Up and down arrows are going to beginning or end of the line first before navigating history

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#127709]
Testing https://github.com/microsoft/vscode/issues/127378

In the input editor of interactive window, Up and down arrows are going to beginning or end of the line first before navigating history

**Comment by rebornix** [comment]
This follows the behavior with SCM but probably doesn't align with Debug console. cc @joaomoreno @isidorn considering we are building a shared component for this.

**Comment by isidorn** [comment]
@rebornix there is already some reuse with the [HistoryNavigationWidget](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/history.ts#L6)

Both with https://github.com/microsoft/vscode/issues/127498 I thought that the debug console input and IW input can share a bit more (looks, expansion to multi lines etc)

I just noticed there is an issue in the debug console as well: up and down does not navigate history when the input is not empty. I will look into this.

**Comment by joyceerhl** [comment]
Got user feedback on this: https://github.com/microsoft/vscode-jupyter/issues/6567

> In my opinion, it would be best if a single up/down arrow press moved to the previous cell if cursor is on the top/bottom-most line, as opposed to jumping to the start/end of the line, (how it worked in the old webview interactive).

**Comment by amunger** [comment]
as designed
