### ISSUE TITLE
Typo in workbench.startupEditor readme description

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#127794]
- VS Code Version: 1.57.0 Insiders
- OS Version: Windows 10

'ccnfiguration' -> 'configuration'

![image](https://user-images.githubusercontent.com/12818376/124154486-6745e100-da4a-11eb-84ca-3b6b088d7bc7.png)

**Comment by JacksonKearl** [comment]
Thanks, fixed via #127893.
