### ISSUE TITLE
can't have two files with the same name open at the same time

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#12776]
- VSCode Version: 1.5.3
- OS Version: ubuntu 14

A lot of types of software projects require having specially named files (CMakeLists.txt, etc) which appear in multiple places within the project but have the same name. Unfortunately, vscode seems to treat them all as if they are the same file, only allowing one instance to be open at a time. This is _very_ confusing, as you can accidentally, and very subtly, change the file you are editing from the one you thought it was. Code should use the path of files to disambiguate them, and allow having multiple files of the same name open at the same time.

Steps to Reproduce:

1. Create two files with the same name, but different paths
2. try to have them both open, and fail

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`
