### ISSUE TITLE
auto closing brackets not working on vscode 1.57

### ISSUE THREAD

**Issue by ashraf-kabir** [microsoft/vscode#127739]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57
- OS Version: ubuntu 20.04.2 LTS

Steps to Reproduce:

1. open a js file on code
2. type a opening bracket (
3. expected result ()
4. actually getting (
5. bracket is not auto closing

**Comment by ashraf-kabir** [comment]
@alexdima I set editor.autoClosingBrackets always.
can you kindly watch the screenrecord ->
https://www.loom.com/share/cf6818f399d441be90fcce5d7b77c5da

**Comment by 0wx** [comment]
I had the same issue suddenly this morning, but I finally get this work by specify the language
![image](https://user-images.githubusercontent.com/28288911/124206537-ccaed600-db0d-11eb-872f-a1c7cd6ad7cd.png)
But it's still not work globally, only the language specified.
![image](https://user-images.githubusercontent.com/28288911/124206601-e7814a80-db0d-11eb-8a3b-79b1794c6b24.png)
![image](https://user-images.githubusercontent.com/28288911/124206628-ef40ef00-db0d-11eb-9465-5f70ff833e48.png)

**Comment by ashraf-kabir** [comment]
@0wx language specific way it worked. Thanks.

**Comment by Arctomachine** [comment]
Encountered this issue as well.
It stopped working suddenly, in the middle of coding session. Not working in JS and Python.
Adding `"editor.autoClosingBrackets": "always"` globally does not solve the issue. Only language-specific settings work.

**Comment by bboychris168** [comment]
I also just got this problem as well. 

![image](https://user-images.githubusercontent.com/43663480/124395432-7af19000-dd47-11eb-9da4-d466f413dc6a.png)

**Comment by alexdima** [comment]
This might be defined by an extension. Are you by any chance using copilot?

**Comment by Arctomachine** [comment]
> 
> 
> using copilot?

I have it installed, but not working yet, because I'm not in the preview program yet.

**Comment by alexdima** [comment]
Copilot is defining these default language settings that can be overwritten only using language specific settings. They do that to workaround an issue in vscode tracked at https://github.com/microsoft/vscode/issues/125663 . Once we ship our next stable release (sometime this week), they will be free to remove that workaround. Until then you can disable the extension if you are not in the preview program yet or you can define the language specific setting e.g.:
```
"[typescript]": { "editor.autoClosingBrackets": "languageDefined" }
```

**Comment by bboychris168** [comment]
> Copilot is defining these default language settings that can be overwritten only using language specific settings. They do that to workaround an issue in vscode tracked at #125663 . Once we ship our next stable release (sometime this week), they will be free to remove that workaround. Until then you can disable the extension if you are not in the preview program yet or you can define the language specific setting e.g.:
> 
> ```
> "[typescript]": { "editor.autoClosingBrackets": "languageDefined" }
> ```

This fixed it for me.

**Comment by adam91holt** [comment]
I was running into this and it looks like it is the new CoPilot plugin that causes this to stop working. Just uninstall and you should be back to normal.

**Comment by crackerberries** [comment]
i uninstalled copilot and yet the issue persists. it WAS caused by copilot as it occured immediately after i installed it, but i disabled it and it still hasnt gotten rid of it. any fixes yet?

**Comment by crackerberries** [comment]
i tried installing copilot again and it just doesn't work at all.

**Comment by Rotion63** [comment]
I also have this issue after installing copilot. Disabling it and reopening the vs code works for me.

**Comment by z7pz** [comment]
> I also just got this problem as well. It is on always. But when i edit my code the auto closing brackets doesnt work.
> 
> ![image](https://user-images.githubusercontent.com/43663480/124395432-7af19000-dd47-11eb-9da4-d466f413dc6a.png)

i just install copilot and the problem happen, so just disable and i hope that will fix :+1:

**Comment by unownone** [comment]
Same thing is happening with me but with python instead. Weirdly it doesn't happen if its a text file and even in a IPython notebook

**Comment by alexdima** [comment]
@unownone You can workaround using `"[python]": { "editor.autoClosingBrackets": "languageDefined" }`

**Comment by crackerberries** [comment]
@alexdima do i have to do this on every language individually? or is there a way to do it for all

**Comment by crackerberries** [comment]
I FOUND A SOLUTION!

go into settings.json and delete this:
![image](https://user-images.githubusercontent.com/84464177/124962255-14aa8d00-e027-11eb-8c4a-e9c4463e7d9a.png)

and save, and it's fixed!

**Comment by letsandeepio** [comment]
I had the same issue, but it went away after I disabled the Copilot extension.

**Comment by devuc** [comment]
i had the same issue but...just right "editor.autoClosingBrackets": "always" in your settings.json
and note : it only happens in copilot don't you think

**Comment by a-ilango** [comment]
> > Copilot is defining these default language settings that can be overwritten only using language specific settings. They do that to workaround an issue in vscode tracked at #125663 . Once we ship our next stable release (sometime this week), they will be free to remove that workaround. Until then you can disable the extension if you are not in the preview program yet or you can define the language specific setting e.g.:
> > ```
> > "[typescript]": { "editor.autoClosingBrackets": "languageDefined" }
> > ```
> 
> This fixed it for me.

An extension breaking a basic feature of editor and being silent about it does not look good.

**Comment by satyabansahoo2000** [comment]
Uninstalled copilot and tried using the feature, it's working now. It's because of the extension, it's breaking down.

**Comment by crackerberries** [comment]
i reinstalled copilot (got into the technical preview) and i'm loving it, but the issue has risen again. how do i get this to work again WITH copilot still enabled?

**Comment by hediet** [comment]
@crackerberries please see Alexs comment:

> Copilot is defining these default language settings that can be overwritten only using language specific settings. They do that to workaround an issue in vscode tracked at #125663 . Once we ship our next stable release (sometime this week), they will be free to remove that workaround. Until then you can disable the extension if you are not in the preview program yet or you can define the language specific setting e.g.:
> 
> ```
> "[typescript]": { "editor.autoClosingBrackets": "languageDefined" }
> ```

You need to do that for every language that you use.

**Comment by zaheeruddinfaiz** [comment]
For me it was Colpilot. I have removed and it is working flawlessly.

**Comment by Shivam-gupta-cmyk** [comment]
I think it's bcz of github copilot ,i uninstalled it now it is working fine.

**Comment by crackerberries** [comment]
it IS because of copilot, but i actually kinda like copilot and don't wanna remove it

**Comment by Rao-Vivek** [comment]
> > using copilot?
> 
> I have it installed, but not working yet, because I'm not in the preview program yet.

**Comment by Rao-Vivek** [comment]
> > > using copilot?
> > 
> > 
> > I have it installed, but not working yet, because I'm not in the preview program 
Yes bro, it is working after removing copilot

**Comment by matteing** [comment]
Same here, it was copilot. Disabled.

**Comment by Code-MMM** [comment]
How do i do the language specific thing for jsx?

**Comment by sumitmukharjeeeeee** [comment]
> This might be defined by an extension. Are you by any chance using copilot?

Thanks sir this worked for me

**Comment by maxijonson** [comment]
> How do i do the language specific thing for jsx?

Check the language of the file in the bottom right corner of the editor. With JSX, the language is usually `javascriptreact` or `typescriptreact`. You can then disable it as mentioned above:

```json
{
    "[javascriptreact]": { "editor.autoClosingBrackets": "languageDefined" }
}
```

**Comment by Code-MMM** [comment]
> > How do i do the language specific thing for jsx?
> 
> Check the language of the file in the bottom right corner of the editor. With JSX, the language is usually `javascriptreact` or `typescriptreact`. You can then disable it as mentioned above.
> 
> ```json
> {
>     "[javascriptreact]": { "editor.autoClosingBrackets": "languageDefined" }
> }
> ```
> 
> In case you're wondering where to put this, it should be put inside the `.vscode/settings.json` file, at the root of your project. This defines a set of settings for the workspace and overrides global settings.

Thanks a lot, was looking for the javascriptreact tag, works now.

**Comment by mdshanbd** [comment]
Thank U So Much

**Comment by rawic** [comment]
> > using copilot?
> 
> I have it installed, but not working yet, because I'm not in the preview program yet.

doesn't matter. if you have copilot (even not activated by GitHub) auto-closing brackets are not gonna work.

**Comment by vibhor2093** [comment]
> This might be defined by an extension. Are you by any chance using copilot?

Yes , and after uninstalling it works!!!

**Comment by Aryan6290** [comment]
Disabling copilot does the job

**Comment by akilaliyanage** [comment]
> This might be defined by an extension. Are you by any chance using copilot?

this was my issue, after un-installing the extension it works now, thank you

**Comment by jaroslavhuss** [comment]
Yeah, 

I can confirm that CoPilot did that for me. Anyway, for Javascript and Typescript I've used this setting: 

`},
      "[typescript]": {
          "editor.autoClosingBrackets": "always"
      },
      "[javascriptreact]": {
          "editor.autoClosingBrackets": "always"
      },
     "[javascript]": {
         "editor.autoClosingBrackets": "always"
     }`

**Comment by AlexandroPerez** [comment]
I just updated to VS code 1.59 and then this happened, so I was worried. But it was indeed copilot, as soon as I uninstalled it it worked.

I hadn't noticed right away because I've been learning svelte, and the problem with the brackets wasn't there. I don't know if it's because of their recommended formatter, or if copilot simply doesn't mess with `.svelte` files.

Afterwards I reinstalled copilot, giving it a second chance, and set individual language specific settings in the `settings.json` file like everyone else, and I got my auto closing brackets back.

```json
"[typescript]": {
  "editor.autoClosingBrackets": "always" 
},
"[javascriptreact]": {
  "editor.autoClosingBrackets": "always" 
}
```
The question is, will this be the only breaking feature?

**Comment by laxman-stan** [comment]
> This might be defined by an extension. Are you by any chance using copilot?

Thanks buddy

**Comment by jscul** [comment]
> This might be defined by an extension. Are you by any chance using copilot?

I laughed. Installed it 2 hours prior to this. Thanks for the quick solution, disabling `GitHub Copilot` worked for me.

**Comment by sayedsadat98** [comment]
Same issue....I disabled copilot and the auto close bracket functionality is working....
I think copilot dev will soon fix this bug!

**Comment by keidarcy** [comment]
disable copilot works for me
