### ISSUE TITLE
Smoke test failure: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#127767]
Found this test failed on the first run. Probably flakey (currently rerunning):

1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Extensions
           install and enable vscode-smoketest-check extension:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=125848&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094

**Comment by chrmarti** [comment]
Again today: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=126042&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

**Comment by sandy081** [comment]
From the error, it does not look like test failed because waiting for specific element in the extensions viewlet. 

> Error: Timeout of 60000ms exceeded. 

Seems to me a set up related.

@lszomoru any insights?

**Comment by chrmarti** [comment]
Now on Linux: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=126062&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=500500fc-d3cc-5138-3a2a-6935e05fea33&s=df1e964f-4580-5d4b-af27-e8818fedb05f

**Comment by lszomoru** [comment]
Closing this as multiple improvements were done over the months.
