### ISSUE TITLE
search in multi root: strange behavior with exclude folder

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#127790]
Verifying #126003

Create a multi root workspace
```
{
	"folders": [
		{
			"path": "$inner"
		},
		{
			"path": "foo"
		}
	],
	"settings": {}
}
```
- with files in the folder
- in the files to exclude field enter `./bar`

Search field has error: `Workspace folder does not exist`

![image](https://user-images.githubusercontent.com/6461412/124145256-ed831700-da8c-11eb-9bf4-04d08956bce9.png)

Not clear
- why that syntax would match on a workspace folder name
- why no search results are shown for the folders that are not affected by the excluding pattern
(I would understand if it were a include pattern)

**Comment by roblourens** [comment]
`./bar` matches a workspace folder named `bar` in a multiroot workspace. If the pattern is invalid, then I just don't search rather than show search results which might be not what the user intended
