### ISSUE TITLE
Colon cancels completion

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#12772]
- VSCode Version: 1.5.3, but same on insider build f62883f
- OS Version: Windows

Running an extension with the following code:

```typescript
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCompletionItemProvider('haxe', {
        provideCompletionItems(doc, pos) {
            return [new vscode.CompletionItem(':foo'), new vscode.CompletionItem('bar')];
        }
    }, "@");
}
``` 

Instead of filtering the results, typing a `:` closes the completion list:

![](http://i.imgur.com/9KD0dD9.gif)

Typing letters works as expected though:

![](http://i.imgur.com/VnIOBNK.gif)

This leads to some unexpected behavior in the vshaxe extension: https://github.com/vshaxe/vshaxe/issues/48

**Comment by jrieken** [comment]
This is because `:` isn't considered part of a word. If you author your own language you can set the word definition using [`setLanguageConfiguration`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4108) or you can completion items must set the [`textEdit`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2326) which allows to define what range of the text is used for compare/sorting/replacing

**Comment by Gama11** [comment]
Thanks, setting `wordPattern` works nicely.

However, vshaxe also happens to use `:` as a trigger character (for type hint completion), which again cancels completion... `triggerCharacters` is just a string array - I guess there is no way to apply a trigger character selectively, only when the text before the cursor matches a regex for instance?

Now, this is not a huge issue, since we can probably work around it by just providing the same completion again on `:`. It will result is a short flicker of the completion box though, since it is closed and immediately repoened.

**Comment by jrieken** [comment]
>  I guess there is no way to apply a trigger character selectively, only when the text before the cursor matches a regex for instance?

Yeah - we blindly call the corresponding provider when that happens. Also repeatedly because suggestion might change (become more specific)
