### ISSUE TITLE
JSON Schema validation https failed without details (768)

### ISSUE THREAD

**Issue by definedrisk** [microsoft/vscode#127769]
Issue Type: <b>Bug</b>

"$schema": "https://my-intranet-server:8081/schema/myschema.json" is underlined with error "Unable to load schema from 'https://my-intranet-server:8081/schema/myschema.json': Request vscode/content failed unexpectedly without providing any details.(768)"

Importantly the logs on my server do not show any connection from the Https request from VS Code!!

I do not use a proxy. The VS Code client and IIS Server are on different Windows 10 PCs on same intranet (HTTP is port 8080 and HTTPS is port 8081) but I can ctrl+click from VS Code on this URI to open a webpage showing the schema file (it opens in Edge browser and Chrome browser) - the IIS Server Logs show connection GET and 200 response fromweb browsers (I have added the self-signed certificate to 'Trusted Root Certification Authorities' on Local Computer). 

"$schema": "http://my-intranet-server:8080/schema/myschema.json" is working fine. IIS Server Logs show VS Code request for this.

**It is as if VS Code is not sending a request when it reads in the $schema with a https uri that is sent to my intranet server (no logs on server)**

I have created "myschema-catalog.json" (for use with Visual Studio), this contains "$schema": "https://json.schemastore.org/schema-catalog.json" and that is working correctly!

If I change myschema.json to contain: 

    "properties": {
        "$schema": {
            "description": "Link to https://my-intranet-server:8081/schema/myschema.json",
            "type": "string",
            "enum": ["https://my-intranet-server:8081/schema/myschema.json"]
        },

Then when I write a json file and refer to this schema using:

"$schema": "http://my-intranet-server:8080/schema/myschema.json" I get the correctly reported error: "Value is not accepted. Valid values: "https://my-intranet-server:8081/schema/myschema.json".(1)" and the remaining JSON is validated correctly with popups in VS Code. As soon as I change it back to https:... then it fails with the original error.

I have no idea how to proceed?!?!

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 4251)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (25.55GB free)|
|Process Argv|--crash-reporter-id afcfd922-20fb-4764-b0c9-db755715f2fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.1
docomment|k--|0.1.20
csharp|ms-|1.23.12
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.4.1
powershell|ms-|2021.6.2
markdown-preview-enhanced|shd|0.5.21
win-ca|uko|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by definedrisk** [comment]
I do not believe the above links are same issue. I have confirmed that the validation is working with Visual Studio 2019 16.10.3. Unfortunately I want to start using "$schema": "http://json-schema.org/draft-07/schema" and Visual Studio only supports draft-04. VS Code seems to support draft-07 just not via https as described above.

**Comment by aeschli** [comment]
Very likely related to the certificate. I will make sure the error message is not swallowed.

**Comment by definedrisk** [comment]
To confirm what is happening: The whole json schema functionality (Draft-04) is working fine with Visual Studio 2019 16.10.3. I have added my own catalog schema which uses https://json.schemastore.org/schema-catalog.json - note the https! This lists my schema including https://my-intranet-server:8081/schema/myschema.json". But when I move to VS Code it fails as explained. I am confused why Visual Studio can download and USE the schema but not VS Code. As I move to Draft-06 and -07 I wanted to use VS Code (as those are unsupported in Visual Studio). They work for http: but as the https://json.schemastore.org/schema-catalog.json requires https^ I am in a catch-22!!

**Comment by larshp** [comment]
I'm experiencing a similar issue,

https://schema.abaplint.org/schema.json loads without problems in a browser, and also works from https://playground.abaplint.org where the monaco editor fetches and use the schema without problems

![image](https://user-images.githubusercontent.com/5888506/135572259-9f612ce0-426f-4024-b8cf-64c6152a2470.png)

**Comment by larshp** [comment]
guess my above error is due to https://github.com/microsoft/vscode/issues/134244

but still it would be nice if it showed more error information

**Comment by estruyf** [comment]
Got this as well, no reason why this is happening. I'm able to retrieve the file, but not within VSCode. In the previous version of VSCode it worked fine.

https://beta.frontmatter.codes/frontmatter.schema.json

![Screenshot 2021-10-06 at 11 14 54](https://user-images.githubusercontent.com/2900833/136174998-234f4b65-d03d-4b05-aa88-f39a9ec172fa.png)

**Comment by larshp** [comment]
works in 1.61.0, so my scenario was probably due to the certificates

**Comment by estruyf** [comment]
I can confirm that it works for me as well.

**Comment by larshp** [comment]
but still it would be nice if it showed more error information

**Comment by aeschli** [comment]
What I fixes that the error has the detail.
It will not fix any issues you have with proxy configurations, but hopefully the message will give an indication what the problem is.

The fix is for the next release.
