### ISSUE TITLE
IDE is stuck at "Starting Java language server"

### ISSUE THREAD

**Issue by DipaliDubey** [microsoft/vscode#127778]
Does this issue occur when all extensions are disabled?: No Without the language server extension it obviously wont load. 

- VS Code Version:1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Take any code and open in visual studio
2. Visual studio stucks at 123ca4c8 Configuring java project handover: 68% Refreshing '/handover/src/main/java'. [684/1000]
 
_The issue arrived since today afternoon.  If I open any project from a day before it works fine, but for any new project the same issue comes. Also I see a ranom folder named apt_generated_tests getting generated in the new projects!_
**I tried deleting the workspaceStorage  as suggested in other issues, still no luck!**

I have the following extensions installed
![image](https://user-images.githubusercontent.com/86785941/124132760-c6cddc00-da9e-11eb-8f1d-683d7f40951f.png)

Can you please suggest what to do?

**Comment by DipaliDubey** [comment]
Which extension is causing this issue?

**Comment by stfujnkk** [comment]
I have the same problem. Springboot project stuck during initialization.
**Java Build Status**
547c270c Configuring java project demo: 68% Refreshing '/demo/src/main/java'. [684/1000]
b556061c Reporting encoding changes. [Done]
f3eaab40 Register Watchers [Done]
