### ISSUE TITLE
 'Remote-SSH commands result in error not found after update of vscode to 1.57.1

### ISSUE THREAD

**Issue by ZakiOro** [microsoft/vscode#127791]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: windows 10.0.19042

Steps to Reproduce:

1. CTRL + SHIFT + P 
2. remote-ssh... (any command)
remote-ssh not wokring after this update of vscode, reinstalling the extension gives same results as well.

**Comment by ZakiOro** [comment]
can no longer connect o any remote host, access configuration file nor settings of the extension

**Comment by roblourens** [comment]
Can you check for errors in the devtools console?
