### ISSUE TITLE
Show enabled and disabled extensions in the workspace or globally

### ISSUE THREAD

**Issue by kecrily** [microsoft/vscode#127753]
In the sidebar - extensions provides separate views of extensions enabled and disabled in the workspace. This should also separate the view of extensions that are globally enabled or disabled.

This gives a clearer view of which extensions are being used in this workspace.

**Comment by sandy081** [comment]
> In the sidebar - extensions provides separate views of extensions enabled and disabled in the workspace

Can you please show the screenshot of which views you are talking about?

**Comment by kecrily** [comment]
> 
> 
> > In the sidebar - extensions provides separate views of extensions enabled and disabled in the workspace
> 
> Can you please show the screenshot of which views you are talking about?

![图片](https://user-images.githubusercontent.com/45708948/124287778-ffdf7c80-db82-11eb-9fe2-0d7df205323e.png)

I would like to be able to split the view about global enable/disable and workspace enable/disable extensions from the current mixed global and workspace enable/disable view.

**Comment by sandy081** [comment]
Got it, you would like to filter global and workspace enabled/disabled extensions
