### ISSUE TITLE
Повторное открытие папки - не работает Visual Studio Code

### ISSUE THREAD

**Issue by motos5** [microsoft/vscode#127743]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

Issue Type: <b>Bug</b>

После повторного открытия папки с проектом перестают работать расширения и прочие другие функции программы Visual Studio Code. Началось это после последнего обновления программы.

VS Code version: Code - Insiders 1.58.0-insider (57930758db9e2c83f59b9ee1851400bd16192d32, 2021-06-30T05:14:00.370Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) 4 CPU 3.06GHz (2 x 3066)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (2.27GB free)|
|Process Argv|--crash-reporter-id e3bda1dd-a817-416b-91f4-aa7c2a2fce12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
All-Autocomplete|Ati|0.0.23
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.0.1
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-gutter-preview|kis|0.27.1
vscode-language-pack-ru|MS-|1.58.6
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
nunjucks|ron|0.3.0
sass-indented|syl|1.8.17
eno|Wsc|2.3.53

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
3f5j7703:30294757
vscod805cf:30301675
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692

```

</details>

**Comment by motos5** [comment]
> Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.
> 
> Issue Type: Bug
> 
> После повторного открытия папки с проектом перестают работать расширения и прочие другие функции программы Visual Studio Code. Началось это после последнего обновления программы.
> 
> VS Code version: Code - Insiders 1.58.0-insider ([5793075](https://github.com/microsoft/vscode/commit/57930758db9e2c83f59b9ee1851400bd16192d32), 2021-06-30T05:14:00.370Z)
> OS version: Windows_NT x64 6.1.7601
> Restricted Mode: No
> 
> System Info
> Extensions (14)
> A/B Experiments

Extensions and other functions of Visual Studio Code stop working after reopening the project folder. It started after the last update of the program.

**Comment by zardoy** [comment]
Translation required means that you also need to change the title.

What do you mean, extensions stopped working? I think it'd much better if you could send a video, demonstrating the issue.

**Comment by motos5** [comment]
Hello. After the last update of the program, this error no longer appears.
This question can be considered closed.

сб, 3 июля 2021, 17:02 Vitaly ***@***.***>:
