### ISSUE TITLE
Image / output visualization within the executed code

### ISSUE THREAD

**Issue by montyvesselinov** [microsoft/vscode#127783]
Is it possible to see the output from the executed julia / pyhon functions next to the command line producing the output?!

**Comment by weinand** [comment]
@montyvesselinov do you mean something like "inline values"?
Please see this https://www.youtube.com/watch?v=nWW0997lu6I

**Comment by montyvesselinov** [comment]
`inline values` is promising.

how about showing images or more complex outputs (Arrays, Dictionary, DataFrames, CSV)?

**Comment by weinand** [comment]
VS Code's Notebooks support this.

**Comment by montyvesselinov** [comment]
Jupyter notebooks are good but messy. I prefer to see the images in the REPL or in the script. And I guess i am not the only one. Atom and Juno use to support these features.

**Comment by weinand** [comment]
Feel free to help us with a PR!
