### ISSUE TITLE
Git-related settings lost

### ISSUE THREAD

**Issue by asampal** [microsoft/vscode#127736]
Issue Type: <b>Bug</b>

In the last build or so, git-related settings have disappeared and it seems that git is no longer configured.

The pull requests and issues extension reports that it can't load and git must be installed. The git tool in the toolbar tells me that that if I want to enable git features, I must enable git in my settings. Clicking on the "settings" link in that advice, the settings window opens with "git.enabled" pre-populated in the search bar, but there are no results showing, only the message "No settings found".

Typing only "git" in the settings search returns almost nothing:

![image](https://user-images.githubusercontent.com/281639/124064256-625d3f00-da02-11eb-8aff-8f2539ee5d8f.png)
 

VS Code version: Code - Insiders 1.58.0-insider (57930758db9e2c83f59b9ee1851400bd16192d32, 2021-06-30T05:14:00.370Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.55GB free)|
|Process Argv|--crash-reporter-id af1c7f06-1fe5-4a50-bddd-2de5a14c940d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (110)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
svelte-intellisense|ard|0.7.1
zls-vscode|Aug|1.0.4
spellright|ban|3.0.58
toml|be5|0.5.1
vscode-unison|Ben|0.3.0
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
better-toml|bun|0.3.2
path-intellisense|chr|2.3.0
codeswing|cod|0.0.16
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
transformer|dak|1.11.1
vscode-deno|den|3.6.1
githistory|don|0.6.16
xml|Dot|2.5.1
arturo|drk|0.2.7
gitlens|eam|11.5.1
vscode-npm-script|eg2|0.3.22
json-tools|eri|1.0.2
magic-racket|evz|0.5.7
vscode-firefox-debug|fir|2.9.4
vscode-svelte-snippets|fiv|0.5.0
code-runner|for|0.11.4
shell-format|fox|7.1.0
godot-tools|gee|1.1.2
copilot|Git|1.1.1899
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
cloudcode|goo|1.13.0
gc-excelviewer|Gra|3.0.42
terraform|has|2.13.0
rest-client|hum|0.24.5
output-colorizer|IBM|0.1.2
figma|ide|0.1.1
r|Iku|2.0.0
vscode-k3d|ine|0.0.10
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|5.5.9
Ionide-Paket|Ion|2.0.0
svelte-vscode|Jam|0.9.3
search-node-modules|jas|1.3.0
plantuml|jeb|2.15.1
vscode-gnupg-tool|JHe|1.3.9
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.9.1
language-julia-insider|jul|1.3.12
vscode-gutter-preview|kis|0.27.1
nim|kos|0.6.6
node-module-intellisense|lei|1.5.0
rust-analyzer|mat|0.2.654
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
vscode-edge-devtools|ms-|1.2.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.7.985709665
remote-containers|ms-|0.185.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.7.3
cpptools|ms-|1.4.1
powershell|ms-|2021.6.2
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.5.1
gradle-language|nac|0.2.3
vetur|oct|0.34.1
red|red|0.4.3
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-microprofile|red|0.2.0
vscode-quarkus|red|1.8.0
vscode-yaml|red|0.20.0
shellman|Rem|5.5.1
LiveServer|rit|5.6.1
shebang-snippets|rpi|0.1.4
partial-diff|ryu|1.4.3
scala|sca|0.5.3
scala-snippets|sca|0.1.0
metals|sca|1.10.6
imba|scr|0.5.2
code-settings-sync|Sha|3.4.3
incremental-search|sie|0.2.1
vscode-hexdump|sle|1.8.1
rewrap|stk|1.14.0
imba|tir|0.4.0
pdf|tom|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.5
vscodeintellicode|Vis|1.2.14
vscode-vlang|vla|0.1.8
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-icons|vsc|11.5.0
codetour|vsl|0.0.56
gistfs|vsl|0.2.9
gitdoc|vsl|0.0.8
quokka-vscode|Wal|1.0.381
ballerina|wso|2.1.0
local-history|xyz|1.8.1

</details>

**Comment by Soyukke** [comment]
I had the same problem, but after uninstalling Julia Insider, everything worked fine.

**Comment by eamodio** [comment]
@asampal Do you have Julia Insiders installed too?

**Comment by asampal** [comment]
Yes, I have it too. Uninstalling also resolved the problem for me.

**Comment by davidanthoff** [comment]
We moved to a new build setup and accidentally published a broken insider build of the Julia extension. Fix is incoming, I hope to get it out in less than an hour.
