### ISSUE TITLE
Deprecate and reduce API for typed editors for editor service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#127747]
Now that we changed the editor service to work better with untyped editors all the way to the override service I think we should start to:
* deprecate `openEditor`, `openEditors`, `replaceEditors` methods that work with typed inputs
* find users and see how we can transition into untyped editor usage
* eventually remove typed API

Luckily we do not have a lot of users anymore, I would say we have 4 categories:
* editors that are not registering an editor with the override service (e.g. extensions editor, performance editor)
* editors that can easily adopt untyped editors but simply didn't do that yet
* editors that have registered as editor with the override service but have some obscure requirements on the target input (e.g. file editor input's need to "force open as binary")
* calls where we already have a typed editor in hand [1]

**[1]** I am not sure about this one to be honest. We have a picker for opened editors and we have the "Open Editors" view above the file explorer where a click takes the existing editor input to open. I don't think it makes a lot of sense to ask these clients to pass in an untyped editor though. 

Thoughts?

**Comment by lramos15** [comment]
> **[1]** I am not sure about this one to be honest. We have a picker for opened editors and we have the "Open Editors" view above the file explorer where a click takes the existing editor input to open. I don't think it makes a lot of sense to ask these clients to pass in an untyped editor though.

I think this is where keeping our `doResolveEditor` function comes in handy as we handle the conversion of them to untyped editors and take care of that for them. We can either leave the function calls as supporting typed to or move it to untyped and just publicly expose the converter

**Comment by bpasero** [comment]
Well another way of solving this is to stop allowing to pass untyped editors into the editor service but still keep those methods on the level of a group: in the case of the open editors view for example, we know exactly in which group to open the editor (similar to clicking on a tab), so there the editor service + overrides doesn't make any sense to be used anyway.

**Comment by bpasero** [comment]
It's actually not too bad, will try to tackle some today:

![image](https://user-images.githubusercontent.com/900690/124873955-6c191080-dfc7-11eb-800c-783d18ea7da0.png)

**Comment by bpasero** [comment]
Found another interesting case: we have a typed editor in hand but want to open in `SIDE_GROUP`. This means we would have to ask clients to first manually create a side group and then open it there...

**Comment by lramos15** [comment]
> Found another interesting case: we have a typed editor in hand but want to open in `SIDE_GROUP`. This means we would have to ask clients to first manually create a side group and then open it there...

I came across this too. I should do a better job documenting the cases. The best solutions is probably to have them call `findGroup` or introduce something like `getSideGroup()`  to the editorService so that they can call `this.editorService.getSideGroup().openEditor(input, options)`. I don't think we would want them to convert to untyped if the typed input is in hand as then you would be creating an extra input.

**Comment by bpasero** [comment]
Hm, maybe `IEditorService.openGroup(SIDE_GROUP)`?

**Comment by bpasero** [comment]
Yeah I had the same feeling actually :)

**Comment by bpasero** [comment]
Deprecated typed versions of `openEditors` and `replaceEditors`, only very few left. Majority of remaining `openEditor` calls are:
* those that did not adopt editor resolver
* the discussed `SIDE_GROUP` users

**Comment by lramos15** [comment]
> * the discussed `SIDE_GROUP` users

Have we decided if we can create a method signature that will work for the SIDE_GROUP consumers?

**Comment by bpasero** [comment]
Not yet, might slip to another milestone, but assigning myself for that piece of the cake.

**Comment by bpasero** [comment]
I think I found a nice solution: `IEditorGroupService.sideGroup` gives access to an object with one method `openEditor` that will behave exactly like `IEditorService.openEditor(..., SIDE_GROUP)`, without the resolving/override piece:

https://github.com/microsoft/vscode/blob/3084de82e992bbda5f8637593095bf1a20c2d4b3/src/vs/workbench/browser/parts/editor/editorPart.ts#L202-L208

I have adopted it in most places and deprecated the `IEditorService.openEditor` method for typed editors. The majority of remainders is editors that have not registered with the resolver service.

**Comment by bpasero** [comment]
One thing I just realised: we cannot simply replace the now deprecated `IEditorService#openEditor` with something like `IEditorGroupService.activeGroup.openEditor` because it would break the `revealIfVisible` setting that users might have enabled. 

In other words, that feature really relies on the caller to use editor service, because it could be that a different group is picked than the active one based on options.

**Comment by lramos15** [comment]
I'm surprised we didn't come across this issue sooner then since it's been phased out slowly. What would be your suggested alternative? It almost sounds like we can't proceed with untyped open editor unless we introduce some type of group resolving intermediary for the typed case

**Comment by bpasero** [comment]
It would probably need some kind of proxy for `activeGroup.openEditor` to target a different group if and only if one of the conditions apply. In other words, behave very similar to the `sideGroup` that I added.

**Comment by lramos15** [comment]
Is it weird to have other groups selected from within a group itself? I guess not if we already have something like that with `sideGroup`

**Comment by bpasero** [comment]
Yeah it is weird.

**Comment by lramos15** [comment]
So she would backtrack on our original idea or go forward with this? It sounds like it's still worth it to implement that work around for a setting that isn't used a ton

**Comment by bpasero** [comment]
Well, if it is used in 1 place, that warrants for implementing proper support. We cannot just silently drop that support. On the other hand, maybe most remaining editors that have not adopted untyped editors yet are not really suffering from this.

**Comment by bpasero** [comment]
Issue grooming, I don't really see meaningful additions here other than asking editors that have not yet adopted the editor resolver to adopt untyped inputs. 

Other than that, I feel adding another method to editor groups for respecting `revealIfOpened` or `revealIfVisible` is equally bad as having the deprecated method on the editor service. I will leave `sideGroup` because it has some purpose and is now more widely adopted.
