### ISSUE TITLE
Debugger: When Breakpoint is hit, opened file should always be preferred

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127792]
When a Breakpoint is hit, opened files should be focused instead of opening a second editor in the focused editor group.

![recording](https://user-images.githubusercontent.com/2931520/124148443-f2959580-da8f-11eb-883c-56ef1ee84207.gif)

**Comment by isidorn** [comment]
This was previously working. 
@bpasero I am just calling the `editorService` here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugSource.ts#L76

So if there is `Group 1` with `a.txt`, and `group 2` with `b.txt`. And `group 2` is active. When I call `openEditor(a.txt)` I would just want `Group 1` to become active, not that `a.txt` is opened in `group 2` (since a.txt is already visible and this will be the least destructive). 

Might this be a regression of the custom editor work?
fyi @lramos15

**Comment by bpasero** [comment]
Yeah the `revealIfOpened` thing should apply. Quite possibly a regression.

**Comment by hediet** [comment]
This might also be something for locked editor groups, in case a breakpoint is hit in a file that is currently not opened.

**Comment by bpasero** [comment]
@lramos15 is it possible to have a unit test for this?

**Comment by lramos15** [comment]
> @lramos15 is it possible to have a unit test for this?

@bpasero I'm not sure of a great way to do that since it isn't really a callable function we can check the outputs on. It seems like it would be a very generic unit test that would be susceptible to noise.

**Comment by rzhao271** [comment]
I reproduced the issue by debugging VS Code OSS.

1. Set a breakpoint and keep the file with that breakpoint open
2. Create an untitled file in a new editor group to the right
3. Debug
4. Hit the breakpoint
5. Focus on the untitled file
6. F10
7. 🐛 The untitled file switches to show a preview of the code file, even though the code file is already visible in the other editor.

![recording (49)](https://user-images.githubusercontent.com/7199958/124672753-6a870580-de6c-11eb-82cf-c6f946206784.gif)

**Comment by bpasero** [comment]
@lramos15 I can reproduce and it originates from the fact that `IUntitledTextResourceEditorInput` has no required property and thus pretty much matches on everything. 

For example, here we wrongly pass in `IEditorInputWithOptions`:

https://github.com/microsoft/vscode/blob/f489dc7b2f91786d7af6a75ce36ca735047e1d79/src/vs/workbench/services/editor/browser/editorService.ts#L670-L670

and here as well:

https://github.com/microsoft/vscode/blob/f489dc7b2f91786d7af6a75ce36ca735047e1d79/src/vs/workbench/services/editor/browser/editorService.ts#L685-L685

and here

https://github.com/microsoft/vscode/blob/f489dc7b2f91786d7af6a75ce36ca735047e1d79/src/vs/workbench/services/editor/browser/editorService.ts#L690-L690

I would still think that a test would have helped uncover this issue.

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/4c2c3ca11643422857c28863c347fbc07e54909d to `main` to make `resource` a required property of untitled inputs and would think that the change in https://github.com/microsoft/vscode/commit/4c2c3ca11643422857c28863c347fbc07e54909d#diff-4729038e6d08c333e1fca18d18afac8a5a2f7fc6dffd55f0cb16ca66dab09190 can partially be backported as it should fix the issue.
