### ISSUE TITLE
Strange padding on extension's publisher display name

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#127781]
There's so much right-padding on the publisher's display name, is this on purpose? The version nunmber feels like it's floating.

![recording (1)](https://user-images.githubusercontent.com/22350/124134805-0d3c2000-da38-11eb-9a4a-7473c1cec63c.gif)

**Comment by sandy081** [comment]
Not on purpose. That place is for other fields like repo, downloads etc., That should not be empty when they do not exist.
