### ISSUE TITLE
Extension Webview resource error with Remote SSH

### ISSUE THREAD

**Issue by oschulz** [microsoft/vscode#127770]
VS-Code v1.57.1, the "Git Graph" (extension) view is completely empty when using Remote-SSH.

See mhutchie/vscode-git-graph#535. The extension author, @mhutchie , indicated that this is very likely due to a VS-Code bug related to Webview with Remote-SSH.

Screenshots:

Git Graph on VS-Code v1.56.2 with Remote-SSH:

![git-graph-working](https://user-images.githubusercontent.com/546147/124124237-7fccf000-da78-11eb-8e33-1f56eb5fec71.jpg)

Git Graph on VS-Code v1.57.1 with Remote-SSH:

![git-graph-not-working](https://user-images.githubusercontent.com/546147/124124327-96734700-da78-11eb-92a9-f27e497d8035.jpg)

Does this issue occur when all extensions are disabled?: N/A (since it affects an extension)

- VS Code Version: v1.57.1
- OS Version: Ubuntu Linux 20.04

Steps to Reproduce:

1. Use the "Git Graph (mhutchie.git-graph)" extension in remote-SSH mode

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If so, please open up the developer tools (run the `Developer: Toggle developer tools` to do this) and share any relevant errors you see there

**Comment by oschulz** [comment]
Will test!

**Comment by oschulz** [comment]
Ok, yes, it does reproduce on the latest VS Code insiders build.

The developer tools console just shows

```
console.ts:137 [Extension Host] (node:81031) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code-insiders --trace-deprecation ...` to show where the warning was created) 
```

but that's even before I open the Git Graph view. Can't see any other errors.

**Comment by oschulz** [comment]
I just tested with code-insider-x64-1628833345 Git Graph seems to work again. :-)

**Comment by mjbvz** [comment]
Thanks for confirming. I believe this has the same root cause as #123494 

Please let me know if this issue comes up again

**Comment by oschulz** [comment]
Will do - thanks @mjbvz .

**Comment by oschulz** [comment]
@mjbvz I just tried the recent VS Code 1.59.1 and ran into this issue again - but with code-insider-x64-1628833345 and also the latest code-insider-x64-1630423112 the issue seems fixed. Is the fix for this not part of the 1.59.1 release yet?

**Comment by mjbvz** [comment]
It's in the August 2021 milestone so it will be part of VS Code 1.60

**Comment by oschulz** [comment]
Great, thanks for the info @mjbvz ! (Was just worried the fix hadn't worked for the production build for some weird reason.)

**Comment by oschulz** [comment]
Just tested with v1.60, everything looks fine! Thanks again for the fix.
