### ISSUE TITLE
VS Code is unhelpful in installing "coreclr" debugger

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#127784]
I had removed all extensions from VS Code Insiders.
Opening a simple C# project and then pressing F5 resulted in this:

![2021-07-01_15-49-35 (1)](https://user-images.githubusercontent.com/1898161/124135842-7cd7fc80-da84-11eb-819b-ae3079e67c40.gif)

Why is "PeachPie" the only result when trying to find the "coreclr" debugger extension?

**Comment by isidorn** [comment]
@gregg-miskelly can you maybe add `coreclr` to your extension description so the marketplace search finds this? Do you mention the phrase coreclr anywhere?
@weinand can you please also file an issue against the marketplace here https://github.com/microsoft/vsmarketplace/i

**Comment by gregg-miskelly** [comment]
The phrase 'CoreCLR' does show up in the body of https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp. Is there something in the [C# package.json](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json) that should have 'coreclr'?

**Comment by isidorn** [comment]
@gregg-miskelly this depends on how the marketplace is doing their ranking. Which I do not know.
Let me open an issue in their repository and let's see if they can recommend something to make this work.

**Comment by isidorn** [comment]
Filled this one for the marketplace. Hopefully they can help https://github.com/microsoft/vsmarketplace/issues/113

**Comment by weinand** [comment]
I think we have a fundamental problem here:
we cannot easily find a VS Code debugger on the Marketplace by its debug type (which is a well known property of all VS Code debuggers).

**Comment by isidorn** [comment]
I think it is a corner case, because:
* For most debugger types this works. I think `coreclr` is the exception. I might be wrong, but would be interested to know what other "strange" this does not work with?
* The most common scenario is you have no `launch.json` and in that case we will search for a language, in this case C# and it will work. 

If you think this should be tackled, we can for example not offer to install an extension when there is a launch.json present...

**Comment by weinand** [comment]
@isidorn I don't think that this is a corner case.
In this case I had a launch.json with the correct debug type. But the matching extension was missing.
Please try how helpful the debug-type queries `@category:"debuggers" python` or `@category:"debuggers" Python` are ;-)

**Comment by gregg-miskelly** [comment]
For what its worth, I tried the two C++ debug adapter types (`cppvsdbg` and `cppdbg`) hoping to see if there was something I could add to the C# package.json and had the same problem.

**Comment by isidorn** [comment]
Php, java and python look good to me.
But yeah for cpp it sucks

![Screenshot 2021-07-01 at 19 01 23](https://user-images.githubusercontent.com/1926584/124162484-c9303600-da9e-11eb-9b69-3fe488ba3a0a.png)
![Screenshot 2021-07-01 at 19 01 33](https://user-images.githubusercontent.com/1926584/124162485-c9c8cc80-da9e-11eb-8f7d-6d632d3418c9.png)
![Screenshot 2021-07-01 at 19 03 33](https://user-images.githubusercontent.com/1926584/124162708-0e546800-da9f-11eb-8b5f-ca1025246255.png)

**Comment by weinand** [comment]
My point is: the query should only return extensions that implement exactly the debug type specified in the query. Pls review the "python" result set and find the 3 debuggers that would actually work with the launch config.

**Comment by prashantvc** [comment]
Can we not redirect users to C# extension instead of searching for `coreclr` debugger?

**Comment by isidorn** [comment]
@prashantvc unfortunetly not, the solution we have here is a general one (it is not special for C#). So we see that the user uses a type `coreclr` and then we search for that extension. We have no mapping between `coreclr` type and the "C#" name.

**Comment by prashantvc** [comment]
> unfortunetly not, the solution we have here is a general one (it is not special for C#)

yeah, you're right. `coreclr` doesn't always mean C#
