### ISSUE TITLE
Feature to do "factory reset" of all VSCode state for a true uninstall

### ISSUE THREAD

**Issue by lgritz** [microsoft/vscode#127726]
Uninstalling VSCode (on Mac) just removes what's in /Applications. That wouldn't remove anything in ~/Library, for example, so if there is some setting you've long forgotten about that is causing a misbehavior, or a corrupted database or something, it can be very tricky to figure out where that might live. A handy feature might be a thorough "return all user options to factory settings and flush all caches and databases."

For example,

```
$ cd ~/Library
$ fd vscode

Caches/com.microsoft.VSCode
Caches/vscode-cpptools
Caches/com.microsoft.VSCode.ShipIt
Preferences/com.microsoft.VSCode.plist
Preferences/ByHost/com.microsoft.VSCode.ShipIt.91EE0198-51E1-555B-A3BC-E3ACE9BFBAA0.plist
Saved Application State/com.microsoft.VSCode.savedState
Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl2
Application Support/Code/CachedExtensionVSIXs/ms-vscode.cpptools-1.4.1
Application Support/Code/CachedExtensionVSIXs/ms-python.vscode-pylance-2021.6.3
Application Support/Code/User/workspaceStorage/df84cd7a565c5b1d4ba0144921f351a5/ms-vscode.cpptools
Application Support/Code/User/workspaceStorage/4452022407e78fba4887dd7ab2ca6348/ms-vscode.cpptools
Application Support/Code/User/workspaceStorage/1eaa37c1a5e35e01ebd6c64d193180f5/ms-vscode.cpptools
Application Support/Code/User/workspaceStorage/ce9408954e065721049090c6561a41b8/ms-vscode.cpptools
Application Support/Code/CachedData/3c4e3df9e89829dce27b7b5c24508306b151f30d/vscode-e1d108fd149352c264576a2cc0954b0c.code
Application Support/Code/User/workspaceStorage/156690e4971cf95480b5bd48cfb519de/ms-vscode.cpptools
```

Those are the ones I can find easily, because the filenames contain the string "vscode" that I thought to search for. If vscode stores anything in files that don't contain those strings, I wouldn't necessarily be able to find them. It shouldn't be the user's onus to know all the possible places (especially in the tangled jungle that is ~/Library on MacOS) where VSCode may have left state. VSCode knows this, so VSCode should provide the one true way to get rid of it all.

Related to #66837, which is Windows-specific.

**Comment by joaomoreno** [comment]
We decided to expose the _full uninstall_ story in our docs, instead of a feature in the product, given it would be hard to implement (something about chickens and eggs): https://code.visualstudio.com/docs/setup/setup-overview#_how-can-i-do-a-clean-uninstall-of-vs-code

**Comment by lgritz** [comment]
Hi, @joaomoreno , please note that just in the cursory search I quoted above ☝️ , there are files VSCode leaves behind that are in directories not mentioned in those docs.

**Comment by lgritz** [comment]
For example, the docs do not mention `~/Library/Preferences`, `~/Library/Caches`, nor `~/Library/Saved\ Application\ State`

I have no idea what else it may be missing, places where it leaves behind files that do not have the substring "vscode" in its name.

**Comment by joaomoreno** [comment]
Not by default. All those folders should've been under `$HOME/Library/Application Support/Code`. Are you *absolutely sure* you never ran `code --user-data-dir SOMETHING` and used `~/Library` as `SOMETHING`? That would explain your state.

**Comment by lgritz** [comment]
Definitely never ran with those arguments. Didn't even know they existed.

**Comment by joaomoreno** [comment]
Got it. Maybe some other tool in your system did that. Maybe some extension which invokes Code in weird ways, we don't really know. But by default, Code won't ever create those folders. You can try this by deleting them, launching Code and quitting. If they reappear let me know.
