### ISSUE TITLE
Horizontal lines break hover a little

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12773]
We now render horizontal lines between each array element a hover is made of. Strictly speaking that's not correct and provides no good separation between elements from provider A and provider B and the elements a single provider created. The below gif shows how the css-selector hover appears  now. IMO we should only render the separator lines for markdown that came from a different source.

![sep-27-2016 16-26-27](https://cloud.githubusercontent.com/assets/1794099/18877954/34cc7cd2-84cf-11e6-8892-973d101f6a0d.gif)

**Comment by joaomoreno** [comment]
I wanna roll it in stable for at least a month, see what more users say.

**Comment by jrieken** [comment]
We should the at least fix the css hover which is under our control

**Comment by joaomoreno** [comment]
Ah! Yeah, I can look into that.
