### ISSUE TITLE
Typos in Workspace Trust source

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#127804]
Search for "workpace" in the vscode repo and you see 81 hits.

For example:
IWorkspaceTrustManagementService.isWorkpaceTrusted
ExtensionVirtualWorkpaceSupport
LimitedWorkpaceSupportType
getWorkpaceSupportTypeMessage

**Comment by sbatten** [comment]
closed by https://github.com/microsoft/vscode/commit/9f7309348f4139404cc1e339216a017bc49884f2
