### ISSUE TITLE
Inform the user when opening native notebooks for the first time

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#127821]
## Problem
This is a response from comments we've seen ([example](https://www.reddit.com/r/vscode/comments/oah295/changing_notebook_looks/)) from users who have been using the webview version of Jupyter Notebooks and are then automatically opted into the native experience are confused as to why it looks different. Some users think there is an error or they accidentally installed a wrong theme.

## Proposal
We should have some way to "inform" the user about the new version when they open it for the first time. Either a toast notification or a new page (like our release notes) would be a good starting point. 

## Examples

Here are some examples of what other products do:

<img width="847" alt="CleanShot 2021-07-01 at 13 56 05@2x" src="https://user-images.githubusercontent.com/35271042/124188429-1b0f9680-da74-11eb-930f-60210d4db928.png">

<img width="495" alt="CleanShot 2021-07-01 at 13 52 04@2x" src="https://user-images.githubusercontent.com/35271042/124188023-886ef780-da73-11eb-8985-778447c0222f.png">

![image](https://user-images.githubusercontent.com/35271042/124188040-91f85f80-da73-11eb-9b00-56c453641fe3.png)

**Comment by tanhakabir** [comment]
Since we've been live with native notebooks for awhile now, I'm going to close this issue
