### ISSUE TITLE
Emmet not working

### ISSUE THREAD

**Issue by krishnan7-dev** [microsoft/vscode#127842]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

I have recently updated my vscode stable build to the latest version. Right after updating, I started working on my html project. But I was unable to use emmet abbreviations. I tried reinstalling vscode but the issue still persisted. It was working fine in the previous version.

- VS Code Version: 1.57.1
- OS Version: macos 10.11.6

Steps to Reproduce:

1. Install the new update.
2. Right after installing, crete an html file and use an emmet abbreviation.

**Comment by krishnan7-dev** [comment]
I wasn't using JSX. It was normal html.

**Comment by thesmartdeveloperr** [comment]
I think it might be some setting switched off in your vs code @krishnan7-dev , everything is working fine for me, all emmet abbs. are working...

**Comment by rzhao271** [comment]
@krishnan7-dev If you go into the extension viewlet and search for Emmet under `@builtin`, is Emmet disabled?

**Comment by krishnan7-dev** [comment]
I have installed VSCode Insider version and it's working fine. Thanks for Helping.
