### ISSUE TITLE
Variables randomly "ReferenceError: xxx is not defined"

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/vscode#127817]
Issue Type: <b>Bug</b>

Debugging an Outlook Add-In from Visual Studio.  React/Typescript.
From the debugger window evaluate some const variables, some work, some display :ReferenceError: xxx is not defined"

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (11.37GB free)|
|Process Argv|--crash-reporter-id 91d32026-f9c4-4a76-885a-0e20560d03b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
csharp|ms-|1.23.12
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.12
vs-asp-classic|wfe|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
binariesv615:30325510
vsccppwtct:30329789
aatestflight:30331711

```

</details>

**Comment by timothyhoffmann** [comment]
Given this code snippet:
```
        const popUps: IUdf[] = [];
        resourceDetails.forEach((rd) => {
          rd.UdfList.forEach((u1) => {
            if (u1.InputType === 7) {
              const check: number = findIndex(popUps, { Id: u1.Id, Type: 1 });
              if (check < 0) popUps.push(u1);
            }
          });
```
Set a breakpoint on the "If (check" line. 
From the debugger window evaluate popUps and check;
```
check
-1
popUps.length
ReferenceError: popUps is not defined
```

**Comment by connor4312** [comment]
Usually this means one of two things is happening:

1. The variable you're referencing is not used in the current scope (V8 optimizes it away)
2. You have a compilation step which is resulting in the variable being renamed

If you provide a standalone example/repo, I can tell you which case it is
