### ISSUE TITLE
In win10 system, using vscode often exits abnormally

### ISSUE THREAD

**Issue by biaoG** [microsoft/vscode#127837]
When using vscode to open multiple project windows, right-click in the Explorer menu and display it in the file explorer, you will exit abnormally.

**Comment by isidorn** [comment]
Can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by biaoG** [comment]
Please see the attached GIF picture




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode] In win10 system, using vscode often exits abnormally (#127837)





 
/needsMoreInfo

**Comment by biaoG** [comment]
版本: 1.57.1 (user setup)
提交: 507ce72a4466fbb27b715c3722558bb15afa9f48
日期: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
Windows 10 专业版
![动画](https://user-images.githubusercontent.com/18205966/124258151-a9ad1200-db5f-11eb-9f2c-3ad56bb4a0db.gif)
