### ISSUE TITLE
stops running in the middle of the execution 

### ISSUE THREAD

**Issue by gintares** [microsoft/vscode#127883]
My code stops running in the middle ( Windows 10, Bitnami\wampstack-8.0.7-0, Visual Studio ). All breakppoints are removed. I have been checking on different browsers - code stops running in the middle in Opera, Chrome, and Edge.

The code is working in another computer and online debuggers.

I can not reveal the code. What could be the reason for this bug?
I switched to another computer temporary.

**Comment by weinand** [comment]
What code are you debugging?
How do you know that "the code stops in the middle of the execution"? A screenshot could help.
Please provide reproducible steps.
