### ISSUE TITLE
HTML tag navigation does not understand optional tags in hierarchy

### ISSUE THREAD

**Issue by Artoria2e5** [microsoft/vscode#127869]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: macOS 11.4

Steps to Reproduce:

1. Open https://github.com/Artoria2e5/fc712/blob/main/css-hw/index.html in VSCode
2. Navigate to the part that says "don't need them!"
3. Observe the navigation at the top
4. For fun, go to the table and observe its navigation

Expected behavior:
```
p > a
```

Actual behavior:
<img width="372" alt="Screen Shot 2021-07-02 at 18 07 53" src="https://user-images.githubusercontent.com/6459309/124258834-6d2de600-db60-11eb-8575-3b2d2543f23b.png">

Notes:
* VSCode does try to avoid this issue from happening at all by suggesting closing tags. But I really don't want them, especially on a chain of `td`s.
* Using `<section>...</section>` could be a workaround. But this is still a bug!
* I am open to any extension suggestions for formatting this sort of code too :)

**Comment by aeschli** [comment]
duplicated of https://github.com/microsoft/vscode-html-languageservice/issues/63
