### ISSUE TITLE
search in settings editor not working

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#127894]
```
Version: 1.58.0-insider
Commit: 062e6519f8973fede2ca736e80682bd19007460a
Date: 2021-07-02T09:21:19.178Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Steps to Reproduce:

1. Open Settings Editor
2. Search for a tag, e.g. @tag:WorkspaceTrust

Result: Search doesn't return just the tagged settings

![image](https://user-images.githubusercontent.com/1487073/124312357-0559aa00-db24-11eb-94da-1fd8d8ae7f53.png)

**Comment by chrisdias** [comment]
Actually, this only happens on the first query.  

* Reload the window
* Open a Workspace Trust Editor
* Click on `Configure your settings`

Result: Search is not executed

Tweak the search (e.g., type something in the query box) the query is then executed

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/128160
