### ISSUE TITLE
Show linked documentation from another method in VSCode

### ISSUE THREAD

**Issue by tomhanax** [microsoft/vscode#127851]
Issue Type: <b>Feature Request</b>

I am aware of JSDoc @link tag and its support in VSCode. However when clicking on that link VSCode throws me to the actual source code of the target, and that is NOT what I am looking for. I want to see documentation for the link target. I do not see good reason why I should be interested of source code in this scenario. When I read some info about some method and that info gives me more info by linking to another method, I want to see documentation about that method - because that is the information I need, not inspecting the source code. Unwanted "jumping" interrupts a flow of thoughts and work.

The behavior I want is implemented in JavaDoc hover in Eclipse for example.

I tried several combinations of keyboard modifiers while clicking on that link, but no effect. Still thrown to see source code.

Is this somehow configurable / supported? If not, is there any chance to be implemented?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

**Comment by mjbvz** [comment]
Please share some example code that shows this problem and describe the expected behavior for it

**Comment by tomhanax** [comment]
Hope this simple picture will explain more then words:
![obrázok](https://user-images.githubusercontent.com/2083149/124659823-aa1e1380-dea5-11eb-9c90-f4640022748d.png)

When I click on `x` I expect that content of the JSDoc hover will show me JSDoc for variable x, but instead the cursor is moved to declaration of `x`.

**Comment by mjbvz** [comment]
This is the designed behavior of the feature. Just over over the symbol to see its rendered documentation

**Comment by tomhanax** [comment]
> This is the designed behavior of the feature. Just over over the symbol to see its rendered documentation
Of course, I want to see documentation! My complaints are about clicking links in the hover. Why close? Did you read what I wrote?
