### ISSUE TITLE
Visual Studio Code Formatting/Splitting Texts & Codes 

### ISSUE THREAD

**Issue by metacogni** [microsoft/vscode#127844]
Issue Type: <b>Bug</b>

Visual Studio Code is breaking up texts and codes copied either from Atom, ST4, or any other text editor.

Screen-recording is available at https://jmp.sh/vtp8LDP

Pretty sure I’m missing something important but can’t figure it out yet.

Not sure if it is a bug or configuration though lmost of the settings are still in default.

Have searched around a bit but can’t seem to find anyone else with the same issue.

Any insight to get it to stop would be appreciated.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|27, 16, 9|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id a3fd3659-696c-4ec2-9227-29b783c8cd32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cloudcode|goo|1.13.0
terraform|has|2.13.0
smarty|imp|0.3.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurevirtualmachines|ms-|0.4.0
vscode-docker|ms-|1.14.0
vscode-dotnet-runtime|ms-|1.1.0
vscode-kubernetes-tools|ms-|1.3.3
remote-containers|ms-|0.183.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-yaml|red|0.20.0
code-spell-checker|str|1.10.2
vscode-stripe|str|2.0.3
vscode-icons|vsc|11.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by sbatten** [comment]
It seems to me that the source you are copying the text from has inserted new lines into the copied text, perhaps due to text wrapping in the source. Does this occur even with text wrapping turned off in the source editor?

**Comment by metacogni** [comment]
@sbatten 
Good evening. 

Yes, it does happen even with text wrapping disabled.

I have 3 text editors: Atom, Sublime Text 4, and Visual Studio Code which I just started using this year and have started loving it.

But this is a vexing problem making it difficult to switch to it completely.

Even when you write a code with VSC, save it and then open it later with the same editor, you will encounter the same issue.

Write a code with Atom, ST4 and then open it with VSC, you will encounter the same issue.

Write a code, minify it then open it with VSC, the same happens.

And strangely, this tends to happen with texts within HTML snippets.

Terraform, Vagrant and others don't have this issue.

**Comment by rebornix** [comment]
@metacogni can you share the code snippet you are using to help troubleshoot? A screen recording can help a lit.
