### ISSUE TITLE
Do you want to migrate the setting you did for terminal (popup started showing from last few version)

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#127841]
I did setup this in my settings.json 
```
 "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": [
        "-NoLogo",
        "-NoExit",
        "-Command",
        "& { Write-Host }"
    ],
```

I do this so I can get better space in terminal. Now VS code show me popup to migrate. I click on Migrate and these thing were removed from settings.json

I don't see it work properly after migrating. I have opened the settings.json at that time so I just roll back by ctrl + z.

**Comment by meganrogge** [comment]
What was your `defaultProfile `set to in your settings when that happened?

**Comment by anirugu** [comment]
@meganrogge  How to check it?. Do you mean Stable or insiders or something else?

**Comment by meganrogge** [comment]
In insider's, try to reproduce the problem and pls provide me w your terminal settings before and after you migrate

**Comment by anirugu** [comment]
yes

**Comment by anirugu** [comment]
Now I am trying to migrate and it looks like works in a stable version.
