### ISSUE TITLE
File\Open Workspace... uses remote file open dialog when currently open workspace has root(s) using a FileSystemProvider scheme

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#127867]
... it's still the case that when I use `File\Open Workspace...` when I already have a workspace open that uses my FSP's scheme, the remote file open dialog opens. And if my remote is now unavailable this dialog hangs for a long time before allowing me to "Show Local".

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/127647#issuecomment-871490234_

**Comment by gjsjohnmurray** [comment]
pinging @alexr00

**Comment by gjsjohnmurray** [comment]
:+1: just built from source and verified. Thanks for resolving in time for 1.58

**Comment by alexr00** [comment]
Thank you for verifying!
