### ISSUE TITLE
Make commands watermark translatable

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12780]
The keybindings are using ' or ' without NLS support.

**Comment by chrmarti** [comment]
I'd go with Greg's suggestion to use / in #12797. @bgashler1 ?

**Comment by bgashler1** [comment]
I saw you checked that in and it looks good to me.

**Comment by chrmarti** [comment]
@bgashler1 Indeed, meant to wait for your opinion, accidentally slipped it in... Thanks.

**Comment by Tyriar** [comment]
Verified via CR
