### ISSUE TITLE
marked text is not case sensitive

### ISSUE THREAD

**Issue by Molle500** [Microsoft/vscode#12783]
When you highlight a variabel and all the other places in the code the variabel is used on gets highlighted as well. However this function is not case insensitive so testthis === testThis. 

Would love if this could be fixed so it only mark the exact same texts.

//Molle

**Comment by Bill-Stewart** [comment]
Which language? I tried in JavaScript and the highlighting is case-sensitive (as it should be).

**Comment by Molle500** [comment]
@Bill-Stewart Javascript as well.

![image](https://cloud.githubusercontent.com/assets/17712562/18882040/ed83fd14-84dd-11e6-974b-a66d5485f9bc.png)


![image](https://cloud.githubusercontent.com/assets/17712562/18881988/add287c6-84dd-11e6-8e7e-63fd5cb18c08.png)

**Comment by Bill-Stewart** [comment]
I can't reproduce it.

**Comment by Molle500** [comment]
weird

**Comment by jrieken** [comment]
@Molle500 Open search input and toggle the case-sensitivity buttons. It's control by that

**Comment by alexandrudima** [comment]
`alt+c` on windows
