### ISSUE TITLE
Terminal colors not working

### ISSUE THREAD

**Issue by rkelly90** [microsoft/vscode#127895]
Issue Type: <b>Bug</b>

The Django 3.X manage.py commands output color-coded text using escape sequences. These are visible in the output  instead of the expected result of coloring the text. The escape sequence oddly starts with the ← symbol, followed by 31m. A similar problem (albeit with the colorama library) is mentioned in the Stackoverflow post linked below.

https://stackoverflow.com/questions/47432418/output-of-31m-text-instead-of-color

Screenshot of results.
![image](https://user-images.githubusercontent.com/3255080/124312766-dea86d00-db3d-11eb-95d6-39e073915b6b.png)

Expected behavior: text should be the color corresponding to the ANSI code.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.68GB free)|
|Process Argv|--crash-reporter-id 6904e0eb-cc58-4e9c-8ae1-90e14defe878|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.0.1
vscode-graphviz|joa|0.0.6
svg|joc|1.4.7
vscode-peacock|joh|3.9.1
vsc-python-indent|Kev|1.14.2
restructuredtext|lex|153.0.0
xml-format|mik|1.1.2
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
powershell|ms-|2021.6.2
autodocstring|njp|0.5.4
vetur|oct|0.34.1
vscode-git-flow|Psy|0.5.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
trailing-spaces|sha|0.3.1
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by Tyriar** [comment]
This problem is not in VS Code but likely whatever django is using to write the colors or your shell conflicting with conpty.
