### ISSUE TITLE
Copy, cut and paste don't work on PNG rename, in VS Code Explorer

### ISSUE THREAD

**Issue by MakePixelsWork** [microsoft/vscode#127868]
- Open Explorer
- Press F2 on file ending with .png
- Try to copy something from the filename
- Try to paste it

This also doesn't work with outside copied text. For instance when I copy a text from another program, I am not able to paste it within the VS Code Explorer.

For some reason it DOES work on SVG images.

![image](https://user-images.githubusercontent.com/56885246/124258358-96814e80-db2d-11eb-8762-76696a1f6ad6.png)

Why this is an issue > I often copy (partial) file names when searching/editing code, to see where these are used. This does not seem to work on PNG's for some reason.

**Comment by Bardiamist** [comment]
https://github.com/microsoft/vscode/issues/126458
