### ISSUE TITLE
Hide tabs on split terminal if the only one

### ISSUE THREAD

**Issue by zorn-v** [microsoft/vscode#127846]
Currently tabs (right panel with opened terminals) is hidden when only one terminal is opened. It is ok. But if you split it, panel showed up, what is illogical. You already see all terminals and do not need to switch between them.

**Comment by gjsjohnmurray** [comment]
If the tab sidebar wasn't there I don't think you'd see the activity spinners anywhere.

**Comment by zorn-v** [comment]
What are you talking about ?
I mean this
![изображение](https://user-images.githubusercontent.com/12619075/124355072-afcfeb00-dc52-11eb-8aa7-0b95ad7e19fc.png)

**Comment by Tyriar** [comment]
This is already a setting: `"terminal.integrated.tabs.hideCondition": "singleGroup"`

**Comment by zorn-v** [comment]
Thanks, I suspected that it already exists but did not find proper option
