### ISSUE TITLE
Block comment toggle issue

### ISSUE THREAD

**Issue by hqasraful** [microsoft/vscode#127852]
Issue Type: <b>Bug</b>

**Dear Sir/ Madam,**
I am Asraful Haque. At first, I appreciate all your efforts to make the VS Code the most beautiful editor and, I am enjoying it as much except an issue. Suppose I have a Java code below.
```
  public final void display() {
        System.out.println("Try to override the final method.");
  }
```

Now I am commenting on the above code as a block comment and, the result is below
```
/*     public final void display() {
        System.out.println("Try to override the final method.");
    }
 */
```

Now I have used the command Shift + Alt + F to format the whole code, result is below
```
    /*
     * public final void display() {
     * System.out.println("Try to override the final method."); }
     */
```

Now I would like to uncomment the block comment applying the "toggle block comment" command, the result is below
```
/*     /*
     * public final void display() {
     * System.out.println("Try to override the final method."); }
     */ */
```

Overall the function is not working.
**Hope your developers will fix this issue soon to enhance the rich functionality!**

Thanks
**Asraful Haque**
Email: https.www.this@gmail.com
    or this.drive.access@gmail.com

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.28GB free)|
|Process Argv|--crash-reporter-id d3e08a65-1584-40c1-ae89-b3c48559ff82|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
alignment|ann|0.3.0
vscode-intelephense-client|bme|1.7.1
phptools-vscode|DEV|1.4.6842
php-debug|fel|1.16.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-test-explorer|hbe|2.20.4
wordpress|hri|1.0.1
php-namespace-resolver|Meh|1.1.8
fluent-icons|mig|0.0.12
theme-monokai-pro-vscode|mon|1.1.19
language-gettext|mro|0.2.0
vscode-docker|ms-|1.14.0
remote-wsl|ms-|0.56.5
sublime-keybindings|ms-|4.0.9
test-adapter-converter|ms-|0.0.10
java|red|0.80.0
vscode-fileutils|sle|3.4.5
learn-vim|vin|0.0.27
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
wordpress-toolbox|wor|1.3.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by aeschli** [comment]
> Now I have used the command Shift + Alt + F to format the whole code, result is below

I can't reproduce that. The built-in JavaScript/TypeScript formatter doesn't change the content of a block comment.

Are you maybe using a different formatter?
