### ISSUE TITLE
Foreground icon colors of selected tree/list items

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#127882]
This is in the SCM view. The title is using the correct color, the twisty and the actions aren't:

![image](https://user-images.githubusercontent.com/4674940/124290903-d84bce00-db08-11eb-9bd8-4bf6c023638f.png)

**Comment by misolori** [comment]
This is a result from https://github.com/microsoft/vscode/issues/125998 where most themes don't have a strong contrasting focus state so there was a request to allow themes to opt-in to the stling. You'll need to set `list.activeSelectionIconForeground` in your theme/user settings to get this to work.
