### ISSUE TITLE
CodeSnippet doesn't support empty brackets anymore - {{}}

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/vscode#12786]
Hi,
 
I’m migrating our code from version: 0.1.0(6c0fe2014e7a7d596ac1af21f25bf2fc17da8a75) to the latest Monaco editor release version: 0.6.1(8f43cf5d0d3d233c9ba1c9085f2bb529f834c841).
 
During the process I encountered a breaking change, hopefully you may help.
 
We are using the SuggestController for showing intellisense for a custom language (‘Kusto’).
In the suggestion we are using codeSnippets with empty brackets {{}}, for placing the cursor inside the added text. 
For example, codeSnippet: ‘count({{}})’.
When the suggestion is selected the value ‘count()’ is added to the editor and the cursor is placed between the brackets. 
In the new release, empty brackets {{}} doesn’t place the cursor in the right position.
 
Another thing, after the user selects a suggestion from the list we trigger again the suggestController to show him more suggestions (without him pressing anything). 
 
           // Trigger automatically the intellisense suggestions after the user accepted a suggestion
           function suggestionAcceptListener() {
               if (!_editor) return;
               
               _editor.onDidChangeCursorSelection(function (event) {
                   // Re-trigger the suggestions right after the user selected one of the suggestions
                   var acceptSuggestion = (event.source === 'modelChange' && event.reason === monaco.editor.CursorChangeReason.RecoverFromMarkers);
                   if (!acceptSuggestion) {
                       return;
                   }
 
                   triggerSuggestions();
               });
           };
 
           function triggerSuggestions() {
 
               var _suggestController = _editor.getContribution("editor.contrib.suggestController");
 
               if (!_suggestController) {
                   return;
               }
 
               _suggestController.model.cancel();
               $timeout(function () {
                   _suggestController.model.trigger(true);
               }, 10);
           };
 
 
I tried to replace the empty brackets with {{ }} (adding a space in between the brackets). The cursor move to the right position, standing on a blue space. The suggestions window is opened again. When the user now selects an item from the suggestions list, we crash. (It seems that the snippetController has been destroyed already, probably since we re-trigger the suggestController).
 
Is there anything I can do?
Can you fix it?
 
Thanks!
Anat
 
For playing with the old editor and see what I’m trying to achieve:
1.	Go to https://analytics.applicationinsights.io/demo
2.	Open a new query tab (next to the Home Page tab)
3.	Write in the editor (or copy paste):
customEvents
| where timestamp >
4.	Add a space to trigger the suggestController.
5.	Select ‘ago()’
6.	See the suggestions window is opened again, while the cursor is inside the brackets.

**Comment by alexandrudima** [comment]
re CodeSnippet `{{}}` -- fyi @jrieken

**Comment by jrieken** [comment]
closing as dup of #11742
