### ISSUE TITLE
terminal.integrated.splitCwd="inherited" is not working on Windows/WSL2 + Multiroot Workspace

### ISSUE THREAD

**Issue by jchang10** [microsoft/vscode#127811]
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.58.0-insider (user setup)
Commit: 1fc68f3cf274141942b424894645a4f7096ec1f1
Date: 2021-07-01T09:30:57.217Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. This error I think only occurs using Workspaces. A single project, the terminals seem to work fine. However,
with multiple projects, the environment gets confused.
2. New Terminal (ctrl+shift+`)
3. Split Terminal 

I get this error message: 'The termial process failed to launch: Starting directory (cwd) "\home\username\my\project"'. The first terminal works, but it's the second or subsequent terminal that creates the error.

This is using the VSCode for Windows using WSL Remote. This error has now existed for at least a week in the Insiders edition. I am surprised this has not already been brought up.

I think the error is indicating that its confusing a windows path for a linux path. Because this is using WSL-Remote, the path should be using forward slashes not backslashes for windows.

This happens when "terminal.integrated.splitCwd" is inherited or initial. The workaround is to set this to workspaceRoot, then it works. However, it's annoying not to have inherited or initial working. Also, nowhere in my settings is "cwd" assigned anywhere.

Also there is #121705, but I suspect the issue on MacOS is different.

Jae

**Comment by jchang10** [comment]
The bottom line: The first or default terminal is properly run in WSL2. However, any subsequent new terminals are being recognized as a Windows environment, not Linux.

**Comment by jchang10** [comment]
Ok I guess this work-around works, but still not understanding.

I just discovered there is a command called "Create new Integrated terminal (In Active Workspace)"; where as the default "New Terminal" calls only "Create new Integrated terminal".

Turns out the version "In Active Workspace" works properly. The Windows/Linux environments are not confused and the SplitCmd works as expected.

Still I dont understand why if I am using a Workspace, why would I NOT want "In Active Workspace", right? I mean I am in an active workspace, so why not use it?

**Comment by Tyriar** [comment]
Can repro:

![image](https://user-images.githubusercontent.com/2193314/126505621-68d568d1-8f9b-486d-a236-4b9973b5dd5c.png)

1. Open multi-root workspace in WSL
2. ctrl+shift+`
3. ctrl+shift+5

**Comment by Tyriar** [comment]
Ah this is happening because we're getting a `string` instead of a `Uri` here:

https://github.com/microsoft/vscode/blob/b4947565d28f09f9f3d5190cae7178c28784572d/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L69-L72

**Comment by InsidersByte** [comment]
I'm also getting this issue when using inherited for workspaces and remote ssh from a windows to a linux host.

If I reload the window I am able to split the terminal for terminals that were created before the reload.

Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by lukasz-mitka** [comment]
Same here.
```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by spasche** [comment]
As a workaround for this issue in version 1.58, I was using this setting:
```"terminal.integrated.splitCwd": "workspaceRoot"```

But now in version 1.59.0, the issue happens with any `terminal.integrated.splitCwd` values 😭.

**Comment by jchang10** [comment]
Awesome! Just got the fix in insiders! Thank you!

**Comment by stuartleeks** [comment]
Verified fixed in

```
Version: 1.60.0-insider (user setup)
Commit: 5f19eee5dc9588ca96192f89587b5878b7d7180d
Date: 2021-08-24T19:41:58.784Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
