### ISSUE TITLE
Select to beginning/end of paragraph

### ISSUE THREAD

**Issue by qua4tre** [microsoft/vscode#127897]
In the spirit of [#114166](https://github.com/microsoft/vscode/issues/114166), I would find it incredibly helpful to have a command to select from the current cursor position to the beginning or end of the next paragraph (delimited by blank lines) in the editor.  It's tedious to select a block of code one line at a time.

**Comment by sbatten** [comment]
Does `Expand Selection` serve your needs? `Shift+Alt+Right Arrow` on Windows by default.

**Comment by qua4tre** [comment]
It's helpful but not great.  It appears to take 6 or 7 levels of expanding (word, delimiter, beginning of line, end of line, etc.) before I finally get to a whole code block, which is again, tedious, and then from there it expands to the whole page, there's no way to select multiple (2 or 3 or n) blocks.  I suppose I can live without it but I can't tell you how many times I want to select whole blocks and move them around, or delete them in some cases.  It's easy to do exactly that in both Atom and Emacs, which are the previous (and still current) editors I've used.

**Comment by ArturoDent** [comment]
```jsonc
{
  "key": "ctrl+down",
  "command": "cursorMove",
  "when": "editorTextFocus",
  "args": {
    "to": "nextBlankLine",
    // "by": "wrappedLine",
    "select": true
  }
},

{
  "key": "ctrl+up",
  "command": "cursorMove",
  "when": "editorTextFocus",
  "args": {
    "to": "prevBlankLine",
    // "by": "wrappedLine",
    "select": true
  }
},
```

**Comment by qua4tre** [comment]
Aha, perfect! That's exactly what I'm looking for. 

Adding shift to those keybindings lets me differentiate between just moving the cursor and simultaneously selecting.
