### ISSUE TITLE
Sorting Keyboard Shortcuts By Precedence Should Indicate Sorting Direction (Asc/Desc)

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127855]
Since the `weight` is not shown, it is very hard to understand if keyboard shortcuts are sorted in ascending or descending order, when sorting them by precedence:

![image](https://user-images.githubusercontent.com/2931520/124237458-d6d5d200-db17-11eb-98e6-c487df846859.png)

**Comment by sandy081** [comment]
@hediet It is just sorting in one direction, there is no reverse of it and hence it is a two state toggle (on/off).

**Comment by hediet** [comment]
> It is just sorting in one direction

But in which direction? Usually, the default sort-direction is ascending. But I guess here it is descending?

**Comment by sandy081** [comment]
yes

**Comment by hediet** [comment]
Since it is not the default sort-direction, I recommend to indicate the sorting order. E.g. a tooltip "Sort by precedence (highest weight first)".

**Comment by sandy081** [comment]
Is not it expected that when you sort by precedence, keys appear first has more precedence. Not sure what does the mean for an user to call out weight.

**Comment by hediet** [comment]
>  Not sure what does the mean for an user to call out weight.

What about "Sort by precedence (highest precedence first)" then?

> Is not it expected that when you sort by precedence, keys appear first has more precedence

It might be common sense, but the opposite sorting direction would also be justified. Since it is sorted by an invisible column, I would at least put some text into the tooltip of the sort button.

**Comment by sandy081** [comment]
Added `(Highest first)` to the label.
