### ISSUE TITLE
registerCompletionItemProvider with letters as trigger characters block other completion items to show up 

### ISSUE THREAD

**Issue by leti367** [microsoft/vscode#127815]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a new simple extension which uses "vscode.languages.registerCompletionItemProvider" API and set the TriggerCharacters as any letters, for example 'a'.

2. Start the extension. Create a ts file(supported file for this provider), type 'a'(trigger character), the popup completionitem list only contains results from test provider and snippet, all others are gone.

Without test extension running, there are bunch of completion items:
![image](https://user-images.githubusercontent.com/26910868/124178072-f6142700-da65-11eb-97af-0222d2a5536a.png)

With test extension running, only snippet and results from test provider show up, all the others are gone:
 
![image](https://user-images.githubusercontent.com/26910868/124178124-07f5ca00-da66-11eb-9aec-6bdb0e4a7e39.png)

The test provider:
![image](https://user-images.githubusercontent.com/26910868/124178238-2fe52d80-da66-11eb-99a4-9256241c335f.png)

**Comment by jrieken** [comment]
\closedWith 0984071fe0d8a3c157a1ba810c244752d69e5689

**Comment by leti367** [comment]
@jrieken Thanks for taking care of this. When would this change be available for us to do the tests?

**Comment by jrieken** [comment]
Will be next 1.59 insiders, likely tomorrow
