### ISSUE TITLE
Opening a folder in VS Code opens two instances

### ISSUE THREAD

**Issue by polys** [microsoft/vscode#127814]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Make sure you don't any VS Code instances running.
2. Do any of the following:
    - go in a folder with some code, right-click and "Open with Code"
    - `code .` in a terminal
    - right-click VS Code pinned on the taskbar or the start menu and open a recent folder
3. Two instance of VS Code open, one with your folder as expected, and another which is empty.

This started happening just after updating to the [May 2021 release](https://github.com/microsoft/vscode/releases/tag/1.57.0); everything was fine before that.

I'm not sure if this is related to #73638 but this can't possibly be a feature by design. 

The empty instance always looks like this (even the size of the window seems to always be the same):
![image](https://user-images.githubusercontent.com/4301432/124177161-c423b480-daa7-11eb-828d-60f12bb5ccc3.png)

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/126725

you can find instructions in there how to get out of it or stay with VSCode insiders.

**Comment by polys** [comment]
Many thanks @bpasero.
VS Code Insiders fixed it for me :)

**Comment by apex-blaze** [comment]
I found this solution in one of the already closed issues -
For window users - **Go to C:\Users\MY PC\AppData\Roaming\Code\**   file address and delete "Backups" folder inside it.
That just fixed my issue. 
Note:- Here, "MY PC" is my username and it could be possible that you can't find one of these folders, just enable your hidden folders!!!

**Comment by Christian-Klempau** [comment]
Fixed by deleting `Backups` folder at: `AppData\Roaming\Code\Backups\`. Thanks!
