### ISSUE TITLE
Intellisense for local report function on class obejct blocked by assert.CallTracker.report()

### ISSUE THREAD

**Issue by brendanhorne** [microsoft/vscode#127833]
I have a class with a report method.
When I am using the intellisense with this method I can only see this option in the screenshot below.

I have renamed the method and this issue disappears, however I don't want to rename the method and report is a fairly common name for a method so others will probably have the same issue as well. 

Kind regards and thanks!
![image](https://user-images.githubusercontent.com/53585097/124204433-6a140500-db22-11eb-9f90-7b69a6e2aa6b.png)

**Comment by mjbvz** [comment]
Please share a complete, self contained code example that demonstrates the issue

/needsMoreInfo
