### ISSUE TITLE
Use keyboard left and right to move between the menus

### ISSUE THREAD

**Issue by KonradHoeffner** [microsoft/vscode#127858]
Issue Type: <b>Feature Request</b>

Normally, users can navigate between menus, such as File and Edit, using the left and right arrow keys on the keyboard. However in Code this is not possible.

I use keyboard navigation all the time and miss this feature heavily as I'm sure many others do as well, please add this feature.

VS Code version: Code - OSS 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-06-18T02:30:22.835Z)
OS version: Linux x64 5.12.13-1-ck-skylake

**Comment by sbatten** [comment]
Workaround (though not optimal on linux due to styling): Use `window.titleBarStyle`: `custom` in your settings.


Issue due to electron menus

**Comment by KonradHoeffner** [comment]
This works, thanks! However there is an inconsistency between left and right movement:

When I hold down the left arrow key, it begins to move automatically like a text cursor and wraps around from the left edge to the right edge.

However when hold down the right arrow key it neither moves automatically, nor does it wrap from right to left.

**Comment by deepak1556** [comment]
Unable to repro on Ubuntu 22.04 with latest stable `1.74` on wayland.
