### ISSUE TITLE
Allow workbench.extensions.action.installVSIX command to accept additional arguments

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode#127803]
Would it be possible to make the `workbench.extensions.action.installVSIX` command accept a specific VSIX file as an argument? Allowing the command to be used by extensions that want to install/update packages without requiring interaction with users.

Note: The issue #58119 comments that this has been resolved, but performing tests it seems not.

**Comment by usernamehw** [comment]
It should already work:

```js
vscode.commands.executeCommand('workbench.extensions.command.installFromVSIX', [vscode.Uri.file(vsixPath)]);
```

**Comment by AlencarGabriel** [comment]
Using the command provided by @usernamehw worked correctly, thanks.
