### ISSUE TITLE
hash marks in terminal.integrated.defaultProfile descriptions

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#127807]
- VS Code Version: 1.57.1
- OS Version: Windows 10

Bring up the Settings JSON view.

There are trailing and leading # hash marks for the other setting references:

```json
	// The default profile used on Linux. This setting will currently be ignored if either `terminal.integrated.shell.linux#` or `#terminal.integrated.shellArgs.linux` are set.
	"terminal.integrated.defaultProfile.linux": null,

	// The default profile used on macOS. This setting will currently be ignored if either `terminal.integrated.shell.osx#` or `#terminal.integrated.shellArgs.osx` are set.
	"terminal.integrated.defaultProfile.osx": null,

	// The default profile used on Windows. This setting will currently be ignored if either `terminal.integrated.shell.windows#` or `#terminal.integrated.shellArgs.windows` are set.
	"terminal.integrated.defaultProfile.windows": null,
```

The settings links are fine in the UI Settings editor.

**Comment by gregvanl** [comment]
@meganrogge Do you have any idea why those hash marks were added in the first place? I've seen them several times when a setting description references another setting.

**Comment by meganrogge** [comment]
I do not know. I suspect that was maybe at one time the way to emphasize text in markdown descriptions? We'd have to ask @Tyriar, which is why I've added him to this issue 😄

**Comment by gregvanl** [comment]
@meganrogge How did the description look in the Settings editor after your change. Were the settings references still links?

**Comment by gregvanl** [comment]
The links are now gone, which would normally be the wrong fix, but since the referenced settings are deprecated, the links don't work in 1.57.1. So just showing the referenced settings as inline code blocks, is probably the best experience.

**Comment by meganrogge** [comment]
Yes I thought it looked better with the change, though not ideal

**Comment by Tyriar** [comment]
The hashes enable linking between settings in the settings UI and it always looks kind of bad in the settings json, since it's deprecated I don't think it worked so this is fine 👌
