### ISSUE TITLE
Call hierarchy item implementation not satisfy the spec

### ISSUE THREAD

**Issue by July541** [microsoft/vscode#127853]
The call hierarchy item implementation in [vscode](https://github.com/microsoft/vscode/blob/d39b3736945f00c9c428f4706845eecc52de6322/src/vs/workbench/contrib/callHierarchy/common/callHierarchy.ts#L26) does not satisfy the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareCallHierarchy), it missed the `data` filed which may necessary in some conditions.

**Comment by jrieken** [comment]
The vscode.d.ts-API  isn't an implementation of the LSP spec but API that full-fills the spec. Indeed, it's usually the other way around: vscode add an API in `vscode.d.ts` and that makes it eventually into the spec.

**Comment by July541** [comment]
@jrieken It turns out `vscode.d.ts` still has no `data` field, I just curious where is it?
