### ISSUE TITLE
Open Containing Folder does not open on right location

### ISSUE THREAD

**Issue by DusanLesan** [microsoft/vscode#127818]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-06-18T02:30:22.835Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
- OS Version:
OS: Linux x64 5.12.14-arch1-1

When opening a directory by using "Open Containing Folder" from explorer context menu, the resulting location is always moved by one level up. For example when trying to open containing directory for file ~/.config/code-oss/user-data/Preferences, the file manager is opened at  ~/.config/code-oss and not at ~/.config/code-oss/user-data

Steps to Reproduce:

1. Open code
2. Open a folder
3. Use Open Containing Folder option from the context menu
4. Validate the opened location

![image](https://user-images.githubusercontent.com/20520590/124177805-01d90b00-dab1-11eb-95a7-913edd1d3302.png)
In this image you can see chosen file and lf opened at the wrong location. This is not issue with lf since I have managed to reproduce this behavior with thunar and web browser also.
This is not OSS only issue as I have managed to reproduce with following version too:
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.12.14-arch1-1

I would like to have the ability to add new context menu options and and edit existing ones without use of extensions. Like if I want to pass full file path instead off only directory path. That would allow me to have file focused in my file manager. Best example of this feature I can think of is settings for Smartgit
![image](https://user-images.githubusercontent.com/20520590/124179694-79a83500-dab3-11eb-9518-fe059f5a7b3f.png)

**Comment by isidorn** [comment]
Code pointer for this command if you would like to investigate more https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/electron-sandbox/fileActions.contribution.ts#L39

As for the customising menus, I think that is on the plan.
And adding other command to the menu is only possible through extensions

**Comment by DusanLesan** [comment]
@isidorn The code did not mean much to me as I do not even know how to debug VSC. Adding custom entries sound reasonable to be done by extensions. 
Were you able to repro the issue?
Do you maybe know anything about mentioned customization? Will it allow to user to select what is passed to system?
