### ISSUE TITLE
Make it possible to select multiple lines

### ISSUE THREAD

**Issue by Molle500** [Microsoft/vscode#12782]
Something pretty much every editor has but not vscode is selecting multiple lines, hold the alt key and drag your mouse down or up to select the lines you want. When you start typing the same letters appears on every line.

**Comment by Bill-Stewart** [comment]
Actually code can do it. See: http://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections

**Comment by Molle500** [comment]
Oh, kinda weird tho that you have to click every line? why not support drag like the other editors? 😞

**Comment by Bill-Stewart** [comment]
You can. Just use the column select commands on the keyboard (defaults are <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>down</kbd>, etc).

**Comment by Molle500** [comment]
yeah thx

**Comment by Zhouxing-Su** [comment]
It seems not working with .tex files.

**Comment by alexandrudima** [comment]
We support the following mouse gestures for multi-cursor / column selection related functionality:

* Shift + Alt + Click
* Alt + Click
* Alt + Double click
* Alt + Triple click
* Alt + Click (on the line gutter)
