### ISSUE TITLE
editor from the terminal area gets used in the terminal panel ....

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#127892]
With these settings
```
"terminal.integrated.defaultLocation": "editor",
    "terminal.integrated.tabs.hideCondition": "never",
    "terminal.integrated.tabs.showActions": "always",
    "terminal.integrated.tabs.showActiveTerminal": "always"
```

Steps to Reproduce:

1. Create an editor terrminal, close it
2. Open the terminal panel -> 🐛 there is a terminal there, but it isn't displayed as the active terminal in the single terminal view 

I suspect that when the editor is closed, the terminal is not disposed of, so gets used in the panel, but is unknown to the group service

Discovered by @rzhao271

**Comment by meganrogge** [comment]
![recording (22)](https://user-images.githubusercontent.com/29464607/124308104-9ed18d80-db1d-11eb-86ff-ff0d71d65c2c.gif)

**Comment by meganrogge** [comment]
Can't reproduce in the latest Insider's.

**Comment by Tyriar** [comment]
This would have fixed that one https://github.com/microsoft/vscode/commit/7d00e4e56078623c828911e0f5798aad84b2bf17
