### ISSUE TITLE
Provide json schema programmatically

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#127812]
Our extension needs to use a json schema installed by another program. The current way of providing json schema by an extension, i.e., using json schema contribution point in package.json, seems to be limited to files in the extension itself. It would be great if there is a way to provide a json schema programmatically in our source code.

**Comment by aeschli** [comment]
It's possible to provide a schema through a document provider:

**Comment by xisui-MSFT** [comment]
@aeschli Thanks for the proposal. Unfortunately this method doesn't seem to work for us either. Although it works fine if the file is opened after VS Code opens, and our extension activates, but if the json file is opened at the start of VS Code, then we get an error `Unable to resolve resource...`.

My guess is, if a json file is opened at the start of VS Code, our extension always activates later than VS Code trying to resolve the resource, and therefore it can't find the document provider, and so we see that error. Also, VS Code never tries to resolve the resource again, so even if we close and reopen the json file, the same problem appears.

Any idea how to solve this issue?

**Comment by aeschli** [comment]
It seems we don't have an specific activation event for documents provided by `TextDocumentContentProviders`.
@jrieken Is the recommendation to use `onFileSystem:scheme` ?

**Comment by jrieken** [comment]
Yeah, the `onFileSystem` event should be fired in this case too

**Comment by aeschli** [comment]
@xisui-MSFT Please add to your `package.json`
```
  "activationEvents": [
    "onFileSystem:yourScheme"
  ],
 ```

**Comment by xisui-MSFT** [comment]
@aeschli Great this resolves our issues. Thanks very much!
