### ISSUE TITLE
Add `Search Only in Open Editors` argument to the `workbench.action.findInFiles` command

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#127898]
The `workbench.action.findInFiles` command currently can access all the options from the Search view like:

```jsonc
  {
    "key": "ctrl+shift+f",
    "command": "workbench.action.findInFiles",
    "args": {

      "query": "",
      "replace": "",
      "triggerSearch": true,
      "isRegex": true,
      "filesToInclude": "", 
      "filesToExclude": "",
      "matchWholeWord": false,
      "isCaseSensitive": false,
      "useExcludeSettingsAndIgnoreFiles": true,
      "preserveCase": true
    }
  }
```

or the same in an `executeCommand` call in an extension.  I would like to be able to designate the `Search Only in Open Editors` option as well - it appears to be the only available option missing.  

It would be extremely useful in an extension.  I suggest `searchOpenEditors` boolean

**Comment by roblourens** [comment]
FYI @JacksonKearl

**Comment by ArturoDent** [comment]
Thank you for the quick update.  I'll try it out tomorrow.

**Comment by ArturoDent** [comment]
/verified 

although it does exhibit the same behaviour as enabling the "Search Only in Open Editors" option **manually** in that `settings.json` and `keybindings.json` are not included in "open editors".   But I assume that is a different issue.

**Comment by 429IhD0** [comment]
Would it be possible to add a command for toggling "Search Only in Open Editors"?
Currently we have toggle commands for toggleSearchRegex, toggleSearchCaseSensitive, toggleSearchWholeWord, etc, but not for "Search Only in Open Editors", even though it has a button in the search interface just like the others.

**Comment by JacksonKearl** [comment]
@429IhD0 that is a fair feature request, please open a new issue for it.
