### ISSUE TITLE
Build VS Code using latest TS 4.4

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#127822]
Tracks upgrading to TS  4.4.0-dev.20210701

**Comment by mjbvz** [comment]
PR #127823 fixes most issues. Remaining issues listed below:

To fix:

`git fetch`
-  checkout `dev/mjbvz/build-ts-4-4`
- `yarn` to get new TS 
- `yarn run watch`

Issues and owners (please reassign if I got the owner wrong):

- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(232,22)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(235,26)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(239,33)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(243,22)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(246,26)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts(250,33)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts(207,31)`: 'OffscreenCanvas' only refers to a type, but is being used as a value here. @Tyriar 
- [ ] `src/vs/workbench/browser/parts/titlebar/titlebarPart.ts(517,22)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/browser/parts/titlebar/titlebarPart.ts(519,22)`: Property 'zoom' does not exist on type 'CSSStyleDeclaration'. @sbatten 
- [ ] `src/vs/workbench/browser/parts/editor/tabsTitleControl.ts(326,82)`: Cannot find name 'MouseWheelEvent'. @sbatten 
- [ ] `src/vs/editor/browser/viewParts/lines/rangeUtil.ts(51,135)`: Cannot find name 'ClientRectList'. @alexdima 
- [ ] `src/vs/editor/browser/viewParts/lines/rangeUtil.ts(97,69):` Cannot find name 'ClientRectList'. @alexdima 
- [ ] `src/vs/editor/browser/view/domLineBreaksComputer.ts(291,19)`: Cannot find name 'ClientRectList'. @alexdima 
- [ ] `src/vs/editor/browser/view/domLineBreaksComputer.ts(319,106`): Cannot find name 'ClientRectList'. @alexdima 
- [ ] `src/vs/editor/browser/controller/mouseTarget.ts(853,26)`: Property 'caretRangeFromPoint' does not exist on type 'ShadowRoot'. @alexdima 
- [ ] `src/vs/editor/browser/controller/mouseTarget.ts(856,24)`: Property 'caretRangeFromPoint' does not exist on type 'ShadowRoot'. @alexdima 
- [ ] `src/vs/editor/browser/controller/mouseTarget.ts(859,21)`: Property 'caretRangeFromPoint' does not exist on type 'Document'. @alexdima 
- [ ] `src/vs/editor/browser/controller/mouseTarget.ts(953,23)`: Property 'caretRangeFromPoint' does not exist on type 'Document'. @alexdima 
- [ ] `src/vs/editor/browser/controller/mouseTarget.ts(970,38)`: Property 'elementFromPoint' does not exist on type 'ShadowRoot'. @alexdima 
- [ ] `src/vs/base/browser/touch.ts(136,99)`: Property 'msMaxTouchPoints' does not exist on type 'Navigator'. Did you mean 'maxTouchPoints'? @alexdima 
- [ ] `src/vs/base/browser/canIUse.ts(44,98):` Property 'msMaxTouchPoints' does not exist on type 'Navigator'. Did you mean 'maxTouchPoints'? @alexdima 
- [ ] `src/vs/base/browser/canIUse.ts(45,181)`: Property 'msMaxTouchPoints' does not exist on type 'Navigator'. Did you mean 'maxTouchPoints'? @alexdima

**Comment by rebornix** [comment]
`msMaxTouchPoints` is for IE 10 which we don't support anymore, we can remove that.

**Comment by mjbvz** [comment]
Hey @alexdima did you perhaps forget to push the fixes for `mouseTarget.ts`? I don't see any changes in that file

**Comment by alexdima** [comment]
That was it! Sorry about that. Pushed now:

https://github.com/microsoft/vscode/commits/dev/mjbvz/build-ts-4-4
![image](https://user-images.githubusercontent.com/5047891/124722445-5a256800-df0a-11eb-9dbc-54b189a5a835.png)

**Comment by mjbvz** [comment]
Just merged this. @sbatten Please follow up on the any casts I had to add for the usages of `zoom`
