### ISSUE TITLE
SINGLE cursor continuous selection mode

### ISSUE THREAD

**Issue by TianqiLi7398** [microsoft/vscode#127831]
I've experienced multiple times about accidentally entering a mode that the cursor will start select to wherever it goes by your directional key (u,l,r,d), not only cross lines but also inside one line. There is already on discussion [here](https://www.reddit.com/r/vscode/comments/ejza3q/every_once_in_a_while_text_is_automatically/). And every time I got inside this mode, I cannot turn it off unless reload the windows. This should no be a system's problem like sticky shift key, since I tested on other ides.

There is no direct answer, thus I think the official one should be great. Actually I love this feature, if it's a bug please fix it and add it as a function; if it is a function, please tell me how to use it.

Thanks!

**Comment by alexdima** [comment]
When you are in this mode, can you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire. (`ArrowLeft`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
