### ISSUE TITLE
tsconfig baseUrl helper is misleading 

### ISSUE THREAD

**Issue by michalvankodev** [Microsoft/vscode#12781]
- VSCode Version: 1.5.3
- OS Version: Fedora 24

Steps to Reproduce:

1. Open any project tsconfig.json
2. Into `compilerOptions` add `baseUrl`
3. A helper which should explain what baseUrl does shows a misleading message:

_"Base directory to resolve non absolute names"_

It should show: 
_"Base directory to resolve non-relative module names."_

I tried to search this and Typescript repository for a potential PR but I wasn't successful finding the definition for this message.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#11203

**Comment by dbaeumer** [comment]
The message comes from the JSON schema maintained by TS team.
