### ISSUE TITLE
Typo in extensions.supportUntrustedWorkspaces description

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#127802]
- VS Code Version: 1.57.0
- OS Version: Windows 10

"Override the untrusted workpace support of an extension"
workpace -> workspace

![image](https://user-images.githubusercontent.com/12818376/124160914-9f045700-da51-11eb-9fbc-75c8f5639a4d.png)

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/9f7309348f4139404cc1e339216a017bc49884f2
