### ISSUE TITLE
To code on remote windows server

### ISSUE THREAD

**Issue by vigneshconfianza** [microsoft/vscode#127857]
Its great to see code and test on linux server from vc studio. It would be great if we also have feature to connect to remote windows server. Code and test them from my local laptop using vc studio.
If any existing feature, please guide me to use it

**Comment by foxeswolf** [comment]
Vscode remote login code can not jump how to solve it

**Comment by sbatten** [comment]
https://code.visualstudio.com/docs/remote/ssh highlights how to connect to remote machines including windows remotes.
