### ISSUE TITLE
Feature request: show deprecations in problems panel

### ISSUE THREAD

**Issue by jl-mindius** [microsoft/vscode#127880]
I had to update some old spaghetti from jQuery 1.x to 3.x today. The deprecation decorations were very helpful but a bit hard to make use of since the code had to be scanned manually. (E.g. noticing <img width="199" alt="form.submit(function(e) {" src="https://user-images.githubusercontent.com/17906528/124285585-54b4d000-db4e-11eb-9b36-809e86121d74.png"> when scrolling through thousands of lines).

According to #78226 it seems to be a conscious decision to exclude deprecations from the problems panel by default, but could an option be added for it?

**Comment by sandy081** [comment]
/duplicate

Yeah it was intentional as mentioned in https://github.com/microsoft/vscode/issues/78226. I am sorry that there are no plans to add this. We will revisit if there are more similar asks. Thanks
