### ISSUE TITLE
Not allowed more than one execution for a notebook cell

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#127884]
Version: 1.58.0-insider (user setup)
Commit: 1fc68f3cf274141942b424894645a4f7096ec1f1
Date: 2021-07-01T09:30:57.217Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

I recently implemented execution syncing for Live Share notebooks. When working on this I realized that you `Cannot call start again` on a CellExecution. I assumed this meant that you could not call start twice, and that each task was single-use. I confirmed this with a sample repro extension this morning.
![image](https://user-images.githubusercontent.com/22576531/124296184-873ed880-db0e-11eb-99f9-6d810161adc8.png)

To sync outputs and execution states between the host and guest, I need to update the guest notebook both when the host's execution state changes and also when the output changes. However, these events are not guaranteed to happen in a specific order and also there are situations in where the cell output does not change for a given action. My approach was to create a new execution task to deal with outputs, and also create a new execution task to deal with execution state changes. This approach worked last week - execution states and outputs were syncing as expected.

However, these changes no longer work. Execution syncing is broke and the following error is shown when trying to run a cell. 
![image](https://user-images.githubusercontent.com/22576531/124296086-6e362780-db0e-11eb-8ba6-2991041eca0c.png)

Based on this,  __is there a new requirement that there cannot be more than one execution task per cell?__ How can you run a cell more than once if you can:
1) only start an execution task once and
2) only have one execution task per cell

`NotebookCellExecution` is not disposable, so I'm not sure how I can dispose of executions in order to create more? 

cc @rebornix @jrieken

**Comment by alyssajotice** [comment]
Hey @roblourens, any updates here?

**Comment by roblourens** [comment]
There isn't a new change here, so I'm not sure why it would have worked before. I don't think it makes sense to say that one cell is involved in two executions at the same time. I would suggest having one execution object in some map, and when you have to do an output update, first check whether there is an active execution for that cell.

**Comment by roblourens** [comment]
And make sure that you call `end()` on an execution to complete it.

**Comment by alyssajotice** [comment]
I didn't change anything in Live Share's code and the above errors are no longer displayed when executing cells. I am not sure what happened, but it doesn't seem to be a problem any longer. I'll close the issue.
