### ISSUE TITLE
Add a feature for Ignore List to VS Code, like the browsers have

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#127886]
Super helpful to hide (temporarily) the call stack items when debugging.

![image](https://user-images.githubusercontent.com/1202528/124296722-481d8100-db28-11eb-8bee-6dd16f65e860.png)

**Comment by roblourens** [comment]
This would be a feature request for the js debug adapter (https://github.com/microsoft/vscode-js-debug). Actually I think the old debug adapter had this feature for dynamically adding files to skipFiles. Currently you have to configure this with skipFiles in your launch.json
