### ISSUE TITLE
External terminal not working for debugging node program

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12791]
Bug found while testing #12252
- VSCode Version: 1.6 Insider
- OS Version: Ubuntu 16.04

Debug on external terminator only works for `gnome-terminal`, the default on Ubuntu. Fails for `rxvt-unicode` and `terminator`.

Steps to Reproduce:

One: Create an empty project. `npm i express`. Make `app.js` like this:

``` js
var express = require('express');
var app = express();

var process = require('process');

console.log(process.cwd());
console.log(process.argv);

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

Two: 
My launch.json

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app.js",
            "stopOnEntry": false,
            "args": ["test"],
            "cwd": "${workspaceRoot}/node_modules",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "externalTerminal",
            "sourceMaps": false,
            "outFiles": []
        }
    ]
}
```

Workspace setting:

``` json
{
    "terminal.external.linuxExec": "rxvt-unicode"
}
```
## rxvt-unicode

Launches external terminal. Outputs `Debugger listening on [::]:43160`, but after few seconds VSCode show error saying "Cannot launch debug target in terminal (timeout)".
## terminator

Launches external terminal. Almost look like cd'ed into `cwd`, because it shows `octref@ubuntu:~/Downloads/test/node_modules`, the `cwd` I specified in the launch config.

Same error "Cannot launch debug target in terminal (timeout)" is shown after a few seconds.

**Comment by isidorn** [comment]
I think this is as designed and that rxvt-unicode and terminator where never supported. Anyways leaving for @weinand to decide.
