### ISSUE TITLE
Slow Opening

### ISSUE THREAD

**Issue by lnm451** [microsoft/vscode#127909]
After cleaning up my computer, my VS Code opens up to 30s. Reinstall doesn't help. Maybe I deleted some file, please help me to solve it. Thanks so much

1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
## System Info

* Code: 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48)
* OS: win32(10.0.19041)
* CPUs: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz(12 x 2208)
* Memory(System): 15.85 GB(7.98GB free)
* Memory(Process): 161.93 MB working set(107.81MB private, 0.17MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 4420     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 163      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 31       | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 4        | [main]                    | initial startup: true                                       |
| create window                                                   | 165      | [main]                    | initial startup: true, state: 0ms, widget: 162ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 415      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 315      | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 902      | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 37       | [renderer]                | -                                                           |
| init workspace service                                          | 56       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 660      | [renderer]                | -                                                           |
| restore viewlet                                                 | 26       | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 69       | [renderer]                | 1: workbench.editors.gettingStartedInput                    |
| overall workbench load                                          | 360      | [renderer]                | -                                                           |
| workbench ready                                                 | 6483     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 1347     | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 7233     | [renderer]                | -                                                           |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 6         | 0             | 17              | *                                                     | vscode.debug-auto-launch                |
| vscode.git                              | true  | 92        | 14            | 126             | *                                                     | vscode.github                           |
| vscode.github                           | true  | 16        | 0             | 0               | *                                                     | vscode.github                           |
| GitHub.vscode-pull-request-github       | true  | 141       | 3             | 0               | *                                                     | GitHub.vscode-pull-request-github       |
| vscode.configuration-editing            | false | 12        | 1             | 15              | onLanguage:jsonc                                      | vscode.configuration-editing            |
| vscode.emmet                            | false | 65        | 5             | 4               | onStartupFinished                                     | vscode.emmet                            |
| vscode.github-authentication            | false | 55        | 4             | 421             | onAuthenticationRequest:github                        | vscode.github-authentication            |
| vscode.json-language-features           | false | 145       | 10            | 18              | onLanguage:jsonc                                      | vscode.json-language-features           |
| vscode.merge-conflict                   | false | 9         | 1             | 3               | onStartupFinished                                     | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 42        | 8             | 475             | onAuthenticationRequest:microsoft                     | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 35        | 3             | 2               | onStartupFinished                                     | ms-vscode-remote.remote-wsl-recommender |
| ms-vscode.js-debug                      | false | 333       | 15            | 0               | onCommand:extension.js-debug.clearAutoAttachVariables | ms-vscode.js-debug                      |
| vscode.testing-editor-contributions     | false | 2         | 0             | 2               | onStartupFinished                                     | vscode.testing-editor-contributions     |
| vscode.typescript-language-features     | false | 116       | 5             | 14              | onLanguage:jsonc                                      | vscode.typescript-language-features     |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1625263943898	0	0
code/didStartMain	1625263944145	247	247
code/willStartCrashReporter	1625263944165	20	267
code/didStartCrashReporter	1625263944196	31	298
code/mainAppReady	1625263948565	4369	4667
code/willLoadMainBundle	1625263948569	4	4671
code/fork/willLoadCode	1625263948588	19	4690
code/registerFilesystem/file	1625263948726	138	4828
code/didLoadMainBundle	1625263948732	6	4834
code/willStartMainServer	1625263948747	15	4849
code/didStartMainServer	1625263948751	4	4853
code/willCreateCodeWindow	1625263948809	58	4911
code/willRestoreCodeWindowState	1625263948810	1	4912
code/didRestoreCodeWindowState	1625263948810	0	4912
code/willCreateCodeBrowserWindow	1625263948811	1	4913
code/didCreateCodeBrowserWindow	1625263948973	162	5075
code/didCreateCodeWindow	1625263948974	1	5076
code/willOpenNewWindow	1625263948980	6	5082
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1625263948981	0	0
code/didStartRenderer	1625263949281	300	300
code/willWaitForWindowConfig	1625263949282	1	301
code/didWaitForWindowConfig	1625263949282	0	301
code/willShowPartsSplash	1625263949282	0	301
code/didShowPartsSplash	1625263949284	2	303
code/willLoadWorkbenchMain	1625263949295	11	314
code/didLoadWorkbenchMain	1625263950197	902	1216
code/registerFilesystem/file	1625263950202	5	1221
code/registerFilesystem/vscode-userdata	1625263950202	0	1221
code/willInitWorkspaceService	1625263950207	5	1226
code/willInitStorage	1625263950208	1	1227
code/didInitStorage	1625263950245	37	1264
code/didInitWorkspaceService	1625263950263	18	1282
code/willStartWorkbench	1625263950268	5	1287
code/LifecyclePhase/Ready	1625263950271	3	1290
code/registerFilesystem/trustedDomains	1625263950388	117	1407
code/willRestoreEditors	1625263950558	170	1577
code/willRestoreViewlet	1625263950561	3	1580
code/didRestoreViewlet	1625263950587	26	1606
code/didRestoreEditors	1625263950627	40	1646
code/LifecyclePhase/Restored	1625263950628	1	1647
code/didStartWorkbench	1625263950628	0	1647
code/didRemovePartsSplash	1625263950628	0	1647
code/willConnectSharedProcess	1625263950662	34	1681
code/willLoadExtensions	1625263950718	56	1737
code/willHandleExtensionPoints	1625263951049	331	2068
code/didHandleExtensionPoints	1625263951368	319	2387
code/didLoadExtensions	1625263951378	10	2397
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1625263950967	0	0
code/fork/start	1625263951248	281	281
code/fork/willLoadCode	1625263951305	57	338
code/extHost/willConnectToRenderer	1625263952097	792	1130
code/extHost/didConnectToRenderer	1625263952098	1	1131
code/extHost/didWaitForInitData	1625263952284	186	1317
code/extHost/didCreateServices	1625263952295	11	1328
code/extHost/willWaitForConfig	1625263952299	4	1332
code/extHost/didWaitForConfig	1625263952355	56	1388
code/extHost/didInitAPI	1625263952359	4	1392
code/extHost/didInitProxyResolver	1625263952364	5	1397
code/extHost/ready	1625263952364	0	1397
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1625263952367	3	1400
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1625263952409	42	1442
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1625263952409	0	1442
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1625263952415	6	1448
code/extHost/willLoadExtensionCode/vscode.git	1625263952416	1	1449
code/extHost/didLoadExtensionCode/vscode.git	1625263952508	92	1541
code/extHost/willLoadExtensionCode/GitHub.vscode-pull-request-github	1625263952509	1	1542
code/extHost/didLoadExtensionCode/GitHub.vscode-pull-request-github	1625263952650	141	1683
code/extHost/willActivateExtension/vscode.microsoft-authentication	1625263952655	5	1688
code/extHost/willActivateExtension/vscode.debug-auto-launch	1625263952663	8	1696
code/extHost/willActivateExtension/vscode.git	1625263952663	0	1696
code/extHost/willActivateExtension/GitHub.vscode-pull-request-github	1625263952677	14	1710
code/extHost/didActivateExtension/vscode.debug-auto-launch	1625263952680	3	1713
code/extHost/didActivateExtension/GitHub.vscode-pull-request-github	1625263952680	0	1713
code/extHost/willLoadExtensionCode/vscode.github-authentication	1625263952704	24	1737
code/extHost/didLoadExtensionCode/vscode.github-authentication	1625263952758	54	1791
code/extHost/didActivateExtension/vscode.git	1625263952803	45	1836
code/extHost/willLoadExtensionCode/ms-vscode.js-debug	1625263952805	2	1838
code/extHost/didLoadExtensionCode/ms-vscode.js-debug	1625263953138	333	2171
code/extHost/willActivateExtension/vscode.github-authentication	1625263953138	0	2171
code/extHost/didActivateExtension/vscode.microsoft-authentication	1625263953147	9	2180
code/extHost/willLoadExtensionCode/vscode.github	1625263953194	47	2227
code/extHost/didLoadExtensionCode/vscode.github	1625263953210	16	2243
code/extHost/willActivateExtension/ms-vscode.js-debug	1625263953210	0	2243
code/extHost/didActivateExtension/ms-vscode.js-debug	1625263953225	15	2258
code/extHost/willActivateExtension/vscode.github	1625263953259	34	2292
code/extHost/didActivateExtension/vscode.github	1625263953260	1	2293
```

### cached data created (lazy, might need refreshes)

2.  :warning: Make sure to **attach** these files from your *home*-directory: :warning:
[prof-878f.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6757269/prof-878f.extHost.cpuprofile.txt)
[prof-878f.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6757270/prof-878f.main.cpuprofile.txt)
[prof-878f.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6757271/prof-878f.renderer.cpuprofile.txt)

**Comment by lnm451** [comment]
When I turn off Load startup items in msconfig, it become normally. I don't know why.

**Comment by jrieken** [comment]
This is due to a delayed app-ready event

**Comment by lnm451** [comment]
> This is due to a delayed app-ready event

Can you help me to fix it, I realized that it returns slow again

**Comment by lnm451** [comment]
I found out that because of Nahimic Service, it becomes normally after I end their tasks.

**Comment by landonth** [comment]
> I found out that because of Nahimic Service, it becomes normally after I end their tasks.

I also have this issue. Nahimic Service is enabled by default on many Asus computers, and other makes. Disabling a service manually is not really an acceptable and in my case it gets reenabled regularly by system updates. And it can't be uninstalled without also removing your onboard audio drivers. (manually extracting installing .inf drivers to work around this isn't a real solution either as aside from being super hacky and disables many features, it's impossible to unpack the inf files from many installers these days.) Very strange that it would cause this kind of interference though Nahimic Service is known to cause issues with other applications, e.g. it can cause SideFX Houdini to crash at random.

Even if there is nothing that can be done to eliminate this issue directly from the VScode developers (I have no idea if where the onus lies), it should be clearly documented as a possible issue (as it is in SideFX Houdini troubleshooting docs) and perhaps even a warning issued in vscode if the Nahimic Service is detected since it is so detrimental, it makes vscode nearly unusable as there is a 10 second delay with EVERY file opened, it's not just a delay of initial app startup which is bad enough.

This was also reported ~8 months ago in this issue https://github.com/microsoft/vscode/issues/113360

Very likely that this often goes unreported as it doesn't completely block VScode from working, it just gives the (very false) impression that VScode and/or the user's computer is a stinking hot unoptimized piece of garbage. So it's work looking into to try and remedy that false perception alone on every single Asus computer in existence and any others that have Nahimic bundle with their audio drivers. Again i'm not blaming VScode for this, it's more likely something nasty that Nahimic is doing but it is also puzzling why certain applications like VScode are somehow severely affected and interfered with while most others are not.

Cheers

**Comment by landonth** [comment]
> I found out that because of Nahimic Service, it becomes normally after I end their tasks.

Thanks, I have been having the same issue. I found this is being tracked under this github issue since 2017 if you would like to track progress 
https://github.com/microsoft/vscode/issues/22087
since disabling the service isn't really an acceptable solution, the service will get reenabled eventually automatically by any audio driver updates on many computers.

**Comment by douglasparker** [comment]
> This is due to a delayed app-ready event

Can this issue actually be addressed or are you going to just keep closing and locking issues?

**Comment by landonth** [comment]
> > This is due to a delayed app-ready event
> 
> Can this issue actually be addressed or are you going to just keep closing and locking issues?
> 
> Edit:
> 
> @lnm451 in this case you closed this issue. There are tons of them. Can we have this addressed so that it doesn't become a widespread issue. This audio driver comes preinstalled on a lot of prebuilt computers.

The main issue is #22087 and is still open. This wasn't mentioned specifically in this issue thread but i found it by searching issues for "nahimic" and it is the master issue for this (which is actually an issue between electron and nahimic.. which is why the vscode devs can't do anything to resolve it directly.) This is a duplicate issue and so it doesn't need to be open. It was closed by the issue reporter, anyway @lnm451 who is not a microsoft developer.

**Comment by douglasparker** [comment]
> > > This is due to a delayed app-ready event
> > 
> > Can this issue actually be addressed or are you going to just keep closing and locking issues?
> > 
> > Edit:
> > 
> > @lnm451 in this case you closed this issue. There are tons of them. Can we have this addressed so that it doesn't become a widespread issue. This audio driver comes preinstalled on a lot of prebuilt computers.
> 
> The master issue for this is #22087 and is still open, this issue here is a duplicate and has no purpose being open. Only problem is the master issue wasn't linked before it got closed so there you go. i found it by searching issues for "nahimic". It is actually an issue between electron and nahimic.. which is why the vscode devs can't do anything to resolve it directly. It was closed by the issue reporter, anyway @lnm451 who is not a microsoft developer. (neither am i)

Thank you for the clarification. I didn't realize this issue was closed by the issue reporter.

This is one of those things that took a lot of digging and I was having my issues closed by the VS Code team members despite trying to identify and resolve the issue.

It's pretty frustrating,  but thank you for the information. It'll be best to log this one with the guys working on Electron then.
