### ISSUE TITLE
Unable to write to Workspace Settings because command .. is not a registered configuration

### ISSUE THREAD

**Issue by AyuSharma-dev** [microsoft/vscode#127921]
I am trying to update StatusBar color in VScode Setting.json using the Configuration and Workspace. But when the code tries to update I am getting following error:

    Error: Unable to write to Workspace Settings because workbench.colorCustomizations.statusBar.background is not a registered configuration.

here is my code:
```
const conf = workspace.getConfiguration("workbench.colorCustomizations");
console.log('config-->'+JSON.stringify(conf));
await conf.update( "statusBar.background", "#00AA00");
```

On GetConfiguration I am getting the existing StatusBar color value but not able to Update it.

**Comment by roblourens** [comment]
You will need to do something like set the value of `workbench.colorCustomizations` to its current value plus your `statusBar.background` key added in
