### ISSUE TITLE
Intellisense menu very slow to open (.js files)

### ISSUE THREAD

**Issue by dancherb** [microsoft/vscode#127995]
Issue still occurs with all extensions disabled.

- VS Code Version: 1.57.1
- OS Version: Windows x64 10.0.17763

Steps to Reproduce:

1. ` code . --disable-extensions`
2. Open a .js file and begin typing the start of a snippet
3. Wait 500-5000+ ms
4. Intellisense menu opens with snippet suggested

**Comment by ArturoDent** [comment]
What is your `Editor: Quick Suggestions Delay` set to?  And does changing that value change the actual behaviour?

**Comment by dancherb** [comment]
> What is your `Editor: Quick Suggestions Delay` set to? And does changing that value change the actual behaviour?

Thanks for getting back - it's set to 0ms. Setting it upwards of 1000ms has a noticeable effect, as expected. The menu typically takes >1000ms to open so between 0-1000 does not really have an effect.

If I type the same snippet in succession, subsequent "intellisense menu opens" are pretty fast, as expected. But menu opens during standard coding, and the first "menu open" in a file, is very slow.

**Comment by dancherb** [comment]
I should also note this has been the case for quite a while, maybe several months - I've unsuccessfully tried to resolve it a number of times, though first time opening an issue here.

**Comment by longbuibao** [comment]
I'm facing the same problem for a while, and I set `Editor: Quick Suggestions Delay` to zero :'), disable all extension has no effect too
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic
```

**Comment by mjbvz** [comment]
Please share a file/project that causes this issue so we can investigate

**Comment by mathucate** [comment]
I've been struggling for a few days to this issue and eventually solved by downgrading the typescript version to 3.8.3!
(solution on issue #95200)
Anyway as far as I know, this issue is strongly relevent to tsserver.js, that is the vscode electron_node process running background, occupying more than 100% of cpu.

`npm install —save-dev typescript@3.8.3
`
```

// settings.json(workspace)
{
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```
command > Typescript: Select Typescript Version...

**Comment by longbuibao** [comment]
niceeeeeeeeeeeeeeeeeeeeeeeee thank you sir!

**Comment by dancherb** [comment]
@mathucate @longbuibao Does this fix apply to standard javascript projects? I tried it anyway and couldn't see an immediate difference

**Comment by longbuibao** [comment]
@dancherb so if you are working on a standard javascript projects, I think you have to install typescript globally by
`npm install -g typescript@3.8.3`
Find your location of `node_modules` folder [(here)](https://stackoverflow.com/questions/24830586/where-do-global-npm-packages-get-installed-on-ubuntu) and then in vscode, press ` Ctrl + , ` to open setting find `typescript.version`, click on `Edit in settings.json` and paste your `node_modules` path in 
````
{
  "typescript.tsdk": "some/path/to/node_modules/typescript/lib"
}

**Comment by dancherb** [comment]
Oooo... so far so good... thanks @longbuibao !!!

**Comment by mathucate** [comment]
I've just tested typescript@4.2 which performs quite well too, but v3.8.3 does the best i think
guess higher the version, getting heavier or something..
It seems to be a trade-off between using newer ts engine or enjoying fast popping suggestion tab, and i prefer the latter

**Comment by PeinZero** [comment]
Try disabling "TypeScript and JavaScript Language Features". It is Vs Code built in extension and disabling this fixed this issue for me.

1) Ctrl + Shift + P 
2) Type TypeScript 
3) Click "TypeScript: Open TS Server log"
4) At the bottom right, there will appear a notification. Click Setting icon on the notification and then manage extension.
5) Disable it.

**Comment by mjbvz** [comment]
Can someone please share a project that causes this

PS: Disabling the extension entirely will disable all language features for JS/TS

**Comment by PeinZero** [comment]
> Can someone please share a project that causes this
> 
> PS: Disabling the extension entirely will disable all language features for JS/TS

For me, in every .js file intellisense was slow. It showed suggestions after 3 4, that "usused variable warning" dissapear 3 4 seconds after the variable was used and so on. 

After disabling "TypeScript and JavaScript Language Features", everything is normal. and I don't see any difference. Plus it fixed the issue for me.

**Comment by mjbvz** [comment]
I'm closing this as we need more information to investigate. Please either share an example project or the full logs from when this happens
