### ISSUE TITLE
Suggestion Preview should preview snippets that have set a prefix that is not an actual prefix of the expanded snippet

### ISSUE THREAD

**Issue by CarlosAMendoza** [microsoft/vscode#127900]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.56.1 
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a custom javascript snippet
2. Set `"editor.suggest.preview": true` in settings
3. Open JS file, type `for` and hit ctrl+space and use arrows to find the for snippet, a preview should be shown.
4. In new line type the prefix of your snippet and use arrow keys to preview it. No preview occurs

I have already tested this on multiple computers, and on a clean insider build. No extensions or custom snippets show preview, yet I am able to modify the built in snippets in the program files and when I reload the page and test them they do work.

**Comment by hediet** [comment]
Can you post your snippet? The prefix of the snippet really must be a prefix of the body, otherwise the preview cannot be shown!

**Comment by CarlosAMendoza** [comment]
Why does it work like this? That doesn't seem very helpful at all. Just as an example let's use this snippet 

```json
{
    "prefix": ["export","fc", "reactFunction"],
    "body": [
      "export interface ${1:App}Props {",
      "",
      "}",
      "",
      "export const ${1:App}: React.FC<${1:App}Props> = ({}) => {",
      "    return (",
			"      <div>",
			"        ${2:}",
			"      </div>",
			"    );",
      "}"
    ],
    "description": "Some snippet"
}
```

When in the editor and I type `export` the snippet above will show preview for the snippet, but if I type any of the prefixes that are actually useful and convenient then it wont work. This does not seem very useful at all.

This is particularly a problem when it comes to snippet extensions, I have many installed and sometimes I want to preview what the snippet is before using it. Some have similar prefixes and being able to preview a snippet should not be determined based on the body starting with the prefix.

**Comment by hediet** [comment]
> This does not seem very useful at all.

I understand that it is not useful in this particular case.

But what should the editor do when the text you typed cannot be made part of the preview, as it is not a prefix or even a substring/subword (which you can enable with `previewMode: subword` in tomorrows insider)? Should the typed text be hidden? That would be very confusing if you do not intend to select that snippet.

If you are passionate about it, I would love to see a mock screenshot of what you would like to see as preview when typing `reactFunction` in your example. What would you do with the typed text `reactFunction`?

**Comment by CarlosAMendoza** [comment]
I haven't looked into how the preview or snippets work but I assumed that the "prefix" property acted more like a keyword for the intellisense. As in when I type `fc` in the editor the intellisense has that selected and the preview shows up. At least that is how every snippet extension treats it. As an example [this extension](https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/master/snippets/ts-snippets.json) uses `tsrcc` and `tsrce` for two snippets that are very similar but still different enough that I would like to preview to know which one I want to use.

An example of intellisense showing the selected preview is this
![Screenshot 2021-07-08 165208](https://user-images.githubusercontent.com/8264470/124990354-419e7600-e00e-11eb-9b01-16cf55417dfb.png)
![Screenshot 2021-07-08 165239](https://user-images.githubusercontent.com/8264470/124990359-4400d000-e00e-11eb-98da-009f141f5a75.png)

Two completely different previews that were detected as possibilities by the intellisense.

**Comment by CarlosAMendoza** [comment]
I just tested the `previewMode: subword` in the insider build and while does not work with `prefix`'s that aren't in the body, it has the functionality that I was looking for in my case and solved my problem. Thank you @hediet

**Comment by hediet** [comment]
> An example of intellisense showing the selected preview is this

I'm very well aware how it looks in these cases where the prefix is an actual prefix of the snippet, I was much more interested in what you think it should look like if the prefix does not appear in the extended snippet (such as `reactFunction`).

> previewMode: subwordDiff

In todays insider build it should be `previewMode: subword` now, I changed it yesterday.
