### ISSUE TITLE
Vs code very slow

### ISSUE THREAD

**Issue by Mahmoud6901** [microsoft/vscode#127913]
Issue Type: <b>Performance Issue</b>

Vscode is very slow, this issue happens when I try write code and when I use android studio emulator.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (22.86GB free)|
|Process Argv|--crash-reporter-id 0f112d45-68ce-4846-80df-9df376e91241|
|Screen Reader|no|
|VM|67%|

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.24.0
flutter|Dar|3.24.0
githistory|don|0.6.16
gitlens|eam|11.5.1
vscode-pull-request-github|Git|0.27.1
vscode-gutter-preview|kis|0.27.1
remote-wsl|ms-|0.56.5
awesome-flutter-snippets|Nas|3.0.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0

(1 theme extensions excluded)

**Comment by Mahmoud6901** [comment]
also, there is a lag when I scroll up or down.

**Comment by gjsjohnmurray** [comment]
Maybe caused by one of your extensions. Please use the Start Extension Bisect command to investigate.
