### ISSUE TITLE
Output appears in "Debug Console" when I select "Run without Debugbing"

### ISSUE THREAD

**Issue by drewbyh** [microsoft/vscode#127906]
Issue Type: <b>Bug</b>

Output appears in "Debug Console" even when I select "Run without Debugbing"

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.00GB free)|
|Process Argv|--crash-reporter-id 01de8043-fc10-4ba8-bdc3-c006ecf584ad|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5

</details>

**Comment by weinand** [comment]
Yes, that's by design.
"Run without Debugging" is implemented as "Run with Debugging" but breakpoints and other debugger features are turned off.
