### ISSUE TITLE
multiple grammars for the same language

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#127917]
Does this issue occur when all extensions are disabled?: N/A. It is an issue with the VSCode API

There are a few languages (within the set of extensions that ship with VSCode by default) that define multiple grammars (with different `scopeName`) for the same `languageId`. Examples include the `cpp` and `php` extensions.

https://github.com/microsoft/vscode/blob/3718ef05565efeb27e7ee29e50ee77fc82458bb0/extensions/cpp/package.json#L72-L81

https://github.com/microsoft/vscode/blob/3718ef05565efeb27e7ee29e50ee77fc82458bb0/extensions/php/package.json#L34-L42

In this case, it is not clear which grammar file would win. I could not find any errors/warnings related to it either.
For example, if a document is matched to the `cpp` language (based on uri extension), which `scopeName` would be used to colorize?

* Is it by precedence? doesn't look like it, as the two examples are in different order.
* Is it a different logic? does the matching to a specific scope name happen via a different look up?
* Is it a bug? happy to help fix, but would love to confirm that is the case first.

**Comment by alexr00** [comment]
> Is it a different logic? does the matching to a specific scope name happen via a different look up?

My understanding is that this is that the matching happens via a different lookup. Example:

For php files VS Code sets the scope to be `source.php`. This is probably what you would expect. 
In HTML files, the HTML grammar has some places where it sets the scope to `text.html.php`.
