### ISSUE TITLE
Can't install python extension from marketplace

### ISSUE THREAD

**Issue by HNSWeb** [microsoft/vscode#127937]
So i was trying to install the offical Python extension, but it wouldn't download and so i went in the logs to find this error message
`[renderer1] [error] Error: Unable to read file 'd:\Program' (Error: Unable to resolve non-existing file 'd:\Program')`
the actual name should be `'d:\Program files\...'` (the lowercase letter since i used regedit to solve some memory issues)
so basically it seems that the whole system doesn't understand spaces or something

Steps to reproduce:
1. Set a new regedit for program files as "Program files" (Might not be needed).
2. Attempt to download **ms-python.python**.
3.1.(Actual Result) Het a simmilar or the same error.
3.2.(Expected Result) Succesfully download the Extension.

_PS: I tried downloading manually but that doesn't even give an error message_

**Comment by CodeCrazy-ywt** [comment]
@vscode-triage-bot please look into this. This issue has made the python development very difficult.

**Comment by sandy081** [comment]
- Are you seeing any error notification? 
- What is it being shown in the application when you try to install? 
- Is it happening only for Python or for other extensions too? 
- Can you please provide the complete following logs while you try to reproduce the issue?
  - View -> Open View… -> Log (Shared)
  - View -> Open View… -> Log (Window)
