### ISSUE TITLE
nyc test coverage reporter not work with vscode-test mocha

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#127980]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version: WIndows_NT x64 10.0.19043

Steps to Reproduce:

1. Use the vscode provided example 'helloworld-test-sample' to test
2. in package.json, add "coverage": "nyc npm run test" 
3. run the commnad line 'npm run coverage' then the test runner file 'runTest.ts' is tested instead of real test file 'extension.test.ts'
![image](https://user-images.githubusercontent.com/73154171/124431303-c6855780-dda2-11eb-97db-625d3357d0b0.png)

**Comment by HuihuiWu-Microsoft** [comment]
I've seen a similar bug reported but closed without conclusion https://github.com/microsoft/vscode/issues/106977

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-test/issues/32. This is not expected to work, since nyc only instruments node.js files and extension tests run inside Electron.
