### ISSUE TITLE
make it possible to create developing profiles

### ISSUE THREAD

**Issue by mostafaElspagh0** [microsoft/vscode#127974]
when I do front end I don't need all the installed extensions I need only subset of them and the remaining extensions is still running consuming resources 
and the same when I do something Like java development I don't need extension like "vetur" at that time    
I know it is possible to edit settings for work space 
but it is boring to copy the same settings for every front end work space it would be much easier if there is an option to apply a predefined profile

**Comment by ArturoDent** [comment]
Probable duplicate: https://github.com/microsoft/vscode/issues/116740
