### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by sourabpramanik** [microsoft/vscode#127999]
Issue Type: <b>Bug</b>

dsaddssa

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|3.31GB (0.10GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id a0ebbffb-a2a5-4d51-b68b-fbb6c93f9bc1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.6
vscode-edit-csv|jan|0.6.0
vscode-styled-components|jpo|1.6.4
solidity|Jua|0.0.124
python|ms-|2021.6.944021595
java|red|0.80.0
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by LohitakshTrehan** [comment]
@sourabpramanik 
Please mention the details of the issue you are posting, this is of no help.
