### ISSUE TITLE
move file folder to the top position

### ISSUE THREAD

**Issue by Frozenlove** [microsoft/vscode#127941]
Issue Type: <b>Feature Request</b>

In an item,there are too many file folders.Some of them is very important. I think if I can move them to the top position, it is easily to find them.
In the same level, adjusting the file folders' position by ourselves is what we want.
Please consider it.Thanks.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks
