### ISSUE TITLE
Assign unique/random color/icon to terminal tab on creation

### ISSUE THREAD

**Issue by kaminskypavel** [microsoft/vscode#127951]
Issue Type: <b>Feature Request</b>

since seeing a tree list of "bash" terminal with the same icon and color isn't very productive, a settings flag such as "terminal.newTabColor" or something alike with possible options such as {"default","random","none"} would be really great!
Also please consider similar feature for "terminal.newTabIcon" .

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

![image](https://user-images.githubusercontent.com/4253088/124385373-e69f1300-dcdd-11eb-99f4-a121f52c1eac.png)

**Comment by Tyriar** [comment]
We considering this:

```
terminal.integrated.tabs.newTabColor: 'unique' | 'default';
terminal.integrated.tabs.newTabIcon: 'unique' | default';
```

Which would set the color and/or icon when they are unset only, if a profile has an icon set you would need to redefine the profile to get this feature. Unique describes the feature a little better than random as we'd want to avoid conflicts.

The issue here is that then it becomes a question of which profiles this is overriding, some may be detrimental like the JS Debug Terminal or tasks which already have unique/descriptive icons and replacing that with something random would be bad. I think this feature is probably more targeted for the default profile to help distinguish n bash/zsh/pwsh terminals like the OP's example. As such let's add it to the profile itself, so you would redefine your default profile if you wanted to use it, something like:

```json
  "terminal.integrated.profiles.osx": {
    "bash": {
      "path": "bash",
      "icon": "unique",
      "color": "unique"
    }
  }
```

**Comment by carlocardella** [comment]
@Tyriar, could it be added to other user defined profiles? For example I use this but if I start two "Powershell Preview" terminals they will both appear identical: 

```json
"terminal.integrated.profiles.windows": {
        "Powershell Preview": {
            "path": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
            "color": "terminal.ansiMagenta"
        },
        "Powershell": {
            "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "color": "terminal.ansiMagenta"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash",
            "icon": "git-branch",
            "overrideName": true,
            "color": "terminal.ansiRed"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "color": "terminal.ansiBlue"
        },
        "Python": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/C", "python"],
            "icon": "repl",
            "overrideName": true,
            "color": "terminal.ansiYellow"
        }
    },
```

**Comment by Tyriar** [comment]
@carlocardella yes the thinking is that you could add `"color": "unique"` to any of them and it would do something like get an unused color (maybe excluding white/black for contrast reasons) if a color is available, otherwise a random one if the 6 colors are already used.

**Comment by Tyriar** [comment]
After some more thought from the team, this is probably something that an extension should be doing similar to the [Peacock extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock). Assigned https://github.com/microsoft/vscode/issues/127573 and https://github.com/microsoft/vscode/issues/128228 to July which would be needed for extensions to be able to do this.

**Comment by meganrogge** [comment]
Moved to August since the API finalization of #128228 will happen then

**Comment by meganrogge** [comment]
closing as an extension could do it
