### ISSUE TITLE
How does a user know what settings are overridden by an extension?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12799]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12614

Steps to Reproduce:

1. Set `"terminal.integrated.cursorBlinking": true` in your settings.json
2. Run an extension containing:
  
  ```ts
  vscode.workspace.getConfiguration()
    .update('terminal.integrated.cursorBlinking', false, false);
  ```

3. Try to figure out why `"terminal.integrated.cursorBlinking": true` is not working
4. File a bug to Microsoft/vscode

**Comment by Tyriar** [comment]
I realized shortly after this that it's in `./.vscode/settings.json`, not local storage. Most users will be unaware of this though, don't we owe users some warning before an extension goes and messes with their settings files?

I was expecting the changes to be stored elsewhere, perhaps with a warning annotation within the settings.json file indicating that an extension has overridden an extension. If I were a normal user without my settings.json source controlled and symlinked to I would be very irritated if an extension messed with it. Especially if I then uninstalled the extension and it didn't revert the change.

**Comment by Tyriar** [comment]
I realize this would be a complete change in how it's handled but I think a model like this is worth consideration for the future to protect settings and make sure installing and then uninstalling an extension doesn't change the way that the editor behaves.

**Comment by bpasero** [comment]
@Tyriar isn't this covered in https://github.com/Microsoft/vscode/issues/10583

**Comment by Tyriar** [comment]
@bpasero that only cares about the extension author perspective doesn't it, not surfacing the information to the user?

**Comment by bpasero** [comment]
@Tyriar ok I see what you mean. there is no information, it is up to an extension to decide if a message should be shown or not. in the end this is just API to write to the settings file.

**Comment by jrieken** [comment]
dup of #10583
