### ISSUE TITLE
Saving dirty editors is taking longer than expected...

### ISSUE THREAD

**Issue by SebghatYusuf** [microsoft/vscode#127949]
Issue Type: <b>Bug</b>

1 - Open a Flutter Project in VS Code
2- Bring some changes to the code.
3- Save the file. 
4- Try to exit the VS Code. 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:50.042Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.88GB free)|
|Process Argv|. --disable-extensions --crash-reporter-id 4634ab9c-90d7-4baa-864c-2a02be55b547|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30322307
binariesv615:30325510
vsccppwtct:30329789
aatestflightcf:30331712
bridge0702cf:30333156

```

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SebghatYusuf** [comment]
@bpasero, yeah I think it's for the Dart extension I'm using, I've opened and issue on their repository, I just wanted to make sure the issue is only from the extension.

**Comment by philipacrowe** [comment]
@SebghatYusuf  can you post the link to the dart issue, im experiencing the same bug. taking forever to save a file.

**Comment by SebghatYusuf** [comment]
Hi @philipacrowe, 
Sure here is the link to dart issue. 
https://github.com/Dart-Code/Dart-Code/issues/3460

**Comment by iplaksiy** [comment]
I’m running into this issue as well, however, mine is a bit stranger. I run a few terminal instances while building (Angular CLI, Concurrently - like ng serve but for Firebase Functions, and the Firebase Emulator Suite). Every once in a while, when coming back from an extended period of time and after a few minutes of development, my system clock (macOS - Catalina) resets 7hrs back and the  terminal instances freeze. Changes to files are not recognized and upon closing VS Code I get the same message and then VS Code freezes. Is it possible that VS Code is resetting the system clock (and possibly dumping memory?) or is it more likely that there’s something else going on with my machine and VS Code is simply reacting to the sudden change(s)? All other applications running during this time continue running normally. Even while VS Code is frozen. 

Any ideas?
