### ISSUE TITLE
Revisit Pie Menus

### ISSUE THREAD

**Issue by TheRealSyler** [microsoft/vscode#127931]
related to #76017,  #70074 and maybe also #3969;

I think pie menus are great and they could be really useful in vscode, im not 100% sure that they work well with vscode but i think its worth trying it out, i made a [feature branch in my fork](https://github.com/TheRealSyler/vscode/tree/pie-menu), but before i put more effort into it, i thought i should open another issue.

i would be willing to implement and maintain the whole thing.

here is an example for changing the current file.
![giphy](https://user-images.githubusercontent.com/46901787/124361842-95d1e080-dc31-11eb-88c6-582d56073475.gif)
Here is a never version with three different themes.
![Untitled](https://user-images.githubusercontent.com/46901787/124363330-e568da00-dc3a-11eb-8aaa-cf842349166e.png)
Here is an even newer version.
![Untitled](https://user-images.githubusercontent.com/46901787/124388755-89f32680-dce4-11eb-9666-ab5a6975c999.png)
if you want to try it out just download the [`pie-menu`](https://github.com/TheRealSyler/vscode/tree/pie-menu) branch of my fork and press `Ctrl+Shift+D` after opening a couple of windows.

**Comment by sbatten** [comment]
Hi @TheRealSyler! Thanks for the issue and the idea is pretty interesting, but I do not believe our priorities around this have changed and thus I'm sorry to have to close this again as out of scope.

**Comment by TheRealSyler** [comment]
@sbatten i agree that this should be in an extension rather than as a core part of vscode, i thought that it can't be done using an extension but yesterday i found out that i can probably make an extension that injects js in vscode with a little bit of hacking.
