### ISSUE TITLE
Include all linux required Microsoft packages in the repository.

### ISSUE THREAD

**Issue by jim255** [microsoft/vscode#127924]
Issue Type: <b>Feature Request</b>

In the future , please Include all linux required Microsoft packages for remote debugging in the repositories locted at,
packages.microsoft.com/repos/code stable/main armhf
packages.microsoft.com/repos/code stable/main amd64
packages.microsoft.com/repos/code stable/main arm64

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No
Remote OS version: Linux arm 4.19.94-ti-r64

**Comment by weinand** [comment]
I don't understand - please explain.

**Comment by jim255** [comment]
I just find it so, Microsoft vs. Linux, when most of the code to use a Microsoft application in a Linux workflow isn't obtainable from a Microsoft repository. Not only that but it's so well scattered around the internet. I STILL haven't got a simple FLASH_LED.C program to compile and run on my target..I've been involved in developing literally every aspect of embedded devices for over 35 years. In my honest, professional opinion is the worst development environment I've ever seen!
Frustration!!

**Comment by joaomoreno** [comment]
> my honest, professional opinion is the worst development environment I've ever seen!

Ufff, a bit harsh.

Is this related to debugging C/C++?

**Comment by jim255** [comment]
Yes, I honesty expected more from the Microsoft brand. I've been writing embedded system code in the C language since the early 1980'sand this is the worst IDE I've experienced. I was asked by my employer to "Upgrade" the working IDE we were using, with vscode, which out of the box, can not compile a simple "flash_LED.c" application and run it on the embedded arm target it is configured to work with..OUT OF THE BOX!

    On Wednesday, July 7, 2021, 02:58:23 AM EDT, João Moreno ***@***.***> wrote:  
 
 



my honest, professional opinion is the worst development environment I've ever seen!


Ufff, a bit harsh.

Is this related to debugging C/C++?
