### ISSUE TITLE
No where to log into Account

### ISSUE THREAD

**Issue by drewbyh** [microsoft/vscode#127905]
Issue Type: <b>Bug</b>

I click on Account to login but it just says I'm not logged in and there is no login option.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.13GB free)|
|Process Argv|--crash-reporter-id 01de8043-fc10-4ba8-bdc3-c006ecf584ad|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-wsl|ms-|0.56.5

</details>

**Comment by jackchoumine** [comment]
> /gifPlease

Hello，after I login github account, but now I wannn change it to Mircosoft account, I can not do this. Could give any advise?

**Comment by TylerLeonhardt** [comment]
@jackchoumine I think you opened an issue recently right? With this exact question. Can you link me to that and I'll answer there?
