### ISSUE TITLE
Also define the standard property 'background-clip' for compatibilitycss(vendorPrefix)

### ISSUE THREAD

**Issue by wspf0824** [microsoft/vscode#127972]
Issue Type: <b>Bug</b>

When I write CSS code visual studio code editor shows me this

Also define the standard property 'background-clip' for compatibilitycss(vendorPrefix)

How can I fix it or at least ignore the warning on VSCode?
```
.form p a:hover {
  background-color: #000;
  background-image: linear-gradient(to right, #434343 0%, black 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.16GB free)|
|Process Argv|--crash-reporter-id 627f9c61-db42-450d-ad55-773d0c71063e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
php-debug|fel|1.16.1
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
vue|jcb|0.1.5
php-cs-fixer|jun|0.2.2
vscode-view-in-browser|kop|1.0.5
vscode-language-pack-zh-hans|MS-|1.57.1
debugger-for-chrome|msj|4.12.12
vscode-icons|vsc|11.5.0
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by aeschli** [comment]
Can you not add a property `background-clip, as suggested?

If you want to disable the vendorPrefix linting, set
`"css.lint.vendorPrefix": "ignore"`
