### ISSUE TITLE
Intellisence does not work on remote Python interpreter

### ISSUE THREAD

**Issue by alexbogun** [microsoft/vscode#127923]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Window 1019042.1052 -> remote to Ubuntu 18.04

Issue: Intellisence does not work on remote Python interpreter

Steps to Reproduce:

1. connect to remote VSCode host via remote ssh
2. create Python file "script.py"
3. type "import numpy"
4. type "numpy."
5. press ctrl+space
6 Intellisence not working ("Loading..." appears forever)

This issue does not happen if working on the local machine
I have tried all Python language servers with the same result

**Comment by alexbogun** [comment]
Not sure what that was, but fully removing .vscode-server from the host has solved it.
By the way "Remote-SSH: Uninstall VS Code Server from Host..." did not do anything for me, I had to manually delete the ~/.vscode-server directory and reboot the host

**Comment by alexbogun** [comment]
Unfortunately, the issue is back, any tips on how I can try to identify the root cause? Thanks in advance!

**Comment by alexeyr** [comment]
Might be the same as #127745?
