### ISSUE TITLE
[Bug] Terminal find widget can't be hidden under a certain circumstance

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#127922]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Focus integrated terminal.
2. Trigger `workbench.action.terminal.toggleFindRegex`, now this will show up:

   ![image](https://user-images.githubusercontent.com/28700378/124355155-58298380-dc42-11eb-8158-a73e4dbfc868.png)

3. Trigger `workbench.action.terminal.hideFind`.
4. Terminal find widget can't be hidden.
5. Change `workbench.action.terminal.hideFind` `when` from `terminalFindVisible && terminalFocus && terminalProcessSupported` to `terminalFocus && terminalProcessSupported`.
6. Repeat step 1 to step 4.
7. Terminal find widget will be hidden.

**Comment by Tyriar** [comment]
Looks like the `terminalFindVisible` context key might only be set initially when focused?
