### ISSUE TITLE
[Test API] ability to configure/communicate with explorer toolbar 

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#127964]
Currently, the Test Explorer has a toolbar with a few buttons like `run all tests`, `debug all tests`, `turn on/off auto run` that are not configurable by the API. 

We have use cases that used external watcher (e.g. `jest --watch`) to monitor and run tests, therefore would prefer not to trigger any manual run via the explorer. While I can turn off the "runnable" for the test items, there didn't seem to have a way to disable these buttons from the test API. 

Furthermore, while I can guess the run/debug all tests in the runTest handler, there is no way to know that the user has turned on the auto-run since all we get is the same request as "run all tests"...

**Comment by connor4312** [comment]
> While I can turn off the "runnable" for the test items, there didn't seem to have a way to disable these buttons from the test API.

I will track this as part of https://github.com/microsoft/vscode/issues/127096#issuecomment-868839093

> Furthermore, while I can guess the run/debug all tests in the runTest handler, there is no way to know that the user has turned on the auto-run since all we get is the same request as

Yea, this is a sore spot. I've come back to thinking that extensions should implement auto run themselves (this is different than what's done in the Test Explorer UI extension). Let's merge discussion into that issue

/duplicate
