### ISSUE TITLE
Bring back the split terminal button.

### ISSUE THREAD

**Issue by mastazi** [microsoft/vscode#127975]
In the previous built-in terminal UI, there was a "split terminal" button, in this area (see red rectangle):

![2021-07-05 14_24_45-e6Api ts - karta-firebase (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/1661655/124417651-f3cf0700-dd9c-11eb-960c-7a6c58272549.png)

This is the old UI for comparison, you can see where the "split terminal" button used to be (see red arrow):

![2021-07-05 14_43_00-QNywUcWxBR mp4 - VLC media player](https://user-images.githubusercontent.com/1661655/124418759-8c668680-dd9f-11eb-903b-433dba42712f.png)

Currently, the split terminal button is gone when I have only one terminal open, and it is only visible on hover if I have multiple terminals:

![2021-07-05 14_27_13-e6Api ts - karta-firebase (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/1661655/124417771-3d1f5680-dd9d-11eb-9656-1d5c66332f31.png)

The only way to see the split terminal button when I have only one terminal, is to first hold `Alt`, and then hover the name of the terminal (in my case `pwsh`), then the button will be visible. So two steps are required before you can see the button, this means that the button is hard to access.

Why is the button easier to access when I have multiple terminals open (no need to press Alt), but harder to access when I have just one terminal open? I would prefer if the button would be more accessible, as it used to be in the old UI.

Let me also say that I really like all the other features of the new built-in terminal UI, I just dislike this particular detail.

**Comment by gjsjohnmurray** [comment]
Are you using 1.57.1 (Stable)? If so, I suggest you try Insiders, or wait until 1.58 ships (probably later this week).

**Comment by mastazi** [comment]
Thank you @gjsjohnmurray I just saw that @Tyriar added the button back. I will wait for 1.58! Closing the issue now.
