### ISSUE TITLE
VS Code stalling overnight (Julia REPL pane)

### ISSUE THREAD

**Issue by bardo84** [microsoft/vscode#127947]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Win 10

Steps to Reproduce:

1. Start VS Code with Julia
2. The next morning the REPL pane is frozen, empty with a cursor in the middle. 
See also [https://discourse.julialang.org/t/repl-in-vs-code-stalling-overnight/63976](url)

**Comment by weinand** [comment]
Please file against Julia extension.
