### ISSUE TITLE
오류 문제 

### ISSUE THREAD

**Issue by jangminju** [microsoft/vscode#127976]
no authentication provider 'github' is currently registered

라고 뜨면서 깃허브와 연결이 안됩니다.
아무리 검색해도 모르겠는데..
어떻게 해야할까요?

**Comment by CodeCrazy-ywt** [comment]
**A possible translation:**
I cannot connect to github.
However I search, I cannot find.
What should I do?

**Comment by joaomoreno** [comment]
@jangminju Can you show me a screenshot of the error?
