### ISSUE TITLE
It is going slow

### ISSUE THREAD

**Issue by Hasan50** [microsoft/vscode#127957]
We have written the n
Issue Type: <b>Performance Issue</b>

It is too slow vs code then android studio. I have use some extension for react only not fancy. When working with this going crazy.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.77GB (0.38GB free)|
|Process Argv|--crash-reporter-id c1143ae8-aa03-48f2-8dda-7aa02b07aa2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    45	 10488	code main
    2	    28	  2748	   window (Issue Reporter)
    0	     0	  9784	   crashpad-handler
    0	   132	 11076	   window (user-invitation.component.html - bd-hot-deals-user-portal - Visual Studio Code)
    0	    10	  2108	     extensionHost
    0	     5	   976	       electron_node serverMain.js 
    0	     0	  2412	       electron_node tsserver.js 
    0	     2	  4300	       "C:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=2108
    0	     6	  5432	       electron_node server.js 
    0	    17	  6884	       "C:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\Hasan\.vscode\extensions\angular.ng-template-12.1.1\server --logToConsole --ngProbeLocations c:\Users\Hasan\.vscode\extensions\angular.ng-template-12.1.1,d:\BdHotDeals\bd-hot-deals-user-portal --tsProbeLocations c:\Users\Hasan\.vscode\extensions\angular.ng-template-12.1.1,d:\BdHotDeals\bd-hot-deals-user-portal --node-ipc --clientProcessId=2108
    0	     7	  8420	       "C:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2108
    0	     8	 10580	       electron_node tsserver.js 
    0	     0	  1184	         electron_node typingsInstaller.js typesMap.js 
    0	     5	 10980	       "C:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Hasan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=2108
    0	     3	  9084	     watcherService 
    0	     0	  2608	       console-window-host (Windows internal process)
    0	     1	 14180	     searchService
    0	   144	 15152	   gpu-process
    0	     7	 15512	   utility
    5	    30	 16228	   shared-process
    0	     7	 15532	     ptyHost
    0	     0	  3692	       console-window-host (Windows internal process)
    0	     1	  7164	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (user-invitation.component.html - bd-hot-deals-user-portal - Visual Studio Code)
|    Folder (bd-hot-deals-user-portal): 1581 files
|      File types: ts(500) scss(348) jpg(200) html(138) png(59) json(17)
|                  js(17) ico(4) css(4) svg(4)
|      Conf files: tsconfig.json(2) tslint.json(2) package.json(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.1.1
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|8.0.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
react-native-snippet|jun|0.5.6
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
color-highlight|nau|2.3.0
laravel5-snippets|one|1.12.0
typescript-hero|rbb|3.0.0
react-redux-es6-snippets|tim|2.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30322307
binariesv615:30325510
vsccppwt:30329788
aatestflight:30331711
bridge0702cf:30333156

```

</details>

eeded data into your clipboard because it was too large to send. Please paste.

**Comment by Hasan50** [comment]
when open vs code it kills my 95% mamory

**Comment by Nihal247** [comment]
Hi @Hasan50 and thank you for your patience.

Visual Studio Code is a memory-hungry program, in my case also it takes more memory than I expect. As it's a performance issue, a better approach would be to end the unnecessary background processes.

Alternatively you can fully disable the background apps by navigationg to **Settings**<**Privacy**<**Background Apps** for better performance.

Thank you in advance.

**Comment by mhatvan** [comment]
I am working in a monorepo and the memory usage is around 40-50%...

**Comment by mjbvz** [comment]
Closing as not actionable without more information from the original poster
