### ISSUE TITLE
Restart debug task doesn't close previous externalTerminal

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12793]
Bug found while testing #12252
- VSCode Version: 1.6 Insider
- OS Version: Ubuntu 16.04

**Comment by isidorn** [comment]
debug adapter should close the externalTerminal on any debug session end including restart.
@octref does the externalTerminal close when you just stop the debug session or you only see this when you restart?

**Comment by octref** [comment]
> does the externalTerminal close when you just stop the debug session

It doesn't close. When you end debug session, it only prints out some info on externalTerminal but doesn't close it until you press a key.

![image](https://cloud.githubusercontent.com/assets/4033249/18935076/8ab148bc-8592-11e6-9082-b15ccd6e1bc1.png)

Launch Debug -> Restart -> Restart:

![screenshot from 2016-09-28 15-42-03](https://cloud.githubusercontent.com/assets/4033249/18935042/3b124306-8592-11e6-81ae-cfdc81009a47.png)

On Mac, it just ends the process but terminal.app is still open:

Launch Debug -> Stop:

![image](https://cloud.githubusercontent.com/assets/4033249/18935123/d689c1ec-8592-11e6-8e1a-65c25f99587e.png)

However, restart ends the process in the current terminal and spawn a new one, instead of creating another terminal:

Launch Debug -> Restart -> Restart:

![image](https://cloud.githubusercontent.com/assets/4033249/18935152/0da5eeb2-8593-11e6-82aa-6d1303856c0c.png)

**Comment by octref** [comment]
Does not repro in latest anymore.
