### ISSUE TITLE
Can't install extension on WSL

### ISSUE THREAD

**Issue by TrafalgarRicardoLu** [microsoft/vscode#127970]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: windows10

Steps to Reproduce:
I just click "install in WSL", and it doesn't work. That's my log.

[renderer1] [error] Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
    at Object.o [as mnemonicMenuLabel] (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:37299)
    at x.<anonymous> (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3884)
    at n.fire (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1855)
    at L.runner (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:662:6717)
    at L.doRun (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:17772)
    at L.onTimeout (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:17738)

**Comment by sandy081** [comment]
Can you please provide following logs completely while you see this issue? 

- Log (Window)
- Log (Remote)

Can you also please explain more about it does not work? Do you see any error pop up or it just stuck installing? It would be great if you can share a screenshot or video.

**Comment by TrafalgarRicardoLu** [comment]
Log(Window):

> [2021-07-07 10:41:20.604] [renderer1] [error] Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
>     at Object.o [as mnemonicMenuLabel] (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:75:37299)
>     at x.<anonymous> (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1926:3884)
>     at n.fire (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1855)
>     at L.runner (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:662:6717)
>     at L.doRun (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:17772)
>     at L.onTimeout (file:///C:/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:17738)

Log(Remote):

> [2021-07-07 10:41:18.506] [remoteagent] [info] 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> [2021-07-07 10:41:18.506] [remoteagent] [info] Extension host agent started.
> [2021-07-07 10:41:18.785] [remoteagent] [info] [::1][ffbf44c2][ManagementConnection] New connection established.
> [2021-07-07 10:41:18.786] [remoteagent] [info] [::1][b8829ca3][ExtensionHostConnection] New connection established.
> [2021-07-07 10:41:19.521] [remoteagent] [info] [::1][b8829ca3][ExtensionHostConnection] <75> Launched Extension Host Process.
> [2021-07-07 10:41:32.659] [remoteagent] [info] [::1][ffbf44c2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
> [2021-07-07 10:41:33.675] [remoteagent] [info] [::1][b8829ca3][ExtensionHostConnection] <75> Extension Host Process exited with code: 0, signal: null.
> [2021-07-07 10:41:33.675] [remoteagent] [info] Last EH closed, waiting before shutting down
> [2021-07-07 10:41:34.991] [remoteagent] [info] [::1][35aa1b4c][ManagementConnection] New connection established.
> [2021-07-07 10:41:35.081] [remoteagent] [info] [::1][e43fbdac][ExtensionHostConnection] New connection established.
> [2021-07-07 10:41:35.094] [remoteagent] [info] [::1][e43fbdac][ExtensionHostConnection] <108> Launched Extension Host Process.
> [2021-07-07 10:41:56.825] [remoteagent] [info] *
> [2021-07-07 10:41:56.830] [remoteagent] [info] baseEnv {"USER":"trafalgar","VSCODE_WSL_EXT_LOCATION":"/mnt/c/Users/Trafalgar Ricardo Lu/.vscode/extensions/ms-vscode-remote.remote-wsl-0.56.5","SHLVL":"0","HOME":"/home/trafalgar","WSL_DISTRO_NAME":"Ubuntu-20.04","LOGNAME":"trafalgar","NAME":"DESKTOP-RCK12UB","WSL_INTEROP":"/run/WSL/15_interop","_":"/home/trafalgar/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/node","TERM":"xterm-256color","PATH":"/home/trafalgar/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/mingw64/bin:/mnt/c/Program Files/Java/jdk-12.0.2/bin:/mnt/c/Program Files/Java/jdk-12.0.2/jre/bin:/mnt/c/Program Files/dotnet/:/mnt/e/Tools/gradle-6.5.1/wrapper/dists/gradle-5.6.4-bin/bxirm19lnfz6nurbatndyydux/gradle-5.6.4/bin:/mnt/c/Program Files/Pandoc/:/mnt/c/Program Files (x86)/Paragon Software/ExtFS for Windows/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Bandizip/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/mingw64/bin/:/mnt/c/Program Files/Java/jdk1.8.0_201/bin:/mnt/c/Program Files/Java/jdk1.8.0_201/jre/bin:/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Fiddler:/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin:/usr/lib/postgresql/13/bin","VSCODE_AGENT_FOLDER":"/home/trafalgar/.vscode-server","LANG":"C.UTF-8","SHELL":"/bin/bash","PWD":"/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code","HOSTTYPE":"x86_64","WSLENV":"VSCODE_WSL_EXT_LOCATION/up","VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH":"/home/trafalgar/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/remote/node_modules","VSCODE_CWD":"/mnt/c/Users/Trafalgar Ricardo Lu/AppData/Local/Programs/Microsoft VS Code","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","LESSCLOSE":"/usr/bin/lesspipe %s %s","LESSOPEN":"| /usr/bin/lesspipe %s","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","VSCODE_LOG_NATIVE":"false","VSCODE_AMD_ENTRYPOINT":"vs/server/remoteExtensionHostProcess","VSCODE_PIPE_LOGGING":"true","VSCODE_VERBOSE_LOGGING":"true","VSCODE_EXTHOST_WILL_SEND_SOCKET":"true","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_LOG_STACK":"false","VSCODE_NLS_CONFIG":"{\"locale\":\"en\",\"availableLanguages\":{}}"}
> [2021-07-07 10:46:33.676] [remoteagent] [info] New EH opened, aborting shutdown

I want to install some extension in WSL. There is a button 'Install in WSL:Ubuntu-20.04', I click it, but nothing happened. It looks like I just click a button that does'nt bind any event. But in normal  workspace at windows, it can download and install extension normally.

**Comment by sandy081** [comment]
Can you able to install other extensions, say by searching for example? Is it possible to provide a gif showing what is happening?

**Comment by TrafalgarRicardoLu** [comment]
I move to a new place, use a new wifi, and everything works well! 

So I think the former wifi used bad DNS.
