### ISSUE TITLE
[Bug] `settings.action.editFocusedSetting` seems to be doing nothing

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#127938]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.57.1
- OS Version: Windows 10

Steps to Reproduce:

1. Try `settings.action.editFocusedSetting` in the UI/JSON split editor.
2. Seems to be doing nothing.

**Comment by roblourens** [comment]
That was a command for the old split json editor which was actually just removed in Insiders. Not sure whether it was working properly before.

**Comment by wenfangdu** [comment]
@roblourens Yes, it was working properly before, see https://stackoverflow.com/a/68264418/7881859.
