### ISSUE TITLE
Cygwin zsh installation doesn't work properly in integrated terminal

### ISSUE THREAD

**Issue by rvcristiand** [microsoft/vscode#127960]
Issue Type: <b>Bug</b>

I try to config the integrated terminal to run cygwin's zsh installation, so I added this to the 'settings.json' file:
```
    "terminal.integrated.profiles.windows": {
        "myCygwin": {
          "path": "C:\\cygwin64\\bin\\zsh.exe",
          "args": ["--login"]
        }
      },
      "terminal.integrated.defaultProfile.windows": "myCygwin"
```

When I try to debug a python file I see the instructions aren't properly typed in the terminal. For example (see the `595` in the path),

```
cmd /C "C:\Users\rvcristiand\AppData\Local\Programs\Python\Python39\python.exe c:\Users\rvcristiand595\pythonFiles\lib\python\debugpy\launcher 53244 \.vscode\extensions\ms-python.python-2021.6.944021-- d:\Documents\pyFEM\pyFEM\core.py "
C:\Users\rvcristiand\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'c:\Users\rvcristiand595\pythonFiles\lib\python\debugpy\launcher': [Errno 2] No such file or directory
```

When I use `bash.exe` for `zsh.exe` works properly.

```
$  /usr/bin/env C:\\Users\\rvcristiand\\AppData\\Local\\Programs\\Python\\Python39\\python.exe c:\\Users\\rvcristiand\\.vscode\\extensions\\ms-python.python-2021.6.944021595\\pythonFiles\\lib\\python\\debugpy\\launcher 53257 -- d:\\Documents\\pyFEM\\pyFEM\\core.py 
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (12.16GB free)|
|Process Argv|--crash-reporter-id eaf4e8c3-faec-4c87-8e8d-e826f112930c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805:30301674
pythonvspyt200:30331937
binariesv615:30325510
vsccppwtct:30329789
aatestflight:30331711

```

</details>

**Comment by meganrogge** [comment]
does this also happen in an external terminal?

**Comment by rvcristiand** [comment]
Hi @meganrogge, I changed the `launch.json` file to execute the python file from `externalTerminal`

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal",
            "env": {"PYTHONPATH": "${workspaceFolder}"}
        }
    ]
}
```
And it works, but vscode run the program in a VS Code Console (it seems to me the command prompt).

**Comment by Tyriar** [comment]
I suspect this isn't an issue with VS Code but rather cygwin, probably due to multiple levels of pty emulation.
