### ISSUE TITLE
Do we still need "Execute Git Commands"?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1279]
We moved quite some commands to top level in F1 but we still have "Execute git commands". I think we should have one or the other. I think having the commands top level is favourable because this allows extensions to call them.

**Comment by joaomoreno** [comment]
:+1:

**Comment by egamma** [comment]
@joaomoreno yes the Command palette looks funny when you filter the commands for Git. So I assume that fix is that the 'git branch' and 'git commit' will become top-level commands?

**Comment by joaomoreno** [comment]
Exacto!

**Comment by egamma** [comment]
:+1: +99
