### ISSUE TITLE
Release notes for insiders launches a tab, closes it and then launches a web page

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12792]
- VSCode Version: Code - Insiders 1.6.0 (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
#12520

Steps to Reproduce:
1. In dev tools Go to Application > Local Storage
2. Set the `storage://global/releasenotes/lastversion` key to 1.5.0
3. Reload window
4. Click the release notes button, a tab will appear and then close before opening a web page

**Comment by joaomoreno** [comment]
If you set the version in `package.json` to `1.5.0` and get the message, it should work. In **any** error case (no internet, firewall blocking, etc) you'll get redirected to the browser just as before.

Can you try again?

**Comment by bpasero** [comment]
I am seeing the same btw :-(

**Comment by Tyriar** [comment]
So I just did the following:

- Set package.json version to 1.6.0
- Set lastversion to 1.5.0
- Change the releaseNotesUrl in product.json to stable's

Still opened the browser, just at https://code.visualstudio.com/updates#vscode instead. Is something other than releaseNotesUrl?

**Comment by joaomoreno** [comment]
Not happening any more.
