### ISSUE TITLE
UX meeting agenda 28 September 2016

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#12795]
Letterpress shortcuts: https://github.com/Microsoft/vscode/issues/12716#issuecomment-249928647

Horizontal panel design: https://github.com/Microsoft/vscode/issues/12277#issuecomment-248688405

Inline title bar for MacOS: https://github.com/Microsoft/vscode/issues/12377

@Microsoft/vscode - let me know if you want to join the meeting (Wednesday 4pm BST)

**Comment by octref** [comment]
I'm interested. How can I join?

**Comment by stevencl** [comment]
Quick notes

- No strong feeling for styling the letterpress shortcuts.
- Brad and Steven to discuss when and how to review the workbench UX holistically, incorporating horizontal panel design and inline title bar.
