### ISSUE TITLE
"workbench.startupEditor" choice not respected, always opens without an editor

### ISSUE THREAD

**Issue by joelhoisko** [microsoft/vscode#127983]
Issue Type: <b>Bug</b>

This started happening within the last month. Whenever I open up vscode with the `code` command (no path specified), it doesn't show me the default `gettingStarted` page, only the blank page with the file explorer telling me to open a folder/clone a repo. Changing `"workbench.startupEditor" ` doesn't help.

But if I open a second vscode window while the first one is still open, the wanted `startupEditor` page shows up, but only while the other page is stil open.

This works as intended on the `Insiders` version I quickly tested with the correct page showing up.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2986)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.29GB (2.92GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 7d038cc3-893f-4e8b-ac01-a8e05549cb08|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache-syntax-vscode|att|0.1.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
language-hugo-vscode|bud|1.3.1
gitlens|eam|11.5.1
vscode-great-icons|emm|2.1.79
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.27.1
go|gol|0.26.0
terraform|has|2.13.0
vscode-guid|hea|1.4.20
vscode-power-mode|hoo|2.2.0
plantuml|jeb|2.15.1
vscode-random|jre|1.9.0
hugo-shortcode-syntax|kae|1.0.0
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
vscode-aks-tools|ms-|0.0.8
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
azure-account|ms-|0.9.8
vsliveshare|ms-|1.0.4498
material-icon-theme|PKi|4.8.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.20.0
gruvbox-material|sai|6.4.5
code-spell-checker|str|1.10.2
ayu|tea|0.20.1
vscode-icons|vsc|11.5.0
vim|vsc|1.21.4
markdown-all-in-one|yzh|3.4.0
grammarly|znc|0.14.0
vscode-proto3|zxh|0.5.4

</details>

**Comment by gjsjohnmurray** [comment]
Insiders is scheduled to become the 1.58 release later this week. If you don't get the problem with Insiders I suggest you close this.

**Comment by joelhoisko** [comment]
Aight, hopefully it'll fix my problem. I'll just wait until then 👍
