### ISSUE TITLE
Touching the Terminal Does Not Set Focus

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#127953]
When using touch instead of a mouse, touching a terminal does not move the focus to the terminal.
Clicking however does.

**Comment by Tyriar** [comment]
Probably need to move to pointer events in xterm.js

**Comment by TheDiveO** [comment]
This really is annoying on devices, such as good ol' Surface Pro 3, where it is natural to use mostly touch and otherwise keyboard shortcuts. Unfortunately, focusing the terminal pane has no configurable shortcut that I'm aware of. Or does it have one?

**Comment by Tyriar** [comment]
I tried simulated touch via devtools mobile emulation as well as touching the xtermjs.org terminal on my phone and both work so I'm not sure what would be causing this. I don't have a touchscreen device other than those and my phone doesn't want to load a Codespace.

**Comment by IllusionMH** [comment]
It works in Demo section on xtermjs.org, but not it VS Code.
I don't have access to Codespaces so can't tell if it's reproducible there.
Also it looks like Web Test Playground doesn't have terminal at all.

**Comment by Tyriar** [comment]
Yeah I'm blocked fixing this unfortunately, maybe @meganrogge can look at this if there's time this month.

**Comment by TheDiveO** [comment]
I can confirm that touch again works as expected with e8a59bc6f920e731b47f0bc72263e82aba8b796e on my Surface Pro 3.
