### ISSUE TITLE
Parameter hints widget size is awkward when the cursor is up against the right of a left or center split editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12794]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/18884506/834475be-849c-11e6-96ab-2addbe268687.png)

Compared to within a split editor on the right side:

![image](https://cloud.githubusercontent.com/assets/2193314/18884526/a0c30510-849c-11e6-86a5-dfa3fb19ad50.png)

**Comment by alexandrudima** [comment]
It is the widget that sets its size, in the editor I read the dimensions (`clientWidth`, `clientHeight`) and I layout it in the viewport at the desired position.

**Comment by joaomoreno** [comment]
Even more breaks, very badly:

![image](https://cloud.githubusercontent.com/assets/22350/19110240/29ddacc6-8af9-11e6-9d9f-934e7eef688e.png)

**Comment by Tyriar** [comment]
Works great! :+1:
