### ISSUE TITLE
自动补全功能无法使用

### ISSUE THREAD

**Issue by lzec97** [microsoft/vscode#127943]
Issue Type: <b>Bug</b>

根据文档配置在WSL下使用的C++环境后，VSC中无法进行自动补全，使用手动补全按键后显示无建议。

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.87GB (6.04GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/parsley/CPP --remote=wsl+Ubuntu-18.04 --crash-reporter-id 352c1ffb-cf57-4b82-98e3-fdf68e1ae436|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3193)|
|Memory (System)|10.80GB (9.45GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-language-pack-zh-hans|MS-|1.57.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-icons|vsc|11.5.0
code-runner|for|0.11.4
vscode-language-pack-zh-hans|MS-|1.57.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by CodeCrazy-ywt** [comment]
After configuring the C++ environment used under WSL according to the document, automatic completion cannot be performed in VSC, and no suggestions are displayed after using the manual completion button.
Translated by Google Translate
