### ISSUE TITLE
cant change color themes

### ISSUE THREAD

**Issue by brandobogar** [microsoft/vscode#127915]
Issue Type: <b>Performance Issue</b>

i cant change my visual studio codes color themes

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by brandobogar** [comment]
Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again. i've tried to change the color themes but i cant

**Comment by gjsjohnmurray** [comment]
I suggest you use Command Palette to open your user settings JSON file, then look at the Problems tab on the Panel to see if any errors are reported.

**Comment by aeschli** [comment]
Thanks @gjsjohnmurray for the reply. Yes, you need to fix the issue in the settings file first.
