### ISSUE TITLE
can't show typescript error

### ISSUE THREAD

**Issue by wjgogogo** [microsoft/vscode#127992]
Issue Type: <b>Bug</b>

Recently, I found the  vs code cant show any ts error inline no matter whether the `tsconfig.json` exists or not.
for example:
![image](https://user-images.githubusercontent.com/17964556/124453758-479c1900-ddba-11eb-8a91-9d7179bf9e4e.png)
I expected vs code will show an error hint under variable `a`.  BTW, I disabled all the extensions.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:50.042Z)
OS version: Darwin arm64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 16015726-1803-4c00-8802-bf4314e3ee9b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
jest-snippets|and|1.8.0
vscode-color|ans|0.4.5
vscode-toggle-quotes|Bri|0.3.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
regex|chr|0.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
tsl-problem-matcher|eam|0.4.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.0.1
vscode-jest-runner|fir|0.4.44
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-google-translate|fun|1.4.13
vscode-pull-request-github|Git|0.27.1
vscode-graphql|Gra|0.3.16
todo-tree|Gru|0.0.213
vscode-drawio|hed|1.5.0
vscode-edit-csv|jan|0.6.0
vscode-browser-sync|jas|1.3.1
search-node-modules|jas|1.3.0
svg|joc|1.4.7
auto-comment-blocks|kev|1.0.1
vscode-gutter-preview|kis|0.27.1
vscode-view-in-browser|kop|1.0.5
template-string-converter|meg|0.5.0
vscode-docker|ms-|1.14.0
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
indent-rainbow|ode|7.5.0
docthis|oou|0.8.2
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.8.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.21
svg-snippets|sid|1.0.1
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
gitmoji-vscode|Vtr|1.0.7
quokka-vscode|Wal|1.0.384
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
find-test-file|wjg|0.2.7
change-case|wma|1.0.0
ReactSnippets|xab|2.4.0
Pangu-Markdown|xlt|0.0.6
file-size|zh9|1.0.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
aatestflight:30331711

```

</details>

**Comment by mjbvz** [comment]
Have you disabled the built-in Typescript extension or set `"typescript.validate.enable": false`?
