### ISSUE TITLE
log

### ISSUE THREAD

**Issue by bearbybrest** [microsoft/vscode#127946]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

Issue Type: <b>Bug</b>

log

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.97GB (7.81GB free)|
|Process Argv|--crash-reporter-id 6b7536a1-1b31-4f0f-be14-4bb7f46a9960|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
c-cpp-compile-run|dan|1.0.14
vscode-clang|mit|0.2.4
vscode-language-pack-ru|MS-|1.57.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.5.0-insiders3
platformio-ide|pla|2.3.2
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30322306
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by CodeCrazy-ywt** [comment]
Here is translation by Google Translate:
We copied the required data to the clipboard as it was too large to send.  Insert this data.
-
It seems that more attention should be paid to the data he inserted.
