### ISSUE TITLE
Renaming file take long time

### ISSUE THREAD

**Issue by jeydi243** [microsoft/vscode#127929]
Issue Type: <b>Bug</b>

Just trying to rename a file.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (2.73GB free)|
|Process Argv|--crash-reporter-id dc3a06e2-3575-4d22-baed-c0386091efd6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-tailwindcss|bra|0.6.12
dart-code|Dar|3.24.0
flutter|Dar|3.24.0
githistory|don|0.6.16
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
php-pack|fel|1.0.2
vue-snippets|hol|1.0.4
vscode-language-pack-fr|MS-|1.57.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
awesome-flutter-snippets|Nas|3.0.0
vetur|oct|0.34.1
material-icon-theme|PKi|4.7.0
vscode-commons|red|0.0.6
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.14

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflightcf:30331712
bridge0702:30333155

```

</details>

**Comment by IllusionMH** [comment]
What kind of files: any type or for specific languages? Rename of JS/TS triggers search for imports update that might take time.

**Comment by jeydi243** [comment]
All type of file

**Comment by isidorn** [comment]
No action planned here since I can not reproduce
