### ISSUE TITLE
Notebook resets scroll position when running cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#127990]
See attached recording

* open my work GH issue notebook
* have a cell in the center of the notebook
* execute
* cell is being scrolled atop
* 
https://user-images.githubusercontent.com/1794099/124447209-70ec8300-dd81-11eb-8b29-40acae46740d.mov

**Comment by rebornix** [comment]
I have made changes to the cell reveal request and currently I didn't reproduce this with the same set up (focused on the first markdown cell, and run code cells below).
