### ISSUE TITLE
[Feature Request] Show more details about extension repository

### ISSUE THREAD

**Issue by tddschn** [microsoft/vscode#127911]
For example, I'd like to open the repo that hosts the code for the extension `dnicolson.binary-plist
` directly from within VS Code, but I couldn't find a way to do it:

![image](https://user-images.githubusercontent.com/45612704/124338651-ba9b6900-dbdb-11eb-9c90-89e04586fc36.png)

Instead, I had to search for this extension on https://marketplace.visualstudio.com/ and then click on the github link on [this page][mp]:
<img src=https://user-images.githubusercontent.com/45612704/124338707-01895e80-dbdc-11eb-808b-de53f9c3794f.png width=300>

, which is really inconvenient.

I'd really love to see the extension page in VS Code to show as much information as the market place page, like the `Rating & Review` tab and the info the on right side on the [market place page][mp]. Thanks!

[mp]: https://marketplace.visualstudio.com/items?itemName=dnicolson.binary-plist

**Comment by gjsjohnmurray** [comment]
Isn't that what a click on the word "Repository" in the subheading does?

**Comment by usernamehw** [comment]
It would still be nice to see inside vscode:

- Last commit date
- Number of opened issues & pull requests

**Comment by tddschn** [comment]
@gjsjohnmurray Thanks! That's almost exactly what I need. But it would be better if it shows more details about the repo, e.g. if it's on GitHub, display `<username>/<reponame>`, or show this info on hover.

**Comment by tddschn** [comment]
Seems like the requested feature has been added in v1.59. Thanks!
