### ISSUE TITLE
Allow/use folder name when opening file in multi-root workspace

### ISSUE THREAD

**Issue by tp** [microsoft/vscode#127958]
## Context

We have a mono-repo with multiple Dart code projects which are each in their own folder directly under the root.

For optimal tooling support we use a "multi-root workspace".

The file structure looks like this:

```
/
 a/
   foo.txt
 b/
   bar.txt
```

## The Problem

Trying to open `a/foo.txt` from the quick open menu (<kbd>CMD</kbd> + <kbd>P</kbd>) leads to 0 results.

## Feature Request

Tooling in the CLI as well as the paths in PRs on GitHub often reference the "local" paths inside the repository, e.g. `a/foo.txt` which also maps 100% with the file layout in the VS Code explorer.

Unfortunately when pasting `a/foo.txt` into the file open (<kbd>CMD</kbd> + <kbd>P</kbd>) dialog, it doesn't show any results. When using just `foo.txt` the correct file in `a/` is offered.

I think it would be nice to have these "perfect matches" offered to open directly.

**Comment by TylerLeonhardt** [comment]
Yeah I think this makes sense to me. I see @bpasero added @roblourens as well. Rob, do you have context on why this doesn't work today?

**Comment by bpasero** [comment]
I believe the underlying issue is that we take the user typed query string from quick open and run it over all folders that are known to the multi root workspace. We would probably have to detect that the user has put the name of a root workspace and remove that from the search string? Or maybe we could trick Ripgrep into understanding that a root workspace has a certain prefix (name) that should be taken into account?

**Comment by bpasero** [comment]
Actually isn't this https://github.com/microsoft/vscode/issues/32444 ?

**Comment by tp** [comment]
@bpasero Indeed, it sounds like it should've been fixed with https://github.com/microsoft/vscode/pull/89765, but I still have the following issue:

It basically doesn't work for "perfect matches" (which is what I usually have when copying paths from GitHub).

So in the case of 

```
/
 a/
   folder/
    foo.txt
```

Quick / File Open works for a "manually typed" `a/foo.txt`, but not for the perfect copied query `a/folder/foo.txt` for some reason.

**Comment by tp** [comment]
One more thing: I also just noticed that click on the path `a/folder/foo.txt` works in the terminal (which then opens the quick open overlay showing the matching file), while the manual entry of the same string does not…

**Comment by roblourens** [comment]
There is something wrong here. It's working for files in the root of a workspace folder but not files under a subfolder

**Comment by andreamah** [comment]
<img width="369" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/d368341c-64c0-4650-a59a-60a9b42befa1">
 
I can no longer reproduce this bug.
