### ISSUE TITLE
Collapse ending brace to the same line in JavaScript

### ISSUE THREAD

**Issue by coderlisan** [microsoft/vscode#127971]
It would be nice if VS code bring this feature. Collapse ending brace to the same line in JavaScript.
![Screenshot_1](https://user-images.githubusercontent.com/44293934/124411588-a176f180-dd6e-11eb-84ec-43f587592f79.png)

**Comment by aeschli** [comment]
The TypeScript/JavaScript language support provides the ranges and could support such a feature.

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/3352 [folding] Collapse ending brace to the same line

**Comment by coderlisan** [comment]
Hey @aeschli, I tried a lot but i don't find that feature. as a contributor could please add this feature in the next edition. as you can every popular code editor has this feature. collapse code block in same line. It's increasing readability.

**Comment by coderlisan** [comment]
Hey @ArturoDent, #3352  has no solution.
