### ISSUE TITLE
"workbench.list.openMode": "doubleClick" breaks terminal tab switching

### ISSUE THREAD

**Issue by zachlitz** [microsoft/vscode#127907]
Issue Type: <b>Bug</b>

When using settings
```json
{
    "workbench.list.openMode": "doubleClick" 
}
```

with terminal tabs, it is impossible to switch terminal tabs.

![image](https://user-images.githubusercontent.com/3002265/124329794-f9301580-db40-11eb-9452-b3d60b34fdd2.png)

Clicking on a tab (red arrow) has no effect. The only way to switch tabs is to play around with dragging the tab to the top.

When `"workbench.list.openMode": "doubleClick" ` is changed to `singleClick` or removed all together then the tabs work as they should.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.99GB free)|
|Process Argv|--crash-reporter-id 30648e84-8aa0-4194-84f2-4c53fdfdfcf2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.1.1
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
vscode-power-mode|hoo|2.2.0
git-tree-compare|let|1.10.2
formate|Mik|1.1.6
vscode-typescript-tslint-plugin|ms-|1.3.3
title|nil|0.1.0
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
