### ISSUE TITLE
fas

### ISSUE THREAD

**Issue by lgraciano** [microsoft/vscode#127902]
Issue Type: <b>Bug</b>

fsa

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.94GB (9.42GB free)|
|Process Argv|--crash-reporter-id 5a8268a9-8ae6-4173-9882-a0912d992d1a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 2999)|
|Memory (System)|15.59GB (10.85GB free)|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.1.0
project-manager|ale|12.2.0
django-html|bib|1.3.0
bracket-pair-colorizer-2|Coe|0.2.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-language-pack-pt-BR|MS-|1.57.1
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.7.0
code-settings-sync|Sha|3.4.3
vscode-djaneiro|the|1.4.2
errorlens|use|3.3.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
vscode-languagetool|ada|3.8.0
vscode-languagetool-pt|ada|3.8.0
project-manager|ale|12.2.0
arepl|alm|2.0.2
vscode-django|bat|1.6.0
vscode-pytest|Cam|0.1.1
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.16
python-extension-pack|don|1.6.0
vscode-python-pack|dse|1.4.0
gitlens|eam|11.5.1
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
ai-docstring|gra|0.1.3
todo-tree|Gru|0.0.213
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
MagicPython|mag|1.1.0
python-path|mge|0.0.11
vscode-docker|ms-|1.14.0
vscode-language-pack-pt-BR|MS-|1.57.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.6.3
jupyter|ms-|2021.6.999662501
vsliveshare|ms-|1.0.4498
color-highlight|nau|2.3.0
indent-rainbow|ode|7.5.0
missinglineendoffile|ric|0.3.1
blank-line-organizer|rin|0.1.5
django-intellisense|sha|0.0.2
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.10.2
code-spell-checker-portuguese-brazilian|str|0.1.7
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30322306
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by CodeCrazy-ywt** [comment]
@Igraciano Sorry I totally don't understand what you mean. Could you explain it more clearly?
