### ISSUE TITLE
'Run in external terminal' does not reuse alternate terminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12790]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

Testing #12252

Steps to Reproduce:
1. Run app.js with `process.exit(0);` using iTerm2.app as external terminal
2. Observe: Each time it is run / restarted a new iTerm2 window opens

Using the default Terminal.app a single window is reused.

**Comment by weinand** [comment]
Someone has to add the 'reuse' functionality to the iTermHelper.scpt AppleScript.
