### ISSUE TITLE
Allow workspace relative files.associations setting

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#12805]
- VSCode Version: 1.6 Insiders
- OS Version: OS X 10.11.6

Currently, if I have a project `test`, with a file `test/src/app.js`. I need this workspace setting to get it recognized as TypeSscript:

``` json
{
  "files.associations": {
    "/Users/octref/Code/fiddle/test/src/*.js": "typescript"
  }
}
```

I wish I could do

``` json
{
  "files.associations": {
    "src/*.js": "typescript"
  }
}
```

**Comment by bpasero** [comment]
@octref for that I think you should set:

{
  "files.associations": {
    "**/src/*.js": "typescript"
  }
}

Since it is totally valid to open files without having a workspace open we cannot allow workspace relative paths here.

**Comment by octref** [comment]
@bpasero 

But things like `test/node_modules/mypackage/src/app.js` would also be matched.

**Comment by bpasero** [comment]
That is true but just allowing workspace relative paths is causing many issues because they do not work once you have no workspace open. How would you solve that?

**Comment by octref** [comment]
How about only applying global `files.associations` when no workspace is open?

Or if you meant adding relative path to workspace settings in general, how about allowing `${workspaceRoot}`, similar to `launch.json`?

**Comment by bpasero** [comment]
I am not sure I understand the suggestion. For one a user might not easily understand the difference between workspace and global association setting, it is too subtle. And then while we could support `${workspaceRoot}` it would not work when no workspace is open and again I fear this is too subtle...

**Comment by bpasero** [comment]
The only potential solution I see is to allow for workspace relative paths only when you configure workspace settings (as opposed to global settings). But this needs lots of guidance to the user to make this understandable. 

I am open for suggestions and PRs if someone wants to jump in.

**Comment by ralish** [comment]
@bpasero Agree with your views on implementation. I just found this issue after trying to set a relative `files.associations` path in a workspace settings files. From my PoV, it only makes sense to support such paths within workspace settings files and not global or user settings files.

**Comment by DaDummy** [comment]
It is sad that there is no way to configure a workspace to e.g. treat only files in the root folders in a special way. I don't understand why it would be complicated to either only allow that in the workspace settings file or ignore such entries whenever there is no workspace.

Why does the workspace "files.associations" configuration support global paths at all? That feels like really bad design IMHO.

Example of a workspace configuration **that does not do, what one would expect** which is treating files in the workspace root specially:
```json
{
    "files.associations": {
        "/*.{yml,yaml}": "ansible",
    }
}
```

Instead I have to do this in a workspace configuration making it strictly non-portable:
```json
{
    "files.associations": {
        "/home/user/projects/myproject/*.{yml,yaml}": "ansible",
    }
}
```

There appears to be no clean alternative as I do not want all yaml files in that workspace to be handled by that extension and it will be tedious to add each and every subfolder to the configuration hoping that it won't also match a path segment on some user's workspace path.

Please consider reopening this issue at least as this currently is a won't-fix-without-existing-workaround.

**Comment by nickiaconis** [comment]
I encountered this today. It was extra perplexing since I also have the following in my `.vscode/settings.json`:

```json
"typescript.tsdk": "./common/temp/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib"
```

It appears that `"typescript.tsdk"` accepts a relative path and works just fine. So then, what is the technical limitation why `"file.associations"` can't do the same?

```jsonc
// .vscode/settings.json
{
  "files.associations": {
    "./config/rush/*.json": "jsonc" // ← this doesn't work
  },
  "typescript.tsdk": "./common/temp/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib" // ← this does
}
```
