### ISSUE TITLE
The Rename Symbol Dialog Ignores Exclamation Mark

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [microsoft/vscode#128042]
Issue Type: <b>Bug</b>

The rename symbol dialog ignores exclamation marks in symbol names, though the actual rename parameters are correct.

1. Write a symbol in any language supporting exclamation marks in identifiers names, using Julia for the snippet below, but it's reproducible with other languages.
    ```julia
    function test!()
    end
    
    test!()
    ```

2. Run the `Rename Symbol` command.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.12.9-1-MANJARO snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|7.65GB (0.22GB free)|
|Process Argv|julia-vscode --no-sandbox --crash-reporter-id e9b4c761-c989-4fe7-8f42-5278286bd6a4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712
bridge0702cf:30333156

```

</details>

**Comment by jrieken** [comment]
This is up to each individual extension, the UI passes on whatever has been typed in the input box

**Comment by AbdulrhmnGhanem** [comment]
All extensions are disabled as indicated in the system report. I used Julia
just to demonstrate it.
