### ISSUE TITLE
Search in files: Toggle context lines failed as lines set to zero previously

### ISSUE THREAD

**Issue by tobyee** [microsoft/vscode#128095]
Issue Type: <b>Bug</b>

1. Ctrl+Shirt+P: open command palette
2. Command: Search Editor: Open new Search Editor to the Side
3. input search key
4. set context lines to 0 (context lines input box will disappear)
5. click toggle context lines icon
expect: context lines input box show again
actual: not show

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: Yes

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|ms-|2021.6.999662501
vscode-autohotkey|sle|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
aatestflightcf:30331712
bridge0702:30333155

```

</details>

**Comment by JacksonKearl** [comment]
This is fixed in the latest Insiders, which will be out in a Stable release in the next few days.
