### ISSUE TITLE
Integrated Bash terminal odd render

### ISSUE THREAD

**Issue by NogrTL** [microsoft/vscode#128056]
Issue Type: <b>Bug</b>

**Steps**
1. Open bash
2. Launch "gladlew" launch file or anything with line change
3. See

**Expected result**
Terminal progress bar and all the dynamic things looks like inteded and you can see resulting screen
<details>
<summary>Preview</summary>

![Screenrecord_correct](https://i.vgy.me/iVCWZt.gif)

</details>

**Actual result**
Terminal old text got mixed with updated one, making impossible to read the data
<details>
<summary>Preview</summary>

![Screenrecord_incerect](https://i.vgy.me/XWd8b9.gif)

</details>

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.16GB free)|
|Process Argv|--crash-reporter-id b63e975e-3806-4e25-a03d-fc8b500157be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.23
FreeMarker|dco|0.0.9
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|8.0.1
auto-close-tag|for|0.5.10
node-module-intellisense|lei|1.5.0
vscode-docker|ms-|1.14.0
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
docthis|oou|0.8.2
material-icon-theme|PKi|4.8.0
java|red|0.80.0
vscode-xml|red|0.17.0
vscode-yaml|red|0.20.0
vscode-gradle|ric|3.6.1
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.4
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-icons|vsc|11.5.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.10.14
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
aatestflight:30331711
bridge0702cf:30333156

```

</details>

**Comment by Tyriar** [comment]
This is an issue with the underlying handling of the process which is like a result of git bash doing something wrong or the program you're running in it. Try updating git bash as a first step but there's nothing we can do for this
