### ISSUE TITLE
Interactive window toolbar is wrapping

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#128077]
It does not in notebooks but it does in the interactive window. 

![image](https://user-images.githubusercontent.com/4674940/124648242-e4f35d80-de4b-11eb-9a7f-50fd79719d12.png)

**Comment by joyceerhl** [comment]
This looks like the webview interactive window. The builtin interactive window's toolbar should not wrap, i.e. behaves exactly the same way as the toolbar in native notebooks: 

![image](https://user-images.githubusercontent.com/30305945/124662815-212fb980-de5e-11eb-92ef-1224f8b1392e.png)

**Comment by kieferrm** [comment]
Yeah, user error.
