### ISSUE TITLE
No me deja abrir ninguna extensión 

### ISSUE THREAD

**Issue by EBF98** [microsoft/vscode#128025]
Buenas, el programa no me deja abrir ninguna extensión, en especial PlatformIO IDE, que es la que necesito para trabajar.
No me sale la pestaña de Home, ni nada por el estilo, no me deja abrirlo y no obstante está instalado. He desinstalado varias veces la extensión y cambiado de versión. También he desinstalado varias veces visual estudio code y sigue igual. 
No encuentro ninguna solución como la descarga de algún software específico o driver. 
Me gustaría solucionar el problema y poder trabajar con vosotros, ya que me gusta más que Atom.
Un saludo.

**Comment by joaomoreno** [comment]
> Buenas, el programa no me deja abrir ninguna extensión, en especial PlatformIO IDE, que es la que necesito para trabajar.

What is the error? Can you show me in a screenshot?
