### ISSUE TITLE
Test: Workspace trust - extension enablement

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#128004]
- [x] anyOS @gregvanl
- [x] anyOS @alexr00

Complexity: 3

Authors: @lszomoru, @sbatten, @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23128004%0A%0A&assignees=sandy081,lszomoru,sbatten)

---

Since I refactored the extension enablement service that touches extension dependencies and workspace trust, I would request to test and validate following scenarios that involves extension enablement and workspace trust.

### Prerequisites
1. Open VS Code, and switch to the Extensions viewlet
2. Install the `lszomoru.helloworld-sample` extension from the Marketplace. This extension supports untrusted workspaces but it depends on the `lszomoru.helloworld-sample-common` extension which does not.

### Trust a workspace 
1. Open a workspace and choose to stay in "Restricted Mode"
2. Click on the "Restricted Mode" status bar item to open the workspace trust editor
3. Click on the "N extensions are disabled or have limited functionality" link to open the Extensions viewlet
    - Confirm that both the `lszomoru.helloworld-sample` and `lszomoru.helloworld-sample-common` extensions appear in the "Disabled in Restricted Mode" section
4. Click on the "Trust" button
5. Open the Extensions viewlet and filter to the installed extensions
   - Confirm that both the `lszomoru.helloworld-sample` and `lszomoru.helloworld-sample-common` extensions are enabled
6. Click on the "Don't Trust" button
7. Open the Extensions viewlet and filter to the disabled extensions
   - Confirm that both the `lszomoru.helloworld-sample` and `lszomoru.helloworld-sample-common` extensions are disabled and show the "Shield" icon
8. Close VS Code

### Extension enablement
1. Open a workspace and choose to stay in "Restricted Mode"
2. Click on the "Restricted Mode" status bar item to open the workspace trust editor
3. Click on the "N extensions are disabled or have limited functionality" link to open the Extensions viewlet
4. Click on the `lszomoru.helloworld-sample` extension
    - Confirm that the "Enable (Workspace)" button is displayed
5. Click the "Enable (Workspace)" button
    - Confirm that you are shown the dialog to trust the workspace in order to enable the extension
6. Click the "Trust Folder & Continue" button
    - Confirm that the workspace transitions to a trusted workspace
    - Confirm that all the extensions that were disabled due to workspace trust are now enabled

**Comment by gregvanl** [comment]
@sandy081 Should the steps above be referencing the helloworld-sample and helloworld-sample-common extensions from Prerequisites rather than the OpenAPI and YAML extensions?

**Comment by sandy081** [comment]
CC @lszomoru who is the original author of this TPI.

**Comment by gregvanl** [comment]
Looks like the OpenAPI (42crunch.vscode-openapi) and YAML (redhat.vscode-yaml) extensions both explicitly support untrusted workspaces so the instructions must be for the two helloworld extensions.

**Comment by lszomoru** [comment]
I have updated the steps. Thanks @gregvanl!

**Comment by sandy081** [comment]
Thanks @lszomoru
