### ISSUE TITLE
vs code is code writing problem

### ISSUE THREAD

**Issue by Md-Shahriar724** [microsoft/vscode#128043]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I can't write any thing properly. because of  vs codes problem. If  I write any thing in first line it automatically break the word and went to the second line, and then if I use a back space it took a space in the word.

please fix my problem immediately.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.27GB free)|
|Process Argv|--crash-reporter-id a7f02f7f-9dce-4785-b3bc-5b07d74bbaee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
prettier-vscode|esb|8.0.1
code-runner|for|0.11.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-wsl|ms-|0.56.5
cpptools|ms-|1.4.1
vscode-typescript-next|ms-|4.4.20210705
java|red|0.80.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
aatestflight:30331711
bridge0702cf:30333156

```

</details>

**Comment by CodeCrazy-ywt** [comment]
@Md-Shahriar724 Have you disabled all your extensions? If not, please disable and try again.

**Comment by alexdima** [comment]
@Md-Shahriar724 Do you have any additional information to help us reproduce?

**Comment by CodeCrazy-ywt** [comment]
@Md-Shahriar724 Or maybe you can post a screenshot
