### ISSUE TITLE
Auto Theme Switch

### ISSUE THREAD

**Issue by deepindersinghbti** [microsoft/vscode#128026]
There should be an option to schedule themes. For example: Use Dark mode from 7:00 PM to 7:00 AM. At 7:00 AM, VS Code should automatically switch back to light theme. There should also be an option to choose our default light and dark modes. For example:

Default Light Mode: Bluloco Light
Default Dark Mode: Solarized Dark

Light Mode Time: 7:00 AM
Dark Mode Time: 7:00 PM

Although this is possible through an extension which I found in the Visual Studio Marketplace, I feel this feature should come built-in.

**Comment by aeschli** [comment]
I think this a good example of functionality that should be provided by an extension, or even the OS. Note that we already have the feature to change themes based on the OS scheme.
All the APIs are there. Extension can innovate, and get as feature rich they want.

**Comment by deepindersinghbti** [comment]
Can you please tell me how I can set the theme to  change based on the OS Schemes?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aeschli** [comment]
The setting is `"window.autoDetectColorScheme": true`. Additionally, you can define your preferred dark and light theme with `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`
