### ISSUE TITLE
VSCODE changes display resolution in Nvidia Surround

### ISSUE THREAD

**Issue by ahahlberg** [microsoft/vscode#128084]
Issue Type: <b>Bug</b>

1. Have a configured mature Nvidia Surround system having no problems with any other application and using a triple 1920x1080 monitor system with bezel correction resulting in what Windows 10 views as a single monitor at 6000x1080 effective resolution.
2. Start VScode
3. Observe that the bezel correction has been removed and the entire display is moved to the left causing the icons along the left side to diappear and the start menu, (configured to be on the left side of the desktop) is now inaccessbile.
4. Observe that typing CTRL-ALT-DEL results in a centered window with the normal options but that the Power icon has disappeared.  The only option available that changes the circumstances is to sign out and then sign back in again, which results in the display returning to normal with proper bezel correction.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (24.20GB free)|
|Process Argv|--crash-reporter-id c14044a8-8ac6-48f2-a007-4eb1cd770325|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.56.5
cpptools|ms-|1.4.1
platformio-ide|pla|2.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by joaomoreno** [comment]
VS Code itself won't ever change that, since it doesn't even know about NVidia Surround. Can you reproduce this with other Electron apps (Teams or Slack) or even Electron itself?
