### ISSUE TITLE
> I'm making a client-side code editor with rudimentary Git support, and syntax highlighting for diff/patch files would be really nice - a way to view the whole diff in a single window (alternative to existing diffeditor - with similar colors to `git diff` console coloring), maybe would be useful for others too.

### ISSUE THREAD

**Issue by kevinsu1015** [microsoft/vscode#128074]
> I'm making a client-side code editor with rudimentary Git support, and syntax highlighting for diff/patch files would be really nice - a way to view the whole diff in a single window (alternative to existing diffeditor - with similar colors to `git diff` console coloring), maybe would be useful for others too.
> 
> https://github.com/microsoft/monaco-languages/ asks to create issues in this repo...

_Originally posted by @kevinsu1015 in https://github.com/microsoft/monaco-editor/issues/2471#issuecomment-874977516_

**Comment by joaomoreno** [comment]
Dupe of https://github.com/microsoft/monaco-editor/issues/2471
