### ISSUE TITLE
`create eslint` matches nothing

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12808]
Found while testing #12601

- VSCode Version: 1.6
- OS Version: OS X 10.11.6

![eslint](https://cloud.githubusercontent.com/assets/4033249/18885977/dd84c280-84a2-11e6-8ad1-14d2a42389ec.gif)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#147

**Comment by octref** [comment]
@dbaeumer 
Are you moving this to eslint as it's a eslint bug?
Because it seems to be
`create es`
not matching
`ESLint: Create '.eslintrc.json' file`
is more a bug on VSCode's command matching algorithm.

**Comment by dbaeumer** [comment]
@octref good point. I will reopen and assign to @bpasero to comment.

**Comment by dbaeumer** [comment]
@bpasero should this be supported? Do I need to tweak this. The command defines ESLint as category

**Comment by bpasero** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/1964
