### ISSUE TITLE
Hierarchy view for YAML and JSON

### ISSUE THREAD

**Issue by yannl35133** [microsoft/vscode#128081]
In the same panel where you show file name then class name then function name in Python,
why not show the parent field name and grand-parent field name, etc ?
Not sure how to deal with lists however, maybe a simple "list" would be okay

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the feature you mean?

**Comment by yannl35133** [comment]
![Screenshot_20210707_095510](https://user-images.githubusercontent.com/40719961/124721545-812f6a00-df09-11eb-8797-745e477d239a.png)
Right under the tabs

**Comment by jrieken** [comment]
<img width="576" alt="Screen Shot 2021-07-07 at 10 33 40" src="https://user-images.githubusercontent.com/1794099/124727223-cd30dd80-df0e-11eb-96d2-143e1e18161e.png">

We have it for JSON, for YAML you need to install an extenion

**Comment by yannl35133** [comment]
It didn't trigger in the new file I made, it probably needs a path for the file.
Do you have a reason why you don't want to include this for the built-in YAML "extension" ?

**Comment by jrieken** [comment]
> It didn't trigger in the new file I made, it probably needs a path for the file.

Yes - it usually needs a file that's saved to disk

> Do you have a reason why you don't want to include this for the built-in YAML "extension" ?

The built-in extensions  only cover syntax highlighting, comment-config, etc but real code for enhanced features.
