### ISSUE TITLE
./code: No such file or directory (file is obviously in folder)  

### ISSUE THREAD

**Issue by Ocean-Moist** [microsoft/vscode#128096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-insider-x64-1625566714
- OS Version: VOID Linux (musl libc)

Running ./code results in this error ```bash: ./code: No such file or directory``` 

```ls``` shows:
```
bin             chrome_100_percent.pak  code           icudtl.dat  libGLESv2.so  libvk_swiftshader.so  locales    resources.pak      swiftshader  v8_context_snapshot.bin
chrome-sandbox  chrome_200_percent.pak  code-insiders  libEGL.so   libffmpeg.so  libvulkan.so.1        resources  snapshot_blob.bin  thing.sh     vk_swiftshader_icd.json
```

I have a separate glibc environment on the same machine. It works perfectly fine. So I am sure that this has something to do with the libc. 

Steps to Reproduce:

1. Install the musl version of void linux
2. Unzip the latest insider version of vscode
3. CD and Run ./code

**Comment by joaomoreno** [comment]
> VOID Linux (musl libc)

musl-based linux isn't supported, unfortunately.
