### ISSUE TITLE
No, I don't want to tweet feedback

### ISSUE THREAD

**Issue by fryew** [microsoft/vscode#128018]
Issue Type: <b>Bug</b>

-Try to submit feedback via the button in the bottom right
-Notice the button says "Tweet"

I don't want to make a twitter account to send feedback.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by polkovnikov-ph** [comment]
The dialog also has "Submit a bug" and "Request a missing feature" links. I think both lead here, so there is a way to send feedback.

What account would you leave feedback with if you didn't have github account? How twitter and github differ objectively?

**Comment by sbatten** [comment]
As mentioned, other ways to contact us are listed in the widget.
