### ISSUE TITLE
Split Terminals Missing Scrollbars

### ISSUE THREAD

**Issue by peterkmurphy** [microsoft/vscode#128087]
Does this issue occur when all extensions are disabled?: Yes

What version of VSCode and OS am I using?:

- VS Code Version: 1.57.1
- Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
- Date: 2021-06-17T13:26:56.255Z (2 wks ago)
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Linux x64 4.15.0-142-generic

Steps to Reproduce:

1. Open the terminal in the working directory.
2. Press the Split Terminal button (once or twice)
3. The notice than only the right hand terminal has a scroll bar; all the other ones are missing one. (I included a screenshot below).

![Screenshot from 2021-07-07 10-24-12](https://user-images.githubusercontent.com/1015989/124682343-e1280f80-df0d-11eb-908b-c8363ea9bccf.png)

I didn't notice this issue until I downloaded the latest version of VScode. Things were working in April.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
