### ISSUE TITLE
Terminal tabs, navigation and focus

### ISSUE THREAD

**Issue by safasofuoglu** [microsoft/vscode#128027]
Great job with the terminal tabs so far! However, I find myself getting caught off-guard when navigating.

### Current status

Selecting a terminal tab:
- Focuses on the tab itself, not the terminal.
- Makes the corresponding terminal visible, except when navigating between splits, which does nothing.

Options when a terminal tab is focused:
- Split (ctrl+shift+5), which also works when terminal is focused.
- Delete (delete), which does not work when terminal is focused.
- Move (up/down), wich does what's explained above in `Selecting a terminal tab`.

Navigation between terminals when a terminal is focused (alt+up/down):
- Is limited to the split group
- Leaves a highlight on the starting terminal tab and puts a secondary highlight on the active terminal tab, both of which are different from the focused terminal tab syle, and unclear how to interpret.

Splitting a terminal tab:
- Focuses on the terminal, if caused by (ctrl+shift+5) when focused on the terminal.
- Focuses on the terminal, if caused by (ctrl+shift+5) when focused on the terminal **tab**.
- Focuses on the terminal, if done through the upper-right menu.
- Focuses on the terminal **tab**, if caused by clicking on the split icon of the terminal tab.

I hope I elaborated the problems clearly. I'm sure you have better context for a solution. Here is my thought process:

### Argument
- There is little utility of having a terminal tab focused.
- For most of the actions (even clicking the terminal tab), I want to start typing on the terminal right away, instead of clicking on the terminal area.

### Ideas
- Remove the need (mostly) for having a terminal tab focused. Provide a means to delete a terminal through keyboard, even when the focus is on the terminal itself.
- Expand (alt+up/down) navigation beyond tab groups to cover all open terminals.

VS Code Version: 1.57.1
OS: Windows 10

**Comment by Tyriar** [comment]
The terminal tabs mostly follow the same rules as other lists like the explorer. By default double clicking will put the focus in the actual terminal but you can configure it to use single click with `"terminal.integrated.tabs.focusMode": "singleClick"`
