### ISSUE TITLE
Math functions not appearing like browser

### ISSUE THREAD

**Issue by jaychapds** [microsoft/vscode#128057]
Example screeshots below.
Incorrect rendering of Math function : ![image](https://user-images.githubusercontent.com/86795317/124620297-f746b900-de96-11eb-9d85-96b4cd1647dd.png)
Correct rendering of Math function : ![image](https://user-images.githubusercontent.com/86795317/124620363-062d6b80-de97-11eb-865e-ae8195400d1a.png)

**Comment by mjbvz** [comment]
See #124783. You need to wrap the math equation in `$`

Extensions could add support for other syntaxes
