### ISSUE TITLE
Not showing previous result of run code 

### ISSUE THREAD

**Issue by Shahid6283** [microsoft/vscode#128071]
In this update When I run my code in the terminal then the terminal is not showing the previous run code. But in the previous update, the terminal is showing the previous result of the run code. Please give this feature in this new update.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
