### ISSUE TITLE
Need a visual separator between the toolbar and the kernel selector

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#128076]
Right now it's your best guess where the line goes. Do we have a theme color token for this?

![image](https://user-images.githubusercontent.com/4674940/124648095-a9f12a00-de4b-11eb-8075-ac2b028badfa.png)

**Comment by misolori** [comment]
I think we should either make the toolbar responsive, just like in the panel when the view is smaller, and move items into the ...

<img width="663" alt="CleanShot 2021-07-08 at 15 44 17@2x" src="https://user-images.githubusercontent.com/35271042/124999610-60e3d600-e003-11eb-9b80-330f8569f72c.png">


Or go into a no-label version:
<img width="662" alt="CleanShot 2021-07-08 at 15 45 00@2x" src="https://user-images.githubusercontent.com/35271042/124999652-7a851d80-e003-11eb-8f58-077c966b85fa.png">

I also think there might be an issue that is tracking this though I can't find it

**Comment by rchiodo** [comment]
+1 on the small icons. This is what Jupyter does.

**Comment by claudiaregio** [comment]
@misolori is this the one you are looking for? https://github.com/microsoft/vscode/issues/125551

**Comment by misolori** [comment]
Thanks @claudiaregio, closing this in favor of https://github.com/microsoft/vscode/issues/125551
