### ISSUE TITLE
Terminal multiple view of the same terminal ?

### ISSUE THREAD

**Issue by maxime4000** [microsoft/vscode#128060]
Lately I've been found to work with the terminal and I originally put the terminal in the Explorer Tabs (for screen estate reason). I start using the debug setup more frequently and I use the Auto Attach: Smart feature. When vscode detect the Auto Attach feature it switch to Run and Debug tab automatically, but I lose the Terminal view which is one that I would prefer seeing in both Explorer and Run and Debug tab.

My request : Could you make duplicate view of the same window ? I would like to see the same terminal view in Explorer and in Run and Debug Side Bar without the need to go back and forth between those tab. Thanks you!

**Comment by isidorn** [comment]
I think terminal now supports being dragged out to the editor area, it should also be possible to open multiple terminals side by side. So closing as designed and @Tyriar can correct me if I am wrong.

**Comment by Tyriar** [comment]
👍 there will only ever be one terminal panel, but you can put them in the editor area now if that helps.
