### ISSUE TITLE
Workspace-Specific Persistent/Saved Terminals

### ISSUE THREAD

**Issue by aacitelli** [microsoft/vscode#128001]
**Context:** In my workspace, I keep two folders open - one that contains the frontend code of my application and one that contains the backend code. I end up running separate commands for each, so for convenience, I usually keep two terminals running, one named "UI" and one named "Backend". I know many users keep a terminal open for git as well (though I personally use the integrated git functionality, which is great). 

**The Problem**: However, whenever I close and reopen vscode, or try and load the workspace from scratch, these terminals disappear. Opening the workspace does not open any integrated terminals, even if I make sure I save the workspace file when they are currently open. 

**The Solution**: I think it would be very cool for terminal state (i.e. name and current path) to be saved and loaded alongside the main workspace file. I'm not sure if simply closing and opening VSCode should cause it to persist (in my case, that would be very beneficial, but that may not be a good general solution), but I'd think at minimum it should load the set of terminals saved when the user did "save workspace" if the user goes through the "Open Workspace" dialog or opens VSCode by double-clicking on a `.code-workspace` file. 

Thanks! Let me know if you need more detail or this has already been suggested (I tried to search, but couldn't find anything similar) and I'm happy to adjust accordingly.

**Comment by Tyriar** [comment]
We defer this type of functionality to extensions like https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

It's possible we will allow persisting and reconnecting to terminals between restarts (not just reloads that works now).
