### ISSUE TITLE
How do I drag a terminal editor into the terminal pane when there is only a single terminal in the terminal pane?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#128069]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.58.0-insider
Commit: 99c968565a27846c330d3498e178184bcb9dd963
Date: 2021-07-06T10:03:54.261Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

#### Steps to Reproduce:

1. Have a terminal in the editor
2. Have a single terminal in the terminal pane (so that the tabs don't show)
3. Drag the terminal in the editor into the terminal pane

#### Expected

Some way to drag the terminal into the terminal pane without it being grouped with the existing terminal in the terminal pane.

#### Actual

There doesn't seem to be a way to do it.
![fordaniel](https://user-images.githubusercontent.com/2644648/124643346-d6a24300-de45-11eb-8252-c6401f65d0df.gif)

#### Addional

If the terminal tabs are visible, you can simply drag and drop the terminal editor into the tabs and it works exactly like I would expect. I'm specifically talking about the scenario when the terminal tabs are not visible because there is only one terminal in the pane.

**Comment by Tyriar** [comment]
Yes this isn't possible right now. We could solve this in two ways:

- Make the inline tab accept drop events
- Make terminals act more like the editor and have 3 drop targets; left, right and center (or top/bottom for panel on side)

**Comment by TylerLeonhardt** [comment]
> Make terminals act more like the editor and have 3 drop targets; left, right and center (or top/bottom for panel on side)

I like this one out of the 2... although... having both wouldn't be too bad.
