### ISSUE TITLE
[folding] Collapse ending brace to the same line

### ISSUE THREAD

**Issue by coderlisan** [microsoft/vscode#128023]
[folding] Collapse ending brace to the same line[
![like that](https://user-images.githubusercontent.com/44293934/124523615-a6dd4600-de19-11eb-92ad-2efe4c870060.png)
](url)

**Comment by coloursofnoise** [comment]
Probably a duplicate of #3352 `[folding] Collapse ending brace to the same line`

**Comment by IllusionMH** [comment]
/duplicate of #3352

Good catch @coloursofnoise Thanks! 
These are screenshots from that issue.
