### ISSUE TITLE
[themes] Allow color customizations in settings to unset color tokens

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#128062]
I suggest that it be possible for `list.activeSelectionIconForeground` to be unset with a boolean too, in case of customizing existing themes that have already set this property.

_Originally posted by @infinnie in https://github.com/microsoft/vscode/issues/125998#issuecomment-866463760_

**Comment by misolori** [comment]
I've imagine that we would want to do something like:

```jsonc
  "workbench.colorCustomizations": {
    "list.activeSelectionIconForeground": null
  },
```

Which would allow for users to unset that color. @aeschli thoughts?

**Comment by NENightElves** [comment]
> I've imagine that we would want to do something like:
> 
> ```jsonc
>   "workbench.colorCustomizations": {
>     "list.activeSelectionIconForeground": null
>   },
> ```
> 
> Which would allow for users to unset that color. @aeschli thoughts?

It will be nice if this can be unset like this.

**Comment by wenfangdu** [comment]
This really shouldn't be in the backlog, perhaps add to the [On Deck](https://github.com/microsoft/vscode/milestone/27) milestone?

**Comment by aeschli** [comment]
Sorry, the change will have ripples and will be adoption work. So I'm not jumping on this until we have more votes.

**Comment by infinnie** [comment]
> Sorry, the change will have ripples and will be adoption work. So I'm not jumping on this until we have more votes.

How many votes are required before it gets moved to On Deck?

**Comment by x80819091** [comment]
> This really shouldn't be in the backlog, perhaps add to the [On Deck](https://github.com/microsoft/vscode/milestone/27) milestone?

I second that.

**Comment by ebrahimiaval** [comment]
I fix this issue by #RGBA colors. when you set "00" for a color this works like disabling. for example:
`
 //settings.json
 "workbench.colorCustomizations": {
        "editor.wordHighlightBackground": "#00000000"
   }
`

**Comment by Tenrys** [comment]
This is especially useful on themes that set certain borders, e.g:

- `diffEditor.removedTextBorder`
- `diffEditor.insertedTextBorder`

They cause the following display issue on my end, and to turn them off completely I have to modify the extension's theme file locally or make a fork of it with my changes. Setting them to transparent does not turn off the outline/borders (whichever VSCode uses)
![image](https://user-images.githubusercontent.com/3979239/210083309-1816fd24-1550-4342-8155-d5b2566ea053.png)

Without outline/borders:
![image](https://user-images.githubusercontent.com/3979239/210083213-7c646cc7-5a5a-4096-9bd1-147021e220f1.png)

**Comment by aeschli** [comment]
Unsetting is now possible using the value `default`

**Comment by wenfangdu** [comment]
@aeschli I'm using `"list.activeSelectionIconForeground": "default"` with the latest insider, but it's still not fixed:

https://github.com/microsoft/vscode/assets/28700378/32acc088-a2ac-4d65-aadc-d76e5a5d98da

**Comment by aeschli** [comment]
The feature is in todays insiders build.
Version: 1.91.0-insider
Commit: 5f646b8e67a869ef33061085ffe0e377d5ba040c
Date: 2024-06-06T05:47:27.758Z

It allows to set a color to its default. Note that only has an effect for the color that have been changed by the current theme.

@wenfangdu In your screenshot it looks like you are already using the default dark theme, not sure what you expect the setting to do.

**Comment by wenfangdu** [comment]
@aeschli I'm on:
Version: 1.91.0-insider (Universal)
Commit: 7cd1f1ce4e8ba91863fc9840530073813a0fd4df
I expected these two icon colors are the same, currently, the active one is white:
![image](https://github.com/microsoft/vscode/assets/28700378/713f5694-46b0-4b10-918f-f96a3b710560)
