### ISSUE TITLE
custom activeBorder not works when window.zoomLevel < -1

### ISSUE THREAD

**Issue by apawn** [microsoft/vscode#128000]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

- OS Version: MacOs 10.15.7

Steps to Reproduce:

1. set the active tab border
```
  "workbench.colorCustomizations": {
    "tab.activeBorder": "#ff8800",
  },
```
2. zoom the vscode window to -2 by using shortcut "Command" + " - "

**Comment by bpasero** [comment]
That sounds like a upstream / chrome issue to me given it works in other zoom levels.
