### ISSUE TITLE
Syntax color changed after last update

### ISSUE THREAD

**Issue by komritza** [microsoft/vscode#128005]
Issue Type: <b>Bug</b>

Start VSC and open any `.dart` file. Syntax color changed from white to light blue. It became really hard for me to work with this colors. How did this happen? Can anyone help?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 7|
|Memory (System)|16.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id e703730f-38dd-4bf9-a649-bcac7c9f462d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
Kotlin|mat|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehovct:30309550
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by ArturoDent** [comment]
If you rollback the dart extension to a previous version, does it go back to the previous syntax coloring?

**Comment by CodeCrazy-ywt** [comment]
@komritza hey, please attach a screenshot so that we can better analyse the issue.

**Comment by komritza** [comment]
So this is how it looked:
![Bildschirmfoto 2021-07-05 um 16 21 35](https://user-images.githubusercontent.com/44901103/124633923-11c46680-de86-11eb-9655-53a39e086fcf.png)

And this is now:
![Bildschirmfoto 2021-07-05 um 16 21 45](https://user-images.githubusercontent.com/44901103/124633901-0bce8580-de86-11eb-98f4-bab121837172.png)

I am wondering if theme it self got changed. FYI I am using Dark+ (default dark). Or maybe there is some issue with DartAnalyzer if it sends different semantic information for code fragments. Pretty confused tbh.

@ArturoDent I didn't try rollback to a previous version so I can't tell you if it will go to previous syntax coloring.

**Comment by CodeCrazy-ywt** [comment]
Emm...From my perspective, I don't think it's a bug.
On one hand, variable names and operators are more easily to distinguish.
On the other hand, if you don't like the color, you can change a theme so that code can be highlighted in your favorite colors.

**Comment by alexr00** [comment]
Before, there was no built in syntax highlighting for dart. One month ago, we added it, which is what you're seeing now. You can try disabling the built in dart extension if you want the old behavior.
