### ISSUE TITLE
unable to stop task in dev container

### ISSUE THREAD

**Issue by kale1d0code** [microsoft/vscode#128008]
Issue Type: <b>Bug</b>

run a task which requires a port.
run a second task which requires the port.
warns about port in use.
no way to end previous task.
have tried killing processes, only solution is to kill the dev container and start again

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.11.0-22-generic snap
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|11.61GB (3.06GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 18d2850e-57ce-49b0-80e1-78bffcc8d3ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Dev Container: PHP|
|OS|Linux x64 5.11.0-22-generic|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3041)|
|Memory (System)|11.61GB (3.07GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-great-icons|emm|2.1.79
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
file-icons|fil|1.0.29
dotenv|mik|1.0.1
remote-containers|ms-|0.183.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
file-and-folder-icons|nex|1.0.4
material-icon-theme|PKi|4.8.0
nunjucks|ron|0.3.0
vscode-icons|vsc|11.5.0
vscode-todo-highlight|way|1.0.4
php-debug|fel|1.16.1
vscode-apache|mrm|1.2.0

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
> run a task which requires a port.
run a second task which requires the port.

Can you share how you're running tasks?
