### ISSUE TITLE
Git sync: Icon looks off compared to others around

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1280]
The screenshots in the test plan show it quite well, on Mac at least the sync and publish icon is not nicely aligned with the SVGs for git and problems/errors markers.

Either we use Octicon for git branch as well or we find SVGs for the publish/sync icons maybe?

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/11783383/48e4d7fe-a277-11e5-8ffd-189fc61edc8a.png)

**Comment by bpasero** [comment]
I think it is actually more a problem within the git status contribution and not so much to the right hand side. I would even think we could move the two things closer and make sure the git icon is aligned to the font.

**Comment by egamma** [comment]
+ @bgashler1
