### ISSUE TITLE
CTRL + V  didn't work when showInputBox in webview `onDidReceiveMessage` callback

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#128035]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.showInputBox in webview `onDidReceiveMessage` callback
2.Press CTRL + V  to paste the text

The text does not appear in the INPUTBOX

![image](https://user-images.githubusercontent.com/995909/124562903-2434a500-de72-11eb-89f7-c57e2c7c10ca.png)

**Comment by zhfnjust** [comment]
this code work in the old vscode version like : 1.55.2

**Comment by mjbvz** [comment]
Should be fixed by f882d49bc7b72b8417f0aba686ed6d76960d5de7 I believe

Let me know if you still see this in VS Code insiders

**Comment by zhfnjust** [comment]
It's ok now.
