### ISSUE TITLE
add a 'managedByParent' property to 'DebugSessionOptions'

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#128058]
When creating child debug sessions programmatically, we need a way to let VS Code know how to manage the lifecycle of the newly created children. Today lifecycle requests (like "restart") are sent to the session itself. But there are [use cases](https://github.com/microsoft/vscode/issues/118196#issuecomment-854021411) where the parent should be in control.

```ts
/**
 * Options for {@link debug.startDebugging starting a debug session}.
 */
export interface DebugSessionOptions {

    /**
     ... other options
     */

    /**
     * Controls whether lifecycle requests like 'restart' are sent to the newly created session or its parent session.
     * By default (if the property is false or missing), lifecycle requests are sent to the new session.
     * This property is ignored if the session has no parent session.
     */
    managedByParent?: boolean;
}
```

@connor4312 does this proposed API and the wording makes sense to you?

**Comment by connor4312** [comment]
lgtm

**Comment by weinand** [comment]
I agree with @connor4312 that adding `lifecycle` to the proposed property makes it clearer what is being managed.

```ts
/**
 * Options for {@link debug.startDebugging starting a debug session}.
 */
export interface DebugSessionOptions {

    /**
     ... other options
     */

    /**
     * Controls whether lifecycle requests like 'restart' are sent to the newly created session or its parent session.
     * By default (if the property is false or missing), lifecycle requests are sent to the new session.
     * This property is ignored if the session has no parent session.
     */
    lifecycleManagedByParent?: boolean;
}
```

**Comment by weinand** [comment]
Proposal from [above](https://github.com/microsoft/vscode/issues/128058#issuecomment-879057319) was discussed and approved on API call from July 13.

**Comment by weinand** [comment]
Since VS Code has not yet implemented this API, it does not make sense to verify it and add it to the release notes for the July 2021 release.
So I will move it to August 2021.

**Comment by weinand** [comment]
VS Code now supports the `lifecycleManagedByParent` API but testing this only makes sense with a debug adapter that creates child debug sessions.
@connor4312 I suggest that we test the `lifecycleManagedByParent` API with js-debug.

**Comment by connor4312** [comment]
I've adopted this in js-debug. Now that we have explicit signaling here, should we create a debt item to remove the previous lifecycle handling heuristics that we added with compact sessions and whatnot?

**Comment by weinand** [comment]
@connor4312 you are proposing to remove the "lifecycle handling heuristics code" but not "compact sessions", right?

**Comment by connor4312** [comment]
That's right

**Comment by weinand** [comment]
@connor4312 I've created debt item https://github.com/microsoft/vscode/issues/131442 for this.
