### ISSUE TITLE
Commit unstaged files

### ISSUE THREAD

**Issue by JPedroBorges** [microsoft/vscode#128007]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Stage a file you want to commit and press the commit button.
![image](https://user-images.githubusercontent.com/12955328/124489380-d0aa5480-dda8-11eb-850f-6211ac03ddfb.png)

2. Both files (staged and unstated) gets committed.
![image](https://user-images.githubusercontent.com/12955328/124489452-eddf2300-dda8-11eb-9197-66853689288a.png)

Expected:
- Only one file (Results.tsx) should be committed.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.89GB free)|
|Process Argv|--crash-reporter-id 2f905500-1e68-425b-9bbd-08d262eb44aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.13.0
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.0.1
vscode-jest-runner|fir|0.4.44
vscode-graphql|Gra|0.3.16
rest-client|hum|0.24.5
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
remote-wsl|ms-|0.56.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4498
angular-console|nrw|17.6.1
indent-rainbow|ode|7.5.0
vscode-boot-dev-pack|Piv|0.0.8
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
highlight-matching-tag|vin|0.10.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30329804
vscextlangct:30322307
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by teki** [comment]
I am not able to commit staged changes anymore. No matter what I do (even Commit Staged) everything is commited.

Btw, it is very confusing that there is 3 types of commit now. What does `Commit` do?
<img width="345" alt="Screen Shot 2021-07-12 at 10 26 13 am" src="https://user-images.githubusercontent.com/5516/125214882-c504e380-e2fc-11eb-8a09-24dce4941580.png">
