### ISSUE TITLE
Keybinding in input editor placeholder is not changed after changing the keybinding

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#128059]
Testing https://github.com/microsoft/vscode/issues/127378

- Open keybindings editor and interactive window in two editor groups
- Check that input editor has shift + enter as keybinding to execute
- Change the keybinding to some other key
🐛 Placeholder is not updated

**Comment by connor4312** [comment]
This doesn't seem to work for me on Windows: https://memes.peet.io/img/21-07-81097592-7213-45e5-b615-92fa3282a408.mp4

**Comment by joyceerhl** [comment]
@connor4312, sorry that's the wrong command, the Jupyter extension contributes multiple Shift+Enter keybindings. Could you please try changing the extension's keybinding for `interactive.execute`? E.g. 
![image](https://user-images.githubusercontent.com/30305945/127555131-5d338516-3ff1-4fc2-b605-6f83a47c7f07.png)

**Comment by connor4312** [comment]
Thanks!
