### ISSUE TITLE
Settings.json suddenly giving suggestions and the yellow underline vanished after saving and changing settings

### ISSUE THREAD

**Issue by rafid149** [microsoft/vscode#128094]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.0-insider
- OS Version: Windows 7 32 bit

Steps to Reproduce:

1.First of all Git bash was not opening when toggle or create new terminal(Git bash default terminal) always PowerShell was appearing---
[http://prnt.sc/1966ds3](url)
2.And so I have to add a git-bash profile and set it to my default terminal use it and then settings.json gave me a suggestion(not an error) that I can only use command prompt as a default profile... and But I didn't care about it and run terminal and I saw it is working fine. but the suggestion... was frustrating so I deleted the profile name and saved it and wrote the profile name again(I don't remember how did I get the idea)
Here are the pictures 
When there were suggestions 
[http://prnt.sc/1968j1i](url)
When I saved it
[http://prnt.sc/1968ay9](url)
And wrote it again
[http://prnt.sc/1968rg4](url)

**Comment by roblourens** [comment]
Sorry, I don't really understand the problem. Can you explain a little more?
