### ISSUE TITLE
files.autosave doesn't get toggled for first time

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12802]
Bug found while testing for https://github.com/Microsoft/vscode/issues/12527

- VSCode Version: 1.6.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open global setting. Make sure `files.autoSave` entry is not present in user's `settings.json`.
2. Click Files -> Autosave in Menu.
3. `"files.autoSave": "off"` is added. I was expecting the previous Menu click would turn this on.

**Comment by bpasero** [comment]
@octref great finding!
