### ISSUE TITLE
INFO: ExitCode=-1073741819 ExistStatus=CancelExit

### ISSUE THREAD

**Issue by marcsatiro** [microsoft/vscode#128093]
Issue Type: <b>Bug</b>

 INFO: ExitCode=-1073741819 ExistStatus=CancelExit

a conexão cai quando estou debugando.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T6600  @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.67GB free)|
|Process Argv|--crash-reporter-id 3c1aea3a-315e-483f-ab69-6d4df6fe5fca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.1.0
All-Autocomplete|Ati|0.0.23
vscode-language-pack-pt-BR|MS-|1.57.1
mssql|ms-|1.10.1
material-icon-theme|PKi|4.8.0
totvs-coverage-analysis|shi|0.0.4
tds-vscode|TOT|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by joaomoreno** [comment]
@marcsatiro What language are you debugging?

**Comment by marcsatiro** [comment]
Good Morning, ADVPL language

________________________________
De: João Moreno ***@***.***>
Enviado: quarta-feira, 7 de julho de 2021 04:01
Para: microsoft/vscode ***@***.***>
Cc: marcsatiro ***@***.***>; Mention ***@***.***>
Assunto: Re: [microsoft/vscode] INFO: ExitCode=-1073741819 ExistStatus=CancelExit (#128093)


@marcsatiro<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcsatiro&data=04%7C01%7C%7C6f604c2f9294470654fd08d9411503d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612380783791144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HUzBHptZqzFXsYVTHIMV9FlFdyufyeVeEuXjn6uyuDI%3D&reserved=0> What language are you debugging?

**Comment by marcsatiro** [comment]
The connection drops when I'm debugging, displaying the message  INFO: ExitCode=-1073741819 ExistStatus=CancelExit. Eu I'm using the tds-vscode extension tds-vscode.  Thanks

**Comment by alefragnani** [comment]
It seems to be a known issue on **tds-vscode** extension. It has been reported 23 ago here https://github.com/totvs/tds-vscode/issues/696

Someone suggested to downgrade the extension, until they fix it.

Hope this helps
