### ISSUE TITLE
{!! $variable !!} is the syntax to output unescaped data of laravel not supported

### ISSUE THREAD

**Issue by bhojkamal** [microsoft/vscode#128006]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: windows 10 - latest

Steps to Reproduce:

1.  VS Code - {
	"resource": "/d:/xamp/htdocs/all-accounting-soft/accounting-new/resources/views/partials/auth/head.blade.php",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Non-null assertions can only be used in TypeScript files.",
	"source": "javascript",
	"startLineNumber": 36,
	"startColumn": 64,
	"endLineNumber": 36,
	"endColumn": 74
}
2.
on line no. 36 ->
 var aka_currency = {!! !empty($currency) ? $currency : 'false' !!}; 
It is correct on code for laravel blade. It is showing error here.

If format on save is tick, it will be modified and the the application will break and wont work at all.  
so need to untick on format on save. 

on format on save, it changes like this - {
!!!empty ....
!! 
}
and does not work. 

and this -> working code -
``` 
var flash_notification = {!! (session()->has('flash_notification')) ? json_encode(session()->get('flash_notification')) : 'false' !!};
```
changes like this and wont work.
```
var flash_notification = {
!! (session() - > has('flash_notification')) ? json_encode(session()->get('flash_notification')) : 'false' !! 
};
```

even (session()->has is separated.

**Comment by diego1araujo** [comment]
You must install a **laravel blade syntax highlight** extension to get it working

**Comment by bhojkamal** [comment]
> You must install a **laravel blade syntax highlight** extension to get it working

Non-null assertions can only be used in TypeScript files.javascript
Non-null assertions can only be used in TypeScript files.javascript
Non-null assertions can only be used in TypeScript files.javascript
Property assignment expected.javascript

I installed **laravel blade syntax highlight* extension, still same error.

**Comment by bhojkamal** [comment]
@diego1araujo 
Thanks and Glad it worked after I re-started after installing the blade ... extensions. I installed 3 blade extensions. 
Before, I had to turn off formatter to save on blade and turn on again for others.
