### ISSUE TITLE
Add a border between sides of the binary diff editor

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#128051]
There should be a vertical line here, indicating where the sash is so the views can be resized.

![image](https://user-images.githubusercontent.com/22350/124605755-19055900-de21-11eb-8f6a-0ea43139c7ea.png)

I looped through all themes and couldn't find one which has a line, maybe we never had this for the binary diff editor?

**Comment by bpasero** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/900690/124606419-29432580-de6d-11eb-931b-8333555046a5.png)

**Comment by joaomoreno** [comment]
To reproduce: don't put your mouse on top of the sash.

Both the workbench grid as well as the text diff editor use some sort of affordance to tell the user where the sash is, without having to go hunt for it:

![image](https://user-images.githubusercontent.com/22350/124607860-1572d180-de23-11eb-979a-0d317dbe5085.png)

![image](https://user-images.githubusercontent.com/22350/124607948-2a4f6500-de23-11eb-8da7-7c4166ea4f39.png)

**Comment by bpasero** [comment]
Yeah I doubt we ever had that for binary diff.

**Comment by bpasero** [comment]
@joaomoreno here is the control code:

https://github.com/microsoft/vscode/blob/3b4d9757e246dd924b792fbab90c41c00ec1cbec/src/vs/workbench/browser/parts/editor/sideBySideEditor.ts#L73-L73

Maybe we have an easy option to show border for splitview that is used there?

**Comment by joaomoreno** [comment]
Yeah the split view has been _invisible_ so far, which has been the lowest common denominator. Recently sashes started showing hover and active UI, but no inactive UI. I don’t really want to add inactive UI since I have to hunt all the usages which currently do their own. So I suggest to do the simple change here and add a `border-left: 1px solid grey` or similar to this specific dom element.

**Comment by bpasero** [comment]
Fair, if someone wants to look into this, I can review a reasonably small PR. The color would have to be themable or reuse an existing color.

**Comment by joaomoreno** [comment]
As I looked into implementing this _extremely low hanging fruit_, I found out your assessment is wrong. This is a regression. Just give `width: 100%, height: 100%` to the `.primary-editor-container` and the border shows up:

![image](https://user-images.githubusercontent.com/22350/124650881-191c4d80-de4f-11eb-8dec-77b6a0e534bc.png)

**Comment by joaomoreno** [comment]
@bpasero Please review.

**Comment by rzhao271** [comment]
Still no sash, it seems.
I also switched to other colour themes, just to be sure.

![Screenshot showing the evidence](https://user-images.githubusercontent.com/7199958/124793680-15e29980-df03-11eb-9e56-362574b29fd5.PNG)

**Comment by bpasero** [comment]
This will only be fixed for July.
