### ISSUE TITLE
CSS color pick for box shadow

### ISSUE THREAD

**Issue by Kushmere** [microsoft/vscode#128019]
This issue has occurred thrice not necessarily under box shadow. It always seems to revolve around color picking when defining properties for a single selector. This time, I was listing two drop shadows under the box-shadow element. When I select the second shadow color-picker and change the color, it changes the color on the first shadow. The issue has always been about trying to change color, either it rejects changing color or it changes an adjacent color.  And there's nothing I can do about it from then on, well, maybe delete the entire selector and try to create a new one.

**Comment by aeschli** [comment]
Can you add a code sample (if this is relevant), or maybe a annimated gif that shows the issue?
