### ISSUE TITLE
Adding intellisense support for node import mapping and subpath imports

### ISSUE THREAD

**Issue by MaxTechnics** [microsoft/vscode#128064]
A feature in node 14 is you can define imports in your package.json and alias your relative paths in your package.json. It would be great if intellisense resolves these so using them would be even better.

An example of package.json imports:
```json
{
  "name": "",
  "version": "1",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "",
  "dependencies": {},
  "devDependencies": {},
  "imports": {
    "#utils/*": "./utils/*",
    "#colors": "./commanddata/colors.json"
  }
}

```

You would be able to use these in your requires. (`require('#utils/myUtil.js');`)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
