### ISSUE TITLE
Automatically crashed When opend 3 Different projects

### ISSUE THREAD

**Issue by face2friend** [microsoft/vscode#128045]
Issue Type: <b>Bug</b>

Hi, I'm using macbook pro, and installed VSCODE in same, sometimes its automatically crashed, when i was using 3 diffeent projects in same time. don't know why this happen, and then asked me to reopen vscode 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|62, 20, 11|
|Memory (System)|10.00GB (1.78GB free)|
|Process Argv|--crash-reporter-id a70703d7-380e-4a69-933a-0db894b8d2a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-laravel-goto|abs|0.4.3
laravel-extra-intellisense|ami|0.6.1
vscode-browser-preview|auc|0.7.1
laravel-blade-spacer|aus|2.1.3
vscode-intelephense-client|bme|1.7.1
laravel-goto-view|cod|1.3.4
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
php-debug|fel|1.16.1
php-intellisense|fel|2.3.14
code-runner|for|0.11.4
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
mssql|ms-|1.10.1
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.12.0
material-icon-theme|PKi|4.8.0
java|red|0.80.0
laravel-artisan|rya|0.0.28
laravel-5-snippets|sac|2.0.1
vscode-blade-formatter|shu|0.7.18
php-formatter|Sop|0.2.4
laravel-goto-controller|ste|0.0.12
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash logs. Thanks!
