### ISSUE TITLE
Jupyter: Enable Scrolling For Cell Outputs not working in the new version since last week.

### ISSUE THREAD

**Issue by hgf777-br** [microsoft/vscode#128017]
Does this issue occur when all extensions are disabled?: Not Relevant

- VS Code Version: 1.57.1
- OS Version: windows 10 Pro 21H1

Steps to Reproduce:

1. Open a Jupyter Notebook
2. Run any code in a cell that generates a lot os lines and it will not create the scroll bar for the output. It will fill the hole lenght of the notebook.

**Comment by rebornix** [comment]
Thanks for reporting, duplicate of https://github.com/microsoft/vscode/issues/126863 and let's track it there.
