### ISSUE TITLE
Going back and forth doesn't work as expected.

### ISSUE THREAD

**Issue by sushil-lakra** [microsoft/vscode#128024]
Issue Type: <b>Feature Request</b>

I usually open two tabs of same file for reference each pointing to different piece of code that I want to refer to simultaneously, This is what VS Code does, If I have two section A and B open, and I have file X open in both sections, Suppose I was in section A, and I go to definition of some function in file X, and it moves me to file Y, now if I go back :/, VS Code moves to file X in section B, Now both sections are in same place, that is I lost what I was referring to.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
