### ISSUE TITLE
"fontWeight" does not correctly apply weights between 100s

### ISSUE THREAD

**Issue by aaronbell** [microsoft/vscode#128097]
Issue Type: <b>Bug</b>

When setting `Cascadia Code` as my editor font, I am unable to access any weight that does not have a weight value on the 100s. 

For example:
`"editor.fontWeight": "340",` will result in a weight equivalent to 300
<img width="291" alt="Screen Shot 2021-07-06 at 10 12 06 PM" src="https://user-images.githubusercontent.com/8460297/124703574-64624a80-dea7-11eb-8ca0-061e9f1e5748.png">
<img width="288" alt="Screen Shot 2021-07-06 at 10 11 37 PM" src="https://user-images.githubusercontent.com/8460297/124703578-64fae100-dea7-11eb-8731-650d9846d0ba.png">

`"editor.fontWeight": "350",` will result in a weight equivalent to 400
<img width="290" alt="Screen Shot 2021-07-06 at 10 14 30 PM" src="https://user-images.githubusercontent.com/8460297/124703696-9a9fca00-dea7-11eb-813c-61028f548a86.png">
<img width="289" alt="Screen Shot 2021-07-06 at 10 14 41 PM" src="https://user-images.githubusercontent.com/8460297/124703698-9b386080-dea7-11eb-82fe-1ccd7c8ab992.png">

In each of these cases, 340 and 350 should be discernibly different than 300 and 400, respectively.  

It appears that VS Code is rounding the weight to the closest 100 (and using that instance) rather than correctly using the variable font setting to interpolate the accurate weight. 

I suspect that this is because CSS "font-weight" values must fall on 100 intervals (https://www.w3schools.com/cssref/pr_font_weight.asp). Instead, for a variable font such as Cascadia Code that includes a full weight range, a CSS property such as `font-variation-settings` should be used. 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
Have you tried using number instead of string values?
String values only support hundreds for compatibility, but numbers are allowed in full range 1-1000 and should be passed to editor as is.

**Comment by IllusionMH** [comment]
#101467 was implemented specifically to support `350` for `Cascadia Code`
Is it reproducible with numeric values as well? 

https://github.com/microsoft/vscode/blob/c9aea49a8727114a2a18a67b8b9af58c5272f1ca/src/vs/editor/common/config/editorOptions.ts#L1589-L1594

What `font-weight` you see if you inspect editor text in editor area?

**Comment by aaronbell** [comment]
Yes, it is reproducible with numeric values as well. 
When I used the 'token inspector' I didn't see anything related to font-weight.

My sense is that though VSCode is now able to accept values that are not at 100s, it may not be using the font variation methodology to implement said values.

**Comment by IllusionMH** [comment]
No, I mean **Help** > **Toggle Developer Tools** and inspect element with text from editor like on web page.
![image](https://user-images.githubusercontent.com/1312662/124761958-04b57f00-df3b-11eb-8a92-70b0972c9d8a.png)
![image](https://user-images.githubusercontent.com/1312662/124762030-1c8d0300-df3b-11eb-854b-8c75fa146cb1.png)
![image](https://user-images.githubusercontent.com/1312662/124762103-31699680-df3b-11eb-9b7f-1e1f0f908c1b.png)

Same `font-weight` style behavior with string values.

If `font-weight` in DevTools matches value from settings then they work correctly and it might be something with installed font version or something platform specific for Electron on Mac.

I don't see any difference between 340 and 350, however as you can see on screenshots 300 vs 350 vs 400 is big difference.

Version: 1.58.0-insider (user setup)
Commit: 4c952751a88154ff4c375b1ca78293ab53a5792a
Date: 2021-07-06T22:43:23.493Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

Cascadia Code PL version 2105.024

Haven't seen any problems with 1.57 versions.

**Comment by aaronbell** [comment]
Ah, thank you! Yes, I am seeing matching weight values between settings and the devtools. So it is likely a platform-specific issue...

**Comment by aaronbell** [comment]
Interestingly, if (in the devTools) I change
`font-weight: 350;`
to
`font-variation-settings: 'wght' 350;`
the font weight renders correctly. 

Given that `font-variation-settings` only takes precedence over `font-weight` in situations where the font is variable, this might be a viable workaround:
<img width="264" alt="Screen Shot 2021-07-07 at 6 21 57 AM" src="https://user-images.githubusercontent.com/8460297/124766320-ab722f00-deeb-11eb-8c24-d0ce5f245352.png">

**Comment by IllusionMH** [comment]
Hm... Does `.ttf` font counts as variable font on Windows and in Chromium specifically? (I have installed all variations, is it correct or wrong usage?)
![image](https://user-images.githubusercontent.com/1312662/124796145-80262900-df59-11eb-8fd1-cc8cf9a3624c.png)

For some reason `font-variation-settings: 'wght' 300;` doesn't do anything by itself and doesn't override `font-weight` value. Need to check more in this area.

**Comment by aaronbell** [comment]
Shouldn’t, no. `.ttf` is a valid variable font format for all platforms. One thing I do know is that css features can be inconsistently implemented in different engines, which might be why it doesn’t seem to do anything on Windows (since apparently the variable font tech is already implemented in font-weight). I don’t know if that would be the cause of the issue here.

**Comment by andreynering** [comment]
While this is not fixed, I found a good enough workaround here: https://github.com/microsoft/cascadia-code/issues/25#issuecomment-1024890739

**Comment by alexdima** [comment]
This was resolved via https://github.com/microsoft/vscode/pull/153968
