### ISSUE TITLE
Make CompletionItemKind customized or extendable

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#128036]
Hello, is it possible to make CompletionItemKind customized or extendable? So that we can have more flexibility setting icons for each CompletionItem.

I'm making an extension which provides snippet completions. There are several types of snippets of my extension: method invocation/variable declaration/... They all have same CompletionItemKind "snippet", because I have to choose one from the provided CompletionItemKind list and cannot add my CompletionItemKind

If the CompletionItemKind can be extended, I can set different icons for different types of snippets, making the completion list more clear for users. Otherwise, users have to expand the details of completion list, see the complete snippet and then get the information about this snippet.

**Comment by jrieken** [comment]
> There are several types of snippets of my extension: method invocation/variable declaration/... They all have same CompletionItemKind "snippet"

Why do you use "snippet" and "method", "variable", or any other of the existing type?

> Hello, is it possible to make CompletionItemKind customized or extendable?

This has come up before and we have decided against that. We want a fixed, simple set of kinds that works across the LSP world.

**Comment by HaoboGu** [comment]
> Why do you use "snippet" and "method", "variable", or any other of the existing type?

Because in our extension, we provide full-line completion, so anyother type except "snippet" is not accurate. Here are two examples:
```
le | 
> let ${1:var} = object.call_some_method();$0

re |
> return object.call_someother_mehtod(${1:param1}, {${2:param2});$0
```
In the first example, the entire variable declaration is completed after `le` and in the second example, the return statement is completed. Currently, we have to use "snippet" for both

It can be improved if we can extend the CompletionItemKind with types like `variable declaration` and `return statement`. Different icons can be assigned to them to indicate they are different types of snippets. 

In this case, a sub-type of snippet like `variable declaration snippet` and `return statement snippet` is also acceptable for me.

In the future, more and more snippet-level completion/generation tools will appear, like Github Copilot/TabNine/etc. If we just put all those snippet completions to "snippet" type, it's not clear for users. What do you think?

**Comment by jrieken** [comment]
I cannot image how an icon for `return statement snippet` would look and I don't believe it will stick with users. Already today our icons aren't "logical" for merely for being recognizable. 

We do have the [`tags?: readonly CompletionItemTag[];`](https://github.com/microsoft/vscode/blob/55868691efbc657fff97af72732e4d8482e11450/src/vs/vscode.d.ts#L4080-L4080)-API but highly doubt this use-case qualifies for a new qualifier. 

For the June release we added support for more detailed completion item labels. That might help you transport more information: https://github.com/microsoft/vscode-docs/blob/1f63b6ea4fdb6f016dc58bc5942de9b2a654c44a/release-notes/v1_58.md#L263-L264
