### ISSUE TITLE
"telemetry.experiments.showCommandsWatermark" switch not working

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12807]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 7

My insiders install had command watermarks displayed. Setting  "telemetry.experiments.showCommandsWatermark" : false didn't have any effect.

**Comment by chrmarti** [comment]
@gregvanl I forgot to ask: Did you restart VS Code to make it pick up the changed setting? It's not live because it's only for testing.

**Comment by chrmarti** [comment]
@gregvanl ping, see previous comment.

**Comment by bgashler1** [comment]
Works for me.

**Comment by bpasero** [comment]
This no longer applies.
