### ISSUE TITLE
New Terminal from profile does not use the "color" setting

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#128163]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.58.0-insider (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:09:55.219Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1. Create a default terminal
2. Create a new terminal selecting the default profile
3. Click the `+` button to add a third instance of the default terminal

My terminal settings:

```json
"terminal.integrated.defaultProfile.windows": "Powershell Preview",
"terminal.integrated.profiles.windows": {
    "Powershell Preview": {
        "path": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
        "color": "terminal.ansiMagenta"
    },
```

![terminal color](https://user-images.githubusercontent.com/5784415/124830074-41c74480-df2e-11eb-8e47-c3403312f6bc.gif)

**Comment by meganrogge** [comment]
blocked by https://github.com/microsoft/vscode/issues/127573
