### ISSUE TITLE
No feature is working

### ISSUE THREAD

**Issue by Mehreen57** [microsoft/vscode#128143]
Issue Type: <b>Bug</b>

Most of the extensions are not working. VS code is very unresponsive. It's working the same as a notepad that is just writing code and nothing else. It delays in responding sometimes it does not respond at all. Had to wait until it finishes saving the file or some other task. Please look into the issue.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.58GB free)|
|Process Argv|--crash-reporter-id a453e1bd-ec1d-4ea0-ae39-c73501641b13|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.1.1
vscode-color|ans|0.4.5
vscode-database|baj|2.2.3
phpserver|bra|3.0.2
emmet-jss|car|1.0.0
bracket-pair-colorizer|Coe|1.0.61
emoji-snippets|dev|1.5.3
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|8.0.1
auto-close-tag|for|0.5.10
code-runner|for|0.11.4
docthis|joe|0.7.1
react-native-snippet|jun|0.5.6
vue|liu|0.1.5
HTMLHint|mka|0.10.0
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.1
jupyter|ms-|2021.6.999662501
vsliveshare|ms-|1.0.4498
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.2
sqltools|mtx|0.23.0
material-icon-theme|PKi|4.8.0
java|red|0.80.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.4
html5-boilerplate|sid|1.1.1
autoimport|ste|1.5.4
open-in-browser|tec|2.0.0
wordpress-snippet|tun|1.1.5
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-java-saber|You|0.1.2
emmet-live|yse|1.0.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0702cf:30334634

```

</details>

**Comment by gjsjohnmurray** [comment]
Please run the "Start Extension Bisect" to investigate which of your extensions (if any) is causing your issue.

**Comment by joaomoreno** [comment]
More details about bisect: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

Also: https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by Mehreen57** [comment]
thanks for reply will check it out

**Comment by joaomoreno** [comment]
Let me know how it goes.
