### ISSUE TITLE
Red triangle (that marks deleted lines) next to line numbers is very hard to click

### ISSUE THREAD

**Issue by irmatov** [microsoft/vscode#128188]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

If an file being edited is under version control and has some lines deleted since last commit, the editor shows red triangle next to line numbers indicating the location of those deleted lines. It is very difficult to click on that red triangle to expand those deleted lines (maybe to revert this edit etc). It either does nothing or expands/ collapses code around if you have braces on that line (it does not relate to braces. If expanding/collapsing is not available, just nothing happens.) You have to aim carefully and click several times to succeed.

**Comment by joaomoreno** [comment]
It seems that the hover animation has been broken actually.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/146360
