### ISSUE TITLE
Display either folder or file icon in Explorer TreeView fails 

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#128129]
This is using VSCode 1.57.1
Also using the default VSCode File Icon Theme - seti 

I am attempting to use an existing VSCode icon and set the color of that icon in my Explorer TreeView.
I define a contributes / color this in my package.json like this:
```
{ 
	"id": "zmfFolder.color",
	"description": "Color for the Baseline, Package library icon",
	"defaults": {
		"dark": "#808bee",
		"light": "#152bee",
		"highContrast": "foreground"
	}
},
```
I then specify this in my TreeItem class:
```
const iconColor = new vscode.ThemeColor("zmfFolder.color"); 
this.iconPath = new vscode.ThemeIcon("folder", iconColor);

```
The result is that no folder icon is presented. The same occurs if I specify "file"
However, it appears that every other icon does work perfectly and is displayed in the correct color. 
For example if I replace folder with "paintcan" or "mute" -  it works fine. 
Notice that the line STEV001571 has no 'folder' icon.
![Capture](https://user-images.githubusercontent.com/46171060/124787451-58a17300-defd-11eb-83c1-54ab7ced034a.JPG)

I am referring to this list of available icons: 
[https://code.visualstudio.com/api/references/icons-in-labels](https://code.visualstudio.com/api/references/icons-in-labels)
where it states:
"...The Codicon library contains all the icons used in VS Code views, as well as a set of useful icons.
VS Code extensions can use these icons in labels, views, and **trees**..." 

Notice also , the hover over text for ThemeIcon states that the icons available are at the link provided - 
![Capture](https://user-images.githubusercontent.com/46171060/124801383-a624dc80-df0b-11eb-88d1-854b5e31566d.JPG)

This may be a defect in that "folders" and "files" icons are not being displayed correctly.

**Comment by isidorn** [comment]
Looks like a custom tree request, thus forwarding to @alexr00

**Comment by alexr00** [comment]
@davidkjackson54 are you using the built in file icon theme? The folder icon isn't displayed for folder in trees in that icon theme (https://code.visualstudio.com/api/extension-guides/file-icon-theme#file-association for more info). You can use a different file icon theme where the folder icon is set if you want to have folder icons show in tree (ex. the "Minimal" file icon theme can be set by running the command "Preferences: File Icon Theme").
