### ISSUE TITLE
unbound breakpoint for Angular project

### ISSUE THREAD

**Issue by Richardxp** [microsoft/vscode#128141]
I just created a new Angular project per (https://code.visualstudio.com/docs/nodejs/angular-tutorial), but once I click green debug and run button, all breakpoints became unbound. beside that, the app run well.

![image](https://user-images.githubusercontent.com/54648825/124790882-8c8a9180-df19-11eb-8f26-ba465c79183f.png)
![image](https://user-images.githubusercontent.com/54648825/124791192-d6737780-df19-11eb-9383-1bb28c643db3.png)
![image](https://user-images.githubusercontent.com/54648825/124791275-e9864780-df19-11eb-8332-9c1ca08ec12d.png)
![image](https://user-images.githubusercontent.com/54648825/124791309-f1de8280-df19-11eb-989f-6d32d7192f58.png)

I have tried downgrade vscode to 1.55, tried javascript debug nightly, tried install/uninstall debugger for chrome

thanks, appreciate your help
[vscode-debugadapter-3a110541.json.gz](https://github.com/microsoft/vscode/files/6778588/vscode-debugadapter-3a110541.json.gz)

**Comment by connor4312** [comment]
You have Angular running in a subdirectory, so you want to set webRoot to `${workspaceFolder}/ng-battleship`

**Comment by Richardxp** [comment]
got it. thanks.
