### ISSUE TITLE
Unable to Create any file or folder in left pane

### ISSUE THREAD

**Issue by SR-Sunny-Raj** [microsoft/vscode#128119]
Issue Type: <b>Bug</b>

Below steps were done to get this issue.

1. Create test folder 'Mongoose_stuffs' on C:.
2. On VS Code select File -> Open Folder and choose the folder you just created.
3. Right click in the left pane for the opened folder and try to create a file or a folder and it creates a file or folder but it just disappears within seconds or if we were able to write the name for the file or folder then it will exist but the name of the folder or file created will be upto the letters that we were able to write within seconds. Also I'm unable to rename the file or folder as whenever i clicks it, it just stays for sometime and then the cursor disappears.

VS Code Version: 1.57.1 (user setup)
OS: Windows_NT x64 10.0.19043

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (2.43GB free)|
|Process Argv|--crash-reporter-id 954b7751-b858-43f3-ad06-b3de887bfa18|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by SR-Sunny-Raj** [comment]
> Does the problem also happen after you run the command to reload with all extensions disabled?

NO, while all the extensions were disabled the problem no more persists.

**Comment by gjsjohnmurray** [comment]
Then I suggest you use the Start Extension Bisect command to find out which of your extensions is causing the issue. Then raise it with the extension developers.

/causedByExtension

**Comment by SR-Sunny-Raj** [comment]
Ok, thanks for helping me out.
