### ISSUE TITLE
Update: Support disabling auto updates

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#12817]
- VSCode Version: 1.5.3
- OS Version: macOS Sierra 10.12

Steps to Reproduce:
1. in "User Settings" set parameter "update.channel" to "none"
2. restart VSCode
3. check main menu "Code", item listed as "Check For Update" will be hidden

It seems that when you opt out of VS Code auto-updates there is no ability to check for updates manually, and I think there should be ability to check for updates manually.

Do not know is it bug or "feature"😏

**Comment by joaomoreno** [comment]
As designed

**Comment by joaomoreno** [comment]
@fzzr- Correctly points out that users want to disable auto updates, but keep the update functionality manual.

**Comment by dhulwells** [comment]
Is this issue still open? If so, I'll take it...
