### ISSUE TITLE
Continue from Call Stack does not work

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#128149]
## Environment data

- VS Code version: 1.39.2
- Extension version (available under the Extensions sidebar): master
- OS and version: windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7 (but N/A)
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): LS

## Expected behaviour

Should continue same as with hitting continue from the debug UI

## Actual behaviour

Does not continue when i hit continue using the continue button in the call stack window, see:
![issue8361](https://user-images.githubusercontent.com/3840081/68099128-b3a3dc80-fe75-11e9-882b-abbf6dc3043e.gif)

## Steps to reproduce:
Run this code:
```py
import concurrent.futures

FIBS = [28, 10]

def fib(n):
    print(n)
    if n < 2: # break-point here
        return 1
    return fib(n - 1) + fib(n - 2)

if __name__ == '__main__':
    with concurrent.futures.ProcessPoolExecutor() as executor:
        executor.map(fib, FIBS)
```

Note that to repro this we need debugger with multiproc support.

**Comment by weinand** [comment]
@karthiknadig with what version could you reproduce this?
I think we've fixed something in that area in Insiders

**Comment by karthiknadig** [comment]
@weinand I can confirm this is fixed in the following insiders version of VS Code:
```
Version: 1.58.0-insider (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:09:55.219Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by weinand** [comment]
@karthiknadig great, thanks a lot for verifying!
