### ISSUE TITLE
Handlebars comments coloring is sometimes off

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1281]
Have the following handlebars snippet 
Notice that the commented line is not fully green. Notice how git hub nicely colors the whole line

```handlebars
<table>
    <tr>
        <th>Band Name</th>
        <th>Date</th>
        <th>Album Name</th>
    </tr>
    <!--{{#each Bands}}-->
        <tr>
            <td>{{Name}}</td>
            <td>{{Date}}</td>
            <td>{{Albums.0.Name}}</td>
        </tr>
    {{/each}}
</table>
```

<img width="352" alt="screen shot 2015-12-14 at 15 28 52" src="https://cloud.githubusercontent.com/assets/1926584/11783401/6aa7ed04-a277-11e5-8e8b-820b3b0f0db1.png">

**Comment by aeschli** [comment]
This coloring looks correct to me. You can have a variable inside a comment. The handlebar transpiler comes first and will replace the content
