### ISSUE TITLE
Can't update extensions

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#128146]
Issue Type: <b>Bug</b>

Trying to force updates with the option ("Check for Updates") in the extension tab.
Error message is popping up: "XHR failed".

In the dev tools I see that the request failed, pointing to line 42 in "request.ts" `

![grafik](https://user-images.githubusercontent.com/2277182/124799845-47845080-df55-11eb-967d-1647b88e9c03.png)

![grafik](https://user-images.githubusercontent.com/2277182/124799999-6edb1d80-df55-11eb-8163-f03591d8d51a.png)

![grafik](https://user-images.githubusercontent.com/2277182/124800065-82868400-df55-11eb-99fd-bebf57c180d2.png)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.61GB free)|
|Process Argv|--crash-reporter-id 6ad73eb2-e24b-4305-a8ef-19341314fe6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
ifc-syntax|Ala|0.1.4
Bookmarks|ale|13.1.0
spellright|ban|3.0.58
change-color-format|bbu|1.1.0
gitignore|cod|0.7.0
aoe2-rms|del|0.3.3
rhinopython|des|0.1.11
dotfiles-syntax-highlighting|dot|0.1.0
vscode-gitignore-syntax|dun|0.1.2
EditorConfig|Edi|0.16.4
vscode-open-in-application|fab|1.0.6
auto-close-tag|for|0.5.10
remotehub|Git|0.10.1
gc-excelviewer|Gra|3.0.42
gdl|Gra|1.24.3
vscode-guid|hea|1.4.20
reg|ion|1.0.3
aoe2-aiscript|jvi|0.1.7
vscode-markdown-notes|kor|0.0.24
nim|kos|0.6.6
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.1
jupyter|ms-|2021.6.999662501
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
cpptools|ms-|1.4.1
hexeditor|ms-|1.7.1
powershell|ms-|2021.6.2
sublime-keybindings|ms-|4.0.9
resourcemonitor|mut|1.0.7
printcode|nob|3.0.0
material-icon-theme|PKi|4.8.0
polacode|pnp|0.3.4
run-on-save|puc|1.4.2
gruvbox-material|sai|6.4.5
sonarlint-vscode|Son|2.0.0
language-stylus|sys|1.11.0
vscode-open-in-github|sys|1.15.0
markdown-links|tch|0.8.0
open-in-browser|tec|2.0.0
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.5.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by deepak1556** [comment]
Do you see the issue with latest stable `1.58` ? If so, can you attach the network log following these steps,

* launch vscode with `code --log-net-log=<some-absolute-path>/netlog.json`
* Perform the steps that create the xhr failure
* Quit the application

**Comment by runxel** [comment]
@deepak1556 Hey there, thanks for asking!

I had 2 VSC windows opened. It looks like the one with the failing XHR was just stuck and remained at 1.57 which obviously broke some things there. After I force quit VSC and restarted everything seems to look fine and I can't reproduce the behaviour any longer.

So this is a classic "XY" bug:
**Instead of a broken XHR the update process seems to be broken when there is more than one VSC window opened.**
