### ISSUE TITLE
Don't remove a path from File -> Open recent when it temporarily disappears

### ISSUE THREAD

**Issue by benapetr** [microsoft/vscode#128107]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Darwin x64 18.7.0

vs code is trying to be too smart when it comes to recent projects - it automatically deletes a recent project from list when you try to open it in a moment when the path doesn't exist anymore - which may be just temporary issue when the path is sshfs or NFS location. Removal of project from recent projects is visible after restart of vscode, which is often necessary because it holds open file descriptors to network device which needs to be remounted. After restart the project is gone from recent projects and user must manually find the path to project again, which is annoying.

Steps to Reproduce:

1. Mount a device (preferrably a network device / smb, sshfs, nfs etc.) that contains your projects
2. Open one project
3. Open second project
4. Close second project
5. Improperly detach the network device - it will be still mounted but path won't be accessible, because vs code has some files in project open (file descriptors are left open in kernel) it's impossible to unmount the device
6. Open a new window in vs code and try to click second project in recent items - vs code will complain that path no longer exists and it will delete it from recent items (on disk, not in memory, item will still be visible in vs code interface until shutdown)
7. Because you can't remount the device while file descriptors are open, you need to shutdown the vs code in order to remount the device
8. Now remount the network device - paths are still same and now they work
9. Open vs code again - your projects are gone from recent items, you have to manually find them again (very annoying if path is too long).

Solution: don't try to be too smart - if item listed in recent projects can't be found, don't delete it from the list, it may start existing again when device where project is located is accessible again.

**Comment by TvdW** [comment]
:+1:, this is frustrating when working with WSL. If I reboot my computer and don't open a terminal prior to opening VS Code, the paths at `\\wsl$` aren't available yet and I have to open everything manually again.

**Comment by benapetr** [comment]
yeah but this is really probably a rare bug that is affecting small amount of users, I didn't know there is requirement that bug needs to get many upvotes for it to be considered for fixing, so this is unlikely to get solved.

Nonetheless if someone could point me to code that removes the recent item if it's not found on disk, I would love to remove it from my copy of vscode as a workaround.
