### ISSUE TITLE
WorkspaceConfiguration.update should warn when setting invalid values

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12811]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12614

Steps to Reproduce:

The following does nothing and doesn't warn:

```js
vscode.workspace.getConfiguration().update('terminal.integrated', false, true)
```

At the least I would expect a console message.

**Comment by jrieken** [comment]
@Tyriar Can you be a little more specific?

**Comment by bpasero** [comment]
@Tyriar you have to handle the error case of the promise you get:

![image](https://cloud.githubusercontent.com/assets/900690/18905103/c73f279e-8561-11e6-9be0-6e4efa7fbff9.png)
