### ISSUE TITLE
Improve default colors for inlay hints

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#128157]
## Problem

Inlay hints are currently pretty prominent in our default dark themes:

![Screen Shot 2021-07-07 at 1 40 00 PM](https://user-images.githubusercontent.com/12821956/124825742-e47cc480-df28-11eb-8a97-5a61a9d2cbcc.png)

I think we should try to make them less prominent by default, more like our code lenses while still making it clear that the hint text isn't actually part of the file

@rebornix Suggested potentially using the comment color for the inlay hints

**Comment by rebornix** [comment]
The reason I suggested using comment color is the trick we used to do

![image](https://user-images.githubusercontent.com/876920/124830443-b8644200-df2e-11eb-9213-66d54fd52b9e.png)

though we do want to make it look slightly different than a real comment to indicate is not editable / part of the code.

**Comment by misolori** [comment]
Here's a couple options playing with our default colors:

## Option A

This one adds a border and looks a little closer to our tooltips. I think this makes it a bit more obvious that the hints are not part of the text.

<img width="959" alt="CleanShot 2021-07-14 at 12 52 47@2x" src="https://user-images.githubusercontent.com/35271042/125684333-98fc5d3c-e535-416e-889b-3fbf18f62459.png">

## Option B

This removes the border and uses a softer gray to blend more with the content

<img width="957" alt="CleanShot 2021-07-14 at 12 53 00@2x" src="https://user-images.githubusercontent.com/35271042/125684367-e6da9f55-760a-4867-9487-fab14bc8b375.png">

## Option C

This one uses colors from the list widget to look different than the rest, a little stronger too

<img width="954" alt="CleanShot 2021-07-14 at 12 53 46@2x" src="https://user-images.githubusercontent.com/35271042/125684445-d10c86e8-3fe7-485c-8890-224da904e905.png">

**Comment by mjbvz** [comment]
I prefer B personally since it is the most subtle. Does it look ok on the other dark themes?

**Comment by misolori** [comment]
The hard part with the colors, and mostly in our color system as a whole, is that you can't reference colors from other parts of the editor. In Option B, I used the activity bar colors, but this isn't possible due to our import rules. So the next best color was using `badge.background` with an opacity to not be so strong:


https://user-images.githubusercontent.com/35271042/125702630-aab4bbc4-988d-4e70-8ea4-fb75f54df900.mp4

**Comment by narilee91** [comment]
How can I change inlay hints background color, color in settings.json?

**Comment by misolori** [comment]
@narilee91 you can use the following color tokens:

```json
    "workbench.colorCustomizations": {
        "editorInlayHint.foreground": "#fff",
        "editorInlayHint.background": "#ff0000"
    }
```

**Comment by misolori** [comment]
Pushed these changes to main, let's see what the feedback is about these defaults. The good thing is theme authors can still change these defaults so this is a solid base to start from.

## Dark
<img width="599" alt="CleanShot 2021-07-15 at 13 49 53@2x" src="https://user-images.githubusercontent.com/35271042/125855679-28d10a71-8ef5-4329-8917-f80b1f7463ff.png">


## Light
<img width="593" alt="CleanShot 2021-07-15 at 13 49 07@2x" src="https://user-images.githubusercontent.com/35271042/125855621-c0c6677f-75b4-4cfe-a21b-ed17e286cadd.png">

## Other themes
<img width="616" alt="CleanShot 2021-07-15 at 13 50 17@2x" src="https://user-images.githubusercontent.com/35271042/125855707-a8a21c9b-d13d-40e3-96dc-0f8f42e1d877.png">
<img width="585" alt="CleanShot 2021-07-15 at 13 50 41@2x" src="https://user-images.githubusercontent.com/35271042/125855772-3b7371bc-96fa-4f79-9bd2-39d867b61c2e.png">
<img width="616" alt="CleanShot 2021-07-15 at 13 51 01@2x" src="https://user-images.githubusercontent.com/35271042/125855804-727ac4d0-f470-4942-8344-5e8332ffd676.png">

<img width="584" alt="CleanShot 2021-07-15 at 13 51 13@2x" src="https://user-images.githubusercontent.com/35271042/125855835-f4389a29-72bd-49fb-8a51-71180ca7493d.png">
<img width="627" alt="CleanShot 2021-07-15 at 13 51 49@2x" src="https://user-images.githubusercontent.com/35271042/125855892-6d6eade4-9238-4b67-b96c-35d74b43f974.png">
<img width="621" alt="CleanShot 2021-07-15 at 13 52 39@2x" src="https://user-images.githubusercontent.com/35271042/125856001-c5fc0598-a077-4107-9ad9-0600559aeaf9.png">

**Comment by Kingwl** [comment]
Looks great! Thanks!
