### ISSUE TITLE
Integrated Terminal has large empty space when zooming out

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12810]
While testing #12519.
- VSCode Version: 1.6.0 insiders
- OS Version: MacOs

Steps to Reproduce:
1. open the integrated terminal
2. Command+Minus to zoom one level out

See screenshot:

<img width="729" alt="screen shot 2016-09-27 at 11 25 27 am" src="https://cloud.githubusercontent.com/assets/4674940/18886615/76b14c74-84a5-11e6-8257-53552609dba0.png">

**Comment by Tyriar** [comment]
Does not repro on Linux:

![image](https://cloud.githubusercontent.com/assets/2193314/18886796/4e11dea4-84a6-11e6-993e-d15cb9c55f32.png)

**Comment by pchomik** [comment]
I have same for:
vscode: 1.8.0
system: Ubuntu 16.04

I set zoomLevel to 1 and after that first line is cutoff.

**Comment by pchomik** [comment]
I found small workaround for this issue.
There is another configuration "terminal.integrated.lineHeight". I changed default value to 1.15 and now terminal look nice again.
This solution is not working if some shortcut is used to change zoom but it is working if zoom level is set in settings.json

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14479
