### ISSUE TITLE
Spurious "No task to execute found" info

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12814]
- VSCode Version: Code - Insiders 1.6.0-insider (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T12:46:15.113Z)
- OS Version: Darwin x64 15.6.0

Not sure how to reproduce. Happened twice while testing #12633. The Output panel with the Tasks channel would open and an info message box saying "No task to execute found" (or similar) would briefly show.

I was running tsc -w as a task and that process and its output in the Output panel have disappeared. So maybe tsc just hung up? The message should say so then and the Output panel should still show its output I'd expect.

**Comment by chrmarti** [comment]
Adding or removing .ts files seems to trigger tsc being restarted. Currently it restarts correctly (previously it didn't from what I remember), but I still get that info message box.
```
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["--sourceMap", "-w", "app.ts"],
    "showOutput": "silent",
    "isWatching": true,
    "problemMatcher": "$tsc-watch"
}
```

**Comment by chrmarti** [comment]
It doesn't restart when the tasks.json changes while tsc is watching, maybe that's by design. The info message box in the case where tasks.json has not changed and tsc restarts correctly is unexpected.

Does the problemMatcher do the restarting?

**Comment by dbaeumer** [comment]
@chrmarti did that happened during extension development. We have a hack in there that restarts the watching task on tsconfig.json changes since the tsc compiler doesn't honor those changes. Have to see if we can remove the hack for 2.0.3.

**Comment by dbaeumer** [comment]
I did some testing and the tsc compiler in watch mode now detects file adds and deletes as well. So we could remove the hack we have but would break people that still rely on 1.8.10. Need to check if I know about the tsc version

**Comment by dbaeumer** [comment]
I opt to leave the hack in for another milestone and then remove it.

**Comment by chrmarti** [comment]
It did not happen during extension development. I was working without a tsconfig.json at that time. I added/removed one of the .ts files app.ts depended on.

**Comment by dbaeumer** [comment]
That is correct. The hack is actually in the $tsc-watch problem matcher that we made along time ago for extension developement :-).

I leave the hack in but in October I will remove it.

**Comment by dbaeumer** [comment]
Moving to November. We have to keep that in for a little longer. Users could still have 1.8.10 in use.

**Comment by dbaeumer** [comment]
Will remove early 1.9.x

**Comment by dbaeumer** [comment]
I removed the hack for the new task execution engine that uses the terminal for January. Will close the issue although the terminal engine is not the default yet. You need to opt in.

**Comment by dbaeumer** [comment]
To Verify ensure that code like
```ts
let result: ITaskExecuteResult = (<any>task).tscWatch
	? { kind: TaskExecuteKind.Started, started: { restartOnFileChanges: '**/*.ts' }, promise: this.activeTaskPromise }
	: { kind: TaskExecuteKind.Started, started: {}, promise: this.activeTaskPromise };
```

Is not present in terminalTaskSystem.ts
