### ISSUE TITLE
Improve perceived loading of inlay hints

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#128159]
Possibly related to #125995

## Problem
While scrolling through a file with inlay hints, I notice the hints constantly popping in. This is distracting as it causes my code to be constantly shifting around.

TS computes inlay hints pretty quickly, so I think this is more an issue with our current implementation

## Ideas
Some ideas that may improve the perceived performance:

1. Cache inlay hints while scrolling through a file

     Inlay hints seem to always be recomputed as you scroll through a file. If the file hasn't changed, we should see if we can cache the previous hints and reuse them

2. Cache inlay hints when switching between files

    They also seem to be recomputed every time you switch between files, even if the file hasn't changed

3. Inlay hints only seem to be requested once scrolling stops

     On systems with momentum based scrolling, this means there is a delay between when code scrolls into view and when inlay are requested for it

**Comment by mjbvz** [comment]
Looks like there is also a fairly large delay when scheduling hint requests: https://github.com/microsoft/vscode/blob/f523f65f3985eb6493cae5d219de35f1d7ba6f7a/src/vs/editor/contrib/inlayHints/inlayHintsController.ts#L59

**Comment by jrieken** [comment]
>  like there is also a fairly large delay when scheduling hint requests:

Made the minimum waiting time much lower with 25ms

**Comment by jrieken** [comment]
There is still problems when typing (see https://github.com/microsoft/vscode/issues/125995) but scrolling and switching files should be much better now. 

https://user-images.githubusercontent.com/1794099/134184574-67bf5f86-2ba7-4c60-bc59-4931e2dacb23.mov

**Comment by jrieken** [comment]
Verify that

* inlay hints remain when switching between tabs
* inlay hints remain when scrolling up/down by a lot
* inlay hints show already when scrolling up/down by a little
