### ISSUE TITLE
Cmd+V not working in quickInput when webview opened in vscode 1.57.1

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode#128118]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.1
- OS Version: Mac OS Big Sur 11.4

Steps to Reproduce:

1. Install webview extension from https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample
2. Open the webview from Command Palette using `Start cat coding session`
3. Copy any text -> Open `Command palette` and paste text using `Cmd+V`, it wont paste the text.

**Its working in the following scenarios** 
- if you close the webview and repeat step 2 it works.
- it is working in vscode version 1.56.0
- it is working using Edit menu and selecting paste option

I have identified the problem when using [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client) extension.
Link to same issue created in extension page https://github.com/rangav/thunder-client-support/issues/254

Issue video link - https://www.loom.com/share/b175aaa8ebff4ed7a9f150e235a29a72

**Comment by gjsjohnmurray** [comment]
Similar to #127881

**Comment by rangav** [comment]
The same issue with search tab, quickInput other inputs paste not working when webview is opened
