### ISSUE TITLE
toggle find commands do not work in terminal editors

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#128152]

**Comment by rzhao271** [comment]
If I reload the window, then the command doesn't work again, until I use ctrl+F to show the find widget at least once. Then, if I close the find widget (or keep it open still), the command works.

**Comment by meganrogge** [comment]
I think that's expected ? @Tyriar

**Comment by meganrogge** [comment]
find gets closed for editors on window reload

**Comment by Tyriar** [comment]
I tried and it works as expected for me too:

1. Reload window
2. Run terminal toggle regex
3. Ctrl+f, regex is enabled
