### ISSUE TITLE
Vertical alignment of breakpoint decorations is off for non-default line heights

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#128172]
The vertical alignment is still off for non-default line heights. For an exaggerated height, for instance:

![](https://memes.peet.io/img/21-07-0d78652d-b331-4c7f-a3e0-932eaa03ec95.png)

_Originally posted by @connor4312 in https://github.com/microsoft/vscode/issues/124169#issuecomment-875974973_

**Comment by isidorn** [comment]
Thanks for finding this, I can look into a fix.

**Comment by isidorn** [comment]
We have to use `position:absolute` here for other reasons. So I tried to make the `top` more dynamic, to be percentage based, to use `vertical-align`. But nothing worked.
The only thing that will work I think is programatically listening editor line height and based on that change to update the `top` pixels. That would work but would not be the nicest.

I am open to suggestions if somebody has a better solution.

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-07-e85d0e2f-18a6-4ba2-93f2-1e5887f2367c.png)

**Comment by isidorn** [comment]
Smart! Thanks!
