### ISSUE TITLE
provide command to go to previous/next reference without open search editor or peek reference view

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#128105]
![image](https://user-images.githubusercontent.com/41773861/124721468-bbb1fa80-df3b-11eb-8239-b28b21ec6299.png)

**Comment by jrieken** [comment]
`editor.gotoLocation.multipleReferences` is the setting, than use to the "Go to XYZ" commands

<img width="693" alt="Screen Shot 2021-07-07 at 10 49 43" src="https://user-images.githubusercontent.com/1794099/124729813-0ff3b500-df11-11eb-8617-e0e19e106ffb.png">

**Comment by tjx666** [comment]
That doesn't satisfy my requirement. I don't want to change the behavior of `go to references`. I just want a new command to let me define the shortcut to navigate to previous/next reference
