### ISSUE TITLE
Cursor position in Source Control

### ISSUE THREAD

**Issue by nosjojo** [microsoft/vscode#128137]
Issue Type: <b>Bug</b>

This might only apply when submodules are in use.

The cursor location in Source Control will jump from the current position inside of the commit message field to another submodule's commit field after staging a file.

To trigger this:
1. Have a Source Control section with multiple submodules.
2. Edit one or more files in the first submodule so that they are modified and able to stage for a commit.
3. Hit the Stage / Stage All button for the file.
4. While the staging operation is running, start typing in the commit message field until the staging operation is completed.

What will happen - while typing your commit message, the cursor will jump to a different submodule commit message field when the staging process completes, and all text typed afterward is directed to that field instead of the intended commit field.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (21.22GB free)|
|Process Argv|--crash-reporter-id 06e9bb31-b3df-4039-a838-4f6b5f5bb3c9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.5.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.1
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
hexeditor|ms-|1.7.1
markdown-preview-enhanced|shd|0.5.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
aatestflight:30331711

```

</details>

**Comment by vvelkovski** [comment]
#135386

**Comment by bburns** [comment]
This also happens with a workspace with multiple folders, each with a git repo. It seems to happen when vscode runs git to see the changes, every 8 seconds or so - it jumps between the commit message boxes. Don't need to have any changes in the folders to see it.
