### ISSUE TITLE
In-product release notes design issues

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12816]
- VSCode Version: Code - Insiders 1.5.0 (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12520 

Since this will become one of the main ways users will consume release notes it should look good.

- No padding on page
- Link color is unreadable on some themes

  ![image](https://cloud.githubusercontent.com/assets/2193314/18887779/6d16a362-84aa-11e6-8cf3-0d714f92244a.png)

- `<code>` should use `editor.fontFamily`
- `kb()` annotations are not resolved

  ![image](https://cloud.githubusercontent.com/assets/2193314/18887807/9da7332a-84aa-11e6-98b9-077114c76949.png)

- No syntax highlighting

**Comment by joaomoreno** [comment]
Mainly build issue.
