### ISSUE TITLE
Contextual menus should have a context to better decide which menu options to show/hide

### ISSUE THREAD

**Issue by str** [microsoft/vscode#128161]
The context menu has way to many options. Go to definition, declaration, implementation. I never know which one to use

![image](https://user-images.githubusercontent.com/123817/124828465-8655de80-df34-11eb-809c-27bc86334819.png)

In theory the [context menu](https://en.wikipedia.org/wiki/Context_menu) should read the context to know which options to show instead of showing all options all the time. For example if I click on an  `if` statement, where should it go if I select the "go to definition"?    Shouldn't that option be shown only for variables and constants?

I [asked the plugin developer who added those options](https://github.com/bmewburn/vscode-intelephense/issues/1863) to the contextual menu and he comment that he only adds them but has no way to get the context to know if they should be added or not.

Is it possible to add more context about where the user right clicked to better filter what options to show/hide in the menu?

Thank you.

**Comment by jrieken** [comment]
> For example if I click on an if statement, where should it go if I select the "go to definition"? 

Unfortunately, the editor doesn't know what the meaning of "if" is, it only knows that there is one or more implementations for a "go to xyz" feature. To update said context keys extensions would need to eagerly push/update context keys as the cursor moves. To make matters more complicated: extensions run in a separate process and and the cursor might already be on a different word while extensions are still "thinking" about some other token.

**Comment by jrieken** [comment]
Closing this as 'wont-fix' - I do understand and agree with the challenge but there is no good solution
