### ISSUE TITLE
Remote-SSH extension initially fails to add additional folder to workspace

### ISSUE THREAD

**Issue by jimmyjayp** [microsoft/vscode#128174]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open VS Code and start a remote-ssh session. Open a folder on the remote, creating a workspace with one folder.
2. Select "Add Folder to workspace..." and select a second folder to add to the workspace.

This operation, for me, fails and I am looking at an unchanged session (workspace window).

Until.....

I quit and restart VS Code (on my mac - need to do a full %Q)

This will re-open all my windows, including the one with the remote session, except this time, the window for the remote session shows the modal asking me if I Trust the folder I added before I quit. Once I click "yes", everything is good.

**Comment by roblourens** [comment]
Works for me. After step 2, does the window reload?
