### ISSUE TITLE
Allow Alt-Z to toggle to `wordWrapColumn` when word wrap is defaulted `off`.

### ISSUE THREAD

**Issue by jpetkau** [microsoft/vscode#128133]
Issue Type: <b>Feature Request</b>

If `editor.wordWrap` is set to `off` in user settings, then Alt-Z and `View/Word Wrap` toggle to `on`, which wraps to viewport width.

If `editor.wordWrap` is instead is set to `wordWrapColumn`, then Alt-Z toggles it off, but word wrap also *defaults* to on. This is undesirable as a default for code windows.

There appears to be no way to have word wrap *default* to off, but still be able to toggle it to `wordWrapColumn` with Alt-Z for viewing the occasional long line, which I very often want to do.

One way to do this would be to make `Alt-Z` toggle to `editor.wordWrap=wordWrapColumn` instead of `editor.wordWrap=on` whenever `editor.wordWrapColumn` is set. Or there could be a new setting, `editor.wordWrap="wordWrapColumnOff"` which toggles to `"wordWrapColumn"`. (Or just remove the "off" enum from `editor.wordWrap`, and make `editor.wordWrapEnabled` its own boolean setting instead which is toggled by Alt-Z.)

[Edited because original description incorrectly said Alt-Z didn't work at all when defaulting to "off".]

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alexdima** [comment]
> If editor.wordWrap is set to off in user settings, then Alt-Z and View/Word Wrap have no effect, and word wrap cannot be easily toggled.

That is not the case for me. Does this reproduce for you when disabling all extensions? Here for example I am opening a TS file in a fresh VS Code and using Alt+Z to toggle word wrap on for the current file:


https://user-images.githubusercontent.com/5047891/125596043-3796f641-2710-49f9-a2d3-acb46acca8d7.mp4

**Comment by jpetkau** [comment]
> That is not the case for me. Does this reproduce for you when disabling all extensions? Here for example I am opening a TS file in a fresh VS Code and using Alt+Z to toggle word wrap on for the current file:

I did reproduce with extensions disabled and in insiders, but yes it turns out I misdiagnosed the problem because I used a really wide window.

Alt+Z _does_ toggle word wrap, but only to "on" (i.e. wrap to viewport width), not to "wordWrapColumn" which is what I was looking for. Since my view was wider than any of the lines I was testing with it looked like it was doing nothing. So I guess the request is actually more like: "if `editor.wordWrap` is set to default off, but `editor.wordWrapColumn` is set, then alt-Z should toggle to `"wordWrapColumn"` instead of `"on"`.

**Comment by alexdima** [comment]
Thank you for clarifying. Currently Alt+Z is only toggling viewport wrapping on or off for the current file and does this without writing to user settings. We added this command to the core of VS Code in order to cover some use-cases where people want to turn on viewport wrapping "on-the-fly", and only for a single file.

I think in your case an extension could be written with a command which uses vscode's configuration editing API to toggle the `editor.wordWrap` setting between `on` and `wordWrapColumn`.
