### ISSUE TITLE
restore the dedicated split window button

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#128142]
Removing the dedicated "split" button for the terminal was a mistake, please put it back. Having to right click an icon is the opposite of how icon buttons are supposed to behave: button icons are to be pressed and nothing else.

Also having it then CHANGE THE INTERFACE and remove that button, instead suddenly presenting a list is _super bad_, please restore the old behaviour where the UI stays the same, and buttons don't require right clicks or disappear. If you want to show a list of open terminals when there's more than one, that's fine, but _only_ add that list to the UI, don't _remove_ other parts of the UI at the same time.

**Comment by Pomax** [comment]
And add a bottom border, because this is just ridiculous:

![image](https://user-images.githubusercontent.com/177243/124794621-10d21a00-df04-11eb-8d18-f667d2fe652b.png)

**Comment by gjsjohnmurray** [comment]
Split button already seems to be back in 1.58 (Insiders) which is due to for general release later this week.

**Comment by gjsjohnmurray** [comment]
Re border, possible workaround is to set "terminal.background" to something sufficiently different from "panel.background"

**Comment by Tyriar** [comment]
Yep this is already all actioned, see settings under `terminal.integrated.tabs` to configure how the tabs list works or to disable it outright.

**Comment by Tyriar** [comment]
fyi @misolori about border on top of terminal comment
