### ISSUE TITLE
vscode.previewHtml appears to modify (or restrict) HTML/Javascript of the passed URI

### ISSUE THREAD

**Issue by kgentes** [Microsoft/vscode#12818]
- VSCode Version: 1.5.2
- OS Version: Win 7 SP1

Steps to Reproduce:

1. I have a working SPA that has no server calls and is simply a very basic Angular2 app that loads and renders data in nice HTML on the screen.  I take that app and build it (using webpack) into 2 files: index.html and a bundled Javascript file (the compiled Angular/TS stuff all crunched down into a single JS file).

2. I can run this single index.html file (with its included script directive:
`<script type="text/javascript" src="http://localhost:3000/app.bundle.f180d8c6cf341d2ce611.js">`
either via a local server or even just double clicking the index.html and rendering it as a file locally. Both work as needed.

3. My goal is to render this same index.html file via the vscode.previewHtml inside of an extension. So...

4. Built a simple extension for previewing custom JSON files, so that we can render an HTML page representing the JSON data. Ultimately, in the `extension.ts` file, the 'activate' function ends with the following code (Which is basically the standard /boilerplate for connecting the HTML preview command to my file type based extension (plus a lot of other code I won't post here for brevity):
```
    let open = vscode.commands.registerTextEditorCommand('myJSONviewer.open', (te, t) => {
        if (!checkmyJSONFile(te.document)) return;
        // else{
        //     vscode.window.showInformationMessage("It's an Good doc!!");
        //     return;
        // }
        

        provider.update(previewUri);
        return vscode.commands.executeCommand('vscode.previewHtml', previewUri, vscode.ViewColumn.Two)
            .then(s => console.log('done.'), vscode.window.showErrorMessage);

    });

    context.subscriptions.push(open);
```

5. the actual URI content is bubbled up in the myJSONDocumentContentProvider.ts (my implementation of the vscode.TextDocumentContentProvider ) by pushing this static HTML that links in javascript source. (Just in case there was a problem with how to reference the JS file, I tried replacing http://localhost:3000/app.bundle.f180d8c6cf341d2ce611.js with various things from file:// URLs etc, in case there was some context problem, but this local host one works to load the javascript and was no different than if I used a hard file:/ URL for the script) :
```
        return `<!DOCTYPE html>
<html>

<head lang="en">
    <base href="/">
    <title>My Prototype</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<bdp-app>Loading App...</bdp-app>
<script type="text/javascript" src="http://localhost:3000/app.bundle.f180d8c6cf341d2ce611.js"></script>
</body>

</html>`;
```

6. Everything in the extension works fine and the vscode.previewHtml is fired with the URI as specified. But when it is rendered in the pane, the preview loads the white back ground and fails as you see.
![image](https://cloud.githubusercontent.com/assets/5266827/18889011/baee837a-84af-11e6-8184-11ba20837ef7.png)

Something in the javascript has been hooked to try to look at a path (specifically beginning with Program Files etc), as you can see by the error.  None of the SPA does this, and it works on its own just fine, but it appears the vscode.previewHtml must be massaging the script or HTML string data somehow before it renders it, and thus produces this error.

7. If I change the URI string to use "http://localhost:3000/" for the base href, such as follows:
```
        return `<!DOCTYPE html>
<html>

<head lang="en">
    <base href="http://localhost:3000/">
    <title>My Prototype</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<bdp-app>Loading App...</bdp-app>
<script type="text/javascript" src="http://localhost:3000/app.bundle.f180d8c6cf341d2ce611.js"></script>
</body>

</html>`;
```

It now fails in a similar way but notice the source files have an entirely new pathing on the right.
![image](https://cloud.githubusercontent.com/assets/5266827/18889598/7a3116c4-84b2-11e6-9f3a-394b6c854b62.png)

 I am trying to understand how the URI data is handled by the vscode.previewHtml . I tried debugging into that, but because of the inability to set breakpoints (something about the extension debugger limits my ability to do this) at important locations, I can't see how to resolve this, or if it is a limitation of the vscode.previewHtml command and how it handles the HTML/JS code it is attempting to render.

**Comment by jrieken** [comment]
We don't modify the content in any way, the page is loaded inside an iframe which is inside a web view. You can debug the web view using the `_webview.openDevTools`-command. 

Modify your keybindings like so and you should be able to bring up dev tools for the preview (when it's visible/running)

```
{
        "key": "shift+cmd+j",
        "command": "_webview.openDevTools"
}
```

**Comment by kgentes** [comment]
Followup: The solution to the issue I was having was to change the header ref to be defined but with a null value. As in:

```
<html>

<head lang="en">
    <base href="">
    <title>My Prototype</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

If you use `<base href="/">` this will cause problems with loading a webpage that uses Angular2 (which mine was). If you use  `<base href="http://localhost:3000/">`  or other such URL, the local references to VS Code (for webview) begin to cause other failures for debugging.  The only one that works in all situations is : 

`<base href="">`

Kim
