### ISSUE TITLE
Rectangles in shape of selected cursor on terminal screen

### ISSUE THREAD

**Issue by turhanhuseynov** [microsoft/vscode#128111]
Issue Type: <b>Bug</b>

I have Vue project with nodejs backend. Whenever I start project, rectangles slowly appear more and more when I use terminal.
https://prnt.sc/198t9r3

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.74GB (4.63GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether --crash-reporter-id b599aa8e-558e-464e-b389-45da54688e2c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.6
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.1
jupyter|ms-|2021.6.999662501
powershell|ms-|2021.6.2
vetur|oct|0.34.1
vscode-thunder-client|ran|1.6.1
tabnine-vscode|Tab|3.4.12
unity-debug|Uni|3.0.2
format-all-files|xyk|0.2.0
mono-snippets|zra|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712
bridge0702:30333155

```

</details>

**Comment by meganrogge** [comment]
Looks like a problem with Chromium GPU acceleration in , you can try updating your graphics driver and if that doesn't work you can move to the DOM-based renderer with this setting:
"terminal.integrated.gpuAcceleration": "off"
/label terminal
