### ISSUE TITLE
Unclear how to delete a config value using WorkspaceConfiguration.update

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12812]
- VSCode Version: Code - Insiders 1.6.0 (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12614

I tried this but it set it to `null`:

```js
vscode.workspace.getConfiguration().update('terminal.integrated.cursorBlinking', undefined, true);
```

Not sure how to do it, I was expecting a `WorkspaceConfiguration.delete(key: string)` API?

**Comment by jrieken** [comment]
Yes - I like a dedicated `delete` method

**Comment by jrieken** [comment]
@bpasero Is there a way using the `IConfigurationEditingService` to remove a value?

**Comment by bpasero** [comment]
@jrieken the code that handles the update of JSON was written by @aeschli and when I pass in `void 0` as value for the setting it indeed seems to get removed from the file (not if I pass in `null`).

**Comment by jrieken** [comment]
makes sense `null` is a valid value while `undefined` isn't - it get messed up when sending over form the ext host

**Comment by jrieken** [comment]
yeah - somehow the marshalling process turns `undefined` into `null`. This message is received on the main side: 
```
"{"req":"69","rpcId":"mMainThreadConfiguration","method":"$updateConfigurationOption","args":[1,"editor.acceptSuggestionOnEnter",null]}"
```

which is caused by this funny `JSON.stringify` behaviour (learnt something today)

```
> JSON.stringify([1, 2, undefined, 4])
'[1,2,null,4]'
>
```

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/12812#issuecomment-250094424 - I changed my mind because a `delete` method would have the same needs for the global flag and I am not a big fan of it. 

I'll add a doc comment about unsetting a value
