### ISSUE TITLE
Transitioning from single-root to multi-root doesn't call extension deactivate

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#128138]
An activated extension doesn't get deactivated before transitioning to multi-root. After it transitions. it gets activated again without being deactivated the last time.

Steps to Reproduce:
1. Create an extension and use `console.log()` to log when the extension activates/deactivates. Also make it activate immediately. 

ie: I used the [Hello World Sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) and added a deactivate function and made it activate immediately. 
```
export function deactivate() {
	console.log("deactivated!");
}
```
```
"activationEvents": [
	"*"
],
```
2. Run the extension and open a workspace. 
3. Activate the extension.
4. Use the `Add Folder to Workspace...` option to transition to multi-root.
5. Notice that the extension activates again without deactivating 🐛

**Comment by alexdima** [comment]
`console.log` cannot be used as means to troubleshoot if `deactivate` is called. The console output is normally routed via the renderer process, but the renderer process is killed before the extensions deactivate. I suggest to use `fs` to check if `deactivate` is called or not.

**Comment by andreamah** [comment]
Looks like this still happens if I use fs to test. Instead of deactivating and calling console.log, I do the following:

```
export async function deactivate() {
	await wait(5000); //sync wait
	fs.writeFile('{path_to_dev_dir}\\newfile.txt', 'deactivate called', (err) => {
		if (err) throw err;
	});	
}

async function wait(ms: number) {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			console.log("Done waiting");
			resolve(ms);
		}, ms );
	});
}  
```

Notice that the file doesn't get created. Seems that deactivate isn't waiting for completion or finishing execution when it takes too long. Therefore, if the cleanup takes too long (ie: closing lots of webview panels), it doesn't get executed correctly when going from 1 to 2 workspaces.

**Comment by roblourens** [comment]
I suspect that deactivate should not be async. What are you doing that you need to wait on?

**Comment by andreamah** [comment]
I just wrote it to demonstrate that any cleanup that takes quite a while seems to not finish (ie: here with the file write). In my case, I want to close webview panels when `deactivate` is called because the extension suddenly deactivates when switching to and from multiroot

**Comment by andreamah** [comment]
From https://github.com/microsoft/vscode/issues/144118#issuecomment-1223109711:
@gjsjohnmurray 

> @andreamah this issue may be relevant to https://github.com/microsoft/vscode/issues/128138 which you commented on and reopened today. I couldn't add this comment there because when reopening it you forgot to unlock it.

**Comment by roblourens** [comment]
Looking at the code, I guess we do wait on promises from deactivate. They get 5s

https://github.com/microsoft/vscode/blob/074596031d14d512612cdea1f020ad78e88e946b/src/vs/workbench/api/common/extHostExtensionService.ts#L261-L262

So the problem in your test might be timing out or it might be that it doesn't wait on the fs call to complete.

In the real scenario, there might be a promise that isn't awaited, or a different issue.

**Comment by andreamah** [comment]
I still had the issue when deactivate was synchronous and I just closed a webview panel. it seemed like it was timing out still?

**Comment by andreamah** [comment]
Seems to be a problem with the webview panel I'm trying to dispose. Discussion moved to #158839
