### ISSUE TITLE
Create local terminal should open canonical folder

### ISSUE THREAD

**Issue by hikaruna** [microsoft/vscode#128113]
## expect
私達が"Create New Integrated Terminal"を実行した時、"localのopenedfolder"でterminalを開いてほしい。"localのopenedfolder"とは、"Remote-Containers: Reopen Folder Locally"と同じfolderが望ましい。

When we ran the "Create New Integrated Terminal", I want you to open the terminal in the "local of opened folder". The "local opened folder of", "Remote-Containers: Reopen Folder Locally" the same folder is desirable.

## actual
私達が"Create New Integrated Terminal"を実行した時、残念なことに、localのhomeでterminalが開かられてしまう。

We, when you run the "Create New Integrated Terminal", unfortunately, the terminal at the home of the local would be opened.

## 必要性 necessity
私がvscodeを使って特定のFolerで作業している時。
ほとんどののケースで、"Create New Integrated Terminal (local)"を実行した後に、手動でworking folderに移動する、不快な手間が発生しています。
"Reopen Folder locally"が可能なので、この機能も実現できるはずです。

When I'm working in a particular Foler using vscode.
In most cases, you'll have the unpleasant hassle of manually navigating to the working folder after running "Create New Integrated Terminal (local)".
Since "Reopen Folder locally" is possible, this function should be possible as well.

**Comment by Tyriar** [comment]
To verifier:

1. Open a folder using remote containers
2. Run the create Create New Integrated Terminal (Local) command, it should open a terminal at the actual path, not $HOME
