### ISSUE TITLE
Native Notebooks - Undo Not Working

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#128173]
- VS Code Version: 1.58.0-insider

Steps to Reproduce:

1. Put code in cell 1
2. Put code in a cell that is off screen, requires scrolling to see it (let's call this cell x)
3. Scroll back up such that cell 1 is back in sight and try to undo using ctrl z
4. Scroll back down to cell x and try to undo using ctrl z 

Actual Behavior: 
Undo doesn't work the first time and requires some scroll trial and error before it works

![undo broken](https://user-images.githubusercontent.com/19276747/124836381-bf438280-df37-11eb-9f29-527524e27886.gif)

**Comment by rebornix** [comment]
> I seem to be unable to undo a cell that got scrolled out of view.

This is actually a side effect of us changing the default value of `notebook.undoRedoPerCell`. When it's set to `true` (the default value), to undo a change in a cell out of viewport, users need to scroll to the cell and focus in the editor and then perform undo. When it's set to `false` (a window reload is required after changing the setting), the undo/redo of cells is on the same undo stack so you can still perform undo when the focus is on another cell.
