### ISSUE TITLE
Terminal icon and color do not disappear after killing the first terminal in a list

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#128168]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.58.0-insider (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-07T12:09:55.219Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

Steps to Reproduce:

1. Add a new terminal (no icon or color is visible)
2. Add a second terminal (icons and colors are visible for both terminals)
3. Kill the **first** terminal
4. The remaining terminal retains its custom icon and color: I would expect icon and color to disapper, similar to how the terminal looks at point 1
5. If instead I kill the _second_ terminal, icon and color disappear as expected

My terminal settings: 

```json
"terminal.integrated.defaultProfile.windows": "Powershell Preview",
"terminal.integrated.profiles.windows": {
    "Powershell Preview": {
        "path": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
        "color": "terminal.ansiMagenta"
    },
```

![terminal color 2](https://user-images.githubusercontent.com/5784415/124833572-3fb3b480-df33-11eb-9b58-df611ce3afbf.gif)

**Comment by meganrogge** [comment]
same root cause as https://github.com/microsoft/vscode/issues/127573

**Comment by Tyriar** [comment]
Here's the right issue I think: https://github.com/microsoft/vscode/issues/128236
