### ISSUE TITLE
I tried to install github theme in vs code it pops up this error "Couldn't find a compatible version of GitHub Theme with this version of Code."

### ISSUE THREAD

**Issue by MohamedEzzat2181** [microsoft/vscode#128177]

**Comment by IllusionMH** [comment]
/needsMoreInfo
What is your vscode version?

**Comment by MohamedEzzat2181** [comment]
> /needsMoreInfo
> What is your vscode version?

![image](https://user-images.githubusercontent.com/32748308/124848917-17ad6b00-df9e-11eb-880c-075975a0a78b.png)

**Comment by IllusionMH** [comment]
/question

Your version is almost 4 years old, so not a lot of extensions/themes would support it.
Theme in question requires VS Code 1.43 and later
https://github.com/primer/github-vscode-theme/blob/master/package.json#L22

You should really download and install latest version if possible https://code.visualstudio.com/Download
