### ISSUE TITLE
Containing directory appears empty when opening code-workspace with open file in folder with query parameter in uri

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#128151]
Issue Type: <b>Bug</b>

[Our extension](https://github.com/intersystems-community/vscode-objectscript) contributes a FileSystemProvider for the isfs scheme. When opening a workspace that contains a file open in a virtual `isfs` folder with a query parameter in the folder uri, the directory that contains the open file appears empty in the file explorer. For example, if the code-workspace file contains this:
```json
{
    "folders": [
        {
            "name": "iris5:USER",
            "uri": "isfs://iris5:USER/?type=cls"
        }
    ],
    "settings": {
        "objectscript.showExplorer": false
    }
}
```
and we have a file `User.test.cls` open in the workspace from our last session, the `User` folder in `iris5:USER` will look like this when the workspace is opened: 

![Screen Shot 2021-07-07 at 1 54 41 PM](https://user-images.githubusercontent.com/44776135/124807561-e1cf9e80-df2b-11eb-8b78-999ae4a4320f.png)

When the codeworkspace file contains this:
```json
{
    "folders": [
        {
            "name": "iris5:USER",
            "uri": "isfs://iris5:USER/"
        }
    ],
    "settings": {
        "objectscript.showExplorer": false
    }
}
```
the `User` folder in `iris5:USER` will look like this when the workspace is opened:

![Screen Shot 2021-07-07 at 2 04 02 PM](https://user-images.githubusercontent.com/44776135/124807818-3410bf80-df2c-11eb-8ea5-75d4a8e5cbcc.png)

We expect to see the files in the `User` folder whether the query parameter is present or not. Clicking the refresh icon causes the files in the directory to flash temporarily then disappear again.

I added some logging to our extension and noticed that when the open file upon workspace load is in a folder without a query parameter, I see that `readDirectory()` in the FileSystemProvider gets called on that file's parent folder. When the open file is in a folder with a query parameter, `readDirectory()` never gets called on the containing folder. I have verified that this happens with any query parameter, not just `type`. 

This issue appears to have been introduced in 1.55.0. Another one of our developers confimed that he is unable to reproduce it in 1.54.3. I looked through all issues and PRs tagged with the March 2021 milestone but didn't find any that were clearly related to this. The following 3 are the closest I could find:
- #115840
- #116856
- #117206

For full context, see the [original issue](https://github.com/intersystems-community/vscode-objectscript/issues/615)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (13.48GB free)|
|Process Argv|--crash-reporter-id 8728ef25-68c4-4e80-aafe-921e2dc7ba3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
servermanager|int|2.0.5
vscode-objectscript|int|1.0.12
language-server|int|1.2.2
vscode-docker|ms-|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0702:30334633

```

</details>

**Comment by bpasero** [comment]
This needs a minimal reproducible extension generated via `yo code` for us to look into. This extension contains a simple fs provider (maybe based on the in memory one from us: https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample).

**Comment by isc-bsaviano** [comment]
@bpasero I was able to reproduce the issue using the `fsprovider-sample` extension. Here are the steps I followed:

1. Create this workspace file:
```json
{
	"folders": [
		{
			"name": "MemFS - Sample",
			"uri": "memfs:/?test=1"
		}
	],
	"settings": {}
}
```
2. Open that workspace with the `fsprovider-sample` extension enabled and use the command to generate some files.
3. Once the files generate, open a file in `folder` in a non-preview editor tab.
4. Open a file in `large` or `xyz`. Your window should now look like this:

![Screen Shot 2021-07-08 at 10 21 19 AM](https://user-images.githubusercontent.com/44776135/124939297-fd43b380-dfd6-11eb-8129-d64c1f8515f2.png)

5. Now click on the tab for `file.ts` to make it active. You should see the 3 files under `folder` disappear, but the arrow next to it is still showing that it's expanded:

![Screen Shot 2021-07-08 at 10 22 42 AM](https://user-images.githubusercontent.com/44776135/124939396-10568380-dfd7-11eb-829f-a8f56bde5ce9.png)

6. Clicking the refresh button causes the files to flash, then disappear again. 
7. Clicking the arrow to collapse or expand `folder` has no effect.

I can provide more information if it would be helpful. Thanks for looking into this.

**Comment by bpasero** [comment]
@jrieken need your advice here. Internally the file service is using a ternary search tree to figure out when to stop resolving a file tree:

https://github.com/microsoft/vscode/blob/994a6c197b5a15d7b9523cb6dfd17f1dbbcb7772/src/vs/platform/files/common/fileService.ts#L197-L219

The idea is that the explorer would give a set of URIs to resolve to based on which nodes are expanded in the explorer and the file service resolves all stats for all expanded nodes.

This works fine for URIs without query param, but seems to break otherwise. See this test:

```ts
test('TernarySearchTree - for URI with query (#128151)', function () {
	let trie = TernarySearchTree.forUris<true>();

	const uriWithoutQuery = URI.from({ scheme: 'memfs', path: '/large/somefile.txt' });
	trie.set(uriWithoutQuery, true);
	assert.strictEqual(Boolean(trie.findSuperstr(dirname(uriWithoutQuery))), true);

	const uriWithQuery = URI.from({ scheme: 'memfs', path: '/large/somefile.txt', query: 'test=1' });
	trie.set(uriWithQuery, true);
	assert.strictEqual(Boolean(trie.findSuperstr(dirname(uriWithQuery))), true);
});
```

If this is intentional, then I will have to change my usage of the ternary search tree to store and search URIs where the `query` (and possibly `fragment` too?) parts are set to `undefined`.

**Comment by jrieken** [comment]
> If this is intentional, then I will have to change my usage of the ternary search tree to store and search URIs where the query (and possibly fragment too?) parts are set to undefined.

It always depends on the scheme but generally the `query`-part of a uri is important and nothing that should be ignored, like `http://duckduckgo.com/?q=blue` is something different than `http://duckduckgo.com/q=red`, the same is IMO true for hierarchies, e.g `foo://bar/bazz?includeDotFiles=true` is different than `foo://bar?includeDotFiles=false`. @bpasero if you want to make that decision then that's up to you.

> This issue appears to have been introduced in 1.55.0. Another one of our developers confimed that he is unable to reproduce it in 1.54.3.

I am unaware of any changes in this area but maybe file service or explorer folks do. I know that there are queries and fragments in the `file` protocol but for all other file systems it's up to the implementors of those (and the mem-fs sample is not good/complete in that respect).

**Comment by isc-kiyer** [comment]
@jrieken Thank you for weighing in. I originally found this bug on [our extension](https://github.com/intersystems-community/vscode-objectscript) along with @isc-bsaviano and some other developers. What would be the next steps here?

> (and the mem-fs sample is not good/complete in that respect)

If this is not a good example, what would be a good way to debug further on either that extension, our extension or some other extension?
This bug is quite frustrating for our developers so would like to get to the bottom of it ASAP. Happy to help in any way I can!
