### ISSUE TITLE
Cannot focus terminal editor find with mouse after opening it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128158]
Repro:

1. Open terminal editor
2. ctrl/cmd+f
3. Click terminal
4. Click find text box

![recording (37)](https://user-images.githubusercontent.com/2193314/124827198-99fc4780-df2a-11eb-851a-c9b7b0360f56.gif)

**Comment by meganrogge** [comment]
looks like it's focusing the terminal instead

**Comment by meganrogge** [comment]
also seeing this 
![recording (26)](https://user-images.githubusercontent.com/29464607/124833500-214db900-df33-11eb-8b2c-b3b002fcfd3a.gif)

**Comment by Tyriar** [comment]
This was difficult to figure out but I got it, it was happening because the find widget was not build to live under the xterm element, but it needs to be a sibling.
