### ISSUE TITLE
Wrong path seperator when use `git bash` as default terminal

### ISSUE THREAD

**Issue by speedoops** [microsoft/vscode#128191]
Issue Type: <b>Bug</b>

When use git bash on vscode windows, vscode show that I don't have pip8 installed, and it give a suggestion. When I click `Install` it will auto run a command. But it did't use a proper path seperator.

```
Somebody@2-vt0003 MINGW64 /d/CodeBase/codescan (master)
$ c:/Python27/python.exe c:\Users\Somebody\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py pip install -U autopep8 --user
C:\Python27\python.exe: can't open file 'c:UsersSomebody.vscodeextensionsms-python.python-2020.12.424452561pythonFilespyvsc-run-isolated.py': [Errno 2] No such file or directory
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz (4 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 7d069a78-8339-4e50-9508-bbd887e13252|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-graphql-client|alg|0.0.4
replacerules|bhu|0.4.1
markdown-table-prettify|dar|3.4.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vscode-powertools|ego|0.64.0
prettier-vscode|esb|8.0.1
code-runner|for|0.11.4
go|gol|0.26.0
todo-tree|Gru|0.0.213
rest-client|hum|0.24.5
plantuml|jeb|2.15.1
vscode-nuget-package-manager|jmr|1.1.6
markdown-toc|jof|1.4.0
graphql-for-vscode|kum|1.15.3
powershell|ms-|2021.6.2
quicktype|qui|12.0.46
pretty-graphql|soo|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335172
bridge0702:30334633

```

</details>

**Comment by meganrogge** [comment]
Please file this issue in the python extension repo
