### ISSUE TITLE
Unclear how to edit values in launch.json and tasks.json

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12813]
- VSCode Version: Code - Insiders 1.6.0 (f62883f07422cae4b53c2a185b105091460a0a85, 2016-09-27T13:07:11.616Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12614

The test mentioned I can edit launch.json and tasks.json but I couldn't figure out how to. I did the following:

1. Inspected the object returned from `vscode.workspace.getConfiguration()`, no `'tasks'` key

  ![image](https://cloud.githubusercontent.com/assets/2193314/18887215/118ff194-84a8-11e6-9636-d24975c8ea1e.png)

2. Had another look at interface WorkspaceConfiguration in `vscode.d.ts`
3. Did a text search of `vscode.d.ts` for `tasks`
4. Gave up

**Comment by jrieken** [comment]
Needs doc and obviously one or both of those files
