### ISSUE TITLE
Markdown Preview View Has Incorrect Size With Zooming

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12824]
- VSCode Version: 1.6 Insiders
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open markdown preview of document
2. Zoom in or out

![sep-27-2016 14-25-20](https://cloud.githubusercontent.com/assets/12821956/18892404/3f734ece-84be-11e6-80b1-5e4792203df0.gif)

When zooming in, the markdown preview pane shrinks in the editor window (see location of scrollbars). When zooming out, the preview document grows beyond the editor window and the scroll bars are hidden.

**Comment by jrieken** [comment]
dup of #5745
