### ISSUE TITLE
Module not found error autoreload \r

### ISSUE THREAD

**Issue by avinash-mishra** [microsoft/vscode#128276]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.0
- OS Version: Windows 10

Steps to Reproduce:

1. Inside jupyter notebook when I write following two lines of code. 
```
%load_ext autoreload
%autoreload 2
```
To support auto reloading of updates in another class. Then I get error. 

module not found error autoreload \r

**Temporary solution**:
As a temporary solution I open jupyter notebook as a json file inside any editor and replace \r\n with \n. 

This issue I started facing in new style of notebook where we can go to source code as well. Please have a look.

**Comment by rebornix** [comment]
@joyceerhl @DonJayamanne can you help me understand this issue? I'm not sure why line break matters in this case.
