### ISSUE TITLE
Comments mess with syntax highlighting on the next line in TypeScript

### ISSUE THREAD

**Issue by ryanechternacht** [Microsoft/vscode#12825]
- VSCode Version: 1.4.0
- OS Version: win10
- Language: TypeScript

Steps to Reproduce:
comments (//) seem to mess with syntax highlighting of the next line (see image)

Expected Behavior:
I expect 'dismiss' to be colored similarly to 'close'

![capture](https://cloud.githubusercontent.com/assets/1644554/18893240/018ca80e-84db-11e6-97ac-3c6fa673db4b.PNG)

**Comment by waderyan** [comment]
@ryanechternacht thank you for opening this issue. We fixed over 200+ issues with grammar with this extension (in beta now, will be bundled with product in the future). Can you install the extension and see if it solves your issue? 

If it doesn't solve your issue, please open an issue in this repo - https://github.com/Microsoft/TypeScript-TmLanguage/issues
