### ISSUE TITLE
Workspaces: expose `transient` property in workspace context service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128280]
Last milestone I introduced `transient` workspaces (https://code.visualstudio.com/updates/v1_58#_transient-workspaces). The main use case is for LiveShare for guest sessions.

Currently we are not really aware of a workspace being transient in the workbench itself, we only check on the `electron-main` side. But we have some motivation to understand transient workspaces in the workbench:
* for trusted workspaces (cc @lszomoru)
* for controlling hot exit and backups

I am mainly interested in the latter: I would like to implicitly disable hot exit in transient workspaces because the idea is that transient workspaces never restore and in that case backups should not be accumulated.

Can we have a `transient` property somewhere here on the `IWorkspace` object: 

https://github.com/microsoft/vscode/blob/ddbc8ae408c817edd4c2bba1a5ed2f9ba8a5de09/src/vs/platform/workspace/common/workspace.ts#L95-L111

Does that make sense or is there maybe another interface that is more specific to multi root workpsaces?

**Comment by sandy081** [comment]
added `transient` property to IWorkspace` 

https://github.com/microsoft/vscode/blob/a0a448f344bc8c068deb1202708dfc1e7c17ef89/src/vs/platform/workspace/common/workspace.ts#L112-L112

**Comment by bpasero** [comment]
Thanks!
