### ISSUE TITLE
Using terminal.show (regardless of params, true or false or nothing) always takes focus

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode#128289]
According to the documentation, if calling show(true), the terminal will be made visible but it won't capture the keyboard focus. I also remember in the past this worked. For some months already I noticed that regardless of how I call show, the focus is always taken.
Anything changed? Is there already an issue that you tracking for this? Am I doing anything wrong?

Related to this, if we won't manage to fix this behavior, how can we make key bindings for commands to be recognized even when the terminal has the focus? For example, when having focus in the terminal, if I press F5 debugging will start. The terminal will not try to write something for "F5". But if I run another key combination that I defined for some extension command, the terminal will react to the key combination (will try to write something) and the command will not be triggered (unless focus is somewhere else).

We have this issue in the CMake Tools repository and the user would be happy if we fix this problem either way.

https://github.com/microsoft/vscode-cmake-tools/issues/1974

**Comment by danila-grobov** [comment]
Hey, I would like to work on this issue. Could you give me any pointers? Where should I start?

**Comment by Tyriar** [comment]
@danila-grobov this one's a little involved as it needs an extension to trigger the issue, you'd be better off finding an issue with the help wanted label.

**Comment by danila-grobov** [comment]
Okay, thanks!

**Comment by alexr00** [comment]
Tried this in an extension after making sure I had a terminal open:
```
vscode.window.terminals[0].show(true);
```

And the focus moved into the terminal.

**Comment by meganrogge** [comment]
did you have focus in the terminal before running that? preserve focus should return the focus to whatever was focused before. 

![recording (101)](https://user-images.githubusercontent.com/29464607/144480012-579bd29c-a5af-4411-9dc4-311aa2137a1c.gif)

**Comment by alexr00** [comment]
![recording (72)](https://user-images.githubusercontent.com/38270282/144581605-6defb4da-8274-408a-a6a4-699b0c308afe.gif)

**Comment by meganrogge** [comment]
This is happening because focus never gets passed in to openComposite here

https://github.com/microsoft/vscode/blob/3febecac20f00eedbbcc13348ea27146f4d60eeb/src/vs/workbench/browser/parts/views/viewsService.ts#L236-L258
