### ISSUE TITLE
After updating the vscode, cppvsdbg can no longer be used.

### ISSUE THREAD

**Issue by cjxx2016** [microsoft/vscode#128288]
{
            "name":"RL",
            "type":"cppvsdbg",
            "request":"launch",
            "program":"D:/cj_work/RL.exe",
        },
can't debug anymore, after i update 1.58

**Comment by slier81** [comment]
i concur...this is bug..
i cant build my `zig` project at all..it used to work with previous vscode version

**Comment by jomerwe** [comment]
Experiencing the same issue.

Executable compiles but cppvsdbg just silently fails.

**Comment by jomerwe** [comment]
Experiencing the same issue.

Executable compiles but cppvsdbg just silently fails.

**Comment by Rob1B** [comment]
I had the same issue this morning. I tried to debug a rust project and cppvsdbg just fails.

Downgrading vscode did not solve the problem. I succeed with downgrading the C/C++ extension which had an auto-update 2 hours ago. The issue is maybe with the extension and not vscode.

**Comment by slysherz** [comment]
Seems to have been fixed already, let's wait for the new release: https://github.com/microsoft/vscode-cpptools/issues/7808

**Comment by cjxx2016** [comment]
> Seems to have been fixed already, let's wait for the new release: [microsoft/vscode-cpptools#7808](https://github.com/microsoft/vscode-cpptools/issues/7808)
> 
> EDIT: the fix is already out, go to the extensions tab, click `...` -> Check for Extension Updates. Then update the C/C++ extension, and now it should work correctly.
