### ISSUE TITLE
Add an option to group global search results by top-level directory

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode#128247]
In my work environment, I started out having a multi-root workspace with all of the roots being only a few folders out of a parent directory that contains many others. Recently I found a way to reconfigure this workspace into one that uses the parent directory as the sole root and only includes the same folders as before by excluding all of the unwanted stuff, and I am currently getting used to the differing practicalities of this setup vs. the previous one.

One of the benefits of the previous multi-root workspace was that global search results were grouped by root, so the root itself could be expanded or collapsed and all search results within the root would be revealed or hidden appropriately. I would love a way to do that with this workspace as well, where each top-level subdirectory of the root is its own group containing all search results within itself and can be collapsed and expanded as such. It's inconvenient to have every single file containing search results be listed at the same level where I must scroll down a long way just to find the one I'm looking for. The only current workaround is to type a file path or extension into the "files to include" field.

**Comment by roblourens** [comment]
This is also quite similar to https://github.com/microsoft/vscode/issues/20224
