### ISSUE TITLE
Native Interactive - Cell history inconsistent behavior

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#128248]
## Environment data
- Version: 1.58.0-insider
- Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
- Date: 2021-07-07T12:08:00.172Z
-  Jupyter Extension version: v2021.8.1007436305
-  Python Extension version: v2021.7.992362372-dev
-   OS: OSX 11.4
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used: poetry
-   Jupyter server running: Local

When using arrow keys to move through previously executed cells, the most recent cell seems to require a second `up arrow` press even when the cursor is at the start of the cell. This makes it a bit hard to know exactly what the behavior will be depending on where you are in the cell history.

Notice how at `00:13` I need to press `up arrow` twice to move from `test3` to `test2`, but only once to `test`:

https://user-images.githubusercontent.com/29611875/124806120-2dc11a00-df11-11eb-8c45-7ffa151ab613.mp4

This is a simple example, so I'm not sure if its necessarily always the last cell only. In general things feel a bit *weird*, can't tell if I'm also needing to double press to move through other cells in the history.

(related functionality request, but not this specific bug):
In my opinion, it would be best if a single `up/down arrow` press moved to the previous cell if cursor is on the top/bottom-most line, as opposed to jumping to the start/end of the line, (how it worked in the old webview interactive).

## Expected behaviour

- single `up arrow` press moves to previous executed cell

## Actual behaviour

- last executed cell requires two `up arrow` presses

**Comment by rebornix** [comment]
Agree that it's weird that the first arrow move cursor to the beginning of the line and then second arrow change history.
