### ISSUE TITLE
executeCommand to search extensions

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#128278]
We are integrating [vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp) into [vscode-R](https://github.com/REditorSupport/vscode-R) (see https://github.com/REditorSupport/vscode-R/issues/691). To avoid the conflict of two language servers running at the same time, we do not start the language service if vscode-r-lsp is detected to be enabled for the workspace, and we'll show a message to suggest that `REditorSupport.r-lsp` be disabled or uninstalled and show the extensions to make it easier for user to do so.

However, I can only find the commands such as `workbench.extensions.action.showEnabledExtensions` but I don't see a way to search installed extension specifically for `REditorSupport.r-lsp` which we are suggesting to disable. The [source code](https://github.com/microsoft/vscode/blob/776bd3d6d02dac6877a47772ad2bc72c4dcf37b0/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L986) of the command seems to hard code the search term and do not accept other search terms as arguments.

I wonder if there is an existing API or command to let me search a specific extension by identifider and show it in the extensions, just like typing "@enabled r-lsp" in the search box in extensions view?

**Comment by usernamehw** [comment]
```js
// Open extension preview
commands.executeCommand('commands.openExternal', Uri.parse('vscode:extension/reditorsupport.r-lsp'));

// Open Extensions View
commands.executeCommand('workbench.extensions.search', '@installed r-lsp');
```

**Comment by renkun-ken** [comment]
Thanks! It works perfectly.
