### ISSUE TITLE
[feature request] recommended workspace settings via `"settings.recommended.json"`

### ISSUE THREAD

**Issue by ZacharyPatten** [microsoft/vscode#128226]
# Feature Request: add a way to recommend settings when users open content in VSC (without forcing settings on users)

We currently have `extensions.json` files, so that when content is opened in VSC, the user will be prompted to install the extensions from the `extensions.json` file. This is a great feature, but I wish the same feature existed for workspace `settings.json`.

It would be nice if we could make a file (perhaps something like `settings.recommended.json`) so that when a user opens our content in VSC, they will be prompted to copy the settings from `settings.recommended.json` to the workspace `settings.json` file.

## Visuals

Here is what the prompt looks like when a user opens a workspace with an `extensions.json` file:
<img src="https://user-images.githubusercontent.com/3385986/125007525-5db20f80-e02e-11eb-8f53-f37ffd0fef2a.png" height="250"/>

What is this issue proposing? The same thing as above but for settings rather than extensions. Here is a mock-up of what it could look like:
<img src="https://user-images.githubusercontent.com/3385986/125007882-458ec000-e02f-11eb-9d1b-dc716efa0ae7.png" height="250"/>
If the user clicks `Apply` in the prompt, the content would be copied from `settings.recommended.json` to `settings.json` applying the settings in workspace.

### Source Control

We can already include a `settings.json` file with our code to automatically apply settings when a user opens our content in VSC, but that is forced. Users cannot opt in-to/out-of an included `settings.json` file. This causes an issue with source control where if you want to have default settings on a code base you have to include the `settings.json` but users that don't want to use the default settings must exclude their `settings.json` changes when they commit. Having a `settings.recommended.json` would mean we could commit that file, `settings.recommended.json`, to source control while `.gitignore`-ing the `settings.json` file.

### Having Recommended/Default `settings.json` Is Nice <em>(especially for new/inexperienced developers)</em>

- When a developer first opens my content, rather than bombard them with a verbose file structure, it is nice to filter out unnecessary directories/files and guide them to the code/files that are important. Such as:
  ```json
  "files.exclude":
  {
  	".gitignore": true,
  	".vs": true,
  	"**/bin": true,
  	"**/obj": true,
  	".github": true,
  	".vscode":true,
  },
  ```

- Also, "semantic highlighting" is disabled by default. I have projects coded in C#, and in order to help new developers out, I include the following in my `settings.json` file:
  ```json
  "csharp.semanticHighlighting.enabled": true,
  ```

- Also, color/theming is nice to recommend. As a C# developer, I especially prefer to have different colors for each type-of-types in my IDE/Editor. By this I mean a different color for `struct`s, `class`es, `delegate`s, `interface`s, and `enum`s. I also like to have a similar but noticeably distinct color for `methods` vs `extension methods`. If I post screenshots on blogs/social-media/documentation, it is easier for users to recognize the screenshot when they open the code if they share the same color/theme. **_However, color/theme is probably the biggest thing that users will want to opt-out-of._** It is nice to recommend color/theme to absolute beginner programmers in C#, but for someone who is already experienced with C#, they don't want to be forced to use other people's settings. This is why we really need a `settings.recommended.json` file proposed in this issue. An experienced C# dev can ignore the prompt to apply the default settings of the content when opened in VSC.
  <details>
  <summary>
  :page_facing_up: <strong>Color/Theme Settings I Use In My C# <code>settings.json</code>s <sub>[Expand]</sub></strong>
  </summary>
  <p>
  
  ```json
  "workbench.colorTheme": "Default Dark+",
  "editor.semanticTokenColorCustomizations":
  {
  	"[Default Dark+]":
  	{
  		"enabled": true,
  		"rules":
  		{
  			"class": "#4EC9B0",
  			"comment": "#57A64A",
  			"controlKeyword": "#569CD6",
  			"delegate": "#BD63C5",
  			"enum": "#FF7F27",
  			"enumMember": "#ffffff",
  			"event": "#ffffff",
  			"excludedCode": "#9B9B9B",
  			"extensionMethod": "#CB859B",
  			"field": "#ffffff",
  			"interface": "#B8D7A3",
  			"keyword": "#569CD6",
  			"label": "#ffffff",
  			"local": "#ffffff",
  			"method": "#BD6380",
  			"namespace": "#ffffff",
  			"number": "#B8D7A3",
  			"operator": "#ffffff",
  			"operatorOverloaded": "#ffffff",
  			"parameter": "#ffffff",
  			"plainKeyword": "#569CD6",
  			"preprocessorKeyword": "#9B9B9B",
  			"preprocessorText": "#ffffff",
  			"property": "#ffffff",
  			"punctuation": "#ffffff",
  			"string": "#D69D85",
  			"stringVerbatim": "#D69D85",
  			"struct": "#FFFF80",
  			"typeParameter": "#808000",
  			"variable": "#ffffff",
  			"xmlDocCommentComment": "#56a64a7c",
  			"xmlDocCommentText": "#9B9B9B",
  			"xmlDocCommentAttributeName": "#9B9B9B"
  		}
  	}
  }
  ```
  
  </p>
  </details>

These were just examples I have personal experience with, but there are tons of settings of course _(cough... tabs/spaces... cough...)_.

**Comment by ZacharyPatten** [comment]
I just want to mention one implementation detail that I forgot to explicitly mention above. The `settings.json` file allows comments. I would like it if the comments from `settings.recommended.json` file were retained when the content is applied to `settings.json`.

Here is one possible example, but there are many examples I could think of:
```
"files.exclude":
{
	".gitignore": true,
	".vs": true,
	"**/bin": true,
	"**/obj": true,
	".github": true,
	".vscode":true,

	// These are supportive directories. They contain code generation, unit tests, documentation, etc.
	// They are only hidden to guide new users to the source code and examples. If you would like to
	// contribute to this repository, it is recommended you unhide them. Thank you for your interest
	// in contributing.! :)
	"docfx_project":true,
	"Tools":true,
},
```

**Comment by ZacharyPatten** [comment]
By the way, this is related to https://github.com/microsoft/vscode/issues/40233, but it is _not a duplicate_. It would be nice if both https://github.com/microsoft/vscode/issues/40233 and https://github.com/microsoft/vscode/issues/128226 existed at the same time.
- https://github.com/microsoft/vscode/issues/128226 gives users the ability to ignore default settings
- https://github.com/microsoft/vscode/issues/40233 gives users the ability to use-but-override default settings

**Comment by AnrDaemon** [comment]
I think we already have enough of a place to store recommendations in the form of `extensions.json` file.

**Comment by sandy081** [comment]
Closing this in favour of [Local Workspace Settings](https://github.com/microsoft/vscode/issues/40233) and [User Profiles](https://github.com/microsoft/vscode/issues/116740) features.

**Comment by ZacharyPatten** [comment]
@sandy081 We need a way to recommend settings but not force settings on users. Unless #40233 will be implemented to allow that, they are not duplicates.

**Comment by sandy081** [comment]
I see. I was mistaken by Local Workspace Settings feature. Sorry about that. But I have to say that we do not have plans to implement this feature in near future. So, have to keep this closed instead of duplicating, but with out of scope. We will get back to it in future when revalidate our plans. Thanks for understanding.
