### ISSUE TITLE
Error When Closing Visual Studio Code On a Multi-User Environment

### ISSUE THREAD

**Issue by GeoMarkou** [microsoft/vscode#128266]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

- OS Version: Windows 10 (version 1809)

Steps to Reproduce:

1. Have someone else in your environment be running Visual Studio Code
2. Close Visual Studio Code when there is an update pending to be installed
3. An error popup will appear saying "There was an error while attempting to kill any running Code.exe processes: Failed to open process: Access is denied. Please verify there are no Visual Studio Code processes still executing."

This is quite annoying as I need to close/reopen VSCode multiple times in a day, and this happens every time I close VSCode. It also blocks me from opening VSCode until it finishes failing to update. I recommend that this either fails silently, or only try once per day. I don't think interrupting my coworkers to close their IDE is a good solution.

![image](https://user-images.githubusercontent.com/12272970/125008216-35172d80-e0a1-11eb-8ff0-ed4587320372.png)

![image](https://user-images.githubusercontent.com/12272970/125008453-b1aa0c00-e0a1-11eb-8fae-5e7a0746e3c4.png)

Log file:
[vscode-inno-updater-1625792529.log](https://github.com/microsoft/vscode/files/6787997/vscode-inno-updater-1625792529.log)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/76641
