### ISSUE TITLE
Intellisense autocomplete fails for Mongoose Objects (Nodejs)

### ISSUE THREAD

**Issue by thsubaku9** [microsoft/vscode#128204]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.57.1
- OS Version:11.4 (20F71)

Steps to Reproduce:

1. Create a valid Mongoose Schema and bind it to an model
2. Export this model out of the file (I used module.exports)
3. Access the model from another file and create a new object from this model
4. No auto prompts are shown for the underlying mongodb functions

**Comment by mjbvz** [comment]
Please share minimal, self-contained example code that demonstrates this issue

**Comment by thsubaku9** [comment]
Create schema file (connection.js)-> 

`var mongoose = require('mongoose');
var Schema = mongoose.Schema;
mongoose.connect(process.env.DBURL,{ useNewUrlParser: true, useUnifiedTopology: true })

var UserModelSchema = new Schema({
  name: String,
  uid: Schema.Types.ObjectId
});
var userModel = mongoose.model('userModel', UserModelSchema );
module.exports = {
    userModel: userModel
}
`

main file -> 

`const {userModel} = require('./connection')

let newUser = new userModel({name:req.query?.name})
    newUser.save((err, data) => {
        if(err) {
            console.log(error);
        }
        else {
            res.send("Data inserted");
        }})    
`

prompts are not displayed for newUser object

**Comment by manishmotiani** [comment]
+1
prompts are not displayed for userModel
prior to May release, userModel would prompt different functions like 'findById', 'findOneAndUpdate'
and now intellisense shows nothing

**Comment by mjbvz** [comment]
Works fine for me in a new project:

<img width="1083" alt="Screen Shot 2021-07-09 at 11 56 43 AM" src="https://user-images.githubusercontent.com/12821956/125124335-c344e100-e0ac-11eb-9642-f1556f6c96dd.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? If so, please share a self contain project as a GitHub repo that shows the problem

**Comment by thsubaku9** [comment]
I tried this out on the VS code insiders with commitId -> 87d692b7bf1eb5a663b3e62620a6e7e436e1838c and extensions disabled. Unfortunately the error still persisted in it. Please refer to this sample project for further triaging -> [link](https://github.com/thsubaku9/vscode_prompt_triage)

**Comment by mjbvz** [comment]
Thanks for the example project. I still can't reproduce  though:

![Screen Shot 2021-07-23 at 2 57 27 PM](https://user-images.githubusercontent.com/12821956/126845420-edc843d7-d62a-40ab-acc5-d49550a4c5db.png)

How did you install the dependencies? `npm`? 

Also what do you see if you hover over `mongoose` in `var mongoose = require('mongoose');`? I see:

![Screen Shot 2021-07-23 at 2 58 25 PM](https://user-images.githubusercontent.com/12821956/126845475-2cd7757d-570f-4922-9c93-c8c5e8889181.png)

**Comment by thsubaku9** [comment]
Just updated VSCode to 1.58.2. Issue is no longer reproducible :) 

(ty for your time and effort)

**Comment by Gitter499** [comment]
Hey I am having the same issue on 1.59, Mongoose queries don't have any autocomplete however models do.
