### ISSUE TITLE
Find and Replace: "Find in selection" includes current line of multi-line selection

### ISSUE THREAD

**Issue by cparker4486** [Microsoft/vscode#12820]
- VSCode Version: 1.5.3
- OS Version: Windows 10.0.14393

If your selection spans multiple lines, and the cursor rests at col 1 of the last line, this last line will be included in the selection even if no characters on that line were _actually_ selected.

## Steps to Reproduce:

0. Make sure you have content on every line you test these instructions against
1. Place your cursor at the front of a line (Col 1)
2. How Shift and press down to select multiple lines
3. After a few lines stop pressing down (your cursor should still be at Col 1)
4. Press Ctrl+H to open Find and Replace
5. Click "Find in selection" on the small control panel that opened previously
6. You'll see that the line where the cursor rests is included in the selection

![unintended selection expansion](https://cloud.githubusercontent.com/assets/1189638/18891219/2308bd3c-84b9-11e6-9185-17d3d2ae2951.gif)

## Expected result:

I expect that a line, without any selection visibly applied to it, does not result in the entire line being included in the selection.

## Steps to workaround:

Press the left arrow key after selecting all your lines for the cursor to be placed at the end of the previous line.

**Comment by isidorn** [comment]
This behavior is as designed. If more users are asking for the behavior you proposed we would welcome a PR
Here is a code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L502

**Comment by cparker4486** [comment]
I'm afraid I don't understand the rationale behind this. This is the first time I've ever encountered this behavior in a program but your response tells me the VS Code team implemented it this way on purpose.

I checked Sublime Text 3114 and Visual Studio Community 2015 and neither behave this way. (I dare say because the way VS Code behaves is not standard and unexpected.)

I'm afraid I don't have the programming skill to submit a PR myself so if the conclusion is to wait for enough* people to complain, I fear I'll never meet your criteria. So considering this is a non-standard behavior for a text editor it makes a lot more sense for you to consider this a bug, rather than a feature request, and address it appropriately.

Thanks for you careful consideration.

\* How many would it take?

**Comment by isidorn** [comment]
Sure - if everybody else behaves the way you propose that I agree that vscode should allign.
I believe it is just an if statement - should not require a lot of programming skill imho
