### ISSUE TITLE
Git sync arrows spin forever on SSH offending key (WSL)

### ISSUE THREAD

**Issue by spotlesstofu** [microsoft/vscode#128208]
Issue Type: <b>Bug</b>

1. Duplicate the line for your Git server in ~/.ssh/known_hosts
2. Replace some characters in the duplicated line key so the ssh key doesn't match
3. Click the spinning arrows to sync with your Git server
4. The arrows spin forever and no error or notification comes up

I only realized this when I tried to push from the CLI, git is prompting yes/no and VSCode can't get past that.

    % git push
    Warning: the ECDSA host key for 'git.example.com' differs from the key for the IP address '172.16.0.9'
    Offending key for IP in /home/camilla/.ssh/known_hosts:2
    Matching host key in /home/camilla/.ssh/known_hosts:14
    Are you sure you want to continue connecting (yes/no)?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (2.95GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/home/camilla/code/repo --remote=wsl+Debian --crash-reporter-id 844017f2-29d2-432b-80fd-36ddca9939b8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|12.23GB (4.75GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
jinja|who|0.0.8
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.6.999662501

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0702cf:30334634

```

</details>

**Comment by lszomoru** [comment]
@spotlesstofu, apologies for not getting back to you on this until now. We have made some improvements in this are as in [September 2022](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase) we have added support for SSH keys with a passphrase. I will go ahead and optimistically close this issue as resolved, but please feel free to reopen in case you are still able to reproduce the issue. Thanks!
