### ISSUE TITLE
Trust and Continue dialog need two clicks on `Continue` to go away

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#128271]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.58.0
- OS Version:MacOS Big Sur

Steps to Reproduce:

1. Open an _untrusted_ folder (in my case, containing a VS Code Extension repo)
2. Run `Task: Build` command
3. The `Do you trust the authors of the files in this folder?` dialog appears, saying that _"Listing and running tasks requires that some of the files in this workspace be executed as code...."_ 
4. Click the `Trust Folder and & Continue` button
5. The `Restricted Mode` banner is removed from VS Code window, but the dialog remains
6. Click the `Trust Folder and & Continue` button **again**
7. Now the dialog closes, and the Task starts

If instead of clicking the `Trust Folder & Continue` button twice (step 6), you simply close the dialog (click the X button), the build task starts normally (as it should, because I already _trusted_ the folder)

Thank you

**Comment by alexr00** [comment]
The `Build` command hits two task entry points where I check for `trust`, but I thought that when I call `requestWorkspaceTrust` on the second one it would just return `true`. @lszomoru should I be checking if the workspace is already trusted before calling `requestWorkspaceTrust`?

**Comment by lszomoru** [comment]
@alexr00, I have looked into this and the issue is in the workspace trust service. Due to a regression introduced last milestone, we resolve the promise for `erquestWorkspaceTrust()` **before** the workspace has fully transitioned from untrusted to trusted. I am working on a fix now.

**Comment by lszomoru** [comment]
Fix has been merged to the release branch.
