### ISSUE TITLE
Tree Indent Guides are misaligned with its parent drop down arrow

### ISSUE THREAD

**Issue by charbelnicolas** [microsoft/vscode#128257]
Issue Type: <b>Bug</b>

When the tree indent guides are enabled ("workbench.tree.renderIndentGuides": "always"), they look misaligned with the parent drop-down arrow on top.

![20210708_173621](https://user-images.githubusercontent.com/14960414/124999110-1e29fa00-e013-11eb-92e5-a6cb614cf644.png)

As a user I would expect the indent guide line to be aligned to the center of the parent drop-down arrow.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.12.14-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.31GB (28.55GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d82b6845-3d72-4a6f-981c-3dbee67a3d78|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions: none

**Comment by charbelnicolas** [comment]
If this is by design then by all means close this issue, it looks weird to me.

**Comment by spartanatreyu** [comment]
Yeah, looks weird for me too. It feels, *wrong*.

<img width="376" alt="Screen Shot 2021-07-09 at 9 44 13 am" src="https://user-images.githubusercontent.com/3240456/125003338-5b859a80-e09a-11eb-9b6b-256373ebde40.png">

**Comment by joaomoreno** [comment]
Unfortunately this is by design: moving the guide only a pixel to the right will make it overlap with _some_ icons. The rule is: the twistie and the indent guides aren't meant to be aligned. It is not meant to be this:

![win95](https://4sysops.com/wp-content/uploads/2014/10/Windows-95-Explorer.-Those-were-the-days.png)
