### ISSUE TITLE
[FR] Auto-complete Fragments

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#128213]
Currently, unlike other tags, fragments can't be auto-completed, would be nice to have them supported:

![2021-07-08 21_49_47](https://user-images.githubusercontent.com/28700378/124933745-b38ab580-e036-11eb-9212-aa4700817813.gif)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
