### ISSUE TITLE
autocomplete for c/c++ is not avaliable

### ISSUE THREAD

**Issue by ZenoWang** [microsoft/vscode#128275]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

mac os:
big sur 11.4

vscode:
版本: 1.58.0 (Universal)
提交: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
日期: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

c++ Intellisense:
v0.2.2

**Comment by jrieken** [comment]
You need to install an extension for that, see this guide for further help: https://code.visualstudio.com/docs/languages/cpp

**Comment by ZenoWang** [comment]
> You need to install an extension for that, see this guide for further help: https://code.visualstudio.com/docs/languages/cpp

I have installed C/C++ and C++ Intellisense. This problem appeared recently. The autocomplete worked well in three months ago. It really confused me. I have tried uninstall all extensions and vscode. 

![image](https://user-images.githubusercontent.com/20139744/125040565-648e6000-e0ca-11eb-8ab9-b508f6a2c4ed.png)

**Comment by ZenoWang** [comment]
@jrieken I have installed C/C++ and C++ Intellisense. This problem appeared recently. The autocomplete worked well in three months ago. It really confused me. I have tried uninstall all extensions and vscode but it still did not work.
