### ISSUE TITLE
i can't run html file on chrome

### ISSUE THREAD

**Issue by Phamthanh69** [microsoft/vscode#128217]
We have written the needed data into your clipboard because it was too large to send. Please paste.

```json
// Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/app.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        },
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "pwa-chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}"
        },

        
        {
            "name": "Attach to Chrome",
            "port": 9222,
            "request": "attach",
            "type": "pwa-chrome",
            "webRoot": "${workspaceFolder}"
        },
        {
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "name": "Launch Extension",
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm",
            "request": "launch",
            "type": "pwa-extensionHost"
        },
    {
        "name": "Attach to Edge",
        "port": 9222,
        "request": "attach",
        "type": "pwa-msedge",
        "webRoot": "${workspaceFolder}"
    },
    
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
    "compounds": [
        {
            "name": "Compound",
            "configurations": ["Launch Chrome against localhost"
            "Launch Extension"]
        }
    ]
}
```

Issue Type: <b>Bug</b>

ican't test my html file on chrome

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.85GB free)|
|Process Argv|--crash-reporter-id a0fe9218-74db-4b69-98a6-3a91ca1394d9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
rtf|ale|2.3.0
remove-vietnamese-tones|ans|1.0.0
vscode-html-css|ecm|1.10.2
live-html-previewer|hdg|0.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.4.1
live-server-preview|neg|0.1.4
slides|nic|4.0.0
LiveServer|rit|5.6.1
html-snippets|wge|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
aatestflightcf:30331712

```

</details>

**Comment by weinand** [comment]
@Phamthanh69 you said:
> ican't test my html file on chrome

Why not?

**Comment by TheEssentialist** [comment]
Tell me which of the following extensions did you use to preview the HTML file in chrome
1: live server by ritwick dey
2: live-html-previewer by negokaz
3: live-html-previewer by harshdeep gupta
And try disabling The HTML snippets made by the authors, mohamed abusaid and geyao Because when I saw their extension's read me file, there was a text saying DISABLE THIS EXTENSION AS IT CURRENTLY CONFLICTS WTH EXISTING VS CODE HTML EXTENSION and then see if it works. this is just a suggestion and please reply at the latest.
