### ISSUE TITLE
[Bug] `workbench.action.terminal.switchTerminal` does nothing

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#128215]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.57.1
- OS Version: Windows 10

Tried this command, seems to be doing nothing.

**Comment by Tyriar** [comment]
Thanks for the report and for digging into this stuff 🙂. This command isn't meant to be exposed in the command palette as it's only purpose is to drive the terminal dropdown behind the scenes.

**Comment by rzhao271** [comment]
It still shows up when setting keyboard shortcuts. Is there any way around that?
I'll mark it as verified because it doesn't show up in the command palette.

**Comment by Tyriar** [comment]
I don't think we can avoid that
