### ISSUE TITLE
Markdown Incorrect Colorization of Fenced Code Blocks Inside of Block Quotes

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12822]
For a markdown file like this:

`````` ms
> ```js
> 
> ```

**Blue Bold** white
``````

The colorization is incorrect. Depending on what language is targeted, the colorization can break out of the code block entirely:

![screen shot 2016-09-27 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/12821956/18891457/28691f28-84ba-11e6-8560-89ea0b95f0bc.png)
![screen shot 2016-09-27 at 1 54 31 pm](https://cloud.githubusercontent.com/assets/12821956/18891458/286a3cbe-84ba-11e6-90fc-380caf73ab30.png)

Here's what things should look like: 

![screen shot 2016-09-27 at 1 54 47 pm](https://cloud.githubusercontent.com/assets/12821956/18891456/284d7a84-84ba-11e6-9647-7d5e6d13f5a8.png)

The problem is that that block quote opening `>` are included as part of the fenced code block content. This causes some language colorizers to freak-out and highlight the entire rest of the file.

**Comment by dcbrwn** [comment]
I suppose that this issue is kind of related to #3746. I'm having the same problem right now with JS code blocks.

**Comment by mjbvz** [comment]
@dcbrwn Yes, this is another manifestation of #3746 but triggered by different behavior

In markdown, the fenced code block tokenizers for various programming languages can currently escape outside of the fenced code block if there is a syntax error in the block. In this example, the `>` is included inside the code content of the fenced code block because of incorrect parsing of block quotes. The Javascript highlighter sees the `>` and breaks out of the block entirely, and then tries to highlight the rest of the file.

I'm planning to address the core problem of fenced code block breakout soon.

**Comment by dcbrwn** [comment]
@mjbvz, mine issue with JS, TS and alike is caused by template string quote introduced in es6 ("\`"). Workaround for now is to stick code blocks to some text like this (added back-slashes to preserve "```"):

```
Some text example:
\```typescript
const a = `the ${template} string`;
\```
```

**Comment by mjbvz** [comment]
Original issue fixed by #14626

![screen shot 2016-11-17 at 3 51 33 pm](https://cloud.githubusercontent.com/assets/12821956/20412785/ac6c15d2-acdd-11e6-8a7d-626a11dd2bca.png)

@dcbrwn I think the issue you identified has also been fixed:

![screen shot 2016-11-17 at 3 52 55 pm](https://cloud.githubusercontent.com/assets/12821956/20412815/d91b4cba-acdd-11e6-9c38-54bbccb927da.png)

Please try out the latest insiders builds and let me know if this is not the case.

**Comment by calebmer** [comment]
Thanks so much guys for all the great work you do :tada:

**Comment by dcbrwn** [comment]
Seem to work as expected 👍
