### ISSUE TITLE
Terminal exits with exit code 1

### ISSUE THREAD

**Issue by handreistoicescu** [microsoft/vscode#128273]
Issue Type: <b>Bug</b>

1. Use an integrated terminal with zsh
1. Make sure there is no .zshrc file present on the system
1. Open a terminal
1. Exit the terminal by typing `exit`
1. Observe the error `The terminal process "zsh '-l'" terminated with exit code: 1.`

**A quick workaround:** Create an empty `.zshrc` file and the error doesn't trigger anymore.

This scenario is important because on fresh installs of macOs Big Sur there is no `.zshrc` file present on the system, so many users will encounter it.

#### Video

![2021-07-09 06 26 40](https://user-images.githubusercontent.com/29334095/125018988-c88b3700-e07e-11eb-882e-28ba038fe456.gif)

VS Code version: Code 1.58.0 (Universal) (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id c9d12437-310e-4699-962d-946eedd4d912|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
haml-lint|aki|0.2.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.0.1
vscode-graphql|Gra|0.3.16
vscode-test-explorer|hbe|2.20.4
haml|kar|1.3.1
dotenv|mik|1.0.1
test-adapter-converter|ms-|0.0.12
vsliveshare|ms-|1.0.4531
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
vscode-nunjucks-formatter|oki|0.1.3
material-icon-theme|PKi|4.8.0
ruby|reb|0.28.1
synthwave-vscode|Rob|0.1.8
nunjucks|ron|0.3.0
vscode-ruby|win|0.28.0
material-theme|zhu|3.10.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by Tyriar** [comment]
This is by design, it's just what that shell exits with so we show it. You can use `"terminal.integrated.showExitAlert": false` to suppress it

**Comment by handreistoicescu** [comment]
> This is by design, it's just what that shell exits with so we show it. You can use `"terminal.integrated.showExitAlert": false` to suppress it

TIL about `"terminal.integrated.showExitAlert": false`. Thanks!
