### ISSUE TITLE
XHR failed when trying to install extensions

### ISSUE THREAD

**Issue by sasikiran1998** [microsoft/vscode#128229]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.XHR failed
2.Not able to see extensions.
3.Every time getting error like " We cannot connect to the extensions marketplace at this time. "
![Screenshot (624)](https://user-images.githubusercontent.com/69857268/124967764-68769f80-e042-11eb-9407-d9193f01f1bf.png)
![Screenshot (625)](https://user-images.githubusercontent.com/69857268/124967772-6b719000-e042-11eb-9761-8ead484c3ef8.png)

**Comment by sandy081** [comment]
Can you please open dev tools console and see if there are errors related to this? You can run the command `Toggle Developer Tools` from command pallette to open developer tools.

**Comment by sasikiran1998** [comment]
Could You specify what to open more clearly, I am using Windows 10. I did not get where to open dev tools and all. So suggestions are readily accepted..

And for more info:
1.Whenever VS Code is opened, it never shows the extensions.
2.If I try to download from internet also, it always shows message as XHR failed.
3.This issue is not resolved even if i try to uninstall and reinstall VS code again and again.
4.Whever is done, the extensions are never visible and will always throws message as " We cannot connect to the extensions marketplace at this time".

**Comment by Akitakek** [comment]
Same issue here, before the last update it worked fine and I could browse extensions.

**Comment by sasikiran1998** [comment]
Ok .. I wil try and update ..

**Comment by sandy081** [comment]
To open developer tools, please do following:

- Press `F1` - this opens command pallette
- Type `Developer: Toggle Developer Tools` and select that command
- It opens the developer tools console
- Try to repro the issue and see if there are any errors in the console

@Akitakek I do not think VS Code and Codium are same, so if you are seeing issues with Codium, please file issues against that product.

**Comment by sasikiran1998** [comment]
please do find the attachment and help me how to resolve the problem
![Screenshot (628)](https://user-images.githubusercontent.com/69857268/125466405-f008bdda-5611-4ed9-bf6f-2e59cc90ea2a.png)

**Comment by sandy081** [comment]
@deepak1556  Tunnel Connection Failed - electron / chromium related ?

**Comment by sasikiran1998** [comment]
wat needs to be done after i open developer tools, there are many errors and warnings..
suggest me how wil i get the extensions activated in my vs code..
![Screenshot (628)](https://user-images.githubusercontent.com/69857268/125916841-197722ed-f75e-42e0-84c7-10b82b89190f.png)

**Comment by SinTan1729** [comment]
I'm also having the same error in Manjaro.

**Comment by deepak1556** [comment]
`ERR_TUNNEL_CONNECTION_FAILED` indicates they have a proxy server configured and it either rejects request to the marketplace or some other error at the proxy layer.

@sasikiran1998 couple of things to confirm,

Are you able to access https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.163.2/vspackage from your system browser ? If it works, then try the following

1) Launch with `code --user-data-dir <dir>` (fill some absolute value for `<dir>`) and check if extension search works
2) 
   * Launch with `code --log-net-log=<dir>/netlog.json`
   * Perform the extension search
   * Quit the application
   * Attach the `netlog.json` file generated at `<dir>`

**Comment by sasikiran1998** [comment]
I have tried your expressions and got the result as mentioned.
But this did not solve my issue of getting the extensions, please take a look and specify me how to get the extensions activated.

![image](https://user-images.githubusercontent.com/69857268/126452425-68271101-46fe-4a81-8335-8fc1737e7a6c.png)
![image](https://user-images.githubusercontent.com/69857268/126452495-74ad1522-bea9-40e8-b563-074554b12289.png)

**Comment by deepak1556** [comment]
> Are you able to access https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.163.2/vspackage from your system browser ?  If not then please check your proxy blocks connections to https://marketplace.visualstudio.com/

Did you try this ?

Also can you attach the generated `netlog.json` file

**Comment by sasikiran1998** [comment]
i tried to access the link : https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.163.2/vspackage  

and a VSIX file downloaded.

**Comment by deepak1556** [comment]
Thanks for testing, can you provide the netlog file for further debugging.

**Comment by sasikiran1998** [comment]
the netlog file is empty
I am using Windows 10
No proxy
I am on Jio4G wifi network

**Comment by deepak1556** [comment]
Based on https://github.com/microsoft/vscode/issues/128229#issuecomment-883974825 the path you have specified is incorrect, it should be `code.cmd --log-net-log="C:\Users\sasi\AppData\Local\Programs\Microsoft VS Code\netlog.json"`

**Comment by sasikiran1998** [comment]
I am getting like tis..

what needs to be done next ?

![image](https://user-images.githubusercontent.com/69857268/126608205-d09cf7fc-941b-48f6-af16-2989a697be63.png)

**Comment by sasikiran1998** [comment]
Again i am getting the same error: 

![image](https://user-images.githubusercontent.com/69857268/126608605-bfcf94be-81ae-49de-9602-2014d37dc26d.png)

**Comment by deepak1556** [comment]
Please share a screen recording of what you tried including the commands used to launch the app, you may find https://gifcap.dev helpful as a browser-based gif recording tool.

**Comment by sasikiran1998** [comment]
Plz find the attached video glimpse, and after even after i relaunch the vs code app, the extensions are not working
![recording](https://user-images.githubusercontent.com/69857268/126614250-7e840c0e-17bb-47ec-9f15-954036ebe853.gif)

**Comment by deepak1556** [comment]
The path should be enclosed in quotes to be parsed correctly. Please follow the steps below to get the log file

* Launch with `code.cmd --log-net-log="C:\Users\sasi\AppData\Local\Programs\Microsoft VS Code\netlog.json"`
* Perform extension search (this step should fail which is expected)
* Quit the application
* Attach `netlog.json` file from the path `C:\Users\sasi\AppData\Local\Programs\Microsoft VS Code\`

These steps will not fix the issue but will provide better logging to understand the issue.

**Comment by sasikiran1998** [comment]
I have executed the above said, as the netlog.json file format is not supported here, i have mailed u the file.. what to do next??

**Comment by deepak1556** [comment]
Thanks for the log, it shows that a proxy server has been configured.

<img width="625" alt="Screen Shot 2021-07-22 at 11 49 14 PM" src="https://user-images.githubusercontent.com/964386/126747123-da416aee-e53c-405a-89b8-411e388d5695.png">


You might want to disable `Automatic Proxy setup` under your system network settings. Closing as issue is not from vscode.

**Comment by sasikiran1998** [comment]
![image](https://user-images.githubusercontent.com/69857268/126747985-cd534bc6-561e-4fe5-8281-c3d4e87fab9e.png)

Even if i have disabled the proxy, i am getting the same issue :

![image](https://user-images.githubusercontent.com/69857268/126748101-9628d70a-6b22-4e44-b3c5-e147fa7c1c55.png)

**Comment by deepak1556** [comment]
Can you start with `code --no-proxy-server` and check.

**Comment by sasikiran1998** [comment]
Still the problem persists


![image](https://user-images.githubusercontent.com/69857268/126753454-baee9d30-1d5b-4f14-a8df-e1e6a242aaaf.png)

**Comment by deepak1556** [comment]
Please attach a new netlog by starting with `code.cmd --no-proxy-server --log-net-log="C:\Users\sasi\AppData\Local\Programs\Microsoft VS Code\netlog.json"`

**Comment by sasikiran1998** [comment]
Should i delete the previous one?

**Comment by sasikiran1998** [comment]
![image](https://user-images.githubusercontent.com/69857268/126754036-8010cefa-dc28-41ac-b16b-05c44cd9a860.png)

**Comment by deepak1556** [comment]
> Should i delete the previous one?

No it will be overwritten. You can follow the same steps as https://github.com/microsoft/vscode/issues/128229#issuecomment-885186811 with added `--no-proxy-server` for the first step. You can zip the `netlog.json` file and upload to this issue.

**Comment by sasikiran1998** [comment]
[netlog.zip](https://github.com/microsoft/vscode/files/6867499/netlog.zip)

**Comment by sasikiran1998** [comment]
![image](https://user-images.githubusercontent.com/69857268/126756380-5e59aa47-7754-433f-8aa6-f26bdaf04dcb.png)
[netlog.zip](https://github.com/microsoft/vscode/files/6867501/netlog.zip)

**Comment by deepak1556** [comment]
Can you print the values of `echo %http_proxy%` and `echo %https_proxy%` from the command prompt.

**Comment by sasikiran1998** [comment]
![image](https://user-images.githubusercontent.com/69857268/126760249-06a48bf1-115b-4665-9b22-c02f2f8526dd.png)

**Comment by sasikiran1998** [comment]
The extensions are activated. 
Thus the issue is closed..
![image](https://user-images.githubusercontent.com/69857268/126762492-9c8978c3-78f0-4628-a993-d555cc30ef3f.png)

**Comment by sasikiran1998** [comment]
Thanks  @deepak1556 for solving this issue
