### ISSUE TITLE
Making large text cell output readable

### ISSUE THREAD

**Issue by ZenosParadox** [microsoft/vscode#128249]
Issue Type: <b>Feature Request</b>

Using jupyter notebook, if cell output text is too long it is intercepted with msg "show more (open the raw output data in a text editor) ...".

When expanded only binary data seen which is not easily readable. example: "valueBytes": [67,111,110,116,...]

Extension version: 2021.6.999662501
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by cmacdonald** [comment]
I have this problem too. 
VS Code version: 1.59.1 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa Date: 2021-08-19T11:53:52.479Z (1 wk ago)
OS version: MacOS

ms-toolsai.jupyter verison v2021.8.1236758218

```json
[
	{
		"metadata": {
			"outputType": "stream"
		},
		"outputItems": [
			{
				"mimeType": "application/vnd.code.notebook.stderr",
				"data": "                                                 "
			}
		]
	},
	{
		"metadata": {
			"outputType": "stream"
		},
		"outputItems": [
			{
				"mimeType": "application/vnd.code.notebook.stdout",
				"data": "num docs 25\n"
			}
		]
	},
	{
		"metadata": {
			"outputType": "stream"
		},
		"outputItems": [
			{
				"mimeType": "application/vnd.code.notebook.stderr",
				"data": ""
			}
		]
	},
	{
		"metadata": {
			"outputType": "stream"
		},
		"outputItems": [
			{
				"mimeType": "application/vnd.code.notebook.stdout",
				"data": 
```
followed by the JSON formatted output. This isnt as easy to read as it would be if it was rendered.

**Comment by DonJayamanne** [comment]
I'm sorry you're running into this issue, however has been resolved in the latest VS Code insiders.
I'm closing this issue as it has been fixed in VS Code& the next version of VS Code will ship sometime this week.

**Comment by DonJayamanne** [comment]
Oops, thought this was the Jupyter repo

**Comment by cmacdonald** [comment]
it probably is a bug for microsoft/vscode-jupyter, but I saw the original post had been "transferred" here.
I have now found https://github.com/microsoft/vscode-jupyter/issues/7207 and https://github.com/microsoft/vscode/issues/130187
so I think this can be closed. I look forward to new release.

**Comment by DonJayamanne** [comment]
Thanks, closing in favor of https://github.com/microsoft/vscode/issues/130187
