### ISSUE TITLE
Malfunctions

### ISSUE THREAD

**Issue by paulkckho** [microsoft/vscode#128260]
White text on white background impossible to read.  Unable to use color themes. Cannot reinstall or reboot. Same problems persisted after multiple attempts at correcting problems. 
![Screenshot 2021-07-08 170730](https://user-images.githubusercontent.com/72099759/125001182-4879b880-e00f-11eb-9887-b3949b861529.jpg)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have any theme extension installed or any settings in `workbench.colorCustomizations`?
Also what is VS Code and OS versions? 

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by paulkckho** [comment]
All extensions are disabled. My OS is Windows 10 Pro. VS Code will not function.

**Comment by aeschli** [comment]
Can yo start with a new user dir? `code --user-data-dir .\tmpUserDirLocation`
