### ISSUE TITLE
Notebook is focused after clicking into a window, stealing focus

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128219]
Repro:

1. Open an editor on left, notebook on right
2. Shrink notebook to smallest width to enable the snapping feature
3. Click into the notebook
4. Open a link from it (eg. from GH issues notebook), the browser will open
5. Click into the editor on the left, it will briefly be focused, collapsing the notebook before the notebook steals focus and expands again

![recording (39)](https://user-images.githubusercontent.com/2193314/124955199-bbf9d680-dfcb-11eb-97d9-f0fb498b4cb1.gif)

Related: https://github.com/microsoft/vscode/issues/128117

**Comment by rebornix** [comment]
Not seeing this anymore in latest Insiders.
