### ISSUE TITLE
`EditorResolution.PICK` hangs when closing quick pick without picking

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128210]
When fixing https://github.com/microsoft/vscode/issues/128145 I noticed that the call to `editorResolverService.resolveEditor` never returned when I closed the picker with ESC or clicking somewhere else.

I think this is risky because it leaves promises hanging around that never complete.

**PS:** I did not fully understand the code that sets `resolvedEditor = undefined` for `ResolvedStatus.NONE`:

https://github.com/microsoft/vscode/blob/183d29041ebc25271b91d7ae7438f7f96f2b4fc2/src/vs/workbench/contrib/files/browser/editors/binaryFileEditor.ts#L69-L70 

Should we simply return both on `ABORT` and `NONE`?

**Comment by lramos15** [comment]
> Should we simply return both on `ABORT` and `NONE`?

When it's `NONE` I simply continue replacing the active editor with the passed in one. This function might benefit from being passed in an untyped input

**Comment by JacksonKearl** [comment]
Is this user-facing?

**Comment by lramos15** [comment]
This is not verifiable as it wasn't user facing, just a hanging promise.
