### ISSUE TITLE
More contrast to selected line in peek definition

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12826]
Currently it's too hard to tell which line is the one containing the symbol.

Really bad for scanning through.

![image](https://cloud.githubusercontent.com/assets/4033249/18893505/135dafc8-84c3-11e6-8192-419b9f6e7dc2.png)

**Comment by jrieken** [comment]
@bgashler1 please advice

**Comment by bgashler1** [comment]
Just from a quick glance at this issue, I would expect this to be a line-highlight, since we're doing that for Search and Find/Replace.  Thoughts?
![screen shot 2016-09-28 at 4 47 47 pm](https://cloud.githubusercontent.com/assets/11839736/18936329/517224a0-859b-11e6-99b2-8c7810beb25c.png)

**Comment by octref** [comment]
Would be best if the line has some shallow highlight like symbol selection:

![image](https://cloud.githubusercontent.com/assets/4033249/18936434/27415312-859c-11e6-9782-36f0dc2f16d7.png)

While the symbol have a strong highlight, like the brown in search.

**Comment by bgashler1** [comment]
@octref that also makes sense.  Similar concept.  Why are we using two different grays for these highlights?  They seem like they should be the same.

**Comment by octref** [comment]
@bgashler1 Not two grays. One line of gray background like `our-editor`, then the strong brown background on the keyword (`editor` in your case).

**Comment by bgashler1** [comment]
@octref Sorry for the miscommunication, what I meant was that that the image I posted of a Search match line highlight has a very similar gray to the shallow gray in your image.  But when I checked the color values of each, the differed.  This is one of many color inconsistencies we have that we should eventually resolve.

**Comment by octref** [comment]
@bgashler1 That I don't know. Indeed we could use more color consistency.

**Comment by jrieken** [comment]
The problem is that some provider give us the word too highlight and some providers give us the whole definition range spanning multiple lines. Therefore we fold the highlight into a single position. Unsure what to do next...

**Comment by jrieken** [comment]
This can be now configured with themes
