### ISSUE TITLE
(ScriptedSandbox64/edit 'Editor content;Press Ctrl+F1 for Accessibili...) The BoundingRectangle property must represent an area of at least 25 pixels.

### ISSUE THREAD

**Issue by saiprasanna93** [microsoft/vscode#128298]
1. Open Visual Studio
2. Create a new project under Azure Resource group​
3. Select azure template as 'Logic App' and create solution​
4. Tab till Extensions->Manage extensions->Online and search for logic app and install and download 'Azure logic apps tools for Visual studio'
5. Navigate till LogicApp.json file and right click->Open with logic app designer​
6. Provide the subscription and resource group details and press enter​
7. Tab till Service Bus queue trigger and press enter
8. Tab till New step button and press enter
9. Tab till 'Control' and press enter
10. Tab till Terminate under actions tab and press enter
11. Run Accessibility Insights for windows on the terminate screen

**Comment by joaomoreno** [comment]
I believe you're referring to Visual Studio. This repository is about Visual Studio Code.
