### ISSUE TITLE
Pin Terminal in Editor Tab

### ISSUE THREAD

**Issue by ifeue** [microsoft/vscode#128269]
Issue Type: <b>Bug</b>

I can caeate a terminal in editor area. I pinned this terminal in editor tab. Atfer I close VSCode and open it again, the pinned terminal disappeared. I expect the pinned terminal still there. 

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by singuerinc** [comment]
The pinned terminal also closes if you do cmd+W, but it shouldn't, like any other pinned editor.

**Comment by Tyriar** [comment]
Think it's happening because of the custom keybinding/command:

https://github.com/microsoft/vscode/blob/60ddedc0503dfec6cb1aac0814f7fc09dc52d2b3/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1713-L1733

**Comment by alexr00** [comment]
I'm still seeing the pinned terminal vanish when I close and re-open the same folder. The tab flickers for a moment, but then it's gone.

![recording (64)](https://user-images.githubusercontent.com/38270282/127505062-d926f0a8-18a1-42b7-b91f-19cb660bea92.gif)

**Comment by meganrogge** [comment]
@alexr00 That behavior is expected because the pty host goes down when the window is closed.

**Comment by meganrogge** [comment]
confirmed that now the pinned terminal in an editor tab doesn't close with `ctrl w` and found a bug related to that #129858

**Comment by alexr00** [comment]
Looks like this was meant to be closed.
