### ISSUE TITLE
MacOS: Could not move terminal into editor area after first move

### ISSUE THREAD

**Issue by mahdi-farnia** [microsoft/vscode#128236]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

1. Open terminal panel
2. Move first terminal into editor area
3. Open terminal panel again
4. Terminal profile name & its icon disappeared

<img width="820" alt="Screen Shot 1400-04-17 at 23 53 13" src="https://user-images.githubusercontent.com/65429393/124979325-218ba880-e048-11eb-812d-cf96b745073f.png">

**Comment by meganrogge** [comment]
Can you attach a gif?

![recording (27)](https://user-images.githubusercontent.com/29464607/124984705-6682f100-dfee-11eb-9385-683f8827bdff.gif)

**Comment by meganrogge** [comment]
oh I see. the single terminal tab item isn't showing up when the panel is opened.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Tyriar** [comment]
I think this was fixed with https://github.com/microsoft/vscode/issues/92649, let's consider for the recovery build if we are doing one.

**Comment by mahdi-farnia** [comment]
It hasn't fixed yet!
i upgraded vsCode to version 1.58.1
did you fix this issue in this update or it has fixed in insider release?

**Comment by mahdi-farnia** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

i don't have insider version, and i don't wanna install it (sorry, may be my sentences are a little like angry person but it's not 😅)
