### ISSUE TITLE
Terminal background color dimmed after update.

### ISSUE THREAD

**Issue by RayPS** [microsoft/vscode#128295]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: macOS Big Sur 11.4 Apple Silicon

Steps to Reproduce:
1. Open Terminal in VS Code.

Just updated VS Code, the Terminal background suddenly appeared to be dimmed/grayed out. I haven't updated VS Code for at least a month, so not sure which version causes this issue.

- I've tried disabling themes/extensions, switching shell to bash, issue still remain.
- <del> Running with `code --disable-gpu` can be temporary solve the issue.</del>
- <del> This issue does not exist in Insider version at all.</del>
--- edit ---
- Setting `"terminal.integrated.gpuAcceleration"` to `"auto"` can be temporary fix the issue for me, some users are different by setting this to `on` / `off`.
- This issue also exist in Insider version when `"terminal.integrated.gpuAcceleration"` set to `"canvas"`.

<img width="885" alt="Screen Shot 2021-07-09 at 16 25 02" src="https://user-images.githubusercontent.com/1941540/125048196-42004500-e0d2-11eb-8bec-ed121a77481c.png">

Related to #69309 & #71568 but those were locked without a solution. Sorry if this are duplicated.

**Comment by kirill-martynov** [comment]
Same thing.
Using same color **#2e3440** for editor.background and terminal.background, but for terminal it looks like darker/dimmed.

checked with color picker and saw that terminal.background color have **rgb 34 39 49** and editor.background have **rgb 40 45 57**

but both set to **#2e3440**

**Comment by kirill-martynov** [comment]
as @RayPS said this really fix the issue:
![image](https://user-images.githubusercontent.com/70448489/125051926-1d917200-e0ac-11eb-8091-0235332f435e.png)

**Comment by dlschmidt** [comment]
Turning off GPU acceleration also fixes this issue for editor-like terminals, i.e. using
```typescript
"terminal.integrated.defaultLocation": "editor"
```

**Comment by RomnKo** [comment]
For me GPU Acceleration was set to Auto, so I changed it to On and that fixed it for me. Looks like any setting but Canvas look good. Canvas is the one that changes the terminal color.

**Comment by memeplex** [comment]
I'm seeing this too in macOS.

**Comment by Tyriar** [comment]
Thanks for the info all, action items:

- Why are users seeing differences between "auto" and "on"
- Investigate why the background color isn't set right when set to "canvas"

**Comment by wavebeem** [comment]
Seeing this too when the terminal is set to canvas rendering. My setting was originally "auto", but now after messing with it, only "canvas" reproduces the issue. Perhaps "auto" was picking canvas behind the scenes previously for some reason.

Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by Tyriar** [comment]
@wavebeem that's good to hear, I tweaked how auto worked in https://github.com/microsoft/vscode/issues/123077#issuecomment-881479727 which was meant to fix that.

**Comment by Tyriar** [comment]
I can't reproduce this on Catalina. While thinking about it, it reminds me of an old issue where the terminal was actually rendering "correctly" according to the theme color and it was everything else that was wrong.

@deepak1556 do you know how the color profile stuff works and are you familiar with this issue on Big Sur(+?) where color codes in the theme are changed when rendered? The screenshot above shows the terminal is `#1e1e1e` which is the default for Dark+ but the editor is `#181818`.

Related: https://github.com/microsoft/vscode/issues/111645

**Comment by Tyriar** [comment]
Not sure why this seems to happen on canvas only but not the webgl renderer. FWIW gpuAcceleration: auto is improved in Insiders so hopefully people will stop wrongly getting the canvas renderer and use the better webgl one which doesn't show this issue.

**Comment by wavebeem** [comment]
@Tyriar I just checked my color codes, it's definitely the wrong color in the canvas terminal, not the other way around, fyi 😄 

![image](https://user-images.githubusercontent.com/176815/126566737-202e73eb-5288-46d6-bb1c-2561d1d68233.png)

**Comment by Tyriar** [comment]
So confused lol

**Comment by wavebeem** [comment]
In case it helps, I didn't noticed this until I used a dark theme. In my regular light theme, the terminal is `#f3f3f3` instead of `#f5f5f5`

So the gray value goes from 245/255 (0.961) to 243/255 (0.953), or minus 2.

![image](https://user-images.githubusercontent.com/176815/126568138-4f2839a2-4a69-42b7-b21e-da0ee97cb7e8.png)
