### ISSUE TITLE
Support another status item background color to indicate "warning" state

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128205]
We currently allow extensions to set a background color for status bar items limited to `statusBarItem.errorBackground`. This is a very strong red indicator that should be used for error cases.

To give extensions a way of indicating warning situations, we should introduce another color that is less strong. Examples include a indication that some feature is not enabled and thus the experience may be less than ideal (though not an error case).

Some ideas:

![image](https://user-images.githubusercontent.com/900690/124923268-90daab80-dffa-11eb-89f6-2b13a0ee6093.png)

![image](https://user-images.githubusercontent.com/900690/124923288-93d59c00-dffa-11eb-9af3-30c974f7d5f1.png)

The former would be a new color for warning, the latter would be exposing our existing prominent color to extensions.

//cc @egamma

**Comment by brettcannon** [comment]
@luabud do you think it makes sense to use this for when no Python interpreter is selected?

**Comment by luabud** [comment]
@brettcannon Great question. I'd love to get @misolori's opinion on it, as I'm not sure how that could look like when it comes to different themes. 


The idea would be to change the background color for when the following is displayed on the status bar:

![image](https://user-images.githubusercontent.com/45497113/126244398-11e3ed68-77af-431f-9849-ffe8efb01898.png)
