### ISSUE TITLE
Disable automatic highlighting of word/token under cursor

### ISSUE THREAD

**Issue by AgilentGCMS** [microsoft/vscode#128235]
Is there a way to disable the automatic highlighting of the word or token under the cursor? I'm using VS Code 1.57.1. I've looked at issues #5351 and #24426, but my version of VS Code doesn't seem to know about the `editor.occurrencesHighlight` flag. It is not suggested as an autocomplete item when I edit `settings.json`, and setting it to `false` has no effect.

This is an issue because if I try to select a part of the current word with shift+cursor, the selected part is highlighted identically to the entire word. See [here](https://drive.google.com/file/d/1MdF3Wp6fYAY38FmLSFEmtB20B-7DGdd_/view?usp=sharing) for a dark theme example, and [here](https://drive.google.com/file/d/1LwrllJm2EfwqYev4WywvLVQYubt-K_45/view?usp=sharing) for a light theme example. In both cases, the `mean` of `mean_tau` is selected, but one cannot tell. 

To me, highlighting the current word is a bell/whistle I can do without. Visually distinguishing selected text from the rest is essential to me. Can I disable the automatic highlighting so that I can see what part of a word I have selected?

**Comment by alexdima** [comment]
@AgilentGCMS You can configure:
```
    "editor.occurrencesHighlight": false,
    "editor.selectionHighlight": false,
```

**Comment by AgilentGCMS** [comment]
For anyone searching for this in the future, you need to put those in the "top level" of settings.json, **not** in `"workbench.colorCustomizations"`. That's where I was trying to put them, and they had no effect.
