### ISSUE TITLE
Open in vscode doesn't support dots in it

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#128252]
Steps to Reproduce:

1. https://open.vscode.dev/Yash-Singh1/zoom.js
2. It returns a 404, while my other repositories without a dot work

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this. This is actually a very interesting issue: dots are fine, but the problem is with repos that end in `.js` or `.css` and it was due to the Azure Static Web Apps configuration.

I've fixed it and will push to prod in a few mins :)
