### ISSUE TITLE
Use bug icon for debug session terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128251]
Just spotted https://github.com/microsoft/vscode/pull/123478, should we use the `bug` icon for these as well?

<img width="253" alt="Screen Shot 2021-07-08 at 2 28 50 PM" src="https://user-images.githubusercontent.com/2193314/124993177-dbf3bf00-dff8-11eb-8599-effc9f46228d.png">

**Comment by connor4312** [comment]
I snagged this yesterday 🙂  https://github.com/microsoft/vscode-js-debug/commit/3148806968e169db99308c7280f34fadd8fee3b6

**Comment by Tyriar** [comment]
@connor4312 I was expecting it to get added here based on that other PR? https://github.com/microsoft/vscode/blob/0762d23ae7ed4dfd553b1084c9dc5fa9057f3a54/src/vs/workbench/api/node/extHostDebugService.ts#L96-L101

**Comment by connor4312** [comment]
Oh, there too. Yea we should add that.
