### ISSUE TITLE
Keyboard multi-select not working in 'Explorer \ Open Editors' and 'Source Control' windows

### ISSUE THREAD

**Issue by Rich-MSR** [microsoft/vscode#128268]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Windows_NT x64 10.0.19043

Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Go to the 'Explorer' → 'Open Editors' window.
2. Click on a file.
3. Try to multi-select using either `Shift`+`↑` or `Shift`+`↓` keys.

Nothing happens.  Same problem in the 'Source Control' window.  This worked in 1.57.
Interestingly, keyboard multi-select still works in the folder tab of the 'Explorer' window.

Also, using `Ctrl`+click still works to do multi-selection (which is the workaround).

**Comment by jeanp413** [comment]
Created a PR #128284 fixing this
