### ISSUE TITLE
wrong errors displayed

### ISSUE THREAD

**Issue by LcsGa** [microsoft/vscode#128253]
Issue Type: <b>Bug</b>

I've created an nx project with both angular and next used on it.
For the angular part, I'm using the primeng library.
Everything works / compiles pretty well, but vscode underlines everything that comes from primeng and displays the angular error for it.
Seeing some red lines everywhere is a little annoying :p

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 1385)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (7.93GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0a804206-16e6-4ab3-ab47-744d65a201ff|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.4
project-manager|ale|12.2.0
ng-template|Ang|12.1.1
node-js-dependency-manager|asl|1.1.2
project-templates|can|1.2.0
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.13.0
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|11.5.1
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.213
error-gutters|Igo|1.0.1
webpack|jer|2.2.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
mongodb-vscode|mon|0.5.0
vscode-typescript-next|ms-|4.4.20210707
vsliveshare|ms-|1.0.4531
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.8.0
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|1.6.1
LiveServer|rit|5.6.1
prettier-plus|svi|4.2.2
vscode-workspace-explorer|tom|1.5.0
vscodeintellicode|Vis|1.2.14
vscode-conventional-commits|viv|1.21.3
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehovct:30309550
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Are these errors in your angular code or the JavaScript or TypeScript? Are they being provided by an extension?

**Comment by LcsGa** [comment]
They only are in my html, on every external component that I still import well in my different modules (and the very first time I started my project, there was no issue)
![image](https://user-images.githubusercontent.com/58547290/125046870-b28d6e80-e09e-11eb-9bc3-b3947bf29d14.png)

**Comment by LcsGa** [comment]
By the way, I have another project using primeng components and everything works well! No errors displayed (I'm repeating myself but despite those 'errors' the projects compiles and works perfectly well)

**Comment by mjbvz** [comment]
Thanks. These errors are coming from one of your extensions. VS Code doesn't provide angular specific errors out of the box
