### ISSUE TITLE
VS Code Terminal doesn't autofocus

### ISSUE THREAD

**Issue by LucasRafaelGoncalves** [microsoft/vscode#128255]
VS Code Terminal doesn't autofocus when I create a new instance after update 1.58.0-1625728071

**Comment by biro456** [comment]
I'm also seeing this.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.32GB free)|
|Process Argv|--crash-reporter-id 4db21ffc-61bb-4e0f-84f1-1d0c8fc0bf39|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (4 x 3792)|
|Memory (System)|7.77GB (3.33GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
Handlebars|and|0.4.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
remote-wsl|ms-|0.58.2
proto|pet|0.0.2
toml|be5|0.5.1
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
vscode-graphql|Gra|0.3.16
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
vscode-kubernetes-tools|ms-|1.3.3
vscode-xml|red|0.17.0
vscode-yaml|red|0.21.0
rust|rus|0.7.8
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
This is working in insider's. Thanks for reporting - the fix will be in the recovery build.

**Comment by bboychris168** [comment]
I get this long line word when i open the terminal.
![image](https://user-images.githubusercontent.com/43663480/125389321-5f8c2200-e3e4-11eb-8dc4-3576f6b13976.png)

**Comment by Tyriar** [comment]
Repro:

1. Load window without terminal showing
2. ctrl+` to toggle terminal, it's focused correctly
3. Kill it via bin icon
4. ctrl+` to toggle terminal, it's not focused correctly 🐛 

The single tab isn't present when this happens:

![image](https://user-images.githubusercontent.com/2193314/125616036-b6eb2652-a5b0-443d-95a9-fb4d9f8aa282.png)

This is already fixed in insiders.
