### ISSUE TITLE
Gutter color should be consistent with scrollbar for new content

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12829]
For newly added content, color on gutter should be consistent with the one in scrollbar.

![image](https://cloud.githubusercontent.com/assets/4033249/18893684/cd14c58c-84c3-11e6-92bb-f48b74220836.png)

![image](https://cloud.githubusercontent.com/assets/4033249/18893697/dcaf12e0-84c3-11e6-8e1b-080089543ef5.png)

**Comment by joaomoreno** [comment]
Where does that blue come from? AFAIK Code doesn't have those decorations, is that an extension?

**Comment by octref** [comment]
@joaomoreno It's the git integration on the scrollbar I believe. I tried running vscode with `--disable-extensions` it's still there:

![image](https://cloud.githubusercontent.com/assets/4033249/18918899/15a2666e-8551-11e6-8b52-c7bdc1744c6f.png)

Same for deleted lines (red left & blue right):

![image](https://cloud.githubusercontent.com/assets/4033249/18918984/632c5cfa-8551-11e6-9c75-6dda9deea3b7.png)

**Comment by joaomoreno** [comment]
Oh yeah, sorry man, totally spaced out there.

This was a purposeful decision. We decided to go with blue for the scrollbar colour, independently of the type of code change, to reduce traffic light syndrome.

If you feel passionate about it, we can make it into a setting.

**Comment by octref** [comment]
@bgashler1 Any thoughts?

Possibly related: #8017

**Comment by octref** [comment]
These are `incomingBaseColor` from here: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/theme/common/colorRegistry.ts#L282
and `editorGutterAddedBackground` from here:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L711-L715

@alexandrudima Can we make them consistent, or is this as-designed?
Should I try to submit a PR against these two files or each of the included themes?

**Comment by alexandrudima** [comment]
@octref I did not define those colors. fyi they are configurable AFAIK and @aeschli changed them to be green<->green, blue<->blue and red<->red both in the line decorations and in the overview ruler and the feedback was overwhelmingly negative.

**Comment by octref** [comment]
They are indeed configurable through themes.

> @aeschli changed them to be green<->green, blue<->blue and red<->red both in the line decorations and in the overview ruler and the feedback was overwhelmingly negative.

I guess that's how dark plus should be colored then.
My theme (Nord) is consistent so I don't mind it.
