### ISSUE TITLE
Unbound Breakpoints - Typescript

### ISSUE THREAD

**Issue by JClevengerGeico** [microsoft/vscode#128238]
I am trying to debug using the Debugger for Chrome, and my breakpoints become unbound on run. I am new to typescript/visual studio code so please bear with me :). 

I have gone through a good amount of similar issues here, and I can't seem to figure out a fix for my issue:

![image](https://user-images.githubusercontent.com/51483726/124980161-09913600-e002-11eb-9746-a50639cfe1f4.png)

![image](https://user-images.githubusercontent.com/51483726/124980732-c2577500-e002-11eb-9962-a5f044cf19ee.png)

I have attempted to add outfiles and that doesn't seem to help either. Here is my current launch.json:

`{
    "configurations": [
    {
        "name": "Launch Chrome",
        "request": "launch",
        "type": "pwa-chrome",
        "url": "http://localhost:38116",
        "webRoot": "${workspaceFolder}",
        "trace": true
    }
    ]
}`

Below is my trace logs:

[vscode-debugadapter-cd81f8c7.json.gz](https://github.com/microsoft/vscode/files/6786849/vscode-debugadapter-cd81f8c7.json.gz)

**Comment by connor4312** [comment]
It does not look like the file

```
c:/Dev/Provision.DevOpsCatalog/src/UI/src/projects/dctpro/blades/override-container-images/override-container-images.ts
```

was loaded by your application, at least not while you were gathering logs for it. The breakpoint will not be bound until the corresponding source or compiled code is loaded.

While I don't see that filename being loaded anywhere, I also don't see anything in the `dctpro` being loaded, but there are files like `c:/src/blades/blade-navigation.ts`. If you are working in a symlinked folder, you may want to disable [webpack's symlink resolution](https://webpack.js.org/configuration/resolve/#resolvesymlinks) to preserve the paths to the files you're working on.

**Comment by JClevengerGeico** [comment]
Here is logs of me getting to the actual file in question. The code goes through the .ts with out hitting the breakpoint:

[vscode-debugadapter-fc81bc70.json.gz](https://github.com/microsoft/vscode/files/6788592/vscode-debugadapter-fc81bc70.json.gz)

**Comment by JClevengerGeico** [comment]
After doing more research, it looks like it was because I was using the correct folder level when adding to my Launch.JSON for the below properties:

```
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.chrome",
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      }
```

Once I updated those paths and opened my project at the correct folder, I was able to use breakpoints.

**Comment by JClevengerGeico** [comment]
After doing more research, it looks like it was because I was using the correct folder level when adding to my Launch.JSON for the below properties:

```
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.chrome",
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      }
```

Once I updated those paths and opened my project at the correct folder, I was able to use breakpoints.
