### ISSUE TITLE
Using command line to open vscode causes code warning

### ISSUE THREAD

**Issue by YashSaxena9** [microsoft/vscode#128279]
Issue Type: <b>Bug</b>

Opening a folder in vscode using terminal causes this warning.

>Warning: 'sandbox' is not in the list of known options, but still
>passed to Electron/Chromium.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|9, 6, 3|
|Memory (System)|7.66GB (0.37GB free)|
|Process Argv|--no-sandbox nodejsSelfStudy/ --crash-reporter-id 6f94af77-0e89-4dd0-91ba-5e3b74b9c614|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.2.0
wallpaper-setting|Ang|0.5.1
vscode-color|ans|0.4.5
docs-view|bie|0.0.9
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
comment-anchors|Exo|1.9.5
vscode-open-in-application|fab|1.0.6
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.4
vscode-drawio|hed|1.5.0
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.0
sublime-keybindings|ms-|4.0.9
vscode-typescript-next|ms-|4.4.20210708
vsliveshare|ms-|1.0.4531
debugger-for-chrome|msj|4.12.12
vs-html-to-css|nep|1.0.0
material-icon-theme|PKi|4.8.0
material-product-icons|PKi|1.0.4
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
pdf|tom|1.1.0
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.13
html-css-class-completion|Zig|1.20.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by hp77-creator** [comment]
I see the same issue, why does this happen?

**Comment by deepak1556** [comment]
Did you install vscode via snap ? Do you see the same issue with deb package ?

**Comment by jugmac00** [comment]
@deepak1556 I see the same problem - I installed VS Code via Snap ( Ubuntu 18.04 ).

**Comment by Anduh** [comment]
v.1.58, installed with snap, Linux Mint 20.1

**Comment by jfdoolster** [comment]
same issue here, ubuntu 20.04. vscode installed though snap with
```
sudo snap install --classic code
```

**Comment by therealphatmike** [comment]
same issue on ubutnu 21.04 installed via snap with `sudo snap install --classic code`

**Comment by lullofthesea** [comment]
> Did you install vscode via snap ? Do you see the same issue with deb package ?

Ubuntu 20.04 - Same issue when installing with `sudo snap install code --classic`

Installing via deb package did not have this issue (works without warning being displayed).

**Comment by YashSaxena9** [comment]
> Did you install vscode via snap ? Do you see the same issue with deb package ?

I installed vscode via snap.
I also tried to use vscode with deb package but then I run into #113175 issue, which makes it impossible to use vs code with non-zero zoomlevel. :(

**Comment by jerryHolurantie** [comment]
I'm having this same issue!

Installed vscode via snap

pop os 21.04

> Did you install vscode via snap ? Do you see the same issue with deb package ?

**Comment by brufelix** [comment]
Estou tendo o mesmo problema. 

Instalei via snap.
```bash 
sudo snap install --classic code

```

**Comment by scaomath** [comment]
Interestingly, I had the same issue before. Using `snap` to install VSCode induces some other problems as well, for example #96041

Now I just manually download the `.deb` file and use `apt` to install it.

**Comment by TheTrio** [comment]
Have the same problem on Ubuntu 20.04. Like others, used snap to install VS Code. I don't think I ever saw this warning before the June update.

**Comment by jfdoolster** [comment]
On ubunut 20.04: 
I uninstalled my snap version, downloaded the .deb file, and installed it with apt

The commands were
```bash
sudo snap remove code # saves snapshot for 31 days

# download .deb from web
cd ~/Downloads/
sudo apt install ./code_<VERSION>_amd64.deb
```

[vscode download](https://code.visualstudio.com/download#)

**Comment by rajuAhmed1705** [comment]
I am facing the same problem in ubuntu 20.04

**Comment by myvotop** [comment]
I am facing the same problem in elementary os, installed from snap

**Comment by jobic10** [comment]
I thought I had mess with my Ubuntu 20.04. 
I am still facing this; I just ignore. But is there any fix for it, yet ?

**Comment by deepak1556** [comment]
@jobic10 can you provide the output of `code --version` and also did you install it via snap ?
