### ISSUE TITLE
Format on Save and Format produce different results

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12827]
Testing #12639.

Version 1.6 insiders
MacOS

Below is a case in which the result of auto-format and the result of an explicit format differ. 

![wubg3io1fr](https://cloud.githubusercontent.com/assets/4674940/18893589/692f9876-84c3-11e6-9de7-5c6c8d753936.gif)

**Comment by jrieken** [comment]
@kieferrm This is a JS or a TS file?

**Comment by kieferrm** [comment]
@jrieken this is a JS file.

**Comment by jrieken** [comment]
@kieferrm I cannot reproduce with similar code. Please point me to your code location or paste it here

**Comment by jrieken** [comment]
@kieferrm ping

**Comment by jrieken** [comment]
Closing until steps allowing to reproduce this are supplied
