### ISSUE TITLE
Editor Freeze frequently for 5-10 secs

### ISSUE THREAD

**Issue by pfizer-kaushik** [microsoft/vscode#128214]
Issue Type: <b>Performance Issue</b>

1. I have disable all extensions
2. Vscode still freeze frequently on loading application as well as while working  with application
3. This freeze is brief but annoying.
4. Looks like some process run in between but not able to get the root cause.

<code>
❯ code --status
2021-07-08 15:25:39.707 Electron[52486:5328424] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
Version:          Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS Version:       Darwin x64 19.6.0
CPUs:             Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)
Memory (System):  16.00GB (0.18GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id c2937732-1a92-4551-8daf-7f1157f84c83
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
   33	   115	 51634	code main
   12	    66	 51639	   gpu-process
    0	    33	 51642	   utility
   34	   246	 51647	   window (package.json — graphql)
    1	    98	 51648	     extensionHost
    0	   115	 51652	       electron_node tsserver.js 
    0	   131	 51653	       electron_node tsserver.js 
    0	    82	 51683	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 51713	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=51648
    0	    33	 51650	     watcherService
    0	    33	 51714	     searchService
    0	   115	 51649	   shared-process
    0	    33	 51651	     ptyHost
    0	     0	 51665	       /bin/zsh -l
    1	    82	 51772	   window (Process Explorer)

Workspace Stats: 
|  Window (package.json — graphql)
|    Folder (graphql): 15 files
|      File types: json(4) js(3) gitignore(2) md(1)
|      Conf files: package.json(2)
<code>

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id c2937732-1a92-4551-8daf-7f1157f84c83|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    82	 51634	code main
    0	    33	 51639	   gpu-process
    0	    16	 51642	   utility
    2	    66	 51649	   shared-process
    0	    16	 51651	     ptyHost
    0	     0	 54755	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   20	   197	 54731	   window (Getting Started)
    0	    98	 54732	     extensionHost
    0	    49	 54748	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0702:30334633

```

</details>

**Comment by pfizer-kaushik** [comment]
`❯ code -insiders --status
Warning: 'i' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
^[[A2021-07-08 19:35:49.808 Electron[54987:5525893] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
Version:          Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS Version:       Darwin x64 19.6.0
CPUs:             Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)
Memory (System):  16.00GB (0.28GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id c2937732-1a92-4551-8daf-7f1157f84c83
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
   35	    98	 51634	code main
    6	    66	 51639	   gpu-process
    1	    16	 51642	   utility
    1	    82	 51649	   shared-process
    0	    16	 51651	     ptyHost
    0	     0	 54994	       /bin/zsh -l
    0	   180	 54731	   window (Visual Studio Code)
    0	    98	 54732	     extensionHost
    0	    66	 54748	   window (Issue Reporter)
  161	   229	 54982	   window (package.json — server)
   15	    98	 54992	     extensionHost
    5	    49	 55027	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=54992
    4	    33	 54993	     watcherService
    3	    33	 55034	     searchService

Workspace Stats: 
|  Window (package.json — server)
|    Folder (server): 4 files
|      File types: json(2) js(1)
|      Conf files: package.json(1)

`

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
