### ISSUE TITLE
'Launch VS Code' debug configuration recently stopped working in Insiders 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#128259]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.58.0-insider (user setup) 2d23c42a936db1c7b3b06f918cde29561cc47cd6
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create Codespace for microsoft/vscode
2. `yarn install` and Ctrl+Shift+B to build tasks
3. Click on 'Launch VS Code' debug configuration
4. 🐛 debug target refused (Note, this was working for me Tuesday night PST, when I submitted https://github.com/microsoft/vscode/pull/128100, so something has recently changed to cause this problem)

![image](https://user-images.githubusercontent.com/30305945/124999929-0434eb00-e004-11eb-887b-a24b5a8b7195.png)

Possibly related: https://github.com/microsoft/vscode/issues/127861

**Comment by connor4312** [comment]
Is anything listening on port 9222? Do you have any existing OSS window open?

**Comment by joyceerhl** [comment]
Nothing listening on 9222, no OSS windows open. Should there be?

**Comment by connor4312** [comment]
When you run the launch config, the OSS window does not open?

**Comment by joyceerhl** [comment]
Just tried it again and it's working now 🤦‍♀️ Thank you!
