### ISSUE TITLE
"Open in Visual Studio Code" as part of GitHub UX?

### ISSUE THREAD

**Issue by Xeevis** [microsoft/vscode#128292]
Hello, I'm not sure if this is the right place to ask, I've noticed VS Code 1.58.0 [suggests adding a badge to README](https://code.visualstudio.com/updates/v1_58#_open-in-vs-code-badge) for use with remote repositories extension. I'm afraid adoption will be very sporadic for such a cool feature. Wouldn't it be possible for VS Code team to pull some weight and get this integrated into GitHub UX, so it's available for all repositories?

![image](https://user-images.githubusercontent.com/5835044/125047941-be2d6500-e09f-11eb-8153-df541863c825.png)

**Comment by joaomoreno** [comment]
It would be awesome, I suggest reaching out to GitHub about it. 👍
