### ISSUE TITLE
Building Angular Project making system lock

### ISSUE THREAD

**Issue by manasadade** [microsoft/vscode#128294]
1.Open Angular project folder in visual studo code
2.build using ng serve
3. During compilation itself, VS code is making my Windows 10 Home PC locked..
4. This happed many times

**Comment by joaomoreno** [comment]
What do you mean by locked? Can you share a screenshot?

**Comment by manasadade** [comment]
![VScodeIssue](https://user-images.githubusercontent.com/60777341/125155560-77fb0300-e17e-11eb-9c93-6782bd2f1923.jpeg)

When compiler about to  compile " @angular/platform-browser/animations: " , my windows system is going to locking mode , Locking and turned off.. Again I have to press Power button to restart it, provide my login credentials , then start working on it...
This is happening every time.

**Comment by joaomoreno** [comment]
This doesn't seem related to VS Code at all. Can you reproduce using an external terminal?

**Comment by manasadade** [comment]
I could not reproduce this issue when using external terminal..
