### ISSUE TITLE
Webpack error and powershell problem

### ISSUE THREAD

**Issue by lindamacdonald** [microsoft/vscode#128246]
Hey there guys :)
I have just installed visual studio code on my new laptop and am trying to run a simple react project, but none of the components are loading so I checked the issue in the console and the issue was coming from webpack. The file is massive so have just taken a screenshot to show you. Attached here.
https://drive.google.com/file/d/1-3NhpYtp0Rmu2DObW9aR-VLgR6bZr3Dj/view?usp=sharing

I noticed that someone else had a similar issue and it had to do with the integrated terminal. The solution was to change the internal terminal from powershell to C:\WINDOWS\System32\cmd.exe.

In my settings my terminal is set to C:\WINDOWS\System32\cmd.exe, but when I look at the terminal actually running in the bottom of visual studio code it clearly says powershell and I am unable to change it. Can I fix this somehow?

**Comment by meganrogge** [comment]
Can you please provide me with your terminal settings?
You should be able to create a command prompt directly from this dropdown
![recording (28)](https://user-images.githubusercontent.com/29464607/125024888-7cb49f80-e036-11eb-9e9b-034cfa3111f4.gif)

**Comment by lindamacdonald** [comment]
Hey there Megan :)

thanks a mil for getting back to me. I tried changing the terminal settings in the terminal but still nothing was working...its like the file extension js isnt recognized so probably set the whole thing up wrong I suspect because I have had a problem running any js files in the ide strangely. Do you have any tutorials that you can recommend on how to setup up visual studio code and how to configure the settings to properly run nodejs/react projects in visual studio code? That would be so good. I couldnt find any onine which are new so a bit difficult to follow those :)
thanks in advance

**Comment by meganrogge** [comment]
Hey Linda, maybe try this one? https://code.visualstudio.com/docs/nodejs/reactjs-tutorial
