### ISSUE TITLE
multiline editing and editing tags doesn't work

### ISSUE THREAD

**Issue by TenSketch** [microsoft/vscode#128319]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

not able to do multi line editing
and
tags editing 
eg
<section></section>
if i'm changing section into div
<div></section>
closing tag doesn't change automatically

![image](https://user-images.githubusercontent.com/23096153/125093755-40de1080-e0f0-11eb-8fec-a20c656f9bc7.png)

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.55GB free)|
|Process Argv|C:\\Users\\bala\\Downloads\\Compressed\\Amazing_design-main\\Amazing_design-main --crash-reporter-id a9e61459-2b8a-4be4-8763-ecf8cc7b0405|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.0.1
vsliveshare|ms-|1.0.4531
vsliveshare-audio|ms-|0.1.91
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.17
bootstrap4-vscode|the|6.1.0
remove-empty-lines|use|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by aeschli** [comment]
Did you enable `editor.linkedEditing` ?

**Comment by TenSketch** [comment]
> Did you enable `editor.linkedEditing` ?
Yeah checked the settings and applied both linked editing and multi cursor editing. it is working. Thank you
