### ISSUE TITLE
Open File Regex Replace escape is inconsistent

### ISSUE THREAD

**Issue by Wayne-II** [microsoft/vscode#128316]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I copied this template from Github

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Fresh install - File->Preferences->Extensions: Installed 0
Version: 1.59.0-insider (user setup)
Commit: 87d692b7bf1eb5a663b3e62620a6e7e436e1838c
Date: 2021-07-09T05:13:26.890Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
- OS Version:
Windows_NT x64 10.0.19041

Steps to Reproduce:

1. start code: C:\Users\Coder 3\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-insiders" --disable-extensions
2. Press CTRL+H with a file open
3. create a regex with a group, excluding forward slashes (/): /Name=([a-zA-Z0-9_]+).*/
4. replace matches with something that has an escaped dollar sign ($) immediately before referencing the matched group /\$$1/
5. try other replace strings /$$1/, /$$$1/, /\\$1/
6. compare inconsistencies between escaping dollar sign and other characters ( I can't think of any other than a backslash )

/\$$1/
Expected result:
$ID_NO
Actual Result:
\$ID_NO

/$$1/
Expected result based on above results:
$ID_NO
Actual Result:
$1

/$$$1/
Expected result based on above results:
$ID_NO
Actual Result:
$ID_NO

/\\$1/
Expected result based on above results:
\\$1
Actual Result:
\ID_NO

When escaping a dollar sign before a group it seems that it does perform the escape, however it doesn't exclude the escaping-backslash from the output replacement.  This doesn't happen with the only other escape I can think of, which is the escape character itself, the backslash ( \ )

Sample line to test against that I copied this from HeidiSQL in order to build my model in PHP.
Name=ID_NO<|||>OldName=ID_NO<|||>DataType=3<|||>OldDataType=52<|||>LengthSet=10<|||>Unsigned=0<|||>AllowNull=0<|||>ZeroFill=0<|||>LengthCustomized=0<|||>DefaultType=3<|||>DefaultText=AUTO_INCREMENT<|||>OnUpdateType=0<|||>OnUpdateText=<|||>Comment=<|||>Charset=<|||>Collation=<|||>GenerationExpression=<|||>Virtuality=<|||>Status=0

VS Code version: Code - Insiders 1.59.0-insider (87d692b7bf1eb5a663b3e62620a6e7e436e1838c, 2021-07-09T05:13:26.890Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.25GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 70b50d9f-f396-4869-8389-436866d8f2f7|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by alexdima** [comment]
Under the hood we're calling JavaScript's [String.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement), so you are observing JavaScript's replacement pattern escaping behavior.

Evaluating the following in Chrome:
```js
console.log('Name=ID_NO'.replace(/Name=([a-zA-Z0-9_]+).*/g,'$$1'));
// prints: $1
console.log('Name=ID_NO'.replace(/Name=([a-zA-Z0-9_]+).*/g,'$$1'));
// prints: $ID_NO
console.log('Name=ID_NO'.replace(/Name=([a-zA-Z0-9_]+).*/g,'\\$1'));
// prints: \ID_NO
```

We don't have any plans to implement our own variant of `String.replace`.
