### ISSUE TITLE
Ability to reorder grouped terminal tabs

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#128336]
Given the following:
![image](https://user-images.githubusercontent.com/2644648/125110714-cb475580-e099-11eb-9138-43cd17157e45.png)

I wanna drag `Ext - Build` down on top of `Core - Build` to reorder them and I want the terminals to switch position in the split so `Core - Build` will be on the left.

**Comment by Tyriar** [comment]
Originally you could unsplit terminals by dragging them to the bottom, we felt it was a little confusing mixing rearranging groups with moving terminals out of groups as well. But this seems reasonable as a special case to rearrange within a group if both source and target share the same group.
