### ISSUE TITLE
VSCode can't open terminal by system software policy

### ISSUE THREAD

**Issue by cpdyj** [microsoft/vscode#128389]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0 (system)
- OS Version: Windows 10 21H1 19043.1083

Steps to Reproduce:

1. Setup the Software Policy (in computer policy / Windows Settings / Security Settings)
2. Open terminal in vscode --> fail.

I don't sure it's a bug or not.
I wondered why Vscode open pty by the `\\?\` prefixed path, and the document doesn't mention it.
Windows default Software policy only allow `C:\WINDOWS` but without `\\?\C:\WINDOWS`
So maybe the documents could be update to provide more information?

**Comment by Tyriar** [comment]
The \\?\ is a UNC path https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention

It sounds like you're intentionally blocking what the terminal needs to do by setting up this policy? I'm not too familiar with software policies in Windows but can you opt out the VS Code install directory or something?
