### ISSUE TITLE
Opens the folder with the folder '.vscode' instead of the folder from which the last file was opened

### ISSUE THREAD

**Issue by mishchenkoandrey** [microsoft/vscode#128383]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Open VS Code.
2. Try to open file (press Ctrl + O or another way).

Expected result:
Opens the folder from which the last file was opened.

Actual result:
Opens the folder with the folder '.vscode'.

3. Press Esc.
4. Try to open file (press Ctrl + O or another way).

Expected and actual results are the same:
Opens the folder with the folder '.vscode'.

**Comment by isidorn** [comment]
I believe this is expected behavior, but forwarding to @bpasero so he can decide to close

**Comment by bpasero** [comment]
I thought we are not doing this anymore (@chrmarti might know who I believe originally added this).

**Comment by mishchenkoandrey** [comment]
Hi.

In this gif I

1. Open a file from some folder (frontend-project-lvl3)
2. Close this file
3. Close VS Code
4. Open VS Code
5. Try to open file

Expected result:
Opens the folder frontend-project-lvl3.

Actual result:
Opens the folder with the folder '.vscode'.

6. Close the window "Open file"
7. Try to open file

Expected and actual results are the same:
Opens the folder frontend-project-lvl3.

![recording](https://user-images.githubusercontent.com/51906367/127832012-d2ae789a-3b7f-4997-bada-5c01f4de4cb4.gif)

**Comment by bpasero** [comment]
That is indeed strange, it seems to me that the first time using the dialog you get a different path compared to using the dialog a second time right?

**Comment by mishchenkoandrey** [comment]
> That is indeed strange, it seems to me that the first time using the dialog you get a different path compared to using the dialog a second time right?

Yes, the first time - the path to the folder containing the ".vscode" folder, the second time - the path to the last parent folder.

**Comment by bpasero** [comment]
I can reproduce even when configuring `"files.simpleDialog.enable": true` so I suspect an issue somewhere in our abstract file dialog service implementation. Here are the exact steps:
* open VSCode (1 window) and bring it into empty state (File > Close Folder)
* open a single file (File > Open File) from a folder that has a top level `.vscode` folder
* close the editor tab
* close the window
* open again 1 window (it should open empty)
* open a single file (File > Open File) and notice how the user home dir is picked by default
* do the exact same action again and see how the previous folder is picked

@alexr00 please pass back to me if you think this is an issue somewhere else, thanks.

**Comment by bpasero** [comment]
Interestingly I was not able so far to reproduce on macOS. I am also not 100% sure the `.vscode` folder is any relevant in the steps...

**Comment by mishchenkoandrey** [comment]
I have established that the 'Open Recent' menu has a fixed path where the folder is opened when it is first opened. I can't delete it, 'Clear Recently Opened' doesn't help.

[http://joxi.ru/v29Eze4FRGbdJ2](http://joxi.ru/v29Eze4FRGbdJ2)

**Comment by alexr00** [comment]
I'm no longer able to reproduce this issue. Please do comment if you still see it happening with version 1.61 (insiders)!
