### ISSUE TITLE
Next/Prev Group should not create new group

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12833]
- VSCode Version: 1.6.0
- OS Version: OS X 10.11.6

Currently if you have group 1 & 2 and is on 2, `Go -> Switch Group -> Next Group` will create Group 3. Instead it should go to group 1.

If you have group 1, 2 & 3 and focus is on 3, `Go -> Switch Group -> Next Group` will do nothing. It should go to group 1, too.

**Comment by bpasero** [comment]
I think we should not change the behaviour you mention first, but the latter can be done I think.

Sounds like a good area for a Pull Request.

**Comment by octref** [comment]
Currently when you have Group  1 & 2 & 3 and is on 1, running `Prev Group` does nothing. I can also make it go 3.
But if you have Group 1 & 2 and is on 1, should `Prev Group` create 3 and go to 3, or just go to 2?

**Comment by hun1ahpu** [comment]
@bpasero: Both Sublime and Atom do not add new Group on Next/Prev but just circle through existing ones. It kind of makes sense.

**Comment by thiagoh** [comment]
Any updates on this issue, by chance? I mean, it's really boring have to close the group when you're on group 2 and then triggers move to next group and it creates a new group.. I think it should circle back to group 1 (if there is no group 3 already, obviously)
