### ISSUE TITLE
[sass] Strings are colored same way as values in dark theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1283]
Sass file, notice how the light theme nicely distinguishes between strings and values and the dark theme does not

<img width="200" alt="screen shot 2015-12-14 at 15 37 00" src="https://cloud.githubusercontent.com/assets/1926584/11783632/8be8e4d6-a278-11e5-9ffe-34c2bbbb0e59.png">
<img width="227" alt="screen shot 2015-12-14 at 15 37 25" src="https://cloud.githubusercontent.com/assets/1926584/11783669/ace0f0e8-a278-11e5-91cc-38937d6d4673.png">

**Comment by aeschli** [comment]
fixed
