### ISSUE TITLE
Support underline and strikethrough in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128321]
Currently underline is supported in dom and canvas renderers, strikethrough isn't supported in either.

Repro:

1. Open terminal on Linux/macOS/WSL
2. Run `echo -e '\x1b[4mUnderline\x1b[24m \x1b[9mStrikethrough\x1b[29m \x1b[4;9mBoth\x1b[0m'`

Expected:

![image](https://user-images.githubusercontent.com/2193314/125096300-ddb99300-e089-11eb-8afd-3e1f3e1bce2a.png)

Upstream:

- https://github.com/xtermjs/xterm.js/issues/580
- https://github.com/xtermjs/xterm.js/issues/2251
- https://github.com/xtermjs/xterm.js/pull/3386

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/125517474-a89b2584-b499-4631-8e4b-e749590efa24.png)

**Comment by frankli0324** [comment]
thanks. I can confirm this.
