### ISSUE TITLE
Cannot open terminals

### ISSUE THREAD

**Issue by KlausSchaefers** [microsoft/vscode#128339]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: : 1.58.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open VS Code
2. Click Terminal in Menu
3. New Terminal
4. Terminal will be closed instantly

https://user-images.githubusercontent.com/7108416/125113544-b7731200-e0e0-11eb-8334-2d4801b7d336.mp4

**Comment by meganrogge** [comment]
any errors in the dev tools console?

**Comment by KlausSchaefers** [comment]
After a reboot I cannot reproduce the error.

Megan Rogge ***@***.***> schrieb am Mo., 12. Juli 2021, 22:21:

**Comment by KlausSchaefers** [comment]
Closed != Fixed :)

Megan Rogge ***@***.***> schrieb am Di., 13. Juli 2021, 15:14:

**Comment by anaritadauane** [comment]
Hi, I have the same problem.

**Comment by anaritadauane** [comment]
How did you fix your problem?

**Comment by KlausSchaefers** [comment]
Rebooted my machine and closed all terminals before

anaritadauane ***@***.***> schrieb am Do., 15. Juli 2021,
15:33:

**Comment by anaritadauane** [comment]
it worked, thank you :)
