### ISSUE TITLE
Default presentation of Explorer: Copy Relative Path Separator in Setting editor is confusing

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#128345]
Issue Type: <b>Bug</b>

Would be noticeable on Windows because of (implicit) default `\\`.

Steps to reproduce:
0. Make sure you are using Windows and reset `explorer.copyRelativePathSeparator` to default value.
1. Open Settings view and search for `explorer.copyRelativePathSeparator` - dropdown has `/` displayed (and setting not changed - no blue border).
![image](https://user-images.githubusercontent.com/1312662/125120537-383f0780-e0fb-11eb-9673-1fcc3a2fb75f.png)

1. Perform Copy Relative Path - path copied with `\\` in it (while dropdown displays `/`)
1. Change setting to `\\` and then "back" to `/` - setting now marked as changed
![image](https://user-images.githubusercontent.com/1312662/125120580-4bea6e00-e0fb-11eb-801e-0a89eaebf273.png)

1. Perform Copy Relative Path - path copied with `/` in it as expected

I think it's because this setting doesn't have default value and dropdown will display first from list, however implementation has different logic.

VS Code version: Code - Insiders 1.59.0-insider (87d692b7bf1eb5a663b3e62620a6e7e436e1838c, 2021-07-09T05:13:26.890Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.15GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
bridge0708:30335490

```

</details>

**Comment by bpasero** [comment]
I added a `auto` default.

//cc @rzhao271 maybe this is a bug for the settings editor: if a setting is a `enum` without a `default`, shouldn't the dropdown indicate this by not showing the setting?
