### ISSUE TITLE
Opening files/tabs

### ISSUE THREAD

**Issue by MasterKavi-24** [microsoft/vscode#128385]
Issue Type: <b>Feature Request</b>

I opened a file. It created a new tab. Then I clicked another file. But no new tab was created. Instead, the previously opened tab was replaced by the new one. This happens regardless of the different extensions the old file and the new file are. I need to open the file in new tabs everytime I click on them from the Explorer or I open them from the File Explorer.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by IllusionMH** [comment]
/question
This is called Preview and controlled by settings `workbench.editor.enablePreview`, `workbench.editor.enablePreviewFromQuickOpen`, and `workbench.editor.enablePreviewFromCodeNavigation`.

See more about this feature in docs [Preview mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode)

If you want to disable it - make sure 3 settings above are set to `false`

**Comment by MasterKavi-24** [comment]
Thank you @Github @Andrii Dieiev ..... Also, is there any newsletter that
post useful infos on VS Code ? If there is one, please subscribe me there.
If not, could you post something useful ?
