### ISSUE TITLE
Kill terminal button works only once.

### ISSUE THREAD

**Issue by heysujal** [microsoft/vscode#128320]
Issue Type: <b>Bug</b>

Open VS Code -> Terminal -> New terminal .
Click on kill terminal button. It works.
Now again ,
Terminal -> New Terminal -> Kill terminal.
It does not work.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.31GB free)|
|Process Argv|--crash-reporter-id 253b8a9a-5831-4c1c-843e-c5cae608c81e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by heysujal** [comment]
https://user-images.githubusercontent.com/55016909/125095431-c7dfb880-e0f1-11eb-92cc-df54f2beb627.mp4

**Comment by spiderseo** [comment]
Hi there my visual studio terminal is not working properly, please watch the recording, thank you!

https://user-images.githubusercontent.com/86869734/125183027-94c42480-e1d8-11eb-8445-49638998f49d.mp4

**Comment by Diogo-Rossi** [comment]
@spiderseo see if [this workaround helps ](https://github.com/microsoft/vscode-python/issues/16640#issuecomment-877838656)
