### ISSUE TITLE
Searching for File in Command Palette Shows Duplicate Matches

### ISSUE THREAD

**Issue by pzelnip** [microsoft/vscode#128350]
Issue Type: <b>Bug</b>

When I search for a file in the palette (cmd+p), all matches show up twice.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.18GB free)|
|Process Argv|--crash-reporter-id 5225aa10-88cc-4190-806e-64c0ca493f30|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-base64|ada|0.1.0
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.2.0
vagrant|bbe|0.5.0
django-html|bib|1.3.0
emojisense|bie|0.8.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.42.1
vscode-faker|dee|1.5.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
hadolint|exi|1.1.0
url-encode|fle|1.1.0
auto-rename-tag|for|0.1.7
code-runner|for|0.11.5
seito-openfile|Fr4|1.8.8
gitlab-workflow|Git|3.25.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
terraform|has|2.13.0
rest-client|hum|0.24.5
tasks-context|jsa|1.0.0
presentationmode|jsp|1.1.5
vscode-gutter-preview|kis|0.27.1
vscode-view-in-browser|kop|1.0.5
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
HTMLHint|mka|0.10.0
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.9
autodocstring|njp|0.5.4
kitty-time|QzS|0.4.3
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.0
vscode-coverage-gutters|rya|2.8.0
partial-diff|ryu|1.4.3
jinjahtml|sam|0.16.0
jenkinsfile-support|sec|0.1.0
vscode-spotify|shy|3.2.1
vscode-fileutils|sle|3.4.5
vscode-hexdump|sle|1.8.1
sourcery|sou|0.9.1
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
vscode-djaneiro|the|1.4.2
mako|tom|0.2.0
vscode-pets|ton|1.8.0
vscode-icons|vsc|11.5.0
vscode-wakatime|Wak|14.0.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by pzelnip** [comment]
Screenshot of it:

![image](https://user-images.githubusercontent.com/414933/125129243-0787af80-e0b4-11eb-9ccd-c7fa5b7d4cf5.png)

Seemed to start right after upgrading to 1.58.

**Comment by pzelnip** [comment]
Oddly, if I open one of the duplicate matches, then close the file, and then execute the same search again that duplicate no longer shows up.  Example, before opening any:

![image](https://user-images.githubusercontent.com/414933/125130882-a57c7980-e0b6-11eb-9832-44c98b6a4af9.png)

I then opened `docker-compose.yml`, closed it, then did the same search and then `docker-compose.yml` only shows up once (but `docker-compose-dev.yml` is still a dupe match):

![image](https://user-images.githubusercontent.com/414933/125130948-c513a200-e0b6-11eb-874b-1d4f53dd476c.png)

Also note the icon beside the match when there's a dupe is different. 🤷

**Comment by TylerLeonhardt** [comment]
@pzelnip unfortunately, I can't reproduce this :( you said it only happens on a single one of your machines? Can you maybe try with a fresh user data dir:

```
code --user-data-dir /tmp/foo ./path/to/the/folder/with/the/problem
```
