### ISSUE TITLE
Multiple Copy Paste when I paste a varible in JS file

### ISSUE THREAD

**Issue by dagar07** [microsoft/vscode#128388]
Issue Type: <b>Bug</b>

- In JS file, Copy paste problem

- Issue: Need to paste only one time but it will get paste the same value repeatedly 
- Expected: Only a Single time copy variable should paste at a time
  

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 19.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 8|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|-psn_0_40970 --crash-reporter-id bef4aa07-19b6-4eaa-90f7-f77b18f27dc5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (109)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
scss-scan|aar|0.1.67
scss-lint|ada|0.1.10
vscode-nginx-conf|ahm|0.1.3
Bookmarks|ale|13.1.0
copy-relative-path|ale|0.0.2
vsc-prolog|art|0.8.23
vscode-changelog-generator|axe|1.0.4
vscode-django|bat|1.6.0
django-html|bib|1.3.0
git-easy|bib|1.11.0
simple-react-snippets|bur|1.2.3
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
cquery|cqu|0.1.10
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
vscode-author-generator|edw|0.2.2
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.22
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.0.1
git-project-manager|fel|1.7.1
bloc|Fel|5.6.2
vscode-firefox-debug|fir|2.9.4
kotlin|fwc|0.2.23
vscode-pull-request-github|Git|0.28.0
vscode-nginx-conf-hint|han|0.1.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
githd|hui|2.2.4
path-autocomplete|ion|1.17.1
RelativePath|jak|1.4.0
weex|jay|0.4.0
vscode-map-preview|jum|0.5.8
vscode-jira|Kni|0.6.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.1
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.31
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.14.0
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4531
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.5.2
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.34.1
gitpatch|par|0.2.1
material-icon-theme|PKi|4.8.0
tslint-vue|pro|1.5.6
nginx-formatter|ray|0.0.13
author-tools|rea|2018.12.0
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
move-ts|str|1.12.0
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|2.0.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-icons|vsc|11.5.0
gitblame|wad|7.0.6
full-react-snippets|wal|1.4.2
vscode-todo-highlight|way|1.0.4
vscode-weex|wee|0.0.12
weex-debugger|wee|0.0.15
weex-doctor|wee|0.1.15
weex-lang|wee|0.0.14
weex-new-project|wee|0.1.7
weex-run|wee|0.0.11
vscode-nginx|wil|0.7.2
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
txt-syntax|xsh|0.1.6
propertylist|zho|0.0.2
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it paste in same place or different across the file? Do you have multiple selections in this moment? 

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
