### ISSUE TITLE
Empty workspace: keep UI state and reopen files

### ISSUE THREAD

**Issue by thedarkfalcon** [Microsoft/vscode#12836]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Version: 1607

**Scenario:** Open files from different directories (not using the "open folder" function) by either dragging them into the editor or using Open File. Close VSC, reopen it.
**Desired Behaviour:** All previously opened files are reopened with the same view/caret position.
**Actual Behaviour:** VSC is blank when opened

I know this feature exists for "Open Folder" but that's not what I want as I rarely open files this way, normally the files span completely different directories (or even machines).

Discussed further in this thread #101 (but a separate issue).

**Comment by bpasero** [comment]
This is an issue with the fact that we do not store any UI state for empty workspaces. I think we have some duplicates here if you want to search for it.

**Comment by ranjan-ranjan** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/101

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/207
