### ISSUE TITLE
blur out .env files and show a alert box asking if you want to unblur the file

### ISSUE THREAD

**Issue by CyrusZei** [microsoft/vscode#128358]
Since a lot of devs are live coding it would be useful if as soon as you click on a .env file, that  file would be blurred out and have a prompt asking you if you want to unblur this since this is sensitive information.

**Comment by CyrusZei** [comment]
I tried to create an extension for this, but I don't think I get access to the .env files(new to creating vs code extensions) so sadge about that

**Comment by SaschaHeyer** [comment]
can we reopen this? I like the idea of hiding .env content until further approval

**Comment by CyrusZei** [comment]
How is this  `out of scope` ?

If you know how many times people have accidentally show the content in the .env file.

Add a button saying `show`  and that will "unblur" the .env file.
