### ISSUE TITLE
Comments no longer show

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#128312]
I traced it back to https://github.com/microsoft/vscode/commit/badabb990cdeede64bd477c2f74ec04317e73f56 with git bisect. Here are the repro steps:

1. Install the GitHub Pull Request extension (nightly build or stable).
2. Open a folder with a repo with PRs.
3. Open the Pull Requests view.
4. Expand a PR that has comments. https://github.com/microsoft/vscode/pull/128050 will work for this purpose. It will show in the "all" section of the PRs tree unless someone merges or closes it before you try to repro this.
5. Open a file diff that has comments in that PR. 

Expected: The comment shows
Actual: The little "there's a comment here" gutter symbol shows, but no comment.

**Comment by rebornix** [comment]
This is caused by us freezing the `CommentThread` object while the GHPRI extensions now add `threadId` to the `CommentThread`. I removed the freeze for now but we should handle this in a better way in GHPRI.
