### ISSUE TITLE
The tab bar shouldn't revert to a scrolling list when a filename is too long

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#128397]
When you have stacked tabs enabled (I forget the setting name) and you open a file with a really long name, VS Code will stop stacking tabs and revert to the default behavior of scrolling the tabs.

Instead, it should truncate the filename in the middle, like it does with long tree view items.

Edit: this may actually be a bug instead, waiting for someone from the team to chime in

**Comment by heartacker** [comment]
me too

**Comment by bpasero** [comment]
Have you tried setting `workbench.editor.tabSizing: shrink`?

**Comment by NSExceptional** [comment]
@bpasero That suggestion seems orthogonal to my feature request ;P I don't want to shrink all tabs all the time

That said, I do think this might just be a bug. IIRC, it happened once but then later on that same window was displayed exactly as I'd expect, with the ultra-log tab truncated and my other tabs stacked above it.

**Comment by bpasero** [comment]
Ok

**Comment by heartacker** [comment]
> This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

you are  bug bot :c
