### ISSUE TITLE
Full Result of run code is not showing in terminal 

### ISSUE THREAD

**Issue by Shahid6283** [microsoft/vscode#128322]
In this new update, the terminal does not show the full result of the run code when I run the code. This update is worst than the previous update. Please fix this problem. And when I used the infinite loop the terminal is not showing the full result. Terminal does not shows some results.

**Comment by weinand** [comment]
How do you run the code?
Are you using a debugger?
Please provide reproducable steps!

**Comment by Shahid6283** [comment]
I run the code using Code runner
