### ISSUE TITLE
After 1.57.0 version, the extension PHP Debug is broken.

### ISSUE THREAD

**Issue by jjasoncool** [microsoft/vscode#128310]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: after 1.57.0 **(below 1.56.2 is normal)**
- OS Version: fedora 34

Steps to Reproduce:

1.Install php_debug extension.
2.Remote php server install xdebug, when do request to the php server, php xdebug can't found php debug server (which install in vscode).
3. The structure is below:

![php_debug](https://user-images.githubusercontent.com/24731867/125076193-315fc700-e0f2-11eb-87a2-a98d476cb61a.jpg)

my remote setting is 
```json
{
    "remote.autoForwardPortsSource": "process"
}
```

wireshark get info:
[php debug.zip](https://github.com/microsoft/vscode/files/6791233/php.debug.zip)
![圖片](https://user-images.githubusercontent.com/24731867/125084330-f6fb2780-e0fb-11eb-9192-2b0e0eed5c8f.png)

Maybe relation to:
https://github.com/microsoft/vscode-remote-release/issues/4601

**Comment by jjasoncool** [comment]
@weinand This is not cause by extension.
https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_57.md#port-forwarding-tunnels-are-bound-to-localhost

This is vscode change, not extentoins fault.

**Comment by weinand** [comment]
Please file this issue against https://github.com/microsoft/vscode-remote-release
