### ISSUE TITLE
Looping problem matcher mismatches twice for wrapped lines

### ISSUE THREAD

**Issue by SchoofsKelvin** [microsoft/vscode#128352]
Issue Type: <b>Bug</b>

I noticed this bug while working with the built-in `$eslint-stylish` problem matcher where ESLint was producing long warnings/errors that resulted in line wrapping. When a line wraps, VS Code tries to problem match both the first line (with the part that'll get wrapped cut off) and then the actual "full" line, where VS Code concats the wrapped lines together.

Bug can be reproduced with this task:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Line wrapping issue",
			"type": "shell",
			"command": "echo '1:2:/test.js'; echo 'something something something something something something something something something something something something something something something something something something something something'",
			"problemMatcher": {
				"owner": "something",
				"source": "something",
				"pattern": [
					{
						"regexp": "^(\\d+):(\\d+):(.*)$",
						"line": 1,
						"column": 2,
						"file": 3
					},
					{
						"regexp": "^(\\w+) (.*)$",
						"message": 1,
						"code": 2,
						"loop": true
					}
				]
			},
			"group": "build"
		}
	]
}
```
_You might require to either change the number of `something`s or shorten your terminal's width by e.g. making the "terminal tabs" panel wider._

Running this gives me the following output and line wrapping with my "width setup" in both VS Code 1.58.0 and the latest Insiders build:
![image](https://user-images.githubusercontent.com/14597409/125134300-76422880-e107-11eb-8c3e-1edc0884708b.png)

This results in the following problems being matched in both VS Code versions:
![image](https://user-images.githubusercontent.com/14597409/125134195-501c8880-e107-11eb-8f65-7ad331778da2.png)

I've only noticed it happening with the `"code"` part of the problem matcher, but a quick debugging session of VS Code (most noticeably with a breakpoint [here](https://github.com/microsoft/vscode/blob/fd14f3ebc07f338d785979fd4fb01b3692a9e8b3/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1420)) shows that it's firing the event for both the "unfinished" and "complete" line. I couldn't get it to work for the `"message"` part, but I assume the 2nd problem is overwriting the 1st one and therefore hiding the unfinished problem.

________

VS Code version: Code - Insiders 1.59.0-insider (87d692b7bf1eb5a663b3e62620a6e7e436e1838c, 2021-07-09T05:13:26.890Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692
bridge0708:30335490

```

</details>

**Comment by alexr00** [comment]
@Tyriar what version of Windows are the line wrapping problems fixed?

**Comment by Tyriar** [comment]
21376

**Comment by alexr00** [comment]
@SchoofsKelvin I'm sad to say that we can't solve this issue due to a Windows terminal line wrapping issue that is fixed in Windows version 21376. I have a heuristic in place for the `message`, which is why you couldn't get the same issue to occur with `message`, but that same heuristic won't work for `code`. Generally, since the `code` tends to be short, most users won't run into the same issue for the code.

**Comment by SchoofsKelvin** [comment]
I see. I currently "fixed" it for me by changing the problem matcher so `code` is part of `message`. While I lose a small bit of UI interaction due to having a blank code (although the code is instead embedded in the message), the `message` heuristic does deduplicate problems. I just noticed it with `ESLint` combined with `@typescript-eslint`, as the codes are indeed usually quite long since it includes `@typescript-eslint/`.

One solution for VS Code itself that I thought of would be copying the line logic (similar to what happens [here](https://github.com/microsoft/vscode/blob/fd14f3ebc07f338d785979fd4fb01b3692a9e8b3/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1395-L1401)) on the problem matcher level, where it checks whether a previous "full" line is actually part of the following "full" line, and if so, erase the problem matched by the previous "full" line, if any. Might be a better alternative than waiting for Windows version 21376, which I feel like will take quite a bit to get released on the main channel.

Shall I close this issue, or leave it open until the public Windows version passes 21376 or so?

**Comment by alexr00** [comment]
I'll close it. It will still be searchable.
