### ISSUE TITLE
Auto format after saving a non-open tab corrupts undo history for it

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12832]
- VSCode Version: Insiders
- OS Version: Mac OSX El Capitan

Regarding test plan item #12639 

Steps to Reproduce:

![problem-focuslostsave-undostack](https://cloud.githubusercontent.com/assets/11839736/18894174/5d9c4de4-84c6-11e6-9a7d-d3eba35f79fd.gif)

1. Have some unformatted code in a file that is in a dirty state
2. Open a different tab in that same editor group so that the unsaved tab that has dirty code is not present.
3. Use the "Save All" button in the Explorer
4. Reopen that tab and try to undo your changes (does not undo the auto format correctly).

Note that you can undo the changes in all other cases (tab not focused, tab active), but if the tab is not open at the time, the undo history seems to get messed up.

**Comment by jrieken** [comment]
Great find!

**Comment by ramya-rao-a** [comment]
I was trying to verify this. I can see that Undo works now. But after undo the cursor is about 10 lines above change.
My steps:

1. Open a file and add an extra tab say in line 30
2. Go to another tab, then `Save all`
3. Come back to your file, you will see that the cursor is in the same line 30 where you had added the tab, and the file is formatted
4. Now `Undo`. Note that the cursor moves about 15 or more lines above
