### ISSUE TITLE
Close terminal tab in editor area with keyboard shortcut not working.

### ISSUE THREAD

**Issue by frederickschmidt1** [microsoft/vscode#128354]
Issue Type: <b>Bug</b>

Keyboard Shortcut Command "View: Close Editor" (Ctrl + F4) not effectual on Terminals in the editor area:
1) Move or create a terminal in the editor area,
2) Attempt to close tab using "View: Close Editor" keyboard shortcut.

Perhaps this is as designed to prevent unintentional closing of an active session.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.99GB free)|
|Process Argv|--file-uri file:///c%3A/Users/fs1285/VS_Code_Workspaces/M4_Development_2.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
accurev|blu|0.1.1
easy-highlight|Bra|1.2.0
custom-window-zoom|cra|1.1.4
FreeMarker|dco|0.0.9
vscode-highlight|fab|1.5.0
plantuml|jeb|2.15.1
nbpreviewer|jit|1.2.2
presentationmode|jsp|1.1.5
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
powershell|ms-|2021.6.2
vscode-sanddance|msr|3.2.0
iar-vsc|plu|1.3.0
selectline-statusbar|tom|0.0.2

</details>

**Comment by Tyriar** [comment]
This keybinding is missing from the close terminal editor command.

**Comment by meganrogge** [comment]
closed w https://github.com/microsoft/vscode/commit/66ec8a2fcc7f5b5458b968e3c8d279c9a1bad218
