### ISSUE TITLE
In desktop widget does not update to current version when you run file to update VSC

### ISSUE THREAD

**Issue by MarcoCarrillo** [microsoft/vscode#128360]
Since version 1.47 my VSC desktop widget does not update when I install the update file, and when i open the widget the screen shows me the updates of version 1.47.2.
Thanks for your attention.

**Comment by joaomoreno** [comment]
> when I install the update file

> when i open the widget

I don't undestand what you mean by the things above. Can you elaborate better? Maybe a screenshot or a screen recording?

**Comment by MarcoCarrillo** [comment]
[https://youtu.be/KxhPtxH9JJ4](url) this is the video

**Comment by joaomoreno** [comment]
You have to quit any instances of Code, before running the new version.
