### ISSUE TITLE
Built-in `application/json` notebook renderer output container height truncates output

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#128391]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.59.0-insider (user setup)  87d692b7bf1eb5a663b3e62620a6e7e436e1838c
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Generate any output which gets picked up by the built-in `application/json` renderer, e.g. here I have Python extension + Jupyter extension + Python kernel + `%lsmagic`

2. 🐛 Output container is just one line in height. Initially I assumed there was only one line of output. The output container is not resizable which makes it really hard to scroll. This is also inconsistent with the text/plain behavior:

![recording (22)](https://user-images.githubusercontent.com/30305945/125175668-7b908900-e182-11eb-8e96-8f421829d1bd.gif)

**Comment by stuartleeks** [comment]
Verified that this is now wrapping the text rather than single line output (windows)

![image](https://user-images.githubusercontent.com/1824461/130786042-73dd7828-78b9-4731-9818-f27086f2ef3b.png)
