### ISSUE TITLE
Stuck active terminal indicator

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#128301]
![recording (4)](https://user-images.githubusercontent.com/22350/125059955-b8fcf580-e060-11eb-9a64-e76d606d42f2.gif)

**Comment by meganrogge** [comment]
Unrelated to tasks - happens when switching between terminals in a group

**Comment by meganrogge** [comment]
Looks like this was only halfway fixed. 

![recording (30)](https://user-images.githubusercontent.com/29464607/125466140-6613cee9-27a7-4679-8c29-cc35c711b54e.gif)

**Comment by rzhao271** [comment]
I can still repro https://github.com/microsoft/vscode/issues/128301#issuecomment-879118927
