### ISSUE TITLE
Pin Terminal: Setting to auto create and pin per workspace type

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode#128370]
I love the new pin terminal feature! I am a PowerShell developer and would like for PowerShell to be opened and pinned when I open a PowerShell project. I can see the same being useful for opening up bash in my TypeScript projects.

Alternatively, if this can't be a feature, API access to pin terminal would be great, then I can write an extension for it.

**Comment by Tyriar** [comment]
We're discussing the solution to this problem of making terminal editors a little more sticky than files in https://github.com/microsoft/vscode/issues/124709
