### ISSUE TITLE
2 Identical Icons When Debugging Themes!

### ISSUE THREAD

**Issue by W3Dojo** [microsoft/vscode#128328]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Ubuntu 21.04

Steps to Reproduce:
1. Debug Theme

---

# Two Icons

When the debug view is open in the sidebar there is a __Stack Section-Header__. Under the _Stack Section-Header_ is an interactive list item that shows the state of the debugger (it has a badge looking item, that is named `"debugView.stateLabelBackground"` in the theme properties), inside of that are two icons that are identical, and their is no reason for two, as they are literally identical. I guess they could be called: ___"Performance Snapshot Icons"___, I doubt I guessed the correct name for the icons, but that should give a pretty good hint of reference (Below is a screenshot that shows them). I have actually noticed them before, but I never really analyzed why there are two of them. Today I investigated, and realized they are the same thing. I guess this would be considered a bug? To me it seems like anything that isn't right in a program is pretty much considered a bug. Anyway, its really annoying seeing two of the same Icon, I guess its just that I am a developer myself, and I want to fix it, but I can't, so I decided to create an issue about it. 

Below are 3 pictures, In the the 2nd & 3rd photos, I ran my cursor over the icons (one I icon per screenshot), to demonstrate that the name is the same in the pop up (functionality wise, they do the same thing as well). Though the screenshot does not show my cursor it is hovering over them.

---

<br>

<br>

---

![GitHub-Issue-2021-July-09(1)](https://user-images.githubusercontent.com/82741003/125105496-5ec95800-e093-11eb-88b7-efdb104df922.jpg)

---

<br>

<br>

---

![GitHub-Issue-2021-July-09(2)](https://user-images.githubusercontent.com/82741003/125105543-6ab51a00-e093-11eb-9a85-bd667bc7f25b.jpg)

---

<br>

<br>

---

![GitHub-Issue-2021-July-09(3)](https://user-images.githubusercontent.com/82741003/125105556-6e48a100-e093-11eb-93b0-d3a995302ed3.jpg)

**Comment by gjsjohnmurray** [comment]
I think those buttons are being contributed by one or more of your extensions. Please use the Start Extension Bisect command to find out which. Or else look at your list of active extensions, make some guesses, and disable items.

**Comment by W3Dojo** [comment]
Okay will do

**Comment by W3Dojo** [comment]
Your right, an extension is adding the extra icon, sorry about the false alarm.

**Comment by W3Dojo** [comment]
I actually knew to try loading vscode without the extensions, but I forgot. Had I followed procedure I would have been a dum dum.
