### ISSUE TITLE
Cant run/debug project after recent vscode update

### ISSUE THREAD

**Issue by slier81** [microsoft/vscode#128300]
I used to run my project using the `launch.json` file..It used to work
But now, it completely not working...I cant run nor can i debug my project
When pressing F5,  vscode will show the debug toolbar and it disappear seconds later..

Here is my `launch.json`

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "(Windows) Launch",
			"type": "cppvsdbg",
			"request": "launch",
			"program": "${workspaceFolder}/zig-out/bin/pong.exe",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"preLaunchTask": "build",
			"internalConsoleOptions": "openOnSessionStart",
		}
	]
}

**Comment by jojolatina** [comment]
I have the same problem, I can't run my program anymore. This is unacceptable. They waste my time with their stupid update. And there is another problem: when I hit F5, the debug view opens everytime even though I set the "Open Debug" setting to "openOnDebugBreak", not "openOnSessionStart"

**Comment by slysherz** [comment]
Same here, updated VSCode this morning and now I can't debug C++ programs. When I click F5, the debugging bar appears and then just disappears. No errors or messages anywhere that I could find.

It's quite easy to reproduce, just click Add Configuration..., select `C/C++: (Windows) Launch` and change the `program` into something valid. Then click F5.

I can provide more info if necessary.

**Comment by slier81** [comment]
Looks like https://github.com/microsoft/vscode-cpptools/issues/7808
