### ISSUE TITLE
[Feature Request] Rename Refactor for TypeScript Dynamic Interface Key

### ISSUE THREAD

**Issue by EricLiuCY** [microsoft/vscode#128398]
There's currently no way to rename globally references to a dynamic key in an interface. 
Let's say I have the following enum + interface setup for a simple user using dyanamic keys
```
const enum UserFields {
    id = 'id'
    name = 'name'
}

# Dynamic Key Version
interface IUser {
    [UserFields.id]: string;
    [UserFields.name]: string;
}

# Static Key Version
interface IUser {
    id: string;
    name: string;
}

# getUser returns a IUser object, and I can access interface properties
function foo () {
    const user : IUser = getUser();
    const userId: user.id;
    const userName = user.name;
}
```
Currently, if I were to press f2 on a static interface key, it would rename all the global properties. So for example, if I press f2 on 'name' in IUser and rename it to 'namesXXX', it would rename the reference in function foo from 'user.name' to 'user.namesXXX'

However, this renaming feature is not supported if I use dynamic keys in the interface.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
