### ISSUE TITLE
Terminal In Editor Does Not Persist

### ISSUE THREAD

**Issue by slaphead** [microsoft/vscode#128311]
Issue Type: <b>Bug</b>

1. Open the terminal in the editor: (cmd+shift+p), select `Terminal: Create terminal in Editor Area`, which opens the terminal in a new tab in the editor.
2. Close the project window
3. When reopening the project, the expectation is to see the terminal tab like the other editor tabs. It quickly shows the tab and then it "disappears". It seems to just close the terminal tab while the other tabs are loading.

I tried to do this several times and it never persists the terminal tab. Also, if I have a current running process in that terminal there is no warning before the project is closed. It just kills the process and closes the project. I assume there should be a warning before closing a tab that has a running process in it? If that is the case, and it is a bug, I can open a new issue for that. If not, I will create a feature request. Thanks!

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (4.10GB free)|
|Process Argv|--crash-reporter-id 81791b85-d380-40e5-a893-96ee1bc59900|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nvm|abu|0.0.1
gherkin-indent|Ara|2.0.0
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
json-tools|eri|1.0.2
prettier-vscode|esb|8.0.1
beautify|Hoo|1.5.0
jenkins-pipeline-linter-connector|jan|1.2.0
json-escaper|jos|1.1.2
solidity|Jua|0.0.124
graphql-for-vscode|kum|1.15.3
saml-extension|mca|0.0.11
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.12
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
cmake-tools|ms-|1.7.3
fix-json|oli|0.1.2
docthis|oou|0.8.2
quantum-devkit-vscode|qua|0.18.2106148911
qub-xml-vscode|qub|1.2.8
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.0
scala|sca|0.5.3
metals|sca|1.10.6
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
json2yaml|tux|0.2.0
cmake|twx|0.0.17
vscode-meteor|vuh|0.1.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
Thanks for the issue. Closing the project kills the terminal process, so it is expected that the terminal editors do not persist. 

They persist on reload of the window. 

We are working on what you mentioned this iteration. https://github.com/microsoft/vscode/issues/127193
