### ISSUE TITLE
When Setting A Breakpoint In VS Code While Debugging OSS, Electron often crashes

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128334]
I'm on Windows and this is a real paper cut.

I cannot reliably reproduce this. Tell me what you need and I use this issue to collect missing information.

I would love to gain knowledge how I can debug electron issues.

*edit*: It just happened. This is the error:
![image](https://user-images.githubusercontent.com/2931520/125112619-b691ae80-e0e7-11eb-8029-38f6d7a4f659.png)

**Comment by deepak1556** [comment]
If you can follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash dump it would be a good start. Thanks!

**Comment by deepak1556** [comment]
Thanks for the crash logs, the issue you are hitting is same as https://github.com/microsoft/vscode/issues/122225#issuecomment-827393564. I will merge this to https://github.com/microsoft/vscode/issues/122225
