### ISSUE TITLE
Markdown Show Source With Tabs Sometimes Switches To Previous File

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12837]
- VSCode Version: 1.6 Insiders
##### Steps to Reproduce
1. Open two markdown files side by side
2. Click on the left one
3. Now click on the right one.
4. Run markdown show source
##### Expected

The current document stays active since it already is the source.
##### Actual

The editor switches back to the file in the first tab.

![sep-27-2016 15-45-23](https://cloud.githubusercontent.com/assets/12821956/18894764/b031cedc-84c9-11e6-8bee-78152b0620b4.gif)

If you click on two lines in the right editor or make any edits, show source does the correct thing.

**Comment by mjbvz** [comment]
Closing as duplicate of #12837, which is the root cause of this problem and not specific to markdown

**Comment by sdwheeler** [comment]
@mjbvz You say this is a duplicate of #12837 but this is #12837. Has this been fixed in some build? I still have the problem.

Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:06:37.428Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

**Comment by mjbvz** [comment]
Sorry, should be #16298 which was just fixed. The next insiders build should have this
