### ISSUE TITLE
[emmet] http-equiv="X-UA-Compatible" in 2021

### ISSUE THREAD

**Issue by TonyZTYang** [microsoft/vscode#128374]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0 (Universal)
- OS Version: Darwin x64 20.5.0

I'm seeing the same behavior as in #80923: html:5 macro still includes `<meta http-equiv="X-UA-Compatible" content="ie=edge">`

According to the issue #80923 in 2019, it should have been fixed. Yet I'm still seeing it even after reinstallation.

**Comment by rzhao271** [comment]
That's awkward. I didn't see the earlier issue and instead fixed this one https://github.com/microsoft/vscode/issues/108119, which adds that tag back in.

**Comment by TonyZTYang** [comment]
Lol. I didn't see that issue as well. It makes sense to keep it since IE 11's EOL won't arrive for another year. I'm closing the issue now. Thanks for the support.
