### ISSUE TITLE
C++ syntax highlight failure with MACRO1(string MACRO2 string) inside a class definition

### ISSUE THREAD

**Issue by LaseriumFloyd** [microsoft/vscode#128333]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:
1. Open/create new .cpp file
2. Insert following dummy code:
```cpp
class TMyClass {
	QUERY_BEGIN("first part" MY_CONSTANT "second part");
}
```
## What happens
You can notice "second part" is not considered a string as it should be.
The definition of both macros does not affect the result.

## When it works again
If you take the line out of the class definition the syntax highlight is working again.

**Comment by LaseriumFloyd** [comment]
C++ extension is not even installed in one of my machines and the issue manifests anyway.
I don't know how do you call the basic colorization feature that VSCode apply to C++ files in a fresh new installation without extensions, the bug is there.

**Comment by gjsjohnmurray** [comment]
pinging @alexr00 - perhaps I was wrong to use the triaging command to mark it as caused by extension, since C++ syntax colorization is apparently done by a built-in extension. Sorry.

**Comment by alexr00** [comment]
@gjsjohnmurray thanks for the ping!

@LaseriumFloyd we get our grammar from jeff-hykin/cpp-textmate-grammar. I can reproduce the incorrect behavior, so I've opened https://github.com/jeff-hykin/cpp-textmate-grammar/issues/558 in the owning repo. Thanks for reporting the issue!
