### ISSUE TITLE
MarkdownString Hover images broken

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#128315]
Does this issue occur when all extensions are disabled?: N/A. I have to test with my extension.

- VS Code Version: 1.58.0
- OS Version: Windows 10

Starting with VS Code 1.58.0, `MarkdownString` `Hover` images are broken when using a `file` URI as the `src`. This is basically the same issue I had with #80352 and that code is essentially unchanged, but I assume with a different cause.

Markdown example: `[![alt text](file:///c%3A/Users/kamasamak/.vscode/extensions/extension-id/images/hover-img.png)](https://example.org)`

HTML example (from Developer Tools Inspector): `<a href="#" data-href="https://example.org" title="https://example.org"><img src="file:///c%3A/Users/kamasamak/.vscode/extensions/extension-id/images/hover-img.png" alt="alt text"></a>`

Console error:
```
Not allowed to load local resource: file:///c%3A/Users/mtbro/.vscode/extensions/extension-id/images/hover-img.png
processTicksAndRejections	@	internal/process/task_queues.js:93
Image (async)		
a	@	markdownRenderer.ts:244
render	@	markdownRenderer.ts:61
renderHoverParts	@	markdownHoverParticipant.ts:131
_renderMessages	@	modesContentHover.ts:544
_withResult	@	modesContentHover.ts:505
(anonymous)	@	modesContentHover.ts:258
_onComplete	@	hoverOperation.ts:146
_withAsyncResult	@	hoverOperation.ts:141
(anonymous)	@	hoverOperation.ts:106
processTicksAndRejections	@	internal/process/task_queues.js:93
Promise.then (async)		
then	@	async.ts:43
_triggerAsyncComputation	@	hoverOperation.ts:104
(anonymous)	@	hoverOperation.ts:69
doRun	@	async.ts:753
onTimeout	@	async.ts:747
setTimeout (async)		
schedule	@	async.ts:726
start	@	hoverOperation.ts:165
_startShowingAt	@	modesContentHover.ts:456
maybeShowAt	@	modesContentHover.ts:345
_onEditorMouseMove	@	hover.ts:173
(anonymous)	@	hover.ts:82
fire	@	event.ts:583
se.onMouseMove	@	codeEditorWidget.ts:1659
emitMouseMove	@	viewUserInputEvents.ts:58
emitMouseMove	@	viewController.ts:302
_onMouseMove	@	mouseHandler.ts:204
(anonymous)	@	mouseHandler.ts:100
Rt	@	dom.ts:314
(anonymous)	@	async.ts:656
setTimeout (async)		
setIfNotSet	@	async.ts:654
(anonymous)	@	dom.ts:327
```

Was this an unintentional regression or is there a new recommended way to do this?

**Comment by DanTup** [comment]
@bpasero is that issue something likely to be addressed in the near term? I'm trying to figure out if I should remove previews in the meantime. This seems like a regression, but that other issue isn't assigned to any milestone and doesn't look like a bug/regression so I'm not sure if it's planned to be done soon?

Thanks!

**Comment by chuck189** [comment]
Has this been fixed because am still getting broken icons but my VS, Dart and already updated
