### ISSUE TITLE
"Confirm On Exit" and "Open Recent"

### ISSUE THREAD

**Issue by 4310V343k** [microsoft/vscode#128353]
Issue Type: <b>Bug</b>

Pressing "Cancel" when `Terminal>Integrated>Confirm On Exit` is checked and trying to switch workspaces(folders) with `File>Open Recent` still puts the workspace you tried to open to the top of the list, even though you didn't open it

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.43GB free)|
|Process Argv|--folder-uri file:///c%3A/Program%20Files%20%28x86%29/Steam/steamapps/workshop/content/365450/2489144062 --crash-reporter-id 977e55b8-89e5-4642-b0b4-ffe243493d75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-zipfs|arc|2.3.0
npm-intellisense|chr|1.3.1
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
code-runner|for|0.11.5
byond-dm-language-support|gba|1.0.1
vscode-pull-request-github|Git|0.27.1
discord-vscode|icr|5.7.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.6.999662501
remote-containers|ms-|0.183.0
powershell-preview|ms-|2021.6.1
vscode-typescript-tslint-plugin|ms-|1.3.3
material-icon-theme|PKi|4.8.0
dm-langclient|pla|0.1.11
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
sharecode|Rol|0.4.1
markdown-preview-enhanced|shd|0.5.22
byond|ss1|1.1.0
auto-comment-blocks|sty|1.1.1
errorlens|use|3.3.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
gistfs|vsl|0.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by Tyriar** [comment]
Not sure this is a bug - vetoing a window close during an open adds it to the recently opened list.

**Comment by bpasero** [comment]
Needs analysis why this happens and open for help if someone is interested.

**Comment by bpasero** [comment]
The entry is added from our flow of opening a window here:

https://github.com/microsoft/vscode/blob/9aab65c6ee6fdca6a3e14fbb2efcf52861dd7175/src/vs/platform/windows/electron-main/windowsMainService.ts#L371-L371

This happens before we know whether the opening is veto'd. 

Arguably not ideal, but since the fix would probably be quite involved and the result is not really bad, closing as wontfix.
