### ISSUE TITLE
truncated paths on terminal after launching

### ISSUE THREAD

**Issue by Indiana3** [microsoft/vscode#128382]
Issue Type: <b>Performance Issue</b>

I launch my script with the run start button but on terminal lines are truncated and I see only the last 2 or 3 characters.
If I zoom the screen, I see the output as usual.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

![terminal](https://user-images.githubusercontent.com/12545890/125167083-07b0a980-e19f-11eb-98d8-04dc227e711b.jpg)

**Comment by Sam-Varghese** [comment]
This is also happening with me. I have described this issue over #128342 (comment) and https://stackoverflow.com/q/68328179/15446699

**Comment by Indiana3** [comment]
> This is also happening with me. I have described this issue over [#128342 (comment)](https://github.com/microsoft/vscode/issues/128342#issuecomment-877676547) and https://stackoverflow.com/q/68328179/15446699

Thanks a lot Sam. After uninstalling Python extension, I firstly tryed to install it again but unfortunately nothing changed. Then I replaced the latest VS Code version (1.58) with the previous one and now everything looks fine!
