### ISSUE TITLE
When multiple ghost text parts have line breaks, the first line of the ghost text gets deleted

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128302]
![image](https://user-images.githubusercontent.com/2931520/125060709-ecfe0800-e0ac-11eb-8004-a6a9476a9f2a.png)

It should look like this:
![image](https://user-images.githubusercontent.com/2931520/125060822-08691300-e0ad-11eb-8dc6-221802fef3cc.png)

Copilot currently does not trigger this behavior, as they currently don't suggest multi line text in the middle of lines, thus I guess this bug is not very critical.

**Steps to verify:**
Enable `"editor.suggest.preview": true,` and set `"editor.suggest.previewMode": "subword",`.
Then type `"quick"` in the settings editor and ensure that the cursor is at `"quick|"` (see screenshot). Notice the ghost text that previews the text buffer as if the suggestion was accepted, as in the reference screenshot.
(In the reference screenshot, `"editor.quick"` has been typed, but that does not affect the outcome.)

**Comment by chrmarti** [comment]
Verified with `"subwordDiff"` (there is no `"subword"` in 1.58):
![image](https://user-images.githubusercontent.com/9205389/125741573-e7f25423-9299-4a3b-843e-76c8f5188bcc.png)
