### ISSUE TITLE
New Terminal in Editor keyboard shortcut

### ISSUE THREAD

**Issue by atomi** [microsoft/vscode#128346]
New Terminal in Editor 
Add keyboard shortcut for 

```workbench.action.terminal.newInEditor```

**Comment by meganrogge** [comment]
You can change your terminal creation default location using` terminal.integrated.defaultLocation` and then use the default keybinding assigned to `workbench.action.terminal.new`

**Comment by Tyriar** [comment]
There is also the `workbench.action.createTerminalEditor` command which does exactly this, we aren't planning on adding a default keybinding for it though, unless there's some common keybinding often used in IDEs that we're not aware of.
