### ISSUE TITLE
Facilitate deployment of Product Icon Themes

### ISSUE THREAD

**Issue by LuanRoger** [microsoft/vscode#128378]
It is currently difficult to implement Product Icon Theme because it has to convert .svg format icons into a .woof file.
My suggestion would be to make the implementation similar to File Icon Theme, indicating the direct SVG file. 
Or in some other way that makes implementing Product Icon Theme less difficult.

> This will also help in adding new icons to an existing theme.

**Comment by aeschli** [comment]
Product icons needs to be glyphs. Only foreground, background, no colors.
I don't know how we could enforce that with SVGs.
If anyone has a suggestion, I'm all ears.

In https://github.com/microsoft/vscode-extension-samples/tree/main/product-icon-theme-sample we have a build script that creates an icons font from SVG (use `npm run updateFont`). Theres also a preview page to make sure the font looks good.
