### ISSUE TITLE
Terminal Window is Showing Nothing

### ISSUE THREAD

**Issue by DivyanshByte** [microsoft/vscode#128364]
Issue Type: <b>Bug</b>

I am Facing The issue with The Terminal Window in VS Code
When I Try To run My Program, The Terminal Window Openes and Shows Nothing not the Terminal Text nor the Output and even can't Kill The Terminal.
I am facing This Is Issue After Updating to 1.58.....
Please Solve This issue as Soon as Possible

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

https://user-images.githubusercontent.com/57246976/125153559-22b8f480-e172-11eb-9e7a-0e63243196ad.mp4

![Screenshot 2021-07-10 at 11 27 43 AM](https://user-images.githubusercontent.com/57246976/125153561-2f3d4d00-e172-11eb-8a3d-e33a3b9973af.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (1.35GB free)|
|Process Argv|--crash-reporter-id 780cb969-96d7-43d1-97e4-9726ff001f53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
tellraw-preview|act|0.2.1
auto-close-tag|for|0.5.11
gc-excelviewer|Gra|3.0.42
mc-datapack|HuJ|0.0.5
mcjson|Lev|0.4.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
debugger-for-chrome|msj|4.12.12
java|red|0.80.0
LiveServer|rit|5.6.1
shader|sle|1.1.5
datapack-language-server|SPG|3.3.14
vscode-mc-shader|Str|0.9.5
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
material-theme|zhu|3.10.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by Sam-Varghese** [comment]
This is also happening with me. I have described this issue over https://github.com/microsoft/vscode/issues/128342#issuecomment-877676547 and https://stackoverflow.com/q/68328179/15446699
