### ISSUE TITLE
Bring back global search

### ISSUE THREAD

**Issue by justinpincar** [microsoft/vscode#128393]
It appears that version 1.58.0 replaced global search with only searching in open editors.

Global search is a necessity for everyday use cases like finding the callers of a particular function.

**Comment by IllusionMH** [comment]
/question
It's still there, but looks like you activated Search only in Open Editors.
Make sure that toggle in "files to include" is not active (no background, as on screenshot below)
![image](https://user-images.githubusercontent.com/1312662/125176799-2f276680-e1df-11eb-9260-c0f613e2cdf0.png)

**Comment by justinpincar** [comment]
My mistake, thank you for the clarification!
