### ISSUE TITLE
Native Notebooks - Show Supported Languages in Language Picker

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#128338]
Had a quick chat with @misolori on the new built-in getting started flow for notebooks. 
When starting off with a new notebook the user will have the ability to either change kernel or change the language. If they decide to change the language first, a drop down list with all supported languages appears. 

![image](https://user-images.githubusercontent.com/19276747/125112490-14000e00-e09c-11eb-8e47-372ced0bb14d.png)

However, a user may not have the required kernels to use certain languages and may lead to confusion when they cannot use one they have selected. 

We were thinking it would be good to limit the languages in the list to just those that would be supported based on the kernels on a user's machine/extensions installed that provide kernels. 

We do something similar with the kernel selector today - If user selects a kernel, we only show the languages supported by the kernel. Below is  example if user selects .NET kernel. 

![image](https://user-images.githubusercontent.com/19276747/125113266-48c09500-e09d-11eb-9284-47cd6024c40d.png)

The idea is to have a "global" version of the above experience.

**Comment by roblourens** [comment]
I implemented this, but in reality I think that we almost always auto-select a kernel now. And also, the list is still pretty long since so many languages can be supported in Jupyter.
