### ISSUE TITLE
Extensions host always crashes

### ISSUE THREAD

**Issue by breadbored** [microsoft/vscode#128349]
Issue Type: <b>Bug</b>

No known information. I have the same extensions as coworkers, however on only my computer, the extensions host will crash upon opening. Any attempt to restart the extensions host is met with another crash.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (6.49GB free)|
|Process Argv|--crash-reporter-id 46f9c026-17d3-45ad-a83a-1ed39607bcfa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
json-tools|eri|1.0.2
prettier-vscode|esb|8.0.1
vscode-sshfs|Kel|1.21.0
vscode-docker|ms-|1.14.0
vscode-kubernetes-tools|ms-|1.3.3
remote-containers|ms-|0.183.0
vscode-yaml|red|0.21.0
rust|rus|0.7.8
vscode-scss-formatter|sib|2.2.2
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.10.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0702:30334633

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to pinpoint the extension that is causing this. Then report it to the author.
