### ISSUE TITLE
`NotebookEditorWidget.getEditorMemento` seems unused

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#128318]
Looks like `NotebookEditorWidget.getEditorMemento` and friends can be removed:

https://github.com/microsoft/vscode/blob/efe0678e96ab93353e11f1656ece4433c6b42e9b/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L530-L530

**Comment by rebornix** [comment]
Good catch, thanks!
