### ISSUE TITLE
terminal is not visible

### ISSUE THREAD

**Issue by healertrix** [microsoft/vscode#128384]
Issue Type: <b>Bug</b>

My integrated terminal is not showing up , I have tried all sort of hacks available only but to no use please help me asap I'm in middle of some important project😥

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.80GB free)|
|Process Argv|--crash-reporter-id a856aa30-cfcb-4ff5-8fc8-349c2c6f9a05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-browser-preview|auc|0.7.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
code-runner|for|0.11.5
terminal|for|0.0.10
javascript-essentials|Gyd|0.0.7
beautify|Hoo|1.5.0
kite|kit|0.147.0
cpptools|ms-|1.5.1
powershell|ms-|2021.6.2
vscode-typescript-next|ms-|4.4.20210709
debugger-for-chrome|msj|4.12.12
gitlink|qez|0.7.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
quokka-vscode|Wal|1.0.384
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by healertrix** [comment]
I just went there to change my terminal font size and it stopped working 
![2021-07-10](https://user-images.githubusercontent.com/75298389/125167405-e612ea80-e1bd-11eb-9728-57ff4d33f0a2.png)

**Comment by Sam-Varghese** [comment]
This is also happening with me. I have described this issue over https://github.com/microsoft/vscode/issues/128342#issuecomment-877676547 and https://stackoverflow.com/q/68328179/15446699

**Comment by healertrix** [comment]
Did anyone find any solution if yes then pls share 👍

**Comment by Sam-Varghese** [comment]
@healertrix Is this solution working for you https://github.com/microsoft/vscode/issues/128342#issuecomment-877775284
