### ISSUE TITLE
 Ability to refresh problems

### ISSUE THREAD

**Issue by asdf23** [microsoft/vscode#128424]
Most people would call it compiling. The "problems" window does not always refresh. And does not do so in a reliable manner. I would like an ability to manually refresh the problems. Perhaps we could use the terminology "compiling" and set a keystroke for it such as one of the function keys.

**Comment by sandy081** [comment]
It is the underlying extension that shall update and refresh them. Please file the issue against the extension that is responsible for generating these problems.
