### ISSUE TITLE
First opened terminal  doesn't show "name" and can't be killed without focus

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode#128435]
Does this issue occur when all extensions are disabled?: Yes/No 

Yes

- VS Code Version: 1.58.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce: (Maybe related to #128320)

1. Open/toggle terminal (with `ctrl + '`)
2. It doesn't have a "name". It can't be killed without focus.
3. Create another terminal. The 2 terminals are shown on the "terminal tabs".
4. Kill the second opened terminal. The first one still doesn't show name and can't be killed without focus.
5. Create again another terminal. Kill the first one.
6. Now the second one shows it's name AND can be killed without focus.

Here's a gif showing all these steps:

![gif2](https://user-images.githubusercontent.com/57204023/125204931-0d1cfb00-e256-11eb-81da-82e430c09397.gif)

**Comment by AmericanY** [comment]
I do have the same issue as well!

**Comment by Diogo-Rossi** [comment]
The solution seems to be going on #128264 and #128320

**Comment by Marines1775** [comment]
I like VSC but it seems like there's not enough testing before release or the quality control is somewhat lacking maybe?
