### ISSUE TITLE
Javascript debugger breaks on 1.58

### ISSUE THREAD

**Issue by Scrandre** [microsoft/vscode#128400]
Issue Type: <b>Bug</b>

After many hours of trying to understand what's going on I have to downgrade and stay on 1.57.1 because if I update to 1.58 my Node.js debugging breaks:
Smart auto-attach stops working but that's just the surface and is not the problem,
If I manually attach the debugger it works until the first pause and then the debug log stops working - it doesn't output or even allow to input anything (even "true" doesn't return anything, in the VS Code's Dev Console I see "Unknown request: evaluate" errors), auto-suggestions don't work either
For some of my projects it doesn't work from the very start

I tried to disable all extensions, it did not change anything,

I've tried reinstalling node from NVM (that I use) to the standalone installer, it didn't change anything, the only thing that helped consistently is downgrading to 1.57.1, and upgrading to 1.58 breaks it as consistently

The Node.js version I use is 12.18.3,

Another thing I've noticed that doesn't work on both 1.57.1 and 1.58 is the process restart button, 1.57.1 doesn't react to it besides clearing the debug log, and 1.58 debug log breaks similar to the aforementioned pausing

Turning off the preview debugger didn't change anything on both versions

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.79GB free)|
|Process Argv|--crash-reporter-id 1c90d51e-3e96-4d9d-85be-0615af61014e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by connor4312** [comment]
First off I suggest updating your Node version. 12.22.3 is the latest 12.x, and there were some previous versions in the 12.x which had random freeze issues.

If that doesn't fix the issue, please try collecting a trace log using these instructions:

/jsDebugLogs

**Comment by baybal** [comment]
https://github.com/microsoft/vscode/issues/126704

**Comment by baybal** [comment]
1.58, and node 16.5 REPL broken on debugging over SSH

**Comment by baybal** [comment]
1.57.1 still working

Can we have a list of things which changed regarding debugging in between 1.57.1 and 1.68 ?

**Comment by baybal** [comment]
How it looks on 1.58 for me:

1. Launch a debugging session over SSH
2. Debugger attaches
3. Console.log output is visible
4. But when I try to enter anything into REPL console, nothing happens
5. When I stop the debugging session, there is `Cancelled` written into the REPL console the number of times I tried to enter something into it

**Comment by baybal** [comment]
REPL console suggestion are also not displayed. Ctrl+space shows `Loading` popup, but nothing is shown.

**Comment by baybal** [comment]
![image](https://user-images.githubusercontent.com/3344988/126157374-f47c7beb-301a-4db4-a1d2-5de2f12eb44e.png)

**Comment by baybal** [comment]
![image](https://user-images.githubusercontent.com/3344988/126157419-2f2cec25-732e-445e-932b-39db284acf5f.png)

**Comment by baybal** [comment]
> /jsDebugLogs

/jsDebugLogs

![image](https://user-images.githubusercontent.com/3344988/126158294-72db7ee1-f384-4428-b757-2de46480164e.png)

**Comment by baybal** [comment]
@connor4312 I uploaded trace to https://microsoft.github.io/vscode-pwa-analyzer/index.html vscode-debugadapter-edb3aba5.json.gz

**Comment by baybal** [comment]
[vscode-debugadapter-edb3aba5.json.gz](https://github.com/microsoft/vscode/files/6840698/vscode-debugadapter-edb3aba5.json.gz)

**Comment by baybal** [comment]
![image](https://user-images.githubusercontent.com/3344988/126159016-eb783f58-9cb1-4dd1-8472-95986355b2b0.png)

**Comment by connor4312** [comment]
@isidorn it looks like in Baybal's case, the evaluate requests are only sent to the root debug session which does not do anything. Was there a change made that caused these to no longer be sent to the child?

**Comment by isidorn** [comment]
@connor4312 I am not aware of a change that would directly cause this. Though I was on vacation so I might have forgot.
Are there some repro steps?

**Comment by connor4312** [comment]
Sure:

1. Have any JavaScript program that runs for a while. Don't hit any breakpoints
2. Enter `2 + 2` in the console. There's no output (this is going to the parent session)
3. Click on the session in the Call Stack view or hit a breakpoint to focus it
4. Enter `2 + 2` again. Now you get back 4 since it goes to the right session

**Comment by isidorn** [comment]
Thanks for steps, assigning to July so I try to look into this issue this week.

**Comment by isidorn** [comment]
I tried to repro this and could not. Here are my steps (following yours).
This javascript file, no breakpoints:

```javascript
setInterval(() => {
    console.log('how is it going')
}, 1000);
```
Start debugging
Click in console, `2 + 2 =` gets evaluated to `4`

@connor4312 what are you doing differently?

**Comment by isidorn** [comment]
Verification steps:

```
setInterval(() => {
    console.log('how is it going')
}, 1000);
```
Put a breakpoint on second line, start debugging hit a breakpoint.
Remove a breakpoint, hit contine
Evaluate 2 + 2 in the debug console, make sure you get the result
