### ISSUE TITLE
Unable to build VSC inside devcontainer (wrong Node version)

### ISSUE THREAD

**Issue by shomeier** [microsoft/vscode#128408]
- VS Code Version: 1.58.0 (commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6)
- OS Version: 11.4

Steps to Reproduce:

1. Select command **Remote-Containers: Clone Repository in Container Volume....**
2. Enter git url: https://github.com/microsoft/vscode
3. In local VS Code client connected to the devcontainer enter **yarn install**
Result:
```bash
node ➜ /workspaces/vscode (main) $ yarn install
yarn install v1.22.5
$ node build/npm/preinstall.js
*** Please use node.js versions >=14 and <=17.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I guess the devcontainer image is not yet updated to Node 14.

**Comment by chrmarti** [comment]
@Chuxel After pulling `mcr.microsoft.com/vscode/devcontainers/repos/microsoft/vscode:branch-main` I still see Node.js 12 as the default. It looks like https://github.com/microsoft/vscode-dev-containers/commit/a6fa43ad961ab28aeddcfc6bb3ca8db2dd79c28d should have taken care of this, but that change somehow hasn't made it into the image in the registry yet.

**Comment by Chuxel** [comment]
@chrmarti Possibly a timing issue - This went with the release, so I think the release updated not the `dev` tag, and I didn't bump the version number. I'll re-trigger the `dev` workflow and assuming that works bump the image version number.

**Comment by Chuxel** [comment]
@chrmarti Turned out that I had a value in the definition manifest that was still set to 12. Things should now be up to date.

```bash
$ docker run -it --rm --init  --pull always mcr.microsoft.com/vscode/devcontainers/repos/microsoft/vscode:branch-main node --version
branch-main: Pulling from vscode/devcontainers/repos/microsoft/vscode
Digest: sha256:266550b47e1864b30f8d73bde56bfedeaf1ecd04315b055a58e0dd1283297ac8
Status: Image is up to date for mcr.microsoft.com/vscode/devcontainers/repos/microsoft/vscode:branch-main
v14.17.3
```

**Comment by shomeier** [comment]
@Chuxel Works like a charm after pulling the new image, thx.
