### ISSUE TITLE
Disable inline breakpoints 

### ISSUE THREAD

**Issue by Megabyteceer** [microsoft/vscode#128480]
Breakpoints inside lines are very annoying sometime. 
![image](https://user-images.githubusercontent.com/5096541/125271048-fdafb780-e312-11eb-8484-0f5a6f974c6a.png)

As I know, debug.showInlineBreakpointCandidates is not related to it, and it is extension decides where to place breakpoint to.
Will be great to add settings option to not place breakpoints inside line. Thank you.

**Comment by Megabyteceer** [comment]
I found an simular old issue in vscode and there was suggestion it on extension side. Maybe im wrong. Any way thank you.

**Comment by isidorn** [comment]
Please try this setting 	
`"debug.showInlineBreakpointCandidates": false`

If breakpoints still appear for your use case we can fine tune this setting to be a string..

**Comment by Megabyteceer** [comment]
I tried "debug.showInlineBreakpointCandidates": false for global and for workspace level. It is changed nothing. Breakpoints still appears in random place of the line.

**Comment by isidorn** [comment]
Yeah I guess that setting only changes that we do not show the gray dots (candidates). 
So your issue is a fair feature request to introduce a setting for.
