### ISSUE TITLE
Status bar error message is cut off; no way to view status bar error message after it disappears

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/vscode#128449]
Issue Type: <b>Bug</b>

I'm not sure - Prettier is refusing to format a file (since it's my default formatter) and it's putting it's error message into the status bar.  Even though I've hidden almost every other thing on my status bar the message is still getting clipped and I can't actually read the error message.

<Once this is filed I'll put in an image to show what I mean>

Also, the message disappears rather quickly (normally this is fine, but I need it to stick around a while longer)

Also, there doesn't appear to be a way to view older/disappeared status bar messages.

It might be nice to do something like 'copy to clipboard when message is double-clicked' or something.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 5bf0e0e5-4e79-4dfe-99e4-8957ae30b275|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
vscode-pull-request-github|Git|0.28.0
vscode-power-mode|hoo|2.2.0
git-graph|mhu|1.30.0
compare-folders|mos|0.22.2
vsliveshare|ms-|1.0.4531
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
swapdiff|sha|0.1.0
open-in-browser|tec|2.0.0
org-mode|too|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by MikeTheGreat** [comment]
Here's the image:

![image](https://user-images.githubusercontent.com/551619/125218118-19fe1680-e277-11eb-85b5-4a2c8beeba41.png)

vscodebot is asking if #84258 is a duplicate.  I think that issue accidentally caused this one; it would be nice if the clipping routine used as much of the status bar as possible.

**Comment by isidorn** [comment]
Seems like the status bar item has a width limit, @bpasero did we introduce this on purpose? I think it makes sense, just the rendering could be done better.

**Comment by bpasero** [comment]
Agree, a "..." would be nice here.

Assigning to @sandy081 from https://github.com/microsoft/vscode/pull/87164

**Comment by MikeTheGreat** [comment]
The ... would be nice

Also - **is there a way to get the full message?** Especially after the message has disappeared from the status bar?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/84258
