### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chirag2123** [microsoft/vscode#128441]
Whenever I try to run the program in the terminal it shows an error that "The term is not recognized as the name of a cmdlet, function, script file, or operable Program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ new
+ ~~~
    + CategoryInfo          : ObjectNotFound: (new:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
Please provide me a proper guide to avoid this error.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
