### ISSUE TITLE
Remove default keybinding of ctrl+w to "Kill the Active Terminal in Editor Area"

### ISSUE THREAD

**Issue by miversen33** [microsoft/vscode#128422]
For those who frequently use a terminal on a linux system, the keybinding "ctrl+w" is used to remove characters to the previous whitespace. This is a very common shortcut to use while working from within a terminal and having the default action of of be "Kill the Active Terminal in Editor Area" is detrimental to ones workflow. Given that "ctrl+w" is also set as the "View: Close Editor", I can understand why it was chosen to have this default set for the terminal, but it doesn't make alot of sense, given the keybinding of "ctrl+w" does _not_ close out the terminal when working within a typical terminal application.

Suggestion:
Remove or remap the default keybinding

**Comment by Tyriar** [comment]
We discussed this and we chose that when it's in the editor it should act more like an editor and respect ctrl+w to close it. You would need to unbind the keybinding there which we allowed by adding a separate command specifically to close the terminal

```json
{
  "key": "ctrl+w",
  "command": "-workbench.action.terminal.killEditor",
  "when": "terminalFocus && terminalProcessSupported && resourceScheme == 'vscode-terminal'"
}
```

Unfortunately it's one of those problems that doesn't really have a clear right or wrong way when you have a terminal embedded into an editor.
