### ISSUE TITLE
Code error on String keyword

### ISSUE THREAD

**Issue by Ttiki** [microsoft/vscode#128469]
Issue Type: <b>Bug</b>

I'm working with LUA and I use the keywork end inside string as I'm working with keyboard input. However, VSCode gives me an error because it doesn't understand  "end" and believes it is the actual end keyword.

function GetKeyString(int)
        if int == nil then return "<INVAILD>" end
	if int == Key.A then return "a" end
        if int == Key.B then return "b" end
	if int == Key.C then return "c" end
        [...]
        if int == Key.Period then return "." end 
	if int == Key.End then return "end" end --Gives me an error because of this line

	return "<INVAILD>"
end --The error is listed here as it doesn't understand the end above is a string and not the keyword.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (0.96GB free)|
|Process Argv|--crash-reporter-id 16535a59-ebd0-4d14-88a1-e61b2a5d5081|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Leadwerks|agg|0.6.9
vscode-intelephense-client|bme|1.7.1
vscode-pull-request-github|Git|0.28.0
vscode-github|Kni|0.30.6
cpptools|ms-|1.5.1
hexeditor|ms-|1.7.1
vscode-html-scss|P-d|0.0.42
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
vscode-lua|tri|0.12.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
/causedByEtension
Support for LUA files and errors in them provided by extension. Please file this issue in corresponding extension repo.
