### ISSUE TITLE
Don't Trim Spaces or Line Breaks on Current Line

### ISSUE THREAD

**Issue by SethFalco** [microsoft/vscode#128464]
VS Code has 2 settings that trim whitespace:
* `files.trimFinalNewlines`
* `files.trimTrailingWhitespace`

One pain point is that they modify the _current_ line I'm on.
I have a tendency to spam `CTRL` + `S` a lot, and it can be quite annoying to press the space/enter, then save either on habit or because I performed `ALT` + `TAB`, and lose the whitespace I put in.

I think there should be an option to trim spaces/line breaks, excluding the current line.

In the case of `files.trimTrailingWhitespace`, this would mean not to remove spaces on the current line.
In the case of `files.trimFinalNewlines`, this would mean to only remove empty lines from under the users text cursor, rather than the last line in the file.

**Comment by alexdima** [comment]
cc @bpasero

**Comment by bpasero** [comment]
cc @jrieken
