### ISSUE TITLE
[json] no completions for enum values in alternatives

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12848]
Testing #12600.
- VSCode Version: 1.6.0 insiders
- OS Version: MacOs

Steps to Reproduce:

1) Create the following `launch.json` file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node"
        }
    ]
}
```

2) in the line 6 place caret in anywhere between the quotes in `"node"`.
3) Ctrl+Space
-> The only proposal you see is `node`. There should also be `node2`.

4) delete the word `node` in line 6
5) Ctrl+Space
-> You get all valid proposal for launch config types.

**Comment by isidorn** [comment]
This is coming from the json schema suggest provider -> forwarding to @aeschli

**Comment by aeschli** [comment]
That's a subtlety of the JSON language server implementation. In the case of alternatives for the same object (in this case a configuration for each debug adapter) code assist looks which alternative matches. As `type` matches 100%, it only considers the schema for that cnfiguration and ignores all others. Thats useful for all properties except for the 'type' itself...
But it's tricky and I'd rather live with the bug for now
