### ISSUE TITLE
File explorer should persist highlight the selected file/files when showing right-click menu

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#128423]
otherwise, this will make users to confuse that which is the file/files operating

![right-click](https://user-images.githubusercontent.com/1876302/125196071-f5ac3500-e28a-11eb-9ca5-731e3281da7c.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/123771
fyi @joaomoreno
