### ISSUE TITLE
Editor indentation reverts when window focus is lost

### ISSUE THREAD

**Issue by DanAtkinson** [microsoft/vscode#128475]
Issue Type: <b>Bug</b>

I have XML and XSD documents that use tab indentation but Code keeps switching it to spaces.

When I open the documents however, the indentation always sets to `Spaces: 4`, even though I have a global rule in my `.editorconfig` file which explictly uses tab indentation for all document types (see below).

If I select `Detect indentation from content` the option then it correctly sets it to tabs. But if I then alt-tab to another window and go back to Code, the indentation reverts to `Spaces: 4`.

I've also tried manually setting the indentation to tabs, but the same thing happens.

`.editorconfig` file contents:
```
# This is the main editor config.
root = true

# All files should use CRLF, tabs and UTF-8.
[*]
indent_style = tab
indent_size = 4
tab_width = 4
end_of_line = crlf
charset = utf-8
max_line_length = off
insert_final_newline = true
trim_trailing_whitespace = true
```

Any guidance you can provide would be greatly appreciated.

Thanks in advance,
Dan Atkinson

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (6.84GB free)|
|Process Argv|--crash-reporter-id 13f7d351-0803-4f7f-ae21-9501daf3edbf|
|Screen Reader|no|
|VM|0%|
</details>
<details>
<summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-nvm|abu|0.0.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.1.1
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
file-icons|fil|1.0.29
url-encode|fle|1.1.0
beautify|Hoo|1.5.0
fontawesome-autocomplete|Jan|1.1.2
tabsanity|jed|0.0.11
ng-bootstrap-snippets|ktr|1.0.0
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
ecdc|mit|1.4.0
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-en-GB|MS-|1.54.1
notepadplusplus-keybindings|ms-|1.0.7
indent-rainbow|ode|7.5.0
bootstrap4-vscode|the|6.1.0
sort-lines|Tyr|1.9.0
json|Zai|2.0.2

</details>

**Comment by DanAtkinson** [comment]
I've checked and #115607 might be related, although it was marked as stale and closed - got to get those numbers down somehow, eh! 😊

**Comment by kieferrm** [comment]
I guess what happens is that the editor config extension fights with the built-in behavior of "detect indentation from content".  Pls see if the built-in behavior is correct when you disable all extensions. You can also convert manually:

![image](https://user-images.githubusercontent.com/4674940/125646401-1f928209-69e3-48b8-ab06-de9250049394.png)

**Comment by DanAtkinson** [comment]
Hi @kieferrm, you're absolutely right. Disabling the editorconfig extension resolves the issue.

I've now opened [#317](https://github.com/editorconfig/editorconfig-vscode/issues/317) on editorconfig-vscode for this.

Thanks!
