### ISSUE TITLE
docker stats

### ISSUE THREAD

**Issue by robross0606** [microsoft/vscode#128478]
Issue Type: <b>Feature Request</b>

Would be amazing if the extension could show `docker stats` data for containers.  A table of stat data would be good.  Graphs of resource utilization would be amazing.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by kieferrm** [comment]
Pls file the issue against the extension you refer to.

**Comment by robross0606** [comment]
@kieferrm, VSCode itself posted this issue when I clicked the "Report Issue" link:
![image](https://user-images.githubusercontent.com/2965467/125648341-09a3e7d9-d06c-4ff5-800a-ab05a16659b5.png)
Clearly _another_ issue that I'll have to make sure I file against the extension.

**Comment by robross0606** [comment]
Reposted as microsoft/vscode-docker#3063
