### ISSUE TITLE
市场返回 "ECONNREFUSED"。请检查 "http.proxy" 设置。

### ISSUE THREAD

**Issue by CNMan** [Microsoft/vscode#12840]
- VSCode Version:1.5.3 stable
- OS Version:windows server 2016

Steps to Reproduce:
1. 运行VSCode
2. 打开“查看”--“扩展”菜单就出现错误

![2016-09-28_070036](https://cloud.githubusercontent.com/assets/8692234/18895153/efb730e4-8549-11e6-8fe6-7cb1da62cf38.png)

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by CNMan** [comment]
i have a local socks5 and http proxy.
```
    "http.proxy": "http://127.0.0.1:8123",
    "https.proxy": "http://127.0.0.1:8123",
    "http.proxyStrictSSL": false,```

have same issue after commented proxy settings
![2016-09-28_180216](https://cloud.githubusercontent.com/assets/8692234/18909444/3923a198-85a6-11e6-9345-52c43a2f4b73.png)

**Comment by CNMan** [comment]
`--extensionHomePath="E:\Backup\VSCODE\extensions"`
delete this argument,works fine.
https://github.com/Microsoft/vscode/issues/8990

**Comment by joaomoreno** [comment]
To confirm: you only get the error when you use the `--extensionHomePath` argument?

**Comment by CNMan** [comment]
yes

**Comment by xymopen** [comment]
I also encounter this bug. I edit `/bin/code.cmd` and add `set VSCODE_EXTENSION_PATH=%~dp0..\extensions` and ` --extensionHomePath="%VSCODE_EXTENSION_PATH%"` argument. I am not behind a proxy.

**Comment by xymopen** [comment]
The console look like this.
![Screenshot of console](https://cloud.githubusercontent.com/assets/8053733/19816399/ad261626-9d79-11e6-950a-f675c8506f3f.png)
And if I create `%USERPROFILE%/.vscode/extensions` there will be no error, and newly installed extension goes there instead of `%VSCODE_EXTENSION_PATH%`.

**Comment by xymopen** [comment]
After upgrade to 1.6 the issus has been fixed. Thanks.

**Comment by joaomoreno** [comment]
@CNMan Is it fixed for you in 1.6.0?

**Comment by CNMan** [comment]
@joaomoreno i upgrade to 1.6.1. this issue has been fixed. thanks.

**Comment by joaomoreno** [comment]
Thanks!
