### ISSUE TITLE
fade working code when specifying a type 

### ISSUE THREAD

**Issue by dmitriy337** [microsoft/vscode#128440]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.0
- OS Version: Windows 10 pro

Steps to Reproduce:

1. specify the type of Responce 

![image](https://user-images.githubusercontent.com/47759698/125209137-76752c00-e29f-11eb-8f22-b248b3cb998f.png)
![image](https://user-images.githubusercontent.com/47759698/125209139-7d9c3a00-e29f-11eb-983c-6660862ac917.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled (even Python)?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Does type of `response.xpath` allows iteration?
Do you see any hints on dimmed code?

It looks like code is marked unreachable/unused by Python extension

**Comment by mjbvz** [comment]
I believe all python diagnostics (including for unused/unreachable code) come from the python extension 

/extPython

**Comment by dmitriy337** [comment]
All the problems were in Pylance, after disabling this extension code ceased to fade, but work without add-ons is not comfortable
