### ISSUE TITLE
Right Click issue when sidebar is at right side

### ISSUE THREAD

**Issue by its-Kumar** [microsoft/vscode#128455]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```
- OS Version:
```
Operating System: Ubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-59-generic
OS Type: 64-bit
Processors: 4 × AMD A6-7310 APU with AMD Radeon R4 Graphics
Memory: 6.8 GiB of RAM

```

Steps to Reproduce:

1. Move sidebar to the right
2. Now in the Explorer when right click on any file, the context box did not appear, and it automatically clicks on any option.

**Comment by IllusionMH** [comment]
/duplicate
There are two issues tracking problems like described - #113175 and #114391

**Comment by its-Kumar** [comment]
> /duplicate
> There are two issues tracking problems like described - #113175 and #114391

I searched, but did not find, so I created this
