### ISSUE TITLE
Emulator not showing

### ISSUE THREAD

**Issue by Musharaf13** [microsoft/vscode#128482]
Issue Type: <b>Bug</b>

Flutter doctor says 2 devices are available but no emulator option is available in bottom bar

![image](https://user-images.githubusercontent.com/48816448/125313231-7b44e900-e34e-11eb-90cb-1974e5a9f39c.png)

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (4.72GB free)|
|Process Argv|--crash-reporter-id 34309fd5-0759-413d-97e3-b13d68e1a525|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
vscode-pull-request-github|Git|0.28.0
go|gol|0.26.0
remote-wsl|ms-|0.58.2
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Make sure you didn't hide status bar item first.
If not - report to corresponding extension repo
