### ISSUE TITLE
PHP typing else <enter> adds garbage code

### ISSUE THREAD

**Issue by Maelstorm1973** [microsoft/vscode#128410]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

When inputting PHP code for a if/else statement, when type 'else' and hit enter, VSC inserts garbage code and screws the formatting up which I have to fix.  It looks like this:

	if (...)
	{
	}
	else {
		# code...
	}

I want it to look like this:

	if (...)
	{
	}
	else
	{
		# code...
	}

Or even better would be for it to not insert anything at all.  I have gone through the settings, disabled all extensions, and it still does it.  So at this point, I have to conclude that it is a bug of some sort.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.97GB (9.40GB free)|
|Process Argv|--crash-reporter-id e2cc8b2a-a6c5-4dac-914d-da5d8c64fa97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-eslint|dba|2.1.23
vscode-great-icons|emm|2.1.79
php-debug|fel|1.16.1
php-intellisense|fel|2.3.14
sqltools|mtx|0.23.0
vim|vsc|1.21.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by roblourens** [comment]
I don't follow. Are you triggering a snippet? Or some auto format?

**Comment by Maelstorm1973** [comment]
I figured it out.  It was a snippet.  A feature that I was not aware of.

Ok to close.
