### ISSUE TITLE
Behavior change on peek tree view with Vim's navigation keys in vscode 1.58

### ISSUE THREAD

**Issue by stevenguh** [microsoft/vscode#128452]
Does this issue occur when all extensions are disabled?: No? It is related to the keybindings contributed by an extension.

- VS Code Version: 1.58
- OS Version: macOS 11.4

Steps to Reproduce:

1. Upgrade to 1.58
2. Install [VSCodeVim extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
3. Use Go to Reference (Shift + F12)
4. Use Vim navigation key such a <kbd>j</kbd> or <kbd>k</kbd>

EXPECTED: It focuses an tree view element up or down using the [contributed keybindings from Vim](https://github.com/VSCodeVim/Vim/blob/v1.21.5/package.json#L148-L172)
ACTUAL: It goes into highlighting mode of keyboard navigation
<img width="818" alt="image" src="https://user-images.githubusercontent.com/3455662/125228787-4707f480-e28a-11eb-927e-1c658d6f477b.png">

In order to use the vim navigation keys, setting `workbench.list.automaticKeyboardNavigation` to `false` can disable that behavior and revert back to a similar behavior pre 1.58.

My question is if this is an expected behavior or it is a regression?

**Comment by joaomoreno** [comment]
Strange. I can reproduce in a build, but not out of OSS.

**Comment by joaomoreno** [comment]
Hm. I can't reproduce on Linux. This is confusing.

**Comment by joaomoreno** [comment]
And now I can't repro it any more anywhere. 😕

**Comment by joaomoreno** [comment]
@stevenguh Can you reproduce this 100% of the time?

**Comment by joaomoreno** [comment]
That was hard to find. The repro trick is to reload the workbench without any rendered trees, though lists are fine.

Repro steps:

1. Open a TS file where you'll run Go to Reference
2. Open the Extensions viewlet, which uses a list instead of a tree
3. Reload
4. `Go to Reference` on a symbol
5. Press <kbd>J</kbd>

🐛 It should focus the next list element, but it enters keyboard navigation mode instead.

**Comment by stevenguh** [comment]
Thank you for the quick fix.

> Can you reproduce this 100% of the time? Just works for me after reloading the window in which I could reproduce the issue.

Just in case, I just realized that this is not 100% repo after trying on my multiple machines. It is consistent repo if I use a macOS ssh remote into a linux machine on a Java project.

**Comment by joaomoreno** [comment]
No worries. With my steps above you should be able to repro 100% of the time. If so, thanks upfront for letting us know if it gets fixed with tomorrow's Insiders.
