### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by anuj304edu** [microsoft/vscode#128421]
Issue Type: <b>Performance Issue</b>

suddenly, preview on chrome not showing up. instead its address showing "http://localhost:8080/". help me out

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.70GB free)|
|Process Argv|--crash-reporter-id 2c92bd21-7d82-4715-96bf-5ab51f5aab2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   117	  1376	code main
    0	    12	  1916	   crashpad-handler
    2	   196	  2196	   gpu-process
    0	    24	  4216	   utility
   18	    63	 12432	   shared-process
    0	    28	  9152	     ptyHost
    0	    45	  3888	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 11444	       console-window-host (Windows internal process)
    0	    74	 10848	     "C:\Users\91931\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\91931\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-chrome "{\"common.vscodemachineid\":\"053cb1577281a4e97b74f419274340b5fcb0f40791eef7dc7dc2c6f869e3d6bb\",\"common.vscodesessionid\":\"bbb81883-082c-4a16-a48f-66f9537246ef1626002128593\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    2	    80	 13220	   window (Issue Reporter)
    0	   169	 15592	   window ([Extension Development Host] - .vscode - Visual Studio Code)
    0	    24	   456	     searchService
    0	    70	  3020	     extensionHost
    0	    25	  8456	       "C:\Users\91931\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\91931\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3020
    0	    43	 12108	       "C:\Users\91931\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\91931\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3020
    0	    13	 17068	     watcherService 
    0	     5	 13936	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window ([Extension Development Host] - .vscode - Visual Studio Code)
|    Folder (.vscode): 9957 files
|      File types: pyi(7246) py(658) js(112) toml(76) svg(64) json(63) txt(61)
|                  md(30) ts(22) typed(16)
|      Conf files: package.json(11) settings.json(3) launch.json(2)
|                  tslint.json(2) tsconfig.json(2) tasks.json(1)
|      Launch Configs: pwa-chrome(2) pwa-node;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
htmlplay|bia|0.0.5
vscode-html-css|ecm|1.10.2
live-html-previewer|hdg|0.3.0
code-beautifier|mic|2.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
vscode-html-scss|P-d|0.0.42
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
vshan820:30294714
vstes263cf:30335440
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
vscextlangct:30333562
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
If the feature that is no longer working was something you added by installing an extension then you need to report the issue to the extension author.
