### ISSUE TITLE
Replace 'outDir' with 'outFiles' in the error message for missing setting in Launch config

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#12846]
Testing #12254

Steps to Reproduce:

1. In a node app with typescript files, configure the generated js files to be in a folder named anything but "out" 
2. Set up launch config, but do not specify `outDir`

You see the error message:

> Cannot launch program '.....'; setting the 'outDir' attribute might help

Now that we are deprecating outDir in favor of outFiles, the message should also reflect the same

**Comment by isidorn** [comment]
Nothing urgent, this is a a message coming from the node debug adatper -> assigning to @weinand
