### ISSUE TITLE
Completion list showing bogus completions

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12849]
Testing https://github.com/Microsoft/vscode/issues/12598

`[Symbol.hasInstance]` should not appear in the list.
![image](https://cloud.githubusercontent.com/assets/762848/18896721/f98f7c82-84d8-11e6-843a-772ae6583483.png)

**Comment by waderyan** [comment]
Repo'd. 

![image](https://cloud.githubusercontent.com/assets/2449568/18931343/a2054dae-8580-11e6-986e-c47ce8804fc9.png)

Moving to TS.

**Comment by waderyan** [comment]
https://github.com/Microsoft/TypeScript/issues/11217
