### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by anuj304edu** [microsoft/vscode#128427]
Issue Type: <b>Feature Request</b>

how can i reset vsc to its earliest form.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/setup-overview#_how-can-i-do-a-clean-uninstall-of-vs-code

**Comment by felipecrs** [comment]
@anuj304edu you may be interested in https://github.com/microsoft/vscode/issues/130510
