### ISSUE TITLE
Use of the keybinding "Toggle Menu Bar" unexpectedly changes user's preferences

### ISSUE THREAD

**Issue by wardw** [microsoft/vscode#128430]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Linux fedora 5.12.14-300.fc34.x86_64

**Summary**

Any activation of the keybinding `workbench.action.toggleMenuBar` to show/hide the menu bar also permanently changes your existing `window.menuBarVisibility` preference to `toggle`.   

**Expected behaviour**

Using the keybinding `workbench.action.toggleMenuBar` unhides the menu and makes it visible.  A second press of the same keybinding hides the menu bar and returns you to your previous state.  That is, I would expect two key presses of `toggleMenuBar` to toggle the menu's visibility on/off and without any further side effects to the user's preferences.

**Current behaviour**

As above, but that two key presses of `toggleMenuBar` also modify the user's `window.menuBarVisibility` preference, setting it to `toggle`.  

**Why I think this is important** 

In the case you have the setting `window.menuBarVisibility` set to `toggle`, you can use `alt` to show/hide the menu bar.  In fact, with this setting a separate keybinding that performs similar behaviour is less useful (IMHO).  Comparatively, it is precisely when you have the setting `window.menuBarVisibility` set to `hidden` that an explicit keybinding to show/hide the menu is most useful:  This covers the case when you want the menu hidden by default, but occasionally do want access to the menu bar and so it's perfect that VS Code provides a keybinding toggle to do just that.  The problem is that using this keybinding also resets your preference from `hidden` back to `toggle`, which is exactly the thing you didn't want - a preference for `hidden` is precisely why I'm using the separate keybinding in the first place.

**Steps to reproduce**

1. Set the preference `"window.menuBarVisibility": "hidden"`.  _Aside: observe that in this state tapping `alt` has no effect._ 
2. Bind the `workbench.action.toggleMenuBar` to some keybinding.
3. Activate that keybinding to show the menu, and again to hide the menu.
4. Observe that your preference has now been changed to `"window.menuBarVisibility": "toggle"`.  _Aside: observe that tapping `alt` now makes the menu steals focus._

**Possible solution** 

I've observed that activating the keybinding `toggleMenuBar` removes the line `"window.menuBarVisibility": ".."` from your settings entirely.  A second press of the keybinding simply re-adds the preference but with `"window.menuBarVisibility": "toggle"`, that is, always with `toggle` and without regard to your existing setting.  My hope is that it would be possible to tweak this behaviour to re-add the line but do so while remembering and adding back your existing preference.  My hunch is that this would have no further impact on broader behaviour and in fact may be what a user might already expect.

**Comment by sbatten** [comment]
Hi @wardw, thank you for the write-up. However, all of the behaviour you have described is as-designed. The `hidden` value for visibility is 100% intended to hide them menubar and not intended to be brought back via keybinding.

`toggle` is intended to be hidden by default while allowing native keystrokes to trigger the menubar entries. It seems this may be the confusion that the command which you can modify a keybinding is called `toggleMenuBar`. On Linux, this should switch between an always visible and a toggleable menubar and the setting would indeed be modified.

The actual showing and focusing of the menubar is controlled upstream and not re-bindable, but `Alt` is the keybinding for that when using any visibility setting besides `hidden`. I hope this clarifies things for you.

**Comment by wardw** [comment]
Yes ok.  I did wonder, and in fact why I thought to put a case forward.

Perhaps my point was that - intentional or not - is there not scope to have `workbench.action.toggleMenuBar` act merely as a (toggling) _action_, without further side effects?  That is, that performing this action twice would leave you in the same state as you started with?

My thought was that there might be scope to achieve this, while both being able to maintain all existing behavior but also be particularly beneficial to the use case as outlined above.  It may also align closer with what user's might expect from an action that performs toggle-like behaviour (?) 

But no problem, there may be reasons for the current behavior that I've not considered.  Just bear in mind that if you do have the menubar `hidden`, I don't believe that there's a simple way of being able to have it show/hide for those odd occasions that it can be useful.  A keybinding to toggle the menu might be particularly helpful here?

(My point being that `toggle` is insufficient here, since then `Alt` will _always_ steal focus (meh) - and as you say this is upstream behavior and not re-bindable - in fact precisely why you might choose to keep the menu `hidden` and like a separate keybinding)
