### ISSUE TITLE
Installed extensions should be sorted by display name, not publisher

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12842]
At first glance it looks like the installed extensions are ordered randomly, but they are sorted by publisher id, with capital letters ordered first.

**Comment by ramya-rao-a** [comment]
weird, I verified this in insiders but the fix went in AFTER the insiders build was run ....

**Comment by joaomoreno** [comment]
It was already fixed before, I just added a few more lines for other code paths.

**Comment by ramya-rao-a** [comment]
Aha! Makes sense
