### ISSUE TITLE
Dissassembly view flashes briefly on every Step Over

### ISSUE THREAD

**Issue by ximon18** [microsoft/vscode#128415]
Issue Type: <b>Bug</b>

I think this only started since I upgraded from VS Code 1.57.0 to 1.58.0.

When stepping through a Rust debug session when I use Step Over by pressing F10 the dissassembly view appears and disappears on every step. This was not happening before.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2660)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.34GB (3.06GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
hex-array-formatter|Alo|0.0.2
asciidoctor-vscode|asc|2.8.9
troff|ban|1.0.22
search-crates-io|bel|1.2.1
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
xml|Dot|2.5.1
gitlens|eam|11.5.1
LogFileHighlighter|emi|2.11.0
filter-line|eve|2.0.1
vscode-todo-plus|fab|4.18.3
remotehub|Git|0.11.0
vscode-pull-request-github|Git|0.28.0
todo-tree|Gru|0.0.213
terraform|has|2.13.0
vscode-test-explorer|hbe|2.20.4
plantuml|jeb|2.15.1
cypress-fixture-intellisense|Jos|1.2.0
rust-doc-viewer|JSc|2.0.1
vscode-github|Kni|0.30.6
rpm-spec|Lau|0.3.2
restructuredtext|lex|153.0.0
rust-analyzer|mat|0.2.662
hex-hover-converter|maz|1.2.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
hexeditor|ms-|1.7.1
test-adapter-converter|ms-|0.0.12
vs-qalc|nor|0.1.7
vetur|oct|0.34.1
oso|oso|0.1.0
git-file-history|pom|1.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.0
jinjahtml|sam|0.16.0
ansi-color-code|Seb|0.1.1
crates|ser|0.5.9
markdown-preview-enhanced|shd|0.5.22
vscode-rust-test-adapter|Swe|0.11.0
shellcheck|tim|0.14.4
vscode-lldb|vad|1.6.5

(1 theme extensions excluded)

</details>

**Comment by ximon18** [comment]
Note: If I change the user setting "Lldb: Show Disassembly" from "auto" to "never" then I instead see the `mod.rs` source file flash up every time instead of the disassembly.

**Comment by ximon18** [comment]
Note: It also happens on "Step Into", not just "Step Over".

**Comment by RYDB3RG** [comment]
It happens also when singlestepping via ms-vscode.cpptools gdb session.
It seems to happen only when there are multiple threads around, which it briefly switches to then.

![GifMaker_20210711131028971](https://user-images.githubusercontent.com/7002848/125192699-8104d680-e249-11eb-8526-1c4f77854996.gif)

**Comment by bog735bog** [comment]
Same issue observed.
Gdb session with WSL. 
Debugger view briefly switches to another thread (and returns back in fraction of second) on every single debug step (F10).
VS Code version: 1.58.2

**Comment by weinand** [comment]
@ximon18 VS Code will start to have a disassembly view in 1.59.
So your "disassembly view" seems to be a feature of your specific debug extension.

**Comment by ximon18** [comment]
Ah, that's interesting!

**Comment by RYDB3RG** [comment]
@weinand removing this code https://github.com/microsoft/vscode/blob/9305cd060955caa9c434350657ebc25ead5858b2/src/vs/workbench/contrib/debug/browser/debugSession.ts#L955-L969 restores the old behaviour

it seems the 800ms timeout thing got lost somehow in https://github.com/microsoft/vscode/commit/5278e78731ce5f0e73c4af8f309960c839aebef3

**Comment by weinand** [comment]
@isidorn ?

**Comment by isidorn** [comment]
More details about that change are explained in my comment here https://github.com/microsoft/vscode/issues/125144#issuecomment-869641057

**Comment by RYDB3RG** [comment]
@isidorn do you think there is a way to fix it? (maybe put the timeout back to prevent instant focus switch)
and since vscode-lldb and ms-vscode.cpptools are affected, i'm not sure its really an extension issue

**Comment by isidorn** [comment]
There was never a timeout there. It existed for less than a day.
In order for this to not happen we would need to not focus or introduce a timeout. There are no plans to change this this milestone.

**Comment by RYDB3RG** [comment]
would it be okay to reopen the issue so it won't get lost? its a bit distracting when it switches around on every step

**Comment by isidorn** [comment]
I do not like that since this talks about the Disassembly view contributed by an extension. While we have a new built in disassembly view. Which I would find confusing when I look at this in a couple of milestone.
