### ISSUE TITLE
C# coloring usings could use 2 colors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1284]
Just having one color for the using statements looks bad imho
We should use one color for the `using` keyword and another for the rest.

<img width="217" alt="screen shot 2015-12-14 at 15 40 06" src="https://cloud.githubusercontent.com/assets/1926584/11783748/11e1fb9a-a279-11e5-8b7f-d2e421f403c3.png">

**Comment by aeschli** [comment]
This is a problem of the grammar, both using and name get the keyword scope

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#47
