### ISSUE TITLE
Keybinding to move focus to interactive window code entry cell

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#128497]
Moving issue from vscode-jupyter:
[https://github.com/microsoft/vscode-jupyter/issues/475](https://github.com/microsoft/vscode-jupyter/issues/475)

In short, it would be very helpful to have a dedicated keybinding function which can:
1. Bring focus to interactive window if not focused
2. Move cursor to code entry cell

I use the interactive window a lot, and this would really speed up my workflow. `cmd 1/2` sort of works, but a dedicate shortcut would be much more ideal. Thanks!

**Comment by rebornix** [comment]
It makes perfect sense to have this command. Not sure about the keybinding but we can introduce the command, and leave the keybindings to users.

**Comment by jaymegordo** [comment]
@rebornix yes sorry, just the command would be fantastic!

**Comment by rebornix** [comment]
@jaymegordo I'm thinking through how to implement this, it's trivial if the interactive window is the active editor and the command will focus the code input box. However if the interactive window is not active, I guess you would expect the command to find the visible interactive window for you and focus? 

Not sure though what's the expected behavior if there are more than one interactive window visible. We can probably focus the first one we find in the editor groups.

**Comment by jaymegordo** [comment]
@rebornix yeah I was trying to think about that too. I think for me personally, the preferred behavior would be the last (most recently) active interactive window, but I usually only have one IW open, so "first found" would also be completely fine for me. Whichever is easiest/best for you guys!

Just to give you some context, my workflow is to have ~1-10 `.py` files open between 2 tab groups, with one IW that I use to quickly test out code changes. So basically I'm just very frequently mousing back to my "home" - the code entry cell in the IW - hundreds of times per day.

**Comment by joyceerhl** [comment]
With the new native interactive window, as soon as the interactive window is activated, e.g. with ctrl+1/2, the input box will automatically receive focus--does that meet your use case @jaymegordo?

![recording (24)](https://user-images.githubusercontent.com/30305945/125530280-59fbd19c-51af-4f18-a522-f6cdad6bd18c.gif)

**Comment by jaymegordo** [comment]
@joyceerhl Unfortunately not quite.

This works if you just have side-by-side code editor and IW, but not if say the right side of that screen also has code editors, because it just jumps between active editors, but doesn't focus the IW if its not the active window. It also takes a bit more mental overhead if you don't know which window is currently active, eg sometimes you might have to do ctrl 1/2/1 just so sorta "check" where you are.

A dedicated command would be really nice because you could do *one* key command and it would always bring you back to the code entry cell of the IW.

**Comment by rebornix** [comment]
Didn't find enough time for this. I still think this is an interesting idea which we can add a command to support. Let's take a look next month.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/128497 can be tackled at the same time

**Comment by jaymegordo** [comment]
Any thoughts to tackle this? Would still be really awesome to have!! Thanks!

**Comment by amunger** [comment]
still trying to fit it in, seems like it should be pretty straightforward, so we just need to set some time aside for it.

**Comment by amunger** [comment]
the existing `interactive.input.focus` command should move focus to the most recently used IW's input box once the next insiders is released.
