### ISSUE TITLE
Task Terminal Closes When Task Fails

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128416]
This used to be different.
The new behavior makes it very hard to debug crashing tasks, as all the terminal output immediately disappears.

**Comment by alexr00** [comment]
Depending on what kind of task you're running, this has always been the case (if it's a background task it has always closed on failure, and now if you set the `close` option on the task it will also close).  Can you share the exact task you're using so I can confirm whether it's one that is supposed to close?

**Comment by hediet** [comment]
It is a background task indeed:

```json
{
    "type": "npm",
    "script": "dev",
    "problemMatcher": {
        "base": "$tsc",
        "background": {
            "activeOnStart": true,
            "beginsPattern": "assets",
            "endsPattern": "compiled"
        }
    },
    "isBackground": true,
    "presentation": {
        "reveal": "never"
    },
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
```

Is there a way to not make them close the terminal?

**Comment by alexr00** [comment]
You should be able to set the `close` `presentation` property to false to prevent the terminal from closing.

The terminal requires that we specify whether it will close at creation time, so we can't use the result of the task to control this.

**Comment by hediet** [comment]
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "dev",
			"problemMatcher": {
				"base": "$tsc",
				"background": {
					"activeOnStart": true,
					"beginsPattern": "assets",
					"endsPattern": "compiled"
				}
			},
			"isBackground": true,
			"presentation": {
				"reveal": "never",
				"close": false
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```
This does not prevent the terminal from closing when the dev script crashes immediately.
However, the terminal stays, when setting `isBackground` to `false`.

**Comment by alexr00** [comment]
That's definitely a bug!

**Comment by hediet** [comment]
Thank you for fixing this!
