### ISSUE TITLE
VS Code Locks Files

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128418]
Sometimes, VS Code keeps a lock on files, preventing any process from deleting that file.

In my case, it locked `dist/extension/index.js` and the webpack dev process immediately crashed (which was hard to debug due to #128416).
Reloading VS Code did not help. I had to exit and start VS Code.

This happens often (especially for node_modules) and is quite annoying, especially as Windows does not show which process holds the lock. Now, whenever some tool cannot delete a file, I have the feeling to kill and reopen all VS Code instances.

I'm on Windows 10.

**Comment by bpasero** [comment]
Unlikely to be our watcher which wouldn't lock inside a folder (possibly only the root folder). I suspect that some extension is installing a custom file watcher (TypeScript? https://github.com/microsoft/TypeScript/issues/32113, https://github.com/microsoft/TypeScript/issues/29407) and that may lock.

**Comment by hediet** [comment]
Is there a nice way on windows to figure out who/which component causes a lock?

**Comment by bpasero** [comment]
Maybe: https://helpcenter.gsx.com/hc/en-us/articles/115015880627-How-to-Identify-which-Windows-Process-is-Locking-a-File-or-Folder

**Comment by dbaeumer** [comment]
Yes, I used Process Explorer to find the process that has a lock on a file.

**Comment by bpasero** [comment]
Bump

**Comment by hediet** [comment]
I'll close this issue and will try to use the process explorer next time I experience it.

I'll reopen when I know more.
