### ISSUE TITLE
Cannot connect to the Extension Marketplace 

### ISSUE THREAD

**Issue by somersgreg** [microsoft/vscode#128438]
Its been a few months I've been waiting and wondering if this software will ever work.  Tried on Debian, Ubuntu, Win 10, 11.  None can install extensions so never got past installing and uninstalling.   Always installing newest version.  Error "We cannot connect to Marketplace ......

**Comment by sandy081** [comment]
Please share the logs from the following locations while you reproduce the issue
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by markovicdenis** [comment]
same issue here, get this error message when using the marketplace:
```
extensionsViews.ts:323 Error querying extensions gallery Cannot read property 'toLowerCase' of undefined
query @ extensionsViews.ts:323
```

**Comment by critamine** [comment]
Hi guys,

Running into a similar problem. Brand new installation of Manjaro and Brand new installation of vscode.

When attempting to search for extensions in the marketplace I am told it cannot connect. I've attached the console logs from the developer tools. Not too sure how to make sense of it. Would appreciate any input, thank you.
[vscode-app-1626298121199.log](https://github.com/microsoft/vscode/files/6825324/vscode-app-1626298121199.log)

I've tried the following:

- Disabled firewall (ufw)
- Updated all packages to most recent versions

I'm a linux n00b so I'm unsure what else I can do. Will continue working on this as I can. Thanks again.

**Comment by sandy081** [comment]
@markovicdenis Is there a full stack trace of this error in the console? or in the logs `View > Open View > Log (window)` ?
If so can you please share it?

**Comment by markovicdenis** [comment]
@sandy081 Weirdly enough I don't see a "Log (window)" under open view options following your 4 step instructions. Best I can do is use the "Save as" button in the console. I should also mention that this issue only happens on VSCode Insiders build, everything works fine in the stable version...

[vscode-app-1626423119606.log](https://github.com/microsoft/vscode/files/6829030/vscode-app-1626423119606.log)

**Comment by sandy081** [comment]
Can you please try the command `Developer: Open Log File...` ?

**Comment by markovicdenis** [comment]
> Can you please try the command `Developer: Open Log File...` ?

Yeah, that works...

[rendererLog.txt](https://github.com/microsoft/vscode/files/6829602/rendererLog.txt)

**Comment by luboi75** [comment]
after recent update (12th July 2021) I get "We cannot connect to the Extension Marketplace at this time, please try again later."

**steps to reproduce**:

1. open vscode
2. switch to extensions
3. type any string in the search box

version information
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.14
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.49-1-MANJARO

additional info - from developer console
Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Request header field x-market-user-id is not allowed by Access-Control-Allow-Headers in preflight response.
extensionsViews.ts:323 Error querying extensions gallery XHR failed
query @ extensionsViews.ts:323
async function (async)
query @ extensionsViews.ts:320
(anonymous) @ extensionsViews.ts:241
y @ async.ts:24
show @ extensionsViews.ts:239
(anonymous) @ extensionsViewlet.ts:693
onDidAddViewDescriptors @ extensionsViewlet.ts:692
(anonymous) @ viewPaneContainer.ts:531
fire @ event.ts:583
triggerOnDidAddVisibleViewDescriptors @ viewContainerModel.ts:447
onDidChangeContext @ viewContainerModel.ts:634
(anonymous) @ viewContainerModel.ts:329
fire @ event.ts:583
(anonymous) @ event.ts:73
fire @ event.ts:583
fire @ event.ts:713
setContext @ contextKeyService.ts:326
set @ contextKeyService.ts:200
doSearch @ extensionsViewlet.ts:680
(anonymous) @ extensionsViewlet.ts:645
(anonymous) @ async.ts:261
Promise.then (async)
trigger @ async.ts:255
triggerSearch @ extensionsViewlet.ts:645
(anonymous) @ extensionsViewlet.ts:552
fire @ event.ts:585
(anonymous) @ suggestEnabledInput.ts:173
(anonymous) @ textModel.ts:252
fire @ event.ts:583
endDeferredEmit @ textModel.ts:3567
pushEditOperations @ textModel.ts:1271
_innerExecuteCommands @ cursor.ts:787
executeCommands @ cursor.ts:745
_executeEditOperation @ cursor.ts:448
(anonymous) @ cursor.ts:655
_executeEdit @ cursor.ts:608
type @ cursor.ts:644
(anonymous) @ viewModelImpl.ts:983
_withViewEventsCollector @ viewModelImpl.ts:1050
_executeCursorEdit @ viewModelImpl.ts:969
type @ viewModelImpl.ts:983
_type @ codeEditorWidget.ts:1081
type @ codeEditorWidget.ts:1607
type @ viewController.ts:70
(anonymous) @ textAreaHandler.ts:266
fire @ event.ts:583
(anonymous) @ textAreaInput.ts:356
request.ts:42 POST https://open-vsx.org/vscode/gallery/extensionquery net::ERR_FAILED

**Comment by critamine** [comment]
@luboi75

I am running Manjaro as well and ran into this exact same issue after installing the app via pacman.
How I ended up resolving it was removing code and replacing it with the [snaps package](https://discover.manjaro.org/snaps/code).

**Comment by jlvdh** [comment]
Same here, Snaps package solved it.

**Comment by luboi75** [comment]
@critamine 
thanks for the hint. My choice was to downgrade to version, that did not suffer from the issue
