### ISSUE TITLE
Debug not autoscrolling with repeating newline

### ISSUE THREAD

**Issue by arash-bizcover** [microsoft/vscode#128460]
Does this issue occur when all extensions are disabled?: **Yes**

- Version: 1.58.0
- Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
- Date: 2021-07-08T06:53:55.113Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Linux x64 5.4.0-77-generic

When debug output has repeating text and specifically it has newline `\n` in the output, this happens.

**👁 Please don't close this I have read [these](https://github.com/microsoft/vscode/issues/118702) 2 [issues](https://github.com/microsoft/vscode/issues/32632), this one is different. I promise, look:**

Steps to Reproduce:

![bug](https://user-images.githubusercontent.com/62287461/125251677-e97fb080-e33a-11eb-9636-aac0cac582e1.gif)

Just print some repeating text which has newline in it:
Specifically, I ran this:
```javascript
console.log(`1

`);
```

I use nodemon and my debug configuration is this:
```json
{
    "launch": {
        "configurations": [
            {
                "name": "Local nodemon",
                "request": "launch",
                "cwd": "${fileDirname}",
                "program": "/usr/local/bin/nodemon",
                "args": [
                    "--inspect",
                    "${file}"
                ],
                "skipFiles": [
                    "<node_internals>/**"
                ],
                "type": "pwa-node"
            }
        ]
    }
}
```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/117674
