### ISSUE TITLE
TypeScript project breakpoint is unbounded on vscode 1.58, but can set on vscode 1.57.1

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode#128462]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58
- OS Version: macOS 10.15.7

Steps to Reproduce

1. run DEBUG
2. Set breakpoint
3. breakpoint is unbound

These steps works normal on VS Code Version 1.57.1

launch.json

"configurations": [
      {
          "type": "pwa-node",
          "request": "launch",
          "name": "main",
          "runtimeExecutable": "nodemon",
          "restart": true,
          "env": {
              "NODE_ENV": "development",
              "IS_DEV": "1",
              "DEBUG": "nb:*",
          },
          "console": "internalConsole",
          "internalConsoleOptions": "openOnSessionStart",
          "program": "${workspaceFolder}/dist/bin/app.js",
      },
]

**Comment by leonkong** [comment]
Here is the log file, [
[vscode-debugadapter-a8bc78e8.zip](https://github.com/microsoft/vscode/files/6807031/vscode-debugadapter-a8bc78e8.zip)
](url)

**Comment by connor4312** [comment]
@leonkong You're using the "Run Without Debugging" action, so it's expected that breakpoints don't work here.

You can debug using the F5 keyboard shortcut (unless you've remapped it), the `Debug: Start Debugging` command, or the play button in the Debug view.

**Comment by leonkong** [comment]
I found a new bug, I will open a new issue

**Comment by leonkong** [comment]
Thanks, I found that the keyboard shortcuts map had some problem, I will correct it myself. Thanks you.
