### ISSUE TITLE
Spacebar stopped working in the editor

### ISSUE THREAD

**Issue by Stockowl** [microsoft/vscode#128431]
Suddenly my spacebar stopped working in the code editor. Instead, I have to use Shift + Space, which is very unusual. It was working yesterday, today, it doesn't. I did not change any settings. And my spacebar works completely fine in the terminal, or the extension browser for example. My current vscode version is 1.58.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<Space>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
