### ISSUE TITLE
Cannot focus to a re-opened terminal

### ISSUE THREAD

**Issue by shikibu-z** [microsoft/vscode#128437]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

- VS Code Version: 1.58.0
- OS Version: Ubuntu 20.04
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:53:55.113Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic
```

Steps to Reproduce:

1. Use Ctrl + ` to open a terminal (the focus is switched to the terminal automatically).
2. Use 'exit' in the terminal to close.
3. Use Ctrl + ` again to open a terminal
4. The focus cannot be switched to the terminal automatically as step 1 does. Will have to reload the window.

**Comment by iamCristYe** [comment]
dup of https://github.com/microsoft/vscode/issues/128255
