### ISSUE TITLE
Terminal editors do not respond to keybindings

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode#128405]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.58.0 (Universal)
- OS Version: OS: Darwin x64 20.5.0

Steps to Reproduce:

1. Open a terminal in an editor (`workbench.action.createTerminalEditor`)
2. Focus on the terminal editor
3. Press shortcut keys for navigating to other panes, or to move an editor window

On some rare occasions they will work, but mostly they will not. I'm struggling to identify what the distinguishing setup is that results in it working sometimes.

**Comment by leighmcculloch** [comment]
Something that is more consistent is that navigating from a terminal editor to the terminal panel doesn't work with action `workbench.action.navigateDown`. The navigation actions work from a file editor window to a terminal panel works, and navigating from the terminal panel to a terminal editor.

Another thing that is odd, is that sometimes running the navigate down action from the CMD-P menu in a file editor will cause focus to move right to a terminal editor to the right, rather than down to the terminal panel below.

**Comment by mishrasidhant** [comment]
Duplicates 
* [Terminal navigation mode broken (#107574)](https://github.com/microsoft/vscode/issues/107574)
