### ISSUE TITLE
Tune the wording of the trust dialog when a folder is empty

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#128457]
- create a new empty folder
- open the folder

You get prompted whether you trust the files in this folder:
![image](https://user-images.githubusercontent.com/172399/125242747-62581b80-e2ed-11eb-8abf-fa949093a772.png)

The message should be sensitive to the fact that there are no files in the folder.

**Comment by kieferrm** [comment]
Things to consider:
- You open an empty folder, then you clone a repo into this folder using the command line or unzip a downloaded zip file, file watching picks up the changes.
- You clone a repo, you create an empty folder inside the cloned repo, then you that empty folder in a new window. Some extensions like ESLint walk up the parent folder chain and run code from there.
