### ISSUE TITLE
Quick Info should apply to all completion items, rather than selectively 

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12844]
Testing https://github.com/Microsoft/vscode/issues/12598

Right now Quick Info only appears for certain items in the list (e.g. `apply` and `call`, but not `all`)

quick info:
![image](https://cloud.githubusercontent.com/assets/762848/18896396/43ba774c-84d6-11e6-8c3b-a2ee9480b5ed.png)

no quick info:
![image](https://cloud.githubusercontent.com/assets/762848/18896386/36ba7e8e-84d6-11e6-9432-4cafedff2d7a.png)

This results in an inconsistent user experience, where a user might ctrl+space in order to see additional details about the function (either because they believe there is documentation, or because the info they can see is cut off.)

Ideally, the quick info box would be displayed for every completion item, even if the documentation on that isn't _as_ comprehensive as the other options

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
