### ISSUE TITLE
electron_node tsserver.js issue

### ISSUE THREAD

**Issue by brascene** [microsoft/vscode#128414]
Issue Type: <b>Performance Issue</b>

This issue happened suddenly, after using VSCode for very long time, it was always very fast and was never lagging or anything, but suddenly the intellisense stopped, as well as imports, autocomplete, linter etc. it's all in loading state, and I've noticed a task in process explorer which is taking 100% CPU.

It sometimes occurs after startup, and sometimes it works fine just after opening VSCode, but then soon after changing types, importing modules or go to definition, it happens again.

I've tried different versions of VSCode, changing typescript version, deleting caches, restarting etc. but issue is still present. 
I've seen similar or the same issue reported last year, but looks like no solution was mentioned, and they're still open.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:16.617Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 6365e737-e779-4976-a198-0b5e583b1aa1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   131	 29363	code main
    3	    66	 29366	   gpu-process
    0	    25	 29368	   utility
    1	   229	 29369	   window (const.ts — fbo-app)
    0	   115	 29587	     extensionHost
    0	    57	 29594	       electron_node tsserver.js 
  100	   590	 29595	       electron_node tsserver.js 
    0	    25	 29607	         electron_node typingsInstaller.js typesMap.js 
    0	    57	 29618	       electron_node eslintServer.js 
    0	    33	 29629	       /private/var/folders/mm/nsnkvhn15m995lnc56y4j4km0000gn/T/AppTranslocation/E5CA956C-78E5-458C-A10A-0840995DC051/d/Visual Studio Code-2.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/mm/nsnkvhn15m995lnc56y4j4km0000gn/T/AppTranslocation/E5CA956C-78E5-458C-A10A-0840995DC051/d/Visual Studio Code-2.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=29587
    0	    33	 29591	     watcherService
    0	    41	 29600	     searchService
    5	    74	 29589	   shared-process
    0	    33	 29592	     ptyHost
    0	     0	 29709	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	    74	 29705	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (const.ts — fbo-app)
|    Folder (fbo-app): 19310 files
|      File types: hpp(12319) h(2410) ts(503) tsx(253) so(202) json(192)
|                  ipp(173) flat(166) m(139) xml(137)
|      Conf files: settings.json(1) package.json(1) tsconfig.json(1)
|                  tslint.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.0.1
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by brascene** [comment]
Just tried it, version 1.59.0-insider, no extensions installed, the same thing, and the same process is eating cpu.

**Comment by vkozinec** [comment]
Having exactly the same issue as mentioned above, Code Helper goes beyond 100% CPU usage,

```
Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z (5 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0
```

**Comment by ivanvoznyakovsky** [comment]
```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```
got something very similar. editor becomes unusable, you can't type because of the lags.
activity monitor shows up to 4 `Code Helper (Renderer)` processes each consuming up to 100% of CPU.
this does reproduce in latest insiders with or without extensions.

**Comment by brascene** [comment]
Just tried the latest insider version, and so far it works perfectly.

Version: 1.59.0-insider
Commit: e8a59bc6f920e731b47f0bc72263e82aba8b796e
Date: 2021-07-22T05:24:54.888Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.5.0

**Comment by mjbvz** [comment]
Great! Not sure what changed but hopefully it has been fixed
