### ISSUE TITLE
Inability to copy errors 

### ISSUE THREAD

**Issue by akmalsoliev** [microsoft/vscode#128499]
## Environment data

-   VS Code version: 1.58.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Mac OS Big Sur, Windows 10 
-   Python and/or Anaconda version: conda 4.10.1, Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
-   Jupyter server running: Local

## Expected behaviour

Copy and paste code errors in the output

## Actual behaviour

Inability to copy errors. 

## Steps to reproduce:

1. Run `int('Hello World')`
2. Try to copy ValueError
3. Inability to copy or paste ValueError

## Logs

Info 2021-07-11 20:38:18: Cell Index:17, state:3, exec: 26. Executed successfully in executeCell
Info 2021-07-11 20:38:18: Cell Index:17, state:3, exec: 26. Execution disposed

**Comment by DonJayamanne** [comment]
Possibly a dup of https://github.com/microsoft/vscode/issues/124917

**Comment by akmalsoliev** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Markdown inline code not rendering correctly? (#125300)](https://www.github.com/microsoft/vscode/issues/125300)

Not a markdown issue, the issue is only presented in the jupyter cell output. 

> Possibly a dup of #124917

Possible, occurs only when there is an error, doesn't happen with a normal output.

**Comment by akmalsoliev** [comment]
Update: Noticed that whenever I select a section of an error the copy is successful, however, when I double click and select the full error line it gives me this error. 

https://user-images.githubusercontent.com/24494206/125660208-7d1d1371-7920-4289-aa07-00e6c8237122.mov

**Comment by rebornix** [comment]
@akmalsoliev brilliant reproduce steps, thanks for your help

Verifier:

* Create a Jupyter notebook
* Insert a cell with `print(fo)` and run
* Switch the renderer of the output to the builtin one
* Test https://github.com/microsoft/vscode/issues/128499#issuecomment-880045948
