### ISSUE TITLE
Saving terminals (per project)

### ISSUE THREAD

**Issue by MauritsWilke** [microsoft/vscode#128544]
Hi! I'd like to be able to save terminals per project or being able to open them with a shortcut.
I have a project that needs 3 running terminals that I always customise in the same way (colour, name, icon and command) and i'd like to just open those all with a shortcut or a way to at least open them from a command

**Comment by meganrogge** [comment]
Have you thought about using tasks for this?

Another good resource is https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

**Comment by MauritsWilke** [comment]
> Have you thought about using tasks for this?
> 
> Another good resource is https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

Ill look into this! Thanks

Would be nice to have it be a standard feature ofc :)

**Comment by MauritsWilke** [comment]
> Have you thought about using tasks for this?
> 
> Another good resource is https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

Doesn't seem to be saving the terminal looks though, maybe im doing something wrong but other than the name nothing is configurable (with looks)

**Comment by ArnieGA** [comment]
Hi:
I gave this _vscode-terminals_ a try but honestly, it wasn't what I was looking for.  I'm actually after something like what @MauritsWilke initially proposed.  I'm needing a way to tell VS Code that whenever I open/load a **specific** project folder in the editor, I want 3 terminals to be automatically loaded:
- Terminal #1 will be labeled "SOLUTION", will cd/start at _**./**_, and it'll be a regular Windows CMD Prompt terminal.
- Terminal #2 will be labeled "API", will cd/start at _**./API/**_, and will also be a regular Windows CMD Prompt terminal.
- Terminal #3 will be labeled "CLIENT", will cd/start at _**./client-app/**_, and will be a Git Bash terminal.

I really don't care much for their styling (although it would be a lot better if we're able to configure that as well) at the moment.

Thank you for your time :-)

**Comment by Tyriar** [comment]
@ArnieGA you could use [tasks](https://code.visualstudio.com/docs/editor/tasks) for this:

![recording (46)](https://user-images.githubusercontent.com/2193314/126560811-9863de2a-89f1-447a-bcea-32798eb2073d.gif)

Here's the .vscode/tasks.json I used for that:

```json
{
  "version": "2.0.0",
  "presentation": {
    "echo": false,
    "reveal": "always",
    "focus": false,
    "panel": "dedicated",
    "showReuseMessage": true
  },
  "tasks": [
    {
      "label": "Setup terminals",
      "dependsOn": [
        "SOLUTION",
        "API",
        "CLIENT"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    },
    {
      "label": "SOLUTION",
      "command": ["cmd"],
      "type": "shell",
      "group": "build",
      "isBackground": true,
      "problemMatcher": [],
      "options": {
        "cwd": "."
      }
    },
    {
      "label": "API",
      "command": ["cmd"],
      "type": "shell",
      "group": "build",
      "isBackground": true,
      "problemMatcher": [],
      "options": {
        "cwd": "API"
      }
    },
    {
      "label": "CLIENT",
      "command": ["bash"],
      "type": "shell",
      "group": "build",
      "isBackground": true,
      "problemMatcher": [],
      "options": {
        "cwd": "client-app"
      }
    }
  ]
}
```

Adding presentation.group like this would let you create split terminals:

```
      "presentation": {
        "group": "vscode"
      }
```

You can run this using ctrl+shift+b but it also has [auto run enabled on folder open](https://code.visualstudio.com/docs/editor/tasks#_run-behavior) (see `runOn`)

**Comment by ArnieGA** [comment]
Thx!! :-D

**Comment by ArnieGA** [comment]
@Tyriar Thank you! It did work! However, I had to add bash's filepath to Windows' PATH in order for CLIENT to work.  I still believe this functionality should be available without having to touch the tasks file.  Cheers!

**Comment by Tyriar** [comment]
I added a more generic example of the above to the website: https://github.com/microsoft/vscode-docs/commit/50815e751bc2f1e7ad09c0cbcf117bbc31dd3c56

**Comment by ArnieGA** [comment]
> @Tyriar Thank you! It did work! However, I had to add bash's filepath to Windows' PATH in order for CLIENT to work. I still believe this functionality should be available without having to touch the tasks file. Cheers!

> I added a more generic example of the above to the website: [microsoft/vscode-docs@50815e7](https://github.com/microsoft/vscode-docs/commit/50815e751bc2f1e7ad09c0cbcf117bbc31dd3c56)

Confirming that, by replacing the "CLIENT" configuration with the following (based on your last post):
```
		{
			"label": "CLIENT",
			"command": "",
			"type": "shell",
			"group": "build",
			"isBackground": true,
			"problemMatcher": [],
			"options": {
				"shell": {
					"executable": "C:\\Program Files\\Git\\bin\\sh.exe",
					"args": []
				},
				"cwd": "client-app"
			}
		}
```
...made it possible for me to remove Git's **bin** folder from Windows' PATH.  Hoping this helps any other fellow dev out there.  Thank you very much for your time and effort.  Cheers!

**Comment by Tyriar** [comment]
Nice, yeah the shell executable part means only a single shell is launched which would speed things up

**Comment by TheColorRed** [comment]
I would also like to see the ability for the terminals to execute the last command for any long running commands such as a local server.

![image](https://user-images.githubusercontent.com/1571806/129224618-111a54e7-78a8-4a8e-9188-b2048184b067.png)

**Comment by Tyriar** [comment]
While we aren't planning on introducing this feature there are alternatives:

- Extensions will soon be able to access an API that lets them split terminals or create them in the editor area https://github.com/microsoft/vscode/issues/45407
- We are looking into saving and restoring the buffer on restarts this iteration https://github.com/microsoft/vscode/issues/131634
- Tasks are quite powerful and are now my tool of choice for creating several terminals in a project
