### ISSUE TITLE
breakpoints don't trigger when starting debug from touchbar

### ISSUE THREAD

**Issue by jackbow** [microsoft/vscode#128512]
Issue Type: <b>Bug</b>

When I start debugging (at least in python using the microsoft python extension) from the touchbar button breakpoints don't trigger. This is with either run button (the one with the little bug on it or the one without). Without changing anything the breakpoints trigger when starting debugging from the debug tab's green arrow button at the top.

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_57358 --crash-reporter-id 999b135d-580f-4aad-aa07-26171592252c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
vscode-color|ans|0.4.5
vscode-tailwindcss|bra|0.6.13
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.1
indent4to2|Com|0.1.2
vscode-eslint|dba|2.1.23
vscode-dash|dee|2.4.0
empty-indent|Dmi|0.2.0
gitlens|eam|11.5.1
EditorConfig|Edi|0.16.4
vscode-svelte-snippets|fiv|0.5.0
auto-close-tag|for|0.5.10
code-runner|for|0.11.4
shell-format|fox|7.1.0
todo-tree|Gru|0.0.213
autofix|Lwl|1.0.0
rust-analyzer|mat|0.2.662
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.6.999662501
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.4498
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
svelte-vscode|sve|105.2.2
language-stylus|sys|1.11.0
vscode-status-bar-format-toggle|tom|2.0.0
vscode-lldb|vad|1.6.5
vscodeintellicode|Vis|1.2.14
vuetify-vscode|vue|0.2.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
material-theme|zhu|3.10.14

(4 theme extensions excluded)

</details>

**Comment by weinand** [comment]
The "Run" and "Debug" touch bar buttons are swapped in VS Code 1.57.
Please upgrade to the latest.
