### ISSUE TITLE
JS completions are... too complete 

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12850]
Testing https://github.com/Microsoft/vscode/issues/12598

Two files `server.js` and `a.js`. `server.js` has no references to `a.js`, but `foo` nevertheless appears in the completion list.
![image](https://cloud.githubusercontent.com/assets/762848/18896874/26229080-84da-11e6-8ecf-e16240a9becd.png)

May be related to #12849

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11231
