### ISSUE TITLE
Allow `args` string in `tasks.json`

### ISSUE THREAD

**Issue by FaustVX** [microsoft/vscode#128561]
In `.vscode/launch.json` we could pass a string in `args`, but in `.vscode/tasks.json` we can only pass an array of strings.

In my situation, I want to pass an input via `${input:args}`, (like `resize -w10 -h10`) and still have the string splited to have `resize`, `-w10` and `-h10` passed to my program.
This works well in `launch.json`, but `tasks.json` require an array.

**Comment by weinand** [comment]
VS Code knows nothing about launch.json properties like "args". All properties are contributed by individual debug extensions. So you will have to file a feature request against the debugger extension you are using.
