### ISSUE TITLE
Update "Getting Started" terminology

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#128580]
This issue covers updating our terminology to move away from using "Getting Started" as it has become an overloaded term. We use it both in the title and actual walkthroughs:

<img width="486" src="https://user-images.githubusercontent.com/35271042/125530086-587af31d-184f-44ed-85bf-ee5b2ef79258.png">

## Proposal

I suggest we change the title to "Walkthroughs" as it best represents what they are. Then each item can use "Getting Started" in their content without feeling like they repeating the same word as this extension API.

<img width="486" alt="CleanShot 2021-07-13 at 14 53 55@2x" src="https://user-images.githubusercontent.com/35271042/125530336-0f5e135f-08c1-4416-9da6-5cee21e8be3c.png">

**Comment by digitarald** [comment]
"Walkthrough" is great, as it also maps to the name of the contribution!

We also just discussed to consider hiding the header of the right column, as it doesn't add much context and "Start" is also a header on the left column.
