### ISSUE TITLE
'Page Down' key treats large cell output as "barrier"

### ISSUE THREAD

**Issue by scsleal** [microsoft/vscode#128591]
## Environment data

-   VS Code version: 1.59.0-insider
-   Jupyter Extension version: 2021.8.1025925145
-   Python Extension version: 2021.6.944021595
-   OS and version: Windows_NT x64 10.0.19041
-   Python version: 3.8.3 64-bit
-   Type of virtual environment used: virtualenv
-   Jupyter server running: Local

## Expected behaviour

- Page Down key scrolls down the notebook more quicker by jumping one or more cells at once according the size of vscode window and the size of the cells.
ex: cell 1 --> cell 7 -->  cell 13 --> ...

## Actual behaviour

- When the cell output (or maybe the cell input as well) is too big (more precisely, in vertical direction), it becomes a "barrier" which prevent to Page Down key to scroll down.

## Steps to reproduce:

![Alt Text](https://media.giphy.com/media/L2d9No0fPF13CDADK9/giphy.gif)

## Logs

N.A

**Comment by rebornix** [comment]
Turns out this is a list command.

**Comment by roblourens** [comment]
I believe this was fixed in https://github.com/microsoft/vscode/issues/149502
