### ISSUE TITLE
sort order of threads from debug adapter is not maintained

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode#128546]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.0

From #5830 it seems that the sort order of the threads in the call stack view are determined by the debug adapter. However, if there is a new thread that is added, it is simply added to the end of the list of threads, no matter where it was put in the results list.

Example:

<img width="1030" alt="Screen Shot 2021-07-13 at 11 31 42 AM" src="https://user-images.githubusercontent.com/6634754/125481380-5ab2e704-c528-4a48-9537-e8c1fe0e496d.png">

New thread added, 3rd in the list:
2021-07-13T11:31:44-04:00 debug layer=dap [-> to client]{
"seq":0,
"type":"response",
"request_seq":25,
"success":true,
"command":"threads",
"body":{
    "threads":[
        {"id":1,"name":"* [Go 1] main.deadlock (Thread 28692229)"},
        {"id":17,"name":"[Go 17] runtime.gopark"},
        **{"id":18,"name":"[Go 18] main.deadlock.func1"}**,
        {"id":2,"name":"[Go 2] runtime.gopark"},
        {"id":3,"name":"[Go 3] runtime.gopark"},
        {"id":4,"name":"[Go 4] runtime.gopark"}
    ]
}}

It is added to the end of the list of threads:
<img width="1028" alt="Screen Shot 2021-07-13 at 11 31 52 AM" src="https://user-images.githubusercontent.com/6634754/125481408-f8bf9d3c-6d45-4ea0-ae7c-75f6f7e08321.png">

**Comment by isidorn** [comment]
Sorry for the slow response, I was on vacation.
Thanks for reporting this issue and for creating a PR that tackles it.
The PR also looks good, however this week we are in the endgame thus we are not accepting new code, and I will probably merge this in start of next week. Thanks!
