### ISSUE TITLE
Closing File freezes VSCode for a second

### ISSUE THREAD

**Issue by BerkeAras** [microsoft/vscode#128567]
Issue Type: <b>Performance Issue</b>

Just close a File - see issue.

VS Code version: Code 1.58.0 (Universal) (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id 218c3f12-e3ec-4ae3-8b4b-fafa3601a1ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.13
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-database-client2|cwe|3.9.4
macos-modern-theme|dav|2.1.9
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.11
auto-rename-tag|for|0.1.7
live-sass|gle|5.0.4
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
path-autocomplete|ion|1.17.1
mysql-syntax|jak|1.3.1
remotefs|lix|0.0.16
vscode-JS-CSS-HTML-formatter|lon|0.2.3
regionfolder|map|1.0.15
vscode-language-pack-de|MS-|1.58.7
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
mdx|sil|0.1.0
sass-indented|syl|1.8.17
tabnine-vscode|Tab|3.4.13
es6-string-html|Tob|2.10.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
material-ui-snippets|vsc|3.3.3
twig|wha|1.0.2
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by BerkeAras** [comment]
@kieferrm What kind of Information do you need? I submitted the issue using the Performance-Issue Tool in VSCcode.

**Comment by kieferrm** [comment]
Please have a look at: https://github.com/microsoft/vscode/wiki/Performance-Issues. I'm guessing it's one of the extensions you have installed. You can also use extension bisect: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect. Thanks!

**Comment by BerkeAras** [comment]
@kieferrm bisect could not find any issues :( It told me that the possible problem is "code."

**Comment by deepak1556** [comment]
Please follow the steps below to get following two traces:

1) Main process

```
* Launch vscode like `code --inspect=9229`
* In chrome browser visit chrome://inspect or in edge browser visit edge://inspect
* You should see an entry under Remote Target that starts with /Applications/Visual Studio Code/....
* If you don't see the above entry, then
  * Under Devices, click open dedicated devtools for node
  * Under Connection tab, add localhost:9229
  * You should now see the target
* Click inspect
* Go to Profiler tab and start the CPU profiler
* Now perform the steps in vscode that recreate the slowdown
* Stop the profiler and attach it to this issue.
```

2) Workbench process

```
* Launch vscode normally
* Open Command Palette and run `Toggle Developer Tools`
* Choose Performance tab
* Hit the reload and record button
* Perform the steps to slowdown and stop recording
* Attach the generated trace
```
