### ISSUE TITLE
inno_updater.exe may be preventing itself from deleting code.exe

### ISSUE THREAD

**Issue by davidlanderos-digital** [microsoft/vscode#128584]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: every update
- OS Version: Windows 10

Steps to Reproduce:

1. Wait for a new VS Code version to be released

You already know, the updater fails for some of us: https://github.com/microsoft/vscode/issues/47841

I use ProcessExplorer to check which process is locking a file (by having a handle to it)

![Screenshot 2021-07-13 145806](https://user-images.githubusercontent.com/79719460/125531862-68015205-996f-4f59-886b-fe621f81a777.png)

It turns out it's the updater itself  :/

Code is definitely not running as demonstrated by ``tasklist | find "code.exe"``  

![Screenshot 2021-07-13 145506](https://user-images.githubusercontent.com/79719460/125531996-e1638daa-a980-473e-a281-f7b99219d081.png)

**Comment by joaomoreno** [comment]
Something is odd since both those processes shouldn't be operating at the same time. Can you reproduce this 100% of the time? Can you reproduce on Insiders?
