### ISSUE TITLE
Jumping to extension setting fails when Settings is freshly opened

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#128587]
Issue Type: <b>Bug</b>

STR:

1. Install LTeX extension (`valentjn.vscode-ltex`), wait for walkthrough to open
2. In the walkthrough that opens, click on the button for "Customize settings"
3. Settings opens with search `@ext:valentjn.vscode-ltex`

ER: Settings are filtered down to extension
AR: Settings are unfiltered.

Clicking the button again while Settings is open or manually typing the search term works.

https://user-images.githubusercontent.com/8599/125533038-ead2a929-cd63-4ad8-8276-86e78feadf85.mov

VS Code version: Code - Insiders 1.59.0-insider (a9070718ebb793eef4e94e34307eee15c09a0cd4, 2021-07-12T05:12:20.084Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (0.07GB free)|
|Process Argv|--user-data-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/data-15-17-26 --extensions-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/ext-15-17-26 --log=trace --enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ltex|val|10.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Probably 128160

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/128554

**Comment by roblourens** [comment]
Or https://github.com/microsoft/vscode/issues/128160 :)
