### ISSUE TITLE
Improve discoverability of notebook customization

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#128549]
## Problem

We have a wide range of notebook settings that allow the users to change the layout and behavior of a notebook, but not many users know about them. This issue explores how to improve the discoverability of these settings and other notebook related items (Getting Started, etc.).

<img width="999" alt="CleanShot 2021-07-13 at 09 29 50@2x" src="https://user-images.githubusercontent.com/35271042/125490370-1bee163d-7039-4efa-a85d-113d48b41ddb.png">

- `notebook.breadcrumbs.showCodeCells`
- `notebook.cellFocusIndicator`
- `notebook.cellToolbarLocation`
- `notebook.cellToolbarVisibility`
- `notebook.compactView`
- `notebook.consolidatedOutputButton`
- `notebook.consolidatedRunButton`
- `notebook.diff.enablePreview`
- `notebook.diff.ignoreMetadata`
- `notebook.diff.ignoreOutputs`
- `notebook.displayOrder`
- `notebook.dragAndDropEnabled`
- `notebook.editorOptionsCustomizations`
- `notebook.experimental.useMarkdownRenderer`
- `notebook.globalToolbar`
- `notebook.insertToolbarLocation`
- `notebook.lineNumbers`
- `notebook.navigation.allowNavigateToSurroundingCells`
- `notebook.outline.showCodeCells`
- `notebook.showCellStatusBar`
- `notebook.showFoldingControls`
- `notebook.undoRedoPerCell`

### Show a gear in the global toolbar

One option was to show a ⚙️ in the global toolbar where it would be more visible. Currently these options live in a `...` in the toolbar but they're not as easily discoverable. This would help make the association clearer as we use the gear for customization in other areas (activity bar, command palette, settings, etc.)

<img width="702" alt="CleanShot 2021-07-13 at 08 57 58@2x" src="https://user-images.githubusercontent.com/35271042/125485258-db1e3dde-02d7-4aeb-86a3-8798c01fa9a8.png">

### Show a gear in the editor toolbar

Alternatively we could place the gear in the editor toolbar. This option was preferred by the team after internal discussions regarding the toolbars. The point being that the left side of the toolbar relates to notebook actions (run, clear, restart, etc.) and the right side was for kernel management. 

<img width="728" alt="CleanShot 2021-07-13 at 08 55 59@2x" src="https://user-images.githubusercontent.com/35271042/125484947-2594a563-306a-4703-8aa7-5b854bcd0593.png">

**Comment by rebornix** [comment]
Since currently we couldn't figure out the difference from the dropdown of notebook toolbar or the gear icon on the editor titlebar, I took the advice from @Tyriar: using different action ids for the actions contributed to the editor titlebar.

To test this, please check if you get different telemetry events when running Customize Notebook Layout or Toggle Breakcrumbs, etc actions from these two different places.

**Comment by roblourens** [comment]
I think this is resolved?
