### ISSUE TITLE
Active item isn't being tracked on the File Explorer

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#128538]
Issue Type: <b>Bug</b>

When switching files through open tabs, File Explorer neglects to select the current active item (even though it's part of the current workspace).

VS Code version: Code - Insiders 1.59.0-insider (f6df685c62da50886f7540cbf768ed4333d58bea, 2021-07-13T05:12:59.073Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.11GB free)|
|Process Argv|--crash-reporter-id 4e347825-8035-44ec-905f-4159d9ffe78f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vscode-pull-request-github|Git|0.28.0
vscode-todo-parser|min|1.9.1
env-cmd-file-syntax|Nix|0.3.0
material-icon-theme|PKi|4.8.0
vscode-yaml|red|0.21.0
sourcery|sou|0.9.3
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlang:30310088
vsccppwt:30312692
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your value for `explorer.autoReveal` setting?

Does it happens for any editor tab or only only for diff/custom editors?

**Comment by bruno-brant** [comment]
> What is your value for `explorer.autoReveal` setting?
![image](https://user-images.githubusercontent.com/1890900/125489474-8120e259-8e26-4f8a-81c9-e777782884d5.png)


> Does it happens for any editor tab or only only for diff/custom editors?
Any tab. I'll upload a quick video. 

Further info:

I'm can't be precisely sure when this issue arose, but I'm sure it was on one of the recent (let's say 3 or 4) versions. Tracking the active item is something I usually miss when navigating code (the first thing I configure in fresh VS Community installations since it's off by default 😊).

**Comment by bruno-brant** [comment]
Heck, it stopped happening. Not sure what I did (I don't think I restarted the environment since posting). 

I'll try to reproduce and come back here.

**Comment by bruno-brant** [comment]
Okay, it is happening again. I did not restarted VS - it began just as it stopped, without any cause that I can track down. I would guess it has something to do with the VS window losing and regaining focus, because I'm alt-tabbing the whole time between the VS and the browser.

https://user-images.githubusercontent.com/1890900/125493374-b21d2957-a374-448c-af0a-425b99cc999a.mp4

**Comment by isidorn** [comment]
I unfortunately can not reproduce this.
Since you seem to be able to repro, can you please F1 > developer tools > put a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileCommands.ts#L329) and try to figure out why the activeFile is not being revealed
