### ISSUE TITLE
Support "simplified UI" debug session

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#128582]
https://github.com/microsoft/vscode/issues/126431

To support Jupyter's "Run by line" mode, we should support a mode for a debug session that will be different in the following ways

- the window statusbar will not change color
- the debug widget will not appear
- the debug viewlet will not be shown automatically

**Comment by isidorn** [comment]
I just came back from vacation and this week is endgame, should we move this to August?
Or let me know how I can help?

**Comment by roblourens** [comment]
Actually, this was implemented in https://github.com/microsoft/vscode/pull/128801
