### ISSUE TITLE
strange error warning with ts quickstart showcase

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#12854]
- VSCode Version: 1.5.3
- OS Version: mac

Steps to Reproduce:

1. copy example from http://www.typescriptlang.org/docs/tutorial.html
2. paste to vscode and save
3. got many warning, such as `duplicate`
  ![image1](https://cloud.githubusercontent.com/assets/227713/18897687/f2dd958c-855e-11e6-9b23-7c23360755d3.png)
4. rename `function greeter(person: Person) {` to `function greeter(person: Person1) {`
5. revert rename
6. delete all code and save
7. got error below  
  ![image2](https://cloud.githubusercontent.com/assets/227713/18897681/eb980686-855e-11e6-8182-3b247a90bf7b.png)

**Comment by atian25** [comment]
update: when reopen the file, all warning is gone...

![image](https://cloud.githubusercontent.com/assets/227713/18897939/e8c17094-8560-11e6-9e6b-16b40f7aaf3c.png)

**Comment by waderyan** [comment]
I am not able to reproduce this. Can you try again with the latest build? You can install the latest build at http://code.visualstudio.com/insiders

**Comment by atian25** [comment]
sorry, I can't either now, will reopen if hit again
