### ISSUE TITLE
Support file extension icons for ThemeIcon.

### ISSUE THREAD

**Issue by zaycev** [microsoft/vscode#128507]
Hello!

We are building an extension that visualizes some data for workspace files in our view using a class derived from `TreeDataProvider`. We wonder if there is a way to use file icons set by the current File Icons Theme for our custom tree items. Base icon class has a field `icon: ThemeIcon` which supports product icons. Wonder if something similar exists for referring to file-type icons?

Related question on StackOverflow: https://stackoverflow.com/questions/68353825/vscode-extension-api-file-type-extension-icons-using-themeicon

**Comment by usernamehw** [comment]
```ts
this.iconPath = ThemeIcon.File;
this.resourceUri = Uri.parse('_.js');
```

**Comment by zaycev** [comment]
> ```ts
> this.iconPath = ThemeIcon.File;
> this.resourceUri = Uri.parse('_.js');
> ```

Perfect! Thank you so much.
