### ISSUE TITLE
Searching the extension marketplace fails with CORS error

### ISSUE THREAD

**Issue by Aleuck** [microsoft/vscode#128583]
Does this issue occur when all extensions are disabled?: Yes (there are no extensions installed, but I tried with --disable-extensions anyway)

- VS Code Version:
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.14
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.12.15-arch1-1
```

Steps to Reproduce:

1. Open VSCode
2. Search for extension
3. ![image](https://user-images.githubusercontent.com/578126/125531136-f233f270-503f-43b3-9b2a-fd34460a88bc.png)

Dev Tools' Network tab output:
![image](https://user-images.githubusercontent.com/578126/125531238-65f591d6-a568-4b07-9803-5c96a5010715.png)

More request's details:
![image](https://user-images.githubusercontent.com/578126/125531364-b8cb3c4f-0dd0-4d25-a5e9-29e303c3479b.png)

Copying the request to cURL and pasting on a terminal works (I get a response).
There is no proxy in my network.

**Comment by gjsjohnmurray** [comment]
Looks like you have installed VS Code from a source that redirects it to open-vsx.org instead of the Microsoft Marketplace.

**Comment by joaomoreno** [comment]
... which is unsupported by us.

**Comment by Busata** [comment]
since google leads you here -> https://github.com/eclipse/openvsx/issues/306

**Comment by armujahid** [comment]
Temporary solution: https://github.com/VSCodium/vscodium/issues/746#issuecomment-881049046
Also referred at https://forum.manjaro.org/t/unable-to-download-extensions-in-code/74397/5?u=armujahid

**Comment by jestarray** [comment]
For arch linux users:
`yay -S code-marketplace` from the AUR to fix

**Comment by dbrgn** [comment]
As another workaround, if you already know which plugin to install (i.e. after searching for it at https://open-vsx.org/), you can install the plugin via command line. For example, to install [rust-analyzer](https://open-vsx.org/extension/matklad/rust-analyzer):

    $ code --install-extension matklad.rust-analyzer

**Comment by dniku** [comment]
I'll make this issue easier to find:

If you are using VSCode on Arch / Manjaro and search in the Extensions Marketplace fails with "We cannot connect to the Extensions Marketplace at this time, please try again later.", press `Ctrl+Shift+I`, open the "Console" tab and make sure that the following errors are there:

```
> Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> Error querying extensions gallery XHR failed    extensionsViews.ts:323
query @ extensionsViews.ts:323
> Failed to load resource: net::ERR_FAILED    open-vsx.org/vscode/gallery/extensionquery:1
```

If so, you are affected by this problem. You will need to install `code-marketplace` or `visual-studio-code-bin` (if you want to switch to the release from Microsoft) to fix this problem.

**Comment by armujahid** [comment]
@dniku Better solution for Manjaro is mentioned at https://forum.manjaro.org/t/unable-to-download-extensions-in-code/74397/5?u=armujahid

**Comment by Mhamza007** [comment]
> For arch linux users:
> `yay -S code-marketplace` from the AUR to fix

Worked on Garuda Linux

**Comment by feitian124** [comment]
same error for manjaro, try use visual-studio-code-bin
