### ISSUE TITLE
Terminal lauching empty

### ISSUE THREAD

**Issue by Lorena1908** [microsoft/vscode#128568]
Issue Type: <b>Bug</b>

When I run a python file, kill the terminal and run it again, the terminal that pops out is empty (with nothing written on it) and I can't kill it. The terminal only go back to normal when I close it using the x in the top right hand corner and open it again using the ctrl-' command. Although doing this makes it go back to normal, if I kill the terminal it'll happen again. 

I think this started to happen because of the latest update, but I don't know to to downgrade 

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.08GB free)|
|Process Argv|--crash-reporter-id 1780c1d7-6442-434d-9169-4ceccb98e265|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
python|ms-|2021.6.944021595
printcode|nob|3.0.0
material-icon-theme|PKi|4.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by Bad-At-Naming** [comment]
Same issue present on macOS Big Sur version 11.4 (20F71). Vscode version 1.58.1

**Comment by meganrogge** [comment]
You can downgrade by uninstalling vscode and re-installing a diff't version, for example https://code.visualstudio.com/updates/v1_57

This will be fixed in the recovery build released next week. another manifestation of #128255
