### ISSUE TITLE
Auto import option to make imports relative only within current directory

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode#128504]
At my workplace, our least favourite relative imports are the ones that venture out of the current directory (i.e. they begin with any number of `../`). But there are times where we want relative imports within the current directory (i.e. beginning with `./`). I don't see any existing options that support this exact style of import, including `project-relative`.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
