### ISSUE TITLE
Opening search editor with a query doesn't always initiate search

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#128554]
1. Go to preferences
2. Click Telemetry settings
3. 🐛 If you haven't opened the settings editor before it doesn't search. Subsequent triggerings of the action works

Here's the line of code in question `accessor.get(IPreferencesService).openSettings(false, '@tag:telemetry');`

**Comment by roblourens** [comment]
I guess https://github.com/microsoft/vscode/issues/128160 was filed already
