### ISSUE TITLE
WorkspaceConfiguration update api throwing unexpected error

### ISSUE THREAD

**Issue by FredCoen** [microsoft/vscode#128531]
The vs code WorkspaceConfiguration update api states:

throws - error while updating
  - configuration which is not registered.
  - window configuration to workspace folder
 -  configuration to workspace or workspace folder when no workspace is opened.
  - configuration to workspace folder when there is no workspace folder settings.
 -  configuration to workspace folder when WorkspaceConfiguration is not scoped to a resource.

However, when calling the api we get the following error that does not seem to be related to any of these points:
``
Error: Unable to write into user settings because the content of the file is newer.
    at v.reject (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:15315)
    at v.doWriteConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:12706)
``

- VS Code Version: Visual Studio Code (1.57.1)
- OS Version: Darwin

Steps to Reproduce:

1. Haven't figured out a consistent pattern to reproduce yet

**Comment by sandy081** [comment]
It seems the configuration file has got changed (may be by user) while updating, to prevent race conditions we abort the operation.
