### ISSUE TITLE
Vietnamese keyboard app does not work on markdown document

### ISSUE THREAD

**Issue by ddddmz** [microsoft/vscode#128513]
Issue Type: <b>Bug</b>

Vietnamese keyboard app (most popular): UniKey
download URL: https://www.unikey.org/download.html
Steps to reproduce:
1. Open markdown file (*.md)
2. Run Unikey
3. In Unikey: turn on Vietnamese mode; select Character set: Unicode; select Input method: Telex
4. Type vietnamese in markdown document, vietnamese characters do not show up

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (0.93GB free)|
|Process Argv|--crash-reporter-id d157bb12-e172-460b-a8e9-9ada03a41c12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.6.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
python-extension-pack|don|1.6.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
code-runner|for|0.11.5
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.28.0
rest-client|hum|0.24.5
openvpn|idl|0.2.3
reg|ion|1.0.3
vscode-edit-csv|jan|0.6.0
csharpextensions|jch|1.3.1
MagicPython|mag|1.1.0
syntax-project-pbxproj|mar|0.1.3
rainbow-csv|mec|1.9.1
csharp|ms-|1.23.12
mssql|ms-|1.10.1
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.8.0
quicktype|qui|12.0.46
java|red|0.80.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
pdf|tom|1.1.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
jinja|who|0.0.8
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, does this open happen for markdown files or are other language also effected?
