### ISSUE TITLE
macOS pwsh not showing in default terminal profile list or new terminal list

### ISSUE THREAD

**Issue by Mercbot7** [microsoft/vscode#128564]
Issue Type: <b>Bug</b>

When selecting menu to add a new terminal the only profiles/terminals listed are zsh and bash. 
If I select "Select Default Profile" the list of profiles/terminals does not include pwsh(Powershell).

![Screen Shot 2021-07-13 at 1 56 59 PM](https://user-images.githubusercontent.com/42525173/125503528-04f9665e-7785-4294-896b-2b3127862a91.png)

![Screen Shot 2021-07-13 at 2 12 33 PM](https://user-images.githubusercontent.com/42525173/125503832-a5fbb017-b417-40f7-b28b-8be9b8ce3328.png)

I expect to see Powershell listed in the new terminal dropdown.
I expect to see Powershell listed in the default profiles dropdown.

Powershell has been installed using Homebrew using the standard method.

If I open a .ps1 file an Integrated Powershell Console will be opened. 

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (3.21GB free)|
|Process Argv|--crash-reporter-id 3b79998c-1229-4c1d-aecf-9aa62998845e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.10.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
gitlab-workflow|Git|3.26.0
go|gol|0.26.0
jsonnet|hep|0.1.0
vscode-docker|ms-|1.14.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
powershell|ms-|2021.6.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
markdown-preview-enhanced|shd|0.5.22
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by keawade** [comment]
I'm seeing this with `fish` as well on osx since updating vscode today.

I was able to workaround it for the moment by using setting `terminal.integrated.shell.osx` to point to my `fish` executable but that setting has been deprecated and I doubt it'll stick around indefinitely for my workaround use.

**Comment by Mercbot7** [comment]
@keawade Yeah, I at one point had configured profiles to get pwsh terminals but am frustrated with that and it seems from the docs I have read that VSCode _should_ be detecting Powershell. I do not like statically configuring what should be dynamically/automatically configured.

**Comment by Mercbot7** [comment]
Also, as a note, when I check the system shells I get:

```shell
cat /etc/shells 
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/pwsh
/usr/local/bin/bash

```

**Comment by keawade** [comment]
Oh interesting note on the contents of `/etc/shells`. I was assuming that vscode was reading that to get its list of allowed shells. I don't have sudo access on my machine (work) to update my system shells which is why I was originally using the setting `"terminal.integrated.defaultProfile.osx": "fish"` to work around that limitation until this last update broke that.

**Comment by Mercbot7** [comment]
I have not been able to find(nor have I done extensive discovery) on how exactly they are searching for standard shells. It would be nice to see the code where that occurs and maybe I just need to dig more.

**Comment by Tyriar** [comment]
We pull form `/etc/shells` and then validate that they exist in this file: /Users/daimms/dev/Microsoft/vscode/src/vs/platform/terminal/node/terminalProfiles.ts

I've notified some weirdness as well, I see this in Insiders:

<img width="321" alt="Screen Shot 2021-07-23 at 1 42 33 PM" src="https://user-images.githubusercontent.com/2193314/126839393-fe44bc8e-7daf-4817-a303-250e6ce06dd5.png">

And this out of sources:

<img width="314" alt="Screen Shot 2021-07-23 at 1 41 53 PM" src="https://user-images.githubusercontent.com/2193314/126839327-3c9f2e7d-d340-4e72-aa0b-7bc2076ed9e0.png">

**Comment by Tyriar** [comment]
Shared proc log in Insiders:

<img width="304" alt="Screen Shot 2021-07-23 at 1 44 15 PM" src="https://user-images.githubusercontent.com/2193314/126839550-9b20f1ad-4dbb-428b-86d8-509e51fdf599.png">

**Comment by Tyriar** [comment]
I see it in Insiders when launched via the dock, not if opened from the terminal. So the issue is probably the environment that's getting used here https://github.com/Microsoft/vscode/blob/9199916f5b728d31e9eb3547a21ec44048ce7e95/src/vs/platform/terminal/node/terminalProfiles.ts#L339-L340

**Comment by idl0r** [comment]
```
[2021-07-24 11:56:24.933] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.new
[2021-07-24 11:56:24.933] [renderer1] [trace] terminalInstance#ctor (instanceId: 1) {"from":"menu","target":"view"}
[2021-07-24 11:56:25.138] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/idl0r/.config/Code/logs/20210724T115346/telemetry.log
[2021-07-24 11:56:25.144] [renderer1] [debug] Terminal process exit (instanceId: 1) with code undefined
[2021-07-24 11:56:25.144] [renderer1] [debug] Terminal process exit (instanceId: 1) state 2
[2021-07-24 11:56:25.144] [renderer1] [trace] terminalInstance#dispose (instanceId: 1)
```

VSCode also spams ```[2021-07-24 11:57:35.381] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/idl0r/.config/Code/logs/20210724T115346/renderer1.log``` like several hundret thousand times which makes it really hard to keep open and follow within vscode itself.


Anyway, that's from the console output, which doesn't look to helpful to me:
```
console.ts:137 [IPC Library: Pty Host] TRACE persistentTerminalProcess#ctor 2 {0: 2, 1: {…}, 2: "f68ae75c90f7d0c9e3a71f3879ac1688", 3: "xls-to-mysql", 4: true, 5: 276, 6: 13, 7: {…}, 8: "[Circular]", 9: "[Circular]"}0: 21: {_store: {…}, _shellLaunchConfig: {…}, _executableEnv: {…}, _logService: {…}, id: 0, …}2: "f68ae75c90f7d0c9e3a71f3879ac1688"3: "xls-to-mysql"4: true5: 2766: 137: {GraceTime: 60000, ShortGraceTime: 6000}8: "[Circular]"9: "[Circular]"__proto__: Object
console.ts:137 [IPC Library: Pty Host] TRACE ptyService#start 2
console.ts:137 [IPC Library: Pty Host] TRACE persistentTerminalProcess#start 2 false
log.ts:272 TRACE profile not validated fish ["fish"]
console.ts:137 [IPC Library: Pty Host] TRACE ptyService#shutDown 2 false
log.ts:272 TRACE profile not validated pwsh ["pwsh"]
log.ts:272 TRACE profile not validated fish ["fish"]
log.ts:272 TRACE profile not validated pwsh ["pwsh"]
```

**Comment by Tyriar** [comment]
This is fixed for me, marking as verified since it's working for both @meganrogge and I
