### ISSUE TITLE
Can't edit with VSCode

### ISSUE THREAD

**Issue by YSHIDM** [Microsoft/vscode#12857]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.Backspace键不能删除只是左移光标
2.回车键只能换行

**Comment by octref** [comment]
Please use English for reporting issues. Thanks.

As for the issue, do you have Vim extension installed?

**Comment by octref** [comment]
Translation:

Steps to Reproduce:

1. Backspace key only moves cursor to left, not deleting anything.
2. Enter key only goes to next line.

**Comment by joaomoreno** [comment]
Does it reproduce with `--disable-extensions`?

**Comment by octref** [comment]
Closing as this is exactly Vim behavior.

If this isn't the cause feel free to reopen.
