### ISSUE TITLE
VS Code freezes when loading big file

### ISSUE THREAD

**Issue by zh-wowtv** [Microsoft/vscode#12855]
- VSCode Version: 1.5.3
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open the attached file.
2. Scroll

The VS Code will freeze and got "Not responding" error message.

[ckeditor.js.zip](https://github.com/Microsoft/vscode/files/496972/ckeditor.js.zip)

**Comment by alexandrudima** [comment]
For 1.7.x we have updated our JavaScript grammar. The new grammar does not cause any freeze for me.
