### ISSUE TITLE
Code OSS Freezes After Some Time When Debugging From VS Code Insiders

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128542]
The renderer process is still alive.

![image](https://user-images.githubusercontent.com/2931520/125466295-930536dc-537d-43db-904b-8cb43d20ef0f.png)

Please give me instructions how I can debug this.

**Comment by hediet** [comment]
@deepak1556 this still happens almost daily :(

**Comment by deepak1556** [comment]
Sorry for the delay on this, can you follow the steps below to capture process dump.

1) Download `etwpackage1.56` from https://github.com/google/UIforETW/releases/tag/v1.56
2) Extract and run `UIforETW` from the `bin` folder
3) Click `settings` in the `UIforETW` application and ensure the following configuration is checked
<img width="600" alt="Screen Shot 2021-11-24 at 23 38 08" src="https://user-images.githubusercontent.com/964386/143259101-f49f06ec-9ffd-45b2-8b87-fc104be56681.png">
4) Ignore the Heap profiled processes section in the above box and leave it blank
5) Close the settings window
6) Ensure the main application window for `UIforETW` has the following options checked in
<img width="846" alt="Screen Shot 2021-11-24 at 23 50 31" src="https://user-images.githubusercontent.com/964386/143260548-24e35c68-b838-4d00-81a7-cc433a091f5e.png">
7) Click `Start Tracing`
8) Open Code OSS for debugging with your usual steps only thing is once the debugging has started take a screenshot of `Help > Process Explorer` page in the OSS application.
9) Once the freeze happens, click `Stop Tracing` in the `UIforETW` application after a few seconds
10) The application will output path to the save `.etl` file on disk
11) Send this file to `Deepak.Mohan@microsoft.com` along with the process explorer screenshot.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/164443
