### ISSUE TITLE
Indentation is broken when using parenthesized JSX expressions

### ISSUE THREAD

**Issue by mgoldenbe** [microsoft/vscode#128537]
- VS Code Version: 1.58.0
- OS Version: Windows 10 Pro Build 19041
 
Steps to Reproduce:

Here is a small React component:

```
const MyComponent = () => {
    return (        
        <div className = "my-class">        
        </div>
        )
    }
    
    export default MyComponent;
```

Note how the last closing curly bracket, as well as the last line beginning with `export` are wrongly indented. If the line return is removed after the opening parenthesis after `return`, the indentation becomes correct.

**Comment by mjbvz** [comment]
Works fine for me. 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
