### ISSUE TITLE
Font sizes / styles of IntelliSense tool tips are disconcerting?

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12851]
Testing https://github.com/Microsoft/vscode/issues/12598

I've been staring at this for far too long... but is it just me, or is the font size of the tooltip larger than the font in the editor? Whatever it is, there is something very disconcerting about the relative font sizes here to me - it looks like 3 separate font sizes, and two font styles (more if you count the tabs), and... I still haven't even come to terms with whether the dress is blue or gold... so this is just too much for me. :wink: 

![image](https://cloud.githubusercontent.com/assets/762848/18897016/632f179a-84db-11e6-8aed-bb7f37a973c1.png)

**Comment by joaomoreno** [comment]
The font size is the same but the line height appears bigger, due to the widget padding. I'm also not entirely happy about it but I'll let it go for a while longer, at least an iteration, see if we get more user feedback on it.

It's black and blue, though.
