### ISSUE TITLE
Add flag to DebugSessionOptions to trigger simple mode on debug session

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#128588]
We can add a flag to DebugSessionOptions to activate the mode described in #128582. Example:

```
debugUI: {
  minimalUI: boolean;
}
```

**Comment by isidorn** [comment]
I think this is tackled via https://github.com/microsoft/vscode/pull/128801
And I think this is already covered by a test plan because of https://github.com/microsoft/vscode/issues/128582
@roblourens If not, please add a verified-needed flag. Thanks
