### ISSUE TITLE
(bug) Handle at-sign in code block of doc comments.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#128543]
Ref. #118977 Please see this issue. It's not fixed. It is marked as duplicate of https://github.com/microsoft/TypeScript/issues/38922. And should have been fixed by https://github.com/microsoft/TypeScript/pull/42364. But it is not fixed. Or am I missing something?

```ts
/**
 * The best decorator ever made.
 * 
 * @todo Fix the "@" bug in code block.
 * 
 * @example
 *
 * ```ts
 * class MyComponent {
 *   @SomeDecorator() myValue = 42; // <- This is the problem line.
 * }
 * ```
 */

 export function SomeDecorator() {}

```

![image](https://user-images.githubusercontent.com/60390085/125473274-4098f6c7-05ba-4a0f-8e89-403f1af1f802.png)

The parser detects the at-sign as doc comment tag. But it's a part of the code. So we should ignore the code block.

```text
Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

Workaround. Avoid `@` sign. For example: 

![image](https://user-images.githubusercontent.com/60390085/125474180-e094f46f-fe83-4845-bf4f-38e25d5daec1.png)

But this sucks. But you see what format is expected.

**Comment by infacto** [comment]
Workaround. Avoid `@` sign. For example: 

![image](https://user-images.githubusercontent.com/60390085/125474180-e094f46f-fe83-4845-bf4f-38e25d5daec1.png)

But this sucks.

**Comment by infacto** [comment]
Sorry, I missed that it is the TypeScript repo. Should I move to this repo? I just wonder why this is not yet working. Is something to do in the vscode repo?

**Comment by mjbvz** [comment]
Yes please open an issue against TS if this is still not working as expected
