### ISSUE TITLE
ts/js IntelliSense is not work when  using code completion

### ISSUE THREAD

**Issue by GiveMe-A-Name** [microsoft/vscode#128547]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.0
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Use code completion like snippets to import 'react'
2. the IntelliSense will be invalidated
3. It will only take effect if I key another place.
![bug](https://user-images.githubusercontent.com/58852732/125482601-bc452c02-8131-4f91-b90b-3e98bc860db0.gif)

I guess it's because VS Code didn't enable IntelliSense when it was using code completion.  Only when it is editing will this feature be enabled.

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`. By default snippets disable suggestions as you type

**Comment by GiveMe-A-Name** [comment]
> Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`. By default snippets disable suggestions as you type

thank you for your suggestion, It is work. 
but I have a doubt why default snippets disable suggestion when I type. Is this for performance reasons or user experience?
In fact, I'm a vscode extension developer，Our team is currently working on an extension for code completion, I've think that if it disable suggestion while the user is using the code completion reduces the user experience
