### ISSUE TITLE
Module exports should appear in completion list as functions, not properties

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12852]
Testing https://github.com/Microsoft/vscode/issues/12598

![image](https://cloud.githubusercontent.com/assets/762848/18897314/156ae270-84de-11e6-857a-10a7cc687dca.png)

**Comment by dbaeumer** [comment]
@waderyan very like we receive property from the tsserver in this case.

**Comment by waderyan** [comment]
Repro'd

![image](https://cloud.githubusercontent.com/assets/2449568/18931464/28da5586-8581-11e6-8b6b-e2006d175a46.png)

Moving to TS

**Comment by waderyan** [comment]
https://github.com/Microsoft/TypeScript/issues/11219
