### ISSUE TITLE
custom "terminal.integrated.defaultProfile.windows" is breaking VSCode on start

### ISSUE THREAD

**Issue by 55f** [microsoft/vscode#128598]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:
Version: 1.58.1
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-13T06:58:28.115Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. basic shell settings,  kept defaults, and added busybox line: 
```json
"terminal.integrated.profiles.windows":{
  "PowerShell":{"source":"PowerShell","icon":"terminal-powershell"},"CommandPrompt":{"path":["${env:windir}\\Sysnative\\cmd.exe","${env:windir}\\System32\\cmd.exe"],"args":[],"icon":"terminal-cmd"},"GitBash":{"source":"Git Bash"},
  "busybox":{ "path":"C:/mingit-busybox/current/mingw64/bin/busybox.exe", "args": ["bash","-i"], "env": {"ENV":"$HOME/.profile"} }
},
"terminal.integrated.defaultProfile.windows": null
```
2. start _code --disable-extensions_
3. runs absolutely normally
4. in Terminal window, Launch Profile _busybox_ 
5. still runs absolutely normally
6. alt+f4
7. change setting to `"terminal.integrated.defaultProfile.windows": "busybox"`
8. launch _code --disable-extensions_
9. wtf is this please ❓ 🤣 (menus keep closing, (output) windows/editor get focused) ![final_60ee3b72e6a2b900f4df72e6_455682](https://user-images.githubusercontent.com/16976424/125546114-11eda671-5db1-4b2c-bb64-fd70505d44a6.gif)
10. some tries, I get that warning, sometimes not 🤷 

### sooo
I suspect this happens when the shell for the Terminal gets pre-loaded (??) in a background process before being visible??
since this erroneous behavior does not occur when the "terminal.integrated.defaultProfile.windows" is not set to the alternative shell and that one is launched from the Terminal window itself.

Could you please elaborate on that?

iirc this started to happen recently with Version: 1.57+ 
(<=1.56 all was fine, so I guess heavy internal changes?)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
