### ISSUE TITLE
SQL DB Connection

### ISSUE THREAD

**Issue by LeonCrafts** [microsoft/vscode#128572]
If you would implement your own SQL DB Connection Function to the most common SQL Softwares, that would solve the never ending extentsion issuses and bugs that occur with the current ones that are available.
I believe this function would make a lot of web-devopers from beginner-junior-senior very happy.

BR

**Comment by kieferrm** [comment]
I hear you about the issues with the existing extension, but we won't provide this functionality out of the box.
