### ISSUE TITLE
Rendering of fenced code blocks in Hover assumes current language

### ISSUE THREAD

**Issue by findleyr** [microsoft/vscode#128560]
- VS Code Version: 1.58.0
- ~Debian Testing

Context: golang/vscode-go#1614

When formatting a [fenced code block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) in a hover, VS Code assumes the syntax of the underlying file.

For example, if I am editing a Go file and the hover markdown is the following:

````
```
for example
```
````

VS Code will render
```go
for example
```

rather than
```
for example
```

We can work around this by specifying a non-existent language (e.g. ```none), but IMO VS Code should not make such an assumption: if the extension wants to display a particular language's syntax, it can specify a language.

**Comment by jrieken** [comment]
We have done that on purpose and it is too late to change this behaviour after so many years

**Comment by findleyr** [comment]
@jrieken ACK, thanks for confirming.

We'll work around it.
