### ISSUE TITLE
Native Notebooks - Not Saving

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#128585]
We have had a number of survey monkey responses come in mentioning notebooks aren't saving properly. We haven't really had a repro up until maybe this? Is anyone able to reproduce doing the following? Is it possible the interaction between the Jupyter extension and VIM extension could cause a result like this? 

![image](https://user-images.githubusercontent.com/19276747/125532478-e25cf0af-5ef3-49bd-95a2-bbbe9e50305f.png)

**Comment by claudiaregio** [comment]
A potential repro? 

1. Create VS Code instance (A) and have a notebook open
2. Create another VS Code instance (B) in new folder/directory
3. Drag and drop the notebook from A to B
4. Make code change -> notebook is marked as dirty
4. In B, hit Ctrl+S or File -> Save 
5. The file is not added to the File Explorer
6. Hit Save As... in B -> The file explorer directory defaults to the path of directory A. (This looks like a bug?) 

If a user is working with multiple instances of VS Code and they drag and drop a notebook file, they may expect that when they go to save the notebook it is in the directory/path of the instance they are working in, not the directory/path the notebook originated from. 

This may be why from the user perspective it appears that notebooks are not being saved at all 
![image](https://user-images.githubusercontent.com/19276747/125536544-2608df01-5366-471d-813c-e1591e560802.png)

**Comment by rebornix** [comment]
This is how VS Code (and other editors like Sublime, Atom, etc) works for all types of files.
