### ISSUE TITLE
Abbreviated runtimeVersion in launch.json not working

### ISSUE THREAD

**Issue by wongjn** [microsoft/vscode#128506]
Issue Type: <b>Bug</b>

```
$ nvm list
        v8.17.0
       v10.22.0
->     v12.22.1
       v14.17.0
        v16.3.0
…
```
launch.json:
```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Jest",
      "program": "${workspaceRoot}/node_modules/.bin/jest",
      "args": ["--color"],
      "outputCapture": "std",
      "runtimeVersion": "16"
    }
  ]
}
```
Running this debug task fails with "Node.js version '16' cannot be found for 'nvm'":
![Unexpected error message](https://user-images.githubusercontent.com/11310624/125355192-a0d8ef00-e35c-11eb-8f15-2a3ee5bfb12c.png)

However, if the value of `runtimeVersion` to a specific version I have installed (`"runtimeVersion": "16.3.0"` in this case), the debug task runs as expected.

I believe this is a bug since the [Multi version support section of Node.js debugging documentation](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_multi-version-support) states that:
> If you omit the minor and patch version and have, for example, `"runtimeVersion": "14"`, then the most recent `14.x.y` version installed on your system will be used.

So my understanding here is that `16.3.0` should be used in this setup and should not error.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.09GB free)|
|Process Argv|--crash-reporter-id 62e8c2a1-a04c-4909-a237-849e0701279d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|5.80GB (3.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|Memory (System)|5.80GB (3.31GB free)|
|VM|0%|
</details>

**Comment by connor4312** [comment]
You'll need to set your launch type to `pwa-node` for this to work. The old `node` type is redirected through the previous debugger, but only after it tries (and failed) to resolve that version number. This'll no longer be necessary when the old debugger (eventually) goes away entirely.

**Comment by connor4312** [comment]
Oh, yea, I see we recommend that in our docs. That needs to be updated.

**Comment by connor4312** [comment]
The old debuggers are being removed next month, so I will just assign this to that iteration since it'll be fixed at that point.

**Comment by connor4312** [comment]
Fixed with https://github.com/microsoft/vscode-js-debug/issues/1065
