### ISSUE TITLE
Code OSS Often Crashes When Starting Debugging

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128540]
When hitting F5 in Code Insiders, Code OSS often crashes.

![image](https://user-images.githubusercontent.com/2931520/125463483-98304d10-a9c2-49e1-964d-7d1ed9210866.png)

I sent @deepak1556 a crash dump.

Maybe this is related to #128334, idk.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/122225
