### ISSUE TITLE
Nextline automatically when writing a markdown code

### ISSUE THREAD

**Issue by panmingyang2009** [Microsoft/vscode#12858]
- VSCode Version:1.5.2
- OS Version: macOS 10.12

Steps to Reproduce:

0. Switch to markdown editor.
1. Writing a line that is much **longer** than the window.
2. It just keep **increasing** the length of the line, instead of switch to a **new line**.

> It's very **difficult** to read in this case. Otherwise, VS is a pretty good editor for markdown.

**Comment by mjbvz** [comment]
It sounds like you don't actually want newlines inserted into the text, but want the line to be visually wrapped if it is longer than the window.

To enable wrapping for the current document, use the "Toggle Word Wrap" command (also found under `View`). To enable wrapping by default, add `"editor.wordWrap": true` to your user or workspace settings.

Please give that a try and let me know if that is what you are after. Thanks.

**Comment by panmingyang2009** [comment]
Thank you very much for your detailed reply!

 I've try it. It's actually what I need! I've already fall in love with the markdown editor of VSCode.

I'm sorry about replying so late. I was on holiday.😋

**Appreciate again.**
