### ISSUE TITLE
blank page on opening vs code 

### ISSUE THREAD

**Issue by myr978** [microsoft/vscode#128520]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.58
- OS Version:windows 10

1.when started updating the vs code this issue of black page is appearing 
2.even by adding --disable-gpu in properties does'nt work
3.by uninstalling and installing it again also it is'nt working

**Comment by mmahdigh** [comment]
I had the same issue. 
Update it to 1.58.1. it fixed it for me.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/128725
