### ISSUE TITLE
Changing Tabs with Ctrl + Page Up/Down not working for Terminals in Editor Area.

### ISSUE THREAD

**Issue by sandeshgit** [microsoft/vscode#128503]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58
- OS Version: Found in Ubuntu but the issue is not OS-specific.

Steps to Reproduce:

1. Open at least one file.
2. Open Terminal in Editor Area.
3. While in the Terminal (in Editor Area), Press **Ctrl + Page Up** or **Ctrl + Page Down**.
 
The expected behavior: The Tab switches/changes to the Next or Previous Tab.

What we get: A new terminal at the bottom.

![Screenshot from 2021-07-13 01-12-08](https://user-images.githubusercontent.com/1939148/125346544-9bd66880-e379-11eb-8f54-eec473cf0d1a.png)

Anyways, thanks to the community for adding this awesome feature(Terminal in Editor Area). 
I am not sure if the issue I faced is actually a bug or if it is supposed to work like this. But this definitely feels odd because we are used to using the Ctrl + Page Up/Down for switching between the Tabs.

**Comment by adamurban98** [comment]
Same issue for me

**Comment by Tyriar** [comment]
This does feel a little weird, it will open the terminal because of these keybindings:

```
{ "key": "ctrl+pageup",           "command": "workbench.action.terminal.focusPrevious",
                                     "when": "terminalFocus && terminalProcessSupported" },
{ "key": "ctrl+pagedown",         "command": "workbench.action.terminal.focusNext",
                                     "when": "terminalFocus && terminalProcessSupported" },
```

Should probably disable them when the editor is focused.

**Comment by sandeshgit** [comment]
> This does feel a little weird, it will open the terminal because of these keybindings:
> 
> ```
> { "key": "ctrl+pageup",           "command": "workbench.action.terminal.focusPrevious",
>                                      "when": "terminalFocus && terminalProcessSupported" },
> { "key": "ctrl+pagedown",         "command": "workbench.action.terminal.focusNext",
>                                      "when": "terminalFocus && terminalProcessSupported" },
> ```
> 
> Should probably disable them when the editor is focused.

Thank you @Tyriar  for the response.

A possible solution I was thinking of is to add a new `When Clause Context` which determines if the active terminal is on the regular place(bottom) or on Editor Area. However, I could not find the correct `When Clause Context`.

Suppose, the When Context available here is `terminalAtEditorArea`. Then we could modify the when clause as:

``` json
    "when": "terminalFocus && terminalProcessSupported && !terminalAtEditorArea"
```
This would make sure to disable the default terminal's **ctrl+pagedown** command for this particular situation.
If some `When Context` like this exists, please let me know.

**Comment by sandeshgit** [comment]
If anyone is ready to give up the regular **Integrated Terminal**'s _Ctrl+PageUp/Down_ shortcuts in favor of the **Terminal In Editor Area**, you can do the following as a temporary fix to this issue.

1. Open Command Pallete with _Ctrl + Shift + P._
2. Type Open Keyboard Shortcuts (JSON).
3. Keybindings.json file will open.
4. Paste/Append the following to it:

``` json
[
  {
    "key": "ctrl+pageup",
    "command": "-workbench.action.terminal.focusPrevious",
    "when": "terminalFocus && terminalProcessSupported"
  },
  {
    "key": "ctrl+pagedown",
    "command": "-workbench.action.terminal.focusNext",
    "when": "terminalFocus && terminalProcessSupported"
  }
]
```
5. Save the file.
