### ISSUE TITLE
terminal blank

### ISSUE THREAD

**Issue by harsh1chaudhary** [microsoft/vscode#128515]
Issue Type: <b>Bug</b>

When i run the code sometime terminal go blank  and terminal killing option also not work

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.02GB free)|
|Process Argv|--crash-reporter-id 0f746359-3989-47b5-b085-ef566003a07d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by david-waterworth** [comment]
This is happening to me as well, after using vscode for some time, my terminal stops rendering. It still appears to be accepting input. You can see in the image below the cursor is still displayed. Hitting Ctrl-C sometimes "fixes" it. This seems to have occurred recently, probably upgrade to 1.57.1 (I'm using Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/5028974/125399424-edbbd480-e3f3-11eb-947c-d0fb86de5ae4.png)

**Comment by ChansonLeung** [comment]
It happening to me as well, the problem of blank seems to be fixed when the terminal size changed such as click the "Explorer"button or maximized the windows

**Comment by ChansonLeung** [comment]
It happening to me as well, the problem of blank seems to be fixed when the terminal size changed such as click the "Explorer"button or maximized the windows

**Comment by dominicdongwuxing** [comment]
I have a similar issue: when I open visual studio code, the integrated terminal is blank and I am not able to type anything or to use it. However, I can kill the terminal and open it over and over again, although it still cannot be used. Reopening visual studio code also doesn't help. My VS code version is 1.44.2, my OS version is Fedora 33 (Workstation Edition) and my linux kernel version is 5.10.16-200.fc33.x86_64.

**Comment by david-waterworth** [comment]
@meganrogge are you sure this is a duplicate? #128264 refers to the lack of focus of the terminal. What we're seeing is different - the window goes blank periodically? Focusing the terminal doesn't help

**Comment by dominicdongwuxing** [comment]
> /duplicate #128264
@meganrogge actually the #128264 issue is different from this one. For example, in my case, I can kill the integrated terminal at any time but I cannot focus on the terminal or type commands.
