### ISSUE TITLE
Explore improving end-to-end experience of opening your first Jupyter notebook

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#128592]
This issue covers the explorations to improve the end-to-end experience of opening a notebook for the first time.

## Creating a new blank notebook

In this scenario, the user has not installed any extensions and attempts to create a new notebook file. Some proposed suggestions are:

- Add Jupyter notebook support out of the box (creating and running notebooks)
- Contribute to the "New File..." API and show a notebook entry
- Display a "Select a kernel and language to get started", similar to our untitled file experience ([refs](https://github.com/microsoft/vscode/issues/114307#issuecomment-823325581))
- Include a "Find More Kernels" option in the Kernel quick pick that goes to the marketplace
- Also include a "Find more languages" option that goes to the marketplace
- If a user selects a kernel and there is an associate language (i.e. Python) then the cell is auto-selected to that preferred language
- If a user selects a language that has an associated kernel, then auto-select that kernel if there is one
- If there is more than one kernel, prompt the user to select a kernel
- Cache the user selection for the next time they create a new notebook or cell
- Hide any actions in the toolbar that relate to the kernel when a cell hasn't ran yet

https://user-images.githubusercontent.com/35271042/125537626-247a40c8-664c-4a57-a154-ff9e9deb6bcb.mp4

## Opening a notebook
TBD

**Comment by rchiodo** [comment]
What can we do to support async operations in the quick pick? Not sure if this would require an API change or not (as @misolori mentioned internally we could add a 'loading' notebook controller) but could we add other UI affordances when 'loading' is still going on?

**Comment by misolori** [comment]
@rchiodo so currently we show the following whenever we are waiting for async operations that take a while:

<img width="650" alt="CleanShot 2021-07-13 at 17 09 30@2x" src="https://user-images.githubusercontent.com/35271042/125540730-1a6c67a8-79b5-4e60-9984-477bbb8c11dd.png">

https://user-images.githubusercontent.com/35271042/125541164-7fe58744-9f59-4694-921a-6378dacf5c08.mp4

I wonder if we're able to follow the same pattern of updating the input placeholder with the "Loading kernels" text and then updating the rest when it's all complete? We use the same mechanism for Codespaces, Cloning repos, etc. so it's a common pattern.

**Comment by rchiodo** [comment]
That sounds great. I think the API for retrieving controllers would have to change to support that though? I don't believe there's any way for an extension to say - still loading?

/cc @jrieken @mattbierner @DonJayamanne @IanMatthewHuff

**Comment by jrieken** [comment]
> think the API for retrieving controllers would have to change to support that though

There is no API for retrieving controllers, extensions simply push them into VS Code. What can be done is allowing extensions to signal that they are still thinking. Tho, that doesn't allow for the picker with progress style UI.

**Comment by misolori** [comment]
## Opening a notebook

The flow for opening a notebook for the first time is similar to the flow above, except a bit simpler since it bypases the need to create a new notebook file. You'll see the same "Select a kernel" quick pick since we don't know what kernel the user has and then prompt them to install one from the marketplace. This kernel should get persisted to the workspace so the user doesn't have to keep re-selecting the same kernel.


https://user-images.githubusercontent.com/35271042/129969691-7255a49e-30df-49c1-b8c6-368b4f5f4216.mp4

**Comment by misolori** [comment]
Design explorations are complete for running & opening a notebook for the first time. If other scenarios come up we can address those.
