### ISSUE TITLE
@see tag not clickable in hover window

### ISSUE THREAD

**Issue by jasonkuhrt** [microsoft/vscode#128593]
VS Code Version: 1.58.0
OS Version: macOS 11.2.3
Steps to Reproduce:

Define a valid @see tag

Notice it working in the source code

![](https://user-images.githubusercontent.com/284476/111706887-76957b80-8819-11eb-8d05-d60c94250e82.png)

Notice it not working in the tooltip

![](https://user-images.githubusercontent.com/284476/111706923-8745f180-8819-11eb-8b6b-cc98da253498.png)

Notes:

- re-open of https://github.com/microsoft/vscode/issues/119288 because that issue is locked preventing me from commenting there and was labeled as a duplicate of an issue that is since closed https://github.com/microsoft/TypeScript/issues/35524 but this issue is still not resolved. If this is a duplicate of something intended to be worked on, it seems that it should be closed with a link to an open issue, not a closed one.

**Comment by jasonkuhrt** [comment]
Maybe I'm confused and [usage](https://code.visualstudio.com/updates/v1_57#_jsdoc-link-support) is supposed to be `@see {@link ...}`?

**Comment by mjbvz** [comment]
Yes you can use `@see {@link ...}`.

Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) if you'd like the bare form of `see`  supported too
