### ISSUE TITLE
Allow svgs in walkthroughs to be clickable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#128581]
We previously talked about how it would be great if our [SVGs could leverage links](https://alligator.io/svg/hyperlinks-svg/) to open commands (like opening the extension marketplace) as the extension images in the walkthroughs look clickable:

<img width="1176" alt="CleanShot 2021-07-13 at 14 58 47@2x" src="https://user-images.githubusercontent.com/35271042/125530960-b2bffc1a-58e7-4974-8192-985a00ac5145.png">

**Comment by misolori** [comment]
Thanks for adding this @JacksonKearl! I was trying to update our svgs to start using this via:

```svg
<a xlink:href="command:extension.open?%5Bms-python.python%5D">
	<g filter="url(#filter1_d)">
		<rect x="236" y="316" width="48" height="48" rx="4" fill="white"/>
		<rect x="240" y="320" width="40" height="40" fill="url(#pattern1)"/>
	</g>
</a>
```

![image](https://user-images.githubusercontent.com/35271042/125688660-7bf4bf61-2e93-4ffc-af50-bc7c532af1d7.png)


The command was provided by @sandy081 but it sounds like the extensionId argument is not being passed when debuggedL:

![image](https://user-images.githubusercontent.com/35271042/125688749-bfa93313-cff3-4338-96f0-69b17a635b28.png)


@JacksonKearl do you know why that would be? Other commands work fine but the ones with arguments don't

**Comment by JacksonKearl** [comment]
@misolori I believe you want "command:extension.open?__%22__ms-python.python__%22__"

**Comment by misolori** [comment]
Aha! Thank you! Looks like this command opens the extension in the extension detail view. Do we have a command to open this in the extensions view like:

<img width="346" alt="CleanShot 2021-07-14 at 14 42 37@2x" src="https://user-images.githubusercontent.com/35271042/125696993-05c5a4b3-9cbb-461b-aabe-463356b764bb.png">

**Comment by misolori** [comment]
This works 🥳🎉


https://user-images.githubusercontent.com/35271042/125700621-814c9660-79b6-4673-b8d3-6d89d790607e.mp4
