### ISSUE TITLE
"Open with code" context menu should open in already open VS Code window

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#12856]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Version 1607 OS Build: 14393.187

Steps to Reproduce:
If VS Code is already open then doing "Open with code" context menu should open another file in same window. Snapshot is added for reference:
![1](https://cloud.githubusercontent.com/assets/16834561/18899653/24c71084-8558-11e6-8a22-1f4d2ac4afbf.png)
Here, 2.html is already open in VS Code. If I click on "Open with code" context menu on 1.html, it should open in same window. Not new VS Code window.

**Comment by bpasero** [comment]
`"window.openFilesInNewWindow": false` helps for files
