### ISSUE TITLE
Win10

### ISSUE THREAD

**Issue by ggdream** [microsoft/vscode#128635]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.1 
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Make a file in the file column be modified
2. Use the cursor to select part or all
3. Cannot copy file name via ctrl+c

**Comment by kieferrm** [comment]
Pls see 
![image](https://user-images.githubusercontent.com/4674940/125641802-7bf5f487-5c1d-403f-9cf3-2d318dc74635.png)

**Comment by ggdream** [comment]
> Pls see
> ![image](https://user-images.githubusercontent.com/4674940/125641802-7bf5f487-5c1d-403f-9cf3-2d318dc74635.png)

Thanks for the reply
