### ISSUE TITLE
Keybinding for "File: Quick Open Recent" does not work properly

### ISSUE THREAD

**Issue by mil-ad** [microsoft/vscode#128629]
Issue Type: <b>Bug</b>

I'm setting a following custom keybinding for the "File: Quick Open Recent":

```json
{
    "key": "alt+meta+o", "command": "workbench.action.quickOpenRecent"
},
```

While this custom keybinding brings up the popup menu correctly, as soon as I let go of the pressed keys the menu takes action and opens (presumably) the first item in the recent list without waiting for user input.

If I keep the keybinding pressed I can press other keys such as arrow keys and they work correctly but obviously this is not the intended behaviour.

If I search for this action in the Ctrl+P menu then things work fine.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:20:02.397Z)
OS version: Linux x64 5.10.49-1-lts
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 4029)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.33GB (0.88GB free)|
|Process Argv|--crash-reporter-id 1b42240a-1e5b-49bd-abe9-2b66db838af2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.58
vscode-pull-request-github|Git|0.28.0
latex-workshop|Jam|8.19.2
vscode-text-pastry|jkj|1.2.0
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4568
highlight-dodgy-characters|nac|1.0.0
vscode-paste-and-indent|Rub|0.0.8
vscode-fileutils|sle|3.4.5
rewrap|stk|1.14.0
ayu|tea|0.20.1
shellcheck|tim|0.14.4
vscode-input-sequence|tom|0.2.0
vscodeintellicode|Vis|1.2.14
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
You are probably looking for `workbench.action.openRecent`

**Comment by usernamehw** [comment]
Nope. Tried it and it the picker is closing @bpasero to reopen the issue.

**Comment by usernamehw** [comment]
Nope. It does work. Only when keeping both modifiers `meta` & `alt` pressed:

```js
{
	"key": "alt+meta+o",
	"command": "workbench.action.quickOpenRecent"
},
{
	"key": "alt+meta+o",
	"command": "workbench.action.quickOpenNavigateNext",
	"when": "inRecentFilesPicker"
}
```
