### ISSUE TITLE
Feature Request: Save Find Settings

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#128642]
Can you please add an option to save find settings:

![VS Code find settings](https://i.stack.imgur.com/wy1SI.png)

I suggest these settings (individually) to be persisted across sessions, so when the user opens another folder or starts another VS Code application session, the previously set flags should be restored.

/ref: [https://stackoverflow.com/questions/65136826/how-can-i-have-visual-studio-code-remember-my-search-options](https://stackoverflow.com/questions/65136826/how-can-i-have-visual-studio-code-remember-my-search-options)

**Comment by ArturoDent** [comment]
To clarify, it looks like on the right you have the Find Widget.  And on the left you have the Search view.  Correct?

And you want the options from one transferred to the other?

**Comment by SetTrend** [comment]
Oh, no. Pardon me from being ambiguous.

Both settings should be dealt with separate. I only suggest these settings (individually) to be persisted across sessions, so when I open another folder or start another VS Code application, the previous flags should be restored.
