### ISSUE TITLE
Plots that work in VSCode 1.57.0 do not work in VSCode Insiders 1.59.0 - Plot Hangs

### ISSUE THREAD

**Issue by JosephKarpinski** [microsoft/vscode#128669]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.59.0
- OS Version:MacOS Big sur 11.3

Steps to Reproduce:

1 . Plot in VSCode 1.57.0 works
2.  This used to work in VSCode Insiders. Now Plots in VSCode Insiders 1.59.0 Hangs
<img width="1038" alt="VSCode2" src="https://user-images.githubusercontent.com/37123616/125649389-c003f078-4a4a-4e88-9d01-21357cd02ac0.png">
<img width="1038" alt="VSCode1" src="https://user-images.githubusercontent.com/37123616/125649436-4097074b-8eb7-408c-8fc2-f4ca7709a810.png">
<img width="1722" alt="Insiders1" src="https://user-images.githubusercontent.com/37123616/125649458-0f1122b9-d029-497a-b06c-97963e60c93e.png">
<img width="1722" alt="Insiders2" src="https://user-images.githubusercontent.com/37123616/125649487-e17e2476-3bb9-49a6-b005-24756746ae87.png">
<img width="1722" alt="Insiders3" src="https://user-images.githubusercontent.com/37123616/125649511-d97a4fdb-0443-41f1-93cd-8d17f341cd71.png">

**Comment by meganrogge** [comment]
Please file an issue with the appropriate extension

**Comment by JosephKarpinski** [comment]
Confusing.

I report a problem that has been going on for more than two days with VSCode Insiders and the reply is “ “Please file an issue with the appropriate extension”. And then the issue is closed? Honestly, it is very difficult  to know where to post an issue on VSCode.
Jupyter plots under VSCode Insiders no longer scale with the display as they had before and currently works under VSCode.
Could you please forward this to the correct support group.

VSCode Insiders is unusable in this state.

Thank you.

Sent from my iPhone

On Jul 15, 2021, at 11:56 AM, Megan Rogge ***@***.***> wrote:

﻿

Please file an issue with the appropriate extension

**Comment by JosephKarpinski** [comment]
Please open the issue and forward to support manager.

Thank you.

Sent from my iPhone

On Jul 15, 2021, at 7:25 PM, Joseph Karpinski ***@***.***> wrote:

﻿ Confusing.

I report a problem that has been going on for more than two days with VSCode Insiders and the reply is “ “Please file an issue with the appropriate extension”. And then the issue is closed? Honestly, it is very difficult  to know where to post an issue on VSCode.
Jupyter plots under VSCode Insiders no longer scale with the display as they had before and currently works under VSCode.
Could you please forward this to the correct support group.

VSCode Insiders is unusable in this state.

Thank you.

Sent from my iPhone

On Jul 15, 2021, at 11:56 AM, Megan Rogge ***@***.***> wrote:

﻿

Please file an issue with the appropriate extension
