### ISSUE TITLE
matchBrackets don't work

### ISSUE THREAD

**Issue by Alexzanderk** [microsoft/vscode#128689]
Issue Type: <b>Bug</b>

add to the JSON settings `"editor.matchBrackets": "always"`
expectation: 
|-cursor
func(`|`)  - click backspace, expect open and close bracket will be removed
func`|` - result

after some time it doesn't work:
func(`|`)  - click backspace, expect open and close bracket will be removed
func`|`) - result

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|8.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 9d6b98cd-c7dc-412e-b3de-853b5548fb93|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Alexzanderk** [comment]
reproduce issue: 
`|` - cursor
func(`|`); - when the cursor in the middle of the brackets click `enter`

func(
`|`              - then go to the last bracket (`|`)) and click backspace in order to return the previous state
) 

func(`|`) - then try to remove the first bracket

**expectation:** 
func`|`

**result:**
`|`)

**Comment by Alexzanderk** [comment]
@alexdima @mojodna @doudou @threeve 
Hey guys! I see that @alexdima is on vacation maybe you can assign this issue to somebody else?

**Comment by alexdima** [comment]
@Alexzanderk The setting you want is `editor.autoClosingDelete`
![image](https://user-images.githubusercontent.com/5047891/129946419-ca45fa2b-305c-416e-90df-5b2f8a97b4c8.png)
