### ISSUE TITLE
Markdown preview: some files flicker/reset scroll position on type

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12865]
In todays insider build I see bad flickering happen when I edit the source file of a markdown preview. This is so bad that it makes it really annoying to have the preview open while editing.

I verified this was not the case in 1.5.

At some point I see the scrollbar disapparing.

This is editing 1.6 release notes in our vscode-docs repo (which includes images, maybe related).

Eventually the flicker goes away, but here are steps that make it happen for me:
* fresh window (I am using the light theme)
* open 1.6 md
* open the preview to the side and do not scroll
* just type into the markdown file

**Comment by jrieken** [comment]
electron update?

**Comment by bpasero** [comment]
@jrieken could be. Also I cannot reproduce when I am not using icons in the markdown. When this happens I also see the scroll position lost, it always jumps back to the top.

Maybe the content in that file is getting too big for Chrome to update in a smooth way.

**Comment by bpasero** [comment]
This is weird, sometimes it stops reproducing after a while. It also seems window size related. 👎

**Comment by jrieken** [comment]
@bpasero You work using a certain default zoom level, right?

**Comment by bpasero** [comment]
@jrieken yeah, I am on zoom level 1 always

**Comment by bpasero** [comment]
![sep-28-2016 11-16-18](https://cloud.githubusercontent.com/assets/900690/18908240/1dfd7e02-856f-11e6-8434-36841769e0e0.gif)

Bad quality gif shows it

**Comment by jrieken** [comment]
I can repo with the `1.6md` page but not with a different sample (which also loads images)

**Comment by jrieken** [comment]
I cannot repo with `./scripts/code.sh`

**Comment by bpasero** [comment]
I was not able to reproduce with VS Code stable.

**Comment by jrieken** [comment]
So, I can see that sometimes (unclear when/how) the embedded iframe looses it's `scrollTop` (it's being reset to 0). What I can do is to set it back to the *before* value when that happened. Might not always be good but it might be an improvement.

**Comment by bpasero** [comment]
That would help for the scrolling issue but I guess the underlying problem is that somehow Chrome decides to just recreate the whole page, much like an explicit refresh on a website.

**Comment by jrieken** [comment]
We do [that](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.html#L116) because otherwise scripts et al won't be reloaded again - however we are (were?) somehow lucky that chrome did restore the position for us. Maybe their internals changed such that that doesn't happen anymore

**Comment by jrieken** [comment]
Closing this after my best effort fix. For markdown a more specific solution could be considered. When generating html from md the current cursor position could be respected and an self-revealing tag can be inserted to always sync source and preview
