### ISSUE TITLE
Right (terminal) panel gets spontaneously resized

### ISSUE THREAD

**Issue by brushless-glitch** [microsoft/vscode#128697]
Does this issue occur when all extensions are disabled?: Yes (verified)

- VS Code Version: Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.0-1026-oem (Ubuntu 20.04)

I use two Wayland sessions and switch between them using Alt+F2/Alt+F3

Steps to Reproduce:

1. Open vscode
2. Open terminal
3. Send the terminal to the right using "View\Appearance"
4. Size document/terminal window equally
5. Switch to another Wayland session using Alt+F2
6. Wait 30 minutes to ensure both sessions trigger screensaver
7. Switch back to original Wayland session using Alt+F3
8. Observe that the terminal window in VSCode is shrunk

Expectation: the window sizes and proportions should stay the same unless user resizes them

I am not sure what exactly event triggers the re-sizing, proportions sometimes stays untouched.

I am attaching two screenshots - one taken originally, and left open. When I came back to the app, the windows were resized, I did not resize them myself.

![Screenshot from 2021-07-14 09-44-50](https://user-images.githubusercontent.com/76972467/125693557-41403152-bd8a-4e15-9d50-7ba7dc2e5ee2.png)
![Screenshot from 2021-07-14 14-00-22](https://user-images.githubusercontent.com/76972467/125693560-ee2016fa-4739-4ce9-b8d8-f1adfe62fba6.png)

**Comment by meganrogge** [comment]
possibly related to https://github.com/microsoft/vscode/issues/127671
