### ISSUE TITLE
Terminal doesnot work

### ISSUE THREAD

**Issue by bonisha89** [microsoft/vscode#128677]
I  cannot type anything in my terminal. It doesn't even show the root user or anything else for that matter. your clipboard because it was too large to send. 

![image](https://user-images.githubusercontent.com/68666030/125661256-12d9d8ed-3577-4cb2-b72a-2b89d8780eaa.png)
Please paste.

**Comment by meganrogge** [comment]
/duplicate #128342 will be fixed in the recovery build released tomorrow
