### ISSUE TITLE
VSCode does not remember the UI settings. "Render Whitespaces" and "Zoom" levels reset after every restart

### ISSUE THREAD

**Issue by sachinma** [Microsoft/vscode#12860]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@sachinma these settings are not stored, if you want to persist the settings, please open settings (File > Preferences) and set:
* `window.zoomLevel`
* `editor.renderWhitespace`
