### ISSUE TITLE
Unable to create new file if `Explorer: Sort Order` is set to `modified` and some file is appending

### ISSUE THREAD

**Issue by zzh1996** [microsoft/vscode#128628]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Both the latest stable release and the latest insider

```
Version: 1.58.1 (user setup)
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-13T06:58:28.115Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

```
Version: 1.59.0-insider
Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
Date: 2021-07-14T07:15:41.024Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Download the latest VSCode stable release or insider version
2. Create a new folder and open it in VSCode
3. Change `Explorer: Sort Order` to `modified` in Settings
4. Keep appending to a file (You can run `while true; do date >> 1.log; sleep 0.1; done` in Linux shell or run some similar scripts doing the same thing)
5. Try to create new file or folder in VSCode
6. The file name textbox will disappear immediately after you click `New File` (due to file list refreshing?)

**Comment by isidorn** [comment]
Dup of New File Input Box closes for file events in the background.

**Comment by SmartHypercube** [comment]
> Dup of New File Input Box closes for file events in the background.

Could you please give a link to the original issue? I searched "New File Input Box closes for file events in the background" in issues but didn't find anything related. I would like to subscribe to that issue's notifications.

**Comment by SmartHypercube** [comment]
@isidorn I think it's a little strange to close an issue as dup without mentioning the original issue's number. I cannot find any issue named "New File Input Box closes for file events in the background". This is unhelpful and will leave future people searching for the same problem a big mystery.

Could you please reopen this issue or give the original issue's number?

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/112293
