### ISSUE TITLE
CSS: @-ms-viewport and @-o-viewport at-rules cause html document rendering to break

### ISSUE THREAD

**Issue by jpcastberg** [microsoft/vscode#128693]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0-insider
- OS Version: OSX Catalina

Steps to Reproduce:

1. create a blank html document (you can populate a template using the `!` emmet abbreviation)
2. add a `<style>` tag in the head of the document
3. add css at-rule
```
@-ms-viewport {
    width: auto;
}
```
4. html syntax highlighting gets all goofed up
![image](https://user-images.githubusercontent.com/37011196/125686922-1dd35c6b-fffc-4dff-8dea-7b3333edb47a.png)

a seemingly identical issue was opened and fixed in 2018: https://github.com/microsoft/vscode/issues/54515, but that fix does not appear to work anymore.

**Comment by alexr00** [comment]
@jpcastberg thank you for reporting this issue. We get our CSS syntax highlighting grammar from https://github.com/atom/language-css. There's already an upstream issue for this: https://github.com/atom/language-css/issues/176

**Comment by jpcastberg** [comment]
cool. opened pr for that repo: https://github.com/atom/language-css/pull/182

**Comment by jpcastberg** [comment]
@alexr00 - fix on upstream branch was merged. just would like to confirm that it will be automatically included in a future release of vscode, and no further action is required on my part.

**Comment by alexr00** [comment]
@jpcastberg thanks for making this change happen! I just pulled in the latest css grammar to pick up the changes.
