### ISSUE TITLE
run botton on top right side of IDE

### ISSUE THREAD

**Issue by kumar11473** [microsoft/vscode#128683]
Issue Type: <b>Feature Request</b>

Traingular Run botton is not available on top right corner of IDE. plz solve it 

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by weinand** [comment]
I don't understand. Please explain.

**Comment by kumar11473** [comment]
Is it necessary to install an extension for the run button in VS code?

**Comment by weinand** [comment]
Please read https://code.visualstudio.com/docs/editor/debugging for an overview of how to run and debug in VS Code.
