### ISSUE TITLE
Previously trusted SSH workspace is no longer trusted

### ISSUE THREAD

**Issue by lostmsu** [microsoft/vscode#128678]
Issue Type: <b>Bug</b>

I trusted a remote SSH workspace (remote is Windows) I think with the previous version of the VS Code (1.57.x). Now when trying to open this workspace, it loads in Restricted Mode. The trust button does no visible change. The workspace is listed under trusted as "SSH: pc-name" /C/Users/etc/etc

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes
Remote OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (50.92GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Blost-pc/c%3A/Users/lost/Projects/Fun/Robot/RosSac --crash-reporter-id 0d5e86b0-b193-444e-b79c-7d38421a5d20|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lost-pc|
|OS|Windows_NT x64 10.0.19043|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|31.87GB (11.93GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-ssh-edit-nightly|ms-|2021.7.19620
remote-wsl|ms-|0.58.2
vs-keybindings|ms-|0.2.1
jupyter|ms-|2021.8.1013163132

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by lostmsu** [comment]
#124210 seems very similar except I was previously able to trust that workspace.

**Comment by lszomoru** [comment]
@lostmsu,
Are you able to reproduce the same behaviour using VS Code Insiders?
Also what if you use the workspace trust editor to remove the existing entry and then try to press the `Trust` button again?

**Comment by lostmsu** [comment]
Just FYI, deleting the workspace from the list of trusted and then clicking "Trust" again solved the issue.
