### ISSUE TITLE
on windows can't open line with absolute path on windows

### ISSUE THREAD

**Issue by kefengwei** [Microsoft/vscode#12861]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

 as you can see when i use -g option with absolute path, i got error.
"Arguments in `--goto` mode should be in the format of `FILE(:LINE(:COLUMN))`."

**Comment by joaomoreno** [comment]
Can you show how the command you run looks like exactly?

**Comment by bpasero** [comment]
@kefengwei @joaomoreno I think we fixed this in our insider release, I got a related bug some time ago.

Can you try with insiders please? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by kefengwei** [comment]
@bpasero I try with insiders, the problem got solved.thanks.

**Comment by ramya-rao-a** [comment]
Absolute path in Windows would have the drive letter making this duplicate of #11731
