### ISSUE TITLE
Git hooks do not use correct ruby version

### ISSUE THREAD

**Issue by royalpeasantry** [microsoft/vscode#128692]
```
VS Code Version: 1.58.1
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-13T06:22:33.013Z (1 day ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

Not sure if this is a feature request or a bug.

Ruby developers generally use an environment manager like chruby or rvm to set the PATH correctly for their project. The manager is triggered when you change directory into a folder that has a config file set in it (specifics change based on which manager you are using).

Unfortunately it seems that vscode does not trigger the version manager code when opening a workspace, so the PATH does not get updated to point to the correct ruby binary.

This means several things, but the one I am running into is that git hooks use the wrong ruby version. I've seen references implying that other people also have issues with tasks, and I'm sure there are more.

### Workaround for Single-Root projects:
```
cd 'path/to/project/root/with/ruby-version/file'
code <optional workspace file>
```
This works for single-root projects - even if it is a bit undiscoverable and annoying.

### Multi-Root Repro Steps
Unfortunately it does not work for multi-root projects, since each project can have its own ruby version.

First install [chruby](https://github.com/postmodern/chruby) and [ruby-installer](https://github.com/postmodern/ruby-install)
```
brew install chruby
brew install ruby-install
```
Don't forget to set chruby up (need to source some files, details in brew info)

Then install the ruby versions we're using for the test
```
ruby-install 2.6.5
ruby install 2.7.2
```

Create project 1 using ruby version 2.6.5 and add a pre-commit hook that will fail if the ruby version is incorrect
```
git init -b main project-1
cd project-1
echo "ruby-2.6.5" > .ruby-version
git add .ruby-version
git commit -m test
echo "#!/usr/bin/env ruby
if RUBY_VERSION == '2.6.5'
  puts 'Correct Ruby Version'
  exit(0)
else
  puts 'Wrong Ruby Version'
  exit(1)
end" > .git/hooks/pre-commit
chmod 755 .git/hooks/pre-commit
cd ..
```

Create project 2 using ruby version 2.7.2 and add a pre-commit hook that will fail if the ruby version is incorrect
```
git init -b main project-2
cd project-2
# Using ruby version 2.7.2
echo "ruby-2.7.2" > .ruby-version
git add .ruby-version
git commit -m test
# Add a pre-commit git hook that fails when the ruby version is incorrect
echo "#!/usr/bin/env ruby
if RUBY_VERSION == '2.7.2'
  puts 'Correct Ruby Version'
  exit(0)
else
  puts 'Wrong Ruby Version'
  exit(1)
end" > .git/hooks/pre-commit
chmod 755 .git/hooks/pre-commit
cd ..
```

Create main project root with code-workspace file referencing the other two projects
```
mkdir project
cd project
echo '{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "../project-1"
		},
		{
			"path": "../project-2"
		}
	],
	"settings": {}
}' >> workspace.code-workspace
cd ..
```

Then just open vscode and try and commit a change - at least one of project-1 or project-2 will fail

### Solutions?
I don't have a great answer here.. but I don't think this is limited to ruby.

**Comment by viperet** [comment]
@royalpeasantry maybe try to run chruby from the git hook?

**Comment by lramos15** [comment]
I think this has something to do with the way `chruby` listens to directory changes and there are no plans to address it anytime soon as I'm not even sure how we would fix this.
