### ISSUE TITLE
right clicking on terminal icon and choosing different icons and colors in the panel doesn't work

### ISSUE THREAD

**Issue by arian47** [microsoft/vscode#128636]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: ubuntu 21.04

Steps to Reproduce:

1. right click on the terminal icon in the panel area
2. choose different icon and color for the terminal
3. it won't work and after moving it to the editor area if you had another terminal there too it will mess up that terminals icon as well
4. but moving it down again to the panel area will cause the changes to appear but messing the other terminal icons in the editor area

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
