### ISSUE TITLE
how to drag to show the panel when the panel was moved to right

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#128601]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. we can drag the bottom bar upper to show the panel,
2. how to drag when panel was moved to right or left

**Comment by sbatten** [comment]
unfortunately this is not possible due to the ambiguity with the window resizer. when the window is fullscreen, we allow it, but not otherwise. using keyboard shortcuts are the recommended way to quickly show the panel.
