### ISSUE TITLE
No markdown preview with error: command 'markdown.showPreview' not found

### ISSUE THREAD

**Issue by msoutopico** [microsoft/vscode#128620]
Does this issue occur when all extensions are disabled?: Yes/No

VSCode Version: 1.58.0 (user setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a markdown document or open an existing one.

2. Right click the tab and select Open Preview. 
Expected result: another tab opens with the preview
Actual result: nothing happens

3. Press Ctrl+Shift+V (shortcut to open preview)
Expected result: another tab opens with the preview
Actual result: error `command 'markdown.showPreview' not found` appears in the status bar

This was working well for me before I got the latest update today.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
