### ISSUE TITLE
VSC keeps freezing, using jupyter notebook

### ISSUE THREAD

**Issue by TickboxPhil** [microsoft/vscode#128658]
Issue Type: <b>Bug</b>

VSC keeps freezing, using jupyter notebook. Suddenly you can't move cursor and although you can try to save, it's ignored. Have to close and re-open. No other notification or warning is displayed, so difficult to see why, although often it's editing the same code which triggers it, although increasingly, it's different code chunks.

Have installed all Win 10 updates, rebooted, same thing. GitHub Desktop closed, so no effect.

If there was some debug trace, maybe we could pinpoint it.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.25GB free)|
|Process Argv|--crash-reporter-id d2176d00-8911-4b68-94f8-b8a8636608a0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
synthwave-vscode|Rob|0.1.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by rebornix** [comment]
@TickboxPhil thanks for reporting this, does it happen to all your notebook files or only a few of them? Do you have a relative stable reproduce code which you can share with us?

**Comment by TickboxPhil** [comment]
[Tickbox Basics 03 Auto - Freeze.zip](https://github.com/microsoft/vscode/files/6817074/Tickbox.Basics.03.Auto.-.Freeze.zip)
A couple of them so far. One is still consistant so can repro the freeze - ipynb in zip attached (it needs Plotly import). If you run all cells above cell 3 which is near bottom starting with:
```
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
```
...and then run that cell 3, it will trigger normal error (not freeze yet). If you scroll the error (its quite a long one, which may cause the crash, or it might be to do with fact that cell 3 was moved down to bottom - I can't see a way to re-order them) and then go to edit the code (eg. try to remove the warned hoverover) it freezes the Editor on my PC so can't save - hopefully yours too, see how it goes!

**Comment by CatNofishing** [comment]
Similiar peoblem， it annoys me

**Comment by CatNofishing** [comment]
@rebornix This problem will appear suddenly, and the frequency is very high, your mouse will suddenly be unable to edit jupyter
![动画](https://user-images.githubusercontent.com/33288114/126093255-0a0db709-d78b-4798-8b8c-9a2c6ee7ff77.gif)
