### ISSUE TITLE
Missing folder explorer

### ISSUE THREAD

**Issue by MistaLemur** [microsoft/vscode#128698]
Issue Type: <b>Bug</b>

When I open a folder, either locally or using the Remote - SSH extension, the editor opens successfully, and is able to open previously opened files with no issue.
However, the folder explorer view is disabled, and is grayed-out and cannot be reenabled in the explorer menu.
This happens now nearly every time I open VSCode.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux arm64 4.9.201-tegra

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (7.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.194|
|OS|Linux arm64 4.9.201-tegra|
|CPUs|unknown (4 x 1479)|
|Memory (System)|3.87GB (1.81GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
gc-excelviewer|Gra|3.0.42
todo-tree|Gru|0.0.213
git-graph|mhu|1.30.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
vsliveshare|ms-|1.0.4568

</details>

**Comment by MistaLemur** [comment]
After uninstalling and then reinstalling vscode, this issue still occurs. No extensions are installed. The first run after reinstallation, the folder explorer functions as expected. After closing and reopening vscode, the folder explorer becomes disabled and no longer functions.

**Comment by Jackzmc** [comment]
I'm having the same issue now too, it just started today. All my existing project folders open completely fine in vscode but any new folders open in vscode just don't show their contents anymore which is extremely annoying.

Also happens with safemode on.

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
