### ISSUE TITLE
Global tool was changed in the latest vscode update

### ISSUE THREAD

**Issue by scsleal** [microsoft/vscode#128681]
## Environment data

-   VS Code version: 1.59.0-insider
-   Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
-   Jupyter Extension version: 2021.8.1025925145
-   Python Extension version: 2021.6.944021595
-   OS and version: Windows_NT x64 10.0.19041
-   Python version: 3.8.3 64-bit
-   Type of virtual environment used: virtualenv
-   Jupyter server running: Local

## Description

The latest vscode update changes the global tool of notebook. 
Comparison between the versions:

| |latest update|old update|
|-|----------------------|------------------|
|Version| 1.59.0-insider (user setup)|1.59.0-insider (user setup)|
|Commit| 9520f0a515e7e24802c92f885a0efb242fca3831|a9070718ebb793eef4e94e34307eee15c09a0cd4|
|Electron| 13.1.6|12.0.13|
|Chrome| 91.0.4472.124|89.0.4389.128|
|Node.js| 14.16.0|14.16.0|
|V8| 9.1.269.36-electron.0|8.9.255.25-electron.0|
|OS| Windows_NT x64 10.0.19041|Windows_NT x64 10.0.19041|

## Expected behaviour

![expected](https://user-images.githubusercontent.com/62887077/125660609-7be61626-2db6-4007-a703-599fb485106d.png)

## Actual behaviour

![bug](https://user-images.githubusercontent.com/62887077/125660618-c7e63479-2065-4a41-adf7-576f53612b9d.png)

**Comment by rchiodo** [comment]
Looks like this is a context key problem with workspace trust.

**Comment by rebornix** [comment]
All of a sudden commands are not available when they have `isWorkspaceTrusted` in their when clause but the workspace is trusted.

**Comment by lszomoru** [comment]
Probably a regression introduced by a recent refactor of the workspace trust context keys. Apologies for the inconvenience.
