### ISSUE TITLE
Welcome page customization and the behavior of Ctrl/Cmd+R

### ISSUE THREAD

**Issue by scaomath** [microsoft/vscode#128661]
## A longer recent list

Related: #106715, #83451

While I understand the vscode team is not pursuing in this direction (#30646, #63057), it would be really nice if the number of recent shown can be customized. 

Especially for people using a screen with higher resolutions:

![Screenshot from 2021-07-14 09-19-48](https://user-images.githubusercontent.com/4467042/125640489-69fe6f60-8235-4f30-b6da-4018b804a1b4.png)

## Better Ctrl/Cmd + R behavior

I understand that this function is similar to <kbd>Ctrl</kbd>+<kbd>R</kbd>, then type the filename. However, upon opening a specific file, the workspace that file is under will NOT be automatically loaded:

![Screenshot from 2021-07-14 09-42-33](https://user-images.githubusercontent.com/4467042/125642058-a4a50945-d1d0-417c-af22-d274432c9b5f.png)

For the example above, upon hitting enter, the workspace `ft-experiment` will not be loaded. Therefore I myself like to load the workspace first, then <kbd>Ctrl</kbd>+<kbd>P</kbd>, which makes the first simple change more attractive.

## Reason behind
Working in scientific computing often deals with LaTeX, experimental code, production code, debugging happening in the same repo same branch. I myself often uses multiple workspaces to handle different "working spaces" (I also taught my student to do so...), which makes displaying more workspaces or folder in the welcome page a nice feature. Thoughts?

**Comment by bolu-tife** [comment]
Hello @JacksonKearl  I would like to work on this issue. Do you have any guide on how to reproduce this and what is required to be done?

**Comment by JacksonKearl** [comment]
@bolu-tife Sure! 

To reproduce, set the max results setting to some larger value, and run a search in the search editor which has more results than the value:
![image](https://user-images.githubusercontent.com/8586769/125858864-efe79c35-e97e-4637-9fe8-ab9d4c90e740.png)
![image](https://user-images.githubusercontent.com/8586769/125858936-e2e2084e-8df1-434d-9071-cf7805c32033.png)


Access search editor with: 
![image](https://user-images.githubusercontent.com/8586769/125858957-b8b6b731-67be-4c92-84d0-d9dc70f802df.png)


You can start by changing the limit passed here to read from the `configurationService` https://github.com/microsoft/vscode/blob/d7712edeaa8e0321ff738329b3a8a14efa292bc3/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L490

Then, you should add a way for the search to be re run with no limit. See what happens in the search from the sidebar, whose code is here: https://github.com/microsoft/vscode/blob/1fc68f3cf274141942b424894645a4f7096ec1f1/src/vs/workbench/contrib/search/browser/searchView.ts#L0-L1 for how to make that change.

**Comment by bolu-tife** [comment]
Thank you

**Comment by dustinm76** [comment]
@JacksonKearl I'm a bit confused about your suggested fix. It seems like the issue here was more about making the Recent list longer than getting a large number of results to show up in the search editor.

**Comment by scaomath** [comment]
> @scaomath One alternative in this vein is the concept of "favoriting" workspaces, so instead of having a longer list of 10+ recent workspaces, you might have your 4 "Starred" workspaces at the top of the list, then 6 recent ones after that. Would that work for your use case?

Personally I like this change a lot (especially for those us who have workspaces involving loading docker containers), but I doubt adding extra UI elements is what VSCode community want...

Guess I will wait for someone to implement an extension for this.

**Comment by githrdw** [comment]
@scaomath  I ran into the same thing and therefore decided to make an extension in the form of a dashboard.  Maybe you want to try it out?  It is a dashboard where widgets can be placed on such as a fixed list of folders or workspaces, a WYSIWYG editor and a list of recently opened folders (limit count is dynamic).  But the best part is that you can make your own widgets with React.

You can install from the marketplace:
https://marketplace.visualstudio.com/items?itemName=rubendew.vsch-core

Or feel free to take a peek in the source code:
https://github.com/githrdw/vsc-home
