### ISSUE TITLE
How to change color of modified repository?

### ISSUE THREAD

**Issue by jaybabani** [microsoft/vscode#128618]
I work with over 30 to 40 repositories and submodules in a visual studio code. All this repositories are shown as source control. I want to highlight modified repositories in source control by changing their colors. Right now i could not find any option to change colors of modified repositories. How to change the colors of this repositories in source control.

Changed repositories right now show a simple asterick (*) mark near branch name. How to change its color for better highlighting.
![vsfeature](https://user-images.githubusercontent.com/3775102/125584591-8ffe1f3c-4cfc-462f-a811-d84324bcf51a.jpg)

**Comment by W3Dojo** [comment]
#### This is a great idea!
