### ISSUE TITLE
Kill terminal button is still dysfunctional

### ISSUE THREAD

**Issue by Unknown273** [microsoft/vscode#128607]
Issue Type: <b>Bug</b>

In the previous update of Visual Studio Code, the Kill terminal button had stopped working, it would work once and but not again. Please fix this bug as soon as possible

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.45GB free)|
|Process Argv|D:\\E Yousuf\\Study Material\\My Java Files --crash-reporter-id 79477b55-3597-4aa7-bcd1-15326f638757|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.3.2
prettier-vscode|esb|8.0.1
auto-close-tag|for|0.5.11
auto-rename-tag|for|0.1.7
code-runner|for|0.11.5
better-cpp-syntax|jef|1.15.6
csharp|ms-|1.23.13
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
hexeditor|ms-|1.7.1
debugger-for-chrome|msj|4.12.12
java|red|0.80.0
vscode-xml|red|0.17.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.13
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
vscode-icons|vsc|11.5.0
commandlist|yam|1.0.3
material-theme|zhu|3.10.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
will be fixed in the recovery build released tomorrow /duplicate #128264
