### ISSUE TITLE
终端闪退

### ISSUE THREAD

**Issue by junjie-lean** [microsoft/vscode#128617]
Does this issue occur when all extensions are disabled?: No

版本: 1.58.1
提交: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
日期: 2021-07-13T06:22:33.013Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0
Steps to Reproduce:

1.打开编辑器（open editer）
2.打开终端 (open terminal)
3.放大终端至全屏 (zoom terminal in full screen,edit area)
4.关闭终端(close terminal)
5.再次尝试打开终端(and try reopen termial )

**Comment by CodeCrazy-ywt** [comment]
Well, he has put the English translation for every step to reproduce in the brackets after the steps.

**Comment by duanqn** [comment]
> Well, he has put the English translation for every step to reproduce in the brackets after the steps.

He/She ;)

**Comment by CodeCrazy-ywt** [comment]
Ahaha, I didn't think about that much...Sorry about that😅
