### ISSUE TITLE
support document diff

### ISSUE THREAD

**Issue by peacedog123** [microsoft/vscode#128614]
Issue Type: <b>Feature Request</b>

just like the functionality of vimdiff on linux, show the difference between two files.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-21-generic

**Comment by kieferrm** [comment]
You can select two files in the explorer:

![image](https://user-images.githubusercontent.com/4674940/125647314-4b732201-d0f8-4cb4-b7d5-2f8d6228f231.png)


Or you can select on file for comparison:

![image](https://user-images.githubusercontent.com/4674940/125647407-db92c568-e034-41fd-aea8-224ccac20a9f.png)

and send compare to another file:

![image](https://user-images.githubusercontent.com/4674940/125647465-d1819a1e-2804-46a2-a2f4-ba3b041774cc.png)
