### ISSUE TITLE
remoteExplorerService.ts function takes 7 seconds on window reload

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128640]
Looking into reload performance and noticed something odd:

![image](https://user-images.githubusercontent.com/2193314/125612002-38edf26d-36eb-47cc-a764-466b582fe792.png)

Clicking into the function landed me here:

![image](https://user-images.githubusercontent.com/2193314/125612106-819e355c-1094-42a2-b133-c00eeaaa5d61.png)

Version: 1.59.0-insider (user setup)
Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
Date: 2021-07-14T07:15:41.024Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

<html>
<body>

CPUs | Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3398)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.94GB (2.94GB free)
Process Argv | --crash-reporter-id f1beee56-b631-4e44-b2a7-05e621b3ee12
Screen Reader | no
VM | 0%

</body>
</html>

**Comment by alexr00** [comment]
@Tyriar were you connected to a remote? And if so, which remote extension were you using?

**Comment by Tyriar** [comment]
No I was on a load window. If this doesn't seem possible based on the code, maybe it was just devtools acting up as the session was being torn down?

**Comment by alexr00** [comment]
I can't see how we'd be trying to do any port forwarding in a local window. If you see it again let me know!
