### ISSUE TITLE
using split terminal attaches debugger and stop it

### ISSUE THREAD

**Issue by saroj990** [microsoft/vscode#128684]
Issue Type: Bug

Steps to recreate:

Fire up a terminal inside Code, then either use `cmd + |` or split using the context menu option.

<img width="1756" alt="Screenshot 2021-07-14 at 11 30 06 PM" src="https://user-images.githubusercontent.com/13915631/125670500-f8f8d38f-e523-470b-87da-93e241f6e159.png">

Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by weinand** [comment]
I don't understand your problem. Please explain.

**Comment by saroj990** [comment]
It basically attaches a new debugger each time I want to split the terminal screen and stop it immediately . The same happens when I use `code .` to fire up a new terminal. Here is a quick video.

https://user-images.githubusercontent.com/13915631/126139361-79e98400-d7cd-4ddd-9b04-0caf2b3e8c46.mp4

**Comment by weinand** [comment]
In the status bar you can see that the "Auto Attach" feature is set to "always". As a consequence the debugger tries to "always attach"  to any JavaScript program, e.g. "code".

Disabling "Auto Attach" should help....

**Comment by saroj990** [comment]
You're right! This resolves the issue. Thanks for the helping out! But I am little confused about the the behaviour,  Running a script with node executable makes sense but for other commands like splitting up terminal and `code .` is little weird I guess.

**Comment by weinand** [comment]
You could try the "smart" setting (instead of "always"). It tries to only attach to programs where it makes sense.

**Comment by saroj990** [comment]
Thanks!
