### ISSUE TITLE
Keybindings watermark on Linux is quite complex

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12862]
See how many combinations of keys show up for "Add Cursor Above/Below"

![image](https://cloud.githubusercontent.com/assets/900690/18901902/26631c5c-854f-11e6-9ba8-d52290b92fe8.png)

**Comment by bgashler1** [comment]
This seems odd that we can use either <kbd>Ctrl</kbd> and <kbd>Alt</kbd> to do the same the command.  @bpasero is there a reason why we have both keybindings for this?

@chrmarti is it possible to also use a comma separating all but the last keybinding (in which case we use the "or") so we don't repeat the "or" over and over?

**Comment by bpasero** [comment]
@bgashler1 Maybe just show the first keybinding you get and not all of them if there are secondary keybindings defined.

**Comment by bgashler1** [comment]
@chrmarti can you do that for now?
