### ISSUE TITLE
VS Code keeps crashing with 'reason: killed code: 15'

### ISSUE THREAD

**Issue by goodspark** [microsoft/vscode#128679]
Issue Type: <b>Bug</b>

From main.log:

```
[2021-07-14 10:16:24.635] [main] [info] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[2021-07-14 10:16:24.699] [main] [info] update#setState idle
[2021-07-14 10:16:54.704] [main] [info] update#setState checking for updates
[2021-07-14 10:16:54.821] [main] [info] update#setState idle
[2021-07-14 10:20:25.295] [main] [error] CodeWindow: renderer process crashed (reason: killed, code: 15)
```

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:20:02.397Z)
OS version: Linux x64 5.8.0-53-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1778)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.14GB (7.71GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6f04067e-ae0c-4ac6-9db7-385b72061b65|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-custom-css|be5|6.0.0
saltstack|kor|0.0.8
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
scala|sca|0.5.4
vscode-bazel|Baz|0.4.1
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.0.1
go|gol|0.26.0
terraform|has|2.13.0
jsonnet|hep|0.1.0
rust-analyzer|mat|0.2.670
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
language-stylus|sys|1.11.0

</details>

**Comment by deepak1556** [comment]
Have you installed using deb or snap package ? Looks like the renderer was killed with `SIGTERM`.
