### ISSUE TITLE
Missing Edit menu items on macOS

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#128625]
Issue Type: <b>Bug</b>

On macOS, the following standard items under the Edit menu are missing:

Command-E - use selection for search
Command-G - search forward
Shift-Command-G - search backward

Sometimes these appear under a submenu called Find and sometimes also on said submenu is the actual Command-F item and sometimes other search-related items such as replace and Jump to Selection or Jump to Cursor. (Still trying to figure out Jump to Selection or Jump to Cursor on VSC--Command-L _almost_ gets the job done but I had to search the net to find out, and that was for Visual Studio, not VSC, and Windows, not Mac.)

On VSC 1.58 the actual command sequences work*, they just don't show up in the menu.

*There seems to be an intermittency. Sometimes these keystroke combinations _dont'_ work. I'm stil trying to see a pattern there, however.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_2917064|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.41.0
ada|Ada|22.0.8
Bookmarks|ale|13.1.0
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
project-manager|ale|12.3.0
rtf|ale|2.3.0
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.42.1
vscode-great-icons|emm|2.1.79
ada-snippets|Ent|0.3.0
vscode-faust|gle|1.1.0
vscode-lyx|gyt|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.19.2
svn-scm|joh|2.13.6
language-julia|jul|1.2.5
keen-neutral-icon-theme|kee|1.0.8
linter-gfortran|krv|2.2.2
octave|lea|0.1.1
eps-preview|mkv|0.1.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.2
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.17
bib|phr|0.3.0
seti-icons|qin|0.1.3
ipf|qms|1.0.1
lualint|sat|0.0.5
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.22
octave|toa|0.0.3
pdf|tom|1.1.0
vscode-lua|tri|0.12.4
vscode-icons|vsc|11.5.0
vscode-icons-mac|way|7.25.3
debug|web|0.25.1
txt-syntax|xsh|0.1.6
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by kieferrm** [comment]
You can find all keyboard shortcuts and their conditions here: <kbd>Cmd+Shift+P</kbd> > "Preferences: Open Keyboard Shortcuts" > search for "find"

![image](https://user-images.githubusercontent.com/4674940/125643201-7ba585db-e110-4285-9252-2f6dc9afd9b6.png)

**Comment by oscarrutt** [comment]
Yes, thank you. But the user shouldn't have to look through thousands of lines of keyboard shortcuts, or even ~100 for "find", to find these standard menu items which are on _every_ Mac program. BTW, even searching through--on my computer nearly 2,500 lines--I still can't find a scroll-to-cursor or jump-to-cursor command.
