### ISSUE TITLE
Terminal making new line every 2 char 

### ISSUE THREAD

**Issue by ilham-2001** [microsoft/vscode#128623]
Every time I run the python program on vs code the terminal always making new line every 2 characters, note that this thing happen just recently cause I update the new version of vs  code, can I fix this in setting or what?

![Screenshot (64)](https://user-images.githubusercontent.com/65677259/125588418-a9e2bdef-dd38-4783-acce-34244e658b54.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by ilham-2001** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

yeah, it's fixed, ty. I forgot to close this issue, sorry.
