### ISSUE TITLE
Preview window and zoom rendering issue.

### ISSUE THREAD

**Issue by AndrueCope** [Microsoft/vscode#12868]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Use the zoom feature on the editor (Ctrl/=)
2. Open the Preview Window.
The Preview window will not open zoomed. It will only show as much text as is visible in the editor window. Using the zoom hot keys causes the Preview Window to jump to the correct zoom.
If you open a second Preview Window by clicking on a link the new Preview Window is correctly zoomed. However if you close the second Preview window the firs one reverts to its original unzoomed state.
![vs code zoom](https://cloud.githubusercontent.com/assets/16834359/18905731/68008fe8-855c-11e6-879c-33657e0ff1cf.png)

**Comment by bpasero** [comment]
This is an electron bug: https://github.com/electron/electron/issues/7375

@jrieken fyi

**Comment by jrieken** [comment]
dup of #5745
