### ISSUE TITLE
New activity bar/panel hovers take too long to show up

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128672]
We added specially styled custom hovers to the activity bar and panel to help identify what these icons means and increase the discoverability of the keybindings. This originally had a short hover timer so the user would see this quickly, my thinking was that this short timing combined with the fact that these specially styled hovers could never be moused over mitigated any annoyance factor.

This also aligns with how many apps work these days, for example hovering over slack workspaces shows the hover nearly immediately, teams with its record icon, etc.

**Comment by misolori** [comment]
We do have https://github.com/microsoft/vscode/issues/123851 were we've been discussing this

**Comment by sandy081** [comment]
At present it follows the default workbench hover delay setting `workbench.hover.delay` which defaults to `1500ms`. We also have editor hover delay setting `editor.hover.delay` that defaults to `300ms`. I do not want to introduce another setting for activity bar/panel hover delay. IMO it shall be consistent across workbench, and not like some hovers appear faster and some slower.
