### ISSUE TITLE
Terminal in Editor (Closing in editor does not close terminal in background)

### ISSUE THREAD

**Issue by zeeforum** [microsoft/vscode#128643]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58
- OS Version: Windows 10

Steps to Reproduce:

1. Open terminal by pressing ctrl+`
2. Now open command palette. Search for terminal: move terminal into editor area.
3. Press enter.
4. It will open your terminal into editor area.
5. Close the terminal in editor area.
6. Now repeat step 1, 2 and 3. It will not open terminal in editor area now.
7. Because first instance we detached from editor area but in background it was running in below command line.
8. I think you need to kill that instance too. To make it work. Background terminal instance open when we opened the bottom screen of terminals.

Thank you.
Regards: Zartash

**Comment by zeeforumcompany** [comment]
The issue is resolved in version 1.58.2.

Thank you.

**Comment by zeeforum** [comment]
Issue is resolved in version 1.58.2

Thank you!
