### ISSUE TITLE
Integrated terminals are not persistent

### ISSUE THREAD

**Issue by MRVDH** [microsoft/vscode#128627]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a few terminals:
![image](https://user-images.githubusercontent.com/6686385/125594532-f4620c54-521c-4010-8381-812d1d56eeef.png)

2. Restart VS Code and notice that the terminals are not persisted:
![image](https://user-images.githubusercontent.com/6686385/125594603-910f1527-7eff-4ee7-99f7-dad9300e119c.png)

The February release claims that integrated terminals are now persistent, but I don't see it happening: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_54.md#retain-terminal-processes-on-window-reload

Extra info:
Terminal Setting Explorer Kind is set to Integrated
Terminal Setting Enable Persistent Sessions is ON

**Comment by meganrogge** [comment]
they persist on window reload, not on restart
