### ISSUE TITLE
Submenu contribution documentation

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#128603]
@joaomoreno was doing [great work](https://github.com/microsoft/vscode/pull/102784) on this. Has it been released yet? If so then the [documentation for the contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) needs to be updated. 

The closest I can find is [this comment](https://github.com/microsoft/vscode/issues/100172#issuecomment-645203070).

**Comment by usernamehw** [comment]
/duplicate of https://github.com/microsoft/vscode-docs/issues/4643
