### ISSUE TITLE
Workspaces inside VScode folder evaporated after update failure

### ISSUE THREAD

**Issue by Lunartist** [microsoft/vscode#128634]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1
- OS Version: windows10

Steps to Reproduce:

1. create folders inside "Microsoft VS Code" directory (same level with bin, locales etc...)
2. open the folder and write scripts for a few days without using repository
3. agree to update VS Code automatically
4. update somehow deletes every workspace under "Microsoft VS Code" without your permission then fails but your hardwork is all gone
5. before taking suicide pill, submit new issue for one last hope.
6. https://imgur.com/a/nrUhvbP

**Comment by joaomoreno** [comment]
I'm sorry you lost your data. But this is a really bad idea... don't put your data in folders not meant for it.
