### ISSUE TITLE
Quickfix of commonjs modules in nodejs project uses client-side es6 syntax

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#128610]
For example:

`const test = require('./test');`

is converted to

`import test from './test';`

but nodejs requires it to be:

`import test from './test.js';`

A possible fix is to have two quickfix options - convert to es6 modules, and convert to es6 modules (nodejs). Alternatively, you can maybe detect whether it is a nodejs project using modules via the package.json type field or the mjs file extension.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
