### ISSUE TITLE
FR: Autoremove unused imports

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#128651]
Something like the organise imports, except it will just remove unused imports.

**Comment by Milo123459** [comment]
I don't know why more info is needed:
A command like ALT+SHIFT+O to organise imports, except it removes unused imports.

**Comment by mjbvz** [comment]
What language is this for?

**Comment by Milo123459** [comment]
JavaScript, TypeScript

**Comment by mjbvz** [comment]
Have you tried using the remove all unused quick fix? It shows up on the unused import themselves

**Comment by Milo123459** [comment]
Yes but it only does it for that singular unused import. Not all of ten

**Comment by mjbvz** [comment]
![Screen Shot 2021-07-19 at 1 22 54 PM](https://user-images.githubusercontent.com/12821956/126222430-0458489a-ae4a-4246-80f5-d11e23c206d3.png)

There should also be a `delete all unused imports` quick fix. If you aren't seeing it, an extension could be causing it not to show up

**Comment by Milo123459** [comment]
Odd. Let me investigate.

**Comment by mjbvz** [comment]
I'm going to close this since I believe the quick fix already exists. If it not showing up in some cases, please put together a small example project that demonstrates the issue so that we can investigate
