### ISSUE TITLE
No stopping on breakpoints in the desktop web extension host

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#128637]
- create a web extension with `yo code --insiders -t=web`
- open in VS Code, 
- set breakpoint in `extension.ts`
- run the 'Run Web Extension in VS Code' launch configuration
- In the Extension Development Host window, run the `hello world` command

-> break point is not reached

**Comment by peter-dolkens** [comment]
Our team had a similar sounding issue this week, and eventually found this workaround:

> The built in Node Debug extension `ms-vscode.node-debug2` is default using a new version of the js debugging extension as of a new update. Even rolling back vscode seems to use the new Node Debug extension. For whatever reason, that's broken the breakpoints in my services. The solution was to revert to the old behaviour by adding this to my vscode/settings.json
`"debug.javascript.usePreview": false`

**Comment by connor4312** [comment]
@peter-dolkens you are not hitting the same issue since the old debugger does not debug web extensions, and bear in mind that the usePreview option will go away in the next release. Please file an issue: https://github.com/microsoft/vscode-js-debug/issues

**Comment by peter-dolkens** [comment]
Thanks @connor4312  - was trying to reduce duplicates, but I'll file a new ticket for you as it's a new issue.

Cheers
