### ISSUE TITLE
Quickly toggles excluded (hidden) files visibility in the file explorer

### ISSUE THREAD

**Issue by GilShoshan94** [microsoft/vscode#128648]
Hi,

*A command to temporarily show excluded files. A sort of toggle switch for files.exclude.*

This feature got already requested in 2020 (#110315)  and is related somehow also to the open issue #108271.

The extension suggested at the time, __*Toggle Excluded Files*__ (https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) works great and I use it since then.
The issue is its creator @eamodio does not maintain it since  2 years it appears (issues and PR are open for a very long time). And I can understand why, he is super active on other project such as GitLens !
Anyway, the point is that vscode is evolving as well as dependencies and it needs to be maintain.

I found another approach with this extension: __*Explorer Exclude*__ (https://marketplace.visualstudio.com/items?itemName=RedVanWorkshop.explorer-exclude-vscode-extension&ssr=false#overview), but it has the same issue, it is not maintained since 2 years.

I think this is a very important feature and that it should be built in.

Toggle Excluded Files path is simpler and seems easier to implement, and if you can add the toggle icon in the explorer/title menu as @eamodio wanted to do (#108271), it would be awesome.

Explorer Exclude has interesting ideas and is more complex (not just a toggle switch all or nothing but let you fine tune it).

I find the simpler approach better but I wanted to proposed several paths.  

Thank you in advance for considering this feature request and thank you for vscode.
Have a nice day.

Gil

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by GilShoshan94** [comment]
Hi @isidorn ,

I read the detailed information about the decision-making process.

I think that the 16.5K installs of the [Toggle Excluded Files extension](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files&ssr=false) with the 5 stars rating fulfills the point 2 "Has the community at large expressed interest in this functionality?". We can also find several related issue opened.

And about point 4, the affordability, it seems pretty affordable with an existing extension already out there and an alternative too. 

The issue is that nobody is maintaining this extension since 2 years, and that this feature, in my opinion, should be core to vscode and not in an extension.

Can you reopen this issue please ?
Or at least provide more information on why it is out of scope ?

Thank you.

**Comment by GilShoshan94** [comment]
Hi @eamodio,

Thank you for the extension "Toggle Excluded Files".
Can you tell us how affordable is it to implement this feature please ?

Thank you.
