### ISSUE TITLE
`Cannot activate error` warning when installing extension dependending on grammar extension

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#128652]
Verifying https://github.com/microsoft/vscode/issues/128375 

Version: 1.59.0-insider
Commit: f6df685c62da50886f7540cbf768ed4333d58bea
Date: 2021-07-13T05:14:01.722Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.11.0-22-generic

- open a dev container window
- install the `scala-lang.scala` extension (scala grammar, no code, extensionKind: `ui`, explicitly defined)
- install the `scalameta.metals` exension (with code, depends on 'scala-lang.scala')
-

Error after installing the second extension:

`Cannot activate the 'Scala (Metals)' extension because it depends on the 'Scala Syntax (official)' extension, which is not loaded. Would you like to reload the window to load the extension?`

That reload should not be necessary here.

Feel free to close the issue as it's a special setup and all works fine after reloading.

**Comment by alexdima** [comment]
The `ExtensionsActivator` works with a set of "resolved extensions". This set is only initialized on workbench start-up and is not updated when extensions are enabled/installed or disabled/uninstalled.
