### ISSUE TITLE
"Run python file in terminal" opens Terminal panel although a terminal in the editor is (and should be) used.

### ISSUE THREAD

**Issue by BerriJ** [microsoft/vscode#128670]
Does this issue occur when all extensions are disabled?: No

Version: 1.59.0-insider
Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
Date: 2021-07-14T05:14:09.735Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.12.15-arch1-1

Steps to Reproduce:

1. Have "terminal.integrated.defaultLocation": "editor" in your settings.json and the panel hidden
2. Open a .py or .R file with any command
3. Run using ctrl + enter or the "Run" Icon
4. Panel will pop up and a new terminal will be created and used in the editor area. The panel won't be used and should not pop up.

Example for python:

![Peek 2021-07-14 17-12](https://user-images.githubusercontent.com/37799358/125650184-15adedd1-2378-4b3e-99d5-5bdb4dde52f6.gif)

Example for R:

![Peek 2021-07-14 17-10](https://user-images.githubusercontent.com/37799358/125650228-262207b9-68fa-4573-b589-2184ec77ad76.gif)

This does not occur when using the python interactive window:

![python_interactive](https://user-images.githubusercontent.com/37799358/125650278-b2d59812-fac3-4261-80bb-27f802a98ee2.gif)

I truly hope this bug was not already reported. I could not find it. Since it affects at least 2 extensions I hope it was reasonable to post it here.

**Comment by jeanp413** [comment]
Created PR #128866 fixing this

**Comment by stuartleeks** [comment]
Verified that running a python file no longer shows the terminal panel with `"terminal.integrated.defaultLocation": "editor"` configured

```
Version: 1.59.0-insider (user setup)
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:47.114Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```
