### ISSUE TITLE
"Copy Full path" and "Open Containing Folder" should also e present in on the context menu of file open

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#12863]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Version 1607 OS Build: 14393.187

Steps to Reproduce: "Copy Full path" and "Open Containing Folder" should also be present as present in VS Community. Snapshots are added as attachments:

1.  This snapshot shows where the options are to be added
![1](https://cloud.githubusercontent.com/assets/16834561/18901966/e15e0ef0-856c-11e6-948a-52ef372bf723.png)

2.  This snapshot shows the options present in VS Community
![2](https://cloud.githubusercontent.com/assets/16834561/18901984/fdfd43f0-856c-11e6-88e6-d7599d36947d.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11942
