### ISSUE TITLE
Cannot close terminal in editor area after split

### ISSUE THREAD

**Issue by plmrry** [microsoft/vscode#128699]
Issue Type: <b>Bug</b>

## To Reproduce

- Add the following to `keybindings.json`

```json
  {
    "key": "ctrl+`",
    "command": "workbench.action.createTerminalEditor"
  },
  {
    "key": "cmd+d",
    "command": "workbench.action.terminal.split",
    "when": "terminalFocus"
  },
  {
    "key": "cmd+w",
    "command": "workbench.action.terminal.killEditor",
    "when": "terminal.active"
  },
```

- Press `` ctrl+` `` to open a new terminal in the editor area.
- Press `cmd+d` to split the terminal.
- Press `cmd+w`. **The new split terminal should close, but it does not.**
- Click on the left terminal pane (the first terminal created, before the split)
- Press `cmd+w` to close the terminal (**which does work**).

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (7.82GB free)|
|Process Argv|--crash-reporter-id 86012986-66ef-4266-b2a2-f4a5a20bfb68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jsdoc-markdown-highlighting|bie|0.0.1
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.0.1
aml|mas|0.0.1
rainbow-csv|mec|1.9.1
svelte-vscode|sve|105.3.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
desyncfixcf:30130017
vspla296:30182853
vsliv998:30157570
vsins829:30142904
vsfol137:30183219
vsliv368:30146709
vsreu685:30147344
vswel105cf:30184331
vspol873:30179962
python383cf:30185419
vsuse955:30177844
aadv2authfix:30212464
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvssav100cf:30294723
vsnat461:30259396
vsnot838:30250669
vspre833:30321513
vshan820:30294714
vsjoi176:30286853
vscus158:30321503
vsret599:30311620
vssha510:30309476
binariesv615:30325510
bridge0708:30335490
vsche201:30337344

```

</details>

**Comment by meganrogge** [comment]
fixed in insider's
