### ISSUE TITLE
vscode stopped working in docker container

### ISSUE THREAD

**Issue by vinniec** [microsoft/vscode#128706]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1 (and 1.58.0) but not with 1.57.1
- OS Version: tinycore 12 (inside docker)
(all the points of the issues template have been accomplished, issues compiled with the 'Report Issue' of version 1.57.1 but the problem occurs with 1.58.0/.1 which does not start at all. I have done this to give you all the prefilled useful information.)

Steps to Reproduce: 
 1. build a docker image with this command `docker build -t tinycode .` and the `code-stable-x64-1626158564.tar.gz` archive in the same dir:
```
ARG IMGVERS=latest
FROM bensuperpc/tinycore:${IMGVERS}
LABEL maintainer "Vinnie Costante <*****@gmail.com>"

ARG DOWNDIR=/tmp/download
ARG INSTDIR=/opt/vscode

ENV LANG=C.UTF-8 LC_ALL=C PATH="${PATH}:${INSTDIR}/bin/"

RUN tce-load -wic Xlibs nss gtk3 libasound libcups python3.9 tk8.6 \
    && rm -rf /tmp/tce/optional/*
RUN sudo ln -s /lib /lib64 \
    && sudo ln -s /usr/local/etc/fonts /etc/fonts \
    && sudo mkdir -p ${DOWNDIR} ${INSTDIR} \
    && sudo chown -R tc:staff ${DOWNDIR} ${INSTDIR}
COPY code-stable-x64-1626158564.tar.gz ${DOWNDIR}/
RUN tar xvf ${DOWNDIR}/code*.gz -C ${INSTDIR} --strip-components=1 \
    && rm -rf ${DOWNDIR}  
CMD ["code"]
```
 2. run this command and inside the container's shell try to run `code` :
```
xhost +
docker run -it --rm \
--net=host \
--env="DISPLAY=unix${DISPLAY}" \
--workdir /home/tc \
--volume="$HOME/.Xauthority:/root/.Xauthority:rw" \
--name tc \
tinycode /bin/ash 
```
The problem:
If the version is 1.57.1 vscode starts, if it is 1.58.0 or 1.58.1 it does not start.
Using the same distro with the same libraries on a physical machine instead of on docker, all versions of vscode work correctly.
Could I ask in your opinion what could have changed between version 1.57.1 and version 1.58.0 to cause this problem?

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.72-0-lts
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (1.86GB free)|
|Process Argv|--disable-extension --no-sandbox --crash-reporter-id 5165cb7e-f344-4859-a05c-add6d29148af|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by deepak1556** [comment]
With `1.58` we are enabling chromium's sandbox model on linux https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md. If the application cannot use namespace sandbox (which is the case in docker containers) then it will resort to use setuid sandbox via binary `chrome-sandbox` shipped alongside the application. For the setuid binary to work it needs to have the correct permissions https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/suid_sandbox.md#helper-executable

We set these permissions for deb and rpm package but it is not possible to persist them in tar archive. There are two ways to fix the issue on your end,

1) Fix the permission of setuid helper

```
sudo chown root <path-to-vscode>/chrome-sandbox
sudo chmod 4755 <path-to-vscode>/chrome-sandbox
```

2) Run with `--no-sandbox` flag in the container

Hope that clarifies, I will merge this to https://github.com/microsoft/vscode/issues/128331 so that release notes has this detailed.
