### ISSUE TITLE
VS Code deletes Jupyter Notebooks in the background

### ISSUE THREAD

**Issue by CraigThompsonCCL** [microsoft/vscode#128774]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57.1
- OS Version: Windows 10 Home, Build 19042.1083

Steps to Reproduce:

1. Create a Jupyter Notebook in the browser.
2. Close the browser, and open the Notebook in VS Code.
3. Write a bunch of code across many cells.
4. Leave VS Code open for a while (on the order of days).
5. Return to find your Notebook completely wiped clean with all your work erased. Zero cells will exist in the Notebook.

 This has now happened to me twice. I thought I must be crazy the first time. Now I see there's clearly some systemic issue.

**Comment by joyceerhl** [comment]
@CraigThompsonCCL Sorry for the trouble, please could you provide a screenshot of your notebook interface? Would like to know if you are using our webview notebook UI implementation or our preview native notebooks UI implementation. Thank you!
