### ISSUE TITLE
Sync Disabled 

### ISSUE THREAD

**Issue by leeo217** [microsoft/vscode#128742]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Syndisabled 

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.08GB free)|
|Process Argv|--crash-reporter-id f02d45c0-76c3-466e-98a8-1188eeb03a04|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
All-Autocomplete|Ati|0.0.23
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.11.0
git-extension-pack|don|0.1.3
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.11
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.7
code-runner|for|0.11.5
beautify|Hoo|1.5.0
path-autocomplete|ion|1.17.1
theme-monokai-pro-vscode|mon|1.1.19
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
vscode-multiclip|sle|0.1.5
sass-indented|syl|1.8.17
vscode-icons|vsc|11.5.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.10.15
vscode-open-in-github|ziy|1.3.6

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What does 'Sync Disabled' mean? Do you see any error or notification? Can it be enabled?
