### ISSUE TITLE
Check for updates always results in "Download Update" even when in latest version (1.58)

### ISSUE THREAD

**Issue by SarveshMD** [microsoft/vscode#128736]
Does this issue occur when all extensions are disabled?: Yes 

- VS Code Version: 1.58
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:
1. Open Visual Studio Code 1.58 on Ubuntu 20.04 LTS
2. Click the gear icon on the bottom left corner
3. Click "Check for Updates..." or "Download Update (1)". Only one of these options will be shown at a time
    - If you clicked Check for Updates, click the gear icon again and you will see "Download Update (1)".
    - If you clicked "Download Update (1)", you will be taken to "https://code.visualstudio.com". 
4. Repeat Step 3 again and again, you will see it never stops giving us "Download Update (1)". 

Note : This problem wasn't there till I updated to version 1.58.

**Comment by joaomoreno** [comment]
Right. On Linux, you either install the deb/rpm/snap and let the system update VS Code. Or you get the archive and the only way to update is to go to https://code.visualstudio.com and download the new package and unzip it yourself. There are no automated updates for the archive package.
