### ISSUE TITLE
Typescript server does not use DOM types

### ISSUE THREAD

**Issue by AgainPsychoX** [microsoft/vscode#128743]
Issue Type: <b>Bug</b>

Typescript server does not use DOM types, even while `tsconfig.json` is set to use `DOM` library and even while it compiles* fine.

1. Create React + Typescript app (with DOM)
2. Try to use base DOM types like `Element`, anything from `@types/react`.
3. It compiles* (providing there is `"lib" ["dom"]`  in `tsconfig.json`), however, VS Code Typescript server does not want to use DOM types.

Typescript version: 4.3.5
React version: `react@16.14.0` / `@types/react@17.0.14` (I don't think I can update major versions, breaking changes to current project). Also, I don't think its react issue since it compiles* well...

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.91GB free)|
|Process Argv|--crash-reporter-id 5ed677a1-ca62-442b-ab0a-0140314bf2c5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

Screenshot:
![image](https://user-images.githubusercontent.com/23557839/125778044-0ec50da9-1317-472d-b00e-c9bba98d7abe.png)

_\* - at the screen I have other issues within the file, but it compiles after I choose to fix those. Yet, the VS Code Typescript server still does not see valid DOM types..._

**Comment by AgainPsychoX** [comment]
I think the issue was there before, I just updated before posting issue just to check maybe new release fix it.

**Comment by IllusionMH** [comment]
What exact problem is? Because it looks like `lib.dom.d.ts` is included (even if from built-in TS version) so "Typescript server does not use DOM types" doesn't look true
![image](https://user-images.githubusercontent.com/1312662/125778821-2b761f61-0e9b-449a-b94b-e920f5080f9a.png)

Do you have typescript package properly installed in workspace?
Do you have workspace configuration to use local TS version instead of built-in? See https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

**Comment by AgainPsychoX** [comment]
> What exact problem is?

It finds and list it (as on your clip from the screenshot), but it does not use them.

> Do you have typescript package properly installed in workspace?

I guess so? It compiles fine usually. Anything I should maybe check?

> Do you have workspace configuration to use local TS version instead of built-in? 

I tried using local TypeScript version `4.3.5`. Before VS Code update it was running the VS Code `4.3.4` (default), after VS Code update it was `4.3.5` - nothing changes.

**Comment by IllusionMH** [comment]
What is exact error because it's not showed anywhere? It will only be listed if used

If variable has bare `Element` type - `value` doesn't exist on it.

**Comment by AgainPsychoX** [comment]
The error, and the variable source:
![image](https://user-images.githubusercontent.com/23557839/125782645-ba1890f0-be84-421e-96be-17df46e6cc27.png)

**Comment by AgainPsychoX** [comment]
Actually, its also refuses to compile :/ 
My bad with assumption that no warning/error listed means it compile.
