### ISSUE TITLE
webview unable to render the svg images in <object> element

### ISSUE THREAD

**Issue by Kxuan** [microsoft/vscode#128714]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.59.0-insider
- OS Version: ArchLinux

Steps to Reproduce:

1. Install `reStructureText` extensions
2. Make directory `/tmp/test`
3. Download `https://github.githubassets.com/pinned-octocat.svg` into `/tmp/test`
4. Open `/tmp/test` in vscode
5. Create a rst file named `test.rst`
6. Fill `test.rst` with the content as below:
```rst
.. raw:: html
    
    <object data="./pinned-octocat.svg" type="image/svg+xml">
    </object>
```
7. Open preview window. If there is a text says `Some content has been disabled in this document`, Click it, choose `Disable`, and reopen preview window.

Expect behavior:
A github logo displays in the preview

Actural behavior:
Nothings displayed in the preview

# Note
This issue has already been report to the extension repo. But it seems a problem with VSCode WebView.

vscode-restructuredtext/vscode-restructuredtext#307

**Comment by mjbvz** [comment]
This is a limitation how we load local resources inside webviews and unfortunately I don't think we can work around it

We use service workers to load local resources but service workers don't see requests to `<object>` or `<iframe>` sources. [This issue](https://github.com/w3c/ServiceWorker/issues/249). To support this, we'd need the service worker spec to be changed and for browsers to adopt this
