### ISSUE TITLE
Python interpreter finding issue, unable to add it.

### ISSUE THREAD

**Issue by debdutta47** [microsoft/vscode#128737]
![interpreter](https://user-images.githubusercontent.com/87472892/125765000-b98294c5-f20a-483a-aba7-d95603ad715c.PNG)

**Comment by CodeCrazy-ywt** [comment]
What's wrong with this? I cannot find anything wrong from your screenshot.

**Comment by debdutta47** [comment]
![Screenshot_2021-07-16-20-29-42-53.jpg](https://user-images.githubusercontent.com/87472892/125968003-8393ab68-fd10-4a56-85d9-33626962d5e8.jpg)

**Comment by debdutta47** [comment]
> What's wrong with this? I cannot find anything wrong from your screenshot.

kindly see it.. Python should be shown here na?

**Comment by CodeCrazy-ywt** [comment]
You can try opening a .py file and see if there are any changes in tbe status bar.

**Comment by debdutta47** [comment]
> You can try opening a .py file and see if there are any changes in tbe status bar.

Okay will try this, Thanks anyway..
