### ISSUE TITLE
Improve long text output rendering

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#128765]
Currently we have a pretty large limit for text output which can be longer than multiple viewports, which is not really accessible as it makes scrolling the notebook editor hard. We need to look into how to improve this experience.

**Comment by DonJayamanne** [comment]
I'd consider updating the existing message to include some information on how the user can view the rest by updating the setting `"notebook.output.textLineLimit": <number> `.
Else users won't know about this.

**Comment by jhoneill** [comment]
> I'd consider updating the existing message to include some information on how the user can view the rest by updating the setting `"notebook.output.textLineLimit": <number> `.
> Else users won't know about this.

I only found out by seeing that post. 

 I'd also suggest that seeing it as one very long line of JSON in another pane might not be the best of all possible ways to unhide it.
