### ISSUE TITLE
CustomDocument dispose() is not called on exit from vscode

### ISSUE THREAD

**Issue by ishche** [microsoft/vscode#128762]
I'm working on a custom editor for remote resources and it's important to me to close the edit sessions at the close of the editor. It seems that CustomDocument dispose() is not called on exit.

It can be reproduced in https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample
If I'll open PawDrawDocument and close the vscode, a dispose method of PawDrawDocument is never called.

**Comment by mjbvz** [comment]
Have you tried using a `deactive` method in your extension? Our APIs generally do not dispose of managed objects such as custom editors when the editor is closed

**Comment by ishche** [comment]
The deactive method seems to solve the problem, but according https://code.visualstudio.com/api/extension-guides/custom-editors

> When the second editor is closed, VS Code again fires WebviewPanel.onDidDispose. However now we've also closed all the editors associated with the CustomDocument. When there are no more editors for a CustomDocument, VS Code calls the CustomDocument.dispose on it. Our extension's implementation of dispose must clean up any resources associated with the document.

And it works fine unless I close the vscode itself.

**Comment by mjbvz** [comment]
Ok, glad dispose is doing what you need

Unless otherwise noted, VS Code will does not call `Dipose` on managed objects when the editor itself is shutdown so I'm going to close this as by-design

**Comment by ishche** [comment]
Just to clarify: Is editor vscode or webview custom editor? And sometimes documents will never be disposed by calling Dispose?
