### ISSUE TITLE
Moving cursor programatically in powershell integrated terminal produces unexpected results

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#128760]
Issue Type: <b>Bug</b>

When I attempt to move the cursor using the curses python library when debugging with Powershell in the integrated terminal, text insertion for my program will appear at the right place (implying that it's working under the hood), but the terminal panel will not accurately reflect the positioning of the cursor. This behaviour doesn't happen in any other terminal I've tried (including Powershell Windows Terminal, Powershell from the start menu, Ubuntu WSL in VS Code terminal, etc), leading me to believe that this is an issue with VS Code's terminal.

To reproduce:
1. Have Python installed on Windows (I was using v3.9)
2. Install the Windows Curses module (`pip install windows-curses`)
3. Run the following Python code in the integrated Powershell terminal. It works when debugging or when manually invoking from the command line.
4. Enter various input. The cursor position will not be accurately reflected when the following keys are pressed: space, left arrow, right arrow. My best guess would be because none of those actions will modify the text (excluding whitespace), and thus VS Code's terminal skips it, leading to the cursor not moving (since it is moved manually by the program through the `stdscr.get_wch(...)` function call).
```py
import sys
import curses

def c_main(stdscr: 'curses._CursesWindow') -> int:
    stdscr.addstr(0, 0, "Press Ctrl+C to quit")
    # Input loop
    while True:
        prompt = "input > "
        inp_row = curses.LINES - 1
        inp_col = len(prompt)
        stdscr.addstr(inp_row, 0, prompt)
        # Get char loop
        inp = ""
        cursor_pos = 0
        while True:
            stdscr.addstr(inp_row, inp_col, inp)
            stdscr.clrtoeol()
            char = stdscr.get_wch(inp_row, inp_col + cursor_pos)
            
            # Keyboard interrupt
            if isinstance(char, str) and char in ['\x03']:
                return 0
            
            # Insert character
            elif isinstance(char, str) and char.isprintable():
                inp = inp[:cursor_pos] + char + inp[cursor_pos:]
                cursor_pos += 1

            # Left arrow
            elif char == curses.KEY_LEFT or char == 452:
                if cursor_pos > 0:
                    cursor_pos -= 1
            
            # Right arrow
            elif char == curses.KEY_RIGHT or char == 454:
                if cursor_pos < len(inp):
                    cursor_pos += 1

            # Backspace
            elif char == curses.KEY_BACKSPACE or str(char) in '\x7f\x08':
                if len(inp) == 0:
                    continue
                else:
                    inp = inp[:cursor_pos-1] + inp[cursor_pos:]
                cursor_pos -= 1
            
            elif char == '\n':
                break
            else:
                stdscr.addstr(4, 0, "Ignored: " + repr(char))
                stdscr.clrtoeol()
        
        # Got input
        stdscr.addstr(4, 0, "Output: " + str(inp))
        stdscr.clrtoeol()

def main() -> int:
    return curses.wrapper(c_main)

if __name__ == "__main__":
    exit(main())
```

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.79GB free)|
|Process Argv|--crash-reporter-id 0e34e492-4ab3-4c70-bb93-29ca874e05c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|13.1.0
todo-tree|Gru|0.0.213
discord-vscode|icr|5.7.0
vscode-nuget-package-manager|jmr|1.1.6
mips|kda|0.0.7
vsc-python-indent|Kev|1.14.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.8.0
vscode-xml-complete|rog|0.3.0
vscode-autohotkey|sle|0.2.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal

**Comment by MiguelGuthridge** [comment]
Here's a recording of the issues. I've got my keypresses up in the top left of the screen (although sadly it doesn't show it when I press multiple times). In the clip, I'm entering text as well as moving the cursor frequently, but the position of the cursor does not change properly unless I am entering text. Hopefully this helps diagnose the issue properly.

![recording](https://user-images.githubusercontent.com/31365175/127767619-c00e257b-2407-4e22-a37f-b27b7b5d3bbd.gif)

**Comment by meganrogge** [comment]
okay let me know when you do. thanks
