### ISSUE TITLE
Drag tab will cause freeze

### ISSUE THREAD

**Issue by ahdung** [microsoft/vscode#128719]
version: 1.58.1 (system setup) - 1.59.0-insider
commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
date: 2021-07-13T06:58:28.115Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.1.7601

Tried:
- --disable-gpu
- disabe all extensions
- create `data` folder make vscode run in portable mode

Drag `Welcome` tab and `Untitled-x` tab no problem, but file tab freeze.

**Comment by deepak1556** [comment]
/gifPlease

Just to confirm you are using the zip package to use the portable mode right ? Portable mode is not supported with system or user installation.

**Comment by ahdung** [comment]
@deepak1556 Thanks for response. I do use zip with `data` folder make portable mode. zip from [here](https://code.visualstudio.com/docs/?dv=winzip&build=insiders).
![recording](https://user-images.githubusercontent.com/12094247/126020744-113ed044-51f6-40b2-985c-b921734891dc.gif)

**Comment by icy-fish** [comment]
Also got this issue, tried to start vscode with `--disable-gpu` option and uninstall all extensions, just open one local file and welcome page in vscode, when draging an editor tab to another, vscode just freezes and end up with 'not responding'

Here's my run env:

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
