### ISSUE TITLE
[intermittent] Window is flickring on the changes tab 

### ISSUE THREAD

**Issue by Shankar-khati** [microsoft/vscode#128767]
Issue Type: <b>Bug</b>

- Click on changes tab(3rd one) from left toolbar .
- Move mouse around the left pane.
- You will able to notice the flickring.
- If not then try same steps on external display

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 23, 18|
|Memory (System)|16.00GB (5.95GB free)|
|Process Argv|-psn_0_77843 --crash-reporter-id ba821a30-283c-4bbe-bc7e-c11040260c67|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nvm|abu|0.0.1
vscode-view-readme|ans|1.0.0
spellright|ban|3.0.58
quick-karma|bla|0.1.1
emoji-commit|cha|2.0.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.0.1
vscode-jest-runner|fir|0.4.44
vscode-test-explorer|hbe|2.20.4
react-native-snippet|jun|0.5.6
lintel|mfl|1.3.4
vscode-docker|ms-|1.14.0
test-adapter-converter|ms-|0.0.10
vsliveshare|ms-|1.0.4568
vscode-react-native|msj|1.5.2
reload|nat|0.0.6
quicktype|qui|12.0.46
karma-problem-matcher|rct|1.0.1
vscode-yaml|red|0.21.1
vscode-paste-and-indent|Rub|0.0.8
vs-code-prettier-eslint|rve|3.0.4
vscode-fileutils|sle|3.4.5
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.14
rdoc-readme|vau|0.0.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by kieferrm** [comment]
Can you pls share a screen recording, I can't reproduce on any of my displays. There is hover feedback on the input box, the section headers etc. but what that looks like depends on your theme.
