### ISSUE TITLE
command 'markdown.showPreviewToSide' not found

### ISSUE THREAD

**Issue by FFLuoyan** [microsoft/vscode#128731]
Issue Type: <b>Bug</b>

Maybe after a update
Suddenly i can't see  the preview of markdown

command 'markdown.showPreviewToSide' not found
command 'markdown.showPreview' not found

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.79GB (9.84GB free)|
|Process Argv|--crash-reporter-id 9938ea84-c283-42ac-b04e-020ef9231d2a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
simple-react-snippets|bur|1.2.3
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vue-format|feb|0.1.8
auto-close-tag|for|0.5.11
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.7
iceworks|ice|1.2.1
iceworks-app|ice|1.0.2
iceworks-codemod|ice|1.0.1
iceworks-config-helper|ice|0.5.5
iceworks-doctor|ice|1.1.1
iceworks-material-helper|ice|1.0.6
iceworks-project-creator|ice|1.0.3
iceworks-refactor|ice|1.0.1
iceworks-style-helper|ice|1.0.1
iceworks-time-master|ice|1.0.2
iceworks-ui-builder|ice|0.3.4
vscode-language-pack-zh-hans|MS-|1.58.8
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscode-wakatime|Wak|14.0.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by FFLuoyan** [comment]
It's work after I unload the extension iceworks-team.iceworks
