### ISSUE TITLE
splitted terminal dont allign

### ISSUE THREAD

**Issue by leobardo-mora-castro** [microsoft/vscode#128788]
Issue Type: <b>Bug</b>

1.- Open a new terminal
2.- Set it to view in Editor
3.- Open a new terminl
4.- Split both terminals
5.- The split line don't allignt between editor terminal and console terminal

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (3.72GB free)|
|Process Argv|--crash-reporter-id e743f953-a023-4345-b46d-1703d004fba4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.1.0
cform|aws|0.0.24
vscode-django|bat|1.6.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.24.2
flutter|Dar|3.24.0
vscode-eslint|dba|2.1.23
vscode-quick-select|dba|0.2.9
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
file-icons|fil|1.0.29
vscode-pull-request-github|Git|0.28.0
terraform|has|2.13.0
vscode-drawio|hed|1.5.0
better-shellscript-syntax|jef|1.1.0
intellij-idea-keybindings|k--|1.4.5
vscode-cfn-lint|kdd|0.19.0
vscode-cloudformation|key|0.0.21
jenkins-doc|Maa|1.7.0
MagicPython|mag|1.1.0
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
mongodb-vscode|mon|0.6.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-remote-extensionpack|ms-|0.21.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
django-intellisense|sha|0.0.2
ayu|tea|0.20.1
python|tht|0.2.3
helm-intellisense|Tim|0.10.0
autocomplate-shell|tru|0.1.1
errorlens|use|3.3.0
footsteps|Wat|0.1.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.16

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
please add a a gif

**Comment by leobardo-mora-castro** [comment]
Does this work?

![out](https://user-images.githubusercontent.com/54635310/126830770-46a4e404-c353-4517-aec7-1b76ffd7a6c0.gif)

**Comment by meganrogge** [comment]
If you want them to align, you can use just the editor area and create a 2 by 2 grid
