### ISSUE TITLE
DownArrow not working

### ISSUE THREAD

**Issue by hhegghei** [microsoft/vscode#128741]
Issue Type: <b>Bug</b>

Hi! My DownArrow is not working properly, I can't move one line down using the down arrow. Think it happened after an upgrade yesterday. Have tried restarting laptop and program. UpArrow is working fine. Have checked Keyboard Shortcuts, but cannot find anything unexpected there either. Except from moving down to the next line, I can use the DownArrow together with other keys (for example Ctrl+DownArrow) to scroll down.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:20:02.397Z)
OS version: Linux x64 5.10.0-1034-oem
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3361)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.30GB (8.44GB free)|
|Process Argv|. --crash-reporter-id 96c69cff-54e5-41c7-bf6e-223c7ba29973|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
toggle-comments|Art|0.3.7
vscode-dbt|bas|0.4.1
bracket-pair-colorizer|Coe|1.0.61
snippet|dev|1.0.1
gitlens|eam|11.6.0
vscode-great-icons|emm|2.1.79
vscode-dbt-power-user|inn|0.5.4
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
vsliveshare|ms-|1.0.4568
jinjahtml|sam|0.16.0
trailing-spaces|sha|0.3.1
plsql-language|xyz|1.8.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by ArturoDent** [comment]
Command Palette: `Developer: Toggle Keyboard Shortcuts Troubleshooting` , clear the `Output` view, and then press a downArrow.  What do you see.  You should see a final line something like this:

`[2021-07-16 12:25:51.376] [renderer1] [info] [KeybindingService]: \ From 16 keybinding entries, matched cursorDown, when: textInputFocus, source: built-in.`

What do you get?

**Comment by hhegghei** [comment]
That helped me find what was wrong, thanks! Had accidentally assigned the DownArrow key as a first key of a shortcut (instead of last) :facepalm: Issue can be closed.

**Comment by ArturoDent** [comment]
Glad it worked - You can close the issue yourself.
