### ISSUE TITLE
How switch account in vscode?

### ISSUE THREAD

**Issue by jackchoumine** [microsoft/vscode#128718]
I wanna change my account  from github to microsoft ,but I dont how to login out my account.

![image](https://user-images.githubusercontent.com/21340150/125733984-da76e3c1-092f-47f4-b484-6e9be5bedf56.png)

I cannot find any switch button， only find "login my account" button.

Hope show the change button in a access place.

I have read docs in vscode website. Found this:
> Switching Accounts#
If at any time you want to sync your data to a different account, you can turn off and turn on Settings Sync again with different account.

I still dont know how to change.

**Comment by TylerLeonhardt** [comment]
@jackchoumine 

> you can turn off and turn on Settings Sync again with different account.

All you have to do is Turn off settings sync which you can by opening the Command Palette and searching for:
![image](https://user-images.githubusercontent.com/2644648/126240540-90de0cc0-2762-48ad-95df-b0ab7cd38852.png)

Then you can turn it back on either here:
![image](https://user-images.githubusercontent.com/2644648/126240617-a168da40-6732-49ee-a3a0-3924faa0fef5.png)
or in the 👤 menu:
![image](https://user-images.githubusercontent.com/2644648/126240638-317e6225-3dfc-421c-8bbe-df8157eab0ec.png)

Hope that helps!
