### ISSUE TITLE
Workbench broken when panels visible in activity bar right on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12876]
![image](https://cloud.githubusercontent.com/assets/900690/18909896/cca3014c-8575-11e6-8ee4-64e835c33c76.png)

**Comment by isidorn** [comment]
@bpasero can not repro - do you see it all the time? Might it be some rendering with the new electron update?

**Comment by bpasero** [comment]
@isidorn wow, only seems to happen when I have the extensions viewlet visible

**Comment by isidorn** [comment]
@bpasero strangely the whole workbench is pushed to the left - so it is not one element inside the workbench that is pushing.

**Comment by isidorn** [comment]
Has nothing to do with the panel work in the activity bad - set "workbench.panels.showInSidebar": false, open extensions viewlet and reload -> broken

**Comment by bpasero** [comment]
@isidorn for some reason the [characterWidthSurveyor](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L150) seems to push the workbench. If I set that element to be hidden I cannot reproduce.

**Comment by isidorn** [comment]
@bpasero that guy is full of content - characters 'a' to measure the length. Let me try to tune that guy somehow...

**Comment by joaomoreno** [comment]
Your `surveyor` is the problem.

![image](https://cloud.githubusercontent.com/assets/22350/18944796/b39f8816-8627-11e6-8810-33ac476644ff.png)

Make sure your `.repl` is `overflow: hidden`.
