### ISSUE TITLE
Inspect a Webview

### ISSUE THREAD

**Issue by nicolasg-da** [Microsoft/vscode#12871]
- VSCode Version: 1.4.0, 1.5.3
- OS Version: 10.11.6

Is there a way to inspect the contents of a Webview?
All I see is an empty object even though there should be some content.

I created a new markdown document with this in it:
```
Markdown
========

1. hi
2. world
```
and then showed the preview.

What I see in the ispector when I select the Webview is this:
<img width="501" alt="screen shot 2016-09-28 at 10 43 48" src="https://cloud.githubusercontent.com/assets/20789770/18906772/3586c200-8569-11e6-9880-58f64b33b99d.png">

I've tried the Shadow-DOM option in the inspector.

Thanks a lot for your help.

**Comment by bpasero** [comment]
I believe you can configure a key for our hidden command to reveal devtools for a webview:

`{ "key": "cmd+b", "command": "_webview.openDevTools" }`

@jrieken fyi
