### ISSUE TITLE
VS Code doesn't handle multiple monitors well

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#128778]
- VS Code Version: 1.58.1
- OS Version: Windows

Reported by @robinsh:
 
"I have 3 monitors. My Surface Book 2 is on the bottom, and I have 2 monitors above the book that are 1020x1920 (or something like that, one of the standard resolutions). When I open VSCode, it shows the surface on the bottom half and the other two monitors as they are. Across 3 screens. Every time. No matter how you opened it last time. I think if you open it on 1 screen, it will do that again, but that’s the only case. Otherwise, every time you open something with VS Code, you have to adjust your screens"

See also:
https://github.com/microsoft/vscode/issues/35148
https://github.com/microsoft/vscode/issues/58220
https://github.com/microsoft/vscode/issues/84164

Also reported by @shsagir

**Comment by deepak1556** [comment]
Can you provide a screenshot of the issue similar to https://github.com/microsoft/vscode/issues/85592#issuecomment-558578837
