### ISSUE TITLE
VSCode won't respect window border limit

### ISSUE THREAD

**Issue by alegrevers** [microsoft/vscode#128758]
Does this issue occur when all extensions are disabled?: Yes/No

I've tried almost every config changes but this bug persists. I'm openned VSCode via WSL terminal (```code .```).

Here is a min-version of settings.json:

```
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.renderControlCharacters": true,
    "breadcrumbs.enabled": true,
    "editor.renderWhitespace": "all",
    "redhat.telemetry.enabled": true,
    "editor.mouseWheelZoom": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "editor.rulers": [
        80,
        120
    ],
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "beautify.config": "",
    "window.dialogStyle": "custom",
    "workbench.editor.centeredLayoutAutoResize": false,
    "window.customMenuBarAltFocus": false,
    "window.autoDetectHighContrast": false
}
```

This bug don't happen in fullscreen or Zen modes, just when I split with other window. My monitor is ultrawide 21:9.

![vscode-bug](https://user-images.githubusercontent.com/56418306/125802987-3d0b9866-0c6b-40da-aef9-a2a8bad85a6e.PNG)

**Comment by deepak1556** [comment]
Can you check if the issue is present with latest stable `1.73` ?

**Comment by gabrielalegrete** [comment]
Hey guys, I tottaly forgot this topic, sorry. After some updates from windows and VSCode, this problem stopped, thanks for trying to help me. Recently I was with troubles with plugins, my VSCode was way to slow and I notice that it was git lens fault, but it's a case for other thread. Thank you again.

**Comment by deepak1556** [comment]
Thanks for confirming.
