### ISSUE TITLE
Codespaces Apollo Server Studio Network Error: unable to reach server

### ISSUE THREAD

**Issue by machooper** [microsoft/vscode#128777]
Issue Type: <b>Bug</b>

This server works if I deploy it or run it locally, I am able to query the GraphQL server without any issues. However if I am running the server in my dev enviroment within a Codespace apollo studio returns this error

```
Network error: unable to reach server

We couldn't reach your server.
The server's response may be missing CORS headers.
To verify, please open Developer Tools and check the console for any CORS related error messages, like “Cross Origin Request Blocked”.
If that is the case, contact your system administrator and add https://studio.apollographql.com to your server's allow-list.
Learn more about enabling CORS 
The server may be not reachable at the provided endpoint. Please double check your configured endpoint URL for typos.
Check the endpoint URL
Is the server currently running?
```

Any idea on how to fix this error?

VS Code version: Code 1.58.1 (Universal) (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1051-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.29GB free)|
|Process Argv|--crash-reporter-id 79f61737-b5de-4063-88f8-69fbb5297293|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1051-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|7.78GB (1.02GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.1
auto-rename-tag|for|0.1.7
codespaces|Git|0.10.10
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
nextjs-snippets|Pul|0.0.3
ayu|tea|0.20.1
vscode-apollo|apo|1.19.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
codespaces|Git|0.10.10
copilot|Git|1.2.1991
vscode-pull-request-github|Git|0.28.0
vscode-graphql|Gra|0.3.16
vscode-placeholder-images|Jak|0.1.0
color-highlight|nau|2.4.0
nextjs-snippets|Pul|0.0.3
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by JellieBeanz** [comment]
What was the resolution for this ?
