### ISSUE TITLE
Cannot push to GitHub FROM VSCode

### ISSUE THREAD

**Issue by ojoshiro** [microsoft/vscode#128748]
Issue Type: <b>Bug</b>

1) Get behind my computer.
2) Commit a change.
3) Push the change to remote.
4) Watch VSCode fumble where every commandline succeeds.
5) Change every possible setting that has "SSH" or "key" in it --> to no avail.
6) Find 10^36 "solutions" for the problem on google but none work.
7) Add 24 SSH keys to your ~/.ssh (Praying has about as much use) and cram them all in GITHub too.
8) Neither GITHub nor VSCode offer an actually working solution. Neither offers a decent way to put the correct data in the correct place either. But as the commandline solution works I assume the problem is on the VSCode side. 
9) Get heavily frustrated and wonder why anno 2021 everybody still sees a commandline as acceptable. I doubt the warp-drive is the limiting factor on building the enterprise. It'll all get stuck on: "Computer, collect my changes, commit them and push them to my Starfleet Academy account"

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (24.29GB free)|
|Process Argv|--crash-reporter-id e3d1450b-2372-4484-8e42-23f227493a21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-model-snippets|ahi|2.0.0
laravel-extra-intellisense|ami|0.6.1
laravel-blade-vscode|ami|2.0.3
shaderlabvscodefree|aml|1.2.8
livewire-docs|aus|2.1.0
vscode-intelephense-client|bme|1.7.1
better-phpunit|cal|1.5.3
livewire-vscode|cie|0.2.8
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|1.2.2
php-debug|fel|1.16.1
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.11
remotehub|Git|0.11.0
vscode-pull-request-github|Git|0.28.0
todo-tree|Gru|0.0.213
phpcs|ika|1.0.5
path-autocomplete|ion|1.17.1
minimal-unity-extensions|jas|0.0.1
laravel-extension-pack|jer|0.1.0
docomment|k--|0.1.20
laravel-snippets|ken|1.2.1
unity-code-snippets|kle|1.3.0
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
laravel-intellisense|moh|0.2.0
csharp|ms-|1.23.13
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cpptools|ms-|1.5.1
php-docblocker|nei|2.1.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
vscode-unitymeta|PTD|0.0.7
view-in-browser|qin|0.0.5
quicktype|qui|12.0.46
laravel-helpers|raf|0.2.2
laravel-artisan|rya|0.0.28
laravel-5-snippets|sac|2.0.1
phpcs|she|1.0.8
shader|sle|1.1.5
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
python|tht|0.2.3
unity-tools|Tob|1.2.12
sort-lines|Tyr|1.9.0
unity-debug|Uni|3.0.2
vscode-phpsab|val|0.0.15
unity-vscode-extension-pack|Ver|1.0.3
bootstrap-v4-snippets|Zac|1.1.3
json|Zai|2.0.2

(2 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
Please provide a gif of VS Code failing and then example of the command line working. It is very hard to fix an issue when the steps are just "it doesn't work"
