### ISSUE TITLE
High GPU usage while running a single task in terminal

### ISSUE THREAD

**Issue by TobiasKrahn** [microsoft/vscode#128775]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
>Version: 1.59.0-insider (user setup)
Commit: 50b3811fdc5b5c80ca516a2edfffedcbd464b033
Date: 2021-07-15T05:13:58.348Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
- OS Version:
>OS: Windows_NT x64 10.0.19043

I'm having an way higher than expected GPU usage (about 16% if you sum up vscode (10%) and dwm.exe (6%)) while having a single task running in the terminal. The usage is caused by the loading animation after the task name. 

![image](https://user-images.githubusercontent.com/16705453/125822965-32ece4b8-812b-4620-b81f-44f90ac0195a.png)

* disabling the animation via dev-tools will get the usage back to normal
* opening a other terminal, so that the sidebar will display the loading animation, will do the same 

Steps to Reproduce:

1. run a task that takes a lot of time (like a watch task or just a sleep cmd executed via npm) 
2. ensure to kill (delete) all other open terminals

**Comment by Tyriar** [comment]
Also this is a watch task, you should mark your task as `isBackground` which will hide the animation as that means the task will not end.
