### ISSUE TITLE
Emmet Extensions Path setting not honored

### ISSUE THREAD

**Issue by calebevans-suitecentric** [microsoft/vscode#128711]
Issue Type: <b>Bug</b>

Hi,

I have been considering switching from Atom to VS Code, but I am having trouble getting VS Code to read my custom Emmet configuration. The expansion of the default abbreviations works fine; the issue is with VS Code is not honoring my "Emmet: Extensions Path" setting. The issue persists even after disabling all downloaded extensions.

I have already reviewed https://code.visualstudio.com/docs/editor/emmet. I have made sure that the paths listed in my "Extensions Path" table are both existing directories containing my Emmet config. I have attached my Emmet JSON files to this issue ([emmet.zip](https://github.com/microsoft/vscode/files/6819649/emmet.zip)). My Extensions Path table is as follows:

```javascript
{
    ...
    "emmet.extensionsPath": [
        "/Users/Caleb/dotfiles/emmet",
        "/Users/caleb/dotfiles/emmet"
    ]
    ...
}
```

As an example, my `profiles.json` in my `emmet` folder specifies that the self-closing tag style to be XHTML:

```json
{
    "html": {
      "self_closing_tag": "xhtml"
    },
    "xml": {
      "self_closing_tag": "xhtml"
    }
}
```

So in Atom, when I type `img` and expand, I correctly get `<img src="" alt="" />`. However, in VS Code, I still get `<img src="" alt="">` (even when the language mode is "HTML"). This implies to me that VS Code is not reading my Emmet configuration properly.

Is anyone else able to reproduce? Please let me know if you need more details.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv|. --crash-reporter-id da0cdd43-ae4c-4a37-bffa-295fbe79e099|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
sca-for-vscode|cal|1.0.0
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
beautify|Hoo|1.5.0
applescript|idl|0.21.0
tabsanity|jed|0.0.11
vs-docblock|jer|1.4.0
svg|joc|1.4.7
cornflakes-linter|kev|0.5.1
AWK|lug|0.0.2
Lisp|mat|0.1.11
remote-ssh-edit|ms-|0.65.7
advanced-new-file|pat|1.2.2
prolog|reb|0.0.4
rewrap|stk|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by rzhao271** [comment]
Does creating a copy of the profiles file and renaming the copy to `syntaxProfiles.json` work?

**Comment by calebevans-suitecentric** [comment]
@rzhao271 Renaming `profiles.json` to `syntaxProfiles.json` alone does the trick in VS Code; no duplicate file required. Even Atom recognizes `syntaxProfiles.json`.

As for my custom Emmet abbreviations which are not recognized, I think I discovered the issue. It appears the `snippets.json` format has changed in Emmet v2.

Per https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets:

> The 2 have been combined into a single property called snippets. See default [HTML snippets](https://github.com/emmetio/snippets/blob/master/html.json) and [CSS snippets](https://github.com/emmetio/snippets/blob/master/css.json)

Following the above fixes that as well. I think I can close the issue now. Thanks very much!
