### ISSUE TITLE
Debug Console: Accept Suggestions on Enter not working

### ISSUE THREAD

**Issue by chopin2256** [microsoft/vscode#128768]
Issue Type: <b>Bug</b>

1.  Go to Debug Console
2.  Type in any object with expected attributes
3.  As attributes are displayed in intellisense, press enter
4.  The command executes instead of autocomplete
5.  Tab will autocomplete, enter will not.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by dmiller-aon** [comment]
Per the release notes this was apparently done on purpose, as people would type what they wanted and hit return, only to have their input unexpectly replaced by the top-level suggestion. I was happy enough to hit the escape key to dismiss the Intellisense box when no correction was desired. The enter key still works to accept the suggestion in the main editing panel, so it is kind of awkward that it doesn't work in the Debug console. It would be nice to be able to control this behavior with a preference - I'm not sure I want to switch to using the Tab key everywhere. I certainly won't use different keystrokes in different panels!

**Comment by chopin2256** [comment]
Oh I see.  Maybe the team can make this an option then.  

- Enter autocompletes for editor (yes / no) - which they have already
- Enter autocompletes for Debug Console (yes / no).

Simple!

**Comment by MaximilianReymann** [comment]
Maybe similar to the editor option ` "editor.acceptSuggestionOnEnter": "on"`, create a new option `"debug.console.acceptSuggestionOnEnter": "on"` ?

Hope this will be added soon.

**Comment by ewerybody** [comment]
Hello! Yeah, I was just baffled by what happens to me! I never complete stuff with <kbd>Tab</kbd>
Why would the behaviour be different from the editor!?
I'd rather have things NOT executed on <kbd>Enter</kbd> anyway and have it <kbd>Ctrl+Enter</kbd> instead.

However: Just bending <kbd>Enter</kbd> to always execute feels **really bad**! There should be some room to customize things and at least optionally enable the old behaviour? I mean I also found myself having stupid suggestions put into the Debug Console via Enter but it was never a problem.

**Comment by isidorn** [comment]
Thanks for your feedback.
More details here on the motivation behind this change https://github.com/microsoft/vscode/issues/108439#issuecomment-871521843

I am open for adding an option in the future, but for now I prefer to keep this open to gather more feedback.

**Comment by isidorn** [comment]
@weinand also feels like a setting should be added.
So let's assign this to August so we introduce a setting
As @bededict-cumberbach  suggested let's use the "debug.console.acceptSuggestionOnEnter": "on" | "off". With `"off"` being the default

**Comment by isidorn** [comment]
To verify:

Set `"debug.console.acceptSuggestionOnEnter": "on"`, type something in the debug console, have some suggestions, press enter and make sure the suggestion is accepted and not evaluated.

Set `"debug.console.acceptSuggestionOnEnter": "off"`, type something in the debug console, have some suggestions, press enter and make sure the current input is evaluated and the suggestion is ignored.

**Comment by ewerybody** [comment]
Nice! Maybe when this is back we can try to find solutions to mitigate the initial issue lead to this change. 🤔
Like said: I also had the problem with adding suggestions when I wanted only what I just typed ... But that can also happen in the text editor! So what makes it worse in the debug console??!

**Comment by eliyahu2** [comment]
That would be great to have an option to autocomplete on "Enter" ... Thanks!

**Comment by ewerybody** [comment]
Thanks again for the option! I feel **super relieved** now that I don't have to stress myself to remember pressing <kbd>Tab</kbd> pcheeew 😅
