### ISSUE TITLE
Outdated extensions are not removed anymore

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12874]

**Comment by roblourens** [comment]
Not sure how to verify...

**Comment by joaomoreno** [comment]
Remember those multiple versions of the same extension in your extensions folder? They should be gone now :)

**Comment by roblourens** [comment]
I thought it sounded like that, but I'm still seeing that. With a clean extension folder, I update an extension, then have two. And when I uninstall the extension, it only removes the latest.
![sep-30-2016 09-42-13](https://cloud.githubusercontent.com/assets/323878/18999400/39b9a6b4-86f2-11e6-9d79-32833d35f8ef.gif)

**Comment by joaomoreno** [comment]
Can you file an issue for not removing all versions on update?
