### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by alexeychikk** [microsoft/vscode#128747]
Issue Type: <b>Bug</b>

Trying to checkout any branch or perform any git operation from VS Code results with the following (or similar) error:
```
git checkout -q -b external-api --no-track HEAD
env: node: No such file or directory
```

Performing git operations from terminal works just fine. Yesterday everything was ok, today I restarted my PC (probably VS Code auto-updated itself) and this error started to show up. 

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 7|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 613e3682-12d8-481e-b2c1-35d685f31a20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
html-snippets|abu|0.2.1
color-info|bie|0.6.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vscode-jest-runner|fir|0.4.44
intellij-idea-keybindings|k--|1.4.5
git-graph|mhu|1.30.0
vscode-docker|ms-|1.14.0
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
open-html-in-browser|pea|2.1.6
material-icon-theme|PKi|4.8.0
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.10.2
pdf|tom|1.1.0
highlight-matching-tag|vin|0.10.1
change-case|wma|1.0.0
unsaved-files-vscode|wra|2.1.1
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by alexeychikk** [comment]
I've downloaded the previous version of VS Code and it doesn't have this bug.

**Comment by happycollision** [comment]
Seems related to this: https://github.com/typicode/husky/issues/912#issuecomment-885071627
