### ISSUE TITLE
lineNumbers: 'off' still renders a lineNumber div

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#12879]
1. Open debug repl input or output window
2. Notice how all the text is indented
3. Both repl input and output have `'lineNumber': 'off'` - however the div for line numbers still gets rendered which indents the text
4. This also happens when you simple set `'editor.lineNumbers': 'off'`

Probably caused by Alex's line number refactoring to support relative line numbers. Investigating...

fyi @dbaeumer

**Comment by isidorn** [comment]
@joaomoreno please code review

**Comment by alexandrudima** [comment]
@isidorn Nice catch! Thanks for the fix!

**Comment by octref** [comment]
Latest master with Vim extension is still broken, no matter `editor.lineNumbers` is on or off:

![image](https://cloud.githubusercontent.com/assets/4033249/19160831/30617c1e-8ba6-11e6-9872-600b6e9f0313.png)

**Comment by isidorn** [comment]
@octref I do not see this.
What do you mean latest from master - on what commit are you? Are you running vscode out of source. Or is this the insider version - if yes what exact version it is?

**Comment by octref** [comment]
@isidorn Do you have Vim extension?

**Comment by isidorn** [comment]
@octref ok now that I enable the vim extension it I see the issue you are mentioning. So it is happening on insiders. Will investigate tomorrow morning.
Might it be that the vim extension is somewhere explictly setting all editors to show line numbers?

**Comment by isidorn** [comment]
@octref the issue you found is not the same as the original issue here.
After debugging a bit the issue is that the vim extension sets editor options to be lineNumbers: true for each editor - even the debug repl.
The only place where I found that the vim extension is setting editor options is [here](https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L1197)
Will investigate more tomorrow.


![screen shot 2016-10-06 at 23 40 08](https://cloud.githubusercontent.com/assets/1926584/19171949/b797fc98-8c1f-11e6-9341-fc39b831edbf.png)

**Comment by octref** [comment]
@isidorn Sorry was on a meeting. I imagine extensions shouldn't be able to do that, and debug repl shouldn't be in the list of editors vim extension could touch on.

**Comment by isidorn** [comment]
Yes there seems to be two issues here: 
1. output channels and repl input show up as active editor https://github.com/Microsoft/vscode/issues/10956 @jrieken can comment more
2. When vim extension asks for active editor options [here](https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L1191) it gets lineNumbers: 1, and sends it to vscode which transforms it to lineNumbers: 'on' [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadEditorsTracker.ts#L260)

**Comment by isidorn** [comment]
The problem seems to be that the mainThreadEditorTracker reads the options of the repl input [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadEditorsTracker.ts#L314) before the configuration is set. So by default it takes the lineNumbers: true

**Comment by isidorn** [comment]
@alexandrudima please review

**Comment by alexandrudima** [comment]
@isidorn Nice catch again! I seem to be writing decent code, but in the wrong position :).

**Comment by isidorn** [comment]
@alexandrudima hahah. Thanks dude - cherry picking it
