### ISSUE TITLE
Terminal stuck after killing it

### ISSUE THREAD

**Issue by shreyash07cod** [microsoft/vscode#128752]
After any file execution in terminal when i try to kill the terminal it doesn't get kill, then running the program again doesn't run on the terminal.
![Screenshot (338)](https://user-images.githubusercontent.com/72395959/125795430-410709a1-7c65-4c45-927f-e4faf01b4568.png)

**Comment by meganrogge** [comment]
/duplicate #128264 will be fixed in the recovery build we release today
