### ISSUE TITLE
Adding folders via Drag & Drop does not retain folder order

### ISSUE THREAD

**Issue by matkatmusic** [microsoft/vscode#128780]
Issue Type: <b>Bug</b>

Drag a group of folders from Finder on OS X into a Visual Studio Code window. 
In previous versions of Visual Studio code, the folders would be added in alphabetical order to the Explorer in VSCode. 
In the latest version, their order is random. 

I have attached a few screenshot showing the folders I have dragged in to the VSCode window, and the way they end up being ordered in VSCode's Explorer. 

<img width="936" alt="Screen Shot 2021-07-15 at 10 49 39 AM" src="https://user-images.githubusercontent.com/2929847/125833995-d9d5f60b-1efc-4aa6-b105-1f8095b0300f.png">

<img width="914" alt="Screen Shot 2021-07-15 at 10 51 13 AM" src="https://user-images.githubusercontent.com/2929847/125834185-01de4b3f-7f52-44cf-85bd-a2b56edab495.png">

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (14.15GB free)|
|Process Argv|-psn_0_9439488 --crash-reporter-id b7b14ef3-b8f3-4bb9-997b-7df296b8766a|
|Screen Reader|no|
|VM|22%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
This can be controlled using the 
`explorer.sortOrder` and the `explorer.sortOrderLexicographicOptions` settings

**Comment by matkatmusic** [comment]
It was set to the default order, and default lexicographic order.  It seems like the sort code for drag-and-drop operations doesn't take into account numbers that appear in the file or folder name.
