### ISSUE TITLE
VScode v1.58.2 won't start unless "--no-sandbox" or "--disable-setuid-sandbox" is given

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#128782]
The title explains it well.

installed VScode using the tarfile (code-stable-x64-1626303100.tar.gz)

OS: CentOS Linux release 7.9.2009 (Core)

**Comment by sweettyler** [comment]
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 3.10.0-1160.31.1.el7.x86_64

**Comment by kieferrm** [comment]
Pls see https://github.com/microsoft/vscode/issues/128706#issuecomment-880318475.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/128331
