### ISSUE TITLE
Files with same name get overwritten when editing only one of them

### ISSUE THREAD

**Issue by TimLiu1** [Microsoft/vscode#12875]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 一个同名文件，内容不同，修改一个文件，宁外一个同名文件内容被覆盖成我们修改的那个文件了，文件系统自动修改名称
2.

**Comment by octref** [comment]
Can you use English to communicate in the repository. Thanks.

Which VSCode version are you using and which OS are you using?
As far as I know Windows/Mac/Linux doesn't allow you to have two files with same name in the same place.

**Comment by octref** [comment]
Are you by any chance using this feature? https://github.com/Microsoft/vscode/issues/12896

**Comment by octref** [comment]
Closing. Feel free to reopen if you can provide more details.
