### ISSUE TITLE
Trust prompt for file already in trused folder

### ISSUE THREAD

**Issue by ltomuta** [microsoft/vscode#128720]
Issue Type: <b>Bug</b>

I don't have the fine grain trust control detailed in https://code.visualstudio.com/docs/editor/workspace-trust#_selecting-a-parent-folder 
(A/B testing?) so I expect that when a folder is added to the trusted folders list, this trust applies to all files created under it, including in subfolders.

VSC is currently behaving oddly, trusting some files from there and prompting whether I trust some other files. Makes no sense.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (4 x 3691)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.53GB free)|
|Process Argv|C:\\Users\\ltomuta\\ownCloud\\WIP\\ThermoSomething Philips\\Baza S1.nc --crash-reporter-id c4010f99-c625-4d7b-be71-bd78ca011273|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
hsm-post-processor|Aut|3.5.4
bracket-pair-colorizer-2|Coe|0.2.1
vscode-jq-playground|dav|4.2.0
gc-excelviewer|Gra|3.0.42
vscode-edit-csv|jan|0.6.0
jq-syntax-highlighting|jq-|0.0.2
pretty-formatter|mbl|0.2.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
remote-wsl|ms-|0.58.2
vscode-react-native|msj|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by niruiyu** [comment]
I confirm that I am having the same issue even with 1.58.2.

**Comment by sbatten** [comment]
@ltomuta can you please detail your folder structure and provide examples of your trusted paths and paths you are still being prompted about? without this information, it will be difficult to diagnose the issue. thanks

**Comment by ltomuta** [comment]
I use Fusion 360 to generate .NC files for CNC machines. They are being
created in various folders (order numbers) under one folder named WIP.
Fusion opens VSCode after each NC file is created/updated.

This WIP folder is set as trusted. I do not have options in the UI to
specify that trust should be extended over all files and folders under it.
So I assume that to be default.

Some files from under WIP open in VSCode in trusted mode and then suddenly
some other files created somewhere under WIP trigger the trust prompt in
the same VSCode window/instance.

joi, 5 aug. 2021, 17:58 SteVen Batten ***@***.***> a scris:

**Comment by ltomuta** [comment]
Ok, in my case it seems that the error was between chair and keyboard. In my scenario two files are created with similar names and the one that was being opened with prompt was not actually the one I was seeing in the trusted folder. So the prompt to grant trust did actually make sense.
