### ISSUE TITLE
Allow customizing sidebar file rows size (height)

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [microsoft/vscode#128724]
I have a feature request about the sidebar in VS Code. The rows size can't be customized without some experimental extension called Customize UI.
I hope you can add some property to the settings of vs code that allow for changing the height of the rows in the sidebar.

Here is what I mean:
| Before | After |
| ------- | ------ |
|   <img src="https://user-images.githubusercontent.com/41989385/125747489-24f6055e-3c88-4f8e-be36-d232e9137858.png" />    |     <img src="https://user-images.githubusercontent.com/41989385/125749275-51fa9201-5b76-4b21-b351-2580640ad500.png" />     |

So, what are your thoughts? 😁

**Comment by DeeparthGupta** [comment]
+1

**Comment by Kitllers** [comment]
As professional code master, this is am amazing project. I advise to take it into consideration.
