### ISSUE TITLE
Allow VSCode Git to use GIT_AUTHOR_NAME / GIT_AUTHOR_EMAIL and GIT_COMMITTER_NAME / GIT_COMMITTER_EMAIL

### ISSUE THREAD

**Issue by therealgilles** [microsoft/vscode#128704]
I have a repo used by multiple users where it is desirable to commit changes (instead of using a local repo and use pull requests). The way it is setup right now is that there are no user.name or user.email set in the git config. Instead the GIT_AUTHOR_(NAME|EMAIL) and GIT_COMMITTER_(NAME|EMAIL) are passed as environment variables when a user logs in.

When using VSCode remote ssh to access the related server, using Git on the shell command line works as expected. But when using Git from inside VSCode, it does not pick up the environment variables. It would be great if this setup could work. I tried to set the variables in terminal.integrated.env.linux but that did not seem to do the trick.

**Comment by rodja** [comment]
I discovered that providing `"git.requireGitUserConfig": false` in the settings lets Git inside VSCode discover the required infos by other means (for example the mentioned environment variables). See https://github.com/microsoft/vscode/issues/114433

**Comment by lszomoru** [comment]
Given that this behaviour can be controlled through the `git.requireGitUserConfig` setting, I will go ahead and optimistically close this issue.
In case the setting does not provide the desired functionality please feel free to reopen the issue. Thank you!
