### ISSUE TITLE
Feature request: add ability to manually check for updates

### ISSUE THREAD

**Issue by ZaJarv** [Microsoft/vscode#12873]
Related with this #12817, it will be cool if there will be ability to have full control over app update process. I mean disable automatic updates but have ability to check for updates manually.

Right now I need to go in "User Settings", enable automatic update, restart VSCode, update VSCode, go to "User Settings" again and disable automatic updates. Over complicated, isn't it.

And we can see from many other apps, many of them have such ability to disable automatic updates, but preserve ability to check for updates manually (or install them in other time, if user wants this).

**Comment by joaomoreno** [comment]
We made this choice because we always want our users as much on the latest as possible.
