### ISSUE TITLE
Icons are no longer colored

### ISSUE THREAD

**Issue by canersnli** [microsoft/vscode#128798]
## Environment data

-   VS Code version: 1.59 Insiders
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1033311975
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A  local

## Expected behaviour

Colored icons like I see while editing on .py file
![renkli](https://user-images.githubusercontent.com/70806315/125911264-04b0d625-36b8-4688-bdfe-fd8d6885d6b1.png)

## Actual behaviour

All icons are gray on jupyter notebook
![color](https://user-images.githubusercontent.com/70806315/125868179-b8606a20-61ce-4def-be3e-fc2a4120a36f.png)
## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by misolori** [comment]
I believe this is a result from https://github.com/microsoft/vscode/issues/126514, will need to add a css class to inherit icon colors

**Comment by misolori** [comment]
This should be fixed now:

<img width="379" alt="CleanShot 2021-07-16 at 08 51 45@2x" src="https://user-images.githubusercontent.com/35271042/125974933-47450545-fba9-41aa-9728-90a7a1f36588.png">

cc @jrieken
