### ISSUE TITLE
Format On Save Is Triggered After Writing Content To Disk (Insiders)

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#128730]
![recording](https://user-images.githubusercontent.com/2931520/125753461-b82e90c8-6080-4fe0-9ce2-4c54f6bd6e91.gif)

I can reproduce this when only Prettier is enabled.
I cannot reproduce this in VS Code stable.

In the Gif, I only hit `Space`, then `Ctrl + S`, then `Ctrl + S` again.

You can see that you have to trigger save twice.

**Comment by jrieken** [comment]
> I can reproduce this when only Prettier is enabled.

Prettier bug? Please try with the builtin TS formatter

**Comment by hediet** [comment]
the same happens with the builtin ts formatter.

**Comment by jrieken** [comment]
caused by https://github.com/microsoft/vscode/pull/127849

**Comment by jrieken** [comment]
Misses awaits from calling [`formatWholeFile`](https://github.com/microsoft/vscode/blob/d1a971fd525d18c1ed5d31a7f83e09b7921635ef/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L268)
