### ISSUE TITLE
Add PowerShell 5 to Integrated Shell profiles

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/vscode#128728]
Please add PowerShell 5 to the integrated shell profiles. There are many use-cases or modules that still required PowerShell 5.

The `PowerShell (Default)` you see in the screenshot refers to PowerShell 7.

![image](https://user-images.githubusercontent.com/2971735/125752370-f8d1dd29-33da-4d03-9e08-298937bc7c59.png)

**Comment by GilShoshan94** [comment]
Hi,

I had the same issue.
Here is my solution:

In the user `settings.json`, add this:
```jsonc
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "terminal.integrated.profiles.windows": {
        "PowerShell 5": {
            "path": [
                "${env:windir}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
            ],
            "args": [],
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Git Bash": {
            "source": "Git Bash"
        }
    },
```

Now I have PowerShell 5 a well:
![image](https://user-images.githubusercontent.com/29143941/125786022-b0224ecc-8c93-4a00-925d-189364e8a10d.png)


Off course you can set the default to PowerShell 5 ( I did to the CMD in my config ).
Just change this line
`"terminal.integrated.defaultProfile.windows": "Command Prompt",`
to
`"terminal.integrated.defaultProfile.windows": "PowerShell 5",`

**Comment by danielniccoli** [comment]
Thank you. It would be great if PS5 could be added as a default, just like PS7 is, when it's installed. It shouldn't be something I have to add manually on computer.

**Comment by GilShoshan94** [comment]
I think Microsoft is pushing PS7.

Also, if I understood correctly, PS5 is not developed anymore, just supported.
(From Wikipedia : _PS5 is the last supported Windows PowerShell version._)

The big advantage of PS7 is that it's cross platform, which is a great !
Also, I think Windows 11 comes with it by default.

(From Wikipedia : _The focus in development was to make PowerShell 7 a viable replacement for Windows PowerShell 5.1_)

**Comment by danielniccoli** [comment]
This isn't a discussion about replacing PS 7 in VScode. It's about adding PS5 as a built-in choice.

PS 5 is still the default in Windows 11 and Server 2022, mainly due to the support lifecycle. And will be supported for at least the next 7 years.

The point is, there are many modules, even developed directly by Microsoft ([AzureAD](https://docs.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0)) that **require PowerShell 5** and **do not support PowerShell Core**. Many scripts rely on those modules and VSCode should come with a pre-configured PS5 terminal to support administrators and system engineers who run and maintain Azure AD.

**Comment by Tyriar** [comment]
It's already detected automatically, we don't add it to the list as it's really old at this point. To get it in your list the easiest way is to run select default profile:

![image](https://user-images.githubusercontent.com/2193314/127160273-ae1b3b09-672e-4505-b2cc-def77e3474f8.png)

Then select it:

![image](https://user-images.githubusercontent.com/2193314/127160338-3a9d8eab-62eb-4aad-b229-062853760720.png)

This will set it as the default and add it to your list of profiles, you can then switch the default if you want.
