### ISSUE TITLE
Highlighting for custom types in html script tag

### ISSUE THREAD

**Issue by FRoith** [microsoft/vscode#128727]
I am developing roll20 Character sheets in vscode, and they use a custom type for their script tag, "sheet/worker".
It would look something like this:
```html
<script type="text/worker">
on('sheet:opened', function() {
    console.log("Hey!");
});
</script>
```
It uses javascript, so it would be nice if there could be a setting for custom types and corresponding languages in the html Language Features server, and I imagine there are other unsupported or custom types other people would have uses for.

**Comment by aeschli** [comment]
You mean like a setting where you could list additional script types. That would be nice, but not syntax highlighting is based onTextMate grammars which are static files and don't have the concept of variables.
TextMate has a mechanism to inject additional rules: Grammar injection. Extension authors can add such rules. 
https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example is an example for this.
