### ISSUE TITLE
The "Search" feature fails to find matches in files that contain NULL characters unless those files are open in the editor.

### ISSUE THREAD

**Issue by gfrung4** [microsoft/vscode#128795]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 Pro, 20H2

Steps to Reproduce:

1. Open a folder with some files in it that contain `NULL` characters.
2. Press CTRL + SHIFT + F to search in "all" files and search for a string you know is in the files with `NULL` characters.
3. Note that the files are not found as expected.
4. Open one of the files and repeat the search.  It is now found.

**Comment by roblourens** [comment]
These files will be detected as binary files and not searched. This is a typical thing to do. Why do you have text files with null characters in them?

**Comment by gfrung4** [comment]
I am searching log files that were collected over a serial port; sometimes there are corrupt characters at the moment the port was disconnected.  The files are otherwise plain text.

When attempting to open a binary file in Visual Studio Code a warning is usually shown, however this warning is **not** shown when attempting to open my log files, which led me to believe they were plain text.  I only found out about the `NULL`s (which were near the end of very long files) by chance.

![image](https://user-images.githubusercontent.com/1622067/126002488-a92ec1dd-12ec-4f32-aa47-92112339b601.png)

I did some digging and determined Visual Studio Code will only show that "binary file" warning if the `NULL` falls in the first 512 characters.  It must not go through the whole file for performance reasons.  But, according to your response, the "Search" feature considers a file "binary" if it finds a `NULL` anywhere in it.

This is inconsistent and contributed to my confusion: parts of Visual Studio Code define "binary file" differently.  But I totally get the technical reasoning behind it: when opening a file you don't look through the whole thing to make it quick, but when searching a file you're already looking through the whole thing so you might as well check for non-printable characters throughout.

Sadly, after reviewing the facts here, I'm not really sure there's anything *objectively wrong* with that approach.

Yesterday when I was trying to search through these log files and wasn't getting any results I was very frustrated with Visual Studio Code for not finding what was obviously there.  There was no indication within Visual Studio Code that these files were considered binary.  Clicking to open the files opened them normally without any warnings.

But, me being frustrated isn't a bug.

It might point to a possible improvement to user experience though.  A bit of text on the interface: "234 binary files skipped" would have saved me an hour of frustration!

**Comment by roblourens** [comment]
You are exactly correct in your analysis. Another aspect is that search results are provided by a third party tool, ripgrep, which doesn't tell us about binary files it found, so it's hard for me to improve this. Sorry for the frustration, but I'm not sure that I can do anything to improve this case.
