### ISSUE TITLE
Disabling `Workbench › Editor: Enable Preview From Quick Open` has no effect

### ISSUE THREAD

**Issue by selrond** [microsoft/vscode#128733]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.58.1
- OS Version: MacOS Catalina 10.15.7 - Darwin x64 19.6.0

Steps to Reproduce:

https://user-images.githubusercontent.com/6603389/125759741-44db52f2-bca2-40eb-b88d-f5251551c6c0.mp4

**Comment by Elton47** [comment]
I confirm this, v1.58.1

**Comment by Elton47** [comment]
Also happens when using the right arrow, to open multiple files from Quick Open, they are opened in "preview" mode.

**Comment by lramos15** [comment]
I can reproduce this in 1.58.1 but not in the insiders version. Please download insiders https://code.visualstudio.com/insiders/ and give it a try. If it works there it means the next release will include this fix if not please let me know.
