### ISSUE TITLE
Search in terminal will type double words.

### ISSUE THREAD

**Issue by syvshc** [microsoft/vscode#128821]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. open vscode
2. ctrl+` to open terminal
3. ctrl+f to open "search window" and type. 
Here is a GIF to show :
![vscode](https://user-images.githubusercontent.com/38098591/125913529-5262b132-4508-4ef0-bc13-784d54f359f8.gif)

**Comment by zeeforumcompany** [comment]
Working fine in version 1.58.2
Please make sure you have updated version of VS Code and you disabled all the extensions.

Thank You

**Comment by meganrogge** [comment]
I can't reproduce this? @Tyriar

**Comment by Tyriar** [comment]
I can't either
