### ISSUE TITLE
Terminal In Editor: Ctrl+PageUp/PageDown goes to unexpected area

### ISSUE THREAD

**Issue by avivey** [microsoft/vscode#128819]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.58.2 / c3f126316369cd610563c75b1b1725e0679adfb3 / x64`
- OS Version: `Windows_NT x64 10.0.19043` (with Remote to `Linux x64 5.4.0-77-generic`)

Steps to Reproduce:

1. Have several editor tabs open
1. Open terminal in the Editor area 
2. Have this terminal focused
3. press Ctrl+PageDown (or pgup) 

* Expected: next Editor tab gets focus
* Actual result: a terminal in the Terminal area gets focus. 
If the terminal area is hidden, it gets un-hidden.
If no terminal exists there, one is created and gets focus. 

I suspect this happens because the keyboard binding for "next terminal" takes precedent over "next editor":
![image](https://user-images.githubusercontent.com/1530242/125907020-5f657c47-11b5-482a-8261-972ba2765eff.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by avivey** [comment]
Yeah, looks fine on Insiders. Thanks!
