### ISSUE TITLE
Interface to view full variable values in separate window

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#128851]
Hello. Maintainer of https://github.com/xdebug/vscode-php-debug here. When inspecting variables the DBGp implementation (Xdebug debug protocol) does not transfer whole property values, but only the first 1024 bytes. So longer strings get truncated.
There is however a protocol level command to fetch the whole data.

It would make sense to give the user an option to view the full string value of a property, something like VisualStudio has:

![image](https://user-images.githubusercontent.com/2456026/125956656-979741df-4920-4b4c-ab70-8bd3ef2bd0fe.png)

Proposing to use DAP Evaluate Requests context value "detail".

**Comment by weinand** [comment]
IIRC, VS Code already uses the `evaluate` request to get the full string.
@isidorn can you provide more details?

**Comment by zobo** [comment]
The only way I found so far to trigger a DAP request for variable is click the "Copy Value..." context menu.
![image](https://user-images.githubusercontent.com/2456026/126292216-4ec8dc1e-cfd0-4b78-a8f0-db1c8dbda3b6.png)

Since I don't set the `supportsClipboardContext` CAP I get context `variables`.

```
-> evaluateRequest
{
  command: 'evaluate',
  arguments: { expression: '$aVeryLongString', frameId: 1, context: 'variables' },
  type: 'request',
  seq: 20
}
```

If I do set that CAP I get a different context.

```
-> evaluateRequest
{
  command: 'evaluate',
  arguments: { expression: '$aVeryLongString', frameId: 1, context: 'clipboard' },
  type: 'request',
  seq: 20
}
```

That, I think, is expected. What is the `variables` context used for besides "Copy Value..."?

Are there any plans to implement a "Details" window?

Thank you.

**Comment by isidorn** [comment]
Sorry for the slow response I was on vacation.
There are no plans to implement the "Details" window. Maybe this could be contributed by your extension using a custom tree?

And yes we currently use the `evaluate` only for "copy value". 
Here's where the context is computed https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/variablesView.ts#L440
So you can follow the flow and look at references to figure out how is the `context` used.
