### ISSUE TITLE
[Test Explorer] The behavior of resolve children in test explorer is strange

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#128826]
Version: 1.59.0-insider (user setup)
Commit: 50b3811fdc5b5c80ca516a2edfffedcbd464b033
Date: 2021-07-15T05:13:58.348Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

https://user-images.githubusercontent.com/6193897/125920715-63362cd5-ab95-4506-a4b6-ba61e8fd7094.mp4

What's the above video shows are:

1. Triggered a test run from `junit5.cucumber`
2. A child `CucumberTest` is found and be run
3. During test running, some child items are added to `CucumberTest` and also test results are applied to them.
4. When user expand the node `CucumberTest` to see the test results, VS Code triggers the `resolveChildrenHandler`, since the children are only available during test run, no test items is discovered and the children are removed(considered as out-of-date).

Does that mean VS Code will call `resolveChildren` if the item has never been resolved before?

**Comment by connor4312** [comment]
It sounds like the CucumberTest node should set `canResolveChildren` to false, right?

**Comment by jdneo** [comment]
Hmm, the `CucumberTest` still needs to set `canResolveChildren` to true.

The definition of it looks like:

```java
@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources")
public class CucumberTest {}
```

In JUnit's test discovery rules, if a class is annotated with `@RunWith`, that means it's a testable class thus might have testable method children.

While this is a special case, the children of `CucumberTest` are generated during test run (Not discovered by visiting it's AST). In my previous implementation, All the children who are not in the result of `resolveChildren()` will be removed -- considered as out-of-date.

Now I changed the logic -- All the children which are dynamically generated during running test will be only be removed before a new test session starts.

I think this change is valid because:

- Users may still need to see the result of those dynamically generated items when they are navigating in test explorer
- When a new test session starts, the dynamically generated test items might be different because the code is different since last test session, so they should be removed.

By making the above change, the issue is gone. Sorry for the false alarm. Will let you know if I have more question regarding this.
