### ISSUE TITLE
multiline tabs shift when focused because of editor action bar

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/vscode#128867]
Issue Type: <b>Bug</b>

With multiline tabs enabled, the layout can shift when taking / leaving focus. This is caused by the "top right" editor actions icons appearing and disappearing.

Related: https://stackoverflow.com/questions/47266613/vscode-hide-top-right-icons

![editor icons shift](https://user-images.githubusercontent.com/18034092/125996030-fb299eb5-4618-48b5-acf5-dc32c79ebabd.gif)

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 4.15.0-147-generic
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3911)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.56GB (0.60GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 60fa2716-04d8-4f22-9f87-5d74c8c60d72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
comment-tagged-templates|bie|0.3.1
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.6.0
gc-excelviewer|Gra|3.0.42
material-theme|zhu|3.10.16

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by matthias-ccri** [comment]
Yeah, this is pretty bad when you're switching between editors.

You try to place your cursor or double-click a word, and it shifts on you.

![shift](https://user-images.githubusercontent.com/18034092/125996920-3fe5975e-8e4c-4dd0-b72a-a029218cd3ee.gif)

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by matthias-ccri** [comment]
https://github.com/microsoft/vscode/issues/115136
