### ISSUE TITLE
tab size - bug

### ISSUE THREAD

**Issue by revythas** [Microsoft/vscode#12880]
- VSCode Version: 0.2.3
- OS Version: ubuntu 16.04 lts

Steps to Reproduce:

1. Open a .py file
2. At the end of for-loop line, e.g.(for i in x:), press enter. The bug is that the tab size is not correct. Tab size is the double of your actual tab.

**Comment by joaomoreno** [comment]
In python, after a for-loop line, the line should indent.

```python
for i in x:
  # <- should be here
```

Are you saying that it indents the double? Can you show a screenshot? Recording?

**Comment by ioakim92** [comment]
I give an example:
When i write the "for i in range(10):" and press enter, the editor add the "    	print i".
the problem is that the "tabs" of  "    	print i" consisted by:
4 spaces + 1 tab(size=4). That is not correct. Should be only 1 tab.
for i in range(10):
    	print i

so it sould be:
for i in range(10):
    print i

**Comment by revythas** [comment]
I give an example:
When i write the "for i in range(10):" and press enter, the editor add the " print i".
the problem is that the "tabs" of " print i" consisted by:
4 spaces + 1 tab(size=4). That is not correct. Should be only 1 tab.
for i in range(10):
print i

so it sould be:
for i in range(10):
print i

**Comment by joaomoreno** [comment]
Does it reproduce with `--disable-extensions`?

**Comment by revythas** [comment]
Now, with "code --disable-extension vscode-icons",  it works fine. Thanks!!

**Comment by joaomoreno** [comment]
You need to find out which extension is breaking you and file the bug in their issues page.
