### ISSUE TITLE
Profiling a jest test fails when stopping profiling

### ISSUE THREAD

**Issue by jpgualdarrama** [microsoft/vscode#128861]
Issue Type: <b>Bug</b>

1. Create a javascript jest test.
2. Put a breakpoint on the first line of your test file, outside the body of any it() or test() functions. Put a second breakpoint later in the file in the body of a it() or test()
3. Run the test file.
4. In the Call Stack pane of the Run and Debug tab, hover over the Jest application.
5. Click the "Take Profiling Performance" button.
6. Select "CPU Profile".
7. Select "Pick Breakpoint".
8. Select the second breakpoint that was added earlier. Click OK.
9. Allow the test to run to the second breakpoint.
10. Open the Developer Tools.
11. Observe the following in the Developer Tools Console: "Error: Line Numbers must be >= 1"

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.16GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/jonpaul/code/javascript/PokeFarmQoL --remote=wsl+Ubuntu-20.04 --crash-reporter-id 25155436-c4b6-4224-8424-f945ae1d40a6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|6.06GB (3.62GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.12.12
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.13.0
vscode-eslint|dba|2.1.23
gc-excelviewer|Gra|3.0.42
vscode-lua-format|Koi|1.3.8
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.3
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
html-fmt-vscode|Nik|0.7.2
vetur|oct|0.34.1
luacheck|rog|1.0.0
bash-debug|rog|0.3.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by jpgualdarrama** [comment]
![image](https://user-images.githubusercontent.com/7121719/125984972-1ee4c68f-e9fc-4e91-8c8b-e66ffff2baa8.png)

**Comment by connor4312** [comment]
I [can't repro this](https://memes.peet.io/img/21-08-d8f5d422-0ebf-49fe-86ad-4eda9a056b12.mp4), using plain Jest, or Jest with Babel+TypeScript. Can you share a complete sample where it happens or more information about the steps you're taking?
