### ISSUE TITLE
Native Notebooks - Can't tell cells apart

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#128885]
Our survey monkey feedback indicates that users are still having a hard time understanding where cell boundaries begin/end. This makes it difficult for them to differentiate between markdown and code cells, input and output parts of the cell. 

May or may not be related to https://github.com/microsoft/vscode/issues/125549

cc/ @tanhakabir @misolori 

![image](https://user-images.githubusercontent.com/19276747/126105015-d51f993f-10ad-4754-a331-0e8e0514944a.png)

![image](https://user-images.githubusercontent.com/19276747/126013202-2f38ea47-f941-4674-80e3-b0229df818c3.png)

![image](https://user-images.githubusercontent.com/19276747/126013259-6722de23-3be2-45cf-8db0-7e35f0fa9935.png)

![image](https://user-images.githubusercontent.com/19276747/126013602-4846216f-c1db-44db-be2f-4e098e63f9a4.png)

![image](https://user-images.githubusercontent.com/19276747/126013778-404e11a7-626c-4d38-a876-24127aba4bf3.png)

![image](https://user-images.githubusercontent.com/19276747/126013819-0c706a15-9126-4f5d-b306-ee4d7530903d.png)

![image](https://user-images.githubusercontent.com/19276747/126013867-f2e06986-12eb-4aec-a3ab-21f95024bd1a.png)

![image](https://user-images.githubusercontent.com/19276747/126013880-90362d67-6742-43a0-a3b0-edf303b819a2.png)

![image](https://user-images.githubusercontent.com/19276747/126013892-f47a2c6b-02ba-4086-bc0c-c89b3a5957d3.png)

![image](https://user-images.githubusercontent.com/19276747/126013901-e16f5660-4272-422a-8d49-87da5472580c.png)

![image](https://user-images.githubusercontent.com/19276747/126013938-6214b5ad-86d1-4ce3-acc1-1c46a6e8299e.png)

![image](https://user-images.githubusercontent.com/19276747/126015634-bd92ff35-e2e2-4ca3-946b-7bc804d41c97.png)

![image](https://user-images.githubusercontent.com/19276747/126015694-c6365ef4-d4b2-46e3-97c4-c5ff4624c8a8.png)

**Comment by misolori** [comment]
Let's try out the background colors and then fix whatever color contrast issues come from this. Below is a sampling of the change:

## Dark
<img width="925" alt="CleanShot 2021-07-19 at 15 13 44@2x" src="https://user-images.githubusercontent.com/35271042/126234172-a8578a13-d675-4ca1-a877-c382add1841b.png">

## Light
<img width="925" alt="CleanShot 2021-07-19 at 15 13 53@2x" src="https://user-images.githubusercontent.com/35271042/126234183-60bde5ce-467e-4f76-9828-fa0e3a3ba970.png">

## Other themes
<img width="925" alt="CleanShot 2021-07-19 at 15 14 41@2x" src="https://user-images.githubusercontent.com/35271042/126234250-d3c4745a-089f-46a2-b356-1edbe81a106d.png">
<img width="925" alt="CleanShot 2021-07-19 at 15 14 49@2x" src="https://user-images.githubusercontent.com/35271042/126234256-b06c561d-e391-44e0-8093-6eb94baa7a54.png">
<img width="925" alt="CleanShot 2021-07-19 at 15 15 10@2x" src="https://user-images.githubusercontent.com/35271042/126234297-e237825c-0117-4432-b921-f8bbecf56773.png">
<img width="925" alt="CleanShot 2021-07-19 at 15 15 18@2x" src="https://user-images.githubusercontent.com/35271042/126234309-ad4d3b79-74da-4b18-a92f-d0ff280e90bd.png">
<img width="925" alt="CleanShot 2021-07-19 at 15 15 49@2x" src="https://user-images.githubusercontent.com/35271042/126234365-9274b36d-dde4-4e9f-b9dd-3ac77e0cac19.png">
