### ISSUE TITLE
Feature Request: Dynamic Markdown Contributions

### ISSUE THREAD

**Issue by joshuatz** [microsoft/vscode#128827]
First, apologies if this capability already exists in some capacity and I missed it. I checked issues, as well as the documentation, and could not see any indication that it does, and it is something that I think would benefit a fair number of extensions, not just the one I'm working on.

Here is the issue / feature request: **the ability of Markdown extensions to dynamically contribute CSS or JS**. And/or, ***soft disabling of extensions***.

## Markdown Conditional Styling

Currently, [Markdown extensions](https://code.visualstudio.com/api/extension-guides/markdown-extension) can dynamically alter the parsing / rendering process by changing what they return as `extendMarkdownIt` (looks like some bundled extensions [already take advantage of this](https://github.com/microsoft/vscode/blob/2ae31a96cfa7e30788cb1731f0102e5d6577591d/extensions/markdown-math/src/extension.ts#L22-L27)), but this only affects the MD -> `Token[]` process (and then `Token[]` -> `HTML`). For CSS and JS, AFAIK, we are left to the static contribution points (`markdown.previewStyles` and `markdown.previewScripts`, respectively).

This effectively means that they (MD extensions) act in an "all-or-nothing" manner when it comes to styling. If the extension is enabled, and it contributes CSS that makes the background color red, then every markdown preview is going to have a red background. This seems out of place, considering the degree of control most other VSCode APIs offer, and it makes it very difficult to write a Markdown extension that respects user choice about which files to apply the altered preview to. Although I can come up with workarounds (such as just using a custom Webview), this seems like something that could be improved.

This could take the form of a new callback function that the extension should provide, and when called is expected to return an array of CSS paths, or something similar.

## Soft Disabling Extensions
Trying to think about how VSCode could offer better solutions for these types of scenarios (toggling functionality dynamically based on changing conditions) made me wonder if VSCode has ever considered offering a *soft disable* API for extensions. This would effectively cover the above use-case, as well as dozens of other extension types.

What do I mean by *"soft disable"*? A lot of extensions already do this internally; if the extension is enabled by the user, there is still a secondary internal check against the active open file(s) to see if they should be acted upon. For example, linters, such as `prettier` might check files against a pattern file, like `.prettierignore`, spell-check extensions might check user and/or workspace settings ([Code Spell Checker does](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)), or some might even check multiple spots (glob list, user preferences, `package.json` nested settings, etc.). In cases where the active file does not match an include pattern, or does match an _exclude_ pattern, no action is taken, even though the user has the extension enabled.

A *soft disable* API could be a way for VSCode to query extensions on whether or not they should be applied to a given file. Perhaps by calling a callback function returned from `activate()` (like how `extendMarkdownIt` is returned) with the file in question and related meta-information. Or by the extension passing a [`DocumentFilter`](https://code.visualstudio.com/api/references/vscode-api#DocumentFilter). Either way, if the extension returns that it should not be applied, then all contribution points from `package.json` are ignored (or, maybe under a separate section like `contributes.dynamicEnabled.x`).

If this existed, then it could work for the Markdown use-case, as my extension could tell VSCode which files it should be enabled for, and for the files that don't match, VSCode simply ignores the regular `markdown.previewStyles` contribution instead of collecting and applying it. This would also probably save a lot of boilerplate code in extensions that rely on soft-disabling of features based on file matching, and overall improve the process of creating an extension that is highly-user-configurable.

**Comment by mjbvz** [comment]
Here's an example of a dynamic markdown parsing extension: https://github.com/microsoft/vscode/blob/e99282187193c864d55fa9706b61e074c41844d1/extensions/markdown-math/src/extension.ts#L9

You can somewhat shoehorn dynamic scripts/css through this extension point as well (you just tack the script/style on to the generated markdown)

If there's enough interest though, I'd be open to exploring adding [`when` clauses](https://code.visualstudio.com/api/references/when-clause-contexts) to the scripts and styles extension points

**Comment by joshuatz** [comment]
@mjbvz Thanks for responding to this.

That's actually pretty much exactly what I ended up doing to work around this - I hooked into the `{markdownItInstance}.parse` method and return extra tokens depending on extension soft-disable status. But... it feels like a non-optimal workaround, and I would definitely prefer something more dynamic on the VSCode API side, like your suggestion of `when` clauses.

I have a feeling that most Markdown extension authors are fine with their extension injecting CSS into every single preview without allowing the user to selectively disable it, so this will probably fall short on the required upvotes, but I appreciate you looking into it and marking it as a feature request all the same.

**Comment by yhatt** [comment]
FYI [my extension](https://github.com/marp-team/marp-vscode) has hooked `markdownIt.parse` and `markdownIt.render` for adding ability to enable/disable the feature of extension via Markdown content, and it is working over 2 years stably. Aside from whether it's good/bad...

> You can somewhat shoehorn dynamic scripts/css through this extension point as well (you just tack the script/style on to the generated markdown)

I've tried to take the same approach to contribute dynamic inline script into Markdown preview (`<script>...</script>`, without `async` attribute to go around #126640). However, this attempt failed because [the preview WebView has protected to run unknown scripts by Content-Security-Policy and not providing how to know the value of `nonce` attribute into the markdown-it plugin](https://github.com/microsoft/vscode/blob/134c34535162b621d4f010386ed8bd4b3cba925e/extensions/markdown-language-features/src/features/previewContentProvider.ts#L215-L228).

It means dynamic scripts such as built from the Markdown content cannot run in preview unless disabling security protection of preview.

On the other hand, an inline style is always allowed by WebView CSP (`unsafe-inline` for `style-src`) so a described way is working now.

**Comment by joshuatz** [comment]
@yhatt Heh, I was just looking at your extension and that exact issue a few days ago (I'm already subscribed to it 😄), as the extension I'm working on has similar areas of concern, and also that same preview jumping / sync issue.

Although I'm sure it would be no small feat, it feels like having an official API for dynamic contributions would really cut down on the number of edge-cases and side effects related to things like this, especially when things are contingent on loading order, etc.

**Comment by BettyJJ** [comment]
If I understand correctly, this is not specific to Markdown. What is needed is the feature to make an extension work only on a specific file or tab. If this is the case, I have always wanted the feature. Currently, VSCode allows an extension to declare what conditions will trigger and enable itself. However, once an extension is enabled, it works on all tabs. I want to have an option like "turn on the extension only on the current tab".

**Comment by joshuatz** [comment]
@BettyJJ Pretty much! I really should have submitted this as exactly that feature request, but originally I was just concerned with the Markdown piece, only realizing as I wrote it (and after submitting) that having conditional extension enabling baked into VSCode would benefit a huge amount of extension developers.

The second half of your comment sounds like a separate feature request though, where the end-use, not the extension developer, is controlling when the extension is soft-disabled, on a per-tab basis. That is an interesting idea though, and I like it!

**Comment by BettyJJ** [comment]
@joshuatz Sublime Text has this feature and it's very handy. If VSCode has the underlying support for this, I think both extension developers and end-users will be able to use it.

**Comment by TripleEmcoder** [comment]
Oh come on, this is a complicated issue that only extension authors will understand. A low number of comments in a relatively short period of time isn't a good measure of impact for end-users in this case.

As far as I can tell, not being an extension author myself, there is no way to eliminate quite frustrating problems with an otherwise very useful extension: https://github.com/mjbvz/vscode-markdown-mermaid/issues/71 - please reconsider or provide any tips there.
