### ISSUE TITLE
VS code doesn't recognize packages source path

### ISSUE THREAD

**Issue by miladMAPS** [microsoft/vscode#128898]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: version 1.58 ( June 2021 )
- OS Version: macOS Catalina version 10.15.7 (19H524)

Steps to Reproduce:

1. lunch VS code and add a new npm package
2. hold command and hover on the package name
but when I want to do this, it doesn't work like so:
![image](https://user-images.githubusercontent.com/57092046/126028825-985f741a-c616-42bd-a16e-b19e5202a88e.png)

but when I address it like this, it works as expected but my code doesn't work with this:
![Screen Shot 2021-07-17 at 11 36 38 AM](https://user-images.githubusercontent.com/57092046/126029174-6fce4f50-de9c-43d8-9ff4-2834914cffe2.png)

here is my jsconfig file:
![image](https://user-images.githubusercontent.com/57092046/126029259-5c2c6ace-6d97-43b9-af91-112dc966a15d.png)

**Comment by IllusionMH** [comment]
Looks like didn't set `moduleResolution`. See https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies

**Comment by mjbvz** [comment]
@miladMAPS Does setting `moduleResolution` fix the issue? If not, please share a minimal example project that demonstrates the problem

**Comment by miladMAPS** [comment]
> Looks like didn't set `moduleResolution`. See https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies

But I'm not using typescript.

**Comment by miladMAPS** [comment]
> @miladMAPS Does setting `moduleResolution` fix the issue? If not, please share a minimal example project that demonstrates the problem

https://codepen.io/miladmaps/project/editor/AOrqVP
when I run yarn install and yarn start, project works but I still can't navigate to package source with "go to definition"

**Comment by IllusionMH** [comment]
> But I'm not using typescript.

VS Code uses TS for both JS and TS features. `jsconfig.json` is configuration you need to update.

**Comment by miladMAPS** [comment]
> > But I'm not using typescript.
> 
> VS Code uses TS for both JS and TS features. `jsconfig.json` is configuration you need to update.

setting  "moduleResolution" key to "node" in the jsconfig.json file solved my problem,
thanks a lot.
