### ISSUE TITLE
Creating multiple files at once

### ISSUE THREAD

**Issue by lamaqdahodwala** [microsoft/vscode#128853]
The feature I have in mind is one where you can separate file names with a comma (or other separating character) to create multiple files at the same time. 

Ex.
![image](https://user-images.githubusercontent.com/74932012/125962110-4b273fa6-4fe4-48c5-b680-3af79e1148a4.png)

Creating a file with this name would create two files, `foo.py` and `bar.py`.

The feature would also allow you to mix and match file suffixes (so I could make `foo.js` and `bar.html` at the same time)

**Comment by hmcclungiii** [comment]
Touch comes to mind.

**Comment by MariaSolOs** [comment]
I just wrote an [extension](https://marketplace.visualstudio.com/items?itemName=mariasolos.add-multifile) that does just this :) @lamaqdahodwala

**Comment by JainnyAryan** [comment]
@MariaSolOs I went through the whole of your portfolio website and projects, and they are great tbh!!!! Keep it up! ❤️

**Comment by MariaSolOs** [comment]
> @MariaSolOs I went through the whole of your portfolio website and projects, and they are great tbh!!!! Keep it up! ❤️

Aww thank you! You just made my day 😸

**Comment by JainnyAryan** [comment]
I have my expertise in Flask, Python, Web and Flutter(Mobile App) Development. If you ever wanna collaborate on any project, do let me know! 💪
