### ISSUE TITLE
VS Code uninstalled itself for upgrading but never installed itself back

### ISSUE THREAD

**Issue by duanqn** [microsoft/vscode#128823]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: I forgot. Should be the second latest release on Win x64.
- OS Version: Windows 22143.1000 -> 22144.1000

Steps to Reproduce:

1. Have a new version of Windows queued up in Windows Update and pending restart.
2. Close VS Code. It seems my VS Code has downloaded a new version in the background and decided to upgrade itself upon exit.
3. At the same time, go to Start -> Power button -> Update & Restart to update Windows. VS Code blocked shutdown for a few seconds but soon allowed Windows to shutdown.
4. In the new version of Windows, VS Code is gone.

It seems that the most plausible explanation is that VS Code did not finish upgrading before the machine is shut down. Either VS Code did not foresee this interruption between un- and re-installing, or VS Code did register the installation to be executed on next Windows login, but Windows did not preserve the one-time startup task through its update. Anyway, I'm filing this issue for VS Code experts to confirm this.

**Comment by joaomoreno** [comment]
#52855
