### ISSUE TITLE
Add new kind of breakpoint types

### ISSUE THREAD

**Issue by Skywalker13** [microsoft/vscode#128822]
Hello,

You should provide new kinds of breakpoints which should be usable for any languages. An example of types of breakpoints that will be very useful in some contexts are:

- One shot breakpoint (or better, with a counter), it breaks only one times (or n times), then the breakpoint is automatically removed
- "Pause" breakpoint (it breaks for a specific time length; useful to experiment latency, debugging races, network issues, ...)
- other ...

Regards

**Comment by weinand** [comment]
@Skywalker13 VS Code already supports "conditions" and "hitCounter" for breakpoints.
These can be used to implement both examples from your list.

**Comment by Skywalker13** [comment]
Disagree, but as you wish.. it's necessary to change the code in order to pause **a certain amount of time** and it's particularly difficult in case of Heisen bugs. Too bad

**Comment by weinand** [comment]
@Skywalker13 As a condition you can just call a wait/sleep function and then return false, right?

**Comment by Skywalker13** [comment]
With languages like javascript.. but with C/C++ it's not easy. I'm a bit disappointed that in 2021, we have still breakpoints stuff like in 90s.

**Comment by weinand** [comment]
@Skywalker13 languages of the 80s have breakpoint stuff of the 80s ;-)

VS Code is language agnostic. We cannot fix C++ limitations. I suggest that you file this feature request against the C++ extension.
