### ISSUE TITLE
Missing option to skip a VSC windows start menu entry / desktop icon

### ISSUE THREAD

**Issue by gitterman** [microsoft/vscode#128817]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 100.19042

Steps to Reproduce:

1. Updates to VSC always creates a windows start menu folder, and there is no option to prevent this.

My PC is a universal tool for me and I have 300+ programs installed.
Thus, I use Classic Shell to structure my startup menu to be usable ergonomically.
VSC frequently messes with this structure, as it thinks there must be a top-level entry named "Visual Studio Code".
There are programs which have an option to not create a start menu folder or a desktop icon, and VSC should definitely have this too.

**Comment by joaomoreno** [comment]
Uninstall VS Code. Then, install it again and don't check that option when installing.
