### ISSUE TITLE
Emmet Tab autocomeplete error

### ISSUE THREAD

**Issue by itzikhillel** [microsoft/vscode#128835]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I try to use emmet auto-completion with Tab and getting the following error
"Running the contributed command: 'emmet.expandAbbreviation' failed."
I reset all settings, uninstalled all extensions
still proceeds.

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|24.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 2762afe0-5948-4dcb-b2b6-3edc6fa656ac|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by rzhao271** [comment]
I remember seeing that yesterday, but I'm unable to reproduce the issue now.
I also verified that Emmet was enabled (in the Extensions viewlet, search `@builtin` and then scroll down until you find Emmet).
After confirming Emmet is enabled, can you try running the `workbench.action.restartExtensionHost` command?
