### ISSUE TITLE
Move "Open Walkthrough" to Start section

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#128860]
This was @kieferrm's suggestion about moving the "Open Walkthrough..." to the Start section as it felt out of place near the bottom:

![image](https://user-images.githubusercontent.com/35271042/125980693-d33bbfae-0b8d-4753-8114-4bb5280ebad0.png)

Maybe something like this would work:

<img width="254" alt="CleanShot 2021-07-16 at 09 41 41@2x" src="https://user-images.githubusercontent.com/35271042/125980992-1d6d929d-be37-41de-b087-cb28c9621e9a.png">

**Comment by joyceerhl** [comment]
![image](https://user-images.githubusercontent.com/30305945/127233594-7d05355a-ba0d-4e52-9926-f38ffd12cb6f.png)

Trying to verify this, but I'm not seeing an Open Walkthrough option at all.

**Comment by misolori** [comment]
@joyceerhl sorry for not clarifying, try removing all of the walkthroughs to see it appear
