### ISSUE TITLE
browser tab in vscode

### ISSUE THREAD

**Issue by a1git** [microsoft/vscode#128836]
Hi, 

Checking if its possible to have a new tab ( type: browser) in vscode. 
This will allow better use of the real-estate so that a browser does not have to be open side by side or in another window, and a tab can work as a browser, where we can preview the changes.  This means a full browser window in a new tab. The browser window can be borrowed from locally installed/available browsers.

**Comment by bpasero** [comment]
Try https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server
