### ISSUE TITLE
Extensions setting vscode.StatusBarItem.tooltip cause the existing tooltip to disappear instead of refreshing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#128887]
Does this issue occur when all extensions are disabled?: N/A requires an extension

- VS Code Version: 1.58.2 or today's Insiders
- OS Version: Windows.

Steps to Reproduce:

1. Hover over a status bar item to view a tooltip.
2. Have some extension set vscode.StatusBarItem.tooltip. I repro it with the C/C++ extension hovering over the database icon (see the code at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/ui.ts#L79 ).

Bug: The status bar item tooltip disappears and doesn't reappear (until the user re-hovers) instead of updating. Depending on a timing, this can cause the tooltip to appear to not appear if it's updated right after the user hovers over it.

**Comment by joshabb** [comment]
I can confirm this is the case for linux as well. I have an extension that updates tooltips frequently and if you're hovered over them and the text changes at all the tooltip disappears. However, if the text gets updated but is the same text then the tooltip remains.

**Comment by jrieken** [comment]
It still disappears but quickly reappears... It's somehow between re-open and verified for me

https://user-images.githubusercontent.com/1794099/135086336-62d86431-d16c-4be8-b417-602a696d6efc.mov

**Comment by bpasero** [comment]
There is currently no way to change the contents of the hover directly without reshowing it. I commented on that fact here: https://github.com/microsoft/vscode/pull/132963#discussion_r707015335

**Comment by jrieken** [comment]
For the language status I added the ability to have any html element as hover. You would have to do the MD rendering yourself but with by keeping the html element around you should be able to achieve this

**Comment by bpasero** [comment]
But does that make the hover adjust size and location dynamically?

**Comment by jrieken** [comment]
yeah

**Comment by bpasero** [comment]
I think we cannot do that in a generic way because status tooltips are typed as `string | IIconLabelMarkdownString | HTMLElement | undefined` so we always have to handle the case where no HTML is used. But I defer to Martin to comment whether this is feasable.

**Comment by sean-mcmanus** [comment]
The behavior seems good enough to me. Thanks.

**Comment by lramos15** [comment]
Marking as verified for now because the main issue is fixed, but sounds like there is some discussion to be had around the updating being a bit smoother
