### ISSUE TITLE
Allow opting out of git status "-u" option.

### ISSUE THREAD

**Issue by ajhyndman** [microsoft/vscode#128800]
## Rationale

Add a new option which allows users to opt out of the `-uall` argument passed to git status by VS Code.

My motivation here is performance.  I regularly work in a very large repository.  `git status -uall` can take 15 seconds, while `git status -unormal` resolves within one second.

## Proposal

Add a new option: `"git.statusArgs.untrackedChanges": "no" | "normal" | "all" (default)`

This option would be used to augment the args passed to the `git status` command, here:

https://github.com/Microsoft/vscode/blob/5ef5837c581469dfd72aea765b10e0a6241f7690/extensions/git/src/git.ts#L1817

Related to #15640

**Comment by lszomoru** [comment]
Closing this issue in favour of https://github.com/microsoft/vscode/issues/169253
