### ISSUE TITLE
GitHub Auth fails: keychain 'Cannot Create an item in a locked collection'

### ISSUE THREAD

**Issue by nelsonov** [microsoft/vscode#128896]
Issue Type: <b>Bug</b>

Attempt to login in to sync settings via Github or login to Github to work with repositories.

System running vscode is being accessed remotely via X (ie DISPLAY=laptop-ip:0). gnome-keychain has been unlocked in the same terminal window.  Running seahorse from the same prompt from which vscode is launched shows that the Login keychain is unlocked. 
```
22:29:54 rpi07 lnelson:~> echo $DISPLAY
lap01:0
22:29:56 rpi07 lnelson:~> source bin/unlock-gnome-keyring.sh
NOTE: This script will only work if launched via source or .
Login password: 
22:30:18 rpi07 lnelson:~> code
22:30:28 rpi07 lnelson:~> seahorse
```
unlock-gnome-keyring.sh:
```
22:31:36 rpi07 lnelson:~> cat bin/unlock-gnome-keyring.sh
echo 'NOTE: This script will only work if launched via source or .' >&2
echo -n 'Login password: ' >&2
read -s _UNLOCK_PASSWORD || return
pkill "gnome-keyring"
eval $(echo -n "${_UNLOCK_PASSWORD}" \
           | gnome-keyring-daemon --daemonize --login \
           | sed -e 's/^/export /')
unset _UNLOCK_PASSWORD
echo '' >&2
```

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:44:45.182Z)
OS version: Linux arm 5.10.17-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 1500)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|3.74GB (0.39GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 482991c4-f25f-4116-8ed9-976efb1c17ac|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gitlens|eam|11.4.1
cpptools|ms-|1.5.1
platformio-ide|pla|2.3.2
emacs-mcx|tut|0.32.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by nelsonov** [comment]
The attached snippit shows a seahorse window overlaying the vscode window with the error message.  The seahorse windows shows that the login key is unlocked.

![gitauth_seahorse](https://user-images.githubusercontent.com/1811554/126027177-b5690775-44ff-474a-8eca-50fbb670f974.jpg)

**Comment by TylerLeonhardt** [comment]
I'm curious @nelsonov. Where did you find out that the Login keychain is what's used here instead of the default keychain (I'm guessing that's what "default k" is in the screenshot)

**Comment by ShonFrazier** [comment]
Same problem on macOS 11.4; VSCode Version: 1.57.1, Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48;

However, the login seems to have worked anyway, but it's not persistent (maybe I should file another issue for that...)

**Comment by nelsonov** [comment]
The login succeeds for me as well, but does not persist. 

@TylerLeonhardt I don't know for sure that it is or should be using the Login keychain.  That is part of my concern.  The Login keychain is the only keychain that gets unlocked by logging in, so using any other keychain (such as the one labeled "Default") would require some additional steps (that I don't know) to lock/unlock.  It wouldn't be very practical.

**Comment by TylerLeonhardt** [comment]
@nelsonov can you try these steps and see how they go? https://github.com/microsoft/vscode-docs/pull/4666/files

Someone is interested in contributing a potential solution to your problem.

**Comment by TylerLeonhardt** [comment]
Has anyone had the opportunity to try these steps? https://github.com/microsoft/vscode-docs/pull/4666

**Comment by ShonFrazier** [comment]
These steps don't appear to have a macOS implementation. I'm sure there's something equivalent with its keychain. I'll make an attempt at translating to Mac this evening.

**Comment by mcartoixa** [comment]
I'm running Ubuntu 20.04, VS Code 1.59.1 installed via snap and suffered from the same problem, when accessing the machine remotely via SSH only (with X Forwarding). The trouble seems to be that the Gnome keyring was apparently never meant to be used without a Gnome session...
After a long fight, what I did was:
- alter my `/etc/pam.d/login` file as described in https://wiki.archlinux.org/title/GNOME/Keyring#Using_the_keyring to add the following lines (they are not continguous):
    ```
    auth       optional     pam_gnome_keyring.so
    session    optional     pam_gnome_keyring.so auto_start
    ```
- add the following to my `.profile`:
    ```shell
    if [ -z "${DESKTOP_SESSION}" ] && [ -n "${SSH_CONNECTION}" ] && [ -n "${DISPLAY}" ]; then
        dbus-update-activation-environment --systemd DISPLAY
        while read -r LINE; do
            [[ $LINE =~ ^\*\*\s.* ]] && echo $LINE || export $LINE
        done < <(gnome-keyring-daemon --replace --daemonize --components=gpg,pkcs11,secrets,ssh)
    fi
    ```
My keychain is not automatically unlocked (and I don't think it can if I use a public key for login), but I get prompted for my password now right after login (thanks to [the _dbus_ update trick I found here](https://bbs.archlinux.org/viewtopic.php?id=202754)) and then the keychain is unlocked. I can work with that.

I don't really understand half of what I did there, so the process may still be improved. In particular opening several SSH connections with X Forwarding is asking for trouble. More information can be found at https://wiki.gnome.org/Projects/GnomeKeyring

Hope this helps.

**Comment by nelsonov** [comment]
I have avoided all the editing of PAM, .profile, .xinitrc, etc....  All attempts at getting things to launch automatically failed for me.  However, I do have a simple workaround that works for me:

First time, there may not be a keyring called "login", see below.  This also assumes you have `seahorse` installed.

1. set your DISPLAY environment variable
2. run `dbus-update-activation-environment --systemd DISPLAY`
3. run seahorse
4. right-click on the "login" key, then select unlock and enter the password
5. launch vscode

```
> export DISPLAY=lap01:0
> dbus-update-activation-environment --systemd DISPLAY
> seahorse
> code
```

If you do not have a "login" keyring when you first launch `seahorse`, then you will need to do:
File -> New -> Password Keyring 
Name the keyring "login" and assign a password

The key missing step for me was 2.  Without this, gnome-keyring tries to launch a password prompt on the console.  The "--systemd DISPLAY" tells it to use your DISPLAY environment variable instead.

Step 3, running `seahorse` automatically launches gnome-keyring-daemon, so there is no need to have it auto-launched by PAM, .profile, etc....

This process requires that the keyring be unlocked manually, but it's simple and not very intrusive.

**Comment by TylerLeonhardt** [comment]
Closing this as we changed this flow quite a bit and I think our docs are better and surfaced more.
