### ISSUE TITLE
[Test UI] What's the usage of 'Show in Active File Only'

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#128824]
Version: 1.59.0-insider (user setup)
Commit: 50b3811fdc5b5c80ca516a2edfffedcbd464b033
Date: 2021-07-15T05:13:58.348Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

@connor4312 Maybe I missed something. There is a menu called `Show in Active File Only` in the test view, what's the usage of that option? I tried to enable/disable it, but nothing happens.

![image](https://user-images.githubusercontent.com/6193897/125916167-e857329a-2f43-47e6-bf5b-9b4aedc5b1ef.png)

**Comment by jdneo** [comment]
@connor4312 Is this option only works for the top level test items? (test items that belongs to `testController.items`)

**Comment by connor4312** [comment]
The algorithm used for showing tests is:

1. If the current file has a URI: if the URI is parent of or equal to the current file show it, otherwise hide it.
2. If the current file does not have a URI, recurse this algorithm for its children. If any children are visible, this item is visible too

**Comment by jdneo** [comment]
Sounds like id the test node's uri contains or equal to the current file's uri, then it will be shown in the explorer?

If that's true, could you try this change? https://github.com/jdneo/vscode-extension-samples/commit/d0e96ee7ba1406d6b0baca36fb7815bae5ee0ac1

I add a folder layer for each file.

**Comment by roblourens** [comment]
That option is gone now, is that expected?

**Comment by connor4312** [comment]
Make sure you're looking in the "filter" menu in the search box; it's still there.

Thanks for the repro Sheng! Fixed in the next Insiders.
