### ISSUE TITLE
Basic usability issues with search & replace

### ISSUE THREAD

**Issue by peter-bertok** [microsoft/vscode#128810]
Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 2004

Compared to other text editors or IDEs, Visual Studio Code's most basic search & replace functionality is broken in numerous ways:

**When trying to make a replacement of a string, the selection is reset** 
1. Select a block of code.
2. Type in the text to replace -- this incorrectly resets the selection.
3. Attempting to enable "find in selection" will set the selection to the first match, not the original selection.

**Toggling any button resets selections if there's a matching string.**
1. Open the search & replace box, with a memorised search string in the find box.
2. Press any button, such as "use regular expressions", "find in selection", etc...
3. The selection will be reset (incorrectly).

(similarly, going back to a search item in the history also resets selections).

**The history keyboard shortcut is the opposite of every other Windows IDE or text editor**
I just assumed VS Code _has no search history_ because it doesn't respond to the standard keystroke that all other editors use. There is also no visual "prompt" indicating that a history exists unlike most other editors (which use combo boxes).

```
   VS Code:       UP
   Visual Studio: DOWN
   Notepad++:     DOWN
   TextPAD:       DOWN
   IntelliJ:      ALT+DOWN
   MS Word:       DOWN
```

**There is no way to view search history**
The only method is to scroll back one at a time, unlike most other IDEs or text editors that use a combo box that can be opened and used to "pick" a specific entry.

**Search in selection doesn't work consistently with "block select"**
Selecting a block of code using middle-click-drag doesn't interact well with search. I can't even get reproducible scenarios! Just trying this a few times in a row resulted in different effects, including two _different_ selection highlights on top of each other, as well as a search indicating that "nothing matches" unexpectedly:

![image](https://user-images.githubusercontent.com/14988123/125894039-46a46e5d-c633-4694-a898-020576f322fa.png)

![image](https://user-images.githubusercontent.com/14988123/125893992-b26b6a14-534a-463f-a574-f7e33416a565.png)

**Comment by amunger** [comment]
https://github.com/microsoft/vscode/issues/116827 covers selection issues
https://github.com/microsoft/vscode/issues/23099 for requested search history
it looks like find in selection for a block selection is working now
