### ISSUE TITLE
Cannot move WebView tab to other view column under Ubuntu

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#128818]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.1, 1.59.0-insider
- OS Version: Ubuntu 21.04

Steps to Reproduce:

1. Create a WebView
2. Drag the WebView to a new view column
3. The rectangle of the target position shows up, but the WebView does not move.

It is a bit like #99208 but only under Ubuntu and the target area is shown but eventually does not move on mouseUp.

On macOS with the same versions, it works well.

**Comment by renkun-ken** [comment]
The problem only occurs when started with ` --enable-features=UseOzonePlatform --ozone-platform=wayland` suggested at https://github.com/microsoft/vscode/issues/121916#issuecomment-836447461. Without this, everything works normally.

**Comment by mjbvz** [comment]
@renkun-ken Do you still see this issue in the latest VS Code insiders build?

**Comment by renkun-ken** [comment]
Looks like it works much better now.
