### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by alloy** [Microsoft/vscode#12883]
- VSCode Version: 1.5.3
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open VSCode with disabled extensions (`--disable-extensions`)
2. Open a JS file from this repo: https://github.com/artsy/emission
3. Scroll vertically (possibly 2 files in split panes)
4. Observe Code Helper process consuming ~100% CPU cycles.

Note that I’m seeing ~15% CPU usage when idle, which also adds up quickly when running multiple editors.

[CPU-20160928T134657.cpuprofile.txt](https://github.com/Microsoft/vscode/files/497997/CPU-20160928T134657.cpuprofile.txt)

**Comment by bpasero** [comment]
If this was Windows I would assume this is because of accessibility ON, but since this is on Mac it might be something else.

@alloy does this reproduce with any 2 files open?

**Comment by jrieken** [comment]
> Open a JS file from this repo

@alloy Can you precisely name the file which causes this for you. If I open *a* JS file I cannot repo (*index.js, load_failure_viewjs, opaque_image_view.js*)

**Comment by alloy** [comment]
1. I open the full project with: `code . --disable-extensions`
2. Open e.g. `infinite_scroll_grid.js` in 2 split panes.
3. Scroll fast up and down repeatedly in one of the panes.

**Comment by Treri** [comment]
Maybe the same with #10289

**Comment by jrieken** [comment]
doesn't repo for me - I see some CPU load while scrolling but not after, nothing stays busy

**Comment by alexandrudima** [comment]
I have also tried, but was not able to reproduce any slowness.

**Comment by alloy** [comment]
When I have the time, I’ll spend some more time thinking about what in my local env could cause this.
