### ISSUE TITLE
finalize open tunnel api

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#128820]
Are there any plans? We would like to call it from our extension to control tunneling of some ports in context of Remote SSH.

**Comment by alexr00** [comment]
Thanks for your interest in this API. We have no plans to ever finalize it.

**Comment by akosyakov** [comment]
@alexr00 thank you for the response, does it mean there will be another way to do it, i.e. a side effect of calling  `vscode.env.asExternalUri` for instance, or it means that there is not plans at all to allow 3rd party extensions controlling ports? Also what about authority resolvers? Is it the same?

**Comment by alexr00** [comment]
`asExternalUri` is the recommended way for extensions to get a URI that "works" in all VS Code situations (i.e., remote or not). `asExternalUri` will cause port forwarding to occur if it's needed, but the returned URI should be used immediately and not saved as it could change later. We don't plan to have finalized API that lets extensions control the details of a forwarded port (like the local port).
