### ISSUE TITLE
VScode Version: 1.58.2 Failing to save

### ISSUE THREAD

**Issue by jonson-ncube** [microsoft/vscode#128833]
I just updated my VSCode Date: 2021-07-14T22:09:06.581Z 
Now I am having issues with saving files :[

**Comment by jonson-ncube** [comment]
<img width="603" alt="Screenshot 2021-07-16 at 13 09 17" src="https://user-images.githubusercontent.com/36877522/125938785-c80b9ca2-5a0c-43f4-accd-012c286a64c0.png">

**Comment by kieferrm** [comment]
Pls try if there's an extension that causes the issue. https://code.visualstudio.com/blogs/2021/02/16/extension-bisect. If not, is there anything out of the ordinary with your setup?

**Comment by jonson-ncube** [comment]
It turns out my computer didn't have enough space 🤦🏾‍♂️

**Comment by clevermiraz** [comment]
Extention load take much more time
