### ISSUE TITLE
Brackets bug

### ISSUE THREAD

**Issue by Yu-jinKim** [microsoft/vscode#128829]
Issue Type: <b>Bug</b>

While coding in Python, brackets do not close automatically when opening them even though the setting is on Always.
```python
# expected when typing print(
print()
# actual
print(
```

![image](https://user-images.githubusercontent.com/25991776/125932390-68e4cc10-f77f-4c04-9137-38a5faa58f13.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3175)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.86GB (7.93GB free)|
|Process Argv|--unity-launch --crash-reporter-id df2fb565-cdf4-40ed-a7d3-da83694f7c40|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
django|big|1.0.2
wdl|bro|1.0.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.42.1
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-great-icons|emm|2.1.79
copilot|Git|1.2.1991
vscode-pull-request-github|Git|0.28.0
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
vsliveshare|ms-|1.0.4568
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0
vscodeintellicode|Vis|1.2.14
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by alexdima** [comment]
@Yu-jinKim I have tried in a brand new installation of VS Code, without any settings, and without any extensions and I cannot reproduce. Do you have additional information to help reproduce?
