### ISSUE TITLE
Copying Stdout Copies Cell Contents Instead

### ISSUE THREAD

**Issue by appleplectic** [microsoft/vscode#128882]
Issue Type: <b>Feature Request</b>

When trying to copy error messages in the stdout of a Jupyter notebook, the extention automatically copies the cell content instead. This is very annoying while trying to debug error messages.

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by rebornix** [comment]
@appleplectic sorry for reaching out late, can you check if you can still reproduce this issue with latest VS Code?
