### ISSUE TITLE
index.{js,ts,jsx,tsx} always on top

### ISSUE THREAD

**Issue by drpicox** [microsoft/vscode#128834]
When we work with JS or TS, we usually do:

```typescript
import { symbol } from 'some/folder'
```

And in the `some/folder` there is a `index.ts` that does:

```typescript
export * from './aThing';
export * from './bThing';
...
export * from './yThing';
export * from './zThing';
```

The problem, is that when we look at the folder in the Explorer we see the files like:

```
- some/folder
  - aThing.ts
  - bThing.ts
  - index.ts
  - yThing.ts
  - zThing.ts
```

It is difficult to spot and edit the `index.ts`. It is like it has camouflage.

The problem is:
1. The file follows a different kind of naming (the one forced by node importing rules) from the rest files from the package
2. It defines what the folder is itself, so it breaks apart the same single concept

**The proposal is** to reorder the contents of the folder so index.{js,ts,jsx,tsx} is always just below the folder name:

```
- some/folder
  - index.ts
  - aThing.ts
  - bThing.ts
  - yThing.ts
  - zThing.ts
```

**Comment by drpicox** [comment]
I am not sure about it, I did some research before adding the issue, and looking one by one from suggested ones it seems that I cannot find an exact duplicated:

- #129047, **no**
- #128853, **no**
- #128698, **no**
- #128648, **no**
- #128538, **no**
- #127818, **no**
- #127746, **no**
- #127596, **no**
- #126872, **no**
- #126842, **no**
- #126817, **no**
- #126450, **no** (kind of tricky title, but reading the body, it is not what I described)
- #126398, **no**
- #126346, **no**
- #125922, **no**
- #125906, **no**
- #125616, **no**
- #125464, **no**
- #125295, **no**
- #124851, **no**
- #124825, **no**
- #124505, **no**
- #124495, **no**
- #124401, **no**
- #124341, **no**
- #124115, **no**
- #124065, **no**
- #124037, **no**
- #124023, **no**
- #124005, **no**
- #123413, **no**
- #123389, **no**
- #123260, **no**
- #123020, **no**
- #122316, **no**
- #122004, **no**
- #121805, **no**
- #117967, **no**
- #117621, **no**
- #116989, **no**
- #114994, **no**
- #114423, **no**
- #112730, **no**
- #112463, **no**
- #112293, **no**
- #112099, **no**
- #111655, **no**
- #111626, **no**
- #111580, **no**
- #111578, **no**
- #111022, **no**
- #108885, **no**
- #108271, **no**
- #105691, **no**
- #94307, **no**
- #91132, **no**
- #88682, **no**
- #87956, **no**
- #84857, **no**
- #75559, **no**
- #67988, **no**
- #67176, **no**
- #66971, **no**
- #62104, **no**
- #52875, **no**
- #45470, **no**
- #41860, **no**
- #41351, **no**
- #38878, **no**
- #30191, **no**
- #27759, **no**
- #27286, **no**
- #15370, **no** (maybe the closest one, but does not cover this case)
- #6328, **no**
- #3553, **no**
- #1214, **no**
- #869, **no**
- #763, **no**

And also checking some of the most recent ones closed

- #129347, **neither**
- #128780, **neither**
- #128726, **neither**
- #128628, **neither**, could be, because it is just ordering, but not
- #128345, **neither**
- #127256, **neither**
- #127219, **neither**
- #126999, **neither**
- #126793, **neither**
- #126684, **neither**
- #126277, **neither**
- #126000, **neither**
- #125919, **neither**
- #125890, **neither**
- #125598, **neither**
- #125041, **neither**
- #125026, **neither**
- #124932, **neither**
- #124850, **neither**
- #124800, **neither**
- #124775, **neither**
- #124611, **neither**
- #124565, **neither**
- #124313, **neither**
- #124030, **neither**
- #123931, **neither**
- #123469, **neither**
- #123438, **neither**
- #122879, **neither**
- #122713, **neither**
- #122493, **neither**
- #122276, **neither**
- #121825, **neither**
- #121217, **neither**
- #121175, **neither**
- #121127, **neither**
- #121006, **neither**
- #120912, **neither**
- #120882, **neither**
- #120752, **neither**
- #120679, **neither**
- #120620, **neither**
- #120580, **neither**
- #120447, **neither**
- #120022, **neither**
- #119847, **neither**
- #119746, **neither**
- #119513, **neither**
- #119464, **neither**

But, it "looks like":
- #119207
But this says that it is a duplicated for:
- #27286
But it does not show this case, and it is too wide. It might get covered, but this case, which I think that makes sense to mention, it is not present.

**Comment by SmartHypercube** [comment]
@isidorn I think it's a little strange to close an issue as dup without mentioning the original issue's number. The author has clearly put some effort in looking for possible dups. I cannot find the original issue either. This is unhelpful and will leave future people searching for the same problem a big mystery.

Could you please reopen this issue or give the original issue's number?
