### ISSUE TITLE
Failed to escape forward slashs when using Placeholder-Transform in snippets

### ISSUE THREAD

**Issue by XJDKC** [microsoft/vscode#128838]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```bash
1.58.2
c3f126316369cd610563c75b1b1725e0679adfb3
x64
```
- OS Version: 
```bash
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
```

Steps to Reproduce:

1. Open the C++ snippets file
2. Create a new snippet as below
```JSON
{
    "TEST": {
        "prefix": [
            "test"
        ],
        "description": "forward slash test",
        "body": [
            "${RELATIVE_FILEPATH/(.*)(src\/)(.*)/${3}/}",
        ]
    }
}
```
3. Open a folder in VS Code.
4. Create a new folder named `src` in the workspace.
5. Create a file (e.g. test.cpp) under the folder and open it in VS Code.
6. Enter `test` to insert the snippet we just created.
7. Get the wrong result `${RELATIVE_FILEPATH/(src/)(.*)//}`, the correct code should be `test.cpp`.

**Comment by jrieken** [comment]
In JSON you need to escape `\` with another backslash, e.g `"${RELATIVE_FILEPATH/(.*)(src\\/)(.*)/${3}/}"`

**Comment by XJDKC** [comment]
> In JSON you need to escape `\` with another backslash, e.g `"${RELATIVE_FILEPATH/(.*)(src\\/)(.*)/${3}/}"`

That is, we need to add a `\` before `/` to escape the `/` as the forward-slash is treated as the delimiter of the place-transform. In order to achieve that, we need to add another `\` before the `\` because back-slash is a special character in a string and will be discarded in the process of parsing JSON.
