### ISSUE TITLE
sass default save as .sass,not is .scss

### ISSUE THREAD

**Issue by johnny19941216** [Microsoft/vscode#12881]
- VSCode Version:1.5.3
- OS Version:win7

Steps to Reproduce:

1. 
2.

**Comment by bpasero** [comment]
@johnny19941216 can you explain what you mean? Here is what I see:

![image](https://cloud.githubusercontent.com/assets/900690/18916000/2bde8470-8593-11e6-9f53-3072656702b4.png)


This is using our insiders build that now populates the file types in the dialog.
