### ISSUE TITLE
Suggestions have no color

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#128863]
Issue Type: <b>Bug</b>
Does this issue occur when all extensions are disabled? **Yes**

The pop-up showing e.g. the type of a property or the signature of a method for suggestions has no color. I'm not entirely sure
if this was actually ever the case but I'm certain this shouldn't be like this.
Function signatures especially can get really blown up by TypeScript and having the entire signature be one single color and line makes it hard to differentiate between the individual parameters and return types.

Take the following screenshot for example, even the automatic import notice is the same color and directly inline with the actual information:

![grafik](https://user-images.githubusercontent.com/11841072/125988775-54968a99-5f4b-48f8-956c-24a5bf467b57.png)

So in case this isn't a bug, please consider this a feature request to enhance the information pop-up by:

- applying the normal theme to the code to allow for better scanning of signatures and type information
- seperating additional text like auto-import notices from the actual content
- consider using more of the available space to allow the information to wrap at more suitable spots (see the image above where it wraps inside words like "Co|mponent", "Option|s" or "an|y")

The last could maybe also enable the signature to extend to it's full length, because afaik there is currently no way to prevent it from hiding stuff as "... x more ..." or just plain "...". Furthermore, the last point also applies to the hover pop-up, which manages to show color and has some visual seperation and does wrap (although it leaves quite some margin on the right) but still leaves out details at some point:

![grafik](https://user-images.githubusercontent.com/11841072/125991857-2673bf10-92e3-4278-b843-5de294d098d9.png)

VS Code version: Code 1.58.2 (c3126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.94GB free)|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"feature-request"+label%3A"new release"+label%3A"suggest"

**Comment by vainamov** [comment]
@jrieken are you sure? Because none of the 23 open issues with matching `feature-request` and `suggest` labels has any resemblance with the problem described here.
