### ISSUE TITLE
Activity bar icons have a 1-2px line that doesn't show hover feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#128844]
Notice how there is a line that doesn't highlight the debug icon inbetween two that do.

![recording (41)](https://user-images.githubusercontent.com/2193314/125951126-08cb6551-b978-40b0-b62c-0cc1ea4d24be.gif)

I think this is the cause:

![image](https://user-images.githubusercontent.com/2193314/125951115-696ce816-77f7-4a81-b96b-571c3888567b.png)

This is important to make https://github.com/microsoft/vscode/issues/122226 work nicely and for general polish of an important UI component

**Comment by misolori** [comment]
I believe you'll also need to convert the margin to padding to keep the cursor hovering over the item (margin pushes it oustide the bounding box vs extending it):

<img width="76" alt="CleanShot 2021-07-16 at 08 56 03@2x" src="https://user-images.githubusercontent.com/35271042/125975507-f969d04d-bc27-4a0d-aefe-6e631cbc03ff.png">

<img width="347" alt="CleanShot 2021-07-16 at 08 56 43@2x" src="https://user-images.githubusercontent.com/35271042/125975536-a2a95ebb-c599-42db-b74c-9230c2c29583.png">

**Comment by sandy081** [comment]
Right that, above margin is causing it, but changing it to padding won't fix it. All hover characteristics are build on top of the label item. Above margin is on its parent container element. So there will be this flicker always. I think this margin is just a legacy when icons were smaller. So, removing this margin completely.
