### ISSUE TITLE
Create Terminal in Editor Area and open the terminal at the same time

### ISSUE THREAD

**Issue by tamnguyenchi93** [microsoft/vscode#128805]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows 10

Steps to Reproduce:

1. `Ctrl + Shift +P`
2. Terminal: Create Terminal in Editor Area

Expect: Only one new terminal shows up.
Result: Vscode creates a new terminal in Editor Aread and show the terminal panel (I hid it).

**Comment by iuvbio** [comment]
Can confirm this on Ubuntu 21.04.

A new terminal in the panel is also opened when an editor terminal is already open and I execute a shortcut such as "Terminal: Run selected text in active terminal" or "Python: Run selection/line in Python terminal". The selection is correctly run in the open editor terminal, but the additional terminal in the panel should not open.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by tamnguyenchi93** [comment]
I cannot replicate it on another machine with the official release.

Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Both machines run: Windows 10.

And I want to ask: 
When I split the terminal in editor area, the new panel show up on another editor group instead of 2 panels in one tab. Is it a bug?

**Comment by meganrogge** [comment]
@tamnguyenchi93 that's by design
