### ISSUE TITLE
We couldnt connect you to the extensions marketplace at this time on manjaro

### ISSUE THREAD

**Issue by wijiler** [microsoft/vscode#128852]
I was coding when I figured it would be nice to have some assembly intellisense and then it hits me with that message I looked for how to fix this found an issue about this from 2019 and it I did all the steps and even tried filtering none of it worked! So if anybody knows how to fix this help would be great.

https://user-images.githubusercontent.com/41879253/125960318-3b17435b-a1a7-4d60-9233-8d1f561edac3.mp4

**Comment by 3y3p4tch** [comment]
I am facing a similar issue. On looking at developer tools, it seems like it's a CORS issue. The request to extensionquery is blocked with `Cross Origin Resource Sharing error: Header disallowed by preflight response`

**Comment by wijiler** [comment]
I wanted help resolving this not saying derrrrrrrrrrrrr uh duplicate now stfu

**Comment by wijiler** [comment]
yes it is a duplicate but I said if anybody knows how to fix this help would be great. I did not get help
