### ISSUE TITLE
Right mouse menu find dependencies (...) missing

### ISSUE THREAD

**Issue by rohanatlarge** [microsoft/vscode#128883]
Issue Type: <b>Bug</b>

1: Start VS Code (either Windows 10, or Ubuntu 20.04)
2: VS Code opens up at last location (was editing React App)
3: Open up any javascript/typescript file (.js, .jsx, .ts, .tsx)
4: Right click on an object -- for instance name of a defined function

menu only shows:
Change All Occurences
Format Document
Format Document With
Source Action
Cut
Copy
Paste
Command Palette
Don't get any language intellicode either, intellisense only offers snippets as options.

Had upgraded to 1.58.2 recently. Issue started happening today. Tried disabling all extensions, no difference. Tried complete uninstall, and re-install to version 1.57.1. Issue still persists.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (15.73GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/usr/src/dojo/api --remote=wsl+Ubuntu-20.04 --crash-reporter-id 5c622570-0879-4027-b07e-abcbe09199c7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.96GB (18.57GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
auto-rename-tag|for|0.1.7
remote-containers|ms-|0.187.0
remote-wsl|ms-|0.56.5
vscode-print|pdc|0.9.8
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
prettier-vscode|esb|8.0.1
vscode-typescript-next|ms-|4.4.20210715

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by rohanatlarge** [comment]
Installed VS Code insiders all worked fine. Returned to VS Code 1.57.1; and initially it still wasn't working. But, this time when I explored the @builtin extensions, I noticed that the TypeScript Language Basics extension was disabled. I was able to enable it and now everything is back to normal. Got a few deadlines, not going to risk 1.58.2 at this point.
