### ISSUE TITLE
VS-CODE -BUG

### ISSUE THREAD

**Issue by RajrupDasid** [microsoft/vscode#128897]
Does this issue occur when all extensions are disabled?: Yes/No:NO

- VS Code Version:Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.49-1-MANJARO
Steps to Reproduce:

1.Hello i am facing an issue with python language server
2.its always crashing even if i uninstalled and reinstall python  extensions and removing other theme extensions .
3.even i followed a guide line written in 2019 where says how to only remove python language server and re installing  it .
noting seems to work , 
4.i did not tried vs code completely uninstall and reinstall again. should i tried that, 
5.Visual studio  code just depreciates my code work flow because for such annoying bugs , 
sometime very slow to load , weird buggy problems , 
6. I can remember an incident where i write some error handling code for python and it shows that python 2.7 is required for that work . why ? , it mess-up the viewing with bunch of squiggly lines ,    
7.suggestion:-python language server analyzer is not properly optimize , you need to increase it's indexing power,

vs code just need to improve more.

**Comment by IllusionMH** [comment]
/extPython

This is repo for VS Code editor itself and Python related functionality provided by Python extension.
Please ask questions about setup problems on StackOwerflow with detailed errors etc. or create a new issue in Python extension repo.

**Comment by RajrupDasid** [comment]
Thanks
