### ISSUE TITLE
Command + A no longer selects all files in "open editors"

### ISSUE THREAD

**Issue by elias6** [microsoft/vscode#128862]
Issue Type: <b>Bug</b>

Open some files in VS Code. Click any of the files in the "Open Editors" list on the left. Then press command+A.

Up until recently, it would select all the files in the list. But now, it selects the contents of the current file.

I miss the old behavior.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|--crash-reporter-id 8546bdc4-919c-427c-bd8c-2a7b47b5943e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
pyformat|giy|1.0.2
vscode-graphql|Gra|0.3.16
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
vsliveshare|ms-|1.0.4568
color-highlight|nau|2.4.0
fish-vscode|sky|0.2.1
language-stylus|sys|1.11.0
selectline-statusbar|tom|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
I can not reproduce, this works just fine for me. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
