### ISSUE TITLE
Windows default terminal profile selection misbehaves

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#128952]
Issue Type: <b>Bug</b>

The dropdown in the settings UI to select a default terminal profile on windows is broken. Every time I select a different profile a new empty item on the top of the list appears. The description of the items do not move however. Furthermore, the corresponding value in the settings.json will always be "PowerShell", no matter which item I select.

![grafik](https://user-images.githubusercontent.com/11841072/126071606-3704a24c-f078-4ed6-99a0-c915357c1a60.png)
![grafik](https://user-images.githubusercontent.com/11841072/126071614-df0062da-4bbd-469f-bc31-541a6c423899.png)
![grafik](https://user-images.githubusercontent.com/11841072/126071716-8625508d-0335-429d-a7ac-05e2deef3734.png)

VS Code version: Code - Insiders 1.59.0-insider (50b3811fdc5b5c80ca516a2edfffedcbd464b033, 2021-07-15T05:13:58.348Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.48GB free)|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by TylerLeonhardt** [comment]
This is odd.. the Linux and macOS ones have a drop down but the Windows one doesn't?
![image](https://user-images.githubusercontent.com/2644648/127571160-a737b93b-8b9f-41f4-9a17-3d6c632e10af.png)

**Comment by rzhao271** [comment]
@TylerLeonhardt I notice the settings have enum values of the following form: 
`enum: detectedProfiles?.os === OperatingSystem.Linux ? profileEnum?.values : undefined`

Therefore, you can validate the issue by making sure the Osx dropdown works. Definitely seems like a polish issue, though.

**Comment by TylerLeonhardt** [comment]
In that case, yes the macOS drop down did work.

**Comment by meganrogge** [comment]
@TylerLeonhardt that's by design. we don't show the windows/linux profiles enum /dropdowns when you're on an osx platform.

**Comment by vainamov** [comment]
There is still an entry in the dropdown labeled "Standard" that is otherwise empty but other than that, the issue seems to be resolved.
