### ISSUE TITLE
Java: toString is not in auto-completion list

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#12890]
Hi,

- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Java file which has 2 phrases:
  - `toString()`
  - `final long helloWorld = 0;`
2. Try auto-completion. While `helloWorld` is in the list, `toString` is not.

Would you please check? Personally I think it's weird. VSC can learn not-a-keyword `helloWorld`, but it cannot learn a... keyword `toString`?

Thanks,

---

_Edit:_ Related issue: #12619

---

_Edit_

I'm sorry I didn't mean keyword. I just wish that VSC doesn't filter out a phrase `toString`. Considering it accepts `helloWorld`, it should just simply accepts `toString`. Otherwise, it's weird.

Please don't think of "keywords", I know Java is not officially supported.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18932507/14e01e44-85d1-11e6-9265-a3ec059983e1.png)

**Comment by jrieken** [comment]
This is the best bug in a long time. Seem like we still use old school map somewhere. Any native property of JavaScript object aren't shown

<img width="405" alt="screen shot 2016-09-29 at 09 27 54" src="https://cloud.githubusercontent.com/assets/1794099/18944694/1c505ab2-8627-11e6-8721-4787eca3d0b4.png">

**Comment by jrieken** [comment]
There you go: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/services/editorSimpleWorker.ts#L127

fyi @alexandrudima

**Comment by joaomoreno** [comment]
Ahah nice one!
