### ISSUE TITLE
Busy spinner failing to render on InputBox, QuickInput, QuickPick controls

### ISSUE THREAD

**Issue by kirksl** [microsoft/vscode#128966]
- VS Code Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:
1. Clone https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample
2. Load and Debug Project
3. View -> Command Palette -> Quick Input Samples -> Click 'multiStepInput'
4. Click any resource group
5. Type unique name for application service and press enter key
6. Expect busy spinner to show in InputBox

This appears to be a regression in Version 1.44 as this was not an issue in Version 1.43.  See links below for further details.

Affected APIs
https://code.visualstudio.com/api/references/vscode-api#InputBox
https://code.visualstudio.com/api/references/vscode-api#QuickInput
https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E

Demonstration showing 1.43 did not have this issue
https://code.visualstudio.com/updates/v1_43
https://recordit.co/UAakJ0p5xy

Demonstration showing 1.44 regressed
https://code.visualstudio.com/updates/v1_44
https://recordit.co/5AwTbjkPsx

**Comment by TylerLeonhardt** [comment]
@kirksl 1.44 is pretty old... did you try this in a more recent version of vscode? We're at 1.58 already.

**Comment by kirksl** [comment]
@TylerLeonhardt Hello.  We were able to reproduce this issue on all versions of VSCode starting from 1.44 all the way to 1.58.

**Comment by alexweininger** [comment]
I'm having the same issue on 1.60-insiders. InputBox is not showing the loading state.


Version: 1.60.0-insider (Universal)
Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
Date: 2021-08-11T05:13:17.497Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0

**Comment by gar1t** [comment]
Same here:

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-39-generic snap

**Comment by SMoRG75** [comment]
Still an issue.

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by TylerLeonhardt** [comment]
Some work around the spinner has been done recently. Can you try in the [Insiders Build](https://code.visualstudio.com/insiders)?

If it still doesn't work, can you attach a gif? Like with https://gifcap.dev/

**Comment by SMoRG75** [comment]
I was a bit to quick, the spinner in QuickPick is working fine.
