### ISSUE TITLE
Drag-and-drop file within active workspace adds entry to recently opened list

### ISSUE THREAD

**Issue by seraku24** [microsoft/vscode#128925]
Issue Type: <b>Bug</b>

1. Open a folder or workspace.
2. Single-click a file from the file list to temporarily open the file.
3. Double-click a file from the file list to permenantly open the file.
4. Drag-and-drop a file from the file list to the editor pane to open the file within a particular editor group.

Expected:
In all cases, the file being opened is part of the active workspace/folder. It should be omitted from the recently opened file list.

Actual:
When dragging-and-dropping, a new entry is being added to the recently opened list unlike when simply single or double-clicking.

VS Code version: Code - Insiders 1.59.0-insider (50b3811fdc5b5c80ca516a2edfffedcbd464b033, 2021-07-15T05:13:58.348Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
I can reproduce. It seems like the editor area adds the dropped file to the recently opened list, thus forwarding to @bpasero

**Comment by seraku24** [comment]
Testing 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094), the issue seems to be fixed.
