### ISSUE TITLE
regarding gcc compiler

### ISSUE THREAD

**Issue by bhaskar-1909** [microsoft/vscode#128947]
Issue Type: <b>Bug</b>

after installing mingw and recognised by window powershell, gcc compiler is not recognised by vs code. After wasting whole a day to resolve this issue i have no option other than to report hopefully you will fix. Like in other ide we don't need such engage mind to encounter problems. Directly install and play with codes.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.72GB free)|
|Process Argv|--crash-reporter-id fc728ba0-47e3-470f-9f14-ffbab2df1d29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|2.1.23
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.5
beautify|Hoo|1.5.0
vscode-docker|ms-|1.14.0
csharp|ms-|1.23.13
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
powershell|ms-|2021.6.2
java|red|0.80.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by Tyriar** [comment]
When you launch the first VS Code window, a snapshot of the Windows environment is taken and used for all other windows. Not sure how you're trying to use the compiler, by an extension or terminal or something else but it probably needs to be on the PATH environment variable. Closing all windows and starting again will use an up to date environment.
