### ISSUE TITLE
Additional windows doesn't react (File -> New Window)

### ISSUE THREAD

**Issue by kolbma** [microsoft/vscode#128903]
Issue Type: <b>Bug</b>

Hello,

there has been introduced a bug with version 1.58.0 (still available in 1.58.2) in handling multiple open vscode windows. 

I try to open a new window from the current one via main menu.

The window opens, but it stays completely empty. 
It seems it doesn't react to keyboard short cuts and also not handling menu events. So I can show the main menu, and also open the main menu, but e.g. clicking "Open a file" doesn't show the dialog. Also "Help -> About" doesn't show a dialog. Pressing the short cut keys also doesn't show any reaction.

Closing the vs code window works only with window manager Alt+F4 and not the main menu.

If I start a new vs code instance there doesn't seem to be a problem with the additional window. So the problem is only when opening a new window from an existing one with the File menu -> New Window.

Edit:

The source of the problem seems to be the existing (old) window. I've just tried to open a different workspace in the new vscode instance, and then the window of the new instance becomes empty, although it showed already a workspace after opening.
Closing the 1st window and starting 2 fresh vscode instances the windows work. But I had this empty window behavior already multiple times. Not sure how to reproduce it always.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.3.18-lp152.81-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz (4 x 2245)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.62GB (1.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
EditorConfig|Edi|0.16.4
vscode-todo-plus|fab|4.18.4
rust-analyzer|mat|0.2.670
crates|ser|0.5.9
vscode-lldb|vad|1.6.5

</details>

**Comment by kolbma** [comment]
This screen recording shows the problem...
https://user-images.githubusercontent.com/5228369/126033517-9d4dcad3-d3aa-4a08-91ce-46c4a8e069bd.mp4

**Comment by karabaja4** [comment]
I can confirm this bug on my system as well:
Visual Studio code 1.58.2 (c3f1263)
Arch Linux
kernel 5.10.50-lts
nvidia 465.31

**Comment by deepak1556** [comment]
Can you launch with `code --verbose`, perform the steps in https://github.com/microsoft/vscode/issues/128903#issuecomment-881871366 and attach the log that is printed to the console. Thanks!

**Comment by karabaja4** [comment]
I will try and run vscode with --verbose, but the bug is very hard to reproduce. It seems to happen under very specific circumstances and after vscode has been running for a while. If I restart it it behaves normally again.

**Comment by mmahdigh** [comment]
I can confirm that this also happens on Windows 10.

**Comment by kolbma** [comment]
Do you all have seen this problem also when using vscode with a remote vscode-server like in a Docker container?  

I run it the whole day in verbose and it has not occurred a single time.  
So two possibilities, it is a race condition which would be relaxed with verbose logging, or it has to do with the remote dev container I've used today. But I've also opened local workplaces in the new windows.  
But nevertheless I'll switch tomorrow back to full local and I'll see if there are some log lines to report.

**Comment by deepak1556** [comment]
@mmahdigh are you running from a symlink path ?

**Comment by kolbma** [comment]
```
[15281:0721/094954.421312:INFO:CONSOLE(627)] "%cTRACE color: #888 [File Watcher (chokidar)]  >> normalized  [ADDED] /home/makolb/Source/Repos/rsudoku-rest/target/debug/.fingerprint/rsudoku-rest-7dbfabbbb4e82f1f/dep-bin-rsudoku-rest", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[15281:0721/095011.130729:INFO:CONSOLE(627)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-21T07:50:11.148Z] menubarService#updateMenubar 5
[15281:0721/095011.982458:INFO:CONSOLE(627)] "%cTRACE color: #888 Layout#layout, height: 846, width: 1590", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-21T07:50:13.803Z] menubar#runActionInRenderer { type: 'commandId', commandId: 'workbench.action.newWindow' }
[15281:0721/095013.818495:INFO:CONSOLE(627)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.newWindow", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-21T07:50:13.824Z] windowsManager#open
[main 2021-07-21T07:50:13.825Z] windowsManager#open pathsToOpen [ [Object: null prototype] {} ]
[main 2021-07-21T07:50:13.829Z] IPC Object URL: Registered new channel vscode:61b8e5a2-b88a-408d-9cb5-2aa95fa571cf.
[main 2021-07-21T07:50:13.831Z] window#validateWindowState: validating window state on 1 display(s) {
  width: 1024,
  height: 768,
  mode: 1,
  x: 312,
  y: 93,
  hasDefaultState: true
}
[main 2021-07-21T07:50:13.831Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1589, height: 870 }
[main 2021-07-21T07:50:13.832Z] window#ctor: using window state {
  width: 1024,
  height: 768,
  mode: 1,
  x: 312,
  y: 93,
  hasDefaultState: true
}
[main 2021-07-21T07:50:13.833Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-07-21T07:50:14.084Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 0, emptyToOpen: 1)
[15281:0721/095014.092228:INFO:CONSOLE(627)] "%cTRACE color: #888 Layout#layout, height: 871, width: 1590", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (627)
[main 2021-07-21T07:50:14.481Z] resolveShellEnv(): running (macOS/Linux)
[15281:0721/095014.556881:INFO:CONSOLE(65)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (65)
[15281:0721/095014.578348:INFO:CONSOLE(6)] "Not allowed to load local resource: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/loader.js (6)
[15281:0721/095014.588192:INFO:CONSOLE(3)] "Loading "vs/css!vs/workbench/workbench.desktop.main" failed", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/loader.js (3)
[15281:0721/095014.588330:INFO:CONSOLE(3)] "Error: Could not find file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css or it was empty", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/loader.js (3)
[15281:0721/095014.588457:INFO:CONSOLE(3)] "Here are the modules that depend on it:", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/loader.js (3)
[15281:0721/095014.588533:INFO:CONSOLE(3)] "===anonymous1===", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/loader.js (3)
```

The file from `Not allowed to load local resource: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css` and same `"Error: Could not find file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.css or it was empty"` exists and is not empty.  
Is it related to Workspace Trust feature?

**Comment by kolbma** [comment]
BTW [This](https://github.com/microsoft/vscode/issues/128903#issuecomment-883979520) happens also when changing workspace in a single window.

**Comment by deepak1556** [comment]
Thanks for the logs, the issue is not related to workspace trust but rather the resource loading protocol is incorrect. Are you able to reliably reproduce the issue ? If so, can you try launching like `code --user-data-dir /tmp/vscode-resource-check` and see if the problem happens.

**Comment by Huluti** [comment]
Happens also on Windows.

**Comment by kolbma** [comment]
@deepak1556 To your question in https://github.com/microsoft/vscode/issues/128903#issuecomment-884043497 ...

Yes, when using a fresh and __empty user-data-dir__ I can reproduce it. Reliably is a different question. It happens quite often, but I don't have the steps to reproduce it _always_. After some working with vscode it _happens_ on local workplace switch or opening new windows.

The only thing I have added to the new __user-data-dir__ are these settings in _User/settings.json_:

```
{
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.accessibilitySupport": "off",
    "editor.fontFamily": "'Cascadia Code', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.minimap.scale": 2,
    "editor.scrollBeyondLastLine": false,
    "explorer.autoReveal": false,
    "files.insertFinalNewline": true,
    "rust.wait_to_build": 1500,
    "rust.all_targets": false,
    "rust-client.engine": "rust-analyzer",
    "rust-client.autoStartRls": false,
    "rust-analyzer.cargo.allFeatures": true,
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "terminal.external.linuxExec": "/usr/bin/xfce4-terminal",
    "update.enableWindowsBackgroundUpdates": false,
    "window.menuBarVisibility": "toggle",
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.enableExperiments": false,
    "workbench.list.openMode": "doubleClick",
    "workbench.startupEditor": "none",
    "workbench.statusBar.feedback.visible": false
}
```

**Comment by deepak1556** [comment]
Thanks for testing, I was able to get a reliable repro from another report https://github.com/microsoft/vscode/issues/128745#issuecomment-885433198 . Can you confirm if you are using the external terminal action ?

**Comment by kolbma** [comment]
@deepak1556  Yes, opening an external terminal/console (Ctrl+Shift+C) and afterwards trying to open new window or changing workspace doesn't work. That reproduces it always immediately.  
Great catch from @psulek !

**Comment by deepak1556** [comment]
The root issue has been identified, I will merge this to https://github.com/microsoft/vscode/issues/128745. Please follow that issue for updates.
