### ISSUE TITLE
cannot connect to marketplace

### ISSUE THREAD

**Issue by brokedevs** [microsoft/vscode#128926]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.58.0 | 2d23c42a936db1c7b3b06f918cde29561cc47cd6 | x64
- OS Version: 5.10.49-1-MANJARO

Receiving error message: We cannot connect to the Extension Marketplace at this time, please try again later!

**Comment by tamuratak** [comment]
duplicate of #128583
