### ISSUE TITLE
Can't debug GNU assembler on Raspberry Pi 4 

### ISSUE THREAD

**Issue by mark-b1980** [microsoft/vscode#128951]
- VS Code Version: 1.58.2
- OS Version: Kali Linux ARM 64 (Raspberry Pi) v. 5.4.83 (2021.2) - but I have the same issue on Rasbian

Steps to Reproduce:

1. Install dan-c-underwood.arm
2. Write code 
3. Created a Makefile:

```
build: test.o
    aarch64-linux-gnu-ld test.o -o test

test.o: test.asm
    aarch64-linux-gnu-as test.asm -o test.o

clean: 
    rm *.o
    rm test
```
_Without a Makefile VS Code don't even try to run gdb._

4. Error message in the terminal:

`GDB: Failed to set controlling terminal: Operation not permitted`

**Comment by weinand** [comment]
VS Code has no built-in support for gdb. So either you have to install a debug extension for gdb, or in case you did this already (but failed to include this info here), it is an extension issue.

**Comment by mark-b1980** [comment]
I tryed 2 or 3 plugins with the same result. I think more I would need a launch.json to tell exact what to do and what to start...

**Comment by weinand** [comment]
I suggest to ask on https://stackoverflow.com for how to debug GNU assembler on Raspberry Pi 4 and what extensions to use.

The debug configurations in a launch.json are specific to individual debug extensions. But please read https://code.visualstudio.com/docs/editor/debugging for an overview.
