### ISSUE TITLE
Jupyter Notebooks don't display images

### ISSUE THREAD

**Issue by kartzke** [microsoft/vscode#128932]
Issue Type: <b>Bug</b>

## Issue summary
I recently cloned this respository to my local: https://github.com/djay/covidthailand

Using the notebook UI in VS Code, all the images are broken.

Using the standard Jupyter notebook UI in the web browser renders all images.

## Steps to reproduce
* Clone this repository: https://github.com/djay/covidthailand
* Create the environment using python 3.9 and the included `requirements.txt` file
* Open `working.ipynb` in both VS Code and a web browser

## Expected result
* All images load in both notebooks

## Actual result
* Images only load in the web browser notebook

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:12.490Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 98ab1729-27d3-463a-b961-152d16ee9e3f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remotefs|lix|0.0.16
sftp|lix|1.12.9
vscode-docker|ms-|1.14.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-data-preview|Ran|2.3.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by kartzke** [comment]
Attaching screenshots to show the UI:

## VS Code:
![image](https://user-images.githubusercontent.com/713503/126055638-68c2fa33-0b41-471c-8435-fdd3ed1af320.png)

## Jupyter Notebook
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/713503/126055659-ce8d62be-0134-497f-858c-9a97f000a5dd.png">

![image](https://user-images.githubusercontent.com/713503/126055669-a9932807-4554-4f91-ba0c-052f4e3e7cfb.png)

**Comment by DonJayamanne** [comment]
This is a known issue in jupyter notebooks in vscode. This is blocked by https://github.com/microsoft/vscode/issues/123021
