### ISSUE TITLE
Dragging File Tab Out Of VSC No Longer Creates Copy Of File

### ISSUE THREAD

**Issue by Danielelkhal** [microsoft/vscode#128975]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 Version 1909

In previous versions of VSC it was possible to drag the tab of a file to the file explorer to create a copy of the file. 
In version 1.56 it was working correctly however I recently updated to 1.58.2 and it no longer works. 
No errors are received, nothing happens now when the tab is dragged outside the window.
I have tested this on 3 different laptops with the same results.
Was this feature removed? I read through the updates but did not see any reference to it being removed.

Steps to Reproduce:

1.Open visual studio and load the required file.
2.Drag the tab out of the window.

I attached a gif to show the issue.

Thank you in advance!

https://user-images.githubusercontent.com/22788398/126139505-8c0e9995-9bb5-48eb-9122-895e842f0ceb.mp4

**Comment by bpasero** [comment]
Unfortunately this is possibly something we may not be able to fix:

https://github.com/microsoft/vscode/blob/a7c466d64983d71b066cf6ce50a4559e41b3042a/src/vs/workbench/browser/dnd.ts#L290-L295

Merging into https://github.com/microsoft/vscode/issues/164

**Comment by bpasero** [comment]
Hm, actually it looks like I might be able to fix this even with the new `vscode-file` protocol by simply enforcing a `file` protocol. This way of data transfer seems to bypass our protocol handler entirely so it is somehow managed internally in Chrome.

**Comment by rctneil** [comment]
Is there likely to be a fix for this?  I'm experiencing it, not when dragging a tab, but when a dragging a file from the sidebar file listing, outside the VSCode window, onto my MacOS Desktop.

**Comment by bpasero** [comment]
Yes that should work in latest insiders now. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by janosh** [comment]
Will this be in the August release or before?

**Comment by bpasero** [comment]
This fix will be available in VSCode `1.60` to be released first week of September.
