### ISSUE TITLE
VSCODE DOES NOT OPENING

### ISSUE THREAD

**Issue by Picoseconds** [microsoft/vscode#128957]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 10.0.22000.65

Steps to Reproduce:
I think you can't
1. Open VSCode
2. See this: 
![image](https://user-images.githubusercontent.com/56701269/126082591-81e229ae-3910-4597-a6f2-99e7638da800.png)

**Comment by deepak1556** [comment]
Are you opening from a symlink folder ?

**Comment by Picoseconds** [comment]
No, I am not.

**Comment by Picoseconds** [comment]
No new DOM elements are ever created except for the ones saved in AppData

**Comment by Picoseconds** [comment]
If I delete that folder it just becomes pure black with no elements which is expected because there would be no saved information

**Comment by Picoseconds** [comment]
Never mind I am starting it from a symlink I am an idiot

**Comment by deepak1556** [comment]
No worries, you hit the same issue as https://github.com/microsoft/vscode/issues/128725, might want to follow that issue for updates if interested.
