### ISSUE TITLE
Can't change publisher owner to Google Domain Email(But I've registered it as a Microsoft Account)

### ISSUE THREAD

**Issue by huacat1017** [microsoft/vscode#128906]
I registered a Microsoft Account(using Gmail Domain) and I went to [Marketplace Manage Page](https://marketplace.visualstudio.com/manage) to change Publisher owner to my new account. But when I typeed my Email, I got Invalid domain error.
Like That:
![ERROR](https://user-images.githubusercontent.com/57604590/126034073-c13f489e-2f18-49f4-ac5d-9f09f0badcc4.png)

**Comment by TylerLeonhardt** [comment]
@huacat1017 thanks for opening this! However, this is the VS Code repo. You're looking for the marketplace repo which is:
https://github.com/microsoft/vsmarketplace

Can you open this over there? Thanks!

**Comment by huacat1017** [comment]
OK!
