### ISSUE TITLE
duplicated item in launch menu

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [microsoft/vscode#128988]
Does this issue occur when all extensions are disabled?: Hard to say, I'm running from WSL code I cannot disable all the extensions.

Duplication in launch menu (api.go is there twice)
![image](https://user-images.githubusercontent.com/43439912/126165137-6e603e49-78f9-41ba-88f7-bf470a854c30.png)

Steps to Reproduce:
content of `launch.json`
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    {
        "name": "api.go",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceFolder}/api/api.go",
 
        // "env": {"HOSTNAME":"0.0.0.0", "PORT":"8123"}
        "envFile": "${workspaceFolder}/api/local.env"
    },
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}"
        }
    ]
}
```

 * when I rename `api.go` entry in `launch.json` to `api2.go`  then the only first item in menu gets renamed.
 * when I click on 2nd `api.go` in menu I get `Configuration 'api.go' is missing in 'launch.json'.`

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (9.56GB free)|
|Process Argv|--crash-reporter-id d80678b5-691e-4e9b-a3e3-43ec75e8f982|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|24.88GB (18.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|24.88GB (18.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|24.88GB (18.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|24.88GB (18.32GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
errorlens|use|3.3.1
vscode-todo-highlight|way|1.0.4
jcl-language-support|bro|1.0.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
shell-format|fox|7.1.0
vscode-lombok|Gab|1.0.1
go|gol|0.26.0
vscode-test-explorer|hbe|2.20.4
ibm-jcl|kel|0.11.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1013163132
test-adapter-converter|ms-|0.0.13
vscode-groovy-lint|Nic|1.4.0
gotestexplorer|pre|0.1.13
fabric8-analytics|red|0.3.3
java|red|0.80.0
vscode-commons|red|0.0.6
code-spell-checker|str|1.10.2
shellcheck|tim|0.14.4
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
markdown-all-in-one|yzh|3.4.0
vscode-extension-for-zowe|Zow|1.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/121148
