### ISSUE TITLE
Add active workspace folder event and collections to API

### ISSUE THREAD

**Issue by 4086606** [microsoft/vscode#128941]
At PKief/vscode-material-icon-theme#208, we would like to apply workspace configurations for active workspaces only.
This would be available in a `vscode.workspace.activeWorkspaceFolders: WorkspaceFolder[]` collection.
This could also benefit from an event emitter such as `vscode.workspace.onDidChangeActiveWorkspaces`.
There should also probably be a `WorkspaceFolder.active` property.

**Comment by jrieken** [comment]
Can you explain what's making a workspace folder "visible"

**Comment by 4086606** [comment]
The subset of `vscode.workspace.workspaceFolders` that belongs to the active window.

**Comment by 4086606** [comment]
I realise that my terminology is off and I should probably go with "active" instead of "visible".

**Comment by jrieken** [comment]
> The subset of vscode.workspace.workspaceFolders that belong to the active window.

Don't they all belong to the active window? The extension host is always scoped to a single window and doesn't know anything about other windows so by that logic all workspaceFolders are active

**Comment by 4086606** [comment]
Active = when the window is in focus in this case

**Comment by jrieken** [comment]
There is `vscode.window.state` or type [WindowState](https://github.com/microsoft/vscode/blob/7422b951b4ce6f2463ac26258d8953d3676dd0b8/src/vs/vscode.d.ts#L8526-L8526)

**Comment by 4086606** [comment]
Is the extension host shared across windows? Is it technically possible for these windows to become aware of each other, perhaps by localStorage?

**Comment by jrieken** [comment]
The extension host is always scoped to a single window and doesn't know anything about other windows

**Comment by 4086606** [comment]
So in theory I could poll `vscode.window.state` with a highish-frequency cron job?

**Comment by jrieken** [comment]
If you wanna be a back extension "yes", if you wanna be a good extension you read a little further and discover `vscode.window.onDidChangeWindowState`

**Comment by 4086606** [comment]
Alright `vscode.window.onDidChangeWindowState` it is :)

**Comment by 4086606** [comment]
Needs `question` flair seeing as its doable atm
