### ISSUE TITLE
Terminal scrollbar is missing when terminal is positioned to the right

### ISSUE THREAD

**Issue by ZeusDeus** [microsoft/vscode#128946]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.57.1
- OS Version: Pop!_OS 21.04 

Steps to Reproduce:

1.  set  "workbench.sideBar.location": "right" inside settings.json
2.  mouse over where terminal scollbar should appear
2. terminal scrollbar does not show. It only appears if you split the terminal or set "workbench.sideBar.location": "bottom" 
![DeepinScreenshot_20210718144837](https://user-images.githubusercontent.com/49918855/126065867-7f214932-d330-4d0d-97ac-9bdb73623cff.png)
![DeepinScreenshot_gjs_20210718144919](https://user-images.githubusercontent.com/49918855/126065883-fcc2d00d-4a4f-4968-8dd4-6384da1d756a.png)

**Comment by meganrogge** [comment]
you're on an old version of vscode - update to fix this
