### ISSUE TITLE
Sign in failed: FetchError: request failed, reason: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by BranchScope** [microsoft/vscode#128910]
## Issue
**I'm getting this error trying to sign in GitHub on VS Code:**

`Sign in failed: FetchError: request to https://vscode-auth.github.com/token?code=<code>&state=<state> failed, reason: getaddrinfo EAI_AGAIN vscode-auth.github.com`

![2021-07-17_13-44](https://user-images.githubusercontent.com/39023184/126035910-44214cf2-6ec2-4096-80d2-b49bfa215724.png)

## Additional infos
**Idk the reason, but i can give you more info about:**

- **OS:** `Arch Linux` 
- **Kernel:** `5.12.15-arch1-1`
- **Network:** `ethernet with neither proxy nor custom dns`
- **VS Code Version:** `1.58.0-1`
- **VS Code Marketplace version:** `1.54.3-4` (added manually due to an issue that blocked me from fetching extensions on VS Code)

**Comment by PeterQiu0516** [comment]
Same error here, on Ubuntu Linux

**Comment by TylerLeonhardt** [comment]
I looked this error up because I've not seen it before and I'm not confident there's anything we can do here besides add even more retry logic.

The issue seems to be a DNS issue on GitHub's auth server side and it happens for a variety of reasons and the best thing to do is just to try again.

https://github.com/nodejs/node/issues/15780
https://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html
https://github.com/npm/npm/issues/15059

**Comment by BranchScope** [comment]
I actually fixed by restarting docker as said here: https://github.com/nodejs/node/issues/15780#issuecomment-605418938

**Comment by rebecamurillo** [comment]
Restart did not work for me. 
Instead I did : 
- Stop docker : systemctl stop docker
- Sign in VsCode with Github ... => signin OK this time
- Start docker again : systemctl start docker

**Comment by bosonbeard** [comment]
This problem is still actual i have next error message:
'Sign in failed: FetchError: request to https://vscode-auth.github.com/token?code=7fd92eXXXXXXbe5c7dd6&state=5f849e53-3566-XXXX-XXXX-c767be09c2dc failed, reason: unable to get local issuer certificate"

**Comment by marcovc** [comment]
I'm having this problem as well, and restarting Docker doesn't help (why would it anyway?)

**Comment by getx-Pro** [comment]
> 

Is docker necessary to install for running copilot. And thanks for replying

**Comment by ThePresence** [comment]
I'm also getting the same error. "Sign in failed: FetchError: ....reason: getaddrinfo ENOTFOUND vscode-auth.github.com"

**Comment by EdKamau** [comment]
I am getting the same issue with GitHub Copilot. Any solutions?!

**Comment by ThePresence** [comment]
> I am getting the same issue with GitHub Copilot. Any solutions?!

Restarting VSCode after the installation solved the problem for me.

**Comment by harshitpheonix** [comment]
> > I am getting the same issue with GitHub Copilot. Any solutions?!
> 
> Restarting VSCode after the installation solved the problem for me.

Same for me

**Comment by Ad0lphus** [comment]
[INFO] [default] [2022-01-09T18:10:22.886Z] Experimentation service initialized
[ERROR] [default] [2022-01-09T18:10:43.242Z] GitHub Copilot could not connect to server. Extension activation failed: "getaddrinfo EAI_AGAIN api.github.com"
[INFO] [default] [2022-01-09T18:11:13.252Z] Stringified features: {"copilotaa":"false","copilotincludeprompt":"eager"}
[INFO] [default] [2022-01-09T18:11:13.252Z] Feature for copilotaa: false
[INFO] [default] [2022-01-09T18:11:13.252Z] Feature for copilotincludeprompt: eager
[INFO] [default] [2022-01-09T18:11:13.252Z] Feature for copilotset1: undefined
[INFO] [default] [2022-01-09T18:11:13.252Z] Feature for copilotghgh: false
[INFO] [default] [2022-01-09T18:11:13.252Z] Feature for copilotfim: false

it was working till yesterday. not sure what happened

**Comment by sxwebster** [comment]
I'm getting the same issue - restarting does not affect the outcome. Happens in both VSCode on windows as a regular extension, and when VSCode is running attached to WSL and the extension are installed via WSL.

**Comment by danielbellhv** [comment]
> I'm getting the same issue - restarting does not affect the outcome. Happens in both VSCode on windows as a regular extension, and when VSCode is running attached to WSL and the extension are installed via WSL.

Same here. Any update? Cool if not

**Comment by timini** [comment]
it ded

**Comment by sxwebster** [comment]
> it ded

Pretty sure I wound up finding out that whatever I was looking at when I posted lacked proxy support

**Comment by captainyakult** [comment]
For me, the problem was with my git credentials manager. Following the instruction here fixed it:
https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/rename.md

**Comment by puffitos** [comment]
Had the same problem when connecting to a remote machine via SSH. I fixed this thanks to a hint by a colleague. Use your HTTP proxy in your settings.json (either the local ones or the remotes one, depending on where you're working):

#settings.json
```json
{
  "http.proxy": "http://10.91.6.12:443"
}
```

**Comment by melsonic** [comment]
```

[error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2023-03-13 17:11:43.198 [error] Error: net::ERR_INVALID_ARGUMENT
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:105:7047)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)

```

I guess this happends when i set `http.proxyAuthorization` to `true` or `false`. When I comment that like it works well. But when i commented that like I was not able to sign in using my github account.

**Comment by Robinlovelace** [comment]
Also hitting this, linked to the extension, Copilot related I think:

```
[ERROR] [default] [2024-01-31T11:07:29.113Z] Extension activation failed: "getaddrinfo EAI_AGAIN api.github.com"
```

![image](https://github.com/microsoft/vscode/assets/1825120/ccba5198-d474-44f7-8248-af787a6adaa9)

**Comment by dvlprroshan** [comment]
I have added the IP address 185.199.108.133 for raw.githubusercontent.com in the /etc/hosts file and restarted my Docker service.

**Comment by YoucanBaby** [comment]
> Also hitting this, linked to the extension, Copilot related I think:
> 
> ```
> [ERROR] [default] [2024-01-31T11:07:29.113Z] Extension activation failed: "getaddrinfo EAI_AGAIN api.github.com"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1825120/301138623-ccba5198-d474-44f7-8248-af787a6adaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ3MTEsIm5iZiI6MTcxNTA1NDQxMSwicGF0aCI6Ii8xODI1MTIwLzMwMTEzODYyMy1jY2JhNTE5OC1kNDc0LTQ0ZjctODI0OC1hZjc4N2E2YWRhYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDQwMDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNkYzliOWRiYzI2N2JlMTczMDVjYjEyNzRiYjFjYWVmOTQ2MGNjNWQ2ODM3NzY1MWJmMjhjMTNlMDNiNjkwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a4t0RNTodVe4eZ8WmVSEBW41rxSRmzLW50FYYw9j3Nc)



> Also hitting this, linked to the extension, Copilot related I think:
> 
> ```
> [ERROR] [default] [2024-01-31T11:07:29.113Z] Extension activation failed: "getaddrinfo EAI_AGAIN api.github.com"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1825120/301138623-ccba5198-d474-44f7-8248-af787a6adaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTQ3MTEsIm5iZiI6MTcxNTA1NDQxMSwicGF0aCI6Ii8xODI1MTIwLzMwMTEzODYyMy1jY2JhNTE5OC1kNDc0LTQ0ZjctODI0OC1hZjc4N2E2YWRhYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDQwMDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNkYzliOWRiYzI2N2JlMTczMDVjYjEyNzRiYjFjYWVmOTQ2MGNjNWQ2ODM3NzY1MWJmMjhjMTNlMDNiNjkwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a4t0RNTodVe4eZ8WmVSEBW41rxSRmzLW50FYYw9j3Nc)

Same error. Could you please tell me how to fix this error?

**Comment by YoucanBaby** [comment]
I get the same error when use "github-copilot".

The solution is: 
  1. open vscode setting, 
  2. search proxy
  3. input proxy address
  
![image](https://github.com/microsoft/vscode/assets/43912540/1def9c8d-a0b1-46eb-b1cc-0eb21745e9d7)

**Comment by TheDave35** [comment]
It's was in my venv file not /etc/resolv.conf of the host:
```
.venvdave@mini-pc:~/t$ cat /etc/resolv.conf 

nameserver 127.0.0.53 **-> replace ip by your dns server or 8.8.8.8**
options edns0 trust-ad
search .
```

It did the trick
