### ISSUE TITLE
 Support for "function inline parameters hints"

### ISSUE THREAD

**Issue by birraasmile** [microsoft/vscode#128934]
One thing I always wished  for but does not yet landed is seeing parameter hints to make code more readable and easier to understand.  I believe it gives additional helpful context when reading a code, mainly making easier to understand what different function parameters refer to by showing the parameter's name inline. 

I have seen a couple of extensions but they are quite limited in the number of languages supported.

I appreciate any of your consideration to make this happen in the future release of this awesome tool.

vscode become the goto editor for me and thank you for your continuous efforts in making it even better. thanks

**Comment by IllusionMH** [comment]
There is editor API and initial implementation for JS/TS in Insiders build + Nightly TS builds
https://github.com/microsoft/vscode/issues/16221#issuecomment-879538951

For other languages this functionality should be provided by corresponding extensions.
