### ISSUE TITLE
Whitespaces changes not ignored in Merge Conflict View

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [microsoft/vscode#128976]
Issue Type: <b>Bug</b>

It seems the case that there is either no option for ignoring whitespace changes for Merge Conflicts. There is one for the Diff Editor, and it is working there. But If you change lets say the line ending sequence of a file and that is a Merge Conflict or there is another merge conflict in the file, the whole file lights up as a change also if you only want to fix the merge conflict that is a non-whitespace change.

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.89GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jenkins-status|ale|4.2.1
conflict-squeezer|ang|1.0.1
vscode-apollo|apo|1.19.4
atlascode|atl|2.9.1
cyberpunk-2020|Car|0.1.4
path-intellisense|chr|2.3.0
vscode-jq-playground|dav|4.2.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vscode-firefox-debug|fir|2.9.4
linter|fna|0.0.4
auto-close-tag|for|0.5.11
auto-rename-tag|for|0.1.7
vuetify-snippets|Gai|0.1.2
gitlab-workflow|Git|3.26.0
vue-snippets|hol|1.0.4
rest-client|hum|0.24.5
output-colorizer|IBM|0.1.2
vscode-postfix-ts|ipa|1.9.4
jenkins-pipeline-linter-connector|jan|1.2.0
jq-syntax-highlighting|jq-|0.0.2
vscode-codemetrics|kis|1.24.0
inline-parameters|lia|0.2.1
codeacejumper|luc|3.3.2
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
test-adapter-converter|ms-|0.0.10
vsliveshare|ms-|1.0.4580
vsliveshare-audio|ms-|0.1.91
gremlins|nho|0.26.0
angular-console|nrw|17.6.1
vetur|oct|0.34.1
vscode-versionlens|pfl|1.0.9
polacode|pnp|0.3.4
vuetify2-jest-snippets|pra|0.0.2
jenkinsfile|rec|1.2.0
vscode-yaml|red|0.21.1
vue-vscode-snippets|sdr|2.2.1
jenkins-jack|tab|1.1.5
vscode-conventional-commits|viv|1.21.3
vuetify-vscode|vue|0.2.0
quokka-vscode|Wal|1.0.386
wallaby-vscode|Wal|1.0.298

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by chrmarti** [comment]
The merge conflict is given as textual markers in the file by Git. So it's not VS Code computing the diff.

https://stackoverflow.com/questions/9776527/merging-without-whitespace-conflicts might be of help.

**Comment by sschneider-ihre-pvs** [comment]
ok, so how can I add `-Xignore-space-change` to vscode then?

**Comment by chrmarti** [comment]
@eamodio Is there a way to add options to the Git merge commands triggered through the UI?

**Comment by eamodio** [comment]
There isn't any option for adding flags to the merge command. You might be able to get the desired result by setting the following git config: https://git-scm.com/docs/git-config#Documentation/git-config.txt-applyignoreWhitespace but it would always apply which may not be desired.
