### ISSUE TITLE
App/Electron won't start on macOS Sierra 10.12

### ISSUE THREAD

**Issue by tmcentee** [Microsoft/vscode#12894]
- VSCode Version: 1.5.3
- OS Version: macOS Sierra 10.12

I cannot get the latest .app to startup properly, either from the .app release or building from source.

When trying to run the .app, it immediately exits without a crash message/etc. I went into the app bundle and tried to run Electron directly and it simply exits without warning/error.

<img width="686" alt="screen shot 2016-09-28 at 10 53 05 am" src="https://cloud.githubusercontent.com/assets/17259755/18921287/d1df4d52-8569-11e6-84e3-2a312fd7b263.png">

When building/running from source, everything compiles and is running (under `npm run watch`) but no Electron window shows. There are also no errors reported in the process. 

<img width="769" alt="screen shot 2016-09-28 at 10 54 18 am" src="https://cloud.githubusercontent.com/assets/17259755/18921326/ef5b95b6-8569-11e6-8dcb-d259392f0cd9.png">

I know this is likely a config issue on my computer, but any debugging tips would be gladly appreciated.

Thanks!

**Comment by bpasero** [comment]
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

Please also see: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by nebev** [comment]
I had the same issue. Insiders build works just fine for me.

**Comment by bpasero** [comment]
@tmcentee can you try

**Comment by tmcentee** [comment]
The latest insider build worked for me.

**Comment by bpasero** [comment]
@tmcentee does it hang for you with high CPU when you run `gulp watch`? we sometimes see this too and then only a forced kill of the process and restart helps. So far we did not find out what is causing it though.

To verify what you should see before you can run out of sources:

![image](https://cloud.githubusercontent.com/assets/900690/18960343/b11f61e6-8669-11e6-9149-852e77252cc2.png)

**Comment by tmcentee** [comment]
@bpasero  Here's what I get on `gulp watch`. It sat for about 15 seconds at 100% CPU before completing. 

<img width="1109" alt="screen shot 2016-09-29 at 10 27 54 am" src="https://cloud.githubusercontent.com/assets/17259755/18960459/727fac96-862f-11e6-94fe-9e29b8984e2e.png">

**Comment by bpasero** [comment]
@tmcentee so the gulp task stays on high CPU all the time? What node.js version are you on? Does it help to 
* git clean -xfd
* scripts/npm.sh install

**Comment by tmcentee** [comment]
@bpasero It's high until the compilation step is done.

Here's node/npm versions. 

<img width="315" alt="screen shot 2016-09-29 at 10 39 11 am" src="https://cloud.githubusercontent.com/assets/17259755/18961077/6ac30564-8631-11e6-99a0-420bb424e00d.png">

This is all from a clean checkout of the source. I did the clean/install again anyway and got the same result.

**Comment by tmcentee** [comment]
@bpasero @nebev I got this resolved by booting into Safe Mode. Must've cleared some corrupt cache somewhere. Thanks for all the help!

**Comment by ChrisFan** [comment]
> I got this resolved by booting into Safe Mode.

@tmcentee dose it work in "Normal" Mode now?
I just come across the same issue, could you please give me more details about how you fix it.

**Comment by tmcentee** [comment]
@ChrisFan Sorry I should've explained a bit more. Booting into Safe Mode clears/recreates some application caches. 

I then rebooted back into macOS normally and everything worked fine.
