### ISSUE TITLE
UnderLine Linux not showing (don't close issues re linux underscore you @Tyriar)

### ISSUE THREAD

**Issue by arash-bizcover** [microsoft/vscode#128967]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.58.2
- Commit: c3f126316369cd610563c75b1b1725e0679adfb3
- Date: 2021-07-14T22:30:16.440Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Linux x64 5.4.0-77-generic

Steps to Reproduce:

1. Just open the integrated terminal and type "_"

**Comment by arash-bizcover** [comment]
https://github.com/microsoft/vscode/issues/35901

**Comment by arash-bizcover** [comment]
https://github.com/microsoft/vscode/issues/35901

**Comment by arash-bizcover** [comment]
https://github.com/microsoft/vscode/issues/107942

**Comment by IllusionMH** [comment]
Looks like duplicate of #123077

Fix should be available in Insiders builds https://code.visualstudio.com/insiders/

Is it reproducible for you in Insiders builds?

**Comment by arash-bizcover** [comment]
Thanks, @IllusionMH I just checked the insiders, it has been fixed there.

Could we not close this until it has been deployed to [vs code ](https://code.visualstudio.com/)

**Comment by IllusionMH** [comment]
Issues are closed when they are resolved in master. Keeping this open does not help.
I don't think that it make sense to keep this one open as it's clearly duplicate of another issue that is resolved, has milestone and tags.

**Comment by arash-bizcover** [comment]
Understood @IllusionMH
