### ISSUE TITLE
Ctrl + f does not get to shell, despite having added exception to keyboard shortcuts

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode#128914]
Issue Type: <b>Bug</b>

**Reproduce**

1. Follow the documentation https://code.visualstudio.com/docs/editor/integrated-terminal#_find and add the following to the keyboard shortcut settings (that's what I assume where the setting should go, the docs don't specify):
```
// Windows/Linux
{ "key": "ctrl+f", "command": "-workbench.action.terminal.focusFind",
                      "when": "terminalFocus" },
// macOS
{ "key": "cmd+f",  "command": "-workbench.action.terminal.focusFind",
                      "when": "terminalFocus" },
```

2. Open integrated terminal.

3. Press `ctrl+f` and observe results.

**Expected results**: `ctrl+f` gets sent to shell

**Actual results**: `ctrl+f` triggers Find in terminal.

**Thoughts**
It could be that I misunderstand the documentation, and should add the snippet in a different place. But in that case the documentation is bad and should be changed.

![image](https://user-images.githubusercontent.com/25161793/126040427-023a3598-8b21-4a77-8158-bf6ec96e6db1.png)

**System details**

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 1648)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (7.87GB free)|
|Process Argv|--unity-launch --crash-reporter-id 56d17e75-4070-4535-8292-5cdd09c86224|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by ArturoDent** [comment]
I see the same thing you do.  However, if you go to the KeyBoard Shortcuts and disable the `workbench.action.terminal.focusFind` it generates this deletion in your keybindings.json:

```jsonc
{
  "key": "ctrl+f",
  "command": "-workbench.action.terminal.focusFind",
  "when": "terminalFindFocused && terminalProcessSupported || terminalFocus && terminalProcessSupported"
},
```

which works for me.  And the entire `when` clause seems to be required.  So the documentation is bad and should reflect the working version above.

**Comment by meganrogge** [comment]
You can set `terminal.integrated.sendKeybindingsToShell` to send ctrl f to the shell
