### ISSUE TITLE
Doesn't connect to extensions marketplace

### ISSUE THREAD

**Issue by hkntrt** [microsoft/vscode#128979]
Issue Type: <b>Bug</b>

When I try to look up for an extension it says "we cannot connect to the extensions marketplace at this time". Upgrading from version 1.56 to 1.58 on Arch Linux results in this error. No proxy, no additional network settings. It's not related to my personal setup. Possible culprit is CORS error. The network request to marketplace fails due to CORS error.

VS Code version: Code - OSS 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-12T23:51:36.303Z)
OS version: Linux x64 5.12.15-arch1-1
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2756)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.68GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by VanGoethe** [comment]
Had the same issue once, i was able to solve it by modifying `~/.vscode/argv.json ` file by adding `"enable-browser-code-loading": false`

hope it works for you too

credit: to @xip-niekneuij at
 https://www.bswen.com/2021/07/others-how-to-solve-can-not-connect-extensions-marketplace1.html

**Comment by hkntrt** [comment]
@VanGoethe yes it solves the issue, thank you.

**Comment by MiloslavStekrt** [comment]
> Had the same issue once, i was able to solve it by modifying `~/.vscode/argv.json` file by adding `"enable-browser-code-loading": false`
> 
> hope it works for you too
> 
> credit: to @xip-niekneuij at
> https://www.bswen.com/2021/07/others-how-to-solve-can-not-connect-extensions-marketplace1.html

Thanks for saving my life i just have this problem about 10 days and i must change distro to do it work. Thanks man...

**Comment by wilsonk** [comment]
Changing .vscode/argv.json also worked for me on a new Arch derivative with code-oss version 1.58-01. Thanks a lot.

**Comment by jackwootton** [comment]
I get `Property enable-browser-code-loading is not allowed.` when attempting to apply this fix.

```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.14
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.12.10-arch1-1
```

**Comment by grtcdr** [comment]
> Had the same issue once, i was able to solve it by modifying `~/.vscode/argv.json` file by adding `"enable-browser-code-loading": false`
> 
> hope it works for you too
> 
> credit: to @xip-niekneuij at
> https://www.bswen.com/2021/07/others-how-to-solve-can-not-connect-extensions-marketplace1.html

Thank you! That fixes it :smile:

**Comment by grtcdr** [comment]
> I get `Property enable-browser-code-loading is not allowed.` when attempting to apply this fix.
> 
> ```
> Version: 1.58.0
> Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
> Date: 2021-07-12T23:51:36.303Z
> Electron: 12.0.14
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.12.10-arch1-1
> ```

It could be an Electron issue, in versions <12.0.18. I can't attest to this being the cause but I'm on version 12.0.18 and it works for me.

**Comment by Virajayawardana** [comment]
> I get `Property enable-browser-code-loading is not allowed.` when attempting to apply this fix.
> 
> ```
> Version: 1.58.0
> Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
> Date: 2021-07-12T23:51:36.303Z
> Electron: 12.0.14
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.12.10-arch1-1
>

> > I get `Property enable-browser-code-loading is not allowed.` when attempting to apply this fix.
> > ```
> > Version: 1.58.0
> > Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
> > Date: 2021-07-12T23:51:36.303Z
> > Electron: 12.0.14
> > Chrome: 89.0.4389.128
> > Node.js: 14.16.0
> > V8: 8.9.255.25-electron.0
> > OS: Linux x64 5.12.10-arch1-1
> > ```
> 
> It could be an Electron issue, in versions <12.0.18. I can't attest to this being the cause but I'm on version 12.0.18 and it works for me.

I have the same issue, but my Electron is 13.1.7 ???

>Version: 1.59.1 (user setup)
>Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
>Date: 2021-08-19T11:56:46.957Z
>Electron: 13.1.7
>Chrome: 91.0.4472.124
>Node.js: 14.16.0
>V8: 9.1.269.36-electron.0
>OS: Windows_NT x64 10.0.19043

**Comment by SteindelSE** [comment]
Same issue. Disabling browser-code-loading also worked for me.
Code-OSS using ArchLinux

> Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.1.0
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.13.13-zen1-1-zen

**Comment by grtcdr** [comment]
> I have the same issue, but my Electron is 13.1.7 ???

@Virajayawardana Well that sucks, maybe someone will find out why it isn't working soon.

**Comment by jrborbars** [comment]
> Had the same issue once, i was able to solve it by modifying `~/.vscode/argv.json` file by adding `"enable-browser-code-loading": false`
> 
> hope it works for you too
> 
> credit: to @xip-niekneuij at
> https://www.bswen.com/2021/07/others-how-to-solve-can-not-connect-extensions-marketplace1.html

@VanGoethe  solution works smoothly for me, too. Thank you!
