### ISSUE TITLE
Powerline symbols broken in terminal w/ ClearType antialiasing

### ISSUE THREAD

**Issue by CoryG89** [microsoft/vscode#128917]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 (Version 21H1, Build 19043.1110)

Steps to Reproduce:

1. Enable ClearType font antialiasing by opening Control Panel -> Appearance and Personalization -> Fonts -> "Adjust ClearType text" and checking "Turn on ClearType"
2. Setup any shell with powerline symbols in the prompt (oh-my-posh, powerline-status, etc).
3. Open vscode, open integrated terminal hosting shell with powerline symbols in the prompt.

So I found many different issues filed for powerline symbols being rendered incorrectly, some on Windows, some on other platforms. I noticed a while back that my powerline prompt was being rendered incorrectly in the vscode integrated terminal on Windows. I thought this was a bit odd as I was not having any issues rendering the Powerline symbols in Windows Terminal using exactly the same font. I was also not having any issues rendering on MacOS. 

I lived with this issue for a while, until recently I was toying around with settings in Windows Terminal and I tried changing one of Windows Terminal's settings for "Text antialiasing" from it's default value of "Grayscale" to "ClearType".  It didn't seem to do anything at first, but when I re-opened Windows Terminal the next day, I was surprised to see that my Powerline symbols were broken in exactly the same way that they were broken in vscode. I tried changing the "Text Antialiasing" setting back to Grayscale, restarted the terminal, and sure enough, the Powerline symbols were fixed, rendering properly. 

Armed with this information, I then went back to vscode, looking for an equivalent setting to enable/disable ClearType. Unless I'm missing it, it seems there is no vscode specific setting that can be used to enable/disable ClearType. After some searching, I did find the Windows OS-level setting in the Control Panel. I took a look at the Windows setting by navigating to Control Panel -> Appearance and Personalization -> Fonts -> "Adjust ClearType text" — and I found that this setting was indeed enabled. I tried disabling ClearType at the OS level using this Control Panel setting. I restarted vscode, opened the integrated terminal. Lo and behold, my Powerline symbols are now fixed in the vscode integrated terminal as well. 

Incorrectly rendered powerline symbols with ClearType enabled:

![powerline-broken](https://user-images.githubusercontent.com/1627957/126045848-5ef48c55-3afc-452a-94b4-3c778bccdde2.PNG)

Properly rendered powerline symbols after disabling ClearType:

![powerline-working](https://user-images.githubusercontent.com/1627957/126045863-91b3120f-bdf6-4856-b687-7157a46e7c67.PNG)

This workaround is not ideal. I would prefer to keep ClearType enabled at the OS-level. Text is rendered okay on my monitor without it, but for some applications, text definitely looks better with ClearType enabled. Ideally, vscode could provide an application-level setting (or even better, a setting specific to the integrated terminal, similar to the setting that Windows Terminal provides) for disabling ClearType, such that I could disable ClearType in vscode or the vscode terminal, _without_ having to disable ClearType across my entire OS.

**Comment by meganrogge** [comment]
does turning off terminal.integrated.gpuAcceleration help?

**Comment by Tyriar** [comment]
Changing `window.zoomLevel` might help

/duplicate https://github.com/microsoft/vscode/issues/53554
