### ISSUE TITLE
Bug: TextEditor.insert() fails to update TextEditor.selections

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#12898]
- VSCode Version: 1.5.3
- OS Version: OSX 10.10.5

Steps to Reproduce:

Create an extension command that runs the following code:

```
let disposable = vscode.commands.registerCommand('myExt.testCommand', function() {

    // Get active text editor
    let textEditor = vscode.window.activeTextEditor;

    // Ignore if no active TextEditor
    if (typeof(textEditor) === 'undefined') {
      return false;
    }

    // Print out the current selections in the document
    console.log(textEditor.selections);

    let text = "helloworld";

    // Create an edit to insert into the document
    let edits = [
      vscode.TextEdit.insert(textEditor.selection.active, text)
    ];

    // Insert the text
    let uri = textEditor.document.uri;
    let edit = new vscode.WorkspaceEdit();
    edit.set(uri, edits);
    vscode.workspace.applyEdit(edit);

    // Once again, print out the current selections
    console.log(textEditor.selections);

    return true;
}
```

So essentially this code, prints out your current selections to the debug console, then inserts some text where the primary/active cursor is, then again, prints out your current selections.

What you will find is that the differences between the 2 selections that get printed to the debug console are exactly the same even though your selections have changed. When you `.insert()` text into the document, that text is then automatically selected. 

For example if you run this command, `helloworld` is inserted into the document. Then if you immediately type a letter or backspace or whatever, `helloworld` is replaced with whatever you typed, just as if `helloworld` was selected already (like if you selected it using your mouse). The bug is that your inserted text is selected, but it doesn't appear to immediately appear as part of `TextEditor.selections`.

Sorry if this is a bit confusing. I assume this is a bug. Can anyone confirm or deny this?

**Comment by jrieken** [comment]
@Jakobud fyi when you have an editor in your hands you should it's [`edit`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L965)-method which is better suited for this case. 

Then both methods `edit` and `applyEdits` return a thenable on which you should wait. Only when they signal complete the edits and selections have been sync'd. 

Please try that and report back

**Comment by Jakobud** [comment]
Ah I missed the `TextEditor.edit()` method. When would be the appropriate time to use the `applyEdit` method to the workspace?

Also yes I totally missed the Thenable on the `applyEdit` method. Thanks,

**Comment by jrieken** [comment]
@Jakobud Rule of thumb should be to use `TextEditor.edit` when you have an editor in your hands and only changes concerning the document of that editor, iff you want to change multiple document at once use `applyEdit`
