### ISSUE TITLE
VSCode intellisens not working

### ISSUE THREAD

**Issue by cemo7** [microsoft/vscode#128942]
Issue Type: <b>Bug</b>

there is no intellisense in vs code and also there is no Go to definition 
![image](https://user-images.githubusercontent.com/32800549/126065123-8db1fbbb-1687-43a0-b8c1-06431bbfaaaa.png)

![image](https://user-images.githubusercontent.com/32800549/126065155-69ae1123-f41b-447e-b1da-fafc136cea03.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (17.42GB free)|
|Process Argv|--crash-reporter-id 50d30592-a92e-4fca-9f0d-b4c1c430edb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.21
xml|Dot|2.5.1
gitlens|eam|11.6.0
Angular2|joh|12.0.0
angular2-inline|nat|0.0.17
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
