### ISSUE TITLE
Drag resizing a maximized window on top and bottom should not be possible

### ISSUE THREAD

**Issue by garfieldbanks** [microsoft/vscode#128972]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10

Steps to Reproduce:

1. maximize vscode window
2. move mouse to bottom of vscode window (between vscode and windows 10 taskbar)
3. resize vscode window

![image](https://user-images.githubusercontent.com/12904270/126123569-a104cceb-c65d-4d21-ba8d-cefb2681d8fb.png)

Expected result:
Resize icon should not appear and resizing in this manner should not be possible.

**Comment by garfieldbanks** [comment]
Also a problem at the top of the screen.

**Comment by deepak1556** [comment]
What is the OS build number of your windows ? Also can you check if the issue happens with our insiders version https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Unable to repro on `Windows 10 Enterprise 19043.1110` and `Windows 11 Enterprise 22000.71`. Can you provide a screen recording to better understand the issue.

/gifPlease

**Comment by garfieldbanks** [comment]
I installed the insiders edition and was unable to reproduce the issue there. After that I also retested the regular version (and again after uninstalling insiders) and was unable to reproduce the issue there as well. Now I really wish I had made a gif or something because it _was_ happening and I have no idea what changed.

**Comment by deepak1556** [comment]
Thanks for checking, I will close this issue for now. Can reopen if it happens again.
