### ISSUE TITLE
Show user icon if there signed in via GitHub

### ISSUE THREAD

**Issue by josh-65** [microsoft/vscode#128987]
It should use my GitHub icon not show as a blank placeholder one.

![image](https://user-images.githubusercontent.com/26977075/126161277-d7b52d81-a8b3-43fc-8ec2-2e290f87c8d3.png)

**Comment by TylerLeonhardt** [comment]
@josh-65 I like the idea.

The only thing is, you can be logged in to many different accounts (like Microsoft for Settings Sync, GitHub for the GitHub Pull Request extension) so for your scenario it makes sense but for those who do have multiple accounts, it doesn't.

Additionally, you can sign in to GitHub here, but some other entity could make an auth provider (like Google) and we'd need to give them the ability to set the icon if they're the _only_ account logged in to.

At the end of the day, I think it's a larger work item for a small scenario.

With that said, I'll put it in the Backlog Candidates to see what other folks have to say. Thanks for opening this!

**Comment by josh-65** [comment]
It could just be it try's to pull the icon from the root of Microsoft or GitHub account and if it can't get it it falls back to what it is now,
