### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by dsignr** [microsoft/vscode#128990]
Hi team,
I am just an average developer with a medical condition that prevents me from working long hours infront of a laptop. For this purpose, I purchased an iPad Pro with blind hopes that it could get it to replace my laptop which was causing my medical condition. And I almost gave up, until I started using VS Code via GitHub spaces. I can’t thank you enough, this has completely changed the way I work, I run large media sites and web applications used by millions of end users in production and VS Code has been able to immensely allow me to have my freedom of breaking free from the shackle of laptops with large power bricks. I am writing this heartfelt thank you letter as a word of support for all you contributors and your hard work that changes peoples lives like it did mine. I just wanted to reach out and say thank you so you understand how much this helped me. It is actually a huge contribution towards my career and it is definitely more than just a tool.
Sorry I am not following any issue templates.  I just wanted to say thanks and sorry if this violates any spam policy or something. 

Thank you!

**Comment by jrieken** [comment]
Thanks for the kinds word ❤️  I have closed this issue "as-designed" because empowering everyone is what we are aiming for. #HappyCoding and let us know how and what we can improve.
