### ISSUE TITLE
User-name become "Anonymous" when opening Liveshare URL

### ISSUE THREAD

**Issue by kotlin-obasan** [microsoft/vscode#128962]
Does this issue occur when all extensions are disabled?: No(Because this problem seems Liveshare-extension's matter)

User-name become "Anonymous" when opening Liveshare URL.

- VS Code Version:1.58.1
- OS Version:Mac OS Catalina 10.15.7 and Big sur

Steps to Reproduce:

1. Open someones Liveshare URL.
2. When host approve my join, username becomes "Anonymous".
3.  I try re-SignIn, Liveshare extension package disabled, and Liveshare uninsall -> re-install. but its not resolved.

**Comment by kieferrm** [comment]
Please file the issue at https://github.com/MicrosoftDocs/live-share/issues. Thank you!
