### ISSUE TITLE
markdown image edit full support

### ISSUE THREAD

**Issue by Kellermaan** [microsoft/vscode#128983]
For now I can't find any solution to let me comfortable at editing markdown file using vscode.
It would be perfect if we can have the image support in vscode like drag image file or copy image file then it can generate the markdown link of this image in the markdown file automatically. And in the same time, the image file has been copied to the designated path.

Thanks very much.
A heavy user of VScode

**Comment by aindr** [comment]
have you tried Markdown Image extension?
https://marketplace.visualstudio.com/items?itemName=hancel.markdown-image

**Comment by Kellermaan** [comment]
@aindr  I just tried to use it for a while. looks like really good to me. Thanks a lot!
