### ISSUE TITLE
Notebook screen cheese 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#128999]
1) Open a notebook
2) Maximize the terminal
3) Close the Window
4) Reopen the window

![image](https://user-images.githubusercontent.com/4674940/126197449-54013876-57cc-4951-9eb4-bc6e73119d8f.png)

There is even a simple version: Just steps 1 and 2. This also renders the panel toolbar unusable.

![image](https://user-images.githubusercontent.com/4674940/126197967-63e25fc3-8894-434b-ae4d-9958ea9ab623.png)

**Comment by jeanp413** [comment]
I can still repro this running from sources :thinking:

**Comment by stuartleeks** [comment]
Confirmed as still an issue on

```
Version: 1.59.0-insider (user setup)
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:47.114Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by rebornix** [comment]
Thanks for testing. I can reproduce this on macOS. Weird that it's not platform agnostic

**Comment by rebornix** [comment]
nvm, I can reproduce this sometimes on Windows as well. The grid view is giving me a non-empty dimension when we max the panel somtimes. Will report a bug for that but for now I will fix this in notebook.

**Comment by jeanp413** [comment]
@rebornix After 5c1b0b7 now I am getting an error ` ERR TypeError: Cannot read property 'width' of null`. Created #129914 with steps to reproduce it
