### ISSUE TITLE
Allow to configure file association for files without extensions

### ISSUE THREAD

**Issue by chrisjaquet** [microsoft/vscode#128985]
Issue Type: <b>Bug</b>

There are a number of C++ libraries out there, including the standard library that have chosen to use extensionless files for headers. VSCode (and its C++ extension) do not detect these files as C++ headers by default (which is reasonable). I decided to  use the Text-Editor -> Files -> Associations settings to set all extensionless files to be C++, but this did not have the desired result.

I tried the following:
```json
"files.associations": {
    "*.": "cpp"
},
```
but it seems to have no effect and using
```json
"files.associations": {
    "*": "cpp"
},
```
associates all files with cpp, even if there is another association for that file type.

Bug: There does not appear to be a way to do a file association for files with no extension. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.34GB free)|
|Process Argv|--crash-reporter-id 01a1c0a7-0d4a-4733-9eef-99e4c6edf57c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Needs analysis why this happens and open for help if someone is interested.

**Comment by bpasero** [comment]
Since I cannot reproduce, I suspect a configuration issue that maybe people in SO can resolve. 

VSCode itself supports any kind of file association as you can see from how languages are resolved using glob matching here:

https://github.com/microsoft/vscode/blob/b776d802d999fd769fd884c15e0c6ecac933ee0b/src/vs/base/common/mime.ts#L169-L194

**Comment by chrisjaquet** [comment]
It seems I am not the only one with this problem. The following two SO posts indicate the same problem (in their case with extensionless bash scripts):
1. https://stackoverflow.com/questions/47636026/get-visual-studio-code-to-syntax-highlight-extensionless-files-as-bash-scripts
2. https://stackoverflow.com/questions/49410524/assign-file-with-no-extension-to-a-language-on-vs-code-as-default

It seems VSCode handles shebangs, thus working around the case for bash scripts with shebangs, but it seems the issues still exists for files that do not have the shebang.

In the second link one of the comments (https://stackoverflow.com/a/53468881) uses the following workaround:
```
{
    "files.associations": {
        "[!.]": "php",
        "[!.][!.]": "php",
        "[!.][!.][!.]": "php",
        "[!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php",
        "[!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.][!.]": "php"
    },
}
```
which seems very clunky. Is there not a simpler way to specify a file with no extension? You mentioned that you could not reproduce the issue, what pattern did you use?

**Comment by bpasero** [comment]
I think we only have to agree on a syntax for this.

//cc @TylerLeonhardt as this goes a little bit into the direction of language detection. I.e. what if we would detect languages automatically in the background for files that are in "Plain Text"?

**Comment by bmartin** [comment]
I'm not sure if it is related. With the upgrade to 1.60.0, I'm now seeing that the language guessing is insisting on interpreting COMMIT_EDITMSG files as shell scripts, probably due to all the lines commented with `#`. This is overriding an explicit pattern supplied by the edamagit extension.

**Comment by TylerLeonhardt** [comment]
@bmartinut that's fixed. It will be in the 1.60.1 release
