### ISSUE TITLE
Character \u12 (New Page form feed character, "FF", "^l") in search inputs affects layout

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [microsoft/vscode#128911]
Issue Type: <b>Bug</b>

The form feed character, \u12, rendered as "FF" in documents when ```Show Control Characters``` is enabled, is interpreted in search fields and breaks the layout by vertically cutting the off the search gadget.

This happens in both ```find``` and ```find in files```. It does not happen when there are other characters in the search string.

<img width="485" alt="Screenshot 2021-07-17 at 13 53 16" src="https://user-images.githubusercontent.com/10232033/126036519-3d476f0d-bc07-4eec-813b-16b0c9ece2c5.png">
<img width="405" alt="Screenshot 2021-07-17 at 13 53 35" src="https://user-images.githubusercontent.com/10232033/126036522-f1c01f9e-e6c6-4e1a-b5e9-43fb25767d53.png">

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin arm64 21.0.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 4|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|n --crash-reporter-id 4ae692ee-828e-4d8a-bc2c-0b7e308fc959|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
Weird. This gets measured wrong, I'll exclude it from measuring. Tried a bunch of other atypical characters and didn't see the same behavior with any other.s
