### ISSUE TITLE
[Test API] Add "testing/title" contribution point

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#128928]
Now the test explorer removes the official support for refresh the entire test tree view, while currently a extension can register commands to its tree node via  `"testing/item/context"`

Please consider adding `testing/title` to make it possible adding commands to the title area, meanwhile support the overflow group.

**Comment by connor4312** [comment]
This can be done via the `view/title` contribution point, which is what we recommend in these cases, for example: https://github.com/microsoft/vscode-test-adapter-converter/blob/050c3788dde1736ae76685b4dd524571368e2d45/package.json#L56-L59

**Comment by jdneo** [comment]
Thank you that's work!
