### ISSUE TITLE
Support Blazor Webassembly For Authoring Webviews

### ISSUE THREAD

**Issue by kkukshtel** [microsoft/vscode#128960]
I'm the developer of [a mildly popular Code extension](https://marketplace.visualstudio.com/items?itemName=afterschool.depot) that makes use of the Webview API, and am currently injecting Svelte into a Webview in order to make the development experience for a complex view much easier.

However, I would like to be able to avoid the toolchains required to do this and instead by able to author views with Blazor Webassembly, leveraging my existing C# knowledge and also leaning more on Microsoft's tooling/ecosystem.

I assume this, in part, is somewhat possible now, but would love it if the Code team could provide a story on this or path/template for people to follow. I know its not ideal from a size perspective in terms of the wasm payload Blazor currently requires, but I think the tradeoff would be worth it for a more consistent and stable development experience.

**Comment by mjbvz** [comment]
Providing support for specific frameworks for webview is out of scope of VS Code. Try seeing if any existing reference projects exist or look into creating one that others can build in

**Comment by kkukshtel** [comment]
@mjbvz Just so the ask is clear here - I didn't mean this ticket to imply that webviews should change from a code perspective to support this use case, just more that I would be nice if there was some sort of documentation/suggested best practice around doing such a thing. People are already using React (and Svelte in my case) to do similar things, but these hacks rely on disparate blog posts and Medium articles to get to work (as well as a _deep_ understanding of the Webview API/interop that a beginner wouldn't have).

Currently, the webview documentation on view authoringimplies you have to write raw HTML code with JS DOM selectors for more dynamic functionality, which likely turns a lot of people away because they make what's possible with Webviews seem limited. Providing some support or suggestions around injecting larger frameworks into Code would, I think, open up more people to leveraging the API because they can lean on their existing tooling and knowledge.

**Comment by mjbvz** [comment]
Yes I was referring to the documentation / example projects

**Comment by rrelyea** [comment]
Here is a sample of hosting React as a webview: https://github.com/rebornix/vscode-webview-react 
(my PR to update a few things to run now was merged yesterday.)

Digging into trying to get a blazor built webview now... (currently dying in blazor.webassembly.js with bad url error)

**Comment by rrelyea** [comment]
/duplicate: https://github.com/microsoft/vscode/issues/146129
