### ISSUE TITLE
Source control is not able to detect renaming a file, even if using Rename feature

### ISSUE THREAD

**Issue by Omcsesz** [microsoft/vscode#128981]
Issue Type: <b>Feature Request</b>

Hello, Team!

After I use the Rename feature in Explorer, I see the file in Source Control with the new name as created, and the old one as deleted, but this way the diff is not doable for the two files in the UI.
Can you consider adding this feature?

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.11.0-24-generic snap
Restricted Mode: No

**Comment by eamodio** [comment]
Unfortunately this is just how Git works -- Git doesn't actually track renames, it just compares files that have similar contents (within a threshold) where one was removed and another was added. So there isn't anything VS Code can do here.

**Comment by Omcsesz** [comment]
> Unfortunately this is just how Git works -- Git doesn't actually track renames, it just compares files that have similar contents (within a threshold) where one was removed and another was added. So there isn't anything VS Code can do here.

But when I use `git mv old_filename new_filename`, and check the status with `git status -s`, it detects the changes as a rename (see picture).
[RenameInGit](https://user-images.githubusercontent.com/1839739/128011989-833ea1da-cb5f-48f6-8d45-081ca02a000a.jpg)
