### ISSUE TITLE
Restore ability to create a file from a link that points to non existing file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12896]
We used to be able to click on a link to a file that does not exist and create that file, which imho was a very cool flow:
![editors](https://cloud.githubusercontent.com/assets/900690/18922564/7b124b2e-85a9-11e6-9b90-55cbf2626c36.gif)

Ever since links.ts seems to use the openerService we lost this ability and clicking on a missing link does not even return a message to the user that the file does not exist.

**Comment by octref** [comment]
Just to add from a usability POV people often have
```
<link rel="stylesheet" href="/lib.css">
```
VSCode will try to create `/lib.css` at system root, which is almost never the case user wants.

**Comment by bpasero** [comment]
Well to be fair that IS what you are expressing there. A web server would also treat this as an absolute path.

**Comment by octref** [comment]
Web servers would map my request `/lib.css` to something like `/www/mysite.com/lib.css` in the server. And while development I doubt anyone would write
```
<link rel="stylesheet" href="/Users/octref/mysite.com/lib.css">
```
to make this feature work.

**Comment by bpasero** [comment]
The HTML extension is the one that produces the links in the document. Only it can have the understanding of additional context that the server has, so I suggest this would need to be filed against the HTML extension we bundle.
