### ISSUE TITLE
VSCode OSS not entirely open source anymore

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#128953]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. With the addition of [`@vscode/vscode-languagedetection`](https://github.com/microsoft/vscode/blob/main/package.json#L60), [`vscode-regexpp`](https://github.com/microsoft/vscode/blob/main/package.json#L82) and [`tas-client-umd`](https://github.com/microsoft/vscode/blob/main/package.json#L78) as dependencies, the VSCode OSS editor is not entirely open source anymore.

I'm wondering whether the introduction of proprietary npm packages to VSCode OSS was intentional and what the plan is going forward. 

All other vscode utilities are open source:
- vscode-oniguruma: https://github.com/microsoft/vscode-oniguruma
- vscode-proxy-agent: https://github.com/microsoft/vscode-proxy-agent
- vscode-ripgrep: https://github.com/microsoft/vscode-ripgrep
- vscode-sqlite3: https://github.com/microsoft/vscode-node-sqlite3
- vscode-textmate: https://github.com/microsoft/vscode-textmate
- applicationinsights: https://github.com/microsoft/ApplicationInsights-node.js
- spdlog https://github.com/Microsoft/node-spdlog
- semver-umd https://github.com/Microsoft/semver-umd
- iconv-lite-umd https://github.com/Microsoft/iconv-lite-umd
- vscode-windows-ca-certs https://github.com/Microsoft/vscode-windows-ca-certs
- vscode-windows-registry https://github.com/Microsoft/vscode-windows-registry

**Comment by kieferrm** [comment]
Repository for https://www.npmjs.com/package/@vscode/vscode-languagedetection is https://github.com/microsoft/vscode-languagedetection.

Base repository for https://www.npmjs.com/package/vscode-regexpp is https://github.com/mysticatea/regexpp. From time to time we build our version off https://github.com/connor4312/vscode-regexpp/commits/master if changes we need have not been merged.

We'll clean-up the dependency on the tas-client-umd package.

**Comment by SimonSiefke** [comment]
Pretty sure that https://github.com/microsoft/vscode-languagedetection was not open source when I posted this issue. But great that it is now.  😎


Thank you @kieferrm!
