### ISSUE TITLE
Cannot connect to Extensions marketplace - CORS error

### ISSUE THREAD

**Issue by AVAtarMod** [microsoft/vscode#128940]
Issue Type: <b>Bug</b>

After enter in Extension section, i see CORS errors in developer panel, and net::error_failed (codium cannot connect to marketplace because policies are incorrect).

VS Code version: VSCodium 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-16T00:15:55.196Z)
OS version: Linux x64 5.12.13-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 1906)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.62GB (0.33GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-makefile-project|adr|1.1.0
insertnumbers|Asu|0.9.1
pretty-edit|cef|0.4.1
doxdocgen|csc|1.3.2
php-intellisense|fel|2.3.14
code-runner|for|0.11.5
todo-tree|Gru|0.0.212
php-cs-fixer|jun|0.2.2
git-graph|mhu|1.30.0
python|ms-|2020.10.332292344
cpptools|ms-|1.2.2
material-icon-theme|PKi|4.8.0
datetime|rid|2.0.3
pdf|tom|1.0.0

</details>

**Comment by AVAtarMod** [comment]
Workaround: add --disable-web-security to launch command

**Comment by cyberwombat** [comment]
Probably this bug https://github.com/VSCodium/vscodium/pull/774
