### ISSUE TITLE
Unexpect extension deactivation after the first workspace closed while using onStartupFinished

### ISSUE THREAD

**Issue by JasinYip** [microsoft/vscode#128980]
I'm writing an extension for VS Code using the activation event `onStartupFinished `. It is in line with expectations of activation. However, the timing of calling `deactive` function is unexpected.

In official document I found:

> Also, an extension should export a deactivate() function from its main module to perform cleanup tasks on VS Code **shutdown**.

In my expectation I think the `deactive` function will be called before VS Code quiting, such as cmd+Q action. But now it called before the first workspace windows closing.

### Environment
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

### Steps to Reproduce

1. Generate an extension project via `yo code`;
2. Use this simple code:

```ts
import * as vscode from 'vscode';

export function activate () { console.log('activate!') }
export function deactivate () { console.log('deactivate!') }
```

also set this in `package.json`:
```json
	"activationEvents": [
		"onStartupFinished"
	]
```
3. Start debuging with F5.
4. When the debug window shows, we can see the log: `activate!`.
5. Create a new workspace window with Cmd+Shift+N.
6. Close the first window(not the new one), then we will see the log: `deactive!` which is unexpected.

Did I make any mistakes or misunderstaning?

**Comment by kieferrm** [comment]
Each window has its own extension host. When you close the first window, the extension host associated with that window goes down and therefore the instance of your extension running in this extension host is deactivated.
