### ISSUE TITLE
Allow more granular fontStyle options for themes.

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#128918]
Currently two font weights are available: normal (400) and bold (700).  Please add support for more (all) weights, specially 500.

**Comment by CodeCrazy-ywt** [comment]
It depends on the font you're using.

**Comment by a5hk** [comment]
Yes it depends on the font, but it also needs to be supported by VS Code to work. Right now VS Code only supports `italic`, `bold` or `underline` or a combination for `fontStyle`. If I want to have bolder tokens, my only option is to use `bold`, which is 700. I cannot use 500 even if the font I'm using supports that.

**Comment by CodeCrazy-ywt** [comment]
Try this:
`"editor.fontWeight":500`

**Comment by a5hk** [comment]
No, I don't want to change font weight editor wide, I have developed some themes, and I want to make for example function calls bold.

![1](https://user-images.githubusercontent.com/5412540/126071132-120f49c0-cdb7-403e-bded-d3f4dc45a75b.png)

![46](https://user-images.githubusercontent.com/5412540/126071133-e2ee2621-14a6-4880-b4d3-cea553f7ef50.png)

![97](https://user-images.githubusercontent.com/5412540/126071134-252da76b-e3f1-4737-bda8-d99224f458a4.png)

**Comment by CodeCrazy-ywt** [comment]
Hmmm... It doesn't affects bold texts(?).

**Comment by CodeCrazy-ywt** [comment]
@a5hk Maybe [this](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting) will help you out.

**Comment by a5hk** [comment]
@CodeCrazy-ywt Thanks. That's essentially what I'm doing. But as you can see [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes) the options are limited:

> The value describes the style if the rule matches. It is either a string, representing the foreground color, or an object, in the form `{ foreground: string, bold: boolean, italic: boolean, underline: boolean }` or `{ foreground: string, fontStyle: string }` as used for TextMate theme rule in tokenColors.

What I'm asking for is more control over `bold`. I want to set how much bold it should be instead of just a true/false setting.

**Comment by CodeCrazy-ywt** [comment]
Hmmm...that seems really an issue to be solved. :/
