### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by abhk4** [microsoft/vscode#128943]
Python err, "test" is not undefined 
![Errorlog](https://user-images.githubusercontent.com/33792235/126065172-0c5b3fc3-657d-47eb-9989-48cd7e526634.JPG)
Pylance(reportUndefinedVaribale),

**Comment by weinand** [comment]
This looks like a problem in your python program, not look like a problem in VS Code or the Python extension.

**Comment by CodeCrazy-ywt** [comment]
@abhk4 Please post your issue in the PyLance respository.
