### ISSUE TITLE
Ctrl+Shift+N produces empty window

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#128977]
Does this issue occur when all extensions are disabled?: Don't know

- VS Code Version: 1.58.2 (happened as of 1.58.0, if I remember. Not earlier than that, but I could be mistaken)
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Have any repository/workspace/file open
2. Press Ctrl+Shift+N

Please note that this doesn't always reproduce the issue. In my case, it's 100% reproducible right now, but ymmv. For you, it might never occur, or always, or sometimes. For me it might not occur the next time I completely exit VScode, or do a reboot, or something. It's hard to tell *exactly* when this happens or not.

This is what I see when I press Ctrl+Shift+N. A new window appears, but that window doesn't fully, ehm, load. Or something.
![image](https://user-images.githubusercontent.com/152227/126144623-36da3911-40c9-4780-8920-1c014d4843de.png)

And it stays like that. It's not slow or anything, and I can close it by pressing Alt+F4 on it.

For me, the only way to get an additional VScode window that does more than drawing a couple of grey & purple rectangles, is to start it again from my desktop/start shortcut. Unless Ctrl+Shift+N happens to work properly, of course.

**Comment by thany** [comment]
Interesting, when I open a repo in the new window created by starting another VScode instance from the shortcut, the window goes empty again like above, but without the purple bottom bar. Doing the same thing in the first window produces the same problem again. Only restarting VScode entirely works around it. Ctrl+Shift+N then works correctly as well. I wonder when it will start failing again.

**Comment by mrob95** [comment]
I've hit the same thing multiple times today. I can't repro it consistently but it gets to a stage where there are a number of windows open and it just can't open another - the new one just hangs. 

Version info:
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by AlexandrAnash** [comment]
I have exactly the same problem as the guys above
![image](https://user-images.githubusercontent.com/2750740/126503335-f7fb15c4-2f6f-463d-aa6a-289116063b3a.png)

**Comment by karabaja4** [comment]
#128903

**Comment by deepak1556** [comment]
Can you launch with `code --verbose` and provide the generated output when you hit the problem.

**Comment by mrob95** [comment]
@deepak1556 re https://github.com/microsoft/vscode/issues/129137#issuecomment-885846899 this is a reliable repro for me:

launch vscode -> open external terminal (windows terminal) -> new window -> hang

**Comment by SorataBaka** [comment]
> Can you launch with `code --verbose` and provide the generated output when you hit the problem.
@deepak1556 
[VCCODE log.txt](https://github.com/microsoft/vscode/files/6872377/VCCODE.log.txt)
here is a log of the generated output upon creating a new window after hitting ctrl shift n or opening an external console.
