### ISSUE TITLE
Build task shows forever spinner

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#128989]
* this task which has no problem matcher https://github.com/microsoft/vscode-anycode/blob/e887e1daf60cd345e42eca7ac1c7c827a05bde91/.vscode/tasks.json#L9
* it spins forever, never stops

https://user-images.githubusercontent.com/1794099/126169623-51d37674-2b06-490f-9d45-e8116f6784dd.mov

**Comment by Tyriar** [comment]
Actually this is different, you need to set `isBackground` to true to get rid of the spinner right now:

https://github.com/Microsoft/vscode/blob/5b642616ef3cba37b07ff6946da0cd8bd2280045/src/vs/workbench/contrib/tasks/browser/taskTerminalStatus.ts#L94-L97

This is likely as designed

cc @meganrogge

**Comment by jrieken** [comment]
Oh, thanks @tyriar!

**Comment by alexr00** [comment]
Yes, this is by design. For tasks that "end" (non- background tasks) we show the spinner until the task exits. Since this is a watch task it should set `isBackground` to indicate that it is a task that will usually not exit on its own.
