### ISSUE TITLE
More options for script in terminal

### ISSUE THREAD

**Issue by daboudii** [microsoft/vscode#128986]
It would be nice to add some options in the terminal for scripts: 

1. Stop script
2. re Run script (in case an error occur)
3. Link to the script in `package.json`

**Comment by meganrogge** [comment]
I think this would add bulk, @Tyriar thoughts?

**Comment by Tyriar** [comment]
We have tasks for this sort of stuff which already has run/re-run, then there's the npm extension which provides the codelens inside package.json. I agree this is something probably best left to extensions.

**Comment by daboudii** [comment]
OK no problem, thanks for the answer
