### ISSUE TITLE
output/debug/terminal/problem bar is as stable as U-238 when docked on the right

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#128996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version, OS Version:

![image](https://user-images.githubusercontent.com/177243/126194453-7b7d5e49-200e-4772-be15-67805843deec.png)

Steps to Reproduce:

Full screen VSCode on a 2550x1200 monitor, with the workspace split as filetree etc on the left, code in the middle, terminal on the right. Cycling through the "tabs" on the right, we already immediately see something weird: problems is hidden. Despite there being tons of space for it.

![{3D700028-CAB9-4A95-AA09-035702B9A85D}](https://user-images.githubusercontent.com/177243/126194610-61270e70-b9bb-4324-af67-f15fc29bbaf7.png)

other than that, nothing weird going on. Same for debug:

![{DB509906-99E9-4BAD-B4F6-EB79998C78CE}](https://user-images.githubusercontent.com/177243/126194622-a3d20358-d276-4aa6-8143-7858803aa540.png)

Selecting terminal suddenly reveals the "problems" option, putting it where it should be from the start:

![{331D32B1-5CF9-4AD6-BF45-2A9E701FF652}](https://user-images.githubusercontent.com/177243/126194638-185c0336-d095-40b3-84dc-0909a8b502bd.png)

Selecting "problems" then _removes_ the output and debug console for no discernible reason, as there is still plenty of room to put them in without encroaching on the associated right hand side filtering:

![{FC651F12-C347-411E-AB9B-EE24BBB79BA2}](https://user-images.githubusercontent.com/177243/126194654-b0a14da2-31df-4926-82f3-ef40464acad9.png)

Is there a way to force-reset this set of panel's behaviour to whatever it's supposed to do, stock?

**Comment by kieferrm** [comment]
The number of tabs visible depends on what is on the right side. The terminal has only small contributions, so there is more space for tabs. At any time, all existing tabs are accessible through the overflow menu `...`

**Comment by Pomax** [comment]
@kieferrm that would make sense if there wasn't _ample_ space for all the headings. If you examine the screenshots, you'll note that not a single one of them has so much content on the right that any of the headings need to be folder into a `...` button.
