### ISSUE TITLE
Add support for suggested imports using Typescript path mapping

### ISSUE THREAD

**Issue by mbokinala** [microsoft/vscode#128937]
Typescript allows developers to define a set of custom mappings for imports that can eliminate complex relative imports (see https://www.typescriptlang.org/tsconfig#paths and https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)

At the moment, when an import is suggested for an unimported item (class, function, etc.), VS Code sometimes suggests a relative import. It would be nice if VS Code could give 2 options in the suggestions list: one for a relative import and one using the typescript path mappings.

**Comment by mjbvz** [comment]
Please share a small project that demonstrates the requested behavior

**Comment by mbokinala** [comment]
Sure, I will share it in a bit

**Comment by mjbvz** [comment]
Closing as we need an example to investigate
