### ISSUE TITLE
Feature Request: Default "find" settings (e.g., case sensitivity, regular expression settings)

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#12897]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.0.0

SublimeText accepts default "find" preferences, such as case sensitivity and regular expression settings. It would be very, very nice of VSCode did likewise.

**Comment by sandy081** [comment]
@brendandixon May I know what settings in Sublime you mean?

**Comment by brendandixon** [comment]
@sandy081 Well, I stand partially corrected. I *thought* it was a setting in SublimeText, but it's just how it behaves without an explicit setting. With SublimeText, once I've set it to use case-sensitive / regular expressions in my "find" -- regardless of whether its global or local -- those settings stick across sessions, files, and projects. With VSCode I continually have to reset them.

Does this better explain my request? :)

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158
