### ISSUE TITLE
TF.js warning in dev tools

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#129005]
![image](https://user-images.githubusercontent.com/8586769/126204650-382a7016-1268-4992-9da4-a02ccfe5eb86.png)

Probably shouldn't log this, either by implementing their suggestion or just finding some way to silence it.

**Comment by TylerLeonhardt** [comment]
Opened an issue upstream: https://github.com/tensorflow/tfjs/issues/5349

**Comment by TylerLeonhardt** [comment]
Upstream issue fixed. Just waiting on it to be deployed.

**Comment by TylerLeonhardt** [comment]
Verification steps:
* Run VS Code
* Open an untitled file and paste in a sizable amount of code to trigger auto detection 
* Open dev tools
* No warnings like the above should show
