### ISSUE TITLE
docker-from-docker output links do not respect remote.autoForwardPorts=false

### ISSUE THREAD

**Issue by ericis** [microsoft/vscode#129050]
Issue Type: <b>Bug</b>

1. Use remote development extension with ".devcontainers"
2. Configure to use "Docker-from-Docker" (https://code.visualstudio.com/docs/remote/containers-advanced#_using-docker-or-kubernetes-from-a-container)
3. Disable auto-forwarding of ports, by configuring ".devcontainer" JSON settings with "remote.autoForwardPorts": false
3. Open in remote container using "Docker-from-Docker" configuration
4. Launch a docker instance with an exposed port from within "Docker-from-Docker" (actually runs on host). Example: `docker run --rm -it -p 8080:80 nginx`.
5. On the host machine, verify that you can visit http://localhost:8080 and that nginx welcome page comes up. VS Code should not list 8080 as a forwarded port.
6. Check output of running docker container in "Docker-from-Docker" .devcontainer instance. Hover over and click on the output with a link to http://localhost:8080. Notice the hover tooltip says "Follow link using forwarded port" and that clicking the link automatically adds 8080 to the forwarded port list. Now, visiting http://localhost:8080 will not work on the host machine!

Notice that output links do not respect the setting `"remote.autoForwardPorts": false`. _*This screenshot happens to use port 8000 instead of 8080 described in the steps above._

![image](https://user-images.githubusercontent.com/974919/126338826-181c8882-5071-4fc9-ab86-2d9b34877e2d.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.37GB free)|
|Process Argv|--crash-reporter-id 0f44f6c6-114b-4c67-9972-e4eb702bf2d1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Ubuntu @ desktop-linux|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2591)|
|Memory (System)|6.79GB (0.86GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.4
vscode-drawio|hed|1.6.1
vscode-azurevirtualmachines|ms-|0.4.0
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details><details>
<summary>Dockerfile</summary>

```

################################################################################
# NOTES:
# - Base image: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/ubuntu/.devcontainer/base.Dockerfile
# - Docker-from-docker:
#   - Overview: https://code.visualstudio.com/docs/remote/containers-advanced#_using-docker-or-kubernetes-from-a-container
#   - Base image and scripts: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker
################################################################################

# [Choice] Ubuntu version: bionic, focal
ARG VARIANT="focal"

# search "focal" distribution under...
# https://packages.ubuntu.com/
# get the version of an installed package with:
#   apt-cache policy {package}
ARG APT_VERSION_TRANSPORT_HTTPS=2.0.6
ARG APT_VERSION_CA_CERTIFICATES=20210119~20.04.1
ARG APT_VERSION_BUILD_ESSENTIAL=12.8ubuntu1.1

# source: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-from-docker/.devcontainer/Dockerfile
# [Option] Install zsh
ARG INSTALL_ZSH="true"
# [Option] Upgrade OS packages to their latest versions
ARG UPGRADE_PACKAGES="false"
# [Option] Enable non-root Docker access in container
ARG ENABLE_NONROOT_DOCKER="true"
# [Option] Use the OSS Moby CLI instead of the licensed Docker CLI
ARG USE_MOBY="true"
# Install needed packages and setup non-root user. Use a separate RUN statement to add your
# own dependencies. A user of "automatic" attempts to reuse an user ID if one already exists.
ARG USERNAME=automatic
ARG USER_UID=1000
ARG USER_GID=$USER_UID

################################################################################
# base
################################################################################
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

ARG APT_VERSION_TRANSPORT_HTTPS
ARG APT_VERSION_CA_CERTIFICATES
ARG APT_VERSION_BUILD_ESSENTIAL

# source: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-from-docker/.devcontainer/Dockerfile
ARG INSTALL_ZSH
ARG UPGRADE_PACKAGES
ARG ENABLE_NONROOT_DOCKER
ARG USE_MOBY
ARG USERNAME
ARG USER_UID
ARG USER_GID

# custom packages
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install -qqy --no-install-recommends \
        # secure communications
        apt-transport-https=${APT_VERSION_TRANSPORT_HTTPS} \
        # secure communications
        ca-certificates=${APT_VERSION_CA_CERTIFICATES} \
        # build tools
        build-essential=${APT_VERSION_BUILD_ESSENTIAL} \
    # clean up docker layer:
    # https://docs.docker.com/develop/develop-images/dockerfile_best_practices/#run
    && rm -rf /var/lib/apt/lists/*

# source: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-from-docker/.devcontainer/Dockerfile
COPY library-scripts/*.sh /tmp/library-scripts/
RUN apt-get update -qq \
    && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
    # Use Docker script from script library to set things up
    && /bin/bash /tmp/library-scripts/docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAME}" "${USE_MOBY}" \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/

# source: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-from-docker/.devcontainer/Dockerfile
# Setting the ENTRYPOINT to docker-init.sh will configure non-root access to
# the Docker socket if "overrideCommand": false is set in devcontainer.json.
# The script will also execute CMD if you need to alter startup behaviors.
ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
CMD [ "sleep", "infinity" ]

```

</details><details>
<summary>devcontainer.json</summary>

```

// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/ubuntu
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Ubuntu version: focal, bionic
		"args": {
			"VARIANT": "focal"
		}
	},
	"mounts": [
		"source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"
	],
	"runArgs": [
		"--init"
	],
	"overrideCommand": false,
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",
	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"remoteEnv": {
		// Pass in the host directory for Docker mount commands from inside the container
		"HOST_PROJECT_PATH": "${localWorkspaceFolder}"
	},
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"EditorConfig.EditorConfig",
		"ms-azuretools.vscode-docker",
		"esbenp.prettier-vscode"
	],
	// Set *default* container specific settings.json values on container create.
	"settings": {
		"terminal.integrated.defaultProfile.linux": "zsh",
		"remote.autoForwardPorts": false
	}
}

```

</details>

**Comment by alexr00** [comment]
This is an interesting situation. The `autoForwardPorts` setting only controls whether we seek out ports and forward them without any user interaction. Clicking a link isn't covered by that setting.

Generally, forwarding a port when a user clicks on a link will provide the best user experience since most of the time that will make the link "just work". In this case that's the wrong thing to do, but we don't have the context to know that.

I don't want to expand the `autoForwardPorts` setting to cover this scenario, since I think that will also cause unexpected behavior for some users. It seems like the best thing to do is to add yet another setting that prevents clicking a link from forwarding the port.

**Comment by alexr00** [comment]
@ericis to get around this for now, you can open the "Ports" view and remove the port from there.

**Comment by ericis** [comment]
Yes, thank you @alexr00 . I've tested that work-around and documented that as the "fix" for now. I appreciate it.
