### ISSUE TITLE
[themes] Settings sync update when previewing themes

### ISSUE THREAD

**Issue by Shy82** [microsoft/vscode#129051]
Issue Type: <b>Bug</b>

Hey there!
Hope you're having a great time developing this beauty,
I was checking out themes I had installed ( the one I was using just bored me) and checking themes with command palette made settings sync requests! ( I guess it shouldn't until user confirms the theme; right? Oh and sorry bad English :) )

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.72GB free)|
|Process Argv|--crash-reporter-id 1c2d542d-98c6-44ae-9134-31ab9ae687a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|1.0.14
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
prettier-vscode|esb|8.0.1
vdf|GEE|0.0.7
csharp|ms-|1.23.13
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
cpptools|ms-|1.5.1
notepadplusplus-keybindings|ms-|1.0.7
vscode-typescript-next|ms-|4.4.20210715
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0
txt-syntax|xsh|0.1.6

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by aeschli** [comment]
Looking at themes with the theme picker does not change the settings.
![themepicker2](https://user-images.githubusercontent.com/6461412/126456683-9415b957-880a-4606-8913-888a35eed064.gif)
Looking at the settings sync log I don't think it makes actual requests.

**Comment by Shy82** [comment]
That's odd, it does recognize changes for me.

https://user-images.githubusercontent.com/41096570/126459383-891fa04b-e3f5-402c-97ce-56450e1230aa.mp4

And even if it didn't, it shouldn't trigger sync until confirmation anyways.

**Comment by aeschli** [comment]
Oh, the storage is changed. We use it to open up flicker free.
Pushed a fix. Thanks!
