### ISSUE TITLE
vscode freezes/crashes on macOS BigSur running on m1 chipset

### ISSUE THREAD

**Issue by Amin-Azar** [microsoft/vscode#129076]
I just bought a macbook air and installed vscode for m1.  It just freezes after a few seconds since I open the vscode. No message to paste here. No steps to reproduce as it just crashes right away!

**Comment by lszomoru** [comment]
Could you please follow [these steps](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) to collect a memory dump of the crash? Thank you!

**Comment by deepak1556** [comment]
Did you install the universal version of the app or apple silicon version ?

**Comment by Amin-Azar** [comment]
Apple silicon one.

-Amin
