### ISSUE TITLE
terminal view disappears

### ISSUE THREAD

**Issue by garrygerber** [microsoft/vscode#129054]
Issue Type: <b>Bug</b>

reproduce:
terminal tab -> new terminal -> select dir

expected: new terminal that is viewable
result: terminal appears for a second and then disapears

also when opening other view next to terminal like debug console, you can see terminal tab, but when clicked on, its again disapears

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|32.00GB (2.06GB free)|
|Process Argv|--crash-reporter-id 8a51f648-c019-4c1c-b80b-858a21f7312f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
go|gol|0.26.0
kubernetes-snippets|ipe|0.1.9
vscode-cfn-lint|kdd|0.20.0
vscode-docker|ms-|1.15.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
vscode-groovy-lint|Nic|1.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
elastic|ria|0.13.3
partial-diff|ryu|1.4.3
jenkins-jack|tab|1.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
Please attach a gif
