### ISSUE TITLE
Should extensionDependencies be tied more closely to their parent extension?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12908]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Related: #12906

Perhaps this was a design decision but how I was envisioning this working was that installing an extension `foo` that depended on `bar`. Would result in something like this in the extension viewlet:

- ext a [Uninstall]
- foo [Uninstall]
  - bar [Detach from foo/promote] [Uninstall]
- ext b [Uninstall]

Then uninstalling `foo` would also uninstall `bar`.

**Comment by joaomoreno** [comment]
We don't want to emphasise this feature. Extension dependencies should be used in rare situations, since we want extensions to be as independent as possible. They can't work as node modules do, so we don't treat them as so.
