### ISSUE TITLE
Expand `vscode.env` to include Product

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#129053]
We currently expose a few telemetry properties such as `machineId` through the `vscode.env` entry point. My proposal is to add an additional property called `product` to the mix in order to better discern between codespaces and web self-hosting as current extension telemetry would just list the product as "web". Additionally, this would allow extensions to more easily identify if they're in a codespace for example.

```
	export namespace env {

		/**
		 * The current "flavor" of VS code running. i.e Desktop, Codespace, Web. 
		 */
		export const product: string;
          }
```

**Comment by mjbvz** [comment]
Names ideas:
- `appFlavor`
- `appEmbedder`
- `embedderIdentifier`
- ?
