### ISSUE TITLE
Very slow intellisense

### ISSUE THREAD

**Issue by naor555666** [microsoft/vscode#129099]
Issue Type: <b>Performance Issue</b>

HI, it takes the intellisense about 4 second to autocomplete, make code suggestions, also sometimes it takes much time just to point on error in the file or point for missing props to pass to component(my project is with React TypeScript, it is not that large) etc.
The issue happens almost in every file in the project, but much less in plain css files. 

I tried:
- Disabling extensions
- Restarting VSC
- Computer restart
None of the above solved the problem.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (6.12GB free)|
|Process Argv|--crash-reporter-id ba1de4a7-23af-4995-b97d-105173c34dab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    74	  3468	code main
    0	   202	   712	   gpu-process
    0	    58	  1140	   shared-process
    0	    40	  8316	     ptyHost
    0	     4	  9292	       console-window-host (Windows internal process)
    0	     3	 14376	       C:\WINDOWS\System32\cmd.exe
    0	    16	 11816	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\naor5\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" start
    0	     4	 16816	           C:\WINDOWS\system32\cmd.exe /d /s /c react-scripts start
    0	    13	 13272	             electron_node react-scripts.js 
    0	   245	  8000	               "C:\Program Files\nodejs\node.exe" "C:\Users\naor5\visual studio code projects\coreai_platform1\node_modules\react-scripts\scripts\start.js"
    5	   342	 17104	                 "C:\Program Files\nodejs\node.exe" --max-old-space-size=2048 "C:\Users\naor5\visual studio code projects\coreai_platform1\node_modules\fork-ts-checker-webpack-plugin\lib\service.js"
    0	   231	  1468	   window (DataPresentationBlock.tsx - coreai_platform1 - Visual Studio Code)
    0	    12	 14360	     watcherService 
    0	     3	 10696	       console-window-host (Windows internal process)
    0	    88	 16708	     extensionHost
    0	    36	  2716	       "C:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16708
    0	    90	  4888	       electron_node tsserver.js 
    0	   272	  5656	       electron_node tsserver.js 
    0	    24	 13960	         electron_node typingsInstaller.js typesMap.js 
    0	    95	 10840	       electron_node eslintServer.js 
    0	    65	 10964	       "C:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=16708
    0	    32	 13848	       electron_node serverMain.js 
    0	    66	 14180	       "C:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\naor5\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=16708
    1	    76	  4272	   window (Issue Reporter)
    0	    12	 14140	   crashpad-handler
    0	    25	 15564	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (DataPresentationBlock.tsx - coreai_platform1 - Visual Studio Code)
|    Folder (coreai_platform1): 73 files
|      File types: png(25) tsx(17) ts(9) json(4) css(2) gitignore(1) ico(1)
|                  html(1) txt(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
vscode-eslint|dba|2.1.23
vscode-npm-script|eg2|0.3.22
auto-rename-tag|for|0.1.7
vscode-styled-components|jpo|1.6.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share a small project that demonstrates the issue

**Comment by naor555666** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> If so, please share a small project that demonstrates the issue

Hi, thanks for the replay.
I tried using the latest VS code insiders with all extensions disabled- it won't solve the issue.
I recently noticed that the intellisense works much faster when I comment most of my styled components which are being used in the component flow and just leave the wrapper element(that is also a styled component), for example:

 `const DataPresentationBlock: React.FC<DataPresentationBlockProps> = () => {
    const [isFeaturesPresentation, setIsFeaturesPresentation] = useState(true)

    return (
        <StyledDataPresentationBlock style={{ marginRight: 'auto' }}>
            {/* <StyledPresentationBlockTopBar>
                <div style={{ marginRight: 'auto' }}>
                    <ThemeTextBold>KPI's</ThemeTextBold>
                    <ThemeTextNormal >Key Prediction Indicators</ThemeTextNormal>
                </div>

                <div style={{ display: 'flex', alignItems: 'center' }}>
                    <StyledElement style={{ marginRight: '16px' }}>
                        <ThemeTextNormal fontSize='32px'>$63/58</ThemeTextNormal>
                    </StyledElement>
                    <StyledIcon background={down_arrow_icon_path} height='18px' width='19px' />
                </div>

                <div style={{ marginLeft: 'auto', visibility: 'hidden' }}>
                    <ThemeTextBold>KPI's</ThemeTextBold>
                    <ThemeTextNormal >Key Prediction Indicators</ThemeTextNormal>
                </div>

            </StyledPresentationBlockTopBar>
            <StyledPresentationBlockOptionsBar>
                <Paragraph1 fontSize='17px' onClick={e => setIsFeaturesPresentation(true)} style={{ cursor: 'pointer', borderBottom: isFeaturesPresentation ? '3px solid #696969' : 'none' }}>Features</Paragraph1>
                <Paragraph1 fontSize='17px' onClick={e => setIsFeaturesPresentation(false)} style={{ cursor: 'pointer', borderBottom: isFeaturesPresentation ? 'none' : '3px solid #696969' }}>Clusters</Paragraph1>
                <StyledDateInput type="date" style={{ marginLeft: 'auto' }} />
                <StyledIcon style={{ marginRight: '4%' }} background={pyramid_icon_path} width='19.5px' height='16.1px' />
            </StyledPresentationBlockOptionsBar> */}
        </StyledDataPresentationBlock>
    );
}`

I am using the latest version of Styled Components and also I tried to use TypeScript nightly and even older versions of TypeScript, none of these worked to solve the issue.

My insight is that this issue has something to do with Styled Components or kind of load(even though my file is not that much loaded)...frustrating, please help.

**Comment by mjbvz** [comment]
To help us investigate the perf issue, can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this


If you can share a self contained project that demonstrates the issue, we can also use that to investigate on our end

**Comment by lorand-horvath** [comment]
Latest version 1.59 has very slow intellisense on .js files. Also if I comment out a line with // the green highlighting doesn't appear over all characters in the commented line, but only on some of them, it looks very strange. The line is greened out only after I swtich to another tab and back or if I hover over the comment with the mouse and then "Loading..." appears as tooltip for a few seconds and only then the comment turns completely green. It is indeed, very slow. Autocompletes are also appearing only after about 4-5 seconds... very annoying.

**Comment by lorand-horvath** [comment]
@naor555666 Are you using mongoose? Please see https://github.com/Automattic/mongoose/issues/10349
