### ISSUE TITLE
Output panel dropdown context view becomes detached from select box on panel resize

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#129085]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  b805d2e94937976bb17d0439f57fcd3a9d423c31
- OS Version: Windows 10

Steps to Reproduce:

1. Click on the output panel dropdown
2. Resize the output panel
3. 🐛 dropdown is detached from select box
![recording (1)](https://user-images.githubusercontent.com/30305945/126430475-45ab2218-3d7c-42f2-b7fe-880f7f5aeee2.gif)

**Comment by sandy081** [comment]
@isidorn Seems to be an issue with the custom select box widget

**Comment by jeanp413** [comment]
Duplicate of #113675, also created a PR with a fix #113723
