### ISSUE TITLE
Webviews over ssh session sometimes don't work

### ISSUE THREAD

**Issue by mateuszkitlas** [microsoft/vscode#129042]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.1
- OS Version: Ubuntu 18.04

I'm developing my own extension. Sometimes (like 1 in 5 times) webviews just don't load leaving js script with `host.js`
![obraz](https://user-images.githubusercontent.com/14885572/126314479-224a7a20-de05-459a-85ba-549c90c2153f.png)
![obraz](https://user-images.githubusercontent.com/14885572/126314509-0d136147-f0d4-4781-b4b8-f14925f03b98.png)

This affects both webviews `window.registerWebviewViewProvider` and `window.createWebviewPanel`. I tried to detect this situation, then `dispose()` badly registered webview and register it again - but it does nothing.

In my case no HTML is loaded.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
