### ISSUE TITLE
Extensions with 0 installs should say 0 installs in viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12905]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

It shows the extension with nothing on the right, why not be explicit?

![image](https://cloud.githubusercontent.com/assets/2193314/18924149/f383dcf8-8563-11e6-9a2b-8d82a88da921.png)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/19074949/01f2f72c-8a43-11e6-9af3-37ca03d5f3d6.png)

I do see it though. 😕

**Comment by Tyriar** [comment]
Hmm :confused:
