### ISSUE TITLE
investigate why instance.onDidDispose isn't firing

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129074]
here https://github.com/microsoft/vscode/pull/128875/files#diff-f693edbad2c9d59a0822f8a026ef7fecdd0a39fc904658cf2f385d84e89569c3R226

necessitating this call
https://github.com/microsoft/vscode/pull/128875/files#diff-f1883fa148c75292499e7150b63a75610d76d58bb20cefff0213d1f5ec6b88fcR265

**Comment by meganrogge** [comment]
@Tyriar should we close this?

**Comment by Tyriar** [comment]
👍 I removed the instance disposable that wasn't firing.
