### ISSUE TITLE
Test: terminal options color

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129009]
Refs #128228

- [x] macOS @sandy081
- [x] linux @deepak1556 
- [x] windows @rzhao271

Complexity: 3

Authors: @meganrogge, @tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129009%0A%0A&assignees=meganrogge,tyriar)

---
With proposed API [enabled](https://code.visualstudio.com/api/advanced-topics/using-proposed-api), use the extension-terminal-sample to test that you can:
- set color in `createTerminal` to a `ThemeColor` 

This color should appear in:
- the TerminalQuickPick via `Ctrl P`
- the terminal tabs list if it's in a group
- the editor tab if it's in the editor area
- as you switch active terminals in the single tab terminal view action item
- anything else you can think of

**Comment by sandy081** [comment]
@meganrogge I am sorry that I could understand the locations you mentioned, for eg., I am not sure where `TerminalQuickPick` is and `ctrl+p/cmd+p` opens normal quick pick for me. Also did not understand what you mean by `as you switch active terminals in the single tab terminal view action item` ? Can you please give more context about these locations.

Irrespective of that, tested following:

- Tested the theme color is shown when the terminal is in the panel and in the editor. 
- When in the editor also tested in file quick pick, recently opened list and in opened editors view in the explorer.

Hope this is good enough.

**Comment by Tyriar** [comment]
@sandy081 terminal quick pick above means ctrl/cmd+p "term ":

![image](https://user-images.githubusercontent.com/2193314/127149596-4465a9ca-9c89-41fc-a2a4-effeee4757cf.png)
