### ISSUE TITLE
Debug console input has a large gap on the left

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12903]
![image](https://cloud.githubusercontent.com/assets/323878/18923930/14865df0-8563-11e6-8dfd-e3fbad42eb62.png)
That text is as far left as I can go

**Comment by roblourens** [comment]
@octref Pointed out, if you have Vim installed
![image](https://cloud.githubusercontent.com/assets/323878/18924118/dcc7aeea-8563-11e6-8218-207cdde41722.png)

**Comment by roblourens** [comment]
Relative line number change?

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/12879
