### ISSUE TITLE
C# (powered by OmniShar) Extension

### ISSUE THREAD

**Issue by kepeter** [Microsoft/vscode#12902]
Hello,

Not sure the right place to report, but couldn't figure out better...

Any case... When opening a C# project (folder) - after installing the extension - OmniSharp installed in the background. Everything seems perfect, but the OmniSharp installation is useless as it installs a 64 bit version, that can not be run on this machine!!!

> Installing OmniSharp to C:\Users\peter\.vscode\extensions\ms-vscode.csharp-1.4.1\out\.omnisharp-coreclr
    Attempting to download omnisharp-1.9-beta14-**win-x64**-netcoreapp1.0.zip
    Downloading to C:\Users\peter\AppData\Local\Temp\tmp-2768LYlP6LMQhvgw.tmp...
    Download complete!
    Decompressing...
    Done! 441 files unpacked.

> Starting OmniSharp server at 28.9.2016, 20:04:57
    Target: c:\Users\peter\Documents\VSCode\ASPTest

> OmniSharp server started
    Path: C:\Users\peter\.vscode\extensions\ms-vscode.csharp-1.4.1\out\.omnisharp-coreclr\OmniSharp.exe
    PID: 2916

> This version of C:\Users\peter\.vscode\extensions\ms-vscode.csharp-1.4.1\out\.omnisharp-coreclr\OmniSharp.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

- VSCode Version: 1.5.3
- OS Version: Win 7 - 32 bit

Steps to Reproduce:

1. Install VSCode 1.5.3 on win 7 - 32 bit
2. Install extension for C#
3. Open the output pane
4. Open a C# project (folder)
5. See what on the output pane

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://github.com/OmniSharp/omnisharp-vscode/issues
