### ISSUE TITLE
Can't execute in-app html to chrome on chrome os (debian)

### ISSUE THREAD

**Issue by Kodbaz** [microsoft/vscode#129013]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Chrome OS 91.0.4472.147 (64 bits), Debian GNU/Linux 10 (buster)

Steps to Reproduce:

1. Open an HTML file
2. do Ctrl + F5

here a screenshot of the error:

![Error Popup](https://user-images.githubusercontent.com/81097895/126230091-cda7275d-9674-4c9e-b772-c5d196bdf38c.png)

**Comment by connor4312** [comment]
We should fall back to the discovered version in these cases
