### ISSUE TITLE
SCSS when using the select all elelements selecor, triggers comment when opening block

### ISSUE THREAD

**Issue by babobski** [microsoft/vscode#129068]
Issue Type: <b>Bug</b>

I'm currently having a issue when writing SCSS.
When I try to type the following:

```SCSS

.selctor {
    * {
    
    }
}
```

I'm getting the following result.

```SCSS
.selctor {
    * {
    * }
}
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.02GB free)|
|Process Argv|--crash-reporter-id c30c5460-fb42-48d6-a3d8-41454c79982a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.1.0
aspect-ratio|Bab|0.0.2
bootstrap-5-snippets|bab|0.0.2
svg-data-uri|Bab|0.0.2
tatu-diff|Bab|0.1.6
vertaaltags|bab|0.0.1
vscode-intelephense-client|bme|1.7.1
vscode-path-tools|cg-|0.0.4
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
php-debug|fel|1.16.1
php-pack|fel|1.0.2
triggertaskonsave|Gru|0.2.17
vscode-wordpress-hooks|joh|0.5.4
auto-comment-blocks|kev|1.0.1
sftp|lix|1.12.9
lucidocean-plurge|Luc|0.0.5
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
html-css-class-completion|nat|1.20.1
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.8.0
format-html-in-php|rif|1.7.0
open-in-browser|tec|2.0.0
vscode-wakatime|Wak|14.0.2
searchwpdocs|yog|2.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by aeschli** [comment]
I'm not able to reproduce
![scss](https://user-images.githubusercontent.com/6461412/126457319-fe84f265-5496-4fe6-8f12-5beadb92dbfa.gif)

Can you run with extensions disabled to make sure this isn't caused by another extension?
