### ISSUE TITLE
Add positive and negative filters to search editor results

### ISSUE THREAD

**Issue by ssigwart** [microsoft/vscode#129063]
Moved from https://github.com/microsoft/vscode/issues/67397#issuecomment-883028881.

The video below is from Komodo Edit.  Essentially, I searched for `<img`, then I wanted to find those with a width, but no height, so I can filter the existing search results using `-height width` (note: the inputs are at the bottom of the video and may get covered up by the video timeline and controls).

https://user-images.githubusercontent.com/1426848/126258177-29e47e96-6cb2-43dd-888b-4e485dbbd8ce.mov

@JacksonKearl, if I implement a text box at the top or bottom of the Search Editor to do this, do you think it's something that would be merged.  I could make it a non-default setting if that would help the chances.

**Comment by JacksonKearl** [comment]
I would recommend doing this using text edits/multicursor/find in the search editor itself, that is much of why we have the search results in an editor.

**Comment by ssigwart** [comment]
Thanks, @JacksonKearl.  I was able to create an extension to accomplish this:
https://marketplace.visualstudio.com/items?itemName=ssigwart.search-results-filter
