### ISSUE TITLE
Log more information on settings sync RequestFailed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129011]
`RequestFailed` is abnormally high, this appears to be when electron's net module throws when the request is running but we can't investigate further without more info on the exception.

https://github.com/Microsoft/vscode/blob/c4fa9ff85be86d821de2a496c1a9a3a83ea57e09/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts#L400-L404

@deepak1556 any idea on what type of things could go wrong when electron's `net.request` throws? We're currently handling request cancelation and timeout but there are more failures happening.

**Comment by deepak1556** [comment]
@Tyriar can you point where we are using electron's net module ? I couldn't find any references to `Electron.ClientRequest`, we only seem to be using node's net module.

**Comment by Tyriar** [comment]
@deepak1556 https://github.com/Microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/platform/request/electron-main/requestMainService.ts#L8-L20

**Comment by deepak1556** [comment]
Oh cool, okay the module can throw only when the request constructor options are invalid, specifically:

1) If opts.protocol is not `https` or `http` https://github.com/electron/electron/blob/d35fb2a2e37a84f304b69ff7428eefa784ecbace/lib/browser/api/net.ts#L217

2) If opts.path contains a space https://github.com/electron/electron/blob/d35fb2a2e37a84f304b69ff7428eefa784ecbace/lib/browser/api/net.ts#L242

3) If opts.headers is not an object https://github.com/electron/electron/blob/d35fb2a2e37a84f304b69ff7428eefa784ecbace/lib/browser/api/net.ts#L257 or if the value is not valid (which is based on the following check https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_util.cc;l=341-355)

**Comment by sandy081** [comment]
Thanks @deepak1556

Added following codes when request fails on the client

```
       RequestCanceled = 'RequestCanceled',
	RequestTimeout = 'RequestTimeout',
	RequestProtocolNotSupported = 'RequestProtocolNotSupported',
	RequestPathNotEscaped = 'RequestPathNotEscaped',
	RequestHeadersNotObject = 'RequestHeadersNotObject',
        RequestFailed = 'RequestFailed',
```

`RequestFailed` is the default error code.

**Comment by Tyriar** [comment]
Let's see how this goes, if we continue to see more unexpected `RequestFailed`s over time maybe we should think about sanitizing(?) and logging the exception message too?
