### ISSUE TITLE
VS Code stops working from command line after update

### ISSUE THREAD

**Issue by juhacket** [microsoft/vscode#129072]
Issue Type: <b>Bug</b>

Every time VS code is updated the search function stops working for active VS Code windows and I can no longer launch new windows from command line using "code [path]". The only solution is to reinstall VS Code.  I get this error:

PS D:\> code .
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.98GB free)|
|Process Argv|--crash-reporter-id 45707cbd-6960-4200-b22d-d92f47ce14f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
go|gol|0.26.0
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.13
powershell|ms-|2021.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vsdfh931:30280409
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by dparkar** [comment]
Facing the same issue. Looks like this issue has happened quite a few time in the past.

**Comment by joaomoreno** [comment]
Yes please uninstall and reinstall VS Code.
