### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by geoxx3** [microsoft/vscode#129089]
We have written the needed data into your clipboard because it was too large to send. Please paste

Issue Type: <b>Bug</b>

Extension host terminated unexpectedly

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.11GB free)|
|Process Argv|--crash-reporter-id c344d6aa-c36a-416b-a9ab-766733878226|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
compile-superhero|Ban|10.3.2
vscode-icontheme-nomo-dark|be5|1.3.6
emmet-jss|car|1.0.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
javascript-ejs-support|Dig|1.3.1
vscode-escape-entities|dja|0.1.0
prettier-vscode|esb|8.0.1
php-debug|fel|1.16.1
file-icons|fil|1.0.29
beautify|Hoo|1.5.0
vscodefy|iag|0.0.11
vscode-gutter-preview|kis|0.27.1
remotefs|lix|0.0.16
sftp|lix|1.12.9
dotenv|mik|1.0.1
vscode-pugbeautify|mrm|1.0.2
python|ms-|2021.7.1050252941
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
open-html-in-browser|pea|2.1.6
emoji|Per|1.0.1
material-icon-theme|PKi|4.8.0
seti-icons|qin|0.1.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
tabnine-vscode|Tab|3.4.17
vscode-todo-highlight|way|1.0.4
eno|Wsc|2.3.53
material-theme|zhu|3.11.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
