### ISSUE TITLE
Aborting rebase results in merge conflict indicators staying on files

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129002]
On today's Insiders, I did `git pull --rebase origin main`, but then realized I didn't want to continue with the rebase, and ran `git rebase --abort`. I checked out `main` instead, and noticed that the merge conflict indicators were still on the file, even though both `git status` and the SCM view showed no merge conflicts. Running the "Merge Conflict: Next Conflict" command also didn't show anything:

![A notification showing that there are no merge conflicts in the file](https://user-images.githubusercontent.com/7199958/126202114-6632eff8-f323-4b7f-ade5-4deccee3cae2.PNG)

**Comment by eamodio** [comment]
Almost missed them at first -- the indicators that are showing up are in the tabs.
