### ISSUE TITLE
terminal cmd+click soft link file but open in original folder

### ISSUE THREAD

**Issue by laowong** [microsoft/vscode#129023]
Issue Type: <b>Bug</b>

1、I'm using extension "Remote - SSH" develop in remote machine
2、My home folder is "/home/xxx/" which is a soft link to /data00/home/xxx
3、Open a folder "/home/xxx/project" in remote machine with vscode
4、 In integrated terminal use "git grep --line-number <keywords>" to search some content in folder "/home/xxx/project", and "cmd+click" the file path
5、vscode open the file in origin folder "/data00/home/xxx/project/yyy.go", but I think it should be open in "/home/xxx/project/yyy.go", becase my workspace folder in vscode is "/home/xxx/project"

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 4.19.117.bsk.6-amd64
Remote OS version: Linux x64 4.19.117.bsk.6-amd64
Remote OS version: Linux x64 4.19.117.bsk.6-amd64
Remote OS version: Linux x64 4.19.117.bsk.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 882949e7-e8bb-454f-b5bf-a038f7b08a64|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 4.19.117.bsk.6-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.03GB (1.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 4.19.117.bsk.6-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.03GB (1.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 4.19.117.bsk.6-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.03GB (1.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 4.19.117.bsk.6-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|15.03GB (1.37GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.58.8
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
go|gol|0.26.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by Tyriar** [comment]
This works fine when I tried to repro:

```
mkdir actual
ln -s actual link
touch actual/testfile
cd link
echo $(pwd)/testfile
```

The printed link `/home/daniel/link/testfile` correctly does not resolve the symlink:

![image](https://user-images.githubusercontent.com/2193314/126493552-0ef5e5f3-4b7f-4d83-80bd-41b8f9e6f125.png)

Anything in the repro I'm missing?

**Comment by laowong** [comment]
It's also OK when I tried in local machine, but was wrong when tried in remote machine using extension "Remote - SSH".

**Comment by Tyriar** [comment]
This was on Windows via WSL which should work the same as Windows -> SSH. Can you post a screenshot of the link format that you clicked?

**Comment by laowong** [comment]
@Tyriar I'm on MAC OS^_^

**Comment by Tyriar** [comment]
I wouldn't expect that to make a difference, but it's possible.

**Comment by laowong** [comment]
![image](https://user-images.githubusercontent.com/10355814/126584090-f8f4af1a-0628-4131-85d9-02013c8c4963.png)

@Tyriar Supply the screenshot。The step difference with you is I "cmd+click"  the relative path on `grep` result.

**Comment by laowong** [comment]
> It's also OK when I tried in local machine, but was wrong when tried in remote machine using extension "Remote - SSH".

**Comment by laowong** [comment]
Sorry I closed this issue carelessly. Can you help me reopen it? @Tyriar

**Comment by laowong** [comment]
Sorry I closed this issue carelessly.

**Comment by Tyriar** [comment]
That's great thanks, can repro. It happens with `./testfile:xxx` but not `./testfile` the folder also must be open to make it happen since it's a relative link.

**Comment by Tyriar** [comment]
Ok more info on repro which is much more involved than initially thought:

- Happens in a local workspace on Linux and macOS
- Do setup in https://github.com/microsoft/vscode/issues/129023#issuecomment-884175381
- Open the `link` folder, make sure the symlink isn't resolved when opening the window which can happen when opening via the open command, use the CLI instead: `code ./link`
- Run `echo ./testfile`, it's important that enter is pressed at least once before trying to click the link\*
- Wait 2+ seconds
- Try open the test file via the link

\*Note that if you reload the window you need to hit enter and wait before it will happen

**Comment by Tyriar** [comment]
What I've found so far

- For mac it's happening because of the cwd query happening here: https://github.com/microsoft/vscode/blob/424a1166f37f10e11f8f88dbbb5d6930a8f9d3f9/src/vs/platform/terminal/node/terminalProcess.ts#L489
- This should be ensuring the symlink is not resolved https://github.com/microsoft/node-pty/pull/156
- I found https://unix.stackexchange.com/a/501007/115410 which says `lsof` with `-b` will not use `readlink` but it doesn't appear to make a difference, the cwd appears to be tracked here resolved

**Comment by Tyriar** [comment]
Can confirm unresolved cwd is passed to node-pty:

<img width="393" alt="Screen Shot 2021-07-22 at 5 01 44 AM" src="https://user-images.githubusercontent.com/2193314/126636012-58f32e86-3f2f-41ab-afde-da1a329e90c7.png">

**Comment by Tyriar** [comment]
For Linux it happens because of the readlink here: https://github.com/Microsoft/vscode/blob/424a1166f37f10e11f8f88dbbb5d6930a8f9d3f9/src/vs/platform/terminal/node/terminalProcess.ts#L507-L507, not sure it's possible to readlink to the `link` symlink instead of `actual`

**Comment by Tyriar** [comment]
Asked on unix stack exchange: https://unix.stackexchange.com/q/659464/115410

**Comment by Tyriar** [comment]
If all else fails we could check if the initial cwd was a symlink and that is resolves to the current cwd and use that. It's not ideal, plus it would fall apart if you actually cd into `actual`

**Comment by Fallonma** [comment]
I met this issue recently. Besides this, there are two more issues. #108306, #105656. Maybe they have the same reason.
