### ISSUE TITLE
Let me refresh the extension list in a reliable way

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12909]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
#12647

It seems very random sometimes when I get informed there is an update to an extension. Sometimes it takes 10+ minutes to get an update, sometimes it's unclear whether I have the updated version and the version string in the viewlet is lying to me.

A refresh button next to the viewlet title or in the overflow would be useful.

**Comment by Tyriar** [comment]
I figured out a work around for this which is to search for it, this took me literally weeks to find though. A refresh button would be far more intuitive.

**Comment by joaomoreno** [comment]
We now have a `Check for Updates` action.
