### ISSUE TITLE
Commands and menus should know from which extension they come

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#129034]
contines https://github.com/microsoft/vscode/commit/d624242076d166bb8ce8b314e8d44b8af6100a3d#commitcomment-53718851

Extensions can contribute commands, menus, and submenus. We do know which extension has contributed what and some UI wants to surface that information. To support this we would need to extend `ICommandAction`, `ISubmenuItem`, and `IMenuItem` which either the extension description/identifier or with a more generic "source" string.

**Comment by JacksonKearl** [comment]
\closedWith https://github.com/microsoft/vscode/commit/ece433775144f6229f40e5d60b8fa9e98c1f32a2

**Comment by jrieken** [comment]
@JacksonKearl Can you add verification steps? Does this show in the New File menu?

**Comment by JacksonKearl** [comment]
Install Luna Paint, check `File => New File...` Menu:
![image](https://user-images.githubusercontent.com/8586769/130501417-1310ed65-031e-400f-8aa0-a243306c587b.png)

code pointer:
https://github.com/microsoft/vscode/blob/e909ece93a75d6e053c916b792f8b8b4a96a4bbe/src/vs/platform/actions/common/actions.ts#L48

**Comment by bpasero** [comment]
@JacksonKearl should "New File..." be directly under "New File"?

![image](https://user-images.githubusercontent.com/900690/130602615-361eb998-738a-4fab-a03e-ca1630e0dbd3.png)
