### ISSUE TITLE
Collapsed notebook cells are rotated 270 degrees in Codespaces

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#129090]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59-Insider b805d2e94937976bb17d0439f57fcd3a9d423c31
- OS Version: Windows 10

Steps to Reproduce:

1. Create a notebook
2. Collapse a cell
3. 🐛 cells are rotated 270 degrees. Seems to be because we use the 'collapsed' classname for cell collapse, and xterm.js loads a stylesheet which applies `transform: rotate(270deg)` to the `collapsed` classname. This stylesheet is not loaded in desktop VS Code so the problem seems to only impact Codespaces

This is particularly unfortunate for the interactive window because all code cell inputs are collapsed by default, but it also impacts any collapsed cell in native notebooks all up.

![recording (5)](https://user-images.githubusercontent.com/30305945/126441667-bf34a471-5a38-4b65-a5e8-a1877f3b1d34.gif)

**Comment by roblourens** [comment]
https://github.com/github/codespaces/issues/2871 I filed this a long time ago, but this is pretty bad, I will just change the styles to work around it in the meantime

**Comment by rebornix** [comment]
@roblourens https://github.com/microsoft/vscode/pull/129091 fix proposal from @joyceerhl
