### ISSUE TITLE
Support the ability to force re-authing in the Auth APIs

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129064]
Handling dead tokens and tokens that don't have SSO for a particular GitHub org is absolutely needed in extensions like Remote Repositories and GHPR who today, don't fail gracefully. GHPR shows a notification that complains about SSO, for example... 

These extensions need some way to force the recreation of an OAuth token but the Auth API doesn't give that today. As such, I'd like to introduce the `forceRecreate` property which, when passed to `getSession` will ignore the fact that an existing session exists and go straight to creating a fresh session and return said session. It will overwrite whatever session was there before (with the specified scopes) and so future calls to `getSession` will pick up that new token.

In short... Expand:
https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L13643-L13671
and
https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L13793

API proposal:
```ts
	/**
	 * Options to be used when getting an {@link AuthenticationSession} from an {@link AuthenticationProvider}.
	 */
	export interface AuthenticationGetSessionOptions {
                // NEW
                forceRecreate?: boolean;
		createIfNone?: boolean;
		clearSessionPreference?: boolean;
	}
```
and adding the following
```ts
export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceRecreate: true }): Thenable<AuthenticationSession>;
```
> Note the `& { forceRecreate: true }` similar to the other `getSession` to change return type.

Usage:
```ts
await vscode.authentication.getSession('github', ['repo'],{ forceRecreate: true });
```

Notes:
* This property will throw just like the `getSession` with `createIfNone` (when aborted) but the existing session will be left in place so that other extensions are not disrupted by the cancelling. (it's possible that one extension cares about SSO and one doesn't for example)
* If the user does not have an existing session, the API will throw saying that there was no session. This is because the scenario for this property is specifically for recreating a session that already exists.

**Comment by TylerLeonhardt** [comment]
cc @eamodio @alexr00

**Comment by alexr00** [comment]
@TylerLeonhardt maybe an auth noob question, but how do I know when to use `forceRecreate`? How do I know that the token is dead?

**Comment by TylerLeonhardt** [comment]
@alexr00 and I talked offline about this and she has a fantastic repro of the SAML issue.

**Comment by TylerLeonhardt** [comment]
Moving this to next milestone for finalization.

**Comment by mjbvz** [comment]
- `forceNewSession` 
-  `forceReauthentication`

**Comment by TylerLeonhardt** [comment]
Here are what the modals look like:

![image](https://user-images.githubusercontent.com/2644648/128097638-20830351-e761-4b6b-82f4-c69ed0c43591.png)

![image](https://user-images.githubusercontent.com/2644648/128097665-32f21955-b610-489a-9878-7a7b2b3477e5.png)

**Comment by TylerLeonhardt** [comment]
Moved to sept to wait on feedback.

**Comment by TylerLeonhardt** [comment]
finalized in 297c52bd80d8dbd18c1bf1900fee25aa8b7a5044
