### ISSUE TITLE
Terminal Goes Away Indiscriminately

### ISSUE THREAD

**Issue by UnderJollyRoger** [microsoft/vscode#129057]
Issue Type: <b>Bug</b>

Why does my terminal not stick around? I'm trying to set up a conda python terminal, and suddenly my terminal window only sticks around for a couple seconds before it goes away. Every time I open a new one (i.e. Terminal> New Terminal, View> Terminal) it goes away on its own? None of the other tabs do this (i.e. Problems, Output, Debug Console).

All I've done was follow this blog so I can use an anaconda python environment in VS Code. https://medium.com/analytics-vidhya/efficient-way-to-activate-conda-in-vscode-ef21c4c231f2

****UPDATE:**
I've set these variables in the *settings.json* file according to the blog. When I remove them the terminal returns to normal behavior (i.e. it no longer goes away indiscriminately).

```json
    "python.pythonPath": "C:\\ProgramData\\Anaconda3\\envs\\py37\\python.exe",
    "python.terminal.activateEnvironment": true,
    "terminal.integrated.shell.windows": "C:\\ProgramData\\Anaconda3\\Scripts\\activate.bat",
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.92GB free)|
|Process Argv|--crash-reporter-id 5ffe9918-f1d2-4621-9a3d-7860791bbe1d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
nbpreviewer|jit|1.2.2
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
@karthiknadig any thoughts?

**Comment by karrtikr** [comment]
> "terminal.integrated.shell.windows": "C:\\ProgramData\\Anaconda3\\Scripts\\activate.bat",

This does not seem right. It should be pointing to the path to a windows shell like `C:\\Windows\\System32\\cmd.exe`. This is not a valid path to terminal.

**Comment by UnderJollyRoger** [comment]
I set the variables again and changed the path to the *cmd.exe. The behaviour I was originally getting hasn't came back. And it seems like my conda environment is functioning. Thanks.
