### ISSUE TITLE
Give visual notification if externally changed open file reloaded from disk

### ISSUE THREAD

**Issue by IKatsu** [microsoft/vscode#129000]
I would like some sort of visual indication that a file was altered on disk and automatically reloaded by the editor.
I often have a debug file open that gets generated by whatever I'm writing and I would like some sort of indication when the viewer detects it having been changed on disk and reloads it. Something simple like just highlighting the tab in a different colour would be enough.

If anyone wants to take it a step further, monitor all project files for if they have been changed outside of the editor even if they're not open and highlight them in the workspace explorer.

**Comment by bpasero** [comment]
Related https://github.com/microsoft/vscode/issues/23107
