### ISSUE TITLE
extensionDependencies should support @x.y.z annotation in addition to ^ and ~ as in dependencies

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12906]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Extension authors will use `extensionDependencies` for more than just packs but to rely on the contributions an extension exposes. That means that it becomes important when API breakages occur. An example of this is an extension that uses `registerTextDocumentContentProvider` could be depended upon by another to utilize its `TextDocumentContentProvider`.

**Comment by joaomoreno** [comment]
Although I do see the benefit, we currently neither support installing old extension versions not running different versions of the same extension simultaneously... both situations that would quickly emerge from this.

We're rolling out with this first and let's tackle the specific dependency issues when they come.
