### ISSUE TITLE
Keyboard Input Issue

### ISSUE THREAD

**Issue by bitjumper** [microsoft/vscode#129056]
Issue Type: <b>Bug</b>

Not taking keyboard input, particularly delete, and ctrl-x are not working, other edits are only possible after hitting the "insert" key.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:20:02.397Z)
OS version: Linux x64 4.15.0-147-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2655LE CPU @ 2.20GHz (4 x 2153)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|3.74GB (0.10GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
doxdocgen|csc|1.3.2
pdf|fri|0.0.6
vscode-pull-request-github|Git|0.28.0
jenkinsfile-support|ivo|1.1.0
vscode-edit-csv|jan|0.6.0
better-cpp-syntax|jef|1.15.6
makefile-command-runner|mad|1.4.1
rainbow-csv|mec|1.9.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
html5-boilerplate|sid|1.1.1
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
shellcheck|tim|0.14.4
pdf|tom|1.1.0
cmake|twx|0.0.17
vim|vsc|1.21.5
vscode-todo-highlight|way|1.0.4
debug|web|0.25.1
txt-syntax|xsh|0.1.6

(1 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
Could you please try the troubleshooting steps documented [here](https://github.com/microsoft/vscode/wiki/Keybinding-Issues).
