### ISSUE TITLE
"Continue backward" button has wrong position in debug toolbar

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129039]
The "Continue backward" button in the debug toolbar is placed between the Restart and the Stop buttons:
 
<img width="663" alt="2021-07-20_12-53-18" src="https://user-images.githubusercontent.com/1898161/126313100-d3a0b3cf-d2c1-40ff-b8b9-d783f97350d9.png">

It should be moved one position to the left so that it is at the end of the "stepping" group.

**Comment by abdlrhmanshehatamoussa** [comment]
Hi Guys,

I'm ready to help,

If any one could give a little push on where exactly can find the relevant code and any other recommendations, I'm ready to gooo.

Best of luck !

**Comment by isidorn** [comment]
Sorry for the slow response, I was on vacation.
I plan to fix this tomorrow. @abdlrhmanshehatamoussa if you fix it before than (in the next 24hrs) I am open to accept a PR.
Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L297

**Comment by abdlrhmanshehatamoussa** [comment]
Hi Isidor
No worries at all, welcome back, hope you enjoyed your vacation ^_^

I think it's a minor change, I have some free time in the next hours, I think I will try to submit a PR, seems like a good start for me.

Thanks

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @isidorn 

Thanks to your code pointer, I was able to reposition the buttons as needed.

Now I want to test my changes (see it in action), but I'm not able to see the reverse debugging buttons on my normal version, should I just push the PR, or there is some customization that can allow me to see the reverse debugging buttons.

Thanks in advance !

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @isidorn 

As it's the end of day here, so I submitted the pull request so that you can review it tomorrow.
I will follow up with in case any further updates is needed.

Thanks,
