### ISSUE TITLE
Log http code for RequestUnknown settings sync failures

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129010]
Now we log the code for RequestUnknown failures as `"Unknown"`. This appears to happen when the returned http code is unexpected. We can't fix these unless we know what the actual codes are so we need the http code logged.

https://github.com/Microsoft/vscode/blob/c4fa9ff85be86d821de2a496c1a9a3a83ea57e09/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts#L456-L458

**Comment by sandy081** [comment]
Included `serverCode` while reporting `sync/error` event
