### ISSUE TITLE
Suggestions doesn't show up for styled-components

### ISSUE THREAD

**Issue by kundanb** [microsoft/vscode#129027]
Issue Type: <b>Bug</b>

Hello VSCode Team,

I am a die heart fan of VSCode because of endless feature supports, but I want you to know about a problem I discovered when using styled-components, the suggestions doesn't show up. When I use extends feature of styled-components, VSCode get stuck into low performance calculation due to which suggestions show up after waiting about  3-4 seconds.

Thanks and Regards

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.55GB free)|
|Process Argv|D:\\kundanb\\client --crash-reporter-id 856cd582-9587-483e-8839-de2747304259|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
vscode-styled-components|jpo|1.6.4
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
powershell|ms-|2021.6.2
vsliveshare|ms-|1.0.4583
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Without more information, this sounds like it is caused by your styled components extension. Please file an issue against them
