### ISSUE TITLE
openTextDocument(uri: Uri) duplicates document on save

### ISSUE THREAD

**Issue by verociraptor** [microsoft/vscode#129060]
Issue Type: <b>Bug</b>

- VS Code Version: 1.58.2 (user setup)
- OS: Windows_NT x64 10.0.19043
- No extensions installed

Steps:
1. Set up command and handler function to use. The `openTextDocument` is given an untitled scheme with a system location:
```
// extension.ts
function creation() {
    const newFile = vscode.Uri.parse('untitled:' + 'c:\\test.txt');

    vscode.workspace.openTextDocument(newFile).then((document) => {
        vscode.window.showTextDocument(document).then((editor) => {
            if(!editor){
                console.error("Could not show.");
                return;
            }

            editor.insertSnippet(new vscode.SnippetString("Hello"));
        });
    });
}
export function activate(context: vscode.ExtensionContext) {
  const createFileDisposable = vscode.commands.registerCommand('composition-companion.createFile', creation);
  context.subscriptions.push(createFileDisposable);
}
```
2. Run command
3. Hit Save

The file is duplicated and the duplicated file is the one that is saved at the provided location while the one that was originally created remains unsaved. 

![image](https://user-images.githubusercontent.com/36288316/126360780-2f350295-c768-4e52-bc0f-ea4673f75e09.png)

I rollbacked to the vscode version 1.57.1 and did not encounter this issue. I expect a single document to pop up and it should be the one to save at the location provided.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.76GB (33.42GB free)|
|Process Argv|--crash-reporter-id 18ff36bc-0ca0-4df0-89f9-5ad152a9aa65|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by Arkadiy-bb** [comment]
I have the same issue.

**Comment by bpasero** [comment]
This seems like bad creation of a URI, it works for me with: `vscode.Uri.file('c:\\Users\\bpasero\\Documents\\ticino-playground\\test.txt').with({ scheme: 'untitled' });`

I will update the JSDoc to indicate this.

**Comment by Arkadiy-bb** [comment]
The path I am using is coming from vscode.workspace.workspaceFolders[0].uri, ant it looks like this: `/c:/Users/MyName/code/myproject`.

Could that be an issue? I do use the proper `.with` call for setting the scheme.

**Comment by Arkadiy-bb** [comment]
One of the things I see is that vscode.Uri.joinPath does not maintain fsPath value.

**Comment by Arkadiy-bb** [comment]
I rather think that the duplication only happens when `editor.formatOnSave` is enabled . @bpasero , could you please try it with a formatter?

**Comment by bpasero** [comment]
I had that enabled when trying:

![recording](https://user-images.githubusercontent.com/900690/128543729-bd9f8fd9-5a28-4f20-b92f-52d56ef9f688.gif)

**Comment by Arkadiy-bb** [comment]
But is there a formatter for .txt? In any case, I do not see the change in file in your recording. Could you try doing it in a way that changes the file's contents as the result of formatting?

**Comment by bpasero** [comment]
I think that would be the responsibility of the author of the issue to give exact steps for me to reproduce?

**Comment by Arkadiy-bb** [comment]
I am sorry it's so hard...

The issue seems to happen at the conflation of custom extensions that create files (a relatively rare case) and possibly language-specific formatters (not quite common either).

I am not sure what formatters you have available in your environment. Maybe the JavaScript one? I am not very good at JavaScript, but if you create a `.js` file rather than `.txt`,  then paste a poorly-formatted JS code in there, it may trigger the formatting. If you happen to have `clang-format`, I can give more exact instructions.
