### ISSUE TITLE
Debugging hangs

### ISSUE THREAD

**Issue by amarendrakothuru** [microsoft/vscode#129096]
Issue Type: <b>Bug</b>

Debugging/Execution from Launch.json hangs after few minutes. Sometimes we can't able to see Debug console logs as well. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (16.26GB free)|
|Process Argv|C:\\ATHENA_Automation_1.0\\athena_markup-api-auto-framework --crash-reporter-id dd7d4324-da16-4f64-a9e8-b5b5e9116b09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberquick|Abh|2.2.1
project-manager|ale|12.3.0
cucumberautocomplete|ale|2.15.1
gitignore|cod|0.7.0
git-extension-pack|don|0.1.3
githistory|don|0.6.17
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
vscode-pull-request-github|Git|0.28.0
vscode-github|Kni|0.30.6
start-git-bash|McC|1.2.1
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1050252941
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
js-debug-nightly|ms-|2021.7.2017
powershell|ms-|2021.6.2
debugger-for-chrome|msj|4.12.12
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306cf:30340756
bridge0708:30335490

```

</details>

**Comment by weinand** [comment]
@amarendrakothuru what debugger are you using?

**Comment by amarendrakothuru** [comment]
I am using Javascript debugger (Nightly) extension for Typescript
