### ISSUE TITLE
Details of extension dependencies should show up in details or contributions tab

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12901]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Publishing an extension with extension dependencies does not show the dependencies anywhere, meaning an "empty" extension with 100 dependencies could exist and radically change the environment without warning the user.

**Comment by sandy081** [comment]
Duplicates #12756
