### ISSUE TITLE
Provide a way to ask user an arbitratry modal dialog before closing window.

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#129082]
Upon closing vscode, extension developers like myself are sometimes in need of asking the user if its ok to lose some state/data, (or some other simple question).

For example, my extension may provide a service or remote feature, or bridge to something outside of vscode, that may be in the process of doing something (may be as simple as the concept of being 'dirty') where it would be greatly useful to ask the user a simple question before closing.

(such as  "save dirty state? yes/no" of whatever the extension is providing a view of..., or "cancel operation or continue after closing" for whatever remote operation the extension had started, in essence,  modal dialogs with those kind of messages, etc.)

Before raising this issue I've tried hooking on 'deactivate' but it does not seem to provide access to vscode's GUI modals, as I've tried this simple 'ok' before quitting to no avail.:

```
export function deactivate(): Promise<any> {
  return vscode.window.showInformationMessage('Deactivating Leo - Unsaved Leo Files will be lost!', { modal: true }, 'ok')
          .then((p_result) => {
              console.log('DEACTIVATE 2', p_result);
              return true;
          }) as Promise<any>;
}
```

Lastly - if deactivate can expect a promise as a return value, I expected vscode would at least wait for the promise to resolve ... or limit it with a 10 second timer to limit extensions in this closing process somewhat. (documentation is short about this)

Anyways Thanks for considering and Thanks for this great product!!

**Comment by bpasero** [comment]
cc @jrieken
