### ISSUE TITLE
Handle 304 from setting sync server in GET manifest call

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129008]
Currently 304s in GET manifest are treated as errors here because of `[]` instead of `[304]`:

https://github.com/Microsoft/vscode/blob/c4fa9ff85be86d821de2a496c1a9a3a83ea57e09/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts#L331-L331

304 does appear to work via Chromium/Express's caching mechanism which will end up returning an empty body in this case when there are no changes. So after the above call, when a `304` is returned, we should assume our existing manifest is the latest and just update the date requested (if we need to do that).

**Comment by sandy081** [comment]
Yeah, client handles 304 only for settings sync resources by passing `If-None-Match` header. I am not sending `If-None-Match` header for manifest. So I would not expect server to return 304. 

When is the server sending 304?

**Comment by sandy081** [comment]
Client handles 304 for manifest requests. Auto sync task makes use of it by remembering the manifest (in  memory).

**Comment by sandy081** [comment]
@Tyriar Just to confirm, server does not return 304 if `If-None-Match` is not sent right, just similar to other resources?

**Comment by Tyriar** [comment]
The server **may** return 304 when `If-None-Match` is **not** present, if the response has the same body.

**Comment by sandy081** [comment]
It is not clear to me when you said response has the same body. Can you please explain with an example?

**Comment by Tyriar** [comment]
@sandy081 if the server evaluates it's about to send the same body for the same request (based on the etag Chromium sets), it will not send any body and a 304 to the client.

**Comment by lramos15** [comment]
@Tyriar and @sandy081 Not really sure how to verify this

**Comment by Tyriar** [comment]
You don't need to verify this one
