### ISSUE TITLE
Typescript died unexpectedly

### ISSUE THREAD

**Issue by rohanatlarge** [microsoft/vscode#129026]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Was editing files. Nothing out of the ordinary.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (10.97GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/usr/src/dojo/web/admin --remote=wsl+Ubuntu-20.04 --crash-reporter-id 5c622570-0879-4027-b07e-abcbe09199c7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.96GB (15.85GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.96GB (15.85GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
auto-rename-tag|for|0.1.7
remote-containers|ms-|0.187.0
remote-wsl|ms-|0.56.5
highlight-matching-tag|vin|0.10.1
JavaScriptSnippets|xab|1.8.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
prettier-vscode|esb|8.0.1
vscode-typescript-next|ms-|4.4.20210715

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by rohanatlarge** [comment]
This bug report was created by your issue reporting template. If it needs more info, maybe the reporting template needs to get fixed. It is your code that generated the bug report! Please be specific of what info is missing, and I can tack it on.

**Comment by mjbvz** [comment]
See the issue reporting guidelines. This ins't actionable with without steps to reproduce or more context about what causes this issue
