### ISSUE TITLE
Creating new folder is not focusing vscode window

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/vscode#129038]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: macOS 11.4 

Steps to Reproduce:

1. Open vscode
2. Focus an other application
3. in the Explorer area of vscode do right click and click "New Folder"

-> you wont be able to enter the name of the folder immediately because vscode is not focused after this action

**Comment by isidorn** [comment]
Dup of opened issue "Context menu does not focus electron app"

**Comment by tbrodbeck** [comment]
👍  Can you maybe provide a link to the other issue? I cannot find it

**Comment by SmartHypercube** [comment]
@isidorn I think it's a little strange to close an issue as dup without mentioning the original issue's number. I cannot find any issue named "Context menu does not focus electron app". This is unhelpful and will leave future people searching for the same problem a big mystery.

Could you please reopen this issue or give the original issue's number?
