### ISSUE TITLE
Global search unicode double \\

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode#129098]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic snap

Steps to Reproduce:

1. globally search (ctrl + shift + F) for unicode
2. a second backslash is read, although it is not present, ss shown in the attached image

left column: the global search, right column the actual code (.ipynb)

![image](https://user-images.githubusercontent.com/11757284/126462889-eb753bf5-30f0-499f-a3c8-7c53cd97a5a9.png)

**Comment by IllusionMH** [comment]
Global search operates on file content as it is on disk (unless there is open editor for this file).
`.ipynb` files are stored as JSON documents and all strings (including lines of code) should be properly escaped, therefore `\` is escaped as `\\` (and also you can see `\n` in search result at the end of the string, and I expect that `"` couple of lines above will be escapes as `\"`).
Therefore when you are performing global search you should take JSON escapes into account at this moment.

**Comment by roblourens** [comment]
Yes, you can only search the raw underlying content right now which will not always be what you expect. Will try to improve this some day but it's difficult. Tracking notebook search in https://github.com/microsoft/vscode/issues/123230
