### ISSUE TITLE
Unsaved files opened when updating imports

### ISSUE THREAD

**Issue by tsongas** [microsoft/vscode#129078]
When I rename or move a file, VS Code asks if I'd like to update the imports for that file in my code, which is fine except...VS Code then opens each file with the unsaved change in a new tab, which I then have to manually close after saving...this could be HUNDREDS of files! I've been using code editors since Microsoft FrontPage and this is quite possibly the single most annoying "feature" I've ever encountered. Is there a setting that can fix this or ?

**Comment by MaledongGit** [comment]
@tsongas : You mean you changed and saved some files out of VSC, and you find thery are reported as "Changed" but not saved in VSC? Am I right?

**Comment by tsongas** [comment]
@MaledongGit no I for example drag a file with an export from one folder to another, then VS Code asks me if I wan to update the imports for that file. If there are say 20 files that import the one I moved, each one gets opened with the unsaved change.

**Comment by mjbvz** [comment]
I believe this falls under #47573. If the files were saved automatically, we wouldn't need to open all of them
