### ISSUE TITLE
Build task in terminal froze the UI

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129080]
Issue Type: <b>Bug</b>

* Open VS Code repo
* Ctrl+Shift+B
* Have it run for half a day
* Close the terminals
* Ctrl+Shift+B again
* The UI is frozen for minutes

From the perf log, it tries to parse every line to find errors it seems

![image](https://user-images.githubusercontent.com/876920/126419589-f8a54966-6a5d-4bbd-9a9d-d3a42c313689.png)

VS Code version: Code - Insiders 1.59.0-insider (d624242076d166bb8ce8b314e8d44b8af6100a3d, 2021-07-19T05:13:36.046Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.45GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
I guess it's because I have `terminal.integrated.scrollback: 100000` ...

**Comment by alexr00** [comment]
I can add some kind of debouncing in tasks. Based on my testing of how fast the terminal events come in once the task starts there will be a minimum of 1.5 seconds delay before the task "settles" and you get errors/success/failure. This delay will apply to _all_ tasks. I'll also only keep the last 200-300 lines from the terminal. 

@Tyriar is there a way I can get the number of lines a terminal is going to have before `onLineData` is fired? I'd like to avoid adding this 1.5 second delay to all tasks.

**Comment by Tyriar** [comment]
> Ctrl+Shift+B again

So this will reconnect to the session and replay all data, it probably isn't actually tied to your scrollback as I think the replay does all output received by watchd over its lifetime.

> is there a way I can get the number of lines a terminal is going to have before onLineData is fired? I'd like to avoid adding this 1.5 second delay to all tasks.

`onLineData` is fired as soon as a line feed or cursor move is hit. Debouncing on your side is the right thing imo, but these events are fired so quickly, even when just changing files, that you should be able to use a much smaller delay of something like 100ms?

> Add line data debouncing for background tasks 

Shouldn't this apply to all tasks, not just background ones?

**Comment by Tyriar** [comment]
> I'll also only keep the last 200-300 lines from the terminal.

@alexr00 you might be able to use a ring buffer to reduce the amount of garbage collection here.

Perhaps a better solution is to lean more on the terminal's impl and instead of constructing the string on each `onLineData`, create an xterm.js marker object for the last evaluated line and only when the debounced method fires would we would generate the line data.

**Comment by alexr00** [comment]
Background tasks are likely to be longer running and so have more lines. I can apply the debouncing to non-background problem matchers too, but it will add a forced delay in to non-background tasks with less chance of benefit. 

For some reason I found the first ~5 `onLineData`s to be pretty slow (even more than 1000 ms). To get my debounce working properly I needed to go up to 1.5 seconds.

**Comment by Tyriar** [comment]
Oh ok, a background task is essentially a watch task, that makes sense

**Comment by Tyriar** [comment]
Accidental close?

**Comment by alexr00** [comment]
I pushed my debounce change and I didn't see https://github.com/microsoft/vscode/issues/129080#issuecomment-884159045.

Terminal API for this would be ideal!

**Comment by Tyriar** [comment]
@alexr00 created https://github.com/microsoft/vscode/tree/tyriar/129080 with some example APIs

To use it I'd track the last processed line with a marker:

```ts
const lastProcessed = instance.registerMarker(0);
```

Then listen to `onLineData` as before but don't use the data there, instead trigger the debounced function

```ts
instance.onLineData(() => debounceMe())
```

Then in that call use `lastProcessed` to get the lines, I don't think currently the buffer length or cursor position is exposed, so create another marker for now and we can figure something better out after.

```ts
function debounceMe() {
  // The -1 here may leave out lines if the line data was triggered by a cursor move,
  // can figure this out after the idea is proven
  const currentLine = instance.registerMarker(-1);
  const startIndex = lastProcessed.line + 1;
  const lines = instance.translateLinesToText(startIndex, currentLine.line - startIndex);
  lastProcessed = currentLine;
}
```

I'd also do this behind a flag initially in case there ends up being problems with dropped lines or something.

**Comment by Tyriar** [comment]
Let me know if you need more help here

**Comment by alexr00** [comment]
Reverting my change in favor of a better change using the terminal API in August.

**Comment by alexr00** [comment]
@Tyriar I tried out the terminal API, and it mostly works. There are a few issues, which I've commented on in my commit: https://github.com/Microsoft/vscode/commit/f1e0249ad4f6347dd4fad852738ee64634866808

**Comment by alexr00** [comment]
Looks like this isn't going to make it for August.

**Comment by meganrogge** [comment]
@rebornix have you seen this recently?

**Comment by meganrogge** [comment]
Ok pls reopen this if you see it again
