### ISSUE TITLE
Installing an extension with dependencies that are already installed still displays install dependencies dialog

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12904]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Related to #12901

I tried installing an extension with a dependency that I already had installed, it asked me if I wanted to install the extension's dependencies and it did not do anything as far as I'm aware as I already had the extension installed.

**Comment by Tyriar** [comment]
This may have been related to using the invalid extension ID in #12907

**Comment by roblourens** [comment]
I've been specifically testing this and didn't see it in OSX

**Comment by Tyriar** [comment]
#12907 is likely the root cause.

**Comment by sandy081** [comment]
Yes, related to #12907.
