### ISSUE TITLE
Allow "command" variables in user-defined snippets

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#129003]
In some places (for example `launch.json`) we can use variables like `${command:foo}` to execute a command and substitute the variable with its return value.

I had [a request] that would require being able to do something like this for user snippets. For example the user may create a snippet that populates a bunch of boiler-plate methods in a class, but want to substitute the classes name inside that code.

For example:

```js
"fromJson": {
	"prefix": "fromJson",
	"body": [
		"factory ${command:dart.getCurrentClassName}.fromJson(Map<String, dynamic> json) {",
		"return _\$\$${command:dart.getCurrentClassName}\$FromJson(json)",
		"}"
	],
	"description": "Creates a fromJson factory constructor"
}
```

If the user invoked this in the following code:

```dart
class Foo {
  fromJson // invoke here
}
```

They would like to see:

```dart
class Foo {
  factory Foo.fromJson(Map<String, dynamic> json) {
    return _$$Foo$FromJson(json); // these $'s are expected, they are calls to generated code
  }
}
```

Of course, the `dart.getCurrentClassName` command would need to be supplied by an extension for this to work.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"feature-request"+label%3A"snippets"

**Comment by DanTup** [comment]
Ah - is it https://github.com/microsoft/vscode/issues/10561 you're referring to? That seems to talk about returning snippets from the provider (in which case we could do the substitutions ourselves). This request is specifically about letting users do this from their own user-defined snippets.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/10561#issuecomment-241765127

**Comment by DanTup** [comment]
Ah cool, I wasn't sure if that included user-defined snippets. Perfect, thank you!
