### ISSUE TITLE
Error when launching VSCode from command line

### ISSUE THREAD

**Issue by Craftzman7** [microsoft/vscode#129062]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 Version 21H1 Build 19043.1110

Steps to Reproduce:

1. Open Command prompt or Powershell. (I was unable to reproduce inside the Windows Terminal app)
2. Launch Visual Studio Code by typing `code`
3. You will get this error when launching `registration_protocol_win.cc(102)] CreateFile: The system cannot find the file specified`

![88fmiPbMv1aMTL5Ny0KqGCfszLYlXn2ymoHU6QqF0silDtgHuZAY4FnekWorQtU1kKW3c](https://user-images.githubusercontent.com/70068692/126367916-7f26353c-d345-4291-947c-2cfedd0c1d1b.gif)

**Comment by Craftzman7** [comment]
Fixed by just installing again. (Don't worry it keeps your extensions)

**Comment by sbatten** [comment]
re-opened as @tylertownsend is hitting this issue with latest insiders.
