### ISSUE TITLE
npm not found in zsh task terminals randomly

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#129086]
Version: 1.59.0-insider (Universal)
Commit: b805d2e94937976bb17d0439f57fcd3a9d423c31
Date: 2021-07-20T05:12:13.059Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:
1. Have the [npm extension](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script) installed.
2. Open up a random project with scripts in a `package.json`. I opened https://github.com/tanhakabir/rest-book
3. Try to run script from `package.json` and see error.
4. **Note** This doesn't happen all the time just happens in random sessions.

![recording (50)](https://user-images.githubusercontent.com/12758612/126435166-2454ae4c-8230-49b5-8662-99c00b7b938e.gif)

**Comment by Tyriar** [comment]
@alexr00 I think this is to do with login shell vs non-login shell? I seem to get these types of issues pretty often, can we get a FAQ that explains how the task constructs the environment on the website that we can point to it?

@tanhakabir it's likely an issue with npm getting set up in one of .zshrc/.zprofile which isn't being run.

**Comment by alexr00** [comment]
Usually issues like this are indeed login related. Especially if you use nvm, the setup for which often requires a login shell. 

An FAQ is a great idea. I'll make one.
