### ISSUE TITLE
Semi transparent upper border border - is this by intention?

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#129045]
The most recent VS Code version displays a semi transparent upper border:

![Upper border](https://user-images.githubusercontent.com/9283914/126316819-8a51c944-74c3-4a56-85cc-05ee4efadc35.png)

I feel it quite irritating when I open VS Code. It raises a feeling in me of a brittle, unstable version, rendering outside its intended rendering buffer memory.

Is this upper semitransparent border by intention?

- VS Code/OS Version:
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Datum: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
Betriebssystem: Windows_NT x64 10.0.19043
```

**Comment by sbatten** [comment]
@SetTrend can you confirm if this is still happening?

@deepak1556 electron related perhaps?

**Comment by deepak1556** [comment]
@SetTrend can you share your display arrangement and configuration.

**Comment by SetTrend** [comment]
@sbatten:

Yes, I can confirm it's still happening:

![VS Code app window - 1](https://user-images.githubusercontent.com/9283914/128928044-e2a8b8ae-19cf-4833-ba64-1064264bef3c.png)

![VS Code app window - 2](https://user-images.githubusercontent.com/9283914/128928342-63d06c1d-89f7-437d-84cd-f4514a6e0111.png)

@deepak1556:

I'm running Windows 10x64, 1920*1200 pixels, single screen.

Here's a (truncated) DxDiag log file from my machine:
[DxDiag.txt](https://github.com/microsoft/vscode/files/6964290/DxDiag.txt)

**Comment by deepak1556** [comment]
This is addressed in recent versions, unable to repro with latest stable `1.74`
