### ISSUE TITLE
Updating an extension will install new extensionDependencies without prompt

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12917]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Steps to Reproduce:

1. Publish an extension with dependency `foo`
2. Install the extension, prompt
3. Publish new version of the extension with additional dependency `bar`
4. Install the extension, no prompt

**Comment by sandy081** [comment]
I am not showing the prompt always. Prompt is shown only during installing. If user confirms, manual / auto update do not show prompt. IMO it makes sense coz, showing again is redundant to the user as he/she already knows it installs dependencies.

**Comment by sandy081** [comment]
Not showing the prompt during manual update might not be fair if the extension to update is installed as a dependency of an another extension. In which case, user is not aware. So to be simple and good - Show prompt when user installs or updates and do not show prompt for auto updates.

**Comment by aeschli** [comment]
I don't see a prompt when updating an extension that has more dependencies than before.
Version 1.7.0-insider
Commit cb0a9f0aacdc23e1e543d3057569218d8f944186
Date 2016-10-28T06:19:13.277Z

@sandy081 What's the expected behaviour?

**Comment by sandy081** [comment]
@aeschli Updating an extension manually should show the prompt if there are any new dependencies to be installed
