### ISSUE TITLE
Support intellisense for args in workbench.action.terminal.newWithProfile command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129140]
To help with https://github.com/microsoft/vscode/issues/126738, the command should profile enum values in the schema so it provides valid options and shows warning when it won't work.

**Comment by Tyriar** [comment]
To verify make sure all profiles work, including extension contributed profiles

**Comment by rchiodo** [comment]
Verified except not sure how to test with other extensions.
