### ISSUE TITLE
Workspace or Folder or both?

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12916]
- VSCode Version: 1.6 insiders
- OS Version: any

The Go menu contains `Go to Symbol in Workspace`.  With #12911 the command palette would contain: 
- Go to Symbol in Workspace
- Configure Workspace Recommended Extension
- Show Workspace Recommended Extension
- Open Workspace Settings

We also experimented with "Configure Workspace". However, anywhere else we use "folder", i.e. we don't really have an explicit concept of workspace.

**Comment by kieferrm** [comment]
@egamma  I missing history here.

**Comment by bpasero** [comment]
I think this is fine but @egamma can tell otherwise.

**Comment by egamma** [comment]
We are using workspace in several other locations
![image](https://cloud.githubusercontent.com/assets/172399/18959521/c905e65c-8666-11e6-9793-4a903568312d.png)

Or inside the launch config "${workspaceRoot}".

So I think we are fine. My issue with Folder is it is not specific enough, it would be 'Root Folder'.

**Comment by egamma** [comment]
This discussion has closed by now, closing issue.
