### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by BradenKing77** [microsoft/vscode#129138]
READ ME

Issue Type: <b>Bug</b>

I have coded a few programs on VS Code and love the IDE. However, now when I make a new file, it just sits and loads and loads and loads and loads and never allows me to actually begin typing or starting the program or starting to code. I cant even type print('anything') except for in the terminal, which doesnt help because you dont write a program fully in the terminal. Please help me

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (3.78GB free)|
|Process Argv|--crash-reporter-id 5d7ee5dd-1e02-4c8c-8702-1e3c163829a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/128977

**Comment by deepak1556** [comment]
Hmm based on your description, it might be a different issue. Can you attach a screen recording to demonstrate the issue.

/gifPlease
