### ISSUE TITLE
Non mi permette di scrivere il codice

### ISSUE THREAD

**Issue by aritowers** [microsoft/vscode#129132]
Il cursone è diventato largo e di colore nero (tipo una scriscia nera verticale), non mi permette di scrivere il codice, come si risolve questo problema?
grazie.

**Comment by lszomoru** [comment]
Google translation of the description:
> The cursor has become large and black (like a vertical black stripe), it doesn't allow me to write the code, how do you solve this problem?
thank you.

**Comment by CodeCrazy-ywt** [comment]
@aritowers 
(English)Please provide a screenshot of this issue.
(Italian)Fornisci uno screenshot di questo problema.
