### ISSUE TITLE
Can't connect to Extensions Marketplace

### ISSUE THREAD

**Issue by vectorx5000** [microsoft/vscode#129147]
Issue Type: <b>Bug</b>

Installed vscode via pacman on KDE Manjaro, then attempt to open the extensions panel. I have looked at all the relevant threads that I could find and none of the solutions fixed my problem. I have my dns set correctly (1.1.1.1, also tried 8.8.8.8). I am not using a proxy. I have tried launching using --log-net-log=netlog.json, and have uploaded that on pastebin [here](https://pastebin.com/Dav2Pj09). This is only the first part of the log since it was so long and was causing an issue with pastebin's automatic moderation.

 It's possible there's something obvious I'm missing but I'm at a loss for what else to try. This is a screenshot of the error that shows up in the developer options. I can screenshot the full errors if it's helpful.
![Screenshot_20210722_000427](https://user-images.githubusercontent.com/18503010/126589243-f3e3ebd3-ae9e-40c8-97d5-bc4b0c5c7bd2.png)

The "Logs (Shared)" output is not of any use, just saying that it's cleaning up logs and language packs etc.

VS Code version: Code - OSS 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-12T23:51:36.303Z)
OS version: Linux x64 5.10.49-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 2361)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.53GB (10.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by joaomoreno** [comment]
We do not support open-vsx
