### ISSUE TITLE
Inlay hints shift around when typing

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#129134]
Issue Type: <b>Bug</b>

1. Set `"typescript.inlayHints.parameterNames.enabled": "all"`
1. Open this file https://github.com/microsoft/vscode/blob/23d99b3055a95aeb586406905b6bdcbc31d39a53/extensions/typescript-language-features/src/typescriptServiceClient.ts#L605
2. Start typing inside the string `'The TypeScript language ...'`

**Bug**
The inlay hints shift around as you type:

![recording](https://user-images.githubusercontent.com/12821956/126565761-997eb03f-6825-48be-963d-750ce46f5f83.gif)

latex-workshop|Jam|8.19.2
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.0
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.15.0
vscode-language-pack-de|MS-|1.59.0
python|ms-|2021.8.1035685139-dev
vscode-pylance|ms-|2021.7.5-pre.1
jupyter|ms-|2021.8.1051926518
remote-containers|ms-|0.188.3
remote-ssh-edit-nightly|ms-|2021.7.29700
remote-ssh-nightly|ms-|2021.7.29701
azure-account|ms-|0.9.8
hexeditor|ms-|1.7.1
js-debug-nightly|ms-|2021.7.2017
live-server|ms-|0.2.4
vscode-github-issue-notebooks|ms-|0.0.102
vscode-typescript-next|ms-|4.4.20210715
vsliveshare|ms-|1.0.4583
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
java|red|0.80.0
code-spell-checker|str|1.10.2
rest-book|tan|3.2.0
ayu|tea|0.20.1
luna-paint|Tyr|0.7.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0

(2 theme extensions excluded)

</details>

**Comment by hediet** [comment]
Semantic synaxhighlighting is also off...
Is this a TypeScript bug?

**Comment by mjbvz** [comment]
Pushed potential fix on the TS side related to which offsets we send to the server. Seems to fix the problem but let me know if you see it again
