### ISSUE TITLE
[UI] Status bar color will not change when I start debugging from touchbar

### ISSUE THREAD

**Issue by buster95** [microsoft/vscode#129126]
When I start debugging from touch bar, status bar color not change, if I start debugging from ui or from shortcut(F5) status bar color will change
[CHECK THIS VIDEO](https://www.youtube.com/watch?v=RhoGO3oVckU)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2 (Universal)
- OS Version: MacOS BigSur 11.4
Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

Steps to Reproduce:

1. Start debugging from touchbar

**Comment by isidorn** [comment]
That is because you have been touching the Run button, not the Debug button. When we just Run (start without debugging) we do not hit breakpoints and we do not change the status bar color

**Comment by buster95** [comment]
- Is there a possibility to modify touchbar buttons?

**Comment by isidorn** [comment]
Not at the moment. We might change this in the future.
