### ISSUE TITLE
Open editor in default editor group

### ISSUE THREAD

**Issue by raulvaldoleiros** [microsoft/vscode#129174]
I would like to define a default editor group, this way I could have multiple editor groups in visual studio code and when I open a new file it will always open in the default one. Scenario:

- Developing some java code
- Executing the unit tests will open the test report in new editor group
- When I open a new java file it opens in the editor group of the unit test report and I want to be opened in the other one where I have the code.

**Comment by gjsjohnmurray** [comment]
/duplicate - see https://github.com/microsoft/vscode/issues/124709#issuecomment-867413948
