### ISSUE TITLE
Updating an extension should present the version of the update

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12912]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Updating from v1 to v2 could cause issues for users.

![image](https://cloud.githubusercontent.com/assets/2193314/18925290/47cc5534-8568-11e6-8970-4c6036526254.png)

**Comment by joaomoreno** [comment]
#9974
