### ISSUE TITLE
Search Editor still has 10000 line limit when search.maxResults is set to a value larger than 10000

### ISSUE THREAD

**Issue by alexzhuaz** [microsoft/vscode#129153]
Issue Type: <b>Bug</b>

1. Set search.maxResults to a value larger than 10000
2. Search some text in file which may have results more than 10000
3. Click "Open in editor" in search panel
4. The search editor shows 
"10000 results - 1 file
The result set only contains a subset of all matches. Be more specific in your search to narrow down the results." and only 10000 results shown in search editor

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: Yes
Remote OS version: Linux x64 4.15.0-136-generic

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30340756
bridge0708:30335490

```

</details>

**Comment by JacksonKearl** [comment]
Accidentally already created a walkthrough of how to resolve this in #128661 so I'll post it here:


To reproduce, set the max results setting to some larger value, and run a search in the search editor which has more results than the value:
![image](https://user-images.githubusercontent.com/8586769/125858864-efe79c35-e97e-4637-9fe8-ab9d4c90e740.png)
![image](https://user-images.githubusercontent.com/8586769/125858936-e2e2084e-8df1-434d-9071-cf7805c32033.png)


Access search editor with: 
![image](https://user-images.githubusercontent.com/8586769/125858957-b8b6b731-67be-4c92-84d0-d9dc70f802df.png)


You can start by changing the limit passed here to read from the `configurationService` https://github.com/microsoft/vscode/blob/d7712edeaa8e0321ff738329b3a8a14efa292bc3/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L490

Then, you should add a way for the search to be re run with no limit. See what happens in the search from the sidebar, whose code is here: https://github.com/microsoft/vscode/blob/1fc68f3cf274141942b424894645a4f7096ec1f1/src/vs/workbench/contrib/search/browser/searchView.ts#L0-L1 for how to make that change.

**Comment by vlwkaos** [comment]
Hello, @JacksonKearl , I would like to work on this issue. 

As-is: Search Editor has maxResults fixed to 10000
To-Be: Should use a maxResult value from configureationService and with no limit if value is null

Am I understading the issue correctly?

**Comment by JacksonKearl** [comment]
@vlwkaos yes that is correct. Thanks!

**Comment by Nirajn2311** [comment]
Hey @vlwkaos, have you started working on this? If not, I'm interested on picking it up.

**Comment by vlwkaos** [comment]
> Hey @vlwkaos, have you started working on this? If not, I'm interested on picking it up.

@Nirajn2311 I've been busy so I have not done much, so you can pick it up. I realized it requires more time than I previously expected. As far as I see, making search editor to rerun the search results with polling like the search view requires some work...

**Comment by JacksonKearl** [comment]
> As far as I see, making search editor to rerun the search results with polling like the search view requires some work...

It is by design that the search editor does not stream results, this causes undesirable behavior in an editor context when you may be in the process of manipulating the results. For this ticket simply respecting the `search.maxResults` setting is sufficient.

**Comment by vlwkaos** [comment]
> > As far as I see, making search editor to rerun the search results with polling like the search view requires some work...
> 
> It is by design that the search editor does not stream results, this causes undesirable behavior in an editor context when you may be in the process of manipulating the results. For this ticket simply respecting the `search.maxResults` setting is sufficient.

In that case, I have just done that, however, I still need to resolve what to do when the maxResult is null, because the editor will hang and crash. What would you suggest I do?

**Comment by Nirajn2311** [comment]
It's cool, I'll pick up another issue.
