### ISSUE TITLE
Double-clicking the When expression in the keyboard shortcut editor opens the keybinding input widget

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode#129175]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open the keyboard shortcuts editor
2. Double-click the When expression
Expected result: The when expression becomes editable
Actual result: The keybinding input widget appears, and the user has to close the widget, right-click the keybinding, and select "Change When Expression"

**Comment by AnrDaemon** [comment]
Double-clicking inside an active editor(field) should select the word, not open some unexpected window.
