### ISSUE TITLE
Extension detail pane should indicate the version of the readme, particularly when an update is available

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12913]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
#12647

In the following image the current extension version is v0.0.3 and the latest is v0.0.5. Until testing #12647 I always assumed that the readme was for the latest version of the extension, not the current version.

![image](https://cloud.githubusercontent.com/assets/2193314/18925349/827ff168-8568-11e6-82a5-261f663c4c0f.png)

**Comment by sandy081** [comment]
Extension editor always show details of latest extension. So, I do not see the necessity of showing the version
