### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by SorataBaka** [microsoft/vscode#129137]
Issue Type: <b>Bug</b>

Opening a new windows or changing file directories inside visual studio code returns a blank page with no text whatsoever after editing code for more than 5 or 10 minutes. 

needed to restart VSCode in order for it to work again

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.89GB (6.77GB free)|
|Process Argv|--crash-reporter-id 8e024c1c-5602-40c4-84ef-91b343c4704b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
beautify|Hoo|1.5.0
discord-vscode|icr|5.7.0
fluent-icons|mig|0.0.12
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1046824664
cpptools|ms-|1.5.1
live-server|ms-|0.2.4
vsliveshare|ms-|1.0.4583
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
tabnine-vscode|Tab|3.4.17
html-preview-vscode|tht|0.2.5
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30340755
bridge0708:30335490

```

</details>

**Comment by frunjik** [comment]
This happens for me without waiting.
Opening a new window opens a (total blank window - no UI)

![image](https://user-images.githubusercontent.com/8170229/126594012-28ba90f2-1041-4018-a967-dd3938b66378.png)

**Comment by Duncank** [comment]
Same here; it happens when opening a new window from the Windows task bar, from within the File menu in VSCode and by switching directories.  

If I open a workspace file or rightclick -> open in code from the file explorer, a new window opens correctly.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/128977

**Comment by deepak1556** [comment]
Can anyone confirm if you tried to execute Open New External Terminal (workbench.action.terminal.openNativeConsole) action (Ctrl+Shift+C) before the issue started to happen ?

**Comment by SorataBaka** [comment]
> Can anyone confirm if you tried to execute Open New External Terminal (workbench.action.terminal.openNativeConsole) action (Ctrl+Shift+C) before the issue started to happen ?

After testing it does seem like the bug only happens after I open an external terminal from inside VSCode by doing Ctrl+Shift+C

**Comment by SorataBaka** [comment]
@deepak1556 after testing it does indeed only happen once i hit ctrl shift n or open an external console.
