### ISSUE TITLE
Support quick fix for override keyword "Add member to base class" in typescript

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#129130]
Add override quick fix to add member to base class

----------------------------------------------------------------

Sorry about missing context.
In typescript language add quick fix: "Add member to base class" for override method missing in base class.

**Comment by LucaGabi** [comment]
Hi, sorry about missing context.
In typescript language add quick fix: "Add member to base class" for override method missing in base class.

**Comment by mjbvz** [comment]
Please share an example of what this would look like

**Comment by LucaGabi** [comment]
I'll try explain the request.

Inside a typescript class that extends a base class writing ```override someMethodName(){}``` will have a quick "Add member to base class" in case ```someMethodName``` is not defined in base class.

**Comment by mjbvz** [comment]
Thanks, opened https://github.com/microsoft/TypeScript/issues/45172 to track upstream
