### ISSUE TITLE
can't copy figures to clipboard in jupyter notebook

### ISSUE THREAD

**Issue by jheissb** [microsoft/vscode#129192]
Issue Type: <b>Bug</b>

in jupyter notebook, produce any plot, then select and try to copy to clipoard either by pressing ctrl-c or edit-copy.

It doesn't do anything and the clipboard remains empty. The only option is to save the figure to disk, which is not practical.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (20.76GB free)|
|Process Argv|--crash-reporter-id 2f12ecf8-3564-49b2-8351-e7b4544d8b03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
githistory|don|0.6.17
gitlens|eam|11.6.0
githd|hui|2.2.4
vscode-github|Kni|0.30.6
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.4
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306cf:30340756
bridge0708:30335490

```

</details>

**Comment by rebornix** [comment]
@jheissb do you mind sharing a screen recording of this particular issue? It can help us understand which notebook UI you are using and how it should work.
