### ISSUE TITLE
Error Installing Test-extension-pack-2 on Windows

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12919]
From #12647 

- VSCode Version: 1.6 Insiders
- OS Version: Win 10

##### Steps to Reproduce

1. Without any extensions installed, try to install `test-extension-pack-2`
2. Select "Yes" for installing dependencies 

##### Actual
I see this error message, and none of the extensions are installed

![image](https://cloud.githubusercontent.com/assets/12821956/18926241/e2bac6f4-856b-11e6-8d22-514164eb16d5.png)

This file does not exist on disk. There is a `C:\Users\matb.REDMOND\.vscode-insiders\extensions\designbright.theme-suicidesquad-0.1.0\.vscode` directory but it is empty.

If I manually install `designbright.theme-suicidesquad` before installing pack-2, the installation works.

**Comment by mjbvz** [comment]
In my testing, you can install `test-extension-pack-2` if you install `test-extension-pack-1` or `test-extension-pack-2` first.

**Comment by sandy081** [comment]
@mjbvz I am not able to reproduce it on windows 10.. I installed `test-extension-pack-2` without any issues when I do not have any extensions installed.

Can you let me know if there is any thing else you tried and I am missing.. Thanks

**Comment by mjbvz** [comment]
@sandy081 Ok, my machine may have just gotten into a weird state. I now hit this consistently, but I believe the sequence of actions I took before hitting this the first time was something like:

* Start with no installed extensions.
* Install pack-1 with "Yes"
* Install pack-2 with "Yes"
* Restart vscode
* Manually uninstall every individual extension and the packs too.
* Restart vscode
* Try to install pack-2
* Hit the error

Now it repos consistently for me though.  Are there any caches I need to clear to start testing this from a clean state? Just restarting things does not seem to be enough.

**Comment by sandy081** [comment]
Duplicates #14411
