### ISSUE TITLE
[Feature Request]Allow users to enable extensions with workspace file

### ISSUE THREAD

**Issue by NoahELE** [microsoft/vscode#129158]
The already-had extension 'Enable (Workspace)' option is kind of implicit and is hard to tell which extensions are workspace enabled and which are globally enabled. I want vscode to read from the `.code-workspace` file and enable the extensions which are written explicitly in the file.

It would also be better if I can install the extensions which will only be used in one folder in that folder. By that I mean if I want to install some extension locally just in the project folder like node modules.

**Comment by NoahELE** [comment]
@sandy081 Can you cite the issue number that this issue is a duplicate of? I tried but did not find it. Thank you!

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/40239
