### ISSUE TITLE
Misaligned traffic light buttons on macOS

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129117]
In Insiders the 3 traffic light buttons are no longer vertically centered in the window title:

<img width="219" alt="2021-07-21_17-31-03" src="https://user-images.githubusercontent.com/1898161/126516951-69d3a080-ec1c-4482-8134-afe0fab13e66.png">

In Stable they are:

<img width="184" alt="2021-07-21_17-31-32" src="https://user-images.githubusercontent.com/1898161/126516995-efe0fd30-1325-49c4-a953-99fd58b8c2f3.png">

**Comment by misolori** [comment]
We don't control any of this from the UI side, likely a Electron issue, assigning to @deepak1556

**Comment by weinand** [comment]
It just makes us look unpolished...

**Comment by deepak1556** [comment]
Following are positions obtained from accessibility inspector

Native:

NSWindow - x: 0 y: 25
Minimize button - x: 27 y: 31
Content Area - x:0 y: 53

Custom:

NSWindow - x:0 y:25
Minimize button - x: 27 y: 28

The titlebar height has not changed, so there is regression in placement of the traffic light buttons.

**Comment by deepak1556** [comment]
It first regressed in https://github.com/electron/electron/pull/27489
