### ISSUE TITLE
Untrust parent folder

### ISSUE THREAD

**Issue by Lyra2108** [microsoft/vscode#129173]
With workspace trust it is possible to trust all folders in the parent folder. I am missing the feature to "untrust" the parent folder e.g. I have sub folders in my Downloads folder and would not trust any of them.

![grafik](https://user-images.githubusercontent.com/2102141/126637580-6e2e57f3-7c32-47b2-a56a-41dcd2df2180.png)

I could not find a similar request sofar.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/126311
