### ISSUE TITLE
java compile error

### ISSUE THREAD

**Issue by solikego** [microsoft/vscode#129157]
I use java.security.jgss module in a java file,my env is jdk11,but complie error,it show me 'sun.security.krb5.KrbException is not accessible'

**Comment by lszomoru** [comment]
@solikego, this seems to be like it's an issue with the extension that provides the Java language capabilities. Could you please share the exact details of the Java extension that you have installed so that I can redirect this issue to the authors of the extension. Thank you!

**Comment by solikego** [comment]
> @solikego, this seems to be like it's an issue with the extension that provides the Java language capabilities. Could you please share the exact details of the Java extension that you have installed so that I can redirect this issue to the authors of the extension. Thank you!
I use Java Entension Pack,it contain Language Support for Java(TM) by Red Hat

,

**Comment by solikego** [comment]
I also add  '--add-exports=java.base/sun.security.jgss=ALL-UNNAMED' in pom.xml,it does not work

**Comment by lszomoru** [comment]
Thanks @solikego. Can you please file an issue in the extension's [repository](https://github.com/redhat-developer/vscode-java) as they are best suited to assist you. Thanks!
