### ISSUE TITLE
Suggest details should use link hover color

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#129193]
Similar to #121536, #121521, #125956, #126752

```js
"workbench.colorCustomizations": {
	"textLink.foreground": "#ffae00",
	"textLink.activeForeground": "#00a2ff",
}
```

Links on hover in suggest details are not using `textLink.activeForeground`.

<img width="500" src="https://user-images.githubusercontent.com/9638156/126701225-76dd4d39-9f36-489e-b9b7-aa708cee8a67.png">

**Comment by jeanp413** [comment]
Created a PR #130966 fixing this
