### ISSUE TITLE
Buffer is not defined: ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#129165]
```
Buffer is not defined: ReferenceError: Buffer is not defined
    at o.getMarkdownDocument
```

This is likely caused by the webpack adoption... I believe we now need to polyfill things explicitly. Adding @aeschli  for more help and fyi. Also for this [specific case](https://github.com/microsoft/vscode/blob/d5f4e119e058e1d01ec4f994f757703348c37db8/extensions/markdown-language-features/src/features/workspaceSymbolProvider.ts#L91) the global `TextEncoder/Decoder` could be used. That's available as a global in all contexts that we support

**Comment by mjbvz** [comment]
I wonder if it's worth creating separate tsconfigs for web that excludes the node types? Will take a look to see how complex this would be to add

**Comment by mjbvz** [comment]
134c34535162b621d4f010386ed8bd4b3cba925e try adding browser specific tsconfig. These errors won't show in the editor but should help catch references to `Buffer` or `process`

Let me know if you think this is worth adding for other extensions as well. I'll look into adopting it for the built-in extensions I maintain

**Comment by rzhao271** [comment]
@mjbvz can you provide some verification steps for this issue?

**Comment by mjbvz** [comment]
To verify:

- `yarn web`
- Open md file
- Trigger a workspace symbol search
