### ISSUE TITLE
Testing API feedback: Profiling

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#129198]
`go test` has flags that can be used to generate a CPU and/or memory usage profile. This can then be rendered as a graph, showing hotspots - that is, functions that use a lot of CPU time or a lot of memory. The [pprof readme](https://github.com/google/pprof/blob/master/doc/README.md) has an example [call graph](https://raw.githubusercontent.com/google/pprof/4bb14d4b1be14417e47d0bbaf2bd4e188eda647f/doc/images/callgraph.png) from a CPU profile.

This can be useful for analyzing tests, but when used with Go's benchmark support, it is particularly useful for identifying potential optimizations. I am working on migrating the features of my extension, the [Go Test Explorer](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-go-test-adapter), into the official Go extension, using the new testing API.

The idea is to provide some user action that runs a test or benchmark, captures a CPU/memory profile, and displays that profile in a tab (rendered as an SVG or equivalent). How should I do that? The options that occur to me are:

- Request the addition of `TestRunProfileKind.Profile`, `Performance`, or similar, with a corresponding UI.
- Request the addition of first-class API + UI support for CPU/memory profiles, as an extension to testing or as a new API (I don't see an existing issue).
- Create a non-default `TestRunProfile` for running profiles.
- Make the default profile configurable, "enable CPU profile [yes|no]", "enable memory profile [yes|no]"
- Add a command, "CPU/memory profile a test"
- Add a context-menu contribution to Go tests(`contributes.menus.testing/item/context`)
- Add a code lens

If I went with adding configuration to the default profile, I'd need some way to let the user know, "There are CPU/memory profiles available for <these> tests," so the user could open those up. If the user runs 100 tests at once, I wouldn't want to open up 100 profile tabs. Maybe I should request a way to attach additional results to a test run, beyond state and messages? Then, profiles would be added any time a test was run (if the user enabled profiling), and the user could show those profiles at a later time, perhaps as a context menu option on the test.

@connor4312, thoughts?

**Comment by connor4312** [comment]
> Create a non-default TestRunProfile for running profiles

I think this would be the recommended path. Once complete you could then `vscode.open` a custom editor or file with the test results, or just open a link.

> If the user runs 100 tests at once, I wouldn't want to open up 100 profile tabs. Maybe I should request a way to attach additional results to a test run, beyond state and messages?

One thing you can do today is contribute a [menu](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) to the `testing/item/context` menu that would open a profile for that item. If given in the `inline` group, it'll be shown inline. It's not super obvious, but it would work. Is there a better way you envision that this could happen?

**Comment by firelizzard18** [comment]
> Is there a better way you envision that this could happen?

I have some vague ideas, but nothing close to a real proposal. If other extension authors express a need for the ability to attach profiles or other test data, that might be enough information to come up with something concrete. On the API side, I was thinking of an additional method on `TestRun` to attach extra files or something. But I can't think of a way to cleanly expose that in the UI.

Is there a way to show a `testing/item/context` menu contribution conditionally on whether a particular test has profile data? The only relevant context key I know of is `testId` (which doesn't appear in "Developer: Inspect Context Keys"?), but I definitely don't want the test ID to be dependent on whether the test was run with profiling enabled.

**Comment by connor4312** [comment]
You could use the `setContext` command (e.g. `vscode.commands.executeCommand('setContext', 'profiledTests', testIdArray)` and then have a contribution like `testId in profiledTests`. If you have thousands of cases that could lead to performance concerns, but that could be a good start.

**Comment by firelizzard18** [comment]
Yeah that would work 🤦
