### ISSUE TITLE
Typescript - do not color colon :

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1291]
Colons should not be colored blue, they should remain black.

<img width="311" alt="screen shot 2015-12-14 at 16 32 34" src="https://cloud.githubusercontent.com/assets/1926584/11785103/58431db0-a280-11e5-9dee-6026f2ef1649.png">

**Comment by mohsen1** [comment]
Is this the right regex for this? https://github.com/Microsoft/vscode/blob/master/extensions/typescript/syntaxes/TypeScript.tmLanguage#L1067

**Comment by aeschli** [comment]
This is a problem of the grammar.
`:` get scope `token annotation body declaration function meta method object parameter type ts`

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#27
