### ISSUE TITLE
how to set breakpoint at jupyter notebook in vscode 1.58？

### ISSUE THREAD

**Issue by A-Pai** [microsoft/vscode#129136]
https://code.visualstudio.com/updates/v1_58#_jupyter-notebook-debugging
![image](https://user-images.githubusercontent.com/5112397/126572980-2e3ddd0a-4911-4e5b-9dcd-64f09141ac81.png)
I have  set "jupyter.experimental.debugging": true, installed version 6 of ipykernel：
![image](https://user-images.githubusercontent.com/5112397/126573116-8bb32625-d47a-4284-87e6-9b27e6b29599.png)
![image](https://user-images.githubusercontent.com/5112397/126573682-9441adad-4ae3-4183-9d08-439a0905e439.png)
but I can not set breakpoint at jupyter notebook in vscode，the version of my vscode is：
![image](https://user-images.githubusercontent.com/5112397/126573779-fc4b08fd-1aa4-4401-b3ff-f6309ed68f3e.png)

**Comment by roblourens** [comment]
When you click the "Debug" button, then the cell breakpoint margin will appear so you can click in the margin to set breakpoints

**Comment by A-Pai** [comment]
> the cell breakpoint margin

![image](https://user-images.githubusercontent.com/5112397/126576671-0d0b91d2-31d3-4b79-9ee4-6e2397aec633.png)

**Comment by DavidKutu** [comment]
@A-Pai you should be able to click to set breakpoints right there

**Comment by A-Pai** [comment]
> @A-Pai you should be able to click to set breakpoints right there where the rightmost arrow is pointing.
you should be able to click to set breakpoints right there where the rightmost arrow is pointing when you enter the debug mode.---
there is no any response when I click 

Did you click the Debug button on the notebook toolbar?
If so, do the debugging widgets appear? And does the status bar at the bottom turn orange?
--I click the left “debug”
--the debugging widgets does not  appear
-- the status bar is
![image](https://user-images.githubusercontent.com/5112397/126578187-1f93e493-4dd1-403b-a766-1c2891818cf5.png)

**Comment by A-Pai** [comment]
> @A-Pai you should be able to click to set breakpoints right there where the rightmost arrow is pointing when you enter the debug mode.
> 
> Did you click the `Debug` button on the notebook toolbar?
> If so, do the debugging widgets appear? And does the status bar at the bottom turn orange?
> 
> Your image looks like the debugging mode hasn't started.

would you please give me an exhaustive tutorial？

**Comment by roblourens** [comment]
You might check whether it works in VS Code Insiders. This is a very experimental feature

**Comment by A-Pai** [comment]
> You might check whether it works in VS Code Insiders. This is a very experimental feature

Do you mean it may not works in VS Code 1.58？I should try it out in VS Code Insiders？

**Comment by A-Pai** [comment]
The one I'm using right now is VS Code Insiders，and 
![image](https://user-images.githubusercontent.com/5112397/126720973-fbd59268-8fd6-453e-8448-a849d16ece33.png)
but
![image](https://user-images.githubusercontent.com/5112397/126720896-bfc608c8-4a01-4adb-97fc-3ece389a9589.png)

**Comment by roblourens** [comment]
That is the old webview notebook UI that doesn't support debugging. Is that an old version of vscode? Or maybe did you set a setting to disable native notebooks?

**Comment by A-Pai** [comment]
the version is : 
![image](https://user-images.githubusercontent.com/5112397/126726452-9d683719-d1c2-437c-8cbf-5ae3a9a8a76d.png)
I have set

![image](https://user-images.githubusercontent.com/5112397/126726622-9fb1032e-8380-47a1-8c44-54b247f420a8.png)

**Comment by roblourens** [comment]
This will only work in native notebooks so you can't set that setting

**Comment by A-Pai** [comment]
> This will only work in native notebooks so you can't set that setting

I have Corrected the Settings：
![image](https://user-images.githubusercontent.com/5112397/126848120-868194c9-66df-4fc6-a8a8-d0cf40fd0bf3.png)
but it  still didn't work

**Comment by roblourens** [comment]
So is the notebook opening in the new native notebook format now?

**Comment by A-Pai** [comment]
> So is the notebook opening in the new native notebook format now?

yes ，I can set breakpoint now just as below，but how to debug？

**Comment by roblourens** [comment]
Once you have clicked the debug button, and have a breakpoint set, then running the cell should hit the breakpoint

**Comment by A-Pai** [comment]
firstly I set the breakpoint，then click the “debug” button, it comes "set environment”  dialog box ，what should I do then？
![image](https://user-images.githubusercontent.com/5112397/126946045-417831ef-14ca-473d-ba41-b02a0c643d2e.png)

**Comment by roblourens** [comment]
You clicked the Debug button in the notebook toolbar, and _not_ the "Run and Debug" button in the sidebar, right?

**Comment by A-Pai** [comment]
I get it，thank you very much

**Comment by A-Pai** [comment]
Did you mean click this button？
![image](https://user-images.githubusercontent.com/5112397/127081693-b1c5b295-03a9-4e6a-ab92-8fa3b7ad10db.png)
but it will not hit the breakpoint：
![image](https://user-images.githubusercontent.com/5112397/127081792-08f23c24-1b73-4c6b-88c8-fd4b8e274759.png)

**Comment by roblourens** [comment]
That is the Run By Line button (it works!). There is another button that says "Debug" in the toolbar at the top of the notebook. It's visible in your previous post.

**Comment by A-Pai** [comment]
> That is the Run By Line button (it works!). There is another button that says "Debug" in the toolbar at the top of the notebook. It's visible in your previous post.

It's visible in your previous post.---which post？

**Comment by A-Pai** [comment]
Please give the screenshots.

**Comment by A-Pai** [comment]
The performance of  VS Code Insiders is not stable，Will it do in VS Code 1.58？

**Comment by roblourens** [comment]
![126946045-417831ef-14ca-473d-ba41-b02a0c643d2e](https://user-images.githubusercontent.com/323878/127243402-9931a500-8ea6-4224-b34c-b24e8260d158.png)

**Comment by A-Pai** [comment]
The performance of VS Code Insiders is not stable，Will it do in VS Code 1.58？

**Comment by roblourens** [comment]
I need more details to answer that question. What problems are you having?

**Comment by A-Pai** [comment]
> I need more details to answer that question. What problems are you having?

you can see the top several post until “would you please give me an exhaustive tutorial？I like this feature very much”

![image](https://user-images.githubusercontent.com/5112397/127255842-dff2f166-642b-4d2e-94a1-de24dbced4d9.png)

**Comment by DavidKutu** [comment]
Hey @A-Pai, this video runs through the notebook debugger https://www.youtube.com/watch?v=d2Yz4tivhPg.
Hope it helps.
