### ISSUE TITLE
不知如何使用

### ISSUE THREAD

**Issue by EayCome** [microsoft/vscode#129144]
Issue Type: <b>Bug</b>

(node:19116) Electron: Loading non-context-aware native module in renderer: '\\?\D:\Microsoft VS Code\_\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.87GB free)|
|Process Argv|--crash-reporter-id 3a45670a-45b8-4ce8-b2f0-9c5b473ca4f9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
jquerysnippets|don|0.0.1
translation|dus|0.0.4
prettier-vscode|esb|5.8.0
ilovejuejin|ezs|0.0.17
php-debug|fel|1.14.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.7
code-runner|for|0.11.2
anes|gam|0.0.2
gobystrok|GoB|0.0.1
vscode-drawio|hed|1.6.1
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
jquery-snippets|Hri|1.0.0
vue|jcb|0.1.5
php-cs-fixer|jun|0.2.5
vscode-gutter-preview|kis|0.26.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
laravel-intellisense|moh|0.2.0
vscode-language-pack-zh-hans|MS-|1.51.2
vetur|oct|0.31.3
indent-rainbow|ode|7.4.0
laravel-blade|one|1.25.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
rainbow-fart|sae|1.4.1
markdown-preview-enhanced|shd|0.5.22
svg-preview|Sim|2.8.3
guides|spy|0.9.3
tabnine-vscode|Tab|3.4.17
vscode-icons|vsc|11.5.0
bootstrap-3-snippets|wcw|0.1.0
beauty|yhp|0.0.2
vscode-preview-server|yui|1.3.0
cloudmusic|YXL|5.2.3
bootstrap-v4-snippets|Zac|1.1.3
at-helper|Zih|0.0.4

(3 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
@EayCome, you seem to be running VSCode `1.51.0`.
Could you please upgrade to the latest version and see if you are still able to reproduce the problem? Thanks!

**Comment by CodeCrazy-ywt** [comment]
@EayCome 你是说不知道如何使用vscode吗？你看官方文档啊，那里面说了如何使用啊，

**Comment by EayCome** [comment]
6 我这里有bug 我这里node进程有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月23日(星期五) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode] 不知如何使用 (#129144)





 
@EayCome 你是说不知道如何使用vscode吗？你看官方文档啊，那里面说了如何使用啊，
