### ISSUE TITLE
Repeated menu underlined shortcut keys

### ISSUE THREAD

**Issue by Nabav** [microsoft/vscode#129115]
There are repeated underlined characters in menu items, at least under menu `Selection`.

- Version: 1.58.2
- OS: Linux x64 4.19.0-17-amd64

Steps to Reproduce:

1. Press `Alt` + `S`
2. Press `S`

There are multiple menu items with an underlined `S` character.

![image](https://user-images.githubusercontent.com/24389873/126508567-585588fd-86b5-4c75-bc68-f90d56cd5427.png)

In general, it might be good idea to revise menu items for underlined characters.

**Comment by CodeCrazy-ywt** [comment]
No, these issues are not talking about the same thing. Not at all.

**Comment by sbatten** [comment]
I don't think its great to change these now and we already handle this gracefully, but leaving this up to @bpasero and @alexdima
