### ISSUE TITLE
Could Terminals created in the editor area optionally be opened in non-active editor group?

### ISSUE THREAD

**Issue by MilesMcBain** [microsoft/vscode#129172]
Currently when you run `Create Terminal In Editor Area` or run `Create New Integrated Terminal` with `terminal.integrated.defaultLocation = "editor"`, the created terminal opens "on top of" the current active text editor in the active editor group.

This is inconvenient if the purpose of creating the terminal was to send text from the active text editor to it, since the active text editor is now hidden. This is a common thing to want to do with programming languages that support REPL programming (E.g. Python, R, Racket, Clojure, etc.)

It would be really useful to have a new option to create terminals in the editor area in an editor group that is not the currently active one. It would be great if it could be a similar kind of thing to the options we get when creating WebViewPanels via the API: https://code.visualstudio.com/api/references/vscode-api#ViewColumn

So that would allow "beside" as an option, which is probably what most users want.

**Comment by MilesMcBain** [comment]
Neither of the above issues discuss the feature I am requesting.

**Comment by MilesMcBain** [comment]
Am I right in reading this is a new command not an option?

Without an option extensions that want to create terminals suddenly have to care about the user's preference for editor area or regular terminals. 

For example, when creating an R REPL the R extension needs to read the user's config to determine if the terminal would be opened in the editor area and if so, run the command to open in editor group to the side.

**Comment by MilesMcBain** [comment]
Is it possible to open an editor area terminal running R to the side via the API with this? It seems like no.

**Comment by Tyriar** [comment]
Ah I misunderstood, you're actually after this: https://github.com/microsoft/vscode/issues/45407

**Comment by MilesMcBain** [comment]
Not really.

As an extension developer I wanted to avoid editor area REPLs I create opening on top of the user's active text editor, for reasons stated.

I suggested an option to control this e.g. : `terminal.integrated.defaultLocation = "editor-beside".

An option would mean I don't have to change any existing code and can I leave it to the user to put their terminals where they wish.

You created a new command with no API binding, which does not allow me to create REPLS that do not block the text editor.

Once you create an API binding for opening terminals to the side, we'll have to update our extension code to only do that when the user has set  `terminal.integrated.defaultLocation = "editor"` since we don't want to force the user to use editor area terminals if they prefer the old workflow.

An option would have been simpler, and allowed extensions to treat terminals uniformly without changing their existing code. Probably the one drawback is that the option applies universally, and so would not allow the default editor area terminal behaviour for some languages, and the open beside behaviour for others. My guess is that opening to the side would be a popular choice and so this would not matter.
