### ISSUE TITLE
editor.foldingImportsByDefault shifts code around when you first open a file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#129127]
Issue Type: <b>Bug</b>

1. With `editor.foldingImportsByDefault` disabled
1. Open a file with lots of imports and scroll down in the file
1. Put the file into a background tab
1. Enable `editor.foldingImportsByDefault`
1. Open the file again

**Bug**
The editor contents shift up when the imports are collapsed

VS Code version: Code - Insiders 1.59.0-insider (Universal) (818c6613f765dd54bb29e77b4f7094a37cf67d08, 2021-07-21T05:15:01.788Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Hope the fix does it.
