### ISSUE TITLE
Command Palette should show "Go to Symbol in File" and "Go to Symbol in Workspace"

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#12911]
- VSCode Version: 1.6 insiders
- OS Version: any

With #11494 the Go menu now includes `Go to Symbol in File` and `Go to Symbol in Workspace`. The command palette only includes `Go to Symbol` which is `Go to Symbol in File`. There is no command for `Go to Symbol in Workspace`. We should add the command and make sure they are called the same in the command palette and the Go menu.

**Comment by bpasero** [comment]
Makes sense for consistency.

**Comment by egamma** [comment]
Verifying.

The action is now shown in the command palette, but it doesn't show the keybinding `CTRL-T` on windows.
![image](https://cloud.githubusercontent.com/assets/172399/18955436/c613b4d8-8657-11e6-93a1-f3b8925437b6.png)

The key binding is shown in the Go menu:
![image](https://cloud.githubusercontent.com/assets/172399/18955450/d710000c-8657-11e6-9459-21fd1a9502b4.png)

**Comment by bpasero** [comment]
@egamma weird, not for me:

![image](https://cloud.githubusercontent.com/assets/900690/18956552/176a3c9a-865c-11e6-98ef-aaedddc736e5.png)

I suspect you changed the keybinding and did not restart? The menu needs a restart to show a change.

**Comment by egamma** [comment]
Issue resolved. Alex's Lcov extension steals 'CTRL+T', easily tracked down thanks to the Contributions tab
