### ISSUE TITLE
does not scroll to the top notebook

### ISSUE THREAD

**Issue by randomQQQ** [microsoft/vscode#129123]
The first cells of the notebook are not displayed after opening

![image](https://user-images.githubusercontent.com/63656568/126534477-52ae2079-37ee-4185-92c0-3f6958aea0d3.png)

Extension version: 2021.8.1051926518
VS Code version: Code - Insiders 1.59.0-insider (818c6613f765dd54bb29e77b4f7094a37cf67d08, 2021-07-21T05:14:36.651Z)
OS version: Linux x64 5.8.0-63-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 3221)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (1.86GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 6d00c0c9-3fe5-497f-84af-e07721208327|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by abdlrhmanshehatamoussa** [comment]
Hi Guys,

I'm ready to help,

If any one could give a little push on where exactly can find the relevant code and any other recommendations, I'm ready to gooo.

Best of luck !

**Comment by roblourens** [comment]
I don't understand, can you explain the problem some more?

**Comment by randomQQQ** [comment]
I scrolled up to the maximum. Above there are cells that I do not see

**Comment by roblourens** [comment]
Do you see all the cells if you close and reopen the notebook?

**Comment by randomQQQ** [comment]
I didn't see them yesterday after restarting vscode, but I see them today. This is not the first time I have seen this problem.

**Comment by randomQQQ** [comment]
I didn't see them yesterday after restarting vscode, but I see them today. This is not the first time I have seen this problem.

**Comment by rebornix** [comment]
I think this issue was the same as missing markdown cell bug. It's already fixed in latest Insiders.
