### ISSUE TITLE
Overlaps between jupyter UI and terminal&vscode UI

### ISSUE THREAD

**Issue by NYGKNYGK** [microsoft/vscode#129148]
## Environment data

-   VS Code version: 1.58.2 c3f126316369cd610563c75b1b1725e0679adfb3 x64
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1046824664
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 & Ubuntu 20.04
-   Python and/or Anaconda version: conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Jupyter server running: Local 

## Expected behaviour

There should be no UI overlaps.

## Actual behaviour

There actually are UI overlaps between jupyter and terminal, vscode both on Ubuntu and Windows OS.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Windows:

Just open a .ipynb file and call a terminal. Just like below:
![image](https://user-images.githubusercontent.com/43544507/126584971-faa18711-2ebc-4234-a18c-a404b87be6b2.png)

After I click the button in the green box to maximize the terminal. The bottons in the red boxes will overlap, like this:
![image](https://user-images.githubusercontent.com/43544507/126584916-a8d83555-5f19-4850-a54f-647050b60a11.png)
There are overlaps between jupyter buttons and vscode buttons(File, Edit, etc)

Ubuntu:

Way to reproduce on Ubuntu is quite similar. But the result is different:
![image](https://user-images.githubusercontent.com/43544507/126585655-7c82191f-d5b1-4867-9ea2-6639e5b3fb4b.png)
You can see there are  overlaps between  jupyter buttons and terminal buttons.

**Comment by rebornix** [comment]
Fixed in main. THanks for reporting.
