### ISSUE TITLE
Info prompt to restart Code after uninstalling extension, but not installing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#12918]
When you uninstall an extension, you see this:

![image](https://cloud.githubusercontent.com/assets/323878/18925598/69aa25f4-8569-11e6-95e4-a138a37bdef9.png)

But when you install an extension, you have to see Enable in the extensions pane. It seems like you should see an info bar for both cases (or neither).

**Comment by joaomoreno** [comment]
Fixed.
