### ISSUE TITLE
Add whitespace between code and line numbers in Notebook Cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#129145]
Without the whitespace between the line numbers and code, I find the code a little hard to read.
I would like to enable the line numbers when working on large cells.
Note: I enable line numbers because I'd like to collapse some of the code (such as loops and the like). 

<img width="273" alt="Screen Shot 2021-07-21 at 21 06 00" src="https://user-images.githubusercontent.com/1948812/126588734-7e1fd726-361f-4080-a42c-bc5d195624ce.png">

@roblourens /cc

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode/issues/129146 actually
