### ISSUE TITLE
Can't do text formatting on showInformationMessage() method - VSCode Extensions

### ISSUE THREAD

**Issue by anburocky3** [microsoft/vscode#129133]
The text are not properly formatted.  Looks like VSCode supports simple bold, italics, but it is not working here:
```js
vscode.window.showInformationMessage('Opening **YT** channel.  __italic__ **bolded**','Open Channel', 'Website')
.then(selection => {
    // ...
})
```

![image](https://user-images.githubusercontent.com/15264938/126564992-54db1c87-547d-43a5-9eae-3f242d66bdbf.png)

**Comment by jrieken** [comment]
Formatting is only supported when the `vscode.MarkdownString`-type is accepted. For notification this is likely designed because we don't want "loud" notification

**Comment by usernamehw** [comment]
I've seen extensions that use hacks like this:

```ts
window.showInformationMessage('𝗯𝗼𝗹𝗱 𝘪𝘵𝘢𝘭𝘪𝘤 𝙗𝙤𝙡𝙙&𝙞𝙩𝙖𝙡𝙞𝙘 𝕕𝕠𝕦𝕓𝕝𝕖 🧡💛💚💙');
```

![Screenshot (136)](https://user-images.githubusercontent.com/9638156/126602326-fdd19b77-1181-4e6b-b231-f9c0deb1aa58.png)

Looks uglier bc it's a different font though. And it won't work with a different language.

https://yaytext.com/bold-italic/

**Comment by anburocky3** [comment]
@jrieken  Looks meaningful! 

@usernamehw I like your suggestion, I'm using the default font(English) only but still, I see some kind of blurriness. So leaving it as before and adding emojis made it look cool. Thanks.
