### ISSUE TITLE
vsce should not publish with duplicates in extensionDependencies

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12914]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:23:37.103Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

#12647

Extensions can be published like the following:

```js
    "extensionDependencies": [
        "Tyriar.sort-lines",
        "Tyriar.lorem-ipsum",
        "Tyriar.lorem-ipsum"
    ]
```

**Comment by joaomoreno** [comment]
Microsoft/vscode-vsce#134
