### ISSUE TITLE
Status bar should get the same "instant hover" treatment as the activity bar/panel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129118]
In the activity bar and panel I recently added the ability to move between entries and the hover will show up without delay: https://github.com/microsoft/vscode/pull/128845

We should do this in the status bar as well.

**Comment by aeschli** [comment]
I'm off for three weeks from tomorrow. @Tyriar If you can do the adoption that would be great!

**Comment by AiverReaver** [comment]
I think I can do that. Can I work on this issue?

**Comment by aeschli** [comment]
@jrieken FYI

**Comment by AiverReaver** [comment]
@aeschli  any suggestions for the PR?

**Comment by aeschli** [comment]
Sorry, I didn't find time yet to look at it

**Comment by aeschli** [comment]
I pushed the change that the hover shows instantly. Always, not only when moving between status bar items.

**Comment by bpasero** [comment]
@aeschli can you clarify as to why you decided to do that? Imho that is very inconsistent with how the hover works in other parts. I think the original ask from @Tyriar was to keep the hover visible once it shows and when you move between elements (same as native hovers would do).

We have had users complaining in the past that the custom hover can be very annoying and showing it without delay is imho wrong.

**Comment by aeschli** [comment]
I reverted the change so this can be discussed further

As status bar hovers now are rich hovers and include status and links, the user that wants to see the information without delay.

**Comment by bpasero** [comment]
I think we will need some heuristic to figure out whether a status entry has rich content or not and then make a decision. If we have that, we can probably revert https://github.com/microsoft/vscode/commit/fac852f4ac038773fe8aec05b2a48e1105ffd78f

**Comment by rzhao271** [comment]
@bpasero looks like a lot happened. I have verified the behaviour in the original comment occurs in Insiders, but I'm wondering if there's anything else to verify?
