### ISSUE TITLE
Allow menu extension point for the Help menu bar

### ISSUE THREAD

**Issue by orellabac** [microsoft/vscode#129179]
Currently there is not extension point to contribute to the MenuBar. 
I have some extensions for which I would like to add help links into the Help menu bar. But does it is not exposed yet.

**Comment by sbatten** [comment]
we currently have no plans to expose the menu as an extension point. please see if the walkthrough api meets your needs https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample

**Comment by sbatten** [comment]
cc @JacksonKearl
