### ISSUE TITLE
Shift+Scrolling over DataFrames scrolls both horizontally and vertically

### ISSUE THREAD

**Issue by evilpegasus** [microsoft/vscode#129119]
Using shift+scroll over an outputted Pandas DataFrame scrolls the entire notebook up and down and the DataFrame left and right. It should only scroll the DataFrame left and right.

This new behavior started happening in the new native notebooks update.

## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1046824664
-   Python Extension version (available under the Extensions sidebar): v2021.7.1050252941
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro Version	10.0.19042 Build 19042
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Holding shift and scrolling over a Pandas DataFrame should only scroll horizontally.

## Actual behaviour

Holding shift and scrolling over a Pandas DataFrame scrolls both horizontally and vertically.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a wide (overflowing) DataFrame and output it:
```python
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 100)

pd.DataFrame(np.ones((5,100)))
```
![image](https://user-images.githubusercontent.com/50010165/126509475-19b745f6-ee35-4415-8152-00775890ed16.png)

2. With the mouse over the outputted DataFrame, hold shift and scroll. The DataFrame will scroll left and right as expected, but the entire notebook will also scroll up and down (not expected).

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rebornix** [comment]
Fixed already in Insiders.
