### ISSUE TITLE
Menubar and Context Menu invisible on Windows High Contrast

### ISSUE THREAD

**Issue by markoczy** [Microsoft/vscode#12915]
<img width="908" alt="vsc_menubar_bug" src="https://cloud.githubusercontent.com/assets/12068873/18925354/f4e600b2-85b3-11e6-8429-b355f9ba3ba0.PNG">

- VSCode Version: 1.5.3
- OS Version: Win 10 Education 10.0.14393 Build 14393

Steps to Reproduce:

1.  Set Windows to high contrast mode with dark background
2.  Start VS Code and open menu bar or context menu

The result is that the menu items are invisible (white on white, see picture), only the selected item remains visible.

**Comment by markoczy** [comment]
Probably this is also useful, this is my High Contrast configuration (I already tried to change the gray, but still no differnce):

<img width="366" alt="hc_settings" src="https://cloud.githubusercontent.com/assets/12068873/18925670/2e4d6024-85b5-11e6-889e-74ad747fd7bc.PNG">

**Comment by joaomoreno** [comment]
Setting to September for analysis.

**Comment by bgashler1** [comment]
This looks like an electron issue (since it's in the native UI).  Not sure I'll be much help here.  Please feel free to assign me back if I'm wrong. :)

**Comment by bpasero** [comment]
This was fixed with the electron update.

@markoczy can you give our insider build a try: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by markoczy** [comment]
Fix confirmed for insider build V1.6.0, thanks a lot for your effort!
