### ISSUE TITLE
Calling Terminal.show() on a terminal that is in the text editor area pops the terminal panel open

### ISSUE THREAD

**Issue by MilesMcBain** [microsoft/vscode#129169]
Does this issue occur when all extensions are disabled?: No (because it's a bug with an API call)

- VS Code Version: 1.58.2
- OS Version: Ubuntu 20.04 (Linux 5.5.19-050519-generic x86_64)

Steps to Reproduce:

1. Run command "Create New Integrated Terminal" from command palette
2. Focus the new terminal
3. Run command "Move Terminal Into Editor Area"
4. Hide the Terminal Panel
5. Move editor area terminal to secondary editor group on its own.
6. Focus a text editor in primary editor group.
7. Run any command that calls Terminal.show() targeting the active terminal. Active terminal should be the editor area terminal since that was the last one you touched in step 5. The internal command "Run selected text in active terminal" seems to do this.
8. Observe the terminal panel is popped open showing a terminal. One is created if none existed other than the editor area terminal.

If you used "Run selected text in active terminal" in step 7, you'll notice the text went to the correct terminal (editor area).

We [observe this behaviour in the VSCode-R extension](https://github.com/REditorSupport/vscode-R/issues/682) when sending commands to a managed R terminal, [the final step of which is to call optionally call show()](https://github.com/REditorSupport/vscode-R/blob/master/src/rTerminal.ts#L289). If `show()` is not called, commands can be sent without popping the terminal panel open.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/128670 - already fixed in insiders
