### ISSUE TITLE
cannot find path

### ISSUE THREAD

**Issue by itvhub-sketch** [microsoft/vscode#129114]
I have been trying to execute a simple c++ program in vs code. when I compile the program it is ok however, when I try to execute the file I get error message cannot find path because it does nor exist. doest anyone know what I am doing wrong, it seems as though I am following the tutorial correctly?

**Comment by lszomoru** [comment]
@itvhub-sketch, do you mind providing some additional information:
1. What version of VSCode are you running?
2. Which tutorial are you following?
3. Have you installed any C++ extension for VSCode? If so, which one?
4. Could you please share the exact error message that you are getting?
