### ISSUE TITLE
before search history should be retained when open new vscode windows.

### ISSUE THREAD

**Issue by hjysmi** [microsoft/vscode#129155]
before search history was retained when open new vscode windows, like notepad++ search history list.
![image](https://user-images.githubusercontent.com/13214614/126606936-710892e2-d9ec-4521-a205-24adc4a8d47b.png)

**Comment by hjysmi** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Input history is not retained on reload (#127701)](https://www.github.com/microsoft/vscode/issues/127701)
this issue is different from my issue.

**Comment by roblourens** [comment]
You can access search history using the arrow keys

**Comment by hjysmi** [comment]
@roblourens 
search history was discarded when **open new windows with different text file**.

**Comment by roblourens** [comment]
We keep the search history per-workspace, this might not be what you always want but I think that search queries are often contextual to the workspac
