### ISSUE TITLE
Code Restart showing this error

### ISSUE THREAD

**Issue by manishsainju** [microsoft/vscode#129150]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`/home/manish/prof-54c1.extHost.cpuprofile.txt`
-`/home/manish/prof-54c1.main.cpuprofile.txt`
-`/home/manish/prof-54c1.renderer.cpuprofile.txt`

**Comment by manishsainju** [comment]
[prof-54c1.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6860064/prof-54c1.extHost.cpuprofile.txt)
[prof-54c1.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6860065/prof-54c1.main.cpuprofile.txt)
[prof-54c1.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6860066/prof-54c1.renderer.cpuprofile.txt)

**Comment by deepak1556** [comment]
Did you start with `code --prof-startup` which would generate those files. Does it happen for every restart or was it a one time repro ?

**Comment by manishsainju** [comment]
it happened for a single time with the` --prof-startup` parameter

**Comment by deepak1556** [comment]
Then it is expected to generate those files
