### ISSUE TITLE
Variables are not  recognize  and  does not show tips for variables

### ISSUE THREAD

**Issue by hopperhuang** [microsoft/vscode#129152]
After recently updates, my vscode doesn't work well.  It doesn't recognize the varaibels.
For examples:

<img width="633" alt="截屏2021-07-22 下午2 16 17" src="https://user-images.githubusercontent.com/20254356/126596957-e7719604-70f0-4a9e-8842-07f17332ae20.png">

I have  a varaible callled "printStatus", but when I print  It always show tips slowly and regard the variabels as text,  you can see the picture below

And  sometimes it even doesn't have tips.

<img width="681" alt="截屏2021-07-22 下午2 20 06" src="https://user-images.githubusercontent.com/20254356/126597202-9af73d84-585d-43fb-8ef2-fa04e7c02ba0.png">

when i want to use this variable in a if ... else statement, it even haven't any tips.

And others, I  some auto import function missed. Used to be, when I type "useState" into the file, It will showt the tips, and when I confirm ,  It will add a line it the file header like "import React, { useState } from 'react'. But now this function has missed. I c

Can you tell me how to fixed this problems? I really need this function. thanks.

**Comment by mjbvz** [comment]
Please share a self-contained, minimal code example (as text) that demonstrates the issue
