### ISSUE TITLE
Unable to collapse code in notebook cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#129146]
I'm unable to collapse code in cells,
E.g. I have a for loop. In a Python file, I'm able to collapse the for loop, not in a notebook cell with the same code.
<img width="397" alt="Screen Shot 2021-07-21 at 21 06 07" src="https://user-images.githubusercontent.com/1948812/126588961-1f09ecc8-4fc7-4e2a-98bb-8f60055cd7b9.png">
<img width="352" alt="Screen Shot 2021-07-21 at 21 11 01" src="https://user-images.githubusercontent.com/1948812/126588968-60069519-e5c9-436c-af78-a94d11ddd11f.png">

@roblourens /cc

**Comment by roblourens** [comment]
We decided to enable this when line numbers are enabled but I haven't done that yet

**Comment by DonJayamanne** [comment]
>  are enabled but I haven't done that yet

Oh sorry, lets close this issue then.

**Comment by roblourens** [comment]
@DonJayamanne I assigned this to myself and added it to the milestone because I intend to do it :)
