### ISSUE TITLE
New windows should be maximized when opened

### ISSUE THREAD

**Issue by tsongas** [microsoft/vscode#129216]
Issue Type: <b>Feature Request</b>

Why make millions of developers hit a button every time they open a new window?

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

**Comment by bpasero** [comment]
Did you try out the `window.newWindowDimensions` setting?

**Comment by tsongas** [comment]
That worked, thanks! Seems like maximized should be the default.
