### ISSUE TITLE
File encoding is automatically detected and identified incorrectly, and the encoding of GB 2312 is incorrectly identified as windows1252

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode#129289]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.59.0-insider (system setup) all versions
- OS Version:Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Turn on automatic encoding detection settings
Create a file to encode GB 2312
Input 中文
![image](https://user-images.githubusercontent.com/63572041/126859921-ac5b1428-3d80-4f01-95b3-c6ac8b5f5886.png)

Close file

2.Reopen the file with garbled characters, the character set is not recognized as GB 2312
[aaa.txt](https://github.com/microsoft/vscode/files/6872006/aaa.txt)

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
