### ISSUE TITLE
Extension Search Default Query Should Have Space After It

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12924]
- VSCode Version: 1.6 Insiders
- OS Version: OSX 10.11

##### Steps to Reproduce

1. In new VS session, click on extensions section
2. Start typing some search term.

##### Expected
Entered text  becomes search term

#### Actual
Because no space in inserted after the default `@sort:installs` query, the text is tacked onto the end of that:

![sep-28-2016 11-28-47](https://cloud.githubusercontent.com/assets/12821956/18927026/d8b81b22-856e-11e6-8864-da2991f23241.gif)

**Comment by joaomoreno** [comment]
Wanna submit a PR?

**Comment by mjbvz** [comment]
@joaomoreno Was just editing the commit when I saw your message :) Just a moment
