### ISSUE TITLE
Unable to execute python code using interactive shell

### ISSUE THREAD

**Issue by raghurajnair** [microsoft/vscode#129285]
Issue Type: <b>Bug</b>

VSCode is looking for ipykernel to be installed, whereas when I run pip install ipykernel, it shows all relevant and requisite packages are installed. Also I see its trying to execute python3.8.10 where as when I check in terminal my default python is 3.8.8 with conda environment (base). 

Selecting a different kernel and trying is not helping either, as its still sticking to the same error message "Running cells with 'Python 3.8.10 64-bit' requires ipykernel". To which any re-install attempt is not helping. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-59-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (3 x 2304)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|4.82GB (0.31GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 41ba546f-537e-4fac-9812-07622f52ee82|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.1.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by joyceerhl** [comment]
@raghurajnair If you open the command palette and run the Python: Select Interpreter command, then pick your 3.8.8 environment, does the problem persist? The Python extension doesn't pick up the Python on PATH, instead it provides you with the ability to configure an active interpreter which is then shown in the bottom left status bar:
![image](https://user-images.githubusercontent.com/30305945/126859726-818ec7db-a24d-4bd6-8ba7-778c65e39ce1.png)
