### ISSUE TITLE
cant sync themes

### ISSUE THREAD

**Issue by viktorilie** [microsoft/vscode#129299]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

cant sync themes between devices

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.33GB free)|
|Process Argv|--crash-reporter-id 5bda362d-57f0-4166-9bd7-c6e1ffedeb33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
search-node-modules|jas|1.3.0
vscode-peacock|joh|3.9.1
theme-monokai-pro-vscode|mon|1.1.19
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.8.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
gruvbox-material|sai|6.4.5
node-pack|Swe|0.1.16
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by sandy081** [comment]
Do you see any errors?
