### ISSUE TITLE
Acrylic and other design elements from Win11

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/vscode#129290]
I am using Win11 Dev build and would love to see transparency and possibly some other design elements in VScode.
I found a [issue](https://github.com/microsoft/vscode/pull/52707), but it's closed and I don't understand why. I find this to be quite an important question. I understand that those who care about the interface have been using apple for a long time, but still.

**Comment by matkoniecz** [comment]
> I found a issue, but it's closed and I don't understand why.

See https://github.com/microsoft/vscode/pull/52707#issuecomment-519462107

> I am going ahead and close this PR for the reasons outlined: We currently do not accept more features that are Electron specific. We have seen to many issues lately when updating to newer Electron versions and playing the catch-up game is very painful.

**Comment by Mystic8b** [comment]
Ah, okay, I wasn't careful enough. Well, in any case, I think with the release of win11 the question is more relevant than ever.

**Comment by misolori** [comment]
Closing for the same reasons that others have already mentioned.
