### ISSUE TITLE
Language change prompt for wrong language

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#129204]
Issue Type: <b>Bug</b>

I did have my OS language set to Spanish for some testing, many months back though. Now my OS languages are 1. en-US 2. de-DE and 3. es-ES.

Even when VS Code starts up with a fresh user-dir does still prompt me to install the Spanish language pack. C++ extension also gets confused by this and switches to Spanish for me: https://github.com/microsoft/vscode-cpptools/issues/7665

![image](https://user-images.githubusercontent.com/8599/126722112-4bed4efb-81a1-4f25-85f9-1b235670c1ad.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (9.73GB free)|
|Process Argv|--log trace --crash-reporter-id 487fc18f-08b0-40a4-87d4-37e92ccd73d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|don|0.3.5
codespaces|Git|0.10.10
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
cpptools|ms-|1.5.1

</details>

**Comment by lszomoru** [comment]
@TylerLeonhardt, is this something that falls into your area of ownership?

**Comment by TylerLeonhardt** [comment]
Not really...(or rather not yet maybe) I own the build infra for the Language Packs outside of VS Code (and soon the build infra for the Language Packs inside of VS Code).

This is more of a @dbaeumer question I think. @digitarald does this feel like a new behavior recently broken?

**Comment by digitarald** [comment]
@TylerLeonhardt yes and no. Language pack recommendation was broken for years and got fixed (https://github.com/microsoft/vscode/issues/123925) in the June release. The C++ issue happened before that, so VS Code has put a locale somewhere that is being re-used between data-dirs.

**Comment by TylerLeonhardt** [comment]
Interesting. So maybe we need @sandy081 in here too.

**Comment by sandy081** [comment]
locale info is stored in args.json file which you can open using command `Configure Runtime Arguments`. This file is not in user data dir. It is in user home dir. Please check if the locale is configured to Spanish language in that file?

**Comment by digitarald** [comment]
@sandy081 yes, that was it. For testing I had probably forced the locale through args. Sorry about all the fuzz. I guess a few things can't be isolated when starting a VS Code instance to a completely fresh state.
