### ISSUE TITLE
JS debug icon is not showing up anymore in tabs list

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129208]
but other extension created icons are...

**Comment by meganrogge** [comment]
doesn't work in tabs list when using this syntax (as opposed to just a string)

`iconPath: '$(server-process)',`

**Comment by Tyriar** [comment]
Works for me with nightly js-debug /cc @connor4312

**Comment by connor4312** [comment]
I don't see this either, what version of js-debug are you on?

**Comment by meganrogge** [comment]
oh works with nightly js-debug 👍🏼
