### ISSUE TITLE
Accessibility Options have permanently disabled checkboxes?

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12928]
Testing #12519

I don't know what they do but I want to check them, and I can't!

![image](https://cloud.githubusercontent.com/assets/762848/18927861/753727b0-8572-11e6-9872-5c6e4d91cb79.png)

**Comment by mousetraps** [comment]
Just chatted with @Tyriar - apparently, these aren't checkboxes... they are empty icons masquerading as checkboxes.

**Comment by Tyriar** [comment]
This is chrome://accessibility, I guess Electron adds it to the menu by default now?

**Comment by bpasero** [comment]
We should take this out for the stable release and only have it in insiders.

**Comment by bpasero** [comment]
Closing, we do not control the contents of the accessibility page from chrome.
