### ISSUE TITLE
Windows Datamigration smoke test failure 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#129279]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=128939&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=316b23c8-21ca-5aab-3515-3225235af7bb

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=129461&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=316b23c8-21ca-5aab-3515-3225235af7bb 

```
  1) Stable vs Insiders Smoke Tests: This test MUST run before releasing
       Datamigration
         verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.tabs-container div.tab.dirty[data-resource-name$="readme.md"]' after 20 seconds.
      at poll (D:\a\1\s\test\automation\out\code.js:178:19)
      at async Code.waitForElement (D:\a\1\s\test\automation\out\code.js:259:16)
      at async Editors.waitForTab (D:\a\1\s\test\automation\out\editors.js:36:9)
      at async Context.<anonymous> (out\areas\workbench\data-migration.test.js:72:13)

  2) "after all" hook in "{root}":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by isidorn** [comment]
Ben is on vacation. Moving to august, also assigning to @JacksonKearl if he would like to look into it this week.

**Comment by bpasero** [comment]
Without screenshots or visual traces I fail to diagnose this further. We really need https://github.com/microsoft/vscode/issues/128479 with support for tracing or upload screenshots during the run as build asset.

I have checked the log files for these runs but did not find anything suspicious unfortunately.
