### ISSUE TITLE
Renaming an open file is jarring

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12923]
Testing https://github.com/Microsoft/vscode/issues/12519

See video below:
[2016-09-28_11-04-54.zip](https://github.com/Microsoft/vscode/files/498920/2016-09-28_11-04-54.zip)

While renaming the file aa.php to aaa.php, the following happens within the course of a second:
![image](https://cloud.githubusercontent.com/assets/762848/18926654/82a40602-856d-11e6-9dc9-eb0779136027.png)
- **Frame 1:** Starting point
- **Frame 2:** aa.php gets renamed to aaa.php in file viewlet, and aa.php becomes unselected (but not removed) in Open Editors view
- **Frame 3:** All of the files in the open editors view shift down by one file "unit", as aaa.php gets added and highlighted to the open editors view, but aa.php isn't removed. Additionally, there is some additional padding that gets added between the open editors view and the file view. 
- **Frame 4:** aa.php gets removed from the open editors view and all of the files below it are subsequently shifted upwards in the Open Editor view.
- **Frame 5:** the extraneous padding between the Open Editors and File view gets removed

All of this occurs within a timeframe that's very much perceptible to the user and gives the impression that the app isn't "smooth". I don't know if this has to do with the recent electron update, but I do notice that v1.5 doesn't seem to feel as jarring, though haven't dug into it as much.

**Comment by isidorn** [comment]
October to investgiate

**Comment by isidorn** [comment]
This is just how we have architectured the open editors view and how the tree refreshes.
PR that fix this are welcome
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L77
