### ISSUE TITLE
Use space as a seperator between the path matching and regular quick open matching

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1292]
In the following example it would be cool if the word after the space would do regular quick open matching on all the files that passed the path filter.

<img width="184" alt="screen shot 2015-12-14 at 16 39 22" src="https://cloud.githubusercontent.com/assets/1926584/11785283/5d71698a-a281-11e5-8261-79753e269651.png">

**Comment by bpasero** [comment]
#5306
