### ISSUE TITLE
Install Extensions cause systemcrash and reboot on MacBookPro 16-inch 2019 macOs10.15.7 

### ISSUE THREAD

**Issue by songjiafan** [microsoft/vscode#129228]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.59.0-insider
- OS Version: macos 10.15.7

Steps to Reproduce:

1.I Installed “AppWorks” Extension，About 5 seconds after the installation is complete，my computer crashed，the mouse did not move，and then computer reboot
2. My computer starts vscode automatically，if I don't turn vscode off when I turn computer on, it will be crashed.
3. I has ask the "AppWorks" Extensions Team，they think it may be vscode&system api compatibility question.

**Comment by sandy081** [comment]
Is it only with this AppWorks extension or installing other extensions also have same issue ?

**Comment by fyangstudio** [comment]
stylelint may cause crash too. It's very strange in 

* VS Code Version: 1.59.0-insider
* OS Version: macos 10.15.7

**Comment by fyangstudio** [comment]
As a VS Code extension developer,  i want to know how to avoid this issue happen again.

**Comment by sandy081** [comment]
@fyangstudio / @songjiafan Can you please provide any logs or report of the crash?
