### ISSUE TITLE
Disable non-native custom hovers 

### ISSUE THREAD

**Issue by strepto572** [microsoft/vscode#129236]
I hate the vs code custom hovers. 
In previous versions, I could disable them with "workbench.experimental.useCustomHover". As a matter of fact, the only thing that makes vs code tolerable is that It has always taken extreme pains to try to provide a native experience where possible. 

The custom hovers are just stupid, they are limited to the viscose window, and they just work weird. 
I'm just extremely frustrated by the new hovers and found out I had to downgrade vs code so that I would not be forced to use it.

**Comment by Tyriar** [comment]
We're adopting the custom hovers in places where they add additional functionality (links, fast display, status bar actions, markdown), so we can't just switch them off. You could try tweak the style of them to your liking but I don't think they're going anywhere.

```json
  "workbench.colorCustomizations": {
    "editorHoverWidget.background": "#ff0000",
    "editorHoverWidget.statusBarBackground": "#0000ff",
    "editorHoverWidget.border": "#00ff00",
    "editorHoverWidget.foreground": "#ffffff",
  }
```

**Comment by zoobear42** [comment]
@Tyriar 
>We're adopting the custom hovers in places where they add additional functionality (links, fast display, status bar actions, markdown)

That is a plain and simple lie. 
Not all status bar actions need additional functionality. 
"Aditional functionality" like 'fast display', 'links', 'status bar actions', all those are things that I want disabled. 
I don't want to see the fucking stupid tooltip in the sidebar just for showing what the keyboard shortcut/name of that thing is. That was perfectly fine as a native hover/tooltip.
I especially hate with all my forces the fact that that shit is bounded to the vscode window limit. 70% of the time I spend on vscode, it is not maximized. I want to leverage all the space in my screen to see information. 
I also hate the speed with which some of these tooltips show up, and the position. 
And I also really hate that all this crap is different and weird, and each one has it's own kinks.

**Comment by zoobear42** [comment]
Everything has a stupid idiotic bubble tooltip now, no one cares right? Might as well remove the native title bar then. Fucking disgusting crappy buggy product
