### ISSUE TITLE
Quick file selection (cmd+p) doesn't hightlight the first result

### ISSUE THREAD

**Issue by alisalahio** [microsoft/vscode#129297]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Darwin x64 20.5.0

Steps to Reproduce:

1. Press ctrl+p or cmd+p on a Mac
2. Quck file selection opens, but the first result isn't highlighted as usual

It's difficult to adapt since there's muscle memory involved

**Comment by TylerLeonhardt** [comment]
I can't verify this in VS Code Insiders. Can you verify if you're seeing the problem in insiders:
https://code.visualstudio.com/insiders/

**Comment by alisalahio** [comment]
Hey @TylerLeonhardt, I faced the problem again once I installed insiders, but then it went away.
It also went away in the stable version. I'll wait till I catch it again then upload a video of it :D

**Comment by TylerLeonhardt** [comment]
I don't know if you are turning on a screen reader at all but the quick input behavior changes a bit when a screen reader is active. 

I'll go ahead an close this for now since there's no actionable steps for me but feel free to drop a video here and I can reopen/get a new issue going.
