### ISSUE TITLE
workspace settings gets cleared after connect to remote

### ISSUE THREAD

**Issue by mhsattarian** [microsoft/vscode#129268]
Issue Type: <b>Bug</b>

I'm using vscode on WSL2 with remote-wsl extension, and everytime I open vscode, which automatically opens `WSL:Ubuntu` remote, my workspace settings get changed.

I'm using `peacock` extension which alters colors and theme of current vscode window, and settings get erased after vscode has connected to remote server.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.42GB free)|
|Process Argv|--crash-reporter-id ffb3ea8f-bd83-480f-bc74-907c81c5c098|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|6.07GB (5.28GB free)|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
vscode-custom-css|be5|6.0.0
bracket-pair-colorizer|Coe|1.0.61
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
output-colorizer|IBM|0.1.2
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
nunjucks|ron|0.3.0
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|2.5.21
vscode-icons|vsc|11.5.0
material-theme|zhu|3.11.1
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
scope-bar|amo|0.2.1
alignment|ann|0.3.0
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.7.1
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.42.1
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
eppz-code|epp|1.2.52
prettier-vscode|esb|8.0.1
vue-format|feb|0.1.8
gc-excelviewer|Gra|3.0.42
vscode-graphql|Gra|0.3.16
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
output-colorizer|IBM|0.1.2
vscode-postfix-ts|ipa|1.9.4
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.6.4
vscode-map-preview|jum|0.5.8
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
vsliveshare|ms-|1.0.4583
color-highlight|nau|2.4.0
live-server-preview|neg|0.1.4
gremlins|nho|0.26.0
vetur|oct|0.34.1
vscode-nunjucks-formatter|oki|0.1.3
emoji|Per|1.0.1
vscode-versionlens|pfl|1.0.9
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
prisma|Pri|2.27.0
vscode-yaml|red|0.21.1
LiveServer|rit|5.6.1
nunjucks|ron|0.3.0
shader|sle|1.1.5
swdc-vscode|sof|2.5.21
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.5.0
footsteps|Wat|0.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.1
html-css-class-completion|Zig|1.20.0

(18 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by sandy081** [comment]
Are you able to repro this when extensions are disabled (except remote-wsl of course)

**Comment by mhsattarian** [comment]
I tried, and with all extensions disabled it didn't happen.

**Comment by sandy081** [comment]
Please bisect by following https://code.visualstudio.com/blogs/2021/02/16/extension-bisect and find out which extension is causing it and file the issue against that extension.
