### ISSUE TITLE
"Reveal in Side Bar" on the diff editor by GitLens doesn't work well

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#129200]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.59.0-insider
Commit: e8a59bc6f920e731b47f0bc72263e82aba8b796e
Date: 2021-07-22T05:13:00.851Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Install GitLens
2. Open a diff of a commit through the source control panel
3. Right-click the tab of the diff editor.
4. Select "Reveal in Side Bar" 
5. VS Code just reveal an entry in open editors, not a file in the directory tree.

The cause is that the resource of the diff editor is `gitlens://...`. It would be easy to implement the feature on the extension side. VS Code had better hide the entry, "Reveal in Side Bar", if the scheme of the resource of a diff editor is `gitlens`.

![スクリーンショット 2021-07-23 7 58 57](https://user-images.githubusercontent.com/10665499/126720013-97c2d212-487f-46d7-8652-4386c5429396.png)

**Comment by eamodio** [comment]
The core _Reveal in Side Bar_ command, probably needs to check that the file uri exists in a workspace folder.

**Comment by isidorn** [comment]
Here's a code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileCommands.ts#L344
There is already a check to see if the `URI` exists in a workspace folder, it seems like that check returns `false` and then we simply focus the Open Editors view

I am open for suggestions or a PR how to potentially improve this.
