### ISSUE TITLE
Start without debugging should not register breakpoints

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129255]
VS Code should consider to skip the breakpoint registering DAP calls.
Even if a DA ignores the "noDebug" option it is somewhat surprising if it still breaks on breakpoints.

**Comment by isidorn** [comment]
I think this makes sense. Feel free to assign to August and I can look into this next milestone.

**Comment by isidorn** [comment]
I have done the change that if we are Running without debugging we do not do any breakpoint calls.
This also includes exception breakpoints.

**Comment by weinand** [comment]
@isidorn Works great!
With this change I could simplify Mock Debug because it is no longer necessary to protect many DAP request implementations from being run in "no-debug" mode.
