### ISSUE TITLE
Enable selecting diff tool from context menu in Source Control panel

### ISSUE THREAD

**Issue by benlindsay** [microsoft/vscode#129209]
My feature request is related to [this issue](https://github.com/microsoft/vscode/issues/97683). With the DrawIO extension and other extensions with custom diff tools, I see no way to opt out of the custom diff tool and view the raw text diff. If I'm in the Explorer panel, I can right click a file, choose "Open With..." and choose between "Text Editor" or "Draw.io"

![image](https://user-images.githubusercontent.com/9361152/126731072-1143d2f8-88bf-45ea-a1f2-c44956a222f8.png)

When I right click on a file with changes in the Source Control panel, I don't see a similar way to choose between the custom diff tool and a raw text diff.

![image](https://user-images.githubusercontent.com/9361152/126731238-00280fb5-a1d1-4941-b4ad-2b603b120578.png)

It would be really nice if there was an analogous "Open With..." option from which I could choose a raw text diff, rather than having to temporarily disable the extension to get the raw diff.

Would this be a feasible change?

In any case, thanks so much for all your work on VSCode! It's a fantastic tool.

**Comment by hediet** [comment]
Would be great to improve general support for diffs in custom editors. Maybe custom diff views that are aware of both documents?
Also see #97683.

**Comment by septatrix** [comment]
Just for completeness here is the issue from the drawio extension repo: https://github.com/hediet/vscode-drawio/issues/211
