### ISSUE TITLE
Test icon colors not appearing in High Contrast theme

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#129281]
Issue Type: <b>Bug</b>

Hi, I'm working on the [Azure static web apps extension](https://github.com/microsoft/vscode-azurestaticwebapps) and am running into a weird issue when using colored codicons in the tree view.

The colors I'm using for these are from the [theme colors testing colors](https://code.visualstudio.com/api/references/theme-color#testing-colors).

1. View tree view in high contrast mode
2. Click around and focus different tree items

Expected: 
Icons should always be shown

Actual:
Sometimes icons disappear, and only appear when the tree item is focused

## Video with High Contrast theme:
https://user-images.githubusercontent.com/12476526/126848342-aa72b7e8-58b9-4c26-8dd4-3e74bd7ae353.mov

## Here you can see that they behave properly with the Dark+ theme:
https://user-images.githubusercontent.com/12476526/126848480-ec5c3292-01d0-4e1d-97bd-82c7461e689d.mov

Thanks! 🙏 😊 

VS Code version: Code - Insiders 1.59.0-insider (Universal) (e8a59bc6f920e731b47f0bc72263e82aba8b796e, 2021-07-22T05:13:00.851Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id eb6f422b-5935-4d6a-89db-b06c6aac18f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
TabOut|alb|0.2.0
vscode-wranglr|ale|0.0.2
statusbar-commands|anw|1.8.0
vscode-tailwindcss|bra|0.6.13
multi-cursor-case-preserve|Car|1.0.5
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
windows-terminal-opener|cyr|1.1.0
vscode-eslint|dba|2.1.23
eslint-disable-snippets|drK|1.3.0
gitlens|eam|11.6.0
prettier-vscode|esb|8.0.1
vscode-jest-runner|fir|0.4.44
auto-rename-tag|for|0.1.7
codespaces|Git|0.11.0
vscode-pull-request-github|Git|0.28.0
helium-icon-theme|hel|1.0.0
rest-client|hum|0.24.5
google-search|kam|0.0.1
workspace-in-status-bar|koa|1.0.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
camelcasenavigation|map|1.1.3
json-to-ts|Mar|1.7.5
copy-github-url|mat|0.6.0
fluent-icons|mig|0.0.12
theme-monokai-pro-vscode|mon|1.1.19
vscode-duplicate|mrm|1.2.1
azure-pipelines|ms-|1.188.1
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.7.1
vscode-azurevirtualmachines|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.0
vscode-docker|ms-|1.15.0
remote-containers|ms-|0.189.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4583
debugger-for-chrome|msj|4.12.12
vscode-json-editor|nic|0.3.0
angular-console|nrw|17.6.1
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.8.0
material-product-icons|PKi|1.0.4
vscode-css-peek|pra|4.2.0
bracketeer|pus|1.3.1
seti-icons|qin|0.1.3
explorer-exclude-vscode-extension|Red|1.2.0
vscode-sort-json|ric|1.20.0
synthwave-vscode|Rob|0.1.8
vscode-appwrite|Str|0.1.3
ayu|tea|0.20.1
ms-teams-vscode-extension|Tea|2.2.0
statusbar-format-on-save|tre|1.1.3
sort-lines|Tyr|1.9.0
highlight-matching-tag|vin|0.10.1
keyoti-changeallendoflinesequence|vs-|0.0.3
vscode-icons|vsc|11.5.0
faster-new|wen|1.3.11
copy-hover-type|You|0.0.6
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.1

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by joaomoreno** [comment]
@misolori Is this fixed now?

**Comment by misolori** [comment]
It appears this is because the high contrast color for the test icons are black (which won't appear because the background is also black):

https://github.com/microsoft/vscode/blob/58d45a9b89527b55861c5f2b225c7ba0b4284a42/src/vs/workbench/contrib/testing/browser/theme.ts#L13-L29

cc @connor4312

**Comment by misolori** [comment]
For verification, create an extension that uses the tree widget and assign one of the test colors to an icon like:

```ts
this.iconPath = new vscode.ThemeIcon('rocket', new vscode.ThemeColor('testing.iconFailed'));
```

You can also use my [sample extension](https://github.com/misolori/vscode-extension-playground/blob/master/src/treeView.ts#L90).
