### ISSUE TITLE
Toggle/Disable Real-time/Live Markdown Preview Updating

### ISSUE THREAD

**Issue by FruitSausage** [microsoft/vscode#129252]
Is there a feature to toggle real-time preview updating, or better to only update on save like LaTeX? For long files full of KaTeX math, real-time preview updating can significantly slow down the editor. I have tried regularly closing/reopening the preview as a workaround, but this steals focus from the editor.

**Comment by universemaster** [comment]
I found that the update speed when using katex got much worse after 1.55, so I still use that version https://code.visualstudio.com/updates/v1_55 .

With the extension https://marketplace.visualstudio.com/items?itemName=goessner.mdmath .

If you find the same, let us know.  I'd love to move the the latest version (with built in math rendering), but it's just too slow when writing math all day.

**Comment by FruitSausage** [comment]
@universemaster I noticed that too around that time but didn't realize it was due to a specific update.  I just tried reverting to 1.55, and it seems like the issue has been fixed as 1.55 was much slower than 1.60 for me, at least for large files (>1000 lines of math in my case).

My workaround at the moment has been opening a separate markdown file, editing a few hundred lines there, and then pasting them back into the main file.

**Comment by FruitSausage** [comment]
So I just discovered part of the slowness was having both the new built-in KaTex math renderer from 1.58 and the Markdown All in One extension trying to render the math at the same time.  This also seems to be why the preview would appear to refresh twice at times.

Some of the issues with running both are explained here:

https://markdown-all-in-one.github.io/docs/guide/compatibility.html#rendering-for-math-in-the-markdown-preview

https://github.com/yzhang-gh/vscode-markdown/issues/1010

https://github.com/yzhang-gh/vscode-markdown/issues/1008

@universemaster If you update, you could try disabling the built-in one with: `"markdown.math.enabled": false`
