### ISSUE TITLE
Extenal uri text is cropped

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#129233]
1. Create an extension that contributes https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider
2. When clicking on a link the dialog fails to show the links' text ( replaced by `...`)

![Screenshot (139)](https://user-images.githubusercontent.com/9638156/126771791-f84769b7-0a20-44bd-9758-b095209823ac.png)

**Comment by sbatten** [comment]
This was designed to prevent extremely long auth urls from creating a bad experience. we always try to show the full url before query parameters to give users enough info to answer the question.
