### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by debdutta47** [microsoft/vscode#129213]
We have written the needed data into your clipboard because it was too large to send. Please paste.
![Capture](https://user-images.githubusercontent.com/87472892/126737976-e760e6e4-c9d7-4969-b9f2-e14f9934bd94.PNG)
mssql: Error 2: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by lszomoru** [comment]
Could you please file this issue agains [the extension's repository](https://github.com/Microsoft/vscode-mssql)? Thanks!
