### ISSUE TITLE
Enter key non-functional

### ISSUE THREAD

**Issue by melanierichards** [Microsoft/vscode#12929]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14937

Steps to Reproduce:

1. Open a current or new file, doesn't matter what file type it is.
2. Press enter, hold and press enter, press enter a thousand times in a row, toggle "Insert" button, no response. This applies to the main enter key and the one on the number pad.

Enter key works in all other programs. All other keys work in VS Code. I'm on a desktop PC w/ a Bluetooth keyboard.

**Comment by robmikh** [comment]
I'm able to reproduce the same issue on both the stable and today's insider builds. Not only do other applications work correctly, other electron based applications do as well. It seems to be specific to Visual Studio Code. I'm on a desktop running Windows 10 insider builds with a normal USB keyboard.

**Comment by joaomoreno** [comment]
Wait, what? You can't press <kbd>Enter</kbd>?

Does it reproduce without any extensions running? Use `--disable-extensions` for that.

**Comment by robmikh** [comment]
Yes, that's exactly it. Curiously, Ctrl+Enter works but is insufficient as a work around.

I'll give that a shot when I'm back at my desk. But when I tried the vscode insider build I didn't have any extensions installed and it reproed.

**Comment by robmikh** [comment]
I launched with `--disable-extensions` and it still repros for me.

**Comment by melanierichards** [comment]
I can still repro it with `--disable-extensions`. Curiously, it launches as `v.1.2.1` when I do that; otherwise it's `v1.5.3`. fwiw I don't think I had any extensions installed. If I search for Code under "Programs and Features", I see version 1.5.3.

I'm also on internal preview builds (I'm on Web Plat if you need to look me up internally).

Like @robmikh, can use `ctrl+enter` as a workaround.

**Comment by robmikh** [comment]
I'm on an internal thread and this is likely not a Visual Studio Code bug.

**Comment by bpasero** [comment]
@melanierichards @robmikh anything in the console when enter does not work? 

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Does it reproduce in insiders? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by joaomoreno** [comment]
> this is likely not a Visual Studio Code bug

What makes you say that?

**Comment by zhengbli** [comment]
I see the same thing. I have to press enter like 10 times for it to work

**Comment by bpasero** [comment]
@zhengbli in 1.5.x or insider release?

**Comment by zhengbli** [comment]
Commit c94c82, 1.6-insiders.

The strange thing is with the same build, I have the issue on my desktop but not on my laptop, all windows 10 64 bit. Investigating.

**Comment by zhengbli** [comment]
I guess it could be a windows 10 problem :) I am using a internal windows 10 build, and it looks like the other two reporters are both Microsoftees.

**Comment by joaomoreno** [comment]
Can any of you guys try installing it in a non-internal windows build and see if you can reproduce it?

**Comment by melanierichards** [comment]
Output from console. I've replaced possibly-sensitive filepaths with `[project path]` and `[git submodule path]`. This is what prints when I press enter several times.

```
[File Watcher] [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher] [ADDED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [ADDED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher] [ADDED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [ADDED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher] [ADDED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [ADDED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher] [ADDED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [ADDED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher]  >> normalized [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [git submodule path]
csharpWatcherService.ts:71 [File Watcher] [ADDED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
csharpWatcherService.ts:71 [File Watcher] [ADDED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [git submodule path]index.lock
csharpWatcherService.ts:71 [File Watcher] [DELETED] [project path].git\index.lock
csharpWatcherService.ts:71 [File Watcher] [CHANGED] [project path].git
```

Interestingly, `code --verbose` launches the program as 1.2.1 instead 1.5.3 (just as `code --disable-extensions` does).

Will try an insider Code build next; will try on a public Windows build tonight.

**Comment by melanierichards** [comment]
The version discrepancy might have been due to the fact that I had Code installed on both the C and E drives somehow; deleted the one on the C drive. @bpasero I downloaded the version from the insiders link you sent but it doesn't fix it and doesn't actually seem to be a higher version (still 1.5.3). Is that the version you expected?

**Comment by robmikh** [comment]
The change that regressed this in Windows has been found and is now being fast tracked. Is there an alias for the VS code team you'd like me to add to the thread?

**Comment by joaomoreno** [comment]
This doesn't seem to be a Code issue.

**Comment by melanierichards** [comment]
Thanks for looking into it!

**Comment by ByronBeleris** [comment]
I fixed it in Macbook using
> fn + enter
