### ISSUE TITLE
Custom hint for the code actions bulb

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#129238]
It would be nice to have a possibility to change the hint for the code actions bulb. Code actions are often being used for other things except for code fixes. For example, in mongodb we would like to use it for partial playground execution: https://github.com/mongodb-js/vscode/pull/318

It can be confusing for users and prevent them from discovering the feature.

<img width="344" alt="125935285-b4e907ef-b334-4900-b18e-fec5aa2e06e5" src="https://user-images.githubusercontent.com/16307679/126779073-8a540455-5091-417c-994a-7f925beb10d3.png">

Maybe there's a way already how to do it, but I didn't find the API?

**Comment by mjbvz** [comment]
I'm going to update the tooltips to be more generic

I don't think we can easily make this customizable by extension since multiple extensions can contribute code actions

**Comment by alenakhineika** [comment]
Thank you, it totally works for us!
