### ISSUE TITLE
vs code has an error in math function specifically power function and addition

### ISSUE THREAD

**Issue by DakshMeghawat** [microsoft/vscode#129258]
153 is an armstrong number but with my programme i am unable to verify it  in visual studio but if i run the same code in another compiler it is working well and it is showilg 153 is armstrong number.
here is the following code :
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
int main()
{
    system("cls");
    long long n1,n2,a,b,c=0,count=0,flag;
    printf("Enter two numbers => \n");
    scanf("%lld%lld",&n1,&n2);
    printf("List of numbers are => n2 = %lld \n",n2);
    system("cls");
    while(n1<=n2)
    {
    count=0;
    a=n1;
    b=0;
    c=0;
    while(a!=0)
    {
        a=a/10;
        count++;
    }
    //printf("for %lld value of count is => %lld \n",n1,count);
    a=n1;
    flag=0;
    //system("cls");
    while(a!=0)
    {
        b=a%10;
        c=c+pow(b,count);
        printf("b= %lld and c=> %lld \n",b,c);
        a=a/10;
    }
   // printf("for %lld value of c is => %lld \n",n1,c);
    /*if(n1==c)
    {
       printf("%lld \n",n1);
    }
    //printf("%lld \n",n1);*/
    ++n1;
    }
}

**Comment by weinand** [comment]
Are you talking about Visual Studio or Visual Studio Code?
