### ISSUE TITLE
scm stash icon is inconsistent

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#129264]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/2230985/126828065-f0ae85f3-b5af-416a-ae5b-8cb75f6a3097.png">

Some nits on this:

- the "stash" icon is more bold than the discard icon
- stash is a safe action that stores your changes, while discard is a destructive icon. Side by side their icons are very similar, maybe stash should have something different, similar to this perhaps? https://iconmonstr.com/shipping-box-8-svg/

**Comment by IllusionMH** [comment]
Isn't this action from GitLens extension? [Code](https://github.com/eamodio/vscode-gitlens/blob/f6355932b33ccb6d65c8fab9875eddf60789915d/package.json#L3826-L3834)

**Comment by misolori** [comment]
This icon is from Gitlens, cc @eamodio
