### ISSUE TITLE
autopep8 Bug

### ISSUE THREAD

**Issue by G00Dway** [microsoft/vscode#129232]
Issue Type: <b>Bug</b>

Hi! I am a VS Code User! And I Found a Bug.. With Autopep8, When I Copy Something And Paste it II Got a File In my Projects, File Like: (dhf.py.394738374682kzes73.tmp) It Says "Formatting with autopep8" But It Stuck On This, It Stuck Like 3 Hours :(

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (3.33GB free)|
|Process Argv|--crash-reporter-id 13505088-1e2e-42d8-b17b-4c6fd154ea1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
converttoasciiart|Bit|1.0.3
bracket-pair-colorizer-2|Coe|0.2.1
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.5
vscode-language-pack-ru|MS-|1.58.8
csharp|ms-|1.23.13
mssql|ms-|1.10.1
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.8.0
ruby|reb|0.28.1
vscode-ruby|win|0.28.0
material-theme|zhu|3.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by irfanka** [comment]
Not just `autopep8`, same thing happens with `black`. Tested on Ubuntu as well as MacOs.
