### ISSUE TITLE
Send feedback dialog doesn't provide correct affordances

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12926]
Testing https://github.com/Microsoft/vscode/issues/12519

Hyperlinks should be underlined when hovering in Other ways to contact us box
![image](https://cloud.githubusercontent.com/assets/762848/18927353/6751c2b0-8570-11e6-977f-05eb153d7949.png)

Wrong cursor when hovering over tweet button, and also button should look depressed (physically, not emotionally)
![image](https://cloud.githubusercontent.com/assets/762848/18927393/8ee48d44-8570-11e6-8b6e-a894ebfe8a6f.png)

Similar to #12847, the selection cursor is appearing for unselectable text 
![image](https://cloud.githubusercontent.com/assets/762848/18927575/56518bb6-8571-11e6-876d-eae138819929.png)

Additionally, we should consider outlining the dialog itself to better differentiate from the background
![image](https://cloud.githubusercontent.com/assets/762848/18927480/0749d168-8571-11e6-8a06-83e47afa506f.png)

**Comment by joaomoreno** [comment]
This would make a great PR!

**Comment by bpasero** [comment]
The tweet button is disabled, thats why the cursor looks like that. You need to type text to make it different.

**Comment by wprater** [comment]
FYI, Im only seeing the href underline issues on current insiders build.  I have a quick PR to fix that, however, when does the feedback face showup?

**Comment by bpasero** [comment]
@wprater you need to patch the product.json a little bit to make it show:

Add:

```json
"sendASmile": {
		"reportIssueUrl": "https://go.microsoft.com/fwlink/?LinkId=534872",
		"requestFeatureUrl": "https://go.microsoft.com/fwlink/?LinkID=533482"
	},
"requestFeatureUrl": "https://go.microsoft.com/fwlink/?LinkID=533482",
	"reportIssueUrl": "https://go.microsoft.com/fwlink/?LinkId=534872"
```
