### ISSUE TITLE
Use LSP in Powershell integrated terminal for highlighting

### ISSUE THREAD

**Issue by 4086606** [microsoft/vscode#129259]
Currently the integrated Powershell terminal uses the ANSI color hues provided by the default theme. This leads to less than optimal color highlighting compared to Powershell scripts.

<img alt="image" src="https://user-images.githubusercontent.com/82655227/126819232-fc63ac24-ae5c-49b0-ad8a-a98dbbce651e.png" height="260px" />

**Comment by Tyriar** [comment]
This isn't possible, it would need to be powershell telling our terminal how to display the right colors via ANSI colors. Also you're on a very old version of powershell so maybe upgrading will improve the experience?

**Comment by 4086606** [comment]
I actually figured out a workaround using `Get-PSReadlineOption` and `Set-PSReadLineOption -colors @{ Command = "Green"}`

**Comment by Tyriar** [comment]
Nice, I'd still recommend moving to pwsh 7 as you seem to be on 5

**Comment by 4086606** [comment]
also done, thanks for the heads up

**Comment by SNDST00M** [comment]
Late reply but huge thanks for recommending pwsh 7, I'm loving the convenience of `&&`
