### ISSUE TITLE
Folders should only open/close when clicking on chevron

### ISSUE THREAD

**Issue by tsongas** [microsoft/vscode#129217]
Issue Type: <b>Feature Request</b>

In the file explorer, clicking on a folder name opens or closes the folder, making it impossible to, for example, select a folder to add a file to that folder, without then having to re-open the folder. This is absolutely aggravating. Only clicking on the chevron next to the folder name should open/close the folder. Making the folder open/close when clicking anywhere on that line is the worst case of UI/UX gone awry I can think of in any modern application I use daily.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
`"workbench.tree.expandMode": "doubleClick"`

**Comment by tsongas** [comment]
@gjsjohnmurray I'm naming my first born child after you.
