### ISSUE TITLE
Can't debug main process on ubuntu

### ISSUE THREAD

**Issue by yinhunfeixue** [microsoft/vscode#129230]
![2021-07-23 17-42-00屏幕截图](https://user-images.githubusercontent.com/29660825/126764702-40d76da7-db51-4785-b279-a0199599c56a.png)

![2021-07-23 17-39-43屏幕截图](https://user-images.githubusercontent.com/29660825/126764468-8be64b7a-b98b-439d-8ee4-78ac771e656e.png)

hello

After `yarn watch`，I Want to debug the main process，Operation as shown in the picture.

It was successful in MacOS, but failed in Ubuntu， In Ubuntu, breakpoints are not entered.

How to debug in Ubuntu? thanks

**Comment by weinand** [comment]
How are you debugging? Which launch configuration (in launch.json) are you using?

**Comment by yinhunfeixue** [comment]
> How are you debugging? Which launch configuration (in launch.json) are you using?
this one
	
"name": "Main Process",

**Comment by connor4312** [comment]
It looks like the main process doesn't start for you, the "call stack" view is empty. Make sure that VS Code is correctly set up and that you can launch it outside of the debugger.

**Comment by yinhunfeixue** [comment]
> Please collect trace logs using the following instructions:
> 
> > If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
> > warning This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to [connor@xbox.com](mailto:connor@xbox.com)

Hello, This is the logs

[vscode-debugadapter-4a308ed7.json.gz](https://github.com/microsoft/vscode/files/6875004/vscode-debugadapter-4a308ed7.json.gz)

**Comment by yinhunfeixue** [comment]
> It looks like the main process doesn't start for you, the "call stack" view is empty. Make sure that VS Code is correctly set up and that you can launch it outside of the debugger.
-------------------
It can be started successfully, but the main process cannot be debugger (it can be on Mac OS, but not on Ubuntu)

**Comment by yinhunfeixue** [comment]
> /jsDebugLogs

this file?

> Verbose logs are written to: /tmp/vscode-debugadapter-4a308ed7.json.gz


[vscode-debugadapter-4a308ed7.json.gz](https://github.com/microsoft/vscode/files/6875031/vscode-debugadapter-4a308ed7.json.gz)

**Comment by peter-dolkens** [comment]
Our team had a similar sounding issue this week, and eventually found this workaround:

> The built in Node Debug extension `ms-vscode.node-debug2` is default using a new version of the js debugging extension as of a new update. Even rolling back vscode seems to use the new Node Debug extension. For whatever reason, that's broken the breakpoints in my services. The solution was to revert to the old behaviour by adding this to my vscode/settings.json
`"debug.javascript.usePreview": false`

**Comment by connor4312** [comment]
@peter-dolkens as posted elsewhere your issue is not related

**Comment by connor4312** [comment]
I can repro on Windows. @deepak1556 it seems like this might be something with the Electron that we grab, it works with https://github.com/abartho/electron-typescript-vscode on Electron 13 with the same launch config. But it seems our electron doesn't get the NODE_OPTIONS/bootloader wired in like vanilla Electron does.

**Comment by deepak1556** [comment]
Electron will filter `NODE_OPTIONS` when packaged https://github.com/electron/electron/blob/main/docs/api/environment-variables.md#node_options, before Electron 12 this filter was not working so all options would be allowed. But it has been addressed via https://github.com/electron/electron/pull/29419

Currently a application is determined to be packaged if the executable name is different than `electron.exe`, which is the case on windows and linux. On macOS we haven't renamed the executable that is why the user is able to debug it.

What `NODE_OPTION` is needed for use case ? I will see if it can be allowed in the filter.

**Comment by connor4312** [comment]
Huh, interesting. The debugger uses `--require` to inject the debugger bootloader. While there is a workaround that we use to debug Deno for example, it's a little less reliable and feature-ful than the bootloader.

**Comment by deepak1556** [comment]
`--require` will remain filtered in upstream electron as a security measure. Some untrusted content that launches application via external uri should not be able to inject scripts. Is it the only way to inject bootloader ? Can it be bundled into core and run when debugger kicks in ?
