### ISSUE TITLE
extensions not loaded on start up

### ISSUE THREAD

**Issue by nithinsinkaran** [microsoft/vscode#129249]
Issue Type: <b>Bug</b>

Dear Team

I have a few sales force extensions on my VS code and it take a while for them to load. somethimes over 10 minutes. If I have more than one instace opened, it some times failes to load. I checked the loaded extensions which would show blank entires. Is there a way for me to manually run the extentions? Pleas advise.

Regard
Nithin

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.35GB free)|
|Process Argv|--crash-reporter-id 280c4cca-8fda-4bdd-90f5-85be0264d4e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
jupyter|don|1.1.6
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
lana|Fin|1.3.5
vscode-npm|fkn|3.3.0
vscode-pull-request-github|Git|0.28.0
r|Iku|2.1.0
search-node-modules|jas|1.3.0
apex|Joh|1.0.4
r|Mik|0.0.25
azure-pipelines|ms-|1.188.1
vscode-azureappservice|ms-|0.22.0
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.0
vscode-bicep|ms-|0.4.451
vscode-cosmosdb|ms-|0.18.0
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.13
vscode-dotnet-runtime|ms-|1.2.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.7.1053846006
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.2.1
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.15.2
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
vscode-yaml|red|0.21.1
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.7
salesforcedx-vscode|sal|52.5.0
salesforcedx-vscode-apex|sal|52.5.0
salesforcedx-vscode-apex-debugger|sal|52.5.0
salesforcedx-vscode-apex-replay-debugger|sal|52.5.0
salesforcedx-vscode-core|sal|52.5.0
salesforcedx-vscode-lightning|sal|52.5.0
salesforcedx-vscode-lwc|sal|52.5.0
salesforcedx-vscode-visualforce|sal|52.5.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.5
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by alexdima** [comment]
@nithinsinkaran Having extensions start up in over 10 minutes is not normal. This sounds like a problem with the extensions themselves, please open an issue directly against the problematic extensions.
