### ISSUE TITLE
Extraneous <global> symbol from Salsa

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12936]
Testing #12598 

![image](https://cloud.githubusercontent.com/assets/762848/18931439/088f3a1c-8581-11e6-8a79-17b54f6a4aeb.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11230

**Comment by waderyan** [comment]
@dbaeumer what do you think about filtering this out? Per @mhegazy's [comments](https://github.com/Microsoft/TypeScript/issues/11230#issuecomment-250335160).

**Comment by dbaeumer** [comment]
@waderyan: we can do this. However I want to understand why this is in in the first place since we ask for symbols for a specific document.

**Comment by dbaeumer** [comment]
Tried a work around on our end but there is more broken. See https://github.com/Microsoft/TypeScript/issues/11230#issuecomment-250429110

**Comment by dbaeumer** [comment]
Fixed it for 1.7.
