### ISSUE TITLE
Test: Injected Text Adoption For Inline Suggestions

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#129383]
Refs 

- [x] anyOS @isidorn
- [x] anyOS @TylerLeonhardt

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129383%0A%0A)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129383%0A%0A&assignees=hediet)

---

Inline Suggestions now use the new Injected Text feature of the core editor.
This fixes some issues that inline suggestions had and enables line wrapping of inline suggestions.

# Prep

Install the copilot extension.

# Testing

Play around with copilot and verify that

* the cursor is never inside of an inline suggestion
* When wrapping is enabled, long inline suggestions are wrapped correctly
* Hover works correctly on ghost text
* There are no weird UI artifacts.

**Comment by TylerLeonhardt** [comment]
I've pretty much finished testing this item but since the steps are "use copilot" I'm not gonna unassign myself yet and will just give it another day of testing since it's easy to test.
