### ISSUE TITLE
Update UI of Visual Studio Code like the new Windows 11 UI

### ISSUE THREAD

**Issue by ShaunakSawant** [microsoft/vscode#129372]
I would like to suggest a new UI for VSCode which matches the Windows 11 UI, I think it looks great and would be nice to see it if implemented.

A user on Reddit made a perfect example of what I am suggesting in the post which is linked below:
[https://www.reddit.com/r/Windows11/comments/orbgzl/visual_studio_vs_code_and_github_desktop_with/](https://www.reddit.com/r/Windows11/comments/orbgzl/visual_studio_vs_code_and_github_desktop_with/)

I am also attaching images from that post for this suggestion below:
![image](https://user-images.githubusercontent.com/69911775/126942849-a309de0a-d565-4fc0-8951-23e51f97114c.png)
![image](https://user-images.githubusercontent.com/69911775/126942866-43212643-877d-40d6-b456-9ea38d7d4361.png)

**Comment by CodeCrazy-ywt** [comment]
Wow, that's amazing!!! 😆

**Comment by misolori** [comment]
Thanks for the feedback. Please see https://github.com/microsoft/vscode/issues/115641 where we are tracking a similar request. Will be closing this one as a duplicate.
