### ISSUE TITLE
we cannot connect to the extensions marketplace

### ISSUE THREAD

**Issue by nafzaa** [microsoft/vscode#129346]
Issue Type: <b>Bug</b>

no connect marketplane linux visual studio code 

VS Code version: Code - OSS 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-12T23:51:36.303Z)
OS version: Linux x64 5.13.4-zen2-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 3512)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.63GB (1.79GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by mo3head** [comment]
Same problem here:
Linux dennis-xps137390 5.10.52-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:32:02 UTC 2021 x86_64 GNU/Linux
[sinnedb@dennis-xps137390 ~]$ code --version
vscode 1.58.0 2d23c42a936db1c7b3b06f918cde29561cc47cd6 x64

![image](https://user-images.githubusercontent.com/10432047/126911871-1d46a49d-cbbc-44de-91c6-d56345b4ae79.png)

**Comment by sandy081** [comment]
duplicate of #128583
