### ISSUE TITLE
Test automatic import folding

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#129359]
Refs: https://github.com/microsoft/vscode/issues/128809

- [x] anyOS @weinand
- [x] anyOS @andreamah

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129359%0A%0A&assignees=aeschli)

---

Use the setting `editor.foldingImportsByDefault` to have import statements folded when a file is opened. The fold state is remembered once a file has been opened once and had an import fold. The feature works with TypeScript, JavaScript, Java, C# and C++ and with all language that have a folding range provider that annotates import statements with `FoldingRangeKind.Imports`.

Test that the feature works.

**Comment by gjsjohnmurray** [comment]
Current description of the setting:

![image](https://user-images.githubusercontent.com/6726799/126909110-37264cd3-b9a7-443b-a4b8-deda011c5811.png)

It surprised me that the description itself doesn't mention imports. Nor is it clear about the behaviour. It seems that when set, the first time I open a file containing imports the imports get folded automatically. Then the state of this block gets remembered across subsequent close and reopen (on my workspace/folder?). So if I expand it, close the file and reopen it the imports return expanded. May be challenging to convey all of this in a concise settings description, but perhaps the current text can be improved.

**Comment by weinand** [comment]
I agree with @gjsjohnmurray: the description needs to be improved:
My suggestion:
> Controls whether the editor automatically collapses import ranges.

**Comment by weinand** [comment]
I've tested this on macOS for JS, TS, C++, C#, and Java. Found now issues other than the description wording.

**Comment by andreamah** [comment]
Looks good! Tested on Windows for TS, JS, Java, C#, and C++. Nothing to note other than the issue I left.
