### ISSUE TITLE
Improve the "We cannot connect to the Extensions Marketplace at this time" message

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#129362]
Issue Type: <b>Feature Request</b>

Many GH issues currently being opened about this message are from people using a VS Code build which doesn't point to `marketplace.visualstudio.com`

![image](https://user-images.githubusercontent.com/6726799/126914312-5ad92f64-a98c-433b-b0d8-61b934732f74.png)

I suggest the error message is extended so it reports the URL it was trying to connect to,

VS Code version: Code - Insiders 1.59.0-insider (04485223ebc6a075f39966bf9b3e261359ac7818, 2021-07-23T19:21:12.120Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
My suggestion: change the text into "We cannot find any extension related to 'xxx'. Please check your spelling and try again."

**Comment by CodeCrazy-ywt** [comment]
@vscodebot I'm afraid these two issues arn't the same. :-/

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/119375

**Comment by gjsjohnmurray** [comment]
@sandy081 I don't think this is a duplicate of the one you referenced. In this one I am suggesting you enhance the text of the "cannot connect" message so it shows us whether the connection attempt was to the Microsoft Marketplace or to another one.

**Comment by sandy081** [comment]
@gjsjohnmurray Fix in the other issue, I changed it to show the real cause of the error instead of this general message. So now, user will know what is the real error and understand and share it while filing an issue.
