### ISSUE TITLE
Key ( c ) is not showing while typing 

### ISSUE THREAD

**Issue by Kshitij0419** [microsoft/vscode#129331]
In VS CODE , key ( C ) is not a command . the key combination , searching for chords etc are cames while typing letter "c" plz help me soon i am unable to solve any code here

**Comment by Kshitij0419** [comment]
i have see that but that was useless plz any other setting from which i may chnge ans type c

**Comment by gjsjohnmurray** [comment]
Sounds like you have a bad keybinding. Please follow the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues
