### ISSUE TITLE
Forwarding a port of remote extension.

### ISSUE THREAD

**Issue by Xuan-Yu-San** [microsoft/vscode#129365]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.2
- OS Version: MacOS High Sierra 10.13.6

I'm not sure where to give feedback.
This is a question about remote extension.
It says in your document
"A notification will tell you the localhost port you should use to access the remote port. For example, if you forwarded an HTTP server listening on port 3000, the notification may tell you that it was mapped to port 4123 on localhost since 3000 was already in use. You can then connect to this remote HTTP server using http://localhost:4123."
But the port of my remote Mongo service is always mapped to 27017, even if 27017 is occupied.

**Comment by alexr00** [comment]
This documentation looks like it's about automatic port forwarding, where we try to make the remote port that your service is running available on your local machine.

The Mongo service you mention sounds like it's running on your remote machine. So if the port was auto forwarded then it may get the "matching" local port or it may not if it's already being used on your local machine.
