### ISSUE TITLE
Go To Line / Column: Wait until user finishes entering in line number to move editor view

### ISSUE THREAD

**Issue by Datrinon** [microsoft/vscode#129313]
Hello, I thought it would be nice if when you used the Go to Line / Column function, the editor waited for you to finish entering in a number before jumping to that line. I find it a bit disorienting when the editor jumps around as I type in a number.

Could you guys add in an option to wait for the user to press ENTER to confirm the line number before the editor moves? Like
Like how Intellij has you press OK/Enter before it jumps a line.
![image](https://user-images.githubusercontent.com/34661945/126882165-37a39070-88c4-404f-86dc-06e85d349e29.png)

Thank you for reading!

**Comment by bpasero** [comment]
//cc @TylerLeonhardt
