### ISSUE TITLE
Out of viewport notebook cells fail to blur

### ISSUE THREAD

**Issue by wangweixuan** [microsoft/vscode#129354]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.58.2
- OS Version: macOS 11.5

Steps to reproduce:

1. In a notebook, focus on a markdown cell ("A") and switch to edit mode. Make sure it contains the cursor.
2. Scroll cell A out of viewport.
3. Focus on another cell ("B"). Optionally, add a cursor in cell B.
4. Scroll cell A back into viewport.
5. Observe.
**Expected:** cell A is blurred, cell B has focus. Cell B also preserves the cursor if added.
**Actual:** cell A has focus and cursor.

Another experiment:

1. In a notebook, focus on a code cell ("C") instead. Make sure it contains the cursor.
2. Scroll cell C out of viewport.
3. Focus on another cell ("D").
4. Scroll cell C back into viewport.
5. Observe.
**Expected:** cell C is blurred, cell D has focus.
**Actual:** cell D has focus (responses to <kbd>Tab</kbd>). However, the editor in cell C still has highlighted border.

https://user-images.githubusercontent.com/24620923/126906559-d1836ffe-866d-4ea0-ad40-b7ebee5e57ba.mov

**Comment by rebornix** [comment]
I think this is a duplicate and @roblourens already had a fix.

**Comment by roblourens** [comment]
#129432
