### ISSUE TITLE
Test new fold navigation commands

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#129353]
Refs: https://github.com/microsoft/vscode/issues/91023

- [x] anyOS @donjayamanne
- [x] anyOS @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129353%0A%0A&assignees=aeschli)

---

Test the new `Goto Previews/Next/Parent` commands
- assign keyboard shortcuts to the new fold navigation commands
e.g.
```
[
	{
		"key": "ctrl+k ctrl+,",
		"command": "editor.gotoToNextFold"
	},
	{
		"key": "ctrl+k ctrl+.",
		"command": "editor.gotoToPreviousFold"
	},
	{
		"key": "ctrl+k ctrl+;",
		"command": "editor.gotoToParentFold"
	}
]
```
- set cursor to a location in a fold and verify that the commands are useful

**Comment by DonJayamanne** [comment]
I came across the same issues filed here https://github.com/microsoft/vscode/issues/129503.
The tests didn't pass for me
