### ISSUE TITLE
`$returnValue` references not working in conditional breakpoint expressions

### ISSUE THREAD

**Issue by jbriales** [microsoft/vscode#129328]
Issue Type: <b>Bug</b>

When using `$returnValue` in a conditional breakpoint expression, this does not seem to work (condition never evaluates to true).

E.g. in
```js
function foo() {
  return true; // BREAKPOINT HERE, expression: `$returnValue`
}
foo()
```
I tried adding a logpoint with content `{$returnValue}` and that works,
BUT a conditional expression `$returnValue` does NOT work.

I created the breakpoint at the end of the line, so `$returnValue` is available at the location.

A similar issue was previously raised for logpoints in https://github.com/microsoft/vscode/issues/94094
and that seems to have been fixed.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.11.22-100.fc32.x86_64 snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 2|
|Memory (System)|23.23GB (2.18GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3-gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|i3-gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
cquery|cqu|0.1.10
vscode-eslint|dba|2.1.23
viml|dun|0.1.7
graphviz-preview|EFa|1.5.0
jbockle-format-files|jbo|3.3.0
goto-next-previous-member|mis|0.0.5
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
vscode-js-profile-flame|ms-|0.0.21
copy-json-path|nid|0.2.0
bash-debug|rog|0.3.9
gitblame|wad|8.1.0
change-case|wma|1.0.0
clang-format|xav|1.9.0
current-file-path|Yos|3.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by connor4312** [comment]
This was actually something we never supported. But we will in the next [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) 🙂

**Comment by rchiodo** [comment]
@connor4312 I had some questions.

Does this only work in typescript/javascript for node?

Does it work with async functions?

**Comment by connor4312** [comment]
Yea this is in the js debugger. It _does_ work in async functions, but the returnValue here is the Promise that's being returned. Since awaits/async callbacks are not possible in conditional breakpoints or log points, this is not useful.

**Comment by rchiodo** [comment]
What about WSL? I can't seem to get any logpoints to work in WSL so maybe that is something different.

**Comment by connor4312** [comment]
Can you https://gifcap.dev what you're doing?

**Comment by rchiodo** [comment]
Was related to my launch.json.

Had to use this in the config:

```
            "name": "Extension",
            "type": "pwa-extensionHost", <-- Has to say pwa-extensionHost (at least until tomorrow's build)
            "request": "launch",
```
