### ISSUE TITLE
load picture error,can't display picture

### ISSUE THREAD

**Issue by Kimtaehung123** [microsoft/vscode#129377]
Issue Type: <b>Bug</b>

in the local,everything is ok.But in the remote connection, something is wrong,eg,picture load error,jupyter notebook markdown's hyperlink picture doesn't show.

![](http://r.photo.store.qq.com/psc?/V538xEDz3QAs2s3S63e53w6ipX1xnA6f/45NBuzDIW489QBoVep5mcaL.xpXLfiSWsfaAqCEBpTy7b81Aw6B3YQ4fA5LTap2oP*5hYpSTqtefwADDecqHnVMObzD7i6EGwS7w12NnNfg!/r)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.84GB (12.18GB free)|
|Process Argv|--crash-reporter-id 89c9936e-1197-4780-82a5-c26b3eee0912|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: 北化计算平台|
|OS|Linux x64 4.18.0-26-generic|
|CPUs|Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz (4 x 2699)|
|Memory (System)|10.00GB (2.62GB free)|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-great-icons|emm|2.1.79
file-icons|fil|1.0.29
h5-code|gre|0.0.4
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-zh-hans|MS-|1.58.8
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
ayu|tea|0.20.1
latex-support|tor|3.8.0
vscode-icons|vsc|11.5.0
jinja|who|0.0.8
material-theme|zhu|3.11.1
tinypng|and|1.0.0
vscode-django|bat|1.6.0
vscode-office|cwe|2.3.1
vscode-markdownlint|Dav|0.42.1
docs-images|doc|0.0.9
python-extension-pack|don|1.6.0
vscode-optimize-images|fab|1.1.1
matlab|Gim|2.0.1
nbpreviewer|jit|1.2.2
pdf|k5h|4.2.3
vsc-python-indent|Kev|1.14.2
vscode-github|Kni|0.30.6
MagicPython|mag|1.1.0
vscode-fileheader|mik|0.0.2
file-downloader|min|1.0.11
mindaro|min|1.0.120210709
vscode-language-pack-zh-hans|MS-|1.58.8
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
autodocstring|njp|0.5.4
vscode-yaml|red|0.21.1
jupyter-notebook-vscode|sam|0.0.2
language-stylus|sys|1.11.0
pdf|tak|0.6.1
python|tht|0.2.3
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8
eno|Wsc|2.3.53
txt-syntax|xsh|0.1.6

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If so, please share details about the image file, such as its path so we can try to reproduce this
