### ISSUE TITLE
`files.defaultLanguage` doesn't work on reload.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#129396]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.2
- OS Version: win10 20h2

Steps to Reproduce:

https://user-images.githubusercontent.com/26390254/126984319-cd127102-49d9-46ce-997b-8fd67b72d0dd.mp4

**Comment by lszomoru** [comment]
@bpasero, @lramos15 seems like the untitled file icon does not honour the default language setting.
