### ISSUE TITLE
Writing login information to the keychain failed

### ISSUE THREAD

**Issue by NotDiamondZ** [microsoft/vscode#129364]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
- OS Version: Linux Debian v5.4.109-26094-g381754fbb430

Steps to Reproduce:
Not sure.

**Comment by justingolden21** [comment]
![Screenshot 2021-07-26 12 08 24 AM](https://user-images.githubusercontent.com/30274440/126947380-0a53b4d7-0590-4282-ac52-e5ff19343319.png)

Same here, just freshly installed vscode on debian

**Comment by TylerLeonhardt** [comment]
do you have gnome-keyring installed?

**Comment by TylerLeonhardt** [comment]
@NotDiamondZ do you have the same exact error as @justingolden21? Word for word?

**Comment by justingolden21** [comment]
I'm not sure what the other error is word for word, but I've posted my screenshot so you can see it. Everything seems to work fine in VS code, I don't know what I did to cause it, so I'm probably not of much help.

**Comment by NotDiamondZ** [comment]
Yes

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by NotDiamondZ** [comment]
I try installing it but it says I hold broken packages.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by NotDiamondZ** [comment]
> @NotDiamondZ do you have the same exact error as @justingolden21? Word for word?

Yes


> do you have gnome-keyring installed?

I try but this is the error I get:
![Screenshot 2021-07-27 1 49 40 PM](https://user-images.githubusercontent.com/83427897/127211194-4d58ce03-256b-4244-b58a-3cef67fb534c.png)

**Comment by justingolden21** [comment]
It says you have "broken packages," maybe the good old "turn it off and on" by uninstalling and reinstalling your packages?

Just an idea, I'm no tech support for this lol

**Comment by NotDiamondZ** [comment]
And how do I know what packages I have? Actually, I'll Google it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by NotDiamondZ** [comment]
I'm just going to reinstall the entire system

**Comment by NotDiamondZ** [comment]
Works!
