### ISSUE TITLE
Folder lat modified upon saving file

### ISSUE THREAD

**Issue by neobie** [microsoft/vscode#129347]
Request feature for modifying last modified of parent folder upon saving file too.
This will be easier for coders to know which folders contain files which have been modified recently.

**Comment by isidorn** [comment]
`	"explorer.sortOrder": "modified"`

**Comment by neobie** [comment]
You misunderstood what I need and closed the file. 
Upon saving a file in Folder A, I need the Folder A modified time to be updated as well.
