### ISSUE TITLE
Promblem with removing brackets or quotes

### ISSUE THREAD

**Issue by CryUshio** [microsoft/vscode#129375]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Open a `.ts` file
2. See this apng

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30655354/126951434-9973f8cf-efe7-4f87-bec7-1ddf3db2c169.png)

Expected that a pair of brackets or quotes can be deleted.

**Comment by hediet** [comment]
Does this also happen when all extensions are disabled?

**Comment by CryUshio** [comment]
@hediet Yes I disabled all extensions but the problem still exists.

**Comment by hediet** [comment]
It is not very easy to see what is going on in your gif (are you pressing arrow left or backspace?).
Can you explain what the issue is?

**Comment by CryUshio** [comment]
@hediet You can try to move the cursor out of the brackets first, then move the cursor to the middle of the bracket and press 
 the backspace:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/30655354/126966098-33e85401-a133-4655-bdfd-12df656034d8.png)

**Comment by hediet** [comment]
This looks as designed. Automatically inserted parentheses are not removed anymore when the cursor position was changed manually.

**Comment by CryUshio** [comment]
@hediet But this problem does not occur in previous versions.

**Comment by hediet** [comment]
You are right. Interesting.

**Comment by CryUshio** [comment]
It is indeed a practical function, isn't it?

**Comment by hediet** [comment]
I think this was introduced with https://github.com/microsoft/vscode/commit/270109115a74dee1aba8bf687b7be4995a723db0 to fix #118270.

I leave it to @alexdima to decide if this is a bug or a feature.

**Comment by alexdima** [comment]
It looks like you want to configure `"editor.autoClosingDelete": "always"`.
