### ISSUE TITLE
Quick open highlight is not working when including wildcards

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1293]
Notice how the matching is wrong in the following screenshot. I would expect some files being matched inside the browser folder. 

<img width="604" alt="screen shot 2015-12-14 at 16 41 47" src="https://cloud.githubusercontent.com/assets/1926584/11785379/d80acc4a-a281-11e5-9310-69117e0c192e.png">

**Comment by bpasero** [comment]
I think the issue here is the wildcards, have to investigate.

**Comment by isidorn** [comment]
Yes, if I just use one * it behaves better
