### ISSUE TITLE
Ctrl+M doesn't work from markdown Preview window

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12939]
Testing #12519

Ctrl+M to toggle "Tab moves focus" mode does not work from File Preview window from markdown file - see below - while preview of `blah.md` is open, Ctrl+M does nothing
![image](https://cloud.githubusercontent.com/assets/762848/18931981/5d9a42ac-8583-11e6-8a9f-935a356fc10d.png)

**Comment by jrieken** [comment]
It should not do anything as the `tab moves focus` is for the editor in which tab usually does something else. For me the bug here is that the status bar still shows the tab-moves label even though no code editor is showing

**Comment by alexandrudima** [comment]
@jrieken "Tab moves focus" is no longer an editor instance specific thing. It is a big fat static that toggles it for all editors. I think the keybinding doesn't reach us as a limitation of the webview.

**Comment by jrieken** [comment]
@alexandrudima It actually does reach us but should I then manually focus the *next* thing? Today it focus things like links and elements of the webview...
