### ISSUE TITLE
List item indication when right clicking non selected item should change

### ISSUE THREAD

**Issue by williamlzw** [microsoft/vscode#129343]
Issue Type: <b>Bug</b>

Vscode deleting large files on remote server crashes.
68/5000 
Linux servers have a PTH file for PyTorch. When I select the file and select delete, vscode will first try to open the file, which causes the deletion to fail and crash. This PTH file is usually more than 50MB. I suggest vscode change its policy so that for binary files over 10MB on the remote server, instead of reading directly, there is an option to ask whether to read.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
Not sure if there is anything we can do here, but forwarding to @bpasero so he can decide if this can be improved in IO layer

**Comment by bpasero** [comment]
I do not fully understand, can you not right click and delete without opening the file firstß

**Comment by laizewei** [comment]
If I right-click on a file, it doesn't select the file I want to delete.

**Comment by bpasero** [comment]
![recording (1)](https://user-images.githubusercontent.com/900690/127865761-bd0decad-45cc-4bfb-80ec-a4170aef15e8.gif)

Works for me.

**Comment by laizewei** [comment]
It is recommended that the IDE right-click the project and change the selected color.

**Comment by bpasero** [comment]
Ok, so this is a totally different issue then about how we chose to present an entry in the list when you right click.

**Comment by misolori** [comment]
I'm a little confused, the original post mentions that vscode crashes when deleting large files on remote servers but then goes on talk about right-clicking files to change selected state. So are these two separate issues?

**Comment by laizewei** [comment]
Now right clicking on an item doesn't change the selection color, making me think right clicking won't select the item. So I left selected the project and deleted it, which caused vscode to crash.

**Comment by joaomoreno** [comment]
Right click changes the focus. Depending on whether you already have a selection, the delete operation on right click will always work on focus, expect if you right click on an element which is already selected, in which case it will operate on the entire selection.
