### ISSUE TITLE
vscode for Ipad

### ISSUE THREAD

**Issue by Teror864** [microsoft/vscode#129326]
I'm new for coding area,and I am a Chinese middle school student.I’m not rich enough to buy a computer like MacBook or Surface Laptop.But I have an IPad.I know it’s hard to build. But I’m sure you can do it.🤓😌
(Maybe my English is not good.Sorry😏)
                                                                                                                                              A Chinese student
                                                                                                                                                            2021.7.25

**Comment by matkoniecz** [comment]
offtopic a bit but may help you: What about PC/old laptop that can have Linux/Windows installed?

**Comment by adaex** [comment]
You can use the web version for development, download a chrome on the iPad, and then open [GitHub Codespaces](https://github.com/codespaces)。 However, codespaces is still in the public beta stage, and may need to apply before it can be used. I have some video screens to help you.

Chinese translation: 你可以使用网页版本进行开发，在iPad上下载一个chrome，然后打开[Github Codespaces](https://github.com/codespaces)。不过目前codespaces还在公测阶段，可能需要申请之后才能使用。我有一些录屏可以帮助你。

https://user-images.githubusercontent.com/29560987/126909568-660d5c45-c479-4b2b-ac11-f9d6136c1aef.mp4

**Comment by Teror864** [comment]
Ok, thanks.But my GitHub codespace is still waiting for passing the audit .
I submitted my request a week ago.😌
Ps:By the way, What country are you from?And how long does it take auditor to pass the audit?🤨

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/70764

**Comment by adaex** [comment]
> Ok, thanks.But my GitHub codespace is still waiting for passing the audit .
> I submitted my request a week ago.😌
> Ps:By the way, What country are you from?And how long does it take auditor to pass the audit?🤨

I started to use the public beta of codespaces last year. At that time, the audit was very fast and passed in a few days. As far as I know, it should be slow now. A friend of mine has applied for more than a month and is still waiting for approval.

**Comment by Teror864** [comment]
Ok,thanks for your help.I’ll go on waiting🤓😏😋.
