### ISSUE TITLE
Problem matcher wont clear

### ISSUE THREAD

**Issue by daominhhieu** [microsoft/vscode#129341]
Issue Type: <b>Bug</b>

Why is my customer problem matcher wont clear when build Task is restart?
```json
        "problemMatcher": {
          "fileLocation": "absolute",
          "pattern": 
          {
              "regexp": "^(.*)\\((.*)\\)\\s\\:\\s(Warning|Error)\\[(.*)\\:(.*)$",
              "file": 1,
              "line": 2,
              "severity": 3,
              "message": 5
          }
        }
```
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by daominhhieu** [comment]
The same problem keep piling up every time i re-run the build task
![image](https://user-images.githubusercontent.com/19222753/126898032-923c4b5a-9782-4a90-8f3b-6cce53505a12.png)

**Comment by alexr00** [comment]
Can you please share your whole task?

**Comment by daominhhieu** [comment]
This is my whole task
`"tasks": [
      {
        "label": "IAR Build",
        "type": "shell",
        "command": "\"C:\\IarBuild.exe\"",
        "args": [
          "\".\\IAR_RL78_IDE_Workspace\\project.ewp\"",
          "-build",
          "Debug",
          "-log",
          "info"
        ],
        "group": "build",
        "problemMatcher": {
          "fileLocation": "absolute",
          "pattern": {
            "regexp": "^(.*)\\((.*)\\)\\s\\:\\s(Warning|Error)\\[(.*)\\:(.*)$",
            "file": 1,
            "line": 2,
            "severity": 3,
            "message": 5
          }
        }
      }`

**Comment by alexr00** [comment]
Your task looks ok. I'm not able to reproduce this issue though. Do you have any other steps to repro the issue?

**Comment by daominhhieu** [comment]
I'm not sure. All I do is Ctrl + Shift + B to run this task,
I thought of clearing the Problems table first then run the build command as a work around solution. But so far, the only way to clear this table is close the VS window and re-open it....
Do you have any suggestion on this?

**Comment by alexr00** [comment]
It might be because your problems don't have an owner, so we don't know to clear them. Can you try adding an owner to your problem matcher? ex:

```json
"problemMatcher": {
  "owner": "typescript",
  "fileLocation": "absolute",
  "pattern": {
    "regexp": "^(.*)\\((.*)\\)\\s\\:\\s(Warning|Error)\\[(.*)\\:(.*)$",
    "file": 1,
    "line": 2,
    "severity": 3,
    "message": 5
  }
}
```

**Comment by daominhhieu** [comment]
alright thanks! all because I missing the owner, since I don't really understand what it's for, but it seems "typescript" is the right one for IAR compiler.
I'll close this issue.

**Comment by alexr00** [comment]
`owner` just give a group that the problems belong to so that when adding/removing problems we can tell if they're the same problem or not. I don't know much about `iarbuild.exe`, but maybe `docker` or `iar` would make sense as an `owner`.
