### ISSUE TITLE
git "Output" lacks timestamps

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#129334]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

The data emitted into the "Output" windows by the git feature (built-in extension) does not feature timestamps.

This makes it difficult to correlate "challenges" with git activity. The ">" shown in the output does not appear to add a lot of value, timestamps would, an indication whether an activity was _initiated_ and _completed_, too.

To reproduce, 
* open VS Code with something that triggers the git feature
* enable auto-fetching for good measure
* switch to "Output" window
* select "Git" from the combobox

//act:
```
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-tree -l HEAD -- <masked>/download-remote-config-files.sh
> git show --textconv HEAD:<masked>/download-remote-config-files.sh
```

//exp something akin to:
```
[2021-01-02 14:01:02.1234] git fetch
[2021-01-02 14:01:02.1234] git status -z -u
[2021-01-02 14:01:02.1234] git symbolic-ref --short HEAD
[2021-01-02 14:01:02.1234] git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
[2021-01-02 14:01:02.1234] git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
[2021-01-02 14:01:02.1234] git remote --verbose
[2021-01-02 14:01:02.1234] git config --get commit.template
[2021-01-02 14:01:02.1234] git ls-tree -l HEAD -- <masked>/download-remote-config-files.sh
[2021-01-02 14:01:02.1234] git show --textconv HEAD:<masked>/download-remote-config-files.sh
```
possibly without the calendar date portion, possibly with T to provide clarity on timezones (or just use local) - this just for the timestamps. Logging could become even more useful if addition to timestamp(s) the log entry could be written at the start of the operation and enriched on the same line with a duration (`123 ms`) after _completion_ (this would indirectly flag completion of the operation, too).

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.13.4-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2903)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|31.31GB (26.00GB free)|
|Process Argv|--unity-launch --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.6.0
rust-analyzer|mat|0.2.678
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2021.6.2
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
vscode-yaml|red|0.21.1
vscode-lldb|vad|1.6.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by lszomoru** [comment]
Tomorrow's Insiders build will contain both timestamps, as well as execution time of the git command.

**Comment by lszomoru** [comment]
Verification steps:
1. Download and install the latest Insiders release
2. Open a folder/workspace that contains a git repository
3. Use the `Git: Show Git Output...` command from the command palette
4. Confirm that:
    - The Git output contain a timestamp at the beginning of each line
    - Each git command (each line with `> git ...`) has the execution time at the end of the line (ex: `[8ms]`)
