### ISSUE TITLE
Floating Debug Control Window blocks multi-row tabs

### ISSUE THREAD

**Issue by martin-braun** [microsoft/vscode#129306]
Issue Type: <b>Bug</b>

I'm using Visual Studio Code with multi-row tabs. When I debug an application and have 3 rows of tabs I'm unable to move the floating debug control window outside of view, so it does not block my tabs.

![2021-07-24 19 49 09](https://user-images.githubusercontent.com/24259245/126877116-4f6bdf04-a714-448d-a341-af3c286029f3.gif)

When I have three tab rows like in the example above, it should allow me to move the window across four different heights, so I can place it down on the open document itself.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (27.50GB free)|
|Process Argv|--crash-reporter-id cab06095-c1ee-4eec-8b38-eceeee0f4de4 --crash-reporter-id cab06095-c1ee-4eec-8b38-eceeee0f4de4|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Did you try the setting that makes it dock instead of float?

**Comment by martin-braun** [comment]
> Did you try the setting that makes it dock instead of float?

No, but yes, the problem is gone, when you use dock instead of float. Some people prefer float while hiding the side bar, though. With the possibility to dock the debug window this issue has lower priority, definitely.

**Comment by martin-braun** [comment]
@isidorn Can you please link the issue this issue is a duplicate from, I wasn't able to find it through search and I would like to upvote. Thanks in advance.
