### ISSUE TITLE
Avoid unnecessary string join and split

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129370]
https://github.com/microsoft/vscode/blob/4e5d793a7828f1baf62e9e06ce5137023bd17c06/extensions/ipynb/src/helpers.ts#L364-L377

Currently the stream output conversion (from VS Code types to Jupyter) does unnecessary V8 string concatenation and split, which slows down the conversion (using more memory and gc):

* Stream output is either `CellOutputMimeTypes.stderr` or `CellOutputMimeTypes.stdout`, so `convertOutputMimeToJupyterOutput` will always return `string`. Using `prev.concat(curr)` will keep creating arrays
* `splitMultilineString(outputs.join(''))` can slow down the process significantly. It firstly joins all the string, and then split by line breaks, this will trigger v8 to flatten the concatenated string (`outputs.join('')`) and double the memory usage.

We can probably run `splitMultilineString` on each output and concatenate last line of each output with the first line of next output (split first, then join).

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/4e5d793a7828f1baf62e9e06ce5137023bd17c06/extensions/ipynb/src/helpers.ts#L171-L171

Do we also want to split `\r\n`?

**Comment by roblourens** [comment]
This way would preserve the `\r` if they exist, if they are expected to be preserved, I don't know

**Comment by roblourens** [comment]
Discussed with @DonJayamanne, he plans to update this during debt week

**Comment by rebornix** [comment]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/876920/127057863-aee58cc5-287c-4fd2-81a1-2e5a1b8e45d1.png">


Another potential improvement we can make for the serializer is indentation detection. Not sure how it's implemented but it has caused quite a lot of GC (which I think can be improved by checking whitespace and line break char codes).

**Comment by DonJayamanne** [comment]
> can make for the serializer is indentation detection.

I agree, we can just look at the string immediately after the first `{` & before the next character.
Ideally it would be of the form:
```json
{
    cell:....
```
Thus all we need to know is the white space between the first `{` and the next non-whiespace character.
& if there are no line feeds, then I think we can ignore indents completely.
Thoughts on that, @rebornix /cc

**Comment by roblourens** [comment]
> Discussed with @DonJayamanne, he plans to update this during debt week

Tbh I don't remember talking about this @DonJayamanne, but are you planning on looking into this? I also can. The `string | string[]` stuff here is a little confusing to me

> I agree, we can just look at the string immediately after the first { & before the next character.

What does the indentation detection library do beyond that? This sounds fine to me.
