### ISSUE TITLE
Could you help to add a feature to show the search results in a separate editor page?

### ISSUE THREAD

**Issue by magicsunny** [microsoft/vscode#129379]
Could you help to add a feature to show the search results in a separate editor page?
Just like the feature in "search" panel. 

Thank you.

**Comment by JacksonKearl** [comment]
We have `Search Editor`s which look as follows:
![recording (30)](https://user-images.githubusercontent.com/8586769/127065109-fe4207e7-e4ef-4b80-8395-911acd8b093a.gif)

If you'd like you can use these by default by configuring the `search.mode` setting to `newEditor`.

**Comment by magicsunny** [comment]
> We have `Search Editor`s which look as follows:
> ![recording (30)](https://user-images.githubusercontent.com/8586769/127065109-fe4207e7-e4ef-4b80-8395-911acd8b093a.gif)
> 
> If you'd like you can use these by default by configuring the `search.mode` setting to `newEditor`.
> 
> Does that help?

Yep, thanks for your help, it really helps.
Sorry for replying late.
