### ISSUE TITLE
VSCode intellisense not working

### ISSUE THREAD

**Issue by MiniToggled** [microsoft/vscode#129312]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.58.2
- OS Version: Windows Version 20H2 19042.1110

Steps to Reproduce:

1. Create a nodeJS project
2. Try to use intellisense
3. BAMM doesnt work

https://streamable.com/zfbn7l

**Comment by mjbvz** [comment]
Please share example code (as text) or a small example project that demonstrates the issue

**Comment by dbarnes18** [comment]
I have the same issue in a Python workspace. No autocomplete come up at all.

I'm using:
* macOS 10.15.7
* VSC Information:
    * Version: 1.58.2
    * Commit: c3f126316369cd610563c75b1b1725e0679adfb3
    * Date: 2021-07-14T22:09:06.581Z (2 wks ago)
    * Electron: 12.0.13
    * Chrome: 89.0.4389.128
    * Node.js: 14.16.0
    * V8: 8.9.255.25-electron.0
    * OS: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster

@dbarnes18 Please file your issue against the python extension

**Comment by dbarnes18** [comment]
@mjbvz No. I don't think it was the Python extension that was the issue. Because I use other languages as well, (I've used JS since), and had the same issue with those.
