### ISSUE TITLE
Prompt option to close the vscode

### ISSUE THREAD

**Issue by ankurskydev** [microsoft/vscode#129380]
We have written the needed data into your clipboard because it was too larg
Issue Type: <b>Bug</b>

1. Open the vscode
2. A pop window appears "vscode cannot be opened"
3. Keep waiting, close, and cancel options

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.74GB (1.82GB free)|
|Process Argv|--crash-reporter-id bf3d70ce-f03e-4b0f-8955-c59fb01e0dbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.213
vscode-git-flow|Psy|0.5.1
sonarlint-vscode|Son|2.0.0
errorlens|use|3.3.1
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

e to send. Please paste.

**Comment by lszomoru** [comment]
@ankurskydev, could you please provide a screenshot of the error that you are seeing when opening VSCode? Thanks!
