### ISSUE TITLE
Search very confused about UTF-16 LE file

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12934]
Testing https://github.com/Microsoft/vscode/issues/12519

The file: [snap_0.zip](https://github.com/Microsoft/vscode/files/499186/snap_0.zip)

![image](https://cloud.githubusercontent.com/assets/762848/18931231/21dc8cdc-8580-11e6-9eba-ba4ed4102d70.png)

**Comment by chrmarti** [comment]
@sandy081 I think the scanning for newlines in textSearch.ts isn't encoding-proof.

**Comment by sandy081** [comment]
@chrmarti Yes we are not encoding the new line characters we check into that of file encoding

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17408
