### ISSUE TITLE
move terminal section from `View` to `Editor`.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#129387]
move terminal section from `View` to `Editor` when `drag&drop` or `terminal.integrated.defaultLocation` = `editor`.

it can be like this icon to add directly in editor tabs secation: 
![image](https://user-images.githubusercontent.com/26390254/126974540-6f1dc94b-2614-441b-babc-8acfd316004d.png)

or add `Terminal` to the `...` in editor.

**Comment by meganrogge** [comment]
not sure what you mean

**Comment by byehack** [comment]
> not sure what you mean

when `terminal.integrated.defaultLocation` to `editor` it should be easier to access and create terminals in editor.

**Comment by meganrogge** [comment]
oh you must be on an old version of vscode. I think the functionality you're describing already exists.
![recording (44)](https://user-images.githubusercontent.com/29464607/127225587-3eb94e5b-cd72-4d2a-be87-718f50c8b955.gif)

**Comment by byehack** [comment]
> oh you must be on an old version of vscode. I think the functionality you're describing already exists.
> ![recording (44)](https://user-images.githubusercontent.com/29464607/127225587-3eb94e5b-cd72-4d2a-be87-718f50c8b955.gif)

as you can see when there is no terminal opens in the editor section, you should create one from `View` section then drag it to editor.(this is not good when `terminal.integrated.defaultLocation` set to `editor`. we set it to have easier access from editor section)

![image](https://user-images.githubusercontent.com/26390254/126974540-6f1dc94b-2614-441b-babc-8acfd316004d.png)
i mean above icon should show on all langauges not just terminals.
like this:
![image](https://user-images.githubusercontent.com/26390254/127330941-c7dd958c-6ab3-43f8-8874-c6233483894d.png)

**Comment by Tyriar** [comment]
We're not planning on adding the + terminal button there when files are opened, you could however build an extension that adds this fairly easily.

**Comment by byehack** [comment]
also we can have `Terminal` to the `...` in editor.

or you can mixed it with debug/run icon that disuccess [here](https://github.com/microsoft/vscode/issues/117722).(maybe this is bad idea)

**Comment by Tyriar** [comment]
@byehack it's a good extension idea 🙂 adding it always there would cause too much bloat since it's an optional feature
