### ISSUE TITLE
Hang on Workspace Recommended Extension Search with Too Many Recommended Extensions in extensions.json

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12935]
- VSCode Version: 1.6 Insiders

##### Steps to Reproduce

1. Create a `.vscode/extensions.json` file
2. Add `"a.a"` to the `"recommendations"`.
3. Really recommend `"a.a"` by repeating it **one hundred thousand** times.
4. Try searching workspace recommended extensions

##### Result
Hang. Window no longer responds for a minute or two before getting search results back.

##### Expected
There would seem to be few valid cases for having more than 1000 recommended extensions or so in a workspace. Maybe we should generate a warning and reduce the query to that size if it is too large. In any case, this should not hang the UI.

**Comment by joaomoreno** [comment]
Great catch!

**Comment by sandy081** [comment]
@joaomoreno This is happening while we prepare query from filters using reduce, assign and slice. For each value, we are slicing and assigning which is making it slow. 
 
Fixed it by doing slicking and assigning only once on all values.

**Comment by joaomoreno** [comment]
@sandy081 Shouldn't you filter out duplicates for your query?

**Comment by sandy081** [comment]
@joaomoreno Yah that should be done too.. wanted to do but forgot.. Thanks for reminding.
