### ISSUE TITLE
Scrollbar problem in terminal.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#129394]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: win10 20h2

Steps to Reproduce:

https://user-images.githubusercontent.com/26390254/126982173-f1af9577-10e0-4619-8dc0-10fe89594bfe.mp4

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by byehack** [comment]
yes. fixed in insiders build.
