### ISSUE TITLE
VSCode doesn't pickup types from .tsx files

### ISSUE THREAD

**Issue by KL13NT** [microsoft/vscode#129373]
I'm trying to use React JSX in my project using TypeScript and Storybook. ESLint prevents JSX in `.ts` files, so I have to use `.tsx`. Problem is, whenever I export a type from a `.tsx` and import it into another `.tsx` file, vscode doesn't infer anything. It isn't even able to navigate to the type.

```ts
// Icon.tsx
export enum COLOR_TYPES {
	BASE = 'base',
	CRITICAL = 'critical',
	INTERACTIVE = 'interactive',
	WARNING = 'warning',
	HIGHLIGHT = 'highlight',
	SUCCESS = 'success',
	PRIMARY = 'primary',
}
```

```ts
// Icon.stories.tsx
import { COLOR_TYPES } from './Icon'; // provides no intellisence, can't even go to `./Icon` when `CTRL+Click`ing it.
```

Yet when renaming `Icon.tsx` to `Icon.ts` it works beautifully! I can `CTRL+Click` it, hover for more info, have autocomplete, etc.

---

Here's my `tsconfig.json`:
```json
{
	"allowSyntheticDefaultImports": true,
	"noImplicitAny": true,
	"module": "es6",
	"lib": [
		"esnext",
		"dom"
	],
	"target": "es5",
	"jsx": "react",
	"rootDirs": [
		"src"
	],
	"allowJs": true,
	"include": [
		"src/**/*"
	],
	"exclude": [
		"node_modules",
		"dist"
	]
}
```

VSCode `settings.json`
```json
{
	"typescript.updateImportsOnFileMove.enabled": "always",
	"typescript.referencesCodeLens.enabled": true,
	"typescript.suggest.completeFunctionCalls": true,
	"typescript.referencesCodeLens.showOnAllFunctions": true,
	"javascript.validate.enable": false,
	"typescript.validate.enable": false,
	"[typescript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[typescriptreact]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	}
}
```

**Comment by KL13NT** [comment]
I also noticed that it auto imports the types as normal, but fails to infer anything beyond that. Like, it prompts me to auto-import the type, but fails to see it beyond that:

![image](https://user-images.githubusercontent.com/20807178/126946825-0f0d27c8-f743-4fe2-a328-4b16b4cd8725.png)

It only sees it as `Import COLOR_TYPES` after importing:

![image](https://user-images.githubusercontent.com/20807178/126946869-ccbf4d14-4eeb-423d-b4f0-ffcff1bce85f.png)

**Comment by KL13NT** [comment]
CodeLens also reports 0 references to `COLOR_TYPE` despite importing and using the type in another file.

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates this issue. You can create a very simply GitHub repository for this

**Comment by KL13NT** [comment]
I cannot reproduce it anymore despite not changing anything. I shutdown my PC, woke up today and started up VSCode again and it worked. What I particularly did was change the `include` key in my `tsconfig`, and then revert that change. VSCode seemed to pick it up then and now imports are working again. 

If I'm able to reproduce it again I'll re-open or submit a new ticket.
