### ISSUE TITLE
Markdown Preview using code blocks not indented text after 100 elements.

### ISSUE THREAD

**Issue by Syntactical01** [microsoft/vscode#129305]
Issue Type: <b>Bug</b>

Create over 100 elements in a numbered list in markdown. Indenting the text under the number sections will cause the indented text in the markdown preview to be considered a code block not just indented text. This is fine for 1-99 items but items numbered 100+ have the issue:

```Markdown
100. My item.

    This text should be indented not a code block, which it is for item 1-99 but 100+ its turned into a code block in VSCode.
```

Note that it works fine if I do the numbers like:
```Markdown
1. Element one
1. Element two
1. Element three
```
but the second I start using a three digit number it has the issue.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

Screenshot for context:
![image](https://user-images.githubusercontent.com/46199814/126877984-5a3a67ad-e364-4e46-9aff-b0aa8132d8d3.png)

**Comment by mjbvz** [comment]
This is consistent [with how CommonMark renders that example](https://spec.commonmark.org/dingus/?text=100.%20My%20item.%0A%0A%20%20%20%20This%20text%20should%20be%20indented%20not%20a%20code%20block%2C%20which%20it%20is%20for%20item%201-99%20but%20100%2B%20its%20turned%20into%20a%20code%20block%20in%20VSCode.) and [how markdown-it renders it too](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22100.%20My%20item.%5Cn%5Cn%20%20%20%20This%20text%20should%20be%20indented%20not%20a%20code%20block%2C%20which%20it%20is%20for%20item%201-99%20but%20100%2B%20its%20turned%20into%20a%20code%20block%20in%20VSCode.%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

If you believe this is an issue, please file an issue against  markdown-it to start. I believe the markdown spec [should allow up to nine digits for ordered lists](https://spec.commonmark.org/0.30/#ordered-list-marker) (although maybe there's some exception I'm overlooking here)

**Comment by Syntactical01** [comment]
@mjbvz Do you know what tool VS Code uses for there markdown formatting? I will try to go file a bug ticket there. You listed two different ones so I didn't know which to go file the issue with.
