### ISSUE TITLE
Cannot set breakpoint in latest version of VSCode with my debug adapter - used to work fine before

### ISSUE THREAD

**Issue by dibyendumajumdar** [microsoft/vscode#129361]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install 'Lua and Ravi 5.3 Debugger'
2. Open a Lua script to debug
3. Try setting a breakpoint.

In recent versions it is not possible to set break points - this seems to have broken since some release of VSCode but I am not sure since when. 

Nothing happens when I click on the area where I would normally click to set breakpoint.

I am attaching a sample interaction log - I don't see any setBreakpoints request going to the debug adapter.

[out1.txt](https://github.com/microsoft/vscode/files/6874590/out1.txt)

**Comment by dibyendumajumdar** [comment]
Hi @weinand  I am not sure what has changed as when I last updated my adapter in 2020 it used to work fine.

**Comment by gjsjohnmurray** [comment]
@dibyendumajumdar I suggest you perform a bisect procedure, installing earlier versions of VS Code until you discover exactly which version your extension stopped working with. Then review that version's release notes.

Release notes for all previous versions are available from the index pane on the left of the page at https://code.visualstudio.com/updates and at the top of each set of release notes there are links for downloading the installers for that version.

**Comment by dibyendumajumdar** [comment]
Hi - I checked earlier versions - its broken since 1.53.

**Comment by weinand** [comment]
@isidorn IIRC we've removed the deprecated "Debuggers" contributions point for breakpoints, right?

**Comment by dibyendumajumdar** [comment]
It seems that I need to add following in the package.json:

```
	"contributes": {
		"breakpoints": [{ "language": "lua" }],
```

I manually amended the package.json in the deployed extension and saw the breakpoints showed up in 1.58.

So the way this works was changed in 1.53? I didn't see any instructions related to this in the release notes.

**Comment by dibyendumajumdar** [comment]
Okay I see instruction in 1.42 release notes.

I will close this issue - but one question: was it necessary to make a breaking change?

**Comment by isidorn** [comment]
Sorry about the breaking change. And I am glad you found the instructions on how to mitigate.
It was necessary.
