### ISSUE TITLE
vs code black screen issue even after using the disable gpu 

### ISSUE THREAD

**Issue by chirag057** [microsoft/vscode#129351]
i am facing a issue of black screen. I went through few videos that said to add --disable-gpu i added it but didnt work please help !!!

**Comment by ShanMuhammad** [comment]
Hello Team,
 
I am facing same issue with visual studio code. after update to latest version when opening the VS code its showing black screen.

Please find attached gif for more info.
![recording](https://user-images.githubusercontent.com/15378718/127331340-7a2bf962-0ae5-4f30-a056-2c24d6cc49f6.gif)

**Comment by deepak1556** [comment]
Can you launch with `code --verbose` and attach the output.

**Comment by ShanMuhammad** [comment]
@deepak1556 

>code --verbose

[main 2021-07-29T09:53:16.036Z] [File Watcher (node.js)] [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\settings.json
[main 2021-07-29T09:53:16.087Z] Starting VS Code
[main 2021-07-29T09:53:16.087Z] from: c:\Program Files\Microsoft VS Code\resources\app
[main 2021-07-29T09:53:16.087Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '3a6bea05-71ec-4f1f-9f43-84e6061861d2',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\smuham16\\AppData\\Roaming\\Code\\logs\\20210729T152316'
}
[main 2021-07-29T09:53:16.100Z] Resolving machine identifier...
[main 2021-07-29T09:53:16.100Z] Resolved machine identifier: 60c996423c869f575fa4dd8886b167f8e6525788fbf5d7c1ffba8b0a0d0ed9ce
[main 2021-07-29T09:53:16.101Z] Main->SharedProcess#connect
[main 2021-07-29T09:53:16.130Z] StorageMainService: creating global storage
[main 2021-07-29T09:53:16.130Z] lifecycle (main): phase changed (value: 2)
[main 2021-07-29T09:53:16.133Z] windowsManager#open
[main 2021-07-29T09:53:16.137Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '4488e3faf123ed12fc3133d871313f44', uri: [m] },
    exists: true
  }
]
[main 2021-07-29T09:53:16.139Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 285, y: 77, width: 1027, height: 771 }
[main 2021-07-29T09:53:16.140Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1536, height: 824 }
[main 2021-07-29T09:53:16.140Z] window#ctor: using window state { mode: 0, x: 285, y: 77, width: 1027, height: 771 }
[main 2021-07-29T09:53:16.229Z] StorageMainService: creating workspace storage (4488e3faf123ed12fc3133d871313f44)
[main 2021-07-29T09:53:16.229Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2021-07-29T09:53:16.230Z] lifecycle (main): phase changed (value: 3)
[main 2021-07-29T09:53:16.262Z] update#setState idle
[main 2021-07-29T09:53:16.263Z] resolveShellEnv(): skipped (Windows)
(node:15276) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-07-29T09:53:16.501Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\settings.json
[main 2021-07-29T09:53:16.517Z] [File Watcher (node.js)] [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\globalStorage
[main 2021-07-29T09:53:16.522Z] [File Watcher (node.js)] [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\globalStorage
[main 2021-07-29T09:53:16.651Z] [File Watcher (node.js)] [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\globalStorage
[main 2021-07-29T09:53:16.676Z] [File Watcher (node.js)] [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\globalStorage
[15276:0729/152316.876:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 1 time(s)
[main 2021-07-29T09:53:16.877Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\smuham16\AppData\Roaming\Code\User\globalStorage
[15276:0729/152317.627:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 2 time(s)
[15276:0729/152318.158:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 3 time(s)
[15276:0729/152318.727:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 4 time(s)
[15276:0729/152319.206:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 5 time(s)
[15276:0729/152320.007:WARNING:gpu_process_host.cc(1272)] The GPU process has crashed 6 time(s)
[15276:0729/152320.013:ERROR:browser_gpu_channel_host_factory.cc(168)] Failed to launch GPU process.
[main 2021-07-29T09:53:46.266Z] update#checkForUpdates, state =  idle
[main 2021-07-29T09:53:46.266Z] update#setState checking for updates
[main 2021-07-29T09:53:46.266Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/3c4e3df9e89829dce27b7b5c24508306b151f30d
[main 2021-07-29T09:53:46.266Z] resolveShellEnv(): skipped (Windows)
[main 2021-07-29T09:54:00.858Z] update#setState downloading
[main 2021-07-29T09:54:00.863Z] update#setState downloaded

**Comment by deepak1556** [comment]
@ShanMuhammad starting like `code --disable-gpu` should fix the issue you are facing, can you check ?

**Comment by ShanMuhammad** [comment]
@deepak1556  Thanks for Quick update. 

When I open new instance then its always open as a black screen. but second instance is opening fine.

**Comment by deepak1556** [comment]
Can you share a gif with the steps you are performing.
