### ISSUE TITLE
improve "Search on Type" to be more useful in more normal development scenarios

### ISSUE THREAD

**Issue by o-o00o-o** [microsoft/vscode#129340]
Right now it seems that Search on Type in the Explorer is really generalist in nature and so cannot be used in most of the cases that someone would want to use it.

Usually developers will want to find files with a specific unbroken sequence of characters in e.g. "readme" or ".sql"

Right now if I seach for "blah" to find files blah.cs and FixBlah_.txt - while it will find them it will also find BeforeLegAfterHeel.txt as it has the letters b l a and h in

If I try to override this with explicit "blah" with quotes, it won't find anything. I guess it is trying to find filenames with double quotes (are they actually allowed in filenames ever in some OS's?)

Also strangely if I try to search for blah_ it will not find FixBlah_ even though ctrl-P does find all the files I really want

Ultimately the current behaviour is obscure and I would like better control

- be able to specify a string to ONLY find files with that specific string in.  Perhaps by quoting or similar method
- ensure that it finds all files with that string in (including special characters such as _ and .)

Honestly I think the current implementation is actually buggy but because I can't find clear docs on how it should work I can't really tell, but for me it isn't useful and I have to resort to Ctrl-P in every case which is not ideal

**Comment by o-o00o-o** [comment]
also notice that this question https://stackoverflow.com/questions/30095376/how-do-i-search-for-files-in-visual-studio-code doesn't really have a good answer

**Comment by joaomoreno** [comment]
#70646
