### ISSUE TITLE
Notebook falsely detects "empty cells"

### ISSUE THREAD

**Issue by wangweixuan** [microsoft/vscode#129332]
In notebook outline, a RegExp is used to test whether a cell is empty.

https://github.com/microsoft/vscode/blob/2a82df9437f5c1d3e0302ff4910a5e7f51ea1756/src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.ts#L423-L428

The RegExp in fact testing whether a cell contains `\w` characters, namely `a-z`, `A-Z`, `0-9`. That leads to some cells with actual content being detected as "empty", for example the following cells, containing Chinese characters or esoteric code:

<img width="666" alt="s" src="https://user-images.githubusercontent.com/24620923/126894374-ce9bde8f-1c09-42bb-99ba-6c17f9aa5536.png">

I believe this behavior is not ideal. I suggest we use the test `content.trim().length === 0`, which detects any content with non-whitespace characters as non-empty.

**Comment by DonJayamanne** [comment]
>  I suggest we use the test content.trim().length === 0, w

Interesting. i would have expected the same, would like to learn why we use regex here (there probably is a good reason for this)
