### ISSUE TITLE
Can the local search box have a "clear search results" button similar to the one in global search?

### ISSUE THREAD

**Issue by mross** [microsoft/vscode#129311]
To me, it seems a good idea to have the ability to easily clear the local search box and return focus to the tab content.
Unless I'm missing something, right now I have to click into the search box, select everything and press the delete key to clear the content highlighting from my previous search, and then remember to move focus back to the tab content.

Sometimes -- not every time, but sometimes -- this seems like a lot of extra work, and often distracts me from what I am trying to think about.

**Comment by roblourens** [comment]
Pressing ctrl+f typically highlights the contents of the find box so you can just type to replace it
