### ISSUE TITLE
Contents inside <script> in html files are commented with html style comments

### ISSUE THREAD

**Issue by tddschn** [microsoft/vscode#129342]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0
```
- OS Version: macOS Big Sur 11.5

Steps to Reproduce:

1. Copy the following html code, create a new file in VS Code and paste the code.
```html
<html>
<body>
	<script>
		alert('hello');
	</script>
</body>
</html>
```
2. Change the language mode to 'HTML'.
3. Try to comment the `alert('hello');` line and see what happens.

https://user-images.githubusercontent.com/45612704/126897858-bcde44b8-21df-4999-a863-927ea427a438.mov

**Comment by aeschli** [comment]
I cannot reproduce this in a bare VS Code. I get the `//` comment.

It is highly likely that an extension redefines the HTML mode.
Please run with extensions disabled (Command: `Reload with Extensions disabled`) and try again.

**Comment by tddschn** [comment]
Commenting works as expected with the Jinja extension disabled. Thank you for pointing that out!
Extension bisecting is amazing. :)
