### ISSUE TITLE
`Show accessibility help` no longer appears in All Commands list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12938]
Testing https://github.com/Microsoft/vscode/issues/12519

The Alt+F1 shortcut is also unavailable, though ctrl+m works fine 
![image](https://cloud.githubusercontent.com/assets/762848/18931776/71ed1ec4-8582-11e6-869a-f7220bf7c5d6.png)

In 1.5, the command would appear:
![image](https://cloud.githubusercontent.com/assets/762848/18931789/7ffc00b6-8582-11e6-92b8-4628e4e3f4c3.png)

**Comment by joaomoreno** [comment]
Setting to September: not sure if regression.

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://cloud.githubusercontent.com/assets/900690/18942104/b627f9ee-8616-11e6-8081-07ea8b1f2030.png)

Since it seems to work for me, maybe Alex can debug this in October with @mousetraps or tell why it might not show up in all cases.

**Comment by bpasero** [comment]
I got it: it needs an opened editor. I think this works as designed.
