### ISSUE TITLE
Disable 'open with Code' on desktop context menu

### ISSUE THREAD

**Issue by babarkhuroo** [microsoft/vscode#129374]
Hi, can you add a setting or something to hide 'open with code' option from desktop context menu? it's a pretty neat feature but i don't think it's useful on desktop context menu.

P.S. this is my first ever feature request on github, so please don't ban/cancel me for this. thanks! :)

**Comment by gjsjohnmurray** [comment]
Assuming you are on Windows, I think you can use regedit and delete the HKEY_CLASSES_ROOT\*\shell\VSCode key plus descendants. Do this at your own risk, and maybe export it first as a backup in case you change your mind.

**Comment by systemRockstar** [comment]
thank you but i don't wanna completely disable it from all context menus. only from context menu on desktop :)

**Comment by gjsjohnmurray** [comment]
Then try removing `HKEY_CLASSES_ROOT\Directory\Background\shell\VSCode`

**Comment by systemRockstar** [comment]
It kinda solved the problem, thanks. But it also removed that option from inside of other folders, not jus from desktop. right clicking on files or folders works fine 👍

**Comment by joaomoreno** [comment]
The right fix is: Reinstall VS Code and choose the right options in the setup wizard.
