### ISSUE TITLE
[install vsix] needs to install .vsix to .vscode-server (not .vscode)

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode#129371]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: windows 10

Steps to Reproduce:

1. connect to Host using Remote-SSH
2. connect ssh (ssh username@host) on command tool
3. type `code --install-extension ${VSIX}`
4. extension is installed to .vscode folder (**not .vscode-server**)

when use `code --install command`,  is there any way to install vscode extension to **.vscode-server**?
(I know we can set the specific path using `code --extensions-dir <dir>`, but that way changes the root path)

**Comment by aeschli** [comment]
You need to run `code --install-extension ${VSIX}` in the integrated terminal in the remote window. Only then, `code` can talk to the remote server. If called in a regular terminal, you are running an instance of (desktop) code installed on the machine.
