### ISSUE TITLE
GUI broken for manual settings sync

### ISSUE THREAD

**Issue by AlexanderLanin** [microsoft/vscode#129398]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Settings sync is already enabled on one setup
2. Change some settings on a second setup
3. Turn on settings sync on second setup
4. In the appearing conflict window select merge manually

Effect:
![image](https://user-images.githubusercontent.com/5074553/126990662-32c94e80-911f-4969-97d6-04aef90be77e.png)
(This image is taken in my "normal" editor, but it also happens without any extensions)

**Comment by sandy081** [comment]
This is coming from the diff editor. 

@alexdima Any insights why this can happen?

**Comment by alexdima** [comment]
@sandy081 Yes, the inline diff editor still consists of two editors, one on the left, with a very small width. 

I have seen something similar in https://github.com/microsoft/vscode/issues/118461 . There I simply opted to not show the "Open Workspace" button in the diff editor.
