### ISSUE TITLE
vs sometimes empty workspace

### ISSUE THREAD

**Issue by yuber83** [microsoft/vscode#129314]
Issue Type: <b>Bug</b>

the problem with vscode is that sometimes vscode open only menus, and no more, and i clicked to menus and nothing happens.
here is the verbose output

**$ code . --verbose**
<details>
[main 2021-07-24T22:21:34.745Z] Starting VS Code                                                                                            
[main 2021-07-24T22:21:34.749Z] from: /usr/share/code/resources/app                                                                         
[main 2021-07-24T22:21:34.749Z] args: {                                                                                                     
  _: [ '/home/yvasquez/practicas/vue/testing/basics' ],                                                                                       
  diff: false,                                                                                                                                
  add: false,                                                                                                                                 
  goto: false,                                                                                                                                
  'new-window': false,                                                                                                                        
  'reuse-window': false,                                                                                                                      
  wait: false,                                                                                                                                
  help: false,                                                                                                                                
  'list-extensions': false,                                                                                                                   
  'show-versions': false,                                                                                                                     
  version: false,                                                                                                                             
  verbose: true,                                                                                                                              
  status: false,                                                                                                                              
  'prof-startup': false,                                                                                                                      
  'no-cached-data': false,                                                                                                                    
  'prof-v8-extensions': false,                                                                                                                
  'disable-extensions': false,                                                                                                                
  'disable-gpu': false,                                                                                                                       
  telemetry: false,                                                                                                                           
  debugRenderer: false,                                                                                                                       
  logExtensionHostCommunication: false,                                                                                                       
  'skip-release-notes': false,                                                                                                                
  'skip-welcome': false,                                                                                                                      
  'disable-telemetry': false,                                                                                                                 
  'disable-updates': false,                                                                                                                   
  'disable-keytar': false,                                                                                                                    
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,                                                                                                            
  'crash-reporter-id': 'd3730f36-c91a-4e15-be32-75edf2a726c6',                                                                                
  'skip-add-to-recently-opened': false,                                                                                                       
  'unity-launch': false,                                                                                                                      
  'open-url': false,                                                                                                                          
  'file-write': false,                                                                                                                        
  'file-chmod': false,                                                                                                                        
  'driver-verbose': false,                                                                                                                    
  force: false,                                                                                                                               
  'do-not-sync': false,                                                                                                                       
  trace: false,                                                                                                                               
  'force-user-env': false,                                                                                                                    
  'force-disable-user-env': false,                                                                                                            
  'open-devtools': false,                                                                                                                     
  __sandbox: false,                                                                                                                           
  'no-proxy-server': false,                                                                                                                   
  'no-sandbox': false,                                                                                                                        
  nolazy: false,                                                                                                                              
  'force-renderer-accessibility': false,                                                                                                      
  'ignore-certificate-errors': false,                                                                                                         
  'allow-insecure-localhost': false,                                                                                                          
  logsPath: '/home/yvasquez/.config/Code/logs/20210724T172134'                                                                                
}                                                            
[main 2021-07-24T22:21:34.753Z] Resolving machine identifier...                                                                             
[main 2021-07-24T22:21:34.757Z] Resolved machine identifier: 0672fc2ea12a2383719ee8be00cd1843b1                                             161a0bfdd550108f24226bbdaaeb8b                                                                                                                
[main 2021-07-24T22:21:34.758Z] Main->SharedProcess#connect                                                                                 
[main 2021-07-24T22:21:34.768Z] StorageMainService: creating global storage                                                                 
[main 2021-07-24T22:21:34.768Z] lifecycle (main): phase changed (value: 2)                                                                  
[main 2021-07-24T22:21:34.769Z] windowsManager#open                                                                                         
[main 2021-07-24T22:21:34.770Z] windowsManager#open pathsToOpen [                                                                           
  {                                                                                                         
    workspace: { id: '16daf1d6ae1eaf266691a660f4fce548', uri: [m] },                                                                          
    exists: true                                                                                                                              
  }                                                                                                         
]                                                                                                   
[main 2021-07-24T22:21:34.772Z] IPC Object URL: Registered new channel vscode:ef81055b-7bcd-488                                             c-b822-2a9545abda63.                                                                                                                          
[main 2021-07-24T22:21:34.773Z] window#validateWindowState: validating window state on 2 displa                                             y(s) { mode: 0, x: 1, y: 51, width: 1614, height: 847 }                                                                                       
[main 2021-07-24T22:21:34.774Z] window#validateWindowState: multi-monitor working area { x: 0,                                              y: 0, width: 1600, height: 900 }                                                                                                              
[main 2021-07-24T22:21:34.774Z] window#ctor: using window state { mode: 0, x: 1, y: 51, width:                                              1614, height: 847 }                                                                                                                           
[main 2021-07-24T22:21:34.775Z] window: using vscode-file:// protocol and V8 cache options: byp                                             assHeatCheck                                                                                                                                  
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)                                                            
[main 2021-07-24T22:21:34.832Z] StorageMainService: creating workspace storage (16daf1d6ae1eaf2                                             66691a660f4fce548)                                                                                                                            
[main 2021-07-24T22:21:34.833Z] windowsManager#open used window count 1 (workspacesToOpen: 0, f                                             oldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)                                                                                           
[1603:0724/172134.835586:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during                                                initialization                                                                                                                                
[main 2021-07-24T22:21:34.835Z] lifecycle (main): phase changed (value: 3)                                                                  
[main 2021-07-24T22:21:34.836Z] update#setState idle
[main 2021-07-24T22:21:34.836Z] resolveShellEnv(): skipped (VSCODE_CLI is set)                                                              
code: intel_memman.c:38: intel_memman_init: La declaración `intel->bufmgr' no se cumple.                                                      
[1565:0724/172134.915373:WARNING:crash_handler_host_linux.cc(341)] Could not translate tid, att                                               empt = 1 retry ...                                                                                                                            
[main 2021-07-24T22:21:34.960Z] resolveShellEnv(): skipped (VSCODE_CLI is set)                                                              
[1565:0724/172135.034830:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 1 time(                                               s)                                                                                                      
/dev/fd/3: No existe el fichero o el directorio                                                                                               
Server response:                                                                                                                              
code: intel_memman.c:38: intel_memman_init: La declaración `intel->bufmgr' no se cumple.                                                      
[1565:0724/172135.055649:WARNING:crash_handler_host_linux.cc(341)] Could not translate tid, att                                               empt = 1 retry ...                                                                                                                            
[1565:0724/172135.207503:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 2 time(                                               s)                                                                                                      
/dev/fd/3: No existe el fichero o el directorio                                                                                               
Server response:                                                                                                                              
code: intel_memman.c:38: intel_memman_init: La declaración `intel->bufmgr' no se cumple.                                                      
[1565:0724/172135.285846:WARNING:gpu_process_host.cc(1288)] The GPU process has crashed 3 time(                                               s)                                                                                                      
/dev/fd/3: No existe el fichero o el directorio
Server response:
[1697:0724/172135.302160:WARNING:vaapi_wrapper.cc(567)] VAAPI video acceleration not available for disabled
[1565:0724/172135.306737:WARNING:gpu_process_host.cc(1008)] Reinitialized the GPU process after a crash. The reported initialization time was 0 ms
[main 2021-07-24T22:21:44.424Z] Lifecycle#window.on('close') - window ID 1
[main 2021-07-24T22:21:44.424Z] Lifecycle#onBeforeCloseWindow.fire() - window ID 1
[main 2021-07-24T22:21:44.427Z] IPC Object URL: Removed channel vscode:ef81055b-7bcd-488c-b822-2a9545abda63.
[main 2021-07-24T22:21:44.427Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-07-24T22:21:44.427Z] Lifecycle#onWillShutdown.fire()
[main 2021-07-24T22:21:44.428Z] Lifecycle#app.on(window-all-closed)
[main 2021-07-24T22:21:44.429Z] Lifecycle#app.on(before-quit)
[main 2021-07-24T22:21:44.429Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-07-24T22:21:44.429Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: 'file:///home/yvasquez/practicas/vue/testing/basics',
    backupPath: '/home/yvasquez/.config/Code/Backups/8def5754b17aa447c19a99adc3a87ee1',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 0,
      x: 1,
      y: 51,
      width: 1614,
      height: 847
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}

[main 2021-07-24T22:21:44.429Z] Lifecycle#app.on(will-quit)
[main 2021-07-24T22:21:44.436Z] StorageMainService: closed global storage
[main 2021-07-24T22:21:44.436Z] StorageMainService: closed workspace storage (16daf1d6ae1eaf266691a660f4fce548)

</details>

and the vscode open and only shows dark workspace and i can't do nothing.
but this problems occurs sometimes, i have to close and open repeatedly.
i have two monitor debian 10, lightdm and awesome

thanks for reply

![vscodefalla](https://user-images.githubusercontent.com/3409723/126882541-d3f3a157-64de-4b07-99d1-cc5a04342568.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.10.0-0.bpo.7-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) G5905 CPU @ 3.50GHz (2 x 3500)|
|GPU Status|2d_canvas: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.64GB (1.90GB free)|
|Process Argv|--crash-reporter-id d3730f36-c91a-4e15-be32-75edf2a726c6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tailwindcss|bra|0.6.13
npm-intellisense|chr|1.4.0
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|8.0.1
auto-close-tag|for|0.5.11
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.7
vue-snippets|hol|1.0.4
vue-autoimport|ish|1.0.5
dotenv|mik|1.0.1
vetur|mwi|0.1.4
color-highlight|nau|2.4.0
vetur|oct|0.34.1
vscode-scss-formatter|sib|2.2.3
html5-boilerplate|sid|1.1.1
bunker|sld|1.1.6
vim|vsc|1.21.5
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
axios-snippets|Ygg|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
