### ISSUE TITLE
white patches all over the vs code

### ISSUE THREAD

**Issue by jibinflotilla** [microsoft/vscode#129403]
Issue Type: <b>Bug</b>

while opening vs code it is showing white patches all over the screen

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.37GB (1.36GB free)|
|Process Argv|--crash-reporter-id 6fe1802f-d339-4911-a710-8212696e6002|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by deepak1556** [comment]
/gifPlease

Does starting with `--disable-gpu` help ?

**Comment by jibinflotilla** [comment]
[image: image.png]

**Comment by deepak1556** [comment]
Sorry but the image attachment seems to have failed, can you add it again. Also did you try launching with `--disable-gpu` ?
