### ISSUE TITLE
Request for better tooling around zen mode

### ISSUE THREAD

**Issue by ansaardollie** [microsoft/vscode#129408]
Currently developing an extension that helps Angular developers code better. It toggles the workbench Zen Mode feature however there is very little tooling available in the VS Code Extension API that allows for any interaction with this workbench mode. 

At the very least having a `window.onZenModeToggle()` event listener / `window.zenModeEnabled` field would solve all of the issues I am currently facing in trying to implement the features envisioned for my current extention.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/114741
