### ISSUE TITLE
Feature: support for custom keyrings on Linux/MacOS

### ISSUE THREAD

**Issue by shinotheshino** [microsoft/vscode#129462]
Currently, the authentication provider extensions (Microsoft/GitHub) use `keytar` to store passwords in keyrings on Linux/MacOS. I use custom user-data and extension directories to keep my personal and work installations of VSCode separate; however, when I sign into Microsoft, for example, in my work instance, I am also logged in in my personal instance, which is undesirable. This is due to keytar always using the default keyring to store the authentication information. It would be useful if vscode allowed a command-line parameter or a setting which allowed users to override the keyring name; or, to use some other alternative to keytar for storing credentials.

**Comment by TylerLeonhardt** [comment]
Makes sense. I've added it to the backlog candidates. I'd also encourage opening an issue on keytar for a potential solution on their side.
