### ISSUE TITLE
Test finalized renderer messaging API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#129472]
Refs: https://github.com/microsoft/vscode/issues/123601

- [x] anyOS @roblourens
- [x] anyOS @isidorn

Complexity 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23125016%0A%0A)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129472%0A%0A&assignees=connor4312)

---

Renderers do not use standard webview messaging, so we created a new messaging channel for them to talk to the extension. Messaging must be requested statically and is opt-in, since renderers which have a hard dependency on messaging will not be usable in aznb. 

- Issue with design and information: https://github.com/microsoft/vscode/issues/123601
- Permalink to API: https://github.com/microsoft/vscode/blob/d611085ac1bd3c43f1f6fa762ddb35c19b3d3652/src/vs/vscode.d.ts#L12329

Note that, since the editor is still proposed, an empty object is given and accepted in this API when `enableProposedApi` is not turned on.

You can test this functionality with an existing renderer-bearing extension, like github-issues-notebooks, or create your own notebook renderer via `npm install -g generator-code && yo code`

**Comment by isidorn** [comment]
Works fine, I just find it weird that this is finalized API but if I do not have `enableProposedApi` I will get an empty object.

**Comment by roblourens** [comment]
Yeah, we are sure we want to finalize an API that depends on proposed API? Are we confident enough in the proposed API?

**Comment by connor4312** [comment]
I think we're confident that there will be _something_ named a NotebookEditor and that we want it passed when doing messaging. Stable vscode.d.ts types it as an empty interface, so an empty object is passed to ensure that non-proposed consumers don't accidentally depend on any of its properties.

**Comment by rzhao271** [comment]
Isi took care of Paula's slot. Closing the TPI
