### ISSUE TITLE
'config.property.duplicate' error when activating the extension

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#129466]
recently, we are getting this error when activating the CmakeTools extension:

![image](https://user-images.githubusercontent.com/16143955/126562520-dede44af-c3d0-4fd6-810d-005bd20c66c3.png)

**Comment by bobbrow** [comment]
To clarify, we only see this when launching the Extension Host while debugging our extension.  It also requires that the released version of the extension is installed.

Repro steps:
1. clone https://github.com/microsoft/vscode-cmake-tools.git
2. Open the folder in VS Code Insiders
3. Press F5 to build and run the extension.
4. In the extension host window, open a folder with a CMakeLists.txt in it. (if you create the file after opening the folder, run the "CMake: Configure" command to fully activate the extension -- or just Reload the window)

**Comment by dbaeumer** [comment]
Sounds like something related to extension debugging

**Comment by weinand** [comment]
@bobbrow do you have the extension to be debugged (CmakeTools) already installed in VS Code, so that a `cmake.cmakePath` is basically registered twice?

**Comment by bobbrow** [comment]
Yes, that is step 3 of my repro.  We've always (4+ years) had the "official" extension installed prior to debugging because we also dogfood the extension when we're not debugging.

**Comment by weinand** [comment]
@bobbrow what API is used to "register" the `cmake.cmakePath`?
This is not related to debugging, but it could be that the register-API has become more strict. But for this you would have to find out what API this is.

@Tyriar to do recognise the error message from above?

**Comment by Tyriar** [comment]
I think you would get this error when an extension (or 2 extensions) registered the same setting twice. I haven't seen this outside of activating multiple versions of the same extension.

**Comment by sandy081** [comment]
This is because `ms-vscode.cmake-tools` extension depends on `twxs.cmake` extension which was installed when the former was installed. `twxs.cmake` extension also registered the same setting `cmake.cmakePath` and hence the warning was shown. 

Please fix it either by renaming the setting id or use the setting defined by the other extension.

**Comment by bobbrow** [comment]
Makes sense.  Sorry I didn't catch that earlier.
