### ISSUE TITLE
Emojis with skin tone are not properly rendered in VSCode Integrated Terminal

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/vscode#129470]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.58.2
- OS Version: Windows 10 Build 21387

Steps to Reproduce:

1. Run Python 3 in VSCode Integrated Terminal
2. Paste code below

```python
mystr = ''
for x in [0x1F442, 0x1F3FC]:
  mystr += str(chr(x))

print(mystr)
print('👌🏻')
```

Here's how VSCode Integrated Terminal renders it:

![image](https://user-images.githubusercontent.com/466713/127075255-a7598835-37eb-445c-8652-0245fed3b1e4.png)

Here's what it (correctly) looks like in Microsoft Terminal (albeit it has a whitespace issue):

![image](https://user-images.githubusercontent.com/466713/127075240-a8b44a39-d138-4ab9-b5a6-9534012a8cbe.png)

### Expected Result

Emojis with skin tones should be rendered with the specified string.

### Actual Result

Emojis with skin tones are rendered as two separate characters.

**Comment by Tyriar** [comment]
Moved to https://github.com/xtermjs/xterm.js/issues/3397
