### ISSUE TITLE
Support HTML as walkthrough media

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#129461]
Currently, walkthrough "media" nodes only support images, and markdown.  This request is to add a field for HTML media.

My motivation for requesting this is to better support localization of content.

To support localization of markdown files in in walkthroughs, a check was added which chooses an appropriate markdown file based on automatically appending(?) a language value to the specified path.  However, the problem of localizing markdown files remain.  Providing an entire markdown file to translators for localization is problematic, as they may not be proficient with markdown.  Extracting strings from markdown and generating a new markdown file is not simple, considering the potential for multiple segments of markdown in a single sentence, the lack of a markdown parser than can emit markdown, or the need to author markdown a special way to enable loc processing.

We have an existing elegant solution for HTML files.  If we could provide an HTML file in the "media" node, this would be a solved problem for us.  We use a `data-loc-id` attribute to indicate nodes in HTML containing text that should be localized.  An HTML parser is used to extract all localizable strings, as well as reinsert translated strings and emit the resulting HTML.  HTML sub-nodes are handled intelligently, by automatically inserting placeholders (`{0}` `{1}`) into exported strings.

**Comment by JacksonKearl** [comment]
With Markdown being something of a superset of HTML, is it possible for you to simply treat the HTML data as a markdown document and provide that?

**Comment by Colengms** [comment]
@JacksonKearl I've tried specifying an HTML file in the "markdown" field, but nothing was displayed.  In order for HTML parsers to deal properly with the file, it needs to be in HTML form.

**Comment by JacksonKearl** [comment]
Could you provide an example of the HTML you'd like to render? I'd expect it to generally render if placed in the markdown field, but we do some sanitation that can result in removing the whole tree.

**Comment by Colengms** [comment]
I tried it with an example file from here: https://www.w3schools.com/html/html_examples.asp  It looks like it works if I remove `doctype`, `html` and `body` tags.  Could I convince you to allow those, to make authoring as simple as possible?  :)  If not, I should be able to get the HTML parser I'm using (parse5) to omit them when emiting, but am not certain.

Also, could you remind me of the naming convention for detecting language-specific files specified to `media.markdown`?  (Or point me to the code, or doc on the subject).  Thanks!

**Comment by JacksonKearl** [comment]
Yes, the code is here: https://github.com/microsoft/vscode/blob/6d882a2750aadef4881afead4f0842acf9b186f6/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L442-L445

Basically: take the filename (doc.md) and locale (en-us), the resolve the first of `doc.nls.en-us.md`, `doc.nls.en.md`, `doc.nls.md`

**Comment by JacksonKearl** [comment]
Where did you come down on this for stripping the tags?

**Comment by Colengms** [comment]
I was able to generate the localized files as fragments, so this was addressed on our side.
