### ISSUE TITLE
--locale cmd line argument not working (Windows)

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12945]
Testing #12519 

From the command line, `code-insiders --locale zh-TW` doesn't bring up the correct locale (always English)

**Comment by joaomoreno** [comment]
Setting to September for regression analysis.

**Comment by bpasero** [comment]
Works for me on Mac.

**Comment by dbaeumer** [comment]
Works for me under Windows.

@mousetraps there is one limitation with this. If a vscode instance is already running you can't change the local for a second instance. So the switch is ignored. Reason being that the menu bar is owned by the main process and that is only started once.

**Comment by mousetraps** [comment]
@dbaeumer yep, you're right! it's working now. I thought I had closed all the windows, but it turns out there were some lingering processes.
