### ISSUE TITLE
emmet auto complete not working

### ISSUE THREAD

**Issue by rasatizdast** [microsoft/vscode#129414]
Issue Type: <b>Bug</b>

Emmet's auto complete doesnt work. when i want to use emmet this error pops up 
Running the contributed command: 'emmet.expandAbbreviation' failed.
i don't know what to do please help.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.54GB free)|
|Process Argv|--crash-reporter-id 8e3010fb-0f8a-4aa0-bc26-f79db2b8d403|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.1
vsc-material-theme|Equ|33.2.2
prettier-vscode|esb|8.0.1
auto-rename-tag|for|0.1.7
material-icon-theme|PKi|4.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by rzhao271** [comment]
I'm not too sure about what's happening here.

Can you check the following comment and see if it helps?
https://github.com/microsoft/vscode/issues/128835#issuecomment-881530481
