### ISSUE TITLE
Allow scoping devtools to a particular frame

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#129437]
Extracted from https://github.com/lostintangent/codeswing/issues/50

With OOPIF webview, extensions don't have a way to scope the top-level devtools to the frame. Can electron hook into `content::RenderFrameDevToolsAgentHost` to fix this ?

Issue is mostly to experiment with above idea.

**Comment by rzhao271** [comment]
So far, to pass in the agent host for `content::RenderFrameDevToolsAgentHost`, I tried creating one with `RenderFrameDevToolsAgentHost::GetFor` https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/render_frame_devtools_agent_host.cc;l=388;drc=f0831f26cd194c819e0f3aa5920fdd88c8d2380e, but that returns `nullptr`.
I'll try some of the other functions in that file that look more promising, such as `RenderFrameDevToolsAgentHost::GetOrCreateFor`, tomorrow.

**Comment by deepak1556** [comment]
@Tyriar @eamodio if `Toggle Webview developer tools` action were to restore the old behavior, would `Toggle Developer Tools` action suffice for your use case or do you need a separate action to keep today's webview devtools behavior ?

**Comment by rzhao271** [comment]
Current progress https://github.com/rzhao271/electron/compare/e223b4db949ebc0e4e0076f0815305a55fb68d46..f802f45ec7a725e0f94ac0ae2dd3e1c9d716ab78

**Comment by Tyriar** [comment]
@deepak1556 `Toggle Developer Tools` is what I use today, as long as the webviews are included in there that's good for me as devtools stays open across reloads.

Here is the issue I created that explains the problem I had with toggle webview developer tools https://github.com/microsoft/vscode/issues/118919

**Comment by deepak1556** [comment]
> Toggle Developer Tools is what I use today, as long as the webviews are included in there that's good for me as devtools stays open across reloads.

Yup this will continue to work.

**Comment by deepak1556** [comment]
/cc @mjbvz 

Originally extracted from https://github.com/lostintangent/codeswing/issues/50

**Comment by mjbvz** [comment]
Using our standard editor developer tools for webviews has a few advantages: 

- You can inspect multiple webviews at the same time 
- You don't have to manage multiple windows
- You can view console logs from the extension and the webview in the same location 

Besides this issue, I haven't seen any other feedback requesting the old webview developer experience. We perviously used multiple dev tools because that was the only option when using `<webview>` tags, but I'm not sure it makes sense to try brining them back

**Comment by deepak1556** [comment]
Thanks for the feedback, closing for now.

@mjbvz can you please engage in https://github.com/lostintangent/codeswing/issues/50
