### ISSUE TITLE
Test: newWithProfile command intellisense and keybinding

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129429]
Refs: https://github.com/microsoft/vscode/issues/129140

- [x] macOS @weinand 
- [x] linux @JacksonKearl 
- [x] windows @tanhakabir 

Complexity: 2

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129429%0A%0A&assignees=meganrogge,Tyriar)

---
See https://github.com/microsoft/vscode/issues/126738 for context. 

Check that:
- you can provide a valid profile name to the new with profile command
- the keybindings for the command work
- you see detected and extension contributed profiles in the intellisense

**Comment by weinand** [comment]
@meganrogge since you mentioned "keybindings" in the test: the "Create Integrated Terminal (With Profile)" command on macOS does not have a key binding. I'm not sure whether this was your intention...

**Comment by Tyriar** [comment]
@weinand this was mainly about the keybinding intellisense for the command:

![image](https://user-images.githubusercontent.com/2193314/127162573-e9bcebe3-4a88-41e4-8399-10532869efa6.png)

**Comment by tanhakabir** [comment]
where should I verify intellisense? in the search in the command palette for the profile picker?

**Comment by meganrogge** [comment]
in the JSON settings @tanhakabir when you're setting `terminal.integrated.<platform>.defaultProfile`
