### ISSUE TITLE
Testing installing and uninstalling extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#129424]
Ref https://github.com/microsoft/vscode/issues/128114

- [x] anyOS @digitarald
- [x] anyOS @alexr00 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129424%0A%0A&assignees=sandy081)

---

Extensions installing and uninstalling has been refactored to support bulk extension enablement support. So please smoke  test installing and uninstalling extensions is working as expected. Also try testing installing extension packs. 

Also verify https://github.com/microsoft/vscode/issues/128088#issuecomment-875633115

**Comment by alexr00** [comment]
Tested on Windows.

**Comment by digitarald** [comment]
Tested on Mac.

Filed https://github.com/microsoft/vscode/issues/129711 the TPI mentions bulk installation and I ran into it again.
