### ISSUE TITLE
Clicking on settings.json in settings sync view does nothing when enabled split json setting

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#129494]
Steps to Reproduce:

1. Enable split json setting `workbench.settings.useSplitJSON`
2. Turn on settings sync
3. Open Settings Sync data view using command `Settings Sync: Show Synced Data`
4. Go to Sync Activity (Remote) view
5. Expand Settings entry and click on settings.json

🐛 Nothing happens

If you disable split json setting, then above interaction opens the diff editor.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/129083
