### ISSUE TITLE
Provide a way to collapse all cell inputs in a notebook 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#129488]
Originally requested by @TickboxPhil in https://github.com/microsoft/vscode-jupyter/issues/6811#issuecomment-887240119 

A command to collapse all, or adding multiselect handling to the existing Collapse Cell Input command, would significantly help users work with large notebooks containing lots of output.

**Comment by TickboxPhil** [comment]
As mentioned in that orig Issue, Collapse/Expand All Code would be great on the global toolbar - but if not wanting to clutter it further, command pallete or anywhere would still be big productivity gain when poring over and comparing multiple outputs and charts (for EDA, ML etc).

**Comment by gjsjohnmurray** [comment]
Adding it as an alt-command to the existing button would avoid adding another button. Here's an example of this being done with the Split Editor button on the regular editor:

![image](https://user-images.githubusercontent.com/6726799/127112349-087f968c-7a6f-4e5c-be55-de2a0d935586.png)

**Comment by TickboxPhil** [comment]
Agreed  @gjsjohnmurray, more than happy with Collapse/Expand All Code on the Command Pallet. 

And thanks for heads up - I don't use that Split Editor much yet, as still need to scroll past all the code when reviewing outputs, but it is useful and would become doubly so when the one window shows code, the other outputs. Would then be superior to PyCharm's split mode which has no collapse, poor layout and is also buggy on preview window (often showing nothing!).
