### ISSUE TITLE
[Test API] not able to disable individual test run/debug with RunProfile

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#129450]
Issue Type: <b>Bug</b>

In our extension (vscode-jest), we used the external jest watcher to auto-run tests when the tests or related source files change. In such use case, we used to disable manual test run for the individual test items (`TestItem.runnable = false`), while still supporting "restarting" the jest watch run for the workspace item. However, after switching to the new RunProfile, we lost the ability to disable the test run on the TestItem level and it would not make sense to fall back to "restart" jest run for the whole workspace...

Similar issue for debugging: we used to only support debugging on the file and individual test level, how to achieve this with the RunProfile?

We end up throwing errors in `runTest` to prevent the unsupported run/debug, which of course is not ideal. I know this issue has been raised in other discussions, this is now impacting our implementation, hopefully, it will get more urgent priority before release.

VS Code version: Code - Insiders 1.59.0-insider (Universal) (955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7, 2021-07-26T05:12:43.446Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (2.79GB free)|
|Process Argv|--enable-proposed-api Orta.vscode-jest --crash-reporter-id bb07f68d-9e6c-4982-a12f-528f81d06cb6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
The plan for this is to introduce test tags: https://github.com/microsoft/vscode/issues/122208#issuecomment-881922046

Let me know if you see any problems with that for your scenario.

**Comment by connectdotz** [comment]
thanks, @connor4312 As long as we can enable/disable the runProfiles at the TestItem level and update the UI (run/debug buttons) accordingly, it should work. But maybe we can get away with yet another identifier like tags? Anyway, I left the comment in #129456 for further discussion

**Comment by connor4312** [comment]
Ok, cool. Let's merge this into that one then
