### ISSUE TITLE
Help > Release Notes still goes to website

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12943]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 10

Should Help > Release Notes also display the release notes in product?

**Comment by joaomoreno** [comment]
We will go to the website as a fallback.

Insiders have no release notes, so we need to fallback to that.

**Comment by gregvanl** [comment]
Sorry, I should have been clearer. I configured insiders to display the release notes in the product (following the test plan).
In this case, shouldn't both the banner and Help > Release Notes both display the release notes in the product. 
Or is it by design that Help > Release Notes goes to the website just like Help > Documentation.

**Comment by joaomoreno** [comment]
I see!

**Comment by gregvanl** [comment]
Closing as there is a different issue https://github.com/Microsoft/vscode/issues/13050. Can't open in product release notes more than once.
