### ISSUE TITLE
Allow specifying the link in debug console

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#129405]
@roblourens 
## Problem Statement
If I use a custom logger that implements the imported console.log because I want to see the logs in the debug window, the links all point to where I called console.log, not where I called my custom logger.

### Contrived Example
![image](https://user-images.githubusercontent.com/15258962/126997901-d6e9c8f7-ec84-490e-a901-278013ec9c48.png)

## Feature Request
vscode's `console.log` should have an optional additional argument to specify the link to the log in the debug window.

## Workaround
The Debug console will render path links. This is noisy but it works.
![image](https://user-images.githubusercontent.com/15258962/126999224-33764fc4-bedf-4a72-99c1-18badfaeb56e.png)

**Comment by connor4312** [comment]
The recommended way to deal with this is to use the `skipFiles` option in your launch config. The location we show on the log output will be the first non-skipped location in the stack trace.

**Comment by JustinGrote** [comment]
@connor4312 nice, is this documented anywhere?

**Comment by connor4312** [comment]
It's under one of the bullets [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code). Yes, it's a little hard to find since you sort of have to know to look for it.
