### ISSUE TITLE
Test: terminal drag and drop between windows

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129419]
Refs: https://github.com/microsoft/vscode/issues/126387

- [x] macOS @donjayamanne 
- [x] linux @connor4312 
- [x] windows @claudiaregio 

Complexity: 3

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129419%0A%0A&assignees=meganrogge,Tyriar)

---
Try dragging and dropping between windows:
- terminals in the editor area to the tabs list
- tabs to the editor area
- tabs to the tabs list
- terminals in the editor area to the editor area

Check that all of those still work in a single window.

**Comment by connor4312** [comment]
Works beautifully

**Comment by claudiaregio** [comment]
Closing as tested and all worked for me :)
