### ISSUE TITLE
Request to be able to run and debug extensions in an empty VSCode instance

### ISSUE THREAD

**Issue by jamesinaxx** [microsoft/vscode#129479]
# I would like to be able to run and debug my extension in a clean, as if new instance of VSCode without any other extensions present

This feature would allow the extension being developed to run without being slowed down by other extensions.

## What currently happens
When I press F5 to run the extension I am working on, it starts a new VSCode instance with all my config, extensions, history, etc.

## What should happen
Have an option, in ```package.json``` for example, that allows you to start the extension in a clean instance of VSCode, with the ability to whitelist extensions and config to come with you.

So when I press F5 it starts an empty VSCode instance, as if I just installed VSCode, and the only extension installed is the one I am working on, and any whitelisted ones

## Example ```package.json``` config
``` jsonc
{
	// The rest of the package.json file
	"sandbox": {
		"enabled": true,
		"whitelist": ["esbenp.prettier-vscode"]
	}
}
```

**This is purely a quality of life feature that I think would be very beneficial and nice to have for VSCode extension developers, who want to test their extension without being weighed down by other extensions, or want to test it as if the user had just installed VSCode, without forcing them to actually get a fresh VSCode install.**

**Comment by weinand** [comment]
Using the command line flags `--extensions-dir` and `--user-data-dir` in a launch config should exactly do what you are asking for.
However, this does not yet seem to work.
