### ISSUE TITLE
Update changed my default terminal to pwsh??

### ISSUE THREAD

**Issue by spazmodius** [microsoft/vscode#129468]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```

### Steps to Reproduce:
I think all I did was install an update of vscode.

My default shell was `cmd`, but it changed without my input to `pwsh`.  If I exit the first terminal and open a new one, it does open `cmd`.

Trying `Select Default Profile` does not seem to do anything.  If I close vscode, it starts `pwsh` the next time it opens.

**Comment by meganrogge** [comment]
you are on a very old version of vs code. update to resolve this
