### ISSUE TITLE
order of json dicts not preserved in jupyter notebooks save files

### ISSUE THREAD

**Issue by JoranDox** [microsoft/vscode#129435]
## Environment data

-   VS Code version: Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-80-generic snap
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
-   Type of virtual environment used N/A
-   Jupyter server running: Local

## Expected behaviour

Make a small change, see only the change in git

## Actual behaviour

Make a small change, the whole file is changed according to git (order of json dict entries is suddenly changed)

## Steps to reproduce:

1. change something to a notebook in git
2. see this for every cell in the notebook: 
3. ![image](https://user-images.githubusercontent.com/7152733/126965555-6a71c7ca-1c76-4b7a-b09b-094352af0a1b.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Oh yes, looks like we aren't doing that.

**Comment by DonJayamanne** [comment]
Sure here you go https://github.com/microsoft/vscode-jupyter/blob/main/src/client/datascience/notebookStorage/vscNotebookModel.ts

**Comment by roblourens** [comment]
It looks like that function isn't called anywhere from vscode-jupyter though

**Comment by DonJayamanne** [comment]
> sn't called anywhere from vscode-jupyter though

Yes, as Joyce mentioned we're not using it. This was used in the old custom editor.

**Comment by roblourens** [comment]
@DonJayamanne already implemented this, thanks
