### ISSUE TITLE
Could not fetch remote environment Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006) 

### ISSUE THREAD

**Issue by YYYYWD** [microsoft/vscode#129483]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/25359077/127095978-c4f81274-4420-4c19-ba32-950accdef776.png)

2.

**Comment by AllendeJavier** [comment]
I'm facing the same problem

Version: 1.58.2 (user setup)
Commit: c3f1263
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sytlq999** [comment]
same problem also

**Comment by rzhao271** [comment]
\gifPlease

**Comment by sytlq999** [comment]
> Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, `.gif` files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.
> 
> If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (`Developer: Toggle Screencast Mode` in the command palette).
> 
> Happy coding!

I have some more details about this same  problem  in my post  below .Can you analyze it further
https://github.com/microsoft/vscode/issues/130887

**Comment by sytlq999** [comment]
Remote connection to Linux. After entering the password, there are two prompts on the right

coude not fetch remote environment
failed to connect to the remote extension host server (error: websocket close with status code 1006)

And the terminal  stuck and cannot input
The remote directory could not be loaded
I had tried countless times in many ways
Reinstall vocode，delete ~/.vscode - server/ directory,and so on .
What the hell should I do.

Steps to Reproduce:

[https://user-images.githubusercontent.com/89000778/130037063-4ff7b1f9-df48-416f-ac06-9b9f21c3c9f1.gif](url)

**Comment by alexdima** [comment]
@sytlq999 This error indicates that the VS Code window cannot open a connection to `127.0.0.1` (localhost), where the SSH extension has created a tunnel to the SSH machine. Is your computer configured to use proxies in any way?

**Comment by sytlq999** [comment]
> @sytlq999 This error indicates that the VS Code window cannot open a connection to `127.0.0.1` (localhost), where the SSH extension has created a tunnel to the SSH machine. Is your computer configured to use proxies in any way?

Thanks  for your reply
I donot know the proxy configuration of my computer ，how do I check and configure  to use proxies in any way.

**Comment by alexdima** [comment]
@sytlq999 Is your computer domain joined or would otherwise be configured by your company / IT department?

**Comment by sytlq999** [comment]
> @sytlq999 Is your computer domain joined or would otherwise be configured by your company / IT department?

My win10 computer in  company is connected to a tplink router which have a simpale 192.168.0.0/24 network , the remote linux  is in my home,I connected it to the tplink router via L2TP myself,there are no dedicated network managers.
Actually the first time I used vscode to test the connection to this remote computer,it was succeed,but  I didn't use it immediately,that was two months ago.

**Comment by alexdima** [comment]
@sytlq999 Could you please open developer tools (`F1` > `Developer: Toggle Developer Tools`) and share any output that appears there near the `WebSocket close with status code 1006` error.

**Comment by sytlq999** [comment]
> @sytlq999 Could you please open developer tools (`F1` > `Developer: Toggle Developer Tools`) and share any output that appears there near the `WebSocket close with status code 1006` error.
> 
> Also, could you please open the window logs (`F1` > `Developer: Show Logs...` > `Window`) and look at the output e.g.:
> 
> ```
> [2021-08-24 15:48:20.637] [renderer2] [error] [remote-connection][ExtensionHost][35667…][initial][127.0.0.1:51422] socketFactory.connect() failed or timed out. Error:
> [2021-08-24 15:48:20.637] [renderer2] [error] Error: WebSocket close with status code 1006
>     at WebSocket.<anonymous> (vscode-file://vscode-app/Users/alex/src/vscode/out/vs/platform/remote/browser/browserSocketFactory.js:82:42)
> ```
> 
> Does accessing `http://127.0.0.1:51422/version` where you replace `51422` with the port value that you have in your logs work for you in a browser?

Because I'm in hurry to use it,I have reinstalled the win10 system.
Now   this trouble is gone, the vscode could connect the remote normally.
If this problem happens again  , I will try this method and come here.
Thanks very much.

**Comment by alexdima** [comment]
:+1: Thanks for following up.
