### ISSUE TITLE
Test: forceRecreate proposed API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129449]
Refs: 

- [x] anyOS @rebornix
- [x] anyOS @sandy081

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129449%0A%0A&assignees=TylerLeonhardt)

---

We added a 3rd property to the options in `vscode.authentication.getSession` it allows you to ask the user to re-sign in. This is great for situations when SSO is lost on a token (like for GitHub).

To test this, make a new extension and play with the proposed API here:
https://github.com/microsoft/vscode/blob/26625e8fb3d931e6e5c7daf40a4e28e664e19ac3/src/vs/vscode.proposed.d.ts#L153-L183

Things to verify:
* It takes you through the flow and you get a dialog that says you are being asked to sign in again
* You get a new session (different access token) in the session that's returned:
```ts

const originalSession = await vscode.authentication.getSession('github', ['repo'], { createIfNone: true });
const newSession = await vscode.authentication.getSession('github', ['repo'], { forceRecreate: true });
console.log(originalSession);
console.log(newSession);
```
* If you abort the flow, the existing token should still exist so we don't mess up other extensions. Code to verify that might like look like this:
```ts
const originalSession = await vscode.authentication.getSession('github', ['repo'], { createIfNone: true });
let newSession: vscode.AuthenticationSession | undefined;
try {
    newSession = await vscode.authentication.getSession('github', ['repo'], { forceRecreate: true });
} catch (e) {}
const session = await vscode.authentication.getSession('github', ['repo']);
console.log(session);
console.log(originalSession);
```

**Comment by rebornix** [comment]
Works as expected, good work @TylerLeonhardt !

**Comment by sandy081** [comment]
Works pretty nicely 👏

**Comment by rzhao271** [comment]
Sandeep took care of Paula's slot. Closing the TPI
