### ISSUE TITLE
Support ChromeOS specific keybindings

### ISSUE THREAD

**Issue by dsnet** [microsoft/vscode#129486]
https://github.com/microsoft/vscode/pull/54894 added support for Linux, Mac, and Windows.

I propose the addition of a `isChromeOS` as determined from the web environment here: https://github.com/microsoft/vscode/blob/87346b6fb5c8b66094f8248c4c3740d0c509af04/src/vs/base/common/platform.ts#L101-L110

The user agent string for ChromeOS looks something like:
```
Mozilla/5.0 (X11; CrOS x86_64 13904.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.147 Safari/537.36
```
It's probably sufficient to just search for the string `'CrOS'`.

This is useful for ChromeOS since the operating has many OS-specified hotkeys that cannot be changed and conflict with those used by VSCode.

**Comment by vadi2** [comment]
It's important to have some Chromebooks don't have function keys, which VScode relies upon.
