### ISSUE TITLE
Test: Run By Line in Jupyter notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#129467]
Refs: #126431, #128582

- [x] windows @alexr00 
- [x] linux @bamurtaugh
- [x] macOS @misolori

Complexity: 3

Authors: @roblourens, @DavidKutu 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%23129467%0A%0A&assignees=roblourens,DavidKutu)

---

- Install ipykernel 6 or newer, which has debugging support
```
pip install ipykernel
python3 -m ipykernel install --user
or
pip install ipykernel --upgrade
```

- Make sure you have the latest version of the Jupyter extension installed in VS Code Insiders
- Set the experiment setting to enable Run by Line `"jupyter.experimental.debugging": true`
- Open a .ipynb notebook file
- Pick a kernel, make sure you pick the one where you installed ipykernel 6

- Click the Run by Line button in the cell toolbar

![image](https://user-images.githubusercontent.com/20347396/126576971-7570f42c-1197-44d4-a1b7-ca8f17a354ad.png)

The button takes a bit to appear, as it's checking that you have ipykernel 6

- A debugging session should start, without the status bar changing, without the debug widget and without revealing the debug sidebar automatically
- Press the same button to advance to the next line, or the stop button to end the session 
- Once you've stepped to the end of the cell, you have to press the stop button in the cell toolbar

### More testing
- It should not step into another cell or file
- Note: the flow above is the only entrypoint. launch.json is not relevant here.
- Test run by line in an untitled notebook
- You should never see an error that looks something like "Unable to open ..." with some tmp file path
- Test run by line in two notebooks simultaneously

### Known issues
- The run by line button takes a second to appear on notebook with valid kernels, it will be cached for the final release.
- The jupyter variables view is not enabled yet.
- There are two stop buttons visible (the normal cancel button and the RBL stop button in the cell toolbar) but these will be merged

**Comment by sandy081** [comment]
@roblourens I do not see Run by Line button in the cell toolbar. I installed  ipykernel as you mentioned in the instruction. Is there a way to check if I have done correctly? This is what I see

![image](https://user-images.githubusercontent.com/10746682/127134866-dfd9ef77-aa87-4a9b-8bfd-86ad60740fc0.png)

**Comment by bamurtaugh** [comment]
I also do not see Run by Line:

![image](https://user-images.githubusercontent.com/25310137/127208792-b6f253e6-a9df-4907-8740-cfa23925eb8c.png)

I am on Jupyter extension `v2021.8.1070546638`

**Comment by misolori** [comment]
Installing ipykernel only installs v.5.3.4 for me and there doesn't appear an option install v6 via Anaconda Navigator?

<img width="619" alt="CleanShot 2021-07-27 at 12 38 58@2x" src="https://user-images.githubusercontent.com/35271042/127217152-b14e2c5a-7e74-465c-a75d-311b13f17d93.png">

<img width="616" alt="CleanShot 2021-07-27 at 12 41 30@2x" src="https://user-images.githubusercontent.com/35271042/127217474-04376264-5aad-4824-9bc1-bd1ad31d1f9d.png">

**Comment by misolori** [comment]
Ok, I was able to upgrade via `pip install ipykernel --upgrade`, I assumed that installing ipykernel would install the newest version.

**Comment by bamurtaugh** [comment]
Another question - I needed to update my ipykernel version (as Miguel mentioned), but now that I've done that, should run by line work in a WSL environment? 

Before I jump to spinning up a Linux VM, wanted to understand if this was a limitation of WSL, an issue with the actual notebook/run by line, or something else (I usually test Windows or anyOS items so wasn't sure if it was expected WSL may not work).

![image](https://user-images.githubusercontent.com/25310137/127230346-5dff7959-9103-46bc-a1e5-c91eafa84a30.png)

**Comment by roblourens** [comment]
Sorry, I don't know why it wouldn't work in WSL. Did the notebook find you kernel, and did you select the right one?

**Comment by bamurtaugh** [comment]
Yes, I ended up installed Python 3.8 and Python 3.9, and it found both versions. I was able to select each one:

![image](https://user-images.githubusercontent.com/25310137/127240132-fba4f89f-a401-4e57-93c5-8d8445fe7d0c.png)

**Comment by roblourens** [comment]
And you can execute cells with it, and that's the one that you ran when installing ipykernel?

**Comment by bamurtaugh** [comment]
Yes it's letting me run cells:

![image](https://user-images.githubusercontent.com/25310137/127240694-0ae14947-7334-4402-831f-32ca09946cee.png)

> and that's the one that you ran when installing ipykernel

I was checking `jupyter --version` to check on my version of ipykernel, but realized it has the same output regardless of which kernel I have selected.

I'm also unsure what I should be seeing in the status bar. I'm used to seeing the Python version of the interpreter, but now it's gone:

![image](https://user-images.githubusercontent.com/25310137/127242294-635623d7-e557-4991-8e7c-3dae91e7276c.png)

I tried creating a virtual environment. Initially, it defaulted to Python 3.6.9, so I manually changed it to 3.9.6, and now the status bar reads "Python 3.9.6":

![image](https://user-images.githubusercontent.com/25310137/127242356-5be09404-2f0b-440d-a176-d61ede0931b4.png)

However, when I close the virtual env file, the status bar entry disappears:

![image](https://user-images.githubusercontent.com/25310137/127242402-8ddea2ac-08cc-4a27-89ba-24220f7adc1e.png)

Apologies if these are obvious setup questions - I haven't experienced these issues when running regular Python projects in WSL before, and for more complex setups, I usually use dev containers. But when I tried the notebook in a dev container in WSL, I also still didn't see the run by line.

**Comment by roblourens** [comment]
I use a virtual env and I recommend that, but it looks like the venv isn't active in your terminal and isn't selected in the notebook.

I had better instructions on setting up a venv for debugging in last month's test plan item, I should have posted these again

https://github.com/microsoft/vscode/issues/127362

**Comment by bamurtaugh** [comment]
Thanks for the links. I created an Azure VM and was just about to give up on WSL and use a VM with a venv for now until I realized the setting was grayed out:

![image](https://user-images.githubusercontent.com/25310137/127245845-a9665e28-5e8c-4e68-b6d0-3713c40c2d8f.png)

I needed to enabled it explicitly for the WSL or SSH remote (rather than just putting it in my local settings.json). Once I did that in WSL, I see run by line:

![image](https://user-images.githubusercontent.com/25310137/127245923-e71c0a03-9db9-4609-b096-822fa69c61d5.png)

(surprised it took me this long to realize this mistake 😅)

Now on to actual testing!

**Comment by roblourens** [comment]
Oh, that setting should not be machine scoped, I don't know why it is. I'll file an issue. Sorry for the trouble!

**Comment by sandy081** [comment]
@roblourens Please let me know if I am doing some thing wrong. I have install ipykernel  version 6.0.3 and enabled the setting `jupyter.experimental.debugging` and I still do not see the Run By Line action.

![image](https://user-images.githubusercontent.com/10746682/127284901-3b892a90-56db-449c-8180-687f7f849d20.png)

I am blocked on this to test.

**Comment by roblourens** [comment]
Sorry @sandy081, I think there is a problem with Conda. Thanks for taking it @alexr00

**Comment by weinand** [comment]
@roblourens just a meta-comment: preparing a Dockerfile for these complex setups is helpful. For my simple-jupyter-notebook I did just that...
