### ISSUE TITLE
[Test UI] Considering switching the color of the test message view

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#129492]
Version: 1.59.0-insider (user setup)
Commit: 955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7
Date: 2021-07-26T05:13:58.801Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

Currently in the test message view, the expected value will be rendered as red and actual value is green:
![image](https://user-images.githubusercontent.com/6193897/127118225-78edd46d-22b4-4c2b-a06a-9ac34d95f0c1.png)

Seems a little bit misleading to me, since I think most test frameworks use opposite colors:

![image](https://user-images.githubusercontent.com/6193897/127118418-a7393331-73ed-4bea-809f-f2ad33190a16.png)

@connor4312

**Comment by connor4312** [comment]
I've actually seen both in different test frameworks, which makes things even more fun 😂  One approach for this would be to have a code lens before the first line on each side that says "Expected:" or "Actual:"

**Comment by jdneo** [comment]
Haha, yes that sounds a good idea. Currently when I create the message via `diff()`, I added prefixes (Expected, Actual) before the values.

**Comment by heptapod42** [comment]
Hi @jdneo I'd like to work on this issue if that's okay. Could you tell me what needs to be done?

**Comment by jdneo** [comment]
@heptapod42 Feel free to take it if you want. While for what the UX will be looked like, may be @connor4312 is the right person to answer.

**Comment by connor4312** [comment]
We have a class that provides testing-related decorations for editors: https://github.com/microsoft/vscode/blob/87e0cb1d4394e87a4987d73190cc26740e3543e9/src/vs/workbench/contrib/testing/browser/testingDecorations.ts#L169

You can parse the current editor's URI using [parseTestUri](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/testing/common/testingUri.ts#L45) to see if (and what kind) of editor it is. If it's an expected or actual output, we should add a lens-like decoration on the first line.
