### ISSUE TITLE
Please show current branch name after the project name(folder) in the explorer

### ISSUE THREAD

**Issue by x-strong** [microsoft/vscode#129490]
It is useful, convenient and necessary showing the current branch name after the project name (folder) that like the bash prompt string along with the current branch name if the path is a git repository. Although the status bar shows the branch name, we can not get the focused project's (folder) branch name when in Explorer pane that has multiple project in a workspace, so to show the branch name after project (folder) is necessary, please consider to implement this feature, thanks!
@isidorn @eamodio

**Comment by x-strong** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Git: Preserve open files list when switching branches (#35307)](https://www.github.com/microsoft/vscode/issues/35307)
> * [Cannot push branch after delete origin (#122719)](https://www.github.com/microsoft/vscode/issues/122719)

No, it is not covered by those two issues.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks

I personally would not add this. But let's keep it open for now.

**Comment by lfvjimisola** [comment]
I would really like to see this implemented as it allows me to quickly see what branch I'm for a repository. Keep in that a workspace can contain more than one repository so just looking at the status bar is not enough.

**Comment by jfkfrb** [comment]
i strongly support this. i have many versions of the same repo checked out while reviewing / updating prs. the folders are asdf1,asdf2,asdf3,asdf4, etc. and they i switch branch on them regularly.

**Comment by venkatarenduchintala** [comment]
This should be a must have feature. It makes sense to see the `<repo>:<branch-name>` next to the folder in the explorer.

**Comment by chrift** [comment]
Has this been added yet?

**Comment by CiucurDaniel** [comment]
Any plans to bring this feature?

**Comment by tylertylerday** [comment]
Something as simple as this:

<img width="618" height="632" alt="Image" src="https://github.com/user-attachments/assets/7788db4a-b567-4ea8-aa1c-8539ea82b5c5" />
