### ISSUE TITLE
[Test Explorer] multiroot-workspace related issues 

### ISSUE THREAD

**Issue by connectdotz** [microsoft/vscode#129444]
Issue Type: <b>Bug</b>

1. the TestController displayed `id` instead of `label` in the explorer 
2. the test coverage did not display the overall (all workspaces) nor updated when the "active" workspace controller is changed
3. not sure if this is intended, but how should we run the coverage profile? 

VS Code version: Code - Insiders 1.59.0-insider (Universal) (955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7, 2021-07-26T05:12:43.446Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (2.79GB free)|
|Process Argv|--enable-proposed-api Orta.vscode-jest --crash-reporter-id bb07f68d-9e6c-4982-a12f-528f81d06cb6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
(1) was just fixed in https://github.com/microsoft/vscode/commit/472a308b0357b50c46fd4a18b71052e336abe355. Test coverage is still a WIP, tracking under https://github.com/microsoft/vscode/issues/123713.

**Comment by JacksonKearl** [comment]
Steps please :)

**Comment by connor4312** [comment]
1. Use the test provider sample https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample
2. Create a second controller and `ctrl.items.add` at least one test
3. In the Test Explorer tree view, verify that you see both controllers with their correct labels
