### ISSUE TITLE
Settings editor text input background lacks contrast in Quiet Light theme

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129453]
In Insiders (though the issue is probably in Stable, too):
1. Use the Quiet Light theme
2. Navigate to the settings editor.
3. Search "emmet". `emmet.extensionsPath` and `emmet.includeLanguages` settings should show up in the results.
4. Add at least one non-empty entry to each setting.
5. Edit both entries/place both entries in edit mode.
6. 🐛 On the inputbox that is not focused, the inputbox background colour is the same as the settings editor background colour.

![Demo](https://user-images.githubusercontent.com/7199958/127050023-9f60c7f9-b1c7-470b-8db5-959a05bde501.PNG)

**Comment by meganrogge** [comment]
@rzhao271 I'm not seeing either of those settings

**Comment by meganrogge** [comment]
but verified using files.exclude
