### ISSUE TITLE
Test: Object Validation in the Settings Editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129448]
Refs: https://github.com/microsoft/vscode/issues/128429

- [x] macOS @TylerLeonhardt
- [x] linux @brettcannon
- [x] windows @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129448%0A%0A&assignees=rzhao271)

---

1. Create an extension, or find an existing extension.
2. Add an object setting where `additionalPropeties` is either `false` or an object, and where all values are type `string` or `boolean` (otherwise the setting won't render in the settings editor. Here's an example setting:

```json
"emmet.hmm": {
  "type": "object",
  "patternProperties": {
	"^#": {
	  "type": "string",
	  "description": "here here"
	}
  },
  "properties": {
	"la": {
	  "type": "string",
	  "enum": ["a", "b", "c"]
	},
	"lb": {
	  "type": "string",
	  "enum": ["b", "c", "d"]
	}
  },
  "additionalProperties": {
    "type": "boolean"
  },
  "default": {}
}
```

3. Try passing in invalid values in the JSON editor or the GUI editor. The number of errors the GUI editor displays should be greater than or equal to the number of errors the JSON editor displays.

**Comment by TylerLeonhardt** [comment]
@rzhao271 any chance that number and integer could be supported? Array and object are bit more complex.

**Comment by rzhao271** [comment]
@TylerLeonhardt I think numbers and arrays are already supported. The validation for objects is new.

**Comment by brettcannon** [comment]
Probably not important to anyone, but to keep notes about what I had to look up:
- https://code.visualstudio.com/api/get-started/your-first-extension to create an extension from scratch
- https://code.visualstudio.com/api/references/contribution-points#contributes.configuration for configuration docs
- https://json-schema.org/understanding-json-schema/reference/object.html?highlight=patternproperties#additional-properties for what `additionalProperties` is
