### ISSUE TITLE
Extension telemetry log output channel

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#129474]
1.59.0-insider
955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7
arm64

Out of the box I see two output channels named `Log (Extension Telemetry)`:

![image](https://user-images.githubusercontent.com/4674940/127078052-729b1648-1685-443c-97c7-6fad4065701e.png)

There should be only one, and it should be below the separator as it is not specific to a specific extension. It's comparable to `Log (Extension Host)`. 

Also, I wonder whether it should be there all the time. We only show the core log (`Log(Telemetry)`) if you set the logging level to `verbose`. I think the extension telemetry log should behave the same.

**Comment by lramos15** [comment]
The two logs appearing in separate places is definitely a bug but I cannot fix the log level nor the location of the log as this log is contributed by extensions and we have no APIs for placing an output channel in that location nor reacting to the log level.
