### ISSUE TITLE
when right clicking, my context menu is sometimes opened and immediately clicks an entry

### ISSUE THREAD

**Issue by Corallus-Caninus** [microsoft/vscode#129454]
Issue Type: <b>Bug</b>

This occurs about 1/4 of the time everytime I right click. I have begun ablating my extensions to see if one of them is the culprit but it's frequent enough I thought I should open an issue. Please let me know how I can be of further assistance.

1. right click
2. menu is opened and immediately closed selecting an entry, sometimes formatting/altering
    the current page.

Thanks for all you do VSCode is amazing.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 4649)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (3.55GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id ee126cf6-d2f9-458e-bd28-4ce663ce51c4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
gitlens|eam|11.6.0
rust-in-peace|gil|0.2.6
copilot|Git|1.2.2126
vscode-test-explorer|hbe|2.20.4
MagicPython|mag|1.1.0
camelcasenavigation|map|1.1.3
cortex-debug|mar|0.3.13
rust-analyzer|mat|0.2.686
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
test-adapter-converter|ms-|0.0.13
crates|ser|0.5.9
strict-whitespace|sid|0.0.2
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.14.2
cmake|twx|0.0.17
errorlens|use|3.3.1
vscodeintellicode|Vis|1.2.14
vim|vsc|1.21.5
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by ntjess** [comment]
For me, this happens only with my external mouse (More than 1/4 of the time, though). If I use my touchpad to right-click, everything works fine.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/113175
