### ISSUE TITLE
False detection of 'PROBLEMS'

### ISSUE THREAD

**Issue by christo070** [microsoft/vscode#129442]
Issue Type: <b>Bug</b>

The issue occur occasionally when writing code, so I could not provide exact steps to reproduce it.
Visual Studio Code showing False detection of errors at 'PROBLEMS' in panel( the panel where Problems, Output, Debug Console and Terminal Sections are present ). It is showing errors based previous typed characters because it  occasionally freeze updating the 'problems section in panel' while writing code. The issue will get resolved only when I restart VSCode. I am having this issue while using WSL2, so not sure whether it will happen when not using WSL2.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (10.54GB free)|
|Process Argv|--crash-reporter-id d78d9355-a45d-4e31-8ebf-f056601abaf7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (2 x 1382)|
|Memory (System)|3.84GB (3.40GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remote-wsl|ms-|0.58.2
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.8.0
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.10.1
material-theme|zhu|3.11.1
competitive-programming-helper|Div|5.8.5
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
cpptools|ms-|1.5.1
vscodeintellicode|Vis|1.2.14

</details>

**Comment by sandy081** [comment]
Please file the issue against the extension that is generating these problems.
