### ISSUE TITLE
update go.icns

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#129480]
https://github.com/microsoft/vscode/blob/main/resources/darwin/go.icns 

In https://github.com/microsoft/vscode-go/issues/1982, we updated the default go file icon in vscode,  but didn't update this icon.

If use of a different file icon is ok, I hope this go.icns to be replaced with a gopher that preserves its original cuteness.
If it is not, I hope this to be replaced with the official go project logo (https://blog.golang.org/go-brand) to match the go file icon used inside vscode.

**Comment by misolori** [comment]
I think it's best to match the default so I'll replace the gopher with the new branding.

**Comment by misolori** [comment]
Updated

<img width="643" alt="CleanShot 2021-09-13 at 16 12 28@2x" src="https://user-images.githubusercontent.com/35271042/133168802-5b408f72-1794-46fe-ab7d-a1f0ae937f5b.png">
