### ISSUE TITLE
Test extension view UX improvements

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#129422]
Ref https://github.com/microsoft/vscode/issues/126479, https://github.com/microsoft/vscode/issues/118511

- [x] macOS @rebornix 
- [x] linux @karthiknadig 
- [x] windows @hediet 

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129422%0A%0A&assignees=sandy081)

---

- Test extensions viewlet improvements
  - Rating and install count are shown only for uninstalled extensions
  - Installed extensions show activation item instead (if they are activated)
  - When you decrease the width of extension viewlet to 250px, icon size is reduced
  - When you decrease the width of extension viewlet to 200px, icon and ratings are not shown.

- Test extension editor details tab improvements - now shows categories, resources and other info details in the right. 
  - Test rendering of these details 
  - Test clicking on a category will open extensions viewlet and filter by selected category.
  - Test clicking on resource links

- Test Runtime status
  - Test extensions which are activated show the activation time on the extension in the extension viewlet, hovering on extension in the extension viewlet and in Runtime status tab when you open the extension. Hover & Runtime status tab also mentions about startup if the extension is activated during startup.
  - Test runtime status tab (in extension editor) is shown only for installed extensions
  - Test that descriptive extensions like themes show no status in the runtime status tab (in extension editor)
  - Test that extensions with code and are not activated will have not yet activated status in runtime status tab (in extension editor)
  - Create a sample extension that contributes a setting that is already registered eg., `css.completion.completePropertyWithSemicolon` and run this extension
  - Test that hovering on above extension in the viewlet shows warning link and clicking on that takes you to the runtime  status tab.
  - Test runtime status tab for this extension shows a warning message about above setting.

**Comment by rebornix** [comment]
@sandy081 it works pretty well, good work!
