### ISSUE TITLE
Test: Workspace trust - trust parent folder in remote scenarios

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#129410]
Refs: #128691

- [x] wsl @rzhao271
- [x] ssh @weinand

Complexity: 3

Authors: @lszomoru, @sbatten

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129410%0A%0A&assignees=lszomoru,sbatten)

---

This milestone we have added the capability to trust the parent folder in the remote scenarios. 

### Startup prompt
1. Open an untrusted folder in VSCode in a window connected to the remote (WSL/SSH)
    * Confirm that the workspace trust startup dialog is being shown
    * Confirm that the dialog contains the checkbox to trust the parent folder
    * Confirm that the parent path is correct
2. Click on the button to trust the workspace
3. After the window initialises, open the workspace trust editor 
    * Confirm that there is an entry for the parent folder in the list of trusted folders & workspaces

### Workspace trust editor
1. Open an untrusted folder in VSCode in a window connected to the remote (WSL/SSH)
2. Click on the button to open the workspace in restricted mode
3. After the window initialises, open the workspace trust editor 
    * Confirm that there is a button to trust the parent folder in the box on the left hand side
4. Click the "Trust Parent" button
    * Confirm that the workspace transitioned to a trusted workspace 
    * Confirm that there is an entry for the parent folder in the list of trusted folders & workspaces

**Comment by weinand** [comment]
Everything was working fine on macOS connected via SSH to ubuntu 20.10 LTE
