### ISSUE TITLE
QuickFix selection reset

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#12949]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:05:08.351Z)
- OS Version: Darwin x64 15.6.0

Found verifying #12531

Steps to Reproduce:

1. Add compile error in C#
2. Before or right after the squiggles are shown open QuickFix with the keyboard shortcut
3. Quickly move the selection down a few entries in the list of QuickFixes
4. Wait and observe: The selection goes away

Not a regression because in 1.5.3 the drop-down closed instead.

**Comment by jrieken** [comment]
This is obsolete because we now use the native context menu which we don't update anymore in case changes happen after it opened.
