### ISSUE TITLE
With tabs disabled, dirty indicator doesn't change to Close X on hover.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#12947]
- VSCode Version:1.6.0 insiders
- OS Version: Windows 10

When Tabs are disabled, the dirty indicator was moved to cover the Close button at the right side of the editor group title bar. 
Should hover display the Close button "x"? The tooltip ("Close") is displayed but the dirty indicator circle remains.
This is not consistent with OPEN EDITORS and when Tabs are enabled where hover shows the Close "x"

**Comment by bpasero** [comment]
Investigating...

**Comment by bpasero** [comment]
@gregvanl great catch and sense for detail 👍
