### ISSUE TITLE
Allow users to configure default MIME type for rendering notebook cell outputs

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode#129434]
Dafault MIME type
![image](https://user-images.githubusercontent.com/33288114/126894608-3e5693d0-a377-4bdc-9a19-64e98819709e.png)

i want  the dafault the type is svg
![image](https://user-images.githubusercontent.com/33288114/126894627-b06add11-8beb-4b68-adfe-1dc5b85f6452.png)

**Comment by connor4312** [comment]
@rebornix not sure if this is still relevant or if it's already been done

**Comment by rebornix** [comment]
The user choice will be persistent now.
