### ISSUE TITLE
Native IW (and notebooks really) There's no reason to show mime-type selection for output when a cell is collapsed.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129420]
Why bother showing the ellipses when a cell is collapsed? Adds unnecessary noise and may seem like a broken feature for some users, since choosing a different mimetype on a cell with collapsed output doesn't do anything visible.
![image](https://user-images.githubusercontent.com/11685408/127017478-cd961166-45f8-4c4b-b26a-4b17f86cb049.png)

**Comment by joyceerhl** [comment]
Cell inputs and outputs can be separately collapsed. Is the cell output collapsed in this screenshot? If cell output is not collapsed, I think it's legitimate to render the output actions menu so users can change the renderer for the output.
