### ISSUE TITLE
Inconsistent Behavior When Using 'Toggle Word Wrap' and 'editor.wrappingColumn'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12942]
- VSCode Version: 1.6 Insiders
- OS Version:

##### Steps to Reproduce

1. Add `"editor.wrappingColumn": 40` and `"editor.wordWrap": true` user settings. 
2. Open a document with a long long.
3. Toggle Word wrap (should disable word wrap)
4. Toggle word wrap again.

##### Expected
Text wraps back to the 40 column mark.

##### Actual
Text wraps to the editor frame boundaries instead.

![sep-28-2016 10-28-18](https://cloud.githubusercontent.com/assets/12821956/18932451/4e3cf8ac-8585-11e6-9bf7-955b53653243.gif)

I'd expect the text in this case to render the same as it does with  `"editor.wrappingColumn": 40` and `"editor.wordWrap": true` applies. Changing the `wrappingColumn` setting causes it to render properly.

**Comment by Phisherman** [comment]
Version 1.5.3 behaves the same way.

**Comment by mjbvz** [comment]
Duplicate of #6433
