### ISSUE TITLE
Checkboxes do not render in an Extension's README

### ISSUE THREAD

**Issue by asklar** [microsoft/vscode#129473]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.57.0
- OS Version: 22000.100

Steps to Reproduce:

I wrote an extension, and have a readme.md at the root, where I use checkboxes like:
```markdown
- [ ] unchecked item
- [X] checked item
```

However, the extension page in VSCode renders those as list items without the checkboxes

![image](https://user-images.githubusercontent.com/22989529/127078031-2e587aa1-1be4-46ab-ade5-5d274d6f49f6.png)

**Comment by mjbvz** [comment]
Are they rendered in the marketplace's web pages?

**Comment by asklar** [comment]
I haven't published my extension to the marketplace yet so I can't check if the checkbox in my extension would be rendered on the marketplace website, i'm also not sure how i would search the marketplace to find an extension whose readme uses checkboxes :D

**Comment by mjbvz** [comment]
Ok, I'm going to close this then since checkboxes are not part of the standard markdown spec (which is what we target with our built-in markdown rendering)

**Comment by tjx666** [comment]
> Ah, figured out an ideal alternative lol. Decided to put them in code blocks instead so they render well.
> 
> ```
> - [x] item 1
> - [x] item 2
> - [ ] item 3
> ```

But this look not good in github readme...

@joshxyzhimself @mjbvz
