### ISSUE TITLE
quickopen **/* sometimes does show all results as matches

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1294]
I would expect in the following case that the first two files are also shown as matched in dark blue.

<img width="535" alt="screen shot 2015-12-14 at 16 50 12" src="https://cloud.githubusercontent.com/assets/1926584/11785613/ecd26dee-a282-11e5-8dfc-64519d0c63e7.png">

**Comment by bpasero** [comment]
I think this is just an issue with how we highlight differently for the editor history. Might also be related to wildcard highlighting.
