### ISSUE TITLE
TODO can't work with TeX file

### ISSUE THREAD

**Issue by imjiangjun** [microsoft/vscode#129496]
Issue Type: <b>Bug</b>

TODO finds nothing in any TeX file. But there are actually many "TODO"s.
However, it works well with other languages, e.g. python.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.35GB free)|
|Process Argv|--crash-reporter-id 3516826e-8aa2-4d38-b93a-7777f7a2c63d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
shell-syntax|bma|1.0.1
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
vscode-firefox-debug|fir|2.9.4
shell-format|fox|7.1.0
todo-tree|Gru|0.0.213
latex-workshop|Jam|8.19.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.15.0
vscode-language-pack-zh-hans|MS-|1.58.8
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
debugger-for-chrome|msj|4.12.12
vscode-yaml|red|0.21.1
explorer-exclude-vscode-extension|Red|1.2.0
bash-debug|rog|0.3.9
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

See https://github.com/Gruntfuggly/todo-tree/issues/357#issuecomment-678626475
