### ISSUE TITLE
Test custom hovers in extensions view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#129421]
Ref https://github.com/microsoft/vscode/issues/126479, https://github.com/microsoft/vscode/issues/118511

- [x] macOS @kimadeline 
- [x] linux @karthiknadig 
- [x] windows @lszomoru (Dev Container)

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23129421%0A%0A&assignees=sandy081)

---

Extensions in extension viewlet now shows custom hovers. Please test these hovers for following scenarios

- Installed extensions
- Uninstalled extensions
- Recommended extensions - shows recommendation reason
- Extensions disabled by you - shows disablement reason
- Extensions disabled automatically or has limited functionality in an untrusted workspace. Eg: ESLint & Gitlens
- Extensions disabled automatically in virtual workspace - Use github.remotehub extension to open virtual workspace and open `Workspace Unsupported` filter.

Please test following in Dev Container

## Set Up

- Open VS Code on an empty folder
- Install `ms-vscode-remote.remote-containers` and `scalameta.metals` extensions
- Run command `Add Development Container Configuration Files...` and select `Node.js`
- Reopen the folder in container
- Test that hovering on `scalameta.metals` extension show proper message with a link to learn more. Make sure that link is taking you to the proper documentation.
- Click on `Install in Dev Container: Node`  action on `scalameta.metals` extension which will install `scalameta.metals` and its dependency `scala-lang.scala` extensions in remote container.
- Hover on `scala-lang.scala` extension in `Dev Container:Node.JS - Installed` section and and test that hover shows appropriate message.

**Comment by lszomoru** [comment]
@sandy081, due to #129557 I am blocked from validating the second and third bullet point for the WSL steps.

**Comment by karthiknadig** [comment]
FYI, for my testing I am using Linux Mint 19.1:
![image](https://user-images.githubusercontent.com/3840081/127214116-9c9f36d7-9cb7-47c3-9b10-0182e7370a2c.png)

**Comment by sandy081** [comment]
@lszomoru changed the steps to use remote containers instead of WSL. Please try it out now.

**Comment by lszomoru** [comment]
I have tested the steps using remote-containers on the Mac. I have added my findings into [this comment](https://github.com/microsoft/vscode/issues/129557#issuecomment-888148608).
