### ISSUE TITLE
User tasks can't be run in single file mode

### ISSUE THREAD

**Issue by tenzinhl** [microsoft/vscode#129415]
Issue Type: <b>Bug</b>

Steps to reproduce:

- Freshly install vscode on Windows 10
- Open a single file (not folder or workspace)
- Open command palette
- See that "Tasks: *" commands are available (Expected: not available, since tasks are not supported when opening single files)

The rest of the steps are the confusing behaviors that I experienced because I thought the UI was telling me that I could access user tasks when editing a single file.

- Select "Tasks: Configure Tasks"
- Create the generic tasks.json from template (I think it was called "Other")
- Select "Tasks: Run Task"
- Only "Configure a Task", "typescript", and "Show all Tasks" are available options even though the user `tasks.json` specifies a task. Trying to go into any of these options leads to dead ends.

My understanding after some searching is that to not mislead users to think that tasks can be run and are available for single files (as I got quite confused lol) is to not show task related options when vscode is opened for a single file (based on: https://github.com/microsoft/vscode/issues/1146#issuecomment-169268265). I would appreciate that behavior here as well.

Also, I checked the insiders version and this behavior was still present

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by alexr00** [comment]
User tasks should indeed be available in single file mode. This is a regression that occurred a few months ago. Thank you for reporting it!

**Comment by alexr00** [comment]
To verify:
- Open VS Code without a folder
- Tasks: Run Task
- If you have a user task already, run it.
- Otherwise, choose the configure task option and choose "other" for a good default. Then Run Task and run the task.
- Verify that the user task run successfully.

**Comment by alexr00** [comment]
Fixed by bedf59228c20dabea2ce3f70486d177332582aa6

**Comment by tenzinhl** [comment]
Thank you! I'll test this out when I get the chance.

**Comment by tenzinhl** [comment]
Also, I don't know if this is the right place to put this, but could the documentation be updated to reflect this please?
https://code.visualstudio.com/docs/editor/tasks
> Note: Task support is only available when working on a workspace folder. It is not available when editing single files.

^Maybe add a note saying that user-level tasks should be available for single files as well?
And preferably in the user tasks section too:
https://code.visualstudio.com/docs/editor/tasks#_user-level-tasks

**Comment by alexr00** [comment]
@tenzinhl thanks for the docs reminder! I'll make an update.

**Comment by alexr00** [comment]
\closedwith bedf59228c20dabea2ce3f70486d177332582aa6

**Comment by tenzinhl** [comment]
/verified
Ran simple echo task in file mode with no folder open with some simple variable substitution. It worked! Let's gooo. Thank you @alexr00 , this will allow me to use my competitive programming workflow a lot easier (without extensions) when I save a file directly rather than in folder mode 👍

**Comment by alexr00** [comment]
Not sure what's up with the bot. Thanks for verifying @tenzinhl !
