### ISSUE TITLE
Unresponsive keyboard in VSCode when attempting to edit code

### ISSUE THREAD

**Issue by tompinataro** [microsoft/vscode#129430]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: most recent downloaded 10 days ago
- OS Version: Big Sur 11.4

Steps to Reproduce:

1. Reboot MacBook Pro
2. Open any file in VS Code
2. get unresponsive keyboard
3.  Can this be fixed or does VS Code need to be removed and reinstalled?

**Comment by tompinataro** [comment]
The keyboard became unresponsive while editing an HTML file in VS Code.
I opened a new file, pasted some html and attempted to edit the lines and only the arrow keys would work. The space key only worked as to advance the location of the cursor.

**Comment by meganrogge** [comment]
does this happen in other apps too or just when using an editor in vscode?

**Comment by tompinataro** [comment]
Just in VS Code.

**Comment by meganrogge** [comment]
Please run the command keyboard shortcuts troubleshooting and provide us with the logs as you press keys
