### ISSUE TITLE
Provide code examples of where the inlay hints show up in settings descriptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129517]
Testing #129381

![image](https://user-images.githubusercontent.com/2193314/127154200-9859fb89-3ae5-4518-b72b-f80970d11f9c.png)

It would be helpful if this shows an example, something like:

```ts
function f(arg: number) {}
f(/*arg:*/10);
```

**Comment by mjbvz** [comment]
The current formatting in the settings UI isn't ideal but hopefully these examples help explain what these settings do

**Comment by Tyriar** [comment]
Thanks, the examples are great 👍
