### ISSUE TITLE
Duplicated "Create Integrated Terminal (With Profile)" commands

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129514]
Testing #129429

- press F1 and enter "Terminal"

Observe:
<img width="650" alt="2021-07-27_14-25-20" src="https://user-images.githubusercontent.com/1898161/127153237-b457fc15-5b43-409f-b404-db296fc9cd3b.png">

there are two "Create Integrated Terminal (With Profile)" commands and they are too long to see a difference in the QuickPick (if there is any...)

**Comment by Tyriar** [comment]
Oh this is happening because the command gets re-registered to apply the new schema. Hopefully we can unregister to avoid this.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/blob/6102a7d263636bf6233b2c2c6e75a511146c752b/src/vs/platform/commands/common/commands.ts#L68-L68
