### ISSUE TITLE
Folding Navigation Commands Sometimes Don't Work

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#129503]
Testing #129353

![recording](https://user-images.githubusercontent.com/2931520/127130120-2db11bf2-d7e3-4fce-9e9a-e66ea9d1a1df.gif)

index.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.activate = void 0;
const vscode = require("vscode");
function activate(context) {
    vscode.window.showInformationMessage('hello world');
}
exports.activate = activate;
//# sourceMappingURL=index.js.map
```

There is a foldable element, but "Go to next fold" does nothing. I'm hitting F1 -> Enter.

**Comment by DonJayamanne** [comment]
Same here with python code:
```python
if True:
    print('Two')

if True:
    print('Two')
```

**Comment by ssigwart** [comment]
@aeschli and @DonJayamanne, I can take a look.  I think it's because those folds don't have a parent fold.
