### ISSUE TITLE
List: Dragging an element causes focus to jump to container when DnD disabled

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#129582]
Testing #129161

@yuehuang010, @xisui-MSFT
Drag and drop within the disassembly view causes the focus to jump into the parent container. I would expect on mouse release nothing happens and focus remains on the same instruction entry.

**Comment by xisui-MSFT** [comment]
@isidorn Not sure how to fix this. Any suggestions?

**Comment by isidorn** [comment]
This happens in all list views that have drag and drop disabled. So it is a general list thing.
I would personally not fix this. However forwarding to @joaomoreno so he can close as designed.

**Comment by lramos15** [comment]
> This happens in all list views that have drag and drop disabled. So it is a general list thing.
> I would personally not fix this. However forwarding to @joaomoreno so he can close as designed.

From an accessibility standpoint is it weird that accidental DnD can cause focus to jump away from the last focused element?

**Comment by isidorn** [comment]
Screen reader users that heavily rely on focus usually do not use the mouse thus they do not use DnD.
Though I agree that the focus jump is a bit weird, and ideally focus would stay in the same spot.

**Comment by joaomoreno** [comment]
Closing as won't fix.
