### ISSUE TITLE
Extension hover - it's inconsistent when we show/hide hover

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#129559]
Testing #129421

Notice how the moment we show and hide the hover is inconsistent between the two extension lists:
![recording](https://user-images.githubusercontent.com/3372902/127183146-e17083c2-59b4-430d-863b-190f12a491cd.gif)

I believe that this is due to the fact that the list of top has a scroll bar, and when the mouse reaches the scrollbar, the hover is hidden. This could be problematic in case there is an actionable element (ex: link) in the custom hover that would have to be clicked as one needs to be real quick to get the mouse in the hover.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/128998
