### ISSUE TITLE
Extension hover - scalameta.metals gets installed in WSL

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#129557]
Testing #129421

Repro steps:
1. Open VSCode with an empty window
2. Install the `scalameta.metals` extension
3. Use the remote indicator to open a new WSL Window
4. In the new WSL Window I see that the extension is installed in WSL which is contradictory to the test plan item steps
![image](https://user-images.githubusercontent.com/3372902/127180164-6f7a30ce-cd9a-4490-894d-9fe33e7c46b8.png)

**Comment by sandy081** [comment]
Do you have settings sync on?

**Comment by lszomoru** [comment]
Yes I do. Should I turned off?

**Comment by sandy081** [comment]
Yeah, can you please turn it off? Uninstall them locally and in WSL and retry?

**Comment by lszomoru** [comment]
I am able to reproduce the issue even with settings sync disabled.

**Comment by sandy081** [comment]
Hmm weird, I am not sure what is syncing these extensions locally and remotely. Lets debug this together tomorrow. 

Actually any remote set up is good enough to test this test plan item, wsl is not mandatory. I picked WSL just because of set up simplicity. I will update the test plan item to use dev containers instead.

**Comment by lszomoru** [comment]
I have run some tests with the remote containers extension and here are mu observations:
* Started VSCode with a new user-data-dir and extensions-dir.
* Installed the remote containers and scalameta.metals extensions.
* Opened the folder in a container, and the scalameta.metals extension was installed locally.
* Clicked on the button to install the extension in the container. 
* Closed VSCode.
* Started VSCode with a new user-data-dir and extensions-dir.
* Installed the remote containers and scalameta.metals extensions.
* Opened the folder in a container, and the scalameta.metals extension was now installed in the container and not locally.

Is there a chance that we somehow persists the fact that an extension has been installed in the remote?

**Comment by sandy081** [comment]
> Opened the folder in a container, and the scalameta.metals extension was now installed in the container and not locally.

Not locally? Do you mean it got uninstalled locally?

> Is there a chance that we somehow persists the fact that an extension has been installed in the remote?

We do not. I think the extension exists in the remote container as the remote containers extension is using the same container as before.

**Comment by lszomoru** [comment]
> We do not. I think the extension exists in the remote container as the remote containers extension is using the same container as before.

Yep, that was it.

**Comment by sandy081** [comment]
I hope we are not getting side tracked here. Is it the same issue as described in the description is the problem here?

**Comment by lszomoru** [comment]
I believe so. In case of WSL, I guess we remember the first time the extension is installed in the distro so until you continue to connect to the same distro, independent which folder you open, the extension will always be installed by default on the WSL side. I am closing the issue.
