### ISSUE TITLE
Extension custom hover - consider defining max-width

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#129546]
Testing #129421

![image](https://user-images.githubusercontent.com/3372902/127170550-7ea8ea4b-52ee-409c-a743-4cc9ca273d17.png)

**Comment by sandy081** [comment]
@Tyriar is it an hover bug?

**Comment by Tyriar** [comment]
Looks like it

**Comment by sandy081** [comment]
Do you want to look into it then?

**Comment by Tyriar** [comment]
Started on this, figured out a pretty nice approach with a new option that restricts the hover dimensions when it's important that the hover position doesn't change:

```ts
	/**
	 * Force the hover position, reducing the size of the hover instead of adjusting the hover
	 * position.
	 */
	forcePosition?: boolean
```
