### ISSUE TITLE
Disassembly view: double click on instruction breakpoint should pass focus to disassembly view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129523]
Testing #129161

fyi  @yuehuang010, @xisui-MSFT

Single click on the instruction breakpoint properly reveals that instruction breakpoint - great.
Double click should pass focus to the disassembly view. Just like we do for regular breakpoints

**Comment by xisui-MSFT** [comment]
@xisui-MSFT Will fix this.
