### ISSUE TITLE
Extension hover - recommended extensions

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#129549]
Testing #129421

We seem to be following the pattern in the hover:
- Extension name
- Extension details about enablement/capabilities/activation/etc.
- Separator
- Extension description

![image](https://user-images.githubusercontent.com/3372902/127173210-53d359aa-c09a-4dce-adff-7bd66eecd88f.png)

This pattern is not being following with recommended extensions:
![image](https://user-images.githubusercontent.com/3372902/127173358-377e8e24-bd2e-4f8d-90c9-63eff5dc0cec.png)

I would move the reason of why the extension is recommended above a separator. 

Where this looks really weird is with an extension like GitLens where you have meta-data both above and below the description:
![image](https://user-images.githubusercontent.com/3372902/127173631-f569de9f-9c2e-4002-a402-19bff4130ff2.png)

**Comment by sandy081** [comment]
I placed the recommendation text at the bottom (after description) as it is not so important than other information. Also from look perspective, I felt it looked better at the bottom. If we move this above separator, it will looks as below

<img width="970" alt="image" src="https://user-images.githubusercontent.com/10746682/127178133-7a52cc4a-fffe-449d-a118-d0a80e5a13f2.png">

@misolori any recommendations?

**Comment by misolori** [comment]
I'd probably say that the extension meta data (recs, activation, etc.) should go at the very bottom with a separator as that is the least important information. I'd also move the description into the main section instead. So it would be like:

<img width="535" alt="CleanShot 2021-07-27 at 08 22 51@2x" src="https://user-images.githubusercontent.com/35271042/127181407-8465bdaa-a934-4226-a709-638bffd27af6.png">

**Comment by sandy081** [comment]
Changed it as recommended

![image](https://user-images.githubusercontent.com/10746682/127220850-1797ae15-a26e-428d-a8fd-cb40879f32d8.png)
