### ISSUE TITLE
We should use VS Code language information to fine tune our language detection

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129596]
Testing #129436

We should use VS Code language usage to fine tune our language detection.
For example Javascript, Typescript and Python should have increased weight and be more easy to detect.

I can dig up our usage language data if needed.

**Comment by TylerLeonhardt** [comment]
@claudiaregio found this great example https://github.com/microsoft/vscode/issues/129730

**Comment by TylerLeonhardt** [comment]
> I can dig up our usage language data if needed.

Did you already give me this? I'm not sure.

**Comment by isidorn** [comment]
Replied to you now privately with our stats.

**Comment by TylerLeonhardt** [comment]
Here's my take on this: 4735c328d7016bf951af86c5b523bd89d1cb67c4 

additionally, I negatively boosted languages that are not used much and are too simple (meaning their syntax is too close to spoken word, like batch)

verification is really just find some code samples online and paste them in an untitled editor.

**Comment by TylerLeonhardt** [comment]
this snippet use to be called SQL but now stays plaintext:

```
Amet ut aliquip laboris ex duis. Dolore magna proident proident sint veniam magna culpa. Laboris nulla incididunt laboris elit in cupidatat voluptate ad minim incididunt. Deserunt ullamco in aliquip nostrud dolor dolore nisi ex cillum deserunt consectetur reprehenderit.

Adipisicing voluptate commodo sunt esse velit eu. Eu labore nisi adipisicing magna non velit. Tempor excepteur cillum deserunt nisi sit labore. Sint nulla irure aute laborum cillum nostrud consectetur elit deserunt cillum duis officia. Eu ad duis qui mollit. Ex laboris ex reprehenderit eiusmod cillum aliqua adipisicing proident veniam ea laborum ut.
```

it came from @Tyriar's lorem extension.

**Comment by isidorn** [comment]
Great, thanks for improving this 👏

**Comment by TylerLeonhardt** [comment]
verification:
* get @Tyriar's lorem ipsum extension
* open an untitled file
* using the extension insert some text

Language detection should not guess any language. Maybe do this a few times for good measure.

**Comment by lramos15** [comment]
If you continue to call the insert paragraph command from the lorem ipsum extension you bounce between YAML, Markdown, and Plain Text. The jump to markdown is especially jarring as the line spacing changes

**Comment by TylerLeonhardt** [comment]
I think markdown makes sense... it _could_ be markdown. YAML is a bit unexpected. I think it would be worth pushing YAML down a bit.

**Comment by lramos15** [comment]
> I think markdown makes sense... it _could_ be markdown. YAML is a bit unexpected. I think it would be worth pushing YAML down a bit.

I would disagree that markdown makes sense just because there are no markdown tokens at all in the sample that I saw. It would be more expected if there was a lot of `#` or `**` etc but it's all just text. Albeit probably hard to train a model to look for only certain pieces when building the model

**Comment by TylerLeonhardt** [comment]
Yeah, I agree with you @lramos15. I was mostly answering that with the grain of salt that it _is_ hard to train a model to look for that without it being a totally separate model. In any case, there's some discussion about treating plaintext better in the guesslang model but I think as long as the language isn't totally weird like SQL and yeah I think YAML is totally out there for this, then I'd consider this "fixed" for the foreseeable future.

**Comment by TylerLeonhardt** [comment]
I've nerfed YAML. I won't touch markdown for now since it's currently not getting buffed or nerfed and I think the work with respect to that should be done with this issue on guesslang:
https://github.com/yoeo/guesslang/issues/45

**Comment by TylerLeonhardt** [comment]
I don't think I wanna nerf YAML any further so I'm thinking there's not much else I can do here for now.

**Comment by rzhao271** [comment]
After running the insert paragraph command multiple times in a row, I get SQL, because the word `in` shows up often.

**Comment by TylerLeonhardt** [comment]
There's not much else I can do here. I've already nerfed SQL, I can't do it any more with totally ignoring the result.
