### ISSUE TITLE
Renaming a file in git causes the "Timeline" window to not show earlier changes to the file

### ISSUE THREAD

**Issue by vmx-joey** [microsoft/vscode#129524]
Issue Type: <b>Bug</b>

Renaming a file in git makes the timeline windows the version control tab onn the left side to not show earlier history of the file

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (1.49GB free)|
|Process Argv|-psn_0_73746 --crash-reporter-id 50a4ec92-e7ac-4159-9d1d-8290e9915a19|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
arm|dan|1.5.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-diff|fab|1.4.2
vscode-highlight|fab|1.5.1
vscode-pull-request-github|Git|0.28.0
gc-excelviewer|Gra|3.0.42
grammaroutlinelang|hun|1.0.0
output-colorizer|IBM|0.1.2
bridlensis|idl|1.2.2
nsis|idl|3.42.0
nsis-plugins|idl|1.3.0
nsl-assembler|idl|1.2.1
restructuredtext|lex|155.0.0
code-groovy|mar|0.1.2
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.5
jupyter|ms-|2021.8.1054968649
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
hexeditor|ms-|1.8.1
color-highlight|nau|2.4.0
speech-time-estimator|Plu|0.9.0
live-preview|pro|0.0.3
java|red|0.80.0
jenkinsfile-support|sec|0.1.0
vscode-table-formatter|shu|1.2.1
code-spell-checker|str|1.10.2
vscode-make|tec|1.0.2
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.17.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.31.0
clang-format|xav|1.9.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by eamodio** [comment]
The Timeline view doesn't follow renames. Although if you use GitLens, the File History view can.
