### ISSUE TITLE
Command `Notebook: Select Between Notebook Layouts` doesn't do much apart from displaying welcome page

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#129588]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Insiders
- OS Version: Mac

Steps to Reproduce:

1. Select command `Notebook: Select Between Notebook Layouts` 
2. The welcome page appears, and I don't know what to do now to change the notebook layout.

**Comment by rebornix** [comment]
@roblourens did we change the getting started section?

**Comment by roblourens** [comment]
You have this setting enabled right? `notebook.experimental.openGettingStarted`

The getting started content when clause is using a different setting...

**Comment by JacksonKearl** [comment]
Still seeing this.

**Comment by roblourens** [comment]
It's a hidden setting
