### ISSUE TITLE
Open Disassembly View should be present but disabled

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129540]
Testing #129161

@xisui-MSFT  @yuehuang010

As @weinand already pointed out

The "Open Disassembly View" command is now only visible when the active stackframe has a instructionPointerReference property. This makes it hard to discover. I suggest to have the context menu's "Open Disassembly View" command always visible if a debug adapter has the supportsDisassembleRequest capability. But the command should only be enabled if the active stackframe has a instructionPointerReference property. That results in a more stable user experience.

Apart from that we should have the Open Disassembly View command in the command palette.

**Comment by xisui-MSFT** [comment]
That's a fair suggestion. However, we are not sure how to disable a command...

**Comment by isidorn** [comment]
@xisui-MSFT commands have `when` clauses and `precondition`. `when` clause determines if the command is present at all and `precondition` if it is disabled. So please use the `precondition` when registering the editor command for disablement.

**Comment by isidorn** [comment]
Also we should consider to introduce a call stack context menu action for the Open Disassembly View.

**Comment by xisui-MSFT** [comment]
@xisui-MSFT will fix this.
