### ISSUE TITLE
Electron 13 - Cropped Titlebar on Fullscreen

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#129568]
Testing #129455

Title bar gets cropped on full screen: 
[![Image from Gyazo](https://i.gyazo.com/1e0ae533095a521abff35974a9f4bbca.gif)](https://gyazo.com/1e0ae533095a521abff35974a9f4bbca)

**Comment by deepak1556** [comment]
Sorry for not being clear in the issue, it was to check if the titlebar was cropped on exiting fullscreen (previously regressed issue https://github.com/microsoft/vscode/issues/83456 that has related screenshots). The above behavior on entering fullscreen is expected.

Tip: When in doubt, always compare the behavior with stable.
