### ISSUE TITLE
Cells executed from interactive window take multiple clicks to uncollapse

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#129551]
Testing #129288

1. Open an interactive window
2. Run some commands from the python file
3. Type `pwd` into the interactive window
4. Click the run button
5. 🐛 Uncollapsing the newly created cell takes 4-5 clicks. This is different from the one click it takes for cells that are backed by the python file

**Comment by rebornix** [comment]
> Uncollapsing the newly created cell takes 4-5 clicks. This is different from the one click it takes for cells that are backed by the python file

@lramos15  Can you show a screen recording of this?

**Comment by lramos15** [comment]
@rebornix Has recorded a gif over teams since my software wasn't working.
