### ISSUE TITLE
focus jumps and makes it impossible to use context menu

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129587]
Testing #129288

![recording (41)](https://user-images.githubusercontent.com/29464607/127205067-c8e9412c-2640-4e8f-b605-5c41587cb4b5.gif)

**Comment by meganrogge** [comment]
looks like the active cell is stealing focus, which closes the context menu

**Comment by joyceerhl** [comment]
This repros even without the active text editor, e.g.

![recording (11)](https://user-images.githubusercontent.com/30305945/127384141-97e8cb2b-3098-4de0-ae4a-4a14a5b31241.gif)

**Comment by rebornix** [comment]
We had the same fix for cell toolbar https://github.com/microsoft/vscode/issues/103926 . I copied the code but we should have a fix in the toolbar itself.

**Comment by rebornix** [comment]
Follow up issue https://github.com/microsoft/vscode/issues/129724
