### ISSUE TITLE
Undo+Redo doesn't re-fold imports

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#129558]
Testing #129359

1. Make a new empty typescript file.
2. Paste a bunch of typescript code with multiple imports at once, ie:
```
import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import { URL } from 'url';

export class WSServerWithOriginCheck extends WebSocket {
	public externalHostName: string | undefined;
}
```
3. The code should fold, but using undo (removes all the code), then redo to restore the code. The imports no longer fold. This also happens if you manually delete all of the code, then re-paste it back in. 🐛

**Comment by aeschli** [comment]
Currently, folding imports only happens when an import appear in an editor for the first time.

**Comment by aeschli** [comment]
I'm not sure if we should start collapsing imports on paste and other operations. Closing the issue for now, but will reopen if the request comes up again.
