### ISSUE TITLE
Adding a new dependency to an installed extension pack does not yield "would you like to install dependencies" prompt

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12959]
Testing https://github.com/Microsoft/vscode/issues/12658

Repro steps:
1. adding a new extension to the dependencies of a published and installed extension pack
2. increment the version of the extension pack
3. update the extension pack from VSCode

Expected: prompt asking if I also want dependencies to be installed
Actual: no prompt, which seems inconsistent with the rest of the experience

**Comment by joaomoreno** [comment]
Maybe #12011

**Comment by sandy081** [comment]
Not related to #12011

I am not showing the prompt always. Prompt is shown only during installing. If user confirms, manual / auto update do not show prompt. IMO it makes sense coz, showing again is redundant to the user as he/she already knows it installs dependencies. 

Duplicates #12917

**Comment by mousetraps** [comment]
@sandy081 thx for the explanation. I agree that the feature would be a bit redundant in the current state of the world, but I think it might be good to revisit after #12756, which would provide more visibility into the packages being installed.
