### ISSUE TITLE
False the first time doesn't seem to be honored as a boolean

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129581]
Testing #129448

Using the example in ^ add an additional property that has an initial value of false. Notice the error that is shown even though it is a boolean value:
![image](https://user-images.githubusercontent.com/2644648/127202135-bd6b8345-ba8e-4377-b61a-a60128b580d4.png)

Looking at the JSON editor, looks like false is being treated as a string:
![image](https://user-images.githubusercontent.com/2644648/127202352-6d82c41b-50e7-451d-8949-7e2f50ba6105.png)

**Comment by rzhao271** [comment]
I'm unable to repro the issue.
When I click add item in the GUI editor, I can only select la or lb. That is probably a separate issue.
In the JSON editor, I can add an additional property with the default value of `false`, but that doesn't seem to cause it to be converted into a string when seeing it in the GUI editor.

**Comment by TylerLeonhardt** [comment]
@rzhao271 here's more specifics of the repo:

my package.json:
```json
{
	"contributes": {
		"configuration": {
			"type": "object",
			"title": "oh you know",
			"properties": {
				"asdf.hmm": {
					"type": "object",
					"patternProperties": {
						"^oi#": {
							"type": "string",
							"description": "here here",
							"enum": ["aaaaaaaaaaaa", "bbbbbbbb"]
						}
					},
					"properties": {
						"la": {
							"type": "string",
							"enum": ["a", "b", "c"]
						},
						"lb": {
							"type": "string",
							"enum": ["b", "c", "d"]
						}
					},
					"additionalProperties": {
						"type": "boolean"
					},
					"default": {}
				}
			}
		}
	},
}
```
Add an item:
![image](https://user-images.githubusercontent.com/2644648/127225742-c7776f2c-efe9-4e48-9fa3-2608de4bbf56.png)

choose false and then Ok:
![image](https://user-images.githubusercontent.com/2644648/127225790-6665379f-96cd-4489-85e9-7c66a2118f43.png)

**Comment by rzhao271** [comment]
1. Create the following setting in an extension
```json
"asdf.hmm": {
	"type": "object",
	"additionalProperties": {
		"type": "boolean"
	},
	"default": {}
}
```

2. Debug the extension
3. Set the setting as follows in the settings json file
```json
"asdf.hmm": {
    "la": "a",
    "aaaa": "true"
}
```
You should see some validation errors. Ignore them for now.
4. Search for the setting in the settings editor. You should see some validation errors.
5. Double click a row to put it into edit mode. A dropdown should show up with true/false values. Set it to any one of the values and press OK. Repeat this process for both rows
6. The settings json file and the settings editor should both not show any errors.
