### ISSUE TITLE
Settings UI requires double click to set setting

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129562]
Issue Type: <b>Bug</b>

Open settings UI
Type in a search expression (I used 'inlay')
Try changing the value of a boolean setting.

Expected:
Click once in a checkbox makes the setting change

Actual:
Have to click twice. 
Once to give focus
Once to check the box.

VS Code version: Code - Insiders 1.59.0-insider (955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7, 2021-07-26T05:13:58.801Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (20.12GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
python|ms-|2021.8.1060463485-dev
vscode-pylance|ms-|2021.7.6-pre.1
jupyter|ms-|2021.8.1070546638
js-debug-nightly|ms-|2021.7.2617
live-server|ms-|0.2.5
vscode-typescript-next|ms-|4.4.20210726
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by roblourens** [comment]
Works fine for me. Maybe you can record a gif?

**Comment by rchiodo** [comment]
![doubleclick](https://user-images.githubusercontent.com/19672699/127242778-edd33648-9440-4f0d-b7da-f7f31b28e17e.gif)

Happens on the second item, first one seems to work.

**Comment by roblourens** [comment]
Oh yes, this is an annoying old bug https://github.com/microsoft/vscode/issues/106577
