### ISSUE TITLE
Uninstalling an extension w/ dependencies should also offer to uninstall those dependencies

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12957]
Testing https://github.com/Microsoft/vscode/issues/12658

Ideally # of installs is directly proportional to # of uninstalls. Right now, if an extension pack installs several dependencies, you have to go through, find, and uninstall every single one. It's like maple syrup. You get just a little bit on your hand and then somehow it defies the laws of physics, multiplies, and it's everywhere!

Extensions shouldn't be like maple syrup. 😜

**Comment by joaomoreno** [comment]
Not entirely convinced about this. What if A depends on B and you install first B and then A? Should you uninstall B when uninstalling A still?

**Comment by sandy081** [comment]
I am also not favor of uninstalling as a pack. Instead what is more useful is either not allowing or prompting the user while uninstalling an extension if it is a dependency of already installed extension.

**Comment by sandy081** [comment]
Assigning to october for discussion and conclusion

**Comment by joshsleeper** [comment]
Maybe a better idea would be to offer a way to _optionally_ remove those dependency packages?
The way I see it, packages should never be removed without our permission, but it's also nice to be able to easily remove dependency packages without having to individually remove them by hand.

I'm thinking something functionally like how `apt` handles things with `apt-get autoremove`

![image](https://cloud.githubusercontent.com/assets/849941/19444847/025421b0-9447-11e6-9d2a-f81be7336928.png)

**Comment by sandy081** [comment]
Uninstalling a pack provides a prompt to uninstall only itself or its dependencies also. So user choose.

**Comment by sandy081** [comment]
Re-opening this issue to consider [comment](https://github.com/Microsoft/vscode/issues/12957#issuecomment-250454397)

**Comment by joshsleeper** [comment]
@sandy081 Does it check to ensure that each dependency of the package being uninstalled isn't a dependency of any other currently installed packages first?

@joaomoreno Does the implementation seem reasonable to you?

**Comment by sandy081** [comment]
@joshsleeper You have a valid point, In fact I too mentioned the same here [comment](https://github.com/Microsoft/vscode/issues/12957#issuecomment-250454397) . That's why I have reopened issue earlier. Thanks for mentioning.
