### ISSUE TITLE
Installing an extension pack should also list other dependencies it intends to install

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12955]
Testing https://github.com/Microsoft/vscode/issues/12658

Right now a popup appears asking if I want to install dependencies of the extension pack, which of course begs the question... "what are the dependencies?" More visibility into this would be helpful. 
![image](https://cloud.githubusercontent.com/assets/762848/18936227/8ecba7e6-859a-11e6-92eb-52e97fd08a28.png)

**Comment by sandy081** [comment]
You are right. This is part of the complete feature and will be implemented in Ocotber

Duplicates #12756
