### ISSUE TITLE
"Run File" should be before "Debug File"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129518]
Testing #129384

`Run File` should be before `Debug File`.
I am not sure if this is controlled by core, but `Run File` should be first because:
* I believe that most users actually use the Run more in the title bar. We can dig out some numbers
* We call the view "Run and Debug" since Run is "lighter", so it should also go first here
* The hover title of the chevron is "Run or Debug"

![Screenshot 2021-07-27 at 14 31 17](https://user-images.githubusercontent.com/1926584/127154141-8972fe84-7501-4014-be67-b68e53521495.png)

**Comment by isidorn** [comment]
Now I saw that this comes from Mock Debug. Though I still think we should fix mock debug so it is a good example for other debug extensions.

**Comment by weinand** [comment]
I've created https://github.com/microsoft/vscode-mock-debug/issues/58 for this.
