### ISSUE TITLE
Two-step scrolling in interactive window

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129580]
Testing #129288

I have the following file, and ran all the cells:

```py
#%%
print(1)

#%%
print(2)

#%%
print(3)

#%%
print(4)

#%%
print(5)

#%%
print(6)
#%%
print(7)
#%%
print(8)
#%%
print(9)

# %%
```

Then, I scrolled to the top of the interactive window.
After, I pressed the `Go to` button for the `print(8)` cell in the Python file.
The interactive window scrolled to show the `print(8)` cell, but then it scrolled again, around one second later.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue locally though. @joyceerhl are you able to reproduce?

**Comment by joyceerhl** [comment]
I'm not able to repro either. It scrolls just once for me. @rzhao271 is this reliable or flaky? Any chance you can do a screen recording? 🙏

**Comment by rzhao271** [comment]
It's reliable

![Screencap](https://user-images.githubusercontent.com/7199958/127580085-33867dba-043e-45a3-8741-9fd56e99c41f.gif)

**Comment by rzhao271** [comment]
@rebornix I posted a screencap above. Not sure if more info is needed here.

**Comment by rebornix** [comment]
@rzhao271 thanks, I think I know what's going on, thanks for the details.
