### ISSUE TITLE
Extension not appearing in @outdated list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12958]
Testing #12658 (Windows)

After publishing [test-extension-pack-1](https://github.com/Microsoft/vscode-extension-samples/tree/master/extension-deps-sample), I updated it to add another dependency to it, and also incremented the version. After it was published, the extensions pane never updated to inform me of an updated version, and queries for `@outdated` were similarly unsuccessful. Restarting VSCode and waiting did nothing either.

Eventually, I searched the marketplace for that extension, and it popped up into the list, with the appropriate Update / Uninstall buttons, which in turn prompted the outdated list to be updated (extension appears in `@outdated` query)

**Comment by joaomoreno** [comment]
#12011
