### ISSUE TITLE
Editing a parameter for a function doesn't apply subsequent edits where the cursor is

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129563]
Testing #129465

Started with this:
![image](https://user-images.githubusercontent.com/19672699/127191532-963dc074-5216-4d32-952c-2431baec89aa.png)

Added the letter 'f' to the end of the name:

![image](https://user-images.githubusercontent.com/19672699/127191590-6a80852e-ec4c-45f0-a913-b76f7693cec1.png)

Cursor moves to front of parameter. 

However typing puts new chars at the end (well where it was before)
![image](https://user-images.githubusercontent.com/19672699/127191657-9c83bffe-0f97-40bd-a381-edfa479c19df.png)

But moving the cursor moves it from where it looks like it was.

**Comment by hediet** [comment]
This was already fixed yesterday, unfortunately the insiders build was not shipped.

Can you please update & try again to verify that it is fixed in todays insiders build?

Thanks!

**Comment by rchiodo** [comment]
Yep works in today's build. Thanks.
