### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by gopalampriyanka** [microsoft/vscode#129508]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Issue Type: <b>Bug</b>

Terminal is opening but not able to type anything

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.44GB free)|
|Process Argv|--crash-reporter-id 34bbaa98-e329-4f23-8538-a43564619eb7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
tslint|eg2|1.0.47
prettier-vscode|esb|8.1.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.7
salesforcedx-vscode|sal|52.6.0
salesforcedx-vscode-apex|sal|52.6.0
salesforcedx-vscode-apex-debugger|sal|52.6.0
salesforcedx-vscode-apex-replay-debugger|sal|52.6.0
salesforcedx-vscode-core|sal|52.6.0
salesforcedx-vscode-lightning|sal|52.6.0
salesforcedx-vscode-lwc|sal|52.6.0
salesforcedx-vscode-soql|sal|52.6.0
salesforcedx-vscode-visualforce|sal|52.6.0
sonarlint-vscode|Son|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by meganrogge** [comment]
open an issue with more detail and context when you next see it's not working
