### ISSUE TITLE
Disassembly view: after session ends if new session is started the disassembly view is left empty

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129526]
https://github.com/microsoft/vscode/issues/129161

fyi @yuehuang010, @xisui-MSFT)

1. Start debugging, open disassembly view
2. Stop debugging. Disassembly view is still open and shows content
3. Start debugging again. Disassembly view is empty and left lingering around

We should automatically close the disassembly view when we detect it is smart to do that.
Either when the session ends (depends if you think that users still want to inspect the disassembly). Or when the new session starts.
Or at least when the new session starts it should be reused and filled with content.

![Screenshot 2021-07-27 at 14 51 42](https://user-images.githubusercontent.com/1926584/127156946-d7e89057-d75e-4a18-bf04-11be2790e3fc.png)

**Comment by isidorn** [comment]
Also when we clear the disassembly view we should get rid of the instruction breakpoints.
Though I see that we do not store them across VS Code reloads, which I think makes sense.

**Comment by xisui-MSFT** [comment]
@xisui-MSFT Will fix this. A special entry like "Program needs to hit a breakpoint in order to get the disassembly" will be added.

As for clearing instruction breakpoints, we need to sync with the debugger team about the correct behavior.

**Comment by isidorn** [comment]
@xisui-MSFT ok. We just need to figure out to not have too much waste left lying around that the user has to manually manage...
