### ISSUE TITLE
terminal.integrated.confirmOnKill does not work in panel

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#129583]
Testing #129428

1. Set `confirmOnKill` to `always` or `panel`
2. Create a new terminal in the panel and `sleep 60`
3. Click the 🗑️  icon
4. No confirmation prompt is shown

**Comment by meganrogge** [comment]
this is not happening because `terminal.hasChildProcesses` is false

**Comment by meganrogge** [comment]
adding this fixes it, but might be as designed already since there are no child processes associated with `sleep`

https://github.com/microsoft/vscode/blob/ffd3894c408359d75ae121cb090f0e663e9621db/src/vs/platform/terminal/node/childProcessMonitor.ts#L106-L109

```
if (!processItem.children) {
			return processItem.load === 0;
		}
```

**Comment by Tyriar** [comment]
Yes this was by design, but maybe we should be considering `load` as an option. I'm a bit concerned about relying on this causing flakiness as it would mean it's dirty if the shell start using cpu even though nothing is run.
