### ISSUE TITLE
Play button doesn't show when using Code Runner extension

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#129599]
Testing #129384

(this might be a Code Runner issue, I can open it there if that's the case)

When using the code runner extension and Python, the play button icon does not show up:

 
![image](https://user-images.githubusercontent.com/45497113/127211193-4f03a53a-7873-41f5-b20b-df016cd3a9ce.png)

Clicking on the area does nothing, so I don't think it's a rendering problem?

Clicking on the drop down we see the following options:

![image](https://user-images.githubusercontent.com/45497113/127211250-fba949af-869c-4266-b47a-5b7172f9d9ba.png)

The same thing happens with Java + Code Runner:

![image](https://user-images.githubusercontent.com/45497113/127211447-3a9b5612-a2b0-47c3-b856-49f0c41533fa.png)

And then disabling code runner we have the icon as expected:

![image](https://user-images.githubusercontent.com/45497113/127211494-860d4de5-4576-4a05-8dd4-8e75b13df5c8.png)

**Comment by isidorn** [comment]
Probably not for last day of endgame, moving out to August

**Comment by weinand** [comment]
There is a workaround in place for this.

**Comment by weinand** [comment]
The Code Runner does not use theme icons but old style SVGs which were not properly covered by some CSS rule.
