### ISSUE TITLE
Use larger initial view size, the scrollbar is too jumpy

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129534]
Testing #129161

@yuehuang010, @xisui-MSFT 

1. Open disassembly view
2. Start scrolling, look at the scroll bar and notice the aggressive jumping
3. I suggest to use a much bigger initial view size so the scrolling will be much smoother. Current experience is very rough.

**Comment by xisui-MSFT** [comment]
@xisui-MSFT will fix this.
