### ISSUE TITLE
Inlay hints: The larger the font size descrepancy, the better it would look vertically middle aligned

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129522]
Testing #129381

Using

```
"editor.inlayHints.fontSize": 8,
"editor.fontSize": 12,
```

The bottom alignment makes this look pretty bad:

![image](https://user-images.githubusercontent.com/2193314/127156004-91a1d335-9bd8-4233-91cb-e612050743fc.png)

If it were middle aligned:

![image](https://user-images.githubusercontent.com/2193314/127155963-4be0e1fb-2d8a-44b8-a130-b8e2681b43f6.png)

**Comment by hediet** [comment]
This is how it looks now:
![image](https://user-images.githubusercontent.com/2931520/129039711-8f93e28a-f2b7-4f8c-91c7-3a0ed599fdb6.png)
