### ISSUE TITLE
Inlay hints: Allow ctrl/cmd+click to go to a type's definition

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129528]
Testing #129381

I tried ctrl+clicking `TerminalIcon` here intuitively:

![image](https://user-images.githubusercontent.com/2193314/127157643-0021de0f-3a4e-4692-b3fb-b230d8845b58.png)

Going to an argument definition would also be handy/expected

**Comment by Tyriar** [comment]
In a similar vein, the hover for the inlays should show for the type they're hovering imo

**Comment by hediet** [comment]
I don't know what the plans are for inlay hints, but I think this is doable with injected text.
However, the injected text feature needs to be extended to support hovers & decorations that just apply to a specific part of the injected text.

**Comment by mjbvz** [comment]
@jrieken Adding you since I believe VS Code's inlay hints api would need to be modified to support this

**Comment by jrieken** [comment]
Yeah, we want that

**Comment by jrieken** [comment]
Stretch for September

**Comment by jrieken** [comment]
Just sample/dummy data but the interaction is real!

https://user-images.githubusercontent.com/1794099/148101798-e972b1fb-177b-4d39-8418-45f9b6854786.mov

**Comment by mjbvz** [comment]
@weswigham @RyanCavanaugh @DanielRosenwasser We want to make sure that TypeScript would be able to support this API 

With the current proposal, TypeScript would need to generate the links for the inlay hint when it returning them. Do you believe this will be feasible TypeScript, or would the performance costs would be too high? We only request the hints for the current viewport but each hint could potentially contain multiple clickable symbols

**Comment by weswigham** [comment]
Hm, when I did the same for my interactive diagnostics experience I returned a handle for the symbol (or generated a link that referenced the handle) that could then be used for further requests. Would a deferred access pattern like that be more suitable?

**Comment by jrieken** [comment]
Yeah, there is two options. The link-approach or a more explicit way: 

1. The inlay hint text uses markdown links, like `[Map](file:///path/lib.d.ts#L88776)<T>` or `command`-links. The latter will allow for said indirections. This will work but is a little unspecific and asks for escaping issues...
2. The inlay hint object will "known" about links, so `InlayHint#text` can be `string` or `StringWithLinks` (similar to tsserver's display parts) and the provider will have the ability to resolve a hint which means it must fill in link targets. The [document link provider](https://github.com/microsoft/vscode/blob/42a43ebbd9a15cdf17a7ad577750981829a46490/src/vscode-dts/vscode.d.ts#L4393) uses a similar pattern. So, at provide-time we need to know that something (one or more parts of an inlay) will be a link and at resolve-time those links need to be enriched with targets.

**Comment by mjbvz** [comment]
@weswigham Would there be cases where we think something would be a link but then can't resolve it? 

@jrieken Have we considered deferring computing the links until the user hovers over the inlay hint, similar to how cmd+hover works with normal code?

**Comment by weswigham** [comment]
I'm just thinking you want a symbol reference that you could use for arbitrary LS operations so you can then use it to provide a hover, find all refs, go to definition, and other symbol operations (rename?). So maybe a link to a declaration location works, but the plugin parses the link to use the location to provide the context menu items. (Which makes it sound a bit more specific than a normal arbitrary location link.) 

However, as you guess, there are definitely some things that could appear in inlay hints that don't have traditional authoritative declaration locations you could use as a "source location" for the LS operation - for example string literals support the rename operation (we find and replace all the matching literals), so in theory one could want to rename such a literal, or just do a find a refs, but I don't think they usually have a definition site. A non-location ref (short-lived, likely only until the next inlay hints request) from the LS could work here, but would need new LS operations for resolving the results of various LS operations at those refs.

So I see links as a pretty quick and dirty way to get like 80% of the way there, but the last 20% would need the different, more structured solution, I think.

**Comment by DanielRosenwasser** [comment]
Also - I also am generally a fan of providing a general-purpose output format instead of markdown. Having every language wrangle edge-cases of markdown when not every editor may understand markdown natively doesn't seem like an optimal way to layer things. A response format where editors could choose however rich/bare to display these would probably be much more flexible and usable long-term for VS Code.

**Comment by jrieken** [comment]
> Also - I am generally a fan of providing a general-purpose output format instead of markdown. Having every language consider edge-cases of markdown when not every editor may understand markdown natively doesn't seem like an optimal way to layer things.

@DanielRosenwasser Yes, esp for LSP that makes a lot of sense. Tho, for VS Code and markdown (and since recently the equivalent subset of html) make sense to me. We have some utils in `MarkdownString` to help construct them but those can be improved. A general-purpose output format can only differ in ergonomics but not in functionality. This is because all of the API (esp. of providers) is just structured output for specific rendering purposes. The markdown/html vs more structure discussion is usually driven by our decisions how to render/constrain things, e.g for inlay hints we can define more API for such links/commands or leave it a little more open by allowing (some) markdown/html. I believe in this case things will be functionally equivalent because a command-link is the most powerful thing we have. It's about developer ergonomics and clarity. 

> @jrieken Have we considered deferring computing the links until the user hovers over the inlay hint, similar to how cmd+hover works with normal code?

@mjbvz I was concerned about discoverability but it's definitely an option. I believe the question if this is more like the cmd+hover gesture or more like code lens or plain links? Anyone having strong feelings about the (inactive) underline that always shows?

**Comment by jrieken** [comment]
Had a good chat with @dbaeumer and we came up with the following API/idea

```ts
	export class InlayHintLabelPart {
		value: string;
		action?: Command | Location; // used with provider
	}

	export class InlayHint {

		label: string | InlayHintLabelPart[];
		
		// rest...
	}

	export interface InlayHintsProvider<T extends InlayHint = InlayHint> {

		resolveInlayHint?(hint: T, part: InlayHintLabelPart, token: CancellationToken): ProviderResult<T>

		// rest...
	}
```

The label of an inlay hint can be a normal string or an array of label parts. The label part is a string and an "action" which can either be a command or a location. The action can be filled-in lazy via the `resolveInlayHint`-call. The editor would call resolve on hover for instance. The "action"-property (better name tbd) can be

* command which we will simply invoke on click. This is very similar to code lens and others
* location is a source location which we will use with applicable providers, e.g source might be "uri: some/path/lib.d.ts, range: L23,11" and we would invoke the references provider with that location but at the position of the inlay hint. This effectively allows to show a context menu very similar to the one we show over "real" positions.

**Comment by Tyriar** [comment]
@jrieken not familiar with this API area but is this forward thinking for the idea of "overlay" hints as well? https://github.com/microsoft/vscode/issues/128162

**Comment by jrieken** [comment]
@Tyriar overlay hints is something that we have in mind but it's not to related to this issue. I suggest we leave that with its issue

**Comment by jrieken** [comment]
Did a prototype implementation of the ideas mentioned above (https://github.com/microsoft/vscode/issues/129528#issuecomment-1007487324). We are seeing a fake inlay hints provider but as label part "action" it returns locations into `lib.d.ts`. With that the hover logic figures that there is hover provider for TypeScript files and invokes it for the corresponding location. All is lazy, eg the label part is resolved lazy and the hover as well. What needs to be know upfront is the label part (w/o action).

https://user-images.githubusercontent.com/1794099/148598073-9e5b3fc8-1013-4e98-83fe-b810f74c7c7c.mov

**Comment by weswigham** [comment]
What about inlay hints that don't have a defined symbol location, like `"foo"` or calculated anonymous types? The LS knows how to provide hovers/refs/etc for something that, it just needs a way to refer to it that doesn't rely on a declaration location.

**Comment by jrieken** [comment]
> What about inlay hints that don't have a defined symbol location, like "foo" or calculated anonymous types? 

It's not strictly limited to the defining location of the symbol but about any location that when hovered/clicked would yield the desired result. Tho, I do admit that this is usually the definition. Also, you can always use the `Command` which allows to do anything but with much less comfort.

**Comment by orta** [comment]
:wave: I think this change isn't backwards compatible (at Monaco level):

```diff
-	provideInlayHints(model: model.ITextModel, range: Range, token: CancellationToken): ProviderResult<InlayHint[]>;
+ 	provideInlayHints(model: model.ITextModel, range: Range, token: CancellationToken): ProviderResult<InlayHintList>;
```

Because you used to return an array of hints, and now you need to return the object with hints (and it crashes if you pass the array ) https://github.com/microsoft/TypeScript-Website/issues/2247

**Comment by jrieken** [comment]
Inlay hints are still proposed API which means breaking changes are happening. Also, there is no stability guarantee wrt API for monaco

**Comment by SomeoneToIgnore** [comment]
@jrieken 
Sorry for asking in not the most appropriate place, please point me to the right issue, if any is present.

I'm reusing the proposed API in rust-analyzer and came up with a small test change: https://github.com/rust-analyzer/rust-analyzer/compare/master...SomeoneToIgnore:kb/vscode-inlay-hints?expand=1

Similar changes worked and displayed the hints on early proposal's stages, but not now:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/2690773/153200618-59f0bb24-68f8-4390-8bfe-fd704fbfbcd6.png">

with the `let i = 22;` line receiving the first item from the json array on the right.


I see no errors or warnings in any logs available, ensured that all experimental APIs are enabled and the extension installs and starts normally, so interested, what else have I missed?

**Comment by jrieken** [comment]
Hard to distance-diagnose... Is the feature enabled? Check the `"editor.inlayHints.enabled": true`-setting?

Also, do "F1 > Log Level > Trace" and check the extension host log via "F1 > Show Logs > Extension Host". It should show message "_similar_" to these `[2022-02-09 13:39:16.135] [exthost] [trace] [vscode.typescript-language-features] INVOKE provider 'j=>j.provideInlayHints(f.URI.revive(U),N,W)'`

**Comment by SomeoneToIgnore** [comment]
The former is on, but the latter does not happen (no trace entries in the logs).
I will check that more, but if you happen to have any API usage example at hand (the one from the video, maybe?), that would help me drastically.

Thanks nonetheless.

**Comment by jrieken** [comment]
Can you check the trace log of the window for messages like `[2022-02-09 13:58:11.398] [renderer1] [trace] [DEBOUNCE: InlayHint] for file:///Users/jrieken/Code/vscode/src/vs/editor/common/services/editorSimpleWorker.ts is 40.166666666666664ms`? That is a good indication if the feature has a provider it wants to work with...


The sample snippet from the video above is this. Notice how it is registered for the `fooLang` (which is my test/fiddle language). Changing that to `rust` or `typescript` should enable this

```ts
vscode.languages.registerInlayHintsProvider('fooLang', new class implements vscode.InlayHintsProvider {
        // onDidChangeInlayHints?: vscode.Event<void> | undefined;
        provideInlayHints(doc: vscode.TextDocument, range: vscode.Range, _token: vscode.CancellationToken) {
            const result: vscode.InlayHint[] = [];
            const text = doc.getText();

            {
                let end = doc.offsetAt(range.end);
                let pos = doc.offsetAt(range.start);
                while (pos < end) {
                    const idx = text.indexOf('bar', pos)
                    if (idx < 0) {
                        break;
                    }
                    pos = idx + 4;
                    const start = doc.positionAt(idx);
                    result.push(new vscode.InlayHint(start, [{ value: 'foo' }]))
                    // result.push(new vscode.InlayHint('FooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFooFoo', start))
                }
            }
            {
                let end = doc.offsetAt(range.end);
                let pos = doc.offsetAt(range.start);
                while (pos < end) {
                    const idx = text.indexOf('foo', pos)
                    if (idx < 0) {
                        break;
                    }
                    pos = idx + 4;
                    const start = doc.positionAt(idx + 3);
                    const label: vscode.InlayHintLabelPart[] = [
                        { value: ': ' },
                        { value: 'Map' },
                        { value: '<number, ' },
                        { value: 'typeof document' },
                        { value: '' },
                        { value: '>' },
                    ]
                    const hint = new vscode.InlayHint(start, label);
                    hint.paddingLeft = true;
                    hint.command = { command: 'extension.helloWorld', title: 'sss' }
                    result.push(hint)
                }
            }
            return result;
        }

        async resolveInlayHint(hint: vscode.InlayHint): Promise<vscode.InlayHint> {
            await new Promise(resolve => setTimeout(resolve, Math.random() * 1234))
            hint.tooltip = new vscode.MarkdownString('I am **Resolved** $(zap)', true);

            if (typeof hint.label !== 'string') {
                for (let part of hint.label) {
                    if (part.value === 'Map') {
                        part.location = new vscode.Location(
                            vscode.Uri.file('/Users/jrieken/Code/vscode/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts'),
                            new vscode.Position(20, 10)
                        )
                        part.tooltip = new vscode.MarkdownString('`lib.es2015.collection.ts`', true)
                        part.command = { command: 'helloWorld', title: 'Hello World', tooltip: 'dddd' }

                    } else if (part.value === 'typeof document') {
                        part.location = new vscode.Location(
                            vscode.Uri.file('/Users/jrieken/Code/vscode/extensions/node_modules/typescript/lib/lib.dom.d.ts'),
                            new vscode.Position(17160, 13)
                        )
                        part.tooltip = new vscode.MarkdownString('`lib.dom.ts`', true)
                    } else if (part.value === 'foo') {
                        part.command = {
                            command: 'helloWorld',
                            title: 'Hello World',
                            tooltip: 'dddd'
                        }
                        part.tooltip = new vscode.MarkdownString('I am a _label_ *part* $(check)', true)
                        part.location = new vscode.Location(
                            vscode.Uri.file('/Users/jrieken/Code/vscode/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts'),
                            new vscode.Position(20, 10)
                        )
                    }
                }
            }

            // console.log('DONE', hint.label)
            return hint;
        }
    })
```

**Comment by lnicola** [comment]
For me it does:

```
TRACE [DEBOUNCE: InlayHint] for file:///home/grayshade/Projects/rust-analyzer/crates/rust-analyzer/src/to_proto.rs is 141.16666666666666ms

[2022-02-09 20:24:22.000] [exthost] [trace] [matklad.rust-analyzer] INVOKE provider 'Q=>Q.provideInlayHints(h.URI.revive(W),O,$)'
[2022-02-09 20:24:22.084] [exthost] [trace] [InlayHints] 0 inlay hints from 'matklad.rust-analyzer' for [object Object]
[2022-02-09 20:24:22.084] [exthost] [trace] [matklad.rust-analyzer] provider DONE after 84ms
```

although the extension is returning a good amount of hints.

**Comment by lnicola** [comment]
Strange, so our range is `(323, 0) - (552, 0)`, the hint position is `(471, 0)`, but the range doesn't contain that position?

![image](https://user-images.githubusercontent.com/308347/153268827-6ea8f90d-3b53-4d80-a126-7edc117f0f9f.png)

**Comment by jrieken** [comment]
Oh... That is very interesting and very good drilling 👏 It is likely that position isn't an instance of `vscode.Position` but just a lookalike. TypeScript doesn't enforce instanceof-compatibility, e.g its structured typing ignore prototypes or ctor-functions and therefore we don't successfully exercise `contains`. Today, you can workaround this by using `new vscode.Position(...)` but I will also push a fix to relax this

**Comment by Tyriar** [comment]
This isn't working as I was expecting it to, ctrl+click goes to the symbol the type is annotating, not the type itself.

![Recording 2022-08-09 at 06 03 41](https://user-images.githubusercontent.com/2193314/183653854-42da1c00-2dff-4341-baea-15c013e1a426.gif)

Cursor feedback is also not great

**Comment by mjbvz** [comment]
@Tyriar I think that's the default behavior (if you look closely, I believe it actually underlines the var in this case)

We haven't actually hooked this up for JS/TS yet but I'll open a TS issue for this

**Comment by Tyriar** [comment]
@mjbvz makes sense, thanks
