### ISSUE TITLE
Do not render "Auto" when in Plain Text mode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129591]
Testing #129436

Plain text mode is the default. We should not render "Auto" in this case to not confuse the user, and there is nothing automatic about this, since it is the default :)

![Screenshot 2021-07-27 at 20 14 42](https://user-images.githubusercontent.com/1926584/127206422-3ea3cd31-5add-4abd-83c9-d791af3e2cb9.png)

**Comment by isidorn** [comment]
I am actually not a big fan of the `(Auto)` part in general. Not sure what is the biggest benefit of rendering it.
Maybe we should just mention this once the user clicks and the quick pick is opened...

**Comment by isidorn** [comment]
I take back my second comment. Rendering it makes sense, but not for Plain Text.

**Comment by TylerLeonhardt** [comment]
The `(Auto)` is used as an indicator to say "hey the language you're currently using could switch at any time" so with that definition it still applies to Plain Text. This aligns nicely with how the setting works (allowing you to language identify which languages you want to switch away from and which you don't)

That said, maybe the indication isn't needed at all. The only way (besides the setting) to not have language detection switch is to manually choose a language in the language picker. The instances where the user would need to do that with language detection on is:

* if the language detection isn't confident enough (my guess is this is 99% of the time)
* if the language detection is wrong and it chose the wrong language

**Comment by TylerLeonhardt** [comment]
I've removed `(Auto)` all-together.
