### ISSUE TITLE
Support number and integer object values and arrays in Settings editor

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129592]
Testing #129448

> where all values are type string or boolean (otherwise the setting won't render in the settings editor)

If I do:
```jsonc
                                     "additionalProperties": {
						"type": "number" // or integer or null
					},
```

Then I get:

![image](https://user-images.githubusercontent.com/2644648/127206664-61bf4013-7838-4564-bf48-38aaad1f72ac.png)

**Comment by rzhao271** [comment]
This issue is more of a debt one. Currently, the validation occurs after the object has been saved, whereas it should come before that. Additionally, only after the validation should the object values be parsed to the correct types.
