### ISSUE TITLE
ipynb file opened as text editor on vscode.dev

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129573]
Testing #129463

When opening a local ipynb file on vscode.dev, it opens as text editor but I can reopen it with notebook editor.

**Comment by joyceerhl** [comment]
The ipynb extension isn't showing up at all in vscode.dev. @rebornix only has the option to reopen with notebook editor because he had my vscode-jupyter-notebook-serializer test extension installed.

**Comment by roblourens** [comment]
Fixed in #129502
