### ISSUE TITLE
No `ipynb` file support for serverless web

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#129502]
Testing #129463 on "web":

I did not see any `ipynb` file support out of the box 

Steps:
- open `https://github.com/odewahn/ipynb-examples` in MS Edge on macOS
- from the github's "Code" menu I selected the "Cloud" tab and pressed the "Open with Web Editor" button
- in the file explorer select `Cell Magics.ipynb`
- Observe:
   <img width="1443" alt="2021-07-27_11-20-24" src="https://user-images.githubusercontent.com/1898161/127129804-01e9b9e0-8f63-40e8-a6b5-b88dfc9b8795.png">

There was no notification about `*.ipynb` file.

Most likely this is the expected behavior because "Open with Web Editor" is the serverless "web" which does not support the new feature. However it would be great if "serverless" could redirect `ipynb` users to Codespaces (as we do for debugging).

**Comment by rzhao271** [comment]
Getting there. All notebooks I click on render as a blank notebook.

![Example](https://user-images.githubusercontent.com/7199958/127398358-03100090-f645-406f-a0cc-d7dc36c54fb1.PNG)

**Comment by roblourens** [comment]
What repo is that? Works for me in some notebooks in vscode-jupyter

**Comment by rzhao271** [comment]
Same steps as https://github.com/microsoft/vscode/issues/129502#issue-953683539
I'm on MS Edge on Windows

**Comment by joyceerhl** [comment]
Oh it's nbformat3

**Comment by joyceerhl** [comment]
@rzhao271 What about https://github.com/jakevdp/PythonDataScienceHandbook? We have never supported anything older than nbformat so this is probably a feature request.

**Comment by weinand** [comment]
Yes, but please clearly show that nbformat3 are not supported.

**Comment by rzhao271** [comment]
nbformat4 is fine

**Comment by roblourens** [comment]
Filed https://github.com/microsoft/vscode/issues/129732

**Comment by rzhao271** [comment]
Removing this issue from this milestone, considering it's being tracked in the new feature request filed above.
