### ISSUE TITLE
Git - Clicking "Stage Changes" after resolving a merge conflict with "Accept All Current" results in no empty commit merge being staged

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#129598]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2 or today's Insiders
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create a git branch with a change, e.g. version change in package.json.
2. Create another git branch with a conflicting change, e.g. a different version.
3. From the Source Control view, use the Merge Branch... option to merge one branch into the other.
4. When the conflict occurs, right-click on the conflicting file and choose "Accept All Current".
5. Save the changed file.
6. Click the "Stage Changes" button:
![image](https://user-images.githubusercontent.com/19859882/127209511-28a2c6a4-4f1b-4591-805a-3160d7aa906c.png)

Bug: No changes are staged and there is no other UI indication of how to conclude the merge (the fix would be to add some UI indication). Use the steps below to try to workaround the issue:

7. Create some new files that are unstaged and not added to git. (in a normal scenario, these files would already exist, and they're just created in this step in order to repro the issue).
8. Use the Commit command in the UI.

Bug 2: A popup appears that doesn't give any option to commit the empty change and instead it asks about staging the new files. Either the 1st bug could be fixed or it should give another option to Create Empty Commit.

![image](https://user-images.githubusercontent.com/19859882/127210213-eaa4b7ab-06f0-4157-b5e0-bd4a76687adc.png)

The workaround is to delete all the unstaged files, which and then use the Commit command, which brings up a "Create Empty Commit" popup, which causes the merge to be completed.

**Comment by 10bo** [comment]
I have also experienced this issue more than once. Searching the project's issues has lead me to find this one.

**Comment by scytacki** [comment]
This could be connected with this request: https://github.com/microsoft/vscode/issues/150353

The commit button could be replaced with "complete merge" and "abort" buttons when there is a `.git/MERGE_HEAD`. This way the commit button logic of "committing something with no changes is not allowed", could be bypassed.

**Comment by hawking71** [comment]
The workflow is broken by this bug, which makes me very confused, like falling in a trap suddenly. Hope a fix as soon as possible.
