### ISSUE TITLE
Cannot Double Click To Insert Emoji Using OSX Emoji Panel 😞

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#12950]
VSCode 1.6 Insiders
OSX 10.11
##### Steps to Reproduce
1. Open blank text document with UTF-8 encoding.
2. Open the emoji panel 
3. Double click on one to insert it into current document
##### Expected

Emoji inserted into file
##### Actual

Two characters are inserted and rendered as missing symbols:

![sep-28-2016 15-46-13](https://cloud.githubusercontent.com/assets/12821956/18935111/b44456d8-8592-11e6-92ab-91f97acede37.gif)

This seems to be a regression since 1.5. Could be related to the electron 1.3 upgrade?

**Comment by mjbvz** [comment]
You can copy and paste them in just fine, it just seems to be using the panel that produces the problem.

**Comment by mjbvz** [comment]
This also happens on Windows using the keyboard:

![image](https://cloud.githubusercontent.com/assets/12821956/18935512/57ec7c64-8595-11e6-8376-54f1feb5da4c.png)

Most are rendered as two question marks, but a few do get rendered for some reason.

**Comment by mjbvz** [comment]
@alexandrudima, I just was talking with @seanmcbreen and he mentioned some recent work to fix emojis crashing code. Could this bug be related to #12329?

**Comment by joaomoreno** [comment]
This used to work, yeah.

**Comment by thedaniel** [comment]
Did this get discussed?

**Comment by ramya-rao-a** [comment]
This still happens in Windows using the virtual keyboard

**Comment by ramya-rao-a** [comment]
Will use #15303 to track the Windows issue
