### ISSUE TITLE
HTML mode produces non-normalized links

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12954]
**Updated findings:**
The HTML mode produces non-normalized URIs when they have leading dots. The mode should ensure that the paths used for producing URIs are always normalized so that any "." and ".." are removed from the path and normalized.

While testing #12896:

- Explorer highlights wrong item.
- Two Tabs would open for the file created.

![12953](https://cloud.githubusercontent.com/assets/4033249/18935440/f6db6dc2-8594-11e6-943f-992ab1e70033.gif)

**Comment by bpasero** [comment]
Looks like "./foo.txt" and "foo.txt" are not the same in our system...

**Comment by bpasero** [comment]
@jrieken when you have a HTML such as:

`<script type="text/javascript" src="./Game2.js"></script>`

The resulting link that ends up being passed to the `openerService` is `file:///Users/bpasero/Documents/ticino-playground/./Game2.js`

Do you know where this link is being created? I think links should be normalized in a way that "." and ".." are removed.

**Comment by bpasero** [comment]
Also interesting to mention that this does not reproduce in 1.3.

**Comment by jrieken** [comment]
My guess is that the links are created [here](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/html/common/htmlWorker.ts#L601) and that during some string concatenation the links being messed up

**Comment by bpasero** [comment]
@jrieken my understanding is that since HTML moved into an extension the htmlWorker is no longer being used. I see a `languageService.findDocumentLinks` call in [htmlServerMain](https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts#L119) but do not see the implementation of that method.

**Comment by jrieken** [comment]
I guess it's here: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/package.json#L11

**Comment by bpasero** [comment]
Ok I will add a workaround for now because I think producing bad URIs can lead to bad bugs that are hard to track. Eventually I should just guard against this on my editor service layer but I am not brave enough to make this change so late.

@aeschli please revisit in October.

**Comment by jrieken** [comment]
Similarly we could invest if uri should normalise paths but I am also not brave enough for such a change (like ever 🙈)

**Comment by bpasero** [comment]
Well not sure if "." and ".." are valid in file URIs. I think they are as long as you have an absolute path to start with. 

Tricky thing is to deal with these non-normalized URIs in all our caches and maps where we call toString() and use that to compare for equalness.

**Comment by bpasero** [comment]
Maybe calling URI.fsPath should normalize? but then again, I often call toString() and that would not help me with comparision either.

**Comment by jrieken** [comment]
Yeah, `fsPath` and `path` should be normalised (resolved). That will then affect also the outcome of `toString` and that's the scary part of it because I believe we have persisted that as cache entries here and there...

**Comment by bpasero** [comment]
Although one could argue that there are not many places where we get such URIs into the system. E.g. if such a URI ends up in the editor area we quickly see 2 models with the same content but different URI appearing and people report it.

Still, NOT normalising also helps us to find those places where bad URIs enter the system as in this case with the HTML extension.
