### ISSUE TITLE
Improve aria label to have most important information at the beginning 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129533]
Testing #129161
@yuehuang010, @xisui-MSFT

1. Open disassembly view
2. Turn on screen reader
3. Focus on an element, notice the following being read out "Can set breakpoint, Instruction address: 0x000000ea, Instruction: of"

We need to imrpove this aria label:
1. The most important piece of information needs to go first, so that blind users can skip the boring repetitive part. So start with the "0x000000ea address, "
2. Make it more concise, I think "can set breakpoint" is not needed here
3. I do not understand the last part "intruction: of", this needs to be fixed I think

**Comment by xisui-MSFT** [comment]
@xisui-MSFT will fix this.

**Comment by xisui-MSFT** [comment]
@isidorn Is there a way to update aria label? Looks like it's set only when the element is rendered? I'm wondering if we can add/remove all texts about breakpoint and stack frame. If not, we should probably remove texts related to breakpoints.

Also, it's a great suggestion that we should reduce the amount of duplicates. So I'll change it to `Address: ..., Bytes: ..., Instruction: ...`.

As for `instruction: of`, it's likely the disassembly instruction you are looking at is `of`. For now, each line in disassembly view looks like:
`InstructionAddress    [InstructionBytes]    Instruction`
Where there may not be InstructionBytes.

For example,
`0x00012345     add eax, ebx`
Will have aria label (currently) `Instruction address: 0x00012345, Instruction: add eax, ebx`.

**Comment by isidorn** [comment]
@xisui-MSFT no, it is not possible to dynamically update the aria label.

> Will have aria label (currently) `Instruction address: 0x00012345, Instruction: add eax, ebx.`

This sounds good, I would just cut it short to be

`Address: 0x00012345, Instruction: add eax, ebx`
