### ISSUE TITLE
Disassembly view: clicking on the active line produces a weird green color

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129535]
Testing #129161

@yuehuang010, @xisui-MSFT 

1. Open disassembly view
2. Click on the focus yellow line
3. The line gets blue because of table selection, blue + focus yellow = green 🐛 

We should not introduce a new random color for this.
I believe we should just "disable" selection in the table for the disassembly, and just keep focus .

![Screenshot 2021-07-27 at 15 16 35](https://user-images.githubusercontent.com/1926584/127160046-7e0a5428-d826-4c90-af02-f4aa73698e46.png)

**Comment by weinand** [comment]
Yes, I provided that feedback already in my PR review (bullet 6 in https://github.com/microsoft/vscode/pull/125737#issuecomment-883318562).

**Comment by xisui-MSFT** [comment]
I don't really have a preference on this, but as I pointed in the original PR, one problem I found was that, if we disable selection, then there would be issues with keyboard navigation. And I know many people like to use keyboard navigation. Any solution to this?

**Comment by isidorn** [comment]
@xisui-MSFT keyboard navigation is based on table focus, not on selection. So selection is not related to keyboard navigation.
However I think the table might not provide an option to disable selection, you would have to experiment. In the end we might just use some smart css rules to make sure the right color is applied.

**Comment by xisui-MSFT** [comment]
@isidorn it does have an option to disable selection. But arrow keys behave weirdly. And I tested the functions related to focus but none of them help. I'll send you some screenshots after I go to work today.

**Comment by xisui-MSFT** [comment]
Actually just found we can set focus... Will do some tests later today.

**Comment by isidorn** [comment]
Fixed via #129616
