### ISSUE TITLE
Schema warning if enum has wrong values

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129584]
Testing #129448

Not sure if this is something that can be fixed but I noticed that if I had a bad configuration like:
```json
                                     "additionalProperties": {
						"type": "string",
						"enum": ["asdf", 2, "blah"]
					},
```
> notice the enum having a 2 in it

I don't get any warning and the user is confused because they're just picking an option given to them:
![image](https://user-images.githubusercontent.com/2644648/127203607-55add616-7392-4fe9-89fa-9ca086b2193d.png)

**Comment by rzhao271** [comment]
I'm surprised it's not validated on the JSON side.

<img src="https://user-images.githubusercontent.com/7199958/127208673-e7f84d74-1aa9-4514-a02b-a0eea765008a.PNG" width="400px">

@aeschli should there be validation in this case?

 The error message in the GUI editor does seem unclear, though.

**Comment by TylerLeonhardt** [comment]
I don't feel too strongly about this but thought this was kinda odd that the same message was displayed X times:
![image](https://user-images.githubusercontent.com/2644648/127556142-6e21c192-2fbc-4b36-9ee0-b6cd34fc5495.png)

**Comment by TylerLeonhardt** [comment]
I'll mark it as verified with that caveat ^ which I think could be fixed if we had JSON validation at the author stage.
