### ISSUE TITLE
Install additional renderers only searches for the Jupyter extension?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129566]
Testing #129463

When installing additional renderers it just searches for the Jupyter extension:

<img width="884" alt="Screen Shot 2021-07-27 at 9 29 23 AM" src="https://user-images.githubusercontent.com/2193314/127192007-a69397e4-9753-4584-96d0-d563dddb7e59.png">

I might be wrong but can't renderers be contributed by other extensions? Should it be searching for a category instead, or for extensions using a particular contribution point?

Also other usability things:

- The last item kind of feels like it should redirect to install the Jupyter extension instead of just not working
- If it's intentional that it just directs the user to the Jupyter extension, the wording of the quick pick item could say that

**Comment by Tyriar** [comment]
This also applies to Select Kernel which directs to only Jupyter

**Comment by roblourens** [comment]
Yeah, we will have a generic way to search for applicable kernels/renderers in the marketplace, that doesn't exist yet, Jupyter is currently hardcoded for this scenario.
