### ISSUE TITLE
Inlay hints disappear when scrolling too far?

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129608]
Testing #129465

Not sure why this happened:
![inlay](https://user-images.githubusercontent.com/19672699/127216509-6045b048-3ab1-4c19-bb8c-1047ced4f296.gif)

Source is here for that file:
https://github.com/microsoft/vscode-jupyter/blob/main/src/client/datascience/kernel-launcher/kernelProcess.ts

**Comment by mjbvz** [comment]
I can't tell what the gif is showing. That file also seems to work fine in my quick testing

Can you please add more details on what is going on here. Also what typeScript version were you using?

**Comment by rchiodo** [comment]
Inlay disappears as I scroll. 

![image](https://user-images.githubusercontent.com/19672699/127221348-f440bcf7-dc15-4929-a242-0f9f369ef68a.png)

Before I scroll:

![image](https://user-images.githubusercontent.com/19672699/127221391-fb44600c-112c-4a5c-a92b-8168205b0eb8.png)

After I scroll:

![image](https://user-images.githubusercontent.com/19672699/127221421-6d5ef607-9429-4d5e-beae-3089ddcf191d.png)

**Comment by mjbvz** [comment]
Thanks. Can you please also check the developer tools for this case? An exception could explain why this hints disappear

**Comment by rchiodo** [comment]
Oh this was the same as the other one. flags error in typescript. I should have duped this against the other one.

Dupe: #129565
