### ISSUE TITLE
Long inlay hints aren't wrapped

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#129673]
Testing #129381

Might be by design, but I don't see long inlay hints get wrapped. Instead, they are overflowed with ellipses. 

![image](https://user-images.githubusercontent.com/38270282/127296197-3dc66379-c01a-4ca8-af18-5e4aea34f6fc.png)

**Comment by hediet** [comment]
I think the ellipses are independent of the wrapping (I guess it is just coincidence that the ellipses are shown close to where the line would break). Can you verify that?

If you make the comment longer, it should break:

![image](https://user-images.githubusercontent.com/2931520/127300210-2de916d4-9f66-4208-ba75-45a67c20db78.png)

**Comment by alexr00** [comment]
Yes, ellipse are independent. The behavior I see is that first ellipse happen, and then if the inlay doesn't fit it will wrap. Seems like as designed then.

**Comment by hediet** [comment]
Yes. Thanks for testing!
