### ISSUE TITLE
clickable tracebacks follow `@` in filepath in the terminal, but not in the debugger popup

### ISSUE THREAD

**Issue by dasturge** [microsoft/vscode#129641]
Does this issue occur when all extensions are disabled?: Yes/No

Yes (aside from the relevant Python extension package v2021.8.1054534874-dev)

- VS Code Version: 1.58.2
- OS Version: Linux 5.4.0

Steps to Reproduce:

due to my organization's quirky setup, my linux username is my email address, e.g. my home folder is:

`/home/myemail@gmail.com/`

Normally, if a program crashes, you can ctrl+click on a link to seek directly to the relevant line of the traceback.  This works for a path in the terminal, but it doesn't work in a path on the red popup which shows up when the debugger catches the traceback prior to exiting.  Instead, the link is clearly broken up by the `@` in the username.  I hope this explains the issue clearly enough.

e.g.

```
  File "/home/myemail@gmail.com/anaconda3/envs/myenv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
```

I can ctrl+click this from the terminal, but not from the traceback which is caught during debugger execution, which means I can't as easily navigate to the flie/line with the debugger still up.

I can't just change my username to address this, sadly.

**Comment by isidorn** [comment]
There are already issues regarding link detection in debug, thus closing as dup of them
