### ISSUE TITLE
'no authentication provider 'github' is currently registered' pops up

### ISSUE THREAD

**Issue by jangminju** [microsoft/vscode#129680]
'no authentication provider 'github' is currently registered' pops up

I cannot connect to github.
However I search, I cannot find.
What should I do?
![20210705_112517](https://user-images.githubusercontent.com/84232038/127307422-b0466803-c73f-4c34-be30-66bf8beb4da6.png)

**Comment by TylerLeonhardt** [comment]
@jangminju can you send me what shows up here in the GitHub Authentication output channel:
![image](https://user-images.githubusercontent.com/2644648/127345504-c64ad1b3-cce5-4321-ba9f-40ead19e78d7.png)

Also any errors in Dev Tools:
![image](https://user-images.githubusercontent.com/2644648/127345573-9c92459e-7ad6-4330-9963-2158a6928fbb.png)
