### ISSUE TITLE
After upgrade to 1.58.2, VSCode show a blank window after run it.

### ISSUE THREAD

**Issue by Femtometer** [microsoft/vscode#129675]
Does this issue occur when all extensions are disabled?: Don't know, can't startup.

- VS Code Version: 1.58.2
- OS Version: Windows7 x64

Steps to Reproduce:

1. double click to run
2. failed to start, reinstall can't solve.

![截屏_2021-07-28_17-07-32](https://user-images.githubusercontent.com/5461891/127297046-c6c47292-cd21-4cf2-97b2-157233df9cc3.png)

**Comment by beatcracker** [comment]
I'm hit by this too, it's probably #128725 but I'm not sure. I had to rollback to `1.57.1`.

**Comment by Femtometer** [comment]
Issue update: Install 1.57.1, No problem, I'll use this for now.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`, also can you confirm if you have installed vscode to a symlink location ?

**Comment by Femtometer** [comment]
> Can you provide the output of `code --verbose`, also can you confirm if you have installed vscode to a symlink location ?

Yes, My vsode is in a symlink dir.

**Comment by deepak1556** [comment]
Thanks for confirming, merging to https://github.com/microsoft/vscode/issues/128725
