### ISSUE TITLE
Hitting "enter" when focus is on play button should trigger the command 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#129606]
Testing #129384

I was tabbing through the VS Code elements UI until focus hit on the play button:

![image](https://user-images.githubusercontent.com/45497113/127213712-9a0daaf7-e023-475d-9db1-69aca6c3d46c.png)

Once I hit enter, I was expecting the same behaviour as a button click. But nothing happened here. I had to tab to focus on the drop down arrow, hit enter, hit the down arrow to focus on "Run Java" and hit enter. Then it worked as expected.

**Comment by weinand** [comment]
@isidorn thanks, I'll try to implement your advice...

**Comment by roblourens** [comment]
This seems to work now
