### ISSUE TITLE
Enable code block syntax highlighting in setting UI

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#129645]
Steps to Reproduce:

1. Open settings UI and browse to the `javascript.inlayHints.propertyDeclarationTypes.enabled` setting

**bug**
This setting uses a typescript code block in its `markdownDescription`. This code block does not get syntax highlighting in the setting UI:

<img width="701" alt="Screen Shot 2021-07-27 at 4 33 57 PM" src="https://user-images.githubusercontent.com/12821956/127240815-445475b7-fd72-4d30-a754-67a8c2b2c70e.png">

However it does get highlighted in the settings.json:

<img width="660" alt="Screen Shot 2021-07-27 at 4 34 02 PM" src="https://user-images.githubusercontent.com/12821956/127240832-471cab6e-d007-4cd5-8c2a-c7103b84ddf0.png">

**Comment by mjbvz** [comment]
Ah sorry @rzhao271! Didn't notice you just opened a pr for this until I already pushed my change. Looks like our solutions are very similar

**Comment by bpasero** [comment]
It works but for some reason the font-size of 13px makes it appear larger for me compared to the other text:

![image](https://user-images.githubusercontent.com/900690/130608779-04be8783-119f-4fb6-a303-eb99b033f087.png)

vs. hardcoding 12px:

![image](https://user-images.githubusercontent.com/900690/130608811-ff4074e7-77b0-4807-bc40-a5fffcd3d9d9.png)

or even 11px:

![image](https://user-images.githubusercontent.com/900690/130608845-ad6a2691-df6b-46c4-bbda-6b276a558453.png)
