### ISSUE TITLE
"Open copilot" is a bad name for the action

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129676]
Testing #129383

"Open Copilot" is very obscure and the user has no clue what this is about to do.
I suggest to instead call this action: 
* "More..."
* "Open to the Side..."

![Screenshot 2021-07-28 at 11 28 54](https://user-images.githubusercontent.com/1926584/127299023-cb8815e4-bfa6-4917-9ca1-32aa3c348fde.png)

**Comment by hediet** [comment]
This is contributed by the copilot extension (@Krzysztof-Cieslak) - we are not in control of the name.

**Comment by hediet** [comment]
I'll close this one as there is nothing we can do about it.

If this is important, we should discuss it in Copilot's repository.

**Comment by isidorn** [comment]
@hediet can you please create an issue in the Copilot's repository since I do not have access. Or can you grant me access? Thank you

**Comment by hediet** [comment]
I pinged @Krzysztof-Cieslak. Unfortunately, I don't have admin rights on that repo. I forgot that you don't have access.

**Comment by hediet** [comment]
I created https://github.com/github/copilot-preview/discussions/1009.
