### ISSUE TITLE
Extension Details Tab - The dates and time should be on one line

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#129618]
Testing #129422

nit:
![image](https://user-images.githubusercontent.com/3840081/127222925-dd118d04-ecad-4cf3-be26-702f573c9e97.png)

**Comment by sandy081** [comment]
Do you see it always? I mean when you increase the size of the extension editor?

**Comment by karthiknadig** [comment]
Yeah, it still does that. It seems like that space for that column has a max limit.
![image](https://user-images.githubusercontent.com/3840081/127227585-661c0457-1f52-4f75-9787-bf0810cfe124.png)

**Comment by sandy081** [comment]
Yeah, actually I do not see `AM` text, hence I customized the width accordingly.

![image](https://user-images.githubusercontent.com/10746682/127228702-c404f132-3942-4535-8ec8-a07a704acc4e.png)

Seems like `Date.prototype.toLocaleString()` shows 24hr/12hr time by region. Fixed it to show 24hr time always.

Thanks for catching this.

**Comment by karthiknadig** [comment]
@sandy081 For my info. Any particular reason we don't want time by region?

**Comment by sandy081** [comment]
For the same reason that we have this issue. I have to then consider dynamic width.
