### ISSUE TITLE
Page-Up in git commit text box shifts everything to the left hiding the activity bar

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#12961]
- VSCode Version: 1.5.3 and 1.6 insiders (9/27)
- OS Version: Windows (doesnt happen in Mac)

Steps to Reproduce:

1. In the Git view, enter multiple lines of text into the commit message text box, until the scroll bar appears.
2. While the text box is focused, press Page-Up / Page-Down.

The entire page is shifted left such that the activity bar is hidden and there is some empty space on the right.

![image](https://cloud.githubusercontent.com/assets/16890566/18937181/c27b1736-85a2-11e6-9cec-16ef2328f598.png)

**Comment by joaomoreno** [comment]
The vertical scroll happens due to the feedback widget in the status bar.

The horizontal scroll happens due to the panel being open, which is tracked by #12876. @isidorn These are excellent repro steps.

**Comment by joaomoreno** [comment]
#13083
