### ISSUE TITLE
Native Notebooks - No Global Run Indicator

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129654]
Currently there is no global indictor to understand if a notebook is running something. There are two indicators for a cell running today - the blue in progress bar across the top of a cell and the spinner in the cell status bar. If I run all cells, the two indicators move off the screen and the notebook does not autoscroll with the cells that are running. Would be nice if there was a quick way to see if a notebook was running without having to slowly scroll and follow the execution or scrolling to bottom and waiting for it to complete. 

Steps to Reproduce:

1. Open notebook
2. Run all cells 
3. Don't scroll

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/124193
