### ISSUE TITLE
Provide an option to always show parent folder for files in tabs

### ISSUE THREAD

**Issue by steveinatorx** [Microsoft/vscode#12965]
- VSCode Version: Version 1.6.0-insider (1.6.0-insider)
- OS Version:

This is a fantastic feature for js devs - is there a way to always turn this on so all file tabs show the parent directory name not just when dupe filenames are open? 

https://www.dropbox.com/s/oqgf7tdqg5vsm7b/Screenshot%202016-09-28%2018.23.16.png?dl=0
![screenshot 2016-09-28 18 23 16](https://cloud.githubusercontent.com/assets/4932399/18937857/f104432e-85a8-11e6-87df-39927961d5e3.png)

**Comment by bpasero** [comment]
Currently there is no setting for this.

**Comment by OliverJAsh** [comment]
Also interested in seeing this! Should it be a feature or extension?

**Comment by steveinatorx** [comment]
seems a bit much to make it an extension.  i'd vote for a configurable option

**Comment by 8balloon** [comment]
Either a feature or an extension would be great... I have to say, for index files it'd I'd really love it if the parent folder name was emphasized *over* the "index" file name (e.g., if "index" was greyed out a bit) 

This would really set apart vscode for me, as working in multiple index files requires a significant cognitive load

**Comment by natew** [comment]
One of those things that not many people will think to search/vote for, but I think a lot of people would gain value from.

**Comment by nusson** [comment]
+1, especially useful for components like
/components/Button/index.js ;)

**Comment by tvald** [comment]
For reference, [tabsTitleControl.ts#L272](https://github.com/Microsoft/vscode/blob/aa79bd40ddfc9e07cd2de1145f55a555a3a5804b/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L272) would be the place to check for a config setting:
```
const description = label.hasAmbiguousName && label.description ? label.description : '';
```

**Comment by comerc** [comment]
I need this feature only for children folders of speciefed folder (for domain based structure of components).

Example

/components/Footer/Copyright.tsx > Footer/Copyright
/components/Footer/Contacts.tsx > Footer/Contacts
/components/Footer/Links.tsx > Footer/Links

**Comment by ephetic** [comment]
An [Atom plugin](https://github.com/joshwcomeau/nice-index) exists for this.  If someone makes an equivalent plugin for VSC first -- great -- if not, it'd be nice to see it become an editor setting.

**Comment by tvald** [comment]
#33718 provides a simple boolean configuration which controls whether tab descriptions are always shown.

A more complicated followup PR could provide a template system similar to `window.title`.

**Comment by tvald** [comment]
Replaced #33718 with #33815, which instead adds a simple template system.

**Comment by bpasero** [comment]
Pushed the changes, a new setting `"workbench.editor.tabSubtitle"` allows to control this. If you pick `short`, `medium` or `long`, the tab description will always be visible and either show parent folder, workspace root relative path or full path.

**Comment by bpasero** [comment]
**Verification**: play around with the `workbench.editor.labelFormat` setting and see that the description portion of the editor label in the tab well changes depending on the setting. Also verify for when tabs are disabled.

**Comment by natew** [comment]
Going along with this I find myself getting confused by fuzzy find really
often here because it doesn't prioritize index.js files. Would be
dramatically helpful if it weighted those as high as regular files, and
highlighted them more clearly too.
