### ISSUE TITLE
How do I edit workspace global config?

### ISSUE THREAD

**Issue by moxicode** [microsoft/vscode#129662]
This is my question
https://stackoverflow.com/posts/68526627/revisions

**Comment by meganrogge** [comment]
![workspace](https://user-images.githubusercontent.com/29464607/127336122-d1acb8a5-71fe-4538-9b12-d0e4154672fa.PNG)

**Comment by moxicode** [comment]
sorry,I mean to modify the user’s configuration, and through extension

**Comment by ArturoDent** [comment]
Please see the excellent answer at your question ;>}

`update()` has this signature:

> update(section: string, value: any, configurationTarget?:
> ConfigurationTarget | boolean | null, overrideInLanguage?: boolean):
> Thenable<void>

You want to use a `configurationTarget` of `true` to change the "User" settings, see https://code.visualstudio.com/api/references/vscode-api#ConfigurationTarget

`await vscode.workspace.getConfiguration().update('Lua.workspace.library', [libraryPath], true);`

I suggest also adding `await` so the changes are made before the rest of your code starts to run.

**Comment by moxicode** [comment]
> Please see the excellent answer at your question ;>}
> 
> `update()` has this signature:
> 
> > update(section: string, value: any, configurationTarget?:
> > ConfigurationTarget | boolean | null, overrideInLanguage?: boolean):
> > Thenable
> 
> You want to use a `configurationTarget` of `true` to change the "User" settings, see https://code.visualstudio.com/api/references/vscode-api#ConfigurationTarget
> 
> `await vscode.workspace.getConfiguration().update('Lua.workspace.library', [libraryPath], true);`
> 
> I suggest also adding `await` so the changes are made before the rest of your code starts to run.

ok thanks
