### ISSUE TITLE
Filtering of extensions that were disabled manually when in restricted mode

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#129627]
Testing #129421

When in restricted mode, it is a bit confusing to see manually disabled extensions in all categories under the `@workspaceUnsupported` filter:

![Screen Shot 2021-07-27 at 1 44 20 PM](https://user-images.githubusercontent.com/51720070/127227317-e0106992-0ba0-4355-b807-a8dd247793e6.png)

1. The Azure Resources extension was disabled because it doesn't support untrusted workspaces, so it makes sense that it is in the `Disabled in Restricted Mode` section;
2. The Babel extension was disabled globally, doesn't have the restricted mode icon, and the reason being displayed is that it was disabled by the user, no mention of restricted mode, so I didn't understand why it is in the `Disabled in Restricted Mode` section?
3. The Maven for Java extension was disabled globally, but provides limited functionality in restricted mode, so it makes sense that it's in the `Limited in Restricted Mode` section, but still a bit confusing that it's disabled.

**Comment by sandy081** [comment]
@lszomoru Assigning it to you as it is related to trusted workspaces feature. Feel free to reassign it to me if it is related to my changes.
