### ISSUE TITLE
Multicursor copy paste issue

### ISSUE THREAD

**Issue by RLeeFF** [microsoft/vscode#129685]
Issue Type: <b>Bug</b>

Multicursor selection copy and then Multicursor paste spread function doesn't work anymore! The multicursor setting is on spread not full and it will paste all the copied lines into each pasted lines. Very frustrating!

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (25.92GB free)|
|Process Argv|--crash-reporter-id 26dbea6a-8f3e-4e15-864d-7dc7aea9ed61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
project-manager|ale|12.3.0
vscode-json|and|1.5.0
All-Autocomplete|Ati|0.0.23
vscode-browser-preview|auc|0.7.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
codeswing|cod|0.0.20
codestream|Cod|11.0.13
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
crestroncomponents|Cre|0.0.34
macros|ctf|0.0.4
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.28.0
todo-tree|Gru|0.0.213
vscode-drawio|hed|1.6.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
easy-snippet|inu|0.6.3
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
vscode-essentials|jab|1.6.0
search-editor-apply-changes|jak|0.1.1
hungry-delete|jas|1.6.0
plantuml|jeb|2.15.1
vscode-text-pastry|jkj|1.2.0
svg|joc|1.4.9
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
vscode-format-context-menu|lac|1.0.4
thinking-in-code|los|0.0.10
vsls-whiteboard|los|0.0.12
pop-n-lock-theme-vscode|Lux|3.31.0
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.30.0
vscode-checkpoints|mic|1.3.2
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vsliveshare|ms-|1.0.4583
vsliveshare-audio|ms-|0.1.91
cordova-tools|msj|2.2.3
debugger-for-chrome|msj|4.12.12
jsflowchart|MUL|0.1.6
crestron-simpl-plus|mwg|1.3.0
crestron-simpl-plus-snippets|mwg|1.1.1
color-highlight|nau|2.4.0
json-parse-stringify|nex|1.0.2
gremlins|nho|0.26.0
material-icon-theme|PKi|4.8.0
polacode|pnp|0.3.4
vscode-data-preview|Ran|2.3.0
explorer-exclude-vscode-extension|Red|1.2.0
code-settings-sync|Sha|3.4.3
vscode-multiclip|sle|0.1.5
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
control-snippets|svi|1.9.1
pdf|tom|1.1.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
gitdoc|vsl|0.0.8
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by IllusionMH** [comment]
Are you sure that you have same number of cursors during copy and paste operations?

AFAIK distribution works only when number of copied ranges equals to number of destination cursors, in other cases it's just paste everything.

Setting `editor.multiCursorPaste` - Controls pasting when the **line count of the pasted text matches the cursor count**.

**Comment by RLeeFF** [comment]
Do you have same number of cursors during copy and paste operations

That was it!
I thought I had the same amount but had one more in the paste operation.
Thanks so much!!




Thank you and I look forward to your reply!

Russell Lee
Technical Engineer
***@***.***
Firefly Integrations
1013 Elroy Drive | Middlebury, Indiana 46540
Phone: (574) 825-4600
***@***.******@***.***>
www.FireflyIntegrations.com<http://www.fireflyintegrations.com/>

**Comment by RLeeFF** [comment]
Do you have same number of cursors during copy and paste operations

That was it!
I thought I had the same amount but had one more in the paste operation.
Thanks so much!!






Thank you and I look forward to your reply!

Russell Lee
Technical Engineer
***@***.***
Firefly Integrations
1013 Elroy Drive | Middlebury, Indiana 46540
Phone: (574) 825-4600
***@***.******@***.***>
www.FireflyIntegrations.com<http://www.fireflyintegrations.com/>
