### ISSUE TITLE
"Wait, how do I run a cell?" (I know the answer, personally, but it's pretty difficult to figure out if you're not privvy)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129636]
Testing #129463

Here's a snippet of a notebook I have. No Jupyter or Python extension loaded.

![image](https://user-images.githubusercontent.com/11685408/127233445-cdac9404-4074-4575-ad15-ae65c8e89602.png)

"Obviously" the user has to select a kernel to be able to run a cell. But given all the "stuff" on the screen, that is very difficult to see.

Note that if I press shift-enter in one of the cells, I simply get a new line inserted into the cell. We have had at least one user state that this occurred and that notebooks were completely broken.

![image](https://user-images.githubusercontent.com/11685408/127233863-b36563b1-7e12-4931-8d4a-8dad889c2eed.png)

**Comment by roblourens** [comment]
We now show the run button in a jupyter kernel when you have not installed jupyter. We had to remove it from today's build because of some issues but it will be back tomorrow. Then shift+enter and so on will also cause the install prompt to show up
