### ISSUE TITLE
Test: Identify keyboard shortcut overlaps 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129646]
Refs: #129463
- [x] windows @joyceerhl
- [x] macOS @DonJayamanne 
- [x] linux @tanhakabir 

Complexity: 2
---
 
Per feedback from customers regarding shortcut confusion and a discussion with Kai, we decided it would be good to understand the state of keyboard shortcuts for native notebooks, asap.

- What keyboard shortcuts that work inside VS Code by default (either the workbench or editor) are overridden or modified when the Jupyter extension is installed? Shift+enter is one. What are the others?
- What keyboard shortcuts do we still required to call Jupyter notebook keyboard shortcuts complete?

Please update this particular issue with details, or link to other issues.

**Comment by joyceerhl** [comment]
# What keyboard shortcuts do we still require to call Jupyter notebook keyboard shortcuts complete?

## Legend
❌   Command not implemented, keybinding not contributed
✅   Command implemented, keybinding contributed
N/A  Command implemented, keybinding not contributed


## Command Mode

| Classic Jupyter Keybinding | VS Code Builtin | VS Code Jupyter Extension |
| --------|-------------|------|
| F: find and replace | `Ctrl+F` | ✅ |
| Ctrl-Shift-F: open the command palette | `Ctrl+Shift+P` | N/A |
| Ctrl-Shift-P: open the command palette | ✅ | N/A |
| Enter: enter edit mode | ✅ | N/A |
| P: open the command palette | `Ctrl+Shift+P` | N/A |
| Shift-Enter: run cell, select below | ✅ | ✅ (⚠ overrides VS Code builtin for Markdown cells) |
| Ctrl-Enter: run selected cells | `Ctrl+Alt+Enter` | ✅ (⚠ overrides VS Code builtin) |
| Alt-Enter: run cell and insert below | ✅ | N/A |
| Y: change cell to code | ✅ | N/A |
| M: change cell to markdown | ✅ | N/A |
| R: change cell to raw | ❌ | ❌ |
| 1: change cell to heading 1 | ❌ | ❌ |
| 2: change cell to heading 2 | ❌ | ❌ |
| 3: change cell to heading 3 | ❌ | ❌ |
| 4: change cell to heading 4 | ❌ | ❌ |
| 5: change cell to heading 5 | ❌ | ❌ |
| 6: change cell to heading 6 | ❌ | ❌ |
| K: select cell above | `Up` | ✅ |
| Up: select cell above | ✅ | N/A |
| Down: select cell below | ✅ | N/A |
| J: select cell below | `Down` | ✅ |
| Shift-K: extend selected cells above | `Shift-Up` | N/A |
| Shift-Up: extend selected cells above | ✅ | N/A |
| Shift-Down: extend selected cells below | ✅ | N/A |
| Shift-J: extend selected cells below | `Shift-Down` | N/A |
| Ctrl-A: select all cells | ✅ | N/A |
| A: insert cell above | `Ctrl+Shift+Enter` | ✅ |
| B: insert cell below | ⚠ `Ctrl+Enter` | ✅ |
| X: cut selected cells | N/A | ✅ |
| C: copy selected cells | N/A | ✅ |
| Shift-V: paste cells above | `Ctrl+Shift+V` | N/A |
| V: paste cells below | N/A | ✅ |
| Z: undo cell deletion | N/A | ✅ |
| D,D: delete selected cells | `Delete` | ✅ |
Shift-M: merge selected cells, or current cell with below if only one cell is selected | ❌ | ❌ |
| Ctrl-S: Save and Checkpoint | ✅ | N/A |
| S: Save and Checkpoint | `Ctrl+S` | ✅ |
| L: toggle line numbers | N/A | ✅ |
| O: toggle output of selected cells | `Ctrl+K T` | ✅ |
| Shift-O: toggle output scrolling of selected cells | ❌ | ❌ |
| H: show keyboard shortcuts | ❌ | ❌ |
| I,I: interrupt the kernel | ❌ | N/A |
| 0,0: restart the kernel (with dialog) | ❌ | N/A |
| Esc: close the pager |❌ | ❌ |
| Q: close the pager | ❌ | ❌ |
| Shift-L: toggles line numbers in all cells | N/A | ✅  |
| Shift-Space: scroll notebook up | ❌ | ❌ |
| Space: scroll notebook down | ❌ | ❌ |

## Edit Mode

WIP

**Comment by joyceerhl** [comment]
# What keyboard shortcuts that work inside VS Code by default (either the workbench or editor) are overridden or modified when the Jupyter extension is installed?

Conflicts
- `Ctrl+Enter` is 'Insert Line Below` in VS Code editors, 'Insert Cell Below' in VS Code notebooks, and 'Run Cell' in the Jupyter extension and classic Jupyter
- `Shift+Enter` is 'Terminal: Find Next' in VS Code. When the current cell is a code cell in command mode, it runs the current cell and selects the next cell. When the current cell is a markdown cell, it does not render the markdown cell and selects the next cell. The Jupyter extension overrides this behavior to make Shift+Enter run current and advance for both code and markdown cells, in command and edit mode
- `Ctrl+; A` is 'Test: Run All Tests' in VS Code and 'Jupyter: Insert Cell Above' for interactive window script files
- `Ctrl+; M` is 'Test: Peek Output' in VS Code and 'Jupyter: Change Cell to Markdown' for interactive window script files
- `Ctrl+; C` is 'Test: Run Test at Cursor' in VS Code and 'Jupyter: Change Cell to Markdown' for interactive window script files
- `Ctrl+R` is 'Developer: Reload Window' in VS Code and 'Jupyter: Refresh Data Viewer'
- `Alt+Enter` is 'editor.action.selectAllMatches' in VS Code editors and 'jupyter.runcurrentcellandaddbelow' for interactive window script files
- `Ctrl+Shift+-` is 'View: Zoom Out' in VS Code and `Split Cell` in Jupyter

**Comment by DonJayamanne** [comment]
# Bug in current shortcuts
* Insert cell above & below `a/b`
Currently it inserts a cell and goes out of command mode (and cursor is in the editor). it should not go out of command mode
