### ISSUE TITLE
Terminal options color not respected

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#129643]
Testing #129009

[Terminal options screen Recording.zip](https://github.com/microsoft/vscode/files/6889222/Screen.Recording.2021-07-27.at.4.19.34.PM.zip)

Not sure if there are additional steps in the setup.

Version: 1.59.0-insider
Commit: c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2
Date: 2021-07-27T15:07:54.419Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.11.22-100.fc32.x86_64

**Comment by Tyriar** [comment]
You need to pass in a `ThemeColor`:

```ts
vscode.window.createTerminal({
	name: `Ext Terminal #${NEXT_TERM_ID++}`,
	color: new vscode.ThemeColor('terminal.ansiYellow')
} as any);
```

![image](https://user-images.githubusercontent.com/2193314/127316832-3cbbf271-bf3f-46b6-8605-aa4115ae4ab1.png)
