### ISSUE TITLE
Never-ending extension "update available" loop after updating vscode.engines property

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#12960]
Testing #12658 (Windows)

Repro steps:
1. Publish [test-extension-pack-1](https://github.com/Microsoft/vscode-extension-samples/tree/master/extension-deps-sample) 
2. install extension, restart vscode
3. Increment the version and change the vscode.engines property to `"^1.7.0"`, publish again
4. Search for extension in marketplace

**Expected:**
"no update" button doesn't appear or some warning about the latest version being incompatible w/ vscode

**Actual:**
Extension pack appears with update button
![image](https://cloud.githubusercontent.com/assets/762848/18936945/c0c98546-85a0-11e6-8dc1-42d424b6570d.png)

Clicking the update button "installs" the extension, adds an "enable" button, but doesn't disable the "update" button
![image](https://cloud.githubusercontent.com/assets/762848/18936961/ec85854a-85a0-11e6-87dd-292002b11573.png)

Press Update button a couple more times (for science!)
![image](https://cloud.githubusercontent.com/assets/762848/18936970/00b6b2fa-85a1-11e6-921e-0c65ae3871d4.png)

Press Enable button, restart VSCode

Search again, extension not installed.... Repeat, ad infinitum

**Comment by joaomoreno** [comment]
Maybe #12011 ...

**Comment by sandy081** [comment]
Not related to #12011. Could be related to compatibility check which I could reproduce.

**Comment by sandy081** [comment]
@mousetraps Good catch.
