### ISSUE TITLE
Support null values in the settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129620]
Testing https://github.com/microsoft/vscode/issues/129593 

The setting editor currently doesn't render rows with null values. Even though `IObjectDataItem` doesn't expect null values, null values are possible, because the user can specify `"key": null` in the JSON file. 

We should just render an empty string for the value.
Currently assigning to the next milestone because I do not expect users to hit this case very often unintentionally.

**Comment by roblourens** [comment]
The problem is how can you differentiate between an empty string and a null? We investigated this a while back and decided that some settings would be affected by confusing those two things. This is why we support `number | null` but not `string | null`. I am totally open to new suggestions for how to handle this though.

**Comment by roblourens** [comment]
I didn't read this carefully, I see you are talking about the object widget specifically. I think it's a similar problem. But I'd like to see an example of a setting that uses null values.

**Comment by rzhao271** [comment]
I was thinking of showing the row so that the user doesn't just see an error message without a matching row, such as here: https://github.com/microsoft/vscode/issues/129593#issuecomment-887817635

But, the only way a user can hit that case (that I'm aware of) is if they purposely tried to glitch the settings editor by changing a setting to null.

**Comment by roblourens** [comment]
Oh ok, I don't think this is worth it

**Comment by rzhao271** [comment]
Marking as won't fix for now. Readers who want a fix can either comment on this issue, submit a PR, or create a new issue (in case this issue is stale/locked).
