### ISSUE TITLE
Consider a more explicit message about missing outputs when detected...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129632]
Testing #129463

- Imagine a new user is opening a notebook with VS Code. No Python or Jupyter is installed and are perusing a set of notebooks for the first time.
- They either:
   - Notice the notification asking whether they want to install extensions for Python and ignore or decline
   - Don't notice the notification
- They are looking for a notebook with some set of output

As they scroll, they don't notice some of the cell outputs that indicate that a renderer can't be found. However, they may also see some cell output rendered, so they have no reason to believe anything is amiss.

They continue looking for output, but eventually discover they need to do an extra step and install the Jupyter extension at least.

Possible suggestions:
- Add color and/or icon to the message indicating a renderer cannot be found to make it stand out.
- Detect the situation and automatically display the "install additional renderers from the marketplace" quick pick
- Show a modal dialog box indicating that some cell output may not be visible until additional renderers are installed. 
- Possibly other ideas... the above are just possibilities.

**Comment by roblourens** [comment]
@connor4312 I think you did this? Do you have an issue to dupe against?

**Comment by connor4312** [comment]
Yea, there's now a button for outputs:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2230985/134618860-bc2c0b08-a739-40c3-ba06-e8cc9cf080f1.png">

https://github.com/microsoft/vscode/issues/123581
