### ISSUE TITLE
Multiple cells can be shown as having focus at the same time. This shouldn't be.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129639]
Testing #129463

Note, this bug makes turning the "Cell Focus Indicator" to "border" unusable, but it also happens when "gutter" is selected, making things confusing at least.

This shouldn't be possible, I don't think: 
![image](https://user-images.githubusercontent.com/11685408/127234515-05cc7643-8f9e-431a-91be-b64714e45524.png)

To achieve it, just select a cell, scroll it off the top or bottom of the view and select another cell, then scroll back up.

**Comment by roblourens** [comment]
Probably same as https://github.com/microsoft/vscode/issues/129635

**Comment by greazer** [comment]
Doesn't seem like a dupe of ultimately linked (and fixed) issue. Still repros in latest insiders.

![Multiselectbug](https://user-images.githubusercontent.com/11685408/127547349-952545d9-fce8-443f-b266-9ff750ab7c72.gif)

**Comment by roblourens** [comment]
Different than the duped issue, but not a regression. Need to be able to unfocus cells even when they are not rendered
