### ISSUE TITLE
Injected text not distinguishable from normal text in HC theme

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129678]
Testing #129383

I understand that in HC theme we need strong contrast and thus we can not use a "ghosted" text. However this might mean that we need to have some additional decoration (apart from color) to distinguish that the text is not inserted yet.

Maybe some floating icon would help, or italics?

![Screenshot 2021-07-28 at 11 50 11](https://user-images.githubusercontent.com/1926584/127302304-af5120a5-dc28-4469-9894-171053b350ee.png)

**Comment by hediet** [comment]
We could add a border around inline suggestions:

![image](https://user-images.githubusercontent.com/2931520/129045801-c009180f-15fd-483c-9122-e9f967891791.png)

I don't think italic is enough:

![image](https://user-images.githubusercontent.com/2931520/129045966-d8498875-422f-4e83-887e-df6f4bc703fe.png)

**Comment by isidorn** [comment]
Maybe border + italic?
Since border for me means stronger. And this should not be stronger but lighter..

**Comment by hediet** [comment]
What about this:

![image](https://user-images.githubusercontent.com/2931520/136243440-e350ef78-b7db-4332-9042-0b57a5423651.png)

(normal ghost text is italic by default now)

**Comment by isidorn** [comment]
Yeah! I like it.

**Comment by hediet** [comment]
Implemented in 3149492f.
