### ISSUE TITLE
KaTeX parse error with triple $ with new built-in notebooks

### ISSUE THREAD

**Issue by ab-gh** [microsoft/vscode#129689]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 11

# Steps to Reproduce:

1. Open an ipynb with the new [built-in notebooks](https://github.com/microsoft/vscode-jupyter/issues/6628)
2. In a markdown cell, use triple $ to open a centered KaTeX
```
$$$
\alpha\beta
$$$
```

# Expected Result
- TeX rendered

# Actual Result
`ParseError: KaTeX parse error: Can't use function '$' in math mode at position 1: $_\alpha\beta $`
![image](https://user-images.githubusercontent.com/18347932/127336516-10ce3e54-7682-4c5d-818d-b495b2beb325.png)
![image](https://user-images.githubusercontent.com/18347932/127336540-97924c3f-c4de-465f-bca4-86c8cfbfc1c1.png)

Possibly an extension of #128490

**Comment by mjbvz** [comment]
We use `$$` for math blocks. Is `$$$` supported in other notebook environments?

**Comment by aejb** [comment]
`$$$` was functional in the previous version of the notebook editor, and used by [some assignment grading software](https://help.gradescope.com/article/3vm6obxcyf-latex-guide)
