### ISSUE TITLE
Having `--data-dir` to enhance the Portable Mode experience

### ISSUE THREAD

**Issue by bahag-raesenerm** [microsoft/vscode#129667]
Hey everybody. First of all let me thank you for VSCode to everyone involved, I really love it.

I even have multiple instances of VSCode each in it's own folder with a `code-portable-data` folder alongside (macOS).

now I could easily have a symlink for every "profile" of VSCode I want to start from CLI, f.e. I have a symlink for `code-react` and I can open a folder with my React centric VSCode setup. So individual themes, Extensions and so forth.

Currently, I have an actual copy of the `Visual Studio Code.app` package for each instance. This is needed because I can pass `--extensions-dir` and `--user-data-dir` to code, which is nice but doesn't help me here. What could be even better is to pass just "the whole portable user data folder" to the instance, as if it's alongside in the filesystem. f.e. I could imagine `--data-dir` for this.

I tried to avoid a duplicate issue, there are issues "similar in topic" and others related to the cli flags but I think my suggestion isn't covered yet. 

have a great day!

**Comment by joaomoreno** [comment]
> This is needed because I can pass `--extensions-dir` and `--user-data-dir` to code, which is nice but doesn't help me here.

Why exactly doesn't this help? You could create scripts that pass along the right folders for you.
