### ISSUE TITLE
Ellipses for choosing renderers can be misplaced and confusing...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#129633]
Testing #129463

Here's an example output from a notebook of mine. It's not clear that I can do anything here as the ellipses appears far above the message indicating that one cannot be found. Note the issue related to having a link in the "No renderer could be found message" could alleviate this.

![image](https://user-images.githubusercontent.com/11685408/127233159-1cc693f6-865d-4d20-8059-368c352b70bd.png)

**Comment by roblourens** [comment]
Are there two outputs here? I'm a little confused
