### ISSUE TITLE
Odd diff editor behavior

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129649]
Testing #129463

Using the Remote Repositories extension to open a repo full of notebooks in VS Code (though this also repros outside of RR)
When I open a notebook, I do get the notebook UI:
![image](https://user-images.githubusercontent.com/2644648/127237720-36745d5c-132b-4b88-a2fb-07481f9b208f.png)

Then I try to open the diff in the source control tab but the editor doesn't appear to change to the diff view:
![image](https://user-images.githubusercontent.com/2644648/127237800-ebbd0a75-043b-476e-a932-cf824284a31e.png)

I need to close the editor first:
![image](https://user-images.githubusercontent.com/2644648/127237841-1d167cdd-7304-4007-9bfd-5e3313521476.png)

then open the diff view for it to show up:
![image](https://user-images.githubusercontent.com/2644648/127237887-efc7e0db-4704-43df-a262-7a39a64277ff.png)

**Comment by joyceerhl** [comment]
@rebornix IIRC you said this is a regression in the editor service?

**Comment by rebornix** [comment]
@lramos15 do you know if we are doing anything wrong in notebook?

**Comment by lramos15** [comment]
Nothing wrong on the notebook end :). Surprised this wasn't caught sooner as it's been broken all iteration.
