### ISSUE TITLE
Cell selection not restored after moving out of view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129635]
Issue Type: <b>Bug</b>

* select a cell
* move it out of view
* move it back
* cell is not reselected

VS Code version: Code - Insiders 1.59.0-insider (c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2, 2021-07-27T15:09:36.374Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by joyceerhl** [comment]
Related to https://github.com/microsoft/vscode/issues/129432?
