### ISSUE TITLE
Always open files with extension '*.fvl' (which is xml) with encoding ISO 8859-15

### ISSUE THREAD

**Issue by itreppert** [microsoft/vscode#129670]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Windows 10

Steps to Reproduce:

1. Trying to get '*.fvl' files to be opened with encoding ISO 8859-15
2. There seems to be no way

Explanation:

- I can assign 'fvl' to the xml language in VSCode and then assign the encoding to xml, but not to 'fvl'....
- I don't want '*.xml'-files to be opened with this encoding.....
- I want the search and replace (CTRL-SHIFT-F) to use this encoding

Don't ask me, why the developers of the tool I have to use (which produces the fvl-file), use this encoding.... It's ridiculous, but do you see the problem ?

**Comment by itreppert** [comment]
The above issues don't relating to my 'bug'

**Comment by gjsjohnmurray** [comment]
My suggestion at https://github.com/microsoft/vscode/issues/127936#issuecomment-888237160 would solve this issue too.

**Comment by bpasero** [comment]
@itreppert to clarify: is this an issue for files you open from the windows explorer into a new instance of VSCode or even when you are inside VSCode and click on a file from VSCode's file explorer?
