### ISSUE TITLE
(auto) does not go away after I explicitly select the already picked language

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#129600]
Testing #129436

1. Paste some code so we auto detect it as Typescript for example
2. Click on the language picker and choose Typescript
3. I would expect the `(Auto)` to go away, since the user confirmed that the choice is good

**Comment by TylerLeonhardt** [comment]
Confirmed. Gonna save this for the next milestone since we might get rid of the `(Auto)` text.

**Comment by TylerLeonhardt** [comment]
We removed `(Auto)` text.
