### ISSUE TITLE
Ctrl+Enter not binding in find+replace menu

### ISSUE THREAD

**Issue by zkldi** [microsoft/vscode#129666]
Issue Type: <b>Bug</b>

The find and replace widget no longer respects ctrl+enter as a command for replaceOne. My bindings as of a month ago were c-a-enter for replace all, and c-enter for replaceOne.

When I try to do this now, I get 'Ctrl+Enter now inserts line break instead of replacing all. You can modify the keybinding for editor.action.replaceAll to override this behavior.'.

A cursory search of the repo for this text shows that nothing around it has been edited recently, which leads me to guess there's a regression somewhere?

Changing editor.action.replaceOne to ctrl+enter seems to not affect the input box at all. Infact, it says that replaceOne is bound to `enter`, but enter just inserts a newline.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.23GB free)|
|Process Argv|--crash-reporter-id 30d96df5-2e50-4bf3-97ca-4856d8aa435e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)|
|Memory (System)|12.43GB (6.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)|
|Memory (System)|12.43GB (6.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3699)|
|Memory (System)|12.43GB (6.80GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
vscode-firefox-debug|fir|2.9.4
better-cpp-syntax|jef|1.15.6
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
vscode-icons|vsc|11.5.0
xml2json|bui|1.2.4
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-pull-request-github|Git|0.28.0
go|gol|0.26.0
simple-vim|jpo|0.0.5
restructuredtext|lex|155.0.0
rainbow-csv|mec|1.9.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.13
cpptools|ms-|1.5.1
hexeditor|ms-|1.8.2
vscode-typescript-next|ms-|4.4.20210727
gremlins|nho|0.26.0
vscode-create-test-file|pau|0.0.1
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.21.1
rust|rus|0.7.8
vscode-coverage-gutters|rya|2.8.0
vscode-node-tap|sar|0.2.0
vscode-scss-formatter|sib|2.2.3
vscode-vuln-cost|sny|1.6.0
lua|sum|2.3.3
vscodeintellicode|Vis|1.2.14
literally-html|web|0.1.3
file-size|zh9|1.0.0

(2 theme extensions excluded)

</details>

**Comment by zkldi** [comment]
> Changing editor.action.replaceOne to ctrl+enter seems to not affect the input box at all. Infact, it says that replaceOne is bound to enter, but enter just inserts a newline.

Restarting the window updated the prompt for replaceOne to say ctrl+enter, but ctrl+enter still just inserts a newline.

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @rebornix

I'm ready for help if needed.

Just guide me through and I will goo

Best of luck!

**Comment by zkldi** [comment]
Update as of today - Haven't changed anything, but ctrl+enter now runs replaceOne **AND** inserts a newline beforehand, which makes it unusable :(

**Comment by bpasero** [comment]
@rebornix is this kind of notification still needed or can we remove it by now?

https://github.com/microsoft/vscode/blob/fa63d292e4320e46a30cd16ff9c2c615e1fb3891/src/vs/editor/contrib/find/browser/findWidget.ts#L884-L887

**Comment by rebornix** [comment]
@bpasero good catch, it's time to get rid of it. https://github.com/microsoft/vscode/pull/245182
