### ISSUE TITLE
Pencil icon instead of gear icon to set profile name for terminal profiles

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#129610]
Testing #129429

I was tasked to change the profile name of a terminal profile but I was confused as to how to do it initially since it wasn't intuitive for me to click on the gear icon. A pencil icon since the gear leads to only one modification makes more sense to me

**Comment by meganrogge** [comment]
I think this makes sense. @Tyriar thoughts?

**Comment by Tyriar** [comment]
Do you mean here?

![image](https://user-images.githubusercontent.com/2193314/127313811-7f44b2bc-8ff4-4ea0-bdf5-6a0106a544b7.png)

We had a discussion about this recently where pencil was used for configuring custom editors and the overwhelming feedback was to make it a gear for consistency.

**Comment by tanhakabir** [comment]
I did, ah hmm I see. For me it's a bit confusing on first glance but I suppose if we have more gears overall I'd feel more incentive to click gears.

**Comment by meganrogge** [comment]
I see Tanha's point since my thought when I see the gear is that I'll be taken to settings or at least get to configure several properties. The gear does not signal rename to me.

**Comment by Tyriar** [comment]
It's creating an explicit entry in your settings.json, if it isn't there already and then opening it to allow you to configure. So configuring is the right word here imo as renaming is not the only thing you can configure.

**Comment by meganrogge** [comment]
Ok makes sense to me
