### ISSUE TITLE
The notification to install recommended extensions isn't consistent?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129650]
Testing #129463

What's the logic around when the notification to "install recommended extension for foo.ipynb" is shown? It seems to happen somewhat randomly for me... I can't get it to show up consistently... and I couldn't get it to show up again to include a screenshot in this issue. I've just hit the x button on it so I don't think I've accidentally hid it forever.

I was opening these notebooks: https://github.com/TylerLeonhardt/JupyterNotebooks

edit: this one! It finally randomly popped up
![image](https://user-images.githubusercontent.com/2644648/127239406-14ed6c45-345e-411f-809b-97517fb0d72d.png)

**Comment by roblourens** [comment]
It will only be shown once per window at least. Not sure if there is also a timeout to avoid showing it too often?

**Comment by TylerLeonhardt** [comment]
> I was thinking it's only once per filetype, ever, cached in global storage, that might not be right.

even if I hit the `x`?

**Comment by roblourens** [comment]
I guess I got it again after reloading the window, so I'm not sure

**Comment by sandy081** [comment]
This is shown until the user takes an action. An action can be any button that is shown - say: Install, Show Recommendations and even Close (`x`). If it go dismissed/canceled with out taking an action, we show it again.

Code ref for cancelling.

https://github.com/microsoft/vscode/blob/f52952332d14de7517cb22b002ef1352ecdee889/src/vs/platform/notification/common/notification.ts#L264-L268

> even if I hit the x?

Yes, It is annoying if I close it explicitly and I keep seeing it.

**Comment by gjsjohnmurray** [comment]
Maybe add a "No" button?
