### ISSUE TITLE
the insider can't use System.Diagnostics.Process.Start open path

### ISSUE THREAD

**Issue by kefengwei** [Microsoft/vscode#12968]
- VSCode Version: Code - Insiders 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb, 2016-09-28T06:09:46.794Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

when i use System.Diagnostics.Process.Start(@"G:/Program Files (x86)/Microsoft VS Code Insiders/bin/code-insiders.cmd", @"c:\Users\kefeng\test.txt") ;  can't open then path and got nothing notifacation.

**Comment by joaomoreno** [comment]
Does it work for stable? Does it work when adding a `--wait` argument?

@bpasero Could be the Electron update.

**Comment by kefengwei** [comment]
it's work for stable. it's the same when add --wait argument.

**Comment by bpasero** [comment]
@kefengwei so everything works in 1.6. insiders if you use `--wait` argument?

**Comment by kefengwei** [comment]
@bpasero i update the latest insiders. the problem is disapear.
