### ISSUE TITLE
Git extensions UI isn't able to show a merge conflict with 1 file when there are 10k staged changes in the merge (VS can)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#129669]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: today's Insiders
- Version: 1.59.0-insider (user setup)
Commit: c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2
Date: 2021-07-27T15:09:36.374Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
- OS Version: Windows

Steps to Reproduce:

1. Use the VS Code git UI to merge one branch into another that has 10k changed files with 1 file having a merge conflict.

Bug: VS Code gives "The git repository at has too many active changes, only a subset of Git features will be enabled. " and the 1 file with the merge conflict doesn't appear in the tree so I'm not able to use the UI to resolve the merge conflict. I don't need to interact with the 10k staged files, so the UI can skip populating the staged changes node if it can't handle it, but it should be able to populate the 1 unstaged merge conflict file. Once I resolve the merge conflict, then VS Code should be able to handle it, either automatically or giving some option to commit all staged changes (i.e. VS Code handles the merge fine if there's no merge conflict).

The VS git UI is able to handle the scenario. Screenshot is from after I resolved the 1 merge conflict.
![image](https://user-images.githubusercontent.com/19859882/127278714-e787a8a2-0827-4358-8961-c4208358c52a.png)

**Comment by sean-mcmanus** [comment]
@vscodebot Those issues are not a duplicate of this one.

**Comment by eamodio** [comment]
I think we have a hard limit of 5000 changes. We can look into bumping that up and/or adding a setting to control it.

**Comment by eamodio** [comment]
There is now a new `git.statusLimit` setting to control the number of status files we will parse before giving up. I've also changed the default from 5000 to 10,000. And if you want you can set the value to `0` to have no limit at all -- but that could take a while if there are LOTS of changes.

**Comment by eamodio** [comment]
Additionally, there is a new validation warning that will show on the input box for this case.
![image](https://user-images.githubusercontent.com/641685/135391064-51e5fe78-add4-4e9d-b029-f64b1ba040f6.png)
