### ISSUE TITLE
Inlay hints moving when typing

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#129637]
Testing #129465

System information:
- VS Code 1.59.0-insider Commit: c3b4df8f5d9c14aa4cfddb587231d0d52e72e5a2
- maOS Big Sur 11.4
- TypeScript 4.4.0-dev20210726
- File: [pythonPathUpdaterService.ts](https://github.com/microsoft/vscode-python/blob/2db4df95b1f58a1ee1934550fd966466ceb7e459/src/client/interpreter/configuration/pythonPathUpdaterService.ts) in the [vscode-python](https://github.com/microsoft/vscode-python/) repo

https://user-images.githubusercontent.com/51720070/127233728-c598e0c0-965c-4532-8c84-dd7f281dc4e1.mp4

**Comment by mjbvz** [comment]
@hediet I'll look to see if there's something going wrong on the TS side in this case

**Comment by Kingwl** [comment]
I guess It's caused by the conversion between line/col and offset.

**Comment by mjbvz** [comment]
@Kingwl  Do you think this is caused by using document offsets instead of positions?

I'm still investigating but it seems like the typescript server may be temporarily getting out of sync with VS Code

**Comment by Kingwl** [comment]
Well, out of sync does make sense.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/45320 with steps to reproduce upstream

**Comment by rebornix** [comment]
@mjbvz I reopened this issue as it's not fixed and having it closed will lead to us reporting duplicates.

**Comment by mjbvz** [comment]
We're tracking this upstream as the root cause appears to be on the TypeScript side
