### ISSUE TITLE
Custom hover status bar styles are messed up

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129683]
![image](https://user-images.githubusercontent.com/2193314/127317336-2ce491c7-ce2c-435c-a92e-73bb52cd3ad3.png)

**Comment by rzhao271** [comment]
I forgot how to get into that state in the first place :s

**Comment by rzhao271** [comment]
Oh right, configuring `terminal.integrated.environmentChangesRelaunch` helped.
