### ISSUE TITLE
Run by line: Error in cell requires explicit stop

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#129657]
Testing #129467

I suppose encountering an error is the same as reaching the end of a cell? I know the original issue mentions:

> Once you've stepped to the end of the cell, you have to press the stop button in the cell toolbar

It looks like the same happens if there's an error:

![recording (39)](https://user-images.githubusercontent.com/25310137/127247888-17f89f1d-0540-4b50-a471-3ec4c473583a.gif)

Is this expected? Would we want to stop for users automatically?

**Comment by roblourens** [comment]
Yes, this is the same as that known issue
