### ISSUE TITLE
Insiders: "ApplicationInsights:An invalid instrumentation key was provided" warnings in developer console

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#129727]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.  Insiders Build
2. Debug an extension
3.  5 "ApplicationInsights:An invalid instrumentation key was provided." messages are output to the `Debug Console`.  

![ApplicationInsightsMessage](https://user-images.githubusercontent.com/31813701/127411049-c6d701e1-308b-4cac-9fe0-22cb3efe5e7c.jpg)

`extension.js`:  

```js
async function activate() {}
module.exports = {
	activate
	// deactivate
}
```

or same result with some code, breakpoints or not.

Version: 1.59.0-insider (user setup)
Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
Date: 2021-07-28T05:13:47.114Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by isidorn** [comment]
Debug is just picking up messages from the console.
The real problem is the following.

1. Start VS Code, open developer tools > debug console
2. Notice `ApplicationInsights` warnings

I am not sure who owns the `ApplicationInsights` telemetry, but for now assigning to @sbatten

```
console.ts:137 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1) (at console.e.<computed> [as warn] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
v @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1) (at console.e.<computed> [as warn] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
v @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1) (at console.e.<computed> [as warn] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
v @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1) (at console.e.<computed> [as warn] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
v @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss Array(1) (at console.e.<computed> [as warn] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:170797))
```

**Comment by mjbvz** [comment]
@lramos15 Can you please take a look since Steven is out?

**Comment by TylerLeonhardt** [comment]
@lramos15 said this is expected for now here: https://github.com/microsoft/vscode/issues/129807#issuecomment-889467532

> This is a standard warning and can be safely ignored. It has to do with us using the application insights module in a non-standard way. The work to fix this won't be happening for at least a few more iterations and there's nothing we can do about it right now.

I'm going to move it out to the next milestone for @lramos15 to clarify anything.

**Comment by isidorn** [comment]
@lramos15 this is spamming the debug console for Extension developers, thus making the experience not nice.
Is it possible to somehow suppress the warning?

**Comment by lramos15** [comment]
> Is it possible to somehow suppress the warning?

Yes and no. This warning comes from the application insights NPM module due to the schema validation not handling specialized 1st party keys. The way we could suppress the warning is to bundle the app insights module into our NPM module and then remove that log line. This would prevent NPM from downloading the app insights module as a dependency which I feel isn't as transparent.

**Comment by weinand** [comment]
@lramos15 could we add an option to the application insights NPM module for suppressing this specific type of warning?

**Comment by lramos15** [comment]
@weinand Sadly no. I spoke to the team as I figured this was going to cause some issues but we're on a heavily deprecated path that they're not interested in supporting anymore. There is some work to move to a different telemetry handling package that is better supported for our use cases but that work isn't slated for the next milestone so this warning will stay unless we do the hand patching. I could also downgrade us back to the old version we were using before, this warning was introduced in a newer version but I'm not sure if there are security concerns surrounding the older packages as we were a few years behind.

**Comment by lramos15** [comment]
I've hand patched this and gone with the suppressing the warning by just removing the logging line as I feel like many users will be worried by this warning
