### ISSUE TITLE
"Trust parent" translated incorrectly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#129775]
Testing #129410

1. Open an untrusted folder with the French language pack installed
2. :bug: The "trust parent" button seems to be translated to something that means "parent of trust" rather than "to trust to the parent folder"

![Example screenshot](https://user-images.githubusercontent.com/7199958/127520699-cc4cfcd5-baf9-4ac5-9535-b0823f632565.PNG)

**Comment by lszomoru** [comment]
@TylerLeonhardt, is this something that you could assist with? Thanks!

**Comment by TylerLeonhardt** [comment]
FYI @v-mholloway

**Comment by TylerLeonhardt** [comment]
Also side note: not sure why the bot didn't assign me and csigs when it had the L10N label. Maybe because it also had the WT label? ( @JacksonKearl )

**Comment by JacksonKearl** [comment]
@TylerLeonhardt I remember discussing something regarding this but don't recall where we landed. In any case, the bot can be configured to assign folks upon a label being added like so: https://github.com/microsoft/vscode/blob/main/.github/commands.json#L68-L72. 

In default configuration it will not auto-assign based on labels, it will only auto-deduce labels (which only exist in it's head, they don't get auto-added) then auto-assign based on the mapping from the deduced label to assignee here: https://github.com/microsoft/vscode/blob/main/.github/classifier.json

**Comment by v-mholloway** [comment]
bug opened [116768](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/116768)

**Comment by v-mholloway** [comment]
bug 116768 resolved - closing
