### ISSUE TITLE
[Web] - Run only on plain text still detects other languages

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129739]
Testing #129436

Retested `"[plaintext]" : { "workbench.editor.untitled.experimentalLanguageDetection": true }` with the code snippets that were detected with the original setting. 
Still keeps detecting the languages

**Comment by TylerLeonhardt** [comment]
My suspicion is that I wasn't clear enough on what the setting actually does. It doesn't control _which languages you can switch to_ but rather _which languages you are currently in cause switches to happen_.

With that said... I really like the idea of having a way to exclude languages that the model can guess... I'll rename this issue to capture that.

**Comment by claudiaregio** [comment]
@TylerLeonhardt My bad I definitely read it as don't detect this language 😆 I thought oh that makes sense if languages are similar and maybe the detection isn't always accurate I as a user can say "Hey I am always using A, not the similar one the model keeps detecting B". 

Not sure I understand that clarification though :(

**Comment by TylerLeonhardt** [comment]
> Not sure I understand that clarification though :(

```json
"workbench.editor.untitled.experimentalLanguageDetection": true
"[markdown]" : { "workbench.editor.untitled.experimentalLanguageDetection": false }
```

Here's an example... what this says is that if I'm in an untitled markdown file, **do not** switch to another language automatically.
If I was in an untitled TypeScript file, for example, then the automatic language detection would run and I could be switched off of TypeScript to something else.

**Comment by TylerLeonhardt** [comment]
Closing this as by-design
