### ISSUE TITLE
[Web] - Plain Text not prioritized in language picker, selecting it does not make (auto) go away

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129737]
Testing #129436

After Plain Text (Auto) detected, clicking on language picker does not bring up Plain Text at the top of the language picker list, have to scroll down to see it. When you scroll down and click it, it the (Auto) does not go away

![plain text test](https://user-images.githubusercontent.com/19276747/127417762-1ca2d032-59dc-484c-8c07-cb373eed379d.gif)

**Comment by TylerLeonhardt** [comment]
I removed the `(Auto)` text yesterday. The idea being that it's not very useful to the user. [See details here](https://github.com/microsoft/vscode/issues/129601#issuecomment-888526231).

Additionally, in this case, the model isn't "guessing Plaintext" but rather it's not confident enough to think it's anything else so it stays on whatever language it's set to (in this case, plain text). Another example of this would be:

I paste in a bunch of TS, auto detect changes it to TS, then I replace that text with a tiny snippet of Python, the model isn't confident enough to know it's Python so it stays in TS until more text is added.

In light of the removal of `(Auto)`, I'll close this.
