### ISSUE TITLE
When opening up a JSON file VSCode crashes with "Error: Cannot find module"

### ISSUE THREAD

**Issue by gabloe** [microsoft/vscode#129785]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 10 21H1 (19043.1149)

Steps to Reproduce:

1. Try to open a JSON file
2. VSCode crashes with below error:
![image](https://user-images.githubusercontent.com/1381240/127534762-3db66efb-f002-40b2-8206-d93abdedea75.png)

**Comment by aeschli** [comment]
Does this reproduce with all extensions disabled?
