### ISSUE TITLE
Could not read source map for node_modules/typescript/lib/typescript.js

### ISSUE THREAD

**Issue by GaikwadPratik** [microsoft/vscode#129795]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 16.5.0
npm: 7.20.3
V8: 8.9.255.25-electron.0
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. package.json
```
{
  "name": "@salty-team/puppeteer-clearcover",
  "version": "1.0.0",
  "main": "src/index.ts",
  "scripts": {
    "start": "ts-node -T src/index.ts",
    "dev": "node -r ts-node/register/transpile-only --inspect-brk=9229 src/index.ts"
  },
  "repository": {
    "type": "git",
    "url": "******"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "chrome-aws-lambda": "^10.1.0",
    "dotenv": "^10.0.0",
    "node-fetch": "^2.6.1",
    "puppeteer-core": "^10.1.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.81",
    "@types/node-fetch": "^2.5.12",
    "@types/serverless": "^1.78.32",
    "aws-sdk": "^2.955.0",
    "prettier": "^2.2.1",
    "puppeteer": "^10.1.0",
    "serverless": "^2.18.0",
    "serverless-domain-manager": "^3.3.2",
    "serverless-offline": "^7.0.0",
    "serverless-plugin-git-variables": "^5.1.0",
    "serverless-webpack": "^5.2.0",
    "ts-loader": "^8.3.0",
    "ts-node": "^10.1.0",
    "typescript": "^4.3.5",
    "webpack": "^4.29.0",
    "webpack-node-externals": "^1.7.2"
  }
}
```
2. `launch.json`
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/src/index.ts",
      "runtimeArgs": ["-r", "ts-node/register/transpile-only"],
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ]
    }
  ]
}
```
3. press `F5` 
4. Debugger logs(generated by using `"trace": true` in `launch.json`
[vscode-debugadapter-d1b438da.json.gz](https://github.com/microsoft/vscode/files/6903035/vscode-debugadapter-d1b438da.json.gz)

**Comment by GaikwadPratik** [comment]
#106787 and #102335 didn't help since those configs are already applied

**Comment by connor4312** [comment]
This is because you configured the debugger to try to load sourcemaps for _everything_ in your workspaceFolder, including node_modules. The debugger will warn you if any of your sourcemaps are incomplete, which TypeScript's are.

If you don't want to load sourcemaps from your node_modules, you can just remove the `outFiles` you've configured. Alternately if there's some sourcemaps you do want to keep, you can add `${workspaceFolder}/node_modules/typescript/**/*.js` to your outFiles.
