### ISSUE TITLE
[Web] - Auto never goes away unless you change focus

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129741]
Testing #129436

For all setting scenarios, when a language is detected and you click the language picker and select the language, (Auto) does not go away unless you change focus to another file and come back.

**Comment by TylerLeonhardt** [comment]
I removed the `(Auto)` text yesterday. The idea being that it's not very useful to the user. [See details here](https://github.com/microsoft/vscode/issues/129601#issuecomment-888526231) but since it's gone now I'll close this.
