### ISSUE TITLE
Predefined variables are not working in VScode workspace's launch config

### ISSUE THREAD

**Issue by yasarsid** [microsoft/vscode#129752]
## Predefined variables are not working in VScode workspace's launch config

Issue Type: <b>Bug</b>

Steps to Reproduce
1. Open the project linked in VSCode
2. Navigate to debug tab, run 'run task (workspace)',
3. It throws an error
4. Similar tasks in general launch.json is succesful.

Link to [testProject ](https://github.com/yasarsid/testProject)- 

workspace.json
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {},
	"launch": {
		// Use IntelliSense to learn about possible Node.js debug attributes.
		// Hover to view descriptions of existing attributes.
		// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
		"version": "0.2.0",
		"configurations": [
		  {
			"name": "run task",
			"type": "node",
			"request": "launch",
			"program": "${FOLDER_NAME:workspaceFolder}/package3/index.js",
			"stopOnEntry": false,
			"args": [
			  "--runTestsByPath",
			  "${file}"
			]
		  }
		]
	  }
}
```

error in console
```
C:\Program Files\nodejs\node.exe ${FOLDER_NAME:workspaceFolder}/package3/index.js --runTestsByPath e:\experiments\testProject\workspace.code-workspace
Process exited with code 1
Uncaught Error: Cannot find module 'e:\experiments\testProject\${FOLDER_NAME:workspaceFolder}\package3\index.js'
```

launch.json content
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "run task",
            "program": "${workspaceFolder}/package3/index.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        }
    ]
}
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (32.97GB free)|
|Process Argv|E:\\newGitRepo\\ooui\\excel-online-core.code-workspace --crash-reporter-id 41d6f26a-c9cd-46c3-b349-0db3387fbeb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
classdiagram-ts|Ale|0.1.43
solargraph|cas|0.23.0
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
ruby|gro|0.1.0
ruby-linter|hoo|1.0.0
vscode-azdo-codereview|Mic|0.0.5
ruby-symbols|mig|0.1.8
ruby-rubocop|mis|0.8.5
azure-pipelines|ms-|1.188.1
csharp|ms-|1.23.14
remote-containers|ms-|0.187.1
azure-account|ms-|0.9.8
cpptools|ms-|1.5.1
js-debug-nightly|ms-|2021.7.2717
vsliveshare|ms-|1.0.4631
vscode-ts-uml|myx|1.0.4
ruby|reb|0.28.1
code-spell-checker|str|1.10.2
jest-snapshot-language-support|tle|1.1.1
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
`FOLDER_NAME` is simply not supported. You have to write the actual name of the folder.
There are no plans to support this as far as I know, but I can leave this open as a feature request for now.
