### ISSUE TITLE
Razor doesn't auto indent on inserting new tag

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12977]
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:

1. In a Razor file, add a tag and then press enter/return to go to next line.
2. Note that it is not auto-indented in a level like it is currently on Stable.

![insiders not indenting razor](https://cloud.githubusercontent.com/assets/11839736/18942689/7c4b18e2-85cf-11e6-93ef-5fbc6027907a.gif)

**Comment by dbaeumer** [comment]
Assigning to @sandy081  as well since @aeschli  is out.

**Comment by egamma** [comment]
@sandy081 inside an html file you get indentation 
![indent](https://cloud.githubusercontent.com/assets/172399/18967279/d14fbff4-8684-11e6-8efd-cbf74cf95869.gif)
