### ISSUE TITLE
No active document to debug when debugging two files

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#129715]
Testing #129467

<img width="1500" alt="CleanShot 2021-07-28 at 13 29 06@2x" src="https://user-images.githubusercontent.com/35271042/127391762-9d247c55-f0cf-4d6c-adcf-fc7732f01fec.png">

1. Open two notebooks
2. Start line by line on left
3. Start line by line on right
4. 🐛  notification appears

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/6868
