### ISSUE TITLE
An option to quick clone a repo to a preset temp folder or /tmp

### ISSUE THREAD

**Issue by wisammechano** [microsoft/vscode#129707]
I would like to be able to quickly skim a repo using vscode without having to select a location for where the repo should sit. Quick Clone should be feasible if the cloning happens to a temp folder.

I am developing an extension for GitHub to quickly open with vscode, so it would be cool if the feature was extended to URLs as well.

**Comment by eamodio** [comment]
Does the GitHub Repositories extension provide what you are looking for here? There is no actual clone, but you can instantly browse, search, edit, etc.
