### ISSUE TITLE
Notebook recommendation installs Jupyter only, without dependencies

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#129711]
Issue Type: <b>Bug</b>

STR:
- Opened ipynb in text editor
- Got extension recommendation for Jupyter, which I installed

![image](https://user-images.githubusercontent.com/8599/127382305-ce59c264-5cb3-4a68-86f2-45e81044269c.png)

AR: Running a cell ends in a big error dialog.
ER: Jupyter also installs Python as it depends on it.

VS Code version: Code - Insiders 1.59.0-insider (e437d424c5e6de97632f5513229c7ebc2cf27a32, 2021-07-28T05:12:37.003Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (10.46GB free)|
|Process Argv|--user-data-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/data-12-09-44 --extensions-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/ext-12-09-44 --log=trace --enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|ms-|2021.8.1074296055

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by joyceerhl** [comment]
> Jupyter also installs Python as it depends on it.

Only for Python notebooks; the Jupyter extension doesn't have Python extension declared as a dependency (and in the screenshot above there is a recommendation for Python extensions)

**Comment by roblourens** [comment]
We can't recommend Python for ipynb for the reason Joyce says, we do recommend Python (you can see it in the screenshot) but you might get the Jupyter recommendation first, it can actually be random. We can't recommend Jupyter and Python simultaneously. So I'm not sure how to improve it.

**Comment by joyceerhl** [comment]
The experience proposed in https://github.com/microsoft/vscode/issues/128592 should cover getting started for Jupyter notebooks, specifically

> Include a "Find More Kernels" option in the Kernel quick pick that goes to the marketplace
Also include a "Find more languages" option that goes to the marketplace

**Comment by roblourens** [comment]
Yeah I think it makes sense to just call this part of that
