### ISSUE TITLE
newWithProfile keybinding with custom profile shows warning

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#129798]
Looking at #126738

when I use a custom profile name from my settings, I get a warning on the keybinding saying that the profileName is not allowed

```json
    "terminal.integrated.profiles.osx": {
        "myprofile": {
            "path": "bash",
            "args": [
                "-l"
            ]
        }
    }
```

![image](https://user-images.githubusercontent.com/323878/127555416-4901803a-5f7e-4934-884f-36d28ac5440c.png)

**Comment by Tyriar** [comment]
Think this was fixed some time ago, cannot repro anymore.
