### ISSUE TITLE
vscode 1.58.2  unable to input chinese character but 1.57.* is ok

### ISSUE THREAD

**Issue by sharkka** [microsoft/vscode#129759]
VSCode version: 1.58.2
Start vscode as user(not root)
Switch to chinese input
Typing chinese is not working
But 1.57.* version works fine,
And reinstall fcitx-googlepinyin, not work.

**Comment by sharkka** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [unable to input chinese character (#96041)](https://www.github.com/microsoft/vscode/issues/96041)
> * [VSCode do not support chinese input method. (#112856)](https://www.github.com/microsoft/vscode/issues/112856)
> * [终端不能输入中文 (#118092)](https://www.github.com/microsoft/vscode/issues/118092)

Maybe it is not the same issue
And, I also install vscode by snap, and I try to modify settings.json, clear all confiration in settings.json, and restart vscode, not work.

**Comment by rebornix** [comment]
@Tyriar it looks like an issue with snap? can you help confirm?

**Comment by sharkka** [comment]
I removed vscode 1.58.2, installed by snap again, problem still exists.

**Comment by sharkka** [comment]
I removed vscode 1.58.2, installed by snap again, problem still exists.
