### ISSUE TITLE
Fallback to word highlighting when contributions don't provide document highlights

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12973]
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test plan item #12100

Steps to Reproduce:
1. May not be a problem, but just filing this issue to be safe.  I'm looking at an old version of VS Code site that was originally written in Razor.  It's the `example-word-count.cshtml` file https://github.com/Microsoft/vscode-website/tree/3cfa8213681f680418997c7671fa1b8c452ac2af
2. Try clicking on the class name `updateWordCount` pictured below on line 79 and note that it doesn't match the symbol with a highlight like it does in Stable today as shown in the picture.

**Left is Insiders.  Right is Stable.**
<img width="1440" alt="screen shot 2016-09-28 at 10 48 18 pm" src="https://cloud.githubusercontent.com/assets/11839736/18942458/113a46aa-85ce-11e6-93b1-f95d7c3c8a33.png">

**Comment by dbaeumer** [comment]
Word highlight is broken in CSHTML. Not sure if this should be the normal word highlight or whether this is a language word highlighter.

**Comment by sandy081** [comment]
I see word highlighting is broken for HTML, CSHTML and HandleBars

Since, HTML has been extracted into a separate language server and this functionality has been lost. Moving to October.

This has to be documented as limitation in release notes

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode/issues/1751?

**Comment by aeschli** [comment]
The html extension registers a document highlighter provider. This seems to prevent the default word highlighting. The same seems to happen in TypeScript: Select a word in a comment does not highlight it.

**Comment by jrieken** [comment]
It seems like that was done on purpose by @alexandrudima - see: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findController.ts#L814

Waiting for him to comment

**Comment by jrieken** [comment]
Not really sure what you mean @aeschli. Yes, we have no more nested modes and lost smart highlight for embedded languages, the rest is driven by the word def, or by the implementation your extension implements.

**Comment by aeschli** [comment]
I verified that my word regex is now correct. As you observed in your comment above (https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findController.ts#L814), word highlighting is skipped if there is a highlight provider.
IMO word highlighting should not be skipped if none of the highlight providers has any results.

**Comment by alexandrudima** [comment]
Yes, this must be fixed by the DocumentHighlightProvider aka the HTML extension. 

The principle is very simple: if there is a **semantic** highlighter, do not do a **stupid** selection highlight

@aeschli The same was happening before, the html worker used to have code in place to fall back to word highlighting.

**Comment by aeschli** [comment]
@alexandrudima So I'd reimplement what the default (aka stupid) word highlighter does in the html extension. And if there's another extension that adds a smarter highlighter provider that also has some highlighting for the words I don't support, that will conflict with the 'stupid' ones the HTML extension would provide.
IMO it would be better if the default behaviour is done by VSCode:
If no provider gives any result on a given empty selection, then provide a default highlight.

**Comment by alexandrudima** [comment]
@aeschli Please do as you wish, as far as I'm concerned you are free to take ownership of `SelectionHighlighter` and `WordHighlighter`, and issues associated with them.

**Comment by aeschli** [comment]
It was a behaviour change, but we haven't had many complaints about it since then.
Changing to 'feature-request'

**Comment by aeschli** [comment]
Closing as there have been no complaints about the new behaviour.
