### ISSUE TITLE
VSCode runs slow when connected to personal hotspot

### ISSUE THREAD

**Issue by Jakub1310** [microsoft/vscode#129799]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: 11.5.1 (20G80)

Steps to Reproduce:

1. Connect VSCode to a 'slower' (I noticed that this issue occurred when I was connected to 3G instead of 5G). When attempting to debug the debugger was awfully slow to start. 
2. Disconnect the Mac from network and the debugger starts normally. 

I think its important to note that this issue occurred on an Apple Silicon Mac which usually starts the debugger fast.

**Comment by weinand** [comment]
what debugger are you using?

**Comment by Jakub1310** [comment]
Hey Andre,

Sorry for the very slow reply. I am using the ordinary VSCode Python debugger.
