### ISSUE TITLE
Notebook toolbar improvement with label hidden

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129728]
We added a setting to hide the label of actions in the notebook toolbar. It saves spaces on the toolbar but since there is no label anymore, the icons are not intuitive enough, for example

* Unclear if `+` inserts code ormarkdown
* Unclear if the Run button run all cells or the active cell
* Unclear if the Clear button clear all cell outputs or only outputs of the active cell

To improve this we can probably introduce submenu for them:

* Insert button, has a sub menu of Insert Code and Markdown (not sure if we want to have actions like `Insert ${LAN}` , LAN is from supported languages)
* Run button on the toolbar will run the active cell, it will have a sub menu, under which there is a Run all, and maybe debug
* Clear button will clear the output of the active cell, it will have a sub menu, under which there is Clear All Outputs

**Comment by rchiodo** [comment]
Not sure I'd want a submenu. I think tooltips are the expected way to understand what a button does. Although a submenu doesn't make the button any less useful so maybe it doesn't matter.
