### ISSUE TITLE
[Web] - Python not detected most times, when detected (auto) did not go away

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129731]
Testing #129436

Used the recommended website: https://www.programiz.com/python-programming/examples
Really hard to get Python detected, strong majority of time it remains as Plain Text (Auto) I must have tried about 20 on the site and only got 2 that were detected correctly. 

🔴 Did not work 
🟢 Worked

🟢 https://www.programiz.com/python-programming/examples/prime-number 
🟢 https://www.programiz.com/python-programming/examples/type-vs-instance 
🔴 https://www.programiz.com/python-programming/examples/represent-enum 
🔴 https://www.programiz.com/python-programming/examples/area-triangle 
🔴 https://www.programiz.com/python-programming/examples/factor-number
🔴 https://www.programiz.com/python-programming/examples/positive-negative-zero
🔴 https://www.programiz.com/python-programming/examples/factorial

For the two that were detected correctly, when I clicked the language picker and selected the language, (auto) did not go away.

**Comment by TylerLeonhardt** [comment]
Thanks for this! Another great case for https://github.com/microsoft/vscode/issues/129596

cc @yoeo for an FYI
