### ISSUE TITLE
vscode dosn't open on linux

### ISSUE THREAD

**Issue by d-shiri** [microsoft/vscode#129761]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 70
- OS Version: Linux 5.10.53-1-MANJARO #1 SMP PREEMPT Mon Jul 26 07:18:28 UTC 2021 x86_64 GNU/Linux

Steps to Reproduce:

1. code 
gives the following error, so does --verbose and code --disable-extensions
`2021/07/29 11:12:45.092228 system_key.go:129: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 1
/var/lib/snapd/snap/code/70/command-code.wrapper: line 2: /snap/code/70/electron-launch: No such file or directory

**Comment by Evpok** [comment]
I am also affected and also on Manjaro, but I only get the last error line 

```
/var/lib/snapd/snap/code-insiders/774/command-code-insiders.wrapper: line 2: /snap/code-insiders/774/electron-launch: No such file or directory
```

**Comment by d-shiri** [comment]
> I am also affected and also on Manjaro, but I only get the last error line
> 
> ```
> /var/lib/snapd/snap/code-insiders/774/command-code-insiders.wrapper: line 2: /snap/code-insiders/774/electron-launch: No such file or directory
> ```

ok after half a day wasted on this stupid problem here's what you can do:
1. https://askubuntu.com/questions/1198384/how-to-reinstall-a-snap-package
if you get:
```
error: cannot install "code": classic confinement requires snaps under /snap or
       symlink from /snap to /var/lib/snapd/snap
```

2. do the following and then go back to 1.
https://snapcraft.io/install/code/manjaro

**Comment by carloschameleon** [comment]
You can either fix this by creating a symlink

`sudo ln -s /var/lib/snapd/snap /snap`

Source: https://snapcraft.io/install/code/manjaro#snippet-distro-install-command-4

**Comment by JoseVale99** [comment]
a solution is putting the following command in your terminal:
1.- sudo snap remove code
2. restart your computer
3.- sudo ln -s / var / lib / snapd / snap / snap
4.- sudo snap install code --classic
It worked for me in manjaro 😁!
