### ISSUE TITLE
Step back in Debugging

### ISSUE THREAD

**Issue by tanmayck1201** [microsoft/vscode#129782]
Issue Type: <b>Feature Request</b>

There is no step back feature present for c/c++ debugger in vs code. 
As per my searching, i didn't found any relative thing. it's there in visual studio enterprise edition but not in vs code 2021. 
It'll be great if there could be this feature, will help to debug the programs more conviniently.
Thank you. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by tanmayck1201** [comment]
Imp Issue/Requirement

**Comment by weinand** [comment]
VS Code supports "step back" in the UI. But debug extension have to implement this functionality. Please file this request against the debug extension you are using.
