### ISSUE TITLE
Still Try Connect Network When Start Python Even Network is down

### ISSUE THREAD

**Issue by lzj347641801** [microsoft/vscode#129757]
When use F5 to run python in VScode, it will try to connect  13.67.9.5:443 and 40.77.226.250:443 even the network 
is change to my corpnet, and  it will wait till timeout which caused great latency.

You can reproduct it use 360 to monitor the instant network connection of VSCode

**Comment by MihailCosmin** [comment]
I experience the same issue. 

Strange thing is, if I try to access https://code.visualstudio.com/ on my corporate wifi I get ERR_CONNECTION_CLOSED
But if I try to access the same website using my mobile data.... it connects. 
Why does microsoft know which IPs come from corporate wifi and which not?
This is some conspiracy shit right here....
