### ISSUE TITLE
Replace(ctrl+h) does not working in notebook

### ISSUE THREAD

**Issue by ZZZZzzzzac** [microsoft/vscode#129781]
## Environment data
VS Code version: 1.58.2 (user setup)
commit: c3f126316369cd610563c75b1b1725e0679adfb3
date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   Python and/or Anaconda version: 3.9.5 64bit
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

in jupyter notebook file, replace (ctrl+h) should work properly

## Actual behaviour

using replace (from ctrl+h or from menu bar) to open replace window, cannot find or replace code.
![replace](https://user-images.githubusercontent.com/17446384/127453392-3a489f5d-bd16-4020-a5ed-3f8e6c7cdf6e.gif)

find (ctrl+f) works fine, and click the down arrow to expand menu, it can replace code properly
![find](https://user-images.githubusercontent.com/17446384/127453408-6d4b2e78-b8e9-4e54-ae8f-b9ba8fedc664.gif)

## Steps to reproduce:
as above

**Comment by ZZZZzzzzac** [comment]
and I find that find (ctrl+f) is also bugged, shown below
![find_cache_wrong](https://user-images.githubusercontent.com/17446384/127629985-1676c45c-e771-4b66-bf4f-c38997b2d2cb.gif)

**Comment by rebornix** [comment]
Both two cases should be fixed now.
