### ISSUE TITLE
When debugging variables take up to two minutes to populate after hitting the breakpoint

### ISSUE THREAD

**Issue by rfmneves** [microsoft/vscode#129755]
Issue Type: <b>Bug</b>

Debugging our source code (haxe / js + sourcemaps) with versions after 1.56.2, takes up to two minutos or more to show the variables after hitting the breakpoint. Windows machines are not affected by this, only mac. We even tried different mac os versions and the new debugger but it didn't work. We had to revert to 1.56.2 which works as always by showing the variable values right after hitting the breakpoint.
TLDR, we expect variable values to show up right after hitting the breakpoint but it doesn't happen with versions after 1.56.2

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 4a9816ab-fc9d-4031-845c-4cc0ce44bd03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
chronicler|arc|0.1.14
vscode-nextgenas|bow|1.7.1
vscode-swf-debug|bow|1.3.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
json-tools|eri|1.0.2
php-intellisense|fel|2.3.14
code-runner|for|0.11.5
ocaml|hac|0.6.44
haxe-hl|Hax|1.1.2
vscode-test-explorer|hbe|2.20.4
lix|lix|1.3.0
ftp-sync|luk|0.3.9
test-adapter-converter|ms-|0.0.10
debugger-for-chrome|msj|4.12.12
vshaxe|nad|2.23.2
vscode-opened-editors|Nic|0.0.8
foe-boy-scout|ric|0.0.7
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
haxe-checkstyle|vsh|1.7.0
haxe-debug|vsh|1.2.3
haxe-extension-pack|vsh|1.3.0
haxe-test-adapter|vsh|1.2.10
hxcpp-debugger|vsh|1.2.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805:30301674
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by connor4312** [comment]
Also note that you're a month behind on VS Code, the latest stable release is 1.58. Updating may resolve your issue.

**Comment by rfmneves** [comment]
Sorry for late reply, I had a vacation day. Didn't noticed there was a new update after 1.57.1 as I was welcomed with the update itself. I just thought it was the last. Today I forced the update to 1.58.2 and tested it again. The issue does not happen in the latest version. It just show the variables right after hitting the breakpoint so you can either close the issue or if you want, I can roll back and test with the trace if you want to dig deeper. Thanks for the help
