### ISSUE TITLE
Terminal scroll position is messed up when dragged from panel to editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129712]
![recording (48)](https://user-images.githubusercontent.com/2193314/127385325-e9c716c7-bbf8-46cd-8f0c-8cf19a89b1f6.gif)

**Comment by meganrogge** [comment]
Because there is no scroll bar, that looks kind of bad and could be confusing IMO for beginners. Though beginners probably aren't using terminals in the editor area 😆

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @meganrogge ,

I'm ready to work on this, if help is needed. 

Any guides?

**Comment by benrkia** [comment]
I'm not able to reproduce, i have version 1.58.2 on Darwin x64 18.6.0

**Comment by allenjohnson8** [comment]
Hi, from what I can understand the problem here is that the terminal edit position should be at the end rather than at the top. Your feedback is appreciated

**Comment by popGitpop** [comment]
i don't know what you say and why i write these words

**Comment by meganrogge** [comment]
I can't repro this
