### ISSUE TITLE
Intellisense in keybinding args without schema gives quick pick of every string in the product

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#129786]
Testing #129429

Not really a critical bug but definitely a bit odd...

![image](https://user-images.githubusercontent.com/8586769/127539331-f2075fd1-8fb6-48dd-82e5-5e0695272830.png)
![image](https://user-images.githubusercontent.com/8586769/127539382-89f7c432-c966-471f-8329-974671a7a70e.png)
![image](https://user-images.githubusercontent.com/8586769/127539434-e5eb0b72-19af-452f-810e-8b50788362f8.png)

**Comment by jrieken** [comment]
JSON as a "special" definition for what a word is (basically tokens) and that's the consequence

**Comment by jrieken** [comment]
fyi @aeschli
