### ISSUE TITLE
Vertically center walkthrough Markdown content

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#129733]
I think vertically centering walkthrough Markdown content would improve the look quite a bit.

## Actual
Here is what Markdown content currently looks like in walkthroughs:

![image](https://user-images.githubusercontent.com/12476526/127416393-cea2042f-641d-4cec-9b0c-910b8b3ab442.png)

## Expected
Here is what I would like it to look like (I faked this by adding \<br\> tags):

![image](https://user-images.githubusercontent.com/12476526/127416567-9528cb21-8eb2-4be3-8482-7c157eccc0b0.png)

**Comment by misolori** [comment]
Also saw this in the Python extension, the markdown rendering also has font sizes that are larger than the content on the left so it throws off the hierarchy:

<img width="1614" alt="CleanShot 2021-09-13 at 10 14 35@2x" src="https://user-images.githubusercontent.com/35271042/133127945-5b5ecbf4-214d-48c5-a881-79d1547e8a46.png">

**Comment by misolori** [comment]
Looks good 👏 

<img width="1024" alt="CleanShot 2021-11-09 at 10 23 41@2x" src="https://user-images.githubusercontent.com/35271042/140982388-6494e831-50a5-477d-9457-9a8506075d30.png">
