### ISSUE TITLE
Extension page disabled message is wrapped

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#129725]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: VS Code Codespaces
- OS Version: Linux

Steps to Reproduce:

1. Open a Codespace
2. Disable an extension
3. 🐛 The 'This extension is disabled globally by the user.' message is wrapped and truncated. This is not a problem in desktop VS Code
![image](https://user-images.githubusercontent.com/30305945/127406260-0477d618-1636-4042-ba27-d9654827808e.png)

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/127468502-f91bc7c0-b7d7-4736-a9d1-275e2a454e0a.png)


Moving this to codespaces as the splash screen from them is overriding the style.
