### ISSUE TITLE
TSC Compiler not matched VS language service.

### ISSUE THREAD

**Issue by SiriusGuo** [Microsoft/vscode#12974]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1. Install typescript of last release.
2. restart vscode

![image](https://cloud.githubusercontent.com/assets/6395714/18942548/5a8a11b8-864c-11e6-852a-9c3be3080de6.png)
---------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/6395714/18942558/70c5dc82-864c-11e6-9715-7bed4c3182d6.png)
---------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/6395714/18942568/7e631de6-864c-11e6-9148-f7d9d94d58e7.png)

**Comment by dbaeumer** [comment]
@SiriusGuo this is by design. VS Code 1.5.3 ships with TS 1.8.10. If you install TS globally you now get TS 2.0.3. This can lead to problem inconsistency if you use scripts that use the global tsc compiler in that workspace. This is why we show the message. VS Code 1.6 will ship with TS 2.0.3.
