### ISSUE TITLE
Notebook diff UI needs some sort of cell indicator

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129783]
Notebook diff seems off to me. I find it hard to tell where cells begin and end:

![image](https://user-images.githubusercontent.com/19672699/127533901-6677e0af-29e4-4004-95db-a54fdde281e9.png)

Perhaps we can include the execution count?

**Comment by roblourens** [comment]
I think it needs the new cell editor background?

**Comment by claudiaregio** [comment]
+1 Rob's suggestion, I think the cell background could help the homogenous look here the same way it helped the original notebook

**Comment by rebornix** [comment]
Make sense, we can use the cell editor background from notebook.
