### ISSUE TITLE
Native Notebooks - Different behavior between click run and shift + enter run

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129713]
- VS Code Version: 1.59.0-insiders
- OS Version: Windows 10 

Steps to Reproduce:

1. Create cell with output
2. Run using icon to left -- nothing moves 
3. Run cell again using shift enter -- cell jumps up a bit 

*Note: This does not occur with ctrl+enter, just shift+enter

![shortcut run scroll](https://user-images.githubusercontent.com/19276747/127387753-499ddb00-10b2-4a9d-8434-844edb147ba5.gif)

**Comment by roblourens** [comment]
I was debugging this recently and it's that we show the second cell, then add the output to the first cell, and we try to maintain the scroll position of the focused cell when inserting output above. Which I think is the right logic, but when it happens fast, it feels crappy. If you make the output show up slower, then I think it makes sense because you don't want the focused cell to move around. So I don't know how to improve it.

**Comment by claudiaregio** [comment]
I would expect to see a shift if the cells were running off the screen but if there is space for both cells and output as I continue to write code and hit shift enter nothing should move. Below for reference

![shift enter jup](https://user-images.githubusercontent.com/19276747/127550638-b38b0117-077e-4e74-84e2-031f8204f252.gif)

**Comment by roblourens** [comment]
We can try that but I find this really annoying that it moves my cursor around on the page

**Comment by claudiaregio** [comment]
@roblourens What do you mean moves cursor around the page? I can take a look at telemetry to see what is more common 

FWIW if the cell takes longer to run Jupyter does the following on shift enter. Shows kernel as running, puts in command mode and then inserts the output
![shift enter jup2](https://user-images.githubusercontent.com/19276747/127560761-e39e789a-6db9-44ce-8dad-bbb6145a7908.gif)

**Comment by roblourens** [comment]
> puts in command mode

Maybe this is the key, I thought the point is that the editor has focus so you can type in the cell you just created. We put focus in the cell editor I think. If you aren't actually using the next cell then my gripe about moving the cursor doesn't matter, and we shouldn't try to maintain the position of the active cell.

**Comment by greazer** [comment]
I'm not reproing this anymore with the latest bits from today. Behavior seems identical to that of Jupyter.
