### ISSUE TITLE
Stopping an extension debug session doesn't close the Extension Development Host

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#129702]
https://user-images.githubusercontent.com/323878/127360861-0f59bdf6-3c51-4a21-a24f-145e6fd387ad.mp4

**Comment by isidorn** [comment]
I can reproduce. This seems to work with stable -> regression.
Investigating...

fyi @weinand

**Comment by weinand** [comment]
@isidorn No, I haven't touched anything in VS Code (other than the new split button).
But I was going to report the same issue because I was seeing this problem with Mock Debug every day 10 times ...

**Comment by isidorn** [comment]
Let's close as a duplicate and does not seem to be a regression and we can investigate more in debt week
