### ISSUE TITLE
Vscode asks to login in to github even after logging in

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [microsoft/vscode#129748]
Issue Type: <b>Bug</b>

After the latest update, it seems like every time I load VSCode window, it asks me to log in to github by opening a white box asking for token or opening browser to login. I clicked on logging through browser and I did it without any problem. I also tried logging with token but the issue still remains.

I have many extensions that controls git and I tried installing, reinstalling, and removing all of them and tried reloading VSCode window again and again. The github login window still opens 3 times every time I login.

I tried reinstalling to make sure but same issue still remains.

Please fix this issue as soon as you can. It is very annoying to close the window every time I am loading VSCode.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (10.02GB free)|
|Process Argv|--crash-reporter-id 46bb00f5-c604-4fc3-959e-71ec44573cde|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.3.0
converttoasciiart|Bit|1.0.3
exe-runner|bra|0.2.1
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
git-extension-pack|don|0.1.3
githistory|don|0.6.17
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
git-project-manager|fel|1.7.1
code-runner|for|0.11.5
todo-tree|Gru|0.0.213
asciidecorator|hel|0.2.0
beautify|Hoo|1.5.0
git-graph|mhu|1.30.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4631
vscode-react-native|msj|1.5.2
material-icon-theme|PKi|4.8.0
box-comment|Pol|0.1.2
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
markdown-editor|zaa|0.1.10
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by HyunseungLee-Travis** [comment]
The two existing bugs/issues is different.

**Comment by abdlrhmanshehatamoussa** [comment]
Hi @eamodio

I'm ready to work on this if there is any help wnanted.

Just guide me through and I'll goo

Best of luck

**Comment by eamodio** [comment]
Does it still happen if you run vscode with `--disable-extensions`?
