### ISSUE TITLE
Docked debug toolbar doesn't show the new Inspect button

### ISSUE THREAD

**Issue by tanguyMichardiere** [microsoft/vscode#129765]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Darwin arm64 20.6.0

Steps to Reproduce:

1. Debug a frontend project (React in my case)
2. Set "debug.toolBarLocation": "docked"

The new "Inspect" button which launches the Edge Developer Tools inside VS Code doesn't appear in the toolbar when it's docked. It appears when it's floating. It doesn't appear even if I make the side bar larger.

**Comment by isidorn** [comment]
Dup of issue created by @DanTup

**Comment by DanTup** [comment]
(for reference, https://github.com/microsoft/vscode/issues/115945 is the other issue)
