### ISSUE TITLE
Misalignments in official website.

### ISSUE THREAD

**Issue by code-reaper08** [microsoft/vscode#129700]
### Sorry for a blank template 😅

I've found some simple misalignments on the official website [here](https://code.visualstudio.com/). I searched for the `report bug` option and it's not available on the official website.

Could anyone help me how to take this issue forward?

Thanks in advance 😄

**Comment by meganrogge** [comment]
Hi, you can report a vscode-docs bug here https://github.com/microsoft/vscode-docs/issues
