### ISSUE TITLE
vs code doesn't connect to the internet

### ISSUE THREAD

**Issue by sercus** [microsoft/vscode#129773]
Does this issue occur when all extensions are disabled?: Yes (Can't open the extensions so yes)

- VS Code Version: 1.58.0
- OS Version: Linux x64 5.13.5-arch1-1

I recently installed vs code in my laptop but for some reason I can't connect to the internet, the marketplace doesn't work and neither the log in. In the console I see  5 errors:

1 - Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.

2 - [Extension Host] (node:14711) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron --trace-deprecation ...` to show where the warning was created)
 
3 - Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

4 - Error querying extensions gallery XHR failed

5 - "Failed to load resource: net::ERR_FAILED" and the this link "https://open-vsx.org/vscode/gallery/extensionquery".

Hope somebody can at least tell me where or what to search for.

**Comment by yonghie** [comment]
same problem there

**Comment by gjsjohnmurray** [comment]
You are running a build that tries to use Open VSX for extensions instead of marketplace.visualstudio.com

/duplicate
