### ISSUE TITLE
terminal.integrated.fontSize cannot be set as large as editor.fontSize

### ISSUE THREAD

**Issue by seraku24** [microsoft/vscode#129766]
Issue Type: <b>Bug</b>

To address #37455, Code implemented an arbitrary maximum on the terminal font size. This limit is overly restrictive when Code is being used as a presentational tool. Font size needs to be quite large to be readable at distance, and the current maximum makes it impossible to scale the terminal to match the editor.

The only workaround I have found is to adjust the font size as large as it can be and then make up the difference using `window.zoomLevel`. This has a major drawback in that the entire UI is affected by the zoom level. Enlarging all elements reduces the available space for text, resulting in a somewhat cramped and cluttered view of the content.

VS Code version: Code - Insiders 1.59.0-insider (50b3811fdc5b5c80ca516a2edfffedcbd464b033, 2021-07-15T05:13:58.348Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.37GB free)|
|Process Argv|--crash-reporter-id aad1c5c9-d96d-4ded-b865-f0c766cf74a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by seraku24** [comment]
Just following up on this. Near as I can tell, the editor does not enforce a maximum font size—perhaps it did so in the past as alluded to in #37455. But it seems odd the terminal would need to be special in this regard. Is there any context I am overlooking that supports limiting font size?

**Comment by meganrogge** [comment]
add validation and max of 100
