### ISSUE TITLE
Dragging a tab doesn't re-evaluate the active terminal indicator

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#129776]
Repro:

1. Set `"terminal.integrated.tabs.showActiveTerminal": "always"`
1. Open a terminal (or run a task)
2. Open another
3. Drag the second one to the top and to the bottom, notice the active terminal in the list doesn't always match the single tab at the top

Watch is the active one below but the active terminal border is not showing it:

![image](https://user-images.githubusercontent.com/2193314/127525713-b424f9ec-b502-476a-9b41-8188c71be560.png)

I think it's to do with the active group index not getting updated. This is probably an easy fix for July.

**Comment by meganrogge** [comment]
this is the same as https://github.com/microsoft/vscode/issues/128301
