### ISSUE TITLE
Invisible Minimap clickable part

### ISSUE THREAD

**Issue by begrs** [microsoft/vscode#129756]
Issue Type: <b>Bug</b>

- Open a code file with long lines of text so that the drop shadow of the code minimap appears.
- Click at the end of the line, around 5px before the visible shadow appears.

Expected result: cursor is placed in the long line of text at the clicked position. 
Actual Result: page scrolls down, because the dropshadow extends invisibly a few pixels you click the minimap unintentionally.

Possible solution: make the dropshadow not clickable at all or click through if possible. It would even be preferable to not register any click there, since then one can easily scroll to the right and click again, because the current position in code is not lost as it is now.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

Extension|Author (truncated)|Version
---|---|---
voice-comments|4a1|0.2.3
vscode-sqlite|ale|0.13.0
vscode-angular2-files|ale|1.6.4
nugetpackagemanagergui|ali|1.1.6
ng-template|Ang|12.1.3
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
githistory|don|0.6.17
tsl-problem-matcher|eam|0.4.0
vscode-html-css|ecm|1.10.2
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|8.1.0
git-project-manager|fel|1.7.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
vscode-csharp-snippets|jor|1.1.0
csharpextensions|kre|1.4.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
powershell|ms-|2021.6.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.8.0
nuget-extensions-vscode|ran|0.1.2
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
</details>

**Comment by alexdima** [comment]
@begrs Could you please post also a screenshot with maybe an arrow that highlights the problematic click area?

**Comment by begrs** [comment]
![image](https://user-images.githubusercontent.com/10938362/132202917-d1690c77-847a-4416-80c3-2324540a554f.png)

Clicking the letters "in" in the first line, "te" in the second line and "o" in the last line scrolls to the end of the page instead of allowing edit there.
