### ISSUE TITLE
Adding a div causes an extra stray bracket in Razor

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#12975]
- VSCode Version: Insiders
- OS Version: Windows 10

Regarding test item #12100 

Steps to Reproduce:

1. Type `<div` and press Tab repeatedly until it completes to `<div></div>>`
2. Note the extra `>` at the end that was not there before

Insiders pictured below
![insiders - extra closing bracket](https://cloud.githubusercontent.com/assets/11839736/18942587/eb4dea9a-85ce-11e6-9639-95b35e2e7f47.g

In Stable today, there is no extra bracket.

**Comment by dbaeumer** [comment]
This is emmet related.

**Comment by egamma** [comment]
This isn't a regression. What has changed in September is that `<` is now auto closed with '>'. This uncovers the emmet behaviour.

As an initial fix I've removed the auto closing of '<', this makes the behaviour consistent with August.

**Comment by egamma** [comment]
Also change the emmet editor access to consume a trailing '>'

**Comment by egamma** [comment]
@dbaeumer pls verify
