### ISSUE TITLE
Notebooks: CTRL+F matching partials

### ISSUE THREAD

**Issue by bwsyn** [microsoft/vscode#129723]
Issue Type: <b>Bug</b>

.ipynb with python and markdown cells

cells contain pandas code, e.g. df['Metaproperty Option']

when I search tags in the CTRL + F, I match partials. e.g. 'ta' in 'Metapropety Option'

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by rebornix** [comment]
This bug should already be fixed.
