### ISSUE TITLE
can't connect to marketplace

### ISSUE THREAD

**Issue by icepirrin** [microsoft/vscode#129768]
Console output:

electron/js2c/renderer_init.js:113 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ electron/js2c/renderer_init.js:113
workbench.desktop.main.js:62 [Extension Host] (node:2757) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `electron --trace-deprecation ...` to show where the warning was created)
m @ workbench.desktop.main.js:62
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
open-vsx.org/vscode/gallery/extensionquery:1 Failed to load resource: net::ERR_FAILED
workbench.desktop.main.js:627   ERR XHR failed: Error: XHR failed
    at XMLHttpRequest.w.onerror (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:76:24456)
workbench.desktop.main.js:2835 Error querying extensions gallery Canceled
query @ workbench.desktop.main.js:2835
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
workbench.desktop.main.js:2835 Error querying extensions gallery XHR failed
query @ workbench.desktop.main.js:2835
open-vsx.org/vscode/gallery/extensionquery:1 Failed to load resource: net::ERR_FAILED
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
workbench.desktop.main.js:627   ERR Error: XHR failed
    at XMLHttpRequest.w.onerror (workbench.desktop.main.js:76)
open-vsx.org/vscode/gallery/extensionquery:1 Failed to load resource: net::ERR_FAILED
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
workbench.desktop.main.js:2835 Error querying extensions gallery XHR failed
query @ workbench.desktop.main.js:2835
open-vsx.org/vscode/gallery/extensionquery:1 Failed to load resource: net::ERR_FAILED
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
workbench.desktop.main.js:2835 Error querying extensions gallery XHR failed
query @ workbench.desktop.main.js:2835
async function (async)
query @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
y @ workbench.desktop.main.js:68
show @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
doSearch @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:68
Promise.then (async)
trigger @ workbench.desktop.main.js:68
triggerSearch @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:2110
(anonymous) @ workbench.desktop.main.js:580
fire @ workbench.desktop.main.js:60
endDeferredEmit @ workbench.desktop.main.js:589
pushEditOperations @ workbench.desktop.main.js:587
_innerExecuteCommands @ workbench.desktop.main.js:617
executeCommands @ workbench.desktop.main.js:617
_executeEditOperation @ workbench.desktop.main.js:616
(anonymous) @ workbench.desktop.main.js:617
_executeEdit @ workbench.desktop.main.js:617
executeCommands @ workbench.desktop.main.js:617
(anonymous) @ workbench.desktop.main.js:618
_withViewEventsCollector @ workbench.desktop.main.js:618
_executeCursorEdit @ workbench.desktop.main.js:618
executeCommands @ workbench.desktop.main.js:618
executeCommands @ workbench.desktop.main.js:654
runCoreEditingCommand @ workbench.desktop.main.js:652
runEditorCommand @ workbench.desktop.main.js:652
(anonymous) @ workbench.desktop.main.js:652
invokeFunction @ workbench.desktop.main.js:625
invokeWithinContext @ workbench.desktop.main.js:652
runCommand @ workbench.desktop.main.js:652
handler @ workbench.desktop.main.js:652
invokeFunction @ workbench.desktop.main.js:625
_tryExecuteCommand @ workbench.desktop.main.js:1678
(anonymous) @ workbench.desktop.main.js:1678
Promise.then (async)
executeCommand @ workbench.desktop.main.js:1678
_doDispatch @ workbench.desktop.main.js:627
_dispatch @ workbench.desktop.main.js:627
(anonymous) @ workbench.desktop.main.js:1705
workbench.desktop.main.js:76 POST https://open-vsx.org/vscode/gallery/extensionquery net::ERR_FAILED
(anonymous) @ workbench.desktop.main.js:76
A @ workbench.desktop.main.js:76
request @ workbench.desktop.main.js:634
queryGallery @ workbench.desktop.main.js:639
async function (async)
queryGallery @ workbench.desktop.main.js:639
query @ workbench.desktop.main.js:639
(anonymous) @ workbench.desktop.main.js:2839
Promise.then (async)
queryGallery @ workbench.desktop.main.js:2839
queryGallery @ workbench.desktop.main.js:2835
async function (async)
queryGallery @ workbench.desktop.main.js:2835
query @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
y @ workbench.desktop.main.js:68
show @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
doSearch @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:68
Promise.then (async)
trigger @ workbench.desktop.main.js:68
triggerSearch @ workbench.desktop.main.js:2835
(anonymous) @ workbench.desktop.main.js:2835
fire @ workbench.desktop.main.js:60
(anonymous) @ workbench.desktop.main.js:2110
(anonymous) @ workbench.desktop.main.js:580
fire @ workbench.desktop.main.js:60
endDeferredEmit @ workbench.desktop.main.js:589
pushEditOperations @ workbench.desktop.main.js:587
_innerExecuteCommands @ workbench.desktop.main.js:617
executeCommands @ workbench.desktop.main.js:617
_executeEditOperation @ workbench.desktop.main.js:616
(anonymous) @ workbench.desktop.main.js:617
_executeEdit @ workbench.desktop.main.js:617
executeCommands @ workbench.desktop.main.js:617
(anonymous) @ workbench.desktop.main.js:618
_withViewEventsCollector @ workbench.desktop.main.js:618
_executeCursorEdit @ workbench.desktop.main.js:618
executeCommands @ workbench.desktop.main.js:618
executeCommands @ workbench.desktop.main.js:654
runCoreEditingCommand @ workbench.desktop.main.js:652
runEditorCommand @ workbench.desktop.main.js:652
(anonymous) @ workbench.desktop.main.js:652
invokeFunction @ workbench.desktop.main.js:625
invokeWithinContext @ workbench.desktop.main.js:652
runCommand @ workbench.desktop.main.js:652
handler @ workbench.desktop.main.js:652
invokeFunction @ workbench.desktop.main.js:625
_tryExecuteCommand @ workbench.desktop.main.js:1678
(anonymous) @ workbench.desktop.main.js:1678
Promise.then (async)
executeCommand @ workbench.desktop.main.js:1678
_doDispatch @ workbench.desktop.main.js:627
_dispatch @ workbench.desktop.main.js:627
(anonymous) @ workbench.desktop.main.js:1705
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/2d23c42a936db1c7b3b06f918cde29561cc47cd6/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

**Comment by gjsjohnmurray** [comment]
/duplicate Your version of VS Code has been built to use Open VSX instead of Microsoft's Marketplace.
