### ISSUE TITLE
Memory leak when trying to plot using pandas scatter_matrix

### ISSUE THREAD

**Issue by scsleal** [microsoft/vscode#129738]
## Steps to reproduce

Copy, paste and run the following code in a cell:

```
import pandas as pd
from pandas.plotting import scatter_matrix
import numpy as np

df = pd.DataFrame({y: np.random.rand(10000) for y in 'abcdefg'})
scatter_matrix(df[['a','b','c','d']])
```

RAM usage keeps increasing till Vscode crashes. Try to reproduce this procedure in vanilla Jupyter notebook to compare.

## Environment data

-   VS Code version: 1.59.0-insider
-   Commit: e437d424c5e6de97632f5513229c7ebc2cf27a32
-   Jupyter Extension version: 2021.8.1055544705
-   Python Extension version: 2021.7.1060902895
-   OS and version: Windows_NT x64 10.0.19041
-   Python version: 3.7.10 64-bit
-   Type of virtual environment used: conda
-   Jupyter server running: Local
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- V8: 9.1.269.36-electron.0

**Comment by joyceerhl** [comment]
This code takes over 60s to execute in a VS Code notebook and 10s in classic Jupyter. It looks like we're spending 60% of that time hashing cell outputs

**Comment by rebornix** [comment]
A few things happened under the hood slowing down the execution:

## Extension Host

* validateAndCOnvertOutputs
* serializeRequestArguments

![image](https://user-images.githubusercontent.com/876920/127425433-f406d0d9-fb89-42ae-a48b-4e4f34b53ba1.png)


## UI
* toNotebookOutputItemDto converts array buffer to array https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/browser/mainThreadNotebookDto.ts#L15
* we do a diff for output replace to ensure that we only do minimal UI change, but diffing this type of output takes long time (diffing large array buffer)
  * while diffing, we generate a hash for each output, and we did hash directly on array buffer, which is slow.

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/127436404-5ce00c18-a97a-40a0-9381-1760ce0a008e.png)

6 seconds to render this image in the webview.

**Comment by rebornix** [comment]
After removing the hash of cell outputs and disable output diffing for simple cases, right now it spent 10 seconds to execute this code in VS Code but less than < 500ms on Jupyter Lab. It might be related to the communication between the Jupyter kernel and ipywidgets comm.

**Comment by DonJayamanne** [comment]
> . It might be related to the communication between the Jupyter kernel and ipywidgets comm in the webview.

Could be the serialization and deralization that's causing this issue. I have seen that in other places, and have a plan to disable that when we don't have widgets (debt week). Eg here we don't have widgets.

**Comment by rebornix** [comment]
This issue should be gone now. Closing it but we can reopen if anyone of you is still experiencing it.
