### ISSUE TITLE
VS Code crashes on file/folder rename/creation

### ISSUE THREAD

**Issue by manibhushan** [microsoft/vscode#129753]
Issue Type: <b>Bug</b>

There are times when I create a new file and it crashes VSCode. Sometimes on renaming a file/folder also crashes it.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
terminal|for|0.0.10
latex-workshop|Jam|6.5.1
vscode-react-native|msj|0.17.0
latex-support|tor|3.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Please update to the current release. Your 1.33 is more than two years behind.
