### ISSUE TITLE
markdown preview not work

### ISSUE THREAD

**Issue by xckai** [Microsoft/vscode#12987]
- VSCode Version:1.5.3
- OS Version:win10
I in put 

##haha
#hehe

and in preview window i got
 
##haha #hehe
 
I don't know why .....

Steps to Reproduce:

1. add a file named test.md
2. add some words in test.md 
3, click preview

**Comment by joaomoreno** [comment]
You need to add spaces:

```
## haha
# hehe
```

**Comment by xckai** [comment]
yes ,thank you
