### ISSUE TITLE
Icons are misaligned when line height is increased

### ISSUE THREAD

**Issue by nawok** [microsoft/vscode#129888]
Issue Type: <b>Bug</b>

1. Set Editor: Lineheight to 25
2. Set a breakpoint
3. Inspect alignment

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 4|
|Memory (System)|64.00GB (21.11GB free)|
|Process Argv|--crash-reporter-id 8700e51f-d645-4d08-a365-3d1f360d22d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
vscode-tailwindcss|bra|0.6.13
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
gc-excelviewer|Gra|3.0.42
headwind|hey|1.7.0
search-node-modules|jas|1.3.0
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.6.6
expand-region|let|0.1.4
vscode-language-babel|mgm|0.0.31
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
remote-containers|ms-|0.187.1
vscode-typescript-tslint-plugin|ms-|1.3.3
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|4.8.0
vscode-thunder-client|ran|1.8.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
typehole|rik|1.8.0
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
mdx|sil|0.1.0
vscodeintellicode|Vis|1.2.14
quokka-vscode|Wal|1.0.386
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by nawok** [comment]
<img width="399" alt="CleanShot 2021-07-31 at 10 00 27@2x" src="https://user-images.githubusercontent.com/159773/127733434-749b146c-3503-450a-893f-e77352132f87.png">

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/128172
It is fixed in latest insiders and soon in stable
