### ISSUE TITLE
Snippets Not Being Suggested Inside JSX markup of .js or .jsx files

### ISSUE THREAD

**Issue by keepforever** [microsoft/vscode#129897]
Issue Type: <b>Bug</b>

I have the same config inside both my `typescriptreact.json` and `javascriptreact.json` files.

For some reason, within the last month or so, snippets stopped being suggested in `.jsx`  or `.js` files when I am within JSX markup (i.e. inside the return, between <div/> tags in a functional React component). 

My snippets get suggest as expected when I'm in the function block above. 

In `.tsx` files, snippets are suggested as expected.

Please see this video for a clear demo of the bug: https://www.loom.com/share/288e32be79734cf98e434b5a63ad802f

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|. --crash-reporter-id fb5f0a5d-b54a-4ab1-8f9f-af6bacdfbb6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
vscode-apollo|apo|1.19.4
vscode-tailwindcss|bra|0.6.13
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
gc-excelviewer|Gra|3.0.42
vscode-graphql|Gra|0.3.16
lorem-whatever|job|1.0.2
vscode-styled-components|jpo|1.6.6
vscode-language-babel|mgm|0.0.31
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
atom-keybindings|ms-|3.0.9
vscode-jest|Ort|4.0.3
prisma|Pri|2.28.0
mdx|sil|0.1.0
code-spell-checker|str|1.10.2
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.5.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
please share your snippet files and code sample
