### ISSUE TITLE
Settings editor drop down causes odd performance of settings editor

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129810]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.59.0-insider
Commit: 0f22f2d343e33b03e8033d1083513072f58ece21
Date: 2021-07-29T05:14:38.439Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0
Steps to Reproduce:

Click on a dropdown in the settings editor:
![image](https://user-images.githubusercontent.com/2644648/127571295-504f89d4-9731-41b6-9df6-f59f5c2cb3e1.png)
![image](https://user-images.githubusercontent.com/2644648/127571305-82f0f697-6f87-4bb5-8bfa-7fa303dc34cf.png)

Now chose an option and quickly scroll in the settings editor. It's not smooth. Let me know if you need me to show you an example.

**Comment by roblourens** [comment]
I don't see the problem

**Comment by roblourens** [comment]
This is probably slowness from rerendering the list after the edited item loses focus. We have some issues around optimizing this
