### ISSUE TITLE
Memento doesn't store JS Objects with getters correctly

### ISSUE THREAD

**Issue by mminkin** [microsoft/vscode#129814]
I am currently developing an extension that uses `context.workspaceState` to save an array of `BFile`.
When I use this implementation:
```
export class BFile {
  constructor(private _fileName: string, private _viewColumn?: ViewColumn) {}

  public get viewColumn(): ViewColumn | undefined {
    return this._viewColumn;
  }
  public get fileName(): string {
    return this._fileName;
  }
}
```

In this way:
```
// file: BFile from storage
workspace.openTextDocument(file.fileName).then(
        (f) => {
          window.showTextDocument(f, {
            preview: false,
            viewColumn: file.viewColumn,
          });
        })
```
During the same session, there was no problem storing and retrieving the `BFile`.

But when I restart VSCode and retrieve that same `file` from storage, VSCode doesn't get the values of the properties (ie `_fileName`) but it returns the getter itself, which shows up as `<accessor>` in the debug console, and opens a blank Untitled-1 file in the extension host window. 

When I changed my implementation to:
```
export class BFile {
  fileName: string;
  viewColumn: ViewColumn | undefined;
  constructor(fileName: string, viewColumn: ViewColumn | undefined) {
    this.fileName = fileName;
    this.viewColumn = viewColumn;
  }
}
```
All was good, no blank Untitled-1s. 

I encountered this issue initially when trying to store `TextDocument` directly.

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z (2 wks ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by bpasero** [comment]
Storage is not for storing live objects but POJOs. Expect things you pass in to `JSON.stringify` and to get out as `JSON.parse`.

**Comment by bpasero** [comment]
Refs:

https://github.com/microsoft/vscode/blob/9b56416d23e28e8ddc36dc287cbce3223b8fda7f/src/vs/vscode.d.ts#L6244-L6250
