### ISSUE TITLE
Number of Items in Dropdowns aren't Read Consistently when Screenreader Active

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/vscode#129869]
Issue Type: <b>Bug</b>

In the debug configuration dropdown, while a screenreader is active, the number of items present in the dropdown isn't reliably read. 

Expand the dropdown, and note the number of items read. Close the dropdown. Expand the dropdown again, and the number of items read will be different (generally a much larger number).

Tested both with NVDA and Narrator, and reproed with both.

![image](https://user-images.githubusercontent.com/40371649/127719727-e8435e8e-12bd-44d7-b58a-5f8d89cc9ee8.png)

VS Code version: Code - Insiders 1.59.0-insider (e437d424c5e6de97632f5513229c7ebc2cf27a32, 2021-07-28T05:13:47.114Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (18.77GB free)|
|Process Argv|--crash-reporter-id bc368e6a-30f5-44b7-a3ad-e8bd3536f152|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
dotnet-interactive-vscode|ms-|1.0.2357011
vscode-dotnet-runtime|ms-|1.2.0
jupyter|ms-|2021.8.1081660962

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805:30301674
bridge0708:30335490

```

</details>

**Comment by isidorn** [comment]
@chlafreniere thanks for filling this I can reproduce this.
However here we are using a native select box widget, and we actually do not explicitly set the number of items in the select drop down.
1. Can you reproduce the issue if you just use NVDA and a regular site with a dropdown using Chrome?
2. Can you file an issue in the NVDA repo so they also investigate on their side https://github.com/nvaccess/nvda Though it might be a chrome issue as well.

Thanks
