### ISSUE TITLE
Gather folk knowledge from endgame week

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#129859]
This issue is to gather details that we didn't know during endgame week which we learned later and thus should probably be documented somewhere (where that is to be determined once everything is gathered).

**Comment by brettcannon** [comment]
Do you unassign yourself after you check off your TPI? Yes.

**Comment by brettcannon** [comment]
Does the last person to check something off on a TPI close the issue? Yes.

**Comment by brettcannon** [comment]
What are all the possible roles the [TPI template](https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items) can use?

**Comment by sandy081** [comment]
Writing test plan items wiki - https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items

**Comment by rzhao271** [comment]
I found some API test plan items (TPIs) difficult to test in the past. The following links helped me:

- There's a samples repo here https://github.com/Microsoft/vscode-extension-samples. One first navigates into the folder containing the extension they want to test, and then starts the usual npm i + build + F5 flow
- Generating a new extension template using yeoman and generator-code https://code.visualstudio.com/api/get-started/your-first-extension
- Getting the proposed API, manually or using vscode-dts https://code.visualstudio.com/api/advanced-topics/using-proposed-api
- Fixing type errors from proposed API mismatch https://code.visualstudio.com/api/advanced-topics/using-proposed-api#proposed-api-incompatibility

When it comes to the endgame week itself:
- The priority for testing and verification is TPIs, then verification-needed feature requests, then bugfixes
- All feature-requests being verified must have verification-needed, or if they're covered by a TPI, on-testplan
- Bugs being verified don't need to have either of those labels -- they just need the `bug` label
- Closed issues with the `bug` label that don't need to be verified (i.e. they're invalid or tracked elsewhere) should have their milestone removed, and if applicable, another label like `invalid` or `*duplicate` added on.

**Comment by jrieken** [comment]
> I found some API test plan items (TPIs) difficult to test in the past. The following links helped me:

Added this section which describes a quick path to latest and proposed API: https://github.com/microsoft/vscode/wiki/Writing-Test-Plan-Items#how-to-testing-proposed-andor-latest-api
