### ISSUE TITLE
fail to git push

### ISSUE THREAD

**Issue by Pengwei-Jin** [microsoft/vscode#129889]
Issue Type: <b>Bug</b>

I connect to a centos server remotely and use git by Module. I can git push in a shell, but when I click the button provided by VSCode, an error come out with the message "fatal: unable to find remote helper for 'https'". 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.95GB free)|
|Process Argv|--crash-reporter-id a010d572-b11d-4b18-96e4-3ea6699500da|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ict_login02|
|OS|Linux x64 3.10.0-1127.13.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (80 x 799)|
|Memory (System)|376.18GB (160.40GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.58.8
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
remote-x11-ssh|spa|1.5.0
vscode-icons|vsc|11.5.0
githistory|don|0.6.17
copilot|Git|1.2.2184
gc-excelviewer|Gra|3.0.42
vscode-language-pack-zh-hans|MS-|1.58.8
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by Pengwei-Jin** [comment]
![2021-07-31 174652](https://user-images.githubusercontent.com/84560451/127736034-427c640c-d4ff-4d59-a271-63130b1c14e3.png)
![2021-07-31 174812](https://user-images.githubusercontent.com/84560451/127736038-e72925bc-fffe-4fe1-8a3a-1f0631357d6b.png)

**Comment by lszomoru** [comment]
@Pengwei-Jin, are you still able to reproduce this with the latest version of VS Code?
