### ISSUE TITLE
CMD + Q confirmation before close EVERYTHING!

### ISSUE THREAD

**Issue by carlosen14** [microsoft/vscode#129838]
On Mac, CMD + Q will close all application windows, I would like to see a confirmation box before do the action, just like Google Chrome does it. This command is so key-close to CMD + W, which will only close a tab.

Example:
- User press CMD + Q
- There will appear a confirmation alert "Are you sure to close all application windows?"
- User select "Yes" to close all, or "No" to just dismiss.

**Comment by carlosen14** [comment]
mmm, similar, but i'll accept it

**Comment by kkanekii** [comment]
I don't think this is a vscode issue / addon / requested feature

For vscode, this could be a future feature, someone should be willing to do this though

For global alert, only MacOS will be able to do it
