### ISSUE TITLE
can't copy figures to clipboard from jupyter notebook

### ISSUE THREAD

**Issue by jheissb** [microsoft/vscode#129880]
Issue Type: <b>Bug</b>

in jupyter notebook, produce any plot, then select and try to copy to clipoard either by pressing ctrl-c or edit-copy.

It doesn't do anything and the clipboard remains empty. The only option is to save the figure to disk, which is not practical.
I had to go back to use the browser instead of VScode for jupyter notebooks.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (22.12GB free)|
|Process Argv|--crash-reporter-id 2f12ecf8-3564-49b2-8351-e7b4544d8b03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
githistory|don|0.6.17
gitlens|eam|11.6.0
githd|hui|2.2.4
vscode-github|Kni|0.30.6
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by jheissb** [comment]
![screenshot](https://user-images.githubusercontent.com/46458532/127729885-6c10fb71-73a7-4fac-b667-d40f794d3a53.jpg)

Attached screenshot showing I can highlight the figure, but it is not getting copied to clipboard. tried ctr-c, right click and from the edit medu.

**Comment by gaboceron10** [comment]
Hello, Is there any update in this feature request? We really need the feature to copy figures to clipboard, this help us when we want to add a figure to a document/article. That would be great, thank you very much.

**Comment by gaboceron10** [comment]
> What do other clients do, copy it as html or as an image?

At the moment I'm using Azure Notebooks, and what it let you do is to right click to copy the image generated for example by matplotlib to the clipboard, then you can right click (or use ctrl+v) to paste it  directly into a document, for example a Word document.

**Comment by vitorbaptista** [comment]
Just chipping in that this feature would be very useful and sharing my current workaround. There are currently two methods of saving a picture to be used in another document:

* Save to your local machine
* Print-screen the image section (the Ctrl+Shift+PrntScr shortcut helps a lot)

Saving is slow to do for many pictures, and print-screen reduces the image quality. Being able to right-click and copy the image would be great.

**Comment by jordi-sastre** [comment]
This feature would be extremely useful. I have worked before with Atom+Hydrogen and it was possible to copy+paste or drag and drop images from the output panel. This made my life much easier. Now I'm using VSCode and I do miss a lot this feature. If I want to quickly copy an image elsewhere I need to either navigate to a directory and save it there or do a screenshot, which is not that practical.

**Comment by mika76** [comment]
> Have the same problem. It really hinders sharing work results and collaboration. Saving as a work around is extremely tedious and time consuming.

I have figured out a bit of a workaround if you're interested - create a powershell cell and use the `Set-Clipboard` command with a `#!share` command - see this discussion: https://github.com/dotnet/interactive/discussions/1984#discussioncomment-2673035

**Comment by pamzgt** [comment]
This feature would be very useful! the workarounds are very annoying. It would be great to have it.

**Comment by AlFontal** [comment]
Indeed, this is definitely the number 1 feature that irks me the most in the VS Code Jupyter workflow!

**Comment by andreimargeloiu** [comment]
+1, this feature would be super useful!

**Comment by kerry-tarrant** [comment]
It would be great if there was a feature to right-click and copy/save my figures.

**Comment by amunger** [comment]
With the Jupyter extension installed and the latest vscode-notebook-renderers extension, there should be a new copy button that shows up on mouse hover over the output, which will place the image into the system clipboard.

Make sure you have the correct presentation selected, only png ouput is currently supported:
![image](https://user-images.githubusercontent.com/2019016/180049546-3afb2d96-fc83-4ed2-9fe9-6e7673a43ab2.png)
![image](https://user-images.githubusercontent.com/2019016/180049629-34731067-7491-4927-a30f-d9ae721870d3.png)
