### ISSUE TITLE
Update shell file icon

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#129894]
🙈 The current icon doesn't fit the other icons or the VSC aesthetic.

**Comment by SNDST00M** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/82655227/127743765-283fb459-f3f2-4e25-bd22-b4ad009e39b9.png" />

**Comment by misolori** [comment]
@SNDST00M Can you please point out the icon in question?

**Comment by SNDST00M** [comment]
`shell.ico` in my screenshot

**Comment by SNDST00M** [comment]
![image](https://user-images.githubusercontent.com/82655227/127875953-8dfdfa2d-09fe-4b42-a660-42094db45e6b.png)

**Comment by misolori** [comment]
That's the same icon we use in our file icons via seti:

<img width="210" alt="CleanShot 2021-08-02 at 08 58 11@2x" src="https://user-images.githubusercontent.com/35271042/127890131-b0a95340-c0a6-4e32-aba2-19c42c804919.png">

**Comment by SNDST00M** [comment]
The Seti icon should also be updated. That looks like a generic document in the UI

**Comment by misolori** [comment]
You'll have to file that in the [seti repo](https://github.com/jesseweed/seti-ui) as we pull directly from that and don't apply any modifications. Will close this as `as-designed`.

**Comment by SNDST00M** [comment]
Done. jesseweed/seti-ui#616

**Comment by SNDST00M** [comment]
It's merged so you should be able to update the shell now.

**Comment by misolori** [comment]
Updated via https://github.com/microsoft/vscode/commit/5a394770ad023da0eb6c0953fddefaaf05f704d5

**Comment by SNDST00M** [comment]
Great! https://github.com/microsoft/vscode/blob/3ace189/resources/win32/shell.ico as well :)

**Comment by misolori** [comment]
I'll re-open this one to track the updates

**Comment by misolori** [comment]
@SNDST00M left a comment about the color https://github.com/jesseweed/seti-ui/pull/616#issuecomment-894511439 i'll wait on updating the ico file once that's updated

**Comment by SNDST00M** [comment]
The colors been updated upstream

**Comment by misolori** [comment]
Shell icon is updated now in our file icons:

<img width="222" alt="CleanShot 2021-08-11 at 12 43 50@2x" src="https://user-images.githubusercontent.com/35271042/129093037-cdb871ea-3c41-4cce-8c20-871f031ea6d2.png">

Will look at updating the file assets in the build next week

**Comment by misolori** [comment]
This has been update via https://github.com/microsoft/vscode/commit/e9b74efc3cc312c4eb8e179ceb331f613fbb82c1

![image](https://user-images.githubusercontent.com/35271042/133131261-8ce55089-0503-4026-82b9-37765fca8818.png)

I'm going to wait on updating the file icons until a few iterations have passed so we don't have too much churn there

**Comment by ericslandry** [comment]
I'd like to share some feedback with the shell icon. I like having the dollar sign icon for my shell files, but I'm colorblind and the icon's cursor looks like an underscore in my file's name. I always do a double take when I see my files might have an underscore prefix.

![icons](https://user-images.githubusercontent.com/3536127/133258315-357812e9-66c4-44e8-af7b-ef954f73b9ca.png)

Sorry for spamming this issue, but it seemed to be close enough.

**Comment by SNDST00M** [comment]
OH color blindness is something I forgot to consider this time and I see that now 😅

**Comment by SNDST00M** [comment]
I believe this was resolved in the November release by #136375 (thanks @adaex!)

**Comment by SNDST00M** [comment]
@misolori gentle nudge to remove this from "On Deck"
