### ISSUE TITLE
Virtual file system sub-folder breadcrumb bar issue

### ISSUE THREAD

**Issue by WaynePhillipsEA** [microsoft/vscode#129881]
- VS Code Version: v1.58.2
- OS Version:  Windows 10

My twinBASIC extension registers virtual filesystems, through registerFileSystemProvider.  The workspace folders are configured to point to subfolders in these virtual file systems, like so:

<img width="351" alt="tb_breadcrumbIssue2" src="https://user-images.githubusercontent.com/25738109/127730242-ba5ad87a-702d-477b-a605-2777baf6937b.png">

Whilst the subfolders are correctly not visible in the Explorer folders treeview, they do appear in the breadcrumbs, as seen here:

<img width="757" alt="tb_breadcrumbIssue" src="https://user-images.githubusercontent.com/25738109/127730267-15a378b9-ff14-4207-890e-c7bd2bbcfa52.png">

Notice the second entry in the breadcrumb bar doesn't correlate to the listed Explorer treeview.  In my opinion, the 'HelloWorld'  entry in the breadcrumb bar should not be visible.

**Comment by jrieken** [comment]
Please share a simple version of your file system provider and workspace setup that allows me to reproduce this. Thanks
