### ISSUE TITLE
Native Notebooks - Clear cell output

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129815]
Would be nice if ability clear one cell's output was contributed to this menu 

![image](https://user-images.githubusercontent.com/19276747/127586679-eea193fe-4779-4f19-ab21-99cab26aba37.png)

**Comment by roblourens** [comment]
It's in the output toolbar (the `...` menu by the output)

**Comment by claudiaregio** [comment]
I remember seeing it there once, however I never find myself going there when looking for the clear. I think that's especially because I have already associated that menu item to have other output impacting items. (Collapse cell output, delete cell, join with next cell/preivous cell)  

![image](https://user-images.githubusercontent.com/19276747/127722661-688906b4-4997-46ea-9084-5f797c0667fa.png)

**Comment by roblourens** [comment]
It seems like there could be other commands that would go under the output toolbar, like copy outputs or things that extensions might contribute. If not, I'd be a little inclined to do what you suggest and make the mimetype picker work the way it used to

**Comment by DonJayamanne** [comment]
> ut toolbar, like copy outputs or things that extensions might contribut

+1 for this

**Comment by DonJayamanne** [comment]
Given that all of the output related menu options have been moved to `...` menu for outputs, we're now consistently not displaying any output related menus in cell toolbar.
Given the fact that we haven't had any other issues/upvotes related to this, I'm closing this for now.
