### ISSUE TITLE
VS Code gives permission denied when attempting to Pull from Github or Gitlab

### ISSUE THREAD

**Issue by nathanjwtx** [microsoft/vscode#129840]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Install clean version of either VS Code or VS Code Insiders (no extensions installed and don't sign in to sync settings)
2. Open a git source controlled project.
3. Click on the Source Control tab in the menu
4. Select Pull from the 'View and more actions' menu
![image](https://user-images.githubusercontent.com/1558027/127681409-84bf8cec-4715-42aa-9e95-279230d3a124.png)

VS Code doesn't appear to require me to sign in to Github, or Gitlab, so I'm not entirely sure how the pull command would succeed anyway.
I can use Git commands from the built-in VS Code terminal, Git Bash, and WSL2 so I'm confident that I am logged in correctly and the SSH keys are setup.

My issue appears to be similar to a couple of other open issues in as much as the error returned is the same but the scenario under which it occurs is different.

VS Code version: Code - Insiders 1.59.0-insider (0f22f2d343e33b03e8033d1083513072f58ece21, 2021-07-29T05:13:10.735Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.75GB (7.12GB free)|
|Process Argv|--crash-reporter-id c612717a-b987-46bd-abac-f2795d09319c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.11
auto-rename-tag|for|0.1.7
code-runner|for|0.11.5
dotnet-test-explorer|for|0.7.6
godot-tools|gee|1.1.2
vscode-test-explorer|hbe|2.20.4
beautify|Hoo|1.5.0
jenkinsfile-support|ivo|1.1.0
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
roslynator|jos|3.2.1
vscode-python-test-adapter|lit|0.7.0
vscode-language-babel|mgm|0.0.31
vscode-exec-node|mir|0.5.4
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.8.1068685406-dev
vscode-pylance|ms-|2021.7.8-pre.1
remote-containers|ms-|0.190.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
mono-debug|ms-|0.16.2
test-adapter-converter|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
godot-csharp-vscode|nei|0.1.3
material-icon-theme|PKi|4.8.0
material-product-icons|PKi|1.0.4
vscode-yaml|red|0.22.0
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|2.0.0
msbuild-project-tools|tin|0.3.15
vim|vsc|1.21.5
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthrucf:30344902

```

</details>

### Edit
I recreated this on a new, clean install of VS Code with no extensions installed and not signed in to sync settings. This happens on VS Code and VS Code Insiders.

**Comment by AnneMayor** [comment]
Did you try to type the command below and see what happen?
`git remote rm origin`
`git remote add origin git@github.com:<your remote repo path>`

For me, I have the similar issue with yours.

Validating found git in: /usr/local/bin/git
Using git 2.30.0 from /usr/local/bin/git
> git rev-parse --git-dir
Open repository: /Users/dahyeannelee/algorithmstudy
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :Main.java
> git ls-files --stage -- /Users/dahyeannelee/algorithmstudy/Main.java
> git check-ignore -v -z --stdin
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

However, I assume that the issue above has linked with ssh key name.
I set the unique name of my ssh key name(git@github.com-study) and changed it.
When I tried to git pull or push through terminal(OS X 11.5) there is no issue.
I have attached the screenshot of the execution in terminal.

<img width="548" alt="Screen Shot 2021-08-22 at 7 51 05 PM" src="https://user-images.githubusercontent.com/15176192/130352965-8b11730c-6585-4d2d-82d2-5161616b6d9b.png">

I am not sure why this issue has occurred in vscode...

**Comment by nathanjwtx** [comment]
I can use Git from the command line, Visual Studio, and Rider without issue using the same account. It isn't tied to a specific repo.

**Comment by AnneMayor** [comment]
Recently, I have tried to git pull & push from my local repo in Vscode and it has worked fine. I think my issue on comment looks resolved.

**Comment by lszomoru** [comment]
@nathanjwtx, are you still able to reproduce this issue with the latest version of VS Code Insiders?

**Comment by nathanjwtx** [comment]
I was able to successfully push to Gitlab, with a password, from the today's Insiders build.

**Comment by lszomoru** [comment]
@nathanjwtx, thanks for the update. I will close this issue but please feel free to reopen if it reoccurs.
