### ISSUE TITLE
Wrong visualization of images

### ISSUE THREAD

**Issue by hildogjr** [microsoft/vscode#129848]
Issue Type: <b>Bug</b>

Just open a PNG image, the (0,0) pixel is centered at the canvas, not the center of the image.

![image](https://user-images.githubusercontent.com/2211474/127698256-5c7e006b-31ff-4b1b-97b3-365e292f2f9d.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2846)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.54GB (5.98GB free)|
|Process Argv|--unity-launch --crash-reporter-id b1cf6861-45ee-48e6-a61c-8956377084d3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|3.0.42
markdown-preview-showdown|jhu|1.3.7
git-graph|mhu|1.30.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
hexeditor|ms-|1.8.2
platformio-ide|pla|2.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
Looks like you are in a git diff view. Because this is a new image, there is no original image to show on the left hand side
