### ISSUE TITLE
editor.wordSeparators no longer allows double click to capture variable with "$"

### ISSUE THREAD

**Issue by Ben-Conrad** [microsoft/vscode#129852]
VSCode 1.58.2 on Windows.

We've been using this setting for **many years** to allow a double click (in PowerShell) to capture variable names (like $MyVariable).  This is used extensively to copy/paste the variables inside VSCode.  

By default VSCode only selects MyVariable when double click, so we use this editor.wordSeparators setting to remove '$'

    "editor.wordSeparators": "`~!@#%^&*()=+[{]}\\|;:'\",.<>/?",

There has been a recent change in VSCode that prevents this from working.  Double clicking on $MyVariable and ctrl-c only selects MyVariable.

I also notice that the "$" is highlighted with a different color than the rest of the variable name.   See screenshots.

Ben

**Comment by Ben-Conrad** [comment]
**WordSeparator not working:**
![wordseparator-not-working](https://user-images.githubusercontent.com/11560403/127706312-f85521cd-fc5a-4da3-9af1-9f460284f9d8.png)

**PowerShell**
![configured-language-powershell](https://user-images.githubusercontent.com/11560403/127706336-4bb323f4-a81c-4de4-94bc-a6da147460c4.png)

**Settings.json**
![settings-json](https://user-images.githubusercontent.com/11560403/127706350-0229d4e0-6706-434b-80c1-2301e43936fe.png)

**Comment by Ben-Conrad** [comment]
This guy's got the answer, it seems the behavior got toggled inside vscode recently- https://stackoverflow.com/questions/68128258/vscode-does-not-honor-editor-wordseparators-when-writing-powershell-code

`    "[powershell]" : {
        "editor.wordSeparators": "`~!@#%^&*()=+[{]}\\|;:'\",.<>/?"
    },
    "files.defaultLanguage": "powershell",
    "editor.showFoldingControls": "always",
    "editor.acceptSuggestionOnEnter": "off",
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.codeLens": false,
    "files.hotExit": "onExitAndWindowClose",
    "git.autofetch": true,
    "git.confirmSync": false,
    "git.suggestSmartCommit": false,
    "git.alwaysShowStagedChangesResourceGroup": true,
    "git.openDiffOnClick": true,
    "git.postCommitCommand": "sync",
    "git.promptToSaveFilesBeforeCommit": "always",
    "git.confirmEmptyCommits": true,
    "git.autoStash": true,
}`

**Comment by Ben-Conrad** [comment]
I consider this a workaround but the maintainers may consider a bug so I'll leave open for a bit to see what you think.

**Comment by alexdima** [comment]
VS Code core does not ship a language-specific setting for `editor.wordSeparators` for PowerShell. This can be verified by using `F1 > Preferences: Open Settings (JSON)` in a vanilla VS Code installation and searching for `editor.wordSeparators`. 

I think you are running into two problems:
1. You are using an extension which defines a language specific setting for PowerShell. Please reach out to the extension that is responsible. You can identify it using Extension Bisect (`F1 > Help: Start Extension Bisect`).
2. It is not made clear to you that the non-language-specific user setting you define for `editor.wordSeparators` is overwritten for PowerShell by the default language-specific setting the extension defines. I agree with this feedback cc @sandy081

**Comment by Ben-Conrad** [comment]
Thanks everyone, this appears to be an intended change in vscode-powershell, noted here: https://github.com/PowerShell/vscode-powershell/blob/c983f75be23b78daeb69e31a0987a655a14207b9/CHANGELOG.md#v202151

Closing issue.
