### ISSUE TITLE
FOLDERS WENT MISSING!

### ISSUE THREAD

**Issue by Ash-KODES** [microsoft/vscode#129823]
Please see if you can find any logged output that could help us find the source of the issue:

run code --verbose from the command line and attach the output
in Code select Help | Toggle Developer Tools and select the Console
attach any output you see in the Console you can find
Thanks!

**Comment by Ash-KODES** [comment]
I have found the root cause of the issue. I have installed a node module called cpx and using it to copy files from the build folder to docs folder after building the app. This module is holding a lock onto the docs folder. So, I will close the issue now.

**Comment by gjsjohnmurray** [comment]
Please close this, and #129819 if that was also created by you.
