### ISSUE TITLE
[macOS] Dragging proxy icon into embeded terminal drops any tilde '~' in filename

### ISSUE THREAD

**Issue by JayPalm** [microsoft/vscode#129846]
Issue Type: <b>Bug</b>

Drag and drop an icon with a tilde character ('~') in the file name (or path) from the finder window into the embeded terminal. The copied path will exclude any tildes in the filename/path.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id 8bed741f-9310-4ce8-9803-b32daf2e2d98|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
see https://github.com/microsoft/vscode/issues/122665#issuecomment-831272376 for more info
