### ISSUE TITLE
.gitignore folder names starting with # are being ignored

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#129841]
- VS Code Version: 1.58.2
- OS Version: macOS 11.4 (Big Sur)

Steps to Reproduce:

1. Add the folder `amplify/#current-cloud-backend` to your root
2. Add `amplify/\#current-cloud-backend` to .gitignore
3. Notice this folder still shows up in the SCM tab

<img width="695" alt="Screenshot 2021-07-30 at 17 22 28" src="https://user-images.githubusercontent.com/22457463/127683035-174e0374-0ce2-43e1-be96-b493d414da52.png">

**Comment by joaomoreno** [comment]
> A line starting with # serves as a comment. Put a backslash ("\") in front of the first hash for patterns that begin with a hash.

https://git-scm.com/docs/gitignore#_pattern_format

**Comment by andrecasal** [comment]
The backslash is there. Please look at the image I attached on line 6: `amplify/\#current-cloud-backend`

The `amplify/#current-cloud-backend` folder is still showing up on Source Control.
