### ISSUE TITLE
ctrl w kills terminals even if the panel isn't focused

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#129858]
1. create an editor terminal, pin the tab
2. create a few terminals in the panel
3. focus the editor terminal -> ctrl W -> 🐛 panel terminal is killed

![recording (51)](https://user-images.githubusercontent.com/29464607/127713189-dcb90fab-d910-45cd-8203-71ed45b29680.gif)

**Comment by rzhao271** [comment]
Is it expected that the editor switches to an unpinned tab after pressing Ctrl+W?

**Comment by Tyriar** [comment]
Yes that's one of the behaviors of pinned tabs - it's more difficult to close them
