### ISSUE TITLE
Invalid instrumentation key warning from Microsoft Authentication extension in developer log

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#129807]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open desktop VS Code
2. Open developer tools log
3. 🐛 error about an invalid instrumentation key
![image](https://user-images.githubusercontent.com/30305945/127565120-b20c52ce-d08e-4bb4-8f48-e34ced28b18a.png)

**Comment by lramos15** [comment]
This is a standard warning and can be safely ignored. It has to do with us using the application insights module in a non-standard way. The work to fix this won't be happening for at least a few more iterations and there's nothing we can do about it right now.
