### ISSUE TITLE
Native Notebooks - Ctrl + H not working

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#129817]
Steps to Reproduce:

1. Try to use Ctrl + H to find and replace in a notebook 

Note: Ctrl + F appears to work fine

![Ctrl H bug](https://user-images.githubusercontent.com/19276747/127591839-45ff9bd4-d58f-462e-96a8-855c2d294147.gif)

**Comment by rebornix** [comment]
thanks we already have an issue tracking this.
