### ISSUE TITLE
How can I use the existing Language Service Host for JavaScript?

### ISSUE THREAD

**Issue by GregorBiswanger** [Microsoft/vscode#12984]
Hi,
I would like to write a VSCode Extension. It will support JavaScript IntelliSense in a HTML file.
For own TypeScript code I used a own TypeScript Language Server Host.  

I like to save a lot of time and would use the existing Language Service Host for JavaScript from VSCode.
So I can support default JS functions and properties... As example, I have a own TypeScript property from type string.. and I would support the string functions like .replace, .length, .sub etc.

Does anyone have an idea?

Gregor

**Comment by dbaeumer** [comment]
This is currently not possible. We have plans to look into exposing API via the extension itself.

**Comment by mjbvz** [comment]
TypeScript server plugins may offer what you are looking for: https://github.com/RyanCavanaugh/sample-ts-plugin Server plugins allows you to augment and change the behavior of TypeScript

Let me know if this enables what you had in mind or if you need additional functionality
