### ISSUE TITLE
markdownEnumDescriptions don't remove markdown <backtick>##<backtick> in the settings UI and don't remove ## in settings.json

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#129844]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows

Steps to Reproduce:

1. View the files.autoSave, afterDelay enum description.

Bug: The \`##\` isn't removed:

![image](https://user-images.githubusercontent.com/19859882/127690558-bce6fa2a-2ba7-470a-804f-0f4c8299e19c.png)

In settings.json, `##` isn't removed:
![image](https://user-images.githubusercontent.com/19859882/127690528-dae59dca-9dd9-406e-8af2-fabf2fcd7b05.png)

**Comment by roblourens** [comment]
@rzhao271 if you are going to move an issue to the backlog, please put labels on it
