### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Javaw1** [microsoft/vscode#129849]
VSCode is great and its a nice experience to code with. But sometimes when i use multiple files and use module.exports i don't get a suggestion for the interface/variable

**Comment by mjbvz** [comment]
Please fill in the issue template and share an example project that demonstrates this issue

/needsMoreInfo

**Comment by CodeCrazy-ywt** [comment]
@Javaw1 Could u provide some specific example?

**Comment by mjbvz** [comment]
Closing as not enough information to investigate
