### ISSUE TITLE
No way to enter a cell at the top of a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#129855]
Issue Type: <b>Bug</b>

The toolbar (hover or main) doesn't allow me to enter a cell above other cells.

I have to select the first cell and hit 'a', or use the command palette and pick 'Insert Cell Above'

VS Code version: Code - Insiders 1.59.0-insider (baed4398a72bde585574b4c6cf3f241438bd3f39, 2021-07-28T19:37:22.975Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (18.16GB free)|
|Process Argv|--crash-reporter-id 108b1212-dd8c-4594-8252-c1351bf31268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
python|ms-|2021.8.1068685406-dev
vscode-pylance|ms-|2021.7.8-pre.1
jupyter|ms-|2021.8.1081660962
remote-containers|ms-|0.190.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.7.2717
live-server|ms-|0.2.6
vscode-typescript-next|ms-|4.4.20210729

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthrucf:30344902

```

</details>

**Comment by rebornix** [comment]
With our insert toolbar styling update, we didn't update the insert toolbar above the first cell, which is intended for inserting cells above first cell.

**Comment by rebornix** [comment]
Fixed.

**Comment by rzhao271** [comment]
\closedWith ee1fc3a0d60aba68e25d0b2cb0113e310d3d7ad5

**Comment by alexr00** [comment]
\closedWith ba0df885e9d6b0f0ccf2cc714c3fa31423572205
