### ISSUE TITLE
Bad overflow with letterpress

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12980]
![image](https://cloud.githubusercontent.com/assets/22350/18944354/57014d12-8625-11e6-8bb2-78678b646d83.png)

**Comment by chrmarti** [comment]
@bgashler1 Could you take a look? Not sure what the best fix is here.

**Comment by joaomoreno** [comment]
`overflow: none` in the parent solves it.

**Comment by chrmarti** [comment]
`none` is not a documented value for `overflow`: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

`white-space: nowrap` seems to do it.

**Comment by joaomoreno** [comment]
I meant `overflow: hidden`. `nowrap` might work, but it could still overflow.

**Comment by joaomoreno** [comment]
And still does:

![image](https://cloud.githubusercontent.com/assets/22350/18970467/b117a4e2-8691-11e6-85d4-0145afdf6985.png)

**Comment by chrmarti** [comment]
@joaomoreno What are the steps to reproduce that?

**Comment by joaomoreno** [comment]
Reduce the window size. In dev tools select the `monaco-workbench` element. In the console type `$0.scrollLeft = 100`.

Scroll can be messed around due to unexpected situations, like #11385.

Please use `overflow: hidden`.

**Comment by chrmarti** [comment]
@joaomoreno Not sure how like that situation is to occur. Should this go into the September release?

**Comment by joaomoreno** [comment]
No no, not September. 👍

**Comment by roblourens** [comment]
I still can repro this
![image](https://cloud.githubusercontent.com/assets/323878/19749891/add53748-9ba1-11e6-9c63-028bfc199b42.png)

**Comment by joaomoreno** [comment]
@roblourens It doesn't appear to overflow anymore, though.

**Comment by roblourens** [comment]
Oh I see - I misunderstood what the bug was.
