### ISSUE TITLE
Uninstalling python uninstalls jupyter

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#129802]
Testing microsoft/vscode-jupyter#6821

1) have the jupyter extension
2) install the python extension when prompted when trying to run a python notebook
3) uninstall the python extension

-> jupyter extension is gone

**Comment by greazer** [comment]
Jupyter is installed as a soft dependency of Python now. So by default we're assuming that soft dependencies are also uninstalled. However, if the jupyter extension is installed first, clearly we shouldn't be uninstalling it with Python. Seems more like a VS Code bug to deal with? Or can we support this in Python / Jupyter?

**Comment by rebornix** [comment]
This should not happen anymore as Jupyter is no longer part of the Python extension pack.
