### ISSUE TITLE
Restart TS server option is not available

### ISSUE THREAD

**Issue by KevinQuinonesA** [microsoft/vscode#129877]
Issue Type: <b>Bug</b>

I opened a .ts file and at the command palette, the option of Restart TS Server is not available. I also tried to reopen VsCode with the extension disabled

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic snap
Restricted Mode: No

Extensions: none

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

When disabling extensions, only disable the installed ones, not built-in ones such as TS
