### ISSUE TITLE
key (ctrl+v) to paste in input Box with custom editor doesn’t work

### ISSUE THREAD

**Issue by ap891843** [microsoft/vscode#129826]
Issue Type: <b>Bug</b>

**Issue**
I am trying to show an inputBox in one of our custom editors. But the key binding(ctrl+c / ctrl+v) doesn't work.
Everything else works as expected, i.e. you can paste using right click and choose option paste. Other key input works as well. I was able to replicate the same in the Sample custom editor code.

link to the repository where the issue can be seen - https://github.com/ap891843/vscode-extension-samples/blob/bugReplication/custom-editor-sample/src/pawDrawEditor.ts#L410

**Please find the below key-binding debug screenshots:**
![image](https://user-images.githubusercontent.com/69206564/127621703-734ea4d2-4c19-4d52-bef4-81cbc48bfc7b.png)

**Please find below keybinding mapping on my system**
![image](https://user-images.githubusercontent.com/69206564/127621777-f67ec28b-b868-490f-a46c-e10afd49173d.png)

NOTE: It seems ctrl+shift+v, works on windows. But not on mac (of course, I am talking about the equivalent of ctrl+shift+v in mac)
keybinding debug output for ctrl+shift+v 
![image (2)](https://user-images.githubusercontent.com/69206564/127622211-da53f665-8427-4783-a23d-9d7527638ab5.png)

**Expected behavior:**
ctrl+v should be able to paste to the inputBox in the custom editor.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (18.90GB free)|
|Process Argv|--crash-reporter-id b039f606-0464-45f2-8cd7-a4c451731926|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jcl-language-support|bro|1.0.0
css-theme-completions|con|0.0.4
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
vscode-lombok|Gab|1.0.1
vscode-antlr4|mik|2.2.4
vscode-docker|ms-|1.15.0
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|0.80.0
html5-boilerplate|sid|1.1.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.0
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.1
vscode-extension-for-zowe|Zow|1.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
vshan820:30294714
vstes263cf:30335440
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe fixed by https://github.com/microsoft/vscode/commit/f882d49bc7b72b8417f0aba686ed6d76960d5de7

Are you able to test your scenario with Insiders (1.59)? If not, I suggest you wait a week, by which time 1.59 should be released.

**Comment by ap891843** [comment]
Thanks, @gjsjohnmurray. Just checked with insiders and it's working as expected. Waiting for the 1.59 release.

**Comment by gjsjohnmurray** [comment]
👍 Please close this issue
