### ISSUE TITLE
enableScriptExplorer setting missing

### ISSUE THREAD

**Issue by proidit** [microsoft/vscode#129837]
- VS Code Version:1.58.2
- OS Version:Windows 10

has the  npm.enableScriptExplorer option been removed from the settings?

**Comment by IllusionMH** [comment]
Yes. It was deprecated year ago and removed later.
See https://github.com/microsoft/vscode/commit/bb3c233e97d8e2d78d9fa97a5fea5274e8300ad1 and https://github.com/microsoft/vscode/issues/104591#issuecomment-673959672

You should be able to show this view from context menu if you have `package.json` in root of the folder or check and upvote https://github.com/microsoft/vscode/issues/119868 and underlying dependency on activation triggers.
