### ISSUE TITLE
Auto-closing pairs in TypeScript aren't working

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#129808]
Version: 1.59.0-insider
Commit: 0f22f2d343e33b03e8033d1083513072f58ece21
Date: 2021-07-29T05:14:38.439Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

1. Open a TS file
2. Type `(`

Expect the paren to be auto-closed but it's not.

![Untitled](https://user-images.githubusercontent.com/2644648/127566274-5bd61449-4593-4a0f-9fbf-e122d3a9c33c.gif)
Here's a gif, PowerShell working as a comparison.

**Comment by mjbvz** [comment]
@TylerLeonhardt Can you see if disabling copilot fixes this for you. It seems to for me

**Comment by mjbvz** [comment]
Marking this as by-design for Copilot
