### ISSUE TITLE
My .CSS files icons is not showing proper, also not detecting the colors

### ISSUE THREAD

**Issue by nirmalsinghoo7** [microsoft/vscode#129890]
Issue Type: <b>Bug</b>

Maybe something changed in my VS code's settings. The icon of CSS files is showing an unknown file type. http://i.prntscr.com/CmH-GiWURfKVsb8q3OCZVg.jpeg
It's not showing the color picker - http://i.prntscr.com/CUE5SkU9Rf2qqLJ0uh4_qw.jpeg  
Like this - http://i.prntscr.com/9JMcaSuBSiCtvCopn0bs_w.jpeg

Also, Autocomplete is not working in CSS files.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.69GB free)|
|Process Argv|--crash-reporter-id e41c3c64-37c1-47de-84fd-120e0262f26e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-browser-preview|auc|0.7.1
indented-block-highlighting|byi|1.0.7
bracket-pair-colorizer|Coe|1.0.61
postcss|css|1.0.9
macos-modern-theme|dav|2.1.9
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
vscode-gutter-preview|kis|0.27.1
kite|kit|0.147.0
code-beautifier|mic|2.3.3
debugger-for-chrome|msj|4.12.12
advanced-new-file|pat|1.2.2
vscode-thunder-client|ran|1.8.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.5
remove-empty-lines|use|0.0.8
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.5.0
quokka-vscode|Wal|1.0.386
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions

**Comment by aeschli** [comment]
Make sure the editor mode is CSS (look for CSS in the status bar).
Check the file associations in the settings.
Run with all extensions disabled (Command: Reload With Extensions Disable)
