### ISSUE TITLE
Provide option to show unsaved(dirty) indicator for webview

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode#129822]
Can you please provide option in vscode api to show/hide unsaved/dirty indicator dot for webview, I am currently developing [Thunder Client ](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client )extesnion. This feature will be very useful to show the state of data on the webview.

![Screenshot 2021-07-30 at 08 25 20](https://user-images.githubusercontent.com/8637550/127617430-3b16f4b6-c5a1-477a-943d-660fe58ac307.png)

or Let me know if its already possible with existing vscode api?

**Comment by Ash-KODES** [comment]
you can simple turn on the autosame from setting which will automatically save the unsaved stuff and no dot will appear.

**Comment by rangav** [comment]
I am looking for vscode api, for development of extension.

that setting won’t have any affect on extension webview

**Comment by Ash-KODES** [comment]
yes,i see!

**Comment by mjbvz** [comment]
This is possible using custom editors. These editors can be for virtual resources, so they do not have to directly map to a resource on disk

Give the custom editor API a try

**Comment by rangav** [comment]
Hi @mjbvz thanks for the reply.

The webviews I am using are **not linked to any physical file** directly, still can I use the `CustomEditorProvider` to achieve this? (see screenshot below)

I have seen the example provider in https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample, which is associated with file.

<img width="1280" alt="Screenshot 2021-08-03 at 11 28 43" src="https://user-images.githubusercontent.com/8637550/128001903-ac2b4cb9-41f0-4f0e-aa64-d61df73db380.png">

**Comment by rangav** [comment]
the current custom editor example has two samples which are associated with physical files

- `catScratchEditor.ts`
- `pawDrawEditor.ts`

do you have any example of custom editor API for **webview with no physical file**?

**Comment by rangav** [comment]
Can you re-open this issue, as there is no example how to use custom editor with virtual document.

It’s better to provide dirty flag on the webview for easy solution. 

Custom editor looks more complicated for my use case.
