### ISSUE TITLE
Shortcut to toggle (show and hide) explorer view

### ISSUE THREAD

**Issue by sergiubologa** [Microsoft/vscode#12983]
- VSCode Version: 1.5.3
- OS Version: Windows 8

Steps to Reproduce:
1. Open the _Explorer_ view by pressing `Ctrl+Shift+E`
2. Press again `Ctrl+Shift+E` to open the _Explorer_ view

Expected result:
The _Explorer_ view will open and will be visible to the user

Actual result:
The _Explorer_ view doesn't open. `Ctrl+Shift+E` works only for closing the view.

**Comment by joaomoreno** [comment]
<kbd>Ctrl B</kbd> shows and hides the sidebar.
