### ISSUE TITLE
Pencil button issues in dirty file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#129861]
- Open settings.json
- Make the file dirty, disable autosave
- Use the pencil icon to try to change a setting
- Get an error that the file is dirty
- Click "Save and retry"
- Nothing happens
- Press cmd+s to save
- Get an error that the 'contents of the file are newer' because the pencil actually wrote to the backing file without updating the editor

**Comment by rzhao271** [comment]
Do you still see this on the latest Insiders? I'm unable to reproduce the issue.

**Comment by roblourens** [comment]
I can still repro
