### ISSUE TITLE
URL not updating in preview browser while using react router

### ISSUE THREAD

**Issue by tejasc0** [microsoft/vscode#129893]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- Version: 1.58.2
- Commit: c3f126316369cd610563c75b1b1725e0679adfb3
- Date: 2021-07-14T22:30:16.440Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Linux x64 5.11.0-25-generic

Steps to Reproduce:

1. create simple route using react-router-dom and use navbar to navigate through routes
2. run "npm start" and open webpage in preview browser
2. when we navigate using nav bar, views changes but the  url doesnt change.
3. the url changes in external browser, but not in the vscode preview browser.

**Comment by tejasc0** [comment]
![vscode](https://user-images.githubusercontent.com/35273882/127740387-dc694143-bc53-4170-8bf7-80f29c615944.png)
screenshot

**Comment by tejasc0** [comment]
![chrome](https://user-images.githubusercontent.com/35273882/127740425-f9176c26-5e29-4a26-a3de-060372d41dc7.png)
screenshot of external browser (Google Chrome)

**Comment by mjbvz** [comment]
We can't inspect when the user navigates inside an iframe (which is how the simple browser is implemented)

Not something we can work around since this is a security limitation
