### ISSUE TITLE
Loss of cell language types when reloading a new untitled notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#129803]
Testing microsoft/vscode-jupyter#6821

1) have the jupyter and python extensions installed
2) create a new untitled notebook
3) add code cells with Python as the language type
-> don't save the notebook
4) uninstall python extension  (also see https://github.com/microsoft/vscode-jupyter/issues/6887)
5) reload window
-> code cells now have the language type "plain text"; we should not lose the language type

**Comment by greazer** [comment]
This is something that the Jupyter extension cannot control.

**Comment by DonJayamanne** [comment]
Should be resolved with https://github.com/microsoft/vscode-jupyter/issues/4757
