### ISSUE TITLE
Chinese IME malfunctioning in integrated terminal search box

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [microsoft/vscode#129891]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0-insider
- OS Version: Windows 10 10.0.19043.1110

Steps to Reproduce:

0. have a Chinese IME installed, I use Microsoft IME
1. (press ctrl+`) open integreted terminal
2. (press ctrl+f) open search dialog
3. (press win+space maybe multiple times) switch input language to Chinese (you might need to install one)
4. switch the Microsoft Input IME to Chinese mode, type in some words, for example (nihao / 你好)
5. the behavior looks like the follwing GIF

![bug](https://user-images.githubusercontent.com/12868093/127737247-29df7db8-7aca-45ca-b848-1ff2173b81a6.gif)

and it shoud work like this (demonstrate in notepad.exe)

![shoudbe](https://user-images.githubusercontent.com/12868093/127737258-a6c84731-feaa-4a19-a902-83472170f27f.gif)

this bug appears in both release version and insider version

**Comment by MichaelSuen-thePointer** [comment]
> did this happen in earlier versions of VS code or is it a new issue?

can't remember, probably this is the first time I use IME in terminal search box

**Comment by MichaelSuen-thePointer** [comment]
> did this happen in earlier versions of VS code or is it a new issue?


I manually bisected earlier versions, it seems a triage
v1.51 is good https://code.visualstudio.com/updates/v1_51
v1.56 is good https://code.visualstudio.com/updates/v1_56
v1.59 is broken https://code.visualstudio.com/updates/v1_59
v1.58 is broken https://code.visualstudio.com/updates/v1_58
v1.57 is good https://code.visualstudio.com/updates/v1_57

**Comment by MichaelSuen-thePointer** [comment]
Hi, folks, any progress?

**Comment by wenfangdu** [comment]
Reproducible in v1.67.2 and v1.68.0, not reproducible in v1.69.0-insider.

**Comment by MichaelSuen-thePointer** [comment]
Seems already fixed during version update, closed

**Comment by wenfangdu** [comment]
@MichaelSuen-thePointer Still reproducible with Sougou IME or Microsoft Pinyin in v1.69.2, are you using the same version?

**Comment by MichaelSuen-thePointer** [comment]
Reopen this issue since it occured again in 1.70.1 (user setup)

**Comment by Tyriar** [comment]
This is working fine for me now, it was likely fixed:

![Recording 2023-12-07 at 13 39 39](https://github.com/microsoft/vscode/assets/2193314/bd7a9a09-7e10-4906-afde-287a01c5d4a5)
