### ISSUE TITLE
Regression: can no longer copy empty lines

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12988]
- VSCode Version: latest 1.6 insider
- OS Version: Mac & Windows

Steps to Reproduce:

1. click somewhere into a line and invoke the copy command
2. paste

=> you no longer paste the full line

This used to work. Marking as important.

**Comment by isidorn** [comment]
@bpasero I can do some git bisection to try to find the root cause...

**Comment by bpasero** [comment]
@isidorn do not even try it, git bisect does not work in this case

**Comment by bpasero** [comment]
Caused by https://github.com/Microsoft/vscode/issues/11673
