### ISSUE TITLE
Azure pull request review plugin

### ISSUE THREAD

**Issue by dmltesla** [microsoft/vscode#129835]
We use Azure repository  pull requests for remote linux code changes made using VS Code.  Unfortunately the Pull Request reviews in the Azure site are not as useful as reviewing code changes in VS Code for us which impacts our procedures.   This is an opportunity for Microsoft to show off what it can do for their own products without appearing to use big brother tactics.   Please seriously consider this as a golden opportunity.

**Comment by dmltesla** [comment]
Just to clarify:  It isn't necessary to create Azure pull requests in VS Code, just to view one and review ALL code changes for one. In fact it can just be a side by side view of a file against it's version in the azure master branch.

**Comment by Tyriar** [comment]
This would be up to the Azure devops team to consider
