### ISSUE TITLE
Unhelpful "TypeError: (x.description || x.markdownDescription || "").split is not a function" occurs when a setting's "description" in package.json is an array instead of a string

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#129850]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows

Steps to Reproduce:

1. Accidentally use a "description" with an array of strings value in an extension's setting in package.json (the intent being to use "enumDescriptions" instead). See https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema .
2. Run the extension.

Actual: Extension settings fail to appear. The developer console shows "TypeError: (x.description || x.markdownDescription || "").split is not a function". The only way to determine the cause is to debug VS Code's javascript in the Developer Console.

Expected: Ideally, the package.json schema could cause a squiggle or error when the description is not a string, or if an informative popup could appear that shows the package.json entry that is invalid, such as what occurs when "description" has a "%key%" that can't be found in package.nls.json.

**Comment by dbaeumer** [comment]
This got fixed yesterday. Please see https://github.com/microsoft/vscode/issues/126408
