### ISSUE TITLE
my folders went missing

### ISSUE THREAD

**Issue by vrindakohli** [microsoft/vscode#129819]
Issue Type: <b>Feature Request</b>

all my folders went missing suddenly on vscode. I did not delete them but now I cant find any project that I made. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Ash-KODES** [comment]
I have found the root cause of the issue. I have installed a node module called cpx and using it to copy files from the build folder to docs folder after building the app. This module is holding a lock onto the docs folder.

**Comment by isidorn** [comment]
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
