### ISSUE TITLE
Incorrect duplicated directories restored upon undo (ctrl/cmd + z)

### ISSUE THREAD

**Issue by mytchmason** [microsoft/vscode#129878]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Delete directory (cmd + delete) within Code file explorer.
2. Restore directory (cmd + z)

Upon restoring attempt of directory restore, somehow, the actual directory with the files or folders inside is not restored, but rather, a copy of the directory's name, but not it's contents. 

Ex: directory deleted labeled "pages".

Upon checking macOS trash, two folders are present: "pages 21-32-37-027" (a copy) and "pages". Only the "pages" directory contains the actual files and/or folders within. However, when restoring folder with VS Code, it restores the "pages 21-32-37-027" directory as "pages", while the original directory remains within Trash.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/111022
