### ISSUE TITLE
[loc][Query][VSCode] the string Please clarify 

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#12999]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Accessibility &amp;&amp;Options
Go to &amp;&amp;Symbol in File...
Go to Symbol in &amp;&amp;Workspace...
File Name:
src\vs\code\electron-main\menus.nls.resx
Resource ID:
".resx", 0; "miAccessibilityOptions"
".resx", 0; "miGotoSymbolInFile"
".resx", 0; "miGotoSymbolInWorkspace"
Query:
Could you please explain why there are two ampersands in the source string? Do we need to reflect it in the translation?	inho.chung	9/29/2016 10:48:17 AM

**Comment by bpasero** [comment]
@mkyjakova && denotes a mnemonic
