### ISSUE TITLE
[snippets] How can I excute some javascript in snippet

### ISSUE THREAD

**Issue by falltodis** [Microsoft/vscode#12990]
- VSCode Version:  1.5.3 (1.5.3)
- OS Version: mac os

How can I excute  some javascript in snippet? I want to make a common coment with systemtime which looks like below

```
// config
"date: ${new Date().toISOString()}"

// I want
date: 2016-09-10 12-12-12

// actually 
date: new Date().toISOString()
```

**Comment by jrieken** [comment]
closing as dupe of #10561
