### ISSUE TITLE
File search (ctrl + E) should suggest more relevant options

### ISSUE THREAD

**Issue by LucyMac** [Microsoft/vscode#12991]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:
1. From anywhere inside VSC, ctrl + E opens a dialog to search by file name. 
2. Start typing, list of options appear. 

Unfortunately, the options are not sorted by any relevance (recently opened, or files from folder currently working on). It would be great if this could be improved!

Example: 

I have 6 files open, all from a folder called .../userSettings/
I want to open a 7th file called main.js from that same folder so I type ctrl + E, "main.js"
I have a main.js file in a dozen different folders in my project, so I get a list of all the main.js from all my folders, but I would expect userSettings/main.js to be at the top of the list as I'm working on that folder. Failing that, it should still be at the top of the list because I worked on it an hour ago and closed it, and I'm reopening it again (having not worked on any other main.js from other folders in a while).

Hope this makes sense! Thanks

**Comment by bpasero** [comment]
We put files you opened in the past to the top, but I agree that there could be many more factors how to make this better based on context.

**Comment by LucyMac** [comment]
thanks @bpasero
