### ISSUE TITLE
exrtreme slow procedures

### ISSUE THREAD

**Issue by Rishanmehmi** [microsoft/vscode#129912]
Issue Type: <b>Bug</b>

usability of vs code is really slow on windows 11 insiders program.
system config: i5 8th gen , Ram : 8 Gb , Hdd space Almost empty

VS Code version: Code - Insiders 1.59.0-insider (104bc571e956e4af623905ef10dfcc8f0fdac625, 2021-07-30T13:25:42.497Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Can you share the startup numbers following https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers for the slow launch and fast launch. Thanks!

**Comment by Rishanmehmi** [comment]
thanks but i resolved it with the configuration preferences method. thanks for your support. <3 Github

**Comment by deepak1556** [comment]
As learning, what configuration was causing the slowdown ?

**Comment by Rishanmehmi** [comment]
well I dont know about the prebuilt config but i set a comment as a code
and it works smooth afterwards
