### ISSUE TITLE
Unexpected behavior from vscode.workspace.applyEdit

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#129969]
(Similar in spirit to #122883 and #111331).

I’ve received some logs from users that imply unexpected behavior from the `vscode.workspace.applyEdit` API.
 
I pass a single edit to `applyEdit`, then receive the `onDidChangeTextDocument` event for multiple edits, then `applyEdit` returns successfully.
 
An example of the logs (the actual edit text is replaced with its length to preserve privacy):
 
```
vscode.workspace.applyEdit: [{"range":[{"line":56,"character":8},{"line":56,"character":8}],"newText":10}]
onDidChangeTextDocument: [{"range":[{"line":61,"character":0},{"line":61,"character":8}],"rangeLength":8,"rangeOffset":1448,"text":0},{"range":[{"line":56,"character":8},{"line":56,"character":8}],"rangeLength":0,"rangeOffset":1438,"text":10}]
vscode.workspace.applyEdit result: true
```
 
You can see the `onDidChangeTextDocument` event includes the edit I was trying to apply but also includes a deletion of 8 characters - `{"range":[{"line":61,"character":0},{"line":61,"character":8}],"rangeLength":8,"rangeOffset":1448,"text":0}`.
 
Sometimes the change from `onDidChangeTextDocument` looks nothing like the edit passed to `applyEdit`. Example logs:
 
```
vscode.workspace.applyEdit: [{"range":[{"line":41,"character":0},{"line":41,"character":0}],"newText":98}]
onDidChangeTextDocument: [{"range":[{"line":0,"character":0},{"line":0,"character":0}],"rangeLength":0,"rangeOffset":0,"text":100}]
vscode.workspace.applyEdit result: true
```
 
I initially thought that this could be due to auto-formatting or an extension that’s performing edits in response to the `onDidChangeTextDocument` event, but I haven’t been able to reproduce that. 
 
Do you have any idea what’s going on? Does VS Code do some combining of edits from multiple sources and raise them in a single `onDidChangeTextDocument` event? How could I reproduce that? And if so, is there any way to disable this behavior? I want to ignore the `onDidChangeTextDocument` for the edit applied with `applyEdit` but take action on all other changes.

**Comment by bpasero** [comment]
@daytonellwanger would you possibly be able to distill this into a small extension to reproduce for us based on a `yo code` generated extension?

**Comment by daytonellwanger** [comment]
@bpasero , unfortunately no. I think this is somewhat rare. I was only able to identify it by looking at user logs. But based on how the logs are created, I'm pretty confident the above is happening, I just don't know *why*. I was hoping you all could fill me in on that part.

But regardless of the specifics of this situation, I'm looking for a theoretical guarantee about how `vscode.workspace.applyEdit` and `onDidChangeTextDocument` are supposed to work together.

**Comment by jrieken** [comment]
> I'm looking for a theoretical guarantee about how vscode.workspace.applyEdit and onDidChangeTextDocument are supposed to work together.

An edit causes a change but there is no guarantee that the change reflects the edit perfectly. For instance, changes are often "too large", e.g replace the whole text to change a single character. Such edits make it hard to keep the editor selections and decorations stable and therefore we have logic to make edits (that are applied with an editor, not document) _more minimal_, see [this](https://github.com/microsoft/vscode/blob/233a3bd7365d09686fb7bc9463333181878c6a53/src/vs/workbench/contrib/bulkEdit/browser/bulkTextEdits.ts#L201). This and similar features can cause the "disconnect" between edit and observed change.

**Comment by daytonellwanger** [comment]
Thanks!

So given that this is expected behavior, is there a simple way for an extension to filter out the parts of the `onDidChageTextDocument` that it was responsible for?

Perhaps another way to accomplish the same would be to start tagging edits with their origin. I know other extensions have the requirement that they would like to know if an edit was caused by the user typing or because of a command or another extension (e.g. time tracking extensions that track time spent coding/lines coded).

Otherwise I suppose we can just compare the edit we apply and the edit we get from `onDidChangeTextDocument` and "subtract out" our edit to get the other changes. It seems like that'd be a little messy, but maybe not.

One other note is that this isn't an issue for me if the received edit is "equivalent" to the applied edit in the sense that both leave the document in the same state at the end (as in your example of transforming an edit that replaces the whole text to one that only modifies a single character). But I don't think that's the type of transformation observed in the logs I attached. The example of wanting to keep edits more minimal to avoid decorator disruption makes sense. What's the motivation for modifying the "intent" of the edit? And if there are such situations, would it make more sense to raise `onDidChangeTextDocument` twice?

**Comment by daytonellwanger** [comment]
Ping

To summarize:
- Is it expected that the edit contained in `onDidChangeTextDocument` would ever change the "intent" of the edit passed to `applyEdit`?
- What's the suggested way to get only those edits that my `applyEdit`s weren't responsible for?

**Comment by alexdima** [comment]
Maybe `editor.trimAutoWhitespace` is playing a part here? When someone presses something like <kbd>Enter</kbd>, the editor inserts "automatic whitespace" with the correct indentation. This "automatic whitespace" is removed with the next text buffer edit if the next text buffer edit does not "use" the automatic whitespace. Here is how the feature works like when pressing <kbd>Enter</kbd> twice (notice how 4 spaces are inserted on line 4, but then automatically removed when pressing the second <kbd>Enter</kbd>):

https://user-images.githubusercontent.com/5047891/130787499-a954784f-e091-489e-a231-5258c0ef6608.mp4

This behavior was first introduced in vscode 5 years ago via https://github.com/microsoft/vscode/commit/fb5b68d199918fbe58e57d4faa3909580430fa4e , so it is not a recent change.

I don't think `applyEdit` is always 100% respecting the passed in arguments. For example, if `applyEdit` is called with an edit which contains a range that would break up a surrogate pair, then that edit range is modified such that it will not break up the surrogate pair.

**Comment by jrieken** [comment]
Different things

* making edits more minimal -> this means the emitted edits differ but the outcome does not
* whitespace insertion/fixing -> this means emitted edits differ and the outcome differs
* prevent broken surrogate pairs -> this means the emitted edits differ but the outcome does not

There is likely others and the bottom line is that there is no guarantee that an extension can observe precisely its own edits or effects of its own edits (submitted via `applyEdit`). The only guarantee is that `applyEdit` resolve to `false` when the edits couldn't be applied and `true` when they could
