### ISSUE TITLE
Cmd-X does not delete/cut the current line

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#12993]
- VSCode Version: Code - Insiders 1.6.0-insider (6746e53a611ecb3e0777fca6a4c8387dc392513f, 2016-09-29T06:04:54.045Z)
- OS Version: Darwin x64 15.6.0
- Extensions: `QassimFarid.ejs-language-support-0.0.1`, `alefragnani.project-manager-0.10.0`, `bradgashler.htmltagwrap-0.0.3`, `donjayamanne.githistory-0.0.12`, `formulahendry.auto-rename-tag-0.0.7`, `tuxtina.json2yaml-0.1.1`, `waderyan.gitblame-1.3.0`, `wcwhitehead.bootstrap-3-snippets-0.0.7`, `wmaurer.join-lines-0.1.5`

Steps to Reproduce:

1. Cmd-X does not delete (cut) the current line. You have so select the line (Shift-Down) to select and then it Cut.

It's happening from this latest build.

**Comment by moigagoo** [comment]
The same on Windows (with Ctrl+X).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12988
