### ISSUE TITLE
Deactivate or subscription.dispose don't write to the log

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#1299]
I have the following code

```typescript
export function activate(context: ExtensionContext) {
	context.subscriptions.push(new Disposable(() => {
		fs.writeFileSync('C:/log-sub.txt', 'On Dispose');
	}));
}

export function deactivate() {
	fs.writeFileSync('C:/log-deact.txt', 'On Deactivate');
}```

However after closing VSCode running that extension no log file exist in C:\

**Comment by alexandrudima** [comment]
@dbaeumer Under Windows AFAIK software needs to run as admin to write to `C:\\`. What works for me is when I write to `C:\\log.txt`

**Comment by alexandrudima** [comment]
I can also repro with the following extension:

... what changed since last week?

```javascript
console.log('I am loaded');

var fs = require('fs');

exports.activate = function() {
	fs.writeFileSync("C:\\Alex\\log.txt", new Date() + ":: activate called");
}

exports.deactivate = function() {
	fs.writeFileSync("C:\\Alex\\log.txt", new Date() + ":: deactivate called");
}
```

**Comment by alexandrudima** [comment]
Tried again with and this seems to work....

```javascript
console.log('I am loaded');

var fs = require('fs');

exports.activate = function() {
	fs.appendFileSync("C:\\Alex\\log.txt", new Date() + ":: activate called\n");
}

exports.deactivate = function() {
	fs.appendFileSync("C:\\Alex\\log.txt", new Date() + ":: deactivate called\n");
}
```

**Comment by alexandrudima** [comment]
I was misreading the log, the version with `writeFileSync` had only one message and it was deactivate called

**Comment by alexandrudima** [comment]
@dbaeumer pls give me a heads up if you try this again as it seems to work for me.

**Comment by dbaeumer** [comment]
@alexandrudima writing to a location different than root works. Sorry for the swirl.

**Comment by jcward** [comment]
FYI, we found (https://github.com/jcward/vscode-haxe/issues/3#issuecomment-192681931) on Linux that dispose wasn't being called in VSCode 0.10.1, and it's working fine in 0.10.8.
