### ISSUE TITLE
react syntax highlight is broken

### ISSUE THREAD

**Issue by atlanteh** [Microsoft/vscode#12996]
- VSCode Version: 1.5.2
- OS Version: Win 7

vscode syntax highlight for react fails to recognize the following snippet:

```jsx
import React from 'react';

export class MyClass extends React.Component {
    
    myMethod() {
        const { 
            prop2} = this.props;

            const some = 
                        `${siteName}`;
    }
}

```
Output:
![capture](https://cloud.githubusercontent.com/assets/3952700/18952648/36cca432-8653-11e6-9d36-95e840183f49.PNG)

Steps to Reproduce:

1. open a JavaScript file
2. copy the above code

**Comment by waderyan** [comment]
@atlanteh thank you for opening this issue. We just released an [extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) in beta (plans are to bring it into the product after test) to fix over 200+ issues like this. can you install and try the extension to see if it resolves your issue?

**Comment by atlanteh** [comment]
Yep, that solves it. Thx :)
