### ISSUE TITLE
Define a "ignored characters" list in the file search (via cmd + p)

### ISSUE THREAD

**Issue by arbesulo** [microsoft/vscode#129952]
Very often I copy a ruby class name from a stacktrace or from the code, which usually is something like `MonduleName::ClassName` (for example `Admin::User`), which by convention is located under `module_name/class_name` (in the example, would be `admin/user.rb`).

The problem is that the separator `::` is not part of the file path and VS-Code does not find it, so I have to 
to delete those `::` every time, which turns pretty annoying very quickly.

I haven't found any option in the settings for this. It would be nice to be able to tell VS-Code to ignore certain characters from  the file search.

**Comment by TylerLeonhardt** [comment]
Reasonable. Let's put it on the Backlog Candidates to gauge interest.
