### ISSUE TITLE
Sync is broken when no internet is available

### ISSUE THREAD

**Issue by KL13NT** [microsoft/vscode#129916]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Every version since Sync landed in production builds
- OS Version: Windows 8.1 Pro Latest

Steps to Reproduce:

1. Login
2. Change some settings
3. Turn on sync
4. Close the editor
5. Set an internet speed limit to 1 KB/s for instance (has to be too low)
6. Launch VSCode again
7. Watch as the extension fails to sync and reset local settings

**Comment by KL13NT** [comment]
My settings were reset for no reason a few minutes ago and all my settings are gone. None. No more. Themes, shortcuts, snippets, environment setup, etc. This is really frustrating, and is not the first time it happened. I'm seriously considering turning off sync for good.

**Comment by KL13NT** [comment]
And when viewing the Sync Activity (Local) tab there's nothing there. Only default VSCode settings.

**Comment by sandy081** [comment]
> Watch as the extension fails to sync and reset local settings

Can you please Enable log level to trace, repeat above steps and provide the settings sync log by running the command `F1 > Open View > Log (Settings Sync)`
