### ISSUE TITLE
I hope to add an option in the menu bar like Editor font zoom in

### ISSUE THREAD

**Issue by lixiao189** [microsoft/vscode#129909]
Now the option in the menu bar here can zoom in the UI's size totally
<img width="561" alt="image" src="https://user-images.githubusercontent.com/44799572/127756802-3bfd27f8-db5c-4ec2-8a5c-a21adb3b7af1.png">

I don't think that's convenient enough. Sometimes I just want to zoom in the size of the font in the editor, not all the element in the UI. So can you add an option in menu bar to change the size of the editor font only? 😃

**Comment by CodeCrazy-ywt** [comment]
You can already do that! Simply adjust the value of `editor.fontSize`.

**Comment by sbatten** [comment]
@lixiao189 please see 
![image](https://user-images.githubusercontent.com/6561887/128380475-abc8aa02-1e85-4997-bbf9-ac209fc5c970.png)

![image](https://user-images.githubusercontent.com/6561887/128380619-2ecd2ce5-eb2b-4432-bc1e-9da916735a1e.png)
