### ISSUE TITLE
`quickOpenNavigateNext` broken?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#12998]
I have below keybinding configuration (to restore the old `cmd+e`) and it use to open a file when I release press/release `cmd+e` in the quick view. This stopped working (today?) and I have to press `enter` to open a file

```
    {
        "key": "cmd+e",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "cmd+e",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    }
```

**Comment by jrieken** [comment]
fyi @joaomoreno from whom I have copied this config

**Comment by bpasero** [comment]
@jrieken caused by https://github.com/Microsoft/vscode/issues/11673 which I reverted
