### ISSUE TITLE
SemanticHighlight not work in .html file

### ISSUE THREAD

**Issue by meowWhat** [microsoft/vscode#129962]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.1
- OS Version: win10  wsl2.0

Steps to Reproduce:
- I wrote a demo following the semantic highlighting guide,In JS files, highlighting works fine, but in HTML files, it doesn't work properly, and the highlighting flashes away。
- Checked the plugins I installed with vscode to make sure they have no side effects, So I guess there's something wrong with the vscode built-in plugin。
- Here is my demo code, along with a GIF of the error replay
```typescript
  const tokenTypes = ['templateType']
  const legend = new vscode.SemanticTokensLegend(tokenTypes)

  const provider: vscode.DocumentSemanticTokensProvider = {
    provideDocumentSemanticTokens(
      document: vscode.TextDocument
    ): vscode.ProviderResult<vscode.SemanticTokens> {
      const tokensBuilder = new vscode.SemanticTokensBuilder(legend)
      tokensBuilder.push(0, 0, 10, 0)
      return tokensBuilder.build()
    }
  }

  context.subscriptions.push(
    vscode.languages.registerDocumentSemanticTokensProvider(SELECTOR_HTML, provider, legend)
  )
```
```json
  "contributes": {
    "semanticTokenScopes": [
      {
        "language": "html",
        "scopes": {
          "templateType": [
            "keyword.winged"
          ]
        }
      }
    ]
  }
```
![test](https://user-images.githubusercontent.com/59830413/127861282-ae4ad3a3-dabf-41c9-bdd5-8548ff24107a.gif)

**Comment by alexdima** [comment]
It looks like there is already a built-in document semantic highlight provider registered by HTML [here](extensions/html-language-features/server/src/modes/javascriptSemanticTokens.ts). 

Currently, VS Code supports at most one document semantic highlight provider. I thought that perhaps you could try beating the built-in HTML semantic highlight provider using a more specific document selector, but that doesn't seem to work.

---

FYI @jrieken I would have assumed that using:
```
vscode.languages.registerDocumentSemanticTokensProvider(
      { language: 'html', scheme: 'file', pattern: '**/*.*' },
      provider,
      legend
    )
```
would beat using:
```
vscode.languages.registerDocumentSemanticTokensProvider(
      'html',
      provider,
      legend
    )
```
But it looks like the both get the score 10 and still the built-in one returns first in the `LanguageFeatureRegistry.ordered` call.

---

The only somewhat proper thing I can think of is to ask @aeschli for a setting or API to prevent the built-in document semantic highlighter from registering.

---

The hacky workaround would be to make sure to register yours after the built-in. It looks like the built-in might be registered later which appears to influence the selected one.
