### ISSUE TITLE
Impossible d'ecrire le fichier "vscodeÉchec de l'enregistrement de 'nq-nci.c' : Impossible d'écrire le fichier 'vscode-remote://wsl+ubuntu/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c')

### ISSUE THREAD

**Issue by ZeruxMiatoll** [microsoft/vscode#129989]
Issue Type: <b>Bug</b>

Échec de l'enregistrement de 'nq-nci.c' : Impossible d'écrire le fichier 'vscode-remote://wsl+ubuntu/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c')

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.14GB free)|
|Process Argv|--crash-reporter-id 3eda70eb-dc87-4de9-aa74-d7aed71dd05b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|7.74GB (3.46GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.6
vscode-language-pack-fr|MS-|1.58.8
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
easy-cpp-projects|ACh|2.0.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
vscode-terminal-for-ubuntu|Doc|0.0.2
vscode-pull-request-github|Git|0.28.0
open-in-browser-wsl2|how|0.0.1
wsl-split|Iam|0.0.1
better-cpp-syntax|jef|1.15.6
wsl-path|kgr|0.1.0
vscode-wsl-workspacefolder|lfu|1.1.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4631
vsliveshare-audio|ms-|0.1.91
vscode-open-wsl|NoT|0.2.2
save-and-run-wsl|rai|0.0.182
wsl-path-tools|rob|1.0.1
cmake|twx|0.0.17
windows-terminal|wra|2.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723cf:30346311

```

</details>

**Comment by aeschli** [comment]
The error says that you don't have write permissions on `/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c'`. Can you check what the permissions are? e.g. `ls -al `/home/zerux/android_kernel_xiaomi_vayu/drivers/nfc/nq-nci.c'`.

**Comment by ZeruxMiatoll** [comment]
i have actually fixed it, i have just reinstall my wsl :/

**Comment by aeschli** [comment]
Thanks for the reply.
