### ISSUE TITLE
Extremely slow startup on Windows 11

### ISSUE THREAD

**Issue by Aerodymier** [microsoft/vscode#129930]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows 11 Insider Beta 22000.100

Steps to Reproduce:

1. Launch VSCode for the first time
2. You'll see the extremely slow startup

I should note that this doesn't happen on second, third or more launches, only on first one. 
This wasn't happening on Windows 10.
I don't know if this is something which VSCode team or Windows team shall handle, please inform me if it's not your case and I'll submit an Insider bug report.

**Comment by deepak1556** [comment]
Can you share the startup numbers following https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers for the slow launch and fast launch. Thanks!

**Comment by Aerodymier** [comment]
This is the fast startup, getting the slow one is a bit rare so I'll add that when I get it:
[prof-85e1.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6919978/prof-85e1.renderer.cpuprofile.txt)
[prof-85e1.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6919980/prof-85e1.main.cpuprofile.txt)
[prof-85e1.extHost.cpuprofile.txt.zip](https://github.com/microsoft/vscode/files/6920012/prof-85e1.extHost.cpuprofile.txt.zip)

Last one was too big for GitHub so I zipped it.

**Comment by deepak1556** [comment]
Can you also attach the startup timer numbers, Hit `F1` and select "Startup Performance". Please provide the numbers for both slow and fast launch.

**Comment by Aerodymier** [comment]
| What                                                            | Duration | Process                   | Info                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------ |
| start => app.isReady                                            | -        | [main]                    | initial startup: false                     |
| nls:start => nls:end                                            | -        | [main]                    | initial startup: false                     |
| require(main.bundle.js)                                         | -        | [main]                    | initial startup: false                     |
| start crash reporter                                            | -        | [main]                    | initial startup: false                     |
| serve main IPC handle                                           | -        | [main]                    | initial startup: false                     |
| create window                                                   | -        | [main]                    | initial startup: false,                    |
| app.isReady => window.loadUrl()                                 | -        | [main]                    | initial startup: false                     |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 107      | [main->renderer]          | ReloadedWindow                             |
| require(workbench.desktop.main.js)                              | 262      | [renderer]                | cached data: YES, node_modules took 0ms    |
| wait for window config                                          | 0        | [renderer]                | -                                          |
| init storage (global & workspace)                               | 89       | [renderer]                | -                                          |
| init workspace service                                          | 30       | [renderer]                | -                                          |
| register extensions & spawn extension host                      | 506      | [renderer]                | -                                          |
| restore viewlet                                                 | 67       | [renderer]                | workbench.view.extensions                  |
| restore panel                                                   | 19       | [renderer]                | workbench.panel.output                     |
| restore & resolve visible editors                               | 197      | [renderer]                | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 402      | [renderer]                | -                                          |
| workbench ready                                                 | 866      | [main->renderer]          | -                                          |
| renderer ready                                                  | 766      | [renderer]                | -                                          |
| shared process connection ready                                 | 43       | [renderer->sharedprocess] | -                                          |
| extensions registered                                           | 1279     | [renderer]                | -                                          |

**Comment by Aerodymier** [comment]
> Any updates here? Does this still reproduce, @Aerodymier?

Sorry I missed the notification. No, it does not happen anymore.
