### ISSUE TITLE
R: Autocompletion will double first word in R chunk in RMD

### ISSUE THREAD

**Issue by wdiao-zju** [microsoft/vscode#129937]
When Using vscode-R, autocompletion will double first word in R chunk in RMD file. For example, 'as.character' will be 'as.as.character' in R chunk in .Rmd file but work well in .R file. Authors from vscode-R extension think it is a vscode issue and symbol with ` . ` will cause this problem. In R, `as.character` is an independent function unlike python.

**Comment by hediet** [comment]
This really sounds like an issue of vscode-R. Why do its authors think otherwise?

Can you reproduce this independently of R?

**Comment by wdiao-zju** [comment]
The author think that `.` in R is obviously different from other language e.g. python. It causes that R-languageserver did not well deal with `.` . For example, `as.tibble` is a whole as a function other than 2 independent functions `as` and "tibble". R-LSP did not make error in as_tibble. Thanks.
