### ISSUE TITLE
Fluent Design

### ISSUE THREAD

**Issue by baris-inandi** [microsoft/vscode#129908]
With the Insider releases of Windows 11, the Microsoft fluent design is implemented throughout the OS. The VS Code icon can also be updated with the new release. The current has flat colors and more light/shadow can be added. Here is an example I did:

![current](https://user-images.githubusercontent.com/68742481/127754447-c1564795-6968-48df-9555-6fcf0392266e.png)

![vsc](https://user-images.githubusercontent.com/68742481/127754448-8605e4fb-6c6b-4c2e-aff7-3d67e009d16e.png)

The second icon features more obvious shadows and light similar to icons on Windows 11. This could be a nice addition to the new fluent design icons.

**Comment by abdouAoufi** [comment]
awesome

**Comment by misolori** [comment]
Thanks for the suggestion, will pass this along to our brand team that handles our product icons. We also have to be aware of how this applies to other operating systems like macOS and Linux as we are a cross platform team.
