### ISSUE TITLE
Bash terminal 

### ISSUE THREAD

**Issue by amalaussena** [microsoft/vscode#129971]
Issue Type: <b>Bug</b>

Re: [microsoft/vscode] Default Integrated Terminal Shell (#128763)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.05GB free)|
|Process Argv|--crash-reporter-id 8db7d65c-9c8d-4330-8c5b-e7695c90306e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dotnet-runtime|ms-|1.2.0
azurecli|ms-|0.5.0
azurerm-vscode-tools|msa|0.15.2

</details>

**Comment by amalaussena** [comment]
Checked terminal (#126545)
Default Integrated Terminal Shell (#128763) seems issue is not yet solved.

**Comment by meganrogge** [comment]
/duplicate 
#128763
