### ISSUE TITLE
Window switcher should indicate the currently active window in the list

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12997]
Testing #12522

In the case below an indicator, e.g, trailing 'dot' would have helped me to see which window is the active one.

![image](https://cloud.githubusercontent.com/assets/172399/18954919/6fa77136-8655-11e6-8cfb-c4506d779407.png)

**Comment by bpasero** [comment]
@heycalmdown would you like to provide this in a new PR?

**Comment by heycalmdown** [comment]
Okay, good point.

**Comment by heycalmdown** [comment]
<img width="611" alt="screen shot 2016-10-01 at 2 00 06 pm" src="https://cloud.githubusercontent.com/assets/154198/19011900/96ea0b88-87df-11e6-8e9d-368b076455ad.png">

which way?

**Comment by heycalmdown** [comment]
<img width="605" alt="screen shot 2016-10-01 at 2 01 15 pm" src="https://cloud.githubusercontent.com/assets/154198/19011912/e2338b46-87df-11e6-947d-e7e8c220af93.png">

I like this one.
