### ISSUE TITLE
TypeScript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by Danilo-ManoMano** [microsoft/vscode#129950]
Issue Type: <b>Bug</b>

I'm just opening a React / Typescript project (that uses Yarn 2), and Typescript crashes.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 6ce42fef-d78c-4805-893f-3773e684546c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.2
Bookmarks|ale|13.1.0
cucumberautocomplete|ale|2.15.1
vscode-zipfs|arc|2.3.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-jest-runner|fir|0.4.44
shell-format|fox|7.1.0
todo-tree|Gru|0.0.213
codeceptjs-gherkin-scaffold|jos|1.0.2
nodejs-repl|los|0.5.15
json-to-ts|Mar|1.7.5
openapi-lint|mer|1.2.0
vscode-docker|ms-|1.15.0
remote-containers|ms-|0.187.1
vsliveshare|ms-|1.0.4631
copy-json-path|nid|0.2.0
jest-cucumber-code-generator-extension|pio|1.0.2
vscode-yaml|red|0.22.0
eta-vscode|sha|1.0.0
mob-timer|son|1.5.1
har-viewer|unc|0.0.1

</details>

**Comment by mjbvz** [comment]
Are you using the custom built of TypeScript that yarn 2 sometimes configures?
