### ISSUE TITLE
Can't scroll in embeded terminal

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/vscode#12995]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.0.0

Steps to Reproduce:

1. Open an embeded terminal
2. Execute a command with a long result
3. Scroll with mouse to see result : the result will not moce

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11805
