### ISSUE TITLE
in Terminal I am not able to perform option+u key for nano text editor. How to do that...?? How to disable extra char inserting.

### ISSUE THREAD

**Issue by shekhars094** [microsoft/vscode#129925]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: MacOs Big Sur 11.3.1

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
