### ISSUE TITLE
VIsual Studio Code sign in web page loading

### ISSUE THREAD

**Issue by oopiooffioinolis** [microsoft/vscode#129944]
Issue Type: <b>Bug</b>

THe VS Code dign in web page does not stop loading no matter how long I wait.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.68GB free)|
|Process Argv|--crash-reporter-id 860407c0-618d-4d15-aab0-03ddf1ddf77d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.14
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
cpptools|ms-|1.5.1
quantum-devkit-vscode|qua|0.18.2107153439
java|red|0.80.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.1
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
vspre833:30321513
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
What sign in page are you talking about? Please share a screenshot

**Comment by oopiooffioinolis** [comment]
Microsoft account does not work, but GitHub does. 
![image](https://user-images.githubusercontent.com/88306662/127926894-83cd4ff2-c193-4713-8fbb-713965d5c3d7.png)

**Comment by TylerLeonhardt** [comment]
@oopiooffioinolis  can you provide the contents of the Microsoft Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by oopiooffioinolis** [comment]
![image](https://user-images.githubusercontent.com/88306662/128140709-42142d06-e494-416e-87e5-27ac8645b978.png)
 I couldn't find the Dev Tools part that you were referring to, but here's a screen shot of the search.
![image](https://user-images.githubusercontent.com/88306662/128141377-1aa8a8a1-7279-4ccf-a0b5-449b9eabd443.png)

**Comment by TylerLeonhardt** [comment]
@oopiooffioinolis its the second option "Toggle Developer Tools"

**Comment by oopiooffioinolis** [comment]
![image](https://user-images.githubusercontent.com/88306662/128290222-08e6c895-42bb-4ec2-9042-e7ca403ded1d.png)

**Comment by TylerLeonhardt** [comment]
Sorry can you share what's in the Console tab in Dev Tools?

**Comment by oopiooffioinolis** [comment]
Of course. Sorry, I'm new to this.
![image](https://user-images.githubusercontent.com/88306662/128294889-94a3b712-82e9-43eb-b504-c0dd3debdb2e.png)

**Comment by TylerLeonhardt** [comment]
@oopiooffioinolis I'm seeing a ton of issues making outbound network requests... how's your internet connection? Would you say it's pretty stable outside of VS Code?

Do you have any work policies/proxy settings applied on this machine?

**Comment by oopiooffioinolis** [comment]
I don't think so. I'm on a very stable home internet. I can play Minecraft on servers with no problem.

**Comment by oopiooffioinolis** [comment]
Also, the Github sign in option has always been working for the past weeks.

**Comment by TylerLeonhardt** [comment]
@oopiooffioinolis we just released a new version of VS Code on Thursday.

Did you get that update? Can you give it a try with that version?

**Comment by oopiooffioinolis** [comment]
It worked! Thank you so much for your help!
