### ISSUE TITLE
`LanguageDetectionService` is instantiated twice

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#129964]
Because it is both registered via `registerWorkbenchContribution` and as `registerSingleton`. This means the computation is running twice when enabled.

Imho the service part should be decoupled from the listener part.

**Comment by bpasero** [comment]
Forgot to mention: this only happens when you click on the language picker once. So maybe not so important after all.

**Comment by isidorn** [comment]
Good catch, I missed this.

**Comment by alexr00** [comment]
Closing since this has been merged into the release branch.

**Comment by TylerLeonhardt** [comment]
Verification steps:

* have setting on
* paste a large snippet into an untitled file to trigger language detection
* Open language picker
* Open dev tools

You should only see one instance of the log:
> Platform browser has already been set. Overwriting the platform with [object Object].
(this log comes from TFJS)
