### ISSUE TITLE
Latex in comments

### ISSUE THREAD

**Issue by robbiemu** [microsoft/vscode#129933]
I've been learning about ml in python for a few years now and it's become second nature for me to create the latex markup of the equation I need for a model in the cell above my code in a notebook. I work day to day in typescript, and I _really_ miss this pattern of behavior. 

The request: a feature to turn on /off inline (markdown with) Latex in comments (something like double clicking a comment with markdown or latex, or putting the cursor in the comment, would de-render it for editing).

I want this enough to probably contribute some weekends to get that extension. I barely know anything about extension writing though, I contributed exactly one pr to an extension so far. How involved would this be?

I am cognizant of the fact that jsdoc/tsdoc would probably already be much more inline-rendered by default if this wasnt difficult in some way. Why is it difficult?

**Comment by mjbvz** [comment]
Closing as out of scope for core VS Code but may be possible with some clever extension api usage
