### ISSUE TITLE
Unable to save file without extension for DockerFile

### ISSUE THREAD

**Issue by sunnyjamshedji** [microsoft/vscode#129906]
Issue Type: <b>Bug</b>

First day on the "job". Am trying to learn how to use Docker. The second page of the Docker tutorial (getting-started) tells you that your DockerFile needs to have no extension. Can't be DockerFile.txt. VSCode won't let me name it as such. Keeps deleting my file and renaming it to DockerFile.txt. I can't find a setting that disables this nor have I been able to find anything on the web.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (5.09GB free)|
|Process Argv|--crash-reporter-id 546711f9-9d9a-4073-9613-92020eb8cf8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.4
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-wsl|ms-|0.58.2
notepadplusplus-keybindings|ms-|1.0.7
vs-keybindings|ms-|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by bpasero** [comment]
There is an entry in the dropdown to save without extension.
