### ISSUE TITLE
truncated terminal fonts after upgrading to 1.58.2

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#129948]
Gitpod users reporting that terminals fronts are truncated after switching to 1.58.2: https://github.com/gitpod-io/gitpod/issues/5014

**Comment by hrithikrtiwari** [comment]
![image](https://user-images.githubusercontent.com/42163313/129154304-de708ace-166f-4d25-b4ba-131b20b376e4.png)

**Comment by Tyriar** [comment]
Brave's fingerprint prevention causes this as it blocks some canvas APIs https://github.com/xtermjs/xterm.js/wiki/FAQ#characters-are-getting-cut-off-in-the-terminal

**Comment by hrithikrtiwari** [comment]
Ohh yes I sometimes come across some online editors where the actual text displayed is good, but it is difficult to access them, like the cursor runs way further than the actual text

Thanks for addressing
