### ISSUE TITLE
Revisit: Search by file should show terminal tabs in the list

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#129956]
Follow up from https://github.com/microsoft/vscode/issues/128445

As the original author of that code, I had some rationale in mind when excluding non-file based editors from quick open search after you type. I am not 100% convinced yet that terminals should appear in the quick open list after you start typing. Let me try to explain:

The fact that editors appear in quick open by default is something we had from day one, way before we had dedicated pickers for editors specifically (and way before we had tabs). The idea back then was to provide a simple navigation model where you can jump between editors via quick open without having to use the mouse while still being able to jump through the history more than one step (similar to how Alt+Tab works in OS). As such, no filtering is applied here and all opened editors appear.

However, I never felt that non-file based editors should appear in the quick open list once you start searching, because this is specifically for searching for files and not for editors:

![image](https://user-images.githubusercontent.com/900690/127845987-2664f2b9-b7c9-4fa5-a916-10ac0585d102.png)

If you want to search for opened editors (including terminals), the more recent editors picker can be used instead:

![image](https://user-images.githubusercontent.com/900690/127846055-a2a03cad-45be-4fc4-908c-cb6308bd693c.png)

Another concern I have is that we now seem to be very inconsistent because terminals now appear in the search results, while other non-file based editors do not. So I think we should decide consistently whether non-file based editors should appear in quick open once you start searching or not.

//cc @Tyriar @meganrogge @misolori @roblourens

**Comment by misolori** [comment]
Is there any concern for allowing all non-file based editors to appear (which would include custom editors)? I'm not sure how many users would know about `?edt` for searching non-files. I'd guess that people think to search any "file" that is open.

**Comment by bpasero** [comment]
> I'm not sure how many users would know about ?edt for searching non-files.

Well, that is not the entry point for users. We have commands to "Search all editors" that will bring up this quick open. There is another command to search editors in the active group, so I think discoverability is not an issue.

> I'd guess that people think to search any "file" that is open.

A terminal is not a file though, right?

> Is there any concern for allowing all non-file based editors to appear (which would include custom editors)?

To give an example: using the SCM view you might pile up a lot of diff editors for outgoing changes. Unfortunately, even when you commit the changes, these editors do not close automatically. I bet it will be super frustrating to constantly see those stale diff editors in the result list when searching for the file.

**Comment by TylerLeonhardt** [comment]
So I made the change that I did because Terminals were showing up in Recently Opened:
![image](https://user-images.githubusercontent.com/2644648/128581542-2bf6c3dd-1e2b-43d1-87f9-9e374853e7ec.png)
So I allowed them to stay there when you filter.

it sounds like @bpasero you're more in the boat of.. they shouldn't have been there to begin with.

**Comment by TylerLeonhardt** [comment]
I've thought about some more and I agree with you @bpasero. For a couple reasons:

1.  We're specifically talking about `ctrl/cmd + p` here and as you've pointed out, the text calls out files
2. Terminals still show up when you `ctrl+tab` so they're still a keystroke away

**Comment by bpasero** [comment]
Yeah the editor history is not affected and should really list all editors to support the navigation case, but once you start a search we should limit the results to only editors from the history that show files.

**Comment by TylerLeonhardt** [comment]
and expanded here: https://github.com/microsoft/vscode/pull/210805
