### ISSUE TITLE
i m not getting red squiggle in my code

### ISSUE THREAD

**Issue by Mehlam589** [microsoft/vscode#129945]
Issue Type: <b>Feature Request</b>

I m not getting any red sqiuggles in my code pls help me to turn this.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo what language is your code? Did you use the "Start Extension Bisect" command from Command Palette to investigate whether one of your extensions is causing the problem?
