### ISSUE TITLE
Run all cells in a collapsed heading

### ISSUE THREAD

**Issue by ceronvgabriel** [microsoft/vscode#129996]
Hi, the functionality to run all the cells in a collapsed heading would be very helpful as you don't have to shift+enter all the cells you want to execute. We use this to set-up the kernel or run a specific part of the notebook. Other notebooks like colab have this feature.

**Comment by j2bbayle** [comment]
More generally, being able to run all cells from a certain section (as defined by the hierarchical structure of the notebook) would be very useful. Google Collab or Mathematica notebook offer this.

**Comment by DonJayamanne** [comment]
Thank you for this feature request, given that we haven't had enough upvotes for this feature I'm closing this as not planned.
