### ISSUE TITLE
Doesn't complete parenthesis

### ISSUE THREAD

**Issue by Mlocik97** [microsoft/vscode#129960]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-63-generic

Steps to Reproduce:

1. I create file.js, and write `console.log` when I press `(` on keyboard, it should automatically add `)` too, but it doesn't even when I set in settings it should always complete parenthesis.

**Comment by hediet** [comment]
Do you have copilot installed?

**Comment by Mlocik97** [comment]
it seems it was caused by copilot... but disabling extension doesn't help immediately, You need to restart VSCode too.

**Comment by hediet** [comment]
Closing as this is caused by copilot. We are working with them to fix that.
