### ISSUE TITLE
Outline Is Very Slow

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#129968]
* Create a file with 25k times the following line:
```
function bla() {}
```

* Unfold "Outline"
* Observe that it freezes the UI

![image](https://user-images.githubusercontent.com/2931520/127870445-f6c87211-df8b-4849-b7e0-1d964f4ab400.png)

This is already a problem in `TextBuffer.ts` - the outline makes typing/deleting noticeable slow.

**Comment by joaomoreno** [comment]
Observations:

1. This runs pretty quickly (300ms) for me in Code OSS.
2. It takes 4s when having 32k lines in Code Insiders.
3. It runs pretty quickly (300ms) in a fresh new Code Insiders.

Big culprit:

![image](https://user-images.githubusercontent.com/22350/135295547-924d5752-230b-4e9e-95b1-de027bc9b8a7.png)

Call tree:

![image](https://user-images.githubusercontent.com/22350/135295763-0a481f4b-ab2a-4703-89cd-89bceec694af.png)

[Profile-20210929T170504.zip](https://github.com/microsoft/vscode/files/7252986/Profile-20210929T170504.zip)

Given these findings, I have to forward this to you @jrieken. Let me know if you find that the performance bottleneck is in fact in the widget.

**Comment by jrieken** [comment]
@sandy081 for each element I check the config-service to know if its filtered or not, these filters are defined per language, e.g for Java interfaces might be filtered and for TypeScript its enum-members etc. I see that each call takes ~3ms and that sums up with many, many element. 

This is the call in question: https://github.com/microsoft/vscode/blob/f523f65f3985eb6493cae5d219de35f1d7ba6f7a/src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsOutline.ts#L102

Unsure if I can workaround but I believe one service-property of the configuration service should be speed 🙊

**Comment by hediet** [comment]
> Unsure if I can workaround but I believe one service-property of the configuration service should be speed 🙊

Cannot you just cache it and use configuration on change as invalidation?

**Comment by jrieken** [comment]
Thanks @sandy081

**Comment by joaomoreno** [comment]
Great job, thanks @sandy081!
