### ISSUE TITLE
Lua function colorizing error

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#12994]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
![qq 20160929191837](https://cloud.githubusercontent.com/assets/1836844/18951806/9ccdaa6c-8679-11e6-8d53-0301c79b44c0.jpg)

**Comment by aeschli** [comment]
This issue was moved to textmate/lua.tmbundle#7
