### ISSUE TITLE
Conda falsely added to end of PATH, not beginning like in normal terminal

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode#129979]
Issue Type: <b>Bug</b>

The VS code terminal adds `conda` folders to the end of PATH instead of the beginning (how it should be).

This means that conda doesn't work properly inside the VS code terminal, as the system python binary is used (if present) instead of conda's python binary.

It's basically this issue which was never resolved but closed due to being stale: https://github.com/Microsoft/vscode-python/issues/2969

The potential root cause could be that by default VS code starts shells with the `-l` flag for *login shell*.

The relevant code seems to be here. There's some link to UNIX stackexchange as an explanation, but it doesn't make much sense to me. Just removing the `-l` from defaults would fix the problem for me.

https://github.com/microsoft/vscode/blob/6a6c1195b81726d71c91118013f7293af13b5155/src/vs/platform/terminal/common/terminalPlatformConfiguration.ts#L148-L151

When I add the `-l` flag to my normal terminal, I get the same behaviour as within vs code's terminal.

So there are two possible things going on here:
1. I set up my terminal incorrectly to somehow just add conda path properly when not using a login shell
2. There's a conda bug that conda is added to path improperly in login shells
3. This is a vs code problem.

I set up my laptop fresh a few days ago, so this could well be due to some quirk in my setup, rather than intrinsic. But I wanted to raise this anyways.

I've reproduced the problem on Vanilla VS Code Insiders (this is where I'm reporting from now). But the same problem was also on customized normal VS code.

VS Code version: Code - Insiders 1.59.0-insider (104bc571e956e4af623905ef10dfcc8f0fdac625, 2021-07-30T13:27:22.525Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

I found this in default settings, could be the root cause, the problem is the same if I use fish (my default) or zsh.
```
	// The macOS profiles to present when creating a new terminal via the terminal dropdown. When set, these will override the default detected profiles. They are comprised of a `path` and optional `args`.
	"terminal.integrated.profiles.osx": {
		"bash": {
			"path": "bash",
			"args": [
				"-l"
			],
			"icon": "terminal-bash"
		},
		"zsh": {
			"path": "zsh",
			"args": [
				"-l"
			]
		},
		"fish": {
			"path": "fish",
			"args": [
				"-l"
			]
                },

	},
```

**Comment by corneliusroemer** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Conda Interpreter (#126405)](https://www.github.com/microsoft/vscode/issues/126405)

No this is not a duplicate since in my case Python the Python extension is not activated.

**Comment by tlambert03** [comment]
@corneliusroemer's suggestion of overriding the default `-l` flag works for me.  specifically, I added the following to my user settings:

```json
  "terminal.integrated.profiles.osx": {
    "zsh": { "path": "zsh", "args": [] },
    "bash": { "path": "bash", "args": [] },
  }
```

to the best of my ability, I can't find anything weird about my login shell setup (I don't have a custom `.zprofile`, etc)... so I don't understand why the default vscode settings aren't working for me.

**Comment by corneliusroemer** [comment]
The explanation for the behaviour described in this issue is already in the documentation: https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

The workaround I came up with is one of the possible two ones described:
>There are two direct fixes for this. The first is to set "terminal.integrated.inheritEnv": false, which will strip most environment variables from the terminal's environment, except for some important ones (like HOME, SHELL, TMPDIR, etc.).
>The other fix is to no longer run a login shell in the terminal by creating a terminal profile and setting its args to []. If you go with this fix, you will want to make sure any aliases in your profile scripts are moved over to your ~/.bashrc/~/.zshrc file since aliases only apply to the shell they're set in.


Thanks @Tyriar for pointing this out. Bit confusing that this is marked a duplicate though when it precedes the other issue ;)

**Comment by Tyriar** [comment]
The other issue had more activity is all 🙂

**Comment by tlambert03** [comment]
But now they're both closed :/
Fwiw, I just set up a brand new OS today, installed conda and vscode, and saw this issue.

**Comment by Tyriar** [comment]
There isn't really a fix for it that I can see, so this is more of a won't fix/as designed issue. Unless someone comes up with ideas that would fix it without breaking other things

**Comment by corneliusroemer** [comment]
To be honest, it's good that there is an explanation of the behavior in docs, but I don't understand the reasoning. I don't have the mangled path in my other terminals. In hyper I don't have any problem with conda paths. So why only in vs code?

The explanation given is that adding the `-l` flag makes the terminal behave more like Mac's default. But I don't see this at all. It's only vs codes terminal that has these problems for me.

Why is this not an issue for everyone using Mac? Do they all apply the workarounds? Or not notice that their path is mangled?

**Comment by Tyriar** [comment]
@corneliusroemer it's because Hyper is the root process, whereas for VS Code's terminal it's run underneath VS Code's process. You can try setting `terminal.integrated.inheritEnv` to `false` which may improve the situation but changing that will cause a bunch of other breakages for people at this point (I tried changing it and got a lot of reports so reverted).

> Why is this not an issue for everyone using Mac? Do they all apply the workarounds? Or not notice that their path is mangled?

I'm sure some people don't notice or it doesn't impact them.
