### ISSUE TITLE
Easy update and upgrade vscode portable use terminal or cmd.

### ISSUE THREAD

**Issue by amin007** [microsoft/vscode#129941]
https://code.visualstudio.com/docs/editor/portable
Easy update and upgrade vscode portable use terminal or cmd.
Like we git pull our coding from github or similer.

I'm used to using git to update new things in my coding.

i was wondering considering vscode is already in github.

wouldn't it be easier if you all use git pull to replace any file in vscode portable compared to a new install for vscode potabe.

I read https://github.com/microsoft/vscode/issues/85358 but it was locked.

**Comment by ashup99** [comment]
> https://code.visualstudio.com/docs/editor/portable
> Easy update and upgrade vscode portable use terminal or cmd.
> Like we git pull our coding from github or similer.
> 
> I'm used to using git to update new things in my coding.
> 
> i was wondering considering vscode is already in github.
> 
> wouldn't it be easier if you all use git pull to replace any file in vscode portable compared to a new install for vscode potabe.
> 
> I read #85358 but it was locked.

I am using linux and  use this command to update vscode:
sudo apt-get update
sudo apt-get install code
