### ISSUE TITLE
Clearing dedicated terminal for task results in initial blank line.

### ISSUE THREAD

**Issue by seraku24** [microsoft/vscode#129994]
Issue Type: <b>Bug</b>

1. Open an empty workspace/folder.
2. Use the following `tasks.json`:
```jsonc
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello",
            "presentation": {
                "echo": false,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": false,
                "clear": true
            },
            "problemMatcher": []
        }
    ]
}
```
3. Run the `echo` task once, which will reveal the dedicated terminal.
4. Run the task again.

**Expected:**
The output of the second run should be identical to the first.

**Actual:**
The second output has an empty line at the beginning.

*NOTE: Manually killing the terminal and running the task produces the expected output. The issue appears to only occur when there is an existing terminal for the task.*

VS Code version: Code - Insiders 1.59.0-insider (ba0df885e9d6b0f0ccf2cc714c3fa31423572205, 2021-07-31T00:41:55.692Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.45GB free)|
|Process Argv|--crash-reporter-id aad1c5c9-d96d-4ded-b865-f0c766cf74a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthrucf:30344902

```

</details>

**Comment by alexr00** [comment]
@Tyriar tasks does this to reuse a terminal:

https://github.com/Microsoft/vscode/blob/a707e282ead8337cb58c8a5277e6e358522776eb/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1287-L1292

I dug around a bit, and the issue seems to be related to the `\n` here:

https://github.com/microsoft/vscode/blob/e261d224599ee3e8bf479c108ac538b012db375c/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1370-L1371

I tried exposing the `reset` parameter on `reuseTerminal`, but that caused the terminal to just be empty. Is there anything I can do from the tasks side to fix this?

**Comment by Tyriar** [comment]
@alexr00 pushed a fix. Instead of using reset which was made for seamless relaunch, I made reuseTerminal return a promise so it would wait on the write calls to be parsed before returning. The issue was that your `clear` would run before `write` was parsed asynchronously on the next frame.

**Comment by seraku24** [comment]
Testing 1.60.0-insider (7c25c174726ab969db3f99058cdf24bcfae1cfbe), the issue appears to have been resolved.
