### ISSUE TITLE
Will not create valid - claims it is invalid

### ISSUE THREAD

**Issue by dalepres** [microsoft/vscode#129913]
Issue Type: <b>Bug</b>

Note that in the description below, init.py is supposed to have two underscores before the word init and two underscores after the word init but the editor on this page strips them.

From recent Flask documentation, the best practice pattern is a file named "__init__.py" for initializing and running a Flask app.  Visual Studio Code refuses to create a file named "__init__.py", claiming that it is an invalid file name.  Windows Explorer, of course, allows the file just fine and Code will work with the file, once created in Explorer.  Visual Studio Code should allow any valid file name that Windows allows.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (39.59GB free)|
|Process Argv|D:\\Dropbox\\RaspberryPI\\github\\firemote2021\\firemoteapi --crash-reporter-id f4983216-0f88-4a32-898a-6207e45bee18|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.6.832593372

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by gjsjohnmurray** [comment]
Not solving the problem, but one way of making the filename `__init__.py` to display in the Markdown GH uses is to enclose it in backticks.

**Comment by isidorn** [comment]
This works just fine for me.
Please update to latest vscode insiders and let me know if you can still repro. 

![Screenshot 2021-08-02 at 12 06 20](https://user-images.githubusercontent.com/1926584/127844559-df45d21e-0c11-4a6c-be7c-8fd0bb33cf10.png)

**Comment by isidorn** [comment]
![Screenshot 2021-08-02 at 12 07 03](https://user-images.githubusercontent.com/1926584/127844649-adaa2bfc-722b-4e49-8581-78b221107249.png)
