### ISSUE TITLE
rename using F2

### ISSUE THREAD

**Issue by mogaozq** [microsoft/vscode#129991]
Issue Type: <b>Bug</b>

I selected an html div tag and then pressed F2 key to rename the tag along with its closing tab, after entering a new name suddenly all div tags in all of my files in my project renamed to the new name. That was so wierd and critical bug. Fortunately I was using git VCS and I could undo all the changes in 147 files :D. 
Thanks, Moga.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (0.88GB free)|
|Process Argv|--crash-reporter-id 63fd5075-69a5-4e66-ad55-b8bb4f8c57a1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
es7-react-js-snippets|dsz|3.1.1
vscode-language-babel|mgm|0.0.31
csharp|ms-|1.23.14
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.22
lorem-ipsum|Tyr|1.2.0
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by aeschli** [comment]
The html mode does not rename across files. Can it be you were in a tsx file?

**Comment by mogaozq** [comment]
> The html mode does not rename across files. Can it be you were in a tsx file?

It was a react jsx file.

**Comment by mjbvz** [comment]
Please share example code that demonstrates the issue

**Comment by mjbvz** [comment]
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Closing as needs more info
