### ISSUE TITLE
Notebook initial loading improvement

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129932]
Currently when opening a notebook after the window is opened, we will try to activate all extensions whose activation event is `onNotebook:{VIEWTYPE}` synchronously, even if they are not accounted for serializing/deserializing the notebook. This caused a significant slow down of the first notebook opening. 

Now that we have the ipynb serializer is part of the core, we should ensure the notebook file opening is fast and not blocked by any extension.

What happens now when opening an ipynb file with multiple notebook extensions installed, one example:

![image](https://user-images.githubusercontent.com/876920/127788560-f43cf297-bcff-4e21-896d-ab99cde0d3e4.png)

It spent 3 seconds in loading and activating Jupyter, Kusto and Julia extensions.

## Proposal

- [ ] Upon request of opening a notebook, activate extension which contributes the exact notebook serializer and wait for it to finish.
  * Request deserialization of the notebook resource
- [ ]  Send activation events for `onNotebook:VIEWTYPE` and `onNotebook:*`, fire and forget, no `await`.
- [ ] Cell output render module should `activate` notebook extensions which contributes the impure notebook renderer prior to rendering the output.

**Comment by roblourens** [comment]
Good idea but wouldn't we need a new activation event for this?

**Comment by rebornix** [comment]
@roblourens my concern of introducing a new activation event is everyone will then use that one. Our activation event doesn't specific if it `await`s or not.

**Comment by rebornix** [comment]
However we don't have such a thing in activation events, we either fire and forget or awaits, there is nothing in between. Maybe we can introduce `onOpenNotebook`.

**Comment by rebornix** [comment]
We now wait for the serializer to be registered on notebook file open but don't wait for other extensions to finish activation on `onNotebook`.
