### ISSUE TITLE
VS Code window does not (re)initialize on load; dead - regression?

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#129915]
Issue Type: <b>Bug</b>

Sometimes Visual Studio hangs effectively dead in an unitialized zombie state when
* switching an existing instance (window) to a different "scope" (folder, workspace)
* creating a new empty window
* opening a scope in a new window

I am unable to *reliably* reproduce the problem; the problem occurs very frequently for me when simply doing
* load vscode (previous workspace restores fine)
* Ctrl+Click on existing folder / workspace entry in File -> Open Recent ...

Very frequently this results in a new window of vscode opening, but this window has been not initialized correctly. 

The menu bar in the new window does show up typically, but the menu items do not seem to be wired up (this makes it impossible to click Help -> Report Issue from that instance...)

The new window is also bare, i.e. none of the UI elements initializes - no icon bar on the left, no explorer, no code editor, no terminal - nothing.

In the past, I used to be able to run quite a few *windows* of vscode in parallel (e.g. "the products", global CI definition, infra-as-code, etc), but this usage pattern is seriously impacted now.

Once the zombie mode is there, it is not possible to launch usable new windows; the existing window continues to work fine, as long as the window does not need to reinitialize with, say, a different workspace.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.13.5-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.31GB (23.86GB free)|
|Process Argv|--unity-launch --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.6.0
rust-analyzer|mat|0.2.686
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
powershell|ms-|2021.6.2
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
vscode-yaml|red|0.22.0
vscode-lldb|vad|1.6.5
debug|web|0.25.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by shoffmeister** [comment]
I'll try to trim the extensions a bit, in the hope that some largely unused ones cause the problem.

**Comment by hediet** [comment]
Maybe #129920 is related.

**Comment by deepak1556** [comment]
Can you try to reproduce with our nightly insider builds ? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
