### ISSUE TITLE
Abnormal usage of cpu and memory

### ISSUE THREAD

**Issue by shadowmimosa** [microsoft/vscode#130010]
Issue Type: <b>Performance Issue</b>

After opening for a few hours, the memory and CPU usage soared. 
It started suddenly a few days ago and no new plug-ins were installed.

![image](https://user-images.githubusercontent.com/38422761/127941776-78d1953d-764a-4191-b5f2-99f4a6263472.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-240.1.1.el8_3.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (0.23GB free)|
|Process Argv|C:\\Users\\ShadowMimosa\\Documents\\Repos\\DongDian\\DongdianUnrar --crash-reporter-id 3f8c4c87-0f92-4c20-90e7-a996e36f35a7|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: dd_db|
|OS|Linux x64 4.18.0-240.1.1.el8_3.x86_64|
|CPUs|AMD EPYC 7K62 48-Core Processor (4 x 2595)|
|Memory (System)|15.46GB (0.16GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    57	  7560	code main
    0	     1	  7276	   crashpad-handler
    0	    81	 10628	   gpu-process
    1	  1616	 13424	   window (卡顿.md - DailyNotes - Visual Studio Code)
    0	     2	 12612	     watcherService 
    0	     0	  5608	       console-window-host (Windows internal process)
    0	    80	 17076	     extensionHost
    0	     1	 86012	     searchService
    0	    44	 17152	   shared-process
    0	    12	 10012	     ptyHost
    0	    23	  5076	       "C:\Program Files\PowerShell\7-preview\pwsh.exe"
    0	     5	 29580	         "C:\Windows\py.exe"
    0	     0	 28896	           C:\Users\ShadowMimosa\AppData\Local\Programs\Python\Python39\python.exe
    0	     1	  6220	       console-window-host (Windows internal process)
    0	     0	 14180	       console-window-host (Windows internal process)
    0	    24	 20208	       "C:\Program Files\PowerShell\7-preview\pwsh.exe"
    0	     0	 86276	         "C:\Windows\py.exe"
    0	     0	 86216	           C:\Users\ShadowMimosa\AppData\Local\Programs\Python\Python39\python.exe
    0	     0	 33244	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\SHADOW~1\AppData\Local\Temp\vscode-linux-multi-line-command-dd_db-168727111.sh" | ssh -T -L 127.0.0.1:12457:127.0.0.1:35989 dd_db bash) & exit /b 0
    0	     2	 35204	         ssh  -T -L 127.0.0.1:12457:127.0.0.1:35989 dd_db bash
    0	     1	 33904	       console-window-host (Windows internal process)
    0	     5	 20048	   utility
    2	  1651	 20396	   window (v4.py (索引) - DongdianUnrar - Visual Studio Code)
    0	     2	 15700	     watcherService 
    0	     0	 19744	       console-window-host (Windows internal process)
    0	   122	 20280	     extensionHost
    0	     3	  8212	       electron_node bundle.js 
    0	    63	 26644	   window (Visual Studio Code)
    0	    16	 30768	     extensionHost
    0	  2352	 31460	   window (temp.md - Secret - Visual Studio Code)
    0	    72	 26648	     extensionHost
    0	    10	 31952	     watcherService 
    0	     0	 27400	       console-window-host (Windows internal process)
    0	    67	 39464	   window (问题报告程序)

Remote: SSH: dd_db
CPU %	Mem MB	   PID	Process
    0	     0	1807901	remote agent
    0	     0	1807972	   ptyHost
    0	     0	1808040	     /bin/bash
    0	     0	1808134	       mysql -uroot -px xxxxxxxxxxxxxx
    0	     0	1808019	   extensionHost
    0	     0	1974400	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (temp.md - Secret - Visual Studio Code)
|  Window (卡顿.md - DailyNotes - Visual Studio Code)
|  Window (v4.py (索引) - DongdianUnrar - Visual Studio Code)
|    Folder (Secret): 26 files
|      File types: md(19) pdf(2)
|      Conf files:
|    Folder (DongdianUnrar): 1305 files
|      File types: py(661) dll(222) gz(148) exe(49) pyc(26) pyd(15) ini(11)
|                  h(11) 1(11) rdb(10)
|      Conf files:
|    Folder (DailyNotes): 643 files
|      File types: md(504) pdf(11) html(3) txt(2) py(2) gitignore(1) json(1)
|                  xml(1) php(1) webp(1)
|      Conf files: settings.json(1)
|  Remote: SSH: dd_db;
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.7.1
code-gnu-global|aus|0.2.2
transformer|dak|1.11.2
dart-code|Dar|3.25.0
flutter|Dar|3.25.0
vscode-markdownlint|Dav|0.43.1
jquerysnippets|don|0.0.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
shell-format|fox|7.1.0
go|gol|0.26.0
gc-excelviewer|Gra|3.0.42
beautify|Hoo|1.5.0
latex-workshop|Jam|8.19.2
vscode-leetcode|Lee|0.18.0
vscode-clang|mit|0.2.4
vscode-language-pack-zh-hans|MS-|1.58.8
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.8.0
git-file-history|pom|1.0.1
vscode-data-preview|Ran|2.3.0
java|red|0.80.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.22
open-in-browser|tec|2.0.0
codelf|unb|11.7.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.2
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.1
vscode-wakatime|Wak|14.0.3
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by hediet** [comment]
This is most likely due to a slow/memory-intensive extension.

Can you try to reproduce this with all extensions disabled?

**Comment by shadowmimosa** [comment]
It takes several hours to appear. It's troublesome to reproduce.

Just two days ago, there was a cpu spike when starting vscode, which was solved by disabling some suspicious extensions.
Now I'm left with some basic extensions that I've been using for a long time and never had these problems before.

Is there any way to see the resource usage of the extensions?

**Comment by hediet** [comment]
> Is there any way to see the resource usage of the extensions?

Yes: F1 -> Show Running Extensions

**Comment by shadowmimosa** [comment]
> > Is there any way to see the resource usage of the extensions?
> 
> Yes: F1 -> Show Running Extensions
This method does not see resource occupancy.

It seems normal for me to view it in Help > Open Process Explorer

**Comment by shadowmimosa** [comment]
![image](https://user-images.githubusercontent.com/38422761/128303049-a3414b38-7f49-4207-b5f5-f62cf58d4130.png)

![image](https://user-images.githubusercontent.com/38422761/128303203-1fe0d0a8-6db1-4f42-8c17-5eb9b02e0041.png)

How can I continue the investigation

**Comment by deepak1556** [comment]
Please provide the output of following

```
Get-WmiObject win32_process -Filter ProcessId=<PID>
```

Replace `<PID>` with process id that is showing high cpu usage in the task manager.

**Comment by shadowmimosa** [comment]
> Please provide the output of following
> 
> ```powershell
> Get-WmiObject win32_process -Filter ProcessId=<PID>
> ```
> 
> Replace `<PID>` with vscode process id that is showing high cpu usage in the task manager.

There are many processes, one of which is selected

```powershell
__GENUS                    : 2
__CLASS                    : Win32_Process
__SUPERCLASS               : CIM_Process
__DYNASTY                  : CIM_ManagedSystemElement
__RELPATH                  : Win32_Process.Handle="123428"
__PROPERTY_COUNT           : 45
__DERIVATION               : {CIM_Process, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                   : SHADOWMIMOSA
__NAMESPACE                : root\cimv2
__PATH                     : \\*\root\cimv2:Win32_Process.Handle="123428"
Caption                    : Code.exe
CommandLine                : "C:\*\Microsoft VS Code\Code.exe" --type=renderer --disable-color-correct-rendering --field-trial-handle=1508,5853398100495482051,17627850152675632329,131072 --disab
                             le-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand --lang=zh-CN --user-data-dir="C:\User
                             s\*\AppData\Roaming\Code" --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webvie
                             w,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --app-user-model-id=Microsoft.VisualStudioCode --app-path=
                             "C:\*\Microsoft VS Code\resources\app" --no-sandbox --no-zygote --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-clien
                             t-id=24 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=7012 /prefetch:1 --vscode-window-config=vscode:153a80da-d3d8-4ef8-8271-6cfddc5bcec7
CreationClassName          : Win32_Process
CreationDate               : 20210810160051.474587+480
CSCreationClassName        : Win32_ComputerSystem
CSName                     : **
Description                : Code.exe
ExecutablePath             : C:\*\Microsoft VS Code\Code.exe
ExecutionState             : 
Handle                     : 123428
HandleCount                : 713
InstallDate                : 
KernelModeTime             : 5645468750
MaximumWorkingSetSize      : 1380
MinimumWorkingSetSize      : 200
Name                       : Code.exe
OSCreationClassName        : Win32_OperatingSystem
OSName                     : Microsoft Windows 10 专业版|C:\WINDOWS|\Device\Harddisk0\Partition2
OtherOperationCount        : 125188
OtherTransferCount         : 3553538
PageFaults                 : 64093825
PageFileUsage              : 1812732
ParentProcessId            : 80440
PeakPageFileUsage          : 1896148
PeakVirtualSize            : 2262570299392
PeakWorkingSetSize         : 1786772
Priority                   : 4
PrivatePageCount           : 1856237568
ProcessId                  : 123428
QuotaNonPagedPoolUsage     : 170
QuotaPagedPoolUsage        : 822
QuotaPeakNonPagedPoolUsage : 404
QuotaPeakPagedPoolUsage    : 849
ReadOperationCount         : 1024363
ReadTransferCount          : 9212991356
SessionId                  : 1
Status                     : 
TerminationDate            : 
ThreadCount                : 22
UserModeTime               : 76632812500
VirtualSize                : 2254806441984
WindowsVersion             : 10.0.19043
WorkingSetSize             : 1709068288
WriteOperationCount        : 347969
WriteTransferCount         : 5436494201
PSComputerName             : **
ProcessName                : Code.exe
Handles                    : 713
VM                         : 2254806441984
WS                         : 1709068288
Path                       : C:\*\Microsoft VS Code\Code.exe
```

**Comment by lorand-horvath** [comment]
I confirm this issue with latest version 1.59.0, please see issue #130807

**Comment by deepak1556** [comment]
Thanks for the log, can you attach performance profile following these steps

* Launch vscode normally
* Open Command Palette and run `Toggle Developer Tools`
* Choose Performance tab
* Hit the reload and record button
* Perform the steps that show increased cpu usage
* Attach the generated trace

**Comment by lorand-horvath** [comment]
@deepak1556 So I've performed the steps you mentioned up until the "reload and record" when the CPU immediately went up to 100% on all cores and stayed there for quite a few minutes, so I couldn't do much - I had to close the vscode developer tools.
But I've noticed in the console an error, even if I restart vscode, I think it might have to do something with the slowness:

> (node:3880) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
_logExtensionHostMessage @ localProcessExtensionHost.ts:512
(anonymous) @ localProcessExtensionHost.ts:282
emit @ events.js:315
emit @ internal/child_process.js:903
processTicksAndRejections @ internal/process/task_queues.js:81

**Comment by lorand-horvath** [comment]
@deepak1556 Can you please check the issue I opened, I have more details in it #130807

**Comment by lorand-horvath** [comment]
@deepak1556 Are you using mongoose? Please see https://github.com/Automattic/mongoose/issues/10349

**Comment by shadowmimosa** [comment]
![image](https://user-images.githubusercontent.com/38422761/131424359-1cd69e63-3089-44c5-b999-d40a49975ff1.png)

How do I get this process information?
