### ISSUE TITLE
debugService shuold not have initializingOptions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#130094]
`initializingOptions` should not live on the `debugService`. Could we somehow get rid of that, or move it to the `debugSession` side? 
If I understand correctly this is only used to now show the debug toolbar when the session is initialising for this simpleUI. Maybe we could achieve that in some nicer way?

**Comment by weinand** [comment]
I think @roblourens had [this problem](https://github.com/microsoft/vscode/pull/128801#pullrequestreview-707928914) with our code:
> ...  the launch config  ...  hasn't been resolved to a full debug session. We want to change the debug UI as soon as possible, so we have to expose the options from the new launch config somehow ... once debugging has started I would get it from the DebugSession, but that doesn't exist yet, so at this stage it has to be exposed in a different way.

@isidorn do you have a suggestion how Rob could tackle this without using the `DebugService`?

**Comment by isidorn** [comment]
Yeah I see the problem.
I am not sure what is the best solution here. I see a couple of options:
1) Leave things as they are
2) Change the creation of debug session, such that an placeholder debug session is immediately created in initialisation state, and only later the launch config is fed in
3) Simply do not enter `initialisation` state for simple debug UI

**Comment by roblourens** [comment]
I think 2 feels like the best option to me, but I have no idea whether it would be a disruptive change to have a "placeholder" debugsession. 3 is probably easier but I don't know what all that state is used for.

**Comment by isidorn** [comment]
Yes 2 might be disruptive and turn out to be the most engineering work.
For 3: initialisation state is used to prevent starting another debug session, to render the debug toolbar and to render the spinner in the debug viewlet. Arguably none of those you need.

**Comment by weinand** [comment]
I prefer 1 because that involves the least amount of risk and I can live with the `initializingOptions` on the debugService.

**Comment by roblourens** [comment]
I would be happy with that too 😁

**Comment by isidorn** [comment]
Then let's go with 1.
Closing this for now, and in the future we can clean this up if we feel motivated.
