### ISSUE TITLE
White patches/lines all over files

### ISSUE THREAD

**Issue by RobJLeonard** [microsoft/vscode#130047]
These white lines appear on every file I open.
![image](https://user-images.githubusercontent.com/29282915/128033415-5ce85529-c199-4439-b4dd-bc68e344e7b6.png)

**Comment by hediet** [comment]
I'm sorry, I cannot see white patches/lines in the screenshot.

Maybe it is an hardware issue? 😉

**Comment by IllusionMH** [comment]
Doesn't looks like uploaded screenshot displays any problem, however from title/description it looks like duplicate of #124226

**Comment by RobJLeonard** [comment]
Just looked at that screenshot on a different machine and I don't see the lines either. Must be some issue with my machine. 
Here's an image taken on my phone for context (and to prove I'm not making this up 😅)
![IMG_20210804_085112](https://user-images.githubusercontent.com/29282915/128143863-51e4ce0e-d75e-4cd6-9396-2adbb9f503ab.jpg)

**Comment by IllusionMH** [comment]
It is HDR screen?
Is it reproducible if you start VS Code with `--disable-gpu` flag?

**Comment by hediet** [comment]
> Must be some issue with my machine.
Here's an image taken on my phone for context (and to prove I'm not making this up 😅)

Wow, very interesting that this issue reproduces in screenshots for you :D

I think this proves that this is not a VS Code issue, but also affects your browser?

**Comment by RobJLeonard** [comment]
Yeah I've tried with ` --disable-gpu` flag and the problem persists.

Very strange alright but I'm going to close this issue as it doesn't seem to be an issue with VS Code. 
Going to try updating drivers and reinstalling but any other fix suggestions very welcome!

Thanks for taking a look :)

**Comment by RobJLeonard** [comment]
Side note: In the meantime I've switched to a slightly lighter theme which doesn't this issue
