### ISSUE TITLE
Enhance workspacePlatform context key for web cases

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#130004]
The `workspacePlatform` context key is currently the remote's platform in cases where there is a remote, or the window's platform otherwise. It should instead be `webworker` when the only available host is the webworker extension host, and the window's platform otherwise. This is needed for cases where walkthrough content depends on ability to run extensions / what platform the extensions will be running on.

cc @alexdima for tips on how this can be detected

**Comment by DivonilLiquid** [comment]
Hey admin, i have recently started with open source contributions , can you assign this task to me so that i can learn the process.

**Comment by JacksonKearl** [comment]
@DivonilLiquid I actually already completed this, so I will be closing it out. In the future, you should look for issues with the "good-first-issue" label.

**Comment by alexdima** [comment]
@JacksonKearl What did you end up doing here? (I don't see any linked commits)

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/blob/25ce48dd797f15ee8099ef37281218c7ad3a3c17/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts#L252-L283

I will create a testplan item for this as it is a bit more involved (multiple platforms should be tested)
