### ISSUE TITLE
Multiple terminal windows do not restore correct session

### ISSUE THREAD

**Issue by nspyke** [microsoft/vscode#130003]
Issue Type: <b>Bug</b>

Using a remote SSH connection, I open two tabbed terminal windows (full screen/new UI style).
Clicking away to work other file tabs, then click back on the first open terminal tab and it shows the second terminal session. 
Click back to any other tab and then back to the first terminal tab and it then comes with the correct session of the first terminal tab

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.31.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.21GB free)|
|Process Argv|--crash-reporter-id 06d148aa-d546-4218-9113-e3a94665824c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: confbox|
|OS|Linux x64 3.10.0-1160.31.1.el7.x86_64|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (2 x 2903)|
|Memory (System)|3.70GB (1.20GB free)|
|VM|50%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-ruby|win|0.28.0
cucumberautocomplete|ale|2.15.1
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-kafka|jep|0.13.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
vscode-xml|red|0.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723cf:30346311

```

</details>

**Comment by meganrogge** [comment]
Please provide a gif of this happening. I'm not sure what you mean
