### ISSUE TITLE
[loc][Query] Possible typo in source

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#13008]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Select the default behaviour of InAppBrowser when opening using the <em>_blank</em> target

Open in a new window: <em>_system</em> target

File available here:
[https://github.com/Microsoft/cordova-simulate/blob/6ad0bd9bae9c78418db484e4796a4e04883659ef/tools/i18n/xliff/ru.xlf]

Query:
The word "target" seems to be out of place. Is this a typo? If not, can you please clarify how connects to the rest of the sentence? Thank you!

**Comment by bpasero** [comment]
This string does not appear to be in our sources.

**Comment by mkyjakova** [comment]
Hi, yes, sorry, I pasted this to the wrong place. closing the bug
