### ISSUE TITLE
high cpu consume

### ISSUE THREAD

**Issue by GiveMe-A-Name** [microsoft/vscode#130011]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2 (Universal)
- OS Version: macOS Big Sur 11.4(M1)

Steps to Reproduce:

1. I open a workspace that add three folders in a vscode window.
2. the vscode has high cpu consume

![image](https://user-images.githubusercontent.com/58852732/127945787-c59a23f3-4999-429f-8a84-dbda575ec4fa.png)

![image](https://user-images.githubusercontent.com/58852732/127945834-c25f8959-1b01-4869-b303-7405b392d3d0.png)

![image](https://user-images.githubusercontent.com/58852732/127945811-1e32cae6-f3f0-4ede-85dd-aa444b93f7c3.png)

**Comment by roblourens** [comment]
This is the process that runs searches. Did you trigger a search? If not, an extension could have. See this page for some details

**Comment by GiveMe-A-Name** [comment]
> This is the process that runs searches. Did you trigger a search? If not, an extension could have. See this page for some details

I disabled all the extensions, But it is  still high cpu consumes when I open the workspace.
I just open the workspace, and do nothing. I have no idea how I search the process that runs searches

**Comment by GiveMe-A-Name** [comment]
> This is the process that runs searches. Did you trigger a search? If not, an extension could have. See this page for some details

it trigger the process, when I put the folders and workspace file in same directory.

![image](https://user-images.githubusercontent.com/58852732/128111231-9317f199-5ff0-4d96-9f9f-91c39049070e.png).

it not run the process that runs searches, when I put the folders and workspace in different directory.

Is that the reason? I'm not sure

**Comment by roblourens** [comment]
You can see the steps on this page to get logs to see what triggered the search https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by GiveMe-A-Name** [comment]
> You can see the steps on this page to get logs to see what triggered the search [microsoft/vscode/wiki/Search-Issues](https://github.com/microsoft/vscode/wiki/Search-Issues)

thanks for your help.
This time, I disabled all extension. And again, there's nothing to open with it.
here is  the `code --status` informations 
```shell
Version:          Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS Version:       Darwin arm64 20.5.0
CPUs:             Apple M1 (8 x 24)
Memory (System):  16.00GB (1.78GB free)
Load (avg):       3, 4, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id c2d1eebe-7647-4279-94a2-b71670296ed1
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    2      131    6818  code main
    0       66    6821     gpu-process
    0       33    6823     utility
    1      262    6824     window (欢迎使用 — iceworks-lab (工作区))
    0      115    7080       extensionHost
    0       49    7081       watcherService
    0       49    7090       searchService
   46       16    7120         electron_node package.js 
   46        0    7122         electron_node package.js 
    0      147    7079     shared-process
    0       49    7083       ptyHost
    0        0    7084         /bin/zsh -l
    0        0    7397           bash /usr/local/bin/code --status
    6       49    7407             electron_node cli.js 
    0       33    7082     utility

Workspace Stats: 
|  Window (欢迎使用 — iceworks-lab (工作区))
|    Folder (adp): 813 files
|      File types: js(293) map(243) ts(153) json(25) ejs(6) tsx(5) md(3)
|                  log(3) tsbuildinfo(2) yml(2)
|      Conf files: package.json(2) tsconfig.json(2)
|    Folder (builder-gog-lint-tbfed): 193 files
|      File types: json(12) js(10) md(3) gitignore(2) eslintignore(1)
|                  npmignore(1) html(1) css(1) jsx(1) DS_Store(1)
|      Conf files: package.json(2)
|    Folder (iceworks-idp): 1129 files
|      File types: js(316) map(257) ts(171) tsx(95) scss(61) json(42) ejs(6)
|                  log(4) md(3) tsbuildinfo(2)
|      Conf files: package.json(2) tsconfig.json(2)

```
