### ISSUE TITLE
Ctrl + F4 can't close a pinned editor

### ISSUE THREAD

**Issue by vwjh37** [microsoft/vscode#130085]
Issue Type: <b>Bug</b>

1. Open VS Code,
2. Pin an editor, 
3. Activate that editor,
4. Press Ctrl + F4,

actual result: that editor is not closed.
expected result: that editor is closed.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Test plan #107464 suggested users wanting tabs to close even if pinned should set a keybinding for `workbench.action.closeActivePinnedEditor`

cc @bpasero

**Comment by vwjh37** [comment]
Oh, it is ok. But it is odd that there are two different commands to close an active editor and to close a pinned editor. Why to differ them?
Another similar question is why there is no a command to close all pinned editors? You know the command, close all editors, can't close any pinned editor, I have to close the pinned editors one by one, or unpin them first then execute close all editors to close them all.
