### ISSUE TITLE
Expose route to set formatting options

### ISSUE THREAD

**Issue by anfomin** [Microsoft/vscode#1300]
I've configured VS Code to always use tabs:
```json
// Place your settings in this file to overwrite the default settings
{
	"editor.insertSpaces": false
}
```

But C# **Format Code** command (Shift+Alt+F) always replaces tabs with spaces. I'm using OS X El Capitan.

**Comment by jrieken** [comment]
This is because OmniSharp doesn't support per request formatting options (https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/Models/v1/FormatRangeRequest.cs#L6). Moving to OmniSharp for that.

**Comment by jrieken** [comment]
@anfomin - Do workaround this, you can create an `omnisharp.json` with the config

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#366
