### ISSUE TITLE
Odd lint error when changing type in our dts

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#130073]
I was changing:

```ts
export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceNewSession: true }): Thenable<AuthenticationSession>;
```
to
```ts
export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceNewSession: true | { detail: string } }): Thenable<AuthenticationSession>;
```

And I got this strange lint error:
![image](https://user-images.githubusercontent.com/2644648/128097757-cd7fd907-fe23-4d1b-a978-98b86366f543.png)

coming from this custom rule:
https://github.com/microsoft/vscode/blob/37a8fe959ca35e7c0ef00ac119bea0034aaa0bda/build/lib/eslint/vscode-dts-literal-or-types.ts

Is there something actually wrong with my dts additon or is this a bug in the rule?

my workaround is to export two functions:
```ts
export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceNewSession: true }): Thenable<AuthenticationSession>;
export function getSession(providerId: string, scopes: readonly string[], options: AuthenticationGetSessionOptions & { forceNewSession: { detail: string } }): Thenable<AuthenticationSession>;
```

cc @mattbierner

**Comment by jrieken** [comment]
Yeah, that lint rule's selector needs some tweaking I guess.
