### ISSUE TITLE
inbuilt emmet is completely wiped out from vs code.

### ISSUE THREAD

**Issue by ankit-kaushik22** [microsoft/vscode#130078]
Issue Type: <b>Performance Issue</b>

hlo , i am using vs code editor for one week . And the emmet extension show some problem then there a option comes in the lower right ( i don't remember what was it but i suddenly click on it and after that emmet is completely wiped out from vs code.  i tried to find out but it was not even  "setting>extension" 
also in setting.json file "emmet.triggerExpansionOnTab": "true",
  "emmet.expandAbbreviation": "true"
are show like they are not recognised by vs code.
whenever i push tab to expand abbreviation . it show a massage like this
"command 'emmet.expandAbbreviation' not found"
i download the vs code again but   maybe due to setting sync it do the same (no emmet at all)  plz help me .

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 6.1.7600
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.90GB (0.67GB free)|
|Process Argv|--crash-reporter-id 0aa4467c-80c2-4a4c-974a-afc1ff47c1f1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    49	  2984	code main
    0	   110	   808	   "C:\Users\HHH\AppData\Local\Google\Chrome\Application\chrome.exe" --single-argument https://aka.ms/vscode-settings-sync-help
    0	    13	   616	     utility
    0	     0	   628	       
    0	     0	   704	       
    0	     6	  1088	     crashpad-handler
    0	   101	  2096	     window (undefined)
    0	    42	  2572	     window (undefined)
    0	   149	  3028	     window (undefined)
    0	    12	  3088	     utility
    0	    61	  4924	     gpu-process
    0	    30	  5088	     utility
    0	     2	   872	   crashpad-handler
    0	   143	  2156	   window (Welcome - setting - Visual Studio Code)
    0	    44	  1904	     extensionHost
    0	     8	  3172	       "C:\Users\HHH\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\HHH\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=1904
    0	    26	  4696	       "C:\Users\HHH\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\HHH\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=1904
    0	    28	  4936	     searchService
    0	    43	  3292	   shared-process
    0	     5	  4312	     ptyHost
    1	    50	  3848	   window (Issue Reporter)
    0	    21	  4604	   gpu-process
    0	    14	  5052	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - setting - Visual Studio Code)
|    Folder (setting): 2 files
|      File types: html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.7.6

</details>

**Comment by rzhao271** [comment]
If you go into the extensions view (Ctrl+Shift+X) and then search `@builtin`, is Emmet disabled?

**Comment by ankit-kaushik22** [comment]
> If you go into the extensions view (Ctrl+Shift+X) and then search `@builtin`, is Emmet disabled?

yes, it was disabled.. but now i enabled it  . thanks for this help. it just save my life.

**Comment by rzhao271** [comment]
No problem. I noticed there have been a few issues where Emmet seems to have disabled itself, and I'm not sure what causes that @sandy081

**Comment by sandy081** [comment]
I do not think an extension can be disabled automatically unless user triggers it.
