### ISSUE TITLE
Show path hints for files with same names across all editor groups

### ISSUE THREAD

**Issue by Maxpxt** [microsoft/vscode#130081]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2 (system setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a workspace with two folders, `foo` and `bar`, each containing a file `hello.txt`
2. Open two editor tabs, one for `foo/hello.txt` and one for `bar/hello.txt`. At this point, the editor tabs show path hints `foo` and `bar`, respectively, since both tabs have the same name, `hello.txt`:

![single](https://user-images.githubusercontent.com/19475500/128123554-4b49d702-0f22-439a-b96a-8f4c033255cd.png)

3. Move the editors into different groups (e.g. vertical split). When in different groups, the tabs no longer show the path hints, so is no longer possible to tell which is which by looking at the titles:

![split](https://user-images.githubusercontent.com/19475500/128123909-71dda6cb-2166-4fee-9222-c5aeb58f9211.png)

The expected behavior is for the path hints to be shown even if the tabs are in different groups.

Also, note that the list of open editors (see the top division of the explorer view in the images above) does correctly show the path hints even when the editors are in different groups.

**Comment by bpasero** [comment]
As a workaround you can play with the `workbench.editor.labelFormat` setting which allows you to always enable the name of the parent folder to appear in the tab label.
