### ISSUE TITLE
Web: httpWebWorkerExtensionHostIframe cannot be loaded

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130027]
`Playwright ERROR: HTTP status 404 for https://vscodeweb.azureedge.net/insider/c3d05cecd76bcffff8a5061f2d6e09753affdde2/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=434e92a6-8bd2-4dc9-92d7-6f8301c13468
   `

Both for running `yarn web` and in the builds: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=129771&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=49

**Comment by mjbvz** [comment]
Hey @bpasero are you still seeing this issue? I believe saw it yesterday but just pulled and everything seems to be working now

With `yarn web`, I see that file served from:

```
http://localhost:8081/static/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=b403dd43-f7d9-4e8e-a323-30798376fa79
```

**Comment by bpasero** [comment]
@connor4312 did you fix this?

**Comment by connor4312** [comment]
Yep, I broke it and fixed it.

**Comment by bpasero** [comment]
Still seeing this in our web smoke tests though:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=130141&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=73

**Comment by connor4312** [comment]
Huh, maybe this isn't related to the change I made? 🤔  It looks like https://vscodeweb.azureedge.net/insider/b96644b15f9f28e9bd3906f1f096389617de2f82/out/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html 404's -- how does that get uploaded, and is the upload failing?

**Comment by bpasero** [comment]
I am not sure, is this file being uploaded as part of the build in a later stage maybe? Then this could well be an explanation because the test runs before that happens.

Not sure if this is a big deal actually, in the end the tests are not failing, but just print this error.

**Comment by connor4312** [comment]
Ok, I found one thing in distro that I needed to update as well, but I don't think that gets around or affects the 404. @mjbvz do you know how this file gets published?

**Comment by mjbvz** [comment]
I also don't see the webview bits on the cdn: 

https://vscodeweb.azureedge.net/insider/b96644b15f9f28e9bd3906f1f096389617de2f82/out/vs/workbench/contrib/webview/browser/pre/main.js

I believe the files are published with `upload-cdn`: https://github.com/microsoft/vscode/blob/3070165ff25834d43fb0637ac83f84a903e1dc84/build/azure-pipelines/upload-cdn.ts#L6

Right now  I can't tell if anything is being published. Let me see if I can check azure

**Comment by bpasero** [comment]
Yeah feel free to close, this does not seem to cause issues. But be aware that any tests depending on this will fail.

**Comment by joaomoreno** [comment]
Why would the Desktop product use bits from the web?

**Comment by joaomoreno** [comment]
Ping @mjbvz @connor4312

**Comment by mjbvz** [comment]
@joaomoreno For the webview at least, we don't use web bits on desktop except when you are running the web tests.  I don't have much context on `httpWebWorkerExtensionHostIframe` however so I'm not sure what the story is here

**Comment by alexdima** [comment]
👋 Hey, sorry to be late to the party. 

The base url for `httpWebWorkerExtensionHostIframe.html` is determined by a combination of flags:
* from the embedder API: `__uniqueWebWorkerExtensionHostOrigin`, `webWorkerExtensionHostIframeSrc`.
* from `product.json` (`IProductService`): `webEndpointUrlTemplate`, `webEndpointUrl`.

What I suspect is going on is that some tests in the build run from the built product and then end up configured with [these values](https://github.com/microsoft/vscode-distro/blob/6ef4281a354a8aed9de0e5a2bd8beb2802a2b2eb/quality/insider/product.json#L29-L30)

**Comment by bpasero** [comment]
> but do you maybe know off-the-top of your head which tests run with a built product

Every CI that produces a full build (I think only our Azure ones, not GH actions) runs tests against that build, except for unit tests obviously. But:
* integration tests (web, desktop local, desktop remote)
* smoke tests (web, desktop local, desktop remote)

For desktop remote and web the built server is running.

**Comment by alexdima** [comment]
I analysed a recent build (got the raw logs) and could no longer find `404` http errors nor the string  `webWorkerExtensionHostIframe.html`. I will assume that this is fixed.
