### ISSUE TITLE
Settings sync disable the typescript plugin

### ISSUE THREAD

**Issue by Osolemio44** [microsoft/vscode#130097]
When you turn ON the Settings sync, the plugin `Angular Language Service` stop working. Auto-complete, intellisence, etc doesnt work anymore.  As soon as i deactivate "Settings sync"everything works fine again. 

Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by mjbvz** [comment]
Please start by filing this against the angular plugin. If they believe that setting sync is the root cause, they can follow up again here
