### ISSUE TITLE
globalState is shared between different remote machines

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#130099]
It is probably me confusing something, but I would expect that values of globalState are not shared, for instance, between 2 different ssh-remote authorities, but it does not seem to be true. At the same time globalStorageUri actually seems to point to folder within remote machines.

Just to clarify: It is in the context of the VS Code extension running on remote machine extension host via Remote SSH.

Is it that for desktop globaState is stored on the local machine not remote?

**Comment by bpasero** [comment]
Yes, global state is persisted in the local machine where you launch VSCode from. Same as workspace state btw and any other user data.
