### ISSUE TITLE
Unable to Remove ctrl+enter Shortcut for Insert Line Break in Find

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#130055]
I want to be able to use enter for replace and ctrl+enter for replace all. It looks like it's not possible, because I can't find the keybinding for ctrl+enter that adds a new line.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Go to Keyboard Shortcuts
2. Look for "ctrl+enter"
3. There is no keymap for something like "Insert line break in find & replace."

**Comment by ArturoDent** [comment]
Probable duplicate: https://github.com/microsoft/vscode/issues/129666
