### ISSUE TITLE
t letter does not woring

### ISSUE THREAD

**Issue by 17pa1a04g4** [microsoft/vscode#130080]
Issue Type: <b>Bug</b>

Key board letter t does not working this app

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.33GB free)|
|Process Argv|--crash-reporter-id ea96751b-cb08-4581-8714-2afd8bd0c5ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-pull-request-github|Git|0.28.0
pubspec-assist|jer|2.2.1
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
arma-dev|ole|0.0.20
java|red|0.80.0
LiveServer|rit|5.6.1
vsfire|tob|1.4.1
errorlens|use|3.3.2
vscodeintellicode|Vis|1.2.14
vscode-maven|vsc|0.32.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues for guidance about how to check whether that keystroke has been bound to a command.

Maybe also run the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by alexdima** [comment]
@17pa1a04g4 
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `t`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
