### ISSUE TITLE
i increased zoom unknowingly to a big number & now not able to scroll or go back to normal condition

### ISSUE THREAD

**Issue by suzukiahmed** [microsoft/vscode#130013]
Issue Type: <b>Bug</b>

everything is zoomed in my app &not able to go back to normal condition as the setting is not able to access, I tried reinstalling the app many times , but the result is same.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.94GB (1.28GB free)|
|Process Argv|--crash-reporter-id d50d30d8-5ead-40ec-a6fb-ffbeb2012e4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
batch-rename-extension|Jan|0.0.4
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30346310

```

</details>

**Comment by suzukiahmed** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/82318831/127950436-1e3996fe-ed89-4928-b4fc-bbaf6309794a.png)
![Screenshot (4)](https://user-images.githubusercontent.com/82318831/127950443-218b19cc-7237-464a-ac4f-3290aff1bc2c.png)

**Comment by gjsjohnmurray** [comment]
Try pressing <kbd>Ctrl</kbd>+<kbd>0</kbd>

**Comment by deepak1556** [comment]
You can also delete `%APPDATA%\Code` to reset app state.
