### ISSUE TITLE
no ability to keep unreachable code

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#130012]
Issue Type: <b>Bug</b>

unreachable code keeps getting automatically deleted on save and there seems to be no way to stop that.
EXTREMELY FRUSTRATING!

why can't it just give a WARNING???

I want to KEEP that code because i'm just TESTING AND WORKING THINGS OUT

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (5.31GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2207)|
|Memory (System)|24.92GB (8.74GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-firefox-debug|fir|2.9.4
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
vscode-apollo|apo|1.19.4
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
restore-terminals|Eth|1.1.6
gauge|get|0.0.20
vscode-docker|ms-|1.15.0
vsliveshare|ms-|1.0.4631
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.34.1
prisma|Pri|2.28.0
indenticator|Sir|0.7.0
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by mjbvz** [comment]
This is not something VS Code does automatically so this is either caused by an extension or by a setting that you've configured

Since it happens on save, first try looking at settings related to save: `formatOnSave` or `codeActionsOnSave`. Then try going through extensions to track down the one that causes this
