### ISSUE TITLE
live serve has dissappared 

### ISSUE THREAD

**Issue by kamotho-njiru** [microsoft/vscode#130049]
Issue Type: <b>Feature Request</b>

my live serve bar has dissappied how do get another one

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic
Restricted Mode: No

**Comment by hediet** [comment]
What do you mean with live serve bar?

**Comment by vtinev** [comment]
> my live serve bar has dissappied how do get another one

Do you mean the extension "Live Server"? If so, you can right click on your status bar and manage the icons displayed there, you can also use `CTRL + SHIFT + P` and type the name of the extension to see if you even have it - you can also start the server from there.

**Comment by rzhao271** [comment]
Closing until we get more info.
