### ISSUE TITLE
Custom terminal title is lost

### ISSUE THREAD

**Issue by sfsaccone** [microsoft/vscode#130056]
Issue Type: <b>Bug</b>

Unfortuantely I can't reproduce this yet. The problem: 

* I set my terminal title to 'mytitle'
* Run something like `bash t.sh` 
* The terminal name changes to 'bash' after the script exits, normally or otherwise

If I close the terminal and open a new one then it works normally for a while. That is, the title is preserved after scripts run.  I'm not sure what triggers the problem. It might have something to do with sudo processes or processes that result in some kind of error. I tried changing `terminal.integrated.titleMode` from 'executable' to 'sequence' but that didn't work (and I don't really understand the 'sequence' setting).

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (22.12GB free)|
|Process Argv|--crash-reporter-id 3a191915-fe54-47d3-a3dd-2048b7172e4f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ninds1|
|OS|Linux x64 5.4.0-72-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (2 x 2593)|
|Memory (System)|7.78GB (0.18GB free)|
|VM|100%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-great-icons|emm|2.1.79
vscode-firefox-debug|fir|2.9.4
vscode-apache|mrm|1.2.0
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.8.0
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.14.0
errorlens|use|3.3.2
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.2
vscode-intelephense-client|bme|1.7.1
prettier-vscode|esb|8.1.0
vscode-terminals|fab|1.12.10
php-debug|fel|1.17.0
vscode-favorites|how|1.9.1
git-graph|mhu|1.30.0
php-docblocker|nei|2.1.0
vscode-workspace-explorer|tom|1.5.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by meganrogge** [comment]
This is by design. To set the terminal title and prevent the process from changing it, use a the overrideName property in a terminal profile.

**Comment by sfsaccone** [comment]
Ok, trying again:

* I set my terminal title to 'mytitle'
* Run something like `bash t.sh`
* Exit the script normally
* **Expected**: the title does not change, it's still 'mytitle'
* **Actual**:  the title changes to 'bash', permanently, my title is lost

**I repeat**: I cannot reproduce this. Sometimes, the expected behavior _does_ occur, other times it does not. If there's a setting that would help with this, such as never changing the title once it's set, that would be great. Thanks.
