### ISSUE TITLE
workbench.action.tasks.build no longer triggers build but opens a list of tasks

### ISSUE THREAD

**Issue by borgdylan** [microsoft/vscode#130028]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.59.0-insider
- Commit: ba0df885e9d6b0f0ccf2cc714c3fa31423572205
- Date: 2021-07-31T00:42:32.346Z
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- V8: 9.1.269.36-electron.0
- OS: Linux x64 5.13.5

Steps to Reproduce:

1. Open a project directory that is hooked up with tasks via tasks.json v2. The tasks.json file must define one of the tasks as being the default.
2. Ensure you have workbench.action.tasks.build bound to a shortcut (mine is ctrl+shift+b)
3. Press the key combination to trigger the build
4. A picker combobox to choose a task appears instead of the default task being executed as used to happen before.

**Comment by alexr00** [comment]
@borgdylan I'm not able to reproduce this issue. Do you have a repository I can test with? I tried with:
https://github.com/microsoft/vscode
https://github.com/microsoft/vscode-pull-request-github

If there is more than one default build task, then we have always shown the picker. If there is only one default build task, then we run it.

**Comment by borgdylan** [comment]
I'm experiencing this with internal company code which cannot be shared. I can share the tasks.json file. It should work with any c# based project.

**Comment by borgdylan** [comment]
Has the schema for tasks.json changed at all in the past month?

**Comment by borgdylan** [comment]
---
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "group": "build",
            "label": "build-js",
            "type": "shell",
            "command": "gulp",
            "args": []
        },
        {
            "group": {"kind": "build", "isDefault": true},
            "dependsOn":["build-js"],
            "label": "build",
            "type": "shell",
            "command": "msbuild",
            "args": ["/property:GenerateFullPaths=true", "/t:Build"],
            "problemMatcher": [
                {
                    "owner": "dylandotnet",
                    "fileLocation": ["absolute"],
                    "pattern": {
                        "regexp": "^(.*)\\((\\d+)(,(\\d+))?\\):\\s*(error|warning)\\s*:\\s*(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 4,
                        "severity": 5,
                        "message": 6
                    }
                },
                "$msCompile"
            ]
        },
        {
            "label": "restore",
            "type": "shell",
            "command": "msbuild",
            "args": ["/property:GenerateFullPaths=true", "/t:Restore"],
            "problemMatcher": [
                "$msCompile"
            ]
        }
    ]
}
---

**Comment by borgdylan** [comment]
I've replicated this on other similar projects, even those that have just one task defined.

**Comment by alexr00** [comment]
Thanks for the additional details and for reporting this issue!
