### ISSUE TITLE
Relative path separator not used when no formatting available

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130019]
We only respect the setting when a `formatting` is found:

https://github.com/microsoft/vscode/blob/4153751d05faa65c43d6bca9f1c9e3736f82ded8/src/vs/workbench/services/label/common/labelService.ts#L141-L144

We should always support the separator.

**Comment by bpasero** [comment]
//cc @IllusionMH

**Comment by bpasero** [comment]
Went ahead with a fix myself because I figured it is more involved: without formatting we cannot just add the separator so I ended up using the `normalize` method that matches the config in that case on the relative path.

**Comment by IllusionMH** [comment]
Thanks for the proper fix!

I had couple of attempts but first failed when list of files in with `memfs` stopped to work (apparently needed https://github.com/microsoft/vscode/commit/aa3cfca4532f8119f42b1b3b21290aa1e7499eee)

Second was
```ts
 if (options.separator) { 
 	// mixin separator if defined from the outside 
 	formatting = formatting ? { ...formatting, separator: options.separator } : { label: '${path}', separator: options.separator }; 
 } 
```
but it produced different results for `auto` and `\`.

Haven't thought about using same normalization as in `getUriBasenameLabel`
