### ISSUE TITLE
Can't set breakpoints in django-html

### ISSUE THREAD

**Issue by sekar-p** [microsoft/vscode#130021]
Can't set breakpoint when debugging the django project whereas if I change the type from django-html to html I can set brekpoint and able to debug the template. how can debug django-html?

**Comment by sekar-p** [comment]
It seems a bug, it should not be categorised as "question".

**Comment by weinand** [comment]
@sekar-p VS Code does not have built-in functionality to debug "django" or "django-html".

So before we will accept a "bug", you will have to ask in some forum what extensions are needed to debug "django" or "django-html". If that still doesn't work for you, please file an issue against the involved extension.
