### ISSUE TITLE
Save all files shortcut

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#13006]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Edit several files without saving

---------

A keayboard shortcut to save all modified files would be great

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/18957640/2623586c-8660-11e6-94c7-d401af0b3c73.png)

**Comment by mbeckenbach** [comment]
Di you use another version than i do? 

![image](https://cloud.githubusercontent.com/assets/6654388/19017384/b8b83bb0-8837-11e6-9ecf-4a4069d3165d.png)
