### ISSUE TITLE
Windows ARM builds don't start for me anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130087]
Trying latest Windows ARM insider builds, right on startup I see this dialog:

![image](https://user-images.githubusercontent.com/900690/128137156-32c55140-d8bc-476e-bfe7-0ab0e083d0a9.png)

**Comment by bpasero** [comment]
Turns out I had the crash reporter ID commented out in `argv.json` but arguably I think we need to be more robust here in case the user makes an edit like that.

**Comment by victormamede** [comment]
My argv.json looks fine to me but the error persists. For now, I will change "enable-crash-reporter" to false.
Maybe my crash-reporter-id is invalid?
