### ISSUE TITLE
Can't edit file after git revert

### ISSUE THREAD

**Issue by fergusg** [Microsoft/vscode#13002]
![selection_015](https://cloud.githubusercontent.com/assets/760983/18956531/a0d2582c-8653-11e6-9459-ab7988621bc8.png)

- VSCode Version:1.5.3
- OS Version: Fedora 23

When I git-revert a file, it can't be edited.  File appears in tab, but selecting that tab doesn't update the body from the previously selected file.  

In attached screenshot, .ts file tab is selected, but shows .scss content (and typing updates the latter)

Steps to Reproduce:

1. Edit a file
2. revert with VSC git tool

Workaround:

Restart VSC (reopening file doesn't work)

**Comment by joaomoreno** [comment]
@bpasero File events?

**Comment by bpasero** [comment]
This was an issue with stale file model caches and got fixed for 1.6
