### ISSUE TITLE
Webivew input events cannot focus datalist items

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#130001]
Related: https://github.com/microsoft/vscode/issues/129999

Normally when you have an input backed by a datalist, up/down will focus items within the datalist and enter will set the text in the input, like this:

![recording (49)](https://user-images.githubusercontent.com/2193314/127923735-7f881ca9-e57f-4f0d-ad42-b1d1b286ebd1.gif)

Up/down doesn't seem to work inside a webview, it pops up the list but doesn't move focus to items within it.

![recording (51)](https://user-images.githubusercontent.com/2193314/127923931-8170d9a1-0add-422c-b797-c371e28ed3b9.gif)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/129999
