### ISSUE TITLE
Fix Spelling In Ids

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#130026]
https://github.com/microsoft/vscode/blob/1ccd6a079463a635756f35308e290551ca135241/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L349-L351

* editLineBrekapoint
* editBReakpoints

I don't know who depends on those IDs and if changing them would be a breaking change.

**Comment by isidorn** [comment]
Nobody is depending on those ids, so I just fixed them.
Thanks!
