### ISSUE TITLE
VS Code node debugger stuck on: Debugger listening on [::]:[port]

### ISSUE THREAD

**Issue by starrett67** [Microsoft/vscode#13005]
- VSCode Version:1.5.3
- OS Version:Windows 7

Unsure how to reproduce the issue. I think I somehow got the debugger in a bad state. It was working before on my environment but vs code threw an error while debugging that I could not make sense of and after that I started experiencing this bug. I am trying to fix the issue by debugging a very simple js file.

Test.js:
`console.log("test");`

launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "fix debugger",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/test.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "externalTerminal",
            "sourceMaps": false,
            "outDir": null
        }
    ]
}
```

When i run the debugger this is all I get before it gets stuck:
![debuggerstuck](https://cloud.githubusercontent.com/assets/5614600/18956590/f13da46c-8629-11e6-9bae-06c4f8af413f.png)

I already attempted re-installing the application to see if that would fix it but no luck.

**Comment by isidorn** [comment]
@starrett67 what happens if you change your launch.json to have `"console": "internalConsole"` instead of "externalTerminal"?
Can you run your application just using `node --debug test.js`?

**Comment by starrett67** [comment]
I tried every option for console (internal console, integrated terminal, external terminal)and all have the same result.

I also tried running the node debug command and it runs as expected.

**Comment by starrett67** [comment]
I will also note that I am using node 6.3.0 and I am using nvm to manage my node versions.

**Comment by starrett67** [comment]
I am happy to keep debugging this. However, if we cant find the issue, is there a better way of doing a complete re-install? I would like to get debugging working again.

**Comment by isidorn** [comment]
We should still look into this issue. 
However if you want to completly reinstall vscode, first uninstall it and then delete .vscode from your user folder. Not sure if that will fix your issue though.

**Comment by adamwlarson** [comment]
I am running into the exact same problem. It literally started in the middle of the day without ever restarting. I'm using Node v6.4.0 and it just hangs in the exact same place. I am running on Windows using nvm to manage my node version.

I have uninstalled and reinstalled which did not fix it.
I have tried deleting my launch.json file and recreating it with base results and that doesn't work either.

I really need debugging working again as well, are their any logs I can look at in Visual Studio Code that will tell me whats happening behind the scenes?

**Comment by adamwlarson** [comment]
I tested a new theory where I install visual studio code to a whole different directory and I still get the same issue. I'm going to try nuking the registry settings for vs-code and see if that makes any difference next.

**Comment by adamwlarson** [comment]
I happened to run across the insider build of VS Code. I installed the latest version of that and for now i'm back up and running, very thankful this is working for now! Back to work

**Comment by jhsware** [comment]
I have run into the same issue. I was debugging one of my npm packages I use in the project and **I think** I set a breakpoint in that package. Then I fixed the bug in the package and did an npm update. I didn't remove the breakpoint but it doesn't show up. The issue appeared on the next start and it gets stuck at:

node --debug-brk=26758 --nolazy --harmony_destructuring app.js 
Debugger listening on port 26758

**Comment by adamwlarson** [comment]
Just for some clarity I definitely did not mess with a npm module when my issue started, but I was most definitely debugging in my main application. It is such an odd issue, I really hope we can work out a way to solve this, but for now I suggest going on the insider build, because once you get it there is nothing I could do to fix the issue locally.

**Comment by jhsware** [comment]
Debugging with VS Code still works for me by attaching the debugger, I just can't launch the node app from VSCode.

**Comment by weinand** [comment]
Please add a `"trace": "all"` to your launch configuration and try to reproduce the problem. You should now see trace information in the debug console. Report back if you find something suspicious.

**Comment by jhsware** [comment]
Removing all breakpoints solved the issue for me. I had a couple of breakpoints that appeared to be inactive. When adding `"trace": "all"` it appeared that VS Code was trying to set a breakpoint, but it was never visible in the given file:

```
node --debug-brk=4280 --nolazy --harmony_destructuring app.js 
56737: _attach: address: 127.0.0.1 port: 4280
Debugger listening on port 4280
56737: _attach: retry socket.connect
56737: _attach: connected
56737: _initialize: got process id 56739 from node
56737: _injectDebuggerExtensions: frame based code injection failed with error 'No frames'
56737: _injectDebuggerExtensions: global code injection failed with error 'ReferenceError: require is not defined'
56737: _startInitialize: stopped: false
56737: _stopped: got break event from node
56737: _stopped: new ref cache
56737: _analyzeBreak: suppressed stop-on-entry event
56737: _startInitialize: got break on entry event after 2 retries
56737: _startInitialize2: fire initialized event
56737: _startInitialize2: remember to do a 'Continue' later
56737: setBreakPointsRequest: {"name":"portfolioCtrl.js"} []
```

**Comment by adamwlarson** [comment]
I don't have any breakpoints and mine still fails, here is the result of my trace some of which does look suspicious:

`16564: _attach: address: 127.0.0.1 port: 23855
Debugger listening on [::]:23855
16564: _attach: connected
16564: _stopped: got break event from node
16564: _stopped: new ref cache
16564: _analyzeBreak: suppressed stop-on-entry event
16564: _initialize: got process id 9488 from node
16564: _injectDebuggerExtensions: frame based code injection successful
16564: _startInitialize: stopped: true
16564: _startInitialize: got break on entry event after 0 retries
16564: _startInitialize2: fire initialized event
16564: _startInitialize2: remember to do a 'Continue' later
16564: setFunctionBreakPointsRequest: result []
16564: setExceptionBreakPointsRequest: ["all","uncaught"]
16564: configurationDoneRequest: do a 'Continue'
16564: _stopped: got exception event from node
16564: _stopped: new ref cache
16564: stackTraceRequest: vscode_backtrace 0 20
16564: NodeV8Protocol hook: ref cache size: 27
16564: __readFile: d:\Code\YouAppBackend\node_modules\lodash-compat\internal\isHostObject.js
16564: _loadScript: 196
16564: __readFile: d:\Code\YouAppBackend\node_modules\lodash-compat\lang\isNative.js
16564: _loadScript: 194
16564: __readFile: d:\Code\YouAppBackend\node_modules\lodash-compat\internal\getNative.js
16564: _loadScript: 193
16564: NodeV8Protocol hook: ref cache size: 28
16564: NodeV8Protocol hook: ref cache size: 29
16564: NodeV8Protocol hook: ref cache size: 30
16564: scopesRequest: scope 0
16564: NodeV8Protocol hook: ref cache size: 32
16564: _resolveToCache: vscode_lookup 1 handles
16564: _createPropertyVariables: trigger getter`

**Comment by Andonon** [comment]
Has anyone figured this... 
Debugger listening on 127.0.0.1:36668
14044: _attach: connected
14044: _stopped: got break event from node
14044: _stopped: new ref cache
14044: _handleNodeBreakEvent: suppressed stop-on-entry event
14044: __initialize: got process id 12768 from node
14044: _initialize: target node version: v7.10.0
14044: _injectDebuggerExtensions: code injection successful
14044: _startInitialize: stopped: true
14044: _startInitialize: got break on entry event after 0 retries
14044: _startInitialize2: fire initialized event
14044: _startInitialize2: remember to do a 'Continue' later
14044: setFunctionBreakPointsRequest: result []
14044: setExceptionBreakPointsRequest: ["uncaught"]
14044: configurationDoneRequest: do a 'Continue'

is there a new launch.json file I can get somewhere. This is sickening. I'm in the middle of javascript learning it, and now I cannot debug. OMG!

**Comment by weinand** [comment]
@Andonon how does your launch.json look like?

**Comment by weinand** [comment]
@Andonon if your program is too short, it might execute so fast that the VS Code debugger has not enough time to attach to it.
In this case please add a `"stopOnEntry": "true"` to your launch config. This will force your program to stop on entry.

**Comment by Andonon** [comment]
Thank you for the support @weinand. I'm a new developer, two things were happening. My short program was running so fast I didn't see it. **I added "stopOnEntry": "true"** back to my launch file, which I had removed a week ago (an now have added back, commented out for future reference). Thank you! My second mistake was **not calling the function I wrote**. *blurg!* Thank you.

**Comment by weinand** [comment]
@Andonon instead of adding "stopOnEntry": "true" to your launch config, you can just set a breakpoint in a line that make more sense to you than the first line. Or you can add a `debugger;` statement to your code.

**Comment by Andonon** [comment]
@weinand You know, I tried the break point yesterday and it was not working because I was not calling my function. You see the rabbit hole I was in... :-) I will look up the debugger; statements. Thanks again.

**Comment by mvcmania** [comment]
I had exactly same issue and unchecking the box which is shown on screenshot solved my problem.
![node_error](https://user-images.githubusercontent.com/3177104/29039158-d66da2fc-7bb2-11e7-9dfc-fe757d0c5c0f.png)
