### ISSUE TITLE
Infer / complete variable names from the type

### ISSUE THREAD

**Issue by BuZZ-dEE** [microsoft/vscode#130023]
In Java you write: `Type variableName`. Eclipse for example infers the `variableName` from the `Type`, because the `Type` is written before the `variableName`.

In Typescript you write: `variableName: Type`. If the programmer begins to write the `variableName` VSCode should look in the available types to infer the completion for the `variableName`.

**Comment by hediet** [comment]
I think this is partially covered by copilot.

**Comment by BuZZ-dEE** [comment]
> I think this is partially covered by copilot.

I would prefer a solution without copilot and without a further extension. As far as I know copilot needs to [communicate to a server](https://copilot.github.com/#faq-how-do-i-get-the-most-out-of-github-copilot).:

> The GitHub Copilot editor extension sends your comments and code to the GitHub Copilot service, which then uses OpenAI Codex to synthesize and suggest individual lines and whole functions.

I would prefer client side only solution without communication to remote service.
