### ISSUE TITLE
Typing repeated dots in js expands to first suggestion

### ISSUE THREAD

**Issue by swantzter** [microsoft/vscode#130096]
Issue Type: <b>Bug</b>

For the past couple days when I type , for example `...rest` the first suggested "property" get's automatically expanded when i enter the second and third dot, resulting in something like `.name.name.rest` meaning I have to do something like <kbd>.</kbd><kbd>←</kbd><kbd>.</kbd><kbd>←</kbd><kbd>.</kbd><kbd>→</kbd><kbd>→</kbd><kbd>rest</kbd>

VS Code version: Code - Insiders 1.59.0-insider (cead2f699cd0afb2464d8d3ad975776051583b4f, 2021-08-03T16:24:47.105Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (8.02GB free)|
|Process Argv|--crash-reporter-id b535a63f-2266-449e-9950-8702a85093ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.2
vscode-apollo|apo|1.19.4
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
vscode-test-explorer-status-bar|con|1.2.0
vscode-github-actions|csc|0.20.3
vscode-eslint|dba|2.1.23
gitlens-insiders|eam|2021.7.1905
vscode-test-explorer-diagnostics|emi|0.1.1
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.213
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.20.4
code-coverage|mar|1.3.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1081660962
remote-containers|ms-|0.190.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
test-adapter-converter|ms-|0.1.2
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
material-icon-theme|PKi|4.8.0
vscode-yaml|red|0.22.0
partial-diff|ryu|1.4.3
vscode-standard|sta|1.5.1
code-spell-checker|str|1.10.2
code-spell-checker-swedish|str|0.1.8
vscode-nginx|wil|0.7.2
material-theme|zhu|3.11.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by IllusionMH** [comment]
Controlled by `editor.acceptSuggestionOnCommitCharacter` and `.` is commit character for JS/TS, you can try to disable it in the meantime.

And also it works OKish¹ for "rest"-places `const [a, ...rest] = []` (triggers only after third `.`), however unexpectedly triggers in "spread"-places `const a = [...arr]` (triggers after first `.`, and I think it's only text suggestions)

@swantzter is it reproducible for you when you add `"editor.suggest.showWords": false` to settings?

----

¹ - inconsistent (e.g. no trigger for functions parameters) and questionable benefit for rest places inside of `const/let/var` you need to declare new local name.

**Comment by swantzter** [comment]
@IllusionMH `"editor.suggest.showWords": false` does make it go away.

The specific place I had this happen the most was in an "object rest" in an array function for an array function, for example `arr.map(({ privateParam, ...rest }) => rest)` but I did notice it in some spread instances too like you mentioned

I also found that if the load on my computer is high I can avoid it by typing faster than the suggestions can load (which seems expected)

**Comment by JayAndCatchFire** [comment]
I _think_ this was introduced with commit https://github.com/microsoft/vscode/commit/76885d753d6749294ab4745e3ceccb6b352b7dfd but I'm not 💯 about that.

**Comment by IllusionMH** [comment]
@JayAndCatchFire looks like you are correct.

In JS/TS files suggestions are triggered when user types first `.`  in `{}` and word based suggestions were always there, they just had not commit characters and were not suggested when user typed second and third dots.
And after `...` TS provided adequate suggestions that were acceptable with commit characters.

1.60-insiders has `.,;` as commit characters on word based suggestions
![image](https://user-images.githubusercontent.com/1312662/129172979-5ddeaaec-7772-4422-aaca-f2e803d78459.png)

while 1.58 does not
![image](https://user-images.githubusercontent.com/1312662/129173196-60a9a386-b140-4128-9da0-cfb383bb59f4.png)

**Comment by rebornix** [comment]
@mjbvz may I ask what's the scenario that I should check, I tried 

```
var a = {
    b: 1,
    c: 2
}

...
```

Every dot on the last line will trigger the auto complete.

**Comment by mjbvz** [comment]
@rebornix Try typing inside an object or array literal. https://github.com/microsoft/TypeScript/issues/45436 has a simple code example, for example:

```ts
const abc = {};

({ }); // type inside here
([  ]); // or here
```

The first three dots should not accept `abc`. The fourth should accept it

**Comment by IllusionMH** [comment]
@rebornix I think it's valid place to trigger and accept suggestions. There are no ASI and it's valid to use property access right after object literal
![image](https://user-images.githubusercontent.com/1312662/129645510-cd46f553-927e-40c3-990e-60819fbdaee4.png)

**Comment by albannurkollari** [comment]
I'm still having this issue of spread operator not respected rather abrupted by VSCode's auto-select of first suggestion on each dot type.

```
Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by IllusionMH** [comment]
1.60 will be released in early September.

In your case you are more interested in July 2021 Recovery release that is tracked in #130212

**Comment by albannurkollari** [comment]
> 1.60 will be released in early September.
> 
> In your case you are more interested in July 2021 Recovery release that is tracked in #130212

No indication of any release date for that milestone or am I missing something?
Would really appreciate to have this feature asap released, really dont wanna opt-in to nightly build.

**Comment by IllusionMH** [comment]
No date there.

As mentioned in https://github.com/microsoft/vscode/issues/130096#issuecomment-892561316 in the meantime you can:
1. disable word suggestions that are shown and accepted with  `"editor.suggest.showWords": false` 
2. prevent `.` from accepting any suggestions with `"editor.acceptSuggestionOnCommitCharacter": false`
