### ISSUE TITLE
Extension Marketplace Error...

### ISSUE THREAD

**Issue by EGO-II** [microsoft/vscode#130020]
Issue Type: <b>Bug</b>

When trying to acess the Extensions I recieve this error: "We cannot connect to the Extensions Marketplace at this time, please try again later" I've tried all the recommendations on the git pages ,adn have un-installed and then re-installed more than once, and still no joy. Oh well, going back to Geany, (on Pop-OS) I guess if they ever fix the issue?..I'll come back but I don't have time to tinker with this much. Here's hoping the devs will figure out what went wrong and what the fix is.

VS Code version: VSCodium 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-16T00:15:55.196Z)
OS version: Linux x64 5.11.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|15.51GB (0.66GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.6.0
bracket-pair-colorizer-2|Coe|0.1.4
gitlens|eam|11.6.0
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.0
code-runner|for|0.11.5
base16-generator|gol|1.15.0
mayukaithemevsc|Gul|3.0.0
vscode-github|Kni|0.30.6
vscode-clangd|llv|0.1.11
pop-n-lock-theme-vscode|Lux|3.31.0
python|ms-|2020.10.332292344
material-icon-theme|PKi|4.8.0
neofloss|rad|1.1.5
salt-water-taffy|rad|0.3.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
everforest|sai|0.1.0
gruvbox-material|sai|6.4.5
ayu|tea|0.20.1
familiar-java-themes|zer|0.1.3
material-theme|zhu|3.11.2

(81 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/129879#issuecomment-890292080 is relevant

**Comment by sandy081** [comment]
Please file issue against VSCodium.
