### ISSUE TITLE
Add "Outline: Show Struct Members" switch

### ISSUE THREAD

**Issue by lzeng14** [microsoft/vscode#130089]
Add "Outline: Show Struct Members" switch for struct to be similar with "Outline: Show Enum Members" for enum.

**Comment by jrieken** [comment]
You mean 'outline.showStructs'?

**Comment by lzeng14** [comment]
![image](https://user-images.githubusercontent.com/11768286/129652331-bee2fd5b-0bb3-45f4-af80-32a96f50fc1d.png)
For Enum, there are both "Show Enum Members" and "Show Enums".
But for Struct, there is only "Show Structs" for now.
So this request is to add "Show Struct Members".

**Comment by jrieken** [comment]
There is no dedicated type for struct members, extensions usually use property I believe

**Comment by lzeng14** [comment]
No specific symbol type for struct members?

Anyway, is there an easy way to only show struct name but not struct members in outline? Sometimes, struct member is too trivial when only quick checking struct name. :)
