### ISSUE TITLE
Web: benefit from new Suggested names for File System Access API

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130034]
With Chrome 91 there is now new API to set suggested names for the file system APIs `showSaveFilePicker` and `showOpenFilePicker`. Specifically the suggested name for a file can be set (which is something we pass in from the `defaultUri` option and the default folder fo the file picker.

Details in: https://developer.chrome.com/blog/new-in-chrome-91/#filenames

Today the save dialog will just always show `Untitled`:

![image](https://user-images.githubusercontent.com/900690/128016297-55ca0684-3a5e-4729-a9d6-b03d69c5b570.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/95ca115b9f148398bf46d0bd2e7976e07964ce2d enables the `suggestedName` property so that the save dialog offers a good default name.

The remaining piece is to pass a default folder to the folder pickers.

**Comment by joaomoreno** [comment]
Verification:

1. Open https://insiders.vscode.dev
2. Create a new file
3. Type something in it
4. Save it

The browser should use the file's contents as a filename suggestion.
