### ISSUE TITLE
 ["--preserve-symlinks", "--preserve-symlinks-main"] debug options not working when debugging a javascript file in a symlink folder on Linux

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#130091]
Issue Type: <b>Bug</b>

1. Open a javascript file which is in a symlinked folder.
2. Use this launch configuration:
{
            "name": "Launch Program",
            "program": "${workspaceFolder}/test.js",
            "request": "launch",
            "type": "pwa-node",
            "runtimeArgs": ["--preserve-symlinks", "--preserve-symlinks-main"]
        }
3. Set breakpoints and start debugging
4. VSCode will open the real file and starts hitting breakpoints there.

Also, similar problem happens while debugging Python file on Linux machines when the "program" is set to a specific file name instead of ${file}. My guess is they are related.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.4.0-1055-azure
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|31.36GB (25.41GB free)|
|Process Argv|--unity-launch --crash-reporter-id 41568f8d-e4e6-4de2-ad40-80b74f8a0bf9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
python|ms-|2021.7.1060902895
jupyter|ms-|2021.8.1054968649
vscode-ai|ms-|0.6.24
vscode-ai-remote|ms-|0.4.0
azure-account|ms-|0.9.8
vscode-typescript-tslint-plugin|ms-|1.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by connor4312** [comment]
I looked into this previously, and unfortunately I don't think it's possible to fix since this is a behavior of the OS https://github.com/microsoft/vscode-js-debug/issues/776#issuecomment-793271832. A workaround you can do is set the `"cwd": "/"`, which does change module resolution behavior subtly but may be sufficient for your needs.

**Comment by connor4312** [comment]
Yea, I'm not familiar with the Python debugger but I'm guessing it's the same root cause for that.
