### ISSUE TITLE
Web: pass well known file types to native file dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130035]
Today we only show "All Files" in the file types dropdown for native file dialog on web:

![image](https://user-images.githubusercontent.com/900690/128016591-ef3c2d53-b739-4bd2-9eb9-1510f44cd2c5.png)

Compare with native:

![image](https://user-images.githubusercontent.com/900690/128016677-b8fd9ece-99f6-4a19-9fdb-c624200f83ba.png)

I think the web platform provides API to set `types` as options ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker)). We compute the possible types here:

https://github.com/microsoft/vscode/blob/b503e9b7f7c18958d7867f969c92e4095e140b7c/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L279-L279

**Comment by alexr00** [comment]
It seems that file extensions with `-` and `_` are not permitted, but we should be able to allow most others.

**Comment by bpasero** [comment]
I see the list of file extensions but the dialog behaves strange, when I pick different extensions I would have expected the file name to update like it does with native VSCode.

Either we are using the API wrong or there is a bug in Chrome/Edge?

**Comment by alexr00** [comment]
I don't think the name not updating is anything we are doing with the file types. We pass in the types and then it is out of our hands.
