### ISSUE TITLE
error counts not showing at bottom left of VSCode

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/vscode#13007]
- VSCode Version: 1.53
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. write code with errors that can be caught by a linter (e.g. pylint)
2.  observe that the errors are not displayed

![9-28-2016 2-24-41 pm](https://cloud.githubusercontent.com/assets/12263288/18957202/3888550e-862c-11e6-827c-010d3bd4c63a.png)

**Comment by sandy081** [comment]
@gbritton1 May I know if you are using any extension for linting?

**Comment by gbritton1** [comment]
I'm using don J's Python extension which supports point. I first posted to his issue log bit he said it was an upstream problem.

**Comment by gbritton1** [comment]
s/point/pylint/

**Comment by gbritton1** [comment]
You need to install pylint. e.g.

`c:\Python3x\Scripts\pip.exe install pylint`

Then (possibly) restart vscode (not sure if a restart is needed). then you should see the errors.

**Comment by sandy081** [comment]
@gbritton1 It is because, the extension is generating markers of type unknowns/ignore. Status bar only shows information about errors/warnings/info and ignores unknowns.
