### ISSUE TITLE
Search&Replace does not function when the text is copied

### ISSUE THREAD

**Issue by furkanarabaci** [microsoft/vscode#130063]
Issue Type: <b>Bug</b>

## Steps to Reproduce
1. Type something on Search bar
2. Paste some text with a guaranteed match
3. Search doesn't find the match

## Expected Result
Search to be found normally even after the paste

## Actual Result
Search doesn't find the paste. Deleting and typing something on the Search bar fixes the issue

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 46716df9-d7ee-4256-b6e2-58445c1897ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
atlascode|atl|2.9.1
vscode-postgres|cko|1.1.18
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
go|gol|0.26.0
gc-excelviewer|Gra|3.0.42
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.0
vscode-docker|ms-|1.15.0
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
vscode-react-native|msj|1.5.2
material-icon-theme|PKi|4.8.0
vscode-yaml|red|0.22.0
svelte-vscode|sve|105.3.3
pdf|tom|1.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by roblourens** [comment]
Is this the search bar inside an editor or the one in the sidebar to search across the workspace (cmd+shift+f)?

You are saying that if you paste the text there is no match but if you type the same text, it finds the match? Is it possible that you copied some extra character that breaks it, like a newline?
