### ISSUE TITLE
can't hide vscode on macos

### ISSUE THREAD

**Issue by wolverineks** [microsoft/vscode#130052]
Issue Type: <b>Bug</b>

run vscode on macos
command + h

expect: hide vscode
actual: nothing happens

other info:
(this correctly hides vscode)
code -> hide Visual Studio Code 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 10, 8|
|Memory (System)|32.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 21ee57b7-d70d-4f3e-8627-a7a1b344eaff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
flow-for-vscode|flo|1.9.1
copilot|Git|1.3.2200
vscode-pull-request-github|Git|0.28.0
syntax-project-pbxproj|mar|0.1.3
git-graph|mhu|1.30.0
npm-outdated|msk|1.4.1
vscode-react-native-storybooks|Ort|2.7.1
vscode-yaml|red|0.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by wolverineks** [comment]
command + h correctly hides all other windows

**Comment by wolverineks** [comment]
searching for `command h`  in keyboard shortcuts reveals no conflicting shortcuts

**Comment by lramos15** [comment]
Are you just clicking the editor or somewhere specifically where it doesn't work as it works for me. Please also try it with all extensions disabled.

**Comment by wolverineks** [comment]
weird, i disabled all extensions and it started working
reenabled all extensions and its still working...
ok, well...thanks!
