### ISSUE TITLE
Selecting something in mongodb files without changing VS Code shows that it has been changed

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode#130140]
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-80-generic

Selecting the last line as the image shows in the aggregate, shows the run line. In every occasion whatever i select something shows this line, however as the font size or something is bigger, lines under moves a little bit, which is annoying when you would like to focus on editing and select.

I simply don't want to run part of the json. (if you select a wordonly, same thing)

By selecting the last line, triggers the files to be changed, as dot appears on the file name.

![error_vs_code](https://user-images.githubusercontent.com/45578746/128253009-09ba797b-4b25-467c-9161-6907fd93dafb.png)

**Comment by hediet** [comment]
I think this is caused by some extension.

If the issue does not persist when you disable all extensions, please file an issue for the corresponding extension.

**Comment by rzhao271** [comment]
Can you try running code with `code --disable-extensions`, and see if that fixes the problem?
