### ISSUE TITLE
Add copy, cut, paste texts inside of a cell in Notebook UI context menu 

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode#130144]
You can only copy, cut or paste a whole cell, but can't do those with text via the context menu. Even though this is consistent with Jupyter's behavior, I still hope they can be added so that I don't have to reach to my keyboard every time when I just need to copy a line of code and insert it inside a cell.

![image](https://user-images.githubusercontent.com/33796896/128262086-408ccc72-accc-446c-8965-0a3be303d98e.png)

**Comment by roblourens** [comment]
You should see that when opening the context menu inside the editor, are you clicking outside of the editor?

![image](https://user-images.githubusercontent.com/323878/128400992-c6b3eaf7-cc02-46fd-ab84-59f43dd44702.png)

**Comment by StevenLi-DS** [comment]
@roblourens Is this .ipynb? I don't have those actions on my end.
![EbUT1yELmz](https://user-images.githubusercontent.com/33796896/128406732-b3b80476-2f69-4c88-9feb-d755bda28da4.gif)




``` 
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by roblourens** [comment]
Oh, there is an issue with this on Windows, got https://github.com/microsoft/vscode/issues/115443 for that
