### ISSUE TITLE
asWebviewUri doesn't return the correct Uri when remote authority is localhost:[port]

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode#130151]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: macOS 11.4

Steps to Reproduce:

I wrote a test case inside VS Code which reproduces the error. Then I added a patch which fixes it. 

This is what `asWebviewUri` currently returns (bug) `https://vscode-remote%2Blocalhost:8080.vscode-resource.vscode-webview.net/Users/codey/file.html` and then is what it should return with the fix `https://vscode-remote%2Blocalhost.vscode-resource.vscode-webview.net:8080/Users/codey/file.html`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by jsjoeio** [comment]
Hmm...I'm not sure how to reproduce this in Insiders 🤔 This only happens when running VS Code in the browser.

Is there a way to run Insiders as a web app? That would recreate the environment for me to reproduce.

**Comment by mjbvz** [comment]
You can run `yarn web` from a local build or for codes-spaces / github.dev, click on the gear and select `switch to insiders`

**Comment by jsjoeio** [comment]
I couldn't reproduce, but I did a test to make sure it works as expected.

**Comment by mjbvz** [comment]
Thanks for testing. Let me know if you still see this in VS Code 1.60+
