### ISSUE TITLE
"U"  (undo, command in Vim keybinding) does not work

### ISSUE THREAD

**Issue by siva-msft** [microsoft/vscode#130142]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0-insider
- OS Version: Windows 10, Version	10.0.19043 Build 19043

Info:

All the other vim comands, such as "x" to delete a character or "DIW" to delete a word work, except for "u" for undo.
However, when I press Ctrl +Z - that works alright.

Attached video for reference.

Steps to Reproduce:

https://user-images.githubusercontent.com/60401095/128261399-38a88a3f-d280-494d-9b0b-7505b084fe89.mp4

**Comment by siva-msft** [comment]
This issue occurs only in Notebooks, the regular editor works fine. Should I keep this issue here, or file it in the vscode-jupyter repo?

**Comment by rebornix** [comment]
@siva-msft thanks for reporting this issue. I'll take a look. We might need some change in the Vim extension.

**Comment by rebornix** [comment]
Moved to extension https://github.com/VSCodeVim/Vim/issues/6960
