### ISSUE TITLE
Multi-line Next Match Selection (Cmd+D)

### ISSUE THREAD

**Issue by ElChupacabra26** [Microsoft/vscode#13016]
- VSCode Version: 1.5.3
- OS Version: OSX Yosemite 10.10.5

I'd like to request multi-line selection matching (ala Sublime). Right now, if you have a code snippet like this, you would only be able to match-next if your selection spans a single line (i.e. `<p class="someHtml">`):

```
<p class="someHtml">
    Test Word 1
</p>
<p class="someHtml">
    Test Word 2
</p>
<p class="someHtml">
    Test Word 3
</p>
```

It's really useful to be able to do a multi-line match-next, as in:

```
<p class="someHtml">
    Test
```

**Comment by Bill-Stewart** [comment]
So you are saying that it would be good if `addSelectionToNextFindMatch` (default <kbd>ctrl</kbd>+<kbd>d</kbd>) and `addSelectionToPreviousFindMatch` (no default keybinding) worked if the selection spans more than one line. Is that correct?

**Comment by atombender** [comment]
I also want this. This is pretty basic, core (by which I mean absolutely necessary; it's burned into my muscle memory now) functionality supported by Atom and Sublime.

To clarify (based on @Bill-Stewart's query). If you have this:

```
some
random text
some
random text
some
random text
```

and select this:

```
{{some
random}} text
some
random text
some
random text
```

and hit cmd-D two times, then you should have selected:

```
{{some
random}} text
{{some
random}} text
{{some
random}} text
```

I.e., cmd-D should not consider lines, only matches.

**Comment by alexandrudima** [comment]
:+1: This was very easy to implement, since now we support multi-line searches in the model.

**Comment by ElChupacabra26** [comment]
I'm late to the party, but nice job! Thanks guys 💃
