### ISSUE TITLE
Auto import not working where it should (ReactJS)

### ISSUE THREAD

**Issue by MGMehdi** [microsoft/vscode#130164]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- VS Code Insider Version: 1.59.0
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. `npx create-react-app test`
2. `cd test`
3. `npm install @material-ui/core`
4. Write a Material-UI component in `div` tag
5. No import for node module

![no_auto_import](https://user-images.githubusercontent.com/48625769/128313962-4b69034f-af47-4291-a366-37b525d90446.gif)

**Comment by mjbvz** [comment]
When you're typing `Button` inside the JSX, you just typing text. You need to type an opening `<` to indicate that you are referencing a symbol

**Comment by MGMehdi** [comment]
It still not working. And now with the version 1.59 of VSCode nothing work like previous gif. I need to manually import `material-ui`

![no_auto_import2](https://user-images.githubusercontent.com/48625769/128509155-c86dac90-5e33-4d6e-afcf-f13ddc58a0fa.gif)
