### ISSUE TITLE
Color theme issue when reloading window after change of System color scheme

### ISSUE THREAD

**Issue by pierre-nedelec** [microsoft/vscode#130160]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0-insider (but it's been doing this for many versions, even non insiders)
- OS Version: macOS 11.4 (20F71)

Steps to Reproduce:

1. Set `window.autoDetectColorScheme` to `true`
2. Set OS theme to Light
3. Launch VS Code: it should be in Light theme
4. Change OS theme to Dark: VS Code theme changes automatically to Dark theme
5.  Hit `Reload window`, when it reloads the theme changes back to the opposite, instead of staying as it should be!

**Comment by michaelgray19840000** [comment]
#118550

**Comment by pierre-nedelec** [comment]
The previous comment has nothing to do with this issue.
@aeschli is it related to [this comment](https://github.com/microsoft/vscode/issues/105102#issuecomment-686559146)?
