### ISSUE TITLE
Logging in with GitHub account fails with "Writing login information to the keychain failed UNIX [No such file or directory]"

### ISSUE THREAD

**Issue by kypeli** [microsoft/vscode#130156]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3)
- OS Version: MacOS Big Sur 11.4

Steps to Reproduce:

1. Log out from the currently logged in account and have a previous Live share account logged in.
2. Restart Code
3. From the Live share extension, select "Start sharing" or "Join session" so that Live share extensions asks to login.
4. Select "GitHub".
5. Proceed to authenticate on GitHub and press "Continue" on "Authorize Visual Studio Code to access GitHub" in order to return to Code.

Expected outcome: Authentication is successful and Live share session is starting.
Actual outcome: Error "Writing login information to the keychain failed with error "UNIX[No such file or directory]'

Please see the screenshot below:
<img width="382" alt="Screenshot 2021-08-05 at 6 19 56" src="https://user-images.githubusercontent.com/39245/128286933-86a75026-4442-43d9-8501-6b781099d109.png">

Please also note that I was able to reproduce this multiple times yesterday and once today. But just prior to writing this bug report just to double check my steps, it seemed I couldn't reproduce this issue and now I am logged in with the GitHub account. I am sure I didn't do any other steps than before and I did see this error on multiple occasions, so I am confident that there is some issue. 

Please let me know if you need any other details.

**Comment by kypeli** [comment]
Just something that came to me that might be different when the error occurred and when it didn't; When the error happened, I wasn't automatically redirected back to Code from the GitHub page after a successful authentication, but instead OS X presented me with a dialog asking if I want to open the URL in Code (to which I answered "Open"). 

Last time when I tried to reproduce this, I don't think I saw that dialog, but focus was taken to Code after login.

So this could be something.

**Comment by TylerLeonhardt** [comment]
Can you provide the contents of the GitHub Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128581415-dea0bda9-9af1-4874-afd6-30f20a815bdf.png)


And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Toggle Dev Tools"
* "Console" tab

![image](https://user-images.githubusercontent.com/2644648/128581434-fa68c85e-6e07-431b-81a0-fed316e5e940.png)

**Comment by kypeli** [comment]
@TylerLeonhardt Thanks for the detailed instructions! However, this is a bit embarrassing; as when submitting the issue, I am no longer able to reproduce it. I tried to restart Chrome, VSCode, revoke VSCode authentication from within GitHub, but now I am every time able to make it work. Is there still something I can try to "reset" the situation? 

I am pretty sure this is somehow related to the fact that when this issue occurred, it was Chrome that asked if I should let VSCode open the callback URI after a successful authentication and giving permission to VSCOde to use the authentication. While, now when it is working, the focus is immediately taken back to VSCode and a dialog popups in while VSCode has focus that asks if I want VSCode to handle the URI.

**Comment by kypeli** [comment]
I now also tried to reproduce this by removing the GitHub Authentication extensions' entry from macOS KeyChain and the retrying. It just works for me now every time.

**Comment by katopz** [comment]
I just bump into this today.
```
[Info  - 15:25:56.414] Reading sessions from keychain...
[Info  - 15:25:56.414] Reading sessions from keychain...
[Info  - 15:25:56.549] Getting sessions for all scopes...
[Error  - 15:25:56.549] Getting token failed: Error: UNIX[No such file or directory]
[Info  - 15:25:56.554] Getting sessions for read:user...
[Info  - 15:25:56.554] Getting sessions for all scopes...
[Info  - 15:25:56.614] Got 0 sessions for all scopes...
[Info  - 15:25:56.614] Got 0 sessions for read:user...
[Info  - 15:25:56.614] Got 0 sessions for all scopes...
[Info  - 15:37:37.373] Getting sessions for all scopes...
[Info  - 15:37:37.373] Getting sessions for all scopes...
[Info  - 15:37:37.373] Got 0 sessions for all scopes...
[Info  - 15:37:37.373] Got 0 sessions for all scopes...
[Info  - 15:37:43.7] Getting sessions for all scopes...
[Info  - 15:37:43.7] Got 0 sessions for all scopes...
[Info  - 15:37:45.43] Logging in for the following scopes: user:email
[Trace  - 15:37:55.965] Handling Uri...
[Info  - 15:37:55.965] Exchanging code for token...
[Info  - 15:37:57.293] Token exchange success!
[Info  - 15:37:57.295] Getting user info...
[Info  - 15:37:57.835] Got account info!
[Info  - 15:37:57.836] Storing 1 sessions...
[Error  - 15:37:58.514] Setting token failed: Error: UNIX[No such file or directory]
```

```
workbench.desktop.main.js:sourcemap:2899 [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:sourcemap:2899
workbench.desktop.main.js:sourcemap:62 [Extension Host] (node:71127) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
S @ workbench.desktop.main.js:sourcemap:62
workbench.desktop.main.js:sourcemap:1735 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/katopz/.vscode/extensions/redhat.vscode-yaml-0.22.0/syntaxes/yaml.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1735
workbench.desktop.main.js:sourcemap:749 Writing login information to the keychain failed with error 'UNIX[No such file or directory]'.
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:749
```

remove keychain didn't seem to work for me.

**Comment by jameszp** [comment]
I had this issue as well. I was able to resolve it by granting full disk access to the terminal app.

**Comment by TylerLeonhardt** [comment]
@jameszp interesting thought. Can you mention how you did this?

**Comment by jameszp** [comment]
@TylerLeonhardt I was able to go to System Preferences > Security & Privacy > Full Disk Access and manually grant the permission to the Terminal app through the GUI. I was originally trying to solve another problem with my machine, but granting the full disk access solved this problem as well. My assumption is that the terminal needs full disk access for VSCode to complete a token exchange.

**Comment by joshunger** [comment]
@TylerLeonhardt Is there a way I can see the GitHub Authentication log from a previous launch? I ran across this same issue but resolved later in the day.

**Comment by TylerLeonhardt** [comment]
Sadly no. Output is purged when you start a new session.

**Comment by TylerLeonhardt** [comment]
I think this should be fixed now that we don't hammer the keychain anymore. I have not heard of any reports like this recently after we moved to the Electron API to store secrets so optimistically closing this. Please let me know if you do still see this in recent versions of VS Code.
