### ISSUE TITLE
public class Javaapplication142

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode#130169]
Issue Type: <b>Performance Issue</b>

いつまでたっても、完結しません。何が不足していますか。codeとしては問題なしかと思っているのですが？

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>Workspace Info</summary>

```
|  Window (class Application142.txt - .vscode - Visual Studio Code)
|    Folder (.vscode): 6 files
|      File types: json(3) txt(1)
|      Conf files: launch.json(2) settings.json(1);
```

</details>
<details><summary>Extensions (104)</summary>

Extension|Author (truncated)|Version
---|---|---
dibs-sassy|1st|0.0.4
vscode-languagetool|ada|3.8.0
vscode-languagetool-ja|ada|3.8.0
shift-shift|ahg|0.0.5
ng-template|Ang|12.2.0
go-restart|art|0.0.2
azps-tools|azp|0.1.0
SecurityIntelliSense|azs|0.8.0
vscode-django|bat|1.6.0
shell|bbe|0.3.0
vscode-log-viewer|ber|0.12.2
django-html|bib|1.3.0
c-compiler|bra|0.0.4
GBK2UTF8|buu|0.6.0
markdown-zenkaku-indent|ccn|0.0.1
vscode-translate|chu|0.1.5
shift-saver|cor|1.1.0
jison-syntax-highlight|cru|0.1.1
c-cpp-compile-run|dan|1.0.14
vscode-markdownlint|Dav|0.43.2
javadebugger|don|0.1.5
python-extension-pack|don|1.6.0
java-debug|DSn|0.0.2
prettier-vscode|esb|8.1.0
hujiang|Exi|0.0.3
nuget4code|ffo|0.0.2
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
docker-explorer|for|0.1.7
japanese-novel-extension-pack|fuj|0.1.0
markdown-preview-fuji-styles|fuj|0.1.3
markdown-ruby|fuj|1.0.1
vscode-google-translate|fun|1.4.13
meet|gee|0.1.6
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.28.0
google-cloud-spanner-driver|goo|0.4.0
google-translate|han|1.2.3
vscode-hyphaene|hyp|0.0.29
turbo-console-debuglog|ida|1.0.0
encdetectjp|ino|0.0.1
powershell-universal|iro|2.1.1
powershellprotools|iro|5.29.4
auto-translate-json|jef|1.0.9
shiftthat|Jim|0.1.2
vscode-nuget-package-manager|jmr|1.1.6
vscode-keyboard-master|jon|1.0.0
google-search|kam|0.0.1
kite|kit|0.147.0
kitety-vsc-extension-demo|kit|0.0.2
rg-sjis|kom|0.2.8
google-fonts|lio|0.0.1
grade-calculator|lou|1.0.0
kite-snippets-basic|lum|0.0.2
MagicPython|mag|1.1.0
markdown-it-container-question|Mat|0.0.1
mp-starter-vscode-ext|Mic|0.2.6
r|Mik|0.0.25
vscode-kite|mrk|0.0.2
vscode-docker|ms-|1.15.0
vscode-language-pack-ja|MS-|1.58.8
mssql|ms-|1.10.1
remote-wsl|ms-|0.58.2
cpptools|ms-|1.5.1
powershell|ms-|2021.6.2
powershell-preview|ms-|2021.8.0
sqltools|mtx|0.23.0
jspm|Neo|3.0.4
pseudocode|noa|0.4.0
keyboard-quickfix|pas|0.0.6
vscode-nuget-gallery|pat|0.0.24
vscode-versionlens|pfl|1.0.9
heroku-command|pko|0.0.8
platformio-ide|pla|2.3.2
vscode-jsp|pth|0.0.3
java|red|0.80.0
vscode-commons|red|0.0.6
laravel-5-snippets|sac|2.0.1
remove-non-ascii-chars|Sam|0.0.5
vscode-base64-encoding-decoding|san|1.1.2
japanese-word-handler|sgr|1.2.2
shiftleft-scan|Shi|1.3.0
vscode-vuln-cost|sny|1.6.0
swdc-vscode|sof|2.5.21
tabnine-vscode|Tab|3.4.21
vscode-typenovel|tat|0.0.1
python|tht|0.2.3
run-in-powershell|tob|1.1.0
decode|ttf|0.1.0
tips|uyi|1.0.3
non-breaking-space-highlighter|vik|0.0.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.2
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.2
vscode-spring-initializr|vsc|0.7.0
jinja|who|0.0.8
vscode-input|wil|0.0.6
generic-pseudocode|Wil|1.4.0
vscode-reflow-japanese|yod|1.0.0
nadesiko3-vscode|yy0|1.19.4
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by hiroshi-nakajima345** [comment]
//(1)my.main.code.
import java.io.*;

public class JavaApplication142 {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String[] args)throws IOException {
        // TODO code application logic here
        System.out.println("文字を入力してください");
        
        BufferedReader br =
                new BufferedReader(new InputStreamReader(System.in));
        
        String str = br.readLine();
        
        System.out.println(str + "が入力されました");
                
    }}

   // Dmaven.defaultprojectBuider.disableGlobalModelCaChe=true//this part added after first code making

/＊(2)(I think) defect ? of my coding
①I think that the contents of my(first) coding have not syntax error →Is this possible?
 
❷how to make code(projedt setting):a.Is there any problem ? to use ide in"create new  project" 
                                                      b.is there any appriate way?

③problem of character code;
i use usually UTB-8,
but in this case have I to use any oter code(for example<shift_jis>etc)

④other　problem：
 is there any ;
please teach me.

incomplete・・・


----- 元のメッセージ -----
From: "VS Code Issue Triage Bot" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Author" ***@***.***>
送信済み: 2021年08月05日 午後 6:43
件名: Re: [microsoft/vscode] public class Javaapplication142 (#130169)

>  この問題を作成してくれてありがとう!しかし、説明は英語ではないため、私たちはそれに取り組むのが難しいです。もし、可能であれば、英語で行くように編集してください。新しいコメントを追加したり、新しい懸案事項を作成したりするのではなく、既存の懸案事項を編集してください。残念ながら、自動翻訳サービスはソフトウェアの問題について効果的にコミュニケーションを取るために必要な技術言語を扱うことはできないので、翻訳を支援する技術に精通している人の翻訳者を見つけることをお勧めします。それ以外の場合、この問題は翻訳が必要であるとマークされており、コミュニティメンバーが翻訳を支援できる場合があります。Thanks for creating this issue!Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.Otherwise, we have marked this as needing translation and a community member may be able to help out.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CodeCrazy-ywt** [comment]
**Here's translation by Google Translate:**
It will never be completed.  What are you missing?  I don't think there is a problem with the code?

**Comment by CodeCrazy-ywt** [comment]
@hiroshi-nakajima345 
What's wrong?
どうしたの？

**Comment by hiroshi-nakajima345** [comment]
I tried toadd "Run｜Debug"
But , the code cannot run

**Comment by rzhao271** [comment]
\gifPlease

**Comment by rzhao271** [comment]
You can also check out https://code.visualstudio.com/docs/languages/java, though I'm not sure if the page is available in Japanese.

**Comment by hiroshi-nakajima345** [comment]
①
I changed  code like this
//package hn1;
import java.io.*;
public class HNsample_1 {

	
		// TODO Auto-generated method stub
		//Run|Debug
		 public static void main(String[] args) throws IOException {


				
			 System.out.println(" Input string array");
				BufferedReader br =
				new BufferedReader(new InputStreamReader(System.in));
				String str = br.readLine();
				
				System.out.println(str + "be Inputed");
			}}


<but> could not run
❷ if possible 
please show me  the model using VSC
it'll be helpful.
added how to use keyboard short cut .more understadable ?




----- 元のメッセージ -----
From: "VS Code Issue Triage Bot" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Mention" ***@***.***>
送信済み: 2021年08月11日 午前 4:30
件名: Re: [microsoft/vscode] public class Javaapplication142 (#130169)

>  Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, .gif files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette).Happy coding!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
