### ISSUE TITLE
Allow for more flexible layout options when moving a group via drag and drop

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#130131]
as i commented in https://github.com/microsoft/vscode/issues/49923#issuecomment-892837423.
first split to editor like this:
```
______________
|      |     |
|      |     |
|______|_____|
````
then try to add new editor to the bottom of those, like this:
```
______________
|      |     |
|      |     |
|______|_____|
|            |
|____________|
```

https://user-images.githubusercontent.com/26390254/128228925-9434eb22-b375-460e-b65f-fcf0b1aa933f.mp4

**Comment by hediet** [comment]
Can you add more details to your feature request?

**Comment by byehack** [comment]
> Can you add more details to your feature request?

i don't know i should tag here as issue or feature request.
as i said we should able to group the editor like this:
```
______________
|      |     |
|      |     |
|______|_____|
|            |
|____________|
```
we can not do it now.

**Comment by hediet** [comment]
This layout is possible:

![image](https://user-images.githubusercontent.com/2931520/128387508-216f9fb4-359e-4608-86f2-e49727b3e53e.png)

**Comment by ArturoDent** [comment]
Split down first, then split right gets you the configuration you want.  The question is: should the order of the splits matter?

**Comment by byehack** [comment]
> This layout is possible:
> 

can u reach that layout after splited like below?
(without close the right or left side splited editor completely)
![image](https://user-images.githubusercontent.com/26390254/128559213-8e22a0b7-b28c-4cce-8f5a-314167bb989e.png)

**Comment by hediet** [comment]
Now I understand. I think this feature request makes sense.

Please update your initial commit to describe the current situation and the improvement you would like to see.

**Comment by bpasero** [comment]
I think the issue is around the fact that split always operates in the active group and not outside that group, so when you split the right group down it will end up as 2 groups in that space and you will not see a editor group create from the primary group.

How would you expect this to work? If we were to change this behaviour you would have equal amount of people that complain that the current behaviour is not possible. I think the current behaviour is more intuitive though.

**Comment by byehack** [comment]
we can use seprate line.
when drag a tab on seprate line it will preview new set.
![image](https://user-images.githubusercontent.com/26390254/128610375-b911146d-7d76-4fef-ad58-83ef54b785ed.png)

**Comment by bpasero** [comment]
I am not entirely sure we can do that without loosing the ability to split within the group then:

![recording](https://user-images.githubusercontent.com/900690/128622687-6b79d4cc-e286-4c14-9522-9581dfba8420.gif)

**Comment by hediet** [comment]
Visual Studio has a nice solution for this afaik: They show temporary drop locations for various areas. I think in this case, they would show a symbol like this:

![image](https://user-images.githubusercontent.com/2931520/128668682-2fd92504-fe26-45c5-a51a-819712829391.png)

If you drop the editor on it, it will create the requested layout.

**Comment by bpasero** [comment]
Yeah I like what VS allows you to do but find the UI a bit heavy. Fair feature request

//cc @joaomoreno
