### ISSUE TITLE
Allow extension walkthroughs to use themed SVGs

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#130153]
Theme-able SVGs only work for VS Code's built-in walkthroughs right now. To keep extension assets small, providing the same capability would help.

Also mentioned in https://github.com/microsoft/vscode-azurestaticwebapps/issues/397.

**Comment by misolori** [comment]
@JacksonKearl do you know if this will make it in for this month? The Python team is also interested in this cc @lydiayschung @luabud

**Comment by JacksonKearl** [comment]
Tightened up the CSP used for hosting the svg webviews and allows extensions to contribute svg's using a `media: { svg: ...` syntax.

**Comment by JacksonKearl** [comment]
cc @mjbvz if this is reasonable from security perspective. We're taking a file from the extension (expected to contain the `svg` in plaintext) and loading it into a webview with the root unset and scripts prohibited, with CSP `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}';">`

**Comment by sandy081** [comment]
Are there any steps to verify this?

**Comment by JacksonKearl** [comment]
@sandy081 you can try it out with the sample extension: https://github.com/microsoft/vscode-extension-samples/blob/main/getting-started-sample/package.json#L95-L103

![image](https://user-images.githubusercontent.com/8586769/130655522-f3d86235-ebf0-4709-a200-c08d27abf657.png)
