### ISSUE TITLE
Terminal Process terminated if the folder contains Chinese characters

### ISSUE THREAD

**Issue by zhanggy** [Microsoft/vscode#13013]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open a folder containing Chinese Characters, such as 'D:\Workspace\project\周报'
2. press Ctrl+`, open build-in terminal, error issues: 
         The terminal process terminated with exit code: 1

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727
