### ISSUE TITLE
Stdout generated raw data file not in expected format.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#130187]
Version: 1.59.0-insider (user setup)
Commit: 8f58c1f457bd2ddf6cf81120c450c783b6e8c01b
Date: 2021-08-04T09:44:34.203Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

In a Python notebook or interactive session
```python
for i in range(1,1000):
    print(i)
```
2. When done click on "show more (open the raw output data in a text editor) ..."
![image](https://user-images.githubusercontent.com/11685408/128382149-dd1136b5-e9fa-4fb8-bffc-1f7cbd0d438d.png)

I would have expected to just see a file with numbers from 1 to 1000

**Comment by rebornix** [comment]
Make sense to me. For single mimetype output, we should directly convert that to the right format.
