### ISSUE TITLE
"typescript.tsdk" isn't sticking in workspace config/not-relative to workspace file.

### ISSUE THREAD

**Issue by jsg2021** [microsoft/vscode#130118]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: Fedora 34

Steps to Reproduce:

1. set up npm 7 workspace where each project's dependencies in the workspace are hoisted to the workspace root node_modules. with this basic package.json: (and some projects under packages)
    ```json 
    {
      "name": "my-workspace",
      "workspaces": [
        "./packages/*"
      ]
    } 
    ```
    workspace.code-workspace:
    ```json 
    {
      "folders": [
        { "path": "projects/a" },
        { "path": "projects/b" }
      ],
      "typescript.enablePromptUseWorkspaceTsdk": true,
      "typescript.tsdk": "node_modules/typescript/lib/" // this should work, the path should be relative to the code-workspace file
    }
    ```
2. manually edit workspace config to point to "../node_modules/typescript/lib".
3. select it from the picker (notice it works)
4. quit & reopen
5. "typescript.tsdk" in the code-workspace file now points to "node_modules/typescript/lib", and the picker no longer shows it as an option. However, all projects within the workspace are shown in the picker, but each has a notice that it couldn't find typescript within. (which is expected since all node_modules are hoisted to the root of the workspace)

**Comment by mjbvz** [comment]
Marking as a feature request since this hasn't been supported previously

**Comment by jsg2021** [comment]
really? i would think any workspace shape supported by your format should work. The glitch is just with multi-root projects. It appears to mostly work. Just a little rough around the picker.

**Comment by yifanwww** [comment]
You can add workspace root folder into your *.code-workspace file, like this:

```json
{
    "folders": [
        {
            "name": "repo-name",
            "path": "."
        },
        {
            "name": "a",
            "path": "projects/a"
        },
        {
            "name": "b",
            "path": "projects/b"
        }
    ],

    "typescript.enablePromptUseWorkspaceTsdk": true,
    "typescript.tsdk": "repo-name/node_modules/typescript/lib"
}
```

What I guess is that the first folder name of the path in the `typescript.tsdk` option targets to a workspace folder.

So this path `repo-name/node_modules/typescript/lib` targets to the package `typescript` in your workspace root `node_modules`, as the workspace root is named `repo-name` in the *.code-workspace.
