### ISSUE TITLE
Cannot connect to marketplace

### ISSUE THREAD

**Issue by agilob** [microsoft/vscode#130119]
Issue Type: <b>Bug</b>

CORS request error 

![image](https://user-images.githubusercontent.com/2544251/128212411-aaf33733-fc6e-41e5-b442-47a8533141b9.png)

VS Code version: VSCodium 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-16T00:15:55.196Z)
OS version: Linux x64 5.10.55-1-lts
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3959)|
|Load (avg)|1, 1, 2|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

installed from [vscodium-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vscodium-bin)

**Comment by agilob** [comment]
Just found I have to install `vscodium-bin-marketplace` as well, sorry guys

**Comment by codingwithdeepak** [comment]
not helped me, i installed amd64.deb from github as it works in my laptop
