### ISSUE TITLE
Dragging an item from file explorer to finder returns an empty file

### ISSUE THREAD

**Issue by massimo-cassandro** [microsoft/vscode#130112]
Issue Type: <b>Bug</b>

With previous versions of VSCode I was able to copy a file from file explorer to desktop or other position by dragging it. Last version of VSCode produces an empty file.

Step to reproduce:
Drag a file from file explorer to a target position

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv|--crash-reporter-id dd71f715-6c21-4334-88c0-cf8405aa43b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.0.1
accessibility-snippets|acc|0.8.0
spaces-inside-braces|Air|0.4.0
project-manager|ale|12.3.0
vscode-sqlite|ale|0.13.0
copy-path|and|0.1.1
vscode-twig-pack|baj|1.1.0
auto-align|bla|0.0.13
file-properties-viewer|bru|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|2.1.23
vscode-faker|dee|1.5.0
githistory|don|0.6.18
permute-lines|ear|1.1.0
replacequotes|eda|0.0.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
html-to-javascript-string|evi|0.0.6
comment-anchors|Exo|1.9.6
nasc-touchbar|fel|1.12.0
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
copilot|Git|1.3.2225
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
vscode-favorites|how|1.9.1
mysql-syntax|jak|1.3.1
svg|joc|1.4.9
string-manipulation|mar|0.5.2
open-with-finder|maz|1.1.0
preview-in-browser|maz|2.1.1
twig-language-2|mbl|0.9.2
vscode-language-babel|mgm|0.0.31
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.10.0
vscode-language-pack-it|MS-|1.58.8
live-server|ms-|0.2.6
vscode-react-native|msj|1.5.2
json-parse-stringify|nex|1.0.2
subtitles-editor|pep|1.1.6
explorer-exclude-vscode-extension|Red|1.2.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.6.1
sql-snippets|sad|0.0.4
vscode-sql-beautify|sen|0.0.4
vscode-stylelint|sty|0.86.0
auto-correct|syg|0.2.2
pdf|tom|1.1.0
sort-lines|Tyr|1.9.0
html-snippets|wge|0.1.5
twig|wha|1.0.2
vscode-file-extra|wil|3.1.0
better-align|wwm|1.1.6
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by isidorn** [comment]
I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
