### ISSUE TITLE
JS: optional or `undefined` is not supported from JSDoc annotations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130163]
For example, `codeCachePath` is declared as `string | undefined` but the language service seems to indicate it is just `string`:

https://github.com/microsoft/vscode/blob/b6ca3e52ae62b64f7e30009bed4402a0235a4e92/src/main.js#L125-L125

Similar `appRoot` is declared as `string=` but appears as `string` too:

https://github.com/microsoft/vscode/blob/b6ca3e52ae62b64f7e30009bed4402a0235a4e92/src/bootstrap.js#L50-L50

**Comment by mjbvz** [comment]
This is because strict null checks are disabled in this file

The file is not part of a project (you can check by running `JavaScript: Go to project configuration`). Strict null checks default to off for any files that are not part of a project

To fix this, just add a jsconfig and turn strict null checks on

**Comment by bpasero** [comment]
I tried that but it still does not work, when I pick "Go to project configuration" even after creating that file from the notification, it still complains that it cannot find the project configuration.

**Comment by bpasero** [comment]
Hm maybe you cannot have `//@ts-check` and `jsconfig.json` together?

**Comment by IllusionMH** [comment]
AFAIK `jsconfig.json` will be ignored if there is `tsconfig.json` in same folder.
Adding `"allowJs": true,` to `compilerOptions` and `"./*.js"` (or specific files) to `includes` will check that files, but also include them in output if used with `tsc` and probably pollute global scope if some specific libs/imports were used in those JS files

**Comment by mjbvz** [comment]
Yes this is correct. To confirm that the js file is in the correct jsconfig project, run `JavaScript: Go to project configuration` with the file open
