### ISSUE TITLE
Terminal editor tab displays content from another terminal editor tab

### ISSUE THREAD

**Issue by hinst** [microsoft/vscode#130110]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.59.0
- OS Version: Windows 10

<details>
<summary>Full VSCode version info</summary>

* Version: 1.59.0-insider (user setup)
* Commit: cead2f699cd0afb2464d8d3ad975776051583b4f
* Date: 2021-08-03T16:24:47.105Z
* Electron: 13.1.7
* Chrome: 91.0.4472.124
* Node.js: 14.16.0
* V8: 9.1.269.36-electron.0
* OS: Windows_NT x64 10.0.19043
</details>

Steps to Reproduce:

1. Open three editor tabs: 1x source, 2x terminal
2. Click on editor tab headers to change tabs
   1. Source
   2. Terminal 2
   3. Source
   4. Wait a minute
   4. Terminal 1
   5. Terminal 2
3. Notice how content of the Terminal 2 appears in Terminal 1

Video reproduction: https://youtu.be/j2tWKjEtOjk

Additional notes
* Happens on both Stable and Insiders versions
* Does not happen 100% of the time; but still happens fairly often (about every 5 minutes)
* Workaround: switch terminal tabs again

**Comment by akshayvijapur** [comment]
any timeline. It is affecting badly ?

**Comment by jeanp413** [comment]
Created a PR #131211 fixing this
