### ISSUE TITLE
Autocomplete/syntax & type validation performance is horrendous in 1.5.3

### ISSUE THREAD

**Issue by oheard** [Microsoft/vscode#13011]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:
1. Open two files
2. Declare a class in one file
3. Use that class incorrectly in the other file (e.g., non-existent member access)
4. Note the squiggly line
5. Correct the error
6. Wait 60 seconds for VSCode to update the squigglies

Also:
1. Do steps 1-2 above
2. Type something something "dot"
3. Wait ages for autocomplete to pop up, observe the text "Loading..."

**Comment by joaomoreno** [comment]
Which language?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate.

@oheard Please let us know if you still see this in VSCode 1.8.1. If so, for what languages? Do you have any extensions installed?

Thanks
