### ISSUE TITLE
Menus do not always initialise correctly

### ISSUE THREAD

**Issue by oheard** [Microsoft/vscode#13012]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Open VSCode several times
2. Note that sometimes entire menus are missing from the menu bar, e.g., "File" or "Help" is completely absent.

**Comment by bpasero** [comment]
Yeah, known upstream issue.  https://github.com/Microsoft/vscode/issues/8901
