### ISSUE TITLE
Switch app windows keyboard shortcut not working on OS X

### ISSUE THREAD

**Issue by himion0** [Microsoft/vscode#13015]
- VSCode Version: 1.5.3
- OS Version:  OSX '15.6.0'

Steps to Reproduce:

1. Open VSCode
2. Open a new window
3. Attempt to use CMD ` to change app windows

**Comment by bpasero** [comment]
I think we fixed this with our electron update recently in our insiders build. 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by himion0** [comment]
Thanks! Can confirm this is working now on OSX El Capitan

**Comment by bpasero** [comment]
Cool 👍
