### ISSUE TITLE
The esbuild binary is present in official Visual Studio Code downloads

### ISSUE THREAD

**Issue by evanw** [microsoft/vscode#130158]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2
- OS Version: macOS 11.5.1

Steps to Reproduce:

1. Visit https://code.visualstudio.com/ on macOS
2. Click "Download Mac Universal Stable Build"
3. Observe that the downloaded app contains `Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/esbuild/bin/esbuild`, which is the x86_64 esbuild executable for Linux

I'm the author of [esbuild](https://github.com/evanw/esbuild) and a user of Visual Studio Code. I was surprised to discover the esbuild binary executable inside of Visual Studio Code and I figured I should let you know. I assume this is unintentional because the executable is for the wrong operating system, so I can't see how it would ever be used.

It's inclusion appears to be harmless but it means that around the world, each and every person who is downloading Visual Studio Code has to **download an extra 7.3mb of useless data!** Edit: Well, I guess it's compressed so the download size is around 3mb, but the on-disk size is around 7mb.

I'm not sure how esbuild is used in this project so I'm not sure what to do to fix this. If it's only being used at build-time and isn't used at run-time, it would be beneficial to install it somewhere else so it's not included in the packaged app. I noticed it's listed in `devDependencies`. Maybe the problem is that `devDependencies` are being packaged when they shouldn't be?

**Comment by bpasero** [comment]
Thanks for discovering this! at least this does not look like a recent regression, I can find `esbuild` in our previous stable release too.

**Comment by bpasero** [comment]
Looks like it came in from https://github.com/microsoft/vscode/commit/7770708545cab5d18a3104fc700723c7d6193d39

**Comment by mjbvz** [comment]
I also see `vscode-grammar-updater` there. Both `esbuild` and `vscode-grammar-updater` are correctly listed as devDependencies so I'm not sure why they are being packaged 

@joaomoreno May know more but we might need this sort of logic to make sure we only include prod dependencies in `extensions/node_modules`: https://github.com/microsoft/vscode/blob/9cfba54681045160ad3cf87d0f3e87c71d775740/build/lib/dependencies.ts#L61

**Comment by gkiely** [comment]
> I also see `vscode-grammar-updater` there. Both `esbuild` and `vscode-grammar-updater` are correctly listed as devDependencies so I'm not sure why they are being packaged
> 
> @joaomoreno May know more but we might need this sort of logic to make sure we only include prod dependencies in `extensions/node_modules`:

Try checking the yarn version. I couldn't see any references to it in the repo but if it's using an older version for the CI/build it might be running into this issue: https://github.com/yarnpkg/yarn/issues/4542
