### ISSUE TITLE
Windows remote smoke tests fail

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#130197]
The Windows remote smoke tests (which aren't running in the CI) fail when run locally due to an issue in the before hook.

**Comment by alexdima** [comment]
It worked for me when I executed `yarn smoketest --remote` on `main`.

**Comment by joaomoreno** [comment]
> due to an issue in the before hook

Fantastic details here.

Please investigate this yourself, having a reproducible way to have it fail is half way of fixing the issue.

**Comment by rzhao271** [comment]
I was running the tests from the wrong repository. Closing and updating the docs.
