### ISSUE TITLE
Unable to open a workspace or project

### ISSUE THREAD

**Issue by tamipangadil** [microsoft/vscode#130152]
Issue Type: <b>Bug</b>

I'm using VS Code on Manjaro Xfce system. Everytime I start my PC after hibernation, it won't open any workspace or project but still keeping my previously opened windows. My interim solution is to restart my PC.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.10.53-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 4199)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.33GB (20.01GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 401b8ccd-a0c3-4b28-ac08-130f96109c41|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-sql-formatter|adp|1.4.4
vscode-nginx-conf|ahm|0.1.3
jest-snippets|and|1.8.0
vscode-apollo|apo|1.19.4
markdown-preview-github-styles|bie|0.2.0
gotemplate|cas|0.4.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-zonefile|Com|0.0.4
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
gitlens|eam|11.6.0
json-tools|eri|1.0.2
prettier-vscode|esb|8.1.0
flow-for-vscode|flo|1.9.1
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
vscode-graphql|Gra|0.3.16
vscode-nginx-conf-hint|han|0.1.0
terraform|has|2.14.0
path-autocomplete|ion|1.17.1
RelativePath|jak|1.4.0
cypress-fixture-intellisense|Jos|1.2.0
vscode-github|Kni|0.30.6
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
compare-folders|mos|0.22.2
graphql|mqu|0.1.2
python|ms-|2021.7.1060902895
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.8.1054968649
remote-containers|ms-|0.187.1
color-highlight|nau|2.4.0
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.8.0
text-power-tools|qcz|1.28.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
scala|sca|0.5.4
metals|sca|1.10.8
trailing-spaces|sha|0.3.1
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.6.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by deepak1556** [comment]
Can you check if the issue happens with our insiders https://code.visualstudio.com/insiders

**Comment by tamipangadil** [comment]
I could try this. Will this replace my whole vs code installation or will
have a separate one?

**Comment by deepak1556** [comment]
It will be separate.

**Comment by tamipangadil** [comment]
I have installed the insider version and the extensions I'm using. It looks like it wasn't affected after restarting my PC from hibernation. I'll continue using this version and alert you if problem occurs again. Thanks for the suggestion!

**Comment by deepak1556** [comment]
In which case please also check if the problem persists with next stable release (1.59) that will be available this week. Insiders get promoted to stable, so very likely the fix should be present.

**Comment by tamipangadil** [comment]
Awesome! I'll keep this issue open and circle back for the good and bad news. Thanks for the superb work and support.
