### ISSUE TITLE
connect EADDRNOTAVAIL 127.0.0.1:53769 - Local (192.168.1.121:52475)

### ISSUE THREAD

**Issue by GaikwadPratik** [microsoft/vscode#130111]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.58.2
       Commit: c3f126316369cd610563c75b1b1725e0679adfb3
       Date: 2021-07-14T22:09:06.581Z
       Electron: 12.0.13
       Chrome: 89.0.4389.128
       Node.js: 14.16.0
       V8: 8.9.255.25-electron.0
       OS Version: Darwin x64 20.6.0
- OS Version: Mac OS Big Sur(11.5.1 (20G80))
- Local Node version: 16.6.1
- Local npm version: 7.20.3

Steps to Reproduce:

1. Create a node js project.
2. Create launch.json with below contents:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/src/index.ts",
      "runtimeArgs": ["-r", "ts-node/register/transpile-only"],
      "envFile": "${workspaceFolder}/.env"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Testing",
      "program": "${workspaceRoot}/node_modules/.bin/mocha",
      "args": [
        "--config=test/.mocharc.json"
      ],
       "skipFiles": [
        "<node_internals>/**/*.js", "node_modules",
      ],
      "envFile": "${workspaceFolder}/.env.test",
      "trace": true
    }
  ]
}
```

Result:
![image](https://user-images.githubusercontent.com/5595263/128202785-90cc9977-98d8-48e7-966f-fce82bdfd965.png)

Let me know if anymore information is needed.

P.S. Same thing happens with `golang` projects as well

**Comment by connor4312** [comment]
Particularly since the same thing happens with Go projects, this seems like it's some permission error locally, perhaps an antivirus or firewall.

**Comment by GaikwadPratik** [comment]
I don't have any external firewall or antivirus installed. If I reboot my computer, then it starts to work fine. Not sure if something gets fixed with reboot on VSCode side

**Comment by connor4312** [comment]
This doesn't really seem like a VS Code related problem, especially if Go hits it too.

**Comment by GaikwadPratik** [comment]
There has to be something. Because right now I'm getting same thing and I sure didn't do anything special this week.

**Comment by togonow** [comment]
Having the same issue here. only fix is to restart the whole computer!!

**Comment by AlbertoMontalesi** [comment]
I'm also getting the same issue occasionally and the only fix is to restart my Mac

**Comment by GaikwadPratik** [comment]
@connor4312 , 

I think this bug needs to be reopened and worked on based on the feedbacks above. I am sure there would be many more

**Comment by connor4312** [comment]
So far we have not received other reports, and this does not seem to be related to VS Code

**Comment by connor4312** [comment]
So far we have not received other reports, and this does not seem to be related to VS Code

**Comment by togonow** [comment]
I can see 4 reports same exact issue on this page. What you mean about not received other reports?

> So far we have not received other reports, and this does not seem to be related to VS Code

**Comment by josep11** [comment]
I have mac OS 10.14 Mojave and experiencing the same issue right now

**Comment by AlbertoMontalesi** [comment]
I figured out that it's related to my IP. I have cloudflare warp installed, if I run Warp, then start a debugger, then stop warp (disabling the VPN), I'll get that error. Re-enable the VPN, error gone. Double check if that's the case for you if you are having this issue.

**Comment by chitampopo** [comment]
> I figured out that it's related to my IP. I have cloudflare warp installed, if I run Warp, then start a debugger, then stop warp (disabling the VPN), I'll get that error. Re-enable the VPN, error gone. Double check if that's the case for you if you are having this issue.

Yes, it works

**Comment by LearnWithTung** [comment]
> I figured out that it's related to my IP. I have cloudflare warp installed, if I run Warp, then start a debugger, then stop warp (disabling the VPN), I'll get that error. Re-enable the VPN, error gone. Double check if that's the case for you if you are having this issue.

yes, You're right but how do we prevent that issue ? I don't want to enable Warp every time I run java

**Comment by omrilotan** [comment]
> I figured out that it's related to my IP. I have cloudflare warp installed, if I run Warp, then start a debugger, then stop warp (disabling the VPN), I'll get that error. Re-enable the VPN, error gone. Double check if that's the case for you if you are having this issue.

Wouldn't have occurred to me. Thank you!

**Comment by 1741Rishabh** [comment]
> I'm also getting the same issue occasionally and the only fix is to restart my Mac

I did it but it does't work

**Comment by fastnlight0** [comment]
Same here. I've tried everything. All I want is to be able to run my code. It used to work, but it doesn't anymore

**Comment by fastnlight0** [comment]
Just found a solution!
`$ sudo ifconfig lo0 alias 127.0.0.1 up`

**Comment by Map1eUM** [comment]
I have the same issue to connect to a new VPS server. SSH set. 

I will try $ sudo ifconfig lo0 alias 127.0.0.1 up

**Comment by Map1eUM** [comment]
> sudo ifconfig lo0 alias 127.0.0.1 up

It doesn't work:
alias: Unknown host
ifconfig: `--help' gives usage information.

Really want a solution to use VS code to connect VPS

**Comment by fastnlight0** [comment]
Try this command and tell me the first few lines of output:
`ping localhost`

**Comment by Map1eUM** [comment]
> @Map1eUM Try this command and tell me the first few lines of output: `ping localhost`

C:\Users\chenr5-INS>ping localhost

Pinging DESKTOP-62V5LQJ [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

looks good

**Comment by fastnlight0** [comment]
It looks like you are on windows. My solution is for MacOS. It doesn't look like it issue is the same as mine however.
