### ISSUE TITLE
opensMaximized preference doesn't give control over new windows

### ISSUE THREAD

**Issue by shepazon** [microsoft/vscode#130108]
The preference `workbench.panel.opensMaximized` lets you specify whether or not a window is opened maximized... which is great. But there's a catch: its only options are:

* `always`: All new windows open with the panel maximized
* `never`: Windows never open with the panel maximized
* `preserve`: Windows are opened with the panel in the state they were in last time they were closed.

This misses one specific scenario: You set the value to `preserve` because you want windows to open with their panels in the same state they closed in. But what should happen in this case for brand new windows? There needs to also be the option `preserveAndMaximizeNew`, to indicate that the current behavior should be followed but new windows should have maximized panels. If the preference is `preserve`, then, the panel would open minimized in new windows.

**Comment by sbatten** [comment]
@shepazon the text you use to describe each option for the setting is not from the product and is misleading. the setting is about how panels are opened when the command is triggered and not about window restoration.
