### ISSUE TITLE
Error: Could not get a unique tmp filename, max tries reached

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130102]
```
C:\GitDevelopment\monaco>yarn smoketest --build C:\Users\bpasero\Downloads\VSCode-win32-arm64-1.59.0-insider
yarn run v1.22.5
$ cd test/smoke && yarn compile && node test/index.js --build C:\Users\bpasero\Downloads\VSCode-win32-arm64-1.59.0-insider
$ yarn --cwd ../automation compile && tsc
$ npm run copy-driver && npm run copy-driver-definition && tsc

> vscode-automation@1.54.0 copy-driver
> cpx src/driver.js out/


> vscode-automation@1.54.0 copy-driver-definition
> node tools/copy-driver-definition.js

C:\GitDevelopment\monaco\test\smoke\node_modules\tmp\lib\tmp.js:117
  throw new Error('Could not get a unique tmp filename, max tries reached');
  ^

Error: Could not get a unique tmp filename, max tries reached
    at tmpNameSync (C:\GitDevelopment\monaco\test\smoke\node_modules\tmp\lib\tmp.js:117:9)
    at Object.dirSync (C:\GitDevelopment\monaco\test\smoke\node_modules\tmp\lib\tmp.js:224:16)
    at Object.<anonymous> (C:\GitDevelopment\monaco\test\smoke\out\main.js:31:20)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\GitDevelopment\monaco\node_modules\mocha\lib\mocha.js:394:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\GitDevelopment\monaco\node_modules\mocha\lib\mocha.js:391:14)
    at Mocha.run (C:\GitDevelopment\monaco\node_modules\mocha\lib\mocha.js:970:10)
    at Object.<anonymous> (C:\GitDevelopment\monaco\test\smoke\test\index.js:38:7)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bpasero** [comment]
@roblourens did you encounter something similar? I see your commit https://github.com/microsoft/vscode/commit/50b3811fdc5b5c80ca516a2edfffedcbd464b033

@deepak1556 assigning to you as last author.

**Comment by bpasero** [comment]
This blocks all my attempts to fix smoke tests...

**Comment by roblourens** [comment]
Yeah, @deepak1556 said this was to work around hitting the path length limit on CI, the folder is supposed to be deleted when tests are done, but seems that it doesn't happen sometimes. You can delete the folder manually or change this code to work around it but we need a better solution.

**Comment by bpasero** [comment]
Ugh. Yeah, deleting the folder helped. But honestly, I don't know what the point of this `tmp` library is if it cannot do this simplest thing. Maybe we are better off writing our own....

**Comment by bpasero** [comment]
It looks like this code always threw an error when killing the smoke test run from the terminal:

https://github.com/microsoft/vscode/blob/b96644b15f9f28e9bd3906f1f096389617de2f82/test/smoke/src/main.ts#L39-L39

Very likely because the VSCode instance is still writing user data into that folder while `rimraf` is running. As such this directory is not deleted.

With the change from @deepak1556 , the tmp folder was no longer unique, but fixed, thus the failure.

My attempt is to just create our own tmp folder now with a prefix `vscsmoke`, I hope that is not a too long path.:

https://github.com/microsoft/vscode/blob/b96644b15f9f28e9bd3906f1f096389617de2f82/test/smoke/src/main.ts#L31-L36

**Comment by deepak1556** [comment]
Thanks for getting the error logs @bpasero , our usual setup is like this

```
<temp-path>/<some-unique-top-level-directory>/<multiple-user-data-dirs> 

Before my change:

<temp-path>/t-<some-random-prefix>/d-<random-prefix-for-each-user-dir>

After my change:

<temp-path>/t/d-<random-prefix-for-each-user-dir>
```

I believe this problem with rimraf trying to delete the top level directory while it had active user data dirs was always present only that it was not visible because we always kept creating unique top level directory.

I am 👍 on change from @bpasero which deletes the directory on start, we will always be in a race to delete the directory on shutdown with busy user data dirs.

Unassigning myself, let me know if there is anything that needs to be done from my side.

**Comment by bpasero** [comment]
I think this is fine now after my change of trying to delete the directory on startup. It is painful that `tmp` doesn't just provide an option for something that obvious...

I was wondering though if my change is risky because I decided to slightly increase the folder in tmp from `t` to `vscsmoke`.
