### ISSUE TITLE
"Open With Code" not appearing in right click menu in windows 11

### ISSUE THREAD

**Issue by jhanikhilnath** [microsoft/vscode#130181]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.58.2
- OS Version: Windows 11(Build 22000.100)

Steps to Reproduce:

1. Right click and the new right click menu(Introduces in Windows 11) will appear
2. There is No "Open with Code" Option. But the option is there when we click more options and it brings more options.

Even tried re-installing VS Code

Photos
![image](https://user-images.githubusercontent.com/68290610/128349729-514f48bd-a846-4917-b7f5-d3da38ea0cbf.png)
![image](https://user-images.githubusercontent.com/68290610/128349794-08580555-5577-45f1-abb4-1b75cfd874cd.png)

The old menu came by clicking "Show More Options"

**Comment by CodeCrazy-ywt** [comment]
No, it's a feature of Windows 11.

**Comment by jhanikhilnath** [comment]
I want to know that just like its coming for Windows Terminal I want that same thing with VS Code. Its an issue I am pretty sure

**Comment by ArturoDent** [comment]
What kind of file are you right-clicking on?

**Comment by jhanikhilnath** [comment]
I am clicking on blank space which will open the current folder on Windows 10

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/127365
