### ISSUE TITLE
Feature Request: Selection within words

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#13019]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.0.0

SublimeText supports, not only selecting whole words, but selecting parts of words. For example, given the term someSnakeCaseWord: Whole word selection would select the entire term. Partial selection would select the next "portion." If the cursor was to the left of "some", then the first partial selection would select "some," the next "Snake," then "Case," and finally "Word." It's *very* handy when modifying like named terms.

**Comment by dynamix** [comment]
👍 was just look for the same thing.

**Comment by alexandrudima** [comment]
Let's track in #3526
