### ISSUE TITLE
Allow to disable the title bar in a full screen mode (macOS)

### ISSUE THREAD

**Issue by sstativa** [microsoft/vscode#130157]
In the full-screen mode, the menubar and the title bar cover a lot of VS Code control elements (like file tabs) when appearing on a screen, this creates an annoying delay when the aim was some tab but the cursor accidentally hit the top of the screen and triggered the menubar.

There is a new feature in macOS Monterey that makes the menubar permanent in the full-screen mode, however, the title bar still appears and covers the top area of VScode (the title bar appears as soon as cursor reaches the bottom of the menubar).

It would be nice if VScode allowed disabling the title bar completely in the full-screen mode. 

This is BigSur behaviour:
![code-bigsur](https://user-images.githubusercontent.com/3362679/128288226-83c707ab-c84b-4b64-9747-14ea25937351.gif)

This is Monterey:
![code-monterey](https://user-images.githubusercontent.com/3362679/128288307-09ceaf5b-ae4d-4589-9589-790f059dbd2f.gif)

The best outcome would be if VScode could do something similar to Safari when the title bar and control elements are unified, but I believe Electron does not support this and this won't be suitable for many themes.

**Comment by bpasero** [comment]
//cc @sbatten

**Comment by bpasero** [comment]
Oh, it seems to me macOS Monterey triggers sort of an issue for VSCode, so I suggest to split this issue up into 2:
* this one for a setting to hide the menu bar (I am not even sure that option exists for Electron @deepak1556 )
* a new issue for the Monterey behaviour

**Comment by sstativa** [comment]
I suppose I was not clear enough. I would like to clarify some things:

1.  Monterey has an option **Automatically hide and show the menu bar in full screen**. When it is **ON**, Monterey behaves exactly like Big Sur.
2. I don't want to hide the menu bar, I just want to hide the native macOS title bar appearing on the second picture.

This is a pure UX issue. When the native macOS control elements (the menubar and the title bar) appear on top of VScode they block access to VScode buttons laying under (primarily Tabs). Hiding of macOS controls takes some time because of animation effects. As result, if the user accidentally triggers the menu, it will take up to 3 seconds for him to hide the menu and complete the desired action (ex. select the tab). 

macOS Monterey allows users to make the menubar permanent in the full-screen mode, however, the title bar still appears and blocks access to the tabs (2nd picture). 

If only it was possible to disable the title bar bar in the full screen the problem with tabs would be solved.

**Comment by sstativa** [comment]
I've just found another related to this problem, however, the suggested implementation is different. #120512

I believe this is what the author wanted for VScode, however, I believe Electron does not support this. 
In these examples, the title bar and toolbar are "united". As for VSCode, the title bar appears on top of the toolbar and blocks access to the toolbar.

**Mail:** 

![Screen Recording 2021-08-05 at 20 41 09](https://user-images.githubusercontent.com/3362679/128337571-8f7fdc41-539e-479f-9526-82a07a77f3c2.gif)


**Excel:**

![Screen Recording 2021-08-05 at 20 41 46](https://user-images.githubusercontent.com/3362679/128337584-427384b9-378b-49a9-a0ff-aa3b2e7b0b96.gif)

**VSCode:**

![code-monterey](https://user-images.githubusercontent.com/3362679/128338219-9b005d12-2828-4fed-8856-19425c914092.gif)

**Comment by deepak1556** [comment]
There is currently no way in the runtime to disable the fullscreen titlebar. So this will require work in Electron before we want to implement it.

**Comment by dkms-its** [comment]
Maybe unrelated, but i noticed the latest 1.59 release always shows a more or less empty title bar even in fullscreen mode on macOS 11.5.1, taking up valuable vertical space. Was this done on purpose or should i file a bug?

![Bildschirmfoto 2021-08-09 um 10 50 26](https://user-images.githubusercontent.com/33903568/128681266-75707ea5-6972-4243-b84f-1d1a92e22ac8.png)

**Comment by pokey** [comment]
@dkms-its what you describe strikes me as a different issue, so I filed it in https://github.com/microsoft/vscode/issues/130401

**Comment by sstativa** [comment]
I think I found a workaround that lets me select the tab without the need to wait for the title bar to disappear. 

I've just added an extra margin. It looks ugly but does its job for me.  

```json
"customizeUI.stylesheet": {
      ".fullscreen": "margin-top:30px"
}
```

![Screen Recording 2021-08-12 at 15 53 44](https://user-images.githubusercontent.com/3362679/129147229-8557aacb-41f5-4c67-b936-6e2f1c09fe06.gif)
