### ISSUE TITLE
Move recent tabs to the left

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#130132]
I don't really use tabs. I jump between files using ctrl+p. I think the reason is that I have many tabs open and I don't quickly find the ones I'm working on. If the visible tabs were more relevant it could be more useful. A way to make them relevant could be to automatically move modified tabs to the left, that way I know that "the first 5 tabs are the 5 most recent files I'm working on".

**Comment by bpasero** [comment]
> I don't really use tabs.

Me too! I use `Ctrl+P` exclusively for navigation and thus have tabs disabled via `"workbench.editor.showTabs": false`, any reason you wouldn't just disable them?

**Comment by madprops** [comment]
I didn't know you could hide tabs. Though it feels like I lose some context that way (like what is open, how many stuff is open), especially when I have split views (though I rarely have split views). I'm gonna close this since I already stated the idea.
