### ISSUE TITLE
Support eqnarray in notebook math equations

### ISSUE THREAD

**Issue by lon91ong** [microsoft/vscode#130150]
Like [this ipynb file](https://github.com/LetsCodePhysics/ModernPhysics/blob/master/Assignment%2002%20Relativistic%20Dynamics.ipynb), does't show right format
```
$$ \begin{eqnarray}
\frac{dx}{dt} &=& v, \text{ and} \\\
\frac{dv}{dt} &=& a,
\end{eqnarray} $$
```

rewrite the equation in one line like:
```
$$ \begin{eqnarray} \frac{dx}{dt} &=& v, \text{ and} \\\ \frac{dv}{dt} &=& a, \end{eqnarray} $$
```
then show right format.

## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version : v2020.12.414227025
-   Python Extension version : v2020.12.422005962
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19042
-   Python: 3.7.6, x64
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

**Comment by mjbvz** [comment]
Multi-line equations should generally work but `eqnarray` isn't supported by KaTeX so this equation will still not render

Updating issue title and marking as a feature request to gauge interest
