### ISSUE TITLE
Tests behave weird when run from a skipped suite

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130161]
![recording](https://user-images.githubusercontent.com/900690/128299643-6d3fcb68-1572-4ef9-94fd-97dd2687dec9.gif)

Version: 1.59.0-insider (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T20:25:19.728Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin arm64 20.6.0

**Comment by bpasero** [comment]
Oh. I just realise this test was added to a `suite.skip` so probably there is a bug with dealing with skipped suites?

**Comment by connor4312** [comment]
This is sort of how Mocha works, we grep for a test and then if it's skipped mocha won't run it. But we could show a warning from the self host test provider when we see a request for a test that has .skip in its parents

**Comment by bpasero** [comment]
Yeah the confusing part was that I saw an instance of VSCode actually launching.

**Comment by connor4312** [comment]
I think I'll just have skipped tests/suites not be published as tests. Eventually we might get some way to indicate "disabled" tests in the API, we can await community feedback.

**Comment by bpasero** [comment]
I wonder if this is causing frustration though when you do not immediately notice that the entire suite is skipped. 

An alternative solution is to allow running a skipped test but open the test output window to indicate that no test was run.
