### ISSUE TITLE
IntelliSense does not understand this keyword when bind is used

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#13010]
- VSCode Version:`1.5.3`
- OS Version:`ubuntu 16.4`

Steps to Reproduce:

1. write a function that is borrowing props through bind to something else
2. intelisense wont work
![](http://i.imgur.com/0136oYp.png)

**Comment by waderyan** [comment]
@NikosEfthias thank you for opening this issue. 

I'm not understanding what is going on. Can you provide a minimal repo that I can clone or copy to recreate what you are seeing? 

Also if you provide an animation that will help me see what is going on.

**Comment by NikosEfthias** [comment]
```ts
interface data {
count: number
}
const data:data={count:0}
data.count //intelisense works here and auto completes the count
(function(){
this.count// intelisense does not understand this keyword here although its context was bound to data 
}).bind(data)
```

**Comment by waderyan** [comment]
Thanks @NikosEfthias. I don't believe this pattern is supported by TS Server currently Moving to TS repo to track it as a feature request.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11259

**Comment by NikosEfthias** [comment]
thank you
