### ISSUE TITLE
Export settings to local file

### ISSUE THREAD

**Issue by Osolemio44** [microsoft/vscode#130117]
## Short Description

Implement functionality to export / import configurations to local file (json, yaml, etc)

### Problem to be solved

VSCode is fully configurable. From the graphical aspect of the interface to the plugins. Reinstalling VSCode can be a nightmare if you want to recover the state of your VSCode.

### Solution

VSCode is currently implementing a system called `Settings sync`, which works badly (and it doesn't matter because it's in beta). But it does not make sense that there is no simple local export of the settings and yet they are implementing a synchronization system between devices using a GitHub or microsoft account.

Although many people may appreciate the synchronization system, what most people are looking for is a simple and easy way to export to a local file. Something that can be saved, copied and imported wherever you want without the need for the internet, syncing or associating an external account like gitHub.

I personally think this functionality is essential and should have been implemented a long time ago.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/2816
