### ISSUE TITLE
Terminal profiles not ordered?

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#130192]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:
```
Version: 1.59.0-insider (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T22:04:52.121Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

The terminal profiles listed do not seem to follow a specific order, certainly it does not respect the order in my settings file. 
Also, I would expect the default profile to be the first in the list so one can quickly invoke a keybinding (`shift+alt+t` in my case) then `Enter` to quickly open a new terminal.

```json
"terminal.integrated.profiles.windows": {
        "Powershell Preview": {
            "path": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
            "color": "terminal.ansiMagenta"
        },
        "Powershell": {
            "path": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
            "color": "terminal.ansiMagenta"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash",
            "icon": "git-branch",
            "overrideName": true,
            "color": "terminal.ansiRed"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "color": "terminal.ansiBlue"
        },
        "Powershell Core": {
            "path": "C:\\Program Files\\PowerShell\\6\\pwsh.exe"
        },
        "Node": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/C", "node"],
            "icon": "repl",
            "overrideName": true,
            "color": "terminal.ansiGreen"
        },
        "Python": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/C", "python"],
            "icon": "repl",
            "overrideName": true,
            "color": "terminal.ansiYellow"
        }
    },
```

![image](https://user-images.githubusercontent.com/5784415/128394788-4624f16b-ea06-4444-a39b-3c76be6eda63.png)

**Comment by meganrogge** [comment]
Just pushed a commit that will put the default profile at the top of the list because you make a good point about the convenience of that. 

The profiles in the "Create with Profile" list are scrambled because we validate and resolve some auto-detected profiles along with the ones you provide in config. I'm not sure it's necessary or warranted to keep them in the configured order. @Tyriar thoughts?

**Comment by Tyriar** [comment]
> Just pushed a commit that will put the default profile at the top of the list because you make a good point about the convenience of that.

I think it used to be like that and regressed at some point

> The profiles in the "Create with Profile" list are scrambled because we validate and resolve some auto-detected profiles along with the ones you provide in config. I'm not sure it's necessary or warranted to keep them in the configured order.

If we can do it, it would be good.

**Comment by Tyriar** [comment]
From what I can tell, the config service doesn't guarantee the order of the profiles so it's wrong already when we get them. Let's go with default at the top and then alphabetical after that.

**Comment by Tyriar** [comment]
This is what I landed on, for the dropdown the default will be at the top regardless of whether it's a normal or contributed profile:

![image](https://user-images.githubusercontent.com/2193314/130287599-4e3d11b0-13fc-4168-8a8b-b5f74ebfad88.png)

For the new with profile command, the default profile is at the top of its category, then the rest alphabetical. So below "Terminal API Profile" is the default:

![image](https://user-images.githubusercontent.com/2193314/130287713-9a8a3335-d277-422f-8afb-74ee5237236b.png)
