### ISSUE TITLE
Better Comment Readability by Using a Proportional Font for Triple-Slash Comments

### ISSUE THREAD

**Issue by leodr** [microsoft/vscode#130168]
XCode has these triple-slash comments that render a proportional font for better text readability:

![Screenshot 2021-08-05 at 10 45 42](https://user-images.githubusercontent.com/39763575/128320757-2577ec93-edae-4e02-83d1-635972b90cae.png)

Could these types of comments be supported in VSCode? I quite like them for non-code, explanatory comments.

**Comment by hediet** [comment]
Proportional fonts are supported by the editor, but I don't know if we can mix fonts.

@alexdima can a textmate grammar rule set a font?

**Comment by rodrigocfd** [comment]
That would hurt Rust code, which uses `///` for [entity documentation rendered as markdown](https://doc.rust-lang.org/rust-by-example/meta/doc.html#doc-comments).

**Comment by leodr** [comment]
I guess this would have to be a setting and probably language specific, some languages don’t even use C-style comments.

**Comment by ctjlewis** [comment]
> That would hurt Rust code, which uses `///` for [entity documentation rendered as markdown](https://doc.rust-lang.org/rust-by-example/meta/doc.html#doc-comments).

@rodrigocfd, could this be worked around by ad hoc'ing to the feature request that these comments should also be parsed with Markdown?

I am supportive of somehow encoding `h1`, `h2`, etc. font-sizing in comments by default.

**Comment by bioball** [comment]
JetBrains editors have the concept of [rendered views for doc comments](https://blog.jetbrains.com/idea/2020/03/intellij-idea-2020-1-eap8/), and plugins have their ability to provide their own rendered docs: https://github.com/JetBrains/intellij-community/blob/4ba0df072ee4c6b11a29577abd00ae4645ef4a86/platform/analysis-api/src/com/intellij/lang/documentation/DocumentationProvider.java#L134

It'd be really neat if VSCode also had this feature.
