### ISSUE TITLE
Option to add WSL to reopen folder in WSL on the editor as default

### ISSUE THREAD

**Issue by KoichaDev** [microsoft/vscode#130177]
Every time I open a new project, I have to manually turn on the `Reopen folder in WSL`. This is really annoying since I am using WSL Ubuntu with ZSH-shell instead of the bash-terminal. 

It would be very nice if it's possible to have this feature request that VSC understands that I wish to have this option to turn on as default every time I am starting the VSC program.

**Comment by aeschli** [comment]
How exactly do you open a new project? From the command line, or from the 'open folder' dialog..?
How is this related to the ZSH-shell instead of the bash-terminal ?
