### ISSUE TITLE
Search settings not working when invoked using the extension settings button

### ISSUE THREAD

**Issue by thedonator** [microsoft/vscode#130124]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: 10.0.19042 Build 19042

Steps to Reproduce:

1.Pick an extension and open the extension tab 
2.Click on manage button and choose extension settings and the search result isn't shown

**Comment by roblourens** [comment]
This should have been fixed in 1.59 (was just released)
