### ISSUE TITLE
to many requests

### ISSUE THREAD

**Issue by ryansquadle** [microsoft/vscode#130188]
Issue Type: <b>Bug</b>

installing a theme and i got too many requests error

VS Code version: Code - Insiders 1.59.0-insider (955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7, 2021-07-26T05:12:43.446Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.49GB free)|
|Process Argv|--crash-reporter-id c2677c59-f392-484d-8c08-b57cd344e72f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
scss-lint|ada|0.1.10
reacticons|afz|0.1.4
copy-relative-path|ale|0.0.2
vscode-zipfs|arc|2.3.0
atlascode|atl|2.9.1
beardedicons|Bea|0.14.0
bits-please-essentials|Bit|1.0.1
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.23
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
moxer-icons|Equ|5.8.0
prettier-vscode|esb|8.1.0
git-last-commit-message|Jan|1.9.0
vscode-simple-icons|Lau|1.15.0
import-sorter|mik|3.3.1
diff-merge|mos|0.5.1
deepdark-material|Nim|3.3.0
material-product-icons|PKi|1.0.4
vscode-seedling-icon-theme|ras|0.8.0
vscode-yaml|red|0.22.0
jasmine-problem-matcher|sea|1.0.1
markdown-preview-enhanced|shd|0.5.22
vscode-scss-formatter|sib|2.2.3
stepsize|Ste|0.8.19
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
file-icons-mac|way|1.0.1
vscode-icons-mac|way|7.25.3
terminal-all-in-one|yas|1.12.0
json|Zai|2.0.2
sort-js-object-keys|zen|1.0.6
html-css-class-completion|Zig|1.20.0

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthrucf:30344902

```

</details>

**Comment by CodeCrazy-ywt** [comment]
Can you give a screenshot?
