### ISSUE TITLE
Shortcut to Reload Window Doesn't Works

### ISSUE THREAD

**Issue by Tanmoy2504** [microsoft/vscode#130109]
Issue Type: <b>Bug</b>

The default shortcut to reload window "Ctrl + R" doesn't works maybe due to some sort of bug or conflict. Each time I've to open palette (Ctrl + Shift + P) then opt for "Developer > Reload Windows". Please look into this bug

I've also tried to change the default "Ctrl + R" key-binding to something else, yet it doesn't trigger reload but selecting it from palette does
This might be a small bug but it shouldn't exist in the first place

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.50GB free)|
|Process Argv|--crash-reporter-id 7f367ead-381e-4c98-af94-5fa36153b2b1|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tomato256** [comment]
Having same issue
