### ISSUE TITLE
VSCode fails to open file when another instance of VSCode is already running as "Administrator" user.

### ISSUE THREAD

**Issue by akasexdev** [Microsoft/vscode#13014]
- VSCode Version: 1.5.3
- OS Version: Windows 8.1 Pro x64

Steps to Reproduce:

1.  Run VSCode as Administrator (Right click on icon, select "Run As Administrator")
2.  Right click on any file, select "Open with Code"
3. Nothing happens: no new instance of VSCode created with selected file opened nor selected file opened in running instance.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4921
