### ISSUE TITLE
tasks.onDidEndTaskProcess is called too many times in VS Code v1.59

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#130277]
Issue Type: <b>Bug</b>

## Repro steps

1. Create a simple hello world extension
2. Replace the code in the `activate` method with the following code:
    ```typescript
    const outputChannel = vscode.window.createOutputChannel('Hello World Test');
    outputChannel.show();
    vscode.commands.registerCommand('extension.sayHello', async () => {
        const tasks = await vscode.tasks.fetchTasks();
        outputChannel.appendLine(`Executing task "${tasks[0].name}"`);
        vscode.tasks.executeTask(tasks[0]);
    });

    vscode.tasks.onDidEndTaskProcess(e => {
        outputChannel.appendLine(`${e.execution.task.name}: ${e.exitCode}`);
    });
    ```
3. F5 the extension
4. In the open workspace, add a `.vscode/tasks.json` with the following contents:
    ```json
    {
        "version": "2.0.0",
        "tasks": [
            {
                "type": "shell",
                "command": "echo 'hi'",
                "label": "helloWorld",
                "presentation": {
                    "reveal": "never"
                }
            }
        ]
    }
    ```
5. Run the "Hello World" command from the command palette several times

## Expected

The output will look consistent, like this
```
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
```

NOTE: This is the behavior on Version: 1.58.2 (Universal) Commit: c3f126316369cd610563c75b1b1725e0679adfb3

## Actual

The `onDidEndTaskProcess` event gets called more and more times each time you do "Hello World" and the output ends up looking like this:
```
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
helloWorld: 0
helloWorld: 0
Executing task "helloWorld"
helloWorld: 0
helloWorld: 0
helloWorld: 0
helloWorld: 0
```

This breaks a decent amount of functionality in our Azure Functions and Azure App Service extensions around tasks because we can't accurately tell when a task is done.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 11, 7|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv|--crash-reporter-id e2c60431-fb89-41a2-b9ed-11e53cee83ac|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Debugging a little, I found that the terminal instance is actually firing an already disposed `onExit` event. When an event is already disposed, the listener is not removed appropriately.

The event is created here:

https://github.com/microsoft/vscode/blob/a0696fb2368cec0179dc9cc3374ec5812709a86e/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L214-L214

and disposed here:

https://github.com/microsoft/vscode/blob/a0696fb2368cec0179dc9cc3374ec5812709a86e/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1336-L1336

but when a terminal is reused, a new even isn't created.

**Comment by alexr00** [comment]
If the fix is low-risk, it might be good to get this in the next recovery release.

**Comment by alexr00** [comment]
Also, thanks @ejizba for the easy repro steps!

**Comment by ejizba** [comment]
I'm not aware of any workaround for this issue and this only started happening in 1.59, which is why we would really appreciate if this made it into a recovery release. If you have any ideas for a workaround on our side let me know. This affects several scenarios that run tasks in our Azure extensions. 

To give more of the "real world" scenario - our normal flow is to start a task with `tasks.executeTask` and then use `onDidEndTaskProcess` to figure out when it finishes (although we wouldn't need to do that if https://github.com/microsoft/vscode/issues/98483 was implemented). However, an event is fired very quickly after we start the task and our extension thinks it finishes way before it actually does.

**Comment by alexr00** [comment]
There is no workaround for this. 

@meganrogge will have to speak to whether a fix will be possible for a recovery release. If the proper change is going to be too complicated for a recovery release then I should be able to make a targeted tasks specific recovery change.

**Comment by Tyriar** [comment]
Am I understanding right that onExit will still only fire when the task actually exits, it just may be called several times? This doesn't seem like it would cause problems since when `onExit` is triggered you can reliably say the task has ended?

**Comment by ejizba** [comment]
Unfortunately it's not that simple, the timing of the "extra" events seems pretty random to me, but it frequently fires before the task actually finishes.

**Comment by alexr00** [comment]
@Tyriar this also causes terminal reuse issues: https://github.com/microsoft/vscode/issues/130461

**Comment by Tyriar** [comment]
Regression caused in fbc568228940a73c1c088fb17695eb3552d1c84d, I don't think that complexity is actually needed based on the fact `super.dispose()` is called after `_onProcessExit`:

https://github.com/microsoft/vscode/blob/58d4666a348734ac621a939540b0e5b1d6e25456/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1010-L1019
