### ISSUE TITLE
I set git bash as a default terminal, but it is still opening powershell

### ISSUE THREAD

**Issue by rafid149** [microsoft/vscode#130272]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0 -insider
- OS Version: Windows 7 32 bit

Steps to Reproduce:

Before this, i said git bash is not working. But after i installing it in Program files it started working well. But after updating it. It is not working
my extensions are ```vim, latex workshop, bracket pair colorizer, code spell checker and material icon them```

See this video:

https://user-images.githubusercontent.com/85733811/128548670-19562e60-b7ec-4476-9081-828af97d1ced.mp4

**Comment by IllusionMH** [comment]
Most likely duplicate of #128763

**Comment by meganrogge** [comment]
valid bug, duplicate of https://github.com/microsoft/vscode/issues/130268 that will be fixed in insider's tomorrow
