### ISSUE TITLE
expose pty terminal api to detect when it is explicitly killed by a user

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#130231]
Right now there is only [close](https://github.com/microsoft/vscode/blob/08d7afbf53f80d232d285d322cfad762d4eb6d4b/src/vs/vscode.d.ts#L9622-L9625) method which is called by different user actions. I need to distinguish the case when the terminal is closed because the user explicitly requested closing of this terminal or because a user, for instance, close the window and disposure of the frontend terminal as well as the ext host terminal service call `close`. Maybe `dispose` is missing?

Context: I have long-running processes to which pty is connecting. Such processes should be stopped if a user requests explicit killing of frontend terminals, otherwise they should not be. But right now they got stopped whenever a user closes the window.

**Comment by Tyriar** [comment]
Does this work?

https://github.com/microsoft/vscode/blob/19959ec90dc48df3e97bccc9629a890a57ba3350/src/vs/vscode.d.ts#L9680-L9692

**Comment by akosyakov** [comment]
It is `undefined` for me in both cases, i.e. when I reload the page and forcefully kills the terminal.

**Comment by jeanp413** [comment]
Is this still out of scope? I have a hack in my extension as you suggested by it's broken now due to https://github.com/microsoft/vscode/issues/152204 , which I'm sure it will be fixed, but having a way to differentiate when a user closes the terminal explicitly would be nice

**Comment by akosyakov** [comment]
@Tyriar Would you be opened if we propose some API to distinguish between close caused by explicit user action to kill the terminal or by system (i.e. unload of extension host caused by window reload or close). As @jeanp413 mentioned we have code like that: https://github.com/gitpod-io/openvscode-server/blob/fa1ade7210e7bba9075dadf3d84a7f65ffcd3da1/extensions/gitpod-shared/src/features.ts#L963-L965 which got broke by last release, but generally we hear complaints from time to time that underlying jobs getting closed by window reloads. We would like to have more robust means than timeout.

**Comment by Tyriar** [comment]
Sure you can propose and I'll bring it to our API meeting to discuss, I guess something like  `TerminalExitStatus.source: 'process' | ...` is what you're after?
