### ISSUE TITLE
Keeps freezing laptop

### ISSUE THREAD

**Issue by wkey1980** [microsoft/vscode#130267]
Issue Type: <b>Performance Issue</b>

I have been using VSCode and it randomally freezes my laptop. The mouse stops moving and the laptop fans spin up. it can be like this for a good 5 minutes and sometimes i get a message the application has crashed. Been doing it for about a week. I have done a clean install of the OS (Running Linux Mint) and was ok for a few days. then it crashed. I thgought my laptop was out of memory. BUT now I am not so sure.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics (6 x 1700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 3|
|Memory (System)|7.23GB (1.95GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4464b685-f8c4-44ef-ac76-c30deaad2055|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   133	 17498	code main
    0	    37	 17502	   zygote
    0	   126	 17534	     gpu-process
    0	    37	 17503	   zygote
    0	     7	 17505	     zygote
    0	    81	 17793	       window (Issue Reporter)
    0	    52	 17537	   utility
    0	   192	 17562	   window (google-clone - Visual Studio Code)
    0	   155	 17632	     extensionHost
    0	    59	 17728	       electron_node serverMain.js 
    0	    59	 17783	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=17632
    0	    59	 17641	     watcherService
    0	    59	 17697	     searchService
    0	   126	 17620	   shared-process
    0	    59	 17664	     ptyHost
    0	     0	 17812	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 17813	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (google-clone - Visual Studio Code)
|    Folder (google-clone): 22 files
|      File types: svg(5) json(2) png(2) editorconfig(1) gitignore(1) md(1)
|                  css(1) html(1) scss(1)
|      Conf files: settings.json(1) package.json(1);
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
alignment|ann|0.3.0
html-end-tag-labels|ant|0.7.0
path-intellisense|chr|2.4.0
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
EditorConfig|Edi|0.16.4
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
live-sass|gle|5.0.4
svg|joc|1.4.9
vscode-language-babel|mgm|0.0.31
color-highlight|nau|2.4.0
indent-rainbow|ode|7.5.0
emoji|Per|1.0.1
material-icon-theme|PKi|4.9.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1
trailing-spaces|sha|0.3.1
errorlens|use|3.4.0
highlight-matching-tag|vin|0.10.1
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by deepak1556** [comment]
Do you experience the issue when launched with `--disable-extensions` ?

Can you share the crash log following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
