### ISSUE TITLE
"|" symbol display error in .yml

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#130229]
The"|" symbol  display to a "/".

![image](https://user-images.githubusercontent.com/11532015/128454286-bc2a98b0-50c0-4ef5-ab1a-7694a8864e85.png)

Other IDE display normally：
![image](https://user-images.githubusercontent.com/11532015/128454621-cbcb7ecb-3617-494b-9513-ce53fdcc1058.png)

**Comment by aeschli** [comment]
What theme are you using? It seems to me that this is rendered italics.
To inspect this, set the cursor before the `|` and invoke the command `Inspect editor token and scopes`. If you can paste a screenshot of the inspection hover that would be great.

**Comment by jianboy** [comment]
theme: Dart+

xx.yml:

![image](https://user-images.githubusercontent.com/11532015/129883687-ca4ac9b3-cd96-4f28-8d3c-8d1efa8dc035.png)


xx.java:

![image](https://user-images.githubusercontent.com/11532015/129883864-a20fc46c-0f00-4e43-995c-dc993176a469.png)


gif:

![动画 (9) (1)](https://user-images.githubusercontent.com/11532015/129884213-827be2f3-1520-4920-917d-cd50e559c217.gif)

**Comment by aeschli** [comment]
As for the theme, do you mean the `Dart+` or `Dark+`? The gif shows that you select the built-in `Dark+`.

The built-in `Dark+ does not define 'italics` for `keyword.control`.
Also, I can't reproduce the issue on my machine.

Did you customize the theming rules in the settings? (`editor.tokenColorCustomizations`)

**Comment by jianboy** [comment]
I got a setting:
```
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.tokenColorCustomizations": {
        "comments": {},
        "keywords": {
            "fontStyle": "italic",
            // "foreground": "#ffee00"
        },
        "functions": {
            "fontStyle": "bold",
            // "foreground": "#15ff00"
        },
    },
```

But, "|" is not a keywords.

**Comment by aeschli** [comment]
That explains what you see. The YAML grammar gives the `|` the `keyword.control` scope, which is typically used for keywords like `if`, `switch`.
You can file an issue against the YAML grammar (https://github.com/textmate/yaml.tmbundle) and argue that the '|' should not be classified as a keyword.
