### ISSUE TITLE
the color of parameter self

### ISSUE THREAD

**Issue by carry-xz** [microsoft/vscode#130223]
Issue Type: <b>Feature Request</b>

the default editer color theme is very nice , and if the color of parameter [self] is diffirent will be better.  how to set the color of parameter [self]?

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-73-generic

**Comment by CodeCrazy-ywt** [comment]
@carry-xz you mean python? If so, then it's Pylance(Microsoft's open-source Python language server)'s issue.

**Comment by aeschli** [comment]
Not sure if could be done with sytax highlighting or requires semantic highlighting.
@carry-xz Please also paste a small code snippet.
