### ISSUE TITLE
1.59 release broke JSON settings editor (or a release note is missing?)

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#130262]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59
- OS Version: Win10

Steps to Reproduce:

1. Open settings
2. click the tab to see the workspace file (or the folder setting files)... except that the tabs are no longer there, now I have to "Open File" and navigate to the workspace file???

Since there's no mention in the 1.59 release notes of the tabs being removed or of how to get to workspace settings, I'm assuming this is a regression bug??? (or maybe someone forgot a section in the release notes? there's something about the GUI settings editor getting enhanced)

**Comment by gjsjohnmurray** [comment]
@af4jm I assume you have `"workbench.settings.useSplitJSON": true`

This is an intentional change. I agree it should have featured in the 1.59 release notes.

In case you haven't already - see #125952

> now I have to "Open File" and navigate to the workspace file???

An easier way is to open the GUI Settings editor (<kbd>Ctrl</kbd>+<kbd>,</kbd>), then use its tabs to pick the scope you want, then use this button top right:

![image](https://user-images.githubusercontent.com/6726799/128541925-ee2cc19b-e862-4ebc-97e2-76052bf4fafe.png)

**Comment by af4jm** [comment]
yes I have that setting, because without that (and the filter bar) there's no way to know what settings to use!

the GUI settings editor looks like it was slapped together by a dev with no design experience (being such a dev, myself, I'm too familiar with those crappy UIs)

now the only way to find settings is to F3 through the left side of the editor, because the filtering feature has also been removed.

interesting choice to post the discussion, because except for 1 comment in there from someone who doesn't use the JSON editor, EVERY OTHER COMMENT asks you to leave it as it is, in another example of why User Voice was shut down, because customer feedback isn't something Microsoft cares about... it compiles so we're going to ship it to our customers to test, so when they give us feedback about bugs, we can either ignore them or tell them they're using it wrong

**Comment by OneOfOne** [comment]
The vscode team completely ignored everyone and went ahead with their choice just because they can, VSCodium time I guess.

**Comment by Nick-Lucas** [comment]
Please revert this change, or at least spin it out into a community extension which can be more easily contributed to and maintained outside the team. If it will take some effort to expose extension APIs then do that first. 

The great thing about VS Code has always been that it doesn't try to force you through GUIs to do your work, but now the JSON settings editor is severely limited and trying to funnel people into the settings GUI. This is a real step back for the editor

**Comment by gjsjohnmurray** [comment]
@Nick-Lucas I am not a member of the core team.

**Comment by roblourens** [comment]
Sorry, but yes it has been removed. Thanks @gjsjohnmurray for linking the relevant issue.

**Comment by AlencarGabriel** [comment]
Consider voting on feature request #131390. Maybe it's a hope for that.

Note: We need at least 20 up votes!
