### ISSUE TITLE
Notebooks Getting Started Experience

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#130200]
Improvements for the Getting Started experience of Notebooks:

- [ ] Add some Getting Started content (this might not have the highest click through rate)
   - Customizing layout
   - Renderers in the marketplace
   - Kernel extensions
   - Debugging
- [x] https://github.com/microsoft/vscode/issues/128592 and resolve how to curate Notebook extensions through either the getting started infrastructure or have Notebooks add a specific tag to their extension rather than using the messy category
   - Make kernel extensions obvious to find
- [x] https://github.com/microsoft/vscode/issues/128549 
   - Make a doc about the different customizations available?
- [ ] Improve the discoverability and ease of use of custom renderers
    - https://github.com/microsoft/vscode/issues/125876
    - May need to seed the marketplace with more renderers

Immediate TODO:
- [ ] Check in with Luciana and Jeffrey about their plans for Getting Started with Python to see if there's any overlaps

**Comment by misolori** [comment]
@tanhakabir let me know if there's other things you want to cover here, otherwise it looks like the only part that needs an issue is the getting started content.

**Comment by tanhakabir** [comment]
Yep can make a separate issue for that!

**Comment by tanhakabir** [comment]
https://github.com/microsoft/vscode/issues/134413
