### ISSUE TITLE
Non-null assertion doesnt work

### ISSUE THREAD

**Issue by vacavaca** [microsoft/vscode#130264]
Issue Type: <b>Bug</b>

vscode fails to recognize "!" (typescript non-null assertion) in a very basic code:

```tsx
// getService(): () => Service | void

const service = getService()!
service.isOpen()  //  <-   Property 'isOpen' does not exist on type 'void | Service'
```

The issue appears and disappears randomly, without file or config changes. This is very annoying, restarts help sometimes but usually they don't, the error disappears sometimes after some non related edits in other files.
Typescript version 4.3.5

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 4.9.0-16-amd64
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor (8 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.67GB (2.38GB free)|
|Process Argv|. --crash-reporter-id db3746f9-6fae-4b98-9ea5-239d47f7c809|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3-gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|i3-gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|1.21.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by IllusionMH** [comment]
Are you sure it worked earlier? 
As I can see even [TS 3.3 wont remove `void` from union](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAyhBOA3AlgY2gXigbysgzgPKQB2AXFABQCUUGAfFAEYD2LANhAIYlQC+AbgBQAEwip2XeNABmAVxKpgyFrwDmEYHCRoINCtpTooAHyiIWyEcKGpV+YFHwIjmKBq0vdNAIRDnOugAdATEECQ0UFAA9NFRADwAtFBCouKS0lDyisqq7pqGuoQA1vqwXsZmCmIyyCQQ1rb2jgGuJXT5noEQJb7+FT3FIUSkNEA)

You should use `Service | undefined` with `strictNullChecks` enabled to get desired effect.

**Comment by vacavaca** [comment]
> Are you sure it worked earlier?

Yes, I suspected that, but the fact it works perfectly in some files and at the same time does not work in others makes me think it's a bug, also `tsc` says the code is ok.

**Comment by vacavaca** [comment]
> And you should avoid void in unions in general.

**Comment by IllusionMH** [comment]
OK my initial test was a bit flawed as I has `strictNullChecks: false` in TS 4.3.5.
In TS 4.3.5+ it won't error with `strictNullChecks: true` but will produce an error with `strictNullChecks: false`.

> works perfectly in some files and at the same time does not work in others

Another explanation might be different configuration if not all files are handled by same `tsconfig.json`.

Do you see same configuration files in files with errors as in files without errors when you run <kbd>F1</kbd> `>TypeScript: Go to Project Configuration` ?

**Comment by vacavaca** [comment]
Yea, I've found that some of my files were not part of my ts project (they weren't explicitly included or imported by other project files), fixed that and all works as expected.

Thanks for pointing that out!
