### ISSUE TITLE
My Bash Terminal is not working

### ISSUE THREAD

**Issue by EyasuG** [microsoft/vscode#130220]
Issue Type: <b>Feature Request</b>

I mistakenly changed the setting json and all my previously used changes were deleted. How can I restore it?

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by meganrogge** [comment]
ctrl shift p -> settings sync open local backups folder

**Comment by EyasuG** [comment]
Thank you! Worked
