### ISSUE TITLE
Large Jupyter notebooks (.ipynb files) ... editor becomes painfully slow. 

### ISSUE THREAD

**Issue by gopalagrawal** [microsoft/vscode#130290]
Issue Type: <b>Performance Issue</b>

Create a jupyter notebook file with .ipynb extension. 

Load large data sets (eg., the Bank Loans EDA set from kaggle ... about 500 MBs).

Create several plots in it (50-60) with matplotlib or seaborn. 

Run the entire file. 

As you type anything... the keystrokes lag by about 1 to 2 seconds .. sometimes, VS Code just freezes for about 5 seconds before our keystrokes are rendered in the cells.  

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.60GB free)|
|Process Argv|C:\\<some path>\\LoanEDA [Git] --crash-reporter-id f04e9e9e-346b-441b-9c7f-0912eaa2c03e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    95	  4860	code-insiders main
    0	   103	  1100	   window (undefined)
    2	   204	  5952	   gpu-process
    0	    85	  6716	   shared-process
    0	    58	 12464	     ptyHost
    0	    23	  9520	   crashpad-handler
    2	    87	 10764	   window (Issue Reporter)
    0	    40	 12620	   utility
    0	   192	 12976	   window (BANK Case STUDY.ipynb - LoanEDA [Git] - Visual Studio Code - Insiders)
    0	    12	  8424	     watcherService 
    0	    11	 11852	       console-window-host (Windows internal process)
    0	   298	 12616	     extensionHost
    0	    17	  2228	       C:\ProgramBin\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
    0	    11	  7344	         console-window-host (Windows internal process)
    0	    51	 11712	         electron_node WIAxqNtEYz.js 
    0	    14	  5484	       C:\ProgramBin\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    11	  9692	         console-window-host (Windows internal process)
    0	    14	  7880	       C:\ProgramBin\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    11	  1396	         console-window-host (Windows internal process)
    0	    14	  9660	       C:\ProgramBin\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
    0	    11	 12768	         console-window-host (Windows internal process)
    0	   147	 10864	       electron_node bundle.js 
    0	    81	 13032	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BANK Case STUDY.ipynb - LoanEDA [Git] - Visual Studio Code - Insiders)
|    Folder (LoanEDA [Git]): 69 files
|      File types: json(46) ipynb(6) csv(3) gitignore(2) TAG(1) py(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.5
gc-excelviewer|Gra|3.0.42
easy-snippet|inu|0.6.3
git-graph|mhu|1.30.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
test-adapter-converter|ms-|0.1.2
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt:30346833
dockerwalkthrucf:30348714

```

</details>

**Comment by rebornix** [comment]
@gopalagrawal can you please share a notebook which you can use to reproduce this issue? Does it still happen if you clear all the outputs?

**Comment by romanovzky** [comment]
I have the same problem in `1.59` which landed on my system (Manjaro) this week.

```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.10.53-1-MANJARO
```

**Comment by rebornix** [comment]
@romanovzky it would be helpful if you can provide a sample notebook to help troubleshoot? Also can you try clear all cell outputs and see if you can still reproduce?

**Comment by romanovzky** [comment]
You can reproduce this with this simple example
```python
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", names=["Sex", "Length", "Diameter", "Height", "Whole weight", "Shucked weight", "Viscera weight", "Shell weight", "Rings"])

plt.clf()
sns.pairplot(data=data, hue="Rings")
plt.show()
```
and then try to do stuff on a new cell. It's painfully slow and sluggish.
