### ISSUE TITLE
Remote WSL not working

### ISSUE THREAD

**Issue by lobosan** [microsoft/vscode#130273]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59
- OS Version: Windows 10 build 19043

Steps to Reproduce:

1. Open a WSL project on Ubuntu 20.04
2. Then I get this error
![image](https://user-images.githubusercontent.com/314886/128549480-802096cf-b2e7-440a-90ca-50794e0676c2.png)

**Comment by aeschli** [comment]
Hm, that's very strange. The `minimist` node module can not be loaded. I would say the install is corrupt.

- close all vscode windows
- in a wsl terminal, invoke `rm -r ~/.vscode-server/bin`
- reopen

**Comment by aeschli** [comment]
Please reopen if that didn't help.

**Comment by lobosan** [comment]
@aeschli thanks that worked perfectly :)
