### ISSUE TITLE
Empty notebook should show a cell by default?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130238]
**Steps:**
* out of sources
* have GH issues notebook extension installed
* run `scripts/code.sh <path to folder>/test.github-issues

**Result:**
![image](https://user-images.githubusercontent.com/900690/128471844-564f113e-1ee0-4310-b88a-ec9361c9309a.png)

I think this looks not very friendly for input, I would have expected a cell to show.

Besides, the buttons in the center seem to miss their top border.

**Comment by tanhakabir** [comment]
I think this should be the choice of the Notebook extension. Jupyter currently shows a single empty cell.
