### ISSUE TITLE
Enable ctrl+enter in notebook markup cells even if you have multiple selections?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#130221]
Issue Type: <b>Bug</b>

1. In a notebook, start editing a markdown cell
1. Use multicursors
1. While still having multiple cursors, try to stop editing by pressing `ctrl + enter`

**Bug**
Nothing happens

This is currently by-design: 

https://github.com/microsoft/vscode/blob/14fdf3012a8ffd802e1b820f425a14d3924800c1/src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts#L1327)

but I always get confused when it happens

VS Code version: Code - Insiders 1.59.0-insider (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T20:25:19.728Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-yaml-preamble|bie|0.0.4
test-ext|bie|0.0.1
typescript-notebook|don|1.4.0
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
codespaces|Git|0.11.3
copilot|Git|1.3.2277
vscode-pull-request-github-insiders|Git|2021.8.3427
vscode-drawio|hed|1.6.1
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.19.2
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.3
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.15.0
vscode-language-pack-de|MS-|1.59.2
python|ms-|2021.9.1095391618-dev
vscode-pylance|ms-|2021.8.1-pre.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh-edit-nightly|ms-|2021.8.5221
remote-ssh-nightly|ms-|2021.8.5221
azure-account|ms-|0.9.8
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.8.217
live-server|ms-|0.2.6
vscode-github-issue-notebooks|ms-|0.0.102
vscode-typescript-next|ms-|4.4.20210804
vsliveshare|ms-|1.0.4650
debugger-for-chrome|msj|4.12.12
vetur|oct|0.34.1
tsserver-live-reload|rbu|1.0.1
java|red|0.80.0
code-spell-checker|str|1.10.2
rest-book|tan|3.2.0
ayu|tea|0.20.1
luna-paint|Tyr|0.8.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.32.2

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Not sure what's the intention of excluding multi cursor.

**Comment by roblourens** [comment]
It was supposed to just be for escape but I copied it and used it for ctrl+enter too https://github.com/microsoft/vscode/issues/105757
