### ISSUE TITLE
Scroll wheel is very hard to use in interactive notebooks because of inconsistent scrolling

### ISSUE THREAD

**Issue by DavidZidar** [microsoft/vscode#130206]
Scrolling in a .NET Interactive Notebook is a pain because the number of lines scrolled varies depending on what type of content the mouse is currently hovering over. As far as I know this problem only exists in notebooks.

1. Scrolling in code blocks is really slow because it is scrolling too few lines per step, far fewer than anywhere else in VS Code
2. Scrolling in output cells scrolls the normal amount of lines

Since a notebook does have mixed code and output cells it is extremely difficult to accurately scroll to where I want to be in the document. One second it is barely moving so I really have to crank the wheel and the next second I have scrolled way too far and have to backtrack.

Let me illustrated this issue with a gif:
![](https://user-images.githubusercontent.com/381720/106369303-926bbd80-6350-11eb-8660-8deaca4a38ff.gif)

I originally reported this issue in dotnet/interactive#1025 6 months ago but since nothing has been done about this I am reporting the issue here as well.

Does this issue occur when all extensions are disabled?: Don't know, I can't disable the .NET Interactive Notebooks extension

- VS Code Version: 1.59.0
- OS Version: Windows

Steps to Reproduce:

1. Create a .NET Interactive notebook with code and output cells (tables, graphs)
2. Use scroll wheel on a mouse

**Comment by DavidZidar** [comment]
I love the interactive notebooks but this has been a daily frustration, it really makes them super annoying to use.

**Comment by rebornix** [comment]
@DavidZidar the issue was already fixed in main (and shipped with the next Insiders).

**Comment by DavidZidar** [comment]
@rebornix It seems to have been fixed incorrectly. Now it is scrolling slowly even in output cells. The scroll speed should be the same as other editor windows.
