### ISSUE TITLE
Extension not open, show this , We cannot connect to extension marketplace at this time, please try agin later.

### ISSUE THREAD

**Issue by devsab087** [microsoft/vscode#130234]
Issue Type: <b>Bug</b>

Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-16T00:15:55.196Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.0-8parrot1-amd64

VS Code version: VSCodium 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-16T00:15:55.196Z)
OS version: Linux x64 5.10.0-8parrot1-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics (8 x 4063)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (8.43GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Probably #130119 as you are using VSCodium

**Comment by Hacksign** [comment]
Same here.
And I got this error under developer tools:

```
workbench.html:1 Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
workbench.desktop.main.js:2835 Error querying extensions gallery XHR failed
```

Environment:

```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.16
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.13.9-arch1-1
```
