### ISSUE TITLE
Inline Suggestion: option for show the list top of cursor.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#130292]
option for show the list of inline suggestions on top of cursor instead bottom of it.(when there is enough space for show in both top and bottom.)

it is good when `editor.suggest.preview` enabled.
![image](https://user-images.githubusercontent.com/26390254/128573923-941b5f7d-0386-4c5b-acaa-2fd35287d453.png)
now i can't see preview of `pass` because it's behind of suggestion list.

but when the list is shown at top of cursor i can see the preview well.
![image](https://user-images.githubusercontent.com/26390254/128574142-f86d4a18-e181-4123-8ba2-895b1480ae9f.png)

**Comment by hediet** [comment]
This is already implemented.

However, I cannot repro:
![recording](https://user-images.githubusercontent.com/2931520/129722709-8e465873-2811-459d-844b-3edc8f2da942.gif)

Where does the snippet come from? (custom defined / extension / ?)

**Comment by byehack** [comment]
> Where does the snippet come from? (custom defined / extension / ?)

custom snippet.

**Comment by byehack** [comment]
> However, I cannot repro:
> 


try add this in your `snippets\python.json` file:
```
"if keyword": {"prefix": "if", "body": ["if ${1:1}:", "\t${0:pass}"]}
```

**Comment by hediet** [comment]
I think this is already fixed in the latest VS Code insider build.

Can you verify that?

![recording](https://user-images.githubusercontent.com/2931520/129887643-ec11ac5f-661e-4de7-acc6-88bec55faf1c.gif)

**Comment by hediet** [comment]
I can verify that this does not work in VS Code stable, but it does work in VS Code insiders, so it is fixed.
