### ISSUE TITLE
Sync stopped working after update from 1.58➤1.59

### ISSUE THREAD

**Issue by nutnutwin** [microsoft/vscode#130216]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59
- OS Version: Windows 10 Pro 20H2(OS Build 19042.1110)

Steps to Reproduce:

1. working fine with outlook account
2. updated to 1.59
3. boot VSCode
4. error message popup(successive autorization failures)
5. tried rebooting windows, does not work
6. confirmed sync works on 1.58.2(another PC)
<img width="284" alt="20210806_Fri -073923" src="https://user-images.githubusercontent.com/34512273/128430455-8efc42a3-4272-493d-b6d3-4076eeafcde5.png">
<img width="349" alt="20210806_Fri -074113" src="https://user-images.githubusercontent.com/34512273/128430491-90c8620c-f6fa-4943-a94c-81c624d21f61.png">

**Comment by TechFounder** [comment]
I'm experiencing the same issue using my MSFT Outlook email account. You would think that they would make sure that it worked on their own property?

**Comment by nutnutwin** [comment]
https://github.com/microsoft/vscode/issues/114265
seems it happened before at the beginning of the year. 

Since it is reproducible not just on my own PC, I believe it would be fixed soon(hopefully

@TechFounder

**Comment by dltmurphy** [comment]
Also affecting me with a M365 account

System Info is below if needed:

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.48GB free)|
|Process Argv|--crash-reporter-id 30944392-500e-48e9-b0dc-2b75ca808a1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.43.2
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.5
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.96
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.9
docs-yaml|doc|0.2.7
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
remote-containers|ms-|0.191.0
remote-wsl|ms-|0.58.2
powershell|ms-|2021.6.2
vscode-yaml|red|0.22.0
snyk-vulnerability-scanner|sny|1.0.7
code-spell-checker|str|1.10.2


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by longnt0707** [comment]
I have the same issue with both my work account on a laptop and my personal account on a PC.

**Comment by TechFounder** [comment]
It seems the issue has now been resolved. When I opened my VS Code yesterday, It asked me to log in to my Outlook account and it's started syncing once again. I hope all of you are experiencing the same thing. If so we can close this ticket.

**Comment by nutnutwin** [comment]
I clicked "Sign in" and MS Account, and successfully logged in. 
If I click the current "xxxx@outlook.com", it still fails

**Comment by TechFounder** [comment]
That's because it needed to establish a new log in as the old one is broken. The fact of the matter is that it's now working as you just confirmed with your new log in.

**Comment by nutnutwin** [comment]
great. Thanks a lot

**Comment by nutnutwin** [comment]
@sandy081 if you don't mind, I would like to close the issue. Thank you

**Comment by dltmurphy** [comment]
Was the update process the root cause of the issue? Should keep the issue open until the problem is resolved in a PR, the update process should be smoother like previous updates were

**Comment by TechFounder** [comment]
I'm seeing authentication sync issues crop up again on one of my Macs. It looks like this issue is not fixed permanently yet.

**Comment by TylerLeonhardt** [comment]
/duplicate #130314

in that issue I added some extra questions for you all to help me get to the bottom of this. Can you comment over there? Thanks!
