### ISSUE TITLE
Source Control Commit Message Focus Lost

### ISSUE THREAD

**Issue by welcometochristown** [microsoft/vscode#130204]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z (20 hrs ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
- OS Version: Windows 10 Enterprise (19042.1110)

Steps to Reproduce:

1. Open a folder or workspace with more than 1 repository.
2. Edit a file from the first repository.
3. Save the file, and start writing the commit message before the source control section has updated.
4. Focus moves to different repository.

![Animation](https://user-images.githubusercontent.com/17158437/128414422-c13926d6-bef7-48ff-ad7b-f73affc7e714.gif)

**Comment by smena** [comment]
A workaround is to reduce the save-after-delay config value to either less or greater time than it takes to focus and type in the commit message input.
