### ISSUE TITLE
Unable to quit the app 

### ISSUE THREAD

**Issue by igorsalari** [microsoft/vscode#130286]
Issue Type: <b>Bug</b>

Click on X button to close the app

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.31GB free)|
|Process Argv|-psn_0_98328 --crash-reporter-id a45fed84-fd41-4ce7-ac2a-b1322121970c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|7.1.1
vscode-language-babel|mgm|0.0.31
theme-monokai-pro-vscode|mon|1.1.19
debugger-for-chrome|msj|4.12.12
prettyxml|Pra|0.8.1
vscode-stylelint|sty|0.86.0
tabnine-vscode|Tab|3.4.21
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by IllusionMH** [comment]
> VS Code version: Code 1.55.2 (3c4e3df, 2021-04-13T09:36:32.643Z)

Latest stable version is 1.59.0. Is this problem reproducible in latest version?

https://code.visualstudio.com/Download

**Comment by Spinderman** [comment]
i also have the same problem vscode version 1.59.0 and this only happen when you are trying to close the app from another application

**Comment by Spinderman** [comment]
![recording](https://user-images.githubusercontent.com/62501507/128593384-b8ad1883-fb61-4013-9fab-9f0e9f96af41.gif)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Spinderman** [comment]
even the insider build is affected 
![recording](https://user-images.githubusercontent.com/62501507/128601558-be150b3f-4d28-464b-8882-b6e1e85f9b93.gif)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Spinderman** [comment]
[terminal log](https://gist.github.com/Spinderman/2081f41125facbc55dcad8e9c1a73d41)
[Developer Tools console](https://gist.github.com/Spinderman/a67d91ed31b2db9bcab931ecf5c7f4e8)
when i clicked the button to close vscode nothing appeared inside the terminal,
i guess this is what should appear inside the terminal when i close vscode
```
[main 2021-08-07T14:30:53.244Z] Lifecycle#window.on('close') - window ID 7
[main 2021-08-07T14:30:53.244Z] Lifecycle#unload() - window ID 7
...
[main 2021-08-07T14:30:53.260Z] StorageMainService: closed workspace storage (1628346641651)
[main 2021-08-07T14:30:53.266Z] Lifecycle#onBeforeCloseWindow.fire() - window ID 7
[main 2021-08-07T14:30:53.267Z] IPC Object URL: Removed channel vscode:4a441369-4670-406f-aba8-cb50dc18a729.
[main 2021-08-07T14:30:53.268Z] Lifecycle#window.on('closed') - window ID 7
```

**Comment by bpasero** [comment]
Strange, I am not seeing anything obvious in those messages.

How about closing the window through the command palette in VSCode itself:

![image](https://user-images.githubusercontent.com/900690/128604825-3744dde3-eb47-48bf-bcfd-bab339352764.png)

**Comment by Spinderman** [comment]
closing vscode from the command palette works

**Comment by bpasero** [comment]
@deepak1556 this somewhat sounds like a possible Electron 13 regression to me then, maybe with the implementation of the native window buttons?

**Comment by deepak1556** [comment]
@Spinderman please share the gif following the steps at https://github.com/microsoft/vscode/issues/130286#issuecomment-894610877 that shows how the application is launched and what steps are performed before quitting the application. Its hard to understand the setup from your previous screenshot. Looks like you are focused on a different application while trying to quit the vscode application but then again that works on my machine, so it would be easier to understand if you can visualize the complete steps. Thanks!
