### ISSUE TITLE
untrustedFiles setting only working as expected from within VSCode

### ISSUE THREAD

**Issue by Hermjard** [microsoft/vscode#130256]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.2 x64 System Install
- OS Version: Windows 10 Professional x64 Version 1709

Steps to Reproduce:

1. Switch the VSCode setting _security.workspace.trust.untrustedFiles_ to _open_. Leave all other settings for Workspace Trust to default.
2. Start VSCode. Don't open any workspaces. Instead, open an arbitrary single text file from within VSCode, e.g. by Ctrl+O. The file opens in Trusted Mode.
3. Close VSCode.
4. Open the same file as above, but directly, i.e. by double click, by context menu "Open with Code" or by Jumplist. The file opens in Restricted Mode.

Expected behavior: In step 4 above, the file should open in Trusted Mode.

**Comment by sbatten** [comment]
@Hermjard this is not the intended behavior of the setting. When opening a new window with a file as a parameter, we can determine if the file is trusted and set the mode of the window on startup.

The setting only applies when a window is already trusted and you are opening an untrusted file in the same window.

**Comment by Hermjard** [comment]
@sbatten I think understand your approach: In the first scenario, you have first a (trusted) empty window, and from this known state, you open a single file, which then will also be trusted. Contrary to that, if you directly open a single file, you open it to VSCode in an "unknown state". Nevertheless, from a user perspective, the difference of these two ways of opening a single file are marginal, and therefore shouldn't behave differently, in my point of view.

What's more, the way, VSCode currently handles Workspace Trust, makes it at least cumbersome, to use VSCode as an ad hoc text editor and full featured code editor at the same time: Either you switch the complete Workspace Trust off, or you are confronted with the Trust Dialog everytime you double click on a readme.txt, or INI, or JSON, or CSV, or XML, or LOG etc. Also note, that there are plugins for these types of files, like Json Editor, XML, Txt Syntax, Rainbow CSV, Hex Editor, or Sort lines, to mention a few, which are mostly deactivated in restricted mode.
