### ISSUE TITLE
Antialiasing in VS Code

### ISSUE THREAD

**Issue by rudinandrey** [microsoft/vscode#130254]
Issue Type: <b>Feature Request</b>

Please, please, please. In any updates I open and hope you added antialiasing in VSCode. Please, make antialiasing in VSCode, rendering like subpixel, grayscale and so on. Your editor is not ideal only by this reason. I have FullHD monitor and it's so pain to look into subpixel rendering font in the VSCode. Please, only one feature antialiasing, and I remove all other editors, and will be using only VSCode. Just it. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

**Comment by deepak1556** [comment]
\gifPlease
