### ISSUE TITLE
Can't sort files by date modified in open folder

### ISSUE THREAD

**Issue by TolliLF** [Microsoft/vscode#13029]
- VSCode Version: 1.5.3
- OS Version: 10 Anniversary

Steps to Reproduce:
1. Open a folder with hundreds of files
2. Try to sort to show recently modified files at top of list

**Comment by bpasero** [comment]
@TolliLF can you invest the time to search for duplicates?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11823
