### ISSUE TITLE
Markdown expand selection should honor links

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#130271]
If I have a link like 
```
[vscode#110882](https://github.com/microsoft/vscode/issues/110882)
```
in my markdown, and place the cursor anywhere inside the link - between the brackets, between the parens, in between the bracket and the paren - expand selection should end-up selecting the complete link at some point. Right now it has no knowledge of links.

**Comment by meganrogge** [comment]
Perhaps that's a special case? Works for links for me
![recording (53)](https://user-images.githubusercontent.com/29464607/128555991-d5f5539f-103d-4085-915c-2487bc2a3cea.gif)

**Comment by meganrogge** [comment]
🤔  it's working for me with your example
![recording (54)](https://user-images.githubusercontent.com/29464607/128556131-cb9cf914-e2ea-4bd7-8ac4-187b205a3480.gif)
