### ISSUE TITLE
Can't highlight lua standard function in the default dark theme

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#13022]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1.monokai 
![moon](https://cloud.githubusercontent.com/assets/1836844/18963252/b5d7733a-86a6-11e6-9997-0aae844813e0.jpg)

2.default dark
![qq 20160930004046](https://cloud.githubusercontent.com/assets/1836844/18963262/bf17a12c-86a6-11e6-9d39-0dd24fdf43d5.jpg)

**Comment by aeschli** [comment]
That's expected as the current strategy of the Dark+ theme is to only colorize function definitions (not references).
This might change, but for now its only definitions.
