### ISSUE TITLE
v1.59 causes the VS Code window not to work with 3rd-party window management utility (i.e., BetterSnapTool)

### ISSUE THREAD

**Issue by cmslewis** [microsoft/vscode#130205]
_Filing a GitHub issue instead of going through Help > Report Issue, because I wanted to include screenshots._

Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **v1.59 (July 2021)**
- OS Version: **11.2.2 (macOS Big Sur)**

Steps to Reproduce:

#### Problem
I have used BetterSnapTool, a 3rd-party OS-level utility for auto-positioning and auto-resizing windows on macOS, for several years. See **Expected** for a description of expected behavior. VS Code v1.59 (July 2021) no longer works with BetterSnapTool, even though all _other_ windows on my OS do still work with BetterSnapTool. For comparison, BetterSnapTool _was_ working with VS Code v1.58 (from which I upgraded just a few minutes ago on my machine).

#### Expected
With BetterSnapTool installed and enabled, dragging any OS window (VS Code window, Chrome window, whatever) to a corner of my screen should move/resize the window to fill that quadrant. Pressing my custom hotkeys for this should do the same.

#### Actual
With BetterSnapTool installed and enabled, dragging any _non-VS Code_ OS window (Chrome window, Finder window, whatever) to a corner of my screen moves/resizes  the window to fill that quadrant. But the VS Code window, uniquely, does not anymore. My BetterSnapTool hotkeys also don't work from VS Code (e.g., <kbd>Cmd + Alt + Arrow{Left,Right,Up,Down}</kbd>). I tried changing all competing VS Code keyboard shortcuts to something else, but that didn't help.

1. Install and enable [BetterSnapTool](https://apps.apple.com/us/app/bettersnaptool/id417375580?mt=12).
2. Try dragging a non-VS Code window to a corner of the screen. Observe that it moves/resizes to fill the quadrant, as expected.
3. Try dragging a VS Code window to a corner of the screen. Observe that nothing happens; the window stays the same size.
4. Try changing all conflicting VS Code keyboard shortcuts to something else, so that the BetterSnapTool behaviors are the only side effects mapped to the keyboard shortcuts in question. Then try pressing those keyboard shortcuts in a VS Code window. Observe that, still, nothing happens; the window stays the same size.

#### Reflection

This is a huge interruptor/decelerator in my daily workflow, but I understand that this is a problem with a 3rd-party application rather than VS Code core, and it's hard to verify every possible 3rd-party interplay. Still, I'm curious if something changed with VS Code's window management in the latest release? Also curious if this is a problem for others, so wanted to file an issue. Would definitely appreciate a fix. Thanks for reading! 

#### Screenshots

My BetterSnapTool settings are included below:

![image](https://user-images.githubusercontent.com/443450/128412352-e663c4fc-efd8-495b-8ed7-cfdca47f1fb1.png)
![image](https://user-images.githubusercontent.com/443450/128413277-595e3af2-add8-4c21-9051-ac9640bddbef.png)

Sample difference in window-snapping behavior between VS Code and Preview app, e.g. (sorry for huge GIF):

![2021-08-05 13 03 42](https://user-images.githubusercontent.com/443450/128413925-772011e1-a893-421c-80dd-d44dc8c09a7b.gif)

**Comment by bpasero** [comment]
I am a heavy user of BetterSnapTool as well and did not encounter this issue:

![recording](https://user-images.githubusercontent.com/900690/128464792-42156e4c-0afb-43e5-8aac-5acc1d80016c.gif)

**Comment by cmslewis** [comment]
@bpasero _Weeeeird_, all of a sudden, it's working this morning. I'm tried restarting VS Code a few times yesterday (e.g., when I tried uninstalling all extensions), so I don't think a VS Code restart was enough to fix the issue. But at the same time...how is everything working now?

![2021-08-06 08 29 35](https://user-images.githubusercontent.com/443450/128534767-25440c25-adc3-463e-8b34-521bd6b8e4ab.gif)

Maybe it's just that good things come to those who sleep? No idea. Anyway, happy to close (will let you do the honors).
