### ISSUE TITLE
[themes] Code won't switch out of HC mode after doing a contrast switch

### ISSUE THREAD

**Issue by HansHugli** [microsoft/vscode#130274]
Issue Type: <b>Bug</b>

[Windows] I was testing some contrast states on a RNW app, I switched to HCBlack and HCWhite and Code properly switched into HC as expected. When I switched back to Dark mode, Code would not switch out of HC mode. I even uninstalled and reinstalled Code and the problem remains. I'm guessing that there is some reg key that remained. 

My question is can I hack it back into non-HC mode? HC mode is disorienting and will definitely slow me down

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.24GB free)|
|Process Argv|--crash-reporter-id c0296c9f-2ffe-451f-87a1-73176e1d2bad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
gitlens|eam|11.6.0
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
git-graph|mhu|1.30.0
python|ms-|2021.8.1102490946
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
powershell|ms-|2021.6.2
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.6.0
color-highlight|nau|2.4.0
vscode-jest|Ort|4.0.3
alphabetical-sorter|ue|2.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
dockerwalkthru:30344881

```

</details>

**Comment by HansHugli** [comment]
I did find that changing the color theme allowed me to get back in a working state, so I am unblocked.

**Comment by aeschli** [comment]
When VSCode is closed while you make the OS high contrast change, and you restart VS code after, we stick with the high contrast mode in VS Code as we don't know for what reasons it was activated. Some users depend on the HC mode, so we better don't switch away from unnecessarily.

So yes, you need to manually change the theme in VS Code.
