### ISSUE TITLE
Stop asking me to find a latex extension

### ISSUE THREAD

**Issue by dionyziz** [microsoft/vscode#130244]
When writing LaTeX, sometimes VS code will open up a dialog asking me to install a LaTeX extension. When I click on the button to search for LaTeX extensions, nothing comes up. I don't want to use a LaTeX extension. I'm fine with the highlighting that I have. There's no way to disable the pop-up, and it interrupts my LaTeX writing workflow. Can we add a checkmark to never ask again?

**Comment by gjsjohnmurray** [comment]
Does `"extensions.ignoreRecommendations": true` work for you?
