### ISSUE TITLE
Missing important features after 1.59 update

### ISSUE THREAD

**Issue by Ascrivia** [microsoft/vscode#130259]
Issue Type: <b>Bug</b>

After the last update (1.59) I can't find "Go to implementation", "Peek definition" and "Find all references" in the contextual menu that appear right clicking on source code.
I can't even find a way to activate them either somewhere in config or with the command palette.
They are fundamental features, why thay have been removed?

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.91GB free)|
|Process Argv|--crash-reporter-id 1263cace-825a-41bc-aa55-c00fb336a82a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
auto-using|Fud|0.7.15
csharp|ms-|1.23.14
python|ms-|2021.8.1102490946
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
resharper9-keybindings|ms-|1.1.0
ayu|tea|0.20.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language? Do you see extension for this language enabled?

**Comment by Ascrivia** [comment]
C#

Nothing has changed in my extensions after the update.

**Comment by Ascrivia** [comment]
Solved!

I had to enabled "Omnisharp: Enable Ms Build Load Projects On Demand" option in settings and restart VS Code.
![img](https://user-images.githubusercontent.com/57408745/128533022-a98185d8-2051-4659-9bc1-41fce3f38903.png)
