### ISSUE TITLE
After updating to 1.60.0 on Linux, all extensions say "Enabled" but are greyed out and not working.

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode#130288]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I updated to 1.60.0 on Linux and now all of my extensions are greyed out. I invoked the "Enable all extensions" command, "Reload Extension Host, etc, but none of those made a difference, it seems. 

![](https://i.imgur.com/3O5QTLn.png)

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:38:56.151Z)
OS version: Linux x64 5.11.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.81GB (0.80GB free)|
|Process Argv|--unity-launch --crash-reporter-id a61367b7-e8a4-4da6-905e-411623666a3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|12.3.0
flutter-snippets|ale|2.0.0
gitkraken-glo|axo|1.1.1
shell-syntax|bma|1.0.2
better-toml|bun|0.3.2
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-shell-snippets|Dee|0.3.1
dotfiles-syntax-highlighting|dot|0.1.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
font-switcher|eva|4.0.1
comment-anchors|Exo|1.9.6
shell-format|fox|7.1.0
copilot|Git|1.3.2277
go|gol|0.26.0
todo-tree|Gru|0.0.213
terraform|has|2.14.0
json-and-jsonc|htw|1.0.1
turnipultimate-theme-vscode|ins|0.0.1
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
path-autocomplete|ion|1.17.1
stylua|Joh|1.2.0
vscode-home-assistant|kee|1.21.0
vscode-lua-format|Koi|1.3.8
l13-sh-snippets|L13|0.15.1
lldb-vscode|lan|0.2.3
expand-region|let|0.1.4
aw-watcher-vscode|lin|0.4.1
bash-ide-vscode|mad|1.11.0
regionfolder|map|1.0.15
themeinfo|McN|0.11.0
rainbow-csv|mec|1.9.1
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cpptools|ms-|1.5.1
powershell-preview|ms-|2021.8.0
awesome-flutter-snippets|Nas|3.0.1
color-highlight|nau|2.4.0
linux-desktop-file|nic|0.0.18
dartgettersetter|Pet|1.0.2
material-icon-theme|PKi|4.9.0
vscode-autohotkey-plus-slimcode|raf|2.1.18
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
fzf-quick-open|rli|0.4.3
bash-debug|rog|0.3.9
color-manager|roy|0.6.2
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
lua|sum|2.3.4
tabnine-vscode|Tab|3.4.21
luna-paint|Tyr|0.8.1
vscode-lldb|vad|1.6.5
vscodeintellicode|Vis|1.2.14
vscode-wakatime|Wak|14.0.3
vscode-todo-highlight|way|1.0.4
debug|web|0.25.1
dotnetscriptr|Wiv|0.2.4
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.4.0
go-snippets|zsh|0.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
3f5j7703:30294757
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt:30346833
dockerwalkthru:30348713

```

</details>

**Comment by MostHated** [comment]
I downgraded back to code-insiders=1.59.0-1628112802 and all my extensions and themes came back. Not sure what is up, but I set the package to hold this version for the time being.

**Comment by GavinRay97** [comment]
See also https://github.com/microsoft/vscode/issues/130219

**Comment by folke** [comment]
Same on Macos
