### ISSUE TITLE
Execute PowerShell-Code in integrated console

### ISSUE THREAD

**Issue by HolgerGiesen** [microsoft/vscode#130251]
Issue Type: <b>Bug</b>

Hello,
I have the problem, that I could not execute PowerShell code in the PowerShell integrated console by pressing 'F5' or selected code by pressing 'F8'.  It's a fresh installation with only PowerShell extension and German language.
I also tried to synchronize alle the settings and extensions over an Microsoft -Account from an installatoin who work fine. I overwrite the local settings but this doesn't work, too. I deinstalled VSCode, delete AppData- and profile folder and make a new fresh installation, but also, it doesnt work. 
Please can you help me?

Regards,
Holger Giesen

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.64GB (46.59GB free)|
|Process Argv|--crash-reporter-id 98118b9b-7ea7-49d1-af8f-7e84a9ce0a59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.59.2
powershell|ms-|2021.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by meganrogge** [comment]
Hi, can you please file an issue in the correct repo, IE https://github.com/PowerShell/vscode-powershell ?
