### ISSUE TITLE
VSC Crash on Mac OSX 10.11.6 El Capitan

### ISSUE THREAD

**Issue by federicosnobohm** [microsoft/vscode#130276]
the Latest veersion of vscode just crash when is opened. Mac OSX 10.11.6

**Comment by deepak1556** [comment]
Please attach the crash logs following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

Also attach the output of `code --verbose`
