### ISSUE TITLE
Preserve `mtime` when renaming files/folders

### ISSUE THREAD

**Issue by munael** [microsoft/vscode#130269]
Currently moving files through the Explorer panel updates the `Modified Date` to the date they were moved on. This is not a "modification" in my (current) opinion, and so would like an _option_ to make such moves preserve all file-level dates.

_Edit: This's a feature request, but the bot hasn't added any tags yet..._

**Comment by bpasero** [comment]
That behaviour has been there pretty much since we ship VSCode and I am a bit afraid to just change it now since I did not hear any complains so far:

https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/node/pfs.ts#L505-L505

**Comment by munael** [comment]
> That behaviour has been there pretty much since we ship VSCode and I am a bit afraid to just change it now since I did not hear any complains so far:
> 
> https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/node/pfs.ts#L505-L505

@bpasero - Would a setting be disruptive?

**Comment by bpasero** [comment]
A new setting is certainly an option to preserve compatbility.

**Comment by aNickzz** [comment]
I can't say this is a critical problem for me but having it update the mtime on a file that I'm moving isn't what I expected (and is kinda annoying).
My workaround is obviously to just use explorer to move the files but I'd prefer not to need to do that.

**Comment by munael** [comment]
I'm worried this title is just not making this issue get visibility when others are searching for annoyances they had.

The triage-bot's ultimatum always feels like it's either the backlog or the graveyard. I'm unconvinced that giving a _feature request_ 60 days to get votes on a platform like GitHub is the best way to do it.

For example, there's no floating of posts or any feed mechanism to let others no what features are up for a backlog vote. So things understandably just get buried.
