### ISSUE TITLE
Update failed every time

### ISSUE THREAD

**Issue by hotkidfamily** [microsoft/vscode#130225]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version:
the last stable version before CodeSetup-stable-379476f0e13988d90fab105c5c19e7abc8b1dea8.exe

- OS Version:
 OS :          Microsoft Windows 10 pro
OS:          10.0.19043
OS:        Microsoft Corporation
OS :      Multiprocessor Free

Steps to Reproduce:

1. auto update
2. wait after exit
3. those file that can not been deleted as below
![image](https://user-images.githubusercontent.com/21275239/128442234-b987cfe7-829b-4244-97fb-ef96902c5f06.png)
![image](https://user-images.githubusercontent.com/21275239/128442231-c5f9ef03-633e-469b-9725-c7097fef9330.png)
![image](https://user-images.githubusercontent.com/21275239/128442219-aaa7bd96-c1bb-412a-ba89-8ae898d98872.png)
4. update log
[vscode-inno-updater-1628204157.log](https://github.com/microsoft/vscode/files/6942437/vscode-inno-updater-1628204157.log)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
