### ISSUE TITLE
Terminal tab focus doesn't always match active tab

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#130227]
- Open a terminal in the vscode repo
- Press cmd+shift+b to launch task terminals with the build task
- The task terminal tab is focused but that is not the active tab

![image](https://user-images.githubusercontent.com/323878/128452502-b870528f-47fc-4eb9-859a-826522680484.png)

I think the focused tab should be the visible one

**Comment by meganrogge** [comment]
how did you make the other terminal visible? by clicking on it in the list?

**Comment by meganrogge** [comment]
oh I can repro
