### ISSUE TITLE
Can't connect to marketplace

### ISSUE THREAD

**Issue by mdminhaziftekhar** [microsoft/vscode#130249]
Issue Type: <b>Bug</b>

cannot connect to marketplace

VS Code version: Code - OSS 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-15T18:36:41.908Z)
OS version: Linux x64 5.10.53-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-4000 APU with Radeon(tm) HD Graphics (2 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|7.04GB (1.50GB free)|
|Process Argv|--extensions-dir /home/minhaz_vai/.var/app/com.visualstudio.code-oss/data/vscode/extensions --no-sandbox --unity-launch /app/share/vscode-flatpak-wrapper/first_run.txt --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by bigjimlefou** [comment]
Same here

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/129879#issuecomment-890292080
