### ISSUE TITLE
Option to force uninstall extensions

### ISSUE THREAD

**Issue by gargolito** [microsoft/vscode#130298]
Currently, I am unable to force uninstall a extension due to a dependency paradox:

When trying to uninstall "Extension A"
Cannot uninstall 'Extension A' extension . It includes uninstalling 'Extension B' extension and 'Extension A' extension depends on this.

When trying to uninstall "Extension B"
Cannot uninstall 'Extension B' extension. 'Extension A' extension depends on this.

If there was an option to force uninstalling any extension, it would be very helpful. This is available in must package management programs like rpm, dpkg, and apt.

FYI: I disabled these extensions, removed their respective directories, restarted vscode and they still showed in my installed extensions and even like that I was unable to uninstall them.

**Comment by sandy081** [comment]
Can you please provide the extensions that you are trying to uninstall?

**Comment by gargolito** [comment]
@sandy081 it really shouldn't matter which extension, users should be able to force remove any extension when this happens in case an extension developer does something malicious by accident or on purpose. However, the extension is https://marketplace.visualstudio.com/items?itemName=VSpaceCode.vspacecode (Extension A in my initial description), and its dependency is called whichkey (Extension B) that is created by the same developer.

**Comment by sandy081** [comment]
/duplicate 

#130310
