### ISSUE TITLE
Import auto type bug.

### ISSUE THREAD

**Issue by Hoodgail** [microsoft/vscode#130252]
LOL WHAT IS THIS 😂😂
![image](https://user-images.githubusercontent.com/45743294/128500933-11096892-bcad-4c5d-9833-93d02c14b63d.png)

`c:` wouldn't even work

but why didn't it just type `../index.js`

**Comment by CodeCrazy-ywt** [comment]
If I got it right, this user seems to be asking a feature -- import relative paths instead of absolute paths.

**Comment by mjbvz** [comment]
Please fill in the issue template and share steps to reproduce the issue

**Comment by mjbvz** [comment]
Closing as not actionable without a minimal example that demonstrates the issue
