### ISSUE TITLE
Removing cells in Interactive Python bad now

### ISSUE THREAD

**Issue by ardeego** [microsoft/vscode#130280]
Issue Type: <b>Feature Request</b>

Hey, why did you guys remove the feature to clear code/cell output from the left hand side? I need to be able to selectively remove code blocks/output in interactive Python....quickly... Now I have no spinning progress indicator anymore for once, and no way to directly remove cells without extra click and way longer mouse movement to the righthand side menu that only becomes visible when the cell is selected. Really guys? This did not improve HCI. At least put keyboard shortcuts then...

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by amunger** [comment]
commands have been added as part of https://github.com/microsoft/vscode/issues/148820 and the toolbar can be configured to show on hover. also related: https://github.com/microsoft/vscode/issues/159513
