### ISSUE TITLE
Custom editor #rename is missing to await resolveEditor call

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130235]
This call is not awaited: https://github.com/microsoft/vscode/blob/5f3d88ad79fbdad08778620a639b6113e0e677dd/src/vs/workbench/contrib/customEditor/browser/customEditorInput.ts#L343-L343

**Comment by lramos15** [comment]
Hmm. Rename isn't an async call. Is making editorInput renames async ok?

**Comment by bpasero** [comment]
I think it is fine but needs adoption here:

https://github.com/microsoft/vscode/blob/64081da3c8c12eddc28eaff05672fe9515e7e502/src/vs/workbench/services/editor/browser/editorService.ts#L278-L278

**Comment by rchiodo** [comment]
@lramos15  do you have some steps on how to verify this?

**Comment by lramos15** [comment]
No steps to verify this, just a small code change
