### ISSUE TITLE
Values in dataframe display are not always centered in native Notebook UI

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode#130207]
```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
Jupyter extension: v2021.8.1195043623
```

If you display your dataframe in the old interactive window, the values are always centered vertically. This keep the view consistent when you resize the interactive window and have long strings with spaces in your dataframe.

![oDROY8pBi2](https://user-images.githubusercontent.com/33796896/128417521-131bba39-7425-4f34-8f73-9c87ce40eb71.gif)

However, in the new Notebook UI, the values are aligned on the top and looks inconsistent when resize the window.

![5bsx6IHhEG](https://user-images.githubusercontent.com/33796896/128417498-7bf7882d-d365-4151-9570-897de7667862.gif)

```python
import pandas as pd
import seaborn as sns
import numpy as np

df = sns.load_dataset('tips')
str_long = ['long str '*np.random.choice([0, 5], 1)[0] for _ in range(len(df))]
df.assign(str_long=str_long)


```

**Comment by misolori** [comment]
This is because the alignment is set to the top:

https://github.com/microsoft/vscode/blob/5a02f42d2b6d6c7ea7ce5c2ee667bd6bda61cb03/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L279-L282

We can look at adjusting this for this milestone.

**Comment by misolori** [comment]
Aligned all columns to the middle:

<img width="819" alt="CleanShot 2021-08-06 at 13 41 27@2x" src="https://user-images.githubusercontent.com/35271042/128568891-2ae9535b-966a-494b-821f-f604c2fa8803.png">

**Comment by StevenLi-DS** [comment]
@misolori Thanks for the fix and this looks way better. I wonder if there could be a way to allow the users to set the font size. The dataframe view takes a much larger space than before.

**Comment by misolori** [comment]
Please upvote and subscribe to https://github.com/microsoft/vscode/issues/123149 for controlling the output size
