### ISSUE TITLE
VS Code Uninstalled Itself from my Computer

### ISSUE THREAD

**Issue by VickyKR37** [microsoft/vscode#130388]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

VS Code just uninstalled itself from my computer! I last used it three days ago and after the weekend wanted to use it again and it's gone!

**Comment by Box-Of-Hats** [comment]
I've just had the same thing happen. I'm on Windows 10 and I just found that it had suddenly vanished, despite the fact that I was using it yesterday.

OS: Windows 10 Pro (21H1) 19043.1165
VSCode Version: 1.59.1 (Latest)

**Comment by VickyKR37** [comment]
I read elsewhere that that can happen if it's updating and gets shut down. When I reinstalled it all my code was still there so it was fine! And updated!

**Comment by joaomoreno** [comment]
#52855
