### ISSUE TITLE
Add option to enable listing of files only from current working folder when using quick search

### ISSUE THREAD

**Issue by ADmad** [Microsoft/vscode#13036]
- VSCode Version: 1.6.0-insider Commit c94c824db64a88bd4909da2e84e44316dbf8e8fb
- OS Version: ubuntu 16.04

Currently when using quick search recently opened files from other folder than the one you have currently opened in your workspace are also listed. If one is working on multiple projects with similar file names and switch between the two you often end up opening and modifying the file from other folder.

So it would be nice to have a setting using which one can make quick search list files only from folder currently opened in workspace. Ideally this should be default behavior.

**Comment by bpasero** [comment]
@ADmad that should not happen unless you had opened these files previously. Could that be it? Can you share screenshot?

**Comment by ADmad** [comment]
> @ADmad that should not happen unless you had opened these files previously.

Yes I did open those files previously. But my point is after I open a new folder in the workspace, I don't want files from other folders i had opened earlier to be listed in quick search, even if they were recently opened.

I work on multiple projects which have similar file structure and naming (since those project use the same framework) and during the day I switch between the projects on few occasions. I have often ended up mistakenly editing file from another project, because the recent files list includes file from previously opened folder.

I hope this clears it :)

**Comment by bpasero** [comment]
@ADmad I still do not understand how this happens. here are my steps:
* clear all editor history (command palette > clear history)
* open folder foo
* open some files
* open folder bar
* open some files
* use quick search and notice that you do NOT see any files from folder foo

**Comment by ADmad** [comment]
After clearing again history I am unable to reproduce it myself either :(  I'll revert back if issue occurs again and I am able to provide a reliable way to reproduce it, sorry for the trouble.
