### ISSUE TITLE
Settings sync stopped working after update to 1.59.0

### ISSUE THREAD

**Issue by frndlyy** [microsoft/vscode#130361]
Issue Type: <b>Bug</b>

Right after the update to 1.59.0 (system setup) and ever since, I am getting the following error (on two different computers) when trying to run settings sync. Another machine with version 1.58.2 (system setup) that I am yet to update, does not have this issue. Looks similar to https://github.com/microsoft/vscode/issues/114231

`Error: Settings sync is suspended because of successive authorization failures. Please sign in again to continue synchronizing`

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2098)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|255.88GB (178.68GB free)|
|Process Argv|--crash-reporter-id 2d6b9e7e-2dbf-4a65-87b0-595066c88675|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.27.0
armview|ben|0.4.5
bracket-pair-colorizer-2|Coe|0.2.1
docs-markdown|doc|0.2.96
docs-preview|doc|0.3.57
docs-yaml|doc|0.2.7
vscode-firefox-debug|fir|2.9.4
rest-client|hum|0.24.5
vscode-sshfs|Kel|1.21.2
azure-pipelines|ms-|1.188.1
vscode-apimanagement|ms-|1.0.3
vscode-azureappservice|ms-|0.23.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azureserverlesspack|ms-|0.1.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.0
vscode-bicep|ms-|0.4.451
vscode-cosmosdb|ms-|0.18.0
vscode-docker|ms-|1.15.0
vscode-logicapps|ms-|1.0.17
csharp|ms-|1.23.14
vscode-dotnet-runtime|ms-|1.2.0
network-edge-devtools|ms-|1.0.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell|ms-|2021.6.2
vscode-node-azure-pack|ms-|0.2.1
azurerm-vscode-tools|msa|0.15.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-sanddance|msr|3.3.0
vscode-data-preview|Ran|2.3.0
vscode-data-table|Ran|1.7.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
vscode-inline-values-powershell|Tyl|0.0.5
shell-launcher|Tyr|0.4.1
vscode-java-debug|vsc|0.35.0
vscode-icons|vsc|11.6.0

</details>

**Comment by Ettariella** [comment]
I'm having the same issue, also since updating to 1.59.0. I am experiencing this on both Windows and macOS.

**Comment by SharakPL** [comment]
duplicate of #130314

you need last option from the context menu to choose an account for settings sync.

**Comment by frndlyy** [comment]
Choosing the account produces the same result. Instead of signing out, I chose the option to "Sign in with a Microsoft Account" and logged in with the same account. This appears to have fixed the problem. 
Closing this GitHub issue in favor of duplicate https://github.com/microsoft/vscode/issues/130314
Thank you @SharakPL

**Comment by SharakPL** [comment]
I was already signed into both GitHub and Microsoft accounts in VSCode and signing in again did nothing. Last option to choose an account for Settings Sync did the trick.

**Comment by yanke1311** [comment]
I have the same problem at 1.60
