### ISSUE TITLE
Extension server : onHover and async return value

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#1303]
Hello,

I'm building a language server extension and I'm trying to implement the onHover event like this:
```
connection.onHover((event):Hover =>{
	getHover(event.uri,event.position,(hoverString)=>{
// this is asynchronous
})
	return new Hover("i'm hover+"+hoverString)
})
```

How to change the hover message asynchronously ?

For info, I get an error on "new Hover" telling me that Hover is unknown but it is imported.
Is it a vscode-language-server mapping problem ?

Thanks in advance for your help.

**Comment by dbaeumer** [comment]
There is a documentation here how to implement a language server in general. https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by dbaeumer** [comment]
@Alphapage regarding the specific questions:

- import { Hover } from from 'vscode-languageserver';
There are a lot more type to import from there.
- Promise: all handlers can either return a value or a Promise. So for the Hover simple declare the return type as Thenable<Hover> and return a Promise (e.g. native Promise or some other Promis implementation).

**Comment by Alphapage** [comment]
Thank you for the info.

My onHover looks like this:
```
connection.onHover((event):Thenable<Hover> =>{
return	getHover(event.uri,event.position).then((str):Hover=>{
		return new Hover(str);
	})
})
```
But I always get "cannot find name Hover" from the line:
```
new Hover(str);
```
Thenable< Hover > doesn't throw any error !!

Can you help me a little more ?
