### ISSUE TITLE
The window has crashed (reason: 'oom', code: '-536870904')

### ISSUE THREAD

**Issue by newtykins** [microsoft/vscode#130375]
Does this issue occur when all extensions are disabled?: Yes

![Screenshot](https://i.newtt.me/r/ks3us33bn9a.png)

- VS Code Version: 1.59.0
- OS Version: Windows 10 21H1 (Build 19043.1110)

Steps to Reproduce:

1. Launch VS Code
2. Randomly but frequently while working I get the error screenshotted above and when I attempt to re-open the window it just crashes out of VS Code entirely.

**Comment by arzpgh60** [comment]
0pen

**Comment by newtykins** [comment]
This keeps happening still at frequent intervals, it's incredibly strange.

**Comment by deepak1556** [comment]
Please follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and attach the crash log. Make sure to launch with `--disable-extensions`

**Comment by pbldmngz** [comment]
Got the exact same issue opening an executable created with pyinstaller that used easyocr. I had a bug that made the program create infinite processes and collapse memory but never work. It works just fine in the editor though. After collapting my sistem this error may appear.

**Comment by Zaieon** [comment]
I've been getting this same issue also. My Visual Studio totally crashes and I have to re-run. I did an update recently though so I'm guessing that's the cause. Or maybe it has something to do with react because that's the technology I'm working with. Still searching for ways to fix it.

**Comment by manish-amplework** [comment]
![image](https://user-images.githubusercontent.com/87966718/131501689-80f68b88-ac86-4287-bcec-068ab3a5ce50.png)
I have also getting this issue.

**Comment by Zaieon** [comment]
How did you sort this out?

**Comment by the-one-with-raspberry** [comment]
I am also getting this issue!!!
![image](https://user-images.githubusercontent.com/72183318/132461489-5114a20d-9c1c-4bfd-819b-5011b1214726.png)

**Comment by the-one-with-raspberry** [comment]
@newtykins Good thing that you opened the issue

**Comment by newtykins** [comment]
Oh hey I didn't really find a way to fix it because I had planned to clean install Windows some time soon so I decided to do it then and when I reinstalled Visual Studio Code worked. So maybe fully remove Visual Studio Code from your system and then reinstall it?

**Comment by ghartz-hz** [comment]
I'm also seeing this problem fairly frequently since the last update of VSCode. On top of that, although a lot more minor of an issue, "Reopen" doesn't do anything.

**Comment by f-markus** [comment]
I also had / have this issue and I narrowed it down to a very strange change in my extension's package.json:
I do provide custom semantic types, so I have plenty of entries like:
```json
"semanticTokenTypes": [
      {
        "id": "identifier",
        "description": "identifiers without specific role"
      },
      {
        "id": "type",
        "superType": "type"
      },
      {
        "id": "enumeration",
        "superType": "enumMember",
        "description": "enumeration literals. enum types is a 'type'"
      }
]
```
When I added "description": "..." tags to all of the semanticTokenTypes (because otherwise the extension's runtime-status shows a warning that those entries don't have descriptions), the OOM error keeps showing up **deterministically**. It's not a single entry that causes the problem, but at least three of them. I couldn't figure out a workaround except for removing the "description" tags again.

**Comment by Hashflower** [comment]
Same issue here, anyone fixed it ?

**Comment by smi48** [comment]
![image](https://user-images.githubusercontent.com/47495777/135455669-0887da30-ee62-40db-9580-8c2f151141a2.png)
same issue, wtf

**Comment by Yasi97** [comment]
Same issue here, anyone solved it ?

**Comment by PaprPrintr** [comment]
Solved it, one of my RAM stick was fucked, as soon as I removed it the problem disappeared. Recommend to do a RAM check to identify the default one in case. Might not be the issue, but for me that was it.
