### ISSUE TITLE
The underline does not show in TERMINAL

### ISSUE THREAD

**Issue by zzeitt** [microsoft/vscode#130393]
We have written the needed data into your clipboard because it was too large to send. Please paste.
![image](https://user-images.githubusercontent.com/30381410/128674503-480c93ae-aa07-489a-8ae2-8991256f7388.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo you didn't give your VS Code version or platform.

See also #129142

**Comment by zzeitt** [comment]
> /needsMoreInfo you didn't give your VS Code version or platform.
> 
> See also #129142

I was using 1.58.xxx when reporting the bug.

The bug is fixed in 1.59.0.

That is, the problem is solved now.

Thanks.
