### ISSUE TITLE
VSCode crashes while exporting in DaVinci Resolve

### ISSUE THREAD

**Issue by TechStudent11** [microsoft/vscode#130363]
Does this issue occur when all extensions are disabled?: I don't know it's random.

- VS Code Version: 1.58.2
- OS Version: Windows 10 Version 20H2

I cannot provide Steps to Reproduce because it happened randomly. I was trying to export a 3 minute and 32-second video that was just Never Gonna Give You Up but it was reversed. Resolve crashed as well as VSCode. I took a screenshot of the error. Can someone tell me what this error means because I've never seen it before.

Error:
![image](https://user-images.githubusercontent.com/76978184/128639176-a7636d16-003f-423d-87f6-1cf00525b8db.png)

**Comment by Nufflee** [comment]
Assuming OOM means "out of memory", your computer ran out of memory which caused both Resolve and VSCode to crash. This is hence not a VSCode issue.

**Comment by TechStudent11** [comment]
> Assuming OOM means "out of memory", your computer ran out of memory which caused both Resolve and VSCode to crash. This is hence not a VSCode issue.

Ohhhhhhhhhhhhh okay. So it isn't a VSCode Error. Thanks!
