### ISSUE TITLE
VSCode freezes once I comment anything

### ISSUE THREAD

**Issue by BernardBrownie** [microsoft/vscode#130331]
Does this issue occur when all extensions are disabled?: Yes/No

- Yes

- VS Code Version:  1.59.0
- OS Version: Windows 10

What I've already tried:

- Reinstalling VSCode

Steps to Reproduce:

1. Comment code using "CTRL + /" shortcut

**Comment by rzhao271** [comment]
\gifPlease

**Comment by rzhao271** [comment]
Also, does this issue occur when running with extensions disabled?
