### ISSUE TITLE
Text typed in left editor is inserted in right editor when focused (HTML files)

### ISSUE THREAD

**Issue by 505aaron** [Microsoft/vscode#13030]
- VSCode Version: 1.5.3
- OS Version: Mac OSX 10.11.6

Steps to Reproduce:
1. Create two HTML files. 
2. Split edit HTML files
3. Place cursor at the beginning of right editor file
4. Type in left editor
5. Give focus to right editor

**Actual**
Text typed in left editor is inserted in right editor.

**Expected**
Focus is given to right editor

See attached gif for visual repro.
![vscodebug](https://cloud.githubusercontent.com/assets/1385823/18966908/64fe63b2-8640-11e6-9780-35ce0387afe6.gif)

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`?

**Comment by 505aaron** [comment]
Nope, it does not. I'll close this issue and try to isolate which plugin is doing this. Thank you
