### ISSUE TITLE
VSCode Insiders v1.60 Broken extensions

### ISSUE THREAD

**Issue by eo1989** [microsoft/vscode#130378]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open VSCode Insiders.
2. Click on Extensions menu button.
3. Notice all extensions are disabled by default, and the typical menu has changed. No option to enable ANY of the extensions, but will allow you to uninstall and reinstall them (until one of them requires reloading the software, in which case... rinse and repeat).
4. This bug has been brought up over the years (found a SO post from '16). Why does it keep being reintroduced? Strangely VSCode - stable (v1.59) does not have this issue.

**Comment by gjsjohnmurray** [comment]
Earlier duplicate is #130219
