### ISSUE TITLE
yamllint fails with "syntax error: expected <block end>, but found '<scalar>' (syntax)"

### ISSUE THREAD

**Issue by hunter86bg** [microsoft/vscode#130387]
Issue Type: <b>Bug</b>

It seems that when I create a yml file in my ansible roles (for example a new file defaults/main.yml ) the VS Code is not adding a new line at the end of the file which causes:
```
syntax error: expected <block end>, but found '<scalar>' (syntax)
```

Prototype code:
```
#Current Repo
repo_minor_ver: '82'
```

Yet, If I add a new line manually, the issue is gone.
I changed the 'The default end of line character.' from 'auto' to '\n' and it still causes that behaviour.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.59GB (1.48GB free)|
|Process Argv|--crash-reporter-id 1bb515c7-b94d-4ac1-81e0-81c5cced5073|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.8.1105858891
azure-account|ms-|0.9.8
vscode-yaml|red|0.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by hunter86bg** [comment]
Can we make VS Code to add add a EoF char at the end of a yml file ?

**Comment by aeschli** [comment]
You can achieve this with:
```
	"[yaml]": {
		"files.insertFinalNewline": true
	},
```
