### ISSUE TITLE
Weird letter spacing in Integrated Terminal for VS Code 2

### ISSUE THREAD

**Issue by Coronon** [microsoft/vscode#130356]
Issue Type: <b>Bug</b>

The exact issue as described in [this](https://github.com/microsoft/vscode/issues/120004) bug report just reappeared.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
Please let me know yours steps to reproduce this.

**Comment by Coronon** [comment]
I open VsCode with the integrated terminal open, the letter spacing is weird. I have to click on the ‘trash’ icon and then reopen the terminal to get it working again or manually resize it, which also fixes it after a few attempts.

**Comment by meganrogge** [comment]
This happens every single time for you? Can you please share your terminal settings and zoom level?

**Comment by Coronon** [comment]
Yes, it does since the newest update. Ill have too boot my PC, just got home.

**Comment by Coronon** [comment]
```json
{
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
   "window.zoomLevel": 1
}

**Comment by Coronon** [comment]
I like how mine is the duplicate, when it was opened 6 days before the other one ^^ But thx for looking into this
