### ISSUE TITLE
Cannot uninstall extension that has dependencies

### ISSUE THREAD

**Issue by stevenguh** [microsoft/vscode#130310]
Does this issue occur when all extensions are disabled?: N/A

# 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0

This is originally reported on https://github.com/VSpaceCode/VSpaceCode/issues/219. This is a new release issue (>1.59) as I have tested on 1.58.

Steps to Reproduce:

1. Install extension `vspacecode.vspacecode`
2. Try to uninstall VSpaceCode

I get the following error:
![image](https://user-images.githubusercontent.com/74915166/128578579-77f74701-e3a0-44b2-9974-eaac4da49e9d.png)

**Comment by stevenguh** [comment]
Related to #130298

**Comment by sandy081** [comment]
Thanks for filing the bug and also providing the fix. I will be pushing the fix to insiders which will be available tomorrow and fix will be included in next stable. 

Here is a workaround for now to use in stable - To uninstall open extensions folder using command `Extensions: Open Extensions Folder` and remove the extension.
