### ISSUE TITLE
Spelling mistake of an Object method in Intellisense for JavaScript

### ISSUE THREAD

**Issue by tariq-mz** [microsoft/vscode#130359]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59
- OS Version: Debian 10

Steps to Reproduce:

1. When we begin typing, it is suggested: Object.getOwnPropertyDescriptor() instead of the real Object.getOwnPropertyDescriptors() method
2. It raises an error: Uncaught TypeError: can't convert undefined to object

**Comment by IllusionMH** [comment]
It's not a spelling mistake - [Object.getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor) (ES5) in an actual method that predates [Object.getOwnPropertyDescriptors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors) (ES2017) so suggestion is correct.

/needsMoreInfo

Do you have `tsconfig.json` or `jsconfig.json` in that workspace? If yes - make sure that `libs` has at least `es2017` in list.

However, in case of folder without configuration and only `test.js` is shows both
![image](https://user-images.githubusercontent.com/1312662/128648535-06e311c6-a3ad-49e8-a01a-c1e43e4a1098.png)

**Comment by tariq-mz** [comment]
Okay, so  thanks for the information.
