### ISSUE TITLE
In TS 2.0.5 allowSyntheticDefaultImports is true in jsconfig.json -> adapt the generated jsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#13034]
see https://github.com/Microsoft/TypeScript/issues/10895

**Comment by jrieken** [comment]
We already have that: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/utils/projectStatus.ts#L204

**Comment by jrieken** [comment]
Seems like we added that with https://github.com/Microsoft/vscode/commit/cf130b686f3c3f8ea9b50395d9b25be59975d71d
