### ISSUE TITLE
Dark+ theme needs some improvements for 'keyword.operator' scope

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13033]
- VSCode Version:
- OS Version:

Used latest vscode extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

This can also be found when using extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

```delete``` is ```keyword.operator.delete``` and it should be colored like keyword and dark+ theme doesn't do that. I will report it in vscode repo

From Microsoft/TypeScript-TmLanguage#274
```typescript
import fetch from 'node-fetch';
import * as assert from 'assert';
import {API_URL} from '../../../../api/../config';
import {createTestToken, shouldRequireAdminPermission} from '../helper';
import {Product} from '../../../../api/models/investment/Product';
import {Notification} from '../../../../api/models/core/Notification';
import Sequelize = require('sequelize');
import * as sinon from 'sinon';
import {pusher} from '../../../../api/pusher';
import {assertDeepEqual} from '../helper';
import {pick, omit} from 'lodash';

describe('Product', () => {
    describe('GET /products', () => {
        shouldRequireAdminPermission('GET', '/products');
        it('should return a list of products', async () => {
            const product = await Product.create({
                name: 'Goldmine SMSF',
                description: 'Established goldmine self-managed super fund',
                type: 'unit',
                status: 'open',
                distributionPeriod: 'annually',
                distributionDate: new Date(Date.UTC(2016, 8, 7)),
                startDate: new Date(Date.UTC(2016, 8, 5)),
                endDate: new Date(Date.UTC(2016, 9, 5)),
                couponRate: '0.05',
                termType: 'absolute',
                managerId: 1
            });
            const token = createTestToken({ permissions: ['admin'] });
            const res = await fetch(API_URL + '/products', { headers: { 'Authorization': 'Bearer ' + token } });
            assert.equal(res.status, 200);
            const body = await res.json();
            delete body[0].createdAt;
            delete body[0].updatedAt;
            assert.equal(~~res.headers.get('x-total-count'), 1);
            assertDeepEqual(body, [{
                id: product.id,
```

**Comment by sheetalkamat** [comment]
Also reported in Microsoft/TypeScript-TmLanguage#273 by @octref  as
Previously:

![image](https://cloud.githubusercontent.com/assets/4033249/18942299/d6954cda-85cc-11e6-86e8-1ef158fdb1bd.png)


Now:

![image](https://cloud.githubusercontent.com/assets/4033249/18942303/de5d287a-85cc-11e6-8187-521a124190c4.png)

**Comment by aeschli** [comment]
'keyword.operator' is used for operators like &, || and or, which we want to keep in the default color.
I'd suggest to use 'keyword.control' or 'keyword'

**Comment by sheetalkamat** [comment]
But they are also scoped in detail like ```keyword.operator.new, keyword.operator.is, keyword.operator.delete, keyword.operator.in, keyword.operator.of, keyword.operator.instanceof, keyword.operator.void, keyword.operator.typeof```.

Other grammars like (atom-js)[https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar] use that scope too.

**Comment by aeschli** [comment]
The default themes now support the `keyword.operator.expression` scope
