### ISSUE TITLE
Directory named "environment" does not show in explorer treeView 

### ISSUE THREAD

**Issue by trailerparkdev** [microsoft/vscode#130369]
Quite simple. 
I create a directory named "environment" right under my app's main dir. I does not show in the Explorer's treeview. 
I rename it to "eenvironment" (from KDE's Dolphin), it shows. 
I rename it back (via the Explorer) to "environment", it disappears again (note that it does exist and two dummy files in it).
So, is "environment" a reserved or otherwise forbidden name? 
I'll be damn if it is.

**Comment by trailerparkdev** [comment]
Addition: 
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have `environment` in `files.exclude` config for User or Workspace levels?

**Comment by trailerparkdev** [comment]
@IllusionMH Thanks a lot for that. Indeed I had "env*" in files.exclude.
Although logical, I was only vaguely familiar with this setting.
Again, many thanks.
