### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by S-eito** [microsoft/vscode#130346]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

Every-time I try to change a setting regardless if it's font size, line height or even color theme I am met with the same "Can not write into the user settings..." error message. 

Everything I do I get this message, even if I am in user setting and using a drop down menu to try to change something.

I love VS Code but this is getting old. I really need to change the line height and font size so I can see better.

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 4ce8f93e-3aeb-4a54-9585-72cdd7b9a2ee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	    90	 55677	code main
    6	    49	 55680	   gpu-process
    0	    16	 55682	   utility
    7	    57	 55691	   shared-process
    0	    16	 55694	     ptyHost
    3	     0	 56322	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   188	 56025	   window (index.html — Practice)
    0	    41	 56026	     extensionHost
    0	    25	 56034	       /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=56026
    0	    16	 56035	       /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=56026
    0	    33	 56140	       /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/s2/wrtwhtbs3q3f8s2l0bqjhhb40000gn/T/AppTranslocation/58FA9CB8-92CD-4E59-B3C0-9C58692C74F6/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=56026
    0	    16	 56027	     watcherService
    0	    16	 56141	     searchService
    3	    57	 56319	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html — Practice)
|    Folder (Practice): 10 files
|      File types: png(3) DS_Store(2) html(2) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.7.1
vscode-power-mode|hoo|2.2.0
theme-monokai-pro-vscode|mon|1.1.19
material-theme|zhu|3.11.3

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is full error message?
Most likely you have syntax errors in `settings.json` file (or VS Code doesn't have permission to write to that file).

Do you see any errors if you open `settings.json` (<kbd>F1</kbd> `>Preferences: Open Settings (JSON)`) ?

**Comment by S-eito** [comment]
After restarting VSCode, everything is working fine now and I can make changes in the JSON file. Thx
