### ISSUE TITLE
Extension titles and icons continually gray out, not available

### ISSUE THREAD

**Issue by mitchellmorris** [microsoft/vscode#130333]
Issue Type: <b>Bug</b>

Open VSCode and you **notice that none of you extensions are available**.  The only thing I have found to prop this is not for the faint hearted.  Basically, go into the extensions menu that would otherwise at that moment have **icons and titles grayed out**, and then I would right click and notice that most of those options are grayed out too so I decided that my only option was to uninstall and reinstall it.  Nice that works! And all yes all my previous settings were preserved.

But then I would open another project.  Nooooooooo. Same. Issue.

I close what I thought I fixed and reopened it.  Yepnope.  Broke.

Please help.  This literally happened while I was sleeping. Just woke up and noticed the theme was gone and that's what got me looking.  I can't be the only one.

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:42:17.124Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 5259b7f3-ca77-48ca-9664-8a68b39e9d6f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
numbered-bookmarks|ale|8.1.0
Handlebars|and|0.4.1
LinkCheckMD|bla|0.3.1
vscode-opennewinstance|chr|0.0.7
vscode-markdownlint|Dav|0.43.2
svg-gallery|dev|2.1.0
vscode-notes|dio|1.1.0
chmod|dle|1.1.1
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.5
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.96
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.9
docs-yaml|doc|0.2.7
githistory|don|0.6.18
xml|Dot|2.5.1
gitlens|eam|11.6.0
restore-editors|eam|0.2.1
cep-debug-runner|hen|1.0.0
applescript|idl|0.21.0
vs-focus|Ivo|0.0.6
Angular2|joh|12.0.0
l13-projects|L13|1.1.0
sftp|lix|1.12.9
vscode-checkpoints|mic|1.3.2
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.15.0
remote-containers|ms-|0.191.0
export-typescript|msc|0.4.1
angular2-inline|nat|0.0.17
vscode-json-editor|nic|0.3.0
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
pin-up|sae|1.4.1
elm|sbr|0.26.0
vscode-autohide|sir|1.0.7
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
linenote|tkr|1.2.1
lorem-ipsum|Tyr|1.2.0
shell-launcher|Tyr|0.4.1
tab-groups|usa|1.4.8
branch-in-window-title|wis|0.1.2
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30348854
dockerwalkthrucf:30348714
bridge0723cf:30346311

```

</details>

**Comment by caleteeter** [comment]
Same issue here @mitchellmorris

**Comment by eamondo2** [comment]
Same problem as well, running code-insiders ver:
```
Version: 1.60.0-insider
Commit: 49af1cbe00271ac2ea36cfc5f7352fe31a7b0094
Date: 2021-08-06T06:38:56.151Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.11.0-25-generic
```

All of my extensions are disabled, I can get individual ones to temporarily re-enable by uninstalling and then reinstalling them, but once the window is reloaded it all reverts. 

Tested by going through and disabling the Trust feature via settings, and opening an explicitly trusted folder, no dice.

**Comment by TheLovinator1** [comment]
Same error here.


VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.95GB free)|
|Process Argv|--crash-reporter-id 0af40a44-9856-401d-9a45-35e49b9e2b45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.6.0
prettier-vscode|esb|8.1.0
copilot|Git|1.3.2277
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
powershell-preview|ms-|2021.8.0
code-spell-checker|str|1.10.2
lua|sum|2.3.4
even-better-toml|tam|0.14.2
errorlens|use|3.4.0
vscodeintellicode|Vis|1.2.14


</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30348854
dockerwalkthrucf:30348714

```

</details>
