### ISSUE TITLE
Settings Sync: Sync disabled extensions

### ISSUE THREAD

**Issue by hichemfantar** [microsoft/vscode#130362]
When I disable an extension, I'd like the disabled state to be synced.
Right now, when I connect my account on a different device, all the extensions are installed and activated, even the ones I previously disabled.

**Comment by sandy081** [comment]
Enablement state is synced too. Have you disabled the extension globally or per workspace?

**Comment by hichemfantar** [comment]
They're disabled globally.
I haven't tried this feature in a while, maybe It was a fixed, I'll try it soon and report the results.

**Comment by sandy081** [comment]
Thanks for the update. I will close it until then. Please reopen it if you see it again with steps to repro.
