### ISSUE TITLE
Expose NotebookCellOutput Id in stable

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#130308]
As an extension author of Notebooks in VSC Stable, I'd like to:
* Create a custom renderer that communicates back with the extension.
* Today the `OutputItem` has an `id` in the renderer.
* However in the extension, neither the outputs nor outputitems have an `Id` property.

I believe this is in proposed API right now.
Would like for this to be made stable. Else the custom renderers are limited as they cannot uniquely identify the notebook output in extension process what the messages belong to.

@rebornix @connor4312 /cc

**Comment by jrieken** [comment]
> Else the custom renderers are limited as they cannot uniquely identify the notebook output in extension process what the messages belong to.

You can use cell index, output index, mime-type to identify an output

**Comment by DonJayamanne** [comment]
> You can use cell index, output index, mime-type to identify an output

Now sure what you mean.
The OutputItem in the renderer only has Id & mime.
If I pass this to the extension host, there could be 10 other cells with the exact same mime type.
Not sure where `cell index` is exposed in renderer to be able to uniquely identify an output.

Again, the outputItem.id is in proposed API & the request is for this to be made stable.

**Comment by DonJayamanne** [comment]
Another place this is required https://github.com/microsoft/vscode/issues/131913
(Currently working around by adding my own `id` into the output metadata)

**Comment by DonJayamanne** [comment]
Not required, currently adding cusotm metatadata that services as a unique identifier
