### ISSUE TITLE
Provide a way to stop changing the focus to Explorer when selecting new files

### ISSUE THREAD

**Issue by nickchomey** [microsoft/vscode#130328]
I'd like it so that when I am using debug the focus doesn't change to Explorer each time a different file gets opened as I step through the code. Same goes for when using Search - I'd like the search pane to persist so that I can keep opening different files quickly while I find what I'm looking for. 

When I'm doing either of these actions, I don't need the explorer - the file info is available in the tab header. Its a great nuisance to have to switch back to the debug/serach pane each time.

To be clear, I'm not talking about Auto Reveal.

**Comment by isidorn** [comment]
`explorer.autoReveal: false`

There is no other way around this. Or you are not explaining the issue clearly enough
