### ISSUE TITLE
Customize `tab.activeBorder` thickness

### ISSUE THREAD

**Issue by mhmmd-ysf** [microsoft/vscode#130394]
Is it possible to make this (active border) thickness customizable? Because creating a new theme just for the sake of it seems 'expensive'.

![image](https://user-images.githubusercontent.com/46883609/128675896-4ed4c1d6-3978-49f1-9c87-e027de3e33d0.png)

**Comment by gjsjohnmurray** [comment]
That is controlled by `tab.activeBorder`

You can override the color using [this technique](https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors) but I don't think the thickness is configurable, not even by a complete new theme.
