### ISSUE TITLE
Display file explorer in a tab

### ISSUE THREAD

**Issue by eternalfreeze** [microsoft/vscode#130342]
Currently we can display a file explorer by using the hot key CTRL + SHIFT + E.
But this takes up the space on the left hand side. And if one wants to hide it, then they have to use the hot key CTRL + B every time.
Recently VS Code adds the ability to treat a terminal window as a tab.
It would be nice if the file explorer can be treated as a tab as well.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now to gather more feedback. Thanks
