### ISSUE TITLE
Use `ThrottledDelayer` for language detection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130315]
I suggested to use `RunOnceScheduler` but realise that `ThrottledDelayer` would be better because this helper prevents accumulation of long running tasks (i.e. supports promises). The scheduler will not prevent the language detection from running multiple times if it happens to take longer than 600ms, but we really want to ensure that language detection runs do not accumulate I would say.

**Comment by TylerLeonhardt** [comment]
All these great utility classes 😃 I should go through them all to learn about them.

Got any others that you use a lot that are worth me knowing?

**Comment by bpasero** [comment]
Hehe, I encourage people to go through the things in `vs/base` there is lots we have accumulated. Besides those async helpers (most from Joao), I like the [`Event`](https://github.com/microsoft/vscode/blob/cd121a7976bd0c8cc5bb93eda6f34ae7e5f4ab2e/src/vs/base/common/event.ts#L21-L21) mappers.
