### ISSUE TITLE
Allow extensions to register snippet variable resolvers

### ISSUE THREAD

**Issue by movermeyer** [microsoft/vscode#130325]
### What is the problem you're trying to solve?

[Foam](https://github.com/foambubble/foam) is a personal knowledge management and sharing system inspired by Roam Research, built as a Visual Studio Code extension.

Foam users create [Foam note templates](https://foambubble.github.io/foam/features/note-templates.html) using the snippet syntax. When they create a new note using the template, Foam calls `editor.insertSnippet` with the template text and VS Code resolves the variables and puts the editor into snippet mode, creating a nice note-creation UX.

Foam also defines Foam-specific `$FOAM_TITLE` and `$FOAM_SELECTED_TEXT` snippet variables, which on the surface appear to behave just like VSCode Snippet variables. However, they are resolved by Foam prior to the resulting `SnippetString` being passed to `editor.insertSnippet`.

---

<details>

<summary><b>Example snippet variable resolution</b></summary>

The user provides the following template and then creates a new note using the template:

```markdown
My template using both VSCode and Foam-specific snippet variables:

# $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE: $FOAM_TITLE
```

Foam resolves the Foam specific variables (e.g. `$FOAM_TITLE` -> `On the Origin of Species`) and gives VSCode the `SnippetString`:

```markdown
My template using both VSCode and Foam-specific snippet variables:

# $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE: On the Origin of Species
```

And VSCode opens the editor in snippet mode with the contents:

```markdown
My template using both VSCode and Foam-specific snippet variables:

# 2021-07-16: On the Origin of Species
```

</details>

---

The current implementation has a few notable limitations:

1. We don't have access to VSCode's snippet parser, so properly finding the Foam-specific variables is currently done via a hacky regex
   * Which leads to [edge-case bugs](https://github.com/foambubble/foam/issues/602)
2. Foam-specific variables cannot be used as part of placeholders, nor transforms
  * We resolve the Foam-specific snippet variables **before** passing them to VS Code
  * Placeholders and transforms require variables, and cannot be used on plain strings of the resolved Foam-specific variables that VS Code gets given

I believe these limitations could be resolved if there were a way for extensions to register snippet variable resolvers with VS Code.

#### Why not `CompletionItemProvider` API?

In this case, the users are not using completions (i.e. they are not hitting `Ctrl+Space` and typing a prefix), but they are writing their own template files using the snippet syntax.

### Do you have any potential ideas for how to solve the problem?

Perhaps VS Code could allow extensions to register snippet [`VariableResolver`s](https://github.com/microsoft/vscode/blob/ea132060dd8c71baa6b2f77e46287710b888bb01/src/vs/editor/contrib/snippet/snippetParser.ts#L483-L485)
These would be called at the same time as all the other resolvers, meaning that:

* Extensions can use VS Code's infrastructure for parsing / locating the variables (Solving limitation 1)
* Extensions can use VS Code's infrastructure for placeholders and transforms (Solving limitation 2)

### Related/Previous issues

* https://github.com/microsoft/vscode/issues/94372
* https://github.com/microsoft/vscode/issues/67718
* https://github.com/microsoft/vscode/issues/59557
  * Instead of being user-defined, they would be extension-defined.
* https://github.com/microsoft/vscode/issues/63534
  * Instead of being user-defined, they would be extension-defined.
* https://github.com/microsoft/vscode/issues/10561
  * Somewhat related: In that code from outside of VSCode's core code is being called, but different UX/usage

**Comment by movermeyer** [comment]
* Pinging @jackwilsdon @gjsjohnmurray @sh7dm @josh-cook @iliazeus @murraycollingwood @shogerr @usernamehw since you upvoted https://github.com/microsoft/vscode/issues/94372
* Pinging @Gruntfuggly since you created https://github.com/microsoft/vscode/issues/67718
* Pinging @DavidHenri008 since you created https://github.com/microsoft/vscode/issues/59557
* Pinging @antmdvs @jmsv @edwardgalligan @dsdenes @yunxi177 @zaverden @parkerault @adamOsieckiBtn @oabpeytzsince since you upvoted https://github.com/microsoft/vscode/issues/63534

If you still want to see this feature added, I'd encourage you to upvote this issue.

**Comment by jrieken** [comment]
Sorry, cannot be done because extensions run in a separate process/thread making such resolvers async. However, snippet insertion is sync due to "snippet only tab complete".
