### ISSUE TITLE
No div completion on Template literals inside of ES6/TS files

### ISSUE THREAD

**Issue by falconmick** [Microsoft/vscode#13039]
More of a feature request than a bug, but Sublime Text can handle auto-creating div's through the div.someclass syntax inside of Template literals, just wondering if it could be added to VSCode.

Cheers

**Comment by aeschli** [comment]
That would be Emmet completion inside ES6/TS if I understand correctly.

**Comment by egamma** [comment]
@falconmick what you can do today is to associate the emmet syntax profile for HTML with javascript. This is documented here https://code.visualstudio.com/updates/v1_5#_languages. Does this cover your scenario?

**Comment by ramya-rao-a** [comment]
@aeschli What would it take to mark template literals as `html` just like we mark html inside jsx files as `jsx-tags?

This would help #13414 as well
