### ISSUE TITLE
Ability to snap window

### ISSUE THREAD

**Issue by 0dp** [microsoft/vscode#130395]
Issue Type: <b>Feature Request</b>

It seems that VScode's window is not capable to snap to corners etc.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-144-generic

**Comment by deepak1556** [comment]
\gifPlease

**Comment by 0dp** [comment]
@deepak1556 
Here using Sublime as example:
https://gyazo.com/46e250dacae1d933f48f8039e72bd62c

Here using VScode:
https://gyazo.com/966e3650b5bba7a14dc50497fbb0d16c

**Comment by deepak1556** [comment]
Thanks for the recording, this depends on support from the runtime for custom titlebars. You can use `"window.titleBarStyle": "native"` setting as workaround.

**Comment by 0dp** [comment]
@deepak1556 Thank you! This has been bugging me for quite some time.
Since this is already a setting, is there any reason the keep this issue open?

**Comment by deepak1556** [comment]
I kept it open for custom titlebar but if the setting helps, feel free to close the issue.
