### ISSUE TITLE
Duplicate definition warning for Interface defined in same file - C#

### ISSUE THREAD

**Issue by Thyshadow** [Microsoft/vscode#13031]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:

1. Define Empty interface in a namespace 
2. Define class using interface in same namespace in the same file

Result: The interface declaration has a red underline. 
The text that pops when hovering the cursor over the interface name is: 
"The namespace 'TrainingPlus.DataAccess' already contains a definition for 'ITrainingClassRepository' [netcoreapp1.0]
TrainingPlus.DataAccess.ITrainingClassRepository"

Notes:
This error does not stop the project from compiling, this appears to only be a warning from the IDE.
When I disable plugins the highlighting error goes away. 
I assume the problem is with the C# extension "C# for Visual Studio Code (powered by OmniSharp)" provided by microsoft

Class Definition following:
----------------------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using TrainingPlus.Models;

namespace TrainingPlus.DataAccess
{
    public interface ITrainingClassRepository : IGenericRepository<TrainingClass>
    {
    }

    public class TrainingClassRpository : ITrainingClassRepository
    {
        public void Add(TrainingClass item)
        {
            throw new NotImplementedException();
        }

        public IEnumerable<TrainingClass> Find(TrainingClass item)
        {
            throw new NotImplementedException();
        }

        public IEnumerable<TrainingClass> GetAll()
        {
            throw new NotImplementedException();
        }

        public TrainingClass Remove(TrainingClass item)
        {
            throw new NotImplementedException();
        }

        public TrainingClass Select(TrainingClass item)
        {
            throw new NotImplementedException();
        }

        public void Update(TrainingClass item)
        {
            throw new NotImplementedException();
        }
    }
}

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: https://github.com/OmniSharp/omnisharp-vscode/issues
