### ISSUE TITLE
Support msys git

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13037]

**Comment by Tyriar** [comment]
Should we be supporting deprecated software? https://github.com/msysgit/msysgit

> msysGit has been superseded by Git for Windows 2.x

Also you may want to elaborate if you want contributions, do you mean searching for its packaged versions of git?

**Comment by joaomoreno** [comment]
> msysGit has been superseded by Git for Windows 2.x

Awesome.
