### ISSUE TITLE
different editor briefly flashes when debugging

### ISSUE THREAD

**Issue by RYDB3RG** [microsoft/vscode#130321]
@isidorn [this fix](https://github.com/microsoft/vscode/commit/90327eae5da3fe987175e12a61ed8bd86ba05fc5#diff-c346def4d04214f97b5a210a6b97322bcd40bf6d788a625001a9debf13af53a3R910-R917) (and its followups) look buggy to me

Am I mistaken or is this whats happening: `clearThreads` reset thread's `stopped` to false, `focusStackFrame` then goes ahead and looks for thread with `stopped=true`, doesnt find current thread anymore (because cleared) and thus briefly removes focus from the current thread, leading to this:
![125192699-8104d680-e249-11eb-8526-1c4f77854996](https://user-images.githubusercontent.com/7002848/128598370-d149913e-2cda-44fa-9801-3f1ca20f66a6.gif)

(follow up of #128415)

**Comment by isidorn** [comment]
@gregg-miskelly how does this not happen to Visual Studio? Is there some heuristic on top? Or maybe it happens, but users are not hitting it?
Since this is the problem I outlined in this comment here https://github.com/microsoft/vscode/issues/125144#issuecomment-869641057

To solve this I can introduce a timeout before I move focus to another thread, so that fast stepping would not switch quickly like in the GIF above.

**Comment by gregg-miskelly** [comment]
To make sure I understand, is this what is going on?
1. The user is debugging two processes
2. Process A is already stopped
3. A breakpoint is hit in process B
4. The UI immediately switches focus to process B
5. The user hits step
6. The UI switches focus back to process A
7. The debug adapter sends a stop event for the step completing in process B
8. The UI switches back to process B

In VS step 4/8 wouldn't happen - if the UI is already stopped, and a new stopping event comes in, that stopping event is queued. So instead when the breakpoint is hit, focus would stay on process A. If you didn't want to be on process A any more, the user can hit continue (or manually switch to process B), and then we would dequeue the stopping event.

**Comment by RYDB3RG** [comment]
The problems happens when debugging a single process with multiple threads.

When a breakpoint is hit, all threads are paused correctly.

When then singlestepping the breaked thread, `onDidContinue` handler resets thread's `stopped` bool to false in `clearThreads`
and then calls `focusStackFrame`.

The problem is that `focusStackFrame` searches for threads with paused=true (in `getStackFrameThreadAndSessionToFocus`) and doesnt find current thread anymore (because `stopped` bool was just reset).

(Atleast this is my understanding)

**Comment by gregg-miskelly** [comment]
Got it. And the behavior of whatever debug adapter you are using is to break these additional threads and leave them paused after continuing the stepping thread?

Assuming that is correct: VS doesn't have a quite analogous scenario to this -- in our scenarios, the background threads would get resumed at the same time as the stepping thread. Off hand, I would guess the best behavior would be to either delay or entirely avoid swapping stack frames if there are no queued events. In other words, make the user manually select a new thread, or only automatically swap threads if say 2 seconds have elapsed without a new stopping event.

**Comment by RYDB3RG** [comment]
Yes, timeout should fix it, but I'm wondering if changing the order of calls in `onDidContinue` is also valid. Atleast it fixes the issue for me:

```diff
diff --git a/src/vs/workbench/contrib/debug/browser/debugSession.ts b/src/vs/workbench/contrib/debug/browser/debugSession.ts
index 0ca0de841ed..2d47b3c0d5c 100644
--- a/src/vs/workbench/contrib/debug/browser/debugSession.ts
+++ b/src/vs/workbench/contrib/debug/browser/debugSession.ts
@@ -949,8 +949,6 @@ export class DebugSession implements IDebugSession {
 				this.cancelAllRequests();
 			}
 
-			this.model.clearThreads(this.getId(), false, threadId);
-			this._onDidChangeState.fire();
 			// If there is some session or thread that is stopped pass focus to it
 			if (this.debugService.getModel().getSessions().some(s => s.state === State.Stopped) || this.getAllThreads().some(t => t.stopped)) {
 				if (typeof threadId === 'number') {
@@ -967,6 +965,9 @@ export class DebugSession implements IDebugSession {
 					}
 				}
 			}
+
+			this.model.clearThreads(this.getId(), false, threadId);
+			this._onDidChangeState.fire();
 		}));
 
 		const outputQueue = new Queue<void>();

```

**Comment by isidorn** [comment]
Thanks a lot for the information and ideas.
I decided to go with a 800ms timeout, so only if the `stop`  event does not happen in `800ms` we would pass the focus. I tried this out and it works fine for me. Try it out and let me know how it goes.

**Comment by RYDB3RG** [comment]
30d73ea fixes the problem for me. Thanks.

**Comment by isidorn** [comment]
Great, thanks. Adding verified label.
