### ISSUE TITLE
Variable view cluttered with "proto" entries in Node

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/vscode#130365]
Does this issue occur when all extensions are disabled?: Yes/No 
Yes

- Version: 1.58.2 (user setup)
- Commit: c3f126316369cd610563c75b1b1725e0679adfb3
- Date: 2021-07-14T22:10:15.214Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

I'm running Node 16.6 and am getting some debugging behavior that seems "new"

1. Write a simple node script that creates an object. Something like:
```javascript
  const a = { this: 3, that: 42, bar: { test1: 'sa', test2: 'po' } }
  console.log(a)
  console.log()
```
2. Debug that script with a breakpoint on the last line
3. When you hit the breakpoint, expand all the properties in the debugger's Variables pane. Notice that there are many entries for `__proto__` and `[[Prototype]]` cluttering up the view.  For example
![image](https://user-images.githubusercontent.com/10070956/128641101-73d79064-a5d2-436b-8f36-06ac55ded3de.png)
4. In the Debug Console you also should see `{this: 3, that: 42, bar: {…}}`. Expand that and notice the same cluttered output. For example: 
![image](https://user-images.githubusercontent.com/10070956/128641126-5eb39b7e-2722-46ac-bea3-42265fe06218.png)

While I get that this may be technically accurate, it makes it very difficult to sort my object props from all the prototype values that are rarely (if ever) useful. I do recall something like the [[Prototype]] entry but do not recall the __proto__ entries. Are those new?

Suggestion would be to ether make an option to hide these (e.g., `variablesViewType: 'uncluttered'` or group them all under one entry that users can expand if they want to see the prototype related values.

**Comment by connor4312** [comment]
Thanks!
