### ISSUE TITLE
Process exited with code 3221225477

### ISSUE THREAD

**Issue by TLKG** [microsoft/vscode#130377]
Issue Type: <b>Bug</b>

This occurs on my Node.js project as backend API. I've observed the pattern as:
1) whenever it's run as "Disable all breakpoints" or no breakpoints at all.
2) then "Disable all breakpoints", "Enable all breakpoints" will run ok.

This is related to this "Unbound breakpoints":
https://stackoverflow.com/questions/64589447/unbound-breakpoint-vs-code-chrome-angular/68323650#68323650

On a side note for this SO issue, I'm also running Angular v11 UI project. The way I discovered this not-hitting-breakpoint issue is most of work is on UI, and sometimes the debug execution not hitting any breakpoint at all, yet no errors printed on console, nor terminal, but execution at browser was not going anywhere, like died in the middle without any error. Meanwhile, all standalone browsers Chrome and Edge are running fine meaning they reach the expected result, not kind of execution seems lost (not hanging). After applying all fixes mentioned in this SO except "devtoolModuleFilenameTemplate: '[absolute-resource-path]'", UI project hits breakpoint always! Did I have this issue before? My memory is not before mid-June.

Because my API project is much smaller, so sometimes I simply disabled breakpoints, then this "Process exited with code 3221225477" came up.

I tried to do "code --crash-reporter-directory <absolute-path>" following https://github.com/microsoft/vscode/wiki/Native-Crash-Issues. New dump folder contains only metadata and settings.dat, "reports" folder is empty so no dump file is available for report.

Thank you!

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (14.85GB free)|
|Process Argv|--crash-reporter-directory C:\\Users\\me\\Documents\\CanDel\\VSCDump|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
openssl-configuration-file|gee|0.0.1
vscode-pull-request-github|Git|0.29.0
regionfolder|map|1.0.15
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.3.684299474
cpptools|ms-|1.5.1
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
sonarlint-vscode|Son|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by connor4312** [comment]
Thank you for the debugged log. The log you posted looks like the program exited normally, and we reported the code that it exited with. At the time it exited, breakpoints weren't touched. You're also debugging a Node.js program, I'm not sure what you're referring when you talk about browser issues. If those are separate problems, please open a separate issue.

**Comment by TLKG** [comment]
Connor,
Forget about the browser issue, it's a totally diff one.
The exit is on a Node.js program running as backend API:
My machine is always power off at the end of the day.
First start in the morning, if F5 starts this API without any breakpoint enabled, as soon as a request comes in will cause "Process exited with code 3221225477"
But if F5 with one breakpoint enabled anywhere in the execution path for a request, this breakpoint will always be hit, no more exit.
Further more, I can disable/remove any breakpoint from now on, even restarting VSC and F5, no problem.
In other words, with a breakpoint does matter for Node.js debugging. I can set up a demo over MS TEAM if needed. Let me know.

Appreciate it.

On August 17, 2021 at 10:24 AM, Connor Peet ***@***.***> wrote:






Thank you for the debugged log. The log you posted looks like the program exited normally, and we reported the code that it exited with. At the time it exited, breakpoints weren't touched. You're also debugging a Node.js program, I'm not sure what you're referring when you talk about browser issues. If those are separate problems, please open a separate issue.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by connor4312** [comment]
This seems like a bug in Node.js where something is crashing. I suggest seeing if it repro's in the latest 16.x version and, if so, open an issue on them.

**Comment by mcdado** [comment]
If it is helpful to anyone, I had the same exact problem. To solve it I recreated a new debug configuration via the menu and checked the difference with my `launch.json` file that I was carrying over since a few years. I then did two things, I suspect the second one was the one that actually made a difference:

1. Make sure the debugger `type` is `pwa-node`. Mine was still `node`.
2. Make sure `skipFiles` **only** contains the one default value.

```js
"configurations": [
  {
    "name": "Launch Program",
    "program": "${workspaceFolder}/app.js",
    "request": "launch",
    "skipFiles": [
      "<node_internals>/**"
    ],
    "type": "pwa-node"
  }
}
```

I'm not sure how, probably because of the old debugger, my `skipFiles` settings had other values:

```js
"skipFiles": [
    "<node_internals>/**/*.js",
    "/usr/local/lib/node_modules/**/*.js",
    "${workspaceFolder}/node_modules/**/*.js"
]
```

My suspicion  is that these other values create some infinite loop or memory leak somewhere in the new debugger.

**Comment by TLKG** [comment]
I have exactly **only one** skipFiles
```
 "skipFiles": [
                "<node_internals>/**"
```

FYI, also have this outside of `configurations`, hope it's not the culprit.

```
"resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
    ]
```

**Comment by weinand** [comment]
@TLKG With VS Code 1.60 `node` is just an alias for `pwa-node`. The underlying VS Code debugger extension (`js-debug`) is the same.

`skipFiles` is just a property that tells `js-debug` to ignore certain files when stepping through the code or hitting exceptions. Whether `skipFiles` has one or more glob patterns shouldn't matter. More patterns are just adding more files to the set of ignored files. 

Having debugger extension specific properties like `resolveSourceMapLocations` outside of `configurations` doesn't make sense (and should be flagged as an error if the launch.json is opened in an editor).
These properties are defined per type (e.g. `pwa-node`) and they must occur in the configuration structure inside the `configurtaions` array. 

Please use Intellisense in the launch.json editor to find the possible properties and values.
Any errors ("squigglies") in the launch.json are asking for trouble.

**Comment by TLKG** [comment]
@weinand Thanks for the detailed instruction. 

- `resolveSourceMapLocations `outside of `configurations `doesn't have red squigglies, used intellisense adding into configuration.
- remove the one outside.

Same outcome.
