### ISSUE TITLE
Formatting on save: script type=module broken

### ISSUE THREAD

**Issue by mhaszprunar** [microsoft/vscode#130398]
We have written the needed data into your cl
Issue Type: <b>Bug</b>

<html>
<body>
<script type="module">
        import something from "somewhere";
        var test= new somethingClass();
        // setup listener
        window.addEventListener(viz.customEventName, function(e, d) {
            console.info("listener:", e, d);
        });
</script>
</body>
</html>

when saving the formatting on save kicks in (great feature), but inside the script tag it puts everything on a single line. When the line is full the formatter creates a hard break which causes all kinds of issues, e.g. incomplete strings, etc. It also leads to having single line comments suddenly afects a whole lot more code.
result of step see below:

<html>

<body>
    <script type="module">
        import something from "somewhere"; var test= new somethingClass(); // setup listener window.addEventListener(viz.customEventName, function(e, d) { console.info("listener:", e, d); });
    </script>
</body>
</html>

I currently can workaround by saving without formatting, but this needs to be fixed.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.05GB free)|
|Process Argv|--log debug --crash-reporter-id e77223ab-f732-42f3-b6f3-72f36907d70f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-end-tag-labels|ant|0.7.0
vscode-eslint|dba|2.1.23
snippet|dev|1.0.1
auto-rename-tag|for|0.1.8
fracturedjsonvsc|j-b|2.1.0
vscode-codemetrics|kis|1.24.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
prettify-json|moh|0.0.3
live-server|ms-|0.2.7
indent-rainbow|ode|7.5.0
es6-css-minify|olb|3.3.2
prettier-vscode-with-tabs|pas|1.1.0
vscode-yaml|red|0.22.0
vscode-javascript-booster|sbu|14.0.1
vscode-babel-repl|t-s|0.1.2
quokka-vscode|Wal|1.0.390

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

ipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled? Especially `vscode-JS-CSS-HTML-formatter`
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

If it's still reproducible with all extensions disabled please show code before and after that is wrapped in code block ` ``` ` so it would be easier to reproduce. Example:
````
```
code
```
````

**Comment by mhaszprunar** [comment]
Thank you @IllusionMH 
I reloaded without extensions and behaviour was fine! I will test all extensions individually to find the culprint and open a defect for this then.
Can be closed

**Comment by IllusionMH** [comment]
Most likely `vscode-JS-CSS-HTML-formatter` but if it's not his extension you can try <kbd>F1</kbd> `>Help: Start Extension Bisect` that should simplify search.
See https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect
