### ISSUE TITLE
CRASHING OF VISUAL STUDIO CODE

### ISSUE THREAD

**Issue by itsyourboyrj** [microsoft/vscode#130319]
We have written the needed data into your clipboa
Issue Type: <b>Bug</b>

HELLO MICROSOFT ,
 I HAVE UPDATED MY LAPTOP TO WINDOWS 11 21H2 EXPERIENCE PACK AND SINCE THE UPDATE EVERYTHING IS GOING FLAWLESS WITHOUT ANY BUGS AND CRASHES EXCEPT THE ONE, VISUAL STUDIO CODE . SINCE I AM FRONTED WEB DEV AND I USUALLY USE VS CODE FOR MY CODING PROJECTS, AND ITS RUNNING FLAWLESSELY GOOD SINCE WINDOWS 10. BUT AFTER THE RECENT UPDATE OF 21H2 EXPERIENCE PACK FOR WINDOWS 11 I AM FACING ISSUES ON MY VS CODE IT SUDDENLY CRASHES WHILE I WAS USING AND A DIALOGUE BOX APPEARS ON MY SCREEN THAT IT HAS BEEN CRASHES PLEASE WAIT TO RESPOND OR CLICK REOPEN.
AT FIRST I THOUGHT IT JUST NIRMAL AND WOULD BE FIXED AUTOMATICALLY BUT, IT IS HAPPENING MORE OFTEN NOWADAYS THAT'S WHY I THOUGHT I NEED TO REPORT ABOUT THIS.
SO PLEASE IF ITS FIXABLE AND I KNOW IT IS AS ITS JUST A PIECE IF CODE SO  DO CHECK OUT THIS AND HELP ME TO FIX THE PROBLEM . AND HOPE YOU WILL REACH ASAP !!

THANKYOU
 RAVI RAJ
(BETA TESTER)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.57GB free)|
|Process Argv|--crash-reporter-id fb7a6466-214f-4a7a-89e9-a7a6f854db8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
vscode-clang|mit|0.2.4
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.9.0
LiveServer|rit|5.6.1
ayu|tea|0.20.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

rd because it was too large to send. Please paste.

**Comment by SirMishaa** [comment]
Be careful, it seems to me that your shift key is blocked.
😁

**Comment by deepak1556** [comment]
Please attach crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
