### ISSUE TITLE
Command Line Option to Start Remote Connection (SSH Remote)

### ISSUE THREAD

**Issue by MatthewFagan** [microsoft/vscode#130313]
It would be great to have a command line option to launch vscode against a specific remote workspace. That way, it would be possible to write shell scripts that do, for example, run vscode on the remote and also open SFTP connection to the same machine and also start up a couple of separate SSH windows, or even fire up web browsers pointing to specific ports on the target machine.

**Comment by roblourens** [comment]
This is possible, see https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal
