### ISSUE TITLE
Debug: move run/debug menu contribution into debug land

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130385]
Talking about this new code:

https://github.com/microsoft/vscode/blob/bf8ac08db9c29c0d9d96240d01d5ea24ae5ec77a/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L323-L323

I feel this is a layer breaker because it seems this should move into a `debug.contribution.ts` rather?

**Comment by weinand** [comment]
@bpasero the code is not new, just passing the `rememberDefaultAction` option is new, but I have moved the contribution to debug land.

**Comment by bpasero** [comment]
Thanks!
