### ISSUE TITLE
First notebook cell doesn't always render

### ISSUE THREAD

**Issue by mcrapts** [microsoft/vscode#130324]
Issue Type: <b>Bug</b>

1. Have a cell where the first cell contains code like `import pandas as pd`
2. Have some multiple cells where something happens below
3. Save and close the notebook and observe that sometimes the first cell doesn't render

I have problems reliably reproducing the issue, so I'm not sure what's causing it.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.72GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/marco/projects/coronacijfers --remote=wsl+Ubuntu --crash-reporter-id fb50cf3c-1a45-4bb7-8ca4-b45ffad8ef02|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|Memory (System)|12.40GB (11.40GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-wsl|ms-|0.58.2
toml|be5|0.5.1
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
r|Iku|2.1.0
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
vetur|oct|0.34.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by rebornix** [comment]
@mcrapts can you share your settings to help troubleshoot?

**Comment by mcrapts** [comment]
You mean `settings.json`? 

<details>
<summary>settings.json</summary>

```
{
    "workbench.colorTheme": "Monokai",
    "git.enableSmartCommit": true,
    "window.zoomLevel": 0,
    "terminal.integrated.fontFamily": "DejaVu Sans Mono for Powerline",
    "[vue]": {
        "editor.defaultFormatter": "octref.vetur"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "python.venvPath": "~/.cache/pypoetry/virtualenvs",
    "vetur.format.defaultFormatter.html": "prettier",
    "python.languageServer": "Pylance",
    "python.dataScience.askForKernelRestart": false,
    "jupyter.askForKernelRestart": false,
    "python.linting.flake8Enabled": true,
    "[jsonc]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "notebook.outline.showCodeCells": true,
    "python.terminal.activateEnvironment": false,
    "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "python.analysis.typeCheckingMode": "basic",
    "diffEditor.ignoreTrimWhitespace": false,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    }
}
```

</details>

**Comment by mcrapts** [comment]
I haven't encountered this issue anymore since recent updates. I think the issue can be closed.
