### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by gaurav5544** [microsoft/vscode#130350]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

program output works correctly in terminal but after running that program again it goes to much down and my previous output can't clear while i am enable this setting, please solve this issue it is to much irritating.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.94GB free)|
|Process Argv|--crash-reporter-id 027804d4-8b79-4d2d-8467-1d6ee17fd135|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	 10828	code main
    0	    88	 11628	   window (Issue Reporter)
    1	    89	 13008	   shared-process
    0	    77	 15312	     ptyHost
    0	    65	  6740	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 15676	       console-window-host (Windows internal process)
    0	     6	 16500	       console-window-host (Windows internal process)
    0	    72	 19724	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    24	 13788	   crashpad-handler
    0	    37	 14316	   utility
    0	   191	 17548	   gpu-process
    0	   158	 20092	   window (neso4.c - neso c programs - Visual Studio Code)
    0	   131	 16812	     extensionHost
    0	    14	  4268	       c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.5.1\bin\cpptools.exe
    0	    10	  3428	         console-window-host (Windows internal process)
    0	    13	 10848	         c:\Users\gaura\.vscode\extensions\ms-vscode.cpptools-1.5.1/bin/cpptools-srv.exe 4268 {268FD6CC-A631-446E-9977-5C9060A24D90}
    0	    70	 16452	       "C:\Users\gaura\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\gaura\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16812
    0	    14	 18484	     watcherService 
    0	    11	  8756	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (neso4.c - neso c programs - Visual Studio Code)
|    Folder (neso c programs): 8 files
|      File types: c(4) exe(4)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.5
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

![Screenshot (1)](https://user-images.githubusercontent.com/82212099/128624602-87132603-1c5b-4ecd-8637-e4b51e3d683e.png)

**Comment by gaurav5544** [comment]
please solve this issue.

**Comment by meganrogge** [comment]
not sure what you mean, please attach a gif
