### ISSUE TITLE
WinUI VSCode

### ISSUE THREAD

**Issue by ayushgun** [microsoft/vscode#130372]
Just a quick question, but with the new Windows 11 WinUI, will we possibly be seeing a VSCode version that uses WinUI? I know VSCode is electron-based, but even a UI design similar to the WinUI could make it seem significantly more consistent and aesthetically pleasing.

**Comment by lorisobi** [comment]
This sounds good. Hope it could be possible, even with keeping fitting design on macos and linux

**Comment by misolori** [comment]
Thanks for the feedback. Please see #115641 where we are tracking a similar request. Will be closing this one as a duplicate.
