### ISSUE TITLE
Hang in file dialog when trying to save untitled file

### ISSUE THREAD

**Issue by JWess** [Microsoft/vscode#13038]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 8.1

Steps to Reproduce:
1. Hit CTRL + N to create a new file.
2. Immediately hit CTRL + S to save the new file. The save dialog comes up as a white box and never unfreezes. VS Code is unresponsive, and force quit is necessary, which closes all instances of VS Code.

*This only happens sometimes. I have had it happen at least 10x over the past couple months. I haven't been able to put my foot on what causes it. I'm always in split screen. I always have several instances of VS Code open. I have no idea if those things affect it.

**Comment by bpasero** [comment]
Never heard this nor seen this but I suspect an upstream issue on your box with something in the file dialog that causes this. E.g. a mapped network drive that is very slow and takes time to load.

**Comment by JWess** [comment]
Thanks for the feedback. I don't have any mapped drives, but next time it happens, I will wait for 5 minutes and see if it is able to recover.

**Comment by bpasero** [comment]
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.
