### ISSUE TITLE
Middle click on a tab or closing it should not focus it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#130322]
Either a middle click on a tab of closing it via the `x` is a strong indicator that the user wants to close the tab. I think we should act more like a browser here and not open it beforehand as it's extra work laying loading the file, initializing/laying out the editor, etc.

![recording (58)](https://user-images.githubusercontent.com/2193314/128600681-e40797a7-a397-4aab-b47e-1af95be16bbe.gif)

**Comment by bpasero** [comment]
Maybe, not sure though. The reason the editor comes to the front is to help the user make that decision the dialog is asking for so that you can review the changes before in the end discarding all your changes. I find that more useful than having to pay the extra price of loading the editor.

**Comment by Tyriar** [comment]
Makes sense, let's close
