### ISSUE TITLE
Notebook renderers API is not really usable in its current form

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#130307]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59
- OS Version:Mac

Even though the API is table, there's no way to use this today as we have no idea what Notebook document the messages belong to.

Today the API is as follows:
```typescript
    /**
     * Message received from {@link NotebookRendererMessaging.onDidReceiveMessage}
     */
    export interface NotebookRendererMessage {
        /**
         * Editor that sent the message.
         */
        readonly editor: NotebookEditor;

        /**
         * Message sent from the webview.
         */
        readonly message: any;
    }
```

**However NotebookEditor has nothing in it in stable**
```typescript
export interface NotebookEditor {}
```

Hence the API isn't usable, even though its in stable.

**Comment by connor4312** [comment]
I think this is just a request to stabilize the NotebookEditor API? That's coming next month I think.

**Comment by connor4312** [comment]
I think this is just a request to stabilize the NotebookEditor API? That's coming next month I think.
