### ISSUE TITLE
There are some problems in use. Uninstalling the software and restarting the computer still can't be solved.

### ISSUE THREAD

**Issue by Tyxll** [microsoft/vscode#130348]
Issue Type: <b>Bug</b>

When the mouse leaves the software interface, some strange patterns will appear on the software interface.
![image](https://user-images.githubusercontent.com/86278896/128624420-66a16b98-8567-4601-9d3d-86490ea65a9f.png)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.55GB free)|
|Process Argv|--crash-reporter-id 2d5fee8a-b26d-42df-a3ff-d90838281335|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.59.2
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration as temporary workaround
