### ISSUE TITLE
VS Code becomes unresponsive on startup

### ISSUE THREAD

**Issue by lwblackledge** [microsoft/vscode#130414]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.59.0
- OS Version:  Windows 10 (64-bit), 1909 (OS Build 18363.1679)

Steps to Reproduce:

1. Attempt to start VS Code

Error Messages:
When running via `code --verbose` this error is seen in the logs:
`[main 2021-08-09T16:14:11.757Z] CodeWindow: detected unresponsive`

**Comment by subspacefield** [comment]
I also am experiencing this issue after upgrading. Windows 20H2 (OS Build 19042 1083).  Log messages:

C:\Program Files\Microsoft VS Code\bin>code --verbose --log debug --disable-gpu

[main 2021-08-09T16:43:23.650Z] Starting VS Code
[main 2021-08-09T16:43:23.652Z] from: c:\Program Files\Microsoft VS Code\resources\app
[main 2021-08-09T16:43:23.652Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  log: 'debug',
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': true,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'a63e70fc-34d9-4bd3-b7e2-cd788993eafd',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\jshuler\\AppData\\Roaming\\Code\\logs\\20210809T114323'
}
[main 2021-08-09T16:43:23.654Z] Resolving machine identifier...
[main 2021-08-09T16:43:23.655Z] Resolved machine identifier: fdac09dcbfdfcda0218b57ed64ef646ebce18a10ecf69621cf605822bb691bcb
[main 2021-08-09T16:43:23.655Z] Main->SharedProcess#connect
[main 2021-08-09T16:43:23.679Z] StorageMainService: creating global storage
[main 2021-08-09T16:43:23.679Z] lifecycle (main): phase changed (value: 2)
[main 2021-08-09T16:43:23.680Z] windowsManager#open
[main 2021-08-09T16:43:23.680Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\jshuler\\AppData\\Roaming\\Code\\Backups\\1628522663144',
    remoteAuthority: undefined
  }
]
[main 2021-08-09T16:43:23.682Z] IPC Object URL: Registered new channel vscode:a5c2ba33-5df2-4393-98d7-e1211034fa05.
[main 2021-08-09T16:43:23.682Z] window#validateWindowState: validating window state on 3 display(s) { mode: 0, x: 183, y: 80, width: 1688, height: 887 }
[main 2021-08-09T16:43:23.682Z] window#validateWindowState: multi-monitor working area { x: 0, y: 0, width: 1920, height: 1040 }
[main 2021-08-09T16:43:23.683Z] window#ctor: using window state { mode: 0, x: 183, y: 80, width: 1688, height: 887 }
[main 2021-08-09T16:43:23.683Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-09T16:43:23.744Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-08-09T16:43:23.744Z] lifecycle (main): phase changed (value: 3)
[main 2021-08-09T16:43:23.754Z] update#setState idle
[main 2021-08-09T16:43:23.754Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:43:23.852Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:43:23.855Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:43:23.978Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:43:23.980Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:43:24.191Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:43:24.235Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:43:38.898Z] CodeWindow: detected unresponsive
[main 2021-08-09T16:43:53.767Z] update#checkForUpdates, state =  idle
[main 2021-08-09T16:43:53.767Z] update#setState checking for updates
[main 2021-08-09T16:43:53.768Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/379476f0e13988d90fab105c5c19e7abc8b1dea8
[main 2021-08-09T16:43:53.768Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:44:03.465Z] update#setState idle
^CTerminate batch job (Y/N)? y

C:\Program Files\Microsoft VS Code\bin>code --verbose --log debug --disable-extensions --disable-gpu

[main 2021-08-09T16:45:42.591Z] Sending some foreground love to the running instance: 1956
[main 2021-08-09T16:45:42.601Z] Sending env to running instance...
[main 2021-08-09T16:45:42.664Z] Sent env to running instance. Terminating...
[main 2021-08-09T16:45:42.664Z] Lifecycle#kill()

C:\Program Files\Microsoft VS Code\bin>code --verbose --log debug --disable-extensions --disable-gpu

[main 2021-08-09T16:45:57.424Z] Starting VS Code
[main 2021-08-09T16:45:57.426Z] from: c:\Program Files\Microsoft VS Code\resources\app
[main 2021-08-09T16:45:57.426Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  log: 'debug',
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': true,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'a63e70fc-34d9-4bd3-b7e2-cd788993eafd',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\jshuler\\AppData\\Roaming\\Code\\logs\\20210809T114557'
}
[main 2021-08-09T16:45:57.428Z] Resolving machine identifier...
[main 2021-08-09T16:45:57.428Z] Resolved machine identifier: fdac09dcbfdfcda0218b57ed64ef646ebce18a10ecf69621cf605822bb691bcb
[main 2021-08-09T16:45:57.429Z] Main->SharedProcess#connect
[main 2021-08-09T16:45:57.485Z] StorageMainService: creating global storage
[main 2021-08-09T16:45:57.485Z] lifecycle (main): phase changed (value: 2)
[main 2021-08-09T16:45:57.486Z] windowsManager#open
[main 2021-08-09T16:45:57.487Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\jshuler\\AppData\\Roaming\\Code\\Backups\\1628522663144',
    remoteAuthority: undefined
  }
]
[main 2021-08-09T16:45:57.489Z] IPC Object URL: Registered new channel vscode:9904a38f-2afe-45c0-ae96-c2c0b738cab4.
[main 2021-08-09T16:45:57.489Z] window#validateWindowState: validating window state on 3 display(s) { mode: 0, x: 183, y: 80, width: 1688, height: 887 }
[main 2021-08-09T16:45:57.489Z] window#validateWindowState: multi-monitor working area { x: 0, y: 0, width: 1920, height: 1040 }
[main 2021-08-09T16:45:57.490Z] window#ctor: using window state { mode: 0, x: 183, y: 80, width: 1688, height: 887 }
[main 2021-08-09T16:45:57.490Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-09T16:45:57.562Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-08-09T16:45:57.562Z] lifecycle (main): phase changed (value: 3)
[main 2021-08-09T16:45:57.571Z] update#setState idle
[main 2021-08-09T16:45:57.571Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:45:57.671Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:45:57.673Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:45:57.784Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:45:57.787Z] [File Watcher (node.js)] [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:45:57.978Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:45:57.995Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\jshuler\AppData\Roaming\Code\User\globalStorage
[main 2021-08-09T16:46:12.734Z] CodeWindow: detected unresponsive
[main 2021-08-09T16:46:27.577Z] update#checkForUpdates, state =  idle
[main 2021-08-09T16:46:27.577Z] update#setState checking for updates
[main 2021-08-09T16:46:27.577Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/379476f0e13988d90fab105c5c19e7abc8b1dea8
[main 2021-08-09T16:46:27.578Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-09T16:46:37.210Z] update#setState idle

**Comment by lwblackledge** [comment]
I'm still experienceing this issue, and cannot currently use VS Code. Please let me know if there is anything else I can provide to help identify the cause.

**Comment by lwblackledge** [comment]
I switched to the latest Insiders build (details below), and did not have this issue, so it seems to be specific to `1.59.0`:

**VS Code Insiders details**
Version: 1.60.0-insider (user setup)
Commit: f0913d7718bbc4a805cd3a051335b4df60ca5d77
Date: 2021-08-17T05:15:18.727Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by michaelyi1983** [comment]
I meet this problem with v1.59.0 too. I download Insiders build for v1.60.0, it works.

The error logs for v1.59.0 as below.
 
C:\Program Files\Microsoft VS Code>code --verbose --log debug --disable-gpu

C:\Program Files\Microsoft VS Code>
[main 2021-08-18T10:13:46.616Z] Starting VS Code
[main 2021-08-18T10:13:46.617Z] from: c:\Program Files\Microsoft VS Code\resources\app
[main 2021-08-18T10:13:46.618Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  log: 'debug',
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': true,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'bb19d5b0-139d-4694-9664-13c5f02f0b1d',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\yigc\\AppData\\Roaming\\Code\\logs\\20210818T181346'
}
[main 2021-08-18T10:13:46.620Z] Deleting Chrome cached data path: c:\Users\yigc\AppData\Roaming\Code\Code Cache
[main 2021-08-18T10:13:46.623Z] Resolving machine identifier...
[main 2021-08-18T10:13:46.623Z] Resolved machine identifier: 9b985d50a377d0ad44d3e1c90fffa03daeded6a2c81a634eeeedeb03b579ecad
[main 2021-08-18T10:13:46.628Z] Main->SharedProcess#connect
[main 2021-08-18T10:13:46.640Z] StorageMainService: creating global storage
[main 2021-08-18T10:13:46.640Z] lifecycle (main): phase changed (value: 2)
[main 2021-08-18T10:13:46.641Z] windowsManager#open
[main 2021-08-18T10:13:46.641Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\yigc\\AppData\\Roaming\\Code\\Backups\\1629280905269',
    remoteAuthority: undefined
  }
]
[main 2021-08-18T10:13:46.642Z] IPC Object URL: Registered new channel vscode:f3f708ac-86fc-4f59-87ee-b081f3ebeaf6.
[main 2021-08-18T10:13:46.644Z] window#validateWindowState: validating window state on 3 display(s) { mode: 1, x: 284, y: 76, width: 1032, height: 776 }
[main 2021-08-18T10:13:46.646Z] window#validateWindowState: multi-monitor working area { x: 0, y: 0, width: 1536, height: 824 }
[main 2021-08-18T10:13:46.646Z] window#ctor: using window state { mode: 1, x: 284, y: 76, width: 1032, height: 776 }
[main 2021-08-18T10:13:46.646Z] window#ctor: vscode-file:// protocol is explicitly disabled
[main 2021-08-18T10:13:46.697Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-08-18T10:13:46.698Z] lifecycle (main): phase changed (value: 3)
[main 2021-08-18T10:13:46.703Z] update#setState idle
[main 2021-08-18T10:13:46.703Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-18T10:14:01.824Z] CodeWindow: detected unresponsive
[main 2021-08-18T10:14:16.718Z] update#checkForUpdates, state =  idle
[main 2021-08-18T10:14:16.719Z] update#setState checking for updates
[main 2021-08-18T10:14:16.722Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/507ce72a4466fbb27b715c3722558bb15afa9f48
[main 2021-08-18T10:14:16.724Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-18T10:15:47.741Z] IPC Object URL: Removed channel vscode:f3f708ac-86fc-4f59-87ee-b081f3ebeaf6.
[main 2021-08-18T10:15:47.741Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-08-18T10:15:47.749Z] Lifecycle#onWillShutdown.fire()
[main 2021-08-18T10:15:47.752Z] Lifecycle#app.on(window-all-closed)
[main 2021-08-18T10:15:47.752Z] Lifecycle#app.on(before-quit)
[main 2021-08-18T10:15:47.753Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-08-18T10:15:47.753Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: 'C:\\Users\\yigc\\AppData\\Roaming\\Code\\Backups\\1629280905269',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 284,
      y: 76,
      width: 1032,
      height: 776
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-08-18T10:15:47.754Z] Lifecycle#app.on(will-quit)
[main 2021-08-18T10:15:47.760Z] StorageMainService: closed global storage

**Comment by lwblackledge** [comment]
I also reverted to `1.58.0` and turned off automatic updates - so it is working for now. I'll move to `1.60.0` when it is released.

**Comment by seanblonien** [comment]
Still seeing in `1.60.1`, so I wouldn't recommend updating yet

**Comment by zsong** [comment]
Use both --disable-gpu --disable-software-rasterizer

**Comment by lwblackledge** [comment]
> Use both `--disable-gpu` `--disable-software-rasterizer`

Thanks! That worked for me too on 1.63.2

**Comment by deepak1556** [comment]
Can you test our exploration builds which are based on a newer runtime and see if the unresponsiveness happens without the `--disable-gpu --disable-software-rasterizer` flags. Thanks!

[windows x64 user setup](https://az764295.vo.msecnd.net/exploration/8eab3dba050a3bd11dcdd33f6bca2fe807cf3f9c/VSCodeUserSetup-x64-1.64.0-exploration.exe)

**Comment by seanblonien** [comment]
@deepak1556 1.64 fixes it for me! 🥳

Tested on a non-elevated corporate laptop that usually doesn't let me run half my programs without some sort of trouble. I was using `--disable-gpu --disable-software-rasterizer` past few months, but it didn't seem to need it in 1.64

@lwblackledge does 1.64 fix it for you too?
