### ISSUE TITLE
Buttons in editor widgets do not show any hover feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130475]
![recording](https://user-images.githubusercontent.com/900690/128838832-08339c1c-f108-4be4-8ab6-692fb9f79e9e.gif)

//cc @rebornix

**Comment by bpasero** [comment]
Maybe this button needs manual tweaking though to align with the one we have in search view:

![image](https://user-images.githubusercontent.com/900690/130607104-301af45f-9dbd-4b20-90c8-730bfcfe1c09.png)

![image](https://user-images.githubusercontent.com/900690/130607116-e83b92f1-c274-49c8-af48-587a12bf4c12.png)

**Comment by misolori** [comment]
Removed the border radius for the expanding chevron:

<img width="139" alt="CleanShot 2021-09-13 at 15 40 09@2x" src="https://user-images.githubusercontent.com/35271042/133165580-c388464d-8b0c-489e-b01b-99a5cb545fa9.png">
