### ISSUE TITLE
Inlay hints should be requested on all open files (similarly to diagnostics)

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#130430]
Issue Type: <b>Bug</b>

Today, VS Code seems to request inlay hints for the most-recently edited (or currently focused?) file; however, inlay hints can be affected by edits in other files. That means you can end up in situations where 2 files can be edited side-by-side where one ends up with stale inlay hints.

![image](https://user-images.githubusercontent.com/972891/128756601-0396f964-262b-479f-b1c1-585f336f70eb.png)

VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by mjbvz** [comment]
@jrieken To support this on the TypeScript side, I believe we either need:

- Make VS Code call `provideInlayHints` for all visible files when one file changes

- Have `onDidChangeInlayHints` take a uri so that TypeScript can fire this event for all visible files

**Comment by DanielRosenwasser** [comment]
I should mention that semantic diagnostics probably has the same issue.

**Comment by jrieken** [comment]
> Have onDidChangeInlayHints take a uri so that TypeScript can fire this event for all visible files

Yeah, I believe that's the most reasonable thing to do. Unsure about requesting inlay hint for all files tho

**Comment by jrieken** [comment]
There already is [`InlayHintsProvider#onDidChangeInlayHints`](https://github.com/microsoft/vscode/blob/927a28da01cec8a71261dfedf87ba48664108a1b/src/vs/vscode.proposed.d.ts#L1844-L1844). No plans to refresh all editors when the any model changes

**Comment by mjbvz** [comment]
@jrieken Can this event take an optional resource uri? Otherwise I have to add extra code to avoid calculating the hints twice

If I have file A and file B open for example:

1. File A changes -> hints requested by VS Code
2. TS extension fires onDidChangeInlayHints because multiple files are visible
3. VS Code requests hints for all visible files 
4. But we only really want to compute the hints from `B` here

**Comment by mjbvz** [comment]
Reopening to track fix for JS/TS specifically

**Comment by jrieken** [comment]
Yeah, adding an optional uri event type should be easy.

**Comment by jrieken** [comment]
fixed with https://github.com/microsoft/vscode/commit/5dcc08052cc7d7af62e831f5226271bad39ccc44
