### ISSUE TITLE
Don't suggest snippets in void places

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#1304]
See attached screen shot, I have many snippets defined and they are the only entries that show up when I auto complete inside an object literal, which is weird imho:

<img width="512" alt="screen shot 2015-12-14 at 19 29 35" src="https://cloud.githubusercontent.com/assets/900690/11789872/1c19940e-a299-11e5-9ce8-d36a5289feb3.png">

**Comment by asvetliakov** [comment]
Is it possible to introduce setting to disable default snippets completely until this fixed? I'm rarely using default snippets for example and i'd choose to not have them instead messing with completion list.

**Comment by evanw** [comment]
Snippets are constantly getting in my way. I never use them and I would love the ability to disable them except I think it's currently impossible. A preference to disable the snippets feature would be amazing.

**Comment by mrmlnc** [comment]
@evanw,

In July: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/July_2016.md#snippets-and-suggestions

**Comment by evanw** [comment]
That's awesome, thanks for the pointer! It looks like v1.4.0 isn't available yet (the app is at v1.3.1 and says no updates are currently available).

**Comment by mrmlnc** [comment]
This version is available in [insider version](https://code.visualstudio.com/insiders). The new version will be available next week (1-10).

**Comment by mjbvz** [comment]
@alexandrudima I don't think this is TypeScript specific. Is there any way to excluded language snippets from specific scopes, similar to how we can defined `"notIn": ["string", "comment"] ` for `autoClosingPairs`?

**Comment by amackintosh** [comment]
+1 I'd like to be able to remove snippets. I created one called "log" to mimic the Atom snippet, so that when i type log+tab, it puts in "console.log()", but the default snippet is some HTML <log> </log> one that is no use to me.

It would be amazing if I could simply turn specific ones off. I am finding it extremely hard to research this aspect of snippets.

**Comment by DavidBabel** [comment]
note that this includes imports too, if cursor is here : 
`import { | } from 'something';`

Intellisense should provide imports items before any snippets

**Comment by Shmolin** [comment]
![image](https://user-images.githubusercontent.com/25280576/51806327-a6b3e600-2270-11e9-8103-5cf436337e62.png)

Please allow us options to remove these keywords. As a beginner of Python, I find it takes longer to find from the list the code I was looking for. C# in VS was perfect however.

**Comment by pouledodue** [comment]
is it possible to insert snippet when the cursor is inside a string?
would be great
