### ISSUE TITLE
Unable to debug extensions

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#130437]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Create a "hello world" extension. (https://code.visualstudio.com/api/get-started/your-first-extension)
2. F5 the extension and try setting a breakpoint.

The breakpoint shows as "Unbound" and it never hits. Nevertheless, I can update the extension code and I see the changes being reflected in the extension development host window.

Adding debug adapter logs:
[vscode-debugadapter-089e0c6c.json.gz](https://github.com/microsoft/vscode/files/6957325/vscode-debugadapter-089e0c6c.json.gz)

**Comment by roblourens** [comment]
@weinand, I was debugging this and @connor4312 said that the log shows that the debug adapter sent the launch request to vscode, and we see the extension development host window launched, but vscode never sends an attach request with the port, so the DA is not actually attached.

Looking at the code I didn't quite understand the flow. If needed I can debug this with @osortega if you tell me where to look.

**Comment by weinand** [comment]
@osortega Did you active the extension by running the "hello" command?

**Comment by osortega** [comment]
@weinand Yes, I see everything being executed fine. It just never attaches to the debugger.

**Comment by osortega** [comment]
I just terminated all VS Code processes, closed some locally forwarded ports and restarted my laptop.
Seems to be working fine now for some reason. 

Will close the issue and re-open if I see it happening again.

**Comment by osortega** [comment]
Reopening the issue since it's happening to me again. Tried doing the same thing I did before to make it work but it didn't help this time.

@weinand I'm happy to send any logs or debug if necessary.

**Comment by osortega** [comment]
![debug3](https://user-images.githubusercontent.com/48293249/129116199-37a269f9-241f-4483-8f94-7bebbc2e9082.gif)

**Comment by weinand** [comment]
can you reproduce when disabling all extensions? (lauching VS Code with --disable-extensions)

**Comment by osortega** [comment]
Yes, looks like it is still happening
![debug4](https://user-images.githubusercontent.com/48293249/129116817-32476b02-cc42-4edf-8947-5c67a00cce8f.gif)

**Comment by weinand** [comment]
no, I meant disabling extensions in the outer VS Code.

**Comment by osortega** [comment]
I tried that but it didn't work. Heres's the gif:

![debug6](https://user-images.githubusercontent.com/48293249/129257388-204aa226-e67b-4db5-a071-62bd3a58dac0.gif)
