### ISSUE TITLE
Native title bar appears in full screen when `"window.nativeFullScreen": false`

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode#130401]
Issue Type: <b>Bug</b>

## Steps to reproduce:
1. Set `"window.nativeFullScreen": false` in settings
2. Restart VSCode
3. Make window full screen

## Expected behaviour
Native title bar disappears, the way that it does when using native full screen mode, and the way that it did in VSCode 1.58 in non-native full screen mode

![image](https://user-images.githubusercontent.com/755842/128693197-ca4dd94e-ae36-457c-bff0-9ef8abf6ed86.png)

## Actual behaviour
Native title bar is still there

![image](https://user-images.githubusercontent.com/755842/128693192-5bae9872-ded8-4339-8cf4-e549d76040de.png)

## Notes
This issue only appeared in the latest update of VSCode (1.59).  I have verified that the title bar disappears in full screen in VSCode 1.58

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 10, 10|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|-psn_0_1298749 --crash-reporter-id 99d35f96-61a9-461b-a60d-f915d32f3eee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.1.0
vscode-neovim|asv|0.0.82
All-Autocomplete|Ati|0.0.23
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.4.0
regex|chr|0.4.0
vscode-eslint|dba|2.1.23
chmod|dle|1.1.1
githistory|don|0.6.18
viml|dun|0.1.7
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
remotehub|Git|0.13.0
vscode-pull-request-github|Git|0.29.0
mdmath|goe|2.7.4
rest-client|hum|0.24.5
jq-syntax-highlighting|jq-|0.0.2
bash-ide-vscode|mad|1.11.0
syntax-project-pbxproj|mar|0.1.3
rainbow-csv|mec|1.9.1
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.30.0
goto-next-previous-member|mis|0.0.5
vscode-edits-history|mis|0.1.6
vscode-talonscript|mro|0.3.2
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vsliveshare|ms-|1.0.4673
vscode-react-native|msj|1.6.0
autodocstring|njp|0.5.4
command-server|pok|0.6.0
cursorless|pok|0.20.1
parse-tree|pok|0.8.0
LiveServer|rit|5.6.1
format-code-action|roh|0.1.0
multi-command|ryu|1.5.1
vscode-fileutils|sle|3.4.5
code-spell-checker|str|1.10.2
vscode-open-in-github|sys|1.15.0
tabnine-vscode|Tab|3.4.22
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by sbatten** [comment]
@deepak1556 since I was out for the last milestone, is there anything that would have changed here?

**Comment by bpasero** [comment]
Fyi I believe this did not change, but would be good to verify. I think there have been issues with custom title and custom fullscreen that would lead to custom title being disabled:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/windows/common/windows.ts#L146-L146

**Comment by pokey** [comment]
Ok I checked and the behaviour is definitely different in 1.58, however not completely.  In both 1.58 and 1.59, having `"window.nativeFullScreen": false` does cause the native window title to be used when not in full screen.  However, in 1.58, that native window title disappears in full screen, but it doesn't disappear in full screen in 1.59, even with all extensions disabled.  So I guess the primary issue here is the fact that the title bar appears in full screen when using `"window.nativeFullScreen": false`.  I'll update issue title / description

**Comment by pokey** [comment]
Got it—thanks. Shall I file this one against Electron then?

**Comment by bpasero** [comment]
Let's wait for @deepak1556 to comment first.

**Comment by deepak1556** [comment]
Yeah this is an electron regression, side-effect of https://github.com/electron/electron/pull/27489. Will follow-up in upstream.

**Comment by deepak1556** [comment]
Upstream issue: https://github.com/electron/electron/issues/30536

**Comment by deepak1556** [comment]
\closedWith https://github.com/microsoft/vscode/commit/70f3c712be1f8459e087648e33696cfb302f32af

**Comment by o8e** [comment]
It's back 😻
