### ISSUE TITLE
Dark+ theme needs some improvements for 'variable.language' scope

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13044]
- VSCode Version:
- OS Version:

Used latest vscode extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

This can also be found when using extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

```this``` and ```super``` are scoped as ```variable.language``` but they aren't colorized as keyword

From Microsoft/TypeScript-TmLanguage#273

From @octref 
Previously:

![image](https://cloud.githubusercontent.com/assets/4033249/18942299/d6954cda-85cc-11e6-86e8-1ef158fdb1bd.png)

Now:

![image](https://cloud.githubusercontent.com/assets/4033249/18942303/de5d287a-85cc-11e6-8187-521a124190c4.png)

**Comment by aeschli** [comment]
Fixed in head
