### ISSUE TITLE
Language mode not persisted correctly

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#130436]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows 10, 19043.1110

Steps to Reproduce:

1. Open a folder, and then open a file in it with identifiable language mode, such as json.
2. Set language mode in the status bar, or by `vscode.languages.setTextDocumentLanguage` to some other language mode.
3. Either close this document or switch to another document.
4. Reopen this document or switch back to it.
5. Notice that the language mode is not persisted.

However, in step (3), if we close the vs code window instead of the file, the language mode will be persisted when reopening vscode.

**Comment by TylerLeonhardt** [comment]
You're talking about an actual file and not an untitled file so I'm removing myself from assignees. Let's see what @aeschli has to say.

**Comment by bpasero** [comment]
Language mode will not persist when document closes and reopens. So this seems to work as designed.

**Comment by xisui-MSFT** [comment]
@bpasero But it's persisted when VS Code closes and reopens, and then persisted forever? This doesn't seem to make sense...

**Comment by bpasero** [comment]
@xisui-MSFT let me try to explain: when a file is opened as an editor (and appears in the editor area as a "tab"), we try to persist any view state and configuration you apply to it, considering that this file is now in a "working state". As such, language mode persists. But when you close the file and open it again, we open it "fresh" without the state that was previously applied.

**Comment by xisui-MSFT** [comment]
Thanks for the explanation.
