### ISSUE TITLE
debug's "WATCH" view is missing

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#130490]
In today's Insiders, debug's "WATCH" view is missing and it cannot even be enabled from the context menu:

<img width="389" alt="2021-08-10_11-30-50" src="https://user-images.githubusercontent.com/1898161/128871124-487e9836-207f-43ea-b8e6-d7f3d451642e.png">

This problem reproduces with extensions disabled.
It does not reproduce when running VS Code from a different user directory ("--user-data-dir").

**Comment by gjsjohnmurray** [comment]
@weinand has the view perhaps got moved to the Panel?

**Comment by weinand** [comment]
@gjsjohnmurray Indeed, that was the issue. But I'm not aware that I did this...

**Comment by gjsjohnmurray** [comment]
@weinand glad it was a simple fix, but worrying that your workbench layout apparently changed itself in the first place. I recently noticed a similar quirk in my 1.59, where the Source Control Repositories view had migrated from the SCM view container to become a standalone item on the activity bar. I initially assumed it must've been something I did and forgot about, but now I'm not so sure.
