### ISSUE TITLE
Unpublish test extensions

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13040]
I can imagine someone searching for extensions related to testing, and this doesn't look that great... I think we should unpublish these when we're done with them or they'll just pile up.

![image](https://cloud.githubusercontent.com/assets/323878/18971394/beb4dd10-8649-11e6-8890-8f2a24952888.png)

**Comment by Tyriar** [comment]
Mine's done, added rob as yours still seems to be published.

![image](https://cloud.githubusercontent.com/assets/2193314/18973406/2cfd3bc0-8652-11e6-8fd8-0f72df298076.png)

**Comment by roblourens** [comment]
Well now mine is referenced in an active bug :P https://github.com/Microsoft/vscode/issues/12843

**Comment by mousetraps** [comment]
Good call, unpublished. Also I played around for a bit, and I found that prepending extension names with `99` pushes it to the end of search results, so worth keeping in mind for future clutter avoidance. If we want to get really fancy, we could also have a temporary extension sandbox (only available for an hr or something), which might encourage new users to try their hand at publishing extensions w/o fear of "doing something wrong"

**Comment by sandy081** [comment]
Done. Thanks.
