### ISSUE TITLE
editor.lineNumbers description needs to be updated for "on", "off", "relative"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13045]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 10

From Default Settings:
    // Controls visibility of line numbers
    "editor.lineNumbers": "on",

Should be something like:
"Controls display of line numbers. Possible values are "on", "off", and "relative". The "relative" options shows the line count relative to the current cursor position."

**Comment by isidorn** [comment]
This is also a good oportunity for a pr so assigning also Greg if he wants to fix this. Here is a code pointer
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L656
