### ISSUE TITLE
Inlay Hints: Cursor bounces back and forth when adding property to function call

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#130434]
Steps to Reproduce:

1. Create a function with a couple of arguments
2. Change it's signature to take an additional argument in the middle
3. Add that value to the function calls
4. 🐛 The cursor appears confused by the inlay hint

Here's a recording
![recording (1)](https://user-images.githubusercontent.com/4544166/128759376-a737901f-f603-4bdb-a4f9-c3668c89955f.gif)

**Comment by mjbvz** [comment]
@hediet I believe this is something that the core inlay hint implementation should handle but please let me know if you believe TS is providing invalid data

**Comment by hediet** [comment]
I have to get an better understanding what is happening here.

I think inlay hints referring to a point (rather than a range) are very tricky when they are inserted at the cursor position.

What should happen when the cursor is at column 10 and now an inlay hint appears (or is removed and readded) at column 10?

Pinging @jrieken as owner of the feature.

**Comment by lramos15** [comment]
This even happens when the cursor isn't on the same line. Say writing a comment above a function I see the inlay hints for Typescript re-render and bounce around a lot

**Comment by mjbvz** [comment]
@lramos15 Can you please test this again using the TS 4.4.1-insiders build of TypeScript that will be in the next VS Code insiders

**Comment by lramos15** [comment]
@mjbvz I'm not seeing the comments causing bouncing but the initial issue still exists

**Comment by jrieken** [comment]
This should be fixed by https://github.com/microsoft/vscode/issues/125995. We now do a better job of giving inlay hints a range to stick to and the back and forth bouncing. Shouldn't happen anymore. 

@lramos Please give this another try and let me know how this works

**Comment by jrieken** [comment]
This should be fixed by https://github.com/microsoft/vscode/issues/125995. We now do a better job of giving inlay hints a range to stick to and the back and forth bouncing. Shouldn't happen anymore. 

@lramos Please give this another try and let me know how this works

**Comment by lramos15** [comment]
Much improved.
