### ISSUE TITLE
function argument names shown

### ISSUE THREAD

**Issue by mmakrzem** [microsoft/vscode#130418]
I just updated to Version: 1.60.0-insider (user setup)
Commit: 1ee61f368ee0570feeb220605578a8768d99e762
Date: 2021-08-09T06:11:00.971Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Now in the IDE, when I call a function, there is some text rendered by VSC which displays the name of the argument (in grey) beside the value that I'm passing into a function.  

This new feature is really buggy especially when I copy and paste code.  The greyed out text renders over top of the actual code in the source file making it difficult to see anything.  

How do I turn off this new feature?

**Comment by hediet** [comment]
Can you post a screenshot?

@mattbierner are typescript inlay hints enabled by default?

**Comment by mmakrzem** [comment]
![disableThese](https://user-images.githubusercontent.com/1681264/128770290-33178759-fa2f-4249-9b69-fca25d5a35bf.png)

**Comment by mmakrzem** [comment]
Here is an example where the grey text renders overtop of my source code 
![badPlacement](https://user-images.githubusercontent.com/1681264/128771238-d606ed44-bbda-46ff-bb8d-161bd3603566.png)

**Comment by gjsjohnmurray** [comment]
> Can you post a screenshot?
> 
> @mattbierner are typescript inlay hints enabled by default?

pinging @mjbvz

**Comment by mjbvz** [comment]
Yes set `"typescript.inlayHints.parameterNames.enabled": "none"` to disable the inlay hints

Positioning issues are tracked upstream by https://github.com/microsoft/TypeScript/issues/45320
