### ISSUE TITLE
Build: setting search step fails for exploration build

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#130455]
Refs https://monacotools.visualstudio.com/Monaco/_build/results?buildId=130317&view=results

**Comment by bpasero** [comment]
Seems fine now?

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=151044&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=72416b58-e963-5988-c483-d93c4e3729ce

**Comment by deepak1556** [comment]
Yeah I have lost context on this, closing for now. Will reopen if we hit this when with main branch
