### ISSUE TITLE
Insiders-Version in Ubuntu - Clear Cache Files gives error

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#130494]
In my Ubuntu 20.04 this folder `~/.config/Code-Insiders/Service Worker/CacheStorage` has become 5+GB and hence wanted to clear the cache.

But when I do Clear Cache Files from Command Palette 

![image](https://user-images.githubusercontent.com/12703975/128887650-1ef9573f-e64c-4002-83fc-bf0405b2c0e5.png)

I get below error

![image](https://user-images.githubusercontent.com/12703975/128887209-b200f8e6-0132-4136-b69e-b4465280d35e.png)

I am using Ubuntu 20.04 and VSCode Version Details as below

```
Version: 1.60.0-insider
Commit: 71b299184f7908491345aec5e231599c3ae8753b
Date: 2021-08-10T05:15:05.568Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-25-generic
```

And given my issue of 5GB+ size of `Service Worker/CacheStorage` folder - can I delete the contents of this folder `~/.config/Code-Insiders/Service Worker/CacheStorage` manually without affecting the proper functioning of code-insiders.

**Comment by rzhao271** [comment]
The command in the error dialog is `r.helpPanel.clearCache`. Is that from an extension?
I don't see that command on my Windows install.

**Comment by rohan-paul** [comment]
Yes, that indeed seems to be the case (i.e. it's from some extension).

I just ran `code-insiders --disable-extensions` and I don't see that option in the command palette.

**Comment by rzhao271** [comment]
The command is contributed by the R extension.
https://github.com/REditorSupport/vscode-R/blob/master/package.json#L1045
