### ISSUE TITLE
IntelliSense shows error for past code version

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#130459]
Issue Type: <b>Bug</b>

STR: I have been typing out "string" for a definition.

AR: After I finished, VS Code underlines "str" and tells me that that it cannot it. I had to delete the last character and re-type it so it catches up.
ER: Don't lag behind my typing input and show errors for outdated code

https://user-images.githubusercontent.com/8599/128807918-fa11d5d6-31c2-42be-b57f-2e9576243cfa.mov

I could reproduce this in the same file/line repeatedly. I have to type the `g` slowly when fixing, otherwise it complains about `strin`.

VS Code version: Code - Insiders 1.60.0-insider (1ee61f368ee0570feeb220605578a8768d99e762, 2021-08-09T05:59:19.046Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (18.78GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-github-actions|csc|0.20.3
vscode-eslint|dba|2.1.23
kusto|don|0.3.5
typescript-notebook|don|1.4.0
gitlens-insiders|eam|2021.7.1905
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
codespaces|Git|0.11.3
copilot|Git|1.3.2283
remotehub-insiders|Git|2021.8.91328
vscode-pull-request-github|Git|0.29.0
restore-git-branch-tabs|gko|0.4.1
gzipdecompressor|Hyu|1.2.0
vscode-styled-components|jpo|1.6.6
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.15.0
vscode-edge-devtools|ms-|1.2.1
python|ms-|2021.9.1106798209-dev
vscode-pylance|ms-|2021.8.1-pre.1
jupyter|ms-|2021.8.2022228455
remote-containers|ms-|0.191.0
azure-account|ms-|0.9.8
cpptools|ms-|1.5.1
live-server|ms-|0.2.7
debugger-for-edge|msj|1.0.15
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.17.0
smart-css-autocomplete|sai|1.4.2
msft-todo-unofficial|tyl|0.0.14
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30349639
dockerwalkthrucf:30348714

```

</details>

**Comment by digitarald** [comment]
Maybe related, I also see issues that highlight the wrong part of the code:

![image](https://user-images.githubusercontent.com/8599/129387778-596c4715-734b-41dc-b66d-b0c016116c4b.png)

**Comment by jrieken** [comment]
what language and what extension is this?

**Comment by digitarald** [comment]
@jrieken the first screenshot is a _TypeScript React_ file, the latter is _TypeScript_.

@mjbvz pinged me to re-test in latest Insiders and I can't reproduce the original issue anymore. Closing for now, until it happens again.
