### ISSUE TITLE
can't connect with mysql

### ISSUE THREAD

**Issue by Iceee95** [microsoft/vscode#130477]
command ' mysql.addConnection ' not found
when I click "mysql", no reply

**Comment by rzhao271** [comment]
Can you make sure the extension is enabled?
Also, can you try running the `workbench.action.restartExtensionHost` command?

**Comment by Iceee95** [comment]
Yes, I can sure the extension is enabled. I have downloaded "MySQL" and "MySQL Syntax" extension.
Also, I can't run the workbench.action.restartExtensionHost command successfully. When I run the command"MySQL：Add Connection", it will show the command 'mysql.addConnection' not found. Therefore, I can't connect with my MySQL.

**Comment by Iceee95** [comment]
Yes, I can sure the extension is enabled. I have downloaded "MySQL" and "MySQL Syntax" extension.
Also, I can't run the workbench.action.restartExtensionHost command successfully. When I run the command"MySQL：Add Connection", it will show the command 'mysql.addConnection' not found. Therefore, I can't connect with my MySQL.

**Comment by rzhao271** [comment]
Upstream issue https://github.com/formulahendry/vscode-mysql/issues/174
