### ISSUE TITLE
Files Opening Behind Other Applications

### ISSUE THREAD

**Issue by jtmontana** [Microsoft/vscode#13042]
- VSCode Version: 1.5.3
- OS Version: WIndows 10

Steps to Reproduce:

1. When using "Open with Code" from right click dialog in Windows Explorer, VS Code opens up the file behind all other open applications. This occurs if VS Code already has other open windows.

**Comment by joaomoreno** [comment]
@bpasero don't we `focus`?

**Comment by joaomoreno** [comment]
@bpasero We might want to do `app.focus()` for any situation the launch service is called with `start`.

fc21ef35bbd6eff937e27702e67b704cd25fd79e

**Comment by bpasero** [comment]
Electron bug: https://github.com/Microsoft/vscode/issues/929

**Comment by bpasero** [comment]
@joaomoreno I did not know this method exists but I am trying out now if it solves anything. I doubt it. Bottom line is that Windows is picky about allowing a window to grab focus. This is due to the multi process architecture of Electron.
