### ISSUE TITLE
Split View Bug

### ISSUE THREAD

**Issue by sonalys** [microsoft/vscode#130421]
Issue Type: <b>Bug</b>

Open 2 files into split view, in which the first view defines a structure, and the second view references the structure
Now CTRL+Click on the reference on the second view, instead of focusing the first view where your code is located, it will duplicate the first view on the second view

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.91GB (8.55GB free)|
|Process Argv|--crash-reporter-id c4a35d11-5242-469a-84c2-8549ec43570d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4000)|
|Memory (System)|7.77GB (1.80GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.8
remotehub|Git|0.13.0
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
codesnap|adp|1.3.4
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
go|gol|0.26.0
vscode-docker|ms-|1.15.0
rust|rus|0.7.8
vscode-scss-formatter|sib|2.2.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by IllusionMH** [comment]
Isn't this behavior controlled by `workbench.editor.revealIfOpen` setting?

Description:
> Controls whether an editor is revealed in any of the visible groups if opened. If disabled, an editor will prefer to open in the currently active editor group. If enabled, an already opened editor will be revealed instead of opened again in the currently active editor group. Note that there are some cases where this setting is ignored, e.g. when forcing an editor to open in a specific group or to the side of the currently active group.

I think setting `"workbench.editor.revealIfOpen": true` would focus editor in other group
