### ISSUE TITLE
update imports after move files

### ISSUE THREAD

**Issue by stupicode** [microsoft/vscode#130473]
update imports after move *.js files to new directory work fine for all *.js imports except CSS, SVG, ... .

- Programming Language: JavaScript React
- VS Code Version: 1.58.2
- OS Version: win 10.0.19042 x64

`Module not found: Can't resolve '../../styles/xxx.module.css'`
`Module not found: Can't resolve '../../assets/empty_xct9.svg'`

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
