### ISSUE TITLE
Closing Developer Tools closes entire application and skips unsaved changes prompt

### ISSUE THREAD

**Issue by JasonTheProgrammer** [Microsoft/vscode#13048]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open a new instance of VS Code.
2. Type something in the "Untitled-1" tab to set an "Unsaved Changes" state.
3. Help > Toggle Developer Tools.
4. Click the 'X' in the top-right of the Developer Tools view.
5. Help > Toggle Developer Tools.
6. Click the 'X' in the top-right of the Developer Tools view.
7. VS Code closes, unsaved changes prompt is not displayed, and unsaved changes are lost.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4430
