### ISSUE TITLE
Action buttons for cells should be visible even if code is not expanded

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#130432]
By "action buttons", I mean these three:
![image](https://user-images.githubusercontent.com/26465923/128752751-9e3a8d4f-0fd8-4691-be5c-99a098c21f5b.png)

They are only visible now if the cell's code is expanded (as shown).

Default view for a cell is with the code collapsed:

![image](https://user-images.githubusercontent.com/26465923/128752822-d7c88140-0c7e-4102-a17f-f8514e2ccab6.png)

I do not want to expand a potentially large code cell just to be able to clear that individual cell out of the output window. The action buttons should be visible all the time.

**Comment by rebornix** [comment]
It makes sense to show the cell toolbar even when the input is collapsed, cc @roblourens
