### ISSUE TITLE
Expand / collapse inconsistency

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#130433]
To expand a cell, a button exists:
![image](https://user-images.githubusercontent.com/26465923/128753109-fa338cce-2802-4c49-a953-a9cb1d44cbd4.png)

To collapse it, there is no button:
![image](https://user-images.githubusercontent.com/26465923/128753153-b0e3a9e0-e3a3-4f14-94ed-d2cf869c4bce.png)

You can double click in the area to the left of the code to collapse it, but this is not obvious. The expand button should simply change to a collapse button and remain at the top left corner of the cell.

**Comment by rebornix** [comment]
We don't show the collapse button anymore. When it's collapsed, we would show the run button when available.
