### ISSUE TITLE
Support variables in snippets

### ISSUE THREAD

**Issue by secato** [Microsoft/vscode#13047]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Is there anyway to get the filename from a snippet? Something like

```
"Test snippet": {
    "prefix": "test",
    "body": [
        "this is a test snippet",
        "file: $FILENAME"
    ],
    "description": "Test snippet"
}
```

**Comment by alexandrudima** [comment]
fyi @jrieken

**Comment by jrieken** [comment]
related or dupe of #3210

**Comment by jrieken** [comment]
Ideas/requests for variables:  *file name* and *time*

**Comment by jrieken** [comment]
Actually, also a dupe of #4956
