### ISSUE TITLE
build in extension doesnt work on WSL

### ISSUE THREAD

**Issue by pyokoNyan** [microsoft/vscode#130462]
Issue Type: <b>Bug</b>

latest stable version 1.59's build in extension such as Git and Emmet does not work with WSL2. It says I need to install the extension on my WSL2 system but I was not able to install the extension since it's a buildin extension. 

Had to reinstall to the older version (currently using) and everything works as normal (including Git and SCM)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (0.70GB free)|
|Process Argv|--crash-reporter-id 779c1568-172a-4ea4-8ea3-f5d36aef9204|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|7.77GB (0.65GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
sublime-keybindings|ms-|4.0.9
material-icon-theme|PKi|4.9.0
vscode-intelephense-client|bme|1.7.1
better-phpunit|cal|1.5.3
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
go|gol|0.27.0
vue|jcb|0.1.5
php-cs-fixer|jun|0.2.5
git-graph|mhu|1.30.0
vscode-docker|ms-|1.15.0
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.34.1
px-to-rem|sai|1.3.1
vue-vscode-snippets|sdr|2.2.1
sass-indented|syl|1.8.17
vscode-pets|ton|1.8.1
docker|vsc|1.0.0
yaml|vsc|1.0.0
quokka-vscode|Wal|1.0.390

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172

```

</details>

**Comment by sandy081** [comment]
@pyokoNyan Can you please show the screenshot of the state you explained -  It says I need to install the extension on my WSL2 system but I was not able to install the extension since it's a buildin extension.

**Comment by pyokoNyan** [comment]
@sandy081 sorry am not able to support you with a screenshot since i've resolved it by **reinstall it with older version and update it to the newest one**.  

I'll close this issue anyway :)
