### ISSUE TITLE
Change similar words feature

### ISSUE THREAD

**Issue by ibra** [microsoft/vscode#130446]
A change similar words feature for vscode would be really nice for when you press F2. Heres an example of it in action in Jetbrains Rider:
![UHXJ38PRXq](https://user-images.githubusercontent.com/61324615/128786286-b8548e47-f312-4cce-ac05-cea7e1dd814e.gif)

**Comment by ibra** [comment]
(Currently if you press F2 on an unrecognized word, this is what happens)
![image](https://user-images.githubusercontent.com/61324615/132285463-266af225-3d90-4f0c-a663-0908e0b27211.png)

**Comment by alexdima** [comment]
We have a built-in feature called Change All Occurrences (cmd+F2) which would go and change all textual occurrences of a word.

**Comment by ibra** [comment]
> We have a built-in feature called Change All Occurrences (cmd+F2) which would go and change all textual occurrences of a word.

ah, was not aware of that, still, it doesn't include the `change all local` thing because it doesn't go by scope, which imo is pretty important, and id also say that making something like that be a default when you press F2 would be way nicer relative to a `You cannot rename this element` tooltip.
