### ISSUE TITLE
Dark+ theme needs some improvements for type, cast and return type annotations

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13046]
- VSCode Version:
- OS Version:

Used latest vscode extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

This can also be found when using extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

Complete typeannotation is colorized as green in Dark+ theme probably because of ```meta.return.type, meta.type.annotation and meta.cast``` in 

```
                                {
                                                "name": "Types declaration and references",
                                                "scope": [
                                                                "meta.type.name",
                                                                "meta.return.type",
                                                                "meta.return-type",
                                                                "meta.cast",
                                                                "meta.type.annotation",
                                                                "support.type",
                                                                "entity.name.class",
                                                                "entity.name.type",
                                                                "storage.type.cs",
                                                                "storage.type.java"
                                                ],
                                                "settings": {
                                                                "foreground": "#4EC9B0"
                                                }
                                },

```
As reported by @octref in Microsoft/TypeScript-TmLanguage#273
Previously I could at least tell primitives from other constructs, and have a nested object displayed fine...

![image](https://cloud.githubusercontent.com/assets/4033249/18942421/cc71fbbc-85cd-11e6-8360-7941b205d591.png)

Now this looks terrible:

![image](https://cloud.githubusercontent.com/assets/4033249/18942434/e46284c6-85cd-11e6-9109-3600f6bdfd9e.png)

**Comment by sheetalkamat** [comment]
Also results in Microsoft/TypeScript-TmLanguage#173

**Comment by aeschli** [comment]
Fix in head

**Comment by sheetalkamat** [comment]
This seems to repro again. Eg. see Microsoft/TypeScript-TmLanguage#437

**Comment by aeschli** [comment]
@sheetalkamat Can you file a new issue? I'm not sure which issue is back. That's what I see in our latest with the dark default+ theme:
![image](https://cloud.githubusercontent.com/assets/6461412/25172970/e6150d74-24f2-11e7-828e-cb9bcfc33b77.png)
