### ISSUE TITLE
In product release notes lacks syntax highlighting

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13049]
- VSCode Version:1.6.0 insiders
- OS Version: Windows 10

![fencedcodeblock](https://cloud.githubusercontent.com/assets/12818376/18975093/8c7686f6-865c-11e6-976b-bff3cf5cb4f2.png)

**Comment by joaomoreno** [comment]
Moving to October because the colorisation is still not there. But at least the surrounding box and formatting is in.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by joaomoreno** [comment]
@alexandrudima This kinda got lost in the past. I call [`tokenizeToString`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/update/electron-browser/releaseNotesEditor.ts#L98) which tokenizes perfectly. But how can I get a hold of the generated CSS, I need to add it to the webview.

@mjbvz Markdown seems to use HLJS for this... why not `tokenizeToString`?

**Comment by joaomoreno** [comment]
@alexandrudima Just found [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textMate/electron-browser/TMSyntax.ts#L100), should I do something similar to it?

**Comment by mjbvz** [comment]
@joaomoreno The markdown extension uses hljs because it does not have access to the editor's tokenization APIs

**Comment by alexandrudima** [comment]
@joaomoreno [This](https://github.com/Microsoft/vscode/blob/df6a4213fbbe172432cdeb4086ac2a44dd6cc768/src/vs/editor/common/modes/supports/tokenization.ts#L386) is the method you want to call. It will generate a few CSS rules like:
```
.mtk1 { color: #333333; }
.mtk2 { color: #f5f5f5; }
.mtk3 { color: #aaaaaa; }
.mtk4 { color: #448c27; }
.mtk5 { color: #ab6526; }
.mtk6 { color: #777777; }
.mtk7 { color: #7a3e9d; }
.mtk8 { color: #660000; }
.mtk9 { color: #aa3731; }
.mtk10 { color: #4b83cd; }
.mtk11 { color: #91b3e0; }
.mtk12 { color: rgba(150, 0, 0, 0.08); }
.mtk13 { color: #000000; }
.mtk14 { color: #ffffdd; }
.mtk15 { color: #ffdddd; }
.mtk16 { color: #ddffdd; }
.mtk17 { color: #434343; }
.mtk18 { color: #ddddff; }
.mtk19 { color: #333333; }
.mtk20 { color: #f5f5f5; }
.mtk21 { color: #eaebe6; }
.mtk22 { color: #800080; }
.mtk23 { color: #cd3131; }
.mtk24 { color: #316bcd; }
.mtk25 { color: #cd9731; }
.mtki { font-style: italic; }
.mtkb { font-weight: bold; }
.mtku { text-decoration: underline; }
```

You can get the color map from `TokenizationRegistry.getColorMap()`.

**Comment by joaomoreno** [comment]
@alexandrudima You rule!

![image](https://user-images.githubusercontent.com/22350/33548884-03947768-d8e9-11e7-8390-f259b70e91f2.png)

cc @seanmcbreen
