### ISSUE TITLE
"show more" link for long output is not useful

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#130431]
Execute this code:

```
# %%
for i in range(1000):
    print(i)
```

You will see this:
![image](https://user-images.githubusercontent.com/26465923/128752310-4fa5e7d8-ca8a-4814-8d23-0cf45722f6b4.png)

Clicking on the link opens a JSON file where all the output is in one line:
![image](https://user-images.githubusercontent.com/26465923/128752369-7e2d01c0-9a8e-402b-adcb-647e5c882a16.png)

The link language is misleading and the result not really useful. I would rather see actual _raw_ output, i.e. what I would have seen had I executed it in a terminal.

**Comment by weinand** [comment]
what language is this? Python?

**Comment by shaperilio** [comment]
Yes, Python.

**Comment by joyceerhl** [comment]
@weinand sorry, this pertains to notebook output rendering and probably should not be assigned to you.

**Comment by rebornix** [comment]
Already have a fix in Insiders
