### ISSUE TITLE
[Test API] runTests should not require TestRunProfile 

### ISSUE THREAD

**Issue by TimWebb** [microsoft/vscode#130451]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows

The current proposed API for `vscode.tests.runTests` indicates in [TestRunRequest](https://github.com/microsoft/vscode/blob/main/src/vs/vscode.d.ts#L14046) documentation that a profile is optional, specifically 'though extensions may programmatically create requests not associated with any profile'. This is hopefully still valid statement as it allows extensions to access tests and invoke a test as needed. When running without a profile, the following error is returned:
`The request passed to 'vscode.test.runTests' must include a profile`

In the API as it is currently implemented, I don't see how an extension that accesses tests would then be able to invoke said test using the supplying TestController that registered the test in the first place.

**Comment by connor4312** [comment]
The "read" half of the test API is not completed. If/when it is, profiles will be exposed, since they are indeed required otherwise the editor can't know what `TestRunProvider.runHandler` to invoke for a given `runTests` request.
