### ISSUE TITLE
Yo code gives Object.fromEntries is not a function

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode#130488]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10 Pro, 21H1, 19043.1110

Steps to Reproduce:

1. Updated VSCode, yo and generator-code to the latest versions
2. I then do a 'yo code' and fill out the questions but I am then met with an error code

$ yo code
(node:31260) ExperimentalWarning: queueMicrotask() is experimental.
(node:31260) ExperimentalWarning: The fs.promises API is experimental

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__
 ´   `  |° ´ Y `

? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? HelloWorld
? What's the identifier of your extension? helloworld
? What's the description of your extension? 
? Initialize a git repository? Yes
? Bundle the source code with webpack? No       
? Which package manager to use? npm

Writing in C:\Users\<username>\temp\helloworld...
Error code 

Object.fromEntries is not a function

<username>@UnitName MINGW64 ~/temp
$

**Comment by IllusionMH** [comment]
What is your version of Node.js (`node -v`)?
Looks like you are using "old" version of Node.js as `Object.fromEntries` should be supported in v12+

**Comment by HenrikHolmIT** [comment]
Just updated node.js to 16.6.1 and that seems to have fixed it. 

Thanks.
