### ISSUE TITLE
Opened a folder via VS Code and it reopened with just basic UI colors but no content or buttons

### ISSUE THREAD

**Issue by dilijev** [microsoft/vscode#130442]
Issue Type: <b>Bug</b>

I was working on a set of files and then decided to open that directory as a workspace. When I did so, VS code reloaded and was basically blank except for basic UI colors. This does seem to repro for me.

![image](https://user-images.githubusercontent.com/494055/128779787-29110761-26ad-47cf-9f46-0ddd5937eb9f.png)

The UI I used to open the folder was:

![image](https://user-images.githubusercontent.com/494055/128779926-813a4597-1ed6-4f7d-8074-a284978e3f56.png)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (3.86GB free)|
|Process Argv|--crash-reporter-id 230f2605-802a-4b33-bdbf-e48a408baedd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
json-tools|eri|1.0.2
go|gol|0.26.0
go-nightly|gol|2021.8.423
kusto-syntax-highlighting|jos|1.0.1
rust-analyzer|mat|0.2.694
python|ms-|2021.8.1102490946
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1054968649
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
powershell|ms-|2021.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
dockerwalkthru:30344881
bridge0723cf:30346311

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by rebornix** [comment]
I'm seeing the same on latest Insiders. Often I open a new window or bring the system back from sleep, the VS Code window becomes blank for quite a few seconds.

**Comment by deepak1556** [comment]
Sounds like an effect of the occlusion tracker

@rebornix can you try launching with `--disable-features=CalculateNativeWinOcclusion`
