### ISSUE TITLE
Right-clicking doesn't work inside cells

### ISSUE THREAD

**Issue by appledora** [microsoft/vscode#130427]
## Environment data

-   VS Code version: c3f12631
-   Jupyter Extension version (available under the Extensions sidebar):  v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar):  v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Pop!_OS 21.04 x86_64 

-   Python and/or Anaconda version:  Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour
pop-up context meny on right-click

## Actual behaviour

Have tried clicking using both laptop's embedded mouse buttons and the wired mouse's right button. also tried the laptop's mouse button, after detaching the wired mouse. However, the keyboard's context menu button works (usually, it also acted up on and off sometimes). I am using a wireless keyboard from micropack.

**Comment by roblourens** [comment]
I wonder if it's something particular to your OS, which window manager do you use with `Pop!_OS`? Do context menus work elsewhere in vscode?

**Comment by appledora** [comment]
@roblourens  DE is `GNOME` and Window manager is `Mutter`

**Comment by roblourens** [comment]
So you right click and simply nothing happens? Do you see any errors in the devtools (Help > Toggle developer tools)
