### ISSUE TITLE
[Inlay hints] Enforce minimal text contrast

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130413]
<img src="https://user-images.githubusercontent.com/9638156/128735856-1275123a-2630-41ca-b08f-88030cf239bc.png" width="600">

![Screenshot (201)](https://user-images.githubusercontent.com/9638156/128736554-2decf746-ade4-4591-8309-c3b71c595e9c.png)

Theme to reproduce: https://marketplace.visualstudio.com/items?itemName=usernamehw.prism

---

Version: 1.60.0-insider (user setup)
Commit: 1ee61f368ee0570feeb220605578a8768d99e762
OS: Windows_NT x64 10.0.19043

**Comment by jrieken** [comment]
@misolori Can you help me find good colors for inlay hints? Currently, there is three kinds: inlay hints for types, for arguments/parameters, and others. 

Also related to https://github.com/microsoft/vscode/issues/133673

**Comment by misolori** [comment]
All of those colors are using the same default for `editorInlayHint` so you are good there. Looking at other light themes, most seem to look good there's just a few that don't look great. This is where those themes need to define the colors using those tokens as we won't be able to find colors that perfectly match every theme.

**Comment by jrieken** [comment]
Thanks @misolori
