### ISSUE TITLE
New up/down search input box keybindings are not symmetric

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13043]
- VSCode Version:1.6.0 insiders
- OS Version: Windows 10

The "up" keybinding is missing the "!searchInputBoxFocus" condition that is in "down".
Not sure if this is an oversight with commit https://github.com/Microsoft/vscode/commit/a9b91a0a8af40e4128d800a3ec740cb48a8d4f44 or by design.

Windows keybindings show:

{ "key": "down",                  "command": "search.focus.nextInputBox",
                                     "when": "inputBoxFocus && searchViewletVisible" },
{ "key": "up",                    "command": "search.focus.previousInputbox",
                                     "when": "inputBoxFocus && searchViewletVisible && !searchInputBoxFocus" },

**Comment by sandy081** [comment]
@gregvanl This is by design.

There is nothing (no input box) to navigate back from Search input. Hence command `search.focus.previousInputbox` has an additional condition.
