### ISSUE TITLE
New action search.focus.previousInputbox should be search.focus.previousInputBox

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13041]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 10

The new action should keep with camel casing used elsewhere for InputBox, ex. search.focus.nextInputBox

**Comment by isidorn** [comment]
@sandy081 assinging to you and september - this is just an ID change which we can not change once we release, so maybe just push a fix for it?

**Comment by sandy081** [comment]
@isidorn Sure
