### ISSUE TITLE
[trivial] settings>files: exclude  changing pattern as (blank) won't deletable

### ISSUE THREAD

**Issue by scharrin** [microsoft/vscode#130407]
Issue Type: <b>Bug</b>

settings > files: exclude 
click <add pattern>
type "ddddd"
enter
double click added "ddddd"
erase the pattern name and enter
click X icon on the right side of the erased pattern

expected : removed
but not and never even after restarting the VSC

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

**Comment by rzhao271** [comment]
There's an asymmetrical check going on. One if condition allows the empty entry to be created, but another one doesn't allow it to be removed 🤦
