### ISSUE TITLE
Python linter PyLint does not work with either Jedi and Pylance language servers in VS Code Insiders

### ISSUE THREAD

**Issue by sztal** [microsoft/vscode#130571]
Issue Type: <b>Bug</b>

I cannot get PyLint to work with both Jedi and PyLance language servers for Python on the Insiders build of VS Code.
Here are my linter-related settings:

```
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.pylintArgs": [
        "--disable invalid-name,bad-whitespace"
    ],
    "python.languageServer": "Pylance"
```

I also checked whether it matters if I install `pylint` via PIP or Conda but it seems not to matter (I am working within a Conda environment).

**EDIT.**

Also, the command (from the command palette) "Python: Run Linting" does absolutely nothing. Even no error message is displayed in the developer console.

============

VS Code version: Code - Insiders 1.60.0-insider (7c25c174726ab969db3f99058cdf24bcfae1cfbe, 2021-08-11T05:14:12.894Z)
OS version: Linux x64 5.11.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2580)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (4.35GB free)|
|Process Argv|--unity-launch --crash-reporter-id ea2cc0b8-cf43-49b3-a0ce-43755c989cd5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.60
latex-count|geo|1.2.1
latex-workshop|Jam|8.20.2
mongodb-vscode|mon|0.6.10
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.2025984474
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.5.1
rewrap|stk|1.14.0
rst-vscode|tht|3.0.1
vim|vsc|1.21.6
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by sztal** [comment]
No it is not. #129017 is just closed without any comment. Although it seems that the problem may be in the Python extensions. But nonetheless this knowledge by itself does not help me whatsoever, so I will be grateful for some more actionable hints as for how to deal with this problem.

**Comment by meganrogge** [comment]
Please report this in the extension's repo
