### ISSUE TITLE
Run search in extension host as an experiment

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#130532]
A sandboxed renderer process can't spawn the search process. We already run search in the EH in remote windows. We also still have a plan to enable extensions to contribute search providers which would run in the EH. We can add a setting to opt-in to running search in the EH all the time, and also enable it as an experiment to see if it causes any issues.

**Comment by roblourens** [comment]
(No verification needed, it's running this way in Insiders and won't in stable)

**Comment by bpasero** [comment]
@roblourens should this get a test plan item though?

**Comment by roblourens** [comment]
I guess verification-needed would be good. 

- Check that text/file search features work
- Open the process explorer, there should be no "searchProcess"

**Comment by bpasero** [comment]
@roblourens is it expected that more than one `rg` process run though? On the vscode workspace with any exclusions disabled I searched and tried to monitor the running `rg` processes with `htop`:

![image](https://user-images.githubusercontent.com/900690/130607619-add88c4e-988c-46e8-b48c-e789931d44a6.png)

**Comment by roblourens** [comment]
htop shows individual threads by default (even though they have different "PIDs") it may be one process. But there is one proc per workspace folder and per search instance.
