### ISSUE TITLE
Maintain cursor position when toggle Open Markdown Preview

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13053]
Open a markdown file. Have the cursor somewhere. Move it somewhere else with the arrow keys, then press cmd+shift+v to 'open markdown preview'. Press cmd+shift+v again. Now the cursor is in a different place. Similar to the bugs like #11727 I guess.

**Comment by bpasero** [comment]
Part of the problem is that imho the markdown extension executes the "Go back in history" command when toggling from the preview back to its source file which in some cases can go wrong badly if another file was opened meanwhile ( @kieferrm to confirm if that is still true).

**Comment by mjbvz** [comment]
We no longer enable the `open markdown preview` command when in the preview, so I don't think this scenario can be hit anymore
