### ISSUE TITLE
`File: Focus on Files Explorer` focuses on wrong file if performed after `Collpase Folders In Explorer`

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#130598]
**Steps to Reproduce:**
1. if your file explorer is closed, open it
1. focus an editor
1. command palette -> `Collpase Folders In Explorer` (aka `workbench.files.action.collapseExplorerFolders`)
1. command palette -> `File: Focus on Files Explorer` (aka `workbench.files.action.focusFilesExplorer`)

**Expected behavior:** 
Current file is un-collapsed into view, and also focused

**Actual behavior:**
Current file is un-collapsed into view, and highlighted too, but keyboard focus remains on some file in project root (use ↑↓ key to confirm).

Note: If your reproduction is flaky, focus on a different editor in step 2 on each try. This ensures the file is properly highlighted in the explorer on step 2.

Side note: There are another two commands that do the same thing as the "actual behavior": `Explorer: Focus on Folders View` and `View: Show Explorer`. While it's the correct behavior for those two commands, it's the wrong behavior for the command mentioned in step 4.

**This issue appeared around July 2021**, I'm not sure in which version. (In order to pinpoint the version, I tried very hard to find a way to download portable historic versions, but it seems impossible).

---------↓ Auto generated info below ↓---------

Issue Type: <b>Bug</b>

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|22.95GB (11.26GB free)|
|Process Argv|--disable-extensions --crash-reporter-id bcf2d3b4-01a7-4dae-8139-f749e75197b1|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30350414

```

</details>

**Comment by ZYinMD** [comment]
sorry, clicked by mistake by using the "report issue" menu in VSCode.

**Comment by isidorn** [comment]
I can reproduce this issue -> bug.
Might be a good issue to get introduced to the explorer. So assigning to @JacksonKearl 
Nothing critical -> not assigning a milestone

**Comment by JacksonKearl** [comment]
@AiverReaver feel free to try taking a look, however I will not be able to provide much guidance at the moment as I have just now adopted this feature area.

**Comment by isidorn** [comment]
Code pointer to start investigation 
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L679

This is the location where the `ExplorerView` tries to select items and resolves up to the item if needed.

**Comment by AiverReaver** [comment]
@isidorn thanks I will look into it.

**Comment by ZYinMD** [comment]
Since you guys are looking into the code, I also want to bring up something related:

After a workspace is opened, if the explorer has never shown yet (e.g. the sidebar has never opened, or the sidebar has opened but never on the explorer), then if you call `workbench.files.action.collapseExplorerFolders`, it'll throw an error `Cannot read property 'collapseAll` of null.

This is not necessarily a bug, but it's a new behavior after some recent update. Previously it would just fail silently, which I think is preferable.

Why I know:
Because I have `workbench.files.action.collapseExplorerFolders` -> `workbench.files.action.focusFilesExplorer` in a macro, and I often call the macro (even when sidebar is closed) followed by ↑↓ keys to navigate to a sibling file. Recently it started throwing.

**Comment by AiverReaver** [comment]
weird I cannot reproduce this issue on my mac os previously I was able to reproduce this.

**Comment by ZYinMD** [comment]
@AiverReaver switch your current editor and try again. 

To be accurate, it reproduces every other time (on odd tries but not even tries) on the same editor. But the simplest way is to switch editor, because the 1st go is an odd go.

**Comment by ZYinMD** [comment]
update: I don't know what changed recently, but right now (I'm on 1.60.1 stable), if you follow the steps in OP but do step 2 with explorer closed, then the bug will not reproduce. Previously when I filed the issue, the bug was reproducing no matter if explorer is open or closed.

I have also updated that info in the OP.

**Comment by ZYinMD** [comment]
@JacksonKearl it seems @AiverReaver is no longer working on this issue.

**Comment by lramos15** [comment]
Not sure I can reproduce what the issue is here, isn't `File: Reaveal Active File in Explorer View` what you want?

**Comment by ZYinMD** [comment]
@lramos15 You're right, closing.
