### ISSUE TITLE
"show more" link for long output is not useful

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#130512]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16909

<div type='discussions-op-text'>

<sup>Originally posted by **shaperilio** August  9, 2021</sup>
Execute this Python code:

```
# %%
for i in range(1000):
    print(i)
```
With VSCode's new "native" notebook / interactive python interface, you will see this:
![image](https://user-images.githubusercontent.com/26465923/128752310-4fa5e7d8-ca8a-4814-8d23-0cf45722f6b4.png)

Clicking on the link opens a JSON file where all the output is in one line:
![image](https://user-images.githubusercontent.com/26465923/128752369-7e2d01c0-9a8e-402b-adcb-647e5c882a16.png)

The link language is misleading and the result not really useful. I would rather see actual _raw_ output, i.e. what I would have seen had I executed it in a terminal.</div>

**Comment by IllusionMH** [comment]
Is it still reproducible in Insiders builds? https://code.visualstudio.com/insiders/

I had similar results previously, but now it shows output without JSON wrapper in my case.

**Comment by rebornix** [comment]
It's already fixed in Insiders and we will have a fix for Stable.

**Comment by wesley-cheek** [comment]
I am still seeing this in Insiders
