### ISSUE TITLE
Active text editor does not proovide symbol information on WSL2

### ISSUE THREAD

**Issue by ipanardian** [microsoft/vscode#130505]
Issue Type: <b>Bug</b>

Ubuntu 20.04
WSL2
/home/{username}/myproject

I can't show list of method or symbol, it only show Active text editor does not proovide symbol information. it's work when using without WSL.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by mjbvz** [comment]
What language is this for?

**Comment by ipanardian** [comment]
@mjbvz not working for PHP but it's working fine on Typescript

**Comment by ipanardian** [comment]
Update:
I'm just installed PHP debug and PHP Intelephense extension and now it's working as expected. I'll close this issue, thanks
