### ISSUE TITLE
Code screen scrolls with output screen

### ISSUE THREAD

**Issue by dkalowsk** [Microsoft/vscode#13055]
- VSCode Version: 1.5.3
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. Start with a fresh run of VSCode.  If you've already had the Output screen and an editor open, this will not reproduce.
2. Build a task to run an external build command.  Something like something like:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "sh",
    "args": ["-c"],
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build mycode",
            "args": ["build.sh my_project"]
        }
    ]
}
```
Build.sh essentially calls make on each sub-directory before it moves on to linking and spills the output on the screen.
3. Open a large-ish C/CPP file in the editor (couple thousand lines).  
4. Run the build task.
5. Watch as the build task fills up the output window and starts to scroll, the text in the above editor will increment line by line with the task output buffer filling.

**Comment by isidorn** [comment]
October to investigate

**Comment by isidorn** [comment]
I am not able to reproduce this using a similar scenario (namely I have nothing open, I start flooding then output and then I open a large .ts file. You can see this in the attached gif. 

Please let me know if you can reproduce this with our latest insiders build? If yes - can you please attach a gif or a video which shows this. Thank you

![output](https://cloud.githubusercontent.com/assets/1926584/19157122/92f54e8a-8be4-11e6-980d-49f1c5c69f8e.gif)

**Comment by dkalowsk** [comment]
With the latest insider build I'm not seeing it either.  Should have thought to test with that first.  Thanks for the follow up and sorry for the noise.
