### ISSUE TITLE
typescript serivce crashed more than 5 times

### ISSUE THREAD

**Issue by carlonoelle** [microsoft/vscode#130573]
Issue Type: <b>Bug</b>

I have a Monorepo which uses yarn workspaces and typescript all the way, with root tsconfig which references all the tsconfigs from the multiple sub-packages. After some time the typescript service crashes multiple times and the warning is shown

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 9, 8|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id b878003a-371f-4e30-8cfe-13ad0c536d66|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.28.0
vscode-color|ans|0.4.5
cform|aws|0.0.24
task-panel|Bit|0.2.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vscode-svelte-snippets|fiv|0.5.0
auto-rename-tag|for|0.1.8
shell-format|fox|7.1.0
terraform|has|2.14.0
svgeditor|hen|2.9.0
svelte-vscode|Jam|0.9.3
vscode-styled-components|jpo|1.6.6
fluent-icons|mig|0.0.12
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
jupyter|ms-|2021.8.1195043623
awesome-flutter-snippets|Nas|3.0.1
color-highlight|nau|2.4.0
material-icon-theme|PKi|4.9.0
prisma|Pri|2.29.0
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
js-jsx-snippets|sky|10.2.0
autoimport|ste|1.5.4
addDocComments|ste|0.0.8
vs-code-node-require|tgr|1.10.2
helm-intellisense|Tim|0.11.0
import-to-require|tle|0.7.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by machineghost** [comment]
Not OP, but I'm running on the latest insiders build, with all extensions disabled (on Linux), and am still getting this error basically as soon as I start up VS Code.

Here's my version info:

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-80-generic

**Comment by mjbvz** [comment]
@machineghost  Yes please open a separate issue. Also be sure to test in VS Code insiders

**Comment by machineghost** [comment]
>but I'm running on the latest insiders build

As I said, already running the latest Insiders build (just got it this morning).  I'll file separately.

**Comment by mjbvz** [comment]
Closing as we need more information from the original poster to investigate
