### ISSUE TITLE
in native interactive window, text search/find is missing

### ISSUE THREAD

**Issue by ltmsyvag** [microsoft/vscode#130587]
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

In previous (python) interactive window, I was able to (in macOS) use cmd+F to search/find text in interactive window. I relied on this feature a lot, since I read python docstrings mostly in interactive window, and when you read docs, you use text search to quickly locate keywords. 

In the new native interactive window, it seems we don't have text search anymore. I would be very happy if I am mistaken, if I am not, then It would be great to have this feature back.

**Comment by rzhao271** [comment]
I can search the cells, but not the output.

**Comment by rzhao271** [comment]
That works. The found text is bolded, but it's not very noticeable to me. I wonder if adding an underline or outline could help. I can also create a new feature request for it if that works better.

**Comment by amunger** [comment]
thanks, yeah that could be improved. The same issue exists in notebooks as well.
