### ISSUE TITLE
VSC is freezing 

### ISSUE THREAD

**Issue by pim-pesochek** [microsoft/vscode#130584]
Issue Type: <b>Bug</b>

When I type C++ code in cpp file VSC is freezing and not allowing me to type code, it looks like it searches for symbols at this moment, because after menu with symbols is shown the freezing is going away. I disable almost all plugins but freezing did not dissapear

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|20, 14, 9|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 3fa2298c-c5ec-46c9-815d-559550ec083c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|1.4.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30350415

```

</details>

**Comment by rzhao271** [comment]
Does this issue occur with other workspaces/folders?
It might help to file this issue in the C++ extension repo if it is specific to C++ files.

**Comment by pim-pesochek** [comment]
> Does this issue occur with other workspaces/folders?
I tried folder with pythons sources and it is also freezing


> It might help to file this issue in the C++ extension repo if it is specific to C++ files.

I have disabled all C++ extensions so I have only IDEA keybinding extension and theme extension active

It starts freezing when I switch CAPSLOCK on and try to type it.
Man, now I realising it is freezing everywhere even here, when I switch capslock on. Looks like macos 11.5.1 problem
https://www.reddit.com/r/applehelp/comments/oul4hg/caps_lock_freezing_computer_after_macos_1151/
