### ISSUE TITLE
Explore how to indicated read-only and deleted files open in editors more effectively

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#130526]
## Summary

Currently when you open a file and it has been deleted or you open a read-only file, we append the text to the editor tab to indicate this:

<img width="430" alt="CleanShot 2021-08-10 at 15 26 20@2x" src="https://user-images.githubusercontent.com/35271042/128942910-b02fb116-4702-4435-ac8e-ce89f821eadc.png">

This can get busy when you have a lot of tabs open, especially with long names. This issue aims to explore a few different ways that we can visualize this.

### Option A

One idea is to try and use different seti file icons for this and show the information via tooltip:

![image](https://user-images.githubusercontent.com/35271042/128946332-033fb244-702d-4d94-abfa-cc5009ce9d4d.png)

Alternatively, we could use codicons to display instead of seti:

![image](https://user-images.githubusercontent.com/35271042/128946318-fef1f493-be73-4f52-8058-2f3f92436000.png)

### Option B

We could use our info icon for read-only and error for deleted:

![image](https://user-images.githubusercontent.com/35271042/128946289-4cbbbc47-5ef6-4cfa-94bb-83f3195ac6be.png)

### Option C

Or we simply rely on the decorators to indicate it, we'd need to figure out how to show read-only:

![image](https://user-images.githubusercontent.com/35271042/128946249-c7462bca-1bab-40ec-a883-500fa7ddfd4f.png)

cc @bpasero

**Comment by bpasero** [comment]
👍 , one interesting aspect of this is that a tab can indicate both readonly and deleted at the same time.

**Comment by misolori** [comment]
@mjbvz let me know what the use case is for custom editors and if the "read only" state would still apply or if you're looking for an alternate version

**Comment by misolori** [comment]
I'm leaning towards leveraging the existing git decorators and using our custom hovers to display this information (as opposed to the native ones):

<img width="552" alt="CleanShot 2021-09-14 at 17 39 26@2x" src="https://user-images.githubusercontent.com/35271042/133351949-2c215a79-0fde-4cc3-a151-7551967e3ff5.png">

@bpasero thoughts?

**Comment by bpasero** [comment]
> leveraging the existing git decorators

but the decorators are not using red for deletion it seems, probably because that is reserved for showing problems:

![image](https://user-images.githubusercontent.com/900690/133374983-3c6dbfa6-a570-4d9c-8760-c7b31c0b88bb.png)

Are you suggesting to change decorator color for deletes to show like problems?

Also, are you suggesting to add a new decoration `R` for the readonly case?

> and swapping to codicons for easier discoverability

To clarify, you mean to show an additional icon to the left of the label for conveying the information that the file is deleted or replacing the file icon with it? Also note that user can disable icons.

> using our custom hovers to display this

Can you elaborate why this better than the native hover where the same information is displayed?

**Comment by misolori** [comment]
> but the decorators are not using red for deletion it seems, probably because that is reserved for showing problems:

I think currently this depends on whether you have any warnings/errors:

<img width="248" alt="CleanShot 2021-09-15 at 07 54 35@2x" src="https://user-images.githubusercontent.com/35271042/133457264-37fb9e7c-c73b-463e-82b9-5f835d83ae19.png">

<img width="196" alt="CleanShot 2021-09-15 at 07 55 38@2x" src="https://user-images.githubusercontent.com/35271042/133457437-bf3ca8bf-d550-4157-a4f4-f1fe6e4163db.png">

<img width="231" alt="CleanShot 2021-09-15 at 07 55 55@2x" src="https://user-images.githubusercontent.com/35271042/133457495-d2bbf637-9d3d-41f5-b6ed-bc9b850f0771.png">

So I'm suggesting for Deleted & Read Only to have an elevated hierarchy to the warnings/errors because when a file is deleted, the warnings/problems don't mean anything because the file is now gone. For Read only, you can't edit the file so the warnings/errors mean less.

> Also, are you suggesting to add a new decoration R for the readonly case?

Yes, since decorators already show a `D` for deleted, it made sense to add `R` for read only, though I don't know if there is a similar concept in git for it. My suggestion was to keep them consistent.

> To clarify, you mean to show an additional icon to the left of the label for conveying the information that the file is deleted or replacing the file icon with it? Also note that user can disable icons.

Suggestion is to replace the file icon with our codicons and yes there are also other states that will hide all of these indicators like:

![image](https://user-images.githubusercontent.com/35271042/133458256-1fd04d8a-f083-4107-82b9-8263c2fe1c0e.png)

> Can you elaborate why this better than the native hover where the same information is displayed?

Because our custom hovers can appear much quicker than native. I'd love it if we switched all hovers to it but understand the challenge in doing so.

**Comment by misolori** [comment]
I brought this up in our design-wide critique for some feedback and here's the suggestions:

- Showing codicons as status icons (like the trash icons) can be a bit confusing, is it a status or an action?
- People associate the the filename w/ the file icon so replacing the file icons can cause additional overhead for the user
- Everyone liked the strikethrough for deleted files
- Additional indicators like tab background color could be another option to explore
- There was a preference for using the git decorators for the status (even though read only isn't a git status, but is a decorator)
  <img width="437" alt="CleanShot 2021-09-15 at 09 39 58@2x" src="https://user-images.githubusercontent.com/35271042/133474360-4eba3bdd-d708-49a5-addb-aca878a37cf9.png">

**Comment by bpasero** [comment]
I have pushed a change to enforce the `strikethrough` decoration. Fun fact, the decoration would have worked, but we had a CSS rule to disable text decorations in tabs, not sure why.

**With SCM**

![image](https://user-images.githubusercontent.com/900690/133609731-63698435-5904-4fd3-a445-472daf92cf3b.png)

**Without SCM**

![recording](https://user-images.githubusercontent.com/900690/133609748-68f6e54c-cb45-4b40-bd67-9e26e85bc7cf.gif)

The fact that a file is readonly only shows up in the hover and not as a decoration because I think showing `R` is misleading: SCM uses that to indicate a file was moved.

> Because our custom hovers can appear much quicker than native. 

That is a user setting tough right? And by default we try to match OS defaults.

**Comment by bpasero** [comment]
Btw one issue with using decorations to convey this information is that I cannot really limit the decoration to tabs only, so we would end up potentially having 2 decorations for "deleted" (one from SCM and one from the the new location).

**Comment by misolori** [comment]
I see, so then we need to explore alternate options that don’t rely on decorations?

**Comment by misolori** [comment]
Visual Studio uses a lock icon for read only:

<img width="391" alt="CleanShot 2021-09-16 at 10 58 33@2x" src="https://user-images.githubusercontent.com/35271042/133661689-d986daf3-bcfe-40d8-8ebd-dd2c21ee852d.png">

So if `Deleted` uses the strikethrough, I wonder if we can append a lock icon for read only that way each can work independently without icons/decorators?

<img width="484" alt="CleanShot 2021-09-16 at 11 01 41@2x" src="https://user-images.githubusercontent.com/35271042/133662107-46d2a63e-58d7-4c9a-9aca-963417c95e55.png">

<img width="588" alt="CleanShot 2021-09-16 at 11 03 28@2x" src="https://user-images.githubusercontent.com/35271042/133662278-0fde5467-f98f-40cd-a9db-844d5bcf554a.png">

**Comment by silkfire** [comment]
Maybe it's just me, but if a file has been deleted, then I no longer care whether it was read-only or not.

**Comment by bpasero** [comment]
I went ahead and fully embraced decorations for this:

![image](https://user-images.githubusercontent.com/900690/133749948-369722c8-fa4f-4cfe-81aa-0a10087a3423.png)

It is possible that multiple decorations apply, e.g. in git case, but I think that still looks fine:

![image](https://user-images.githubusercontent.com/900690/133750079-715a8726-63c3-438b-a763-d093ac02029b.png)

**Comment by bpasero** [comment]
Related hover indicator:
![recording](https://user-images.githubusercontent.com/900690/133784756-8f6aa81e-8804-4199-9748-0508cb1fbfbd.gif)

**Comment by misolori** [comment]
Looks good!

**Comment by bpasero** [comment]
@misolori feedback from the standup was to maybe use a different icon since we use the lock already for locked groups. Not sure we would have anything else in the cards. I personally do like the lock icon though.

**Comment by gjsjohnmurray** [comment]
I also like the lock, but understand the scope for confusion. Could the eye codicon represent a view-only document?

**Comment by misolori** [comment]
yea we could use eyes as an alternate that would still work well with locked groups:

<img width="437" alt="CleanShot 2021-09-20 at 09 31 36@2x" src="https://user-images.githubusercontent.com/35271042/134039350-1f55e3c5-94bd-4fba-8459-288ec7cc7afc.png">

But we do use the lock icon in multiple areas (notebooks locked cells, output scrolling, ports privacy) and we add the lock icon to the tab and not the group so I personally still think it's fine to use:

![image](https://user-images.githubusercontent.com/35271042/134039855-312da84e-020b-4f6a-b1cd-2a514ea62f0b.png)
