### ISSUE TITLE
Select Language "js" could offer JavaScript before JSON

### ISSUE THREAD

**Issue by varna** [microsoft/vscode#130552]
I would like that when "Selecting Language" in a new file and typing `js` I would receive `JavaScript` instead of `JSON` as the first suggestion.

**Comment by TylerLeonhardt** [comment]
Thanks for opening this!  We have a new feature landing in the next release that will help in this space called "Automatic Language Detection". If you paste a decent amount of JS inside of your editor, we will auto-detect that it's JS and set the language to JS without you having to set it yourself.

Additionally, JS will float to the top of the "Select Language" if we feel confident enough.

This feature is already on by default in insiders so if you get that you can test it out.

I think this feature, plus the existing ability to set the default language to whatever you want:
![image](https://user-images.githubusercontent.com/2644648/129064307-934b140c-624e-4beb-b7e1-7a8a2e446a7a.png)

Is enough to cover this case
