### ISSUE TITLE
Testing API to support navigation to a specific line for non-test item

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130541]
Navigation to a `TestItem` using `Go to test` does not work unless the `TestItem.range` is set. If the `TestItem.range` is not set and a `TestItem.uri` is provided, the file referenced by the `uri` will be opened in a random location.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/2074089/128967218-f78e99d3-d830-4f37-9c5f-e0c2f8d7305c.png">

It is not possible to navigate to a line using a file URI bookmark like it is elsewhere in VS Code's API, for example, profile `file://mypath/myfile#L15`.

For example, I may want to structure test output as follows:

- myPath/myFile.js
  - myFirstDescribeBlock
     - myNestedDescribeBlock
        - test should do something

In the example above, I want `myPath/myFile.js` file URI to reference `file://myPath/myFile.js#L1` even though there is no range associated with this TestItem.

**Comment by connor4312** [comment]
By default it'll just open the location the user was last editing in the file, just as if it was opened from the File Explorer. I think this is a matter of personal preference, a setting could be appropriate.

**Comment by smcenlly** [comment]
> By default it'll just open the location the user was last editing in the file, just as if it was opened from the File Explorer. I think this is a matter of personal preference, a setting could be appropriate.

I agree this is good default behavior. However, if a line number is appended to the URI (e.g. adding `#L1`) and there is no range for the test, ideally it should open to the file + line/column specified in the URI. Not doing so is inconsistent with how VS Code treats URIs in other places.

**Comment by jrieken** [comment]
verified in source
