### ISSUE TITLE
URL opener does not bring window to top on Windows

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#13054]
- VSCode Version: Code - Insiders 1.6.0-insider (0f7880d7a490ba9aee2b053f3f2e46c19423e7e4, 2016-09-29T13:50:23.615Z)
- OS Version: Windows_NT ia32 10.0.14393

Found verifying #10340

Steps to Reproduce:

0. Open VSCode insider
1. Enter vscode-insiders:extension/vscodevim.vim into the browser's location bar
2. Observe the VSCode window does not come to top (unexpected), the extension's description correctly opens in an editor tab

**Comment by joaomoreno** [comment]
Actually: #929
