### ISSUE TITLE
creating new file/folder and name it by copy-paste, NOT WORKING with right-click

### ISSUE THREAD

**Issue by yilmazdurmaz** [microsoft/vscode#130564]
Issue Type: <b>Bug</b>

I want to create a new file/folder with the the name copied elsewhere. So I right-click  the explorer, select "new ...", then try right-click in the box that expect to enter a name.

expected behaviour: right-click menu opens with copy/paste options in it.

current behaviour: right-click cancels the operation and then opens the explorer menu for currently selected file.

PS: copy-paste works from keyboard but in cases right-click is is a faster action to take, this slows down productivity.

PS: title is already long, but I have found that trying to rename an existing file/folder by copy/paste from right-click also does this same bug. right-click into the box just cancels the operation and opens menu for active file/folder

-----------------------
I have tested many older versions of VS, so apparently the problem has started somewhere in summer to fall of 2018. (all windows zip versions set portable by "data" folder in extracted folder)

v1.20.0: context menu opens for copy/paste correctly
v1.28.0: context menu opens but the action is cancelled while the context menu stays on the screen.
v1.38.1: context menu opens for a very short time (less than a second) and closes along with cancelling the action
v1.49.3: right-click cancels the action and opens a context menu for the file/folder already selected before the action.
v1.57.0 and v 1.59.0 are the same as v1.49.3

-----------------------

VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.94GB free)|
|Process Argv|. --crash-reporter-id 584324ec-9312-4a21-82cb-89491f399328|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
prettier-vscode|esb|8.1.0
vs-code-http-server-and-html-preview|Fli|2.2.2
vscode-jsonp|luy|1.0.1
js-interactive|Moh|1.1.11
csharp|ms-|1.23.13
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.6.999662501
cpptools|ms-|1.5.1
vetur|oct|0.34.1
material-icon-theme|PKi|4.9.0
vscode-npm-scripts|tra|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172

```

</details>

**Comment by isidorn** [comment]
There are already issues for the context menu and the tree, thus closing as duplicate since I think this is covered by those issues. To find them search for context menu and focus

**Comment by yilmazdurmaz** [comment]
@isidorn It is how awesome you decided so quickly to close the issue just because you "think" it is covered elsewhere. proud of you.

If it was really a duplicate somewhere, do you think I would still write this post?

you are right there are hundreds of context menu focus posts. but none seems to point a problem about creating new files/folders, along with right mouse clicks.

anyways, I have tested many older versions of VS, so apparently the problem has started somewhere in summer to fall of 2018. (all windows zip versions set portable by "data" folder in extracted folder)

v1.20.0: context menu opens for copy/paste correctly
v1.28.0: context menu opens but the action is cancelled while the context menu stays on the screen.
v1.38.1: context menu opens for a very short time (less than a second) and closes along with cancelling the action
v1.49.3: right-click cancels the action and opens a context menu for the file/folder already selected before the action.
v1.57.0 and v 1.59.0 are the same as v1.49.3

now, please re-open the issue and let's hope for a fix for this 3-years old shapeshifting problem.

**Comment by yilmazdurmaz** [comment]
@isidorn  what does an "is:issue is:open" in search box mean to you? if you use "is:issue is:open context menu focus" you will get only 67 open issues right now. and none of them, other than the one opened yesterday, reports this bug.

and if no issue was posted before this that is still active then that means there cannot be any other "solved" ones to make this post a duplicate because the issue has been present for the last 2 years.

so why do you still hesitate to reopen it?

**Comment by joaomoreno** [comment]
@yilmazdurmaz, thanks for the patience here. This fix will soon land in Insiders and in the next Stable:

![Recording 2022-12-23 at 16 32 04](https://user-images.githubusercontent.com/22350/209360717-ae9f9816-8858-48ef-b46f-16c0c8d0cadd.gif)
