### ISSUE TITLE
Check input box already popup before call vscode.window.showInputBox

### ISSUE THREAD

**Issue by fiveight58** [microsoft/vscode#130559]
I want vscode to add a new api to vscode.window, like hasInputBox.
Then I can use this function to check input box already popup before call vscode.window.showInputBox.
Thanks!

**Comment by TylerLeonhardt** [comment]
@fiveight58 can you give me a real scenario why you would want this? Perhaps the solution to your issue can be solved a different way and I'd like to help. I don't know if we want something like `hasInputBox ` in the API without multiple scenarios that prove its worth.

**Comment by fiveight58** [comment]
@TylerLeonhardt
Thanks for your reply!  
In my vscode there are two extensions, one of them developed by me, each one shows an input box when vscode open a folder, and all of them register timer to show the input box again and again after user press ECS.
So before user finish input something in first input box, the second input box comes to make user crazy.
I want to check input box already popup before call vscode.window.showInputBox in my extension to make user easy.
Thanks!

**Comment by TylerLeonhardt** [comment]
Usually showing an input box upon opening a folder is pretty disruptive for the user. Can you explain why you're extension needs to prompt immediately? and why the other extension needs to do so to? It would be better to prompt when you absolutely need the information.
