### ISSUE TITLE
typo in status bar: pluralize "info" -> "infos"

### ISSUE THREAD

**Issue by vapurrmaid** [microsoft/vscode#130503]
Does this issue occur when all extensions are disabled?: Not sure --> the only _reliable_ way I know how to reproduce it is by creating a spelling error with Code Spell Checker. If anyone has any tips how I can try to repro this with all exts enabled, I'm happy to take that on and post a new GIF.

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Cause exactly one information status to be reported in the status bar
2. Hover and observe the tooltip
3. The tooltip will read `"1 Infos"` instead of `"1 Info"`

![one_infos_2](https://user-images.githubusercontent.com/11184711/128903721-6c6e6e5a-355a-4823-9559-576d97acb5fd.gif)

**Comment by heynan0** [comment]
If you want to implement different cases, this would involve having separate translation strings for the singular and plural, as well as a third case for the 0 value.

```
const errorTitle = (n: number) => {
  if (n === 0) {
    return localize('totalErrorsZero', "No Errors"); 
  } else if (n === 1) {
    return localize('totalErrorsSingular', "{0} Error", n); 
  } else {
    return localize('totalErrors', "{0} Errors", n); 
  }
}
```

But is it really necessary? One could easily avoid the grammatical discussion if you put like this: `Errors: {0}`, `Warnings: {0}`, `Infos: {0}`.

**Comment by vapurrmaid** [comment]
> if you put like this: `Errors: {0}`, `Warnings: {0}`, `Infos: {0}`

Seems very reasonable to me

**Comment by Nirajn2311** [comment]
>  if you put like this: Errors: {0}, Warnings: {0}, Infos: {0}

This looks better and is understandable

**Comment by sourabh112** [comment]
Can I take on this issue( If it is not assigned to someone else )? It looks fairly simple to me.
But as I'm quite new to this so I might need some guidance.

**Comment by sourabh112** [comment]
@sandy081, I have made the changes to correct the typos. Should I make a PR or it is already completed?
