### ISSUE TITLE
Show "Debug Cell" command in cell execute dropdown

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#130524]
#126431

Each cell in a Jupyter notebook should have a dropdown by the run button with a "Debug cell" command that runs the cell in debug mode

**Comment by JacksonKearl** [comment]
Noticed there's no dropdown in untitled notebooks, other than that looks good.

**Comment by roblourens** [comment]
Known issue :+1, https://github.com/microsoft/vscode-jupyter/issues/6898#issuecomment-930656216
