### ISSUE TITLE
Vscode stuck at downloading update forever

### ISSUE THREAD

**Issue by pedrost** [microsoft/vscode#130506]
Does this issue occur when all extensions are disabled?: Yes

I can't update my vscode because it show's this message of an update that's already happening, but this message is on my vscode for weeks now, and I really wish I could update it.
<img src="https://imgur.com/MrKvHfT.png" />
- VS Code Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (2 mos ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
- OS Version: macOS BigSur 11.2.3

**Comment by deepak1556** [comment]
Can you attach the `ShipIt_stderr.log`, `ShipIt_stdout.log` under `Library/Caches/com.microsoft.VSCode.ShipIt/`.
