### ISSUE TITLE
VS Code closes unexpectedly

### ISSUE THREAD

**Issue by ssorlliw** [microsoft/vscode#130521]
Issue Type: <b>Bug</b>

Steps:
Open code with `code --disable-extensions`.
Wait 5-10 minutes.  
VS code terminates on its own.

Happens in both 1.59  and 1.60-insider

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.0-80-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.27GB (7.05GB free)|
|Process Argv|--no-sandbox --disable-extensions --crash-reporter-id 0aefd19d-413b-4637-9358-6f107bdcc172|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by deepak1556** [comment]
Can you launch with `code --verbose --disable-extensions` and attach the output when issue happens, thanks!

**Comment by MeMineToMe** [comment]
Same issue on my laptop, exact same config : 
```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-80-generic snap
```
Started with following command line : 
`code --disable-extensions --crash-reporter-directory /tmp`

I can attach dump file if needed.

**Comment by MeMineToMe** [comment]
[8d325946-0a76-48dc-a1a730b1-cd20a005.dmp.gz](https://github.com/microsoft/vscode/files/6993245/8d325946-0a76-48dc-a1a730b1-cd20a005.dmp.gz)

**Comment by ssorlliw** [comment]
@MeMineToMe try one of the other methods of installing vscode on linux (from https://code.visualstudio.com/docs/setup/linux) to get around this issue . I'm on Ubuntu, and reinstalled using apt instead of snap and it works fine.

@deepak1556 I've attached a file with the verbose output, but for code-insider rather than code.   I did need to removed all log lines for the file watcher on file Insiders/logs/20210817T131258/renderer1.log to get the size down to one github would accept. They all look like the following:

> [27218:0817/131401.095173:INFO:CONSOLE(601)] "%cTRACE color: #888 [File Watcher (node.js)] [CHANGED] /home/wross/.config/Code - Insiders/logs/20210817T131258/renderer1.log", source: vscode-file://vscode-app/snap/code-insiders/790/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (601)


[code_verbose_2.txt](https://github.com/microsoft/vscode/files/7001836/code_verbose_2.txt)

**Comment by deepak1556** [comment]
@ssorlliw if you are seeing the issue with latest stable `1.62` which has got some runtime updates, can you share the crash log based on https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports. Thanks!
