### ISSUE TITLE
Status Bar color for paused debugging

### ISSUE THREAD

**Issue by snoosmoomrik** [microsoft/vscode#130566]
There is a setting ```statusBar.debuggingBackground``` which sets status line color in debugging mode.
Is it possible to add something like ```statusBar.debuggingPausedBackground``` to set different color of status line when breakpoint is reached?

**Comment by weinand** [comment]
I'm not aware of such a feature...

**Comment by isidorn** [comment]
`statusBar.debuggingBackground` is not a setting, but a color which we support to customise.
Adding a new color `debuggingPausedBackground` is a fair feature request, but we do not have it on the plan. Thus assigning to backlog for now.
