### ISSUE TITLE
Output to the debug console from a PowerShell script stops at some random point

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vscode#13056]
- VSCode Version: 1.5.3
- OS Version: Win10.1607

Steps to Reproduce:

1. Run a powershell script (I observed that behaviour on a couple of very different scripts)
2. At some point output to the debug console stops, though the script finishes just fine.

**Comment by isidorn** [comment]
Please file this to the powershell extension here
https://github.com/PowerShell/vscode-powershell
