### ISSUE TITLE
Err: https://packages.microsoft.com/repos/vscode stable Release 404  Not Found

### ISSUE THREAD

**Issue by maravento** [microsoft/vscode#130523]
Does this issue occur when all extensions are disabled?: Yes/No 
Not related to extensions

- VS Code Version: 1.59.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:
/etc/apt/sources.list.d/vscode.list
deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

Err: https://packages.microsoft.com/repos/vscode stable Release 404  Not Found

![Captura de pantalla -2021-08-10 17-35-18](https://user-images.githubusercontent.com/14880802/128943630-18f0cfda-acdf-48fc-9fd8-2bb482d4037d.png)

**Comment by Tyriar** [comment]
This might have been a temporary outage, is it still a problem? @eamodio do you get a 404 when you hit that from US east?

**Comment by maravento** [comment]
fix it for LA

**Comment by eamodio** [comment]
Works for me
