### ISSUE TITLE
Wrong language with definition preview hover

### ISSUE THREAD

**Issue by freebroccolo** [Microsoft/vscode#13057]
It seems that when a definition preview is shown in a hover (on ⌘+hover), it is assumed that the location occurs in a file of the same language as the origin position. Since this is not always the case, the result can be incorrectly highlighted.

I think a straightforward way to address this would be to allow specifying an optional `language` field (like for `MarkedString`) along with the returned `Location`.

**Comment by jrieken** [comment]
We should be able to figure that out using the URI of the location

**Comment by joaomoreno** [comment]
Verification steps?

**Comment by jrieken** [comment]
@joaomoreno https://github.com/Microsoft/vscode/issues/13057#issue-180200312 In language A have a symbol from language B. Control hover over that symbol and make sure language B is used for code highlighting

**Comment by aeschli** [comment]
Oh, I already started.. verified with:
```
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    context.subscriptions.push(vscode.languages.registerDefinitionProvider('html', {
        provideDefinition: (document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken) => {
            let other = document.uri.with({path: document.uri.path + '.css'})
            return new vscode.Location(other, new vscode.Position(1, 0));
        }
    }));
}
```

**Comment by freebroccolo** [comment]
This seems to be broken again as of 1.8.1.

Now the preview just highlights almost everything in blue (see below) so it seems it's not even using the same language as the origin but something else unexpected. It doesn't look like an issue with the grammar incorrectly parsing either. I may be doing something wrong in the extension though.

Can someone confirm this is still working as expected? @jrieken @aeschli

![preview-highlights-opt](https://cloud.githubusercontent.com/assets/151197/21506579/6b196c0e-cc2e-11e6-9404-ba844a435bc9.png)
