### ISSUE TITLE
Feature Request: Use Up/Down Arrow Key To Move Focus In Hover Action Bar

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#130562]
![image](https://user-images.githubusercontent.com/2931520/129006443-7905bdf6-f9c9-4d9c-ab87-3b282e829248.png)

Currently you can use Tab/Shift+Tab to move the focus. However, this only works if tab is not bound otherwise (e.g. to "Accept Inline Suggestion"). In this case, you have to enable "Tab moves focus" - but then you have to disable it again when you want to use Tab to accept inline suggestions or to indent code.

It would be nice if you could also use the arrow keys to move the focus to the next/previous button in the hover action bar.

(Idea from @isidorn)

**Comment by Tyriar** [comment]
@hediet your inline suggest keybinding could just use `!editorHoverVisible`?

**Comment by hediet** [comment]
Then it would still insert \t into the editor.

**Comment by Tyriar** [comment]
Tab insertion requires editorTextFocus though which should be false when the hover is focused?

```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus" },
```

**Comment by aiday-mar** [comment]
The Up and Down arrows are currently reserved for scrolling with the horizontal and vertical scrollbars on editor hover resize.

**Comment by Tyriar** [comment]
Tab and shift+tab work fine for me without tab focus mode. Since up and down already have jobs according to @aiday-mar I don't think there's anything to do here.

> In this case, you have to enable "Tab moves focus" - but then you have to disable it again when you want to use Tab to accept inline suggestions or to indent code.

Since I can't repro, maybe this is a custom keybinding conflict?
