### ISSUE TITLE
Align in-editor peek views (test, problems, references, etc.) UX

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#130516]
## Summary

This issue aims to capture the consolidation of the test peek view + problems "go to problem" view. The problems view has UI to view the context of the failures, similar to a peek definition, while the problems view has limited UI and causes users to navigate from the error to the problems panel to see the next set of problems/warnings.

## Test failures
<img width="698" alt="CleanShot 2021-08-10 at 12 48 21@2x" src="https://user-images.githubusercontent.com/35271042/128925382-69cfc561-73bb-4750-934d-52395b8daaea.png">

## Problems view
<img width="705" alt="CleanShot 2021-08-10 at 12 50 21@2x" src="https://user-images.githubusercontent.com/35271042/128925625-af2d0e71-5ae1-40a8-9a00-9594c0250142.png">

## Concepts

One idea is to combine the test UI with problems:

- Add toolbar options for navigating and toggling the side view inside of the peek view
- Provide inline actions for problems where relevant (quick fix)
- Update colors to add visual refresh to peek view

<img width="801" alt="CleanShot 2021-08-10 at 12 57 25@2x" src="https://user-images.githubusercontent.com/35271042/128926604-ec2b675a-5c4e-4add-8dc9-e3689b967baf.png">

cc @connor4312 @sandy081

**Comment by connor4312** [comment]
I like the visual refresh. In previous discussions in my 1:1's with Kai I was an advocate for the combination (I think "alignment" might be a better word, not sure how much reuse there would be on a code level) to bring a tree or list view into the problems peek. I like having everything in one place and not have to look in the sidebar or panel when I'm going through issues.

**Comment by misolori** [comment]
Some feedback we saw in our ux sync today:

- The arrows should only appear when the side panel is not visible as that is primary way to navigate
- We should align this work with our peek views as well (references)
- Would expect for these to work similar to references where you can navigate to other tests
- We should persist the side panel per each area (references, test, problems, etc.)

And below is an example of aligning the UI in the peek view with this:

<img width="737" alt="CleanShot 2021-08-11 at 15 17 05@2x" src="https://user-images.githubusercontent.com/35271042/129110791-0ed78df0-1195-4500-88e2-afbec88bfd61.png">

**Comment by sandy081** [comment]
So we are trying to bring the items explorer into the peek view that can be toggle-able? If so, Problem peek will have all problems from the file. How about test failure peek? Does it contain all test failures or history of test failures?

**Comment by misolori** [comment]
Yes, the concept is that all peek views have the same building blocks (navigation, panel, etc.). For problems, showing all errors and warnings for what we show in the panel is what I would expect. In tests, it shows the history of the tests. So they are slightly different but still similar and I think that's ok. References shows all files where there are references to those items, so that's also slightly different. But the main blocks remain the same in terms of layout.

**Comment by byehack** [comment]
+ support up/down key on peek view panel focused.

**Comment by misolori** [comment]
@byehack can you elaborate? up/down keys already work on the peek view panel

**Comment by byehack** [comment]
> @byehack can you elaborate? up/down keys already work on the peek view panel


https://user-images.githubusercontent.com/26390254/129944666-77ec3d5e-d625-483c-aa05-5083d065b374.mp4

stable v1.59.0

**Comment by misolori** [comment]
@byehack the proposal here would be to bring the panel to the warning/error peek views so you will be able to navigate via up/down

**Comment by byehack** [comment]
> @byehack the proposal here would be to bring the panel to the warning/error peek views so you will be able to navigate via up/down

yes. and because of you are aligning all of peek views, i just would notice that the up/down keys supports well.

**Comment by misolori** [comment]
@byehack when the panel is not visible you will need to navigate to the up/down icons in the peek view or use the keyboard shortcut (F8):

<img width="838" alt="CleanShot 2021-08-18 at 12 37 33@2x" src="https://user-images.githubusercontent.com/35271042/129961320-e75ac541-e1d0-4489-be59-74bb7573dd6b.png">

**Comment by byehack** [comment]
i am in v1.50.0 and default keyboard shortcut is `Alt+F8`/`Shift+Alt+F8`:
![image](https://user-images.githubusercontent.com/26390254/129975726-93e4a755-364f-484e-97f0-acbc6cee577f.png)

and Up/Down keys doesn't do anything. isn't it better to set it to arrow keys or should i manually change the default key binding?

**Comment by sandy081** [comment]
> For problems, showing all errors and warnings for what we show in the panel is what I would expect. 

Is it all or only those associated to the opened file?

**Comment by jrieken** [comment]
I a fan of the updated colors and styles but I am very skeptical about showing a list of errors inside the error peek. In fact, I find the test fail/pass history annoying and useless. What's the value in knowing that a test passed before it failed? I would rather not have it and reduce clutter - which I now fear is being added into the peek error widget too.

**Comment by jrieken** [comment]
linking https://github.com/microsoft/vscode/issues/73111 which is about adding a command to open the references view from the peek title

**Comment by misolori** [comment]
I think there are some users that would like a list of the rest of the problems (like myself) and others that don't. That's why we are wanting to push for having a toggle that would allow both groups to be satisfied. If people really didn't want to toggle this then a setting could hide it completely.

I think the a separate discussion is what the content inside of the list should be. In almost all other cases we show the current state/items and in the test explorer it is a history, which some have mentioned is a bit odd.

**Comment by misolori** [comment]
Design explorations are done and assigning to the other area owners

**Comment by misolori** [comment]
Design explorations are done and assigning to the other area owners

**Comment by connor4312** [comment]
Thanks for your great work on this Miguel 🙂

**Comment by jrieken** [comment]
> I think there are some users that would like a list of the rest of the problems (like myself) and others that don't. 

That's making error peek an absolute outlier - all peeks show extra information about the "thing" its arrow is pointing at. Like, references of the symbol being pointed at, failures of the test being in etc. The same is true for squiggles: its the whole diagnostic for the current squiggle (message, source, related etc). Showing any message under a squiggle is just confusing because the message is out of context, like peek points at `foo.bar()` and its messages says `cannot resolve console.lock()`

I do understand the desire for good overview of errors and rapid navigation (that's why F8 is cross file) but peek isn't the right platform for that. We are also not discussing that breakpoint peek should include a list of all breakpoints or that quick-diff peek shows all changes in all files (they don't duplicate panes/views but show contextual information)

**Comment by sandy081** [comment]
Agreed with @jrieken opinions. I feel it's not worth duplicating problems view into peek view for the value it brings in. It will cause inconsistencies between these two views and could possibly lead to port all features to the list. I understand about consistency between views, but it adds noise and looses simplicity.

**Comment by misolori** [comment]
Brought this up in the ux sync today and the consensus was that even though having richer navigation in the go to error/warning peeks, it ends up taking away from the "simplicity" of quickly looking at more information. 

There was also discussion around how the Test peek has the history panel open by default is a bitt odd/unclear since it behaves differently from our other peek views. It was suggested to have an action in the toolbar to toggle the panel instead:

<img width="716" alt="CleanShot 2021-09-08 at 14 51 09@2x" src="https://user-images.githubusercontent.com/35271042/132590561-afce01bb-765c-4346-92ca-9387ed141c1b.png">
