### ISSUE TITLE
User sync stoped since there was too many requests

### ISSUE THREAD

**Issue by djindjic** [microsoft/vscode#130539]
Issue Type: <b>Bug</b>

no steps, I have just seen warning message.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:11:51.081Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 35d30834-9ee1-4d64-9e1d-bc74a888ab48|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
todo-tree|Gru|0.0.213
vscode-yaml|red|0.22.0
autoimport|ste|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by djindjic** [comment]
@sandy081 can you refer to original one? I've created this one almost automatically through some vs code error form as I remember

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/91286
