### ISSUE TITLE
Expose Run and Debug test to other UI entries?

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#130548]
Hi @connor4312,

Bellow are some rough ideas came up in my mind, would like to hear your thoughts on them :)

The new testing API provide functionality like `Run/Debug tests in current file`, `Run/Debug tests at cursor`. Since now they can only be triggered from the Command Palette, which users might even do not know their existence. I'm thinking if it's possible to promote them in different UI entries?

- Put `Run/Debug tests in current file` to `editor/title/run` when current file has tests? 
  - There is a separate discussion in https://github.com/microsoft/vscode-java-debug/issues/1037
- Put `Run/Debug tests at cursor` in to the context menu, like when debugging we have `run to cursor`:
  ![image](https://user-images.githubusercontent.com/6193897/128973796-e151c08f-f116-42c6-b1c1-da8e560e3103.png)

**Comment by weinand** [comment]
Yes, all "test xxx" commands that work on the active editor contents (and not a selection within that), should live in the Run/Debug dropdown item as well. But these commands must be contributed in a very selective way (with a "when" context condition) so that the dropdown does not get crowded.

And having selection based "test xxx" commands in the context menu are a no-brainer, right?

**Comment by jdneo** [comment]
> And having selection based "test xxx" commands in the context menu are a no-brainer, right?

Maybe @connor4312 can answer this question. Currently the extension which adopts the new testing API will provides test items to VS Code (containing URI and range if they have). So I guess from VS Code side, it's possible to have selection based `test xxx` commands?

**Comment by connor4312** [comment]
Yea, haven't prioritized it yet though, should be pretty simple

**Comment by weinand** [comment]
@connor4312 maybe a "help wanted"?

**Comment by raymbartlett** [comment]
If this is still open and unresolved, I'd like to give it a shot.

**Comment by connor4312** [comment]
Sure!

**Comment by weartist** [comment]
Can I also add pr for this question? There seems to be no progress

**Comment by weartist** [comment]
> Sure, PR's welcome, just haven't gotten to this

I'll try to fix it
