### ISSUE TITLE
Alt-tabbing to another application underlines the first letter of items in the menu bar (file, edit etc)

### ISSUE THREAD

**Issue by jellyberg2** [Microsoft/vscode#1305]
Minor niggle of mine :)

Other applications such as Windows Explorer do not display the keyboard shortcut guides when the user alt-tabs, it would be more consistent if VS Code did the same.

**Comment by pali88** [comment]
H

**Comment by dbaeumer** [comment]
Might be Electron reality.

@bpasero

**Comment by hashhar** [comment]
I would like to add some information regarding this:

Windows Explorer does this too but there seems to be a timeout of about 500ms to 800ms (I screengrabbed a video :stuck_out_tongue: ) before the tooltips show up. Maybe you could also implement a similar timeout?

**Comment by bpasero** [comment]
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by valtism** [comment]
This is not fixed on Windows 10 with version 1.14.2
