### ISSUE TITLE
Test UI: Sort/Filter by Duration

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130538]
It would be ideal if the Testing user interface would allow to sort/filter based on duration.

**Use case:** I have a large number of tests in my project and they're slow, I want to sort by duration to identify long running tests.

![image](https://user-images.githubusercontent.com/2074089/128965722-4bb2e552-116e-4b8d-8c64-d04d004626ed.png)

**Comment by ThakurKarthik** [comment]
I want to work on this @connor4312 shall I give it a try ?

**Comment by ThakurKarthik** [comment]
Can I get a little help here ? I think I am not able to find the UI in the app. Is this screen capture same as above ? (Left panel)
![Screenshot from 2021-08-15 18-45-10](https://user-images.githubusercontent.com/26309938/129479864-9a99feb4-f7e0-4cb5-aefe-272d054010e8.png)
I made two tests locally, but I am not seeing the time it took to run the tests ?

**Comment by has12zen** [comment]
The 40th Fibonacci number is  63245986
either change the toEqual to match that or 
check for fib 12
--

**Comment by connor4312** [comment]
You'll need to use `testing.useNativeTesting: true` to make the Test Explorer use the native experience.

**Comment by DivonilLiquid** [comment]
Hey admin, i have just started my open source contribution journey. Can you assign this task to me? so that i can start working on it.

**Comment by connor4312** [comment]
Feel free to submit a PR

**Comment by san-coding** [comment]
Hey Conor, can I work on this issue

**Comment by san-coding** [comment]
@connor4312 , I  found that following changes will be needed

1.  adding a class `TestingSortByDurationAction` to [src/vs/workbench/contrib/testing/browser/testExplorerActions.ts](https://github.com/microsoft/vscode/blob/5da4d93f579f3fadbaf835d79dc47d54c0d6b6b4/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts)
2.  adding `byDuration='duration'` to 
`export const enum TestExplorerViewSorting {
	ByLocation = 'location',
	ByStatus = 'status',
}
`
inside the file [src/vs/workbench/contrib/testing/common/constants.ts](https://github.com/microsoft/vscode/blob/cfc48e81aae077197142e026d8a3294c17866328/src/vs/workbench/contrib/testing/common/constants.ts)

### What other files need to be changed and what all changes need to be made, please guide/help me , I am new to open source

**Comment by connor4312** [comment]
The TestExplorerView is where it happens. You can do a "find all references" on `TestExplorerViewSorting` and that'll give you a good indication of places to update

**Comment by san-coding** [comment]
There is such a line for sort ByLocation , but not there for ByStatus , why is it so 
https://github.com/microsoft/vscode/blob/0040f1577d0918b001ccbf6562d864abb4d6976b/src/vs/workbench/contrib/testing/common/testingContextKeys.ts#L29

**Comment by smcenlly** [comment]
Have added a pull request for this: https://github.com/microsoft/vscode/pull/132097
