### ISSUE TITLE
A task's terminal view is unfocusable with commands until clicked into the terminal area

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#130570]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
```

When a task with a definition `presentation.reveal === 'silent' || 'never'` is started in a workspace the terminal tab containing the task cannot be properly focused using commands, a mouse click into the task's terminal area is required in order to restore "focusability". Video demonstrating the issue is attached.

Steps to Reproduce:

1. In a fresh workspace, start a regular Terminal
2. Focus any text editor
3. Use `View: Toggle Terminal` command to focus the regular terminal - this should work as expected and you should be able to write into the terminal prompt
4. Focus the editor again
5. Start a task defined in `.vscode/tasks.json` that has `presentation: { reveal: 'never' }` configuration option.
6. Use `View: Toggle Terminal` command to focus the regular terminal
7. Use `Terminal: Focus Next Terminal Group` to get to the task's terminal tab
8. Observe your focus is still in the text editor area, not in the terminal tab
9. Observe `View: Toggle Terminal` no longer toggles the terminal pane
10. Mouse-click into the task's terminal area in order to restore full functionality

A mouse click is required every time the task is started again. This always breaks my flow especially because I cannot close the terminal tab after I look at the task's output - I need to reach the mouse and click into the terminal in order to close the pane.

https://user-images.githubusercontent.com/3058150/129026110-fed9dcc9-c9a2-4475-8390-a37e867b60b7.mov

**Comment by robertrossmann** [comment]
Thanks bot, I will work on improving my issue searching skills! 👍 I do think, however, that this issue has a good repro steps and a nice video, maybe that counts. 😄 ❤️

**Comment by robertrossmann** [comment]
I can confirm this is now working as expected. Thanks for the fix! ❤️ 🎉 

```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

**Comment by Tyriar** [comment]
Thanks for following up
