### ISSUE TITLE
Supporting "when" clause in contributes.configuration

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#130500]
Is there currently a way to make the contributes.configuration conditional? Live Share is merging its web and desktop extension into one package.json. There are features that are currently only supported in desktop. I tried using the "when" clause but that doesn't appear to work in contributes.configuration.

**Comment by m-paternostro** [comment]
@jramsay I also would like to define `when` clauses on configurations, so I've opened a feature request for it: https://github.com/microsoft/vscode/issues/167843

Please consider giving it a thumbs up if you are still interested on this feature ;-)
