### ISSUE TITLE
Go To Panel Find Folders

### ISSUE THREAD

**Issue by thatryan** [microsoft/vscode#130507]
I have searched a lot and seen several issue that are close, but nothing solving this.
When hitting cmd+p to open the goto panel, the search for files is great, but if my project has 100 directories it would be very helpful to open a folder I need. Is there a way to add a function to filter by folder instead of files inside folders? 

Example from PHP Storm, opening their "goto" panel and typing in a string followed by a trailing `/` returns **only** folder names, that would be immensely helpful.

Thank you.

**Comment by isidorn** [comment]
Cmd + P supports fuzzy matching so you can just start typing the folder name and we will only show the contents of that folder.

fyi @bpasero if there is something else to add here.
Closing as designed

**Comment by thatryan** [comment]
Right I understand that is how it is designed was just hoping for an option. I don’t always know the name of the file I’m looking for but I know what directory it is in.
