### ISSUE TITLE
C# Grammar has a misplaced token definition in the Tuples

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#130513]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: macOS 11.4

I have nothing more to describe than these two screenshots. There is a misplacement in the definitions:

<img width="751" alt="Screen Shot 1400-05-19 at 22 53 50" src="https://user-images.githubusercontent.com/2157285/128914743-3a94a7c1-9bc6-41fe-9a04-fdd3c582a641.png">

<img width="694" alt="Screen Shot 1400-05-19 at 22 53 57" src="https://user-images.githubusercontent.com/2157285/128914759-6b45741a-411e-4289-81f3-648ed8e9a6e5.png">

**Comment by alexr00** [comment]
Can you please share a copy/pastable sample that I can use to reproduce the issue?

**Comment by pouyakary** [comment]
Yeah sure:
```c#
var names3 = (First:"Peter", Last: "Parker")
```

**Comment by alexr00** [comment]
Thank you! I've moved the issue overt o https://github.com/dotnet/csharp-tmLanguage since that's where we pull our C# syntax highlighting grammar from: https://github.com/dotnet/csharp-tmLanguage/issues/223

**Comment by pouyakary** [comment]
Thanks !
