### ISSUE TITLE
new terminal options for debugging.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#130518]
there is `internalConsoleOptions` in `launch` configurations options. via set it to "neverOpen" we can prevent from opening debug console.

but some projects doesn't need open terminal on debug starts. there should be `internalTerminalOptions`. here is the options:
"neverOpen"
"openUnfocused"
"alwaysOpen"(Default)

**Comment by weinand** [comment]
Terminals are not controlled by VS Code but by individual debug extensions. Please file this feature request against the debug extension you are using.
