### ISSUE TITLE
First right-click takes about 10s

### ISSUE THREAD

**Issue by ehsanghorbani190** [microsoft/vscode#130509]
Issue Type: <b>Bug</b>

Hi :D 
I've installed manjaro linux 3 months ago, and now i got a weird bug.
when I open a new window of VSCode (not a new tab, a new window) and i right click (anywhere) for the first time, it takes about 10s for menu to appear. after that, the bug is gone and right-clicks are almost instant and ok.
How can i fix this ?

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.10.56-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2486)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|5.69GB (1.85GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8a455267-57ac-4015-846c-ef80e6ff5f12|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
comment-anchors|Exo|1.9.6
php-debug|fel|1.17.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-atom-sass-snippet|glu|0.0.3
css-snippets|joy|1.0.2
php-cs-fixer|jun|0.2.5
fluent-icons|mig|0.0.12
vscode-autoprefixer|mrm|3.0.1
vscode-duplicate|mrm|1.2.1
color-highlight|nau|2.4.0
es6-css-minify|olb|3.3.2
vscode-php-getters-setters|php|1.2.3
vscode-css-navigation|puc|1.10.7
code-snapshot|rob|0.2.1
html5-boilerplate|sid|1.1.1
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you run the command to reload with all extensions disabled?

**Comment by ehsanghorbani190** [comment]
@gjsjohnmurray 
No, it's ok when i reload with extensions disabled.
How can i find out which extension is causing this problem ?

**Comment by rzhao271** [comment]
You can use extension bisect: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
