### ISSUE TITLE
Improve behavior of typescript.preferences.importModuleSpecifier: non-relative

### ISSUE THREAD

**Issue by Avivhdr** [microsoft/vscode#130583]
Currently, with this setting`"typescript.preferences.importModuleSpecifier": "non-relative"` VScode goes to `.tsconfig` --> `baseUrl` or `paths` and look for a match.

I situation that I experience is that I have a few paths in my `path` property and they sometimes overlap.
Example:
```
"baseUrl": ".",
    "paths": {
           "*": ["src/main/*"],
          "utilsFunctions/*": ["src/main/utils/utilsFunctions*"],
      },
```
With this configuration I can import a function from the `utilsFunctions` folder in one of these 2 options:
1. `import { foo } from "src/main/utils/utilsFunctions/functions.ts`
2. `import { foo } from "utilsFunctions/functions.ts`
Both of these import statements will work.

But If I add `foo` in my code without writing the import statement myself, `vscode` will auto-suggest me to import it like option 1 above. In my case, I wanted option 2.

**Requested behavior:**
When using `foo` (without it importing it first), VScode should suggest me both options.

My solution, in this case, was to reverse the order of `paths` like this:
```
    "paths": {
          "utilsFunctions/*": ["src/main/utils/utilsFunctions*"],
           "*": ["src/main/*"],
      },
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) (with a small example project that demonstrates the request)
