### ISSUE TITLE
Truncation in `Refactor Preview` panel

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#130527]
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

This was originally reported against the C/C++ extension here: https://github.com/microsoft/vscode-cpptools/issues/7826

There appears to be some truncation that occurs in the `Refactor Preview` panel.  Repro is fairly simple, but involves using the C/C++ Extension.  Note that the C/C++ Extension does not return the contents of the line replicated in the `Refactor Preview` panel.  It only provides the range to be replaced, what to replace it with, what Icon to use, text for the group label, etc..  The remainder of the line extracted from the original file appears to be coming from VS Code.

Repro code:

```
int foo(void)
{
    int foo = 1; // A much longer line that is not trunacated.
}

int main(void)
{
    foo();
}
```

The repro is to use the Rename feature to change `foo` to `foo2`.

![image](https://user-images.githubusercontent.com/49173979/128946529-42d2e5ef-a2b1-44d4-9793-19180c4ec0a8.png)

**Comment by jrieken** [comment]
code pointer: https://github.com/microsoft/vscode/blob/37c4d4b0a8388543227ac71dbc75ecb257697181/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEditTree.ts#L226

**Comment by weartist** [comment]
> code pointer:
> 
> https://github.com/microsoft/vscode/blob/37c4d4b0a8388543227ac71dbc75ecb257697181/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEditTree.ts#L226

hi, I found that the 'findTokenIndexAtOffset' is calculated from 0, but the range we pass to him is calculated from 1, so we may need to add a -1, both the ‘prefixLen’ and ‘suffixLen’ are required, but the prefixLen is fine without it, because he will continue to look forward, without it it will just be one more loop

**Comment by weartist** [comment]
> code pointer:
> 
> https://github.com/microsoft/vscode/blob/37c4d4b0a8388543227ac71dbc75ecb257697181/src/vs/workbench/contrib/bulkEdit/browser/preview/bulkEditTree.ts#L226

hi, I found that the 'findTokenIndexAtOffset' is calculated from 0, but the range we pass to him is calculated from 1, so we may need to add a -1, both the ‘prefixLen’ and ‘suffixLen’ are required, but the prefixLen is fine without it, when there is only one character, it is only one more loop, and the calculate result of this loop is always 0
