### ISSUE TITLE
Testing API should make gutter indicator behaviour option for a TestItem

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130542]
The VS Code Testing API adds a gutter indicator beside the start line of a test's `TestItem.range`. Feature request is to be able to disable this behavior on an extension-by-extension basis (suggest default is `on`).

We already display gutter indicators and the VS Code indicators overlap and lead to a bad UX (see below).

![image](https://user-images.githubusercontent.com/2074089/128968439-af674ead-4cd7-4fbf-829d-663286a7ad87.png)

**Comment by connor4312** [comment]
The gutter icon is particularly useful over extension icons since it has its clickable and context menu actions. I know you use line-by-line indicators for test status, is there a use you have for gutter icons that isn't covered by testing's native icon? / is the desire to disable the icon mostly a matter of having a consistent look in the gutter?

**Comment by smcenlly** [comment]
> is there a use you have for gutter icons that isn't covered by testing's native icon?

At this stage, our use of the Testing API is planned to be asynchronous and on-demand. This means that we will likely display the gutter icons before the Testing API even knows about tests. 

We also do not want any of the gutter integration when Wallaby is running. Wallaby runs tests a little bit different from other test runners (always, as you type) so the gutter actions and the idea of forcing a test run is foreign and doesn't make sense in our context.

**Comment by connor4312** [comment]
There's a new `testing.gutterEnabled` setting you can use and set automatically.

**Comment by smcenlly** [comment]
Thanks! It's great to have a setting for this. As an extension developer, it feels wrong to automatically adjust a user's settings based on the capabilities of our extension. This is sufficient for us but definitely feels wrong an like there's something missing from the API when we need to do this.

**Comment by connor4312** [comment]
I'm open to consider something formal in the API if we have other consumers who also end up needing this, though so far I haven't heard anything. Wallaby.js is somewhat unique in the features it provides and we generally don't create API if there's only a single consumer/use case for it 🙂
