### ISSUE TITLE
Auto add import statements as part of code completion 

### ISSUE THREAD

**Issue by dcworldwide** [Microsoft/vscode#13058]
- VSCode Version: 1.5.x
- OS Version: Win7

Please auto add import statements as part of code completion. I find that with large class files, having to scroll to the top and write a import statement to be a huge time sink. I must have done this same task a few hundred times now. 

Steps to Reproduce:
1. Create 2 ts files with exported classes
2. In the 2nd class, create an instance of the 1st class. 
3. Expect that an 'import x from y' statement is automatically added, but this isn't the case.

**Comment by waderyan** [comment]
@dcworldwide thank you for your feature request. I have a couple questions. 

How are you imagining this would happen? Would there be a code action lightbulb to click on, much like an experience in Eclipse? 
Is there an editor that does this already that you would want to see VS Code behave like? 

The more details you can provide the better we can zero in on nailing this issue.

**Comment by dcworldwide** [comment]
Thanks @waderyan 

The first UX flow that comes to mind is:

- User starts typing out a class declaration in code. I.e. let x = new MyCl...
- An auto-complete popup above/below the code line appears with class suggestions
- The user could use the mouse or keyboard (up/down + enter) to select a class suggestion, but they shouldn't need to, as the popup should infer the best class definition based on the partially typed class name. I.e. MyC lists MyClass and MyComp, but after typing MyCl, the popup lists only MyClass1 and therefore that item is auto-selected. 
- Hitting Enter auto-completes the class definition code line 
- The import is auto-added to the header. I don't think the scroll position should change. 

I'm sure there are many great solutions...

**Comment by waderyan** [comment]
@dcworldwide thank you for sharing. I believe this is a valid feature request and one I would personally like to see. 

@bowdenk7 do you have an issue tracking this feature request on TypeScript's side?

**Comment by bowdenk7** [comment]
We have [this issue](https://github.com/Microsoft/TypeScript/issues/2893) tracking the feature and already have work underway in the [unknown identifier imports](https://github.com/Microsoft/TypeScript/tree/unknown_identifier_imports) branch.

**Comment by waderyan** [comment]
@dcworldwide would you mind taking a look at the issue @bowdenk7 posted and confirming that this is what you are looking for?

**Comment by PKief** [comment]
This extension has no auto import but it suggests the right imports and you can simply add the imports by clicking on the suggestion

https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

**Comment by waderyan** [comment]
Work tracked here - https://github.com/Microsoft/TypeScript/issues/2893
