### ISSUE TITLE
Respect trailing comma style when organizing imports

### ISSUE THREAD

**Issue by KyDenZ** [microsoft/vscode#130556]
Does this issue occur when all extensions are disabled?: Yes

An issue has already been created but is closed, impossible to relaunch the subject. It doesn't seem to me to be because of an extension: https://github.com/microsoft/vscode/issues/98123

- VS Code Version: 1.59.0
- OS Version: MacOS 11.5.1

Steps to Reproduce:

1. Disable all prettier extensions, eslint, editorConfig...
2. Activate organize Imports in the visual code settings
3. Have an import on several lines with a comma on the last line

After applying organize Imports, the last comma is removed. If we deactivate organizeImports the comma remains

**Comment by mjbvz** [comment]
The linked issue was closed as `extension candidate` because we leave more advanced formatting options like this up to extensions: https://github.com/microsoft/vscode/issues/98123#issuecomment-630530364

This is still the case
