### ISSUE TITLE
prefix argument to quickOpen command doesn't work.

### ISSUE THREAD

**Issue by wujunchuan** [microsoft/vscode#130549]
# prefix argument to Quickopen command doesn't work.

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.0-insider
- OS Version: Darwin arm64 20.5.0

## Description

Add an argument (prefix) to "workbench.action.quickOpen" command.

According the [document - Key binding command arguments](https://code.visualstudio.com/updates/v1_8#_key-binding-command-arguments) and [build-in commands arguments](https://code.visualstudio.com/api/references/commands#:~:text=workbench.action.quickOpen%20-%20Quick%20access).

But it doesn't work correct until I change `args: {prefix: string}` to `args: string`.

```js
{
    "key": "cmd+shift+a",
    "command": "workbench.action.quickOpen",
    // "args": "edt active", // correct
    "args": { "prefix": "edt active " } // type warn, and will not work
}
```

## conclusion

Please update misleading documentation in [build-in commands arguments](https://code.visualstudio.com/api/references/commands#:~:text=workbench.action.quickOpen%20-%20Quick%20access)

**Comment by TylerLeonhardt** [comment]
I see where you're getting at... for this I think the idea is that `args` follows the [executeCommand](https://code.visualstudio.com/api/references/vscode-api#:~:text=FUNCTIONS-,executeCommand%3CT%3E) API where it has an array of arguments... or just the single argument if it only takes one. You don't need to name them.

**Comment by bpasero** [comment]
I documented this in https://github.com/microsoft/vscode-docs/commit/9362287ef15abf5696dcef8ae8d98801eb302d53 but think we cannot just change this given people already use it.
