### ISSUE TITLE
Delete IntelliSense suggestions

### ISSUE THREAD

**Issue by Manubi** [microsoft/vscode#130605]
Hi,
I'd like the possibility to delete/disable certain autocomplete suggestions from IntelliSense.

I hate it when I write `class` and it always get the 
```
class name {
                constructor(parameters) {
                  
                }
              } 
```
suggestion instead of just the `className`. I didn't write a class for years...

Thank you for your help and work!

**Comment by IllusionMH** [comment]
You can open settings editor and there select Test Editor > Suggestions from ToC or search by `suggest`.
There are a lot of options, however in your case it looks like snippet suggestiosn.
You should tune `editor.snippetSuggestions` to your preference.

**Comment by Manubi** [comment]
Thanks for the quick answer!

![CleanShot 2021-08-11 at 23 40 54](https://user-images.githubusercontent.com/20935138/129107188-56a4e001-6925-49a2-b1b6-3d062884fad6.png)

Is this a snippetSuggestion?

**Comment by IllusionMH** [comment]
Yep https://github.com/microsoft/vscode/blob/main/extensions/typescript-basics/snippets/typescript.code-snippets#L15-L25

`"editor.snippetSuggestions": "bottom"` coupled with `"terminal.integrated.gpuAcceleration": "first"` (if needed) allows to keep snippets in suggestions and access with arrow up key, but prevent them from interfering with regular suggestions.

**Comment by Manubi** [comment]
Thanks! You made my day. 💯
