### ISSUE TITLE
Codespace: Terminal icons are off

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130646]
Seeing this in latest Chrome in Codespace using insiders:

![recording](https://user-images.githubusercontent.com/900690/129142462-06e5446f-8965-4763-af3d-4108f0604746.gif)

**Comment by meganrogge** [comment]
![chrome](https://user-images.githubusercontent.com/29464607/129985880-ab52381c-7f01-459d-b790-4c603abf0201.PNG)
not seeing this, let me know if you have additional info that will help me to repro it

**Comment by meganrogge** [comment]
yep seeing this when it's in the min width on any browser when switching between tabs

**Comment by Tyriar** [comment]
Happens in Edge too, but not running out of sources

**Comment by Tyriar** [comment]
This is a codespaces css scoping issue

**Comment by Tyriar** [comment]
Moving to that repo

**Comment by bpasero** [comment]
Still opened, moving to September.
