### ISSUE TITLE
Terminal settings point at invalid anchor on website

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#130618]
The settings point at https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

Should be https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles

**Comment by AiverReaver** [comment]
can i work in this issue

**Comment by Tyriar** [comment]
@AiverReaver sure 👍

**Comment by AiverReaver** [comment]
@Tyriar  Thanks, I started looking at the vs code a few days ago. can you help me a little bit? how to open vscode user guide link from settings. Like I opened the settings from the file->preferences->settings->terminal but I didn't find any way to open that link in vs code.

**Comment by Tyriar** [comment]
These settings are a little special as they're deprecated so they won't show up in the UI. If you switch to the JSON file you can add the setting manually like this and then hover it:
![image](https://user-images.githubusercontent.com/2193314/129370195-f04629e0-e212-46ee-bed2-433b360252e9.png)

![image](https://user-images.githubusercontent.com/2193314/129370098-f64563b3-7351-4cd9-ae47-89f82fe934d7.png)
