### ISSUE TITLE
Internal terminal buffersize too small

### ISSUE THREAD

**Issue by drmaex** [Microsoft/vscode#13064]
- VSCode Version: 1.5.3
- OS Version: Windows 7

Although the buffersize of "C:\WINDOWS\system32\cmd.exe" is set to 5000 the internal terminal does not use it. It is not possible to scroll up to the beginning of the produced output when its to long. A possiblity to control the buffersize in the settings-file would be nice (I couldn't find it)

Steps to Reproduce:
1.  Create a long output  >700 lines
2. Try to read the beginning of the output

**Comment by Tyriar** [comment]
To verifier: xterm.js currently does this by halving the buffer when the scrollback value is reached, as such there should be from `scrollback/2` to `scrollback` lines allowed above the viewport when the limit has been reached.
