### ISSUE TITLE
Unable to save Github Credentials on openSUSE Tumbleweed.

### ISSUE THREAD

**Issue by mengxinayan** [microsoft/vscode#130640]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: openSUSE Tumbleweed 20210810
- Linux Kernel Version: Linux Tumbleweed 5.13.8-1-default x86_64
- Desktop Environment and Version: KDE Plasma Version 5.22.4

Steps to Reproduce:

1. Click the person icon in the bottom right,
2. Click "Sign in to Settings Sync",
3. Select "Sign in with GitHub",
4. Browser auto opens, does Oauth flow, and returns to VS Code,
5. Error message appears: `Writing login information to the keychain failed with error 'The name org.freedesktop.secrets was not provided by any .service files'`.

Note that the Github account will be logged in, but when I close current vscode window or open a new vscode window, the login will be invalid, and I need re-login again.

I tried this solution https://github.com/microsoft/vscode/issues/120392#issuecomment-814210643, but it doesn't work :(.

Thanks.

**Comment by TylerLeonhardt** [comment]
Have you looked at the troubleshooting guide here?
https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

Do you have `gnome-keyring` installed?

**Comment by mengxinayan** [comment]
Thank you. It works well after I tried to install `gnome-keyring`. 

I didn't try before because I thought `gnome-keyring` is a software/component in Gnome desktop, while my desktop environment is KDE. But the fact tells that I am wrong.

Thanks.

**Comment by TylerLeonhardt** [comment]
Glad it's working for you!
