### ISSUE TITLE
Unable to click the "Lean more" link in extension tooltips

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#130687]
I don't know if this is the right repo for this, but if I press `.` in a GitHub repo to open it in github.dev, the Dart extension is unavailable. I suspect it's because it doesn't support virtual workspaces, but the "Learn More" link is hard to click because the tooltip vanishes when you try to move the mouse to it:

![Aug-12-2021 15-09-03](https://user-images.githubusercontent.com/1078012/129211837-06697328-a9cf-40a9-aa85-645632b3d6b2.gif)

I'm using latest Chrome stable on macOS.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/128998
