### ISSUE TITLE
letter c 

### ISSUE THREAD

**Issue by sangu-143** [microsoft/vscode#130639]
Issue Type: <b>Bug</b>

when i type  c in my visual studio code i am not able to type but 
i am able to type c in other platform such as notepad

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (1.64GB free)|
|Process Argv|--crash-reporter-id 1e0d9bc7-e362-46b7-a386-78474f87f219|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.3.2
c-cpp-compile-run|dan|1.0.14
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
copilot|Git|1.3.2335
vscode-pull-request-github|Git|0.29.1
CppSnippets|har|0.0.15
rest-client|hum|0.24.5
quicktemplate-vscode|jdi|1.1.0
better-cpp-syntax|jef|1.15.6
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
material-icon-theme|PKi|4.9.0
tabnine-vscode|Tab|3.4.22
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30350414

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by CodeCrazy-ywt** [comment]
@sangu-143 Screenshot please

**Comment by rzhao271** [comment]
\gifPlease

**Comment by rzhao271** [comment]
Also, use Extension Bisect to check if it's caused by an extension: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
