### ISSUE TITLE
Extra character appear when pasting multi line commands in wsl terminal

### ISSUE THREAD

**Issue by lijian12345** [microsoft/vscode#130657]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. paste such multi line commands

> docker run -dp 3000:3000 \
   -w /app -v "$(pwd):/app" \
   --network todo-app \
   -e MYSQL_HOST=mysql \
   -e MYSQL_USER=root \
   -e MYSQL_PASSWORD=secret \
   -e MYSQL_DB=todos \
   node:12-alpine \
   sh -c "yarn install && yarn run dev"

then the commands shows in vs code terminal(with an extra ~ character in tail):
![image](https://user-images.githubusercontent.com/26590220/129159122-0449dd4e-7f35-413f-9fbd-d8a09861352d.png)

and it shows in windows terminal:
![image](https://user-images.githubusercontent.com/26590220/129159277-1927f958-a7f7-4bc8-a010-06bdce54e188.png)

Well, i don't know how the '~' added.

**Comment by meganrogge** [comment]
I can't reproduce this. Could you `toggle escape sequence logging` and provide me with the logs?

**Comment by lijian12345** [comment]
> I can't reproduce this. Could you `toggle escape sequence logging` and provide me with the logs?

Well, now this situation is not existed, thank you!
