### ISSUE TITLE
Repl: cursor looks off in repl compared to editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13067]
On my Mac OS the blinking cursor in the repl looks larger and off by 1px compared to the editor. 

![screen shot 2016-09-30 at 11 42 18](https://cloud.githubusercontent.com/assets/900690/18987661/f996157a-8702-11e6-9a71-5954b30947f4.png)

Editor:

![image](https://cloud.githubusercontent.com/assets/900690/18987668/020c42c4-8703-11e6-92f9-ae0f8b762c02.png)

**Comment by roblourens** [comment]
It still looks off. It's like it's missing the top left pixel. It's only when it's on the first column in that input box.

![image](https://cloud.githubusercontent.com/assets/323878/19749753/5c96a5e8-9ba0-11e6-94ad-e3e937706eef.png)

**Comment by bpasero** [comment]
Yeah still repros for me too.

**Comment by isidorn** [comment]
The original fix was to change the cursor size. And yes I agree that the top left pixel when at start is missing but this is not cruical -> pushing out of october

**Comment by joaomoreno** [comment]
ping @alexandrudima

**Comment by alexandrudima** [comment]
well... where should I put the textarea :)

**Comment by joaomoreno** [comment]
Opacity doesn't work? Also, top right corner is much less likely to have content than top left corner.

**Comment by alexandrudima** [comment]
This has been fixed in the meantime 
![image](https://user-images.githubusercontent.com/5047891/30912884-78b4e54a-a38e-11e7-9377-8a8bb0a86de3.png)
