### ISSUE TITLE
issue with "go to implementation" and "go to definition" 

### ISSUE THREAD

**Issue by Ariv6** [microsoft/vscode#130667]
Issue Type: <b>Bug</b>

I am unable to traverse through my JS functions using "go to implementation" or "go to definition" 

when I mouse over a function name I can't see function references in the popup but only "any" 
⌘ + click on function name has no effect.

Please help me fix my problem

Regards,
Arivarasan Ramasamy

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 38c7f79a-a04c-4cfa-9300-bd857709fc17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets|Bin|2.0.0
vscode-eslint|dba|2.1.23
jquerysnippets|don|0.0.1
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
gobystrok|GoB|0.0.1
ember-snippets|Hri|1.0.0
Angular2|joh|12.0.0
vscode-docker|ms-|1.15.0
vuejs-extension-pack|mub|1.2.1
vetur|oct|0.34.1
vue-vscode-snippets|sdr|2.2.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.14
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by mjbvz** [comment]
Please share some example code that demonstrates this issue

**Comment by snys98** [comment]
Im not sure if it's the same problem, but this also happens to *.graphql files, using "go to definition".

<img width="595" alt="d09baeb8aee9c349528837c4956e8f0" src="https://user-images.githubusercontent.com/11873100/129474687-0071a9da-7344-4407-8d8f-cc837f98a82e.png">

it seems that the reference model got a wrong uri of the definition file.

<img width="1393" alt="9119aa39ac17929d9a1fbe995920d3e" src="https://user-images.githubusercontent.com/11873100/129474676-96267abd-3e5f-4425-baee-0ee6d92ebb7b.png">

besides, the reference count is 1, but code goes to the case of 0. I'm not sure if this is a problem of sourcemap.
![image](https://user-images.githubusercontent.com/11873100/129474800-2f0e3ac0-f3cc-48c1-bb0e-214000249d6f.png)

thanks.

**Comment by mjbvz** [comment]
@snys98 Yes please file that against the graphql extension

**Comment by mjbvz** [comment]
Closing as we need more information from the original poster to investigate
