### ISSUE TITLE
Notebook folding processes  '#' signs in code blocks when they should be ignored 

### ISSUE THREAD

**Issue by jhoneill** [microsoft/vscode#130669]
Does this issue occur when all extensions are disabled?:  n/a

- VS Code Version:
 Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
- OS Version:  Windows_NT x64 10.0.19043

**Steps to Reproduce:**
_In the screen shots  I have set  notebook.showFoldingControls to "Always" for clarity_

1. Create and "run" 4 markdown cells  In the first put   
   `## first heading`   
   `text 1`
   In the second put   
   `  ``` ` 
   `code`
   ` ``` `
   In the Third put   
   `## second heading`   
   `text 2`
   In the fourth put   
   `text 3`
 
2. Observe where the fold chevrons appear   
![image](https://user-images.githubusercontent.com/16209593/129185112-1aef2937-f4c8-4e6e-92f9-4810821123a3.png)

3. Note that clicking the chevron next to first heading hides "code" but not "second heading"  
![image](https://user-images.githubusercontent.com/16209593/129185227-81093757-e1ab-41b6-ac0b-36184898c25d.png)

4.  Insert a # to change the second cell to `#code` and observe where the chevrons now appear `#code` is treated as a top level heading  - note that in markdown the # signs must to be followed by a space to denote heading levels, and  this example has none.   
![image](https://user-images.githubusercontent.com/16209593/129185667-0fd4bcbc-1dc0-411d-9e70-015507c661de.png)

5.  Note that clicking the chevron next to `#code` now hides "second heading" 
![image](https://user-images.githubusercontent.com/16209593/129187455-3fb5d29a-8c00-4fdc-b576-d8eed9bca391.png)

6. (Optional) Change `#code`  to `###code`  Note that it is treated as a level 3 heading (a chevron will appear if a cell is inserted below it). Change to `   #code` (with preceding spaces) and note it is no longer treated as a heading marker. 

7.  (Optional) Move the code block with a single hash into the first markdown cell and note that it behaves as level 1 heading cell. 

**Conclusion** The # signs at the start of a line in a code block are being treated as heading-level X markers. `\#code ` is correctly ignored, and so is  
``` 
`#code` 
```
**Suggestion** folding should look for a space after `# ` and ignore any hashes wrapped in back quotes 

**Work round** Avoid putting # as the first character in a script block (e.g. for PowerShell comments use many # signs for a comment, use <#  ... #>  to create a block comment or indent the comment)

**Comment by rebornix** [comment]
Tweaked the detection a bit to ensure that only `#` followed by a space will be treated as headers.

**Comment by rzhao271** [comment]
Verified that the behaviour follows https://github.com/microsoft/vscode/issues/130669#issuecomment-960299515.

A warning that the following will still cause a chevron to occur:
<pre>
```
# code
```
</pre>
