### ISSUE TITLE
Notebook Output Cell Dropdown under Mimetype Selector

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#130699]
![image](https://user-images.githubusercontent.com/6561887/129241242-ba4b0620-1827-441e-81b3-6580c2c16de5.png)

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/129603136-19f23593-02d7-4479-b75a-7bc3ab430fd8.png)

**Comment by roblourens** [comment]
I guess I'm not sure how we set a z-index on the custom context menu, is that possible?

**Comment by rebornix** [comment]
Looked into similar issue with @sbatten before, the trick is rendering the dropdown as an overflow element (other than a child of the toolbar).
