### ISSUE TITLE
Test UI: Provide the ability to hide test run history in error peeks

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130648]
As mentioned in a previous issue, our extension is constantly running tests in the background, as the user types. As a result, in a given minute, it would not be unusual for there to be 20-30+ test runs (depending on typing speed, lag between keystrokes, etc). For our product, this is efficient from a performance perspective but makes the idea of showing historic test results confusing/irrelevant.

![image](https://user-images.githubusercontent.com/2074089/129147034-bd7c90a6-306e-4608-b376-769722357609.png)

Ideally, we would like to be able to turn this off at an extension level. I can see a user setting for this would be ideal for all extensions but I can also see it might be desirable for some test runners, and not for others.

**Comment by connor4312** [comment]
As part of https://github.com/microsoft/vscode/issues/130516, we want to add the ability to toggle this tree view https://github.com/microsoft/vscode/issues/130516

**Comment by connor4312** [comment]
Added this a few months ago (by default via the keybinding ctrl/cmd+h)
