### ISSUE TITLE
EditorLayout window grows after File Explorer closes so not expanding automatically on focus

### ISSUE THREAD

**Issue by mirel-spr** [microsoft/vscode#130650]
Issue Type: **Bug**

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open VSCode and collapse File Explorer if open
2. Open two files in vertical layout
3. Resize one file to smallest possible width
4. Open File Explorer
5. Focus on smaller file (expands as expected)
6. Close File Explorer
7. Focus on smaller file
8. File is no longer at smallest possible width so doesn't expand on focus

Tested in VS Code with info included below.
Also tested in VS Code Insiders.

Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by isidorn** [comment]
Sounds like grid layout smartness. Forwarding to @sbatten

**Comment by sbatten** [comment]
duplicate #70083
