### ISSUE TITLE
Make search feature behavior consistent

### ISSUE THREAD

**Issue by zoharl3** [microsoft/vscode#130635]
There are various search features, such:
1. A simple text search (ctrl+f)
2. A symbol search.

In the first, you write a word, and it homes in on the first occurrence, where you can:
- Press Enter to go to the next occurrence. 
- ESC leaves you where you are and closes the search.

In the second, confusingly:
- Enter leaves you where you are.
- ESC jumps back to where you've been.

**Comment by roblourens** [comment]
I think that this is sort of just due to the UX of the quick pick control that symbol search uses. "enter" to accept, "escape" to cancel. I see the annoyance with this difference, but I don't really think it can be resolved.

**Comment by zoharl3** [comment]
Maybe could add a checkbox to settings to behave consistently or like visual studio.
