### ISSUE TITLE
Test UI: Inline Peek outside of running tests

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130649]
I really like the new inline error display and can see the potential for using this outside of testing context. Are there any plans to support this outside of running tests? I also think it would be nice to have an `error`, `info`, `warn` style border where you may want to display other message types in between lines of code.

**Comment by connor4312** [comment]
The testing peek prompted a discussion around alignment, check out https://github.com/microsoft/vscode/issues/130516 🙂
