### ISSUE TITLE
Statusbar Connect Icon same width as activity bar

### ISSUE THREAD

**Issue by DominicVonk** [microsoft/vscode#130683]
Statusbar Connect Icon same width as activity bar

**Comment by sbatten** [comment]
@DominicVonk Thanks for the feature request, however due to the variance in size of this component, I do not believe we want to align these widths

**Comment by DominicVonk** [comment]
Hi, It only had a min width, so the inactive state would be the same width of the activity bar, I checked it also with a connected window, and it sizes perfectly.
