### ISSUE TITLE
the font of code in notebook-markdown

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#130647]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.60.0-insider (system setup)
提交: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
日期: 2021-08-11T05:15:24.598Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393
* text
![image](https://user-images.githubusercontent.com/1876302/129142503-0fd24681-f437-4fc3-bf7c-e8f056244e99.png)

* view
![image](https://user-images.githubusercontent.com/1876302/129142507-58dd221a-fd30-45e2-9b05-f62ce9c5a213.png)

please render it like markdown preview
* markdown preview
![image](https://user-images.githubusercontent.com/1876302/129142698-9c480b61-575e-44fc-a814-129cd251584d.png)

**Comment by danila-grobov** [comment]
@mjbvz Hello, I would like to work on this issue. This is my first time contributing, could you give any pointers? Where should I start looking to fix this?

**Comment by mjbvz** [comment]
@danila-grobov The css used for markdown is defined here: https://github.com/microsoft/vscode/blob/d3ceb35bece3f8ab658fb9006c9161e7a65d36c4/extensions/markdown-language-features/notebook/index.ts#L23

To test changes to this file:

1. Build VS Code normally
1. `cd extensions/markdown-language-features`
2. ` yarn run build-notebook`

**Comment by mjbvz** [comment]
Closing as this has been superseded by #136693 which adds syntax highlighting to these code blocks and also uses the editor font-family

Other tweaks the the rendering are welcome, although I don' think we want to add a background. Jupyter lab doesn't have one and it stands out too much imo in notebooks
