### ISSUE TITLE
Opening a C# file through Unity shows Visual Studio Code frozen with another file open, need to defocus / refocus 

### ISSUE THREAD

**Issue by spajus** [microsoft/vscode#130644]
Issue Type: <b>Bug</b>

Details and reproduction steps are in this video clip:
https://www.twitch.tv/videos/1115785986

I have reproduced this on two different computers (both Windows 10)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.62GB free)|
|Process Argv|--crash-reporter-id f390de25-4b12-4b2b-9c86-8f1db349efa0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.2.6
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.39.0
gitlens|eam|10.2.3
EditorConfig|Edi|0.15.1
todo-tree|Gru|0.0.188
vscode-nuget-package-manager|jmr|1.1.6
csharpfixformat|Leo|0.0.84
rainbow-csv|mec|1.8.1
csharp|ms-|1.23.14
python|ms-|2020.5.86806
remote-wsl|ms-|0.44.2
vscode-unitymeta|PTD|0.0.7
ruby|reb|0.27.0
shader|sle|1.1.4
shader-toy|ste|0.10.15
code-spell-checker|str|1.8.0
unity-tools|Tob|1.2.12
org-mode|too|0.5.0
vscode-lua|tri|0.12.4
sort-lines|Tyr|1.9.0
unity-debug|Uni|3.0.2
vim|vsc|1.18.9
vscode-ruby|win|0.27.0
moonsharp-debug|xan|1.8.3
json|Zai|1.0.4

</details>

**Comment by deepak1556** [comment]
Thanks for the detailed repro steps, this is an issue with occlusion tracker in the runtime.
Please add the following flag `--disable-features=CalculateNativeWinOcclusion` to the vscode launch arguments as a temporary workaround.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/123257
