### ISSUE TITLE
Issue Reporter is insane

### ISSUE THREAD

**Issue by orcmid** [microsoft/vscode#130603]
We have written the needed data into your clipboard because it was too large to send. Please paste.  See what it put on my clipboard.  This what was on my clipboard when I did the "Preview on GitHub"

Issue Type: <b>Bug</b>

((VS Code Issue reporter is ridiculous.  If I provid details it tells me there is too much text and I must provide some text or it fails there too.))

VS Code version: Code - Insiders 1.60.0-insider (7c25c174726ab969db3f99058cdf24bcfae1cfbe, 2021-08-11T05:15:24.598Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (25.74GB free)|
|Process Argv|--crash-reporter-id 58cc4c7a-c48c-4ef1-982e-1036f7b2fc90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30349639
dockerwalkthru:30348713
bridge0723:30350414
javagetstartedt:30350119

```

</details>

**Comment by orcmid** [comment]
@TylerLeonhardt oh I see what you did there.  The triage-bot comment is not very great though.  

Here's what happened.

![VSCode-1 60 0-2021-08-11-1530-insider--ReportIssue](https://user-images.githubusercontent.com/3372580/129112652-c38830fc-355d-4efd-b237-cf6921ad42a7.png)

This was my first-ever use of the Help | Report Issue in the client.  I failed to notice the automatically-provided check marks in the lower left there.  So instead I cancelled and removed my comments and then I was scolded for having no comments.  But I got to GitHu anyhow and posted this issue.  

The whole thing is a minefield for a new re;porter.  I would have made an issue directly, but the new-issue boiler plate \<!-- comment wanted me to try Insider and also then recommended using the Help feature so I did.  I was seriously attempting to apply my beginner mind.  I was more successful at that than I intended :).

**Comment by TylerLeonhardt** [comment]
The problem is, GitHub let's you auto-fill an issue using a query parameter in the url... but some browsers can only have a certain number of characters in that query parameter... so we have to show this warning and put it into your clipboard otherwise the entire content we want to include in the issue won't show up.

Now... one way around it... if you sign in to GitHub for Settings Sync or a GitHub extension, then we can open an issue automatically for you using a different method that would avoid this warning.
