### ISSUE TITLE
Web: node modules no longer load (integration / smoke tests)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130643]
Looking at the logs of our integration and smoke tests I see many errors printed about node modules not loading, e.g.:

Integration Test:
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=130859&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&l=118

Smoke Test:
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=130859&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9&l=24

**Comment by lramos15** [comment]
I'm not sure what's going on here. The server bits are receiving the new `webPackagePaths.js` which is then used to construct the node module paths to load the resources. It should be equivalent to what was there before and `yarn web` seems to work without console errors. Let me know if you have any ideas I'll keep exploring.

**Comment by lramos15** [comment]
\closedWith ba68cfaf3bdd15e09fa84663a3bb8876c86dbf7c
