### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by abbasiusa98** [microsoft/vscode#130670]
its hard to identify active tab on vs code default theme
Please redesign active tab style (put underline of some bright color or something like that), so that we can easily identify active tab without diverting attention.
Thankyou : )

**Comment by misolori** [comment]
Thanks for the feedback, you can try [other themes](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs) that might better suite your preferences or you can add this to your user settings to set a border on the active tab:

```json
"workbench.colorCustomizations": {
    "tab.activeBorder": "#007acc",
  }
```

**Comment by abbasiusa98** [comment]
Theme name: Dark+

**Comment by abbasiusa98** [comment]
> Thanks for the feedback, you can try [other themes](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs) that might better suite your preferences or you can add this to your user settings to set a border on the active tab:
> 
> ```json
> "workbench.colorCustomizations": {
>     "tab.activeBorder": "#007acc",
>   }
> ```

Thankyou so much it worked for me 👍
