### ISSUE TITLE
Add "Clear Terminal" button like "Output" window and "Debug console" window have

### ISSUE THREAD

**Issue by zeroxia** [microsoft/vscode#130636]
I found this inconsistent, and not convenient:

Inside the terminal window, I use PowerShell on Windows, if I enter "`cls`", the terminal window content is not actually cleared, it just places the prompt at the top window.

I have to assign "`Ctrl+K, Ctrl+K`" to do `workbench.action.terminal.clear` to actually clear the terminal content. Otherwise each time test is run, the output appends to the terminal, making it distracting to check the output.

Debug console has the "Clear console" button:
![Debug console](https://i.imgur.com/t2KSxMW.png)

Output window has the "Clear Output" button:
![Output window](https://i.imgur.com/n3EA7y6.png)

Terminal window has only the "Kill" button, which I often accidentally click it expecting it clears the terminal content...

![Terminal window kill button](https://i.imgur.com/OeudGRl.png)

Thanks!

**Comment by igorskyflyer** [comment]
#130190

**Comment by igorskyflyer** [comment]
microsoft/vscode#130190

**Comment by igorskyflyer** [comment]
Related to #130190.
