### ISSUE TITLE
Ctrl+Z will delete the whole cell even when the focus is in the cell

### ISSUE THREAD

**Issue by hainingpan** [microsoft/vscode#130607]
## Environment data

-   VS Code version: 1.60.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2025984474
-   Python Extension version (available under the Extensions sidebar): v2021.1117361286
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 21H1 19043.1151
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | Local

## Expected behaviour
When typing in the cell, "undo" should delete the text being typed just now.
## Actual behaviour
However, when I type ctrl-z, the whole cell is deleted.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a new cell, type something. With the focus inside the cell, press ctrl-z. The whole cell is deleted. See the GIF below, the second cell is gone after pressing 'ctrl-z'.
![vscode_jupyter_ctrl_z](https://user-images.githubusercontent.com/22186947/129085988-8e403a01-2d00-49e9-a014-7fa4b0a3e05c.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-08-11 14:51:24: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
```

</p>
</details>

**Comment by rebornix** [comment]
@hainingpan can you check if you have `notebook.undoRedoPerCell` in your user setting? I'm currently not able to reproduce this issue.

**Comment by Alaboudi1** [comment]
This bug is really bad. lost my work because of it :(
