### ISSUE TITLE
OSS build 100% CPU usage on macOS Big Sur

### ISSUE THREAD

**Issue by award999** [microsoft/vscode#130600]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: OSS 1.59
- OS Version: macOS 11.4

Steps to Reproduce:

1. Fresh clone of "vscode" repo
2. Checkout origin/release/1.59
2. Build the application: yarn && yarn gulp vscode-darwin-x64-min
3. Open ../VSCode-darwin-x64/Code - OSS.app without any extensions installed or workspace opened
4. Open the Process Explorer
5. Notice how top level "code main" stays hovered around 90-100% CPU usage

Some other things to note:

1. Didn't see on Catalina, started seeing on Big Sur
2. Downloading stable 1.59 or insiders build is fine, only happens when building OSS product locally
3. Building this way had worked fine for 1.54, only saw after updating to 1.59. I did a git bisect and found this was introduced with 3fb483e7fff42559b5f93e8aa92d0354021ee5ff when VSCode moved to electron 12
4. Using codesign to signed the .app does not seem to help

Should "yarn && yarn gulp vscode-darwin-x64-min" build properly or are there more setup steps? It is weird that the official MS build is fine, but not a local build from a fresh clone.

**Comment by award999** [comment]
Is this maybe related to https://github.com/electron/electron/issues/26143?

**Comment by award999** [comment]
Confirmed that was in fact the issue. Is it not possible for the version of Electron that VSCode is using to be made available for OSS builds?

**Comment by deepak1556** [comment]
Closing as upstream issue has been resolved.
