### ISSUE TITLE
Test UI: Ability to contribute to context menu commands

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130627]
As a VS Code API developer, I would like to be able to contribute to the VS Code context menu commands in the test UI (e.g. see `Hide Test` shown below):

![image](https://user-images.githubusercontent.com/2074089/129125571-d985d27e-a99a-4ef7-ad18-76bfc455b86b.png)

Ideally I want to be able to show/hide commands for each individual TestItem. Some examples of menu items we would want to contribute:

* Jump to Error Source
* Add to Exclusive Test Run
* Add to Filter
* Remove from Filter

I don't imagine the contribution points/menu names would be fixed across all API contributors. For example, I can imagine some other more complex scenarios, for example `Open last CI Run Result`.

**Comment by connor4312** [comment]
You can do this via the `testing/item/context` menu contribution point. The `testId`, `controllerId`, and other keys indicating runnability are exposed

https://github.com/microsoft/vscode/blob/b4aa5aee5712680250b7f23583675ab47551b95e/src/vs/workbench/contrib/testing/browser/explorerProjections/testItemContextOverlay.ts#L19-L22

**Comment by smcenlly** [comment]
That's awesome, thanks. Maybe I missed that in the docs. If not, would be nice to include...

**Comment by smcenlly** [comment]
FYI - I have added two pull requests to reference `testing/item/context` menu contribution point:

- https://github.com/microsoft/vscode-docs/pull/4757
- https://github.com/microsoft/vscode-docs/pull/4758

**Comment by connor4312** [comment]
Thanks for the PRs!
