### ISSUE TITLE
Test welcome view not always shown

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#130696]
Does this issue occur when all extensions are disabled?:No

- VS Code Version: 1.60.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19043
Commit: 1c445fe4c7c540d323a206f2f7cb8df9aa99d60e
Date: 2021-08-10T23:41:24.812Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

Steps to Reproduce:

1. Install insiders version of the python extension (download here https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix)
1. Create a folder with no tests configured for python, follow this folder structure:
```
project-root
|- .vscode
|  |- settings.json
|- tests
|  |- test_repro.py
|- somemodule.py
```
2. Use following content for the test_repro.py
```python
import unittest

class TestSomething(unittest.TestCase):
    def test_this(self):
        pass
```
3. Open folder in VS Code, and open a python file.
4. At this point No-tests are configured you should see the Welcome View in the test for python.
5. Click on `Configure Python Tests` or run `Python: Configure Tests` command from the command pallet.
    1. Select `unittest`
    2. Folder `tests`
    3. Pattern `test_*.py` 
6. A test should show up in the test view.
7. Run it.
8. Delete settings.json and Reload.
9. We should be back in the same state as step 4. but we don't see welcome view. 

I have verified on the `Python extension` side that there are no items in the TestController. Also, I noticed that if I add an item and remove it, the welcome view shows up. Also, the above is not a 100% repro, it happens often but not always.

**Comment by karthiknadig** [comment]
This is what I see when I debug (as you can see there are no items in the test controller:
![image](https://user-images.githubusercontent.com/3840081/129273420-dd083fa3-8452-471f-bc52-428d23ba1f8d.png)

**Comment by JacksonKearl** [comment]
cc @connor4312 is this you?

**Comment by connor4312** [comment]
That me
