### ISSUE TITLE
New crashes on macOS with version 1.59.0

### ISSUE THREAD

**Issue by oscarrutt** [microsoft/vscode#130658]
Issue Type: <b>Bug</b>

I am seeing a new kind of crash on macOS since installing 1.59.0 from I think 1.58.2. I get a dialog noting some problem such as "Code Helper (GPU)" and then the standard macOS crash report.  I'll attach the crash report. It happens very intermittently and does not appear to affect the app, since I just continue working without interruption.
[macOS crash report for VSC 1.59.0.txt](https://github.com/microsoft/vscode/files/6973739/macOS.crash.report.for.VSC.1.59.0.txt)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 11, 7|
|Memory (System)|8.00GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.43.0
ada|Ada|22.0.9
Bookmarks|ale|13.1.0
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
project-manager|ale|12.3.0
rtf|ale|2.3.0
vscode-mac-color-picker|dae|1.0.2
textpad-icon-theme|dam|1.19.21
vscode-markdownlint|Dav|0.43.2
vscode-great-icons|emm|2.1.79
ada-snippets|Ent|0.3.0
vscode-faust|gle|1.1.0
vscode-lyx|gyt|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.20.2
svn-scm|joh|2.13.6
language-julia|jul|1.3.27
keen-neutral-icon-theme|kee|1.0.8
linter-gfortran|krv|2.3.0
octave|lea|0.1.1
eps-preview|mkv|0.1.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
cpptools|ms-|1.5.1
postscript|mxs|1.0.1
vscode-json-editor|nic|0.3.0
vsc-octave-debugger|pau|0.4.18
bib|phr|0.3.0
seti-icons|qin|0.1.3
ipf|qms|1.0.1
lualint|sat|0.0.5
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.22
octave|toa|0.0.3
pdf|tom|1.1.0
vscode-lua|tri|0.12.4
vscode-icons|vsc|11.6.0
vscode-icons-mac|way|7.25.3
debug|web|0.25.1
txt-syntax|xsh|0.1.6
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by deepak1556** [comment]
The trace is incomplete, can you follow these steps to get a crash log https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by oscarrutt** [comment]
I followed the instructions, making a new directory. Upon running the command it has three subdirectories, all empty, and file settings.dat. I was able to cause the crash but no file was added to the directory or any subdirectories. As previously stated, I get the standard Mac crash window, with title "Code Helper (GPU) quit unexpectedly." I sent the text of one of these crashes with my original post. Again, no .dmp file appears in the directory referenced with the `code --crash-reporter-directory <absolute-path>` command.

**Comment by deepak1556** [comment]
Thanks for trying the above steps, can you attach the recent crash reports from macOS console.

**Comment by oscarrutt** [comment]
Sorry for the delay. Console.app doesn't seem to like the way I'm using the filter function but here are several crash logs with file names containing Code Helper (GPU). I've not been using VSC for a few days so they are a few days old. I _suppose_ they are similar to the one attached to my original post.
[Code Helper.zip](https://github.com/microsoft/vscode/files/7024703/Code.Helper.zip)

**Comment by oscarrutt** [comment]
The problem has been fixed for a while so I'll close it. Thanks.
