### ISSUE TITLE
Inconsistent matching when typing quickly with Go To File

### ISSUE THREAD

**Issue by tucker-m** [Microsoft/vscode#1306]
I have a file called `products_controller.php`. So, that should be found if I do Go To File and type `prodcon`.

If I quickly type `prodcon`, it says "No results found." If I delete the last 'n' it will show a match for `products_controller.php`, as well as a few other files. If I then re-type the `n`, it will still show those matches.

If I type out p-r-o-d-c-o-n slowly, it will also find those matches.

Typing quickly:
![screen shot 2015-12-14 at 12 00 41 pm](https://cloud.githubusercontent.com/assets/1341275/11790707/6f467ec4-a25a-11e5-9167-f673e73daf23.png)

Deleting last character:
![screen shot 2015-12-14 at 12 00 57 pm](https://cloud.githubusercontent.com/assets/1341275/11790709/70bebbcc-a25a-11e5-9588-d1cfb5c00aa0.png)

Readding last character:
![screen shot 2015-12-14 at 12 01 06 pm](https://cloud.githubusercontent.com/assets/1341275/11790712/7337af44-a25a-11e5-8f23-45d4835049ef.png)

This is on Mac OSX Yosemite, 10.10.5.

**Comment by dbaeumer** [comment]
@bpasero

**Comment by bpasero** [comment]
Should be fixed with my changes, but I will check.

**Comment by bpasero** [comment]
Yes, fixed.
