### ISSUE TITLE
selecting a terminal tab does not focus the cursor on the command line

### ISSUE THREAD

**Issue by mmmurf** [microsoft/vscode#130624]
Issue Type: <b>Bug</b>

- open multiple terminals 
- click on the tab corresponding to one that you are not using
- start typing 

notice that the cursor was not focused on the command line of that terminal and that you must click again onto the terminal pane itself before the cursor is focused. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Fetching remote diagnostics for 'ssh-remote+192.168.86.23' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (17.10GB free)|
|Process Argv|--crash-reporter-id d46c9b78-d09a-412c-96f4-d3a1af28342e|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+192.168.86.23' timed out.
</details>

**Comment by mmmurf** [comment]
I don't think this is a duplicate of either of the suggested possible duplicates.

**Comment by gjsjohnmurray** [comment]
There is a setting that makes focus move into the terminal when you single-click a terminal tab. The default is for that to happen on doubleclick.

**Comment by mmmurf** [comment]
Thank you for the explanation. Do you happen to know why that was the
chosen default behavior?
