### ISSUE TITLE
Files do not delete completely after uninsatallion of visual studio code

### ISSUE THREAD

**Issue by singhal0306** [microsoft/vscode#130679]
Issue Type: <b>Bug</b>

as there is setting or something like error bcz of that i am getting nothing in terminal. bcz of that I am unable give input to my program. so i just uninstall it and install it again so that i can work on fresh vs code and its updated version but all it get in newly installed vs code is same settings and same extension installed as it is. It is what that make new coders or programmeres hard to use vs code. it is a grt problem, that make newly one away from vs code. All files and  setting should removed itself when somebody uninstalled and install it again.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.34GB free)|
|Process Argv|--crash-reporter-id b5d8365a-4126-4592-9a1c-2ea125a518e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.5
auto-save|mcr|1.0.3
cpptools|ms-|1.5.1
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173

```

</details>

**Comment by singhal0306** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/86726484/129201187-7e4269e3-6a5b-4268-ae49-ba9702b22b00.png)

**Comment by rzhao271** [comment]
Is the issue that the terminal is not loading?
Do you have steps to reproduce the issue?
