### ISSUE TITLE
Bitwise operators are not properly classified as such and resulting in incorrect syntax highlighting.

### ISSUE THREAD

**Issue by CocaineJohnsson** [microsoft/vscode#130677]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.58.0
- OS Version: Arch Linux 5.13.5-arch1-1

Steps to Reproduce:

1. write any code using bitwise operators while using a theme that colours bitwise operators separately from other operators
2. observe that only right and left shift bitwise operators are coloured differently and that `|`, `&`, `^`, `~` aren't properly classified as `keyword.operator.bitwise`  when they ought to be, instead they are classified as `keyword.operator`
3. Consider that the logical equivalents:
`||`, `&&` , `!` are classified as `keyword.operator.logical`, this is a discrepancy that makes it impossible to properly colour bitwise operators differently from normal operators.

See the (in my opinion) incorrectly closed https://github.com/microsoft/vscode/issues/118379 and the following discussion in https://github.com/microsoft/vscode-cpptools/issues/7961 that was created due to the incorrect closure.

The issue appears to be with the TextMate scopes not properly encapsulating bitwise operators under `keyword.operator.bitwise`

![image](https://user-images.githubusercontent.com/53689060/129199120-c94b4cc3-bebd-4293-94d8-927c2bb26523.png)

**Comment by aeschli** [comment]
For C++ we're using the Textmate grammar from https://github.com/jeff-hykin/cpp-textmate-grammar

The change request needs to be made there. I think you want a change at this line:
https://github.com/jeff-hykin/better-cpp-syntax/blob/90896461dd19144c7a3913c262b1592ec24ed90d/main/main.rb#L1534

Can you file the issue there?
