### ISSUE TITLE
Ctrl+click "Open in Editor" from terminal in editor group opens file in same group as editor

### ISSUE THREAD

**Issue by jabcross** [microsoft/vscode#130613]
Currently, ctrl+clicking a file path in an editor terminal opens the file in the same group, replacing the terminal. This happens even if the file is already open in a different group.

I expected the behavior to be similar to the panel terminal, where the terminal remains visible. I'd also expect it to give preference to a group that is already displaying the file.

Could be related to #124709.

**Comment by bpasero** [comment]
Terminal can control how the file opens via options such as:
* [`revealIfVisible`](https://github.com/microsoft/vscode/blob/22cf36faf81ca270390ec233389a81339b40b63a/src/vs/platform/editor/common/editor.ts#L228-L228)
* [`revealIfOpened`](https://github.com/microsoft/vscode/blob/22cf36faf81ca270390ec233389a81339b40b63a/src/vs/platform/editor/common/editor.ts#L236-L236)

Given groups new auto-lock for a terminal at least when the terminal is opened to the side this issue should no longer persists.

I would think it makes sense that the terminal sets `revealIfOpened`, at least when showing as editor.

**Comment by Tyriar** [comment]
To verify:

1. Open README.md
2. Open a terminal and move to the 2nd editor group
3. Unlock the 2nd editor group
4. Run `echo ./README.md` in terminal
5. Ctrl/cmd+click the link, it should reveal/focus README.md in the first group
