### ISSUE TITLE
yarn web: dragging and dropping vsix into extension explorer causes exception 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#130632]
Steps to Reproduce:

1. `yarn web`
2. Open in Chrome
3. Open extension view and drop a vsix onto it

**Bug**
Nothing happens.

In the dev tools, I see:

```
log.ts:301   ERR Cannot read property 'indexOf' of undefined: TypeError: Cannot read property 'indexOf' of undefined
    at Object.onDrop (http://localhost:8080/static/out/vs/workbench/contrib/extensions/browser/extensionsViewlet.js:458:42)
    at HTMLDivElement.<anonymous> (http://localhost:8080/static/out/vs/workbench/browser/dnd.js:398:32)
```

**Comment by mjbvz** [comment]
Seems like a duplicate of #106914 but @lszomoru can confirm if this isn't excepted to work

**Comment by lszomoru** [comment]
This is a feature request that is being tracked by #106914. Closing as duplicate.
