### ISSUE TITLE
Hundreds of invalid problems show up for a TS file when Kusto notebook extension is installed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#130692]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Latest Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Update to latest Insiders (by default comes with TypeScript dev version 20210806)
2. Open https://github.com/microsoft/vscode-jupyter
3. 🐛 999 problems immediately reported, most of which appear to be invalid, e.g. complaining about reserved keywords like `constructor` and `import` not being defined
4. Problems continue to be reported after downgrading to TS 4.3.5 and reloading
![recording (16)](https://user-images.githubusercontent.com/30305945/129227616-4e04d187-467d-4553-b28f-31cbe8b6178c.gif)
5. If I disable https://marketplace.visualstudio.com/items?itemName=donjayamanne.kusto that stops the problems from being reported. However that extension has not been updated in over a month, and this only started happening this morning after I updated Insiders, so I'm filing this issue here as it seems like document selector filters for the language service might not be being correctly applied

**Comment by mjbvz** [comment]
@joyceerhl Can you please start by filing this against the Kusto extension since it seems to cause this. If Don investigates and determines VS Code is doing something wrong, we can investigate further on our side
