### ISSUE TITLE
The object type contained in the iterator will be ignored in the debug console pannel.

### ISSUE THREAD

**Issue by YiFeng-W** [microsoft/vscode#130686]
Issue Type: <b>Bug</b>
## Bug screenshot
![image](https://user-images.githubusercontent.com/33275892/129210940-5220fea9-1867-46e7-b29d-f94a42d5a94d.png)

## test code
let arr = [1, 2, { a: 1 }, 'text']
console.log(arr)
for (let index = 0; index < arr.length; index++) {
    console.log('**', arr[index])
    console.log('//', arr[index], arr[2])
}
for (const iterator of arr) {
    console.log('--', iterator)
}
## view in debug console

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.24GB free)|
|Process Argv|--crash-reporter-id c8bc2a04-8975-4327-a88e-21f1815570b2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
vscode-great-icons|emm|2.1.79
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vue-snippets|hol|1.0.4
vscode-language-pack-zh-hans|MS-|1.59.3
csharp|ms-|1.23.14
vetur|oct|0.34.1
material-icon-theme|PKi|4.9.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.1

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172

```

</details>

**Comment by weinand** [comment]
@YiFeng-W you mean the colors of the debug output do not match the colors in the source?

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/161
