### ISSUE TITLE
Huge margin between letters only in vscode

### ISSUE THREAD

**Issue by KermanGreem** [microsoft/vscode#130685]
<img width="686" alt="Screenshot 2021-08-12 at 15 54 34" src="https://user-images.githubusercontent.com/85343923/129209320-ba469f18-0e26-4fe8-b839-6ec71d2c9229.png">

There is a huge margin between letters whereby the font ("fixedsys") works fine in my terminal and other code editors. 
The  below shows how it should normally look:

<img width="504" alt="Screenshot 2021-08-12 at 16 00 33" src="https://user-images.githubusercontent.com/85343923/129210353-018a2a10-d51f-42f2-8841-d8b92de401f4.png">

- VS Code Version: Version: 1.59.0
- OS Version: macOS Big Sur 11.2.2

**Comment by Tyriar** [comment]
Can you share your settings.json file?
