### ISSUE TITLE
Typescript color bug caused by generic variables are multiple lines

### ISSUE THREAD

**Issue by Kang-Jh** [microsoft/vscode#130638]
Issue Type: <b>Bug</b>

Let's say we have class SomeClass<T, U, V> {}
and then use it like below.
```typescript
const something = new SomeClass<
     SomeType1,
     SomeType2,
     SomeType3
>();
someFn('some text', async () => {})
```
The key point is generic variables are multiple lines.
When generic variables are multiple lines then 'some text' and async keyword doesn't have color which distinguish themselves to recognize easily by developers.
String covered by single quotes and async keyword have the same collor. 

At first I thought this might be extension theme issues. but even disabled all extensions doesn't solve this issue.

I think this is bug. Guess because "<" is recognized as operator not typescript specifying generic type variables when type variables are multiple lines

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by IllusionMH** [comment]
/duplicate
See https://github.com/microsoft/TypeScript-TmLanguage/issues/475#issuecomment-309905772 for details
