### ISSUE TITLE
Takes an inordinate amount of time to close a notebook file (ipynb) 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#130625]
Version: 1.60.0-insider (user setup)
Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
Date: 2021-08-11T05:15:24.598Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Crappy bug as I'm not able to consistently reproduce this, but I've seen it more than once. Trying to repro, but failing. Here was the scenario.

1. Open a large notebook. https://github.com/greazer/covid-19-data/SampleNbsAndScripts/TroubleNotebooks/1.5Kcells.ipynb. I don't actually know if the size of the notebook matters. 
2. Run cells, edit some cells, etc.
3. Close the notebook. 

Say "No" when asked if you want to save changes. I'd expect the ipynb to immediately close. But what I've seen is a long delay until the tab actually disappears.

**Comment by roblourens** [comment]
Possibly fixed with the other memory leaks, optimistically closing

**Comment by rebornix** [comment]
Actually the slowness is still there as shown below

![image](https://user-images.githubusercontent.com/876920/129388262-21c4f5f4-65f0-4fae-b578-c234878688d0.png)


It seems "do not save" on file close is not "soft".

**Comment by jrieken** [comment]
fixed with @mjbvz's IPC improvements
