### ISSUE TITLE
VScode editor .xml file extension to show html file inside editor

### ISSUE THREAD

**Issue by Sujay-shetty** [Microsoft/vscode#13060]
@joaomoreno 
- VSCode Version: *
- OS Version: Windows/Linux

I'm new to vscode editor, I need below functionality to extended vscode editor.

How to render and display html file inside a vscode editor depending on file extension type.

Suppose following is the folder structure.

    > MyProject[folder]
       > src[folder]
       > lib[folder]
       > package.json[file]
       > config.xml[file]

When user clicks on config.xml file I want to open an index.html file inside vscode editor(may be in preview window or any other option). Html file should be displayed as how it displays in browser inside vscode not as how editor displays as an editing html file.

**Comment by jrieken** [comment]
You can use the `vscode.previewHtml`-command which is documented [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands).

**Comment by Sujay-shetty** [comment]
thank you @jrieken, it helped a lot
