### ISSUE TITLE
Notebook Interactive Window: Keybinding / Command to move from input box to output history

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#130724]
Does this issue occur when all extensions are disabled?: No (using Jupyter extension for testing)

- VS Code Version: 1.60 insiders (8/12 build)
- OS Version: MacOS BigSur

Was dogfooding the new interactive window (testing VIM extension in input box) and I wasn't finding a good way to jump between the output history and the input box without using the mouse. I wanted to be able to move up to the history and scroll back in it, and then jump back down to the input box to put something new in. 

![image](https://user-images.githubusercontent.com/812783/129276530-4dae5b8c-9226-401b-a4bf-bcdc58a6a7ae.png)

As a side note, when my focus was on a cell back in the history list, doing shift+enter or ctrl+enter would execute the current contents of the input box. I'm not sure if this is a bug as I'm not 100% sure on what I would have expected there. I might expect that cell I have selected to be rerun?

**Comment by connor4312** [comment]
Very similar to https://github.com/microsoft/vscode/issues/128497, but not an exact duplicate

**Comment by greazer** [comment]
I don't really see this as a feature-request but more like a workflow bug. You could argue that it's an accessibility problem as well. Going to add it as a golden-path issue for visibility. We've had a valuable customer recently complain about this.

**Comment by rebornix** [comment]
```
{
  "key": "alt+cmd+up",
  "command": "interactive.history.focus"
},
{
  "key": "alt+cmd+down",
  "command": "interactive.input.focus"
}
```

Added two commands to focus the history or input editor in the interactive window. Above snippet is keybindings I use.
