### ISSUE TITLE
Jupyter extention fails demo variables

### ISSUE THREAD

**Issue by bearhunt110** [microsoft/vscode#130750]
Issue Type: <b>Bug</b>

The Jupyter variables not working constantly in the latest version of vscode, which showing no variables and stating 'No variables defined'.
And I used to change some self-defined function in editor and run, in the last version, the result changes, but in latest version, it invokes the unchanged function and get  the same result. For instance, the function raise an error, and I change the function and rerun it, the same error raised with unchanged function.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-305.3.1.el8.x86_64
Remote OS version: Linux x64 4.18.0-305.3.1.el8.x86_64
Remote OS version: Linux x64 4.18.0-305.3.1.el8.x86_64
Remote OS version: Linux x64 4.18.0-305.3.1.el8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id cd097cdc-a6b8-497d-a81a-67d936455907|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: CCXD|
|OS|Linux x64 4.18.0-305.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (40 x 2400)|
|Memory (System)|251.28GB (56.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: CCXD|
|OS|Linux x64 4.18.0-305.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (40 x 2400)|
|Memory (System)|251.28GB (56.20GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: CCXD|
|OS|Linux x64 4.18.0-305.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (40 x 2400)|
|Memory (System)|251.28GB (56.23GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: CCXD|
|OS|Linux x64 4.18.0-305.3.1.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (40 x 2467)|
|Memory (System)|251.28GB (56.12GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-icons|vsc|11.6.0
gitlens|eam|11.6.0
gc-excelviewer|Gra|3.0.42
path-autocomplete|ion|1.17.1
vsc-python-indent|Kev|1.14.2
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30351747

```

</details>

**Comment by rzhao271** [comment]
\gifPlease
