### ISSUE TITLE
Maximize of VSCode window is not working with Actual Window Manager

### ISSUE THREAD

**Issue by Louti** [Microsoft/vscode#13078]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Install Actual Window Manager (v8.9 here)
2. Try to maximize VS Code window

Here is a [link ](https://www.youtube.com/watch?v=NkAYAo6t-jg&feature=youtu.be) to describe the problem with a video. 

Thanks for this marvelous piece of work by the way, it's a very nice program!

**Comment by Tyriar** [comment]
Almost certainly an issue with Electron, Chromium or the window manager

**Comment by bpasero** [comment]
@Louti does it reproduce with our insider build? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Louti** [comment]
Hello and thanks for the update, sorry for the delay.
 
With insider version 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z) I still sadly have this bug.

But I can confirm that it happens to another program namely WebTorrent that must use the same engine (Electron?) as you. So I think it's definitely not a bug within VS Code but still very annoying.

Good luck and I'm still there if you need me.

**Comment by bpasero** [comment]
Ok thanks 👍

**Comment by Louti** [comment]
It has been fixed in the latest version ! Thanks a lot !
