### ISSUE TITLE
remote ssh failed _workbench.downloadResource failed

### ISSUE THREAD

**Issue by DLlearn** [microsoft/vscode#130742]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59
- OS Version: win10

Steps to Reproduce:

1、use vscode to connect remote machine by using ssh
2、after input the password ,the vscode output " Could not estabilsh connection to  "xxx":Runing the contributed command:'_workbench.downloadResource'failed.
3、change vscode version to 1.57,keep other things same .the this problem solved 
4、from version 1.57.4 to 1.59.0,all the vscode will output this error message

![image](https://user-images.githubusercontent.com/12130348/129306390-d5b14301-55d4-403b-9665-fe5598a3a4fa.png)

**Comment by roblourens** [comment]
Can you share the full log from behind that dialog?
