### ISSUE TITLE
lose changes when closing the editor - jupyter notebooks

### ISSUE THREAD

**Issue by kellycastrof** [microsoft/vscode#130765]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10

I've been using vscode to modify notebooks. I copy an existing file, change the name, make the modifications, they are saved in the output cells, but when I close the editor and reopen the file the changes I made are lost.
I have the option afterDelay enabled.

**Comment by rebornix** [comment]
@kellycastrof if you scroll to the top of the document and then close/reopen, do you get the changes back?
