### ISSUE TITLE
Improve workspace API for Notebook lifecycle to support (at least) saving events

### ISSUE THREAD

**Issue by francisco-perez-sorrosal** [microsoft/vscode#130799]
There are certain VSCode extensions that are devoted to allow users to define shell commands that are executed when files are saved. These include, among others, the following: 

1. [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave)
2. [VSCode Run on Save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save)
3. [Save and Run](https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run)

The extensions above rely on events currently available in the [VSCode `workspace` API](https://code.visualstudio.com/api/references/vscode-api#workspace) such as `onWillSaveTextDocument` and `onDidSaveTextDocument`. 

In the recently added native support for notebooks in VSCode, it looks like notebooks are treated in a different way than text documents. The new `workspace` API has included some events specifically targeted to the notebook lifecycle, such as `onDidOpenNotebookDocument` and `onDidCloseNotebookDocument`. However, the API currently lacks other useful notebook lifecycle events such as `onWillSaveNotebookDocument` and `onDidSaveNotebookDocument`, so the extensions above can't work properly when save-related events happen on notebooks.

Would it be possible to extend the workspace API with at least `onWillSaveNotebookDocument` and `onDidSaveNotebookDocument` (and other useful methods for the notebook lifecycle if possible)?

Thanks in advance!!!

Note: I've just stumbled upon a similar request for those APIs in an issue related to LiveShare: #102503

**Comment by syrusakbary** [comment]
That would be super useful to have, indeed!

**Comment by reggi** [comment]
Is there any workaround for this? I currently can easily see if a text file has been saved, but not have an event to tap into when a notebook has been saved. 😤😭

```ts
vscode.workspace.onDidSaveTextDocument(e => {
  vscode.window.showInformationMessage('did' + e.fileName)
})

vscode.workspace.onWillSaveTextDocument(e => {
    vscode.window.showInformationMessage('will' + e.document.fileName)
})
```

**Comment by rebornix** [comment]
Re https://github.com/microsoft/vscode/issues/157844

**Comment by rebornix** [comment]
We already have `onDidSaveNotebookDocument` and we are finalizing `onWillSaveNotebookDocument` API in https://github.com/microsoft/vscode/issues/157844, thus closing this issue.

**Comment by rebornix** [comment]
@francisco-perez-sorrosal  @reggi you can follow https://github.com/microsoft/vscode/issues/157844 on where we are with the `onWillSaveNotebookDocument` API, thanks!

**Comment by rebornix** [comment]
This can be now tested against VS Code Insiders using the latest vscode.d.ts file from main branch. A sample extension with following content should work

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	vscode.workspace.onWillSaveNotebookDocument(event => {
		if (event.reason === vscode.TextDocumentSaveReason.Manual) {
			event.waitUntil(new Promise((resolve) => {
				const notebookEdit = new vscode.NotebookEdit(new vscode.NotebookRange(0, 0), [new vscode.NotebookCellData(vscode.NotebookCellKind.Code, 'print(1)', 'python')]);
				const edit = new vscode.WorkspaceEdit();
				edit.set(event.notebook.uri, [notebookEdit]);
				resolve(edit);
			}));
		}
	});
}
export function deactivate() {}
```
