### ISSUE TITLE
This error appears when try to choose Terminal: Select Default Profile

### ISSUE THREAD

**Issue by MuhammadAlBarham** [microsoft/vscode#130793]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0 (user setup)
- OS Version: Windows 10 Home Single Language

Steps to Reproduce:

1. F1
2. Terminal: Select Default Profile

Error appears as a pop up message:
`Command 'Terminal: Select Default Profile' resulted in an error (Cannot use 'in' operator to search for 'path' in Visual Studio 2019 Dark)`

**Comment by meganrogge** [comment]
what are your configured terminal profiles? IE terminal.integrated.profiles.<platform> ?

**Comment by MuhammadAlBarham** [comment]
The `IE terminal.integrated.profiles.`  is stated below

Windows:

```json
{
        "terminal.integrated.profiles.windows": {
        "PowerShell -NoProfile": {
          "source": "PowerShell",
          "args": ["-NoProfile"]
        },
```

**Comment by meganrogge** [comment]
any errors in the dev tools console?

**Comment by MuhammadAlBarham** [comment]
Yes, there are 8 errors.

**Comment by meganrogge** [comment]
Please provide them

**Comment by meganrogge** [comment]
Thanks . Have you tried disabling all of your extensions?

**Comment by MuhammadAlBarham** [comment]
Yes, I disabled all extensions and I have faced the same problem.
