### ISSUE TITLE
Live share: An error pops up when join in the host.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode#130717]
## Environment data
Build of Visual Studio Code - Insiders: 1.60.0 -insider (user setup)
Build of python-insider: 2021.9.1121560038-dev
Build of jupyter-insider: 2021.8.2025984474

## Actual behaviour
An error pops up when join in the host.
The folder is a new folder and the file is saved.
![image](https://user-images.githubusercontent.com/59192491/129165343-104d03f3-1e97-4d1c-8eb4-6e5a43a099fb.png)

## Steps to reproduce:
1. Install the LiveShare VSCode Extension (VS Live Share Extension Pack)
2. Open manualTestFile.py in VSCode
3. Run the first cell in the file
4. Switch to the Live Share tab in VS Code and start a session
5. Open another window of VSCode
6. Connect the second instance of VSCode as a Guest to the first Live Share session

**Comment by greazer** [comment]
This isn't likely a vscode problem, but we're not sure how to transfer it to the LiveShare extension.

**Comment by rzhao271** [comment]
@linette-zyy Please re-file the issue here https://github.com/MicrosoftDocs/live-share/issues
