### ISSUE TITLE
Suggest details: close button doesn't have hover feedback

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130703]
Similar to this issue: #130475

![Screenshot (202)](https://user-images.githubusercontent.com/9638156/129249973-19fed0b2-01da-403e-9ed2-976d582f18aa.png)

**Comment by jrieken** [comment]
I see this working now

**Comment by usernamehw** [comment]
4bbec283c36a51cf80f9b77c7a81c140a76a363b no hover feedback.
