### ISSUE TITLE
Typescript server keeps dying

### ISSUE THREAD

**Issue by jihan-yin** [microsoft/vscode#130728]
Issue Type: <b>Bug</b>

When I try to open my workspace via vscode ssh, I get stuck on "Initializing JS/TS language features" in my vscode notifications, and it seems that the ts server keeps dying. This makes it so I get no intellisense and can't jump to definitions, and get no typechecking across my code, which is pretty bad.

This works when I open the same exact workspace locally. I've tried doing a clean reinstall of vscode (removing .vscode-server in the remote linux server, deleting all vscode related directories locally) and it's still happening. I tried looking at the vscode logs and there doesn't seem to be any obvious errors or crashes. What is going on?

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1054-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 8bf6222a-7d99-4e1e-bac8-6ee373271eeb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 5.4.0-1054-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 2499)|
|Memory (System)|31.02GB (23.25GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jihan-yin** [comment]
It does, but just tried
```
"typescript.tsserver.maxTsServerMemory": 6000
```
and it seems to have stopped the crashes for now!
