### ISSUE TITLE
settings.json styling should take precedence over third party plugins

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#130720]
I would like an option for VSCode to reject third party styling for any style parameters defined in settings.json. This way, VSCode can work around some limitations in the resolution order for third party styling plugins like EditorConfig.

The EditorConfig plugin for VSCode unfortunately treats ~/.editorconfig as higher precedence than a settings.json file located in a project directory. That can lead to the wrong indentation style being applied.

It makes sense for ./.editorconfig to override .vscode/settings.json, but not for ~/.editorconfig to override .vscode/settings.json.

Either the plugin should improve the precedence logic, or else VSCode should prohibit third party plugins from altering style in contexts where a settings.json file defines the style. If an engineer wishes to use multiple styling systems, then the configurations should agree, but any settings.json present should take effect on the parameters it stipulates.

https://github.com/editorconfig/editorconfig-vscode

**Comment by roblourens** [comment]
The readme says

> This plugin attempts to override user/workspace settings with settings found in .editorconfig files.

It sounds like this is by design? I don't think vscode is able to enforce what you are asking for. The extension has to implement their own logic here. I think you can file this issue on their repo.
