### ISSUE TITLE
Comand double clicking on a file doesn't open a new tab

### ISSUE THREAD

**Issue by IanAshleyEckoh** [microsoft/vscode#130772]
Issue Type: <b>Bug</b>

1. One a project containing multiple files
2. Double click on one of them to open it
3. Command double click on a second one, should open in a new tab => doesn't

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.70GB free)|
|Process Argv|. --crash-reporter-id b1debbb2-7e38-457e-90ae-b5e6ab64d2c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
gitlab-workflow|Git|3.28.1
terraform|has|2.14.0
vscode-format-context-menu|lac|1.0.4
meson-build|Mrm|0.2.1
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.9.0
java|red|0.80.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
vscode-checkstyle|she|1.4.0
sonarlint-vscode|Son|2.0.0
shellcheck|tim|0.15.2
opa|tsa|0.8.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.3
vscode-java-test|vsc|0.31.1
vscode-maven|vsc|0.32.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce.

/gifPlease
