### ISSUE TITLE
These two function "Undo" and "Redo" are missing.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode#130716]
## Environment data
Build of Visual Studio Code - Insiders: 1.60.0 -insider (user setup)
Build of python-insider: 2021.9.1121560038-dev
Build of jupyter-insider: 2021.8.2025984474

## Actual behaviour
![image](https://user-images.githubusercontent.com/59192491/129152320-2ec3f398-e88c-4ded-ba1a-4cfdcba570a6.png)

## Expected result
1. Undo the delete action with `Undo`
2. Redo the delete action with `Redo`

**Comment by greazer** [comment]
Need to make sure that the existing undo/redo functionality via Edit > Undo, has reasonable behavior. Especially regarding the global/cell based undo setting.

**Comment by linette-zyy** [comment]
Build of Visual Studio Code - Insiders: 1.61.0-insider (user setup)  
Build of python-insider: v2021.10.1239554536-dev
Build of jupyter-insider: v2021.9.1001236957
Build of pylance-insider: v2021.9.1
Build of jupyter Keymap-insider: v1.0.0

I click the "Clear all" button in the interactive window. All the executable cells were deleted.
Then I go to Edit > Undo, my operation has not been revoked. 
![image](https://user-images.githubusercontent.com/59192491/133558665-ff09dd39-b698-4afe-b214-935b1a9911b9.png)
The undo no use for interactive window.
