### ISSUE TITLE
Markdown preview loses scrollbar on edit

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#13075]
Steps to Reproduce:
1. Open a Markdown file, long enough to have a scrollbar in its preview
2. Open preview to the side
3. Edit the file

The preview loses the scrollbar once it refreshes due to the file change event.

**Comment by mjbvz** [comment]
I believe that this was fixed by #19394, which worked around an upstream chrome issue

Please try VSCode 1.9 and let me know if you still see this

Thanks
