### ISSUE TITLE
vscode intergrated terminal not visible 

### ISSUE THREAD

**Issue by healertrix** [microsoft/vscode#130738]
Issue Type: <b>Bug</b>

I tried to change the font in terminal settings but the whole sceen blank and despite my efforts to debug , nothing has improved please help me ,I had raised a similar issue earlier too but to no good,I love vscode and this has hampered my coding experience

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.09GB free)|
|Process Argv|--crash-reporter-id a856aa30-cfcb-4ff5-8fc8-349c2c6f9a05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-browser-preview|auc|0.7.1
simple-react-snippets|bur|1.2.3
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
terminal|for|0.0.10
javascript-essentials|Gyd|0.0.7
beautify|Hoo|1.5.0
cpptools|ms-|1.5.1
powershell|ms-|2021.8.0
vscode-typescript-next|ms-|4.5.20210812
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.6.0
material-icon-theme|PKi|4.9.0
gitlink|qez|0.7.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.4.22
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.390
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by healertrix** [comment]
![image](https://user-images.githubusercontent.com/75298389/129299487-ed163236-8663-434b-aa79-f6669560fbd5.png)

**Comment by healertrix** [comment]
this is no lack of information , I click on the console icon and then only this blank space shows up , please sort this asap

**Comment by meganrogge** [comment]
1. please provide me with your terminal settings
2. any errors in the dev tools console? (ctrl+shift+i)

**Comment by healertrix** [comment]
terminal settings - :


{
    "terminal.integrated.fontSize": 12,
    "workbench.iconTheme": "material-icon-theme",
    "explorer.confirmDragAndDrop": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "liveServer.settings.donotShowInfoMsg": true,
    "debug.console.fontSize": 16,
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "python.languageServer": "Pylance",
    "liveServer.settings.donotVerifyTags": true,
    "git.autofetch": true,
    "jupyter.alwaysTrustNotebooks": true,
    "kite.showWelcomeNotificationOnStartup": false,
    "python.defaultInterpreterPath": "C:\\Users\\ASUS\\anaconda3\\python.exe",
    "editor.formatOnType": true,
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "modifications",
    "editor.formatOnPaste": true,
    "editor.showDeprecated": false,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "code-runner.saveFileBeforeRun": true,
    "code-runner.runInTerminal": true,
    "code-runner.executorMap": {


        "javascript": "node",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "cpp": "cd $dirWithoutTrailingSlash && g++ -std=c++11 $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt",
        // "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        //above for cmd and powershell
        "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "php": "php",
        "python": "python -u",
        "perl": "perl",
        "perl6": "perl6",
        "ruby": "ruby",
        "go": "go run",
        "lua": "lua",
        "groovy": "groovy",
        "powershell": "powershell -ExecutionPolicy ByPass -File",
        "bat": "cmd /c",
        "shellscript": "bash",
        "fsharp": "fsi",
        "csharp": "scriptcs",
        "vbscript": "cscript //Nologo",
        "typescript": "ts-node",
        "coffeescript": "coffee",
        "scala": "scala",
        "swift": "swift",
        "julia": "julia",
        "crystal": "crystal",
        "ocaml": "ocaml",
        "r": "Rscript",
        "applescript": "osascript",
        "clojure": "lein exec",
        "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
        "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
        "racket": "racket",
        "scheme": "csi -script",
        "ahk": "autohotkey",
        "autoit": "autoit3",
        "dart": "dart",
        "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
        "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
        "haskell": "runhaskell",
        "nim": "nim compile --verbosity:0 --hints:off --run",
        "lisp": "sbcl --script",
        "kit": "kitc --run",
        "v": "v run",
        "sass": "sass --style expanded",
        "scss": "scss --style expanded",
        "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
        "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
    },
    "code-runner.fileDirectoryAsCwd": true,
    "code-runner.respectShebang": false,
    "yaml.schemas": {
        "file:///toc.schema.json": "/toc\\.yml/i"
    },
    "C_Cpp.updateChannel": "Insiders",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "gitlens.defaultDateFormat": null,
    "powershell.powerShellDefaultVersion": "Windows PowerShell (x86)",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "emmet.triggerExpansionOnTab": true,
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "C:\\Program Files\\Git\\bin\\bash.exe (migrated)": {
            "path": "C:\\Program Files\\Git\\bin\\bash.exe",
            "args": []
        }
    },
    "code-runner.clearPreviousOutput": true,
    "editor.inlineSuggest.enabled": true,
    "window.zoomLevel": 1,
    "security.workspace.trust.untrustedFiles": "open",
    "terminal.integrated.localEchoStyle": null,
    "terminal.integrated.fontWeight": null,
    "terminal.integrated.inheritEnv": true,
    "terminal.integrated.allowMnemonics": true,
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.fontFamily": "monospace",
    "tabnine.experimentalAutoImports": true,
    "editor.fontSize": 15,
    "files.autoSave": "afterDelay",
    "debug.terminal.clearBeforeReusing": true,
    "terminal.integrated.cursorWidth": 2,
    "editor.wordWrap": "on",
    "terminal.external.windowsExec": "wt.exe",
    "terminal.integrated.windowsEnableConpty": true,
    "workbench.colorTheme": "Abyss",
    "javascript.updateImportsOnFileMove.enabled": "always",
}

**Comment by healertrix** [comment]
please look into it asap

**Comment by Tyriar** [comment]
Please check for errors in the dev tools console (Help > Toggle Developer Tools)
