### ISSUE TITLE
Trigger signature help after completion

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/vscode#13072]
In my case completion for functions also insert the parenthesis ( e.g. `foo({{}})`)
For signature help I have the triggerCharacter `'('` but unfortunately inserting it by applying a suggestion doesn't trigger signature help. 
Is there a way to have signature help triggered when applying a completion suggestion?

**Comment by joaomoreno** [comment]
What's the language, in your case?

**Comment by joaomoreno** [comment]
Ping @svenefftinge

**Comment by svenefftinge** [comment]
Sorry for late response, It is R. But i think this can be applied to any language that uses parenthesis fro function arguments.

**Comment by joaomoreno** [comment]
Are you using any extension for R? The `editor.action.triggerParameterHints` will trigger signature help. The R extension could call this command on demand.

**Comment by svenefftinge** [comment]
We are building this extension, and it is a language server using the LSP. I would like to avoid custom client code for this if possible. I will try to use the CompletionItem#command property for that. Thank you!
