### ISSUE TITLE
the "electron" process loads the processor by 50% constantly since the start of the code-oss  

### ISSUE THREAD

**Issue by x555xx54** [microsoft/vscode#130764]
Issue Type: <b>Bug</b>

the "electron" process loads the processor by 50% constantly since the start of the code-oss  
constantly increasing the amount of occupied RAM 

VS Code version: Code - OSS 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-12T23:51:36.303Z)
OS version: Linux x64 5.10.56-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X4 651 Quad-Core Processor (4 x 1487)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.75GB (1.68GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by jacobfriedman** [comment]
That sucks.

**Comment by deepak1556** [comment]
Can you provide the output of `cat /proc/<PID>/cmdline` where `<PID>` is of the process that shows increased memory usage.

**Comment by x555xx54** [comment]
Run Code OSS.
I found an electron process in the list of processes, which with every second consumed more and more RAM with the processor load
executed the command  (Did I execute the command correctly?)

[august@amdbox ~]$ cat /proc/2655/cmdline
/usr/lib/electron12/electron --type=renderer --disable-color-correct-rendering --field-trial-handle=1485096788758611510,8103713643764736055,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=ru --enable-crash-reporter=51d12b11-75fe-48de-bb25-01bc2751c2c8,no_channel --global-crash-keys=51d12b11-75fe-48de-bb25-01bc2751c2c8,no_channel,_companyName=Microsoft,_productName=Code - OSS,_version=1.58.0 --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --app-path=/usr/lib/code --no-sandbox --no-zygote --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=5 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100 --vscode-window-config=vscode:40de52bc-37cb-4c21-bbaa-233b70b0197f[august@amdbox ~]$

**Comment by deepak1556** [comment]
`/usr/lib/electron12/` this looks like a global installation of electron, please file an issue against the package from where you have installed. Closing as out-of-scope, if the issue repros with installation from https://code.visualstudio.com/#alt-downloads  happy to reopen.
