### ISSUE TITLE
Code not consistently saving on Live Share

### ISSUE THREAD

**Issue by CapTightpants** [microsoft/vscode#130730]
Issue Type: <b>Bug</b>

I am currently running two systems - Ubuntu 20.04 server, and windows 10 - with VScode live. The Ubuntu system is acting as a server of sorts, so that myself and other collaborators can work on this project without overlapping.

When editing my files, regardless of file type, the changes are not always reflected immediately on the host machine's file system. The client's 'live share workspace' still reflects the changes and no longer says that there are files to save, but a check on the host confirms they have not. If I make some changes - such as a comment line - and save it again, the changes are reflected.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.72GB free)|
|Process Argv|--crash-reporter-id 568295cb-5638-4849-8aa6-e440cd1b4384|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-codemetrics|kis|1.24.0
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-for-node-js-development-pack|nod|2.0.1
code-settings-sync|Sha|3.4.3
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748
javagetstartedt:30351793

```

</details>

**Comment by rzhao271** [comment]
Please re-file the issue at https://github.com/MicrosoftDocs/live-share/issues
