### ISSUE TITLE
Native Interactive - Collapse Cell Input Code By Default - Not Respected

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#130713]
## Environment data
- Version: 1.60.0-insider
- Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
- Date: 2021-08-11T05:13:17.497Z
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2025984474
-   Python Extension version (available under the Extensions sidebar): v2021.9.1117361286-dev
-   OS (Windows | Mac | Linux distro) and version: Darwin x64 20.6.0
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used: pipenv
-   Jupyter server running: Local

## Expected behaviour

- Interactive Window cell input code automatically collapsed when `Jupyter: Collapse Cell Input Code By Default` is enabled

## Actual behaviour

- Code IS collapsed when run from a `.py` file, but not from IW code entry cell:
<img width="1116" alt="Screen Shot 2021-08-11 at 11 33 19 AM" src="https://user-images.githubusercontent.com/29611875/129084819-6b8e7e5d-2e1d-4906-8579-7db1aed0d9c2.png">

## Steps to reproduce:

1. Create interactive window
2. run any code
3. cell input is not collapsed

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
This is a change in default behavior from the original implementation of the Interactive Window. Therefore, marking as a regression for now. 

Personally, I don't like the difference in behavior between running a cell in the .py file vs running it in the input box. I guess that's a way to help a user quickly determine which cells are in the PY file or not. I don't know of a particular use case where this would be useful. The two issues that seem to be related to is were both requesting the default to be collapsed. 

See: microsoft/vscode-jupyter#3708 and microsoft/vscode-jupyter#3799

**Comment by greazer** [comment]
Marking as part of the interactive window golden path.

**Comment by roblourens** [comment]
Do some people prefer the current behavior? How about `notebook.interactiveWindow.collapseCellInputCode` with "always", "never", and "fromEditor" (the current behavior)

**Comment by roblourens** [comment]
@rebornix we don't have any interactive window settings, do you like that setting name pattern or do you prefer `interactiveWindow.*` or something else?

**Comment by rebornix** [comment]
@roblourens I personally prefer `interactive.*` but fine with `interactiveWindow` if `interactive` is too generic.

**Comment by roblourens** [comment]
I will change the setting to `interactiveWindow.*`
