### ISSUE TITLE
Save terminals upon exiting app

### ISSUE THREAD

**Issue by aahlrichs5** [microsoft/vscode#130783]
Now that we can give terminals custom icons/colors/names let us save those terminals so that when we exit the app they are still there. It would be nice to not have to set these up every time I restarted the app.
![image](https://user-images.githubusercontent.com/66093591/129401783-3babbf02-4075-4113-945e-b7403de57388.png)

**Comment by meganrogge** [comment]
You can create custom terminal profiles, which make it very easy to recreate the terminals when re-opening VS code. 

If you mean you want the terminals to persist upon re-opening the window, that would likely be a by-product of implementing #10121
