### ISSUE TITLE
Hardcoded `vscode-vfs` dependency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130766]
In some places:

![image](https://user-images.githubusercontent.com/900690/129367541-126c86be-d637-4fc9-81ea-62e66d2e739e.png)

Should imho not hardcode because it originates from an extension. Can rather use `IPathService.defaultUriScheme`

**Comment by mjbvz** [comment]
@aeschli Adding you for the merge conflict (please reassign if needed as I'm not sure about the proper owner)

**Comment by lszomoru** [comment]
@sbatten as this is related to workspace trust in a virtual workspace.

**Comment by chrmarti** [comment]
The merge-conflict code-lens provider is registered for specific schemes to avoid https://github.com/microsoft/vscode/issues/33133.

**Comment by bpasero** [comment]
Please check `IPathService.defaultUriScheme` which is a way to know the "default scheme" the workspace operates in.

**Comment by chrmarti** [comment]
That's in an extension which doesn't have access to `IPathService`. We could check the first workspace folder's URI scheme (if it is not an empty window).
