### ISSUE TITLE
Markdown hover can be hidden when hovering over links' title attribute

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130723]
1. Inside the hover popup hover over the link 
2. After `"title"` attribute is shown for the link - move cursor over the title attribute
3. The hover popup is closed even though cursor didn't leave the hover boundaries

![demo](https://user-images.githubusercontent.com/9638156/129272405-0352edcd-0ede-4b57-8a69-7bce922bb93e.gif)

Possible to reproduce in any markdown hover (editor or Markdown hover in Tree View or Status Bar).

**Comment by alexdima** [comment]
I can't reproduce this anymore, I will optimistically close it given https://github.com/microsoft/vscode/pull/161407
