### ISSUE TITLE
NotebookController.interruptHandler() should include the cell that hit it as a parameter

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#130794]
It can be an optional parameter or something. But it doesn't make sense that it is clickable on a cell, but it won't tell which cell clicked it.

**Comment by DonJayamanne** [comment]
@DavidKutu Do we need this in jupyter extension?

**Comment by IanMatthewHuff** [comment]
I think I was wondering the same thing Don was. Is there a cell specific action that we would take here? Wasn't sure why we would need to know which cell triggered the interrupt.

**Comment by jrieken** [comment]
Yeah, please clarify what this is needed for. The whole point of interrupt vs cancel is that the former is cell agnostic and just happens.

**Comment by DavidKutu** [comment]
I needed it to cancel the debugging session of the cell that clicked it. I ended up working around it.

**Comment by roblourens** [comment]
I think that clicking it while debugging should do pretty much the same thing as clicking it while running normally
