### ISSUE TITLE
Windows can't go to sleep mode

### ISSUE THREAD

**Issue by blastZ** [microsoft/vscode#130781]
Issue Type: <b>Bug</b>

Windows can't go to sleep mode, if I have opend vscode. Even I close the vscode, the windows still can't go to sleep mode.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.65GB (19.66GB free)|
|Process Argv|--crash-reporter-id 054ce757-d9c6-439c-9496-9a907a5fc070|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|Memory (System)|15.46GB (14.03GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.9.0
mdx|sil|0.1.0
svg-preview|Sim|2.8.3
vscode-nginx|wil|0.7.2
vscode-markdownlint|Dav|0.43.2
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
todo-tree|Gru|0.0.213
vscode-ansi|ili|1.1.2
svg|joc|1.4.9
git-graph|mhu|1.30.0
vscode-docker|ms-|1.15.0
color-highlight|nau|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by blastZ** [comment]
Maybe It's not vscode's bug, but the situation is the windows can't go to sleep mode, if I have opend vscode. I need some helps.

**Comment by rzhao271** [comment]
Can you try some other scenarios to see when Windows can go to sleep?

**Comment by blastZ** [comment]
I already tried other scenarios. I opened edge, wsl, docker, office and more, even run some apps in the wsl, Windows still can go to sleep successfuly.

So I opened Windows again to run vscode, but It can't go to sleep mode in this time.

I even try to install ubuntu vscode, run it by wsl gui, the same situation happened.

It's weird, so I opened this issue to get some advices.
