### ISSUE TITLE
Save won't save

### ISSUE THREAD

**Issue by kaitlynmichael** [microsoft/vscode#130774]
Issue Type: <b>Bug</b>

When I press cmd+s or even File>Save, nothing happens. 

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|-psn_0_10349022 --crash-reporter-id 24e22c70-6c17-4216-8381-d8b1586b0aef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.43.2
prettier-vscode|esb|8.1.0
azure-virtual-machine-explorer|for|0.0.2
vscode-docker|ms-|1.15.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1054968649
azure-account|ms-|0.9.8
vscode-yaml|red|0.22.0
velocity|sod|0.2.0
code-spell-checker|str|1.10.2

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747

```

</details>

**Comment by kaitlynmichael** [comment]
It turns out the save is just unreliable/delayed. I was eventually able to save but only after several minutes and several attempts.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have any actions triggered on save like `editor.formatOnSave` or `editor.codeActionsOnSave`?
