### ISSUE TITLE
Unable to copy output of dataframe.columns from notebook or IW.

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#130710]
Running the native interactive window using the latest Python and Jupyter extensions, I'm unable to copy text from the output of `df.columns`.

Minimal example:

1. Open command palette and run "Jupyte Create Interactive Window".
2. Enter
   ```py
   import pandas as pd

   df = pd.DataFrame(range(2), columns=['foobar'])
   df.columns
   ```
3. Try to copy-paste the column name `'foobar'` into the input field at the bottom of the window. Doesn't work (for me).

**Comment by janosh** [comment]
I'm not running insiders. Is the memory leak only occurring there?

**Comment by janosh** [comment]
@rebornix Will wait for next week's stable.

**Comment by rebornix** [comment]
No longer reproducible in latest version.
