### ISSUE TITLE
1.59 webview fails to update, loses focus on key press

### ISSUE THREAD

**Issue by ammkrn** [microsoft/vscode#130752]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59
- OS Version: MacOS Big Sur 11.4

Steps to Reproduce:

1. Open a webview that accepts keyboard inputs, where those keyboard inputs update the html contents.

I have an extension that opens a webview; the html in the webview has a script tag, and uses the object from `acquireVsCodeApi()` to accept keyboard inputs, and also input from an html form. It works fine in all versions <= 1.58. In 1.59, keyboard inputs that update the webview html cause focus to shift away from the webview. In some cases, updating the webview's html causes rendering to fail completely, though the webview.html field is still populated.

The release notes for 1.59 claim that there was a major change from `<webview>` tags to "normal `<iframe>` elements", but includes no further details, no warnings of breaking changes, and no migration guide, so I have to assume this breakage is unintended/unanticipated.

**Comment by mjbvz** [comment]
Please share the source of a minimal example extension that demonstrates this issue

**Comment by ammkrn** [comment]
@mjbvz 

https://github.com/ammkrn/webview_bug_demo

I re-used the template from the official `catCoding` example so there may be some cat leftovers, but the only thing it does is load an HTML page with a counter, where the script in `main.js` accepts left/right (or h/l) keypresses. `webview.onDidReceiveMessage` updates the webview's html. Using 1.59, I experience the first issue reported above, where incrementing/decrementing the counter with a keystroke requires me to either click on or use tab in order to re-focus the panel. In 1.58, I could repeatedly press a key to repeat an action.

I'm not sure where to begin in terms of minimizing the second behavior (just not rendering) since the extension I'm using isn't simple. I've confirmed it works fine in 1.58, is there any effective way of comparing the webview developer tools output between the two versions?

**Comment by ammkrn** [comment]
@mjbvz 

Do you know if this is related to any other known issues/anything slated to be fixed? The other open issues mentioning webviews are sort of nebulous.

**Comment by ammkrn** [comment]
@sbatten Would it help to open a new issue for the second part? I'm still getting this behavior on 1.62.3.
