### ISSUE TITLE
Manage_Settings_DeveloperTool:There is no name defined for checkbox. (Accessibility)

### ISSUE THREAD

**Issue by nasc17** [microsoft/vscode#130722]
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/69922333/129271030-ad3f9382-b272-4fd6-876b-90fe32c49f6f.png)

Date: 2021-08-06T05:23:36.445Z
VS Code: 1.56.0
OS: Windows_NT x64 10.0.19043

Repro Steps:
Tab till settings button and press enter.
Tab till checkbox.
Open developer tool using ctrl+shift+I and check if the name is defined for the checkbox.

Actual:
There is no name defined for the checkbox.

Expected:
The name should be defined for checkbox

User Impact:
Screen Reader users will get wrong information regarding the checkbox

**Comment by roblourens** [comment]
Users will first focus the list item which has full aria info, then tab into the row to edit it. What "name" are you expecting for the checkbox?

**Comment by nasc17** [comment]
@roblourens A name for the checkbox defined as the text adjacent to it.

**Comment by roblourens** [comment]
That is read when the setting row is focused
