### ISSUE TITLE
Syntax highlighting fails after opening bracket on the new line

### ISSUE THREAD

**Issue by svetlym** [Microsoft/vscode#13077]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

In Typescript:

```
class Dummy
{
   // If I remove the newline after 'dummyMethod', highlighting of the next 'public' keyword works.
   public dummyMethod
   (
      // Some parameters.
   )
   {
      // Function body.
   }

   //  The 'public' keyword will not be highlighted.
   public anotherDummyMethod() {}
}
```

**Comment by svetlym** [comment]
Color theme is Light (Visual Studio).

**Comment by svetlym** [comment]
There is also similar issue for keyword 'constructor':

class Dummy
{
  // Keyword 'constructor' will be syntax highlighted.
  constructor() {}
}

class Dummy2
{
  // Keyword 'constructor' won't be syntax highlighted.
  constructor
  (
  )
  {
  }
}

**Comment by Tyriar** [comment]
Seems fine in the new TypeScript grammar which is currently testing as an extension so this is already resolved:

![image](https://cloud.githubusercontent.com/assets/2193314/19048349/cc7c7872-895a-11e6-89b7-bed41ed0e60d.png)

You can try it out here https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar
