### ISSUE TITLE
Bracket Pair Colorization ToDos

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#130767]
* [x] P1 hide customBracketPairs (and in the future merge it with language configuration)
ITextModelUpdateOptions
    * [x] remove configureBracketPairColorization from view model
* [x] P1 move backgroundTokenizationCompleted up to BracketPairColorizer: this.initialAstWithoutTokens is not undefined
* [x] P1 get rid of owners / use attached concept event
* [x] P1 in PairAstNode, why not have individual members instead of the children array them and handle iterating with the kind, maybe add firstChild / hasChildren
* [x] P1 hard coded to 3 colors - ColorProvider
* [ ] investigate many instances of InvalidBracketAstNode in sqlite3.c / consider reusing instances
* [x] P0 introduce some kind of limit for super large files, drive it by having it <100ms
    * [ ] a much better solution would be to split the work in 10ms chunks
* [x] P0 open 1GB file with brackets INSERT STATEMENT () / csv
* [ ] P2 Tokenizer: instead of working off a string, work off a ITextSnapshot
* [ ] P2 a test that tests end-to-end
* [x] Support readonly tree (copy on write)

**Comment by pkese** [comment]
Brackets in some languages are not matched correctly, e.g. in F#:

![image](https://user-images.githubusercontent.com/278492/167635547-3662e701-a598-4a6b-bff4-867590b0c291.png)

Also #139286

**Comment by hediet** [comment]
Closing, as the Bracket pair colorization feature is very stable now and the remaining tasks are not needed.
