### ISSUE TITLE
File name don't changed color in file list when file modies

### ISSUE THREAD

**Issue by FarrokhFarivar** [microsoft/vscode#130747]
Hi
My vscode has stop showing file has been modified by change color of file name in file list to the left side. It's not only mine but my other colleague as well.

My version is:
Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

**Comment by JacksonKearl** [comment]
You're referring to these markers? 
![image](https://user-images.githubusercontent.com/8586769/129404975-a0138d07-5ae9-49a9-a2ea-aa2e55f59f60.png)

I still see them, have you changed any "decorations" settings?
![image](https://user-images.githubusercontent.com/8586769/129405025-c0c0cf79-89af-45a5-b9d8-02138fdc1ba2.png)

**Comment by FarrokhFarivar** [comment]
No I haven't. However the one in the list: Workbench > Editor > Decorations: Colors I don't have in my list. The other options you listed is the same.

As I mention in my description this is not an isolated issue since my other colleague experiencing the same issue.
Need to mention I'm using MacBook Pro laptop if it would be any significant.

**Comment by JacksonKearl** [comment]
I have not been able to reproduce this on the same platform. If you can find a particular repo that causes this behaviour that may help, or try running in insiders. Also, try running via `code --user-data-dir {} --extensions-dir {}` ({} replaced with a temporary directory) and see if the issue reproduces there.
