### ISSUE TITLE
Problems and errors in the code are not reported

### ISSUE THREAD

**Issue by aquilesaugusto** [microsoft/vscode#130721]
Issue Type: <b>Performance Issue</b>

Hi. I've been using VS Code for a few days now and I came across a problem: Code problem warnings don't show up, which used to happen on the first day, but not now. For example, if there is a syntax error in my code, it won't be reported in the "Issues" tab. How can I solve?

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.0-80-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU          550  @ 2.00GHz (1 x 1994)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|3.83GB (0.76GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 0c331d47-9436-4703-9087-011f5530a98c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   130	  1724	code main
    0	    43	  1728	   zygote
    0	    67	  1765	     gpu-process
    0	    43	  1729	   zygote
    2	    82	  2606	     window (Relator de Problemas)
    0	    59	  1769	   utility
    0	   181	  1787	   window (● a.c - fifteen - Visual Studio Code)
    0	   106	  1821	     extensionHost
    0	    67	  1845	     watcherService
    0	   114	  1829	   shared-process
    0	    63	  1858	     ptyHost
    0	     0	  2620	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  2621	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● a.c - fifteen - Visual Studio Code)
|    Folder (fifteen): 8 files
|      File types: json(3) c(1) txt(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1) makefile(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.59.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by mjbvz** [comment]
What language is this for?
