### ISSUE TITLE
Option to show "dirname/" instead of file name for "index" files

### ISSUE THREAD

**Issue by atg** [microsoft/vscode#130734]
I often end up with many "index" files in my projects, e.g. `index.ts`, `__init__.py`, etc that are used by module systems to represent a directory.

Currently VSCode will help disambiguate these by displaying the directory path in small font next to the file name, however I still expend more mental cycles than I'd like dealing with these things.

It would be nice if VSCode could display these files as the name of the directory, i.e. instead of `index.ts [.../foo]` it would show `foo/ [index.ts]`. i.e.

instead of this

<img width="465" alt="oldtabs" src="https://user-images.githubusercontent.com/32292/129293119-ae2e2b25-153e-4c97-ab1c-5998f369c228.png">

have this:

<img width="427" alt="newtabs" src="https://user-images.githubusercontent.com/32292/129293130-e1199f98-e3de-4b85-b5ae-3d61471a0f53.png">

The three main places where this would be helpful are the Open Editors section, the Tab titles and File Finder (meta-P).

---

References:

https://github.com/microsoft/vscode/issues/72514#issuecomment-579228646

**Comment by alex-cory-kr** [comment]
+1

**Comment by d9k** [comment]
Any progress? Any extensions for achieving this behavior?

**Comment by benibenj** [comment]
This is now possible with the `workbench.editor.customLabels.patterns` setting.
- Show dirname for all files: `**`, `${dirname}`
- Show dirname for all files in folder `example`: `**/example/**`, `${dirname}`

**Comment by franciscolourenco** [comment]
@benibenj any chance of getting this to work in the "go to file" panel as well?

**Comment by benibenj** [comment]
@franciscolourenco We added it yesterday. It should works in todays insiders release and should be available in the next stable release.

**Comment by franciscolourenco** [comment]
@benibenj tried and it works, thanks! Was confused because the customLabel feature is already available in the march release.
