### ISSUE TITLE
Possibly enable a way to prioritize substrings over fuzzy matching

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#130797]
for example:
![image](https://user-images.githubusercontent.com/2644648/129425421-536a4e27-fc10-4ae5-a045-fbbec7031f56.png)

I would expect the `21` to be highlighted in `2021-7-21.md` not the 2 and then the 1 at the end.

**Comment by mak626** [comment]
Hey, I would like to assist on this issue, can someone point me at the code lines to get started?

**Comment by TylerLeonhardt** [comment]
I've added "quotes" support in #131292 and am planning on it releasing in stable as "experimental".

Now in the file picker `cmd+p` or `ctrl+p` you can wrap a word in quotes and it will search in a non-fuzzy way. 

However, I want to experiment with another way to do this next iteration.
