### ISSUE TITLE
Available update reported, but fails to install

### ISSUE THREAD

**Issue by cjpn** [microsoft/vscode#130763]
Issue Type: <b>Bug</b>

I repeatedly get available update messages, but when I download the update it fails to install and if I try to refresh using snap I get the message:  snap "code" has no available updates.

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-80-generic

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-80-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.24GB (11.26GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 340af7c1-0701-4991-afbd-6d60a1c0f700|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
vscode-pull-request-github|Git|0.26.0
better-cpp-syntax|jef|1.15.6
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.56.5
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
cmake|twx|0.0.17
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748
javagetstartedt:30351793

```

</details>

**Comment by joaomoreno** [comment]
This seems to be a problem in your OS, since the Snap store reports a newer build of code:

https://snapcraft.io/code

![image](https://user-images.githubusercontent.com/22350/132219989-faec3840-95da-4086-844d-247b832aed36.png)
