### ISSUE TITLE
C++ Debugger not launching

### ISSUE THREAD

**Issue by aayush749** [microsoft/vscode#130757]
Issue Type: <b>Bug</b>

When I try to debug my c++ code by pressing F5, the code gets compiled, but it is not launched in the debugger. 

Previously, the code was executed and the debugger started up, but suddenly now it has stopped working. Please fix this.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (2.09GB free)|
|Process Argv|--crash-reporter-id f320e1a2-8851-4b26-a06b-a26fd0fcd76c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
cpptools|ms-|1.6.0-insiders
java|red|0.80.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.3
vscode-java-test|vsc|0.31.1
vscode-maven|vsc|0.32.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by KaizokuJG** [comment]
yes same issue with me

**Comment by Ryukee** [comment]
me too

**Comment by asherhe** [comment]
Same problem
