### ISSUE TITLE
Jupyter Notebook displayed over terminal

### ISSUE THREAD

**Issue by siva-msft** [microsoft/vscode#130725]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60-insiders
- OS Version: Windows 10

Steps to Reproduce:
Been having this issue since 1.59-insiders.
When my notebook editor window is active, I am unable to use the terminal; and the terminal itself isn't displayed (or overlaying) correctly. A regression, perhaps?

![image](https://user-images.githubusercontent.com/60401095/129277663-4415fcb3-b736-45eb-9dae-50351558961b.png)

In the below image, "t" is the terminal screen that is mingled with the "n", that is the notebooks output.
![image](https://user-images.githubusercontent.com/60401095/129277720-a3a9976d-5c76-4869-8d2e-8cbb30064b70.png)

It works alright when any other editor is active/selected:

![image](https://user-images.githubusercontent.com/60401095/129277804-c69e642b-d1ea-4393-a124-968f1a1bb39f.png)

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/129292764-b7f28248-17b6-4b3f-b142-accebb9bc07b.png)

I'm not able to reproduce this issue, can you please share your terminal related settings?

**Comment by jeanp413** [comment]
Created a PR #130854 fixing this

**Comment by rebornix** [comment]
@jeanp413 thanks for your help, do you have a stable reproduce of this issue?

**Comment by jeanp413** [comment]
@rebornix sure:
1. open a notebook editor
2. resize panel as much as possible without maximizing it
3. toggle panel with <kbd>ctrl</kbd> + <kbd>J</kbd>
