### ISSUE TITLE
Hover could be more readable in this case

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13070]
1. Open debugService.ts
2. Hover over constructor
3. I think the hover could somehow be more readable, all these constructor arguments one after the other are not helping - could we colorize better?

![screen shot 2016-09-30 at 12 15 50](https://cloud.githubusercontent.com/assets/1926584/18988596/b78518ca-8707-11e6-882e-cb6e8d35b4d9.png)

**Comment by joaomoreno** [comment]
Both content and colorization comes from Typescript.

**Comment by waderyan** [comment]
This is closely related to #11415. Migrating this to TS as there is an API dependence with them.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11335
