### ISSUE TITLE
Weird letter spacing in Integrated Terminal for VS Code

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vscode#130751]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Darwin x64 18.7.0

It looks like the same error as in #120004. I actually never had this issue before the last VS Code update, and it is a little bit hard to reproduce.

Steps to Reproduce:

1. Open a directory with `code --disable-extensions .` until it happens.
![image](https://user-images.githubusercontent.com/15056323/129321078-e69a4e85-9913-40e9-a4cf-41ae8ef20d9e.png)

Closing and reopening a terminal, or resize the terminal solve the issue:
![image](https://user-images.githubusercontent.com/15056323/129321179-48fbee40-6d0e-4760-b7ae-c3d9dd405e8d.png)

It usually happens when I start my computer and opens VS code, which opens all my workspaces I was working on.

**Comment by meganrogge** [comment]
Seems like this is happening for a few people with the latest release

**Comment by PierreMarchand20** [comment]
It happened quite often a week ago, but now I have a hard time reproducing it TBH.

**Comment by tys1244147276** [comment]
This problem occurs when vscode is turned off and then turned on, regardless of whether I turn off the terminal before turning off

**Comment by tys1244147276** [comment]
my computer system is Mac OS Big Sur  11.4

**Comment by brown339** [comment]
Same here.
Windows 10.

**Comment by webaxones** [comment]
Same here on windows 10 v21H1, VSCode 1.60.1
I can't find a relation but the only thing I did before having this bug in my terminal was to install Github Desktop App.

**Comment by sjansen1** [comment]
Today i installed VS Code 1.66.2 (.deb from MS Website) on a fresh Ubuntu 22.04 (using X11). With my usual MesloLGS NF Regular.ttf Font that i use on another Linux and Windows machine with Code. On this new Ubuntu 22.04 machine i get that strange font spacing between letters. No change by disable extensions or reopen the terminal window. It works fine in other applications like gnome terminal.

**Comment by MohamedAliRashad** [comment]
I just updated vscode to 1.67.1 and this issue occurred.
Any ideas ?

**Comment by jcbritobr** [comment]
Here, it happens on pop os 64 bits.
![image](https://user-images.githubusercontent.com/6579862/178072730-e8b26391-760b-410e-8a24-118599ff2208.png)

**Comment by giviz** [comment]
Same issue here 
Version: 1.70.1
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
OS: Darwin x64 21.6.0

I only had that issue from time to time before, but since a recent release that introduced the gray/blue dots on each line of the terminal to rerun commands, I have the issue each time I reload vscode window (which is all the time to get typescript to refresh properly).

Setting Terminal > Integrated: Letter Spacing to 1 instead of 0 does fix the issue, but obviously make each line more spaced which is not ideal.

But at least that's a temporary fix I can live with :)

**Comment by theelderbeever** [comment]
Having the same problem on Ubuntu 22.04 using the `MesloLGS NF` font. Setting the letter spacing doesn't fix the issue per the suggestion above.

I use synced settings with vscode on my Mac M1 and there isn't any letter spacing issue there. Strangely, if I change the font to `monospace` it causes the spacing issue on the Mac but, doesn't resolve the issue on Ubuntu.

```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-46-generic snap
```

**Comment by daniel-anova** [comment]
Also having the same issue when using "CaskaydiaCove Nerd Font Mono" font. Changing the font to "monospace" makes the font spacing correct as reported in #120004 but no longer displays the expected symbol characters.

```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.12-200.fc36.x86_64
Sandboxed: No
```

**Comment by giviz** [comment]
The fix I'm using still works for me, but I've noticed that if I move the vscode window from monitor 1 to monitor 2 (they have different resolutions), then the active terminal now has a font spacing issue (but not as bad as without the fix). The other term do not have the issue, even if the active terminal is split in two.

If I move back the window to monitor 1, then the issue resolves.

**Comment by Tyriar** [comment]
The situation should improve a lot with https://github.com/microsoft/vscode/pull/168222, if anyone still sees this could you try repro in the xtemr.js demo and report to that repo? https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo
