### ISSUE TITLE
1st integrated terminal different from others

### ISSUE THREAD

**Issue by maucaro** [microsoft/vscode#130735]
Issue Type: <b>Bug</b>

I launch VSCode from the shelf on Chrome OS and I'd like the default integrated terminal to be a bash login shell so that an environment variable I set in ~/.profile is available. To that effect, I have the following in settings.json:
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash",
            "args": ["--login"]
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
    },
    "terminal.integrated.inheritEnv": true,
    "terminal.integrated.defaultProfile.linux": "bash"

Note that I've tried with both 'true' and 'false' in "terminal.integrated.inheritEnv" with similar behavior. The 1st terminal when VS Code starts des not have the environment variable set but any subsequent bash shells I open do have the environment variable in question set appropriately. This doesn't seem like expected behavior.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.4.109-26094-g381754fbb430
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.20GB (14.16GB free)|
|Process Argv|--unity-launch --crash-reporter-id 885f28eb-2cca-4baf-a315-b425c5077bf1|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.4.1
vscode-eslint|dba|2.1.23
vscode-dotnet-adapter|der|1.4.3
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
go|gol|0.27.1
cloudcode|goo|1.13.1
vscode-test-explorer|hbe|2.21.0
node-module-intellisense|lei|1.5.0
file-downloader|min|1.0.11
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-remote-extensionpack|ms-|0.21.0
test-adapter-converter|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-yaml|red|0.22.0
trxviewer|sca|1.0.1
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by IllusionMH** [comment]
May be same root cause as #128763

**Comment by maucaro** [comment]
It definitely does seem like the same root I cause. I just tried to split the 1st terminal (that is not behaving correctly); the split instance does the right thing. Feel free to merge.

**Comment by dfoverdx** [comment]
This bug seemed to start occurring about a week ago in VS Code Insiders.  It's quite frustrating.

**Comment by maucaro** [comment]
A workaround (per #128763) is to start VS Code with no terminal window visible. Or, if it is visible on startup, to create another one and close the first one. A little annoying but it works, at least in my case.
