### ISSUE TITLE
Problem marker: cursor pointer in header

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130705]
1. Execute `editor.action.marker.nextInFiles`
2. Hover over the file name
3. `cursor: pointer` usually means that the element is clickable.

![Screenshot (206)](https://user-images.githubusercontent.com/9638156/129252931-65dc0175-1720-4efc-b5cd-41a1ef95ee57.png)

**Comment by heynan0** [comment]
Could you write down the steps you took and what do you expect to happen?
