### ISSUE TITLE
could you please add a compact mode for pc mouse user, begging you my dear M$

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#130834]
please 
1. the title bar height
![image](https://user-images.githubusercontent.com/1876302/129452858-7aa5224d-4839-490c-be4a-4b9627e7ad68.png)

2. side bar width
![image](https://user-images.githubusercontent.com/1876302/129452869-2b786f57-f2ba-4f1f-8eb6-83e21017b0c7.png)

3. the editor tab height
![image](https://user-images.githubusercontent.com/1876302/129452891-9b8fcbf6-a0ad-4098-8bf7-3d4a712c9803.png)

4. the panel title height
![image](https://user-images.githubusercontent.com/1876302/129452903-b2044a14-4394-46cf-a009-848088889c77.png)

**Comment by moefear85** [comment]
bump

**Comment by sbatten** [comment]
@heartacker does zoom level not satisfy your requirements?

**Comment by heartacker** [comment]
> @heartacker does zoom level not satisfy your requirements?

no my  pc is  with  small  screen 

and i find  that  the ui is Overstretch，like vs 2019,we could  found that there  is more space for  code  editor

**Comment by sbatten** [comment]
cc @misolori

**Comment by misolori** [comment]
Also, please subscribe to https://github.com/microsoft/vscode/issues/115641 as that explores a density option
