### ISSUE TITLE
editor.tabSize keeps changing to 8 in user settings

### ISSUE THREAD

**Issue by typeoneerror** [microsoft/vscode#130876]
Issue Type: <b>Bug</b>

Been experiencing this for a few months now. When I open a file, it'll open with Tab Size: 8. When I then open User Settings `editor.tabSize` has changed to `8`. I did not change this. 

Tried with `editor.detectIndentation` set to `false` and `true`.

Steps to Reproduce:

1. Use VS Code
2. `editor.tabSize` randomly changes to `8` when opening a file. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.76GB free)|
|Process Argv|. --crash-reporter-id 4764d9f4-a305-4ef9-8271-b680dbae2a9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.1
Handlebars|and|0.4.1
Nix|bbe|1.0.1
toml|be5|0.5.1
vscode-tailwindcss|bra|0.6.8
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.4.0
vscode-firefox-debug|fir|2.9.4
vscode-graphql|Gra|0.3.16
vue|jcb|0.1.5
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.13.0
python|ms-|2021.5.842923320
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
remote-containers|ms-|0.177.2
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.6
remote-wsl|ms-|0.56.4
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.12.12
sqltools|mtx|0.23.0
language-liquid|nei|0.1.1
vetur|oct|0.34.1
ruby|reb|0.28.1
java|red|0.79.2
postcss|ric|2.0.0
rust|rus|0.7.8
slim|sia|0.1.2
dot|Ste|0.0.1
code-spell-checker|str|1.10.2
shellcheck|tim|0.14.1
haml|vay|1.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.34.0
vscode-java-dependency|vsc|0.18.4
vscode-java-pack|vsc|0.16.0
vscode-java-test|vsc|0.30.0
vscode-maven|vsc|0.31.0
vscode-icons|vsc|11.4.0
vim|vsc|1.21.0
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.28.0
viml|Xad|1.0.1

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your many extensions.

**Comment by typeoneerror** [comment]
@gjsjohnmurray I ran Start Extension Bisect
