### ISSUE TITLE
Apparently, git extension does not let me rename the root folder of a git repository (and all folders higher up the hierarchy)

### ISSUE THREAD

**Issue by aweebit** [microsoft/vscode#130836]
Issue Type: <b>Bug</b>

1. Run VS Code with `code .` or `code . --disable-extensions` in a folder that has a git repository in one of its subfolders (or a folder lower down the hierarchy)
2. Open a file from that git repository so that VS Code starts highlighting its modified files in the file explorer if it does not happen automatically
3. Try to rename the folder containing the git repository or a folder higher up the hierarchy

After following those steps, I get one of the following errors:

- `Error: EPERM: operation not permitted, ...`
- `Error: EBUSY: resource busy or locked, ...`

Sometimes it takes a while before an error shows up.

There is no program using the folder or one of its files other than VS Code:

![image](https://user-images.githubusercontent.com/36817090/129455752-b52c8598-d392-4dea-b960-416678dd3c13.png)

The issue is resolved by disabling Git in VS Code or closing VS Code and renaming the folder in Windows Explorer. But as you can imagine, I would not like to do that each time I want to rename a folder. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747
javagetstartedc:30351792

```

</details>

**Comment by eamodio** [comment]
This is by-design since vscode is rooted to that folder.
