### ISSUE TITLE
C syntax highlighter uses wrong colors after some macro definitions.

### ISSUE THREAD

**Issue by danielkasza** [Microsoft/vscode#13085]
- VSCode Version: 1.5.3
- OS Version: Ubuntu Gnome 16.04

Steps to Reproduce:

1. Create a new C file. 
2. Copy&paste this code:

````
/* Syntax highlighting works here. */

#define TEST1 f(5)

/* Syntax highlighting is all messed up here. */

/* Workaround. */
#define TEST2 (f(5))

/* Now it's good again. */
````

3. Observe that the second and third comments have the wrong color applied to them.

![vscodecolor](https://cloud.githubusercontent.com/assets/11418469/18997300/c6ce81b4-8701-11e6-80a2-082f91ef5492.PNG)

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#173
