### ISSUE TITLE
Laggy on Windows 11

### ISSUE THREAD

**Issue by viralcodex** [microsoft/vscode#130828]
Issue Type: <b>Performance Issue</b>

VSCode has become laggy and slow since Win 11 upgrade. Please resolve this optimization issue for your apps Microsoft.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.05GB free)|
|Process Argv|--crash-reporter-id 6e560d89-7d5f-41c8-969a-734f900dadda|
|Screen Reader|no|
|VM|80%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	  5812	code main
    0	    26	  2080	   crashpad-handler
   10	    96	  5160	   shared-process
    0	    70	 16756	     ptyHost
    0	    39	  5300	   utility
    0	   153	  6880	   window (● calculator.html - d: - Visual Studio Code)
    0	    16	  2132	     watcherService 
    0	    11	  9972	       console-window-host (Windows internal process)
    0	    75	  4356	     searchService
    1	  1282	 12500	     extensionHost
    0	    98	 17376	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=12500
    0	    73	 19320	       electron_node eslintServer.js 
    0	   105	 12256	   gpu-process
    0	    69	 16196	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● calculator.html - d: - Visual Studio Code)
|    Folder (): more than 120414 files
|      File types: dat(1155) txt(680) png(615) vcs(469) qml(438) vtf(382)
|                  vmt(367) dll(354) mp3(349) jpg(316)
|      Conf files:;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|2.1.23
vscode-html-css|ecm|1.10.2
jupyter|ms-|2021.8.1195043623
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
vscodeintellicode|Vis|1.2.14
beauty|yhp|0.0.2
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747
javagetstartedt:30351793

```

</details>

**Comment by Xoben** [comment]
ditto
