### ISSUE TITLE
Page-Up / Page-Down in git commit text box scrolls entire page up a little

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#13083]
Extracted from #11385 

I still see a little movement on page up and see the status bar is moved a little up

![screen shot 2016-09-30 at 17 10 11](https://cloud.githubusercontent.com/assets/10746682/18996551/045beb82-8731-11e6-95df-6c379fb32ebf.png)

@isidorn @joaomoreno FYI

**Comment by joaomoreno** [comment]
This is the feedback widget... which has no owner... I'll take it.
