### ISSUE TITLE
Python: interactive window not showing code execution status

### ISSUE THREAD

**Issue by Sutyke** [microsoft/vscode#130816]
July version(1.59) of VS Code came with new interactive window.

In the previous version interactive window shows [*] during the time when line is running. Once line completed, number appear [1]. In the new version user is required to click on the wheel sign to see if the line is still running. 

Please return the feature from the previous version back to see if the line of code is still running without any additional clicks.

Thanks for your help.

**Comment by amunger** [comment]
running indicator now shows
