### ISSUE TITLE
Terminal: inconsistent commands in palette

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130851]
The commands for creating new terminals are not very consistent:
* sometimes talking about "integrated" vs not
* sometimes saying "create terminal" vs "create new terminal"

![image](https://user-images.githubusercontent.com/900690/129470518-cb6e6653-586c-4943-a205-a0e7476a5f16.png)

**Comment by meganrogge** [comment]
I think this is because terminals in the editor area are, by definition, not external terminals. @Tyriar thoughts?

**Comment by bpasero** [comment]
I am not sure I follow, here is my suggestion:
* Create Terminal in Editor Area => Create New Integrated Terminal in Editor Area
* Create Terminal in Editor Area to the Side => Create New Integrated Terminal in Editor Area to the Side

**Comment by meganrogge** [comment]
What I'm saying is that it's redundant to say `Integrated` for terminals that will be created in the editor area since there's no way to create an external terminal in the editor area.

**Comment by meganrogge** [comment]
Perhaps we should remove `New` from all of these commands since creating means something new?

**Comment by bpasero** [comment]
I always understood "Integrated" as an indicator that the terminal will be created within VSCode (no matter where, panel or editor). An "external" terminal for me is always a terminal that opens outside VSCode.

In other words:
* "integrated terminal" = xterm
* "external terminal" = native OS terminal outside VSCode

Did I get that wrong?

**Comment by Tyriar** [comment]
@bpasero that's right.

Maybe we should just remove integrated at this point since the external terminal command is clearly labelled with external and all the other terminal commands don't mention integrated 🤔

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/130083727-e62ed3dc-22d4-46a5-b210-80d8210e00c8.png)

**Comment by bpasero** [comment]
Yes, I like 👍

**Comment by bpasero** [comment]
PS: If you where to keep "new" (i.e. "create new...") you would probably get more users, the ones typing "new" and the ones typing "create". I somehow always type "new"

**Comment by Tyriar** [comment]
Will change 👍
