### ISSUE TITLE
PHP Parsing String | Highlight

### ISSUE THREAD

**Issue by DinosDev** [microsoft/vscode#130843]
PHP Highlight with parsing arrays don't work!

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows 10 Pro 

Steps to Reproduce:

1. Create a file test with .php extension
2. Write this:
```php
<?php
$array = array(
    'Testing' => 'Test'
);

echo "Array: {$array['Testing']}";
```

3. See the  Highlight! It's bug!

![image](https://user-images.githubusercontent.com/71853418/129462948-aee637e0-3148-4903-bc0f-fc3696285094.png)

The color of ['Testing'] is a color of string...
I stay confused with this...

**Comment by roblourens** [comment]
What exactly is the problem?

**Comment by DinosDev** [comment]
Well, the Color is incorrect...
Is a color of string

**Comment by roblourens** [comment]
Not sure how to fix this since our themes don't have special colors for punctuation, so the string color for [] takes precedence here

**Comment by roblourens** [comment]
Actually we have the theme rules, we would need to improve the php grammar's parsing of php template strings to maybe include a `meta.embedded` scope. 

This is all we have for this case

```
punctuation.section.array.begin.php
string.quoted.double.php
source.php
meta.embedded.block.php
text.html.php
```

This would be a request for upstream https://github.com/atom/language-php/issues and would be difficult to do. I'm not going to file it, I am not sure it's practical
