### ISSUE TITLE
Debug Session focus issues after `Stepping` commands 

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#130888]
Hi,
Here is an issue (?) I've experienced when I was trying to find out a focus-related issue when killing a debug session.

Version: 1.60.0-insider (user setup)
Commit: 9dd4f31a21d63deea5e1fc322cfc802413b31d95
Date: 2021-08-16T05:21:19.431Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Start Debug Session twice
2. Focus `Session 1` 
3. Do a stepping

Expect:
- `Session 1` is still focused

Observed:
- `Session 2` takes the focus

https://user-images.githubusercontent.com/45362067/129535687-75ab2ff9-0bcb-44b6-a3be-efdd7080f84b.mp4

**Comment by isidorn** [comment]
Thanks a lot for this issue, however duplicate https://github.com/microsoft/vscode/issues/130321
I have just pushed a fix, and would appreciate if you try it out tomorrow with VS Code insiders
