### ISSUE TITLE
Blue bottom bar - add number of lines when selecting text

### ISSUE THREAD

**Issue by jakubmuda** [microsoft/vscode#130831]
It's a very small feature but would be usefull. When selecting text you can see the amount of characters selected. Can you add number of selected lines too? Something like `(200 selected in 5 lines)`

![image](https://user-images.githubusercontent.com/40349972/129451598-ead58e56-06f6-4b8c-9b5c-594dd466858f.png)

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/45726 and others.  That link mentions an extension that will show the number of selected lines.

**Comment by rzhao271** [comment]
Duplicate of #45726
