### ISSUE TITLE
Settings Sync: No way to specify individual platform-specific settings

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [microsoft/vscode#130805]
This was previously brought up in #88625; but the discussion was left a little bit narrow.

That discussion decided that #23251 would sufficiently satisfy the need for Settings Sync to allow specific settings to be left un-synced to specific platforms; but I think this feature would be widely useful *outside of* which-extensions-are-installed. Various features that almost *necessitate* platform-specific values for individual settings:

- Filesystem paths to installed binaries, for formatting programs and other tooling
- Fonts, sizes, window-locations, and the like, for which different values will be available on different platforms (I [use this myself](https://github.com/ELLIOTTCABLE/System/blob/3e3e30a85a25e41d31c938bb7a43d9be1f40e13b/Dotfiles/config/Code/User/settings.json#L42-L45), with the deprecated Settings Sync extension)

I'm opening this because the original Issue is bot-locked, and I figure this could use a little more discussion; even if it ends up being out-of-scope.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/5595
