### ISSUE TITLE
Go to reference doe not work. 

### ISSUE THREAD

**Issue by omaralfredo** [microsoft/vscode#130844]
Issue Type: <b>Performance Issue</b>

My goto references functions, in the menu.   it is not working I am using a MAC OS computer.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|-psn_0_282693|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   131	   894	code main
    1	    98	   898	   gpu-process
    0	    33	   900	   utility
    5	    90	   908	   shared-process
    0	    41	   911	     ptyHost
    0	     0	  1056	       /bin/bash -l
    0	    49	  1814	         dotnet run
    0	    66	  1852	           dotnet exec /Users/omarrodriguez/Desktop/INAP/Webinap/API/bin/Debug/net5.0/API.dll
    0	     0	  2224	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   254	  1022	   window (RITInapLoad.cs — Webinap)
    0	   139	  1023	     extensionHost
    0	    25	  1480	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1023
    0	    49	  1025	     watcherService
    0	    41	  1031	     searchService
    5	    74	  2218	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (RITInapLoad.cs — Webinap)
|    Folder (Webinap): 987 files
|      File types: cs(215) tsx(124) jpg(99) dll(83) png(65) ts(51) pdb(35)
|                  css(35) json(32) cache(29)
|      Conf files: csproj(5) launch.json(1) tasks.json(1) sln(1)
|                  package.json(1) tsconfig.json(1)
|      Launch Configs: coreclr(2);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-mysql-client2|cwe|4.0.5
csharpextensions|jch|1.3.1
csharp|ms-|1.23.14
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747
javagetstartedt:30351793

```

</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

**Comment by omaralfredo** [comment]
C#

**Comment by gjsjohnmurray** [comment]
/extC#

The functionality that isn't working for you is provided by one of your C# extensions.
