### ISSUE TITLE
join odjeto in javascripts 

### ISSUE THREAD

**Issue by jesuslike211** [microsoft/vscode#130827]
Hello, I work in javascript to join two objects {... xxx, ... xxx} I need the points but vscode in javscript allows me to make a point and when adding another point, the autocompletion appears and it does not allow me to add the three points. Could you help, I don't know if it's a bug in the vscode update, I have the July update, it won't let me do anything

**Comment by jesuslike211** [comment]
quisiera uqe me ayudaran  es muy desperante que no deje  agregar mas de dos puntos

**Comment by gjsjohnmurray** [comment]
/duplicate of #130096 which is candidate for July 2021 Recovery release
