### ISSUE TITLE
Parameter Hints: should use link hover color

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130864]
Similar to #121536, #121521, #125956, #129193, #126752

```js
"workbench.colorCustomizations": {
	"textLink.foreground": "#ffae00",
	"textLink.activeForeground": "#00a2ff",
}
```

Links on hover in parameter hints popup should use `textLink.activeForeground`.

**Comment by jeanp413** [comment]
Created a PR #130963 fixing this
