### ISSUE TITLE
It's too easy to enter a breakpoint when just clicking to set cursor pos in cell

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#130833]
Version: 1.60.0-insider (user setup)
Commit: 58454f7bec838f79fe2422ab5914419147d82e40
Date: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

1. Line numbers are off for notebooks by default
2. I found that as I'm editing I often want to click such that the insertion caret is at the start of the line. This is either to prepend something, OR to start a click drag selection on the line.

![image](https://user-images.githubusercontent.com/11685408/129452606-38ddeaa5-c037-4268-baba-0cbac1f47467.png)

It's too easy to accidentally set a breakpoint in this situation. Quite annoying.

**Comment by greazer** [comment]
Couple ideas that could help, but may be difficult to pull off and aren't foolproof...

- Require that the user double click to set a breakpoint 
- Require that the user hold the mouse button down for a second or so to set the bp. Much like modern iphones and ipads support "pushing harder on an on-screen button" to make something different happen. Of course, you could indicated how long the hold needs to occur by using an animation of some kind as the mouse button is held down.

Perhaps only do one of the above only if line numbers are not displayed. Otherwise use the same behavior as the regular editor.

**Comment by greazer** [comment]
I noticed that with the code folding chevrons, if you accidentally left click on the chevron, then drag to the right (simulating trying to select the line of code) nothing happens. Code is not folded or unfolded. Therefore...

We could consider the same behavior for breakpoints. Instead of enabling the breakpoint on mouse down, enable it on mouse up. That way if I click and drag to select text, I won't accidentally set or unset a breakpoint. This doesn't totally solve the irritation of trying to find exactly the right place to click to set the caret at the start of the line, but it can help prevent bp's from being set.

**Comment by roblourens** [comment]
@kieferrm and I discussed changing the spacing to add a few pixels between the code and the breakpoint margin. @rebornix any idea how to do that?

**Comment by roblourens** [comment]
Actually just going to use https://github.com/microsoft/vscode/issues/132800 for this

Showing the folding margin all the time makes the problem basically go away
