### ISSUE TITLE
Tasks error with MSIX/Windows Store installed execution aliases

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#130863]
The following task definition
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run winget",
            "type": "process",
            "command": "winget",
            "args": [
                "list"
            ],
            "problemMatcher": []
        }
    ]
}
```
errors with
![image](https://user-images.githubusercontent.com/1036561/129488552-c057e5b7-e9e5-43fa-81ae-15ef3cb66bc2.png)

`winget` is MSIX installed and adds itself to the `PATH` via an execution alias (I believe it is on everyone's system by default now on Windows 10). It seems that tasks in VS Code are generally broken with commands that are installed in that way.

Here is some speculation what is going on, but nothing definitive: the path that is shown in the error message is a symlink that MSIX creates that points to the actual binary that is located somewhere else. All the other execution systems in VS Code (like run a terminal, start language server client etc) seem to work fine with that, but maybe there is some extra check in the task running system that somehow can't deal with that?

This is becoming a major problem for the Julia extension: we have a new Julia deployment strategy via the Windows Store, and we expose custom tasks extensively in the Julia extension, but that entire area of functionality is now broken in the combo with the Windows Store deployed Julia version. The reproducing example here in this issue is the simplest way I found to reproduce this, but the case that is the real problem for us is [this](https://github.com/julia-vscode/julia-vscode/blob/474634e00312c6a4b8efc5fdd25386a0795e4d14/src/tasks.ts#L43), i.e. the entire tasks that we expose from the Julia extension.

It would be great if this could be fixed with priority :)

**Comment by davidanthoff** [comment]
Here is another clue:

![image](https://user-images.githubusercontent.com/1036561/129489934-619beaf6-b3d3-4152-9076-e373ff4c7126.png)

Note how both `winget` and `julia` have a symlink that points to an exe file with a different name. Those are valid for MSIX installs, but maybe that is causing the problem?

**Comment by pfitzseb** [comment]
I haven't looked into this too much, but it seems like it would be best if `Task` execution simply doesn't try to `stat` the file at all, since there doesn't seem to be a way to do that correctly (if I interpret [this](https://stackoverflow.com/questions/56974927/permission-denied-trying-to-run-python-on-windows-10) correctly).

**Comment by davidanthoff** [comment]
Woah, that was fast, much appreciated :)

**Comment by alexr00** [comment]
@davidanthoff yep, you can just use the insiders build to test it. The bot has posted instructions now that there's a build with the change in it :).

**Comment by davidanthoff** [comment]
/verified

Yes, that fixes it, I just tried. Thanks a lot!
