### ISSUE TITLE
Same code is running again and again even if the code is different

### ISSUE THREAD

**Issue by SuryanshD** [microsoft/vscode#130849]
Issue Type: <b>Bug</b>

When I am running the Code the same Code which was earlier is running again and again even if the code is different. Tried uninstalling VS Code and reinstalling it again but the problem persists. Please help as soon as possible.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.88GB free)|
|Process Argv|--crash-reporter-id 30940f08-60b0-4fcd-ac8f-ceca7eee9b8b|
|Screen Reader|no|
|VM|0%|

Extensions
---|---|---
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
cpptools|ms-|1.5.1
LiveServer|rit|5.6.1

vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30351747

**Comment by gjsjohnmurray** [comment]
What language are you coding in? If it is a compiled language have you started a build task?

**Comment by SuryanshD** [comment]
> What language are you coding in? If it is a compiled language have you started a build task?

It's HTML

**Comment by gjsjohnmurray** [comment]
> When I am running the Code

How are you doing this?

Please also confirm that you save your changes before doing this.

**Comment by SuryanshD** [comment]
Clicking F5 for run the code and before it I am saving it to .. But there is a blue line that comes at the last of your screen it always shows the old program name on it and when I am running the code the last old code runs and gives the output.
