### ISSUE TITLE
Vscode cannot connect to remote Linux （_WebSocket close with status code 1006）

### ISSUE THREAD

**Issue by sytlq999** [microsoft/vscode#130887]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59.0
- OS Version:win10 ltsc
![12343](https://user-images.githubusercontent.com/89000778/129527222-2b993e1e-d05a-49e8-ac31-01377ed6fa11.jpg)
![2234240](https://user-images.githubusercontent.com/89000778/129527356-a3d6235c-66b7-4a3c-b94d-6298a0314bac.jpg)

Remote connection to Linux. After entering the password, there are two prompts on the right 

coude not fetch remote environment
failed to connect to the remote extension host server (error: websocket close with status code 1006)

And the terminal cannot input and  stop as below
![12345](https://user-images.githubusercontent.com/89000778/130026954-d354f8c1-6145-47ca-a791-b62f2cd49813.jpg)
![123456](https://user-images.githubusercontent.com/89000778/130026970-3db33d65-9271-4449-9bc6-99eab7ef9381.jpg)

The remote directory  could not be loaded
I had tried countless times    in many ways
Reinstall vocode，delete ~/.vscode - server/  directory,and  so on .
What the hell should I do.
 
Steps to Reproduce:
![remote1](https://user-images.githubusercontent.com/89000778/130037063-4ff7b1f9-df48-416f-ac06-9b9f21c3c9f1.gif)

**Comment by NoxLP** [comment]
Well, I've finally solved it uninstalling VSCode, removing manually all vscode related folders from windows and WSL, and reinstalling VSCode.

**Comment by Renkunzhao** [comment]
@NoxLP Hi, I'm facing the same issue. Could you please list related folders you removed manually? (My English is limited, sorry about that.)

**Comment by Renkunzhao** [comment]
![1](https://user-images.githubusercontent.com/57552000/141670733-94a964e5-9939-4b46-90d2-781668f1e1ec.png)
![2](https://user-images.githubusercontent.com/57552000/141670735-df46bce9-0561-4066-9c69-4a7247633f79.png)
![3](https://user-images.githubusercontent.com/57552000/141670737-f823ba6b-f8c2-4c64-abfb-f883b366858e.png)
