### ISSUE TITLE
Problem With Run Code Shortcut Key 

### ISSUE THREAD

**Issue by Umair-N** [microsoft/vscode#130889]
Issue Type: <b>Bug</b>

The run code shortcut ctrl+alt+N usually runs the code but sometimes it prints some kind of symbol (ṇ)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (1.24GB free)|
|Process Argv|--crash-reporter-id 1f007d21-272c-4514-b310-5ac5eefbeaa4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
makefile-boilerplate|Alp|0.1.9
code-gnu-global|aus|0.2.2
vscode-django|bat|1.6.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
doxdocgen|csc|1.3.2
c-cpp-compile-run|dan|1.0.14
python-extension-pack|don|1.6.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
pythonsnippets|frh|1.0.2
kotlin|fwc|0.2.23
better-cpp-syntax|jef|1.15.6
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.15.0
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
notepadplusplus-keybindings|ms-|1.0.7
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
code-spell-checker|str|1.10.2
python|tht|0.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8
material-theme|zhu|3.11.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by gjsjohnmurray** [comment]
Which command is that keycombo bound to in your VS Code? It is not a default binding.
