### ISSUE TITLE
HTML AND CSS CODE ISSUES

### ISSUE THREAD

**Issue by Forlahuang2003** [microsoft/vscode#130871]
Hello,
           May I ask what happened to Visual Studio Code seemed like not functioning CSS AND JS CODE, example-as entered exclamation mark "!" usually can be referenced to select automatically html 5 and syntax, but now it can't.  And how to fix it please help out ...etc. Thank you .

**Comment by ArturoDent** [comment]
What language is shown for the file in the bottom right corner of the application window?

**Comment by Forlahuang2003** [comment]
Hello, 

         The following language is shown inside my Visual Studio Code when opened html file  and entered any code . Wonder if someone messed up my code without a secure key by  hacking into  my webpage ?     Microsfoft Edge Browser was unable to display CSS result  after styling color  and  position ,meantime, tested in Dreamweaver Software wasn't worked ,neither. Please help out such as a thing . Thank you so much.

**Comment by Forlahuang2003** [comment]
Hello, 

         According to a message popping up said that," git repository has too many active activities" and Source: git Extension".  Is Visual Studio Code needed to download git extension?
