### ISSUE TITLE
Custom ANSI colors in integrated terminal

### ISSUE THREAD

**Issue by rschweter** [Microsoft/vscode#13087]
@Tyriar this issue (https://github.com/Microsoft/vscode/issues/143) mentions the ability to setup custom ANSI colors via settings.json but I haven't found how to do this yet. Is it supported?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6979

**Comment by rschweter** [comment]
Ah, thanks @Tyriar
