### ISSUE TITLE
No inputs were found on jsconfig.json with basic config and project

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#130817]
Issue Type: <b>Bug</b>

1. Create a basic JS project
1. Use `.mjs` files so you can use module system with node
1. Add a tsconfig file with the following basic configuration

``` 
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}
``` 

See the error

```
No inputs were found in config file '/.../js-file-mover/jsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["node_modules","**/node_modules/*"]'.ts
```

I also tried to add an include path with no luck:

```
{
  "compilerOptions": {
    "module": "es2015",
    "checkJs": true,
    "target": "es6"
  },
  "include": ["./src/**/*.mjs"],
  "exclude": ["node_modules", "**/node_modules/*"]
}

```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.20GB free)|
|Process Argv|. --crash-reporter-id 3bf10e6d-54c9-4df4-8aaa-781f2b9fc1b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (121)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
project-manager|ale|12.3.0
auto-add-brackets|ali|0.11.0
Handlebars|and|0.4.1
jest-snippets|and|1.8.0
vscode-apollo|apo|1.19.4
gitstash|art|4.0.0
material-ui|Aru|1.0.0
All-Autocomplete|Ati|0.0.23
tailwind-docs|aus|1.4.0
vscode-django|bat|1.6.0
file-browser|bod|0.2.10
vscode-tailwindcss|bra|0.6.13
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
keymapceditor-vsc|Cia|0.7.7
vscode-devtools-for-chrome|cod|0.0.7
bracket-pair-colorizer-2|Coe|0.2.1
systemd-unit-file|coo|1.0.6
vscode-svgviewer|css|2.0.0
python-snippets|cst|0.0.9
danielo-node-snippets|dan|1.8.13
danielo-vsc-tools|dan|1.0.3
vscode-eslint|dba|2.1.23
javascript-ejs-support|Dig|1.3.1
vs-code-snippet-generator|dku|1.1.0
githistory|don|0.6.18
python-extension-pack|don|1.6.0
jest-test-language-support|dpl|1.30.2
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-powertools|ego|0.64.0
prettier-vscode|esb|8.1.0
esy-vscode|esy|0.0.2
vscode-search-open-all-results|fab|1.0.3
vimL|fal|0.0.3
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
reasonml|fre|1.0.38
vscode-extension-react-ts-snippets|fun|1.2.0
monkey-c|ghi|0.4.0
lintlens|ghm|3.0.0
copilot|Git|1.3.2335
vscode-pull-request-github|Git|0.29.2
go|gol|0.27.1
vscode-graphql|Gra|0.3.16
ansible|haa|0.2.8
vscode-nginx-conf-hint|han|0.1.0
githd|hui|2.2.4
customize-ui|ioc|0.1.54
monkey-patch|ioc|0.1.15
fuzzy-search|jac|0.0.3
yuml|Jai|3.5.1
search-editor-apply-changes|jak|0.1.1
svg|joc|1.4.9
vscode-peacock|joh|3.9.1
styled-components-snippets|jon|0.10.0
open-in-vim|jon|0.6.0
tw5-syntax|jos|1.0.4
vscode-styled-components|jpo|1.6.6
magit|kah|0.6.20
favorites|kdc|2.4.5
vscode-home-assistant|kee|1.21.0
MagicPython|mag|1.1.0
vscode-wrap-console-log|mid|1.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.15.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-ssh-explorer|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.5.1
vscode-typescript-next|ms-|4.5.20210813
debugger-for-chrome|msj|4.12.12
vscode-purty|mva|0.6.0
color-highlight|nau|2.4.0
incrementor|nms|1.0.3
indent-rainbow|ode|7.5.0
docthis|oou|0.8.2
platformio-ide|pla|2.3.2
python-string-sql|ptw|1.1.0
geo-data-viewer|Ran|2.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
partial-diff|ryu|1.4.3
jinjahtml|sam|0.16.0
vscode-javascript-booster|sbu|14.0.1
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.5
code-spell-checker|str|1.10.2
code-spell-checker-spanish|str|1.0.8
vscode-stylelint|sty|0.86.0
control-snippets|svi|1.9.1
json-schema-validator|tbe|0.1.0
open-spec-file|the|0.0.6
errorlens|use|3.4.0
highlight-matching-tag|vin|0.10.1
template-strings|vit|0.0.6
vscode-icons|vsc|11.6.0
material-ui-snippets|vsc|3.3.3
vim|vsc|1.21.6
vspacecode|VSp|0.10.1
whichkey|VSp|0.9.2
vscode-wakatime|Wak|15.0.0
literally-html|web|0.1.3
jinja|who|0.0.8
vscode-file-extra|wil|3.1.0
glean|wix|5.2.2
change-case|wma|1.0.0
jinja2-snippet-kit|Wya|2.0.0
template|yon|1.3.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6
es6-string-javascript|zjc|1.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by danielo515** [comment]
It is working now after renaming all the `.mjs` files to js and setting type as module  `"type":"module"` on package.json.
Seems to be because TS doesn't understand mjs files, they don't exist for TS therefore doesn't exist for VSC

**Comment by mjbvz** [comment]
Mjs support is tracked upstream by https://github.com/microsoft/TypeScript/issues/27957
