### ISSUE TITLE
API for extensions previewing in HTML

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#1308]
Like Markdown preview, I want to build extensions that preview other types of files in HTML/CSS/JS. Please open up API for this type of extensions.

**Comment by Stephanvs** [comment]
Actually I was trying to do something similar like this for my graphviz extension, I want to be able to generate some html based on the current active document and preview it in a similar way as the Markdown preview. I found the way the Markdown extension does this, but it's not available as public API's

**Comment by jrieken** [comment]
Yeah, the markdown stuff isn't an extension yet. I can think of either a special `HTMLTextDocument`, a mode when opening an editor, or some command. Needs some thinking...

**Comment by Stephanvs** [comment]
Also I noticed the `OpenPreviewToSideAction` and related `Action` class, which can toggle the preview mode, something like that would also be useful to do.

**Comment by jrieken** [comment]
yeah, tho that action takes undocumented context... We need to elevate it

**Comment by alefragnani** [comment]
I was also looking for this :+1: 
@jrieken , you could also look (when deciding the new APIs) for other supported file types, like images (png, jpg).

**Comment by jrieken** [comment]
related to #272. Idea goes like this:

1. extension creates a virtual document with Uri & content
2. have command to _preview_ html/md from Uri

**Comment by be5invis** [comment]
And maybe the API can support more preview types, for example, TeX?
