### ISSUE TITLE
The terminal process failed to launch: Path to shell executable “___” is not a file of a symlink.

### ISSUE THREAD

**Issue by jacobfriedman** [microsoft/vscode#130800]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.59.0
- OS Version: Linux x64 Ubuntu 20 Node 14.16 (NVM)

The terminal process failed to launch: Path to shell executable "___" is not a file of a symlink.

___ is logtalk, in my case. I believe vscode is trying first to find the executable in my directory, but failing on first try. The call is from an extension; the name of the language in the extension is the same, and I the name of the object used in the extension is the same.
 
Steps to Reproduce:
1. Put a folder with the name of the executable you want to launch in your home directory
2. Try to launch the executable as an object from an extension.
--

<br class="Apple-interchange-newline">

**Comment by meganrogge** [comment]
> ___ is logtalk, in my case. I believe vscode is trying first to find the executable in my directory, but failing on first try. The call is from an extension; the name of the language in the extension is the same, and I the name of the object used in the extension is the same.

This is confusing me. Can you please reiterate it in a different way?
