### ISSUE TITLE
How to make colors of activity bar more consistent to color theme `Light+`?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vscode#130813]
![image](https://user-images.githubusercontent.com/3665590/129439864-fff0495e-e8eb-4456-b8b6-648226487373.png)

When using color theme `Light+`, by default the colors of the activity bar look inconsistent, how to make it more consistent to the theme?

**Comment by playgithub** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Color theme issue when reloading window after change of System color scheme (#130160)](https://www.github.com/microsoft/vscode/issues/130160)
> * [all colors are just washed away and no highlighting (#126931)](https://www.github.com/microsoft/vscode/issues/126931)

no

**Comment by misolori** [comment]
Our default light theme has always had the same activity bar colors. If you want to change these you can edit your user settings via:

**Comment by playgithub** [comment]
Thanks it woks.
As a note, settings as below is more consistent to the theme in colors
```json
"workbench.colorCustomizations": {
    "[Default Light+]": {
        "activityBar.foreground": "#000000",
        "activityBar.background": "#eeeeee"
    },
}
```
