### ISSUE TITLE
[JS] Spread operator code completion problem

### ISSUE THREAD

**Issue by cpusam** [microsoft/vscode#130842]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:1.59.0
- OS Version: XUbuntu 20.04
Steps to Reproduce:
1. create a var of type Object (var obj = {A:0, B:0})
2. now, try assign the object to another var but with operador spread (var other = {...obj})
3. note, while you are typing the dots, the VScode put the members of the obj, like it was pressed enter to choose.

**Comment by IllusionMH** [comment]
/duplicate of #130096 which is candidate for July 2021 Recovery release
