### ISSUE TITLE
Test UI: Right-click context menu action executes against wrong item when multiple tests selected

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130873]
Version: 1.60.0-insider (Universal)
Commit: 7c25c174726ab969db3f99058cdf24bcfae1cfbe
Date: 2021-08-11T05:13:17.497Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.5.0

**Steps to Reproduce:**

1. Create extension that contributes a command to `testing/item/context`
2. Populate test UI with 3 tests and select all 3 tests (i.e. multi-select)
3. Right-click on the bottom item and run the contributed command

**Expected Outcome:**

Either: 

(a) the command is executed for all test items, or
(b) the command is executed for the item where I right-clicked

**Actual Outcome:**
The command appears to be executed only once, for the first test that appears in the Test Explorer (not the test that I right-clicked).

---

I like the idea of being able to run a command for multiple selected items (i.e. behavior (a)). I also think it would be ideal if there was a `context key` that I could use to know that multiple items are selected so that I can show/hide commands based on whether command should run in "single" or "multiple" context.

**Comment by connor4312** [comment]
All items will be given as positional arguments, so if you deal with multiple you can handle then via `registerCommand('myCommand', (...items) => {})`
