### ISSUE TITLE
Slow intellisense & autocomplete of .js files

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#130807]
Latest version 1.59 has very slow intellisense on .js files. Also if I comment out a line with // the green highlighting doesn't appear over all characters in the commented line, but only on some of them, it looks very strange. The line is greened out only after I switch to another tab and back or if I hover over the comment with the mouse and then "Loading..." appears as tooltip for a few seconds and only then the comment turns completely green. It is indeed, very slow. Autocompletes are also appearing only after about 4-5 seconds... very annoying.

_Originally posted by @lorand-horvath in https://github.com/microsoft/vscode/issues/129099#issuecomment-898831022_

**Comment by lorand-horvath** [comment]
Also noticed that CPU usage increases a lot as soon as I start typing anything in a JS file and is kept high for the 4-5 second duration while Intellisense/autocomplete is doing its job... and goes back to normal as soon as it comes back with the autocompleted result. This only occurs in version 1.59.0

**Comment by lorand-horvath** [comment]
Adding support for parameter hints inline for TS 4.4 in #16221 might have caused the slowness/lag of intellisense in the July 1.59.0 release #128444

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also the July release still uses TS 4.3.5 unless you switch to use a workspace version of TS

**Comment by sachinraja** [comment]
I am also experiencing this with inlay hints. Turning them off fixed it for me.

**Comment by mjbvz** [comment]
Closing as not actionable without more information

**Comment by lorand-horvath** [comment]
@sachinraja Are you using mongoose? Please see https://github.com/Automattic/mongoose/issues/10349
