### ISSUE TITLE
Editor flashes while stepping in the debugger

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#130802]
## Environment data

-   VS Code version: 1.59.0
-   Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS and version: windows 11, 21H2, build 22000.132
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Anaconda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Pylance language server 2021.8.1 (pyright abd41b72) starting

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Debugger stepping should always be nice and smooth.  See video below.

## Actual behaviour

See Video: https://user-images.githubusercontent.com/18707114/129293365-0f555632-a39b-4554-b191-0fbbf8a06f6c.mp4

## Steps to reproduce:

Not sure, but it may have something to do with Watch and CALL STACK panels.  When I collapsed those away the flashing stopped.

**Comment by matthewbastien** [comment]
I'm experiencing the same issue. I suspect that it's a bug with the fix for #125144

This happens when I'm debugging a multi-threaded program and more than one thread is stopped on a breakpoint. When stepping through one of the stopped threads, VSCode will briefly focus the other stopped stack frame before jumping back after the current thread completes the step action.

**Comment by isidorn** [comment]
This should be fixed with latest VS Code insiders. If you still see it with latest Insiders let me know and I will reopen

**Comment by lovettchris** [comment]
ok, cool, thanks.
