### ISSUE TITLE
Test UI: Provide a mechanism to control sort order other than by label

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#130882]
The Test Explorer `Sort By Location` uses the test label as the sort key when a `uri` and `range` is not provided. Depending on the test runner, intermediary nodes in the Test Explorer may be show (for example, for describe blocks).

For example, you may have a test file with a structure as shown below:
```
- src/components/feature/app.spec.ts
    - describe block Z
            - test 1 (Line 100)
    - describe block A
            - test 2 (Line 200)
```

In this case, the `range` and `uri` exist only for the `test 1` and `test 2` nodes. This results in the order of the nodes being ordered as shown below (line 200 is before line 100):

```
- src/components/feature/app.spec.ts
    - describe block A
            - test 2 (Line 200)
    - describe block Z
            - test 1 (Line 100)
```

As an extension developer, it would be nice to be able to control the sort order in this case. I guess it's possible for the sort order of leaf nodes to ripple up to the parents and you wouldn't have this problem.

**Comment by connor4312** [comment]
I think the recommendation in this scenario is to have a `range` on the `describe` blocks as well. This is a feature request for something like `sortText`, but I'm on the fence about whether this'd be useful or meaningful to show to users, we'd have "Sort by Location", "Sort by Status", or "Sort by Extension Order?" That does not seem very predictable.

**Comment by smcenlly** [comment]
> I think the recommendation in this scenario is to have a range on the describe blocks as well.

We had originally taken this path but unfortunately for many test runners, we don't have a range for the describe blocks. The describe blocks get reported as an array on the test in some cases. For example:

```
- src/components/feature/app.spec.ts
    - "describe block A"
        - "describe block B"
            - "test 1" (Line 100)
```

May be returned as:

```json
{
  "results": [
    {
      "testName": "test 1",
      "suite": ["describe block A", "describe block B"]
      "status": "passed"
    }
  ]
}
```

In this case, there's no `range` for the describe blocks so you'd have to do something special to try work them out (which may be unreliable) - e.g. string matching maybe?

> This is a feature request for something like sortText

Yes - I think this would work.

> I'm on the fence about whether this'd be useful or meaningful to show to users, we'd have "Sort by Location", "Sort by Status", or "Sort by Extension Order?" That does not seem very predictable.

I completely agree. I would not expose another sort order to the user. I reviewed the sort logic yesterday for `Sort by Location` but not for `Sort by Status`. I would suggest sticking to two sort orders (or perhaps 3 if you add `Sort by Duration`). Under the covers, if `sortText` exists on a TestItem, it will be used instead of `label`.

I think its correct to sort by uri/range before custom sort text but an argument could be made either way. Since it is possible to provide a uri with fragments (e.g. line number), might be worth updating the sort logic at that point to also consider that case as it does not right now.

I think this keeps the UI the same, and provides flexibility in the API. Also means that API behavior remains the same unless people want a custom sort order.

---

If you want to go ahead with this feature, I'm happy to help code it.

**Comment by connor4312** [comment]
Sure, I would be happy to accept a PR that added optional `sortText` on the test items

**Comment by smcenlly** [comment]
Have created a PR for this: https://github.com/microsoft/vscode/pull/132099

**Comment by connor4312** [comment]
Thanks for the PR! This iteration is our housekeeping iteration, I will put this in as an API proposal for November.

**Comment by rchiodo** [comment]
@connor4312 can you provide some verification steps? Thanks.

**Comment by smcenlly** [comment]
@rchiodo - [this](https://github.com/microsoft/vscode/pull/132099) may help: 

> This repo may be used for testing: https://github.com/smcenlly/vscode-issue-130883. Change `sortText` and `label` to confirm `sortText` is being used instead of `label` when `sortText` exists.
> 
> **./src/extension.ts**
> ```
> import * as vscode from 'vscode';
> 
> export async function activate(context: vscode.ExtensionContext) {
>   const ctrl = vscode.tests.createTestController('duration-bug', 'duration-bug');
>   const parent = ctrl.createTestItem('TestParent', 'Test Parent');
>   const testItem1 = ctrl.createTestItem('A', 'A');
>   const testItem2 = ctrl.createTestItem('B', 'B');
>   (testItem1 as any).sortText = 'B';
>   (testItem2 as any).sortText = 'A';
>   parent.children.add(testItem1);
>   parent.children.add(testItem2);
>   ctrl.items.add(parent);
>   context.subscriptions.push(ctrl);
> }
> ```

**Comment by rchiodo** [comment]
Thanks @smcenlly.

/verified

I changed 'sortText' in that sample and it changed the sort order.
