### ISSUE TITLE
build/lib/electron.ts throw error when working on macOS which has case-sensitive disk.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#130886]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Prepare disk that is Case-sensitive.
![image](https://user-images.githubusercontent.com/7701575/129527313-2ada0187-6f15-4af5-a0c6-dd6c1299255c.png)
2. git clone `vscode` code base, run `yarn` `yarn watch` and `./scripts/code.sh`
3. Error throws since glob cannot find `Bower.icns` (which is bower.icns)

Currently `build/lib/electron.ts` not care about case-sensitive disk. Add `.toLowerCase()` to icon at https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L64 and https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L87 will fix this bug.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/129665
