### ISSUE TITLE
The code is automatically restored

### ISSUE THREAD

**Issue by gangells** [microsoft/vscode#130819]
Issue Type: <b>Bug</b>

When I open a VUE project with VSCode, a security prompt appears: Do you trust the authors of the files in this folder? I selected Yes and my code was automatically restored to the historical version

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.46GB (6.77GB free)|
|Process Argv|--crash-reporter-id e4afe423-cf8d-4ed8-9b46-b311046c8ce9|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.59.3
vetur|oct|0.34.1
java|red|0.80.0
LiveServer|rit|5.6.1
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by sbatten** [comment]
@gangells Can you provide more details on the issue? Are you saying that some changes were lost? Can you reproduce this issue reliably? If so, what are the steps?
