### ISSUE TITLE
C++ Debugger broken after update

### ISSUE THREAD

**Issue by Riaz-404** [microsoft/vscode#130885]
Issue Type: <b>Bug</b>

After updating to July 2021(version 1.59), C++ debugger isn't working.  After starting debugging, code build successfully, then nothing happens. Even the debug action pane hides automatically.  I went back to previous version(1.57); it works perfectly there. 

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.70GB free)|
|Process Argv|--crash-reporter-id ea3c0203-6fd4-42a6-ae55-75566abf23b8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.3
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.14
font-switcher|eva|4.0.1
code-runner|for|0.11.5
error-gutters|Igo|1.0.1
fluent-icons|mig|0.0.12
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.9.0
tabnine-vscode|Tab|3.4.22
ayu|tea|0.20.2
errorlens|use|3.4.0
vscodeintellicode|Vis|1.2.14

(9 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/extC++

Debugging in VS Code is implemented by language-specific extensions.
