### ISSUE TITLE
Create new Folder from selection

### ISSUE THREAD

**Issue by lachieh** [microsoft/vscode#130832]
I would like the ability to be able to select a few files from the Explorer Side Bar and be able to create a new folder from the selection. Personally, I feel that this feature would be a useful addition to VSCode. macOS has had this feature for a few versions now and I find myself using it while refactoring.

Here is an example:
![new-folder](https://user-images.githubusercontent.com/1687902/129452504-392fe741-3379-4d91-8190-a6e1e981e812.gif)

**Comment by JacksonKearl** [comment]
Extensions can contribute to the context menu, see here for more info https://code.visualstudio.com/api/references/contribution-points#contributes.menus
