### ISSUE TITLE
Razor's trace level is currently set to 'Off' still an issue.

### ISSUE THREAD

**Issue by joelrb** [microsoft/vscode#130829]
This issue has been discussed in https://github.com/microsoft/vscode/issues/68739.

It's August, 2021 already and this is still an issue.

--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 10:53:22 PM] Server initialization failed.
  Message: Request Cancelled
  Code: -32800 

Visual Studio Code
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

**Comment by joelrb** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

Yeah, but you have to tell me which extension it is. VS doesn't say anything. Should I turn off all extension?

**Comment by weinand** [comment]
Maybe the "Razor" extension?

**Comment by joelrb** [comment]
> Maybe the "Razor" extension?

I don't have any razor extension installed.

**Comment by joelrb** [comment]
I removed two .Net extensions. Problem solved. I guess I won't use .Net in VS Code lol.

**Comment by weinand** [comment]
Yes, "Razor" might by part of .Net
