### ISSUE TITLE
Right click "find definition and Peek does not work with files in open folder

### ISSUE THREAD

**Issue by i-frost** [Microsoft/vscode#13086]
- VSCode Version: Version 1.5.3
- OS Version: Linux Mint 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. open git repo folder in code, python files
2. right click select "Go to Definition"

Nothing happens, definition file.py is in same folder
Same with "peek definition"
Find all References just displays "loading"

It used to work but I have upgraded code twice since then.

**Comment by Tyriar** [comment]
Please make sure you have the python extension installed, if this still occurs file an issue to https://github.com/DonJayamanne/pythonVSCode

cc @DonJayamanne
