### ISSUE TITLE
Order command palette by usage

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#13080]
- VSCode Version: 1.5

When searching for items in the command palette, it would be nice if it ordered the items by usage amount. So if I use command `az` more than command `aa`, it would be nice if command `az` showed up first when I typed `a` into the search.

**Comment by bpasero** [comment]
@TheColorRed I wonder if that would not be too much magic. An alternative is to always restore the last used command when you search and the last typed command is part of the result set.

**Comment by bpasero** [comment]
@TheColorRed how about just showing the last used commands in MRU order and use that as sorting instead of going by invocation count?

**Comment by TheColorRed** [comment]
@bpasero that sounds like it could be a decent idea, how many commands would it remember and would it remember those last commands upon restart?

**Comment by bpasero** [comment]
@TheColorRed yes it would store the commands globally across any window and between restarts I suppose. The number should be high enough to cover a bit, maybe make it configurable.

**Comment by bpasero** [comment]
There is now a (configurable) number of recently executed commands to the top of the command palette. This can be configured via `"workbench.commandPalette.history"`. Setting it to 0 will disable the history.

![flicker_chrome58](https://user-images.githubusercontent.com/900690/26881324-617b1b8c-4b97-11e7-97f0-bcc80889ff5d.gif)
