### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by qqakashi** [microsoft/vscode#130894]
Issue Type: <b>Bug</b>

Net:: err appears_ INVALID_ ARGUMENT when I update the version
vscode version：1.59.0

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.70GB free)|
|Process Argv|--crash-reporter-id 8cdd384b-43ee-4fbc-b9a4-f92e2310ac8c|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|2.0.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
macos-modern-theme|dav|2.1.9
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.1.0
anes|gam|0.0.2
mayukaithemevsc|Gul|3.0.1
beautify|Hoo|1.5.0
icon-fonts|idl|2.5.2
react-native-snippet|jun|0.5.6
fluent-icons|mig|0.0.12
vscode-language-pack-zh-hans|MS-|1.59.3
csharp|ms-|1.23.14
vscode-react-native|msj|1.6.0
awesome-flutter-snippets|Nas|3.0.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.9.0
synthwave-vscode|Rob|0.1.8
theme-switcher|sav|2.0.2
vscode-field-lights|sve|0.0.11
adb-interface-vscode|vin|0.22.1
propertylist|zho|0.0.2

(44 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether one of your extensions is causing this.

/needsMoreInfo
