### ISSUE TITLE
Web: simple file dialog buttons look odd

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130965]
Running `yarn web` out of sources and opening the file dialog:

![image](https://user-images.githubusercontent.com/900690/129670872-ca0fb916-fc00-4890-8433-537eba24956c.png)

//cc @TylerLeonhardt

**Comment by alexr00** [comment]
@TylerLeonhardt this is also occurring in insiders.

**Comment by alexr00** [comment]
Here's where the simple file dialog calls `createQuickPick`

https://github.com/microsoft/vscode/blob/1bbe9cfd599ccb1bc1fa220ee05201add6d7c9db/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L270-L270

**Comment by TylerLeonhardt** [comment]
probably the removal of display:flex here:
https://github.com/microsoft/vscode/commit/f4f6a69ac19ed88cd27ce623306c2d937bd8c9d3

I'll bring it back for now but I'll need to figure out another change to prevent the prompt from bleeding.
