### ISSUE TITLE
Version 1.59.0 with bug in "internalConsole" in Nodejs.

### ISSUE THREAD

**Issue by SamStalschus** [microsoft/vscode#130924]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10

When updating the vscode to this version, it was identified that launch.json has a problem when I try to use internalConsole. 

Steps to Reproduce:

1. **Use the launch configuration below**:

```json
{
    "version": "0.2.0",
    "configurations": [        
        {
            "type": "node",
            "request": "launch",
            "name": "Lauch Internal Console",
            "program": "${workspaceFolder}\\server.js",
            "console": "internalConsole"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Lauch Integrated Terminal",
            "program": "${workspaceFolder}\\server.js",
            "console": "integratedTerminal"
        }
    ]
}
```

2.**Then select the internalConsole option and run debbuger**:
![image](https://user-images.githubusercontent.com/70023098/129604027-8a4b6c8a-7fa6-4b80-a069-5adc361804f7.png)
The program runs but the debug console does not answer any logs.

3. When using the `"console": "integratedTerminal"` the program responds as expected:
![image](https://user-images.githubusercontent.com/70023098/129604392-0a5b5f04-4c55-4219-ba66-b9244681b91c.png)

**Comment by weinand** [comment]
Please try to add `"outputCapture": "std"` to the launch config.
With this you can configure from where to capture output messages: the default debug API if set to console, or stdout/stderr streams if set to std.

**Comment by SamStalschus** [comment]
> Please try to add `"outputCapture": "std"` to the launch config.
> With this you can configure from where to capture output messages: the default debug API if set to console, or stdout/stderr streams if set to std.

Thank you very much for your help.

I made the change and it's working now ;)
