### ISSUE TITLE
Allow for Function Usage List

### ISSUE THREAD

**Issue by DanielBell-Io** [microsoft/vscode#130908]

**Comment by IllusionMH** [comment]
/needsMoreInfo

Looks like Find All References and maybe Show Call Hierarchy actions that are available for TS/JS (supported out of the box) and other languages where extension provide this functionality.

**Comment by DanielBell-Io** [comment]
@IllusionMH I am using Python 3.8. What extension do I need for this to work?

**Comment by DanielBell-Io** [comment]
> /extPython
> 
> Whatever extension you use foe Python files
> 
> Usually it's https://marketplace.visualstudio.com/items?itemName=ms-python.python
> Also see https://code.visualstudio.com/docs/languages/python for setup info

Top link downloaded the correct extension needed for Finding Usages. Ty
