### ISSUE TITLE
Quick Pick: long words overflow

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#130935]
```js
window.showQuickPick([], {
	title: 'a'.repeat(100),
});
```

<img src="https://user-images.githubusercontent.com/9638156/129623446-fdf0aa5e-69e0-4df6-8265-5c47cfc33030.png" width="500">

InputBox has the same issue

```js
window.showInputBox({
	prompt: 'a'.repeat(100),
	title: 'a'.repeat(100),
})
```

**Comment by TylerLeonhardt** [comment]
Nice find. Thanks!
