### ISSUE TITLE
Explorer: "Remove Folder from Workspace" is a no-op when selected in empty space

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130964]
Steps:
* multi root workspace with 2-3 folders
* right click into empty space below last folder
* select "Remove Folder from Workspace"
* nothing happens

//cc @isidorn

**Comment by isidorn** [comment]
I guess this should remove the last workspace folder.

**Comment by bpasero** [comment]
Not sure, if you invoke this command from F1 list, you get a picker asking which folder to remove. We could do the same here.

**Comment by isidorn** [comment]
Sometimes the empty area takes the last workspace folder as context and sometimes not. So we should be consistent and check what other actions do on the empty area.

Maybe the only exception is actually drag and drop, which on drop on empty area drops to the last workspace folder.

**Comment by byehack** [comment]
![image](https://user-images.githubusercontent.com/26390254/129805676-41b12479-c13c-4029-a6a9-42687c1ad93c.png)

context menu of empty area should be something like this.

**Comment by byehack** [comment]
![image](https://user-images.githubusercontent.com/26390254/129806149-a65d1238-0d13-4161-a341-d50bdbbc7005.png)

and also change this icons when there is no folder selected.
