### ISSUE TITLE
[themes] Dark+ theme can possibly have different colors for properties and variables

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13092]
Reported by @emzero in Microsoft/TypeScript-TmLanguage#282

VS Code
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:50:42.185Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Latest TypeScript and Javascript Grammar 0.0.2

Windows 7 SP1 x64

Is it possible to have different colors for local variables and object properties?

Using the Latest TypeScript and Javascript Grammar it seems that some themes are able to do this but not the default ones. Not sure if it's something related to the themes or to the TmLanguage.

Default Dark+
![image](https://cloud.githubusercontent.com/assets/412489/18977251/fed24e06-868e-11e6-98f9-d45f2de71041.png)

Monokai Dimmed
![image](https://cloud.githubusercontent.com/assets/412489/18977259/1889cf18-868f-11e6-9aba-e00633b2c768.png)

**Comment by leaxoy** [comment]
and methods, and functions too!!!

**Comment by aeschli** [comment]
The current 'philosophy' of the Default Dark+ theme is to only highlight variable declarations, not references.

**Comment by sheetalkamat** [comment]
@aeschli Do you think the variable declarations be scoped differently than the references? Also what about function/method declarations and references. Having looked at few javascript grammars, none scope these differently.

**Comment by emzero** [comment]
@aeschli Ok, but in the screenshot I posted there is a variable `person` that's not being properly colored as it's the same color as its properties.

**Comment by aeschli** [comment]
@sheetalkamat It would be great if we could add an additional scope to it so we can differentiate between declarations and references.

**Comment by aeschli** [comment]
We currently only have a singe color for variables. The colors originally come from the default VS themes.

**Comment by aeschli** [comment]
We have no plans to add this. Custom themes can add such coloring or users can add it in the settings:
```json
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "meta.object-literal.key",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
```
