### ISSUE TITLE
Running extensions editor: Indicate that an extension is running in the web worker extension host

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#130905]
I was migrating an extension to a web extension and was running it on the desktop with the a launch config to run the extension as a web extension (see the [web extension guide](https://github.com/microsoft/vscode-internalbacklog/wiki/Web-Extension-Author-Guide#create-a-web-extension))

When opening the Running extensions editor I would have expected to see some indication in the editor that the extension is running in the web worker extension host, but the extension showed up as the other extensions. There should be an indication in which extension host this extension is running.

![image](https://user-images.githubusercontent.com/172399/129569217-7c82083b-0f6d-4cce-8d97-27c25d693cf2.png)

**Comment by alexdima** [comment]
This is what will be rendered: 

![image](https://user-images.githubusercontent.com/5047891/129699748-a69fe9b4-5a50-474f-a53d-ebe27eefbbe0.png)

**Comment by bpasero** [comment]
Not sure about the icon. //cc @misolori

**Comment by misolori** [comment]
A globe might be better suited:

<img width="149" alt="CleanShot 2021-08-30 at 10 45 37@2x" src="https://user-images.githubusercontent.com/35271042/131381969-de2c201a-004a-4618-9810-195971428f7f.png">
