### ISSUE TITLE
the built-in terminal of the sign hangs for 1 second

### ISSUE THREAD

**Issue by Bobrovskih** [microsoft/vscode#130986]
Issue Type: <b>Performance Issue</b>

when using the vs code terminal
there are suspensions of the period for 1 second
especially noticeable if you type text there, for example, when using git from the console

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.6.0

**Comment by meganrogge** [comment]
you are on an extremely old version of vscode. can you update it and let us know if you still see the issue?

another thing to try: - set `terminal.integrated.localEchoLatencyThreshold` to -1
