### ISSUE TITLE
Diff editor does not ask to save when closing

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#13095]
- VSCode Version: Code - Insiders 1.6.0-insider (c96822698cdbd47b8245fb5f9f45a0168bc9da33, 2016-09-30T17:37:14.267Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: `chrmarti.regex-0.0.6`, `DavidAnson.vscode-markdownlint-0.5.0`, `dbaeumer.vscode-eslint-1.0.6`, `eg2.tslint-0.5.39`, `ms-vscode.csharp-1.4.1`, `msjsdiag.debugger-for-chrome-0.5.2`, `seanmcbreen.Spell-0.8.6`

Smoke-testing

Steps to Reproduce:

1. Open diff editor from Git viewlet
2. Make change in current version
3. Close editor -> no dialog asking for saving which is inconsistent with the regular editor

Open Editors shows no editor, but 1 UNSAVED. Closing the window / opening another folder correctly asks for saving the file.

**Comment by bpasero** [comment]
@chrmarti great catch, I pushed a fix. Can you please verify? the motivation for the change was to allow to close a dirty diff editor if the file is opened anywhere else. Only the last editor containing the resource (either diff editor or normal editor) should prompt the user for saving.

**Comment by chrmarti** [comment]
@bpasero The regular editor always asks, even if there is still a diff editor with the same file open. That doesn't match your description of what should happen. The original bug is fixed though. (Tested when running from source, will verify when we have a new build.)

**Comment by chrmarti** [comment]
Verified in todays insiders with the above mentioned caveat.

**Comment by bpasero** [comment]
@chrmarti yes you are right and I think that is ok because it may confuse users that they can close a normal dirty editor when only a diff editor is open to the side.
