### ISSUE TITLE
"Error: Unable to resolve non-existing file" on JSDoc file link

### ISSUE THREAD

**Issue by ScribbleNerd** [microsoft/vscode#130968]
Issue Type: <b>Bug</b>

When trying to create a link to a relative file using JSDoc and markdown like this:
```js
/** [link](./file.js) */
const test = 'test'
```
you can try to click on the link, and it'll produce the following error:
```md
# Unable to open 'file.js"'
Unable to read file '\file.js" (Error: Unable to resolve non-existing file '\file.js')
```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.04GB free)|
|Process Argv|--crash-reporter-id b49bd496-32d9-4a43-8329-536816f85c17|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vdf|GEE|0.0.7
beautify|Hoo|1.5.0
discord-vscode|icr|5.7.0
sftp|lix|1.12.9
languague-renpy|Luq|1.1.0
csharp|ms-|1.23.14
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
remote-wsl|ms-|0.58.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
typescript-initializer|Scr|0.0.2
sass-indented|syl|1.8.17
vscode-icons|vsc|11.6.0
vscode-nginx|wil|0.7.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723cf:30351748

```

</details>

**Comment by AiverReaver** [comment]
can I work on this issue?

**Comment by ScribbleNerd** [comment]
any updates on this?
