### ISSUE TITLE
Window freezes on debug breakpoint

### ISSUE THREAD

**Issue by mschief148** [microsoft/vscode#130961]
Issue Type: <b>Bug</b>

I have an angular project and each time I set a breakpoint and then launch Chrome for debugging the VsCode window freezes when the breakpoint is reached, I have to minimize the window and then reopening the window again for the window to work. I tried in two different angular project, both of them with the same result

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.10GB free)|
|Process Argv|--crash-reporter-id 8b37705f-d11f-45ad-ae52-63506143eed8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|12.2.0
browse-lite|ant|0.2.13
vscode-mysql-client2|cwe|4.1.0
angular-schematics|cyr|4.13.0
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-eslint|dba|2.1.23
parameter-hints|Dom|0.2.7
githistory|don|0.6.18
gitlens|eam|11.6.0
vscode-great-icons|emm|2.1.79
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
activitusbar|Gru|0.0.46
html-tag-wrapper|hwe|0.2.3
error-gutters|Igo|1.0.1
mysql-syntax|jak|1.3.1
Angular2|joh|12.0.0
fluent-icons|mig|0.0.12
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.6.0
angular2-inline|nat|0.0.17
angular-component-extractor|PKi|0.1.0
material-icon-theme|PKi|4.9.0
material-product-icons|PKi|1.1.1
subtle-brackets|raf|3.0.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
terminalis|Spe|0.4.0
addDocComments|ste|0.0.8
open-in-browser|tec|2.0.0
errorlens|use|3.4.0
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.10.1
better-align|wwm|1.1.6
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136

```

</details>

**Comment by connor4312** [comment]
Could you take a performance profile using the instructions here so we can see what's causing the freeze? Thanks! https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by mschief148** [comment]
I couldn't do the performance profile because now it says unable to attach to browser. I also uninstalled vscode yesterday and then installed again to test one last time the debugger but after shutting down my laptop I came with this error

![image](https://user-images.githubusercontent.com/28127669/129766399-78eeffe1-eee9-4641-bc90-76a035769b89.png)

**Comment by mschief148** [comment]
Here you go
[vscode-debugadapter-2b055f92.json.gz](https://github.com/microsoft/vscode/files/7001743/vscode-debugadapter-2b055f92.json.gz)

**Comment by mschief148** [comment]
Now it let's me run the debugger and this is the performance profile you asked 
[CPU-20210818T002006.zip](https://github.com/microsoft/vscode/files/7004696/CPU-20210818T002006.zip)

**Comment by connor4312** [comment]
@mschief148 please run the [steps linked](https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process) on VS Code itself, not your app.

**Comment by mschief148** [comment]
My bad sorry. Here it is
[CPU-20210818T111620.zip](https://github.com/microsoft/vscode/files/7008652/CPU-20210818T111620.zip)

**Comment by connor4312** [comment]
Ok, thanks! The profile is pretty sparse, but I think I've seen this sometimes hitting BPs in the VS Code repo too. @deepak1556 is there any Electron-level profile information we can take to see if something's happening there?

**Comment by deepak1556** [comment]
This seems to be a side effect of the occlusion tracker, duplicate of https://github.com/microsoft/vscode/issues/123257. Can you try launching the app with `--disable-features=CalculateNativeWinOcclusion` and see if the issue happens.

Also what does your setup look like (ex:) are you running in a multi-monitor configuration, can you provide a screen recording showing the issue repro steps. Thanks!

**Comment by MihaPro-CarX** [comment]
The same bug is reproduced in my debugging session.
I am working in Unity and using two monitors, a C # project.

When a breakpoint is triggered in the tray, the VSCode window lights up, but when the window is activated with a mouse click, it freezes visually, although it reacts to hotkeys and it is possible to edit the code without visual displaying the changes. To restore the VSCode display, you have to minimize and maximize the window.

I tried the latest Insiders version so far c0891333. The bug in it is still reproduced.

But if run VSCode with the parameter: `--disable-features = CalculateNativeWinOcclusion` then the problem goes away. The VSCode window fires at the breakpoint correctly.

**Comment by connor4312** [comment]
I can confirm as well. I hit this very reliably when debugging from OSS, and that flag fixes it. I'll reopen the mentioned issue and close this as a duplicate.
