### ISSUE TITLE
Emoji keyboard opens in the wrong place

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13093]
Ctrl+cmd+space to open this on OSX. Sometimes it's on the wrong monitor, sometimes it's fairly close like in the gif. Everywhere else in the system, it opens pointing at the cursor or focused input box, so I'm guessing it's something we actually have control over somehow. If the cursor is in a basic input box like the find widget, marketplace search box, etc, then it shows up in the right place.

![sep-30-2016 11-10-27](https://cloud.githubusercontent.com/assets/323878/19001958/a2c6f254-86fe-11e6-91cc-9be958f40b94.gif)

**Comment by alexandrudima** [comment]
It shows at the top of the editor, where we keep the textarea

**Comment by Tyriar** [comment]
@alexandrudima do you move the text area under the cursor when doing an IME composition? I was expecting an emoji IME to act the same as a language IME.

**Comment by roblourens** [comment]
In the gif that appears to be the case but I see it in different places depending on where the cursor is.

**Comment by alexandrudima** [comment]
I move the textarea to the cursor location when I get a `compositionstart` event. Chromium/Electron doesn't give a `compositionstart` event when popping up the emoji picker

**Comment by mushanshitiancai** [comment]
I meet similar problem with Chinese IME.

![image](https://cloud.githubusercontent.com/assets/4251771/20826174/090e443c-b8a4-11e6-8282-2cdacb5f27bf.png)

**Comment by cesarvarela** [comment]
![image](https://cloud.githubusercontent.com/assets/1172479/21298218/75726732-c56c-11e6-95d3-fea69cfa165c.png)

Not just chinese

**Comment by alexandrudima** [comment]
After ad023e4 and 689a607 (done for #356) here is the status:

@mushanshitiancai Chinese IME is tracked in #356 . The first time, the suggestions pop up at the correct location. On a second usage, the suggestions pop up at the top left window position. This appears now to be an upstream bug which I've filed against Electron.

@cesarvarela This now works correctly:
![accents-good-popup](https://cloud.githubusercontent.com/assets/5047891/25738975/1907fa04-3180-11e7-8445-69f13dbe8be4.gif)

**Comment by alexandrudima** [comment]
After my latest change, the emoji picker shows "really close" to the primary cursor. I can only guess that the emoji picker is positioned in a way that does not account for the `overflow: hidden` of the textarea and tries really hard (but fails) to position itself next to the native cursor inside the textarea:

![emoji-picker](https://cloud.githubusercontent.com/assets/5047891/25739666/248d0628-3183-11e7-82f6-b0072ec2d138.gif)

**Comment by roblourens** [comment]
What I see now is that it's always right on the cursor but maybe a little too close for comfort. Huge improvement though! Opening a new issue.
