### ISSUE TITLE
CLI on Mac doesn't seem to work

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#130925]
Ref https://github.com/microsoft/vscode/issues/102975

1. Run `code-insiders dirname` where `dirname` is the name of a directory.
2. 🐛 Insiders may or may not open `dirname`.
3. In a separate terminal, run `code-insiders dirname2` where `dirname2` is the name of another directory.
4. 🐛 Insiders doesn't open that directory.

Replacing the commands with calls to `open` doesn't work.

**Comment by deepak1556** [comment]
Unable to repro with latest insiders.

[Screen Recording.zip](https://github.com/microsoft/vscode/files/6994611/Screen.Recording.2021-08-16.at.11.36.02.AM.zip)

**Comment by rzhao271** [comment]
The issue above in my case seems to be caused by having `VSCODE_DEV=1` in the env. I'll check the options parameter again and see if I can make it so that during the open command, `VSCODE_DEV` gets reset. That would help me test using the open command by running the following on the command-line: `VSCODE_DEV=1 vscode/.build/electron/Code\ -\ OSS.app/Contents/MacOS/Electron vscode/out/cli.js repo-name`

**Comment by deepak1556** [comment]
How are you running the open command ? Is it via the cli wrapper, if not can you provide the full command used.

**Comment by rzhao271** [comment]
`vscode/out/cli.js` is the cli wrapper, and that calls the `spawn` function to run the `open` command. The `open` command has the `--env` arg so I can try using that. `spawn` also has an `options` param, though I left it blank for now.

**Comment by deepak1556** [comment]
Yes you need to pass the environment set via the spawn options into the open command for things to work correctly https://github.com/microsoft/vscode/blob/9921c378a0006f14b0386ae2e531058c9363ef72/src/vs/code/node/cli.ts#L313-L316
