### ISSUE TITLE
Debug step out continues

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#13096]
- VSCode Version: Code - Insiders 1.6.0-insider (c96822698cdbd47b8245fb5f9f45a0168bc9da33, 2016-09-30T17:37:14.267Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: `dbaeumer.vscode-eslint-1.0.7`, `eg2.tslint-0.5.39`, `ms-vscode.csharp-1.4.1`, `msjsdiag.debugger-for-chrome-0.5.2`

Steps to Reproduce:
1. In smoke-test hit breakpoint in index.js:7
2. Step in to render()
3. Step out
4. Observe execution continuous instead of stepping out

**Comment by chrmarti** [comment]
I keep running into this during the Smoke-Test. Should we add a note to it?

**Comment by weinand** [comment]
@chrmarti do you see the same behaviour with `"type": "node2"`?

**Comment by chrmarti** [comment]
Yes, same with node2 using node 7.0.0. Previously with the old protocol and node 6.3.0.

**Comment by weinand** [comment]
@chrmarti OK, then this looks like a node bug.

/cc @roblourens

**Comment by chrmarti** [comment]
Also: It seems to be related to the calling function not having any further lines of actual code after the one I stepped into. We found that stepping over at the end of the stepped into function then correctly stops on the closing } of the calling function.

**Comment by weinand** [comment]
I'm seeing the same behaviour with node-inspector.
So this is not a VS Code issue but a node bug.
