### ISSUE TITLE
Some file operation strings not localized

### ISSUE THREAD

**Issue by wangweixuan** [microsoft/vscode#130909]
`files` and `folders` not localized. They appear in undo labels and progress labels.

https://github.com/microsoft/vscode/blob/4168941deec97e4416493daf844e516740c716b3/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1202-L1215

**Comment by TylerLeonhardt** [comment]
Assigned the folks based on the blame.

@isidorn added it,
@joaomoreno modified stuff closest to it,
@bpasero was also seen quite a bit in that file
https://github.com/microsoft/vscode/blame/4168941deec97e4416493daf844e516740c716b3/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1202-L1215

**Comment by isidorn** [comment]
It is localized, just check how that method is being used. It is always under a localized call.
Thus closing

**Comment by isidorn** [comment]
My mistake, after discussing with @bpasero this is a valid issue. We need to call localize on each substring, because the transaltors can localize `Foo {0}` but not the thing in `0`.

**Comment by rzhao271** [comment]
@isidorn I'm wondering what are some repro steps for this issue? I'm not sure where to find the strings.

**Comment by isidorn** [comment]
@rzhao271 I guess code review is good enough for this one.
I believe these labels are not seen anywhere: they are undo labels which we might surface in the future if we introduce a richer Undo UI.
