### ISSUE TITLE
Pressing CMD-S in VS Code often results in Electron save dialog showing up instead of simply saving the current file

### ISSUE THREAD

**Issue by franktopel** [microsoft/vscode#130913]
Issue Type: <b>Bug</b>

I haven't yet found a reliable way to reproduce this, yet it happens like 10-25 times per day. I have the impression the issue is related to editing and then saving too quickly in succession, but cannot tell for sure.

<img width="3120" alt="image" src="https://user-images.githubusercontent.com/10668603/129585600-72a6cfce-233b-4875-b74f-3b60fccf5e4d.png">

I was able to create this reproduction for the screenshot quickly undoing recent edits using CMD-Z very quickly followed by CMD-S.

I was also able to provoke this behaviour with all extensions disabled.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:11:51.081Z)
OS version: Darwin arm64 21.0.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|webcomponents.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
preview-pdf|ana|1.0.0
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-colorize|kam|0.11.1
change-string-case|max|1.1.2
vscode-language-pack-de|MS-|1.59.3
vscode-typescript-next|ms-|4.5.20210815
docthis|oou|0.8.2
material-icon-theme|PKi|4.9.0
LiveServer|rit|5.6.1
vscode-css-variables|vun|1.4.3
CSS-sorter|zas|0.2.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by franktopel** [comment]
I can reproduce the same faulty behaviour in VS Code Insiders as well.

To reproduce it, what works for me is:

1. Open any code file
2. Make 2 changes
3. In very quick succession press CMD-Z twice, immediately followed by CMD-S.
4. If it doesn't "work" immediately, try reversing your changes using SHIFT-CMD-Z followed by CMD-S.
5. Repeat 3 / 4 until the save dialog occurs.

**Comment by bpasero** [comment]
The issue is that "Save As.." is being hit because you end up pressing `Cmd+Shift+S` due to the `Shift` key being pressed when you undo. I suggest you remove the keybinding for "Save As..." to fix this.

**Comment by franktopel** [comment]
I did, thanks for taking the time to investigate!
