### ISSUE TITLE
dataframe output font size too big after update

### ISSUE THREAD

**Issue by kangseung** [microsoft/vscode#130943]
dataframe output font size too big after update

I can reset font size by code

```
heading_properties = [('font-size', '6px')]

cell_properties = [('font-size', '6px')]

dfstyle = [dict(selector="th", props=heading_properties),
           dict(selector="td", props=cell_properties)]

df.style.set_table_styles(dfstyle)
```

can I set default jupyter output font size ?

**Comment by greazer** [comment]
The output size is the wrong size for this user. They're adding the code above to work around it.

**Comment by rebornix** [comment]
The font size of outputs now aligned with input and we didn't have a setting to allow customzie ityet.
