### ISSUE TITLE
Source control changes not updated when VSC is not in focus

### ISSUE THREAD

**Issue by MmAtBosch** [microsoft/vscode#130906]
I would like to have VSC source control gets updated even when VSC is not in focus.

I have two displays, one with VSC open and one with my browser controlling my CI pipeline.

My normal process is to commit and push my code changes via a shortcut and instantly switching to my browser to rerun my pipeline.
In this time git commits and pushes my changes but this is not reflected in the source control tab of vsc, which is still  showing the number of changes or clock icon which indicates that the change is pending.
![GithubPrimarySystemDesiredStateJobs yml — workspace (Workspace) 2021-08-16 15-24-35](https://user-images.githubusercontent.com/48314408/129571130-14d1745b-0cbd-44f7-9c76-54c573a8cc57.png)

I have to focus my vsc to get this icon updated and to know if my change we pushed successfully.

Maybe related to:
https://github.com/microsoft/vscode/issues/121463

**Comment by eamodio** [comment]
While this is by-design, I'll mark this as a feature request.
