### ISSUE TITLE
Let notebooks renderers check workspace trust status

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#130951]
Some notebook renders may want to limit their behavior if they are used in an untrusted notebook. This is currently not possible unless the renderer can talk to a kernel that can share the workspace trust status with them. We should provide an easier way to accomplish this

**Comment by mjbvz** [comment]
Proposal:

```ts
// Passed to `activate` function of the renderer
export interface RendererContext {
    ...  // existing props


    const isTrusted: boolean;
}
```

Alternatively, if we want to align this more with `vscode.d.ts` and think we may other properties from `workspace`:

```ts
export interface RendererContext {
    const workspace: { isTrusted: boolean; }
}
```

**Comment by mjbvz** [comment]
Ended up going with `workspace.isTrusted` for extensibility

**Comment by mjbvz** [comment]
To verify: 

1. Using a notebook renderer (such as https://github.com/microsoft/vscode-extension-samples/tree/main/notebook-renderer-sample)
2. Check the `ctx` passed to `activate` to confirm `ctx.workbench.isTrusted` is correct
3. Now starting with an untrusted workspace, confirm that trusting the workspace re-renders the output and that `ctx.workbench.isTrusted` becomes true

**Comment by IanMatthewHuff** [comment]
In a trusted workspace, ctx.workspace.isTrusted is correctly true:
![image](https://user-images.githubusercontent.com/812783/130693029-73cb288a-bd54-419d-a1bb-af22cffdda1a.png)

In an untrusted workspace, ctx.workspace.isTrusted is correctly false:
![image](https://user-images.githubusercontent.com/812783/130694466-a1ff06b5-e1e6-42c3-9cb7-2306e6ea1cc3.png)

Trusting the workspace change it correctly to true.
