### ISSUE TITLE
git nott showing

### ISSUE THREAD

**Issue by 09Raghu09** [microsoft/vscode#130914]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:41:20.664Z)
- OS Version: Linux x64 5.10.47.mx64.390
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.2|

---

Steps to Reproduce:

1.
2.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible in latest stable build which is 1.59? https://code.visualstudio.com/Download

> VSCode Version: Code 1.8.1 (ee428b0, 2016-12-19T14:41:20.664Z)

is ~4.5 years old
