### ISSUE TITLE
Remote debugger won't detach when running uvicorn app with --reload

### ISSUE THREAD

**Issue by gionapaolini** [microsoft/vscode#130941]
## Environment data

- debugpy version: 1.4.1 
- OS and version: Windows 10
- Python version: python:3.9.6-alpine3.13 (in docker)
- Using VS Code or Visual Studio: VS Code

## Actual behavior
Debugging works fine, but when I'm finished and I click on the detach button the remote debugger won't detach.

## Expected  behavior

Remote debugger should stop and close

## Steps to reproduce:
1. Create a very simple fastapi app called app.py
```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}
```
2. Run it with debugpy and with uvicorn and --reload option (I run it in a docker container it so that I can then attach remotely, and make sure to expore ports 5678 and 80)
```
python -u -m debugpy --listen 0.0.0.0:5678 -m uvicorn --reload --host 0.0.0.0 --port 80 app:app
```
3. Attach to it with the following launch.json config:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote debugging",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "...",              -> make sure to map source files correctly
                    "remoteRoot": "..." 
                }
            ]
        }
    ]
}
```
Importing debugpy inside the app itself works, but I was wondering if I can make it work without this workaround.

**Comment by zdytch** [comment]
> This one would be a minor issue by itself - you'd only need to click Disconnect once more to disconnect from the child process, as well

@int19h Clicking once more and more and more doesn't work for me. The debugger remains attached

**Comment by DavidS-cloud** [comment]
Can confirm that behaviour with `werkzeug`, a different spawn-and-reload python/django host:

After attaching to localhost:3000:

![2022-06-07_14MS+0100_625x364](https://user-images.githubusercontent.com/88319323/172387790-488b085f-e0a9-4704-93c7-8b3f902c88e4.png)

After Detaching:

![2022-06-07_14MS+0100_643x385](https://user-images.githubusercontent.com/88319323/172387820-c3d9bb91-1c18-4084-8702-20858321dd09.png)

PID 53 is the spawned process:

```
app@dschmitt:/opt/app/app$ ps auxwfwwww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
[...]
app           19  0.5  1.8 1256992 300948 ?      Sl   11:35   0:29 python -m debugpy --listen 0.0.0.0:3000 -m app runserver_plus --threaded 0.0.0.0:8000
app           53  6.8  2.5 3180892 408876 ?      Sl   11:36   6:19  \_ /opt/app/deps/venv/bin/python /opt/app/deps/venv/lib/python3.7/site-packages/debugpy/_vendored/pydevd/pydevd.py --module --port 41871 --ppid 19 --client 127.0.0.1 --access-token token --multiprocess --skip-notify-stdin --json-dap-http --file app runserver_plus --threaded 0.0.0.0:8000
app           26  0.0  0.1 1514160 20328 ?       Sl   11:35   0:01 /opt/app/deps/venv/bin/python /opt/app/deps/venv/lib/python3.7/site-packages/debugpy/adapter --for-server 42925 --host 0.0.0.0 --port 3000 --server-access-token token
```

**Comment by roblourens** [comment]
Possibly same as what's going on in https://github.com/microsoft/vscode/issues/164553

**Comment by sbatten** [comment]
@connor4312 this seemed to work-ish. It reliably took 3 clicks to detach.

**Comment by connor4312** [comment]
Yea, that's intentional. Detaching detaches from the specific session, as Python does not use `lifecycleManagedByParent` (https://github.com/microsoft/vscode-python/issues/20376). But you can do this instead of having the UI break 🙂
