### ISSUE TITLE
Native title bar on GNOME (Linux) does not adapt to light/dark theme switches

### ISSUE THREAD

**Issue by cbrnr** [microsoft/vscode#130974]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Linux (GNOME 40.3 X11)

Steps to Reproduce:

1. Open VS Code
2. Switch GNOME theme from light to dark (or vice versa)
3. VS Code adapts to the new theme, but the title bar stays how it initially was. Sometimes, it changes to dark on the first light->dark switch, but then it never switches back to light (logging out of the session solves this).
![Peek 2021-08-17 10-16](https://user-images.githubusercontent.com/4377312/129691097-2a3af92a-c4db-4e7d-8a07-56f24f4a125d.gif)

**Comment by reuseman** [comment]
It's still happening the same thing. By setting "window.titleBarStyle": "custom" it shows the Windows UI

**Comment by deepak1556** [comment]
This is an issue with the native titlebar which is rendered by the runtime and not VSCode, please check if the issue persists with latest stable `1.73`.

**Comment by cbrnr** [comment]
Yes, the issue still persists with 1.73.1.

**Comment by jnns** [comment]
The Open-File / Save-File-As dialogs don't adapt to the current colorscheme either. Not sure if this is related or breaking the scope of this ticket.

**Comment by deepak1556** [comment]
Upstream PR https://github.com/electron/electron/pull/38977

**Comment by slagiewka** [comment]
> Upstream PR [electron/electron#38977](https://github.com/electron/electron/pull/38977)

The aforementioned PR has been merged and released as [v25.8.4](https://github.com/electron/electron/releases/tag/v25.8.4).

**Comment by slagiewka** [comment]
Electron bumped by  #194487 and #194488.

I've installed Code Insiders 1.83 and toggling dark and light themes in KDE works. Tested with native and custom title bar. Tested with "Auto Detect Color Scheme" ON.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/318f421af3746f02d63db566d35069c58d7f4c4a
