### ISSUE TITLE
VSCode crashing when sshfs mounted drive is removed

### ISSUE THREAD

**Issue by tcpekin** [microsoft/vscode#130978]
Issue Type: <b>Bug</b>

I often use SSHFS to mount remote drives and then use VSCode to edit files on those drives. When I have a file on a remotely mounted drive open in VSCode and I have to unmount the drive (either problem with sshfs, or just no longer on the required VPN), VSCode crashes. During the crash it asks if I would like to relaunch, and I click yes. A screenshot of the message is below. The button does not relaunch VSCode, so I have to manually open the application again. Once I do so (usually after unmounting `sudo diskutil umount force ~/mnt` and remounting the remote drive), everything returns to it's previous state. This behavior is 100% reproducible on my computer. Additionally, I have check with all extensions disabled and the same thing occurs.

![image](https://user-images.githubusercontent.com/9438848/129698965-9e690f38-d309-41f1-ad9b-20c6b2bc889c.png)

I would expect that unmounting a drive via sshfs while having a file from that drive open in VSCode would not cause VSCode to crash, but rather just complain that file cannot be saved/found/etc. VSCode already gives this warning when I am not on the correct VPN or sshfs is not working correctly, but then as soon as I force the unmount so that I can remount the drive, it crashes in the background. 

Thanks for the help, and if there is anything else I can do to help with this please let me know. 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|82, 21, 9|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 6181084c-00e1-40ef-aeda-66f2d6f78f3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|2.0.1
vscode-cudacpp|kri|0.1.1
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
latex-support|tor|3.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30353136

```

</details>

**Comment by IllusionMH** [comment]
Looks like duplicate of #114283 which was in turn marked as duplicate of #106879

You should provide your use case there if it wasn't handled by latest workaround.

**Comment by tcpekin** [comment]
It does seem to be the same general issue as both of those that you mention, but I don't think any real workaround is provided. This comment [here](https://github.com/microsoft/vscode/issues/106879#issuecomment-892477867) seems to imply that a change was pushed to VSCode, but as the comment suggests, it is only a bandaid as it does not work for drives not mounted in `/Volumes/`. I do not mount my drive to `/Volumes/`, but rather a different path, so the workaround should not work. 

Should I close this issue and post this comment also on issue #106879?

**Comment by IllusionMH** [comment]
My assumption is yes, as that issue acknowledges that it's still a problem for other paths. Maybe propose other common paths in that issue if you are using standard or common/popular path for network mounts.

However I'm not a VS Code dev so feel free to wait for reaction/comment from devs.

**Comment by tcpekin** [comment]
Thank you very much for the help!
