### ISSUE TITLE
Allow smooth scrolling with arrow keys in notebooks

### ISSUE THREAD

**Issue by H-Sorkatti** [microsoft/vscode#130942]
Please add an option to allow smooth scrolling in notebooks using the arrow keys. As in make the arrow keys scroll up and down the page and not just shift focus between cells. 
In Jupyter notebooks (Webserver) one can enable smooth scrolling by executing the following code in the first cell:
```
%%javascript

Jupyter.keyboard_manager.command_shortcuts.remove_shortcut('up');
Jupyter.keyboard_manager.command_shortcuts.remove_shortcut('down');
```
But of course, it doesn't work in vscode.
I find the current scrolling experience very clunky, especially with large cells. An option to disable it would be much appreciated.

**Comment by greazer** [comment]
Thanks for the feedback @H-Sorkatti! We'll consider this in a future version.

**Comment by tanhakabir** [comment]
Hey @H-Sorkatti! We're busy going through and cleaning up issues in our repos this month. Currently there's an On Deck milestone on your issue so it seems like we're working on it, we're just a little bit slower on issues this month since we're busy cleaning up so many issues.
