### ISSUE TITLE
High CPU consumption after update to v1.59

### ISSUE THREAD

**Issue by ubalklen** [microsoft/vscode#130919]
I've noticed as soon as you activate the Jupyter extension, CPU consumption stays high even if the notebook is not running anything. It didn't happen before the update.

[CPU profile](https://github.com/microsoft/vscode-jupyter/files/6987300/CPU-20210814T233614.851Z.cpuprofile.txt)

**Comment by rchiodo** [comment]
The only real CPU spikes in that profile look like this:

![image](https://user-images.githubusercontent.com/19672699/129593165-72ebc111-25f1-4870-8431-69159b00fa34.png)

Not sure what's causing the requests though. @rebornix are these in response to actions by the jupyter extension?
