### ISSUE TITLE
file name saved under .c but changes to .c++ automatically

### ISSUE THREAD

**Issue by RJ1911** [microsoft/vscode#130903]
Issue Type: <b>Bug</b>

when i try to add a new file named 03_03.c it changes to c++ file type .....instead of c type.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.77GB (0.88GB free)|
|Process Argv|--crash-reporter-id 614bf1ab-e90b-41d5-a208-84c24c200bde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.3.2
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.29.2
better-cpp-syntax|jef|1.15.6
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.5.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30351747

```

</details>

**Comment by rzhao271** [comment]
\gifPlease

**Comment by RJ1911** [comment]
> \gifPlease

![ezgif-3-abacac1a682d](https://user-images.githubusercontent.com/80115748/129950804-2d95919f-40d6-4bc5-97ed-276d913cb48c.gif)

**Comment by TylerLeonhardt** [comment]
I can't repro this... I have a suspicion that it is caused by an extension.
![image](https://user-images.githubusercontent.com/2644648/129982876-bec7c1fa-6c08-40f4-8563-cc663767c180.png)

Can you try extension bisect and see if there's a particular extension that's causing this?
![image](https://user-images.githubusercontent.com/2644648/129982979-835b899d-1ea5-410f-92f1-11fc577b3b2b.png)

**Comment by RJ1911** [comment]
> I can't repro this... I have a suspicion that it is caused by an extension.
> ![image](https://user-images.githubusercontent.com/2644648/129982876-bec7c1fa-6c08-40f4-8563-cc663767c180.png)
> 
> Can you try extension bisect and see if there's a particular extension that's causing this?
> ![image](https://user-images.githubusercontent.com/2644648/129982979-835b899d-1ea5-410f-92f1-11fc577b3b2b.png)
> 
> also share whats in your settings.

Its fixed now . Thanks for your time .
