### ISSUE TITLE
Language Server Completion Trigger Kind returned as Invoked with latest vs code

### ISSUE THREAD

**Issue by kalsky** [microsoft/vscode#130953]
Issue Type: <b>Bug</b>

We're working on an extension that is using LSP (if that matters).
The completion feature used to work fine in 1.58.2 but stopped working well in 1.59 (also not working on 1.60 insiders).

What we see is that the that the client side is sending a request to the server side about a completion request, but the kind is most of the times "Invoked", instead of "Trigger Character" when we do use the trigger character/s.

The data being sent from the client looks like this:
{"jsonrpc":"2.0","id":5,"method":"textDocument/completion","params":{"textDocument":{"uri":"file:///some-path/filename.yaml"},"position":{"line":12,"character":48},"context":{"triggerKind":1}}}

In some cases it does send it correctly, but i couldn't pin point on when this happens.

Anything else to provide?

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (8.81GB free)|
|Process Argv|--crash-reporter-id c56c1600-a807-43a2-8501-5d38bed1e331|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.29.2
terraform|has|2.14.0
vsc-python-indent|Kev|1.14.2
vscode-codemetrics|kis|1.24.0
saltstack|kor|0.0.8
tf-snippets|log|0.5.0
MagicPython|mag|1.1.0
azure-pipelines|ms-|1.191.0
mssql|ms-|1.10.1
vscode-postgresql|ms-|0.3.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
azure-account|ms-|0.9.8
vscode-manifest-yaml|Piv|1.27.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
terraform-doc-snippets|run|0.6.0
vscodeintellicode|Vis|1.2.14
bracket-lens|wra|1.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793

```

</details>

**Comment by jrieken** [comment]
What trigger characters do you use?

**Comment by kalsky** [comment]
I use either '.' or '$', both have the same result

**Comment by jrieken** [comment]
In your languague are those word characters?

**Comment by kalsky** [comment]
Not sure about the word characters, where is that defined?

I did try to play with these settings, 
"[yaml]": {
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }        
},

If my yaml has:
somenode: 1
and I add a '.' after the 1, I'll get a correct event.

If I have:
somenode: abcd
and I add a '.' after the abcd, I'll get a wrong event.

**Comment by jrieken** [comment]
> Not sure about the word characters, where is that defined?

The language defines that. An easy test is to call [getWordRangeAtPosition](https://github.com/microsoft/vscode/blob/b3a86e6feea1759a9ddb75e957da6907e3ef4e81/src/vs/vscode.d.ts#L225-L225) (inside the provideCompletion-function) and see if the range includes `.` and `$`. 

When a trigger is also word character we trigger "normal" (as you type) completions and not trigger-character completions. Which is also is comparable to users disabling trigger characters and manually invoking completions after such a character

**Comment by kalsky** [comment]
And was there any behavior change in 1.59 around how it is triggered?
I tried using a comma as a trigger character and it works in 1.59, so I guess there is something special with `.` and `$`.
But trying to understand how it worked before and stopped now, and whether there is some configuration to change this.

**Comment by jrieken** [comment]
Likely two month ago via this commit: https://github.com/microsoft/vscode/commit/0984071fe0d8a3c157a1ba810c244752d69e5689

**Comment by jrieken** [comment]
Going to close this as-designed

**Comment by kalsky** [comment]
Ok, so your suggestion is not to rely on the trigger character in such cases, and just check if the word ends with that character?

**Comment by jrieken** [comment]
Unsure about your use-case but, yeah it might be advised to check the last character of the word that you are completing
