### ISSUE TITLE
Need to save twice for json, js and css files to save changes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#13094]
- VSCode Version: 1.6 insiders (c96822698cdbd47b8245fb5f9f45a0168bc9da33)
- OS Version: OS X El Capitan (10.11.6)

Steps to Reproduce:

1. Open any json/js/css file, make changes, attempt to save either via Cmd+S, or File -> Save, or Save All from the Opened Editors section in the explorer
2. The dirty/unsaved indicator on the tab flickers to saved state and then back to unsaved state.
3. Save again and the file is saved

Doesn't happen in Windows

**Comment by chrmarti** [comment]
@ramya-rao-a What extensions do you have installed? Does it work when disabling extension? Related: #12755

**Comment by ramya-rao-a** [comment]
Narrowed it down to `JS-CSS-HTML Formatter` extension.
The issue doesn't exist in 1.5.3
Looks like some change we did in VS Code is making the extension behave this way

**Comment by ramya-rao-a** [comment]
This issue was moved to Lonefy/vscode-JS-CSS-HTML-formatter#28
