### ISSUE TITLE
didCloseTextDocument not called in extension tests

### ISSUE THREAD

**Issue by strager** [microsoft/vscode#130957]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.53.2-1613044664; 1.59.0-1628120042; Insiders 1.60.0-1629092954
- OS Version: Linux Mint 20 Ulyana (x86_64)

When running an extension test, `didCloseTextDocument` does not get called when closing an editor. When running the extension outside test mode, `didCloseTextDocument` is called as expected.

Steps to Reproduce:

1. Extract this .zip: [vscode-close-editor-bug.zip](https://github.com/microsoft/vscode/files/6996897/vscode-close-editor-bug.zip)
2. Open the .zip's folder in VS Code.
3. In the "Run and Debug" pane (ctrl-shift-d), choose the "Test" target then press the "Start Debugging" arrow.

Expected: The test logs `test: closing` then `extension: didCloseTextDocument: file://[snip]/hello.js` then `test: closed`. `extension: onDidChangeVisibleTextEditors` is logged before or after the `didCloseTextDocument` message.
Observed: The test doesn't ever log a `didCloseTextDocument` message.

Full observed logs:
```
(node:297645) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
test: activating extension
extension: activated
test: starting
test: opening
extension: didOpenTextDocument: file:///home/strager/tmp/Projects/vscode/vscode-close-editor-bug/test_workspace/hello.js
extension: onDidChangeVisibleTextEditors
test: opened
test: closing
extension: onDidChangeVisibleTextEditors
test: closed
test: finished
```

**Comment by jrieken** [comment]
> When running an extension test, didCloseTextDocument does not get called when closing an editor

There is _no_ guarantee that `didCloseTextDocument` fires when an editor is being closed. There might be other parts holding references to the documents and/or for faster re-open the editor might decide to keep documents open for a short while.

**Comment by strager** [comment]
@jrieken Is the behavior supposed to be different between testing and production?
