### ISSUE TITLE
program runs but no output 

### ISSUE THREAD

**Issue by mojito76** [microsoft/vscode#130994]
[![image](https://user-images.githubusercontent.com/70653546/129732596-401464bd-9b0d-4b16-a7d4-21f2387066ed.png)
](url)

**Comment by mojito76** [comment]
I do not get any "hello!!!" to either output nor debug console. But I can get the result to show in Command Prompt.

Can't find good answer to this googling.
Thanks in advance!

**Comment by weinand** [comment]
I don't think that you are running your "hello.exe".
In the terminal you are just compiling hello.c into hello.exe:

<img width="260" alt="2021-08-17_17-59-01" src="https://user-images.githubusercontent.com/1898161/129760641-75527195-7dda-4862-92b2-80d4234cce99.png">

**Comment by mojito76** [comment]
Yeah, since I do get the right results in command prompt, as you say hello.exe is getting created properly but it is not run.

Used to push either "Run\Run without debugging" or "Run\Start debugging" and I would see results (if it built successfully) in the output window but now it's not the case since Monday. 
Don't know if it had to do with the update VS code recommended me to do just before the issue!?

My json files look like this:
launch.json
![image](https://user-images.githubusercontent.com/70653546/129840294-bb9e80dc-34f5-4668-a04c-5bb1c0170714.png)

settings.json
![image](https://user-images.githubusercontent.com/70653546/129840428-c231daa0-7f02-43a7-8c87-a5ec8cc5e4c8.png)

tasks.json
![image](https://user-images.githubusercontent.com/70653546/129840500-f04652e5-2889-4e95-b92a-39e541746e30.png)

**Comment by mojito76** [comment]
Allright, after the recommended VS code update, I needed to go to extensions and press "Reload" on my C/C++ Intellisense.
Now I do get result printed out .. to the terminal that is, as it used which is good enough for me. Many thanks 

![image](https://user-images.githubusercontent.com/70653546/129841827-21a49f08-1246-47d4-966e-f232c239eba3.png)
