### ISSUE TITLE
Powershell integrated terminal issue on Windows Server 2016

### ISSUE THREAD

**Issue by FMS1989** [microsoft/vscode#130934]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows server 2016

Steps to Reproduce:

1. When I try to rerun the debugger in vs code using powershell integrated console, the bar at the bottom does not turn orange. I cannot run the debugger again. I need to restart the powershell session. So far this is only happening on Windows server 2016. This is a recent issue and happened after I update VS code to 1.59.0

**Comment by weinand** [comment]
What debugger are you using?

**Comment by FMS1989** [comment]
I am using the debugger in VS code. I have Powershell launch current file selected. What specific info do you need and where can I find it?

**Comment by weinand** [comment]
VS Code's only built-in debugger is for JavaScript/TypeScript. All other debuggers are separate extensions.
Are you using the built-in JavaScript debugger?

**Comment by FMS1989** [comment]
Hello,

This is the code in my launch.json file. Does this help?

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File in Temporary Console",
            "script": "${file}",
            "args": [],
            "cwd": "${file}",
            "createTemporaryIntegratedConsole": true
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File w/Args Prompt",
            "script": "${file}",
            "args": [ "${command:SpecifyScriptArgs}" ],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch DebugTest.ps1",
            "script": "${workspaceRoot}/DebugTest.ps1",
            "args": ["-Count 55 -DelayMilliseconds 250"],
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Interactive Session",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Pester Tests",
            "script": "Invoke-Pester",
            "args": [],
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "PowerShell",
            "request": "attach",
            "name": "PowerShell Attach to Host Process",
            "processId": "${command:PickPSHostProcess}",
            "runspaceId": 1
        }
    ]
}

**Comment by FMS1989** [comment]
Please note this happens even I don't use the debugger. I can't run the scripts regularly twice in a row. I need to keep having to restart the current PowerShell.

**Comment by weinand** [comment]
You seem to use the PowerShell debugger (which is not part of VS Code but a separate extension). 
Please file the issue against the PowerShell extension.
