### ISSUE TITLE
Add a default kernel option to settings.json

### ISSUE THREAD

**Issue by JILPulvino** [microsoft/vscode#130946]
Perhaps the wrong venue to request this, but it would be great to have a default kernel setting for the settings.json file.

see this SO question: https://stackoverflow.com/questions/67516550/vs-code-how-do-i-select-jupyter-kernel-for-a-workspace

**Comment by greazer** [comment]
Thanks for the feedback, @JILPulvino. Setting a default kernel for a workspace is a reasonable request. We'll consider it! BTW, it's related to #114663

**Comment by DonJayamanne** [comment]
Related issues https://github.com/microsoft/vscode/issues/131370, https://github.com/microsoft/vscode/issues/131369

**Comment by joshdunnlime** [comment]
This is backlogged but I would like to reopen it. How can I do that?

**Comment by MSZeftawy** [comment]
Is there a deadline for adding this feature?

**Comment by patgratt** [comment]
would love for this to get implemented!

**Comment by srosenzweig09** [comment]
Looking forward to this feature!

**Comment by claudiaregio** [comment]
+1

**Comment by GoldEagle93** [comment]
Needed!

**Comment by shredder67** [comment]
+1 for this feature

**Comment by lee-uidam** [comment]
looking forward to it! Loses remote jupyter conn after sleep mode :(

**Comment by ilovejs** [comment]
alternatively,

force one and only one chose :)

```
"jupyter.kernels.filter": [
      {
        "path": "/bin/python3"
      }
    ]
```

**Comment by yanyu2015** [comment]
> alternatively,
> 
> force one and only one chose :)
> 
> ```
> "jupyter.kernels.filter": [
>       {
>         "path": "/bin/python3"
>       }
>     ]
> ```

why my config does‘t works?
```
    "jupyter.kernels.filter": [
        {
          "path": "F:\\ADS\\Pys\\anaconda\\python.exe"
        }
    ]
```

**Comment by jtkiley** [comment]
There are similar discussions about default kernels in devcontainers, for many of the same reasons.

See:

- https://github.com/microsoft/vscode-jupyter/discussions/13032
- https://github.com/microsoft/vscode-jupyter/issues/13641

**Comment by JosephDHenry** [comment]
The default python environment used to be picked by default, but a while ago its just stopped working and this is very inconvenient.

**Comment by Kradirhamik** [comment]
Interested in this as well

**Comment by cosmic-latte** [comment]
This is a reasonable and frequently used feature.

**Comment by PierXuY** [comment]
Interested in this, looking forward to it.

**Comment by oscar-wos** [comment]
I was running Windows 10, with WSL Debian 10, Python3.9, I had all the extensions installed (Python / Jupyter / WSL) and the kernel would be instantly picked, however now with Windows 11, WSL Debian 12, Python3.11 same extensions I have to manually reselect the kernel for each new notebook I open.

The install process had only 1 alteration, `pip install ipykernal --break-system-packages` would yield:

```ERROR: Could not find a version that satisfies the requirement ipykernal (from versions: none)
ERROR: No matching distribution found for ipykernal```

which I manually overrode with:

`pip install ipykernel==6.26.0 --break-system-packages`

**Comment by rpm5099** [comment]
Maybe this will also fix the problem of reconnecting to a jupyter kernel after reloading the window - it seems that the extension tries to reconnect to the same jupyter kernel URL (which no longer exists) instead of just using the base url that you put in when it asked which jupyter server you wanted to use.  

```
  response: F [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://[jupyter url]/api/kernels?1698785875946',
      status: 403,
      statusText: 'Forbidden',
      headers: [D [Headers]],
      counter: 0
    }
```

**Comment by DonJayamanne** [comment]
# Solutions

# 1. Hide all of the Python environments except the one you need
   * If you have n python environments and you only use one, then hide all of the others.
   * If you have just Jupyter and Python extension, then the remaining Python env will be automatically selected (however if you have other remote jupyter kernels, or other extensions that contribute kernels, then this will not get selected automatically). Please see solution 2.
   * Open a Jupyter ntoebook (to ensure the Jupyter extension gets activated)
   * Open your settings.json file
   * Add the setting `"jupyter.kernels.excludePythonEnvironments": [...]` and add the environments you wish to hide.

See here https://github.com/microsoft/vscode-jupyter/discussions/13032#discussioncomment-8049433

# 2. Install the extension `Default Python Kernels for Jupyter Notebooks`
* Currently this only works in the latest Insiders Version of VS Code (will be supported in the next release of VS Code and Jupyter extension)
* [Install VS Code insiders](https://code.visualstudio.com/insiders/)
* Install latest pre-release version of Jupyter Extension (a change in Jupyter extension is required to make this possible)
* Install the above extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.vscode-default-python-kernel

From here on, all notebooks opened will have the `active Python environment` selected as the kernel.
You can change the `Active Python Environment` for your workspace/globally using the command `Python: Select Interpreter`

You can find more information on the read me of the above extension.
