### ISSUE TITLE
Add terminal keybinding for cmd+. -> ctrl+c to match Terminal.app

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#130990]
See https://github.com/xtermjs/xterm.js/issues/3400

Code pointer: https://github.com/microsoft/vscode/blob/a26f3b00c0039cce6164b0c78b19b284a273c189/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L174-L186

**Comment by kunalnagar** [comment]
Hi. Is this issue under progress? If not, I'd like to take it up 🙂

**Comment by Tyriar** [comment]
@kunalnagar if you could hold off a few days to give @jihoon-ernesto a change to take it if they want that would be good (see https://github.com/xtermjs/xterm.js/pull/3401#issuecomment-900238232).

**Comment by TitanArmy** [comment]
1. File > Preferences > Keyboard Shortcuts. (Code > Preferences > Keyboard Shortcuts on macOS)


2. code > preferences > keywords> type "scm view"
