### ISSUE TITLE
UX: editor placeholder affordance

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#130971]
This is just a collection of the fact that in certain cases we decide to show a "placeholder" editor to show a message to the user:

**Workspace Trust**

![Screenshot 2021-08-17 at 09 17 52](https://user-images.githubusercontent.com/900690/129681539-836d47de-8af3-4da0-ab61-a3307737433d.png)

**Binary Files**

![Screenshot 2021-08-17 at 09 18 38](https://user-images.githubusercontent.com/900690/129681563-77bd094d-fcde-467f-b7bb-3983df7a8693.png)

**Unavailable Resources (new!)**

![Screenshot 2021-08-17 at 09 18 10](https://user-images.githubusercontent.com/900690/129681584-8222895b-5144-448f-afd8-ba05d3651ec1.png)

I wonder if the UX solution we have here is right or needs tweaks. I like that the UI is minimal but the presentation of the information might not be optimal, as well as discoverability of the action how to continue from there.

//cc @isidorn for accessibility concerns

//cc @stevencl who can maybe chime in how VS does it, if at all :)

**Comment by stevencl** [comment]
Here is an example in VS:

![image](https://user-images.githubusercontent.com/1704059/129712063-d146959a-f062-4574-8e5f-896109328e8d.png)

**Comment by stevencl** [comment]
@bpasero - I sent you a link to the VS design guidelines separately.

**Comment by isidorn** [comment]
For accessibility: just make sure that you properly set the `aria-label`. Here's how the regular [editor does it](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/aria/aria.ts#L1)
Apart from that it would be cool if the link to open anyway can be tabbed to, or navigated in some way.

As for the VS design: feels a bit heavy, but at least it gives the correct message immediately, you know it is disabled.

**Comment by bpasero** [comment]
The screenshot from VS reminds me that the link inside the editor should probably be using our link color?

**Comment by bpasero** [comment]
Using the `Link` widget now from `src/vs/platform/opener/browser/link.ts`

![image](https://user-images.githubusercontent.com/900690/129855639-ba45729e-5ae2-4f07-b038-dd375c8c7c3e.png)

@isidorn I verified that the link is keyboard accessible too and opens on `Enter` key, however I was not seeing any ARIA labels:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/opener/browser/link.ts#L63-L67

Maybe you could advise if a change is needed on the level of that widget, it is used in many more places.

**Comment by bpasero** [comment]
Slightly related, I see how `button.ts` registers to `Gesture`:

https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/browser/ui/button/button.ts#L98-L98

While `link.ts` does not:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/opener/browser/link.ts#L69-L69

In addition, `button.ts` seems to support `Space` and `Escape` key, while `link.ts` does not.

**Comment by isidorn** [comment]
@bpasero
No need to set the `aria-label` on the `AnchorElement` since screen readers can handle those elements, based on their `title` / `href`.

I think they should be consistent, and that both button and link support `Space` and `Escape`.

**Comment by bpasero** [comment]
I verified that both NVDA and macOS read the content of the editor. 

Seeing how standard links behave in browsers, I did not add the `Space`/`Escape` treatment because they also do not behave like that.

**Comment by misolori** [comment]
@bpasero do you own this area or someone else? unsure who else to assign it to

**Comment by bpasero** [comment]
I don't mind closing this as wontfix if UX team decides no changes are needed. If not, I am happy to discuss UI designs in a UX call and then decide on next steps.

**Comment by stevencl** [comment]
I am not aware of any pressing reason to change this at this point.

**Comment by misolori** [comment]
Ok, let's bring up the mock ups that @lychung7 made in the UX Call this week to get feedback. It would be great to have the messaging there consistent and easier to parse at a glance.

**Comment by bpasero** [comment]
Yeah agree, we can make it a topic in a UX call at least and then decide if we want to proceed.

**Comment by bpasero** [comment]
Made a PR to match the second designs in https://github.com/microsoft/vscode/issues/130971#issuecomment-943637159. What I really like about it that visually the editor is clearly different from normal text editors, though arguably a bit heavier now:
![Recording 2022-04-07 at 13 44 55](https://user-images.githubusercontent.com/900690/162191865-c6478203-9474-49b3-8d6f-ac57a46b2edf.gif)

**Comment by bpasero** [comment]
Fyi I am leaning towards changing the look to use buttons and not links:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/900690/209392781-a1872fb7-139d-4706-9697-d6fb6abf50d9.png">

I feel buttons are our standard widget to offer interactions in most places.

//cc @daviddossett
