### ISSUE TITLE
Terminal 

### ISSUE THREAD

**Issue by MVITA-nkanga** [microsoft/vscode#130940]
Issue Type: <b>Bug</b>

I come a cross this issue when I run my code for the first time it executes without a problem but when ever I try to run code after that it really just not responding anymore no error just not a single response I refresh close and reopen uninstall reinstall the problem persists.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
cpptools|ms-|1.5.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464:30350172
bridge0723:30353136

```

</details>

**Comment by meganrogge** [comment]
No errors in the dev tools console?

Can you pls provide a gif of this happening?
