### ISSUE TITLE
Saved a file

### ISSUE THREAD

**Issue by aramix** [microsoft/vscode#130977]
Issue Type: <b>Bug</b>

Not sure, since I just saved the file and TypeScipt server died unexpectedly.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1032-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 7|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 477a2a2f-7d99-4004-bf9f-f3e5ad15d5f2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pair1|
|OS|Linux x64 5.4.0-1032-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 x 3179)|
|Memory (System)|62.03GB (17.42GB free)|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
flutter-snippets|ale|2.0.0
Handlebars|and|0.4.1
quitcontrol-vscode|art|4.0.0
bracket-pair-colorizer-2|Coe|0.2.1
systemd-unit-file|coo|1.0.6
LogFileHighlighter|emi|2.11.0
auto-rename-tag|for|0.1.8
vscode-todo-highlight|jgc|2.0.3
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
nc-gcode|ML|0.13.0
remote-containers|ms-|0.191.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.9
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.9.0
shellman|Rem|5.6.0
shebang-snippets|rpi|0.1.4
vscode-nginx|sha|0.6.0
gitconfig|sid|2.0.1
swdc-vscode|sof|2.5.23
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
propertylist|zho|0.0.2
material-theme|zhu|3.11.3
vscode-markdownlint|Dav|0.43.2
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
shell-format|fox|7.1.0
elixir-ls|Jak|0.8.0
vscode-sbt-scala|lig|0.2.4
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.11.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1195043623
powershell|ms-|2021.8.0
vsliveshare|ms-|1.0.4673
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|0.22.0
shellman|Rem|5.6.0
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
serverless-ide-vscode|Thr|0.5.32
shellcheck|tim|0.15.2

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
