### ISSUE TITLE
VS Code window is not maximized when restored from minimized

### ISSUE THREAD

**Issue by andreldm** [microsoft/vscode#130932]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.13.7-arch1-1

- OS Version: Arch Linux

Steps to Reproduce:

1. Open a text file with VS Code (from desktop, file manager, terminal...)
2. Maximize VS Code if not maximized already
3. Minimize VS Code
4. Open the same or another file

Actual results:
1. VS Code window is NOT maximized

Expected results:
1. VS Code window is maximized

Details:
- If the bug is not reproducible, try to first resize VS Code window to a small size (e.g. 800x600) then continue from step 2.
- I was able to reproduce this bug on Xfce and Gnome (Xorg and Wayland), but not on Windows.
- I don't think this is a duplicate of #114632, could be related though
- Setting `window.titleBarStyle` to custom or native makes no difference

https://user-images.githubusercontent.com/599565/129616718-1b364927-6ddc-4484-bb2c-c3f6a9fe3a0b.mp4

**Comment by bpasero** [comment]
Might be OS dependent or Electron specific. All we do when opening the file again is to focus the window, this seems to take away the window state.

**Comment by andreldm** [comment]
@bpasero you're right, I was able to reproduce this bug with [electron-quick-start](https://github.com/electron/electron), I just had to add single window behavior based on this [snippet](https://stackoverflow.com/a/52633637/3109776).

Now I'm going to investigate electron and ping back if I find something interesting.

**Comment by bpasero** [comment]
Thanks a lot for reporting this to Electron!
