### ISSUE TITLE
Impossible to use vertical scrollbars in the debugger.

### ISSUE THREAD

**Issue by kzwix** [microsoft/vscode#130901]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10 Enterprise, version 21H1

Steps to Reproduce:

1. Debug a program, using a breakpoint. When the debugger stops, you should see the debug panel left of the code panel, and, in that debug panel, there are the variables panel, then the watch panel, then the call stack, and then, the breakpoints list.
2. If you have enough variables, watch expressions, or whatever, there should be a need for a scrollbar, to be able to browse everything. However, when trying to get the scrollbar to appear, the scrollbar for the whole debug panel will appear too, and will mask the scrollbar for the panel you want to scroll, thus making it impossible to navigate it using the mouse.
You can use the keyboard arrows to a certain extent, but that, too, will fail if in some configurations.

Please note that the bug only appears if the "sum" of the panels is too big. When I reduced some of the panels to their title only, the "debug panel" scrollbar didn't appear, thus letting access to the "variables panel" scrollbar, for instance.

So, would it be possible to:
- Have a way to keep the scrollbars ALWAYS visible ?
- Have the scrollbars NOT overlap each other ?

**Comment by isidorn** [comment]
Please use the following setting `"workbench.list.horizontalScrolling": true`
As for other issues you mention (overlapping scrollbars) that is covered by other issues that are already open. Thanks

**Comment by kzwix** [comment]
I wasn't speking about horizontal scrolling. Vertical scrolling is the problem, here.

And I still have to find a way to keep the scrollbars displayed at all time, instead of fading out and disappearing.

**Comment by isidorn** [comment]
That is just how the split view is designed. We have no plans to change that. If you think it is an ui glitch a picture would help.
