### ISSUE TITLE
Report Issue Menu Item Broken on Edge

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#13098]
- VSCode Version: Code - Insiders 1.6.0-insider (17b0c8d028d3b7ceaf3b7c2c226cd0ad6b1feb51, 2016-09-30T06:10:50.521Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: `sandy081.todotasks-0.4.0`, `seanmcbreen.Spell-0.8.6`

Steps to Reproduce:

1. Report an issue from help menu 
2. Have more than one extension installed
3. Edge is the default browser
4. You will get a web page with # only i.e.
5. To make this issue I copied the URL into Chrome - so this is the exact case that failed on Edge

![image](https://cloud.githubusercontent.com/assets/1051190/19005810/5b35e37e-8711-11e6-9498-cb3e73c11262.png)

Repro for 1 extension (this works)
https://github.com/microsoft/vscode/issues/new?body=-+VSCode+Version%3a+Code+-+Insiders+1.6.0-insider+(17b0c8d028d3b7ceaf3b7c2c226cd0ad6b1feb51%2c+2016-09-30T06%3a10%3a50.521Z)%0a-+OS+Version%3a+Windows_NT+ia32+10.0.14393%0a-+Extensions%3a+%60seanmcbreen.Spell-0.8.6%60%0a%0aSteps+to+Reproduce%3a%0a%0a1.%0a2. 

Repro for 2 extnesions (this gives the `#` page)
https://github.com/microsoft/vscode/issues/new?body=-+VSCode+Version%3a+Code+-+Insiders+1.6.0-insider+(17b0c8d028d3b7ceaf3b7c2c226cd0ad6b1feb51%2c+2016-09-30T06%3a10%3a50.521Z)%0a-+OS+Version%3a+Windows_NT+ia32+10.0.14393%0a-+Extensions%3a+%60sandy081.todotasks-0.4.0%60%2c+%60seanmcbreen.Spell-0.8.6%60%0a%0aSteps+to+Reproduce%3a%0a%0a1.%0a2.

cc @bgashler1 who saw some other issues

**Comment by chrmarti** [comment]
Might be the XSS filter of Edge. My console shows: SEC7130 "Potential cross-site scripting detected in [URL]. The content has been modified by the XSS Filter. "

Interestingly the above URL does not repro it on my machine. Using the command in VS Code does.

**Comment by chrmarti** [comment]
Too many backticks appears to trigger it. If I replace %60 (a backtick) with ' in an URL that reproduces the problem, it goes away.
