### ISSUE TITLE
vs vode just can't find the git

### ISSUE THREAD

**Issue by flowfire** [Microsoft/vscode#13097]
- VSCode Version:1.5.3
- OS Version:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

Steps to Reproduce:

1. install git
2. open vscode

![test](http://ww1.sinaimg.cn/large/93d5a393gw1f8c8erszjoj208f0a474z.jpg)
![test](http://ww4.sinaimg.cn/large/93d5a393gw1f8c8g7m0rkj20ir0d5tdn.jpg)

**Comment by Emeryao** [comment]
just add the git directory to the `PATH` environment variable
把git路径加到`PATH`环境变量里就好了兄弟

**Comment by joaomoreno** [comment]
Or use the `git.path` configuration variable.
