### ISSUE TITLE
Codespace auto forwarded service not forward POST request to local server, 302 redirect to sign in instead.

### ISSUE THREAD

**Issue by neekey** [microsoft/vscode#130921]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  Github Codespace, stable
- OS Version: Firefox / Mac OS

Steps to Reproduce:

1. start up my local service in codespace, which i used 8081 as my port
2. codespace automatically generated a link for me, like `https://neekey-xxxxxxx-8081.githubpreview.dev/`
3. my POST requests like `https://neekey-xxxxxxx-8081.githubpreview.dev/functions/user_getCurrentUser` all get http code 302, with response header `Location` point to `https://neekey-xxxxxxx-8081.githubpreview.dev/signin?cid=xxxxxxxx&rd=https://neekey-xxxxxxx-8081.githubpreview.dev%2Ffunctions%2Fuser_getCurrentUser`

I wrote a simple GET/POST route to see if there's any way it can get through:

```js
app.get('/', (req, res) => {
        console.log('receive request');
        res.send(200, 'hello');
      })

      app.post('/test', (req, res) => {
        console.log('receive post request');
        res.send(200, 'hello post');
      })
```

The GET request got through, but the POST to `/test` bumped into the same issue, being 302 redirected.

Is there any policies to prevent the forwarding to request method other than GET? or is there any setting i missed?

Thank you

**Comment by alexr00** [comment]
@cmbrose I think this is as designed. Can you confirm?

**Comment by ryansmith94** [comment]
@alexr00 @cmbrose any update? Also having the same issue.

**Comment by ryansmith94** [comment]
Okay, I was able to fix this, go to the Ports tab.
![image](https://user-images.githubusercontent.com/3045513/130599177-a47af216-3d89-4f88-a59b-a17f9f0b18a6.png)

Then right-click the privacy for the forwarded port which will be "Private" and set to "Public".
![image](https://user-images.githubusercontent.com/3045513/130599216-a76985f5-cbf2-49b9-b38d-1e4ddbf22f91.png)

**Comment by alexr00** [comment]
Thanks for the update @ryansmith94. This confirms that the auth redirect by design.

**Comment by neekey** [comment]
It works, thank you guys
