### ISSUE TITLE
[less] mixins "{ expected" errors

### ISSUE THREAD

**Issue by coderfin** [Microsoft/vscode#131]
When editing a **.less** file unexpected errors show when working with mixins. The error text is `{ expected`. These errors show when using a mixin without wrapping it in a CSS selector or when using a mixin in a media query. 

To reproduce take an example from lesscss.org.
http://lesscss.org/features/#loops-feature
http://codepen.io/anon/pen/EjqwNr?editors=010

The Codepen contains code that can be used to replicate `{ expected` errors in Visual Studio Code 0.10.1. In Codepen no errors are shown and the code compiles fine. If this code is put into a **.less** file in Visual Studio Code 0.10.1 you will see the errors on lines 8 and 11. The image below shows the red squiggles signifying the *"errors"* in the code.

![screen shot 2015-11-18 at 6 09 04 pm](https://cloud.githubusercontent.com/assets/1514172/11259540/9f7a5272-8e1f-11e5-965f-4d035ea70c8e.png)

**Comment by mrmlnc** [comment]
The same thing occurs in the ruleset.

![image](https://cloud.githubusercontent.com/assets/7034281/12112805/ec2a7d12-b3af-11e5-9a19-9e66c863b5f1.png)

**Comment by torabian** [comment]
Also we can't use when statement:
```
& when (@direction = rtl) {
      
}
& when (@direction = ltr) {
     
}
```

**Comment by rdennis** [comment]
[Detached rulesets](http://lesscss.org/features/#detached-rulesets-feature) show as errors when being assigned `(line 7)`, or used as a mixin parameter `(line 4 and previous comments)`.
<img width="210" alt="screen shot 2016-07-14 at 8 56 48 pm" src="https://cloud.githubusercontent.com/assets/1097629/16861432/20a70ffa-4a06-11e6-89b1-23dec137c199.png">

**Comment by adamal** [comment]
I am still seeing this issue in 1.8.1 with a media query nested in a detached ruleset. E.g.
![screen shot 2017-01-12 at 14 37 45](https://cloud.githubusercontent.com/assets/3245228/21891816/bfd0134e-d8d4-11e6-84f3-2eccb2752d50.png

**Comment by rdennis** [comment]
Also, passing a detached ruleset directly as an argument directly to a mixin still causes the issue.

![screen shot 2017-01-12 at 8 10 46 am](https://cloud.githubusercontent.com/assets/1097629/21892959/ba85179e-d89e-11e6-88de-696f2e75d95b.png)

**Comment by aeschli** [comment]
Please file new, separate issues, thanks! If you can also attach the code snippet, that would speed things up for us.
