### ISSUE TITLE
Cannot colorize parts of Ligatures

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131092]
Set
```
"editor.fontLigatures": true`
"editor.fontFamily": "'Cascadia Code PL', Consolas, 'Courier New', 'Segoe UI emoji', monospace",
```
and create a foreground color decoration for `>` in `/>`.

Notice that it has no effect.

Create a color decoration for `/` in `/>`. Notice that is colors the entire ligature.

This problem can be reproduced by this fiddle:
https://jsfiddle.net/xL4ms6e8/

I think, as fix, characters that have different inline class names should be separated by a no-width-whitespace.

This issue is the underlying cause of https://github.com/microsoft/vscode/issues/130996.

**Comment by IllusionMH** [comment]
Will these ZWS affect editor actions like <kbd>Backspace</kbd> and copy operations?

P.S. Typo in code - `` ` `` instead of `,`

**Comment by hediet** [comment]
> Will these ZWS affect editor actions like Backspace and copy operations?

No, it is only for rendering the view model.
All operations work directy on the model/view model.

**Comment by hediet** [comment]
After discussing this with @alexdima, we probably cannot fix this in a performant way in the editor, as we would need to insert a lot of zero-width-whitespaces.

Maybe this is a chrome bug.

I leave this issue open to track this bug.
