### ISSUE TITLE
Find/replace all: request keybinding for DISMISS action

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#131095]
Issue Type: <b>Feature Request</b>

<img width="436" alt="Screen Shot 2021-08-18 at 10 06 39" src="https://user-images.githubusercontent.com/382183/129913190-3ca3dc98-b514-4f46-9137-6c29063ca015.png">

^^ I would like this to please be keyboard shortcutable

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Mac: Cmd+Backspace; Win/Lin: Del

**Comment by fulldecent** [comment]
@JacksonKearl but the tooltip is not confirm that:

The one shows
<img width="607" alt="Screen Shot 2021-08-19 at 17 12 30" src="https://user-images.githubusercontent.com/382183/130144963-d72b8571-8df3-413e-a3d1-b0a8299da108.png">

But the other doesn't
<img width="586" alt="Screen Shot 2021-08-19 at 17 12 33" src="https://user-images.githubusercontent.com/382183/130144979-26a151c6-18c4-46b4-bcaa-2398bf900cb0.png">

**Comment by JacksonKearl** [comment]
Fair

**Comment by fulldecent** [comment]
Awesome, thank you!
