### ISSUE TITLE
File starting with "hidden " doesn't appear in file explorer

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/vscode#13106]
- VSCode Version: 1.5.3
- OS Version: Win10 64-bit

Steps to Reproduce:

1. Create a file named "Hidden from VScode.md" or similar name starting with "hidden " or "Hidden "
2. Open the folder containing that file

Result:
![image](https://cloud.githubusercontent.com/assets/6685088/19010013/e53fc91e-872e-11e6-9724-1a18f6d83374.png)

The blank spot between the two there otherwise behaves normally and will successfully open "hidden file.txt"

**Comment by Tyriar** [comment]
I believe this is already fixed in Insiders, fyi @bpasero
