### ISSUE TITLE
Logo above watermark commands animates every time it becomes visible

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#13108]
If I have one editor open, then close it, the vscode logo does the slide up animation. Is this by design? Maybe, but I thought maybe it's only supposed to happen the first time or something.
![sep-30-2016 18-31-57](https://cloud.githubusercontent.com/assets/323878/19010930/44984972-873e-11e6-899a-fa1272e8040b.gif)

**Comment by chrmarti** [comment]
@bgashler1 Did you mention that is not intended?

**Comment by bgashler1** [comment]
This is not intended. See #12877 
We can address it in October.

**Comment by bgashler1** [comment]
Closing so we can track in the original issue mentioned above.
