### ISSUE TITLE
Notebook formatting randomly replaced the initial line of all cells for the same code thing and I lost hours of work 

### ISSUE THREAD

**Issue by romanovzky** [microsoft/vscode#131009]
Does this issue occur when all extensions are disabled?: I don't know and I don't want to find out

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.10.56-1-MANJARO

Steps to Reproduce:

Not sure and I'm not trying to find out.

What happened:

I was working on a notebook for a few hours. The code was getting messy to read so I ran `Notebook: Format Notebook`. The results couldn't be more frustrating: all the cells first line was replaced by a seemingly random bit of code (maybe something I had in the clipboard?). Since the code format saves the notebook, and for some reason `ctrl-z` did not revert the cells to the previous state, I lost hours of work as I now have to remember which piece of code was in the first line in every single cell.

In addition to all the regressions added with the new version, I'm going to go back to `jupyter lab/notebook` for now as working on notebooks with Code has become painfully counter-productive. It does feel like I'm using a `nightly` or `dev` build.

**Comment by rebornix** [comment]
Can you confirm what you are seeing is the same as https://github.com/microsoft/vscode-python/issues/16980 ?

**Comment by romanovzky** [comment]
Yes, it seems exactly that. Sorry for my previous tone of voice, it was just very very frustrating at the time. Let me know if there is more information that I can provide.

One thing that I noticed, but I'm not sure if it was related, was a vscode popup notification (those that appear on the bottom right) with the error sign saying `could not load model`, but again I'm not sure if this is related.

**Comment by rebornix** [comment]
@romanovzky thanks for your help, you have already been pretty helpful. We will look into a fix and see how soon we can get it released.
