### ISSUE TITLE
Miodrag

### ISSUE THREAD

**Issue by utazabanje** [microsoft/vscode#131069]
Issue Type: <b>Bug</b>

Go to some extension download, and just scroll on the description of the extension. Text will go over Details, Feature contributions, Changelog tabs. Looks like some z-index is broken.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<img width="1638" alt="Screenshot 2021-08-18 at 10 31 49" src="https://user-images.githubusercontent.com/25405661/129866039-e908f727-42ed-4d2f-9a2f-39553ada2b4c.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (2.81GB free)|
|Process Argv|--crash-reporter-id 1fa3902b-cd00-482c-85ea-5b860ce2de0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.6.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
vscode-npm-script|eg2|0.3.22
twig-language-2|mbl|0.9.2
vscode-docker|ms-|1.15.0
remote-containers|ms-|0.191.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30351747

```

</details>

**Comment by sandy081** [comment]
@mjbvz Is this web view related?

**Comment by mjbvz** [comment]
It looks like an extension page issue instead of a webview specific bug. Try calling `webview.layoutWebviewOverElement` if the webview is in the incorrect position:

https://github.com/microsoft/vscode/blob/73cd17eab7b0770295a566fb9a90a8a6e0fcac30/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L596

**Comment by utazabanje** [comment]
@mjbvz @sandy081 I think we can close this one since the issue is not present anymore.
