### ISSUE TITLE
Duplicate actions for sidebar? Focus vs. Show

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#131032]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Win10

Steps to Reproduce:

1. See screenshot, try both options
2. They do the same thing, don't they?

It's confusing, and I think one of them should be removed. I think it's like this for all side views.

![image](https://user-images.githubusercontent.com/5781692/129787152-ccb24e18-d1f5-4eda-b8e4-a311c629b558.png)

**Comment by isidorn** [comment]
We might have duplicate actions, I would double check if there is some difference when there are multiple views in the explorer. One action might be coming from viewlet and another from the view.

I suggest to not do anything here, since we can not remove actions for backwards compatibility.
