### ISSUE TITLE
strange shapes rendered in vscode

### ISSUE THREAD

**Issue by positiveflat** [microsoft/vscode#131058]
Issue Type: <b>Bug</b>

Same problem as this issue https://github.com/microsoft/vscode/issues/110378 is occurred in my VSCode.

- VSCode version: v1.59.0
- OS: macOS Big Sur 11.5.2

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|64.00GB (1.01GB free)|
|Process Argv|--crash-reporter-id 96d547f2-7172-4b9c-bd54-1e4d290be337|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.2
stackoverflow-search|Ale|1.2.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vscode-pull-request-github|Git|0.29.2
path-autocomplete|ion|1.17.1
svelte-vscode|Jam|0.9.3
svg|joc|1.4.9
vscode-peacock|joh|3.9.1
rainbow-csv|mec|1.9.1
vscode-filesize|mkx|3.1.0
vscode-language-pack-ja|MS-|1.59.3
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.8.1105858891
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
hexeditor|ms-|1.8.2
vscode-json-editor|nic|0.3.0
vetur|oct|0.34.1
vscode-jest|Ort|4.0.3
material-icon-theme|PKi|4.9.0
vscode-yaml|red|0.22.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
music-time|sof|2.2.21
swdc-vscode|sof|2.5.24
svelte-vscode|sve|105.3.4
sass-indented|syl|1.8.17
language-stylus|sys|1.13.0
gitblame|wad|8.1.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you try the suggestion from this comment on that issue?

https://github.com/microsoft/vscode/issues/110378#issuecomment-725690351

**Comment by positiveflat** [comment]
Yes, but still facing same issue.

**Comment by gjsjohnmurray** [comment]
And also after you run the command to reload with all extensions disabled?

**Comment by positiveflat** [comment]
Thanks! It seems to be fixed.
I disalbed all extensions before trying https://github.com/microsoft/vscode/issues/110378#issuecomment-725690351 , but I didn't do it after that.

**Comment by gjsjohnmurray** [comment]
Since it's OK with all extensions disabled, maybe use the Start Extension Bisect command to investigate if the problem is coming from just one of your extensions.
