### ISSUE TITLE
Unbound breakpoint : launch.json not correctly defined

### ISSUE THREAD

**Issue by MerwaneHAMADI** [microsoft/vscode#131056]
Issue Type: <b>Bug</b>
Hi,
I receive an unbound breakpoint every time I am trying to setup a breakpoint on visual studio code.

Things to know that might give you a hint of what my problem is:
- I am working on the opensearch dashboard repo  : https://github.com/opensearch-project/OpenSearch-Dashboards => you can see the webpack config and ts config.
- there are multiple tsconfig files in the repo, working in cascade. They point to a .target directory which seems to be working fine.
- When using debugger; it's working fine, but it's showing the loaded script. This loaded script looks nice, the problem is that I can't edit it since it's not the original file. and so I am always working with 2 files, the original and the loaded, it's a lot of time wasted.
- The sourcemap is working perfectly on google chrome. I can set breakpoints there, but I would rather do it on vscode.
- there is a base path randomly generated by the app.
- I think the problem is the outfile. Because my conversion from JS to TS works well (proof is that chrome breakpoint work). But the conversion TS to JS doesn't work. And that's what outfiles changes according to this [issue](https://github.com/Microsoft/vscode/issues/57752)

This is my launch.json. Here I only show you the simplest option I am using, but I have tried a bunch of things and none of them have worked : change overridepaths, outfiles, webRoot, localRoot.

```
{
    "type": "pwa-chrome",
    "name": "opensearch-dashboard",
    "request": "launch",
    "url": "http://localhost:5603/mji", => this is the base path
    "sourceMaps": true,
}

Tell me if you need more information to solve my problem. 

I don't know exactly what you need to solve my problem. I was thinking of a screenshot of the loaded scripts, and of the repo in general.


```

PS : there is something very confusing about outfiles parameter in launch.json. According to [this issue](https://github.com/opensearch-project/OpenSearch-Dashboards ), it's necessary most of the time, and yet, it's not in the default config when you use the debugger for the first time. Why ?

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 4dd49d49-9ced-4699-a92c-e6a301fb6bb3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version **Issue happening even without the extensions**
---|---|---
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.6.0
kite|kit|0.147.0
theme-monokai-pro-vscode|mon|1.1.19
autoimport|ste|1.5.4
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793

```

</details>

**Comment by MerwaneHAMADI** [comment]
Something I should mention.
When I run jest : 
`node --inspect scripts/jest ` and attach the port 9229 to vs code, all the breakpoints work.

But they don't work when I serve opensearch dashboard  and visit it on chrome. I think the conversion JS to TS works but not TS to JS. Somehow vscode can't find the associated JS file of a TS file, and therefore can't put a breakpoint on the bundled JS file.
I can provide a screencast if you need me to. That might make things more clear.

**Comment by connor4312** [comment]
/jsDebugLogs

The first thing I notice is that you don't have a `sourceMap: true` in your tsconfig, so sourcemaps won't get generated to allow us to point back to the original sources.

**Comment by MerwaneHAMADI** [comment]
Please watch this screencast (sorry for the waiting time)
https://www.youtube.com/watch?v=1eKEEL1OStQ
In the screencast I do the following: 
- show launch.json
- add sourcemap in tsconf
- run jest and shows that it's working great.
- serve opensearch dashboard using :

`node --inspect --nolazy scripts/opensearch_dashboards --dev  `
- show that I can't reach the breakpoint.


The logs have been sent by email, they were too big on github.

**Comment by connor4312** [comment]
It looks like you need to customize your sourceMapPathOverrides, like setting `"/entry:core/*": "${workspaceFolder}/*`. You can always look at the file path of the 'virtual' file when you hit a `debugger` statement to see what the reported path is and how to fix it.

**Comment by MerwaneHAMADI** [comment]
Thanks.
It worked with this setting : 

it worked with : 
```
"sourceMapPathOverrides": {
    "/entry:core/src/core/public/*": "${workspaceFolder}/src/core/public/*"
}
```
For anyone having the issue in the future : 
The idea is to map the TS file in google chrome to your TS file in vscode.

**Comment by MerwaneHAMADI** [comment]
@connor4312 I have another question related to the same problem.
I have 20 sourceMapPathOverrides to define, but the rule is always the same : 
Rule : 
"/plugin:$nameOfPlugin/src/plugins/toSnakeCase($nameOfPlugin)/*":"${workspaceFolder}/src/plugins/toSnakeCase($nameOfPlugin)/*",

Example : 
"/plugin:apmOss/src/plugins/amp_oss/*": "${workspaceFolder}/src/plugins/apm_oss/*",


is there a way to do this in one line instead of manually define the 20 sourceMapPathOverrides ?
