### ISSUE TITLE
You can never replace \r\n with \n through global replacement.

### ISSUE THREAD

**Issue by SilkageNet** [microsoft/vscode#131050]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment]
Why not use the 'Change End Of Line Sequence' command? (see https://code.visualstudio.com/updates/v1_40#_editor)

This is also accessible by clicking on the status bar indicator:

![image](https://user-images.githubusercontent.com/6726799/129853872-69e71909-80f5-420e-b296-b91b3c9c553c.png)

**Comment by roblourens** [comment]
Yes, the editor will normalize line endings based on what is detected/configured.
