### ISSUE TITLE
Ability to "Go Back" and "Go Forward" by touchpad gestures

### ISSUE THREAD

**Issue by ustyantsevxx** [microsoft/vscode#131077]
It would be nice to be able to jump back and forward in code ("**Go back**" and "**Go Forward**" commands in command pallette) by pressing mouse side buttons or touchpad (e.g three fingers sideway swipe in MacOS does the thing in Finder and Chrome  by default).

Right now these actions do nothing in VSCode ((

**Comment by gjsjohnmurray** [comment]
My mouse side buttons already do this.

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by ustyantsevxx** [comment]
> My mouse side buttons already do this.
> 
> Version: 1.59.0 (user setup)
> Commit: [379476f](https://github.com/microsoft/vscode/commit/379476f0e13988d90fab105c5c19e7abc8b1dea8)
> Date: 2021-08-04T23:13:12.822Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.19043

My bad. I didn't use mouse recently)
I meant touchpad gestures in this case.
