### ISSUE TITLE
Pinned tabs: add another `workbench.editor.pinnedTabSizing` setting to show tabs fully

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#131053]
Issue Type: <b>Bug</b>

The full file name cannot be displayed after the editor tab is enlarged
![2021-08-15_081326-001](https://user-images.githubusercontent.com/54253524/129831071-de34650b-0284-4116-a47a-fa1b5c697ee2.png)
![Uploading 2021-08-15_081326-001.png…]()

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by bpasero** [comment]
Does it improve when you configure `workbench.editor.tabSizing: fit` in settings?

**Comment by bpasero** [comment]
This is a consequence of pinning the tab and currently works "as designed", but fair feature request.

**Comment by zhouxinghong** [comment]
Cannot display the full file name even if it is not fixed
![2021-08-18_162456](https://user-images.githubusercontent.com/54253524/129865341-c4251cff-b32c-40cf-9c89-94d3d1641499.png)

**Comment by bpasero** [comment]
@zhouxinghong try with setting `workbench.editor.tabSizing: fit`

**Comment by zhouxinghong** [comment]
workbench.editor.tabSizing: fit can temporarily alleviate the problem, but this setting changes the tabs to multiple lines and changes the original display mode.
The best way to display is that the tabs can fully display the file name according to the length of the file name without changing the original display mode. For example: short file name tabs are automatically shortened, and long file names are automatically shortened. Lengthen to show the full file name
![2021-08-18_001](https://user-images.githubusercontent.com/54253524/129870039-7b57f780-abc6-4bb4-9546-c34e47df299d.png)

**Comment by zhouxinghong** [comment]
Look at the display style after setting, is it terrible! This is the result of the current tab not being able to display the file name according to the length of the file name....
![2021-08-18_002](https://user-images.githubusercontent.com/54253524/129871241-7ebe6b57-0940-426e-9b12-8d05da99bf1e.png)
![2021-08-18_003](https://user-images.githubusercontent.com/54253524/129871245-1d1607b6-d54e-4568-90f5-599fd0250b0e.png)

**Comment by zhouxinghong** [comment]
So if the problem is obvious, it's better to improve it!
