### ISSUE TITLE
Auto choose suggestion when press dot

### ISSUE THREAD

**Issue by vdnhi** [microsoft/vscode#131085]
Issue Type: <b>Bug</b>

Just typing multiple dots (...) and it auto completes with the suggestions instead of filling dots only.

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (2.02GB free)|
|Process Argv|--crash-reporter-id 2b4d9f53-3268-42d8-b64b-3d6232420c7b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
rescript-vscode|che|1.1.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
go|gol|0.27.1
vscode-graphql|Gra|0.3.16
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.1
jupyter|ms-|2021.8.1236758218
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.5.1
LiveServer|rit|5.6.1
cmake|twx|0.0.17
vscode-icons|vsc|11.6.0
vim|vsc|1.21.6
material-theme|zhu|3.11.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464:30350172
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

Demo video

https://user-images.githubusercontent.com/9262617/129898469-1809f5bc-8d29-45b0-8dfd-1638b1c52f64.mov

**Comment by gjsjohnmurray** [comment]
Probably #130096 which is fixed in upcoming recovery release.

**Comment by vdnhi** [comment]
Then this is a duplicated issue, thank you.
