### ISSUE TITLE
Feature Request: Colored line scopes

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131001]
Now that bracket pair colorization landed, we can do more advanced stuff like this:

![](https://user-images.githubusercontent.com/5593825/129736776-cb8c7bd2-0a15-4ca7-97d2-c5417bf83398.png)

(Idea by @CoenraadS)

**Comment by hediet** [comment]
Also see #130379 for a related feature.

**Comment by CoenraadS** [comment]
I will include this screenshot also, as it shows more 'smart' behavior that would be nice to have.

![image](https://user-images.githubusercontent.com/5593825/129740613-f0a7c7e3-f527-4c04-b096-95a6c782ade9.png)

**Comment by Stanzilla** [comment]
Any plans to also add the "consecutive/independent color mode" and "force unique opening color" settings?

**Comment by hediet** [comment]
@Stanzilla please open a separate issue for these two features!
In these feature requests, please provide examples that demonstrate the usefulness of the feature.

**Comment by Stanzilla** [comment]
Done!

https://github.com/microsoft/vscode/issues/131027
https://github.com/microsoft/vscode/issues/131029

**Comment by byehack** [comment]
Any plans to also add the "show Brackets In Ruler" settings?

it's really usefull when brackets are so long. we can see first/end of bracket in ruller with specified color in lef/middle/right of ruler.

**Comment by hediet** [comment]
@byehack please file an issue request!

**Comment by hediet** [comment]
Maybe this feature could even be implemented in an extension if some version of https://github.com/microsoft/vscode/issues/131062#issuecomment-900901980 lands.

---

Also, I think it might make sense to only show these colored line scopes when the distance of opening/closing bracket is less than 500 lines apart (it is very cheap to compute the distance).
In this case, you can quickly iterate over all lines in between, find the smallest indentation and setup all decorations.

For a performant implementation that spans thousands of lines, you should not walk all lines in between on every cursor move operation. In this case, the tree data structure needs to be extended so that you can cheaply compute the smallest indentation in logarithmic time.
However, this probably will prevent reusing text nodes.
Also, you would need to compute the line decorations on demand for the current viewport.

**Comment by sanket-bhalerao** [comment]
@hediet is this feature separate from the `editor.bracketPairColorization.enabled`? 
I don't feel comfortable(at least at this point in time) with the brackets being colored differently. However, I would love to see the line scopes as shown by @CoenraadS. If it's a possibility I would love to enable the line scopes and keep the bracket pair colorization disabled.

**Comment by hediet** [comment]
If implemented, this feature could be enabled independently, yes.

**Comment by JustinGrote** [comment]
This is the only thing preventing me from removing the BPC2 extension.
![image](https://user-images.githubusercontent.com/15258962/131895909-ff9ce889-68ee-4588-b075-a7a2c139f3dd.png)

**Comment by MatthewCushing** [comment]
> I will include this screenshot also, as it shows more 'smart' behavior that would be nice to have.
> 
> ![image](https://user-images.githubusercontent.com/5593825/129740788-a1359ddc-6d76-4561-9b79-0f31a975789c.png)
> ![image](https://user-images.githubusercontent.com/5593825/129770817-bbc6e46d-6e48-46ac-8cbe-7e6a66887e92.png)
> ![image](https://user-images.githubusercontent.com/5593825/129740805-c1f08b00-5ad3-4c27-9679-daa79adf49e9.png)
> ![image](https://user-images.githubusercontent.com/5593825/129741044-c1d5bbf9-5e3f-4878-963c-bfb589610518.png)
> 
> This is a more general smart indent line feature, and not actually related to the coloring though. Just putting it out there. I believe it is one of the reasons my extension so popular. I even got emails from teachers about how much it helped their students.

I personally can't live without this feature after the years I've been using it with  your extension.  Like @JustinGrote said, it is the only thing preventing me from moving to VS Code's native version.  Thanks for all the work you've done on your extension and helping getting it into native @CoenraadS and the VSCode team.

**Comment by EryX666** [comment]
I upgraded to the native VSCode bracket pair colorization and when i realized that this feature isn't implemented i turned it off and reinstalled BPC2, I think this feature is one of the best and most helpful features in the extension ecosystem.
I also feel this is important for us developers to say this here, so the implementation of this feature will happen and not get thrown away to the end of the line. there is a real and i suspect large audience of developers who need this feature.

**Comment by hediet** [comment]
Implemented in #133509.

We will iterate on the feature we implemented and differs a little bit from the requested feature.

Mainly, scope lines for all bracket pairs are shown, not only for the active one.
But indentation is not considered and there are no horizontal lines.

**Comment by jjspace** [comment]
@hediet Just looking at the screenshots in that PR I don't personally feel this feature has been implemented and this issue should remain open to track it. At the _very_ least follow up issues should be created so it doesn't get forgotten.

> scope lines for all bracket pairs are shown

This is not how BPC2 worked and I could easily see people thinking this adds too much visual clutter distracting from the point of highlighting the _current_ block/bracket pair you're in. To @CoenraadS's comment "I even got emails from teachers about how much it helped their students". If every block's guide is shown then this can't happen as easily

> there are no horizontal lines

However _more_ importantly, _this_ is the biggest benefit of this feature and the whole reason to use it in my opinion. Just look at the difference it makes in @JustinGrote's comment https://github.com/microsoft/vscode/issues/131001#issuecomment-911940363 or the main screenshots shared by @CoenraadS https://github.com/microsoft/vscode/issues/131001#issuecomment-900328555. I already use `editor.renderIndentGuides` which gives much the same effect as what is shown in the PR so the changes you made would not help me much. However if the horizontal lines are added then I think I (and others) would actually switch away from BPC2

**Comment by JustinGrote** [comment]
@hediet agree with jjspace on both the visual clutter and the horizontal lines, I'm ok with an additive setting as a future iteration, but this is not sufficient to move me from BPC2 (your hard work and efforts are appreciated however!)

**Comment by Nahor** [comment]
And what happens when there are multiple brackets on the same line? e.g. last line of:
![image](https://user-images.githubusercontent.com/1198364/134955131-b53ceb27-5ce7-402f-8b35-3656f56b500c.png)


> Bracket guides can overlap badly formatted text (fixing this is a non-trivial follow up feature and this case should not happen often anyway):

For C/C++, this will happen for macros and goto labels. Both could be quite common:
![image](https://user-images.githubusercontent.com/1198364/134956031-cadd256e-c563-4b07-ac0e-117b3c69af04.png)

**Comment by silkfire** [comment]
I have to say that that looks like a very sloppy and half-arsed implementation. Not even close to the original.

![image](https://user-images.githubusercontent.com/1554615/134970238-5c3a671f-c274-4901-9ff4-30902c021ce3.png)

**Comment by JustinGrote** [comment]
@silkfire as they said they are going to iterate on this, it may just be baby steps and they have to carefully consider performance and stability. I'm willing to give them the benefit of the doubt, they've been clear this is just a first iteration.

**Comment by hediet** [comment]
@JustinGrote thanks for creating the follow-up issue!

I fully understand that the implemented feature currently is a strict subset of the BP2 functionality.
Because we cannot easily take features back once they are generally available, we rather try to start with a small feature-set, incrementally iterate on it and see what the community-feedback is.
