### ISSUE TITLE
Jsdoc type intellisense not working when using custom file extension

### ISSUE THREAD

**Issue by csvenke** [Microsoft/vscode#13100]
- VSCode Version: 1.5.3
- OS Version: Windows 10

In a .js file, intellisense provides correct jsdoc types
![js](https://cloud.githubusercontent.com/assets/9643219/19006509/20ad4dec-8760-11e6-9c36-94f46308d147.JPG)

In a custom extension file associated with javascript, types from jsdoc are not provided
![sj](https://cloud.githubusercontent.com/assets/9643219/19006504/1a07fa0a-8760-11e6-9c01-4af978f2e6a6.JPG)

#### Steps to Reproduce:
1. Create a .sj file
2. In settings.json, set "files.associations": { "*.sj": "javascript" }
3. Create a function with jsdoc parameters with types
4. Call function and check if intellisense provides types

**Comment by waderyan** [comment]
@csvenke thank you for opening this issue. This is a great find! 

@dbaeumer I have recreated this with latest TS and VS Code Insiders. 

Here is the code to copy and paste. 

```javascript
/**
 * @param {string} a
 * @param {string} b
 * @param {string} c
 */
function asd(a, b, c) {}
```

Do you think this is on our end or on TS's end?

**Comment by dbaeumer** [comment]
@waderyan a TS issue since the hover is computed by the tsserver. Is this with 1.6 insider. I thought they fixed this in 2.0.x since we reported this on 1.8.x already.

**Comment by waderyan** [comment]
@dbaeumer this is with 1.6. I'll open an issue on their repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11367
