### ISSUE TITLE
Tooltips/Comments not localized in settings.json for settings from built-in extensions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#13102]
- VSCode Version:1.6 insiders
- OS Version: doesn't matter

All settings related to css, sass, less, html, json and markdown.

This might be because these come from extensions that are built in?

**Comment by mjbvz** [comment]
I've gone through the builtin extensions and opened new issues for each one that is missing setting localization. Please met me know if I missed any
