### ISSUE TITLE
preinstall.js can not check supported Visual Studio Version, when  Visual Studio 2019 not in default path

### ISSUE THREAD

**Issue by z-mirror** [microsoft/vscode#131074]
Does this issue occur when all extensions are disabled?:  yes
this issue occur when install dependencies by yarn

- VS Code Version:  1.60.0
- OS Version:  Windows_NT 10.0.19042

Steps to Reproduce:

1.  install Visual Studio 2019 not in default path (eg: D:\Program Files (x86)\Microsoft Visual Studio\2019 )
2.  run `yarn` in vscode project
```js
$ node build/npm/preinstall.js
*** Invalid C/C++ Compiler Toolchain. Please check https://github.com/microsoft/vscode/wiki/How-to-Contribute.
```
when I see this error messeage, I check my computer environment by `https://github.com/microsoft/vscode/wiki/How-to-Contribute.` ;
It's still not work, so I  read code in preinstall.js;
There is a litter bug in function `hasSupportedVisualStudioVersion`
```js
function hasSupportedVisualStudioVersion() {
	const fs = require('fs');
	const path = require('path');
	// Translated over from
	// https://source.chromium.org/chromium/chromium/src/+/master:build/vs_toolchain.py;l=140-175
	const supportedVersions = ['2019', '2017'];

	const availableVersions = [];
	for (const version of supportedVersions) {
		let vsPath = process.env[`vs${version}_install`];
		if (vsPath && fs.existsSync(vsPath)) {
			availableVersions.push(version);
			break;
		}
		const programFiles86Path = process.env['ProgramFiles(x86)'];
		if (programFiles86Path) {
			vsPath = `${programFiles86Path}/Microsoft Visual Studio/${version}`;
			const vsTypes = ['Enterprise', 'Professional', 'Community', 'Preview', 'BuildTools'];
			if (vsTypes.some(vsType => fs.existsSync(path.join(vsPath, vsType)))) {
				availableVersions.push(version);
				break;
			}
		}
	}
	return availableVersions.length;
}
```
`process.env['ProgramFiles(x86)']`  value is `C:\\Program Files (x86)` in most cases;

if I not install Visual Studio 2019 in default path, preinstall can not check VisualStudio  version;

**Comment by deepak1556** [comment]
This requires wiki improvement and probably better error from the preinstall script, if vs is not installed in the default drive then we expect users to set an env variable `vs2019_install` or `vs2017_install` indicating the path of installation.

**Comment by rzhao271** [comment]
Updated https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites

**Comment by rzhao271** [comment]
Closing since docs have been updated
