### ISSUE TITLE
Doc thumbnail disappears after a long sleep

### ISSUE THREAD

**Issue by agonzalezro** [microsoft/vscode#131060]
Does this issue occur when all extensions are disabled?: Not sure, if I disable extensions for a long period I can't use the editor.

- VS Code Version: 1.59.0-insider
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Minimize a VSCode instance
2. Keep it on that state for a long time (I think the trigger might be a long sleep, but I am not sure)
3. You will not see the thumbnails, just the small icon (see screenshots).

Adding to point 2: is it possible that this happens when I have a new update? Because I think everytime this happen I will have the option "Restart to Update". I had open this tab to create the ticket for a week and it didn't happen until today.

Screenshot of how it should be:

<img width="66" alt="Screenshot 2021-08-18 at 09 03 51" src="https://user-images.githubusercontent.com/205176/129853732-5ba6fd78-aa61-47dc-8133-a215f13a51f8.png">

Screenshot of what I am describing as a bug:

<img width="63" alt="Screenshot 2021-08-18 at 09 03 33" src="https://user-images.githubusercontent.com/205176/129853942-60ef75b0-dade-4bd4-84be-70c8b7b7a8f9.png">

Screenshot of what happens if I open & minimize again one of the editors:

<img width="85" alt="Screenshot 2021-08-18 at 09 03 41" src="https://user-images.githubusercontent.com/205176/129853985-8b5fd547-c385-4a7c-b03e-725e6d3bd0b7.png">

Thanks!

**Comment by isidorn** [comment]
Feels like an electron issue, for now assigning @rzhao271

**Comment by rzhao271** [comment]
@agonzalezro does the issue still occur for you on the latest Insiders?

**Comment by agonzalezro** [comment]
Yes, it still happens.

Sorry I didn't comment earlier but I wanted to reproduce the error again and I was able to do it today:

<img width="85" alt="Screenshot 2021-10-08 at 11 00 04" src="https://user-images.githubusercontent.com/205176/136528857-1ead3e5e-2985-4195-b398-5503ef0a1094.png">

**Comment by deepak1556** [comment]
I was able to repro this with other apps after waking from sleep, looks like this is known issue in the community https://discussions.apple.com/thread/252130664. Closing as this not something particular to vscode.
