### ISSUE TITLE
Can't install VSIX into VS Code Insiders

### ISSUE THREAD

**Issue by DustinCampbell** [Microsoft/vscode#13101]
- VSCode Version: 1.6.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Download latest C# extension beta release: https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.5-beta2/csharp-1.5.0-beta2.vsix
2. In VS Code, use File->Open to open the VSIX.

**Expected Result**: Extension installs

**Actual Result**:
![image](https://cloud.githubusercontent.com/assets/116161/19007405/c0968342-8719-11e6-93f9-d465f4c20a56.png)

**Comment by gregvanl** [comment]
This means of installing a VS Code extension is deprecated. There is a new Extension View command "Install from VSIX..." to install an extension from a .vsix.
There is also the command line "--install-extension" switch.

**Comment by DustinCampbell** [comment]
Thanks @gregvanl! A bit of feedback -- I found the "Install from VSIX..." command pretty difficult to find. I actually looked around for it for quite awhile, even after you mentioned it.

**Comment by gregvanl** [comment]
@DustinCampbell Agreed, I just entered https://github.com/Microsoft/vscode/issues/13174 to make sure it is in the Command Palette.
I'm also in the process of updating the docs.

**Comment by DustinCampbell** [comment]
Thanks!

**Comment by gregvanl** [comment]
I'm going to reopen this issue so it gets more visibility. I'm not sure of the reasons to deprecate the File > Open. Adding "Install from VSIX..." is nice but removing the previous way can be confusing. 
It would be better to deprecate File > Open at a later release after warning users.

**Comment by joaomoreno** [comment]
Let's not go back.

I will make sure #13174 is done asap, so people can still find it.
