### ISSUE TITLE
Feature Request: Color mismatched brackets

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#131033]
The inbuilt coloring works really well, however doesn't color mismatched brackets. A nice red color would indicate that it is unmatched and easy to find.

![image](https://user-images.githubusercontent.com/5593825/129789417-933e1fd4-7742-4238-be36-0d39d299728a.png)
vs
![image](https://user-images.githubusercontent.com/5593825/129789448-066e6e42-6ba1-4a77-81a3-9af766eaf47c.png)

**Comment by hediet** [comment]
Implemented in 91818ab.

**Comment by CoenraadS** [comment]
That was quick, thanks!
