### ISSUE TITLE
Double clicking Release Notes preview mode tab closes editor and goes to website

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13105]
- VSCode Version:1.6.0 insiders
- OS Version:Windows 10

Steps to Reproduce:
1. Follow test plan to enable in product release notes in insiders https://github.com/Microsoft/vscode/issues/12520
2 Help > Release Notes
3. The release notes are shown in product as a preview mode editor.
4. Double click the tab header to try and persist the editor

Editor disappears and a browser window is opened to the insiders release notes page.

**Comment by joaomoreno** [comment]
Cherry picked to `release/1.6`

**Comment by joaomoreno** [comment]
Rolled back cherry pick. Removing it from candidates. Can't merge this in without merging #12982 which wasn't properly smoke tested.

**Comment by chrmarti** [comment]
Removing candidate label and updating milestone to October.
