### ISSUE TITLE
git extension: if "git.untrackedChanges" is "hidden" ignore untracked files in git status

### ISSUE THREAD

**Issue by thekorn** [microsoft/vscode#131020]
Issue Type: <b>Bug</b>

`Repository.getStatus()` always runs `git status -z -u` even if the "git.untrackedChanges" config is set to "hidden". later on in `Repository.updateModelState()` the untracked files are then filtered out

As an optimisation for repositories with a huge number of untracked files `Repository.getStatus()` should run `git status -z -uno` in this case

This is a bug, and not a feature request as `git status -z -u`  makes not much sense without a mode anyways - if it is intentional to not provide a mode and use the default mode `git status -z` would just be the same

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.11.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 1688)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.74GB (47.54GB free)|
|Process Argv|-n . --crash-reporter-id d0c804c3-bc25-4308-8c30-c703355b6832|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
rest-client|hum|0.24.5
mongodb-vscode|mon|0.6.10
vscode-docker|ms-|1.16.0
vscode-language-pack-de|MS-|1.59.3
python|ms-|2021.8.1105858891
remote-containers|ms-|0.191.1
hexeditor|ms-|1.8.2
vetur|oct|0.34.1
java|red|0.80.0
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
rust|rus|0.7.8
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.2
vscode-maven|vsc|0.32.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30353136
javagetstartedt:30351793

```

</details>

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/commit/29f9e514449e6332432fd96c1b8d8ea92c7c5ca9.
