### ISSUE TITLE
Allow ability to provide custom duration for Notebook cell execution tasks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131052]
Today when the cell execution task API accepts start time & end times.
However in Jupyter, the start & end times are not accurately captured by the extension host.
We do have the ability these values from the kernel.

Is it possible to provide an API where by the extension can provide the elapsed time, instead of end time.
I.e. 
* We provide the start time (let the timer start ticking over)
* When the task is over we provide the elapsed time or a more accurate start & end times.

One way to look at this is, assume the execution is taking place on a remote machine, at this point the accurate times can only be returned by the remote server.

Here's the original Jupyter issue https://github.com/microsoft/vscode-jupyter/issues/7154

Note: In a personal extension of mine, I have the same requirement, as the execution is taking place in a separate process, hence the duration calculated from (end time - start time) is not an accurate representation  (as it includes time taken to send messages across the processes, & other vscode processing, etc)

**Comment by DonJayamanne** [comment]
@roblourens /cc

**Comment by roblourens** [comment]
If you have the correct duration, you could send a "fake" end time, I don't see a problem with that.
