### ISSUE TITLE
Escaping pattern highlighting fails

### ISSUE THREAD

**Issue by btrautmann** [microsoft/vscode#131017]
Issue Type: <b>Bug</b>

When highlighting a pattern (Using CTRL+G when using Intellij hotkeys, I'm not sure of the default VSCode hotkey), pressing escape is not exiting the pattern highlight, leaving multiple cursors in the editor. To escape it, you must click somewhere inside the editor.

Also, when doing this multiple times, i.e highlighting, escaping and then attempting to highlight another pattern, sometimes the second one will not work, i.e I cannot highlight the pattern (it is just stuck on the first instance) --  I need to again click in the editor and then begin highlighting again.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv|-psn_0_73746 --crash-reporter-id 4f4793be-2862-4f8b-8e51-1c25ca7bc541|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
flutterment|Bet|0.0.6
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
bloc|Fel|5.7.0
intellij-idea-keybindings|k--|1.4.5
indent-rainbow|ode|7.5.0
vsfire|tob|1.4.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by btrautmann** [comment]
https://user-images.githubusercontent.com/8343465/129766106-4dbf90f2-3efc-47a5-8bd6-91fbd7a2f1b3.mov

In the above video, I show highlighting the pattern. After all are highlighted, I press ESC which should bring it to only one cursor again, but this is not the case. Finally, clicking in the editor does so.

**Comment by IllusionMH** [comment]
/needsMoreInfo

I think it's `editor.action.addSelectionToNextFindMatch` ([extension contributions](https://github.com/kasecato/vscode-intellij-idea-keybindings/blob/9cffce1b54ffa101a59bdfb9251ed49a418e50ab/package.json#L365-L371)) which is <kbd>Ctrl/Cmd</kbd>+<kbd>D</kbd> in VS Code and after <kbd>Esc</kbd> only one cursor is left.

Is it reproducible with all extensions and keymaps disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by btrautmann** [comment]
I was able to confirm that this does _not_ happen with all extensions disabled. I'll file something with the intellij key bindings developer, thank you!
