### ISSUE TITLE
Allow to detect encoding from file content (e.g. XML)

### ISSUE THREAD

**Issue by LinoBarreca** [microsoft/vscode#131070]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. open an xml file with an encoding different than UTF-8 and in which the prolog specifies correctly that the encoding is, for example "ISO-8859-1"
2. in the status bar it's opened as utf-8 encoding and edits to the file are in UTF-8.

This violates the XML specifications.
I already saw that there was a bug already reported which has been closed as "we don't have time for this" but this has high priority and must be solved as soon as possible because you mess with important user files.

**Comment by LinoBarreca** [comment]
In this case we don't have a problems as it's just a comment
![image](https://user-images.githubusercontent.com/897723/129867087-6c8189f4-3b5d-4f35-9a13-5a6961611b4f.png)
but xml files are used for localization and the encoding IS important and must be respected

**Comment by gjsjohnmurray** [comment]
Please link to the issue you found.

**Comment by LinoBarreca** [comment]
#1316

**Comment by gjsjohnmurray** [comment]
pinging @bpasero who responded on that issue.

**Comment by LinoBarreca** [comment]
sure. even if I disagree with his former "feature request" classification.
you either respect a standard or you don't...and in this case you don't.

If the user doesn't know that vscode messes with encoding he risks damaging important files.
A feature request would be to warn the user like "hey, I have an unprintable character on line 12665, did you open the file with the correct encoding?" when you open a file without an explicit encoding header.

...but in this case there is a standard, the encoding IS specified and you don't open the file correctly.
from a dev to a dev this is a bug (and even an important one) there's no way to classify it as a "feature request"

**Comment by LinoBarreca** [comment]
this is just ridiculous.

**Comment by LinoBarreca** [comment]
@ujay68 @fortinmike @odinmillion @mortenseifert @rubenprins
