### ISSUE TITLE
Add system file icons for popular file types

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#131057]
As I added more [file associations](https://github.com/microsoft/vscode/pull/131048) I noticed that some frequently used file types only get the default icon: https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L141-L158

- rust
- toml
- lua
- dart
- clojure
- ipynb
- _maybe others?_

Might be worth filling them in, if it's no major work.

**Comment by misolori** [comment]
We decided to keep the list to the top most used files at the time, as each file icon has to have a icns + ico file, which adds more mbs. We've previously closed requests for adding more because of this but will wait to see what @joaomoreno thinks.

**Comment by misolori** [comment]
One clarifying question: are you proposing to add that list of file types to show our default file icon or to show their custom file icon individually?

**Comment by digitarald** [comment]
Thanks for the background. Might be not worth the effort though, or only for specific filetypes that we are actively investing in, like ipynb. I don't have any sense if this helps users. I'd leave it to the type owners to speak up then and open issues for specific types.
