### ISSUE TITLE
Extensions: Be able to differentiate binary files that are opened as plaintext files from "real" plaintext files

### ISSUE THREAD

**Issue by damien-urruty-sonarsource** [microsoft/vscode#131076]
When users open binary files, they are prompted with this message : "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. _Do you want to open it anyway ?_". If the user chooses to open it anyway, the binary file is then opened as a `plaintext` file.

Plain text files is something we are interested in in our [extension](https://github.com/SonarSource/sonarlint-vscode), but we are not interested in binary files. 

The problem today is that from an extension point of view, both (forced open) binary files and true plain text files will be seen as `plaintext`, and we have no easy way to differentiate between them. 

I think it would make more sense to have a `binary` file type and not rely on the `plaintext` type in this situation.

**Comment by bpasero** [comment]
Hm yeah, fair. Let me investigate this...

**Comment by bpasero** [comment]
**Verification:**
* open a binary file in vscode (e.g. a zip file)
* from the editor select "Do you want to open it anyway"
* pick the "Text Editor" (in case you get asked and e.g. have HEX editor installed)
* the language indicator in the status bar should read "Binary"

**Comment by damien-urruty-sonarsource** [comment]
Thanks for the reactivity!
