### ISSUE TITLE
VSCode window always opens between laptop monitor and extension monitor

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#131098]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows 10 1909

Description:
I have a laptop with extension monitor setup. The laptop is a Dell and is currently set to its native res of: 3840x2400. My extension monitor is a Dell set at its native res of: 1920x1200.

I'm also using 3 virtual desktops because I have certain apps that always need to be open and I just switch to the appropriate desktop when needed (common usage).

The problem is after maximizing vscode on my extension monitor and closing it, vscode doesn't remember that info. So when I launch vscode again, it appears in between the laptop monitor and the extension monitor. When I click on the title bar to try to move it to either monitor, it doesn't budge. The only solution is to use win+shift-arrow to get it out of that limbo state and move it to either monitor. I've tried launching, moving it to either monitor, maximizing, then closing. When I launch again, it always starts in between both monitors. It's a rather annoying issue.

Steps to Reproduce:

The steps, I guess will vary depending on res, monitors, and virtual desktop

1. Add an extension monitor to laptop
2. Setup so that desktop is display 1, and ext monitor is display 2, then move display 2 on top of display 1 in control panel. Now you should be able to drag a window from laptop screen up and into ext monitor.
3. Create 3 virtual desktops (I'm not sure this even matters)
4. Open vscode and move it to ext monitor, then maximize.
5. Close vscode, then launch it again.
6. Right here is when the window doesn't open in ext monitor. It opens in between both and you can't move the window unless you use win+shift-arrow

**Comment by bpasero** [comment]
Probably the same as https://github.com/microsoft/vscode/issues/115768

**Comment by u84six** [comment]
Yes, I did leave out that last piece of info about scale. Monitor 1 (the laptop) is scaled to 250%, otherwise I can't see a thing because everything is too small. So I can't really scale it down.
