### ISSUE TITLE
Inlay hints messed up syntax highlighting

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#131021]
On Mac, I switched to another small window while VS Code was loading its extensions. I may have also been typing before the hints got rendered.
I saw sudden blurs of grey and then noticed the hints got rendered, but at weird places.

<img width="479" alt="Screen Shot 2021-08-17 at 10 39 19 AM" src="https://user-images.githubusercontent.com/7199958/129774661-3565004e-9239-40b4-9750-c2bd3d985674.png">

**Comment by mjbvz** [comment]
Do you remember which TS version was active in the workspace?

**Comment by rzhao271** [comment]
It seems to be 4.5.0-dev.20210810

**Comment by mjbvz** [comment]
Ok, let me know if you see this using the 4.4.1-RC or the latest TS version (0817)
