### ISSUE TITLE
Authentication decryption error

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#131019]
signature changed in latest snap of recovery build/insiders. This causes users to have to re-log in to everything on Windows.

**Comment by IllusionMH** [comment]
Happened second Insiders update in a row

Version: 1.60.0-insider (user setup)
Commit: af770c2dc85ef6835197a8bd7eb416fe0a022c44
Date: 2021-08-17T19:06:19.805Z

Both extensions have same error `Getting token failed: Error: Decryption failed`

**Comment by TylerLeonhardt** [comment]
Fixed in latest insiders and latest recovery build

**Comment by TylerLeonhardt** [comment]
Verification steps:
* Be logged in in current stable
* Upgrade to recovery build
* be still logged in

**Comment by IllusionMH** [comment]
Do I understand correctly that Insiders build that will be tomorrow morning (2021-08-18) should no longer log out users?

**Comment by TylerLeonhardt** [comment]
@IllusionMH I released an insiders today (~3hrs ago) with the fix. If you logged in again with the bad build from this morning, then you'll have to re-log in with the good build.

In short, yes. If you log in with the latest insiders right now, you will not be forced to log in again tomorrow.

**Comment by roblourens** [comment]
using the windows build or the snap?

**Comment by TylerLeonhardt** [comment]
This issue only applies to the windows build.

**Comment by roblourens** [comment]
> signature changed in latest snap of recovery build/insiders

Verified on windows, you aren't talking about the snap package though?

**Comment by TylerLeonhardt** [comment]
Oh sorry... "snap" in that case is like "snap a build" or like "specific build" or like "fire off a build" it has nothing to do with our snap(craft) build. lol

**Comment by IllusionMH** [comment]
Worked as expected in during update from
Commit: af770c2dc85ef6835197a8bd7eb416fe0a022c44
Date: 2021-08-17T19:06:19.805Z
to
Commit: 0214d59846f265d9e50f53b61e2267407d81cbfb
Date: 2021-08-18T05:14:14.284Z


OS: Windows_NT x64 10.0.19041
