### ISSUE TITLE
Webview view does not position itself correctly.

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#131005]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows 10 Prof 64

If expand the treeview the opened webview is not positioned correctly 
Steps to Reproduce:

1. Sidebar  with
2. Treeview (top) - Webview view (middle) - Treeview (bottom)
![WebviewViewPosition](https://user-images.githubusercontent.com/32703052/129753222-56fae683-50f4-49d8-873b-c707d5940cff.gif)

**Comment by a-stewart** [comment]
I think this is the same issue as https://github.com/microsoft/vscode/issues/130353

I left a comment there with what I think it the issue causing this.
