### ISSUE TITLE
[request] Open Terminal tabs as siblings to "Editors"

### ISSUE THREAD

**Issue by agreeff** [microsoft/vscode#131075]
First off, greetings.. 😁 ..and a massive thank you for VSCode, it literally is my daily driver for practically everything code related, across three platforms. Doesn't get much better than this.. Unless, of course, you would consider my suggestion.

Just for clarification:

* by "Terminal tabs", I'm referring to each individual terminal instance, as currently listed in the relevant top-corner dropdown list in the "Terminal" tab, found in the current bottom panel.
* by "Editors", I'm referring to each main tab with *something* opened, like a file, a Git diff, the "Settings" view; effectively anything that could/would be listed under the "Open Editors" list of the "Explorer" pane.

With that out of the way, what I would love to see, is the ability to open inside a new tab as a direct sibling of currently opened Editors..

There isn't really much more to my request though, but to list some of the benefits I see here:

* Terminal tabs could be arranged alongside any Editor tab, simplifying and extending panel layout options.
* The terminal "bell" could flash the "Terminal Editor" tab title, making it super easy to spot, as well as keeping consistency with 99% of the tabbed terminal emulators out in the wild.
* You could (*possibly..?*) end up with a fair amount less code to maintain.. 🍻 
* Many devs would love you just that little bit more..
* Some genius dev(s) might make an extension that uses the Editor's existing text rendering to implement a terminal... (*this is just wishful speculation at the moment, but it **would** be seriously awesome! imagine setting terminal fonts to match file editors? with one setting!?* 😁)
* ..plus many more that I haven't thought of yet

Please note: I have searched high and low for an extension that does this, but haven't found anything yet.. I also haven't tried creating my own extension yet (though that is on my todo list). However, since the terminal handling feels like a core part of VSCode, I thought it might be best to make this request first, see the outcome, and take it from there.

---

Edit: I believe this would also solve the unlying issues in #129956 and #130860. Might even lay down the groundwork to cater for things like #130432.. I only looked through the first 3 pages of issues that came up from a `terminal tabs` issue search, so there's possibly more like this.

**Comment by gjsjohnmurray** [comment]
Have you yet discovered that with the arrival of 1.59 terminals can now be dragged from the Panel into the Editor area?

https://code.visualstudio.com/updates/v1_59#_drag-and-drop-terminals-across-windows

**Comment by agreeff** [comment]
> Have you yet discovered that with the arrival of 1.59 terminals can now be dragged from the Panel into the Editor area?

Well well, I did actually miss that one.. Thanks. That is quite literally how I had imagined this working...

If there's an option to make them open there by default, then my feature request is already covered. 🤦🏼‍♂️ I just found the `terminal.integrated.defaultLocation` setting, changed it from `view` to `editor`, but that doesn't seem to affect the behaviour. Should I perhaps close off my feature request and open a bug report instead then? 🤔

**Comment by agreeff** [comment]
Alrighty, so I can clearly see that some other awesome people were way ahead of me here, and what I was (secretly, until recently) hoping for is already in the works! Thank you so much..

I was using <kbd>ctrl</kbd>+<kbd>\`</kbd> to launch a terminal, so I decided to look at the active keyboard shortcuts, in which I found the following:

Just for clarification:

* `workbench.action.terminal.toggleTerminal` is set to <kbd>ctrl</kbd>+<kbd>\`</kbd>
* `workbench.action.terminal.new` is set to <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\`</kbd>

In combination with the `terminal.integrated.defaultLocation` setting I mentioned, using <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\`</kbd> **does** actually open a new terminal in an Editor tab. 👍🏼 

In the meantime, I'm simply going to switch these bindings in my config. If there are any open issues for this, perhaps it would be helpful to reference them below from this issue for a little context? Either way, I believe this particular issue doesn't need to stay open any longer then.

Thanks @gjsjohnmurray for sending me down *that* little rabbithole, my day just got that little bit better. 😁

**Comment by agreeff** [comment]
That makes perfect sense. Possibly because most people would *instictively think* of <kbd>ctrl</kbd>+<kbd>\`</kbd> as a sort of "get me into a terminal", as opposed to "toggle the pane that contains a terminal"...? 🤔 

That said, going by the explicit names of the keyboard shortcuts, there really isn't any space for confusion.. The shortcut I *needed* for my workflow is specifically the "Terminal: Create New Integrated Terminal" command, whereas the easiest way to do this has always been the "View: Toggle Terminal" command, simply due to a shorter shortcut.

At the end of the day, I guess things like this are all "tomato, tomato" anyway..
