### ISSUE TITLE
Custom task status is 'error' and there is no 

### ISSUE THREAD

**Issue by ClaudeZhao** [microsoft/vscode#131141]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.57 and higher
- OS Version: Win10

Steps to Reproduce:

Follow the vs code sample: [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample) to create a custom task. Then run the task, you can see the task / terminal status is 'task has error', but actually the task runs without any problem. This issue doesn't exist before 1.56 because the status was not displayed.
![vscodetask](https://user-images.githubusercontent.com/16837065/129989838-d488eb72-3e77-4fd8-9824-ba41b3b1606b.png)

I didn't find any APIs or commands to change the task status, and I also tried problem matcher to filter the output of the task, still not work.
I also submit a question in [stackoverflow](https://stackoverflow.com/questions/68810877/how-to-change-a-vs-code-tasks-status-vs-code-extension-development/68811217?noredirect=1#comment121621482_68811217), but didn't find out any solution. Could you help give some guidance?

Thanks!

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Which of the tasks from the sample shows this? Are you making sure to fire your close emitter with `0` to indicate the "task process" has exited without an error?

https://github.com/microsoft/vscode-extension-samples/blob/0839a5dd8e7c3df07428352b0a701fbd323676e0/task-provider-sample/src/customTaskProvider.ts#L129-L130

**Comment by ClaudeZhao** [comment]
> 
> 
> I'm not able to reproduce this issue. Which of the tasks from the sample shows this? Are you making sure to fire your close emitter with `0` to indicate the "task process" has exited without an error?
> 
> https://github.com/microsoft/vscode-extension-samples/blob/0839a5dd8e7c3df07428352b0a701fbd323676e0/task-provider-sample/src/customTaskProvider.ts#L129-L130

You are totally right! The sample I used a little old and I didn't pass number to fire(). Now it works.
Thanks a lot! I think this ticket could be close.
