### ISSUE TITLE
Windows filepaths are lowercased in language server requests

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#131121]
This reproduces with VS Code 1.59 on a Windows machine (Windows_NT x64 10.0.19042).

When I make a directory with an uppercase path element (something like `C:\work\Go`), VS Code will send `c:\work\go` in `didOpen` and other language server requests. ​The Go language server has handling for the lowercase drive letter, but it expects other elements of the path to match their case on disk.

When  I `cd` into the directory with an uppercase path (`C:\work\Go`) and start VS Code with `code .` - it will send the lowercase path. It's possible to work around this by running `code C:\work\Go`.

**Comment by dbaeumer** [comment]
This is not specific to language servers. This is what is provided by the VS Code API. Ben, Joh can you explain why this is the case.

I got hit by this in the ESLint server as well since some ESLint plugins expected a correct casing. I use the realPath API in node to get the real casing from disk.

**Comment by bpasero** [comment]
Needs a minimal extension from `yo code` (https://github.com/Microsoft/vscode-generator-code) for me to understand the context where I can see a file path all being lowercased and not how it was opened in the editor.

To my knowledge and looking at the `URI` code, I only know that we normalise the drive letter to lowercase always:

https://github.com/microsoft/vscode/blob/77905c850e170eab00cac5ca190c7b1fe5ad43ba/src/vs/base/common/uri.ts#L595-L595

Is this only about the drive letter or more?

**Comment by dbaeumer** [comment]
To clarify my comment: In ESLint I struggled with renames that change casing which is not reflected in the URI. I did struggle with lower case drive letter as well. But I never encounter the path being all lower case

**Comment by bpasero** [comment]
@stamblerre could that happen here? a file was opened with one case and later renamed?

**Comment by bpasero** [comment]
@stamblerre ok good, can you share a setup for me to print these paths and debug it? ideally minimal. Thanks!

**Comment by bpasero** [comment]
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
