### ISSUE TITLE
Git "Clean All" feature should display a confirmation dialog

### ISSUE THREAD

**Issue by marceloemanoel** [Microsoft/vscode#13119]
The Git "Clean All" action is destructive and unlike other actions, can't be undone. The user might end up loosing his/her work by firing it without previous knowledge of this or even by accident. I suggest that when the user click on it, the editor display a confirmation dialog allowing him/her to cancel the action if done by mistake or if unsure of the consequences.

- VSCode Version: 1.5.3
- OS Version: OS X 10.11.6

**Comment by joaomoreno** [comment]
Something like this?

![image](https://cloud.githubusercontent.com/assets/22350/19065539/68d0009a-8a14-11e6-8d35-e932573e80be.png)
