### ISSUE TITLE
activating terminal profile keeps closing combo boxes

### ISSUE THREAD

**Issue by joao-aguirre** [microsoft/vscode#131111]
Issue Type: <b>Bug</b>

I know it is a little weird, but when I define a terminal profile using:

```
"terminal.integrated.profiles.windows": {
        "cmder": {
            "path": "C:/WINDOWS/System32/cmd.exe",
            "args": ["/K", "C:/tools/cmdermini/vendor/init.bat"]
        }
    },`
```
and later on use this profile as default by:

```
"terminal.integrated.defaultProfile.windows": "cmder",
```

Then, whenever I open a combo box (lithe the bombo box at the Output window, allowing me to choose which output to check, the combo box gets closed even if I am still navigating it.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.27GB free)|
|Process Argv|--crash-reporter-id f55e9b6a-a451-44ae-9a30-50322c5bd48b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by meganrogge** [comment]
please include a gif of this happening with screencast mode enabled

**Comment by meganrogge** [comment]
also what does that script you are passing in as an argument do?

**Comment by joao-aguirre** [comment]
> please include a gif of this happening with screencast mode enabled

Here it follows:

![cmder-terminal](https://user-images.githubusercontent.com/11059665/130115006-d087e2bb-1cbb-4b8b-a0c4-2231894b11d4.gif)

**Comment by joao-aguirre** [comment]
> also what does that script you are passing in as an argument do?

I haven't checked, I use `cmder` as my terminal tool and I have found these instructions on VSCode documentation [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows).

Here follows the file: [init.txt](https://github.com/microsoft/vscode/files/7016568/init.txt)

**Comment by meganrogge** [comment]
strange. @Tyriar, thoughts?

**Comment by meganrogge** [comment]
Thanks for the gif and info. I still can't reproduce it.

**Comment by Tyriar** [comment]
The cause is all the panel actions are getting rebuilt when the terminal setting changes

![recording (80)](https://user-images.githubusercontent.com/2193314/132344027-e3026264-edc0-4cd6-9127-975581d6248a.gif)

@sbatten is this by design that changing an action item on one panel would rebuild all actions on all other panels?

**Comment by sbatten** [comment]
if a context that affects the actions in the visible panel changes, then yes the whole thing is rebuilt. could you specify what context changes? "changing an action item on one panel" << which panel in this case?

**Comment by Tyriar** [comment]
We refresh the terminal config registrations so the settings editor auto complete gets updated:

https://github.com/Microsoft/vscode/blob/44129daac8b9f17ffdf741206b7f603ea082ed16/src/vs/platform/terminal/common/terminalPlatformConfiguration.ts#L393-L401

Plus re-create the commands:

https://github.com/Microsoft/vscode/blob/08069da0075f86f8feafcaa249021080bcfc56a2/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L2015-L2015

Not aware of context key value changes

**Comment by meganrogge** [comment]
@sbatten let us know if you need anything from us

**Comment by sbatten** [comment]
After investigation, it seems this is caused by the configuration updates here which eventually trigger a whole slew of contex tkey changes https://github.com/microsoft/vscode/blob/9f7309348f4139404cc1e339216a017bc49884f2/src/vs/workbench/services/configuration/browser/configurationService.ts#L668

**Comment by Tyriar** [comment]
@sandy081 this comes back to a more performant option for updating config schemas https://github.com/microsoft/vscode/issues/120940

**Comment by sandy081** [comment]
I see, will try to add this in this milestone.
