### ISSUE TITLE
Was bug #118267 filed upstream with Apple?

### ISSUE THREAD

**Issue by vtjnash** [microsoft/vscode#131110]
(opening a new issue for this question since the old issue is locked)

Did https://github.com/microsoft/vscode/issues/118267#issuecomment-797016213 get filed with Apple in Feedback Assistant <https://developer.apple.com/bug-reporting/>? I will keep the work-around for this when I make a libuv release with that feature, but also would be helpful to file an upstream issue and know the FB# for it.

**Comment by deepak1556** [comment]
Hi @vtjnash , nope it was not. I will file one this week and update here.

**Comment by deepak1556** [comment]
Filed FB9578526
