### ISSUE TITLE
That is not possible to copy information from Problems window

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#13115]
The Problems window does not allow to copy information about detected problems:

![image](https://cloud.githubusercontent.com/assets/14539/19013409/1c10d40a-87d0-11e6-958c-200a162ddff9.png)

- VSCode Version: 1.6.0-insider (1.6.0-insider)
- OS Version: Mac OS X 10.11.6 (15G1004)

Steps to Reproduce:

1. Open a source code - here C# code - with any kind of error or warning 
2. Open View > Problems
3. Try to select with mouse or using keyboard
4. Try to copy selected text with mouse or keyboard

Expected:
I should be able to copy selected warning/error text in any way (keyboard or mouse)

Actual:
I'm not able to copy selected warning/error text in any way

That's not a problem with my own code, but sometimes I have to pass just the information about the problem to other people.

Thanks!

**Comment by sandy081** [comment]
Implemented a context menu with Copy option that copies the problem details `file, severity, message, at, source`

![image](https://cloud.githubusercontent.com/assets/10746682/19116038/6aa93232-8b14-11e6-870b-5c1c95b1658c.png)
