### ISSUE TITLE
`scmProvider` context key is not visible from everywhere

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#131172]
Not sure what's going on here. I want to use the value of the `scmProvider` context in `view/item/context` menu items (https://github.com/microsoft/vscode-pull-request-github/pull/2920), but that context key doesn't exist on those items. It does exist in other menus such as `scm/title` and `remoteHub/pullRequest`. 

Interestingly, the `scm.providerCount` does exist on `view/item/context` menu items.

**Comment by gjsjohnmurray** [comment]
Looks like it's one of the context keys that only exists for SCMRepositoryMenus

https://github.com/microsoft/vscode/blob/6fea665f6809444e3d664aef59f8fd6afc4fe8b1/src/vs/workbench/contrib/scm/browser/menus.ts#L176-L180

I think these are intended for controlling visibility of contributions to SCM view menus.

**Comment by alexr00** [comment]
Interesting. Well, that makes sense I suppose. @eamodio is there a way I can tell if the scm provider is remote hub, irrespective of these keys?

**Comment by eamodio** [comment]
Not that I know of -- but why are you interested in the SCM provider? If these actions are on a resource, you could check the resource uri -- so look for the `vscode-vfs` scheme, and if you only want GitHub ones, check that the authority contains/starts with `github`.

**Comment by alexr00** [comment]
I don't think I can get the scheme on a resource from `when`, and the `context` currently set on tree items is complex enough without adding to it. Maybe it's time to add a new `resourceScheme` context value to tree item menus...

**Comment by gjsjohnmurray** [comment]
> 
> 
> I don't think I can get the scheme on a resource from `when`, and the `context` currently set on tree items is complex enough without adding to it. Maybe it's time to add a new `resourceScheme` context value to tree item menus...

@alexr00 I'm not clear why the existing `resourceScheme` (see [here](https://code.visualstudio.com/api/references/when-clause-contexts#available-contexts)) doesn't meet your need.

**Comment by alexr00** [comment]
@gjsjohnmurray I thought that was restricted only to the explorer view. But I can see now that it's available in other views. Looks like we're all set then!

**Comment by eamodio** [comment]
Going to close this as as-designed 😄
