### ISSUE TITLE
Context Menu 'Open in Integrated terminal' not honouring default profile of git bash and instead opens in powershell

### ISSUE THREAD

**Issue by aMadReason** [microsoft/vscode#131112]
Issue Type: <b>Bug</b>

windows 10 run vscode insiders build
Set default terminal profile to Git Bash
Use Explorer and right click on a folder and select 'Open in Integrated Terminal'

I would expect the default profile to run but it always opens in powershell even though using the + button in terminal opens git bash.

VS Code version: Code - Insiders 1.60.0-insider (0214d59846f265d9e50f53b61e2267407d81cbfb, 2021-08-18T05:14:14.284Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.13GB free)|
|Process Argv|--crash-reporter-id db8561bc-6afc-474e-9cb1-5ab551945242|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
vscode-eslint|dba|2.1.23
vscode-faker|dee|1.5.0
vscode-npm-script|eg2|0.3.22
gc-excelviewer|Gra|3.0.42
vscode-styled-components|jpo|1.6.6
python|ms-|2021.8.1105858891
js-debug-companion|ms-|1.0.15
vsliveshare|ms-|1.0.4673
syncing|non|3.1.0
vetur|oct|0.34.1
polacode|pnp|0.3.4
vscode-open|san|0.1.0
markdown-preview-enhanced|shd|0.5.22
code-spell-checker|str|1.10.2
write-good-linter|tra|0.1.4
vscodeintellicode|Vis|1.2.14
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824cf:30353184
javagetstartedt:30350119

```

</details>

**Comment by max-hk** [comment]
@Tyriar Is there any expected timeline when this bug will be resolved?

It is very annoying for me.

**Comment by Vidfinnx** [comment]
Only workaround i found  (after hours of thread reading and trying to edit settings.json with no success in getting it to stick) was downgrading to 1.59 where it functions perfectly, i didn't even know auto upgrades were a thing for vscode, all i know is i was working on a project just fine then later in the afternoon reopened vscode and this extremely annoying thing was happening. I am scared to death of auto updates and to update vscode period because it does this on the "stable build" directly from the site. I have since now disabled auto updates.
