### ISSUE TITLE
[Ctrl]+[`] to launch external terminal and attach a terminal session to it.

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#131188]
Integrated terminal is great. 

However there are VSCoders favor to use their own external terminal, e.g. Windows Terminal, iTerm2, etc.

It'd be nice to be able to configure VSCode to launch external terminal when hitting **[Ctrl] + [`]**, and attach a terminal session to it.

My understanding is VSCode Server hosts the sessions, independent of the running state of VSCode client. Thus I feel this feature should be feasible technically.

I'd imagine some command like `ssh <user@host> -- vscode-server terminal-session [--attach | --new]` should be I need to pass to my favorite terminal emulator.

Thanks for all the hard work, VSCode team.

**Comment by Tyriar** [comment]
Only VS Code can talk to the "server" component right now which if you're interested is the pty host process here:

![image](https://user-images.githubusercontent.com/2193314/130100019-8575700c-819e-4133-b63d-4d67e20f70eb.png)

AFAICT the only benefit you would get from this is the ability to easily open the active folder in your terminal which can already be accomplished by the `Open New External Terminal` command (ctrl+shift+c) and for anything beyond that an extension could add the integration you're after. I publish a Windows Terminal integration extension which gives some more options: https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal

Also FYI you can [rebind](https://code.visualstudio.com/docs/getstarted/keybindings) ctrl+` if you want to whatever command you like, for example:

```json
{
  "key": "ctrl+`",
  "command": "workbench.action.terminal.openNativeConsole",
  "when": "!isWeb"
}
```

**Comment by tigerinus** [comment]
@Tyriar - Thanks for pointing this approach out.

I've configured settings.json as given in the description:

```json
    "terminal.explorerKind": "external",
    "terminal.external.windowsExec": "wt",
```

But when I click `Open in Windows Terminal` on a folder (Remote SSH), it still opens the integrated terminal instead of launch WT. 

Is there anything I missed?

**Comment by Tyriar** [comment]
@tigerinus that's something only an extension could handle since the connection details need to be handled, so you'd want to try https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal which should work for wsl/ssh/containers

**Comment by tigerinus** [comment]
> @tigerinus that's something only an extension could handle since the connection details need to be handled, so you'd want to try https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal which should work for wsl/ssh/containers
> 
> To be clear, you'd want to setup the keybinding for one of these:
> 
> ![image](https://user-images.githubusercontent.com/2193314/130110527-8e42d183-f804-49ac-9208-17a7bb62488e.png)

Yes. I tried the extension. It still launches integrated terminal when I click on Open In Windows Terminal.
