### ISSUE TITLE
Markdown-specific search for GitHub.dev

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131105]
I've been using GitHub.dev more now that there's a handy shortcut for it. Something I really miss is being able to ctrl+f in readmes for specific content I'm looking for. Today that opens the generic find window that operates on the whole window/editor. I know we don't have control over the native find behavior in browser, but for github.dev could we have a custom "find" implementation in the markdown preview  that supports a common set of scenarios?

**Comment by bpasero** [comment]
see https://github.com/microsoft/vscode/issues/125118#issuecomment-857461433 for a quick experiment I did. `window.find` works actually pretty well.

**Comment by mjbvz** [comment]
Duplicate of #136473
