### ISSUE TITLE
[Question]Disable extensions is not working anymore in Windows?

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#13110]
- VSCode Version: 1.5.3 and 1.6.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Disable extensions with `--disable-extensions` is not working anymore in Windows?

Now I need to relocate the extensions folder or rename to be able to disable, as said @joaomoreno  this [comment](https://github.com/Microsoft/vscode/issues/8926#issuecomment-231664050)? --disable-extension is faster.

**Comment by joaomoreno** [comment]
No, we didn't remove the flag. It should work.

I can't reproduce though. Make sure all windows are closed before you call the command. Did you install `vscode-icons`?

**Comment by Tekbr** [comment]
The insider version yes, but the stable version does not.

I created a new shortcut to the VSCode and VSCode Insiders and it worked now. Very strange ... Thank you for attention.
