### ISSUE TITLE
Markdown settings create two Settings editor tree entries

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#131113]
- VS Code Version: 1.59.0
- OS Version: Windows 10

If you filter the Settings editor on "markdown", you can see that there are two "Markdown" entries in the Settings editor tree entries.

![image](https://user-images.githubusercontent.com/12818376/129946242-95e88e71-9df4-4822-b01b-4ddf90adbe43.png)

For some reason, the Markdown > Math: Enabled setting creates a new tree node.

**Comment by AiverReaver** [comment]
Yeah for some reason there are two markdown entry
