### ISSUE TITLE
hover links in terminal disappear when new output appears

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#131114]
Issue Type: <b>Bug</b>

this is using windows client with linux remote-wsl guest in terminal window. use-case is clicking filenames in a program's console log output:

- run program in terminal window
- program outputs log line containing filename
- hover over filename in terminal window
- underline appears indicating clickable link
- wait
- program outputs another log line
- hovered link disappears. the underline is gone and the filename is no longer clickable.
- move the mouse cursor a couple pixels to the right (still over same filename)
- hover link reappears

this may seem pathological, but if you're scrolled to the top of a bunch of output (such that the program output does not cause the window to scroll) and your program is spewing many lines per second of output, this bug makes it almost impossible to click these links because they only appear for a split second.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-63-generic
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (8.63GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|SSH: larkbox|
|OS|Linux x64 5.8.0-63-generic|
|CPUs|Intel(R) Celeron(R) J4125 CPU @ 2.00GHz (4 x 1310)|
|Memory (System)|5.63GB (1.01GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (9.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (9.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.35GB (9.56GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
gitlens|eam|11.6.0
autoscrolldown|fox|1.1.1
cpptools|ms-|1.5.1
hexeditor|ms-|1.8.2
edit-with-shell|ryu|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn478:30354110

```

</details>

**Comment by Tyriar** [comment]
Demonstration of issue:


![Image](https://user-images.githubusercontent.com/2193314/206313284-90c0dd2c-50ba-4c59-bb6d-e6104be6a588.gif)

ie. it would feel more polished if links were re-evaluated when data was added to the buffer if ctrl is held.

**Comment by Tyriar** [comment]
Created an upstream issue: https://github.com/xtermjs/xterm.js/issues/4295 let's just track it over there as it's a pretty minor polish thing

**Comment by Spongman** [comment]
it's not a minor polish thing. this bug makes it *impossible* to click links in output that is continuously being added to.
