### ISSUE TITLE
.txt files get incorrectly associated with "random" languages on open

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#131133]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.60.0-insider (user setup)
Commit: 0214d59846f265d9e50f53b61e2267407d81cbfb
Date: 2021-08-18T05:14:14.284Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open some text document with a bunch of English/etc. language text that is obviously not C/C++ but has some C/C++ in it. I can send the repro text file via email if you want.

Bug: It's auto-detecting it as C++, but when I manually click the C++ and choose auto-detect it correctly updates it to "Plain text" which matches the associations for .txt (for the C++ scenario our team just wants the auto-language detection for extensionless files).

**Comment by sean-mcmanus** [comment]
I also repro .txt files getting associated incorrectly with Batch.

**Comment by sean-mcmanus** [comment]
Another case got it associated with Ruby -- seems like it might be random or something.

We have a whole bunch of txt test files that have test output.

**Comment by gjsjohnmurray** [comment]
Maybe caused by https://github.com/microsoft/vscode/commit/85936d39d31996beec5064856919be9e100bd963

/assign @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
I've removed the support of guessing what's in `.txt` files and left those as plaintext. If the file is extension-less, then we'll try and guess.

**Comment by TylerLeonhardt** [comment]
@sean-mcmanus can you verify this is working as expected for you now? And not changing the language on .txt files?
