### ISSUE TITLE
Intellisense inserts useless `import` on globals

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#131158]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59
- OS Version: Windows 10 21H1

Steps to Reproduce:

1. Open any typescript or javascript project.
2. Install [globalthis](https://www.npmjs.com/package/globalthis) into it.
3. Type in an object (or also a type, in typescript) that is available globally, like `Array`, `DocumentFragment`, `window`, `Math`, etc. Literally *any* global will do, but I'll use just one as an example hereafter.
4. Observe intellisense helping you complete `DocumentFrag` into `DocumentFragment`:
    ![image](https://user-images.githubusercontent.com/152227/130038200-3a0a0892-5da8-400a-8096-520f550f1c48.png)
    (on a sidenote: why two?)
5. Select that one in intellisense and hit enter to confirm.

Expected:

`DocumentFragment` is inserted into the document and that's it.

Actual:

`DocumentFragment` is inserted into the document **and** this is inserted at the top:

```typescript
import { DocumentFragment } from "globalthis/implementation";
```

This is a useless and incorrect import. Globalthis doesn't work like that, and the package contains no instruction for VScode to do this, as far as I can tell. It is meant purely as a polyfill/shim, which shouldn't affect development in any way.

**Comment by thany** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [typescript intellisense import is not supported in <script lang="ts"> block (#126770)](https://www.github.com/microsoft/vscode/issues/126770)

Bad bot. That's totally different.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by thany** [comment]
@mjbvz  
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

It doesn't appear to happen on Insiders with extensions disabled. I even took the effort to copy all my settings over.

Does this indicate the problem has been fixed? If so there should be at least a pre-existing issue for it, which I couldn't find. Perhaps under a different kind of title...

**Comment by mjbvz** [comment]
Closing as likely fixed by the new TS version in insiders based on the feedback
