### ISSUE TITLE
Indicate focused panel

### ISSUE THREAD

**Issue by Trebor-Huang** [microsoft/vscode#131184]
I'm using the builtin dark theme. From my personal experiences, it is difficult to tell which panel is currently focused on. So it is easy to accidentally type into files when trying to execute commands in a terminal, or vice versa. I'd like to have a setting to enables some sort of indication, e.g. highlighting the bounds or using a slightly different shade as background,  of the current focus.

**Comment by misolori** [comment]
We you open the panel, we do have our focus indicator that highlights the area:

![image](https://user-images.githubusercontent.com/35271042/130107895-2a3cc635-f7b1-4f94-a1d0-3ccb136563fa.png)

And when you are focused on an item in there, the item will be highlighted:

<img width="1024" alt="CleanShot 2021-08-19 at 09 35 03@2x" src="https://user-images.githubusercontent.com/35271042/130107953-eb1fc54f-0795-446a-bde6-5143b34e53d7.png">

And when your focus is in the editor, the selected item turns a different color:

<img width="1024" alt="CleanShot 2021-08-19 at 09 35 07@2x" src="https://user-images.githubusercontent.com/35271042/130108013-487d8a16-4013-4d23-9f61-e183288b2053.png">

Are you not seeing this?

**Comment by Trebor-Huang** [comment]
I'm having problems seeing the indicator on consoles and text editors. I'm away from keyboard now, so I'll provide a screenshot tomorrow. Searching in the settings doesn't turn up anything useful.

**Comment by misolori** [comment]
In the console when you are focused you'll see the cursor indicator:

<img width="468" alt="CleanShot 2021-08-19 at 10 09 17@2x" src="https://user-images.githubusercontent.com/35271042/130112992-040e4e4f-4f45-4b37-bc2c-6e67b8142db8.png">

and when focus moves out:

<img width="392" alt="CleanShot 2021-08-19 at 10 09 43@2x" src="https://user-images.githubusercontent.com/35271042/130113014-94002a15-fedd-4d9c-bbb3-71b1f045b301.png">

**Comment by Trebor-Huang** [comment]
I see. Is it possible to add the blue border as in the Problems panel? It makes the focus indication more uniform.

**Comment by misolori** [comment]
Since the focus is on the input, it does not make sense to place the blue focus on the entire panel. I'll close this as `as-designed` since this is by-design.
