### ISSUE TITLE
Potential leak of notebook outputs 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#131145]
Debugging notebook memory usage, I noticed that this code is rendering markdown but not dealing with the resulting disposables:

https://github.com/microsoft/vscode/blob/955a1aca9a2e4473eec4f4bdc70506a3a7c43ca7/src/vs/workbench/contrib/notebook/browser/view/output/transforms/textHelper.ts#L40

This seems to cause a notebook output data buffer to be retained even after the notebook is closed

**Comment by mjbvz** [comment]
One more potential case (although I don't see it causing leaks):

https://github.com/microsoft/vscode/blob/b88a5c3286ecd3bf0cfec222b6d18fcc23464ce1/src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts#L808

**Comment by rzhao271** [comment]
@mjbvz what are some verification steps for this issue?
