### ISSUE TITLE
lua syntax highlighting bug

### ISSUE THREAD

**Issue by qq06314488** [Microsoft/vscode#13118]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.lua 语言模式下,十六进制,语法高亮显示不正确
![qq 20161001195715](https://cloud.githubusercontent.com/assets/22559946/19013919/55e2a1d6-8811-11e6-92de-54f96416492b.jpg)

**Comment by aeschli** [comment]
This issue was moved to textmate/lua.tmbundle#6
