### ISSUE TITLE
Not recognising Typescript 2.0 npm/@types definitions in code highlighting

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/vscode#13117]
I have been using the Typescript 2.0 approach to definition files and installed them, but VSCode doesn't seem to be picking these up, see the unrecognised modules, and the definitions in `node_modules/@types` on the right-hand side. `tsc` runs fine. I have reopened Code a few times to see if this is intermittent. It would appear to be persistent. 

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/dAchZ.png

- VSCode Version: **1.5.3**
- OS Version: **Windows 10 Pro**
- Node: **6.7.0**

Steps to Reproduce:

1. `git clone https://github.com/georgeedwards/docs`
2. `npm i`
3. `code .`
4. Observe Highlighting issues

**Comment by waderyan** [comment]
@georgeedwards thank you for opening this issue. 

I saw the same issue when I cloned your repo. I took steps to recreate it on a smaller example and then I realized what I didn't do. Try reloading the window with this command. 

![image](https://cloud.githubusercontent.com/assets/2449568/19054593/f34a8718-8974-11e6-8162-8520b9d75824.png)

This solved the issue for me.

**Comment by georgeedwards** [comment]
@waderyan Ahh, what does the Reload Window command do? I think the issue might be vscode selecting TS1.8 rather than 2.0. I usually get a prompt to ask me to check, but I didn't this time. Is there a way to stop it asuming 1.8 is an option?

**Comment by waderyan** [comment]
I believe we added a setting to your settings file when you checked for it not to prompt again. Can you check there? 

Reload Window reloads the current VS Code window. Think of it like browser refresh.

**Comment by mohsen1** [comment]
I have the same issue and here is a tiny repository to reproduce it:

https://github.com/mohsen1/expect-tsd

**Comment by mohsen1** [comment]
Another update:

Using `Version 1.6.0-insider (1.6.0-insider)` (093d09e9e8a6b76ec09af97da45e242e317d8d95) I don't have this issue anymore

**Comment by waderyan** [comment]
@mohsen1 can you show me what you see? I am not seeing any issues. Also, please update to v1.6

![image](https://cloud.githubusercontent.com/assets/2449568/19252034/5e1051c2-8ef7-11e6-962f-2b79001fb598.png)

**Comment by mohsen1** [comment]
Can confirm it works in 1.6. How did I miss that update?!
