### ISSUE TITLE
Inconsistent terminal renaming when using the editor area

### ISSUE THREAD

**Issue by newbRaymond** [microsoft/vscode#131190]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Open two or more terminals in the panel.
2. Move one or more terminals into the editor area.
![image](https://user-images.githubusercontent.com/14317628/130093389-0e3051a3-a57a-4ada-ba73-7580c8e06dbc.png)
3. Attempt to rename either an unfocused editor area terminal, or if only one terminal remains in the panel, the panel terminal by right clicking when the editor area has had last focus.
![image](https://user-images.githubusercontent.com/14317628/130097794-01a0025d-5d55-4616-bd12-f8d37664315b.png)
![image](https://user-images.githubusercontent.com/14317628/130093556-ccebc5ef-e162-42cd-b085-7de9a670d63b.png)
![image](https://user-images.githubusercontent.com/14317628/130097909-3e0c4c08-a371-41a9-9ad7-995d39e01e04.png)
4. The name of the most recently focused editor terminal (even if none is presently selected) changes, rather than the right-clicked terminal (whether an unfocused editor area terminal or the unfocused panel terminal).
![image](https://user-images.githubusercontent.com/14317628/130098109-97777afb-ce33-4baf-b4ec-5389ccbfdd60.png)

Expected behaviour:

The name of the terminal selected on right click will be changed.

**Comment by Tyriar** [comment]
Same applies to color and icon
