### ISSUE TITLE
typescript.tsserver.useSeparateSyntaxServer -> typescript.tsserver.useSyntaxServer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#131142]
Tracks renaming the `typescript.tsserver.useSeparateSyntaxServer` setting to a new `typescript.tsserver.useSyntaxServer` setting. Unlike the existing boolean property, `typescript.tsserver.useSyntaxServer` will have three states:

- `always` — Only use a syntax server 
- `never` — Use a single server that handles both syntax and semantic requests (replaces `false`)
- `auto` — Use a dedicated syntax server for syntax operations and for limited semantic operations while loading projects (replaces `true`)

**Comment by amcasey** [comment]
LGTM
