### ISSUE TITLE
No close field in vscode.d.ts interface TaskPresntationOptions

### ISSUE THREAD

**Issue by jackos** [microsoft/vscode#131125]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Linux JD 5.13.10-arch1-1

Although there is an option to close terminal after task completes running in tasks.json, the option doesn't exist in vscode.d.ts interface TaskPresntationOptions

Steps to Reproduce:

1. Create VS Code extension
2. Create a task in extension
3. Try to set presentation field with close:
![image](https://user-images.githubusercontent.com/77730378/129965587-f28eb364-33ec-4bd5-869f-c72d516bdaaa.png)

Steps to Fix:
1. Add close field to interface TaskPresntationOptions in vscode.d.ts:
![image](https://user-images.githubusercontent.com/77730378/129965936-d43b600e-f4d4-4090-9c4a-31d6030be6b3.png)
2. No TypeScript error:
![image](https://user-images.githubusercontent.com/77730378/129966086-85d44671-0f5a-46bb-bac8-6ce9c34995cb.png)
3. Behaves as expected, task closes after run:
![working](https://user-images.githubusercontent.com/77730378/129967473-8bd69d94-f21f-46b1-b30c-e6e8036c8ca7.gif)

Adding this issue for a pull request

**Comment by alexr00** [comment]
@jackos can you please describe why having the presentation options `close` is important to have as extension API? We do not like to add API just for the sake of having it, so I want to understand that it will be useful for multiple extension authors before adding it.

**Comment by jackos** [comment]
Hi @alexr00 

[I added details of why it's important in pull request 131127](https://github.com/microsoft/vscode/pull/131127)

**Comment by alexr00** [comment]
@jackos sounds like you have a real use case for it. Thanks for the details!

**Comment by meganrogge** [comment]
Reopening for finalization
