### ISSUE TITLE
[css] at-rules in CSS no longer distinguished from selectors in dark theme

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1311]
Probably somewhat related to #1271

In the dark theme (and light theme), CSS at-rules (e.g. @font-face) were coloured purple, distinguishing them from regular selectors.

In builds from Master, they're now the same colour as selectors: blue. In light theme they are distinguished from selectors, but are now blue instead of purple (regular selectors are dark red in light theme)

See @font-face in the screenshot (note @keyframes is not highlighted at all in stable, but it probably isn't known in css.plist or Intellisense)

Also, Unknown keywords when used as property values (e.g. keywords known by IntelliSense like the local keyword for background-attachment, but not known by the CSS.plist highlighter) are now not coloured (white) rather than a orange/red like before.

Left: current stable. Right: built from MS/Master

![screen shot 2015-12-14 at 4 12 51 p m](https://cloud.githubusercontent.com/assets/465069/11798237/e67a7a4a-a27d-11e5-95c0-70982922de04.png)

**Comment by aeschli** [comment]
fix delivered
