### ISSUE TITLE
Explore migrating kernel preloads to use JavaScript modules

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#131117]
Let's explore using JS modules for notebook kernel preload scripts. This would better align with the notebook renderers API

**Comment by mjbvz** [comment]
Jupyter is currently using these preload script to load JS globals for the notebook environment, such as requirejs. We'd need to figure out how to handle those cases

**Comment by mjbvz** [comment]
@DonJayamanne For jupyter, could you register a single module based preload that then writes any required global scripts into the document?

**Comment by DonJayamanne** [comment]
Yes, that would work.
