### ISSUE TITLE
Tasks in workspace file not being detected

### ISSUE THREAD

**Issue by sharpninja** [microsoft/vscode#131174]
Issue Type: <b>Bug</b>

 
Here is my workspace file.  There doesn't appear to be any errors and the tasks work in a yasks.json file.

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"cSpell.words": [
			"coreclr"
		]
	},
	"extensions": {},
	"launch": {
		"configurations": [
			{
				"name": ".NET Core Launch (console)",
				"type": "coreclr",
				"request": "launch",
				"preLaunchTask": "build",
				"program": "${workspaceFolder}/bin/Debug/<target-framework>/<project-name.dll>",
				"args": [],
				"cwd": "${workspaceFolder}",
				"stopAtEntry": false,
				"console": "internalConsole"
			}
		],
		"compounds": []
	},
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "Build",
				"type": "shell",
				"command": "dotnet",
				"args": [
					"build",
					"${workspaceFolder}/PObject-Study.sln"
				],
				"problemMatcher": [
					"$msCompile"
				],
				"group": {
					"isDefault": true,
					"kind": "build"
				}
			},
			{
				"label": "Watch",
				"type": "shell",
				"command": "dotnet",
				"args": [
					"watch",
					"--project",
					"${workspaceFolder}/src/PattenLang.PObject/PattenLang.PObject.csproj"
				],
				"options": {
					"cwd": "${workspaceFolder}/src/PattenLang.PObject"
				},
				"problemMatcher": [
					"$msCompile"
				]
			},
			{
				"label": "Clean",
				"type": "process",
				"windows": {
					"command": "c:\\Program Files\\PowerShell\\7\\pwsh.exe",
				},
				"linux": {
					"command": "pwsh"
				},
				"args": [
					"-c",
					"{ gci bin,obj -recurse | ri -recurse -force; }"
				],
				"options": {
					"cwd": "${workspaceFolder}"
				}
			}
		]
	}
}

```

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.93GB free)|
|Process Argv|. --crash-reporter-id 11c780ce-9fc0-40c3-9553-00ac345e8db8|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
stack-overflow-view|4tr|0.1.1
underscore-name|adr|1.2.1
Bookmarks|ale|13.1.0
code-web-search|ale|1.0.0
specflow-tools|ami|1.1.3
github-markdown-preview|bie|0.0.2
markdown-preview-github-styles|bie|0.2.0
jsonviewer|cci|1.2.2
vscode-jetbrains-icon-theme|cha|1.0.6
path-intellisense|chr|2.4.0
regex|chr|0.4.0
gitignore|cod|0.7.0
reverse-search|Dan|2.0.2
ini-for-vscode|Dav|0.0.4
vscode-quick-select|dba|0.2.9
search|dba|2.0.4
xslt-xpath|del|0.3.6
vscode-dotnet-adapter|der|1.4.3
cs-repl|Dom|0.0.6
githistory|don|0.6.18
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
prettier-vscode|esb|8.1.0
fakesharper|fak|1.0.0
vscode-solution-explorer|fer|0.4.4
seito-openfile|Fr4|1.8.8
vscode-pull-request-github|Git|0.29.2
vscode-test-explorer|hbe|2.21.0
beautify|Hoo|1.5.0
githd|hui|2.2.4
reg|ion|1.0.3
open-nuget-site|itn|0.0.1
search-editor-apply-changes|jak|0.1.1
plantuml|jeb|2.15.1
vscode-nuget-package-manager|jmr|1.1.6
roslynator|jos|3.2.2
reflow-markdown|mar|2.1.0
plantumlpreviewer|Meb|0.6.0
csharp|ms-|1.23.14
mssql|ms-|1.10.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
powershell|ms-|2021.8.0
test-adapter-converter|ms-|0.1.2
vs-keybindings|ms-|0.2.1
vscode-markdown-plantuml-preview|mym|0.0.2
git-config-user-profiles|onl|1.0.18
vscode-versionlens|pfl|1.0.9
csharp-to-plantuml|pie|1.2.4
stack-trace-formatter|Rad|1.0.6
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
explorer-exclude-vscode-extension|Red|1.2.0
csharp-helper|roa|0.0.14
scratchpadmd|saa|0.2.0
integrated-stackoverflow|sau|1.0.1
gitconfig|sid|2.0.1
vscode-devto|sne|0.0.12
vscode-vslauncher|spm|1.0.8
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.15
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.14
vscode-plantuml-stdlib-snippets|vor|0.2.0
vscode-icons|vsc|11.6.0
gistfs|vsl|0.3.0
vscode-nxunit-test-adapter|wgh|0.1.3
file-size|zh9|1.0.0
vscode-proto3|zxh|0.5.4

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. Did you make sure to open the _workspace_ (with the command File: Open Workspace then choosing the .code-workspace file) not the folder?
