### ISSUE TITLE
Search input - recent search history

### ISSUE THREAD

**Issue by RPainter8West** [microsoft/vscode#131160]
I typically search for the same things over and over.  In VS the search input has a dropdown with my recent search terms so I can just click one.  In VS-Code I have to re-type my search term each time.  For a complex regex search this doesn't work.  I have to keep a text file open with my regex search terms.

Please add a recent search term history feature.

**Comment by gjsjohnmurray** [comment]
History is already there but you need to know to use <kbd>UpArrow</kbd> and <kbd>DownArrow</kbd> to access it.

PR #129324 is addressing discoverability.

**Comment by RPainter8West** [comment]
Thanks @gjsjohnmurray . I didn't realize the arrows worked, and that PR would be an improvment.  

But still, it would be nice to have this as a drop-down so I can select a specific one rather than paging through them one at a time for who knows how long, only to find that the one I was looking for wasn't actually in my history.  A drop-down would allow me to see if my value was in the history, and allow me to select it in 2 clicks.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/23099
