### ISSUE TITLE
Python and Pylance extension installation failed. 

### ISSUE THREAD

**Issue by xinrongl** [microsoft/vscode#131232]
## Environment data

-   VS Code version: 1.59.1
-   Extension version (available under the Extensions sidebar): Python & Pylance
-   OS and version: 
  >NAME="Ubuntu"
    VERSION="18.04.4 LTS (Bionic Beaver)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 18.04.4 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.6.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: Python (v2021.8.1147840270) & Pylance (v2021.8.2)
-   Value of the `python.languageServer` setting: N/A

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour
Expected extension to be installed. Tried to install python and pylance extension on above os (remote ssh), not working. Below steps are attemped:
- Download python extension from github release and install .vsix manually, same error message. (see log below)
- Download and install other extension are successful and seems like only python and pylance extension got affected since the latest update.

## Actual behaviour

Error while installing 'Pylance' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install via extension sidebar within vscode, or
2. Install manually via calling `Extensions: Install from VSIX` command within vscode.

## Logs
[2021-08-20 14:28:13.591] [renderer7] [error] getaddrinfo ENOTFOUND marketplace.visualstudio.com: Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[2021-08-20 14:29:30.638] [renderer7] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[2021-08-20 14:29:35.740] [renderer7] [error] getaddrinfo ENOTFOUND marketplace.visualstudio.com: Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[2021-08-20 14:31:54.178] [renderer7] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[2021-08-20 14:32:55.819] [renderer7] [error] ENOENT: no such file or directory, access '/home/cdsw/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218': Error: ENOENT: no such file or directory, access '/home/cdsw/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218'
[2021-08-20 14:32:56.785] [renderer7] [error] ["Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)"]
[2021-08-20 14:32:56.799] [renderer7] [error] getaddrinfo ENOTFOUND marketplace.visualstudio.com: Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by sandy081** [comment]
It seems from the logs, you have network connection issues - Please check if you are able to do following?

Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a network issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please contact your network administrator.

**Comment by xinrongl** [comment]
Can you please try installing the python extensions and provide us following logs
-----------------------------------------------------------------------------------------

Apologize for the late reply again. Please see the below logs.

- Help -> Toggle Developer Tools -> Console
>
![image](https://user-images.githubusercontent.com/34294114/131282458-e355e3d7-674e-4c17-a8a6-7a4fe49bec17.png)

- View -> Command Pallette... -> Toggle Shared Process -> Console
> N/A

- View -> Open View… -> Log (Shared)
> N/A
- View -> Open View… -> Log (Window)
> [2021-08-30 13:54:25.900] [renderer5] [error] ["Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)"]
[2021-08-30 13:54:25.924] [renderer5] [error] getaddrinfo ENOTFOUND marketplace.visualstudio.com: Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

**Comment by ZhouqyCH** [comment]
I met the similar problem. I've tried the following two way to install them but failed.
(1. Install via extension sidebar within vscode, or
2. Install manually via calling Extensions: Install from VSIX command within vscode.)

My solution is as follows. I don't know the reason but it actually works for me. Hope it helps you.
1. Download the .vsix file of python extension from https://marketplace.visualstudio.com/vscode and install it via command line: 
code --install-extension xxxx.vsix
This command installs python extension to the path ./.vscode/extensions/ms-python.python-xxx successfully. 
2. Move ./.vscode/extensions/ms-python.python-xxx to ./.vscode-server/extensions/.
Now you can find the python extension in vscode and the pylance extension will be installed automatically. When receive the installation success message, restart the vscode window to activate them.

**Comment by xinrongl** [comment]
> I met the similar problem. I've tried the following two way to install them but failed.
> (1. Install via extension sidebar within vscode, or
> 2. Install manually via calling Extensions: Install from VSIX command within vscode.)
> 
> My solution is as follows. I don't know the reason but it actually works for me. Hope it helps you.
> 
> 1. Download the .vsix file of python extension from https://marketplace.visualstudio.com/vscode and install it via command line:
>    code --install-extension xxxx.vsix
>    This command installs python extension to the path ./.vscode/extensions/ms-python.python-xxx successfully.
> 2. Move ./.vscode/extensions/ms-python.python-xxx to ./.vscode-server/extensions/.
>    Now you can find the python extension in vscode and the pylance extension will be installed automatically. When receive the installation success message, restart the vscode window to activate them.

Hi Zhuo, thanks for your reply. I followed your step and failed at the first step, got same error: "Failed Installing Extensions: vscode-remote://ssh-remote%2Bbocvp/home/cdsw/ms-python-release.vsix". Do you have any ideas?

**Comment by ZhouqyCH** [comment]
> > I met the similar problem. I've tried the following two way to install them but failed.
> > (1. Install via extension sidebar within vscode, or
> > 2. Install manually via calling Extensions: Install from VSIX command within vscode.)
> > My solution is as follows. I don't know the reason but it actually works for me. Hope it helps you.
> > 
> > 1. Download the .vsix file of python extension from https://marketplace.visualstudio.com/vscode and install it via command line:
> >    code --install-extension xxxx.vsix
> >    This command installs python extension to the path ./.vscode/extensions/ms-python.python-xxx successfully.
> > 2. Move ./.vscode/extensions/ms-python.python-xxx to ./.vscode-server/extensions/.
> >    Now you can find the python extension in vscode and the pylance extension will be installed automatically. When receive the installation success message, restart the vscode window to activate them.
> 
> Hi Zhuo, thanks for your reply. I followed your step and failed at the first step, got same error: "Failed Installing Extensions: vscode-remote://ssh-remote%2Bbocvp/home/cdsw/ms-python-release.vsix". Do you have any ideas?

Did you install it via remote-ssh connection? I didn't meet the problem. I executed the command on the remote server (by MobaXterm) but not by the remote-ssh.

**Comment by agneskinra** [comment]
I'm having this problem trying to load Python and Pylance on an ssh remote. I can install other extensions - and in fact Jupyter installs successfully when I try to install Python and Pylance. Other random extensions can be installed on the remote.

The failure normally shows up as a connection failure to an IP address, something like this:
```
[2021-09-02 06:51:32.418] [renderer1] [error] connect ETIMEDOUT 13.107.6.175:443: Error: connect ETIMEDOUT 13.107.6.175:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

```
This visualstudio.com address seems to be used for python extension installation but not for anything else. Just poking around at it with a browser gets:
`<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>`

**Comment by sandy081** [comment]
@xinrongl There is a new release update last week. Can you please update VS Code to 1.60.0 and please try?

**Comment by xinrongl** [comment]
> @xinrongl There is a new release update last week. Can you please update VS Code to 1.60.0 and please try?

hi @sandy081 , thanks for notifying me, found the issue is resolved from the latest release, thanks.

**Comment by Huskers2020** [comment]
This issue is also on FreeBSD not certain if this is supported from your end. Also, 1.6 is not yet ported to FreeBSD so cannot validate.

**Comment by marknelson** [comment]
> @xinrongl There is a new release update last week. Can you please update VS Code to 1.60.0 and please try?

Fixed for me, thanks!

**Comment by mrajcok** [comment]
I was getting the following error when trying to install on a remote server in our lab that does not have Internet access: 

`[2021-10-02 09:48:12.729] [renderer1] [error] Error while installing 'ms-python.python' extension in the remote server. getaddrinfo ENOTFOUND ms-python.gallery.vsassets.io`

The solution was to download the vsix file, copy it to the remote/lab server, the install it manually: https://stackoverflow.com/a/50232194/215945
