### ISSUE TITLE
Not hitting breakpoints in web extension running in VS Code Desktop stable

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#131265]
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

JavaScript debugger: v1.59.0

- clone https://github.com/microsoft/vscode-extension-sample and open VS Code in folder `helloworld-web-sample`
- install the recommended extensions
- set a breakpoint the command handler of `extension.ts`: https://github.com/microsoft/vscode-extension-samples/blob/66223aae68dbea6313b80aecbcac99e8605c21b4/helloworld-web-sample/src/web/extension.ts#L20
- from the run viewlet run `Run Extenion`
- in the Extension Development Host window run the Hello World command

dialog shows that we are running in the web extension host (`Hello World from helloworld-web-sample in a web extension`), but breakpoint is not hit. 

In the latest insider build it works (1.60.0-insider , c08913337cb8b95493be8e99d62e0b3241563f6b, 2021-08-19T05:15:46.693Z) JavaScript debugger: v1.60.0

**Comment by aeschli** [comment]
Now I got a breakpoint hit in stable, but the breakpoint was a on the line below the handler. So maybe its source map related.

**Comment by connor4312** [comment]
The latest [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) is required to debug web extensions, which requires 1.60-insiders or newer.

/duplicate https://github.com/microsoft/vscode/issues/128637
