### ISSUE TITLE
Support links in stack traces (of Notebook Cell Outputs) that end up being links to a position in a file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131239]
Assume .NET extension adds an error object as an output, the stack traces contain paths to lines.
None of them can be clicked.

In Jupyter extension we have ability to change these stack traces into links for Interactive window.
I have a personal extension that turns these stack traces into links for Jupyter Notebooks.
I also have another extension that turns these stack traces into links for yet another Notebook.

Tomorrow if .NET or Julia too want links in stack traces, they'll need to create custom renderers for the error mime type.

This doesn't seem too practical.

**Suggestion:**
* Solution 1: Allow proving simple HTML links or markdown links in the stack trace string that can be parsed & displayed as real links in the error renderer.
* Solution 2: (preferred) Or provide some extensibility to register a link provider for error outputs (just as we do with Document & terminal link providers)

This way:
* Interactive window can have links in notebook outputs can map to Python files
* Jupyter error outputs can have links that point to cells or other external files
* Similarly other languages could have their own links.

**Comment by DonJayamanne** [comment]
The problem in not having this is, if we install Jupyter extesnion that overrides the error formatter for every other notebook.
I personally don't want the error formatter from jupyter in other notebooks.

This is actually related to https://github.com/microsoft/vscode/issues/125876, but with some usability issues (i.e. one extension isn't designed well enough, hence ends up breaking other extesnsions. I.e. i don't see errors in other notebooks, but the perception is, that this second notebook is broken)

**Comment by rebornix** [comment]
Let's track in it https://github.com/microsoft/vscode-jupyter/issues/12285
