### ISSUE TITLE
vscode can't update on windows

### ISSUE THREAD

**Issue by backermanbd** [microsoft/vscode#131270]
Issue Type: <b>Bug</b>

when i tried to update my vscode in windows, it shows something like vscode can't write a file (couldn't copy the message)
i had this problem many times
that i had to download from vscode main page, and manually install it
please fix this issue

PS: telemetry was enabled.. i guess you should get my crash report by now

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.43GB (0.67GB free)|
|Process Argv|--crash-reporter-id 6b20bd8a-49fc-4477-8041-66a0ee7e3ffc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
better-keybindings|cal|0.1.2
simple-project-switcher|cal|0.1.4
better-jest|Coa|1.0.0
disableligatures|Coe|0.0.10
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
php-namespace-resolver|Meh|1.1.8
vscode-duplicate|mrm|1.2.1
cpptools|ms-|1.5.1
toggle|reb|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedc:30351792
vsdyn478:30354110

```

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
