### ISSUE TITLE
Show notebook cell status when cell is collapsed - Example: Show Cell Completed Run Symbol

### ISSUE THREAD

**Issue by gebob19** [microsoft/vscode#131200]
In the previous notebook UIs there was a symbol which appeared after the notebook cell finished running. In the most recent version this was removed and now when you run cells which don't have any output (e.g last line in cell: `x = fcn(y)`) you don't know if it completed or is still running unless you expand the cell output and see the green checkmark.

_Feature Request:_ If we could add a symbol which is visible when a notebook cell finished running while the cell is in collapsed mode that would be awesome. 

For example, we can just move the cell run number (`[61]`) and the green checkmark outside the collapsable cell so they are always visible. 

Thanks!

Current UI Cell Collapsed (no completion symbol)
![image](https://user-images.githubusercontent.com/28021277/130129254-a98b8095-f21e-4e6f-b18d-bd3947334f12.png)

Current Bottom-of-Cell UI Expanded (completion symbol visible)
![image](https://user-images.githubusercontent.com/28021277/130129303-77bdc446-cdc9-4fea-a7ea-3a3ec5cecffe.png)

**Comment by DonJayamanne** [comment]
I tend to collapse a lot of the cells when running some training. I end up tweeking just one or two cells, and the rest remain un-changed, hence they are all collapsed (as some have outputs as well).
this would be very very useful as I tend to expand cells or look at the execution order to ensure the cells ran (e.g. if i have 23 cells, i check the last cell thats uncollapsed and confirm it has an execution count of 23).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/130611#issuecomment-919582034 has a mockup for this

**Comment by roblourens** [comment]
> For example, we can just move the cell run number ([61]) and the green checkmark outside the collapsable cell so they are always visible.

Actually the thing I linked above isn't what we need for this issue, @misolori have you done mockups for this yet?

**Comment by misolori** [comment]
I mocked this up a while ago but it would only show the icon status (not time):

<img width="346" alt="CleanShot 2021-12-17 at 13 32 05@2x" src="https://user-images.githubusercontent.com/35271042/146610407-b6934219-a5a2-4f16-ac86-b2fc194af0fc.png">


<img width="442" alt="CleanShot 2021-12-17 at 13 31 31@2x" src="https://user-images.githubusercontent.com/35271042/146610389-21602221-0b8b-45df-8a32-6715f8257b97.png">

**Comment by roblourens** [comment]
I like that. Thanks.
