### ISSUE TITLE
Can't get other machine synced data

### ISSUE THREAD

**Issue by diegonogueira** [microsoft/vscode#131284]
I can't get the settings of another machine. I formated my Windows and now I lost some settings.

How can I get the setting history of the others machines? I don't have those machines anymore.

![image](https://user-images.githubusercontent.com/68256/130300347-665fc0e1-c485-45ae-a1e9-87b3333bf639.png)

Thanks

**Comment by sandy081** [comment]
https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data
