### ISSUE TITLE
Codespaces Product icons not working

### ISSUE THREAD

**Issue by baris-inandi** [microsoft/vscode#131248]
I don't know if this is a github.dev thing or if it's about vscode, but the product icon themes do not load on the newly released GitHub codespaces. 

I tried multiple product icon themes and none of them work properly in workspaces.

![Screenshot from 2021-08-20 11-42-36](https://user-images.githubusercontent.com/68742481/130206411-3f00d6a6-4062-4d55-8b73-762f16669381.png)

**Comment by aeschli** [comment]
It's a github.dev thing. I pinged them in the internal issue.

**Comment by Milo123459** [comment]
Can we get a comment here when it's resolved?

**Comment by aeschli** [comment]
Yes, I'll ask them to do that.

**Comment by Milo123459** [comment]
Thank you

**Comment by misolori** [comment]
This is now fixed in github.dev:

<img width="1140" alt="CleanShot 2021-09-10 at 08 40 02@2x" src="https://user-images.githubusercontent.com/35271042/132880404-599e8b6e-1550-4706-9b56-5f26147699ea.png">
