### ISSUE TITLE
Request for features

### ISSUE THREAD

**Issue by DumboJetEngine** [Microsoft/vscode#13124]
- VSCode Version: 1.5.3
- OS Version: Win10

1. I think we should be able to disable extensions without uninstalling them.
2. I see no obvious way to ignore files on Git. Brackets has an obvious option that is extremely easy to find. Maybe I miss something here?
3. I see no obvious way to clone repos from VSCode. I think it should be able to do this.
4. I can't find a good way to adjust the font size globally (not only in the editor). The best I found was this while trying to make fonts look more like Brackets and I don't like it much:
    "window.zoomLevel": -0.3,
    "editor.fontFamily": "arial, sans-serif"
5. All the file-icon extensions that I tried have their icon blurry. Not sure why, but I guess it has to do something with VSCode itself and its HTML.
6. Maybe the "button" for running the build tasks (and maybe also running the code) should be in a more accessible place?
7. I see no way to view the history with Git.

**Comment by octref** [comment]
1. #2882, likely to land in October.
2. You can edit `.gitignore`.
3. Open integrated terminal, and `git clone <GitURL>`. VSCode usually works in the context of a workspace, which is already a git repo
4. Quick Command -> Zoom in
5. Can you post a picture?
6. `Ctrl-Shift-B` and `F5`.
7. #68

**Comment by octref** [comment]
This issue is more like questions so I'm closing it.
5 looks like a valid feature-request, so feel free to open another issue with screenshots & more detailed description. We prefer to keep a single issue for each bug/feature-request. Thanks!

**Comment by DumboJetEngine** [comment]
> You can edit .gitignore.

> Open integrated terminal, and git clone <GitURL>. VSCode usually works in the context of a workspace, which is already a git repo

OK.
However, I can't understand where you draw the line here.
You have already added UI on top of Git, so this seems like leaving the work half finished (maybe I am wrong, donno).
But I understand (a bit) that you don't want to go to the same direction as Brackets (where they are trying to build UI for everything).
But, it's OK. No need to explain probably.

Here is the new issue:
https://github.com/Microsoft/vscode/issues/13126
:)

**Comment by octref** [comment]
Instead of working on problems that has a work-around, we are more likely to prioritize things that can't work around with (like your point 7).
You can keep an eye on our monthly iteration plan to see what'll be done: https://github.com/Microsoft/vscode/issues/11917
