### ISSUE TITLE
TypeScript decorators not recognized

### ISSUE THREAD

**Issue by jorgeas80** [Microsoft/vscode#13127]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Install [angular-cli](https://github.com/angular/angular-cli)
2. Run ng new myproject
3. Create a new service: cd myproject && ng g service myservice
4. Open the generated project in VSCode and open the myservice.service.ts file

Decorated service not recognized (see img, two examples of decorators not recognized: @Injectable and @Inject)

![not recognized](http://pix.toile-libre.org/upload/original/1475345638.png) 

Check list:
1. "experimentalDecorators": true in tsconfig.json

**Comment by waderyan** [comment]
@jorgeas80 thank you for opening this issue (clearly we're not working well with angular-cli :) ). 

@dbaeumer could use your thought on this. Is this a TS Server bug or is there something unique we do for decorators?

**Comment by dbaeumer** [comment]
@waderyan decorators are a TS feature and therefore a tsserver problem. However in this specific case I am pretty sure that the reason is a missing tsdk setting. Angular cli requires TS 2.0.x and VS Code 1.5.3 still ships with 1.8.10.

**Comment by waderyan** [comment]
Thanks @dbaeumer. 

@jorgeas80 can you try with the daily build of VS Code called Insiders? You can download it [here](http://code.visualstudio.com/insiders).

**Comment by jorgeas80** [comment]
Hi @waderyan,

It's working with the insider version. Great work! And sorry for the delay.

**Comment by waderyan** [comment]
Great thank you.
