### ISSUE TITLE
Stale fwlink generated in extensions.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#13121]
From @gregvanl in https://github.com/Microsoft/vscode-docs/issues/618#issuecomment-250805616.

>Looks like the fwlink in https://github.com/Microsoft/vscode/blob/master/.vscode/extensions.json is stale

Need to verify and fix if needed.

**Comment by sandy081** [comment]
Extensions.json in our workspace got generated before the new fwd link and it was using that of tasks as a placeholder. It's only in our workspace. Fixed it.

**Comment by sandy081** [comment]
@egamma Do we need this to be pushed in 1.6 branch too?

**Comment by egamma** [comment]
@sandy081 that explains it, no need to push to the branch. 

We should fix the screenshot in the release notes.

**Comment by sandy081** [comment]
@egamma We do not have any screenshot of it.. Instead, we copied our recommendations as code (text).

**Comment by egamma** [comment]
@sandy081 then we are good 😄
