### ISSUE TITLE
Add 'publish to gitlab' and 'clone from gitlab' buttons

### ISSUE THREAD

**Issue by dragonDScript** [microsoft/vscode#131212]
Many of us work with gitlab in a daily basis. Integrating it with vscode would improve our lifes.

So, I suggest:
- [ ] A login with gitlab feature.
- [ ] A publish to gitlab [private/public] repository option.
- [ ] A clone from gitlab repository option.

**Comment by IllusionMH** [comment]
Have you tried extension from GitLab team?
https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow

**Comment by dragonDScript** [comment]
> Have you tried extension from GitLab team?
> https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow

No, however I'd prefer a first party workaround. I only need these features, not viewing prs etc.

Also, this extension does not provide the above features.

**Comment by dragonDScript** [comment]
This extension does provide cloning from gitlab, thanks!
