### ISSUE TITLE
VS Code 1.60.0-insider no long respect tokenColorCustomizations for brackets

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#131228]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider
- OS Version: MacOS Catalina

Just restart VS Code Insider to get the update, and it comes back with a bunch of colourful brackets with a weird choice of colours... (I config my bracket to only use specific color based on its type)
![Screen Shot 2021-08-20 at 11 43 22 am](https://user-images.githubusercontent.com/17170199/130166292-bed01453-b7b5-4525-9726-e57718ea51e3.png)

Another thing I noticed that's been on for a while is in the setting page (side by side json), we no longer have the edit button in the left panel for each item. This also takes the scroll sync with it which makes checking configs a huge pain...

**Comment by pingshunhuangalex** [comment]
Actually lots of the syntax highlighting are different after the update. It tries to apply my `tokenColorCustomizations` override but fails here and there all over the place... Hopefully, it's not an intended change. Every time something happens to theme and syntax highlighting, it just completely destroyed my day and workflow

**Comment by gjsjohnmurray** [comment]
See #129231 for incoming feature. Looks like it is enabled by default.

**Comment by pingshunhuangalex** [comment]
Thanks so much @gjsjohnmurray `"editor.bracketPairColorization.enabled": false,` saved the day.

By any chance you also know the answer to my second question? (sorry for being lazy here instead of opening a separate ticket)
> Another thing I noticed that's been on for a while is in the setting page (side by side json), we no longer have the edit button in the left panel for each item. This also takes the scroll sync with it which makes checking configs a huge pain...

**Comment by gjsjohnmurray** [comment]
See #130262

**Comment by pingshunhuangalex** [comment]
Oh no, not sure why the team decides to do this. Well, thanks @gjsjohnmurray again for the link.
