### ISSUE TITLE
With in half an hour have three times with out work when edit html

### ISSUE THREAD

**Issue by WinxEI** [Microsoft/vscode#13122]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.
![image](https://cloud.githubusercontent.com/assets/22310332/19015185/380ea79c-8832-11e6-8e2b-cb122ec26e6a.png)

2.when have the BUG as the figure shows, the edit box will not work,but the menu bar will still work.
if close VS code ,the file not saved will lost.

**Comment by Tyriar** [comment]
@bpasero fyi it's the not responding dialog

**Comment by bpasero** [comment]
@WinxEI any steps to reproduce?

**Comment by Tyriar** [comment]
@WinxEI can you try running VS Code via `code --verbose` and see if there is some exception printed to the console when it crashes?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
