### ISSUE TITLE
Wrong guess encoding using ISO 8859-1

### ISSUE THREAD

**Issue by cirofeitosa** [microsoft/vscode#131258]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS: Darwin arm64 20.6.0
- OS Version: Mac OS Big Sur 11.5.2

Steps to Reproduce:

1. Create a file with accentuations (in my case using portuguese language, example of word: "você"), and save using "ISO 8859-1" encoding
2. Open this file again, VS Code will open as "Windows 1251" encoding, with problems at accentuations ("vocк"). Can't detect the correct encoding.

PS.: I can't use this encoding as default, because exists "UTF-8" files at same project (is a huge project with legacy files)

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by cirofeitosa** [comment]
I know about your explanation. By the way, thank you.

My issue reported is only about the "auto guess encoding" feature, it isn't working in this case. When open the file, the VS Code can't detect the correct file encode automatically. To compare, when I open in Sublime Text, the same file, it open correctly (any encode).

**Comment by bpasero** [comment]
Oh yeah sorry, my comment doesn't make a lot of sense for guessing encoding...

Can you attach the file? We use a library for detection so this issue would need to be reported to https://github.com/aadsm/jschardet/issues

**Comment by cirofeitosa** [comment]
Yes, I have a example (attached).

I'll report at library repository. Thank you, again! 

[example-ISO-8859-1.txt](https://github.com/microsoft/vscode/files/7021851/example-ISO-8859-1.txt)

**Comment by bpasero** [comment]
I think for me it detects the right encoding though:

![image](https://user-images.githubusercontent.com/900690/130242787-7b55eef8-80b8-41fa-88dd-2d8f3996634b.png)

**Comment by cirofeitosa** [comment]
The correct should be ISO-8859-1, not ISO-8859-2.

Try to open this example in another IDE/Editor, and see the difference in accentuations. 

The first word should be: "você"

**Comment by bpasero** [comment]
Ah ok, then yeah please report to `jschardet`, maybe they know about this.

**Comment by bpasero** [comment]
Closing as this is an upstream issue.
