### ISSUE TITLE
Only one editor tab is shown at a time when there are many

### ISSUE THREAD

**Issue by unobatbayar** [microsoft/vscode#131227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.59.1 (Universal)
- OS Version: macOS Catalina

Steps to Reproduce:

1. Open VSCode
2. Open multiple files
![Screenshot 2021-08-20 at 10 40 34](https://user-images.githubusercontent.com/38866249/130165969-918c5591-e768-43a4-b0a7-a74121d6f82b.png)

Wanted behaviour:
![Screenshot 2021-08-20 at 10 45 13](https://user-images.githubusercontent.com/38866249/130166040-9bd7385e-f78e-433c-a363-b4e4f54befb5.png)

**Comment by unobatbayar** [comment]
Is this an update? How can I revert this? Please help, it's difficult to look around files.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by unobatbayar** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Thank you, can you confirm this doesn't happen in your VSCode?

**Comment by unobatbayar** [comment]
By removing everything including preferences and caches, this has been solved. Thank you for your time, sorry for inconvenience.
