### ISSUE TITLE
Terminal window *incredibly* slow.

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/vscode#13128]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open up VS Code.
2. Use the Terminal window by typing something in.

I never really noticed too much but with the latest versions of Code and Ionide (which use the Terminal window now for F# output), I've noticed that the Terminal window is really, really slow - not just for output sent to the terminal from F# but also just typing in the standard terminal - long pauses (1/2 seconds) before it "catches up" with what I'm typing etc.. It also blocks the main editor window whilst these pauses happen.

I suppose that this could be any number of things - happy to help provide more details that would help.

**Comment by Tyriar** [comment]
Duplicate #10328
