### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by 19PosBGH32** [microsoft/vscode#131230]
- Issue Type: `Bug`
- Extension Name: `microsoft-authentication`
- Extension Version: `0.0.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.59.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Defnewbe** [comment]
Hi, I am also having issues loading the extensions. "We cannot connect to the Extensions Marketplace ......"

**Comment by RuppBen** [comment]
Hi, I am  having this issue to, by starting code from the terminal with:

> code --disable-web-security

i get the error:

> Warning: 'disable-web-security' is not in the list of known options, but still passed to Electron/Chromium.

But I can access the marketplace
Note:
Before this I completely deleted code/electron and all user data
starting code normally from the terminal does not work around the issue
