### ISSUE TITLE
Broken image rendering in MarkDownString for VS Code Insiders

### ISSUE THREAD

**Issue by FredCoen** [microsoft/vscode#131256]
It seems that some update in August broke the rendering of images in a MarkDownString. Vs Code Insiders does not render them correctly anymore whereas vs code latest version does. 

- VS Code Version: Version: 1.60.0-insider
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

Withing the MarkdownString of a hoverMessage the below string renders correclty for in VS Code but doesnt in Vs Code Insiders:

data:image/svg+xml,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20style%3D%22%22%20viewBox%3D%220%200%2020%2020%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cimage%20width%3D%2295%25%22%20height%3D%2295%25%22%20preserveAspectRatio%3D%22none%22%20href%3D%22data%3Aimage%2Fjpeg%3Bbase64%2C%2F9j%2F2wCEAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDIBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMv%2FAABEIADAAMAMBIgACEQEDEQH%2FxAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29%2Fj5%2BgEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4%2BTl5ufo6ery8%2FT19vf4%2Bfr%2F2gAMAwEAAhEDEQA%2FANyXw5AWEc0Nr5gHIK7eapX2i6NpMJuL10tVKlgVlZc49MdayfinDt1uMqSMluQfepNf0tJb%2FwAJwTXLyQvZwyNC%2FwB1QFyeffBzXJY7Vq7HLapDrOqXG61t7v7O64iBc%2FdzxnJqybrxr4blguJbqdoYl3LGkmVUf7vSuovPFGivdGOC8XAbbwhAz7E1SvtasLmQoL6MsBgq5xWbk10NuSL6neaJrH%2FCU6JBfqsEwcYdJYlba3ccimahpdpDG122j6Z5sSMUP2RevuMVx%2Fwpv0TxNq%2BmbGCuBNGFPyrg4PH4ivS9cUfYJAynbtOcd606GKtc81%2BKIJ1y3G1uc9veuh8TaTBqXh3w804Hli22PgYONg7%2FAFxxWD8RtU1RdVt5rVZTCqBmbyshee%2FHFd1DjV%2FAMM%2B0PMtsHDEc5A%2BbH5EUO9hRtc8buPD9o%2BrKJ5WSFSCxZvlwD6%2B%2FaqF3o9jNqV01nMPIDkrtORg9q2Nb0%2B6vreRvPZIQB%2B6RNxc%2B%2FIrBt7S4sP4yIW6qy4P86zUnbc3cVfY9I%2BE%2BlwwnWb5dxkVUgjYnouCT%2BorsrqVp45dxJAtxxnvzTfB%2BmR6V4Nt%2F3arPPF50rDqxbJGfoCBSzlY47gdhbKf51prYy0uTSTQzX5iaIGNo23ZHGK5mx8W6ZoXhk2csped4isEKDOODgn0HSuJvvEl7JNO8V3OI2ZsfNjAJ6cVzJkaQl2JLA81nKtf4TqpYJrWoa2o6tK1ozW0%2BzLfMnesKS%2BuLlgryFsGkuNkiNncHBG1h0A75%2FSoo%2FmbOMDsKSelzR0%2Fft0PW%2FD3xEgg0a202%2FtpAscCwi4Rt3QYG4dR%2Btbeoagj6Ne30DpJD9nUK6nOSM5%2FnXjMc6CIbjyBgirsGpXEEbRJIwhcfMgPDD3FQq0loy54OEleDsz%2F%2F2Q%3D%3D%22%20%2F%3E%3Ccircle%20cx%3D%2283.6%25%22%20cy%3D%2283.6%25%22%20r%3D%2212%25%22%20fill%3D%22Red%22%20%2F%3E%3Ccircle%20cx%3D%2283.6%25%22%20cy%3D%2283.6%25%22%20r%3D%2214%25%22%20stroke%3D%22rgba(0%2C0%2C0%2C40%25)%22%20stroke-width%3D%224%25%22%20fill%3D%22rgba(0%2C0%2C0%2C0)%22%20%2F%3E%3C%2Fsvg%3E

**Comment by SuDa2103** [comment]
@mjbvz I have the same issue

**Comment by mjbvz** [comment]
Caused by 863eb4d80acf09ad20bfacc76bea5c3f76a18386
