### ISSUE TITLE
Strange behavior of completion in string

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#131238]
Does this issue occur when all extensions are disabled?: No

版本: 1.60.0-insider (system setup)
提交: 1c445fe4c7c540d323a206f2f7cb8df9aa99d60e
日期: 2021-08-10T23:49:45.206Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 10.0.22000

I am the developer of a extension, I want to complete the file name of the `require`, just like typescript:

![ts](https://user-images.githubusercontent.com/5213431/130192963-e24622a7-43a7-4798-95f0-2951e35538f8.png)

But I found that completion will not work in the string:

![not_work](https://user-images.githubusercontent.com/5213431/130193602-a236135b-a7dd-4f37-83c1-be7f730cc21d.gif)

Then I tried to register letters in `triggerCharacters`, but something strange happened: when I typed letters at the end of the string, completion would not work; but when I typed letters in the middle of the string, completion would work :

![strange](https://user-images.githubusercontent.com/5213431/130193873-f9cc64a9-0440-4dad-a501-b499ba3aa880.gif)

1. Is this strange behavior a bug?
2. Is there a better way to achieve my purpose? Registering all the letters as `triggerCharacters` does not look very graceful.

**Comment by jrieken** [comment]
That's the `editor.quickSuggestions` setting. By default suggestion don't trigger as you type when typing in strings
