### ISSUE TITLE
Syntax-Highlighting differs since Insider 1.60

### ISSUE THREAD

**Issue by Raydir** [microsoft/vscode#131246]
Hey there

I just mentionend that the latest Insider build did mess with the colorization of my syntax-highlithing

Stable 1.59.1
![grafik](https://user-images.githubusercontent.com/17499573/130202016-5aa6494e-206c-4393-b697-e032064cb688.png)

Insider 1.60
![grafik](https://user-images.githubusercontent.com/17499573/130201858-e28f20be-7a29-47ec-8808-f44b719b96a9.png)

Extension for reproduction:
https://marketplace.visualstudio.com/items?itemName=OpaccSoftwareAG.f-script

Any advice / idea on what did change the color of the "guillets"? (« / ») 

Regards
Roman

**Comment by Raydir** [comment]
Also differs on Monokai:
![grafik](https://user-images.githubusercontent.com/17499573/130202657-42e17caa-a6db-4993-a2e6-284808944d5b.png)

**Comment by IllusionMH** [comment]
This is built-in brackets pairs colorization #129231

Also see #131176

**Comment by jaymegordo** [comment]
The bracket colorization could be helpful, but pretty ugly without the ability to customize the colors for each level. Is this available? Currently I just see a setting to turn it off or on.

**Comment by IllusionMH** [comment]
As with syntax highlight -  it's part of theming `editorBracketHighlight.foregroundN` https://github.com/microsoft/vscode/pull/129231#issuecomment-896860315
Please do not hijack other's issues - there are umbrella issues that track this feature e.g. #128465

**Comment by Raydir** [comment]
@IllusionMH 
ahm.. why should one want vscode to override the definied Colors within an extension by default?
should your option "editor.bracketPairColorization.enabled" not be passiv by default?

**Comment by hediet** [comment]
> should the option "editor.bracketPairColorization.enabled" not be passiv by default?

We enabled it temporarily for Insiders to get early feedback before we turn the feature off by default and roll it out to stable.

**Comment by Raydir** [comment]
fine by me, thanx for the responses.

To be clear: 
Me for myself  I do like the feature... i just got several persons "behind" me, that are using my highlighting and those will be questioning me directly ;)

**Comment by hediet** [comment]
Btw. as a theme author, you can customize the colors used for colorizing bracket pairs!
