### ISSUE TITLE
can't use shortcuts

### ISSUE THREAD

**Issue by wing0621** [microsoft/vscode#131298]
We have written the needed data into your clipboard because it was too large to send. Please paste.Hi, 

I'm having an issue while using VS (I'm a newbie, it could totally be me). The shortcut to run the code (control+f5) sometimes works and sometimes doesn't. Same thing happen when I want to "clear" the terminal. I know, it's strange... Any clue what it may be? 

Thank you! 
Antonio

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+F5`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by alexdima** [comment]
@wing0621 The command `Developer: Toggle Keyboard Shortcuts Troubleshooting` needs to be ran in VS Code. You can press `F1` or `ctrl+shift+p / cmd+shift+p` to bring up the command palette in VS Code and execute the command
