### ISSUE TITLE
Add a way to inform users why a command is disabled

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#131205]
While declaring our extensions support for virtual workspaces as "limited", we have disabled some commands via the "enablement" property. The issue is that users may not know why the commands and buttons have been disabled (because of virtual workspaces). It would be great to have a way to inform them. 

Ideas:
* Tooltip that says "<command title> (disabled in virtual workspaces)"
* Notification when they click it explaining that the command is disabled in virtual workspaces

![image](https://user-images.githubusercontent.com/12476526/130137501-c5b55391-d8c1-4709-bc49-74e4126da04d.png)

**Comment by misolori** [comment]
I'd suggest that you update the title information to inform the user of this, we do this in parts of the UI:

<img width="306" alt="CleanShot 2021-10-04 at 15 13 37@2x" src="https://user-images.githubusercontent.com/35271042/135931951-f1596863-ce62-4f1d-bf37-5d8d17633353.png">
