### ISSUE TITLE
Python extension installation failure with XHR  error

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#131272]
Hi there! Since the 1.59 release we got 3 reviews from users saying they can't install the Python extension with a "Extension: Python': XHR timeout: undefinedms." error.  Not sure if the same thing happening with other extensions, but we're not sure what could be happening. https://github.com/microsoft/vscode/issues/127214 and https://github.com/microsoft/vscode/issues/34385 seem to be related, but the error message also seems slightly different? 

The reviews I'm referring to are here: 
  https://marketplace.visualstudio.com/items?itemName=ms-python.python&ssr=false#review-details

**Comment by sandy081** [comment]
/duplicate

Could be a duplicate of https://github.com/microsoft/vscode/issues/130962
