### ISSUE TITLE
Codicon: add an icon that resembles the VS Code logo

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131297]
For the new `welcomeBanner` support in VSCode web I need a Codicon that is the VSCode logo (doesn't really need to be different for insiders vs stable I would say). I couldn't find it in our set currently.

Thanks!

//cc @bamurtaugh @digitarald

**Comment by misolori** [comment]
Is there a reason why we can't use the svgs that get swapped in our builds? If it's a codicon then it won't have the same styling as our logo since it has the gradients/shadows.

**Comment by bpasero** [comment]
That would require support for icons in the welcome banner. @lszomoru I think created that workbench piece. Currently it only allows for codicons.

**Comment by misolori** [comment]
I think I'd be more in favor of doing that since the logo has complex gradients and it would look better than a codicon with a single color that we don't often use.

**Comment by bpasero** [comment]
Ok then I think we can close this.

**Comment by misolori** [comment]
Do we need a separate issue for the banner to support svgs?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/131977
