### ISSUE TITLE
vscode will use more and more memory

### ISSUE THREAD

**Issue by jianweihao** [microsoft/vscode#131223]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: win10 18363

Steps to Reproduce:

1. start vscode
2. coding, compile and debug
3. open Task Manager, vscode use more and more memory

![2](https://user-images.githubusercontent.com/23733835/130163041-17f39dff-abc8-4b15-b039-f8025b14ab3e.png)
![3](https://user-images.githubusercontent.com/23733835/130163047-82282bde-1d1f-4988-94fa-0b3b5ca1914d.png)
![4](https://user-images.githubusercontent.com/23733835/130163056-51407957-e3f9-42f3-8997-76a9cf4c9d4b.png)

**Comment by jianweihao** [comment]
This is the process explorer in vscode.

![5](https://user-images.githubusercontent.com/23733835/130163447-75a0c95c-a599-4b99-976e-4b96fb5ca539.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jianweihao** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Thanks for reply, I will try to reproduce in the next few days.

**Comment by bpasero** [comment]
Ok.
