### ISSUE TITLE
[Bug] VSCode window is blank

### ISSUE THREAD

**Issue by DoranYun** [Microsoft/vscode#13129]
- VSCode Version: 1.5.3
- OS Version: macOS 10.12

Steps to Reproduce:

1. close the window
2. use commandline open VScode
3. the window is blank
4. open devtool, you can see some error

![default](https://cloud.githubusercontent.com/assets/16359169/19018464/2125973a-8895-11e6-9664-a350b5f0791d.png)

5. I must quit VSCode, and restart.
6. This's always happen
7. There are my extensions

![dingtalk20161002114537](https://cloud.githubusercontent.com/assets/16359169/19018474/c1774daa-8895-11e6-801f-420a7f6ccad5.png)

**Comment by bpasero** [comment]
@DoranYun for now I suggest you start using our insider build to see if it reproduces: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
