### ISSUE TITLE
Copying running cells causes run state information to be copied

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131243]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.60.0-insider
Commit: c08913337cb8b95493be8e99d62e0b3241563f6b
Date: 2021-08-19T05:17:33.223Z (1 day ago)

- OS Version: Mac

Steps to Reproduce:

1. Run a cell in a notebook
2. While its running, duplicate the cell
2. Note how the run information is copied over to the new cell (the pasted cell too has a running state)

![recording](https://user-images.githubusercontent.com/1948812/130199234-fa98d057-7739-41b3-bbf0-83b41a44c7bd.gif)

**Comment by roblourens** [comment]
This was fixed last week
