### ISSUE TITLE
Test: terminal location API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#131278]
Refs #45407

- [x] macOS @weinand
- [x] linux @TylerLeonhardt 
- [x] windows @stevencl 

Complexity: 3

Authors: @meganrogge, @tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131278%0A%0A&assignees=meganrogge,tyriar)

---
With proposed API [enabled](https://code.visualstudio.com/api/advanced-topics/using-proposed-api), use the extension-terminal-sample to test the following:

```

	export interface TerminalOptions {
		location?: TerminalLocation | TerminalEditorLocationOptions | TerminalSplitLocationOptions;
	}

	export interface ExtensionTerminalOptions {
		location?: TerminalLocation | TerminalEditorLocationOptions | TerminalSplitLocationOptions;
	}

	export enum TerminalLocation {
		Panel = 0,
		Editor = 1,
	}

	export interface TerminalEditorLocationOptions {
		/**
		 * A view column in which the {@link Terminal terminal} should be shown in the editor area.
		 * Use {@link ViewColumn.Active active} to open in the active editor group, other values are
		 * adjusted to be `Min(column, columnCount + 1)`, the
		 * {@link ViewColumn.Active active}-column is not adjusted. Use
		 * {@linkcode ViewColumn.Beside} to open the editor to the side of the currently active one.
		 */
		viewColumn: ViewColumn;
		/**
		 * An optional flag that when `true` will stop the {@link Terminal} from taking focus.
		 */
		preserveFocus?: boolean;
	}

	export interface TerminalSplitLocationOptions {
		/**
		 * The parent terminal to split this terminal beside. This works whether the parent terminal
		 * is in the panel or the editor area.
		 */
		parentTerminal: Terminal;
	}
```
Also, be sure to test splitting terminals in the editor and panel as that should all still work properly and there were a lot of changes that went into this work.

**Comment by stevencl** [comment]
I expect that this is probably just my misunderstanding of how viewColumn works but I expected this code to create a new terminal in the 4th editor. If I have a 2 x 3 grid of editors (2 rows of 3 columns) I expected this to create a new terminal in the first editor group in the second row. But instead it creates a new terminal next to whatever editor is active.

	context.subscriptions.push(vscode.commands.registerCommand('terminaltest.createTerminal', () => {
		let termEdLocation:vscode.TerminalEditorLocationOptions = {
			viewColumn: vscode.ViewColumn.Four,
			preserveFocus: false
		};
		vscode.window.createTerminal({
			name: `Ext Terminal #${NEXT_TERM_ID++}`,
			location: termEdLocation
		} as any);
		vscode.window.showInformationMessage('Hello World 2!');
	}));

**Comment by weinand** [comment]
@meganrogge for testing the `TerminalSplitLocationOptions.parentTerminal` property, I my extension code passed the `vscode.window.activeTerminal`. Then I noticed that `activeTerminal` only tracks the terminals of the panel, but not the ones from the editor area. If this is the intended behavior, then the comment needs to be updated.

**Comment by meganrogge** [comment]
@Tyriar I debugged and see this happening appropriately when I create a terminal in the editor area or panel or when I focus and switch between them. So not sure how it's not working

```
public async $acceptActiveTerminalChanged(id: number | null): Promise<void> {
		const original = this._activeTerminal;
		if (id === null) {
			this._activeTerminal = undefined;
			if (original !== this._activeTerminal) {
				this._onDidChangeActiveTerminal.fire(this._activeTerminal);
			}
			return;
		}
		const terminal = this._getTerminalById(id);
		if (terminal) {
			this._activeTerminal = terminal;
			if (original !== this._activeTerminal) {
				this._onDidChangeActiveTerminal.fire(this._activeTerminal.value);
			}
		}
	}
```

**Comment by weinand** [comment]
@meganrogge I was using this code in the "helloWorld" command of the standard "hello world" extension:

```ts
		const terminal = vscode.window.createTerminal({
			name: 'august',
			message: 'a message',
			location: {
				viewColumn: ViewColumn.Beside,
				parentTerminal: vscode.window.activeTerminal
			}
		});
```

When running the "helloWorld" command, new terminals are always added to the panel but not to editor area. Maybe my interpretation that "activeTerminal only tracks the terminals of the panel" is wrong...
