### ISSUE TITLE
Notebook markdown cell does not know about my markdown formatter

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#131290]
`Format Document` in a markdown cell does show a dialog about missing formatter, even though I have `Markdown All in One` installed:

![image](https://user-images.githubusercontent.com/8599/130305603-8d5191db-90db-443e-9118-15c8d41e3801.png)

This is annoying as table formatting is amazing and especially useful to summarize tabular data in markdown.

**Comment by mjbvz** [comment]
Please open an issue against that extension. Its formatter is only registered for a few file types so it currently does not apply to notebook cells: https://github.com/yzhang-gh/vscode-markdown/blob/master/src/util/generic.ts#L5
