### ISSUE TITLE
Icons seem blurry

### ISSUE THREAD

**Issue by DumboJetEngine** [Microsoft/vscode#13126]
- VSCode Version: 1.5.3
- OS Version: Win10

All the file-icon extensions that I've tried have their icons shown blurry.
Not sure why, but I guess it has something to do with VS Code itself and its HTML (I would guess you scale the image or something).

Example:

VS Code:
![image](https://cloud.githubusercontent.com/assets/8676903/19016106/b9547da4-8819-11e6-8e7a-d0af8cfcaab9.png)

Brackets (could well be the exact same icon only mirrored, although I am not sure):
![image](https://cloud.githubusercontent.com/assets/8676903/19016109/c862bf68-8819-11e6-8771-f302bfaa22f0.png)

Anyhow, I have tried all icons I could find and they all look as bad as that.

(While we are comparing the two, I like the font Bracket uses too - not sure where they got it... I like many things on VS Code as well. Just pointing out where you could probably improve.)

There are some icons that look a bit better:
![image](https://cloud.githubusercontent.com/assets/8676903/19016236/f20cbb9a-881c-11e6-9592-b0b6e657e4e6.png)

![image](https://cloud.githubusercontent.com/assets/8676903/19016241/0d7a08e2-881d-11e6-8ceb-41dd030b1dfa.png)

Things are improving a bit when not using a zoom:

![image](https://cloud.githubusercontent.com/assets/8676903/19016256/84a1db70-881d-11e6-8f1c-a65874edf903.png)

![image](https://cloud.githubusercontent.com/assets/8676903/19016269/deddbce4-881d-11e6-802f-526b089dda14.png)

You can only see no problem with the "Minimal (Visual Studio Code)" extension :

![image](https://cloud.githubusercontent.com/assets/8676903/19016293/595a622e-881e-11e6-9f9d-1ada7ebd2acf.png)

But if you use zoom, even this gets blurry:

![image](https://cloud.githubusercontent.com/assets/8676903/19016310/afa4e762-881e-11e6-81bb-33bf897fc968.png)

Maybe I want too much. :(

**Comment by aeschli** [comment]
@DumboJetEngine Do you still see this? I can't reproduce that in my setup.
From the screenshot I assume that shows also with the 'Minimal' theme. Is it just the file icons. Or also icons in the VSCode status bar?

**Comment by DumboJetEngine** [comment]
I can still see some blur when using zoom and I have the impression that the icons on the status bar are at better shape:

![image](https://cloud.githubusercontent.com/assets/8676903/22521684/81573b36-e8c1-11e6-8ef5-5ceec3830e1b.png)

It seems that the problem appears whenever the icon gets resized from its original size (even when it is an SVG or a webfont), but it might be just a browser problem or maybe the values for the zoom levels are such that make the pixels of the icons be rendered with anti-alias causing this blur.

It might not be fixable. I see that Brackets has no zoom, only settings for font sizes, so I cannot compare it in equal terms.

I guess that this is a general problem with rendering and that some icon libraries must change their default icons sizes to be 16px (which seems to be what VS Code uses). Then it would at least look nice in normal zoom. And **maybe** choosing the best zoom levels for VS Code (if possible and if it not done already) might help.

**Comment by aeschli** [comment]
We leave it up to Electron (actually Chromium) to do the rendering and I'm, right now, not aware of any tricks to improve the icon rendering.
