### ISSUE TITLE
"propfull" snippet selected before "prop" snippet

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#13123]
- VSCode Version: Code - Insiders 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d, 2016-10-01T00:31:36.133Z)
- OS Version: Darwin x64 16.0.0
- Extensions: EditorConfig.EditorConfig-0.3.3, Shan.code-settings-sync-2.3.1, be5invis.vscode-icontheme-nomo-dark-1.1.3, chenxsan.vscode-standard-format-0.0.12, christian-kohler.npm-intellisense-0.1.3, dbaeumer.vscode-eslint-1.0.7, dbalage.vscode-stylesheet-formatter-0.2.0, dkundel.vscode-npm-source-0.0.3, eg2.tslint-0.5.39, eg2.vscode-npm-script-0.0.20, fknop.vscode-npm-3.3.0, ms-vscode.csharp-1.4.1, ricard.PostCSS-1.0.1, samverschueren.yo-0.8.5, zgudino.editorconfig-vscode-snippet-0.1.0

Steps to Reproduce:

1. In a C# file, type `prop`
2. See that the `propfull` snippet is highlighted, rather than the `prop` snippet, which matches exactly.

![image](https://cloud.githubusercontent.com/assets/594564/19015380/afefcc34-8803-11e6-8022-520adfd0d473.png)

**Comment by joaomoreno** [comment]
#11423
