### ISSUE TITLE
On restart terminal opens with sh rather than zsh

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#131294]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0
Steps to Reproduce:

1. With vscode running with an integrated terminal open, restart my mac
2. After logging in vscode will be started automatically. The integrated terminal will open using /bin/sh

If I reopen the terminal within vscode, or I restart vscode, it will correctly use /bin/zsh

Settings:

`terminal.integrated.shell.osx` is not set
`terminal.integrated.defaultProfile.osx = "zsh"`

UserShell
```
$ dscl . -read ~/ UserShell
UserShell: /bin/zsh
```

**Comment by tekumara** [comment]
Inside the terminal:
```
sh-3.2$ echo $SHELL
/bin/sh
```

If I then reopen the terminal, it'll start with zsh but `SHELL=/bin/sh`.

If I then stop vscode, and start it again, the terminal will be zsh and `SHELL=/bin/zsh`.

So it looks like, only when vscode is started automatically by macos on login will `SHELL=/bin/sh`

**Comment by meganrogge** [comment]
related to https://github.com/microsoft/vscode/issues/125898?
