### ISSUE TITLE
Toggle cell toolbar menu item doesn't do anything when position is defined in settings

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131241]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:	Version: 1.60.0-insider
Commit: c08913337cb8b95493be8e99d62e0b3241563f6b
Date: 2021-08-19T05:17:33.223Z (1 day ago)

- OS Version: Mac

Steps to Reproduce:

1. I have a setting for toolbar position defined as follows:
```json
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "right"
  },
```
2. Click `Customize Notebook` icon & click the `Toggle Cell Toolbar Position` item
3. Nothing happens
<img width="373" alt="Screen Shot 2021-08-20 at 00 20 52" src="https://user-images.githubusercontent.com/1948812/130196146-59a6b7e2-6b03-44ab-bb59-f73d1184dec2.png">

**Comment by rebornix** [comment]
Fixed now and no longer reproduced in latest build.
