### ISSUE TITLE
Debugger AutoLaunching

### ISSUE THREAD

**Issue by kay-stack** [microsoft/vscode#131240]
Issue Type: <b>Bug</b>

Expected result: 

Debugger should only launch on command.
-------------------------------------------------------------------------
Actual result: 

Debugger automatically launches with no interaction while editing any source files. 

Disabling all extensions causes pop-up prompting to install plugin to debug plain-text from Marketplace with no way of dismissing it. When cancel is clicked the pop-up immediately returns making it impossible to take any action including closing VSCode without using the task manager.

![image](https://user-images.githubusercontent.com/57327745/130195235-c9147b5e-c336-4583-b396-ef6db08e5b31.png)
_example of popup with all extensions disabled_

Re-enabling extensions causes the debugger to prompt choosing debugging configuration after an indeterminate delay. Debugger prompt can be dismissed by hitting enter.

When the system is in this state the browser is effectively high-jacked and any content entered in the omnisearch is refreshed and removed.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.39GB free)|
|Process Argv|--crash-reporter-id d40cdb8a-bd29-4792-ab24-70379ef3115b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
npm-intellisense|chr|1.4.0
codestream|Cod|11.0.13
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-mysql-client2|cwe|4.1.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.23
git-extension-pack|don|0.1.3
githistory|don|0.6.18
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
json-pretty-printer|eus|1.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
quasar-extension-pack|fra|1.1.0
vscode-format-context-menu|lac|1.0.4
prettify-json|moh|0.0.3
vscode-attrs-sorter|mrm|2.1.0
vetur|oct|0.34.1
java|red|0.81.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
sass-indented|syl|1.8.18
language-stylus|sys|1.13.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.2
vscode-maven|vsc|0.32.2
vscode-icons|vsc|11.6.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793
vsdyn321cf:30354108

```

</details>

**Comment by gjsjohnmurray** [comment]
Seems to be acting like you pressed the F5 key. Maybe check your keybindings, e.g.

![image](https://user-images.githubusercontent.com/6726799/130199869-7a86edb8-ea50-4f99-8443-5d4c6852cacf.png)

What triggers the start of debugging? Saving the document? Maybe you have enabled autosave. Any custom tasks?

**Comment by kay-stack** [comment]
> Seems to be acting like you pressed the F5 key. Maybe check your keybindings, e.g.
> 
> ![image](https://user-images.githubusercontent.com/6726799/130199869-7a86edb8-ea50-4f99-8443-5d4c6852cacf.png)
> 
> What triggers the start of debugging? Saving the document? Maybe you have enabled autosave. Any custom tasks?

Typically just clicking anywhere within VSCode triggers the debug, I have rolled back my version to Version: 1.58.2 (system setup) and the problem seems to be resolved. 

Debug keybindings are set to default and the debug started automatically with no input from keyboard (mouse click) but there have also been instances when debug started while typing.

![image](https://user-images.githubusercontent.com/57327745/130204060-389f76f5-4d1f-4e32-9a65-5c1a48f311e4.png)
_debug keybinding screenshot_

Presently there is no autosave active in the environment. I typically run "quasar dev" from cli which starts a local dev server but this has never caused an issue in the past.

Thanks so much for your prompt response and assistance :)

**Comment by roblourens** [comment]
Could you run the command "Toggle keyboard shortcuts troubleshooting", and leave that on until the dialog shows up, then share the output here?

**Comment by kay-stack** [comment]
I've updated my VSCode and can't replicate the issue across a couple of different projects. Can I close this thread and reopen at a later stage if it occurs again? Sorry for the inconvenience :)
