### ISSUE TITLE
Strange document URIs in onDidOpenTextDocument callback when workspace is initially loaded

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#131282]
Issue Type: <b>Bug</b>

I see this issue when debugging vscode-go with `--disable-extensions`, so AFAIK the only extension running should be my local development version of vscode-go.

After the extension activates, my `vscode.workspace.onDidOpenTextDocument` callback is called with a TextDocument with a rather strange URI:

```
git:/home/ME/src/runway/internal/geom/face_test.go.git?{"path":"/home/ME/src/runway/internal/geom/face_test.go","ref":""}
```

I expect to see `file:///home/ME/src/runway/internal/geom/face_test.go`. I can add code to handle this:

```typescript
function didOpenCallback(doc: TextDocument) {
	if (doc.uri.scheme === 'git') {
		const { path } = JSON.parse(doc.uri.query);
		doc = await vscode.workspace.openTextDocument(path);
	}

	// ...
}
```

But it seems rather odd. I haven't found any documentation on this.

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.10.27-gentoo
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 4800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.62GB (50.78GB free)|
|Process Argv|--unity-launch --crash-reporter-id 217c2155-7214-48e7-83e7-a2317fced1b9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/wayland-sessions/plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793
vsdyn321cf:30354108

```

</details>

**Comment by jrieken** [comment]
> so AFAIK the only extension running should be my local development version of vscode-go.

The doc about `--disable-extensions` is precise but non obvious. I says disable all installed extensions, so built-in extensions aren't disabled and still running. E.g. in the case git is still active and adding its documents

**Comment by firelizzard18** [comment]
So what I'm seeing is the built-in Git extension calling `vscode.workspace.openTextDocument` for its own purposes?

**Comment by bpasero** [comment]
This is very likely the model git creates for quick diff support in the editor:

![image](https://user-images.githubusercontent.com/900690/130577298-c73f33fc-81a8-4e7b-a13a-5b789652f25d.png)

Ever since Git has adopted a real file system provider, it is resolving real text models that end up in the extension host.

I wonder if we need a way to filter out these models to appear in the extension host?

//cc @joaomoreno

**Comment by firelizzard18** [comment]
It would be nice to have a way to differentiate between real files and text document providers. I want to support things like remote files systems, but scanning virtual files for Go tests is probably not what the user wants. Granted, I check for a `_test.go` suffix, but that’s not a guarantee I won’t get virtual files.
