### ISSUE TITLE
Support displaying annotations in the editor

### ISSUE THREAD

**Issue by trdyer** [microsoft/vscode#131244]
Currently comments that have been added to files/lines are viewable in the editor. It would be great if lint or codeql annotations were also available to be viewed in the same way.

**Comment by sandy081** [comment]
> It would be great if lint or codeql annotations were also available to be viewed in the same way.

Can you please explain what these are?

**Comment by trdyer** [comment]
Hi, a good rundown of what I am thinking of is here: https://github.blog/2018-12-14-introducing-check-runs-and-annotations/

But for clarity it is the feature in github where a linter, test reporter, code coverage tool etc can attach an item (annotation) to a line in a file that can highlight a potential issue, defect or test failure.

**Comment by sandy081** [comment]
@alexdima FYI - not sure who is the right owner here as it involves various editor features . Hence pinging you.
