### ISSUE TITLE
[C/C++] Double quote auto inserted when typing forward slash in include path

### ISSUE THREAD

**Issue by adrian-purser** [microsoft/vscode#131309]
Issue Type: <b>Bug</b>

Start typing a C/C++ include directive up to the end of the first folder. e.g.

#include "somefolder

Type a forward slash. A double quote gets inserted. e.g.

#include "somefolder"/

Expected behaviour -

#include "somefolder/somefile.h"

Actual Behaviour -

#include "somefolder"/somefile.h"

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.10.59-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3566)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (5.64GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 4b251083-758b-430d-aaef-562045a37caa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.29.2
better-cpp-syntax|jef|1.15.6
autoconf|mae|0.1.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
vscode-edge-devtools|ms-|1.3.0
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.7.3
cpptools|ms-|1.6.0-insiders3
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.8.2
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
veriloghdl|msh|1.5.0
vscode-yaml|red|0.22.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
cmake|twx|0.0.17
wavetrace|wav|1.1.2
JavaScriptSnippets|xab|1.8.0
linkerscript|Zix|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793
vsdyn420:30354109

```

</details>

**Comment by aeschli** [comment]
I can't reproduce in a bare VS Code without extension. Is t the C++ extension code completion that does that?
Can you file this against the C++ extension? https://github.com/Microsoft/vscode-cpptools/issues
Thanks!
