### ISSUE TITLE
Show markdown file's outline in preview mode

### ISSUE THREAD

**Issue by tusharsadhwani** [microsoft/vscode#131397]
When viewing the plain-text version of a markdown file, you can see the outline of the file (headings, sub-headings) in the outlines section on the left:

![image](https://user-images.githubusercontent.com/43412083/130439443-d80769ee-8898-4e1f-a01f-b6f95f2f82df.png)

But when watching the preview of the file:
![image](https://user-images.githubusercontent.com/43412083/130439695-6ec3d983-6d4d-4114-96be-3a41cb38ae56.png)

It is no longer visible:
![image](https://user-images.githubusercontent.com/43412083/130439657-c33a7305-17f7-4863-84b8-8ca4bc8578e2.png)

---

It would be very useful to be able to see and navigate through the outline of a markdown file even in the preview.

**Comment by tusharsadhwani** [comment]
@mjbvz could you please link which issue this is a duplicate of?
I don't think #53992 is related.

**Comment by mjbvz** [comment]
#97095
