### ISSUE TITLE
Keep Call Stack closed while running

### ISSUE THREAD

**Issue by cemde** [microsoft/vscode#131388]
VSCode keeps opening the Call Stack during debugging. This makes debugging multiple Apps simultationsly impossible.
For example, I am running `App A` while debugging `App B`. The Call Stack of `App A` keeps expanding everytime a new subprocess is launched or terminated. This makes debugging App B impossible because its call stack jumps up and down in the list.

Suggestion:
A functionality to keep the Call Stack closed upon launching subproccesses, e.g. a button. 

Image:
Callstack keeps going back and forth between the left and right image.
![sceenshot_call_stack](https://user-images.githubusercontent.com/42615086/130415519-28fba291-b682-4b63-84a4-987e0b746637.jpg)

**Comment by weinand** [comment]
The issue that the callstack is expanded whenever a new subprocess is launched should be fixed in Insider (@isidorn correct?).

**Comment by isidorn** [comment]
@weinand yes this should behave better now.
@cemde can you please try this with vscode insiders https://code.visualstudio.com/insiders/
And if it still does not behave well let us know and there might be other things which we could do to further improve this (maybe we should fully respect if a user collapses some node in the tree and not auto expand it anymore)
