### ISSUE TITLE
Cannot connect to codespace 

### ISSUE THREAD

**Issue by adaex** [microsoft/vscode#131306]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0-insider
Commit: 89bbd372f459ce72e9c0b60eb3b26b924f64f62d
Date: 2021-08-20T17:51:40.521Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Open `Remote Explorer`
2. Select a github codespace and click `Connect to Codespace` Button
3. Waiting for a long time without any response or prompt

![recording](https://user-images.githubusercontent.com/29560987/130317930-9b1b5cc6-9e12-490f-a4f8-d47b37d1831c.gif)

**Comment by iBhavesh** [comment]
I am facing the same issue

**Comment by iBhavesh** [comment]
This is a duplicate of #131438  and the issue has been closed might as well close this one

**Comment by adaex** [comment]
OK
