### ISSUE TITLE
Excessive startup time (near-hang), then OK

### ISSUE THREAD

**Issue by mklement0** [Microsoft/vscode#13139]
- VSCode Version: 1.5.3
- OS Version: Win7 Ultimate 32-bit, all Windows updates installed (VMware Fusion 8.5 on OS X 10.11)
- Pristine VSCode installation (no extensions installed, default settings)

Symptoms:

* On launching, only 2 processes show up: `Code.exe` without parameters, and the GPU process (running with `--disable-gpu` to eliminate the latter makes no difference):

![image](https://cloud.githubusercontent.com/assets/588825/19022775/ce9b2a70-88ad-11e6-9ca0-4c25753b7e2b.png)

No window shows up, and the `Code.exe`-without-params process is near 100% for ca. 2.5  minutes, with very little memory activity and virtually no IO (the GPU process shows virtually no CPU or GPU activity); the I/O spike and memory increase at the end is when the window finally opens:

![image](https://cloud.githubusercontent.com/assets/588825/19022777/d326a2e0-88ad-11e6-8db7-6fd60c4f6e69.png)

Once the window is visible, additional `Code.exe` processes appear, CPU activity subsides, and things appear to work normally.

**Comment by bpasero** [comment]
@mklement0 does it reproduce with our insider build? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by mklement0** [comment]
(I assume you meant https://code.visualstudio.com/insiders.)

Yes, the problem still exists in the latest insider build, with startup times now varying between 1 and 5+ minutes(!).

**Comment by bpasero** [comment]
Does it reproduce when you reload a window? If so we could try to produce a CPU profile maybe?

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by mklement0** [comment]
Unfortunately, the problem only occurs on startup. If, by contrast, you create a new window after startup has completed (I assume that's what you meant), the problem doesn't occur.

**Comment by bpasero** [comment]
@mklement0 do you have a slow network connection or maybe are offline when you launch it?

**Comment by mklement0** [comment]
No, I can rule that out. It's a VM, but it has a high-speed Internet connection and everything else in the VM works normally; a Windows 10 VM I run in parallel (using NAT in both cases) does not exhibit the problem.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by mklement0** [comment]
This is what I see in the _PowerShell_ console when I start the `*.exe` directly with `--verbose` (as opposed to the `*.cmd` file):

```none
←[93m[main 3:53:41 PM]←[0m Starting VS Code in verbose mode
←[93m[main 3:53:41 PM]←[0m from: c:\Program Files\Microsoft VS Code Insiders\resources\app
←[93m[main 3:53:41 PM]←[0m args: { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  'open-url': undefined,
  locale: undefined,
  wait: false }
←[93m[main 3:53:44 PM]←[0m IPC#vscode:startCrashReporter
←[93m[main 3:53:44 PM]←[0m IPC#vscode-workbenchLoaded
```

By contrast, starting the `*.cmd` file with `--verbose` shows no output in the developer tools' console at all.

Incidentally, the current insiders build has an extraneous `| cat` in the `*.cmd` file, which, while doing no harm, causes an error message to display in the cmd.exe/PowerShell console: `The syntax of the command is incorrect.`

As an aside, there is no benefit to using `call` in the `*.cmd` file; `setlocal` is automatically scoped to the enclosing batch file, so there's no need to return after invoking the `*.exe` to make an explicit `endlocal` call.

**Comment by bpasero** [comment]
@mklement0 weird, on my Windows 7 the output shows up with the help of cat.exe:

![image](https://cloud.githubusercontent.com/assets/900690/19179428/85412a24-8c5d-11e6-9f1b-8cf223691447.png)

Any idea why it would not work for you? Can you share a screen shot when the error shows up for you?

Btw the output does not show anything suspicious to me...

**Comment by mklement0** [comment]
Oops! My bad: I had a broken `cat` in my `%PATH%` that preempted the one that comes with VSCode (on a side note: the `| cat` looks like a no-op - what is its purpose?).

Generally, I would suggest invoking _embedded_ utilities with _full_ paths so as to avoid such situations.

As for the `--verbose` output looking normal: I forgot to mention (because I only realized right now) that the output doesn't appear until _just before the window appears_; in other words: VSCode is spinning its wheels at full CPU load for a couple of minutes, then the verbose output appears and the window opens.

**Comment by bpasero** [comment]
Ok thanks, I am out of ideas what this issue could be, sorry.

**Comment by bpasero** [comment]
@mklement0 does it reproduce if you run `code --disable-gpu` from the command line?

**Comment by mklement0** [comment]
Yes, it does - adding `--disable-gpu` makes no discernible difference. 

To add to the mystery, I'm now seeming similar, but distinct symptoms in a Windows 10 VM (also run in VMware Fusion): startup is fine, but - intermittently - opening _another_ instance - takes far too long and maxes out the CPU.

P.S.: I'm still curious: what's the purpose of the `| cat` in the startup batch file?

**Comment by bpasero** [comment]
@mklement0 it is needed to get the output to show up when you run from the command line.

I believe this is https://github.com/Microsoft/vscode/issues/13882, lets continue there.
