### ISSUE TITLE
Unable to open file directly

### ISSUE THREAD

**Issue by SANG714** [microsoft/vscode#131352]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

The issue started right after installing the app. The 'open with' option is not available on any folder and thus I am not able to open any folder directly on VS code.  Also I am not able to open the writeup present on the VS code using extensions(currently I am using live server). Please help me regarding this issue.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.3.0-28-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2267)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|3.83GB (0.86GB free)|
|Process Argv|--unity-launch --crash-reporter-id a0524810-6bff-4604-87d5-5a3187fe2e79|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   149	  2444	code main
    0	    39	  2449	   zygote
    0	   102	  2540	     gpu-process
    0	    39	  2450	   zygote
    0	     8	  2452	     zygote
    1	    82	  3077	       window (Issue Reporter)
    0	    55	  2589	   utility
    0	   196	  2614	   window (<!DOCTYPE html> - Documents - Visual Studio Code)
    0	   110	  2707	     extensionHost
    0	    63	  2731	     watcherService
    0	    63	  2787	     searchService
    0	   118	  2694	   shared-process
    0	    59	  2747	     ptyHost
    0	     0	  3132	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  3133	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (<!DOCTYPE html> - Documents - Visual Studio Code)
|    Folder (Documents): 3 files
|      File types: txt(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
vsdyn420:30354109

```

</details>

**Comment by gjsjohnmurray** [comment]
> The 'open with' option is not available on any folder

Is this in your Linux file / folder explorer?

Are you able to start VS Code and then use Open Folder from its File menu?

**Comment by SANG714** [comment]
> > The 'open with' option is not available on any folder
> 
> Is this in your Linux file / folder explorer?
> 
> Are you able to start VS Code and then use Open Folder from its File menu?

Yes, it is in a Linux file/folder explorer.

Yes, I am able to start VS Code and then use open folder from its file menu.
