### ISSUE TITLE
VS Code keeps re-ordering my "last in-focus" window

### ISSUE THREAD

**Issue by altjx** [microsoft/vscode#131366]
If I have 2 windows opened, let's call them Window 1 and Window 2, and let's say I have Window 1 currently in focus. If I alt+tab to another application outside of VS Code, and then alt+tab to get back to VS code, for some reason Window 2 comes in focus. I can visually see Window 1 for a split second, and then Window 2 comes in focus.

It's almost like it doesn't remember which window was in focus prior to shifting to another application, so it just automatically puts window 2 in focus instead of window 1, which is where I originally alt+tabbed out of.

Not sure if this is a setting or something, but I don't have this issue in the non-beta VS Code. Only VS Code - Insiders.

Version: 1.60.0-insider (Universal)
Commit: c08913337cb8b95493be8e99d62e0b3241563f6b
Date: 2021-08-19T05:17:33.223Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0 (macOS Big Sur v11.5.2)

**Comment by bpasero** [comment]
Sounds like https://github.com/microsoft/vscode/issues/131218

**Comment by bpasero** [comment]
Does this still reproduce?
