### ISSUE TITLE
HoverProvider appears in the wrong position

### ISSUE THREAD

**Issue by liby** [microsoft/vscode#131326]
Issue Type: <b>Bug</b>

## Actual behavior

1. when using the rust-analyzer plug-in, it will prompt the error code, the pointer hovering over the wrong code 
2. The hover box appears in the wrong position and does not appear near the pointer

## Expected behavior

- Appear near the pointer

The detailed recording screen can be seen in this [issue](https://github.com/rust-analyzer/rust-analyzer/issues/9974).

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (12.33GB free)|
|Process Argv|--crash-reporter-id e0440de6-b5ea-426f-9ba9-e175b8460637|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
copilot|Git|1.3.2425
rust-analyzer|mat|0.3.715
git-graph|mhu|1.30.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.9.0
vscode-fileutils|sle|3.4.5
guides|spy|0.9.3
code-spell-checker|str|1.10.2
vim|vsc|1.21.6
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn478:30354110

```

</details>

**Comment by gjsjohnmurray** [comment]
> That flashing happens because the error also points to the top of the file, note the `main.rs(1, 1)` in the message, so vscode tries to move the diagnostic hover to the top first and then puts it back down for some reason.
> 
> The main problem here is VScode not handling multi span diagnostics too well which we create from rustc's output as it likes to point over the entire file with its diagnostics.

_Originally posted by @Veykril in https://github.com/rust-analyzer/rust-analyzer/issues/9974#issuecomment-903142860_

@Veykril it may help the VS Code devs understand this issue if you are able to post the JSON of the `Diagnostic` object(s) that Rust Analyzer will be returning in the example given by @liby

**Comment by liby** [comment]
@gjsjohnmurray 

Based on what Veykril has described [here](https://github.com/rust-analyzer/rust-analyzer/issues/9974#issuecomment-903301859), I got the following information and I don't know if it can help.

<details>
<summary>Received notification 'textDocument/publishDiagnostics'</summary>

```
[Trace - 1:27:22 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Volumes/Code/Play/gui/src/main.rs",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 3,
                    "character": 17
                },
                "end": {
                    "line": 3,
                    "character": 23
                }
            },
            "severity": 1,
            "code": "E0422",
            "codeDescription": {
                "href": "https://doc.rust-lang.org/error-index.html#E0422"
            },
            "source": "rustc",
            "message": "cannot find struct, variant or union type `Screen` in this scope\nnot found in this scope",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///Volumes/Code/Play/gui/src/main.rs",
                        "range": {
                            "start": {
                                "line": 0,
                                "character": 0
                            },
                            "end": {
                                "line": 0,
                                "character": 0
                            }
                        }
                    },
                    "message": "consider importing this struct: `use gui::Screen;\n`"
                }
            ]
        },
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "severity": 4,
            "code": "E0422",
            "codeDescription": {
                "href": "https://doc.rust-lang.org/error-index.html#E0422"
            },
            "source": "rustc",
            "message": "consider importing this struct: `use gui::Screen;\n`",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///Volumes/Code/Play/gui/src/main.rs",
                        "range": {
                            "start": {
                                "line": 3,
                                "character": 17
                            },
                            "end": {
                                "line": 3,
                                "character": 23
                            }
                        }
                    },
                    "message": "original diagnostic"
                }
            ]
        },
        {
            "range": {
                "start": {
                    "line": 14,
                    "character": 21
                },
                "end": {
                    "line": 18,
                    "character": 13
                }
            },
            "severity": 1,
            "code": "E0308",
            "codeDescription": {
                "href": "https://doc.rust-lang.org/error-index.html#E0308"
            },
            "source": "rustc",
            "message": "mismatched types\nexpected struct `SelectBox`, found struct `Button`"
        }
    ],
    "version": 1
}
```
</details>

**Comment by alexdima** [comment]
This has been fixed in the meantime via https://github.com/microsoft/vscode/issues/151235
