### ISSUE TITLE
Can't find extension st

### ISSUE THREAD

**Issue by ViperBling** [microsoft/vscode#131359]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59.1
- OS Version:Windows 10 21H1

Steps to Reproduce:

can't find extension setting in setting panel
![无标题](https://user-images.githubusercontent.com/17715149/130361234-8b551981-8e12-4ed1-ba0b-49ec53180b37.png)

**Comment by roblourens** [comment]
Are there any errors in the devtools console? (Help > Toggle developer tools)

**Comment by ViperBling** [comment]
> Are there any errors in the devtools console? (Help > Toggle developer tools)

Nope, I just open the editor, and click the settings panel, and there's nothing....

My VSCode verison is VSCodeSetup-x64-1.59.1, and I had tried both user version and system version. Both of them don't have any extension settings.

**Comment by roblourens** [comment]
Do you have extensions installed? Can you try starting with `--disable-extensions` to see whether one of them is breaking the editor?

**Comment by ViperBling** [comment]
> Do you have extensions installed? Can you try starting with `--disable-extensions` to see whether one of them is breaking the editor?

It's weird that when I disabled extension, settings of extensions appeared, but only few of my all extensions. when I enable extensions, and settings of extensions disappeared again.

this pic is the settings when I disable extensions:
![image](https://user-images.githubusercontent.com/17715149/130799046-face5902-175d-49da-9dcb-4ff884cecf2d.png)

this is all extensions I have:
![image](https://user-images.githubusercontent.com/17715149/130799137-cb603648-9f6c-4220-82f2-7e3ce9630ba9.png)

**Comment by roblourens** [comment]
@aeschli do you know why I don't get a validation error if I change the type of `description` on a setting to something besides a string? It seems like that is what the schema requires.
