### ISSUE TITLE
the text in tree ''' doesn't hide in def

### ISSUE THREAD

**Issue by Mehtar21** [microsoft/vscode#131337]
![image](https://user-images.githubusercontent.com/89327929/130340527-b8f60a0c-94e5-4a8a-97da-a8931d104c58.png)

when I hide the def , the text doesn't hide. in here i tried with tab and move text to right but then it had 4 spaces when it was sent.

**Comment by gjsjohnmurray** [comment]
What programming language are you coding in?

It looks like VS Code is using its default indent-based folding.

**Comment by Mehtar21** [comment]
I'm using python.
nearly all my VS Code is on its default.

**Comment by gjsjohnmurray** [comment]
Did you install any Python language extensions?

**Comment by Mehtar21** [comment]
where should I know?
I usually install libraries.
