### ISSUE TITLE
Inserting tabs causes Code to stop responding.

### ISSUE THREAD

**Issue by cnswico** [Microsoft/vscode#13137]
- VSCode Version: 1.5.3
- OS Version: Windows 10 x64 Pro (build 10586)

Steps to Reproduce:
1. Create a `.css` file.
2. Use `tab` inside CSS comments.

**Comment by mrmlnc** [comment]
@cnswico, please, provide GIF or a small code example where occurs described problem.

**Comment by Tyriar** [comment]
Could be related to emmet, CSS intellisense, editor?

**Comment by sandy081** [comment]
Closing this as there is no response
