### ISSUE TITLE
Show dicts and other types properly

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode#131367]
One of the biggest features of Spyder, is that the Variable explorer can show correctly various types of Python and is able to keep opening then when they are nested.

```
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
aaa={'a':'string',
     'b':100,
     'c':np.array([1,2,3]),
     'd':{'e':[1,2,3,4]},
     'f':scaler}
```

![image](https://user-images.githubusercontent.com/68517641/130369485-f61a676e-7e40-4070-9b82-1f6147ef2d5b.png)
![image](https://user-images.githubusercontent.com/68517641/130369523-e50dbd33-0263-4db9-b977-371774d7a1c1.png)

When I try to do the same in VSCode:

![image](https://user-images.githubusercontent.com/68517641/130369546-07aa53c0-22af-4e27-9088-20aec5590ca2.png)

**Comment by Zhangyongtao123** [comment]
@alandema what's the name of this extension for showing types of variables in VSCode?

**Comment by weinand** [comment]
@Zhangyongtao123 a language's debugger extension is responsible for showing the variables of the language.
In this case, it seems to be Python.

**Comment by alandema** [comment]
Hello @Zhangyongtao123 . The extension I mentioned is the Jupyter extension to work with the Python extension.
