### ISSUE TITLE
[FR] Wrap selected content with quotes in all files

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131347]
I noticed some files like `COMMIT_EDITMSG`, `.gitignore` etc. don't allow wrapping content with quotes:

![STG 2021-08-22 16_46_20](https://user-images.githubusercontent.com/28700378/130348494-0ffd52a0-d4e9-4ed4-9971-76365cc3c06b.gif)

While a plain `foo` file allows that:

![STG 2021-08-22 16_36_56](https://user-images.githubusercontent.com/28700378/130348111-c304d7ea-cbca-4d98-8705-7e7b2c4afe6f.gif)

Can we add the option to enable all files with this feature?

**Comment by aeschli** [comment]
For that the quotes need to be added ad autoClosingPairs in git language configurations files at https://github.com/microsoft/vscode/tree/main/extensions/git/languages
(If it makes sense)

**Comment by wenfangdu** [comment]
@aeschli Can we do that in the `settings.json` or must via an extension?

**Comment by aeschli** [comment]
This can't be done in settings. The feature request for that is: https://github.com/microsoft/vscode/issues/102574

**Comment by wenfangdu** [comment]
@aeschli I've submitted a PR for it:

- https://github.com/microsoft/vscode/pull/131403

**Comment by lszomoru** [comment]
Verification steps:
1. Launch the latest VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Make a change to a file, and press the "Commit" button (do not enter a commit messages)
4. This will open the COMMIT_EDITMSG file
5. Type in a word, select it, and type `"`
    * Confirm that the word has been wrapped in `"`

**Comment by wenfangdu** [comment]
@lszomoru Verified.
