### ISSUE TITLE
Format cell context menu item does nothing in notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131342]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Create a Jupyter notebook (or other)
2. Add a cell (typescript/javascript)
3. Right click on the cell & select `Format Cell`, note how nothing happens.
4. Select the context menu item `Format Notebook` and note how the cells are formatted.

**Comment by roblourens** [comment]
Did you mean the other way around? For me, Format Cell works but Format Notebook doesn't

**Comment by roblourens** [comment]
Seems like vscode does the right thing and we just don't get formatting edits (I think from the Python extension)

**Comment by roblourens** [comment]
I think we aren't applying the edits correctly

![Aug-31-2021 09-15-45](https://user-images.githubusercontent.com/323878/131539953-180dc680-bd5d-490b-9f6f-569cea2d028b.gif)

**Comment by roblourens** [comment]
Actually no, I think the problem is in the python extension handling the cell URI wrong

**Comment by roblourens** [comment]
Filed https://github.com/microsoft/vscode/issues/131342

**Comment by DonJayamanne** [comment]
I can repro this outside non-jupyter notebooks.

**Comment by roblourens** [comment]
Which formatter?

**Comment by DonJayamanne** [comment]
Aaaah, so its the individual formatter. Ok
Then its caused by prettier.
