### ISSUE TITLE
Perl syntax highlighting issue - s{foo}{bar} if $baz;

### ISSUE THREAD

**Issue by NorthboundTrain** [microsoft/vscode#131322]
Issue Type: <b>Bug</b>

Perl's regex operators can use any pair of matching characters as delimiters (see https://perldoc.perl.org/perlop#Regexp-Quote-Like-Operators). When using a bracketing character as the delimiter, e.g. `({[`, then the matching closing bracket can be used to close the operator, e.g. `m<foo>` or `s{foo}{bar}`. The bug only occurs when using the substitution operator (`s///`), and only when using bracketing delimiters, and only with a statement modifier (a trailing `if`, `while`, etc).

<img width="813" alt="Screen Shot 2021-08-21 at 12 25 02 PM" src="https://user-images.githubusercontent.com/2432691/130328509-91ccfd4a-e51f-4098-b647-5ff7e2a8ae10.png">

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.12GB free)|
|Process Argv|--crash-reporter-id 90d0d44f-9a2d-4c6d-8a76-8104cbdd8a55|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
spellright|ban|3.0.60
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
vscode-markdownlint|Dav|0.43.2
vscode-simpler-icons|dav|1.6.5
shebang-language-associator|dav|1.1.1
gitlens|eam|11.5.1
permute-lines|ear|1.1.0
prettier-vscode|esb|7.1.1
code-runner|for|0.11.5
perl-outline|hit|0.0.7
bats|jet|0.1.7
vsc-space-block-jumper|jmf|1.2.2
jq-syntax-highlighting|jq-|0.0.2
bash-ide-vscode|mad|1.11.0
python|ms-|2021.5.926500501
vscode-pylance|ms-|2021.7.7
jupyter|ms-|2021.6.999406279
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
oracledevtools|Ora|19.3.4
jq-vscode|pet|0.1.3
remote-vscode|raf|1.1.0
rehydrate|Lla|0.0.2
vscode-workspace-switcher|sad|1.15.3
rewrap|stk|1.14.0
shellcheck|tim|0.15.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723cf:30351748

```

</details>

**Comment by alexr00** [comment]
@NorthboundTrain can you please provide a code snippet that repos the issue that I can copy/paste for testing?

**Comment by NorthboundTrain** [comment]
Thanks for the help!

```perl
s/foo/bar/; # OK
s/foo/bar/ unless $baz; # OK
s/foo/bar/ if $baz; # OK

s{foo}{bar}; # OK
s{foo}{bar} if $baz; # BROKEN
# lasts until a scalar variable is given; neither an @array nor a %hash works,
# but the $scalar does (but the remainder of the line is still FUBAR)
# next line is OK, though

s(foo)(bar) if $baz; # BROKEN - $clear;
s[foo][bar] if $baz; # BROKEN - $clear;
s<foo><bar> if $baz; # BROKEN - $clear;
s:foo:bar: if $baz; # OK
s#foo#bar# if $baz; # OK

# other statement modifiers
s(foo)(bar) for $baz; # BROKEN differently
s(foo)(bar) foreach $baz; # BROKEN - $clear
s(foo)(bar) unless $baz; # OK
s(foo)(bar) until $baz; # BROKEN differently
s(foo)(bar) when $baz; # BROKEN differently
s(foo)(bar) while $baz; # BROKEN differently

# other regex/quote-like operators are OK:
m/foo/ if $baz; # OK
m{foo} if $baz; # OK
q/foo/ if $baz; # OK
q{foo} if $baz; # OK
qq/foo/ if $baz; # OK
qq{foo} if $baz; # OK
qw/foo/ if $baz; # OK
qw{foo} if $baz; # OK
```

**Comment by alexr00** [comment]
Thanks, I can reproduce the issue. We get our perl syntax highlighting grammar from https://github.com/textmate/perl.tmbundle. I've moved the issue there: https://github.com/textmate/perl.tmbundle/issues/49
