### ISSUE TITLE
Default settings deprecation warning with `\n` breaks the json

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#131345]
1. Install https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens
2. Open default json settings editor `workbench.action.openRawDefaultSettings`
3. Deprecation warning is shown as comment, but `\n` introduces errors:

![Screenshot (214)](https://user-images.githubusercontent.com/9638156/130347551-4e984a39-feae-478a-9e11-6ee828aaee2d.png)

https://github.com/usernamehw/vscode-error-lens/blob/9daae8eb8b03ed5bbe37c9186a9eee6289b71b34/package.json#L199-L204

**Comment by usernamehw** [comment]
I have removed the newlines from the `Error Lens` extension, but the issue is still likely there.

**Comment by rzhao271** [comment]
Verification steps:
1. In a new or existing extension, add a setting with a `deprecationMessage` field that has at least one newline in it.
2. Debug/run the extension, open the default json settings editor `workbench.action.openRawDefaultSettings`, and search for that setting.
3. The deprecation message should all be in comments, and there should be no syntax errors in the file.
