### ISSUE TITLE
les fichiers html sont reconnus comme des fiichiers texte

### ISSUE THREAD

**Issue by kkkyy02D** [microsoft/vscode#131371]
Issue Type: <b>Feature Request</b>

Quand je crée un fichier html, il n'est plus reconnu comme un fichier html
l'image a gauche du nom du fichier reste l'image d'un fichier texte et du coup il n'est plus reconnu comme un fichier html malgré l'extension  '.html' quand j'ouvre le fichier et je tape '!' il ne le remplis plus avec du code html, il le considère désormais  comme un fichier texte, j'ai dû touché une configuration quelconque sans faire exprès et cela a changé le comportement de Visual studio code, pourtant, il  reconnait bien les fichiers javascript,, il les colore et pas les fichiers html qui restent gris
que s'est-il passé ?

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Google translate:
When I create an html file, it is no longer recognized as an html file
the image to the left of the file name remains the image of a text file and suddenly it is no longer recognized as an html file despite the '.html' extension when I open the file and type '! ' it no longer populates it with html code, it now considers it as a text file, I must have touched some configuration without doing it on purpose and this changed the behavior of Visual studio code, however, it recognizes javascript files well, , it colors them and not the html files which remain gray
What happened ?

**Comment by aeschli** [comment]
- check you user settings. `files.associations` might have been set to associate html files with something selse
- run with extensions disabled (Command: Reload with Extensions Disabled) find out if an extension causes this.

**Comment by aeschli** [comment]
Closing the issue as there was no resonse.
