### ISSUE TITLE
we cannot connect eith extention market place at this time

### ISSUE THREAD

**Issue by Swapnil0102** [microsoft/vscode#131307]
Issue Type: <b>Bug</b>

we cannot connect eith extention market place at this time

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx   (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.44GB (0.36GB free)|
|Process Argv|--crash-reporter-id 7340cb75-829f-43eb-a316-f74d99dbffb7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
Can you please open developer tools (`F1 > Developer: Toggle Developer Tools`) and see if there are any errors in the console?
