### ISSUE TITLE
(Suggestion on syntax highlighting) Offer a setting for comments to appear in italics

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#13134]
- VSCode Version: 1.5.3
- OS Version: win10 x64

My suggestion on syntax highlighting is offer a setting ( in Preferences|User Settings.) 
for comments to appear in _italics_.

It's a feature I've noticed in Atom's default theme and I like it a lot, 
so I've modified Sublime Text's default color scheme (Monokai) to also show comments in italics. 
It helps the user focus on the actual code better, visually ignoring the comments.

**Comment by Tyriar** [comment]
Themes can currently do this, you should just shop around for a theme that does it or make your own.

**Comment by darkred** [comment]
@Tyriar Alright. So, I've downloaded the `.tmTheme` for the third-party `Flatland Monokai` theme (from its repo), edited it and made it a package with `yo code`.

Is the `.tmTheme` for the default theme, `Dark+`  available?
Is this https://github.com/Microsoft/vscode/blob/80f8000c10b4234c7b027dccfd627442623902d2/extensions/theme-colorful-defaults/themes/dark_plus.tmTheme
its most recent version?

I couldn't find it neither inside "C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions`,
nor by searching in this repo.

**Comment by Tyriar** [comment]
You're pinned to a pretty old commit there, here is the file on the master branch: https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json

Notice that it also includes `dark_vs.json` so you'll also need that file.

**Comment by darkred** [comment]
Thank you for the quick answer.



So, what I do is:
- rename  
dark_plus.json to `dark_plus.tmTheme` and   
dark_vs.json to `dark_vs.tmTheme`.
- modify inside `dark_vs.tmTheme`  
this
```
		{
			"scope": "comment",
			"settings": {
				"foreground": "#608b4e", 
			}
		},
```
into
```
		{
			"scope": "comment",
			"settings": {
				"foreground": "#608b4e", 
				"fontStyle": "italic"
			}
		},
```
- copy `dark_plus.tmTheme` in a new folder,
- run a Command Prompt in that folder and start 'yo code',
- select `New color theme`
- in the 'URL or file name' question type this `dark_plus.tmTheme`  
and complete the rest questions by entering names/identifier/etc for the new package
- when it finishes creating the package folder, e.g. mypackage,  
copy `dark_vs.tmTheme` into  `mypackage\themes`.  
- copy the entire package `mypackage` folder into `C:\Users\User\.vscode\extensions`  
and launch VSCode.
- Now select the new theme in FIle|Preferences| Color Theme:   
- **unfortunately I get** `Problem loading theme: {0}`


Could you please tell me what I am doing wrong?

**Comment by Tyriar** [comment]
Do not change it from json to tmTheme. You should be pointing your extension at the json theme file. Try:

- Generating a new theme
- Copying dark_vs.json and dark_plus.json to your theme
- Pointing package.json to dark_plus.json

I would expect that to read in dark_plus.json without any problems, you can add italic from there.

**Comment by darkred** [comment]
I had tried without renaming it from json to tmTheme
but it renames them in .json.tmTheme in the new package folder\themes.

Anyway, I tried that. following your instructions, i.e.:
- added the following inside`dark_plus.json :
```
		{
			"scope": "comment",
			"settings": {
				"foreground": "#608b4e", 
				"fontStyle": "italic"
			}
		},
```
- copy `dark_plus.json` in a new folder,
- open a Command Prompt window in that folder and start 'yo code',
- select `New color theme`
- in the 'URL or file name' question type this `dark_plus.json`  
and complete the rest questions by entering names/identifier/etc for the new package
- when it finishes creating the package folder, e.g. mypackage,  
copy `dark_vs.json` into  `mypackage\themes`.  
Also notice that inside `mypackage\themes` the filename now is `dark_plus.json.tmTheme`
- notice in package.json that it already points to `dark_plus.json`, i.e.
`path": "./themes/dark_plus.json.tmTheme"`
- copy the entire package `mypackage` folder into `C:\Users\User\.vscode\extensions`  
and launch VSCode.
- Now select the new theme in FIle|Preferences| Color Theme:   

**Unfortunately I still get** `Problem loading theme: {0}`

---

For reference, here is the dark_plus theme I used in yo code:

```
{
	"name": "Dark+",
	"include": "./dark_vs.json",
	"settings": [
		{
			"scope": "comment",
			"settings": {
				"foreground": "#608b4e",
				"fontStyle": "italic"
			}
		},
		{
			"name": "Types declaration and references",
			"scope": [
				"meta.type.name",
				"meta.return.type",
				"meta.return-type",
				"meta.cast",
				"meta.type.annotation",
				"support.type",
				"entity.name.class",
				"entity.name.type",
				"storage.type.cs",
				"storage.type.java"
			],
			"settings": {
				"foreground": "#4EC9B0"
			}
		},
		{
			"name": "Function declarations",
			"scope": [
				"entity.name.function",
				"entity.name.method"
			],
			"settings": {
				"foreground": "#DCDCAA"
			}
		},
		{
			"name": "Control flow keywords",
			"scope": "keyword.control",
			"settings": {
				"foreground": "#C586C0"
			}
		},
		{
			"name": "Variable and parameter name",
			"scope": [
				"meta.parameter.type.variable",
				"variable.parameter",
				"variable",
				"variable.name"
			],
			"settings": {
				"foreground": "#9CDCFE"
			}
		},
		{
			"name": "CSS property value",
			"scope": [
				"support.property-value",
				"constant.rgb-value",
				"support.property-value.scss",
				"constant.rgb-value.scss"
			],
			"settings": {
				"foreground": "#CE9178"
			}
		}
	]
}
```
and here is the `package.json` is like this:
```
{
    "name": "darkplus",
    "displayName": "darkplus",
    "description": "Dark+ modified",
    "version": "0.0.1",
    "publisher": "darkred",
    "engines": {
        "vscode": "^1.5.0"
    },
    "categories": [
        "Themes"
    ],
    "contributes": {
        "themes": [
            {
                "label": "Dark+ modified",
                "uiTheme": "vs-dark",
                "path": "./themes/dark_plus.json.tmTheme"
            }
        ]
    }
}
```

PS. Sorry for the lenthy post, I but I've made various attempts and I can't find out what the problem is.

**Comment by Tyriar** [comment]
You should test the theme before applying your change to narrow down the issue. Once you do this you can check the dev tools (Help > Toggle Developer Tools) console for more information on the error.

**Comment by darkred** [comment]
No error (in fact no info) appears in console when I try to switch to my modified theme.
and I get `Problem loading theme: {0}`
And, I've even checked the modified `dark_plus.json.tmTheme` http://jsonlint.com/
and it is valid.

If' you'd like, please check the ZIP I've uploaded.
I'm suspect that maybe the modified theme (as a separate package) doesn't work
because it links to another file (` dark_vs.json`), i.e. it's not stand alone.

**Comment by Tyriar** [comment]
Just rename the tmTheme to json and link to the json file in package.json. 

![image](https://cloud.githubusercontent.com/assets/2193314/19127344/68724f06-8af3-11e6-9a07-6e2e2bc1d912.png)

**Comment by darkred** [comment]
Thank you. It works now.
