### ISSUE TITLE
Actions in QuickPickItem should always be top alligned

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#131398]
<img width="472" alt="capture" src="https://user-images.githubusercontent.com/1931590/130446051-352a3151-9ac3-462e-aa77-7cdd40837ab8.png">

**Comment by TylerLeonhardt** [comment]
I think they look nice centered in the quick pick item. Any particular reason for this feedback?

**Comment by dbaeumer** [comment]
I think they don't look nice :-), especially since the second line is rendered slightly dimmed.

**Comment by jilljac** [comment]
This suggestion looks like it's in line with the documented design intent from @misolori in the VS Code design toolkit. The actions and shortcuts should be aligned with the primary text of the option. This makes the position stable whether the second line of supporting text is shown or not :) 
![image](https://user-images.githubusercontent.com/60361194/130665561-6b75266f-7f5f-4b71-b16b-47a740963c0a.png)

**Comment by Tyriar** [comment]
Yeah top aligned looks like it fits more imo

**Comment by misolori** [comment]
I think another reason for top right alignment is that when hovering over items, the action will always be in a consistent spot.

**Comment by TylerLeonhardt** [comment]
I think I'm use to seeing them center aligned because of Teams:
![image](https://user-images.githubusercontent.com/2644648/131724961-fc6fec6b-757d-49aa-9422-cacf34585122.png)

**Comment by misolori** [comment]
Another example where we have multi-lines and actions shown is in notifications:

<img width="466" alt="CleanShot 2021-09-01 at 12 04 53@2x" src="https://user-images.githubusercontent.com/35271042/131729183-1d491f08-b565-4665-bf1d-08e032d4848b.png">

**Comment by chrisdias** [comment]
LGTM
