### ISSUE TITLE
Intellisense doesn't work anymore

### ISSUE THREAD

**Issue by xMaxximum** [microsoft/vscode#131383]
Issue Type: <b>Bug</b>

Intellisense simply stopped working after updating to the newest version and I don't know what's causing this since I didn't change any settings at all. Googling the problem and following the troubleshoot steps also didn't help

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.52GB free)|
|Process Argv|C:\\code\\js\\astrea --crash-reporter-id 67ffa095-349f-402e-b0f7-d7f992e7dd8f|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
rust-launcher|duf|1.0.0
rust-syntax|dus|0.6.0
prettier-vscode|esb|8.1.0
vscode-yarn|gam|2.0.0
vscode-pull-request-github|Git|0.29.2
go|gol|0.27.1
discord-vscode|icr|5.7.0
rust-assist|moo|0.2.3
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
python|ms-|2021.8.1147840270
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
remote-wsl|ms-|0.58.2
vetur|oct|0.34.1
material-icon-theme|PKi|4.9.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
rust|rus|0.7.8
crates|ser|0.5.9
svelte-vscode|sve|105.3.4
rust-pack|Swe|0.2.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn420:30354109

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

/needsMoreInfo

**Comment by xMaxximum** [comment]
Well I was using it with javascript

**Comment by mjbvz** [comment]
Please describe the problem and share steps to reproduce it

**Comment by xMaxximum** [comment]
So I just updated to the newest version of vscode and then simply the intellisense stopped working. Before I would get intellisense for libraries like discord.js or express, and now I simply don't anymore. What I mean by intellisense is you get a few functions like .connect() or .on() and those don't show up anymore.

I even tried reinstalling and the issue still persists

**Comment by mjbvz** [comment]
Please share a minimal, self contained code sample that demonstrates the problem
