### ISSUE TITLE
[FR] Double clicking tab -> maximise view

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode#131332]
Issue Type: <b>Feature Request</b>

Based on Eclipse, when we **double click a file tab**, we could hide 

- side panels
- bottom console 

To focus on one file. (but not zen mode, maybe optionally)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mrx23dot** [comment]
Sorry for the duplicate, neither VS bug report window, nor bot here showed a another existing one.
Cheers

**Comment by gjsjohnmurray** [comment]
No problem. Duplicates aren't always easy to find.
