### ISSUE TITLE
All table cells in HTML output of notebooks are right aligned even for non-jupyter notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131339]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Create jupyter notebook with the following cell:
```html
%%html
<table>
    <thead>
        <tr>
            <td>
                Heading should be left aligned
            </td>
            <td>
                Heading should be left aligned
            </td>
        </tr>
    </thead>
    <tr>
        <td>
            Cell
        </td>
        <td>
            Cell
        </td>
    </tr>
</table>
```
2. Run the cell and observe the output.

Note: this applies to all notebooks (Jupyter doesn't inject any sytyles). I've tested this with another non-jupyter notebook and found this same problem.

**Note: I have a notebook that runs Tensorflow js and the output of tensorflowjs contains some HTML & all of the data seems to be right aligned (which is wrong).**

This seems to be the faulty code
https://github.com/microsoft/vscode/blob/f0edba3e02b4ce5be481b39740e2b32d1fa979cb/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L309-L312

<img width="360" alt="Screen Shot 2021-08-21 at 20 27 28" src="https://user-images.githubusercontent.com/1948812/130341107-d068c14a-cbe4-4fd0-bd48-df02bbc1fcf1.png">

**Comment by misolori** [comment]
Yes, this is intentional as Jupyter right-aligns everything:

<img width="764" alt="CleanShot 2021-08-30 at 15 27 02@2x" src="https://user-images.githubusercontent.com/35271042/131414344-18457f29-df3f-4b50-9242-f13981d1d6df.png">

**Comment by DonJayamanne** [comment]
But when creating any other notebook, all the cells are right aligned.
i'm creating a non-jupyter notebook, but the cells are right aligned, 
i.e. i dont think Jupyter notebook styles should dictate styles for all notebooks. 

Will update the title accordingly.

**Comment by misolori** [comment]
Ah, I do see your point. If we're able to determine what kind of notebook it is we could place a class selector on the output that would then dictate the layout alignment.

**Comment by DonJayamanne** [comment]
I personally think a better solution is for Jupyter notebooks to inject a CSS in their preload script to add this style (right align all table cells).
This way, jupyter notebooks will always be left aligned & all other notebooks will be left to their defaults.

@rebornix /cc

**Comment by DonJayamanne** [comment]
Closing this for now, as there haven't been any upvotes on this
