### ISSUE TITLE
Scala Intellisense stops working if there is a match statement in the code somewhere below the line being entered

### ISSUE THREAD

**Issue by Wonderer0** [microsoft/vscode#131335]
Issue Type: <b>Bug</b>

Scala Intellisense stops working if there is a `match` statement in the code somewhere below the line being entered, unless it is immediately followed by a `val` or `var` declaration.  This can be shown by the following experiment.

Type in code the code below in 4 stages, after each stage try typing `msg.` to see if Intellisense is still working, then delete `msg.`

1. When there isn't a `match` statement below `msg.` Intellisense prompts as soon as the `.` is entered.

1. After the `match` statement is added Intellisense doesn't give any prompts, but does show the correct type info.

1. Adding a `val` or `var` between `msg.`and the `match` makes Intellisense work OK again.

1. Adding another statement between `msg.` and the `val` stops it from working again.

```
@main def hello: Unit = {
  val msg = "Hello world!"
  val opt: Option[String] = Some("thing") 
  // (1) Intellisense works when nothing below msg.
  
  msg.
  
  println("It stops again") // (4) Adding this line stops it again.
  val x = "It works again"  // (3) Adding this line makes it work again

  opt match {               // (2) Adding match stops Intellisense
    case Some(value) => println(opt)
    case None          =>
  }
}
```
Intellisense prompting is a lot less reliable for Scala than JS.  Sometimes it stops working completely for no apparent reason, and somtimes only prompts after a few characters have been entered after the `.`.  However this does seem to be a reproducable bug, which might perhaps throw light on other problems.

I am a newbie to Scala and Java, and their build environments, so would appreciate any help if this isn't a bug but something in my setup.

This was tested using the following software, running in Windows 10:

* VSCode: v1.60.0-insider
* Extensions:
    * Scala (Metals): v1.10.8
    * Scala Syntax (official:): v0.5.4
    * Language Support for Java(TM) by Red Hat: v0.81.0
* Scala 3.0.1, installed by Coursier.

`bloop.settings.json` has:  `"semanticDBVersion": "4.4.24"` and the highest `supportedScalaVersions` is `2.13.6`.  I tried adding `3.0.1` and running 'Import build', but this didn't fix it.

The project was created in VSCode 1.59.1 as a "scala/scala3.g8" project by Metals, but now re-tested using the insider version.

VS Code version: Code - Insiders 1.60.0-insider (89bbd372f459ce72e9c0b60eb3b26b924f64f62d, 2021-08-20T17:51:50.560Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3311)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.74GB free)|
|Process Argv|--crash-reporter-id 0b712d9a-33ab-48d3-88b8-dbfecc832bf0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.81.0
scala|sca|0.5.4
metals|sca|1.10.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187cf:30356035

```

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Scala functionality provided by extension and looks like it's problem with language service rather than VS Code editor itself.

Please report in corresponding extension repo
