### ISSUE TITLE
powershell isnt responding

### ISSUE THREAD

**Issue by refaee94** [microsoft/vscode#131330]
Issue Type: <b>Bug</b>

powershell isnt responding when i start VS code and i cannot type anything

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.34GB free)|
|Process Argv|--crash-reporter-id e5b316d2-408a-45ad-ad19-54561c554670|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.2.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
csharp|ms-|1.23.14
powershell|ms-|2021.8.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.9.0
material-theme|zhu|3.11.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
javagetstartedc:30351792
vsdyn478:30354110

```

</details>

**Comment by meganrogge** [comment]
Let me know if you can repro this issue in insider's with all of your extensions disabled. If so, please provide me with your terminal settings and let me know if there are any errors in the dev tools console.
