### ISSUE TITLE
Trace/breakpoint trap (core dumped) when using code command in terminal

### ISSUE THREAD

**Issue by hpcdgrie** [microsoft/vscode#131384]
Issue Type: <b>Bug</b>

I can start and use vs code and vs code insiders using the gui icons, but if i use the command line command code (code-insiders) with any parameters I always get the message "Trace/breakpoint trap (core dumped)" in the corespondig terminal and nothing else happens. This happens if I use it in a vs code terminal and in a normal bash terminal without an instance of vs code running.
I tried to delete my settings (in $HOME/.config/Code and $HOME/.vscode), reinstalling with snap (after snap remove --purge code) and reinstalling code-insiders from deb file. Unfortunately I dont't know what I did to cause this issue so I cant tell how to reproduce it.

VS Code version: Code - Insiders 1.60.0-insider (89bbd372f459ce72e9c0b60eb3b26b924f64f62d, 2021-08-20T17:46:50.966Z)
OS version: Linux x64 5.11.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600XT 6-Core Processor (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|31.35GB (0.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id f16d63df-737c-46f0-b952-f6baee8bad1c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
3f5j7703:30294757
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824cf:30353184
javagetstartedt:30350119
pythonvspyt187:30356034

```

</details>

**Comment by stroucki** [comment]
Version downloaded was code-stable-x64-1631295096.tar.gz
Final lines of strace VSCode-linux-x64/code :
<code>
getrandom("\x37\xe1\xed\xe0\xd4\x3c\x32\x9c", 8, 0) = 8
getrandom("\x75\x99\xc0\x53\x67\xbb\xef\xf0", 8, 0) = 8
gettid()                                = 507955
gettid()                                = 507955
mmap(0x2aa400000000, 34359738368, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap(0x2aa400000000, 34359738368, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
+++ killed by SIGTRAP (core dumped) +++
Trace/breakpoint trap (core dumped)
</code>
