### ISSUE TITLE
an error occurred while trying to rename a file destination directory

### ISSUE THREAD

**Issue by aajaj4729** [microsoft/vscode#131353]

**Comment by aajaj4729** [comment]
![Screenshot (186)](https://user-images.githubusercontent.com/74093811/130351588-cc500ca3-e7ef-4dee-a231-0885342a0dc8.png)

**Comment by gjsjohnmurray** [comment]
Are you using an antivirus app? Maybe it is interfering with installation.

**Comment by joaomoreno** [comment]
Also, can you uninstall and reinstall VS Code?
