### ISSUE TITLE
Jupyter notebooks don't pick up kernel changes in file

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#131369]
Here is how to reproduce:
1. Create a new notebook file in Jupyter Lab, select Julia 1.6.2 kernel, save it.
2. Open it in VS Code, run some code etc. then close in VS Code.
3. Open the file in Jupyter Lab again, _change_ the kernel in Jupyter Lab and save the notebook file.
4. Open the file in VS Code again. It now happily still defaults to the kernel that it used in step 2, i.e. it does not recognize that the kernel information in the file has been updated by a different piece of software in the meantime and that it should not use the kernel that was used in step 2.

In my mind this is a bug, and given how often people use different editors for Jupyter notebook files, one that is on a common codepath.

The root problem here is probably the strategy that @DonJayamanne described [here](https://github.com/julia-vscode/julia-vscode/pull/2315#issuecomment-887027214). I think as implemented right now, that simply won't work: kernel information is stored in Jupyter notebooks themselves according to the spec, so if VS Code then decides to additional store kernel selection information per notebook in some other location, it needs to be super careful about properly invalidating that other information when the kernel information in the file itself is changed. Also CC @claudiaregio.

**Comment by mjbvz** [comment]
@DonJayamanne I believe the VS Code part of this was fixed by #131934. Please let me know if there's anything that still needs to be done in our core notebook implementation
