### ISSUE TITLE
Code scrolls when typing with markdown preview open

### ISSUE THREAD

**Issue by sgon00** [microsoft/vscode#131315]
My Environment:

```
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.10.0-5mx-amd64
```

More info: MX Linux 19.4 based on debian 10. **KDE** windows manager.

Please refer to the closed bug: https://github.com/microsoft/vscode/issues/65504

I don't need to provide any more steps. The bug is exactly the same as the bug #65504

I don't have any image inside the markdown file. You can simply use any long enough (more than one page) markdown file to test and try to edit something in the middle. You can use that bug's test file too. The problem just happens to all my markdown files.

I don't have any markdown extension installed.
I also tried to open vscode with all extensions disabled with the command `code --disable-extensions`. The problem still exists.

Thanks a lot.

**Comment by gjsjohnmurray** [comment]
Is #119370 similar?

**Comment by sgon00** [comment]
@gjsjohnmurray Thanks a lot for the quick reply. It's similar. But I won't say the same. Because that bug reporter explicitly mentions the problem happend when typing something near the end of document, and that document has an image inside. But for me, the problem happens when I type anywhere in the document and the document does NOT need to have an image. 
If you plan to mark this bug duplicated, I think that bug should modify bug description and remove `near the end of the document` related words. Thanks.
