### ISSUE TITLE
Create Custom Commands To Run/Debug Files Based On Extension

### ISSUE THREAD

**Issue by MasterKavi-24** [microsoft/vscode#131311]
Issue Type: <b>Feature Request</b>

Team VSCode,
          I need to set a command that runs the currently active file based on it's extension... I already sent a request regarding this issue and the reply was not much helpful or satisfying. I need to make my own commands without the help of third-party extensions. Waiting for your reply.........

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by weinand** [comment]
The [Code Runner](https://github.com/formulahendry/vscode-code-runner) extension does exactly what you are trying to do. Please read the source to learn how to do this.
