### ISSUE TITLE
Fonts: consider to set `font-display: block`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131396]
As far as I know, we use custom fonts in 3 areas:
* our Codicon set
* extension contributed file icons
* extension contributed product icons

I often see the workbench appear similar to this because fonts were not loaded yet and the browser fallsback to a standard font that doesn't include the used characters, as such glyphs appear:

![recording](https://user-images.githubusercontent.com/900690/130436998-b7d8b429-9190-48ad-a2c7-dc76e21d0b10.gif)

With `font-display: block` the browser will not use any fallback and will simply refuse to show the font until loaded (for up to 3s I think):

![recording (1)](https://user-images.githubusercontent.com/900690/130437152-be57d7de-3dde-46a6-86cb-bb1525a82662.gif)

More info on the available choices are in this great article:

![image](https://user-images.githubusercontent.com/900690/130436649-df94b319-07b5-49b7-8808-f0b6bc2e1b08.png)
(credits: https://sia.codes/posts/making-google-fonts-faster/)

The following locations in code are imho impacted:
* [`productIconThemeData.ts`](https://github.com/microsoft/vscode/blob/b07d19a768b42af2aa8f78f8b1b68978f14f9bd9/src/vs/workbench/services/themes/browser/productIconThemeData.ts#L224-L224)
* [`fileIconThemeData`](https://github.com/microsoft/vscode/blob/b07d19a768b42af2aa8f78f8b1b68978f14f9bd9/src/vs/workbench/services/themes/browser/fileIconThemeData.ts#L346-L346)
* [`iconStyleSheet.ts`](https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/theme/browser/iconsStyleSheet.ts#L56-L56)
* [`contextView.ts`](https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/browser/ui/contextview/contextview.ts#L367-L367)
* [`codicon.css`](https://github.com/microsoft/vscode/blob/dc269a975e2cc5df96d8c02b00b25c37be5409c2/src/vs/base/browser/ui/codicons/codicon/codicon.css#L7-L7)

I realise that this might be a controversal change, so maybe alternatives can be discussed here as well. One alternative would be to try to load the fonts in parallel to the workbench loading to prevent the flicker alltogether,

**Comment by isidorn** [comment]
I prefer not showing anything than the current empty squares which always feel like rendering glitches and are disturbing.

**Comment by aeschli** [comment]
Makes sense to me. I'll make the change.

**Comment by aeschli** [comment]
@bpasero Thanks for the research!
If you have any tricks to get to see the placeholder boxes as long as in your screencasts, please add that for the verifier.

**Comment by bpasero** [comment]
Thanks!

Yeah I cheated in my demo: I added code to specifically slow down the loading of `ttf` and `woff`. However, it should be relatively easy to be reproducible e.g. in a incognito browser session over a slow network connection.

**Comment by bpasero** [comment]
I just noticed how file icons where still suffering from this and realised that `font-display` can only be set on `@font-face` and not anywhere else. As such, this rule:

https://github.com/microsoft/vscode/blob/c8209aff4c8495fa936058c9f213abf452ff60f0/src/vs/workbench/services/themes/browser/fileIconThemeData.ts#L348-L348

Needs to move, I guess into here:

https://github.com/microsoft/vscode/blob/c8209aff4c8495fa936058c9f213abf452ff60f0/src/vs/workbench/services/themes/browser/fileIconThemeData.ts#L346-L346

**Comment by aeschli** [comment]
Oh, yes, my bad. I'll make a PR.

**Comment by misolori** [comment]
@aeschli I'll update this in the main codicons repo as well https://github.com/microsoft/vscode-codicons/blob/main/src/template/styles.hbs

**Comment by rzhao271** [comment]
I found the perfect opportunity to verify this issue: I had Electron build in the background.
