### ISSUE TITLE
No intellisense in project.json from local nuget source

### ISSUE THREAD

**Issue by daghb** [Microsoft/vscode#13130]
- VSCode Version: Any
- OS Version: Any

Steps to Reproduce:

1. Create a lib and compile (dotnet new -t library)
2. "dotnet pack" it
3. Create a Nuget.config with a local file repository
4. "nuget add" the library to this repository
5. Create an empty .NET app (dotnet new)
6. Attempt to use the library by adding the library name and version to project.json

No intellisense in proect.json. However, if you add the library manually, it will be added to the "dotnet restore" and work.

**Comment by Tyriar** [comment]
Please file an issue against the [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode) extension as that provided C# support.
