### ISSUE TITLE
How to remove the Visual Studio Code Terminal window file path output

### ISSUE THREAD

**Issue by HezzyBear** [microsoft/vscode#131361]
Issue Type: <b>Feature Request</b>

How do you remove the file path from the terminal window?

PS C:\Users\MyProDesk> cd c:/Users/MyProDesk/PycharmProjects/SpaceGame
PS C:\Users\MyProDesk\PycharmProjects\SpaceGame> & C:/Users/MyProDesk/AppData/Local/Programs/Python/Python39/python.exe c:/Users/MyProDesk/PycharmProjects/SpaceGame/space_game.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by HezzyBear** [comment]
I'm sorry, I guess I didn't explain myself very well. Here's a video of the file path in the VScode terminal window that I want removed. Thanks 

https://user-images.githubusercontent.com/87545509/130496173-06d1de03-74a2-49a8-8c28-769287776e78.mp4

**Comment by meganrogge** [comment]
Please file an issue in the python extension repo
