### ISSUE TITLE
it offen alert the the window has crashed tip

### ISSUE THREAD

**Issue by qiutian00** [microsoft/vscode#131303]
- VS Code Version: 1.48.2
- OS Version: windows 10
![S)DZ@$C2XK}GHW} AYH RHB](https://user-images.githubusercontent.com/24382500/130314904-3a2baa2f-a4dd-45e5-846e-91a2cc0801ff.png)

Steps to Reproduce:

- sometimes , it offen alert the `the window has crashed` tip,  today it alerted three times when I running two projects in vscode， so how to avoid this.

![vscode 退出problem](https://user-images.githubusercontent.com/24382500/130314909-7249bb69-0eda-420e-88b5-221cf698344f.png)

**Comment by qiutian00** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Alert same name when rename a variable (#120668)](https://www.github.com/microsoft/vscode/issues/120668)

not the same, enen

**Comment by gjsjohnmurray** [comment]
Please update to the current release, 1.59.1, then see if the problem remains.

**Comment by qiutian00** [comment]
> Please update to the current release, 1.59.1, then see if the problem remains.

ohoh, thanks.

**Comment by qiutian00** [comment]
Used it yestoday after updated the version, the problem not remains, thanks a lot.
