### ISSUE TITLE
Sync Setting Issue when attempting to sync setting with github with account which is not logged in

### ISSUE THREAD

**Issue by ranefattesingh** [microsoft/vscode#131327]
Steps to reproduce
1. Ensure that you are not logged in with your Github account on your default browser
2. Open VSCode
3. Click on Accounts icon
4. Select Signin to Sync Settings option
5. Select Signin with Github account
6. You'll see your default browser opened with Github login page
7.  Login into your Github account
8. You will notice that settings are not getting sync instead you get error on browser instead.

NOTE: You cannot reproduce this issue if you are already logged in with your Github account on your default browser
Tested on Windows and Linux system

**Comment by sandy081** [comment]
> You will notice that settings are not getting sync instead you get error on browser instead.

@TylerLeonhardt Seems authentication issue as there is an error on browser.

**Comment by ranefattesingh** [comment]
@TylerLeonhardt @sandy081 
When I login into my github account I receive an error in browser but if I go to github.com on new tab then I can see I am signed in successfully (means my previous login attempt was successful) so I don't think it has anything to do with authentication of my account.

**Comment by TylerLeonhardt** [comment]
@ranefattesingh what error are you seeing in the browser?

**Comment by ranefattesingh** [comment]
Issue is not appearing anymore hence closing it!
