### ISSUE TITLE
I can open jpg ,but can not open JPG(upper)

### ISSUE THREAD

**Issue by ingxii** [Microsoft/vscode#1313]
I can open jpg ,but can not open JPG(upper)

**Comment by mohsen1** [comment]
It was fixed in this commit: 65d2803a603d1b679a68100bec463958

Line of code to look at: https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L82

**Comment by dbaeumer** [comment]
@mohsen1 Thanks. Closing.
