### ISSUE TITLE
how to check command is completed or in progress via API

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#13136]
Is there any way that when user starts the command and start again. API checks the same command is in progress so allow us to check to run the command again when first one completes of just notify its in progress.

```
    var downloadSettings = vscode.commands.registerCommand('extension.downloadSettings', async () => {
});
```

**Comment by jrieken** [comment]
The API cannot do that and also don't think it's desirable. Commands are very different and it's hard argue they no equal command should ever run 'in parallel'.
