### ISSUE TITLE
while in terminal ctrl c does not return to a new line

### ISSUE THREAD

**Issue by zeshanb** [microsoft/vscode#131358]
Issue Type: <b>Bug</b>

After running command:

cordova build browser

ctrl+c ,or in this case on a Mac using a PC keyboard, the windows key + c, doesn't end the process and move to the next line for more command input. User is required to close the existing terminal window when not required and open a new terminal window.

VS Code version: Code 1.59.1 (Universal) (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 39c759b2-3dba-4378-9b6f-7c13ef4571ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cordova-tools|msj|2.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn478:30354110

```

</details>

**Comment by zeshanb** [comment]
As of 2021-08-19T11:53:52.479Z this is resolved. ctrl + c on a keyboard is closing the terminal window on Mac OS 11.5.2.

**Comment by meganrogge** [comment]
please attach a gif with screen cast mode enabled. I don't think the windows key + c should end the process
