### ISSUE TITLE
[Bug] "Copy Command Title" doesn't have a command ID

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131350]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Search "Copy Command Title" in the Keyboard Shortcuts editor.
2. No result shows up.

Since other menu items for a single command all have an associated command ID, it would be inconsistent to leave "Copy Command Title" out:

![image](https://user-images.githubusercontent.com/28700378/130751533-6c6c8e49-5a78-4152-b93d-4db746efb1f0.png)

**Comment by wenfangdu** [comment]
@timfenney Please have a look at this feature request, it's an improvement over [your original PR](https://github.com/microsoft/vscode/pull/125563).

**Comment by AiverReaver** [comment]
can I work on this feature request? @wenfangdu

**Comment by AiverReaver** [comment]
It might be too early to create this PR as this is a backlog candidate but created it anyway.

**Comment by wenfangdu** [comment]
@AiverReaver Thanks!

**Comment by wenfangdu** [comment]
@sandy081 Since it's inconsistent with other menu items in the keybindings editor, it could be considered as a bug, upvoting to move to Backlog Candidates is too much trouble for just adding a simple command ID, please move it into Backlog, as we know it may never make into the Backlog by upvoting.

![image](https://user-images.githubusercontent.com/28700378/130750602-4317aedc-06c2-4902-96f4-91f476e5c102.png)

**Comment by wenfangdu** [comment]
@sandy081 Since it's inconsistent with other menu items in the keybindings editor, it could be considered as a bug, I've updated the issue to reflect that. Voting to move to the Backlog is too much trouble for just adding a simple command ID, please just move it, as we know it may never make it into the Backlog by voting, not to mention it has a PR already.

![image](https://user-images.githubusercontent.com/28700378/130750602-4317aedc-06c2-4902-96f4-91f476e5c102.png)
