### ISSUE TITLE
Cannot define recursive dictionary object in jsdoc, but I can define recursive Map

### ISSUE THREAD

**Issue by bkilinc** [microsoft/vscode#131394]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Linux Mint 18

recursive dictionary object that I defined in jsdoc comment is not recognized by VSCode and it is reported as 'any' type. But if I convert object dictionary to Map, it works. 

Following code includes both definitions
```js
/** 
 * @typedef {Object.<string, (number | SelfOrNumberObj)>} SelfOrNumberObj
 * @typedef {Map<string, (number | SelfOrNumberMap)>} SelfOrNumberMap
 */

/**
 * 
 * @param {SelfOrNumberObj} val1 
 * @param {SelfOrNumberMap} val2
 */
function testObj(val1, val2) {

}
```
Steps to Reproduce:

1. create a blank js file and open it in VSCode
2. copy the js code above and paste it in open file.
3. confirm that val1 is recognized as 'any'. 
4. confirm that val2 is recognized correctly as Map.

**Comment by bkilinc** [comment]
following typedef works but it is typescript style and it gives error on my linter.
```js
@typedef {{ [key :string] : (number | SelfOrNumberObj) }} SelfOrNumberObj
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
