### ISSUE TITLE
Weird visual bug in codespaces terminal

### ISSUE THREAD

**Issue by SHoogland** [microsoft/vscode#131389]
![image](https://user-images.githubusercontent.com/2057831/130420320-13b83679-1790-4709-b423-cb71b4922fb1.png)

On a Dell U2412M display with a resolution of 1920x1200 this weird visual issue occurs in the terminal

The display is connected to a m1 mac book pro, and it occurs in the brave browser while using github codespaces

**Comment by meganrogge** [comment]
With your monitor and computer does it always look like this? if not, can you please describe how you got into this state?

**Comment by SHoogland** [comment]
It always looks like this on that monitor, as soon as I connect the monitor and launch a codespace, the terminal renders like that, when I move the window between the 2 displays, it renders normally on the macbook, and it renders like the screenshot on the monitor.

**Comment by meganrogge** [comment]
does turning `terminal.integrated.gpuAcceleration` to `off` fix the issue? looks like webGL sometimes doesn't work on Brave
