### ISSUE TITLE
Vscode does not display right colours from the theme

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#131360]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-18T00:13:37.935Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-81-generic
OS Version: Ubuntu 20.04.2

Steps to Reproduce:

1. Use Solarized Light Theme: Open Developer: Inspect Editor Tokens and colors. Then point cursor in editor without any text. It shows: foreground `#657B83` and background `#FDF6E3`. Which is correct as per the Solarized light theme.
2. But when I used inbuilt color picker (pipette) tool, I get background as `#FCFAE1`. Also, I tested the pipette tool at Solarized themes at other places it shows the correct background of `#FDF6E3`. Also, the background in vscode editor actually looks different and more whiter than Solarized themes used in other places. My colour pipette is `zenity --color-selection`

**Comment by aeschli** [comment]
The difference of RGB measured by the pipette tool is related to the color profile that Electron/Chromium uses.

You can use the following Chromium settings in `argv.json` or on the command line to influence the color profile.
```
{
  "disable-color-correct-rendering": true
  "force-color-profile": "srgb"
}
```
