### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Arjun13maurya** [microsoft/vscode#131413]
Issue Type: <b>Bug</b>

sir i have a bug found on visual studio code 
That if i have written any thing on terminal page, and if i have cut that and written something els then that the first one that i have written is not going on 
so i have a request to solve my bug please

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G (4 x 2695)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.52GB free)|
|Process Argv|D:\\web --crash-reporter-id d644aba8-bdc6-4bcc-9bb0-bf353c277985|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
tabulate|a5h|0.4.0
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
prettier-vscode|esb|8.1.0
code-runner|for|0.11.5
theme-monokai-pro-vscode|mon|1.1.19
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.0
mssql|ms-|1.10.1
python|ms-|2021.8.1147840270
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
cpptools|ms-|1.5.1
material-icon-theme|PKi|4.9.0
java|red|0.81.0
LiveServer|rit|5.6.1
preview-vscode|sea|2.2.5
errorlens|use|3.4.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.32.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
vstre464:30350172
bridge0723:30353136
vsdyn420:30354109

```

</details>

**Comment by kaffarell** [comment]
Could you explain yourself better? What do you mean by "cut that" and "going on".

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
