### ISSUE TITLE
Test type hierarchy peek UI

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#131424]
Refs: https://github.com/microsoft/vscode/issues/15533

- [x] anyOS @donjayamanne
- [x] anyOS @stuartleeks (Windows)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131424%0A%0A&assignees=jrieken)

---

We are working on UI and API for the type hierarchy feature. The TPI is about the peek UI for type hierarchy, it should be working analog the peek call hierarchy. 

* install this dummy extension: [typeh-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/7033356/typeh-0.0.1.vsix.zip)
* start VS Code with `--enable-proposed-api testing.typeh`
* it will offer fake type hierarchy for plaintext files, words from the above line are super-types and words from the below line are sub-types

Test that

* there is 'Peek > Peek Call Hierarchy' in the context menu (for supported files types)
* peek shows a preview editor and the type hierarchy
* the title has a toggle command to change from super-types to sub-types and vice versa
* types that are selected in the tree are highlighted in the editor
* pressing `Shift+Enter` on a tree node re-root peek onto that item

**Comment by stuartleeks** [comment]
Notes
- It's probably obvious, but I had to start VS Code with the `--enable-proposed-api` flag
- The steps refer to the 'Peek > Peek Call Hierarchy' but it's the "Peek _Type_ Hierarchy" that is new

**Comment by DonJayamanne** [comment]
Verified.
