### ISSUE TITLE
`Ctrl+.`: `Sougou Pinyin` behaves differently in VS Code Insiders than VS Code Stable

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131465]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider (**Not Reproducible In v1.59.1**)
- OS Version: Windows 10

Steps to Reproduce:

1. Enable "Screencast Mode".
2. Focus settings UI editor's search bar.
3. Type <kbd>Ctrl</kbd>+<kbd>.</kbd>.
4. Click elsewhere.
5. Repeat step 2.

![STG 2021-08-24 10_59_49](https://user-images.githubusercontent.com/28700378/130548844-726889ac-22e7-43b3-a2a8-e416d7de98ee.gif)

**Comment by roblourens** [comment]
Sorry, what are you expecting `ctrl+.` to do?

**Comment by wenfangdu** [comment]
@roblourens I bound <kbd>Ctrl</kbd>+<kbd>.</kbd> to just `workbench.action.openSettingsJson`, pressing it should open the `settings.json` no matter whether the settings UI editor's search bar is focused.

This issue appears in v1.60.0-insider, but doesn't in v1.59.1.

**Comment by wenfangdu** [comment]
@roblourens I bound <kbd>Ctrl</kbd>+<kbd>.</kbd> to just `workbench.action.openSettingsJson`, pressing it should open the `settings.json` no matter whether the settings UI editor's search bar is focused.

Currently, when the search bar isn't focused, <kbd>Ctrl</kbd>+<kbd>.</kbd> can open `settings.json` normally.

This issue appears in v1.60.0-insider but not in v1.59.1.

**Comment by roblourens** [comment]
There are editor keybindings using that shortcut. You can find them in the keyboard shortcuts editor and either unbind them if you don't use them, or modify their when clauses to add `!inSettingsEditor`

**Comment by wenfangdu** [comment]
@roblourens

> I bound <kbd>Ctrl</kbd>+<kbd>.</kbd> to _**just**_ `workbench.action.openSettingsJson`.

Sorry, I should've explained more clear, it _is_ the only command being bound to <kbd>Ctrl</kbd>+<kbd>.</kbd>.

**Comment by roblourens** [comment]
Are you sure? Can you run the command "Toggle keyboard shortcuts troubleshooting", then use that keybinding again, to see if there is something else?

**Comment by wenfangdu** [comment]
@roblourens

When the search bar is focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:
![image](https://user-images.githubusercontent.com/28700378/130572350-1018d8fc-e2e8-42fa-ab55-bc30680a3565.png)

When the search bar isn't focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:
![image](https://user-images.githubusercontent.com/28700378/130572497-581338a1-2408-4deb-afd0-dd1ec3a7fd47.png)

**Comment by wenfangdu** [comment]
@roblourens

When the search bar is focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:

![image](https://user-images.githubusercontent.com/28700378/130572704-30eea6e1-9792-4864-adba-c2cc77b42350.png)

When the search bar isn't focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:

![image](https://user-images.githubusercontent.com/28700378/130572987-45b7da0c-2cc3-45f8-b5ca-1280d16b2502.png)

**Comment by wenfangdu** [comment]
@roblourens

I unbound all keybindings mapped to <kbd>Ctrl</kbd>+<kbd>.</kbd>, and ran "Toggle keyboard shortcuts troubleshooting".

When the search bar is focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:

![image](https://user-images.githubusercontent.com/28700378/130572704-30eea6e1-9792-4864-adba-c2cc77b42350.png)

When the search bar isn't focused, typing <kbd>Ctrl</kbd>+<kbd>.</kbd>:

![image](https://user-images.githubusercontent.com/28700378/130572987-45b7da0c-2cc3-45f8-b5ca-1280d16b2502.png)

**Comment by roblourens** [comment]
Interesting. @alexdima did anything change this month? The input where this breaks is an editor instance.

**Comment by alexdima** [comment]
@wenfangdu I cannot reproduce. Here is what I see when I press `ctrl+.` in the search input:
```
[2021-08-25 13:56:46.534] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-08-25 13:56:46.535] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-08-25 13:56:46.535] [renderer3] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-08-25 13:56:46.535] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Period, keyCode: 190, key: .
[2021-08-25 13:56:46.536] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Period, keyCode: 84 ('.')
[2021-08-25 13:56:46.537] [renderer3] [info] [KeybindingService]: | Resolving ctrl+.
[2021-08-25 13:56:46.537] [renderer3] [info] [KeybindingService]: \ From 2 keybinding entries, no when clauses matched the context.
[2021-08-25 13:56:46.790] [renderer3] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
[2021-08-25 13:56:47.097] [renderer3] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

For you, it appears that `ctrl+.` is not reaching VS Code. Are you by any chance using a special input method where `ctrl+.` has a certain meaning or are you using the US keyboard layout?

**Comment by wenfangdu** [comment]
@alexdima I'm using [Sougou Pinyin](https://en.wikipedia.org/wiki/Sogou_Pinyin) and US keyboard layout. But the strange thing is I have no problem when using <kbd>Ctrl</kbd>+<kbd>.</kbd> in the search bar in v1.59.1. And in v1.60.0-insider, when the search bar isn't focused, I can use <kbd>Ctrl</kbd>+<kbd>.</kbd> as well.

**Comment by alexdima** [comment]
@wenfangdu I don't think we changed anything in the keybinding handling code that would impact this. VS Code Stable ships Electron `13.1.7`, while Insiders has Electron `13.1.8`, which contains a Chromium update ( https://github.com/electron/electron/pull/30169 ), so perhaps that introduced a difference.

Can you reproduce in Chrome?
- latest insiders - https://vscode-web-test-playground.azurewebsites.net/?enter=true 
- latest stable - https://vscode-web-test-playground.azurewebsites.net/?quality=stable&enter=true

**Comment by alexdima** [comment]
@deepak1556 Do you have any ideas? It looks like the very minor update to Chromium that we are about to ship as stable might have introduced a change in the way input is handled when using [Sougou Pinyin](https://en.wikipedia.org/wiki/Sogou_Pinyin). We haven't done any changes in this area on our side, it just looks like the newer Chromium version "eats up" `ctrl+.`. It is unclear to me if `ctrl+.` serves a purpose with the Sougou Pinyin IME.

cc @rebornix

**Comment by deepak1556** [comment]
@alexdima I don't see any changes related to input handling in the said upstream versions. Lets try to confirm the issue once again with base electron app, @wenfangdu can you follow the below steps and attach a screenshot

1) Download and open https://www.electronjs.org/fiddle for you platform
2) Load https://gist.github.com/deepak1556/69b8930b819f82115df50d0f466dd1ba via `Load Fiddle` button on the top right corner
3) Choose Electron version `v13.1.7` from top left dropdown
4) Run the app
5) With the input box focused, press `Ctrl+.`
6) Take Screenshot
7) Close the app
8) Choose Electron version `v13.1.8` from top left dropdown
9) Repeat steps 5, 6, 7

**Comment by wenfangdu** [comment]
@deepak1556 v13.1.7 screenshot:

![image](https://user-images.githubusercontent.com/28700378/131413265-6c516caa-ac2a-4992-aba6-3d3f82f7cfdd.png)

v13.1.8 screenshot:

![image](https://user-images.githubusercontent.com/28700378/131413409-2feea1e8-c2fd-4c92-adc9-36b996db729e.png)

**Comment by deepak1556** [comment]
Hmm there is no difference in capture for the runtime versions, but definitely we don't see keydown event for `period` character.

Can you also load https://w3c.github.io/uievents/tools/key-event-viewer.html in your chrome or edge browser and attach the screenshot of pressing `ctrl+.`

@alexdima did we change any keyboard event handlers for the search input box that now relies on `keydown` rather than `keyup` ?

**Comment by wenfangdu** [comment]
> Can you also load https://w3c.github.io/uievents/tools/key-event-viewer.html in your chrome or edge browser and attach the screenshot of pressing `ctrl+.`

@deepak1556 

![image](https://user-images.githubusercontent.com/28700378/131428431-820340e1-f7d2-4916-970d-c0bdf6ef6e12.png)

**Comment by deepak1556** [comment]
Thanks that confirms the runtime are aligned in receiving the same input events when used with `Sougou Pinyin`, in normal scenario the input events are as follows.

<img width="1286" alt="Screen Shot 2021-08-31 at 11 02 14 AM" src="https://user-images.githubusercontent.com/964386/131429677-9359d41b-d8d6-4fcd-8fc0-d39f187b770e.png">

**Comment by wenfangdu** [comment]
@roblourens @deepak1556 @alexdima For the record, v1.60.0 stable does capture <kbd>Ctrl</kbd>+<kbd>.</kbd> when the settings UI editor's search bar is focused.

**Comment by alexdima** [comment]
> @alexdima did we change any keyboard event handlers for the search input box that now relies on keydown rather than keyup ?

No, we always did dispatching on `keydown`. 

> For the record, v1.60.0 stable does capture Ctrl+. when the settings UI editor's search bar is focused.

@wenfangdu This makes no sense. Unless... Is it possible that `Sougou Pinyin` looks at the current focused window and it behaves differently for `Code.exe`? What if you download VS Code Insiders (as a zip) and rename `Code - Insiders.exe` to `Code.exe`?

**Comment by wenfangdu** [comment]
@alexdima **It is**. After renaming `Code - Insiders.exe` to `Code.exe`, the capturing works, I'll file an issue on their side.

**Comment by wenfangdu** [comment]
@alexdima _It is_. After renaming `Code - Insiders.exe` to `Code.exe`, the capturing works, I'll file an issue on their side.

**Comment by alexdima** [comment]
Thanks for following up on this. 

To summarize: `Sougou Pinyin` behaves differently in VS Code Insiders than VS Code Stable and the root cause seems to be with `Sougou Pinyin` itself, which looks at the process image name (`Code.exe` vs `Code - Insiders.exe`).
