### ISSUE TITLE
Allow customizing bracket pairs

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131412]
Is it possible to add language specific overrides for brackets pairs in config?
```json
"[typescriptreact]": {
    "editor.brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["<", ">"]
    ],
    "editor.colorizableBracketPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ]
}
```

Or other way to specify subset of pairs provided by language. Or expend it if implementation supports expanding list of pairs and don't rely on language implementation.

_Originally posted by @IllusionMH in https://github.com/microsoft/vscode/issues/131176#issuecomment-901959714_

**Comment by gajabo** [comment]
> Verify that only `[`...`]` is colorized. Notice that the pairs `(`...`)` and `[`...`]` are highlighted when the cursor is on either the closing or opening bracket.

Hello. I have added the mentioned code to my %appdata%\Code\User\settings.json file, but bracket pair colorization still doesn't work for Plain Text, and both "editor.language.bracketPairs" and "editor.language.colorizedBracketPairs" settings are underlined as problems with the following caption: "This setting does not support per-language configuration."

My VS Code version is 1.61.2

**Comment by IllusionMH** [comment]
> insiders-released 
This setting only available in Insiders version at this moment. https://code.visualstudio.com/insiders/

**Comment by j9108c** [comment]
just got this on stable release, thanks. i have one issue, when i set any custom bracket pair where the opening and closing bracket are the same character (e.g., ["\`", "\`"]) in colorizedBracketPairs, it doesnt recognize the pair, so each character is colorized differently

**Comment by IllusionMH** [comment]
Same character pairs are not supported.

**Comment by allenyllee** [comment]
In [Bracket Pair Colorizer (version 1)](https://github.com/CoenraadS/BracketPair)  extension, it supports HTML tag pair:
```json
"bracketPairColorizer.consecutivePairColors": [
    ["<", "</"],
    ["<", "/>"],
    [
        "Gold",
        "Orchid",
        "LightSkyBlue"
    ],
    "Red"
]
```

It looks like that:

<img width="170" alt="Snipaste_2021-11-05_14-07-15" src="https://user-images.githubusercontent.com/3991134/140466015-e7076226-fd6f-475e-a154-adf59d61772d.png">

I try to do the same on the VScode's native bracketPairs settings, 

```json
"[vue]": {
    "editor.language.bracketPairs": [
        ["[", "]"],
        ["(", ")"],
        ["{", "}"],
        ["<", "</"],
        ["<", "/>"],
    ],
    "editor.language.colorizedBracketPairs": [
        ["[", "]"],
        ["(", ")"],
        ["{", "}"],
        ["<", "</"],
        ["<", "/>"],
    ]
},
```
but it only works on the most outer pairs:

<img width="211" alt="Snipaste_2021-11-05_14-29-43" src="https://user-images.githubusercontent.com/3991134/140468068-5e2ed98f-45d6-4b2c-83e6-478d3c42ccdb.png">




And also, in [Bracket Pair Colorizer (version 1)](https://github.com/CoenraadS/BracketPair) extension, the paired brackets has its own background color. But in the [VScode theme color document](https://code.visualstudio.com/api/references/theme-color), there is only one background setting `editorBracketMatch.background`, which means that background can only have single color, doesn't like foreground color can have independent settings like `editorBracketHighlight.foreground1`, `editorBracketHighlight.foreground2`, `editorBracketHighlight.foreground3`,....

**Comment by IllusionMH** [comment]
Please create separate issues for separate requests. This one implemented as requested and closed therefore so other are either bugs that should be fixed or new requests.
Devs receive 100s or 1000s of notifications from repo so it's too easy to miss comment on already completed and closed almost month ago request.

In your comment there is even more that 2 independent requests - backgrounds and higlight inside of template.
As for highlight inside of template - make sure that it is part of `"[vue]"` language. I won't be surprised if only `template`s are part of `"[vue]"` and contents are embedded language which is controlled by `"[vue-html]"`.

These are no settings for backgrounds and not even single color - `editorBracketMatch.background` is only for case when you cursor is on bracket and editor highlights matching bracket which is not relates to brackets pairs colorization.
Search for duplicates - this most likely already requested or create separate request (after thorough search).
