### ISSUE TITLE
Incorrect syntax highlighting for Markdown?

### ISSUE THREAD

**Issue by Arnie97** [Microsoft/vscode#13149]
- VSCode Version: 1.5.3
- OS: elementary OS 0.3.2 Freya (built on Ubuntu 14.04)
- Please refer to lines 18 - 21 in the screenshot for details.

![](https://cloud.githubusercontent.com/assets/10341686/19030630/943352a2-8981-11e6-94e2-02e0e9b35919.png)

``````
# Arbitrary Piece of code

```c
#include <stdio.h>

int main(void)
{
    puts("hello world");
    return 0;
}
```

## The 2nd Heading

Lorem ipsum minim amet laboris id aliquip quis duis qui aliquip tempor ut.
Above is the main function (`int main(void)`).

## This Heading is not rendered properly

Also note that things'll get even worse after an apostrophe.
Excepteur nulla occaecat pariatur excepteur.
Reprehenderit laboris do laboris eu esse labore sit consequat.
In culpa ut mollit quis eu excepteur veniam.
``````

Any ideas?

**Comment by mjbvz** [comment]
I'm unable to repo this colorization with VSCode 1.6, but I do still see incorrect results (such as the heading text being gold after the code block):

![screen shot 2016-10-03 at 11 58 36 am](https://cloud.githubusercontent.com/assets/12821956/19049789/bb7eb46c-8960-11e6-990b-a6481d39467b.png)

I believe this is another case where the fenced code block's syntax highlighting leaks outside of the fenced code block itself. We're planning to address this problem this month.

**Comment by mairaw** [comment]
I'm seeing the same issue with version 1.7.1

![image](https://cloud.githubusercontent.com/assets/12971179/20161713/404fdb42-a6a5-11e6-82a8-0129ee354a43.png)

Changing the ' to ’ seems to fix the colorization:
![image](https://cloud.githubusercontent.com/assets/12971179/20161750/88b73d8a-a6a5-11e6-9e98-28afc206772c.png)

It seems that VS Code is trying to treat single-quote as a backtick. And then backticks don't get special colorization as I'd expect.

See the same file on Markdown Pad, for example:
![image](https://cloud.githubusercontent.com/assets/12971179/20161826/e1fd858e-a6a5-11e6-96f3-0e432e633f93.png)

**Comment by mjbvz** [comment]
Original issue seems to be fixed by #14626

![screen shot 2016-11-10 at 4 03 19 pm](https://cloud.githubusercontent.com/assets/12821956/20199437/41128d44-a75f-11e6-9846-c3b6ba499cfe.png)


@mairaw Can you please open a new issue to track the problem you are seeing and include the markdown source for the incorrectly highlighted file for testing. Thanks.

**Comment by mairaw** [comment]
@mjbvz missed this earlier. Sure, I'll do that if it still repros!

**Comment by mairaw** [comment]
Good news! Version 1.8.1 seems to have fixed my issue too:
![image](https://cloud.githubusercontent.com/assets/12971179/21621862/c701312e-d1af-11e6-88e0-d84a7a15a020.png)

Thanks!
