### ISSUE TITLE
Testing installing and updating extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131409]
Ref https://github.com/microsoft/vscode/issues/23251

- [x] Mac @chrmarti
- [x] Mac: @deepak1556 (arm64)
- [x] windows @karrtikr (x64)
- [x] windows @karthiknadig (ia32)
- [x] windows: @eamodio (arm64) 
- [x] linux @lramos15

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131409%0A%0A&assignees=sandy081)

---

Extensions installing and updating has been refactored to support platform specific extensions (which will be enabled in next milestone). So, please smoke test existing following functionalities are intact.

Note: Please test using fresh user-data and extensions dir so that existing caches are not used

### VS Code

- Test Installing an extension, extension with dependencies (vscjava.vscode-java-test), extension pack. Python, Pylance & Jupyter extensions are good targets to test.
- Test Updating an extension - To trigger auto update, change the version of the extension in its package.json in extensions folder
- Test Installing a specific version of extension
  - Using action available in the context menu of installed extension
  - Using the command `Extensions: Install Specific Version of Extension...`

### VS Code CLI 

  - Test Installing an extension, extension with dependencies and extension pack. Use cli command `code-insiders --install-extension <pub.name1> --install-extension <pub.name2>`. Also test installing multiple extensions at once.
  - Test installing a specific version of an extension.  Use cli command `code-insiders --install-extension <pub.name@version>`

**Comment by karthiknadig** [comment]
@sandy081 Can I use a HyperV VM for the ia32 Windows? I don't have 32 bit windows to test this on.

**Comment by sandy081** [comment]
Its ok to install VS Code ia32 installer on x64 windows to test it - https://code.visualstudio.com/insiders/#win
