### ISSUE TITLE
"is already running dialog" displayed when restarting js-debug sessions with children

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131432]
1. Debug something that immediately spawns a child session, like the [web-worker demo](https://github.com/microsoft/vscode-js-debug/tree/main/demos/web-worker)
2. Restart the session
3. Get this dialog:

![](https://memes.peet.io/img/21-08-65419769-5afa-4060-8680-f0b2473532fe.png)

@eamodio (and I) noticed it when debugging with the webworker extension host, where the web worker host is a child of the "renderer" debug session. I think that programmatic calls to `vscode.debug.startDebugging` should never trigger this alert, or at least those with a `parentSession` set since child sessions are never started explicitly by the user.

**Comment by weinand** [comment]
Yes, the debug API `vscode.debug.startDebugging` should never trigger this warning.

**Comment by roblourens** [comment]
I actually have a similar issue with notebook debugging. I think that the startDebugging API should be exempt from this, since the session is not managed or named by the user
