### ISSUE TITLE
Terminal interactedWith not clear if this means explicit user interaction

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131497]
Testing #130775

It is not 100% clear to me if the `interactedWith` will be fired if VS Code automatically opens a terminal with some command (for example when starting debugging in an internal terminal). `interactedWith` sounds like user initiated, I am not sure if it behaves like that in practice. We could also clarify this a bit in the docs.

**Comment by Tyriar** [comment]
Sounds good, right now we mention "key is pressed" but it should also mention "sent text" to align with these:

![image](https://user-images.githubusercontent.com/2193314/130609859-0505d765-8c36-4345-a646-8d73e9636742.png)
