### ISSUE TITLE
Inlay hints moves cursor invalid position when writing TypeScript files

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#131476]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0-insider 89bbd372f459ce72e9c0b60eb3b26b924f64f62d and 44568e5947efa4811419e529e80fb14b7554cf61
- OS Version: macOS 11.5.2
- TypeScript Version: typescript@4.5.0-dev.20210823

Steps to Reproduce:

1. Make TypeScript project
2. write TypeScript in VSCode
3. Use AutoComplete

![repro](https://user-images.githubusercontent.com/1955233/130568557-985ef86c-1f6b-47bf-8a53-16f1f3e46bf1.gif)

I tried insider/c08913337cb8b95493be8e99d62e0b3241563f6b/VSCode-darwin.zip , it's ok.

I think it's would be better that the cursor position is to the right of null. ( c08913337cb8b95493be8e99d62e0b3241563f6b and previous's behavior)

---

I searched keyword in Issue with 'argument' 'codelens' 'autocomplete' 'suggestion'

**Comment by hediet** [comment]
Can you test if e898b8d0 already fixed this?
The change should be included in the latest insider release.

**Comment by yamachu** [comment]
Thanks @hediet 

It seems to be fixed issue of cursor position.
However, the inlay hint feature itself seems to be stuck...

I can't confirm that it's completely fixed, as it may be a combination issue with the TypeScript version.
<img width="600" alt="No Inlay Hints" src="https://user-images.githubusercontent.com/1955233/130791274-62602c05-0e50-4d75-9367-58b1a4d7abdf.png">

**Comment by hediet** [comment]
Ah I think TS inlay hints are now disabled by default.
You can enable them with:
```
"editor.inlayHints.enabled": true,
"typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true,
"typescript.inlayHints.parameterNames.enabled": "all",
```

**Comment by yamachu** [comment]
Thanks!
After enabling the setting, Inlay hints worked.
Also, it seems that the cursor problem no longer occurs!
