### ISSUE TITLE
Test: Proposed QuickInputItem inline actions API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#131454]
Refs: #88716

- [x] anyOS @weinand
- [x] anyOS @karrtikr

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131454%0A%0A&assignees=TylerLeonhardt)

---

This iteration, we introduced a new proposed quick pick API... Buttons on QuickPick Items!
![image](https://user-images.githubusercontent.com/2644648/130532299-960fdb49-a0f6-47b8-83d9-2ba5fc74e493.png)

definition:
https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts#L2892-L2904
```ts
        // extends what is in vscode.d.ts
	export interface QuickPickItem {
		buttons?: QuickInputButton[];
	}
        // extends what is in vscode.d.ts
	export interface QuickPick<T extends QuickPickItem> extends QuickInput {
		readonly onDidTriggerItemButton: Event<QuickPickItemButtonEvent<T>>;
	}
	export interface QuickPickItemButtonEvent<T extends QuickPickItem> {
		button: QuickInputButton;
		item: T;
	}
```

Please play around with this API addition and let me know what you think. Keep in mind, you may see this issue: https://github.com/microsoft/vscode/issues/109969
I will be addressing this for both Core and extensions next milestone.

Full steps if you need them:
* create an extension https://code.visualstudio.com/api/get-started/your-first-extension
* then run `npx vscode-dts dev` in the root of the extension repo to get the proposed API typings
* look at quick pick examples here: https://github.com/microsoft/vscode-extension-samples/blob/main/quickinput-sample/src/quickOpen.ts#L53

these buttons are only supported on the `window.createQuickPick` object and not on the simpler `showQuickPick`

**Comment by weinand** [comment]
I like the API - didn't find any issues.

**Comment by karrtikr** [comment]
API works nicely. `onDidTriggerItemButton` is very similar to
```typescript
/**
 * An event signaling when a button was triggered.
 */
readonly onDidTriggerButton: Event<QuickInputButton>;
```
_Feedback:_ We should probably edit the doc comment to signal this is not for item buttons, or maybe even combine the two events? `item` property can be `undefined` in the case of button without items.
