### ISSUE TITLE
[FR] Option to configure word wrap for specific files

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131483]
I have a JavaScript file that has very long one-line comments, I want to set `"editor.wordWrap": "on"` for this file only and keep other js files unwrapped.

I tried <kbd>Alt</kbd>+<kbd>Z</kbd>, but it doesn't persist on VSCode reload. Are there any better ways?

If not, please consider this a feature request for adding such an option.

**Comment by alexdima** [comment]
AFAIK currently, it is not possible to define settings for individual files.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/112280
