### ISSUE TITLE
[Test UI] Visual Bug where test errors get "swapped" temporarily on runs

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#131443]
Issue Type: <b>Bug</b>
@connor4312 

When running a test, if you have multiple errors on test nodes, they swap around (it seems) when you click run, then restored after the run is complete.

![Capture](https://user-images.githubusercontent.com/15258962/130514605-3ccbd8d8-7e8c-4bb8-b304-8fb993714aee.gif)

VS Code version: Code - Insiders 1.60.0-insider (44568e5947efa4811419e529e80fb14b7554cf61, 2021-08-23T10:43:01.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (2.73GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/JGrote/Projects/vscode-adapter --crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer|ber|0.12.2
markdown-checkbox|bie|0.1.3
vscode-opennewinstance|chr|0.0.12
bracket-pair-colorizer-2|Coe|0.2.1
esbuild-problem-matchers|con|0.0.2
vscode-eslint|dba|2.1.23
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.6.0
filter-lines|ear|1.0.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
copilot|Git|1.3.2467
remotehub|Git|0.13.4
vscode-pull-request-github|Git|0.29.2
todo-tree|Gru|0.0.213
vscode-test-explorer|hbe|2.21.0
vscode-drawio|hed|1.6.1
change-case|hjd|1.0.2
git-graph|mhu|1.30.0
vscode-bicep|ms-|0.4.613
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
vscode-dotnet-runtime|ms-|1.2.0
remote-containers|ms-|0.191.1
remote-ssh-nightly|ms-|2021.8.18181
azure-account|ms-|0.9.8
powershell-preview|ms-|2021.8.0
test-adapter-converter|ms-|0.1.2
vscode-paste-image|mus|1.0.4
indent-rainbow|ode|7.5.0
docthis|oou|0.8.2
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
vscode-sort-json|ric|1.20.0
even-better-toml|tam|0.14.2
vscode-inline-values-powershell|Tyl|0.0.5
errorlens|use|3.4.0
vscode-icons|vsc|11.6.0
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
gitmoji-vscode|Vtr|1.0.7
better-align|wwm|1.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vshan820:30294714
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vsccppwtct:30312693
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
javagetstartedt:30350119

```

</details>

**Comment by connor4312** [comment]
I'm not able to repro this, does it still happen on the latest Insiders? https://memes.peet.io/img/21-08-65911e51-fe49-47e5-8aba-f34aa473562e.mp4
