### ISSUE TITLE
TypeScript React code highlighting broken

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/vscode#131426]
Issue Type: <b>Bug</b>

I noticed an issue with my usual Dracula theme:

![Screen Shot 2021-08-23 at 10 27 04 AM](https://user-images.githubusercontent.com/16144158/130483147-89b65ae3-b37e-4960-bac4-74363538d2cf.png)

I then disabled all extensions in my editor and tried the default Dark theme and can see the same issue persisting with the `</` characters and such.

![Screen Shot 2021-08-23 at 10 29 02 AM](https://user-images.githubusercontent.com/16144158/130483387-ceb34741-4696-4f38-a60a-fd75eea8ba03.png)

VS Code version: Code - Insiders 1.60.0-insider (44568e5947efa4811419e529e80fb14b7554cf61, 2021-08-23T10:42:53.526Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (8.86GB free)|
|Process Argv|--crash-reporter-id 9a7faba5-f890-4b5d-b40f-7e27975b59fa|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824cf:30353184
javagetstartedc:30350118
pythonvspyt187cf:30356035

```

</details>

**Comment by IllusionMH** [comment]
/duplicate
Related to #130996 and #131176 which have more details and other issues tracking problems.
