### ISSUE TITLE
Add a command for toggling "Search Only in Open Editors"

### ISSUE THREAD

**Issue by yg-h** [microsoft/vscode#131437]
I'd like to request the addition of a command for toggling "Search Only in Open Editors".

Currently we have toggle commands for toggleSearchRegex, toggleSearchCaseSensitive, toggleSearchWholeWord, etc, but not for "Search Only in Open Editors", even though it has a button in the search interface just like the others. 

Screenshots to show what I mean.

![image](https://user-images.githubusercontent.com/28206448/130509590-450943a7-23c2-4734-b94d-21abc9731d02.png)

![image](https://user-images.githubusercontent.com/28206448/130509747-c38cc4cc-ef72-4672-807c-34289695f518.png)

Adding the command would make keyboard-oriented users like me very happy!

From:
https://github.com/microsoft/vscode/issues/127898#issuecomment-904033190

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
