### ISSUE TITLE
Suggest changes doesn't work in Github.dev

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131434]
1. Make some edits when a PR is checked out
2. Run the "Suggest Changes" command
3. 🐛 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/2230985/130505031-1704ab6d-d49f-4c98-9127-a0af3a1030a0.png">

**Comment by SimonSchick** [comment]
Likewise `Applying patch failed: command 'git.stageAll' not found` does also occur when manually unstaging files first.

**Comment by connor4312** [comment]
Oh, though it still makes the comment: https://github.com/microsoft/vscode/pull/131405#issuecomment-904049334

**Comment by eamodio** [comment]
I believe that is contributed by the GHPR extension, please open the issue there.
