### ISSUE TITLE
[Bug] Selection background is not rendered correctly

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131458]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

Notice at the second round of selections, the second `foo` isn't highlighted after pressing <kbd>Escape</kbd>:

![STG 2021-08-24 09_26_16](https://user-images.githubusercontent.com/28700378/130540670-81562f14-bfea-4ac0-8323-a685e557956f.gif)

**Comment by maldahleh** [comment]
I'm interested in trying this out. Would you have any tips on where to start?

**Comment by alexdima** [comment]
@maldahleh The logic for this is implemented [here](https://github.com/microsoft/vscode/blob/ff1e16eebb93af79fd6d7af1356c4003a120c563/src/vs/editor/contrib/multicursor/multicursor.ts#L851)

**Comment by maldahleh** [comment]
@alexdima Thank you

**Comment by pdrgds** [comment]
@alexdima fixed on https://github.com/microsoft/vscode/pull/136625 - let me know if anything needs to be changed.
