### ISSUE TITLE
[javascript][highlighting] Parsing error on non latin characters

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#13147]
- VSCode Version: 1.5.3
- OS Version: Win 10

Steps to Reproduce:

1. Create new file
2. switch to javascript language syntax
3. Paste that:
```javascript
const somevargood = `somevar1`;

const абв_badvar = `somevar2`;

var  абв_badvar = `somevar3`;
const somevar = `somevar2`;
if( some ) then execfunc();
```
![image](https://cloud.githubusercontent.com/assets/1981785/19029816/1f3ccdf4-8952-11e6-990d-09d7107ec36c.png)

**Comment by Tyriar** [comment]
Moved to https://github.com/Microsoft/TypeScript-TmLanguage/issues/288
