### ISSUE TITLE
Terminal Text randomly duplicates when backspacing in split-screen mode.

### ISSUE THREAD

**Issue by TechStudent11** [microsoft/vscode#131440]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows 10 Version 20H2

Steps to Reproduce:

1. Open VSCode in split-screen mode.
2. Open a new terminal
3. Try typing out a command
4. Try backspacing

Here is a screenshot:
![image](https://user-images.githubusercontent.com/76978184/130511574-856c089d-9355-4f6a-86b8-a57250714515.png)

**Comment by TechStudent11** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Weird backspace handling in terminal/pwsh (#127098)](https://www.github.com/microsoft/vscode/issues/127098)

That is not what is happening but hey looks like that is an experimental feature.

**Comment by TechStudent11** [comment]
I know that a lot of issues get raised on the VSCode repo, but it's been 7 days and this issue is getting worse. I now normally have my windows in this layout: A VSCode Window taking up half my screen space, a Microsoft Edge window takes up a quarter, and another VSCode window takes up another quarter. With the half VSCode window, if I type a command and try backspacing, randomly it just cuts into the path. I don't have a screenshot, but it looks something like this after backspacing: `C:git commit rojects/Nexa> git comm-m "commit message"`.

**Comment by meganrogge** [comment]
Hey, yes lots of issues coming in. Sorry for the delay. Could you pls provide a gif of the issue so I can investigate it?

**Comment by TechStudent11** [comment]
@meganrogge Once it happens again, I'll send a GIF, because it happens randomly.

**Comment by meganrogge** [comment]
ok sounds good thanks

**Comment by TechStudent11** [comment]
bruh I said it happens randomly...

**Comment by TechStudent11** [comment]
@meganrogge So it has happened again.
![image](https://user-images.githubusercontent.com/76978184/133896767-67f9a1fe-39d3-4d2b-b295-258743b50b94.png)

**Comment by TarunavBA** [comment]
Try changing the front slash (/) to back slash (\)

**Comment by TechStudent11** [comment]
@TarunavBA how is that gonna work?

**Comment by TechStudent11** [comment]
@vscode-triage-bot how about you re-open the issue, please?
