### ISSUE TITLE
Unable to run vs code as root in Redhat 8 & Ubuntu 20

### ISSUE THREAD

**Issue by Veverke** [microsoft/vscode#131482]
Issue Type: <b>Bug</b>

Using `sudo code --user-data-dir={whatever}` (or even `--user-data-dir` alone) works in Ubuntu 16. Does not in Ubuntu 20 and Redhat 8.
I know there are other posts/issues on the same problem, but usually they get it sorted out by a specific format of the `user-data-dir` parameter value. It does not work for me.

I tried commenting out `/usr/bin/code`'s `if [ "${id -u})" = "0" ]; then` block thinking I would bypass the root validation and that would help, but no.

I tried running `sudo code --user-data-dir={whatever} --log trace`, checked the log files and can't find any clue.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 4.18.0-305.el8.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 3128)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 1|
|Memory (System)|7.48GB (0.29GB free)|
|Process Argv|--unity-launch --crash-reporter-id ac82e985-2992-4205-a9ac-6beb2632b939|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.6.0
dotnet-test-explorer|for|0.7.6
bash-ide-vscode|mad|1.11.0
git-graph|mhu|1.30.0
csharp|ms-|1.23.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793
vsdyn478:30356813

```

</details>

**Comment by Veverke** [comment]
By the way, the auto generated info on my VS Code instance was taken from my Windows machine where I had internet, not from the Redhat machine I mentioned.

**Comment by Tyriar** [comment]
We don't really support launching code with sudo:

https://github.com/microsoft/vscode/blob/38e500687d46d56e630822f29ff446c5e9e82423/resources/linux/bin/code.sh#L32-L35

You get a notification in vscode when sudo is needed to save write protected files.

**Comment by Tyriar** [comment]
FYI @deepak1556 in case I've missed something

**Comment by deepak1556** [comment]
We have been partially running with chromium sandbox on linux https://code.visualstudio.com/updates/v1_59#_progress-for-electron-sandbox-support. Running as root is not supported in this mode, it is very likely you are not hitting the sandbox layer in ubuntu 16. Can you provide the output of `sudo code --verbose` from either your RHEL8 or ubuntu 20 device to confirm, thanks!

**Comment by Veverke** [comment]
@deepak1556 : you are right.
Thanks @Tyriar , @deepak1556 , although problem does not have a resolution, you helped me understand this is a known issue and not something on my side.

**Ubuntu 20.04.2 LTS verbose output:**
```
ubuntu-build@ubuntu-build:~$ sudo code --verbose --user-data-dir
[4233:0825/150341.073920:FATAL:electron_main_delegate.cc(263)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Redhat 20.4 verbose output:** 
```
[redhat-build@redhat-build ~]$ sudo code --verbose --user-data-dir
[0825/145731.147136:FATAL:electron_main_delegate.cc(309)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Comment by Veverke** [comment]
By the way, the "working" ubuntu is 18.04.4, although I mentioned it was 16 - must have been recently updated. Can't run the same on 16 to double check, though.
