### ISSUE TITLE
No auto-detect in notebook cell language picker

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#131487]
Testing #131451

1. Have `"workbench.editor.languageDetection": true`. 
2. Open a .ipynb file with the Notebook editor.
3. Click in a python cell.
4. Open the language picker for the cell.
5. 
![image](https://user-images.githubusercontent.com/38270282/130592710-85521fcb-0735-498f-9f7a-b67bd4aa6c91.png)

**Comment by TylerLeonhardt** [comment]
@alexr00 just to confirm... you tested this with the latest insiders? I added it yesterday which is why I ask.

**Comment by roblourens** [comment]
Works for me

**Comment by alexr00** [comment]
I think the latest build hadn't been released yet. Works now that I'm on yesterday's build!
