### ISSUE TITLE
tasks.json suppressTaskName doesn't work 

### ISSUE THREAD

**Issue by jonnyguo1988** [Microsoft/vscode#1314]
Hi
Please see the attachment
![tasks](https://cloud.githubusercontent.com/assets/14086700/11802894/615fd810-a330-11e5-9f51-34912043a7ab.png)

I set the "suppressTaskName": false but it still put the task name after command in Output window.

Another problem, I can only add one command in one project, which mean I can only use one command for one project, it's a big limitation.

Thanks.

**Comment by jonnyguo1988** [comment]
For example I have a project and I configure a build task for it, but I also want to configure a unit test task, code analysis task and so on, but vs code cannot do it. Or , I have to write a broker tool for it.

**Comment by dbaeumer** [comment]
@jonnyguo1988 to suppress the task name set "suppressTaskName": true

**Comment by jonnyguo1988** [comment]
@dbaeumer  Thank you I tried and succeed. because when i set this option is promotes "true" is the default value and it doesn't work when i did set it which mislead me to set it as false.

Thank you.
