### ISSUE TITLE
Bring back Workspace and Run and Debug feature

### ISSUE THREAD

**Issue by richiephp** [microsoft/vscode#131417]
Workspace and Run and debug

Regarding this. 
https://github.com/microsoft/vscode-edge-devtools/issues/471

I had everything set up with a workspace with a lot of projects up and running, only to think that there was a problem, once vs code was updated only a couple of weeks ago. The Run and Debug function did not run properly with Workspaces after the update and since then, only to find it was "normal behaviour" with Workspace

**Comment by roblourens** [comment]
Like https://github.com/microsoft/vscode-edge-devtools/issues/471#issuecomment-903835218 says, this is by design when  to make that view accessible all the time https://github.com/microsoft/vscode/issues/120163
