### ISSUE TITLE
Missing support for `__END__` directive in ruby grammar

### ISSUE THREAD

**Issue by brasic** [microsoft/vscode#131470]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: tested with 1.59 and 1.60.0-insider (44568e5947efa4811419e529e80fb14b7554cf61)
- OS Version: MacOS 10.15.7

In ruby source files, [the directive `__END__` ](https://ruby-doc.org/docs/keywords/1.9/files/keywords_rb.html#M000003)is not recognized as language syntax.  All text after this line should be considered commented out.  Instead it's treated as a method call and subsequent code is highlighted.  Autocompletion also attempts to suggest completions for this and refuses to let me actually enter the keyword unless I work harder than I should have to.  (i.e. if I type `__END__<return>`, the text inserted will not be what I typed.  Instead I have to type `__END__<space><return>` and then go clean up the extra space since the directive is only valid when it is by itself on a line.

Steps to Reproduce:

1. open an existing ruby source file
2. type `__END__` by itself in the middle of the file.

Here's a video demonstrating the issue.

https://user-images.githubusercontent.com/677224/130555686-45e2c21e-5e48-4332-af17-748341ff0efa.mov

I would expect syntax highlighting to respect the directive something like the following:

https://user-images.githubusercontent.com/677224/130556225-733f8e1a-f391-4aa0-9d35-e9337218ddc8.mov

**Comment by jkeech** [comment]
It looks like the built-in textmate grammar supports the `__END__` directive ([reference](https://github.dev/microsoft/vscode/blob/main/extensions/ruby/syntaxes/ruby.tmLanguage.json#L119-L139)), but the "VSCode Ruby" extension doesn't support it. When the Ruby extension is installed, it installs the dependent VSCode Ruby extension which takes over the syntax highlighting.

This issue looks related to https://github.com/rubyide/vscode-ruby/issues/729.

**Comment by aeschli** [comment]
Thanks @jkeech for the investigation.
@brasic Can you file the issue against the ruby extension?
