### ISSUE TITLE
Test Bracket Pair Colorization

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131416]
Refs: https://github.com/microsoft/vscode/issues/128465

- [ ] anyOS @donjayamanne
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131416%0A%0A&assignees=hediet)

---

# Preparation

* Enable bracket pair colorization (currently enabled by default, will change on 25/08): `"editor.bracketPairColorization.enabled": true`.

# Tasks

* Verify bracket pair colorization is correct, in particular after complex edits and when brackets appear in comments or strings
* Verify that unclosed bracket pairs get closed automatically when a parent bracket pair is closed: `(])` vs `[(])`
* Verify that closing brackets that have no opening bracket pair are highlighted red.
* Verify that colors can be customized and new colors can be added (up to 6):
    ```json5
    "workbench.colorCustomizations": {
        "editorBracketHighlight.foreground1": "#FFD700",
        "editorBracketHighlight.foreground2": "#DA70D6",
        "editorBracketHighlight.foreground3": "#87CEFA",
        // ...
    },
    ```
* Verify that bracket pair colorization adds no noticable delay for medium-sized files.

**Comment by DonJayamanne** [comment]
time to un-install the extension from he marketplace that already does this.

**Comment by DonJayamanne** [comment]
Works perfectly well, one less extension
