### ISSUE TITLE
How to prevent VSCode correcting my code

### ISSUE THREAD

**Issue by nguyenaivuong** [microsoft/vscode#131473]
Issue Type: <b>Bug</b>

My VSCode corrects my code automatically. I don't know how to control it.
Here is the video of the problem: 
https://drive.google.com/file/d/10LNWw006AKhLA1u_iId-kMjcBuJCNtoW/view?usp=sharing

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.86GB free)|
|Process Argv|--crash-reporter-id e6502788-80c5-4737-ada5-90f5ac9e0738|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.4
aixcoder|aix|3.1.8
code-tester|Aka|0.0.6
Bookmarks|ale|13.1.0
bracket-pair-colorizer|Coe|1.0.61
devdocs|dei|0.2.0
competitive-programming-helper|Div|5.8.5
githistory|don|0.6.18
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
copilot|Git|1.3.2467
vscode-pull-request-github|Git|0.29.2
gc-excelviewer|Gra|3.0.43
kite|kit|0.147.0
rainbow-csv|mec|1.9.1
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
cpptools|ms-|1.5.1
vsliveshare|ms-|1.0.4673
vsliveshare-audio|ms-|0.1.91
color-highlight|nau|2.4.0
material-icon-theme|PKi|4.9.0
vscode-sort-json|ric|1.20.0
indenticator|Sir|0.7.0
music-time|sof|2.2.22
swdc-vscode|sof|2.5.24
tabnine-vscode|Tab|3.4.22
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn420:30356812

```

</details>

**Comment by kaffarell** [comment]
I think this is a feature/issue of tabnine. Try starting vscode without extensions `code --disable-extensions` and see if the problem persists.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

As correctly mentioned above it's most likely an extension.
Moreover VS Code doesn't provide advanced support for C/C++
