### ISSUE TITLE
Create Terminal location API tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131425]
We could create tests that:

- Create a terminal in editor and verify it shows up
- Open a text document and then create a terminal in editor and verify it's in the same group
- Create a terminal to the side and verify it's in a new group
- Open a text document and then create a terminal to the side and verify it's in a new group
- Create terminals using view column 1, 2, 3
- Create a terminal in editor are and then create a terminal using parentTerminal, verify it's in a new group
- Check if editor tests have a way of testing preserveFocus (perhaps checking context key?)
- Duplicate some tests for `ExtensionTerminalOptions.location` to make sure it also works
- Make sure activeTerminal works for editor terminals

**Comment by meganrogge** [comment]
This code is pretty stable now.
