### ISSUE TITLE
I have enabled workspace library execution but tslint is still baned 

### ISSUE THREAD

**Issue by JYC-99** [microsoft/vscode#131463]
Issue Type: <b>Bug</b>

I have to enable it EVERY TIME when I start a new session or relaunch my vscode. 
![image](https://user-images.githubusercontent.com/5934735/130545467-63cb3c20-5973-493b-9c36-0b515e564c77.png)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (16.97GB free)|
|Process Argv|--crash-reporter-id 69b762a0-0b46-4dbd-8877-b709bd186ffc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-yarn|gam|2.0.0
vscode-leetcode|Lee|0.18.0
inline-parameters|lia|0.2.1
prettify-json|moh|0.0.3
vscode-scss|mrm|0.10.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
csharp|ms-|1.23.14
vscode-edge-devtools|ms-|1.3.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-typescript-tslint-plugin|ms-|1.3.3
team|ms-|1.161.1
debugger-for-edge|msj|1.0.15
vscode-jest|Ort|4.1.0
code-spell-checker|str|1.10.2
highlight-matching-tag|vin|0.10.1
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
dockerwalkthru:30344881
bridge0723:30353136

```

</details>

**Comment by JYC-99** [comment]
Same issue with vscode insider, too.

**Comment by JYC-99** [comment]
Ping on this issue and update: I'm seeing this prompt even every time I do "git checkout" or "git merge". It is really annoying.

**Comment by mjbvz** [comment]
Please file this against TSLint

**Comment by mjbvz** [comment]
And also make sure you have installed VS Code in a location  where it is able to write your user data

**Comment by JYC-99** [comment]
> And also make sure you have installed VS Code in a location where it is able to write your user data so it can save this setting

@mjbvz Thanks for answering this question. I'm trying re-installing it now.

1. I have been using VsCode and tslint extension for years. I believe I did not change the install location and am seeing this issue in recent 2 months.
2. If the reason is that VS Code does not have correct permission to write the user data, why it did not prompt any alerts about the saving attempts failures?
