### ISSUE TITLE
Test: Windows 11 Store Installer

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131445]
Refs: #130410

- [x] windows: @TylerLeonhardt  (x64)
- [x] windows: @connor4312  (x86)
- [x] windows: @eamodio (arm64)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131445%0A%0A&assignees=sbatten)

---

**Test machine must be running Windows 11**

**For x86 only, there is no Windows 11 option which means this test is for a theoretical future. Please just try using the installer directly on Windows 10 (which is not signed so you will get additional prompts)**

https://github.com/microsoft/vscode-winsta11er/releases/tag/v0.0.3

This milestone, we created a simple executable installer for VS Code that can be deployed to the new Windows 11 Store. Currently, the first version of this installer has been deployed to the store and is available for those using Windows 11 Preview builds.

The installer will always install the latest stable release of VS Code and is completely silent.

To verify this installer:
1) Uninstall VS Code stable from the target machine.
2) Open the Microsoft Store on the target machine and search *Visual Studio Code*
3) Click *Install*
4) Perform general sanity testing on the newly installed VS Code

The store has no uninstall or update process, this is all managed just like it is with the normal user VS Code install on Windows.

Some additional fun testing:
1) Try the install process with a pre-existing install
2) Try the install process with the system install pre-installed
3) Try cutting the network just after the store finishes downloading the installer but while its still installing (this should break the executable and bubble up an error to the store)

**Comment by TylerLeonhardt** [comment]
Uninstalled with store opened? -> have to restart store to see install button
network cut out? -> have to restart store to see install button (retry button doesn't work)

I feel like these are not vscode bugs... but are Store bugs.

**Comment by TylerLeonhardt** [comment]
on the VS Code side everything seems to be working.

**Comment by connor4312** [comment]
I'm blocked on https://github.com/microsoft/vscode/issues/131549

**Comment by eamodio** [comment]
I saw the same as @connor4312, but the install did succeed for me (was able to launch VS Code from the start menu). The other issues I saw, I don't know how much control over the experience we have:

- There was no launch button in the Store for VS Code, just a disabled "Installed" button
- VS Code doesn't show up in the library in the Store

**Comment by connor4312** [comment]
Works now!
