### ISSUE TITLE
Scroll focus is lost when adding items dynamically to end of quickpick list

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#131457]
Hi Python extension dev here 👋

As mentioned in https://github.com/microsoft/vscode/issues/21372#issuecomment-419864437, I tried attempting to implement dynamic quickpick using the API `createQuickPick` and then adding elements to the end of the quickpick list doing something like,

```
quickpick.items = <new item list>;
```

Although if a user happens to scroll down the list while the list is loading, the scroll focus is reset to the top position every time the quickpick list is edited, even though no active item is present.

![interpreterlist](https://user-images.githubusercontent.com/13199757/130537339-b62a0a8b-c3b5-4070-9a51-e3457a2c9306.gif)

In case an active item is present, the reset position always focuses on the item. I request an API to add elements to the list in such a way that the scroll doesn't loose focus.

cc @jrieken

**Comment by gjsjohnmurray** [comment]
Maybe related to #109969

**Comment by TylerLeonhardt** [comment]
Yeah this is a tricky one... `items` is readonly by-design... but I think we need some way to add to the end of the list without refreshing the list.

I'm wondering if we can support `.push()` on `.items` with the idea that it doesn't change the cursor top. Or we could call it `.append()`...

What do you think @chrmarti?

**Comment by TylerLeonhardt** [comment]
Also related https://github.com/microsoft/vscode/issues/76193

**Comment by karrtikr** [comment]
Actually I would also like the functionality to edit the item in place without scroll reset, as visible in the GIF. So just append won't do it.

**Comment by chrmarti** [comment]
`quickpick.insertItems(index, additionalItems)` might be similar in complexity to implement as `quickpick.appendItem()` and a bit more general. It makes sense to consider this together with the other issues (removing and replacing items).

**Comment by TylerLeonhardt** [comment]
The overall fix for this issue is being tracked in: https://github.com/microsoft/vscode/issues/132068
I just checked in a proposed API built on top of the fix for Core (also checked in today) please give it a go and let me know what you think.

**Comment by karrtikr** [comment]
Nice, can I somehow download the Insiders now? Or do I have to wait for tomorrow's Insider release?

**Comment by TylerLeonhardt** [comment]
@karrtikr you can run from sources or wait for tomorrow's insider release

**Comment by karrtikr** [comment]
API works great. Only downside I see is that the scroll focus is not maintained when elements are deleted in the middle of the list, i.e the visible items change.

**Comment by TylerLeonhardt** [comment]
@karrtikr curious what you see... Does it jump up to the top? A gif/video would be ideal.

**Comment by karrtikr** [comment]
It doesn't jump to the top, it just shifts a bit. I'll see if I can get the GIF.

**Comment by karrtikr** [comment]
I have a list which populates after I click the refresh button. I scroll to the middle of the list and slowly start deleting items at random over a course of 30 seconds, this is what I see:

![interpreterlistshift](https://user-images.githubusercontent.com/13199757/132599031-114352b9-0540-4936-b5c5-481cbb74b226.gif)

I guess it's expected since there is no way for VSCode to know if these are new items everytime I assign `quickpick.items`.

**Comment by TylerLeonhardt** [comment]
Yep I agree. Thanks for sharing!
