### ISSUE TITLE
Strange insiders crash

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13140]
- VSCode Version: Code - Insiders 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d, 2016-10-01T00:34:33.697Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.sort-lines-1.1.0, Tyriar.theme-glacier-0.0.10, Tyriar.vscode-terminal-here-0.0.5, christian-kohler.path-intellisense-1.0.2, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, eg2.tslint-0.5.39, felipecaputo.git-project-manager-0.1.15, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.2, rebornix.Ruby-0.8.0, rebornix.nova-0.0.5, redhat.java-0.0.4, ryu1kn.annotator-0.10.0, ryzngard.vscode-header-source-1.0.4

Steps to Reproduce:
1. I was coding in a JavaScript file, syntax highlighting was broken due to the issue with ms-`vscode.typescript-javascript-grammar-0.0.2`
2. All of a sudden I got a crash dialog and got asked to relaunch, I did
3. The instance of VS Code I was working on remained fine
4. Another Insiders instance launched with 2 files open I did not recognize:

![image](https://cloud.githubusercontent.com/assets/2193314/19023264/346d919e-889f-11e6-9d8c-b869c81c49c2.png)

![image](https://cloud.githubusercontent.com/assets/2193314/19023269/53473688-889f-11e6-92ff-e3ef2982ff1a.png)

This has only happened once.

**Comment by bpasero** [comment]
@Tyriar is this reproducible? did you have 2 windows open when this happened?

**Comment by dbaeumer** [comment]
No idea how this happened.

**Comment by Tyriar** [comment]
Not sure if I had more than one Window open before the crash, I certainly didn't have server.js open. Haven't been able to reproduce and I doubt I will, if you both have no idea then feel free to close the issue. @bpasero do you see any way https://github.com/Microsoft/vscode/blob/6fa85223efb25ad7ce3e534c7eb07edd9524bd6d/extensions/typescript/src/utils/electron.ts#L118 could break?

**Comment by dbaeumer** [comment]
It is indeed very wired but I have no idea how VS Code could decide to open files from an extension implementation. I opt to close.

**Comment by Tyriar** [comment]
@bpasero feel free to close

**Comment by Tyriar** [comment]
Some more info, this is in my storage.json:

```js
{
    "openedPathsList": {
        "files": [
            "/home/daniel/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.0.7/server/server.js",
            "/home/daniel/.vscode-insiders/extensions/dbaeumer.vscode-eslint-1.0.7/node_modules/vscode-languageclient/lib/utils/electronForkStart",
            "/home/daniel/playground/ts-pg/src/a.ts",
            "/home/daniel/Downloads/google44a591bcde78497c.html",
            "/home/daniel/dev/Microsoft/vscode/appveyor.yml",
            "/home/daniel/Downloads/vttest-20140305/vttest.h",
            "/home/daniel/Downloads/xterm-325/input.c",
            "/home/daniel/Downloads/xterm-325/charsets.c",
            "/home/daniel/Downloads/xterm-325/charproc.c",
            "/home/daniel/temp/shiporder.xsd",
            "/home/daniel/dev/dotfiles/waderyan.gitblame",
            "/home/daniel/dev/dotfiles/ryzngard.vscode-header-source",
            "/home/daniel/dev/dotfiles/ms-vscode.csharp"
        ],
...
```

**Comment by bpasero** [comment]
I am not sure what that JSON file is telling us? If an instance decides to open electronForkStart, those files will show in the `openedPathsList`.

I am moving this to you to provide more steps to reproduce so that we can work on a fix.

**Comment by Tyriar** [comment]
Haven't seen since
