### ISSUE TITLE
slow compiling

### ISSUE THREAD

**Issue by Billaalch** [microsoft/vscode#131474]
Issue Type: <b>Performance Issue</b>

I'm workig on a react app. I'm using the in build terminal of vs code. after i run "npm start" my dev server is ready, but slow to load. and when i make changes to code, the compile time is pretty slow. it is happening nowadays and not before.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.68GB free)|
|Process Argv|--crash-reporter-id b7376296-dd5a-4adb-a807-2f3556c2b7d3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	  6704	code main
    0	   213	  1592	   window (Signin.jsx - food - Visual Studio Code)
    0	    74	  3676	     searchService
    0	    14	 10392	     watcherService 
    0	    11	  8040	       console-window-host (Windows internal process)
    0	   270	 10676	     extensionHost
    0	   117	  1312	       electron_node tsserver.js 
    0	    72	  2684	       electron_node serverMain.js 
    0	   370	 10292	       electron_node tsserver.js 
    0	    89	  9596	         electron_node typingsInstaller.js typesMap.js 
    0	   186	  3084	   gpu-process
    0	    97	  7564	   shared-process
    0	    72	  8964	     ptyHost
    0	     6	  7948	       console-window-host (Windows internal process)
    0	    69	  9588	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	  9308	         C:\Windows\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    32	  7336	           "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" start
    0	     4	  6856	             C:\Windows\system32\cmd.exe /d /s /c react-scripts start
    0	    24	  4840	               electron_node react-scripts.js 
    0	   609	  4804	                 "C:\Program Files\nodejs\node.exe" "F:\REACT DEV\food\node_modules\react-scripts\scripts\start.js"
    0	    37	  8508	   utility
    0	    24	  8840	   crashpad-handler
    0	    81	  9520	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Signin.jsx - food - Visual Studio Code)
|    Folder (food): 41 files
|      File types: jsx(11) js(5) json(3) png(3) html(2) gitignore(1) ico(1)
|                  txt(1) md(1) css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
auto-rename-tag|for|0.1.8
vscode-power-mode|hoo|2.2.0
vscode-styled-components|jpo|1.6.6
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464cf:30350173
bridge0723:30353136
vsdyn321cf:30356811

```

</details>

**Comment by Billaalch** [comment]
No

**Comment by Tyriar** [comment]
Do the powershell environments of either terminal differ? It's out of our hands once we create the process and I think that's the only thing that could change the behavior.
