### ISSUE TITLE
QuickPick and InputBox prompts are always truncated and never wrapped

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#131460]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60-insiders
- OS Version: macOS 11.4

I believe that commit https://github.com/microsoft/vscode/commit/f4f6a69ac19ed88cd27ce623306c2d937bd8c9d3 which was a fix for https://github.com/microsoft/vscode/issues/130935 introduced this bug unintentionally. Words that overflow should break and wrap instead of truncating, and it should break on whitespace like before https://github.com/microsoft/vscode/commit/f4f6a69ac19ed88cd27ce623306c2d937bd8c9d3. Currently ALL prompts for QuickPick and InputBox elements are truncated with an ellipse.

Instead of using `text-overflow: ellipse;` I think using `overflow-wrap: break-word;` will give the wanted behavior.

More info: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text#breaking_long_words

Steps to Reproduce:

1. View any InputBox or QuickPick on insiders that has prompt value long enough to overflow and truncate.

![image](https://user-images.githubusercontent.com/12476526/130540916-5cc05f9c-0e24-44ab-aa1d-9d2c66fa0f64.png)

**Comment by TylerLeonhardt** [comment]
Thanks! `overflow-wrap: break-word;` seems to work nicely.

**Comment by alexweininger** [comment]
> Thanks! `overflow-wrap: break-word;` seems to work nicely.

Thanks for the quick fix! 🔥 🏅
