### ISSUE TITLE
VSCode doesn't read form stdin on Fedora 34

### ISSUE THREAD

**Issue by ElSamhaa** [microsoft/vscode#131430]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Linux x64 5.13.12-200.fc34.x86_64

Steps to Reproduce:

1. Run `ps aux | grep code | code -`
2. VSCode starts with no open editors and no console errors.

![image](https://user-images.githubusercontent.com/34912861/130495094-0f70fc98-98cc-4ee7-9619-d4925477a3e4.png)

**Comment by bpasero** [comment]
Could be same as https://github.com/microsoft/vscode/issues/131148

**Comment by ElSamhaa** [comment]
@TylerLeonhardt Worked on latest insiders 1.60

**Comment by TylerLeonhardt** [comment]
Thanks! Closing this since it's fixed. Next week's release will have the fix.

**Comment by ElSamhaa** [comment]
@TylerLeonhardt Issue is still there after updating to stable 1.60. I think we should reopen.

**Comment by ElSamhaa** [comment]
To my surprise, it worked in my latest attempt just about now, with and without extensions. My guess is that the workspace-trust component might have something to do with this issue.

Will observe and report back if it happened again.
