### ISSUE TITLE
Test shortTitle-property for commands

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#131423]
Refs: https://github.com/microsoft/vscode/issues/126457

- [x] anyOS @JacksonKearl 
- [x] anyOS @sandy081

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23131423%0A%0A&assignees=jrieken)

---

We have finalized the shortTitle-property for package.json-contributed commands. Test that

* the property is documented
* it can be used _without_ enabling proposed API

**Comment by sandy081** [comment]
Unassigning @rebornix as he is not available for testing

**Comment by JacksonKearl** [comment]
It's downright lovely.
