### ISSUE TITLE
Filter by folder

### ISSUE THREAD

**Issue by phaistonian** [microsoft/vscode#131478]
Filter by type is a great feature, but, at times, what you need is to filter by folder.

In other words, you want your project to have all the folders hidden but the ones you are working on.

You can open a new workspace based on a folder, but then you end up with all sorts of issues, e.g. your `jsconfig` not being referenced anymore since the root is different than the _master_ project.

## Suggestion

- Enable filtering by folder (same as filtering by type).
- Enable right-clicking on a folder and selecting "hide others".

I am certain those would provide a major boost to productivity when dealing with large projects.

Ps: Unsecussefully tried to find extensions for the above.

**Comment by phaistonian** [comment]
@TylerLeonhardt I was referring to this functionality (see attachment) and how handy it would be have been if you could use the same UI to also filter by folder, i.e. only show results (folder and nested items) for matched folder(s).

![CleanShot 2021-08-28 at 08 09 29@2x](https://user-images.githubusercontent.com/796530/131207010-16a0dc90-c1b6-4378-80a3-f438161922be.png)

**Comment by TylerLeonhardt** [comment]
I believe @joaomoreno owns this?
