### ISSUE TITLE
Set Value Does Not Update Variables in JS Debug Nightly

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131488]
Testing #130170

Note the value of x.

![image](https://user-images.githubusercontent.com/2931520/130595253-10182e92-7f83-4c27-904c-94a02485f331.png)

**Comment by isidorn** [comment]
I believe this is a known limitation. Variables are cached too aggressively.
For now assigning to @connor4312 as he would know more

**Comment by connor4312** [comment]
Yea, this is a known issue in V8. Even if we re-request the properties of the call stack it doesn't return the updated values.
