### ISSUE TITLE
Problems in active file are not shown

### ISSUE THREAD

**Issue by mkistler** [microsoft/vscode#131444]
Issue Type: <b>Bug</b>

I selected the "Show Active File Only" in the "Problems" panel and VSCode shows "No problems have been detected in the current file", but that is clearly wrong because:
- In the file explorer the file shows "9+" problems,
- There is a problem visible in the open file window,
- If I remove the "Show Active File Only" filter, I find find the file in the list and it shows 29 problems.

![image](https://user-images.githubusercontent.com/800728/130522157-28acc0d3-120e-461e-aa96-44f2bd749fba.png)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|. --crash-reporter-id 08dd8079-cddc-4c8b-a317-9a3409e8bae1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.5.2
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
docs-linting|doc|0.0.7
clipboard-manager|Edg|1.4.2
vscode-jest-runner|fir|0.4.44
go|gol|0.27.1
csharp|ms-|1.23.14
python|ms-|2021.8.1147840270
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-yaml|red|0.22.0
spectral|sto|0.2.5
code-spell-checker|str|1.10.2

</details>

**Comment by mkistler** [comment]
There are some similarities with #99155, but that looks like a very special case caused by the structure of notebooks -- or at least it is presented that way.  This issue is occurring in a completely different file type that does not have the complex structure of notebooks.

**Comment by mkistler** [comment]
I've just reproduced the problem in a completely separate repo with a different file type, .md.

Unfiltered problems:
![image](https://user-images.githubusercontent.com/800728/130524459-3be251c0-e15d-4dc2-a499-6a9e3aae82eb.png)


Filtered problems:
![image](https://user-images.githubusercontent.com/800728/130524383-41f5fda0-8299-4a89-ad36-b82121197b8c.png)

**Comment by sandy081** [comment]
Can you please provide the steps to repro so that I can repro and diagnose the issue?

**Comment by mkistler** [comment]
@sandy081 Unfortunately I cannot get the same behavior today. I haven't updated my VSCode so I am at a loss to explain the difference.  Perhaps my previous VSCode had been running for a while and had leaked memory to point where some processing failed, but on a fresh session it passed. I will continue to test and let you know what I learn. (Thankfully I took screen shots (above) that confirm this _really did happen_ -- but there must be some environmental aspects that changed between yesterday and today.)

**Comment by sandy081** [comment]
Hmm I see. No worries and I believe you. It would be hard for me to diagnose without repro. I would close this for now and please feel free to reopen it if you can repro it again. Thanks for support.
