### ISSUE TITLE
bug without visual studio code without linux mint

### ISSUE THREAD

**Issue by lhmathias** [microsoft/vscode#131448]
Good night I'm using linux mint and this system is causing visual bugs! 

- VS Code Version:1.59
- OS Version: 19.3

https://photos.app.goo.gl/o4RVfBijzSSgC5Ft6
https://photos.app.goo.gl/BESFZ53ywdFQphcY7

**Comment by lhmathias** [comment]
even with the original version not being flatpack everything appears distorted!
https://photos.app.goo.gl/EJFdUF8tpSr267wp6

**Comment by deepak1556** [comment]
Seems like a gpu issue, are you running via any VM ? Can you provide the output of `code --verbose`
