### ISSUE TITLE
Intellisense doesnt work

### ISSUE THREAD

**Issue by SandorDebnar** [microsoft/vscode#131422]
Issue Type: <b>Feature Request</b>

I had yesterday a normal day with VS Code but today there is no more intellisense, no more problem checker... im blind..

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by mjbvz** [comment]
Closing as not actionable with more info
