### ISSUE TITLE
Unable to load a notebook with large output

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131575]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version:Mac

Steps to Reproduce:

1. Creat a Jupyter notebook and the the following cell:
```python
for i in range(0,1000000):
    print(i)
```
2. Give it some time to complete 1M iterations
3. Note the output is truncated & the notebook is usable.
4. Save the notebook & close it.
5. Re-load VS Code & open this notebook.
VS Code will hang

This is a regression from the current stable version

**Comment by mjbvz** [comment]
Not sure if this is the root cause but I saw this error stack in the dev tools while trying to save the file:

![Screen Shot 2021-08-24 at 3 04 17 PM](https://user-images.githubusercontent.com/12821956/130696245-2f6f9b2c-6f67-4fdb-b1ad-bdd424af39ec.png)

**Comment by DonJayamanne** [comment]
I had a PR to resolve that, I didn't realize the PR was not merged. I merged the PR with the fix earlier today.
I'm not running into issues in saving. it has been saved for me.
However, when I open the notebook it hangs (the exact same notebook can be opened in VS Code stable).

It seems as though we're not truncating the output when we load it (but only trucated when running a notebook)

**Comment by DonJayamanne** [comment]
Here's the PR i merged earlier to day https://github.com/microsoft/vscode/pull/131035/files

**Comment by DonJayamanne** [comment]
Wait a minute, theres an error in the Jupyter extension. Thanks @mjbvz I failed to notice that.
Will look into the jupyter extenssion to see what's going on, weird I cannto repro this (time to increase that iteration to 10M).

**Comment by DonJayamanne** [comment]
Never mind, i think i found the problem in the Jupyter extension.

**Comment by DonJayamanne** [comment]
Note: The issue in Jupyter extension is unrelated.

**Comment by DonJayamanne** [comment]
Damn, unable to repro this as well.
