### ISSUE TITLE
Insiders: Syntax highlighting: Some tokens not rendered in color specified for respective textmate scope

### ISSUE THREAD

**Issue by derkallevombau** [microsoft/vscode#131576]
Tested with:

Version: 1.60.0-insider
Commit: 5f19eee5dc9588ca96192f89587b5878b7d7180d
Date: 2021-08-24T18:11:19.257Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.0-8-amd64

Some examples:

![VS Code Insiders - wrong color - example 1](https://user-images.githubusercontent.com/35200962/130694335-a104e173-cd16-45f7-a5fa-06c10f997d29.png)
![VS Code Insiders - wrong color - example 2](https://user-images.githubusercontent.com/35200962/130694359-d6375f87-1072-4d3d-91eb-a94c97fb7cfc.png)

In normal VS Code, everything is fine.

**Comment by IllusionMH** [comment]
/question

This is Brackets Pair Colorization implemented in #129231 which is not released to stable yet and [enabled temporarily by default](https://github.com/microsoft/vscode/issues/131246#issuecomment-903476282) in Insiders for testing purposes.

**Comment by derkallevombau** [comment]
Thank you for the link @IllusionMH, I disabled it.
