### ISSUE TITLE
Locked groups: allow `Alt+Enter` to forcefully open in a locked group from quick pick

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131581]
Testing #131196

If a group is locked, using the quick pick to open a file has the following behaviour:

**Unlocked Group**
Enter: Open in group
Alt-Enter: Open to the side

**Locked Group**
Enter: Open in unlocked group or to the side
Alt-Enter: Open to the side

Could we make alt-enter open in the current group?

**Comment by bpasero** [comment]
Would like to wait for more feedback on this, sounds reasonable to me.

//cc @Tyriar if this is a usecase for terminals.

**Comment by bpasero** [comment]
Actually it would result in a bit of inconsistency because `Alt+Enter` is specifically meant to open a new group to the side while with a locked group, the editor would open in any of the non-locked groups and only open a new group when there is no unlocked.
