### ISSUE TITLE
Contribute to documentSelector for HTML with a custom language id

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode#131531]
There are a lot of issues about how to use HTML language service with custom language to benefit with HTML language feature but all solution works if you are in TypeScript Land. 

I have a language server written in Java and I have a custom language id bind with this language server. I would like to benefit with completion,validation, etc from HTML and the only solution that I see is to give the capability to contribute to documentSelector like suggested in https://github.com/microsoft/vscode/issues/88377#issuecomment-573183584

https://github.com/microsoft/vscode/blob/76d0b308ededd3a706d26fb1ccc564428248cd29/extensions/html-language-features/client/src/htmlMain.ts#L73

We had the same problem with our project vscode-microprofile and we give the capability to contribute to document selector from package.json

Here the code which create documentSelector https://github.com/redhat-developer/vscode-microprofile/blob/9cddbc13541c50fce9f44199374eccc2d7d9a274/src/extension.ts#L167

Here a sample of package.json which contribute to document selector https://github.com/redhat-developer/vscode-quarkus/blob/9cb7a2dfcb2c503a7dbac910e0c5765283dda860/package.json#L66

If HTML could provide this feature,it should be fantastic.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/49210 is the issue to bind a language id to html so it inherits the HTML language capabilities

I always wanted to add that, but haven't been able to get the time for it. 
If someone wants to work on a PR with a proposal, that would be great.

Closing as a dup of #49210
