### ISSUE TITLE
Mouse hides the Inline Completion hover too easily

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131526]
https://github.com/microsoft/vscode/issues/131415

1. Trigger Inline Completion hover via keyboard (ctrl + k, ctrl + i)
2. Try to use the mouse to click on some actions in the hover -> hover hides as soon as mouse is moved

Regular editor hovers are not this delicate.

**Comment by hediet** [comment]
Are you fine with waiting to address this once at least 5 people expressed their interest in this?

I doubt many people use the keyboard to trigger the hover but only then switch to the mouse to move to click into it.

**Comment by isidorn** [comment]
@hediet of course. I do not think this is something for the endgame. I would keep it open and if no other users hit this feel free to close.

**Comment by hediet** [comment]
I did not see any user running into this, so I'll close this for now.

Feel free to reopen when people run into this.
