### ISSUE TITLE
Re-render custom outputs when trust state changes

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131579]
Testing https://github.com/microsoft/vscode/issues/130951

I recall seeing code that renderers markdown when the trust state changes, should we do the same thing for custom renderers?

**Comment by mjbvz** [comment]
I think this makes sense. @DonJayamanne @joyceerhl Are there any concerns about re-rendering python outputs when the user trusts a workspace? It should be pretty uncommon but I'm not sure if ipywidgets for example may have important UI state that would be lost 

We could also instead leave the re-rendering up the extension by adding a `onDidChangeWorkspaceTrust` event that the renderers can listen to

**Comment by DonJayamanne** [comment]
Sorry, I missed this, it should be fine to re-render the output.

**Comment by joyceerhl** [comment]
If the workspace is untrusted, users aren't able to run code/connect to kernels, so AFAIK there shouldn't be any live state in the widgets that would get lost with a rerender.

**Comment by mjbvz** [comment]
To verify:

1. Use the notebook renderer sample: https://github.com/microsoft/vscode-extension-samples/tree/main/notebook-renderer-sample
2. Start with an untrusted workspace
3. Open a notebook
4. Change the workspace trust
5. Verify that the renderer is invoked again to re-render the cells
