### ISSUE TITLE
Testing: empty space context menu

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131501]
Refs: https://github.com/microsoft/vscode-python/issues/17040

Currently when you context menu into an empty area in the testing view nothing happens.
I suggest to have a context menu with some global actions. Here are some candidate:
* Run All Tests
* Debug All Tests
* Refresh Tests
* Unhide All Tests
* Clear All Results

For simpler projects the empty area can be quite large and I think we should use it.

**Comment by connor4312** [comment]
Haven't really heard others wanting this, will close for now
