### ISSUE TITLE
Failed to save 'httpd.conf': A system error occured (EACCES: permission denied, open

### ISSUE THREAD

**Issue by nurp** [Microsoft/vscode#13152]
- VSCode Version: 1.5.3 (1.5.3)
- OS Version: EL Capitan

Steps to Reproduce:

1. In a terminal window type: open /etc/apache/httpd.conf (or a file owned by root)
2. make changes to the file and cmd+s to save.
3. Error appears on the title bar: Failed to save 'httpd.conf': A system error occured (EACCES: permission denied, open '/private/etc/apache2/httpd.conf')

I expect VS Code to ask for my password for authorization. Because if I do the same things with Atom, it opens an OSX native window asking for password. Can we have the same window asking for password instead of giving error?
Also, I noticed that this path _/private/etc/apache2_ (in the error bar) is different than what I typed.

**Comment by Tyriar** [comment]
Currently you should be able to run `sudo code --user-data-dir <some temp folder>`, this is to be improved in:

- https://github.com/Microsoft/vscode/issues/1614
- https://github.com/Microsoft/vscode/issues/3884
- https://github.com/Microsoft/vscode/issues/5561
