### ISSUE TITLE
[FR] Format code to use the specified `tabSize` with the built-in formatter

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131598]
I have the following [AutoHotkey](https://www.autohotkey.com/) script sample, notice the code is indented by a _single_ space:

```
#z::
 MsgBox The Win-Z hotkey was pressed.
 Gosub MySubroutine
 return

MySubroutine:
 Sleep 1000
 return
```

I searched through the [VS Marketplace](https://marketplace.visualstudio.com/) but didn't find a usable formatter extension for AHK scripts.

I've configured `"editor.tabSize": 2`, is there a way to format the code to use the specified `tabSize` with the built-in formatter?

If that's not possible, please consider this a feature request for adding such a function.

**Comment by aeschli** [comment]
We have built-in formatter for only very few languages. You'll have to find one on the Marketplace.

If this is only about changing indentation, you can use the indentation entry in the status bar:
- Indent Using Space: 1
- Convert Indentation to Tab
- Indent using Tab: 2
- Convert Indentation to Spaces

![indent](https://user-images.githubusercontent.com/6461412/133791367-2b302777-155a-4d5f-95d4-c295e820507a.gif)
