### ISSUE TITLE
Can't easily search for Jupyter Notebook keymaps in Keyboard Shortcuts.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#131553]
Testing #131209

I would be great if I could easily identify or search for all the keyboard shortcuts related to notebooks (including those provided in notebook keymaps). In addition, I can't seem to search for shortcuts such as "D D" at all.

**Comment by joyceerhl** [comment]
@greazer is this not working for you? 

![image](https://user-images.githubusercontent.com/30305945/130698667-edaf0ecf-329f-4ba8-bdc6-62586cc950a1.png)
