### ISSUE TITLE
Consider deprecating "editor.inlineSuggest.mode" and "editor.suggest.previewMode"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131525]
Refs: https://github.com/microsoft/vscode/issues/131415

Consider deprecating these setting because:
1. Both of these setting a very hard to understand
2. There should be one setting that controls both these behaviours
3. `subword` option can lead to what appears as broken rendering

**Comment by san-coding** [comment]
is this a good first issue? if so can I take it up , I am new to open source

**Comment by isidorn** [comment]
@san-coding I suggest that you look into issues label with help-wanted. Here's a query https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

Or even better https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by hediet** [comment]
Are you fine with just not mentioning them in the schema?
I still find them quite useful for debugging issues with ghost text.

**Comment by isidorn** [comment]
Yes, I am fine with that of course.
