### ISSUE TITLE
CPU usage on 100%

### ISSUE THREAD

**Issue by wibed** [microsoft/vscode#131530]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: linux 5.13.12_1

Steps to Reproduce:

1. download docker image https://github.com/wibed/ideVScode
2. build and run using: `make sync && make run`
3. ensure you have x11 server on /tmp/.X11-unix
4. from within terminal opened in vscode:
  1. create a folder with a test swift package: `mkdir test && cd test && swift package init --type executable --name test`
  2. build and run the package: `swift build && swift run`
  3. watch the cpu usage spike event after restart

error:
vscode works at first glance, but as soon as the terminal is used to build && run a swift package the log message:
```
[23:0824/145821.704326:INFO:CONSOLE(630)] "%cTRACE color: #888 [File Watcher (node.js)] [CHANGED] /home/user/logs/20210824T145802/renderer1.log", source: vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
```

is spammed and spikes cpu usage.

full log message: https://termbin.com/ykx7

**Comment by meganrogge** [comment]
Could you please capture and share performance information using dev tools?

**Comment by wibed** [comment]
> Could you please capture and share performance information using dev tools?

could you provide the scope and tolls to capture performance information

**Comment by Tyriar** [comment]
You can check the process explorer (Help > Open Process Explorer) to see which process is the problem. If it's labelled with "window" you can open devtools (Help > Toggle Developer Tools) to capture and upload a performance profile:

![image](https://user-images.githubusercontent.com/2193314/132342541-fca08afd-ab28-41bf-8916-a5e5d16e3349.png)
