### ISSUE TITLE
Locked groups: inactive tab creates empty group

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131557]
Testing #131196

Opening a file from the explorer that is already an inactive tab in a locked group activates the tab but also creates an empty group.

![recording (1)](https://user-images.githubusercontent.com/6561887/130673576-70da1dbd-f3e0-4189-afe4-9e7a07cb6a17.gif)

**Comment by bpasero** [comment]
That sounds like a bug to me and not intended behaviour.

**Comment by bpasero** [comment]
**Steps:**
* enable `workbench.editor.revealIfOpen: true`
* build up a group and editor layout like Steven has, all groups are locked
* try to reproduce by clicking on a file in the explorer that is inactive
