### ISSUE TITLE
Go to Test Alt+Enter doesn't work on Linux

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#131538]
Testing microsoft/vscode-python#17039

testing on Linux Debian build

Select a test in the Test Explorer and press Alt+Enter (called out in the context menu). Focus goes to the File menu and the cursor does not go to the selected test in the editor.

**Comment by Trass3r** [comment]
Confirmed on Windows with Remote Containers.

**Comment by connor4312** [comment]
Duplicating into https://github.com/microsoft/vscode/issues/174241
