### ISSUE TITLE
I would name the context key workspace.platform not workspacePlatform to make it more consistent with the other keys

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#131513]
Testing #131467

I see that we have camel case keys as well but the majority of the keys seem to take `.` to build a qualified name

**Comment by JacksonKearl** [comment]
Going to keep as-is due to `workspaceFolderCount` being camel already, I think it'd be more odd to have `workspaceFolderCount`//`workspace.platform` than `workspaceFolderCount`//`workspacePlatform`.

**Comment by dbaeumer** [comment]
But if you look at all the keys we have most of them are '.' qualified names so IMO we should start using those independent whether we have old once that are still camcel cased.
