### ISSUE TITLE
Explore ways to make terminal rendering edge cases more reliable

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131580]
Sometimes issues like these are reported where something goes horribly wrong with the gpu support:

![image](https://user-images.githubusercontent.com/2193314/130698666-58267512-6e6e-4528-b8a3-f22c45e7621e.png)

I believe that this is likely due to either browser bugs or hardware issues as I've never been able to reproduce them. We should devote some time to try reproduce some of these problems and see if we can detect and fallback to the DOM renderer for these cases. For example one idea that may or may not work is if we created the texture for `☐` and made sure that all of its sides are within the glyph?

**Comment by Tyriar** [comment]
Related: https://github.com/xtermjs/xterm.js/issues/3449

**Comment by Tyriar** [comment]
From @SHoogland in https://github.com/microsoft/vscode/issues/131389

> ![image](https://user-images.githubusercontent.com/2193314/132679003-15bf3e30-cb71-4937-8397-ce759e1701d0.png)
> On a Dell U2412M display with a resolution of 1920x1200 this weird visual issue occurs in the terminal

**Comment by SHoogland** [comment]
https://github.com/microsoft/vscode/issues/131389#issuecomment-914410914
To answer this question, and add some more info: disabling integrated gpu acceleration does fix the issue!

**Comment by Tyriar** [comment]
@SHoogland yep thanks, that will fix pretty much all the rendering issues but rendering in the terminal will be significantly slower

**Comment by Tyriar** [comment]
Closing as things are better now and this was more of a plan item
