### ISSUE TITLE
x86 installer no-ops

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#131549]
Testing #131445

I run the installer, and briefly see it running in Task Manager, but then it exits without showing a window or any other output.

**Comment by eamodio** [comment]
I saw the same thing on ARM64, but the installation did succeed in my case.

**Comment by connor4312** [comment]
I can't seem to find any trace that it got installed

**Comment by sbatten** [comment]
You should not see anything since it runs silently, can you please verify is Code is in your Add/Remove Programs list?

**Comment by connor4312** [comment]
No luck https://memes.peet.io/img/21-08-67e3da6e-ccee-44dc-a889-c8530552dea4.mp4

**Comment by sbatten** [comment]
fixed
