### ISSUE TITLE
Fix performance issue joining hundreds of editors

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131506]
Scenario: the left editor group has 100 files, the right editor group has 1 file, use "View: Join All Editor Groups" from the right editor group, the joining can take several seconds or more to complete, whereas using "View: Join All Editor Groups" from the left editor group, the joining can complete instantly.

The idea is that VSCode should always join the editor group which has fewer files to the one that has more files no matter which editor group is focused on.

**Comment by bpasero** [comment]
👏  for the issue, I think a better fix is to understand the performance issue and address that. Very similar to https://github.com/microsoft/vscode/issues/130634 actually.

**Comment by bpasero** [comment]
@wenfangdu can you maybe test this in our insiders version if it is fixed for you? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by wenfangdu** [comment]
@bpasero I created 1000 mock files using `seq 1 1000 | split -l 1 -a 3 -d - file` and tested the joining, seems it's fixed, or at least faster than before.

I've also noticed opening these 1000 mock files at a time will make VSCode hang forever, I had to open them per a hundred files or so at a time.

**Comment by bpasero** [comment]
@wenfangdu a very easy way to open hundreds of editors is by keep pressing `Cmd/Ctrl+N` to open untitled editors. I used that in my testing:
* have 100 untitled editors in group left
* have 1 untitled editor in group right
* focus right group
* join editors

That was pretty instant for me now.

**Comment by jrieken** [comment]
Measured 180ms for merging 1 editor into ~180 untitled. Not super fast but no freeze to be seen

<img width="444" alt="Screen Shot 2021-09-30 at 15 22 05" src="https://user-images.githubusercontent.com/1794099/135463128-f3633948-ecbc-4d93-a61c-4abdecbaaba8.png">
