### ISSUE TITLE
[i18n] Fix ru locale

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#13150]
- VSCode Version: 1.5.3
- OS Version: Win 10

On i18n\rus\src\vs\workbench\parts\git\browser\gitQuickOpen.i18n.json 
```
"checkoutRemoteBranch": "Удалить ветвь в {0}"
```
It should be
```
"checkoutRemoteBranch": "Удаленная ветвь в {0}"
```
Удалить means "delete", that is incorrect
Удаленная means remote

**Comment by johnliu2016** [comment]
@lukaschal please fix accordingly in /Localize/rus/vscode/src/vs/workbench/parts/git/browser/gitQuickOpen.nls.resx.lcl

      <Item ItemId=";checkoutRemoteBranch" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Remote branch at {0}]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Удалить ветвь в {0}]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\workbench\parts\git\browser\gitQuickOpen.nls.resx
ID: ".resx", 0; "checkoutRemoteBranch"
SRC: Remote branch at {0}
TGT: Удаленная ветвь в {0}
