### ISSUE TITLE
Inline completion hover can not be triggered via mouse while suggest is visible

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131529]
1. Have suggest widget visible and have the inline completion rendered
2. Hover over the inline completion -> inline completion hover does not show 🐛 

I know you mentioned that you doubt people would want to see the suggest widget and the hover at the same time. But I think that users might be surprised the first time they see inline completion and try to move the mouse over them. Providing no feedback, or showing hover `any` as in my case is not useful, showing the completion item hover might clarify things.

![Screenshot 2021-08-24 at 16 55 59](https://user-images.githubusercontent.com/1926584/130639789-a14d864f-ee7a-4e50-9025-ee42f8353f9e.png)

**Comment by hediet** [comment]
I suggest to wait on more feedback for this.

**Comment by hediet** [comment]
Closing due to lack of feedback.
