### ISSUE TITLE
Command line option -g FILE:LINE not working

### ISSUE THREAD

**Issue by steynpjm** [Microsoft/vscode#13153]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.open command prompt.
2. ensure in local directory, say c:\somedirectory. Ensure c:\somedirectory contains somefile.ext
2. `code -g somefile.ext:2`      :- This works
3. `code -g c:\somedirediretory\somefile.ext:2`     :- does not work, gives error "Arguments in '--goto' mode should be in the format of 'FILE(:LINE(:COLMUMN))'.
4 `code -g "c:\somedirediretory\somefile.ext:2"`  :- does not work. gives same error as above.

**Comment by bpasero** [comment]
This has been fixed in our insiders (1.6. release). 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
