### ISSUE TITLE
Locked groups: show lock icon even for inactive groups

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131559]
Testing #131196

I remember this being discussed, however, in practice, I lost track of which groups were locked because the icon does not show unless the group is the active group.

It would be more usable imo if the lock icon was shown for all locked groups.

**Comment by bpasero** [comment]
Good point and it would nicely align with how empty groups would show when we show 2 icons. Will investigate if this is feasable.

**Comment by bpasero** [comment]
**Verification**
Prep: open more than one editor group and have one of the groups locked.
Steps: click through inactive groups to make them active and observe actions (top right) in active and inactive groups.

* tabs enabled
  * active: all actions visible including "Unlock" action if the group is locked
  * inactive: only "..." visible and "Unlock" action if the group is locked
* tabs disabled
  * active: all actions visible including "Unlock" action if the group is locked
  * inactive: only "Close" and "..." visible and "Unlock" action if the group is locked
