### ISSUE TITLE
[Bug] Installation count and rating are missing for installed extensions

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131503]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

Previously, they were there, a recent update removed them:

![image](https://user-images.githubusercontent.com/28700378/130615914-f239353e-e746-4f05-bea5-24b91edd7800.png)

Installation count and rating are very helpful information for installed extensions as well.

**Comment by sandy081** [comment]
Yes it was removed intentionally for an installed extension. These details are important for user to install the extension to know how popular it is. They are not much useful after installation. You can always see those details by opening the extension.
