### ISSUE TITLE
Editor error message alignment

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#131511]
Testing #131192

With the navigation breadcrumbs on (which I believe is the default) the left alignment of the error seems weird:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/3372902/130624837-7fb425d1-3fd5-4e3a-ab74-f86b6598e68a.png">

**Comment by bpasero** [comment]
Yeah, maybe. Then again we probably have this issue in other editors too, like notebook toolbar:

![image](https://user-images.githubusercontent.com/900690/130629923-96cd673c-ebc3-4062-8ca6-def982ed91f5.png)

//cc @misolori
