### ISSUE TITLE
Editor that fails to load error message

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#131509]
Testing #131192

Do we have enough information about the error so that we can distinguish between the resource not being available vs. an error? I am asking as it would be nice to clearly state that the resource was deleted if that is the case. And if an error occurred, could we show some information about the error?

**Comment by bpasero** [comment]
The error is currently logged only to dev tools and not visible. I didn't think that seeing the error details is very helpful, but maybe for the "file not found" case, it could be more specific.

**Comment by bpasero** [comment]
Ended up with these 2 cases:

**File not found**
![image](https://user-images.githubusercontent.com/900690/130645274-31e043e4-8c50-4148-9753-aaccba87c51b.png)

**Other**
![image](https://user-images.githubusercontent.com/900690/130645313-9b6467a0-1265-40d1-bea3-6f02ff7d4af4.png)
