### ISSUE TITLE
VS Code is difficult to use on a virtual file system over a network (gvfs)

### ISSUE THREAD

**Issue by bogomips** [Microsoft/vscode#13156]
Hi, 
I use the latest version on ubuntu and I work through gvfs.
I like the editor and I am trying to totally move from sublime, but I still have two big problems 
1)  when I switch tab the editor tries everytime to update the content from the network not using the cache, it is nuisance on slow networks.
2) after I save a tab content, randomly, the tab gets closed.
These two things together, turn my working in a hell.
Is there a solution, I bet those are not  bugs but just a setting to change...
thanks

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/13665

**Comment by bpasero** [comment]
@bogomips do you still see tabs closing randomly using latest VS Code 1.6.x?
