### ISSUE TITLE
Changing terminal.integrated.persistentSessionExperimentalSerializer does not prompt for restart

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#131558]
Testing #131453

It's nice when the changes that require full restart show the dialog box asking the user to restart. Otherwise it's easy to reload instead and be confused.

**Comment by Tyriar** [comment]
Didn't think it was worth it here as it's a temporary just in case setting and last I looked there isn't a property to switch this on with a config schema change.
