### ISSUE TITLE
Localization for Settings Menu

### ISSUE THREAD

**Issue by hetasanghvi-zz** [microsoft/vscode#131578]
Hi,
I would love to have localization for the settings menu here,

![image](https://user-images.githubusercontent.com/4486307/130695478-e961426d-ad66-41b8-9856-fe552f76f9b6.png)

The way VS Code supports localization for settings description is seen in the green box. It would be great to have a localization option for red boxes as well.

**Comment by roblourens** [comment]
Yes, right now these are autogenerated from the setting name but would like to be able to support custom names here from the extension, and localization.

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/191807
