### ISSUE TITLE
Terminals appear briefly when a VS Code window is restored

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#131522]
Testing #131278

- create a few new terminals side by side in the editor area
- close VS Code
- start VS Code

Observe:
when the VS Code window opens, the terminals become visible for a brief moment and then disappear.

![2021-08-24_16-34-28 (1)](https://user-images.githubusercontent.com/1898161/130636276-b7f52757-adb4-4b60-a7ac-2fc678861e28.gif)

This is irritating:
Why are they persisted if they are immediately closed?
If terminals are ephemeral, then there is no reason to persist them.

**Comment by meganrogge** [comment]
This is fixed
