### ISSUE TITLE
Quick Open not showing files with negated .gitignore pattern

### ISSUE THREAD

**Issue by MarcoNovaro** [microsoft/vscode#131566]
Issue Type: <b>Bug</b>

I have a big project, with a .gitignore file like this

```
# Ignore everything
*
# But descend into directories
!*/
# Don't ignore the .gitignore file
!.gitignore
!.gitattributes

# C source files (.c, .h):
!/Asw/**/*.c
!/Asw/**/*.h
!/Bsw/**/*.c
!/Bsw/**/*.h
```

Basically I want to ignore everything, except some specific files.
I noticed that the "goto file" (Ctrl+P) is not showing all files which are in the "negated pattern". For instance, all files in /Asw/**/*.c are not shown.
The same files are shown in the Explorer window, and they can be opened from there. Once opened in a window, they are shown in the Ctrl+P dialog. This is similar to the issue in previous bug https://github.com/microsoft/vscode/issues/93182, but with a "complex" .gitignore pattern

Tested with VS Code 1.59.1 and 1.60 preview.

VS Code version: Code - Insiders 1.60.0-insider (f4db5eac35995ab23cb563a55a35425de80ff9ce, 2021-08-24T08:07:47.451Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.36GB free)|
|Process Argv|--crash-reporter-id 43707cf2-3c1a-4602-8fea-7bd9599305cf|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
3f5j7703:30294757
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgst2:30356659

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/107944
