### ISSUE TITLE
Misleading lock icon in empty groups

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131586]
Testing #131196

By replacing the X icon in empty groups, I tend to believe that this lock protects the empty group from closing, but this is an unrelated feature.

**Comment by bpasero** [comment]
Did this for a leaner look, but agree it is a bit misleading.

**Comment by bpasero** [comment]
**Verification:**
* open 2x2 editor layout
* lock one of the empty groups from the context menu
* verify the lock icon appears next to the close icon
