### ISSUE TITLE
Simple coloring in inline suggest widget

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131516]
Testing #131415

Can we use an editor to render the inline suggestion and then set it to a mode of the underlying active editor.
That way we will get some colors here.

![Screenshot 2021-08-24 at 15 48 30](https://user-images.githubusercontent.com/1926584/130628372-8a33e5ef-1be8-4ce2-bf9a-8c43a40f55af.png)

**Comment by san-coding** [comment]
can you assign this issue to me

**Comment by isidorn** [comment]
No need to do this, since this is only for screen reader users.
I forgot that you only render this then.

No action, thus closing
