### ISSUE TITLE
Graph with error message with jupyter 

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/vscode#131544]
Hi, I am new on vscode and I tried something very simple with Jupyter extension.  
My code is: 
```
# Pandas
import pandas as pd

# Plotting
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn')

%matplotlib inline
plt.rcParams['figure.dpi'] = 150
df = pd.DataFrame([2, 5, 67, 2, 3, 5, 23, 124])
df.hist();
```

but the line `%matplotlib inline`seems to produce an error message although I get my graph 
The error message is: 
`Expected expression Pylance`

Second the graph is not nice and I do not understand how to improve it in particular the white espace in the graph that seems strange from my point of view. 

Thx for your help. 

<img width="1273" alt="Capture d’écran 2021-08-24 à 19 40 51" src="https://user-images.githubusercontent.com/49912455/130664143-5d591cd3-7e67-438a-8811-a231a3bf9e12.png">

**Comment by roblourens** [comment]
We are working on fixing these error messages, see https://github.com/microsoft/vscode-python/issues/17058

I don't think we can do much about the extra white space. This area is managed by the matplotlib renderer and isn't themed like vscode. cc @DonJayamanne
