### ISSUE TITLE
Test nodes with all skipped children do not show as skipped

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#131537]
Issue Type: <b>Bug</b>

In [the docs](https://code.visualstudio.com/api/extension-guides/testing) about the test runner, it says:

```
// Otherwise, just run the test case. Note that we don't need to manually
// set the state of parent tests; they'll be set automatically.
```

This doesn't seem to be the case for nodes with all-skipped children though:

![Screenshot 2021-08-24 at 17 11 19](https://user-images.githubusercontent.com/1078012/130651886-9deadd8a-ff5c-437a-8b0d-8aa5a382e5c1.png)

I would expect to see the Skip icon on the "skipped group 2.1" node.

-----

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (10.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-eslint|dba|2.1.23
tsl-problem-matcher|eam|0.4.0
vscode-dotnet-runtime|ms-|1.2.0
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Yea, skipped doesn't "bubble up" above `unset`. We could add some special casing for the all-unset case: right now the algorithm is "the computed state of the parent is the state with the max priority of any of its childrens' computed states".

**Comment by connor4312** [comment]
Insiders is currently not being released off main since we have a release pending. This'll work in the first 1.61 Insiders version.

**Comment by DanTup** [comment]
I realised that after posting. All looks good now - thanks!
