### ISSUE TITLE
window platform is express using booleans

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#131514]
Testing #131467

like isWindows, isMac, ...

to make things consistent shouldn't we have a `window.platform` as well?

**Comment by JacksonKearl** [comment]
Hm, I like the idea and it makes good sense, but the window platform can be more nuanced: for instance `isWeb & isMac`, or `isMac & isMacNative`. 

In theory the platform can be similarly nuanced (`hasWebHost && hasLinuxExtHost`), but a use case for such distinctions hasn't come up.
