### ISSUE TITLE
InlineCompletionContext.triggerKind is always automatic

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131508]
Testing #131415

1. Start running the extension from [here](https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions)
2. Put a breakpoint in the `provideCompletionItem` call in the extension
3. Notice how the `triggerKind` is always `0`. Even if the user triggers suggestions via `ctrl+space`

**Comment by hediet** [comment]
triggerKind only refers to how the inline suggestion part is triggered.

It is only non 0 if the user invokes the command "Trigger inline suggestions" or one of the commands "next inline suggestion" / "previous inline suggestion"

**Comment by isidorn** [comment]
But I get a `triggerKind` of `0` even if I `Trigger inline suggestions` as a user.
