### ISSUE TITLE
cfn-lint triggers on all yaml files on disk and locks machine

### ISSUE THREAD

**Issue by b3cft** [microsoft/vscode#131521]
Issue Type: <b>Bug</b>

I think this is the AWS Developer extension but can't be sure, and the drop down for logging an issue won't display installed extensions to be able to select one.

Steps to reproduce
1. Open vscode
2. vscode connects to WSL2 instance
3. triggers a scan of all yaml files in cfn-lint
4. all 24 core at 100% usage
5. load average shoots to somewhere about 150
6. WSL2 stops responding
7. vscode reports wsl2 instance is disconnect (reconnect?)
8. click reconnect
9. thinks about it, reconnects, goto 3. 
10. issue a `sudo pkill -f cfn-lint` to get anything responding again.

![image](https://user-images.githubusercontent.com/51764/130636432-8d2bc3e8-2487-4a9a-be7c-f9893b0d5754.png)

VS Code version: Code - Insiders 1.60.0-insider (f4db5eac35995ab23cb563a55a35425de80ff9ce, 2021-08-24T08:07:47.451Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (40.88GB free)|
|Process Argv|--crash-reporter-id d84130c3-89a0-47ae-a4ce-aa1e8a9d5382|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-20.04' failed: Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgst2:30356659

```

</details>

**Comment by aeschli** [comment]
Can you disable extension by extension to find out which one is creating the  `python --cfn-lint` processes? 
We need to file the issue against the extension (None of the built-in VS Code extensions does that).
