### ISSUE TITLE
[Help wanted] Is there a keybinding for moving a specific number of lines up/down?

### ISSUE THREAD

**Issue by guy-kdm** [Microsoft/vscode#13154]
PgUp is very extreme and moving one line up is slow, it would really help if I there was a keybinding that allowed me to move up/down 3-4 lines at a time. Can I redfine PgUp or maybe there's an unbounded command for something like that?

**Comment by Bill-Stewart** [comment]
Have you tried `scrollLineUp` and `scrollLineDown` commands (default keybindings <kbd>ctrl</kbd>+<kbd>up</kbd>  and <kbd>ctrl</kbd>+<kbd>down</kbd>) for scrolling one line at a time?

**Comment by Tyriar** [comment]
I don't believe there is a keybinding for moving lines up x lines, there are a few extensions out there to do this though:

- https://marketplace.visualstudio.com/items?itemName=selbh.move-fast
- https://marketplace.visualstudio.com/items?itemName=alekseychaikovsky.line-jumper
- https://marketplace.visualstudio.com/search?term=move%20lines&target=VSCode&sortBy=Relevance
