### ISSUE TITLE
Problems view should maintain scroll position

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13151]
- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

1. Have lots of problems, open problems view and scroll down
2. Hide / show problems view
3. Notice that the problems view is now scrolled all the way to the top - we should maintain the scroll position as we do for all the other panels https://github.com/Microsoft/vscode/issues/12937

**Comment by sandy081** [comment]
@isidorn Problems view always retain the previous state unless `problems.autoReveal` setting is `true`. When it is `ture`, it reveals problems for the current open file if there are any. This is similar to `explorer.autoReveal` setting

**Comment by isidorn** [comment]
That makes sense I am just not sure if `'problems.autoReveal'` should be `true` by default?

**Comment by sandy081** [comment]
IMO it makes sense coz mostly you are interested in the problems for the editor I am seeing . Editor and problems go along with each other.
