### ISSUE TITLE
How can I run more than one node project at sametime?

### ISSUE THREAD

**Issue by SilentTiger** [Microsoft/vscode#1315]
I have a project solution in Visual Studio 2015 with 3 NodeJS projects in it. I need to run these three projects together, it's easy in VS2015, but in VS Code, what should I do?

I think that's should be a very important feature of VS Code.

**Comment by isidorn** [comment]
Currently this is possible by opening multiple instances of VSCode.
Running them in one instance is a feature-request for the future.
