### ISSUE TITLE
Locked groups: auto lock setting needs to suggest valid entries

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#131587]
Testing #131196

How do I know what to put in this setting? I have no idea what the ids should be from the setting.

**Comment by bpasero** [comment]
@rzhao271 @roblourens what is the latest on this for the settings editor, can I dynamically suggest entries to fill into objects or array from the UI?

**Comment by rzhao271** [comment]
There's no suggestion mechanism yet. If the number of choices is finite, you can specify an enum.

**Comment by bpasero** [comment]
The choices are infinite, and it looks like there is no UI choice for settings of type object. 

But maybe via `settingsDocumentHelper.ts` something can be built in:

https://github.com/microsoft/vscode/blob/6d66648c51be891335a698649cfb6efd6f66c268/extensions/configuration-editing/src/settingsDocumentHelper.ts#L13-L13

**Comment by bpasero** [comment]
**Verification:**
Take a look at the `workbench.editor.autoLockGroups` setting and verify it works as advertised

![image](https://user-images.githubusercontent.com/900690/134700564-5eb4dafe-7924-4e0a-9393-5432f5ad7ad2.png)

**Comment by rchiodo** [comment]
This doesn't seem to be working for me. If I select interactive as auto lock, it doesn't auto lock.

Although maybe I'm doing something incorrectly.

**Comment by rchiodo** [comment]
![autolock](https://user-images.githubusercontent.com/19672699/135179412-24c82bf9-1881-4b3e-a691-80ad67e07072.gif)

**Comment by bpasero** [comment]
Thanks, I created https://github.com/microsoft/vscode/issues/134088 to follow up. In the meantime please try with other editors.

**Comment by rchiodo** [comment]
/verified. Works with preview editor
