### ISSUE TITLE
TaskGroup.id isn't in @types/vscode 1.59.0

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#131583]
Testing #131402

Not a bug, more of a question on how to proceed next time 🙂 

When testing part 2 of https://github.com/microsoft/vscode/issues/131402, the instructions mention copying this command:

```ts
const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		const tasks = (await vscode.tasks.fetchTasks())
			.filter(task => (task.group?.id === vscode.TaskGroup.Build.id) && task.group?.isDefault);
		const taskNames = tasks.map(task => task.name).join(', ');
		vscode.window.showInformationMessage('Hello World, you have the following default tasks: ' + taskNames);
	});
```

However if I copy it as-is in my freshly generated extension I get squiggles under `id` and `isDefault`:

![image](https://user-images.githubusercontent.com/51720070/130700037-1a9e80c3-d771-4a02-bd36-d3eb9f7d3f58.png)

and the following error:

![image](https://user-images.githubusercontent.com/51720070/130700057-504ddbbd-b422-40e7-8b90-946b88731c4b.png)

In order to resolve it I replaced the content of `node_modules/@types/vscode/index.d.ts` with what's in`src/vs/vscode.d.ts`, is there a cleaner way to do it?

**Comment by alexr00** [comment]
@kimadeline you used the same work around that I do :). @jrieken do you have a better way to test newly finalized API before the new release has occurred?

**Comment by jrieken** [comment]
You can also use the `vscode-dts` tool to fetch latest vscode.d.ts from master. Just make sure to nuke the NPM dependency first
