### ISSUE TITLE
when running a file in the powershell console, ` is erroly removed from the path:

### ISSUE THREAD

**Issue by Binger-cn** [microsoft/vscode#131683]
Issue Type: <b>Bug</b>

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\`work\py> & c:/python39/python.exe c:/`work/py/count6.py
C:\python39\python.exe: can't open file 'c:\work\py\count6.py':

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8200Y CPU @ 1.30GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.15GB free)|
|Process Argv|--crash-reporter-id fadc8f3b-d8ac-41b6-bc28-5476bb73b69f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.14.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-language-pack-zh-hans|MS-|1.59.3
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
vsdyn321cf:30356811

```

</details>

**Comment by lramos15** [comment]
Closing due to lack of an update. Please try VS code version 1.60 and let us know if you see this issue again. Thank you for creating this issue and we hope your problem is resolved, if not feel free to open another issue with an english description and we would be happy to investigate.
