### ISSUE TITLE
Terminal.integrated.profiles.windows doesn't control temrinal profiles

### ISSUE THREAD

**Issue by ChandlerTayek** [microsoft/vscode#131665]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider
- OS Version: Windows 10

I'm not sure if this is an actual bug but when I try to control my user terminal profiles in my settings with this: 
![image](https://user-images.githubusercontent.com/6510301/130854429-a12af125-2081-4508-bfad-2ff9f5664c66.png)
I'm expecting to only see the two terminals yet PowerShell seems to still be set as my default python terminal when pushing the play button or running the debugger. This is what I currently see:
![image](https://user-images.githubusercontent.com/6510301/130854697-7e69515e-54fd-4e01-93de-0bec0259a2e4.png)

Any help would be warmly welcome and again sorry if this isn't a bug and just a user error.

**Comment by meganrogge** [comment]
Set those other ones to null in order to remove them from that list
