### ISSUE TITLE
Problem matcher $msCompile using MSBuild does not work

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode#131611]
Does this issue occur when all extensions are disabled?: I don't know.

I tried to execute an msbuild task by disabling all extensions but VSCode now complains that "The term msbuild is not recognized as the name of a cmdlet, function,.... Check the spelling of the name, or ..., and try again.

- VS Code Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1.

Have a project structure like so:
```
/project
    ---src/
        --- file1.cpp
   ---include/
       ---file1include.h
   ---.vscode/
       proj.vcxproj
```

proj.vcxproj can be any suitably built project file that can be generated using Visual Studio IDE for the project in question. With this message, I attach all 3 files specified above so that they can be clearly replicated at your end.
[New folder.zip](https://github.com/microsoft/vscode/files/7044178/New.folder.zip)

2.

Execute the following task from within tasks.json

```
{
            "label": "winbuilddebug",
            "type": "shell",
            "command": "msbuild",
            "args": [
                ".vscode/proj.vcxproj",
                "/property:GenerateFullPaths=true",
                "/property:Configuration=Debug",
                "/property:Platform=x64",
                "/t:build",
                "/consoleloggerparameters:NoSummary"
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher":"$msCompile"
}
```
When doing so, you should be able to observe in the bottom terminal tab the following output of msbuild

```
> Executing task: msbuild .vscode/proj.vcxproj /property:GenerateFullPaths=true /property:Configuration=Debug /property:Platform=x64 /t:build /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25-08-2021 11:42:50.
Project "E:\project\.vscode\proj.vcxproj" on node 1 (build target(s)).
PrepareForBuild:
  Creating directory "x64\Debug\".
  Creating directory "x64\Debug\proj.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\proj.tlog\unsuccessfulbuild" because "AlwaysCreate" wa
  s specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\1
  4.27.29110\bin\HostX86\x64\CL.exe /c /I..\include /I"C:\Program Files (x86)\V
  isual Leak Detector\include" /ZI /JMC /nologo /W3 /WX- /diagnostics:column /s
  dl /Od /D _DEBUG /D _CONSOLE /D VSCODE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC
  1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x
  64\Debug\\" /Fd"x64\Debug\vc142.pdb" /Gd /TP /FC /errorReport:queue ..\src\fi
  le1.cpp
  file1.cpp
E:\project\src\file1.cpp(7,10): warning C4244: 'initializing': conversion from 'double'
 to 'int', possible loss of data [E:\project\.vscode\proj.vcxproj]
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\1
  4.27.29110\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"E:\project\.vscode\x64
  \Debug\proj.exe" /INCREMENTAL /NOLOGO /LIBPATH:"C:\Program Files (x86)\Vis
  ual Leak Detector\lib\Win64" kernel32.lib user32.lib gdi32.lib winspool.lib c
  omdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.l
  ib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /
  manifest:embed /DEBUG:FASTLINK /PDB:"E:\project\.vscode\x64\Debug\proj.pdb" /SUB
  SYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\project\.vscode\x64\Debu
  g\proj.lib" /MACHINE:X64 x64\Debug\file1.obj
  proj.vcxproj -> E:\project\.vscode\x64\Debug\proj.exe
FinalizeBuildStatus:
  Deleting file "x64\Debug\proj.tlog\unsuccessfulbuild".
  Touching "x64\Debug\proj.tlog\proj.lastbuildstate".
Done Building Project "E:\project\.vscode\proj.vcxproj" (build target(s)).


Terminal will be reused by tasks, press any key to close it.
```

You will observe that msbuild warns that on line 7, column 10 of file1.cpp, I am assigning a double to an int and issues warning C4244. This is indeed reported in the Problems tab below. But, when I go to the Problems tab and click on this particular warning, I receive

`Unable to open 'file1.cpp': Unable to read file 'e:\project\ur\src\file1.cpp' (Error: Unable to resolve non-existing file 'e:\project\ur\src\file1.cpp').`

with an option to create this file. I note that inadvertent creation of such files can lead to a fatal overwrite of the actual file in question.

Please suggest how to fix this issue. I raised this issue over at `vscode-cpptools` but was informed that they are not involved in the maintenance of this particular feature. See that discussion [here](https://github.com/microsoft/vscode-cpptools/discussions/8042). Being able to build and quickly and correctly navigate to the warning / errors thrown by the compiler is by far the most common activity someone can do. At present, this is draining one's productivity quite dramatically.

**Comment by gjsjohnmurray** [comment]
You are using an old version. Please update and retest.

**Comment by TryerGit** [comment]
I did update it to 1.59.1 and on this, the problem matcher does indeed work without any issues so far. Thank!

**Comment by TryerGit** [comment]
Sorry. I was too fast to close this. My experimentation reveals that the problem still persists. 

```
"problemMatcher": {
                "base": "$msCompile",
                "fileLocation":"absolute"
}
```

The above does not work with /property:GenerateFullPaths=true in msbuild.exe

I still get situations where a build gives rise to errors / warnings that are parsed wrongly and I still get the problem I reported in the OP. Could VSCode folks try out the contents of the zipped file I provided in my opening post to see if the problem persists at their end as well?

**Comment by TryerGit** [comment]
When the exact same project is compiled via make on linux, the following task works just fine in terms of capturing problems and navigating to them on clicking on them.

```
        {
            "label": "lindbgbuild",
            "type": "shell",
            "command": "make",
            "args": [
                "CONF=Debug",
                "-C",
                "./.vscode"
            ],
            "group": "build",
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}/.vscode"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
```

So, the problem seems to be specific to Windows and msbuild.

**Comment by TryerGit** [comment]
@alexr00 I am unable to consistently replicate this. I will be on the lookout for when the Problems tab does not catch errors/warnings.
