### ISSUE TITLE
Description for `additionalProperties` shows extra line at beginning

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#131676]
Testing #130449

I still see the "Describes a JSON file..." line for `additionalProperties`, but I think the issue is separate from 130449.

![](https://user-images.githubusercontent.com/7199958/130867543-56b828f0-5003-448d-b856-42a38078d026.PNG)

CC @aeschli

**Comment by rzhao271** [comment]
I think this needs a new release of the language service to test.

**Comment by aeschli** [comment]
The language service is now updated
