### ISSUE TITLE
Add Explorer right-click options to the file tab right-click options

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#13160]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Right-click the tabs for a file.
2. Compare with right-clicking the file in the Explorer.

Feature Request: Add all/more of the Explorer right-click options to the tabs for a file. My main request is Copy Path.

**Comment by Tyriar** [comment]
Duplicate #11942
