### ISSUE TITLE
[scss] !global flag marked as 'unknown keyword'

### ISSUE THREAD

**Issue by ashleahhill** [Microsoft/vscode#13165]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. Attempt to use the `!global` flag to control SASS variable scope.

```
#main {
  $width: 5em !global;
  width: $width;
}

#sidebar {
  width: $width;
}

#footer {
 $footer-height: 40px !default !global;
  height: $footer-height;
}
```
1. Get the error `[scss] unknown keyword <global>`

**Comment by maqboolkhan** [comment]
This issue still persisted :(

**Comment by Kurtz1993** [comment]
+1

**Comment by simeonoff** [comment]
+1

**Comment by Dwlad90** [comment]
+1

**Comment by fegyi001** [comment]
+1

**Comment by cassianomon** [comment]
+1

!important too...
