### ISSUE TITLE
how to cancel

### ISSUE THREAD

**Issue by fengbjhqs** [Microsoft/vscode#13162]
- VSCode Version:1.5.3
- OS Version:windosw 7

Steps to Reproduce:

![Alt text](http://feng89.b0.upaiyun.com/img-1.png)
1    this Mouse tips how to cancel

**Comment by Tyriar** [comment]
Pressing escape should close that.

**Comment by fengbjhqs** [comment]
Sorry, I don't understand.

**Comment by Tyriar** [comment]
You cannot turn the off, you can dismiss it by pressing <kbd>esc</kbd> though.

**Comment by Molunerfinn** [comment]
@Tyriar Hi~I also meet this problem. But I use the vim-mode and I find that I can't dismiss it by pressing `esc`. In normal-mode, it's helpful. How can I dismiss it in vim-mode? Thx :)
