### ISSUE TITLE
Encoding detection from XML header

### ISSUE THREAD

**Issue by ujay68** [Microsoft/vscode#1316]
The attached XML file declares and uses ISO-8859-15 as its encoding, but it opens as UTF-8. The sample Euro character (U+20AC), coded as byte 0xA4 in that encoding, is not shown correctly. v0.10.3 on OS X 10.11.2.

![iso-8859-15-vsc](https://cloud.githubusercontent.com/assets/3627476/11805513/8aef06e8-a30c-11e5-96e3-b5adeea66f2a.PNG)

[ISO-8859-15.xml.zip](https://github.com/Microsoft/vscode/files/62171/ISO-8859-15.xml.zip)

**Comment by bpasero** [comment]
Detecting the encoding like that is a feature request.

**Comment by ujay68** [comment]
Thanks for picking this up. If you regard it as a feature request it's IMO at least very very close to a bug. The XML specification is very clear about how a conformant XML processor (and one can think of an XML-aware editor as an XML processor) must detect and handle the encoding, either an explicit one (like here the charset in the XML declaration) or implicitly (by looking at byte-order marks and the initial <? sequence). If you make encoding detection for XML files optional and leave it to the user to switch the encoding manually, you have a very high risk of her or him forgetting that and producing non-wellformed XML documents. Editors like IntelliJ IDEA follow that encoding detection strictly for XML files and even disallow a user to accidentially change it.

See also: http://www.w3.org/TR/REC-xml/#charencoding and http://www.w3.org/TR/REC-xml/#sec-guessing

**Comment by bpasero** [comment]
@ujay68 I think this cannot be a bug because we do not have code that does encoding detection so you cannot really say that we are doing something wrong here. It is literally not implemented. The only encoding detection we do is when you use UTF-8 or UTF-16 byte-order-marks that work in all files.

**Comment by bpasero** [comment]
Btw great chance for a pull request, the code could go into https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/encoding.ts

**Comment by ujay68** [comment]
I'm not a JavaScript/TypeScript programmer, I'm afraid, but if someone is volunteering here, I'd be glad to help with any questions regarding the XML specification.

**Comment by rubenprins** [comment]
I have the opposite problem: I have UTF-8 encoded XML files without an encoding header or BOM (perfectly allowed and unambiguous per the specs). My default encoding is UTF-8 as well.

Yet VS Code insists on "detecting" the encoding for these files as Windows 1252 every time I open them, giving me garbled text.

**Comment by bpasero** [comment]
@rubenprins there is no such thing as automatic encoding detection in VS Code other than looking for a UTF-8 or UTF-16 BOM. This can only mean that your workspace or global setting is defined to be cp1252. Can you check?

**Comment by rubenprins** [comment]
@bpasero, You're right, I'm sorry. I opened the files within an existing VS Code session with such a setting. Since the folder containing the XML files did not contain a .vscode folder, I didn't realise the workspace had such an override (in another folder).

**Comment by fortinmike** [comment]
I just stumbled upon this (editing a file in VS Code then saving it messed-up some accented characters because the file was read as UTF-8 instead of Windows 1252, as declared in the XML itself). This caused us a bit of a headache!

I vote for XML-aware encoding detection in Code.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
