### ISSUE TITLE
Changing default terminal does not work until all VS Code instances are restarted

### ISSUE THREAD

**Issue by luckerby** [microsoft/vscode#131609]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.1
- OS Version: Windows 10 21H1

I have 2 Visual Studio Code windows opened. I currently have wsl as the default terminal in Visual Studio Code. I've used the Ctrl+Shift+P with "Terminal: Select Default Profile" and selected Command Prompt in one of the VS code instances. Yet trying to open a new terminal (Ctrl+Shift+`) still results in a wsl instance to be opened. Closing and reopening that VS Code instance has no effect. No error is reported in the dev tools output.

It's only after all the VS Code windows are closed and reopened that the new default terminal setting kicks in. Not sure if this is by design.

**Comment by TarunavBA** [comment]
@luckerby You can press `ctrl + p` if you are on windows and if you are on Mac press `cmd + p` and type `developer: reload window`.

**Comment by meganrogge** [comment]
I can't repro the issue you describe and it should work immediately. 

Can you provide me with your` terminal.integrated.<platform>.profiles` and  `terminal.integrated.<platform>.defaultProfile` settings before and after you make a change to the value of the latter?

**Comment by luckerby** [comment]
Strange enough, but I can't repro it either. Version is still the same (1.59.1). Steps followed below.

I've started with 2 VS.Code windows opened. Command Prompt was set as the default terminal. Corresponding settings:

```
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "terminal.integrated.profiles.windows": {
        "C:\\Windows\\System32\\wsl.exe (migrated)": {
            "path": "C:\\Windows\\System32\\wsl.exe",
            "args": []
        }
    }
```
I've then used Ctrl+Shift+P with "Terminal: Select Default Profile" and selected Powershell. The settings changed as follows:
```
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.profiles.windows": {
        "C:\\Windows\\System32\\wsl.exe (migrated)": {
            "path": "C:\\Windows\\System32\\wsl.exe",
            "args": []
        }
    }
```

Trying to open a new windows in either VS.Code instances resulted in Powershell to be opened, as expected.

I can only conclude it was some transient issue between WSL and VS.Code
