### ISSUE TITLE
[Bug] Markdown links display incorrectly when used with backticks

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131693]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Paste the following code into a markdown file:

```
[`code`](https://example.com)
```

2. Use the `markdown.showPreview` command.
3. Displays as code, can't tell it's a link:

   ![image](https://user-images.githubusercontent.com/28700378/130912052-8c833110-71ce-4678-bb0c-b9686b25918b.png)

**Comment by wenfangdu** [comment]
@medmor Thanks, I've opened an issue there https://github.com/markdown-it/markdown-it/issues/814.

**Comment by wenfangdu** [comment]
@medmor Quote from a member of `markdown-it`:

> [That's not this package's problem. This package generates html only. You can style it as you wish with css.](https://github.com/markdown-it/markdown-it/issues/814#issuecomment-907599603)

**Comment by wenfangdu** [comment]
@medmor Quote from a member of `markdown-it` from [here](https://github.com/markdown-it/markdown-it/issues/814#issuecomment-907599603):

> That's not this package's problem. This package generates html only. You can style it as you wish with css.

**Comment by san-coding** [comment]
Hey, I am new to open source, can I contribute to this?

**Comment by san-coding** [comment]
> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version: v1.60.0-insider
> * OS Version: Windows 10
> 
> Steps to Reproduce:
> 
> 1. Paste the following code into a markdown file:
> 
> ```
> [`code`](https://example.com)
> ```
> 
>  1. Use the `markdown.showPreview` command.
> 2. Displays as code, can't tell it's a link:
>    ![image](https://user-images.githubusercontent.com/28700378/130912052-8c833110-71ce-4678-bb0c-b9686b25918b.png)

Even here it is clickable, but can't figure out by looking at it if its a link

**Comment by san-coding** [comment]
In GitHub markdown, this is how it shows up
[`code`](https://example.com)

**Comment by san-coding** [comment]
Which CSS file has to be changed to fix it ?

**Comment by san-coding** [comment]
Color is set to blue here, why is it appearing as golden

https://github.com/microsoft/vscode/blob/8dbad73de575e47e127c8b1a4324f2b61257fbdc/extensions/markdown-language-features/media/highlight.css#L16-L19

**Comment by san-coding** [comment]
Section is given golden color , when section is put inside link, it is overriding the blue color , is this the issue ?
https://github.com/microsoft/vscode/blob/8dbad73de575e47e127c8b1a4324f2b61257fbdc/extensions/markdown-language-features/media/highlight.css#L76-L78

**Comment by san-coding** [comment]
How to run the app after cloning?

**Comment by wenfangdu** [comment]
> I think the Section is given golden color, when the section is put inside a link, it is overriding the blue color, is this the issue?
> https://github.com/microsoft/vscode/blob/8dbad73de575e47e127c8b1a4324f2b61257fbdc/extensions/markdown-language-features/media/highlight.css#L76-L78

@san-coding Thanks for contributing, only restoring the blue color won't be enough, since we won't be able to tell it's `code`, a better solution is to simulate the GitHub markdown display: [`Linked Code`](https://example.com) `Plain Code`.

> @wenfangdu What should I click on to run the app after cloning this repo?

Please see [Build and Run](https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run).

**Comment by mjbvz** [comment]
Thanks for looking into this. While seeing how to provide advice on fixing this, I realized it was a simple change so I pushed a fix

Please test in 1.61 insiders and let me know if it doesn't work as expected

**Comment by wenfangdu** [comment]
@mjbvz Thanks for the fix, however, only restoring the blue color won't be enough, since we won't be able to tell it's `code`:

![image](https://user-images.githubusercontent.com/28700378/132074009-a5221cc9-1a83-4cec-986b-8865051b4bca.png)

A better solution is to simulate the GitHub markdown display: [`Linked Code`](https://example.com) `Plain Code`.

**Comment by mjbvz** [comment]
Code is rendered in a monospace font

**Comment by wenfangdu** [comment]
@mjbvz The difference is quite subtle, would be nice to add a background to the code:

![image](https://user-images.githubusercontent.com/28700378/132078059-6f4caab9-3b7e-4757-9be2-73a944a35394.png)
