### ISSUE TITLE
Light/Dark Visual Studio theme needs improvements to handle expressions in template string

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13166]
- VSCode Version:
- OS Version:

Used latest vscode extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

This can also be found when using extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar

From @mhegazy at Microsoft/TypeScript-tmLanguage#287 
see `number` below
![image](https://cloud.githubusercontent.com/assets/8000722/19012536/bdb0de44-876d-11e6-9681-25e96f9b00ae.png)

The expression is tokenized as `meta.template.expression` but theme doesn't use this information to colorize it correctly. Also note that `number` in the expression is scoped as `variable.other.readwrite`. 

Probably `${` and `}` could be colored blue by using their scopes `punctuation.definition.template-expression.begin` and `punctuation.definition.template-expression.end`

**Comment by Tyriar** [comment]
Yes the scopes exist so this is indeed a theme issue:

![image](https://cloud.githubusercontent.com/assets/2193314/19047852/7deea15a-8958-11e6-934f-6ca93c864dda.png)

**Comment by aeschli** [comment]
I adopted the default themes to the grammar. It now looks like this:
![image](https://cloud.githubusercontent.com/assets/6461412/19442626/3de8f334-948a-11e6-8117-56343a8515fd.png)

**Comment by emzero** [comment]
Would it be too hard to make `${` and `}` a different color or maybe bold or something?

**Comment by rob3c** [comment]
Yes, didn't `${` and `}` used to be separately colored? Matching them to either the string or the expression color is confusing and seems like a regression.

**Comment by aeschli** [comment]
Reopening to fix the coloring of the interpolation `${...}`

**Comment by gertcuykens** [comment]
Can you expand the template string coloring to include html syntax while you are at it?

Example:
![image](https://cloud.githubusercontent.com/assets/863731/20235670/8950b812-a898-11e6-8c35-65c5d9409821.png)

**Comment by aeschli** [comment]
@gertcuykens Yes, please file a separate request. Please include the full code snippet that shows the issue. Please also for what language the code snippet is.

**Comment by gertcuykens** [comment]
I looked around a bit better and found many other tickets scattered around asking for it :) I think this is the main one https://github.com/Microsoft/vscode/issues/2000

**Comment by Tsmith18256** [comment]
This is not working for variables that use the all-caps constant naming convention.

![screen shot 2016-11-23 at 10 26 20](https://cloud.githubusercontent.com/assets/7586082/20574001/5a93e94a-b167-11e6-9e1d-f7581e4ca00d.png)

Tested in the latest version (1.7.2).

**Comment by aeschli** [comment]
@Tsmith18256 Please file a new issue? You can file directly against https://github.com/Microsoft/TypeScript-TmLanguage. Thanks a lot!

**Comment by emzero** [comment]
I've filed a new issue: https://github.com/Microsoft/TypeScript-TmLanguage/issues/368

**Comment by emzero** [comment]
@aeschli: @sheetalkamat says this is a vscode issue. Could you re-open this?
https://github.com/Microsoft/TypeScript-TmLanguage/issues/368#issuecomment-262651679

**Comment by lidderupk** [comment]
@aeschli possible to create a setting to allow auto closing the } bracket and place the cursor inside? Like the editor does for functions. This is not a bug. Just a question. 

```console.log(`this is ${this}`)```

**Comment by aeschli** [comment]
@lidderupk Inside strings we currently don't auto close brackets. Please file a new enhancement request with details against https://github.com/Microsoft/vscode/issues.

**Comment by lidderupk** [comment]
@aeschli done. Thank you.
https://github.com/Microsoft/vscode/issues/28053
