### ISSUE TITLE
Toggle cell toolbar position translated incorrectly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#131671]
For the French language pack:
Expected translation: "Toggle cell toolbar position" gets translated to something like "Changer la position de..." to indicate that clicking on that option moves the toolbar to the left or to the right
Current translation: "Activer/désactiver la position de..."

<img src="https://user-images.githubusercontent.com/7199958/130861279-360fd5e3-efe8-49d0-b367-2684b8fbd705.png" width="300px">

**Comment by v-mholloway** [comment]
closing as global bug now resolved
