### ISSUE TITLE
Restore terminal sessions across application restarts

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131634]
I have looked in the past at supporting the auto creation of terminals for workspaces and my conclusion was that the amount of customization that people wanted would be too much to add to core and would be best left to an extension. With the upcoming [terminal location API](https://github.com/microsoft/vscode/issues/45407) extensions will be able to accomplish this properly.

The major case of restoring terminals across restarts without bringing in the complexity of a pty host that lives outside of the main process could be solved by saving the all terminal buffers/cwd/icon/etc. on a restart and restoring them similar to how Terminal.app restored when macOS is updated where it will restore the buffer, print something like `[Session restored from <datetime>]` and then create a new shell. This in combination with [task reconnection](https://github.com/microsoft/vscode/issues/117408) and similar restoration should make the restart VS Code experience really nice.

Right now the plan is to look at this in the November iteration after our clean up iteration.

cc @alexr00: I'm not sure right now how tasks would get their buffer restored yet but it would probably need something beyond https://github.com/microsoft/vscode/issues/117408 to create a new task using an existing terminal.

**Comment by bpasero** [comment]
Important for me would be that terminals used for tasks (watch etc.) are not piling up more and more:

![image](https://user-images.githubusercontent.com/900690/130785573-f43d4b4a-71ca-420a-b8d0-73c8e2e3521c.png)

I.e. are being reused when I run the build task again.

What is the particular challenge to connect back to an existing terminal, esp. for the window reload case where shared process is not going down?

**Comment by Tyriar** [comment]
@bpasero window reload to reconnect to existing task processes is tracked in https://github.com/microsoft/vscode/issues/117408. No particular challenge AFAIK apart from resources/time.

This issue is about restarting and restoring the buffer but creating new processes and running new tasks.

**Comment by Tyriar** [comment]
Just merged this in, will likely get a bit of polish over the next week.
