### ISSUE TITLE
Interactive window `interactive.history.previous` and `interactive.history.next` do not persist history position when reexecuting commands

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#131659]
1. Execute four cells from the interactive window input box, e.g. `print(1)`, `print(2)`, `print(3)`, `print(4)`
2. To reexecute multiple commands from earlier in your history, e.g. `print(1)` and `print(2)` use `interactive.history.previous` via the up arrow
3. After executing an entry from earlier in the history e.g. `print(2)`, scroll position resets to the bottom of the history, and you have to start over and scroll up from the most recent command (4 -> 3 - > 2 -> 1). This can be frustrating for users who are trying to reexecute multiple commands. Note also that the original interactive window used to preserve your scroll history in the interactive window so that you didn't have to scroll back up through the entire history, and users have complained about this behavior change: https://github.com/microsoft/vscode-jupyter/issues/4716#issuecomment-902079450 https://github.com/microsoft/vscode-jupyter/issues/4716#issuecomment-905719688

**Comment by joyceerhl** [comment]
The expectation is that the interactive window input behaves just like a REPL. https://github.com/microsoft/vscode/issues/127498 would address this. We should have shared logic for handing history traversal.

**Comment by rogerlga** [comment]
Any news on that? I agree with the PR that the current behavior is quite frustrating and deserves further attention.

**Comment by jaymegordo** [comment]
Yes this is one of my main frustrations with the IW still. At minimum I just want the up arrow to go to the last executed code, not have cycle through like 20 cells every time I need to re-run something. And it did used to work this way ~1.5 yrs ago.
