### ISSUE TITLE
The window is no longer responding -  you can reopen or close the window or keep waiting

### ISSUE THREAD

**Issue by seba615** [microsoft/vscode#131678]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 64 bits for Windows.
- OS Version: Windows 10.

Steps to Reproduce:

1. Open Visual Studio Code.

[Window Title]
Visual Studio Code

[Main Instruction]
The window is no longer responding

[Content]
You can reopen or close the window or keep waiting.

[Reopen] [Keep Waiting] [Close]

![image](https://user-images.githubusercontent.com/38956750/130876613-57d41fc3-9b0e-434c-a148-af5794aa00ef.png)

Does this issue occur when all extensions are disabled?: Yes

I already tried to uninstall and reinstall different versions but I keep getting the same error.
It is not a Citrix environment.

Thank you.

**Comment by seba615** [comment]
I think it is valid to clarify it used to work properly.
I added some extensions and it worked fine for a while, and a few days later this error came up.


This is what I see if I open the app with --disable-extensions --verbose:

> [main 2021-08-28T15:30:35.450Z] Starting VS Code
[main 2021-08-28T15:30:35.452Z] from: c:\Users\spereyra\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2021-08-28T15:30:35.452Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': true,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'b5d53d6a-358b-4966-aad6-a9161615d6ee',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\spereyra\\AppData\\Roaming\\Code\\logs\\20210828T123035'
}
[main 2021-08-28T15:30:35.455Z] Resolving machine identifier...
[main 2021-08-28T15:30:35.455Z] Resolved machine identifier: 89fc0cc56fdf3f937ce409a086dd52c9ac639d7118c67854166a71907744e434
[main 2021-08-28T15:30:35.456Z] Main->SharedProcess#connect
[main 2021-08-28T15:30:35.473Z] StorageMainService: creating global storage
[main 2021-08-28T15:30:35.473Z] lifecycle (main): phase changed (value: 2)
[main 2021-08-28T15:30:35.474Z] windowsManager#open
[main 2021-08-28T15:30:35.475Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\spereyra\\AppData\\Roaming\\Code\\Backups\\1625332643473',
    remoteAuthority: undefined
  }
]
[main 2021-08-28T15:30:35.476Z] IPC Object URL: Registered new channel vscode:559fad7c-2e75-4979-a6f3-5cd4b4a16441.
[main 2021-08-28T15:30:35.477Z] window#validateWindowState: validating window state on 1 display(s) { mode: 0, x: 0, y: 0, width: 1024, height: 728 }
[main 2021-08-28T15:30:35.477Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1366, height: 728 }
[main 2021-08-28T15:30:35.477Z] window#ctor: using window state { mode: 0, x: 0, y: 0, width: 1024, height: 728 }
[main 2021-08-28T15:30:35.477Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-28T15:30:35.513Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-08-28T15:30:35.513Z] lifecycle (main): phase changed (value: 3)
[main 2021-08-28T15:30:35.522Z] update#setState idle
[main 2021-08-28T15:30:35.523Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-28T15:30:35.626Z] [File Watcher (node.js)] [CHANGED] c:\Users\spereyra\AppData\Roaming\Code\User\globalStorage
[main 2021-08-28T15:30:35.630Z] [File Watcher (node.js)] [CHANGED] c:\Users\spereyra\AppData\Roaming\Code\User\globalStorage
[main 2021-08-28T15:30:35.747Z] [File Watcher (node.js)] [CHANGED] c:\Users\spereyra\AppData\Roaming\Code\User\globalStorage
[main 2021-08-28T15:30:35.748Z] [File Watcher (node.js)] [CHANGED] c:\Users\spereyra\AppData\Roaming\Code\User\globalStorage
[main 2021-08-28T15:30:35.796Z] resolveShellEnv(): skipped (Windows)
[main 2021-08-28T15:30:35.961Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\spereyra\AppData\Roaming\Code\User\globalStorage
[main 2021-08-28T15:30:36.204Z] StorageMainService: creating workspace storage (1625332643473)
[10552:0828/123036.264:INFO:CONSOLE(630)] "%cTRACE color: #888 [lifecycle] starting up (startup kind: 1)", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[10552:0828/123036.264:INFO:CONSOLE(630)] "%cTRACE color: #888 lifecycle: phase changed (value: 2)", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[10552:0828/123036.264:INFO:CONSOLE(630)] "%cTRACE color: #888 Renderer->SharedProcess#connect", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[10552:0828/123036.272:INFO:CONSOLE(630)] "%cTRACE color: #888 Skipping initializing user data in desktop", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[10552:0828/123036.376:INFO:CONSOLE(630)] "%cTRACE color: #888 UserDataInitializationService#requiresInitialization", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (630)
[10552:0828/123036.384:INFO:CONSOLE(146)] "Not allowed to load local resource: file:///C:/Users/spereyra/Downloads/VSCode-win32-x64-1.56.2/resources/app/extensions/theme-seti/icons/seti.woff", source: vscode-file://vscode-app/c:/Users/spereyra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js (146)

Hope this helps.
Thanks in advance.

**Comment by ConfidantCommunications** [comment]
Same here. Mac OS 10.13 High Sierra. VSCode 1.65.2. Tried a total removal and a fresh install with current and older versions but no luck. Restarting the machine did not help.

**Comment by ConfidantCommunications** [comment]
Update: On Mac I did `sudo open /Applications/Visual\ Studio\ Code.app` and told it to "keep waiting" one time. Finally it opened!

**Comment by deepak1556** [comment]
@seba615 can you check if the issue repros with our latest insiders https://code.visualstudio.com/insiders ?
