### ISSUE TITLE
visual studio code insider 

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode#131699]
Issue Type: <b>Performance Issue</b>

the time when started.
visual studio code insider do not work normaly.

VS Code version: Code - Insiders 1.60.0-insider (b71e20ceba833fcb2efada1a4765929ff96ccbb1, 2021-08-26T05:13:37.746Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) 3205U @ 1.50GHz (2 x 1497)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.27GB free)|
|Process Argv|--crash-reporter-id d2d171a0-f25a-4997-b1fa-ffcb672aeb85|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    63	  8688	code-insiders main
    0	     7	  1688	   crashpad-handler
    4	   156	  3216	   window (Welcome to Settings Sync - Visual Studio Code - Insiders)
    0	   310	  9524	     extensionHost
    0	    38	   260	       "C:\Users\HIROSHI\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\HIROSHI\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9524
    0	    36	  2524	       electron_node server.js 
    0	     7	  2752	       C:\WINDOWS\system32\cmd.exe /c GCLOUD.CMD config config-helper --format json --quiet
    0	    10	 12740	         console-window-host (Windows internal process)
   11	    51	 12864	         "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\platform\bundledpython\python.exe"  -S "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\lib\gcloud.py" config config-helper --format json --quiet
    0	    26	  3452	       electron_node serverMain.js 
    0	     8	  3464	       C:\WINDOWS\system32\cmd.exe /c GCLOUD.CMD auth application-default print-access-token --quiet
    0	    10	  8996	         console-window-host (Windows internal process)
    4	    58	 12312	         "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\platform\bundledpython\python.exe"  -S "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\lib\gcloud.py" auth application-default print-access-token --quiet
    0	     7	  7376	       C:\WINDOWS\system32\cmd.exe /d /s /c "kubectl config view -o json"
    0	    15	  2296	         kubectl  config view -o json
    0	    10	  9492	         console-window-host (Windows internal process)
    0	     7	  7908	       C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\Users\HIROSHI\.vs-kubernetes\tools\minikube\windows-amd64\minikube.exe" update-check"
    0	    10	  5304	         console-window-host (Windows internal process)
    0	    11	 11396	         "C:\Users\HIROSHI\.vs-kubernetes\tools\minikube\windows-amd64\minikube.exe"  update-check
    0	    44	  9128	       electron_node server.js 
    0	    33	  9192	       electron_node languageserver.js 
    0	     7	  9260	       C:\WINDOWS\system32\cmd.exe /d /s /c "kubectl config current-context"
    0	    15	  1188	         kubectl  config current-context
    0	    10	 11760	         console-window-host (Windows internal process)
    0	     7	  9596	       C:\WINDOWS\system32\cmd.exe /c GCLOUD.CMD config config-helper --format json --quiet
   13	    50	  4708	         "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\platform\bundledpython\python.exe"  -S "C:\Users\HIROSHI\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\..\lib\gcloud.py" config config-helper --format json --quiet
    0	    10	 12296	         console-window-host (Windows internal process)
    0	     7	 10680	       C:\WINDOWS\system32\cmd.exe /d /s /c "kubectl config view -o json"
    0	    10	  3676	         console-window-host (Windows internal process)
    0	    15	  7288	         kubectl  config view -o json
    0	   153	 10788	       electron_node server.js 
    0	    29	 12372	       electron_node ssmServer.js 
    0	     7	 12636	       C:\WINDOWS\system32\cmd.exe /c C:\USERS\HIROSHI\APPDATA\LOCAL\CLOUD-CODE\INSTALLER\GOOGLE-CLOUD-SDK\BIN\GCLOUD.CMD components copy-bundled-python
    0	    10	 12556	         console-window-host (Windows internal process)
    1	    20	 13068	       "c:\Users\HIROSHI\.vscode-insiders\extensions\ms-vsliveshare.vsliveshare-1.0.4761\node_modules\@vsliveshare\vscode-launcher-win\Live Share for VS Code.exe"
    0	    42	 13148	       electron_node aslServer.js 
    1	    21	 13308	       "C:\Program Files\Java\jdk-11.0.12\bin\java" -version
    0	    11	  1432	         console-window-host (Windows internal process)
    0	    17	  6688	   utility
   10	   127	  7388	   gpu-process
    0	    51	  9296	   window (undefined)
    0	    74	  9824	   shared-process
    0	    15	  9728	     ptyHost
    2	    53	 12824	   window (問題のレポーター)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (219)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-languagetool|ada|3.8.0
vscode-languagetool-ja|ada|3.8.0
vscode-tomcat|ada|0.11.3
vscode-tmp|ads|0.0.3
Bookmarks|ale|13.1.0
project-manager|ale|12.3.0
nugetpackagemanagergui|ali|1.1.6
aws-toolkit-vscode|ama|1.29.0
ng-template|Ang|12.2.0
asciidoctor-vscode|asc|2.8.9
vscode-django|bat|1.6.0
armview|ben|0.4.5
close-all|ben|1.0.2
print-it|bma|0.1.5
emmet-jss|car|1.0.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
inline-html|col|0.3.0
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.43.2
while-syntax|dav|1.0.4
vscode-eslint|dba|2.1.23
vscode-gist|dba|1.0.0
vscode-just-start-server|dea|0.2.0
java-decompiler|dgi|0.0.2
copy-on-select|din|0.0.7
vscode-github-gist|dog|1.0.3
git-extension-pack|don|0.1.3
githistory|don|0.6.18
javadebugger|don|0.1.5
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
gitlens|eam|11.6.0
gitlens-insiders|eam|2021.7.1905
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
deletefromeditortab|eff|0.0.1
vscode-npm-script|eg2|0.3.22
apacheconf-snippets|eim|1.3.0
vscode-svn|eli|0.1.0
my-public-ip|ema|0.0.8
LogFileHighlighter|emi|2.11.0
prettier-vscode|esb|8.1.0
svn-commit|fen|0.1.1
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
japanese-novel-extension-pack|fuj|0.1.0
markdown-preview-fuji-styles|fuj|0.1.3
markdown-ruby|fuj|1.0.1
vscode-lombok|Gab|1.0.1
geecode-python|gee|2019.5.10
docker-run|geo|1.1.0
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.29.2
go|gol|0.27.1
go-nightly|gol|2021.8.2415
cloudcode|goo|1.13.2
todo-tree|Gru|0.0.213
angular-essentials|Gyd|0.1.3
javascript-essentials|Gyd|0.0.7
typescript-essentials|Gyd|0.2.2
vsc-essentials|Gyd|0.5.0
vsc-essentials-themes|Gyd|0.1.3
web-design-essentials|Gyd|0.5.0
google-translate|han|1.2.3
live-html-previewer|hdg|0.3.0
docker-linter|hen|0.5.0
beautify|Hoo|1.5.0
githd|hui|2.2.4
vscode-psl|ing|1.11.4
path-autocomplete|ion|1.17.1
powershell-universal|iro|2.1.1
vscode-git-add-and-commit|iva|2.1.1
copy-filename|jac|2.3.2
elixir-ls|Jak|0.8.0
vscode-angular2-emmet|jak|2.0.3
plantuml|jeb|2.15.1
vscode-polarion|Jes|0.2.2
vscode-svn-polarion-branching|Jes|0.0.3
coffee-emmet-mithril|jhe|0.1.2
vscode-nuget-package-manager|jmr|1.1.6
pwa-tools|joh|0.1.0
read-time|joh|1.0.0
vscode-peacock|joh|3.9.1
css-snippets|joy|1.0.2
package-plus-plus|jun|0.0.1
github-gist-explorer|k99|0.2.1
lib-search|Kho|0.0.3
vscode-github|Kni|0.30.6
vscode-java-dev-tools-pack|lar|1.0.0
google-fonts|lio|0.0.1
minisnippet|lit|1.0.1
kefu-to-localhost|liu|0.0.3
execoder|Maz|0.0.1
json|Mee|0.0.1
mp-starter-vscode-ext|Mic|0.2.6
Angular-BeastCode|Mik|10.0.3
r|Mik|0.0.26
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
hg|mrc|1.7.1
vscode-apache|mrm|1.2.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.4.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-bicep|ms-|0.4.613
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.0
vscode-logicapps|ms-|1.0.19
vscode-language-pack-ja|MS-|1.60.1
csharp|ms-|1.23.14
vscode-dotnet-runtime|ms-|1.2.0
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.2031165864
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.193.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-ssh-edit-nightly|ms-|2021.8.18181
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
powershell-preview|ms-|2021.8.2
sublime-keybindings|ms-|4.0.9
vs-keybindings|ms-|0.2.1
vscode-node-azure-pack|ms-|0.2.1
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.6.0
sqltools|mtx|0.23.0
gradle-language|nac|0.2.3
angular2-inline|nat|0.0.17
color-highlight|nau|2.4.0
copy-json-path|nid|0.2.0
vsc-mybatis|nik|1.2.0
printcode|nob|3.0.0
mysql-inline-decorator|odu|0.0.5
docker-compose|p1c|0.3.5
vscode-versionlens|pfl|1.0.9
vscode-spring-boot|Piv|1.27.0
material-icon-theme|PKi|4.10.0
devicetree|plo|0.1.1
stack-trace-formatter|Rad|1.0.6
gist-generator|ram|1.0.0
vscode-formatall|rat|0.0.2
vscode-p3c|Rec|0.1.2
java|red|0.81.0
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
java-sysout|ric|1.0.1
vscode-gradle|ric|3.6.1
vscode-stdext|ser|0.0.6
japanese-word-handler|sgr|1.2.3
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.0
vscode-zipexplorer|sle|0.3.1
java-generate-setters-getters|soh|7.2.1
sonarlint-vscode|Son|2.1.2
vscode-purescript-emmet|spa|1.0.0
svn-scm-ext|spm|1.2.1
guides|spy|0.9.3
code-spell-checker|str|1.10.2
vscode-jetty|Sum|0.1.11
system-viewer|sys|1.0.2
prop2yaml|tan|0.1.0
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
vscode-docker-ws|tii|0.5.0
scm-buttons-vscode|tom|0.1.1
vscode-status-bar-format-toggle|tom|2.0.0
vscode-input-sequence|tom|0.2.0
errorlens|use|3.4.0
produirelang|uto|0.0.3
c-cpp-flag-debugging|uts|0.0.1
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
expand-selection-to-scope|vit|0.2.0
vscode-conventional-commits|viv|1.21.3
azure-iot-edge|vsc|1.24.3
azure-iot-toolkit|vsc|2.16.6
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
gitblame|wad|8.1.0
sublime-text-pack|wad|0.0.2
quokka-vscode|Wal|1.0.395
vscode-todo-highlight|way|1.0.4
debug|web|0.25.1
vscode-input|wil|0.0.6
JavaScriptSnippets|xab|1.8.0
log-analysis|Xin|1.1.0
local-history|xyz|1.8.1
vscode-extension-collection|yde|0.0.1
vscode-jaconv|yok|0.2.0
vscode-java-saber|You|0.1.2
emmet-live|yse|1.0.0
json|Zai|2.0.2
vsc-docker|Zim|0.34.0
vscode-open-in-github|ziy|1.3.6

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgsc2:30356658

```

</details>

**Comment by liuliangsir** [comment]
Same issue here

**Comment by hiroshi-nakajima345** [comment]
Visual studio Code Insider seem to does not aware of this matter. or neglect it

**Comment by hiroshi-nakajima345** [comment]
reason may be virus

**Comment by CodeCrazy-ywt** [comment]
ウイルス対策ソフトウェアを使用して、コンピューターにウイルスが存在するかどうかを検出してみてください。
___
You can try using antivirus  software to detect whether there is any virus in your computer.

**Comment by hiroshi-nakajima345** [comment]
日頃より使用してます。trendo micro のソフトでは、無しとなります。
