### ISSUE TITLE
Switching to a "comparison" tab always puts the cursor back to the start of the file

### ISSUE THREAD

**Issue by russpenska** [Microsoft/vscode#13163]
- VSCode Version: 1.5.3
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Right click on a working file and choose "Select to compare" 
2. Right click on another working file and choose "Compare with...". This will open a tab showing the comparison.
3. Scroll down to a position.
4. Open another file / switch to another tab.
5. Go back to the comparison tab - the cursor is back at the start of the document and the scroll position is lost.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10663
