### ISSUE TITLE
Force close all vscode instances to install update (reopening on previous state ofc)

### ISSUE THREAD

**Issue by dimkk** [Microsoft/vscode#13164]
- VSCode Version: all
- OS Version: windows

Steps to Reproduce:
1. Get some users working in their sessions with VSCode launched on you machine
2. Try to install Update - Access Denied error

What to do:
1. Ask before install - do you want to force close all instances?
2. If Yes - close'em and install
3. Reopen them when installation finished - ideal situation - other users will not notice something changed, just VSCode blinking

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/101

**Comment by joaomoreno** [comment]
[This is currently being done](https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L21).

What files exactly were blocking the update?

**Comment by dimkk** [comment]
VSCode.exe - access denied error - User accounts both local administrators

**Comment by joaomoreno** [comment]
Where does that VSCode.exe come from? Our executables are either `VSCodeSetup.exe` or `Code.exe`.

**Comment by joaomoreno** [comment]
Just found this

> The name can have a "Global\" or "Local\" prefix to explicitly create the object in the global or session namespace. The remainder of the name can contain any character except the backslash character (\). For more information, see Kernel Object Namespaces. Fast user switching is implemented using Terminal Services sessions. Kernel object names must follow the guidelines outlined for Terminal Services so that applications can support multiple users.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682411(v=vs.85).aspx

We can switch to `Global\`.

**Comment by joaomoreno** [comment]
Haven't seen this issue in a while now, closing it.
