### ISSUE TITLE
Terminal window closing immediately

### ISSUE THREAD

**Issue by Bikeman868** [microsoft/vscode#131603]
I was just editing some code when my terminal window suddenly disappeared. I tried View|Terminal. The terminal window appeared very briefly then closed again immediately. I closed VSCode and started it up again. Still no terminal window and View|Terminal behavior is the same as before. So I checked my $SHELL and it points to /bin/bash, the default. So I updated VSCode to the latest version. Still no terminal window.

I am wondering if I hit a strange key combination by accident while editing. Surely no key combination would cause this behavior by design!

VSCode version: July 2021 (version 1.59)
Patch: Update 1.59.1

**Comment by meganrogge** [comment]
Please see this info on launch failures https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by Bikeman868** [comment]
I had already seen these troubleshooting steps and tried all of those things before opening this ticket.
I did eventually figure out what happened though, and I still consider this to be a bug. It is possible to minimize the window containing the Terminal, Output etc down onto the bottom toolbar - I have not yet figured out the key combination that does this, but my fingers must have found it by accident. After you do this, the terminal window will pop up very briefly when you try tp open it. The solution is to click on the minimized window on the bottom toolbar, which brings the window back into its usual position.
