### ISSUE TITLE
VS Code Extension Disappeared

### ISSUE THREAD

**Issue by skandasoft** [microsoft/vscode#131672]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version:1.59
- OS Version: windows 10

Steps to Reproduce:

1. All VSCode Extension disappeared.  :
2. Though I have it on my users/me/.vscode/extension

**Comment by skandasoft** [comment]
I went ahead and reinstalled all extension :( . I also lost lots of my files on some folder which I had it open..when I click on the tab it says no more available vscode...something.

**Comment by sandy081** [comment]
@skandasoft I am really sorry that I am not following the issue. Can you please provide precise information about what is not working? It would be great if you can provide screenshots and logs as requested above.
