### ISSUE TITLE
Please support Win11 window-management flyout on maximize button

### ISSUE THREAD

**Issue by Silver-Fang** [microsoft/vscode#131601]
In win11, if your mouse hover on the maximize button of a standard window, a flyout will appear to allow some fine window layouts. However, nothing happens when it comes to VS Code's maximize button. Maybe VS Code is not using the standard window framework?

**Comment by bpasero** [comment]
You will get this when you configure `window.titleBarStyle: native`

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/127449
