### ISSUE TITLE
Extensions hover placement could be improved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131642]
Hover over an extension -> notice how the hover is placed all the way to the right. I understand that you want to place the hover next to the whole extensions row element, however I suggest to either place the hover above the extension row, or below and that you respect the `x` axis of the mouse. That way horizontally the hover would respect the mouse position.

Currently it does not respect neither the `x` or `y` axis.

![Screenshot 2021-08-25 at 14 47 12](https://user-images.githubusercontent.com/1926584/130793342-8c234035-3253-44d5-b5f3-1496f219ccfd.png)

**Comment by sandy081** [comment]
I think you are talking about same issue here - https://github.com/microsoft/vscode/issues/128998 ?

**Comment by isidorn** [comment]
Yeah it looks similar. I think the client should also be able to specify the orientation. So that you can say place above
Feel free to close as dup
fyi @Tyriar

**Comment by sandy081** [comment]
Client can set the orientation. But when asked to show extension hover on the right, there is a scroll bar in between that causes the hover to disappear when moving the mouse horizontally. I think it will be the same issue when hover is shown top/bottom (other elements can come in between). So the request is to debounce closing the hover.

**Comment by isidorn** [comment]
@sandy081 I think due to the vertical layout of the extensions list that an `above` orientation will be a much better fit here. Even though it might hit some of the same issues, visually it will look better I imagine.

**Comment by sandy081** [comment]
I tried placing it on the top/below but I felt not right and also does not look good. Mainly the hover covers other extensions when it is on top/bottom. Hence chose to have it left/right.

For eg, m Ignoring the pointer position, hover looks like this when it is above

![image](https://user-images.githubusercontent.com/10746682/130805045-b212f879-7b2c-4781-9742-27be35ddf83d.png)
