### ISSUE TITLE
Markdown - Sync Positions In Paragraphs

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#131639]
When double clicking on a markdown paragraph the the preview, the cursor jumps to the paragraph in the mardown source file.

It would be nice if it jumps to the exact word I double clicked on.

**Comment by mjbvz** [comment]
Unfortunately our markdown parser (markdown-it) does not provide accurate token positions within a line

Implementing our own solution for this does seem worth the initial effort and maintenance cost
