### ISSUE TITLE
Show debug output in editor

### ISSUE THREAD

**Issue by MeghanshBansal** [microsoft/vscode#131605]
Issue Type: <b>Feature Request</b>

The output and current state of variables should be shown on the respective line in editor while debugging. 

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by weinand** [comment]
Variable values are shown in the editor if you enable the `Debug: Inline Values` setting.

What debugger are you using?
