### ISSUE TITLE
terminal.integrated.defaultProfile.osx: Value is not accepted. Valid values: "bash", "JavaScript Debug Terminal".

### ISSUE THREAD

**Issue by chenasraf** [microsoft/vscode#131680]
Issue Type: <b>Bug</b>

The following `settings.json`:
```jsonc
"terminal.integrated.profiles.osx": {
    "bash": {
      "path": "bash",
      "icon": "terminal-bash"
    },
    "zsh": {
      "path": "zsh",
      "args": [
        "-l"
      ]
    },
    "fish": {
      "path": "fish"
    },
    "tmux": {
      "path": "tmux",
      "icon": "terminal-tmux"
    },
    "pwsh": {
      "path": "pwsh",
      "icon": "terminal-powershell"
    }
  },
  "terminal.integrated.defaultProfile.osx": "zsh"
```

Causes this warning to pop in the Problems panel:

```
Value is not accepted. Valid values: "bash", "JavaScript Debug Terminal".
```

For the setting:

```jsonc
 "terminal.integrated.defaultProfile.osx": "zsh",

```

> Note: Recently after restarting VS Code, non of my PATH was set correctly, which resulted in me having to manually add paths to the appropriate setting. Might/might not be related.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 4572492f-d970-4f6f-9623-4d22110b66b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (88)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-m3u|af4|1.0.0
Bookmarks|ale|13.1.0
quitcontrol-vscode|art|4.0.0
vscode-browser-preview|auc|0.7.1
gitlab-pipeline-monitor|bal|1.1.5
vscode-django|bat|1.6.0
freezed|bla|0.9.6
vscode-toggle-quotes|Bri|0.3.5
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-markdownlint|Dav|0.43.2
shebang-language-associator|dav|1.1.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.23
jekyll-run|Ded|1.6.0
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|8.1.0
bloc|Fel|5.8.0
auto-rename-tag|for|0.1.8
shell-format|fox|7.1.0
godot-tools|gee|1.1.2
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
gc-excelviewer|Gra|3.0.43
todo-tree|Gru|0.0.213
vscode-drawio|hed|1.6.1
i18next|jac|0.7.2
pubspec-assist|jer|2.3.0
svg|joc|1.4.9
vscode-styled-components|jpo|1.6.6
unity-code-snippets|kle|1.3.0
flutter-intl|loc|1.16.0
i18n-ally|lok|2.7.1
MagicPython|mag|1.1.0
regionfolder|map|1.0.15
vscode-rufo|mbe|0.2.1
dotenv|mik|1.0.1
mongodb-vscode|mon|0.6.10
vscode-duplicate|mrm|1.2.1
vscode-stylefmt|mrm|2.6.2
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
highlight-dodgy-characters|nac|1.0.0
color-highlight|nau|2.4.0
copy-json-path|nid|0.2.0
vetur|oct|0.34.1
indent-rainbow|ode|7.5.0
vscode-jest|Ort|4.1.1
jekyll|ost|0.1.1
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.10.0
heroku-command|pko|0.0.8
vscode-css-peek|pra|4.2.0
quicktype|qui|12.0.46
gdscript-toolkit-formatter|Raz|1.2.2
project-snippets|reb|0.5.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
postcss|ric|2.0.0
LiveServer|rit|5.6.1
vscode-coverage-gutters|rya|2.8.1
pegjs-language|Sir|1.0.4
vscode-taskexplorer|spm|2.5.6
addDocComments|ste|0.0.8
vscode-make|tec|1.0.2
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
vscode-wakatime|Wak|15.0.2
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedt:30351793
vsdyn478:30356813

```

</details>

**Comment by meganrogge** [comment]
When you run select default profile, what are the paths/options shown?

**Comment by meganrogge** [comment]
Also, you have 88 extensions installed. Please try running extension bisect to see if any of them is causing an issue.
