### ISSUE TITLE
Incorrect underline in terminal with wrapped link

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#131646]
1. Have a bunch of file paths / links in the terminal
2. Have one of the links in the middle wrap by 1 character
3. Hover the wrapped link
4. :bug: Everything below gets underlined 

![recording (1)](https://user-images.githubusercontent.com/4544166/130811463-32c39929-7353-480d-b703-37d20f9443cb.gif)

**Comment by Tyriar** [comment]
Likely caused by https://github.com/microsoft/vscode/issues/110446

/duplicate
