### ISSUE TITLE
Tab does not work

### ISSUE THREAD

**Issue by TogrulKazimov** [microsoft/vscode#131694]
We have written the needed data into yo
Issue Type: <b>Bug</b>

"Tab moves focus" is off, but when I click the tab button, it goes to "Select tab size" every time. Shift+Tab works.
![image](https://user-images.githubusercontent.com/60192576/130913971-9ef63a25-c7b0-48ef-86ad-e73bb4ca7f11.png)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.91GB (0.87GB free)|
|Process Argv|--crash-reporter-id e4816a9b-156d-4ca1-9430-5b5944115f67|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-graphviz|joa|0.0.6
python|ms-|2021.8.1159798656
jupyter|ms-|2021.8.1236758218
graphviz-interactive-preview|tin|0.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140cf:30358037

```

</details>

ur clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
It's not clear what the issue is anymore, can you enable screencast mode via the command palette (f1) and record a [gif](https://gifcap.dev/)?
