### ISSUE TITLE
When all extensions disabled UI it is not very clear that disablement actually happened

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131641]
1. `github-dev`, in Extensions view search for "spell checker"
2. Notice that all extensions are disabled
3. When all extensions are rendered as disabled it is not obvious to the user that they are actually disabled 🐛 
4. I suggest that the info that they are disabled should be yellow/orange not blue. To make it clear that there is a warning. Maybe we could also introduce a stronger disablement indication

Bonus bug: hover over a disabled extension -> it gets color and no longer looks disabled

fyi @misolori

![Screenshot 2021-08-25 at 14 43 50](https://user-images.githubusercontent.com/1926584/130792654-19a272f9-e661-446f-b5fa-e9f0fe359f34.png)

**Comment by san-coding** [comment]
Hey, is this a good first issue ? I would like to contribute, I am new to open source

**Comment by san-coding** [comment]
Where can we see that it is marked as yellow

**Comment by isidorn** [comment]
@san-coding thanks for your offer, however please do not comment on every new issue. I think I already replied to you in another issue. But check out these queries and try to help with those issues https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by san-coding** [comment]
Okay , I am sorry

**Comment by sandy081** [comment]
This is to represent that the extension cannot be installed. I also got feedback that showing all of them disabled does not look nice. How about not showing them disabled (remove the opacity as show as normal) and leave them as normal extension with info icon? Moreover we do not show install button already.

**Comment by isidorn** [comment]
I would at the very minimum change the info color to be orange for warning.
The hover should not color them also. For a fancy effect: hover should only increase the color of the orange warning. That way you would draw the users attention to the warning info. I think it would work nicely.

**Comment by sandy081** [comment]
Is not warning implies something wrong with the product. In this case it is to inform user that this extension cannot be installed / supported in web. So info makes sense to me. And showing info with warning color might not make it consistent across product.

**Comment by isidorn** [comment]
@sandy081 what you describe sounds to me like an error (something is wrong). A warning is there to warn the user about something, when something is not ideal.
Though I do understand that this is just different personal interpretations :)

My point is: blue is not visible enough, and this information is the most important part of the extension item. It should be stronger. Using my idea from above might also help: that on hover we only highlight the Warning / Info icon.

fyi @misolori for ideas.

**Comment by misolori** [comment]
I agree that the warning feels more appropriate, "unsupported" does not equate to "information" to me. Here are two options:

<img width="901" alt="CleanShot 2021-08-30 at 11 11 07@2x" src="https://user-images.githubusercontent.com/35271042/131385096-b27fb5a5-fbb2-42fc-8f60-c4d3f50de89c.png">

**Comment by isidorn** [comment]
@misolori my preference is for the right one. The left one feels too strong since it is at the start.
The color might also be a bit strong, what do you think of my idea to show the color a bit dimmed, and on hover to strengthen it?

**Comment by misolori** [comment]
I'm not a fan of dimming colors that we already use since that just adds complexity for color contrast ratios that isn't needed. Plus, when there are other extensions that CAN be installed, there will be an install button and that would be a clear contrast to the warning outline.

**Comment by sandy081** [comment]
I agree with @misolori opinions on dimming colors. To brief:

- I would remove the opacity
- Change to warning icon

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/132227843-3748eebb-dae6-458e-983c-6a860e631265.png)

**Comment by isidorn** [comment]
Great, thanks Sandy 👏  
Let's try it out and see how it goes. Adding bug so I do not forget to verify this later.
