### ISSUE TITLE
Running VSCode on aarch64 architecture 

### ISSUE THREAD

**Issue by DohaMustafa** [microsoft/vscode#131624]
I am trying to run VSCode on an arm64 based machine but I got segmentation fault, I know that VSCode is an electron based application so I also tried to run a simple electron application to try and figure out the root cause of  the segmentation fault but i got the same result even though the ARM64 architecture is supported by both VSCode and by electron. 
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  code-1.59.1.aarch64
- OS Version: Linux Centos7 

Steps to Reproduce:

1. Install visual studio code on an aarch64 based machine.
2. Run it (The result was segmentation fault).

**Comment by deepak1556** [comment]
Can you attach the crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
