### ISSUE TITLE
View for information of Getting Started seems squished and small

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#131675]
This view on the right seems squished:
![image](https://user-images.githubusercontent.com/12758612/130866254-d7e1cd3d-4345-49d6-b959-56c4ceabb74a.png)

**Comment by JacksonKearl** [comment]
Thanks, the markdown now takes up the full right half of the screen, I think this looks better, we'll see if there's any feedback for the rest of this iteration.
![image](https://user-images.githubusercontent.com/8586769/140006011-905aa62a-7d24-41af-a937-1ba3f2502b01.png)
