### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by PankajBansal2018** [microsoft/vscode#131633]
Issue Type: <b>Feature Request</b>

The thin horizontal scrollbar in the editor only appears on hovering the mouse and use has to struggle to use it.

Why does one has to struggle  for something which should be there all the time ans is very important ?

How much space does the use get at the expense of the scrollbar  ?

This is very annoying and can be the reason to put me off using Visual studio code.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19042

**Comment by alexdima** [comment]
@PankajBansal2018 Newer versions of VS Code have an option that can configure this: `"editor.scrollbar.vertical": "visible"`
