### ISSUE TITLE
Hover won't work on custom extension after 1.59.1 on Linux

### ISSUE THREAD

**Issue by atsetoglou** [microsoft/vscode#131667]
Issue Type: <b>Bug</b>

I am actually trying to make a VSCode extension (yales2)  that will provide hover functionality. I had managed to make it work but since the last release of VSCode (1.59.1) it doesn't work anymore on Linux computers (I have tested on Ubuntu and CentOS), but it still works on Windows and MacOS. I tried to downgrade VSCode on Ubuntu (installed 1.58.2) and once again it was working perfectly.  Here is my client js file (./client/extension.js):
```javascript
const vscode = require('vscode');


function activate(context) {

    console.log('Congratulations, your extension of YALES2 is now active!');
    console.warn('Congratulations, your extension of YALES2 is now active!')
    let disposable = vscode.commands.registerCommand('extension.mamar', () => {
        vscode.window.showInformationMessage("Hover");
    });
    
    context.subscriptions.push(disposable);

    disposable = vscode.languages.registerHoverProvider('yales2', {
        provideHover(document, position, token) {

            const range = document.getWordRangeAtPosition(position);
            const word = document.getText(range);
            if (word=="wordTriggeringHover") {
                return new vscode.Hover({ language: "yales2", value: 'Message to show on Hover'});
            }
        }
    });

    context.subscriptions.push(disposable)
}

function deactivate() { }

module.exports = {
    activate,
    deactivate
}
```
And on my `package.json` I have writen:
```json
"activationEvents": [
        "onCommand:extension.mamar",
        "onLanguage:yales2"
     ],
     "main": "./client/extension.js",
     "contributes": {
        "capabilities": {
            "hoverProvider": "true"
        }
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.11.0-31-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.61GB (2.02GB free)|
|Process Argv|--unity-launch --crash-reporter-id ca2799ce-c36c-47ec-9353-c09c16714e50|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer-gb2312|And|0.9.1
npm-intellisense|chr|1.4.0
yales2|COR|0.0.1
vscode-html-css|ecm|1.10.2
matlab|Gim|2.0.1
h5-code|gre|0.0.4
fortran-ls|han|0.6.2
latex-workshop|Jam|8.20.2
plantuml|jeb|2.15.1
linter-gfortran|krv|2.3.0
scilab|mam|0.0.2
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
vsliveshare|ms-|1.0.4761
java|red|0.81.0
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136
vsdyn321cf:30356811

```

</details>

**Comment by sbungert-mms** [comment]
I have noticed with 1.59.1 on mac and linux that hover in various parts of the GUI seems broken

**Comment by sketchbuch** [comment]
Here is a similar issue with this version: https://github.com/microsoft/vscode/issues/132038

**Comment by sketchbuch** [comment]
I have noticed with 1.59.1 on mac and linux that hover in various parts of the GUI seems broken

Here is a similar issue with this version: #132038

**Comment by atsetoglou** [comment]
Does this mean that the problem comes from my extension? And if yes would you have references for which would be the right way to make hover for language extensions?

**Comment by sketchbuch** [comment]
For me the problem is everywhere, not just extensions

**Comment by atsetoglou** [comment]
I still haven't found a solution so if someone has something to propose I would be grateful!

**Comment by SukiTUK** [comment]
[Hover issue LSP implementation on vscode - client side implementation](https://github.com/microsoft/vscode/issues/139370 )

Can someone help me with this issue?

**Comment by alexdima** [comment]
@atsetoglou I have tried with the initial steps in a fresh xubuntu 20.04 install and the following works for me:
* `package.json`:
```json
{
    "name": "131667",
    "publisher": "alex",
    "version": "0.0.1",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": ["onLanguage:fooLang"],
    "main": "main.js",
    "contributes": {
        "languages": [{
            "extensions": [
                ".foo"
            ],
            "id": "fooLang"
        }]
    }
}
```
* `main.js`:
```js
const vscode = require('vscode');

exports.activate = function(context) {
    vscode.languages.registerHoverProvider('fooLang', {
        provideHover(document, position, token) {
            const range = document.getWordRangeAtPosition(position);
            const word = document.getText(range);
            if (word=="wordTriggeringHover") {
                return new vscode.Hover({ 
                    language: "fooLang", 
                    value: 'Message to show on Hover'
                });
            }
        }
    });
};
```
* creating a file `test.foo` with the word `wordTriggeringHover` works for me:
![image](https://user-images.githubusercontent.com/5047891/148783457-05877c24-6590-4cbe-ba47-b8bc69647340.png)

**Comment by atsetoglou** [comment]
I am closing the issue cause I found the problem. The problem was that I was proposing multiple hovers depending on the detected word and I was doing that by using `if else if` so at the end I had memory issues.
