### ISSUE TITLE
Slow updates in notebook cell output 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131606]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders (latest as of today)
- OS Version: Mac
- Latest version of Jupyter insiders (as of today)
- 
Steps to Reproduce:

1. Run the following cell:
```python
from timeit import default_timer as timer
import time
from IPython import display

start = timer()

for i in range(10000):
    display.clear_output()
    print(i)

end = timer()
print(end - start)
```
2. Watch the timer
3. Assume the timer goes upto 50s and then execution ends.
4. After execution ends it goes back down to 30s.
5. This means the extension host provided the outputs and ended execution in 30s, but VS Code was busy updating the outputs that dragged the over all pereived time to 50s.

I can replicate this very consitently. Run the same cell again, and it show the timer ticking over to 20s. But after execution has completed, the timer shows 11s.

The only explanation is that jupyter extension finishes execution in 11s (that's how we provide the end time), but VS Code is busy updating the output that makes things twice as slow.

Watch the following screen recording, execution seems to go on for 13s, but after it ends, the timer reads 5s.
![startSlow](https://user-images.githubusercontent.com/1948812/130734282-0ebe2ffb-31df-46d1-8645-0e765af4ea29.gif)

**Comment by DonJayamanne** [comment]
@roblourens @rebornix  /cc

**Comment by DonJayamanne** [comment]
I've come across this in another notebook, this time in a real world scenario.
This is while running some  tensorflow.js model training.
See below, the execution seems to take 5s, but in reality has completed within 1s.

Please can we re-open this as this is a totally different notebook & different scenario with the same results (real world example).
I think the more information is logged (depends on the author of the code), the time difference would be much higher. E.g. in tensroflow.js, i've found tensforlow.js samples with custom logging while training a model in tensorflow.js (thus in a notebook, this could slow things down even further).

![slow](https://user-images.githubusercontent.com/1948812/131267885-b11d6f0c-09f6-4050-9d26-717e269d5798.gif)

**Comment by roblourens** [comment]
What outputs edits are being made in this case?

**Comment by roblourens** [comment]
So is the bug that replaceOutputItems is slow, or is there something in particular about the sequence of edits here? It also doesn't look like the output items are changing (or they just are not getting rerendered for some reason). How can I try this out?

**Comment by DonJayamanne** [comment]
Damn it, its slow because I'm using awaits everywhere in the execution.
Goes back to the API (we don't have a stable API to do this efficiently).

.
