### ISSUE TITLE
VSCode not start the Windows command prompt.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#13161]
- VSCode Version: 1.5.3 e 1.6.0-insiders 602155b
- OS Version: Windows 10

--Sorry for the English, I used Google Translator --

Steps to Reproduce:

1.See the gif, when I type `start code.exe`, show me an error. But when I put a space between `code` and `.exe`, the plumb starts with an open tab ".exe".

![gif](https://cloud.githubusercontent.com/assets/19866231/19043959/a322a27c-8968-11e6-814f-f345efd36eda.gif)

2.The same goes for insiders version.

![gif - 1](https://cloud.githubusercontent.com/assets/19866231/19043975/b87084be-8968-11e6-9c7c-20584925dc1b.gif)

And it should open with the last opened folder, as currently happens when we click the shortcut, and not an empty file. If there is a setting to always open with empty workspace, should be to keep the setting.

**Comment by joaomoreno** [comment]
The prompt comes up because you use `start`. If you simply call `code .exe` it doesn't bring up a prompt.

**Comment by Tekbr** [comment]
@joaomoreno About putting the start at the beginning, I do not know if you have a rule, but it was new to me, which is the least of it.

The question is not even open a new prompt.

Now, I'm sorry, but the first program I see I have to insert a space between the program name and extension.

Even taking the `start` it opens a tab "`.exe`" that would be a mistake not? He would have to open as previously quoted.

> And it should open with the last opened folder, as currently happens when we click the shortcut, and not an empty file. If there is a setting to always open with empty workspace, should be to keep the setting.

This is not a bug?

**Comment by joaomoreno** [comment]
I don't understand what it is you are trying to achieve.

Why not simply running `code`? You neither need the `.exe` part nor you should use it because the global command available in your PATH is not `code.exe` but `code.bat`.

**Comment by Tekbr** [comment]
I was the most obvious. And I did not know vscode was in `.bat`. I find it more intuitive `start "program" .exe`. But thanks for the help.
