### ISSUE TITLE
In Problem Matcher, the predefined variable ${cwd} doesn't work.

### ISSUE THREAD

**Issue by SejoongDeJang** [microsoft/vscode#131610]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.59.1 (system setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
Hi I have been developing extension. And I  try to define a problem matcher for the tizen build. I tested ${env:variable} and ${cwd}.
And our extension give automatically created tasks. 
For example, my project's structure is like following:
```
$ tree -L 1
.
├── some-app
├── some-service
├── lib-some-core
├── lib-some-core-2
```
Then our extension give 4 tasks like
```
build-native : some-app
build-native : some-service
build-native : lib-some-core
build-native : lib-some-core-2
```
I intend to giving each package's build task.
But when I define the problem matcher, I figure out that the `${workspaceFolder}` is not match to the log.
``` console
src/main.cpp:36:15: error: 'ui_app_mains' was not declared in this scope; did you mean 'ui_app_main'?
   36 |     int ret = ui_app_mains(argc, argv, &lifecycle_callback, NULL);
      |               ^~~~~~~~~~~~
      |               ui_app_main
```
There is whole between the `${workspaceFolder}` and the file of problem matcher(src/main.cpp:36:15).
That is the package name. So when user click the error in problem panel, the vscode is unenable to move src file.

I tried to two methods. Using `$env` and `$cwd`. Both methods have problem.
First using the `$env' case, I can't set a environment variable before call the `task`.
``` json
            {
                "name": "tizen",
                "label": "For tizen native build",
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}/${env:pacakgeName}"
                ],
                "applyTo": "allDocuments",
                "source": "tizen",
                "severity": "error",
                "pattern": [
                    {
                        "regexp": "(.*):(\\d+):(\\d+):\\s(error):\\s(.*)$",
                        "file": 1,
                        "location": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                ]
            }
```
Into my `provideTasks()`, I just return whole task's instances. If I set a task manually and set environment variable in `resolveTask()`, it works with above problem matcher.

Send using the `$cwd` case, I set the `cwd` of the `ShellExecutionOptions` and use followed problem matcher. The `cwd ` is set package's path.

``` typescript
return new Task(
            definition,
            TaskScope.Workspace,
            name,
            'build-native',
            new ShellExecution(
                `tizen build-native -a arm -c gcc -C Debug -- /home/abuild/rpmbuild/BUILD/some-app-2.2.5/${name} -j 16`,
                {
                    executable: '/usr/sbin/chroot',
                    shellArgs: [targetDir, '/bin/bash', '-c'],
                    cwd
                }
            ),
            '$tizen'
        );
```
```json
          {
                "name": "tizen",
                "label": "For tizen native build",
                "fileLocation": [
                    "relative",
                    "${cwd}"
                ],
                "applyTo": "allDocuments",
                "source": "tizen",
                "severity": "error",
                "pattern": [
                    {
                        "regexp": "(.*):(\\d+):(\\d+):\\s(error):\\s(.*)$",
                        "file": 1,
                        "location": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                ]
            }
```
This work like first case. There is whole between the workspace path and the log's path.

**Comment by alexr00** [comment]
> There is whole between the workspace path and the log's path.

Can you give me an example of what this looks like?

**Comment by SejoongDeJang** [comment]
Hi @alexr00 
Anything do I support you?
