### ISSUE TITLE
Browser integration tests on Mac are timing out

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131622]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=132371&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585&l=435

They used to finish in 3m24s before -  https://dev.azure.com/monacotools/Monaco/_build/results?buildId=132216&view=logs&j=[…]-5f82-0dbc-272432d9a0fb&t=ff86458e-371d-5daa-d7a2-208b9a858585

**Comment by sandy081** [comment]
I can confirm that tests started timing out after this commit - https://github.com/Microsoft/vscode/commit/e880f7ef3d2ca036a8467cb65fa3e6d64ef0d3e4. The first commit that is started happening is https://github.com/Microsoft/vscode/commit/f0942b381674448a8087bb38602821dce27f4b11

Checking what commits in between would have caused it.

@mjbvz FYI

**Comment by sandy081** [comment]
Assigning to @mjbvz as one of his commits has caused this timeout.

**Comment by mjbvz** [comment]
Mac seems to be passing pretty reliably now 🤞  but now windows fails consistently on two tests

Been adding a bunch of logging to investigate this. Here's the relevant new error:

```
__requestfailed__ https://vscode-remote+localhost-003a8000.vscode-resource.vscode-webview.net/d%3A/a/1/s/extensions/vscode-api-tests/testWorkspace/image.png NS_ERROR_UNKNOWN_HOST
```

**Comment by mjbvz** [comment]
Actually it's not windows specific: its Firefox specific. The windows browser tests just happen to be the only ones using Firefox

Can reproduce on Mac too
