### ISSUE TITLE
Default themes need to handle jsx evaluated code scopes for better coloring

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#13167]
- VSCode Version:
- OS Version:

Used latest vscode extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

From @emzero at Microsoft/TypeScript-tmLanguage#280 
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:50:42.185Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Windows 7 SP1 x64

Using the [Latest TypeScript and Javascript Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) does provide better Typescript syntax coloring but code between `{ }` in Typescript React is being colored as plain text.

Here's a screenshot using the default dark+ theme.

![image](https://cloud.githubusercontent.com/assets/412489/18976838/a231a5b4-868b-11e6-9696-92f980332ef1.png)

Note that the grammar does scope the code in tsx file between ```{``` and ```}``` and Microsoft/TypeScript-tmLanguage@67954e4  gets into master (probably today) its going to be even more readable and is going to be scoped as ```meta.embedded.expression``` so theme needs to handle these better. (Note before this change it was scoped as ``meta.brace.curly``` which seems incorrect and hence the change. 

https://github.com/babel/babel-sublime uses same scope name ```meta.embedded.expression```  for jsx evaluated code.

**Comment by waderyan** [comment]
@aeschli un-assigning myself unless there is something you'd like me to do here.

**Comment by aeschli** [comment]
The underlying problem is #3008 that prevents us for properly colorize embedded code.
Closing as duplicate of #3008
