### ISSUE TITLE
Exploration: Language-specific default overridden values and language-specific settings in the Settings editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131707]
It is not made clear to the user that the non-language-specific user setting user defined for eg `editor.wordSeparators` is overwritten for a language by the default language-specific setting the extension defines.

**Comment by sandy081** [comment]
@rzhao271 @misolori 

This came up many times in different issues and also in Zurich standup today. It is really confusing to users to not to see language overrides in the UI. This also includes default language overrides coming from an extension.

It would be great if we can start with some UI mock ups for this.

**Comment by debonte** [comment]
> `formatOnSave` as default value for python

Actually formatOn**Type**

**Comment by misolori** [comment]
Is this needed from either the UI or JSON editor, or both?

**Comment by sandy081** [comment]
It is needed for the UI editor.

**Comment by misolori** [comment]
Would also be worth exploring some alternate ways to lay out the Setting labels as we add more and they get very compact (https://github.com/microsoft/vscode/pull/142045)

<img width="758" alt="CleanShot 2022-02-02 at 16 00 25@2x" src="https://user-images.githubusercontent.com/35271042/152258243-e87b56cc-9080-4f32-a29c-4da62e4d092e.png">

**Comment by lychung7** [comment]
We are leaning towards showing the Settings labels as icons that can reveal more information on hover. This can allow users to view multiple overrides from various languages and extensions without the limitation of space next to the setting name. 

<img width="745" alt="image" src="https://user-images.githubusercontent.com/60596156/154167887-15f36db9-fdbe-4510-9553-4a34361b37ef.png">

For showing detailed information about overrides we think that placing this information in a table format can allow for quick scanning and editing. 

![table](https://user-images.githubusercontent.com/60596156/154167461-c736ead5-91e9-4ba4-b290-d8a501c4851e.png)

Also, another change we discussed was the search experience. For example, when searching for jsonc, we can have a link to configure settings which would then show all jsonc settings that have overrides. 

![filter language](https://user-images.githubusercontent.com/60596156/154167750-59b0e0c6-389d-4d7f-999b-d2b5aacb7d12.png)

![filter language-1](https://user-images.githubusercontent.com/60596156/154167808-c5d3aba9-a945-40ba-9718-b7046f1fa7ca.png)

**Comment by Lemmingh** [comment]
May I know the relationship between these issues?

* #58995
* #74195
* #131707

They are quite similar, and this issue looks like a comprehensive combination of the others.

**Comment by rzhao271** [comment]
On Insiders, you can now type `@lang` into the search widget in order to view and modify language-overridable settings for a given language ID.

**Comment by debonte** [comment]
@rzhao271, is it just `@lang` or `@lang:python`? Is this the long-term solution or a first step towards the table format [shown above](https://github.com/microsoft/vscode/issues/131707#issuecomment-1040906512)?

**Comment by rzhao271** [comment]
It would be `@lang:python`. I edited the message above. This filter is only one part of the long-term solution, and it helps when configuring multiple settings under the same language ID.
There should still be a way for the user to configure and view language-specific values for one setting, though.

**Comment by rzhao271** [comment]
The current plan is to keep using language filters, since I'm not sure how often a user would compare language setting values and/or modify them, anyway.

However, I did add a button to the Settings editor search widget that I hope makes it easier for users to discover that there is a way to apply a language filter:

![A screenshot showing the language option of the Settings editor search widget filter button](https://user-images.githubusercontent.com/7199958/164303134-813599da-9a12-41f0-9719-e916561223dd.PNG)

Something else I'd like to work on is improving support for viewing language-specific extension-contributed default overrides.
There is currently an issue in the configuration service that prevents us from reliably identifying which extension contributed a language-specific default override.

**Comment by rzhao271** [comment]
I created #148674 to track the table idea.
I created #148672 to track showing language-specific default override indicators.
Sandeep's issue in the original comment (https://github.com/microsoft/vscode/issues/131707#issue-980049688) actually reminds me of https://github.com/microsoft/vscode/issues/145731, and we can track it there.
