### ISSUE TITLE
Remote file not opened in existing remote window

### ISSUE THREAD

**Issue by Qwaz** [microsoft/vscode#131731]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Windows 10, Build 19043.1165 / Ubuntu 20.04 (WSL)

Steps to Reproduce:

1. Open a WSL vscode window at `/home/project`.
2. In a WSL terminal that is not an integrated terminal, run `code -r /home/project/README.md`.

This command disregards `-r` option and opens the `README.md` file in a new vscode window with an empty folder. This is inconsistent with other cases, and I expect it to open `README.md` in the vscode window that is currently available. For reference, the below cases work as expected:

*WSL Integrated Terminal*

1. Open a WSL vscode window at `/home/project`.
2. In integrated terminal, run `code -r home/project/README.md`.

*VSCode on Windows*

1. Open a vscode window at `C:\Users\<me>\project`.
2. In powershell, run `code -r C:\Users\<me>\project\README.md`. It works regardless whether the terminal is integrated or not.

For context, I was trying is to setup a synctex inverse lookup from Windows PDF Viewer (SumatraPDF) to VSCode WSL with `-r` and `-g` options, and I found that VSCode is always opening a new empty window.

**Comment by Qwaz** [comment]
I'm not sure whether this is a duplicate of #121926 or not.

#121926 is about `-r` option being broken *in the integrated terminal* with two VSCode windows, one native and one remote.

This issue is about `-r` option being broken *outside of the integrated terminal* with a single remote VSCode window.

**Comment by Tyriar** [comment]
Ah sorry, in that case I don't think it's related to the special environment variable in the integrated terminal that links back to the session for https://github.com/microsoft/vscode/issues/121926

Moving to @aeschli

**Comment by ccmattr** [comment]
@aeschli Any luck trying to recreate it? As its definitely still there.
