### ISSUE TITLE
"Git: Open changes" action and button gone missing :(

### ISSUE THREAD

**Issue by CComparon** [microsoft/vscode#131739]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Win10 21H1 19043.1165

Steps to Reproduce:

1. On a git-managed repo, open a file that has local changes (compared to local HEAD)
2. Used to have the "Git: Open changes" action available and the corresponding button below, but that's no longer the case.
![image](https://user-images.githubusercontent.com/12992190/131018055-0cf6e909-8f97-4436-82a7-b94089ff376c.png)
3. Only alternative is to go manually through the Source Control panel, locate the file of interest, and do "Open Changes" on it.

I remember seeing an issue mentioning that regression a month or two ago, it got fixed, but somehow didn't make its way into the 1.59.1 release.

Thanks,
Cyril

**Comment by CComparon** [comment]
Installed 1.60.0 and still no way to Open Changes on the current file 😫

**Comment by jacktkk** [comment]
I met the same problem, could anyone help?

**Comment by eamodio** [comment]
/gifPlease

I can't reproduce this -- can you reproduce with 1.61 (insiders)?

If so, can you attach a gif please?

**Comment by CComparon** [comment]
Here is a screencast showing my installed extensions and the issue itself.
It's taken with vscode 1.60.1. The insider build suffers from the same problem.
It seems it's happening in WSL2 only as I don't have the issue with native windows, MacOS or native Ubuntu.
@jacktkk are you running vscode on Windows with WSL backend?

https://user-images.githubusercontent.com/12992190/133496903-60099ba8-46fd-468a-b01c-9104fc627913.mp4

**Comment by zero41120** [comment]
VSCode with WSL doesn't show the open changes button.
In most cases, I assume using the "open changes with previous revision" achieve the same as the missing open working tree button.
![image](https://user-images.githubusercontent.com/10471270/134708534-8ba181c5-8d96-4c12-ad4a-97df5854df09.png)

**Comment by CComparon** [comment]
> VSCode with WSL doesn't show the open changes button.
This had always worked perfectly until ~2 month ago.

> "open changes with previous revision" achieve the same as the missing open working tree button.
Unfortunately it shows a diff with different left/right versions than what "Open changes" does, which doesn't allow to stage/unstage changes.

Again, the situation is:
- the Open changes button is gone
- the Open change action is gone
- I can trigger the Open change by clicking directly on a file in the Source Control panel 
![image](https://user-images.githubusercontent.com/12992190/134723519-3b8afb7f-e7fe-4309-9c08-62714fd48a9e.png)

**Comment by KyleRAnderson** [comment]
I am observing the same behaviour on two Windows devices running VSCode 1.60.2. For me however, the button doesn't show up in any scenario; not when running with a WSL remote, not when using remote-containers, and not with no remotes either.

System information:
<details>

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'Dev Container: C++' failed: Canceled
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.30GB free)|
|Process Argv|--crash-reporter-id f1b78eeb-acbd-4eea-9d09-3b3a3b816af2|
|Screen Reader|no|
|VM|25%|

Fetching remote diagnostics for 'Dev Container: C++' failed: Canceled

|Item|Value|
|---|---|
|Remote|Dev Container: C++|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|4.82GB (0.68GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C++|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|4.82GB (0.68GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C++|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|4.82GB (0.68GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
prettier-vscode|esb|9.0.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.4
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
slim|sia|0.1.2
vscode-ruby|win|0.28.0
Bookmarks|ale|13.2.1
gitlens|eam|11.6.0
todo-tree|Gru|0.0.214
cpptools|ms-|1.6.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by CComparon** [comment]
@lszomoru Thanks a ton!
I was even able to hot apply the patch myself and the "open change" action is back!!
Still not clear to me why it works but glad it does
