### ISSUE TITLE
Anfaänger

### ISSUE THREAD

**Issue by max2max4u** [microsoft/vscode#131764]
Wir haben die erforderlichen Daten in die Zwischenablage geschrieben, da sie zu groß zum Senden waren. Fügen Sie sie ein.

danke euch für eure zeit ;)

**Comment by CodeCrazy-ywt** [comment]
We have written the needed data into the clipboard as it was too large to send. Please paste.

thank you for your time;)

**Comment by lramos15** [comment]
Closing due to lack of an update.
