### ISSUE TITLE
Dark text background not correct on color corrected OSX machine...

### ISSUE THREAD

**Issue by FonsRademakers** [Microsoft/vscode#13175]
- VSCode Version: 1.5.3
- OS Version: 10.12 Sierra

Steps to Reproduce:

1. Color correct display and use custom display profile
2. Use vscode with dark or dark+ theme

For error, see attached screen dump. Normally defining a colorspace like sRGB when drawing, will solve the problem.

![vscode-color](https://cloud.githubusercontent.com/assets/2265419/19055874/80d8a0b4-89c6-11e6-9b7a-16e61b3b4f72.png)

In the light theme the error is not visible.

Cheers, Fons.

**Comment by mrmlnc** [comment]
See https://github.com/Microsoft/vscode/issues/12473
