### ISSUE TITLE
I can't choose a word by double click any more, and I used to do this 

### ISSUE THREAD

**Issue by ZijieZh** [microsoft/vscode#131770]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Double-clicking the mouse cannot select a common word, no matter whether it has a hyphen or something. Even ordinary words cannot be selected, only command + D. Very troublesome.

VS Code version: Code 1.59.1 (Universal) (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|20, 8, 6|
|Memory (System)|16.00GB (2.00GB free)|
|Process Argv|--crash-reporter-id c652f6c0-26c1-4cac-b856-c653a4d95fad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
appx-axml-language|ali|0.4.6
minicode-completion|ali|1.4.1
color-info|bie|0.6.1
vscode-svgviewer|css|2.0.0
githistory|don|0.6.18
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
code-runner|for|0.11.5
icon-fonts|idl|2.5.2
vscode-docker|ms-|1.16.0
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
autoimport|ste|1.5.4
vscode-stylelint|sty|0.86.0
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.395
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
vstre464:30350172
bridge0723:30353136
vsdyn478:30354110

```

</details>

**Comment by ZijieZh** [comment]
I uninstalled and reinstalled the software, the performance is still the same

**Comment by alexdima** [comment]
@ZijieZh The word definition can be defined in user settings. To launch in a clean environment, could you close all instances of vscode and launch `code --user-data-dir <specify-some-absolute-directory-path-here>`

**Comment by ZijieZh** [comment]
yes, I launch this order and generated some files, could you please tell me how to troubleshoot this problem or which files to upload to show you.
![image](https://user-images.githubusercontent.com/50355277/133209863-b2ba2f0a-ccfe-4ff6-8470-346769802f8e.png)

**Comment by ZijieZh** [comment]
I compressed all the files into this compressed package, could you please check it.
[data.zip](https://github.com/microsoft/vscode/files/7159504/data.zip)

**Comment by alexdima** [comment]
The word definition is something that can be defined in user settings, workspace settings or folder settings. Does the issue reproduce when opening a new VS Code window (File > New Window) and in the new window opening an untitled file (File > New File) and typing "hello world" and double clicking in there?

**Comment by ZijieZh** [comment]
yes I tried all kinds of ways.no matter if i open a new window or uninstall and reinstall, I can’t solve this problem.

**Comment by ZijieZh** [comment]
I can select a word by double click the touchboard or mouse on other macbook

**Comment by alexdima** [comment]
@ZijieZh Could you please try opening the website https://vscode-web-test-playground.azurewebsites.net/?enter=true in Chrome? Can you double click there?

**Comment by ZijieZh** [comment]
I can not too.

**Comment by alexdima** [comment]
@ZijieZh Can you double click to select words in Chrome when opening a website like wikipedia?

**Comment by ZijieZh** [comment]
no. I tried in 'blog.csdn.net', I can't connect to wikipedia cause of network limit.

**Comment by alexdima** [comment]
@ZijieZh If you are unable to double click to select words in any website, this indicates that you have a defect with your hardware.

**Comment by ZijieZh** [comment]
thanks
