### ISSUE TITLE
Better Find & Replace Keyboard Navigation

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#131792]
The way that Atom find works is perfect. When I press control-F, I can have the find and replace window show up, focused on find. When pressing tab or ctrl-F, it focuses on the replace field. When I'm in the replace window and I press tab or ctrl-F, it focuses back to the find field.

This behavior is not possible with VSCode. When I press ctrl-F, I just get a find window. If I bind it to replace, I can't get back to the find window with the keyboard. This issue can be fixed by having commands such as the following:

- editor.action.focusFind
- editor.action.focusReplace

Also, it would be better to have "when conditions" like the following:

- findFieldFocus
- replaceFieldFocus

**Comment by ArturoDent** [comment]
You can achieve what you want with a couple of keybindings:

```jsonc
{
  "key": "ctrl+f",
  "command": "actions.find",
  "when": "editorFocus && findWidgetVisible && replaceInputFocussed"
},
{
  "key": "ctrl+f",
  "command": "editor.action.startFindReplaceAction",
  "when": "editorFocus && findWidgetVisible && findInputFocussed"
}
```

**Comment by NotWearingPants** [comment]
> If I bind it to replace, I can't get back to the find window with the keyboard
Does Shift+Tab not solve the problem?

**Comment by RobbyCBennett** [comment]
Shift + tab doesn't go from find to replace. It just goes from replace to find.

This solution works for me:
`{
	"key": "ctrl+f",
	"command": "editor.action.startFindReplaceAction"
},`
