### ISSUE TITLE
VSCode not recognizing repos

### ISSUE THREAD

**Issue by Samega7Cattac** [microsoft/vscode#131710]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder that contains a git repo
2. Go to Source Control

The Issue is that VSCode doesn't recognize any git repo folder or workspace.
I use Msys2 and added the git executable to the path (it works).
And wanted to use the source control on my repos but it keeps says `The workspace/Folder currently open doesn't have any folders containing git repositories.` and shows the button to init one.
I tried to create a folder and open it on vscode and init using the vscode but it generates the .git folder but keep saying it's not a repo.

**Comment by TarunavBA** [comment]
Can u upload the picture? Of the error?

**Comment by Samega7Cattac** [comment]
![image](https://user-images.githubusercontent.com/25128554/131816337-0829a36c-6ddd-444b-b56f-09d55f702b5c.png)
As u can see the dir has a valid repo but vscode doesn't recognize it. If I click on "Initialize Repository" it does nothing.

**Comment by TarunavBA** [comment]
Try resetting VSCode **Completely**

**Comment by Samega7Cattac** [comment]
What do u mean by reseting completely?

**Comment by TarunavBA** [comment]
@Samega7Cattac delete the vscode folder in `appdata` and reinstall vscode.

Note: this is for windows users.

**Comment by josephgarnier** [comment]
Same problem than @Samega7Cattac (it works on Linux and with a terminal)

**Comment by Samega7Cattac** [comment]
@TarunavBA deleting appdata vscode folder and reinstalling doesn't solve the issue.

**Comment by josephgarnier** [comment]
@Samega7Cattac maybe this post could help: https://github.com/microsoft/vscode/issues/4651#issue-143290321

**Comment by TarunavBA** [comment]
Closed #131710

**Comment by Samega7Cattac** [comment]
@josephgarnier indeed it works with that wrapper.

**Comment by Samega7Cattac** [comment]
now with https://github.com/microsoft/vscode/issues/4651#issue-143290321
I get
```
> git rev-parse --git-dir
Opening repository for path='<path to folder>' failed; ex=spawn C:\msys64\usr\bin\git.exe ENOENT {
  "gitErrorCode": "NotAGitRepository"
}Error: spawn C:\msys64\usr\bin\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
git.exe is inside msys64/usr/bin folder

**Comment by lszomoru** [comment]
@Samega7Cattac, I am not familiar with the script provided in the referenced comment. Given that at the moment VS Code does not support the version of git that gets installed through MSYS2 (feature request tracked [here](https://github.com/microsoft/vscode/issues/143165)), I would highly recommend that you install [Git for Windows](https://gitforwindows.org/).
