### ISSUE TITLE
HTML img tag is reformatted despite setting "html.format.unformatted"

### ISSUE THREAD

**Issue by ph-dev-2016** [Microsoft/vscode#13177]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. VS Code's setting  "html.format.unformatted": includes img, so it should NOT be reformatted
2. I have an img tag in Django HTML template.
   <img src="{% static "notesapp/site_icon.png" %}" alt="site_icon" style="width:150px;height:150px;" />
3. If I press CTRL-S to save the file, VS Code adds extra space characters around the .png file name. 
   <img src="{% static " notesapp/site_icon.png " %}" alt="site_icon" style="width:150px;height:150px;" />

Because of this the image file is not found when I browse the site  This step3 is the bug.

 If I save from menu File/Save, then this img tag is NOT reformatted.
So it works differently depending on whether you save from CTRL-S or from File menu.

**Comment by aeschli** [comment]
@ph-dev-2016 Can you add a small code snippet that shows the bug? I'm not able to reproduce.

**Comment by ph-dev-2016** [comment]
I included a code snippet, but for some reason Github does not show the text correctly.
If this is a line in my Django template file before save
<img src="{% static "mysapp/site_icon.png" %}" alt="site_icon" style="width:64x;height:64px;" />

in save it becomes (extra spaces in the static file name in quotes)
<img src="{% static " mysapp/site_icon.png" %} " alt="site_icon" style="width:64x;height:64px;" />

**Comment by aeschli** [comment]
The problem is that your snippet is not really html. From a HTML perspective, the src attribute ends with the first quote: `src="{% static "`. `mysapp/site_icon.png` is considered the second attribute.
The formatter decides to separate the attributes.

You'd need a proper formatter for Django that takes the templates into account.
