### ISSUE TITLE
Opening a lot of files in a specified line in quick successions doesn't target the correct line

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#13176]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. It doesn't seem deterministic, but it seems to happen quite often:
Execute in a command prompt these commands to open several files at specified lines and numbers in VS Code, and sometimes some of the files are opened at the wrong line.<br>
code-insiders -rg fileName1:47:1<br>
code-insiders -rg fileName2:3:1<br>
code-insiders -rg fileName3:440:1<br>
code-insiders -rg fileName4:716:1<br>
code-insiders -rg fileName5:95:1<br>
code-insiders -rg fileName6:96:1<br>
code-insiders -rg fileName7:23:1<br>
code-insiders -rg fileName8:284:1<br>
code-insiders -rg fileName9:254:1<br>
code-insiders -rg fileName10:260:1<br>
code-insiders -rg fileName11:1284:1<br>
code-insiders -rg fileName12:1288:1<br>

**Comment by bpasero** [comment]
@digeff to clarify, you are targeting the same code instance all the time because you are using the "-r" option and you open different files in that instance on different lines?

**Comment by digeff** [comment]
Exactly...

**Comment by bpasero** [comment]
@digeff Is there a use case for running these commands separately instead of just putting all the files into one `code-insiders` call?

**Comment by digeff** [comment]
I didn't think of doing that. If that works as expected, then please consider this just a "nice to have" feature

**Comment by bpasero** [comment]
I would like to close this one though to clean up. I think passing them into a single argument list is preferred.
