### ISSUE TITLE
vscode opens new duplicate file tab if focus is not on existing-tab's tab-group

### ISSUE THREAD

**Issue by bentheadset** [microsoft/vscode#131738]
Issue Type: <b>Bug</b>

1. search for some text (or other actions, F12 etc, see below)
2. click on a result (tab opens in the current tab group (expected).  Note: it's a preview tab by default; but have tested making it non-preview, and the reproduction is not affected)
3. move cursor focus to other tab group, leaving the editor open in the former tab group
4. click on the _same_ search result entry
5. a new tab is opened in the newly-focused tab group; now TWO tabs of the same file are open.

This began reproducing for me sometime recently - a few weeks?

This reproduces:
- for all the actions I can think of that will jump focus to a file (eg open a new file when it's not already open):
    - F12 / go to def
    - hit a debugger breakpoint
    - auto breakpoint on `sys.exit` (eg, multiple `pytest.py` files end up open, depending on where (what tab group) my cursor was when a test failed
    - file search (the method mentioned above as I have all extensions DISABLED atm)
- after un-installing (`snap`) the IDE and deleting everything `vscode` in my home dir
- on a 2nd machine
- with and without all extensions disabled

this is nearly blocking for debugging a large system.  The cursor dumps around, i have 4 tab groups open to be able to hit breakpoints and still track the overall logic ... and tabs just keep cycling through making it extremely difficult to keep track mentally of state.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.11.0-27-generic snap
Restricted Mode: No

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by bpasero** [comment]
This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by bentheadset** [comment]
This is untrue - the issue reproduces with ALL extensions disabled.
