### ISSUE TITLE
Sometimes extension processes start with lowest priority which may affect their performance

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#131761]
Issue Type: <b>Performance Issue</b>

## Background

I have installed a music player extension (which plays music by calling OS API from within extension host process). Today its audio suddenly became stuttering.

After some investigation, I found that Code's extension host process and all its child processes are running at priority Idle (4). So every time other processes want to use the CPU, this extension doesn't have enough CPU time to maintain smooth audio playing.

Manually changing the priority to Normal (8) fixes the stuttering.

## Reproduce steps

After further checking, my observation is that it happens if Code lunches when a maximized window is having focus. The most stable steps I found are:

1. Open Windows Terminal, maximize its window, then `cd` into project folder
2. Type `code-insiders.cmd .`
3. Hit Enter, while quickly and continually clicking the Windows Terminal window to keep it focused.
4. Open Task Manager or Process Explorer to verify the process priority.

![image](https://user-images.githubusercontent.com/1330321/131070625-8ddff64c-b798-47f5-a732-31f4b57308a2.png)

## "Real-world" performance impact

I also tested performance of TypeScript extension by measuring the "Initializing JS/TS language features" phase time over vscode repository.

In first group, I only have minimal background processes running; in second group, I generate a fake 100% CPU load over all cores from a process with priority Normal (8).

Times are measured by hand and shown as average of three runs.

* **CPU Idle, Priority Normal (8)**: 35.53s
* **CPU Idle, Priority Idle (4)**: 36.18s (+1.83%)
* **CPU 100%, Priority Normal (8)**: 36.80s
* **CPU 100%, Priority Idle (4)**: 41.31s (+12.25%)

## Other information

I can reproduce with `code-insiders.cmd --disable-extensions .`

I can reproduce on two of my machines.

---

VS Code version: Code - Insiders 1.60.0-insider (b71e20ceba833fcb2efada1a4765929ff96ccbb1, 2021-08-26T05:13:37.746Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.70GB free)|
|Process Argv|. --crash-reporter-id 0c8d1f67-5848-4d3e-815e-43caccaefed2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    90	 11132	code-insiders main
    0	    38	 12176	   utility
    0	   216	 13588	   window (vscode - bootstrap.js - Visual Studio Code - Insiders)
    0	    14	 27672	     watcherService 
    0	    11	 34932	       console-window-host (Windows internal process)
    0	   140	 33668	     extensionHost
    0	    70	 13720	       "C:\Users\cxm\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\cxm\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=33668
    0	   106	 21020	       electron_node tsserver.js 
    0	   702	 34836	       electron_node tsserver.js 
    0	    78	 13836	   window (Issue Reporter)
    0	    25	 28720	   crashpad-handler
    0	   134	 31488	   gpu-process
   17	   120	 38612	   shared-process
    0	    66	 27068	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (vscode - bootstrap.js - Visual Studio Code - Insiders)
|    Folder (vscode): 7001 files
|      File types: ts(3428) json(605) js(248) css(195) lock(97)
|                  vscodeignore(81) txt(68) svg(65) png(64) md(57)
|      Conf files: package.json(100) tsconfig.json(45) github-actions(21)
|                  launch.json(19) tasks.json(13) settings.json(8)
|                  webpack.config.js(3) gulp.js(2) jsconfig.json(1) makefile(1)
|      Launch Configs: node(10) extensionHost(9) pwa-chrome(4) pwa-node(3) pwa-msedge;
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.7.2
Bookmarks|ale|13.1.0
gitlens|eam|11.6.0
copilot|Git|1.3.2467
remotehub|Git|0.13.4
rest-client|hum|0.24.5
monkey-patch|ioc|0.1.15
search-node-modules|jas|1.3.0
vscode-edge-devtools|ms-|1.3.0
remote-containers|ms-|0.193.0
remote-ssh-edit-nightly|ms-|2021.8.18181
remote-ssh-nightly|ms-|2021.8.18181
remote-wsl|ms-|0.58.2
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.8.2617
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|4.5.20210826
debugger-for-edge|msj|1.0.15
vetur|oct|0.34.1
explorer-exclude-vscode-extension|Red|1.2.0
reveal|smu|1.2.7
luna-paint|Tyr|0.9.0
vscode-icons|vsc|11.6.0
cloudmusic|YXL|9.1.3
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187:30356034
pydsgst2:30356659

```

</details>

**Comment by deepak1556** [comment]
Process spawning is controlled by chromium and libuv, there is not much we can do here. Closing as not actionable.
