### ISSUE TITLE
Open Workspace should allow to open folder

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131793]
I was just in a user study with @stevencl and I think we have a problem that IDE users have a concept of workspace which is not the VS Code Workspace.

So what happens -> users click `Open Workspace` and actually want to open the whole folder, however they can not since you expect a `.code-workspace` file.

Due to that I suggest (if technically possible) that the `Open Workspace` button allows to open `.code-workspace` file but also any folder.

This is especially confusing on mac, since the `Open..` button opens everything including folders, so users go for Open Workspace and end up being puzzled.

**Comment by isidorn** [comment]
@bpasero aha got it, thanks! Good point.
Maybe we bring it up quickly in a UX meeting? Or we try it in Insiders and listen to negative feedback? What do you think?

**Comment by bpasero** [comment]
UX meeting sounds fine to me, since I have my doubts about it I would not push it to insiders without a discussion first.

**Comment by bpasero** [comment]
@isidorn spend a bit more time thinking about this and feel we should try to be consistent across OS, so what about:
* we add "Open Folder..." on macOS too (which then puts us in the same category as the other OS)
* we rename "Open Workspace..." to "Open Multi-Root Workspace..." (I think I got similar feedback from https://github.com/microsoft/vscode/issues/77718 that the name is a bit misleading)

I would still not change "Open..." on macOS because I think it works OK today and changing it would probably confuse existing users.

**Comment by isidorn** [comment]
Love this suggestion 💯 
`Open Workspace` is too general, so `Open Multi-Root Workspace` will hit the spot. `Open Folder..` also makes good sense to be more explicit.

Should we still bring this up in the UX today or should I remove it from the agenda?

**Comment by bpasero** [comment]
Since we do not have many items, feel free to bring it up.

**Comment by gjsjohnmurray** [comment]
How about `Open Workspace from File... ` instead? Not all such workspaces have multiple roots.

**Comment by bpasero** [comment]
Yeah I like that, wasn't so happy with the wording I chose.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/131709065-6da5d258-c26c-4336-a6d3-2b0445f2b6db.png)

Also in Welcome:

![image](https://user-images.githubusercontent.com/900690/131709101-877670d6-9163-4de3-ae52-44c1d3f390a5.png)

**Comment by bpasero** [comment]
**Verification: ** 
* where previously we would have "Open Workspace" it is now "Open Workspace from File"
* macOS: there is a "Open Folder" entry in the file menu and command palette that only allows to open folders
