### ISSUE TITLE
Intellisense not picking up file move

### ISSUE THREAD

**Issue by markmcgookin** [Microsoft/vscode#13172]
- VSCode Version:

Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:40:08.699Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
Ubuntu Linux 16.04

Steps to Reproduce:

1. C# Project with dotnet core plugin
2. Create Files in folders and compile project
Root > src > ApplicationDir > folder > foo.cs
3. Add new folder beside file
Root > src > ApplicationDir > folder  
> foo.cs
> folder2
4. Move file into folder
Root > src > ApplicationDir > folder > folder2 > foo.cs

Intellisense thinks it's a duplicate file and hilights with errors saying class/methods already exist, even though it runs and debugs.

Close code an reopen it and problem goes away.

**Comment by Tyriar** [comment]
You should file this in the C# extension's repository https://github.com/OmniSharp/omnisharp-vscode
