### ISSUE TITLE
No-Commercial Use License in Files 

### ISSUE THREAD

**Issue by Dr-wood** [microsoft/vscode#131724]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: all?  Identified in 1.3 - 1.59.1
- OS Version:

Steps to Reproduce:

1.  Inspect file licensing at: vscode-1.59.1\extensions\vscode-colorize-tests\test\colorize-fixtures\test.css  and 
2. vscode-1.59.1\extensions\vscode-colorize-tests\test\colorize-results\test_css.json
3.  Both files and any related files based on Dave Shea's software are licensed under the "Creative Commons by-nc-sa license" cannot be used for commercial purposes.  The software test files should be completely removed and or replaced with files that do not contain his software which must be used and distributed under this license (http://creativecommons.org/licenses/by-nc-sa/1.0).  What this means is that no-one who is using this open source software can use it to develop software for use or sale to third parties (technical opinion from reading the license).

**Comment by chrisdias** [comment]
@Dr-wood the file in question isn't in the distros that I inspected (Mac, Windows). Where are you seeing this?  

If in the vscode repo then I think it is fine b/c we're not redistributing it.

**Comment by Dr-wood** [comment]
Chris Dias
The license and authorship are clearly referenced in both of the files referenced in my earliest message.  
vscode-1.59.1\extensions\vscode-colorize-tests\test\colorize-fixtures\test.css, and
vscode-1.59.1\extensions\vscode-colorize-tests\test\colorize-results\test_css.json

I have examined the source code downloaded directly from the Git Hub repositories for numerous earlier versions and found these same files and licensing information.
For example following is an extract of the comments in VSCode 1.54.3, file named "test.css" 
"/* css Zen Garden default style v1.02 */
/* css released under Creative Commons License - http://creativecommons.org/licenses/by-nc-sa/1.0/  */
/* This file based on 'Tranquille' by Dave Shea */
/* You may use this file as a foundation for any new work, but you may find it easier to start from scratch. */"  
A similar statement can be found in the second file named "test_css.json" as follows:
"**_"c": " css released under Creative Commons License - http://creativecommons.org/licenses/by-nc-sa/1.0/  ",
                              "t": "source.css comment.block.css",..._**"

From the content of all the test files in those directories I am presuming those files are compiled into the VSCode binary package to perform part of the functions available in the application; please advise if my presumption is correct.  Additionally, could the build-master or architect also provide a statement saying what the code is used for and whether it is in the functional (binary) distribution for use?

The Creative Commons Attribution-NonCommercial-ShareAlike 1.0 Generic (CC BY-NC-SA 1.0) license (http://creativecommons.org/licenses/by-nc-sa/1.0/) allows anyone to modify the source code but if the modified version of the software is distributed it must be released under the CC BY-NC-SA 1.0 license.  Additionally, the license does not allow for use for any commercial purpose (see the human-readable summary of the license which states the following: NonCommercial — You may not use the material for commercial purposes.)  You may wish to confer with your legal counsel to determine whether your team’s use of the software is in compliance with the license. 

Thank you,
Dr. Chris Wood

**Comment by chrisdias** [comment]
ok, I see you were looking at a tag. I wanted to make sure you were not seeing this in a built version of product somehow.

these are part of our integration tests, they are not built into the final product.  see `scripts/test-integration.bat`.
