### ISSUE TITLE
Word wrap implementation for text editor (f.e like in SublimeText)

### ISSUE THREAD

**Issue by greybax** [Microsoft/vscode#1317]
It would be usefull to implement **Word Wrap**, which supports now in all modern Text Editors (f.e Sublime on screenshot):

* **SublimeText**:
![sublime](https://cloud.githubusercontent.com/assets/3235047/11805592/1eefd99c-a31e-11e5-9cc0-87be77d7cd45.png)

* **vscode**:
![vscode](https://cloud.githubusercontent.com/assets/3235047/11805604/3712c138-a31e-11e5-8cac-c2923f900456.png)

Also would be usefull to implement such features as **Word Wrap Column** and **Ruler**

**Comment by dbaeumer** [comment]
VSCode supports word wrap. Use "editor.wrappingColumn": 0 in the settings. (File > Preferences > Workspace settings).
