### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Astaldo2003** [microsoft/vscode#131717]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 6.1.7601
```

Steps to Reproduce:

1. Launch vscode with `code --disable-extensions`
2. Open new editor window if not
3. Paste some text more than ~1000 lines
4. Press `ctrl+k m` or `ctrl+shift+p` and run `change language mode`

If text less than 1000 lines it works fine:
![maximum call stack size exceeded](https://user-images.githubusercontent.com/35482652/130976479-cd1390b1-c800-4adc-a638-94e5105e1b39.gif)

> ERR Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
>     at Xe (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:22892)
>     at Object.kernelFunc (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:105789)
>     at o (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:242459)
>     at C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:243406
>     at y.scopedRun (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:240964)
>     at y.runKernelFunc (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:243158)
>     at y.runKernel (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:241470)
>     at stringSplit_ (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:437551)
>     at Object.stringSplit__op [as stringSplit] (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:392714)
>     at C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:212953
>     at C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:213212
>     at C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:240843
>     at y.scopedRun (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:240964)
>     at y.tidy (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:240777)
>     at Module.f (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:256518)
>     at C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:212600
>     at ar (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:215253)
>     at hr.processStack (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:224679)
>     at hr.executeWithControlFlow (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:223909)
>     at async hr._executeAsync (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:222881)
>     at async Nt (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:187687)
>     at async Promise.all (index 0)
>     at async hr.executeWithControlFlow (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:223941)
>     at async hr._executeAsync (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:222881)
>     at async fr.executeAsync (C:\Users\podvysotskiy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\@vscode\vscode-languagedetection\dist\lib\index.js:2:230456)

**Comment by rzhao271** [comment]
\closedWith 7294dbdc9959d3229daf50f60240e75b9509e898

**Comment by sandy081** [comment]
Confirming that this is merged in release - https://github.com/microsoft/vscode/commit/84fe01573e9b4d74096030a89ec6dd6df1cc6aaa
