### ISSUE TITLE
Terminal random errors

### ISSUE THREAD

**Issue by iperson** [microsoft/vscode#131735]
Issue Type: <b>Bug</b>

Running GNU make in terminal will randomly cause terminal to have strange behavior like no updates in the terminal, being unable to type in the terminal, until VSCode restart. This happens about 1 out of 10 to 20 times. Started after most recent update, never had this problem before.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.94GB (26.86GB free)|
|Process Argv|--crash-reporter-id 4dfd8db4-d54e-4a66-b04e-167eabdeb29a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
githistory|don|0.6.18
gc-excelviewer|Gra|3.0.43
blender-development|Jac|0.0.16
vscode-cudacpp|kri|0.1.1
rainbow-csv|mec|1.9.1
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
vscode-ai-remote|ms-|0.4.0
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
makefile-creator|zen|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
bridge0723:30353136
javagetstartedc:30351792
vsdyn321cf:30356811
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by meganrogge** [comment]
please attach a gif
