### ISSUE TITLE
[Test UI] Testresult are not shown if running tests over different test controller/profiles

### ISSUE THREAD

**Issue by d-biehl** [microsoft/vscode#131716]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59 and 1.60-insider
- OS Version: Windows 10/Arch Linux

If you have more then one test controller registered, and if you want to run all tests with the "Run Tests" button, then the test run stops after the first controller ends the test run. Or better, the result of the other, longer running test runs are not shown in the UI. 
If you run only one test profile, everything works fine. 

See here ...

![sample-1629983529652](https://user-images.githubusercontent.com/7069968/130968950-1da69121-b38d-40d5-a944-74055a4e3813.gif)

There is a message in debug console:

    Setting the state of test "file:///c%3A/tmp/vscodetest/test-provider-sample/sample/test.md/2 + 2 = 5" is a no-op after the run ends.

Steps to Reproduce:

To repoduce this, you need at least 2 test controllers registered. 
For testing purposes, I have prepared a github repo based on the test-provider-sample and the insider version of the python extension.

https://github.com/d-biehl/test-provider-sample

---

just one thougth: it seems, running tests over different test controllers, the test profiles are executed in parallel. I think, it should be better to run the test profiles sequentialy or it should be configurable. Because if there could be side effects running tests profiles in parallel, ie. using the same resources or testing the UI with different language or so...

**Comment by connor4312** [comment]
\closedWith https://github.com/microsoft/vscode/commit/604dd1418fe540861768d54276e227b7922378b5

**Comment by rchiodo** [comment]
/verified

Sample test controller ran at the same time as the python one

**Comment by d-biehl** [comment]
/verified

But:
Running tests over different test controllers, the test profiles are executed in parallel. I think, it should be better to run the test profiles sequentialy or it should be configurable. Because there can be side effects running tests profiles in parallel, ie. using the same resources or testing the UI with different language or so...

**Comment by connor4312** [comment]
> Running tests over different test controllers, the test profiles are executed in parallel. I think, it should be better to run the test profiles sequentialy or it should be configurable. Because there can be side effects running tests profiles in parallel, ie. using the same resources or testing the UI with different language or so...

That's something we intentionally leave up to the test extensions to deal with 🙂
