### ISSUE TITLE
Color Picker Not showing

### ISSUE THREAD

**Issue by dipsonu10** [microsoft/vscode#131785]
Issue Type: <b>Bug</b>

{
    "workbench.startupEditor": "newUntitledFile",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Microsoft",
    "java.configuration.checkProjectSettingsExclusions": false,
    "terminal.integrated.rendererType": "dom",
    "workbench.preferredDarkColorTheme": "Default Dark+",
    "terminal.integrated.shell.linux": "/bin/bash",
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.previewLsp": true,
    "java.project.importOnFirstTimeStartup": "automatic",
    "dart.debugExternalLibraries": false,
    "dart.debugSdkLibraries": false,
    "kite.showWelcomeNotificationOnStartup": false,
    "terminal.integrated.enableBell": true,
    "powershell.powerShellDefaultVersion": "PowerShell (x64)",
    "python.showStartPage": false,
    "editor.wordWrap": "on",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        },
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe (migrated)": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": []
        }
    },
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "terminal.integrated.defaultProfile.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe (migrated)",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'",

    "terminal.integrated.defaultProfile.linux": "bash",
    "[java]": {
        "editor.defaultFormatter": "redhat.java"
    },
    "terminal.integrated.fontFamily": "Cascadia Code PL",
    "files.exclude": {
        "**/.git": false
    },
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook",
        "*.m": "default"
    },
    "editor.fontSize": 15,
    "editor.fontFamily": "Cascadia Code",
    "workbench.activityBar.visible": false,
    "workbench.colorTheme": "DD Dark theme"
}

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.43GB free)|
|Process Argv|--crash-reporter-id f1cd7c19-8917-4998-ba05-bc9eab5c6bbb|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
gitlens|eam|11.6.0
remotehub|Git|0.13.4
reg|ion|1.0.3
git-graph|mhu|1.30.0
vscode-docker|ms-|1.16.0
dotnet-interactive-vscode|ms-|1.0.2409020
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.0
cpptools|ms-|1.6.0
live-server|ms-|0.2.8
java|red|0.81.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
material-theme|zhu|3.11.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
bridge0723:30353136
vsdyn420:30356812
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by rebornix** [comment]
@dipsonu10 can you provide more info like in what files/languages you can't use the color picker?

**Comment by dipsonu10** [comment]
In **json** file 
For editing colour of different components
