### ISSUE TITLE
Project Folder Not opening in Terminal

### ISSUE THREAD

**Issue by saadbinsaeed007** [microsoft/vscode#131788]
Issue Type: <b>Bug</b>

Hope you are doing well.
i am facing a problem in vs code.When i try to open my project by right clicking on the project folder then click on "open with code".But my terminal does not open the desired folder and I am always needed to change directory to come in to folder.
Please solve my issue.Bundle of Thanksss.....

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.62GB (7.43GB free)|
|Process Argv|--crash-reporter-id 82afe205-e2d4-429d-a0ae-2b0f536477bd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|1.6.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
django|big|1.0.2
vscode-html-css|ecm|1.10.2
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040
vssid140cf:30358037

```

</details>

**Comment by meganrogge** [comment]
Can you share a gif of the issue so I can be sure I know what you mean?
