### ISSUE TITLE
[Bug] `cursorWordPart[Left/Right]` navigations doesn't work for text like `foo1Bar`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131774]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Enter `foo1Bar` in the editor.
2. Put cursor at the beginning.
3. Use `cursorWordPartRight`.
4. Cursor goes to the end.

Expected behavior:

The cursor stops just before `Bar`.

**Comment by hediet** [comment]
I don't know the semantics of `cursorWordPartRight` - why do you think this is a bug?

I think this feature should be documented (see #131429).

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/147074
