### ISSUE TITLE
Frequent Crash - Reason: 'crashed', Code: '-2147483645'

### ISSUE THREAD

**Issue by Stephen-Ross** [microsoft/vscode#131714]
I'm encountering a frequent and frustrating crash. This has been happening for around 6 months but I've been wary of opening a bug report.

I cannot reliably reproduce the issue, occasionally the app will crash as soon as I've opened it (and can happen repeatably on me attempting to open the app). Other times I'll be in the middle of working and it'll crash.

**Actual Result:**
On each occasion though I will get the message box that the window has crashed and that I can reopen it with the message `reason: 'crashed', code: '-2147483645'`.
![image](https://user-images.githubusercontent.com/22176150/130972121-fe88241e-0f6c-44a9-a036-f3389a95181c.png)
When I am able to reopen the app I get the error that the Extension Host has crashed and would I like to restart it.

**Expected Result:**
VS Code doesn't crash when I'm in the middle of working and is able to be reliably opened.

**Things I've Tried:**
- Full clean re-install. I nuked my VS Code install and then re-installed.
- Running with all extensions disabled.
- Tried running the insiders build.
But none of these have allowed me to get to the bottom of the issue.

I have attached a dmp file that has been generated.
[5166cc11-f576-4099-93b4-07a88e1b02fe.zip](https://github.com/microsoft/vscode/files/7060123/5166cc11-f576-4099-93b4-07a88e1b02fe.zip)

I enjoy using VS Code, but I'm nearing the end of my patience with the continual crashes.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (8.90GB free)|
|Process Argv|--crash-reporter-id b03ea020-f6e4-4bee-aab8-6807e777224c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
csharp|ms-|1.23.14
gradle-language|nac|0.2.3
material-icon-theme|PKi|4.10.0
vscode-protolint|ple|0.6.0
errorlens|use|3.4.0
licenser|ymo|1.6.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by Stephen-Ross** [comment]
Apologies as this is only happening on my work machine I didn't have access until this morning.

I have attached the output of `code --verbose` both when the application crashes on startup and from when it runs normally.
[VS Verbose.zip](https://github.com/microsoft/vscode/files/7075295/VS.Verbose.zip)

**Comment by MawRojas** [comment]
I've had the same issue for quite  a long time with different machines. Did you figure out what was causing it?

**Comment by deepak1556** [comment]
Sorry for the delayed response, this is now blocked on a newer runtime update for further testing.

**Comment by goliafrs** [comment]
Fresh install insiders, user setup, v1.63.

![1](https://user-images.githubusercontent.com/6551082/140710046-78f491d0-c5c2-40a3-9bba-5725daebf3e9.jpg)

After synchronizing the settings and extensions, the error appears with the same code as in the thread.

**Comment by deepak1556** [comment]
@goliafrs can you attach crash log based on https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by goliafrs** [comment]
> @goliafrs can you attach crash log based on https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

[eb752ffc-d06f-4150-bd2a-806f9c1b8a8c.zip](https://github.com/microsoft/vscode/files/7503691/eb752ffc-d06f-4150-bd2a-806f9c1b8a8c.zip)

**Comment by Patrick2812** [comment]
can someone explain what is electron 16 and how to update it?
As i am also having the same issue with vs code
