### ISSUE TITLE
Interactive Window doesn't always keep latest execution scrolled into view

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#131732]
Version: 1.60.0-insider (user setup)
Commit: b71e20ceba833fcb2efada1a4765929ff96ccbb1
Date: 2021-08-26T05:13:37.746Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

1. Open the myanalysis_plotly.py file from https://github.com/greazer/covid-19-data
2. To run it all the way through there are some setup steps in the Readme. 
3. Command Palette -> Jupyter: Run All Cells

Just let the cells execute. Don't touch anything. At some point it's likely that the autoscrolling to keep the last executed cell output in view fails to work. 

There's a side effect bug to this occurrence as well. Which I'll enter separately.

**Comment by amunger** [comment]
should be fixed with autoscrolling improvements
