### ISSUE TITLE
enter key does not make new lines

### ISSUE THREAD

**Issue by stanleyhon** [Microsoft/vscode#13170]
- VSCode Version: 1.5.3
- OS Version: W10 internal (MS FTE)

Steps to Reproduce:

Unclear step to reproduce.
Sometimes problem intermittent, spamming enter 10 times will sometimes unlock it and let it create new lines again. Many tabs open, complex folder open in the folder viewer.

Debugging steps taken:

- Tried different physical keyboard   
- Tried onscreen keyboard
- Tried uninstalling all extensions
- Tried restart that comes with uninstalling an extension
- Tried switching tabs and typing (can type)

**Comment by mattdot** [comment]
Same issue with same configuration.  My project is not as complex and just has a few nodejs files.

Found that hitting ctrl+enter can be a workaround to create some new lines.

**Comment by hoovercj** [comment]
Thank. God. I was going crazy thinking this was just me.

**Comment by hoovercj** [comment]
Follow-up:

OS Build: 14939.100

Consistently repros here in the Github comment box and in other text boxes around the internet (reddit comment fields, etc.). Closing and re-opening this page and clicking into the comment box exhibits the same behavior as VS Code.

I can only repro in Chrome, though, and not IE or Edge. That suggests it is a Chromium bug independent of VS Code.

**Comment by bpasero** [comment]
This is a WINDOWS bug.

**Comment by joaomoreno** [comment]
#12929 

> The change that regressed this in Windows has been found and the fix is now being fast tracked.

**Comment by Richard-Payne** [comment]
I'm seeing this issue on Linux too.

**Comment by programmingandtea** [comment]
This is also a bug with the Mac version.

**Comment by clounie** [comment]
Same on Mac:  
- macOS Sierra 10.12.3
- VS Code 1.11.0-insider (so nothing accidentally fixed between 1.10 and 1.11)

**Comment by amykapernick** [comment]
Currently using Mac OSX 10.12.5 and VS Code Version 1.13.1 and getting the same issue

**Comment by RichardLindhout** [comment]
Mac OSX 10.12.6 and VS Code Version 1.17.2 did have this when doing 'yarn start' in the integrated terminal.
