### ISSUE TITLE
[coffeescript] Syntax Support for 1.11.1 `import` and `export

### ISSUE THREAD

**Issue by alexlur** [Microsoft/vscode#13173]
CoffeeScript 1.11 adds support for [ES2015 modules](http://coffeescript.org/#modules). It would be nice to update the syntax highlighting to reflect this.

---
- VSCode Version: 1.5.3
- OS Version: macOS Sierra

**Steps to Reproduce:**
1. Switch language to CoffeeScript.
2. Type `import _ from 'lodash';`

**Expected Result:**

Code is properly highlighted.

**Actual Result:**

Tokens are not recognized.

**Comment by aeschli** [comment]
That's what I see after updating to the latest grammar from https://github.com/textmate/coffee-script.tmbundle:
![image](https://cloud.githubusercontent.com/assets/6461412/19377614/140739b2-91e8-11e6-928b-8933e4ef50ff.png)

Is that acceptable?

**Comment by alexlur** [comment]
Thanks for the reply! Can you make `from` a keyword too?

**Comment by aeschli** [comment]
I changed the grammar to https://github.com/atom/language-coffee-script with support for 'import' and 'from'.
Please file additional issues directly against that grammar.
