### ISSUE TITLE
Navigation in Angular app stopped working

### ISSUE THREAD

**Issue by lechu1985** [microsoft/vscode#131709]
Issue Type: <b>Bug</b>

VS code stopped finding reference in my apps Angular or pure js.
 
I suspect it is due to an extension but I removed them all and even then it did work. I am unable to figure out what to do next. 

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (15.73GB free)|
|Process Argv|--crash-reporter-id e222c790-ae3f-4f11-b23b-75655264fd26|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|Memory (System)|24.88GB (19.78GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-wsl|ms-|0.58.2
ng-template|Ang|12.2.0
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30322572
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
bridge0723:30353136
vsdyn420:30356812
vscus224:30358039
vssid140cf:30358037

```

</details>

**Comment by mjbvz** [comment]
Closing as it doesn't happen in insiders. 1.60 stable should be going out sometime this week

**Comment by lechu1985** [comment]
After upgrading to 1.60 this issue was still reproducible. 

I was able to fix it by removing all of the contents of:
`C:\Users\<USER>\AppData\Roaming\Code`
I had to reconfigure the look and feel of the app, but at least code navigation works. 
Please let me know if you need any files/info to figure out what might have been wrong. I will be more than happy to provide what you need.
