### ISSUE TITLE
Add context key for active/test file

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131748]
Testing microsoft/vscode-python#17040

For the debug welcome view we show the extension Buttons only when the appropriate file is open.  [Code pointer](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/welcomeView.ts#L69)
For example, only when a `javascript` file is open we would show the `js-debug` welcome buttons.
I believe this reduces clutter and makes it easier for the user to make a right choice based on context.

Currently in the Test welcome view we do no such thing. I can have a `.js` file open and I am offered to `Configure Python Tests`.

Creating this issue so you consider to introduce a similar mechanism for Test view.

![Screenshot 2021-08-24 at 13 35 28](https://user-images.githubusercontent.com/1926584/130609842-4fe35de2-7c63-4ba1-80bf-cb5c12f9688e.png)

**Comment by connor4312** [comment]
We don't have a notion of "interesting languages" for testing. But there is already a context key for the active editor, extensions can use that to match test patterns when possible.
