### ISSUE TITLE
Sandbox: explore how to support direct helper process to renderer communication

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131798]
Allow direct communication between a helper process and the renderer.

![image](https://user-images.githubusercontent.com/900690/131149466-e9585594-671a-4c8e-b8c1-33c171608975.png)

**Some raw ideas**
* what if Electron would provide an API similar to `BrowserWindow.loadUrl` but `UtilityProcess.loadUrl` to create such a child process 
* Electron should delegate this to Chrome and reuse the ability Chrome has to spawn utility processes like GPU and Network
* Utility process has node.js integration enabled and direct communication support to a renderer (either via electron IPC or message ports)

**Comment by deepak1556** [comment]
Prototype demonstrating communication between Node integration enabled chromium service process and sandbox renderer is complete.

Link: https://streamable.com/tqozwr

Current state of API:

```ts
// Main Process
interface ProcessOptions {
 entry: string;
 displayName?: string;
 args?: string[];
}

interface MessageEvent {
  data: any;
}

class UtilityProcess extends NodeJS.EventEmitter {

 constructor(options: ProcessOptions);

 postMessage(channel: string, message: any, transfer?: Electron.MessagePortMain[]): void;

 on(event: 'message', listener: (event: MessageEvent) => void): this;
}

// Service Process
interface MessageEvent {
 data: any;
 ports: MessagePortMain[];
}

interface Process extends NodeJS.EventEmitter {

 on(channel: string, listener: (event: MessageEvent) => void): this;

 send(message: any);
}
```

**Comment by deepak1556** [comment]
Next Steps in order:

- [ ] Create custom builds with the new API
- [ ] Implement extension host with the above API and iron out edge cases if any
- [ ] Send RFC PR to https://github.com/electron/governance/tree/main/wg-api/spec-documents
- [ ] Upstream implementation PR to https://github.com/electron/electron

**Comment by safasofuoglu** [comment]
Will this work enable shareable non-copy buffers, rather than one-way ownership transfer?

**Comment by deepak1556** [comment]
Exploration is complete and extension host has adopted this behind a setting. Next steps continued in https://github.com/microsoft/vscode/issues/154007
