### ISSUE TITLE
Finding the desired file extension by typing first two or three letters of the name of the extension while saving files

### ISSUE THREAD

**Issue by KLN888** [microsoft/vscode#131781]
While saving files using VS code we need to select the file types from the available list of files .If we want to select a particular extension then instead of scrolling we can type the starting letters of the extension then we can see all the types of extensions starting with the letter .So it would be even more better if we can get the extension by typing first two or three letters of the extension .If we want to select the files with .html extension then we need to type H and T  but after typing H this  will be shown
![Screenshot 2021-08-28 152022](https://user-images.githubusercontent.com/69143967/131214122-49598f40-8499-4ce3-9076-d0b34cdab54e.jpg)
And after typing T then this will be displayed 
![Screenshot 2021-08-28 152057](https://user-images.githubusercontent.com/69143967/131214138-fb026f47-82e1-41fe-8e47-e5a16cc4f252.jpg)
Instead of this , it will be better if we type h and t on keyboard and immediately all the names starting with h and t  like HTML will be shown .

**Comment by KLN888** [comment]
This is not related to vs code extensions .This is related to the name of file extensions that we need to store while saving files.

**Comment by KLN888** [comment]
How to find the part of the source code related to  saving files in vs code.

**Comment by KLN888** [comment]
@vscode-triage-bot  help needed to find the code related to saving files

**Comment by bpasero** [comment]
This dialog comes from Windows, so I suggest you file a feature request against windows: https://www.windowscentral.com/how-send-feedback-about-windows-10-microsoft
