### ISSUE TITLE
Increase limit of recently opened workspaces and files

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#131708]
Issue Type: <b>Feature Request</b>

Now the quick open recent history size is 30 maximum. I would like to set to 3000. I have too many projects.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.4.0-80-generic
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic
Remote OS version: Linux x64 5.4.0-80-generic

**Comment by alexr00** [comment]
@xgdgsc do you want to change the history limit for _tasks_ or for _files_?

**Comment by xgdgsc** [comment]
I think it' s files and recent folders, which I didn' t find a config.

**Comment by TylerLeonhardt** [comment]
Just so we're clear, @xgdgsc, can you send a screenshot?

**Comment by xgdgsc** [comment]
It' s just the `Ctrl+R` shortcut which refers `File: Open Recent`. I find the folder number searchable in this list not enough for me. I want to be able to search for all folders that exist now that I have opened once.

**Comment by bpasero** [comment]
The limit is only 30 in the menu to keep the menu from becoming large. If you click on "More..." or use the associated command you get all entries.

**Comment by xgdgsc** [comment]
I search for some projects that I have opened a year ago and there is no result? Is there a history project size limit?

**Comment by bpasero** [comment]
There is only a limit of 100 entries for the recently opened workspaces, folders and files:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L44-L44

**Comment by xgdgsc** [comment]
Could that be changed to a config item? I believe modern hardware could handle 10000 easily.

**Comment by bpasero** [comment]
Yeah I think we should increase this, maybe 500-1000, I do not see perf issues with it.

**Comment by rdwoodring** [comment]
Looking to contribute. Am I understanding correctly that the change needs to happen here: https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L44-L44

**Comment by vanenshi** [comment]
Hi, I want to take this issue as my first contribution.

If I get it right, your want to make a config item for max recently opened workspaces? also users can only increase it up to 1000? right?

**Comment by xgdgsc** [comment]
I' d like default 500 and max 100000, don' t know what others think.

**Comment by vanenshi** [comment]
I need to add the config item somewhere in the settings, but there is no `workspaces` item.

can somebody help me here? should I create a `workspaces` item with only one subitem inside it??

**Comment by github-account1111** [comment]
Why have a max to begin with? It's akin to [this](https://www.youtube.com/watch?v=Hwab428Iqxs) problem in Bitcoin. As the hardware progresses you need to keep updating the max, while having that max at all accomplishes nothing. Just remove the limit.

Default can stay as is IMO, because it seems to work for most people, as this hasn't been reported until now, and a larger quantity might actually be a problem for some.

**Comment by jesperjen98** [comment]
I would like to try working on this issue, i am a first time contributor and this issue does not seem to hard.

**Comment by TylerLeonhardt** [comment]
@vanenshi there is a related setting called `search.quickOpen.includeHistory` so we should probably align with that and call the setting: `search.quickOpen.history`

**Comment by vanenshi** [comment]
> @vanenshi there is a related setting called `search.quickOpen.includeHistory` so we should probably align with that and call the setting: `search.quickOpen.history`

oh, thank you
I didn't notice that, I start working on it soon

**Comment by bpasero** [comment]
The limit is now 500, thanks to https://github.com/microsoft/vscode/pull/135741. This limit only applies to the quick picker:

![image](https://user-images.githubusercontent.com/900690/139639212-84ed9259-18c8-4aef-92a4-dc333cb142f8.png)

**Comment by github-account1111** [comment]
@bpasero Why not keep the limit at 100 and let the user change it to whatever the number they need?

**Comment by bpasero** [comment]
Yeah a setting is fine as well for me, if someone wants to do a PR for tht.
