### ISSUE TITLE
Allow extensions to contribute language workspace files to be treated specially

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131894]
Currently when a user opens a `.code-workspace` file we treat it specially by offering a blue floating button.
Ideally we could somehow open this mechanism for extensions, such that extensions can contribute `workspace files` for which this button should be shown, and extensions should also contribute an action which will get executed once a user clicks on this button.

This should make the flow of opening a `pom.xml` file smoother.

fyi @testforstephen

![Screenshot 2021-08-30 at 13 47 29](https://user-images.githubusercontent.com/1926584/131334419-219f1376-5b2b-4360-bfaf-d969e219d51b.png)

**Comment by bpasero** [comment]
Makes sense to me. I feel this is pretty much in the ballpark of "extension recommendations" so I move it to Sandy who owns this area. 

The flow I could see work:
* you see a button "Open with Extension..." 
* you click it and get extensions offered either installed or not yet installed based on recommendations
* you pick an extension
* the extension gets either installed and/or activated and handles the opening

The opening can either be a simple operation such as opening the folder of the project file or a more complex one where maybe a multi root workspace is generated ad-hoc.

**Comment by bpasero** [comment]
@isidorn btw I don't really agree with the issue title, imho this has nothing to do with `.code-workspace` files, can you update it?

**Comment by isidorn** [comment]
`.code-workspace` was just an example of files which we already treat a bit special. But makes sense to update the title, since the mechanism would be different and contributed by extensions.

**Comment by testforstephen** [comment]
I like this idea. In some other Java IDEs, when the user selects a build file, such as pom.xml to open, it will lead to opening the entire project. It would be helpful if VS Code offered a similar feature.

// cc: @akaroml @nickzhums @Eskibear @jdneo @CsCherrYY

**Comment by isidorn** [comment]
Parts of the discussion from https://github.com/microsoft/vscode/issues/131893

@bpasero A slight variant of the proposal is to allow "File > Open Workspace from File" and being able to select "pom.xml" or even C# solution files 👍

@JoeRobich and @nohwnd for `.csproj` files

**Comment by sandy081** [comment]
We have a mechanism to recommend extensions when certain file types are opened. For eg., if you open a .java file, we recommend java extension pack. Why not following the same strategy for this file?

> if the extension is installed, then delegate to the extension to execute some special opening operation.
Seems like a request for new API and I am not sure what and how this generic opening operation shall look like.

**Comment by testforstephen** [comment]
> We have a mechanism to recommend extensions when certain file types are opened. For eg., if you open a .java file, we recommend java extension pack. Why not following the same strategy for this file?

Yes, the .java file currently has the recommendation for Java extension pack. But pom.xml does not. It would be nice if VS Code could add the missing recommendation when opening a pom.xml file.

>if the extension is installed, then delegate to the extension to execute some special opening operation.

>Seems like a request for new API and I am not sure what and how this generic opening operation shall look like.

The user experience would be like:
When the user opens the pom.xml file, the Java extension has the ability to contribute a blue floating button in the bottom right corner (e.g. "**Open as Project**" or "**Open as Workspace**"). If that button is clicked, then the Java extension will invoke the "Open Folder" command to open the containing folder.

**Comment by isidorn** [comment]
@testforstephen we fixed the issues that we recommend Java for pom.xml https://github.com/microsoft/vscode/issues/131893

And I agree the user experience would be like this. And as I mentioned above the `Open Workspace` command should allow users to pick these contributable files.

**Comment by testforstephen** [comment]
> we fixed the issues that we recommend Java for pom.xml #131893

@isidorn It seems a little different. When i open a folder with pom.xml in the root directory, now there is popup to recommend Java extension. But opening a pom.xml in a new VS Code window, no recommendation appears. I'm using the latest insider.

**Comment by isidorn** [comment]
@testforstephen thanks! I have reopened that issue with your steps.
