### ISSUE TITLE
intellicode not working

### ISSUE THREAD

**Issue by alagesan007** [microsoft/vscode#131834]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59
- OS Version:Device name	LAPTOP-K00SCSVQ
Processor	Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz   2.59 GHz
Installed RAM	4.00 GB (3.86 GB usable)
Device ID	C09C5F2A-B9F4-4DEC-BD9B-74B1A178EEC5
Product ID	00327-36223-34304-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Steps to Reproduce:

1.VS intellicode not working in javascript files .pls solve it
![scrnshot](https://user-images.githubusercontent.com/82628512/131207298-027c8f20-4999-45b5-a91d-7f1a8afa8bf0.png)

2.
![scrnshot](https://user-images.githubusercontent.com/82628512/131207410-a6227f0d-6c23-450a-bc6a-aad4065a4d92.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
