### ISSUE TITLE
Quickfix popup stopped suggesting imports for JS

### ISSUE THREAD

**Issue by croraf** [microsoft/vscode#131840]
Does this issue occur when all extensions are disabled?: Yes/No  (It requires ESLint extension to reproduce)

- VS Code Version: 1.59.1
- OS Version: Linux x64 5.4.0-45-generic

Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:54:37.513Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-45-generic

Steps to Reproduce:

1. Context: 
 - have a JS project with `package.json` with `"type": "module"` property.
 - Have ESLint extension installed, eslint dependency installed locally with `npm install eslint`
 - Have the following eslint configuration file `.eslintrc.cjs`:

```
module.exports = {
  'env': {
    'node': true,
    'es2021': true,
  },
  'extends': 'eslint:recommended',
  'parserOptions': {
    'ecmaVersion': 12,
    'sourceType': 'module'
  },
  'rules': {
  }
};
```

2. have two JS files `first.js` and `second.js`

```
// second.js
const myItem = 5;
export {myItem};
```

```
// first.js
const temp = myItem;
```

During typing of `myItem` in `first.js` the editor does suggest me to complete it and import, and on confirm it does complete and import `myItem`. (this part works even without ESLint extension and library)

But, if it is already completed, it does get underlined as a missing error and you can open a Quickfix popup. But in the Quickfix popup there is no suggestion to "Add the missing import".
![Screenshot from 2021-08-28 12-53-06](https://user-images.githubusercontent.com/19698636/131215682-c85f9e2f-1ae9-4644-84bc-a75c2961c3f7.png)
![Screenshot from 2021-08-28 12-55-07](https://user-images.githubusercontent.com/19698636/131215733-2985b5b2-8cf6-4fd4-9904-c3425c99a779.png)

The "Add the missing import" suggestion was present until sometime in the mid 2021. (But perhaps I disabled something in the settings also.)

**Comment by mjbvz** [comment]
If this only happens when eslint is enabled, please start by filing it against that extension

**Comment by croraf** [comment]
`vscode-eslint` hasn't had production release since 2020, and this issue started to appear mid 2021.

Are typescript lanugage features (built in into vscode) in charge of providing quick fix `Add missing import` in JS files?

**Comment by mjbvz** [comment]
Auto import come from VS Code itself but if this bug only happens when eslint is enabled, something with that extension is causing issues. Please put together a demonstration of the issue that doesn't require anything eslint and we'll take a look

**Comment by croraf** [comment]
(Yes, I think it might be better to go with the issue through the vscode-eslint extension repo, even though the error might be in the vscode API)

FYI:

The autoimport on _autocompletion dropdown_ selection works fine! (as on the following two images)
![Screenshot from 2021-08-31 01-31-55](https://user-images.githubusercontent.com/19698636/131418902-024c44a4-ff2c-40f7-a5d9-135a72b254eb.jpg)
![Screenshot from 2021-08-31 01-33-48](https://user-images.githubusercontent.com/19698636/131418937-db589a0a-81b0-442e-a6c7-1019a9afe306.png)

**What does not work is the following:** 
- VSCode does provide a Quick Fix feature (API) as can be seen on this image `Quick Fix... (Ctrl + .)`
![Screenshot from 2021-08-31 01-44-28 (1)](https://user-images.githubusercontent.com/19698636/131420370-f02a7a03-bc0a-4f4a-90c7-46a9502b8df3.jpg)
- the `Quick Fix` feature suddenly stopped providing "Add missing import" option (which is requested by the vscode-eslint  Extension with the rule `no-undef`)

**Comment by croraf** [comment]
Could it be that the `typescript language features` module provided the "Add missing import" and "Add all missing imports"  Quick fix options, and it stopped providing this two months ago?
