### ISSUE TITLE
.NET Coding Pack fails to install the VS extension

### ISSUE THREAD

**Issue by profix898** [microsoft/vscode#131899]
I have downloaded the '.NET Coding Pack for VS Code' (https://code.visualstudio.com/learn/educators/installers#_net-coding-pack) installer. VS Code (step 1) and the .NET SDK (step 2) get installed correctly. However, the third step, which is supposed to install the '.NET Extension Pack' extension into the newly installed VS Code, fails. The error message simply says: "Failed to install .NET Extension Pack" (see screenshot).
It looks like you have to launch VS Code once, so that it registers itself with Windows as the default program for VS Code extension packages. After that you can at least proceed manually.

Obviously, the .NET Coding Pack is meant for new .NET users to get started. Due to the above problem that turns out a pretty bad experience ...

![dotnet-pack-vscode](https://user-images.githubusercontent.com/2789426/131342558-b5f0fb7b-09f1-469c-8beb-4ebe421a738e.png)

**Comment by sana-ajani** [comment]
Hey @profix898, thanks for letting us know about this. Since this seems to be an issue with the .NET extension pack, I've opened it in their repo: https://github.com/dotnet/installer/issues/11977
