### ISSUE TITLE
Breakpoint margin shouldn't be available if debugger experiment is off.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#131835]
Current bits allow breakpoints to be set even if the debugging experiment is disabled. Doesn't really make sense to do this.

**Comment by roblourens** [comment]
On the vscode side where the breakpoint margin is shown, we don't know whether there is a debug adapter available for a notebook. Breakpoints can be added if there is a debug adapter available for the language. This isn't really the right condition. They are actually getting enabled by the Python extension. Have been meaning to investigate a new package.json contribution for a notebook DA. I just wrote an issue for that:https://github.com/microsoft/vscode/issues/132014

**Comment by roblourens** [comment]
Although my proposal still doesn't really help, because the contribution can't be conditionally enabled by a setting. But, that is a temporary situation and not a typical thing to do.
