### ISSUE TITLE
VSCode with High Contrast mode

### ISSUE THREAD

**Issue by nishant09** [Microsoft/vscode#13184]
- VSCode Version: 1.4.0
- OS Version: Windows

I would like to know how have you guys implemented High Contrast color theme ? Is it a native support from Electron ? 

My app is using the latest version of Electron. However, if i turn on the Windows High contrast mode my app doesn't align well.

I would appreciate if you guide here

**Comment by bpasero** [comment]
All with CSS.

**Comment by nishant09** [comment]
thanks
