### ISSUE TITLE
Live Share extension in codespace strange detail text

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#131826]
"This"

![image](https://user-images.githubusercontent.com/8586769/131198362-10ceb3ae-db68-4815-bfe3-1c5d62e0fe10.png)

**Comment by JacksonKearl** [comment]
![Uploading image.png…]()

**Comment by JacksonKearl** [comment]
Not just live share

**Comment by sandy081** [comment]
This is an issue with codespaces embedder defining global css style for `status-text`. There is already an issue filed in codespaces for this. Hence marking as upstream.
