### ISSUE TITLE
[Problems panel] "Show Active File Only" does not work when a folder is selected

### ISSUE THREAD

**Issue by joel-schaal** [microsoft/vscode#131801]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Windwos_NT x64 10.0.19043

Steps to Reproduce:

1. Open a workspace that has a lot of errors
2. Open the Problems panel and enable the filtering option "Show Active File Only"
3. Click on a File in the Explorer:  the panel is refreshed and only the errors/warnings for that file are shown
4. Click on a Folder in the Explorer: the panel is not refreshed and the same errors/warnings are shown

I was expecting that this would work the same as what I'm used to with Eclipse, which helps drilling down when you have an "interesting" legacy application to improve, with thousands errros/warnings... 

Also, this is even more helpful for workspaces having multiple projects (folders ?) in them, because sometimes quality varies from one project to another, and I did not find a way to temporarily disable an entire project from the problems tab (some people had [similar need](https://github.com/microsoft/vscode/issues/22289) if I understand right)

**Comment by sandy081** [comment]
Filter `Show Active File Only` shows problems for the file that is opened and active in the editor. It is not for folders. You can use text/glob filter input to filter by folders

![image](https://user-images.githubusercontent.com/10746682/133090787-c6516197-aeb8-421c-a530-66e3437bc63a.png)
