### ISSUE TITLE
"Your changes will be committed to main" should be dismissable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131890]
Love the "your changes will be committed directly" inline notification 👏 

The problem is that once user figures this out we still show it and there is no way to hide it. It can overlap over content in the Staged changes.
We should fix this by simply making this dialog dismissible, we could have an `x` on the right. And once user clicks it we would no longer show it for him / her.

fyi @joamoreno

![Screenshot 2021-08-30 at 12 16 12](https://user-images.githubusercontent.com/1926584/131324470-e0e269e3-59c9-4b81-840f-88af50a5ba7e.png)

**Comment by eamodio** [comment]
This has been added to the latest insiders version of GitHub Repositories (will hit stable this iteration).

**Comment by isidorn** [comment]
Great, thanks a lot 👏  
Let's add to September milestone so we get this verified.
