### ISSUE TITLE
 "default" should at the end of value "null”

### ISSUE THREAD

**Issue by v-ericawu** [microsoft/vscode#131886]
VS Code Version: VSCode 1.59.1

Steps to Reproduce:
1. Install C/C++ extension.
2. Click "Manage" in the lower left corner.
3. Click Settings.
4. Type "C_Cpp: Clang_format_sort Includes" and click drop-box.
5. Observe the information.

Actual:
![image](https://user-images.githubusercontent.com/78774400/131318950-fd6ee0e4-bc44-4f46-bef5-7d0c1c78e54f.png)

Expected:
the "default" in settings will be displayed after the specific default value
such as:
![image](https://user-images.githubusercontent.com/78774400/131320383-1eb4992d-e6a1-4608-8b19-7fd172279c4a.png)

**Comment by IllusionMH** [comment]
Most likely related to #128367

[Extension specifies default value `null`](https://github.com/microsoft/vscode-cpptools/blob/5dcb3081e502f84185b71f773f3d106b5d27f63c/Extension/package.json#L786)

However check in `settingsTree` will "lose" `null` and `undefined` values even if explicitly specified in `package.json` https://github.com/microsoft/vscode/blob/f146e5d4c435a0eaa5da688c43fabdb449d9dcb4/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L1572

/assign @rzhao271

**Comment by rzhao271** [comment]
I think I was trying to fallback to using an empty string for consistency, but it turns out I don't need to do that.
