### ISSUE TITLE
Mac M1 Big Sur - keybindings not working

### ISSUE THREAD

**Issue by meschenbaum** [microsoft/vscode#131818]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: 11.5.2

Steps to Reproduce:

1. Open file for edit.
2. Try to move cursor to end of word with option+leftArrow shortcut. Nothing happens.
3. Checked Keyboard Settings in preferences, and looks correct. Tried to redo keybinding and it would not allow an option+leftArrow. It actually created a duplicate entry. Seems to have an issue pairing the option key to another key for a keybinding.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Option+LeftArrow`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by meschenbaum** [comment]
I was able resolve the issue. Seems Big Sur added keybindings to their
spaces that are interfering. I removed the interfering keybindings and
reset vscode’s.

Cheers,
Matt
