### ISSUE TITLE
Getting started extension contribution is failing to read markdown file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131809]
See https://github.com/lunapaint/vscode-luna-paint/issues/97

When loading luna paint's getting started, it fails to read markdown file.

![image](https://user-images.githubusercontent.com/2193314/131173263-ce568a9c-43b0-478b-afdc-43d01b843de2.png)

The failing url works fine, for example https://tyriar.vscode-unpkg.net/Tyriar/luna-paint/0.9.0/extension/getting-started/2-pencil-tool.md

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/135035576-aac5b487-130e-4462-8db5-88af52c43165.png)
ah. looks like `resolve` is insufficient to determine if a file exists...

**Comment by rchiodo** [comment]
/verified

Luna Paint getting started works and I can go through the whole thing
