### ISSUE TITLE
Windows formatted path is inserted into a bash terminal when dragging and dropping files from the explorer panel

### ISSUE THREAD

**Issue by Rami-Sabbagh** [microsoft/vscode#131844]
Issue Type: <b>Bug</b>

- Run VSCode on a Windows machine.
- Connect to a Linux machine using SSH remote.
- Open a directory as the workspace.
- Open a terminal, which should be bash.
- Drag and drop a file from the explorer side panel.
- A Windows formatted path (using back-slashes `\`) is inserted instead of posix formatted path (using forward-slashes `/`).

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-81-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.96GB free)|
|Process Argv|--crash-reporter-id 032e08d3-d701-454f-bef1-8110bf04eabc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: personal-vps|
|OS|Linux x64 5.4.0-81-generic|
|CPUs|Intel Core Processor (Haswell, no TSX) (1 x 2399)|
|Memory (System)|1.89GB (0.27GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.0.10
vscode-firefox-debug|fir|2.9.4
discord-vscode|icr|5.7.0
dotenv|mik|1.0.1
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
material-icon-theme|PKi|4.10.0
vscode-asl|Tho|1.0.0
errorlens|use|3.4.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.4
vscode-zipfs|arc|2.3.0
markdown-table-prettify|dar|3.5.0
gitlens|eam|11.6.0
vscode-docker|ms-|1.16.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30351387
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140cf:30358037

```

</details>

**Comment by meganrogge** [comment]
@JacksonKearl I investigated and it looks like the explorer is providing a Windows, back-slashed path to the terminal via drag and drop for this remote Linux case

**Comment by JacksonKearl** [comment]
Does the `explorer.copyRelativePathSeparator` setting help here at all?
