### ISSUE TITLE
File menu items disabled

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131895]
1. Insiders, new user data dir
2. Add some folders to your workspace
3. Notice that some actions are disabled in the menu which should be enabled 🐛 

I can not reproduce this, sorry! However please let me know what info you need the next time I see this.
Or maybe other users are also seeing this

fyi @bpasero

![Screenshot 2021-08-30 at 13 45 14](https://user-images.githubusercontent.com/1926584/131335806-aae2581b-da9f-4449-90d9-a5f8ee352c7c.png)

**Comment by sbatten** [comment]
@isidorn I don't see the issue, it doesn't appear that you have an active window, so none of the disabled entries should be enabled.

**Comment by isidorn** [comment]
The window was active, I had focus in the editor and I was typing. Maybe the window focus logic was broken.

**Comment by isidorn** [comment]
I was not able to reproduce this again.
Feel free to close if I am the only one that complained about this

**Comment by sbatten** [comment]
closing until we see again
