### ISSUE TITLE
vscode get stuck when open html file

### ISSUE THREAD

**Issue by jiangbo0216** [microsoft/vscode#131803]
Issue Type: <b>Bug</b>

I am working in a large project , and vscode get stuck when I open a html file, I can't reproduce in a small project

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.67GB free)|
|Process Argv|. --crash-reporter-id 880cc852-ff8d-403a-8da5-ed5103f4c13e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by aeschli** [comment]
Any chance you can share the HTML file where it happens?

Does it reproduce with extensions disabled? (command: `Developer: Reload with Extensions Disabled`).

Can you set `"html.trace.server": "verbose"` and check the Output view: HTML language server

**Comment by jiangbo0216** [comment]
> Any chance you can share the HTML file where it happens?
> 
> Does it reproduce with extensions disabled? (command: `Developer: Reload with Extensions Disabled`).
> 
> Can you set `"html.trace.server": "verbose"` and check the Output view: HTML language server

**Comment by jiangbo0216** [comment]
> Any chance you can share the HTML file where it happens?
> 
> Does it reproduce with extensions disabled? (command: `Developer: Reload with Extensions Disabled`).
> 
> Can you set `"html.trace.server": "verbose"` and check the Output view: HTML language server

the wired thing is if i open the file alone, or in other opened window, it is ok.

only when i open it in my huge project (almost 9.5G), vscode get stuck like what I show above

and I can not reproduce it in my friend's computer

disable all extension is not helpful 

HTML language server do not show nothing meanningful

[Trace - 下午8:50:50] Sending request 'textDocument/linkedEditingRange - (10)'.
Params: {
    "textDocument": {
        "uri": "xxxx"
    },
    "position": {
        "line": 74,
        "character": 31
    } 
}


[Trace - 下午8:50:50] Received response 'textDocument/linkedEditingRange - (10)' in 0ms.
No result returned.

**Comment by jiangbo0216** [comment]
maybe have chance to see it with you?

**Comment by aeschli** [comment]
Can you disable breadcrumbs and see if that makes a change?

**Comment by jiangbo0216** [comment]
yep
// src/vs/platform/configuration/common/configurationModels.ts

![image](https://user-images.githubusercontent.com/18640629/131522799-10761d5c-f5f3-48d0-9824-b4ef16c4751b.png)
![image](https://user-images.githubusercontent.com/18640629/131522826-38a5b95f-df4a-45b4-98c5-870302b95e34.png)
I think disable breadcrumbs can be help, and I make some change to the source code, the vscode response speed is well now, 
this maybe cause bug, but for now it's ok for me

**Comment by jiangbo0216** [comment]
![image](https://user-images.githubusercontent.com/18640629/131523717-308572a8-9829-445b-84b3-406ebd8fc6cf.png)
![image](https://user-images.githubusercontent.com/18640629/131523781-20c9d38a-9e33-4168-9dc9-f2ab063bce6e.png)

here has more detail

**Comment by aeschli** [comment]
So you removed the calls to objects.freeze and distinct and the problem is gone?

I assume you are running from sources?

**Comment by aeschli** [comment]
The problem seems to be related to the configuration object.

**Comment by jiangbo0216** [comment]
> So you removed the calls to objects.freeze and distinct and the problem is gone?
> 
> I assume you are running from sources?

yes, I running from sources, and find the problem in 
https://github.com/microsoft/vscode/blob/0a06a59ea6d90a20763520b7f12ac4827cd47a49/src/vs/platform/configuration/common/configurationModels.ts#L142

and 

https://github.com/microsoft/vscode/blob/0a06a59ea6d90a20763520b7f12ac4827cd47a49/src/vs/platform/configuration/common/configurationModels.ts#L77

**Comment by aeschli** [comment]
Both changes are needed?

**Comment by jiangbo0216** [comment]
> ![image](https://user-images.githubusercontent.com/18640629/131523717-308572a8-9829-445b-84b3-406ebd8fc6cf.png)
> ![image](https://user-images.githubusercontent.com/18640629/131523781-20c9d38a-9e33-4168-9dc9-f2ab063bce6e.png)
> 
> here has more detail
> 
> I and my friend open same file, the bug only occur to me, I think the way to reproduce is complex
> 
> hope this will be fix soon



> Both changes are needed?

you can see these images

**Comment by sandy081** [comment]
Is it possible to provide a sample repo where I can reproduce the issue?
