### ISSUE TITLE
Option to force adding `.js` extension when importing from .ts files into .ts files

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#131837]
```ts
// foo.ts
export const foo = 'foo';
// index.ts
import { foo } from './foo';
```
Because of the infamous https://github.com/microsoft/TypeScript/issues/24779, if you want to use `tsc` to compile this code into ES modules that can run natively in node 14+, sorry you can't, because the `import` line lacks a .js extension. 

As crazy as it sounds, the current consensus is to add the .js extension in the import line **when you're writing the .ts file**, like this:
```ts
// index.ts
import { foo } from './foo.js'; // add `.js`, even though the file does not exist
```
It works. But unfortunately auto-import won't do it for you.

So, can we add an option to force appending `.js` with auto import, even when writing .ts files?

**Comment by andrewbranch** [comment]
You want `TypeScript > Preferences: Import Module Specifier Ending: js`

<img width="426" alt="image" src="https://user-images.githubusercontent.com/3277153/131399515-609a3776-c8b6-4d14-ab53-cd467f3a3746.png">

**Comment by ZYinMD** [comment]
You're right. Thanks!
