### ISSUE TITLE
AutoImport showing multiple imports and always imports relative 

### ISSUE THREAD

**Issue by rkesters** [microsoft/vscode#131849]
Does this issue occur when all extensions are disabled?: YES

- VS Code Version:
Version: 1.59.1 (Universal)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. In a Lerna based mono repo, attempt to quick fix: import from another package in the repo

![Screen Shot 2021-08-28 at 3 57 09 PM](https://user-images.githubusercontent.com/5572145/131229696-cb81a740-de6e-42b3-90fe-d97a6fed2fb6.png)

As shown in the screenshot all imports are relative. 

1. But If you have already imported something from the package then it imports correctly

![Screen Shot 2021-08-28 at 4 04 32 PM](https://user-images.githubusercontent.com/5572145/131229734-24d662bd-5f82-4b79-b794-57e54e93fec9.png)

Lerna Version: 4.0.0
TS Version: 4.3.2

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share a minimal, self contained example that demonstrates the problem

/needsMoreInfo
