### ISSUE TITLE
VS Code Crashed

### ISSUE THREAD

**Issue by wkey1980** [microsoft/vscode#131852]
Issue Type: <b>Performance Issue</b>

VS Code locked up laptop for about 5 minutes then displayed message saying the program has crashed. After  about 5 minutes the recomes responsive again.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.11.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics (6 x 1700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 20, 14|
|Memory (System)|7.23GB (3.60GB free)|
|Process Argv|--unity-launch --crash-reporter-id ab4191bc-64a8-41e1-b1ec-357d2f7953a6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	  8479	code main
    0	     0	  8485	   zygote
    0	    81	  8519	     gpu-process
    0	     0	  8486	   zygote
    0	     7	  8488	     zygote
    1	    81	 10820	       window (Issue Reporter)
    0	    22	  8554	   utility
    0	    96	  8617	   shared-process
    0	    22	  8637	     ptyHost
    0	     0	  9602	       /usr/bin/bash
    0	     0	 10837	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 10838	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   200	  9364	   window (index.html - travel website - Visual Studio Code)
    0	   133	  9387	     extensionHost
    0	    67	  9444	       /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=9387
    0	    15	  9445	       electron_node server.js 
    0	    44	  9485	       electron_node server.js 
    0	    22	  9506	       electron_node server.js 
    0	    30	  9537	       /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=9387
    0	    52	  9549	       electron_node tsserver.js 
    0	    67	  9557	       electron_node tsserver.js 
    0	    22	  9565	         electron_node typingsInstaller.js typesMap.js 
    0	     7	  9400	     watcherService
    0	     7	  9414	     searchService
    0	   178	 10763	   window (Visual Studio Code)
    0	   141	 10792	     extensionHost
    0	    67	 10807	       electron_node server.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - travel website - Visual Studio Code)
|    Folder (travel website): 20 files
|      File types: jpg(6) svg(4) png(4) css(1) html(1) js(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.3.0
html-class-suggestions|And|1.1.1
html-end-tag-labels|ant|0.7.0
path-intellisense|chr|2.4.0
highlight-line-vscode|cli|0.0.1
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
live-sass|gle|5.1.0
svg|joc|1.4.9
vscode-gutter-preview|kis|0.27.1
vscode-language-babel|mgm|0.0.32
vscode-scss|mrm|0.10.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
vscode-flexbox-picker|Rax|0.0.1
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1
trailing-spaces|sha|0.3.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
errorlens|use|3.4.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
wordpress-toolbox|wor|1.3.11
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by deepak1556** [comment]
Can you attach the crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!
