### ISSUE TITLE
Add a "not in" conditional operator for when clause in extensions

### ISSUE THREAD

**Issue by Cammisuli** [microsoft/vscode#131819]
We currently have this list of operators that we can use when defining the `when` clause:

Operator | Symbol | Example
-- | -- | --
Equality | == | "editorLangId == typescript"
Inequality | != | "resourceExtname != .js"
Or | \|\| | "isLinux\|\|isWindows"
And | && | "textInputFocus && !editorReadonly"
Not | ! | !editorReadonly
Matches | =~ | "resourceScheme =~ /^untitled$\|^file$/"
Greater than | > >= | "gitOpenRepositoryCount >= 1"
Less than | < <= | "workspaceFolderCount < 2"
In | in | resourceFilename in supportedFolders

And with these, the only one that supports custom context is the `in` operator. This is awesome, and I really appreciate it!

But it really needs a `not in` operator as well. There's times where I would like to set the context for only 1 folder, and negate that for everything else. 

The final clause would look like this:
```
{
	"when": "resourcePath not in appDirectory",
    "command": "generate",
    "group": "2_workspace"
},
```

**Comment by Lorenz-N** [comment]
Experimented a bit today with the `when` clause and I also would have expected that it's possible to combine the "Not" and "In" operator. But I don't think it makes sense to introduce a worded operator with spaces like `not in`, it would probably make more sense to just add the operator as `!in` or `![key value] in [key value]`.

Just as a side-note: Looks like "Matches" at least supports combining the "Not" when doing a `=~ !/regexp/` to get a "NotMatches" (somehow missing in the documentation).

**Comment by qiancy98** [comment]
If one can solve #91473 then this can be simply covered by adding brackets.

**Comment by ulugbekna** [comment]
As far as I understand, this is implemented: https://code.visualstudio.com/api/references/when-clause-contexts#in-and-not-in-conditional-operators
