### ISSUE TITLE
Botframework samples unable to debug using f5 key

### ISSUE THREAD

**Issue by ShujaathKhan** [Microsoft/vscode#13188]
- VSCode Version: 1.5.2
- OS Version: windows 10

Steps to Reproduce:
1. get the repo of samples from github bot framework
2.  open the examples of botframework
3. set the path of js for execution
4. press f5

**Comment by waderyan** [comment]
@ShujaathKhan can you provide a link to github bot framework? 

Also, have you generated a `launch.json`? f5 will not work without setting up the `launch.json` debug file.

**Comment by ShujaathKhan** [comment]
Hi @waderyan link for your ref: https://github.com/Microsoft/BotBuilder/tree/master/Node/examples
would more thankful as i'm very new to VSCode, visual studio gels well with c#.
thanks

**Comment by waderyan** [comment]
@ShujaathKhan thank you for sharing the link. 

I need more info to help you with this issue. You mention you "set the path of js for execution" what do you mean by that? What specifically did you do? 

Please follow this [doc](http://code.visualstudio.com/docs/editor/debugging#_launch-configurations) to understand `launch.json`. If the file is not generated than <kbd>f5</kbd> will not do anything.

**Comment by waderyan** [comment]
Closing until more info is obtained.
