### ISSUE TITLE
Force installing a web extension is not working

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131891]
Steps to Reproduce:

1. Open github.dev 
2. Choose an extension that cannot be installed on web and enable it in web using `remote.extensionKind` setting. Eg:
```json
"remote.extensionKind": {
        "julialang.language-julia": [
            "web"
        ]
    }
```
Note: It is expected to get a warning for "web" value in the setting.
3. Try to install that extension - `julialang.language-julia`

🐛 Gets an incompatibility error

Expected to install the extension

**Comment by lramos15** [comment]
Not clear if I'm doing something wrong but all I see is the warning saying it cannot be installed on web even with that setting

**Comment by sandy081** [comment]
Can you please check in which version you are in github.dev, if it is stable you can switch to insiders version using the gear menu.

**Comment by joyceerhl** [comment]
I had to reload github.dev in order to get the Install button to show up. @sandy081 is that expected?

**Comment by sandy081** [comment]
yes.
