### ISSUE TITLE
vscode mirror not working 

### ISSUE THREAD

**Issue by yousufAzadAyon** [microsoft/vscode#131892]
- VS Code Version: 1.59.1
- OS Version: Ubuntu 20.04

I get this message every time I run the command `sudo apt update`

<pre>  File has unexpected size (255716 != 256011). Mirror sync in progress? [IP: 13.93.152.112 80]
  Hashes of expected file:
   - Filesize:256011 [weak]
   - SHA512:9923e06a69f972b4fe12a9a01abeff42be235a49d91c2b5dc2d013e9aa495ccee7b468038aa98d2c57baaad89c55d1db8c2fe5b7825d8eabb90effc50e092a38
   - SHA256:66f52a872e8b4aecfacc20dbfec5b428973676a1cf188adcfbfa0e2572e9c620
   - SHA1:78871ddd4b7e6a6a37c49161cc5d94ec8189b276 [weak]
   - MD5Sum:b05f77c350a37dbe89ae6a21f6b8fa47 [weak]
  Release file created at: Thu, 26 Aug 2021 06:27:16 +0000
Fetched 332 kB in 2s (207 kB/s)
Reading package lists... Done
<font color="#EF2929"><b>E: </b></font>Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (255716 != 256011). Mirror sync in progress? [IP: 13.93.152.112 80]
   Hashes of expected file:
    - Filesize:256011 [weak]
    - SHA512:9923e06a69f972b4fe12a9a01abeff42be235a49d91c2b5dc2d013e9aa495ccee7b468038aa98d2c57baaad89c55d1db8c2fe5b7825d8eabb90effc50e092a38
    - SHA256:66f52a872e8b4aecfacc20dbfec5b428973676a1cf188adcfbfa0e2572e9c620
    - SHA1:78871ddd4b7e6a6a37c49161cc5d94ec8189b276 [weak]
    - MD5Sum:b05f77c350a37dbe89ae6a21f6b8fa47 [weak]
   Release file created at: Thu, 26 Aug 2021 06:27:16 +0000
<font color="#EF2929"><b>E: </b></font>Some index files failed to download. They have been ignored, or old ones used instead.</pre>

this has been an issue for me for a week.

**Comment by Tyriar** [comment]
Reported to the Linux repo team, thanks.
