### ISSUE TITLE
Unable to push on Github

### ISSUE THREAD

**Issue by codersaiful** [microsoft/vscode#131857]
Issue Type: <b>Bug</b>

Github pull push is not working

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.93GB free)|
|Process Argv|--crash-reporter-id 11fa694f-897f-48a0-8b0b-8612a12d59e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
ACF-Snippet|ant|1.9.0
vscode-intelephense-client|bme|1.7.1
simple-react-snippets|bur|1.2.3
path-intellisense|chr|2.4.0
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
vscode-github-actions|csc|0.21.2
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
theme-macos-classic|hua|1.3.0
githd|hui|2.2.4
rest-client|hum|0.24.5
phpcs|ika|1.0.5
vscode-wordpress-hooks|joh|0.5.5
wordpress-vscode-extensionpack|jpa|1.2.0
vscode-liquid-snippets|kil|2.0.3
elementor-snippets|lau|0.0.1
jupyter|ms-|2021.8.1236758218
remote-wsl|ms-|0.58.2
php-docblocker|nei|2.3.0
language-liquid|nei|0.1.1
file-icons-mac|way|1.0.1
wordpress-toolbox|wor|1.3.11

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by BunnyTheLifeguard** [comment]
Are you using the UI for pushing?

![image](https://user-images.githubusercontent.com/36411819/131249002-ca67e586-dd04-49d4-95eb-118a279f4fc3.png)

Same thing happened to me all of a sudden today, pushing via terminal still works though.
See also:

https://github.com/microsoft/vscode/issues/42039

**Comment by codersaiful** [comment]
Yes, I m using UI

**Comment by gjsjohnmurray** [comment]
Any clues in the Git channel of the Output tab?

**Comment by BunnyTheLifeguard** [comment]
> Any clues in the Git channel of the Output tab?

Here is mine from my last commit:

```
> git log --oneline --cherry main...main@{upstream} --
> git pull --tags origin main
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
> git ls-files --stage -- C:\Users\...\src\App.vue
> git cat-file -s ced...013
> git show --textconv :src/App.vue
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
```

**Comment by BunnyTheLifeguard** [comment]
After working with GH actions I was made aware to refresh my access token for VSCode. Now push/pull via UI works again, though there seem to be rare cases in some repos where it still throws the error, can't really tell what's different in those atm.

@codersaiful can you check your own token an confirm? 🤔

**Comment by codersaiful** [comment]
After update git, the issue has gone. Problem solved.

**Comment by BunnyTheLifeguard** [comment]
That's odd, I reinstalled my git installation (via chocolatey) and tried again, but still not working in some repositories.
I noticed that it's prompting me for my ssh password when the UI is not working and I am trying to push/pull manuially via command line.

Here's my configuration (was working before):

.gitconfig:
![image](https://user-images.githubusercontent.com/36411819/131684864-d4c85551-8061-43c7-ae22-c03f979c080a.png)

and the content of .gitconfig-gh:
![image](https://user-images.githubusercontent.com/36411819/131684975-f06269c7-6894-46f2-94ff-cb805e47f3f9.png)
