### ISSUE TITLE
Typescript Pick<> and Omit<> refactoring

### ISSUE THREAD

**Issue by Maxim-Mazurok** [microsoft/vscode#131879]
Related to: https://github.com/microsoft/vscode/issues/54185 and https://github.com/microsoft/TypeScript/issues/25607

VS Code seems to be aware of which properties I can `Pick<>` or `Omit<>`:
![image](https://user-images.githubusercontent.com/7756211/131292193-3241a138-7446-4bfa-a816-36a2e5a3f6e2.png)

Yet, when I'm trying to refactor code and rename the property - it doesn't change `'height'` string in the `Pick<>`:

![image](https://user-images.githubusercontent.com/7756211/131292097-5fba389b-3091-4b6e-a6b4-3c2f59b9d5d4.png)

Note, that it did change `console.log(userWithoutName.height);` to `console.log(userWithoutName.height);` automatically.

So, I want VS Code to automatically rename properties in `Pick<>` and `Omit<>` for TypeScript.

Thanks!

**Comment by IllusionMH** [comment]
This refactoring should be requested in TS repo and in fact it has already been requested https://github.com/microsoft/TypeScript/issues/30263
