### ISSUE TITLE
Update Now moves all VS Code windows to the same macOS Desktop

### ISSUE THREAD

**Issue by brandondrew** [microsoft/vscode#131850]
Does this issue occur when all extensions are disabled?: 
I was reminded of this bug by updating, so it was then too late to test without extensions. Since I can't control when updates are available, it is impossible for me to experimentally verify this, but I'm almost certain that this behavior is not related to extensions.  

- VS Code Version: 1.59.1
- OS Version: 11.4 (20F71)

Full output of "About Visual Studio Code":
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

Steps to Reproduce:

1. Distribute your windows across macOS Desktops according to whatever pattern you find most productive (by project, for example).
2. Press the "Update Now" button to update VS Code
3. Discover that your window arrangement has been utterly disregarded.

**Comment by joaomoreno** [comment]
cc @bpasero @deepak1556

**Comment by bpasero** [comment]
Upstream: https://github.com/electron/electron/issues/10124

**Comment by joaomoreno** [comment]
Closing as per electron/electron#10124
