### ISSUE TITLE
"Emmet: Toggle comment" not working in insiders build

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/vscode#131863]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.60.0-insider (user setup)
Commit: 8dbad73de575e47e127c8b1a4324f2b61257fbdc
Date: 2021-08-27T21:25:29.781Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create or open a `.js` file with some code
2. Run the `"Emmet: Toggle Comment" command on any line which contains code -> Nothing happens

**Comment by ArturoDent** [comment]
Looks like that command works on html or css files only.  See https://docs.emmet.io/actions/toggle-comment/#:~:text=Toggle%20Comment%20This%20action%2C%20as%20name%20says%2C%20toggle,while%20Emmet%E2%80%99s%20one%20do%20this%20on%20current%20context.

**Comment by TarunavBA** [comment]
> Looks like that command works on html or css files only. See https://docs.emmet.io/actions/toggle-comment/#:~:text=Toggle%20Comment%20This%20action%2C%20as%20name%20says%2C%20toggle,while%20Emmet%E2%80%99s%20one%20do%20this%20on%20current%20context.

@ArturoDent I totally agree with you! 👍

**Comment by TarunavBA** [comment]
@marvinhagemeister  It only works with **html and css**

**Comment by marvinhagemeister** [comment]
Alright, I guess that works for me.
