### ISSUE TITLE
Typescript extension dies unexpectedly

### ISSUE THREAD

**Issue by lukjaki** [microsoft/vscode#131811]
Issue Type: <b>Bug</b>

TS/JS extension dies repeatedly and unexpectedly all the time.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:57:20.140Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv|. --crash-reporter-id c27db050-406d-4bbf-90de-150f108e339e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.19.4
vscode-database|baj|2.2.3
vscode-twig-pack|baj|1.1.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
todo-tree|Gru|0.0.213
vscode-styled-components|jpo|1.6.6
vscode-docker|ms-|1.16.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
vscode-typescript-next|ms-|4.5.20210826
indent-rainbow|ode|7.5.0
vscode-css-peek|pra|4.2.0
swdc-vscode|sof|2.5.24
tabnine-vscode|Tab|3.4.23
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn420:30356812
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by mjbvz** [comment]
Closing as not actionable without more info
