### ISSUE TITLE
best way to use VSCode to view and edit a graphical file

### ISSUE THREAD

**Issue by llnagy** [Microsoft/vscode#13183]
Request for information on what classes to extend to implement this behavior myself in VSCode. Looking for guidance. 

- VSCode Version: 1.5.3
- OS Version: Windows 7 sp1

Steps to Reproduce:
1. open a file myfile.esfc that is a proprietary format
2. display a graphical representation of that file in html using a custom parser and graphics package
3. allow the user to edit that graphical representation with custom controls/commands
4. allow the user to save those changes back to the proprietary format

I've looked at the previewHtml extension and created a TextDocumentContentProvider, but what I am trying to do is use VSCode as a framework for editing and verifying chart diagrams not just preview them. 

It looks like the editor.contribution.ts contains the functions that register the different types of IEditorDesctiptor; string, text diff, binary with their associated IEditorInput.  Is this where a custom chartEditor and chartInput could be registered? where is the transition from file contents to the view being done? Is this done in EditorPart? It looks like it is asking the registered editor for the input to show the contents.  It looks like the fileEditorInput is used to get the appropriate IEditorDescriptor from the registry.

**Comment by jrieken** [comment]
That's right - you can use the `previewHtml` command to show contents and it also allows for running script which means it's powerful. Still, the preview command isn't our UI extensibility story and currently there is none. You can read more about our approach and way we don't allow for arbitrary UI extensions here: https://code.visualstudio.com/docs/extensions/our-approach
