### ISSUE TITLE
My git repos always get broken

### ISSUE THREAD

**Issue by Yonier** [microsoft/vscode#131830]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. I clone a repo with git in VS, it works well for a couple days
2. Then it get broken from nowhere any time i try to do push, i get this message:

`
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/master': reference broken
`

Is any solution there?, this problem is so annoying!!

**Comment by TarunavBA** [comment]
Did you check which branch you are?

**Comment by Yonier** [comment]
> Did you check which branch you are?

When checking the branch appears the same message: 'fatal: HEAD...' the repo basically broke from nowhere.

**Comment by TarunavBA** [comment]
Try re cloning the repo.

**Comment by Yonier** [comment]
> Try re cloning the repo.

Yea that works, but it brokes again in a couple days...

**Comment by TarunavBA** [comment]
What is the method of ur cloning?

**Comment by TarunavBA** [comment]
U can try resetting VSCode completely.

**Comment by Yonier** [comment]
> What is the method of ur cloning?
i delete the folder and clone the repo again.

> U can try resetting VSCode completely.
i already tried, i start to think is a pc's problem.

**Comment by TarunavBA** [comment]
> > What is the method of ur cloning?
> > i delete the folder and clone the repo again.
> 
> > U can try resetting VSCode completely.
> > i already tried, i start to think is a pc's problem.

@Yonier did you delete the `.vscode` folder in the AppData folder?
