### ISSUE TITLE
Unable to debug on the external terminal in Manjaro KDE 21.1.0

### ISSUE THREAD

**Issue by Leismael** [microsoft/vscode#131821]
Issue Type: <b>Bug</b>

1. Install any language plugin. (for example Dart)
2. Open launch.json and put this line --> "console":"externalTerminal"
3. Then press F5 and the error that appears is the following --> "Unable to start debugging: /usr/bin/bash: /usr/bin/bash: cannot execute binary file"

## The terminal configuration in visual studio code is as follows:
![Terminal Settings](https://user-images.githubusercontent.com/39781660/131194018-04da120e-9188-4e20-bb63-83e93e205e64.png)

### Note:
- With the integrated terminal everything works ok.
- And the strangest thing is that not a week ago I had Manjaro Gnome installed with this same version of VSCode and I did not have this problem and the week before that I had Ubuntu with a Gnome desktop and this did not happen either (the amount of distribution changes was by pure experimentation)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.13.11-1-MANJARO snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (5.50GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch /home/leismael/Desktop/Leismael/School/2nd year/EDA I/EDA I Codigo VSCode/Codigo en Dart --crash-reporter-id ed9ba8a1-719d-416a-b602-5fd374219e9a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.3.4
Bookmarks|ale|13.1.0
project-manager|ale|12.3.0
flutter-snippets|ale|2.0.0
vscode-django|bat|1.6.0
search-crates-io|bel|1.2.1
markdown-mermaid|bie|1.10.0
better-toml|bun|0.3.2
vscode-glsllint|CAD|1.4.0
glsl-canvas|cir|0.2.13
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
supersharp|cra|0.1.4
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vscode-great-icons|emm|2.1.79
vsc-material-theme-icons|equ|2.0.10
pubspec-dependency-search|eve|1.1.0
bloc|Fel|5.8.0
vscode-solution-explorer|fer|0.4.4
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.5
auto-using|Fud|0.7.15
kotlin|fwc|0.2.23
godot-tools|gee|1.1.2
go|gol|0.27.1
todo-tree|Gru|0.0.213
vscode-test-explorer|hbe|2.21.0
live-html-previewer|hdg|0.3.0
pubspec-assist|jer|2.3.0
vscode-todo-highlight|jgc|2.0.3
vscode-github|Kni|0.30.6
rust-analyzer|mat|0.2.718
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.1.19
csharp|ms-|1.23.14
python|ms-|2021.8.1147840270
vscode-pylance|ms-|2021.8.2
jupyter|ms-|2021.8.1236758218
cpptools|ms-|1.6.0
test-adapter-converter|ms-|0.1.2
cargo|pan|0.2.3
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.10.0
platformio-ide|pla|2.3.3
synthwave-vscode|Rob|0.1.8
crates|ser|0.5.9
markdown-preview-enhanced|shd|0.6.0
shader|sle|1.1.5
vscode-3dviewer|sle|0.2.2
shader-toy|ste|0.10.15
vscode-rust-test-adapter|Swe|0.11.0
tabnine-vscode|Tab|3.4.23
even-better-toml|tam|0.14.2
ayu|tea|0.20.2
open-in-browser|tec|2.0.0
vsfire|tob|1.4.1
pdf|tom|1.1.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.5
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.3
vscode-java-dependency|vsc|0.18.7
vscode-icons|vsc|11.6.0
gitblame|wad|8.1.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
material-theme|zhu|3.11.4

(7 theme extensions excluded)

</details>

**Comment by weinand** [comment]
What debugger are you using and how does your debug configuration (from launch.json) look like?

**Comment by Leismael** [comment]
Hello, I already managed to solve this problem. What was causing this was that I had set "bash" as the program to call to run an external console and in manjaro bash as such it is not a console, the Manjaro  KDE console is called "konsole" and well I put that in the place that it had set "bash" and everything started to work

**Comment by Leismael** [comment]
That is, change the line that says "bash" here for "konsole"

![Terminal Settings](https://user-images.githubusercontent.com/39781660/131227318-1f4de26d-703b-43d0-9761-f8ce6c3f3218.png)

**Comment by weinand** [comment]
Great that you could find a solution.
