### ISSUE TITLE
vscode.TestRun state methods incorrectly handle multiple items with the same id in different TestItemCollections

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#131827]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: 11.5.2

Steps to Reproduce:

Create a nested structure of vscode.TestItems like:

* (controller root)
  * Test Target (id: `target1`)
    * Test Class (id: `class1`)
      * Test Method (id: `method1`)
    * Test Class (id: `class2`)
      * Test Method (id: `method1`)

Then create a vscode.TestRun and enqueue both versions of Test Method.

This should mark both as running, however only the last one will be marked running.

According to the documentation for TestItem this should be allowed since their parent containers should have different identifiers. 

> Identifier for the TestItem. The test item's ID must be unique in the TestItemCollection it's added to.

**Comment by connor4312** [comment]
Good find!
