### ISSUE TITLE
Idea for a standard way of importing Windows Trusted Root Certs for NodeJS

### ISSUE THREAD

**Issue by ryank425** [microsoft/vscode#131804]
- What: I am wondering if MS can come up with official way of doing this and make it part of some official documentation, like maybe here? https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows#install-visual-studio-code

- Why: Using Trusted Root Certificates in NodeJS program is cumbersome and there is no one official way of supporting it.
https://github.com/nodejs/node/issues/4175 and it is required for corp environments to make Secure Network Connection to outside.
 
- Where: Somewhere on MS Official Docs for NodeJS

- When: After discussion and with approvals?

- Who: To MS Devs

- How: Either use https://github.com/microsoft/vscode-windows-ca-certs or some other packages and promote it to have a standard way of importing Trusted Root Certs from Windows for all NodeJS and Electron communities

Background:

I was researching as to how to make our Electron app to fetch Trusted Root Certificates from Windows as it is not possible to know every trusted certificates from clients computer beforehand, and it seems to be that every Electron app uses different ways to solve this issue.

For vscode, I see that this is using 
https://github.com/microsoft/vscode-windows-ca-certs from https://github.com/microsoft/vscode/blob/main/package.json (vscode-proxy-agent has dep to vscode-windows-ca-certs)
and it is a fork from 
https://github.com/ukoloff/win-ca/

and I do see that `This branch is 11 commits ahead, 269 commits behind ukoloff:master.` from https://github.com/microsoft/vscode-windows-ca-certs

Since I couldn't make new issues on https://github.com/microsoft/vscode-windows-ca-certs, I was wondering if I can ask this to Microsoft as I know MS itself has other electron apps like MS Teams.

Maybe other Electron apps in MS is using other ways to import Trusted Root Certificates?

**Comment by chrmarti** [comment]
I like the idea, unfortunately it's currently beyond the scope of the VS Code project. /cc @deepak1556 in case we have someone familiar with Windows APIs and Node.js internally to pass this on.

**Comment by deepak1556** [comment]
I am not aware of contacts who can prioritize this one, best way forward is to work with the Node.js community https://github.com/nodejs/node/issues/3159#issuecomment-672747462.

**Comment by chrmarti** [comment]
Closing as out of scope. Thanks.
