### ISSUE TITLE
The search box is below the navigation bar and cannot be displayed in full

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#131841]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
Version: 1.60.0-insider (Universal)
Commit: b71e20ceba833fcb2efada1a4765929ff96ccbb1
Date: 2021-08-26T05:13:21.489Z (2 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.
- OS Version: Apple M1 (8 x 24)

Steps to Reproduce:
Same as in the picture below
The search box is below the navigation bar and cannot be displayed in full.

![image](https://user-images.githubusercontent.com/13393959/131216589-619a2cea-076e-43d8-84a9-c3dc3cc67a7b.png)

![image](https://user-images.githubusercontent.com/13393959/131216701-50f87a70-4cf6-4f6f-89eb-104cb603a4a8.png)

CPUs | Apple M1 (8 x 24)

**Comment by rebornix** [comment]
@czfadmin may I ask how do you end up with this state?

**Comment by czfadmin** [comment]
@rebornix I came across this by accident, and it doesn't happen in the latest version.It could have happened by accident. I can't reproduce it right now.I will pay attention to this problem and report it again
