### ISSUE TITLE
Files in folder not reloading after switching git branch

### ISSUE THREAD

**Issue by papamuziko** [Microsoft/vscode#13181]
- VSCode Version: 1.5.3
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. create a branch "test" in a big project
2. add some files in a folder
3. switch to master branch
4. those new files will disappear from the Explorer (normal)
5. switch back to the "test" branch
6. those new files don't re-appear in the Explorer => not normal
7. restart Visual Code and those files appear 

This bug is present since some versions (around 1 month).

Please let me know if you need more details

**Comment by bpasero** [comment]
@papamuziko 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* do the steps you talked about
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
