### ISSUE TITLE
Octal literal syntax error is not handled for all cases

### ISSUE THREAD

**Issue by StrongRef** [Microsoft/vscode#1318]
When declaring an octal literal, an error is shown.
![error1](https://cloud.githubusercontent.com/assets/16247609/11806897/601b9f94-a316-11e5-901c-d3a59257fb5f.png)

However, if another error is introduced, the error for octal literal usage is omitted.
![error2](https://cloud.githubusercontent.com/assets/16247609/11806917/7d572592-a316-11e5-8913-9faa08df0f89.png)

Another strict rule violation, this time both errors are visible.
![error3](https://cloud.githubusercontent.com/assets/16247609/11806958/c402e9b8-a316-11e5-9bbb-b6d2ca665e3d.png)

I could like into this one, just want to make sure this is an actual error.

**Comment by dbaeumer** [comment]
This is the tsserver. Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6107
