### ISSUE TITLE
Does not work Explorer

### ISSUE THREAD

**Issue by kamuz** [microsoft/vscode#131820]
Windows 7, Chrome, Firefox, Edge - check browser console

![21-08-28 00-58-25](https://user-images.githubusercontent.com/587267/131192890-19555fd7-bae9-43c9-aa2c-8eacd5463bf1.png)

**Comment by eamodio** [comment]
@kamuz do you still see this behavior?

If so, please enable debug logging by running from _GitHub Repositories: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _GitHub Repositories_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _GitHub Repositories_ channel.
