### ISSUE TITLE
Crash when opening a 35MB, 13.7MM lines txt file 

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#13187]
- VSCode Version: 1.5.3
- OS Version: Ubuntu

I have a text file with 13765201 lines and each line contains an int range from 0 to 20. It's about 35M. Code crashes when opening it. There are other reports on big files (like https://github.com/Microsoft/vscode/issues/6474), however, unlike in this case, Codes will warn that the file is too large there. The bad part is that you cannot click on the wrong file.

![vscode_no_response](https://cloud.githubusercontent.com/assets/9464825/19060141/0e94c0e4-8a18-11e6-9cd1-f1ebec7946c1.png)

Steps to Reproduce:
1. open a large file like [here](https://github.com/innerlee/vscode.bug).
2. then wait.

**Comment by alexandrudima** [comment]
Even with the improvements in #30180 this will crash with OOM.

**Comment by rebornix** [comment]
With our next text buffer implementation, the metadata memory usage of line breaks decrease significantly. Old text buffer used 800+ MB memory for 13765201 lines metadata, but the new one only uses around 20 MB. As we won't release new text buffer impl this iteration, let's revisit this issue next week.

**Comment by rebornix** [comment]
@innerlee we re-implemented our text buffer and the memory usage of loading a file is less. For the file you provided, the metadata for the line breaks is 30MB so we used 75MB in total. The OOM issue should be gone if the system has enough memory.

**Comment by alexandrudima** [comment]
This 13MM lines file now opens fine.
