### ISSUE TITLE
[Bug] `search.exclude` is not working for `workbench.action.showAllSymbols`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#131858]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.59.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make sure `node_modules` is excluded from `search.exclude`.
2. Use `workbench.action.showAllSymbols`.
3. Type in a symbol name that exists in `node_modules`.
4. That symbol shows up in the search result.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/46718
