### ISSUE TITLE
Notebooks - Can't fold code anymore? 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#131817]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Open notebook
2. Hover to left of code that is foldable 
3. The chevron that allowed you to fold code is gone? Or at least blocked by the breakpoint hover

![image](https://user-images.githubusercontent.com/19276747/131192426-45c36a9e-bfa1-4f3d-8c34-7cb96fffcb19.png)

**Comment by rebornix** [comment]
This might be a side effect of breakpoint margin.

**Comment by claudiaregio** [comment]
@rebornix Where is the duplicate for this issue? We got some different feedback still related to breakpoint location
![image](https://user-images.githubusercontent.com/19276747/133946381-d2e35f11-27f6-4aef-9ca0-e79ddc8711d9.png)
