### ISSUE TITLE
Allow installing extension packs those without code

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#131885]
Allow installing extension packs those without code

CC @aeschli

**Comment by sandy081** [comment]
To verify:

- Open github.dev
- Go to extensions view
- Browse for `sandy081.999-test-pack` extension pack
- Make sure you can install this extension pack

**Comment by sandy081** [comment]
@aeschli Can you please verify this?

**Comment by aeschli** [comment]
Verified on github.dev insiders:
Version: 1.60.0-insider
Commit: b6a7847b1d6be302f579ef39d2b9ab891d92eed6
Date: 2021-09-01T01:33:58.665Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4544.0 Safari/537.36 Edg/93.0.933.1
