### ISSUE TITLE
toml files icon in Seti theme

### ISSUE THREAD

**Issue by winuxue** [Microsoft/vscode#13185]
Is it possible to associate the .toml files to the same icon as .config has in Seti Theme?

**Comment by winuxue** [comment]
If you read the documentation (https://github.com/toml-lang/toml)
TOML aims to be a minimal configuration file format. So i think that icon is the best for this file extension.
Horizons uses this kind of configuration files, then it will be usefull for horizon developers like me.

**Comment by aeschli** [comment]
The VSCode Seti theme is based on https://github.com/jesseweed/seti-ui. Please make the request there. Once added there, we will update our association file.

**Comment by winuxue** [comment]
it was added.
https://github.com/jesseweed/seti-ui/issues/429
