### ISSUE TITLE
failed modify keybinds of 'organize imports'

### ISSUE THREAD

**Issue by lifeike** [microsoft/vscode#131861]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1 x64
- OS Version: ubuntu LTS 20.04

Steps to Reproduce:

1.customize or add new keybindings on 'organize imports' (original keybind -- ctrl+shift+o)
2.does not invoke organize imports prompt window at all.

**Comment by mjbvz** [comment]
What language is this for? Please share complete steps to reproduce 

/needsMoreInfo
