### ISSUE TITLE
Do not randomly change port forwarding config if port is already in use

### ISSUE THREAD

**Issue by cesarvarela** [microsoft/vscode#131832]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Windows 11

Steps to Reproduce:

1. Setup port forwarding in one window
![image](https://user-images.githubusercontent.com/1172479/131207264-cd09346e-24a8-4782-81d5-40d90bdb2c5d.png)
2. Open another window with the same port forwarding config
3. Vscode randomly changes the port forwarding setting in the last window to arbitrary port numbers
![image](https://user-images.githubusercontent.com/1172479/131207191-25672277-69b7-4acb-86fd-a1da6366e7aa.png)

I get what it tries to do, but I would prefer if it doesn't do this. Just leave it as it is or add an option to disable this feature, as I find myself having to set up the same config time and time again.

Maybe these could be stored in the .vscode folder, so they don't change every time?

**Comment by alexr00** [comment]
Currently, port forwarding is done per window, so each window is maintaining it's own set of forwarded ports. We would need to move port forwarding in the shared process to prevent this.

**Comment by cesarvarela** [comment]
I know *nada* about vscode's architecture,  but personally, I would be happy with each window just ignoring the config if the port is already busy.

**Comment by alexr00** [comment]
This should be resolved now as we do port forwarding in the shared process.
