### ISSUE TITLE
Add Restart option inside file menu

### ISSUE THREAD

**Issue by thirumalaivasan95** [microsoft/vscode#131854]
While if i add new configuration on vscode, i need to restart manually all the time! while i do that, i need a shortcut key, or just add them on file menu at the top, so that it would be easy transition without i hunt and search them all over, or i don't want to open a terminal again to type code all the time.

Hope you could do that soon!

**Comment by gjsjohnmurray** [comment]
Does the `Developer: Reload Window` command in Command Palette give you the results you want? If so, you can set up your own keyboard shortcut for it.

If not, please explain why you need to restart so often.

**Comment by LaudateCorpus1** [comment]
Macros sound like fun for the [Developer: Reload Window] optioning in keyboard extras. Maybe a C++ widget/applet re-call/API to a running instance of VS Code online? or a .yml that reloads the whole thing? Or even better, a mix of both! Hmmm, thinking of Orbs...

**Comment by weinand** [comment]
@thirumalaivasan95 what kind of "new configurations" are you using that require a VS Code restart?

**Comment by thirumalaivasan95** [comment]
@gjsjohnmurray The feature you've mentioned just reloads the whole vs code, but it wouldn't restart, this means, while i do c++, the configuration sometimes miss the path for header file, which would turns the header file with a squiggly line.  To help resolve this, i need to do restart each and every time. Why wouldn't it so be useful if you do add restart on file menu on next update, would resolve most of the issues and dependencies, adding paths, etc., would resolve. Hope this answers your question!

**Comment by thirumalaivasan95** [comment]
@weinand Simply to reset it all back to where it was on, i mean to let the compiler know what configuration i have prefixed it into. Just no more fancy terms

**Comment by weinand** [comment]
/extCpp

@thirumalaivasan95 this is a problem of the C++ extension. Other language extensions don't require a restart.
