### ISSUE TITLE
Notebooks code cleanup

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#131808]
- [x] Review internal APIs
  - NotebookEditorWidget
  - NotebookViewModel
  - NotebookTextModel#applyEdits
- [x] More work on notebookExecutionService.ts (https://github.com/microsoft/vscode/issues/125668)
- [ ] Clean up cellRenderer.ts
- [ ] CSS cleanup https://github.com/microsoft/vscode/issues/140133

**Comment by rebornix** [comment]
My wish list of internal API of the notebook editor component:

- [ ] No `.viewModel` usage in `contrib`
  - [ ] This means we would need API on `NotebookEditorWidget`

**Comment by roblourens** [comment]
I think probably everything except my cellRenderer task is done? Anything else you plan to do?

**Comment by rebornix** [comment]
Yeah, the only thing left is polishing cell renderer. Let's finish that next month.

**Comment by rebornix** [comment]
Potential issues found while refactoring the cell renderer:

* CSS for dnd doesn't work for markdown cell as it's webview based https://github.com/microsoft/vscode/blob/57f6be85d4863ffef1d372669e42545e7e66d3b1/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L162-L166. Suggestion for fixing this would be moving dnd completely out of the `cellRenderer` and use decoration API which can work in both main and iframe @roblourens

**Comment by rebornix** [comment]
As part of the refactoring, we introduced the concept of `CellPart` which is an abstraction of components in a cell component, e.g., Toolbar, ProgressBar, Output. A `CellPart` should try its best to construct DOM and update DOM nodes in its ctor or `updateLayout`, and perform DOM read operations only in `prepareLayout` to ensure that DOM write and read operations are batched along with other cell parts. A cell part doesn't need to bind its own listener to cell state change, the events will be passed in through `CellPart#updateState`.

![CellPart](https://user-images.githubusercontent.com/876920/142681545-29aca152-4943-484c-b236-f74b5b1cc4bf.png)
