### ISSUE TITLE
Wrong formatter is shown as default and selected after setting ESLint as default formatter in Settings

### ISSUE THREAD

**Issue by croraf** [microsoft/vscode#131862]
Does this issue occur when all extensions are disabled?: Yes/No  (It requires ESLint extension to reproduce, and perhaps also Prettier extension)

- VS Code Version: 1.59.1
- OS Version: Linux x64 5.4.0-45-generic

Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:54:37.513Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.4.0-45-generic

Steps to Reproduce:

1. Install ESLint extension. Install Prettier extension.
2. Go to VSCode Settings file.
3. For the User settings. Set `Editor: Default Formatter` property to "ESLint _dbeaumer.vscode-eslint_". Make sure the Workspace settings' property is None.
4. Check `Eslint › Format: Enable` property in User settings. 
5. Create a testing react typescript project with `npx create-react-app test-formatter --template typescript --use-npm`.
6. (Optional: Restart VSCode to make sure the changes are applied)
7. Go to command popup in the .tsx file with CTRL+SHIFT+P and `Format Document With...`. The selected and the default formatter here is `Prettier` instead of `ESLint` (which is also not shown in the list when first opened after changing the workspace)

![Screenshot from 2021-08-29 14-48-13](https://user-images.githubusercontent.com/19698636/131250896-8eab776d-9932-46e2-9029-4c3dee386a91.png)

![Screenshot from 2021-08-29 14-50-10](https://user-images.githubusercontent.com/19698636/131250920-59b63565-4e45-48b5-8aac-0e3ef5671da3.png)

**Comment by jrieken** [comment]
please check that you don't have a language specific configuration for this value: https://flaviocopes.com/vscode-language-specific-settings/

**Comment by croraf** [comment]
@jrieken Yes this was the case. Why don't these settings show in the settings GUI?

**Comment by jrieken** [comment]
The settings UI is incomplete wrt language specific setting
