### ISSUE TITLE
A11y_Visual Studio Code_ Keyboard Shortcuts_ Usability: No Status message is appear on the screen when we populate invalid data in "Search Field".

### ISSUE THREAD

**Issue by Latha2564** [microsoft/vscode#131877]
GitHubTags:#A11y_VSCode;#A11ySev4;#A11yTCS;#A11yUsable;#DesktopApp;#Visual Studio Code Client;#MAC;#AINotInScope;#Benchmark-VisualStudioCode-MAC-Aug2021

### Environment Details:​
Application Name: Visual Studio Code
Standard Violated: Usability

### Repro Steps:​
1.Open Visual Studio Code editor
2.Tab till "Settings "and press enter
3.Tab till "Keyboard Short Cuts" and press Enter.
4. Tab till "Search Field" and populate random Data in Search field and Pres Enter. 
5.Verify whether the status message will appear on the screen and Voiceover is reading the status message or not.

### Actual Result:
When we populate some invalid data in the Search field "No status message" will appear on the Screen.

### Expected Result: ​
When we populate some invalid data the Status message like "No data available" or 'No results found" should appear on the Screen and also the Screen reader should read the status message.

https://user-images.githubusercontent.com/89508906/131290922-592fa0f1-19e4-4d5e-a483-a488ee0440ee.mp4

### User Impact:
Screen Reader users will find difficult in finding the Search results if no status message will appear on the screen and also the status message not read by the Screen Reader.

**Comment by san-coding** [comment]
Do you want it to display, no results found ?

**Comment by sandy081** [comment]
Assigning to our accessibility expert @isidorn first to get initial insights.

**Comment by isidorn** [comment]
Dislike, dup of https://github.com/microsoft/vscode/issues/131718
Same as what I wrote in that issue in this comment https://github.com/microsoft/vscode/issues/131718#issuecomment-908314958

**Comment by Latha2564** [comment]
![A11y_Visual Studio Code_Keyboard Shortcuts_No status message will appear on the Screen](https://user-images.githubusercontent.com/89508906/132293965-e59ddb87-635c-41cd-a2bd-d265f415e6f0.gif)

**Comment by Latha2564** [comment]
![131877](https://user-images.githubusercontent.com/89508906/133748962-5905037f-9252-4e28-8bdd-e41ffaecd50c.gif)
