### ISSUE TITLE
Reset theming

### ISSUE THREAD

**Issue by CosmoAbdon** [microsoft/vscode#131824]
Issue Type: <b>Bug</b>

Define a custom theme (Dracula by exemple)

When switching tabs or coding, it gonna resets for default one: Dark+

Extension making it: bioSyntax

Extension version: 0.0.11
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.10.60-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 3678)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|5.80GB (1.09GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 7e7dd69d-85c1-4717-b7df-79378c81c438|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140cf:30358037

```

</details>

**Comment by CosmoAbdon** [comment]
Also happens on my desktop

**Comment by aeschli** [comment]
How do you define the custom theme. Can you give some steps or maybe add a animated gif?

**Comment by CosmoAbdon** [comment]
Using Ctrl+ P -> Color Theme
![recording](https://user-images.githubusercontent.com/3496248/131484215-edd47982-9e5d-47ce-9482-7a903bcfa8c1.gif)

--
From Settings (JSON)
![recording (1)](https://user-images.githubusercontent.com/3496248/131484504-7b50b024-5976-4a80-a7f8-cc1655db4a26.gif)

**Comment by CosmoAbdon** [comment]
btw, the theme still reseting because I did activate the extension, if I disable it, I can have my theme working as expected.

**Comment by CodeCrazy-ywt** [comment]
You should press `enter` to apply this theme.

**Comment by CosmoAbdon** [comment]
> You should press `enter` to apply this theme.

Crazy, I'm applying.. I'm not a new user, the revert is caused by an extension.
If I disable the 'byoSintax' extension, everything work flawless.

The main point of this issue is discovering what may be causing this reset and if it affects in any other place.

**Comment by aeschli** [comment]
Maybe that extension switches the theme based on some option (e.g. daylight). Can you add a link to the extension (can't find `byoSintax`)?

**Comment by CosmoAbdon** [comment]
Sure, https://marketplace.visualstudio.com/items?itemName=reageyao.biosyntax

This one

**Comment by aeschli** [comment]
Looks like auto switching theme is a feature of biosyntax.
Uninstall the extension or set `BioSyntax.autoSwitchTheme` to false;
