### ISSUE TITLE
quero estuda html

### ISSUE THREAD

**Issue by juniorpessanha** [microsoft/vscode#131816]
Issue Type: <b>Bug</b>

queria estuda html tem como formata isso por favor

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (4.59GB free)|
|Process Argv|--crash-reporter-id da5bb72a-adbb-4b35-8ae5-05584b865a08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
js-quick-console|Aha|0.0.3
vscode-language-pack-pt-BR|MS-|1.59.3
cortex-builder|sem|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627cf:30244335
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn420:30356812
vscus224:30358039
vssid140cf:30358037

```

</details>

**Comment by CodeCrazy-ywt** [comment]
Google Translate: I wanted to study html is there a way to format it please

**Comment by lramos15** [comment]
`CMD/CTRL + SHIFT + P` -> Format Document
