### ISSUE TITLE
pom.xml should trigger Java extension recommendation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131893]
1. VS Code new user data dir
2. Open `pom.xml` file -> no java extension recommendation 🐛 
3. Open `hello.java` -> notice you get the java extension recommendation

I see that we already have some special code for handling `pom.xml` we should make sure to also offer Java extension when this file is opened.

**Comment by isidorn** [comment]
Ideally apart from Java we would also offer vscode:extension/vscjava.vscode-java-dependency

**Comment by testforstephen** [comment]
Agree, pom.xml is definitely for Java, it's worth recommending "**Extension Pack for Java (vscjava.vscode-java-pack)**", which includes the popular extensions for Java development.

// cc: @akaroml @nickzhums @Eskibear @jdneo

**Comment by jdneo** [comment]
Maybe we can also consider other Java project configuration files we support, like `*.gradle` & `*.gradle.kts`

**Comment by isidorn** [comment]
Assigning to **on-deck** since I think we should do this sooner or later. 
It would also be interesting if C# would need something like this for `.csproj` files. @gregg-miskelly ?

@stevencl did we notice in user studies that users have trouble opening projects for some other languages?

**Comment by bpasero** [comment]
A slight variant of the proposal is to allow "File > Open Workspace from File" and being able to select "pom.xml" or even C# solution files 👍

**Comment by isidorn** [comment]
@bpasero I agree, I think that would be expected. That currently not working is a bit of a wtf moment for the user.

**Comment by gregg-miskelly** [comment]
> It would also be interesting if C# would need something like this for `.csproj` files. @gregg-miskelly ?

I am redirecting to @JoeRobich and @nohwnd

**Comment by sandy081** [comment]
At present, we show following workspace recommendation if user opens a folder that has `pom.xml` file at the root. (There was a bug that recommendation is not getting shown always and fixed it)

![image](https://user-images.githubusercontent.com/10746682/132190973-41f0f187-ff44-4ddb-bbee-2c65ed153a1d.png)

Is this the most common flow than opening the pom.xml?

**Comment by isidorn** [comment]
@sandy081 thanks for pushing the fix. 
In order to have a cleaner discussion around opening let's continue that here https://github.com/microsoft/vscode/issues/131894

As for this issue, your fixes address the original comment. Thus closing.

**Comment by isidorn** [comment]
Reopening this based on smart feedback from @testforstephen 

1. Purple no folder vscode
2. Open pom.xml file
3. No recommendation 🐛 

I think this flow is very important for new users that are trying to open java projects and can easily end up opening `pom.xml` in an empty folder.
There is only a recommendation if VS Code is opened in the folder and `pom.xml` lives top level.

**Comment by sandy081** [comment]
@isidorn What is expected when users opens pom.xml file in empty window? How does it help user seeing java extension recommendation and installing it? Is not the first action user has to do is opening the folder?

**Comment by sandy081** [comment]
Just read the linked issue #131894. I do not think showing recommendation when file is opened is a separate issue. IMO it has to implemented along with the complete flow. Add recommendation support with out extension contributing anything might be of no use and confusing. I would suggest to tract the complete flow and what needs to be implemented in the same issue. If agreed I would like to close this.

**Comment by isidorn** [comment]
Sure we can track this in the other issue if that makes more sense to you. Thus closing this one
