### ISSUE TITLE
Can't install update 1.59.1

### ISSUE THREAD

**Issue by nienn** [microsoft/vscode#131881]
Issue Type: <b>Bug</b>

I always updated before without any problems. Now it just does not update. There aren't any errors.

I have VSCode installed in Windows 10 and in WSL.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3311)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (2.76GB free)|
|Process Argv|--crash-reporter-id 751d1688-a0cf-4aca-9398-eeb31d35c701|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.3.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
docker-explorer|for|0.1.7
vscode-docker|ms-|1.16.0
remote-containers|ms-|0.187.1
remote-wsl|ms-|0.58.2
code-spell-checker|str|1.10.2
quokka-vscode|Wal|1.0.395
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by TarunavBA** [comment]
You can try _reinstalling_ vscode! 😃

**Comment by joaomoreno** [comment]
> You can try _reinstalling_ vscode! 😃

Can you try this?

**Comment by TarunavBA** [comment]
Hey @joaomoreno what I meant to say is that when you go to https://code.visualstudio.com/ and download it again it will automatically install the newer version! 🤷‍♂️ 

**Note: you should first uninstall Vscode.**

**Comment by nienn** [comment]
> You can try _reinstalling_ vscode! 😃

This worked for now. Thanks!

**Comment by TarunavBA** [comment]
@nienn It's ok! 😃

**Comment by nienn** [comment]
Its still not updating. Now trying to update to **1.60.1**.
I'm sure that if I reinstall **Vscode** it will be updated to version **1.60.1**, but that's not really practical for each new version.
Any ideas about what in my specific setup might be causing this?

**Comment by TarunavBA** [comment]
@nienn Try removing the `vscode` folder in `AppData` and reinstall VSCode. Let me know if the problem persists for the next release of VSCode also.

**Comment by nienn** [comment]
Hi @TarunavBA, sorry for the delay.

What folder do you mean? I've searched through `C:\Users\{USER}\AppData` folder and sub-folders and can find no folder named `vscode`. The only I've found was `C:\Users\{USER}\.vscode` which has the extensions information. Is this the one?

**Comment by TarunavBA** [comment]
Yes @nienn you can try that or if that doesn't work you can delete all the `.vscode` folders
