### ISSUE TITLE
TreeItem is not expanded after setting vscode.TreeItemCollapsibleState.Expanded

### ISSUE THREAD

**Issue by swatDong** [microsoft/vscode#131955]
I'm developing my own extension. One scenario is to add a child TreeItem and expand its parent on user's command.
I'm trying to achieve this behavior via set `TreeItem.collapsibleState = TreeItemCollapsibleState.Expanded`, but it's not expanded.

Here's the sample code of TreeDataProvider (calling `funcExpand` to add child and expand the parent), and I've also created a sample extension with full code (https://github.com/swatDong/one-extension/tree/treeviewexpand):
``` typescript
import * as vscode from 'vscode';

class TreeDataProvider implements vscode.TreeDataProvider<vscode.TreeItem> {
    private _onDidChangeTreeData: vscode.EventEmitter<vscode.TreeItem | undefined | void> = new vscode.EventEmitter<vscode.TreeItem | undefined | void>();
    readonly onDidChangeTreeData: vscode.Event<vscode.TreeItem | undefined | void> = this._onDidChangeTreeData.event;

    private parent: vscode.TreeItem = new vscode.TreeItem("Tree Item A (Parent)");
    private child: vscode.TreeItem = new vscode.TreeItem("Tree Item AA (Child)");

    private showChild: boolean = false;

    constructor() {
    }

    getTreeItem(element: vscode.TreeItem): vscode.TreeItem | Thenable<vscode.TreeItem> {
        return element;
    }

    getChildren(element?: vscode.TreeItem | undefined): vscode.ProviderResult<vscode.TreeItem[]> {
        if (element === undefined) {
            // The root, always return parent
            return [this.parent];
        } else if (this.showChild) {
            // Not root, return child if showChild
            return [this.child];
        } else {
            // Not root and child is hidden
            return [];
        }
    }

    funcExpand() {
        this.parent.collapsibleState = vscode.TreeItemCollapsibleState.Expanded;
        this.showChild = true;
        this._onDidChangeTreeData.fire();
    }
}
```

For example, the initial tree view looks like:
![image](https://user-images.githubusercontent.com/7642967/131444364-7ea5d1cb-89cd-45fd-af5d-cc3b5f09fc65.png)

Then after user's command, it turns to be:
![image](https://user-images.githubusercontent.com/7642967/131444689-fe947058-47d3-4b43-b4ef-9fa70fff29db.png)

But what my expectation is to expand the parent node:
![image](https://user-images.githubusercontent.com/7642967/131444775-c16985af-8a27-4c40-8a13-991d84be0c7c.png)

Does this issue occur when all extensions are disabled?: Yes/No
(Occur when all other extensions are disabled and only my sample one is active)

- VS Code Version: 1.59.1 (user setup)
- OS Version: Windows_NT x64 10.0.19043
```
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by alexr00** [comment]
@swatDong this is as designed. To show a collapsed tree item, please checkout the `reveal` API:

https://github.com/microsoft/vscode/blob/c4546485f006e5676ddb3221e1b4d98a651c0d6d/src/vs/vscode.d.ts#L9257-L9270
