### ISSUE TITLE
CustomExecution tasks get stuck when run to quickly

### ISSUE THREAD

**Issue by award999** [microsoft/vscode#131926]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: macOS 11.4

Steps to Reproduce:
The issue tracked by #114177 is still occurring in July release and Insiders. It is not as prevalent as it once was but still happens. Our extension starts up some tasks to initialize the workspace. If we don't put a 500ms pause between starting each task then it hangs from time to time.

**Comment by alexr00** [comment]
@award999 did the issue go away and then come back, or has it always been sporadic for you?

**Comment by award999** [comment]
We've seen this since 1.54. This was still reproducible with 1.58 and 1.59. The hang itself is sporadic, may not see it for a day, may see it on 3 subsequent launches of VSCode. Task never continues either, forcing a restart of VSCode.
