### ISSUE TITLE
debug configuration dropdown in visual studio code

### ISSUE THREAD

**Issue by Nikki942** [microsoft/vscode#131901]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.59.1(user setup)
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Open Visual studio code.
2. Press F5 key for selecting a debug configuration.

Hello experts!
I was exploring Visual studio code 1.59.1 and I pressed f5 key for selecting the debug configuration by mistake. The dropdown doesn't go from the screen if I click anywhere on the screen unless I press escape unlike other dropdowns(like command palette).Is there any reason for it that I may not know about? I am new to VSC.

Please help!
Thanks in advance!

**Comment by weinand** [comment]
I cannot reproduce this on Windows.
Could you please provide a screenshot showing the dropdown menu.

**Comment by Nikki942** [comment]
Hello Sir!
Figure 1: Normal VSC screen.
Figure 2: I pressed F5 key
This suggestion list for selecting debug configuration doesn't go even after clicking anywhere on the screen except escape button unlike Command prompt suggestion list. So, Is there any reason for it? only this was my doubt
![Screenshot (96)](https://user-images.githubusercontent.com/81428616/131358749-50daaf4e-d837-423c-9c30-11d15b023900.png)
![Screenshot (97)](https://user-images.githubusercontent.com/81428616/131358851-ed02b613-ed5b-4144-ae2f-6d7cc69595e6.png)
Thank you!

**Comment by weinand** [comment]
/extPython

In plain VS Code pressing "F5" does not result in the debug configuration dropdown (aka QuickPick) what you are seeing. So I'm speculating that what you are seeing is an issue with one of your installed extensions.

I suggest that you disable your extensions one by one to find the culprit.
