### ISSUE TITLE
Add "stage this hunk" quick action to the diff view

### ISSUE THREAD

**Issue by detzt** [microsoft/vscode#131970]
I would like to stage individual hunks from the diff viewer quicker than selecting the text within, opening the context menu, and pressing "stage selected ranges".

Clicking the gutter indicators in the normal editor window opens an inline diff viewer with buttons to stage / revert this hunk. How about opening a reduced context menu containing only "Stage this change" and "Revert this change" upon clicking the gutter in the diff viewer? (For an already staged change, it should of course be replaced with "Unstage this change".)

See also this idea of @rijk https://github.com/microsoft/vscode/issues/3562#issuecomment-612415850 to collapse the unchanged regions in between and add the quick action buttons to that area.

**Comment by crackwitz** [comment]
The diff view already has a "revert" button, which I use *a lot less often* than "stage hunk". That is the ideal place for the proposed feature.

![image](https://user-images.githubusercontent.com/7065108/211799204-618c5314-ed15-4243-81fc-04f81ff5ea05.png)

Staging should be the **default** for whatever button goes there.

Other diff tools and Git GUIs offer this, some even sensitive to a modifier key, e.g. shift key to change direction of "push".

If you can, model the behavior after SmartGit (which even lets you text-edit the stage, which I _really really_ want in VSCode). [SmartGit's changelog](https://www.syntevo.com/smartgit/whats-new/) has some screenshots that show their diff views.  One can choose to remove or copy insertions/deletions symmetrically (see 22.1 screenshots). One can choose to push changes in either direction (see 21.1 screenshots).

That type of diff view isn't unique to SmartGit. Meld does it too.

![image](https://user-images.githubusercontent.com/7065108/211799793-2ff28d59-7d61-4c87-ab9f-bc9541265f9a.png)

**Comment by Devourian** [comment]
Great idea, but I think PyCharm does it the best having a checkbox that one can use to easily stage or unstage a hunk. 
If it was implemented in VSCode in the same manner it would be great 🚀 

![image](https://github.com/microsoft/vscode/assets/96141879/05c39e55-2f25-40ed-8f7e-e3cbfa54f156)

**Comment by rijk** [comment]
What I find is especially important for me, is in the inline view to have the option to hide staged code. This way I can go through all the changes and stage every hunk, until all that's left are `console.log`s etc, or changes meant for a different commit.

Not sure if that's relevant for this feature though.

**Comment by hediet** [comment]
I'm glad you enjoy the feature! :)
