### ISSUE TITLE
Editor becomes unusuably slow

### ISSUE THREAD

**Issue by chkn** [microsoft/vscode#131979]
Issue Type: <b>Bug</b>

I'm editing an F# script (fsx) file that includes literate markdown as described at https://fsprojects.github.io/FSharp.Formatting/literate.html with the Ionide F# extension enabled.

I'm not adding any line breaks to the markdown paragraphs and instead enabling Word Wrap from the View menu. After a couple minutes of editing, the editor becomes so slow to type or even move the cursor that it is unusable. ~~Turning off Word Wrap seems to fix it.~~

Note: I don't think this is a dupe of #117106 because the file is very small (651 bytes)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|16.00GB (2.57GB free)|
|Process Argv|--crash-reporter-id 6b5fd6a5-e318-4060-9a7a-b9987724cccf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.0.4
Ionide-fsharp|Ion|5.7.1
csharp|ms-|1.23.14
dotnet-interactive-vscode|ms-|1.0.2409020
vscode-dotnet-runtime|ms-|1.2.0
vscode-dotnet-sdk|ms-|0.7.0
jupyter|ms-|2021.8.1236758218
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
mono-debug|ms-|0.16.2
LiveServer|rit|5.6.1
llvm|RRe|0.1.1
vscode-il|sol|0.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
javagetstartedc:30351792
vsdyn478:30356813
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by chkn** [comment]
Update: turning off Word Wrap did seem to improve things for a second, but then they started slowing down again. Perhaps it's related to having very long lines

**Comment by TylerLeonhardt** [comment]
@chkn can you try running extension bisect? I'd like to understand if this issue is caused by an extension:
https://code.visualstudio.com/blogs/2021/02/16/extension-bisect
