### ISSUE TITLE
Format on paste doesn't fix indentation tabs/spaces

### ISSUE THREAD

**Issue by ygoe** [microsoft/vscode#131990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.1
- OS Version: Windows 10

Steps to Reproduce:

1. Enable the format on paste setting and indent with tabs (not spaces)
2. Open a Python documents with spaces for indentation (install all suggested extensions for Python)
3. Create a new document with tabs for indentation, add some content
4. Copy multiple indented lines from the old document
5. Paste into the new document (install all suggested extensions, repeat steps if necessary)

The pasted code is formatted if necessary, but still has spaces at the beginning of the line. Next I get an error that the indentation is inconsistent. This is only obvious when selecting the lines to see the spaces instead of tabs (whitespace characters are invisible by default, and should be).

IIRC in Visual Studio, pasted code is also adjusted for the current indentation style. VS Code doesn't do that.

**Comment by TylerLeonhardt** [comment]
I feel like this is a Python extension issue since they provide the formatting.

/extPython
