### ISSUE TITLE
cannot paste more than 2 lines into ipython in integrated terminal

### ISSUE THREAD

**Issue by patrickrmaia** [microsoft/vscode#131983]
Does this issue occur when all extensions are disabled?: **Yes**

I'm having the exactly problem described in this old issue (#79251) but running a newer version of VS Code.

- VS Code Version: 1.59.1 (user setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. `$ code --disable-extensions`
2. in integrated terminal, type ipython and hit Enter to start ipython
3. type within **editor window:**
  ````
   for name in ('foo', 'bar'):
       print(len(name))
       print(name)
  ````

4. Select all three lines, copy, and paste into the ipython. Result is:

```
In [3]: for name in ('foo', 'bar'):
   ...:         print(len(name))
   ...:             print(name)
  File "<ipython-input-3-558a771c8ff0>", line 3
    print(name)
    ^
IndentationError: unexpected indent
```

Same result if step 4 is Terminal: run selected text in active terminal instead of copy-paste.

For reference, here is the result of the same copy-paste in a system terminal (which is what used to happen in integrated terminal):
![image](https://user-images.githubusercontent.com/23424945/131532520-922f0891-05ac-461e-ad36-cb7036282556.png)

**Comment by Tyriar** [comment]
Does this also happen in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)? We share the backend (conpty) with them.
