### ISSUE TITLE
UI render Bug

### ISSUE THREAD

**Issue by knownothingsnow** [Microsoft/vscode#13192]
- VSCode Version:1.5.3
- OS Version: mac OS 10.12

Steps to Reproduce:

1. open a folder or some files in editor.
2. move window to external display, and toggle to full screen.
3. Unplug your Display port video line and switch to another external display with different resolution，e.g. 2K to 1080p.And editor show some strange shadow blocks.
![2016-10-04 15 15 48](https://cloud.githubusercontent.com/assets/9696289/19065432/14e9f076-8a46-11e6-8ea1-86a8b4b93c7e.png)
![2016-10-04 15 16 08](https://cloud.githubusercontent.com/assets/9696289/19065441/22003e3c-8a46-11e6-96ba-110cbcfe7692.png)
![2016-10-04 15 23 04](https://cloud.githubusercontent.com/assets/9696289/19065500/7d284318-8a46-11e6-83e0-1861d554630a.png)

As you see, once the UI bug shows up , it will not dismiss when I change my color theme or window size.I often use different resolution display in my office and home. So this bug is quite a confusion to me

**Comment by mrmlnc** [comment]
See https://github.com/Microsoft/vscode/issues/12473

**Comment by knownothingsnow** [comment]
@mrmlnc Thank you!
