### ISSUE TITLE
Ctrl+H in interactive window input box results in warning popup

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#131996]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Jupyter: Create Interactive Window
2. Place cursor in input box, hit Ctrl+H 
2. 🐛 Popup appears with message 'cannot read property replace of null'

![image](https://user-images.githubusercontent.com/30305945/131549113-b8c61b5d-3653-4ed4-a373-65fb1949e94b.png)

**Comment by joyceerhl** [comment]
Ctrl+F causes a 'cannot read property show of null' message.

**Comment by zalberts** [comment]
Close duplicate in vscode-jupyter linked above - same problem with ctrl+f as @joyceerhl  mentioned above.
