### ISSUE TITLE
Submit a bug link not working for Edge

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vscode#13195]
I clicked submit a bug and got the following link in Edge which literally output just # on the screen.

https://github.com/microsoft/vscode/issues/new?body=-+VSCode+Version%3a+Code+-+Insiders+1.6.0-insider+(17b0c8d028d3b7ceaf3b7c2c226cd0ad6b1feb51%2c+2016-09-30T06%3a10%3a50.521Z)%0a-+OS+Version%3a+Windows_NT+ia32+10.0.14393%0a-+Extensions%3a+%60dbaeumer.vscode-eslint-1.0.7%60%2c+%60donjayamanne.githistory-0.0.12%60%2c+%60ms-vscode.csharp-1.4.1%60%2c+%60ms-vscode.PowerShell-0.7.2%60%2c+%60ow.vscode-subword-navigation-1.1.5%60%2c+%60rebornix.Ruby-0.8.0%60%2c+%60WallabyJs.wallaby-vscode-1.0.27%60%0a%0aSteps+to+Reproduce%3a%0a%0a1.%0a2.

**Comment by massimocode** [comment]
Clicking the above link works, so it might be an Edge issue.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13098
