### ISSUE TITLE
Unable to fit window to screen using option-click on green traffic light button in MacOS

### ISSUE THREAD

**Issue by rmnprb** [microsoft/vscode#131969]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. While holding down the option key click on the green traffic light button
2. The window will enter fullscreen while default MacOS behavior is to resize the window to fit the screen

As expected pressing the option key while hovering over the green traffic light button will change its icon from the fullscreen icon to the + icon indicating pressing it should resize the window to fit the screen.

**Comment by sbatten** [comment]
must be upstream, we do not implement traffic lights

**Comment by deepak1556** [comment]
Unable to repro with latest stable on macOS ventura.
