### ISSUE TITLE
How to debug vscode source code for one specific feature?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1319]
I have followed the instruction from page https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source to try to debug vscode source,  But i have not found how to debug a specific feature such as Intellisense feature ,now  i want to set breakpoint for "update" method in \vscode\src\vs\editor\contrib\suggest\browser\suggest.ts ,but i don't know how to trigger this method ,anyone can tell me the detail steps?

**Comment by BleyChen** [comment]
I just want to know the whole process of show suggestion Intellisense in vscode, such as when you write js in vscode ,it will popup completionlist for you, I want to know the whole process of this, anyone can tell me how to run the vscode source code and debug for this feature?

**Comment by egamma** [comment]
Please refer to the debugging section in https://github.com/Microsoft/vscode/wiki/How-to-Contribute#development-workflow. The suggest supports runs in the` renderer` process so you use the Chrome Dev tools to debug this code.

@chrisdias fyi, should we improve this section of the doc?

**Comment by BleyChen** [comment]
@egamma , I agree with you to provide more detail about debug steps, maybe you can put an sample for us or provide an video to tell us how to debug it ,thank you!
