### ISSUE TITLE
Notebook files are not saved with an extra new line

### ISSUE THREAD

**Issue by bohni** [microsoft/vscode#131991]
## Environment data

-   VS Code version: 1.55.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Python and/or Anaconda version: 2.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

Text files should be saved with posix lines

See https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
![image](https://user-images.githubusercontent.com/1252254/113829021-4e989880-9785-11eb-9687-b89396e0c3f8.png)

## Actual behaviour

The last line of a ipynb file is missing the \<newline> character.

## Steps to reproduce:

1. Use a text editor (or plain text editor in VS Code) to edit a ipynb file, adding a \<newline> character in last line
   ![image](https://user-images.githubusercontent.com/1252254/113828424-a71b6600-9784-11eb-9c01-78d4140b3a54.png)
2. Open the file in VS Code with the jupiter editor and save it
3. The last line is missing the \<newline> character
   ![image](https://user-images.githubusercontent.com/1252254/113828869-25780800-9785-11eb-9de0-199afd64786d.png)

**Comment by dhimmel** [comment]
@rebornix can you take a look before @vscode-triage-bot closes this issue and discards the efforts @bohni and I have done to report this issue?

**Comment by DonJayamanne** [comment]
This issue has been open for over 2 years and we haven't had enough votes on this, hence closing this for now.

**Comment by dhimmel** [comment]
> DonJayamanne closed this as completed

@DonJayamanne it would be more appropriate to close this issue as "not planned" rather than "completed". You can still change the label via

> ![image](https://github.com/microsoft/vscode/assets/1117703/e92e88a8-792f-4f3c-84ff-e1014dac0e12)
