### ISSUE TITLE
Show notification with disabling search.symlinks option.

### ISSUE THREAD

**Issue by kubakrupski** [microsoft/vscode#131900]
When searching takes a long time + option "search.followSymlinks" = true,  show gentle notification with an option to disable the mentioned option, which improves the search speed and stops consuming CPU resources. 

Connected with https://github.com/microsoft/vscode/issues/98594

**Comment by roblourens** [comment]
I don't want to do this, because having lots of symlinks in your repo is not something that actually comes up that often. I don't like popping up random "tip" notifications in front of users who probably don't need it.
