### ISSUE TITLE
Jupyter notebook creation, extension loading, and execution is slow 

### ISSUE THREAD

**Issue by ad12** [microsoft/vscode#131930]
Issue Type: <b>Bug</b>

The notebook creation and execution steps seem to have slowed down in Jupyter recently. Adding steps to reproduce below:

1. Right click on Folder -> New File -> demo.ipynb (takes ~12-15min)
2. Type `print("hello world")`
3. Click on Run or press Shift+Enter (takes 8-10 min)

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-59-generic
Fetching remote diagnostics for 'SSH: torino' failed: Canceled
Remote OS version: Linux x64 5.8.0-63-generic
Fetching remote diagnostics for 'SSH: stelvio' failed: Canceled
Remote OS version: Linux x64 5.4.104+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 7|
|Memory (System)|32.00GB (6.44GB free)|
|Process Argv|--crash-reporter-id 1572910a-3d68-41d5-8b2d-a8224b00f95b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: torino|
|OS|Linux x64 5.8.0-59-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (32 x 2056)|
|Memory (System)|125.80GB (0.88GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: torino' failed: Canceled

|Item|Value|
|---|---|
|Remote|SSH: stelvio|
|OS|Linux x64 5.8.0-63-generic|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 4408)|
|Memory (System)|125.50GB (25.28GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: stelvio' failed: Canceled

|Item|Value|
|---|---|
|Remote|io-pod in io-pod (gcr.io/hai-gcp-mri/mtr-img)|
|OS|Linux x64 5.4.104+|
|CPUs|Intel(R) Xeon(R) CPU (60 x 3100)|
|Memory (System)|236.15GB (227.53GB free)|
|VM|0%|
</details>

**Comment by greazer** [comment]
Creating an empty ipynb file is done by the core code.

**Comment by ad12** [comment]
@greazer the "Connecting to kernel" step also seems to hang for about 8-10 minutes on the remote machine before connecting. below are some of the logs.

```bash
Info 2021-08-31 05:50:35: Kernel python3810jvsc74a57bd017efa7ee1d6afd524561ec9e18042ff0cbeae9ae3c81d8dde584139922230b01 matches Python 3.8.10 64-bit ('mtr_env': conda) based on path in argv.
Info 2021-08-31 05:51:17: Process Execution: > /home/common/miniconda3/envs/mtr_env/bin/python -m pip list
> /home/common/miniconda3/envs/mtr_env/bin/python -m pip list
Info 2021-08-31 05:51:17: Process Execution: > /home/common/miniconda3/envs/mtr_env/bin/python -c "import notebook"
> /home/common/miniconda3/envs/mtr_env/bin/python -c "import notebook"
Info 2021-08-31 05:51:17: Process Execution: > /home/common/miniconda3/envs/mtr_env/bin/python -c "import jupyter"
> /home/common/miniconda3/envs/mtr_env/bin/python -c "import jupyter"
Info 2021-08-31 05:51:18: Process Execution: > /home/common/miniconda3/envs/mtr_env/bin/python -c "import ipykernel"
> /home/common/miniconda3/envs/mtr_env/bin/python -c "import ipykernel"
Info 2021-08-31 05:51:18: Install Missing Dependencies, Class name = E, completed in 226006ms, has a falsy return value, Return Value: undefined
Info 2021-08-31 05:51:18: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 2021-08-31 05:51:18: Launching kernel daemon for Python 3.8.10 64-bit ('mtr_env': conda) # /home/common/miniconda3/envs/mtr_env/bin/python
```

**Comment by roblourens** [comment]
Sorry for the late response, does this still happen? Can you tell me more about what you see when you try to create a file and it takes so long, for example, are you looking at a loading notebook editor with a progress bar for 12-15 minutes?
