### ISSUE TITLE
Support emoji IMEs in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#131921]
Right now the Windows emoji IME (win+.) seems to work fine but the macOS one does not (ctrl+cmd+space).

Upstream: https://github.com/xtermjs/xterm.js/issues/469

Related https://github.com/microsoft/vscode/issues/35266

**Comment by bobby169** [comment]
🤩 great work! 🥳

**Comment by bobby169** [comment]
🤩 great work! 🥳
