### ISSUE TITLE
Improve keyboard shortcuts for switching between Command Palette and Go To File

### ISSUE THREAD

**Issue by nnnnicholas** [microsoft/vscode#131997]
**Problem**: User intends to invoke the Command Palette (ctrl + shift + p) but accidentally invokes Go to file (ctrl + p). To switch to the Command Palette, the user must either manually enter `> `  into the Go to file input _or_ hit Esc and start from scratch.

**Behavior**: Pressing ctrl + shift + p while in the Go to file query input has no effect.

**Expected behavior**: Pressing ctrl + shift + p while in the Go to file query input should add `> ` to the input, thus switching the input to the  Command Palette behavior in place of file search.

VSCode UX would benefit significantly from keyboard shortcut symmetry between Command Palette invocation and Go to file invocation. 

At present it is only possible to go from the Command Palette to the Go to file search. If the user presses ctrl + shift + p then ctrl + p, VSCode removes the `>` so the user can begin searching their files. The inverse scenario is not currently enabled by the software. This would be a simple fix that would make the interface more logically coherent and quicker to use as a programmer.

**Comment by heartacker** [comment]
indeed
