### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by soheil56** [microsoft/vscode#131965]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Command "code -runner.run" not found

**Comment by CodeCrazy-ywt** [comment]
> Command "code -runner.run" not found

What you input is not a valid command. This is what I got when I input this command:
```
Warning: 'u' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
```
