### ISSUE TITLE
vscode/flutter cannot find imports without reset

### ISSUE THREAD

**Issue by bksubhuti** [microsoft/vscode#131949]
idk

- VS Code Version:
- OS Version:

ubuntu 21.04
vscode 1.59.1

I need to reload vscode in order for the errors to stop showing.  The variables are not found in the import until I reset the vscode.  This disturbs issues with hot reload and is annoying anyway.  I think I have only standard plugins from flutter.
![deleteme](https://user-images.githubusercontent.com/18184280/131423892-c7db0a6a-5f7d-410e-a862-0af55ec84649.png)

**Comment by TylerLeonhardt** [comment]
Looks like the extension is here:
https://github.com/Dart-Code/Flutter
