### ISSUE TITLE
Ability to copy link directly to markdown preview

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#131964]
1. https://github.dev/microsoft/vscode-docs/tree/vnext
2. Open some markdown preview
3. I can copy the link to open the markdown file, however I can not copy a link directly to the markdown preview

My use case: I am using `github.dev` for writing notes, and when I share these notes with people to read I want them to be directly in the markdown preview.

fyi @bpasero

![Screenshot 2021-08-31 at 12 07 07](https://user-images.githubusercontent.com/1926584/131484262-7100e438-1396-4c18-b332-da3d278b069d.png)

**Comment by mjbvz** [comment]
Just to make sure I understand, you'd like to be able to right click on the preview  tab and copy a link to `GitHub.dev` that will open the file in preview mode?

That may be possible using our custom editors, but we'd have to make sure the copied link contains the editor id

**Comment by isidorn** [comment]
Exactly. But I do not want it to be open side-by-side. I just want the preview open.
