### ISSUE TITLE
Selected item from suggestions widget is truncated when displayed as gray text

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#131942]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19043
- List of extensions: None, all are disabled

Steps to Reproduce:

1. Create a new typescript file.
2. Type `fun`, the suggestions widget opens and the first suggestion is `function`. 
3. The gray text however, only shows `functio`, it's missing the last character. 
4. I've attached a gif. Notice how when I type `fu`, the gray text displays `function` but when I type `fun`, it shows `functio`. 
![completionsDrivenBug3](https://user-images.githubusercontent.com/86270736/131416327-c597e813-0cfe-4ab2-b0c6-651bb1849e2c.gif)

**Comment by juihanamshet1** [comment]
@hediet

**Comment by hediet** [comment]
@juihanamshet1 can you please verify todays insider build fixes this?

**Comment by juihanamshet1** [comment]
@hediet Yes, it has been fixed!
