### ISSUE TITLE
regex replace should preview what the replacement will be

### ISSUE THREAD

**Issue by theodore-wilson-amd** [microsoft/vscode#131993]
VisualSlickEdit provides a preview of what a regex replacement will place on each match.  This is very handy letting you correct the regex or skip matches avoiding mistakes.  It would be very handy for VsCode to provide a preview of what a search/replace will place at each match.

**Comment by JacksonKearl** [comment]
I believe we do already support this:
![image](https://user-images.githubusercontent.com/8586769/132437396-9e11a9f9-8cc1-4639-81dd-3d939675f4d2.png)
do you see something different?

**Comment by theodore-wilson-amd** [comment]
Thank you for your attention Jackson!

A search and replace in a single file does not show the red/green content..
I only see an orange match to the regex.

search for gl(\d)
replace with gl$1$1

leaves the file highlighted as below... no preview of what is about to
happen.  Could this be a setting for my copy of VsCode I wonder?

-e 'run_test "gl1/sanity -v"' \
-e 'run_test "ch/sanity -v"' \
...

**Comment by ShadowMitia** [comment]
I've had the same issue.
There is indeed a preview inside "Replace in Files" but there is no preview in "Replace in File".

See here

![image](https://user-images.githubusercontent.com/3752363/143787153-cd382753-df76-4c2a-8724-2a753dae1752.png)

**Comment by ShadowMitia** [comment]
Previewing would there would be nice, and some kind of previewing inside the file would be great!
