### ISSUE TITLE
On iMac, Visual Code comes up blank

### ISSUE THREAD

**Issue by ayrtonsoftware** [microsoft/vscode#131943]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.59.1
- OS Version: 12.0

Steps to Reproduce:

1. Run "$ Code"
2. or Run "$ Code . --disable-gpu"

Nothing works

I have the same blank problem on a Mac. I have tried the --disable-gpu and it still does not work. v1.59.1

[main 2021-08-30T22:46:25.751Z] Starting VS Code
[main 2021-08-30T22:46:25.752Z] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 2021-08-30T22:46:25.752Z] args: {
_: [ '/Users/*' ],
diff: false,
add: false,
goto: false,
'new-window': false,
'reuse-window': false,
wait: false,
help: false,
'list-extensions': false,
'show-versions': false,
version: false,
verbose: true,
status: false,
'prof-startup': false,
'no-cached-data': false,
'prof-v8-extensions': false,
'disable-extensions': false,
'disable-gpu': true,
telemetry: false,
debugRenderer: false,
logExtensionHostCommunication: false,
'skip-release-notes': false,
'skip-welcome': false,
'disable-telemetry': false,
'disable-updates': false,
'disable-keytar': false,
'disable-workspace-trust': false,
'disable-crash-reporter': false,
'crash-reporter-id': '34efb1fa-a3bc-4cf3-a964-d86a075ab4d2',
'skip-add-to-recently-opened': false,
'unity-launch': false,
'open-url': false,
'file-write': false,
'file-chmod': false,
'driver-verbose': false,
force: false,
'do-not-sync': false,
trace: false,
'force-user-env': false,
'force-disable-user-env': false,
'open-devtools': false,
__sandbox: false,
'no-proxy-server': false,
'no-sandbox': false,
nolazy: false,
'force-renderer-accessibility': false,
'ignore-certificate-errors': false,
'allow-insecure-localhost': false,
logsPath: '/Users//Library/Application Support/Code/logs/20210830T154625'
}
[main 2021-08-30T22:46:25.754Z] Resolving machine identifier...
[main 2021-08-30T22:46:25.754Z] Resolved machine identifier: ***
[main 2021-08-30T22:46:25.754Z] Main->SharedProcess#connect
[1774:0830/154625.828549:WARNING:address_sorter_posix.cc(388)] FromSockAddr failed on netmask
[1770:0830/154627.771704:ERROR:service_worker_storage.cc(1895)] Failed to delete the database: Database IO error
[main 2021-08-30T22:46:31.282Z] StorageMainService: creating global storage
[main 2021-08-30T22:46:31.283Z] lifecycle (main): phase changed (value: 2)
[main 2021-08-30T22:46:31.284Z] windowsManager#open
[main 2021-08-30T22:46:31.284Z] windowsManager#open pathsToOpen [
{
workspace: { id: '28529e1601eef3243e719cc031231060', uri: [v] },
exists: true
}
]
[main 2021-08-30T22:46:31.285Z] IPC Object URL: Registered new channel vscode:e6cec54a-3fc0-49ae-9458-6352328f8a25.
[main 2021-08-30T22:46:31.285Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 683, y: 205, width: 1654, height: 1036 }
[main 2021-08-30T22:46:31.285Z] window#validateWindowState: 1 monitor working area { x: 0, y: 25, width: 2560, height: 1324 }
[main 2021-08-30T22:46:31.286Z] window#ctor: using window state { mode: 1, x: 683, y: 205, width: 1654, height: 1036 }
[main 2021-08-30T22:46:31.286Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-30T22:46:31.362Z] StorageMainService: creating workspace storage (28529e1601eef3243e719cc031231060)
[main 2021-08-30T22:46:31.362Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2021-08-30T22:46:31.377Z] lifecycle (main): phase changed (value: 3)
[main 2021-08-30T22:46:31.380Z] update#setState idle
[main 2021-08-30T22:46:31.380Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2021-08-30T22:46:31.555Z] resolveShellEnv(): skipped (VSCODE_CLI is set)

**Comment by deepak1556** [comment]
Are you able to open chrome or edge browser on the same system ?

**Comment by ayrtonsoftware** [comment]
The OS Version is 12.0

**Comment by ayrtonsoftware** [comment]
@deepak1556 Yes, I am able to run the Chrome browser without any issues.
