### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/vscode#131960]
Why don't we add a glassy look by default?

**Comment by CodeCrazy-ywt** [comment]
Hey, you can install an extension to have a galssy look. In addition, the glassy look seems to be on the way (see #115641).

**Comment by TarunavBA** [comment]
Oh ok @CodeCrazy-ywt but it would be better if we can get the glass ui without any extension! Maybe we can release it with the next major release of VSCode! 😀

**Comment by misolori** [comment]
Thanks for the feedback, we've had lots of issues related to this so will be closing this one. Please see https://github.com/microsoft/vscode/issues/26572 https://github.com/microsoft/vscode/issues/12578 https://github.com/microsoft/vscode/pull/52707
