### ISSUE TITLE
Font Aliasing Config Setting for Windows

### ISSUE THREAD

**Issue by PBI-David** [microsoft/vscode#131928]
Could we get a config setting for Windows like the one implemented for Mac here: https://github.com/Microsoft/vscode/issues/2577

On my Windows install, I have all aliasing disabled but this is not honoured by VS Code and so I have blurry fonts which I find give me a headache. I have looked all over and see others reporting the same issue but no fix.

**Comment by bpasero** [comment]
The way it is implemented in VSCode, we use the `font-smooth` CSS property which only is supported on macOS: https://caniuse.com/?search=font-smooth

So we cannot support this currently on Windows or Linux.

**Comment by PBI-David** [comment]
Disappointing to hear but thanks for confirming.
