### ISSUE TITLE
Copying markdown from vscode results in nonbreaking spaces between words, breaking word wrap behavior in destination applications

### ISSUE THREAD

**Issue by KRyan** [microsoft/vscode#131922]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0 
- OS Version: Windows Version	10.0.19043 Build 19043

Steps to Reproduce:

1. Create a new file in vscode and type a sentence
![image](https://user-images.githubusercontent.com/181584/131379761-a2fac837-029c-45ac-b69c-c3d2dd11f31f.png)

2. Save it as an md file.  

3. Select and copy the content you just typed.

4. Open up Outlook on the web or Microsoft Word and paste the content in.  (Word wrapping may already look incorrect)
![image](https://user-images.githubusercontent.com/181584/131379956-d30326fd-206a-4754-9950-6749afdf0afa.png)

5. Now start typing more words in the middle of what you typed and observe how the wrapping behaves. 
![image](https://user-images.githubusercontent.com/181584/131380203-f9682b01-d5b9-4620-80b3-c8dd72855eb9.png)

Expected: normal word wrapping behavior
Actual: unexpected spacing gaps.  This is due to the presence of nonbreaking spaces between all the words. 

Context: we are getting reports of this in the Office Fluid Experiences team, where users are copying content from vscode into Fluid components.  The result looks like a bug in our Fluid editor, but actually it is technically correct wrapping behavior that occurs due to the presence of nonbreaking spaces between every word.  While we could work around this on the Fluid side by converting nbsps to standard whitespace on paste, we believe the right fix is on the copy side in vscode, as this repros in multiple applications.  Please let us know if we can provide more information.

Similar past issue: https://github.com/microsoft/vscode/issues/80825#issuecomment-532672061

**Comment by KRyan** [comment]
@alexdima thanks for the context.  Yes, I would recommend using non-breaking spaces only for consecutive spaces.  I can't speak to what OneNote is doing specifically in that code snippet, but it is HTML standard to collapse successive whitespace, so that would be reasonable parsing behavior.

OneNote, Outlook Web, and the new Fluid Editor copy "Word1    Word2" as "Word1&nbsp; &nbsp; Word2".  Can vscode do the same?  

(I checked Word and OneNote for Windows as well, and they are similar, but seem to prefer nbps in a row in the middle, padded by ordinary whitespace.)

**Comment by rebornix** [comment]
> OneNote, Outlook Web, and the new Fluid Editor copy "Word1    Word2" as "Word1&nbsp; &nbsp; Word2". (nbsp + standard space + nbsp + standard space...) Can vscode do the same?

Rotating nbsp and standard space sounds like a good workaround for preventing whitespace collapse. However currently I can no longer reproduce the issue #35954 in latest OneNote on Windows 10. @alexdima can you also help confirm?

**Comment by KRyan** [comment]
Thank you @alexdima!! I used the Insiders build to confirm the scenario now works as expected!
