### ISSUE TITLE
[scss] Consider custom aliases in module resolution

### ISSUE THREAD

**Issue by HughxDev** [microsoft/vscode#131954]
Please read from `tsconfig`/`jsconfig`’s `compilerOptions.paths`—and perhaps other popular locations such as `webpack.config`’s `resolve.alias`—when providing IntelliSense features to SCSS/Sass files. For instance, if I specify:

**tsconfig.json / jsconfig.json**
```json
{
  "compilerOptions": {
    "paths": {
      "~/*": [
        "src/*"
      ]
    }
  }
}
```

or

**webpack.config.js**
```js
module.exports = {
  resolve: {
    alias: {
      '~': path.resolve( __dirname, 'src' ),
    }
  }
};
```
…then I want to get IntelliSense features for this, such as <kbd>cmd</kbd>-clicking on the underlined import to jump to the relevant file. Currently if I do this, e.g. in:

**src/components/Foo/Foo.scss**
```scss
@import '~/globals';

.foo {
  /* … */
}
```

…VS Code looks for `src/components/Foo/~/globals`, when I want it to look for `src/globals`, as I’ve set it up. (I understand that the tilde character already maps to `node_modules` in Sass, but this is a tilde + a forward slash, and the character could just as easily be `@` or anything else.)

Thank you for your consideration.

**Comment by aeschli** [comment]
The built-in scss support does not load any imports. See https://github.com/microsoft/vscode/issues/100217

The only thing we have is a link on the @import that is aware of the `~` to load from node modules.

How does the tsconfig file impact a scss file? Isn't it only used for TypeScript?

**Comment by HughxDev** [comment]
@aeschli It doesn’t necessarily, but it seems to be VS Code’s intent that `jsconfig`/`tsconfig` are as much for the IDE as they are for the compiler. [From the docs on `jsconfig`](https://code.visualstudio.com/docs/languages/jsconfig#_what-is-jsconfigjson):

> The presence of `jsconfig.json` file in a directory indicates that the directory is the root of a JavaScript Project. The `jsconfig.json` file specifies the root files and the **options for the features provided by the [JavaScript language service](https://github.com/microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio)**.

While [the section on `tsconfig`](https://code.visualstudio.com/docs/typescript/typescript-compiling#_tsconfigjson) doesn’t say exactly the same thing, it stands to reason that it serves a similar function to `jsconfig` but for TypeScript projects.

I only suggest these files because they are already being read by VS Code to modify its behavior. The configuration that actually impacts SCSS files in my workflows is `webpack.config.js`, but I know there are plenty of bundlers out there so maybe VS Code doesn’t want to play favorites, or go down a path of including OOTB support for every bundler.

Specifically, SCSS files are impacted if you use a loader that respects Webpack’s module resolution rules while following Sass imports. This is how [webpack-contrib/sass-loader](https://github.com/webpack-contrib/sass-loader) works, the most popular library for doing this in that ecosystem. For instance if you do this:

**webpack.config.js**
```js
module.exports = {
  resolve: {
    alias: {
      '~': path.resolve( __dirname, 'src' ),
    }
  },
  module: {
    rules: [
      {
        test: /\.(s[ac]ss|css)$/i,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
    ],
  },
}
```

…then doing `@import '~/foo'` will reference `module.exports.resolve.alias` and resolve to `@import '/path/to/src/foo.scss'` (or `/path/to/src/foo/index.scss`, as the case may be), without any Sass-specific configuration. So really the request here is to allow me to tell VS Code to resolve modules the same way as my bundler. Currently there is a disconnect between the two.

**Comment by aeschli** [comment]
`tsconfig.json` is the well-defined way of configuring a TypeScript projects. 
From what I know, for `scss` there's no such standard. Getting the information out of webpack, or any other build script is hard and error prone. We might not understand the full webpack config or build script and we might confuse users with wrong results. That's why I don't think we should go that way. We might fix your use case but get it wrong for others.

And, as said, currently , all that would be good for it to get the link right. We don't do any loading of imports. If we were to do that, I agree this is a problem we would have to solve (e.g. by introducing a scss configuration file).

Closing as out of scope / won't fix.
