### ISSUE TITLE
DEBUG CONSOLE AUTO SCROLL DOWN

### ISSUE THREAD

**Issue by antillgrp** [microsoft/vscode#131999]
DEBUG CONSOLE AUTO SCROLL DOWN

DEBUG CONSOLE AUTO SCROLL DOWN

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide correct description of issue or request

**Comment by lramos15** [comment]
Closing as duplicate of #117674 feel free to correct me if I'm wrong and we can revisit this issue.
