### ISSUE TITLE
Screen flickers and intellisense disappears in Insiders only

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#131935]
Issue Type: <b>Bug</b>

abc

VS Code version: Code - Insiders 1.60.0-insider (6a2daec767703dad42461333fbf8666aa481a32b, 2021-08-27T08:44:34.765Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
kusto|don|0.3.7
brackethighlighter|Dur|2.2.4
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.29.2
todo-tree|Gru|0.0.213
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-bicep|ms-|0.4.613
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.0
vscode-language-pack-de|MS-|1.60.1
csharp|ms-|1.23.14
dotnet-interactive-vscode|ms-|1.0.2423011
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.2031173646
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
azure-account|ms-|0.9.8
powershell|ms-|2021.8.2
vscode-github-issue-notebooks|ms-|0.0.102
azurerm-vscode-tools|msa|0.15.2
vscode-versionlens|pfl|1.0.9
vscode-todo-highlight|way|1.0.4

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824cf:30353184
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgst2:30356659

```

</details>

**Comment by StephenWeatherford** [comment]
This was first reported (I think it's the same issue) here: https://github.com/microsoft/vscode-azurearmtools/issues/1352, saying that the Intellisense result disappear after a couple seconds of being displayed.

I hadn't seen this before, but this morning I saw a bunch of flickering of the screen after making edits, and when the flickers occurred (looked like the screen was redrawing), any open intellisense window would disappear.

Unfortunately it stopped once I reloaded the window.  I have not seen this so far in stable builds.

**Comment by jrieken** [comment]
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by StephenWeatherford** [comment]
Not an extension.  

1) Disable all extensions
2) Install https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools
3) Create new file
4) Copy the following into the file:
```json
{
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"resources": [
{
"type": "Microsoft.AAD/domainServices",
"apiVersion": "2017-01-01"
}
]
}
```
5) Wait until the "Loading ARM Schemas" message disappears (about 1 min)
5) Place cursor at end of apiVersion line
6) press ENTER, then a double quote
7) You should get Intellisense
!) Unexpected: The Intellisense goes away after a second or two

This occurs in 1.60.0-insider e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Does not occur in Version: 1.59.1 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa


https://user-images.githubusercontent.com/6913354/131921274-d8e9cf2b-72c8-463b-9ea1-6d44ab06e64a.mov


https://user-images.githubusercontent.com/6913354/131921282-3d48989d-06d2-4d3d-a33e-e0f6d9c97d81.mov

**Comment by jrieken** [comment]
> Not an extension.

And step 2 says "install extension...". Then please provide repro steps for a built-in extension like JSON, TypeScript, or CSS

**Comment by StephenWeatherford** [comment]
You know what I mean.  However, I've now been able to repro on stable, so trying to narrow down more, but still most likely a vscode issue.
