### ISSUE TITLE
microsoft / vscode-references-view not be localized

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#131974]
https://github.com/microsoft/vscode-references-view/

VSCode-REF-VIEW now has been a builtin extension in vscode.
but now, REF-VEW hasn't be localized, let's to make it support i18n。

FYI:
https://github.com/microsoft/vscode-loc/issues/427
https://github.com/microsoft/vscode-loc/issues/427

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"references-viewlet"
