### ISSUE TITLE
vscode terminal output condensed

### ISSUE THREAD

**Issue by ikoyfman** [microsoft/vscode#131927]
Hello I am currently having an issue with 1.59.1 and my terminal output being very condensed. How would I resolve this?

![image](https://user-images.githubusercontent.com/46546149/131393777-11416dba-a28e-4b1a-b68c-b79669e3438a.png)

![image](https://user-images.githubusercontent.com/46546149/131393843-5341d335-95c2-439e-b984-4ff2396cdb2f.png)

**Comment by meganrogge** [comment]
I'm unable to reproduce this, so please provide me with the steps so I can investigate

**Comment by ikoyfman** [comment]
Hmm I just realized this is the python debug console. Running a django configuration. Different repo?
