### ISSUE TITLE
 [Feature Request] Top level folders in workspace support custom aliases

### ISSUE THREAD

**Issue by jay-zhou-yan** [microsoft/vscode#131951]
Issue Type: <b>Feature Request</b>

We have a usage scenario, in workspace, multiple projects have dependencies, and their folder names are the same, as shown below,
 --- Workspace
		--- trunk
		--- trunk
		--- trunk
		--- trunk
In order to facilitate synchronization with the server, we cannot modify the folder name of the project.  Could you add an alias function to the folder in this workspace (the original folder name cannot be changed), as shown below ?
 --- Workspace
		--- trunk-1
		--- trunk-2
		--- trunk-3
		--- trunk-4

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by bpasero** [comment]
You can add a `name` to any folder in a multi-root workspace file:

![image](https://user-images.githubusercontent.com/900690/131442103-fa5ebd7d-42cb-46ee-be5f-2f490a2c7f99.png)

**Comment by jay-zhou-yan** [comment]
Thanks @bpasero .
Your method solved my problem， I understand this problem can be closed.
