### ISSUE TITLE
Notebook Cell output appended into task is not added, instead a clone seems to be added

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#131913]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Insert a new output into a notebook cell as follows:
```javascript
const task = this.controller.createNotebookCellExecution(cell);
task.start();
const output = new NotebookCellOutput([NotebookCellOutputItem.stdout('1\n')]);
await task.appendOutput(output);
// At this point the number of outputs is `1` (something exists)
console.log(task.cell.outputs.length);
// However the output does not exist
console.log(task.cell.outputs.indexOf(output));

```
2. Looks like an output has been added, but not the one provided by us.
This doesn't seem to work the way the rest of the API works, generally the same object we provide is used.
Use of other API like replaceOutputItems won't work because of this.

@roblourens /cc

**Comment by roblourens** [comment]
Not sure whether the API should guarantee this. Why do you need it? It would be complicated to implement.

**Comment by DonJayamanne** [comment]
Was trying to use the work around you suggested here https://github.com/microsoft/vscode/issues/131123#issuecomment-904057832
Found that using `indexOf` will not work, now I'm resorting to iterating through the outputs and looking for an output with some special metadata (again wish the Id was exposed in stable, feels wrong to have to add my own identifier into the metadata - taht's tracked here https://github.com/microsoft/vscode/issues/130308)

> Not sure whether the API should guarantee this.

I thought it should as `NotebookCells` are guaranteed to be the same, hence I made the same assumption here.
