### ISSUE TITLE
Surface the glob editor for use with settings

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#131972]
Surface the glob editor for use with settings. Built in things that use glob lists get this polished UX

![image](https://user-images.githubusercontent.com/5498936/131503612-b4080d43-99a7-4e71-b576-73bb09873875.png)

My extension has include and exclude glob lists but all I get is a link to the json. The settings experience would be greatly improved by this UI. It's specialised but in extensions to a dev tool dependence on glob lists is hardly even surprising. 

Looking at what this edits, it's an object for which all the properties are strings. I understand why "object" is too hard and you give up and link to the json, but this is a special very constrained case. How about a new type `globs`?

**Comment by IllusionMH** [comment]
Exclude - custom case case of `{[glob: string]: boolean}`.

For most cases `string[]` array should be enough and it's should be already supported see #62440
Coul you use `string[]` instead?

**Comment by roblourens** [comment]
Object settings are also supported. If you post your setting contribution we can help you figure out why it isn't getting a nice renderer

**Comment by ArturoDent** [comment]
This is probably the relevant part for @PeterWone :

> Other types, such as `object` and `array`, aren't exposed directly in the settings UI, and can only be modified by editing the JSON directly. Instead of controls for editing them, users will see a link to `Edit in settings.json` as shown in the screenshot above. 8️⃣

from https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

**Comment by roblourens** [comment]
That is out of date. I will update it right now, thanks for pointing that out @ArturoDent

**Comment by PeterWone** [comment]
I just tried without success on 1.59.0 
```json
          "print.folder.exclude": {
            "default": [
              "bin",
              "obj",
              "**/*.dll",
              "**/*.exe",
              "**/*.pdb",
              "**/*.pdf"
            ],
            "type": "string[]",
            "description": "%print.folder.exclude%"
          },
```

**Comment by roblourens** [comment]
Try this

```json
"print.folder.exclude": {
	"default": [
		"bin",
		"obj",
		"**/*.dll",
		"**/*.exe",
		"**/*.pdb",
		"**/*.pdf"
	],
	"type": "array",
	"items": {
		"type": "string"
	},
	"description": "%print.folder.exclude%"
},
```

**Comment by PeterWone** [comment]
Thanks, Rob.

It's rendering with the UI that I was after but the default didn't work, is some other syntax required for that?

**Comment by roblourens** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/323878/131588226-07f85a47-3417-49f4-a8e5-e928ac86960c.png)

What do you see?

**Comment by PeterWone** [comment]
Empty list. But it worked when I used the UI to add items.

**Comment by PeterWone** [comment]
If it hasn't already been done, an issue is needed for the doc update to reflect this new capability.

**Comment by roblourens** [comment]
I updated the doc, it will be published soon.
