### ISSUE TITLE
intellisense not working

### ISSUE THREAD

**Issue by alanwei0** [Microsoft/vscode#13190]
- VSCode Version: 1.6.0-insider
- OS Version: mac os 10.12

Steps to Reproduce:

1. create a new file
2. set language mode to 'javascript' and save with a name, 'untitle-1.js'
3. input some word, for example: 'webso', there's no suggestion list shown. 
4. close the file and reopen it, input 'webso' again, suggestion is shown, over.
5. i can reproduce it every time.

<img width="336" alt="screen shot 2016-10-04 at 2 43 56 pm" src="https://cloud.githubusercontent.com/assets/3991105/19064628/0d163e36-8a41-11e6-9aa1-6d9b1da7d0d2.png">

**Comment by P3N5K4** [comment]
I've just verified that I get the same issue on:

VSCode Version: 1.5.3
OS Version: Windows 8.1 Enterprise

Setting the Language Mode does not appear to make intellisense available until the file is saved and re-opened.

**Comment by waderyan** [comment]
Thank you for opening this issue. This seems closely related - https://github.com/Microsoft/vscode/issues/13135 (see step 6).

**Comment by waderyan** [comment]
I have reproduced this and believe this is a duplicated of #13135.
