### ISSUE TITLE
Accepting co-pilot autocomplete for a markdown stopped working

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#131953]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. With co-pilot installed create a markdown file
2. Type '## Key take'
3. Try to accept the `aways`

🐛 Tab or space don't work.

![ScreenFlow](https://user-images.githubusercontent.com/8599/131439611-9f34d8a6-12f3-4c72-87be-55d8407a363e.gif)

VS Code version: Code - Insiders 1.60.0-insider (44a4b19a910a287adef4daaeabcf68f2ba893c35, 2021-08-30T11:36:29.726Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (0.28GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
npm-intellisense|chr|1.4.0
vscode-github-actions|csc|0.21.2
vscode-eslint|dba|2.1.23
kusto|don|0.3.7
typescript-notebook|don|1.4.0
gitlens-insiders|eam|2021.7.1905
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
codespaces|Git|1.0.4
copilot|Git|1.4.2535
remotehub-insiders|Git|2021.8.300914
vscode-pull-request-github|Git|0.29.2
restore-git-branch-tabs|gko|0.4.1
gzipdecompressor|Hyu|1.2.0
vscode-styled-components|jpo|1.6.6
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.16.0
vscode-language-pack-es|MS-|1.60.1
vscode-edge-devtools|ms-|1.3.0
python|ms-|2021.10.1183791216-dev
vscode-pylance|ms-|2021.8.4-pre.1
jupyter|ms-|2021.8.2031173646
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
live-server|ms-|0.2.8
vsliveshare|ms-|1.0.4761
debugger-for-edge|msj|1.0.15
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
smart-css-autocomplete|sai|1.4.3
msft-todo-unofficial|tyl|0.0.14
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824cf:30353184
javagetstartedt:30350119
pythonvspyt187:30356034
pydsgst2:30356659

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? (besides copilot)

**Comment by MitchTalmadge** [comment]
I ran into this problem too. It works until I enable `markdown-all-in-one`. They are conflicting in some way.

**Comment by dcsan** [comment]
@MitchTalmadge did you find a way to patch the config or keyboard settings for the markdown-all-in-one ? It would be nice to have both working!

**Comment by MitchTalmadge** [comment]
@dcsan there is a suggested solution here: https://github.com/yzhang-gh/vscode-markdown/issues/1011

Let me know if you try it and if it works for you! I haven't tried it yet.

**Comment by MitchTalmadge** [comment]
The solution in https://github.com/yzhang-gh/vscode-markdown/issues/1011 ended up working great for me.
