### ISSUE TITLE
Banner: allow to set a SVG icon path instead of codicon

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#131977]
For the welcome banner in web, we want to show a SVG instead of Codicon. Would be great if the API for welcome banner could allow either a codicon or path to a SVG icon.

**Comment by sbatten** [comment]
I updated the banner part to support an svg and made the fallback for the welcome banner point to the app icon instead of the code codicon. I suppose the welcome banner api now should also accept a uri string and not just a codicon string as the banner service can also handle it

**Comment by bpasero** [comment]
Thanks for the prompt change, I pushed the API changes too 👏
