### ISSUE TITLE
Unbind alt+z

### ISSUE THREAD

**Issue by replay111** [Microsoft/vscode#13198]
- VSCode Version: 1.5.3
- OS Version:  macOS Sierra 10.12

Steps to Reproduce:

Is there any way to remap alt+z to other combination or even remove this binding?
In Polish language this combination should give my letter from my alphabet ("ż"), but because of this key binding I am not able to do this ;(

**Comment by Tyriar** [comment]
See [documentation](https://code.visualstudio.com/docs/customization/keybindings#_removing-a-specific-key-binding-rule) for how to unbind keybindings.

**Comment by replay111** [comment]
```json
[
    { "key": "alt+z",                 "command": "-editor.action.toggleWordWrap",
                                     "when": "editorTextFocus" }
]
```

**Comment by rebornix** [comment]
It's the same as #17420 and we can reproduce this issue.
