### ISSUE TITLE
Defender is flagging VSCode

### ISSUE THREAD

**Issue by ashwin-84** [microsoft/vscode#131986]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Download from https://github.com/microsoft/vscode-winsta11er/releases/download/v0.0.4/vscode-winsta11er-x64.exe
2. Observe that Smartscreen (browser) and Windows Defender instantly flag the above binary.
3.
![image](https://user-images.githubusercontent.com/54099665/131536004-63568e93-5a76-40e3-8eeb-b6ef82eed437.png)

**Comment by sbatten** [comment]
This is resolved with 0.0.5
