### ISSUE TITLE
Emmet unable to expand abbreviation with onclick attribute

### ISSUE THREAD

**Issue by yblui** [microsoft/vscode#131966]
**Does this issue occur when all extensions are disabled?**: Yes

- VS Code Version: 1.59.1
- OS Version: Windows 10

**Steps to Reproduce**:

1. 输入`span[onclick="chsld();"]*12`.
2. 按"Tab"。
3. 并未展开Emmet缩写。
4. 我又选择了这段文字。
5. 点击“编辑-Emmet展开缩写”。
6. 仍无任何反应。
7. 注释：该缩写在emmet.io官网运行正常。

**Comment by CodeCrazy-ywt** [comment]
1. Input `span[onclick="chsld();"]*12`.
2. Press "Tab"。
3. The Emmet abbreviation was not expanded. 
4. Select the text again.
5. Click `Edit` -> `Emmet: Expand Abbreviation`. 
6. Still nothing happens.
7. Note: This abbreviation works on the official website emmet.io.
