### ISSUE TITLE
slow startup and not responsive

### ISSUE THREAD

**Issue by imadjamil** [microsoft/vscode#131978]
## System Info

* Code: 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa)
* OS: win32(10.0.19043)
* CPUs: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz(8 x 1382)
* Memory(System): 15.74 GB(9.09GB free)
* Memory(Process): 143.69 MB working set(96.72MB private, 0.18MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 9111     | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 125      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 9046     | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 4        | [main]                    | initial startup: true                                       |
| create window                                                   | 42       | [main]                    | initial startup: true, state: 0ms, widget: 18ms, show: 19ms |
| app.isReady => window.loadUrl()                                 | 237      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 24837    | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 884      | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 31       | [renderer]                | -                                                           |
| init workspace service                                          | 47       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 14617    | [renderer]                | -                                                           |
| restore viewlet                                                 | 0        | [renderer]                | -                                                           |
| restore panel                                                   | 0        | [renderer]                | -                                                           |
| restore & resolve visible editors                               | 9        | [renderer]                | 1: workbench.editors.gettingStartedInput                    |
| overall workbench load                                          | 250      | [renderer]                | -                                                           |
| workbench ready                                                 | 35382    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 1207     | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 50084    | [renderer]                | -                                                           |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1630419421123	0	0
code/didStartMain	1630419421246	123	123
code/willStartCrashReporter	1630419421265	19	142
code/didStartCrashReporter	1630419430311	9046	9188
code/mainAppReady	1630419430357	46	9234
code/willLoadMainBundle	1630419430361	4	9238
code/fork/willLoadCode	1630419430381	20	9258
code/registerFilesystem/file	1630419430480	99	9357
code/didLoadMainBundle	1630419430486	6	9363
code/willStartMainServer	1630419430497	11	9374
code/didStartMainServer	1630419430501	4	9378
code/willCreateCodeWindow	1630419430547	46	9424
code/willRestoreCodeWindowState	1630419430548	1	9425
code/didRestoreCodeWindowState	1630419430548	0	9425
code/willCreateCodeBrowserWindow	1630419430550	2	9427
code/didCreateCodeBrowserWindow	1630419430568	18	9445
code/willMaximizeCodeWindow	1630419430568	0	9445
code/didMaximizeCodeWindow	1630419430587	19	9464
code/didCreateCodeWindow	1630419430589	2	9466
code/willOpenNewWindow	1630419430594	5	9471
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1630419430599	0	0
code/didStartRenderer	1630419455421	24822	24822
code/willWaitForWindowConfig	1630419455422	1	24823
code/didWaitForWindowConfig	1630419455422	0	24823
code/willShowPartsSplash	1630419455422	0	24823
code/didShowPartsSplash	1630419455423	1	24824
code/willLoadWorkbenchMain	1630419455431	8	24832
code/didLoadWorkbenchMain	1630419456315	884	25716
code/registerFilesystem/file	1630419456322	7	25723
code/registerFilesystem/vscode-userdata	1630419456323	1	25724
code/willInitWorkspaceService	1630419456327	4	25728
code/willInitStorage	1630419456328	1	25729
code/didInitStorage	1630419456359	31	25760
code/didInitWorkspaceService	1630419456374	15	25775
code/willStartWorkbench	1630419456378	4	25779
code/LifecyclePhase/Ready	1630419456380	2	25781
code/registerFilesystem/trustedDomains	1630419456477	97	25878
code/willRestoreEditors	1630419456619	142	26020
code/didRestoreEditors	1630419456628	9	26029
code/LifecyclePhase/Restored	1630419456628	0	26029
code/didStartWorkbench	1630419456628	0	26029
code/didRemovePartsSplash	1630419456628	0	26029
code/willConnectSharedProcess	1630419456658	30	26059
code/willLoadExtensions	1630419456713	55	26114
code/willHandleExtensionPoints	1630419471152	14439	40553
code/didHandleExtensionPoints	1630419471324	172	40725
code/didLoadExtensions	1630419471330	6	40731
```

### cached data created (lazy, might need refreshes)

[prof-284b.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/7084615/prof-284b.main.cpuprofile.txt)
[prof-284b.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/7084616/prof-284b.renderer.cpuprofile.txt)

![image](https://user-images.githubusercontent.com/6026260/131519551-93cc00fc-e3bf-4240-8f44-3725c65cd6b1.png)

**Comment by jrieken** [comment]
delayed app-ready event

**Comment by deepak1556** [comment]
Based on the profile, looks like crash reporter took 9s to start. Can you launch with `code --disable-crash-reporter` and see if it helps.

Lets start with eliminating the factors that might have caused this from previous similar reports,

1) Is there Nahimic service running on your device
2) Do you have faceit anti-cheat client installed ?
3) Do you have any anti-virus software running ?

**Comment by imadjamil** [comment]
@deepak1556 
Disabling the crash reporter makes things a bit faster and prevents the "not responding" window but it does not resolve the issue.

1. I don't see Nahimic service running
![image](https://user-images.githubusercontent.com/6026260/131637177-b2c340eb-0e23-434f-b21a-435a294621c5.png)

2. I don't have faceit anti-cheat client installed

3. I have Bitdefender Endpoint Security Tool running but I don't think it's causing the problem since I have the same tool running on my old PC without any issues with vscode.

Note: this is a fresh install on a new PC that is causing the issue.

**Comment by deepak1556** [comment]
Thanks for confirming, the root issue here is all of the child process launches from the application are delayed than normal as to why that is happening needs further debugging.

Can you follow the steps in this recording to capture event trace.

![recording](https://user-images.githubusercontent.com/964386/131648183-e523569e-cdef-4667-9431-496b7ef402a8.gif)


Couple of things to follow,

1) You can download the tool from https://github.com/google/UIforETW/releases/download/1.55/etwpackage1.55.zip
2) Make sure to set the heap profiled process in your case to `code.exe`
3) Launch with `--disable-crash-reporter`
3) Stop and save the trace once the editor has finished opening.
3) Send the captured trace to Deepak.Mohan@microsoft.com as it contains sensitive information.
