### ISSUE TITLE
Consider a vertical select option to select past end of line, padding with spaces when doing so.

### ISSUE THREAD

**Issue by theodore-wilson-amd** [microsoft/vscode#131992]
Visual SlickEdit allows you to vertically select past EOL such that when you insert at the selected vertical bar, the selected lines are padded with spaces.  This is a very handy feature, allowing you to insert commas or semicolons aligned like a table in the source code.

It would also be handy to be able to vertically select with the right mouse button instead of <alt><shift> which is slower.

This is an excellent tool.  Thank you, Ted

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/13960
