### ISSUE TITLE
Files don't get created or saved

### ISSUE THREAD

**Issue by AnishDe12020** [microsoft/vscode#131975]
Issue Type: <b>Bug</b>

If I try to create or save a file, the progress bar just goes on forever. If I try the same from the cli, the file gets created and written to like normal. Also I only face this issue for projects saved on my HDD, it doesn't occur for projects saved on my SSD. 

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.11.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1848)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|15.52GB (0.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id ec723d73-50d6-4f5f-8059-8f98f53cde6e|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.13.0
vscode-browser-preview|auc|0.7.1
vscode-django|bat|1.6.0
emojisense|bie|0.8.0
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
vscode-notion|fre|1.1.0
copilot|Git|1.4.2535
vscode-graphql|Gra|0.3.18
vscode-styled-components|jpo|1.6.6
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-edge-devtools|ms-|1.3.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
indent-rainbow|ode|7.5.0
csv-to-table|php|1.3.0
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
prisma|Pri|2.30.2
vscode-data-preview|Ran|2.3.0
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
vba|spe|1.7.1
ayu|tea|0.20.2
vscode-status-bar-format-toggle|tom|2.0.0
windows-terminal|Tyr|0.6.1
vscode-wakatime|Wak|17.0.0
jinja|who|0.0.8
jinja2-snippet-kit|Wya|2.0.0
JavaScriptSnippets|xab|1.8.0
codesandbox|yes|0.0.8
material-theme|zhu|3.11.4

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether the issue is being caused by one of your extensions.

**Comment by gjsjohnmurray** [comment]
Start Extension Bisect only disables extensions during its testing. If it identified Material Theme as the cause of the problem please disable it yourself in the Extensions view.

**Comment by AnishDe12020** [comment]
I tried one more `Start Extension Bisect` and I felt as if the debug was just picking out a random extension and telling me it is bugged so i cloned down my code to a new folder, opened vscode, reloaded it with all extensions disabled, and the issue persists. This seems extremely weird

**Comment by AnishDe12020** [comment]
Update: Seems like the problem was with my hard drive. Everything works well now on a new hard drive as well as on my SSD. Thanks for all the help!!!
