### ISSUE TITLE
Insiders - Don't launch output panel on startup

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode#131915]
For the last month or so, there's been a change where Insiders always opens the output panel on startup, which is a bit annoying.

Would really prefer if it just preserved the panel state (eg stayed on the terminal tab, or hidden if it wasn't open before).

(not sure if there's a new setting to change this behavior, but couldn't find anything)

Thanks!

<img width="515" alt="insiders_panel_startup" src="https://user-images.githubusercontent.com/29611875/131372237-4270c136-8808-470a-937d-dfb8e0e37086.png">

**Comment by sbatten** [comment]
@sandy081 perhaps you know of a change here?

**Comment by sandy081** [comment]
@jaymegordo Is it opening a specific output channel in the output pane? Can you please try disabling all extensions and see if you can reproduce the issue?

**Comment by jaymegordo** [comment]
Ahhhhhhh very sorry... yes the behavior was related to a specific extension (Makefile Tools)... I didn't even think to glance at the actual chanel that was opening. Thanks!!
