### ISSUE TITLE
Settings Sync conflict bc of order difference

### ISSUE THREAD

**Issue by ewerybody** [microsoft/vscode#131971]
Issue Type: <b>Bug</b>

I have an instance of settings sync conflict although ALL the values are the same. There is just 2 settings that have swapped order.

I'd assume the order does not matter. This is what its highlighting:
![image](https://user-images.githubusercontent.com/218956/131498794-1cf90f11-52ae-4697-bcad-029d4c858021.png)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (8.51GB free)|
|Process Argv|--crash-reporter-id 52bfd6ed-a49c-4227-9403-bca1ab1a5ea5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.14.2
vscode-autohotkey-plus-plus|mar|2.8.1
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
hexeditor|ms-|1.8.2
mayacode|sav|1.4.0
vscode-qt-for-python|sea|1.1.4
material-theme|zhu|3.11.4

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
yeah in general order does not matter. But since settings are stored in a json file and users can format as they wish, resolving merges are made strict. So this is as design.
