### ISSUE TITLE
files.watcherExclude not working

### ISSUE THREAD

**Issue by alexschoeberl** [microsoft/vscode#131988]
Issue Type: <b>Bug</b>

I am using VSCode in a remote docker container. I am developing a Python application. The watcher should exclude files in the .mypy_cache directory. I added the following setting to devcontainer.json:

    "files.watcherExclude": {
      "**_cache/**": true,
      "/app/.mypy_cache/**": true
    }

However, changes in /app/.mypy_cache sub-directories are still detected and result in a reload. My workspacefolder is /app.

VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.19.121-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.98GB free)|
|Process Argv|--crash-reporter-id 540f205f-27a0-4da0-841a-acb084d5192a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Design Service|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|4.82GB (1.07GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.191.1
vscode-nginx|sha|0.6.0
MagicPython|mag|1.1.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by bpasero** [comment]
> However, changes in /app/.mypy_cache sub-directories are still detected and result in a reload

What does that mean? Who is reloading what?
