### ISSUE TITLE
emmet not found on vscode

### ISSUE THREAD

**Issue by Salaimuniselvam** [microsoft/vscode#131981]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.59
- OS Version: windows 10

Steps to Reproduce:

1. shows unknown configuration for emmet
2. emmet not working and not found ...

**Comment by Salaimuniselvam** [comment]
![error](https://user-images.githubusercontent.com/84083924/131530445-b9f4e3cb-4078-4613-8047-586b90e51694.png)

**Comment by Mo-Shakib** [comment]
In your VS Code user setting, add this line,
`emmet.includeLanguages": { "javascript": "html" }`

**Comment by Salaimuniselvam** [comment]
> In your VS Code user setting, add this line,
> `emmet.includeLanguages": { "javascript": "html" }`

i have added it and does not fix the issue..
the issue was anything related emmet in vscode does not working and vscode shows unknown configuration setting for anything related emmet.. 
How to fix the issue?

**Comment by Salaimuniselvam** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/84083924/131618603-f4f35cb5-9f91-451e-ad45-8b8e06024314.png)

emmet folder is missing in my vscode extensions..

**Comment by TarunavBA** [comment]
@Salaimuniselvam For your information `Emmet` is not and **extension**. You can probably try reinstalling Vscode.

**Comment by Salaimuniselvam** [comment]
> @Salaimuniselvam For your information `Emmet` is not and **extension**. You can probably try reinstalling Vscode.

i know that and i tried reinstalling and it does not work for me...

![Screenshot (197)](https://user-images.githubusercontent.com/84083924/131624841-34a9e85c-546c-4c70-a113-50d5ca5b038e.png)

**Comment by Salaimuniselvam** [comment]
emmet even not found on settings in vscode..

![Screenshot (200)](https://user-images.githubusercontent.com/84083924/131625599-807fa92b-1c0d-4d5f-ae48-de8c46a5dd4a.png)

**Comment by TarunavBA** [comment]
> > @Salaimuniselvam For your information `Emmet` is not and **extension**. You can probably try reinstalling Vscode.
> 
> i know that and i tried reinstalling and it does not work for me...
> 
> anything related emmet shows unknown configuration settings in vscode... why.?
> 
> ![Screenshot (199)](https://user-images.githubusercontent.com/84083924/131625332-1917f782-99fe-4d7c-8b63-0d8851dc6290.png)

Did you try resetting _VSCode_ **completely**? Also which language do you use frequently?

**Comment by Salaimuniselvam** [comment]
> > > @Salaimuniselvam For your information `Emmet` is not and **extension**. You can probably try reinstalling Vscode.
> > 
> > 
> > i know that and i tried reinstalling and it does not work for me...
> > anything related emmet shows unknown configuration settings in vscode... why.?
> > ![Screenshot (199)](https://user-images.githubusercontent.com/84083924/131625332-1917f782-99fe-4d7c-8b63-0d8851dc6290.png)
> 
> Did you try resetting _VSCode_ **completely**? Also which language do you use frequently?

i m using javascript in meteorjs framework

**Comment by Salaimuniselvam** [comment]
.
> Did you try resetting _VSCode_ **completely**? Also which language do you use frequently?

 I fixed the issue by resetting completely..
I deleted the code folder in appdata after uninstalling vscode and reinstalled it..
now the problem is fixed..
 before you mentioning .. i didn't know how to reset completely...
Thank you bro...

**Comment by TarunavBA** [comment]
> .
> 
> > Did you try resetting _VSCode_ **completely**? Also which language do you use frequently?
> 
> I fixed the issue by resetting completely..
> I deleted the code folder in appdata after uninstalling vscode and reinstalled it..
> now the problem is fixed..
> before you mentioning .. i didn't know how to reset completely...
> Thank you bro...

It's ok! 😁 What is your nMe/

**Comment by Salaimuniselvam** [comment]
> It's ok! 😁 What is your name?

salaimuniselvam

**Comment by TarunavBA** [comment]
I'm Tarunav.BA studying 7th grade

**Comment by TarunavBA** [comment]
@Salaimuniselvam Don't forget to visit my GitHub page! github.com/TarunavBA

**Comment by raratiru** [comment]
> Did you try resetting _VSCode_ **completely**? 

Indeed that worked, thank you, here are the docs:

https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall

**Comment by Rakeshpradhan1999** [comment]
I completely deleted all files and uninstalled vs code and then reinstalled,  now its working fine

**Comment by sumittiwari5** [comment]
> .
> 
> > Did you try resetting _VSCode_ **completely**? Also which language do you use frequently?
> 
> I fixed the issue by resetting completely.. I deleted the code folder in appdata after uninstalling vscode and reinstalled it.. now the problem is fixed.. before you mentioning .. i didn't know how to reset completely... Thank you bro...

I reset my vscode and also reinstall it but still the emmet option is not showing in my vscode.
