### ISSUE TITLE
Using the Jupyter Notebook extension in VSCode not possible.

### ISSUE THREAD

**Issue by Dervis-vL** [microsoft/vscode#131931]
Does this issue occur when all extensions are disabled?: Yes

 The extension publisher referred me to this page for support.
- VS Code Version: 1.59.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a new or existing Jupyter Notebook (Jupyter Notebook extension and ipykernel are installed);
2. The Notebook does not show content, does not let me open a new cell and "loading" bar is showing.

![image](https://user-images.githubusercontent.com/65704977/131400228-3dbf496b-fa6f-4b29-b034-ed4baf63d75f.png)

**Comment by rebornix** [comment]
@Dervis-vL can you confirm if you can reproduce with latest Stable and Jupyter extension?
