### ISSUE TITLE
cmake "$ENV{VAR}" not working in vscode portable (ubuntu)

### ISSUE THREAD

**Issue by pramitbiswas** [microsoft/vscode#131963]
Does this issue occur when all extensions are disabled?: Yes/No
Not Applicable as CMake tools need to be installed

- VS Code Version: 1.59.1, commit: 3866c3553, Linux  portable
- OS Version: Linux x64 4.4.0-186-generic

Steps to Reproduce:

Working version:
From windows (vscode is installed, not portable), I SSHed to Linux server, run Build from the bottom status bar icon. It builds as expected.
From Linux (vscode not installed, portable version), run Build from the bottom status bar (of course same project, same everything) it failed.

To find the error I added one existing environment variable that required to run to CMakeLists.txt file `message("$ENV{VAR_NAME}")`.

VSCode from the Windows machine, I got the VAR_NAME printed on the OUTPUT window. However, VSCode (portable) on the Linux machine does not print anything and shows a blank line.

This problem does not appear if I open a terminal and then call VSCode to start.

How to get around this?

**Comment by TylerLeonhardt** [comment]
I think this might be by design because the VS Code process will only inherit envvars from the parent process. If the parent process is a terminal (and specifically a login shell) you'll probably have all the envvars you expect.

The vscode-server is launched using bash I believe which _should_ have all the envvars.

**Comment by joaomoreno** [comment]
There's a bunch of settings regarding setting env for VS Code to load, eg: `terminal.integrated.env.linux`. Can you give that a try?
