### ISSUE TITLE
Shift+click highlights wrong cell range after rearranging cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#131938]
- Open a notebook
- Move cells around
- Use shift+click to highlight a range
- The wrong range is highlighted

(See 8/30 meeting recording)

**Comment by roblourens** [comment]
This is from https://github.com/microsoft/vscode/issues/118044, we have a new "anchor" concept but the notebook needs different logic than other lists. I think what we want is just to set it to the focused cell each time focus changes?

Simpler repro steps

- Click cell 0
- down arrow to focus cell 2
- Shift+click cell 3
- Cells 0 to 3 are selected

cc @joaomoreno if you have ideas

**Comment by rebornix** [comment]
@roblourens I can't reproduce this with the steps you provided in latest OSS, can you help confirm?

**Comment by roblourens** [comment]
Still happens for me

**Comment by joaomoreno** [comment]
This even feels broken to me on normal lists, eg explorer:

1. Click a row
2. Down arrow a few times
3. Space bar to select
4. Shift click a few rows below

🐛 Everything from the initial row to the clicked row gets selected. I expected only from step 3 to clicked. I think we should move the anchor with some keyboard actions.

**Comment by joaomoreno** [comment]
@roblourens Can you verify?
