### ISSUE TITLE
Add Symbol navigation for PHP 

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#132]
would you please add support for PHP symbol navigation ? 

I like the symbol navigation for js, just press CTRL+SHIFT+O
The symbol list will show to us

that's amazing

**Comment by imanesski** [comment]
PHP symbol navigation is working on previous builds after today's build is now broken.

Please help us, I'm using vscode in mac.

**Comment by stefangabos** [comment]
I need this, too!

**Comment by arzzen** [comment]
+1

**Comment by eugen-v** [comment]
+1 too.
This used to work before 0.10.x :(

**Comment by egamma** [comment]
>This used to work before 0.10.x :(

Sorry about that, but it was based on an hand written PHP parser that could not keep up with the PHP language.

**Comment by stefangabos** [comment]
that's still better than nothing, i guess :)

**Comment by lyndon1115** [comment]
Is there any extension to make it work again? I just have to stay on the lower version, for the vs code is the best ide for php I have ever seen.

**Comment by felixfbecker** [comment]
I'm working on an extension

**Comment by thuey** [comment]
@felixfbecker That's great! Do you have a link to the extension?

**Comment by felixfbecker** [comment]
@thuey Currently trying to extend PHPParser so it can parse incomplete PHP documents so I can get AST nodes all the way up to the cursor position, even if it is not terminated by a semicolon yet:
https://github.com/nikic/PHP-Parser/issues/262

**Comment by tills13** [comment]
This is still an issue, and would be nice if it were resolved.

**Comment by felixfbecker** [comment]
PHP IntelliSense supports both file and workspace symbol search
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

![documentsymbol](https://cloud.githubusercontent.com/assets/10532611/18989804/374aa7a4-870e-11e6-8630-941f11258e38.gif)

![workspacesymbol](https://cloud.githubusercontent.com/assets/10532611/18989806/3a5efb98-870e-11e6-9fae-0a2d763f5aad.gif)

**Comment by gulshan** [comment]
May be this issue can be closed now.

**Comment by netroby** [comment]
ok. close it now . thanks.

**Comment by gopi-ar** [comment]
Those who can't use @felixfbecker 's extension because of it's PHP7 requirement, can use Lin Yang's PHP symbols extension:
https://marketplace.visualstudio.com/items?itemName=linyang95.php-symbols

**Comment by felixfbecker** [comment]
Just to avoid confusion, my extension works with PHP code of any version. You just need to install PHP 7 locally because the extension is written in PHP 7 itself and needs PHP 7 to run.

**Comment by vietvudanh** [comment]
@felixfbecker Thanks for the clarification, you might want to add it explicitly in the plugin description, I misunderstood too.
