### ISSUE TITLE
Action Buttons in editor are way too large

### ISSUE THREAD

**Issue by TreasureJim** [microsoft/vscode#132028]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.1
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. start vscode `code . --disable-extensions
2. click on source control button during merge
3. click on file under merge changes

Expected output: normal sized buttons

Actual Output: 
![image](https://user-images.githubusercontent.com/71513440/131609547-821d39ab-7daa-4b04-ba02-4602f4e5c103.png)

**Comment by jrieken** [comment]
Did you configure this setting: `editor.codeLensFontSize`?

**Comment by TreasureJim** [comment]
Thank you, I couldn't find this setting.
