### ISSUE TITLE
VS Code froze when processing project the first time

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#13209]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 3.13.0-24-generic

Steps to Reproduce:

1. have a big project (many files and folders with c, c++, perl, bash, python, yml, makefile, etc )
2. installed vcode-todo
3. restarted

After it opened, it froze for a least 40m (with RED linux emblem in the right  bottom corner, assuming that means it's working like hell). Shouldn't it run without  affecting the program !? Same happened the first time I opened a big project with VSCode, assuming it was processing and storing the functions and all.

**Comment by Tyriar** [comment]
It sounds like the todo extension is bad at handling large projects, you should file an issue against the extension to not index everything on very large projects.
