### ISSUE TITLE
Comparing editors when one is custom with diff support fails

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132035]
We offer various ways to compare editors, e.g. from the explorer: 

![recording](https://user-images.githubusercontent.com/900690/131634264-019b574c-c7da-4a57-a104-77e514226614.gif)

I think this broke when editor resolvers got in charge of creating diff editors. We are probably now asking the notebook editor to create both sides of the diff editor, which fails because only the one is valid.

I wonder whether we could simply fallback to the default text editor diff when any of the sides failed to create for the diff case specifically?

An alternative would be to create a side by side input and open the 2 editors properly (e.g. text editor left, notebook right).

**Comment by bpasero** [comment]
@lramos15 this is actually a case where picking the editor from the `modified` override will result in issues because the `original` one might be different.

**Comment by lramos15** [comment]
Hmmm, so I guess what you want here is check both sides and see if they're the same else you should fallback to default since there's no way to generate a cross editor diff

**Comment by bpasero** [comment]
Yes!

**Comment by lramos15** [comment]
Alright once your PR goes in I'll implement better override logic into the resolver for diffs

**Comment by bpasero** [comment]
I think I can still reproduce though:

![recording (2)](https://user-images.githubusercontent.com/900690/131713031-7b13489a-b863-4b3f-933d-152b6d3cca86.gif)

**Comment by lramos15** [comment]
Fixed

**Comment by bpasero** [comment]
Works with notebook, but when comparing a text file to an image (I have Luna paint installed), I get this:

![image](https://user-images.githubusercontent.com/900690/131787532-328622c9-0d65-40b1-8f6b-1d58e895dcda.png)

**Comment by lramos15** [comment]
Not sure what is happening here as if you compare image to .ts it works but not if you swap the direction of compare. I can confirm that the resolver is returning a diff editor with two FileEditorInputs that have the correct resource

**Comment by bpasero** [comment]
Oh interesting. This is probably a regression that is a bit older. Since I go through the editor service, my input to replace ends up being identical with the input to replace it with (for some reason?).

I can fix it by switching to the `IEditorGroupView` methods that bypass any resolving.
