### ISSUE TITLE
[loc][Query][VSCode] Please clarify the placeholders

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#13205]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
'{0}' failed with exit code {1}

File Name:
src\vs\workbench\parts\execution\electron-browser\terminalService.nls.resx

Resource ID:
".resx", 0; "linux.term.failed"

Query:
Please explain "{0}". Thanks.	Zinacle	10/4/2016 11:31:14 AM

**Comment by ZombieProtectionAgency** [comment]
`{0}` and `{1}` are generally placeholders to be filled in later.

**Comment by Tyriar** [comment]
`{0}` is a placeholder for the path of the executable (eg. `/bin/bash`, `cmd.exe`, etc.), `{1}` is a placeholder for the exit code (a non-zero number).
