### ISSUE TITLE
Not able to input in debug console

### ISSUE THREAD

**Issue by Jaideep25** [microsoft/vscode#132040]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.59
- OS Version:22000.168 win11

Steps to Reproduce :
The problem is that I can't type in the debug console when I run the program it shows this error : `Evaluation failed because the thread is not suspended.`
Language used : `JAVA`
Code ran : 
```
import java.util.*;

class Compound_Record {
    double p, t, r, ca, ci;

    void getData() {
        Scanner in = new Scanner(System.in);
        System.out.println("Enter the principal amount");
        p = in.nextDouble();
        System.out.println("Enter the time");
        t = in.nextDouble();
        System.out.println("Enter the rate of interest");
        r = in.nextDouble();
        in.close();
    }

    void calculate() {
        ca = p * Math.pow((1 + r / 100), t);
        ci = ca - p;
    }

    void display() {
        System.out.println("Principal : " + p);
        System.out.println("Compound Interest : " + ci);
        System.out.println("Amount : \u20B9" + ca);
    }

    public static void main(String args[]) {
        Compound_Record jai = new Compound_Record();
        jai.getData();
        jai.calculate();
        jai.display();
    }

}
```

Thanks.

**Comment by gjsjohnmurray** [comment]
So maybe suspend the thread by clicking the pause button on the debug toolbar.

**Comment by Jaideep25** [comment]
I mean that I can't type values inside the debug console but I can type inside the Terminal window

**Comment by gjsjohnmurray** [comment]
That is as designed. Debug Console is where you interact with the process you are debugging. Terminal is a different process which spends a lot of its life waiting for your commands.

**Comment by Jaideep25** [comment]
Lol yes, I know that, but this works in debug console without values, but with values it shows the error....
