### ISSUE TITLE
dotnet run hangs on vscode mac

### ISSUE THREAD

**Issue by dortega88** [microsoft/vscode#132019]
Issue Type: <b>Bug</b>

After using dotnet run to compile and build console application, it starts to hang until restart.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv|--crash-reporter-id 2bbbaba9-7b74-4d27-81b6-32031e8c4624|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.2.0
bracket-pair-colorizer-2|Coe|0.2.1
githistory|don|0.6.18
vscode-surround-with|drc|1.2.0
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
auto-using|Fud|0.7.15
angular2-switcher|inf|0.3.4
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|12.0.0
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.20
csharpfixformat|Leo|0.0.84
csharp|ms-|1.23.14
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn420:30356812
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by dortega88** [comment]
Can I update this one or do I need to reopen a new bug report was busy and didn't have it happen until now, I do have the gif now though showing the problem.

**Comment by deepak1556** [comment]
@dortega88 you can update in this issue. Thanks!

**Comment by dortega88** [comment]
Ok so I went ahead and used the .net-core-uninstall toolkit and removed some older SDKs and runtimes (I had more than a few) and the issue doesn't seem to happen quite as often as it did. I'll be sure to open a new ticket if I see this issue again.

https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-macos

**Comment by dortega88** [comment]
Added the link for the MacOS uninstall tutorial.
