### ISSUE TITLE
Hiding Notebook level toolbar doesn't result in toolbar icons being displayed in editor toolbar for Interactive widow

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#132063]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders 1.60
- OS Version: Mac

Steps to Reproduce:

1. Hide global toolbar
2. We should see the icons in the editor toolbar for interactive window
See images of Notebook vs interactive

No icons for interactive window (kernel picker)
![Screen Shot 2021-09-01 at 09 02 50](https://user-images.githubusercontent.com/1948812/131705777-f0b5e8b8-4149-49b7-980d-501d976b98db.png)

**Comment by IanMatthewHuff** [comment]
Verified:
![image](https://user-images.githubusercontent.com/812783/135542327-6873922c-98e6-461e-8e53-5ea08f8ae640.png)
