### ISSUE TITLE
Editor resolver `canHandleDiff` is obsolete?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132036]
My understanding is that a registered editor implements the function to create a diff and does not need to signal it.

**Comment by lramos15** [comment]
I thought the same but when I went through the work to remove this I ran into the reason I had to add this in the first place. Notebooks. Notebooks don't want to render diffs when there is a screen reader so even though they register a factory we don't always want to call it.

**Comment by bpasero** [comment]
@lramos15 but this is weird, no? I can register a diff editor factory and forget to say `canHandleDiff` in my registration?

**Comment by lramos15** [comment]
@bpasero Yes and in that case we just assume true for everything (or at least we are supposed to but I haven't fixed that bug yet).

**Comment by bpasero** [comment]
Then I would rename the property to reflect how it is used today.

**Comment by lramos15** [comment]
Alright will do once your PR gets merged to avoid conflicts. Do you have a suggested name? `canSupportDiff(resource)`?

**Comment by bpasero** [comment]
Now I wonder, couldn't the notebook registration for notebook editors detect screen reader case and update the contribution dynamically?

I think we could get this functionality by just doing that from the single factory method, no?

**Comment by lramos15** [comment]
There's also a setting and to change the functions you would have to unregister and re-register everything when these values change which seems intensive.

https://github.com/microsoft/vscode/blob/bfc47075381995d15a31bb93e69a4f50c9557756/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L163-L164

**Comment by bpasero** [comment]
And I guess the factory cannot return `undefined` or another hint to signal this?

**Comment by lramos15** [comment]
That was a design decision at the very start because we wanted registration to mean "you will create an input when the resolver decides it's your turn" to keep the resolver as the controller and prevent these cases of "oh I know I should handle this, but don't want to in this case". It was more of a strictness thing, but I would be open to changing it if you want

**Comment by bpasero** [comment]
Ok maybe it is just about the naming then:
* `singlePerResource` should this be `singleton` to match with `EditorInputCapabilities.Singleton`
* `canHandleDiff` / `canSupportResource` should this maybe be aggregated into a single method `isEnabled(resource|diffInput)`? I think the intent is to enable/disable the registration dynamically for specific inputs

**Comment by lramos15** [comment]
> * `singlePerResource` should this be `singleton` to match with `EditorInputCapabilities.Singleton`

Does that imply one per resource? Singleton to me implies one editor only

> * `canHandleDiff` / `canSupportResource` should this maybe be aggregated into a single method `isEnabled(resource|diffInput)`? I think the intent is to enable/disable the registration dynamically for specific inputs

Sure I can do this

**Comment by bpasero** [comment]
`singlePerResource`: so what is the behaviour, you can have multiple editors opened of the kind but not when the resource is the same?

**Comment by lramos15** [comment]
> `singlePerResource`: so what is the behaviour, you can have multiple editors opened of the kind but not when the resource is the same?

This is correct

**Comment by lramos15** [comment]
Closed via https://github.com/microsoft/vscode/pull/156672
