### ISSUE TITLE
Enable Step Into / Over before debugging has started

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#132000]
In VS non-C, Step Into and Step Over will Start Debugging and break on the first occasion possible (in main). Could the same be done for VSC?

**Comment by roblourens** [comment]
We have the same for the F10 and F11 keybindings, but we won't show the debug toolbar all the time when not in a debug session

**Comment by OlafvdSpek** [comment]
It's not about the toolbar.. the actual commands seem to be disabled / grayed out (according to the menu).

![image](https://user-images.githubusercontent.com/2218936/132806583-e8f20b10-27c8-44c0-8a53-4766151a4937.png)

**Comment by roblourens** [comment]
There is a command "Start Debugging and Stop on Entry" but it doesn't show up in the menu. It is bound to F10 and F11 and shows up in the command palette. I don't think we should add this to the menu since we already have a lot in there (and multiple start-debugging commands)

**Comment by OlafvdSpek** [comment]
That's not enabled for C++ and Python is it?

**Comment by roblourens** [comment]
Oh right, this has to come from the debug extension, because "pause on entry" concept only exists for the particular debug adapter. Extensions can't contribute to the menu. So unfortunately it's not really practical for us to add this to the menu. The  extensions could add the keybinding if they wanted. I know they also have their own entrypoints like the run button in the editor toolbar.

**Comment by OlafvdSpek** [comment]
Wouldn't it be simpler to add the logic into the standard Step Over / Into commands / handlers? 
`if !InDebugMode: doStartDebuggingandStopOnEntry`?
That way the menu entries would work too and there'd only be one key binding.

**Comment by roblourens** [comment]
The problem is that "pause on entry" is not a general vscode debug concept but a feature of a specific debug adapter

**Comment by OlafvdSpek** [comment]
> The problem is that "pause on entry" is not a general vscode debug concept

Maybe it should be. ;)

Anyway, what's the right issue tracker for the C++ and Python extensions?
