### ISSUE TITLE
Show complete docstring on hover

### ISSUE THREAD

**Issue by jingw222** [microsoft/vscode#132070]
What we have:
<img width="1207" alt="Screen Shot 2021-09-02 at 12 36 05 AM" src="https://user-images.githubusercontent.com/5494367/131709728-8a20f169-c1bd-478c-878a-d2b6daafc598.png">
which only shows a very terse signature. We need the **full** docstring instead:
<img width="857" alt="Screen Shot 2021-09-02 at 12 40 38 AM" src="https://user-images.githubusercontent.com/5494367/131710471-d57fbb88-b30f-4e0c-9a60-7ba9669079ce.png">
as in Juptyer:

https://user-images.githubusercontent.com/5494367/131711331-b0e085f1-1290-4177-b068-44b612aa25e3.mov

```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0
```

**Comment by IllusionMH** [comment]
/extPython

It actually looks like extension issue and it's not providing full information for hovers (or picks that text from some other place).

You can see in gif attached to issue #112373 - hovers support can have a ton of text.
