### ISSUE TITLE
Unable to view entire error message in top drop down error bar

### ISSUE THREAD

**Issue by wmpainter** [Microsoft/vscode#13202]
- VSCode Version: 1.5.3
- OS Version: macOS Sierre v 10.12

Steps to Reproduce:

1. Load any process that will create a error message to display in the top drop down error bar on either a reduced window size or with a long file path error.
2. Unable to view or scroll through whole message, so unsure what the end of the message is (even with debug console open, the error messages do not display in the debug console, which i wouldn't expect them to, but thought it was worth mentioning).

<img width="1456" alt="screen shot 2016-10-04 at 6 21 53 am" src="https://cloud.githubusercontent.com/assets/5957293/19070990/e598a398-89fb-11e6-9ae3-ae18226ec3bc.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5454
