### ISSUE TITLE
Native Notebooks: alt-enter runs cell and creates a new one for code cells, but doesn't work for markdown

### ISSUE THREAD

**Issue by nickeubank** [microsoft/vscode#132010]
## Environment data

-   VS Code version:  1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: 11.4
-   Python and/or Anaconda version: n/a
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Jupyter server running: Local

Turned on experiment with:

```jsonf
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "jupyter.experiments.optInto": [
        "__NativeNotebookEditor__"
    ],
```

## Steps to reproduce:

`alt-enter` in a code cell runs the cell and creates new cell below; it doesn't do anything with a markdown cell. 

![alt-enter](https://user-images.githubusercontent.com/9683693/124945239-f7040600-dfdb-11eb-8946-fd2d2c530b2d.gif)

## Logs

<details>

<summary> Ran code cell with alt-enter. Escaped, moved down to markdown cell, tried to run with alt-enter. 
</summary>

<p>

```
Info 2021-07-08 11:03:43: Execute Cells request 1 5
Info 2021-07-08 11:03:43: Execute Cell 5 file:///Users/Nick/github/practicaldatascience/source/what_is_gis.ipynb
Info 2021-07-08 11:03:43: Cell Index:5, state:1, exec: undefined. User queued cell for execution
Info 2021-07-08 11:03:43: Cell Index:5, state:1, exec: undefined. Ready to execute
Info 2021-07-08 11:03:43: Cell Index:5, state:1, exec: undefined. Before Execute individual cell
Info 2021-07-08 11:03:43: Cell Index:5, state:1, exec: undefined. Start execution
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. Send code for execution
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. Empty cell execution
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. Completed successfully
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. Completed successfully & resolving
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. After Execute individual cell 2
Info 2021-07-08 11:03:43: Cell Index:5, state:3, exec: undefined. Execution disposed


```

</p>
</details>

**Comment by tanhakabir** [comment]
Hey @nickeubank! Thanks for opting into the Native Notebooks experiment and trying out our new Notebook experience before our launch! We appreciate the bug report. Just wanted to let you know this is on my plate for this month
