### ISSUE TITLE
VS code terminal freezes

### ISSUE THREAD

**Issue by MartinMcCaulley** [microsoft/vscode#132003]
Issue Type: <b>Bug</b>

when I am working on other things and leave VS code for a while, VS code's terminal does not respond in a timely manner. I'll type `git ...` but nothing happens. 

I've had patience in the past and eventually the terminal starts responding, but lately I simply close VS code and restart.

Please fix. This is annoying.

Best,
Martin

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.31GB free)|
|Process Argv|--crash-reporter-id 7cd011b7-6da3-4a74-b15e-ac634b1b8451|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.13.0
vscode-django|bat|1.6.0
better-toml|bun|0.3.2
dart-code|Dar|3.25.1
flutter|Dar|3.25.0
vscode-eslint|dba|2.1.23
python-extension-pack|don|1.6.0
vscode-wasm|dts|1.3.1
vscode-html-css|ecm|1.10.2
tslint|eg2|1.0.47
prettier-vscode|esb|8.1.0
cshtml-tm|fir|1.0.0
vscode-jest-runner|fir|0.4.44
kotlin|fwc|0.2.23
go|gol|0.27.1
MagicPython|mag|1.1.0
Kotlin|mat|1.7.1
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.16.0
csharp|ms-|1.23.14
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.8.3
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.0
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
vsliveshare|ms-|1.0.4761
rust|rus|0.7.8
scala|sca|0.5.4
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
vscode-lldb|vad|1.6.5
vscodeintellicode|Vis|1.2.14
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
javagetstartedc:30351792
vsdyn420:30356812
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by TarunavBA** [comment]
Maybe it is because ur laptop is not having so much ram. 🤪

**Comment by TarunavBA** [comment]
@MartinMcCaulley You can simply press `ctrl + p` and type `developer: reload window`. But make sure u have saved all the files! 😄

**Comment by meganrogge** [comment]
please try disabling your 38 extensions and use extension bisect to see if the poor performance in the terminal is related to any of those.
