### ISSUE TITLE
Fold/unfold tags in JSX like HTML

### ISSUE THREAD

**Issue by andersonmalheiro** [microsoft/vscode#132049]
Issue Type: <b>Feature Request</b>

When foldind HTML tags inside JSX code, the closing tag is hidden and sometimes this make the understanding of the code a little bit confusing. Also, copying the folded code becomes a bit difficult. I was wondering if its possilble to make it work like in HTML, where when you fold a tag it is possible to see both opening and closing tags.

Imagine that we have this JSX code:
```
<Container>
    <Navbar>...</Navbar>
    <Content>...</Navbar>
</Container>
```

When we fold the `Container` tag, it is displayed like this:
```
<Container>...
```

In HTML the code will be like this, showing the closing tag:
```
<Container>...
</Container>
```
so its easier to copy the code and understand the structure

---

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.11.0-31-generic
Restricted Mode: No

**Comment by mjbvz** [comment]
Relevant code: https://github.com/microsoft/vscode/blob/4247b296eb143c94e48ca2629a1945f429e8768c/extensions/typescript-language-features/src/languageFeatures/folding.ts#L63

**Comment by jwei98** [comment]
Hi, would love to take this on as my first contribution!
