### ISSUE TITLE
the agent due to an RPC failure. Code 0.

### ISSUE THREAD

**Issue by LollipopRussia** [microsoft/vscode#132055]
Hello everyone, I have such a problem, the terminal does not start. There are a bunch of different errors, here one of them is the termination of the agent due to an RPC failure. Code 0. What should I do? I have already installed Google dns, disabled antiviruses, enabled all Windows services, I did everything / help !!!! My English is bad, help me for God's sake

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
