### ISSUE TITLE
Enable select all with RegEx patterns

### ISSUE THREAD

**Issue by elkebirmed** [Microsoft/vscode#13203]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

**Steps to Reproduce:**
1. Find strings with RegEx pattern `h\d`
   - this will highlight `h1, h2, h3, h4, h5, h6`
2. Now i want to select all the matches `Ctrl+Shift+L`

**Expected:** close the find dialog and select all the matches

**Note:** This will work with non RegEx pattern!

**Comment by therealmarv** [comment]
workaround `alt + enter` here https://github.com/Microsoft/vscode/issues/5400#issuecomment-258781766 ?
