### ISSUE TITLE
Terminal no vertical scrollbar with zsh on openSUSE

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#13200]
- VSCode Version: 1.5.3
- OS Version: openSUSE Leap 42.1

Steps to Reproduce:

1. Install zsh and oh-my-zsh, and set it as default shell
2. Start VSCode, open terminal, type `cat /proc/cpuinfo`
3. No scrollbar on right

![2016-10-04 17-45-22](https://cloud.githubusercontent.com/assets/19658647/19069766/e2abf5c2-8a5a-11e6-9b60-40eb9298bac9.png)

**Comment by Tyriar** [comment]
This is fixed in the insiders build https://code.visualstudio.com/insiders coming soon to stable.
