### ISSUE TITLE
Provides a spinner wheel similar to Jupyter notebook when debugging

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#132078]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16296

<div type='discussions-op-text'>

<sup>Originally posted by **altosaar** May 21, 2021</sup>
Steps to reproduce:

1. Use Python VS Code extension to launch a new jupyter notebook
2. Execute a cell with `import time; time.sleep(20)`
3. Notice the spinner icon that moves, denoting that something is running (below the cell with current runtime in seconds):
![image](https://user-images.githubusercontent.com/5317244/119143591-c2c98b80-ba15-11eb-8548-728216111a6f.png)

Now switch to the python debugger: 

1. Use ctrl + shift + D to launch debug the current python file
2. Notice that the only visual affordance for seeing that something is running is the 'RUNNING' text in the bottom right in the call stack. 
![image](https://user-images.githubusercontent.com/5317244/119143862-1a67f700-ba16-11eb-8dda-7c6969d21656.png)

Just a thought, but adding a spinner icon besides 'running', or in the play/pause/stop on top while a debugging process is running, along with the timing info in seconds could be very helpful as a visual cue (I've found myself restarting processes frequently, unnecessarily)

</div>

**Comment by brettcannon** [comment]
Transferred on behalf of @altosaar

**Comment by roblourens** [comment]
Thanks for the suggestion. Besides the UI hints in the debug viewlet, we also change the status bar color (maybe not in your theme but it can be configured) and show the badge (1) on the debug activity bar icon. I don't think I want to show animation or a timer. I'd find an animation distracting and it's not clear in what case the timer would be meaningful - time running between breakpoints? It's sort of a different situation than running a notebook cell.
