### ISSUE TITLE
input not working 

### ISSUE THREAD

**Issue by brunofernandes18** [microsoft/vscode#132092]
Issue Type: <b>Feature Request</b>

i said  ("what is your name") and it doesnt work I AM VERY CROSSS!!!!🤬🤬

VS Code version: Code 1.59.1 (Universal) (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by lramos15** [comment]
Closing due to lack of update.
