### ISSUE TITLE
El motor de typescript terminó inesperadamente

### ISSUE THREAD

**Issue by paulvenci** [microsoft/vscode#132091]
Issue Type: <b>Bug</b>

El error dice que el motor de typescript terminó inesperadamente 5 veces en menos de 5 minutos.. Estoy trbajando conectado al servidor via SSH

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.12GB free)|
|Process Argv|--crash-reporter-id 4c92ddaf-2efe-466c-ae48-37a6c9357ac1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 104.248.67.211|
|OS|Linux x64 5.4.0-74-generic|
|CPUs|DO-Regular (2 x 2294)|
|Memory (System)|1.94GB (0.44GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
vscode-ionic-snippets|fiv|2.2.2
auto-close-tag|for|0.5.12
vscode-language-pack-es|MS-|1.59.3
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
material-icon-theme|PKi|4.10.0
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
copilot|Git|1.4.2535
sftp|lix|1.12.9
vscode-language-pack-es|MS-|1.59.3
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
addDocComments|ste|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
javagetstartedt:30351793
vsdyn420:30356812
vscus224:30358039

```

</details>

**Comment by CodeCrazy-ywt** [comment]
TypeScript server died 5 times in the last 5 minutes. Connected via SSH.
