### ISSUE TITLE
terminal cursor foreground is over dropBackground

### ISSUE THREAD

**Issue by michal037** [microsoft/vscode#132090]
Issue Type: <b>Bug</b>

I searched for known issues and did not find this. I read and accept `Rules of Conduct`.

### Currently
`terminalCursor.foreground` is over `terminal.dropBackground`

### Expected
`terminalCursor.foreground` is under `terminal.dropBackground`

### Video recording of the problem
![terminal](https://user-images.githubusercontent.com/7441419/131764801-44b80efe-3877-456c-a8e8-3a384da10417.gif)

---

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (26.86GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 115d5e1c-df42-47e2-8ae1-76ba0eec26f0|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

---

### My settings

```json
{
    "workbench.colorTheme": "Noctis Azureus",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "editor.accessibilitySupport": "off",
    "editor.wordWrap": "on",
    "editor.rulers": [
        80,
        100
    ],
    "terminal.integrated.cursorBlinking": true,
    "remote.SSH.remotePlatform": {
        "debianVM": "linux"
    },
    "python.autoComplete.addBrackets": true,
    "python.analysis.completeFunctionParens": true,
    "python.defaultInterpreterPath": "C:/Programy/Python39/python.exe",
    "vscodeGoogleTranslate.HoverTranslations": false,
    "vscodeGoogleTranslate.preferredLanguage": "English",
    "autoDocstring.quoteStyle": "'''",
    "workbench.colorCustomizations": {
        "terminal.background": "#0c0c0c",
        "terminal.foreground": "#cccccc",

        "terminal.ansiBrightBlack": "#767676",
        "terminal.ansiBrightRed": "#e74856",
        "terminal.ansiBrightGreen": "#16c60c",
        "terminal.ansiBrightYellow": "#f9f1a5",
        "terminal.ansiBrightBlue": "#3b78ff",
        "terminal.ansiBrightMagenta": "#b4009e",
        "terminal.ansiBrightCyan": "#61d6d6",
        "terminal.ansiBrightWhite": "#f2f2f2",
        "terminal.ansiBlack": "#0c0c0c",
        "terminal.ansiRed": "#c50f1f",
        "terminal.ansiGreen": "#13a10e",
        "terminal.ansiYellow": "#c19c00",
        "terminal.ansiBlue": "#0037da",
        "terminal.ansiMagenta": "#881798",
        "terminal.ansiCyan": "#3a96dd",
        "terminal.ansiWhite": "#cccccc",

        "terminal.selectionBackground": "#858585",
        "terminalCursor.background": "#0c0c0c",
        "terminalCursor.foreground": "#ffffff",
        "terminal.dropBackground": "#2c2c2c",
    }
}
```

**Comment by Tyriar** [comment]
This has been fixed on all rendered sometime since it was reported.
