### ISSUE TITLE
Allow "toSide" command to work on walkthrough descriptions 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#132087]
Hey there! I was trying to make so that the "Open" word on one of the Python extension's tile would trigger the `workbench.action.files.openFile` command and open a file to the side. I can make it happen if I add a `:toSide:` in the button action, but not if it's added as a "link", if that makes sense. In the GIF below you can see that it triggers a `command 'toSide:workbench.action.files.openFile' not found` error because it doesn't seem to be supported.  

![toSideWalkthroughBehavior](https://user-images.githubusercontent.com/45497113/131751593-8230c025-1608-4182-bd74-3135068a824d.gif)

```json
                    {
                        "id": "python.runAndDebug",
                        "title": "Run and debug your Python file",
                        "description": "[Open](command:toSide:workbench.action.files.openFile) a Python file and click on the play button on the top right of the editor. \n You can also just press F5 and select \"Python File\" to run with the debugger. \n  \n[Open file](command:toSide:workbench.action.files.openFile)",
                        "media": {
                            "svg": "resources/walkthrough/rundebug2.svg",
                            "altText": "How to run and debug in VS Code with F5 or the play button on the top right."
                        },
                        "when": ""
                    },
```

Is there any chance this could be supported? I'd like to keep directing users to our docs through the button instead of a having a `Open File` CTA there 🤔

**Comment by JacksonKearl** [comment]
Good catch thanks, should be good now :)

**Comment by luabud** [comment]
Thanks a lot Jackson! 🥳
