### ISSUE TITLE
"Replace All" confirm dialog should be improved

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#132056]
## Search terms
* Replace All
* Confirm dialog

## Whats the Problem?
The confirm dialog for **Replace All** contain only
* The count of places
* The count of files
* The new text for the replacement

## What should be improved
The confirm dialog should contain the **original search text** too (the text that will replaced).

## Additional information
![2021-09-01 12_27_34-src - Visual Studio Code](https://user-images.githubusercontent.com/17874713/131697735-ccb48692-a3d6-408c-81f9-b4ea8e4521f7.png)

**Comment by ArturoDent** [comment]
Doesn't this get very messy if your search text is a regexp (with alternation, etc.) so that the text to be replaced can be many different things in different files.

**Comment by yashpalgoyal1304** [comment]
> if your search text is a regexp

nice point, but then, just the used regex should be shown verbatim
