### ISSUE TITLE
Collapsable cells groups to Jupyter Notebooks in VSCode

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#132081]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16092

<div type='discussions-op-text'>

<sup>Originally posted by **pbower** April 29, 2021</sup>
In the insider's build we can collapse Jupyter cells which is awesome.

Now, it would be even better if we can group cells and collapsed cells and collapse the group, with a user-entered Group name displayed.

This would mean that we turn something that was previously say '20 cells', and taking up heaps of screen real estate, into a neatly organised group. In effect, a draft for a Python module or something of that nature.

Absolute heaven.</div>

**Comment by rchiodo** [comment]
@pbower you can achieve this goal with markdown cells between cells. They allow you to collapse a group:

Uncollapsed:

![image](https://user-images.githubusercontent.com/19672699/131742214-72e77f6a-8e28-4a7e-8517-e01f58970b0d.png)

Collapsed:

![image](https://user-images.githubusercontent.com/19672699/131742243-fd57b461-f00f-471e-ba54-0cb46007cbb2.png)

It collapses up to the last markdown cell.
