### ISSUE TITLE
Cannot open file in restricted mode on ssh remote

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#132069]
1. On an ssh remote, `code-insiders <file>` and choose to open in restricted mode
2. Two new windows pop up 🐛 
3. You hit the trust prompt again 🐛 
4. Choose to open in restricted mode, a new window pops up instead of opening. Repeat.

Recording: https://memes.peet.io/img/21-09-33893714-9e28-463c-9024-41c47e08a6fe.mp4

**Comment by sbatten** [comment]
I could not repro the 2 new windows, but overall the flow is quite broken.

Our initial calculation is not working because we check against file only I believe, so we don't initialize as untrusted.

**Comment by roblourens** [comment]
This actually worked fine for me now
