### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Beoo-666** [microsoft/vscode#132076]
To make it easier to view, please add an icon to the folder.
Please add some more spaces for the indentation of the sub-directories/files.
Please add a line to the files between the top-level directory and the sub-directory to distinguish them.
![image](https://user-images.githubusercontent.com/55978588/131728193-3a6852d3-ed74-46fe-8fc3-39aa85f4031c.png)

**Comment by ArturoDent** [comment]
For indentation and guide lines, see `https://stackoverflow.com/a/55315106/836330.
