### ISSUE TITLE
Synchronizing repo causes git to push to wrong remote and fails

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#132071]
<img width="559" alt="CleanShot 2021-09-01 at 10 42 47@2x" src="https://user-images.githubusercontent.com/35271042/131718543-834d8700-dd0f-4059-8d1a-f417493e6c92.png">

>git fetch --all
>remote: Repository not found.
>fatal: repository 'https://github.com/4086606/vscode-codicons/' not found
>error: Could not fetch 4086606

And my config is:

<img width="595" alt="CleanShot 2021-09-01 at 10 44 11@2x" src="https://user-images.githubusercontent.com/35271042/131718701-453dded6-c4f7-430b-a16c-5285a9867eb5.png">

When I push manually via `git push` it works so somehow VS Code is choosing the wrong remote and don't know why

**Comment by lszomoru** [comment]
We are running `git fetch --all` so we try to fetch from all the registered remotes. 
There is a remote that does not exist any more hence we fail to fetch from it.
