### ISSUE TITLE
gopls: Uninitialized settings in multi-root workspace

### ISSUE THREAD

**Issue by Michael-F-Ellis** [microsoft/vscode#132054]
Summary
In a multi-root workspace containing folders with code that must be built with different GOOS & GOARCH, the folder's settings.json is initially ignored the first time one of the files in the folder is opened for editing. In the case of js,wasm this results in a cascade of error messages stemming from the inability to import syscall.js.

The errors can generally be resolved by Developer Reload Window.

I created a minimal repo that can be used to reproduce the problem at https://github.com/Michael-F-Ellis/wasmvetissue

I don't know if this is a gopls issue or a vscode issue, so I'm submitting it in both repositories.

Does this issue occur when all extensions are disabled?: Yes/No
No, since the behavior depends on the Go Extension.

- VS Code Version:
```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```
Steps to Reproduce:

1. Install the Go Extension in vscode
2. Clone the repository from https://github.com/Michael-F-Ellis/wasmvetissue. 
2. Open it in vscode by opening its workspace.code-workspace. 
3. In vscode, open wasm/main.go.
4. Observe four errors total beginning with a failure to import syscall.js accompanied by a message about build constraints.
5. Execute Developer Reload Window.
6. Observe that the errors disappear.

The behavior is dependent on the initial state of the workspace, i.e. if you quit vscode with one of the files in the wasm folder opened for editing, the problem does not recur the next time you open the workspace. OTOH, if you quit with a file from the notwasm folder opened, the problem will recur.

**Comment by sandy081** [comment]
Settings are owned by the go extension. It needs initial investigation from the go extension. Hence closing it.
