### ISSUE TITLE
Inlay hints cause editor message to show in wrong location

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#132021]
Issue Type: <b>Bug</b>

**Repro**
1. Create a keybinding that runs extract constant refactorings:

```json
	{
		"key": "ctrl+shift+e",
		"command": "editor.action.refactor",
		"args": {
			"kind": "refactor.extract",
			"preferred": true
		}
	},
```

2. In a JS file:

```js
console.log($ $);
```

2. Select `$ $` so that your cursor is on the first `$` and try running the refactoring using the above keybinding

**Bug**

The message shows from the start of the inlay hint instead of showing at the cursor position:

<img width="659" alt="Screen Shot 2021-08-31 at 5 59 53 PM" src="https://user-images.githubusercontent.com/12821956/131594970-e0d6fde5-0240-444f-aa2d-3d975bb9f22b.png">

VS Code version: Code - Insiders 1.60.0-insider (Universal) (efaa9c304bba61bdce8b0d39db5df94ce3a53fb6, 2021-08-31T15:05:11.419Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|1.8.0
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
folder-source-actions|bie|0.2.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-yaml-preamble|bie|0.0.4
test-ext|bie|0.0.1
vscode-eslint|dba|2.1.23
typescript-notebook|don|1.4.0
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
EditorConfig|Edi|0.16.4
codespaces|Git|1.0.4
vscode-pull-request-github-insiders|Git|2021.8.43924
vscode-drawio|hed|1.6.2
vscode-postfix-ts|ipa|1.9.4
latex-workshop|Jam|8.20.2
vscode-platform-specific-sample|joa|1.2.1
vscode-platform-specific-sample|joa|1.5.0
vscode-memfs|jri|0.0.3
template-string-converter|meg|0.5.3
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.16.0
vscode-language-pack-de|MS-|1.60.2
vscode-edge-devtools|ms-|1.3.0
python|ms-|2021.9.1144093763-dev
vscode-pylance|ms-|2021.8.4-pre.1
jupyter|ms-|2021.8.2031187289
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
azure-account|ms-|0.9.8
hexeditor|ms-|1.8.2
js-debug-nightly|ms-|2021.8.3117
live-server|ms-|0.2.8
vscode-github-issue-notebooks|ms-|0.0.105
vscode-typescript-next|ms-|4.5.20210831
vsliveshare|ms-|1.0.4761
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
java|red|0.81.0
code-spell-checker|str|1.10.2
rest-book|tan|4.2.0
ayu|tea|0.20.2
luna-paint|Tyr|0.9.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-test|vsc|0.31.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30353183
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgsc2:30356658

```

</details>

**Comment by mjbvz** [comment]
We're using `MessageController` to show this message: https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/editor/contrib/codeAction/codeActionUi.ts#L98

**Comment by hediet** [comment]
Would it be better if the message would always point to the position right to the inlay hint (or other injected texts)?
Currently it always points to the position left to injected text.

I overlay widgets could get and pass down a position affinity (left/right) to `Widget._setPosition`.

**Comment by mjbvz** [comment]
My intuition is that the message should always show near the text, so right side. Not sure if this would look odd though if the user selects right to left though and then the message is displayed after the selected text

**Comment by hediet** [comment]
This can actually get even worse:

![image](https://user-images.githubusercontent.com/2931520/155981775-c9b238cc-899e-440f-9a18-5d9cebd669ba.png)

And also happens when using extra-wide characters:

![image](https://user-images.githubusercontent.com/2931520/155982227-8ac4b22f-e260-46bb-88f6-d48b5d81b7d6.png)

First fix is to use `column` rather than `column - 1`:

![image](https://user-images.githubusercontent.com/2931520/155986613-6f6017c3-5fb9-4162-bd33-146994010974.png)

Next fix is to introduce position affinity for the message widget and the widget system:

![image](https://user-images.githubusercontent.com/2931520/155988412-d00962cb-9351-48b9-9b5f-4ff38d979248.png)

![image](https://user-images.githubusercontent.com/2931520/155988525-7f607333-d401-4a51-b512-1d212b2d5337.png)
