### ISSUE TITLE
Errors/Problems not showing

### ISSUE THREAD

**Issue by karank786** [microsoft/vscode#132060]
first it was showing any errors i make but now it not showing errors or problems anymore even when i knowing do errors to check but still not showing any problems

**Comment by karank786** [comment]
Errors and mistakes are not showing

**Comment by IllusionMH** [comment]
You need to provide info that will help to reproduce problem.

At this point this issue contains no info useful to resolve it.

**Comment by karank786** [comment]
Ok tomorrow i will show some info

**Comment by sandy081** [comment]
I am closing this as we do not got enough information from user.

Please reopen with the necessary info.
