### ISSUE TITLE
Node JS

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/vscode#132039]
Hey guys it will be good if it will automatically install nodejs when installing Vscode!

**Comment by TylerLeonhardt** [comment]
Hi there. I appreciate you talking the time to open an issue but automatically installing nodejs, and really, the _correct version_ of nodejs for everyone is very challenging and would be hard to get right when a user could install the one they need themselves. As such, I'm going to close this as out of scope.

**Comment by TarunavBA** [comment]
@TylerLeonhardt We can give the **option** for users to download Node.JS if they choose _yes_ we can ask them to type their wanted version of node.js. If they choose _no_ we can go on with the regular installation. 😃
