### ISSUE TITLE
hover not working

### ISSUE THREAD

**Issue by bstaliyan** [microsoft/vscode#132038]
Issue Type: <b>Bug</b>

hover is not working well...

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.21996
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (6.50GB free)|
|Process Argv|--crash-reporter-id dd922b62-c028-44f4-a4c1-fde77fb3d003|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
elixir-ls|Jak|0.8.0
csharp|ms-|1.23.14
debugger-for-chrome|msj|4.12.12
cs-script|ole|2.0.0
vscode-css-custom-properties|Toc|0.0.5
c-cpp-flag-debugging|uts|0.0.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by lramos15** [comment]
Closing in favor of #131667 as that appears to be similar with more info. If this isn't that then feel free to come back to this issue.
