### ISSUE TITLE
Remove web extension kind

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#132034]
Remove web extension kind

**Comment by sandy081** [comment]
To verify:

You can check where the extension is running using the command `Developer: Show Running Extensions`

Make sure you can install following extensions in codespaces and github.dev and are running in **web extension host**. When installed in vscode desktop or vscode remote, they shall run in **local node extension host**

- `vscodevim.vim`
- `tuttieee.emacs-mcx`
- `ollyhayes.colmak-vim`

Make sure you can install following extensions in codespaces, github.dev, vscode desktop and vscode remote and always run in **web extension host**

- `ms-vscode.anycode`

Make sure you can install following extensions github.dev

- vsls-contrib.codetour
- joyceerhl.vscode-pyodide
- vsls-contrib.gistfs 
- yamoo9.euid-scss-mixins-snippets
- Tyriar.luna-paint
- TylerLeonhardt.msft-todo-unofficial
- donjayamanne.kusto
- viewdo.dxp
- gregoire.dance

**Comment by isidorn** [comment]
Works great. Only corner case is `anycode` which does not get activated on VS Code desktop. In other cases it works in the web extension host as expected. Sandy is investigating this. Adding verified label.

**Comment by sandy081** [comment]
Seems to work (also for Isi).
