### ISSUE TITLE
Search(ctrl+shift+F) doesn't work for C++

### ISSUE THREAD

**Issue by Mike-wujf** [microsoft/vscode#132053]
1.Open a c++ project folder in vscode and no files opened;
2.Click : Search(ctrl+shift+F) tab on the left;
3.Enter a class name which exsit in c++ project folder to search edit box;
4.The search result is empty; And I think the file in the folder is not searched;
5. But if open the files of the opened folder, it will search all the opened files, and the result will shown;

**Comment by IllusionMH** [comment]
/needsMoreInfo
Are these classes in excluded/ignored folders?

See https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options especially paragraph with
"Also note the Use Exclude Settings and Ignore Files toggle button in the files to exclude box."

Files in open editors use different mechanism for search and will be included even if outside of workspace root or in excluded files.
