### ISSUE TITLE
Popups occur all over workspace and prevent me from reading while typing

### ISSUE THREAD

**Issue by Corallus-Caninus** [microsoft/vscode#132012]
Popups happen inline while typing for suggestions and definitions. I would at least prefer to send them to dedicated window(s) instead as I cannot read nearby code while typing.

I have scoured the internet and cannot find a solution so I thought this would be suiting as a bug either way due to documentation.

Thank you VSCode is otherwise my favorite IDE.

**Comment by TylerLeonhardt** [comment]
@Corallus-Caninus just trying to understand... which popups in particular are bothering you?

**Comment by Corallus-Caninus** [comment]
everything that occurs where I type that isn't there when I don't type.

**Comment by TylerLeonhardt** [comment]
Unfortunately, I don't think this is something that we're able to support anytime soon. You can either show the popups or hide them individually. If more users end up chiming in I can reopen.
