### ISSUE TITLE
Extension host terminated unexpectedly In another Window of VS-CODE.

### ISSUE THREAD

**Issue by zeel-codder** [microsoft/vscode#132098]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.58.2
- OS Version: Ubuntu 20.04.2 LTS

![Screenshot from 2021-09-02 09-36-49](https://user-images.githubusercontent.com/69882648/131780238-228f641f-03d3-45df-ba76-5c872aa037d3.png)

In Image, We can see that In One Window the Extension Host is Running Fine, But in the Other Window, it does not work.

**Comment by gjsjohnmurray** [comment]
Does the Start Extension Bisect command reveal which extension is causing the problem?

**Comment by zeel-codder** [comment]
By Opening the Developer tool I am getting this Error.
```bash
 Extension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ workbench.desktop.main.js:2899
workbench.desktop.main.js:630   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git, CoenraadS.bracket-pair-colorizer, DivyanshuAgrawal.competitive-programming-helper, ecmel.vscode-html-css, formulahendry.terminal, PKief.material-icon-theme, ritwickdey.LiveServer, streetsidesoftware.code-spell-checker, Wscats.omi-snippets
```

I also tried to uninstall some of the extensions but the problem is not solved.

**Comment by gjsjohnmurray** [comment]
Did you try the Extension Bisect (launch it from Command Palette)? That procedure is designed to pinpoint an extension causing problems.

**Comment by zeel-codder** [comment]
oh, Thanks For Giving Advice, There is An Extension That is Casing The Problem, after running Extension Bisect the Problem is Gone. 
Thank You 🙏🙏 .
