### ISSUE TITLE
Horizontal scroll bar only works at the end of the Jupyter feed

### ISSUE THREAD

**Issue by turbonate** [microsoft/vscode#132166]
## Environment data

-   VS Code version: 1.59.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro - 20H2
-   Python and/or Anaconda version: 3.9.5 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

When I am viewing a large dataframe output, I expect the horizontal scroll bar to be visible and work when I scroll up to view the headers of the dataframe print.  The horizontal scrollbar should be available anytime the feed is showing a table or output that is wider than the visible feed.

## Actual behaviour

I have to scroll to the bottom of the -correction: dataframe - to make the horizontal scroll bar visible, move the bar, then scroll back up to see the column headers. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. df = Dataframe()
2. load df with 15 columns and 36 rows of data (with long enough column names that it goes off the screen to the right)
3. print(df)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
This is related to the other issue we have about being able to control how much of a dataframe (HTML) is displayed at a time.

**Comment by rebornix** [comment]
The horizontal scrollbar should now be always visible 

![Image](https://user-images.githubusercontent.com/876920/206310777-8562f049-af30-44f8-8993-5d89279ee4b5.png)
