### ISSUE TITLE
Setting custom bracket color when using built-in "Bracket Pair Colorization"

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode#132195]
With the latest stable vscode v 1.6.0, feature "Bracket Pair Colorization" is built-in, but the custom color setting for this feature is confusing. It hints that default high light color could be overrided by  setting in  "workbench.colorCustomizations". 

Q1: what property could user config in `settings.json`  to change bracket color (I did googled, but not found )?
Q2:For instance, I just want to change the most inner-layer bracket color, how to do it, (what if the most 2, 3 and so on... inner-layer color)?

After clarify the answers on questions above, I hope there coulde be some ui settings to config for this new feature.

**Comment by athos** [comment]
As for Q1, I [found the `editorBracketHighlight.foreground[1-6]` properties](https://github.com/microsoft/vscode/blob/43666f33a14fd93d80f16c1518ce52e2d2d3154a/src/vs/editor/common/view/editorColorRegistry.ts#L55-L60).
I'm using them like the following, which works fine:

```json
    "workbench.colorCustomizations": {
        "editorBracketHighlight.foreground1": "#ffd700",
        "editorBracketHighlight.foreground2": "#90ee90",
        "editorBracketHighlight.foreground3": "#87cefA",
        "editorBracketHighlight.foreground4": "#da70d6",
        "editorBracketHighlight.foreground5": "#ff7f50"
    },
```

**Comment by dbsxdbsx** [comment]
@athos, thanks. Now it is worked.
