### ISSUE TITLE
In 1.59 typing <div> automatically closes with </div>, and in 1.60, it doesn't

### ISSUE THREAD

**Issue by BruceJi7** [microsoft/vscode#132185]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Type `<div>`
2. Be sad because you have to type `</div>` manually

I am typing in .tsx files, I have Prettier and ESLint active.
Yesterday, when I typed `<div>` it would complete the div itself, today it does not.
It still closed `<span>` by itself, same as button, li... it appears to only be `<div>`

**Comment by TylerLeonhardt** [comment]
Can you share what extensions you have installed?
