### ISSUE TITLE
Notebook editor: support `viewState`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132101]
With https://github.com/microsoft/vscode/commit/22cf36faf81ca270390ec233389a81339b40b63a, `IEditorOptions.viewState` is now a generic thing and no longer text editor specific. There are a few places where we automatically fill in `viewState` before doing an operation, the most prominent one is probably when you drag and drop an editor to another group or even across windows.

The idea is:
* your `IEditorPane` (notebook editor) implements the optional method `getViewState`
* in `setInput` you check for `options.viewState` and apply it accordingly

I did a quick and dirty

```ts
getViewState(): object | undefined {
        const input = this.input;
        if (!(input instanceof NotebookEditorInput)) {
                return undefined;
        }

        return this._loadNotebookEditorViewState(input);
}
```

in `notebookEditor.ts` but wasn't sure how to add the applying side in `setInput`, it probably needs to be respected somewhere here:

https://github.com/microsoft/vscode/blob/c3f63dc2bb2211e46c3369696e4061dbd2d0630c/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1110-L1110

**Comment by rebornix** [comment]
It seems if I reload the window, then the `setInput` doesn't carry `viewState` info, is there anything I miss?

**Comment by bpasero** [comment]
When editors are restored, the view state needs to be restored from the mementos, such as here:

https://github.com/microsoft/vscode/blob/d4c222488de817d491f7c5686cf1161e9cceb7d4/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L146-L150

The `viewState` property of `EditorOptions` will not carry the view state when you reload, it is meant only when `openEditor` API is called with specific view state. You should always check if there is `viewState` in the `options` to apply and then fallback to persisted view state otherwise.

**Comment by rebornix** [comment]
@bpasero thanks for the explanation, works as charm 🚀
