### ISSUE TITLE
option to disable unreachable code warning

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#132193]
there are many problems with pyright's unreachable code detection. see https://github.com/microsoft/pyright/issues/1951, https://github.com/microsoft/pyright/issues/2231, https://github.com/microsoft/pyright/issues/1531

it would be nice to have an option to disable unreachable code warnings. especially since my project already uses mypy to detect unreachable code anyway.

**Comment by TylerLeonhardt** [comment]
\extPython

**Comment by DetachHead** [comment]
https://github.com/microsoft/vscode-python/issues/17276
