### ISSUE TITLE
Add WebviewOptions.enableForms to control if forms are enabled in a webview

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#132157]
Tracks adding a new `enableForms` option to `WebviewOptions` that lets extensions disable forms inside of webview

For back compat, the default would be:

- False if scripts are disabled
- True if scripts are enabled

Explicitly setting `enableForms` would override these defaults

**Comment by mjbvz** [comment]
To verify:

1. Using the [Webview example extension](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample)
2. Add a form to the html:

```html
<form action="http://example.com" method="get" class="form-example">
  <div class="form-example">
    <input type="submit" value="Subscribe!">
  </div>
</form>
```

1. Do not yet add `enableForms`
1. Launch the webview and confirm that the form works (open the dev tools an confirm clicking the button doesn't produce errors and instead redirects to `example.com`
1. Now remove the `enableScripts` webview option and confirm that form no longer renders
2. Finally, explicitly set `enableForms` and confirm this controls if forms are enabled or not

**Comment by SNDST00M** [comment]
How would one check if `enableForms` was part of the API in <CURRENTVERSION>
