### ISSUE TITLE
Markdown enumerations are not rendered

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/vscode#132160]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur
Create a markdown cell. Write the following:
```
Some header text
1. Text
2. Text
```

## Actual behavior
The text is displayed as 
```Some header text 1. Text 2. Text```
 in the rendered view.

## Expected behavior
It should be rendered as 
```
Some header text
1. Text
2. Text
```

**Comment by greazer** [comment]
This still repros even with the Katex implementation. If you have backticks around the text it repro's.

**Comment by mjbvz** [comment]
If there are literal quotes in the markdown source (either back tic or quote), rendering as a single like is expected: https://spec.commonmark.org/dingus/?text=%601.%20Text%0A2.%20Text%60

It seems to me though like the quotes got introduces while the poster was trying to share the example and were not actually in the source markdown. I confirmed that the markdown block:


```md
Some header text
1. Text
2. Text
```

Renders as expected:

![Screen Shot 2021-09-02 at 1 38 01 PM](https://user-images.githubusercontent.com/12821956/131912904-12da6a8c-caf7-47f9-acc6-3a9302b0feff.png)


Let me know if I've misunderstood the issue
