### ISSUE TITLE
Debugging web extension hangs window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#132142]
Issue Type: <b>Bug</b>

**Repro**
1. Try debugging a web extension with the debug configuration:

```json
{
	"name": "Run Web Extension in VS Code",
	"type": "pwa-extensionHost",
	"debugWebWorkerHost": true,
	"request": "launch",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}",
		"--extensionDevelopmentKind=web"
	],
	"outFiles": [
		"${workspaceFolder}/dist/web/**/*.js"
	],
	"preLaunchTask": "npm: compile-web"
}
```

**Bug**
Sometimes the window being debugged will completely freeze on launch. Killing the debugger does not close the window you also can't close it normally. I have to force quit the entire app to kill the window

VS Code version: Code - OSS Dev 1.61.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
@connor4312 Let me know what logs would be helpful. I don't see anything in the dev tools of the main window (the one that launched the debugger and can't view the logs of the frozen window

**Comment by connor4312** [comment]
Deepak suggested launching with [this flag](https://github.com/microsoft/vscode/issues/127861#issuecomment-904144910) to avoid the freeze.

**Comment by mjbvz** [comment]
Still seeing this in OSS after launching with this flag. It does't happen all the time but I just hit it after reloading the window being debugged

**Comment by deepak1556** [comment]
That flag is only effective for windows, this would be a different issue. Can you take a process sample of the frozen renderer from the macOS activity monitor

<img width="710" alt="Screen Shot 2021-09-03 at 5 44 23 AM" src="https://user-images.githubusercontent.com/964386/131913598-46b4dd26-914b-409d-884a-21ac0ecd19a0.png">
