### ISSUE TITLE
When adding a breakpoint while currently being stopped on a different breakpoint, the debugger continues.

### ISSUE THREAD

**Issue by lorinatzberger** [microsoft/vscode#132141]
Issue Type: <b>Bug</b>

1) Have a piece of code (tested on c#)
2) Put a breakpoint somewhere
3) Run the code till the breakpoint is hit
4) Attempt to add another breakpoint
5) Notice how the debugger will automatically "continue", potentially stopping into the next breakpoint

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (3.12GB free)|
|Process Argv|--crash-reporter-id a6513a52-67fa-4a7d-a158-6736d14ecfba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.15
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vscode-yaml|red|0.22.0
vscode-counter|uct|2.3.0
unity-debug|Uni|3.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by TylerLeonhardt** [comment]
@lorinatzberger do you see this repro in other languages other than C#?

**Comment by lorinatzberger** [comment]
@TylerLeonhardt I could not reproduce it with python, and I tried setting up a c++ project as well but I can't get it to run (my clang is too old, and it won't create the launch.json and associated tasks correctly for msvc)
C# may not be the whole truth here as I'm doing this using Unity but I don't really see how adding a breakpoint in the VSCode UI could trigger a debugger continue because of an extension. Maybe I don't understand how extensions tie into VSCode.
Before this happens, I also get this bug happening which I assume is from a C#/Unity extension but not really sure:
https://github.com/Unity-Technologies/vscode-unity-debug/issues/201
There's a video there showing the issue. If it'll help, I can add one here too but I guess the behaviour should be clear from the description.

**Comment by TylerLeonhardt** [comment]
When you set a breakpoint in the UI and you have an active debug session, a message is sent to the extension that's providing the debug adapter.

Since you couldn't repro in python, signs point to the unity debugger.

**Comment by lorinatzberger** [comment]
@TylerLeonhardt Thank you for your input on this. I'm trying to transfer this issue to https://github.com/Unity-Technologies/vscode-unity-debug/issues but this link on doing so, does not seem to apply: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository . I can't seem to find that right sidebar.

**Comment by TylerLeonhardt** [comment]
@lorinatzberger unfortunately GitHub doesn't support cross-org transferring :(  I'll go ahead and close this since you'll get an issue going on them
