### ISSUE TITLE
unproductive activity

### ISSUE THREAD

**Issue by percival254331717** [microsoft/vscode#132144]
Issue Type: <b>Bug</b>

I have to authenicate to pull and push images to repository repeatedly. Overbearing and distracting from value activities.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon Silver 3050U with Radeon Graphics    (2 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.88GB (2.09GB free)|
|Process Argv|C:\\Users\\Percival Austin\\Documents\\app_active_worker --crash-reporter-id 4ae523d5-ef14-4cf2-b6bb-b230735d46ba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
mimeconvertor|ajo|0.2.0
askia-qexml-generator-extension|Ask|1.0.1
code-gnu-global|aus|0.2.2
troff|ban|1.0.22
npm-intellisense|chr|1.4.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
vscode-pull-request-github|Git|0.29.2
go|gol|0.27.2
cloudcode|goo|1.13.2
beautify|Hoo|1.5.0
batch-rename-extension|Jan|0.0.4
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
vscode-docker|ms-|1.16.1
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vscode-yaml|red|0.22.0
arrow-function-converter|Roe|0.4.1
snyk-vulnerability-scanner|sny|1.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040

```

</details>

**Comment by TylerLeonhardt** [comment]
> pull and push images to repository repeatedly

where are doing this? Is this from the Docker extension?

**Comment by joaomoreno** [comment]
> I have to authenicate to pull and push images to repository repeatedly. Overbearing and distracting from value activities.

Can you share a screenshot of that dialog that asks for authentication?
