### ISSUE TITLE
[Bug] Confusing integrated terminal order numbers

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#132122]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open two split terminals and two standalone terminals:

   ![image](https://user-images.githubusercontent.com/28700378/131927239-8ef45438-7d5c-4037-9556-56c314b5a88f.png)

2. Use `workbench.action.quickOpenTerm`:

   ![image](https://user-images.githubusercontent.com/28700378/131843913-c82c4f70-7ebb-4612-b32a-2cc1bf3071eb.png)

Expected behavior:

1.1: bash
1.2: bash
2: bash
3: bash

**Comment by meganrogge** [comment]
please include a gif showing your terminal layout

**Comment by wenfangdu** [comment]
@meganrogge I've updated the issue description.

**Comment by Tyriar** [comment]
This is fixed:

![image](https://user-images.githubusercontent.com/2193314/208197655-26c2f0c5-d840-490b-990a-d635dd07a02d.png)
