### ISSUE TITLE
vscode Jupyter notebook not working properly

### ISSUE THREAD

**Issue by MUZAMMILKHAN02** [microsoft/vscode#132194]
•VSCode Version 1.60.0
• OS Version Windows 10 
• Extension Installed Python, Pylance, Jupyter Notebook

**I run one line of code in code cell then it's suppose to pop up second code cell for another code but it's not popping out automatically I have do manually by clicking on "+code" please give solution for that thank you.**

![Screenshot (24)](https://user-images.githubusercontent.com/87357083/131941721-3773b7fa-a67a-4de4-bbc9-d20a7e567494.png)
![Screenshot (25)](https://user-images.githubusercontent.com/87357083/131941725-0eebba3b-8ff1-461c-b3c0-1246df31e25f.png)
![Screenshot (26)](https://user-images.githubusercontent.com/87357083/131941726-5ddc58ff-adc9-4268-b3e5-c592af976004.png)

**Comment by roblourens** [comment]
If you press shift+enter it will insert a new cell, like Jupyter does. If you just click the button, it will not do that.
