### ISSUE TITLE
XML folding does not work when it contains multiline text values

### ISSUE THREAD

**Issue by Developer-Alexander** [microsoft/vscode#132110]
When an XML file contains multiline text values the folding does not work properly.

```
<?xml version=“1.0“ encoding=“UTF-8“?>
<root>
    <level1>This is a
multiline text.
    </level1>
    <level1>
        <level2>This is another
multiline text.
        </level2>
    </level1>
</root>
```

When you fold the root node it looks like this:
![grafik](https://user-images.githubusercontent.com/74363317/131826812-f4b9839a-12c5-4728-9324-f6174724e395.png)

It seems to stop at the first line without indentation. But the expectation is that the entire root node gets folded independently of the content.

Additional Information:

Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Have you installed any XML extensions?

Without a language-aware extension VS Code can only provide indent-based folding. See https://code.visualstudio.com/docs/editor/codebasics#_folding

**Comment by Developer-Alexander** [comment]
I tired it with

1. _XML Tools_ active
and
2. All extensions disabled.

The result was the same.

**Comment by Developer-Alexander** [comment]
Using _XML_ Extension from Red Hat makes a difference.

But when I get https://code.visualstudio.com/docs/editor/codebasics#_folding right then tag based folding should work for HTML without extension. Then it should be easy to get the same for XML since HTML is basically an XML.

**Comment by aeschli** [comment]
VS Code has no rich XML support out of the box, so folding is based on indentation.

An extension like XML Extension from Red Hat adds that.

**Comment by Developer-Alexander** [comment]
> VS Code has no rich XML support out of the box, so folding is based on indentation.

And there is no intention to change that? Especially when you keep in mind how close to each other HTML and XML actually are?

**Comment by aeschli** [comment]
No plans to change this. We're happy that this comes from an extension. HTML and XML look similar but each one has its own specifications. Separate parsers are required to get it right.
