### ISSUE TITLE
0   How can I show the tip again on the top of the file if I click "don't show"?

### ISSUE THREAD

**Issue by saimohan11** [microsoft/vscode#132128]
![vs](https://user-images.githubusercontent.com/88264744/131861106-c432db95-ad8c-4b4a-887a-bef764c230df.jpg)

I haven't click "don't show" yet cause I afraid I can't set it to show again please show me a solution for this

**Comment by gjsjohnmurray** [comment]
I don't think there's currently an easy way of doing this. See #24815

Pinging @meganrogge because you have a draft PR #114114 which might resolve this.

**Comment by saimohan11** [comment]
> I don't think there's currently an easy way of doing this. See #24815
> 
> Pinging @meganrogge because you have a draft PR #114114 which might resolve this.

 iam not getting settings option in notifications is there any way to get that tip again pls help me with this

> I don't think there's currently an easy way of doing this. See #24815
> 
> Pinging @meganrogge because you have a draft PR #114114 which might resolve this.

**Comment by isidorn** [comment]
Open your settings and reset this setting
`"workbench.editor.untitled.hint"`

It should not be set to `hidden`

**Comment by saimohan11** [comment]
> Open your settings and reset this setting
> `"workbench.editor.untitled.hint"`
> 
> It should not be set to `hidden`

thanks a lot
