### ISSUE TITLE
Files served by readonly filesystem show double '(read-only)' suffix in titlebar again

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#132127]
Issue Type: <b>Bug</b>

Recurrence of #79240 and #109733

Also happens in 1.59.1, so not a recent regression.

I will submit a PR.

VS Code version: Code - Insiders 1.60.0-insider (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:40:58.134Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/issues/130526 landing, we no longer indicate this state in the titlebar, only in places where the icon label appears.
