### ISSUE TITLE
Add Electron support for theming MacOS titlebar

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#13213]
Latest versions of Atom added the ability to theme or hide the MacOS titlebar, which apparently is due to the ability being added to latest versions of the Electron shell.

![screen shot 2016-10-04 at 11 42 59 am](https://cloud.githubusercontent.com/assets/835148/19081286/c0a29ad6-8a27-11e6-8261-ca44ad50a5f5.jpg)

**Comment by leaxoy** [comment]
May be duplicate with #12377 ?

**Comment by octref** [comment]
Dup of #12377.
