### ISSUE TITLE
Notebooks: 2 different icons for output mimetype

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#132125]
Open a Notebook with a pandas plot and see 2 icons:

![image](https://user-images.githubusercontent.com/12758612/131857503-af526884-a9fa-477e-8534-d35053c96a8f.png)

Version: 1.60.0-insider (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:39:32.559Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by tanhakabir** [comment]
@roblourens just to clarify this is intended right? How would I clear the chart in this scenario?

**Comment by roblourens** [comment]
This is intended. The "Clear outputs" command would be under `...` and would clear all outputs
