### ISSUE TITLE
Allow other extensions to use `vscode.languages.registerInlayHintsProvider`

### ISSUE THREAD

**Issue by kitsonk** [microsoft/vscode#132197]
While vscode 1.60 shipped with Inlay Hints for the built-in TypeScript/JavaScript language service, `vscode.languages.registerInlayHintsProvider` still exists only in `vscode.proposed.d.ts` which means that other extensions that need to be published cannot leverage the proposed protocol, which seems a cruel arbitrary limitation.  It would be great if shipping features in built-in extensions are available to other extensions.

**Comment by jrieken** [comment]
duplicate of https://github.com/microsoft/vscode/issues/16221
