### ISSUE TITLE
`TypeHierarchyProvider` doc is unclear about depth of super/subtypes to return

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#132117]
Issue Type: <b>Bug</b>

Should `provideTypeHierarchySupertypes` return only immediate supertypes (i.e. the ones named in an Extends clause), or all supertypes in the hierarchy?

Ditto for `provideTypeHierarchySubtypes`

Relates to #15533

VS Code version: Code - Insiders 1.60.0-insider (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:40:58.134Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isc-bsaviano** [comment]
It would be great to get more clarification on this before the API is released.

**Comment by jrieken** [comment]
We have done that
