### ISSUE TITLE
Extensions can't write spec conform Jupyter notebook files

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#132174]
See https://github.com/julia-vscode/julia-vscode/pull/2424 over at the Julia extension for an explanation. I'm just opening an issue here as well to make sure this shows up in the standard VS Code issue tracking process.

**Comment by mjbvz** [comment]
Fixed by #132298

**Comment by davidanthoff** [comment]
And just FYI, we are testing a new build of our extension that uses this in our insider channel right now, will probably push it out to everyone tomorrow or the day after that :) Thanks a lot for the super quick turn around on this, much appreciated!

**Comment by TylerLeonhardt** [comment]
@davidanthoff is this working for you now? If so feel free to respond `/verified`

**Comment by IanMatthewHuff** [comment]
Using Julia extension saved files now have the metadata.language_info in them:
![image](https://user-images.githubusercontent.com/812783/135691740-1a091add-d73a-43b1-b949-5a16e6b826c2.png)
