### ISSUE TITLE
Don't allow running the empty string in the debug console

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#132130]
Repro:

1. Start a js-debug session
2. Press enter when no text is in the debug console input

![image](https://user-images.githubusercontent.com/2193314/131861680-69a8ef38-34e5-4a59-ba2a-b47876cef33d.png)

Browser devtools do nothing here which is better behavior imo.

**Comment by connor4312** [comment]
I think this is something that the REPL in core should ignore

**Comment by roblourens** [comment]
I believe this is on purpose for DAs where they want this to work like a terminal, like powershell.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/11350

**Comment by roblourens** [comment]
Is it annoying enough to let the DA specify which behavior it wants? I don't really think so
