### ISSUE TITLE
Make the "output" panel keyboard navigable

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode#132124]
Issue Type: <b>Bug</b>

It's currently possible to focus the outputs view (workbench.panel.output.focus) using a keyboard shortcut, but it isn't possible to navigate it with the keyboard (as in, select which outputs to view). 

There appears to be an action for it `workbench.output.action.switchBetweenOutputs`, but it doesn't do anything (hence my labeling of this as a bug report rather than a feature request - if that command is unrelated to what I want, then it's just a feature request :-) )

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-74-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.80GB free)|
|Process Argv|--crash-reporter-id 89aeed25-8dc2-46ce-b17c-1f93ab95c565|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: spidsmus.sdma.nzcorp.net|
|OS|Linux x64 5.4.0-74-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz (12 x 3092)|
|Memory (System)|58.88GB (25.36GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vscode-azurevirtualmachines|ms-|0.4.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-autohotkey|sle|0.2.2
vim|vsc|1.21.7
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.43.2
gitlens|eam|11.6.0
gc-excelviewer|Gra|3.0.43
githd|hui|2.2.4
rainbow-csv|mec|1.9.1
gitignore|mic|1.0.1
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.9.1-pre.1
jupyter|ms-|2021.8.1236758218
gremlins|nho|0.26.0
autodocstring|njp|0.5.4
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14

</details>

**Comment by gjsjohnmurray** [comment]
Does <kbd>Shift</kbd>+<kbd>Tab</kbd> move you from the Output area to the channel dropdown?

**Comment by ldorigo** [comment]
> Does Shift+Tab move you from the Output area to the channel dropdown?

No, but I re-mapped a lot of shortcuts, so might be because of that?

**Comment by sandy081** [comment]
Yes, tab / shift+tab should work. You can also navigate from quick pick as follows

- Open quick pick (cmd/ctrl+p)
- Type `view output`
