### ISSUE TITLE
Never translate code into VSCode display language

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode#132190]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Install a non-English extension and switch VSCode display language into that language.
2. Open "settings".
3. Type "inlay" in the search box.

As you can see, some keywords are translated into VSCode display language, which is not a correct syntax.
![屏幕截图 2021-09-03 095757](https://user-images.githubusercontent.com/62426149/131939679-528f9653-927d-4f66-87ad-caa65c351a8c.png)
![屏幕截图 2021-09-03 095818](https://user-images.githubusercontent.com/62426149/131939709-8acc5287-a496-4dae-aeed-902bec9fc765.png)

**Comment by mjbvz** [comment]
@danyeh I added comments in the `package.nls.json` about how these strings are used. I believe the localizations also need to be updated

**Comment by infinnie** [comment]
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/typescript-language-features.i18n.json

Incorrect translation is located here.

**Comment by TylerLeonhardt** [comment]
Now that the comment is added, it will go through the pipeline and should be fixed in the next 1 or 2 versions of the Language Pack.

**Comment by TylerLeonhardt** [comment]
Closing this since there is no more action besides waiting.
