### ISSUE TITLE
Why is vscode recommending a deprecated extension?

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#132153]
Issue Type: <b>Bug</b>

(Debugger for Chrome)

VS Code version: Code - Insiders 1.60.0-insider (8dbad73de575e47e127c8b1a4324f2b61257fbdc, 2021-08-27T21:27:11.911Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
bracket-select|chu|2.0.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
kusto|don|0.3.7
brackethighlighter|Dur|2.2.4
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
todo-tree|Gru|0.0.213
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-bicep|ms-|0.4.613
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.1
vscode-language-pack-de|MS-|1.60.2
csharp|ms-|1.23.15
dotnet-interactive-vscode|ms-|1.0.2431011
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
azure-account|ms-|0.9.8
powershell|ms-|2021.8.2
vscode-github-issue-notebooks|ms-|0.0.106
azurerm-vscode-tools|msa|0.15.2
vscode-versionlens|pfl|1.0.9
vscode-todo-highlight|way|1.0.4

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824cf:30353184
javagetstartedt:30350119
pythonvspyt187cf:30356035
pydsgst2:30356659

```

</details>

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/131900993-afc1afe8-2cae-4337-8f90-63ddc7e8a59f.png)
![image](https://user-images.githubusercontent.com/6913354/131901081-608179f7-fa8e-4f7a-8f5e-d9a6f5996d59.png)

**Comment by chrisdias** [comment]
good catch, thanks.  fixed.
