### ISSUE TITLE
Smooth scrolling with Ctrl+Up is very slow

### ISSUE THREAD

**Issue by ygoe** [microsoft/vscode#132165]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:

1. Enable smooth scrolling in the editor
2. Open a document that is longer than a single page and move the cursor to the end of it

Now press Ctrl+Up to scoll the editor up line by line. Keep it pressed, we want to scroll to the top of the document. Other editors usually do this very quickly, just as the typing/repetition speed of the keyboard (default is maximum). With smooth scrolling enabled, this is extremely slow. But only with Ctrl+Up. Ctrl+Down is fine. As is scrolling with the mouse wheel. Without smooth scrolling, it's also fine.

If it's relevant, here's the Ctrl+Up keybinding:

```json
	{
		"key": "ctrl+up",
		"command": "editorScroll",
		"when": "editorTextFocus",
		"args": 
		{
			"to": "up",
			"by": "line",
			"revealCursor": true
		}
	},
```

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/128956
