### ISSUE TITLE
New bracketPairColorization doesn't work with JSX

### ISSUE THREAD

**Issue by Puritanic** [microsoft/vscode#132164]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Big Sur 11.5.2

Steps to Reproduce:

1. Open any javascript file with some JSX in it, React or Next.js for example
2. Notice that tag openings and closings have messed up colors

![Screen Shot 2021-09-02 at 22 32 21](https://user-images.githubusercontent.com/25148427/131912235-72d249b2-f7d7-4ad5-864b-a1da8a70386e.png)

Not happening with HTML tags. I've been able to reproduce this in files with js and jsx extensions, both for Javascript Babel and Javascript React syntax highlighting.

**Comment by gjsjohnmurray** [comment]
@Puritanic which extension is handling these files on your VS Code? For example, maybe https://github.com/michaelgmcd/vscode-language-babel ?

I think the extension author needs to add the new `colorizedBracketPairs` setting to its language-configuration.json file. See #131405

Documentation for `colorizedBracketPairs` hasn't yet reached https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Comment by Puritanic** [comment]
@gjsjohnmurray That' correct. Looks like vscode-language-babel extension is causing issues :/ I'll open the issue there, sorry. Had no idea that these syntax flavors are not VSCode built-ins 😅
