### ISSUE TITLE
Visually distinguish fixes from non-fixes in lightbulb menu

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#132109]
When invoking the lightbulb menu on an error, the menu can include a mix of both fixes and non-fixes (eg. refactors) mixed together:

<img width="600" alt="Screenshot 2021-09-02 at 10 21 36" src="https://user-images.githubusercontent.com/1078012/131818754-7dd25330-c833-4725-912d-2a8452fa1cfe.png">

It would be good if there was some visual separation or indication of which of these are fixes for the diagnostic and which are not. For example in Android Studio I see the fixes have lightbulbs and non-fixes have pencil/edit icons:

<img width="388" alt="Screenshot 2021-09-02 at 10 25 09" src="https://user-images.githubusercontent.com/1078012/131819120-04443903-f1d8-407e-99d4-58b6dd3d3e16.png">

**Comment by lgrammel** [comment]
Hey I just tried out the new menu in insiders and it looks great!

I was wondering if you would consider adding 2 code action classes that are I think quite common:

* `refactor.inline` (Inline)
* `refactor.move` (Move)

This would be super valuable for the extension that I'm developing (P42 JavaScript Assistant), but I think also for other extension. Afaik the TS language server also has `refactor.move` actions for example.

**Comment by justschen** [comment]
@lgrammel Do you think you can provide examples of inline and move options and what those labels say?

ATM, I know there is a `Move to new file` code action, and I just have it lumped under `More Actions...`, but if inline and move are sufficiently different, I'd like to provide them with their own codicons as well!

**Comment by lgrammel** [comment]
@justschen Here are some examples from "Refactoring, 2nd Edition" (Fowler):

Inline:
* Inline Class
* Inline Function
* Inline Variable

Move:
* Move Field
* Move Function
* Move Statement into Function
* Move Statements to Callers
