### ISSUE TITLE
Git clone with SSH

### ISSUE THREAD

**Issue by salahooo** [microsoft/vscode#132126]
Please add easy way to connect to gitlab server or clone repo from gitlab with SSH like in intelji

**Comment by TylerLeonhardt** [comment]
Have you tried clicking the "Clone Repository" button and pasting that ssh url in:

![image](https://user-images.githubusercontent.com/2644648/131882774-02d8ac24-6527-4d0e-86ab-c11d55d1f899.png)
I know I specified github here but I think gitlab's should work too.
![image](https://user-images.githubusercontent.com/2644648/131882828-df8cfed8-01d2-44b2-8458-02b37558b36a.png)

**Comment by salahooo** [comment]
i have tried that but i get permissions denied 
> git clone git@xxxxxxxxxxxxxxxxxxxxxx --progress
git@xxxxxxxxxx Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by TylerLeonhardt** [comment]
@salahooo are you able to clone this repo outside of vscode just fine?

git clone git@xxxxxxxxxxxxxxxxxxxxxx
