### ISSUE TITLE
Dead key and then return key produces double character

### ISSUE THREAD

**Issue by BinaryHammer** [microsoft/vscode#132112]
Issue Type: <b>Bug</b>

### Description:
Some dead keys prints the character doubled (only in Visual Studio Code) when return is pressed next.

### Steps to reproduce:
1. Use macOS
2. Open Visual Studio Code
3. Create a new file
4. Select `U.S.` software keyboard layout
5. Press on US hardware layout <kbd>option</kbd> + <kbd>`</kbd>
6. Press <kbd>return</kbd>

### Expected:
The character ``  ` `` will be printed followed by a newline: `` `\n ``. Like it does when simply using the key <kbd>`</kbd>

Without pressing the additional <kbd>option</kbd> modifier (because then it is not a dead key). Since the dead key state is terminated by not using one of the keys that combine with the dead key <kbd>`</kbd>

It should just print ``  ` `` followed by the symbol that could not be combined with ``  ` ``. This is the normal behavior in any other app, like `TextEdit.app`.

### What happens:
The character `` ` `` will be printed two times followed by a newline: `` ` ` \n``.

### Notes:
It does not happen with option + u, there it always prints ¨ just once, even though this is also a dead key. Custom set dead keys do always have this problem.

### System:
macOS Big Sur 11.5.2 on MacBook Pro

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|79, 25, 11|
|Memory (System)|16.00GB (4.06GB free)|
|Process Argv|--crash-reporter-id 22e78f52-d1d7-4c5d-8c9a-855d201de122|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
I can reproduce this in any `<textarea>` in Chrome and Edge, so this is an upstream issue. 

When pressing <kbd>option</kbd>+<kbd>\`</kbd>, followed by <kbd>Enter</kbd>, I get ``` `` ``` instead of `` `\n ``.

Please report this upstream at https://bugs.chromium.org/p/chromium/issues/list

https://user-images.githubusercontent.com/5047891/143960520-2537b2f1-3d6a-47dc-9bd9-63f6169c867f.mp4
