### ISSUE TITLE
Open in Integrated Terminal opens PowerShell instead of WSL

### ISSUE THREAD

**Issue by cameronandrews** [microsoft/vscode#132198]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.6
- OS Version: Windows 10

Steps to Reproduce:

1. Open folder which has subfolders from WSL in VS Code,
2. Set default terminal to WSL
3. Right-click on a subfolder in the left sidebar and click "open in integrated terminal"
4.  Opens it in PowerShell instead of WSL

**Comment by kohane27** [comment]
https://github.com/microsoft/vscode/issues/128763
I can report that I'm having the same issue. Rolled back to 1.59 and default shell as Git Bash works again. I also added "update.mode": "none" to settings.json

**Comment by gjsjohnmurray** [comment]
Probably #132149

**Comment by thesethtruth** [comment]
Can confirm that I'm having exactly the same issues as of version 1.60.

**Comment by andriychuma** [comment]
Same issue in version 1.60.0. I set up Git Bash as the default profile, but while opening a folder in the integrated terminal via the context menu, PowerShell gets open.

**Comment by patrickhlauke** [comment]
same here

**Comment by patrickhlauke** [comment]
is it a duplicate though? i've explicitly set wsl as my default, and it's showing as such in settings and even in the terminal dropdown, and opens wsl correctly when I just hit the "+" for a new terminal. it's just that first time around (when opening VSCode, or when switching to a different folder) it invariably opens a powershell one regardless of the default being clearly set to wsl (i.e. ignores the default)

**Comment by rahul-soshte** [comment]
Yes I am facing the same issue, since last 2 days, earlier it was working
