### ISSUE TITLE
Python breakpoints stopped working

### ISSUE THREAD

**Issue by bagofmice** [microsoft/vscode#132148]
Issue Type: <b>Bug</b>

I updated to the new version below, and I can't hit any breakpoints after being told I have to switch to pylance or jedi.
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.58GB free)|
|Process Argv|--crash-reporter-id 935c2ce9-af9d-4331-b6a1-6166e321e72f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.3
swagger-viewer|Arj|3.1.2
azps-tools|azp|0.1.0
azurepolicyextension|Azu|0.2.0
language-prometheus|caa|0.1.2
rapid-json-search|dat|0.1.6
xml|Dot|2.5.1
gitlens|eam|11.6.0
json-tools|eri|1.0.2
vscode-diff|fab|1.4.2
opensslutils|ffa|1.1.1
terraform|has|2.14.0
json-escaper|jos|1.1.2
vscode-jmespath|jos|0.0.6
kusto-syntax-highlighting|jos|1.0.1
eml|lei|0.4.0
rainbow-csv|mec|1.9.1
file-downloader|min|1.0.11
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
vscode-edge-devtools|ms-|1.3.0
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell|ms-|2021.8.2
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.2
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.6.1
json-parse-stringify|nex|1.0.2
vscode-vault|owe|2.2.3
vscode-thunder-client|ran|1.9.1
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
swagger-tools|The|0.5.0
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.14
application-insights|Vis|0.4.2
vscode-java-debug|vsc|0.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn420:30356812
vscus224cf:30358040

```

</details>

**Comment by TylerLeonhardt** [comment]
\extPython
