### ISSUE TITLE
All my terminals are gone and I can't get rid of the defaults

### ISSUE THREAD

**Issue by promethyttrium** [microsoft/vscode#132178]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install VS Code Update
2. Ctrl + Shift + `  to Open Terminal 
3. Terminal dropdown is only "PowerShell", "Command Prompt" and "Javascript Debug Terminal". No idea where these came from but my git-bash is gone.
4. Clicking "Configure Terminal Settings" just gives the useless UI Settins about Automation Shells and whatever. Editing settings.json doesn't show any of the above choices (I don't want those). I can't get rid of those and I can't add new ones.
5. Only recourse is uninstall and change career.

**Comment by pebeid** [comment]
Same issue here. Same windows and VS Code Version as @promethyttrium 

For more info, I have put below the image of my settings, and the terminal error resulting:

![image](https://user-images.githubusercontent.com/48051935/131943853-0b600a77-fdad-4b94-a745-5a808c4c5dd7.png)

**Comment by tao-cumplido** [comment]
"JavaScript Debug Terminal" ignores every default profile setting (new and deprecated) and always uses PowerShell on Windows now

**Comment by dolphin17** [comment]
try add new and set  like this
![image](https://user-images.githubusercontent.com/8563317/131979801-1bfa4417-f38b-46b5-8dae-96d96a4809a9.png)
![image](https://user-images.githubusercontent.com/8563317/131979855-6575f4cc-c935-4a03-8fe7-42a1dcc915cc.png)
![image](https://user-images.githubusercontent.com/8563317/131980050-681676f8-75d0-4e62-9ede-c3100d1a7fce.png)

**Comment by debadeepta** [comment]
Same for me. I change default back to Command Prompt but on opening a new window, VS Code starts a PowerShell terminal. This is extremely annoying and is breaking all workflows at the moment.

**Comment by meganrogge** [comment]
will be fixed in insider's tomorrow and in the recovery build this week /duplicate #132150
