### ISSUE TITLE
no option to use in command line for developers, had add it to env myself

### ISSUE THREAD

**Issue by balaarunreddyv1** [Microsoft/vscode#13218]
- VSCode Version: 
- OS Version: win-81

Steps to Reproduce:
Install and you need to import  code manually. devs are used to git bash or terminal, need to open files or folders from bash or teminal.

**Comment by joaomoreno** [comment]
What do you mean by the following?

> need to import code manually

If you run `code` from the command line, it should open.

**Comment by balaarunreddyv1** [comment]
apologizes my mistake was able to open code from cmd.

I was just saying that i couldn't open the code from cmd and I had to add it to system environment variables.
