### ISSUE TITLE
Broken link in setting description

### ISSUE THREAD

**Issue by sharedrory** [microsoft/vscode#132181]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:

1.Open settings editor
2.Goto `editor.inlayHints.fontFamily`
3.
![image](https://user-images.githubusercontent.com/85806407/131933585-0394ab88-7fcd-45b1-99af-db67915caacb.png)

Shouldn't that setting in the description be a clickable jump-to link?

**Comment by sharedrory** [comment]
Found another one 
![image](https://user-images.githubusercontent.com/85806407/132058882-d8e0e0aa-8a55-472d-8f21-6ab219f6134a.png)
Same vscode version

**Comment by jrieken** [comment]
This is now fixed
