### ISSUE TITLE
Language pack recommendation prompts on every start

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#132139]
STR:
1. Open VS Code with locale set `code --locale=es`
2. Wait for language prompt and close it
3. Close VS Code and repeat 1st step

🐛 Language prompt shows again.

[localizations](https://github.dev/microsoft/vscode/blob/e43c252ee04fe74e6aecf14bbb8c75de42b91f30/src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts) has logic for storing an ignore key after a prompt was shown, but is using the wrong key (_language_ instead of _locale_). The same variable mixup has caused prior breakage of the feature.

**Comment by isidorn** [comment]
Forwarding to @TylerLeonhardt since he owns localization.

**Comment by sandy081** [comment]
I partly own localizations support in VS Code especially recommending. 

@digitarald It seems you come up with a fix. Do you mind opening a PR?

**Comment by sandy081** [comment]
Ignore above comment, I see the PR now.

**Comment by mjbvz** [comment]
I'm still seeing this in insiders

I clicked the `x` on the notification and then restarted. After a few seconds, the prompt came up again

**Comment by digitarald** [comment]
Found it. Only "Don't show again" triggers that logic, but just canceling doesn't.

I wonder what the right behavior should be. Other buttons also depend on "Don't show again" for a similar logic and otherwise pop up again on next launch. cc @misolori for guidance.

**Comment by sandy081** [comment]
Clicking `x` is never meant to be not to show again and user has to explicitly select `Don't show again` action. I think this is general behavior for all prompts. I would recommend to discuss this UX change separately and mark this as verified otherwise.

**Comment by rzhao271** [comment]
Marking as verified based on comments above
