### ISSUE TITLE
Notebooks do not respect editor.mouseWheelScrollSensitivity setting

### ISSUE THREAD

**Issue by DavidZidar** [microsoft/vscode#132155]
Mouse wheel scrolling in notebooks is more or less unusable because `editor.mouseWheelScrollSensitivity` is not respected.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10, 21H1

Steps to Reproduce:

1. Set `editor.mouseWheelScrollSensitivity` to a bigger value than 1, like 5
2. Use scroll wheel in a Notebook, compare with a regular code window

**Comment by rebornix** [comment]
The notebook editor is a list view component so you can use `workbench.list.mouseWheelScrollSensitivity` to update its scrolling sensitivity.

**Comment by DavidZidar** [comment]
@rebornix Wow, that is super unintuitive. But thank you for the response, it works!
