### ISSUE TITLE
Disable "Next Conflict" icon on the last conflict

### ISSUE THREAD

**Issue by eladcandroid** [microsoft/vscode#132106]
When clicking "Next Conflict" (Down arrow icon):
![image](https://user-images.githubusercontent.com/13297000/131813132-ba95c290-85f0-485f-9770-a3745396b76e.png)

Instead of showing this message:
![image](https://user-images.githubusercontent.com/88163261/131812213-ea18c76d-5f46-401e-8a61-a5d142fc9636.png)

Just disable the button, or auto cycle to the first one...

**Comment by eamodio** [comment]
I believe we mainly do this today, as it would be more expensive to figure that out ahead of time.
