### ISSUE TITLE
Duplicate clear commands

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#132137]
I keep forgettign which one works & which doesnt

![Screen Shot 2021-09-01 at 15 48 45](https://user-images.githubusercontent.com/1948812/131755430-9527802a-8a80-43f1-b7f0-6ad0d96a6238.png)

**Comment by rebornix** [comment]
I updated this to `Clear Outputs of All Cells` to better reflect the purpose of that command.
