### ISSUE TITLE
The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-7476659.821891487-in').

### ISSUE THREAD

**Issue by miyuehu** [microsoft/vscode#132105]
Open VSCode(Version: 1.59.1) ----> "Help" ----> "About"
```
Version: 1.59.1 (system setup)
Commit: 3866c35
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Open VSCode ----> "Terminal" ----> "New Terminal"**
There are always errors, error messages:

> The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\.\pipe\conpty-7476659.821891487-in').

Reinstall the old software version（VSCode VSCodeSetup-x64-1.52.1.exe），Open Terminal is ok

**Comment by miyuehu** [comment]
Open VSCode(Version: **1.59.1**) ----> "Help" ----> "About"
Version: 1.59.1 (system setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Open VSCode ----> "Terminal" ----> "New Terminal"**
There are always errors, error messages:
The terminal process failed to launch: A native exception occurred during launch (EBUSY: resource busy or locked, open '\\.\pipe\conpty-7476659.821891487-in').

Reinstall the old software version（VSCode VSCodeSetup-x64-1.52.1.exe），Open Terminal is ok

**Comment by miyuehu** [comment]
WSL is OK
```
C:\Users\yuehu.mi> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         2
```

**Comment by miyuehu** [comment]
Process Name  ptyHost
![image](https://user-images.githubusercontent.com/1926079/131819584-32ff32ee-99ca-4c2d-8dd0-4eacf2c38998.png)

**Comment by miyuehu** [comment]
Video of operation terminal failure
https://user-images.githubusercontent.com/1926079/131940440-b204dafa-8bd5-4b25-8c71-8b56fc3954f9.mp4

**Comment by miyuehu** [comment]
@vscode-triage-bot @mojodna @doudou @threeve can you help me?

**Comment by miyuehu** [comment]
Update to the latest version：Version: 1.60.0 (system setup)。There are still problems

![image](https://user-images.githubusercontent.com/1926079/132155745-10f03e75-6897-4220-96d1-2478ec51047f.png)

**Comment by meganrogge** [comment]
Please see https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
