### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by Hollow-R** [microsoft/vscode#132159]
![image](https://user-images.githubusercontent.com/88184672/131908990-eaa0779c-7bf5-4c9f-8620-4ee2c4b310e7.png)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version:

Steps to Reproduce:

1.
![resim_2021-09-02_230659](https://user-images.githubusercontent.com/88184672/131909068-7285693c-c47f-46a0-abbd-c90a74c96589.png)

how do i fix this ? (sorry i dont really know how to use github)

2.

**Comment by AdhTri-001** [comment]
See my #132161 issue. Something wrong with the terminal this update.

**Comment by TylerLeonhardt** [comment]
@AdhTri-001 I think your issue is different.

**Comment by deepak1556** [comment]
Can you provide the vscode version and os info, thanks!

**Comment by Hollow-R** [comment]
my vs code version is 1.60.0 and this thing happened right after i updated it OS is windows student

**Comment by deepak1556** [comment]
Can you launch with `code --user-data-dir <dir> --verbose` and provide the output. Replace `<dir>` with some absolute writable directory path.

**Comment by Hollow-R** [comment]
> Can you launch with `code --user-data-dir <dir> --verbose` and provide the output. Replace `<dir>` with some absolute writable directory path.

sorry im kinda new to all that stuff, where do i enter this code. thanks for the help btw

**Comment by deepak1556** [comment]
1) Open any console on the system, command prompt or powershell or windows terminal
2) Enter the above command
3) Wait for application to load and then copy the data from the terminal output

**Comment by Hollow-R** [comment]
Error: Cannot find module 'C:\Users\Sun Bilgisayar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []


this is the terminal output, sry i looked what does --user-data-dir means thats why it taked too long

**Comment by deepak1556** [comment]
Looks like a corrupted install, can you reinstall and try again.

**Comment by Hollow-R** [comment]
I installed an older version and it solved thanks for your help : )

**Comment by deepak1556** [comment]
Can you perform and update to see if the issue persists with newer updates.
