### ISSUE TITLE
Incorrect text rendering in firefox

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode#132186]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.60.0
- Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
- Date: 2021-09-01T10:49:24.188Z
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

See the screenshot letter spacing. Especially, the 'o'.
If I toggle off the css 'letter-spacing: .25px', then it become correct.
https://github.dev/nodejs/undici
![图片](https://user-images.githubusercontent.com/54468/131938986-92dbe7b9-344f-45c0-9b75-7264ce30d780.png)

**Comment by connor4312** [comment]
This duplicates https://github.com/github/codespaces/issues/1718

**Comment by heroboy** [comment]
> This duplicates https://github.com/github/codespaces/issues/1718
But I can't access this.

**Comment by connor4312** [comment]
GH fixed this a little while back
