### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Beoo-666** [microsoft/vscode#132120]
To make it easier to view, please add an icon to the folder.
Please add a line to the files between the top-level directory and the sub-directory to distinguish them.
![image](https://user-images.githubusercontent.com/55978588/131840019-ee730794-b7be-4c18-a75f-60ba653c0c61.png)

**Comment by IllusionMH** [comment]
Seti icon theme doesn't have folders intentionally - please install any other file theme that contains folder icons.

**Comment by Beoo-666** [comment]
I like the default theme, I can’t accept its changes to other content if I change the theme @IllusionMH

**Comment by CodeCrazy-ywt** [comment]
其实可以实现的哈，
1. 进入“设置”
2. 点击“工作台” -> “外观”，然后一直往下滑，找到“控制树是否应呈现缩进参考线”
3. 点击下拉框，选择`always`。就可以了。
![屏幕截图 2021-09-03 155825](https://user-images.githubusercontent.com/62426149/131972005-4ebb6e69-f98a-46e0-80de-e8e3b113486a.png)

---
Actually you can do it.
1. Go to "settings"
2. Click "Workbench" -> "Appearance", swipe the page until you see `workbench.tree.renderIndentGuides`
3. Choose `always` from the drop-box. That's ok.
