### ISSUE TITLE
vscode dies when reopening a crashed window

### ISSUE THREAD

**Issue by jeffory-orrok** [microsoft/vscode#132154]
Issue Type: <b>Bug</b>

Since the last macos upgrade, vscode has been crashing several times a day; usually it starts with one window crashing with different codes (such as 5) and then when I click the reopen button, the entire app dies.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 9de7534c-9999-461f-8888-24c5224ca9cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
unsaved|esa|0.2.5
color-tabs-vscode-ext|ore|0.12.1
mongo-snippets-for-node-js|roe|1.3.10
vt100-syntax-highlighting|Tob|1.0.1
unsaved-files-vscode|wra|2.1.1
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn321cf:30356811
vscus224:30358039

```

</details>

**Comment by deepak1556** [comment]
Can you attach the crash report following these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by jeffory-orrok** [comment]
73638e50-af44-4059-8658-181dd73d7567.dmp

fa63b46b-ef9c-49a5-8d3b-69590cdb53aa.dmp

**Comment by deepak1556** [comment]
The files are not uploaded, might want to compress and attach them

**Comment by jeffory-orrok** [comment]
gee github doesn't support .dmp  how stupid

[pending.zip](https://github.com/microsoft/vscode/files/7102221/pending.zip)

**Comment by jeffory-orrok** [comment]
It crashed again this morning, but there are no new dump files

**Comment by deepak1556** [comment]
Can you start with `--disable-features="ParkableStringsToDisk"` and see if the crash happens. Also can you clarify if you are running vscode from a mounted volume ?

**Comment by jeffory-orrok** [comment]
Not sure whether I should continue using --crash-reporter-directory on each launch.

Here is how I just started vscode and the response I got
```
code --crash-reporter-directory /Users/jeff/vscode_crash.d --disable-features="ParkableStringsToDisk"
Warning: 'disable-features' is not in the list of known options, but still passed to Electron/Chromium.
```
As far as I know, vscode is just installed on my hard drive like any other app.

```
which code
/usr/local/bin/code
"Jeffory-Orrok's-MacBook-Pro":vmware_vro jeff$ df
Filesystem     512-blocks      Used  Available Capacity iused      ifree %iused  Mounted on
/dev/disk1s1s1 1953595632  29948448 1671135960     2%  553781 9767424379    0%   /
devfs                 398       398          0   100%     690          0  100%   /dev
/dev/disk1s5   1953595632  10485816 1671135960     1%       5 9767978155    0%   /System/Volumes/VM
/dev/disk1s3   1953595632    904416 1671135960     1%    2046 9767976114    0%   /System/Volumes/Preboot
/dev/disk1s6   1953595632      4304 1671135960     1%      19 9767978141    0%   /System/Volumes/Update
/dev/disk1s2   1953595632 239487568 1671135960    13% 4356339 9763621821    0%   /System/Volumes/Data
map auto_home           0         0          0   100%       0          0  100%   /System/Volumes/Data/home
```

**Comment by deepak1556** [comment]
> Here is how I just started vscode and the response I got

You can ignore the warning, does it still crash ?

> Not sure whether I should continue using --crash-reporter-directory on each launch.

Only till we confirm the issue, after that it can be removed.

**Comment by jeffory-orrok** [comment]
[pending.zip](https://github.com/microsoft/vscode/files/7110566/pending.zip)

**Comment by jeffory-orrok** [comment]
[pending.zip](https://github.com/microsoft/vscode/files/7110568/pending.zip)

Now it is crashing pretty much immediately upon startup.  Saw a couple code 5 and one code 10

**Comment by jeffory-orrok** [comment]
[pending.2.zip](https://github.com/microsoft/vscode/files/7110577/pending.2.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, most of the reports points to crash in the parkable strings feature and there are some v8 GC crashes as well. Very likely a bad code cache state, lets try with a fresh user data dir,

1) Close all running instances of vscode
2) `code --user-data-dir /tmp/vscode-test --disable-features="ParkableStringsToDisk" --crash-reporter-directory /Users/jeff/vscode_crash.d`
3) If crash happens, please attach the logs.
