### ISSUE TITLE
Destructuring fails as first line of Node program but not otherwise

### ISSUE THREAD

**Issue by countergram** [Microsoft/vscode#13216]
- VSCode Version: 1.5.3
- OS Version: OS X 10.11.5
- Node version: 6.5.0

Steps to Reproduce:
1. Start in empty directory and add an index.js file as follows

```
const [foo, bar] = [1, 2]
```
1. Run the debugger (set up launch.json and continue)

```
(function (exports, require, module, __filename, __dirname) { const [foo, bar] = [1, 2];
                                                                     ^
TypeError: Cannot read property 'next' of undefined
    at Object.<anonymous> (/Users/jstitt/n/index.js:1:70)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:590:10)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```
1. Run index.js from command line with node. Error does not occur.
2. Add a line before this (e.g. `console.log('hello')` and re-run. Error does not occur in either VSCode Debug or command line node.

**Comment by waderyan** [comment]
This is very interesting. @weinand can you advise on this issue? 

Note that OP is using Node 6.5.0.

**Comment by widmoser** [comment]
I have the same issue in node 6.6. When I insert the line before like described by @countergram, I still get the error, when the break-point is placed at the line of the deconstruction.

![image](https://cloud.githubusercontent.com/assets/185609/19233848/618d3ef0-8ee8-11e6-850f-1240bde2a0ac.png)

**Comment by weinand** [comment]
This is a a strange interaction between node's '--debug-brk' flag, an 'evaluate' that VS Code sends to configure the debug session and the destructuring feature.
I have not yet found a way to fix it, but workarounds exist.
(And you can use the experimental node2 debugger).

**Comment by guyellis** [comment]
Workaround for the current (at May 2, 2017) version of VSCode is to add:

```
      "protocol": "inspector",
```

to your launch.json project.

**Comment by weinand** [comment]
Should be fixed in tomorrow's Insiders build.
