### ISSUE TITLE
Search-bar broken

### ISSUE THREAD

**Issue by pwbarclay** [microsoft/vscode#132277]
Issue Type: <b>Bug</b>

Attempting to search for anything using the search-bar (not ctrl-f, the search all files utility) results in error message:

spawn
c:Users\NAME\AppData\Local\MicrosoftVSCode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.70GB free)|
|Process Argv|--folder-uri file:///d%3A/VTAKU/frontend --crash-reporter-id b8b8893c-477b-4cc4-acc7-be4d890c7cc3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
cpp-extentions-pack|bou|0.3.0
c-cpp-compile-run|dan|1.0.14
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
vscode-graphql|Gra|0.3.18
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
ruby|reb|0.28.1
youcompleteme-vscode|Tom|0.4.6
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn321cf:30356811
pydsgst2:30361792
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by ArturoDent** [comment]
Do you have anything in the "files to include" input filter?  I can get that error sometimes.

**Comment by pwbarclay** [comment]
> 
> 
> Do you have anything in the "files to include" input filter? I can get that error sometimes.

The problem persists even with various files in the include field.

**Comment by JacksonKearl** [comment]
It looks like the binary for ripgrep (the utility we use for full text searching) is missing from your install. This could perhaps be from some sort of antivirus? You could try reinstalling the application to see if that helps.

cc @roblourens

**Comment by roblourens** [comment]
You may also have a folder in your workspace which doesn't exist

**Comment by pwbarclay** [comment]
Uninstalling and reinstalling corrected this issue.
