### ISSUE TITLE
Make built in terminal searchable

### ISSUE THREAD

**Issue by markchagers** [microsoft/vscode#132244]
Issue Type: <b>Feature Request</b>

VSCode MacOS
Currently the built in terminal window is not searchable. With lots of output (e.g. when linting a large project for the first time) having search functionality would be really useful. I have tried redirecting the terminal output to a file, that makes the output searchable, but then the links to open file locations (which are really helpful in the terminal) do not work.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
/needsMoreInfo
Integrated terminal already has Find functionality. See https://code.visualstudio.com/docs/editor/integrated-terminal#_find

Have you tried it? Or provide examples that don't work now.

**Comment by CodeCrazy-ywt** [comment]
@IllusionMH Yes, we can do it by pressing Ctrl+F. But this functionality is not visible enough.
@vscode-triage-bot No, I don't think this issue lacks basic info though.
