### ISSUE TITLE
" ṇ " This symbol appears when we try to run a Program

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#132254]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8)
- OS Version: win32(10.0.19043)

Steps to Reproduce:

1. Open any C code file in VSCode
2. Hit ctrl + alt + n

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you nave non-US keyboard layout? Do you see same symbol if you type text in browser or somewhere else?
Where does this shortcut came from? It's not default

Check that it actually exists in Keyboard shortcuts and you invoke it from place that satisfices `when` conditions.

Also check https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings to see if VS Code receives this shortcut.

**Comment by tymsai** [comment]
1. QWERTY Keyboard
2. NO, This happens only in VSCode
3. This shortcut is used to run programs
4. 
![image](https://user-images.githubusercontent.com/76956612/132009874-e3bca159-f084-4105-9219-a5aaa83b70a0.png)

**Comment by IllusionMH** [comment]
Then go to troubleshoot steps

**Comment by tymsai** [comment]
> Then go to troubleshoot steps

any link ? :-)

**Comment by IllusionMH** [comment]
> Check that it actually exists in Keyboard shortcuts and you invoke it from place that satisfices when conditions.
> 
> Also check https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings to see if VS Code receives this shortcut.

In addition check that there are no other extensions/actions that use same shortcut.

**Comment by lramos15** [comment]
This seems like a keybinding collision issue so closing for now, if you have no keybinding collisions and still an issue let me know
