### ISSUE TITLE
1.61.0-insider (aec6ee0) (Sept/03) crashes immediately after launch

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#132278]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.61.0-insider
aec6ee09fa1021cb59c7f4f4d000b027febc967d
x64
- OS Version:
Microsoft Windows [Version 10.0.19042.1165]

Steps to Reproduce:

1. Open VS Code from start menu
2. The window name "flashes" on the taskbar and disappears.

This begin right after insiders updated today to the latest version. I've tried running code-insiders --disable-extensions, but nothing changed.

**Comment by IllusionMH** [comment]
Do you have `"window.menuBarVisibility": "toggle"`?

Probably duplicate of #132238 - see workaround in issue.

**Comment by bruno-brant** [comment]
@IllusionMH correct, that's the root cause.
