### ISSUE TITLE
Allow code --folder-uri to ignore path/to/directory from command line

### ISSUE THREAD

**Issue by ashrauma** [microsoft/vscode#132265]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: any
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Run vscode-server somewhere https://github.com/cdr/code-server
2. Execute (cmd.exe), `code --folder-uri vscode-remote://ssh-remote+{host}:{port}`

This works `code --folder-uri vscode-remote://ssh-remote+{host}:{port}/path/to/directory`.

**Comment by joaomoreno** [comment]
We do not support code-server.
