### ISSUE TITLE
python debugging script will not now use command as terminal. It opens a pwershell terminal instead.

### ISSUE THREAD

**Issue by pbs-websuntangled** [microsoft/vscode#132264]
Issue Type: <b>Bug</b>

It was working fine until vscode restarted and updated to the August 2021 edition. 

From that point debug would only open a pwershell terminal

The default terminal was also changed to powershell 

I reverted that back to command termional and now opening a new terminal works as expected 

But debug still only opens pwershell terminal

I downgraded to July 2021 version and that now behaves in the same problematic way (debugging python only opens in powershell) 

I cannot start using powershell terminals because I use anaconda to manage python environments and powershell refuses to activate anaconda environments 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor  (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.43GB free)|
|Process Argv|--crash-reporter-id 62687609-2214-4260-a68c-e81d20dfa052|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.18
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
vscode-3dviewer|sle|0.2.2
vscode-arduino|vsc|0.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187cf:30361754
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by gjsjohnmurray** [comment]
Probably the same root cause as #132149

I'm guessing there'll be a recovery build to fix this.

**Comment by ssoworld** [comment]
If you kill the terminal, then do ctrl+`, it will load your desired default

**Comment by Duoquote** [comment]
Same issue here, in my config:
```json
{
  ...
  "terminal.integrated.defaultProfile.windows": "Command Prompt",
  ...
}
```
It is defined as `Command Prompt` and opening a terminal works just fine but when I try to run my django launch configuration with conda environment:
```json
{
      "name": "Django: Server",
      "type": "python",
      "request": "launch",
      "program": "${workspaceFolder}/location-getty-server/manage.py",
      "args": [
        "runserver"
      ],
      "django": true
}
```
It's unable to activate conda environment because of powershell path things:
![image](https://user-images.githubusercontent.com/16341937/132072978-404ad504-c327-4e93-870c-b55fa626ac5c.png)

So I am fully unable to use debug mode, also been trying to get conda working with powershell for the last 3-4 hours... Wondering how long will that issue last.
