### ISSUE TITLE
Return key is ignored a couple of times before being accepted.

### ISSUE THREAD

**Issue by RonaldAi** [Microsoft/vscode#13226]
- VSCode Version: 1.5.3
- OS Version: Windows 10 (insider preview build 14939)

Steps to Reproduce:

1. open C document
2. switch away from VSCode, wait a few seconds
3. switch back to VSCode
2. press return/enter key and no new line is started, keep pressing until new line appears, then works normally until switching away again.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12929
