### ISSUE TITLE
Module Not Recognized

### ISSUE THREAD

**Issue by AaravAgarwal1** [microsoft/vscode#132252]
Issue Type: <b>Bug</b>

I am trying to import opencv to use cv2, it says requirement already satisfied but when I write any program using it it says cv2 not recognized. I am quite bugged with this issue, kindly fix it.

**Comment by lramos15** [comment]
If your code doesn't run at all then it is most likely not a problem with VS Code as we don't execute your code in any special way. Is it just not offering completions?

**Comment by lramos15** [comment]
Closing due to lack of update

**Comment by AaravAgarwal1** [comment]
I am sorry for not replying to the mail, apparently I missed ur msg
somehow…however, the problem’s now has been resolved. VS code is working
properly now :) thank you so much for the assistance, really appreciate it!
