### ISSUE TITLE
Run tasks using cmd.exe instead of powershell

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode#132241]
Since the august update, the tasks are running automatically in powershell, and i makes some of my scripts deprecated.

I have tried to use the setting `"terminal.integrated.defaultProfile.windows": "Command Prompt"` but it doesn't change anything for the tasks and they are still ran inside powershell.

I believe this is a bug. But is there an option that you have just added to select cmd.exe (msdos) for the executable running the tasks?

**Comment by capraynor** [comment]
Default terminal also not works for me after an upgrade.

**Comment by TarunavBA** [comment]
> Since the august update, the tasks are running automatically in powershell, and i makes some of my scripts deprecated.
> 
> I have tried to use the setting `"terminal.integrated.defaultProfile.windows": "Command Prompt"` but it doesn't change anything for the tasks and they are still ran inside powershell.
> 
> I believe this is a bug. But is there an option that you have just added to select cmd.exe (msdos) for the executable running the tasks?

@bonjourjoel Try giving the path of Command Prompt in `terminal.integrated.defaultProfile.windows": "path to Command Prompt"`
Change the `path to command prompt` to path where your command prompt is located.

**Comment by bonjourjoel** [comment]
> 
> @bonjourjoel Try giving the path of Command Prompt in `terminal.integrated.defaultProfile.windows": "path to Command Prompt"`
> Change the `path to command prompt` to path where your command prompt is located.

Thanks but it doesn't work. The powershell is still used to start the tasks.

And also, the setting seems refused by vs code: It raises the error: `Value is not accepted. Valid values: "PowerShell", "Command Prompt", "Git Bash", "JavaScript Debug Terminal".`

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #132149

**Comment by meganrogge** [comment]
will be fixed in the recovery release, duplicate of #132150
