### ISSUE TITLE
Expose alias type in intellisense

### ISSUE THREAD

**Issue by Davilink** [microsoft/vscode#132285]
I would like to also see the type alias in the Intellisense

Example:
Instead of having this:

![image](https://user-images.githubusercontent.com/1498932/132047844-69d78437-1ac9-470f-a70f-adf167720f41.png)

having something like that:

![image](https://user-images.githubusercontent.com/1498932/132048435-b6b36132-a4ae-4fd7-8493-b70be3e16908.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by Davilink** [comment]
Sorry, my bad. After looking in the typescript repo, i found out that an issue already exist (if anyone else want to know): 
 https://github.com/microsoft/TypeScript/issues/31940
