### ISSUE TITLE
need more hint about the wrong use of local variable

### ISSUE THREAD

**Issue by bing1zhi2** [microsoft/vscode#132273]
Issue Type: <b>Feature Request</b>

``` python
for i in range(10):
    aaa = 3234

for i in range(10):
    print(aaa)
```
I except vscode can tell me something like  "local variable aaa might be referenced before assignment", but nothing happend!   I had try pylint and open all the hints , but still can't get what I want

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by IllusionMH** [comment]
/extPython

VS Code doesn't provide support for Python(I assume from code) out of the box.
Make sure that you have proper extensions installed and enabled corresponding checks.

If there are no configuration - request should be reported in extensions repo

**Comment by bing1zhi2** [comment]
> /extPython
> 
> VS Code doesn't provide support for Python(I assume from code) out of the box.
> Make sure that you have proper extensions installed and enabled corresponding checks.
> 
> If there are no configuration - request should be reported in extensions repo

ok ,thanks~
