### ISSUE TITLE
Add filters in settings which shows only the newly-added settings since the last update

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#132257]
I propose a button to be added to the settings. It's action may be implemented as a filter. Upon click of that button it would show all the new settings and settings with new possible values to select since the last updates.

For example:

1. You update VS Code three times but you don't check what new settings there are. 
2. Then you decide to check out and click this button. This filters the settings and shows you all the new settings from the last 3 versions.
3. Then an update to VS Code happens. Now you can again click this button once updated to see the new settings from the last 1 version.
4. Now say 4 updates to VS Code happen but you haven't checked what new settings there are for the last 3 updates. But after the 4th update you remember to check. When you check, the new settings from the last 4 updates are shown.

**Bonus:** This button shows up in some visible place (say like the same way the "Add configuration" button shows up in "launch.json") when you haven't checked and there are new settings from updates.

**Comment by roblourens** [comment]
Thanks for the suggestion. We have actually discussed this before, and decided against it. We think that the release notes is the right place for this where we can show new settings in context of the feature area, with extra explanation, etc.

Here are some other issues https://github.com/microsoft/vscode/issues/107831 https://github.com/microsoft/vscode/issues/45093
