### ISSUE TITLE
Give us settings to disable restart debugging modal confirmation dialog

### ISSUE THREAD

**Issue by iamwwc** [microsoft/vscode#132201]
I'm using shortcut to restart debug process everytime. I think the aim of shortcuts is to quick control vscode behaviour. 
**I'm know what happened after pressing shortcut key.**

But the latest update come with a `modal confirmation dialog` when I press F4, Now I need press additional `Enter` to tell vscode `Yes`

> When starting another instance of a debug session that is already running, there is now a modal confirmation dialog to prevent accidentally starting two sessions.

![image](https://user-images.githubusercontent.com/24750337/131943277-dd486514-56e7-4199-9d0a-26f4cbac8fc3.png)

I have to rollback previous vscode version, and disable vscode update forever to avoid useless pressing.

**we want to having a new setting to totally disable latest feature `modal confirmation dialog`**

> Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

My shortcut

> {
        "key": "f4",
        "command": "workbench.action.debug.start",
        "when": "!inDebugMode"
    },
    {
        "key": "f4",
        "command": "macros.restart",
        "when": "inDebugMode"
    },

**Comment by iamwwc** [comment]
@weinand could you watch this?

**Comment by weinand** [comment]
Did you try the "Restart" command for restarting your debug session? It will terminate the running session and start it again. So you can be sure that there is only one session running.

If you use "F5" it starts a session without terminating the previous session. So if you see the dialog, that means that your previous session hasn't terminated yet and you will end up with two (or more) sessions. Is this really your intention?

**Comment by iamwwc** [comment]
> Did you try the "Restart" command for restarting your debug session? It will terminate the running session and start it again. So you can be sure that there is only one session running.
> 
> If you use "F5" it starts a session without terminating the previous session. So if you see the dialog, that means that your previous session hasn't terminated yet and you will end up with two (or more) sessions. Is this really your intention?

I don't use f5, I use f4 which a customized macros to do `stop and then start`

**Comment by iamwwc** [comment]
The reason is I first use stop, and then start. There should not have an another debug session at the same time. But It does.

https://github.com/microsoft/vscode/issues/132446
