### ISSUE TITLE
IntelliSense's text show [object Object]

### ISSUE THREAD

**Issue by kainstar** [microsoft/vscode#132212]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: macOS Big Sur 11.2.3

When i input `report` in vscode editor, the IntelliSense's completion items list show me a item `[object Object]?`, which is `report` method from node's process module.

![image](https://user-images.githubusercontent.com/15249633/131961964-948f5c11-b7ee-4dad-8190-96a5621939a0.png)

But the code action's display is normal.

![image](https://user-images.githubusercontent.com/15249633/131961888-76951487-b55d-4846-ac6d-db44b8e54552.png)

I guess it's a vscode problem because it occurs after i update vscode version this morning.

**Comment by gjsjohnmurray** [comment]
When the list is displayed and the [object Object] is selected please press <kbd>Cmd</kbd>+<kbd>/</kbd> to run the `toggleExplainMode` command. This should tell you where the entry comes from.

**Comment by kainstar** [comment]
I know where the `[object Object]` comes from by explain. My question is why vscode show `[object Object]` in its IntelliSense result list? Can it be repaired? What info should I supply?

**Comment by gjsjohnmurray** [comment]
> What info should I supply?

Please paste a screenshot of the explain mode info.

**Comment by sharedrory** [comment]
Hi. I'm not sure where this belongs but I would like to confirm weather this is the same issue I am having.
![image](https://user-images.githubusercontent.com/85806407/133936932-a11c6a80-b23c-4660-9d52-7fdfa5982d81.png)
![image](https://user-images.githubusercontent.com/85806407/133936941-455be7b1-6ffb-4310-951e-d4817cac292c.png)
