### ISSUE TITLE
bracket pair colorization feature; inside code comments

### ISSUE THREAD

**Issue by b0tm0de** [microsoft/vscode#132249]
Issue Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

Hello, thank you for this amazing software (VS Code).

New feature colorized brackets still shown colorfull even inside comments in JavaScript language file.

Create a Javascript file, write something and comment it:
![vscode](https://user-images.githubusercontent.com/6636688/131999266-10545059-dbed-415c-bfab-e3d4f6ac1875.jpg)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (4.54GB free)|
|Process Argv|--crash-reporter-id 9e34d4fb-2e50-4f19-a640-5a617785ac86|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|8.1.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1

</details>

**Comment by sharedrory** [comment]
Just found this issue and wanted to say that it would be nice to have such (unexpected?) behavior as a setting. I have found it useful for some things I do and not for others.

**Comment by hediet** [comment]
Thanks for reporting this bug!

Can you list steps how I can reproduce this?

**Comment by b0tm0de** [comment]
Hi again.
After read your message i tried 2 different path:

A) Open VSCode, use "File" menu then click "Open Folder". Select a folder that contains a Javascrit file. Open a .js file and try commenting Javascript code by keyboard shortcut.

B) Drag and drop .js file to VSCode, then comment code via keyboard shortcut.

Both path A and B reproduce that thing same.

```
> Version: 1.60.0 (user setup)
> Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
> Date: 2021-09-01T10:41:52.311Z
> Electron: 13.1.8
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19043
```

**Comment by hediet** [comment]
I'm sorry it does not happen for me:
![recording](https://user-images.githubusercontent.com/2931520/132202911-f0a96d3b-7564-4e18-9e14-bfc715c76153.gif)

You tried it with all extensions disabled? (including the indent-rainbow extension)

**Comment by b0tm0de** [comment]
![Animation2](https://user-images.githubusercontent.com/6636688/132233940-75adaeec-b27e-4a10-93f2-1cb8a89fc911.gif)

I disabled all extensions and disabled + uninstalled indent-rainbow

**Comment by Nahor** [comment]
It's even weirder than the description says: there was no colorization when the code was NOT commented out.

Maybe there is a race condition between the colorizer and the rendering? Like the rendering happening before the colorizer or something like that? Then the described issue is that once commented out, the bracket colorization didn't get removed YET, and once removed, there is no refresh of the screen?

**Comment by carlosmgilp** [comment]
Hello how are you.
I am presenting the same error.
With AutoLISP.

![image](https://user-images.githubusercontent.com/80189444/132716601-d38081c8-b75f-406c-96be-ace257f0290b.png)

**Comment by hediet** [comment]
@carlosmgilp can you test the latest insider build of vscode?
It should be fixed there.

**Comment by Whobeu** [comment]
Took a while to find this report as I have been seeing color highlighting in comments and wanted to make sure I was not creating a dupe. I used to use Bracket Pair Colorizer 2 so I did notice this change in behavior with brackets being highlighted in comments. Definitely not a show stopper but I wanted to add my 2 cents for a future update.
