### ISSUE TITLE
AFTER NEW UPDATE npm script run in power shell BUT default terminal is CMD

### ISSUE THREAD

**Issue by DmitriyIvanko** [microsoft/vscode#132280]
After update 03/09/2021 (few seconds ago) all npm script starting in Power Shell. BUT my default terminal is CMD

When you click "Open Integrated Terminal" it's opened Power Shell again. BUT default terminal is CMD.

Download previos version -- everything fine.

FIX IT!!! IT REALLY IMPORTANT!!!!

**Comment by ArturoDent** [comment]
I think this is the tracking duplicate: https://github.com/microsoft/vscode/issues/132149
