### ISSUE TITLE
⌘⌃H keybindings don’t work

### ISSUE THREAD

**Issue by babramczyk** [microsoft/vscode#132215]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
- OS Version: macOS 11.5.2

Steps to Reproduce:

1. Use a keybindings with ⌘⌃H

The keybinding does not trigger properly

or

1. Go to `Keyboard Shortcuts` page
2. Use the `Record Keys` function

Instead of `cmd+ctrl+h` showing up, just `cmd+ctrl` shows up

**Comment by sandy081** [comment]
I think another application that is installed on your system is consuming `cmd+ctrl+h`. Hence VS Code is not able to receive and record it. Please check for the application that is consuming it.

CC @alexdima
