### ISSUE TITLE
Integrated terminal does not resize when pane is resized

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode#132281]
Issue Type: <b>Bug</b>

Integrated terminal does not resize when pane is resized.

If the Integrated Terminal pane is started so it is on the bottom and covers 50% of the vertical screen space.  When resizing the pane so it only covers 30%, the prompt stays up at the 50% position, so I have to either press <kbd>Enter</kbd> or <kbd>Ctrl</kbd>+<kbd>c</kbd> repeatedly so the prompt lowers down the terminal enough to become visible.  

The reverse happens if I resize the pane up from 50% to 80% of the vertical screen space.  Then the prompt also stays at the 50% position and I have 30% of blank screen above the prompt position.  Pressing <kbd>Ctrl</kbd>+<kbd>l</kbd> to clear the terminal screen does nothing to move the prompt up to the top of the Integrated Terminal pane.

In either case, no matter how long I use the terminal, the prompt position is fixed to where it was when I first started the terminal.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (0.59GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
sftp|lix|1.12.9
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo
Latest stable version is 1.60.0. Is this issue reproducible there?

**Comment by clayms** [comment]
@IllusionMH 

Yes.  Screen capture below to show what I am talking about.  It is particularly annoying when I resize to a smaller size about halfway through the gif, I am pushing <kbd>Enter</kbd> 20 to 30 times before the prompt gets pushed down far enough to reappear in the terminal window.

![vscode_terminal](https://user-images.githubusercontent.com/12793783/132100870-2866e81f-8bf5-4571-9b4c-a59b97433763.gif)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
