### ISSUE TITLE
Cannot exit vscode when remote ssh connection broken

### ISSUE THREAD

**Issue by Sccotliu** [microsoft/vscode#132203]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60
- OS Version: windows 10  19041.1165

Steps to Reproduce:

1. remote ssh to virtualbox machine
2. after connection broken, then will reconnect automatically
3. then click close button but cannot exit vscode, and also cannot stop reconnect, and cannot connect success actually

**Comment by roblourens** [comment]
> then click close button but cannot exit vscode, and also cannot stop reconnect, and cannot connect success actually

I can't repro this, a gif would help. I'm not sure what state exactly vscode is in when you click the close button.
