### ISSUE TITLE
fetchTasks is losing the reference to TaskGroup 

### ISSUE THREAD

**Issue by carlos-algms** [microsoft/vscode#132279]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Mac

I have a custom Task Provider and a Tree view to show the list of tasks with specific icons depending on the task type.

The provider looks like this: 

```ts

export class MyMakeTaskProvider implements vscode.TaskProvider {
  /**
   * @inheritdoc
   */
  provideTasks(): vscode.ProviderResult<MakefileTask[]> {
    const task = new vscode.Task(
      definition,
      folder,
      targetName,
     "make",
      new vscode.ShellExecution("make", [....]),
      [],
    );

    task.group = vscode.TaskGroup.Build;

    return [task];
  }
}
```

Elsewhere, when I try to get the available tasks, the reference to the `TaskGroup` is lost: 
```ts
const [task] = await vscode.tasks.fetchTasks({ type: "make" });

if (task.group === vscode.TaskGroup.Build) {
  // it will never enter here
}
```

Also, it is not possible to check by ID or label, because the `TaskGroup` class does not have public properties.

**Comment by alexr00** [comment]
We made the `ID` a public property with 1.60 so you can compare to that, but the behavior you're seeing is an accidental breaking change. I will see if there's anything I can do.

**Comment by alexr00** [comment]
With this fix, you should be good to go for most cases. The exception is if the task gets marked as a default task by the user.

**Comment by carlos-algms** [comment]
Thank you very much @alexr00 👏🏻 

Will I be able now to check like this:

```ts
if (task.group === vscode.TaskGroup.Build) {
```

Or do I still have to check by `id`?

**Comment by alexr00** [comment]
@carlos-algms the safest thing to do is to check by `id`, as the the `TaskGroup` will not be the same if the user has marked a task as default. If the user hasn't marked the task as default then `if (task.group === vscode.TaskGroup.Build) {` will work the way you expect.
