### ISSUE TITLE
Git-bash no longer possible to be used as shell in integrated terminal

### ISSUE THREAD

**Issue by tzvic** [microsoft/vscode#132253]
Issue Type: <b>Bug</b>

option 1
Set  "terminal.integrated.shell.windows" to the path to git bash.exe binary .

option 2
add in   "terminal.integrated.profiles.windows"  :
        "Git Bash": {
            "path": "..path to bash.exe",
            "icon": "terminal-bash"
        }
set  "terminal.integrated.defaultProfile.windows"  to "Git Bash".

The system recognizes only the autodetected shells and not one provided directly

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
mimeconvertor|ajo|0.2.0
jenkins-status|ale|4.2.1
cucumberautocomplete|ale|2.15.1
vscode-eclipse-keybindings|alp|0.14.0
gitstash|art|4.0.0
asciidoctor-vscode|asc|2.8.9
vscode-browser-preview|auc|0.7.1
vagrant|bbe|0.5.0
markdown-mermaid|bie|1.11.0
markdown-preview-github-styles|bie|0.2.0
vscode-intelephense-client|bme|1.7.1
insert-unicode|bru|0.12.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
hex-to-rgba|dak|1.0.0
vscode-jq-playground|dav|4.2.0
mustache|daw|1.1.1
vscode-eslint|dba|2.1.23
FreeMarker|dco|0.0.9
quicktype-refresh|dog|0.1.1
githistory|don|0.6.18
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vsc-material-theme-icons|equ|2.2.0
markdown-table-formatter|fcr|2.2.3
vscode-firefox-debug|fir|2.9.4
vscode-mysql|for|0.4.1
vscode-lombok|Gab|1.0.1
mayukaithemevsc|Gul|3.0.1
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.2
rest-client|hum|0.24.5
mysql-syntax|jak|1.3.1
plantuml|jeb|2.15.1
vscode-peacock|joh|3.9.1
jq-syntax-highlighting|jq-|0.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
velocity|luq|0.7.1
VS-code-vagrantfile|mar|0.0.7
marp-vscode|mar|1.3.0
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
file-downloader|min|1.0.11
theme-monokai-pro-vscode|mon|1.1.19
vscode-docker|ms-|1.16.1
data-access-migration-toolkit|ms-|0.3.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
hexeditor|ms-|1.8.2
powershell|ms-|2021.8.2
test-adapter-converter|ms-|0.1.2
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.4.0
indent-rainbow|ode|7.5.0
oracledevtools|Ora|19.3.4
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
vscode-thunder-client|ran|1.9.1
ruby|reb|0.28.1
fabric8-analytics|red|0.3.3
vscode-commons|red|0.0.6
vscode-wsdl2rest|red|0.0.13
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
robotframework-lsp|rob|0.21.0
vscode-coverage-gutters|rya|2.8.1
jinjahtml|sam|0.16.0
scala|sca|0.5.4
markdown-preview-enhanced|shd|0.6.0
code-spell-checker|str|2.0.3
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
json2yaml|tux|0.2.0
vscode-icons|vsc|11.6.0
footsteps|Wat|0.1.0
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.28.0
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.4.0
cursorCharCode|zei|0.2.0

(11 theme extensions excluded)

</details>

**Comment by mok-liee** [comment]
same problem here!
