### ISSUE TITLE
Page overlaping

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#132216]
Issue Type: <b>Bug</b>

The extension descriptions are overlaping the head...
![image](https://user-images.githubusercontent.com/39626142/131847018-48c8b225-2e04-4ead-8db7-b200c42c280a.png)

VS Code version: Code - Insiders 1.60.0-insider (efaa9c304bba61bdce8b0d39db5df94ce3a53fb6, 2021-08-31T15:01:21.969Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
@ProtocolLive this works just fine for me. Can you please try to reproduce using https://code.visualstudio.com/insiders/

![Screenshot 2021-09-03 at 09 20 15](https://user-images.githubusercontent.com/1926584/131967733-6e753fc2-6809-44cf-9627-6aee58f7a45e.png)

**Comment by ProtocolLive** [comment]
Im using the insiders version.
this issue are been fixed...
