### ISSUE TITLE
Terminal not scrolling to current line when reopening

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13227]
- VSCode Version: 1.6 Insider
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Open terminal and run a script that keeps generate output
2. Hide terminal
3. Reopen terminal. It's not scrolling to the newest content.
4. Press enter. Now it's showing the newest content.

![terminal](https://cloud.githubusercontent.com/assets/4033249/19096346/8b940d1a-8a50-11e6-8372-5e3063122f67.gif)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/12000

**Comment by Tyriar** [comment]
Not a regression from 1.5, removing from October and waiting until #12000 is done to re-evaluate.

**Comment by Tyriar** [comment]
I think this has been fixed.
