### ISSUE TITLE
editorBracketHighlight.foreground to accept CSS color names

### ISSUE THREAD

**Issue by Spleeding1** [microsoft/vscode#132266]
The bracket highlighting is great, but coming from the extenstion, it is nice to be able to type in CSS color names.

Please add support for CSS color names for "editorBracketHighlight.foreground" settings.

**Comment by hediet** [comment]
Unfortunately, this is not possible. The native implementation uses the theming-engine (and as such, bracket pair can be styled by theme-authors!) which does not support CSS color names.

However, I could imagine that an extension could provide a refactoring here to convert between those representations.
