### ISSUE TITLE
Smoketest failure

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#132233]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=133609&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=00d0ae10-f5a4-5438-a3b8-c58076933cab

**Comment by jrieken** [comment]
fyi - pushed change to skip this test

**Comment by bpasero** [comment]
@sandy081 There is a trace attached that you can open with `npx playwright show-trace trace.zip`

The last of the traces in  https://dev.azure.com/monacotools/Monaco/_build/results?buildId=133609&view=artifacts&pathAsName=false&type=publishedArtifacts

![image](https://user-images.githubusercontent.com/900690/131986669-9859840f-2220-4805-bcbd-04f9af1b274a.png)


Seems to me it is just not clicking the "Install" button:

![image](https://user-images.githubusercontent.com/900690/131986535-d03e4a0f-4bf4-4940-9831-e0762b24bf27.png)

**Comment by sandy081** [comment]
@bpasero Thanks for the tooling support. It helped to figure out what's going wrong.

**Comment by bpasero** [comment]
👏
