### ISSUE TITLE
Python Debugger Defaulting to PowerShell

### ISSUE THREAD

**Issue by sonicauto-david** [microsoft/vscode#132296]
Issue Type: <b>Bug</b>

There was an update today and ever since running the debugger launches in a power shell terminal instead of the command prompt. For whatever reason, it does not recognize the conda environment correctly and complains about missing packages. I am just running one of my launch.json configurations from the debug panel of the left-hand side of the window. 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (20.90GB free)|
|Process Argv|--crash-reporter-id 6784a384-ec76-4663-97a6-61983b73790a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SalmaHaidar** [comment]
I suddenly noticed the same behavior today and was searching all over the place what went wrong with my setup. Noticed that I had an update to 1.60 today and now my custom workspaces are not working anymore. I hope this gets fixed asap.
