### ISSUE TITLE
[Bug] vscode can't open when menuBarVisibility is set to "toggle"

### ISSUE THREAD

**Issue by jamestansx** [microsoft/vscode#132238]
Issue Type: <b>Bug</b>

1. Set `window.menuBarVisibility": "toggle`
2. Close all vscode instances
3. Start vscode again
4. The vscode will be started up but the window will immediately close (The screen just flashed and closed).  

5. Delete `window.menuBarVisibility": "toggle` in setting.json
6. Reopen vscode and it will work again

VS Code version: Code - Insiders 1.61.0-insider (aec6ee09fa1021cb59c7f4f4d000b027febc967d, 2021-09-03T05:14:10.486Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.90GB free)|
|Process Argv|--crash-reporter-id 7004f2a0-6b56-4181-b730-80bcef7fa54a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
matlab-code-run|bra|1.0.2
gitignore|cod|0.7.0
gitlens-insiders|eam|2021.7.1905
git-project-manager|fel|1.7.1
matlab|Gim|2.0.1
remotehub-insiders|Git|2021.9.30010
vscode-pull-request-github|Git|0.30.0
pdm-task-provider|kno|1.0.0
python|ms-|2021.10.1195952443-dev
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
test-adapter-converter|ms-|0.1.2
vsliveshare|ms-|1.0.4761
material-icon-theme|PKi|4.10.0
platformio-ide|pla|2.3.3
joplin-vscode-plugin|rxl|0.5.2
markdown-preview-enhanced|shd|0.6.0
tabnine-vscode|Tab|3.4.26
vim|vsc|1.21.7
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vshan820:30294714
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vsccppwtct:30312693
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
javagetstartedt:30350119
pydsgst2:30361790

```

</details>

**Comment by stagefright5** [comment]
Thanks for this. I was struggling to point out the issue.

**Comment by bpasero** [comment]
@deepak1556 confirmed, insiders only. crash dump: 

[07825acf-f98e-417b-92f4-8036f7396166.zip](https://github.com/microsoft/vscode/files/7107435/07825acf-f98e-417b-92f4-8036f7396166.zip)

**Comment by sbatten** [comment]
Crash occurs only with this line present
https://github.com/microsoft/vscode/blob/56abba58572b4c548f315e9acc0ada017578a87f/src/vs/platform/windows/electron-main/window.ts#L1197

**Comment by deepak1556** [comment]
The crash was lucky to be caught by the above code path, the problem is incorrect initialization in the frame code path which recently regressed by https://github.com/electron/electron/pull/30598. I will revert the electron update and bring back the menu bar changes as the root issue can have unintended effects in possibly other paths during workbench load.
