### ISSUE TITLE
Trust file by actual location not by path string

### ISSUE THREAD

**Issue by ltomuta** [microsoft/vscode#132210]
Issue Type: <b>Feature Request</b>

I have a path added to my trusted folders list but files located in the folder this path poins to are not truested if they are opened via a directoy junction path.

Directory of C:\Users
15.10.2020  10:24    <JUNCTION>     ltomuta [C:\Users\lucian]
30.07.2021  09:17    <DIR>          lucian

Trusted folder:
C:\Users\lucian\ownCloud\WIP

Untrusted file:
C:\Users\ltomuta\ownCloud\WIP\test.txt

I can fix this by duplicating the paths in the trust settings but I'd hope VSCode would rather resolve all file paths to a unique/real one and rezolve iits trustiness regardless of which path was inputed as. 

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

**Comment by sbatten** [comment]
This is quite some work since the renderer does not know how to resolve symlinks. We have already introduced the workaround to allow adding both versions of trust in the workspace trust editor.

**Comment by ltomuta** [comment]
Isn't this a security risk though? If one manages to place a directory junction in a trusted folder, pointing to an untrusted location, one extends the trust to that location as well. And if junction's target location is the root of the drive...

As long as trust is given by file location the that file location has to be trustworthy in the way it's address is resolved and the items trusted should be uniquely identifiable 

Say a symlink is found in a trusted folder. Should you asume that the user knows it is there and what it is pointing to? Or should you prompt to extend (or not) trust to the target folder as well, explicitly? i'd say the later. What if said junction is changed to point somewhere else after it was reviewed and marked trusted for a previous location?
