### ISSUE TITLE
Run - Start Debugging issue

### ISSUE THREAD

**Issue by MaryBrandt** [microsoft/vscode#132288]
Issue Type: <b>Feature Request</b>

The program will not run the "Start Debugging". I think I may have deleted something or changed a setting. It was working at first and now it is not. I am new to writting code and using this type of program.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by TylerLeonhardt** [comment]
Can you give us some more details of what kind of code you're trying to debug and maybe a gif of what you're doing so we can understand?

**Comment by MaryBrandt** [comment]
I tried Chrome.



I do not know what to put here.




Is this what you need?
    On Friday, September 3, 2021, 09:09:37 PM EDT, VS Code Issue Triage Bot ***@***.***> wrote:  
 
 


Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, .gif files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.

If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette).

Happy coding!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by connor4312** [comment]
Please provide more details, or a gif as requested, around your issue. This information is not enough for us to triage your problem.
