### ISSUE TITLE
Add setting to close open editors when loading fails on startup

### ISSUE THREAD

**Issue by apeforever** [microsoft/vscode#132297]
Add setting to close open editors when loading fails on startup instead of keeping them open, which is new.
- VSCode version : 1.60.0
- OS version : Windows_NT x64 10.0.19043

Associated feature request: https://github.com/microsoft/vscode/issues/110062

**Comment by grahamperrin** [comment]
I don't entirely understand: 

> instead of keeping them open,

The looping screen recording at https://github.com/microsoft/vscode/issues/110062#issuecomment-899340040 seems to show _Try Open Again_
