### ISSUE TITLE
Minimap position not visible on dark themes

### ISSUE THREAD

**Issue by andrea-capigiri** [microsoft/vscode#132270]
Issue Type: <b>Bug</b>

Using dark themes with vertical minimap the visible portion of file is difficult to see

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (8.51GB free)|
|Process Argv|--crash-reporter-id ad761973-8fe2-433c-bcba-6b1f3aff4bca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
ng-template|Ang|12.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
codespaces|Git|1.0.4
vscode-edit-csv|jan|0.6.0
csharp|ms-|1.23.15
live-server|ms-|0.2.8
powershell|ms-|2021.8.2
vs-keybindings|ms-|0.2.1
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details>

**Comment by TylerLeonhardt** [comment]
@andrea-capigiri which theme are you experiencing this with?

**Comment by andrea-capigiri** [comment]
On GitHub dark themes mainly.
Here a comparison between "VisualStudio Light" theme vs "GitHub Dark"

![image](https://user-images.githubusercontent.com/12972252/132094722-da2d896d-cceb-4eef-8752-edf52fcc3fae.png)

**Comment by lramos15** [comment]
Please open an issue against their extension https://github.com/primer/github-vscode-theme. It does say GitHub Dark is a legacy theme
