### ISSUE TITLE
código não quer depurar no navegador!

### ISSUE THREAD

**Issue by isaqueluiz** [microsoft/vscode#132295]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by CodeCrazy-ywt** [comment]
Google Translate: We wrote the necessary data to your clipboard because it was too big to send. Please, Cole(Paste?). 
Looks like this user sent this issue but forget to paste the needed data.

**Comment by lramos15** [comment]
Closing due to lack of description
