### ISSUE TITLE
VS Code does not recognize git repo it did not create

### ISSUE THREAD

**Issue by MalikRumi** [Microsoft/vscode#13220]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:40:08.699Z)
- OS Version: Linux x64 4.4.0-38-generic

Steps to Reproduce:
1. Click on git icon
2. Message "the repo is not under git control"
3. Notice it is not referencing the correct directory
4. created git repo at terminal, independent of VS Code
5. Same message "the repo is not under git control"
6. Close VS Code and reopen
7. Same message "the repo is not under git control"

**Comment by joaomoreno** [comment]
What do you mean by the following?

> Notice it is not referencing the correct directory
