### ISSUE TITLE
file associations documentation

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#13224]
Please include a list of default file associations in the documentation

https://code.visualstudio.com/docs/customization/userandworkspace

It took me forever to find `shellscript`
Tried `sh` `bash` `shell` 

```
"files.associations": {
    "*.fish": "shellscript"
}
```

**Comment by gregvanl** [comment]
I think you want the list of language ids?
In the 1.6.0 release (you can see this on [insiders](https://code.visualstudio.com/insiders)), the Language Mode selection dropdown will have the language identifier next to the language friendly name.

![languageid](https://cloud.githubusercontent.com/assets/12818376/19095304/dc5f918a-8a49-11e6-8bdc-bf59de3dda32.png)

The language overview page also has a table of language ids (though not shellscript - I'll add it) https://code.visualstudio.com/docs/languages/overview#_language-id

**Comment by gregvanl** [comment]
Also please open documentation issues against the vscode-docs repo https://github.com/Microsoft/vscode-docs/issues

**Comment by gertcuykens** [comment]
Perfect, thanks

**Comment by gertcuykens** [comment]
O one more thing in your screenshot I see `Shell Script (Bash) (shellscript)` can that be renamed to    `Shell Script Bash (shellscript)`
