### ISSUE TITLE
Launching contributed command via TreeView Item UI doesn't always have a parameter

### ISSUE THREAD

**Issue by clovis-dugue** [microsoft/vscode#132272]
## Does this issue occur when all extensions are disabled?: 
Issue applies to the Extension API

- VS Code Version: 1.60
- OS Version: Ubuntu 20.04

## Steps to Reproduce:

1. Create a basic vs code extension
2. Contribute a command to a TreeView, e.g. with the JSON below
```json
{
	"contributes": {
		"viewsContainers": {
			"activitybar": [
				{
					"id": "viewContainer",
					"title": "View Container",
					"icon": "./resources/view-container.svg"
				}
			]
		},
		"views": {
			"viewContainer": [
				{
					"id": "view",
					"name": "View"
				}
			]
		},
		"commands": [
			{
				"command": "issue.command",
				"title": "Issue command",
				"icon": "$(x)"
			}
		],
		"menus": {
			"commandPalette": [
				{
					"command": "issue.command",
					"when": "false"
				}
			],
			"view/item/context": [
				{
					"when": "view == view",
					"group": "inline@1",
					"command": "issue.command"
				}
			]
		}
	}
}
```
3. Register a basic TreeViewProvider to match the above contribution
4. Click the icon on the newly-contributed TreeView
5. Repeat until the issue (randomly) happens

## Expected
The command launches, with the TreeViewItem on which we clicked earlier as its argument

## Actual
The command launches, sometimes with no argument. It then crashed, and shows an Information message saying the provided command could not run, ignoring `vscode.window.showXMessage()` if we attempt to run any

## Additionnal info
The same behavior does not happen on other VS Code API implementations (e.g. theia), but the code was developed for VS Code, and tested on both

**Comment by alexr00** [comment]
@clovis-dugue my understanding based on this issue is that the problem should occur for any tree view with any inline contributed command, is that correct?

I tried to repro ~30 times on an existing tree view, but I wasn't able to see the behavior you describe. Can you provide a repo with a full sample?
