### ISSUE TITLE
Getting 404s for JSs and CSSs while debugging default website from Visual Studio Code

### ISSUE THREAD

**Issue by Andrei-Rinea** [Microsoft/vscode#13222]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1. Create a directory
2. 'dotnet new -t Web' in the directory
3. 'dotnet restore' and 'dotnet run' in the directory
4. Load the website in a browser at http://localhost:5000/ and notice that everything loads and looks OK
5. Open Visual Studio Code and open the directory from step 1
6. Accept adding debugging assets and start debugging the website
7. The browser will load the site (at http://localhost:5000/) and notice that JS and CSS requests are getting 404s and the site looks bad.

I've recorded [a video with these steps](http://www.screencast.com/t/NvbuNGKCFZbX). Also I [cross-posted on Stackoverflow](http://stackoverflow.com/q/39860484/1796).

**Comment by Tyriar** [comment]
I believe this would be an issue with the C# extension, not vscode itself. Please file the issue at https://github.com/OmniSharp/omnisharp-vscode
