### ISSUE TITLE
 The format of block comments in JavaScript is wrong, which makes it impossible to use d.ts intelligent prompt

### ISSUE THREAD

**Issue by yangdan8** [microsoft/vscode#132205]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- 1.60.0

- OS Version:
win10

- ------------------------------------------------------ 

Can I modify the template of comments? The current comment is / * XX * /, actually it should be / * * XX * /

Only the comment vscode of / * * XX * / can recognize and provide intelligent prompt

Steps to Reproduce:

1. Open js file
2. Input a function
```js
function ddd() {}
```
3. Input comments and press ctrl+alt+/ 
```js
/* some commets */
function ddd() {}
```
4. Function ddd can't distinguish comments
5. However, the following comments are OK
```js
/** some commets */
function ddd() {}
```

**Comment by ArturoDent** [comment]
`/*  */` is the correct format for javascript block comments.  See https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics#comments

What do you have `Ctrl+Alt+/` bound to?  That isn't a default keybinding.

In any case you can change javscript's block comment style with the extension https://marketplace.visualstudio.com/items?itemName=ArturoDent.custom-language-syntax

and this setting:

```jsonc
  "custom-language-properties": {
    javascript.comments.blockComment": ["/**","*/"]
  }
```
