### ISSUE TITLE
VSC Git push stuck

### ISSUE THREAD

**Issue by hasanbhati** [microsoft/vscode#132211]
When I commit changes and then I try to push the changes to my github account, the sync icon keeps on going forever and it never ends. No changes are being made to my GitHub repository.

![image](https://user-images.githubusercontent.com/32542258/131960496-f4147a20-86d8-4975-91e9-f8e5d37abd07.png)

**Comment by realivanjx** [comment]
dont bother using it sometimes it is unreliable. just use `git push`

**Comment by eamodio** [comment]
Can you provide more details on when this happens? Is there any pattern to it? Does it happen 100% of the time?

**Comment by hasanbhati** [comment]
Hi Eric and Ivan,

Thank you for approaching me on this. At the moment one of my colleagues
has managed to fix this for me. If it ever happens again, I will jot down
more detailed info and let you know.

Thanks,
Hasan Bhati
