### ISSUE TITLE
Word Wrap disabled when saving a new file

### ISSUE THREAD

**Issue by andresgottlieb** [Microsoft/vscode#13221]
- VSCode Version: 1.5.3
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Make sure you have `"editor.wordWrap": false` set in your Settings
2. Create a new file (don't save it)
3. Write a line of text longer that the current window width
4. Toggle Word Wrap
5. Save the file
6. Word Wrap will be disabled

**Comment by bpasero** [comment]
Got fixed for 1.6.0.
