### ISSUE TITLE
`COMMIT_EDITMSG` defaults to YAML with the new language detection

### ISSUE THREAD

**Issue by nirebu** [microsoft/vscode#132226]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: MacOS Big Sur 11.5.2

Steps to Reproduce:

1. Have VS Code as the git editor of choice
2. `git commit`
3. the commit message is highlighted correctly and suddenly changes to be highlighted as YAML

**Comment by gjsjohnmurray** [comment]
Workaround is probably to set `"workbench.editor.languageDetection": false`

**Comment by TylerLeonhardt** [comment]
specific workaround
```
"[git-commit]": {
        "workbench.editor.languageDetection": false
},
```

You can also do this for `git-rebase`
