### ISSUE TITLE
Insider shuts down immediately

### ISSUE THREAD

**Issue by Idered** [microsoft/vscode#132221]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0
- OS Version: Windows 11 Pro 21H2 22000.176

Steps to Reproduce:

1. Start vs code
2. It closes immediately

Running from CMD:

```
C:\Users\Kasper\AppData\Local\Programs\Microsoft VS Code Insiders>"Code - Insiders.exe" --disable-extensions

C:\Users\Kasper\AppData\Local\Programs\Microsoft VS Code Insiders>
[3156:0903/101313.228:ERROR:crashpad_client_win.cc(808)] not connected
```

**Comment by stevenhobs** [comment]
I found my problem caused by settings.json 
`"window.menuBarVisibility": "toggle"`
Deleting this configure can make vscode-insider running well.😅

**Comment by Idered** [comment]
@stevenhobs it works for me too 👍

**Comment by gjsjohnmurray** [comment]
See #132238
