### ISSUE TITLE
Make the Explorer Level "Create File" and "Create Folder" available so that keybindings can be assigned

### ISSUE THREAD

**Issue by garethfentimen** [Microsoft/vscode#13223]
- VSCode Version: 1.5.3
- OS Version: Win10

This is more of a feature request. In https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts
line 600 there is a class called CreateFileAction. I have noticed this is used in the solution explorer class.

There is a public ID, but when trying to assign a keybinding to this action I get a warning.
http://puu.sh/rxN5l/673879404b.png

command "workbench.files.action.createFileFromExplorer" not found

Would it be possible to make it available?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4557

**Comment by bpasero** [comment]
This is actually already possible for a while via:
* `workbench.action.files.newFile`
* `workbench.action.files.newFolder`
