### ISSUE TITLE
Error: Cannot find module 'stream/consumers'

### ISSUE THREAD

**Issue by Rajesh01B** [microsoft/vscode#132260]
i dont know what happened. but when i run a code ,it says 
Error: Cannot find module 'stream/consumer'

CODE = "MODULE _NOT_FOUND"
requiredStack:
            'path'

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your OS, versions etc.

**Comment by lramos15** [comment]
If your code doesn't run at all then it is most likely not a problem with VS Code as we don't execute your code in any special way.
