### ISSUE TITLE
Integrated http library for vscode extensions

### ISSUE THREAD

**Issue by GerbenRampaart** [microsoft/vscode#132225]
This is a feature request.

When building extensions it's common to do http requests to www apis and other such sources. I could not find a way in the @types/vscode to do this in a 'managed' way. By managed I mean using proxy settings that vscode has configured and without instantiating a sort of library instance. 

For me I ended up using got. Which I prefer over axios. But to have either integrated sounds like a good idea because it's just such a common thing to do.

**Comment by chrmarti** [comment]
We patch `http` and `https` modules to add proxy support. Not sure we would add extension API for something that has many convenience npm packages, but maybe github.dev and similar setups could change that. /fyi @jrieken
