### ISSUE TITLE
Upgrade questions

### ISSUE THREAD

**Issue by liaoxuewei** [microsoft/vscode#132204]
When checking the upgrade, why do some computers download compressed packages and do not install them automatically, while some computers install them automatically? What causes it and how to solve it?

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs

**Comment by liaoxuewei** [comment]
Does this option to control background upgrade? However, I see that the option of my computer environment are true, but in fact, the vscode will not be background upgrade.
```

  // Enable to download and install new VS Code versions in the background on Windows.
  "update.enableWindowsBackgroundUpdates": true,

```

**Comment by liaoxuewei** [comment]
And my vscode is 1.60.0 now.
