### ISSUE TITLE
File icons not showing as before?

### ISSUE THREAD

**Issue by Firosee** [microsoft/vscode#132378]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10 pro

Steps to Reproduce:

1. This is a fresh install of VSC on a fresh windows pc

Hey everyone, i have recently changed pc's and i have reinstalled VSC today and i have noticed that all my icons for files are not the same as they were on my old pc. On my old pc the files icons were all the VSC logo for .yml files for example, however on the new pc they all look like this. I have tried to google for countless hours and try resolve it myself but i couldnt find a resolution. 

Im hoping i am just blind and someone is able to guide me how to fix this.

**NEW PC ICONS:**
![image](https://user-images.githubusercontent.com/59424511/132121763-fde0c14e-f9da-4a00-add9-6d3b6bd3a390.png)

**OLD PC ICONS:**
![image](https://user-images.githubusercontent.com/59424511/132121798-7066c1b7-0ce1-4abc-92a4-eb8e466a9013.png)

I am 100% sure that these icons are coming from VSC as i have it set to default open via VSC and if i uninstall VSC all the icons change to the default windows ones.

**Comment by lramos15** [comment]
Following these steps and choosing VS code should do the trick
https://helpdeskgeek.com/how-to/how-to-change-the-default-program-to-open-a-file-with/
