### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by bcarb** [microsoft/vscode#132352]
Hi

I would like to distribute your software "Visual Studio Code Server" in a command-line tool that is to be published on the npm marketplace.

It is a great software as it allows to launch vscode headless and programmatically interact with extensions.

The clause 1 of the [license](https://aka.ms/vscode-remote/license) seems to prevent me from distributing it, even without modifying the software.

How much does it cost to afford a license for commercial use?

Best
Ben

**Comment by chrisdias** [comment]
Sorry, we don't license the VS Code Server for commercial use outside of the Visual Studio Code product itself (per the license).
