### ISSUE TITLE
Can not set default command prompt

### ISSUE THREAD

**Issue by ngoclongxdev** [microsoft/vscode#132355]
Issue Type: <b>Bug</b>

I can not set default command prompt or default gitbash, visual studio code always set power shell command default

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.72GB free)|
|Process Argv|--crash-reporter-id 57fb6f31-87ff-43d9-8b1b-8a7960029f86|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
gitlens|eam|11.6.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
beautify|Hoo|1.5.0
git-graph|mhu|1.30.0
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn420:30356812
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release
