### ISSUE TITLE
Markdown hover link detection stops working

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#132354]
1. Create markdown hover for the tree view item:

```ts
const markdown = new MarkdownString(undefined, true);
markdown.isTrusted = true;
markdown.appendMarkdown(`
- https://www.google.com
- [google](https://www.google.com)
- https://www.google.com
`);
this.tooltip = markdown;
```

Links found in text are being detected until a proper markdown link is met, after which they stop being transformed:

![Screenshot (232)](https://user-images.githubusercontent.com/9638156/132107212-537f4691-c82d-4e40-bee5-29e7c3e4ff1b.png)

---

Version: 1.60.0 (user setup)
OS: Windows_NT x64 10.0.19043

**Comment by joelhock** [comment]
This affects my company's usage specifically in the GitLens blame hover; the commit message contains a URL, but it is no longer clickable now because the hover has the committer's name as a link via markdown earlier in the hover.
