### ISSUE TITLE
Autodetection of language overrides an installed extension

### ISSUE THREAD

**Issue by dchw** [microsoft/vscode#132310]
Does this issue occur when all extensions are disabled?: No, but its related to extensions in general.

- VS Code Version: 1.60.0
- OS Version: Pop! OS 21.04

Steps to Reproduce:

1. Install the Earthly extension (https://marketplace.visualstudio.com/items?itemName=earthly.earthfile-syntax-highlighting)
2. Open any valid Earthfile 

The issue is that valid `Earthfile`s are autodetected as `Dockerfile`s. The syntax is similar, but incompatible. This leads to lots of incorrectly detected errors.

Our extension (linked above) provides an Earthfile language mode and syntax highlighting, and selecting it makes everything behave like it used to.

It seems like auto-detecting languages for extensionless files doesn't account for ones that have an already-installed language mode (and are not in the 54 language autodetection set).

**Comment by futurejones** [comment]
Having a similar problem.
All `Jenkinsfile` are now being auto detected as `sh` scripts
