### ISSUE TITLE
Add google search 

### ISSUE THREAD

**Issue by MeghanshBansal** [microsoft/vscode#132324]
Issue Type: <b>Feature Request</b>

Many programmers need to browse the internet while creating software. A google search feature will save time switching between a browser and vscode.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by AviralCoder** [comment]
I don't think switching between browser and vscode takes more than 2 seconds.
