### ISSUE TITLE
Inlay hints not shown when syntax server set to always

### ISSUE THREAD

**Issue by zapirkon** [microsoft/vscode#132362]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:
1. `"editor.inlayHints.enabled": true,`
2. `"typescript.tsserver.useSyntaxServer": "always",`

The hints become visible when I change syntax server to auto.

<details>
<summary>My user config</summary>
<pre>
"typescript.tsserver.useSyntaxServer": "always",
"editor.inlayHints.enabled": true,
"typescript.inlayHints.enumMemberValues.enabled": true,
"typescript.inlayHints.functionLikeReturnTypes.enabled": true,
"typescript.inlayHints.parameterNames.enabled": "all",
"typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": false,
"typescript.inlayHints.parameterTypes.enabled": true,
"typescript.inlayHints.propertyDeclarationTypes.enabled": true,
"typescript.inlayHints.variableTypes.enabled": true,
</pre>
</details>

**Comment by mjbvz** [comment]
This is because syntax server only supports basic syntax operations while inlay hints require type info

Closing as by-design
