### ISSUE TITLE
Enhancement Request: Jump-to-line + move up or down X lines

### ISSUE THREAD

**Issue by bluSCALE4** [microsoft/vscode#132300]
When you press ctrl+g, you're prompted with the jump to dialog. It'd be nice to be able to press up or down to instead of going to the line, you go up or down that many lines similar to how number arrow key works in vi.

**Comment by TylerLeonhardt** [comment]
Sorry I'm not quite sure I follow, is the idea that you would press ctrl+g and then hit the up/down arrows?

**Comment by bluSCALE4** [comment]
You would press ctrl+g, type in a number and instead of hitting enter, you
hit an arrow key and it'll take you in that direction.
