### ISSUE TITLE
Google App Script Icon

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#132367]
Add Google App Script icon for files ending in `.gs`:

![](https://upload.wikimedia.org/wikipedia/commons/f/f2/Google_Apps_Script.png)

**Comment by gjsjohnmurray** [comment]
You need to make a feature request to https://github.com/jesseweed/seti-ui because that is where VS Code gets these icons from.

**Comment by Yash-Singh1** [comment]
Moved to jesseweed/seti-ui#628.
