### ISSUE TITLE
Launch terminal profile drop-down menu bug

### ISSUE THREAD

**Issue by Vallek** [microsoft/vscode#132332]
- VS Code Version:1.60.0
- OS Version:Windows 10

Steps to Reproduce:

1. Open terminal 
2. Make it not very high
3. Click on a arrow button
4. Last menu item gets immediately clicked when letting go mouse button (see gif)

![bug-1](https://user-images.githubusercontent.com/22982571/132090883-b050b723-4b39-4d96-af6f-b4a8fd78e339.gif)

**Comment by Tyriar** [comment]
@sbatten I think you're tracking a similar issue related to the native popup

**Comment by sbatten** [comment]
@Tyriar this looks like a native context menu appearing from the dropdown. Since we don't have the fidelity to tell the OS not to draw over the mouse, I would recommend making this trigger on mouse up instead of mouse down. If you aren't controlling that, let me know.

**Comment by Tyriar** [comment]
@sbatten this is using `DropdownMenuActionViewItem` which is used by the ... overflow button button which I see also react on mousedown. Looks like this is the problem line:

https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/browser/ui/dropdown/dropdown.ts#L57-L57

I guess @bpasero is the most relevant person here, I'm a bit worried about breaking something making the change myself.

**Comment by bpasero** [comment]
This is intentional, see https://github.com/microsoft/vscode/commit/3d521cf28d93babfaad6d772a0fa90f371060885

**Comment by Tyriar** [comment]
I guess this is a won't fix then, with the recommendation to switch to the custom title bar?

**Comment by sbatten** [comment]
Unfortunately with the dropdowns we try to position the menus based on the button, not the mouse. With electron APIs this is limiting because it only takes a single coordinate and therefore draws under the menu. The custom menus do resolve this.
