### ISSUE TITLE
Alert users of Stable when Insiders endgame has started 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#132369]
I suggest VS Code should notify users whenever a new endgame begins.

The notification would point to Insiders and ask the user to try it in their environment. 

Doing this might get more users of Stable to try Insiders. This could help detect high-impact issues that would otherwise only surface when the new release ships.

**Comment by mattseddon** [comment]
@gjsjohnmurray from https://github.com/microsoft/vscode/issues/134638

> Also, my previous idea at #132369 might have got enough extra eyes onto 1.61 during endgame week to have detected this particular problem before shipping. It's a only Backlog Candidate at the moment and currently needs 12 more upvotes to progress to Backlog. 🙏

I actually discovered #134421 in insiders before the release but it didn't make any difference. Is the hope that you'll get a small deluge of issues instead of the tsunami that we saw in the above issue?

**Comment by gjsjohnmurray** [comment]
@mattseddon [the change that caused these problems](https://github.com/microsoft/vscode/issues/110882#issuecomment-928784945) arrived in Insiders on the day endgame started, a full week before you discovered #134421. It is regrettable that your report didn't result in anyone on the team recognising that this last-minute change was going to be so disruptive when it reached Stable a few days later.

I'm interested to know if you use Insiders routinely or only during endgame,

**Comment by gjsjohnmurray** [comment]
@egamma this was only one vote short of the threshold for automatic progression to Backlog. I still think it will benefit the project. Please consider keeping the idea alive.
