### ISSUE TITLE
Cannot Attach to Docker image on Remote Host

### ISSUE THREAD

**Issue by cemde** [microsoft/vscode#132379]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0, Commit e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
- OS Version: Local: MacOS 11.5.2 Remote: Ubuntu 20.04.2 LTS
- Docker version: Local: 20.10.8, build 3967b7d Remote: 20.10.8, build 3967b7d
- VS Code extensions: Docker v1.16.1, Remote - Containers: v0.194.0, Remote SSH v0.65.7

Steps to Reproduce:

1. Build this Docker file into an image on both the remote and local machine, e.g. `docker build -f Dockerfile -t user/image-name -m 8g .`:
```Docker
FROM anibali/pytorch:1.8.1-cuda11.1-ubuntu20.04

COPY --chown=user . /app

RUN mkdir -p /home/user/.vscode-server/extensions /home/user/.vscode-server-insiders/extensions \
    && chown -R user  /home/user/.vscode-server /home/user/.vscode-server-insiders

CMD ["bash"]
```
2. In the menu of the Docker extension, choose the image `user/image-name` and select `run interactive`.
3. right click on the running container and select `Attach Visual Studio Code`. On the local machine this works: The window reloads and I end up inside the container. On the remote machine, this will fail. The VSCode window will get stuck on a screen shown below. Nothing happens from here.
<img width="784" alt="Screenshot 2021-09-05 at 12 10 57" src="https://user-images.githubusercontent.com/42615086/132123095-d65b3ed9-8fd7-42f2-b878-4ee0bf8e5832.png">

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/2994.
