### ISSUE TITLE
recognize `file:///c:/script.mjs:456:23` and make it equivalent to `c:/script.mjs:2:5` (DEBUG CONSOLE)

### ISSUE THREAD

**Issue by FuPeiJiang** [microsoft/vscode#132368]
in DEBUG CONSOLE, I just want to be able to ctrl+click on `file:///c:/script.mjs:2:5` and it opens `c:/script.mjs:2:5`
![Code_ffdg3zkNKD](https://user-images.githubusercontent.com/42662615/132114563-016b391a-f3b7-4edb-b861-5304802fe4b8.png)
```
(node:19100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at main (file:///c:/script.mjs:2:5)
```
`file:///c:/script.mjs:2:5` is underlined when I hover over it, but I can't open it 

I think "debug console": `Ctrl + click to follow link` and "ctrl+p": `Go to File...` are implemented at the same place:
when I do ctrl+p : command `Go to File...` or `"workbench.action.quickOpen"`
`file:///c:/script.mjs:2:5` : no matching results
`c:/script.mjs:2:5`: works

I found someone explaining the same thing https://github.com/microsoft/vscode/issues/131773#issue-980964481 but it's `https://`. `file:///` should be way easier to implement
recognize pattern `file:///c:/script.mjs:2:5` and make it equivalent to `c:/script.mjs:2:5`

if anyone knows where it's implemented, I can work on the pull request faster
___
my `launch.json`
```json
      {
        "type": "pwa-node",
        "request": "launch",
        "name": "js debug current file",
        "skipFiles": [
          "<node_internals>/**"
        ],
        "program": "${file}",
        "outputCapture": "std"
      },
```

**Comment by FuPeiJiang** [comment]
I think I found where it's implemented
after searching in all files `Ctrl + click`, I found
```
) : localize('fileLink', "Ctrl + click to {0}", followLink);
```

then, using the debugger call stack, I find out that function `linkify` is the root of this

https://github.com/microsoft/vscode/blob/769d5fb521a047073eaad740a3d8620b95c57be6/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L59

**Comment by roblourens** [comment]
Can you check the developer tools for errors when you ctrl+click on it? (Help > Toggle Developer Tools)

**Comment by FuPeiJiang** [comment]
```
  ERR Unable to resolve filesystem provider with relative file path 'c:\script.mjs:2:5': Error: Unable to resolve filesystem provider with relative file path 'c:\script.mjs:2:5'
    at ci.withProvider (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:11090)
    at ci.doResolveFile (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:12348)
    at ci.resolve (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609:12071)
    at vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1672:908
```
![Code_APnRu7me39](https://user-images.githubusercontent.com/42662615/132760466-4c3c76a2-1268-4794-84fb-bc1cf2545390.png)

error string comes from here:
`src\vs\platform\files\common\fileService.ts:117:58`
```
		// Assert path is absolute
		if (!isAbsolutePath(resource)) {
			throw new FileOperationError(localize('invalidPath', "Unable to resolve filesystem provider with relative file path '{0}'", this.resourceForError(resource)), FileOperationResult.FILE_INVALID_PATH);
		}
```

**Comment by roblourens** [comment]
The debug console link detection is not up to par with the terminal and has some missing cases like this https://github.com/microsoft/vscode/issues/34026

**Comment by FuPeiJiang** [comment]
please fix the terminal: it opens a symlink to `\script.mjs` (this is what's underlined when I hover link), now I have 2 tabs of the same file open: `C:\script.mjs` and `\script.mjs` it really messes with the debugging process, in fact this is why I switched to DEBUG CONSOLE (I was using debug terminal)
![Code_-_OSS_WFoAOBmjns](https://user-images.githubusercontent.com/42662615/132776984-175807ef-5af7-4988-830c-9ad5506ec394.png)

**Comment by FuPeiJiang** [comment]
sorry for the too fast complaining,
thanks for telling me that terminal is different, the terminal can be fixed first, then debug console can use the same linkdetector as terminal

terminal already has the feature, symlink probably took priority
https://github.com/microsoft/vscode/blob/b69c899b550b4449c4ce8155be7b3123bb105762/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L205

this organization is pretty cool:
`src/vs/workbench/contrib/debug`
so I went to `terminal`
`src/vs/workbench/contrib/terminal`
