### ISSUE TITLE
Clicking ellipses for cell output options flickers if the outputing cell is not already selected

### ISSUE THREAD

**Issue by jshihadeh** [microsoft/vscode#132305]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Remote

## Expected behaviour

Clicking ellipses next to a cell output consistently opens additional options

## Actual behaviour

Output options menu flickers with each click and closes

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Make a cell that generates no output (eg import statements or setting variables)
2. Make a cell that generates an output (eg print)
2. Click once on the first cell. First cell is highlighted
3. Click once on the ellipses on the output for the second cell. Output options quickly appear and disappear (not expected)
4. Click once on the second cell. Second cell is highlighted
5. Click once on the ellipses on the output of the second cell. Output options persist. (expected)
6. Order of the two cells does not seem to matter.

![vs-code-output-ellipses-flicker](https://user-images.githubusercontent.com/52261114/132052275-feac6967-3fc8-4d89-ae38-e2ce2c07f719.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/125109
