### ISSUE TITLE
VS Code open file readonly on breakpoint

### ISSUE THREAD

**Issue by ryancmlee** [microsoft/vscode#132307]
https://stackoverflow.com/questions/69006739/vs-code-open-file-readonly-on-breakpoint

I have been using VS Code for many years now and all of a sudden last week all my nodejs projects will open and focus a readonly copy of the file when encountering a debugger or breakpoint.

How do I disable this new unwanted functionality that has been forced upon me?

The path for the original file and readonly file are EXACTLY the same.
It effect all my individual unrelated nodejs projects. So it is not the launch config or something with the project files. It must be some global VS Code setting.
I have no extensions installed.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. hit any breakpoint or debugger in nodejs vs code

**Comment by connor4312** [comment]
What version of Node.js are you using? Node 8 has some issues with this (and other issues; it's been end of life for several years now). You can set `enableContentValidation: false` to disable checking here.

**Comment by ryancmlee** [comment]
Hi,
Thank you for the reply. 
I am using node v14.17.4
I set `enableContentValidation: false` in my launch configs and that seamed to work!
 
Thank you so much,
Ryan

**Comment by connor4312** [comment]
Could you capture a trace log so I can see what the root cause was?

/jsDebugLogs

**Comment by jacksteamdev** [comment]
I also experienced this after installing VSCode @ 1.60.0

`enableContentValidation: false` works it for me too, here's a trace log without it:

[vscode-debugadapter-234cc3c0.json.gz](https://github.com/microsoft/vscode/files/7117488/vscode-debugadapter-234cc3c0.json.gz)

**Comment by connor4312** [comment]
@jacksteamdev you're hitting this, see here for a solution: https://github.com/microsoft/vscode-js-debug/issues/1100#issuecomment-912989704

**Comment by jacksteamdev** [comment]
@connor4312 I installed the nightly debugger, works perfectly! Thanks for the help, I'm knee deep debugging tests, you're a life saver!

**Comment by ryancmlee** [comment]
Hi,
I tried adding `trace: true` in my launch configs but it did nothing.
There is no indication of where a log is saved either in the debug console or the terminal in VS Code.
