### ISSUE TITLE
Debugger forcing PowerShell

### ISSUE THREAD

**Issue by sonicauto-david** [microsoft/vscode#132351]
Issue Type: <b>Bug</b>

Pre downloading version 1.6, the python debugger would open in the console using the command prompt. Now it is using power shell and power shell is not working with my conda environments.

Please fix!!!!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (21.19GB free)|
|Process Argv|--crash-reporter-id 6784a384-ec76-4663-97a6-61983b73790a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release
