### ISSUE TITLE
Stabilize navigation and interaction in Settings editor

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/vscode#132303]
Issue Type: <b>Feature Request</b>

This is probably a bug, but let's start here first.  

Clicking on checkboxes in the Settings editor has some odd behavior. Clicking on a control that is not currently focused causes an immediate and disorienting jump (scroll position shift). Sometimes the click on the control (e.g., checkbox) doesn't toggle it, but instead changes the scroll position only leaving you to wonder if you really toggled it.  In fact, sometimes that repositioning moves the view to a point where the element you clicked on no longer is visible and requires a manual rescroll to get the settings group back in view.

You might be able to repro this by searching for "inlay" in Settings and then trying to interact with the Javacript and Typescript settings dealing with inlay hints.

Expected behavior:

- Clicking on a control, no matter where the scroll position is or if the settings group is focused should activate the behavior on the control first

- Changing the scroll position should use smooth scrolling so the abrupt change of view is not disorienting

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/106577
