### ISSUE TITLE
Render non-breaking space when renderWhitespace is active

### ISSUE THREAD

**Issue by tomhoule** [microsoft/vscode#13239]
I ran into an usability problem with a specific keyboard layout (bépo, a French dvorak variant) and VSCode. The shift+space combination produces non-breaking spaces (U+00A0), and it is very easy to hit involuntarily when typing a space before or after a capital letter. This is not a problem itself, but it becomes one when a codebase is littered with invisible non-ASCII characters.

A simple fix in my case would be to show non-breaking spaces in an obvious way when editor.renderWhitespace is turned on. In 1.5.3 non-breaking space seems to be treated like a word character by renderWhitespace.

Emacs displays it even out of whitespace-mode with a bold colored underscore, and that can be done in Vim with listchars. As this does not look like a very complicated problem, I could submit it as a first PR to the project.

I checked, but if this has already been fixed or the discussion has already taken place, please feel free to close the issue.

P.S. : VSCode is an awesome piece of software and a pleasure to use, please keep up with the great work!
- VSCode Version: 1.5.3
- OS Version: Linux 4.7.6-1-ARCH  x86_64 GNU/Linux

Steps to reproduce:
1. Turn on renderWhitespace
2. Insert a non-breaking space (U+00A0) in the middle of an indentation
3. The non-breaking space character is invisible, and the indentation following it becomes invisible

**Comment by tomhoule** [comment]
With the release of 1.6 and the new renderWhitespace settings, inserting a non-breaking space does not make the indentation after it invisible anymore, but the non-breaking space character itself is still invisible.

**Comment by BojanKogoj** [comment]
I have a similar issue as well, making non breaking space with alt+space (Slovenian Apple keyboard). Unfortunately it breaks almost every second class (SASS) I make, because I press alt too early.

**Comment by docmerlin** [comment]
Bump

**Comment by varkor** [comment]
I feel this would be useful even without `renderWhitespace` on: I suspect the majority of cases in which it appears in code, it's a mistake.

**Comment by ToMakeSense** [comment]
Also met this problem when comparing two list of strings. the [&#8203](https://stackoverflow.com/questions/2973698/whats-html-character-code-8203) is annoying.

**Comment by alexdima** [comment]
This has been implemented in the meantime --> https://code.visualstudio.com/updates/v1_63#_unicode-highlighting
