### ISSUE TITLE
Some characters are rendered incorrectly when Monaco or Menlo font is used and font ligatures are enabled

### ISSUE THREAD

**Issue by etigin** [microsoft/vscode#132377]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: macOS Big Sur 11.5.2

Steps to Reproduce:

1. Enable font ligatures
2. Set font family to Menlo or Monaco
3. In the editor window, type letters "fi". They are treated as a ligature.
<img width="1041" alt="Screenshot 2021-09-05 at 11 59 56" src="https://user-images.githubusercontent.com/2362723/132121355-8459cf4b-545b-4b5a-9b56-53e9c31cdc7c.png">

I do realize that enabling ligatures with fonts that don't support them doesn't make sense, but I enabled this setting when I was trying other fonts like Fira Code and kind of forgot about it.

**Comment by alexdima** [comment]
This works as designed. `Monaco` has a font ligature for `fi` and because `editor.fontLigatures` is enabled, `fi` gets rendered as a ligature. From an implementation point of view, there is no difference between ligatures in Fira Code or ligatures in `Monaco`.
