### ISSUE TITLE
access denied 

### ISSUE THREAD

**Issue by SentiSachin** [microsoft/vscode#132393]
Issue Type: <b>Feature Request</b>

whenever I try to run c program my antivirus deny the access of the file and it won't run.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Please report this to your antivirus provider.
