### ISSUE TITLE
Extension comes back after uninstall

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13234]
- VSCode Version: 1.6.0
- OS Version: Mac OS X

Steps to Reproduce:

1. I saw an update for the latest TypeScript grammar
2. I applied the update and at the same time also uninstalled the go extension
3. I restarted the window
4. I got unhappy with the typescript grammar extension
5. I uninstalled the extension and reloaded
6. I noticed an update showing up in the extensions viewlet for the typescript grammar extension

=> looks like I am back to the older version of the typescript grammar

**Comment by joaomoreno** [comment]
#12761
