### ISSUE TITLE
Disable inlay hints for tests (or allow conditional overrides)

### ISSUE THREAD

**Issue by TrueWill** [microsoft/vscode#132304]
I ❤️ the new [inlay hints](https://code.visualstudio.com/updates/v1_60#_inlay-hints-for-javascript-and-typescript) feature. One area where it's a bit noisy is in tests, though. Even with the `literals` setting, it shows up for Jest (and similar) test blocks (`describe`, `it`, `test`). Please consider adding a way to override this for certain cases. Thank you!

![image](https://user-images.githubusercontent.com/1709726/132072476-c73a7b13-a4b8-48d4-ad55-304baf80220d.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by TrueWill** [comment]
> We plan to continue improving inlay hints going forward so be sure to [share any feedback](https://github.com/microsoft/vscode/issues/new/choose) you have on the new feature!

You might want to update that link then...
