### ISSUE TITLE
extension version rollback in terminal failed.

### ISSUE THREAD

**Issue by jihuacao** [microsoft/vscode#132388]
vscode version:1.59.1
date:2021/08/19
chrome:91.0.4472.124
OS:Windows_NT x64 10.0.19043

description(operating with ms-vscode.cpptools as an example) :
I want to update cpptool from 1.6.0 to 1.5.1 in terminal with command: code --install-extension ms-vscode.cpptools@1.5.1.
The command executes successfully.
After I reopen the vscode, extension manager show that the version of cpptools is still 1.6.0.

picture as follow:
1.update command
![image](https://user-images.githubusercontent.com/22140223/132126950-2af0b6f4-6c9b-4156-a3f7-86b9e8e6fee1.png)
2.reopen the vscode, cpptools still 1.6.0
![image](https://user-images.githubusercontent.com/22140223/132126983-526e3d2d-cef2-4223-9dd9-69639982fa22.png)

Thanks for Any Suggestion!

**Comment by sandy081** [comment]
Do you have auto update enabled for extensions? If so you are hitting a limitation when installing specific version from CLI - https://github.com/microsoft/vscode/issues/63903
You can always install a specific version from the gear icon > Install Specific Version in extensions UI

**Comment by jihuacao** [comment]
> Do you have auto update enabled for extensions? If so you are hitting a limitation when installing specific version from CLI - #63903
> You can always install a specific version from the gear icon > Install Specific Version in extensions UI

Yes,auto updating is turned on.
Thank You！
problem solved.
