### ISSUE TITLE
IntelliSense just stop working

### ISSUE THREAD

**Issue by khainl1110** [microsoft/vscode#132398]
Issue Type: <b>Bug</b>

IntelliSense stops working and it's so annoying.
First it was dead when I was using TypeScript and it said something like The TypeScript language service died 5 times right after it got started. The service will not be restarted. Then IntelliSense just stopped working and it's so annoying. What a let down

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.89GB (6.11GB free)|
|Process Argv|--crash-reporter-id c3c012e6-0add-4a86-9490-aff795d88e0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.3.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
vscode-install-vsix|fab|1.4.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-lombok|Gab|1.0.1
vscode-docker|ms-|1.16.1
remote-containers|ms-|0.191.1
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vscode-typescript-next|ms-|4.5.20210904
fabric8-analytics|red|0.3.3
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
scala|sca|0.5.4
metals|sca|1.10.8
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-initializr|vsc|0.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn321cf:30356811
pydsgsc2:30361791
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
