### ISSUE TITLE
Extensions won't work

### ISSUE THREAD

**Issue by ahmed2khan** [microsoft/vscode#132353]
searching or looking for extensions on extensions tab won't work it display this massage : 
we can not connect to the extension marketplace at this time , please try again later . 

PS: my internet connection is good and i don't have any hardware or software/system problems.

**Comment by bounasserabdelwahab** [comment]
Extensions are not working for me either after I updated to the latest version, I get this message:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by Holt59** [comment]
Any updates on this? Makes using VS Code very hard... This also happens with the extensions tab, where most of the content on the extension page is not loaded.

Using the developer tools, I get the following logs (VS Code 1.60.0)

```
main.js:116 Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ VM5 main.js:116
notificationsAlerts.ts:40 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
onDidChangeNotification @ notificationsAlerts.ts:40
webviewCommands.ts:28 Using standard dev tools to debug iframe based webview
main.js:116 Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ VM6 main.js:116
async function (async)
(anonymous) @ VM6 main.js:116
(anonymous) @ VM6 main.js:115
notificationsAlerts.ts:40 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:577
addNotification @ notifications.ts:206
error @ notificationService.ts:92
(anonymous) @ webviewElement.ts:209
(anonymous) @ webviewElement.ts:301
(anonymous) @ webviewElement.ts:301
main.js:753 Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ main.js:753
async function (async)
(anonymous) @ main.js:751
(anonymous) @ main.js:280
notificationsAlerts.ts:40 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:577
addNotification @ notifications.ts:206
error @ notificationService.ts:92
(anonymous) @ webviewElement.ts:209
(anonymous) @ webviewElement.ts:301
(anonymous) @ webviewElement.ts:301
```

**Comment by iamthewallrus** [comment]
Replicable. [https://i.imgur.com/f2s3mu1.png](url)

(yes I do use Linux)

**Comment by sandy081** [comment]
Can you please share VS Code version details - Please copy and paste  the screenshot of Help -> About

**Comment by jonpalle** [comment]
I'm facing the same problem.
<img width="269" alt="billede" src="https://user-images.githubusercontent.com/25053653/132638788-da3bf627-0434-4413-8846-dc62e506a315.png">

**Comment by sandy081** [comment]
Try to reproduce the issue and please share following logs 

- Help -> Toggle Developer Tools -> Console
- View -> Open View… -> Log (Window)

Also please share the gif showing the repro.

Thanks

**Comment by jonpalle** [comment]
@sandy081 I'm not sure what you mean by the gif, but I have reproduced the error by editing a markdown file (.md) and opening the preview to the side (command K V). The preview window is empty errors are reported in the dev tools - console window. Nothing in logs (window): 
<img width="1431" alt="billede" src="https://user-images.githubusercontent.com/25053653/132648833-8bcdd997-bf95-4a1b-a068-b55b1bcc72ac.png">

**Comment by sandy081** [comment]
@jonpalle Info you shared is useful but it seems your issue is completely different than the original issue that is reported. I would suggest to open a new issue by providing above details so that the main issue here will not get distracted. Thanks.
