### ISSUE TITLE
Run With Terminal

### ISSUE THREAD

**Issue by imbikramsaha** [microsoft/vscode#132319]
Issue Type: <b>Feature Request</b>

Previously vs code gives an option of run with terminal after clicking run. But now there is no such option, after clicking the run button it starts running code at the output.
I search everywhere in vs code but I did not find anything.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Tyriar** [comment]
Sounds like it might be related to an extension.

Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal
