### ISSUE TITLE
XML closing tags not properly colorized

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#132394]
Issue Type: <b>Bug</b>

The new bracket/parens colorization feature does not seem to be working for XML closing tags e.g.,

```xml
<PropertyGroup>
  <MyProperty>foo</MyProperty>
</PropertyGroup>
```

In this example, all "</" are gray instead of the appropriate color matching all brackets of the opening tag i.e., "<" and ">" and the closing bracket of the closing tag i.e., ">".

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.24GB free)|
|Process Argv|. --crash-reporter-id f626689c-6e32-475a-b31a-7098b21efda7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.15
docs-build|doc|0.3.6
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.97
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.11
docs-yaml|doc|0.2.7
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
remotehub|Git|0.14.0
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
vscode-guid|hea|1.4.20
azure-pipelines|ms-|1.191.0
vscode-azurecognitivesearch|ms-|0.2.0
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-bicep|ms-|0.4.613
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
dotnet-interactive-vscode|ms-|1.0.2431011
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
powershell|ms-|2021.8.2
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4761
vsonline|ms-|1.0.3076
azurerm-vscode-tools|msa|0.15.2
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
rust|rus|0.7.8
code-spell-checker|str|2.0.4
cmake|twx|0.0.17
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn478:30356813
pythonvspyt187cf:30361754
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by hediet** [comment]
Can you share a screenshot?

Seems to be a duplicate of #130996.

**Comment by heaths** [comment]
Confirmed as a duplicate of #130996
