### ISSUE TITLE
Js.nemucod.af detection by quick heal  while installing VS Code

### ISSUE THREAD

**Issue by KanuPriya718** [microsoft/vscode#132383]
![2021-09-05 (2)](https://user-images.githubusercontent.com/90136363/132124575-69ad109d-e6da-48a3-8f5a-ec5a1d7a1397.png)

**Comment by gjsjohnmurray** [comment]
Please report this to your antivirus provider.

**Comment by joaomoreno** [comment]
Another thing you can try: uninstall and reinstall VS Code.
