### ISSUE TITLE
Inlay hint for for-of variable

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#132350]
Discrepancy:

![Screen Shot 2021-09-04 at 12 59 00 PM](https://user-images.githubusercontent.com/4399718/132104046-91edda65-2669-49e3-bfd7-eafdc33dc911.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
