### ISSUE TITLE
Native Notebooks - Diff view shows diagnostics

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#132397]
VS Code Version: 1.61.0-insider

When opening the diff editor for notebooks it shows diagnostics... I find it strange that this would appear in a diff?

![image](https://user-images.githubusercontent.com/19276747/132135600-8378129b-0c04-475e-8652-e5bd3cf5ec20.png)

**Comment by rebornix** [comment]
@claudiaregio we didn't turn off language features in diff view and the right side is editable.
