### ISSUE TITLE
Web: Switch to `BroadcastChannel` for user data provider sync

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132322]
Related to https://github.com/microsoft/vscode/issues/132084

We are using a `window.localStorage` trick for cross tab communication for the user data file system provider. Rather, we should use [`BroadcastChannel`](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) which allows nice `postMessage` / `onmessage` support for windows/tabs from the same origin.

**Note:** this will actually not work in Codespaces because each Codespace has a separate sub-domain and as such each Codespace has a different origin. So even today with `window.localStorage`, this kind of sync you do only works for when the same Codespace is opened in multiple tabs or on github.dev web editor.

**Comment by sandy081** [comment]
Yes, it is never intended for codespaces instead only for those tabs with same origin. Thanks for the pointers to BroadcastChannel, will take a look.

**Comment by sandy081** [comment]
It seems [`BroadcastChannel`](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) is not supported in Safari & iOS. Hence falling back to `localStorage` in those envs.
