### ISSUE TITLE
Git menu: Commit without Push

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#132301]
I have the setting "Git: Post Commit Command" set to "push".  Normally when I Commit, this is exactly what I want.  However, there are rare times when I want to Commit without a Push.  Currently, to do so requires me changing my setting (or using the command-line, etc.).  It would be nice to have an additional menu option that would only need to be shown when "Git: Post Commit Command" is set to "push", to "Commit without Push" (or perhaps "Commit Only").  This would not need to be prominent and could be put under the Commit menu.

**Comment by ronaldhoek** [comment]
Why not create a ‘Commit’ and ‘Commit & push’ menu entry/command in the first place…? Then there’s no need to have a setting either.

**Comment by andyj513** [comment]
> Why not create a ‘Commit’ and ‘Commit & push’ menu entry/command in the first place…? Then there’s no need to have a setting either.

I usually commit via the check-mark button, rather than the menu.  So, I (and probably many others) would still want a setting to have the check-mark do both.

**Comment by ronaldhoek** [comment]
Don't know what the 'check mark button' is and how it's shown/available, but basically the same can be applied here.

When there's nog enough space, then keep the option to set de action for the 'check-mark button' and add a popup-style secondary button to be able to use the other 'commit style' when needed.

But then the settings will need to be called something else then "Git: Post Commit Command"...
