### ISSUE TITLE
FEAT REQ - Mac app icon keeps changing after each update

### ISSUE THREAD

**Issue by mistermantas** [microsoft/vscode#132346]
I've tried searching but I couldn't find any way to permanently change the app icon on Big Sur to not be white? It's quite jarring in-between all other apps having colored backgrounds.

Is there a bot to automate this or a script? Or could it be done by the app itself from settings?

**Comment by lramos15** [comment]
<img width="407" alt="Screen Shot 2021-09-07 at 12 42 53 PM" src="https://user-images.githubusercontent.com/4544166/132381317-f9c43b6b-ecd6-413b-84d9-44446069e2c8.png">
Sorry, there isn't 1st party support for what you want to do. Slack and Telegram are examples of apps that on Big Sur which also use a white background.

**Comment by mistermantas** [comment]
That sucks that there's no API
