### ISSUE TITLE
Problems with node in vscode

### ISSUE THREAD

**Issue by Rojas-Andres** [microsoft/vscode#132349]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

I have a very strange problem with node. When I open a folder in my vscode, node does not recognize me but without opening a folder it recognizes it perfectly, I do not understand what the error may be. On the other hand I already have node added to the path.

Open folder in vscode
![image](https://user-images.githubusercontent.com/47504973/132103996-3f475e12-ae02-4a96-aa99-57837a8e94cc.png)

Without opening a folder just opening the vscode

![image](https://user-images.githubusercontent.com/47504973/132104007-e66d1910-5980-4c87-864b-e7e99bea00b0.png)

In cmd
![image](https://user-images.githubusercontent.com/47504973/132104022-01f35bde-2252-4cc5-919e-30b92d16fb90.png)

Path
![image](https://user-images.githubusercontent.com/47504973/132104029-788b3d33-3ace-4b87-a76e-745eb745cb8f.png)

**Comment by meganrogge** [comment]
I have been seeing this as well.

**Comment by Rojas-Andres** [comment]
I found a solution and it is when installing node, also install chocolatey. Currently when you install node that option appears unchecked, activate it and thus I would think that the problem would be solved
