### ISSUE TITLE
Default terminal VS code v1.60

### ISSUE THREAD

**Issue by 1alexvash** [microsoft/vscode#132321]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Windows 10

With a new version of VS Code the default terminal is set to be PowerShell, and it seems there's no way to change it

![image](https://user-images.githubusercontent.com/46556479/132084053-06a6eabc-678a-4db1-a364-7ff440b3577e.png)

**Comment by TianYafu** [comment]
Yes. I got the same problem
I manually set **"terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe",`**
And also:
`"terminal.integrated.defaultProfile.windows": "Command Prompt",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        }
    },`

But neither two solutions work for me.
