### ISSUE TITLE
Update the default  ctrl + shift +w keyboard binding

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#132356]
By default, we can use ctrl + shift + w to close the current vscode window. And personally I always use ctrl + shift + e to open the file explorer. I have ran into many cases where I mistakenly pressed the w key instead of e key and closed vscode accidently.

I know we can remove the keyboard binding in keyboard settings. I guess there are other users also frustrated by accidently closing vscode with the keyboard binding. Is it possible to change it to ctrl + shift + alt + w? Or just remove it from the default keyboard bindings? At lease on Windows, I can still close vscode using Alt + F4.

**Comment by gjsjohnmurray** [comment]
See #14710 for a request for confirmation before close.

Default keybindings are unlikely to be changed because doing this breaks muscle memory for existing users.

**Comment by lramos15** [comment]
Closing since @gjsjohnmurray provided the response I would.
