### ISSUE TITLE
default terminal keeps defaulting to powershell when running code or opening up vs code (v1.60) despite changing it.

### ISSUE THREAD

**Issue by JoshRodz027** [microsoft/vscode#132341]
I have changed my default terminal both in the .json and preferences to cmd. However it constantly defaults to powershell.

**Comment by cheestudio** [comment]
+1 here. There's always that light sense of dread when I see VSCode updated...thankfully I can run tasks manually, but I get the same behavior.

**Comment by jsnoriegam** [comment]
#132338 It looks like the same issue

**Comment by SliderCO-007** [comment]
I also see Powershell opening in my terminal panel despite my settings being configured to use Git Bash as the default terminal after the most recent update.

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by gjsjohnmurray** [comment]
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release
