### ISSUE TITLE
Powershell as default terminal.

### ISSUE THREAD

**Issue by SumanKSah** [microsoft/vscode#132348]
After my last update,  It showed something is deprecated and after that, I am unable to change my default terminal. In the setting.json file, it's written then I have changed my profile to cmd but it opens with PowerShell shell, and whenever I try to run any program Powershell gets executed.

**Comment by ashelleyPurdue** [comment]
Same problem for me.

**Comment by gjsjohnmurray** [comment]
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release
