### ISSUE TITLE
Allow test extensions to activate when test view is shown

### ISSUE THREAD

**Issue by hbenl** [microsoft/vscode#132395]
This came up in hbenl/vscode-test-explorer#226, but it is equally relevant for test extensions that use the native testing API directly.
It could make sense for test extensions to only activate when the user opens the test view (or calls a test command etc.) to save resources during VS Code startup. However with the native testing API this turns into a chicken-and-egg problem: the test icon (for opening the test view) isn't shown until the testing extension is activated, and the extension isn't activated until the test icon is clicked.
Perhaps VS Code could check if there is an installed extension that activates on `onView:workbench.view.testing` and always show the test icon in that case. Alternatively, a setting for making the test icon permanently visible (similar to [`testExplorer.hideWhen`](https://github.com/hbenl/vscode-test-explorer#configuration)) could be used.

**Comment by connor4312** [comment]
Tests may be required at other times aside from when the test explorer view is open. For example, when users open a file, or when they simply issue the "run all tests" even if no testing view or files are open. Also, if no tests controllers are registered, we don't show the testing view at the moment. We recommend that extensions use  `workspaceContains` activation event to activate if they suspect tests may be present.

**Comment by connor4312** [comment]
I don't think it's appropriate to add an activation event here since test are often needed in the document. For example, I use testing but rarely open the test explorer and rely solely on keybindings and gutter actions.

**Comment by connor4312** [comment]
Yes, that's one case. Or any time the editor needs items from the tree. For example, if the user reloads the window and runs "rerun last" or "rerun failed", then the editor will resolve items so that it can pass them to the `runHandler`
