### ISSUE TITLE
regex search not working when using complex regex

### ISSUE THREAD

**Issue by gautamkrishnar** [microsoft/vscode#132396]
- VS Code Version: 1.58.2
- OS Version: MacOS 11.5.2 (20G95)

Steps to Reproduce:
1. Open up the search tab
2. Enable the regex search
3. Use the regex `^(?=[\s\S\n]*(Landroid\/view\/Window;->addFlags))(?=[\s\S\n]*(0x2000))[\s\S\n]*$` to search

No results will be returned. Search will keep running indefinitely.

This regex actually matches a smali source code: https://regexr.com/6525n

**Comment by roblourens** [comment]
This is probably https://github.com/microsoft/vscode/issues/30874, you could try simplifying the regex
