### ISSUE TITLE
Add push/pull buttons in source control area

### ISSUE THREAD

**Issue by dlidstrom** [microsoft/vscode#132330]
I believe push/pull button (sync, like at the bottom left of the main window) would be great to have in the source control pane. This would allow more rapid workflow. I am working in a pull request with many small commits (to get feedback from the build actions) and I feel a little bit (very tiny, but still) friction in having to move focus from the source control pane down to the bottom left to find the sync button. I know that it is possible to push from the menu on top of the source control area, but that isn't very rapid (IMO). Maybe a sync button (two circles, as in the bottom) next to the refresh button? I know the area is small so maybe a tooltip could supply the 0↓2↑?

<img width="334" alt="Screenshot 2021-09-04 at 10 53 51" src="https://user-images.githubusercontent.com/371713/132089024-9db74fc5-e4af-42e3-8279-38bb527722f4.png">

**Comment by gjsjohnmurray** [comment]
`"scm.alwaysShowRepositories": true` will give you this.

**Comment by dlidstrom** [comment]
Thanks for the tip @gjsjohnmurray !
