### ISSUE TITLE
VSCode calling PowerShell on first load despite CMD was set as default

### ISSUE THREAD

**Issue by kimlimjustin** [microsoft/vscode#132338]
Issue Type: <b>Bug</b>

On the first load of VSCode, the terminal will automatically use PowerShell despite CMD was set as default. However, if I close it and open it again or split the terminal, cmd will come out. This is a new bug that came out with the new release. Hope this will be fixed soon, thanks!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (21.48GB free)|
|Process Argv|--crash-reporter-id 764f0631-6594-4b5e-bed6-3335a3412ce3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-crowdin|Cro|1.2.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
discord-vscode|icr|5.7.0
jsdoc-generator|kim|0.0.2
es6-css-minify|olb|3.3.2
vscode-jest|Ort|4.1.2
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn321cf:30356811
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by karl-lunarg** [comment]
Same here.  I have:
`    "terminal.integrated.defaultProfile.windows": "Git Bash",`
in my User-level settings.

At startup, the Terminal pane is running powershell.  If I close the Terminal pane by clicking the trash can icon and reopen it with Ctrl-` , I get bash.  Splitting or opening new terminals open bash.

**Comment by LXSMNSYC** [comment]
I tried re-opening VS Code, re-opening, splitting and trashing terminals, still the same.

Looks like it's a day off for me

**Comment by arwhyte** [comment]
Teaching with VS Code and two of my students running Windows have reported this error. Despite switching their default terminal profile to Git Bash, every time they run a Python file in the editor pane a PowerShell session is launched in the lower pane instead of Git Bash.

**Comment by gjsjohnmurray** [comment]
/duplicate - thanks @albertosantini - and fixed in upcoming recovery release
