### ISSUE TITLE
Allow skipping Inlay Hints for arrow function return types

### ISSUE THREAD

**Issue by voxpelli** [microsoft/vscode#132472]
For use with the [`p-settle`](https://github.com/sindresorhus/p-settle) module I had a piece of code that looked roughly like:

```javascript
const tasks = anArray.map(value => async () => {
  const input = value.abc;
  await somethingAsync(input);
  return value.xyz;
});
```

It became very hard to read with Inlay Hints on:

![Skärmavbild 2021-09-06 kl  16 30 36](https://user-images.githubusercontent.com/34457/132232308-529c386e-d6ec-4b21-a653-6c5ee871568d.png)

This is a similar problem as described in #132471. Maybe a full opt out of showing function types in any Inlay Hints all together could be a good solution to them both?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
