### ISSUE TITLE
Getting blank Editor window for  files with content in it and needs a close and start vs code to work properly

### ISSUE THREAD

**Issue by aptro** [Microsoft/vscode#13246]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16:04

Steps to Reproduce:

1. Open editor and open a file
2. It shows blank content for the file.
3. It occurs rarely, but not true for every time i open a file.

**Comment by Tyriar** [comment]
@aptro when this occurs can you open dev tools (Help > Toggle Developer Tools) and check the console for any errors?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
