### ISSUE TITLE
JavaScript broken highlight

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#13247]
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:

1. Open JS-file
2. add to begin: { el = data?true:false; }

Exp.: 'true' and 'false' are highlighted

Act.: 'false' is highlighted, but 'true' - not

**Comment by Tyriar** [comment]
This is fixed in the latest version of the JS grammar, it will probably come to stable in v1.7 though. You can try it out now by installing this extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar
