### ISSUE TITLE
Output channel does not handle spaces in link detection

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#13245]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:
1.  Create a new vscode extension as described on the official page
2.  Write the following code in the extension.ts

``` javascript
var channel = vscode.window.createOutputChannel('test');
channel.show();

channel.append(path.join(vscode.workspace.rootPath, 'nospace', 'file.txt') + ':2:10\r\n');       

channel.append(path.join(vscode.workspace.rootPath, 'with space', 'file.txt') + ':2:10\r\n');    
channel.append(path.join(vscode.workspace.rootPath, 'with%20space', 'file.txt') + ':2:10\r\n');    
channel.append('"' + path.join(vscode.workspace.rootPath, 'with space', 'file.txt') + '"' + ':2:10\r\n');    
channel.append("'" + path.join(vscode.workspace.rootPath, 'with space', 'file.txt') + "'" + ':2:10\r\n');
```
1. Run the extension and open the folder with the following structure:
   myfolder
   -- with space
   ---- file.txt
   -- nospace
   ---- file.txt
2. Run "Hello world" command to trigger extension and expect the output

The first link to \nospace\file.txt:2:10 is correctly recognized and ctrl+click opens the file.
The rest of the links to \with space\file.txt:2:10 are not correctly parsed. Quoting to url escaping does not help.

**Comment by dennisfrostlander** [comment]
Hi, @isidorn, 
Could you please share a few more details on the planning state of this issue? Is there any chance it could be planned for any near update? 

We start getting complaints from the users of ours about this behavior. For example, see https://github.com/Microsoft/AL/issues/167 (this is all happening in VSCode).

**Comment by isidorn** [comment]
Hi @dennisfrostlander fixing this feature is not on our immediate plan.
However we accept PRs that fix this. 
[Code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/links/browser/links.ts#L78)
