### ISSUE TITLE
"Breakpoints" for all file types

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#132468]
Issue Type: <b>Feature Request</b>

On some file types, an extension will allow open files to have breakpoint markers set. These are individual lines marks (in red) which indicate where a debugger can stop.

Please note that that these breakpoints in VS Cdoe are useful for setting breakpoints but also they are useful as breadcrumbs or cheap bookmarks.

When the language server does not support breakpoints, you lose the ability to set breakpoints AND you lose the cheap bookmark functionality.

Therefore, I am requesting that "breakpoints" be supported by every file format, in general, at the VS Code level.

VS Code version: Code 1.59.1 (Universal) (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Try setting `"debug.allowBreakpointsEverywhere": true`

**Comment by fulldecent** [comment]
That's great, thank you. Now I can put bookmarks everywhere!

I'll leave it up to the Defaults Committee as to whether that is helpful for others.
