### ISSUE TITLE
Improve load time of Electron app

### ISSUE THREAD

**Issue by JarnoNijboer** [Microsoft/vscode#13240]
Today I was coming along a new [gist](https://gist.github.com/paulcbetts/da85dd246db944c32427d72026192b41) of @paulcbetts, where he demonstrates a trick for loading a Electron app faster.
I think that this trick may benefit the startup time of vscode, especially on windows, also.

/cc @joaomoreno @bpasero

**Comment by bpasero** [comment]
I am not a big fan of patching a core node.js function like that. If you are curious how much faster it becomes when using this function you should do the benchmarking with this injected to our scripts. We should check the numbers first.

Also note that node.js is doing constant improvements to their module resolution and lookup, I think they are aware of this.

Finally we try hard to keep our NPM dependencies as small as possible to avoid excessive module resolution on startup time.

You can find out how much time is spend in module loading by:
* run `code -p` from the command line
* in the window bring up the command palette and execute `Developer: Startup Performance`
* click on Console in the developer tools

![image](https://cloud.githubusercontent.com/assets/900690/19109669/a78eb9a6-8af6-11e6-8121-49f257cbbdf7.png)

**Comment by bpasero** [comment]
Let's discuss in https://github.com/Microsoft/vscode/issues/15455

**Comment by paulcbetts** [comment]
We've had this patch in Slack for the last 2-3 releases or so and it has caused us zero problems, highly recommended

**Comment by bpasero** [comment]
@paulcbetts thanks, I will play with it and see how much it improves 👍

**Comment by bpasero** [comment]
Likely not needed once https://github.com/nodejs/node/pull/8100/files is available in Electron.
