### ISSUE TITLE
Java Process Console doesn't scan Cyrillic script.

### ISSUE THREAD

**Issue by kagu-tsuchi** [microsoft/vscode#132482]
Does this issue occur when all extensions are disabled?  Yes

- VS Code Version:1.60.0
- OS Version: Windows 10 Pro 10.0.19043 Build 19043
- VSCode Encoding: UTF-8;
- Windows Encoding: UTF-8;

Steps to Reproduce:
1. Copy and paste the following code.
`import java.util.Scanner;`
`class App {`
    `public static void main(String[] args) {`
     `Scanner input = new Scanner(System.in);`
      `String wordCyrillic = input.nextLine();//!Привет`
      `String wordLatin = input.nextLine(); //!hello`
      `System.out.println("we print: " + wordCyrillic);`
      `System.out.println("we print: " + wordLatin);`
      `System.out.println("we print: " + "\u26a1\u2661");`
      `System.out.println("we print: " + "Привет");`
    `}`
`}`
2. Run this code, inputting commented data(or use a random Cyrillic letter).
3. You will get such output:
![Screenshot (18)](https://user-images.githubusercontent.com/85038072/132240152-5abb1500-b0c2-4f50-a1b4-5307d579b4fd.png) 

p.s this piece of code does work in IntelliJ idea and eclipse. @Tyriar

**Comment by Tyriar** [comment]
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

/label terminal terminal-conpty windows
