### ISSUE TITLE
JSDoc optional param forms will not display parameter info.

### ISSUE THREAD

**Issue by OverlyExcessive** [Microsoft/vscode#13243]
- VSCode Version: 1.5.3
- OS Version: OSX Yosemite

According to the documentation of [JSDoc support](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript) in VSCode, posted below. Then optional parameters can be declared in all of the below forms. However it seems that as of VSCode 1.5.3 the last two forms the latter two forms in the sample will not display parameter information.

```javascript
// Parameters may be delcared in a variety of syntactic forms

/**
 * @param {string}  p1 - A string param. 
 * @param {string=} p2 - An optional param 
 * @param {string} [p3] - Another optional param.
 * @param {string} [p4="test"] - An optional param with a default value
 * @return {string} This is the result
 */
function fn3(p1, p2, p3, p4){
  // TODO
}
```

**Comment by waderyan** [comment]
@OverlyExcessive thank you for opening this issue. 

If I'm understanding you correctly, in VS Code 1.5.3 you are not seeing parameter information for p3 and p4. By parameter information do you mean type information? 

Using the latest VS Code Insiders 1.6 (you can download that here), I am not seeing the issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/19154175/422b522a-8b8e-11e6-8211-38b434a6c0b9.png)

Please confirm that I understand you correctly and that I am not seeing the issue in the latest bits. If I misunderstood please send a screenshot of what you are seeing.

**Comment by OverlyExcessive** [comment]
@waderyan 

Thank you for the quick reply. What I mean by parameter information is not the type information, rather the parameter description that will be supplied as you are entering the parameters in order. I have attached of how it looks for the first parameters below:

![captvs](https://cloud.githubusercontent.com/assets/346756/19168856/5519e674-8c12-11e6-973b-9291b1f45ed0.PNG)

And the missing parameter info here:

![captvs2](https://cloud.githubusercontent.com/assets/346756/19168900/722fc486-8c12-11e6-8490-f706d7cc29b6.PNG)

I hope this clarifies what I meant.

**Comment by waderyan** [comment]
@OverlyExcessive thank you for clarifying. This has been confirmed with the latest bits. Moving to TS repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11493

**Comment by michaeljota** [comment]
This is not related to the issue, @waderyan What theme do you use? Mines does not show the `@return` any different from the rest of the `@description`

**Comment by waderyan** [comment]
That would be the new grammar extension! Its in beta right now and we're looking to bring it into the product. 

https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by michaeljota** [comment]
¡Oh! Will test it then. Thank you. 👍
