### ISSUE TITLE
Providing completions with parameters does not work well with parameter hints

### ISSUE THREAD

**Issue by fvclaus** [microsoft/vscode#132490]
Sorry if this is the wrong repo. I am not sure, if this belongs here, on 
vscode-languageserver-node or the language server.

I am using vscode-java and there are few quirks regarding parameter hints and completions.

Completions and parameter hints will be displayed at the same time:
![java_completion](https://user-images.githubusercontent.com/2384738/132253788-be92bf1c-50f6-4128-b305-3f7420fdf795.gif)

Parameter hints have to be triggered manually if a method with parameters is completed (I am not triggering them - just showing that they are not triggered):
![java_completion_no_parameter_hints](https://user-images.githubusercontent.com/2384738/132253954-dcfe171d-c30c-4aef-94a6-899322ec82c0.gif)

The original issue with more information can be found here: https://github.com/redhat-developer/vscode-java/issues/2063

Browsing through the source code, I think that it is currently not possible for an extension to improve upon this situation. vscode decides on its own when it requests `document/completions` making it impossible for an extension to "hide" completions depending on the cursor position. I also think that it is not possible for an extension to programmatically hide completions.

Is it possible to hide completions when a method invocation is entered (either by typing or by completion)?

**Comment by jrieken** [comment]
Completion stays open because the label is still matching what's being typed. Lately we have added new API to make labels more structured (see https://code.visualstudio.com/updates/v1_58#_detailed-completion-item-labels) and that should prevent this. 

fyi @Eskibear as Java extension contributor

**Comment by Eskibear** [comment]
Thank for involving me.

@fvclaus 
Completion item label will be included in LSP 3.17, and I think we have room to improve the experience based on that. Please reopen redhat-developer/vscode-java#2063  track the issue.
