### ISSUE TITLE
public class Sandbox

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode#132448]
Issue Type: <b>Performance Issue</b>

Security Scann が働きません

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) 3205U @ 1.50GHz (2 x 1497)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.98GB free)|
|Process Argv|--crash-reporter-id 68d192bf-fa38-4c43-9e1e-cfd5ac9e68a6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    52	  3512	code main
    0	    45	   940	   shared-process
    0	    12	  6640	     ptyHost
    0	     2	  2352	       console-window-host (Windows internal process)
    0	     3	  2844	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     1	  4680	       console-window-host (Windows internal process)
    0	     4	  9420	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    4	   183	  1224	   window (public class Sandbox{.txt - Sandbox - Visual Studio Code)
    0	     2	 10112	     watcherService 
    0	     1	  3792	       console-window-host (Windows internal process)
    0	   243	 11612	     extensionHost
    0	    13	  2000	       "C:\Users\HIROSHI\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\HIROSHI\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11612
    0	     1	  8156	       C:\WINDOWS\system32\cmd.exe /c c:\Users\HIROSHI\.vscode\extensions\adamvoss.vscode-languagetool-3.8.0\lib\languagetool-languageserver\build\install\languagetool-languageserver\bin\languagetool-languageserver-live.bat 58163
    0	     1	  7452	         "java.exe"      -classpath "c:\Users\HIROSHI\.vscode\extensions\adamvoss.vscode-languagetool-3.8.0\lib\languagetool-languageserver\build\install\languagetool-languageserver\bin\..\lib\*;c:\Users\HIROSHI\.vscode\extensions\adamvoss.vscode-languagetool-ja-3.8.0\lib\*" App 58163
    0	     0	  8172	         console-window-host (Windows internal process)
    0	     4	 10144	       c:\Users\HIROSHI\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.6.5\x86_64-pc-windows-gnu\TabNine.exe --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.0 pluginVersion=3.4.26 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=Quiet Light" vscode-theme-kind=Light vscode-machine-id=b22d441da8ebb99f29c8084d2c5b827b094def98c2a7c0ae9050e6463e99da04 vscode-is-new-app-install=false vscode-session-id=b62a6c27-55b0-4822-a459-bad32beab9d31630919371899 vscode-language=ja "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	     0	  1400	         console-window-host (Windows internal process)
    0	     9	  3256	         "c:\Users\HIROSHI\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.6.5\x86_64-pc-windows-gnu\TabNine.exe" --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.0 pluginVersion=3.4.26 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=Quiet Light" vscode-theme-kind=Light vscode-machine-id=b22d441da8ebb99f29c8084d2c5b827b094def98c2a7c0ae9050e6463e99da04 vscode-is-new-app-install=false vscode-session-id=b62a6c27-55b0-4822-a459-bad32beab9d31630919371899 vscode-language=ja "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
    0	     7	  9176	         "C:\Users\HIROSHI\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\3.6.5\x86_64-pc-windows-gnu\WD-TabNine.exe" --client vscode --client-metadata clientVersion=1.60.0 pluginVersion=3.4.26 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 "vscode-theme-name=Quiet Light" vscode-theme-kind=Light vscode-machine-id=b22d441da8ebb99f29c8084d2c5b827b094def98c2a7c0ae9050e6463e99da04 vscode-is-new-app-install=false vscode-session-id=b62a6c27-55b0-4822-a459-bad32beab9d31630919371899 vscode-language=ja "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	     7	 10460	       C:\Users\HIROSHI\go\bin\gopls.exe -mode=stdio
    0	     1	  3200	         console-window-host (Windows internal process)
    0	     5	 11204	       electron_node languageserver.js 
    0	    24	 11456	       electron_node main.js 
    0	    14	 11912	       electron_node server.js 
    5	    22	 12200	       "C:\Program Files\Go\bin\go.exe" get -v github.com/go-delve/delve/cmd/dlv
    0	    11	 13980	         console-window-host (Windows internal process)
    0	    21	  4880	   window (undefined)
    2	   131	  4940	   gpu-process
    0	     2	 10628	   crashpad-handler
    0	    12	 10796	   utility
    6	    75	 12488	   window (問題のレポーター)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (public class Sandbox{.txt - Sandbox - Visual Studio Code)
|    Folder (Sandbox): 8 files
|      File types: json(3) txt(1) baseline(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: platformio-debug;
```

</details>
<details><summary>Extensions (170)</summary>

Extension|Author (truncated)|Version
---|---|---
dibs-sassy|1st|0.0.4
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-languagetool|ada|3.8.0
vscode-languagetool-ja|ada|3.8.0
shift-shift|ahg|0.0.5
project-manager|ale|12.3.0
al-code-outline|and|3.0.15
ng-template|Ang|12.2.0
go-restart|art|0.0.2
assert-security-editor|ass|3.0.3
azps-tools|azp|0.1.0
SecurityIntelliSense|azs|0.8.0
vscode-django|bat|1.6.0
shell|bbe|0.3.0
vscode-log-viewer|ber|0.12.2
htmlplay|bia|0.0.9
django-html|bib|1.3.0
c-compiler|bra|0.0.4
GBK2UTF8|buu|0.6.0
markdown-zenkaku-indent|ccn|0.0.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-translate|chu|0.1.5
gitignore|cod|0.7.0
shift-saver|cor|1.1.0
jison-syntax-highlight|cru|0.1.1
c-cpp-compile-run|dan|1.0.14
vscode-markdownlint|Dav|0.43.2
wxml|daz|0.2.0
vscode-eslint|dba|2.1.23
git-extension-pack|don|0.1.3
githistory|don|0.6.18
javadebugger|don|0.1.5
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
java-debug|DSn|0.0.2
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
troll-keyboard|eri|1.0.1
prettier-vscode|esb|8.1.0
hujiang|Exi|0.0.3
cortlog|Fax|0.0.6
nuget4code|ffo|0.0.2
generateuuid|Fir|0.0.5
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
vscode-coding-tools-extension-pack|fra|0.3.0
japanese-novel-extension-pack|fuj|0.1.0
markdown-preview-fuji-styles|fuj|0.1.3
markdown-ruby|fuj|1.0.1
vscode-google-translate|fun|1.4.13
meet|gee|0.1.6
vscode-javac|geo|0.2.39
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
google-cloud-spanner-driver|goo|0.4.0
go-log-utils|gpn|0.0.1
google-translate|han|1.2.3
vscode-hyphaene|hyp|0.0.29
turbo-console-debuglog|ida|1.0.0
encdetectjp|ino|0.0.1
path-autocomplete|ion|1.17.1
powershell-universal|iro|2.1.1
powershellprotools|iro|5.30.1
auto-translate-json|jef|1.0.9
readabilitycheck|jem|1.3.0
shiftthat|Jim|0.1.2
vscode-nuget-package-manager|jmr|1.1.6
vscode-keyboard-master|jon|1.0.0
google-search|kam|0.0.1
io|ken|0.0.3
ki|ki|1.0.37
vscode-codemetrics|kis|1.24.0
kite|kit|0.147.0
kitety-vsc-extension-demo|kit|0.0.2
gettingstartedtemplates|Kok|0.1.1
rg-sjis|kom|0.3.2
vscode-format-context-menu|lac|1.0.4
google-fonts|lio|0.0.1
grade-calculator|lou|1.0.0
kite-snippets-basic|lum|0.0.2
MagicPython|mag|1.1.0
marukeyex|mar|0.2.2
markdown-it-container-question|Mat|0.0.1
json|Mee|0.0.1
mp-starter-vscode-ext|Mic|0.2.6
r|Mik|0.0.26
localize-lens|mma|1.0.0
vscode-kite|mrk|0.0.2
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.16.1
vscode-language-pack-ja|MS-|1.60.2
mssql|ms-|1.10.1
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
powershell|ms-|2021.8.2
powershell-preview|ms-|2021.8.3
vscode-typescript-next|ms-|4.5.20210905
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
sqltools|mtx|0.23.0
jspm|Neo|3.0.4
pseudocode|noa|0.4.0
printcode|nob|3.0.0
vscode-for-node-js-development-pack|nod|2.0.1
hyogai-kanji-checker|noy|0.1.0
docker-compose|p1c|0.3.5
keyboard-quickfix|pas|0.0.6
vscode-nuget-gallery|pat|0.0.24
open-html-in-browser|pea|2.1.6
vscode-versionlens|pfl|1.0.9
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.27.0
heroku-command|pko|0.0.8
platformio-ide|pla|2.3.3
vscode-jsp|pth|0.0.3
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
java-sysout|ric|1.0.1
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
laravel-5-snippets|sac|2.0.1
remove-non-ascii-chars|Sam|0.0.5
vscode-base64-encoding-decoding|san|1.1.2
virustotal|sec|0.1.2
japanese-word-handler|sgr|1.2.3
code-settings-sync|Sha|3.4.3
shiftleft-scan|Shi|1.3.0
vscode-vuln-cost|sny|1.6.0
swdc-vscode|sof|2.5.24
code-spell-checker|str|2.0.4
tabnine-vscode|Tab|3.4.26
vscode-typenovel|tat|0.0.1
python|tht|0.2.3
run-in-powershell|tob|1.1.1
decode|ttf|0.1.0
errorlens|use|3.4.0
produirelang|uto|0.0.3
tips|uyi|1.0.3
non-breaking-space-highlighter|vik|0.0.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
crs-al-language-extension|wal|1.4.9
jinja|who|0.0.8
vscode-input|wil|0.0.6
generic-pseudocode|Wil|1.4.0
vscode-import-cost|wix|2.15.0
vscode-reflow-japanese|yod|1.0.0
nadesiko3-vscode|yy0|1.19.5
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
vsdyn478:30356813
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by hiroshi-nakajima345** [comment]
it does not need any difficult comment ,
I need only the reason why  security scan don't start & get cnclusion.

**Comment by hiroshi-nakajima345** [comment]
I do not want published. in this column.
So,I try to inform,twiter.

**Comment by lramos15** [comment]
Sorry, I don't understand what you mean by security scan.

**Comment by lramos15** [comment]
Closing due to lack of update

**Comment by CodeCrazy-ywt** [comment]
@hiroshi-nakajima345 「Security scan」とはどういう意味ですか？
