### ISSUE TITLE
proxy - connect ECONNREFUSED 191.238.172.191:443

### ISSUE THREAD

**Issue by k-sea** [Microsoft/vscode#13249]
- VSCode Version: 1.5.3
- OS Version: windows 7

Steps to Reproduce:

1. connect to your corporate internet
2. use the corporate internet proxy pac file
3. Click Extensions tab

connect ECONNREFUSED 191.238.172.191:443

Proxy should use the local system proxy so we don't have to mess with the settings and store a windows password in plan text.

Check for updates works properly, why doesn't the extension module use the same underlying http functionally of the check for updates routine?

**Comment by joaomoreno** [comment]
#7140

**Comment by thatslibran** [comment]
Was able to resolve the issue by specifying http.proxy settings. 

**File** -> **Preference** -> **Settings**

Use the key - 
{
    **"http.proxy":"http://username:password@ProxyServerIP:ProxyServerPort"**
}
