### ISSUE TITLE
Insiders freezes when using settings editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#132430]
(No good info yet but I believe this has to do with markdown rendering)

Steps:

* open settings editor (UI)
* type "inlay"
* 🥶 vs code freezes and doesn't recover

**Comment by jrieken** [comment]
I see lots of markdown renderer on the stack but this might be local to the settings tree. I see the following (async) endless loop:

* [asyncRenderCallback](https://github.com/microsoft/vscode/blob/d474449fc2332d8f2df38892571ee0925806e7cd/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L872-L872) - called when async code rendering happens
* [renderSettingElement](https://github.com/microsoft/vscode/blob/d474449fc2332d8f2df38892571ee0925806e7cd/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L754-L754) - called in response, triggering another code render...


<img width="303" alt="Screen Shot 2021-09-06 at 09 33 42" src="https://user-images.githubusercontent.com/1794099/132177931-fb5f947b-79e6-4346-b6ca-242536c6abda.png">

**Comment by jrieken** [comment]
Unsure if this is caused by https://github.com/microsoft/vscode/commit/7bc9757b84be47872031d3f183d1f8cce5c1215a or by changing to dompurify and thereby changing the timing of said event?

**Comment by jrieken** [comment]
FYI - I have pushed a *bad* workaround which prevents the endless loop but also causes screen cheese when code blocks are used (heights are wrong)

**Comment by gjsjohnmurray** [comment]
Previously reported as #132250

**Comment by mjbvz** [comment]
@roblourens  I bisected and believe this started with 7bc9757b84be47872031d3f183d1f8cce5c1215a. I confirmed that reverting that change (but keeping the dompurify change) fixes the freeze, although the settings page renders incorrectly

Un-assigning myself but let me know if you believe the changes in markdown renderer are causing issues

**Comment by roblourens** [comment]
@mjbvz why is markdown rendering async, do I need to assume that? List rendering is always sync, so the approach I took to moving settings editor row measuring to the list in https://github.com/microsoft/vscode/pull/129181/files can't be used 😭

**Comment by mjbvz** [comment]
It needs to be async so that we can rendering code blocks in the markdown. This may require activating the language being rendered. Also image loading may also cause the height of the rendered markdown to change

**Comment by roblourens** [comment]
FYI @joaomoreno I will stop using the change from the PR, but will leave the code in the list since it might make sense for someone else. 

The settings editor keeps becoming more and more like a notebook...
