### ISSUE TITLE
Debug another project TS file and set a breakpoint, which will jump to the breakpoint of another TS file of JS icon

### ISSUE THREAD

**Issue by Shawn211** [microsoft/vscode#132416]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows10
- Node.js Version: v14.17.6

Steps to Reproduce:

1. create a ts file in a project
2. open the ts file in another project
3. set breakpoint and debug it
4. cannot debug in current ts file

![debug1](https://user-images.githubusercontent.com/34535599/132154598-13661883-c074-4aa7-a0c9-e713931a1083.png)
![debug2](https://user-images.githubusercontent.com/34535599/132154282-55c21a59-592b-4f87-9f4d-fcbc2a718e2f.png)

Btw, it is normal to debug in ts file project or before upgrade vscode
there are my launch.json and tsconfig.json
``` json
launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Current TS File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/ts-node/dist/bin.js",
            "sourceMaps": true,
            "args": [
                "${relativeFile}"
            ],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        }
    ]
}
```
``` json
tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2020",
        "noImplicitAny": true,
        "outDir": "./dist",
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

__Expected:__ debug in current ts file
__Actual:__ jump to another ts file

**Comment by sean-daley** [comment]
For what it's worth, I'm hitting the exact same issue after updating to Version: 1.60.0 as well.

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/1100#issuecomment-912989704 Please see that comment for resolution
