### ISSUE TITLE
The terminal process failed to launch: Cannot create process, error code: 5

### ISSUE THREAD

**Issue by isatria** [microsoft/vscode#132458]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10 Enterprise 64-bit Build 19042

Steps to Reproduce:

1. Right-click from the workspace.
2. Choose the "Open in integrated Terminal".
 
![vscode-terminal](https://user-images.githubusercontent.com/9941418/132219206-b4436eee-b5d7-4207-8a70-5a94f28e6b65.gif)

I have a problem while open the integrated terminal from the workspace menu like the attachment. and this also happening with the extension that has similar features (e.g: port-forward from right-click menu) like the Kubernetes extension.

I was following the new config for the integrated terminal (using os profile) and it seems ok when open the terminal from the menu (ctrl+shift+`).
![image](https://user-images.githubusercontent.com/9941418/132220225-ffcf1415-6837-45eb-a72d-c870b924bb51.png)

is there any configuration I missed?

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #132150 which will be fixed in upcoming recovery release.

**Comment by isatria** [comment]
Problem solved in v1.60.1

Thank you
