### ISSUE TITLE
VSC not detecting a closing tag in PHP when mixing syntax

### ISSUE THREAD

**Issue by NeboCode** [microsoft/vscode#132452]
Does this issue occur when all extensions are disabled?:  **Yes**

- VS Code Version: **1.60**
- OS Version: **Windows 10 19041.1165**

**Steps to Reproduce:**

Given the following code which is using PHP Escaping (https://www.php.net/manual/en/language.basic-syntax.phpmode.php), I've made a somewhat simplistic replication of the error.

Basically if I open a php tag using the long form `<?php` (instead of shorthand `<?`) and then close it using the shorthand `<?` form, PHP syntax highlighter throws an error: `'}' expected.` because it did not detect the angle bracket in the shorthand property.

This example is perfectly valid code, though the use of tags isn't consistent, VSC still should not throw an error like this and should pick up the closing bracket properly.

```php
<?php
$i = 5;
while($i < 10) {
    $i++;
?>

<div>Test</div>

<? } ?>
```

**Comment by roblourens** [comment]
That error would be coming from a PHP extension like PHP Intellisense. Which one are you using? You can look for or file an issue on the extension's repo
