### ISSUE TITLE
Neu geschriebener code funktioniert nicht

### ISSUE THREAD

**Issue by Maechto** [microsoft/vscode#132405]
Issue Type: <b>Bug</b>

Wenn ich einen neuen code schreibe und ihn dann ausführe, wird nur der alte angezeigt. Bsp.: Ich schreibe Console.WriteLine("Hallo"); ändere as dann zu 
Console.WriteLine("Hallo12345"); , ich lasse es dann debugen und es kommt nur Hallo raus. Auch bei Variabeln die ich anfangs benutzt habe bleiben einfach wie im alten code und lassen sich nicht ändern.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.41GB free)|
|Process Argv|--crash-reporter-id 45cb9185-0322-4ca0-9a98-339501416cc6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.1
vscode-language-pack-de|MS-|1.60.2
csharp|ms-|1.23.15
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30361774
pythonf5test824:30361777
vsdyn420:30356812
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by infinnie** [comment]
Translation:
## Newly written code does not function

**Comment by weinand** [comment]
Make sure that you "build" or "compile" your code before debugging it.

**Comment by Maechto** [comment]
and how can I do so ???

**Comment by weinand** [comment]
Please ask on stackoverflow.
