### ISSUE TITLE
Control over WebView's iframe origin

### ISSUE THREAD

**Issue by mfukala** [microsoft/vscode#132464]
Today when one creates a new WebView via window#createWebviewPanel API there's no control over the origin of the underlying iframe. The iframe gets an autogenerated ID that's part of the source URL. You get something like 

`vscode-webview://bf4f6748-5e6c-4cf2-bc63-0ba7e97558a7/index.html?id=bf4f6748-5e6c-4cf2-bc63-0ba7e97558a7&...
`
as the origin of the iframe. Because of this origin changes every time a WebView is created there's no way how to utilize things like http cache or IndexDB - they are always created empty again for every webview.

I perfectly understand the need for isolation in terms of security but I think that WebViews created by one extension could share the origin and the origin would be somehow fixed - keyed for example by the extension ID, like this:

`vscode-webview://coolExtension/index.html?id=bf4f6748-5e6c-4cf2-bc63-0ba7e97558a7&...
`
Then features like http cache or IndexDB would be usable and able to cache/share data across multiple WebViews created by the same extension.

This would dramatically improve performance.

**Comment by lucaswerner90** [comment]
Any update on this? We've some new features blocked because of this issue. Thanks!

**Comment by gjsjohnmurray** [comment]
@mjbvz looks like this has exceeded the 20 upvotes but hasn't yet moved to Backlog.

**Comment by stephen424242** [comment]
Any update on this? Unfortunately this issue is blocking the adoption of VSCode as a mainstream dev tool. We like VSCode, it's a great tool. We want to expand its footprint in our dev organizations but can't until this issue is resolved.

Thanks.
Steve

**Comment by stephen424242** [comment]
@mjbvz Any update on this? Is it so deep in the backlog it will never get worked?

**Comment by franekp** [comment]
Seems like a low-hanging fruit that could largely improve usability of WebViews.

I would be happy to write a PR if that could possibly speed things up. @mjbvz what do you think?

**Comment by franekp** [comment]
Do I understand correctly that although #79147 is closed, it's not yet possible to use cache when loading (both local and http) resources in a newly-opened WebView?

From what I understand, chrome partitions http cache by origin of the current page/iframe, so each time a new WebView is opened, it starts from an empty cache. I have checked with DevTools that local resouces (`webview.asWebviewUri(vscode.Uri.file(<local-resource>))`) every time return `200 ok` instead of `304 not modified`. Is this behaviour intentional?

**Comment by venkataguddanti** [comment]
We would very much appreciate it if we can get a fix for this issue. I attempted a pull request for this: https://github.com/microsoft/vscode/pull/144055. It was rejected for a valid reason that the change in behavior will be an indirect feature and we need an opt in API.

I do see now that the Webview internal code takes origin as a parameter. Can we now have a public API (WebviewContentOptions?) to pass in the origin or a flag to preserve the origin for webviewpanels? I have a fork with test changes and preserving origin for webviews does improve performance a lot for webviews that are reused/reopened. Features like browse cach/indexDB  etc work well with this test change.

cc @mjbvz

**Comment by mjbvz** [comment]
We now try to maintain a consistent origin for every webview instance of a given type. These origins are unique to the webivew type and to the extension that created the webview. For security reasons, they are also randomly generated and are reset when the user clear their local storage

You can read more about this here: https://code.visualstudio.com/updates/v1_73#_consistent-origin-for-webviews-and-webview-views

If this is causing any issue for webviews in your extension, please open a new issue with details about the problem

**Comment by mjbvz** [comment]
To verify:

1. Using the [webview extension sample](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/README.md)
2. Load up the example webview and add `console.log(window.origin)` to the JS
3. Try opening the webview multiple times and confirm the same origin is always printed
4. Try reloading the window and confirm the same origin is printed
5. Try closing the editor and reloading it. Confirm that the same origin is printed
