### ISSUE TITLE
Debugger UI not activating when triggering breakpoint without focus

### ISSUE THREAD

**Issue by nikita-kiryanov** [microsoft/vscode#132487]
Issue Type: <b>Bug</b>

- Start a debugging session, and place a breakpoint.
- Switch to your app, and cause the breakpoint to be activated.
- The Visual Studio Code icon on the Windows taskbar will flash, indicating new activity.
- Switch to VSCode, and observe that the breakpoint is not highlighted, and the debug controls are not engaged.
- Minimize VSCode and maximize it again. Suddenly the debug UI is active and the breakpoint is highlighted.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4350T CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.25GB free)|
|Process Argv|--crash-reporter-id c0c64dcb-1aca-4f5c-8efc-e2616ece41da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
gitlens|eam|11.6.0
php-debug|fel|1.17.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by roblourens** [comment]
Is this a new issue? Which language are you debugging?

**Comment by weinand** [comment]
I think this is an old issue. There should be a duplicate...

**Comment by roblourens** [comment]
Closest I can find is https://github.com/microsoft/vscode/issues/123257. Can you help find the duplicate @isidorn?

**Comment by nikita-kiryanov** [comment]
@roblourens The language I'm debugging is Python. I think it started happening a 3-4 weeks ago, I'm not sure.

**Comment by nikita-kiryanov** [comment]
@roblourens I tried to follow the steps in issue #123257 that you linked, and it looks like it's the same problem. In #123257 it is said that if you don't maximize your app window, then then bug doesn't trigger, so I tried it, and indeed if I don't maximize the app I'm debugging, then the debug controls in VSCode activate normally.

**Comment by roblourens** [comment]
Ok, thanks for checking that!
