### ISSUE TITLE
Please remove < > angle brackets pair colorization by default in all languages

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#132476]
As per https://github.com/microsoft/vscode/issues/132175#issuecomment-913208461 I would like to ask to remove the default colorization in all languages for the `< >` pair. It creates a lot of issues in `.vue` SFC files, as you can see here:
https://github.com/microsoft/vscode/issues/132175#issue-987246726

Otherwise, we have to specifically ask each community extension developer to include the bracket pair colorization support in their extension, example: Vetur extension for Vue.js here https://github.com/vuejs/vetur/issues/3141
That can be tedious and difficult to solve in the communities. It is easier to remove the `< >` from VSCode altogether, that would solve many of the latest problems related to native bracket pair colorization. Thank you!

**Comment by hediet** [comment]
@alexdima what do you think? I think that's a reasonable request.
I think the current default is more natural, but the requested default is more common (at least in 2021, who knows how programming languages of the next decade look).

**Comment by IllusionMH** [comment]
@hediet It is possible for extension to specify which pairs can be colored? Similar to #131412 which is more user space (settings).

**Comment by lorand-horvath** [comment]
@IllusionMH The ability to customize which pairs to be colored at the extension level, would be nice. I'm not sure @hediet if that is possible and how exactly (there's currently missing documentation about this).

I would even take it another step further: the possibility to choose the color of certain bracket pairs. For example, I would like to have `{{ }}` and `{% %}` in `.vue` and `.liquid` files detected as bracket pairs, but colored differently (i.e. the gray color used for tags in `.html` files). That would be preferable to the default yellow used for the outermost brackets (please see https://github.com/microsoft/vscode/issues/132240#issuecomment-913380862 )

**Comment by hediet** [comment]
@IllusionMH yes that is possible. Every language should have a language-configuration.json, provided by some extension (the file can be named differently though). This file can define general brackets, [but also which brackets to colorize](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json#L11).

**Comment by lorand-horvath** [comment]
> 
> @IllusionMH yes that is possible. Every language should have a language-configuration.json, provided by some extension (the file can be named differently though). This file can define general brackets, [but also which brackets to colorize](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json#L11).

@hediet I have checked and double checked, but I can't find for the life of me a configuration file for either Vetur (for .vue files) or Liquid (for .liquid files), so where exactly should we add the `"colorizedBracketPairs"` option for these languages?

**Comment by glcraft** [comment]
I have the same issue in Rust language : 
![image](https://user-images.githubusercontent.com/6421451/132323792-cf1099bd-58a9-4330-8a41-081338fc76dc.png)

**Comment by lorand-horvath** [comment]
> @alexdima what do you think? I think that's a reasonable request.
> I think the current default is more natural, but the requested default is more common (at least in 2021, who knows how programming languages of the next decade look).

@hediet looks like @alexdima approves of this (thumbs up reaction).

**Comment by hediet** [comment]
Btw. this is a nice issue for external contribution! 😉

**Comment by alexdima** [comment]
:+1: for tweaking the fallback path in case `colorizedBracketPairs` is not defined, we could use `brackets` and always remove the problematic `<`,`>` pair . Sorry, I should have been more explicit than just a thumbs up.

**Comment by glcraft** [comment]
> I have the same issue in Rust language :
> ![image](https://user-images.githubusercontent.com/6421451/132323792-cf1099bd-58a9-4330-8a41-081338fc76dc.png)

In the last version of [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer), the language server is now aware of the bracket and disable coloring brackets. It's not a problem anymore.

**Comment by lorand-horvath** [comment]
@hediet thank you for https://github.com/microsoft/vscode/commit/152413e0a8d222cc88c3394cc27cf1b92944a7b8
