### ISSUE TITLE
VS Code does not stick to downgraded version

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode#132453]
Issue Type: <b>Bug</b>

After having the latest version and finding errors, trying to downgrade is possible, but then VS Code still updates itself on next or next after restart. Seems like the update that was downloaded, takes control, even if update mode is none and automatic updates is unchecked.

I was having 1.60 installed automatically, but found serial port errors on Arduino Extension, and wanted to downgrade.

Uncheck Enable Windows Background Updates
Set Update mode to "none".

Download 1.58.2 and install it.

Restart a few times, and boom, 1.60 is in action again.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (16.52GB free)|
|Process Argv|--crash-reporter-id 937b32ac-d42d-4d5c-8600-a5390f81789c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.1.0
gitlens|eam|11.6.0
output-colorizer|IBM|0.1.2
remote-wsl|ms-|0.58.2
hexeditor|ms-|1.8.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by joaomoreno** [comment]
Can you reproduce this on a fresh VM?

**Comment by iqapps** [comment]
Not running VM..sorry

**Comment by joaomoreno** [comment]
I can't reproduce this locally, unfortunately.

**Comment by iqapps** [comment]
hmm...it very consistent. Where can I find the downloaded 1.60 update files on my local disk. Maybe I can delete these.

**Comment by joaomoreno** [comment]
Yes. One thing to try is just to remove everything VS code related from your system and reinstall from scratch. You might have two simultaneous installations.

**Comment by iqapps** [comment]
Checking - yes, I do. I have both the User mode install and the system mode install. Let me try uninstall the user mode install, and retry. I bet you are right about this.

**Comment by iqapps** [comment]
Just tested it again.

Uninstalled the user mode app, and restarted a number of times, no updates coming through. Seems like the user mode was the updated one.

User mode app was started as preferred app on .log files, while the system mode app was started from shortcut.

You can close this. Sorry for the inconvenience.
