### ISSUE TITLE
Makefile grammar for function call separator syntax

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#132473]
The `,` needs a syntax grammar

<img width="890" alt="Screen Shot 1400-06-15 at 19 11 45" src="https://user-images.githubusercontent.com/2157285/132234624-0b0ea0f7-bb6b-422d-a199-186680abb5a0.png">

**Comment by alexr00** [comment]
Moved to upstream repo: https://github.com/fadeevab/make.tmbundle/issues/12
