### ISSUE TITLE
Issues in `mainThreadWebViewPanel` using `columnToEditorGroup`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132421]
I am not sure if this is surfacing in issues already, but I noticed how the `columnToEditorGroup` usage in `mainThreadWebViewPanel` is dangerous. That method can return `ACTIVE_GROUP` (value `-1`) or `SIDE_GROUP` (value `-2`) and as such cannot be used to resolve an existing group. 

https://github.com/microsoft/vscode/blob/75aa22e7d99b6353bfc4543218d50d04fbbe04cf/src/vs/workbench/api/browser/mainThreadWebviewPanels.ts#L165-L165

https://github.com/microsoft/vscode/blob/75aa22e7d99b6353bfc4543218d50d04fbbe04cf/src/vs/workbench/api/browser/mainThreadWebviewPanels.ts#L206-L206

You can safely pass the result into any `IEditorService.openEditor` call as last argument though.

**Comment by mjbvz** [comment]
Thanks for noticing this @bpasero! It does look like the current webview implementation has some bugs because of this

Is there a way to resolve `ACTIVE_GROUP` or `SIDE_GROUP` to an `IEditorGroup`? I see `findGroup` but an not sure it does what I need

**Comment by bpasero** [comment]
@mjbvz yeah `findGroup` would help but it requires you to pass in an editor input and it has some internal rules how to return a group when the editor is already opened, so it may not be what you want.

Why do you need the group to begin with? The idea with `ACTIVE_GROUP` and `SIDE_GROUP` is to use with `IEditorService`.

As a workaround if you must operate on groups you could:
* `ACTIVE_GROUP`: `IEditorGroupService.activeGroup.openEditor`
* `SIDE_GROUP`: `IEditorGroupService.sideGroup.openEditor`

**Comment by mjbvz** [comment]
Thanks @bpasero. I've revised the webview logic to pass the group identifier instead of an  `IGroup`. With the changes that we made for custom editors, I think simply calling `openEditor` does the right thing in these cases now
