### ISSUE TITLE
Would it be helpfull using Tabs instead of dropdown for  Integrated Terminal windows And feature for switching between the tabs.

### ISSUE THREAD

**Issue by aptro** [Microsoft/vscode#13248]
VSCode Version: 1.5.3
OS Version: Ubuntu 16.04

Current:
![a](https://cloud.githubusercontent.com/assets/10391409/19113668/5546b324-8b28-11e6-8f20-0377a7ba4ea4.png)

Same as Editor windows for Integrated terminal
![b](https://cloud.githubusercontent.com/assets/10391409/19113672/59f9fdae-8b28-11e6-8179-2b36f27706ed.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546

You can set keybindings to move to the next and previous terminal already, this is what mine look like:

```js
{ "key": "ctrl+shift+j",    "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",    "command": "workbench.action.terminal.focusPrevious" },
```
