### ISSUE TITLE
VS Code freezes when using PHP Debug and PHP Xdebug

### ISSUE THREAD

**Issue by DevManPGP** [microsoft/vscode#132409]
Issue Type: <b>Performance Issue</b>

I have been using these two extensions along with VS Code for almost a year now with no issues. Last week, I tried to debug a php page and it was not working anymore. I uninstalled and reinstalled the extensions many times. I also reset IIS webs server for PHP and verified nothing has changed on my Windows 10 Pro PC. I finally got it working again but it takes like 3-5 minutes for the VS Code to unlock and display at the break point. From there F11 works fine. It does this on every page breakpoint coming from Chrome to VS Code. At the breakpoint, VS Code flashes immediately on the taskbar. Opening VS Code to walk through, shows the app frozen for minutes until active again. After getting this far, I noticed that VS Code was updated in August to 6.1. That would be the only thing that changed (which I wish I knew before hand) on my pc! So logic dictates VS Code version 1.6 as the most likely cause! Please check it out and fix if possible. Thanks! Paul

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (26.45GB free)|
|Process Argv|--crash-reporter-id eedfb54f-df69-4190-b77a-4f75ef872706|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    82	  1404	code main
    0	    24	  1996	   crashpad-handler
    0	    82	  5136	   shared-process
    0	    74	 12932	     ptyHost
    0	    67	   764	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 12764	       console-window-host (Windows internal process)
    1	    74	 12412	   window (Issue Reporter)
    0	    37	 14040	   utility
    0	   128	 15408	   window (Welcome - ElectroRestore - Visual Studio Code)
    0	    12	  5408	     watcherService 
    0	    11	  2336	       console-window-host (Windows internal process)
    0	   121	  7096	     extensionHost
    0	    84	 16172	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - ElectroRestore - Visual Studio Code)
|    Folder (ElectroRestore): 363 files
|      File types: jpg(81) php(68) asp(63) png(18) inc(13) txt(12) js(11)
|                  css(8) svg(7) json(6)
|      Conf files: launch.json(2) settings.json(2)
|      Launch Configs: php(2);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.7.1
vscode-mysql-client2|cwe|4.1.2
php-debug|fel|1.17.0
php-xdebug|kak|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
javagetstartedc:30351792
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by lramos15** [comment]
Please open an issue against https://github.com/xdebug/vscode-php-debug/issues since this appears to be an issue with the debug extension.
