### ISSUE TITLE
Using "<" and ">" in CodeLens Command tilte

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#13242]
- VSCode Version: Latest Insiders 
- OS Version: Windows 10

Steps to Reproduce:

1. Set command title for code lens to something containing lot of "<" and ">" (for example: `a : Async<Choice<int,string>> -> Choice<string,int>`

![image](https://cloud.githubusercontent.com/assets/5427083/19111186/81571ae6-8afe-11e6-8c61-59f2717401dd.png)

I guess it's side-effect of using CodeLens for unexpected stuff ;) 

Reported by @vasily-kirichenko in https://github.com/ionide/ionide-vscode-fsharp/issues/181

**Comment by Krzysztof-Cieslak** [comment]
Looks like command.title should be escaped here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codelens/browser/codelens.ts#L107-L129 

I'll PR change.

**Comment by jrieken** [comment]
Great - waiting for PR

**Comment by Krzysztof-Cieslak** [comment]
Also, you can do crazy bad things like: 
![image](https://cloud.githubusercontent.com/assets/5427083/19112302/66a69a54-8b04-11e6-83cf-b06a3080f066.png)

Reported by @duckmatt
