### ISSUE TITLE
Search within file responsiveness is broken

### ISSUE THREAD

**Issue by omonimus1** [microsoft/vscode#132428]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: Windows 11

Steps to Reproduce:

1. Open 2 files in parallel (one next to each other
2. Open the file explorer
3. Search something with the file closed to the file exploired (via search functionality)
4. In few but boring cases, the responsiness of the search input text does not work. 
5. The general Rule is that the search input text does not cover the number of the line, but in that specific case, it slight break. Is very annoying. 
![image](https://user-images.githubusercontent.com/23085146/132175611-25c5a220-6f7e-4222-a1b3-217e1a3966b7.png)
![image](https://user-images.githubusercontent.com/23085146/132176160-eec3ac16-3d7c-4e10-b6c3-d51f59eb57c6.png)

**Comment by amunger** [comment]
this seems to be fixed, or maybe I'm not following the repro steps correctly

> Search something with the file closed to the file exploired (via search functionality)

is not clear to me.
