### ISSUE TITLE
I set matchBrackets to never but it became false after close and open editor

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#132449]
vscode

Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.6.0

mac 11.5.2 (20G95)

the right setting for  `edit.matchBrackets` is

```
{
   editor.matchBrackets:"never"
}
```

When I save the setting.json. it's good. But when I close the app, then open it again, it becomes like this.

<img width="979" alt="Screen Shot 2021-09-06 at 6 36 20 PM copy" src="https://user-images.githubusercontent.com/538657/132212203-c292eb07-a7f5-4bf5-bccb-053c64b9f72e.png">

**Comment by gjsjohnmurray** [comment]
I see you are running 1.55. Are you able to update and re-test?

**Comment by craigcosmo** [comment]
I updated to vscode 1.6 still there same bug

<img width="973" alt="Screen Shot 2021-09-07 at 6 25 04 AM" src="https://user-images.githubusercontent.com/538657/132265449-f05e757d-2637-4b69-9dca-12b9734b881c.png">

**Comment by gjsjohnmurray** [comment]
Does the problem happen when you run the `Developer: Reload Window` command?

What about after the command to reload with all extensions disabled? Maybe one of your extensions is writing this bad setting when it activates.

**Comment by craigcosmo** [comment]
`Developer: Reload Window` still dont fix.

`reload with all extensions disabled` also dont fix

**Comment by gjsjohnmurray** [comment]
Are you using Settings Sync?

**Comment by craigcosmo** [comment]
disable all the extension will work.

So I figure there is one extension that cause this, it's `subtle match brackets` https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets

you are right, it's badly written
