### ISSUE TITLE
executeCommand don't follow promise ordering to execute

### ISSUE THREAD

**Issue by iamwwc** [microsoft/vscode#132446]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
> Version: 1.60.0 (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
- OS Version:
MacOS big sur 11.5.2

Steps to Reproduce:

1. install https://marketplace.visualstudio.com/items?itemName=ctf0.macros
2.
use this settings
```
"macros.list": {
        "restart": [
            "workbench.action.debug.stop",
            {
                "command": "$delay",
                "args": {
                  "delay": 100
                }
              },
            "workbench.action.debug.start",
        ]
    },
```
3. use follow shortcut

```json
    {
        "key": "f4",
        "command": "macros.restart",
        "when": "inDebugMode"
    },
```

4. open any project, press f4 to debug. There should hit confirm restart dialog
5. change 2 delay to 500
```
"macros.list": {
        "restart": [
            "workbench.action.debug.stop",
            {
                "command": "$delay",
                "args": {
                  "delay": 500
                }
              },
            "workbench.action.debug.start",
        ]
    },
```

6. press f4, there aren't confirm restart dialog showing

there are same question.
https://github.com/Microsoft/vscode/issues/10534

**Comment by iamwwc** [comment]
@weinand Does this issue has some result? 😃

**Comment by weinand** [comment]
@iamwwc what is the exact reason that you cannot use "Restart" to do the "Stop"/"Start" sequence?

**Comment by iamwwc** [comment]
> @iamwwc what is the exact reason that you cannot use "Restart" to do the "Stop"/"Start" sequence?

"Restart" in Rust will use previous binary. But I have changed my codes already, so I want to stop first, then start again, extension(lldb) will first recompile my codes.

**Comment by iamwwc** [comment]
It's important for Non-interpreter language. Javascript's "Restart" will re-interpreter codes, so it will always use latest codes. But in others, possibly not

**Comment by iamwwc** [comment]
Currently I'm using https://marketplace.visualstudio.com/items?itemName=geddski.macros, executing `workbench.action.debug.stop`, `workbench.action.debug.start` sequentially. But 

settings.json
```json
    "macros": {
        "restart": [
            "workbench.action.debug.stop",
            "workbench.action.debug.start"
        ]
    },
```

shortcuts
```json
    {
        "key": "f4",
        "command": "macros.restart",
        "when": "inDebugMode"
    },
```
But after pressed F4, `'xxxxx' is already running. Do you want to start another instance?` dialog showed. I guess `stoped` state from one process don't sync to another process. It I delay some second, there no dialog showing.

**Comment by iamwwc** [comment]
@weinand  In clion(a jetbrains rust IDE), there are option showing that we can disable dialog forever. 

After clicking `stop and rerun`, **recompile** is the first step.

![image](https://user-images.githubusercontent.com/24750337/141762332-66c1a83e-55df-4b4c-8dfe-33bbffa91774.png)

**Comment by iamwwc** [comment]
@weinand Does have any progress?

**Comment by iamwwc** [comment]
@weinand 😃 Does have some result?

**Comment by roblourens** [comment]
There is an await missing here: https://github.com/microsoft/vscode/blob/d2114a401eb6dbe161ca447761758b06b6322dbc/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L575

But I'm not sure whether that's enough to fix this issue. Would take a PR for it if someone else has the time to debug and investigate.

**Comment by roblourens** [comment]
Recently made the same fix 2 lines above: https://github.com/microsoft/vscode/pull/166137. I think just adding the await is fine.

**Comment by iamwwc** [comment]
@roblourens I can still reproduce this bug in insider
```
Version: 1.75.0-insider (user setup)
Commit: 243854703b7fa371abb752ec0df7817a615a308b
Date: 2023-01-13T07:48:05.934Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

**Comment by roblourens** [comment]
Works fine for me, debugging in node, even with no delay. If you still see it, it could be an issue on the debug adapter's end? What are you debugging? Consider filing an issue on the debug extension.

**Comment by iamwwc** [comment]
If we have the prebuild task take 10s to finished in `tasks.json`. Before vscode's toolbar become to yellow, press F4 will cause confirm restart dialog showing up

**Comment by roblourens** [comment]
Ok but that will be sort of a different issue, if you open another issue I can take a look.

**Comment by iamwwc** [comment]
@roblourens Ok https://github.com/microsoft/vscode/issues/172346
