### ISSUE TITLE
Skip Inlay Hints for implicit variable types when instantiated with a new function

### ISSUE THREAD

**Issue by voxpelli** [microsoft/vscode#132471]
I would like the following to not get an implicit variable types inlay hint:

```javascript
const foo = function () {
  return 'bar';
};
```

```javascript
const foo = () => 'bar';
```

Especially if I already have the inlay hints on for the function itself, then I don't need to be told both that the function will return `string` and that `foo` is of type `() => string`.

Its the worst for arrow functions, as the implicit variable type and the definition of a short arrow function are very similar looking, making it very hard to navigate when both are around.

### Examples:

![Skärmavbild 2021-09-06 kl  16 24 44](https://user-images.githubusercontent.com/34457/132231654-1391d51c-b3a2-4547-b151-e59effa83bca.png)
![Skärmavbild 2021-09-06 kl  16 24 57](https://user-images.githubusercontent.com/34457/132231664-ae8afd23-1f3b-4ad6-95ba-19a2665f3e8a.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
