### ISSUE TITLE
Debug Console suggestions do not auto-complete properly

### ISSUE THREAD

**Issue by blimmer** [microsoft/vscode#132415]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z (4 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. Clone my sample repo and install the dependencies: https://github.com/blimmer/vscode-issue-repro
```
git clone https://github.com/blimmer/vscode-issue-repro.git
cd vscode-issue-repro
npm ci
```
2. Open the terminal window (Command + `)
3. Create a "Javascript Debug Terminal" (Click "+" and choose "Javascript Debug Terminal")
4. Run `index.ts` with `ts-node`
```
ts-node index.ts
```
5. When the `debugger` breakpoint is hit, click the "Debug Console" tab in the terminal window.
6. Start typing `myObj.` - you'll see the intellisense popup come up and correctly suggest the properties `foo`, `bar` and `baz`. However, selecting from these suggestions does not work properly. There are a few times it doesn't work.
a) When the popup first appears. For instance, if `myObj.` highlights `myObj.foo` as the suggestion, I expect I could hit "Enter" and the terminal bar would be autocompleted to `myObj.foo`. However, the string entered is `myObj.`.
b) When using the arrow keys to select a suggestion. For instance, if you type `myObj.ba`, press the down arrow key (so `myObj.baz`) is highlighted and press "enter". I expect the string `myObj.baz` to appear in the debug console, but `myObj.ba` is what gets entered.

I've got an example of this issue in the gif below:

![issue](https://user-images.githubusercontent.com/630449/132153180-673b089e-109f-4342-8ae8-70f770e07860.gif)

**Comment by connor4312** [comment]
The debug console inserts completions on tab by default, you can see the reasoning here: https://github.com/microsoft/vscode/issues/108439#issuecomment-871521843

This can be controlled via the `debug.console.acceptSuggestionOnEnter` setting.
