### ISSUE TITLE
Circular dependecies are not handled correctly when uninstalling extension packs

### ISSUE THREAD

**Issue by mkko-dev** [microsoft/vscode#132436]
Issue Type: <b>Bug</b>

- Install Docs Authoring Pack (docsmsft.docs-authoring-pack)
- Uninstall it
- voila:
 Cannot unistall 'D.A.P.'. It includes unistalling [...] and 'D.A.P' extension depends on this.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
I can not reproduce. This works just fine for me.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
