### ISSUE TITLE
new powershell default keeps opening on startup despite having set the default back to cmd

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#132480]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Win10 pro x64

Steps to Reproduce:

1. ctrl-shift-p -> Terminal: selected default profile -> set "command prompt" as the default terminal to use (because powershell does not support cross-platform syntax like `&` chaining, making it utterly useless for cross-platform projects)
1. make sure the workspace has a terminal open, and that it's a "command prompt" terminal.
1. close VS code
1. reopen VS code for the same dir/project
1. VS code reopens with a powershell terminal instead of a "command prompt" terminal.

Rechecking the default terminal profile, it's still set to "command prompt", so this feels like a bug, especially given the next behaviour:

1. click the powershell terminal
1. type `exit` and hit enter
1. the integrated terminal panel disappears
1. ctrl-shift-` to open a new terminal
1. the terminal panel is restored, with the new terminal opened being the expected "command prompt" terminal.

**Comment by Pomax** [comment]
@IllusionMH the first one is about remote workspaces, which doesn't apply here, the second appears to be a closed issue that concluded with a workaround, not a proper fix?

**Comment by IllusionMH** [comment]
Why workaround? First issue closed with commit to `main` branch as third action on it. It needs to be added to recovery for stable release. 
Second issue is basically same but found in Insiders before 1.60 and reproducible without remote.

**Comment by Pomax** [comment]
ah. Missed that part, thanks.
