### ISSUE TITLE
With bracket colorization, handle symmetric block of brackets in a single color

### ISSUE THREAD

**Issue by Nahor** [microsoft/vscode#132488]
To avoid an overload of colors, it would be nice that for the new bracket colorization, if there was an option to keep symmetric "chunks" of brackets in a single colors. IMHO, the colorization is mostly used to easily identify which opening goes with what closing. If multiple openings and multiple closings are both clump together, it's not that useful to know which specific opening bracket goes witch what specific opening bracket (especially since the colors are eventually reused).

C++ example of a current rendering:
![image](https://user-images.githubusercontent.com/1198364/132250398-3aa84f4a-8a95-4e9a-b4b8-e852bc1094c3.png)

Proposed feature:
![image](https://user-images.githubusercontent.com/1198364/132251108-f87c465f-4a70-47a1-8f4f-43ecd4683bf4.png)

In this particular example, the "[[" of the C++ attribute are not really individual brackets. Rendering then in separate colors is counter-productive.
For the struct, being able to identify each individual nested struct is not really useful. And even if it was, I think it's actually more readable with a single color because it provides a helpful "layer of nesting", with one layer for S1-S3, and another for S4-S6.

**Comment by lorand-horvath** [comment]
This would also solve the .vue and .liquid issues when using `{{` and `}}` output tags in one sweep.

**Comment by hediet** [comment]
I think the feature is easy to implement, but I'm not certain yet that it is a good feature that solves a real problem.
I see its usefulness for C++, but maybe the underlying problem is something else.

I wonder how C++ parses `[[maybe_unsed] ] S6 s = ...;`. I also wonder if `[[` is a single token. 

In JS, you can easily do `[[1]]` to create a nested array. It would be strange if this is colorized differently, even though it is the very same expression:
```
[
    [
        1
    ]
]
```

**Comment by Nahor** [comment]
@hediet 
It's not really about "ambiguous pairs" or "accuracy". It's about cluttering. Too many color changes make it harder to read the code. In the first line, it's hard to find the "i" in the middle of all those "{" and "}". The "i" is the most important, the color of the brackets is secondary, and yet, that's what attract the attention the most.

For C++, I don't know if "[[" for attributes is technically a single token or not, but semantically at least it is.

I also don't know if newlines between brackets should count as part of the group or not. My initial idea was that it wasn't. The goal of the feature is to avoid the cluttering caused by too many color changes. When there are newlines, the cluttering is less pronounced and the indentation is (at least for me) primary way to distinguish between pairs.
A more ambiguous case is "[ [ [" (while spaces between brackets). Personally, I don't have white between consecutive brackets, but some C/C++ coding conventions do.
Maybe this could be part of the setting for the feature: "useSameColorForBracketGroup = [ false | consecutive | consecutiveWithShitespaces ]"

Another ambiguous one is: should it be all the same brackets or any combination, i.e. "(([((" should that be 3 colors or one? I'm more in the camp of "one" but I can see that on occasion "3" would be useful. That said, personally, I think I would rely on spaces or newline+indentation anyway for the cases where "3" would be beneficial. So "one" would be my preferred choice.

@lorand-horvath
I don't know vue nor liquid, but from the sound of it, you're more advocating for "multicharacter brackets". My proposed feature is for any combination of brackets. Having the manually list all combinations of '{', '(' and '[', in any reasonable number would be a major pain, and a performance bottleneck as well (for up to 3 characters, that's 72 combinations, for 4 that's 234), and ambiguous (if combination of 3 is defined, what is "{{{{{" (5)? It's 3+2 or 2+3 or 5? If combination of 4 is defined, add 4+1 and 1+4 to the potential list)
