### ISSUE TITLE
Add accent-color to CSS IntelliSense

### ISSUE THREAD

**Issue by SjorsHartwijk** [microsoft/vscode#132477]
New feature since Chrome 93+ 

https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

**Comment by aeschli** [comment]
I updated the css language service with the latest css properties.
-> IntelliSense and hover are now supported
Syntax highlighting needs to come from the css grammar. See #132498

**Comment by jrieken** [comment]
@aeschli Not seeing the mentioned `accent-color`-property

<img width="405" alt="Screen Shot 2021-09-28 at 14 21 15" src="https://user-images.githubusercontent.com/1794099/135085592-b3d44962-f2e7-4b09-8381-314052230e79.png">

**Comment by aeschli** [comment]
Thanks, service update was missing: e653defeca8b1bba196a274407e64bbfa3119fbb
