### ISSUE TITLE
Bracket pairs should not be colorized in .txt files or any other non-programming language related files

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#132432]
As per #132240 bracket pairs should not be colorized in .txt files or any other non-programming language related files.

**Comment by hediet** [comment]
Makes sense. This can be fixed by setting [this](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json#L11) for .txt and other files.

**Comment by lorand-horvath** [comment]
@hediet Would be good to know how to do that.
I've created a `txt` folder inside `c:\Program Files\Microsoft VS Code\resources\app\extensions\` and created a language-configuration.json file in it with the following json `{ "colorizedBracketPairs": [] }` - an empty array because I don't want any brackets colorized for .txt files, but that doesn't work.
I have the exact same problem for .vue files where, in turn, even the <> tags are colorized (inside the <template> section of the .vue file) which I don't want to be colorized.
Would be good to know how to fix these specifically, per file type/extension (or language type). Thanks.

**Comment by Suven-p** [comment]
Would these be non-programming languages? diff, dockerfile, dockercompose, git-commit, git-rebase, ignore, ini search-result, shaderlab, xsl

**Comment by lorand-horvath** [comment]
@Suven-p Good question... I think only the angle brackets `< >` colorization should be removed by default, from ALL languages/file extensions, and I hope that will be the road taken in #132476

**Comment by Suven-p** [comment]
I couldn't figure out a way to pull changes from microsoft/vscode without introducing additional pull requests to existing pull request.

**Comment by gjsjohnmurray** [comment]
@Suven-p to avoid this you should have created a branch, made your change on the branch, then submitted the branch as a PR.
