### ISSUE TITLE
XML content encoding detection bad or broken

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#132466]
Issue Type: <b>Bug</b>

XML content encoding detection is highly annoying due to it being either bad or plain broken

XML specifically has embedded declarative encoding information which clearly defines the encoding of an XML document, e.g. `<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>`

vscode unfortunately totally ignores the encoding attribute and performs automagic - and then detects UTF-8, which is plain wrong.

While I do agree philosophically that everything except UTF-8 ought to be shredded and burnt, in real life, we have ISO-8859-1 or other ISOs, and working with those inside vscode is very unpleasant right now. To reproduce, create a text document on disk with content
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<WithLove>
    ... an alle Entwickler im Kanton Zürich, 
    die ähnlich wie ich 
    öfters einmal auch in 
    lustige Probleme hineinlaufen ... 
</WithLove>
```
and do make sure that the above funkiness is really persisted as ISO-8859-1, because otherwise the umlauts (äöü) prevalent in the German language("s") won't show up. Load text file into vscode and

//exp: detected encoding == iso-8559-1 (based on xml declaration)
//act: utf-8

This is not limited to iso-8559-1; much fun can be had with incrementing to -2 (ő - ű) or -7 (Ελληνικά).

I do appreciate that for other text documents, heuristics are the only way forward, but XML is rather explicit:  https://www.w3.org/TR/xml/#dt-xmldecl

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.13.13-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.31GB (17.14GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn478:30356813
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by shoffmeister** [comment]
Please note that this is core functionality and all extensions were disabled.

**Comment by LinoBarreca** [comment]
"it's not a bug. it's a feature request." (cit.)
