### ISSUE TITLE
Logpoint work like breakpoint

### ISSUE THREAD

**Issue by ShadowInks** [microsoft/vscode#132439]
Issue Type: <b>Bug</b>

 I created a logpoint  in my code and run the debugger,but no log in debug console , instead it breaked in logpoint as if i create a breakpoint
![image](https://user-images.githubusercontent.com/42799053/132191951-32fa6bc9-5195-46d2-948c-6fa19b4fd7cd.png)

![image](https://user-images.githubusercontent.com/42799053/132191829-efcfd1ae-02a0-4ca5-8c52-8375987bd441.png)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0050

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.12GB free)|
|Process Argv|--crash-reporter-id d07b1d82-52e9-4455-90d3-af7bb39f237a --crash-reporter-id d07b1d82-52e9-4455-90d3-af7bb39f237a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 9.134.25.65|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0050|
|CPUs|Intel(R) Xeon(R) Gold 61xx CPU (32 x 2494)|
|Memory (System)|125.34GB (3.03GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.60.2
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
vscode-icons|vsc|11.6.0
vscode-bazel|Baz|0.4.1
githistory|don|0.6.18
gitlens|eam|11.6.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.60.2
python|ms-|2021.9.1191016588
cpptools|ms-|1.6.0
rdhelper|RDM|1.6.35
vscodeintellicode|Vis|1.2.14
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by ShadowInks** [comment]
i found some error in developer console
![image](https://user-images.githubusercontent.com/42799053/132196371-b650bb12-b364-4c7f-bc03-d12889ad362b.png)

contextKeyService.ts:432 Element already has context attribute: inputContainer

**Comment by weinand** [comment]
/extCpp

If Logpoints are not supported by C++, they will bahve like breakpoints.

**Comment by ShadowInks** [comment]
well thanks ,indeed  it's  a bug of C/C++ Extension v1.6.0 ,https://github.com/microsoft/vscode-cpptools/issues/8065
