### ISSUE TITLE
Include setting for default Source Control sort criteria 

### ISSUE THREAD

**Issue by kadireryigit** [microsoft/vscode#132423]
Hi Microsoft and VScode devs,
It would be nice if there was a setting to choose the default sort order for the Source Control pane.  
It is sorted by Path by default so I have to set it to sort by Status manually every time I reopen the editor.  
![vscode_feat](https://user-images.githubusercontent.com/24525647/132170632-33279746-abed-4907-ad4b-54b68f827823.png)
This is also reported as a bug in [#127952](https://github.com/microsoft/vscode/issues/127952)

Thanks and regards.
Kadir

**Comment by joaomoreno** [comment]
Dupe https://github.com/microsoft/vscode/issues/120271
