### ISSUE TITLE
August 2021 Endgame Recovery

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#132426]
- [x] Create a milestone `<Month> <Year> Recovery` **owner**
- [x] Bump the version number **owner**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22August+2021+Recovery%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit **@alexdima**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit **@alexdima**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 **@bpasero**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal **@sandy081**
    - [x] Intel **@isidorn**
    - [x] Intel server **@isidorn**
    - [x] Apple Silicon **@sandy081**
  - [x] Linux x64
    - [x] deb **@aeschli**
    - [x] rpm **@aeschli**
    - [x] archives **@aeschli**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) **@aeschli**
  - [x] Linux server
    - [x] x64 **@chrmarti**
    - [x] x64 Alpine **@chrmarti**
    - [x] ARM32 **@chrmarti**
    - [x] ARM64 **@chrmarti**
- [x] Publish website **@sana-ajani**
- [x] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by gjsjohnmurray** [comment]
@meganrogge #132150 needs to be a candidate for this. I hope the fix you pushed also resolves the similar symptoms with tasks.

**Comment by formulahendry** [comment]
Please include https://github.com/microsoft/vscode/issues/132150 in Recovery release, a lot of VS Code users and extension users are impacted by this.

**Comment by tomaxsas** [comment]
This should be fixed #132519

**Comment by IllusionMH** [comment]
Please consider PR #132851 for Recovery as it resolves set of terminal issues that are not handled by fix for #132150
