### ISSUE TITLE
can't type in CLI

### ISSUE THREAD

**Issue by castbreeder** [microsoft/vscode#132411]
We have written the needed data into your clipboard because it was too large to send. Ple
Issue Type: <b>Bug</b>

VSC restarted, reinstaled, disabled extensions

thank you

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (15.88GB free)|
|Process Argv|--crash-reporter-id ae95890a-6d51-44ad-8915-512155ef76c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Coderslang|Agi|0.3.13
vscode-javascript-snippet-pack|aka|0.1.6
vscode-browser-preview|auc|0.7.1
markdown-preview-github-styles|bie|0.2.0
generate-wt-scheme|bla|0.0.5
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
json-tools|eri|1.0.2
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
iceworks-time-master|ice|1.0.2
markdown-extended|jeb|1.0.19
fluent-icons|mig|0.0.12
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
Terminal-StatusBar|Tho|0.0.5
react-component-generator|udi|1.0.2
full-react-snippets|wal|1.4.2
vscode-js-console-utils|wht|0.7.0
js-runner|Zol|3.2.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

ase paste.

**Comment by meganrogge** [comment]
Please create an issue with actionable information
