### ISSUE TITLE
Debug console is missing horizontal scrollbar

### ISSUE THREAD

**Issue by Rademenes16** [microsoft/vscode#132408]
I wish there was a horizontal scrollbar or at least word-wrap for debug console. I quickly made 2 arrays consisting of 200 numbers and I can't see more than my window size allows to. 
https://imgur.com/a/Bmi8aC2

**Comment by roblourens** [comment]
The preview does not wrap, but you can click that item to expand it.

**Comment by roblourens** [comment]
There is a setting for this, `"debug.console.wordWrap"`
