### ISSUE TITLE
Source Control using parent folder repository, when current folder is a git repository

### ISSUE THREAD

**Issue by flleeppyy** [microsoft/vscode#132496]
Issue Type: <b>Bug</b>

Source control uses the parent git repository instead of the git repository inside the folder that vscode has open.
Hopefully this acsii tree demonstrates it.

```
parent-repo/
├─ .git/ (Source control is prefering this repo)
├─ plugins/
│  ├─ plugin-repo/ (This folder is open in VSCode)
│  │  ├─ .git/ (Source control SHOULD be preferring this one)
├─ .gitignore (contains a line for the plugins folder)
```

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (12 x 3393)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.82GB (0.17GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8ea9290f-6f71-48b2-a9c4-91d69f4e556c|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
path-intellisense|chr|2.4.0
dart-code|Dar|3.26.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
escaping-characters|drp|1.0.0
vscode-html-css|ecm|1.10.2
vscode-firefox-debug|fir|2.9.4
vdf|GEE|0.0.7
html-slim-scss-css-class-completion|gen|1.7.8
ctrl-semicolon|Gfo|0.1.0
copilot|Git|1.4.2586
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
discord-vscode|icr|5.7.0
vscode-cdnjs|Jak|0.19.0
vue|jcb|0.1.5
webpack|jer|2.2.0
vscode-position|jtr|1.0.3
google-fonts|lio|0.0.1
pretty-formatter|mbl|0.2.2
regexsnippets|Mon|1.0.2
vscode-scss|mrm|0.10.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
js-debug-nightly|ms-|2021.9.417
vscode-typescript-next|ms-|4.5.20210905
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.34.1
material-icon-theme|PKi|4.10.0
java|red|0.81.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
vs-code-prettier-eslint|rve|3.0.4
background|sha|1.1.28
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
prettier-vscode|Sim|2.0.7
vue-docs|tit|1.0.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
qf|Wsc|6.8.122

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by eamodio** [comment]
In this case, you don't see both repositories? What do you have `git.autoRepositoryDetection` set to, as that will determine how we find repositories.

**Comment by studgeek** [comment]
I'm not 100% certain I understand the exact issue this bug is reporting, but do see #133577 which I think may cover this case. It includes concrete reproduction steps.
