### ISSUE TITLE
Support debug terminal across languages (and debuggers)

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#132437]
Provide better support for the following scenario (from https://twitter.com/marksaroufim/status/1433549022191513625?s=19):
> "an executable that launches a Python program that then talks to a Java codebase and back."

VS Code already supports concurrent debug sessions for different languages.
But the tricky part is to start the different debugging sessions so that they are available if the code is hit for the first time.

In the scenario from above it might be difficult to control from outside of the executable that the Python program and the Java code is run in debug mode: Running the Python and Java code in debug mode might need to pass specific arguments to the corresponding runtimes. Only if the "codebase" is part of a server, then it can be easily started ahead of time in debug mode.

Here it would help if all debuggers would support the "inverted" mode that our "js-debug" supports as the "JavaScript debug terminal":

In "inverted" mode it would be possible to set some magic environment variable (which automatically gets inherited to subprocesses), and then all involved debuggers/runtimes would "call back" into VS Code in order to start debug sessions.

**Comment by connor4312** [comment]
So far we've not heard much from other folks wanting this, nor have we seen other "X Debug Terminals" in spite of the popularity of the JS Debug Terminal. Though we've also made a [contribution mechanism](https://github.com/microsoft/vscode-js-debug/blob/main/EXTENSION_AUTHORS.md#extension-api) for the js-debug terminal for other runtimes to contribute to its creation. Maybe that will evolve in the future to a generic debug terminal, but for now I will close this for housekeeping
