### ISSUE TITLE
New option: Folding does not open

### ISSUE THREAD

**Issue by miko-github** [microsoft/vscode#132514]
#### How good it would be if we could lock the code blocks fold so they wouldn't open again?!

Hi [**vscode**](#) Developers :wave:,

i working with some JS/TS codes in single file with some of function

who i want to folding them, but, when i save the file, folds open and

file-view show very bussy and i confusing to find my block and again

 i should fold all block and unfold my block

so, if we lock block, then we are happy :smile: 

> sorry if it isn't correct because i'm use **G Translate** :sweat_smile: 

THANKS :heart: :+1: :v: 

![image](https://user-images.githubusercontent.com/64307152/133231668-8aac4e2f-d414-421a-a0a6-309fe3aa7af7.png)

###### @miko-github

**Comment by gjsjohnmurray** [comment]
In VS Code, open the **folder** that contains the file. Then open the file from VS Code's Explorer. Fold the sections you don't want to see.

Now when you close VS Code and reopen the folder, the file should reopen with the same sections folded.

**Comment by aeschli** [comment]
You are talking about folded functions in a TS/JS file. On save they should stay folded. That's how it should work.

I suspect an extension like a formatter causes this to happen. Can you run with all extensions disabled and see if it reproduces?
