### ISSUE TITLE
macOS: revisit usage of `-n` for `open` from CLI

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132569]
This is a follow up to https://github.com/microsoft/vscode/issues/102975. Wondering whether we could drop our usage of `-n` when running with `open` command and rather rely on the `open-file` event in Electron to get the data passed in:

https://github.com/electron/electron/blob/13-x-y/docs/api/app.md#event-open-file-macos

My understanding is that this event would fire when a second instance is launched via `open` and without `-n`.

It probably needs an upstream fix to get access to more data. Similar to the work we are doing for request single instance lock.

**Comment by bpasero** [comment]
I ran a quick test by removing the `-n` from `cli.ts` and printing the events from `open-file` here:

https://github.com/microsoft/vscode/blob/9525d0e1ed50ad8e78f83d315885caecf74042c8/src/vs/code/electron-main/app.ts#L226-L226

And did not get any call, so maybe this is not working as I had thought.

**Comment by deepak1556** [comment]
@bpasero why cannot we handle this case via the singleinstance api ?

```
app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, parse commandline for `-n`
   // and force new window if needed
})
```

If possible I would like to not rely on platform specific event and keep it consistent for all platform via a single entry point, thoughts ?

**Comment by bpasero** [comment]
@deepak1556 yes sounds good, I wasn't sure whether when you use `open` with an existing app identifier that is running triggers the single instance flow too.

**Comment by deepak1556** [comment]
Yup it will as open just ends up launching the app process, and there are certain files that are setup in the user data directory to identify an active instance associated with it https://github.com/electron/electron/blob/3b1c9dfc5400ceffb75a934cb6b8686fc5ba3fcd/chromium_src/chrome/browser/process_singleton_posix.cc#L5-L38 should clarify things :)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/97626, since we want to eventually end up with it.
