### ISSUE TITLE
Top Tool bar in MacOS disappears after update

### ISSUE THREAD

**Issue by kashishshah881** [microsoft/vscode#132507]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version:  MacOS Big Sur 11.5.2
<img width="1440" alt="Screen Shot 2021-09-06 at 8 16 42 PM" src="https://user-images.githubusercontent.com/46309829/132279062-7c3ced49-17b3-4fa7-9263-e0a212ebbdfd.png">

Steps to Reproduce:

1. Update to Version 1.60
2. Open VScode 

Note: This issue doesnt happen if you open in full screen and get it out of full screen.

**Comment by sbatten** [comment]
I'm unable to reproduce this issue, can you please share your settings which might contribute to the repro?
