### ISSUE TITLE
Cannot resolve file-resources in nested worker of ext host worker

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#132543]
related https://github.com/microsoft/vscode/issues/131902

* run an extension in the web worker extension host
* spawn a worker
* fetch a resource like a WASM file
* :bug: fails because the `file` schema hasn't been massaged

**Comment by alexdima** [comment]
[Here](https://github.com/microsoft/vscode/blob/e9f77ae35291bcefe06f36f9fad9475b7eb02f76/src/vs/base/common/network.ts#L168-L190) is the relevant case we hit which transforms `file` to `vscode-file` in the extension host web worker.

**Comment by jrieken** [comment]
Pushed `5c1cce4` which fixes most cases. I didn't tackle [polyfiled nested workers](https://github.com/microsoft/vscode/blob/5c1cce4e9d08ca5cc81f0fb44d4c70a43c80a869/src/vs/workbench/services/extensions/worker/extensionHostWorker.ts#L135) because those only exist in safari, which is web only and therefore not a problem. The code is ugly and duplicates stuff but due to the nature of static nature of these script you cannot re-use code... Ideas welcome

**Comment by jrieken** [comment]
@bpasero fyi my fix duplicates [asBrowserUri](https://github.com/microsoft/vscode/blob/494cbbd02d67e87727ec885f98d19551aa33aad1/src/vs/base/common/network.ts#L160-L160) and both places now need to be kept in sync
