### ISSUE TITLE
Replace All: search results are not cleared anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#13250]
- VSCode Version: 1.6
- OS Version: Mac OS

I did a replace all from the search viewlet and when I ran the action, the search results did not get removed:

![image](https://cloud.githubusercontent.com/assets/900690/19114351/f955882a-8b0d-11e6-8edc-15ec354a6c01.png)

Nothing in the console unfortunately.

**Comment by bpasero** [comment]
Not reproducible when I tried a second time. I was in super weird state when local files showed up as deleted in the git viewlet, no clue how this could have happened :-(

Feel free to close if you cannot reproduce after trying a couple of times.

**Comment by sandy081** [comment]
Not able to reproduce this, hence closing
