### ISSUE TITLE
Handle error code 267 on terminal launch on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#132578]
This happens when the cwd is invalid, we could give a better error message https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

<img width="645" alt="Screen Shot 2021-09-07 at 12 43 39 PM" src="https://user-images.githubusercontent.com/2193314/132401907-9975d035-3e44-4c4b-a113-eee275baef0d.png">

**Comment by Un-index** [comment]
Is "A natie exception ocured during launch" the better error message?

**Comment by Tyriar** [comment]
We'd want to detect the error code: 267 part and present something more friendly like the terminal's starting directory doesn't exist, we already have a similar message which catches other cases of this:

https://github.com/microsoft/vscode/blob/3a902162b48ef268f0da6a0280cbca9c322ef6c2/src/vs/platform/terminal/node/terminalProcess.ts#L193-L205

**Comment by Un-index** [comment]
Just the `_initialCwd`  part might not have been handled but I managed to fit the rest it

**Comment by Tyriar** [comment]
@meganrogge it should show a notification as well 🤔 

To get this to repro, try commending out the section that handles cwd validation so we try to start the process with an invalid one.
