### ISSUE TITLE
Git file status indicators in the tabs disappear

### ISSUE THREAD

**Issue by DrShushen** [microsoft/vscode#132540]
Issue Type: <b>Bug</b>

The Git status indicator tabs ("M" for modified etc.) and the associated color highlighting of the tab disappear when switching between different editor tabs. Present in vscode-insiders since the version as of the last few days. The tab indicators and colors seem to occasionally come back after a while, but the only reliable way to bring this back is to go to the Git panel and to manually hit Refresh.

VS Code version: Code - Insiders 1.61.0-insider (a3fce6207d9364afcfccaa55efc82ff8a392fdd5, 2021-09-06T08:03:22.271Z)
OS version: Linux x64 5.11.0-27-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4599)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|62.75GB (51.02GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id cefae089-8112-4e10-9c73-f7d437f36f9b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.18
vscode-edit-csv|jan|0.6.0
vscode-docker|ms-|1.16.1
python|ms-|2021.10.1200408502-dev
vscode-pylance|ms-|2021.9.1-pre.1
jupyter|ms-|2021.9.1001208778
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
autodocstring|njp|0.5.4
code-spell-checker|str|2.0.4
even-better-toml|tam|0.14.2
html-preview-vscode|tht|0.2.5
zoombar-vscode|wra|1.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627cf:30244335
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
pythonrunftest32:30353181
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30361752
pydsgst2:30361790

```

</details>

**Comment by bpasero** [comment]
Yup, should be fine in today's build.

**Comment by DrShushen** [comment]
Can confirm this is fixed in version:
```
Version: 1.61.0-insider
Commit: bb9491d9f2c65510226dcc920a6efbf6501d5943
Date: 2021-09-07T05:16:14.653Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-27-generic snap
```
