### ISSUE TITLE
Remote-SSH generates spurious traffic before 2-factor authentication is completed

### ISSUE THREAD

**Issue by theodore-wilson-amd** [microsoft/vscode#132565]
Kindly consider how to have vsCode not generate spurious traffic to a host available only after 2 factor authentication completes.  

Currently VsCode will attempt to reconnect to a server on a polling basis which can result in email correspondence with IT security teams.  

If a user closes VsCode of course this is not an issue but it is common to leave VsCode up and then reauthenticate only after reviewing email, attending a Teams meeting or similar, during which time VsCode will generate internet traffic that can concern IT security teams.  

Best regards,

Ted

**Comment by roblourens** [comment]
You can set `remote.SSH.maxReconnectionAttempts` to 0 to disable reconnecting after failed attempts to connect.

**Comment by theodore-wilson-amd** [comment]
Excellent.  Thank you
