### ISSUE TITLE
Dragging in-product release notes to start a new editor group, closes notes and goes to web

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13259]
- VSCode Version:1.6.0 insiders
- OS Version: Windows

Steps to Reproduce:

1. Follow test plan to enable in product release notes in insiders https://github.com/Microsoft/vscode/issues/12520
2. Help > Release Notes
3. Try to drag the release notes to the side to start a new editor group.

The release notes editor is closed and the user is directed to the release notes on the website.

This happens when the release notes are in preview mode or as a persistent editor after doing the **Keep Open** command.

This might be related to https://github.com/Microsoft/vscode/issues/13105 which has been fixed and included in the October release. Given this is likely a common action for users who want to review the release notes next to another editor group, we may want to fix this for September.

The workaround is to drag the release notes to an existing editor group.

**Comment by joaomoreno** [comment]
This is the same as #13105. Since it doesn't cause data loss, it's not a privacy issue and does not break functionality, I suggest we don't fix this in September.
