### ISSUE TITLE
Goto definition in hovers

### ISSUE THREAD

**Issue by sharedrory** [microsoft/vscode#132500]
![image](https://user-images.githubusercontent.com/85806407/132266937-322410d6-f690-408e-ab82-923d30a3fc3d.png)

It would be nice to be able to click "SetStateAction" in the screenshot above and vscode treating it as if it was in an editor and someone held ctrl while clicking it or used the context menu to trigger the action.

Perhaps have a setting to enable such behavior. Additionally, another setting to make it default behaviour without holding the keybind for "gotoDefinition".

Obviously, I am not asking for recursive hovers for obvious reasons.

**Comment by mjbvz** [comment]
Duplicate of #64566

**Comment by sharedrory** [comment]
It's not a duplicate but it is related to it.
