### ISSUE TITLE
Modification of launch.json requires restarting VSCode to be applied.

### ISSUE THREAD

**Issue by whoismaruf** [microsoft/vscode#132566]
Issue Type: <b>Bug</b>

Whenever I edit my launch.json file,  I am required to restart my VSCode everytime. Specially I tried to debug my FastAPI application. I checked reloading my application and restart debugging but these didn't work. I must needed to close my VSCode and open it again. Then it works fine with my specified configuration.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by weinand** [comment]
What debugger are you using?

**Comment by whoismaruf** [comment]
Hey @weinand 👋
I don't know how, but it's working right now. ✔

_For your kind information,
I am trying to debug my `FastAPI (Python)` application. And, by default, the `launch.json` file for `FastAPI` debugging doesn't include the `auto-reload args`. So, I was trying to add the `--reload` argument to the `args `list._

**Comment by weinand** [comment]
I do not see any reason why you would need to restart VS Code for this.
But if you see this problem again, please file the issue against the Python extension. All attributes of the Python launch configuration are handled by the Python extension.
