### ISSUE TITLE
Scrolling to the warning when the user tries to edit far away from the warning

### ISSUE THREAD

**Issue by borysl** [Microsoft/vscode#13254]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

You need to have some code validator (I used JSLint 1.2.1 )
File with several pages which has some warnings (I used JavaScript file)
1. Press F8 to navigate to the warning (you can do it several time)
2. Use Mouse to scroll to a different page, so you cannot observe warning anymore
3. Locate you cursor and start typing

EXPECTED:
VSCode will let you type
ACTUAL:
It navigates to the page where warning exists

WORKAROUND: Press Esc before scrolling away from warning

**Comment by jrieken** [comment]
That as design to make the widget accessible and screen reader aware. So, when you open it focus moves into it. You can press tab to focus back to the editor, select the editor, or hit ESC.
