### ISSUE TITLE
Full UNC Paths are not supported

### ISSUE THREAD

**Issue by Darthmonkey** [microsoft/vscode#132503]
Issue Type: <b>Bug</b>

The following code uses the full UNC path to search subfolders of file shares which go over 260 characters in the ISE console, but the same code returns nothing in VS Code:

- VS Code Version: 1.59.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to reproduce:
1. Input this transposing the NAS Server Share Path with a valid path which has folders exceeding 260 characters: 
`$FullUNCPath = Resolve-DFSNamespace <NAS Server Share Path> -UNCPath`
2. Receive this output: `\\?\UNC\domain\share\subfoldersover260charactersinlength...`
3. Run this: `Get-ChildItem $FullUNCPath -Directory -Recurse` 
4. In PowerShell_ISE if the folder structure goes over 260 characters, it'll still work, but if run in VS Code it doesn't run.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.12GB free)|
|Process Argv|--crash-reporter-id 25881db3-412f-40ef-a9c6-25ee922d360c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-PSStackoverflow|Dou|0.0.2
powershell|ms-|2021.8.2
team|ms-|1.161.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30361775
pythonf5test824cf:30361778
javagetstartedc:30351792
vsdyn321cf:30356811
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by roblourens** [comment]
Are you running this in the terminal or the debug console for powershell?

**Comment by Darthmonkey** [comment]
This is running in the terminal... I'm not massively familiar with VS Code yet, so haven't used the Debug Console in anger.

**Comment by roblourens** [comment]
In that case, I think this is just a powershell issue, not a vscode issue, is it different if you run it in a normal terminal outside of vscode?
