### ISSUE TITLE
VS Code doesn't install due to MOVEFILE Faile Code 183

### ISSUE THREAD

**Issue by h612** [microsoft/vscode#132532]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.60.0
- OS Version:Windows 10

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/23230497/132329627-d5b4dd9b-bd8b-4847-a1d2-6c7d303df79d.png)

2.

**Comment by joaomoreno** [comment]
Can you fully uninstall and reinstall VS Code?

**Comment by h612** [comment]
I troed that but it didnt run. And gave this error again.

**Comment by joaomoreno** [comment]
What if you install in a different location?

**Comment by h612** [comment]
Reinstalled the fourth time today and the issue has been resolved.
I guess it was a bug. Thanks.
