### ISSUE TITLE
Code doesn't appear when opened in browser

### ISSUE THREAD

**Issue by ScroofWasToken** [microsoft/vscode#132593]
So I downloaded open in browser because I wanted to try out Html and CSS, so I wrote some code and opened the browser and nothing appeared I went into developer tools to check if something was wrong and it was empty even though I wrote code down? Whats happening?

**Comment by lramos15** [comment]
Please open an issue against the extension as this isn't an extension the team owns. May I also suggest https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server which has the browser built into VS Code.
