### ISSUE TITLE
Terminal Standard Profile

### ISSUE THREAD

**Issue by eder-ig** [microsoft/vscode#132544]
Issue Type: <b>Bug</b>

After August 2021 (version 1.60) is updated, it is no longer possible to set another terminal as the default VsCode.
Every time it is closed and opened again, it starts with Windows Power Shell as default.
Therefore, it is extremely unsatisfactory to have to reset the terminal every time the IDE reboots.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043

**Comment by test137E29B** [comment]
Duplicate https://github.com/microsoft/vscode/issues/132150
