### ISSUE TITLE
Notebook with large outputs do not render properly

### ISSUE THREAD

**Issue by isshiki** [microsoft/vscode#132548]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60 (user setup) 
  - and Version: 1.61.0-insider (user setup) with command `Code - Insiders.exe --disable-extension`
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Load a .ipynb file with large outputs. An example file: https://github.com/isshiki/MLnotebooks/blob/master/v06_ohe-hyperparam-tuning.ipynb
2. The rendering process with large outputs keeps looping and does not render outputs, as shown below
![2021-09-07_19h17_37](https://user-images.githubusercontent.com/195644/132334202-65b0141d-fdcd-43bf-b2c8-040a623b89ea.gif)

This happens only in 1.60 and not when reverting to 1.59. Therefore, I think it may be due to the following improvement.
- [Visual Studio Code August 2021 (1.60): Performance improvements when dealing with large outputs](https://code.visualstudio.com/updates/v1_60#_performance-improvements-when-dealing-with-large-outputs)

**Comment by antcodd** [comment]
On a probably related note, I also find notebooks with large *numbers* of outputs (256 or more) also render incorrectly and don't scroll properly after some point in the file, getting stuck scrolling, rendering on top of each other and rendering incorrectly. This is also a regression in 1.60.

**Comment by antcodd** [comment]
Worth checking if this is resolved in 1.60.1 by the large output fixes in #131914. The related issue I mentioned above was, as the 256 buffer issue was spotted during investigation of that issue.

**Comment by isshiki** [comment]
Thanks for the information. I checked this issue with v1.60.1 on Ubuntu 20.04 and Windows 10.

v1.60.1 fixed this issue!

**Comment by rebornix** [comment]
As confirmed it's fixed.
