### ISSUE TITLE
git commit cannot be submitted after input a message

### ISSUE THREAD

**Issue by trevorwang** [microsoft/vscode#132517]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

1. opened a project under git control
2. did some changes
3. tried to commit the changes
4. there would be a input box to let you input a message
5. input the message and try to commit by commnd+ enter

commit could not be submitted.

![Screen Shot 2021-09-07 at 3 27 22 PM](https://user-images.githubusercontent.com/121966/132302764-ee3848be-de46-4867-a573-03a96e426179.png)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.94GB free)|
|Process Argv|../../robot --crash-reporter-id 69c1dd73-e630-4496-8502-7ac0d65a0b53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
vscode-mysql-client2|cwe|4.1.3
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
kotlin|fwc|0.2.23
gauge|get|0.0.21
vscode-test-explorer|hbe|2.21.1
json-to-dart|hir|3.3.6
jenkins-pipeline-linter-connector|jan|1.2.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
test-adapter-converter|ms-|0.1.2
vetur|oct|0.34.1
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.27.0
vscode-manifest-yaml|Piv|1.27.0
vscode-spring-boot|Piv|1.27.0
jenkinsfile|rec|1.2.0
fabric8-analytics|red|0.3.3
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-gradle|ric|3.6.1
robotframework-lsp|rob|0.22.0
rf-intellisense|Sno|2.9.6
code-spell-checker|str|2.0.4
open-in-browser|tec|2.0.0
vscode-rf-formatter|tum|0.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
vim|vsc|1.21.7
markdown-all-in-one|yzh|3.4.0
propertylist|zho|0.0.2

</details>

**Comment by gjsjohnmurray** [comment]
First you need to stage your changes. Use the + buttton alongside hello.py

**Comment by trevorwang** [comment]
Thanks so much.  You saved me.
