### ISSUE TITLE
Panel is hiding when last terminal closes

### ISSUE THREAD

**Issue by Antonius-S** [microsoft/vscode#132520]
Issue Type: <b>Bug</b>

- Make visible the panel with Terminal/Problems/Output/Debug console tabs
- Activate Terminal tab and close the newly created terminal
- Panel hides

While this behavior on manual terminal closing is something I can cope with, the same happens when a task is run with the option to close terminal after execution is set. And this is much more inconvenient
Tested with absolutely clean fresh install; no options to disable this behavior was found.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by Tyriar** [comment]
Closing as designed, you can change the task to stay open and that's the default I believe.
