### ISSUE TITLE
Support right click to hide panel actions and allow hidden by default actions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#132555]
In order to support users who want buttons like clearing the terminal (https://github.com/microsoft/vscode/issues/130636) or renaming, etc. using a single button click it would be nice if we supported right click to hide panel actions just like in the status bar and activity bar as well as being able to declare internally that actions are hidden by default.

Note that we cannot add these actions by default as it would clutter the UI and doing so with a setting is cumbersome. This would also allow users to customize their UI to go as minimalist as they want.

**Comment by sbatten** [comment]
Sounds like this would require some thought on implementation, but the request appears to result in action bars being allowed to toggle item visibility.

some questions:

1) should this apply to all action bars or is this opt-in by the action bar owner
2) how do we deal with overflow items in the dropdown
3) how do we discover hidden by default items?

**Comment by sbatten** [comment]
cc @misolori @bpasero @isidorn

**Comment by isidorn** [comment]
cc @sandy081

**Comment by Tyriar** [comment]
> should this apply to all action bars or is this opt-in by the action bar owner

It probably makes sense for all action bars, I'm mainly interested in the terminal though so I can expose commands that I know some will want but I don't want to add it to avoid clutter.

> how do we deal with overflow items in the dropdown

What do you mean overflow items in the dropdown? I'd expect the hidden items to just not be checked like with the panels themselves

![image](https://user-images.githubusercontent.com/2193314/132405339-dc496020-1691-4b3e-9219-fcee98041fbc.png)

> how do we discover hidden by default items?

By discovering by right click/docs

**Comment by misolori** [comment]
Given that this already exists in the status bar, i'm 💯 in support of this. Would love out editor toolbars to also support this.

**Comment by sandy081** [comment]
Is not this a dup of https://github.com/microsoft/vscode/issues/46403 ?

**Comment by sbatten** [comment]
@sandy081, I would agree. @Tyriar do you think #46403 covers your request?

**Comment by Tyriar** [comment]
Yep this is a duplicate, added a comment there
