### ISSUE TITLE
Debug Console shows "0" icon before each line

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#132563]
Issue Type: <b>Bug</b>

1. Debug a C# program in VS Code Insiders (see [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md) for more information.
2. View the debug console window, and note all the '0' before each line:

Result:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/13488/132367347-edf2b3ec-b02f-47cb-952d-5cb1a0285193.png">

VS Code version: Code - Insiders 1.61.0-insider (bb9491d9f2c65510226dcc920a6efbf6501d5943, 2021-09-07T05:17:08.586Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (11.28GB free)|
|Process Argv|--crash-reporter-id 8dd46428-3c33-429b-aec8-0a1119b2424f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gregg-miskelly** [comment]
Here is an example output event that the coreclr debug adapter is sending:

```json
{"seq":20,"type":"event","event":"output","body":{"category":"console","output":"Loaded 'C:\\proj\\cliexceptions\\bin\\Debug\\net5.0\\cliexceptions.dll'. Symbols loaded.\n"}}
```

**Comment by roblourens** [comment]
Can't repro, I tried on mac and windows.

![image](https://user-images.githubusercontent.com/323878/132765170-e807db29-8605-4b64-9d8e-0caa35111c17.png)


Can you try again with today's Insiders?

**Comment by gregg-miskelly** [comment]
Yup, I am not seeing it anymore, so the issue must be fixed.
