### ISSUE TITLE
Update Broken link in ThirdPartyNotices.txt

### ISSUE THREAD

**Issue by Un-index** [microsoft/vscode#132525]
server responds with a **404** for http://www.unicode.org/cldr/data/ 
the link is located in ThirdPartyNotices.txt

**Comment by sbatten** [comment]
@mjbvz generated from https://github.com/microsoft/vscode/blob/e8760a5d6c0e09ab692e5b3e414eca018745490f/extensions/typescript-language-features/cgmanifest.json#L27-L40 I believe
