### ISSUE TITLE
In product release notes always reloaded upon tab switching

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13256]
- VSCode Version:1.6.0 insiders
- OS Version: Windows

Steps to Reproduce:
1. Follow test plan to enable in product release notes in insiders https://github.com/Microsoft/vscode/issues/12520
2. Help > Release Notes
3. Scroll or down arrow down the page
4. Switch to a different editor and then go back to release notes.

release notes editor is re-rendered and doesn't remember your previous scroll or cursor position.

This will make trying the product or copying code snippets with the release notes problematic as the user will need to scroll back down and find their place in the release notes.

**Comment by PunchyRascal** [comment]
This still seems to be an issue in 1.10, at least there used to be a link to open the release notes in the browser before.

**Comment by ryenus** [comment]
The problem seems to be that, upon switching tabs e.g. first to the **Interactive Playground** tab, then back to the **Release Nots** tab, its content page is always reloaded, and for me it took 2+ seconds for (re-)loading.

**Comment by ryenus** [comment]
Suggested title: **Release Notes tab always reloaded upon tab switching**

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
