### ISSUE TITLE
Option to open terminal in a new tab by default

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [microsoft/vscode#132599]
Currently command + J on a mac opens a terminal at the bottom by default.
It would be nice if there's an option to open the terminal in a new tab by default.

**Comment by Lemmingh** [comment]
```json
"terminal.integrated.defaultLocation": "editor"
```

"New Terminal" is `` ⌃⇧` `` (`` Ctrl + Shift + ` ``).

---

`` ⌘J `` is "View: Toggle Panel".

`` ⌃` `` is "View: Toggle Terminal".

**Comment by Yu-Chieh-Henry-Yang** [comment]
@Lemmingh This is brilliant, thank you. 

This solves the problem that I open the issue for. 👍
