### ISSUE TITLE
I use iosevka font.I use iosevka font. Iosevka has various font styles, such as thin, light, medium, exterior, extended, heavy and so on. However, some fonts cannot be set in vs code

### ISSUE THREAD

**Issue by gitQqqHs** [microsoft/vscode#132522]
I use iosevka font. Iosevka has various font styles, such as thin, light, medium, exterior, extended, heavy and so on. However, some fonts cannot be set in vs code. For example, setting iosevka SS12 extended is invalid, the default font will be displayed, and setting iosevka SS12 thin can be displayed successfully.

I have tried many times. Only fonts that affect the font thickness will succeed. Other extended font styles are invalid.

These problems only appear in vs code. I can successfully set all the extended fonts in other editors, which is also the reason why I found the problem.

**Comment by dok42** [comment]
Hi, try `Iosevka SS12 Expanded`.
It works for the default style.

**Comment by alexdima** [comment]
@gitQqqHs Could you please try with @dok42 's suggestion?

**Comment by gitQqqHs** [comment]
> Hi, try `Iosevka SS12 Expanded`.
> It works for the default style.
Yes, iosevka SS12 expanded works normally.

It's strange. Why can't I use iosevka SS12 extended?

It is normal for other editors to use iosevka SS12 extended, and this is also the name of the font.

**Comment by gitQqqHs** [comment]
The extended one can be enabled in CSS with font-stretch: expanded.
The extended version of Iosevka is called "expanded". Just figured it out by looking at build-plans.
[widths.extended]
shape = 7
menu  = 7
css   = "expanded"
