### ISSUE TITLE
Terminal loads up powershell instead of default

### ISSUE THREAD

**Issue by aalicea** [microsoft/vscode#132545]
Issue Type: <b>Bug</b>

I have git bash set as default and recently when I load up VSCode it opens powershell in the terminal. I keep resetting it, but every time I open it, it loads powershell instead of git bash.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.33GB free)|
|Process Argv|--crash-reporter-id 8aa22f26-5aed-4e53-8c10-db3c664e6672|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.29.0
terraform|has|2.14.0

</details>

**Comment by test137E29B** [comment]
Duplicate https://github.com/microsoft/vscode/issues/132150

**Comment by IllusionMH** [comment]
@test137E29B thanks!
/duplicate

Fixed in Insiders
