### ISSUE TITLE
Wrong terminal (powershell) is reopened

### ISSUE THREAD

**Issue by pewscorner** [microsoft/vscode#132576]
Issue Type: <b>Bug</b>

1. Modify VS Code settings to use Command Prompt as the default Windows terminal profile:
```
    "terminal.integrated.profiles.windows": {
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "PowerShell": null,
    },
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
```
2. Open a folder, then open a terminal, and check that it is using Command Prompt.
3. Close VS Code (it is not enough to execute a reload).
4. Reopen VS Code, then reopen the previously open folder.

VS Code will now automatically reopen the terminal, but will use Powershell instead of Command Prompt.

If I remember correctly, this problem was present earlier, then was fixed, and now seems to have reappeared.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:34.699Z)
OS version: Windows_NT ia32 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (26.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
autotrim|chr|1.1.1
overtype|DrM|0.4.0
gitlens|eam|11.6.0
wordcounter|kir|2.3.0
string-manipulation|mar|0.5.2
git-graph|mhu|1.30.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
debugger-for-edge|msj|1.0.15
showflags|pew|1.1.0
vscode-fileutils|sle|3.4.5
rewrap|stk|1.14.0
open-in-browser|tec|2.0.0
selectline-statusbar|tom|0.0.2
sort-lines|Tyr|1.9.0

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by pewscorner** [comment]
Yes, it seems to work in Insiders.
