### ISSUE TITLE
Getting An error

### ISSUE THREAD

**Issue by NiharJani2002** [microsoft/vscode#132529]
Issue Type: <b>Bug</b>

The token '&&' is not a valid statement separator in this version 
I am currently using April 1.6.0 version

Can anyone have solution have to solve this

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (2.14GB free)|
|Process Argv|--crash-reporter-id 9b8832c7-c42f-4105-bc01-896753bde0a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
code-tester|Aka|0.0.6
icons-carbon|ant|0.2.4
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.3.2
competitive-programming-helper|Div|5.8.7
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
gc-excelviewer|Gra|3.0.44
better-cpp-syntax|jef|1.15.6
fluent-icons|mig|0.0.12
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4761
vsliveshare-audio|ms-|0.1.91
material-icon-theme|PKi|4.10.0
java|red|0.81.0
LiveServer|rit|5.6.1
pdf|tom|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224:30358039
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What language are you coding in?

What does your code look like?

Please paste screenshot(s) too if possible.

**Comment by NiharJani2002** [comment]
I am coding in c language
Error is like the given below:-
The && is not applicable in this version

**Comment by CodeCrazy-ywt** [comment]
Screenshot?
