### ISSUE TITLE
Place problems tab in editor window?

### ISSUE THREAD

**Issue by ardunster** [microsoft/vscode#132567]
I was super excited about the ability to put terminal tabs in editor windows and was all set to permanently configure my editor layout.... then realized that doing this meant problems was no longer one click way, and would open to cover a new, big section of my screen, instead of replacing the space my terminals are in.

Is it possible to get the problems tab placeable in an editor also? in my particular layout, I'd ideally put it as a second tab on an editor behind a certain terminal. And with the ability to lock editors, I could lock them in there, too and have it be the same layout every time. 

I think this would be a reasonable extension of the ability to put terminals in editor windows. (Some people may also want the output tab and debug console to have the same behavior. I never use either of them unless an extension or something unexpectedly has issues of its own, so it doesn't affect me, but I am sure there are other users that make use of them for other things.)

**Comment by mjarmstr** [comment]
I agree with this.  I'd like to be able to move the output tab into the editor area just like terminals.

**Comment by ardunster** [comment]
Really? Mine was older, and had more votes.
(actually they're the same votes now, but it was more when I found it.)
