### ISSUE TITLE
power shell appears as default terminal instead of users preferences

### ISSUE THREAD

**Issue by anton-marchenko** [microsoft/vscode#132556]
Does this issue occur when all extensions are disabled?: couldn`t check

- VS Code Version: 1.6.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install previous version  VS Code
2. set git bash console as default terminal
3. update vscode to 1.6.0

Actual result: power shell appears as default terminal
Expected result: git bash appears as default terminal according to users preferences

**Comment by gjsjohnmurray** [comment]
/duplicate of #132150 and will be fixed in upcoming 1.60.1 recovery release
