### ISSUE TITLE
Will not open sql file

### ISSUE THREAD

**Issue by eric-maxson** [microsoft/vscode#132554]
Issue Type: <b>Bug</b>

I have VS Code as my default app for SQL files, and when I double click on a file that I need to review, Code opens, but it doesn't open the SQL file.  I tried manually opening the file with menu FIle --> Open File, but that didn't work either.  I even tried rebooting my laptop, but that didn't work.  Also, there are no Problems reported in the output window.  It just acts as if I didn't request that a file be opened.  I ended up using Notepad++ to make sure the files weren't corrupted, and it works just fine there.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (8.96GB free)|
|Process Argv|C:\\Users\\emaxson\\source\\repos\\ProdIssue\\Schema\\SSACHDEV_BSYSRPTS.sql --crash-reporter-id 0813a1cf-01a8-41de-b925-0562566249a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
csharp|ms-|1.23.15
remote-wsl|ms-|0.58.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by bpasero** [comment]
What happens when you do `code --verbose <path to SQL file>`?
