### ISSUE TITLE
intellisense not working properly

### ISSUE THREAD

**Issue by khazzi** [microsoft/vscode#132559]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

i opened a new html document and clicked on html expecting intellisense to show me autocompletes showing html 5 but all it brought were truncatecharset

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.56GB free)|
|Process Argv|--crash-reporter-id 0e77f96f-94ca-42c5-8314-f907b9e605ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
vscode-jq|dan|1.2.0
vscode-jq-playground|dav|4.2.0
vscode-eslint|dba|2.1.23
jquerysnippets|don|0.0.1
jq-syntax-highlighting|jq-|0.0.2
graphql-for-vscode|kum|1.15.3
MagicPython|mag|1.1.0
ms-inkling|ms-|1.0.36
cpptools|ms-|1.6.0
autodocstring|njp|0.5.4
python|tht|0.2.3
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn321cf:30356811
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by aeschli** [comment]
Make sure the editor mode is HTML (seen in the status bar on the right).
Also verify that this issue is not caused by another extension. -> Run command `Developer: Reload with Extensions Disabled` and try again.
