### ISSUE TITLE
Notify users to switch builds when running via rosetta

### ISSUE THREAD

**Issue by sam-gronblom-rj** [microsoft/vscode#132598]
Issue Type: <b>Bug</b>

Visual Studio shows a notification "Restart Visual Studio Code to apply the latest update." Previously when clicking "Update Now" VSCode would automatically restart. However currently it only exits and doesn't manage to restart itself. Manually starting VSCode after this (running `code .`) starts the current version of VSCode (not the updated version) which again shows the update dialog.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|. --crash-reporter-id aa9fb884-c292-4430-89f4-feb0adbe6d93|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.17.0
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
haskell|has|1.6.1
Ionide-fsharp|Ion|5.7.1
language-haskell|jus|3.4.0
theme-karyfoundation-themes|kar|25.0.2
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
python|ms-|2021.9.1191016588
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4761
sqltools|mtx|0.23.0
vscode-xml|red|0.18.0
synthwave-vscode|Rob|0.1.8
rust|rus|0.7.8
jinjahtml|sam|0.16.0
vscode-fileutils|sle|3.4.5
ayu|tea|1.0.5
shellcheck|tim|0.16.0
vim|vsc|1.21.7

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by deepak1556** [comment]
Can you attach the `ShipIt_stderr.log`, `ShipIt_stdout.log` under `Library/Caches/com.microsoft.VSCode.ShipIt/`. Also can you confirm the permissions of this directory.

**Comment by sam-gronblom-rj** [comment]
[ShipIt_stderr.log](https://github.com/microsoft/vscode/files/7133908/ShipIt_stderr.log)

ShipIt_stdout.log is empty

```
❯ ls -la ~/Library/Caches/com.microsoft.VSCode.ShipIt/

total 64
drwxr-xr-x   6 sam  staff    192 Sep  9 15:08 .
drwx------+ 98 sam  staff   3136 Sep  9 15:13 ..
-rw-r--r--   1 sam  staff    303 Sep  9 15:08 ShipItState.plist
-rw-r--r--   1 sam  staff  26422 Aug 23 09:23 ShipIt_stderr.log
-rw-r--r--   1 sam  staff      0 Mar 20 14:29 ShipIt_stdout.log
drwx------   3 sam  staff     96 Sep  8 10:27 update.CtoJEUw
```

**Comment by deepak1556** [comment]
Thanks for confirming, error logs don't contain info about the recent update. Can you also paste the content of `ShipItState.plist`

**Comment by sam-gronblom-rj** [comment]
Content of ShipItState.plist:

```
{"launchAfterInstallation":0,"updateBundleURL":"file:\/\/\/Users\/sam\/Library\/Caches\/com.microsoft.VSCode.ShipIt\/update.79N5Etl\/Visual%20Studio%20Code.app\/","useUpdateBundleName":0,"bundleIdentifier":"com.microsoft.VSCode","targetBundleURL":"file:\/\/\/Applications\/Visual%20Studio%20Code.app\/"}
```

Will try deleting the update folder and see what happens.

**Comment by sam-gronblom-rj** [comment]
Removing the folder triggered a re-download after manually restarting VSCode. After the download finished I clicked "Restart to update", however VSCode did not start automatically. Restarting it manually from the command line again still starts up v1.59.1 and the "Update is available" popup shows up again. The content of the plist changed to reference the new folder containing the DL, but there is no new output in the stderr_log file.

**Comment by deepak1556** [comment]
Can you check the size of that new update downloaded folder, also is there a `Visual Studio Code.app` inside that update folder ?

**Comment by sam-gronblom-rj** [comment]
![image](https://user-images.githubusercontent.com/32093141/132647279-c25df5f5-d3d6-4aa4-a706-ad76e4fea722.png)

**Comment by sam-gronblom-rj** [comment]
Ah it says "Application (Intel)" I'm on an M1 here

**Comment by deepak1556** [comment]
What is the type of your current version in `/Applications`, it is incorrect that arm version downloads an intel update.

**Comment by sam-gronblom-rj** [comment]
Hmm, yeah the current one was Intel too! Maybe would be nice if VSCode would be able to pop up some notification about that...

**Comment by sam-gronblom-rj** [comment]
I guess I should just manually install the latest Arm version then?

**Comment by deepak1556** [comment]
I would recommend to install the universal version which is the default downloads from https://code.visualstudio.com/

> Hmm, yeah the current one was Intel too! Maybe would be nice if VSCode would be able to pop up some notification about that...

Agreed, PR to improve it is welcome :) will keep this issue open for it.

**Comment by sam-gronblom-rj** [comment]
Ok thanks for helping me figure it out. I replace it with the Universal build. Probably the next update should work fine.

**Comment by san-coding** [comment]
Hey, can I work on this, I am new to open source

**Comment by antonioprudenzano** [comment]
We can check if the process is translated by checking the sysctl.proc_translated flag

**Comment by deepak1556** [comment]
Steps for verification:

* Install [intel version](https://code.visualstudio.com/docs/?dv=darwinx64&build=insiders) of Insiders in apple silicon mac
* Launch the application and you should see a notification to warn about running the application as emulated similar to the screenshot https://github.com/microsoft/vscode/pull/181191#issuecomment-1598155127
* Click the `Download` button in the notification and it should download the universal build from the website
