### ISSUE TITLE
Zen Mode

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#13258]
It would be nice to be able to go into a mode where the current document takes up the entire editor.

This would mean hiding everything except for:

- Menu bar
- Status bar
- Current document

Toggling zen mode could be done like so: <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>enter</kbd>

And now for some sweet GIMP skills to show how this would look (line numbers could potentially be toggled too):

![vscode-zen](https://cloud.githubusercontent.com/assets/1571806/19124239/0083924c-8af8-11e6-8fac-16f640da8380.png)

As you can see everything is gone. This is helpful especially when you are on a smaller monitor or have multiple editors open.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12940
