### ISSUE TITLE
Extension properties' `scope: machine` attr have behavior that's different with the docs

### ISSUE THREAD

**Issue by kkocdko** [microsoft/vscode#132575]
- VS Code Version: `yarn web`, or [server-linux-x64-web](https://update.code.visualstudio.com/latest/server-linux-x64-web/stable)
- OS Version: Fedora 34

[Docs](https://code.visualstudio.com/api/references/contribution-points/#:~:text=scope) says:
> `machine` - Machine specific settings that can be set in user or remote settings. For example, an installation path which shouldn't be shared across machines.

But these code prohibited me to set properties in `User` setting scope:
https://github.com/microsoft/vscode/blob/892785264b4682d102b9cb81e01a549c218a74ee/src/vs/workbench/contrib/preferences/browser/preferencesRenderers.ts#L550-L559

( I am not very familiar with VSCode, hoping "`User` setting scope" this name is correct ):

![image](https://user-images.githubusercontent.com/31189892/132394035-f2722040-b21c-413d-bc36-f444a9ced6db.png)

**So is this behavior in design? Why?** Docs says *"can be set in user or remote settings"*, but now it only could be set in `Remote` setting scope.

---

An example: create a extension with `machine` scope prop:

```
"myextension.cfg1": {
  "type": ["string"],
  "scope": "machine",
  "default": null
}
```

Then set this prop on Web UI, you will see:

```
This setting cannot be applied in this window. It will be applied when you open a local window.
```

**Comment by sandy081** [comment]
Doc needs to be updated - `Configuration that can be configured only in the user settings or only in the remote settings`

**Comment by kkocdko** [comment]
@sandy081 You say `only in the user settings or only in the remote settings`, but still does not match the current implementation 😂

The result of my test is `only in the remote settings, but NOT in the user settings`. Although remote setting not be set, user setting value **still be ignored**. That's why I think it's unreasonable.

If you still think that this impl is true, ╮(╯▽╰)╭ ,I have nothing to say.

**Comment by roblourens** [comment]
We mean "in a local window, only in user settings. In a remote window, only in remote settings". It's typically a setting that has something like a path that only has meaning on the actual machine where a workspace extension runs.
