### ISSUE TITLE
not showing word suggestion while writing in Java script

### ISSUE THREAD

**Issue by sharmaraman8285** [microsoft/vscode#132528]
Issue Type: <b>Performance Issue</b>

.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.31GB free)|
|Process Argv|C:\\Users\\sharm\\OneDrive\\Documents\\CODE\\JAVAScript --crash-reporter-id 779641cd-b1ed-442b-9c5b-514303813cce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.5
vscode-language-babel|mgm|0.0.32
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Please us the `Start Extension Bisect` to investigate whether one of your extensions is causing the problem.
