### ISSUE TITLE
"workbench.editor.languageDetection" replaces language already set (through extension) in the middle of typing

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#132571]
Issue Type: <b>Bug</b>

1. In VS Code 1.60.0 with default "workbench.editor.languageDetection" setting of `true`, install "Todo+" extension: `vscode-todo-plus`.
2. Add this setting to your settings: `"todo.symbols.box": "[ ]",`
3. Create a new `TODO` file
4. Note how the file language is set to `Todo`
5. Put in some text that might resemble Markdown:

```md
Session auth:
[ ] OAuth 2.0 https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0 @done(21-09-01 14:41)
[ ] Add "Animation" header title
[ ] Add "Styles" section
[ ] Add skeleton loading placeholder

Access scopes:
https://github.com/microsoft/vscode/issues/new
[ ] Set `access_scopes` to initial values
```

This is the text that creates this bug for me. Not all the text produces the bug.

Expected:

The language of the file is consistently `Todo`

Actual:

The language of the file changes as the file contents change. Pair this with auto formatting and you get a complete mess when your "auto save on focus lost" kicks in and reformats the whole file based on another language syntax/rules.

It might also be worth to note that I even have this in my settings:

```json
"files.associations": {
    "TODO": "todo"
  }
```

I'd argue that this should never be automatically overridden by language detection.

The only workaround that I've found is this setting:

```json
  "[todo]": {
    "workbench.editor.languageDetection": false
  }
```

This setting is very confusing for me.

I suggest this to only be used when there's no language already selected.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.37GB free)|
|Process Argv|--crash-reporter-id 5a9112e5-d69d-439e-b6ab-63ec46831773|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
browse-lite|ant|0.2.14
vite|ant|0.2.5
vscode-eslint|dba|2.1.23
prettier-vscode|esb|8.1.0
vscode-todo-plus|fab|4.18.4
copilot|Git|1.4.2586
ruby-rubocop|mis|0.8.5
sublime-keybindings|ms-|4.0.10
abracadabra|nic|6.3.1
hocus-pocus|nic|1.7.0
ruby|reb|0.28.1
vscode-javascript-booster|sbu|14.0.1
markdown-preview-enhanced|shd|0.6.0
theme-check-vscode|Sho|1.1.3
code-spell-checker|str|2.0.4
vscode-ruby|win|0.28.0
change-case|wma|1.0.0
reactpreview|zen|0.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140cf:30362081

```

</details>

**Comment by vfonic** [comment]
Even worse, if I have a file like this (that's not recognized as Markdown):

```
Session auth:
  [ ] OAuth 2.0 https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0 @done(21-09-01 14:41)
  [ ] Add "Animation" header title
  [ ] Add "Styles" section
  [ ] Add skeleton loading placeholder

Access scopes:
  https://github.com/microsoft/vscode/issues/new
[ ] Set `access_scopes` to initial values
```

(please notice the spaces before `[ ]`)

And then I unindent `https://github.com/microsoft/vscode/issues/new`, the language at that moment switches from `Todo` to `Markdown`. This means that the language switches in the middle of typing. This should never happen.

After (this is suddenly recognized as Markdown and the language is changed):

```
Session auth:
  [ ] OAuth 2.0 https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0 @done(21-09-01 14:41)
  [ ] Add "Animation" header title
  [ ] Add "Styles" section
  [ ] Add skeleton loading placeholder

Access scopes:
https://github.com/microsoft/vscode/issues/new
[ ] Set `access_scopes` to initial values
```

**Comment by vfonic** [comment]
@gjsjohnmurray that might be it. I'll wait for the release next week and close this issue once I confirm it's been fixed.

**Comment by TylerLeonhardt** [comment]
@vfonic can test this out in insiders? It might already be fixed.

https://code.visualstudio.com/insiders/

**Comment by vfonic** [comment]
@TylerLeonhardt tested and it works as expected on the insiders build! Thanks!

Closing...
