### ISSUE TITLE
Adopt injected text infrastructure for other features

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#132537]
Users of [`IModelDecorationOptions.beforeContentClassName`](https://github.com/microsoft/vscode/blob/b2c343d085a972f1038ef2b61525898309b020cb/src/vs/editor/common/model.ts#L157) or [`IModelDecorationOptions.afterContentClassName`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/common/model.ts#L161):
* [x] [`breakpointEditorContribution.ts#L103`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L103)
  * reason: reserves space inline
* [x] [`breakpointEditorContribution.ts#L136`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts#L136):
  * reason: renders a symbol inline
* [x] [`callStackEditorContribution.ts#L83`](https://github.com/microsoft/vscode/blob/b2c343d085a972f1038ef2b61525898309b020cb/src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts#L83)
  * reason: renders a symbol inline
* [ ] #136740
  * reason: renders `⋯` at end of folded lines

---

Users of [`IThemeDecorationRenderOptions.before`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/common/editorCommon.ts#L621) or  [`IThemeDecorationRenderOptions.after`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/common/editorCommon.ts#L622):
* [x] [colorDetector.ts#L182](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/contrib/colorPicker/colorDetector.ts#L182) and [colorDetector.ts#L191](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/contrib/colorPicker/colorDetector.ts#L191):
  * reason: renders color boxes (e.g. in css)
* [x] [ghostTextWidget.ts#L276](https://github.com/microsoft/vscode/blob/ce2764c70c96665b65f5efa775468ea269c2881b/src/vs/editor/contrib/inlineCompletions/ghostTextWidget.ts#L276)
  * reason: old implementation

---

Users of [`IThemeDecorationRenderOptions.beforeInjectedText`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/common/editorCommon.ts#L624) or [`IThemeDecorationRenderOptions.afterInjectedText`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/common/editorCommon.ts#L625):

* [x] [`inlayHintsController.ts#L249`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/editor/contrib/inlayHints/inlayHintsController.ts#L249)
  * reason: generates dynamic CSS

---

Users of [`IThemeDecorationInstanceRenderOptions.after`](https://github.com/microsoft/vscode/blob/b2c343d085a972f1038ef2b61525898309b020cb/src/vs/editor/common/editorCommon.ts#L671):
* [`breakpointWidget.ts#L70
`](https://github.com/microsoft/vscode/blob/ce2764c70c96665b65f5efa775468ea269c2881b/src/vs/workbench/contrib/debug/browser/breakpointWidget.ts#L70)
  * reason: renders a placeholder in the breakpoint editor widget e.g. "Message to log when breakpoint is hit"
* [x] [`debugEditorContribution.ts#L89`](https://github.com/microsoft/vscode/blob/ce2764c70c96665b65f5efa775468ea269c2881b/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L89)
  * reason: renders inline values when debugging
* [`repl.ts#L693`](https://github.com/microsoft/vscode/blob/273470f94acce356ade20ac8ff1cbee80a574128/src/vs/workbench/contrib/debug/browser/repl.ts#L693)
   * reason: renders a placeholder in the debug repl e.g. "Please start a debug session to evaluate expressions"
* [`interactiveEditor.ts#L574`](https://github.com/microsoft/vscode/blob/273470f94acce356ade20ac8ff1cbee80a574128/src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts#L574)
  * reason: renders a placeholder in the interactive window e.g. "Type code here and press {0} to run"
* [`commentThreadWidget.ts#L855`](https://github.com/microsoft/vscode/blob/f411e1cffbdc3a2d18a4e998ec602521607ed674/src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts#L855)
  * reason: renders a placeholder in the comments widget e.g. "Type a new comment"

---

Sample showing how we could render a color box:

![image](https://user-images.githubusercontent.com/5047891/140333492-0c83577f-b483-40ab-ad95-d0bfe12e9eae.png)

```js
var jsCode = [
  '"use strict";',
  "function Person(age) {",
  "	if (age) {",
  "		this.age = age;",
  "	}",
  "}",
  "Person.prototype.getAge = function () {",
  "	return this.age;",
  "};",
].join("\n");

var editor = monaco.editor.create(document.getElementById("container"), {
  value: jsCode,
  language: "javascript",
});

var decorations = editor.deltaDecorations(
  [],
  [
    {
      range: new monaco.Range(3, 6, 3, 7),
      options: {
        after: {
          content: " ",
          inlineClassName: "special-box",
          inlineClassNameAffectsLetterSpacing: true,
        }
      }
    }
  ]
);
```
```css
.special-box {
  border: solid 0.1em #000;
  box-sizing: border-box;
  margin: 0.1em 0.2em 0 0.2em;
  width: 0.8em;
  height: 0.8em;
  background-color:red;
  line-height: 0.8em;
  display: inline-block;
}
```

**Comment by Tyriar** [comment]
@hediet can you clarify what other features will be looked at for this?

**Comment by hediet** [comment]
Mainly the test explorer I think.

The scope of this issue is flexible.

**Comment by hediet** [comment]
> renders ⋯ at end of folded lines

Injected text semantics currently do not make much sense for `⋯`: There would be a cursor stop both to the right and to the left and the symbol would word-wrap separately.

Alex thoughts:
> but maybe it’s the line wrapping algorithm that should not break before this specific injected text
> the problem with the current implementation is that the … is not accounted for when wrapping, so you will get a horizontal scrollbar which also is bad

We decided to adopt injected text for `⋯` at a later point, possibly together with enhancing the feature to support `{ ⋯ }`.
