### ISSUE TITLE
Allow to split an editor into two without creating separate tabs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#132651]
Extracted from #36700

**Comment by ArturoDent** [comment]
Currently, if I `Split in Group` an editor and then later `Join in Group` that same editor tab that editor is closed - which is unexpected.

![splitInGroup](https://user-images.githubusercontent.com/31813701/132616130-854cc75e-4cc3-413f-8b82-aca834337170.gif)



----------

Version: 1.61.0-insider (user setup)
Commit: df115e761ae11cf87ca569ca1824b7257099553a
Date: 2021-09-08T17:51:26.439Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by bpasero** [comment]
@ArturoDent good catch, this took a while to fix but should be fine with https://github.com/microsoft/vscode/commit/844aab2b3b6d5731a855dd76b94e432d6dd82b4e

**Comment by ArturoDent** [comment]
Looks good - I can't replicate the problem anymore.

Version: 1.61.0-insider (user setup)
Commit: 0884da1650baa24994d23d2a3742823c1186e526
Date: 2021-09-10T08:12:39.143Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
