### ISSUE TITLE
Allow to configure the timeout for waiting to resolve shell environment

### ISSUE THREAD

**Issue by pbrennand-francis** [microsoft/vscode#132669]
Issue Type: <b>Bug</b>

Javascript Debug Terminal not attaching debugger

	1. Open a JavaScript Debug Terminal
	2. Create `index.js` and attach breakpoints to the contents
	3. Run `node index.js` 

Actual: The code runs normally.
Expected: The debugger attaches and the breakpoints are triggered.

### Other Info:
My PATH: 
```/Users/piers/.nvm/versions/node/v14.17.0/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/piers/dev/flutter/bin:/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home/bin:/Users/piers/dev/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home/bin```

node version: 14.17.0 
which node: /Users/piers/.nvm/versions/node/v14.17.0/bin/node

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

### Things attempted:

1. Setting `Auto-attach: always` - this triggers the error `We did not find `node` on your PATH, so we cannot enable auto-attach in your environment` which links me to https://github.com/microsoft/vscode-js-debug/issues/708 
2. Switching from the nvm version of node to the brew version of node.
3. Running `Debug: Force Enable Auto-Attach` as suggested in the link - but this is not an available command
4. Setting `debug.javascript.usePreviewAutoAttach` as suggested in the link, but this is also not an available setting.
5. Checking the log files. Nothing of note other than possibly two errors in the main log file: `[2021-09-08 16:23:18.929] [main] [error] [resolve shell env] Could not resolve shell environment within 10 seconds. Proceeding without shell environment...
[2021-09-08 16:23:18.985] [main] [error] getUnixShellEnvironment#error An unknown error occurred. Please consult the log for more details.`

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.40GB free)|
|Process Argv|--crash-reporter-id f2039b3f-4da2-4e10-a09d-f641c4c7a6fe|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by connor4312** [comment]
> Could not resolve shell environment within 10 seconds. Proceeding without shell environment

This is the underlying issue

**Comment by bpasero** [comment]
We always gave up resolving the shell environment after 10 seconds, I did not change that, not even when introducing the shell environment service. We cannot really remove the timeout because processes like the extension host are waiting for the shell environment to be resolved and thus blocks from starting.

I think we probably need to introduce a setting for this for users that suffers or close this as wontfix.

**Comment by bpasero** [comment]
Code pointer: https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/environment/node/shellEnv.ts#L62-L67

@pbrennand-francis I suggest you remove any `nvm` entry from your `.zshrc` file. You should see new terminals opening on your system be as slow as 10s and more, so I think you must be suffering quite a bit from that config.

**Comment by pbrennand-francis** [comment]
@bpasero @connor4312 So I tinkered around a bit to test this theory. This is what I found.

1. My average .zshrc startup time is actually closer to 1-2 seconds. This is the time I get when I run `time  zsh -i -c exit`. I used this snippet from someone seeing a similar issue [https://github.com/microsoft/vscode/issues/113869#issuecomment-770081953](url) to confirm - this suggests a setting to disable this or extend the time might not be a bad idea.
2. **On startup**, it does take substantially longer - so I fully quit vscode and rebooted. When I checked the logs, the error had disappeared. The main log file now only contains ```[2021-09-09 09:33:51.723] [main] [info] update#setState idle
[2021-09-09 09:34:21.723] [main] [info] update#setState checking for updates
[2021-09-09 09:34:22.066] [main] [info] update#setState idle```
3. I also found that despite this error being gone, the Javascript Debug Terminal still does not attach when running node.

**Comment by pbrennand-francis** [comment]
UPDATE: I resolved this issue - it turned out I had been setting `NODE_OPTIONS=--max_old_space_size=4096` as part of my .zshrc. I changing it to `export NODE_OPTIONS="$NODE_OPTIONS --max_old_space_size=4096"` resolved this for me.

What tipped me off was this warning message which popped up by my terminal when I set `Auto-attach: always` again.
```
"Extensions want to make the following changes to the terminal's environment"

NODE_OPTIONS=--require "/Users/piers/Library/Application Support/Code/User/workspaceStorage/685647b32bdb36ce9377903d99553b60/ms-vscode.js-debug/bootloader.js" --max_old_space_size=4096 ${env:NODE_OPTIONS}

VSCODE_INSPECTOR_OPTIONS=${env:VSCODE_INSPECTOR_OPTIONS}:::{"inspectorIpc":"/var/folders/sl/k215xykn3xbdmdm1mlt89hs40000gn/T/node-cdp.6350-2.sock.deferred","deferredMode":true,"waitForDebugger":"","execPath":"/Users/piers/.nvm/versions/node/v14.17.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always"}
```

I guess my only suggestion would be improving the error messaging on the extension a little, as this was clearly my fault, but would have been extremely hard to chase down without that warning message when I turned on `Auto-attach: always`. 

Thank you both for helping out!

**Comment by connor4312** [comment]
Ah, gotcha. The timeout was a red herring.

Ben I'll leave this open in case you want to use this for tracking making the timeout configurable.

**Comment by sultanmyrza** [comment]
When I shut down my macOS I always check 
- [x] **Reopen windows when logging back**.

![image](https://user-images.githubusercontent.com/12681781/155903859-7b006a15-76df-49dc-8b0d-6b906e9a45fe.png)

Then when I turn on the computer I always get [Resolving shell environment fails](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails). To resolve this issue I restart my VSCode. I agree with @lbfalvy it would be nice to have a configurable timeout as shown by @bpasero

**Comment by gearintellix** [comment]
so, the timeout now is already configurable or still keep stick in 10 seconds?
because the vscode documentation says still 10 seconds timeout https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails

**Comment by jeffabailey** [comment]
Why isn't this configurable?

I have a lot going on with my shell, and ten seconds or more to load it is fine by me.

I HAVE NEVER SEEN THIS BEHAVIOR FROM ANY OTHER SOFTWARE EVER.

**Why is this not configurable?**

**Comment by gearintellix** [comment]
it's sound sacrifice anything to get fast application boot
but in the end, the app is useless and usually user will reboot again until ENV load properly

so, instead of hard code the timeout, just give a user power to configure it
i guess user won't complain if application boot taking a bit longer, just give a warning message about it
user know their computer spec it's normal

**Comment by bpasero** [comment]
A new setting `application.shellEnvironmentResolutionTimeout` to control this will be available starting tomorrow.

**Comment by jeffabailey** [comment]
Thank you!

**Comment by aprilmintacpineda** [comment]
> A new setting `application.shellEnvironmentResolutionTimeout` to control this will be available starting tomorrow.

No updates available yet, hopefully gets released soon! <3

**Comment by bpasero** [comment]
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by aprilmintacpineda** [comment]
Thanks for the suggestion! I'll just wait for the next release.

**Comment by bpasero** [comment]
**Verification:**
* be on macOS
* add `sleep 12` to your `~/.bashrc` or `~/.zshrc` first line
* open VS Code from the dock (NOT a terminal)
* verify you see a notification telling you that shell environment could not be resolved in a reasonable time
* adjust the `application.shellEnvironmentResolutionTimeout` setting to a larger value
* quit
* start again from the dock
* verify the notification does not appear and you should also see a little progress indicator in the status bar
* **IMPORTANT**: remove the `sleep 12` again

**Comment by aprilmintacpineda** [comment]
> 

hi @bpasero, apologies but where do I add this `application.shellEnvironmentResolutionTimeout`?
