### ISSUE TITLE
Move panel tab to same window and then move to panel again cause additional views showing

### ISSUE THREAD

**Issue by iamwwc** [microsoft/vscode#132619]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
> Version: 1.60.0 (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
- OS Version: Osx Big sur

Steps to Reproduce:

Additional views show even though there are enough space. It doesn't call https://github.com/microsoft/vscode/blob/a3fce6207d9364afcfccaa55efc82ff8a392fdd5/src/vs/base/browser/ui/actionbar/actionbar.ts#L354 again to recalculate tab width I guess

https://user-images.githubusercontent.com/24750337/132462307-e65bc117-ce56-42c1-8f3a-2ee59653486b.mov

**Comment by sbatten** [comment]
dupe https://github.com/microsoft/vscode/issues/123722
