### ISSUE TITLE
Cannot install extension pack on github.dev even if all extensions it contains are web enabled

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#132687]
**Repro**
1. Using `github.dev`, try installing the `Github Markdown Preview` extension pack

**Bug**
I can't install the extension even though the four extensions in the pack are now web enabled:

![Screen Shot 2021-09-08 at 1 20 14 PM](https://user-images.githubusercontent.com/12821956/132579917-e35542b4-2a94-4bae-8479-469d4e7e3c1f.png)

**Comment by mjbvz** [comment]
Seems similar to #131885 but I'm  using the insiders build: df115e761ae11cf87ca569ca1824b7257099553a

![Screen Shot 2021-09-08 at 1 24 09 PM](https://user-images.githubusercontent.com/12821956/132580190-87679030-31d7-4069-9a3d-75159ae35081.png)

**Comment by sandy081** [comment]
We are working with Marketplace team to enable extension packs as web extensions by default. Mean while you can fix this by republishing your pack.
