### ISSUE TITLE
Cannot override the default terminal in the remote container for non-root user since 1.60.0

### ISSUE THREAD

**Issue by skyred** [microsoft/vscode#132633]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Ubuntu

Some dev containers (e.g. [the official docker PHP image](https://hub.docker.com/_/php) based container) creates `www-data` user with `/sbin/nologin` shell set, see below

```
# cat /etc/passwd | grep www-data
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
```

Before 1.60.0, when launching a terminal with `www-data` user in the remote container,  `/bin/bash` was always used, but since 1.60.0, the specific shell set in the container is used instead, see the comparison from `trace`. This will throw an error, and preventing the terminal to launch, of course. 

![image](https://user-images.githubusercontent.com/164034/132486056-f0468b5b-7d3c-441e-aaef-74e1bc9ef8cb.png)

I tried below options to override the default shell for non-root users in `devcontainer.json` of the container:

1. `"terminal.integrated.shell.linux": "/bin/bash",`
2. `"terminal.integrated.automationShell.linux": "/bin/bash"`,
3.  
```
"terminal.integrated.profiles.linux":{
      "bash": {
        "path": "bash",
        "icon": "terminal-bash"
      }
    },
    "terminal.integrated.defaultProfile.linux": "bash",
```

But, none of the options worked. How can we override it, if it is supported?

**Comment by owennewo** [comment]
@skyred  - I'm seeing a terminal crash when upgrading to 1.60 on windows.  I've a locked down (no uac) windows machine.
The following workaround works for me
```
    "terminal.integrated.inheritEnv":false,
    "terminal.integrated.defaultProfile.windows": "Git Bash"
``` 
This may be a different (windows) issue but you could try to see if `terminal.integrated.inheritEnv":false` helps on linux.

**Comment by skyred** [comment]
> This may be a different (windows) issue but you could try to see if `terminal.integrated.inheritEnv":false` helps on linux

No. I just tested with all other options enabled above. The terminal still crashes for non-root user.

**Comment by piotrS-bright** [comment]
Attempted to use in my settings.json file
```
"terminal.integrated.inheritEnv":false,
"terminal.integrated.defaultProfile.windows": "Command Prompt", 
```
but it still defaults to PowerShell on my Windows machine when attempting to debug.

So far only solution I found was to downgrade to 1.59.1.

**Comment by MichaKnoe** [comment]
On windows we also see a similar problem since 1.60. If we set Git Bash as the default terminal VS code starts with powershell which is just wrong. Closing all the terminals and starting terminals again, opens Git Bash as a default. 

So far the only solution that worked entirely again was to switch completely to WSL2 
Downgrade to 1.59.1 does NOT work for me. Something is completely messed up.

**Comment by bas2k** [comment]
Same issue for in @ Windows.
Downgrade to 1.59.1 worked for me

**Comment by meganrogge** [comment]
/duplicate #132150 fixed in the recovery build
