### ISSUE TITLE
VSCode Extension Issue: Copying file(s) via the scripts fields in the package.json fails.

### ISSUE THREAD

**Issue by kgentes** [Microsoft/vscode#13268]
- VSCode Version: 1.5.3
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Used Yeoman generator to boilerplate a simple VSCode extension. (basically "Hello world")
2. The extension runs great , launches from "DEBUG > Launch Extension" menu as expected.
3. I tried to add a source file (customfunctions.js) to the src directory, but it never gets copied to the output directory when the extension is compiled/launched.

Details:
I've got what seems like it should be a simple thing to do. I want to add a Javascript source file to my "build/compile" process of my VS Code extension. This seems like it should be simple enough, so I added a copy task to the scripts field in the package.json of the extension project. Like so:
```
"scripts": {
    "copy:dist": "cp src/customfunctions.js out/src",
    "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
    "compile": "npm run copy:dist && node ./node_modules/vscode/bin/compile -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
},
```
The rest of the VS Code extension project is just a boilerplate VSCode extension generated from a Yeoman generator. I literally just have these files in my extension project src directory :

- the two files boilerplate for the extension-  extension.ts and myDocumentContentProvider.ts
- my custom javascript file customfunctions.js

When I use the 'DEBUG > Launch Extension' mention to test my extension the "Launch Extension" (again boilerplate) has "preLaunchTask": "npm" which I assume runs my package.json and should compile the TS files and (in my case) copy the one js file I've added.

But, for some reason, this doesn't work. My file isn't copied. In fact, the TS files are compiled and the results copied to out/src, but MY custom JS file is not copied.

And, **yes**, I went through all the documentation on extensions (including https://code.visualstudio.com/docs/extensionAPI/extension-manifest ), but nothing explains a working way to do this.

**Comment by Tyriar** [comment]
You say you adds a file `customfunction.js` but you mention `customfunctions.js` (functions plural) in the `copy:dist`. If this was just a typo when filing the issue I'm curious why you are using a js file here instead of a ts file and why you're not linking to it within the ts file?

**Comment by kgentes** [comment]
the "customfunctions.js" it was a typo sorry.. [corrected above]

as to your question "I'm curious why you are using a js file here instead of a ts file and why you're not linking to it within the ts file?"

I am using a JS file because it is simply a small library that is already written in JS and I want to access it . I did think initially of just renaming the file to customfunctions.ts, but even that does not generate a new JS file into the out/src directory as I'd expect.

**Comment by kgentes** [comment]
So @Tyriar , given your reply, do you expect this should do what I was hoping:

```
"scripts": {
    "copy:dist": "cp src/customfunctions.js out/src",
    "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
    "compile": "npm run copy:dist && node ./node_modules/vscode/bin/compile -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
},
```

???

**Comment by Tyriar** [comment]
Well the copy script won't run as part of the watcher since it's running before the watch command.

I would expect if you import the js file into your ts file then it would all work fine without needing to copy it over?

**Comment by kgentes** [comment]
Let me make sure I understand what you are saying... I should be able to:

1. add customfunctions.ts to the src directory
2. put the contents of customfunctions.js in it.
3. it should just be compiled and the output placed into out/src as customfunctions.js

Is this what you are saying?

Even if this is true, my original question still stands-- why does the "scripts" field in package.json not actually do the copy I've requested???

**Comment by Tyriar** [comment]
I'm saying I don't think the `cp` is necessary at all and typescript should be pulling it in provided it's linked to correctly.

As for the copy, when you run `npm run compile`, that is `npm` running the `cp` command, *not vscode*. Are you running `npm run compile` in your terminal? I don't think vscode does this when you start debugging if this is what you expect.

**Comment by AkashGutha** [comment]
having the same problem when developing extension in javascript.

**Comment by Tyriar** [comment]
Closing as I see this as an issue with cp, npm or TS, not vscode.

**Comment by kgentes** [comment]
This is not an issue with npm or TS. They operate correctly on other
package.json instances. VSCode is making custom use of package.json format
and it now does not operate as it should .

Have you investigated the actual issue and reproduced it?

Kim Gentes

**Comment by Tyriar** [comment]
TS is probably clearing out files from `out` that it doesn't expect as I don't think you're meant to do this in TypeScript. Add that to the fact that the cp is run *before* the watch it means the js file will never be there. Try running:

- `npm run copy:dist` and see if it is copied to out
- `node ./node_modules/vscode/bin/compile -watch -p ./` and check the contents of out

**Comment by Tyriar** [comment]
Also try running `npm run compile` from the terminal and see if the js file is in out.
