### ISSUE TITLE
Wrong accessibility service instantiated 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#132684]
Caused by https://github.com/microsoft/vscode/pull/131947

1. Start vscode app, notice that the `browser/accessibilityService` gets instantiated and not the `electron-sandbox` one 🐛 
2. Also the `browser/accessibilityService` should also send out telemetry, namely the event `accessibility` when accessibility is turned on. [Code pointer](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/accessibility/electron-sandbox/accessibilityService.ts#L60)

Assigning to September since this is a regression and makes our accessibility events to not be sent.

fyi @bpasero @devinvalenciano

**Comment by TylerLeonhardt** [comment]
Not sure I understand... the electron-sandbox one extends the browser one.

**Comment by isidorn** [comment]
My mistake, source maps in Built VS Code fooled me.
Sorry for the noise 🙏  
Closing
