### ISSUE TITLE
Allow also setting the language_info in a notebook

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#132694]
The current ipynb api only allows setting the kernelspec. We should also allow extensions to set the `language_info`

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode/commit/55af133ac43df33fefb0f5215785860fefd0c747

**Comment by mjbvz** [comment]
@davidanthoff @DonJayamanne  Can you please verify this new api resolves your issue? It should be in the latest VS Code insiders build

**Comment by davidanthoff** [comment]
I just updated https://github.com/julia-vscode/julia-vscode/pull/2424 to work with this new API, and it seems to all work! Hurray, much appreciated.
