### ISSUE TITLE
Powershell is opened on startup although Command Promp is default

### ISSUE THREAD

**Issue by siaccarino** [microsoft/vscode#132620]
Whenever I start vscode with a folder Windows Powershell is started regardless of the default terminal (Command Prompt in my case)
This bug is new and appears with 1.60

Expected behaviour:
Open the default terminal like before

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Windows 10.0.18363 Build 18363

Steps to Reproduce:

1. start vscode

**Comment by albertosantini** [comment]
This is a duplicate of #132150 and will be fixed in upcoming recovery release
