### ISSUE TITLE
nobody in the world wants powershell as default terminal

### ISSUE THREAD

**Issue by rossi-jeff** [microsoft/vscode#132664]
I've been using vscode with WSL as my default terminal for years. A recent update made powershell the default and no matter how many times I change it , powershell is in my terminal every time I open the program. This is an uninstall the program and use something else level of offence.

seriously fuck you all

**Comment by IllusionMH** [comment]
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery September release.

**Comment by CodeCrazy-ywt** [comment]
So I wonder whether they had July & August off work? If otherwise how can they make such a bug?
