### ISSUE TITLE
Cannot disabled Indentation

### ISSUE THREAD

**Issue by jcamelis** [microsoft/vscode#132686]
Issue Type: <b>Bug</b>

I've got this setting
"editor.tabSize": 2
"editor.detectIndentation": false
but every time I open a file it change the file tab size to 4, and If I manually change it back to 2, when I switch windows and back to VCS, it change the tab size to 4 again at file level. 
 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-27-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|18.74GB (9.61GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 1e6fb6da-4d3c-41ad-8057-09dcecb0fd7c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.0
swagger-viewer|Arj|3.1.2
vscode-eslint|dba|2.1.23
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
angular-essentials|joh|12.0.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
vscode-typescript-next|ms-|4.5.20210907
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.10.0
material-icon-theme|PKi|4.10.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
gitblame|wad|8.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30361775
pythonf5test824:30361777
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by sharedrory** [comment]
Looking at your extensions, perhaps editor-config is changing the settings based on the config file?

**Comment by jcamelis** [comment]
I disabled EditorConfig and now works.
@sharedrory Thank  you very much!!!
