### ISSUE TITLE
Explorer cannot set the font

### ISSUE THREAD

**Issue by miui8824** [microsoft/vscode#132671]
Issue Type: <b>Feature Request</b>

Explorer cannot display according to the font set by the user

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/issues/519
