### ISSUE TITLE
Not recognizing screen reader user when screen reader is running before VS Code starts

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#132688]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Download and install NVDA screen reader
2. Run screen reader on device and turn on Tools -> Speech Viewer
3. Boot up VS Code with the --verbose tag
4. Check the telemetry logs - in my experience, I have not fired 'monacoworkbench/accessibility' despite having the screen reader on and the accessibility setting set to "auto"
5. Set editor accessibility Setting to "on" instead.  Terminal text wrap turns off, as it should, but I still don't fire a 'monacoworkbench/accessibility' event.

I do fire the accessibility event when I turn the screen reader on _during_ a VS Code session.

**Comment by isidorn** [comment]
I can not reproduce this on my macOS and Win VM.
@devinvalenciano it would be interesting if you could F1 > developer tools > sources > put a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/accessibility/electron-sandbox/accessibilityService.ts#L59)
Have a screen reader turned on. Reload. Does the breakpoint get hit?

fyi @sbatten for `accessibilityService`

**Comment by isidorn** [comment]
@devinvalenciano friendly ping for my questions from above if you found a chance to look into this?
I double checked and I can still not reproduce this.

![Screenshot 2021-11-10 at 15 01 18](https://user-images.githubusercontent.com/1926584/141126809-a0a71098-c3be-47b8-a079-067bcde393d0.png)
