### ISSUE TITLE
Clean Up Dead Code Button

### ISSUE THREAD

**Issue by key6oardWarrior** [microsoft/vscode#132699]
Issue Type: <b>Feature Request</b>

Visual Studio (VS) Code already has the ablity to detect dead code, but to clean up the dead code the user must manually search for the dead code and remove it. However, it would be more efficient if there was a button in the debug side tab that would remove all dead code. There should be options for the user to remove dead variables, functions, methods, and or classes. There should be an option to remove dead code from all files open, just selected files, or just the current open file. If the user has two, or more, code files open, in the split editor, and the user selects the current file open then which ever file is active (A.K.A the file that the user is currently editing). Of course there should be a pop up warrning explaing that removing dead code will remove any variables, functions, methods, and or classes (depending on which the user selected to have removed) that are not in use, regardless of their implementation.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by weinand** [comment]
This is a language function and unrelated to debug.
