### ISSUE TITLE
Wrong default terminal

### ISSUE THREAD

**Issue by toxik** [microsoft/vscode#132656]
Issue Type: <b>Bug</b>

When I open VSCode (I usually use the cmdline extension – `code path/to/folder`) the terminal is bash instead of my default, zsh.
Subsequent calls to open terminal correctly open zsh.

A colleague of mine (on Windows) has the same problem – his default is Git Bash, however on startup Powershell pops up.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 724c4690-1a92-4c94-b2fd-31736e8bafc6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.2.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.23
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.79
vscode-angular-html|gha|1.7.0
copilot|Git|1.4.2628
output-colorizer|IBM|0.1.2
Angular2|joh|12.0.0
vscode-colorize|kam|0.11.1
translation|Mih|0.0.1
import-sorter|mik|3.3.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.16.1
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
mssql|ms-|1.10.1
remote-containers|ms-|0.194.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
angular2-inline|nat|0.0.17
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
vscode-sort-json|ric|1.20.0
vscode-scss-formatter|sib|2.2.3
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
javagetstartedc:30351792
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by RUSshy** [comment]
nobody uses this shitty shell so they force it on everybody

"bug" sure, trash tools deserve to go to the trashbin

**Comment by IllusionMH** [comment]
> nobody uses this shitty shell so they force it on everybody

Any proofs? Code is open you can looks for that commit that intentionally does that...

No need to hijack other's issue especially if you are not helping to solve it.
