### ISSUE TITLE
Settings view has invalid height panes

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#132627]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0-insider 34861b8c8aa76b517f203743ad5b5d72ef5fcd81
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Open Settings view (command + ,)
2. Show TypeScript Section

![settings-pane-height-is-invalid](https://user-images.githubusercontent.com/1955233/132471850-a8d048d0-b411-461d-983d-1a05fbe70c8a.gif)

When state of Reset Zoom, reproduced it too.

I tried the old version and it was reproduced on a3fce6207d9364afcfccaa55efc82ff8a392fdd5 .

**Comment by yamachu** [comment]
related? https://github.com/microsoft/vscode/issues/132430

CSS `top` position looks incorrect even for adjacent elements.

<img src="https://user-images.githubusercontent.com/1955233/132475436-00cce31f-e3c7-4b0a-a199-b81f21ca1c53.png" 
  height="400" />
<img src="https://user-images.githubusercontent.com/1955233/132475497-b4770ba3-9321-4b9c-8816-f12e68135191.png" height="400" />

**Comment by IllusionMH** [comment]
Yes, looks like duplicate after https://github.com/microsoft/vscode/issues/132430#issuecomment-913425124
