### ISSUE TITLE
Object is of type 'unknown' error

### ISSUE THREAD

**Issue by MarX156** [microsoft/vscode#132640]
Issue Type: <b>Bug</b>

Hello,

Since the latest update (1.60) I have had issues with TS and VSC.

**Code example:**
```
![image](https://user-images.githubusercontent.com/49168513/132500006-1db49607-b10d-43fe-9d0a-9db86f67fff8.png)

catch (err) {
if (err.response && err.response.statusCode == 400) {
                    this.setStatus('400 Bad Request, retrying.', 'error');
 }
}
```
- `err` is underlined as an error
this code is returning the error "Object is of type 'unknown' error", it wasn't happening before that update...

Thanks!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 56c718db-ab1b-4290-8d27-7d3c2c9056f1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-eslint|dba|2.1.23
es7-react-js-snippets|dsz|3.1.1
vscode-wasm|dts|1.3.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
rest-client|hum|0.24.5
discord-vscode|icr|5.7.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
rainbow-csv|mec|1.9.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
vsliveshare|ms-|1.0.4761
vetur|oct|0.34.1
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|3.0.4
vue-vscode-snippets|sdr|2.2.1
vscodeintellicode|Vis|1.2.14
vscode-wakatime|Wak|17.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
javagetstartedt:30351793
pythonvspyt187:30362782
pydsgst2:30361792
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by IllusionMH** [comment]
/question
This is expected behavior if you use built-in TS version which is now 4.4 (instead of workspace specific which might be different) and have `"strict": true`
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables

/cc @mjbvz
