### ISSUE TITLE
Retain cursor position when clicking to bring editor to foreground

### ISSUE THREAD

**Issue by ssigwart** [microsoft/vscode#132674]
When VSCode is in the background and I click on an editor to bring it to the foreground, I'd like the cursor to stay where it was before.  Typically, I'm typing something and need to switch back to another app to look something up.  Then I click whatever visible part of VS Code there is to bring it back to the foreground.  However, the cursor moves and I lose where I was at.

This is somewhat like #130147 except that one expects the cursor to move.

**Comment by yashpalgoyal1304** [comment]
hi, @ssigwart u can use <kbd>alt</kbd> + <kbd>tab</kbd> if on windows. i suppose keyb shortcuts for this action exist in other os-es too.

**Comment by ssigwart** [comment]
Hi, @yashpalgoyal1304.  Yes, on Mac, it's Cmd+Tab.  The  problem is that it's inconsistent because you may have to use it once or multiple times if it's not the last window.

> amh, this might be obvious, but i thought to say it. ~'cz in all the softwares the cursor position changes on clicking on them. so, if this suggestion was imple.....~ but yeah, after this suggestion, it would have become double click to move cursor. yeah, it makes sense then.

At least on Mac, I'm fairly certain that most applications do not change the cursor position when the window is in the background.  I've tested this with Word, Excel, Chrome, Safari, Mail, Finder, iTunes, and TextEdit.  They all behave that way.  I did find that Calendar changes state when you click to restore it from the background, but in general, not much seems to behave the way VS Code does.

For those that are also annoyed by this, I created an extension (https://marketplace.visualstudio.com/items?itemName=ssigwart.retain-cursor-after-background) to fix it.
