### ISSUE TITLE
Disable Extension through api

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#13269]
- VSCode Version: 1.5.x
- OS Version: 10.10.3

Is there a way to disable the extension? Upon disabling the extension we do not want any command traces in the context menu or a command palette. As of now there is a tight coupling with how the commands are declared / registered. 

For our extension we have a need to disable it if a product license or trial version is expired.

Thank you,

Ritesh

**Comment by joaomoreno** [comment]
#2882
