### ISSUE TITLE
Low performance in terminal for repeated identical formatting

### ISSUE THREAD

**Issue by ReallySuperOtter** [microsoft/vscode#132642]
Issue Type: <b>Bug</b>

In an ssh session with grep coloring enabled (specifically against a CentOS 7 target), the performance for grep . filename is far lower than grep .\* filename

Both expressions will match every character, coloring every character. However, the second one will identify a single match per line, while the first one colors every single character as a separate match.

The VS Code terminal struggles in the first case, causing a timing at the remote end for an output from a small log file of 194 lines with 7986 characters to be 8 seconds. With the second version, the time usage is 0.010 seconds. Thus, the time usage with identical color transitions on the same line seems to perform far worse than what would be predicted from just the linear increase in the number of colored segments (194 segments in the first one, 7986 in the second, but time usage increasing by far more than a factor of 40).

This is using a Windows native ssh binary. Running the same binary in the plain classic Windows console, or the newer Windows Terminal, (on 22000.168) gives no noticeable difference between the two expressions (in the range of 0.010 s).

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.41.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (8.80GB free)|
|Process Argv|--crash-reporter-id 90c82e08-84ac-4efb-9a8b-686fc4a20ad1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alvis|
|OS|Linux x64 3.10.0-1160.36.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz (32 x 2206)|
|Memory (System)|754.39GB (674.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: rackham2.uppmax.uu.se|
|OS|Linux x64 3.10.0-1160.41.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 x 2200)|
|Memory (System)|251.35GB (58.15GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
pdf|tom|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn420:30356812
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by Tyriar** [comment]
Can you try changing the value of `terminal.integrated.gpuAcceleration` to see if that helps? Also recording a performance profile would help identify where the slowness is https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
