### ISSUE TITLE
[Java] Method Signature Refactoring

### ISSUE THREAD

**Issue by DreamFulFil** [microsoft/vscode#132698]
All prevalent IDEs such as Eclipse, IntelliJ, Netbeans provides a way to refactor method signatures.
It would be nice to have such a feature implemented in VSCode since the methods are spread across the project,
and currently no such refactoring actions are supported(checked the documentation and opened/closed issues).
Visual Studio seems to have such an existing [feature](https://docs.microsoft.com/en-us/visualstudio/ide/reference/change-method-signature?view=vs-2019).

Thank you for the hard work.

**Comment by aeschli** [comment]
Can you file this against the Java extension? (https://github.com/redhat-developer/vscode-java/issues)
