### ISSUE TITLE
cannot connect marketplace

### ISSUE THREAD

**Issue by slodreamer** [microsoft/vscode#132661]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.60.0 (Universal)
- OS Version: mac os big sur 11.4

Steps to Reproduce:

1. open Extensions
2. input someone plugin
3. get Error message: cannot connect marketplace

![image](https://user-images.githubusercontent.com/15122540/132542215-c2a68b30-0379-4f82-a112-60ffd5f4f61e.png)

![image](https://user-images.githubusercontent.com/15122540/132541833-23635634-43de-4646-b2aa-b179c9d25cbf.png)

**Comment by kai475** [comment]
got the same problem...

**Comment by shiqi0319** [comment]
got the same problem...

**Comment by markexin** [comment]
got the same problem...

**Comment by markexin** [comment]
i find it happen to mac os，windows vs code works well~~~

**Comment by Blithe-Chiang** [comment]
got the same problem in Windows

**Comment by GU0FORY1** [comment]
got the same problem

![image](https://user-images.githubusercontent.com/42399180/132632166-d94e9fab-1c86-422b-a04d-5b78c5e4ec50.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/132634
