### ISSUE TITLE
Does not show jsdoc documentation from import - JavaScript ES module

### ISSUE THREAD

**Issue by patoi** [microsoft/vscode#132649]
Issue Type: <b>Bug</b>

Given the next module (./utils/setup.mjs file):
```javascript
/** @module utils/setup */
import { firefox } from 'playwright-firefox'

/**
 * Playwright page object.
 * @type {import('@playwright/test').Page}
 */
export let page
```
And other js file, with import (./utils/setup.mjs):
```javascript
import { strict as assert } from 'assert'
import { page} from './utils/setup.mjs'

describe.only('smoke test', () => {
  it('test', async function () {
    await page.goto('https://lwhateveruwant.com')
   ...
  })
})
```

**Actual:** When I pressed `CMD + space` over `goto` function, the documentation is "No suggestion."

<img width="539" alt="image" src="https://user-images.githubusercontent.com/1846548/132517364-1620b7c7-0376-41d4-a8d1-187862f585b3.png">

**Expected:** show Playwright Page `goto` function documentation, for example: <screenshot>

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1846548/132517499-7d690c70-eb71-4db5-b1a4-5701caf45e05.png">

**jsconfig.json:**

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es6",
    "checkJs": true,
    "allowSyntheticDefaultImports": false
  },
  "exclude": [
    "node_modules",
    "target"
  ],
  "include": [
    "src/test/uat/**/*.mjs"
  ]
}
```

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.9
better-toml|bun|0.3.2
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
FreeMarker|dco|0.0.9
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|8.1.0
vscode-google-translate|fun|1.4.13
todo-tree|Gru|0.0.214
jenkinsfile-support|ivo|1.1.0
search-node-modules|jas|1.3.0
JavaScriptSnippetsStandard|jms|1.8.0
asciidoctor-vscode|joa|2.8.0
presentationmode|jsp|1.1.5
vscode-commitizen|Kni|1.0.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.16.1
vscode-language-pack-hu|MS-|1.48.3
remote-containers|ms-|0.194.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.34.1
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
svelte-vscode|sve|105.3.5
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.4

(4 theme extensions excluded)

</details>

**Comment by sharedrory** [comment]
For me its always like that no matter the case. I think it's intended

**Comment by mjbvz** [comment]
Does it work if you use `.js` files instead of `.mjs`? See https://github.com/microsoft/TypeScript/issues/27957

**Comment by patoi** [comment]
If I renamed to .js, then it works fine, thank you!

**Comment by patoi** [comment]
Thanks for investigation!
