### ISSUE TITLE
Q: How to access "ignore snippets" api

### ISSUE THREAD

**Issue by sequencerr** [microsoft/vscode#132655]
The fact that nobody is can't answer, says me that this is impossible or something
https://stackoverflow.com/questions/69099192/vscode-how-to-access-ignore-snippets-api

**Comment by jrieken** [comment]
There is no API to ignore snippets, it's a user feature that is operated via the UI

**Comment by sequencerr** [comment]
> 
> 
> There is no API to ignore snippets, it's a user feature that is operated via the UI

I'm sorry, It will be in future? Or is there a way for me to access it through the UI API or something?
