### ISSUE TITLE
Grouping files by name

### ISSUE THREAD

**Issue by seveves** [Microsoft/vscode#13262]
I really miss the option to group files by name (or couldn't figure out how to do this). Visual Studio has a similar feature (f.e. App.cs has the sub-item App.Designer.cs).

The following examples should clarify this feature request:

Example:
jquery.min.js jquery.min.map will be grouped/hidden to jquery.js

Another example (angular2):
foo.component.ts foo.component.html foo.component.css will be grouped to foo.component

**Comment by osnoser1** [comment]
Maybe #6328

**Comment by seveves** [comment]
Yes that's the same ... I'll close this one and following the other one.
