### ISSUE TITLE
Drag and drop in explorer has visual artifacts on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13260]
- VSCode Version: Code - Insiders 1.6.0-insider (782e3ad7e504c308a5f1592ca6ae2574a13b0e73, 2016-10-05T16:59:53.654Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.sort-lines-1.1.0, Tyriar.terminal-tabs-0.0.1, Tyriar.theme-glacier-0.0.10, be5invis.vscode-icontheme-nomo-dark-1.1.4, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.3, rbbit.typescript-hero-0.8.0, rebornix.nova-0.0.5, ryu1kn.annotator-0.10.0

![image](https://cloud.githubusercontent.com/assets/2193314/19125839/69e0dce6-8aed-11e6-912b-4a319fa35a6d.png)

**Comment by bpasero** [comment]
Maybe we can tweak this better? seems introduced from https://github.com/Microsoft/vscode/commit/e058bde3ea1632edc1424dfe406e29c673c4aff5

**Comment by Tyriar** [comment]
Would probably go away if `border-radius: 10px;` was removed, I'm guessing this is just a chromium on Linux issue.

**Comment by bpasero** [comment]
This seems to be an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=550999

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
