### ISSUE TITLE
Default Terminal Profile is Not Respected Again

### ISSUE THREAD

**Issue by eliphatfs** [microsoft/vscode#132607]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:

1. Switch default profile to cmd
2. Restart VSCode, or right click in a folder and select Open with VSCode (my project is in python, in case it matters)
3. Still a Powershell is opened
4. Starting from 1.60, Python Debugger runs in powershell which is incompatible with my anaconda environment. This is extremely annoying for me.

PS. Even deleting powershell setup from settings.json the situation still remains the same.

![image](https://user-images.githubusercontent.com/23738781/132443371-6bb8141e-204c-41f9-99b9-9a9bc672e115.png)
![image](https://user-images.githubusercontent.com/23738781/132443633-7e283987-07c6-4ce0-8086-997723012753.png)

**Comment by ccrsxx** [comment]
Same, it happens right after I updated my VS code. It really annoyed me, even tho it only happens when you close VSCode while the terminal is opened.

**Comment by albertosantini** [comment]
This is a duplicate of #132150 and will be fixed in upcoming recovery release

**Comment by eliphatfs** [comment]
The fourth point has greater impact than the one on startup, could you also check it please?

**Comment by gjsjohnmurray** [comment]
That point may be related. @meganrogge please confirm.
