### ISSUE TITLE
Support encoding diff + side-by-side as a single URI

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#132665]
Many of our APIs return just a resource URI, it would be a lot easier to work with diff and side by side editors if we also supported encoding them as a single URI rather than having to have a type which doesn't overlap nicely such as `URI | {primary: URI, secondary: URI}`. 

The proposal would be for Side-by-side to be encoded as 
`vscode-file://sidebyside?primary={resource}&secondary={resource}`

Diff encoded as 
`vscode-file://diff?original={resource}&modified={resource}`

This would of course be unwrapped to the object syntax internally at some point, but would allow working with diff and side by side editors utilizing one URI.

//cc @jrieken for the original idea during the API sync.

**Comment by bpasero** [comment]
The scheme cannot be `vscode-file` though, it needs to be a new one not already taken by a file system provider or protocol handler. `vscode-file` is for serving files into the renderer from the main process.

For persisting view state for diff editors, I already came up with a resource:

https://github.com/microsoft/vscode/blob/d0623487f546e2ef0bf33fc0fa06a51a2731b7ed/src/vs/workbench/browser/parts/editor/textDiffEditor.ts#L365-L383

**Comment by bpasero** [comment]
One thing which we have to be careful about is whether the side by side editor and diff editor should expose a `resource` property or not. I think we have lots of code that makes assumptions when there is a `resource` that is maybe not fit to deal with this new scheme yet. 

If we do this, we need to check each user of `IEditorInput.resource` or `EditorResourceAccessor` if they are fit for dealing with this new kind of resource.

The alternative is to just create this resource for the API and not use it in the workbench internally.

**Comment by lramos15** [comment]
I would be fine having it exposed at the API level. I think we would just need some sort of translation layer to ensure that they work as expected. I also wonder user's expectations if they do say `showTextDocument(uri)` and pass in a diff URI

**Comment by jrieken** [comment]
> I also wonder user's expectations if they do say showTextDocument(uri) and pass in a diff URI

That will never work because the API spec's that a TextEditor is being returned

**Comment by lramos15** [comment]
Right, I was just curious if users would expect a no-op in the cases where diff URIs + side-by-side URIs wouldn't work because they're representing two resources.

**Comment by bpasero** [comment]
Ok, if we just expose this on the API level then I leave this up to you, I think you need to just add it to `mainThreadTabs` then.

**Comment by lramos15** [comment]
TabKind models this a lot nicer. We won't pursue this approach
