### ISSUE TITLE
Debugger points to wrong file after upgrade to 1.60.0

### ISSUE THREAD

**Issue by krystianolech** [microsoft/vscode#132644]
Issue Type: <b>Bug</b>

Hi, I noticed that after upgrade to the newest version my debugger scripts start working incorrectly after upgrading to new version of vsocde.

The debugger script I use is responsible to open mocha tests written in typescript. It uses ts-node as transpiler so files are not compiled before running tests.  
`    {
      "type": "node",
      "request": "launch",
      "name": "Mocha tsc",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": ["-r", "ts-node/register", "src/**/*.test.ts"],
      "console": "integratedTerminal",

      "internalConsoleOptions": "neverOpen",
      "protocol": "inspector",
      "skipFiles": ["<node_internals>/**/*.js"]
    }`
 In the current version when I set up breakpoint it break in a virtual compiled file on incorrect line:
![Screenshot 2021-09-08 at 15 08 51](https://user-images.githubusercontent.com/5447595/132515539-8ce64658-e017-4a83-aeb8-8ede35ec053e.png)

While in 1.59 It was pointing to the source file correctly:
![Screenshot 2021-09-08 at 15 17 32](https://user-images.githubusercontent.com/5447595/132516660-c2f57d57-6180-4396-805a-87cc88830c44.png)

What I noticed is that usage of _reflect-metadata_ has an impact on it, as it works correctly in projects where I don't use it.

Here is a repository with minimal source code that reproduces issue:
https://github.com/krystianolech/vscode-issue-132644

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 8a7267e1-1a43-4f53-8977-59c6c2c75859|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by connor4312** [comment]
/duplicates https://github.com/microsoft/vscode-js-debug/issues/1100

See my comment on there for a resolution
