### ISSUE TITLE
vscode.workspace.onWillSaveTextDocument or LSP textDocument/willSaveWaitUntil don't wait at all

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#132600]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows

Steps to Reproduce:

1. Our extension is trying to get VS Code to wait a short period of time before a save occurs, but VS Code appears to not wait and tries to save almost immediately (fail to save popup appears immediately due to a process having a lock on the file that we haven't killed yet), i.e. < 1 second. This seems like a bug. We've tried via vscode.workspace.onWillSaveTextDocument and via the LSP textDocument/willSaveWaitUntil and the results are the same.

I don't know what additional logging or diagnostics is needed.

**Comment by jrieken** [comment]
Can you share a code sample that uses the `onWillSaveTextDocument` API? Also what does the log from the extension host says (F1 > Show Logs > Extension Host)?

**Comment by sean-mcmanus** [comment]
@jrieken Yeah, we register it at https://github.com/microsoft/vscode-cpptools/blob/seanmcm/clangTidy/Extension/src/LanguageServer/clientCollection.ts#L65 and other code that is run is at https://github.com/microsoft/vscode-cpptools/blob/seanmcm/clangTidy/Extension/src/LanguageServer/client.ts#L2117 (basically, just mimicking the textDocument/willSaveWaitUntil message). Previously we just handled the LSP message, which works, but it wasn't waiting at all (so I thought it was an vscode-languageclient bug https://github.com/microsoft/vscode-languageserver-node/issues/808).

No logging message appears in the Extension Host logging panel, and the Developer Console just (immediately) shows that VS Code is incorrectly trying to save without waiting before we're able to release the lock on the file (from the external clangTidy process):
`
workbench.desktop.main.js:630   ERR [text file model] handleSaveError(1) - exit - resulted in a save error: Error: Unable to write file 'pathToFile.cpp' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'pathToFile.cpp') file:///pathToFile.cpp
workbench.desktop.main.js:749

Failed to save 'pathToFile.cpp': Unable to write file 'pathToFile.cpp' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'pathToFile.cpp')
`

**Comment by jrieken** [comment]
Sorry, I meant a small reproducible sample. I am fairly confident about our implementation - it hasn't seen changes in the last years and it is used for things that we selfhost on: format on save and code action on save. You seem to operate the client API correctly but I cannot say if the IPC request etc keeps the promise properly alive etc. So, a minimal repo will help to clarify this. When a listener is behaving badly either [this](https://github.com/microsoft/vscode/blob/dcef262f4e41a5fd3e730652d908e56195714d84/src/vs/workbench/api/common/extHostDocumentSaveParticipant.ts#L94) or [this](https://github.com/microsoft/vscode/blob/dcef262f4e41a5fd3e730652d908e56195714d84/src/vs/workbench/api/common/extHostDocumentSaveParticipant.ts#L86) message is logged (on the extension host)

**Comment by sean-mcmanus** [comment]
Oops, sorry -- found the bug in our code.
