### ISSUE TITLE
Expose Keymap command in Keyboard Shortcuts toolbar

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#132677]
Usertesting showed that keymap extensions are not easy to discover due to a mix of issues. Users have many different terms for them, don't know that they exist or don't look in the right places.

To improve organic discovery the idea here is similar to _Turn on Settings Sync_ button in _Settings_, showing a _Migrate your Keyboard Shortcuts from other Editors_ in the _Keyboard Shortcuts_ page.

To focus on new users, it could be hidden when a user installed a keymap.

**Comment by daviddossett** [comment]
To clarify, would the command just bring up the filtered keymaps extensions view? 

One possible option would be an additional icon added the toolbar e.g.

<img width="1143" alt="CleanShot 2021-09-09 at 13 18 39@2x" src="https://user-images.githubusercontent.com/25163139/132756756-4945e1ed-1400-44cc-8f09-6864d8556c79.png">

We don't yet have the right icon in codicons so consider the new icon a placeholder for now

**Comment by digitarald** [comment]
The command is `workbench.extensions.action.showRecommendedKeymapExtensions` (_Preferences: Keymaps_)

> One possible option would be an additional icon added the toolbar e.g.

I am skeptical that am icon solves the discoverability problem. The UI is already pretty dense and an icon might just blend in with everything. Could we explore a non-primary labeled button as well?

**Comment by daviddossett** [comment]
I agree. Without changing the existing toolbar I can see that the commands can also feature a label. However I've never seen this used in VS Code so I'm not sure it's the right way to go.

I'll take a look at some other options and will report back.

<img width="438" alt="CleanShot 2021-09-09 at 13 32 42@2x" src="https://user-images.githubusercontent.com/25163139/132758550-46f4d7ca-3d42-401a-9d69-2166ca124fef.png">

**Comment by daviddossett** [comment]
Oh ok, I see what you're referring to now re: Settings Sync. Hadn't noticed this since it's always been on for me :) 

<img width="1006" alt="CleanShot 2021-09-09 at 13 45 41@2x" src="https://user-images.githubusercontent.com/25163139/132760130-a5172470-8b6e-4e99-802f-eea5bd295fe2.png">

**Comment by daviddossett** [comment]
## Secondary button inline with search

<img width="1017" alt="CleanShot 2021-09-09 at 13 50 50@2x" src="https://user-images.githubusercontent.com/25163139/132760807-ff0c3ecb-6e4d-45a3-af30-2b21db349f8e.png">

## With H1 

I realize this one is a bit of scope creep here. I'm actually curious how we're getting away without an H1 on this or similar pages. @misolori would you have any context there?

<img width="993" alt="CleanShot 2021-09-09 at 13 50 58@2x" src="https://user-images.githubusercontent.com/25163139/132760868-36ff854f-6b82-4138-864a-6dee442bfe45.png">

**Comment by misolori** [comment]
We tend to rely on the file tab as the "heading" for most of our single pages (settings, running extensions, etc.) and the extensions detail page is one of the exceptions of this:

![image](https://user-images.githubusercontent.com/35271042/132765435-7cbc9354-89be-4d5a-9bae-eff6a5e9da33.png)

**Comment by digitarald** [comment]
Closing for now as we lost traction on this.
