### ISSUE TITLE
Automatic language detection always identify my dotenv file as ini file

### ISSUE THREAD

**Issue by DrakeXiang** [microsoft/vscode#132625]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.60.0 (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Create a dotenv file and put something in it
2. open it with vscode 

Example content:
```
# prod appid
# MP_APPID="abcde"
# test appid
MP_APPID="sldkfj"
```

**Comment by davikor** [comment]
I encounter similar behavior with COMMIT_EDITMSG files. For a short period of time they are highlighted as git commit messages, then the file type is automatically switched to ini. Maybe related?
