### ISSUE TITLE
Toggle comments

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode#132667]
Issue Type: <b>Feature Request</b>

If I have 2 lines of code like this:

// doSomething(withThis);
doSomething(withThat);

and I highlight both and press Cmd-/, I'd expect Code to remove the comment on the first line (like it would do if it was the only line selected) and add the comment chars to the second line (like it would do if it was the only line selected).  To wit - the desired outcome:

doSomething(withThis);
// doSomething(withThat);

BUT this is the ACTUAL outcome:

// // doSomething(withThis);
// doSomething(withThat);

no bueno.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

**Comment by sharedrory** [comment]
I don't think its worth it when all you need to do is press ctrl + / on the first line, down arrow, then another control + /. Just my opinion tho.

**Comment by ArturoDent** [comment]
See this extension I wrote: [Toggle Comments](https://marketplace.visualstudio.com/items?itemName=ArturoDent.toggle-comments&ssr=false#overview).

![fullDemo1](https://user-images.githubusercontent.com/31813701/132605315-8e8a1f57-2b07-45e7-8095-420c72d6060f.gif)

**Comment by ChrisMiami** [comment]
Well first of all, since the behavior is different on the commented line depending on other lines in the selection, one could argue the behavior is broken since it is inconsistent. 

Second, a tool should reduce tedious work, not add to it as you suggest. However “easy” it is, it’s still additional, unproductive work that is ideal for simple automation.

**Comment by ChrisMiami** [comment]
Nice! I hope it gets integrated into Code but this is a cool extension!
