### ISSUE TITLE
Add drop down options to current folder view

### ISSUE THREAD

**Issue by risingBirdSong** [microsoft/vscode#132695]
![Screenshot from 2021-09-08 15-27-02](https://user-images.githubusercontent.com/52929863/132594349-a06151ec-5572-4c94-b320-dc32e5bf71c8.png)

In the file explorer we can right click a folder and get a drop down of options like new file, find in folder, copy path, etc. I think this same functionality would be very useful on the top view of the folder structure (the view provided in screen shot). This would be helpful especially for large files where I quickly want to access the drop down controls of the current folder without having to scroll up a lot in the regular file explorer.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"breadcrumbs"
