### ISSUE TITLE
Debt: Better support telemetry levels 

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#132693]
- Add a minimum level to appenders
	- Remove combined appender in favor of service logic
	- Service checks level of telemetry against appender 
	- Remove `setEnabled` and isOpted in favor of getTelemtryLevel
	- consider `onDidChangeTelemetryLevel`
	- Do we need to update the API for telemetry level

**Comment by lramos15** [comment]
Talked to @jrieken and @eamodio in the API sync about the API pieces. It sounds like the suggested path forward would to be to add isErrorEnabled and then make it explicit that isTelemetryEnabled is for usage data

**Comment by lramos15** [comment]
Closing as we've tackled 
- Moving all logic out of the appenders and into the telemetry service
- Remove combined appender
- Centralize the checks for telemetry into telemetry utils
- Remove `setEnabled` and `isOptedIn` in favor of telemetry level logic

TODO in another issue
- API Proposal to better support the different telemetry levels
