### ISSUE TITLE
Web: undo/redo does not work after a file has been closed

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#132612]
Does this issue occur when all extensions are disabled?: don'y know

- VS Code Version: 1.55
- OS Version:

Steps to Reproduce:

1. open [playgroupd](https://github.com/microsoft/vscode-web-playground)
2. edit some file
3. close the file
4. reopen the same file
5. trigger undo

the file can't undo correctly
There are same problem on `FileSystemProvider` in vscode-web

**Comment by bpasero** [comment]
We probably have some heuristic based on the file scheme?

**Comment by alexdima** [comment]
Yes, here are the schemas where we maintain undo-redo elements across text buffers being disposed and recreated: https://github.com/microsoft/vscode/blob/ad321f6ba01568a507d850e8aef1c23a3e297e6b/src/vs/editor/common/services/modelServiceImpl.ts#L133-L141

**Comment by bpasero** [comment]
@alexdima I have similar code:

https://github.com/microsoft/vscode/blob/2d50df638c5f6239ac0d0bb2449630324e5544fc/src/vs/workbench/services/history/browser/history.ts#L581-L585

One thing I use is `this.pathService.defaultUriScheme` which is a way to get at the standard scheme for the workspace, which would then include our web playground and github.dev too. But I am not sure the impact of further enabling this support on your end.

**Comment by zWingz** [comment]
Thanks
But I think It should work on custom file-system

**Comment by alexdima** [comment]
I've pushed that we restore the undo-redo elements for `IPathService.defaultUriScheme`. I would not expand this to all schemes, because there are many usages of custom schemes, and many usages of text buffers, and sometimes people change these text buffers by issuing editing commands. I don't know what would be the impact of keeping (almost in perpetuity) all the undo-redo history for all text buffers.

**Comment by bpasero** [comment]
Yeah very good point, for example every opened editor ends up having 2 text models, one for the visible text and one from git to do the quick diff decoration.

**Comment by zWingz** [comment]
I agree the point.
Can provide support for `file-system` that define `isMaintainUndoRedo=true`?
If a `file-system` is writeable, it should also support the `redo/undo` even if the file has been closed

**Comment by bpasero** [comment]
I think given the fix Alex just pushed it should work fine now, even for a custom file system provider that is used in web because that should end up being the default path scheme.

**Comment by rchiodo** [comment]
/verified using https://vscode-web-test-playground.azurewebsites.net/
