### ISSUE TITLE
Improve discoverability of cell folding

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#132690]
## Summary

This issue explores how we could improve the discoverability of cell folding. We currently support markdown folding via the chevron, via code cells for both input and output using the context menus, and we also have code folding when line numbers are enabled. 

The secondary issue is that when markdown cells are folded, it's difficult to tell what cells are folded underneath as there is no indicator. You also can't run any of the folded cells inside of the markdown region (unless you run all cells).

## Design exploration

One idea is to use the left gutter for folding (similar to JupyterLab). One downside is that this repeats functionality via our chevron, but we have limited space for code cells and also have a split run button (which has a small chevron).

![CleanShot 2021-09-08 at 13 23 35](https://user-images.githubusercontent.com/35271042/132580858-d5ede3cd-548d-4850-b5fc-fd77b3d1f97e.gif)

And for folding markdown regions, it would be great to show underneath what cells are hidden with an ability to run those cells. There's other questions with how do we surface additional information about those cells (run state, execution count, etc.) which may or not be useful. At the minimum, using the placeholder text with a run button will solve a large amount of frustration with knowing how many cells are folded and if they are running. This would also be done in parallel with #130611 for showing what cells are actively running.

![CleanShot 2021-09-08 at 13 52 06](https://user-images.githubusercontent.com/35271042/132584466-ba0bc4e8-d01f-403a-8a3a-47fb03e82762.gif)

**Comment by tanhakabir** [comment]
I think a tooltip saying "hide cell" when they hover over the gutter could be helpful here as well

**Comment by misolori** [comment]
@roblourens I believe the design exploration is done on this issue, let me know if you need anything else from me.

**Comment by roblourens** [comment]
Can you link to those figmas? I don't know how to discover things in Figma

**Comment by misolori** [comment]
Here's a link to the Figma: https://www.figma.com/file/I4lDqeDSAT4n3V47aZltLg/Notebook-Cell-Folding?node-id=12%3A1497
