### ISSUE TITLE
Extensions are grayed out

### ISSUE THREAD

**Issue by saamirt** [microsoft/vscode#132605]
Issue Type: <b>Bug</b>

Not sure, extensions including Code Runner, Prettier, Arduino, C/C++, C#, Debugger for Java, etc. are just grayed out without any indication as to why.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (20.15GB free)|
|Process Argv|--crash-reporter-id 04091769-ff20-4f2c-a689-1da614e32ab4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
GetterAndSetterGenerator|afm|1.0.3
vscode-django|bat|1.6.0
simple-react-snippets|bur|1.2.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
python-snippets|cst|0.0.9
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|8.1.0
vs-code-xml-format|fab|0.1.5
php-intellisense|fel|2.3.14
code-runner|for|0.11.5
getter-setter-generator|Gab|1.4.0
vscode-javac|geo|0.2.39
gc-excelviewer|Gra|3.0.44
vscode-graphql|Gra|0.3.18
firebase-snippets|has|0.0.1
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|1.1.0
unity-code-snippets|kle|1.3.0
vscode-phpfmt|kok|1.0.30
MagicPython|mag|1.1.0
rainbow-csv|mec|1.9.1
csharp|ms-|1.23.15
mssql|ms-|1.10.1
python|ms-|2021.9.1191016588
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
vscode-react-native|msj|1.6.1
vscode-python-typehint|njq|1.4.1
material-icon-theme|PKi|4.10.0
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
prettier-now|rem|1.4.9
arduino-snippets|ron|1.0.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.0
js-jsx-snippets|sky|10.2.0
vscode-autohotkey|sle|0.2.2
java-generate-setters-getters|soh|7.3.0
svelte-vscode|sve|105.3.5
ayu|tea|1.0.5
python|tht|0.2.3
vsfire|tob|1.4.1
unity-tools|Tob|1.2.12
vscodeintellicode|Vis|1.2.14
vscode-arduino|vsc|0.4.4
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
full-react-snippets|wal|1.4.2
jinja|who|0.0.8
change-case|wma|1.0.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
plsql-language|xyz|1.8.2
unity-snippets|Ycl|0.1.2
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824:30361777
javagetstartedt:30351793
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by gjsjohnmurray** [comment]
Please start by updating to the current release, 1.60

**Comment by sandy081** [comment]
Can you please update to latest release and let us know if you are still reproducing it.
