### ISSUE TITLE
My Editor get red 

### ISSUE THREAD

**Issue by hckhanh** [microsoft/vscode#132603]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode

I really don't know how to turn off/fix it

![image](https://user-images.githubusercontent.com/6380436/132436173-9c26fd75-9952-4ac0-bd6c-3793fb7489bc.png)

**Comment by kkocdko** [comment]
Did you changed the `workbench.colorCustomizations`?

![image](https://user-images.githubusercontent.com/31189892/132441301-3d443761-a256-4c35-ad12-c7aa762ebbe4.png)

Or check the theme file? Try reinstall?

**Comment by zulrang** [comment]
If you're using the GitHub Themes, they made a change that made everything red.  A fix has been released, so just update the Github Theme extension.
