### ISSUE TITLE
Don't warn before closing empty files without undo history

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode#132673]
I sometimes open multiple editors by mistake, e.g. when typing `code <Ctrl+V>` in the command line, and my clipboard contains a multi-line block of text instead of the filename I expected. The newlines in the clipboard content lead the command to be executed and VS Code opens one editor for each word of the first line.

I would like to close these multiple editors without having to confirm, one by one, that I don't want to save the files.

Since these editors have no content (they don't merely refer to existing files that happen to be empty — the files themselves do not exist) and there's no edit history that could lead to data loss e.g. in case someone emptied the contents of an editor which did have content previously, it should be safe to either close them immediately by default, or provide an option in the settings to choose this behavior.

In fact, the [current warning dialog](https://github.com/microsoft/vscode/blob/78f63b7d0b1aeb737db54e08f1ce765940c58b4b/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L128-L130) is misleading, even. It says: 

> **Do you want to save the changes you made to &lt;foobar&gt;?**
>
> Your changes will be lost if you don't save them.

...when in reality there are no changes, and VS Code should be able to detect this. So perhaps this could even be considered a bug :)

**Comment by bpasero** [comment]
The reason these files appear as dirty immediately is to indicate that they are in fact not saved files on disk but untitled. Without the dirty indicator, they would appear as if they are on disk and that is maybe misleading?

**Comment by waldyrious** [comment]
I don't know what the best technical solution would be, but as a user, it seems appropriate to treat an empty editor with no changes the same way as a file that's been saved to disk (i.e., being safe to close without prompting).

Perhaps the "not-dirty" state should not automatically imply "saved on disk"? That might introduce some additional complexity to the editor's model (i.e. two independent states, "dirty" and "saved", rather than a single "dirty/saved" one), but it better reflects reality.

**Comment by bpasero** [comment]
I would like to see if people agree via upvotes, lets move to Backlog Candidates and let it sink for a while.
