### ISSUE TITLE
Slow spawn from ext host process when built from sources

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#132654]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version: Darwin x64 20.6.0

We noticed that vscode which is built locally, started to work much slower than previous version. Profiling shown that spawns take much more time than before (15ms vs 300-1500ms). One of the most notable places is getHead in the git extension.

Steps to Reproduce:

1. Checkout release 1.60
2. Go to extensions/git/src/git.ts
3. Add a measuring around the getHead() method
4. Locally compile vs code, and open the same repo
5. You will have getHead taking around 300ms
6. If you will do it, say on 1.55, it will much less than that (15ms)

On 1.55, it took much less (~15ms). It seems that it's caused by https://github.com/libuv/libuv/issues/3050 which was reverted due to broken tests (https://github.com/libuv/libuv/issues/3050#issuecomment-778495429). It seems that vscode uses patched version of electron (is it true?). Is it possible that you share the patched electron with the community?

cc @deepak1556

**Comment by solomatov** [comment]
Confirmed that the behavior is different in locally built vs MS version of VS Code.

If you have extension like this (derived from yo template), time on OSS vs time on MS version is different and consistent with what we have above:

```
import * as vscode from 'vscode';
import * as cp from 'child_process';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "test-it" is now active!');

	let disposable = vscode.commands.registerCommand('test-it.helloWorld', async () => {

		const folder = vscode.workspace.workspaceFolders![0];
		const path = folder.uri.fsPath;


		const start = Date.now();

		cp.spawnSync('git', ['status']);

		console.log('status took', Date.now() - start, 'ms');
	});
}

// this method is called when your extension is deactivated
export function deactivate() {}
```

**Comment by deepak1556** [comment]
You can try newer version of patch from https://github.com/libuv/libuv/pull/3257

**Comment by solomatov** [comment]
@deepak1556 Ok. Will do it. Thanks for your help!

**Comment by solomatov** [comment]
@deepak1556 BTW, which patch do you use in the latest vscode? (may be there're other patches as well)

**Comment by deepak1556** [comment]
Current stable is based on Electron 13 which uses the patch attached in https://github.com/electron/electron/issues/26143#issuecomment-879569238

**Comment by solomatov** [comment]
@deepak1556 Thanks, I will!

**Comment by solomatov** [comment]
@deepak1556 One more question if you don't mind. How do you build it? I assume you have some hidden repo, but electron has only cricle ci scripts. Do you have any other scripts to run it on github or azure?

Also, I assume that you plug your custom build here: https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L204 Is there an easy way to plug a locally built electron in there?

**Comment by deepak1556** [comment]
Yes our custom build uses Azure pipelines. The scripts are not generic enough to share for external usage.

> Also, I assume that you plug your custom build here: https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L204 Is there an easy way to plug a locally built electron in there?

You can provide a new repo value for (repo)[https://github.com/microsoft/vscode/blob/main/build/lib/electron.ts#L187] via product.json which contains binaries published in the format like https://github.com/electron/electron/releases/tag/v14.0.0
