### ISSUE TITLE
1.60.0: terminal defaultProfile not working on windows

### ISSUE THREAD

**Issue by mduft** [microsoft/vscode#132615]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0, tested also 1.61.0-insider
- OS Version: Windows 10 21H1 Build 19043.1165

The issue appeared with the 1.60.0 update - before that everything was working flawlessly.

Steps to Reproduce:

1. Configure Git Bash as default terminal
2. Restart VSCode
3. Use "Angular Schematics" extension, which triggers a command on the default terminal - which uses the wrong one. See Video.

https://user-images.githubusercontent.com/533793/132456179-bd830853-935d-4c47-99b4-fa6dd22ca363.mp4

It seems the issue is not 100% reproducible. I played a little with the configuration and at one point I restarted and both the initial terminal as well as the one use by angular schematics worked fine. Today I started again with the very same configuration and things stopped working again and I can't get them back to working.

In 1.60.0 it seems that whenever the initial startup terminal is wrong, the terminal used by schematics is also wrong. In 1.61.0-insider though, I managed to get the *initial* terminal to be the correct one, but the one used by the angular schematics plugin is the wrong one - which is even worse xD

Edit: Note that setting `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",` did not change anything. VSCode is still starting powershell insead.

**Comment by pablohs1986** [comment]
Same problem here. I had Git Bash as the default terminal. Since the update to v.1.60, it is impossible to configure a default terminal in Windows, Powersell always appears.

**Comment by gjsjohnmurray** [comment]
/duplicate of #132150 and will be fixed in upcoming 1.60.1 recovery release

**Comment by mduft** [comment]
Should this be fixed in 1.61.0-insider? Because it does not...

**Comment by gjsjohnmurray** [comment]
> Should this work in 1.61.0-insider? Because it does not...

@meganrogge please investigate

**Comment by mduft** [comment]
The issue indeed *is* fixed after update to 1.60.1. Thanks
