### ISSUE TITLE
VS Code Freezes/Hangs when switching file tabs or selecting an already open file

### ISSUE THREAD

**Issue by SVVSD-Woods** [microsoft/vscode#132666]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
 1.60.0
- OS Version:
 Windows 10 Pro (Education) build 19042.1165 / 14GB memory

Steps to Reproduce:

1.  Open multiple files (I have 30+ open). Either switch between them using tabs, or by selecting files from the open editors menu.
2.  Code freezes after a several tab changes.  I have to wait up to five minutes before I can use Code again.  This has been happening for a few months now, and I am really close to finding a new editor. :(

Note: I have disabled all extensions and have done a re-install. I also have Visual Studio Community 2019 ver. 16.9.4 installed.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by SVVSD-Woods** [comment]
I uninstalled Code and installed the insiders version.  Opened my folder, then opened a several files (12 or so), then tried to drag one of the tabs and it hung right away.  It stays hung for a few minutes then I can use Code again.

The files are mostly .js inside an Angular app.

Any ideas?

**Comment by bpasero** [comment]
> then tried to drag one of the tabs

That is not what the summary indicates, the summary indicates you just click on a file. So what do you do?

Gif please.

**Comment by SVVSD-Woods** [comment]
Either, or. Drag a tab or click a file in the Open Editors list.

Also, I just installed Code using the System Installer (64bit), and it has the same issue.

**Comment by bpasero** [comment]
Are you mixing user rights? Running as admin vs installed as normal user?

**Comment by SVVSD-Woods** [comment]
Here's the gif. I could only capture a minute or so before gifcap ran out of memory.

I'm running as an admin, but there are group policies on our windows installations.  I've run it this way for over a year with no issues, until a few months ago.

![recording](https://user-images.githubusercontent.com/60297335/132886851-e31c6590-7a93-4d55-bcb8-08758b7a757a.gif)

**Comment by SVVSD-Woods** [comment]
One nuance I just noticed is that it's the drag operation that causes the hang. It's possible that in the Open Editors list, when I click on a file, I might be accidentally invoking a drag.

**Comment by bpasero** [comment]
We do not officially support running VSCode as admin and it will likely not be an option going forward. 

I suspect this is a Chrome issue.

**Comment by SVVSD-Woods** [comment]
On my home computer, I run as Admin as well and it works fine.  Same version of Code installed, same Chrome version as well.

**Comment by deepak1556** [comment]
@SVVSD-Woods can you confirm the following points, thanks!

1) Does the issue happen with user installed version and not run as admin ?
2) What is your requirement to run vscode as admin ?

**Comment by SVVSD-Woods** [comment]
Yesterday, I updated my Wacom drivers for my pen, and rebooted my pc.  So far I have not experienced the freezing when moving tabs or files in the Open Editors view. Not sure if it was related to the Wacom drivers but they are a likely suspect.
