### ISSUE TITLE
Ignoring "Command Prompt" in terminal.integrated.defaultProfile.windows during build.

### ISSUE THREAD

**Issue by mcheedle** [microsoft/vscode#132766]
Issue Type: <b>Bug</b>

VS Code is no longer recognizing "terminal.integrated.defaultProfile.windows": "Command Prompt" when I run a build while building an Azure Function dotnet core 3.1 project.

As a workaround I'm setting "terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe". This started happening this week after an update.

"Command Prompt" = "C:\\Windows\\System32\\cmd.exe" in profiles.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
azurite|Azu|3.14.2
vscode-markdownlint|Dav|0.43.2
vscode-diff|fab|1.4.2
code-runner|for|0.11.5
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
minifyall|jos|2.9.2
json2csv|kha|0.0.1
l13-diff|L13|1.0.3
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-asa|ms-|1.0.1
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
mssql|ms-|1.10.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
azure-account|ms-|0.9.8
notepadplusplus-keybindings|ms-|1.0.7
azurerm-vscode-tools|msa|0.15.2
elastic|ria|0.13.3
azure-event-hub-explorer|Sum|0.1.1
change-case|wma|1.0.0

</details>

**Comment by IllusionMH** [comment]
Please try latest Insiders build and let devs know if it's still broken.
https://code.visualstudio.com/insiders/

**Comment by mcheedle** [comment]
The insiders build worked! Thank you.
