### ISSUE TITLE
Too many Cell outputs generated when replacing cell output with a new item containing a single output item

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#132772]
Identified when debugging https://github.com/microsoft/vscode/issues/131914

VS Code version: OSS
OS: Mac

**Scenario:**
* Run a cell
* Cell generates outputs
* Extension will replace output with a new output containing a single output item
* Everytime extension gets new output, the output is concatenated with the existing output.

Thus the over all effect is: we have a single output object with a single output item.

However, when we replace the output item, looking at the code we can see that we're passing a few 100 outputs around. I have a scenario where i have just 350 lines and each line is generated one at a time, looking at the logs we end up calling `NotebookCellData.to` with a cell data object containing 699 outputs.

This happens over 600 times. Feels like a lot of unecessary serialization & deserialization (data being passed back & forth).

I cannot tell whether this causes any perf issues, buf if this code is run over an hour, then we'd end up with a very very large number of outputs (running code for an hour or even 15-20 minutes is common in machine learning when training models) & at that point when we get output we end up in this scenario.

I.e. I think in CodeSpaces & and when users run cells for long periods of time this could be a perf issue.

**Comment by roblourens** [comment]
I can't repro it in Jupyter and am not sure how this would happen, if you can still repro can you show me? I can't get the Node notebook example to run, I get this error `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/roblou/code/node-notebook/node_modules/node-fetch/src/index.js`

**Comment by DonJayamanne** [comment]
Please use `isomorphic-fetch` instead of `node-fetch` (not entirely sure why it works for me, updated the samples to use that instead of `node-fech`).

**Comment by roblourens** [comment]
I see it, thanks. Are you sure you are not doing appendOutput? I see appends coming through on the front end (didn't debug renderer yet)

**Comment by DonJayamanne** [comment]
My bad, its an issue at my end.
