### ISSUE TITLE
text invisible on terminal window after using git stash list

### ISSUE THREAD

**Issue by Nitin4191** [microsoft/vscode#132720]
Issue Type: <b>Bug</b>

1. Use git stash list to see previously stashed changes in any project.
2. After seeing all changes exit the git stash list. I have over 40 stashes so results might vary.
3. No text will be seen on typing but will work.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by meganrogge** [comment]
please attach a gif of this
