### ISSUE TITLE
Visual Studio Code window is not responding on startup 

### ISSUE THREAD

**Issue by PabloRiv** [Microsoft/vscode#13273]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Displays Info window that says, "The workspace folder contains TypeScript 2.0.2. Do you want to use this version instead of the bundled version 1.8.10?"
2. Cannot escape or close info message bar

**Comment by t2rif3** [comment]
you have to change the settings.json under `File/Preferences/Workspace Settings` and add this `"typescript.tsdk": "node_modules/typescript/lib"`. maybe this link will help you:
http://stackoverflow.com/questions/39505048/version-mismatch-between-tsc-compiler-and-vs-codes-language-service

**Comment by Tyriar** [comment]
@PabloRiv can you provide a screenshot of the issue? Also run `code --verbose` and paste in the output when it becomes unresponsive.

**Comment by waderyan** [comment]
Closing until more info is given.
