### ISSUE TITLE
Omnisharp DefaultLaunchSolution Setting Is Broken

### ISSUE THREAD

**Issue by JonathanTremblay** [microsoft/vscode#132760]
Issue Type: <b>Bug</b>

1. Create a C# project containing more than one SLN and/or CSPROJ files.
2. Open the project in VSCode 1.60 (or the current Insiders build).
3. Omnisharp is supposed to load the first file by default. But it doesn't select the file automatically. Instead, it opens the Command Palette with Omnisharp: Select Project to ask the user to make a selection.

Note: If the DefaultLauchSolution setting is edited with a precise file (e.g. 'Test.sln'), the project opens with the desired file, but if the setting is empty (null), the bug happens.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.34GB free)|
|Process Argv|C:/ProjetsUnity/TestChoix2_newPath -g C:\\ProjetsUnity\\TestChoix2_newPath\\Assets\\NewBehaviourScript.cs:1:0 --crash-reporter-id 85db5a8f-5826-4c3a-96bd-c29ecd856909|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
docomment|k--|0.1.20
unity-snippets-modified|lio|0.4.0
vscode-language-pack-fr|MS-|1.60.3
csharp|ms-|1.23.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604

```

</details>

**Comment by lramos15** [comment]
Please open an issue against https://github.com/OmniSharp/omnisharp-vscode
