### ISSUE TITLE
Settings with type object and numerical properties don't show up properly

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode#132748]
Issue Type: <b>Bug</b>

In the [documentation](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema), it says the following:

> Objects that have properties of type `number`, `string`, and `boolean` will be rendered as editable grids of keys and values

However, given the following `configuration` entry:

```json
"cursorless.hatPenalties.colors": {
	"description": "How much to penalize each hat color. Number of syllables is a good default",
	"type": "object",
	"properties": {
		"blue": {
			"type": "number"
		},
		"green": {
			"type": "number"
		},
		"red": {
			"type": "number"
		},
		"yellow": {
			"type": "number"
		},
		"pink": {
			"type": "number"
		}
	},
	"default": {
		"blue": 1,
		"green": 1,
		"red": 1,
		"yellow": 1,
		"pink": 1
	},
	"additionalProperties": false
}
```

I get the following in my settings:

![image](https://user-images.githubusercontent.com/755842/132683861-64825ada-0c56-48b5-b2a6-46da94ef6492.png)

Note that if all the properties have type `string` instead of `number`, they show up as an editable grid, as expected

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.04GB free)|
|Process Argv|--crash-reporter-id 99d35f96-61a9-461b-a60d-f915d32f3eee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.1
vscode-neovim|asv|0.0.82
All-Autocomplete|Ati|0.0.23
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.4.0
regex|chr|0.4.0
vscode-eslint|dba|2.1.25
chmod|dle|1.1.1
githistory|don|0.6.18
xml|Dot|2.5.1
viml|dun|0.1.7
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
remotehub|Git|0.14.0
vscode-pull-request-github|Git|0.30.0
mdmath|goe|2.7.4
rest-client|hum|0.24.5
jq-syntax-highlighting|jq-|0.0.2
bash-ide-vscode|mad|1.11.0
syntax-project-pbxproj|mar|0.1.3
rainbow-csv|mec|1.9.1
metago|met|4.2.0
MetaJump|met|1.2.1
MetaWord|met|1.3.0
git-graph|mhu|1.30.0
goto-next-previous-member|mis|0.0.5
vscode-edits-history|mis|0.1.6
vscode-talonscript|mro|0.3.2
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4761
vscode-react-native|msj|1.6.1
autodocstring|njp|0.5.4
command-server|pok|0.7.0
cursorless|pok|0.21.0
parse-tree|pok|0.9.0
ruby|reb|0.28.1
LiveServer|rit|5.6.1
format-code-action|roh|0.1.0
multi-command|ryu|1.5.1
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.4
vscode-open-in-github|sys|1.15.0
tabnine-vscode|Tab|3.4.26
vscodeintellicode|Vis|1.2.14
vscode-icons|vsc|11.6.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by roblourens** [comment]
Remind me, is this case supposed to work @rzhao271 or did we not do it for numbers?

**Comment by rzhao271** [comment]
We don't do it for numbers yet.
That's being tracked at https://github.com/microsoft/vscode/issues/129592

**Comment by rzhao271** [comment]
I'll mark this as a duplicate and fix the docs.

**Comment by pokey** [comment]
Oh weird I searched and that issue didn't come up for me. Apologies for the spam 🙈
