### ISSUE TITLE
java não funciona

### ISSUE THREAD

**Issue by saturno1977** [microsoft/vscode#132763]
Nós escrevemos os dados n
Issue Type: <b>Performance Issue</b>

o java não roda 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD C-60 APU with Radeon(tm) HD Graphics (2 x 998)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.60GB (0.40GB free)|
|Process Argv|--crash-reporter-id 3c686dea-176d-4afe-99b9-2731cf60004f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    42	 10344	code main
   12	    56	  1984	   window (Relator de Problemas)
    1	    18	  7108	   gpu-process
   48	    48	  7724	   shared-process
    0	     3	  9936	     ptyHost
    0	     0	  9440	       console-window-host (Windows internal process)
    0	     0	 11008	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   142	  8684	   window (project.java - java-vscode - Visual Studio Code)
    0	     0	  7552	     watcherService 
    0	     0	  6704	       console-window-host (Windows internal process)
    0	     9	  8952	   utility
    0	     0	 11032	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (project.java - java-vscode - Visual Studio Code)
|    Folder (java-vscode): 3 files
|      File types: json(1) java(1)
|      Conf files: launch.json(1);
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-javac|geo|0.2.39
sass-lint|gle|1.0.7
beautify|Hoo|1.5.0
vscode-git-tags|how|1.4.4
fontawesome-autocomplete|Jan|1.1.2
vscode-styled-components|jpo|1.6.6
vscode-github|Kni|0.30.6
vscode-language-pack-pt-BR|MS-|1.60.3
vscode-dotnet-runtime|ms-|1.2.0
remote-containers|ms-|0.194.0
cpptools|ms-|1.6.0
sublime-keybindings|ms-|4.0.10
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.6.1
color-highlight|nau|2.4.0
vscode-extension-auto-import|Nuc|1.4.3
docthis|oou|0.8.2
material-icon-theme|PKi|4.10.0
quicktype|qui|12.0.46
java|red|0.81.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
js-jsx-snippets|sky|10.2.0
sonarlint-vscode|Son|2.1.2
autoimport|ste|1.5.4
sass-indented|syl|1.8.18
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-pack|vsc|0.18.4
caniuse-query|Wil|0.0.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30361775
pythonf5test824cf:30361778
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604

```

</details>

ecessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide detailed problem description and steps to reproduce in English.
