### ISSUE TITLE
vs code 158

### ISSUE THREAD

**Issue by cintraxavier** [microsoft/vscode#132704]
Issue Type: <b>Bug</b>

Traduce de portuguese to English
Cannot install the extension 'ms-toolsai.jupyter' because it is not compatible with the current version of VS Code (version 1.58.0). I want to install python extension and it is incompatible

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.64GB (0.48GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.3
cyberbrain|lai|0.2.0
vscode-language-pack-pt-BR|MS-|1.58.9

</details>

**Comment by cintraxavier** [comment]
Alguém sabe me dizer o que seria isso, erro que deixa instalar o Pyhton por ser uma versão desatualizada ou já está atualizada, no python está atual 3.9, me ajudem por favor!!!

**Comment by sandy081** [comment]
Can you please update VS Code and try again?
