### ISSUE TITLE
A series of problems caused by bracket pair colorization

### ISSUE THREAD

**Issue by liby** [microsoft/vscode#132762]
Issue Type: <b>Bug</b>

1. Write code
2. It is found that the parentheses that should match are colored differently.
    2.1  Minimal replication can be found [here](https://github.com/liby/base64-rs/blob/main/src/main.rs#L48).
    ![image](https://user-images.githubusercontent.com/38807139/132715641-fc72cecb-f7ff-4f50-84fd-04938f48464b.png)

And then there’s the issue of [angle brackets coloring](https://github.com/microsoft/vscode/issues/132476), I think this is the same for Rust, please restore the previous style.
![image](https://user-images.githubusercontent.com/38807139/132716442-48980f75-45aa-49db-82bc-b92af1a70c7a.png)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.38GB free)|
|Process Argv|. --crash-reporter-id e0440de6-b5ea-426f-9ba9-e175b8460637|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
gitlens|eam|11.6.0
copilot|Git|1.4.2635
rust-analyzer|mat|0.3.738
git-graph|mhu|1.30.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.10.0
vscode-fileutils|sle|3.4.5
guides|spy|0.9.3
code-spell-checker|str|2.0.4
even-better-toml|tam|0.14.2
vim|vsc|1.21.7
material-theme|zhu|3.11.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30361774
pythonf5test824cf:30361778
pythonvspyt187cf:30362783
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by IllusionMH** [comment]
Rust extension should remove `<>` form colorizing already, but not released yet
https://github.com/rust-analyzer/rust-analyzer/pull/10186

And you linked issue that should remove `<>` for other languages by default.

And I guess problems with `}` on first screenshot may be caused by unmatched `>`.
Is it still a problem if you comment/remove 3 lines with `=>` ?
![image](https://user-images.githubusercontent.com/1312662/132737700-e23b7cd9-4fc7-43cb-93f9-de3a3127b37c.png)

/cc @hediet

**Comment by liby** [comment]
> And you linked issue that should remove <> for other languages by default.

Because there is a similar problem in Rust, so the link is to a similar issue that already exists, in case the description is not clear to generate misunderstanding, there is also a fear of creating a similar issue repeatedly.


> And I guess problems with } on first screenshot may be caused by unmatched >.
Is it still a problem if you comment/remove 3 lines with => ?

Not for that reason, but it looks like the problem has disappeared in the latest rust-analyzer.
![image](https://user-images.githubusercontent.com/38807139/132784810-a2833689-221b-4d25-a4d7-d964f8a80e06.png)
