### ISSUE TITLE
Customizable Editor Context menu

### ISSUE THREAD

**Issue by R35007** [microsoft/vscode#132752]
Need Customization for the editor context

 - When I right click my editor, I see lots of commands which I rarely use. 
 - Is there any way to customize the editor context menu. ?
 - I wish I can customize the editor context by keeping only my favorite commands in the context.

Suggestion: 
 - Have a separate .json file for context menu which it list down all the editor context commands.
 - Now I can able to enable and disable or show and hide the context which I like.
 -  Is it possible to bring the cut, copy, paste at top as it is in windows 11 ?

Thanks,
Siva

**Comment by R35007** [comment]
Cool. Thanks for the Update ☘️

**Comment by sisrfeng** [comment]
Hi, would you mind feaguring out where is the duplicated issue? How to customize the Editor Context Menu?
