### ISSUE TITLE
Array of TypeScript SDK paths in project VSCode settings

### ISSUE THREAD

**Issue by marcmarina** [microsoft/vscode#132757]
There's a feature I'd like to have for the `.vscode` settings folder of a project. I'd like the option to set a typescript SDK path to accept an array of values. Right now the path VSCode sets is OS-specific, so working on different machines makes you change the setting every time and commit it.

**Comment by mjbvz** [comment]
Can you share some examples of the paths you are using? Relative paths should work cross platform

**Comment by marcmarina** [comment]
This is the path VSCode sets when used on Windows: `node_modules\\typescript\\lib`.
And this is on Linux: `node_modules/typescript/lib`.

This is inside `.vscode/settings.json` in a project's root folder.

**Comment by mjbvz** [comment]
Thanks. Did VS Code write those setting values automatically or did you add them?

**Comment by marcmarina** [comment]
You're welcome :D That was VS Code setting them
