### ISSUE TITLE
Search for extensions and tell me "we cannot connect to the Extensions Marketplace at this time, please try again later"

### ISSUE THREAD

**Issue by chenjinchao** [microsoft/vscode#132716]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

- OS Version:
Version: Windows 10 Home Edition
Version number:	21H1
Installation date:	‎2020/‎12/‎28
Operating system internal version:	19043.1165
Serial number:	LR05V8QR
Experience: Feature Experience Pack 120.2212.3530.0

Steps to Reproduce:

1.Open vscode and toggle developer Tools
<img width="1276" alt="1" src="https://user-images.githubusercontent.com/11922485/132624412-18e5adae-6f81-45db-9276-6119ce088845.png">

2.Click to expand
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/11922485/132624411-519e211d-d3db-4565-aaf2-042ebca3d319.png">

3.Search extension
<img width="1280" alt="3" src="https://user-images.githubusercontent.com/11922485/132624460-32c2e818-bfb5-417f-ba9d-2152059fc8ed.png">

**Have a CORS error**
**Still so after reinstalling**

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/132634
