### ISSUE TITLE
Bracket colorization: Exlude scope

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#132786]
Exclude the bracket pair colorization by scope inside a language.
I code in a language that has the feature of unbalanced brackets:
`range(0,1]` and `range[0,1)` are perfectly valid here.
It would be great if a language definition could somehow exlude these scopes from the bracket colorization, because otherwise they will always look like an error has made (which hasn't).

**Comment by hediet** [comment]
I fear implementing this is not going to be easy, if possible at all with the current architecture.

What exactly do you mean with "scope"? Do you have an example?
These scopes would need to be defined by the text mate grammar.
Unfortunately, only some very limited properties of tokens are stored and can be used for skipping brackets in strings/comments.

**Comment by runxel** [comment]
> 
> 
> I fear implementing this is not going to be easy, if possible at all with the current architecture.

Yeah, I feared that, too! 😅

> What exactly do you mean with "scope"? Do you have an example?
> These scopes would need to be defined by the text mate grammar.

Yes exactly. With scope I mean a textmate grammar scope (like in my example it would be `keyword.parameter.gdl`. The language has the whole `range()` thing as one scope currently, without distinguishing between the different possible brackets.)

**Comment by hediet** [comment]
@alexdima do you have ideas here?
I think besides comments/strings/regexp there are some bits left in the token metadata.
What about `*.unstructured` for tokens that don't contribute to the "structure" of the document?

That way, a grammar could mark `range(0,1]` as `keyword.unstructured`.

**Comment by hediet** [comment]
Btw. maybe you can change your textmate grammar to treat `range[0,1)` as single regex token (which has other implications though). In that case, these brackets are skipped.
