### ISSUE TITLE
Extensions don't appear as `preview` in product

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13276]
- VSCode Version: Code - Insiders 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d, 2016-10-01T00:34:33.697Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.sort-lines-1.1.0, Tyriar.theme-glacier-0.0.10, Tyriar.vscode-terminal-here-0.0.5, christian-kohler.path-intellisense-1.0.2, cssho.vscode-svgviewer-1.2.0, dbaeumer.vscode-eslint-1.0.7, eg2.tslint-0.5.39, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.3, rebornix.Ruby-0.8.0, rebornix.nova-0.0.5, redhat.java-0.0.4, ryu1kn.annotator-0.10.0, ryzngard.vscode-header-source-1.0.4

https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs is an example of an extension that has `"preview": true` in its package.json which shows up on [web](https://marketplace.visualstudio.com/items?itemName=Tyriar.terminal-tabs) but not in product.

**Comment by gerane** [comment]
I would say the user should be given option to choose preview or stable. I'd there any other usage of this flag other than a visual indicator on the marketplace? 

Maybe have a config for extensions you allow preview builds of. If you have terminal tabs listed in the config for preview, it updates to the preview version, but stays at the stable version for others.

**Comment by pbt** [comment]
I'm new to this; can I take this on?

**Comment by joaomoreno** [comment]
Sure

**Comment by golf1052** [comment]
I've implemented this in #36261
