### ISSUE TITLE
VSCode occupy much CPU resource when it free

### ISSUE THREAD

**Issue by shuaigit** [microsoft/vscode#132746]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.60.0(user setup)
- OS Version:Ubuntu 18.04

Steps to Reproduce:

1.Let VSCode free
2.View CPU usage

**Comment by deepak1556** [comment]
Please provide the output of `ps -eo pcpu,pid,user,args` or any other similar commands showing the cpu usage from the code process, thanks!

**Comment by shuaigit** [comment]
PID   USER         PR  NI    VIRT    RES      SHR S  %CPU %MEM     TIME+ COMMAND
 9225 zhaweih+  20   0 5657476 1.024g  75844 S  99.7  3.3   1:25.05 cpptools-srv
 2324 zhaweih+  20   0 1033156 146540  33020 S   1.0  0.4   0:10.46 node
10714 shuaiba+  20   0   46624   4320   3364 R   0.7  0.0   0:00.16 top

**Comment by deepak1556** [comment]
`cpptools-srv` is from the https://github.com/microsoft/vscode-cpptools extension, please open an issue with the extension for further debugging.
