### ISSUE TITLE
Defaults to Debugging in Power Shell even when default in cmd.exe

### ISSUE THREAD

**Issue by markwaters306** [microsoft/vscode#132740]
Visual Studio Code keeps defaulting to Power Shell when running the debugger. This wasn't changed by the user and automatically defaulted to this. The default settings have been changed back to use cmd.exe as the default terminal but debugging keeps trying to use Power Shell which doesn't work with conda env.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.55GB free)|
|Process Argv|--crash-reporter-id 579658e7-be48-420d-9236-b698ae5dd88d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 30344	code main
    0	    24	  7528	   utility
    0	   162	 17028	   window (● launch.json - testing - Visual Studio Code)
    0	    38	 11512	     searchService
    0	   131	 23892	     extensionHost
    0	   133	 21736	       electron_node bundle.js 
    0	    41	 23088	       "C:\Users\watersm\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\watersm\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=23892
    0	    13	 32976	     watcherService 
    0	    14	 28052	       console-window-host (Windows internal process)
    0	    74	 24108	   shared-process
    0	    50	 17276	     ptyHost
    0	     9	  4160	       console-window-host (Windows internal process)
    0	     9	  9728	       console-window-host (Windows internal process)
    0	     7	 21216	       C:\WINDOWS\System32\cmd.exe
    0	    72	 28776	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   184	 28720	   gpu-process
    0	    17	 29624	   crashpad-handler
    0	    28	 30276	   utility
    0	    56	 31904	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● launch.json - testing - Visual Studio Code)
|    Folder (testing): 41 files
|      File types: py(16) png(8) css(4) json(3) ico(2) svg(2) DS_Store(1)
|                  pyc(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.6.0
vscode-icons|vsc|11.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
javagetstartedt:30351793
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

oo large to send. Please paste.

**Comment by mfaheemakhtar** [comment]
Similar issue.

When I open a project, it opens the Powershell first time (default is bash). After closing the powershell and opening a terminal again, it works fine, i.e. opens the bash.

**Comment by markwaters306** [comment]
> Similar issue.
> 
> When I open a project, it opens the Powershell first time (default is bash). After closing the powershell and opening a terminal again, it works fine, i.e. opens the bash.
> 
> Edit: Looks like mine is resolved in #132150

Hi mfaheemakhtar,

Thanks for your reply. The issue still persists when I close the power shell terminal. I can open a cmd terminal fine but it's when I go to use the debugger it reverts back to PS and opens another terminal.

I've even deleted the path to Power Shell in  the settings to try stop it but no success.

From reading the other comments in #132150 it looks like my only option is to downgrade to <1.6

**Comment by albertosantini** [comment]
Before downgrading, It seems the recovery release is released in hours, reading latest comment in that issue.

**Comment by roblourens** [comment]
Should be fixed in Insiders. The recovery release has been delayed though to fix another issue. https://github.com/microsoft/vscode/issues/132150
