### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by VikasTandon** [microsoft/vscode#132783]
We have written the needed data into yI face major problem in html and javascript. In javascript "!" is not work vs code this message "command 'emmet.expandAbbreviation' not found"
and html boiler plate could not appear with this sign "!"  Please help me to resolve this our clipboard because it was too large to send. Please paste.

**Comment by rzhao271** [comment]
If you go to the extensions viewlet (the tab that shows installed extensions) and search `@builtin`, does Emmet show up as a disabled extension?
Also, if you open the command palette and run the Toggle Developer Tools command, are there any errors being reported from Emmet?
