### ISSUE TITLE
The search extension shows that you can't connect to the extension store right now. Please try again later.

### ISSUE THREAD

**Issue by liyuhui653139137** [microsoft/vscode#132709]
Issue Type: <b>Bug</b>

The recommended content in the extension can be displayed or downloaded normally, but the search cannot be used and is displayed you can't connect to the extension store right now. Please try again later. Open the developer tool, which displays the cross domain search interface

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 10, 9|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 4d50e280-870d-4e25-9b69-3f26f299e627|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
flutter-snippets|ale|2.0.0
vscode-ant-design-vue-helper|ant|1.0.6
smarty-template-support|asw|1.9.0
eggjs|ati|0.3.1
antd-snippets|ban|1.2.0
vscode-intelephense-client|bme|1.7.1
egg-sequelize-helper|cao|1.0.6
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-eslint|dba|2.1.23
python-preview|don|0.0.4
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.8
pythonsnippets|frh|1.0.2
path-autocomplete|ion|1.17.1
pubspec-assist|jer|2.3.0
vsc-python-indent|Kev|1.14.2
vscode-gutter-preview|kis|0.27.1
vscode-leetcode|Lee|0.18.0
flutter-tree|mar|1.0.0
vscode-language-pack-zh-hans|MS-|1.60.3
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
debugger-for-chrome|msj|4.13.0
awesome-flutter-snippets|Nas|3.0.1
color-highlight|nau|2.4.0
autodocstring|njp|0.5.4
korofileheader|OBK|4.8.17
vetur|oct|0.34.1
vscode-css-peek|pra|4.2.0
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vue-helper|she|2.4.7
autoimport|ste|1.5.4
var-translation|sve|0.13.22
highlight-matching-tag|vin|0.10.1
vscode-translator|vol|0.0.3
JavaScriptSnippets|xab|1.8.0
eggjs-dev-tools|yuz|0.4.0
material-theme|zhu|3.11.4
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by sandy081** [comment]
Can you please try and share following details:

    - Help -> Toggle Developer Tools -> Console
    - View -> Open View… -> Log (Window)
