### ISSUE TITLE
vscode.env.shell always set to PowerShell instead of default profile

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#132787]
Issue Type: <b>Bug</b>

Could be related to https://github.com/microsoft/vscode/issues/132150, but I tested on Insiders and my issue (which is slightly different) is still reproducing. This only started happening in v1.60.0

### Repro steps

1. Add this to your user settings:
"terminal.integrated.defaultProfile.windows": "Command Prompt"
2. Create a 'hello world' extension and add this code:
    `vscode.window.showInformationMessage(vscode.env.shell);`
3. F5 the extension and run the hello world command

### Expected:
`env.shell` is set to the command prompt

### Actual
env.shell is set to PowerShell, no matter how long I wait or even if I reload VS Code
![Screen Shot 2021-09-09 at 11 28 12 AM](https://user-images.githubusercontent.com/11282622/132742353-d2fcf056-f1cb-49a7-a5a4-bb9741c62f89.png)
The terminal itself seems to respect the profile setting, though:
![Screen Shot 2021-09-09 at 11 28 00 AM](https://user-images.githubusercontent.com/11282622/132742442-905af5f5-7521-4bcd-bba6-7834d1cd7c2c.png)

VS Code version: Code - Insiders 1.61.0-insider (aa93eefe550167de3ca29aaa3d06f721a47594a3, 2021-09-09T05:15:19.597Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (4 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (9.87GB free)|
|Process Argv|--crash-reporter-id fb927676-2903-44ae-bbc9-133db7d2893d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ejizba** [comment]
@Tyriar are you sure it's a duplicate? I'm aware of the linked bug, but my issue is still reproducing on Insiders. I even tried on today's version: 

> 1.61.0-insider (user setup)
> Commit: 0884da1650baa24994d23d2a3742823c1186e526
> Date: 2021-09-10T08:12:39.143Z
> Electron: 13.1.8
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19043

**Comment by Tyriar** [comment]
Some related fixes got pushed in in the past few hours
