### ISSUE TITLE
Red theme: xml and ascx files are too red.

### ISSUE THREAD

**Issue by bbarry** [Microsoft/vscode#13271]
- VSCode Version: 1.5.2
- OS Version: Win7

Steps to Reproduce:

1. open xml file or ascx file or xsl file
2. open html or aspx file
3. switch to Red theme
4. compare open files

(file contents don't matter so long as there is some sort of xml document including tags, attributes and text content; it seems sufficient to save the same file with various extensions)

Expected Results:

* syntactic elements shared between these file types appear the same colors as they do in other themes (Dark theme for example)

Actual Results:

* xml and ascx files do not appear to identify much syntax compared to html or aspx files

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode-themes/issues/10
