### ISSUE TITLE
Extension code actions blocking file saves

### ISSUE THREAD

**Issue by phylix** [microsoft/vscode#132798]
Extensions with long-running code actions will sometimes block saving.

Message appears saying "Running Save Participants," which lasts between 3 and 20 seconds.

**Comment by mjbvz** [comment]
Which extension is causing this? Shouldn't they fix their code actions?

**Comment by phylix** [comment]
It was from a company's internal extension.

**Comment by mjbvz** [comment]
I'm closing this as it sounds like a workaround for an extension issue

If we were to add a timeout, I think don't think it should be specific to code actions as slow formatters can also cause this issue
