### ISSUE TITLE
Markdown cells don't get rendered and an error 'No renderer found for "text/markdown" a' is shown

### ISSUE THREAD

**Issue by Jakoviz** [microsoft/vscode#132788]
## Environment data

-   VS Code version: 1.61.0-insider & stable 1.60
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001208778 (insider) & v2021.8.2041215044 (stable)
-   Python Extension version (available under the Extensions sidebar): v2021.10.1210725981-dev (insider) & v2021.10.1200408502-dev (stable)
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04
-   Python and/or Anaconda version: Python 3.8.3, Anaconda 2020.07
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A & virtualenv
-   Jupyter server running: Local & Remote

## Expected behaviour

Markdown rendered properly.

## Actual behaviour

Markdown cells don't get rendered and an error 'No renderer found for "text/markdown" a' is shown.
![image](https://user-images.githubusercontent.com/7263106/132656909-85fac434-19bf-4128-b3f0-53148630528e.png)

## Steps to reproduce:
No matter whether I "Add markdown cell" or turn a code cell into markdown, the result is the same. I've been using notebooks on VS Code since March on two different computers with totally different setups (one Windows and the other one Linux) and I can't remember ever seeing the markdown cells rendered properly during this time on either one. I've only got this error since the beginning.

## Logs

<details>

<summary>
</summary>

<p>
</p>
</details>

**Comment by DonJayamanne** [comment]
Please note: Markdown rendering is supported in VS Code core (not an extension).

**Comment by mjbvz** [comment]
Have you disabled VS Code's built-in markdown extension? Search `@builtin markdown` in the extension view to check this

**Comment by Jakoviz** [comment]
That did it, Markdown Language Features was disabled. I did search the command palette and settings with "markdown", but couldn't find anything relevant. Good to know this "@builtin" key word. Thanks.
