### ISSUE TITLE
Add TerminalProperty ptyHost message

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#132774]
deferred from #132691

How about we have a new generic pty host message something like this to avoid all this piping through in the future for similar props?

```
onDidChangeProperty(name: TerminalProperty)

const enum TerminalProperty {
  cwd,
  initialCwd, // This wouldn't change but we could fetch it using a shared mechanism
  // We could add more like below after we validate this is a good idea
  // title,
  // icon,
}
These could always get synced over to the renderer when it changes so accesses are free?
```

related 
- https://github.com/microsoft/vscode/pull/132691#discussion_r705524180
- https://github.com/microsoft/vscode/pull/132691#discussion_r705207786

we will store the properties on the LocalPty object and reference them directly instead of the round trip every time

**Comment by Tyriar** [comment]
Also on RemotePty for remote terminals

**Comment by Tyriar** [comment]
Looks like this was reverted

**Comment by meganrogge** [comment]
was only reverted on @chrmarti 's branch
