### ISSUE TITLE
TASK RUN SHORTCUT

### ISSUE THREAD

**Issue by filip-attracs** [microsoft/vscode#132761]
Issue Type: <b>Bug</b>

Task run shortcut (Ctrl + Shift + B) is not using the default selected terminal.

This happened after updating vscode to 1.6!

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.54GB free)|
|Process Argv|--crash-reporter-id f74eca33-7ff0-4335-a486-923e87101753|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
es6-string-css|bas|0.1.0
prettier-vscode|esb|8.1.0
go|gol|0.27.2
lit-plugin|run|1.2.1
literally-html|web|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by filip-attracs** [comment]
I am trying to use Bash which is default selected but when i try to run tasks with shortcut it runs them in powershell.

**Comment by filip-attracs** [comment]
Also the default selected terminal is not saving. As soon as i restart VSCode the default goes back to powershell.

**Comment by alexr00** [comment]
> the default selected terminal.

Can you share where you set the default terminal?
