### ISSUE TITLE
VSCode hard freezes Linux system

### ISSUE THREAD

**Issue by mjiangsjtu** [microsoft/vscode#132735]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.2; 1.60
- OS Version: Ubuntu 21.04 (Pop OS 21.04)

Steps to Reproduce:

1. Open VSCode in Linux after fresh install
2. Switch to plugin tab
3. After a few seconds OS hard freezes (even the curses cannot move, so no way to find out what went wrong)

First I thought it was hardware/OS compatibility problem. Then the problem occurs on two different laptop computers, one with Intel CPU+NVidia graphics (Pop OS 21.04 Nvidia), one with AMD CPU and graphics (Pop OS 21.04 Intel/AMD).

This also does not happen with any other programs, even other Electron ones. Only when openning VSCode and switching to plugin tabs.

**Comment by deepak1556** [comment]
Can you attach the output of `code --verbose`
