### ISSUE TITLE
Extensions Status: The number after the icon does not help me at all

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1327]
I see the number 1 after the icon but what does it mean? At least tell me "1 Warning".

**Comment by isidorn** [comment]
Icon should be more intuitive to reflect that it is a broken extension. Icon + number + warning is too wide imho.
Forwarding this to @bgashler1 to get opinion

**Comment by bpasero** [comment]
Well since we do not show this when everything is ok, it would actually draw some attention to it. Currently I would never think about clicking there.

**Comment by isidorn** [comment]
Makes sense. Though 7 warnings & errors is really long. Should I just say 7 messages?

**Comment by egamma** [comment]
Suggest to be more specific, e.g. 7 issues

**Comment by isidorn** [comment]
issues works for me
