### ISSUE TITLE
Lagging on typing

### ISSUE THREAD

**Issue by LucasTeixeira793** [microsoft/vscode#132780]
Issue Type: <b>Performance Issue</b>

I got this problem very recently, almost everything on the app is very slow, every time I try to code, everything I type appears on the screen about 20 seconds. And I realized that the emmet abbreviation only works sometimes.
I thought it might be some extension I intalled or something like this, but not, I uninstalled and installed VsCode like 4 times and the problem is still here

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.85GB free)|
|Process Argv|--crash-reporter-id 17e67dd2-d36a-42f8-b307-968b0ffab174|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    82	 10144	code main
    0	   169	  6224	   window (dashboard.html - 1CCO-2021-2-Grupo-06 - Visual Studio Code)
    0	   130	 14772	     extensionHost
    0	   113	 13936	       "C:\Users\LENOVO T480\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\LENOVO T480\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=14772
    0	     2	 16588	       "C:\Program Files\Git\cmd\git.exe" show --textconv HEAD:site-estatico/public/teste.html
    0	    66	 21484	       electron_node serverMain.js 
    0	    14	 28092	     watcherService 
    0	    11	 10048	       console-window-host (Windows internal process)
    0	    38	 16664	   utility
    0	    77	 19004	   window (Relator de Problemas)
    1	   120	 24496	   gpu-process
    0	    24	 29976	   crashpad-handler
    0	    89	 31412	   shared-process
    0	    66	 21832	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dashboard.html - 1CCO-2021-2-Grupo-06 - Visual Studio Code)
|    Folder (1CCO-2021-2-Grupo-06): 55 files
|      File types: js(8) png(6) html(5) xlsx(2) sql(2) json(2) css(2) jpg(2)
|                  gitignore(1) mwb(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
vscode-language-pack-pt-BR|MS-|1.60.3
color-highlight|nau|2.4.0
material-icon-theme|PKi|4.10.0
open-in-browser|tec|2.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30364559
pythonf5test824:30361777
javagetstartedc:30351792
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604

```

</details>

**Comment by deepak1556** [comment]
Please attach the performance profile following the below steps

* Open devtools for window (From the command palette)
* Choose Performance tab in the devtools
* Hit the reload and record button
* Perform the steps to slowdown
* Stop recording
* Attach the generated trace
