### ISSUE TITLE
Sourcemaps no longer work in 1.60.0 when debugging mocha in ts-node

### ISSUE THREAD

**Issue by tbuschto** [microsoft/vscode#132742]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

- VS Code Version: 1.60.0
- OS Version: Kubuntu 20.04, Windows 10 21H1

Steps to Reproduce:

1. Clone https://github.com/tbuschto/vsc-debugger-bug
2. `npm i`
2. open in VSC Version 1.60.0
3. Set a breakpoint, e.g. in test/App.test.ts
4. Debug with launch configuration "Mocha"

Result in 1.60.0:
![image](https://user-images.githubusercontent.com/527303/132673107-8dedd3be-393d-4b82-8a84-79b2dd60748d.png)

Result in 1.59.0 (same project folder on same machine):

![image](https://user-images.githubusercontent.com/527303/132673633-bf1c506f-e1df-4e93-b358-0a5748b46d76.png)

My launch config:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "args": [
        "--require",
        "ts-node/register",
        "${workspaceFolder}/test/*.test.*"
      ]
    }
  ]
}
```

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/1100
