### ISSUE TITLE
code indention doesn't work somtimes

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vscode#13278]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Pro Version 1607 OS Build: 14393.222

Steps to Reproduce:

1. Code indention doesn't work sometimes, e.g., `<span>` as shown in the snapshot
![1](https://cloud.githubusercontent.com/assets/16834561/19141775/e33ff36a-8bb5-11e6-8be4-9cd6623f3578.png)

**Comment by ranjan-ranjan** [comment]
Also, another issue:

I have word wrap turned off. When i do `Alt+Shift+F`, the whole text is wrapped. It shouldn't be this way. this is behavior when word wrap is turned on.

**Comment by Tyriar** [comment]
@ranjan-ranjan to confirm, you're running a formatter when this occurs right?

Please file another issue with info and a screenshot if you have found another bug.

**Comment by ranjan-ranjan** [comment]
no formatter running. no extensions installed. kindly ask for more information if needed.

**Comment by ranjan-ranjan** [comment]
Also, another issue while running the sample given in https://www.tutorialspoint.com/angularjs/angularjs_custom_directives.htm. The only thing I have changed is deleted the white space before `mainApp.directive('student', function() {`
This is the result:

Snapshot1:
![1](https://cloud.githubusercontent.com/assets/16834561/19180031/411377da-8c80-11e6-9b4d-28d11d1273c8.png)

Snapshot2:
![2](https://cloud.githubusercontent.com/assets/16834561/19180036/46d1c6ea-8c80-11e6-8255-a0667cf7853b.png)

**Comment by ranjan-ranjan** [comment]
Another instance where it doesn't work:
![1](https://cloud.githubusercontent.com/assets/16834561/19181637/1389b94e-8c8c-11e6-9ced-81002b25a479.png)

**Comment by aeschli** [comment]
It is unclear to me how you got to the shown code and how the wrong indentation has occurred.
Can you give steps on how to reproduce? Best with a smaller code example.

**Comment by ranjan-ranjan** [comment]
Kindly note that the above snapshots are of html file with JavaScript embedded in it. So anything in `<script> ... </script>` won't be indented properly (which is my conclusion). The JavaScript would be indented properly only if it is in different .js file.

The code to reproduce above issue is:

```
<html>

<body>

	<div ng-app="mainApp" ng-controller="doctorController">
		<form name="doctorRegistrationForm" novalidate>
			<label>
                        namea
                            </label>
		</form>
	</div>
</body>

</html>
```

**Comment by aeschli** [comment]
Yes, that's expected. Our html formatter does not format inside script tags. That is #12972

**Comment by ranjan-ranjan** [comment]
the `</label>` should come just on the same level as `<label>`

**Comment by ranjan-ranjan** [comment]
Also, in this case the html doesn't gets formatted correctly. When we click on the codepen link marked in the snapshot and save it to html file. The html code doesn't gets formatted correctly.
![1](https://cloud.githubusercontent.com/assets/16834561/19514780/80c2a018-9612-11e6-87c7-409369aef5f3.png)
