### ISSUE TITLE
Dirty file marker (the dot) no longer appers when a file is modified but not saved.

### ISSUE THREAD

**Issue by vtcifer** [microsoft/vscode#132705]
Issue Type: <b>Bug</b>

Steps to reproduce
1\ Open a file.
2\ Make modifications to the file.
3\ No dot next to the name in the file tab appears, even though the contents in the editor do not match what is on disk anymore.

The indicator still seems to show up with a NEW file up until the moment you save it.
1\ Create a NEW file.
2\ Make modifications to the empty file.
3\ The dot next to the "Untitled-#" appears.
4\ Save the file (dot dissappears).
5\ Make modifications to the file.
6\ No dot next to the name in the file tab appears, even though the contents in the editor do not match what is on disk anymore.

Tested with all extensions disabled, same behavior. 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.40GB (6.51GB free)|
|Process Argv|--crash-reporter-id caccde11-90e1-4296-a460-47e5f8371143|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|6.0.1
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
remote-wsl|ms-|0.58.2
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
code-spell-checker|str|2.0.4
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by bpasero** [comment]
Auto save enabled?

**Comment by vtcifer** [comment]
> Auto save enabled?

Thanks, that does appear to be the case, not sure how it got turned on.
