### ISSUE TITLE
by default opens the  files in insert mode

### ISSUE THREAD

**Issue by logi-seesamjagan** [microsoft/vscode#132721]
Issue Type: <b>Bug</b>

just open any file in mac machine it opens the file in insert mode.
when i press "escape" key it goes to insert mode.
when i press "cmd+C"  it goes to insert mode.

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|36, 10, 5|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id a5c27f5a-69b7-40c1-b953-2f1010d49533|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
electron-snippets|ant|1.0.3
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.23
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|8.1.0
vscode-todo-plus|fab|4.18.4
gc-excelviewer|Gra|3.0.44
vscode-env|Iro|0.1.0
vscode-json5|mrm|1.0.0
debugger-for-chrome|msj|4.13.0
emoji|Per|1.0.1
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.6.0
open-in-browser|tec|2.0.0
vsfire|tob|1.4.1
vim|vsc|1.21.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by lramos15** [comment]
This sounds like an issue with the vim extension. Please open the issue there https://github.com/VSCodeVim/Vim
