### ISSUE TITLE
Should we hide the terminal cwd in tab description on Windows?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#132797]
Right now cwd is just the initial directory on Windows, this could be useful in multi-root repos but could confuse and just cause noise in single root repos. The actual solution to this needs some thinking.

**Comment by meganrogge** [comment]
`cwdFolder` 

create capibilities object returning when process gets created, would return !isWindows 
if cwdDetection is false, don't fill in
add note to settings that this won't work for Windows
add workspace folder variable so ppl on windows using multi-root could use that

**Comment by meganrogge** [comment]
if it's a multi-root workspace, show them all (mention in setting)
