### ISSUE TITLE
terminal defaulting to PowerShell

### ISSUE THREAD

**Issue by hoogesh** [microsoft/vscode#132711]
Hi,
I've setup GitBash to be the default terminal, but every time I launched VSCode, it defaults to PowerShell. Then when I closed an re-opens the terminal it goes back to GitBash.
`
  "terminal.integrated.profiles.windows": {
    "Git Bash": {
      "path": ["C:\\Program Files\\Git\\bin\\bash.exe"],
      "source": "Git Bash",
      "icon": "terminal-bash"
    },
  },
  "terminal.integrated.defaultProfile.windows": "Git Bash",
`

**Comment by ILunie** [comment]
same behavior  https://github.com/microsoft/vscode/issues/132713

**Comment by albertosantini** [comment]
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery  release.

**Comment by CodeCrazy-ywt** [comment]
I wonder if it's hardcoded to PowerShell.

**Comment by hoogesh** [comment]
Thanks waiting for the release.
