### ISSUE TITLE
SuggestModel: editor model can change between request for `provideSuggestionItems` and results

### ISSUE THREAD

**Issue by atscott** [microsoft/vscode#132785]
Does this issue occur when all extensions are disabled?: No (At least, it's much harder to reproduce because there aren't enough extensions participating in autocompletion to cause an issue with the async resolution timing)

- VS Code Version: 1.60.0
- OS Version: MacOS 11.5.1

Steps to Reproduce:

1.
Apply this patch to the vscode source to get a `debugger` breakpoint when the problem occurs:
```
diff --git a/src/vs/editor/contrib/suggest/suggestModel.ts b/src/vs/editor/contrib/suggest/suggestModel.ts
index 747f78a4b4c..5ffbd091a7a 100644
--- a/src/vs/editor/contrib/suggest/suggestModel.ts
+++ b/src/vs/editor/contrib/suggest/suggestModel.ts
@@ -116,6 +116,7 @@ export class SuggestModel implements IDisposable {
        readonly onDidCancel: Event<ICancelEvent> = this._onDidCancel.event;
        readonly onDidTrigger: Event<ITriggerEvent> = this._onDidTrigger.event;
        readonly onDidSuggest: Event<ISuggestEvent> = this._onDidSuggest.event;
+       wordAtPosition?: string;
 
        constructor(
                private readonly _editor: ICodeEditor,
@@ -431,6 +432,7 @@ export class SuggestModel implements IDisposable {
                const itemKindFilter = SuggestModel._createItemKindFilter(this._editor);
                const wordDistance = WordDistance.create(this._editorWorkerService, this._editor);
 
+               this.wordAtPosition = this._editor.getModel().getWordAtPosition(this._editor.getPosition())?.word;
                const completions = provideSuggestionItems(
                        model,
                        this._editor.getPosition(),
@@ -446,6 +448,10 @@ export class SuggestModel implements IDisposable {
                        if (!this._editor.hasModel()) {
                                return;
                        }
+                       const word = this._editor.getModel().getWordAtPosition(this._editor.getPosition())?.word;
+                       if (this.wordAtPosition !== word) {
+                               debugger;
+                       }
 
                        let clipboardText = existing?.clipboardText;
                        if (!clipboardText && completions.needsClipboard) {
```
i.e. save the word at position right before `provideSuggestionItems` and then put a debugger statement in the `Promise.all` if it is different.

2. Enable a few extensions that are completion providers for the document type. I've been using an HTML with built in "HTML Language Features" and "Angular Language Service" extension
3. Starting at a location that would trigger a new completion model (i.e., not on an exiting word), type two letters _very quickly_. 
4. If done quickly enough (or the completion providers have the right amount of delay), this will trigger the breakpoint. The result here is that if the `editor.suggest.insertMode` is `replace`, the replacement will be incorrectly computed because the completion results were retrieved when the document had different text. This means the replacement will delete more characters than it should.

This was found when investigating a bug report for our language service extension (https://github.com/angular/vscode-ng-language-service/issues/1503)

**Comment by jrieken** [comment]
>  editor model can change between request for provideSuggestionItems and results

That's expected - we cannot stop the world and prevent typing when asking for completions. On the renderer we keep track of the position at which completion has been requested and later [add such](https://github.com/microsoft/vscode/blob/0adbf29ccb2aaa401fc8a2d3f53697e6be40411b/src/vs/editor/contrib/suggest/suggestController.ts#L425) deltas to the completions. For completion providers it is vital to compute the range that it wants to replace/insert synchronously e.g. before invoking an async computation

**Comment by atscott** [comment]
Hi @jrieken, thanks for the quick response. I suspected there was logic somewhere that did that adjustment.
 Sorry for not being clear in the report, but the problematic suggestions were coming from VSCode’s `editor.suggest.show words`, not from another extension so I believe the issue is still with something in VSCode. 
 Do you have a pointer to where those replacement ranges are computed? I can spend a bit more time debugging where the problem happens - I’m just unfamiliar with the codebase so it’s a bit difficult to do.
