### ISSUE TITLE
Black border intermittently appearing at bottom of tree view

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#132756]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

In the process of dragging the vscode project explorer tab under the Light theme style, a black border sometimes appears, which is very annoying. May I ask what caused this, hope to fix it quickly, it is really frustrating. . . . Hope to fix it quickly. . .
Please see the attachment for specific performance as follows:

https://user-images.githubusercontent.com/54253524/132697041-efbb0ce2-8015-48af-9d1f-5429ddf6fce6.mp4

VS Code version: Code - Insiders 1.60.0-insider (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:40:58.134Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

https://user-images.githubusercontent.com/54253524/132696691-4f275770-4ac2-4740-8662-69216dce9de3.mp4

**Comment by zhouxinghong** [comment]
https://user-images.githubusercontent.com/54253524/132705031-4c6fb974-64ce-441f-a49b-e82dbec8dccd.mp4

**Comment by zhouxinghong** [comment]
This bug also exists in the default Dark theme style, which is very distracting. . .
https://user-images.githubusercontent.com/54253524/132788223-7ce9bdb1-fa60-4ff5-b496-c003fe2483eb.mp4

https://user-images.githubusercontent.com/54253524/132788523-ea3c462d-0ca5-49fd-8fa2-4c9ec9158159.mp4

**Comment by joaomoreno** [comment]
Can you reproduce with zoom level 0?

**Comment by zhouxinghong** [comment]
"window.zoomLevel": 2,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Visual Studio Dark",

**Comment by zhouxinghong** [comment]
The previous zoom level was: 2
The following demo is the zoom level I set to reproduce the bugs, for example: set the zoom level to 1, please see the specific demo as follows:
    "window.zoomLevel": 1,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Default Light+",
https://user-images.githubusercontent.com/54253524/132937723-f4df6b65-2c64-4b9d-beab-e2db1c2af001.mp4

**Comment by zhouxinghong** [comment]
https://user-images.githubusercontent.com/54253524/132937800-a132fde1-6e77-471e-b939-0d3a501a807c.mp4

**Comment by zhouxinghong** [comment]
Hello! Can this problem be fixed?

**Comment by joaomoreno** [comment]
Can you reproduce with zoom level 0?

**Comment by zhouxinghong** [comment]
> What's your current zoom level? Can you reproduce with zoom level 0?
This problem is very serious in version 1.60.2, which completely affects the consistent experience and distraction of the UI. Will you fix it? ? ?

**Comment by zhouxinghong** [comment]
> Can you reproduce with zoom level 0?

"window.zoomLevel": 2,
"workbench.iconTheme": "material-icon-theme",
"workbench.colorTheme": "Visual Studio Dark",

The previous zoom level was: 2
The following demo is the zoom level I set to reproduce the bugs, for example: set the zoom level to 1, please see the specific demo as follows:
"window.zoomLevel": 1,
"workbench.iconTheme": "material-icon-theme",
"workbench.colorTheme": "Default Light+",
https://user-images.githubusercontent.com/54253524/132937723-f4df6b65-2c64-4b9d-beab-e2db1c2af001.mp4

https://user-images.githubusercontent.com/54253524/135702256-929fe76e-cf2b-466c-9a1d-4be46560471b.mp4

**Comment by zhouxinghong** [comment]
> Can you reproduce with zoom level 0?

Hello, teacher!
If you confirm my needs, please reply, thank you very much!

**Comment by zhouxinghong** [comment]
> What's your current zoom level? Can you reproduce with zoom level 0?

Hello, teacher!
If you confirm my needs, please reply, thank you very much!

**Comment by zhouxinghong** [comment]
> Can you reproduce with zoom level 0?

Hello, teacher! 
      excuse me! Could this problem be fixed by the next milestone? Looking forward to your fix in the next milestone, thank you very much!

**Comment by zhouxinghong** [comment]
Hello, teacher! 
      excuse me! Could this problem be fixed by the next milestone? Looking forward to your fix in the next milestone, thank you very much!

**Comment by zhouxinghong** [comment]
https://user-images.githubusercontent.com/54253524/142089635-a2428efe-7366-4e07-976a-798a10959545.mp4

**Comment by zhouxinghong** [comment]
> Can you reproduce with zoom level 0?

Hello, teacher!
VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
vscode contributors
20220126

**Comment by zhouxinghong** [comment]
Hello, teacher!
VSCode is a great project that gives users the greatest autonomy from the very beginning, allowing users to personalize configurations according to their own habits, so it can fully surpass the long-born jetbrion series in just 5 years. The most important reason is that VSCode's open source thinking and allowing users to customize and configure VSCode development methods to the greatest extent can achieve today's achievements. I hope VSCode can continue to develop this way of thinking and development, focusing on every reasonable request of users and need. Thank you here!
vscode contributors
20220126

**Comment by zhouxinghong** [comment]
![2022-01-27_201532](https://user-images.githubusercontent.com/54253524/151361118-4c1e8ad4-7529-4619-8133-ced1c55fccbf.png)

**Comment by zhouxinghong** [comment]
![Uploading 2022-01-27_223915.png…]()

**Comment by zhouxinghong** [comment]
![2022-01-27_223915](https://user-images.githubusercontent.com/54253524/151381669-b625c77b-26ac-41d4-9ea7-5c99bf24e072.png)
White lines appear on text selected with the mouse

**Comment by zhouxinghong** [comment]
![2022-02-18_224923_黑色线条](https://user-images.githubusercontent.com/54253524/154708269-005c9974-ef6c-46af-94df-8a0f7d00afda.png)

**Comment by zhouxinghong** [comment]
![2022-02-22_120625_黑色线条2](https://user-images.githubusercontent.com/54253524/155061491-109466ce-fef8-43f2-9441-1638823d59f2.png)
