### ISSUE TITLE
code will become same while switching two files

### ISSUE THREAD

**Issue by jojokaran72** [Microsoft/vscode#13277]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. open two js files
2. work on one file if you switch to other file and come back suddenly both files become same code 
3. This issue occurring multiple time try to fix this ASAP

**Comment by bpasero** [comment]
This has been fixed for 1.6.0

**Comment by jojokaran72** [comment]
Can you please share the link to download 1.6.o because on website i can only see till 1.5.3
