### ISSUE TITLE
Make the WSL profiles less prominent

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#132754]
When in a local window and opening the profile dropdown, I now see a lot of WSL terminals.

https://user-images.githubusercontent.com/6461412/132689318-eaa0ec72-e741-419c-8fb4-dd885d2ffe39.png

We should advertise a WSL window instead.

**Comment by runxel** [comment]
> We should advertise a WSL window instead.

So the user has then to decide again???
Not really an improvement, I think.
