### ISSUE TITLE
[Bug|Feat?] Regexp end of string lacking or not working

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#13270]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

**Steps to Reproduce:**

1. Open new file and write anything, ex. "presentation proportions".
2. Use normal search (ctrl + f) or folder search with regexp `ion$` and enter to start the search.

**Expected behavior:**

Find `presentation` word but not `proportions`.

**Current behavior:**

Doesn't find any words.

**Comment by Tyriar** [comment]
`ion$` would not match `"presentation proportions"` as `$` matches the end of the *line*, not the end of a *word*. `ion[^s]` will match what you want.

![image](https://cloud.githubusercontent.com/assets/2193314/19133974/feff5ad8-8b0f-11e6-84e0-b11dbe6fad4b.png)

**Comment by Luchillo** [comment]
So maybe i'm using the rules of JS for regexp match in VSCode, which are the rules or where are defined for VSCode? i tough since VSCode is made with Electron it would use the JS regexp rules.

**Comment by Luchillo** [comment]
Ok i'm reading again and testing in https://regex101.com/ and it is true, i'm formulating a bad regexp, seems like the one i'm searching for is `ion\b`
