### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by Sakib714** [microsoft/vscode#132758]
Issue Type: <b>Performance Issue</b>

My VS code settings.json file shows some problem...and I don't modify anything___

How can a restore or reset my code in the settings.json file??

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.04GB free)|
|Process Argv|--crash-reporter-id 97e9e590-cf35-48b0-a18e-9437f5f263da|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    57	  8488	code main
    0	   139	  1208	   window (Settings - Untitled (Workspace) - Visual Studio Code)
    0	     8	  1160	     watcherService 
    0	     1	   956	       console-window-host (Windows internal process)
    3	    68	  6544	     extensionHost
    0	   122	  2124	       "C:\Program Files\Kite\kited.exe" --plugin-launch --channel=autocomplete-python
    0	    44	  6984	       "C:\Users\N.S Computer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\N.S Computer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6544
    0	    14	  7944	       electron_node bundle.js 
    0	     2	  8672	     searchService
    0	     3	  4276	   crashpad-handler
    0	    12	  5012	   utility
    3	    43	  7784	   shared-process
    0	     5	  1868	     ptyHost
    0	    78	 10120	   window (Issue Reporter)
    1	    75	 10596	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - Untitled (Workspace) - Visual Studio Code)
|    Folder (Desktop): 1879 files
|      File types: qml(715) png(227) qmlc(170) dll(132) pak(57) qmltypes(54)
|                  py(46) xml(44) qm(39) pyd(27)
|      Conf files:;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.3
code-runner|for|0.11.5
vscode-test-explorer|hbe|2.21.1
kite|kit|0.147.0
vscode-python-test-adapter|lit|0.7.0
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
test-adapter-converter|ms-|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824:30361777
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by roblourens** [comment]
What are the problems? Extensions can modify it sometimes.

**Comment by Sakib714** [comment]
Actually, it was some syntax error.

I have reset that file..

**Comment by roblourens** [comment]
So you have resolved the issue?
