### ISSUE TITLE
vscode v1.5.3 make root partition remounted read-olny

### ISSUE THREAD

**Issue by Rooomaaa** [Microsoft/vscode#13272]
- VSCode Version: 1.5.3
- OS Version: Calculate Linux ( cldm stable ) 

Steps to Reproduce:

1. calculate guest # uname -a
Linux calculate 4.4.23-calculate #1 SMP PREEMPT Sun Oct 2 09:28:10 UTC 2016 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux

2. run vscode (v1.5.3)

I also run it inside gdb (separate run):
guest@calculate ~ $ gdb /opt/VSCode-linux-x64/code 
GNU gdb (Gentoo 7.10.1 vanilla) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/VSCode-linux-x64/code...(no debugging symbols found)...done.
(gdb) run
Starting program: /opt/VSCode-linux-x64/code 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff4da2700 (LWP 4410)]
[New Thread 0x7ffff3b45700 (LWP 4412)]
[New Thread 0x7ffff3344700 (LWP 4413)]
[New Thread 0x7ffff21ab700 (LWP 4416)]
[New Thread 0x7ffff19aa700 (LWP 4417)]
[New Thread 0x7ffff19a2700 (LWP 4418)]
[New Thread 0x7ffff11a1700 (LWP 4419)]
[New Thread 0x7ffff09a0700 (LWP 4420)]
[New Thread 0x7ffff019f700 (LWP 4421)]
[New Thread 0x7fffef99e700 (LWP 4422)]
[New Thread 0x7fffef19d700 (LWP 4423)]
[New Thread 0x7fffee99c700 (LWP 4424)]
[New Thread 0x7fffee19b700 (LWP 4425)]
[New Thread 0x7fffed99a700 (LWP 4426)]
[New Thread 0x7fffed199700 (LWP 4427)]
[New Thread 0x7fffeb2f4700 (LWP 4428)]
[New Thread 0x7fffeaaf3700 (LWP 4429)]
pci id for fd 14: 80ee:beef, driver (null)
[New Thread 0x7fffe22f0700 (LWP 4434)]
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
[New Thread 0x7fffe1079700 (LWP 4440)]
[New Thread 0x7fffe066b700 (LWP 4441)]
[New Thread 0x7fffdfe6a700 (LWP 4442)]
[New Thread 0x7fffdf669700 (LWP 4443)]
[New Thread 0x7fffdee68700 (LWP 4444)]
[New Thread 0x7fffde667700 (LWP 4445)]
[New Thread 0x7fffdde66700 (LWP 4446)]
[New Thread 0x7fffdd665700 (LWP 4447)]
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

**Comment by Tyriar** [comment]
Can you elaborate a little on what the issue is?

**Comment by Rooomaaa** [comment]
Hi, it is related to SCSI controller + host cpu clock non-synchronization, and NOT related to VSCODE. 
sorry. thnx for closing .... 

Running vscode catch the scsi-realted-error since big amount of read-write io.

**Comment by Rooomaaa** [comment]
If it can be useful for anybody: 
Problem: ( for me it is vbox with gentoo, 4.4.23 kernel on scsi LSI-logic & host io enabled & VSCode v1.5.3 - after few minutes of usage root fs remounted read-only  ) 
1. https://www.virtualbox.org/ticket/10031

Yes, VirtualBox does normal user land read/writes. But most of normal user land applications are not too sensitive to read/write operation timing while guest kernel running in VirtualBox is. Therefore if write operation in the host takes too long (what can happen if host flushes too much dirty pages to disk) then guest kernel may consider it as SATA timeout and trigger error handling procedure. There are several ways to overcome this issue: 1). Configure virtualbox to bypass host cache (use direct I/O). This may cause issues with ext4 in some kernel versions (like in Ubuntu 10.04) and also may not be enough if host itself performs heavy write operations. 2). Use "raw" VMDK on top of LVM partitions to store VM disks rather than files on file system (this also avoids double file system overhead). 3). Configure host kernel to flush buffer cache more frequently to not create heavy write batches. 4). Use periodic flush in VirtualBox to limit amount of data in host buffer cache...... 

Solution: 
2. http://unix.stackexchange.com/questions/174400/can-the-hard-drive-timeout-be-disabled-in-linux-attempting-task-abort
