### ISSUE TITLE
The keyboard focus shifts to the "968,137" non-interactive control.

### ISSUE THREAD

**Issue by 12-shweta** [microsoft/vscode#132744]
“[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yMAS;#A11yTCS;#VisualStudioCode-Win32-Apr2021;#Visual Studio Code Client;#A11ySev3;#WCAG2.1.1;#DesktopApp;#Win10;#Keyboard;

### Environment Details:
Visual Studio Code
Azure Function
Operating System: Windows 10 Pro 21H1

### Steps to Reproduce:

1. Launch the Visual studio code.
2. TAB to on "Extension" button and search for "Azure Functions" and select it using ENTER key.
3. TAB to "Microsoft" control.
4. Observe that with next TAB key, keyboard focus shifts to the "968,137" non-interactive control.

### Actual:
The keyboard focus shifts to the "968,137" non-interactive control while navigating using TAB key.

### Expected:
The keyboard focus should not shifts to the "968,137" non-interactive control while navigating using TAB key.

### User Impact:
The keyboard users will get confused while navigating using TAB key and will think this is interactive control.

![image](https://user-images.githubusercontent.com/54656883/132679982-1dc48063-0455-4aa9-8ab6-cc0582116d0a.png)

**Comment by isidorn** [comment]
Disagree. This is a way how users discover how many install are there. The focus should land on it.
Closing as designed.
