### ISSUE TITLE
Bracket pair colorization bug when pasting comments

### ISSUE THREAD

**Issue by ClintWinter** [microsoft/vscode#132755]
Issue Type: <b>Bug</b>

When pasting comments that have parentheses, they are highlighted by the new setting `"editor.bracketPairColorization.enabled": true`.

When typing out the comment, this is not the case.

E.g.:

```javascript
// This is my comment (a great comment).
```

If the closing parenthesis is left off and pasted, it will affect the colors of the parentheses in the code following the opening one in the comment.

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by IllusionMH** [comment]
Looks like related to or duplicate of #132249
Is it reproducible for you in Insiders build? https://code.visualstudio.com/insiders/

/assign hediet

**Comment by Whobeu** [comment]
> Looks like related to or duplicate of #132249
> Is it reproducible for you in Insiders build? https://code.visualstudio.com/insiders/
> 
> /assign hediet

From what I am experiencing, #132249 describes the problem.

**Comment by hediet** [comment]
Can you verify that the insiders build fixes the problem you are experiencing?
