### ISSUE TITLE
"File" participants running minutes

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode#132726]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.6.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1 Connect to a remote machine using the Kubernetes extension: attach visual studio code to a running pod. I am using the Kubernetes extension version v1.3.3
2. Delete a file in the file explorer or Copy a file using the file explorer

After the operation above, a dialog is shown with "running ... participant":
- in the case of folder deletion, the dialog disappeared after a couple of minutes
- in the case of file copy, it has never disappeared, even if the file was actually copied.

**Comment by JacksonKearl** [comment]
It would help us if you could identify which save participants are running. I suspect it would be participants contributed by the Kubernetes extension, in which case you should file an issue on that repo. To verify this, you could disable all extension except the Kubernetes one, and see if the issue reproduces.

**Comment by thistlillo** [comment]
The "participants" dialog appears also when working locally. In this latter case, it stays open for a shorter time.

I have never seen this dialog before upgrading VSC to v1.6

**Comment by JacksonKearl** [comment]
The save participants are contributed by extensions. You can try an [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to see what extension is causing the long save delay.
