### ISSUE TITLE
VS Code isn't outputting the output of the pre-push git hook script

### ISSUE THREAD

**Issue by bencresty** [microsoft/vscode#132778]
Vs Code isn't outputting the output of the pre-push git hook script script nor the output of any triggered batch-files (*.bat) triggerd by it.

I initially thought this was an issue in Git for Windows, so started an issue message over there (https://github.com/git-for-windows/git/issues/3419), but it works when using git push in a commandline and when searching on google more people were having the exact same issue with the `pre-push` hook not outputting in VS Code's output panel.

An example of other people having this issue with `pre-push`:
https://developercommunity.visualstudio.com/t/git-integration-does-not-show-local-hooks-output/153462

According to this thread (https://github.com/microsoft/vscode/issues/59787) it would've be fixed in VS Code years ago, but it doesn't work in the latest VS Code. 

Some other hooks DO output its output to VS Codes git panel though. The hooks `pre-commit`, `prepare-commit` and `commit-msg` perfectly show their output in the output panel and also a batch-file (*.bat) which was triggered by the `commit-msg` hook here has its output shown in the VS Code git output panel.

So I would expect the `pre-push` output to be shown there as well, the same with the batch-file triggered from there.

---

- VS Code Version: 1.60.0
- OS Version: Windows 10

---

Steps to Reproduce:

1. Create a `pre-push` script inside .git/hooks which echos a string and triggers a batch file

``` bash
#!/bin/sh

echo '----------------- PRE PUSH ------------------'

cmd.exe /c "test.bat"

exit 0
```

2. Create a `test.bat` batch script inside the project folder which echos a string and creates a folder

``` text
@echo --------------- BATCH FILE EXECUTING ----------------

mkdir test-created-by-push
```

1. Commit the batch file to git
2. Open the Output panel on Git
2. Use VS Code's build in git push
3. Look at the Output > Git panel and see there's no indication of the hook being fired; no echo from the hook and no echo from the batch file. The folder is created though, so the script was executed while pushing.

---

**Example of `pre-push` hook that does NOT show the output of the hook nor the output of the bat-file**
![push-hook-not-working-vs-code](https://user-images.githubusercontent.com/69322733/132753234-36696620-e85c-4d07-8773-d33193a5258d.png)

**Example of hooks that DO show the output of the hook as well as the output of the triggered batch-file (*.bat)**
![commit-vs-code-does-work](https://user-images.githubusercontent.com/69322733/132753048-f24d8b2c-e0bf-4446-acb9-34df09c1bbb2.png)

**Example of the `pre-push` to indicate it IS working from 'just a' commandline:**
![image](https://user-images.githubusercontent.com/69322733/132753585-1903f244-d71b-4018-a6e2-29f9dff94246.png)

**Comment by smasala** [comment]
Can confirm this when using `husky`

**Comment by paolocattani** [comment]
same problem for me using husky

**Comment by iJackUA** [comment]
Have the same issue, by using hooks via https://github.com/evilmartians/lefthook (but it just creates a regular Git hooks).

Also I am using VSCode remote container (git is running inside container, Debian based), host machine is also Debian based Linux. So it looks like not related to Windows.

**Comment by saiichihashimoto** [comment]
Is there something we can do to poke this or see its priority? I'm running into this as well and seeing nothing on it since September is discouraging.

**Comment by lszomoru** [comment]
The output of the git client-side hooks is being written to `stdout` and by default only `stderr` is being logged in the "Git output" channel. The Insiders release on Monday will have a new setting (`git.commandsToLog`) that one can use to specify an array of git commands that will have their `stdout` (including the output of the client-side hooks if there are any configured) logged to the "Git output" channel.

Try out the new setting and update the issue if you see any problems with it.

**Comment by bencresty** [comment]
@lszomoru Thanks! Great to 'hear' it's coming!

One question tho; you write only the `stderr` is currently being logged, as being the reason the hook is not outputed in vs code. But some of the hooks' outputs ARE shown in VS Code (see opening post).  How come these hooks ARE shown while not being errors?

**Comment by lszomoru** [comment]
@bencresty, that is a fair question. Looking at [the code](https://github.com/microsoft/vscode/blob/49ae1ecfb5f33af885acbc0f7f5f6c0ac8954f81/extensions/git/src/git.ts#L539), I am fairly confident that before my change, we have only logged the contents of `stderr`. So my only hypothesis at the moment is that somehow that content ends up in `stderr` and that is why it gets written into the Git output channel.

**Comment by lszomoru** [comment]
Steps to verify:
1. Create a new folder (ex: `hooks-test`) and run `git init` in the folder
2. Open `hooks-test\.git\hook` and create a new file called `pre-push`
3. Add the following to the file
    ```
    #!/bin/sh
    echo HELLO WORLD!
    ```
4. Open the `hooks-test` folder in VS Code Insiders
5. Open the Git output channel using the `Git: Show Git Output...` command
6. Make a file change, commit, and push the change
    - Confirm that you do not see "HELLO WORLD!" in the Git output channel
7. Open settings and find the `git.commandsToLog` setting. Add `push` to it.
8. Make a file change, commit, and push the change
    - Confirm that you see "HELLO WORLD!" in the Git output channel
