### ISSUE TITLE
My Typescript syntax color doesn't work for Angular 2

### ISSUE THREAD

**Issue by zh-wowtv** [Microsoft/vscode#13274]
- VSCode Version: 1.5.3
- OS Version: 10.11.6

<img width="534" alt="2016-10-06 11 10 49" src="https://cloud.githubusercontent.com/assets/18462946/19139270/bb96e79c-8bb5-11e6-9088-bece332a8b08.png">

**Comment by waderyan** [comment]
We've been working on this grammar extension - https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

Can you try it out and let me know if it solves your issue?

**Comment by zh-wowtv** [comment]
Here is the result:

<img width="805" alt="2016-10-08 9 34 40" src="https://cloud.githubusercontent.com/assets/18462946/19209316/8e84e2d2-8d3a-11e6-8e4d-5f81a83e9dc3.png">

<img width="528" alt="2016-10-08 9 34 47" src="https://cloud.githubusercontent.com/assets/18462946/19209317/90ad814a-8d3a-11e6-98c7-43983d4367d6.png">

**Comment by waderyan** [comment]
@zh-wowtv this looks good to me. Does this suffice for you? If not can you open an issue on the [grammar's repo](https://github.com/Microsoft/TypeScript-TmLanguage)?

**Comment by zh-wowtv** [comment]
Yes，thank you. @waderyan
