### ISSUE TITLE
single tab description should be styled to match others

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#132876]
![description](https://user-images.githubusercontent.com/29464607/132895802-cc1a151e-7cd8-4258-9194-df9dc554dac8.PNG)

IE smaller, dimmed text

**Comment by Tyriar** [comment]
This would be nice, I don't think there's a mechanism for it right now though.

**Comment by meganrogge** [comment]
couldn't we apply custom CSS that matches that of the descriptions in other places? or perhaps we shouldn't show the description for the single tab? it looks a little heavy to me

**Comment by meganrogge** [comment]
add a separator here and only show if not equal to initialCwd
