### ISSUE TITLE
Explore adding a second side bar

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#132893]
This issue contains the discussion around adding a second side bar. The secondary side bar would be the next step in improving layout flexibility.

A primary motivator of the second side bar is to address the scenarios expected in https://github.com/microsoft/vscode/issues/26777.

The current step is understanding the various UX options that could be used to solve the problem. Below are some notes from the current exploration.

* Side bar is a loose term here. We could introduce a second panel instead which already knows how to move to multiple orientations.
* Second may also be limiting. As many have pointed out, should we just allow N number of panels or side bars? Limiting the number does simplify things like keybinds and general layout management and adding too many comes at the cost of complexity that many users will find less useful.
* Currently the panel and side bar solve nearly the same purpose but the panel is drawn differently. Could we adapt the panel to turn into a side bar when it is on the left or right and then make more of them?
* If we go with a second side bar, is it necessary to have an activity bar?

Also adding some mockups from @misolori 

![image](https://user-images.githubusercontent.com/6561887/132918821-a9b4aff2-ac6f-4631-b803-2cd8284a4488.png)
![image](https://user-images.githubusercontent.com/6561887/132918843-a87f9775-e4dd-47ab-be5e-79732f708472.png)
![image](https://user-images.githubusercontent.com/6561887/132918864-0a58431a-2240-4026-839a-7569b09d54b4.png)
![image](https://user-images.githubusercontent.com/6561887/132918880-3bc66037-8fdc-4e65-9c4b-300616412988.png)

**Comment by sharedrory** [comment]
I would love this feature. I am working on a project which has a lot of files in the root directory so I cannot fold it like a folder. It takes nearly all the space to see all the files at once. I prefer not to scroll. I wanted to have a second sidebar where I could put the outline in the top half and the timeline (git) in the bottom.

> The secondary side bar would be the next step in improving layout flexibility.

Agreed. I imagine one day VSCode's layout would be as flexible as https://theia-ide.org/ ie. Drag and drop pretty much anything anywhere you like (it also has vertical tabs like the ones in the screenshots)

> Second may also be limiting. As many have pointed out, should we just allow N number of panels or side bars? Limiting the number does simplify things like keybinds and general layout management and adding too many comes at the cost of complexity that many users will find less useful.

Definitely something else to keep in mind too.

**Comment by DominicVonk** [comment]
Maybe make it possible to do vertical tabs or icons on both sidebars.

**Comment by paror** [comment]
Another possibilité : horizontal icons on the top of the second sidebar (not to waste space in a long vertical bar with some icons on top ...)

**Comment by misolori** [comment]
Here's another iteration that @sbatten and I worked on. This idea closely follows the sidebar appearance/styling but works just like the panel (with multiple panel titles and views):

<img width="1311" alt="CleanShot 2021-09-14 at 14 56 09@2x" src="https://user-images.githubusercontent.com/35271042/133339325-941b7a14-8511-4ef3-8b76-69060b2d5bd1.png">


So this means that the panel will still be able to be placed on the left/bottom/right and the secondary sidebar can take multiple views containers:

<img width="1327" alt="CleanShot 2021-09-14 at 14 55 56@2x" src="https://user-images.githubusercontent.com/35271042/133339304-cfb79187-b75a-4a04-9917-97b60ddcd387.png">

We also discussed toggling the secondary sidebar via keyboard shortcuts and via the "sash" drag & adding a single click to toggle this:

<img width="442" alt="CleanShot 2021-09-14 at 15 01 37@2x" src="https://user-images.githubusercontent.com/35271042/133339903-c4540913-8396-4d3c-8489-adfbebac13cf.png">

**Comment by DominicVonk** [comment]
Maybe make a setting, that everyone can pick their favorite. I would really like the activity bar because then I feel more organized.

**Comment by sbatten** [comment]
Adding some screenshots comparing a full length second side bar and editor length side bar
 
Full-Length
![image](https://user-images.githubusercontent.com/6561887/133508335-5b57b834-ca31-481a-a5f1-038420b55267.png)

Editor-Length
![image](https://user-images.githubusercontent.com/6561887/133508346-f1f5558c-6e17-40b2-b32c-ae658fadd9d3.png)

**Comment by wendellhu95** [comment]
Great to have this feature!

**Comment by heartacker** [comment]
@sbatten  Thanks 
and IMO, I want the new side bar like this,

![image](https://user-images.githubusercontent.com/1876302/133723059-59b06c22-2472-45f0-91ed-5db4521075e0.png)

exactly, I believe that floating panel is a good solution for user, like ^VS2019, the visual studio float panel is very useful and powerful, we could use for reference.

there is the float panel(FP) of vs2019, and some of those features are yummy

- when the FP is hide, there are titles standing by side.
- when click the of title of FP, the FP show, we can do something like navigation, but after lost the focus, the FP automatically hide in order to maximize the editor view
- we could also PIN those FP for persist view.
![AA](https://user-images.githubusercontent.com/1876302/125550737-d3de4a19-8146-4626-8cc7-56505007fbe6.gif)

**Comment by DominicVonk** [comment]
I would prefer Full-Length @sbatten

**Comment by mhanuszh** [comment]
> I would prefer Full-Length @sbatten

How about a setting for it?

**Comment by DominicVonk** [comment]
I have it enabled with the setting "workbench.experimental.sidePanel.enabled". And it already looks promising. But I would also like to move a complete group from the activitybar into the sidebar, and sidetabs please.

**Comment by Vjust** [comment]
It would be good to have the second explorer be a browser for other things.

-  ability to move the outline to the second bar.
- ability for extensions to use the second bar
- to be used for intellisense & find results & TODOs & bookmarks maybe

**Comment by gjsjohnmurray** [comment]
@Vjust you should be able to drag those things and drop them there.

**Comment by Vjust** [comment]
Thanks , I missed that obvious detail. Is this feature already in the insider-build

**Comment by gjsjohnmurray** [comment]
> Is this feature already in the insider-build

Yes.

**Comment by sbatten** [comment]
Moving to October as all exploration for September is complete.

**Comment by sharedrory** [comment]
> > Is this feature already in the insider-build
> 
> Yes.



> Moving to October as all exploration for September is complete.

Does this mean we can expect it to be in the October release or will we have to wait for a couple more months? Sorry if you count this as spam -- you may delete this.

**Comment by sbatten** [comment]
This is not ready for prime time in the October release and the next milestone is less focused on feature work. However, now that we have this going in insiders, the exploration will continue when feature work picks up again the following milestone.

**Comment by Igorgro** [comment]
Completely agree with previous comment. I think the best solution is to use second activity bar as it is shown in the original issue:
![2 activity bars](https://user-images.githubusercontent.com/6561887/132918821-a9b4aff2-ac6f-4631-b803-2cd8284a4488.png)

**Comment by McPan** [comment]
@iamwwc: it's grayed out in the json settings, but the feature still works.The new panel must then be activated via the main menu "View"-> "Appearance" -> "Show Side Panel".

@the rest of the participants: thanks an thumbs up!

**Comment by heartacker** [comment]
hi,@sbatten, could you please rotate the side panel title bar to vertical, and also, please show the title bar when side panel is hide so that user could easy to show side panel. 
PLEASE.  I believe that is better than now.
![image](https://user-images.githubusercontent.com/1876302/138619108-d072b222-c555-454d-8588-efdfb80dacfa.png)

**Comment by byehack** [comment]
@Jademalo 


> I do think it would be worthwhile having a setting available for the bar being either editor length or full length

drag and drop is better option see https://github.com/microsoft/vscode/issues/130131

> having a second Activity Bar on the right hand side instead of just the panel.

activity bar icons have not support for multi-tabbed containers yet.

**Comment by orta** [comment]
To add another example case, as an extension author I'd love to be able to open a new workspace _with_ the 2nd sidebar set up with a particular view container:

![Screen Shot 2021-11-08 at 3 18 30 PM](https://user-images.githubusercontent.com/49038/140768264-d39b65b2-52c8-4af3-ac66-980f7c4185d4.png)

**Comment by alefragnani** [comment]
Just played a bit in the Insiders release, and I can say I missed the **Second Activity Bar**. 

My muscle memory failed recognizing any of the Views using the the currently provided tabbed container. And in fact, the tabbed container (probably) won't work if you move a bunch of views there. The ellipsis button/tab, is one of the reasons I don't move the Panels (bottom panels) to the right.

Vertical Tabs, on the other hand, I'm sorry, really sorry, but I still don't understand how people use/like it 😄 . Yes, I'm able to read vertical text, but _why_ should I do it? In the end, it's useless and I simply ignore its existence. Again, sorry for those that prefer this UX. This is probably the same tabs vs space / light vs dark theme fight wee see today...

My vote: **2 Activity Bars**

Thank you

**Comment by iamwwc** [comment]
Are this feature still be update? I don't see any of codes updates recently.

When the feature will be ship in the stable?

**Comment by mohmedaref1** [comment]
Please add this

**Comment by gjsjohnmurray** [comment]
> When the feature will be ship in the stable?

Already in Stable (currently 1.62.3), after adding `"workbench.experimental.sidePanel.enabled": true` to your user settings.json and restarting VSCode, the "Show Side Panel" is available in the View\Appearance submenu.

**Comment by clytras** [comment]
Can we move it to the left side right next to the explorer?

This is a super cool and long waited feature and please consider making the 'side' of the side panel configurable (right or left). I have an ultra wide monitor and I split to multiple panel columns views and with the side bar on the right side, I need much more mouse traveling each time I want to navigate using the outline, but if I can move the sidebar panel at the left side, right next of the main explorer, it would be super productive on ultra wide screens.

**Comment by abflow** [comment]
@ clytras, as there are at least as many layout configurations as there are VS Code users, and considering the thousands of extensions with their own view containers and activities in the marketplace, I think we would also need a way to store, retrieve and sync multiple layouts settings, with all the different locations of sidebars, panels, items, etc. (#138263)

Presently, VSCode design feels constrained and not enough flexible. Consequently, it is indeed more designed for notebooks than for ultra-wide monitors with lots of space for complex layout configurations.

In all professional softwares that I have personally used (not just for coding), the layouts were customizable and switchable, which is much more productive.

**Comment by rejhgadellaa** [comment]
Thanks for the great work here.

Just wondering if a keyboard shortcut is on the roadmap? It is mentioned in this ticket but only once.

**Comment by alefragnani** [comment]
Just noticed the current builds changed how the selected **Tabbed Container** UI works. It is only displaying the `Icon`, not the `Label` anymore.

```
Version: 1.64.0-insider
Commit: e8a26d3ebf5095d4324ad4bf794787540ed3b33e
Date: 2021-12-21T05:14:12.146Z
```

But, it is not working correctly for some extensions, like my Bookmarks and Project Manager, neither Microsoft's Live Share.

![Kapture Side Panel Icon Issue](https://user-images.githubusercontent.com/3781424/146922772-9a37d1cf-a357-487b-9159-85ca83158e57.gif)

Is it something that will be fixed in the Side Panel itself, or extension developers must update their Side Bar icons to be visible there too?

BTW, the icons currently works perfectly in the original Side Bar.

Thank you

**Comment by alefragnani** [comment]
Also, why can't I move **any** panel / side bar / extension, from the Side Bar to the Side Panel?

Most of the native ones are not supported.

**Comment by Kroc** [comment]
Whilst you're doing all this great work, I'm just here to make sure the millions of users on "small" resolutions like 1366x768 don't get overlooked! It's already a struggle as it is

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/149707030-1da9bbfa-8853-426c-a271-7f5b9c3cf8c7.png)
 seem that the icon is some bigger that other three in visual

**Comment by nidefawl** [comment]
The second sidebar is a great addition.

One bug I came across today: 
I have the references view in the extra sidebar, I enabled it in the workspace config.
When I open a new workspace that has the sidebar disabled it fails to open the references view when use 'Find all references'.

**Comment by sbatten** [comment]
@nidefawl in the latest insiders builds, the side bar can no longer be "disabled" so this should no longer be an issue. please follow up if you are still seeing it in those builds

as for the icon @heartacker, we are still playing around with this icon, feedback is noted. cc @misolori

**Comment by heartacker** [comment]
{
  "command": "workbench.action.toggleMaximizedPanel"
}
@sbatten the command seems to maximize the side panel, not the panel

**Comment by sbatten** [comment]
@heartacker are you using a non-center panel alignment?

**Comment by heartacker** [comment]
@sbatten there is the gif pic

![sidepanel](https://user-images.githubusercontent.com/1876302/150239500-5b8d056a-4a4f-4071-93b1-8e19c7ce0677.gif)

**Comment by sbatten** [comment]
@heartacker I attempted to support maximization of the panel in the non-centered panel alignment scenario but our grid widget has some issues with it at the moment. as such, I've had to disable panel maximization in this case while we look into proper support for this.

**Comment by heartacker** [comment]
@sbatten thanks for ur clarify, so I want to set the penel aligning by center. but
1. I cannot see any setting about `panel align` or `align penel`
![image](https://user-images.githubusercontent.com/1876302/150444877-84b0a6f1-92db-4842-8806-5fd92f03d20c.png)
2. I cannot align panel by center through command prompt, there are only two commands without align center

![image](https://user-images.githubusercontent.com/1876302/150444997-f47e3324-6653-405e-9b97-c2326d957b06.png)
3. finish I find it is menu view

maybe we could improve the ux.
for example:
add setting to panel right click menu 
![image](https://user-images.githubusercontent.com/1876302/150445262-86dc9fad-daba-4002-8b70-073aa0fc9d21.png)

**Comment by sbatten** [comment]
@heartacker thanks for testing this out, it highlights a discoverability issue with the command titles. in today's insiders, there are a few ways to tweak the panel alignment. 

### Command Palette

<img width="461" alt="image" src="https://user-images.githubusercontent.com/6561887/150568747-98a6fdde-0dc6-41a3-ae7a-51eeb2dff4c9.png">


### Appearance Menu

<img width="485" alt="image" src="https://user-images.githubusercontent.com/6561887/150568873-c79f3662-fe27-48fb-a8a5-8ded61340ec1.png">

### Control Layout to Customize Layout...
<img width="178" alt="image" src="https://user-images.githubusercontent.com/6561887/150568964-890ecd8c-a243-4faf-8576-01a1381a5643.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/6561887/150569014-e4b9b84e-2eee-4ed6-8579-144ce1f2e10a.png">

**Comment by sbatten** [comment]
Closing this issue as the exploration phase is over. Please file new issues for feedback, bugs, and requests.
