### ISSUE TITLE
Remove the error list zone widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#13286]
I would like to remove the error zone widget due to the following reasons:

1. All of this functionality should live in the error list in the panel
2. Looks bad
3. I have a feeling that people are not using this, though for this assumption to be verified I would need @seanmcbreen to check some usage numbers

One of the rare features that the zone widget has and that is missing in the error list is captured here #13285

So once we have that and if the usage numbers are not high I propose to remove the error list zone widget. If we decide not to remove it then I volonter to make it look better.
@jrieken does not have a strong feeling against removing it

Opinions welcome @egamma @chrisdias @sandy081 

Picture for reference

<img width="660" alt="screen shot 2016-10-06 at 10 26 14" src="https://cloud.githubusercontent.com/assets/1926584/19145799/f4505dac-8bb0-11e6-8053-35ed78f44ded.png">

**Comment by jrieken** [comment]
No strong feelings, but things to think of
* we need to keep/maintain it for the standalone editor - to keep diagnostics accessible and because there is no *alternative* feature
* compared to the error list it allows for easier diagnostics navigation scoped to the current file or when using in *editor-full-screen*-mode

**Comment by egamma** [comment]
I regularly use it, and like the light weight navigation. It is consistent with our peek experience. I only opens the problems view when I want to see the errors in the workspace. I don't have it open when I'm editing a single file.

**Comment by jrieken** [comment]
> We must remove the quick fixes at the bottom. Now that we have a light bulb they are redundant.

That I removed with #13287. For mighty `abc` language the ugliness comes from it always producing a multiline error - which we must render properly using a mono-space font.

**Comment by sandy081** [comment]
Removing the error widget is not a good suggestion and I think it is removing useful functionality from the editor. I do not think Problems view is a replacement to Error widget. It is not easy to get the error description from problems view for a given error at given line. It will be more difficult if there are more errors on a single line.

Instead, I think it will be useful to show error widgets for all errors in the editor when asked.

**Comment by isidorn** [comment]
Closing as this will not happen
