### ISSUE TITLE
Run python in terminal is executing in powershell instead of default CMD

### ISSUE THREAD

**Issue by kumaran-chandrababu** [microsoft/vscode#132869]
The new software update has issues. Trying to run python in terminal by right clicking and chosing the option but instead of running on cmd terminal which Ive set that as a default, it runs on powershell terminal. This happens even I remove the powershell option from the terminal profile settings.

**Comment by kumaran-chandrababu** [comment]
So will there be a fix for this shortly then?

Many thanks,
Kumaran

**Comment by kumaran-chandrababu** [comment]
I updated the vscode to 1.60.0 two days back and only after updating I’m facing this issue, will there be another bug fix release?

Many thanks,
Kumaran

**Comment by IllusionMH** [comment]
You can try Insiders build https://code.visualstudio.com/insiders/ where fixes are in place. Recivery 1.60.1 currently planed for Monday if nothing else delay it. https://github.com/microsoft/vscode/issues/132150#issuecomment-917023548
