### ISSUE TITLE
npm script  not work in default  terminal  

### ISSUE THREAD

**Issue by sweetwisdom** [microsoft/vscode#132824]
# npm script  not work in default  terminal   (windows10)

In the past, I configured settings in NPM Script. When running '. Sh' script, PowerShell did not support it. So I set GitBash as the default terminal .

![image](https://user-images.githubusercontent.com/57869305/132792000-710273ba-1a7b-4b79-94e0-f195de27ba11.png)

However,Now I set git bash as the default terminal. When I click the run-time NPM script  

> bash不是内部或外部命令，也不是可运行的程序或批处理文件。
>Bash 'is not an internal or external command, nor is it a runnable program Or batch file

  it's not work , the terminal to execute is still PowerShell, 

![image](https://user-images.githubusercontent.com/57869305/132791518-fafcdd37-de66-4e3c-8f3e-6851cd1c5c8d.png)

# How to set Git Bash as the default terminal of NPM script ?

**Comment by beatgrabe** [comment]
Same problem here

**Comment by albertosantini** [comment]
See #132150

**Comment by dave90dave** [comment]
Wow, I spend so much time solving this issue.
I first thought that npm was the problem.
Never thought about visual studio code being the problem

**Comment by sweetwisdom** [comment]
官方已经解决这个问题,更新一下你的vscode就可以了
