### ISSUE TITLE
Text gets cut off for TS version mismatch error

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#13284]
![image](https://cloud.githubusercontent.com/assets/972891/19144259/620a0ea0-8b5d-11e6-9a80-1cada854f2dd.png)

**Comment by waderyan** [comment]
This seems to be a UX problem that we see in other ways. 

@dbaeumer should we look into making the language shorter?
@Tyriar possibly this should go on the UX backlog to solve this issue?

**Comment by dbaeumer** [comment]
@waderyan shorting the message does make sense as well. You can hover over the message to see the full text. Do you have an idea what can be left out?

**Comment by waderyan** [comment]
Here is the full text: 

> A version mismatch between the globally installed tsc compiler ({0}) and VS Code\'s language service ({1}) has been detected. This might result in inconsistent compile errors.

Here is a couple stabs

1. Version mismatch! global tsc ({0}) != VS Code's language service ({1}). Inconsistent compile errors might occur. 
2. Version mismatch! global tsc ({0}) does not match VS Code's language service ({1}). Compile errors might occur. 
3. Version mismatch detected! global tsc ({0}) does not match VS Code's tsc ({1}).

**Comment by dbaeumer** [comment]
I like 1.). Feel free to change https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptServiceClient.ts#L410

**Comment by waderyan** [comment]
@dbaeumer PR created - https://github.com/Microsoft/vscode/pull/13432

**Comment by dbaeumer** [comment]
Thanks. PR merged.
