### ISSUE TITLE
bug on searching uses regular expression

### ISSUE THREAD

**Issue by AndroidBeta** [microsoft/vscode#132835]
Issue Type: <b>Bug</b>

Version: 1.60.0 (Universal)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 16.7.0

I use regular expression to search one keyword in a txt file, while I input 
"  .*window:.* " (the input sequence is this: window: , .* , the first .* ),  VScode then not responding and crash. 

BTW: Searching uses regular expression is very slow on VSCode, but Sublime performs very vell

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 16.7.0
Restricted Mode: No

**Comment by AndroidBeta** [comment]
The regular expression is this:  .*window:.*

**Comment by AndroidBeta** [comment]
> the regular expression is this:   .*window:.*

**Comment by IllusionMH** [comment]
Looks like github ate `*` characters. Please wrap your input in backtics so it will be treated as Code and not markdown markup. Example `` `regexp` ``

Is it find in files or find widget in editor?

**Comment by AndroidBeta** [comment]
`the expression is here:    .*window:.*      `

**Comment by AndroidBeta** [comment]
find in a single file of about 2.5M size
