### ISSUE TITLE
use terminal as default for Git bash

### ISSUE THREAD

**Issue by oliversh99** [microsoft/vscode#132812]
Issue Type: <b>Bug</b>

i cant open my terminal on default with git bash its every time back to powershell and let me back to main file on git bash when i chose it to work all this is show after the last update .
thanks for help 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by datuadiatma** [comment]
I am having the exact same problem after updating to 1.60.0.

**Comment by Roy0309** [comment]
+1! The integrated terminal always uses PowerShell after I setting "terminal.integrated.defaultProfile.windows" : "Command Prompt".
