### ISSUE TITLE
No indent guides for these lines

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#13288]
From https://github.com/Microsoft/vscode/issues/12398#issuecomment-250580634

From @Tyriar 

![image](https://cloud.githubusercontent.com/assets/2193314/18970891/f31f447a-8647-11e6-84f8-7380096bf08c.png)

``` jade
        .bla
            label(for)
include script
```

**Comment by Nimzozo** [comment]
Also found a bug with HTML markup.
```html
    <div>

    </div><!-- comment

 --><div>

    </div>
```
Because of the comment, the indent guide is missing for the second `div`.

**Comment by alexandrudima** [comment]
This now works as expected:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/5047891/33660819-87f2a7a8-da85-11e7-9ff3-22f31acd508e.png">
