### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by zhangx306** [microsoft/vscode#132804]
Issue Type: <b>Bug</b>

**run the previous cell while mouse pointing at the next one**

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by yuanchongtt** [comment]
I have had this problem, too It occurred when I add a cell_2 below cell_1, after I run cell_2 with ctrl+Enter, it run the cell_1. It has brought some problems. Now I must remind myself to use mouse to click `run Execute cell` rather than ctrl+Enter.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/133038
