### ISSUE TITLE
Maintain open files and groups on a branch-by-branch basis

### ISSUE THREAD

**Issue by BekahHW** [microsoft/vscode#132882]
## Description
When changing branches in VSCode, maintain the open files and groups on a branch-by-branch basis rather than carrying over the open files and groups based on the most recently worked-on branch.

### Example
**Initial Open Branch**: `feature/profile-tests` 
     - **Files open**:  `cypress> integration > profile.js`, and `admin > profile.js`
 
 While working on that branch, I need to switch what I'm working on to squash a bug in a new branch.
 
 **New Branch**: `fix/address-form`
     - **Files open**: `address-form.js`,  `cypress> integration > address-form.js`, `shipping.js`, `thanks.js`
     
 After completing the fix, I have all six files from both branches open in my `fix/address-form` branch. And when I switch back over to the `feature/profile-tests` branch, I still have all of the files open.  But, if the feature I'm requesting were implemented, I would start the new branch with no open files, and when I switched back over to the initial open branch, I would only have the two files open associated with that branch (`cypress> integration > profile.js`, and `admin > profile.js`). This would make it quicker to move back and forth between branches and issues, rather than having to open a new window or create a new workspace.

**Comment by eamodio** [comment]
Once the "tab" api lands this would make for a good extension -- I actually have plans of either adding to GitLens or my Restore Editors extension
