### ISSUE TITLE
Copy Path(Shift+Alt+C) Not working Propery

### ISSUE THREAD

**Issue by lawweiliang** [microsoft/vscode#132803]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.6.0
- OS Version: Window10

Steps to Reproduce:
1. Open Multiple Code Tab
2. Then, click Shift+Alt+C
3. Then, paste the path.
4. You will figure out that, you select a particular tab but it give you other tab path.

Error Image

![image](https://user-images.githubusercontent.com/34936929/132764474-d1e5fbd9-09d4-4f37-bba1-3b77dee30056.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
