### ISSUE TITLE
Latest insider regressed issue with remote ssh adding an extraneous 0 to the server bin hash

### ISSUE THREAD

**Issue by zulrang** [microsoft/vscode#132885]
Issue Type: <b>Bug</b>

When trying to connect to a host using remote-ssh, VSCode is looking for a bin/{hash} folder using an extra zero.

This is an issue with the stable version in Windows 11, which was fixed in the last Insider build, but has re-appeared today.

![image](https://user-images.githubusercontent.com/1043189/132906662-40261534-dbf3-40b5-90a7-c9d2097caf7b.png)

VS Code version: Code - Insiders 1.61.0-insider (23cffa27b806f9e1733e15d611ec251dcdba2c42, 2021-09-10T17:05:11.199Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (21.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0

</details>

**Comment by roblourens** [comment]
We can keep discussing in the original issue https://github.com/microsoft/vscode-remote-release/issues/5303 and I can reopen if needed
