### ISSUE TITLE
When typing "SWITCH" in C# format, there is something strange

### ISSUE THREAD

**Issue by zh-ray** [microsoft/vscode#132841]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Win10

Steps to Reproduce:

1. Ctrl+N, select C# format
2. type switch
![switchError](https://user-images.githubusercontent.com/16232711/132818693-bd9f57d8-7402-44af-9c50-21c3059c2446.gif)
I've tried disabling all extensions , but the problem remains

**Comment by alexdima** [comment]
@zh-ray What is strange? Is there a problem with typing or is there a problem with syntax highlighting?

**Comment by zh-ray** [comment]
It is the same as the #133431, and I know the way to fix it
