### ISSUE TITLE
Setting to hide cwd/cwdFolder if in a single root workspace

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#132888]
it's extra noise on the screen if you only have one folder in the workspace, since it doesn't help to distinguish the terminals.

![one-folder](https://user-images.githubusercontent.com/29464607/132933544-8eadd8db-8e6a-4113-aeeb-c7978f181755.PNG)

While this can be configured, that isn't easily discoverable for beginners, who could be distracted by the extra info

**Comment by meganrogge** [comment]
only show for cwds that are not equal to `initialCwd `specifically for `cwdFolder `

**Comment by meganrogge** [comment]
Not clear if this is the best behavior for this (pretty rare) scenario...:
- single folder -> multi -> dirs appear in titles 👍🏼 
- multi -> single folder (with terminals in diff't dirs) -> dirs disappear 😦 
![recording (67)](https://user-images.githubusercontent.com/29464607/133156616-95f0b423-2bf5-4c66-815c-2c652034d38b.gif)

**Comment by Tyriar** [comment]
@meganrogge oh instead of looking against initialCwd we should be looking again the default cwd of the workspace for single root workspaces? ie. terminal.integrated.cwd if it's defined, otherwise the workspace folder. That would cause the last 2 to still say "hi"

**Comment by meganrogge** [comment]
I'm not sure we can use `terminal.integrated.cwd` for this since it changes based on the terminal. I think we always have to compare against the resource for the workspace.

**Comment by meganrogge** [comment]
I'm not sure we can look at `terminal.integrated.cwd` to tell us this because that changes per terminal. I think each time we have to compare the cwd with the resource of the workspace.

**Comment by Tyriar** [comment]
We need to use terminal.integrated.cwd in the same way it is used during process creation:

https://github.com/microsoft/vscode/blob/9584fec6e982c2435b2589cc650cdf3087103bbe/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L424-L431

The following case should be covered:

- Open vscode repo
- Set `terminal.integrated.cwd` in `.vscode/settings.json` to `"src"`
- Open a terminal, the terminal should open in the `src` directory but the `cwdFolder` should be `""`, not `"src"`
- Run `cd ..`, the `cwdFolder` should be `"vscode"`
