### ISSUE TITLE
Show parent tests even if URIs differ when filtering for a document

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#132818]
I'm working with the new test API and I've noticed that the filter `Show in Active File Only` is only considering the top level test items when filtering.

If I have a setup like:

* Test Target (id: target1, location: `root/tests/BUILD:123:0`) (in the `items` on the `vscode.TestController`)
  * Test Class (id: class1, location: `root/tests/MyTestFile1.swift:1:0`)
    * Test Method (id: method1, location: `root/tests/MyTestFile1.swift:5:2`)
  * Test Class (id: class2, location: `root/tests/MyTestFile2.swift:1:0`)
    * Test Method (id: method1, location: `root/tests/MyTestFile1.swift:5:2`)

If I enable the document filter while `root/tests/MyTestFile1.swift` or `root/tests/MyTestFile2.swift` open then the Test Explorer is empty.

If I open the `root/tests/BUILD` file then the filer does work.

**Comment by connor4312** [comment]
We expect extensions to listen to `vscode.workspace.onDidOpenTextDocument` in order to publish tests in the file; this is necessary to enable test gutter decorations. If tests are published when this happens, then the document filter will work.

**Comment by ashgti** [comment]
Here is a clip of the behavior I'm talking about, it looks like the gutter icons are all present for the file I have open, but when I apply the filter it doesn't show any tests in the test explorer

![active-file-filter-bug](https://user-images.githubusercontent.com/22535/132883559-bc3bb0b9-cdb7-49f9-b6e1-2f6c1d5ac3c7.gif)

**Comment by ashgti** [comment]
Ah okay, so changing the top level item (from my example item with id `target1`) to point to the folder instead of to the definition in a file the document filter does work as expected.

So, I think this may be an issue with `vscode.TestItem`'s that have a `uri` to a file with children having a `uri` to a different file.

**Comment by connor4312** [comment]
I fixed this, however there is a bug/behavior in our tree views that you might hit. I should get that fixed this month or next: https://github.com/microsoft/vscode/issues/133272

**Comment by ashgti** [comment]
Checked with a0af58197e4a1d3e82fbe3048e0549e622d19f4f and it works for me.

/verified
