### ISSUE TITLE
User data configuration files are using `vscode-userdata` scheme from 1.37.0 but it is still using `jsonc` language. Can prettier extension use language instead of scheme for document selector and formatting?

### ISSUE THREAD

**Issue by fatihaziz** [microsoft/vscode#132831]
User data configuration files are using `vscode-userdata` scheme from 1.37.0 but it is still using `jsonc` language. Can prettier extension use language instead of scheme for document selector and formatting?

_Originally posted by @sandy081 in https://github.com/microsoft/vscode/issues/79038#issuecomment-528305846_

It happen to me too but after i add 
```
{...settings.json
	"[jsonc]": {
		"editor.formatOnSave": true,
		"editor.formatOnPaste": true,
		"editor.formatOnType": true,
		"editor.wordWrap": "on",
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
}
```

it work properly now!

**Comment by sandy081** [comment]
Please file the issue against the prettier extension.
