### ISSUE TITLE
Support code folding when line numbers are turned off

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode#132800]
In virtually every other coding scenario in VS Code, line numbers are enabled by default. In Jupyter Notebooks, they are off by default. The side effect of this is that code folding doesn't work and the user isn't sure why. 

It seems to me that if we are going to be consistent with the rest of the developer experience in VS Code, we should have line numbers on by default.

**Comment by greazer** [comment]
Seems like code folding should be supported even if line numbers are disabled.
