### ISSUE TITLE
Feature request: Offset "Delete" on mouse right click context menu

### ISSUE THREAD

**Issue by jowrjowr** [microsoft/vscode#132805]
Couldn't find any issues related to this.

The current right click context menu on files in the explorer has the interesting UI quirk that "Delete" is the element above the mouse, and if you have a mouse weirdness or just misclick you can easily delete a file. 

Not an issue for committed code of course, but this has eaten uncommitted code a few times. Ultimately I need to train myself to use shortcuts instead of relying on context menu, but I need it relatively infrequently so I just....don't.

What I would like would be to either change where the menu appears so its offset from the cursor. Alternatively, simply add a blank menu item so that "Delete" function doesn't pop up right next to your mouse button.

**Comment by JacksonKearl** [comment]
Extensions can contribute to this menu, I either creating or installing one that places entries last on this list. For example, the [Editor Config](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension puts an entry here, as do some Azure extensions for deploying apps.
![image](https://user-images.githubusercontent.com/8586769/132783309-90490316-1a4e-4fd6-b2b0-a8358d0a392f.png)

**Comment by thequailman** [comment]
Too bad this was closed, this has happened to me quite a bit too.  It's extremely frustrating when it happens (and also not super obvious), and I think it's under reported.  Like the reporter, I think the default should be changed--users shouldn't need an extension to avoid shooting themselves in the foot with a fresh VSCode install.
