### ISSUE TITLE
`workbench.editor.languageDetection` keeps detecting `.gitignore` as `bat`

### ISSUE THREAD

**Issue by jameschenjav** [microsoft/vscode#132814]
Issue Type: <b>Bug</b>

Even I set project settings
```json
  "files.associations": {
    ".gitignore": "gitignore",
  },
```

My `.gitignore`:

```gitignore
tmp/*
nohup\.out
passenger.3000.pid
passenger.3000.pid.lock
Gemfile.fs_repo.lock
passenger.*.pid.lock
passenger.*.pid
coverage/
private/reports_production/svnupdate.log
private/reports_production/Production/.svn
log/*
doc/app
doc/app/
dump.rdb
doc/app/*
doc/app/classes/
public/wf_graphs/*
public/uploads/*
dump.rdb
public/external/*
public/fs_online/*
private/document_storage/*
private/document_storage
private/exports/*
private/report_images
private/report_output
public/passenger_stats.txt
public/prtg.xml
public/packs/fs_online/*
lib/assets/javascripts/static-dev.js
lib/assets/stylesheets/static-dev.css
*~*
#*
*#
*swp
*log
config/config\.yml
config/fsonline\.yml
config/fsapi\.yml
config/ldap\.yml
config/puma\.rb.sample
config/puma\.rb
config/mail\.yml
config/skylight\.yml
config/newrelic\.yml
config/database\.yml
config/masq\.yml
config/saml.yml
db/db_code/unprocessed/*
db/db_code/processed/*
db/test_structure.sql
db/development_structure.sql
public/email_attachment
public/email_attachment/*
db/development_structure.sql
public/stylesheets/application.css
app/stylesheets/.sass-cache/*
public/document/*
public/email_attachments/*
public/report_output/*
app/stylesheets/.sass-cache/*
app/stylesheets/.sass-cache
app/assets/stylesheets/.sass-cache/
public/stylesheets/compiled/*
public/assets/*
nbproject/
nbproject/*
rerun.txt
public/report_template
public/report
public/report_output
public/report_file
public/javascripts/cached/*
public/javascripts/cached/
reports.log
afiedt.buf
*Thumbs*
.idea/*
tags
TAGS
.#*
*#
vendor/gems/rails_upgrade/
public/images/active_scaffold/default/config.png
.vscode/
._.DS_Store
.DS_Store
**/node_modules/
test/browser/cypress/fixtures/settings.js
coverage
.bundle/
/config/initializers/fs_api_services.rb
private/fs_api_services
private/report/html/*.yml
tests/screenshots/*
!tests/screenshots/.keep
private/fs_auth/

# dev assets built with `USE_DEVELOPMENT_ASSETS=1 yarn build` ({entries,manifest}.dev.json)
private/assets/*.dev.json
public/dev

# force including assets compiled by webpack in case weird char (like ~) in name
!public/web/**/*.js
!public/web/**/*.css
!public/web/**/*.gz

# dotenv: https://www.npmjs.com/package/dotenv#faq
!.env
# use `.env.dev` to override for development
.env.*

# generated by `yarn build --report` or with `--report-json`
public/web/report.*

# for vscode, can open app/web individually in order to use separated eslint auto-fix settings
app/web/tsconfig.json
```

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.61-1-MANJARO
Remote OS version: Linux x64 5.10.61-1-MANJARO
Remote OS version: Linux x64 5.10.61-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 2863e2fb-a0d2-481e-a375-609eeb69ee47|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: javln-dev|
|OS|Linux x64 5.10.61-1-MANJARO|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2592)|
|Memory (System)|9.69GB (0.31GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: javln-dev|
|OS|Linux x64 5.10.61-1-MANJARO|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2592)|
|Memory (System)|9.69GB (0.31GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: javln-dev|
|OS|Linux x64 5.10.61-1-MANJARO|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2592)|
|Memory (System)|9.69GB (0.31GB free)|
|VM|67%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.1
project-manager|ale|12.4.0
ruby-on-rails-snippets|ate|0.0.1
vscode-toggle-quotes|Bri|0.3.5
vscode-markdownlint|Dav|0.43.2
es7-react-js-snippets|dsz|3.1.1
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
remotehub|Git|0.14.0
output-colorizer|IBM|0.1.2
endwise|kai|1.5.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
hexeditor|ms-|1.8.2
material-icon-theme|PKi|4.10.0
slim|sia|0.1.2
rewrap|stk|1.14.0
rails-snippets|Ven|0.5.0
highlight-matching-tag|vin|0.10.1
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.28.0
atlascode|atl|2.9.1
vscode-tailwindcss|bra|0.6.14
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
docker-explorer|for|0.1.7
todo-tree|Gru|0.0.214
volar|joh|0.27.17
endwise|kai|1.5.1
haml|kar|1.3.1
vscode-gutter-preview|kis|0.27.1
git-graph|mhu|1.30.0
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.16.1
color-highlight|nau|2.4.0
vscode-gem-lens|nin|0.3.1
oracledevtools|Ora|21.3.0
vscode-versionlens|pfl|1.0.9
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
markdown-preview-enhanced|shd|0.6.0
slim|sia|0.1.2
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.4
svelte-vscode|sve|105.3.5
sass-indented|syl|1.8.18
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.14
vscode-ruby|win|0.28.0
change-case|wma|1.0.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4
plsql-debug|zer|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30364559
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by Fdawgs** [comment]
As a workaround i have just straight up disabled it for now, see https://github.com/microsoft/vscode/issues/132505#issuecomment-915466075
