### ISSUE TITLE
[JSDoc] [TestUI] Data property on createTestItem no longer exists

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#132819]
Issue Type: <b>Bug</b>

@connor4312 
The data property no longer exists on createTestItem but it is still present in the JSDoc

![image](https://user-images.githubusercontent.com/15258962/132783604-5d68c60e-21c7-4cf7-afa0-6083a5b8571e.png)

VS Code version: Code - Insiders 1.61.0-insider (a3fce6207d9364afcfccaa55efc82ff8a392fdd5, 2021-09-06T08:02:01.874Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (3.23GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/JGrote/Projects/vscode-adapter --crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-log-viewer|ber|0.12.2
markdown-checkbox|bie|0.3.2
vscode-opennewinstance|chr|0.0.12
esbuild-problem-matchers|con|0.0.2
vscode-eslint|dba|2.1.25
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.6.0
filter-lines|ear|1.0.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
copilot|Git|1.4.2635
remotehub|Git|0.14.0
vscode-pull-request-github|Git|0.30.0
todo-tree|Gru|0.0.214
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.2
change-case|hjd|1.0.2
git-graph|mhu|1.30.0
vscode-bicep|ms-|0.4.613
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
remote-containers|ms-|0.194.0
remote-ssh-nightly|ms-|2021.9.12420
remote-wsl|ms-|0.58.2
azure-account|ms-|0.9.8
powershell-preview|ms-|2021.9.0
test-adapter-converter|ms-|0.1.2
vscode-paste-image|mus|1.0.4
indent-rainbow|ode|7.5.0
docthis|oou|0.8.2
vscode-jest|Ort|4.1.2
pester-test|psp|2021.8.1
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
vscode-sort-json|ric|1.20.0
even-better-toml|tam|0.14.2
vscode-inline-values-powershell|Tyl|0.0.5
errorlens|use|3.4.0
vscode-icons|vsc|11.6.0
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
gitmoji-vscode|Vtr|1.0.7
better-align|wwm|1.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30361752
pydsgst2:30361790

```

</details>

**Comment by connor4312** [comment]
This is updated in main, I suspect you have an older version of the typings

https://github.com/microsoft/vscode/blob/9176be11bc10ff48b24a4066731c9643fc36aff9/src/vs/vscode.d.ts#L14210-L14220
