### ISSUE TITLE
C++ file name with space causes error in Visual Studio Code

### ISSUE THREAD

**Issue by Supriyo016** [microsoft/vscode#132890]
When I write a C++ program with the file name Hello World.cpp in Visual Studio Code I got some errors:

#include<iostream>
using namespace std;
int main()
{
  cout<<"Hello World!!!"<<endl;

return 0;
}
Output:-
g++.exe: error: Hello: No such file or directory
g++.exe: error: World.cpp: No such file or directory
g++.exe: error: World: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.

But when I rename the file without space like HelloWorld.cpp, then I did not get any type of error. And I use the latest updated Visual Studio Code and MingW compiler.

But I wanted to use filename with space. How do I resolve this problem?
![image](https://user-images.githubusercontent.com/87006598/132915508-9268b163-06b3-4e51-9e06-01c7dc7fabc2.png)

**Comment by lramos15** [comment]
Try placing quotes around the file name in your terminal.

**Comment by lramos15** [comment]
Closing due to lack of update
