### ISSUE TITLE
Workspace search with "match whole world" does not respect language-specific wordSeparators setting

### ISSUE THREAD

**Issue by maxrothman** [microsoft/vscode#132874]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: MacOS 11.5.2

Steps to Reproduce:

1. Set `editor.wordSeparators` for a specific language. For example:
    ```
    "[css]": {
        "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?"
    }
    ```
    Notice that `-` has been removed from the setting's value.
2. Create the following file (foo.css):
    ```
    .foo { background-color: blue; }
    ```
3. Search in that file for `background` with "Match whole word" enabled. As expected, no results are returned until you finish typing `-color`.
4. Search In Files (workspace search) for `background` with "Match whole word" enabled. Unlike file-specific search, the `background` in `background-color` is matched.

**Expected result**: like file search, the result of "Search In Files" with "Match whole word" enabled respects the `editor.wordSeparators` setting, and the results returned by both types of searches are identical

**Actual result**: when `editor.wordSeparators` is set for a specific language and "Match whole word" is enabled, the results of file-specific search and workspace search differ

**Comment by roblourens** [comment]
Unfortunately language-specific search features aren't really practical for us to do. Will leave this open for now though. Roughly related to https://github.com/microsoft/vscode/issues/27280

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. PRs are welcome so you can create a PR that fixes this if you are passionate about getting this feature across the finish line. Thanks!
