### ISSUE TITLE
I can't use shortcut like 'ctrl + A' .

### ISSUE THREAD

**Issue by solikego** [microsoft/vscode#132838]
I can't use shortcut like 'ctrl + A'  in editor,and it always in replace mode when I open a file.I use vscode in linux.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+A`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
