### ISSUE TITLE
Markdown renderer disposing issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#132816]
I can help with these, figured I'd discuss first

Issue 1. `asyncRenderCallback` is still called after the rendered markdown is disposed
- Call `markdownRenderer.render` with a `asyncRenderCallback` set and immediately dispose the result
- `asyncRenderCallback` is called after the object is disposed, it seems like this shouldn't be called, and caused some confusion in https://github.com/microsoft/vscode/issues/132430

Issue 2. img load listener might never be disposed. I think that if we remove the element from the DOM, or the image doesn't load for some other reason, then this listener won't be disposed
https://github.com/microsoft/vscode/blob/8b7264a91d63da706fb44f9a3dd34cb4c804e7e0/src/vs/base/browser/markdownRenderer.ts#L251-L251

**Comment by mjbvz** [comment]
Good find! Just pushed a fix for the second issue

**Comment by mjbvz** [comment]
Pushed fix for the first issue too and added tests for these cases. Let me know if you still see any issues

**Comment by roblourens** [comment]
Thanks!
