### ISSUE TITLE
key not working 

### ISSUE THREAD

**Issue by sanket-blip** [microsoft/vscode#132843]
'M' key is not working when i code any thing in any programming languages like (python , c,java,html) m key is not working

**Comment by aeschli** [comment]
There's a command `Developper: Toggle Keyboard Shortcuts Troubleshooting`
When activated, it will show in the output what happens on a key press (what command in invoked).

Maybe you accidentally configured a command for 'M'. Check the keyboard shortcuts configuration page for that.

**Comment by sanket-blip** [comment]
Thankyou so much
