### ISSUE TITLE
Please add read support and intellisense for EJS HTML

### ISSUE THREAD

**Issue by rasyidrafi** [microsoft/vscode#132817]
Issue Type: <b>Feature Request</b>

I am developing using node on back end, and html ejs on client side,
however, the  vs code read ejs file as regular html,
so it was very bad at formatting and syntax highlighting,

example case :
i was working on html with ejs 
<div>
   <% variableFormBackend %>
   
</div>

below the line after including ejs, the intellisense miss underestand that i working on javascript. 
but the real one is i currently working on html.

this become bad issue at formatting and word break

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

Default formatter did :
![Screenshot (27)](https://user-images.githubusercontent.com/69502214/132778303-ce3d4e9f-e3a1-4ff5-95a1-5d30c898e2a4.png)

Comment on html readed as javascript
![image](https://user-images.githubusercontent.com/69502214/132778407-37b7bf5f-60d6-4f76-b159-3ca8ef245eb1.png)

**Comment by infinnie** [comment]
There are many extensions for this feature. However if you don’t want to install one, you can force the language mode to HTML for this file extension.

**Comment by sharedrory** [comment]
https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support
