### ISSUE TITLE
VSCode unittest error discovering unittest tests

### ISSUE THREAD

**Issue by BruceGraham-Zoetis** [microsoft/vscode#132887]
No help.

 I did.
 No help.

Does this issue occur when all extensions are disabled?: Yes/No
Just the ones I need.

- VS Code Version: 1.60.0
- OS Version: Linux ubuntu 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. In VSCode, open the testing directory.
2. Open the test file.
3. click on the testing icon.
4. Expected: test_one shows up in the testing window.
5. Actual: The testing window reports: Error discovering unittest tests

The testing project...
[testing.zip](https://github.com/microsoft/vscode/files/7146085/testing.zip)

**Comment by karthiknadig** [comment]
This is https://github.com/microsoft/vscode-python/issues/17363

**Comment by karthiknadig** [comment]
@BruceGraham-Zoetis We just pushed a fix for this. Please update the python extension.
