### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by naveen7123** [microsoft/vscode#132855]
- Issue Type: `Bug`
- Extension Name: `json-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT ia32 6.3.9600`
- VS Code version: `1.60.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by naveen7123** [comment]
![Screenshot (125)](https://user-images.githubusercontent.com/74102747/132844355-ada09b73-1185-4ea2-94b2-0686392f5476.png)

**Comment by aeschli** [comment]
Closing as information is missing
