### ISSUE TITLE
vs code 启动程序报错

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [microsoft/vscode#132837]
![image](https://user-images.githubusercontent.com/57666259/132815032-9c24c01d-96f0-40ff-9451-c0c4b1e8b49f.png)

无法启动！！！

**Comment by Tuzhiqiang1996** [comment]
我尝试在 配置文件中添加

"terminal.integrated.shell.windows": "C:/Windows/System32/cmd.exe",

但还是无效的

**Comment by CodeCrazy-ywt** [comment]
The terminal cannot be started properly. Switching `terminal.integrated.shell.windows` to  `C:/Windows/System32/cmd.exe` doesn't help.

**Comment by Tuzhiqiang1996** [comment]
thank you！Finally choose to reinstall the software to solve
