### ISSUE TITLE
[feature] Add a way to tell where a configuration setting exists (user vs workspace)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#13281]
- VSCode Version: `Version 1.6.0-insider (1.6.0-insider)` 782e3ad7e504c308a5f1592ca6ae2574a13b0e73
- OS Version: `macOS Sierra Version 10.12 (16A323)`

Now that there is a way to update configuration settings (at either the workspace or user level), it would be great if there was a way to tell where a configuration setting is currently saved. That way if an extension is trying to update a setting it can do so in the proper location.

Maybe `get` or `has` could have an optional `global` bool like `update` which would only check the global (i.e. user) level?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10583
