### ISSUE TITLE
Inlay hints does not take effect when the parameter variable passed in is the same as the parameter name

### ISSUE THREAD

**Issue by xlboy** [microsoft/vscode#132832]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Darwin arm64 20.6.0

1.   In setting.json, `"typescript.inlayHints.parameterNames.enabled": "all"`
2.  Pass in the function a variable name that is the same as the parameter name

The effect is shown in the following figure.
![inlay-hints-issues](https://user-images.githubusercontent.com/63690944/132800196-7b92480b-04ad-4d24-90dd-6608cbb7208c.gif)
![image](https://user-images.githubusercontent.com/63690944/132800638-8f5f90ae-8469-44e8-b7ac-092d438c88e9.png)

**Comment by mjbvz** [comment]
This is by-design since the hint would simply duplicate the name. You can disable this behavior with `javascript.inlayHints.parameterNames.suppressWhenArgumentMatchesName` (it is on by default)
