### ISSUE TITLE
Terminal "description" should always show up in the hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#132801]
Right now it only contains the title and the status icon explaination.

![image](https://user-images.githubusercontent.com/2193314/132758839-d1c85ca4-6fd6-4a62-8123-1eff0c205a5b.png)

This is also missing in the terminal panel

![image](https://user-images.githubusercontent.com/2193314/132759081-ec3a9b9e-d1f2-440b-a134-eedfb8e99310.png)

```
${title} - ${description}

${statusDescription}
```

**Comment by meganrogge** [comment]
the name is being used on hover for the terminal editors and I can't find where that is happening in the code 🤔

looks like for other file types, the description is shown on hover, which is what we want

**Comment by meganrogge** [comment]
Doesn't work in the editor
