### ISSUE TITLE
'Embed into Div' option in Edit menu

### ISSUE THREAD

**Issue by Remonetized** [microsoft/vscode#132862]
When writing code, one thing I often do (perhaps because I'm fairly amateur) is wrapping a section of html within a new div, eg a bootstrap container. There may be some easier way to do this, but I tend to use emmet shortcuts to create a div, delete the closing tag and make the new one below the relevant section (or cut and paste it). Then of course I highlight the code to indent it. It would be very useful to have an option or extension which allows me to highlight a section of code, and wrap it into another div, ideally even indenting it. This would be similar to the option in the EDIT menu to highlight a section and toggle a block or line comment, but instead you highlight the section, then select 'embed into div'. Obviously this only applies to html files so maybe it could be a contextual feature. 
Anyway if this is already possible in some way or at least there's a quicker workaround then please let me know. Many thanks.

**Comment by rzhao271** [comment]
Check out the Wrap with Abbreviation command. First, you select the part you want to wrap, and then an inputbox should show up allowing you to enter an Emmet abbreviation like `div`.

**Comment by Remonetized** [comment]
Thank you, that is extremely helpful, I will use this a lot! For anyone else who may find this useful, highlight the part you wish to wrap into a div (or any other tag), press 'ctrl + shift + p' then begin to type 'emmet' then select 'emmet: wrap with abbreviation'. You can also select a keyboard shortcut to get directly to this by clicking the preferences icon to the right then clicking the '+' to add a keyboard binding. I chose a chorded 'ctrl w e' (hold ctrl, press w, then e).
