### ISSUE TITLE
VSCode doesn't clean up old extension versions

### ISSUE THREAD

**Issue by ImRodry** [microsoft/vscode#132896]
Issue Type: <b>Bug</b>

Whenever an extension updates, vscode simply downloads it again and creates a new folder in the extensions folder with the new version, leaving the old version on the folder as well which takes up unnecessary space. This should be improved so that the old extension is deleted and replaced with the updated version

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.89GB (4.24GB free)|
|Process Argv|D:\\Users\\rodri\\Documents\\GitHub\\hypixel-translators-bot --crash-reporter-id 1aa51578-c79e-468f-b062-c24334e21918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
jsdoc-markdown-highlighting|bie|0.0.1
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.1.0
copilot|Git|1.4.2635
vscode-graphql|Gra|0.3.18
discord-vscode|icr|5.7.0
vscode-env|Iro|0.1.0
volar|joh|0.27.17
python|ms-|2021.9.1218897484
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
vsliveshare|ms-|1.0.4836
vetur|oct|0.34.1
vscodeintellicode|Vis|1.2.14
minecraft-lang-colorizer|zz5|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by sandy081** [comment]
We do it when VS Code is restarted. Until then we are not sure if any of the opened VS Code windows are running this extension.
