### ISSUE TITLE
No reference to discussion forums

### ISSUE THREAD

**Issue by Chealer** [microsoft/vscode#132891]
I could not find any forum about Visual Studio Code. And unfortunately, none of the project resources I searched (which include README.md, CONTRIBUTING.md, the wiki and https://code.visualstudio.com/) lists any as far as I can see.

Some minimally prominent resource should list this project's web forums and/or mailing lists. Given the structure, at least CONTRIBUTING.md should provide that information.

**Comment by digitarald** [comment]
We did link to the [extension discussions](https://github.com/microsoft/vscode-discussions/discussions) from more places that talk about extensions, and google traffic on the discussions board is also much stronger now.
