### ISSUE TITLE
Manual installation of python extension fails with: XHR failed

### ISSUE THREAD

**Issue by Roccoriu** [microsoft/vscode#132849]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Download latest version of vscode
2. Download latest VSIX of the python extension
3. Try installing the VSIX file in vscode

The developer tools show the following 
![image](https://user-images.githubusercontent.com/25778176/132823665-5d963d4b-96c7-445a-9b12-f43c64e84da9.png)

I have tried reinstalling twice. It didn't solve the problem. It happens only with the python extension. All other extensions I've tried can be installed using the VSIX file.

**Comment by sandy081** [comment]
Please return and share the following logs

> F1 > Open View... > Log (Shared)

**Comment by Roccoriu** [comment]
![image](https://user-images.githubusercontent.com/25778176/133396932-56db1c75-e556-47e0-b614-4ff8f1c8fa6f.png)

This is the logs

**Comment by ryanxsim** [comment]
I'm having the same issues with the remote-ssh extension. See my issues: https://github.com/microsoft/vscode/issues/133226

**Comment by sandy081** [comment]
It seems there is an error downloading the VSIX from Marketplace. Need more details to understand more. 

- Open Shared Process Dev tools using command `F1 > Toggle Shared Process`
- Open console in Shared process window
- Retry the operation

See what is the network error logged there. Also go to network tab in shared process and see the failed request and let us know what error it is.
