### ISSUE TITLE
Open recently closed tab auto pins it when the other group has a pinned tab

### ISSUE THREAD

**Issue by shogunsea** [microsoft/vscode#132833]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: macOs 11.5.2

Steps to Reproduce:
1. Open a file in a tab, pin it.
2. open another file in a new group, or split to right.
3. Close the tab on the right
4. "command+shift+T" to open recently closed tab.
5. The other tab is reopened but pinned.

**Comment by bpasero** [comment]
👏
