### ISSUE TITLE
debug button suddenly appears inside  editor with json code 

### ISSUE THREAD

**Issue by andrei-trybukhouski** [microsoft/vscode#132857]
Issue Type: <b>Bug</b>

1. Open package.json
![Alt text](https://i.imgur.com/EqTued3.png "screenshot")
the button works as expected -  starts debugging))
file:
`{
    "name": "******",
    "version": "0.0.1atr",
    "description": "",
    "author": "",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "license": "MIT"
}`

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.10.25r5n4
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1200 Quad-Core Processor (4 x 1398)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.63GB (1.58GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5021d1f0-14be-476c-a851-4a45052ccc5f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.7.1
php-pack|fel|1.0.2
code-runner|for|0.11.5
vscode-javac|geo|0.2.39
terraform|has|2.14.0
kubernetes-snippets|ipe|0.1.9
jenkins-pipeline-linter-connector|jan|1.2.0
better-cpp-syntax|jef|1.15.6
vscode-phpfmt|kok|1.0.30
kubernetes-templates|lun|1.3.0
jenkins-doc|Maa|1.7.0
groovy|Mel|1.0.0
vscode-docker|ms-|1.16.1
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
cpptools-extension-pack|ms-|1.0.0
live-server-preview|neg|0.1.4
vscode-groovy-lint|Nic|1.4.0
md-template|oGr|2.0.1
platformio-ide|pla|2.3.3
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
jenkinsfile-support|sec|0.1.0
ms-teams-vscode-extension|Tea|2.6.0
autocomplate-shell|tru|0.1.1
vscode-java-debug|vsc|0.35.0
vscode-java-pack|vsc|0.18.4
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0
debug|web|0.25.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30364559
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by IllusionMH** [comment]
/question

This is helper for running/debugging NPM scrips from your `package.json`.
You can control it with `debug.javascript.codelens.npmScripts` setting.
