### ISSUE TITLE
Differential syncing - platform agnostic and platform specific synchronisation flags

### ISSUE THREAD

**Issue by raydleemsc** [microsoft/vscode#132822]
a framework for extensions to have their settings synchronized across platforms which share attributes relevant to the settings being shared - an extension requiring a linux package should not be asking for the package when synced to a windows platform, so have this requirement morphed into a windows-relevant requirement and then sync that across windows environment.

And, while we're at it, have syncable settings for groups which can then be personally overridden by bringing in personal look and feel settings which do not interfere with organisational operational settings required for the environment being synced into.

So an incoming expert can import their own settings but not over-write the operational settings for the organisation that he's starting to work for.

(And allow sentences ending on prepositions, please.)

**Comment by raydleemsc** [comment]
Call it a titanic issue - syncing

**Comment by sandy081** [comment]
/duplicate

It seems you have multiple requests which are platform specific settings and profiles - issues already exist for each of these.
