### ISSUE TITLE
한글로 번역해주세요.

### ISSUE THREAD

**Issue by minna0723** [microsoft/vscode#132993]
Issue Type: <b>Feature Request</b>

작성한 코드에 마우스를 올릴시 설명이 영문으로 나옵니다 한국어로 수정해 주세요.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by lramos15** [comment]
Google Translate: When you mouse over the written code, the description appears in English. Please correct it in Korean.

**Comment by IllusionMH** [comment]
I think screenshots with examples will be helpful. Otherwise it's hard to tell problem is with language pack or it's docs picked from code/definitions that will be displayed as is.
