### ISSUE TITLE
change the color of the highlighted text in the terminal.

### ISSUE THREAD

**Issue by refresko1** [microsoft/vscode#132920]
Hello gentlemen, I want to suggest (or ask where it can be customized), the color of the highlighted text in the terminal.

With the option "minimap.findMatchHighlight" I can change it in the minimap and with the option "editor.findMatchBackground" I can customize that option in the main editor section

but how can I do it to change the color in the words found in the terminal?

Thanks

**Comment by ArturoDent** [comment]
An issue to change the background color of find matches in the terminal: https://github.com/microsoft/vscode/issues/110339

The actual find text color appears to be themeable with:

` "terminal.selectionBackground": "#e5ff00",`  rather non-intuitively.

**Comment by refresko1** [comment]
> An issue to change the background color of find matches in the terminal: #110339
> 
> The actual find text color appears to be themeable with:
> 
> ` "terminal.selectionBackground": "#e5ff00",` rather non-intuitively.

is exactly what I was looking for, indeed,

Thank you so much
