### ISSUE TITLE
Changing selected launch configuration is not regarded when application is already running

### ISSUE THREAD

**Issue by codewithpassion** [Microsoft/vscode#13296]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Have more than one launch configuration ('Config A', 'Config B')
2. Start application debug/run with 'Config A'
3. Change launch configuration to 'Config B' while application is still running under config A
4. Stop application via stop button
5. (Drop down sais 'Config B')
6. Start debugging
7. 'Config A' is started and drop down changes to 'Config A'
8. Expected behaviour: 'Config B' is started

**Comment by isidorn** [comment]
This has been fixed in the latest vscode release which will be out some time this week.
It is also fixed in the vscode insiders
