### ISSUE TITLE
Run and Debug showing duplicate environment names for selection

### ISSUE THREAD

**Issue by hadayovi** [microsoft/vscode#132932]
![image](https://user-images.githubusercontent.com/90535896/132967287-fd47cd00-a2c0-4716-b3f8-c2d3d430463e.png)

Duplicate? I don't know, supposedly it was "fixed" but apparently not quite. 
https://github.com/microsoft/vscode/issues/121148#issue-comment-box

Does this issue occur when all extensions are disabled? Yes

- VS Code Version: Just auto-updated, 1.60.0
- OS Version: Windows 10 Pro 21H1

![image](https://user-images.githubusercontent.com/90535896/132967308-ee2341ae-abde-455f-b36b-ee64229eee9d.png)

Steps to Reproduce:

1. Click the Run and Debug tab on the left of VS Code.
2. Click the blue Run and Debug button inside of the panel.
3. Notice that a search box pops up at the top, and shows duplicated environment names as suggestions (?). I can't tell which to of the duplicates to click.

**Comment by maiux** [comment]
Same problem here on macOS Big Sur, running:
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
![image](https://user-images.githubusercontent.com/278691/132997000-0e6d2a08-2e48-41f4-8395-374e1f3cb410.png)

**Comment by roblourens** [comment]
Hey @connor4312 this comes from having js-debug register its debug adapters twice, with and without pwa-. Would it make sense to remove the `languages` property from the `pwa-` DAs?

**Comment by hadayovi** [comment]
Note that I'm not coding a PWA, just a local Node.js app only for personal computer use. I don't know if it's relevant for me to say that, but I'm doing very little with VS Code at this time.

**Comment by bogekt** [comment]
I have the same issue
<img width="1144" alt="Screenshot 2021-09-22 at 17 39 23" src="https://user-images.githubusercontent.com/1389210/134364899-4b8f8de6-dd60-4c76-bc82-909da2eb12e8.png">


Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by ramonmata** [comment]
It is happening to me too with latest version:

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0


Tried removing all things from Library and the .vscode from my home folder.
Then launch vscode without signing or installing any extensions.


I see the same duplicated list
