### ISSUE TITLE
Javascript debug terminal use powershell instead of default profile after 1.60

### ISSUE THREAD

**Issue by Blafy** [microsoft/vscode#132987]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: Windows 10 20H2

Steps to Reproduce:

After the update, without touching any of my VS code settings, starting a new Javascript Script Terminal will open a Powershell console, when it was a Git bash terminal (my default profile) in older versions of VS code.

- Adding `terminal.integrated.automationShell.windows` to "C:\\Program Files\\Git\\git-bash.exe" does not resolve this issue.
- Adding a new lauch.json file in my application .vscode with `"console": "integratedTerminal"` doesn't work either

How do I set the default shell for automated tasks and launches to Git Bash ?

**Comment by albertosantini** [comment]
See #132150. It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.

**Comment by Blafy** [comment]
Closing the issue, although the other issues are about the default terminal, this one is about the debug terminaL      
Either way, this kind of bug should not make it in a stable release,
