### ISSUE TITLE
Make enableable features settings consistent and intuitive

### ISSUE THREAD

**Issue by KrOstir** [microsoft/vscode#132986]
In the VSC settings some options that can be enabled and disabled contain text Enabled, and some not. Here are examples for the Hover.

```
"editor.hover.enabled": true
```

Is displayed as `Hover: Enabled`.

```
"editor.hover.sticky": true
```

Is displayed as `Hover: Sticky`.

![Code_w80hPDW6Hf](https://user-images.githubusercontent.com/13023733/133085655-f6cedb80-08c7-4737-ae18-025056a3f1ba.png)

Checkmark is intuitive and there is no need write `: Enabled`. This might be even confusing - does `Hover: Enabled` mean that the setting is enabled?

**Comment by roblourens** [comment]
Valid feedback. One thing that we aim for is a close correspondence between what you see in the GUI, and the "actual" JSON version of the setting, meaning that I don't want to give it a different title or display. That might change in the future though. Also where we use "enabled" usually refers to turning an entire feature on or off, not just some flag or attribute of it. That's how it's used here.

**Comment by tomByrer** [comment]
> we use "enabled"

Could another word be used instead?  Or maybe better UX to not have the sub-feature text be bolder than the feature name?

**Comment by KrOstir** [comment]
> > we use "enabled"
> 
> Could another word be used instead? Or maybe better UX to not have the sub-feature text be bolder than the feature name?

I agree. `Enabled` is bold, suggesting that it is more important than the feature name. `Enable` and not bold is more intuitive to me.

**Comment by roblourens** [comment]
We use "enable" for some settings, "enabled" for others, it would be better to be consistent but changing setting keys is a pain so I'm not going to fix it. And I think that when you are looking at a bunch of settings in the same category, which is a common way to browse them, then the last segment is the most important.
