### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by akashshyamdev** [microsoft/vscode#132938]
I get this error sometimes(not always) when running webpack. It's like the server is running and i'm coding for an hour and this happens:
![Screenshot 2021-09-12 at 12 04 21](https://user-images.githubusercontent.com/56759828/132975238-45f1a953-0a4c-431a-8cf2-05d2118447f9.png)

I don't have other details, as this is not a recurring issue. Based on [this](https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas) SO post, there seems to be a memory leak. My Mac has 8Gb ram so I'm not sure how much I should allocate to NodeJS.

Here's details about OS and vscode:
OS: Mac OS Big Sur 11.5.2
Vs Code: 1.60.0

I apologize that I can't be of more help, looking forward to hearing your reply.

**Comment by IllusionMH** [comment]
> when running webpack

Could you please clarify how it is related to VS Code editor itself? Looks like issue with Webpack and not VS Code

**Comment by akashshyamdev** [comment]
@IllusionMH I don't think it is an issue with webpack, the heap problems are related to vs code and the setup works slow but fine in webstorm.

**Comment by IllusionMH** [comment]
On screenshot there are no paths that are related to VS Code - node is launched. And it it's "memory leak" it's in running app -webpack, not in host app.

Also not clear how you launch it with VS Code: it's task, extension action, just in integrated terminal etc. More info is still needed.
