### ISSUE TITLE
Git checkout should create a tracking branch, if any remote contains a matching branch

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1329]
Currently when you use quick open to "git checkout branch", the branch will be created even if the branch already exists in the remote. The command line does a better job and connects to the existing branch in that case.

**Comment by kelchm** [comment]
This is related to #3385.  Definitely confusing behavior that will trip people up.

**Comment by joaomoreno** [comment]
Closing as duplicate of #3385
