### ISSUE TITLE
Disable CTRL auto open on quickOpenNavigate

### ISSUE THREAD

**Issue by milosavljevicoa** [microsoft/vscode#132911]
Hi everyone,

Here is feature request: I would like to have the option to disable `ctrl` for auto opening inside quick open.

I know that this is intended behavior but I don't find it useful, here is the reason why:

I have the following key bindings 
```
{
   "command": "workbench.action.quickOpenNavigateNext",
   "key": "ctrl+n",
   "when": "inQuickOpen"
},
{
   "command": "workbench.action.quickOpenNavigatePrevious",
   "key": "ctrl+p",
   "when": "inQuickOpen"
},
``` 

Example of workflow: I initiate quick open navigate few entries (with the key bindings specified above) then I would like to narrow down my search with some text (pattern), this will not be possible since releasing `ctrl` opens the selected entry.

**Comment by TylerLeonhardt** [comment]
merging with https://github.com/microsoft/vscode/issues/98479
