### ISSUE TITLE
Shell use Git Bash default, but always show the powershell first

### ISSUE THREAD

**Issue by XKF** [microsoft/vscode#132958]
You can see this situation when you open the terminal

**Comment by XKF** [comment]
This phenomenon appeared in version 1.60

**Comment by AlexanderMaslov** [comment]
confirm. Some problem

**Comment by AtheS21** [comment]
Same problem, default shell profile is set to Command Prompt (cmd.exe) but powershell is always used when starting visual code. When I create a new terminal, it does create a cmd terminal though

Also the python debug console always uses powershell when set the console option to "integratedTerminal" in launch.json

**Comment by IllusionMH** [comment]
/duplicate of #132150

It's a bug which is already fixed in Insiders build and supposed to be in upcoming Recovery August release.
