### ISSUE TITLE
Enable "Find All References" results list to "Open in editor", like search

### ISSUE THREAD

**Issue by Xuerian** [microsoft/vscode#132956]
It's very convenient with search results to have extra context without jumping from result to result.

I think it would also be useful for Find All References to have similar functionality, for example when a function call is broken up into multiple lines for readability.

Alternately, supporting more context in the result tree could help too.

**Comment by jrieken** [comment]
there is https://marketplace.visualstudio.com/items?itemName=jrieken.references-plusplus and likely other extensions for that

**Comment by Xuerian** [comment]
> there is https://marketplace.visualstudio.com/items?itemName=jrieken.references-plusplus and likely other extensions for that

Awesome! Thank you! I should have searched extensions as well.

**Comment by Xuerian** [comment]
And I made that comment without checking.

https://github.com/microsoft/vscode-extension-samples/issues/189

The extension seems to have been (partly) broken for a while. And I wasn't able to find any other extensions providing similar functionality.

**Comment by jrieken** [comment]
> The extension seems to have been (partly) broken for a while.

Broken how?

**Comment by Xuerian** [comment]
> > The extension seems to have been (partly) broken for a while.
> 
> Broken how?

It opens an editor showing simply, for example, "Found 6 references". It's done that every time I've used it, but others in the above microsoft/vscode-extension-samples#189 thread seemed to indicate it was intermittent.
