### ISSUE TITLE
I want to use MSVC in vscode,but  `Passthrough is not supported, GL is disabled` alerted

### ISSUE THREAD

**Issue by MisakawaConan** [microsoft/vscode#132966]
Issue Type: <b>Bug</b>

i have installed the visual studio 2019 community,
and i want to use msvc in vs code
so i open the Develper command prompt for vs 2019
type `cd D:/workspace/emptyfolder`and `code . `
so something alerted as followed

[main 2021-09-13T05:17:01.461Z]update#setState idle
[main 2021-09-13T05:17:31.465Z] update#setState checking for updates
[main 2021-09-13T05:17:31.586Z] update#setState idle
[52964:0913/131901.311:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.38GB free)|
|Process Argv|D:\\MicrosoftVScode\\Microsoft VS Code\\bin\\..\\resources\\app\\out\\cli.js . --crash-reporter-id 964bad23-09e5-4726-8d74-b4ac550abe7b|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.2.0
vscode-svgviewer|css|2.0.0
vscode-html-css|ecm|1.10.2
json-tools|eri|1.0.2
code-runner|for|0.11.5
gitee|g8u|0.0.7
go|gol|0.27.2
haskell|has|1.6.1
vscode-drawio|hed|1.6.2
beautify|Hoo|1.5.0
vue|jcb|0.1.5
svg|joc|1.4.9
language-haskell|jus|3.4.0
vscode-leetcode|Lee|0.18.0
vscode-clangd|llv|0.1.13
vscode-language-pack-zh-hans|MS-|1.60.3
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
vetur|oct|0.34.1
java|red|0.81.0
scala|sca|0.5.4
open-in-browser|tec|2.0.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by lramos15** [comment]
Not sure I understand the use case? Are you trying to use the Visual Studio terminal to open VS Code?
