### ISSUE TITLE
not possible to use VScode from another linux user

### ISSUE THREAD

**Issue by ka223** [microsoft/vscode#132924]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code-stable-x64-1630494605.tar.gz
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. switch to another user with 
  xhost +local:
  su otherUser
2. unpack tar archiv
3. start with ./code

Error at startup:
```
Visual Studio Code

Unable to write program user data.

A system error occurred (listen EACCES: permission denied /run/user/1002/-vscode-***1.60.0-main.sock)

Please make sure the followring directories are writable:
~/.config/code
~/.vscode/extensions
/run/user/1002
```

The user is 1002 is my current user, but I am using the program with another user / id.
VScode is using the wrong ID, other programs have no problem if they are started as a different user.

**Comment by aeschli** [comment]
Did you make sure the new user has the permissions to open the listed folders?

**Comment by ka223** [comment]
Shure, but in my usecase, the otherUser has userID 1006, my logged in user is 1002.

VScode is using the wrong directory, I think it should be "/run/user/1006".
Of course, otherUser has no access to "/run/user/1002".

**Comment by joaomoreno** [comment]
> It is recommended to always use the --login option (instead of its shortcut -) to avoid side effects caused by mixing environments.

https://man7.org/linux/man-pages/man1/su.1.html

**Comment by ka223** [comment]
> > It is recommended to always use the --login option (instead of its shortcut -) to avoid side effects caused by mixing environments.
> 
> https://man7.org/linux/man-pages/man1/su.1.html

But with `su --login otherUser`, here is another problem:
```
ERROR:browser_main_loop.cc(1301)] Unable to open X display.
The futex facility returned an unexpected error code.
Aborted (core dumped)
```
