### ISSUE TITLE
Feature request: add option to remove context item "Learn more about JS/TS refactorings"

### ISSUE THREAD

**Issue by favna** [microsoft/vscode#132943]
This is a revival of closed issue #121374 which didn't get 20 community upvotes within 60 days. I want to give it another push as it came extremely close.

----

There should be an option to remove this action item:

![image](https://user-images.githubusercontent.com/4019718/132986804-dfcdcc81-12d3-4cd5-8e86-9efbc5b3b278.png)

There is a time in the life of a TypeScript developer where they no longer need this tutorial hint every single time they want to apply a code action. In fact, it's getting in the way when navigating the menu. It's rather extremely annoying, and I often find myself accidentally selecting it.

It would be beneficial to be able to disable such onboarding elements.

**Comment by mjbvz** [comment]
With the new code action menu, this item is no longer part of the normal list so arrowing through items will not select it (you can tab to it if you want to access it using the keyboard)
