### ISSUE TITLE
文件git暂存后，文件选中高亮已更换文件，但是主窗口内容还是旧文件内容

### ISSUE THREAD

**Issue by HelloDBA** [microsoft/vscode#132970]
Issue Type: <b>Bug</b>

第一步：修改两个文件；
第二步：在源代码管理标签下，点击排在上面的第一个文件，左侧主窗口分两栏显示文件更改前后的差异；
第三步：点击+号，暂存该文件，高亮文件选中下第二个文件，左侧主窗口还是显示之前的第一个文件；

到第三步预期左侧主窗口应该显示第二个文件的更改前后差异。

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (6.71GB free)|
|Process Argv|D:\\FescoSolution\\FescoERP\\FescoERP.Api --crash-reporter-id 440f32aa-04a1-4bbb-ac4e-528fc9370878|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
vscode-language-pack-zh-hans|MS-|1.60.3
csharp|ms-|1.23.15
debugger-for-edge|msj|1.0.15
vetur|oct|0.34.1
vs-code-prettier-eslint|rve|3.0.4
vscode-counter|uct|2.3.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by kkocdko** [comment]
A clearer version of description, not fully same:
1. Open a folder with git inited.
2. Modify two files, switch to `Source Control` panel.
3. Select the first item, editor shows diff content.
4. Click `+` button to stage file, the focus will turn to second (not be staged) file, but editor still displays the first file's content
---
These UI bug about focus and async tasks seems happen again and again, like https://github.com/microsoft/vscode/issues/102498.

**Comment by rchiodo** [comment]
Author closed the bug, assuming verified.
