### ISSUE TITLE
Unable to open VS Code 1.5 with "-g" option on Windows

### ISSUE THREAD

**Issue by lukaszunity** [Microsoft/vscode#13290]
- VSCode Version: 1.5.3
- OS Version: Windows 8.1

Steps to Reproduce:

1. Run: Code.exe -r -g "C:\Users\Lukasz\Desktop\Projects\Shooter\Assets\Done\Done_Scripts\Done_BGScroller.cs":1
2. Notice error message and that VS Code window does not show.
`Arguments in ``--goto`` mode should be in the format of ``FILE(:LINE(:COLUMN))``.`

Also does not work without quotes around filename.

This worked correctly in VS Code 1.4. This is blocking Unity 5.5 from opening VS Code 1.5 on Windows.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by tf2manu994** [comment]
The code that does this appears to be here: 

https://github.com/Microsoft/vscode/blob/4a87145e2c1b7b86bd9f7cc8ae58012c0215a44a/src/vs/platform/environment/node/argv.ts#L77-L83 and the regex doesn't match his reproduce steps.

While I am not the OP, I tried running the insiders build and passing it the goto argument with the same (swapped out username, though), and it didn't work.

The part of the regex that I think is broken is that it is looking for a C:\ at the beginning, and not finding it.

The regex matches `C:\Users\test\foo_bar\Done_BGScroller.cs":1`, but does not match `"C:\Users\test\foo_bar\Done_BGScroller.cs":1`.

Hope this helps :)

**Comment by bpasero** [comment]
I asked for 1.6 because we fixed a bug here for 1.6, but there could well be more bugs around the regex.

**Comment by lukaszunity** [comment]
I've verified that this issue is fixed in the nightly insiders build.
