### ISSUE TITLE
Allow to specify formatter when invoking `editor.action.formatSelection` 

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#132990]
There is the command "Format Selection With..." that allows to use a non-default formatter: It shows a list of all available formatters and formats the selection with the selected one.

I think there are situations where it makes sense to bind this command to a keyboard shortcut.

In this case, it would be very handy if the formatter to use could be set as argument in the keyboard shortcut, so the formatter does not have to be selected every time.
That way, when using multiple formatters at the same time, different shortcuts can trigger different formatters.

Something like this could work nicely:
```json
{
    "key": "ctrl+shift+alt+f",
    "command": "editor.action.formatDocument",
    "args": {
      "formatter": "prettier"
    }
},
```

I propose to support some `formatter` argument, I'm also open to implement this feature.

In my case, it turns out that Prettier can even be very useful (and non-destructive) when prettier is not setup as default formatter (the default formatter is configured to not be Prettier and I cannot change that). It would be nice to support this use-case.

What do you think?

(edit: Rephrased the feature request)

**Comment by jrieken** [comment]
> However, the default formatter is configured to not be Prettier and I cannot change that.

If you cannot change that than it is a strong signal that shouldn't be using it
