### ISSUE TITLE
having a word "switch" in c# variable name breaks keyword highlighting

### ISSUE THREAD

**Issue by spajus** [microsoft/vscode#132917]
Issue Type: <b>Bug</b>

Demo:
![image](https://user-images.githubusercontent.com/70706/132950090-66822e50-78fb-413c-b3e0-87222f8a44f8.png)

Create a c# file with this class:
```csharp
    public class Test {
        private bool switchMode;
        public int TestMode() {
            if (switchMode) {
                return 1;
            }
            return 2;
        }

        public int TestMode2(bool input) {
            if (input) {
                return 1;
            }
            return 2;
        }
    }
```
It appears to be breaking github's highlighting too :)

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.21GB free)|
|Process Argv|--disable-features=CalculateNativeWinOcclusion --crash-reporter-id 8fb0ef7a-4d32-4f17-88ff-5b2f95ae1f11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.2.8
gitlens|eam|11.6.0
todo-tree|Gru|0.0.213
blender-development|Jac|0.0.16
csharp|ms-|1.23.15
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
unity-debug|Uni|3.0.2
vim|vsc|1.21.7

</details>

**Comment by alexr00** [comment]
@spajus the fix is already available in VS Code insiders and will be in the next stable release.
