### ISSUE TITLE
`vscode.workspace.fs` error reporting is weird

### ISSUE THREAD

**Issue by lnicola** [microsoft/vscode#132981]
- VS Code Version: 1.60.0
- OS Version: Linux

Steps to Reproduce:

If you invoke `vscode.workspace.fs.rename` on a non-existing file it returns `code` set to `Unknown` (instead of `EntryNotFound`) and `name` set to `EntryNotFound (FileSystemError) (FileSystemError)`.

See https://github.com/rust-analyzer/rust-analyzer/pull/10222.

**Comment by jrieken** [comment]
@bpasero on the renderer side there is [handling]([instanceof](https://github.com/microsoft/vscode/blob/c4546485f006e5676ddb3221e1b4d98a651c0d6d/src/vs/workbench/api/browser/mainThreadFileSystem.ts#L127-L127)) for `FileOperationError`-errors but it seems that rename (and maybe others) don't return instances of that error. Can you clarify?

<img width="639" alt="Screen Shot 2021-09-21 at 16 33 36" src="https://user-images.githubusercontent.com/1794099/134190797-69f10836-4652-48e5-9261-246bed128fe1.png">

**Comment by bpasero** [comment]
@jrieken that code seems to originate from https://github.com/microsoft/vscode/commit/a4fc9bb8c4cf7e2d0d09afb08bc46750c386cfbb#diff-846607570366635cf48c9895c277d0f8d4750266100d285fe4b46f3e197ec49cR103 maybe before we had more specific error codes for rename and forgot to update? I don't see a reason why we cannot update that list. 

Isn't this also somewhat API'ish that should appear in the API docs for the expected error codes that can happen when using the vscode fs API?

**Comment by jrieken** [comment]
I know where the code is coming from 😄  What I am saying is that it was likely working when it was written, esp. `instanceof FileOperationError`. Now I wonder what the expected error type for file service operations is. Is there no more specific instance of `Error`?

**Comment by bpasero** [comment]
@jrieken yeah, I do not really remember but some of the errors from `IFileService` are just `Error` or `FileSystemProviderError`. I think I only ensure `FileOperationError` when any of these error kinds applies:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/files/common/files.ts#L1032-L1045

If there is a case missing that we have a `FileSystemProviderErrorCode` for then we need to add that.

**Comment by jrieken** [comment]
I believe [toFileSystemProviderErrorCode](https://github.com/microsoft/vscode/blob/33c149f3ad49db462cb451f4db2e01d64b15e40b/src/vs/platform/files/common/files.ts#L526-L526) is what I need
