### ISSUE TITLE
Slow WSL remote terminal 

### ISSUE THREAD

**Issue by Kaify** [microsoft/vscode#132950]
Issue Type: <b>Bug</b>

I use WSL ubuntu 18.04 which has been integrated with VSCode via WSL extension, so when I open VSCode with WSL remote, and use terminal to type in command there is significant amount of delay, suppose I press up to bring the last executed command, and now I have to edit it, it blinks like 5 secs or more then reflect where the cursor has actually reached, way too slow to be used.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.46GB free)|
|Process Argv|--crash-reporter-id fe04f98d-59a5-4134-a7ce-69abcd85306d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|Memory (System)|7.81GB (1.46GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
vscode-yaml-sort|Pas|5.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224:30358039
vssid140:30363603

```

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by Kaify** [comment]
> Can you share your settings.json file?

Could you please confirm which settings.json you are referring to and where would I find it?
