### ISSUE TITLE
Files starting with a '.' are out of order

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#13298]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Just a small bug, nothing huge, but some files are out of order.

![vscode-file-order](https://cloud.githubusercontent.com/assets/1571806/19159429/1744f29a-8bb2-11e6-9dd6-d990de58b9b5.PNG)

In the above image, `.env.example` should be after `.env`.

Here is what it looks like in the windows explorer:

![explorer-file-order](https://cloud.githubusercontent.com/assets/1571806/19159494/584a3b42-8bb2-11e6-9934-b043f66a7183.PNG)

**Comment by Tyriar** [comment]
Can reproduce on Ubuntu 16.04 1.6.0-insider @ 602155bb781f509c7a4ddcd700b57cb9b9f5286d

**Comment by bpasero** [comment]
This was introduced for the changesViewer and only later for the explorer, so a fix should go into there. Ping pong to @joaomoreno
