### ISSUE TITLE
regarding node js programmes

### ISSUE THREAD

**Issue by Princepandey22** [microsoft/vscode#132905]
Issue Type: <b>Feature Request</b>

hello sir/mam
from last two days i am unable to use node js programmes in vs code i've successfully installed node js and all its extensions but whatever i do not even a single node js progarmmes is running in vs cod eit is showing module not found error please help me sir 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by himrd95** [comment]
What is the node version you have installed?
