### ISSUE TITLE
Visual Studio freeze after start

### ISSUE THREAD

**Issue by yazhubal** [Microsoft/vscode#13293]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. 
![2016-10-06 14_14_45-program manager](https://cloud.githubusercontent.com/assets/9074776/19151841/4c2ba040-8bcf-11e6-896e-830f478654a4.png)

2. No reaction --> Reopen and Keep Waiting
3. I can use top menu, but no reaction after choosing any options.

**Comment by tf2manu994** [comment]
What extensions do you have installed?

I had a similar problem when I had an extension that looks for css class names in the working tree, and my working tree contained a node_modules folder with about 400 items.

**Comment by yazhubal** [comment]
@tf2manu994 - 
Visual Studio runs for me only when i use RMB on VS icon (on the taskbar) and choose New Window option. 
Below screen from my extension pannel:
![extensions](https://cloud.githubusercontent.com/assets/9074776/19153570/61c74c94-8bd7-11e6-97a8-32915a623fc0.png)

**Comment by tf2manu994** [comment]
Odd, I have the exact same extensions installed, and then some, but I don't have this problem.

**Comment by yazhubal** [comment]
@tf2manu994 - after few mintues of testing: 
i deleted all files and project folders, then clone all in new folder, now it works fine O_o 
😂

**Comment by Tyriar** [comment]
Going to close this off since there's no reliable repro, comment if you see if again
