### ISSUE TITLE
Need an option for the terminal on focus to take higher priority for keyboard shortcuts

### ISSUE THREAD

**Issue by playgithub** [microsoft/vscode#132937]
## Case with problem
When the integrated termianl is on focus, `Ctrl+p` is intended to show the previous command in the terminal, but vscode pops up a dialog for searching. There mgiht be other shortcuts works the same way unexpectedly.

**Comment by IllusionMH** [comment]
/question

It it intended as <kbd>Ctr</kbd>+<kbd>P</kbd> is crucial part of VS Code workflow and useful even when you are in terminal.

Therefore VS Code provides `terminal.integrated.commandsToSkipShell` to configure which shortcuts will be intercepted by VS Code and settings descriptions speaks exactly about <kbd>Ctr</kbd>+<kbd>P</kbd>. Please see setting description in VS Code and [Keybindings and the shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_keybindings-and-the-shell)

**Comment by playgithub** [comment]
`"terminal.integrated.sendKeybindingsToShell": true` works as expected

Thanks
