### ISSUE TITLE
Format Selection right-click menu is gone

### ISSUE THREAD

**Issue by ErlendKH** [microsoft/vscode#132946]
Issue Type: <b>Bug</b>

Hello,

My name is Erlend Haartveit and I love to use VS Code for C#. I think there's been an update some days ago, because when I use it now, I have very limited options in my right-click menu: Kite, Change all Occurrences, Run/Debug Tests in Context, Cut/Copy/Paste and Command Palette.

I'm no expert so I have been struggling with re-enabling the "Format Selection/Document" functionality. I've assign and tried their hotkeys (CTRL + ALT + F, SHIFT + ALT + F, CTRL + K, CTRL + F), but nothing happens. What I basically want to do is to select some code and format its indentation automatically, rather than doing it manually which is very time-consuming.

Best regards,
Erlend Haartveit

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.88GB free)|
|Process Argv|--crash-reporter-id 85f60533-1179-497e-b253-a216fd93559e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.147.0
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.15
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by jrieken** [comment]
> What I basically want to do is to select some code and format its indentation automatically, rather than doing it manually which is very time-consuming.

I assume c# source files, right? Do other c# features, like IntelliSense or Outline, work?

**Comment by ErlendKH** [comment]
Hello jrieken,

Hm, not sure how to test that. However, the popup menu on right-click always had the formatting option while working on C# scripts in Unity until recently.

[Here is a screenshot of how the menu looks like now](https://tinyimg.io/i/k978NGM.png).

[It also seems like the autocomplete doesn't work as the variable types don't show](https://tinyimg.io/i/VgdjYmh.png).

**Comment by ErlendKH** [comment]
Hello, still would like to know how to fix it?
