### ISSUE TITLE
[BUG]  VSCode crashes on drop and drop of 'View Problem' button

### ISSUE THREAD

**Issue by ayushsharma82** [microsoft/vscode#132989]
![image](https://user-images.githubusercontent.com/26592968/133089568-1ba1d13c-5b8e-4659-a93e-f43d706f5dff.png)

All instances for VSCode become unresponsive & crash when we drag and drop the 'View Problem' button from error popup. ( did that accidentally )

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: 10.0.1.19043

**Comment by bpasero** [comment]
Are you running as admin maybe?

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
