### ISSUE TITLE
Change PR template

### ISSUE THREAD

**Issue by Genius398** [microsoft/vscode#132947]
Change PR template

**Comment by IllusionMH** [comment]
On what?

**Comment by Genius398** [comment]
the current template is too bland

**Comment by Genius398** [comment]
> On what? Haven't seen discussions or proposals before

the current template is too bland

**Comment by CodeCrazy-ywt** [comment]
> 
> 
> 
> 
> 
> Change PR template

so what do you think the pr template should be like? Why do you think it's too bland?
