### ISSUE TITLE
How to open previewHtml as popup in vscode editor

### ISSUE THREAD

**Issue by Sujay-shetty** [Microsoft/vscode#13291]
- VSCode Version: *
- OS Version: *

Hi,
I want to open an previewHtml as popup window in vscode editor.
When popup is active background pages(either workspace , window, editor etc...) cannot be selectable.

Is there any API available or any other way of opening a popup in vscode.

@jrieken 
@bpasero

**Comment by jrieken** [comment]
This is not possible as we don't support model pop up dialogs or UX extensibility. Why that is we have tried to explain here: https://code.visualstudio.com/docs/extensions/our-approach

**Comment by Sujay-shetty** [comment]
Did you people planning for UI APIs in the future ? if yes, when?
