### ISSUE TITLE
Evaluate zero-copy transfer of ArrayBuffers to and from webviews

### ISSUE THREAD

**Issue by safasofuoglu** [microsoft/vscode#132962]
After reading and running https://github.com/microsoft/vscode/issues/115807:

In `extHostWebviewMessaging.ts`, `deserializeWebviewMessage` seems to duplicate the underlying memory of the VSBuffer. Is that really necessary? If that copy could be avoided, I believe a (interior-mutable) reference could just be passed to an arraybuffer that is completely managed on the extension side, making instant communication possible.

@mjbvz @Tyriar

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/116715#issuecomment-916914472

**Comment by mjbvz** [comment]
We are transferring the data between distinct processes and not just between separate browsers contexts

Let us know if you believe we can avoid these copies
