### ISSUE TITLE
visulizing file changes in commits before pulling changes

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#132977]
When using the VSC built-in source control UI, it would be extremely useful to be able to visualize the changes to files before pulling a commit. The workflow would be:
"fetch (+flags)" -> list of commits to pull -> click on commit -> visulize file changes in that commit in the same way changes can be visualized when staging changes for a commit

This can already be done in software such as sublime merge:

![image](https://user-images.githubusercontent.com/74593034/133066283-15a62f02-f45b-4429-902a-96e0d91e7917.png)

**Comment by ghylander** [comment]
t has come to my attention that a marketplace plugin adds this functionality, although a better integration into VS would be preferred. The pluign is laborious to work with.

https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

**Comment by eamodio** [comment]
That feature is provided by GitLens, please feel free to open a feature request with the changes you would like on it's repository.
