### ISSUE TITLE
choiceService warning when installing extension via CLI

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13299]
- VSCode Version: Code - Insiders 1.6.0-insider (602155bb781f509c7a4ddcd700b57cb9b9f5286d, 2016-10-01T00:34:33.697Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

```
❯ code-insiders --install-extension Tyriar.theme-glacier                                                    
[createInstance] extensionManagementService depends on choiceService which is NOT registered.               
Extension 'Tyriar.theme-glacier' is already installed.
```

**Comment by joaomoreno** [comment]
@sandy081 We need a choice service implementation working in the command line only, for the CLI process. 👍

**Comment by joaomoreno** [comment]
For verification: make sure this works fine on Windows, where stdin is usually an issue.

**Comment by sandy081** [comment]
Sure 👍
