### ISSUE TITLE
Debugger is not closing while re-running launch.json

### ISSUE THREAD

**Issue by dwarakanath-rao** [microsoft/vscode#132997]
DebugServer: Moving selected files to staging area
DebugServer: Adding stop statements for active breakpoints
DebugServer: Creating zip archive from project sources
DebugServer: Connecting to Roku via telnet at 192.168.2.2
DebugServer: Exiting any active brightscript debugger

That's it. It never moves forward. If we try to launch the telnet, it shows already in use. I guess some issues with the latest update. Please resolve ASAP.

**Comment by roblourens** [comment]
I need some more information about what you are doing. Did you stop running the previous instance?

**Comment by dwarakanath-rao** [comment]
> I need some more information about what you are doing. Did you stop running the previous instance?

Hi @roblourens,
I tried to stop the previous instance but didn't work. I tried after restarting my computer and run. It works for the first time but from the 2nd iteration the same issue continues. It seems, in the version 1.60 somehow the previous instance is not getting terminated.
I downgraded the version to 1.59, where everything seems working fine.

Thank you for your revert!

**Comment by roblourens** [comment]
Thanks for the details, I need to know exactly what you are doing and what you see. If you can share the project for me to try to reproduce the issue, that would be best. What language are you using?

So you click the stop button? What happens, does the debug session end? Do you see your program's process still running?
