### ISSUE TITLE
Терминал

### ISSUE THREAD

**Issue by sarnor** [microsoft/vscode#132933]
Issue Type: <b>Bug</b>

Terminal problem. I have the GitBash terminal selected by default. If I close VSCode and reopen it with the embedded terminal running, it opens PowerShell instead of GitBash. Also, if I try to open some project in explorer with the context menu to open in the built-in terminal, it opens PowerShell. GitBash opens only if I use the hot keys " CTRL + ` ".

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4360 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.01GB free)|
|Process Argv|--crash-reporter-id bb5e77be-9dcd-42a8-85d0-3709323145fc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
Bookmarks|ale|13.2.1
angular1-code-snippets|ale|0.0.3
turbo-console-log|Cha|2.1.6
open-html-in-browser|cod|0.1.21
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.25
vscode-html-css|ecm|1.10.2
beautify|Hoo|1.5.0
autofilename|Jer|0.1.3
svg|joc|1.4.9
vscode-gist|ken|3.0.3
vscode-language-pack-ru|MS-|1.60.3
indent-rainbow|ode|8.0.0
material-icon-theme|PKi|4.10.0
filenamecomplete|qin|0.0.3
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.8.18
ayu|tea|1.0.5
highlight-matching-tag|vin|0.10.1
markdown-pdf|yza|1.4.4
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.11.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by vBread** [comment]
Translation from [DeepL](https://www.deepl.com/en/translator):

> Terminal problem. I have the GitBash terminal selected by default. If I close VSCode and reopen it with the embedded terminal running, it opens PowerShell instead of GitBash. Also, if I try to open some project in explorer with the context menu to open in the built-in terminal, it opens PowerShell. GitBash opens only if I use the hot keys " CTRL + ` ".

**Comment by jbussmann** [comment]
You can try Insiders build https://code.visualstudio.com/insiders/ where fixes are in place. Recivery 1.60.1 currently planed for Monday if nothing else delay it. [#132150 (comment)](https://github.com/microsoft/vscode/issues/132150#issuecomment-917023548)

**Comment by vBread** [comment]
Translation from [DeepL](https://www.deepl.com/translator):

> Вы можете попробовать сборку Insiders [code.visualstudio.com/insiders](https://code.visualstudio.com/insiders/), в которой уже есть исправления. Восстановление 1.60.1 в настоящее время запланировано на понедельник, и если ничего другого нет, отложите его. [#132150 (комментарий)](https://github.com/microsoft/vscode/issues/132150#issuecomment-917023548)
