### ISSUE TITLE
[json] accept an alternate schema for a given location in $schema property.

### ISSUE THREAD

**Issue by micro-nirawat** [microsoft/vscode#132999]
Currently by specifying schema in the $schema property of JSON files, JSON language server allows to download the schema file and provide JSON validations. 

This is limited if the schema is not publicly available or needs authentication or other possible reasons. See for example, in the following image, the schema cannot be downloaded from the website provided.
![image](https://user-images.githubusercontent.com/89929616/133114889-97debce8-f725-4473-9bea-95501b341fb1.png)

We are requesting a feature, such that an extension can provide an alternate schema for the inaccessible schema location, bundled with the extension. This alternate schema is bundled with the extension.
For example, for the schema present in the screenshot available, i.e. "https://schema.website.net/schemas/1932-01-01/iceModel.json", it can be replaced by a locally present schema and all the language server validations are based on it.

**Comment by aeschli** [comment]
As discussed with @micro-nirawat : closing for now, as an alternative solution has been found.
