### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by apotox** [microsoft/vscode#132976]
Issue Type: <b>Bug</b>

vscode is becoming too slow in my macbook pro

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|. --crash-reporter-id 101f6707-a93e-41c0-8b10-bcf4767f1aca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
vscode-mocha|Com|0.1.1
vscode-eslint|dba|2.1.25
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-jest-runner|fir|0.4.47
copilot|Git|1.4.2635
vscode-pull-request-github|Git|0.30.0
go|gol|0.27.2
Kotlin|mat|1.7.1
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.2.4
mdx|sil|0.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-initializr|vsc|0.7.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by IllusionMH** [comment]
/needsPerfInfo

More details on in which cases it feels slow will be helpful.
Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Please follow guide linked by bot to help identify problem.
