### ISSUE TITLE
Does not "Pin to Start"

### ISSUE THREAD

**Issue by fabfella** [microsoft/vscode#132934]
Hello

I downloaded the latest Windows 10  build (VSCodeUserSetup-x64-1.60.0.exe)  and installed Visual Studio Code. The desktop icon is created , however when I search for "Visual Studio Code" on the Windows 10 Start menu and select the "See more information" arrow alongside it i don't see the option to "Pin to Start".

After trying various ways to do this I have determined that there is no longer a way to Pin the Visual Studio Code to Start menu anymore.
Is this correct?

**Comment by joaomoreno** [comment]
> however when I search for "Visual Studio Code" on the Windows 10 Start menu and select the "See more information" arrow alongside it i don't see the option to "Pin to Start".

Can you show me a screenshot of this?

**Comment by fabfella** [comment]
![Screenshot 2021-09-29 221355](https://user-images.githubusercontent.com/30516481/135239846-c0cf87f1-39f5-4f23-acbf-fb99481e6ab1.png)

**Comment by fabfella** [comment]
![Screenshot 2021-09-29 221602](https://user-images.githubusercontent.com/30516481/135240068-3b35e5ff-7064-4784-acda-09a86b202669.png)

**Comment by fabfella** [comment]
This is Visual Studio 2019 community. Here you can see the "Unpin from Start", because i have already pinned it to the Start.

![Screenshot 2021-09-29 221744](https://user-images.githubusercontent.com/30516481/135240344-a4c12649-5071-40aa-81e6-6b61e11139e9.png)

**Comment by joaomoreno** [comment]
If you choose `Open file location`, where does that point to?

**Comment by fabfella** [comment]
It points to the shortcut on my desktop. I think this was created when i did the install.

**Comment by joaomoreno** [comment]
I see. If you reinstall VS Code, make sure you pick the option to add a shortcut to the Start Menu. Once the installer does that, you should be able to easily pin it.

**Comment by fabfella** [comment]
That did not work as there is no " If you reinstall VS Code, make sure you pick the option to add a shortcut to the Start Menu"

Can you show me what you mean?

![image](https://user-images.githubusercontent.com/30516481/135692997-dd669c83-7671-4be3-b2b7-c521abe249b0.png)

**Comment by joaomoreno** [comment]
Oh I see. We add it by default, without any option. I wonder why Windows is borking the shortcut on your machine, though. I recommend reaching out to Windows support and asking.
