### ISSUE TITLE
[enhancement] Be able to set extension loading order

### ISSUE THREAD

**Issue by tf2manu994** [Microsoft/vscode#13292]
I (and I'm sure many others) have a fair few extensions. My vim emulation extension loads last, as the author's name starts with a V. I have about 30 seconds before this one can launch.

Instead of loading alphabetically, it would be awesome if we could set load order, or at least set one or two to be priority loaded (in a json file or an ini).

I tried renaming the folder to have AAA at the beginning, VSC doesn't update it then (as expected).

**Comment by joaomoreno** [comment]
Loading order is something we don't let extensions have control over.

cc @alexandrudima @jrieken

**Comment by tf2manu994** [comment]
Yep, but could the user have that power? Perhaps in settings.json, the user could provide extensions they wanted loaded first?

**Comment by joaomoreno** [comment]
What is the actual problem you're hitting?
