### ISSUE TITLE
Template literals with substitutions are auto-completed with too many backticks

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#132912]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: MacOS Big Sur

This only started occurring recently.

https://user-images.githubusercontent.com/960753/132944858-116c6db5-1e56-47bf-916f-2f8940c2fab0.mov

**Comment by thebinarysearchtree** [comment]
The problem is that vscode does not have any concept of substitutions at all. The language configuration file has:
`{ "open": "`", "close": "`", "notIn": ["string", "comment"] },`
under the auto-closing pairs section. The way vscode determines whether it is in a string or comment is simply by checking the token before the closing backtick, and returning one of:
`export const enum StandardTokenType {
	Other = 0,
	Comment = 1,
	String = 2,
	RegEx = 4
}`
When a substitution is the last thing before the end of the template literal, it return 'Other', which is not one of the things in "notIn", and therefore auto-closes.

**Comment by hediet** [comment]
This is difficult to solve nicely.

* Because of https://github.com/microsoft/vscode/issues/25658, the backtick does not autoclose, as it touches the word `sql`.
* Because `}` is not a word and not a string-token, the second backtick is autoclosed.

**Comment by thebinarysearchtree** [comment]
This bug also occurs in Python, Ruby, and Swift. It does not occur in PHP, c#, and a couple of other languages. Strangely, those languages report the token type as a string, which makes no sense to me. Either way, this bug is probably not that important compared to the tagged template one. I wouldn't have noticed it if the tagged templates auto-completed.

**Comment by thebinarysearchtree** [comment]
@hediet there is no reason backticks have to be in that fix so taking them out solves the issue and makes this bug less relevant because most people do not remove the end quote when wanting to edit a string.

**Comment by alexr00** [comment]
Verified that in the example the first backtick is autocompleted, so I don't need to add a backtick at the problematic location.
