### ISSUE TITLE
input Chinese shouldn't trigger suggestion when typing

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#132939]
When I typing the Chinese half way, It suggest the code snippets.

![image](https://user-images.githubusercontent.com/41773861/132976938-3797433b-7764-4879-b1a7-02b7c16778f3.png)

**Comment by rebornix** [comment]
@tjx666 may I ask what IME you are using?

**Comment by tjx666** [comment]
@rebornix https://pinyin.sogou.com/mac/

**Comment by tjx666** [comment]
@hediet

**Comment by alexdima** [comment]
@tjx666 Could you please explain in great detail what are the exact keys that you press on the keyboard? I am looking for instructions that are very detailed in order to try to investigate what is going on. Here is an example for the kind of detail I need -- https://github.com/microsoft/vscode/wiki/IME-Test#windows-chinese

**Comment by tjx666** [comment]
System: MacOS 12.0.1

Reproduce:

1. install the Sougo input as describe in https://github.com/microsoft/vscode/wiki/IME-Test#windows-sogou-pinyin-chinese-input-method
2. add following setting
   ```javascript
   "editor.quickSuggestions": {
   "strings": false,
   "comments": true,
   "other": true
   },
   ```
3. open a typescript file, input `//`
4. toggle to Chinese input, press l

![image](https://user-images.githubusercontent.com/41773861/143974522-8987b544-0e07-413c-9290-c7d755fc6a77.png)

**Comment by jrieken** [comment]
@tjx666 I can reproduce but I am a little confused by you saying "macOS" and also referring to windows installation instructions. Anyways, in code I see that suggest is triggered (by cursor movements) although composition is active. That's something we shouldn't do.
