### ISSUE TITLE
Heavy lag making Visual Studio Code unusable

### ISSUE THREAD

**Issue by odragora** [microsoft/vscode#132992]
Issue Type: <b>Bug</b>

macOS Big Sur 11.4, M1 MacBook Pro 16gb RAM.

A few days ago Visual Studio Code started lag so heavily that actions like page scrolling or tab switching take about 30 seconds and queue one after other.

In the macOS Activity Monitor I can see a process sandboxd which takes about 100% of CPU. Neither the system istself no any other apps are affected by this, only VSCode.

If I close my current project nothing changes, the lag still persists.

Around every minute the lag dissapears and then returns again in another minute or so.

If I restart my Mac, the issue goes avay, but retuns after a while. Simply restarting VSCode does not help.

I did not install any new extensions around this time.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 8, 6|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 0ed82087-440f-4809-b645-8a78c87f9efe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
react-pure-to-class-vscode|ang|1.1.8
vscode-apollo|apo|1.19.4
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.1.25
aoe2-rms|del|0.3.3
xml|Dot|2.5.1
gitlens|eam|11.6.0
prettier-vscode|esb|8.1.0
nasc-touchbar|fel|1.12.0
godot-tools|gee|1.1.2
react-component-generator|luk|0.1.0
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
react-proptypes-intellisense|OfH|1.0.3
react-proptypes-generate|sum|1.7.3
tabnine-vscode|Tab|3.4.26
quokka-vscode|Wal|1.0.400
glean|wix|5.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by xiajunwen1007** [comment]
I have the same issue.

**Comment by deepak1556** [comment]
Sorry for the delayed response, can you check if the issue happens with the following exploration build that has a newer runtime.

[macOS universal](https://az764295.vo.msecnd.net/exploration/1ed4b16d638968489596d86fc737e05dd10e052d/VSCode-darwin-universal.zip)

**Comment by xiajunwen1007** [comment]
I found my issue is caused by a too large fontsize in the editor, after change the size,it works quite well. So I think the problem I have is unrelated to this issue. Sorry about the fact that I can not test it.
