### ISSUE TITLE
The window has crashed (reason: 'crashed', code: '-1073741819')

### ISSUE THREAD

**Issue by chr7** [microsoft/vscode#132945]
Issue Type: <b>Bug</b>

Worked with VSC when I left the computer for a break. Returning and unlocking the screen, I was presented with a small window telling that VSC has crashed.

I downgraded VSC from 1.60.0 to 1.59.1 three days ago.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (8.89GB free)|
|Process Argv|--crash-reporter-id be1ba9a5-eabf-47ce-9df7-f0e301ef8fad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-importmagic|bra|0.2.5
gitlens|eam|11.6.0
sort-lines-by-selection|ear|1.0.0
todo-tree|Gru|0.0.214
rest-client|hum|0.24.5
rainbow-csv|mec|1.9.1
git-graph|mhu|1.30.0
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
autodocstring|njp|0.5.4
vscode-python-typehint|njq|1.4.1
java|red|0.81.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30363604

```

</details>

**Comment by deepak1556** [comment]
Can you follow the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash logs, thanks!

**Comment by chr7** [comment]
I added the paramter '--crash-reporter-directory' as default (why itsn't that set by default?), so whenever this happens again I will get such are port. Unfortunately, I can't reproduce my crash.

**Comment by chr7** [comment]
I haven't had this problem again after I got a new laptop. The old one started to have trouble, so I think the crash was caused due to slowly breaking hardware and therefore not executing applications reliable any longer.
