### ISSUE TITLE
Brace matching for angle brackets gives wrong match

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#13295]
- VSCode Version: 1.5.3
- OS Version: Windows 10 Enterprise version 1607

Steps to Reproduce:

1. Open a new file.
2. Set the language to TypeScript (in the lower-right corner).
3. Type `const x: Array<() => void> = []`.
4. Place your cursor at the end of `Array`.
5. The `>` at the end of `=>` is highlighted. I would expect the `>` at the end of `void>`.

This does not appear to be a problem with the TypeScript language service; see Microsoft/TypeScript#11389.

**Comment by Tyriar** [comment]
![image](https://cloud.githubusercontent.com/assets/2193314/19155753/751f95e6-8b94-11e6-9d4c-63a92e7cacbf.png)

**Comment by mfazer** [comment]
Similar here - steps to reproduce:

1. Type this code in new **Sass** file:
```
b { font-weight: 600; }  
li {
    hr{ border: 0; }
    > a {
			display: block;
			color: #666;
		}
}
i { font-weight: 300; }
```
2 . Place the cursor right after ```border:```
3. Press keys ``` [shift]+[alt]+[right_arrow]``` for code selection a few times and observe unexpected matching (the problem is with ```>``` character included between ```{``` and ```}```.
