### ISSUE TITLE
[javascript] Bring back ES6 syntax highlighting support

### ISSUE THREAD

**Issue by txchen** [Microsoft/vscode#133]
Right now, those keywords like `import` `class` `from` are all plain white.

**Comment by leafduo** [comment]
And `async` from ES7 seems to be interpreted to TypeScript keyword.

**Comment by jahewson** [comment]
+1. Also `=>`  needs to be in a separate syntax class from the operators which are keywords, such as `instanceof` because I want to color keywords separately from  `=>`. Also for `import * as 'foo'` `import` and `as` need to be keywords while `*` needs to either an operator or something else more specific to imports.

**Comment by aeschli** [comment]
Our colorizer doesn't support ES6 / ES7 yet. I will look for a text mate grammar that does that.

**Comment by jnystrom** [comment]
@aeschli I thought for sure ES6 template strings were handled fairly well in the previous version of VSCode.

**Comment by aeschli** [comment]
@jnystrom  Yes, it's a regression, we switched from our own tokenizer to a JavaScript text mate grammar.

**Comment by egamma** [comment]
Plan is to use the TypeScript provided textmate grammar for JavaScript

**Comment by aeschli** [comment]
New grammar based on TypeScript grammar delivered.

**Comment by aeschli** [comment]
To try this out on a November release (0.10.1 - 3), replace the content of
`Microsoft VS Code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage `
with
https://github.com/Microsoft/vscode/raw/0b3f7b223d86ac1e8bbebc670913ed83595e98c6/extensions/javascript/syntaxes/JavaScript.tmLanguage

**Comment by konrad-garus** [comment]
I tried the workaround from @aeschli, restarted Code, but still keywords like `yield` are not highlighted. This is 0.10.6 on Ubuntu.

**Comment by aeschli** [comment]
@konrad-garus `yield` is still not colored due to bug https://github.com/Microsoft/TypeScript-TmLanguage/issues/29
