### ISSUE TITLE
Go to Cell # command for Notebooks

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133006]
A Go To Cell # command like Go To Line

**Comment by roblourens** [comment]
@tanhakabir what do you want this for, when do you know the cell # that you want to see?

**Comment by tanhakabir** [comment]
Yeah, I got instructions for "Go to cell 37 and..." Having a command to navigate to there would make this much easier. Not sure what you mean by the current cell status bar item. I'd assume this would be a command from command palette

**Comment by roblourens** [comment]
Where did those instructions come from? I don't think that Jupyter shows these cell numbers anywhere, so I didn't think that people are usually navigating notebooks this way

**Comment by tanhakabir** [comment]
These instructions are from our golden scenario testing so that's definitely fair that it's not a feature of Jupyter either. I do think though overall it'd be way easier to navigate notebooks if cells were visually indexed.

**Comment by DonJayamanne** [comment]
Wouldn't the outline view work, Not convinced many would use the command palette to navigate between cells. Feels too early to add this, we haven't had anyone ask for this in the jupyter extension, if anything they wanted the outline view to navigate to cells.

**Comment by tanhakabir** [comment]
I agree the outline view would be best
