### ISSUE TITLE
Indentation affects which blocks are collapsible 

### ISSUE THREAD

**Issue by abgivant** [Microsoft/vscode#13309]
- VSCode Version: 1.5.3
- OS Version: Windows 8.1

I'm not sure if this a bug or not, but I just noticed that indentation/spacing has an affect on which blocks of code are collapsible. 

As it is right now, anything that is indented past the first line of a block will be considered as being part of that block. This makes sense for a language where indentation determines context (Python), but in languages with explicitly defined blocks (JavaScript in this case) I'd expect the collapsible regions to be aware of the defined block.

**Examples:**

![image](https://cloud.githubusercontent.com/assets/3431954/19168061/027d1136-8bd4-11e6-8247-e1141bde7773.png)

![image](https://cloud.githubusercontent.com/assets/3431954/19168063/04b9ab8a-8bd4-11e6-9947-a8d505ff92ad.png)

![image](https://cloud.githubusercontent.com/assets/3431954/19168305/33b2290c-8bd5-11e6-94ce-3b0fdec968ad.png)

![image](https://cloud.githubusercontent.com/assets/3431954/19168310/36c59ef8-8bd5-11e6-8cb7-f8c3312945cb.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/3422
