### ISSUE TITLE
VSCode will not close if attempting to discard an unsaved file

### ISSUE THREAD

**Issue by tht13** [Microsoft/vscode#1330]
When attempting to close or change workspace containing unsaved file(s) vscode prompts you to save them (expected) however clicking 'Don't save' results in the same action as clicking 'Cancel'. I.e. the editor remains in the current workspace.
Detected on 0.10.4

**Comment by renil** [comment]
It looks like "Don't Save" and "Cancel" switched the functions. Cancel actually closes the editor.

**Comment by bpasero** [comment]
Fixed already, sry for that.
