### ISSUE TITLE
settings files.exclude false item does not work

### ISSUE THREAD

**Issue by shishirong** [microsoft/vscode#133052]
Does this issue occur when all extensions are disabled?: No
- VS Code Version: 1.6.0
- OS Version:windows 10

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/16620315/133190209-937ab47f-b2fa-45f4-8e80-53bd7dda35de.png)

2.
![image](https://user-images.githubusercontent.com/16620315/133190272-e3f80c6f-c7c7-4bbc-b142-5a3df4da2887.png)

I tried like 
```c
"!bsp/stm32/**": true
```
and 

```c
"bsp/!(stm32)": true
```
Still not working

**Comment by IllusionMH** [comment]
`false` doesn't work like re-include.You need proper support for `!` in glob patters which is tracked in #869. Please upvote that issue.

/duplicate

**Comment by shishirong** [comment]
> `false` doesn't work like re-include.You need proper support for `!` in glob patters which is tracked in #869. Please upvote that issue.
> 
> /duplicate

I have seen and tried reference #869,but the problem is still.

**Comment by IllusionMH** [comment]
That issue is tracking request for implementation as this is not supported yet.

Unfortunately, in the meantime you'll need to exclude everything else except from what you want, open specific folder directly, or try extensions that will create excludes "ladder" for you.
