### ISSUE TITLE
 cmd+click on files without extension doesn't work in markdown

### ISSUE THREAD

**Issue by opauloh** [microsoft/vscode#133030]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Linux x64 5.11.0-34-generic snap

Steps to Reproduce:

1. Create a README.md file
2. Put a relative link reference to a file without extension. i.e `[Dockerfile Reference](sample/Dockerfile)`
3. A popup will show saying: Unable to open `Dockerfile.md`: Unable to read file '/path/to/project/sample/Dockerfile.md' (Error: Unable to resolve non-existing file '/path/to/project/sample/Dockerfile.md'). And it will have a button to "Create File"

![image](https://user-images.githubusercontent.com/19270322/133153447-b3c8865f-f0a8-4e5e-a499-5cb8d52b8552.png)

It was working before the update, so I think it is related to [PR 130815](https://github.com/microsoft/vscode/pull/130815/files)

**Comment by ernestob** [comment]
This is also happening to me on VS Code on Mac.

It will open the file though, but it is also displaying the window to create the file.
