### ISSUE TITLE
List Tree View for tasks

### ISSUE THREAD

**Issue by SandHilt** [microsoft/vscode#133020]
Some editors have the ability to tag and navigate tasks marked as TODO.
Not just marking but navigating between tasks with tree view for example.
https://mcuoneclipse.com/2016/05/24/to-do-lists-with-eclipse-tasks-view/

**Comment by lramos15** [comment]
Something like this? https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus
