### ISSUE TITLE
Typescrip language support crashes more than 5 times in 5 minutes

### ISSUE THREAD

**Issue by cankahya** [microsoft/vscode#133069]
Issue Type: <b>Bug</b>

Typescrip language support crashes more than 5 times in 5 minutes error message appearing almost all the time.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|--crash-reporter-id 41a6e6fd-0378-4795-8e57-10fea26a4365|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
vscode-custom-css|be5|6.0.1
lit-html|bie|1.11.1
jsonviewer|cci|1.2.2
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
prettier-vscode|esb|8.1.0
vscode-graphql|Gra|0.3.18
svg|joc|1.4.9
vscode-docker|ms-|1.16.1
vscode-language-pack-de|MS-|1.60.3
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
sublime-keybindings|ms-|4.0.10
vscode-json-editor|nic|0.3.0
vetur|oct|0.34.1
vscode-xml|red|0.18.0
vue-vscode-snippets|sdr|2.2.1
markdown-preview-enhanced|shd|0.6.0
svg-preview|Sim|2.8.3
vscode-stylelint|sty|0.86.0
html-preview-vscode|tht|0.2.5
gitblame|wad|8.1.0
twig|wha|1.0.2
vue-style-beautify|xig|1.1.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
