### ISSUE TITLE
Error terminal VS Code Power Shell Windows

### ISSUE THREAD

**Issue by malipesilva** [microsoft/vscode#133098]
# Help me
***
![error](https://user-images.githubusercontent.com/90657405/133445626-229ed057-ba25-4731-8ddf-8c3b2d90ea89.PNG)

Terminal error how to solve?
Please help me
Open the link to view the image.

**Comment by TarunavBA** [comment]
@malipesilva The link is broken! 🤷‍♂️

**Comment by malipesilva** [comment]
Ready. I fixed it now
