### ISSUE TITLE
Support Proxy-Authenticate: Negotiate

### ISSUE THREAD

**Issue by marciopamplona** [Microsoft/vscode#13302]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 7

Corporate proxy server: `squid for windows`
Authentication method: Negotiate 
http://wiki.squid-cache.org/Features/NegotiateAuthentication
http://wiki.squid-cache.org/Features/Authentication

I use `ntlmaps` for debug the connection process. 
## **ntlmaps log:**
# 
# New client header:

CONNECT marketplace.visualstudio.com:443 HTTP/1.1
Proxy-Authorization: Basic PASSWORD
Host: marketplace.visualstudio.com:443
Connection: close
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/vnd.ms-excel, application/msword, application/vnd.ms-powerpoint, _/_

Connecting to remote server...(proxyserver:8080)...Done.
Sending client request header to remote server...Done.
Got remote server response header.
# 
# Remote server header:

HTTP/1.1 407 Proxy Authentication Required
Server: squid
Mime-Version: 1.0
Date: Thu, 06 Oct 2016 13:52:13 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 84718
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
Proxy-Authenticate: Negotiate
X-Cache: MISS from 10.14.64.2
Via: 1.1 10.14.64.2 (squid)
Connection: close

Server 'Content-Length' found to be 84718.
Authentication routine started.
Got Error 407 - "Proxy authentication required".
Authentication methods allowed: Negotiate
There are no supported authentication methods in remote server response.
Passing 407 to client.
Authentication routine finished.
Sending remote server response header to client...Done.

---

**Comment by joaomoreno** [comment]
Did you use the `http.proxy` setting?

**Comment by marciopamplona** [comment]
Yes, it doesn´t work. 
It´s returning 407 in every attempt.
Note the authentication method is ONLY "Negotiate", it´s not allowed, in our squid configuration, the "Basic" method.
I try to use cntlm to mediate the transaction, but the cntlm 0.92.3 do not support the Negotiate method.

**Comment by joaomoreno** [comment]
Do you mind going through #6480? Let me know if you find something.

**Comment by marciopamplona** [comment]
Yes, i try the suggested :
Proxy-Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
(The base64 string is just username:password encoded)

But my proxy don´t accept Basic authentication, like i mentioned.

**Comment by joaomoreno** [comment]
So, what kind of authentication does your proxy accept?

**Comment by marciopamplona** [comment]
ONLY: Proxy-Authorization: Negotiate
http://wiki.squid-cache.org/Features/Authentication

**Comment by joaomoreno** [comment]
#22369
