### ISSUE TITLE
Default integrated terminal on Windows always is Powershell on startup 

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vscode#133090]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.0
- OS Version: windows 10

Steps to Reproduce:

1. Open vscode
2. Change the default terminal to git bash
3. Close vscode
4. Open vscode
5. Terminal is powershell regardless

**Comment by tmeader** [comment]
Seeing the same issue. Trying to make default WSL (Ubuntu). Always reverts to Powershell on the next launch.

**Comment by IllusionMH** [comment]
/duplicate of #132150

Already fixed in Insiders build and supposed to be in upcoming Recovery August release.
