### ISSUE TITLE
`Ctrl+left click` on `Play Test` button should trig "Run with debug"

### ISSUE THREAD

**Issue by nalepae** [microsoft/vscode#133007]
**What we have:**
If we want to run a test in debug mode, we have to right click on the following green tick button:
![image](https://user-images.githubusercontent.com/4943830/132953431-725710e5-b516-45e1-b1fa-5dcd1d1fd990.png)
then click on `Debug Test`.

**What I would like:**
Pressing `Ctrl+left click` on the same green tick button could run the test in debug mode too.

Thanks a lot!

**Comment by connor4312** [comment]
I added this using the `Alt` key, to match alternate behavior in other areas of the UI (and general semantics)

**Comment by roblourens** [comment]
Love it, would be cool if the icon could change when I hold alt and hover, but I'm not sure we can do that with gutter decorations.

**Comment by connor4312** [comment]
We could add a listener for the "alt" key and change the icons in decorations when pressed.
