### ISSUE TITLE
Display Language TEST for testing translation 

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#133045]
Testing localisation of extensions requires changing the Display Language. 

This makes testing very difficult for anyone who isn't bilingual. 

The one and only sample for vscode-nls uses Japanese, which doesn't even use the same character set. This makes it tough to navigate the UI of VSCode while testing. It's alright for _me_, I can use French as the test language, but not everyone can read a second language.

Apropos of this https://github.com/microsoft/vscode-extension-samples/issues/481#issuecomment-918675803 I propose that VS Code needs a new LangId "TEST" for which the localisation strings are the English ones with some kind of marker to make the change of language visible, for example prepending everything with "(test)" wouldn't be too intrusive. 

Then someone adding localisation code to an extension would be able to implement translation strings for the TEST language according to the same pattern (English prepended with "(test)"), build the resources, set up for testing and select the TEST display language. They'd be able to read the UI and easily see which strings were translated. It would be easy to see when fall-through occurred if the extension used a different translated marker eg "(t)"

**Comment by dbaeumer** [comment]
This exists in development mode. You can use the locale `pseudo` which will keep the English string adds `[` and `]` and doubles vowels. 

There is also a pseudo language pack https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-qps-ploc which keeps the strings still readable but uses quite some unicode characters. 

Let me know if this works for you

**Comment by PeterWone** [comment]
I already make use of the pseudo language for testing. 

I did not know about the pseudo language pack, and I think that may well fulfil the purpose of helping those without a second language.

**Comment by PeterWone** [comment]
@dbaeumer I'm installed the pseudo language pack, this is quite clever in the way it also tests the character set aspect.

One thing that's not clear: what folder names should be used. What's the three letter country name for pseudo? For example, German is deu per this example.

![image](https://user-images.githubusercontent.com/5498936/133705193-060ad830-e6ed-4178-9bcd-7591671865e9.png)

When registering the languages in `gulp.js`, both the three letter language name and the langId are required. Does this look right?

```js
const languages = [
  { folderName: 'eng', id: 'en' },
  { folderName: 'deu', id: 'de' },
  { folderName: 'fra', id: 'fr' },
  { folderName: 'pse', id: 'qps-ploc' }
];
```

Just looking at the property names in that snippet, I wonder whether the folder name even matters so long as the name specified in gulp matches the name of the folder containing the string translations.

**Comment by PeterWone** [comment]
@dbaeumer Never mind, I have established by experiment that the folder names are arbitrary.
