### ISSUE TITLE
problemmatcher gives inconsistent results

### ISSUE THREAD

**Issue by mischw** [microsoft/vscode#133013]
Issue Type: <b>Bug</b>

When running a simple custom problemmatcher it gives inconsistent results. Sometimes showing duplicate problems, sometimes not showing all problems.

I try to attach a video of the issue here:

I reload the window to show this is probably related but different behavior from #132551

https://user-images.githubusercontent.com/2901275/133127499-c7561d5d-35fa-44ae-a25f-8408296219a9.mp4

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.13.13-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|7.47GB (0.65GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-gpu --unity-launch --crash-reporter-id 107c02ea-e02b-42e7-b8db-9d831efd30c2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|sway|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none

**Comment by alexr00** [comment]
When you give the problem a different `owner`, then it is expected that the problem will show up again.

Tasks problem matching only accepts one problem per "location", where "location" is the file, line, and position of the problem. Since your sample has all problems occur in the same file on the same line, just one of the problems shows. 

Are there any other behaviors shown in the video that I'm missing?

**Comment by mischw** [comment]
Ok, I wasn't aware that there is only one problem per location allowed.

But why does it then display two problems after changing the owner? (Video 00:35 to 00:45) Shouldn't it still be one problem per "location", since I didn't change the problem locations? Maybe it is one problem per location _and_ owner, and the problem of the old owner is not deleted somehow?
I expected to have it display one problem, or all three of them. Showing two out of three problems seems random. If the "anothermessage" problem is only shown because the problemMatcher now has a different owner, then why does it show the "message" and the "anothermessage" as output? Maybe there is some internal state that did not get reinitialized when the owner changes?

Also, at 01:05 to 01:10 I change the owner once again, and it goes from two problems to three problems. But the last one is actually a duplicate of the second one (2 x "anothermessage"). Even if this is due to the third introduced owner, which I think is confusing in itself, the duplicate does make no sense to me.

**Comment by alexr00** [comment]
The owner is part of the ID of the problem so each time you run it it with a new owner you'll get a new problem. The old problem is not cleared because a problem matcher with the same owner has not been run again.
