### ISSUE TITLE
The "Continue Working on..." button in the terminal appears twice in VS Code web

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#133058]
In VS Code web, the "Continue Working on..." button in the terminal appears twice. Persists even if I refresh the webpage.

![image](https://user-images.githubusercontent.com/12476526/133193873-2fb6d6ab-5562-4362-a29b-ccd7031266e8.png)

Version info:

Version: 1.61.0-insider
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:12:56.408Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

**Comment by meganrogge** [comment]
the issue is that you have both the insiders and stable version of remotehub enabled
