### ISSUE TITLE
VS Code does not open at macOS Monterey 12.0 Beta 

### ISSUE THREAD

**Issue by ForlornerBian** [microsoft/vscode#133057]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: macOS Monterey 12.0 Beta

Steps to Reproduce:

1. I tried to open VS Code.
2. The application is stuck at this stage.
<img width="1436" alt="Screen Shot 2021-09-14 at 12 10 35 AM" src="https://user-images.githubusercontent.com/31659511/133193737-311aad9d-a14f-41a1-b6c5-3dbf762a8632.png">

**Comment by mdarif** [comment]
macOS Monterey
Version 12.0.1 (21A559)

Facing the same weird issue on stable Monterey latest stable version.

**Comment by nffdiogosilva** [comment]
I'm having this issue on Monterey 12.1. Was anyone able to solve it?

**Comment by azabraao** [comment]
I'm also having this issue on Monterey 12.1 🙁

**Comment by deepak1556** [comment]
Is the issue present with latest stable `1.63.2` ? If so, can you attach the output of `code --verbose`
