### ISSUE TITLE
After updating the old version, one of the button disapear

### ISSUE THREAD

**Issue by jacktkk** [microsoft/vscode#133086]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
This button is used to compare the modified file. I want to know where I can find this button again?
![image](https://user-images.githubusercontent.com/27617155/133263061-4d43bfbc-ce69-4857-97a7-2d5a752408ec.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Which version?

Is this file tracked in git or other VCS? Doesn't looks like your file has changes

**Comment by jacktkk** [comment]
> /needsMoreInfo
> 
> Which version?
> 
> Is this file tracked in git or other VCS? Doesn't looks like your file has changes

Yes, the file is tracked in git. The picture is used to denote the button, we can assume the file is modified. In short, I want to display the changes before applying "git add .".

**Comment by IllusionMH** [comment]
Related to #26425 and https://github.com/microsoft/vscode/commit/323237921b889eaedb02d4a58af2d766bde59ce7 should include untracked files.

Are you using latest stable version or Insiders?

/assign @lramos15

**Comment by jacktkk** [comment]
> Related to #26425 and [3232379](https://github.com/microsoft/vscode/commit/323237921b889eaedb02d4a58af2d766bde59ce7) should include untracked files.
> 
> Are you using latest stable version or Insiders?
> 
> /assign @lramos15

The version of my vscode is August 2021 (version 1.60).
No matter whether the file is changed, the button does not display.
![image](https://user-images.githubusercontent.com/27617155/133288910-e1353c69-22b8-4367-846f-4d0520a95c59.png)

**Comment by lramos15** [comment]
I'm not able to reproduce this. I assume you're in a git repo?

**Comment by jacktkk** [comment]
> I'm not able to reproduce this. I assume you're in a git repo?

**Comment by jacktkk** [comment]
> I'm not able to reproduce this. I assume you're in a git repo?

Yes, I just want to know how to re add the missing button, which is framed in red in the first comment.

**Comment by lramos15** [comment]
Right, I understand your issue but I see the button on my version of 1.60 and the button should automatically turn on and off when needed. Can you try `F1 -> Reload With Extensions Disabled` and see if that works?
