### ISSUE TITLE
Vscode for Mac: failed to run or debug C/C++ code when the code file path contains blank space(Such as files in iCloud)

### ISSUE THREAD

**Issue by q944093** [microsoft/vscode#133091]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2 
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1.Press F5 to run the C/C++ code.
2.An external Terminal opened and left a warning: "working directory doesn't exist: '/Users/XXX/Library/Mobile'"
as following picture.Same situation when debug.
![image](https://user-images.githubusercontent.com/58098692/133280988-4feb6de5-7c21-4ceb-802f-42e0aada0156.png)
3.If I run the same code in a non-space file path in the same way,The issue doesn't occur.

It seems that blank space in file path between 'Mobile Documents' cause this issue.How can I fix it without moving to a non-space path?

**Comment by roblourens** [comment]
Please file this on the cpptools extension repo
