### ISSUE TITLE
Slight lag scrolling around large images in Notebook

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133005]
Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Having the output of a large image seems to make scrolling laggy. 7:15 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

**Comment by DonJayamanne** [comment]
Could this be a dup of https://github.com/microsoft/vscode/issues/117644
We have a large number of users complaining about scrolling perf there

**Comment by rchiodo** [comment]
Did some perf analysis around this. Not quite sure how to interpreter the slowdowns yet, but here's a scroll spanning two frames (which I believe would cause a stutter):

![image](https://user-images.githubusercontent.com/19672699/148456335-6eec0ccd-84f5-4939-b1a5-52aa8bdd2581.png)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/microsoft/vscode/issues/129972
