### ISSUE TITLE
How to implement custom IntelliSense through extension

### ISSUE THREAD

**Issue by yansenlei** [microsoft/vscode#133001]
```
// dir/*.json
// a.json
{
    "name": "first",
    "list": ['aaa', 'bbb']
}

// b.json
{
    "name": "more",
    "list": ['ccc', 'ddd']
}
```
![image](https://user-images.githubusercontent.com/23315895/133114920-40780340-9d5b-4ba3-a6af-f2928e55dd13.png)

Maybe we can do that in extension:
```js
// Read the file structure tree
const tree = fs.read('mydir/')
// to IntelliSense
// ...
```

**Comment by IllusionMH** [comment]
/question
Please see https://github.com/Microsoft/vscode-extension-samples/tree/main/completions-sample and other extension samples in that repo.
As well you can check VS Code API Docs for more details: https://code.visualstudio.com/api/references/vscode-api#languages.registerCompletionItemProvider, https://code.visualstudio.com/api/language-extensions/programmatic-language-features and other
