### ISSUE TITLE
Bracket pair colorization should also work for language-specific bracket tokens

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#133004]
In Python 3, the following is a valid expression:

```python3
f"""foo {
	f'''bar{
		f"baz {f':-) {42}'}"
	}
	'''
}"""`
```

![image](https://user-images.githubusercontent.com/38782922/133119157-3431a3ce-3d03-429b-928b-271ca1fff55d.png)

In Bash, the following are valid expressions:

- ```bash
  echo "foo $(echo "bar $(echo "echo baz $(echo "echo :-)")")")"
  ```
- ```bash
  echo "hello1-`echo hello2-\`echo hello3-\\\`echo hello4\\\`\``"  # credit: https://stackoverflow.com/a/2657037/13994294
  ```

![image](https://user-images.githubusercontent.com/38782922/133119197-02af87d7-a578-4841-b499-4ffcc49b69ac.png)
_(using shellcheck)_

I think it would be nice if pair colorization could also be applied to language-specific bracket tokens such as single quotes (`'`) and double quotes (`"`) but also their triple equivalents in Python (`'''` and `"""`) or backticks in bash (`` ` ``). There might be even further bracket tokens in other languages, maybe chevrons (`<`​`>`), I don't know.

The question is for which tokens it would be vise to provide colorization as a language-agnostic concept (as bracket colorization works at the moment to my knowledge) and for which ones you should dispatch them over the LSP ...

**Comment by IllusionMH** [comment]
VS Code brackets colorization relies in `brackets` that is specified in `language-configuration.json` (usually) by extension that provides support for this language. Should work if extension specifies them as brackets.
Otherwise you can wait for #131412 which will allow user specified brackets config, however I'm not sure if it's supposed for multicharacter entities.

/assign @hediet

**Comment by LinqLover** [comment]
Thank you, so shall I file in two issues for the Python and Shellscript language extensions?

**Comment by hediet** [comment]
Opening brackets must be distinguishable from closing brackets at the moment.
