### ISSUE TITLE
Does not reflect changes on the fly - React Native

### ISSUE THREAD

**Issue by ChiragMDave** [microsoft/vscode#133085]
Issue Type: <b>Bug</b>

This is a serious bug after last update.
The react native app is connected to packager on ip:8081.
After saving the changes in code it displays refreshing caption on phone but does not actually update/reflect the change. Also, logs old values on console.
It needs to always restart the app on phone or emulator to get the changes. Which is absolutely not desired.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-34-generic
Restricted Mode: No

**Comment by IllusionMH** [comment]
Looks like issue with extension that provide RN functionality or watchers.
Could you specify how exactly it's related to VS Code editor itself? Does it update files on disk when they are saved?

**Comment by ChiragMDave** [comment]
I have been working on development as usual, in between came this vs code update and then this happened. As I said, it requires to restart the app to see the code changes, so yes it does update file on disk. Will try to find out the cause and get back. Thanks.

**Comment by ChiragMDave** [comment]
> Looks like issue with extension that provide RN functionality or watchers.
> Could you specify how exactly it's related to VS Code editor itself? Does it update files on disk when they are saved?

Lets close this issue. Now it's working as expected.
