### ISSUE TITLE
Re-surfacing path variable issues with relativeFile

### ISSUE THREAD

**Issue by markjm** [microsoft/vscode#133000]
Related https://github.com/microsoft/vscode/issues/70050#issuecomment-472052839 https://github.com/microsoft/vscode/issues/40256

Hi all - I read through all the conversation on the above topics, and I just wanted to resurface this information.

For some context, using vscode debugger to run jest tests is very difficult due to the above issue (as jest can only understand forward slashes, while VSCode uses OS-specific slashes). The workarounds above suggest using `${fileBaseName}`, but this causes issues in monorepo-style projects. For example, if I want to run the tests in my open file `a/index.ts`, using `fileBaseName` will be a regex match for every other `index.ts ` in the repo (thousands in our case). There is no other way to dynamically grab the whole relative file name.

My suggestion would be to allow choosing slash used via some known syntax. Example would be `${relativeFile|slash=unix}` or something similar. This would continue to be totally backward compatible, but allow for a little more configuration to solve the cases mentioned above.

**Comment by markjm** [comment]
For anyone else looking for a workaround for this issue, I found the best way to be by creating a small shim for jest specifically to be called by VSCode

`my-jest.js`
```// Workaround shim for VSCode Jest debugging due to the following issue.
// https://github.com/microsoft/vscode/issues/70050

const regexPositionFromVSCode = process.argv.length - 1;
const fileNameRelative = process.argv[regexPositionFromVSCode];
process.argv[regexPositionFromVSCode] = fileNameRelative.replace(/\\/g, "/");

require("jest/bin/jest");
```
`launch.json
```
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Unit Tests In Current File",
      "sourceMaps": true,
      "program": "${workspaceFolder}/my-jest.js",
      ...
    },
```

**Comment by roblourens** [comment]
@alexr00 I think you own general variable resolution?

**Comment by markjm** [comment]
@alexr00 thats great to be exposed, but does not solve the case I described.

Consider a file at [1] `a\\b.js` and [2] `a\\b\\c\\d.js`

If I want to unix-pathify these, 

[1] can be `${relativeFileDirname}${pathSeparator}${fileBasename}`

for [2], though, the intermediate path segments are not individually accessible. The closest option would be
`${fileDirname}}${pathSeparator}${fileBasename}`. But that would yeild `a\\b\\c/d.js`. Note how there is no way to "control" the seperators in the intermediate segments.
