### ISSUE TITLE
Invalid 'cwd' value '/workspace/projectA'.  The system cannot find the file specified.

### ISSUE THREAD

**Issue by stevef51** [microsoft/vscode#133055]
Issue Type: <b>Bug</b>

New issue (ie, been doing this for months without issue)
Seems to occur when multiple VSCode dev containers are open (which is my daily activity)
With 3 dev containers (all C# .NET 5 projects) ProjectA, ProjectB, ProjectC
Hit F5 (Run) on ProjectB - it compiles and when starts to launch will instead display an error dialog :-

<<
Invalid 'cwd' value '/workspace/ProjectA'.  The system cannot find the file specified.
[Open 'launch.json']
[Cancel]
>>

Notice that the dialog is looking for ProjectA when I hit F5 from ProjectB - if I Cancel and retry then it usually works fine, but I have also just seen it then display the same error but with ProjectC as the path its looking for.
Opening launch.json shows the correct ProjectB

This occurs from each devcontainer aswell - it seems there is some level of intermixed configuration between the VSCode windows.

This seems to be a transient issue which is resolved by Cancel and re-run the project, but is a little frustrating.

Expected behaviour:
Hit F5 Run on ProjectB should compile and launch ProjectB, not ProjectA from a different VSCode devcontainer.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.47-linuxkit
Remote OS version: Linux x64 5.10.47-linuxkit
Remote OS version: Linux x64 5.10.47-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (14.76GB free)|
|Process Argv|--crash-reporter-id 30a098bd-a960-4180-b1ce-56b74d95c381|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: VirtualMgr.SPA Dev Container|
|OS|Linux x64 5.10.47-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (4 x 2300)|
|Memory (System)|11.70GB (1.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: VirtualMgr.Portal Dev Container|
|OS|Linux x64 5.10.47-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (4 x 2300)|
|Memory (System)|11.70GB (1.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: VirtualMgr.Auth Dev Container|
|OS|Linux x64 5.10.47-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (4 x 2300)|
|Memory (System)|11.70GB (1.64GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.43.2
Angular-BeastCode|Mik|10.0.3
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.10.0
vscode-icons|vsc|11.6.0
csharp|ms-|1.23.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by stevef51** [comment]
Actual screenshot ..
![image](https://user-images.githubusercontent.com/956253/133192371-ae705b81-a820-402c-bbb0-4fb4f54b6b34.png)

**Comment by roblourens** [comment]
That's really strange. And this only happens when the `VirtualMgr.Portal` project is also open in another window?

**Comment by stevef51** [comment]
Yes, a little more testing on this and it occurs when I switch between VSCode windows .. it appears to be trying to run the prior selected VSCode window instead of the current one, quite strange.

This short video shows VirtualMgr.Portal on the left and VirtualMgr.Auth on the right, both .NET Core projects in DevContainers - I then try to run VirtualMgr.Auth but it errors trying to start VirtualMgr.Portal, a retry then succeeds.  Then over to the VirtualMgr.Portal and run it which also fails trying to find VirtualMgr.Auth, but on retry succeeds.

The video is very hard to read because of the 10mb upload limit, but I think it illustrates the issue clear enough.

Its actually very reproducible here

https://user-images.githubusercontent.com/956253/133373317-895ae975-d0a2-4c6a-9163-efba9e3bb530.mov

**Comment by roblourens** [comment]
Does it still happen if the launch configs have different names? Are you pressing F5to start debugging?

**Comment by stevef51** [comment]
So yes, I always start a debug with F5 keyboard shortcut. 

Ok, so just tried naming the launch configs "Launch Auth" and "Launch Portal" but still has same issue.  Also then tried clicking the green Run arrow (not F5 keyboard) but still same issue.

**Comment by roblourens** [comment]
@sandy081 I'm wondering if you have any idea what could be happening here? Seems like the user is switching windows, pressing F5, and briefly getting a launch configuration from the previous window, which seems impossible, but maybe there is something in the configuration service that is driven by the shared process that could lead to this?

**Comment by sandy081** [comment]
I do not think configuration service is getting any information from shared process. Every window has its own configuration service and it fetches data directly from files.

**Comment by sandy081** [comment]
Wait a sec, I just saw the video, it seems to happen with dev containers. By any chance do they have same paths?

**Comment by sandy081** [comment]
I just fixed this bug in my cache. But I do not know this is the root cause. It may be worth asking user to try again using tomorrow insiders.

**Comment by roblourens** [comment]
Interesting, @stevef51 would appreciate if you try this with tomorrow's Insiders build

**Comment by stevef51** [comment]
Cool, installed VSCode Insiders and confirmed that it is fixed - thanks guys
