### ISSUE TITLE
Run and Debug (c++ gcc and gdb) works in Remote Container but not Codespaces

### ISSUE THREAD

**Issue by seorasray** [microsoft/vscode#133097]
I have a c++ repo that contains `devcontainer`, `tasks.json` and `launch.json` configs. When running VSCode locally and in a Remote Container I can use the `Run and Debug` menu to run a gcc task that builds the executable and then launches gdb to debug it. When I do the same thing in CodeSpaces I get a prompt asking me to `Select environment` with the options `C++ (GDB/LLDB)` or `C++ (Windows)` and then just takes me to my `launch.json` file for editing.

The `devcontainer` Docker Image includes the gcc toolchains and gdb etc. I can run gdb manually in the Codespaces terminal and it works fine. I can run the build tasks from `tasks.json` in Codespaces and they also work fine.

If I deliberately add syntax errors to my `launch.json` it exhibits the same bad behaviour indicating the error occurs before it parses the `launch.json` and as such is not caused by any settings in there. Although I have also tried changing these settings to no avail. I have also tried both the stable and insiders version of Codespaces with no change.

I would love to get this fixed since this would be a game changer for our users who do not have good development environments set up and can't easily run Docker or gcc/gdb etc. 

Thanks for any help!

**Comment by seorasray** [comment]
Sorry if this is an issue with the vscode-cpptools extensions and should be opened over there instead.

**Comment by seorasray** [comment]
If I take the contents of my `.vscode/launch.json` file and add them to the VSCode Settings as the default `launch` config the debugging works when pressing F5 so it seems that it just can't find the `.vscode/launch.json` file when run normally.

**Comment by roblourens** [comment]
Please file this on the vscode-cpptools repo first, thanks
