### ISSUE TITLE
Auto Guess Encoding -  "Windows-1250" not detected, ignores default encoding setting

### ISSUE THREAD

**Issue by peminator** [microsoft/vscode#133075]
Issue Type: <b>Bug</b>

Windows-1250 in most cases detected as other Windows-125x or iso8859-x, ignores defualt encoding should be preferrred in guessing order (guess result different, based on contained characters)

1) turn "Auto Guess Encoding" on
2) set default encoding to "Central European (Windows 1250)"
3) put into new file text inluding accented characters: "Žuvačka Čerešňa Šáňo" or other centraul european (eg slovak, czech, ..) accented characters , 
4)  save with encoding "Central European (Windows 1250)" - using palette command or clicking the encoding in statusbar
5) close and reopen the file
6) compare the displayed string with what was entered

note: turning auto guess is a no-go, most users facing this issue use utf8 for new files + one local encoding for older files, same here, i need to detect utf8, and set all other files to open as Windows-1250 by default, only if it contains characters not recognized in the secondary (1250) encoding, VSCode may offer dialog to try reopen in other encodings (with preview on snippet containing the first problematic caracter from current file, and dropdown menu of possible matches - would be uber-perfect) 

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by peminator** [comment]
Im aware of the list, and aware it can be set per type, but if my default
is windows 1250 like i said, then that setting should be used as first, and
only if  file contains characters that really dont match that encoding,
only then proceed to rest of auto guess. If i set my default to be 1250, i
expect it to have priority on guessing. That is the bug, the autoguess
feature should honor this setting, try to validate against default encoding
first. it does not which causes wrong results.

**Comment by bpasero** [comment]
I do not fully understand your suggestion. The option is simple: if you have auto guess encoding enabled, `jschardet` is used: https://github.com/aadsm/jschardet, otherwise the encoding is used as configured in settings.

Can you clarify how this would work exactly?

**Comment by peminator** [comment]
I say, the detection is not reliable, so as first, there should be file
content validation for default encoding. Yet, not sure how to do it, that
is on others to decide. If it does not throw error, no invalid or
suspicious characters, file opens in that default encoding, without ever
using jschardet - bc that one is not 100% reliable, as shown on previous
examples. Using that repo is also questionable, they mark support for
windows-1250 as Hungarian, but it should correctly be "Central European" -
afaik, the windows 1250 is also used in Slovak and Czech Republic, and
maybe other around too, so then the code probably was not properly tested
with all characters to be expected, and probably should not be used, or the
support should be questioned more


*for detecting, there hould be multiple steps:*

1) test for utf8 and other multibyte recognizable

2) if 1) fails, test specifically for encoding set as default, with
reasonable "confidency" value using jschardet

3) if both 1) and 2) fail, use the now used standard jschardet


*suggested feature: *

instead one default encoding, there should be an orered list of preferred
encoding, those would then be used as loop in point 2) above in the
specified order








st 15. 9. 2021 o 7:03 Benjamin Pasero ***@***.***> napísal(a):

**Comment by bpasero** [comment]
> there should be file content validation for default encoding

What is "file content validation"?

I think you already figured it out: encoding detection is not guaranteed to be correct, so you need to turn it off when it provides bad results to you. 

This sounds like a duplicate of https://github.com/microsoft/vscode/issues/36951 that asks for more fine grained control about the guessed result.

**Comment by bpasero** [comment]
> file validation was meant as "compare text content of file against selected specific encoding"

Compare? like how? as far as encoding is concerned, you have 2 arrays of bytes to compare. How do you make a decision if the encoding is good or bad?

As for UTF encodings: we do detect Byte-Order-Marks and we can detect UTF-16-LE and UTF-16-BE because those are the only encodings with a very specific byte pattern.

**Comment by peminator** [comment]
reading jschardet over, it can return the detected object with encoding and confidence, so basically there needs to just be set e reasonable minimum confidence for autoguess , and fall back to default encoding if the returned confidence is low... to make this even more universal, the auto gues confidence could be a user definable valuem with something reasonable as default

btw, found something about setting the setting the guessable encodings, maybe that is the whole thing many ppl need, just needs to be defined better, and available in ui so ppl have more info about it.. how i set it to guess only utf8 and windows-1250? array? can someone provide example of that settings json part?
