### ISSUE TITLE
Walkthrough markdown content is larger than primary content

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#133015]
Markdown preview text that uses h1 has a font size of 26px:

<img width="772" alt="CleanShot 2021-09-13 at 10 27 19@2x" src="https://user-images.githubusercontent.com/35271042/133129466-1585e2b1-bd10-4dbd-98e8-415024bad7ac.png">

Primary content on the left has a font size of 19.5px:

<img width="589" alt="CleanShot 2021-09-13 at 10 27 30@2x" src="https://user-images.githubusercontent.com/35271042/133129477-80f333a5-e0a8-4224-b101-999164042d18.png">

We should either reduce the largest font size on the markdown preview or make our title larger. Vertically aligning cells would also help but that is captured in #129733

<img width="1266" alt="CleanShot 2021-09-13 at 10 32 22@2x" src="https://user-images.githubusercontent.com/35271042/133130114-d82dad17-d405-4ffe-97a6-534c09fba44f.png">

**Comment by kimadeline** [comment]
right-side h1 font size is 19.5px:

![image](https://user-images.githubusercontent.com/51720070/144330452-8dfa2b64-d143-4eb9-a1bf-d51e2d8b2ca8.png)


left-side h2 font size is 1.5em:

![image](https://user-images.githubusercontent.com/51720070/144330612-a3c3595b-170f-4314-92a4-23c28818e368.png)

which resolves to 19.5px:

![image](https://user-images.githubusercontent.com/51720070/144330875-1cfaac16-9711-414b-aeb1-55ff3b2a7869.png)
