### ISSUE TITLE
vscode explorer multi choice is f****p

### ISSUE THREAD

**Issue by Y2k38** [microsoft/vscode#133050]
in linux, when use ctrl/command + click to choose multi files/dirs, it also select current open file, then right click menu to delete, if close current open file by mistake, well, it is deleted permanently

**Comment by JacksonKearl** [comment]
Is the issue here that the current file is kept selected in the explorer?

**Comment by Y2k38** [comment]
> Is the issue here that the current file is kept selected in the explorer?

yes

**Comment by JacksonKearl** [comment]
What would you propose?

**Comment by Y2k38** [comment]
> What would you propose?

 i have no idea, what i realize is that "muti selected" is conflict with "highlight current open file", ignore it
