### ISSUE TITLE
Light border around outputs to tell which area to use to scroll in the notebook or output

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133003]
Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

If you have a large output with a white background, it's confusing to tell where I can scroll to scroll within the output or in the notebook. Minute 4:45 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a).

![image](https://user-images.githubusercontent.com/12758612/133118065-69268d6d-33c0-4f7f-9d81-2b6f1ddf7dac.png)

**Comment by tanhakabir** [comment]
@misolori do you have a PR out for this already?

**Comment by misolori** [comment]
Yes, this should be an option now via https://github.com/microsoft/vscode/issues/125462#issuecomment-918634217
