### ISSUE TITLE
Python Interactive Window | Add new notebook.cellToolbarVisibility option to be always on

### ISSUE THREAD

**Issue by abd-shouman** [microsoft/vscode#133067]
Cell toolbars (mainly cell delete) used to be always available on the left side of the cell. 
However, after the new update, the design changed, one workaround is to show it on hover as mentioned here (https://github.com/microsoft/vscode-jupyter/issues/7250#issuecomment-906739023)  

However, this can be a bit inconvient, espcially if I want to delete multiple cells at once (and even more inconvients when the cells I want to delete are not right after each other). This comment discuss the old behaviour that I thought was convinent and helped make the interactive window more clean (https://github.com/microsoft/vscode-jupyter/issues/7188#issuecomment-901711018)

While the hover can be a decent workaround adding an option to make toolbars always visible (always on) would be very conviennent (and it is actually just the old behaviour which worked just fine).

**Comment by gjsjohnmurray** [comment]
Seems related to #130280

**Comment by gjsjohnmurray** [comment]
Also to #129417

**Comment by amunger** [comment]
multiple deletion of cells is now possible - selecting and pressing the delete key. Closing this in favor of the related issues
