### ISSUE TITLE
Cannot Open Mutiple git branch in different windows.

### ISSUE THREAD

**Issue by Yasir900aslam** [microsoft/vscode#133082]
Issue Type: <b>Bug</b>

Suppose you have Two Branches [One and Two] in your git project folder known as Test.

1. Create two windows (for example A and B ), open the Test project in both of them.
2. Change the Window A Git branch to One. 
3. Change the Window B Git Branch to two.

Now you will see Conflict in the window A and B that git console will show that both windows are on the different branch but the view is the same. 

**Screenshot Attached**

[
<img width="1440" alt="Screenshot 2021-09-14 at 4 14 08 PM" src="https://user-images.githubusercontent.com/26070254/133248843-ea4c0ed6-e0ec-4316-9e69-eda3046f6af7.png">
](url)
<img width="1440" alt="Screenshot 2021-09-14 at 4 13 50 PM" src="https://user-images.githubusercontent.com/26070254/133248874-8ca65df8-38c9-4a51-9482-08607b38245f.png">

**_Explanation_**
As You can see in above screenshots that, newdev has different file from bugfix/poc_with_multiple_users but the vscode view is showing that they are on the same branch

VS Code version: Code 1.58.2 (Universal) (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.73GB free)|
|Process Argv|--crash-reporter-id 90aec32d-205c-4330-96ca-1628be6ddffe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
pug|ama|1.0.1
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
vue-peek|dar|1.0.2
githistory|don|0.6.18
pug-formatter|duc|0.6.0
css-flexbox-cheatsheet|dzh|3.2.3
prettier-vscode|esb|8.1.0
git-project-manager|fel|1.7.1
flow-for-vscode|flo|1.9.2
go|gol|0.27.2
vue-snippets|hol|1.0.4
githd|hui|2.2.4
rest-client|hum|0.24.5
vscode-env|Iro|0.1.0
vue|jcb|0.1.5
vscode-elixir|mjm|1.1.0
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.16.1
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.8.1159798656
vscode-pylance|ms-|2021.9.1
remote-containers|ms-|0.187.1
vscode-jest|Ort|4.0.3
prisma|Pri|3.0.1
vscode-thunder-client|ran|1.9.1
rust|rus|0.7.8
glassit|s-n|0.2.3
vue-helper|she|2.4.7
vscode-stripe|str|2.0.3
vim|vsc|1.21.7
change-case|wma|1.0.0
vscode-proto3|zxh|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by eamodio** [comment]
This behavior is by-design, as it is how Git works -- there is only 1 working directory, so when you switch to a different branch that working directory changes.

**Comment by Yasir900aslam** [comment]
@eamodio , Exactly This is what I expected in the first place but vscode doesn't detect that the working directory changed, even after reloading it, I will try to reproduce again
