### ISSUE TITLE
"Preferences: Open Remote Settings (JSON)" opens UI settings instead of JSON

### ISSUE THREAD

**Issue by pgit** [microsoft/vscode#133039]
Starting with ~v1.60 (not exactly sure), the command for opening the remote-specific JSON settings file opens the UI instead.

- VSCode Version: 1.60.0 or v1.61.0-insiders 
- Local OS Version: Windows 10 or RHEL8
- Remote OS Version: Debian, RHEL7 or RHEL8
- Remote Extension/Connection Type: SSH, Docker and WSL (tested with all of them)
- Remote Development Extension Pack Version: v0.21.0

Steps to Reproduce:

1. Open ar remote workspace (either WSL, Docker or SSH)
2. Run command: "Preferences: Open Remote Settings (JSON)"

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by roblourens** [comment]
The JSON version of this command was only just added, and I see the problem
