### ISSUE TITLE
Git: Search commit in specific branch

### ISSUE THREAD

**Issue by arhakim** [microsoft/vscode#133061]
Hi, is it possible to improve the [Git search feature](https://prnt.sc/1s4m9h8) by filtering the results by branch? 
For example, I have 3 branches: dev, staging, master
I code everything in the dev branch, then after it's finished (commit), I'd copy the commit using cherry-pick to staging branch, and then it's ready to release, I'd copy it again to master branch.

Thanks

**Comment by eamodio** [comment]
That feature is provided by GitLens, please feel free to open a feature request with the changes you would like on it's repository.
