### ISSUE TITLE
Loosing focus while Renaming Files/Folder 

### ISSUE THREAD

**Issue by mcewball13** [microsoft/vscode#133035]
Issue Type: <b>Bug</b>

Similar to issue #96528, It's random when it happens some files do it, some don't. Some files it immediately loses focus, others happen after a few seconds. It' very annoying. I'm not sure what to do, I tried reinstalling and nada.

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.01GB (0.11GB free)|
|Process Argv|--crash-reporter-id c2f559bd-df74-4654-9bf4-d61e37f7d1d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|8.1.0
auto-rename-tag|for|0.1.8
vscode-graphql|Gra|0.3.18
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.6.1
js-jsx-snippets|sky|10.2.0
tabnine-vscode|Tab|3.4.27
open-in-browser|tec|2.0.0
quokka-vscode|Wal|1.0.400
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by JacksonKearl** [comment]
Could be related to https://github.com/microsoft/vscode/issues/112293, can you see if this reproduces when an external process is creating files in the folder?
