### ISSUE TITLE
Notebooks: when run above is selected from a cell and new outputs are rendered above, should scroll to original cell

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133096]
Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

I'm at a specific cell in the middle of the notebook and the cells above haven't been run yet. When I click run above and cells above are run and new output is rendered, I'd expect the cell I clicked run above from to still be in view.

13:06 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

**Comment by rchiodo** [comment]
I believe @roblourens already fixed this. Works this way for me now.
