### ISSUE TITLE
VS Code keep lagging

### ISSUE THREAD

**Issue by Luminous-Coder** [microsoft/vscode#133081]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Windows x64 stable (1.60.0) (Downloaded from the official web)
- OS Version: Windows 10

Steps to Reproduce:

1. I just run VS Code normally.
2. Created a new file, VS Code costed about 10 seconds to do this.
3. Typed in the file (I typed Hello World in C), the extension for C didn't give me tips, and Rainbow Brackets and other extension didn't work, too.
4. Power Mode worked 1~2 minutes later, but the effect didn't stop. It keep to made points!
5. VS Code didn't save the file after I pressed ctrl + s, but 10 seconds later.

I have tried on another Windows 10, but didn't go into this bug.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
