### ISSUE TITLE
github.dev: extension contributed terminals don't show up when welcome view is active

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133024]
In a web extension register a terminal profile provider that creates a `vscode.PseudoTerminal`. When the terminal welcome view is active, creating a terminal doesnt replace the welcome view:

Clicking this 
![image](https://user-images.githubusercontent.com/20570/133128610-34d58ab3-19aa-4167-b8bd-5a67c45c4202.png)

results in just this:
![image](https://user-images.githubusercontent.com/20570/133128634-34957525-718d-45f4-9eb2-0ca57b3c73e9.png)

I can click on Move into editor are:
![image](https://user-images.githubusercontent.com/20570/133128671-b799b279-9994-451e-a980-a000c7100c55.png)

and that'll show the terminal as an editor and at that point the welcome view is gone and the terminal view works normally

**Comment by meganrogge** [comment]
fixed with https://github.com/microsoft/vscode/pull/136327

**Comment by meganrogge** [comment]
to verify:

- run `yarn watch-web && web`
- install a web extension that contributes a terminal profile 
- click the plus button
- the terminal should appear and not be covered by the welcome view
