### ISSUE TITLE
Search performance/Bug

### ISSUE THREAD

**Issue by jasonhu777** [microsoft/vscode#133022]
Issue Type: <b>Bug</b>

OS: Win 10 
OS Version: 10.0.190.43
Since recently update, whenever I search anything using VS code, Antimalware Service Executable's CPU usage spikes upto 80%, which also undermines search performance. prolonged search time by a lot(maybe 10-20times), for some searches I had to wait for 3 mins to complete. And this never happened before.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.82GB free)|
|Process Argv|C:\\Users\\aweja\\Desktop\\Work\\webviewer --crash-reporter-id d3e50ce6-a0b7-4417-8477-fba227bcb2dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
path-intellisense|chr|2.4.0
bracket-pair-colorizer-2|Coe|0.2.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
auto-close-tag|for|0.5.12
color-highlight|nau|2.5.0
indent-rainbow|ode|8.0.0
tabnine-vscode|Tab|3.4.27
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224cf:30358040
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by roblourens** [comment]
Nothing has changed on vscode's side, it's not clear to me when Windows Defender decides to interfere or not
