### ISSUE TITLE
Effectively signal limited language support to users, e.g. in untrusted folders

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#133049]
Ideally VS Code could signal to users why certain language features and behaviors aren't available in situations like untrusted workspaces/folders.

### Trusted
<img width="858" alt="CleanShot 2021-09-13 at 19 20 37@2x" src="https://user-images.githubusercontent.com/25163139/133184176-0e766e24-ac21-4f9a-9d8e-26c3de3dea79.png">

### Untrusted
<img width="276" alt="CleanShot 2021-09-13 at 19 20 52@2x" src="https://user-images.githubusercontent.com/25163139/133184193-1f4fc19f-4258-4c9d-a01f-8f360585f718.png">

**Comment by daviddossett** [comment]
One idea here would be to show language support messaging only when hovering or under certain suggestion/completion scenarios.

<img width="895" alt="CleanShot 2021-09-15 at 10 40 36@2x" src="https://user-images.githubusercontent.com/25163139/133482648-967752bc-8320-4521-8fe5-f2d4b6ff07c8.png">


@isidorn brought up a good point this morning about how and when we would know when to show these. Still thinking about how to be consistent and predictable here.

We also thought about some other options like surfacing hints on list items with actionable buttons/links. The general consensus was that this somewhat pushes users towards trusting the workspace without the context they have from the banner (which could be dismissed) or the workspace trust dialog itself.

<img width="799" alt="CleanShot 2021-09-15 at 10 38 26@2x" src="https://user-images.githubusercontent.com/25163139/133482507-f1475635-32b0-420f-bf4b-c4a72c255cda.png">

**Comment by isidorn** [comment]
@jrieken brought up the same point in the ux channel. Also he might have some good ideas on how to detect when to show this.

**Comment by jrieken** [comment]
> Also he might have some good ideas on how to detect when to show this.

Unsure if I have good ideas but I can make the problem more complicated ;-) 

I like what I am seeing so far but I wonder how we will determine when to show what? I believe we statically know that an extension with name X isn't enabled but we cannot introspec on what features we are missing out, e.g things like hover, completions etc aren't statically declared but "appear" at runtime, therefore we cannot detect the lack of such. To make matters more complicated there can be other useful extensions that do work in restricted mode and we don't want to treat them unfairly by such prominent warnings...

**Comment by daviddossett** [comment]
Thanks for the context @jrieken. I wonder if it would make more sense to tie this into the language status as a more general warning specific to a language/language extension instead?

**Comment by jrieken** [comment]
> I wonder if it would make more sense to tie this into the language status as a more general warning specific to a language/language extension instead?

Yeah, maybe. The challenge is that the language status is computed dynamically via code and in this case the code doesn't even run... I wonder if for untrusted mode we should look at something pragmatic like a list of well-know extensions that would provide a good language experience if they are not disables due to trust. We could use that information to drive the UI and we should also think about re-using the UI for the language status information

**Comment by daviddossett** [comment]
> I wonder if for untrusted mode we should look at something pragmatic like a list of well-know extensions that would provide a good language experience if they are not disables due to trust

Sounds like a reasonable approach. What sort of criteria are you thinking about? # of extension installs?

**Comment by jrieken** [comment]
Yeah, we could use installed extensions but another idea that was brought up is to use let extensions specific themselves. E.g when signaling limited support for untrusted workspaces they could include more information that targets specific files and/or features

**Comment by jrieken** [comment]
cc @sbatten for more details when signaling limited features
