### ISSUE TITLE
Extension update visible but not installable due to `engines`

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#13303]
- VSCode Version: 1.5.3
- OS Version: macOS sierra

Steps to Reproduce:

1. Install the [final-newline](https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline) extension in VS Code 1.5.3 (this is important!)
2. It will install `final-newline@0.2.0` because that one was target to [0.10.x](https://github.com/SamVerschueren/vscode-final-newline/blob/v0.2.0/package.json#L7)
3. Enable the extension and search again for the `final-newline` extension in the extension list. It will show that their is an update available, namely `0.3.0`, but that version is targetted to [^1.6.x](https://github.com/SamVerschueren/vscode-final-newline/blob/master/package.json#L7)
4. You can try to install the plugin, which looks like it succeeds, but when restarting VS Code, it will again show up as update.

Extension list should show `0.2.0` as `0.3.0` is not supported by VS Code 1.5.3

<img width="302" alt="screen shot 2016-10-06 at 19 29 29" src="https://cloud.githubusercontent.com/assets/1913805/19163165/3ead5d42-8bfb-11e6-977e-6cc29cef7d6e.png">

After installing the extension and enabling it, this is what shows up in the extension list

<img width="303" alt="screen shot 2016-10-06 at 19 30 26" src="https://cloud.githubusercontent.com/assets/1913805/19163210/681d8332-8bfb-11e6-822d-a3996ca85eb4.png">

So it succesfully installs the correct version, only the notification shouldn't be showing.

FYI @joaomoreno

**Comment by SamVerschueren** [comment]
That also makes me wonder, is `engines` fully semver compatible? Because I used `^1.6.x` which means that it won't work on `2.0.0` if it ever comes out. So I might be better using `>=1.6` instead?

**Comment by joaomoreno** [comment]
#11573

Yes, it's the `semver` format.

**Comment by SamVerschueren** [comment]
Thanks @joaomoreno !
