### ISSUE TITLE
.env file detected incorrectly as inf file

### ISSUE THREAD

**Issue by arikal** [microsoft/vscode#133165]
Issue Type: <b>Bug</b>

1. Open an environment variables file named `.env`
2. See in bottom-right that the file was detected as an `inf` file

This means that the file isn't handled by the configured extension, syntax highlighting is incorrect and adding comments adds `;` instead of `#` which is invalid.

Note that it _does_ handle files like `.env.example` correctly.

Workaround is to click _Select Language Mode_ and choose _Environment Variables_, but this must be done each time the file is opened.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-7633-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|22.99GB (8.04GB free)|
|Process Argv|--unity-launch --crash-reporter-id b64626b7-78ff-41e3-b0f9-d4559c7f9764|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.7.1
vue-peek|dar|1.0.2
gitlens|eam|11.6.0
phpunit|ema|4.1.1
php-debug|fel|1.18.0
code-runner|for|0.11.5
go|gol|0.27.2
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.16.1
remote-containers|ms-|0.194.0
cpptools|ms-|1.6.0
php-docblocker|nei|2.4.0
vetur|oct|0.34.1
vim|vsc|1.21.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by IllusionMH** [comment]
/duplicate of #132173

You need to update to latest stable version 1.60.1

**Comment by arikal** [comment]
Sorted, thank you.
