### ISSUE TITLE
Paths containing hash symbol (#) in Problems panel break file link

### ISSUE THREAD

**Issue by svArtist** [microsoft/vscode#133159]
Issue Type: <b>Bug</b>

0. Be on Windows?
1. Create project with a "#" in its path, like "D:\[Projects]\C#.NET\Geistreich\Geistreich.csproj"
2. Have a "problem", click on the file link to go to the source

![Capture 2021-09-15 14-36-38](https://user-images.githubusercontent.com/13470026/133436132-96629b3c-98f8-4110-9ed8-20e95ac97882.png)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3588)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.91GB free)|
|Process Argv|--crash-reporter-id 143bf0e7-84bd-4340-b6a3-b569938d752e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-export|asl|1.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
working-sets|ber|1.4.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.25
open-files|Div|0.0.4
file-icons|fil|1.0.29
csharp|ms-|1.23.15
brackets-keybindings|ms-|0.1.1
vscode-opened-editors|Nic|0.0.8
prettier-now|rem|1.4.9
tabster|rib|0.0.6
vscode-editor-group-minimizer|suh|1.3.2
reopenclosedtab|uyi|1.1.0
vscode-backup|Wes|0.0.6

</details>

**Comment by sandy081** [comment]
Please file the issue against the sharp extension as the extension is responsible for these problems.
