### ISSUE TITLE
Freezing when running long time cells after windows session lock

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode#133170]
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version: v2021.8.2041215044
-   Python Extension version: v2021.9.1230869389
-   OS and version: Windows_NT x64 10.0.19043
-   Python version: python 3.9.6
-   Type of virtual environment used : conda 4.10.3
-   Jupyter server running: Local

## Problem

While having long time running cells (pytorch conv net training) if I lock the session for some time or stay away until the screen turns off and then come back to vscode, it always ends up freezing, and I get a popup with the message `The window is no longer responding` with options for reopening, waiting and closing.

If I choose to wait it never recovers and I am forced to close, sometimes losing unsaved changes to the notebook. This seems to be just a display issue of vscode since under the hood it keeps advancing without issue as can be seen on tensorboard logs. The cell animation for running keeps ongoing (the cycling arrows and blue bar sliding) but no change in the execution time or the cell output.  From the looks of it, the displayed time is from the moment the session was locked/screen turned off.

This may be related to microsoft/vscode#78138 since the behavior is very similar, and I am also working on a system with dual display with different resolutions and one on portrait mode, and with an NVIDIA gpu. Although disabling the screen on portrait mode doesn't make a difference.

How should I proceed to debug this issue?

Edit: Added some details.

Edit2: I don't know if this is relevant, but I am using `pytorch lightning` which uses `tdqm` to display a progress bar. I am going to disable the progress bar now and see if this avoids the issue.

**Comment by grudloff** [comment]
> This would be a VS code issue (not a jupyter extension problem). Transfering.

Thanks, I wasn't really sure myself if it had to go on jupyter or here.

**Comment by rebornix** [comment]
I wonder if this is some memory leak. @grudloff can you check the CPU and Memory usage of VS Code processes and share with us? You can follow the guidance here https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by grudloff** [comment]
Right now vscode is frozen. This is the output for `code --status`:

```
Version:          Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS Version:       Windows_NT x64 10.0.19043
CPUs:             AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)
Memory (System):  15.95GB (7.17GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id c296c18b-d270-44c0-98dd-9c0a4564e2f6
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              enabled_on
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0      137   14412  code main
    1      135    5536     gpu-process
    8      427    5876     window (ÔùÅ Convolutional_serial pytorch.ipynb - Simulaciones - Visual Studio Code)
    0      252    7980       extensionHost
    0      331    1088         electron_node bundle.js
    0        9    8964         C:\Users\Usuario\.conda\envs\pytorch-gpu\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
    0        5   12384           console-window-host (Windows internal process)
    0      772   15012           electron_node qy.js
    0      108   15148         electron_node main.js
    0       14   13120       watcherService
    0        5   13160         console-window-host (Windows internal process)
    0       66    8900     utility
    0       95   10436     window (undefined)
    0       88   10600     shared-process
    0       66   12200       ptyHost
    0       63   15192     crashpad-handler

Workspace Stats:
|  Window (ÔùÅ Convolutional_serial pytorch.ipynb - Simulaciones - Visual Studio Code)
|    Folder (Simulaciones): 96 files
|      File types: ipynb(27) pyc(13) py(12) png(5) sqlite3(5) gitignore(2)
|                  md(2) txt(2) pkl(2) npy(2)
|      Conf files: settings.json(1)
```

**Comment by grudloff** [comment]
I added some additional details to the description.

**Comment by grudloff** [comment]
Jackpot! The issue has to do with the `tdqm` progress bar. I just left a cell running overnight with no progress bar and it finished without a problem.

**Comment by rebornix** [comment]
Will investigate next week and see why it's blocking the UI.

**Comment by rebornix** [comment]
Tried `tqdm` locally but didn't reproduce. It seems that the tqdm is generating the text output for progress, not sure how it would freeze the UI, especially that from the CPU info shared above https://github.com/microsoft/vscode/issues/133170#issuecomment-920461725, both the CPU and Memory are in reasonable shape.

I'm interested in seeing https://github.com/microsoft/vscode/issues/78138 being fixed soonish and then we revisit if this one still reproduces.

**Comment by rebornix** [comment]
Closing for now as we have pushed multiple perf fixes for it, we can reopen if it's still an issue.
