### ISSUE TITLE
Using shift + enter to insert new line instead of accept suggestion

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#133135]
```
Version: 1.61.0-insider (Universal)
Commit: f66a3e06bcb9f000e5dc0ad0040ff9b32fc75c78
Date: 2021-09-14T05:14:54.400Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

When I press shift + enter, result in accepting the suggestion,  which should insert new line would be better.

![image](https://user-images.githubusercontent.com/41773861/133363276-fd13ed8c-2a39-4de8-8855-3c3a456f7389.png)

**Comment by jrieken** [comment]
We can tweak this but only when there are no alternative suggestions

**Comment by ArturoDent** [comment]
Not sure I understand your issue but you could disable the <kbd>Shift</kbd>+<kbd>Enter</kbd> keybinding there:

```jsonc
{
  "key": "shift+enter",
  "command": "-acceptAlternativeSelectedSuggestion",
  "when": "suggestWidgetVisible && textInputFocus"
}
```
