### ISSUE TITLE
workbench.action.terminal.newWithProfile changes user settings

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#133183]
Issue Type: <b>Bug</b>

Bind a key to `workbench.action.terminal.newWithProfile`.

Use it to start any terminal different from your default choice.

Check your settings - the default selected terminal is changed.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.64GB free)|
|Process Argv|//DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/caduceus/bach-x5-gui/caduceus-phpweb --crash-reporter-id d05c8b79-33ba-42b6-8c5c-db1f4b0e913c|
|Screen Reader|no|
|VM|0%|
</details>

<details>
<summary>Configured terminals</summary>
User settings:

```json
{
    "terminal.integrated.defaultProfile.windows": "Cygwin Bash",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Cygwin Bash": {
            "path": "C:\\Programs\\Cygwin_64\\bin\\bash.exe",
            "args": ["-i"]
        },
        "Git Bash": {
            "path": "C:\\Programs\\Git\\bin\\bash.exe",
            "args": ["-i"]
        }
    }
}
```

Workspace settings:
```json
{
    "terminal.integrated.profiles.windows": {
        "PHP CLI server": {
            "path": "C:\\Programs\\PHP\\bin\\php.exe",
            "args": [
                "-e",
                "-d", "zend_extension=php_xdebug.dll",
                "-d", "internal_encoding=UTF-8",
                "-d", "include_path=${workspaceFolder}/dependencies/pear",
                "-S", "0.0.0.0:8080",
                "-t", "${workspaceFolder}/tmbase",
                "${workspaceFolder}/cli-router.php"
            ],
            "icon": "tools",
            "overrideName": true
        },
        "SSH to host": {
            "path": "C:\\Programs\\Cygwin_64\\bin\\ssh.exe",
            "args": [
                "-R", "9005:localhost:9005",
                "-L", "1521:172.16.6.22:1521",
                "-D", "4080",
                "daemon-ec.darkdragon.lan"
            ]
        }
    },
}
```
</details>

In example, I start SSH to dev. host to connect IDE's xdebug server. Which SUDDENLY! changes my choice of "Cygwin Bash" default terminal.

**Comment by meganrogge** [comment]
I can't reproduce this. Can you see if you can in insider's?

**Comment by AnrDaemon** [comment]
You are spawning new shells in view.
As I said, you have to change default location to "editor" and sometimes restart VS Code for it to take effect.
Then use command palette or shortcut to create a terminal.
Only then you will see the effect.
Yes, I just downloaded the fresh update and yes, I can reproduce the problem.

**Comment by Tyriar** [comment]
@AnrDaemon that's the repro I was trying, can you share your settings.json file? Maybe something else is impacting it too? Also do you see any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by AnrDaemon** [comment]
There's one error, but it seems unrelated.

```
log.ts:301   ERR Cannot refresh property when process is undefined: Error: Cannot refresh property when process is undefined
    at k.refreshProperty (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1713:24164)
    at ii.refreshProperty (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2756:8139)
    at async ii._updateProcessCwd (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2755:968)
```

How did I repro'd it:
1. Removed settings directory entirely.
2. Opened VS code with an empty workspace.
3. Trusted the workspace.
4. Opened settings.
5. Entered "terminal.integrated.default" in search field.
6. Changed two settings mentioned.
7. F1 - "create new terminal" - a new tab in editor opened with command prompt.
8. Exit the terminal.
9. F1 - "new terminal with profile" - "PowerShell" - new powershell console opened.
10. Exit powershell - at the settings page the default terminal is now powershell.

```json
{
    "terminal.integrated.defaultLocation": "editor",
    "terminal.integrated.defaultProfile.windows": "PowerShell"
}
```
