### ISSUE TITLE
launching chrome debugger with React reports: crbug/1173575, non-JS module files deprecated.

### ISSUE THREAD

**Issue by JonathanMEdwards** [microsoft/vscode#133190]
Does this issue occur when all extensions are disabled?:
Yes

- VS Code Version:

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1. npx create-react-app my-app
2. cd my-app
3. code --disable-extensions
4. create Launch Chrome debug config
5. launch chrome

Chrome window says can't connect. 
Debug console shows: crbug/1173575, non-JS module files deprecated
[Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1173575)

**Comment by connor4312** [comment]
> Chrome window says can't connect.

In the steps you provided, there's no place where you run `npm run start` or `yarn start`. This is needed otherwise the dev server will not exist. If this is not the issue you're facing, please provide more details.

**Comment by JonathanMEdwards** [comment]
Damn, sorry! I just had the wrong port #, saw the crbug trap and that led me down this wild goose chase to repro it.
