### ISSUE TITLE
VS Code Memory/CPU out of control

### ISSUE THREAD

**Issue by SeanBintleyThrive** [microsoft/vscode#133157]
Issue Type: <b>Bug</b>

not sure. I'm also running Vs2022 preview 4 with a preview version of dotnet 6 installed. The .Net Host sometimes just spirals out of control in terms of memory, and then CPU. not sure what it's doing or why. Restarting vs code solves the issue for a while

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (5.74GB free)|
|Process Argv|--crash-reporter-id 28974648-7414-41a2-a253-27dfde052753|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
azurite|Azu|3.14.2
vscode-markdownlint|Dav|0.43.2
gitlens|eam|11.6.0
vscode-solution-explorer|fer|0.4.4
vscode-vstest-framework|gfr|0.0.3
Ionide-fsharp|Ion|5.7.3
vscode-icon-theme|jtl|1.6.6
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
vscode-azurecache|ms-|0.1.0
vscode-azurefunctions|ms-|1.5.1
vscode-azurelogicapps|ms-|1.0.4
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.16.1
vscode-logicapps|ms-|1.0.20
csharp|ms-|1.23.15
dotnet-interactive-vscode|ms-|1.0.2462010
vscode-dotnet-pack|ms-|1.0.4
vscode-aks-tools|ms-|0.0.9
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
azure-account|ms-|0.9.8
powershell|ms-|2021.9.0
vs-keybindings|ms-|0.2.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
markdown-preview-enhanced|shd|0.6.0
vscode-fileutils|sle|3.4.5
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgst2:30361792
vssid140cf:30363604
vssur157:30365996

```

</details>

**Comment by aeschli** [comment]
Can you find out which process is causing the CPU load?

https://github.com/microsoft/vscode/wiki/Performance-Issues has more information
