### ISSUE TITLE
VS Code crashes after latest Windows Update

### ISSUE THREAD

**Issue by nCubed** [microsoft/vscode#133181]
Issue Type: <b>Bug</b>

After updating Windows, VS Code is now crashing whenever a file is opened.

Things I've tried:
- disable all extensions
- clear AppData\Roaming\Code\User\workspaceStorage 
- clear AppData\Roaming\Code\CachedData
- rebooting Windows

Not quite sure what other info I can include. Any suggestions would be appreciated as I'm basically unable to do any work with VS Code until this is resolved.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

Edition: Windows 10 Pro
Version: 20H2
Installed on: ‎8/‎13/‎2021
OS build: 19042.1237
Experience: Windows Feature Experience Pack 120.2212.3530.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.83GB (56.46GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.10.2
classic-asp|ili|0.0.4
rainbow-csv|mec|1.9.1
formate|Mik|1.1.6
csharp|ms-|1.23.15
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
powershell|ms-|2021.9.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
code-spell-checker|str|2.0.4
vscode-ruby|win|0.28.0

</details>

**Comment by nCubed** [comment]
F/U: I decided to run the x64 installer on top of my existing install and everything appears to be working as intended again. I will leave this open for a couple of days to verify if any further crashes are encountered.

**Comment by deepak1556** [comment]
If you are still facing the crashes, please attach the crash reports following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports. Thanks!

**Comment by nCubed** [comment]
After running the installer on top of the existing install, no issues have surfaced. Going to close this as a space time continuum anomaly.
