### ISSUE TITLE
August 2021 Endgame Recovery 2

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#133189]
- [x] Create a milestone `<Month> <Year> Recovery` **owner**
- [x] Bump the version number **owner**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22August+2021+Recovery+2%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit **@rzhao271**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit **@alexr00**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 **@bpasero**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal **@jrieken**
    - [x] Intel **@jrieken**
    - [x] Intel server **@jrieken**
    - [x] Apple Silicon **@jrieken**
  - [x] Linux x64
    - [x] deb **@aeschli**
    - [x] rpm **@aeschli**
    - [x] archives **@aeschli**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) **@aeschli**
  - [x] Linux server **@chrmarti**
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.60.1)

**Comment by jogo-** [comment]
Why was it re-released 22 hours ago by @sandy081 ?
https://github.com/microsoft/vscode/releases/tag/1.60.2

**Comment by sandy081** [comment]
I mistakenly deleted and hence recreated that. Sorry about that.
