### ISSUE TITLE
Typescript intellisense looks broken after dot completion

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1331]
https://youtu.be/whtggr9RFXs
1. Trigger intellisense with <kdb>dot</kbd> works.
2. Manual trigger doesn't work

Video recorded at gitServices.ts#768

**Comment by joaomoreno** [comment]
Works fine in JavaScript.

**Comment by dbaeumer** [comment]
Did some investigation but wasn't able to reproduce. I also check that the position is the same whether the code assist is triggered by . or by hand.

**Comment by dbaeumer** [comment]
Closing since I can't reproduce this anymore. Please ping if you still see the issue.
