### ISSUE TITLE
git hide left diff pane button

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#13314]
(v1.5.3 osx) This is me checking my code
![image](https://cloud.githubusercontent.com/assets/863731/19171397/c2c80250-8c1c-11e6-9f6b-558b03b0fdc5.png)

And this is me developing :P
![image](https://cloud.githubusercontent.com/assets/863731/19171369/a2d8f792-8c1c-11e6-9abc-b38cf63eb5d6.png)

Am I the only one that ends up doing this? Yes I know there is a inline view and a
![image](https://cloud.githubusercontent.com/assets/863731/19171317/575517f6-8c1c-11e6-90e5-58ef4da90119.png) 
go to file button, but thats not the same as I am doing :)

Can you make a hide left diff pane button please? And by left I mean the left diff editor view not the git side bar :)

Location and how the new icon button should look like is ofcourse open for discussion.

<img width="1025" alt="screen shot 2016-10-10 at 20 14 03" src="https://cloud.githubusercontent.com/assets/863731/19246767/45d7ed8c-8f28-11e6-8781-dab964d4fbfd.png">
 
EDIT: rjmunro pointed out that you can right click and do `open change` in the sidebar so no extra button needed, but there is no diff highlighting when you do that so that still needs to be implemented.

**Comment by gertcuykens** [comment]
Sugestion: Maybe by double clicking on the tab to hide the left pane? 
![image](https://cloud.githubusercontent.com/assets/863731/19208708/174e3772-8cfe-11e6-88e3-74bc9109b5e3.png)

**Comment by joaomoreno** [comment]
So... ultimately you just want the diff decorators on the editor, instead of the simpler gutter ones?

![image](https://cloud.githubusercontent.com/assets/22350/19229680/b000ed0c-8ecf-11e6-99bf-f596e6f51202.png)

**Comment by gertcuykens** [comment]
Just the possibility to hide the left pane, but still have the git side bar to switch between changed or new files.

<img width="1025" alt="screen shot 2016-10-10 at 20 14 03" src="https://cloud.githubusercontent.com/assets/863731/19246472/ce94e834-8f26-11e6-9bfb-a4662277ece9.png">

**Comment by rjmunro** [comment]
You can right click on the file in the sidebar and do "Open File", instead of "Open change". Is that what you want?

**Comment by gertcuykens** [comment]
nope sorry, because that removes the diff coloring and highlights, but it does keep the git sidebar open, thats a start :) So instead of a extra button, `Open change` would be ideal for me if it also keeps the diff highlights like the right side does when you just click on it.

![image](https://cloud.githubusercontent.com/assets/863731/20361958/ebbfbf62-ac39-11e6-8614-f2da74312133.png)

**Comment by joaomoreno** [comment]
We're gonna go with the Side-by-Side view as the answer for this one.

![image](https://cloud.githubusercontent.com/assets/22350/25390322/7e3d7d72-29d3-11e7-9b5d-4d40b61f0e4a.png)

![image](https://cloud.githubusercontent.com/assets/22350/25390325/81b45872-29d3-11e7-89ff-898e94c9ab50.png)
