### ISSUE TITLE
sequence doesn't work when set in title/description

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133102]

**Comment by rzhao271** [comment]
What are some verification steps for this issue? When I put "${process}${separator}${sequence}" for the title setting, I get "pwsh - pwsh" on Windows, but every other terminal type seems to only display the process (e.g. "bash")

**Comment by meganrogge** [comment]
@rzhao271 you need a sequence that matches this pattern. to verify this was fixed, I had to comment out the following conditional because none of the shells I had set sequence

https://github.com/microsoft/vscode/blob/75e3411fd3a8197060db895d05cacace14768e4f/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1856

**Comment by rzhao271** [comment]
A sequence of the form `<user>@<computer-name>` shows up when I run WSL.
