### ISSUE TITLE
Enter button does not go to new line 

### ISSUE THREAD

**Issue by bradbart** [Microsoft/vscode#13315]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14939

Steps to Reproduce:

1. Press enter 
2. Notice that cursor remains in the same place

**Comment by gertcuykens** [comment]
Screenshot please because I think we are missing allot of extra information here?

**Comment by bpasero** [comment]
This is a windows bug from using Windows insiders channel.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12929
