### ISSUE TITLE
git blame insertions in between code

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vscode#133175]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version: windows 10

Steps to Reproduce:

1. Turn on git lens plugin
2. Make some commits
3. Type code
4. Sometimes the git lens history inserts in between the code on the line you are typing 

This issue has been raised in the git lens repo.
https://github.com/eamodio/vscode-gitlens/issues/1477

**Comment by lszomoru** [comment]
Closing issue as it is being tracked in the GitLens repo - eamodio/vscode-gitlens#1477
