### ISSUE TITLE
Codespaces: Debugging is broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#133178]
Steps to repro:

- Create a new Codespace **in Web** using a repo with launch.json. Eg: https://github.com/microsoft/vscode-remote-try-node
- Start debugging (Press `F5`)

🐛 Prompts to select the debugger type

![image](https://user-images.githubusercontent.com/10746682/133475379-48696ff6-3cc3-4b66-b4c0-2a78eaaf1cd5.png)

Expected: Starts debugging without any prompts

**Comment by sandy081** [comment]
Fix of https://github.com/microsoft/vscode/issues/125259 triggered this. 

Root cause: When asked to reload configuration, configuration service is reloading from the cache instead from real folder.

@isidorn @roblourens I see you are asking to reload configuration always

https://github.com/microsoft/vscode/blob/1fd7873ceeddc6a15e61c5b5d363c5fbd5226963/src/vs/workbench/contrib/debug/common/debugUtils.ts#L321-L321

I think you shall reconsider this and ask it only when needed.Because, it reloads all configurations, eg: user configuration (settings, tasks), remote user settings, workspace configuration, folder configurations (settings, tasks, launches). So it will impact perf.

**Comment by joshspicer** [comment]
Repros only on the web for codespaces (not with a codespace connected thru vscode), with the error:
`You don't have an extension for debugging 'JSON with Comments'. Should we find a 'JSON with Comments' extension in the Marketplace?`

**Comment by isidorn** [comment]
@sandy081 thanks a lot for fixing this 👏 
I have added the `reloadConfiguration` code because it was probably needed in the past. @roblourens feel free to remove some of this calls as part of some debt week.

**Comment by roblourens** [comment]
I think this should just go out with the second recovery release. I opened another issue for looking at the reloadConfiguration usage

**Comment by roblourens** [comment]
It's working in codespaces insiders 🎉
