### ISSUE TITLE
Resource Monitor opening automatically when program is run

### ISSUE THREAD

**Issue by Amanda-Vasas** [microsoft/vscode#133120]
I made a post [here ](https://github.com/microsoft/vscode/issues/132954) that was auto-answered by a bot who didn’t help me.

Apparently I have an extension active for Python on VSC that is opening Resource Monitor automatically when I run a program. The only active extension I have installed is the main Python extension. If this could be something inside there I would love some assistance as to how to shut it off. If I somehow activated an extension, WHICH extension is it so I can check it out, because my VSC only says I have the one main Python extension activated.

Thanks!

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues

**Comment by roblourens** [comment]
It would probably help to include details about how you are running the program and what the program is
