### ISSUE TITLE
Enter key does not work; ctrl+enter does

### ISSUE THREAD

**Issue by judnich** [Microsoft/vscode#13310]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.14939

The enter key does not create a newline as expected. Must press CTRL+ENTER for it to work. This behavior does not exist in any other app I have.

Steps to Reproduce: Not sure how to reproduce except that restarting Visual Studio Code does not solve the problem.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/12929
