### ISSUE TITLE
Run by line in Notebook took a long time to get started

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#133100]
Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

It took approximately 20 seconds to start Run By Line for this Notebook: https://github.com/claudiaregio/data-science
14:15 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

**Comment by DonJayamanne** [comment]
@tanhakabir does it (delays) make a difference if you are not recording?

**Comment by roblourens** [comment]
That delay is just starting the kernel and checking the ipykernel version, and in theory you would see basically the same delay when running a cell for the first time. Second time should be fast.

**Comment by tanhakabir** [comment]
Closing because it was mainly slow due to screensharing
