### ISSUE TITLE
"New file" and "New folder" actions on directory hover in file explorer

### ISSUE THREAD

**Issue by gulshan** [microsoft/vscode#133168]
It would be nice to have the `New file` and `New folder` action icons show up right-aligned, on hover for the folders/directories in the File Explorer. It will be similar to how theses actions shows up on hover for the file explorer "Header" now.

**Comment by JacksonKearl** [comment]
We do not support buttons in the explorer tree, but these actions are available on the context menu of the explorer:
![image](https://user-images.githubusercontent.com/8586769/134572941-a7c32221-5d4e-4c22-b726-b4394b4d4f2b.png)
