### ISSUE TITLE
Shift+Enter doesn't search previous

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/vscode#133119]
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22458

1. ctrl+f to open search box
2. type something in so that you can search (something that has multiple instances in the document)
3. press enter --> search next
4. press shift+enter --> BUG

Expected: search previous
Actual: nothing happens

**Comment by roblourens** [comment]
Is it possible that some other keybinding is conflicting? Check the keybindings editor for conflicts, or run "Toggle Keyboard Shortcuts Troubleshooting" to see what runs when you press shift+enter
