### ISSUE TITLE
the full name of the task is now displayed

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133113]
![task](https://user-images.githubusercontent.com/29464607/133311736-7ab8ad85-8e50-4179-9c8e-269ac1eb262d.PNG)

**Comment by Tyriar** [comment]
Does tasks do this automatically in a multi-root workspace now?

**Comment by meganrogge** [comment]
Oh good question

**Comment by meganrogge** [comment]
Yep they do
