### ISSUE TITLE
Large notebook on remote server can be slow to update

### ISSUE THREAD

**Issue by zxvix** [microsoft/vscode#133171]
I often work with large notebooks on a remote server via the remote-ssh plugin. Recently I found that large notebooks can often become very slow responding to edits. 

The problem seems to be, every edit to the notebook will trigger an upload of the whole notebook to the server (I have an internet speed monitor to help me see this).  Therefore even a small edit will take notebook_file_size/connection_speed time to save. And cells will not run until saving is complete, with makes large notebooks slow to work with.

And what's more, sometimes the saving never completes and vscode has to be reloaded.

## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: local: macos 11.5.2 remote: ubuntu 18.04
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: tried both Local and Remote

I have attached a notebook to reproduce this issue. 
[large_notebook.ipynb.zip](https://github.com/microsoft/vscode-jupyter/files/7169211/large_notebook.ipynb.zip)

I found that this happens with both Local and Remote jupyter servers.

**Comment by rebornix** [comment]
@zxvix I assume that you have auto save turned on, right?

**Comment by zxvix** [comment]
> @zxvix I assume that you have auto save turned on, right?

Yes, previously I had auto save turned on. Now I tried turning off auto save. To my surprise, every time I type something in the notebook, it will trigger an upload of  ~24MB for a 16MB notebook, even with auto save turned off.

**Comment by jrieken** [comment]
> To my surprise, every time I type something in the notebook, it will trigger an upload of ~24MB for a 16MB notebook, even with auto save turned off.

I cannot reproduce that. Can you please update your steps and/or make sure that you have auto-save disabled? Also check if you maybe have any other extension enabled that causes save or save-all (disable all extensions except for ipynb-support)
