### ISSUE TITLE
Preferences: Configure Language Specific Settings... not entry new line in setting.json 

### ISSUE THREAD

**Issue by thanh125643** [microsoft/vscode#133117]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Run Preferences: Configure Language Specific Settings... in Command Palette
2. Choose any language

Expected results:
Open setting.json with new entry language i choose

Actual results:
It just open setting.json but dont have new entry language

And also Configure "language name" Language base setting... not work either

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.22454
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.49GB free)|
|Process Argv|--crash-reporter-id fcf059d5-6e9a-4cd5-86b7-7ace50964434|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|15.60GB (6.65GB free)|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.3.0
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.25
es7-react-js-snippets|dsz|3.1.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
vscode-power-mode|hoo|2.2.0
autofilename|Jer|0.1.3
vsc-python-indent|Kev|1.14.2
fluent-icons|mig|0.0.12
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.16.1
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.6.1
indent-rainbow|ode|8.0.0
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
copy-copy-paste|roc|0.0.7
music-time|sof|2.2.22
swdc-vscode|sof|2.5.24
tabnine-vscode|Tab|3.4.27
bootstrap4-vscode|the|6.1.0
learn-vim|vin|0.0.27
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.400
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.11.4

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by roblourens** [comment]
Yeah this doesn't work anymore, it stops here because the defaultValue is `undefined`:

https://github.com/microsoft/vscode/blob/fd4a3fc62a770c91d6bc63a855b11ba17366c1f3/src/vs/workbench/services/preferences/browser/preferencesService.ts#L552-L552

I don't know how it's supposed to work?
