### ISSUE TITLE
just white blank page that immediately closed! 

### ISSUE THREAD

**Issue by mehdraz** [microsoft/vscode#133115]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1 
- OS Version:Ubuntu Impish Indri 

Steps to Reproduce:

1. after updating my vs code to 1.60 and upgrading my distro, i faced this problem
![Screenshot from 2021-09-15 10-24-35](https://user-images.githubusercontent.com/64796646/133378391-dc468b5e-3ecf-4885-b56e-12d314187bcd.png)
![Screenshot from 2021-09-15 10-25-54](https://user-images.githubusercontent.com/64796646/133378541-a4c779de-d3e4-4792-8648-c0fdc78e340e.png)
![Screenshot from 2021-09-15 10-26-45](https://user-images.githubusercontent.com/64796646/133378597-c0e9136e-ebb2-4fb7-8e24-c9424858a6ae.png)

2.
[code.bug.txt](https://github.com/microsoft/vscode/files/7164381/code.bug.txt)

**Comment by mehdraz** [comment]
i had  this problem with version 1.60.0 also

**Comment by rzhao271** [comment]
It looks like an issue with the GPU. As a workaround, you can try running VS Code in the command line with `code --disable-gpu`

**Comment by mehdraz** [comment]
> It looks like an issue with the GPU. As a workaround, you can try running VS Code in the command line with `code --disable-gpu`

i tried to solve this problem with --disable-gpu and --disable-extensions but never work

**Comment by mehdraz** [comment]
by  changing driver to X.org X server - nouveau problem solved

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/132609

Will be fixed in next insiders release.

**Comment by borgdylan** [comment]
@deepak1556 please pass this along tot he azure data studio team. they have the same issue.
