### ISSUE TITLE
TypeScript: Importing file from parent directory ("../") causes invalid autocomplete

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/vscode#13319]
- VSCode Version: 1.5.3
- OS Version: Linux Mint 17.3

Steps to Reproduce:

1. Open a TypeScript file
2. Type `import {} from ".`
3. Type `.` again

**Expected:**
I can import modules from a parent directory with no hassle.

**Actual:**
It is filled in automatically to be come `import {} from ".tslint.`, with "tslint" possibly replaced by some other package that happens to be in my `package.json`.

**Comment by waderyan** [comment]
@andy-hanson thank you for opening this issue. What extensions do you have installed? This is not a feature that is available without an extension.

**Comment by andy-ms** [comment]
@waderyan I uninstall all extensions and still get this behavior.

**Comment by andy-hanson** [comment]
I don't have any extensions installed, but I do have the setting `"typescript.tsdk": "/home/andy/.nvm/versions/node/v6.7.0/lib/node_modules/typescript/lib"`, without which the problem doesn't happen.

**Comment by waderyan** [comment]
What is the version of TS?

**Comment by andy-hanson** [comment]
`2.1.0-dev.20161007`

**Comment by waderyan** [comment]
@andy-hanson you are the bleeding edge! Ok this issue falls onto the TS server team. Sending their way...

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11457
