### ISSUE TITLE
debugger contribution point should support a when clause

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#133146]
Just like `menus` and `taskDefinition` contribution points the `debugger` contribution point should also support `when` clauses. 

Here's where we handle the debugger extension point
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L63

Here's where we define the schema https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugSchemas.ts#L14

Here's how Alex Ross does this for tasks 
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1663

I think the [debugAdapterManager](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L35) would have to evaluate all the `when` clauses when being asked for a list of debuggers and when setting the `debuggersAvailable` context key and we should be good.

@roblourens let me know if you are busy this milestone and I can also look into this
fyi @weinand

**Comment by isidorn** [comment]
We should also consider the `breakpoints` contribution point. Though this is lower priority since this contribution is not so visually aggressive.

**Comment by roblourens** [comment]
Thanks for the starting points. I guess if you try to run a launch config for a type that is disabled, we should show a special error message instead of the generic "debug type `xyz` not supported" also

**Comment by isidorn** [comment]
@roblourens makes sense, but I would not worry about that for now. Since in practice it will not even be possible to start debugging since none of the debuggers should be enabled in the `web`.
The only case where I see this is if the user has Mock Debug installed and Python and presses `F5`. Since if the user did not have Mock Debugging all the Debug UI will be disabled and `F5` would not even work.

**Comment by weinand** [comment]
@isidorn IIRC, LiveShare is another debugger that works in the Web. So we can ignore Mock Debug for realistic scenarios, but not LiveShare.

**Comment by isidorn** [comment]
@weinand good point. I have created this item as follow up so we tackle this in the future: https://github.com/microsoft/vscode/issues/133728

**Comment by sandy081** [comment]
@isidorn @roblourens Any steps to verify this?

**Comment by isidorn** [comment]
I think @karrtikr would be the best to verify this since he is adopting this on the Python side :)
If that is not possible, I will provide steps.

**Comment by connor4312** [comment]
I can verify

**Comment by connor4312** [comment]
The prompt when trying to start the debugger works well, but there might be other cases we want to update based on enablement. I opened issues for a couple of them 🙂
