### ISSUE TITLE
The item 'Code.exe' that this shortcut refers to has been changed or moved.

### ISSUE THREAD

**Issue by Apurva-Nagar** [microsoft/vscode#133182]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1 (user version)
- OS Version: Windows_NT x64 10.0.19042
- Using WSL2 and WSL VSCode extension.

Steps to Reproduce:

1. Using `code .` command or using the shortcut icon to open VSCode.

#### More Information

 - My VSCode was working fine till yesterday. I started facing the problem above after starting my PC today.
 - There is now another directory `-` in my Microsoft VS Code directory which has the Code.exe and many other files
 - It seems to me like some sort of update didn't end properly and that has resulted in this?

<img width="539" alt="image1" src="https://user-images.githubusercontent.com/8392802/133481958-70da3f4f-2958-489d-a79c-3196ad39a4b3.PNG">
<img width="553" alt="image2" src="https://user-images.githubusercontent.com/8392802/133481965-477a7346-56c3-4ac8-a172-411edae393ab.PNG">

How can I resolve this? Thanks

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
