### ISSUE TITLE
Why vscode update automatically without inform me?

### ISSUE THREAD

**Issue by lawweiliang** [microsoft/vscode#133132]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: Window 10

Steps to Reproduce:

1. Vs Code was updated to the latest version without even asking my permission?
    This is scary. How to avoid this?

![image](https://user-images.githubusercontent.com/34936929/133359623-5d27d6c2-4996-4ea8-b876-f9ddc2597e79.png)

**Comment by TarunavBA** [comment]
@lawweiliang It is because you have set automatic updates on. 🤷‍♂️

**Comment by TarunavBA** [comment]
@lawweiliang Try changing that value in settings to `off`.

**Comment by lawweiliang** [comment]
@TarunavBA 
 My is default, I did not modified any automatic updates. Is `default` mean `automatic update`?

![image](https://user-images.githubusercontent.com/34936929/133370778-9530de68-dfe4-43cc-a7ab-510bb7925f93.png)

**Comment by TarunavBA** [comment]
@lawweiliang Click on that drop-down and you can see `off` option, click on that.

**Comment by lawweiliang** [comment]
@TarunavBA 
In another word, automatic update is on by default, can I say so?
Hmm, I need to inform my buddy about this.
