### ISSUE TITLE
Copy Paste Not Working

### ISSUE THREAD

**Issue by farkass** [microsoft/vscode#133167]
Issue Type: <b>Bug</b>

Open multiple files
Arrange into two panes
Check current line / highlighted word at left pane
Go to file at right pane
Highlight a word at right pane
Copy by Ctrl+C or Popup menu Copy
Go to a new position at left pane
Paste clipboard content
The clipboard contains the text from the left pane, not the text from the right pane.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (50.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.24.5
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
vscode-multiclip|sle|0.1.5

</details>

**Comment by CalebEverett** [comment]
I've been having trouble with copy-past as well. Intermittently not able to copy output from cells.

**Comment by alexdima** [comment]
Most likely caused by https://github.com/microsoft/vscode/issues/132641
