### ISSUE TITLE
Search shows a portion of the line but not the entire line

### ISSUE THREAD

**Issue by jwrey01** [microsoft/vscode#133184]
Issue Type: <b>Bug</b>

I am searching for a string and the previewed results show truncated lines, cutting off the left-most portion.  

Although even for the same file, there are lines where the left-most portion is truncated yet other lines are shown in their entirety.  It is unpredictable when truncation occurs.

The left-most portion contains key information so it is important that I see the entire line, or if that isn't possible, to control that the truncation occurs on the right (or perhaps optionally left, right or current behavior).

The "Open in editor" shows the entire line, but I prefer to remove irrelevant files from the preview results (based on left-most content) and then use "Open in editor" as that gives me focus on the relevant ones only.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
openmatchingfiles|bca|0.5.0
vscode-language-plx|IBM|1.1.2
vim|vsc|1.21.7
vscode-extension-for-zowe|Zow|1.18.1

</details>

**Comment by roblourens** [comment]
The truncation is a rough estimate to make sure the match text is visible. It depends on how many characters precede the match, and we try to find a nice word break. The search results tree is not really a place to read full lines of code. I recommend the search editor if you want to do that, or opening the full file
