### ISSUE TITLE
Add "search this directory" option when right click on a directory 

### ISSUE THREAD

**Issue by miladr0** [microsoft/vscode#133140]
when I want to search something in a directory and all its subdirectory, I have to do this:

1- right-click on that specific directory and select `copy relative path`
2- paste that path in `files to include` at the search pan

let's make these two steps auto by just add `search this directory` option when right-click on a directory

**Comment by IllusionMH** [comment]
It should be already in context menu for folders
![image](https://user-images.githubusercontent.com/1312662/133396935-0d66875d-75cc-4957-94e6-a58263b0b7fa.png)

**Comment by miladr0** [comment]
@IllusionMH why I didnt it 🙆‍♂️, thank you sir
