### ISSUE TITLE
Vscode becomes unresponsive after a new file is launched into it

### ISSUE THREAD

**Issue by DerekSMorin** [microsoft/vscode#133176]
I'm not sure why.  Very frequently I do a file "open with code" from explorer, or I have some code that writes a file to disk and launches it into code.

The code window comes to the front, but I can't click into the text editor.  Also the new file isn't showing.

If I switch to another window and then back into code the new file will be visible and everything is back to normal.

Just wondering if anyone has any ideas, maybe not easy to duplicate.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/123257, underlying issue is with the occlusion tracker.
