### ISSUE TITLE
Python datetime.strptime syntax highlighter bug

### ISSUE THREAD

**Issue by maallaard** [microsoft/vscode#133127]
Issue Type: <b>Bug</b>

1. import the datetime class from the datetime module
2. convert string to date using datetime.strptime
3. experience syntax highlighter bug with "%d" in "%Y-%m-%d"
It should be orange, used for text surrounded by quotes, but for me it is the same color blue as True and False.

```python
from datetime import datetime

string_date = "2021-9-14"

datetime.strptime(string_date, "%Y-%m-%d")
```

VS Code version: Code 1.60.1 (Universal) (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 48443e02-eb41-4f23-bfc5-e8beff8c3c8b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
vscode-eslint|dba|2.1.25
json-tools|eri|1.0.2
prettier-vscode|esb|8.1.0
vscode-pull-request-github|Git|0.30.0
vsc-python-indent|Kev|1.14.2
csharp|ms-|1.23.15
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
cpptools|ms-|1.6.0
powershell|ms-|2021.9.0
material-icon-theme|PKi|4.10.0
java|red|0.81.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-icons|vsc|11.6.0
material-theme|zhu|3.11.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by alexr00** [comment]
@maallaard thanks for the sample! I'm not able to reproduce this issue, so I suspect it's related to one of the extensions you have installed. You can try out the "Help: Start Extension Bisect" command to narrow down which extension it is.
