### ISSUE TITLE
Add scrolling to integrated terminal

### ISSUE THREAD

**Issue by andreyorst** [Microsoft/vscode#13318]
- VSCode Version: 1.5.3
- OS Version: Arch Linux

Please add scrolling to integrated terminal, because if i have many errors (i am bad at cpp) i need to stretch terminal upwards to see all output, which sometimes goes way far, so i cant see anything. 
Same situation when running console apps.
I cant check if it is zsh making a problem, but if it is, then fix it please too.

Steps to Reproduce:
0. Open integrated terminal;
1. Compile something with huge amount of errors, or print something;
2. Notice that you can't scroll in integrated terminal.
3. Cry.

![screenshot from 2016-10-07 01-58-14](https://cloud.githubusercontent.com/assets/19470159/19173651/8726b830-8c31-11e6-91fa-37fd7dbaff50.png)

**Comment by Tyriar** [comment]
This should be fixed in the [insiders build](https://code.visualstudio.com/insiders), coming to stable in a few days.
