### ISSUE TITLE
Code Helper is consuming most of the CPU

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#13311]
<img width="800" alt="screen shot 2016-10-06 at 2 01 43 pm" src="https://cloud.githubusercontent.com/assets/949380/19170561/d7e84d56-8bcd-11e6-9a80-a11e68aa4eaa.png">

- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: OS X 10.11.6 (15G1004)

**Steps to Reproduce:**
Keep VS Code open for a while for a ember project.

**Doubt**
Probably due to the `tmp` folder. I tried ignoring it, but it did not help.

**Comment by bpasero** [comment]
@sarbbottam can you make sure the tmp folder is also ignored from file watching adding it to the `files.watcherExclude` setting?

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by sarbbottam** [comment]
@bpasero I didn't know about `files.watcherExclude`, just updated.

>To find out more about this issue, we need to get at the process that is causing the high load. 
I guess multiple `find` process was getting triggered.

Let me update the thread with the information.

**Comment by sarbbottam** [comment]
@bpasero looks like the `watcherService` is the cause.

<img width="800" alt="screen shot 2016-10-07 at 10 07 29 am" src="https://cloud.githubusercontent.com/assets/949380/19198855/0e052fe6-8c76-11e6-8b25-57ca53a2040c.png">

<img width="1433" alt="screen shot 2016-10-07 at 10 08 01 am" src="https://cloud.githubusercontent.com/assets/949380/19198856/0e0ae12a-8c76-11e6-8e82-b3e2715cd879.png">

Please find the user setting like so:

```js
  // Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "**/xnode_modules": true,
    "**/.git": true,
    "**/.DS_Store": true,
    "**/tmp": true
  },

  // Configure glob patterns for excluding files and folders in searches. Inherits all glob patterns from the files.exclude setting.
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.git": true,
    "**/.DS_Store": true,
    "**/tmp": true
  },

  // Configure glob patterns of file paths to exclude from file watching. Changing this setting requires a restart. When you experience Code consuming lots of cpu time on startup, you can exclude large folders to reduce the initial load.
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true,
    "**/tmp": true
  }
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3998
