### ISSUE TITLE
Double save then discard closes the new file and loose all changes

### ISSUE THREAD

**Issue by softlion** [microsoft/vscode#133142]
I'm upset !!!! I lost 30mn of writings !!!

Reproduction:
- Create a new file in VSCode (File, new)
- write some random text
- tap "CTRL-S" 2 times quickly
- on the windows save dialog, clic cancel
- In VS code, this popup is now displaying :

![image](https://user-images.githubusercontent.com/190756/133399261-b7e43086-cd4e-4817-b4d7-52f2128cc189.png)

Clic "discard".
It closes the tab, and its content is definitely lost...
Instead it should only discard this popup !!!!

![image](https://user-images.githubusercontent.com/190756/133399669-c31816ab-b185-4c61-b832-fe7eda5c915a.png)

```
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by bpasero** [comment]
@softlion if you still have VSCode open, when you open the file again and hit "Undo", the contents should come back.

**Comment by softlion** [comment]
> @softlion if you still have VSCode open, when you open the file again and hit "Undo", the contents should come back.

The file has never been saved. It was a new file.

**Comment by bpasero** [comment]
Oh I see. Yeah we can maybe improve the wording and/or tweak the notification actions.

**Comment by bpasero** [comment]
I pushed a fix to treat this error situation as if you had pressed `Cancel` on the dialog. Sorry for your data loss here and thanks for still reporting this issue 👍
