### ISSUE TITLE
My extensions didn't work

### ISSUE THREAD

**Issue by nazhwaameera** [microsoft/vscode#133134]
We have written the needed data into your clipboard because it was too large to send. Please pas
Issue Type: <b>Performance Issue</b>

Recently, i encountered this issue. I've installed every extensions i need for auto completion and such but it seems nothing work.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.92GB (3.72GB free)|
|Process Argv|--crash-reporter-id 0c56320d-8708-471b-bd58-fd27d90514ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    88	  5988	code main
    0	   172	  1148	   window (Extension: HTML Snippets - HTML - Visual Studio Code)
    0	    33	   756	     searchService
    0	   302	  3616	     extensionHost
    0	    33	  2500	       electron_node languageserver.js 
    0	    33	  2596	       "C:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=3616
    0	    55	 10672	       "C:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3616
    0	    28	 12040	       electron_node serverMain.js 
    0	    32	 15648	       "C:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Damar Dayu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3616
    0	   165	 16508	       C:\xampp\php\php.exe "c:\Users\Damar Dayu\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php" --tcp=127.0.0.1:63717 --memory-limit=4095M
    0	    11	 16688	         console-window-host (Windows internal process)
    0	    31	 18812	       electron_node server.js 
    0	    13	  4240	     watcherService 
    0	    11	 13684	       console-window-host (Windows internal process)
    0	    49	  5712	   window (undefined)
    2	    52	  6044	   window (Issue Reporter)
    0	    13	 10048	   crashpad-handler
    0	   137	 11488	   gpu-process
    0	    24	 16472	   utility
    0	    69	 17992	   shared-process
    0	    33	  6852	     ptyHost
    0	    51	 18036	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: HTML Snippets - HTML - Visual Studio Code)
|    Folder (HTML): 17 files
|      File types: html(7) jpg(2) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
laravel-extra-intellisense|ami|0.6.1
vscode-browser-preview|auc|0.7.1
vscode-database|baj|2.2.3
vscode-django|bat|1.6.0
vscode-intelephense-client|bme|1.7.1
gltf-vscode|ces|2.3.12
path-intellisense|chr|2.4.0
glsl-canvas|cir|0.2.13
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
python-extension-pack|don|1.6.0
vscode-html-css|ecm|1.10.2
vscode-optimize-images|fab|1.1.1
php-debug|fel|1.17.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vsls-whiteboard|los|0.0.12
MagicPython|mag|1.1.0
vscode-mesh-viewer|mic|0.0.10
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
sqltools|mtx|0.23.0
vscode-plugin-webgl-syntax|nie|0.0.2
vetur|oct|0.34.1
laravel-blade|one|1.25.0
laravel5-snippets|one|1.13.0
gcc-md|pha|0.0.1
java|red|0.81.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
html5-boilerplate|sid|1.1.1
shader|sle|1.1.5
vscode-3dviewer|sle|0.2.2
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30358039
vssid140cf:30363604
vssur157:30365996

```

</details>

te.

**Comment by aeschli** [comment]
Please add more detailed steps with samples and screenshots and describe what you see and what you expect.
