### ISSUE TITLE
Multiroot project, cannot attach breakpoint using jest after the latest update TS

### ISSUE THREAD

**Issue by gjorgjivladimirov-allocate** [microsoft/vscode#133138]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: Win 10

On older versions >=1.58 everything was working fine and as a workaround I'm going to downgrade vs Code, but I would like to get this issues solved so.
Steps to Reproduce:

1. I have 2 folders(projects)
├───ProjectA
│          Component A.ts
 |           Unit_tests.spec.ts
├───ProjectB
│         ComponentB.ts
 |         UnitTestsForB.spec.ts

2. Project B is referenced(linked) in ProjectA with npm link..
3. I have unit tests for both projects. some unit tests in ProjcetA are using component B from ProjectB.
4. Place breakpoints in Unit_test.spec.ts ComponentA and ComponentB.
5. Debug some test in ProjectA and when debugger is attached breakpoints from ComponentB disappears. The test finished successfully.
   - insert debugger; in componentB and the debugger will stop but in some hidden generated file(js file with sourmapping) not the original .ts file where I expecting.

Note: If I debug test from ProjectB then the debugger is working as expected. Only when the debugger needs to jump from ProjectA to some component in ProjectB

Debug Configuration used in both projects:
```
{
"type": "node",
"request": "launch",
"name": "Debug Jest Current File Work",
"port": 9229,
"runtimeArgs": [
	"--inspect-brk",
	"${workspaceFolder}/node_modules/jest/bin/jest",
	"--runInBand",
	"${fileBasename}"
],
"console": "integratedTerminal",
"internalConsoleOptions": "neverOpen",
},
{
"type": "node",
"request": "attach",
"name": "Attach Work",
"port": 9229,
}
```

Hidden generated file where the debugger stops:
![image](https://user-images.githubusercontent.com/82090787/133384621-9fbab4e7-9993-40b0-a5b9-a22fabdbda69.png)

TsConfig:
```
"compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "typeRoots": [
            "./node_modules/@types",
            "@types"
        ],
        "types": ["node", "jest"],
        "watch": false,
        "declaration" : true,
        "forceConsistentCasingInFileNames": true,
    },....
```

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-js-debug/issues/1100, see the comment there for resolution

**Comment by gjorgjivladimirov-allocate** [comment]
@connor4312 Still it's not clear how to resolve it ???
I installed Nightly as debugger but same thing when the debugger is attached automatically the original .ts file is converted into some hidden generated file and in the Breakpoints section is it displayed the full path.
![image](https://user-images.githubusercontent.com/82090787/133618312-07a5d5fb-8070-4edc-834b-9a31038f6305.png)

**Comment by connor4312** [comment]
You can set `resolveSourceMapLocations: null` to not filter the included paths is projectB is in a different workspace folder

**Comment by gjorgjivladimirov-allocate** [comment]
finally that solved it thx @connor4312

**Comment by connor4312** [comment]
You may want to set `resolveSourceMapLocations` to a more specific pattern, it's possible you have a lot of sourcemaps in your node modules and resolving them everywhere is slow.E.g. to 

```
"resolveSourceMapLocations": [
  "${workspaceFolder}/**",
  "${workspaceFolder}/../my-other-folder/**",
  "!**/node_modules/**"
],
```
