### ISSUE TITLE
How to exclude the non-suffix files by "files.exclude" setting?

### ISSUE THREAD

**Issue by q944093** [microsoft/vscode#133163]
Some unix files without suffix will generate when I compile codes.
![image](https://user-images.githubusercontent.com/58098692/133446833-4091e341-7e77-4841-a8a4-2aa685e79e77.png)

I want to hide them in the file explorer but can't find a way to express it in "files.exclude" setting. How can I figure it out?
![image](https://user-images.githubusercontent.com/58098692/133446998-42537bd5-bd8d-4a64-a224-37d555363acb.png)

**Comment by JacksonKearl** [comment]
You can exclude it specifically with `"1test": true` but there is no way I know of to exclude all files without extensions.

**Comment by ArturoDent** [comment]
Ugly, but this may help for generated files: https://stackoverflow.com/a/61201674/836330
