### ISSUE TITLE
Unable to launch terminal

### ISSUE THREAD

**Issue by jawadhoot** [microsoft/vscode#133180]
Issue Type: <b>Bug</b>

Click terminal menu, click new terminal

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.40GB (1.68GB free)|
|Process Argv|--crash-reporter-id 3c90e116-f972-4a2b-aa5b-c1adc7da0f4e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your terminal configuration? Do you see any errors?

**Comment by Yasirunet** [comment]
Also getting the same issue after I updated it to 1.60. The issue is not resolved by the 1.60.1 update either. Once I open the integrated terminal, it returns a blank. Before the PowerShell opened every time, instead of bash which is my default selected terminal.
There may be an association with #132150

**Comment by jawadhoot** [comment]
@IllusionMH This is a clean install, I have deleted ".vscode" folder in my home dir and "Code" in appdata roaming.
I don't get any error.

**Comment by iNesFig** [comment]
Also getting the same issue after the 1.60.1 update! The 1.60.0 update forced PowerShell but now the Terminal doesn't even get launched!

**Comment by jawadhoot** [comment]
Its working after windows update, not sure what fixed it!
