### ISSUE TITLE
Text highlight includes unselected whitespace characters

### ISSUE THREAD

**Issue by philosofool** [microsoft/vscode#133174]
## Environment data

Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-7620-generic snap

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   OS (Windows | Mac | Linux distro) and version: Linux x64 5.11.0-7620-generic snap
-   Python and/or Anaconda version: 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Docker container
-   Jupyter server running: Remote

## Expected behaviour

When highlighting text within a cell on more than one line, the text in the cell should be highlighted starting where the cursor was on mouse-press or shift+arrrow and ending where it was released.

## Actual behaviour

Repeating the same mouse action, the highlighting extends an extra character width to the left and right if that character is whitespace. (Seems to happen with non-whitespace characters is one of the boundary characters is whitespace. Sometimes it's only one character (left or right, not both.) Not totally consistent or obvious what exactly is happening.)

## Steps to reproduce:

Type several lines  of text into a cell at an indent level greater than zero spaces. Click-and-hold next to a whitespace character on a middle line of text then drag the mouse up or down more than one line. The highlighting jumps to include an extra space of text outside the region bounded by the mouse cursor and position where it was initially pressed. (Again, it s a little inconsistent, occasionally it doesn't happen or doesn't happen exactly as described, but most of the time it does.)

The problem can also be produced by holding shift and moving the cursor with the arrow keys.

**Comment by rebornix** [comment]
@philosofool can you check if you can reproduce this with extensions disabled? (running vscode through `code --disable-extensions`)?

**Comment by philosofool** [comment]
> @philosofool can you check if you can reproduce this with extensions disabled? (running vscode through `code --disable-extensions`)?

Yes, this error persist when launching VSCode with `code --disable-extensions`.

**Comment by rebornix** [comment]
@philosofool do you mind share a screenshot of what you see?

**Comment by philosofool** [comment]
> @philosofool do you mind share a screenshot of what you see?
![Screenshot from 2021-09-28 12-38-25](https://user-images.githubusercontent.com/66087178/135154622-605db9ef-7914-4c54-8fea-da015eafede4.png)
