### ISSUE TITLE
Make searching # symbols better

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#13317]
- VSCode Version: 1.6 Insider

Currently global symbols search isn't really a good experience, as user can't find anything without typing and then waiting for 3 seconds.

One improvement could be letting Cmd+T cache "recently jumped symbols" like Cmd+P does for "recently opened documents", and show it at Cmd+T even if no input is received yet.
Currently it's blank with no input:

![image](https://cloud.githubusercontent.com/assets/4033249/19173046/0abaac2c-8bda-11e6-8a29-95551112e8e5.png)

Another idea is to fastly compute all symbols in all open files (or files that have been open since launching) and provide them as `#` symbols. Which would be much more useful than the current Cmd+T.

**Comment by bpasero** [comment]
Any caching should go into the language service, not into Code imho. This is something typescript should look into (fast global symbol search).

**Comment by egamma** [comment]
CC @waderyan

**Comment by waderyan** [comment]
Ping @bowdenk7 is this on your radar? I did a quick scan of the TS repo for similar issues and couldn't find one. I'll plan on migrating this issue to TS unless I hear from you that a duplicate already exists.

**Comment by bowdenk7** [comment]
I'm not aware of anything similar - go ahead and migrate it.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11503
