### ISSUE TITLE
Review usages of `setImmediate`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133173]
We have a few places that call `setImmediate` which has different runtime behaviour when running in desktop (where we still have node.js) and web (where it is [shimmed](https://github.com/microsoft/vscode/blob/e045e3b1b25de81232b7db32747f31bf90d02d13/src/vs/base/common/platform.ts#L193-L193)).

Given there is [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask) available in all browsers and node.js, I suggest we review whether the usage is actually still required and/or change to `queueMicrotask` if still needed and if applicable.

**Usages:**

* [x] `webviewViewPane` @mjbvz 

https://github.com/microsoft/vscode/blob/0a4bfb31c9027e231e89977d03846f53d2bac48c/src/vs/workbench/contrib/webviewView/browser/webviewViewPane.ts#L113-L115

* [x] `testingDecorations` @connor4312 

https://github.com/microsoft/vscode/blob/aac4d020827481cd1ac7e317ac7d3d49a318103e/src/vs/workbench/contrib/testing/browser/testingDecorations.ts#L360-L363

* [x] `fileBasedRecommendations` @sandy081 

https://github.com/microsoft/vscode/blob/fda50dae3c5a2eeea922e1f0b1b594bc23ed6298/src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts#L184-L184

* [x] `textModelTokens` @alexdima 

https://github.com/microsoft/vscode/blob/eb5e38bb0bc5e96a472c2404dfde5d41346f868b/src/vs/editor/common/model/textModelTokens.ts#L259-L265

* [x] `ipc.net.ts` @alexdima 

https://github.com/microsoft/vscode/blob/b88626977819c490fa22e5b88eaec0f251aa97d6/src/vs/base/parts/ipc/common/ipc.net.ts#L373-L375

* [x] `ipc.net.ts` @alexdima 

https://github.com/microsoft/vscode/blob/b88626977819c490fa22e5b88eaec0f251aa97d6/src/vs/base/parts/ipc/common/ipc.net.ts#L484-L487

**Comment by sandy081** [comment]
@bpasero What is the option if queueMicroTask does not fit as alternative?

**Comment by bpasero** [comment]
@sandy081 I think we have 2 options:
* `setTimeout(0)` if you want to schedule your work onto the next event loop
* `queueMicrotask` if you want to schedule your work at the end of the current event loop before the next loop starts

**Comment by sandy081** [comment]
I want to retain the same behavior as before ie., not to block any browser events - so went with `setTimeout`

**Comment by bpasero** [comment]
@sandy081 actually I forgot one alternative: `scheduleAtNextAnimationFrame` allows to schedule a task to run when the next frame get's rendered and is useful to unblock the current rendering if that is desired.

We also have `runWhenIdle` to schedule something when the browser reports idle.

**Comment by sandy081** [comment]
Good to know, thanks. Will stick to setTimeout for my case.

**Comment by alexdima** [comment]
@bpasero I could not find any good alternative for the usage at https://github.com/microsoft/vscode/blob/eb5e38bb0bc5e96a472c2404dfde5d41346f868b/src/vs/editor/common/model/textModelTokens.ts#L259-L265

* the pattern used there is that there is a lot of work to do (e.g. tokenize 100k lines) and after 10 or 20ms the loop yields and schedules itself again.
* using `queueMicrotask` is not an option because the entire idea of yielding is to allow the browser/nodejs event loop to execute
* using `setTimeout(0)` is not an option because most browsers round that up to `setTimeout(5)` or `setTimeout(15)` artificially, i.e. last time I looked at it introduces an artificial gap of a few ms.
* `scheduleAtNextAnimationFrame` is not helpful
* I could look at using `runWhenIdle` but [on Safari](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#browser_compatibility) it looks like that adds a [15ms artificial delay](https://github.com/microsoft/vscode/blob/423b51adfcfe3112da73667a6391177ef5614c3d/src/vs/base/common/async.ts#L983) cc @jrieken . I think perhaps the `runWhenIdle` shim should use `setImmediate` or its shim when `requestIdleCallback` is not available.

**Comment by bpasero** [comment]
@alexdima thanks for looking into this usage. the reason I bring this up is that we will eventually enable `sandbox: true` and then we will be using a shim for `setImmediate` as implemented by us via the `postMessage` trick/hack:

https://github.com/microsoft/vscode/blob/e045e3b1b25de81232b7db32747f31bf90d02d13/src/vs/base/common/platform.ts#L203-L203

Maybe if we want to use that here, we introduce an explicit method that makes clear what the intent is? Like `queueWorkerTask` or however we want to name it?

**Comment by alexdima** [comment]
I think the browser feature I want to use is `requestIdleCallback`, but that is not available in Safari and the current shim for that is using `setTimeout(15)`. I don't know immediately if `Safari` supports `setImmediate` or not. Maybe the `requestIdleCallback` can be shimmed in Safari using `setImmediate` or using self-posted message via `postMessage/onmessage`.

**Comment by jrieken** [comment]
> I could look at using runWhenIdle but on Safari it looks like that adds a 15ms artificial delay cc @jrieken .

That's not an artifical delay but the `timeRemaining` - see https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline/timeRemaining. The idea is that users check this to see how much time they have left - in this case you have 15ms and time is already up. Nevertheless, it does use `setTimeout(fun, 0)` which isn't entirely clear how browsers handle it: https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified

**Comment by jrieken** [comment]
fyi - pushed a better polyfill for `timeRemaining`

**Comment by roblourens** [comment]
This broke the EH for me, seems like the performance API doesn't

**Comment by jrieken** [comment]
fyi - `requestIdleCallback` ships as experimental feature in Safari 15. So, might become stable soon'ish

<img width="672" alt="Screen Shot 2021-09-28 at 09 57 20" src="https://user-images.githubusercontent.com/1794099/135047122-028c0793-7d51-45bc-a984-eaff206bc8ab.png">

**Comment by alexdima** [comment]
Given its MDN description, I initially thought that `requestIdleCallback` would be a good replacement in the case of background tokenization, but after testing it, it really isn't. With the current yielding using `setImmediate`, tokenization reaches the end of `checker.ts` (44k lines) in 14s. When using `requestIdleCallback`, it took about 3 minutes. It looks like calling `requestIdleCallback` from inside `requestIdleCallback` schedules the new work after 15ms (maybe at the next frame?).

**Comment by jrieken** [comment]
> It looks like calling requestIdleCallback from inside requestIdleCallback schedules the new work after 15ms (maybe at the next frame?).

Yeah, very likely as I believe the idle time is always the remainder of a frame (I believe I have never seen `timeRemaining` showing higher values than a couple of millis)

**Comment by bpasero** [comment]
Not sure if helpful here but Chrome 94 adds job scheduling API: https://www.chromestatus.com/feature/6031161734201344. We will only get it with the Electron 16 update.

**Comment by alexdima** [comment]
@bpasero All done. I'm leaving the issue open in case you want to delete `platform.setImmediate`.

**Comment by bpasero** [comment]
Thanks a lot!

**Comment by connor4312** [comment]
In https://github.com/microsoft/vscode/commit/c635a395496a0699e6c6748d37b974fb4fba18cc I make the Delayer microtask-capable since I wanted to use it (over a heavier weight timeout). Do we want to look at applying that to more of our async code?

**Comment by bpasero** [comment]
This issue is for avoiding node.js primitives because when sandbox is enabled, there is no `setImmediate` or `nextTick`, `setTimeout` is still fine to use.
