### ISSUE TITLE
Ability to hide activity/status bars in just one window

### ISSUE THREAD

**Issue by TranquilMarmot** [microsoft/vscode#133111]
Currently, if you hide the activtiy bar (View -> Appearance -> Show Activity Bar) it will be hidden on _all_ windows of Visual Studio Code that are open. The same goes for the status bar.

It would be nice to be able to hide these on just one window, but keep them visible on other windows.

My main use case here is that I want to use vscode as my main terminal emulator. I have a vscode instance open just with terminals, so I don't have a workspace open at all and don't need the activity bar or any of the other bars. I only want to see the editor area.

**Comment by IllusionMH** [comment]
> My main use case here is that I want to use vscode as my main terminal emulator.

Interesting decision when there is e.g https://hyper.is/ (and I think I've seen another one) that use same xterm.js under the hood and it's main goal is to be terminal emulator.

Anyway - best option for you is to create workspace and set `"workbench.activityBar.visible": false` and other setting as you see fee on **Workspace** level (either in settings editor or workspace config file)

**Comment by misolori** [comment]
@IllusionMH is correct in that as a current workaround you can open an empty folder add [workspace settings](https://code.visualstudio.com/docs/getstarted/settings) to achieve this:

```json
{
    "workbench.activityBar.visible": false,
    "workbench.statusBar.visible": false,
    "workbench.editor.showTabs": false
}
```
<img width="1576" alt="CleanShot 2021-09-14 at 10 47 52@2x" src="https://user-images.githubusercontent.com/35271042/133308213-8bc12475-0f72-481f-b426-378a4ecd23ea.png">

**Comment by TranquilMarmot** [comment]
@IllusionMH Hyper is okay, but I wanted to see how well vscode could be a terminal emulator. It's nice to be able to just run `code some-file.sh` and have it open in the same window that you're currently in. Plus, vscode has some really nice tiling features.

@misolori Awesome, this works perfectly! Thank you. It's still a little weird to me that hiding/showing these affects global settings and not workspace settings but 🤷
