### ISSUE TITLE
Provide a UI editor for tasks.json and launch.json similar to the settings.json UI editor

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode#133122]
Similar to how VS Code provides a UI editor for editing settings.json. A UI editor for editing launch.json and tasks.json files would be awesome as well.

I believe that Tasks and Debug configurations are a tad bit inaccessible to many users as the features are complex and some users are not as comfortable configuring the json files.

A UI editor could provide a lot more inline documentation to help users create proper tasks and launch configurations.
I think this might help boost the % of users using the great debugging features in VS Code.

**Comment by roblourens** [comment]
Thanks for the suggestion. We have worked to make debugging and tasks usable even without launch configs, that has been the focus of our efforts to make it more accessible. I don't think that a GUI like the settings editor is a good match for these files. They often have arbitrarily shaped nested objects which we can't display in the settings editor. Building a generic JSON GUI editor is not a winning goal for ease of use.
