### ISSUE TITLE
launch.json deleted

### ISSUE THREAD

**Issue by Charlie7701** [microsoft/vscode#133179]
Issue Type: <b>Feature Request</b>

Configuration 'Run Current File' is missing in "launch.json."

 Deleted on accident how to I fix this?

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by roblourens** [comment]
You can get it from wherever you got it from originally :) if it's in source control/git maybe you can restore it from there
