### ISSUE TITLE
Markdown extensions are not initialised when connecting to a remote host

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#133204]
Does this issue occur when all extensions are disabled?: No 

Of course not. It's an extension initialisation problem.

The problem only happens when the remoting extensions are in use. There is a failure to initialise markdown plugins _only when remoting_.

Microsoft is the publisher for both the remoting extensions and the extension responsible for configuring the markdown rendering pipeline. 

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

## TL;DR

* Markdown plugins get themselves inserted into the rendering pipeline by returning an installation callback as a method on object returned by the activate method.
* When connecting to a remote host, activate fires but the callback method is **not** invoked.

### Interactively

1. Preview a Markdown document that uses any installed markdown plugin (eg Math+Markdown) in the local filesystem.
2. Preview the same document from a remote filesystem. The special rendering provided by the plugin will fail to occur.

#### Sample failure for remote host
![image](https://user-images.githubusercontent.com/5498936/133528747-d13a9aca-4478-4204-ae41-c29bc94ba1a7.png)

#### Sample success for local host

![image](https://user-images.githubusercontent.com/5498936/133528808-70bf596f-7732-4e26-bb67-16ab2d97b182.png)

### In a debugger 

* get the source for some markdown plugin extension that you know works
* breakpoint the code inside the callback method of the object returned by the extension's activate method
* repeat the above exercise

You'll hit the breakpoint when you trigger activate for local and you won't for remote markdown preview. 

To work up a sample for testing, write a minimal extension with an activate method that returns an object like so.

```ts
  const markdownPluginInstaller = {
    extendMarkdownIt(mdparam: any) {
      // chain your markdown plugin and return the new wrapper object
      wrapper = mdparam; // there is no spoon
      return wrapper;
    }
  };
  return markdownPluginInstaller;
```

Then bind it to all activation events and mark the extension in `package.json`.

```json
  "activationEvents": [
    "*"
  ],
  "contributes": {
    "markdown.markdownItPlugins": true,
```

**Comment by mjbvz** [comment]
Is your markdown extension configured to be a [workspace extension](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds)? Markdown it extension need to be running in the same host (the remote one in this case) as the core `markdown language features` extension

**Comment by PeterWone** [comment]
If you are referring to the `extensionKind` setting

```json
  "extensionKind": [
    "ui"
  ],

I've tried supplying `ui`, `workspace` and both.

When it's set to `ui` or both, things work as described above. When it's set to `workspace` the activate method is not called at all.

**Comment by PeterWone** [comment]
Well, that's embarrassing.

![image](https://user-images.githubusercontent.com/5498936/133695788-18d9e304-5245-4db8-943d-076f8a93feb4.png)

I'm still not hitting breakpoints, but the correct rendering is proof positive that the activate method is being called and my extension is hooking the pipeline. So I guess I'm not correctly set up for debugging a remote extension.

During that successful test I had `extensionKind` set to `workspace` only. 

I guess this means that a _lot_ of markdown extensions need their `extensionKind` changed.
