### ISSUE TITLE
Easier way to change a value in the watch window

### ISSUE THREAD

**Issue by Ben136KBC** [microsoft/vscode#133268]
While debugging, the VARIABLES window may show a lot of variables. So you add variables of interest in the WATCH window. And you can right click on a watched variable and use "Set Value". If you double click anywhere on a line in the WATCH window, it lets you edit the expression.

It would be nice if you could double click somewhere on the watched variable line to edit its value. Maybe if you click to the right of the colon, it means change the value, and if you click to the left of the colon, it means change the expression?

Most other debuggers let you do this. VS 2019 shows the watched variables and values in different columns, making it easier for you to edit a value. I think VSCode is more space efficient by not using columns. But it would be nice if you could somehow double click on the watched variable line to change the value and not just the expression.

Nit picky I know! But someone who comes from the VS world initially wonders "Hey how do I change the watch variable value?" and double click on it like you would in VS but it wont let you change the value. And then later you discover the right click menu. And yes that works, but its a lot more clicks and just a quick easy double click on the value.

Thanks.

**Comment by roblourens** [comment]
Not sure about this - like you point out, we use a list. Typically a list row only does one thing when you double click on it, regardless of which part you double click on. So I'm not sure about trying to support changing the two different parts with the same action
