### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by hkelsenn** [microsoft/vscode#133283]
when i compile my program show this

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

**Comment by aeschli** [comment]
This is not a VS Code issue but related to your .net installation. 
I suggest looking for answers on stackoverflow:
https://stackoverflow.com/questions/31875825/how-to-run-roslyn-instead-csc-exe-from-command-line
