### ISSUE TITLE
window not responding this message is again and again while open vs code

### ISSUE THREAD

**Issue by pullumoni** [microsoft/vscode#133245]
Issue Type: <b>Performance Issue</b>

not good windows is not responding

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (2.14GB free)|
|Process Argv|-n --crash-reporter-id a3c8e7a6-cbc8-47d1-b997-b6254ead407c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	  8856	code main
    0	   110	 13148	   shared-process
    0	    71	 13928	     ptyHost
    0	   125	 13564	   window (Welcome - Visual Studio Code)
    0	   390	 16444	     extensionHost
    0	    72	  9348	       "C:\Users\Anamika\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Anamika\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16444
    0	    70	 15340	       electron_node serverMain.js 
    0	    72	 18340	       electron_node aslServer.js 
    0	    72	 21840	       electron_node ssmServer.js 
    0	    65	 15500	   crashpad-handler
    0	    70	 18052	   utility
    2	    81	 18840	   window (Issue Reporter)
    0	   175	 18920	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aws-toolkit-vscode|ama|1.29.0
icons-carbon|ant|0.2.4
op-1|ate|0.1.1
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-toggle-quotes|Bri|0.3.5
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
jshint|dba|0.11.0
vscode-eslint|dba|2.1.25
go-coverage-viewer|def|1.0.3
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
el-vsc-product-icon-theme|ElA|0.1.8
vscode-great-icons|emm|2.1.79
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|8.1.0
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
obsolete-ooc|han|0.2.4
beautify|Hoo|1.5.0
monkey-patch|ioc|0.1.15
sf-symbols|j-f|2.1.0
vscode-styled-components|jpo|1.6.6
react-native-snippet|jun|0.5.6
theme-dark-plus-contrast|k3a|0.1.101
google-fonts|lio|0.0.1
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
python|ms-|2021.8.1159798656
jupyter|ms-|2021.8.1054968649
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.6.0
sublime-keybindings|ms-|4.0.10
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.4836
debugger-for-chrome|msj|4.12.12
script|Nur|0.2.1
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
java|red|0.81.0
LiveServer|rit|5.6.1
bootstrap-product-icons|rub|1.0.2
workspacetheme|sag|1.0.1
MyTestExtension|Sai|0.0.3
python|tht|0.2.3
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.6
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.30.1
vscode-maven|vsc|0.33.0
vscode-import-cost|wix|2.15.0
es7-react-js-snippets|woo|2.3.8
omi-snippets|Wsc|2.2.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment]
/needMoreInfo

Is this problem reproducible in latest stable VS Code - 1.60.1?
You can get latest version here https://code.visualstudio.com/Download

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is this problem reproducible in latest stable VS Code - 1.60.1?
You can get latest version here https://code.visualstudio.com/Download
