### ISSUE TITLE
"Open in Integrated Terminal" does not use Default Profile

### ISSUE THREAD

**Issue by fcarelse** [microsoft/vscode#133274]
Issue Type: <b>Bug</b>

Updated to latest version. Still not fixed. Brings up CMD when Anything else is selected as default terminal.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.08GB free)|
|Process Argv|--crash-reporter-id cffc0c75-9b30-4593-ba91-3340b538e6c7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.1
ng-template|Ang|12.2.0
svelte-intellisense|ard|0.7.1
lit-html|bie|1.11.1
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
vscode-firefox-debug|fir|2.9.4
next-js|fox|0.0.2
vscode-yarn|gam|2.0.0
vue|jcb|0.1.5
Angular2|joh|12.0.0
compare-folders|mos|0.22.2
vscode-docker|ms-|1.16.1
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
vscode-react-native|msj|1.6.1
vetur|oct|0.34.1
java|red|0.82.0
vscode-yaml|red|0.22.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
lit-plugin|run|1.2.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.2.1
svelte-vscode|sve|105.4.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-maven|vsc|0.33.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224:30367819
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by meganrogge** [comment]
can you run extension bisect to see if any of those could be interfering with your settings or environment?

**Comment by fcarelse** [comment]
Hi

Tried with Bisect. Disabled 41 extensions. Same issue for right clicking on
a folder and selecting "Open in Integrated Terminal"
Double checked and settings are still pointing to Cygwin.
I even tried the settings below to try to not give VSCode the option of
defaulting to "Command Prompt" from settings.
So it probably is actually referencing the OS for it's settings in this
case.
I had already tried disabling all extensions before.
Are you not able to re-create the issue on your side?
If not then don't worry about it. Probably not worth fixing.
I just have to launch the other terminal from inside the Command Prompt
each time.

Thanks,
 Frank

  "terminal.integrated.defaultProfile.windows": "Cygwin",
  "terminal.integrated.profiles.windows": {

    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt Old": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Command Prompt": {
      "source": "Git Bash"
    },
    "Git Bash": {
      "source": "Git Bash"
    },
    "Cygwin": {
      "path": "C:\\cygwin64\\bin\\bash.exe",
      "args": [
        "--login"
      ]
    }
  },
  "terminal.integrated.automationShell.windows": "Cygwin",
  "terminal.external.windowsExec": "C:\\cygwin64\\bin\\bash.exe",
  "terminal.integrated.automationShell.linux": ""

**Comment by meganrogge** [comment]
I can't reproduce this.  In order to explicitly remove command prompt as an option, you would update your setting like this:

```
"Command Prompt": null
```

**Comment by fcarelse** [comment]
After trying that it created an entry for "c:\\windows}\\System32\\cmd.exe"
And it automatically set "terminal.integrated.defaultProfile.windows" to that too.

So I removed every option except Cygwin and set "terminal.integrated.defaultProfile.windows" to Cygwin and restarted.
After that it opened cygwin as default from the popup menu.
Restarted twice and it kept working.

After putting back all the other settings and restarting it is now allowing Cygwin to be the popup menu default integrated terminal.
So it worked out. But not sure if that is a fix in the normal sense of the word.
But the problem is solved for me.
