### ISSUE TITLE
Other extension has renamed file when onDidSaveTextDocument is executed

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode#133221]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
- OS Version: Windows 10.

We're using VSCode to develop extensions in the Business Central ERP System. This is done in AL code.

We've developed a VSCode Extension that makes it easier for our AL developers to make and publish BC Extensions.

One of those features dels with manipulating AL files on save so our extension is listening to the vscode.workspace.onDidSaveTextDocument event and doing what need to be done to the file.

Our AL developers are also using another AL Extension namely the 'waldo's CRS AL Language'. This extension is also listening to the vscode.workspace.onDidSaveTextDocument event.

With the CRS Extension you can handle file naming rules which means that when you save a new temp.al file CRS will rename it to say MyPage.Page.al.

Now for  the problems.
Case 1: If CRS Extension gets activated first then when our extension eventhandler is activated the temp.al file no longer exists and we have no way of knowing what the new file is called. 

Case 2: Our extension is activated first and we start to manipulate the temp.al file. Then, while we're editing the file, the CRS Extension is making a copy of the file but fails deleting the temp.al file because our code is manipulating the file. This means there are now 2 files in the editor with the same Object Name and ID and the AL code compiler dont like that very much.

Steps to reproduce:
It's pretty hard to setup an environment to reproduce this issue.

You may need to make 2 extensions. One that renames a file on save and another that manipulates said file on save.

I have no idea what the solution is.

I've tried to make our code lock the call but we are still experiencing CRS extension renaming the file when doing that.

**Comment by jrieken** [comment]
> our extension is listening to the vscode.workspace.onDidSaveTextDocument event and doing what need to be done to the file

Why don't you use [`onWillSaveTextDocument`](https://github.com/microsoft/vscode/blob/cbf8b411b9ccce33926bfa2d20f86e0970a85235/src/vs/vscode.d.ts#L10926-L10926)? Modifying a file _after_ it has been edited is very error prone and can yield in repeated save-change-save cycles

**Comment by HenrikHolmIT** [comment]
Yeah we tried that but some of the processing we are doing can sometimes end up running longer that is allowed and we experienced being shut down for taking too long. To resolve this we had to use onDidSaveTextDocument.
We are downloading language resources and scanning the file for new text fields that needs to be uploaded also. Its not so long that users notice, but VSCode blocked our execution in some cases with large files with lots of text resources.
Also editing the file through the Editor object (because file is not saved yet) is a very cumbersome developer task. Editing after save directly on the file on disc is a lot easier and VSCode catches the edits right away so we opted to use onDidSaveTextDocument and edit the file directly.

**Comment by HenrikHolmIT** [comment]
Could a solution be if you could report back to the initiator of the event that the file was actually renamed?
Obviously an extension that, like CRS, are in fact rename files would have to be updated to actually supply back the new name and I understand that there is no guarantee that an extension renaming files would actually report a rename. 

Then extension activated after a rename action could be supplied the new correct name of the file?

event.fileWasRenamed(string newFilename)

**Comment by jrieken** [comment]
> Also editing the file through the Editor object (because file is not saved yet) is a very cumbersome developer task

I believe you didn't see that [`waitUntil`](https://github.com/microsoft/vscode/blob/cbf8b411b9ccce33926bfa2d20f86e0970a85235/src/vs/vscode.d.ts#L10361-L10381) accept text edits that are being made. Wrt to the threshold: it exists and is around 1.5 seconds - we don't want further delaying of the save operation and believe a save-handler isn't the right approach than. 

> Could a solution be if you could report back to the initiator of the event that the file was actually renamed?

The didSave-event is a synchronous event - we save, we are done, we fire the event and that's it. There is no async-part in that event-delivery and therefore we cannot feed some information back. You can try [onWillRenameFiles](https://github.com/microsoft/vscode/blob/cbf8b411b9ccce33926bfa2d20f86e0970a85235/src/vs/vscode.d.ts#L11048-L11048) but that only fires when the CRS uses the `vscode.workspace.fs`.

I am unsure if you author/own both extensions in that case you can couple them tighter. If the  the aync-modify-after-save vs async-rename-after-save problem is home made, then could be avoided by having just one listener. Tho, you are always exposed to these kind of problems, e.g when another extension does something after did-save.

**Comment by HenrikHolmIT** [comment]
So each extension is receiving they own isolated copy of the event object passed into onDidSaveTextDocument?

I am in contact with the publisher of the CRS extension also (Waldo). His extension is publicly available but our extension is private. None of its functionality would work outside of our business domain with local servers and paths to SMB shares and stuff like that.

He suggested we could turn off the rename action on file save (which is active because of a setting) and activate the Rename command from our extension when we are done with our edit on the file.

**Comment by jrieken** [comment]
> So each extension is receiving they own isolated instance of the event object passed into onDidSaveTextDocument?

Yes - they receive the `TextDocument` itself and that is immutable. Also the two extensions might run on different extension hosts. I am closing the as extension-issue. There is nothing we can as post-save things aren't under our or anyones control. It seems it just a conflict that can occur and which does occurs often in this specific setup
