### ISSUE TITLE
Feature request: Jake tasks integration

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#13322]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. List tasks
2. Jake tasks should be listed

**Comment by Tyriar** [comment]
@vp2177 is this something that could be accomplished with an extension?

**Comment by vp2177** [comment]
@Tyriar yes even though VSCode has built-in support for `grunt` and `gulp` tasks, actually, the docs also mention Jake: https://code.visualstudio.com/docs/editor/tasks#_autodetecting-gulp-grunt-and-jake-tasks

**Comment by Tyriar** [comment]
@waderyan @gregvanl did we remove Jake support due to low usage or something?

**Comment by waderyan** [comment]
I was not aware of this. @chrisdias do you have context for this? We talk about Jake in the [docs](https://code.visualstudio.com/docs/editor/tasks#_autodetecting-gulp-grunt-and-jake-tasks), but we don't show it with the Configure Task command. 

![image](https://cloud.githubusercontent.com/assets/2449568/19206677/7f8e1ca8-8c9f-11e6-8901-05c6ca0da3e5.png)

We may need to simply update the docs and then keep this alive as a valid feature request to bring Jake back.

**Comment by chrisdias** [comment]
yes, jake had very low usage.

cc @dbaeumer

**Comment by dbaeumer** [comment]
+1 for updating the doc and keep this around as a feature request.

**Comment by waderyan** [comment]
Doc issue here - https://github.com/Microsoft/vscode-docs/issues/636
