### ISSUE TITLE
shift-enter not always running current cell

### ISSUE THREAD

**Issue by cplager** [microsoft/vscode#133266]
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: Windows 10 version 1909
-   Python and/or Anaconda version: 3.83
-   Type of virtual environment used Anaconda
-   Jupyter server running: Local 

## Expected behaviour

shift-enter  is supposed to run existing cell and then move down to next existing cell.
control-enter is supposed to run existing cell and then create a new cell and move to it.

## Actual behaviour

Often shift-enter runs another cell. Control-enter as well.  Does not always happen, but it happens a lot.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by roblourens** [comment]
Likely the same as https://github.com/microsoft/vscode/issues/133038

**Comment by cplager** [comment]
> Likely the same as #133038

Agreed.
