### ISSUE TITLE
Quick Fix from anywhere on the line

### ISSUE THREAD

**Issue by gregveres** [microsoft/vscode#133253]
I would like to request that Quick Fix can be launched from anywhere on the line with the error. 

This is important because it promotes developer flow. When I am  writing code, I know the line I want to write and I am typing it out. I may end up typing some things that need imports or other types of fixes along the way, but at the time, it is important for me to get my idea out than it is for it to be perfect. But then I have to move the cursor all over the line to let quick fix help me out. I would rather that quick fix give me solutions for every error on the line and let me pick which ones I want to address or let me apply all of them if I know they are all unrelated. 

Here is a really simple example. 

Say I am writing a function, in this case I am writing a jest test function and the code snippet I have used didn't make the function async. Part way through writing the testing code, I realize that I need the test to be async. There is a great quick fix for that, as soon as I type await in the function, I get a quick fix suggestion to make the function async. Here is what I was typing at the time:

 await flushPromises();

now, the quick fix suggestion wasn't fast enough to show up when I typed the t and before I typed the space, and I didn't pause long enough for it to come up, make the selection and move on. Instead, I just typed the entire line and then looked back and noticed the error on the await. At this point my cursor is after the ; and quick fix says it has no suggestions. 

I would like to see quick fix recognize that there are errors on this line and give me the suggestion for all the errors on the line. 

If handling all the errors on the line is too difficult, I would settle for only allowing this behaviour if there is only a single error on the line - show me the error / quick fix suggestion as if my cursor was on the error. This would save us developers a ton of time moving the cursor back to the error location to be able to pick up the quick fix suggestion.

**Comment by mjbvz** [comment]
Thanks for the issue report!

This is already being tracked by #117767

**Comment by gregveres** [comment]
sorry for the duplicate. I did a search but I didn't see that one in the results.
