### ISSUE TITLE
Unable to read file!

### ISSUE THREAD

**Issue by romi477** [microsoft/vscode#133238]
Hi, i have a wierd trouble. Unable to open/read file during ''find in folder" (Alt + Shift + F) request in previously added to workspace directory. It's trouble only for separate search window. I have a lot of results in the search response, but i cannot open any found file. In "sidebar window"  (Ctrl + Shift + F)  the search works correctly.

- VS Code Version: 1.60.1
- OS Version: Ubuntu 20.04.3 LTS
![no_open_1](https://user-images.githubusercontent.com/35193232/133590737-95f4e624-fbb6-46f0-a763-d85ef77287ca.png)
![no_open_2](https://user-images.githubusercontent.com/35193232/133590744-6ea104aa-6121-44c4-b7ef-8b144d15f208.png)

**Comment by JacksonKearl** [comment]
Does the path in the error message exist? If not, what is the correct path? Also, what does your workspace configuration file look like?

**Comment by romi477** [comment]
Sure... it's a valid path. As i said previously the search works correctly and i can open required file in the "sidebar window" (Ctrl + Shift + F), and i have a problem in the separate window search ('find in folder" (Alt + Shift + F)).

`{
	"folders": [
		{
			"path": ".."
		},
		{
			"path": "../../../../odoo/14"
		},
		{
			"path": "../../../../odoo/10"
		},
		{
			"path": "../../10"
		}
	],
	"settings": {
		"terminal.integrated.cwd": "${workspaceFolder}/erp/",
		"git.ignoreLimitWarning": true
	}
}`

**Comment by JacksonKearl** [comment]
Could you try providing explicit names for those folders (the `name` property in addition to `path`)?  Also it may help to provide absolute paths rather than relative ones.
