### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Longdoahihi** [microsoft/vscode#133243]
- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.60.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by IllusionMH** [comment]
/needsMoreInfo

You forgot to paste problem details.
