### ISSUE TITLE
AFTER UPDATE IT SHOWS PERMISION DENIED AFTER RUNING A CODE 

### ISSUE THREAD

**Issue by geetanjalichawla** [microsoft/vscode#133241]
We have written the needed data into your clipboard beca
Issue Type: <b>Bug</b>

AFTER UPDATE IT SHOWS PERMISION DENIED AFTER RUNING A CODE 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (2.62GB free)|
|Process Argv|--crash-reporter-id 7e424b45-c0ed-43fe-81e0-7b5c37af7d14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.5
cpptools|ms-|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

use it was too large to send. Please paste.

**Comment by geetanjalichawla** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/80254854/133592744-0e0eacda-22d0-4d50-966f-b515be87bbf3.png)

**Comment by roblourens** [comment]
It looks like this is either an issue with your setup or with the C++ extension
