### ISSUE TITLE
Bazel BUILD files detected as Python due to Automatic Language Detection

### ISSUE THREAD

**Issue by grantwwu** [microsoft/vscode#133297]
Does this issue occur when all extensions are disabled?: No, this is a bug originating from the interaction of a feature and the extension

Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.119-14945-gafc97d54f809
Steps to Reproduce:

1. Have a Bazel BUILD file.
2. Disable Automatic Language Detection (i.e. `"workbench.editor.languageDetection": false`)
3. Have the BazelBuild.vscode-bazel extension installed.
4. See that Bazel files are set as the Starlark language
5. Now enable Automatic Language Detection (i.e. `"workbench.editor.languageDetection": true`)
3. Note that Bazel files are being automatically detected as Python.

A confluence of issues causes this:
1. BUILD files don't have an extension
2. Automatic Language Detection doesn't know about Starlark
3. Starlark looks a lot like Python

My ask here is essentially that the VSCode Bazel extension previously was able to have its own detection logic, and detect these files as Starlark files. Automatic Language Detection is overriding this. Is there some way to make it so that languages set by extensions override what ALD does?

In the interim I am working around this by disabling the new ALD feature for Starlark specifically.

**Comment by grantwwu** [comment]
cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
@grantwwu what version of VS Code are you using?

**Comment by grantwwu** [comment]
1.60.0, sorry, I didn't realize that the big blob of info I copied didn't actually have the version number 😅

**Comment by grantwwu** [comment]
Is this fixed in https://github.com/microsoft/vscode/issues/132173 ?

**Comment by grantwwu** [comment]
The issue appears to have been fixed in 1.60.1.

**Comment by TylerLeonhardt** [comment]
Yep! You found it :)

**Comment by TylerLeonhardt** [comment]
Closing as a duplicate/already fixed
