### ISSUE TITLE
JSON property value IntelliSense

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#13324]
- VSCode Version: 1.5.3
- OS Version: Windows 10 1607

Steps to Reproduce:
1.  Create a tsconfig.json file
2.  Add "compilerOptions", then "target"

The tooltip over "target" says: Permitted values are 'es3', 'es5', or 'es2015'.
It would be much better to just provide those 3 values as candidates of completion. Use IntelliSense hotkey Ctrl+Space only show the default value, still doesn't provide completion candidates.

**Comment by waderyan** [comment]
@cnshenj thank you for your feedback. This is an excellent find! 

@dbaeumer handing this off to you. 

Tested with latest Insiders build. 

![image](https://cloud.githubusercontent.com/assets/2449568/19206787/3e285be2-8ca0-11e6-9a74-7dcba981a9fe.png)

Code to copy and paste. 

```json
{
    "compilerOptions": {
        "target": "ES6"
    }
}
```

OP and I expect to see all possible values in IntelliSense suggestion box.

**Comment by dbaeumer** [comment]
@waderyan this is owned by the TS team. We present this using the schema they maintain (https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json#L209). But you can do PR against the schema store directly.

**Comment by waderyan** [comment]
cool. Created a PR - https://github.com/SchemaStore/schemastore/pull/237

**Comment by mjbvz** [comment]
Resubmitted as https://github.com/SchemaStore/schemastore/pull/268

Closing as upstream
