### ISSUE TITLE
Enable more than one window on the same workspace

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#13329]
- give the user the option to open more than one window on the same workspace, but avoid that the user does this by accident when they forgot that they already have a windows open.

- provide an API so that the debugger can do this programmatically

**Comment by egamma** [comment]
@bpasero I've deferred this in favor of investigating into first class multi-target debugging support.

**Comment by bpasero** [comment]
@egamma Ok, we should close this one as duplicate of https://github.com/Microsoft/vscode/issues/2686 then if we do not plan to work on it for October.

**Comment by egamma** [comment]
Makes sense. Closing as suggested.
