### ISSUE TITLE
Failed to install extension: ms-vscode-remote.ssh XHR failed

### ISSUE THREAD

**Issue by ryanxsim** [microsoft/vscode#133226]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.59.1
- OS Version: Windows Server 2016 Standard

Steps to Reproduce:

- Download latest VSIX of the remote-ssh extension
- Try installing the VSIX file in vscode
- Tried installing older Versions of remote-ssh extension

I'm unable to install my ssh-remote Extension pack (version: 0.65.8). I tried to install it from the .vsix file but every time this message pops up: "Failed to install extension: ms-vscode-remote.remote-ssh XHR failed". I do not have internet access on this server so I can not install it directly from the marketplace. 

![image](https://user-images.githubusercontent.com/67103111/133576714-ba828094-e429-4ce5-9201-5fed45303c24.png)

**Comment by sandy081** [comment]
Please update to latest release 1.60.1 and try again

**Comment by ryanxsim** [comment]
Great, that worked, thanks for your help.
