### ISSUE TITLE
execvp(3) failed. Permission denied, The terminal process "bash '-l'" failed to launch (exit code: 1).

### ISSUE THREAD

**Issue by roviram** [microsoft/vscode#133275]
Does this issue occur when all extensions are disabled?: Yes

- **VS Code Version**: Version: 1.59.1 (Universal)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (4 wks ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
**OS**: Darwin x64 19.6.0

**DESCRIPTION OF ISSUE**:
bash is my default shell in my MacOS terminal. Whenever I open up the terminal in VSC, I get the following error "execvp(3) failed. Permission denied, The terminal process "bash '-l'" failed to launch (exit code: 1)."

I have checked my preferences - > settings -> changed "terminal.integrated.defaultProfile.osx" to "bash" or left it as null. I have compared my settings with my friends who also use VSC and we have the exact same default json setting preferences and they are able to use bash instead of zsh as their shell when using the terminal through VSC.

I have also tried to override the default settings using "terminal.integrated.automationShell.osx"
Here are the several combinations I have tried and still facing this issue:
 "terminal.integrated.automationShell.osx": null,
 "terminal.integrated.automationShell.osx": "bash",
 "terminal.integrated.automationShell.osx": "bin/bash",

![Screen Shot 2021-09-16 at 11 51 18 AM](https://user-images.githubusercontent.com/16768182/133669072-a85f506e-d124-4691-86a8-25392bf31e33.png)

Let me know if you need any further information.

**Comment by notbucai** [comment]
Same question
