### ISSUE TITLE
editorIndentGuide.activeBackground not working

### ISSUE THREAD

**Issue by christo070** [microsoft/vscode#133263]
Issue Type: <b>Bug</b>

Applying 
"editorIndentGuide.activeBackground" : "#ff0000",
in "workbench.colorCustomizations"{ } of settings.json 
does not work even though 
"editorIndentGuide.background" : "#ff0000"
works.
If it is mistake from my part, please guide how to enable 'highlight active indent guide' in VSCode.
Thanks

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (9.45GB free)|
|Process Argv|--crash-reporter-id e6c5d090-3265-456a-b3b8-150c2a5d7680|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.25
competitive-programming-helper|Div|5.8.7
docs-markdown|doc|0.2.97
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|2.2.0
prettier-vscode|esb|8.1.0
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
vscode-phpfmt|kok|1.0.30
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
live-server|ms-|0.2.8
material-icon-theme|PKi|4.10.0
vscode-css-peek|pra|4.2.0
open-php-html-js-in-browser|Pri|2.0.1
java|red|0.81.0
errorlens|use|3.4.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
material-theme|zhu|3.11.4
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details>

**Comment by ArturoDent** [comment]
Works here for me on W11 Insiders and Stable.  Did you try it with all extensions disabled?

**Comment by christo070** [comment]
Sorry, It was my mistake, now I am able to enable it after tweaking some settings.
For me, Editor: Highlight Active Indent Guide  was not enabled by default. Found that later.
Thanks
