### ISSUE TITLE
VSCode freeze when opening a new folder

### ISSUE THREAD

**Issue by Kowalski-Zireael** [microsoft/vscode#133212]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60
- OS Version: Linux version 5.4.0-85-generic Ubuntu 20.04

Steps to Reproduce:

1. Open a new empty window
2. Open a folder
3. Then the editor freeze but the menu is still work
However when I opened a folder containing simple document (like only one CSS file with 50 lines) it won't freeze

**Comment by Kowalski-Zireael** [comment]
Does this issue occur when all extensions are disabled?: Yes

**Comment by Kowalski-Zireael** [comment]
[code.txt](https://github.com/microsoft/vscode/files/7174761/code.txt)
this is the log output when I open vscode second time with last time opening a folder already and freezing

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/wiki/Performance-Issues has some tips on how to find out which process or extension is causing this.

**Comment by Kowalski-Zireael** [comment]
I've tried, but the question is nothing causes high CPU consumption. What's more, I found that if a folder is causing freezing problem, opening a new empty window and opening any folder else won't cause any problem. Even, renaming it can also solving the problem... That's wired.

**Comment by Kowalski-Zireael** [comment]
Process Explorer shows all 0's in column "CPU%" before and after freezing.I also check the memory. It still have 3G more free memory

**Comment by Kowalski-Zireael** [comment]
After renaming the folder, I rename it back and freezing shows again

**Comment by aeschli** [comment]
So with freezing you mean the window stays empty?
Can you open the dev tools (Help > Toggle Developer Tools) and see if there's something in the console?

**Comment by Kowalski-Zireael** [comment]
Editor shows the content successfully, but it will immediately become unable to respond and alert a "The window is not responding" message

**Comment by Kowalski-Zireael** [comment]
Open terminal or Toggle Developer Tools usually arises the same problem

**Comment by Kowalski-Zireael** [comment]
I clicked Toggle Developer but nothing happened

**Comment by Kowalski-Zireael** [comment]
No output shows up in the console. It's like the console seems freezing as well.

**Comment by Kowalski-Zireael** [comment]
Is some config being written to the file combining with the folder when freeze occur, and next time I open the same folder, it will load such "bug" config and make freezing again?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Based on the logs gpu process is crashing with segmentation fault, can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash logs if the issue repros with insiders as well.

Also can you confirm the value of `systemctl --version`

**Comment by Kowalski-Zireael** [comment]
➜  ~ systemctl --version
systemd 245 (245.4-4ubuntu3.13)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Comment by Kowalski-Zireael** [comment]
the .dmp files zip:
[dmp.zip](https://github.com/microsoft/vscode/files/7189098/dmp.zip)

Meanwhile... chrome browser usually freeze as well (so I use Firefox instead). Maybe there are some relations??

**Comment by Kowalski-Zireael** [comment]
The freezing problem haven't shown in insiders version. I will keep looking on it

**Comment by Kowalski-Zireael** [comment]
Freezing shows again in insiders version, but it seems that the editor can work for about 8s and then freeze. Not like the common version that crash immediately.
Tow .dmp files
[dmp.zip](https://github.com/microsoft/vscode/files/7189117/dmp.zip)
:
[dmp-insiders.zip](https://github.com/microsoft/vscode/files/7189118/dmp-insiders.zip)

Meanwhile, the chrome browser is usually freeze as well (so I use Firefox instead now). Maybe there are some relations?
