### ISSUE TITLE
Indicate to user when JS/TS Server is running in syntax only mode

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#133296]
On GitHub.dev, we currently only provide JS/TS intellisense within the current file. We should add a new language status item that tells users about this

A few other cases where this status item could be useful:

- During project loading
- If a user has configured `"typescript.tsserver.useSyntaxServer": "always"`

**Comment by jrieken** [comment]
Verified but it is a little thin... We should add a 'learn more' link that explains what's going on and how to proceed alternatively (continue on). The same/similar thing is planned for anycode
