### ISSUE TITLE
Ability to hide activity bar!

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13326]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 16.1.0

The activity bar take many columns. In the other way, we can easy call it use shortcut like `cmd+shift+e` for explorer. 
Should we narrow it or give a config item to hidden it.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1105

**Comment by leaxoy** [comment]
👌 Thanks
