### ISSUE TITLE
Cannot Open Terminal

### ISSUE THREAD

**Issue by javierabosch2** [microsoft/vscode#133280]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

After building the remote container. I tried to click on the + button to open a new terminal and nothing happend. 

I went to the Terminal Menu and to start New Terminal and it displayed an error: Cannot use 'in' operator to search for 'path' in /bin/bash 

```
[2021-09-16 15:49:05.673] [renderer3] [error] Cannot use 'in' operator to search for 'path' in /bin/bash: TypeError: Cannot use 'in' operator to search for 'path' in /bin/bash
    at c (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:327)
    at f (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:213)
    at A (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:117:7846)
    at f.getProfiles (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:7472)
``` 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-81-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 1b8525d7-77e7-4706-b25f-d9a77947b25c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Lambda1 - Tsuyaku3 - Bosch @ ssh://vg@mtsut-lambda1|
|OS|Linux x64 5.4.0-81-generic|
|CPUs|Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (48 x 1000)|
|Memory (System)|251.56GB (11.47GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.10.0
TabOut|alb|0.2.1
gitlens|eam|11.6.0
todo-tree|Gru|0.0.214
git-graph|mhu|1.30.0
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
autodocstring|njp|0.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by stsnkmr** [comment]
I have same problem...
OS : mac OS BigSur (intel)
VS Code version: Code 1.60.1 (83bd43b, 2021-09-10T17:09:14.403Z)

**Comment by stsnkmr** [comment]
> We have written the needed data into your clipboard because it was too large to send. Please paste.
> Issue Type: Bug
> 
> After building the remote container. I tried to click on the + button to open a new terminal and nothing happend.
> 
> I went to the Terminal Menu and to start New Terminal and it displayed an error: Cannot use 'in' operator to search for 'path' in /bin/bash
> 
> ```
> [2021-09-16 15:49:05.673] [renderer3] [error] Cannot use 'in' operator to search for 'path' in /bin/bash: TypeError: Cannot use 'in' operator to search for 'path' in /bin/bash
>     at c (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:327)
>     at f (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:213)
>     at A (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:117:7846)
>     at f.getProfiles (/root/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/remoteExtensionHostAgent.js:118:7472)
> ```
> 
> VS Code version: Code 1.60.1 ([83bd43b](https://github.com/microsoft/vscode/commit/83bd43bc519d15e50c4272c6cf5c1479df196a4d), 2021-09-10T17:09:14.403Z)
> OS version: Darwin x64 20.6.0
> Restricted Mode: No
> Remote OS version: Linux x64 5.4.0-81-generic
> 
> System Info
> Extensions (18)
> A/B Experiments

I solved this problem.

My old settings.json ↓
```
    "terminal.integrated.profiles.osx": "/bin/zsh",
```
I rewrited this passage.
```
    "terminal.integrated.profiles.osx": {
        "zsh": {
            "path":"/bin/zsh",
            "icon": "window", // this passage is anything ok.
        }
    },
```

**Comment by meganrogge** [comment]
Glad you figured it out!
