### ISSUE TITLE
Improvements to Debug Console window

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode#133298]
There is no command to scroll up and down the debug console. As a result, it is impossible to do this via keyboard shortcuts. Furthermore, while focussed on the line with the prompt `>` in the debug console, also provide a command to toggle between this prompt and the various other input line related to the Debug console: Filter, Clear Console, Maximize Panel Size and Close Panel.

**Comment by roblourens** [comment]
You can shift+tab back to the list and use cmd+up/down to scroll (this is `list.scrollUp/scrollDown` if you want to rebind it). You can also tab back to focus the toolbar with those buttons.
