### ISSUE TITLE
debug-continue icon is bolder than others

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133293]
@misolori we are trying to use the `debug-continue` icon for a button in the cell toolbar, but it has a more bold appearance than other icons. It seems like this is probably just on purpose because all the debug icons are colored and look nice with bold lines. But it might mean that we can't reuse them in other places. Or it might be fine. What do you think?

![image](https://user-images.githubusercontent.com/323878/133703233-026bad7c-8b4a-4f3b-a1d5-11334e28e48e.png)

cc @DavidKutu

**Comment by DavidKutu** [comment]
I'd prefer it not being bold.

**Comment by roblourens** [comment]
I think it's ok for now, gonna move it off Sept, but let me know if you have any ideas @misolori

**Comment by misolori** [comment]
I can add a less bold version for each of the debug icons? Or should it just be continue?

**Comment by roblourens** [comment]
That would help. I only plan to use continue

**Comment by misolori** [comment]
Ok we now have `debug-continue-small` that we can use the uses the regular 1px stroke:

![image](https://user-images.githubusercontent.com/35271042/134707211-2a28eb20-054a-40dd-a9be-5d2d5363475d.png)
