### ISSUE TITLE
Unclear copy for what sync settings will be replaced

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#133262]
I finally enabled Settings Sync as I had more projects in Codespaces but missed extensions I got used to. After enabling Settings Sync, I got:

<img src=https://user-images.githubusercontent.com/8599/133640718-bb562422-90d0-4600-b638-35f9604e45aa.png width=200>

`Replace Local` might be what I want (as I don't care about the prior backups) but I can't tell. Does it replace _my_ local with the cloud data – does it replace the cloud with my local? `Would you like to merge or replace with your data in the cloud?` also doesn't help as "your data" is ambiguous.

**Solution**

Maybe making it a bit wordier can help:

> *Do you want to replace or merge the existing cloud data?*
>
> Your cloud data is synced from another machine. If you like to keep machines in sync, merge their data. If this machine has the setup you prefer, replace your cloud data.
>
> [Merge local with cloud data]
> [Replace cloud with local data]
> [Replace cloud with local data]

---

Related UI from steam that makes it crystal clear:

<img src=https://user-images.githubusercontent.com/8599/133641228-f14da444-52ec-444e-baba-ef41ff0e07a1.png width=300>

**Comment by misolori** [comment]
We’ve been using these actions for quite a while now and not sure if we’ve seen this feedback/confusion before. Adding @sandy081 for more context.

**Comment by digitarald** [comment]
@misolori do you question if this is widespread problem or that the actions are not clear enough?

I am not sure how many users are ever seeing this, as it requires a sync from another machine to be sitting in the cloud.

**Comment by misolori** [comment]
I question whether this is a problem as I haven't seen any feedback around this (I could be wrong). Looking back the release notes, this was added in [July 2020](https://code.visualstudio.com/updates/v1_48#_settings-sync) and a previous version was in [May 2020](https://code.visualstudio.com/updates/v1_46#_settings-sync) so we've definitely had this flow for a while.

We previously had an action "Replace Cloud with Local Data" but after looking at the various use cases that seemed like a rare actions as most users are wanting to sync a new machine with their cloud data. So that's how we ended up with those two actions.

**Comment by digitarald** [comment]
> We previously had an action "Replace Cloud with Local Data" but after 

Sorry, I had misunderstood what the button does. I am not suggesting adding any more options.

I now understand from the last comment that `Replace Local` indeed wipes my local setup and puts whatever was synced to cloud before. I still can't confidently read this from the text with a _new user_ hat on.

**Comment by sandy081** [comment]
I have not received any issues for this dialog/actions. But I think it's not rare to get this dialog for users. TBH I do not have numbers but I log telemetry when users choose an action using event id - `sync/firstTimeSync`

Please let me know what is the recommended wordings for this dialog and actions. I will be happy to change.

**Comment by sandy081** [comment]
Reopening this as per request from team and recommendations as follows:

Provide a **More Information** or **Learn More** link in the prompt and clicking on it opens a modal dialog explaining about the actions

![image (1)](https://user-images.githubusercontent.com/10746682/145181238-142f6777-e051-4712-a324-5949442486ce.png)

**Comment by sandy081** [comment]
We no longer show this dialog. Hence closing this.
