### ISSUE TITLE
Python extension loading... (forever..)

### ISSUE THREAD

**Issue by dreammirror000** [microsoft/vscode#133240]
Hello, 
The python extension is not able to load.
I looked online, but couldn't fix with the only recommendation which were to install an older version. 
Best regards.

info sys: 
<html>
<body>

CPUs | Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.85GB (8.88GB free)
Process Argv | XXXXXX --crash-reporter-id 7fe0681a-24f0-4a55-ab67-22fbc84a4c1f
Screen Reader | no
VM | 0%

</body>
</html>

<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
gc-excelviewer | Gra | 3.0.44
vscode-language-pack-fr | MS- | 1.60.4
python | ms- | 2021.10.1239554536-dev
vscode-pylance | ms- | 2021.9.1
jupyter | ms- | 2021.8.2041215044
jupyter-keymap | ms- | 1.0.0
cpptools | ms- | 1.6.0

</body>
</html>

vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30367819
vssid140:30363603
vssur157:30367808

**Comment by aeschli** [comment]
This issue needs to be filed against https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
