### ISSUE TITLE
Format typescript code does not work properly with comment

### ISSUE THREAD

**Issue by osechet** [Microsoft/vscode#13327]
- VSCode Version: 1.5.3
- OS Version: Windows 10 / Ubuntu 16.04

Steps to Reproduce:

1. Open this [file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80060c94ef549c077a011977c2b5461bd0fd8947/openlayers/index.d.ts)
2. Call the format code command.
3. Some comments are not formatted as expected. For example, around line 62 or 149. The indent is wrong.

**Comment by waderyan** [comment]
@osechet thank you for opening this issue. This is a good find and easy to follow recreation steps. 

The format code command is dependent on the TypeScript language service. I will send this issue to their repo. 

Here are images of the problem. 

![image](https://cloud.githubusercontent.com/assets/2449568/19206882/eea2928a-8ca0-11e6-9a18-fd08e115df96.png)

![image](https://cloud.githubusercontent.com/assets/2449568/19206890/fadbcfda-8ca0-11e6-841b-600652076234.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11456
