### ISSUE TITLE
Allow to split an editor into an existing group

### ISSUE THREAD

**Issue by Conchylicultor** [microsoft/vscode#133260]
When I edit code, I often use the `Right click -> Split right` to duplicate a file side by side. However I rarely need more than 2 panes open at the same time.

When a pane already exists on the right, it would be nice if `Right click -> Split right` duplicate the file in the existing pane, rather than creating a new one.
So the first time, `Right click -> Split right` would create a new pane, then the future `Right click -> Split right` would reuse the new existing right pane.

In the less frequent case where users need 3 or more panes, it would still be possible to create new panes by using `Right click -> Split right` on the right-most pane.

I think it would simplify the most frequent use-case where user want to duplicate a file (to view it side by side), but want to reuse the existing opened pane.

This new behavior could be controlled by a new setting option.

Currently, when the editor is split in 2: Everytime we need to duplicate a file, `Right click -> Split right` create a third collumn (in the middle), and we need to manually drag the file into the right collumn to close the middle collumn.

**Comment by bpasero** [comment]
@Conchylicultor does https://twitter.com/BenjaminPasero/status/1437460422462947330 help?

Refs https://github.com/microsoft/vscode/issues/132651

**Comment by Conchylicultor** [comment]
Thanks for the pointer. However this does not really solve my issue. I want to keep my editor split in 2-groups with each groups having tabs. #132651 only seems useful to have two views of the same file. However in many case, my 2 groups contain different files and I'm controlling each groups individually (through tabs).

**Comment by bpasero** [comment]
Understood. I added the following 8 commands to split editors into other groups, reusing groups if present:

![image](https://user-images.githubusercontent.com/900690/133783794-d3dae4ad-24e7-450d-997d-90b9197a686b.png)

* `workbench.action.splitEditorToPreviousGroup`
* `workbench.action.splitEditorToNextGroup`
* `workbench.action.splitEditorToAboveGroup`
* `workbench.action.splitEditorToBelowGroup`
* `workbench.action.splitEditorToLeftGroup`
* `workbench.action.splitEditorToRightGroup`
* `workbench.action.splitEditorToFirstGroup`
* `workbench.action.splitEditorToLastGroup`

**Comment by Conchylicultor** [comment]
Awesome! Thank you for the fast implementation.
Is there a way to use those from the contextmenu (`right click > split left`) ? Or will this require creating an extention ?

**Comment by bpasero** [comment]
Currently no plans to add this to the context menu to keep it small.
