### ISSUE TITLE
TypeScript Language Server Repeatedly Crashes on WSL2

### ISSUE THREAD

**Issue by killshot13** [microsoft/vscode#133264]
Issue Type: <b>Performance Issue</b>

# VS Code Bug Report

## TypeScript Language Server

* What Happened?
A few minutes after opening VS Code, I received a notification about the TypeScript server crashing repeatedly. In fact, I believe it said this behavior had occurred more that five times in the past several minutes.

* What was I Doing?
I was not actively using TypeScript within the app I was building, and no TypeScript files were open in the editor or referenced from the terminal, so I cannot provide much more detail to further narrow down a method to reproduce.

* What did I Expect to Happen?
I assumed the TypeScript server would either not be running at all, or if there was a reason for it to be active of which I am unaware, that it would function as designed, quietly and out of sight without crashing or otherwise causing a distraction.

* Additional Info
Hopefully the system diagnostics will help fill in the gaps concerning this matter. I am sorry that I cannot offer much additional detail at this time.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (0.28GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/wsl2/dev/repoOrg/ormicaOrg/ormica-development --remote=wsl+Ubuntu --crash-reporter-id 4a30d5b9-1cd9-45e7-b6f1-ae3997de3ba4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (4 x 1497)|
|Memory (System)|4.82GB (0.59GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    67	 24048	code main
    0	     2	  2552	   crashpad-handler
    1	   162	  9332	   window (SearchBar.js - ormica-development [WSL: Ubuntu] - Visual Studio Code)
    0	    53	  7328	     extensionHost
    0	    29	  2164	       electron_node serverMain.js 
    0	    17	  2176	       electron_node wslDaemon.js 
    0	     5	  2572	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c 'env && VSCODE_WSL_DEBUG_INFO=true "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 83bd43bc519d15e50c4272c6cf5c1479df196a4d stable .vscode-server 0  '
    0	     5	  6796	           console-window-host (Windows internal process)
    0	     4	 19892	           C:\Windows\System32\lxss\wslhost.exe --mode 2 --distro-id {5963433f-3acb-41cb-8833-05179eaf085a} --vm-id {35c64e06-ae02-4447-b2c1-754c3a7cf87d} --handle 716 --event 740 --parent 744
    0	     5	  2968	             console-window-host (Windows internal process)
    0	    83	 15628	   shared-process
    0	     8	  7612	     ptyHost
    1	    64	 20000	   window (Issue Reporter)
    0	   145	 21356	   gpu-process
    0	    15	 25452	   utility

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	  3129	remote agent
    0	     0	  3141	   ptyHost
    0	     0	  3426	   watcherService
    4	     0	  3687	   extensionHost
    0	     0	  3763	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/extensions/webhint.vscode-webhint-1.5.12/dist/src/server.js /home/wsl2/.vscode-server/data/User/globalStorage/webhint.vscode-webhint enabled true --node-ipc --clientProcessId=3687
    0	     0	  3770	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/extensions/mtxr.sqltools-0.23.0/dist/languageserver.js --node-ipc --clientProcessId=3687
    0	     0	  3816	     /home/wsl2/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.1 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Palenight (Mild Contrast) vscode-theme-kind=Dark vscode-machine-id=b1739dbee5826dc5c57093d116a655877a51bae241c06281d772cd6aa703f0f1 vscode-is-new-app-install=false vscode-session-id=d0ace531-4282-4126-a9ae-963f4223c8271631808878808 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	     0	  3865	       /home/wsl2/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/WD-TabNine --client vscode --client-metadata clientVersion=1.60.1 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Palenight (Mild Contrast) vscode-theme-kind=Dark vscode-machine-id=b1739dbee5826dc5c57093d116a655877a51bae241c06281d772cd6aa703f0f1 vscode-is-new-app-install=false vscode-session-id=d0ace531-4282-4126-a9ae-963f4223c8271631808878808 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	     0	  3866	       /home/wsl2/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --client-metadata clientVersion=1.60.1 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Palenight (Mild Contrast) vscode-theme-kind=Dark vscode-machine-id=b1739dbee5826dc5c57093d116a655877a51bae241c06281d772cd6aa703f0f1 vscode-is-new-app-install=false vscode-session-id=d0ace531-4282-4126-a9ae-963f4223c8271631808878808 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
    6	     0	  3955	         /home/wsl2/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/3.6.8/x86_64-unknown-linux-musl/TabNine-deep-local --settings /home/wsl2/.config/TabNine/local.settingsSmall --settings-version 1 --client vscode --client-metadata clientVersion=1.60.1 pluginVersion=3.4.27 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=wsl vscode-extension-kind=2 vscode-theme-name=Palenight (Mild Contrast) vscode-theme-kind=Dark vscode-machine-id=b1739dbee5826dc5c57093d116a655877a51bae241c06281d772cd6aa703f0f1 vscode-is-new-app-install=false vscode-session-id=d0ace531-4282-4126-a9ae-963f4223c8271631808878808 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
    0	     0	  3837	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=3687
    0	     0	  4118	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/extensions/graphql.vscode-graphql-0.3.18/out/server/server.js --node-ipc --clientProcessId=3687
    0	     0	  4119	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.25/server/out/eslintServer.js --node-ipc --clientProcessId=3687
    0	     0	  4172	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/wsl2/.vscode-server/extensions/pranaygp.vscode-css-peek-4.2.0/server/out/server.js --node-ipc --clientProcessId=3687
    0	     0	  4555	     /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node --max-old-space-size=128 /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/3531c972e644e8b2cd24/tscancellation-09f1aafa96f248c1b2e3.tmp* --globalPlugins typescript-vscode-sh-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations /home/wsl2/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/extensions/typescript-language-features,/home/wsl2/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.2.14 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
    0	     0	  4599	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4600	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (ormica-development): 197 files|      File types: js(84) jpg(25) png(23) json(7) md(4) env(2) gitignore(2)
|                  prettierignore(2) xml(2) svg(2)
|      Conf files: package.json(2) launch.json(1) settings.json(1)
|                  tasks.json(1) jsconfig.json(1)
|      Launch Configs: pwa-node;
```

</details>
<details><summary>Extensions (150)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.4
emojisense|bie|0.9.0
es7-react-js-snippets|dsz|3.1.1
LogFileHighlighter|emi|2.11.0
auto-rename-tag|for|0.1.8
codespaces|Git|1.0.5
helium-icon-theme|hel|1.0.0
Kotlin|mat|1.7.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-azurevirtualmachines|ms-|0.4.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
back-n-forth|nic|3.1.1
chai-snippets|nwh|0.1.0
shellman|Rem|5.6.0
shebang-snippets|rpi|0.1.4
svg-preview|Sim|2.8.3
swdc-vscode|sof|2.5.24
highlight-matching-tag|vin|0.10.1
gistfs|vsl|0.3.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
codesnap|adp|1.3.4
html-end-tag-labels|ant|0.8.0
armview|ben|0.4.5
close-all|ben|1.0.2
emojisense|bie|0.9.0
markdown-checkbox|bie|0.3.2
simple-react-snippets|bur|1.2.4
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
codechampion-vscode|Cod|0.0.3
gitignore|cod|0.7.0
vscode-database-client2|cwe|4.1.5
vscode-markdownlint|Dav|0.43.2
vscode-eslint|dba|2.1.25
flowbookmark|Dee|5.0.0
vscode-faker|dee|1.5.0
githistory|don|0.6.18
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
apacheconf-snippets|eim|1.3.0
LogFileHighlighter|emi|2.11.0
prettier-vscode|esb|8.1.0
vscode-github-notifications-bell|fab|2.3.1
git-project-manager|fel|1.7.1
php-debug|fel|1.18.0
auto-rename-tag|for|0.1.8
shell-format|fox|7.1.0
kotlin|fwc|0.2.23
gatsbyhub|Gat|1.0.8
codespaces|Git|1.0.5
vscode-codeql|Git|1.5.5
vscode-pull-request-github|Git|0.30.0
vscode-graphql|Gra|0.3.18
vscode-test-explorer|hbe|2.21.1
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
vscode-placeholder-images|Jak|0.1.0
search-node-modules|jas|1.3.0
snipped|jef|0.25.0
vscode-rufo|jnb|0.0.4
php-cs-fixer|jun|0.2.5
google-search|kam|0.0.1
Kotlin|mat|1.7.1
template-string-converter|meg|0.5.3
php-constructor|Meh|0.1.2
vscode-language-babel|mgm|0.0.35
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.4
mongodb-vscode|mon|0.6.10
vscode-apache|mrm|1.2.0
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.10.0
azure-pipelines|ms-|1.191.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-azurevirtualmachines|ms-|0.4.1
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
cpptools|ms-|1.6.0
js-debug|ms-|1.60.2
powershell|ms-|2021.9.0
test-adapter-converter|ms-|0.1.2
vscode-js-profile-flame|ms-|0.0.21
vscode-node-azure-pack|ms-|0.2.1
vscode-react-native|msj|1.6.1
sqltools|mtx|0.23.0
resourcemonitor|mut|1.0.7
back-n-forth|nic|3.1.1
chai-snippets|nwh|0.1.0
vscode-yaml-sort|Pas|5.1.0
vscode-versionlens|pfl|1.0.9
vscode-php-getters-setters|php|1.2.3
vscode-css-peek|pra|4.2.0
todo-txt|rar|0.0.5
ruby|reb|0.28.1
shellman|Rem|5.6.0
mongo-snippets-for-node-js|roe|1.3.10
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
svg-preview|Sim|2.8.3
vsc-quokka-statusbar|ske|1.3.6
swdc-vscode|sof|2.5.24
slack|soz|0.0.14
es6-mocha-snippets|spo|0.2.2
uridecode|sry|0.3.5
tabnine-vscode|Tab|3.4.27
even-better-toml|tam|0.14.2
vscode-readme-pattern|tho|1.3.0
shellcheck|tim|0.16.2
pdf|tom|1.1.0
vscode-choosealicense|ult|0.6.0
samplext|Vai|1.1.3
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.0.4
vscodeintellicode|Vis|1.2.14
simple-ruby-erb|vor|0.2.1
codetour|vsl|0.0.58
gistfs|vsl|0.3.0
dingo-vscode|Wal|1.0.9
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
vscode-webhint|web|1.5.12
vscode-js-console-utils|wht|0.7.0
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
five-server|yan|0.0.32
commentbars|zfz|0.0.10
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

![](https://1drv.ms/u/s!AheVKmdqRRWvo4pVKu9h9fku9X8qmQ?e=EefONA)

**Comment by mjbvz** [comment]
Did you have javascript files open? The TS extension is also used for them

Can you also try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by killshot13** [comment]
> Did you have javascript files open? The TS extension is also used for them

Yes, I did have several javascript files open in the editor. Now I feel silly about my earlier comment about not using TypeScript.😅 

> Can you also try collecting the TS Server log from the crashed instance:

I was able to capture this data and added the logfiles to [this gist](https://gist.github.com/killshot13/65b3a6c66f33a6b91ea158565ac17fe1).

> Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out.

You are welcome to review what I was able to collect.

> > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this.

No worries, I already sanitized the logfiles with `.env` variables to remove any private details or PII.

**Comment by killshot13** [comment]
Update:

I couldn't narrow down exactly which setting was causing the issue, but this is my current configuration, and I have used it for about two weeks now, and the server never crashes anymore. So I may have just configured something in a way that was causing an internal conflict and causing the crashes.

I'm pretty confident now that I was unknowingly trying to use one of the JavaScript features without realizing the feature required TypeScript behind the scenes, and I had the corresponding TypeScript features disabled in the VSCode settings.

```JSON
{
	"javascript.preferences.useAliasesForRenames": true,
	"js/ts.implicitProjectConfig.strictFunctionTypes": false,
	"js/ts.implicitProjectConfig.strictNullChecks": false,
	"typescript.check.npmIsInstalled": true,
	"typescript.enablePromptUseWorkspaceTsdk": true,
	"typescript.format.enable": false,
	"typescript.format.insertSpaceAfterCommaDelimiter": false,
	"typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
	"typescript.format.insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false,
	"typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": false,
	"typescript.format.insertSpaceAfterSemicolonInForStatements": false,
	"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
	"typescript.format.insertSpaceBeforeAndAfterBinaryOperators": false,
	"typescript.implementationsCodeLens.enabled": true,
	"typescript.inlayHints.enumMemberValues.enabled": true,
	"typescript.inlayHints.functionLikeReturnTypes.enabled": true,
	"typescript.inlayHints.parameterNames.enabled": "literals",
	"typescript.inlayHints.parameterTypes.enabled": true,
	"typescript.inlayHints.propertyDeclarationTypes.enabled": true,
	"typescript.inlayHints.variableTypes.enabled": true,
	"typescript.locale": "en",
	"typescript.preferences.importModuleSpecifier": "relative",
	"typescript.preferences.importModuleSpecifierEnding": "index",
	"typescript.preferences.includePackageJsonAutoImports": "off",
	"typescript.preferences.jsxAttributeCompletionStyle": "braces",
	"typescript.preferences.quoteStyle": "single",
	"typescript.preferences.useAliasesForRenames": true,
	"typescript.referencesCodeLens.enabled": true,
	"typescript.referencesCodeLens.showOnAllFunctions": true,
	"typescript.suggest.completeFunctionCalls": true,
	"typescript.suggest.enabled": true,
	"typescript.suggestionActions.enabled": true,
	"typescript.surveys.enabled": false,
	"typescript.tsc.autoDetect": "off",
	"typescript.tsdk": "",
	"typescript.tsserver.enableTracing": true,
	"typescript.tsserver.experimental.enableProjectDiagnostics": false,
	"typescript.tsserver.log": "off",
	"typescript.tsserver.maxTsServerMemory": 1000,
	"typescript.tsserver.trace": "off",
	"typescript.tsserver.useSyntaxServer": "never",
	"typescript.tsserver.watchOptions": {},
	"typescript.updateImportsOnFileMove.enabled": "always",
	"typescript.validate.enable": true,
	"typescript.workspaceSymbols.scope": "currentProject"
}
```
