### ISSUE TITLE
Ctrl+p does not fire

### ISSUE THREAD

**Issue by spartanhooah** [microsoft/vscode#133206]
Issue Type: <b>Bug</b>

1. Enable keyboard shortcuts troubleshooting
2. Type the chord ctrl+p
3. Observe keydown event for ctrl, nothing for p

Other combinations using these keys (e.g. ctrl+shift+p) work fine and register with the troubleshooting / debugging output.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.75GB free)|
|Process Argv|--crash-reporter-id 768a73d7-6eb1-4c69-ae2d-9549f2483e37|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.27.2
intellij-idea-keybindings|k--|1.4.5
xml-format|mik|1.1.2
remote-wsl|ms-|0.58.2
powershell|ms-|2021.9.0
printcode|nob|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
highlight-matching-tag|vin|0.10.1
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by alexdima** [comment]
Dup of https://github.com/microsoft/vscode/issues/133208
