### ISSUE TITLE
GitBash ist nicht als Standard Terminal gesetzt

### ISSUE THREAD

**Issue by 10Bude10** [microsoft/vscode#133218]
Mit Version 1.56 gab es einige Änderung zum Terminal in VS Code. Ich habe dementsprechend alles angepasst, wie hier beschrieben:
https://dev.to/andrewriveradev/how-to-set-git-bash-as-integrated-terminal-in-vscode-2k31

Mit dem Neustart von VS Code wird allerdings beim Öffnen des Terminals nicht die GitBash angezeigt, wie konfiguriert. Stattdessen wird immer noch die Powershell von Windows verwendet. Schließe ich das Terminal (mithilfe des Mülleimer-Icons) und öffne das Terminal erneut, dann ist die GitBash gesetzt.
Ich erwarte allerdings, dass die GitBash direkt auch schon beim Start von VS Code im Terminal gesetzt ist.

**Comment by gjsjohnmurray** [comment]
Please update to 1.60.1 and then retest.
