### ISSUE TITLE
"CMake: Select a Kit" is missing in command palette

### ISSUE THREAD

**Issue by smrtos** [microsoft/vscode#133299]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Goto: https://code.visualstudio.com/docs/cpp/CMake-linux#_select-a-kit
2. Follow the MSDN steps to install CMake extension for VSC.
3. Type CMake to search for all CMake related commands in Command Palette
4. There's no "CMake: Select a Kit" in CMake VSC extension.

**Comment by aeschli** [comment]
Please file this issue against https://github.com/microsoft/vscode-cmake-tools/issues.
