### ISSUE TITLE
Any way to trigger completions upon pressing `Tab` for indentation?

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#133258]
@dbaeumer, @jrieken FYI

I’m working on a language server for Docker Compose, and I’ve hit a wall on completions. With “[dockercompose].editor.quickSuggestions.strings” set to true, rather than subsequent characters I type being used to filter the completion list, it just closes and then retriggers completions, alternating with each keystroke. I think this is because partially-completed lines are almost always treated as strings by the YAML TextMate grammar, rather than identifiers.
 
I noticed that completions triggered by a trigger character rather than the 24x7 completions seem to always have the filtering behavior working the way I want it to. The shortfall here is that when I hit <kbd>Tab</kbd> (to indent), I can’t seem to tie that keypress to a trigger character. Neither `' '` (space) nor `'\t'` worked, even though spacebar does trigger completions with `' '`. Is there a way to treat <kbd>Tab</kbd> press as a trigger character?
 
(Note: YAML cannot actually contain tabs, so we have language settings to always insert spaces, by default 2)

**Comment by jrieken** [comment]
> rather than subsequent characters I type being used to filter the completion list, it just closes and then retriggers completions, alternating with each keystroke. I think this is because partially-completed lines are almost always treated as strings by the YAML TextMate grammar, rather than identifiers.

Is asking for `Tab` completion a workaround for that problem?

**Comment by bwateratmsft** [comment]
> > rather than subsequent characters I type being used to filter the completion list, it just closes and then retriggers completions, alternating with each keystroke. I think this is because partially-completed lines are almost always treated as strings by the YAML TextMate grammar, rather than identifiers.
> 
> Is asking for `Tab` completion a workaround for that problem?

Yeah, I think that's accurate. My ideal vision would _not_ show completions upon hitting <kbd>Tab</kbd>, but rather on beginning to type one of the Compose keys from the [spec](https://docs.docker.com/compose/compose-file/compose-file-v3/) or upon <kbd>Ctrl</kbd>+<kbd>Space</kbd>. The former would use the 24x7 completions.

**Comment by jrieken** [comment]
>  it just closes and then retriggers completions, alternating with each keystroke

Are your completion results marked as incomplete?

**Comment by bwateratmsft** [comment]
No, we're returning `CompletionItem[]` instead of `CompletionList`. However, I tried returning `CompletionList` with `isIncomplete === false`, and had the same behavior.

When I tried with `isIncomplete === true`, it still wasn't filtering the list, but wouldn't close it every keystroke.

**Comment by jrieken** [comment]
You might have an issue with the range/filterText etc👇 that's my standard blurb for these kind of issues. 

A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by bwateratmsft** [comment]
Yeah, I was reaching the same conclusion but from a different direction. FWIW, we're doing this as a language server rather than programmatic features, and I guess the LSP `CompletionItem` lacks that `range` property.

I found that doing `CompletionItem.insertText` instead of `CompletionItem.textEdit`, it does more what I'm expecting. I guess that the string vs. identifier thing in the TextMate grammar was a red-herring, there was no difference in behavior from one to the other. 

In the long run we should probably use `InsertReplaceEdit` so it is more client-agnostic, but in the short run our only client is likely to be very recent versions of VSCode, so for now I'll just use `insertText`.
