### ISSUE TITLE
Please add a "Open with Visual studio code" button, in the context menu

### ISSUE THREAD

**Issue by dave90dave** [microsoft/vscode#133235]
1. right click on a directory or file
2. show a button in the context menu, that opens a directory or file with visual studio code

Visual studio already has such button, stating: "Open with Visual Studio"
It might be great if Visual studio code also got a button like that:
![image](https://user-images.githubusercontent.com/7985017/133583689-d4807903-8bed-44f3-8caf-ad6c37f50ed4.png)

If you got questions, feel free to ask,

Regards

Dave

**Comment by IllusionMH** [comment]
VS Code creates this entry, but you need to check corresponding options during installation
![image](https://user-images.githubusercontent.com/1312662/133588352-03d3f216-5c99-4a23-911b-cca6521f5dbe.png)
