### ISSUE TITLE
Using VS Code same as Eclipse packages and classes

### ISSUE THREAD

**Issue by JJ1006** [microsoft/vscode#133219]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
![Screenshot (20)](https://user-images.githubusercontent.com/74872123/133558539-4184817f-9f63-4707-9add-010a0bafbb7b.png)
![Screenshot (21)](https://user-images.githubusercontent.com/74872123/133558546-efd53587-8e93-404e-87fd-a19b7efa6e5a.png)
I am unable to use packages properly as it shows that a class is not able to get another even if it is public. While I am able to perform the same task in other IDE. I always prefer VS Code over any other IDE, but this problem is not getting solved. Please see to it...

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/redhat-developer/vscode-java/issues
Would you mind filing the issue there?

**Comment by JJ1006** [comment]
Yes sure, please redirect and solve the issue.

**Comment by aeschli** [comment]
Sorry, you'll have to refile it it otherwise the issue is under my name.

**Comment by JJ1006** [comment]
ohh...sorry, I shall refile it.
