### ISSUE TITLE
After updating the OS update in Ubuntu 20, system asked for restart, After start visual studio code file emptied all code. How to recover lost code?

### ISSUE THREAD

**Issue by hunzaigeek** [microsoft/vscode#133242]
**### System Specs:**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by Tyriar** [comment]
Not sure what happened here but backups are stored in `$HOME/.config/Code/Backups`, if you can't find them in that folder unfortunately the changes seem like they would be lost.
