### ISSUE TITLE
Omnisharp server not running

### ISSUE THREAD

**Issue by PatatasOnMe** [microsoft/vscode#133224]
Issue Type: <b>Feature Request</b>

I use C# extension. Then when i try to generate assets for build and debug, it will say a problem that Omnisharp server not running. I tried to restart omnisharp but it doesnt work

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by aeschli** [comment]
Can you file this against https://github.com/OmniSharp/omnisharp-vscode/issues?
