### ISSUE TITLE
The built in Git plugin indent error

### ISSUE THREAD

**Issue by IAseven** [microsoft/vscode#133234]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.60.1
- OS Version: windows 10 home
- Language: python

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/38178039/133582372-2b8a606f-7aa7-459e-bb03-25982536b320.png)
2.
![微信图片_20210916165558](https://user-images.githubusercontent.com/38178039/133582582-a26f79a9-6a60-4e43-b4d5-76d354180c05.png)

**Comment by IllusionMH** [comment]
Please describe actual problem.
I would guess that you expect to see line as updates in diff view - then you need to toggle diffs for whitespace changes.
In the tabs row you should see paragraph icon "Ignore Leading/Trailing Whitespace Differences"
![image](https://user-images.githubusercontent.com/1312662/133587192-af6a0a2a-f285-473b-8104-731422fb1339.png)

**Comment by IAseven** [comment]
Thank you very much. That solves my problem perfectly！
