### ISSUE TITLE
warn if project contains problems when running or debugging something

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode#133220]
most of the time, errors in a file means that it won't run. if my project has compile errors that the IDE has picked up, i'd like a warning popup like "there are problems in this project. do still want to run/debug?"

i'm not sure if this is entirely a vscode issue or rather individual plugins. i assume depending on how you run a file (eg. a debug config, an inline run button, etc.) there might be plugin-specific changes required to support it.

**Comment by roblourens** [comment]
This feature actually exists, if you have a `preLaunchTask` in your launch config, and that task has reported errors. I wouldn't hook this up to complain if there are any red squiggles in some file, because those can show up for many reasons without a direct relation to your launch.
