### ISSUE TITLE
자동완성

### ISSUE THREAD

**Issue by Matthew-Jeon** [microsoft/vscode#133228]
Issue Type: <b>Feature Request</b>

VS code를 사용하는데 자동완성이 지원이 안돼요..
어떻게 작동돼는지 알려주세요 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
I'm using VS code, but autocomplete is not supported..
Can you show me how it works?

**Comment by jrieken** [comment]
There is still in sufficient information to proceed with this issue

**Comment by CodeCrazy-ywt** [comment]
@Matthew-Jeon 
Which programming language are you using?
어떤 프로그래밍 언어를 사용하고 있습니까?

**Comment by CodeCrazy-ywt** [comment]
Yeah, there *is* English in my comment. The reason why I add Korean to my comment is to ensure this user can understand my meaning. 😂
