### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Mehmetfati** [microsoft/vscode#133250]
Issue Type: <b>Performance Issue</b>

ı use visual studio code since once month and I start learn this editör a few month ago.When entry this editör I cross lots of ıssue.One of those fatal error issue.This error about my repository don't found from vs code.I search on the NET however I can't any solution to this issue.İf you are understand please explain this solution from this issue.

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (4.70GB free)|
|Process Argv|--crash-reporter-id eea90a12-381c-4285-b942-7a8dad84a097|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	  4988	code main
    0	    11	  2664	   C:\Users\ensml\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-83bd43bc519d15e50c4272c6cf5c1479df196a4d.exe /verysilent /update="C:\Users\ensml\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-83bd43bc519d15e50c4272c6cf5c1479df196a4d.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
   24	    38	  5940	     "C:\Users\ensml\AppData\Local\Temp\is-SL4NU.tmp\CodeSetup-stable-83bd43bc519d15e50c4272c6cf5c1479df196a4d.tmp" /SL5="$202D4,78558123,828416,C:\Users\ensml\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-83bd43bc519d15e50c4272c6cf5c1479df196a4d.exe" /verysilent /update="C:\Users\ensml\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-83bd43bc519d15e50c4272c6cf5c1479df196a4d.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    23	  3356	   crashpad-handler
    1	    75	  5952	   window (Issue Reporter)
    0	   139	  7764	   window (login.html - My Project - Visual Studio Code)
    0	   110	  3460	     extensionHost
    0	    90	  8168	       "C:\Users\ensml\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\ensml\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=3460
    0	    52	  8588	       "C:\Program Files\AMD\CNext\CNext\Radeonsoftware.exe" atlogon
    0	     0	  8444	         "C:\Program Files\AMD\CNext\CNext\cncmd.exe" watch 8588
    0	    68	  4648	     searchService
    0	    13	  7128	     watcherService 
    0	    11	  7124	       console-window-host (Windows internal process)
    0	    80	  8228	   shared-process
    0	    60	  8432	     ptyHost
    2	   121	  8940	   gpu-process
    0	    39	  9144	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (login.html - My Project - Visual Studio Code)
|    Folder (My Project): 16 files
|      File types: css(3) html(3) js(2) gitignore(1) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is this problem reproducible in latest stable VS Code - 1.60.1?
You can get latest version here https://code.visualstudio.com/Download
