### ISSUE TITLE
error with 4 terminlas

### ISSUE THREAD

**Issue by Brunidas** [microsoft/vscode#133336]
I configured the color, icon and name in 4 terminals, a day later when I used the returned terminal, the name of the terminal that I left open is changed to the default name.
I use WSL on win10 with python3
now:
![image](https://user-images.githubusercontent.com/25810763/133807934-6d176f1b-0f82-476a-9cf3-7ccf39e79d51.png)
yesterday:
![image](https://user-images.githubusercontent.com/25810763/133808137-8aec2bc4-6389-4e35-8a87-cd4aca7d30e4.png)

**Comment by Brunidas** [comment]
update: I run a program in the terminal, stop it and switch to another terminal and the name of the first terminal is changed

**Comment by meganrogge** [comment]
I believe you're using an old version of VS Code bc cannot repro this. Pls create a new issue with your system's information if you can repro this in insider's.
