### ISSUE TITLE
Some UI elements stop responding to clicks

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#133371]
Issue Type: <b>Bug</b>

Sometimes some UI elements stop responding to clicks, and instead trying to click it activates the UI element behind it. I've noticed this issue for the scrollbars and editor pop-ups. I haven't been able to find any exact steps to reproduce it, but it tends to happen when I've been on a different activity or dekstop and then switch back to the activity/desktop with VSCode it. It then starts responding normally again if I click a different window and go back to the affected window. It also tends to happen when I bring up Yakuake. I've also noticed similar issues for the merge arrows and crosses in Meld, so I'm not sure exacly where the issue is.

This is on OpenSUSE Tumbleweed with KDE Plasma.

VS Code version: Code - Insiders 1.61.0-insider (23cffa27b806f9e1733e15d611ec251dcdba2c42, 2021-09-10T17:06:05.072Z)
OS version: Linux x64 5.14.0-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.70GB (3.45GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by modscleo4** [comment]
For me it only happens on Linux (tested on Arch Linux and KDE Neon)

**Comment by deepak1556** [comment]
Does the issue repro when you launch with `--disable-features=SendMouseLeaveEvents` as mentioned in https://github.com/microsoft/vscode/issues/124895

**Comment by LinAGKar** [comment]
It seems to work better with that switch
