### ISSUE TITLE
[css] propose `var()` function

### ISSUE THREAD

**Issue by emirhansisman** [microsoft/vscode#133330]
When I try to use CSS functions they don't appear in code completion, in addition to that I can't see defined variables in seperate SCSS file as well. I uninstalled all extensions and tested, nothing changed.

![vscode_intellisense_issue](https://user-images.githubusercontent.com/11505373/133796859-bea66b72-daac-4082-aa6f-ba2265dd6b25.png)

**Comment by aeschli** [comment]
Teh CSS/SCSS language support only know about symbols defined in the same file. 
#28459 is the request to follow @import to get css variables declarations.

You are correct, we should add a proposal for the `var` function.

**Comment by abderrahmaneMustapha** [comment]
can i start working on this , iwant to help

**Comment by aeschli** [comment]
@abderrahmaneMustapha Thanks for the offer, no worries, I'll fix it today
