### ISSUE TITLE
The cursor is not in the correct place when inlayHint is enabled

### ISSUE THREAD

**Issue by yasin-vibely** [microsoft/vscode#133385]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60
- OS Version: Mac OS Big Sur 11.5.2 (M1)

Steps to Reproduce:
I have activated inlayHint's in vscode and I love using it, but the situation you see in the gif really bothers me. there is "2" right in front of inlayHint and the cursor is not over it, but on the first character of inlayHint.
 <img src="https://user-images.githubusercontent.com/90043897/133896132-4184fbcb-01a7-4fe5-824f-350aaf899d1a.gif" />
 
<details>
  <summary>Gif 2</summary>
  <img src="https://user-images.githubusercontent.com/90043897/133896064-5ab50862-b40b-407f-950c-a47df24a7e0a.gif" />
</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"inlay-hints"

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/127703
