### ISSUE TITLE
 After I run yarn web, it will open localhost:8080, but it will always load, and the interface cannot be displayed.

### ISSUE THREAD

**Issue by phyLearn** [microsoft/vscode#133315]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version:Darwin x64 19.6.0

Steps to Reproduce:

1.clone
cd vscode
yarn

2.Click the Run and Debug button in vscode, select the VS Code (web) project to run successfully, but it will continue to load and cannot display the interface on the web page

Can anyone help me answer tthis question, thank you very much

**Comment by roblourens** [comment]
Are there errors in devtools?

**Comment by phyLearn** [comment]
Devtools doesn't have any errors. It just keeps loading

**Comment by bpasero** [comment]
Not sure, did you compile? I think it also needs `yarn watch` and `yarn compile-web`.
