### ISSUE TITLE
Tests are not repopulated if extension host crashes

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#133359]
Issue Type: <b>Bug</b>

1. Install an extension that provides a test controller
2. Open a folder that contains tests
3. Open the Test Explorer view
4. `Restart Extension Host`
5. Tests are not repopulated

I tested this from the extension host, launched with `--disable-extensions`. The only running extension (except built in ones) is my local version of the Go extension.

Related to #128341, golang/vscode-go#1771

Normally, after a test controller is registered (during activation), the test controller's resolve handler is called with null/undefined, which resolves all top-level items. If the extension host is restarted, this does not happen.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (49.43GB free)|
|Process Argv|--crash-reporter-id 8d76c88c-bb0c-4275-afc9-bb8b9f014c6a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by firelizzard18** [comment]
Also, if I do a forced refresh/resolve, which definitely creates test items, I still get nothing.

**Comment by connor4312** [comment]
This sounds like a duplicate of https://github.com/microsoft/vscode/issues/132601, does it reproduce on Insiders?

**Comment by firelizzard18** [comment]
@connor4312 It does not reproduce on Insiders. Everything appears to work.
