### ISSUE TITLE
Pretty Print debug watch list

### ISSUE THREAD

**Issue by artoodeeto** [microsoft/vscode#133352]
Hello, I would like to add a way to pretty-print the watch list from the debugger instead of showing it in one line. 

![Screen Shot 2021-09-17 at 3 57 13 PM](https://user-images.githubusercontent.com/19770382/133862430-a2f49660-8997-46f1-818a-da0ed25802bc.png)

I'm not sure if this feature is available but I've been googling and I couldn't find relevant answers online. I also tried searching it on the issues and no relevant answer. I might be missing something here. sorry for the ignorance. Thank you!

**Comment by roblourens** [comment]
It's a string, and since we don't know how to interpret it, we can't really do any pretty printing. I'd recommend watching a variable that has this value parsed into an object, or copying the string into a file and pretty printing it manually.
