### ISSUE TITLE
findFiles-API returns ignored files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133334]
* anycode [uses](https://github.com/microsoft/vscode-anycode/blob/2fba12e1c69b0edaddab2f6f1948921873e1fb00/client/src/main.ts#L69) the `findFiles`-API
* I am using default excludes, expressed via the `undefined` as 2nd parameter
* :bug: I do get results from the `node_modules` folder

You can see this in action when installing anycode and opening the VS Code folder. Activate the extension (e.g cmd+t) and see that a too large files was ignored

<img width="611" alt="Screen Shot 2021-09-17 at 17 21 12" src="https://user-images.githubusercontent.com/1794099/133807829-0b40e23f-1f03-4c3d-8741-d80365546e7e.png">

**Comment by roblourens** [comment]
findFiles has always applied the default files.exclude but not search.exclude. There is no easy way to apply search.exclude (https://github.com/microsoft/vscode/issues/48674) but we can't do it by default (https://github.com/microsoft/vscode/issues/68056)

**Comment by jrieken** [comment]
> There is no easy way to apply search.exclude 

What? Just extend to API to support both excludes. This is easy right?

**Comment by roblourens** [comment]
I mean there is no easy way that exists today without changing the API
