### ISSUE TITLE
Unused screen estate when I am using vscode along with another application in split mode.

### ISSUE THREAD

**Issue by jaideeprana** [microsoft/vscode#133319]
I prefer working in split screen for most of my apps and I love vscode's center layout feature.

However when I have another app opened there's unused space left in vscode which can be utilised.

Here's an image that describes the issue pretty well. Let me in case there's any further clarification needed from my end.
![unused space](https://user-images.githubusercontent.com/3875065/133776462-8ba8b7a1-28a4-438b-b84c-06b486a48aea.jpg)

**Comment by JacksonKearl** [comment]
You can adjust the width of the centered column by dragging.. not sure what you're looking for here?

**Comment by jaideeprana** [comment]
I am looking for a responsive behaviour.

For example when I just a have a single window, then I want screen to look something like this:

<img width="1792" alt="B7y04" src="https://user-images.githubusercontent.com/3875065/134699285-3c204b31-4b72-4b5e-b3e6-fafce26cb029.png">

And then when I have another app opened let's say my browser window then I want it to look something like this:

<img width="1792" alt="QvLCx" src="https://user-images.githubusercontent.com/3875065/134699512-3b999743-9174-4d48-a055-ed9fc49011c2.png">

Currently like you mentioned I can achieve it by dragging but then when I close the other application I again have to adjust the width.

Whoever I want it to utilise the entire screen estate without manual intervention.

VScode does that only when we split a file in VScode as depicted in the following image. However I want the same functionality when I have a single file and another app opened in split layout.

<img width="1792" alt="hTIHy" src="https://user-images.githubusercontent.com/3875065/134699952-433970e0-eb59-4f34-b2f8-c16dce96e3f8.png">

Let me know if you still need more info. I will create a Gif in case it's still not clear.

**Comment by JacksonKearl** [comment]
![recording (35)](https://user-images.githubusercontent.com/8586769/134725880-ea88d9ac-2717-4b61-9043-d063c3cfdef3.gif)
I see this behaviour on screen size changes, which to me seems like the desired behaviour you describe.
