### ISSUE TITLE
SVG not rendering in Markdown code hover tooltip

### ISSUE THREAD

**Issue by kriswuollett** [microsoft/vscode#133389]
Issue Type: <b>Bug</b>

Add a code comment like the following on an identifier:

```
/**
   * Preview: ![red 50](https://mui.com/static/colors-preview/red-50-24x24.svg)
   */
```

Hover over the identifer, and the tooltip will show a broken image icon for the SVG. PNG works fine.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.0-1045-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (15.30GB free)|
|Process Argv|--crash-reporter-id 8067519b-e432-4f58-bfd4-020219e81bca|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dragon-remote|
|OS|Linux x64 5.10.0-1045-oem|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (48 x 1201)|
|Memory (System)|125.53GB (118.79GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
mustache|daw|1.1.1
flatbuffers|gab|0.1.0
jq-syntax-highlighting|jq-|0.0.2
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vscode-pbtxt|the|0.0.4
vscode-tailwindcss|bra|0.6.14
vscode-svgviewer|css|2.0.0
shell-format|fox|7.1.0
vscode-docker|ms-|1.16.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by kriswuollett** [comment]
I've seen some issues filed for the same thing in the past like #68033, but did not find any currently open ones to follow for notifications or comment.

**Comment by mjbvz** [comment]
This is by design. For security reasons, we block remote svg images in markdown strings
