### ISSUE TITLE
can't run a simple c++ loop program

### ISSUE THREAD

**Issue by shubham032** [microsoft/vscode#133337]
Issue Type: <b>Bug</b>

i keep getting this error

PS C:\Users\goswa\OneDrive\Desktop\VSC\C++> cd "c:\Users\goswa\OneDrive\Desktop\VSC\C++\" ; if ($?) { g++ for loop.cpp -o for loop } ; if ($?) { .\for loop }
g++.exe: error: for: No such file or directory
g++.exe: error: loop.cpp: No such file or directory
g++.exe: error: loop: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (1.62GB free)|
|Process Argv|C:\\Users\\goswa\\OneDrive\\Desktop\\VSC\\C++\\for loop.cpp --crash-reporter-id 11faf2ab-55bf-494e-a6e4-b12773583659|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.5
c-cpp-runner|fra|1.3.0
r|Iku|2.2.0
batch-rename-extension|Jan|0.0.4
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
sublime-keybindings|ms-|4.0.10
java|red|0.82.0
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30367819
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your setup, or possibly the C++ extension if you are using that. I'm not sure that's a valid powershell command
