### ISSUE TITLE
Create a launch.json file doesn't do anything

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#133327]
Issue Type: <b>Bug</b>

When launch.json is empty (or invalid?), clicking "Create a launch.json file" doesn't do anything. 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
cpptools|ms-|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by roblourens** [comment]
Hm, I'm not sure whether we should overwrite a user's launch.json when they created it on their own and may have some other content in it. But we should show an error or something. So you created a launch.json manually before trying to have vscode create it?

**Comment by roblourens** [comment]
If exists but is invalid, we just open it. We aren't trying to validate it at this point. I will also just open it if it is empty. I don't want to try to be smarter than that.
