### ISSUE TITLE
[FR] Filter Test UI with a negated tag

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#133350]
Splitting this out from https://github.com/microsoft/vscode/issues/129456#issuecomment-921280280

In the Test UI you can filter by text or exclude text using `!` and filter by a `@tag`. It would be nice if we could also negate tags in the filter like `!@tag` to exclude a specific tag.

**Comment by connor4312** [comment]
Starting point, this is where tag filtering happens:
