### ISSUE TITLE
Centered layout should be preserved per user, not per workspace

### ISSUE THREAD

**Issue by Mo-Shakib** [microsoft/vscode#133300]
Whenever I close a project or folder the centered layout get lost, I need re-enable it manually. Please add a feature which will keep the centered layout view setting saved until I change it by myself.

**Comment by gjsjohnmurray** [comment]
Does `"zenMode.restore": true` achieve what you want?

**Comment by Mo-Shakib** [comment]
no

**Comment by gjsjohnmurray** [comment]
By "the centred layout" do you mean [Zen Mode](https://code.visualstudio.com/docs/getstarted/userinterface#_zen-mode)?

How are you closing your project or folder?

What platform are you running VS Code on? And what version of VS Code?

**Comment by gjsjohnmurray** [comment]
Or maybe you are using the `View: Toggle Centered Layout` command? For me (1.60.1 on Windows) if I toggle this mode on, then close VS Code, then reopen the same folder it displays with [centered editor layout](https://code.visualstudio.com/docs/getstarted/userinterface#_centered-editor-layout) still on.

**Comment by sbatten** [comment]
Centered Layout is currently remembered per-workspace. So, if you open a new folder/workspace, it will not be centered. The request here is to allow this to be stored at the global-level.

**Comment by sbatten** [comment]
@isidorn any history of issues like this one?

**Comment by isidorn** [comment]
There have not been issues like this previously. Though I think it is a fair feature request towards the centered mode, thus forwarding to @JacksonKearl since he now owns this.
I personally think we should not do this, but leaving it open to gather more feedback makes sense.
