### ISSUE TITLE
Add "Copy Name" to right-click menu for files in the explorer

### ISSUE THREAD

**Issue by philip-gai** [microsoft/vscode#133364]
When right-clicking on a file in the explorer, it would be great if you could quickly copy the file name from the dropdown menu.

<img width="459" alt="vs-code-copy-name" src="https://user-images.githubusercontent.com/17363579/133871463-30531982-258a-4d53-b4c8-a054d7c54303.png">

1. I know there is the option of hitting `Enter` on a file to highlight the name minus extension but you have to select the file (changing the open editor) and you risk accidentally changing the name. It also only highlights the name (not the extension) so it's some extra effort to `Ctrl+A` or whatever other method you want to use to get the extension highlighted as well before copying it.
2. Not sure if "Copy Name" should copy the full name (name + extension). But that's a UX decision I'm not qualified to make 😄

**Comment by JacksonKearl** [comment]
An extension can implement this by contributing to the `explorer/context` menu, some info here https://code.visualstudio.com/api/references/contribution-points#contributes.menus.

**Comment by philip-gai** [comment]
🥲

**Comment by wasi-master** [comment]
You can press <kbd>F2</kbd> to go into the rename stage then press <kbd>Ctrl+C</kbd> to copy the name since it will be automatically selected when renaming, you can also press <kbd>Ctrl+A</kbd> to select the entire text in case the file extension isn't automatically selected
