### ISSUE TITLE
Redesign the Visual Studio Code UI to match Windows 11's design language

### ISSUE THREAD

**Issue by 97I8TOE47K** [microsoft/vscode#133372]

**Comment by aeschli** [comment]
Do you mean Visual Studio or Visual Studio Code?
Can you given an example of what should change? Maybe a screenshot to illustrate>

**Comment by 97I8TOE47K** [comment]
> Do you mean Visual Studio or Visual Studio Code?
> Can you given an example of what should change? Maybe a screenshot to illustrate?

I mean Visual Studio Code, sorry. What I want is a UI that matches the design principles that Windows 11 uses like acrylic menus and toolbars and rounded corners. I hope you get my point

**Comment by 97I8TOE47K** [comment]
> > Do you mean Visual Studio or Visual Studio Code?
> > Can you given an example of what should change? Maybe a screenshot to illustrate?
> 
> I mean Visual Studio Code, sorry. What I want is a UI that matches the design principles that Windows 11 uses like acrylic menus and toolbars and rounded corners. I hope you get my point.

Visual Studio Code is already one of the best looking IDEs on the market. If the design principles of Windows 11 are incorporated into it, then it will be the cherry on top of the already unbeatable IDE which is much better than its competitors like any JetBrains IDE.

**Comment by 97I8TOE47K** [comment]
> Do you mean Visual Studio or Visual Studio Code?
> Can you given an example of what should change? Maybe a screenshot to illustrate?

[Here they are, as per Microsoft, yes the devs.](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/design-principles)

**Comment by misolori** [comment]
Thanks for the feedback. Please see #115641 where we are tracking a similar request. Will be closing this one as a duplicate.
