### ISSUE TITLE
A language status item created with scheme and pattern never show up.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#133331]
In ESLint the status basically depends on individual files, not a language id (for example a JS file A might be validated a JS file B not at all).

I therefore create a language status item from a URI in the following form

```
				item = Languages.createLanguageStatusItem('eslint' + idCounter, [
					{ scheme: uri.scheme, pattern: uri.fsPath }
				]);

```

However such a status item never shows up. 

It does show up if I remove the `scheme` property.

**Comment by jrieken** [comment]
> It does show up if I remove the scheme property.

Is this vscode-remote or anything like that? I believe the selector needs to go through uri transformation and currently doesn't...

**Comment by jrieken** [comment]
also seeing `'eslint' + idCounter` - rethinking about what we discussed - you should be updating the selector-property instead of creating/disposing items. The id will be used to store the show/hide state and with dynamic ids this is basically off

**Comment by dbaeumer** [comment]
Not sure I understand that. It could easily be that the user has two JS files open one has ESLint validation, one has not. In my current design I create a specific ESLint language status for open files that are validated by ESLint. This has the advantage that I don't need to track editor switching. It has also the advantage that the workbench can decide to show the status independent of the active editor (e.g. for example as an overlay in the explorer). 

The id is not really dynamic. I could have used uri.toString() as well. It says stable as long as a file is open.

Since the API provides a selector I would like to avoid tracking any UI state to correctly update the status item. Is this not the intended design?

**Comment by jrieken** [comment]
The id property only exists so that we can identify a status item across sessions. That is used for the hide feature - we know by id if an item goes into the status bar or into the hover (default). I think its undesirable if I would have to hide/show various eslint entries just because I have been switching between editors. 

> I would like to avoid tracking any UI state to correctly update the status item.

I don't think you need to track the UI state but you will be tracking something, right? How else do you know the uri to target? If you know that you can update a document selector list with that uri

**Comment by dbaeumer** [comment]
OK. I see. I track validated files (which the eslint server tells me). What I can do is to update the selector with the list of tracked files. Never thought about that since I usually can't update selectors post fact for registered language features. Or can I? If I could it would simplify other ESLint code :-)

**Comment by dbaeumer** [comment]
Looked into it but that approach even requires me to track the UI state since different files can have a different status. For example A.js could be OK where as B.js has a config problem. So I need to update the severity of the language status item based on the editor that has focus. I was hoping that I can avoid this with the new status item.

**Comment by jrieken** [comment]
Assuming that you have a single status bar item today I would recommend to keep the tracking logic and to simply update/append to the selector. That should get you going and then we reconsider

**Comment by dbaeumer** [comment]
This is what I do now.

**Comment by dbaeumer** [comment]
Implemented it. How stable is the new API?

**Comment by jrieken** [comment]
It's proposed but relatively stable

**Comment by dbaeumer** [comment]
Thanks.
