### ISSUE TITLE
Configure Workspace Configure Workspace 'extension'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#13330]
Provide support to configure a workspace for:
- node
- docker

**Comment by egamma** [comment]
Talked to @chrisdias and given all the other improvements for JS (automatic type acquisition, no need for jsconfig.json) there isn't much left for this item.

I defer to @kieferrm to close/remove this item from the plan.

**Comment by kieferrm** [comment]
No work was needed here.
