### ISSUE TITLE
[Bug] `workbench.action.terminal.joinInstance` hides the terminals if they're already joined

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#133361]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.61.0-insider
- OS Version: Windows 10

Steps to Reproduce:

![STG 2021-09-18 10_59_02](https://user-images.githubusercontent.com/28700378/133870250-3d14e340-a47e-4f61-ac22-291011489dc4.gif)

Expected behavior:

If the selected terminals are already joined, `workbench.action.terminal.joinInstance` should do nothing.

**Comment by IanMatthewHuff** [comment]
@meganrogge I'm not a big user of the integrated terminal so maybe this is just a silly misunderstanding on my part. But I was looking to help verify this, and following the gif of the steps I don't actually see the terminals join in a group after selecting two terminal tabs and using the join command. 

![TerminalJoin](https://user-images.githubusercontent.com/812783/135541612-1d8b8124-eb70-4dd2-a95c-fe0a4a94b508.gif)

Something I'm doing wrong here?
