### ISSUE TITLE
$PATH clobbered on macOS

### ISSUE THREAD

**Issue by winterqt** [microsoft/vscode#133357]
Issue Type: <b>Bug</b>

`$PATH` before launching Code with `code .`:
```
/nix/store/yr7gd6sl44mw25wb44y4pi3cy4xj3wmz-rustc-1.54.0/bin [...] /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

`$PATH` after launching Code (persists in integrated terminal and extension host):
```
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /nix/store/yr7gd6sl44mw25wb44y4pi3cy4xj3wmz-rustc-1.54.0/bin [...]
```

It looks like Code is overriding the environment using macOS' `path_helper`.

If I'm understanding correctly, after going through similar issues (like #56125), #108804 should fix this.
@bpasero My apologies in advance for the ping, but is this a regression, or am I misunderstanding #108804?

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:13.580Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by joaomoreno** [comment]
You can disable this behavior with `--force-disable-user-env`, does that help?

**Comment by winterqt** [comment]
> You can disable this behavior with `--force-disable-user-env`, does that help?

@joaomoreno `$PATH` is still reordered even if launching VS Code with this flag. (i.e. `code --force-disable-user-env .`)

**Comment by joaomoreno** [comment]
Strange, maybe @bpasero knows more?

**Comment by bpasero** [comment]
Maybe run with `--verbose` and see if there is something printed containing the words `resolveShellEnv`

**Comment by winterqt** [comment]
@bpasero It seems that this behavior should be disabled if VS Code is launched from the CLI anyways, strange...

The integrated terminal part of this is probably due to my shells `path_helper` implementation (so unrelated), but I want to make sure the extension host is working as expected.

To aid in debugging, do you know of an easy way to read environment variables of the extension host?

**Comment by bpasero** [comment]
Not really. But you could install your own little extension that does `console.log(process.env)`. Should be fairly easy to get going via `yo code` and `vsce` for local packaging.

**Comment by winterqt** [comment]
Everything looks good, this turned out to be a different issue at play. Thanks for helping out, @bpasero.
