### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Punith777** [microsoft/vscode#133322]
Issue Type: <b>Bug</b>

When I try to run my Python code, It is not compiling and showing the error SyntaxError: invalid syntax in the Terminal,
If I Debug and Run it, it is running well and even I use ctrl+f5 shortcut key the code is running well. I hope the Visual Studio Code will soon removes this bug. Hoping a replay at punithkumarc777@gmail.com. 
                                                 Regards,
                                                 Punith Kumar.C

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (2.53GB free)|
|Process Argv|C:\\Users\\PUNITH KUMAR C\\Downloads\\Python Course with Notes\\7. Chapter 7\\My chapter 7 --crash-reporter-id f619ef09-fc44-489b-84f6-cd3a5231982f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by Punith777** [comment]
Issue Type: <b>Bug</b>

When I try to run my Python code, It is not compiling and showing the error SyntaxError: invalid syntax in the Terminal,
If I Debug and Run it, it is running well and even I use ctrl+f5 shortcut key the code is running well. I hope the Visual Studio Code will soon removes this bug. Hoping a replay at punithkumarc777@gmail.com. 
                                                 Regards,
                                                 Punith Kumar.C


VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (2.53GB free)|
|Process Argv|C:\\Users\\PUNITH KUMAR C\\Downloads\\Python Course with Notes\\7. Chapter 7\\My chapter 7 --crash-reporter-id f619ef09-fc44-489b-84f6-cd3a5231982f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224cf:30358040
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by joeljose350** [comment]
Can you paste the code and the error message here?

**Comment by Punith777** [comment]
Hi there, I'm glad that I received your email. I'm having the trouble with
running the program in Visual Studio Code, the bug is that when I try to
run my python code the Terminal is continuously giving the SyntaxError :
invalid syntax. When I tried the shortcut key ctrl+f5 key the program is
executing the code perfectly.

**Comment by Punith777** [comment]
I hope Visual Studio Code team will fix this issue as soon as possible.
Please leave a replay at ***@***.*** When you fix this
error.
Regards, Punith Kumar.C

**Comment by roblourens** [comment]
Hi, it sounds like there is probably an issue with your code. That error is coming from Python.

**Comment by Punith777** [comment]
No bro, that's not the problem in code.
Please replay me bro.

**Comment by Punith777** [comment]
Please replay me
