### ISSUE TITLE
git "Discard Changes" confirmation dialog files count wrong

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#133387]
Issue Type: <b>Bug</b>

The source control pane allows discarding changes by right-clicking on *selected* items and then choosing "Discard Changes".

If _items_ are selected in a tree view, and part of the selection is a directory, then the confirmation dialog shows a wrong (impossible) number of files to be discarded.

Steps:
* open vscode in a git directory, with no current changes
* `mkdir mydir`
* `touch 1`
* `touch mydir\2`
* switch to the source control pane, note the changes
* make sure that "View as Tree" mode is active
* select all three _items_ in the treev view, comprising of _1 directory_ and _2 files_
* right-click onto select items -> "Discard Changes"

//exp: Confirmation - "This will DELETE 2 untracked files"
//act: Confirmation - "This will DELETE 3 untracked files"

IOW, the directory is counted as a file.

This is rather irritating if one expects to discard a very well-known number of files, only to discover that the UI confirmation dialog is off.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.13.15-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.31GB (20.85GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 80e0ae97-0bc4-4a76-8337-f435f2ec1554|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|/usr/share/xsessions/plasmax11|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by shoffmeister** [comment]
Just noticed a simpler scenario: Just use tree view mode, have 1 file in the directory, and directly discard the directory.

The confirmation dialog will ask for confirmation to delete 2 files, while there is 1 file only (the directory will not be touched by the git revert)

**Comment by shoffmeister** [comment]
Funny enough - clicking on the "Discard All Changes" icon reports the correct number of files (2 files in the scenario above).

**Comment by lszomoru** [comment]
@joaomoreno, I see multiple options for implementing a fix for this:
1) Deduplicate the resources in the `git.clean` command
2) Deduplicate the resources in core before the are passed to the `git.clean` command as args

**Comment by joaomoreno** [comment]
1 sounds great!
