### ISSUE TITLE
open setting config with split view, then use <kbd>ctrl+k</kbd><kbd>ctrl+shift+\\</kbd>and the split view is closed into one, but trigger that again, we couldn't recover the split setting view,

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#133312]
open setting config with split view, then use <kbd>ctrl+k</kbd><kbd>ctrl+shift+\\</kbd>and the split view is closed into one, but trigger that again, we couldn't recover the split setting view,

_Originally posted by @heartacker in https://github.com/microsoft/vscode/issues/36700#issuecomment-919235698_

**Comment by roblourens** [comment]
If you close and reopen the settings editor, that works to fix it. I think this is basically by design. It's a little different since we have two different files in the tabs here.
