### ISSUE TITLE
Bir Bölgeyi türkçeye çevirmeyi unutmuşunuz 

### ISSUE THREAD

**Issue by kuroibaratr** [microsoft/vscode#133374]
İhtiyaç duyulan veri gönderilemeyecek kadar büyük olduğu için, bu veriyi panonuza ko
Issue Type: <b>Bug</b>

Gezgin bölümünde open folder yazıyor bunun tr paketinde dosya seç yada dosya aç olması gerekiyor 
kuroibaratr@gmail.com
mailden ulaşabilirsiniz ,isterseniz ss atarım
iyi günler

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.07GB free)|
|Process Argv|C:\\Users\\Yiğit\\Documents\\brawlhallatrguard1-main\\index.js --crash-reporter-id cef935a0-b168-4df1-8c91-b5b56e9be354 --crash-reporter-id cef935a0-b168-4df1-8c91-b5b56e9be354|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-tr|MS-|1.60.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

pyaladık. Lütfen yapıştırın.

**Comment by kuroibaratr** [comment]
[image: Ekran Alıntısı.PNG]

I wanted to say ;
I'm using visual studio code and there are untranslated parts in the
tr language pack. As a programmer, I fixed this part from the language
file myself, but another user may not be able to fix it. here's
exactly like the screenshot I posted below, the sections that say "You
have not yet opened a folder" and "Open Folder" should be "Henüz bir
klasör açmadınız." and "Dosya Seç/Klasör Seç", respectively.
my aim is just to support you :) have a good and healthy day :)

**Comment by TylerLeonhardt** [comment]
@kuroibaratr unfortunately, the screenshot is not showing up. Screenshots attached to emails do show up on the website. Upload the screenshot on the website please?

**Comment by v-mholloway** [comment]
@kuroibaratr can you fill out this template so we can target the correct strings and please provide the screen shot?...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)
