### ISSUE TITLE
Object as default function parameter inlay hints bug

### ISSUE THREAD

**Issue by Adamih** [microsoft/vscode#133382]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: 
Microsoft Windows 10 Home 10.0.19043 Build 19043
WSL2 Ubuntu Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Enable TypeScript › Inlay Hints › Parameter Types in settings. 
2. Write this function in a .ts file:

```javascript
function test({ test } = { test: 3 }: { test: number }) { }
```

This code will cause a ts error and weird inlay hint behaviour. Probably create similar weirdness in js files.

**Comment by Adamih** [comment]
![image](https://user-images.githubusercontent.com/14089184/133895447-022d3565-8bed-4f00-9a2a-edd7084f8655.png)

**Comment by mjbvz** [comment]
That code sample isn't valid; it should be written with the type before the default value:

```ts
function test({ test }: { test: number } = { test: 3 }) { }
```
