### ISSUE TITLE
Plotly.js latest version

### ISSUE THREAD

**Issue by guyko81** [microsoft/vscode#133386]
It seems that plotly is not up to date in VSCode, because when I use add_vline it only grows between 0 and 1 on the y axis in VSCode Ipython Notebook interactive view. 
Running the same code in the browser, Jupyter generates the lines in full length.

**Comment by IllusionMH** [comment]
/extPython

This repo doesn't contain references to plotly, most likely you should fill this request in Python extension repo (and please follow issue templates)
