### ISSUE TITLE
Editors change event: revisit only firing `EDITOR_ACTIVE` only for active group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133306]
Referring to this event:

https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/services/editor/browser/editorService.ts#L145-L145

It will only fire if the group is active:

https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/services/editor/browser/editorService.ts#L126-L128

Isn't that inconsistent? For example, the `onDidVisibleEditorsChange` will fire in that case:

https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/services/editor/browser/editorService.ts#L155-L155

I think we should probably always fire `onDidEditorsChange` for the `EDITOR_ACTIVE` event, even if the group is not active.

**Comment by lramos15** [comment]
To me it doesn't matter so I'm ok with either. I think the mentality was that it aligns with when we fire the active editor changing here 
https://github.com/microsoft/vscode/blob/cc4ace196cf5482f801b2ac06128bace2906f874/src/vs/workbench/services/editor/browser/editorService.ts#L144-L145

**Comment by bpasero** [comment]
Yeah but that event is really for "the active editor in the active group", while the other is for any change across all groups.
