### ISSUE TITLE
Images in walkthrough are broken on Codespaces

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#133309]
#### Steps to Reproduce:

1. Create a Codespace with a Java repo.
2. Open Walkthrough ... 
3. Choose "Dive into Java Development ......"
4. You see broken images

![image](https://user-images.githubusercontent.com/2351748/133737201-61198a29-f9de-4245-9bf2-0929927bdcfd.png)

#### I checked, all the images are well existing on filesystem.
![image](https://user-images.githubusercontent.com/2351748/133737239-20241fbb-3452-4f91-90a2-fcefacb9e793.png)

#### Same for Python extensions:
![image](https://user-images.githubusercontent.com/2351748/133737268-69664614-b591-4ece-8285-0cab48d6d79a.png)
![image](https://user-images.githubusercontent.com/2351748/133737291-ae9c6232-b95a-4ab3-a137-e769f71f7aac.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/135034872-95f245df-c7aa-4ab4-b1fa-ee46299aaff3.png)
I am not able to reproduce this at the moment. Can you confirm you're still seeing this?

**Comment by Eskibear** [comment]
It's working well now.

Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:58:31.782Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Edg/94.0.992.31

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/135679455-d851cc5a-7599-49db-94f9-323aac4e3dd1.png)
![image](https://user-images.githubusercontent.com/812783/135679834-fb0e093f-8023-4569-b9f6-443519846239.png)
Verified, looked good with a couple of python ones.
