### ISSUE TITLE
Need a way to test in-product release notes with insiders and vnext content 

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13347]
Right now we can only view the previous version release notes following the steps in test plan https://github.com/Microsoft/vscode/issues/12520 since the vnext release notes aren't available on code.visualstudio.com/raw.
While the Markdown preview of the vnext release notes is close to the actual release notes display, it is not exactly the same (for example, OS specific key board short cuts are resolved) and the two displays may diverge more in the future.
Can we point insiders to vscode-vnext.azurewebsites.net/raw? I'm not sure if non-Microsoft accounts will have access but for our own testing this should work.

**Comment by gregvanl** [comment]
Doesn't look like vscode-vnext.azurewebsites.net will work due to the two factor authentication. Going against the vscode-docs vnext branch in GitHub is also not great since it won't have the *.md preprocessing to remove the header and would require a separate product code path for insiders.
Probably the easiest and most accurate testing would be to periodically do a manual commit of the vnext release notes and images to vscode-website views/raw and then publish the websites so the vnext release notes are available on code.visualstudio.com/views/raw. No user would actually see these *.md files on the websites.
If you agree with the last approach, reassign this issue to me and I'll make it part of the end game release process.

**Comment by joaomoreno** [comment]
Was bringing in Release Notes into the product worth all this amount of work? IMO the website solution was working for us quite well.

**Comment by gregvanl** [comment]
Agreed. Not my idea nor was I pushing for it. I'm just trying to make it work reasonably well since others feel strongly about the in-product display.

**Comment by joaomoreno** [comment]
At best, we can maybe provide a global command to open a specific version of the release notes, but you still need to have them published to the website. It would just save you the hassle of editing the `package.json`.

cc @egamma @chrisdias

**Comment by gregvanl** [comment]
@joaomoreno I don't think we need to mess with package.json. For insiders (ex 1.7), we can periodically publish v1_7.md on code.visualstudio.com/raw so that an insiders build will display the correct release notes (Help > Release Notes).  Not ideal, but pretty low overhead to publish the vnext release notes and it will then use the same code path as the final product.
It would have been nice to have done this last week, as yesterday we had to work around several issues with in-product release notes rendering that we didn't detect with the regular Markdown preview (unassigned keyboard shortcuts handled differently, h3 links didn't work if punctuation in the title).

**Comment by gregvanl** [comment]
Published a snap shot of v1_7.md (and images) to code.visualstudio.com. Insiders now shows in-product release notes rather than going out to the insiders release notes page. 
@joaomoreno We no longer send insiders to https://github.com/Microsoft/vscode/wiki/Insiders-Release-Notes through https://go.microsoft.com/fwlink/?LinkId=724002. I think that's fine and that wiki page was just to have somewhere for insiders to land. If we want to put some of the wiki links in the prerelease version of the release notes we certainly could.
