### ISSUE TITLE
Dragging settings tab to another editor group clears search query

### ISSUE THREAD

**Issue by zsalzbank** [microsoft/vscode#133444]
Issue Type: <b>Bug</b>

1. Open the settings UI.
2. Search for a setting (e.g. "inlay").
3. Drag the settings tab to a new editor group. Note that the search you entered previously has been cleared.

https://user-images.githubusercontent.com/939977/134008969-5fde2f60-f252-4a38-a3a0-c91a774a402c.mov

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 726080a9-504a-4ce7-82e2-a7fc09b1cb07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-nginx-conf|ahm|0.1.3
reorder-lines-by-length|ara|1.0.2
docs-view|bie|0.0.9
pgformatter|bra|1.17.0
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
vscode-diff|fab|1.4.2
shell-format|fox|7.1.0
go|gol|0.27.2
postgresql|JPT|0.0.2
rainbow-csv|mec|1.9.1
render-crlf|med|1.5.21
template-string-converter|meg|0.5.3
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
debugger-for-chrome|msj|4.13.0
nbsp-vscode|pos|0.0.1
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
final-newline|sam|0.3.2
vscode-hexdump|sle|1.8.1
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by rzhao271** [comment]
A function called `restoreCachedState` in `settingsEditor2.ts` is being called after the drop, which is correct.
But, the function `saveState` in the same file name isn't being called when the user does step 3 above.
