### ISSUE TITLE
Multiple search tabs in bottom panel

### ISSUE THREAD

**Issue by eclipse-like** [microsoft/vscode#133437]
Hello,
I have worked a lot of years with the Eclipse-based editors, and now at the firm we work for we have to evaluate the VS Code in order to make a switch.
After a few hours of using the VS Code (version 1.59.0) I have noticed what is for me a major step back compared to the Eclipse: the search function.
Eclipse has a very well organized visual interface
- the list of files in the left part
- the opened code files in the middle of the screen
- the search tabs in the bottom panel.
I have managed to put in VS code the search tab in the bottom panel:
![image](https://user-images.githubusercontent.com/91057769/133985215-d20036f3-58e6-4040-9932-22c83e99297d.png)
But if I try to open a new one, it will open in the main window, in between the code files:
![image](https://user-images.githubusercontent.com/91057769/133985418-857d9d40-ab10-420a-a48b-0a453801a037.png)
Also, for the search in the bottom panel I can expand/contract the files in which the search item was found. In the additional search windows opened afterwards I do not have this option.
![image](https://user-images.githubusercontent.com/91057769/133987836-3044e322-ad43-4a82-af59-1b27e1bb0c16.png)
vs
![image](https://user-images.githubusercontent.com/91057769/133987935-ebb9d11b-3699-436c-ad19-c98f48181ad4.png)

I do not like this mix: code and search tabs in the same space. Code should be separate.
In Eclipse you can either choose to have one search window, or you can pin them and  open several search tabs in the bottom panel:
![image](https://user-images.githubusercontent.com/91057769/133986497-4cf2720f-e373-4ff1-a533-e50bd3778c57.png)
They are all the same as features (for all you can expand/contract the file names)
It is much easier to navigate this way.  Also now in VS code the bottom tab is a waste of space. The code area is overcrowded with the search part, and the bottom tab is unused.
Is there any way to have this also in VS code?

**Comment by roblourens** [comment]
No, we don't support multiple search tabs like that. You've found our search editors, and you can have multiple of those if you want. You can also put them in a separate editor group if you don't want them mixed with your code files.
