### ISSUE TITLE
Visual Studio Code settings.json

### ISSUE THREAD

**Issue by Edward34William** [microsoft/vscode#133490]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. l think I remove the code.
2. Please help me as soon as possible, thanks.
![Screen Shot 2021-09-20 at 11 28 42 PM](https://user-images.githubusercontent.com/57689527/134107203-27c98562-8140-4eeb-b13c-7cf1f228ede2.png)

**Comment by Edward34William** [comment]
![Screen Shot 2021-09-20 at 11 29 39 PM](https://user-images.githubusercontent.com/57689527/134107326-1e39a4c2-622c-4863-883a-ad5195ac7832.png)

**Comment by Edward34William** [comment]
I believe that 116 line= " java.help.firstView": "gettingStarted": {},
 ull,
}
last one I have a problem.

**Comment by ArturoDent** [comment]
Look at your line 113.  A trailing `n` is bad. Fix that first.

**Comment by Edward34William** [comment]
Please send it to me correct one

**Comment by Edward34William** [comment]
> Look at your line 113. A trailing `n` is bad. Fix that first.

Should I remove 'n'? Let me know. Also, l believe 116 lines should I write something "gettingStarted": {},

**Comment by gjsjohnmurray** [comment]
Have you been randomly editing your settings.json file?

I suggest you delete lines 113, 114, 116 and 117.
