### ISSUE TITLE
Terminal shows black lines after restart

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133496]
![image](https://user-images.githubusercontent.com/900690/134114858-a2593708-32d1-42af-8443-f44da4722965.png)

![image](https://user-images.githubusercontent.com/900690/134114876-72e6d0c3-b2db-4c4e-b2dd-945bb0aa3023.png)

**Comment by Tyriar** [comment]
What theme is this?

**Comment by Tyriar** [comment]
Went with something a little less intense using indexed colors so it's the same across all themes:

![image](https://user-images.githubusercontent.com/2193314/134161970-6bf5b26b-896f-402c-b828-5cd10004442c.png)

![image](https://user-images.githubusercontent.com/2193314/134162005-289b7542-f729-4d5a-9d98-cecf4e54f61a.png)

@misolori feedback welcome on the colors and style of the message. These are the greyscale colors available to us (without using true color which is a little slower):

![image](https://user-images.githubusercontent.com/2193314/134162485-dd070df4-0bdd-4dbe-80db-e16418bcb730.png)

The above is using 247 as the background and 234 as the foreground which is a 6.36:1 contrast ratio (AA, not AAA wcag)

**Comment by Tyriar** [comment]
Went with something a little less intense using indexed colors so it's the same across all themes:

![image](https://user-images.githubusercontent.com/2193314/134161970-6bf5b26b-896f-402c-b828-5cd10004442c.png)
![image](https://user-images.githubusercontent.com/2193314/134162694-298af506-c468-4787-bc46-014b555da826.png)

@misolori feedback welcome on the colors and style of the message. These are the greyscale colors available to us (without using true color which is a little slower):

![image](https://user-images.githubusercontent.com/2193314/134162485-dd070df4-0bdd-4dbe-80db-e16418bcb730.png)

The above is using 247 as the background and 234 as the foreground which is a 6.36:1 contrast ratio (AA, not AAA wcag)

**Comment by bpasero** [comment]
Theme is: Light+ (builtin).

**Comment by misolori** [comment]
When I first saw this today I thought text was selected. Is that the intention? Or why don't we just use regular text colors? 

iTerm for example:

<img width="378" alt="CleanShot 2021-09-21 at 12 28 40@2x" src="https://user-images.githubusercontent.com/35271042/134235221-bc5029dc-07e4-42b1-aa4e-875e38198c4f.png">

**Comment by Tyriar** [comment]
iterm does as does Terminal.app I think when you restart macOS, both have similar presentations with the bar across. This helps make it more clear that the above is a separate thing to prevent confusing the user
