### ISSUE TITLE
Fold / Unfold for methods directly from the Outline

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode#133477]
An example image can explain my feature request better than a thousand words:
![image](https://user-images.githubusercontent.com/52244768/134069514-120c1619-d179-4f7f-8794-42d5f7c460fc.png)
Please add these cool little icons for folding / unfolding methods directly from the Outline (obviously also the method will be brought into the user's scrolling view). And also please provide a configuration that when enabled, unfolding each method in the outline, will fold all the others(no more than one method will be unfolded at the same time).
Thank you.
***
Also as a side-note (not directly related to this feature request), there are a few feature requests among the issues that have requested having the visibilities (public/private/etc.) on the symbols (and in the outline) as well (and ideally, to be able to filter only the public ones too), but they are all closed stating that they were duplicates, however, searching in the issues, I couldn't find the main issue that these were duplicates of. So I wanted to re-mention that request here too, to support it, and it is not terribly unrelated to my request too since both relate to the symbols and the outline.

**Comment by aeschli** [comment]
Thanks for the idea, but we don't have plans to add such a feature.
