### ISSUE TITLE
tsconfig.json is not being taken in consideration

### ISSUE THREAD

**Issue by ipeychev** [Microsoft/vscode#13348]
Visual Studio just stops taking in consideration the tsconfig.json file. I don't have exact steps to reproduce it, but I _think_ it happens once I rename a folder in the project. I'm attaching a screenshot with the result and the options in tsconfig.json

- VSCode Version: Version 1.5.3 (1.5.3)
- OS Version: MacOS 10.12 (16A323)

There are no indicators of any errors, but there were previously:
<img width="373" alt="screen shot 2016-10-07 at 3 54 37 pm" src="https://cloud.githubusercontent.com/assets/78014/19192409/72629af2-8ca6-11e6-86b6-33bff90d29d5.png">

Thanks,

**Comment by ipeychev** [comment]
One more addition here: it looks that if the file is *next* to tsconfig.json (in the same folder), it will be processed, but if it is in a subfolder, the rules will be ignored.

**Comment by waderyan** [comment]
@ipeychev thank you for opening this issue. Can you share your `tsconfig.json` file?

**Comment by ipeychev** [comment]
Yes, I attached it with the screenshot, not sure why is it not here. Here is it again:
[tsconfig.json.zip](https://github.com/Microsoft/vscode/files/517459/tsconfig.json.zip)

**Comment by ipeychev** [comment]
And one more comment (hint):
Angular cli setups a project in such a way, that there are **two** tsconfig.json. One in the main (root) directory and one in the `src` directory. I looks like if the file in `src` directory is missing, this is confusing the IDE.

**Comment by waderyan** [comment]
@ipeychev nothing obvious from the tsconfig.json file. Can you share your workspace?

**Comment by ipeychev** [comment]
I don't have workspace settings, but once I added tsconfig.json to the `src` folder too, it started to work properly, so I'm going to close this issue.

Thanks,
