### ISSUE TITLE
[UI] Breakpoints window always expands

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode#133480]
Issue Type: <b>Bug</b>

1. start python debugging
2. collapse breakpoints window, to have more space for watch window.
3. restart debugging 

now breakpoints window always starts expanded, kinda annoying.

Does it happen for anyone else?

Extension version: 2021.2.633441544
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (3.28GB free)|
|Process Argv|--crash-reporter-id d068a291-e2ce-4726-851f-8253022ad348|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
dockerwalkthrucf:30369616
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by roblourens** [comment]
This happens when there are only these two view panes visible: 
![image](https://user-images.githubusercontent.com/323878/134083426-2464cf39-e5c4-4ac4-a014-d7f878317cb8.png)

@sandy081 or @sbatten I wonder whether you can suggest something here. I think what's happening is that we are setting context keys which make that first view not visible, and make other views visible. In the process of doing this, we do the remove first, hit this line:

https://github.com/microsoft/vscode/blob/f47facd3a4888d31b57f00eff777b8d9903dde67/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L1049-L1049

which forces the Breakpoints view to be visible since it is the only view (?), but then the other views are added immediately after. Is there any way to preserve the collapse state of the Breakpoints view when this happens?

**Comment by sandy081** [comment]
This happens when you have only single view and I think this should not be executed in your case. Because you have more than one view and we remember that. So on reload we will not merge the view with view container.

Is it possible to repro?

**Comment by roblourens** [comment]
> This happens when you have only single view and I think this should not be executed in your case. 

But as context keys change, there is an instant where you have removed the welcome view so there is only one view, the breakpoints view, present. But the other views are being added.

Yeah @sandy081 I can repro it. Open a workspace with no launch config, set a breakpoint in a .py file, collapse the breakpoints view, press F5 to debug the python file, see that the breakpoints view gets expanded.

**Comment by roblourens** [comment]
It looks like views get removed before they get added, on context key change: https://github.com/microsoft/vscode/blob/7690293ae208f91f4e3612e309ac130a85244486/src/vs/workbench/services/views/common/viewContainerModel.ts#L630-L635

**Comment by sandy081** [comment]
Ok, I can repro. It seems the views are removed and added very quickly in a random order and I do not think above ordering of events matter. As the views can be removed and added in a separate event loops. I am not sure if we can have a perfect fix for this. May I know how important it is for Debug viewlet to have the single view merged with viewlet container? If not you can opt out of that by setting `mergeViewWithContainerWhenSingleView` to false here:

https://github.com/microsoft/vscode/blob/f47facd3a4888d31b57f00eff777b8d9903dde67/src/vs/workbench/contrib/debug/browser/debugViewlet.ts#L58-L58

This will let views to be shown always with their headers and not merging with the viewlet title. Let me know if this tactical fix works for you?

**Comment by roblourens** [comment]
I think we should have this for the welcome view, which will often be the only one, and I think it looks better to be merged. I thought they were added/removed in the same event loop iteration, so the order would matter, are you sure it was random?

**Comment by sandy081** [comment]
Fixed it. Remembering the last collapsed state of merged view and retaining it if the view is not merged anymore.

**Comment by mrx23dot** [comment]
Thank you!
