### ISSUE TITLE
React jsx or js files causing errors

### ISSUE THREAD

**Issue by jackcodej** [microsoft/vscode#133469]
Issue Type: <b>Bug</b>

Hello I am at a loss for how to proceed. 

When I write react code in js or jsx files, vscode is not able to recognize it as such code and I am thrown errors for everything. 
This issue only applies to react code. My application is acting normal for other languages.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.20GB free)|
|Process Argv|--crash-reporter-id bcc163aa-ad9a-4688-9f1b-49150db448da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.5
vscode-intelephense-client|bme|1.7.1
path-intellisense|chr|2.4.0
es7-react-js-snippets|dsz|3.1.1
vscode-html-css|ecm|1.10.2
php-debug|fel|1.18.0
php-pack|fel|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-spring-boot|Piv|1.28.0
fabric8-analytics|red|0.3.3
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide code example? What is language mode displayed in status bar? Is it correctly marked as JavaScript?

**Comment by jackcodej** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/54961278/134082022-8833aa69-b33f-4ada-a657-516a37e33359.png)

![Screenshot (48)](https://user-images.githubusercontent.com/54961278/134082222-8591d2a6-d196-4ecc-bc45-7a1d0a79db7c.png)

I followed your tip for Reloading the window with extensions disabled and the issue persisted. I attached a screenshot of it.
The language mode displayed on the status bar for my JavaScript React file is also JavaScript React. The error is the same for cases with or without extensions. I also attached an image of the same for with extensions.

The code itself is a jsx file for creating a functional contact form using emailjs-com

**Comment by IllusionMH** [comment]
That's definitely broken JSX so no wonder why everything is red. You need to fix formatting first and then check again. 

What formatter did you use in this file?

I suspect that vscode-Js-Css-Html-formatter might not support some new JS syntax and break everything. Is it the case?

**Comment by jackcodej** [comment]
That is actually the formatting it changes to whenever I save a jsx file.

Before saving the file was a functional normal looking jsx file.

**Comment by IllusionMH** [comment]
> What formatter did you use in this file?

Does it happen if you disabled all extensions and format whole file (using default formatter)?

You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

If problem is still reproducible try to remove parts of JSX markup to find what code causes problem, remove project specific values and share it.
