### ISSUE TITLE
Jupyter Notebook pyplot output whitespace spans the entire available width

### ISSUE THREAD

**Issue by owen-hwlee** [microsoft/vscode#133414]
- VS Code Version: 1.16
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Create a pyplot graph by code and run
2. Regardless of whether or not figsize is specified, background whitespace takes up the entire span of the available width

![image](https://user-images.githubusercontent.com/55585505/133944523-4d15dd9c-18e3-45bb-84e4-5f167a19267d.png)

![image](https://user-images.githubusercontent.com/55585505/133944537-0225d217-2e07-41d1-bae7-560c3b2acc29.png)

**Comment by rchiodo** [comment]
Dupe of https://github.com/microsoft/vscode-jupyter/issues/7470
