### ISSUE TITLE
make update automated in ubuntu

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#13341]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.4.0-38-generic

updates from vscode are very frequent and it would be better to support automated updates in deb based systems like ubuntu.

thanks.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/2973
