### ISSUE TITLE
Using VSCode snippet with ${CLIPBOARD} that contains multiple new lines causes other cursors to be offset

### ISSUE THREAD

**Issue by ryanIs** [microsoft/vscode#133482]
With a code snippet that I wrote, <b>using the ${CLIPBOARD} (while I have new lines in my clipboard) seems to cause the other cursors to be offset in position.</b> I was expecting the cursor(s) to land exactly where I put them in my code snippet (e.g. Supposed to end here: $0).

Does this issue occur when all extensions are disabled?: Yes

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. I used this VSCode code snippet in plaintext.json
```
"Clipboard bug snippet": {
    "prefix": "clipboardBug",
    "body": [
      "Input 1: $1, Input 2: $2",
      "To lowercase and replace spaces with dashes: $1-${2/(\\s)+|([A-Z]+)/${1:+-}${2:/downcase}/g}",
      "CLIPBOARD: ${CLIPBOARD}",
      "",
      "Supposed to end here: $0",
      "",
      "To lowercase and replace spaces with dashes: $1-${2/(\\s)+|([A-Z]+)/${1:+-}${2:/downcase}/g}",
      "",
      "    CURRENT_DAY_NAME_SHORT: ${CURRENT_DAY_NAME_SHORT}, CURRENT_DATE: ${CURRENT_DATE}*",
      "",
    ],
    "description": "New lines contained in the clipboard cause other VSCode cursors to include a newline."
  },
```
2. Copy a multi-line text block to your clipboard. Example:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id metus dui. Sed faucibus consectetur lorem, non sodales justo tempor eu.

Ut semper nisl sed nulla sagittis, vitae pretium nibh dapibus. Quisque vitae nisl sed erat fermentum pretium eu eget risus. Nulla facilisi. Donec egestas nunc nunc, et varius ex sodales sed. Praesent pulvinar felis vel nunc mattis vulputate. Duis tincidunt sodales laoreet. Pellentesque ac interdum eros.

Phasellus lacinia ipsum mi, nec volutpat justo eleifend non. Cras luctus nisl non turpis congue, non sollicitudin magna gravida. Vivamus mollis
```
3. Run the code snippet `clipboardBug`
4. For input I used: 
```
$1: Hello world!   
$2: THIS IS TEXT
```
5. My result:
```
Input 1: Hello World!, Input 2: THIS IS TEXT
To lowercase and replace spaces with dashes on Input 2: Hello World!-this-is-text
CLIPBOARD: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id metus dui. Sed faucibus consectetur lorem, non sodales justo tempor eu.

Ut semper nisl sed nulla sagittis, vitae pretium nibh dapibus. Quisque vitae nisl sed erat fermentum pretium eu eget risus. Nulla facilisi. Donec egestas nunc nunc, et varius ex sodales sed. Praesent pulvinar felis vel nunc mattis vulputate. Duis tincidunt sodales laoreet. Pellentesque ac interdum eros.

Phasellus lacinia ipsum mi, nec volutpat justo eleifend non. Cras luctus nisl non turpis congue, non sollicitudin magna gravida. Vivamus mollis

Supposed to end here: 

To[I actually ended here] lowercase and replace spaces with dashes on Input 2: -

 Hello World! this-is-text  *CURRENT_DAY_NAME_SHORT: Mon, CURRENT_DATE: 20*
```

Thank you!

**Comment by jrieken** [comment]
This works for me as expected. 
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

https://user-images.githubusercontent.com/1794099/134915093-122e4ad6-3455-4ce9-90c6-6b4b86160d23.mov

**Comment by ryanIs** [comment]
**This works on VS Code Insiders!** 

It did not work on my main VS Code. I am thinking it has something to do with my user settings. I will dink around with my settings to see if I can figure out what may be causing this. The problem still persists without any extensions so I'm kind of confused as to why it may be happening 🙃

https://user-images.githubusercontent.com/7889588/135524709-d64c08a3-d7ee-4f98-8ef8-e87901c11b79.mp4

**Comment by ryanIs** [comment]
Yes sir! Let's go ahead and close it for now! I believe that it only happens to me because of some interesting setup that I have with regard to something about my OS or build. I think this issue is unique to my local environment and does not destruct much productivity. Let's close this ticket! (haha I have a work around for it so it's all good!)

Thank you for your time!
