### ISSUE TITLE
Syntax Highlighting bug C#

### ISSUE THREAD

**Issue by AharonSambol** [microsoft/vscode#133431]
Issue Type: <b>Bug</b>

Variables with switch in their name mess up syntax highlighting.

<b>Steps to reproduce:</b>
Open a new c# file, make a variable whith a name that starts with "switch" for example - "switchableKey" then use the variable in some manner, for example - "switchableKey++;".
After that all the syntax highlighting is ruined.
![image](https://user-images.githubusercontent.com/75334174/133976796-384e209d-2b1a-48d6-934e-fba3d8f0affe.png)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by alexr00** [comment]
@AharonSambol can you please provide a copy/pastable sample I can repro with?

**Comment by AharonSambol** [comment]
@alexr00 
using System;
namespace CSharp{
    class Program{
        static void CorrectSyntaxHighlighting(){
            string str = "str";
            Console.WriteLine(str);
        }
        void func(){
            var switchableKey = true;
            if(switchableKey){  Console.WriteLine("..."); }
        }
        static void IncorrectSyntaxHighlighting(){
            string str = "str";
            Console.WriteLine(str);
        }
    }
}

**Comment by thebinarysearchtree** [comment]
Oh wait, @alexr00 already fixed this, it just isn't in the current version.

**Comment by alexr00** [comment]
@AharonSambol thanks for the sample!

I tested it out, and it looks like one of the recent changes pulled into the C# grammar does fix this as @thebinarysearchtree said.

**Comment by AharonSambol** [comment]
Great, Thanks!
