### ISSUE TITLE
Task #3 Debugging a Java Program( Alternative Code)

### ISSUE THREAD

**Issue by Edward34William** [microsoft/vscode#133499]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
![Screen Shot 2021-09-21 at 1 14 56 AM](https://user-images.githubusercontent.com/57689527/134115199-5f45aaff-11c9-4229-aef7-96ce685c8f42.png)

**Comment by gjsjohnmurray** [comment]
/question

Please do not open issues here which are about making your assignment code work.
