### ISSUE TITLE
Allow to rename an editor tab

### ISSUE THREAD

**Issue by kevin-lindsay-1** [microsoft/vscode#133453]
Let's say, as is often the case, that you're working with a file with a pretty long filename. Having more than one longer filename open can really eat up the window space at the top of the screen.

It would be really nice to be able to give a file a custom name, or a similar system which shrinks the file's tab down in horizontal space. Additionally, it might be nice to be able to "pin" the file's tab so that you can't close it.

I don't think that this pin should be saved across the board, rather just in a particular project.

Perhaps nicknaming a file and pinning a file would be better as separate features, but for my ideal experience, they're both necessary.

I don't see other extensions that really do pinning particularly well, probably the best one I puts the pins on a separate tab in the sidebar, but that's not really the same as keeping the file open while simultaneously reducing its real estate usage.

**Comment by gjsjohnmurray** [comment]
Pinning is already there. Look for it on the tab's context menu.

And see the `workbench.editor.pinnedTabSizing` setting for options.
