### ISSUE TITLE
Can we have a "by project" npm.exclude

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#133446]
When we add some path to exclude for npm in the setting.json (in my case to not showing the npm scripts contained in a folder in the npm scripts section of the sidebar) It is part of the user Vscode config but for me there should be some way of adding a path exclusion relative to the project itself. 
But perhaps this option already exist but couldn't find it

**Comment by IllusionMH** [comment]
Have you tried to add it to workspace settings? `.vscode/settings.json` supposed to store project/folder related settings and can be shared in Git (or VCS of your choice) with teammates.

See https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Comment by albu77** [comment]
No I didn't try because Ididn't know this basic features. Too stupid I am. 
So I've created .vscode/settings.json and move my npm setting there  and sure it works...
Sorry to have bothered you with such a basic detail.
