### ISSUE TITLE
Terminal not interactive, and opening a new terminal not working

### ISSUE THREAD

**Issue by Mann-o** [microsoft/vscode#133435]
Issue Type: <b>Bug</b>

Following latest Insiders update, the Terminal is no longer interactive upon opening VSCode. Trying to split the terminal, or opening a new terminal window (regardless of using bash, zsh etc) results in an empty box.

VS Code version: Code - Insiders 1.61.0-insider (c28c86fcd12e4f8693d6569deadfc740dcf8f55b, 2021-09-20T05:15:38.795Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
laravel-extra-intellisense|ami|0.6.1
atlascode|atl|2.9.1
vscode-intelephense-client|bme|1.7.1
vscode-tailwindcss|bra|0.6.14
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
laravel-blade|cjh|1.1.2
gitignore|cod|0.7.0
laravel-goto-view|cod|1.3.4
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
prettier-vscode|esb|8.1.0
vscode-diff|fab|1.4.2
vscode-todo-plus|fab|4.18.4
php-debug|fel|1.18.0
code-streaming|git|0.3.8
gitlab-workflow|Git|3.30.0
vscode-graphql|Gra|0.3.18
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
githd|hui|2.2.4
vscode-liquid-snippets|kil|2.0.3
graphql-for-vscode|kum|1.15.3
edge|luo|0.3.2
dotenv|mik|1.0.1
vscode-mjml|mjm|1.0.5
vscode-dotnet-runtime|ms-|1.2.0
js-debug-nightly|ms-|2021.9.1717
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4836
language-liquid|nei|0.1.1
vetur|oct|0.34.1
indent-rainbow|ode|8.0.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.13.0
phpunit-snippets|one|1.1.0
vscode-jest|Ort|4.1.2
vscode-versionlens|pfl|1.0.9
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.28
vue-vscode-snippets|sdr|2.2.1
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
laravel-goto-controller|ste|0.0.15
vscode-stripe|str|2.0.3
language-stylus|sys|1.13.0
ayu|tea|1.0.5
vscode-icons|vsc|11.6.0
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
preview-insiders|znc|2021.7.24081567

(4 theme extensions excluded)

</details>

**Comment by sajibAdhi** [comment]
Facing same Bug after August 2021 (version 1.60) update.

**Comment by ErrorDimension** [comment]
![image](https://user-images.githubusercontent.com/75573917/133990728-5309bc93-0d7e-4dc2-af73-04b1a58a8704.png)
Do you mean like this because I have the same regardless what color scheme im using

**Comment by alexanderniebuhr** [comment]
same behaviour, regardless extensions and color themes. 

```
Version: 1.61.0-insider (Universal)
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T05:15:38.795Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

**Comment by ivanvoznyakovsky** [comment]
```
bootstrap-window.js:249 TypeError: this._cursorRenderers[n] is not a function
    at e._render (CursorRenderLayer.ts:153)
    at e.onGridChanged (CursorRenderLayer.ts:115)
    at e.renderRows (WebglRenderer.ts:276)
    at t._renderRows (RenderService.ts:114)
    at e._renderCallback (RenderService.ts:61)
    at e._innerRefresh (RenderDebouncer.ts:61)
    at RenderDebouncer.ts:42
b @ bootstrap-window.js:249
CursorRenderLayer.ts:153 Uncaught TypeError: this._cursorRenderers[n] is not a function
    at e._render (CursorRenderLayer.ts:153)
    at e.onGridChanged (CursorRenderLayer.ts:115)
    at e.renderRows (WebglRenderer.ts:276)
    at t._renderRows (RenderService.ts:114)
    at e._renderCallback (RenderService.ts:61)
    at e._innerRefresh (RenderDebouncer.ts:61)
    at RenderDebouncer.ts:42
```

**Comment by MariaSolOs** [comment]
I'm also having issues with the integrated terminal after today's Insider's update. The cursor is not even there (I can't type in commands) and when resizing it the text is distorted:
![image](https://user-images.githubusercontent.com/62502207/134020590-c7ead6a3-4353-46cd-a5bc-366e46e9cfbd.png)
![image](https://user-images.githubusercontent.com/62502207/134020657-549b8de2-f8d8-452c-a9c7-80f7db10ac17.png)

**Comment by irackson** [comment]
The fix for me was to switch  `"terminal.integrated.cursorStyle": "line",` back to the default 'block'

**Comment by alexanderniebuhr** [comment]
regarding this commit (92ec2bb4ae0d6a16740308d7466ed55cc611b838) `bar` will be the new name for `line`. It does add an legacy mapping. So using following also works for me, regardless the warning that this setting is not introduced yet (would have to wait for new nightly build)

```
"terminal.integrated.cursorStyle": "bar",
```

**Comment by kai3341** [comment]
@irackson @alexanderniebuhr, I have the same issue and the same solution

**Comment by meganrogge** [comment]
I can't reproduce this in Insider's, so believe it's been fixed.
