### ISSUE TITLE
Could not connect to Remote SSH host Again

### ISSUE THREAD

**Issue by tomaxsas** [microsoft/vscode#133436]
- VS Code Version:
- Version: 1.61.0-insider (user setup)
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T07:28:25.574Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

Remote SSH is broken on Windows, again
"remote.SSH.useLocalServer": true setting helps

**Comment by duanehutchins** [comment]
How to roll back VSCode Insider:

Get your VSCode Insider download link (from https://code.visualstudio.com/insiders/), and change the hash in the link to the hash from the last working commit (nightly build), which is `a0af58197e4a1d3e82fbe3048e0549e622d19f4f`. 

So the download links for Windows (64 bit) are:

* User Installer: https://az764295.vo.msecnd.net/insider/a0af58197e4a1d3e82fbe3048e0549e622d19f4f/VSCodeUserSetup-x64-1.61.0-insider.exe
* System Installer: https://az764295.vo.msecnd.net/insider/a0af58197e4a1d3e82fbe3048e0549e622d19f4f/VSCodeSetup-x64-1.61.0-insider.exe
* .zip: https://az764295.vo.msecnd.net/insider/a0af58197e4a1d3e82fbe3048e0549e622d19f4f/VSCode-win32-x64-1.61.0-insider.zip

(You might also have to change the version number, in some cases.)

I tested and confirmed rolling back to `a0af58197e4a1d3e82fbe3048e0549e622d19f4f` fixes the SSH issue.

**Comment by meganrogge** [comment]
fixed with https://github.com/microsoft/vscode/commit/5c922cee38d8bf0f22d1f550020ef5e9d1929677 for tomorrow's insider's

**Comment by TylerLeonhardt** [comment]
@tomaxsas @duanehutchins @benedikt-mayer @1n can you give the insider build a try and let us know if it's fixed for you?
