### ISSUE TITLE
Cannot undo delete cell in Notebooks MacOS

### ISSUE THREAD

**Issue by brunolajoie** [microsoft/vscode#133473]
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: Mac OS 11.4
-   Python and/or Anaconda version: python 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jupyter server running: Local

## Expected behaviour
- Delete a notebook cell
- Press "Z" to "undo delete cell"

## Actual behaviour

- Nothing happens when pressing "Z"
- Cannot find any "Undo delete cell" command anywhere. 
![image](https://user-images.githubusercontent.com/22095643/133804276-beb4f705-2af8-49de-a2c7-61bf5130cc65.png)

**Comment by pa-mike** [comment]
To add to this:

Can replicate, 
![image](https://user-images.githubusercontent.com/45373322/134717385-5c19de54-e4c5-469b-a796-6938fc9eefb6.png)

And additional info on the issue I found for reproducibility: 

VS:
Version: 1.60.1 (Universal)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d

Jupyter Extension: v2021.8.2041215044
Jupyter Keymap: v1.0.0
OS: MacOS 11.5.2
Python 3.9.6
Type of virtual environment used: Conda
Jupyter: Local

Its super finicky. Undo delete cell does not appear in any command, and the shortcut does not appear in jupyter mappings. It looks like regular undo _(Cmd-Z / Ctrl-Z)_ will work to undelete a cell if no other changes are made any cells prior to trying the undo, and as soon as anything is added or changed in cells, it will fail to undelete. 

Start, brand new notebook, add two cells
![image](https://user-images.githubusercontent.com/45373322/134716802-46d80498-11fe-4278-a1c8-5cc0831bef9e.png)

Delete using [...] menu
![image](https://user-images.githubusercontent.com/45373322/134716728-45c9c1be-8a69-4de3-8bd0-ea67742a7153.png)
![image](https://user-images.githubusercontent.com/45373322/134715980-6b9bde11-5e20-4530-8019-b481bca4f553.png)

Undo using topbar
![image](https://user-images.githubusercontent.com/45373322/134716015-2360ea8d-f18d-4ff5-a19c-b08204696857.png)

Will recover the cell operations:
![image](https://user-images.githubusercontent.com/45373322/134716923-e1616a64-7b44-4b46-9d5a-4ff6e7b5ff6d.png)

Delete again, then type in cell,
![image](https://user-images.githubusercontent.com/45373322/134717193-b22fe034-6e8f-4045-b34f-11f5f9adfaef.png)

It appears it fails alongside the merge-cell functionality disappearing.
![image](https://user-images.githubusercontent.com/45373322/134717224-844800d3-76a6-483d-949c-0674279ca3f8.png)

Very strange. Don't know if I am doing something wrong, but hope this helps.

**Comment by brunolajoie** [comment]
I've upgraded VS code to 1.60.2 (as opposed to 1.60.1 when issue was created) and it works.

"Cmd-Z" and "Z" are having the same behavior: they recover my deleted cell.

Closing issue
