### ISSUE TITLE
`Console.KeyAvailable` support in Console (terminal) window

### ISSUE THREAD

**Issue by ikivanc** [microsoft/vscode#133467]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:1.60.1
- OS Version: 19043.1237

I want to use `Console.KeyAvailable` in my C# code using remote debugger with VS Code. I set up `launch.json` with
following the documentation for Console (terminal) window:
[https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window) however I retrieve an error, but same code is working properly with a standalone run through command prompt.

Steps to Reproduce:
1. Create a C# .net core application for .NET Core IoT
2. Add integratedTerminal in launch.json for remote debugging (Copy launch.json as an example)
3. Add line in Main
  ```csharp
  while(!Console.KeyAvailable)
  {
  
  }
  ```
4. Run the remote debugging
5. You'll retrieve an error for Console.KeyAvailable in integratedTerminal
![image](https://user-images.githubusercontent.com/118657/134043246-d437be3d-3521-4d4d-9caa-95531d6961bf.png)

It seems like same issue with `Console.ReadLine()` mentioned in the documentation to not use with internalConsole in launch.json, [https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window)

To solve this I used `integratedTerminal` and 'externalTerminal', but it seems like it's not supported in VSCode console.

**Error:**
![image](https://user-images.githubusercontent.com/118657/134043246-d437be3d-3521-4d4d-9caa-95531d6961bf.png)

**launch.json**

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Remote Launch",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "publish",
            "program": "/opt/dotnet/dotnet",
            "args": ["/home/pi/DNSensorAzureIoTHub/DNSensorAzureIoTHub.dll"],
            "cwd": "~/DNSensorAzureIoTHub",
            "stopAtEntry": false,
            "console": "integratedTerminal",
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}\\dotnet-iot",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "pi@192.168.1.46"
                ],
                "debuggerPath": "~/vsdbg/vsdbg"
                }
            }]
}
```

**Comment by roblourens** [comment]
Please file this on the C# extension repo
