### ISSUE TITLE
vsix opened as text file

### ISSUE THREAD

**Issue by yhql** [Microsoft/vscode#13343]
- VSCode Version: 1.6.0-insider (Date 2016-10-06)
- OS Version: Windows 7 Pro

Steps to Reproduce:

1. Open File
2. Select any .vsix package
3. VSCode tries to display its contents wihout installing it.

**Comment by joaomoreno** [comment]
This behaviour was deprecated.

You can install VSIX by using the action for it, in the extensions pane:

![image](https://cloud.githubusercontent.com/assets/22350/19228803/e4d4413e-8ec8-11e6-9e3f-9296b9f5478e.png)

**Comment by yhql** [comment]
Oh right, thanks :) Clearer like this actually !
