### ISSUE TITLE
[FR] Include newline in selection when clicked beyond the last character of line

### ISSUE THREAD

**Issue by aoyama-val** [microsoft/vscode#133498]
Point the cursor at the beginning of the selection.
Shift + click at the point beyond the last character of line.
The newline is not included in the selection, so cut & paste is being awkward.

![vscode-selection](https://user-images.githubusercontent.com/13144822/134114744-63495c6c-acca-436d-9d87-c0a9550cec87.gif)

I know that I can include the newline with Shift + right after click, but it would be better if there was no need to do so.

**Comment by gjsjohnmurray** [comment]
Try clicking on the line number instead.

**Comment by aoyama-val** [comment]
@gjsjohnmurray 
Thanks for the tip, dragging the line number worked. 😁   However

1. Line number is so small that we easily misclick breakpoint or fold marker area
2. Dragging is harder to select many lines. Imagine holding the left button and scrolling wheel until you see the end position.

**Comment by gjsjohnmurray** [comment]
You don't need to drag the line number. Just click it. And to select multiple, shift-click the final line.
