### ISSUE TITLE
Typescript suggestions very often stops working until I restart vs code

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/vscode#13346]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Steps to Reproduce:

1.  Just doing regular work

p.s. actually this happens not only for typescript but for example auto arrange code: alt + shift  + f, or plugins like: JavaScript (ES6) code snippets, Code Beautifier

**Comment by waderyan** [comment]
@vytautas-pranskunas- thank you for opening this [issue](https://github.com/Microsoft/TypeScript/issues/10735). I have observed this numerous times and have created this issue on the TS repo to try and recreate it.

Can you help us find out what is going on? 

Set this attribute in your settings. 

```
"typescript.tsserver.trace": "verbose"
```

Then open the output window and post what you see in this [issue](https://github.com/Microsoft/TypeScript/issues/10735). 

Also open the developer console (Help -> Toggle Developer Tools) and send us the output.

**Comment by waderyan** [comment]
I'm closing this in our repo as it is represented in TS repo now here - https://github.com/Microsoft/TypeScript/issues/10735
