### ISSUE TITLE
want to disable auto format feature of editor

### ISSUE THREAD

**Issue by jojokaran72** [Microsoft/vscode#13344]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open any javascript file with existing code
2. hot ctrl+s to save file editor will save  file and perform code formatting which i don't want
3. Please tell me where i can disable this feature of auto formatting.

**Comment by Tyriar** [comment]
Try adding `"editor.trimAutoWhitespace": false` to your setting.json file, if it's not that it's likely an extension.
