### ISSUE TITLE
[Bug] File is listed in the "Changes" section even if it has no change

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#133417]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.61.0-insider
- OS Version: Windows 10

_**File encoding is UTF-8 with BOM.**_

Steps to Reproduce:

- ![STG 2021-09-20 09_55_48](https://user-images.githubusercontent.com/28700378/133950823-a8af0f9d-6df9-439c-9956-1598defd3bb7.gif)

- Notice the diff editor in the "Changes" (**Not** "Staged Changes") section shows no change, but the file is still listed there nonetheless.

**Comment by hamzawaleed0102** [comment]
@wenfangdu I'm unable to figure out whats wrong here 😕 I mean you added a **new line** and then staged the changes, then under diff viewer its reflecting that exact **new line** change. That's perfectly fine 🤔 . Pardon me if I missed something?

**Comment by wenfangdu** [comment]
@hamzawaleed0102

> then under diff viewer it's reflecting that exact new line change

That's under "Staged Changes", the issue is for the "Changes" section:

![image](https://user-images.githubusercontent.com/28700378/133974811-38a8568e-b4c8-42b8-baac-be22b7e20389.png)

**Comment by wenfangdu** [comment]
@Lemmingh @hamzawaleed0102 Please see the updated issue, and remove the "confused" emoji if it's clear for you now.

**Comment by hamzawaleed0102** [comment]
@wenfangdu Oh got it, now makes sense. I'm not a pro in it so I need to see whether it's a bug or expected behaviour. After all changing the file encoding is still a change but sometimes not a visible one.

**Comment by wenfangdu** [comment]
@hamzawaleed0102 It's reproducible for new files with `utf8bom` encoding as well, i.e. no change for the encoding.

**Comment by wenfangdu** [comment]
@hamzawaleed0102 I've updated the issue to reflect that.

**Comment by Lemmingh** [comment]
OK. I can tell what happened. But I'm not sure who is to blame: VS Code, Git, or ConHost.

When invoking "Git: Stage Selected Ranges" (`git.stageSelectedRanges`), VS Code runs:

```shell
git hash-object --stdin -w --path test.ahk
```

Inspect the created object, and we can surprisingly find that **it does not have BOM**.

You can get a visual hint by:

```shell
git status --verbose
```

**Comment by Lemmingh** [comment]
/duplicate #111915

<https://github.com/microsoft/vscode/blob/adee8fa29ad3635418ff995b235c4b08a40c8434/extensions/git/src/git.ts#L1278-L1283>

The encoding information is lost.

I can also reproduce the problem with GB 2312.

```
锟斤拷
```
