### ISSUE TITLE
Terminal content not shown while resolver runs

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#133442]
This seems to be new with today's Insiders build. Previously the terminal would show its content while the resolver was still running. Now it shows empty:
![image](https://user-images.githubusercontent.com/9205389/134004447-52dbe3ec-4625-4f36-8a10-1937b4531be0.png)

Not sure I've seen the same on Windows. This is Mac.

Version: 1.61.0-insider
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T05:15:38.795Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by alexanderniebuhr** [comment]
might be related to, not sure
https://github.com/microsoft/vscode/issues/133435

**Comment by chrmarti** [comment]
It works as expected in last Friday's Insiders build.
Version: 1.61.0-insider
Commit: a0af58197e4a1d3e82fbe3048e0549e622d19f4f
Date: 2021-09-17T05:13:49.338Z

**Comment by Tyriar** [comment]
Think it's related to `this._userHome = (await this._pathService.userHome()).fsPath;`

https://github.com/microsoft/vscode/commit/185cd700714bb8044ee0869017f7a3e95259682a#
