### ISSUE TITLE
Jupyter Notebook markdown cell not displaying task list correctly 

### ISSUE THREAD

**Issue by owen-hwlee** [microsoft/vscode#133413]
- VS Code Version: 1.16
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Creating a markdown cell in a Jupyter Notebook
2. Type up a checklist in [x] and [ ] format
3. Displaying the markdown cell

![image](https://user-images.githubusercontent.com/55585505/133944323-3cf78366-633a-49ba-90a7-5838b707f6ac.png)

![image](https://user-images.githubusercontent.com/55585505/133944331-844deec8-8367-4694-b83e-f22f49719eb6.png)

**Comment by mjbvz** [comment]
This is currently expected as task lists are not part of the markdown standard (but other jupyter programs may enable them)
