### ISSUE TITLE
Update in wrong directory

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#133448]
Issue Type: <b>Bug</b>

When a vscode insider update is installed, it is installed in c:/programfiles, and I installed vscode on d:/

VS Code version: Code - Insiders 1.61.0-insider (a0af58197e4a1d3e82fbe3048e0549e622d19f4f, 2021-09-17T05:15:50.405Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.37GB free)|
|Process Argv|--crash-reporter-id afa3a3df-842c-47d3-b623-a2aafc374e90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
TabOut|alb|0.2.1
Bookmarks|ale|13.2.1
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.1
toggle-upper-case|epr|0.0.1
vscode-gutter-preview|kis|0.27.1
sftp|lix|1.12.9
gremlins|nho|0.26.0
code-spell-checker|str|2.0.6
code-spell-checker-portuguese-brazilian|str|2.0.2
tabnine-vscode|Tab|3.4.27
vscode-input-sequence|tom|0.2.0
hex-ascii-converter|yrp|0.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by joaomoreno** [comment]
Can you fully uninstall VS Code and reinstall again in the proper location? Make sure you don't have multiple VS Code installations on your system.
