### ISSUE TITLE
Diff view from git and gitlens send textDocument/documentColor request to connected LS

### ISSUE THREAD

**Issue by nixel2007** [microsoft/vscode#133458]
Issue Type: <b>Bug</b>

Hello. I have a LS with documentColor and colorPresentation requests. If I open diff on some file, vscode sends textDocument/documentColor request:

```
[Trace - 18:20:25] Sending request 'textDocument/documentColor - (33)'.
Params: {
    "textDocument": {
        "uri": "gitlens://7a3d137/d%3A/git/accreditation/main/src/cf/Catalogs/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D1%8B%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D0%B8%D1%85%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0/Ext/Form/Module.bsl?%7B%22path%22%3A%22%2Fd%3A%2Fgit%2Faccreditation%2Fmain%2Fsrc%2Fcf%2FCatalogs%2F%D0%93%D1%80%D1%83%D0%BF%D0%BF%D1%8B%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D0%B8%D1%85%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%B9%2FForms%2F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%2FExt%2FForm%2FModule.bsl%22%2C%22ref%22%3A%227a3d1370492ae91274d078b9fb91f3f89002c2dc%22%2C%22repoPath%22%3A%22d%3A%2Fgit%2Faccreditation%2Fmain%22%7D"
    }
}
```

No other requests with this uri were sent to LS (no didOpen/didChange/hover/format, etc), so LS know nothing about this file/uri.

I thinks this is a bug, and git/gitlens should not send this requests as well as they don't send other requests.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (7.67GB free)|
|Process Argv|--crash-reporter-id 9801231d-329c-438e-82b7-823b8802b67c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (120)</summary>

Extension|Author (truncated)|Version
---|---|---
1c-executor-plugin|1c-|0.1.6
language-1c-bsl|1c-|1.24.2
vscode-sql-formatter|adp|1.4.4
markdown-toc|Ala|1.5.6
Bookmarks|ale|13.2.1
pascal-formatter|ale|2.5.0
vscode-sqlite|ale|0.13.0
cucumberautocomplete|ale|2.15.1
1c-extension-pack|ast|1.0.2
gitkraken-glo|axo|1.1.1
docs-view|bie|0.0.9
vscode-intelephense-client|bme|1.7.1
better-toml|bun|0.3.2
gitignore|cod|0.7.0
vscode-crowdin|Cro|1.2.1
vscode-markdownlint|Dav|0.44.0
vscode-eslint|dba|2.1.25
ansible-vault|dho|0.1.3
githistory|don|0.6.18
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
vscode-npm-script|eg2|0.3.22
json-tools|eri|1.0.2
prettier-vscode|esb|8.2.0
oscript-debug|Evi|0.7.1
php-pack|fel|1.0.2
file-icons|fil|1.0.29
flow-for-vscode|flo|1.9.2
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
shell-format|fox|7.1.0
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.30.0
gc-excelviewer|Gra|3.0.44
todo-tree|Gru|0.0.214
vscode-nginx-conf-hint|han|0.1.0
minify|Hoo|0.4.3
rest-client|hum|0.24.5
error-gutters|Igo|1.0.1
reg|ion|1.0.3
java-properties|ith|0.0.2
asyncapi-preview|iva|0.1.1
jenkins-pipeline-linter-connector|jan|1.2.0
plantuml|jeb|2.15.1
Lua-Nginx-Snippets|jie|0.0.4
jenkins-declarative-support|jmM|0.1.0
Angular2|joh|12.0.0
Kotlin|mat|1.7.1
rainbow-csv|mec|1.9.1
vscode-antlr4|mik|2.2.4
dotenv|mik|1.0.1
ecdc|mit|1.4.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.16.1
vscode-language-pack-ru|MS-|1.60.4
vscode-kubernetes-tools|ms-|1.3.3
mssql|ms-|1.10.1
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
sarif-viewer|MS-|3.0.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
powershell|ms-|2021.9.0
vscode-js-profile-flame|ms-|0.0.21
vscode-typescript-tslint-plugin|ms-|1.3.3
sqltools|mtx|0.23.0
gradle-language|nac|0.2.3
vscode-groovy-lint|Nic|1.4.0
createGUID|nwa|0.0.2
vscode-versionlens|pfl|1.0.9
vscode-boot-dev-pack|Piv|0.1.0
vscode-manifest-yaml|Piv|1.28.0
vscode-spring-boot|Piv|1.28.0
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
ansible|red|0.4.5
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
tester|Res|1.5.4
vscode-gradle|ric|3.6.1
vscode-gradle-extension-pack|ric|0.0.2
vscode-coverage-gutters|rya|2.8.1
partial-diff|ryu|1.4.3
vscode-nginx|sha|0.6.0
vscode-table-formatter|shu|1.2.1
vscode-autohotkey|sle|0.2.2
sonarlint-vscode|Son|2.2.0
cucumber|ste|0.13.5
code-spell-checker|str|2.0.6
code-spell-checker-russian|str|2.0.1
jenkins-jack|tab|1.1.6
json-schema-validator|tbe|0.1.0
vscode-markdown-paste-image|tel|0.13.8
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
asyncapi-validator-vscode|wal|0.0.5
ansible-vault-inline|wol|0.4.0
bracket-lens|wra|1.5.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.11.4
markdown-html|zhy|0.1.8

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by nixel2007** [comment]
On the other side vscode could send all requests to LS (including didOpen with content), so LS could provide some functionality to this fake uri.

**Comment by dbaeumer** [comment]
@nixel2007 this is under the control of the extension or language server. It is controlled via the document selector used either when creating the language client or when registering the feature dynamically via the language server.

**Comment by nixel2007** [comment]
@dbaeumer there is no problem with document selector. it really matches server's config. The problem is with types of requests. vscode doesn't send _any_ other requests except textDocument/documentColor for this file. no dynamic registration of capabilities, all capabilities are registred at initialize request.

**Comment by nixel2007** [comment]
here is the same unwanted request from git diff panel:
```
[Trace - 11:38:11] Sending request 'textDocument/documentColor - (638)'.
Params: {
    "textDocument": {
        "uri": "git:/e%3A/aayukhanov/repo/add/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl?%7B%22path%22%3A%22e%3A%5C%5Caayukhanov%5C%5Crepo%5C%5Cadd%5C%5Ctests%5C%5Csmoke%5C%5C%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%5C%5C%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%5C%5CForms%5C%5C%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%5C%5CExt%5C%5CForm%5C%5CModule.bsl%22%2C%22ref%22%3A%22~%22%7D"
    }
}
```

**Comment by nixel2007** [comment]
clientOptions (https://github.com/1c-syntax/vsc-language-1c-bsl/blob/develop/src/features/languageClientProvider.ts#L161-L172): 
```
documentSelector: [
    { scheme: "file", language: "bsl" },
    { scheme: "untitled", language: "bsl" }
],
```

documentSelector in server's `initialize` response (https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/DocumentSelector.java#L42-L45)
```
"colorProvider": {
    "workDoneProgress": false,
    "documentSelector": [
        {
            "language": "bsl"
        }
    ]
},
```

**Comment by dbaeumer** [comment]
The problem is the document selector on the server side. A selector with `"language": "bsl"` will match the `"git:/e%3A/aayukhanov/repo/add/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl?%7B%22path%22%3A%22e%3A%5C%5Caayukhanov%5C%5Crepo%5C%5Cadd%5C%5Ctests%5C%5Csmoke%5C%5C%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%5C%5C%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8%5C%5CForms%5C%5C%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%5C%5CExt%5C%5CForm%5C%5CModule.bsl%22%2C%22ref%22%3A%22~%22%7D"` since that git file has the language id 'bsl' as well. You should also add the scheme there ('untitled' and 'file') to filter the 'git' scheme.

**Comment by nixel2007** [comment]
okey, but why vscode doesn't send any other requests other than documentColor? why it does not send didOpen? who sends this request? client is registered with schemas, so it can't send this request. who sends it then?

**Comment by nixel2007** [comment]
Ah, I see! I didn't notice that document selector in registration options override client defaults for this provider.

If I understand it correctly, I don't receive didOpen, cause there is no override of document selector in text document synchronization options, so schema-filter ehm... filters git/gitlens files. And I _do_ recieve documentColor, cause server override document selector for color provider options with larger value (without schema-filter). 

Maybe it deserves some additional note in DocumentSelector jsdoc. Something like "You should use it only for making selector more strict than default one, cause you could miss some basic requests".

One last question: I don't see any information about document selector on client side in `initialize` request. How should I know about this default values so I can override it in providers' options if I need it?

**Comment by nixel2007** [comment]
And it is strange, that other providers with document selector does not receive any requests... I have this selectors overrided in foldingRange also.

```
        "foldingRangeProvider": {
            "workDoneProgress": false,
            "documentSelector": [
                {
                    "language": "bsl"
                }
            ]
        },
```

but LS doesn't receive any requests for this schema.

LSP trace log file: 
[tracelog.log](https://github.com/microsoft/vscode/files/7217063/tracelog.log)

**Comment by dbaeumer** [comment]
That the VS Code client has a default client selector is legacy and not part of the protocol. Other clients might treat that different. Since there is dynamic registration there is no need for a client to define a default anymore.

**Comment by nixel2007** [comment]
ok, thanks for clarification, @dbaeumer!
