### ISSUE TITLE
Please reopen issue #131384 ... Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by jshaw15** [microsoft/vscode#133449]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: OpenSuse 15.2
- OS Version: 1.56 and higher

Steps to Reproduce:

1. Run any version of VS code higher than 1.55 (which works correctly!)
2. On start, I get this error:
3.    ./bin/code: line 53:   344 Trace/breakpoint trap   (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@", Its unclear if this is the same error as #131384 or not, but its similar. The code will not start from a gui icon either.
4. I have tried many versions, pulled from the Microsoft yum repository for OpenSuSE. I have also tried Chormium versions with the same result. A completely virgin install (ie,delete all code parts, ~/.vscode, and ~/.config/Code) makes no difference. I have tried the "standalone" version from a tgz file as well. The difference between 1.55 and 1.56 seems to be the later is using ELECTRON 12. 
5. I have attached an strace of an attempted run from version "code-stable-x64-1631295096.tar.gz". You can see its some sort of memory allocation issue.  Computer is i7-6700k (4 core Skylake), 32 GB memory, btrfs as root, 2 nVidia GPUs GTX-950 + V100). I have also tried to disable extensions, no gpu, etc.
6. Also attached is listing of ldd on the code.
[code_strace.txt](https://github.com/microsoft/vscode/files/7196201/code_strace.txt)
[code_ldd.txt](https://github.com/microsoft/vscode/files/7196229/code_ldd.txt)

**Comment by jshaw15** [comment]
We have a winner! I had set both memoryuse and vmemoryuse to 31g with the csh limit command (in .cshrc). Pushing vmemoryuse up to 48g in a test shows new versions of code now start and work. This is about as low as it can be. This may explain some other issues I have with electron-based applications (eg, discord). At least discord now tries to start for me, but it still crashes. I expect that is some other issue.

I have spend months on this issue and it was driving me crazy. Its not that I could not live without an update to code, but I was looking for hardware errors, and all sorts of other software issues (eg, memory is failing, disks are failing, cpu + MB is failing, ... there is a tread here).

I would propose the developers put in an explicit test and print a message if code fails to allocate memory, and suggest the fix.

**Comment by jumpmanjay** [comment]
It would be nice if there was a different workaround for this. Ie- a way to run 1.56+ on boxes where ulimit -a != unlimited.

**Comment by deepak1556** [comment]
This is a limitation from the runtime to surface the error in these cases, closing as not actionable.

**Comment by ExpHP** [comment]
Do you have any further details about this limitation that could help somebody file an appropriate issue to an upstream project?  (e.g. to electron or chromium)

**Comment by deepak1556** [comment]
The error in this case happens before the application code gets a chance to execute, so it is upto the runtime to surface allocation errors. You can file a feature request in https://github.com/electron/electron/issues/new/choose with a minimal repro.
