### ISSUE TITLE
Extension authors should be able to put settings in a specific order

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#133483]
Affects https://github.com/microsoft/vscode/issues/70589

**Comment by eamodio** [comment]
@rzhao271 I've been playing around with this in GitLens -- This is awesome!

From using this new field, it makes me *REALLY* which the order of the settings in the JSON were honored -- similar to how command placements are. That way I could largely avoid needing to set an order on individual settings and instead rely on the order within each category. And then the order could just be used as an override.

Also ran into a minor issue, it looks like not having an `order` on settings does indeed order them at the end (which is great), but `order` on the categories doesn't (seems like they are ranked highest). Not a big deal as it is much easier to add an order to every category, but it would be nice to be consistent.

/cc @roblourens

**Comment by rzhao271** [comment]
I'll treat that inconsistency as another bug under https://github.com/microsoft/vscode/issues/137257
