### ISSUE TITLE
Language status item improvements

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#133456]
While adapting the status item for ESLint I noticed that it is hard to spot the reason why the language status is NOT OK. 

I would like to request the following two improvements:

- render the severity icon with every status if the overall status is !== OK. This will help to spot the contribution that causes issues
- if the status item is detached (rendered as its own status item) always render the status severity with the item.

**Comment by jrieken** [comment]
> if the status item is detached (rendered as its own status item) always render the status severity with the item.

For that I am leaning towards the corresponding status bar colors, like the warning and error background

**Comment by bpasero** [comment]
Given the special treatment of the language status indicator being a "friend" of editor language, the background color might not work as nicely as it would if the indicator was separate:

![image](https://user-images.githubusercontent.com/900690/134119546-e6963e80-e67b-4d7b-9049-44736a4aef64.png)

I would rather then suggest to have both the indicator and the language picker to have the same background color:

![image](https://user-images.githubusercontent.com/900690/134119645-6e67743f-5798-4598-b162-f525d2cfadbf.png)

**Comment by jrieken** [comment]
fyi @daviddossett

**Comment by dbaeumer** [comment]
That makes sense however I meant something different. In the screen shot below there is a warning icon in front of TypeScript since one of the language status item has a severity of warn. But which one? You need to read the text of all the items and even then it would not be clear.

**Comment by dbaeumer** [comment]
Rendering the item with the warn severity in a different background might be better than adding icons.

**Comment by jrieken** [comment]
Yeah, there the two options: (a) show warning/error when pinned and (b) show warning/error when inside the hover. This is how both variants look like now:

<img width="371" alt="Screen Shot 2021-09-21 at 10 54 07" src="https://user-images.githubusercontent.com/1794099/134141884-8a87b585-5654-4333-b43b-e5953d684d2e.png">

<img width="622" alt="Screen Shot 2021-09-21 at 10 52 35" src="https://user-images.githubusercontent.com/1794099/134141804-50acfb67-1eb0-4e8b-86ae-3fbd1d7016a6.png">

The OK (double check) icon might not be needed after all. Also, the color of the "main" status bar entry doesn't change right now
