### ISSUE TITLE
On "Developer: Reload Window" another terminal instance opens

### ISSUE THREAD

**Issue by Admiralfeb** [microsoft/vscode#133405]
Issue Type: <b>Bug</b>

1. Open VS Code
2. Have the Integrated Terminal open
3. Open the Command Pallete and choose "Developer: Reload Window"
4. Window will reload

Expected: Only the terminal instance that I have open should be present after reload.
Actual: 2 instances of the terminal are open. (or n+1 where n was the number of terminals before reload)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:13.580Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--disable-extensions --crash-reporter-id e2dfbe27-82cd-4d6f-8cd1-7760b8fd9275|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by meganrogge** [comment]
Already fixed in insiders
