### ISSUE TITLE
Large python libraries slow down language server dependent features.

### ISSUE THREAD

**Issue by tylerchambers** [microsoft/vscode#133487]
Issue Type: <b>Bug</b>

I'm using [bitcoinlib](https://bitcoinlib.readthedocs.io/en/latest/) and when working with bitcoinlib.keys everything depending on a language server slows down in my editor. Things that normally happen pretty instantly like syntax highlighting, jumping to a definition, autocomplete, etc. take seconds. The editor itself remains responsive. I can still type, open / close files, change tabs, etc.

To reproduce, install bitcoinlib and navigate to this file:
https://github.com/tylerchambers/flask-btc/blob/main/src/flask_btc/wallet.py

In the Wallet class try doing anything with self.HDKey. 
e.g: declaring a variable and assigning to subkey.address(). Takes forever.

Things I've tried to fix it: fresh VSCode and fresh OS Install.

Any help appreciated!

*EIDT:* I ran the extension profiler, and reproduced the issue. It does look like the MS python extension is waiting on a reply from the language server. I'm no longer sure this is the appropriate place to file the bug, any pointers appreciated.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.11.0-34-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 1550)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.29GB (23.60GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
prettier-vscode|esb|9.0.0
go|gol|0.28.0
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by sbatten** [comment]
Please try filing the issue https://github.com/microsoft/vscode-python first, thanks for filing the issue.
