### ISSUE TITLE
CMD+J default keyboard shortcut not firing

### ISSUE THREAD

**Issue by emeraldsanto** [microsoft/vscode#133454]
Issue Type: <b>Bug</b>

I recently noticed that the usual `CMD+J` hotkey to toggle the editor panel no longer triggered anything. I've followed the troubleshooting steps I found on other issues (enabling shortcut debugging, etc.) without much success.

I found out that when trying to remap this shortcut, upon registering `CMD+J` for this command, only the `CMD` symbol shows up. It seems the `J` key is never sent to Code.

I have looked at the OS level keyboard shortcuts and could not find anything that could conflict with this particular combination.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 11, 7|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 28a9acaa-16d8-4685-88be-f4635e474678|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
user-secrets|adr|2.0.1
ng-template|Ang|12.2.0
theme-verdandi|be5|2.0.1
vscode-tailwindcss|bra|0.6.14
path-intellisense|chr|2.4.0
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|8.2.0
vscode-mysql|for|0.4.1
vscode-pull-request-github|Git|0.30.0
vscode-graphql|Gra|0.3.18
vscode-test-explorer|hbe|2.21.1
vscode-styled-components|jpo|1.6.6
vscode-jest-test-adapter|kav|0.8.1
vscode-docker|ms-|1.16.1
csharp|ms-|1.23.15
vscode-edge-devtools|ms-|1.3.1
mssql|ms-|1.10.1
test-adapter-converter|ms-|0.1.2
mdx|sil|0.1.0
svelte-vscode|sve|105.4.0
quokka-vscode|Wal|1.0.401
vscode-todo-highlight|way|1.0.4
fig|wit|0.0.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `cmd+J`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by emeraldsanto** [comment]
Not sure how to interpret the logs so here they are!

```
[2021-09-21 09:06:44.069] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-09-21 09:06:44.070] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-09-21 09:06:44.070] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-09-21 09:06:44.609] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord meta.
[2021-09-21 09:06:44.910] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

**Comment by alexdima** [comment]
Indeed, it looks like `cmd+j` does not reach VS Code. Unfortunately, there is nothing we can do on our side, it looks like the OS or some other software is consuming `cmd+j` globally.
