### ISSUE TITLE
Work directory is ignored when opening a new terminal with different profile in multiple folder workspace

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode#133459]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.60.1
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Click on the "arrow" to launch profile in the terminal 
2. Select the desired profile
3. VS Code asks for "select the current work directory for the new terminal"
4.  Select a different folder on the multi root workspace
5. The terminal opens on the same directory/folder, ignoring what is selected in step 4.

![gif001](https://user-images.githubusercontent.com/57204023/134034394-2571a860-ff47-47db-8f5a-7e5ff84f4a28.gif)

#### OBS:

The following steps still works fine:

Press `ctrl+k ctrl+tab` → `create a new terminal with profile` → selecting the working directory → select the profile.

**Comment by meganrogge** [comment]
can you see if you're able to reproduce this in insider's?

**Comment by Diogo-Rossi** [comment]
> can you see if you're able to reproduce this in insider's?

yes, also happens in the insider's version, look:

![gif002](https://user-images.githubusercontent.com/57204023/134953265-b04476b7-145f-4552-b559-9ff6936efaab.gif)
