### ISSUE TITLE
Missing jsconfig.json attributes

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#13349]
`jsconfig.json` is `tsconfig.json` with `allowJS` set to `true`. 

A recent release of TS added `include` attribute to the configuration file. We are not seeing that in the IntelliSense for `jsconfig.json`

![image](https://cloud.githubusercontent.com/assets/2449568/19192599/9b5aee5a-8c5b-11e6-99b9-db60d33f5f41.png)

Test by creating a `jsconfig.json` file with 

```
{

}
```

Trigger IntelliSense. I expect to see the `include` attribute but I do not.

**Comment by dbaeumer** [comment]
This is again something that has to come from the JSON schema store. The JSON schema drives code assist and validation.

**Comment by waderyan** [comment]
Thanks @dbaeumer. I looked in schema store and it looks like include definition is already specified in the schema. Possibly I am not reading the file correctly. 

Here is what I see in [jsconfig.json](https://github.com/SchemaStore/schemastore/blob/1d6da775dc217822580738992a44f78210597f2f/src/schemas/json/jsconfig.json).

![image](https://cloud.githubusercontent.com/assets/2449568/19390112/89729136-91db-11e6-9af6-ea7ab0814381.png)

Here is what I see in [tsconfig.json](https://github.com/SchemaStore/schemastore/blob/1d6da775dc217822580738992a44f78210597f2f/src/schemas/json/tsconfig.json).

![image](https://cloud.githubusercontent.com/assets/2449568/19390143/a57e5e96-91db-11e6-8c33-e507d4e1e810.png)

These definitions are in schema store, but they are still not showing up with IntelliSense. 

![image](https://cloud.githubusercontent.com/assets/2449568/19390084/69cc43cc-91db-11e6-9a0d-81365b84a851.png)

**Comment by dbaeumer** [comment]
Are you offline when trying this. The we can't reach the schema store?

**Comment by waderyan** [comment]
No I am online.

**Comment by dbaeumer** [comment]
OK. Might be a problem not mapping jsconfig.json to the right schema.

**Comment by waderyan** [comment]
@dbaeumer can you advise on how I can investigate? Unless you are already on it.

**Comment by dbaeumer** [comment]
I am not on it. The code to look at would be the package.json of the TS extension to see if the schema is mapped to jsconfig.json files.

**Comment by mjbvz** [comment]
I've opened a PR against schemastore to fix this: https://github.com/SchemaStore/schemastore/pull/253

I believe the root cause is that the current `jsconfig.json` and `tsconfig.json` schemas do not expose the `include` property on the top level object.
