### ISSUE TITLE
Adopt EditorInputCapabilities.ForceDescription in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133452]
This new capability allows the terminal to control when the tab description shows, so we can align the description in the terminal editor with how it shows up in a terminal panel tab.

https://github.com/microsoft/vscode/blob/adee8fa29ad3635418ff995b235c4b08a40c8434/src/vs/workbench/common/editor.ts#L527-L533

**Comment by meganrogge** [comment]
To verify:
- Run a task, move the terminal to the editor area, check that the `Task` description shows up like it did in the panel
- In a terminal, change the directory, verify you see it in the tab description in the panel
- Move that to the terminal editor, make sure you see it there as well

**Comment by andreamah** [comment]
Is this tooltip the task description?
<img width="486" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/5e384796-8339-4219-8b88-26991f172e25">

I think I'm a bit confused on how a task would be affected by a different terminal changing directories.

**Comment by meganrogge** [comment]
drag the terminal into the editor area and you should still see `task` in the label of the tab.
