### ISSUE TITLE
New Terminal does not open in v.1.60. Update Mode cannot be set to "none" 

### ISSUE THREAD

**Issue by mrRimas** [microsoft/vscode#133423]
Issue Type: <b>Bug</b>

After update to v.1.60:
Terminal => New Terminal not appearing - no reaction whatsoever.
After returning to older versions: 1.56.2, 1.54.3 New Terminal working. But impossible to set Update Mode (Preferences => Settings => Update) to 'none'. At the attempt the text appears "Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again". After opening Settings.json at least one error is indicated: red waving line under "PowerShell". 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.43GB (0.33GB free)|
|Process Argv|--crash-reporter-id 6f8001b7-169b-4a42-86b0-3dd7984e9a2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.27.2
debugger-for-chrome|msj|4.13.0
vscode-print|pdc|0.9.12
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.14

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
>  Please open the user settings to correct errors/warnings in it and try again". After opening Settings.json at least one error is indicated: red waving line under "PowerShell".

Please provide lines that cause an error. Did you write them.
Then remove of fix lines with error - then settings could be saved as expected.

Also latest 1.60.1 has fixed related to terminals.

**Comment by mrRimas** [comment]
Thank you for your assistance. See attachment.
I didn't spoil the settings.json, too much afraid to make changes which I
do not understand.

BR from Lithuania,
mrRimas
Rimantas Zabarauskas
Self-learner of JS, Node etc.

**Comment by IllusionMH** [comment]
Unfortunately you need to upload filed from GitHub UI, email attachments are not added to issue comments.

**Comment by mrRimas** [comment]
Please ignore the second file in Lithuanian... attached accidentally..
My apologies,

mrRimas

**Comment by mrRimas** [comment]
[newTerminalCrash.docx](https://github.com/microsoft/vscode/files/7195383/newTerminalCrash.docx)

**Comment by IllusionMH** [comment]
.docx is bad format to show settings.json files, that all that was needed.

You have random `"!**/node_modules/..." ` that shouldn't be part of profiles object. You should remove it.

How did you get this line in that place?

**Comment by mrRimas** [comment]
See attached.
1.Removed the line "!**/node_modules/..."
The red err line under "PowerShell" disappeared.

2.Noticed a small red line under the last line (28). Added one curly
bracket.
All errors disappeared.

3. System required to save changes. After restarting everything things went
smoothly and I could change the Update Mode to 'none'
Success!!

Restarting automatically updated to v1.60.1
Still Terminal => New Terminal not working.

At least now I can hold in place older versions.

How did the wrong line get into settings.json? It might be my fault... now
I remember that a month ago I probably tried to "modernise" the file
including Node (I was working with the backend). I did not worry because I
was certain that a new update or installation automatically reset the
settings.json to the default option (which cannot contain errors)  ...
seems I was wrong.

Thanks a lot for solving one issue... another still remains.

**Comment by mrRimas** [comment]
Andrii Dieiev solved my issue with Update. It was me who accidentally spoiled the file settings.json . After repair the Update Mode working well.
However Terminal => New Terminal not working yet.

**Comment by IllusionMH** [comment]
Try to remove (backup first if needed `terminal.integrated.profiles.windows` and `terminal.integrated.defaultProfile.windows` from from `settings.json` and add back default values and see if that works. with defaults.

**Comment by mrRimas** [comment]
One problem out of 2 solved by IllusionMH. The other - New Terminal not working in v1.60.1 remains, but this does not create any inconvenience because I can use older versions (currently 1.59.1, in which New Terminal works) with Update option set to 'none'. This is quite OK.
Thanks for help.
