### ISSUE TITLE
Korean typing error

### ISSUE THREAD

**Issue by hyun98** [microsoft/vscode#133421]
Issue Type: <b>Bug</b>

Some characters are missing when I type Korean.

VS Code version: Code 1.60.1 (Universal) (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id d5f8e7b3-a61e-4c51-9b8c-56cb107f1c29|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.13.0
vscode-django|bat|1.6.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
python-extension-pack|don|1.6.0
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.5
gc-excelviewer|Gra|3.0.44
CppSnippets|har|0.0.15
vsc-python-indent|Kev|1.14.2
MagicPython|mag|1.1.0
vscode-docker|ms-|1.16.1
vscode-language-pack-ko|MS-|1.60.4
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
cpptools|ms-|1.6.0
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-pg|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
material-icon-theme|PKi|4.10.0
django-snippets|Sid|0.0.4
vscode-djaneiro|the|1.4.2
python|tht|0.2.3
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by rebornix** [comment]
@hyun98 can you share a recording of what you ran into and could you also share the Input Method you are using?

**Comment by hyun98** [comment]
> @hyun98 can you share a recording of what you ran into and could you also share the Input Method you are using?

Thank you for your interest. The problem has been solved.
