### ISSUE TITLE
Terminal not displaying characters

### ISSUE THREAD

**Issue by DiXcipuli** [microsoft/vscode#133440]
In the terminal, lets say I type "a", then nothing will get displayed, then I ll type "z" and the "a" will be displayed etc.. There is always an offset of one character, which is quite annoying. Switching to another window (like a file or internet browser) and switching back to Vscode will make it work for a while, but then, 5 seconds later the behavior will be the same.
The behavior is also the same with arrow keys and the history.

- VS Code Version: 1.60.1
- OS Version: Jetson Xavier NX Ubuntu 18.04

**Comment by ivanvoznyakovsky** [comment]
On macos it's simply blank. nothing shows up at all

**Comment by alexanderniebuhr** [comment]
might be related to, not sure
https://github.com/microsoft/vscode/issues/133435

**Comment by DiXcipuli** [comment]
@Tyriar would you have any news on that? I have absolutely no settings related to the terminal in settings.json, and still have the issue explained above on my machine with the 1.62.0 ARM64 version.

**Comment by Tyriar** [comment]
@DiXcipuli this issue was related to the terminal cursor style setting and is fixed. If you're seeing another problem you should create a new issue with relevant info https://github.com/microsoft/vscode/wiki/Terminal-Issues#creating-great-terminal-issues
