### ISSUE TITLE
Using @ in Razor Page .cshtml in Visual Code

### ISSUE THREAD

**Issue by abdollahkahne** [microsoft/vscode#133559]
Issue Type: <b>Feature Request</b>

When I try to use `@{ `in Razor Page to switch the context to c#, The IntelliSense feature replace it with `@__o{` which is not Intended. It would be great to resolve this. 
Thanks in advance
![image](https://user-images.githubusercontent.com/48277995/134236177-5be5cf66-2c8d-4727-9db3-87c432d18438.png)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.11.0-34-generic
Restricted Mode: No

**Comment by aeschli** [comment]
Please file this against https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks a lot!
