### ISSUE TITLE
File Filtering

### ISSUE THREAD

**Issue by PilotCoder6627** [microsoft/vscode#133581]
Issue Type: <b>Feature Request</b>

You know, can VSCode Groupe add a feature that I can view some file after filtering in the file manage window(left side), for example, only view .cpp files.Thanks.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Have you discovered https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree there?

**Comment by PilotCoder6627** [comment]
I mean add a filter, not just a search

**Comment by JacksonKearl** [comment]
This link @gjsjohnmurray provided shows what I'd call a filtering. For instance I can see this:
![image](https://user-images.githubusercontent.com/8586769/134560905-7e20c191-8eda-4f86-aa13-62d8562af784.png)
or this:
![image](https://user-images.githubusercontent.com/8586769/134560935-e595e560-1577-4de2-818d-6a4d955f42aa.png)
