### ISSUE TITLE
Allow swapping out letterpress image in empty workbench background

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/vscode#133530]
Not sure if it's possible or if there's already a request, but a search leads to no relevant results. While vscode has file icon themes, it doesn't look like the logo in the empty workbench can be customized (unless you hack into `workbench/browser` in the installed application bundle):

![image](https://user-images.githubusercontent.com/55398995/134182246-34bd4b39-05b2-4ebc-b3be-b42669ea70ed.png)

Would it be possible to add a config option or allow extensions to swap out this image? Are there branding / stability concerns?

**Comment by misolori** [comment]
> Would it be possible to add a config option or allow extensions to swap out this image? Are there branding / stability concerns?

When it comes to branding we don't allow this to be configurable. This applies to the product icon appearing in as a file icon (welcome screen and release notes) as well as in the title bar on Windows/Web. Because of this I'll mark this as out of scope. Appreciate the request though.

**Comment by Josh-Cena** [comment]
Okay, thanks for the clarification, makes sense :D
