### ISSUE TITLE
Integrated terminal doesn't start and the terminal controls on the top right of the panel don't work

### ISSUE THREAD

**Issue by nksaraf** [microsoft/vscode#133534]
Does this issue occur when all extensions are disabled?: Yes

Happening in both:

Version: 1.61.0-insider
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T05:14:38.053Z (1 day ago)
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.5.0

Version: 1.60.1 (Universal)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.5.0

Steps to Reproduce:

The integrated terminal doesn't start and the terminal controls on the top right of the panel don't work

Happening in both versions of VSCode on my computer. Recently started happening. I checked the developer tools console and found this error every time this happens. 

<img width="1117" alt="Screen Shot 2021-09-21 at 8 17 52 PM" src="https://user-images.githubusercontent.com/11255148/134193299-fe5d2a9f-b4d8-44af-a8aa-de6477b6d147.png">

**Comment by gjsjohnmurray** [comment]
Please update to today's Insiders and re-test.

**Comment by nksaraf** [comment]
Same thing happening with:
Version: 1.61.0-insider
Commit: 1b9403cd461c9c975bcb9e48d84ba9e4ea86559e
Date: 2021-09-21T08:57:27.561Z (7 hrs ago)
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.5.0
