### ISSUE TITLE
Typescript server died 5 time within 5 minutes

### ISSUE THREAD

**Issue by RadhiRasho** [microsoft/vscode#133533]
Issue Type: <b>Bug</b>

A warning popped up saying that the typescript language server died 5 times within 5 minutes.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.78GB free)|
|Process Argv|--crash-reporter-id 49cbc9ee-2ef5-4e42-832d-6efd50ff8438|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.9.1
pgformatter|bra|1.17.0
npm-intellisense|chr|1.4.0
format-json|Cle|1.0.2
vscode-css-modules|cli|0.3.2
bracket-pair-colorizer-2|Coe|0.2.1
vscode-redis-client|cwe|1.2.8
vscode-eslint|dba|2.1.25
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.22
vsc-material-theme|Equ|33.2.0
prettier-vscode|esb|9.0.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
copilot|Git|1.4.2730
vscode-mocha-test-adapter|hbe|2.13.0
vscode-test-explorer|hbe|2.21.1
svg|joc|1.4.10
fluent-icons|mig|0.0.12
vscode-docker|ms-|1.17.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
test-adapter-converter|ms-|0.1.2
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.10.0
vscode-thunder-client|ran|1.9.1
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
vscode-pets|ton|1.8.1
vscode-icons|vsc|11.6.0
quokka-vscode|Wal|1.0.401
vscode-import-cost|wix|2.15.0
material-theme|zhu|3.11.4

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share information about how to reproduce this so we can investigate /needsMoreInfo

**Comment by mjbvz** [comment]
Closing as not actionable without more information about the issue or how to reproduce it
