### ISSUE TITLE
marketplace extensions cannot connect 

### ISSUE THREAD

**Issue by Stimea87** [microsoft/vscode#133523]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.60.1
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open VS Code
2. Try to search in marketplace

I'm very new at VSCode and I need some help with it.
As I open the VSCode, i got the following error. I tried to use it at home, at corporation non of them worked. We dont use proxy. I have a basic firewall on the computer. I tried a lots of settings forexample this one: https://github.com/microsoft/vscode/issues/106342 and this one https://github.com/microsoft/vscode/issues/106341

Nothing helped.  

 [error] net::ERR_TUNNEL_CONNECTION_FAILED: Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

In developer tools i got the following error too : 
(failed)net::ERR_TUNNEL_CONNECTION_FAILED

![2021-09-21 14_00_03-](https://user-images.githubusercontent.com/91130467/134166781-e0952f8f-255c-42f8-92ef-57eeee1f9e69.png)

I'm very new at VSCode and I need some help with it.
Thank you!

**Comment by Stimea87** [comment]
It says net::ERR_TUNNEL_CONNECTION_FAILED to a simply vscode check for updates..
![2021-09-21 21_09_56-Welcome - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/91130467/134232874-833a6e4f-1112-439e-9821-4398fd5295c5.png)
 :/

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by Stimea87** [comment]
I started it with the --log-net-log=netlog.json but I couldn't find any netlog.json file. I have the following log in the commandline.

![image](https://user-images.githubusercontent.com/91130467/134630764-3c7b7757-16b0-49cb-8e27-b478b1678ff1.png)

**Comment by chrmarti** [comment]
@Stimea87 Not sure what the default is, could you try an absolute path?

**Comment by deepak1556** [comment]
Relative paths are allowed for `--log-net-log` switch, @Stimea87 the file will be created only after you have exited the application.
