### ISSUE TITLE
Regex for empty lines ending with \n should highlight only empty lines

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#13355]
Steps to Reproduce:
- Search for regex for empty line `^\s*$\n`
- Use `Enter` to navigate matches

Expected: Only empty lines should be highlighted
Actual: Empty line and its next line are getting highlighted

**Comment by Bill-Stewart** [comment]
Regex can be shortened to `^$\n` - reproduced here also - should match empty line followed by a newline. However I am wondering what the use case is - why not just `^$` (why trailing newline)?

**Comment by sandy081** [comment]
@Bill-Stewart I have the same question asked in #11572. For empty lines you do not need `\n` at the end of the reg ex. But with above regex I see some inconsistency between selected matches and line highlights. I will investigate why is this difference occurring.

Thanks

**Comment by Bill-Stewart** [comment]
I agree the behavior seems puzzling. It seems that the match should not include the end of non-empty lines.

**Comment by therealmarv** [comment]
@sandy081 this seems for me fixed on 1.9.0

**Comment by sandy081** [comment]
@therealmarv I still see it in insiders

![kapture 2017-02-06 at 7 42 24](https://cloud.githubusercontent.com/assets/10746682/22637039/dac2c33a-ec3f-11e6-986c-db22d22bd21a.gif)

**Comment by therealmarv** [comment]
sorry! Thanks for the gif. I've first thought of marking instead of highlighting. So this is a pure cosmetic problem. btw. searching, editing (like removing) all this empty lines e.g. with multi cursor works.
