### ISSUE TITLE
Test: Terminal process revive

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133516]
Refs: #131634, #133512

- [x] macOS @bpasero
- [x] linux @deepak1556
- [ ] windows @karrtikr
- [x] wsl @rchiodo

Complexity: 4
Authors: @Tyriar, @meganrogge 
Roles: Developer, Engineering Manager

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133516%0A%0A&assignees=Tyriar,meganrogge)

---

When terminal processes are torn down when shutting down a window or the application it's now possible to store the buffer contents, restore it and "revive" the terminal process. The way this works is when closing a window it's evaluated whether this should persist, if so all relevant details are stored to disk and then when the same workspace is loaded, when the pty host connection is established the old processes are re-launched and then reconnected to using the same mechanism that regular process reconnection on window reload uses.

The settings that drive this feature:

- `terminal.integrated.persistentSessionReviveProcess`: Whether to revive on application exit, window close or disable.
- `terminal.integrated.persistentSessionScrollback`: The amount of buffer data to store

Here are some test cases to get you started:

- Note that terminal editors do not currently support process revive https://github.com/microsoft/vscode/issues/133512
- Test each `terminal.integrated.persistentSessionReviveProcess` setting value
- Test in single folder and multi-root workspace
- Fill the buffer and trigger process revive
- Open the alt buffer (eg. run `vim` or `tmux`) and trigger process revive, the alt buffer should _not_ be restored but whatever was in the normal buffer before opening vim should be. Note that on Windows this can end off looking wrong due to how conpty works for example the below shows a revive of a terminal with the process tree pwsh -> wsl -> vim:
  ![image](https://user-images.githubusercontent.com/2193314/134158337-b5778a70-0a6e-496c-99c8-b88abd18e86d.png)
  We cannot easily detect this case though so it's by design currently.
- The amount of lines restored should be controllable via the `terminal.integrated.persistentSessionScrollback` setting
- Window reload process reconnect should still work
- Process revive should restore buffer contents when the application is shutdown due to a config change (eg. change `update.mode`). Note regular process reconnect can't work here because the whole application is taken down in case the setting change affects the main/shared proc.
- Make sure the session restored message looks good on various themes
- Feedback on the setting and feature name is welcome

**Comment by karrtikr** [comment]
> the buffer contents, restore it and "revive" the terminal process
> Fill the buffer and trigger process revive

I'm not clear on what "buffer" and "terminal process" means from user's perspective, can you clarify? An example of a process I can launch, or how to "fill the buffer" would help.

For me as long as `terminal.integrated.enablePersistentSessions` is set to `true`, whatever I type or launch in the terminal is restored even on VSCode stable, so I'm not sure what that means.

**Comment by meganrogge** [comment]
@karrtikr sorry for the confusion. 

buffer just means terminal input and output
terminal process means anything running in the terminal - `yarn watchd` for example
