### ISSUE TITLE
"Show Hover" does not show docstring when inside parenthesis

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/vscode#133556]
## Environment data

- VS Code version: 1.40.2
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.3
- Type of virtual environment used: conda
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): true

## Expected behaviour
For example code `print()`, if `|` is the flashing cursor, then with `print(|)`, `Show Hover` (`Ctrl + K, Ctrl + I`) should produce the docstring.
## Actual behaviour
Nothing happens. The marker must be placed at `print|()` or elsewhere among the letters in order to show the docstring.

## Steps to reproduce:
1. Paste `print()` into the code editor
2. Place the cursor into the paranthesis -> `print(|)`
3. Press `Ctrl + K, Ctrl + I` or press `Ctrl + Shift + P` and type `Show Hover`

**Comment by jrieken** [comment]
> Transferring this to VS Code to see if there should be a Show Signature command.

There is one: "Trigger Parameter Hint `Shift+Cmd+Space`
