### ISSUE TITLE
If the name of the extension is too long, the name will be lost in the extension page

### ISSUE THREAD

**Issue by mochi-sann** [microsoft/vscode#133579]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.60.1
- OS Version: Mac OS 11.6

Steps to Reproduce:

1. Show extensions with long names, such as https://marketplace.visualstudio.com/items?itemName=Mikael.Angular-BeastCode, in VSCode.
2.As shown in the image below, the name of the extension is missing in the middle.

<img width="1634" alt="screenshot 2021-09-22 14 29 25" src="https://user-images.githubusercontent.com/44772513/134288180-3694f497-2678-4e6c-a4ee-5213dcb8c1af.png">

**Comment by sandy081** [comment]
We are sorry that we do not encourage such long names and we trim it and show that fits.
