### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by HeroesOfBalkan** [microsoft/vscode#133569]
Issue Type: <b>Bug</b>

I was using Visual Studio Code for about 1 year, with a problem that every symbol and word that is not a keyword of specific language is white. I was preparing this program specially for C programming, and since then this problem is active till this day.

This really annoys me, and it makes my coding way harder.

What I was trying is to uninstall VSC, uninstall every single extension, restarts VSC multiple times after deleting/installing each extension,...

Even Internet is not helping here. All of them are kinda awkward. This problem is applied to every language I use

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.43GB free)|
|Process Argv|--crash-reporter-id ba0404ba-47e0-4c42-b88d-4fe84d413411|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-browser-preview|auc|0.7.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
vscode-html-css|ecm|1.10.2
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
vscode-pull-request-github|Git|0.30.0
CppSnippets|har|0.0.15
c-math-viewer|Hye|1.0.4
c-cpp-flylint|jbe|1.10.2
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|1.1.0
kite|kit|0.147.0
browser-debugger-extension-pack|mag|1.0.0
csharp|ms-|1.23.15
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4836
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
pluralsight|Plu|0.4.2
java|red|0.82.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
sonarlint-vscode|Son|2.2.0
tabnine-vscode|Tab|3.4.27
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by alexr00** [comment]
Can you share a screenshot that illustrates what you're seeing?

**Comment by HeroesOfBalkan** [comment]
I currently don't have any picture, but if I find, I'll send.
It hadn't highlighted variables, constants, instances, objects and
functions. Sometimes it highlights on some places in code.

I have fixed the problem by completely uninstalling VSC as well as its
local files, then start fresh install. For now, it works fine.

čet, 23. sep 2021. 11:21 Alex Ross ***@***.***> је написао/ла:

**Comment by alexr00** [comment]
Ok, next time you see it a screen shot + a copy/pastable snipped of code that shows the issue would be very helpful.
