### ISSUE TITLE
Can :root be used instead of * for notebook styles?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133555]
I've been seeing this recently which makes me need to scroll more when looking at styles:

![image](https://user-images.githubusercontent.com/2193314/134231812-6a3ceb21-0943-452f-99ee-ffa13234cbaa.png)

I think these can go under `:root`, or another selector which would cause them to be applied to an ancestor and show up down the bottom of devtools. `*` might also be doing slower things in the browser as the style applies to every single dom node, as opposed to just one and being inherited.

**Comment by rebornix** [comment]
@sbatten I think `:root` and `*` would be identical in this case?

**Comment by sbatten** [comment]
@rebornix I think that should work
