### ISSUE TITLE
Devcontainer link-clicking incorrectly unescapes special characters

### ISSUE THREAD

**Issue by anchpop** [microsoft/vscode#133551]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1 
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Open a devcontainer or codespace
2. Get a local server running: `npx local-server`
2. `echo http://localhost:8000/a%2Fb`
3. ctrl-click the link
4. The link, originally `http://localhost:8000/a%2Fb`, will now be something like `http://127.0.0.1:59935/a/b` Note that the `%2F` has been changed to `/`.

**Comment by alexr00** [comment]
@anchpop I tested on Windows and Ubuntu, but I wasn't able to reproduce the issue. Do you have any extensions installed? They can provide terminal links too and may be the culprit.
