### ISSUE TITLE
Rendered as object Object when markdownDescription is used in the extension feature contributions

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#133583]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.61.0-insider 8d2a6fa12466c488f732b020298bc836636c5b17
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

1. Search Prettier in Extensions tab
2. Click Prettier - Code formatter, then click Feature Contributions

![Insiders](https://user-images.githubusercontent.com/1955233/134307805-f08cc2db-1b26-4de1-a5b2-e8fe2a07ecb7.png)

![Stable 1.60.1](https://user-images.githubusercontent.com/1955233/134307863-d4761c4e-d2c4-4799-90ef-22e1dabfa724.png)

The stable version renders it as Markdown

https://github.com/prettier/prettier-vscode/blob/80cb558846165b329635c07d177d496e6779ca1e/package.json#L157

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/88927
