### ISSUE TITLE
Add support for multi-paragraph doxygen comments

### ISSUE THREAD

**Issue by agnickolov** [microsoft/vscode#133573]
At present VS Code squashes all paragraphs of a multi-paragraph doxygen comment into a single paragraph when displaying tool-tips. It does not even add spaces between the squashed sentences. It should instead honor blank lines in the comment and thus preserve paragraph boundaries.

**Comment by mjbvz** [comment]
Please share example code and  describe the expected behavior for it

Also, do other tools handle this differently? 

/needsMoreInfo
