### ISSUE TITLE
SVC Sync Button Only Shows In Multi-Root Workspaces

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#133588]
This is how Git support looks in multi root workspaces, and I like it:
![image](https://user-images.githubusercontent.com/2931520/134327887-4b9d73db-2000-43f0-a187-29438431dfbd.png)

However, when only a single root is opened, it looks like some features are missing:
![image](https://user-images.githubusercontent.com/2931520/134327998-8b29cb18-bbb8-4f18-b9d3-a87f53e80f44.png)

In particular, the branch is not shown and the sync button is missing.

**Comment by gjsjohnmurray** [comment]
@hediet There is a setting that will solve this for you by displaying the header even if there is only one repo.

**Comment by hediet** [comment]
> There is a setting that will solve this for you by displaying the header even if there is only one repo.

Thanks for the pointer! The setting is `"scm.alwaysShowRepositories": true`.

But why is it false by default?

**Comment by gjsjohnmurray** [comment]
> But why is it false by default?

Historical I assume. Anyway, when false you can always use the status bar item to sync or switch branch.

**Comment by hediet** [comment]
I just discovered that the sync button is rendered in the status bar.
Somehow, I totally missed that.
