### ISSUE TITLE
"Session content restored" message keeps old theme

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133543]
When I change themes, the "session content restored" message in my terminal always has the colors of the old theme, even when the rest of the terminal content is able to adapt.

![image](https://user-images.githubusercontent.com/323878/134214625-1dd3a426-ea45-4fe6-83ef-61f3b685836c.png)

**Comment by meganrogge** [comment]
The color of the message is now static, so you won't encounter this issue. https://github.com/microsoft/vscode/issues/133496#issuecomment-923890191

**Comment by Tyriar** [comment]
@roblourens your screenshot actually shows it reacting to theme changes and now it's static, just a less extreme grey color.
