### ISSUE TITLE
I've disabled all online features could find, but VSCode still try to connect to internet

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#133582]
Does this issue occur when all extensions are disabled?: Yes

- OS Version: Win10

Steps to Reproduce:

1. settings.json
```
		"extensions.autoCheckUpdates": false,
		"extensions.autoUpdate": false,
		"http.proxyAuthorization": null,
		"javascript.suggestionActions.enabled": false,
		"json.schemaDownload.enable": false,
		"npm.fetchOnlinePackageInfo": false,
		"settingsSync.keybindingsPerPlatform": false,
		"telemetry.enableCrashReporter": false,
		"telemetry.enableTelemetry": false,
		"typescript.disableAutomaticTypeAcquisition": true,
		"typescript.suggestionActions.enabled": false,
		"update.enableWindowsBackgroundUpdates": false,
		"update.mode": "manual",
		"update.showReleaseNotes": false,
		"workbench.enableExperiments": false,
		"workbench.settings.enableNaturalLanguageSearch": false
```
2. On launch, and occasionally, it tries to connect to Microsoft servers . (when no update or other such actions is performed by user)

**Comment by lramos15** [comment]
@irvnriir Could you please provide the URLs it is trying to connect to if you have them as that will help us narrow down which service is still being hit.

**Comment by irvnriir** [comment]
@lramos15 its tries to TCP port 443 on different IPs . A Network tab in Developer Tools shows only `vscode-file:` and `data:` items .

**Comment by irvnriir** [comment]
I've also just found `https://ticino.blob.core.windows.net` in `Developer Tools \ Customize and control DevTools \ More tools \ Developer Resources`, but idk what the tab means .

**Comment by lramos15** [comment]
Thanks for the information, if you could also provide those IPs I can look to see which services they're hitting.

**Comment by irvnriir** [comment]
```
51.144.164.215
152.199.19.160
```

**Comment by lramos15** [comment]
I did investigate this and we currently see two requests being sent with these settings and are working to address them.
1. We ask the update service if you're on the current version
2. When we initialize the telemetry modules they make an "is the endpoint alive check" which is just an empty request with nothing in it. No telemetry is sent throughout the session but that's what you're seeing.

**Comment by sbatten** [comment]
For the update service issue:

@jrieken's suggestion is for the update service to honor any offline settings, thus assigning to @joaomoreno. Though, I do understand that the update mode setting and what is expected are at odds here and there is difficulty in knowing the returned value for isLatestVersion(). Perhaps we should just return undefined and consumers can compensate.

**Comment by lramos15** [comment]
@joaomoreno @jrieken Marking this as important because we're not respecting the setting description.

**Comment by joaomoreno** [comment]
As I told @sbatten on Slack:

> I see that being called from these two:
> 
> - [startupTimings.ts](https://github.com/microsoft/vscode/blob/66a1a51a07a299dbe00583030aa74b7718fb0683/src/vs/workbench/contrib/performance/electron-sandbox/startupTimings.ts/#L117)
> - [timerService.ts](https://github.com/microsoft/vscode/blob/66a1a51a07a299dbe00583030aa74b7718fb0683/src/vs/workbench/services/timer/browser/timerService.ts/#L562)
>
> Both have nothing to do with the update service. I suggest reaching out to @jrieken and/or see if there's a setting to disable the features these files bring in

**Comment by lramos15** [comment]
@joaomoreno But this is an update service setting so shouldn't the update service just return undefined in the case where the setting is set to off or manual. The user isn't requesting an update when this function is being called

**Comment by joaomoreno** [comment]
The update setting controls the feature to check for updates. The startup timings and the timer service have nothing to do with that. They purely use the _inner_ update service to know whether they are the latest or not. They need to have a setting to disable that behavior.
