### ISSUE TITLE
/usr/bin/bash: [path without slashes]: command not found typescript project

### ISSUE THREAD

**Issue by justusbotlabsgg** [microsoft/vscode#133527]
Issue Type: <b>Bug</b>

After updating to 1.60.1 my typescript project stopped compiling when it was working fine before.  It fails to debug or build.

Here is my launch.json:
```
{
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "preLaunchTask": "tsc: build - tsconfig.json",
            "program": "${workspaceFolder}/dist/arbi.js",
            "outFiles": [
                "${workspaceFolder}/**/*.js"
            ],
            "sourceMaps": true,
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**"
            ]
        }
    ]
}
```

And here is my error when building or trying to debug:
> Executing task: c:\Users\Justus\Documents\GitHub\Arbi\node_modules\.bin\tsc.cmd -p c:\Users\Justus\Documents\GitHub\Arbi\tsconfig.json <

/usr/bin/bash: c:UsersJustusDocumentsGitHubArbinode_modules.bintsc.cmd: command not found
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'c:\Users\Justus\Documents\GitHub\Arbi\node_modules\.bin\tsc.cmd -p c:\Users\Justus\Documents\GitHub\Arbi\tsconfig.json'" terminated with exit code: 127.

I notice the "command" has all the slashes removed and I assume this is part of the problem.  The only thing I can think of that haschanged was doing the update of vscode.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (8.02GB free)|
|Process Argv|--crash-reporter-id f58bf5c4-06ed-4f69-ab16-db2823332ea7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.29.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by justusbotlabsgg** [comment]
I did change the default terminal back to cmd.exe and can at least build and debug now.

**Comment by roblourens** [comment]
It looks like you were trying to run a windows command in a bash terminal
