### ISSUE TITLE
cwdFolder is showing when in the same root

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133539]
Repro:

1. Open a WSL folder
2. Create a terminal, notice the cwd's folder is showing, it shouldn't because it's the default 🐛 
3. `cd src`, it shows ✔️ 
4. `cd ..`, it shows 🐛

**Comment by meganrogge** [comment]
still seeing this

**Comment by meganrogge** [comment]
this is also happening in windows now too which it shouldn't be
