### ISSUE TITLE
Period causes autocomplete to be accepted

### ISSUE THREAD

**Issue by mkahvi** [microsoft/vscode#133565]
Issue Type: <b>Bug</b>

In Javascript, try to use ellipsis for filling arrays, such as [...oldArray, ...otherOldArray], instead the autocomplete will completely garble the intended code since each period will accept the autocomplete and fill it in.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (33.55GB free)|
|Process Argv|--file-uri file:///n%3A/WebForge/transient/.vscode/transient.code-workspace --crash-reporter-id a760b153-9a2a-48a0-a874-aa79caeadef8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
spellright|ban|3.0.60
path-intellisense|chr|2.4.0
vscode-eslint|dba|2.1.25
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-language-babel|mgm|0.0.35
formate|Mik|1.1.6
test-adapter-converter|ms-|0.1.2
vscode-typescript-next|ms-|4.5.20210920
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
synthwave-vscode|Rob|0.1.8
ActiveFileInStatusBar|Ros|1.0.3
strict-whitespace|sid|0.0.2
code-spell-checker|str|2.0.6
errorlens|use|3.4.0
vscodeintellicode|Vis|1.2.14
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment]
Description is cryptic but looks similar to #130096

Is it what you are seeing? What TS version are you using?

**Comment by mkahvi** [comment]
Only version I can find for TS is 4.5 from nightly that I'm using, which looking at the other issue probably isn't right. But it does look to be the same issue. Sorry for duplicate report, I'm not so great with the terminology.
