### ISSUE TITLE
Regex Engine can't recognize carriage return in find menu

### ISSUE THREAD

**Issue by watermagpie** [microsoft/vscode#133557]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: Windows 10 21H1, Korean Version.

Steps to Reproduce:

1. regex ```\r\n\r\n\r\n``` doesn't work between search menu/search toolbar in file viewer

![image](https://user-images.githubusercontent.com/61748622/134229530-d188fcde-702a-4494-b5a8-6fc76d85186e.png)

As this screenshot, search menu can find regex ```\r\n\r\n\r\n``` properly, but search toolbar do not work.

2. But, if I remove carriage return ```\r```, It works properly.

![image](https://user-images.githubusercontent.com/61748622/134229853-88cb9b07-bc31-4453-8da8-78e7b061bd37.png)

3. And, It sometimes works weird, like this.

![image](https://user-images.githubusercontent.com/61748622/134231920-e10f517f-3551-45b4-b35b-24fe20f85c54.png)

I made brand new file for test. (I think you can test it same way with your own PC)

![image](https://user-images.githubusercontent.com/61748622/134231711-fd9e0c8e-ac09-499a-b426-0526bd03ac9a.png)

If the file hasn't open in vsc, vsc can find carriage return properly.

![image](https://user-images.githubusercontent.com/61748622/134231984-9c6fdae6-8b0a-4b4b-b75a-6fb7278c8cb3.png)

But when I open it, just messed up.

**Comment by IllusionMH** [comment]
Find (in editor, also used for open editors during Find in Files) uses JS engine and normalized text for editor (without `\r`).

So easier workaround to use `\r?\n` as "universal" approach or close open editors if `\r`is crucial.

Not sure if there are plans to force ripgrep on files even if they are in open editors.

As for `\r` in editors - see #19864

**Comment by roblourens** [comment]
Yes, thanks @IllusionMH for the link, this is tricky an inconsistent case between the editor's search and workspace text search.

**Comment by watermagpie** [comment]
> Find (in editor, also used for open editors during Find in Files) uses JS engine and normalized text for editor (without `\r`).
> 
> So easier workaround to use `\r?\n` as "universal" approach or close open editors if `\r`is crucial.
> 
> Not sure if there are plans to force ripgrep on files even if they are in open editors.
> 
> As for `\r` in editors - see #19864

Thanks for your help!
