### ISSUE TITLE
Terminal issue with certain keystrokes after single or double quote

### ISSUE THREAD

**Issue by ghvanderweg** [microsoft/vscode#133597]
Issue Type: <b>Bug</b>

After I type a single or double quote (`'` or `"`) in the terminal and want to follow that up with either an arrow key, Delete, Backspace or Enter keystroke, the first of those keystrokes is "swallowed" and doesn't seem to register.
I need to double that next keystroke to make it work (a combination also works, so an arrow key followed by Enter, for example).

Possibly (probably?) relevant: I'm using the English (Netherlands) locale with the United States-International QWERTY keyboard, which allows me to type a single or double quote followed by a vowel to generate characters like `ë`, `é` and `ï`. To generate a single or double quote by itself, I type `'` or `"` followed by Space. After that, I'm in the bugged state.

This problem started in one of the most recent versions of VS Code, but I'm not sure when exactly.

I've tried running VS Code with extensions disabled, the result is the same. It also happens regardless of whether I'm using cmd.exe, bash or PowerShell in the terminal.

**How to reproduce**
1. Open a Visual Studio Code terminal
2. Type a `'` or `"` (followed by a space, to make it appear)
3. Hit an arrow key, Enter, Backspace or Delete and observe that nothing happens
4. Hit an arrow key, Enter, Backspace or Delete again, this should work

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.40GB free)|
|Process Argv|--crash-reporter-id e6d382bf-7aa6-4f5c-8abc-384c1dc12a05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
codesnap|adp|1.3.4
vscode-markdownlint|Dav|0.44.1
gitlens|eam|11.6.0
json-tools|eri|1.0.2
vscode-diff|fab|1.4.2
theme-monokai-pro-vscode|mon|1.1.19
azure-pipelines|ms-|1.191.0
vscode-azurefunctions|ms-|1.5.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.15
vscode-dotnet-runtime|ms-|1.2.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
powershell|ms-|2021.9.0
azurerm-vscode-tools|msa|0.15.2
highlight-dodgy-characters|nac|1.0.0
material-icon-theme|PKi|4.10.0
cron-explained|tum|1.3.1
errorlens|use|3.4.0
arm-params-generator|wil|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
dockerwalkthru:30369615
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by meganrogge** [comment]
I can't reproduce this, so I believe your QWERTY keyboard is relevant

**Comment by SjoerdV** [comment]
I have the same issue. It's definatly not the keyboard because the same procedure works right in the code editor itself.
type `"` -> `"` -> `Arrow Left` (THIS IS SWALLOWED) -> `Arrow Left` (CURSOR GOES IN BETWEEN DOUBLE QUOTES)

**Comment by ghvanderweg** [comment]
@meganrogge I don't agree with closing this issue as not-reproducible. Have you tried setting your keyboard & localization the same as mine and @SjoerdV? 

The VS Code terminal is the only place this weird behaviour occurs. In the editor it works fine, in Windows Terminal it works fine, in every other program I've tried it works fine, and it used to work in the VS Code terminal as well.

It's very annoying, and being told it's not reproducible without further comment feels dismissive to be honest.

**Comment by tairosonloa** [comment]
Same here. ANSI keyboard with an English (Unite States - International) layout on a Spain-Spanish (ES-ES) locale system.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/3573
