### ISSUE TITLE
Run Test at Cursor and Gutter icons handle multiple tests inconsistently

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#133519]
With dynamic tests, it's possible for the test tree to end up with multiple nodes that have the same range (here, `danny $i`, `danny 1` and `danny 2` are all the same range - the latter two are runtime instances of the `danny $i` dynamic test).

![Screenshot 2021-09-21 at 11 43 51](https://user-images.githubusercontent.com/1078012/134157317-e536f0d4-2a1b-4a14-88fd-f4186815ee2e.png)

When clicking on the gutter icon on line 19, VS Code calls `runTests` and passes a `TestRunRequest` that includes all three nodes. Running the first node (`danny $i`) will already run the other two tests, so I'm able to remove them and run just a single test session that results in both tests running.

However, if I run "Run Test at Cursor", `runTest` is called with a `TestRunRequest` that includes only _the very last node_ covering that range. In this case, that's `danny 2` and thus only that test runs. I can't tell the difference between the user running Run Test at Cursor and explicitly clicking the Run icon next to that test in the tree, so I have no way to resolve this.

It seems like this behaviour should be consistent. Run Test at Cursor should do the same thing as clicking the gutter icon for the test the cursor is in. This probably means it should pass all tests that have same range (or start point, or start line) as the first test found.

**Comment by connor4312** [comment]
Good find
