### ISSUE TITLE
Show folder for tabs with same file if opened in another group

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#13350]
- VSCode Version: 1.6.0-insider
- OS Version: OSX 10.11.6

When I open two files with identical file names in one group I get the folder path as expected:
<img width="1603" alt="screen shot 2016-10-07 at 15 43 23" src="https://cloud.githubusercontent.com/assets/5306662/19192590/0404c110-8ca7-11e6-830d-4aeb63b7c93b.png">

As soon as I split my workbench into two groups and put the files into different groups, the folder information disappears:
<img width="1603" alt="screen shot 2016-10-07 at 15 43 41" src="https://cloud.githubusercontent.com/assets/5306662/19192648/37b651ea-8ca7-11e6-87fe-bfea84d15788.png">

**Comment by Tyriar** [comment]
@bpasero by design or oversight?

**Comment by bpasero** [comment]
By design.

**Comment by bgashler1** [comment]
I don't have any data to back this up per-se, but I would think it would make sense to leave this on even after splitting.  I think even if it's split that it's not clear where each file is living.  Just my opinion though, not complaining :)

**Comment by brettjashford** [comment]
+1 for maintaining this behavior across groups.

**Comment by leocaseiro** [comment]
The [RoscoP.ActiveFileInStatusBar](https://marketplace.visualstudio.com/items?itemName=RoscoP.ActiveFileInStatusBar) extension is not ideal, but helps for the time being within the focused tab.

**Comment by jberube** [comment]
May I suggest adding a setting to have either:
- the current behavior
- the current behavior, but that checks accross groups
- the full path, always visible

**Comment by bpasero** [comment]
A workaround is to configure the new `workbench.editor.labelFormat` setting. No further work is planned otherwise.
