### ISSUE TITLE
VCS changes are no longer detected automatically

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#133510]
Issue Type: <b>Bug</b>

Previously, changes in files would automatically appear in the VCS panel. This has stopped happening a while ago.

An apparently similar issue has been discussed, and prematurely closed, at #116673. Over there, it is assumed that disabling git auto-fetch (which is disabled by default and disabled on my machine) resolves the problem.

Can't repro without extensions as extensions are required to use WSL.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|79.87GB (31.31GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|62.71GB (5.81GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|62.71GB (5.81GB free)|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
prettier-vscode|esb|9.0.0
output-colorizer|IBM|0.1.2
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-js-profile-flame|ms-|0.0.21
vscode-icons|vsc|11.6.0
vscode-zipfs|arc|2.3.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.18
yarn2-dependency-explorer|hah|0.0.1
terraform|has|2.14.0
vscode-esformatter|how|1.6.0
vscode-random|jre|1.10.0
template-string-converter|meg|0.5.3
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.16.1
vscode-kubernetes-tools|ms-|1.3.3
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
test-adapter-converter|ms-|0.1.2
vscode-js-profile-flame|ms-|0.0.21
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.33
vscode-jest|Ort|4.1.2
vscode-yaml|red|0.22.0

(1 theme extensions excluded)

</details>

**Comment by chrim5** [comment]
I have the same issue working on a Linux machine with remote-ssh.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-305.12.1.el8_4.x86_64
Remote OS version: Linux x64 4.18.0-305.12.1.el8_4.x86_64

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.33GB free)|
|Process Argv|--crash-reporter-id 33f69ef3-977a-4121-8570-23ef70b8f630|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: e1-christenm-alsu001|
|OS|Linux x64 4.18.0-305.12.1.el8_4.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (2 x 2297)|
|Memory (System)|7.59GB (0.20GB free)|
|VM|40%|

|Item|Value|
|---|---|
|Remote|SSH: hostname|
|OS|Linux x64 4.18.0-305.12.1.el8_4.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz (2 x 2297)|
|Memory (System)|7.59GB (0.20GB free)|
|VM|40%|
</details><details><summary>Extensions (13)</summary>
Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.44.3
dotenv|mik|1.0.1
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
jinja|who|0.0.8
gitlens|eam|11.6.0
go|gol|0.28.1
kubernetes-snippets|ipe|0.1.9
vscode-go-template|jin|0.2.1
vscode-docker|ms-|1.17.0
vscode-commons|red|0.0.6
vscode-yaml|red|0.23.0
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis400:30374798
```
</details>

**Comment by yss14** [comment]
I have the same issue working on local git repositories on my M1 MacBook Pro.

VS Code version: Code 1.60.2 (#7f6ab54)
Os version: macOS 11.5.2 (M1 MacBook Pro)

**Comment by jyavorska** [comment]
I have the same issue, though in my case somehow disabling git auto-fetch fixes it. Can't explain why that would be the case, but it does. I'm using mine with WSL2 and the WSL2 extensions.

Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by oliversalzburg** [comment]
@jyavorska Then you seem to experience https://github.com/microsoft/vscode/issues/116673, which is different from this issue.

**Comment by AndreiRacasan** [comment]
I also have the same issue on Linux running on ThinkPad T490.

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-21-generic

**Comment by Orillian** [comment]
Just to add a me too, I started experiencing this issue in late November. About 3 weeks after I upgraded to Windows 11 (completely fresh install)

This fix mentioned above in #116673 does not work as I'm set to the default(false) already.

**Comment by lucaspompeun** [comment]
Any news from this issue? I'm still with the same problem!

**Comment by deciacco** [comment]
> I have the same issue, though in my case somehow disabling git auto-fetch fixes it. Can't explain why that would be the case, but it does. I'm using mine with WSL2 and the WSL2 extensions.
> 
> Version: 1.62.1 (user setup) Commit: [f4af3cb](https://github.com/microsoft/vscode/commit/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f) Date: 2021-11-05T10:57:55.946Z Electron: 13.5.2 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22000

same for me, fresh install of windows and vscode on wsl2... enabled auto-fetch and noticed source control not showing changes automatically. disabled it and changes now show up... very strange.

Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by oliversalzburg** [comment]
@deciacco 
> enabled auto-fetch and noticed source control not showing changes automatically. disabled it and changes now show up...

If auto-fetch has an impact on this behavior, you're likely experiencing #116673. This issue is specifically about the case where auto-fetch has no impact on the behavior.

**Comment by oliversalzburg** [comment]
I'm not sure if this has gotten worse or if I just didn't notice the extent of this defect yet.

Files changes that were made by external processes are now no longer detected inside VS Code at all. This is not exclusive to VCS, it affects the entire application. Files must be closed and reopened to get the fresh file contents. Folders in the Explorer panel need to be manually refreshed to see updated contents.

**Comment by sharifzadesina** [comment]
Hello,
I am also facing this issue recently.
Any update on this?

**Comment by Orillian** [comment]
Just a heads up for those of you that have not updated. The version that dropped today seems to have fixed this issue for me even though I do not see any details of this fix in the Release Notes.

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by oliversalzburg** [comment]
@Orillian I can confirm that, after installing 1.64, the VCS changes behavior seems to be back to normal. At least for the time being.

**Comment by oliversalzburg** [comment]
Changes in this range changed the behavior: https://github.com/microsoft/vscode/compare/e96a97448aae1572246bf7c438b7c2ee68a964c0...284e0db6c4cac1e557a43cd6691babdaafc2e1a9

Looking at that, the work on the watcher stands out. Wouldn't be the first time that some Windows/Linux detection mistake inside WSL caused VS Code problems.

**Comment by JohnnyHuo** [comment]
> @Orillian I can confirm that, after installing 1.64, the VCS changes behavior seems to be back to normal. At least for the time being.
> 
> Might be a great use for the new `vscode-bisect` :D

I'm using Version: 1.64.2  and experiencing the problem, code refreshed by git pull not synced in VS Code

**Comment by zbs** [comment]
Can also confirm this happens on 1.65 with all extensions disabled. Note that file changes are *correctly* reflected under the **Changes** header; however, if I stage/unstage/commit a file, that is *not reflected*.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.x86_64

**Comment by lszomoru** [comment]
@JohnnyHuo, @zbs could you please file separate issues so that I can look at the issue that you are running into. Thanks!
