### ISSUE TITLE
Allow to define the file extension when reading from stdin

### ISSUE THREAD

**Issue by bkmeneguello** [microsoft/vscode#133562]
Whenever I open a file using the stdin pipe `echo foo | code -` it generates a random file `code-stdin-xxx` in the temporary dir, this is done in the function [getStdinFilePath() here](https://github.com/microsoft/vscode/blob/83bd43bc519d15e50c4272c6cf5c1479df196a4d/src/vs/platform/environment/node/stdin.ts#L39).
I would like to suggest to add a new option, something like `--stdin-file-ext`, which would allow someone to invoke the vscode like this: `echo foo | code --stdin-file-ext=js -` and have in the editor a file `code-stdin-xxx.js`. If the argument is not provided, the current behavior continues the same.

**Comment by bkmeneguello** [comment]
Yeah, this is a possible workaround, but I prefer to avoid the intermediate step. About the full name, it could be a possibility, I just didn't suggest that because the current implementation is more able to avoid naming conflicts, also this naming strategy makes it clear where the file comes from: stdin.

**Comment by joaomoreno** [comment]
cc @bpasero
