### ISSUE TITLE
Setting terminal.integrated.tabs.title isn't showing the title

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133538]
The ones missing the titles were created with `"terminal.integrated.tabs.title": "${process}${separator}${sequence}"` set.

![image](https://user-images.githubusercontent.com/2193314/134211025-b299271c-e646-4a3b-935b-335465d4f048.png)

**Comment by rzhao271** [comment]
I'm wondering how the paths are showing in a smaller font? When I set the setting value to "${process}${separator}${sequence}", the title only displays "bash".

**Comment by meganrogge** [comment]
@rzhao271 are you on windows? if sequence is undefined (it usually is), neither the separator nor the sequence will be shown.

**Comment by rzhao271** [comment]
I think what I meant was the path. I saw the path when I opened a workspace file.
