### ISSUE TITLE
Cannot commit staged changes after conflict resolution

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#133590]
I resolved a conflict, staged the file and wanted to commit. 
However, I get this obscure message:

![image](https://user-images.githubusercontent.com/2931520/134331815-900d524d-2f6c-4fbc-92d9-b975a6222def.png)

Show Command Output is:

```
> git rebase --continue
C:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe: bad option: --wait
error: There was a problem with the editor '"C:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --wait'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
```

Open Git Log shows:

```
C:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe: bad option: --wait
error: There was a problem with the editor '"C:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --wait'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
> git config --get-all user.name
> git config --get-all user.email
> git ls-files --stage -- C:\dev\microsoft\redacted\September 2021.md
> git cat-file -s 5d*************33
> git show --textconv :redacted/September 2021.md
> git status -z -u
> git symbolic-ref --short HEAD
fatal: ref HEAD is not a symbolic ref
> git rev-parse HEAD
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z 5d*************33
```

Even if I did something wrong, I think the error message could be improved.

**Comment by YouthCoder135** [comment]
I am encountering the same issue as above - unable to commit changes, pull, fetch etc..

[2022-02-14T12:06:35.251Z] Too many errors from stdin
error: There was a problem with the editor 'nano.exe'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.

**Comment by Gr33nLight** [comment]
I am encountering the same issue as well, after a conflict resolution, its unable to continue with the commit.

`[2022-03-12T17:51:50.541Z] Error opening terminal: unknown.
error: There was a problem with the editor 'nano'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.`

**Comment by Gr33nLight** [comment]
UPDATE:
I resolved the issue by manually setting vscode as editor from the git config (note this is on macOS)
`git config core.editor "code --wait" `

It was trying to use nano to write the commit message for the conflict resolution, but this was throwing the error.
Hope this helps

**Comment by knittingarch** [comment]
I am able to pull changes and initiate a rebase, but I cannot run `git rebase --continue` without hitting the error above.  Setting VS Code as the editor from the git config did not work for me.

**Comment by willwillman-kr** [comment]
I have similar/same issue as OP (im on mac) 
it appears any time you try to make a commit during a rebase (whether thats to fix conflicts or just doing an interactive)

1. git rebase -i HEAD~10
3. change any commit to edit
4. stage some changes
5. add message
6. click the check mark to commit changes
7. open git output
8." > git rebase --continue [...] Please supply the message using either -m or -F option"
![Screen Shot 2022-05-25 at 10 05 25 AM](https://user-images.githubusercontent.com/79229197/170320418-e686532e-4875-4541-857c-6793649ecc0e.png)
9. stash all commits 
10. click checkmark
11. "there are no changes to commit"
![Screen Shot 2022-05-25 at 10 04 25 AM](https://user-images.githubusercontent.com/79229197/170320516-bc1913ab-5f5a-4f4a-9d93-706eba39105b.png)

almost seems like the logic for the button gets switched for rebase (ie like the check should work to --continue when no commits present and do a normal commit -m when there is commits staged?)

_workaround for me is just to do the `git commit -m "blah" && git rebase --continue` from the terminal_

**Comment by lszomoru** [comment]
Related to https://github.com/microsoft/vscode/issues/114461. 
This issue has been fixed in today's Insiders release (2022-07-21) or later.
Please give it a try and let me know if you are still experiencing the problem. Thank you!
