### ISSUE TITLE
Breakpoints contribution needs to support when clauses

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#133585]
Same as https://github.com/microsoft/vscode/issues/133146

Breakpoints contribution should support `when` clauses.
This should be much simpler though, since we only read the `breakpoints` contribution [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts#L254)
So only when somebody asks us if breakpoints can be set in the model we should make sure that the `breakopints` `when` context evaluates to `true`.

**Comment by roblourens** [comment]
Hopefully it's ok if this doesn't happen until October, I have a lot left on this month

**Comment by isidorn** [comment]
@roblourens of course. This is nothing urgent. We can do it in October. Thanks!

**Comment by isidorn** [comment]
Unassigning myself. Rob let me know if you have too much on your plant and I can also provide a PR. Thanks

**Comment by isidorn** [comment]
@roblourens thanks for tackling this 👏

**Comment by jrieken** [comment]
Verified but could get this to work. What's the minimal debugger contribution that has "UI impact". This didn't seem to be enough

```
"debuggers": [
			{
				"type": "dddddd",
				"label": "dddddebugger"
			}
		]
```

**Comment by roblourens** [comment]
`breakpoints` is a separate contribution point, so you don't need a debugger.
