### ISSUE TITLE
GIT could not be used

### ISSUE THREAD

**Issue by pangxieju** [Microsoft/vscode#13352]
- VSCode Version:1.5.3
- OS Version:windows 10 x64

GIT could not be used.

**Comment by Tyriar** [comment]
This means that git cannot be found in your `PATH` environment variable

**Comment by pangxieju** [comment]
![qq](https://cloud.githubusercontent.com/assets/18155203/19209338/f603466a-8d3a-11e6-97c0-aefeec1489f3.png)

**Comment by Tyriar** [comment]
I don't know your setup but it should probably be `D:\Program FIles\Git\bin`, not cmd

**Comment by pangxieju** [comment]
Oh, thank you! I really appreciate it.
