### ISSUE TITLE
VSCode Git not detecting nested repositories

### ISSUE THREAD

**Issue by studgeek** [microsoft/vscode#133577]
VSCode Git is not detecting nested, non-submodule repositories. For example, given the directory structure a/aa/aaa/aaaa where every level is a git repo, it will only detect the top-level “a”.

### Steps to Reproduce:

The following is with default settings, so `git.autoRepositoryDetection: true`. I see the same result with `openEditors` in which case I think 3-Result is expected, but 4-Result is still unexpected.

#### 1) Create a nested repo structure, with a file at each level.
```
for name in a aa aaa aaa; do
  mkdir "${name}"
  cd "${name}"
  git init
  touch "${name}.txt"
done
```

#### 2) Open vscode on the top level directory
```
code a
```

#### 3-Result)
The Git tab will only show the top repository “a’. See pic 1 below.

#### 3-Expected)
If `git.autoRepositoryDetection` is `true` or `subFolders` then I would expect the Git tab to show `a` and also the nested `aa`, `aaa`, and `aaaa`.

#### 4) In vscode open the file in each nested repo
Open "a/a.txt", "aa/aa.txt", "aaa/aaa.txt", and "aaaa/aaaa.txt".

#### 5-Result)
The Git tab still only shows the top repository “a’. See pic 1 below.
The GitLens tab actually shows all 4 nested repos. See pic 2 below.

#### 5-Expected)
If `git.autoRepositoryDetection` is `true` or `openEditors` then I would expect the Git tab to show`a` and also the nested `aa`, `aaa`, and `aaaa` (like GitLens).

### Version Info
VSCode Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Does this issue occur when all extensions are disabled?: Yes

#### Pic 1 - 3-Result and 5-Result:
![Screen Region 2021-09-21 at 19 02 39](https://user-images.githubusercontent.com/770765/134283244-72da9aaa-52a3-4356-a2d4-c7b1883fff8d.png)

#### Pic 2 - GitLens showing all 4 repos as expected for 5-Expected
![Screen Region 2021-09-21 at 19 03 52](https://user-images.githubusercontent.com/770765/134283342-25a32897-5699-45d9-bbf9-0e79d218a71b.png)

**Comment by geekley** [comment]
Almost an year later, still an issue...? Is this setting completely ignored or what?

**Comment by dbelanger** [comment]
I could really use this feature as well

**Comment by geekley** [comment]
I believe this is fixed now: https://code.visualstudio.com/updates/v1_72#_source-control

**Comment by lszomoru** [comment]
VS Code 1.72 added support for detecting nested git repositories.
