### ISSUE TITLE
Please! Add pinch and control+mouse wheel forward(backwards to zoom out) to zoom in and out.

### ISSUE THREAD

**Issue by GuruTheCoderYoutube** [microsoft/vscode#133525]
I think it is a pretty commonly used shortcut, and I think it should be added to Vs Code by default. I do not find any reason not to. Thanks! BTW, VS CODE IS AWESOME, I have nothing against it, just a tiny request.

**Comment by sbatten** [comment]
@GuruTheCoderYoutube see this setting: `editor.mouseWheelZoom` and let me know if this is what you are looking for.

**Comment by GuruTheCoderYoutube** [comment]
I do know that and have enabled that. But I think it should be made the default as it is pretty intuitive.

**Comment by sbatten** [comment]
cc @rebornix
