### ISSUE TITLE
"Path must be a string. Received null" when debugging node

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#13365]
- VSCode Version: 1.6.0-insider 98c935
- OS Version: Windows 10

Steps to Reproduce:

1. Use "attach" to attach to a mocha debugging process run using `--compilers js:babel-core/register`

I guessed this is related to `launch.json` parsing based on [https://github.com/Microsoft/vscode/issues/3625] but I can't seem to work around it. I had 

    "outDir": null

before (since it's not relevant when I attach to a mocha debugging process, as the code is compiled JIT and there is no outDir). There was a complaint in the IDE about it, so I changed it. Still getting the error. I don't have any other warnings in `launch.json` so I'm at a loss as to how to work around it. 

			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/dist"

I saw a suggestion to look at the "dev tools console" in VS Code to see a stack trace of the source of the problem from the linked issue above. I can't find any "dev tools console" in either the menus, and couldn't find anything by googling it. If you can tell me how to access this I can provide more info.

*Update*

I regenerated `launch.json` from scratch to be sure my old config wasn't invalid. Same problem. So no idea what's causing it.

**Comment by Tyriar** [comment]
@jamietre to get to the console go to Help > Toggle Developer Tools and then click the console tab up the top. Can you also upload a screenshot of the error if possible?

**Comment by jamietre** [comment]
Thanks! Here's the stack trace that appears relevant, there's another error "Cannot read property 'document' of undefined"

Path must be a string. Received null messageService.ts:128
e.doShow @ messageService.ts:128
e.show @ messageService.ts:107
(anonymous function) @ mainThreadMessageService.ts:55
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

![image](https://cloud.githubusercontent.com/assets/573056/19201382/8cbaecd4-8c9b-11e6-8930-915e84225ff5.png)

**Comment by Tyriar** [comment]
@jamietre I see an error related to an extension, could you run `code-insiders --disable-extensions` and see if it still reproduces?

**Comment by jamietre** [comment]
It goes away when I disable all extensions. However when I disable just the one that appears to be offending here, it doesn't solve anything - I still get the error. The other stack trace "cannot read property "document"" goes away though. But I still get the "Path must be a string. Received null" one same as before.

Buuuuuut.. I did happen to update ESLint today also.  I just uninstalled it, the problem goes away.

So I guess this is an eslint issue.,.

**Comment by Tyriar** [comment]
@dbaeumer fyi this may have had something to do with eslint

**Comment by dbaeumer** [comment]
I have a bug for this in eslint. Bottom line: we have a new node version and old eslint version called path functions with null which in node 6.x now throws. Way out is to use a newer version of eslint.

**Comment by jamietre** [comment]
@dbaeumer I am using eslint@3.7.1 (current) and node 4.4.7 (old) which seems to conflict with this assesment of the source of the problem.

**Comment by jamietre** [comment]
Sorry - vscode is using node 6.5 (I didn't realize vs code/electron apps use their own version of node, which in retrospect makes sense ;). But I am current with eslint already.

**Comment by ramya-rao-a** [comment]
@jamietre Are you saying that you are using the latest version of eslint and are still seeing the issue?

**Comment by ramya-rao-a** [comment]
Ok, closing the loop on this issue and removing the label "bug" as there is nothing to fix anymore
