### ISSUE TITLE
vscode tensorboard  on remote server not able to Download Current Chart as SVG

### ISSUE THREAD

**Issue by ybagdasa** [microsoft/vscode#133683]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When I try to download the scalar charts in TensorBoard by first checking the "Show data download links" box and then clicking on the download icon on the chart and selecting Download Current Chart as SVG, nothing happens and no new files are created in the directory. Similarly, the "run to download" menue with csv or json doesn't work. 

Maybe related, the ? icon on the top right also does not respond.

Excited for the fix because these features are great!

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.11.0-34-generic snap
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1062.18.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (3.92GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 09889aea-dff4-45a4-8c0b-7ecc3bf3592e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Container 10.158.62.98/library/tfnightly-gpu-py3:yelena (sleepy_jennings) @ ssh://10.158.62.105|
|OS|Linux x64 3.10.0-1062.18.1.el7.x86_64|
|CPUs|AMD EPYC 7302 16-Core Processor (32 x 1500)|
|Memory (System)|188.62GB (12.10GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container 10.158.62.98/library/py3.7-torch1.7:yelena (yb_dino3) @ ssh://10.158.62.105|
|OS|Linux x64 3.10.0-1062.18.1.el7.x86_64|
|CPUs|AMD EPYC 7302 16-Core Processor (32 x 1500)|
|Memory (System)|188.62GB (12.10GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
gitlens|eam|11.6.0
latex-workshop|Jam|8.20.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
autodocstring|njp|0.5.4
vscode-yaml|red|0.22.0
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140cf:30363604
vssur157:3036780
![Screenshot from 2021-09-23 10-28-16](https://user-images.githubusercontent.com/5349813/134555446-ca0e34b9-aafa-40ac-8914-c1cb63c5019a.png)
8

```

</details>

**Comment by sbatten** [comment]
@ybagdasa it sounds like you are describing an issue with an extension, though I am not sure which one. Please file an issue with the extension repository.

**Comment by ybagdasa** [comment]
@sbatten I don't know what you mean, as Tensorboard is directly integrated with vscode at this point: https://code.visualstudio.com/docs/datascience/pytorch-support#_tensorboard-integration

Do you mean with some other extension?

**Comment by sbatten** [comment]
The launch tensorboard command and feature are contributed by the python extension. Please file the issue on their repository https://github.com/Microsoft/vscode-python

**Comment by ybagdasa** [comment]
@sbatten Thanks, I filed it with them.
