### ISSUE TITLE
Emmet completion doesn't work within cursor stop when inside custom snippet

### ISSUE THREAD

**Issue by mscherr-fastspot** [microsoft/vscode#133609]
Issue Type: <b>Bug</b>

_I did my best to make sure another bug report wasn't filled out for this. I apologize if there already is one._

1. Create a custom snippet for `scss`

Example:

```json
{
    "Minimum Media Query": {
        "prefix": "fs-min-mq",
        "body": ["@media #{$$min_${1:md}} {", "\t${2}", "}"]
    }
}
```
2. Use the snippet, tab into the second cursor stop
3. Try and use any emmet completion, like `pt20` for `padding-top: 20px`

It will only let you use Emmet completion if your cursor comes off the current line and then back onto it.

Example in action:

https://cln.sh/buRk4K

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|. --crash-reporter-id a65a573e-30fe-4bdb-ad36-b9b8463620ba|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by ArturoDent** [comment]
Disable this setting and it will work for you:

`Editor > Suggest: Snippets Prevent Quick Suggestions`

**Comment by mscherr-fastspot** [comment]
👍 Perfect! Thank you so much. Confirmed this works for me.

This is good to be closed out unless I do that!
