### ISSUE TITLE
Notebook keybindings don't work as expected when focus is in the webview

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#133696]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

on a windows machine:
1. open an ipynb file
2. delete a cell
3. press "ctrl-z" 

expected: cell deletion is undone
actual: nothing happens. Menu Edit->Undo works though. I understand the Jupyter shortcut for undo is "z" but since menu Edit->Undo (which maps to Ctrl-z) works, as a user, I have expected ctrl-z to work the same.

![image](https://user-images.githubusercontent.com/26419852/134436368-9e4d96fb-2d15-43de-8b7e-36bf6dbe1ac9.png)

**Comment by roblourens** [comment]
Works fine for me. Surely there's some other step needed? Or call me so I can try it out

**Comment by ronglums** [comment]
Just talked with @roblourens. This repros when no cell in the notebook is selected (i.e. click anywhere in the notebook to deselect the cell), because in this case ctrl-z is applying to the cell output, not the entire editor. Since the cell is deleted (therefore no need to undo anything in the output), redirecting ctrl-z to apply to the editor would be reasonable.

**Comment by roblourens** [comment]
We can see whether it's possible to know that the webview did not use undo and redirect the command to the list. Not sure whether that is possible though. This should only happen after clicking into the webview

**Comment by DonJayamanne** [comment]
@rebornix @roblourens Are you still able to replicate this issue?
I cannot replicate this anymore,
