### ISSUE TITLE
persist fixedDimensions so reloading works as expected

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133639]

**Comment by mjbvz** [comment]
Any steps to verify this?

**Comment by meganrogge** [comment]
Set fixed dimensions via the command or by alt/option + z with wrapped lines in the terminal. Reload the window. It should persist the dimensions

**Comment by rchiodo** [comment]
This doesn't seem to be persisting for me? I'm testing with WSL:
![persistTerminal](https://user-images.githubusercontent.com/19672699/135687032-a188a0a2-2a89-4800-91f7-380dec258bae.gif)

**Comment by meganrogge** [comment]
@rchiodo tracking the issue with remote IE wsl in a separate issue - as I stated before, remote terminal persistence has been broken since 1.59
