### ISSUE TITLE
Unable to debug or run terminal - Cannot create process, error code: 5

### ISSUE THREAD

**Issue by CristianAven** [microsoft/vscode#133680]
Hi

I've just installed VS Code in a new machine, but I can't debug with python or run the terminal. This is the data:

Windows: Version 10.0.19042.1202

VS Code: 1.61.0-insider (user setup)
Chrome: 91.0.4472.164
Electron: 13.4.0
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

VS Code: 1.60.2 (user setup)
VS Code: 1.53.2 (user setup)
VS Code 1.60.2 (system setup)

I've tried the following:
a) Run VS as Admin: Same error
b) Uninstall and reinstall same version of VS Code and Previous/Insiders versions: Same error
c) Uninstall/Reinstall the extensions: Same error
d) Reboot computer (multiple times..): Same error

Screenshot (Trying to launch the terminal):
![image](https://user-images.githubusercontent.com/44200742/134536816-61b8c5e6-5e31-4039-a0ed-93b89c3bb94f.png)

code --verbose Log:
[Code cmd_verbose.txt](https://github.com/microsoft/vscode/files/7219003/Code.cmd_verbose.txt)

Developer Tools --> Console Log:
(https://github.com/microsoft/vscode/files/7219005/Console.vscode-app-1632411445956.log)
[Console vscode-app-1632411445956.log]

Please help!

**Comment by meganrogge** [comment]
@deepak1556 

does this line in the logs mean anything to you?

```
[11512:0923/123758.201:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
```

**Comment by meganrogge** [comment]
Looks like error code 5 means Access is denied - so a permissions issue with your setup.

**Comment by meganrogge** [comment]
See https://support.microsoft.com/en-us/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e

**Comment by CristianAven** [comment]
Sure, it is an access is denied. But what is denied? There no way to find what file causes the permission is denied. Also, the setup has been done many times and as user/admin and the error is still there.

**Comment by CristianAven** [comment]
Finally I've solved it.
There was a deny permission to execute PowerShell. So i've deleted all deny permissions on the file C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe and VS Code started working.
