### ISSUE TITLE
Tabs jump back to beginning when scrolling

### ISSUE THREAD

**Issue by bjacobs09** [microsoft/vscode#133631]
Issue Type: <b>Bug</b>

I have multiple tabs open, when I scroll right, it eventually jumps back to the first tab. This is happening consistently and has caused me to accidentally close the wrong tab, as well as been a major annoyance since I can't get to the tab I want to because it keeps jumping back.
I have a video of it happening if there is a way to submit it.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 7, 5|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id f8795675-8a09-4f02-a3ef-5b9dfa3297a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
openmatchingfiles|bca|0.5.0
vscode-custom-css|be5|6.0.1
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-npm-source|dku|1.0.0
gitlens|eam|11.6.0
flow-for-vscode|flo|1.9.2
macros|ged|1.2.1
vscode-graphql|Gra|0.3.18
relativepathrefactor|jak|0.9.0
graphql-for-vscode|kum|1.15.3
duplicate-module|Leo|0.0.3
rainbow-csv|mec|1.9.1
vscode-language-babel|mgm|0.0.35
ruby-rubocop|mis|0.8.5
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.10.1
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.4836
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sublime-search-vscode|nig|0.1.5
indent-rainbow|ode|8.0.0
ruby|reb|0.28.1
code-settings-sync|Sha|3.4.3
stackery|sta|1.1.4
vscode-icons|vsc|11.6.0
vscode-vydia|vyd|0.0.5
gitblame|wad|8.1.0
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
sort-js-object-keys|zen|1.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vscus224:30367819
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by bjacobs09** [comment]
![tab jumping 3](https://user-images.githubusercontent.com/2531426/134686534-50086391-80cb-4903-ab69-87272e59aa9d.gif)

**Comment by bpasero** [comment]
Is there any action you perform that made the jump? We have code to reveal the active tab e.g. when you open the editor.

**Comment by bjacobs09** [comment]
No I didn't move/click my mouse or press any keys.

**Comment by bpasero** [comment]
Any background activity in that workspace that could explain it, like a watcher or git operation? Something must trigger the revealing...

**Comment by bjacobs09** [comment]
At first I thought it was related to my spec watcher, but I tested it without that running and it still did it. Nothing else is running that I'm aware of.

**Comment by bpasero** [comment]
When you add a breakpoint from devtools into `tabstitlecontrol.ts` at `doLayoutTabsNonWrapping` and see who is calling it when the scrollbar bounces back, that would be helpful.

**Comment by bjacobs09** [comment]
Well there's a large call stack...is there something specific I should be looking for? Or do you want a screenshot of it?

**Comment by bpasero** [comment]
Screenshot is a good start, awesome that you got there 👍

**Comment by bjacobs09** [comment]
<img width="232" alt="Screen Shot 2021-09-24 at 2 29 45 PM" src="https://user-images.githubusercontent.com/2531426/134723480-b13e089e-a95e-4ccc-9543-c64718572c3f.png">


<img width="227" alt="Screen Shot 2021-09-24 at 2 30 00 PM" src="https://user-images.githubusercontent.com/2531426/134723498-06cf87ad-347a-46e0-bcb5-99972a7634a2.png">

**Comment by bpasero** [comment]
Thanks! Yeah, so it looks like the editor toolbar actions get an update and we start to layout tabs to ensure the active one remains visible. The rationale is that you might have a tab visible and shortly after 5 actions appear slightly delayed pushing the tab out of view. We still want the tab to remain active.

In this case though, the actions do not visually change, so maybe we can be more clever.

To confirm: can you disable maybe some of your extensions like GitLens momentarily to ensure this is the issue?

**PS:** I assume you hit the breakpoint really at the right time without interacting with the tabs in any way right?

**Comment by bjacobs09** [comment]
Disabled all extensions and it still happens. And yes, I hit the breakpoint without interacting in any way, and as soon as I hit play, it jumped.

**Comment by bpasero** [comment]
I pushed a change that the active tab will only get revealed when the size of the tab container changes. As such it can still happen that you get brought back to the active tab if an action is added or removed, but this should only happen in the very beginning and not later.

**Comment by bjacobs09** [comment]
Thank you for the solve. I'll look forward to the release. 
Let me see if I understand... I'm assuming the tab container size changes when a new tab is added or a tab is removed. So when a new tab is added, that is automatically the active tab, so no difference in functionality there. But what your fix will impact is that the active tab will only be revealed when we remove a tab?
So then I'm assuming that my issue was happening when the active tab is being revealed in certain circumstances when I was not removing a tab?
Also, what do you mean by "only happen in the very beginning"?
