### ISSUE TITLE
Intellisense suggests path with old file name

### ISSUE THREAD

**Issue by heysujal** [microsoft/vscode#133603]
Issue Type: <b>Bug</b>

Create a file Useritem.js 
Rename the file as UserItem.js 
Now , try `import` statement using import UserItem in your App.js of React Project and wait for intellisense to suggest some statement.
 
![Untitled](https://user-images.githubusercontent.com/55016909/134358553-60afd7ad-eb80-497a-b12b-363bb272e343.png)

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.50GB free)|
|Process Argv|. --crash-reporter-id 253b8a9a-5831-4c1c-843e-c5cae608c81e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.25
competitive-programming-helper|Div|5.8.7
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
code-runner|for|0.11.5
stylelint-plus|hex|0.56.6
git-graph|mhu|1.30.0
python|ms-|2021.9.1246542782
cpptools|ms-|1.6.0
material-icon-theme|PKi|4.10.0
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by mjbvz** [comment]
Can you try adding `forceConsistentCasingInFileNames` to your [`jsconfig`](https://code.visualstudio.com/docs/languages/jsconfig)? On windows, paths are treated as being case insensitive otherwise
