### ISSUE TITLE
Open folder from built in terminal

### ISSUE THREAD

**Issue by ygorlazaro** [Microsoft/vscode#13368]
- VSCode Version: 1.5.3
- OS Version: Windows 10 1601

Steps to Reproduce:

Is there a way you are looking for open a project from the build in terminal? I mean, I want to change the project I am working on, reusing the same instance, using a command like `code .` at the external terminal/command prompt.

**Comment by Tyriar** [comment]
`code -r .` :smiley: 

It will reload the workbench meaning the terminal is lost afterwards, that's unlikely to change though due to the architecture of the workbench.

**Comment by ygorlazaro** [comment]
How, awesome! 

Thanks @Tyriar!
