### ISSUE TITLE
Not importing extracted files

### ISSUE THREAD

**Issue by SpeedsMach5** [microsoft/vscode#133632]
We have written the needed data into your clipboa
Issue Type: <b>Bug</b>

When I try to open / import files to VScode, it fails silent with no error code and will not open / import the selected download (file). There are no updates available. This issues just started today 9.22.2021. I have restarted my machine and have reinstalled VScode.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.77GB (6.32GB free)|
|Process Argv|--crash-reporter-id beb3d594-f66a-41ec-88f9-1f1a080ede18|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

rd because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Please share steps to reproduce this issue. Right now it's not even clear what language you are working in

/needsMoreInfo
