### ISSUE TITLE
Absolute Import not work when create new file

### ISSUE THREAD

**Issue by thanhhai16** [microsoft/vscode#133628]
Hi, I got this problem in VS code, only within this project.
When I created a new file, I can't use Absolute Import Path, I have to restart the VS Code or re-run `npm start`
This is the new file
![image](https://user-images.githubusercontent.com/21291118/133940729-fd47afc0-1f4b-4dbd-b2af-81d02f5b2c56.png)

And here, same file but after restart VS Code 
![image](https://user-images.githubusercontent.com/21291118/133940751-09ed42ce-d2cc-4a26-901e-fb64e91059fc.png)

It is time-consuming when I have to re-run the project or restart VS code every time when I create a new file.
Please help me out
Here is my tsconfig.json
![image](https://user-images.githubusercontent.com/21291118/133940791-eabe3d11-eda9-41dd-8de6-ccc7118655f9.png)

**Comment by mjbvz** [comment]
Closing as not actionable without more information about the issue or simple steps to reproduce it
