### ISSUE TITLE
The same restored terminal session can occur in multiple windows

### ISSUE THREAD

**Issue by Fydon** [microsoft/vscode#133602]
Issue Type: <b>Bug</b>

Only tested via Windows 10

1. Open multiple windows each with a terminal
2. Run different commands in terminals
3. Close all windows via File -> Exit
4. Reopen vscode via the Start Menu

The first window has access to at least some, if not all, restored terminals in the other windows. Closing a terminal in the first windows, closes that instance of the terminal in the other window. When closing the terminal in the subsequent windows, it closes in the first.

VS Code version: Code - Insiders 1.61.0-insider (8d2a6fa12466c488f732b020298bc836636c5b17, 2021-09-22T01:05:21.842Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (37.44GB free)|
|Process Argv|--crash-reporter-id 09295c6e-295b-4ff9-95ca-615dc584c0f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (83)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
better-comments|aar|2.1.0
Bookmarks|ale|13.2.1
ng-template|Ang|12.2.0
atlascode|atl|2.9.1
markdown-mermaid|bie|1.12.1
markdown-preview-github-styles|bie|0.2.0
vscode-intelephense-client|bme|1.7.1
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.4.0
angular-schematics|cyr|5.0.0
vscode-markdownlint|Dav|0.44.1
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
xml|Dot|2.5.1
vscode-wasm|dts|1.3.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|9.0.0
php-debug|fel|1.18.0
url-encode|fle|1.1.0
auto-close-tag|for|0.5.12
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-lombok|Gab|1.0.1
remotehub|Git|0.14.0
vscode-pull-request-github|Git|0.30.0
go|gol|0.28.0
todo-tree|Gru|0.0.214
debug-visualizer|hed|2.2.4
output-colorizer|IBM|0.1.2
vscode-env|Iro|0.1.0
Angular2|joh|12.0.0
vscode-peacock|joh|3.9.1
wordcounter|kir|2.3.0
file-downloader|min|1.0.11
mindaro|min|1.0.120210803
ecdc|mit|1.4.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
jupyter|ms-|2021.9.1001256920
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.195.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
live-server|ms-|0.2.8
powershell|ms-|2021.9.0
vs-keybindings|ms-|0.2.1
vscode-github-issue-notebooks|ms-|0.0.106
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4836
gradle-language|nac|0.2.3
indent-rainbow|ode|8.0.0
vscode-versionlens|pfl|1.0.9
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.28.0
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
fabric8-analytics|red|0.3.3
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
perl|ric|2.2.0
preview-vscode|sea|2.2.5
sonarlint-vscode|Son|2.2.0
code-spell-checker|str|2.0.6
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by Fydon** [comment]
I'm now on commit 5df296407363de70e9d7b455e1fcb004ceaa6b75 and I'm seeing commands that I ran in one terminal being restored into another restored terminal. This means that if I ran foo in terminal 1 in windows 1 and bar in terminal 2 in windows 2, after restarting, e.g. updating to a new version, terminal 1 and terminal 2 could both have a command history showing that foo was run after bar.

**Comment by meganrogge** [comment]
try setting `terminal.integrated.persistentSessionReviveProcess` to `never` and let me know if that fixes the problem

**Comment by Fydon** [comment]
Thank you for looking into this. I switched to `never` and it is now not restoring terminals. Is that not just turning off the feature rather?

I do like the restored terminals and plan to keep using it. It generally works fine, but there are some glitches. I haven't seen these issues recently. Although on the latest build setting `terminal.integrated.persistentSessionReviveProcess` back to `onExit` I just had an issue where the restored terminal didn't start properly, so I can't type a command in it. Should I create a new issue?
![image](https://user-images.githubusercontent.com/3404761/134738300-a886a4f0-836b-48e0-9322-673ccd4436de.png)

The cursor does change to a solid square, but doesn't respond to key presses. The PowerShell Integrated Console is a terminal that the Powershell extension creates when a Powershell script is in the active tab. They seem to fail to restore every time on every window with vscode insider 8d30d4d922dda917d22f05a81f2ab4fad7349779.

**Comment by Fydon** [comment]
I thought that I would just mention that the issues with the PowerShell Integrated Console terminals appear to be fixed in the latest version after killing the terminals created in the previous version. Thank you for all the work on this.
