### ISSUE TITLE
Find and Replace dialog covers content

### ISSUE THREAD

**Issue by cparker4486** [Microsoft/vscode#13362]
- VSCode Version: 1.5.3
- OS Version: Win 10 1607

Steps to Reproduce:

1. Have content as long as the window is wide in the first three lines of the window
2. Display the Find and Replace dialog

![image](https://cloud.githubusercontent.com/assets/1189638/19198376/b739d95c-8c73-11e6-9e0d-e9b0a6335cbb.png)

In some cases, like mine above, this dialog covers the content and there's no way to change that except to make changes to the content itself by adding additional empty lines at the top.

Scrolling doesn't work and neither does changing the size of the window. The content will always be covered. Additionally, stepping through matches doesn't help because the dialog doesn't move out of the way when a match is found underneath it.

What's my preferred fix? I think a good solution is to model the control after Sublime Text's implementation. In ST's case, a single row dialog slides up from the bottom of the window. If it covers a line of text at the bottom, the content becomes scrollable which allows the user to scroll the content up. Similarly, stepping through the matches will make them visible because doing that repositions the content not the dialog.

I recognize that my preferred fix completely changes the UI which might be too much to accept for the dev team and some users. (Even though I think it would be a net positive change.)

Here are some other possible fixes I came up with.

1. Display the dialog in the same place but shift the content itself down a maximum of three lines.
2. Move the dialog down up to three lines if it covers matches. If it _still_ covers matches (on lines 4,5,6) then move the dialog one line at a time when stepping through the matches. Move the dialog progressively downard, up to three lines, when stepping forward. Move the dialog back up, up to three lines, when coming from below the dialog while stepping backward. In other words, push the dialog in the direction the user is moving through the matches.

There are certainly other options out there but I've spent too much time on this at this point. :)

Thank you for your consideration!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11102

**Comment by cparker4486** [comment]
All that effort... gone.

I even searched too. What a bummer.

**Comment by Tyriar** [comment]
@cparker4486 you should transfer the useful bits over to #11102

**Comment by cparker4486** [comment]
Thanks for the suggestion. Would that be just a copy/paste?

**Comment by Tyriar** [comment]
Yep, thanks for the suggestions :smiley:
