### ISSUE TITLE
Search "Open in editor" misidentifying results, omits match lines when selecting '0' neighbors

### ISSUE THREAD

**Issue by datocrats-org** [microsoft/vscode#133607]
Issue Type: <b>Bug</b>

1. Create a text file with text like the following
```
BEGIN
  UB4       ITEMID
  TEXT      NAME
  BLONG     PLSLFID_EP
  UB4       OBJECT_ID
  UB1       TYPE
  TLONG     PLSLFID_ST
```
2. Search the file for something like ID to match on multiple lines, e.g., regex `\wID\n`
3. Click Open in editor to view results, observe the full resultset, vscode bolds the lines with semicolons shown below that do not always include the result as defined e.g.
```
2 results - 1 file

~\vscode_error.txt:
  1  BEGIN
  2:   UB4       ITEMID
  3:   TEXT      NAME
  4    BLONG     PLSLFID_EP
  5:   UB4       OBJECT_ID
  6:   UB1       TYPE
  7    TLONG     PLSLFID_ST
```
4. In the text box that defaults to show 1 line above and below each result, change it from 1 to 0
5. Observe the result that shows only the bolded and semi-colon'd lines, it removes in an inconsistent manner, e.g.
```
~\vscode_error.txt:
  2:   UB4       ITEMID
  3:   TEXT      NAME
  5:   UB4       OBJECT_ID
  6:   UB1       TYPE
```

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.2.1
json-flattener|App|1.0.5
unique-lines|bib|1.0.0
markdown-shiki|bie|0.1.1
vscode-path-tools|cg-|0.0.4
path-intellisense|chr|2.4.0
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
cloudformation-yaml-snippets|dst|3.32.0
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
markdown-table-formatter|fcr|2.2.3
opensslutils|ffa|1.1.1
auto-rename-tag|for|0.1.8
todo-tree|Gru|0.0.214
timing|Haa|2.6.0
vscode-settings-cycler|hoo|1.0.1
auto-markdown-toc|hun|3.0.12
json-escaper|jos|1.1.2
vsc-python-indent|Kev|1.14.2
l13-diff|L13|1.0.3
vscode-format-context-menu|lac|1.0.4
json-to-ts|Mar|1.7.5
gitignore|mic|1.0.1
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
sqltools|mtx|0.23.0
autodocstring|njp|0.5.4
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
code-settings-sync|Sha|3.4.3
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Including the trailing `\n` will cause the result set to include the next line. This is more or less as-designed, if you want to only assert that the match is at the end, I recommend a regex.
