### ISSUE TITLE
Rename "Synchronize" command to "Pull & Push"

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#13360]
"Synchronize" suggests to me that it will not do anything harmful. Yet it does potentially add a merge commit and then push that and all other outgoing changes to a potentially public repository.

At least two people have run into this while smoke-testing and I have reports from other teams that this is causing some grief.
#8655 discusses enabling the confirmation dialog by default or making the command more configurable, but the main issue seems to be that it does something people new to it don't expect from its name.

/cc @egamma @chrisdias @bgashler1 @joaomoreno

**Comment by felixfbecker** [comment]
What I would like is instead of synchronize, make the `↑ n` and `↓ n` buttons clickable individually and trigger a pull / push

**Comment by joaomoreno** [comment]
Note that 96010725e5b3e3035174b0cfc85898add1d79159 introduced a confirmation dialog by default. Given that, I suggest keeping the `Sync` label

**Comment by felixfbecker** [comment]
I still think the actions should be separated completely. That's just how git works, you cannot do both at the same time, you always either do a push or do a pull.

**Comment by joaomoreno** [comment]
@felixfbecker Care to create a new issue for that?

**Comment by felixfbecker** [comment]
I don't care that much about it, just wanted to give my 2ct for your consideration 😄

**Comment by borgdylan** [comment]
@felixfbecker I agree. There are cases where you only want to pull, not push as well such as when you know that you committed something that will cause conflicts on other people's machines.

**Comment by chrmarti** [comment]
Using this issue to track the labeling. Since "Synchronize" is not part of the git terminology it still seems to make sense to change it to "Pull & Push". Please open new issues for splitting the two operations in the status bar and other changes. /cc @seanmcbreen (related: #15158)

**Comment by chrmarti** [comment]
Never got traction on this idea. Closing.
