### ISSUE TITLE
Synchronize edits across multiple windows even when editor dirty

### ISSUE THREAD

**Issue by iyz91** [microsoft/vscode#133640]
Issue Type: <b>Feature Request</b>

Related to https://github.com/microsoft/vscode/issues/11866 and https://github.com/microsoft/vscode/issues/22128 though doesn't appear to have ever been implemented.

Editing file in one window should be reflected in another window for the same file (at least on gain of focus) while the file is in a dirty state (i.e. before saving). This was a useful feature coming from sublime.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sbatten** [comment]
@bpasero
