### ISSUE TITLE
The prompt for ipykernal installation takes a long time to come up with no visual indication

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#133641]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. Set up a new conda env (without installing ipykernel in it), select the new env as the kernel
2. Run a cell

expected: cell to run or users are informed that ipykernel needs to be installed
actual: no visual clue of what's happening until at least 30 seconds later when the model dialog shows up

Please refer to this video (7'06'' - 7'38'') https://msit.microsoftstream.com/video/12e10840-98dc-ae71-db7b-f1ec19e01ea4?list=studio

**Comment by DonJayamanne** [comment]
Looking at the Video kernels are available, but hitting the run all or run cell button doesn't end up prompting the user to select a kernel.
How ever manually selecting a kernel fix things

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/7700
