### ISSUE TITLE
Profile with sync my extensions, settings and more

### ISSUE THREAD

**Issue by jesusgy** [microsoft/vscode#133693]
Hello vscode team, I want a profile like feature with options for syncing my extensions, settings, themes, etc.. would be great to do if for example I used more than one computer to code(in my case I use 3 computers).  thanks in advance

**Comment by IllusionMH** [comment]
It's already existing functionality https://code.visualstudio.com/docs/editor/settings-sync

/question
Marking as question as this request doesn't mention existing functionality and specific request for improvement of it.
