### ISSUE TITLE
Search: `LocalSearchService` is now unused

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133654]
It looks like `vs/workbench/services/search/electron-browser/searchService` is not used anymore in the product, even though the file still exists and is even added to the product:

https://github.com/microsoft/vscode/blob/2222f3cc1d55eb0b20606c687d5fdf7d585e5842/src/vs/workbench/workbench.desktop.main.ts#L60-L60

I suggest to remove this file. One interesting fact is that it seems to reference `vs/workbench/services/search/node/searchApp` and related files, but I wasn't sure if we could remove even more now.

**Comment by roblourens** [comment]
I still have a setting which enables opting into local search. Will leave it there for a month in case we need to A/B test in some github issue with stable.

**Comment by bpasero** [comment]
Really to close this issue, this line needs to go away:

https://github.com/microsoft/vscode/blob/926dcb80e1cf6b92eda148b53b74d569b3a5e9b9/src/vs/workbench/workbench.desktop.main.ts#L60

This file will very soon be gone for good when sandbox is enabled.

**Comment by roblourens** [comment]
Please check that my entry in workbench.sandbox.main.ts is ok, it's a little weird because the common SearchService is basically the implementation I want for desktop, but it's subclassed for browser.

**Comment by bpasero** [comment]
@roblourens seems fine to me. What I typically end up doing is to have a abstract class and then have subclasses for browser and desktop specifically for the difference.

Thanks for pushing this forward 👏

**Comment by bpasero** [comment]
@roblourens one thing I noticed is still this code:

https://github.com/microsoft/vscode/blob/66b1668b66768275b655cde14d96203915feca7b/src/vs/workbench/services/search/node/rawSearchService.ts#L22

That should only really be needed if search is using node.js FS APIs, but I think that is not true anymore right?

**Comment by roblourens** [comment]
Yeah that fs import is not actually used, good catch
