### ISSUE TITLE
visual studio code is not responding it keeps on telling me to restart, keep waiting or close in a pop up window

### ISSUE THREAD

**Issue by ikennobunga** [Microsoft/vscode#13367]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
What is the output when you run `code --verbose`? Can you upload a screenshot of the window when it's not responding?

**Comment by maylortaylor** [comment]
I'm having this issue on Visual Studio Code 1.6.1.
As soon as i open Code, it starts to load my project and i can click around for about 5 seconds, **then** the program freezes and i'm only able to click on the menu dropdowns at the top. Everything seems frozen. Every minute or so, Code will ask if i want to "Reopen, Keep waiting, or close"

**Comment by Tyriar** [comment]
@maylortaylor can you answer the questions in https://github.com/Microsoft/vscode/issues/13367#issuecomment-252327931 to help figure out what's going on?

**Comment by mamoorkhan** [comment]
> As soon as i open Code, it starts to load my project and i can click around for about 5 seconds, then the program freezes and i'm only able to click on the menu dropdowns at the top. Everything seems frozen. Every minute or so, Code will ask if i want to "Reopen, Keep waiting, or close"

I have the same problem and I get the below logs when I run it as code --verbose

[main 4:16:20 PM] Starting VS Code in verbose mode
[main 4:16:20 PM] from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[main 4:16:20 PM] args: { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  'open-url': undefined,
  locale: undefined,
  wait: false }
[main 4:16:24 PM] IPC#vscode:startCrashReporter
[main 4:16:24 PM] IPC#vscode-workbenchLoaded
[VS Code]: detected unresponsive

**Comment by mamoorkhan** [comment]
and when I ran `code --disable-extensions` it loaded just fine, I think there is some extension that is trying to parse/format code and it is hanging up

**Comment by Tyriar** [comment]
Thanks @mamoorkhan, I'll close this off as it's an extension issue. You should be able to look at and uninstall extensions from the command line using `code --list-extensions` and `code --uninstall-extensions`.

**Comment by mamoorkhan** [comment]
Furthermore I'd like to add that one can also run vs code with extensions disabled via `code --disable-extensions` and then uninstall extensions from the UI one by one.

**Comment by Tyriar** [comment]
@mamoorkhan even better, wasn't sure if you could do that :+1:
