### ISSUE TITLE
More indentation

### ISSUE THREAD

**Issue by nove1398** [microsoft/vscode#133697]
Issue Type: <b>Feature Request</b>

The workspace pane looks a bit jumbled, perhaps the folder tree could have some more indentation

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Did you yet try the `workbench.tree.indent` setting?
