### ISSUE TITLE
debug: toolbar does not update if focused thread no longer exists

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode#133623]
- VS Code Version: 1.60.1
- OS Version: darwin/amd64

Steps to Reproduce:
Reported in the vscode-go repo: golang/vscode-go#1648

All threads are stopped expected toolbar to be:

<img width="188" alt="Screen Shot 2021-09-22 at 12 39 23 PM" src="https://user-images.githubusercontent.com/6634754/134402574-d35f2358-54b7-480d-a2d3-e2125649f3f0.png">

Instead got:
<img width="191" alt="Screen Shot 2021-09-22 at 12 39 09 PM" src="https://user-images.githubusercontent.com/6634754/134402568-51485c1f-35fa-4cde-a305-cded9540b261.png">

This occurs when a stopped event is returned with no threadId AND the previously focused thread no longer exists, then the toolbar is left in the running state with the pause button enabled.

All of the active threads are paused:
<img width="256" alt="Screen Shot 2021-09-22 at 12 25 40 PM" src="https://user-images.githubusercontent.com/6634754/134402092-fb9a1f70-462d-4b58-bdf4-0c4eaaca7c39.png">

But the focused thread is still running, but actually does not exist anymore:
<img width="593" alt="Screen Shot 2021-09-22 at 12 25 52 PM" src="https://user-images.githubusercontent.com/6634754/134402099-84b588f5-3ea3-47c8-a68f-f01d20cf4901.png">

The focused thread should be cleared if the thread no longer exists.

**Comment by roblourens** [comment]
@suzmue I assume you tested the PR that you sent, but would appreciate you double-checking that it is fixed in our build since I'm not sure how to trigger the issue, thanks!

**Comment by rchiodo** [comment]
/verified

At least I think so.

I ran the steps here:
https://github.com/golang/vscode-go/issues/1648#issuecomment-922171664

And they work now.
