### ISSUE TITLE
Expand Selection not selecting inside quotes

### ISSUE THREAD

**Issue by dapc11** [microsoft/vscode#133689]
Issue Type: <b>Bug</b>

In python, given the following snippet:
    def render_templates(self) -> None:
        """Render templates defined in templates.json."""

if one were to put the cursor inside 'defined' see following with []:
    def render_templates(self) -> None:
        """Render templates def[]ined in templates.json."""

When expanding the seletcion I would expect that the following would be selected:
    def render_templates(self) -> None:
        """Render templates [defined] in templates.json."""

And If I were to expand select ion again:
    def render_templates(self) -> None:
        """[Render templates defined in templates.json.]"""

Instead the selection is the following:
    def render_templates(self) -> None:
        ["""Render templates defined in templates.json."""]

This is a bit like the expand selection in IDEA products work, which I find very usable in my day-to-day work.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.11.0-34-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3065)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.58GB (0.81GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id be1569b3-a36c-4648-8c9d-1e6b554f0ae2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-quick-select|dba|0.2.9
go|gol|0.27.2
intellij-idea-keybindings|k--|1.4.5
expand-region|let|0.1.4
bash-ide-vscode|mad|1.11.0
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
viml|Xad|1.0.1
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by dapc11** [comment]
@jrieken This is actually happening in other files than python as well. Yaml for example:

`file: ".archive/test-[]reports.zip"`
`file: ".archive/test-[reports].zip"`
`[file: ".archive/test-reports.zip"]`

Is it because I have the python plugin turned on in other files than Python as well?

**Comment by jrieken** [comment]
Each language extension needs to do that. By default VS Code expands words, line and bracket pairs but strings are surprisingly complex and therefore not covered by the default-solution

**Comment by dapc11** [comment]
I understand. Thanks for the information and pointers @jrieken.
