### ISSUE TITLE
Not clear how to add additional reactions to PR comments 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#133601]
When you open a PR in review mode with the extension, there is an extra button to add emoji's to the comments in the PR but it's not very clear. If there is already an existing emoji reaction to a comment, there is a button next to it to add another one, but it's not obvious (on github.com, there's a smiley face on the button)

In the extension:
![image](https://user-images.githubusercontent.com/9721254/134213746-e4d76535-252d-4625-86b0-cc2af168895a.png)

On github.com:
![image](https://user-images.githubusercontent.com/9721254/134213715-3cf1c88d-6a05-4050-84c5-b2c542d17c48.png)

**Comment by alexr00** [comment]
Assigning to @rebornix since these UI elements are provided by the comment widget.

**Comment by alexr00** [comment]
The button has the smiley now. 

I'm also changing the button at the bottom to show even when there aren't existing reactions, and to show on hover of the entire comment, not just the "comment reaction toolbar".
