### ISSUE TITLE
Feature request: Represent stale test results with a different icon to tests that have been run recently.

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#133686]
It'd be really great to be able to see which tests haven't been run since the last change to the source part of my code by giving them a different icon to the green check in a circle used for passing tests currently. Maybe a grey icon without the circle or something?

**Comment by gjsjohnmurray** [comment]
Is this related to https://github.com/microsoft/vscode/issues/134970#issuecomment-943660452?

**Comment by MiguelGuthridge** [comment]
Yep looks pretty similar, although my issue is less related to auto-running tests, and more just showing the information to the user.

**Comment by connor4312** [comment]
Duplicates the linked issue 🙂
