### ISSUE TITLE
VS Code keeps displaying info alert: "The workspace folder contains TypeScript version 2.0.3." even though I removed TypeScript from my project

### ISSUE THREAD

**Issue by alejandroiglesias** [Microsoft/vscode#13361]
- VSCode Version: 1.5.3
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce: not sure how to reproduce, I started using VS Code with this project while having TypeScript. I always clicked to use 2.0.3 version. It asks every time I open VS Code. Now TypeScript is removed from the project and the question keeps appearing. Is it related to some leftover file or cache? Is there any way to disable it for this project? Or make it ask just once? If I click "Don't check anymore", will it still ask for other projects?
Please let me know if you need more info.

**Comment by waderyan** [comment]
@alejandroiglesias thank you for opening this issue. 

@dbaeumer can you advise here? I have tried recreating the issue and actually see the reverse of what OP sees. I cannot get the info message to appear even when I add TS to my workspace (tried reloading, restarting, removing all settings, etc.)

I am using the latest VS Code bits.

**Comment by roblourens** [comment]
@waderyan Check your user settings for the setting to disable the check, which will be there if you ever clicked "don't show this again" or whatever it is.

**Comment by waderyan** [comment]
Hey @roblourens, thanks for the tip! I did check settings and unfortunately did not see the setting.

**Comment by Nikki1993** [comment]
@waderyan you could download latest typescript via npm

`npm i -g typescript` and then point the VS Code to the latest typescript in the settings.json file, in my case on macOS 10.12 it looks like this 

```
  //  typescript settings 
  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib",

```

**Comment by dbaeumer** [comment]
@waderyan I only warn if the version installed in the workspace folder differs from the one we ship. So if you installed TS 2.0.3 in the workspace there will not be a message.

@alejandroiglesias how did you uninstall typescript. You need to remove it from the node_modules folder as well. Simply removing the entry from the package.json is not enough.

**Comment by alejandroiglesias** [comment]
@dbaeumer thanks. I didn't uninstalled Typescript myself, so just received an updated `package.json` when pulling my repo. It seems Typescript dependencies were still kept in `node_modules/` dir and wanting Typescript. `npm install` kept installing it even after `rm -rf node_modules/typescript/`. Finally, `rm -rf node_modules/ && npm install` did a clean install without Typescript. That's a tricky treat of npm. Thanks to everyone for your comments and sorry for the false alarm.
