### ISSUE TITLE
Terminal with remote ssh gets out of sync

### ISSUE THREAD

**Issue by bjtucker** [microsoft/vscode#133626]
Issue Type: <b>Bug</b>

* set key repeat rate as high as it will go.
* use the remote ssh feature to open a session on a remote host (I do it over a slowish vpn. I think that matters, since this seems to be a race condition)
* open a bash terminal on the remote host
* write a really long bash command
* up-arrow to recall the command, then left-arrow near the front of it. Make some edits. hit CTRL-L to redraw the screen. A significant portion of the time, I find that my cursor is misplaced, and the edits I'm making are really happening elsewhere in the line.

workaround:
I hit ^L kind of all the time when editing commands so I don't end up messing up. It's a pain, and when I forget, I can send bogus commands that look right but really are just messed up.

other workaround:
Some coworkers just avoid the builtin terminal since it's unreliable.

This doesn't only happen in the above circumstance, but kind of all the time. It's really annoying and can sometimes lead to VERY scary errors executing bash commands that are kind of but not exactly what you meant. for instance, the difference between "rm -rf ./*" and "rm -rf . /*"

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Remote OS version: Linux x64 3.10.0-1160.36.2.el7.x86_64
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled
Fetching remote diagnostics for 'SSH: XXXXXXXXXX' failed: Canceled

<details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
openssl-configuration-file|gee|0.0.1
pytest-snippets|jai|1.0.0
bats|jet|0.1.7
vscode-peacock|joh|3.9.1
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-fluentd|msy|0.0.4
terraform-doc-snippets|run|0.6.0
jinja|who|0.0.8
vscode-ruby|win|0.28.0
jinja2-snippet-kit|Wya|2.0.0
vscode-pytest|Cam|0.1.1
chef|che|2.1.0
whitespace-plus|dav|0.0.5
gitlens|eam|11.6.0
terraform|has|2.15.0
vscode-test-explorer|hbe|2.21.1
compareit|in4|0.0.2
git-tree-compare|let|1.10.2
vscode-python-test-adapter|lit|0.7.0
render-crlf|med|1.5.21
vscode-docker|ms-|1.17.0
mssql|ms-|1.10.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.2
jupyter|ms-|2021.8.1236758218
powershell|ms-|2021.9.0
test-adapter-converter|ms-|0.1.2
vsliveshare|ms-|1.0.4836
gremlins|nho|0.26.0
ruby|reb|0.28.1
ansible|red|0.4.5
vscode-commons|red|0.0.6
vscode-yaml|red|0.22.0
partial-diff|ryu|1.4.3
docker|vsc|1.0.0
sql|vsc|1.0.0
yaml|vsc|1.0.0
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by bjtucker** [comment]
The symptom here is that sometimes the cursor gets a little misplaced when editing previous lines in bash. Everything else is about recreating that. I'm happy to provide any more information I can.

**Comment by KapitanOczywisty** [comment]
I have the same issue, for me server load (spikes) is causing this most of the time. Thanks for `Ctrl+L`!

**Comment by KapitanOczywisty** [comment]
Same thing was *probably* reported in here: #132858 #131961 #126209 #126589 and probably more. Known issue for sure.

3 last issues are mentioning that setting `terminal.integrated.localEchoLatencyThreshold: -1` fixes issue, and this might be right, I was not able to mess-up command after that.

[Local Echo feature from v1.51](https://code.visualstudio.com/updates/v1_51#_local-echo)
