### ISSUE TITLE
Terminal tabs layout is expensive

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#133635]
Resizing the explorer makes the UI laggy, it looks like the main culprit is tabs:

![image](https://user-images.githubusercontent.com/2193314/134421907-5ff66dbb-d2da-41eb-8695-48c6d6b35995.png)

**Comment by bpasero** [comment]
Upon second look, `_rerenderTabs` is coming from terminal:

https://github.com/microsoft/vscode/blob/4e12faaecebb7984bef524076f5fa2a3850823fb/src/vs/workbench/contrib/terminal/browser/terminalTabbedView.ts#L285

**Comment by Tyriar** [comment]
🤯 sorry about the hassle.

**Comment by Tyriar** [comment]
@meganrogge FYI I pushed a change to no longer trigger `_rerenderTabs` on layout as this is an expensive action. I don't think we should need to do this on layout but keep an eye out for regressions.
