### ISSUE TITLE
Integrated Terminal default exe not being used

### ISSUE THREAD

**Issue by Kizmar** [microsoft/vscode#133670]
Issue Type: <b>Bug</b>

I have Bash set up as the default for the Integrated Terminal. Since the last update or two; every time I open vscode it opens a Powershell terminal. Everything is already set up with Bash as default, so I don't know what needs to be changed in order for Bash to actually be the default when opening a new integrated terminal panel.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (10.89GB free)|
|Process Argv|--crash-reporter-id 55902eed-5576-46ee-b343-6ba59e3b08e0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/duplicate

Update to latest stable version where default profile is fixed already.
