### ISSUE TITLE
Explore option for allowing to run all cells in a folded markdown region

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#133690]
Separating this out from #132690

When a markdown cell has code cells folded underneath, the suggestions is to surface the total number of cells folded and to show a run action next to it:

<img width="1004" alt="CleanShot 2021-09-23 at 12 51 59@2x" src="https://user-images.githubusercontent.com/35271042/134574593-7c89d8a4-28cb-418d-ad8e-4b4b3efc2e4e.png">

Running the cell would show progress for the cells (with a stop action that will interrupt the kernel). And when the cell is finished, the cell returns the previous state. You can also click on the cell `...` to expand the collapsed state (which is equivalent to opening the folded markdown region)

![CleanShot 2021-09-08 at 13 52 06](https://user-images.githubusercontent.com/35271042/132584466-ba0bc4e8-d01f-403a-8a3a-47fb03e82762.gif)

**Comment by Yoyokrazy** [comment]
This was completed several iterations ago, with the functionality described. When header md cells are collapsed, a run button is surfaced if there are code cells within the section.

![Image](https://github.com/user-attachments/assets/866a5081-0b29-4633-9110-ac87ea5a020b)
