### ISSUE TITLE
Add arbitrary callback support to test explorer

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#133612]
I use the test explorer now more than the CLI when running tests in the VS Code repo. Test that use non standard functions as the callback aren't picked up in the explorer which caused me to miss them. Here's an example with a custom sinonTest function

Example 
https://github.com/microsoft/vscode/blob/a01c72ed3b8c78e499d3cf7099f4dde046826f81/src/vs/platform/telemetry/test/browser/telemetryService.test.ts#L90-L91

**Comment by connor4312** [comment]
Here's the function used to figure out what's a test or not:

https://github.com/microsoft/vscode-selfhost-test-provider/blob/2ddd1cb9f669d4dcb50d7304a7fb194f2bfdd506/src/sourceUtils.ts#L16

**Comment by chenjefferson** [comment]
Hey! I'd like to work on this. If I don't give an update within 2 weeks or if that's not okay, feel free to give this to someone else.

**Comment by connor4312** [comment]
Probably you don't have `yarn watch` running to recompile changes
