### ISSUE TITLE
Faulty Extensions

### ISSUE THREAD

**Issue by Jamez009** [microsoft/vscode#133684]
Issue Type: <b>Performance Issue</b>

Extensions not loading even though my device is connected to the internet. All updates have been applied to the application but the extension updates and installations are faulty.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.78GB free)|
|Process Argv|--crash-reporter-id b4b67050-462f-4905-a957-e8ddfd54ec55|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|12.34GB (11.94GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	 79116	code main
    0	    95	 17732	   shared-process
    0	    69	 76180	     ptyHost
    0	   151	 63948	   window (Settings - Visual Studio Code)
    0	   106	 84348	     extensionHost
    0	    71	 79432	       electron_node wslDaemon.js 
    0	     7	 81772	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 7f6ab5485bbc008386c4386d08766667e155244e stable .vscode-server 0  '
    0	     6	 78260	           C:\WINDOWS\system32\lxss\wslhost.exe {7419a849-eb10-4e58-b5b9-ed6a3ca208ab} 500 524 528 {1a842da4-f441-467d-ac7d-aea175759627}
    0	    12	 84440	             console-window-host (Windows internal process)
    0	    11	 82340	           console-window-host (Windows internal process)
    0	   161	 75384	   gpu-process
    0	    41	 80100	   utility
    0	    82	 82452	   window (Issue Reporter)
    0	    26	 83136	   crashpad-handler

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	    38	remote agent
    0	     0	    49	   ptyHost
    0	     0	   126	   extensionHost
    0	     0	   141	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   142	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
better-cpp-syntax|jef|1.15.5
remote-wsl|ms-|0.54.6
vim|vsc|1.19.1
cpptools|ms-|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by sandy081** [comment]
Please follow these steps and provide us the logs

- `F1 > Set Log Level... > Trace`
- Retry installing or updating extensions and provide following logs
- `F1 > Open View... > Log (Window)`
- `F1 > Open View... > Log (Remote)`
- `F1 > Open View... > Log (Shared)`

**Comment by sandy081** [comment]
Please reopen it with requested information
