### ISSUE TITLE
Bad link from VS Code API page

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#133658]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. go to https://code.visualstudio.com/api/references/vscode-api#FileSystem
2. notice `an instance of this interface is available as {@@linkcode workspace.fs}.` with a non-interpreted linkcode

![Screenshot from 2021-09-23 09-31-55](https://user-images.githubusercontent.com/1105127/134469759-617d267a-b170-4f94-a8f0-5723e35f3477.png)

**Comment by jrieken** [comment]
Looks like this has been fixed already: https://github.com/microsoft/vscode/blob/36b0223a9dba92f9f4a31054ae7a4db18376b734/src/vs/vscode.d.ts#L7439
