### ISSUE TITLE
Indicator of running VSCode disappears from dock pane when new version is available

### ISSUE THREAD

**Issue by mirao** [microsoft/vscode#133688]
- VS Code Version: 1.60.1
- OS Version: Ubuntu 21.04, Gnome Shell 3.38.4 (also Ubuntu 21.10 with Gnome Shell 40.5 is affected)
- Gnome extension Ubuntu Dock ver. 69

**Steps to Reproduce:**
I can see the issue already for long time.
I have suspicion it happens only when dock pane is set on the left side on screen
1. Have running VSCode window (or more windows)
2. Suppose a new code update is available (e.g. 1.60.2):
![new_version](https://user-images.githubusercontent.com/12584138/134567155-de50b062-c713-40a2-bf52-f33dc57188af.png)

**Expected result:**
- Still red dots (their count equals to number of running VSCode windows) is displayed in dock pane
![reddots_three](https://user-images.githubusercontent.com/12584138/134567193-4c3d0832-7992-4988-9604-1de8b5c70aff.png)

**Actual result:**
- Red dots from VSCode from docker pane disappear
![reddots](https://user-images.githubusercontent.com/12584138/134567270-4a28268a-757a-48a6-bcf9-d51e924ec142.png)

It looks like no VSCode window is running, but actually still some windows are running and you can see them by `Alt + Tab`

**Comment by mirao** [comment]
GitHub from some reason doesn't allow to insert pictures. So one more time:
file:///home/mirao/Pictures/new_version.png

**Comment by joaomoreno** [comment]
What is in `Help > About`? Is this a snap package?

**Comment by mirao** [comment]
It's a snap package
```
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.2-051402-generic snap
```
```bash
$ snap list code
Name  Version   Rev  Tracking       Publisher  Notes
code  7f6ab548  75   latest/stable  vscode✓    classic
```

**Comment by joaomoreno** [comment]
Interesting. Maybe when a new snap package is installed, Ubuntu points to that new version, so Gnome Shell stops believing it's the same app. Do you see this happening with other (potentially Electron basede) snap apps?

**Comment by mirao** [comment]
E.g. I'm using Slack (it's a snap application too) and never observe such behavior when Slack is running.
But Slack doesn't notify that a new version is available, it's just upgraded on background (as well as other snap applications), so I guess when I restart Slack then, a new version is loaded.

**Comment by mirao** [comment]
> I have suspicion it happens only when dock pane is set on the left side on screen

No, it happens even with dock pane placed on bottom of screen 

Here are reliable steps how to reproduce the issue quickly:
- Close VS Code
- Uninstall it: `$ sudo snap remove code`
- Download [VS Code 1.60.1](https://update.code.visualstudio.com/1.60.1/linux-snap-x64/stable) (currently it's the previous stable version)
- Install it: `$ sudo snap install ~/Downloads/code-stable-x64-1631295313.snap --classic`
- Run VS Code
- Get the latest version: `$ sudo snap refresh code`
- Now you can see that a new version is offered :heavy_check_mark: :
![image](https://user-images.githubusercontent.com/12584138/135725970-22c3c920-1647-42da-9483-2a6f7b02d1f3.png)
but a red dot indicating running VS Code will disappear :x: 
![image](https://user-images.githubusercontent.com/12584138/135725997-c64bb5e3-9fc7-4838-ac05-6df8342e6d2c.png)

**Comment by mirao** [comment]
Just FYI:
Visually the app running indicator is managed by [Ubuntu Dock](https://github.com/micheleg/dash-to-dock) extension. This command turns on dots: `gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style 'DOTS'` (DOTS is a default value)

**Comment by mirao** [comment]
Since Ubuntu 22.04, no notification about a new version appears in VSCode.
Ubuntu shows a notification in its notification list instead (for any Snap application):

![image](https://user-images.githubusercontent.com/12584138/196029456-d2d6c351-75a9-471f-b5e4-68b70445ecae.png)

More info about the process is here: https://askubuntu.com/a/1412580

**I'm closing** this issue as it cannot happen anymore from the above mentioned reason.
