### ISSUE TITLE
Remember editor view state for readonly editors

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#13364]
- VSCode Version:1.6.0 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. File > Preferences > User Settings
2. In Default Settings, search for "enabletelemetry" so you go down to the bottom of the readonly editor.
3. Switch to another editor in the same editor group.
4. Now switch back to Default Settings.

You're back at the top of the editor.  This also happens with Default Keyboard Shortcuts.

**Comment by bpasero** [comment]
Landed with Sandeeps work 👍
