### ISSUE TITLE
Hard to customize inlay hint colors

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#133673]
Observations:

- the settings keys would have been better named `editor.inlayHintType.background` instead of `editorInlayHintType.background` to allign it with the setting to enable inlay hints with is `editor.inlayHints.enabled`

- the setting `editorInlayHint.background` didn't have any effect. I would have expected to change the background color for parameter and type

**Comment by jrieken** [comment]
Always unsure how the rules for color names go. @aeschli Can you help me? This is what I currently have https://github.com/microsoft/vscode/blob/db47462779e8803f196501e6c856843b0aa0371c/src/vs/platform/theme/common/colorRegistry.ts#L360-L365

**Comment by aeschli** [comment]
The chosen color names are good.
We are following a two-segment naming scheme: 'location.property`

See our other colors: https://code.visualstudio.com/api/references/theme-color

**Comment by jrieken** [comment]
> the setting editorInlayHint.background didn't have any effect. I would have expected to change the background color for parameter and type

Maybe the name isn't explicit enough. It's not the default style but the style for "other", so there is three kind: type, parameter, and other.

**Comment by dbaeumer** [comment]
> Maybe the name isn't explicit enough. It's not the default style but the style for "other", so there is three kind: type, parameter, and other.

But if you add another one I need to customize the color as well. Would it make sense to name the `other` different and treat the other one as the default.

**Comment by jrieken** [comment]
Yeah, I can make the others (type, parameter) use the default (other) but ultimately we want to give them different colors (that the whole point of them being different inlay types) and than there is no more concept of default/override color for all inlays

**Comment by jrieken** [comment]
> We are following a two-segment naming scheme: 'location.property`

@aeschli quick clarification. Should it be `editorInlayHintParameter.background` or `editorInlayHint.parameterBackground` etc? So, `editorInlayHint` in the location/subject and than comes a couple of properties like parmater-foreground/background and type-foreground/background

**Comment by aeschli** [comment]
@jrieken Makes sense. `editorInlayHint.parameterBackground` is better.
It's like the colors for https://code.visualstudio.com/api/references/theme-color#symbol-icons-colors

**Comment by jrieken** [comment]
The colors are now

```
editorInlayHint.foreground
editorInlayHint.background
editorInlayHint.typeForeground
editorInlayHint.typeBackground
editorInlayHint.parameterForeground
editorInlayHint.parameterBackground
```

The first two are the default for the corresponding latter colors but that might change as we tweak themes
