### ISSUE TITLE
TIMELINE history beyond file renames using --follow

### ISSUE THREAD

**Issue by kenbankspeng** [microsoft/vscode#133606]
Under file EXPLORER is TIMELINE, which provides a repo history back until the file was initially committed or until it was renamed.

Git supports a --follow option which allows repo history through renames.

Could  TIMELINE be enhanced to support history beyond a file rename?

Thank you.

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/pull/187174

**Comment by lszomoru** [comment]
Verification steps:
1. Launch the latest version of VS Code Insiders
2. Open a folder/workspace that contains a git repository 
3. Open one of the files from the folder/workspace, make some changes, and commit them
    * Confirm that the commits appear in the Timeline view
4. Rename the file using Explorer or the "Git:  Rename" command, and commit the change
5. Make more changes to the file and commit the changes
    * Confirm that the timeline view shows commits from before and after the rename
