### ISSUE TITLE
Find and replace regex match should include newlines in \s

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#13369]
- VSCode Version: Code - Insiders 1.6.0-insider (98c9e612e2110cbaa6923f649c01fab3df0c9c31, 2016-10-06T18:06:29.844Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04
- Extensions: EditorConfig.EditorConfig-0.3.3, Tyriar.lorem-ipsum-1.0.0, Tyriar.terminal-tabs-0.0.5, Tyriar.theme-glacier-0.0.10, cssho.vscode-svgviewer-1.2.0, felipecaputo.git-project-manager-0.1.15, gerane.Theme-Wombat-0.0.2, ms-vscode.csharp-1.4.1, ms-vscode.typescript-javascript-grammar-0.0.3, ryu1kn.annotator-0.10.0

Reported by @g5codyswartz in https://github.com/Microsoft/vscode/issues/313#issuecomment-252127985

For the text:

```html
<form>
    <fieldset>
        <legend>abc</legend>
```

`<fieldset>\s*<legend>` finds no matches but it should. `<fieldset>$^\s*<legend>` and `<fieldset>\n\s*<legend>` both work.

**Comment by sandy081** [comment]
Duplicates #9051

**Comment by g5codyswartz** [comment]
Thanks for opening up this new issue from my comment @Tyriar
