### ISSUE TITLE
Enable custom validation of Settings through `ConfigurationChangeEvent`

### ISSUE THREAD

**Issue by robole** [microsoft/vscode#133604]
Currently, it is not possible to do custom validation of *Settings* programmatically. There are some options in the *Extension Manifest* (package.json) e.g use a regex to validate a string. However, if you have a group of options (like a checkbox group), and you want to have at least one to be selected, this is not possible to validate. I have this scenario for my extension [Marky Stats](https://marketplace.visualstudio.com/items?itemName=robole.marky-stats), I always want at least one stat to be selected. I can do this validation with the `QuickPick`, but I cannot do the equivalent with the configuration.

![example](https://user-images.githubusercontent.com/3703647/134359293-055929bc-69e5-48f4-8821-062c5166748b.gif)

Currently, you can use the `workspace.onDidConfigurationChange` event to respond to config options being changed, but you can only tell if something has changed or not. This is done through [ConfigurationChangeEvent.affectsConfiguration()](https://code.visualstudio.com/api/references/vscode-api#ConfigurationChangeEvent). It would be great if you could update the API of `ConfigurationChangeEvent` to enable a change to be validated.

**Comment by roblourens** [comment]
How do you want to display validations? Currently you could show a notification or something

**Comment by robole** [comment]
I think reporting the validation error through `window.showErrorMessage()` would be sufficient. You would need the concept of a checkbox group to give inline feedback.

**Comment by roblourens** [comment]
So what's keeping you from being able to do that?

**Comment by robole** [comment]
> So what's keeping you from being able to do that?

As I stated at the outset, you can only tell if something has changed or not. You cannot tell what has changed. You cannot reject a change, which is typically what validation does.

**Comment by roblourens** [comment]
You can read the configuration at any time to see whether the values are valid, using `getConfiguration`. So I don't see what is missing

**Comment by roblourens** [comment]
You can read the configuration at any time to see whether the values are valid, using getConfiguration. But we won't enable custom validation to reject changes like this. You can either show a warning in some other way, or you can change the way your settings work to be able to validate it with JSON schema

**Comment by robole** [comment]
I appreciate your time @roblourens. but I just want to clarify that you wont support a group of options like a checkbox group in future? This is what I would like to validate.  Im just not sure we are on the same wavelength from your response. This is not possible in the JSON schema or the config, you need to go in a different direction if you want to do something like this. 

The only alternative I can think of is to compress those options into a single config property that accepts a formatted string with a set of accepted interpolated parameters, thenyou could use an elaborate regex to validate it. That's not a great solution.
