### ISSUE TITLE
Can't update Visual code

### ISSUE THREAD

**Issue by Yamira26** [microsoft/vscode#133600]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: Microsoft Windows Version 20H2 (Build 19042.1237)

Steps to Reproduce:

1. Click "Hilfe"(help)
2. Click "Suche Updates"(search for updates)
3. Click "Installiere Update"(install update)
4. The View changes to "Update wird installiert..." (in progress)

The view stays that way the whole day until the machine is turned off. Then the view is back to "Suche Updates". I had the issue previously somewhere around 1.47 where I had to uninstall visual code and reinstall the new version manually.

![image](https://user-images.githubusercontent.com/57996669/134345539-adfdb802-dd94-44d7-b922-64c45e7de005.png)

**Comment by joaomoreno** [comment]
If you run `F1 > Developer Tools`, do you see any error?
