### ISSUE TITLE
No visual indication that cell input/output is collapsible

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#133644]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. open an ipynb file
2. inspect a code cell
3. the cell input and output is collapsible but there's no visual clue 

![image](https://user-images.githubusercontent.com/26419852/134436095-d1318ca5-5a12-46e1-ba17-4c51e86accfa.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/132690
