### ISSUE TITLE
After using down arrow key to pick a completion in debug console, Enter doesn't complete it

### ISSUE THREAD

**Issue by justingrant** [microsoft/vscode#133629]
Issue Type: <b>Bug</b>

1. Go to Debug Console
2. Type any identifier that will generate an autocomplete list
3. Press the down arrow key 1-2 times to choose a completion from the list.
4. Press Enter

**Expected:** Because I've interacted with the autocomplete list, my intent is clearly to use autocomplete. The IDE should therefore treat the autocomplete list as if it's focused, and Enter should complete the suggestion without executing the command.
**Actual:** The partial command that I typed is executed.  My intent is ignored. 

BTW, I think that the current behavior is generally correct: If the user doesn't interact with autocomplete, then it's a reasonable assumption that the user doesn't want Enter to complete the suggestion. But if the user *does* interact with autocomplete, then it seems like a mistake to ignore that signal of user intent. 

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id fc815e00-6664-4e31-9edb-1a84fa91e72d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|5.1.0
vscode-eslint|dba|2.1.25
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
node-module-intellisense|lei|1.5.0
template-string-converter|meg|0.5.3
csharp|ms-|1.23.15
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
js-debug-nightly|ms-|2021.9.2017
vetur|oct|0.34.1
convert-css-in-js|pau|1.1.3
rewrap|stk|1.14.0
code-spell-checker|str|2.0.6
vscode-status-bar-format-toggle|tom|2.0.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
dockerwalkthrucf:30369616
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by connor4312** [comment]
Please see here for the reasoning: https://github.com/microsoft/vscode/issues/108439#issuecomment-871521843 and here for the configurable setting: https://github.com/microsoft/vscode/issues/128768#issuecomment-892902058

**Comment by justingrant** [comment]
> Please see here for the reasoning: [#108439 (comment)](https://github.com/microsoft/vscode/issues/108439#issuecomment-871521843) and here for the configurable setting: [#128768 (comment)](https://github.com/microsoft/vscode/issues/128768#issuecomment-892902058)

@connor4312 Yep, I filed this issue after reviewing that one. There's a subtle difference here. The current behavior seems right when if you're not interacting with autocomplete, because having it override what you type is annoying. But if you *are* interacting with autocomplete by using the arrow keys, then it's confusing when Enter doesn't complete. 

I know there's a setting but I don't actually want that setting. I don't want Enter to complete in the debug console *except* when I've declared my intent to use autocomplete by using the arrow keys.

**Comment by roblourens** [comment]
Thanks for the suggestion. I'd rather have consistency here. I don't really see why there should be a difference in behavior based on whether you pressed arrow keys before pressing enter. It would be just as easy to interact with the suggest widget by mistake, then get different enter behavior, as it is to accept a suggestion by mistake.

**Comment by justingrant** [comment]
Would you be open to a PR to add a third choice to the `"debug.console.acceptSuggestionOnEnter"` setting that would allow Enter to complete the suggestion only if the user had interacted with the current completion list? The "has interacted with" state would reset itself every time the completion list was hidden e.g. via ESC or when its contents were changed e.g. by typing another character.

> I don't really see why there should be a difference in behavior based on whether you pressed arrow keys before pressing enter. 

I wondered about this myself too. So before filing this issue, I spent a day observing when I typed Tab and when I typed Enter to complete a suggestion in the preview pane.

There was a pattern. The only times I accidentally pressed Enter (despite my conscious mind knowing it won't work) was when my right hand and my attention was was already focused close to the Enter key and my right hand was "idle" (meaning that it wasn't doing anything else like typing letters). The most common cause of an idle right hand in the neighborhood of Enter is when I just finished using the arrow keys to pick an autocomplete suggestion.

But when I was typing normal commands (without using arrow keys to choose a completion), I always typed Tab to complete the suggestion. Probably because my hands were usually equidistant from Tab or Enter, so there was no need for right-hand muscle memory to dominate.

Others may have a different experience, but for me it was pretty clear.

> It would be just as easy to interact with the suggest widget by mistake, then get different enter behavior, as it is to accept a suggestion by mistake.

It's possible to press any key by mistake, but "just as easy" seems like a stretch. AFAIK, picking completions is the primary use of the down arrow key in the debug console.

The other uses of the down arrow (e.g. navigating through multi-line commands, or going forwards in history after previously using up arrow to navigate back in history) are rare. Also, neither of those cases can happen while the suggestion list is showing, so there'd be no ambiguity about what Enter would do in those cases.

**Comment by roblourens** [comment]
We are not sure about this, don't work on a PR right now, but we can keep it open for discussion, for now
