### ISSUE TITLE
First run doesn't prompt users to select a kernel

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode#133642]
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. Create a new Conda env from the Python terminal. 
2. open an ipynb file. there should be no kernel selected at this point.
3. hit "Run" button in any cell or the "Run all" button in the top toolbar

expected: promoted to select a kernel
actual: nothing happened

 please refer to this video (6'13'' - 6'30'') https://msit.microsoftstream.com/video/12e10840-98dc-ae71-db7b-f1ec19e01ea4?list=studio

**Comment by DonJayamanne** [comment]
Looking at the video, user isn't prompted to select a kernel, even when kernels are available (the kernel picker shows that itmes are available).
Also run button is displayed in the cells, meaning kernels are avaialble.

**Comment by roblourens** [comment]
Should have been fixed in https://github.com/microsoft/vscode/issues/133271
