### ISSUE TITLE
Renaming terminal window

### ISSUE THREAD

**Issue by andy-96** [microsoft/vscode#133662]
Issue Type: <b>Bug</b>

When multiple terminals are open:
1. Right click and click on "Rename" or pressing enter
2. Type desired terminal name
3. Terminal name does not change => Should be changed

VS Code version: Code - Insiders 1.61.0-insider (f66a3e06bcb9f000e5dc0ad0040ff9b32fc75c78, 2021-09-14T05:16:58.370Z)
OS version: Darwin arm64 20.2.0
Restricted Mode: No
Remote OS version: Linux x64 5.0.0-32-generic
Remote OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id dcbe6ea3-078a-4f62-ae06-d36bc93250d2|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.44.1
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.12
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.8
vscode-drawio|hed|1.6.2
rn-full-pack|kel|0.7.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.1
remote-containers|ms-|0.195.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
color-highlight|nau|2.5.0
vscode-singularity|onn|0.5.1
material-icon-theme|PKi|4.10.0
code-settings-sync|Sha|3.4.3
material-theme|zhu|3.11.4
todo-tree|Gru|0.0.214
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.9.1001261101
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by meganrogge** [comment]
Please confirm that this is fixed when you update to the latest insiders

**Comment by andy-96** [comment]
@meganrogge yep, it's fixed, thanks a lot!
