### ISSUE TITLE
Can't set text focus in first line of first cell

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#133702]
Really strange bug.

- VS Code Version:
Version: 1.61.0-insider (user setup)
Commit: 53aff5e347865fe22f9487ebd54dec9db23773b2
Date: 2021-09-23T13:51:38.771Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22458

- OS Version: Windows 11

Steps to Reproduce:

1. Open any notebook. (I've reprod with github-issues and .ipynb files)
2. Add a single cell to the notebook with a single line
3. Try to click in the text of the first line to set the caret.

Doesn't take. It will if you click just slightly below the bottom of the text.
![recording (8)](https://user-images.githubusercontent.com/11685408/134600953-f8bd34e4-ede5-40d9-84e7-b2122a1a4386.gif)

**Comment by rebornix** [comment]
Fixed via e5346784113c927ee03b4df9ced8e7c49a77215f
