### ISSUE TITLE
Add command to generate a .tsconfig file

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#133763]
This would look like a prompt for some common questions followed by creating either the file on disk, or an untitled editor with the contents to be saved. 

Ex questions:
- Are you targeting Node or the browser?
  - Browser:
      - Module is set to ES 2020
      - Target is set to ES 2020
      - Source Map is true
  - Node:
     - Module is set to commonjs
     - Target is set to ES 2020
      - Source Map is true
- Where are your input files located?
    - src/ (default option)
    - source/
    - current folder
    - enter folder name
- Where would you like your output files to be located?
   - lib/ (default option)
   - dist/
   - current folder
   - enter folder name
- Enable TypeScript in strict mode?
   - Yes (default option)
   - No

cc @mjbvz @DanielRosenwasser @gcrev93 @digitarald

**Comment by mjbvz** [comment]
If you run `TypeScript: Go to project configuration` in a js/ts file that is not part of a project, it will generate a ts/jsconfig. It does not prompt the user for more advanced options 

May be a good starting point for this
