### ISSUE TITLE
Test: allow to split an editor into 2 without creating a second editor group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133756]
Refs: https://github.com/microsoft/vscode/issues/132651

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133756%0A%0A&assignees=bpasero)

---

It is now possible to show the same editor side by side in a single tab:

![image](https://user-images.githubusercontent.com/900690/134710578-8f1bd0ee-7aac-4854-a100-b79ebafbd84b.png)

**Testing**
* play around with the new "Split in Group" and "Join in Group" commands for a couple of editors and see if it behaves as you expect (e.g. from tab context menu, or the view menu)
  * the actions should not appear for editors that do not support it (e.g. diff editors)
* an editor that is split into 2 should behave and appear as before splitting it
  * going into split mode or moving out preserves view state (scroll position, selection)
  * clicking on a file in the explorer or elsewhere should reveal the split editor and not open a second editor in the same group
  * the tab label appears as before with the name of the file
  * the editor history entry (recently opened bucket in `Cmd+P`) shows just 1 editor even when it is split and you can reveal it by selecting the entry
* status bar shows the selection of the left or right side and updates when you jump between left and right side
* view state is preserved for both sides (have selection and scroll position on both sides and open another tab and back or reload window and verify it restores, including which side had focus)
  * the same is true for sash sizes even when you switch between multiple split editors
* verify the new commands to focus the left or right side (search for "Focus Side" commands in F1 list)
*  saving an untitled file or using "Save As..." on a file will keep you in split mode after saving
* you can drag and drop split editors into other groups or even other windows and they open with the view state restored
* you can flip the layout between horizontal and vertical via setting or the new action in the split editor toolbar
  * this changes a new setting `workbench.editor.splitInGroupLayout` and thus should apply to all opened split editors
* a new color `sideBySideEditor.border` allows to change the separator border between the two sides

**Comment by paulacamargo25** [comment]
Everything works as expected, good job!
