### ISSUE TITLE
Run by line does not start from first line of code

### ISSUE THREAD

**Issue by nhaliasos** [microsoft/vscode#133781]
Issue Type: <b>Bug</b>

when using jupyter notebook and trying to Run by line mode, in some cells the feature works as expected  while in others it would start in the middle of the code lines inside the cell or not start at all.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (9.26GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/nikos/test38 --remote=wsl+Ubuntu-20.04 --crash-reporter-id 51af61ee-d808-4130-9112-16985889d861|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2711)|
|Memory (System)|18.63GB (15.03GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
remote-wsl|ms-|0.58.2
gitignore|cod|0.7.0
vscode-pull-request-github|Git|0.30.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by nhaliasos** [comment]
i thought i should add few snippets of code as examples where the Run by Line does not start from the first line of code of the cell but rather randomly in a subsequent line:

----example of code contained in a cell-------------------
output_path=Path(absCurrDir+'/outputs/')
try:    
    output_path.mkdir(parents=True, exist_ok=False)
except FileExistsError:
    print('Folder already exists') <----------starts here
else:
    print('Folder ../outputs/  created')

-------another example-----
settings = {}
settings['binWidth'] = 25
settings['normalize']=True
#settings['resampledPixelSpacing'] = None
##important!! unless resampling is done there is geometry mismatch error
settings['resampledPixelSpacing'] = [1, 1, 1]  # This is an example for defining resampling (voxels with size 3x3x3mm)
settings['interpolator'] = 'sitkBSpline'
settings['force2D']=True
settings['verbose'] = True
extractor = featureextractor.RadiomicsFeatureExtractor(**settings) <--------starts here

**Comment by roblourens** [comment]
Sorry for the slow response, we fixed issues in the last release that could cause this, please let me know if you see it with the latest versions of VS Code and the Jupyter extension.
