### ISSUE TITLE
[Accessibility] "document" role is needed for "monaco-hover" class div

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#133773]
CC @isidorn

Similar to [#132275](https://github.com/microsoft/vscode/issues/132275). When Ctrl+K, Ctrl+I is pressed, the focus  moves to mouse hover content where screen readers' browse mode is used. As this is a read-only area, please consider adding "document" role.

**Comment by jooyoungseo** [comment]
I have a better idea. Please use `role = "textbox"` and `readonly = "true" instead of `role = "document"`.

I am suggesting this because `Focus on Output View`(Ctrl+Shift+U) uses this technique, which offers screen readers very satisfactory accessibility.

I can share my test results using insider build once this patch is made.

**Comment by isidorn** [comment]
This makes good sense, thanks a lot for the suggestion.
@jooyoungseo what's the benefit of using a `readonly textbox` instead of a `role = "document"` on the user side?
`role="document"` sounds a bit more precise, since the hover is not actually a `textbox`.

@alexdima do you mind if I add this role to the editor hover? I will also do it for the debug hover.

**Comment by jooyoungseo** [comment]
@isidorn -- We may want to test `role = "document"` first. If that gives us satisfactory usability, I don't think we need to switch to "textbox". I wish I could build the dev version of VSCode on my end to experiment around.

**Comment by isidorn** [comment]
@jooyoungseo here are the steps for getting VS Code built on your machine
https://github.com/microsoft/vscode/wiki/How-to-Contribute
It should just work. So if you have time give it a try, if you hit some issue feel free to ping me.

I think this might be a good place for a code change
https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/hover/hoverWidgets.ts#L27

Also the current role is `tooltip` which seems fitting to me. Maybe a better approach would be if we go to NVDA and suggest to them that if the `tooltip` has focus that they auto switch to browse mode?

**Comment by alexdima** [comment]
@isidorn I am open to tweaking the role to anything that works. But I agree with you that the current `tooltip` role seems appropriate.

**Comment by jooyoungseo** [comment]
Since the [tooltip aria spec](https://www.digitala11y.com/tooltip-role/) doesn't require screen readers to switch to browse mode, the browse-mode activation against tooltip focus goes beyond the scope of a certain screen reader's behavior (e.g., NVDA).

Because tooltip is likely used when a temporary information pops up for a short period of time, screen readers would deliver a new tooltip info via passing-by speech against "tooltip" role. Hence, I would be reluctant to suggest changing the default behavior of screen readers for `tooltip` role. Instead, I would suggest VSCode takes either "document" or "textbox" role for this area. As you know, accessibility markup should contextually be utilized depending on its use case. I think this area better fits with "document" or "textbox" instead of "tooltip".

**Comment by isidorn** [comment]
Makes sense. We could tweak the role start of October and see how it feels.
@MarcoZehe @jvesouza @zersiax for potential feedback

**Comment by jooyoungseo** [comment]
@isidorn -- The suggested path is not found.

> I think this might be a good place for a code change https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/hover/hoverWidgets.ts#L27
>

**Comment by isidorn** [comment]
@jooyoungseo sorry about that, here's a good link
https://github.com/microsoft/vscode/blob/c9e8266ee24f34107ff52d836a4e8f533afb93c5/src/vs/base/browser/ui/hover/hoverWidget.ts#L29

**Comment by jooyoungseo** [comment]
Thanks @isidorn. I was able to build my demo version, but I need your help. In order to test the hover tooltip, I need to trigger an error. However, I was not able to find a way to easily create a detectable syntax error within the demo VSCode since it is a vanilla version without any languageserver extensions.

**Comment by isidorn** [comment]
@jooyoungseo even in vanilla VS Code we have simple language server support. Here's a simple error, save the following content as `test.json` and open it in vanilla VS Code. This file will produce 2 errors since it does not comply with `json` syntax.
```
{
    a
}
```

Hope that helps!

**Comment by isidorn** [comment]
After more thinking I have decided to open an issue on the NVDA side https://github.com/nvaccess/nvda/issues/13047
Let's see what they say, but I think we are using the correct role and we should not change anything here. Thus closing this for now and we can reopen if we decide to change the role in the end.
