### ISSUE TITLE
"Stop Execution" button and notebookInterruptibleKernel key don't work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133776]
We have a button in core which is essentially the same as the Interrupt button, but it never appears because a context key is not updated for kernels that implement interrupt. Not sure what the history is here.

**Comment by greazer** [comment]
Be sure to fix https://github.com/microsoft/vscode-jupyter/issues/7661 at the same time.

**Comment by roblourens** [comment]
You did this right @rebornix? https://github.com/microsoft/vscode/issues/128245
