### ISSUE TITLE
unsaved file is visible when reopen vs code

### ISSUE THREAD

**Issue by tingtien** [Microsoft/vscode#13375]
- VSCode Version: 1.5.3 
- OS Version:10.11.3

Steps to Reproduce:

1.  create new the untitled file and don't save
2.  close VS Code and choose "Don't Save"
3.  Reopen VS Code,  File disappeared
4.  We hope the unsaved file is visible,  but  cannot be saved in the current project (e.g. Sublime)

**Comment by ranjan-ranjan** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/12836

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/101
