### ISSUE TITLE
Test: Webview UI Toolkit 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#133758]
Refs: #94741

- [x] macOS @alexdima
- [x] linux @deepak1556
- [x] windows @rchiodo

Complexity: 4

Authors: @hawkticehurst, @daviddossett

[Create Issue in toolkit repo](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/new?body=Testing+https://github.com/microsoft/vscode/issues/133758&assignees=daviddossett,hawkticehurst)

---

The `Webview UI Toolkit for Visual Studio Code` is a component library made for building webview-based extension UI that matches the native look and behavior of Visual Studio Code itself.

Ahead of a preview release, we want to ensure that developers can easily install the toolkit and get started by following a simple guide.

Here are the scenarios to test:

- Find the Getting Started Guide in the [toolkit repo](https://github.com/microsoft/vscode-webview-ui-toolkit).
- Follow the guide to create a new extension that installs and uses the toolkit.
- Trigger a "Hello world" notification by clicking the `vscode-button` in the extension using `vscode.window.showInformationMessage`
- Switch to dark, light, and high-contrast themes and verify that elements appear as expected.
- Add an instance of each remaining component to the webview HTML and verify they render as expected. Browse the docs to see examples of each component's "Basic Usage".
- Try different ways to break the components!

**Comment by gjsjohnmurray** [comment]
Tantalising info here, but the toolkit repo link gives me a 404, so I guess it isn't open source yet.

**Comment by daviddossett** [comment]
@alexdima @deepak1556 @rchiodo please push this to the end of your items to test. The package won't be ready until Tues AM due to a publishing snafu.

cc @hawkticehurst

**Comment by rchiodo** [comment]
@daviddossett do you have an ETA? Should I wait till PM?

Npm package gives me a 404:

```
D:\Source\test_webview_toolkit\webview-helloworld>npm install --save @microsoft/vscode-webview-ui-toolkit
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@microsoft%2fvscode-webview-ui-toolkit - Not found
npm ERR! 404
npm ERR! 404  '@microsoft/vscode-webview-ui-toolkit@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aku91\AppData\Roaming\npm-cache\_logs\2021-09-28T17_02_46_677Z-debug.log
```

**Comment by daviddossett** [comment]
I think that would be ideal, yes. We just cleared the 24hr period where we couldn't republish. It should be up soon. @hawkticehurst can update this thread when it's ready.

**Comment by hawkticehurst** [comment]
Was finally able to publish! @alexdima @deepak1556 @rchiodo you're good to go!

**Comment by hawkticehurst** [comment]
Also as a quick heads up @misolori just pointed out an error with part one of the getting started guide, so I'll be pushing a quick change for that momentarily.

**Comment by hawkticehurst** [comment]
Alright, the guide issue has been fixed!

**Comment by deepak1556** [comment]
Really well crafted starter documentation and playground setup 👍

**Comment by gjsjohnmurray** [comment]
> Really well crafted starter documentation and playground setup

Itching to take a look, When will the repo go public?

**Comment by daviddossett** [comment]
> Itching to take a look, When will the repo go public?

Stay tuned! Very soon.

**Comment by gjsjohnmurray** [comment]
> Stay tuned! Very soon.

Confirming that it is now available 🎉
