### ISSUE TITLE
Enable Italics setting for font families (Cascadia Code for example).

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#133721]
Issue Type: <b>Feature Request</b>

I want to use Cascadia Code italics for VSCode. I can do that by installing just the italics .ttf files of the Cascadia Code. However, once I install Windows Terminal Preview it all goes for a toss as it installs the normal versions of the Cascadia Code font family (i assume)
the cursive font faces look amazing and make coding bit more fun ( personal opinion)

expected: there should be a simpler way to enable the italics for VSCode.
the current way of enabling italics is very tedious.

VS Code version: Code - Insiders 1.61.0-insider (53aff5e347865fe22f9487ebd54dec9db23773b2, 2021-09-23T13:51:38.771Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by sbatten** [comment]
@sanket-bhalerao this does not sound quite right. Cascadia Code has italics in its "normal versions." Whether or not a token in code is italic is dependent on text mate rules. 

e.g. I am using the following settings to set italics:

```json
"editor.tokenColorCustomizations": {
	"textMateRules": [
		{
			"scope": [
				"comment",
				"keyword.control",
				"keyword.operator.new",
				"storage.modifier",
				"storage.type",
			],
			"settings": {
				"fontStyle": "italic"
			}
		}
	],
},
```
