### ISSUE TITLE
window crashed (reason: 'crashed', code: '-1073741819')

### ISSUE THREAD

**Issue by DerivativeMarmot** [microsoft/vscode#133700]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.60.2.0
- OS Version: Windows 10 21H1 (19043.1237) Professional

Steps to Reproduce:
1. [issue #132945](https://github.com/microsoft/vscode/issues/132945) does not give a solution
2. dmp files below
[reports.zip](https://github.com/microsoft/vscode/files/7221132/reports.zip)

**Comment by moshem1234** [comment]
I've been having this same issue repeatedly and can't leave it open. Let me know if you figure out how I can fix this.

**Comment by jonechoulover** [comment]
I have also encounter the same problem, If you solved,please tell me how  ,thank you so much.

**Comment by deepak1556** [comment]
Thanks for the crash logs, can you also attach the output of `code --verbose`.

**Comment by DerivativeMarmot** [comment]
> Thanks for the crash logs, can you also attach the output of `code --verbose`. Also are you running the application as administrator ?

![image](https://user-images.githubusercontent.com/78244769/135385329-e5f0dc3d-8611-4c81-87a2-bbac1282924b.png)

surprisingly, my VSCode back to normal two days ago. I have no idea how it fixed itself.

**Comment by deepak1556** [comment]
Thanks for checking back, I will close the issue for now. Can reopen if the issue persists.
