### ISSUE TITLE
C++ always warning auto etc even changed cpp standard to c++17

### ISSUE THREAD

**Issue by memayo** [microsoft/vscode#133791]
I have changed every C++ standard related settings to C++17 (including C/C++ extension, c_cpp_properties etc), but it still warning like auto, emplaces methods that are c++11 features etc, very annoying! Even I have uninstalled the C++ extension, same warning!

**Comment by memayo** [comment]
<img width="721" alt="Screenshot 2021-09-25 at 13 28 41" src="https://user-images.githubusercontent.com/56354990/134759686-df84c1a8-60f1-4131-9c98-1fca7d962de0.png"
<img width="738" alt="Screenshot 2021-09-25 at 13 28 55" src="https://user-images.githubusercontent.com/56354990/134759694-fba65309-c2c3-4826-838e-b1bf8d05cd6a.png">
<img width="721" alt="Screenshot 2021-09-25 at 13 29 14" src="https://user-images.githubusercontent.com/56354990/134759703-30f963fc-5e60-49f4-b9fe-4ec7e196cd4b.png">
>

**Comment by memayo** [comment]
<img width="721" alt="Screenshot 2021-09-25 at 13 29 58" src="https://user-images.githubusercontent.com/56354990/134759722-85ef121e-4350-4275-b112-8dc86f13c4b4.png">
<img width="1000" alt="Screenshot 2021-09-25 at 13 30 10" src="https://user-images.githubusercontent.com/56354990/134759728-18d9b78d-62fa-402b-afc5-aed0a6f85fe3.png">
<img width="721" alt="Screenshot 2021-09-25 at 13 30 36" src="https://user-images.githubusercontent.com/56354990/134759737-0da10895-faa1-4d93-bb9c-7567062fe9d2.png">

**Comment by IllusionMH** [comment]
/extCpp

These diagnostics are provided by extension. Please report this problem in extension's repo.
