### ISSUE TITLE
 Add the outline display function

### ISSUE THREAD

**Issue by xiongsisi** [Microsoft/vscode#13376]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. i wish the newest version can  add the outline display function,like in Visual Studio 2012
![jg p eq j1pzctgjven](https://cloud.githubusercontent.com/assets/13955666/19211574/270c1cb4-8d72-11e6-8f84-ccedd790ed1c.png)

**Comment by leaxoy** [comment]
duplicate with #5605

**Comment by isidorn** [comment]
@leaxoy thanks for pointing out this is a duplicate
