### ISSUE TITLE
Terminal text invisible when running Codespaces on Safari 15.0

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode#133710]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:58:31.782Z (1 day ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
- OS Version: macOS 11.5.2

Steps to Reproduce:

1. Visit any Codespaces
2. Start typing in terminal

![Screen Shot 2021-09-24 at 00 09 05](https://user-images.githubusercontent.com/10591665/134616797-529e6bc8-57ce-4b24-bc8a-4522f5642d2e.png)

**Comment by TarunavBA** [comment]
Can you provide a **Gif** not a picture showing the issue?

**Comment by rongxin-liu** [comment]
Sure, here it is:
[https://media.giphy.com/media/mrhMgWOV9AnkRnrmKX/giphy.gif?cid=790b7611b01cff118a30e66d5190790b0a5cc0d2a8ca0a11&rid=giphy.gif&ct=g](https://media.giphy.com/media/mrhMgWOV9AnkRnrmKX/giphy.gif?cid=790b7611b01cff118a30e66d5190790b0a5cc0d2a8ca0a11&rid=giphy.gif&ct=g)

**Comment by curiouskiwi** [comment]
For clarity, in the above example that I provided to @rongxin-liu, I am typing in the (invisible) terminal

```
cd <enter>
code newtext.txt <enter>
``` 

and the file then opens in the editor.

**Comment by jkeech** [comment]
As a workaround, you can set GPU Acceleration (`terminal.integrated.gpuAcceleration`) to `off`:

![image](https://user-images.githubusercontent.com/746020/134705514-e44674cd-038e-43ce-8b3f-c309d7499116.png)

**Comment by mego22** [comment]
Just ran into this today. Thank you for the work around.

**Comment by jkeech** [comment]
Confirming this is fixed in Codespaces now. Thanks!

**Comment by MaevaBtd** [comment]
Thank you, it fixed it on Windows/Firefox
