### ISSUE TITLE
Cannot run MATLAB code in Visual Studio Code

### ISSUE THREAD

**Issue by quanganh2001** [microsoft/vscode#133714]
Hello everyone, this is the first time I write issue in Github

Here is my settings in file settings.json

![Settings json](https://i.imgur.com/P45aEDo.png)

Today I got this error:

![Error when run MATLAB code](https://i.imgur.com/Zcw1ji3.png)

Although I install MATLAB extension, matlab-formatter and MATLAB Code RUN but it doesn't run MATLAB code and it error: Code language not supported or defined.

Can someone else help me to fix this error?

 Thank you so much

**Comment by sbatten** [comment]
Please seek assistance at the extension's repository https://github.com/Gimly/vscode-matlab
