### ISSUE TITLE
default charset problem when debugging in integrated console

### ISSUE THREAD

**Issue by rmchenhy** [microsoft/vscode#133765]
Issue Type: <b>Bug</b>

My system language is Chinese, so the default charset in Windows Powershell is GBK. However, when I try to debug a program in the VS Code integrated console, which is actually Windows Powershell, its default charset is UTF-8 and this causes the Chinese characters mistakenly displayed when debugging.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.97GB free)|
|Process Argv|--crash-reporter-id d354c8e5-b552-451d-a6b4-0be0ff4276e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.20.2
vscode-language-pack-zh-hans|MS-|1.60.4
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
markdown-preview-enhanced|shd|0.6.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by rmchenhy** [comment]
This problem didn't occur one month ago.

**Comment by Tyriar** [comment]
Try tweaking the setting `terminal.integrated.detectLocale`

**Comment by meganrogge** [comment]
@Tyriar can't think of a very recent change that would cause this.
