### ISSUE TITLE
Possible to expose window.menuBarVisibility as a Remote and Workspace setting?

### ISSUE THREAD

**Issue by dmalan** [microsoft/vscode#133786]
At the moment, the `window.menuBarVisibility` setting only seems to be available as a User setting. Might it be possible to expose that as a Remote and Workspace setting as well? For educational use cases, particularly with first-time programmers familiar with common menus like **File**, **Edit**, et al. but not VS Code itself, we'd ideally provide students with instructions like **File > New File** and **Terminal > New Terminal**, but when the menuBar defaults to `compact`, it's less obvious to students where those menus are hidden. Ideally, we'd enable the menuBar by default via a Remote setting.

Thank you!

CC @rongxin-liu

**Comment by sbatten** [comment]
cc @sana-ajani

**Comment by sbatten** [comment]
@sana-ajani I don't think exposing this setting is necessarily the only/right solution to the problem, but familiar layouts for education purposes sound like they are in your space

**Comment by sbatten** [comment]
I think this is covered by profiles
