### ISSUE TITLE
Windows 11 look & feel

### ISSUE THREAD

**Issue by ProCode-Software** [microsoft/vscode#133774]
Issue Type: <b>Feature Request</b>

If a Windows 11 user uses VS Code, it would be nice to have VSCode look like UI in other Windows 11 apps. Example: Menus, acrylic surfaces, etc.
Thanks

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No

**Comment by Hashimlokasher** [comment]
It should feel same as the image attached
[Image ](https://cmsphoto.ww-cdn.com/superstatic/41269/art/grande/57515481-42596798.jpg?v=1625489993.7321959&force_webp=1)

**Comment by misolori** [comment]
Thanks for the feedback. Please see #115641 where we are tracking a similar request. Will be closing this one as a duplicate.
