### ISSUE TITLE
suggestion: keybinding for `find all implementations`

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#133726]
![image](https://user-images.githubusercontent.com/1876302/134665147-0be46f52-d61e-44e6-a17d-dfa340e3d447.png)

maybe we could add a new keyshortcut <kbd>Shift+Alt+F11</kbd> for `find all implementations`

**Comment by IllusionMH** [comment]
You can already add key binding you like to this action.
**File** > **Settings** > **Keyboard Shortcuts**, search for `references-view.findImplementations`, and click on plus sign.

**Comment by heartacker** [comment]
yes I Know, And I just hope that It could be by official

**Comment by jrieken** [comment]
Will be very hard to find a free keybinding for this...
