### ISSUE TITLE
My terminal does not work

### ISSUE THREAD

**Issue by Sambhav-Saraswat123** [microsoft/vscode#133795]
Issue Type: <b>Bug</b>

If I open my terminal it shows a blank area and there is nothing
The new terminal button also shows Javascript debug terminal only

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.70GB free)|
|Process Argv|--crash-reporter-id 94bcf889-9866-49dd-bc24-df6d7a47db5d|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.6.14
path-intellisense|chr|2.4.0
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
auto-rename-tag|for|0.1.8
code-runner|for|0.11.5
vscode-yarn|gam|2.0.0
fluent-icons|mig|0.0.12
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
live-server|ms-|0.2.8
vscode-react-native|msj|1.6.1
color-highlight|nau|2.5.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.10.0
material-product-icons|PKi|1.1.1
vscode-thunder-client|ran|1.9.1
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
code-spell-checker|str|2.0.7
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.12.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgsc2:30361791
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by chetanpatil1984** [comment]
Facing same issue. Please refer to attached screenshot.

<img width="1918" alt="issue" src="https://user-images.githubusercontent.com/3284711/134807562-4ce1a832-2f88-489d-831f-ea9184af0e7c.PNG">

**Comment by meganrogge** [comment]
any errors in the dev tools console? 

also, what happens if you set `terminal.integrated.useWslProfiles`: false?
