### ISSUE TITLE
SCM: Allow sorting of repositories

### ISSUE THREAD

**Issue by kthr** [microsoft/vscode#133759]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (Universal)
- OS Version: Darwin x64 20.6.0

Steps to Reproduce:

I'm working in a workspace with multiple folders added where each contains a number of git repositories. These respositories are reordered in Source Control almost each time I reopen the workspace. If there are a lot of repos this creates a lot of confusion. Apparently repositories are sorted for each path but paths are reordered randomly.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16030001/134713448-2e79ac32-2a32-4375-b349-96c16adcb522.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16030001/134713493-9596c02a-fa80-411b-8bfd-3b1a20f1af15.png">

Here is a small bash script to create shown repositories and a workspace.code-workspace file under ./repos (try at you own risk):
[create_repos.sh.zip](https://github.com/microsoft/vscode/files/7227405/create_repos.sh.zip)

**Comment by lmapii** [comment]
I'd second this request. Our projects include 100+ repositories, being able to sort the repos in the "Source Control Repositories" view would help a lot.

**Comment by conFusl** [comment]
Strongly agree with @lmapii - this feature would be awesome² as with an increasing number of repos in the project you really loose overview.

**Comment by lszomoru** [comment]
No update on this issue. I will try to take a look at this during the February milestone.

**Comment by lmapii** [comment]
That would be great, thanks!

**Comment by lszomoru** [comment]
Tomorrow's Insiders release (2022-03-22) [has changes](https://github.com/microsoft/vscode/commit/e5872fd73fbc2f07b8be1827deac4982140e12e8) so that the list of repositories is always sorted by name both in the "Source Control Repositories" and "Source Control" views. Give it a try a let me know if you see any issues related to sorting. Thanks!

**Comment by lmapii** [comment]
Can't wait! Will try it out as soon as the build is available.

**Comment by rzhao271** [comment]
Marking as verified based on https://github.com/microsoft/vscode/issues/133759#issuecomment-1074975601

**Comment by lszomoru** [comment]
Quick update on this capability. Today's Insiders release (2022-04-14), contains two changes related to repository sorting:

- The default sorting was reverted to be by discovery time, which was the original behaviour
- A new setting `scm.repositories.sortOrder` was added that can be used to control the repository sorting (discovery time, name, path)

**Comment by lmapii** [comment]
You had me worried there for a second :D. I was enjoying sorted repositories so much. Just checked the new insiders release, for me it is working nicely.

**Comment by simonhermann** [comment]
@lszomoru 
We have a specific order that makes more sense than alphabetical/etc.
Please add an option to restore the previous behavior, where the order was defined by the order of "folders" in workspce settings.
Alternatively we could use the folder "name". I'd have expected it to be used for sorting, but it does not seem so?

```
"folders": [
    {
      "name": "1-FE",
      "path": "my-frontend"
    },
...
```

**Comment by lszomoru** [comment]
@simonhermann, the current Insiders release and the next Stable release will have a setting, `scm.repositories.sortOrder`, to control the default sort order in the "Source Control Repositories" view. Setting the setting to `discovery time` (default value), will restore the original behaviour and respect the order of folders in the workspace file.

**Comment by simonhermann** [comment]
Hi @lszomoru That sounds great! Thanks for your quick answer and your work on this amazing tool! 🙇
