### ISSUE TITLE
Unable to run cells (run icons disappears on hover)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#133784]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest insiders
- OS Version: Mac

Steps to Reproduce:

1. Select a cell, attempt to run another cell using the mouse
2. When hovering over the run cell icon, it disappears just when the mouse is over the run icon
I.e. its impossible to run a cell as I cannot get the icon to stay visible.

![catchmeifyoucan](https://user-images.githubusercontent.com/1948812/134749322-fe0219d0-bfec-4167-ba75-2eb1a887c400.gif)

I've been running into this for two days now

**Comment by rchiodo** [comment]
Thought it was just me. I hit this as well.

**Comment by misolori** [comment]
<img width="503" alt="CleanShot 2021-09-24 at 18 38 26@2x" src="https://user-images.githubusercontent.com/35271042/134753567-ba00cc54-dc82-4e7f-82d9-627d2fbd8f62.png">

I believe the top cell toolbar is getting in the way

**Comment by roblourens** [comment]
Will use https://github.com/microsoft/vscode/issues/133702 for this
