### ISSUE TITLE
Test: indication of deleted/readonly editor labels via decorations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133743]
Refs: https://github.com/microsoft/vscode/issues/130526

- [x] anyOS @isidorn 
- [x] anyOS @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133743%0A%0A&assignees=bpasero)

---

Previously we used to append either "deleted" or "readonly" or even both to the label of an editor in case the editor was readonly or deleted. To produce shorter editor labels, we now use decorations for this purpose:

![image](https://user-images.githubusercontent.com/900690/134696983-7b00c818-fdae-42f8-995c-7e93de1a0763.png)

**Testing**
* open a file as editor and delete the file externally (from a OS explorer or second window) and verify you see the decoration that the file is deleted and when you save the decoration disappears again
* open readonly files (for example anything on the "Index" when you have staged changes in git) and verify you see a lock icon in the editor label
* the hover should give you a hint about the meaning of the lock icon

**Note:** the readonly decoration will not appear for when a file is readonly on disk. It is meant for files that are marked readonly by the file system provider.

**Comment by jsoref** [comment]
Personally, I'd encourage you to use 🗑️ for deleted similar to 🔒 for readonly instead of ~strikethrough~ as the latter makes things fairly unreadable.
