### ISSUE TITLE
clear recently opened files list in ther start menu

### ISSUE THREAD

**Issue by CuiiGen** [microsoft/vscode#133704]
The `Recent Folders` list of vs code in start menu will be cleared if we `Clear Recently Opened` in vscode, while not the `Recent files`. That makes quite confuse why the `Recent Files` list is not cleared and I need to clear it by right click and remove them one by one.

**Comment by sbatten** [comment]
we are using an electron api for this, I am not sure if this is by design, a limitation, or a bug on electrons side.

**Comment by deepak1556** [comment]
This is a limitation from the runtime, closing as not actionable.
