### ISSUE TITLE
Test: Allow to split an editor into an existing group

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133745]
Refs: https://github.com/microsoft/vscode/issues/133260

- [x] anyOS @alexdima
- [x] anyOS @DavidKutu

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133745%0A%0A&assignees=bpasero)

---

We always had commands to split the active editor into any direction by creating a new editor group for it. Now we added other commands to split editors into an existing group if one is present at the location to prevent creating new groups over and over.

![image](https://user-images.githubusercontent.com/900690/133783794-d3dae4ad-24e7-450d-997d-90b9197a686b.png)

**Testing:**
* verify the commands as listed in the screenshot above work as you expect them to work (a group will open if none exists but a group will be reused otherwise)

**Comment by gjsjohnmurray** [comment]
For a native English speaker `Above Group` and `Below Group` are clunky. How about changing them to `Group Above` and `Group Below`?

**Comment by bpasero** [comment]
@gjsjohnmurray yeah, there is even more commands that use this wording:

![image](https://user-images.githubusercontent.com/900690/134712369-0a971a8e-6777-4332-9648-70f1c8e163cc.png)

**Comment by bpasero** [comment]
Fixed the ones using "Above" or "Below". Now I wonder about others like "View: Move Editor into Left Group", should they be renamed as well? E.g. "View: Move Editor into Group to the Left" (more verbose though).

**Comment by gjsjohnmurray** [comment]
> Now I wonder about others like "View: Move Editor into Left Group"

@bpasero no, I don't think these need to be changed.

**Comment by DavidKutu** [comment]
I guess this is intended, but wouldn't it make sense to move the file to the editor group instead of opening a copy? Is there a setting for this?
![Uploading image.png…]()

**Comment by bpasero** [comment]
Sorry what am I looking at?

**Comment by DavidKutu** [comment]
The files are the same on both editor groups. I expected them to be moved, not copied.

**Comment by gjsjohnmurray** [comment]
@DavidKutu which command did you use? The "Split Editor into *" ones open a tab in the target group for the same file. The tab you were on when you ran the command remains. The "Move Editor into *" ones move the focused tab to the target group.

**Comment by DavidKutu** [comment]
I used the `Split` commands. But good, looks like its intended and there's another command for what I wanted.
