### ISSUE TITLE
Cannot Remove Keybiding

### ISSUE THREAD

**Issue by oleg-slapdash** [microsoft/vscode#133708]
Issue Type: <b>Bug</b>

1. Open Keyboard Shortcuts
2. Find "File: Open..." command
3. Right Click
4. Select "Remove Keybiding"
5. Nothing happens.

Setting condition to `false` does not help either.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

![2021-09-23 22 50 06](https://user-images.githubusercontent.com/73438352/134611001-00d0a5ff-06f7-4969-a18f-ea92b4c916a7.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 7, 6|
|Memory (System)|32.00GB (9.25GB free)|
|Process Argv|-psn_0_46246936 --crash-reporter-id 598b540e-1f56-4323-af49-94f26544babf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-modules|cli|0.3.2
js-codeformer|cms|1.27.0
jsrefactor|cms|3.0.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
pgsql|dou|0.1.3
gitlens|eam|11.6.0
prettier-vscode|esb|9.0.0
auto-rename-tag|for|0.1.8
stylelint-disable-snippets|hed|1.0.3
search-node-modules|jas|1.3.0
intellij-idea-keybindings|k--|1.4.5
refactorix|kri|0.3.6
git-graph|mhu|1.30.0
vscode-duplicate|mrm|1.2.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
color-highlight|nau|2.5.0
tsserver-live-reload|rbu|1.0.1
partial-diff|ryu|1.4.3
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.4.5
rewrap|stk|1.14.0
code-spell-checker|str|2.0.6
move-ts|str|1.12.0
vscode-stylelint|sty|0.86.0
vscode-open-in-github|sys|1.15.0
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@alexdima Above action is adding following entry to the `keybindings.json` file.

```
 {
        "key": "cmd+o",
        "command": "-workbench.action.files.openFileFolder",
        "when": "isMacNative && openFolderWorkspaceSupport"
    }
```

It seems the `KeybindingsService` is giving this keybinding even though it is negated

**Comment by alexdima** [comment]
This is caused by `isMacNative` being resolved to the constant `false` or `true` during deserialization, which leads to a strict equality check to fail somewhere in the kb resolver.
