### ISSUE TITLE
VS Code 1.60.2 discards the first scroll event (either up or down) when first gaining window focus (Arch Linux)

### ISSUE THREAD

**Issue by charbelnicolas** [microsoft/vscode#133744]
Issue Type: <b>Bug</b>

1. Open a file in VS Code where there is enough content to be scrollable.
2. Position your cursor where the content can be either scrolled up or down.
3. Switch focus to another window other than VS code.
4. Switch back focus to the VS Code window and DO NOT CLICK ON ANYTHING, just position your cursor on top of the editor content and do a SINGLE scroll either up or down.
5. You will see that nothing moves.
6. Do another single scroll.
7. You will see that it now scrolled.

Now, repeat the same process as before from step 1 to 3. On step 4, when you switch back to the VS Code window, this time, do a SINGLE click on the editor to set your cursor position, then do a SINGLE scroll.

What happened? It didn't scroll again even though the editor HAS FULL FOCUS.

You can also trigger this by dragging the tabs from the tab bar around and then positioning your cursor on top of the editor and trying to scroll up or down again.

Somehow VS Code is eating/discarding the first scroll event, either if it's up or down which the user perceives as lag since it adds quite a bit of delay when first starting to scroll.

This also happens on the latest insider build and also occurs when all extensions are disabled.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.14.7-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 2405)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.31GB (29.06GB free)|
|Process Argv|--crash-reporter-id 7fcea4a6-0799-485e-92b2-c7624057c249|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-vscode|sve|105.4.0

</details>

**Comment by charbelnicolas** [comment]
I just realized this also happens on chromium, so it might be an upstream bug...

**Comment by charbelnicolas** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1252801

**Comment by jkt628** [comment]
i've noticed for a while, 2 weeks? 4 weeks?, that when i had the focus on another window then hover over a vscode scroll bar, the indicator lights up like it should but nothing happens when i grab it.  i have to grab it a second time before scroll succeeds.
Kubuntu 21.10
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:36.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-30-generic snap

**Comment by deepak1556** [comment]
Updated upstream issue link: https://bugs.chromium.org/p/chromium/issues/detail?id=608246

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/28795
