### ISSUE TITLE
Reversal of scrolling is ignored

### ISSUE THREAD

**Issue by milanaleksic** [Microsoft/vscode#13378]
- VSCode Version:1.5.3
- OS Version: Debian 8 (XFCE)

Steps to Reproduce:

1. In mouse setting set trackpad to use reverse scrolling [1]

2. observe that scrolling is not reversed as it is in Chrome, other editors (vim/gvim, sublime text) and basically all other system applications

[1] ![screenshot](https://i.imgur.com/qhqu88B.png)

**Comment by alexandrudima** [comment]
@milanaleksic There is a workaround:

`"editor.mouseWheelScrollSensitivity": -1`
