### ISSUE TITLE
Extension pack should not be available for install if all it's extension are not available

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#133717]
1. https://github.dev
2. Extensions view -> search for "azure"
3. Notice how Azure Extension Pack can be download
4. None of the extensions work in the Web inside the extension pack. Thus it should also not be available

fyi @spboyer

![Screenshot 2021-09-24 at 09 54 18](https://user-images.githubusercontent.com/1926584/134638900-4c396270-d7d5-46da-a7a4-32c4c11a6677.png)

**Comment by sandy081** [comment]
@isidorn We do not have upfront information to know if all extensions are supported or not unless we get all extensions. Hence the install action is not disabled.

Please check here - https://github.com/microsoft/vscode/issues/132549#issuecomment-922843592

Happy to take suggestions (lets continue discussion in above issue)
