### ISSUE TITLE
GitHub extension is asking for permission to login to GitHub

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#133793]
I was reviewing the clone repo flow. In usertesting had a few cases where this was really exciting for users to discover.

One odd aspect is the permission dialog that made me pause in his otherwise extremely smooth flow:

<img src=https://user-images.githubusercontent.com/8599/134759982-5a0f993b-bb4d-473a-963f-c2054c178a25.png width=400 />

Why does a built-in extension ask for permission? From the user's perspective, this is VS Code functionality and they never installed a GitHub extension.

**Comment by 0cjs** [comment]
I'm not clear on why it's asking for a login at all, at times. My first experience with web VSCode was clicking "Open Remote Repository," giving it `https://github.com/0cjs/8bitdev`, and being told that I must give VSCode some sort of access to my GitHub account for no reason at all. (`git clone` on that URL pulls down the whole repo without problems; no authentication is necessary.) Even if I were inclined to to immediately give this application access to my GitHub account, I wasn't inclined to log in to GitHub at all on the not-well-trusted machine I happened to be using at the time.

The initial user experience probably should not be, "give us access to sensitive stuff that we don't actually need so you can see a simple demo."

**Comment by joyceerhl** [comment]
Note that without authentication, we can easily run into GitHub API rate limits (60 calls / hour), and that's the primary reason that we do not support unauthenticated access to repos at the moment.

**Comment by 0cjs** [comment]
Yes, but the OP is just trying to clone the repo, which (as I mentioned in [my other comment](https://github.com/microsoft/vscode-remote-repositories-github/issues/74#issuecomment-987704862)) doesn't require GitHub's proprietary API. (`git clone` works just fine without using GitHub's API.) So why not just clone the repo the way you'd clone a repo from another, non-GitHub source?

**Comment by joaomoreno** [comment]
@TylerLeonhardt I couldn't find a "allowed extensions to login to specific auth providers" mechanism. Do we have one?

**Comment by TylerLeonhardt** [comment]
@joaomoreno it's in the project.json now.

**Comment by joaomoreno** [comment]
Oh this is only specific to code-oss. We already do this for stable and insiders. I suggest closing this issue.
