### ISSUE TITLE
Provide more precise message when debugger is disabled

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#133728]
If a debugger is disabled via a `when` clause we should provide a more specific error message and not the usual "debug type xyz not supported". We should say something like "debug type xyz is installed but not supported in this environment"

This is nothing for September.

**Comment by roblourens** [comment]
I did add this message

https://github.com/microsoft/vscode/blob/fad4a5f50ca0b975e81468d818ec6e51e7bcbe34/src/vs/workbench/contrib/debug/browser/debugService.ts#L496-L496

**Comment by roblourens** [comment]
I like your message better

**Comment by isidorn** [comment]
I missed that! Yeah my message is a bit more precise so user does not get puzzled.
