### ISSUE TITLE
Open the side terminal in the editor, the terminal cannot be killed (closed)

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#133722]
Issue Type: <b>Bug</b>

Open the side terminal in the editor, the terminal cannot be killed (closed) by the right-click menu command

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

![2021-09-24_175721](https://user-images.githubusercontent.com/54253524/134657520-b2ce45df-6da0-44ac-90d5-ddf7b87efd24.png)

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by zhouxinghong** [comment]
This affects development in full screen mode

**Comment by meganrogge** [comment]
verify that:
- with or without moving the terminal editor to the side, you can kill it using the context menu
- with or without terminals in the panel, you can kill it using the context menu and it doesn't impact the terminals in the panel

**Comment by zhouxinghong** [comment]
> verify that:
> 
> * with or without moving the terminal editor to the side, you can kill it using the context menu
> * with or without terminals in the panel, you can kill it using the context menu and it doesn't impact the terminals in the panel
Can’t kill and shut down with the right-click command on my machine? ? ? It's unknown for what reason? ? ? I use version 1.60.2

**Comment by meganrogge** [comment]
@zhouxinghong it's fixed in insider's, not 1.60.2

**Comment by zhouxinghong** [comment]
> @zhouxinghong它已在内部人员中修复，而不是 1.60.2

Hello! Which version is it? Is it version 1.61?

**Comment by zhouxinghong** [comment]
> @zhouxinghong it's fixed in insider's, not 1.60.2

Hello! Which version is it? Is it version 1.61?

**Comment by TylerLeonhardt** [comment]
@zhouxinghong yes you should be able to get VS Code insiders: http://code.visualstudio.com/insiders and verify if it's fixed there.

**Comment by zhouxinghong** [comment]
Thank you for your patience! I will try again after 1.61 is released.
