### ISSUE TITLE
Preview not Rendering

### ISSUE THREAD

**Issue by Wayfiding** [microsoft/vscode#133772]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.2
7f6ab5485bbc008386c4386d08766667e155244e

x64

- OS Version: openSUSE Tumbleweed
- Kernel: Linux 5.14.5-1-default
- Architecture: x86-64

Steps to Reproduce:

1.Just create any README.md file and try to preview it and will show nothing. 
 
 
 I tried everything: reinstall code, reinstall the OS but none of those things help get back the preview. I could take some log that is on this image below: 
 
 ![Preview_problems](https://user-images.githubusercontent.com/72744170/134728342-f148ba76-186b-4d66-8b85-7486f4c499a6.png)

I don't know how to fix it. It's a little beyond my knowledge.

**Comment by Wayfiding** [comment]
I kept coding and another thing seems to be not working, as well my extension on extession sessions don't show any details or changelogs: 
![Another_thing_not_working](https://user-images.githubusercontent.com/72744170/134781812-adea744d-fdfb-4e0b-a312-d668367312b2.png)
![Another_pic](https://user-images.githubusercontent.com/72744170/134781819-53d08b34-6986-4690-8d98-0b6b629e2ee1.png)

![Another_pic2](https://user-images.githubusercontent.com/72744170/134781825-85948e39-97a6-43f0-8982-138058df80d1.png)

I can't open too the Developer tools, and can't find a proper logs to understand why this is not showing. I don't know if its a problem with a wrong library or any kind of this stuff, as I don't have any log or knowledge to solve this.

**Comment by Wayfiding** [comment]
For somehow the installation with Zypper Package Manager is bugged. I unistalled code and removed the config folder of code from $HOME/.config/Code and reinstalled using the Snapd Code.

**Comment by mjbvz** [comment]
Closing as it sounds like it is working with the official install
