### ISSUE TITLE
Extension `when` clause not working for `menuBar/edit/copy` menu

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#133752]
Issue Type: <b>Bug</b>

For the https://github.com/anuraghazra/vscode-strip-ts-copy extension, I tried adding a command as a `editor/context/copy` and `menuBar/edit/copy` menu. Since this extension works on selected TypeScript, I used the when clause `editorHasSelection && editorLangId == typescript`. This works fine for `editor/context/copy`, but for `menuBar/edit/copy` both `editorHasSelection` and `editorLangId == typescript` are false.

Not 100% sure if this is a bug or intended behavior.

Extension `menus` configuration:
```
    "menus": {
      "editor/context/copy": [
        {
          "command": "strip-ts-copy.copyAsJs",
          "when": "editorHasSelection && editorLangId == typescript"
        }
      ],
      "menuBar/edit/copy": [
        {
          "command": "strip-ts-copy.copyAsJs",
          "when": "editorHasSelection && editorLangId == typescript"
        }
      ]
    }
  },
```

Related PR: https://github.com/anuraghazra/vscode-strip-ts-copy/pull/2

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id ae7777ee-c64c-4b3e-aa57-8ec8dc4c2a8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
stylus|Ala|0.0.4
git-rename|amb|1.2.0
svelte-intellisense|ard|0.7.1
markdown-preview-github-styles|bie|0.2.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
dart-code|Dar|3.26.0
flutter|Dar|3.26.0
vscode-markdownlint|Dav|0.44.1
vscode-eslint|dba|2.1.25
binary-plist|dni|0.6.0
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
copilot|Git|1.4.2782
vscode-pull-request-github|Git|0.30.0
sass-lint|gle|1.0.7
go|gol|0.28.0
gc-excelviewer|Gra|3.0.44
svgeditor|hen|2.9.0
vscode-edit-csv|jan|0.6.2
eml|lei|0.4.0
node-module-intellisense|lei|1.5.0
coffeelinter|lky|1.4.0
rust-analyzer|mat|0.2.751
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.58.2
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
debugger-for-chrome|msj|4.13.0
gradle-language|nac|0.2.3
color-highlight|nau|2.5.0
vetur|oct|0.34.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.10.0
color-manager|roy|0.6.2
crates|ser|0.5.9
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
svelte-vscode|sve|105.4.0
sass-indented|syl|1.8.18
vscodeintellicode|Vis|1.2.14
vscode-meteor|vuh|0.1.1
HCL|who|0.0.5
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by sbatten** [comment]
@probablykasper these 2 context keys are not global,  they exist per editor that is open. the global menu bar can only use global context keys. a recommendation would be to create your own custom context key https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context and track active editor changes.

**Comment by probablykasper** [comment]
Makes sense, thanks for explaining
