### ISSUE TITLE
Remote terminal reconnection isn't working

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133741]
Also repro's in stable

**Comment by meganrogge** [comment]
unsure when this started happening. I don't see any open issues about it, which makes me think this is expected in WSL?

**Comment by meganrogge** [comment]
was last working in stable 1.59

**Comment by meganrogge** [comment]
and because it was broken in stable 1.60, we can narrow it down - the breaking change happened in August

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/commit/9fbffef8b8db993adee6a99f27dd1287f2b73fe3#diff-ed5bbcbd535ee6c002cd4cc00cea9e790a0731715b175f66f2439ef308f154e8R27

**Comment by meganrogge** [comment]
looks like perhaps a race condition - get layout info is called w the correct workpsaceId, but then set layout info is called  so might be wiping out the stored info before the reconnect can occur.

**Comment by meganrogge** [comment]
still doesn't work for WSL. based on my investigation, the pty service gets re-created when the window is reloaded, thus losing the `ptys` and `workspaceLayoutInfos` maps

**Comment by meganrogge** [comment]
when connected to localhost via ssh, reloading does persist the terminals 🤔 but I thought this would still be using the `remoteTerminalChannel`...
![Screen Shot 2022-06-06 at 5 20 31 PM](https://user-images.githubusercontent.com/29464607/172270197-f14736a9-f1b9-4722-bedc-f62faef97d6f.png)

**Comment by meganrogge** [comment]
![Screen Shot 2022-06-06 at 5 21 57 PM](https://user-images.githubusercontent.com/29464607/172270293-201b630a-d6c9-4d43-8651-fb126febc00a.png)

**Comment by meganrogge** [comment]
Seeing this though
![Screen Shot 2022-06-06 at 5 25 51 PM](https://user-images.githubusercontent.com/29464607/172270597-ce1f1445-ffbc-465f-ad28-18451bd888c5.png)

**Comment by meganrogge** [comment]
Also working for me in codespaces
https://user-images.githubusercontent.com/29464607/172485009-d1c550bf-5f98-4a95-b189-19c68398b0c8.mov

**Comment by meganrogge** [comment]
sometimes it does work in WSL. interestingly, other state isn't persisted that should be though (see the layout change)
![Recording 2022-06-07 at 13 27 30](https://user-images.githubusercontent.com/29464607/172485935-56b552b5-9072-48e6-8f96-d52c19dee2e8.gif)

**Comment by meganrogge** [comment]
this works on all remote platforms based on my testing. i saw a few times reloading WSL didn't work, but now cannot reproduce

**Comment by Tyriar** [comment]
All seems to work 🎉

**Comment by meganrogge** [comment]
> All seems to work 🎉

/verified
