### ISSUE TITLE
Test: Opening VS Code using macOS CLI

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#133771]
Refs: https://github.com/microsoft/vscode/issues/102975

- [x] macOS @aeschli
- [x] macOS @donjayamanne

Complexity: 4

Authors: @rzhao271, @bpasero, @deepak1556  

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133771%0A%0A&assignees=rzhao271,bpasero,deepak1556)

---

macOS now uses a different code path when opening code-insiders from the terminal. The purpose of this TPI is to check that the new code path hasn't caused any regressions.

1. Open a terminal
2. Run `code-insiders <your-flags-and-args-here>`

An idea of flags/configurations to test:
  - Running code-insiders multiple times. Note that multiple icons showing up in the Recently Opened section of the dock is normal.
  - Running with just `--verbose` and/or `--wait`.
  - Running the program from multiple terminals.
  - Running with the `--status` flag in another terminal.
  - Using the `-d` and `-a` flags.
  - Combinations of `--verbose` and/or `--wait` with the other configurations above.

**Comment by DonJayamanne** [comment]
Found one issue, filed #134030, else LGTM
