### ISSUE TITLE
Inlay hints jump a lot when declaring a local

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#133730]
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/134672430-2f220014-a074-4a48-b7e3-a35edea6fff8.gif)

I think the inlay hint is always correct, i.e. it reflects the expression that I am typing, but this is very distracting, as my cursor is jumping all over the place based on the width of the inlay hint.

**Comment by jrieken** [comment]
Good catch... It almost feels like we should delay certain updates until a typing pause occurs. Or even better update but don't change the width while a line has a cursor

**Comment by jrieken** [comment]
Closing after fixing a couple of things:

* proper cancellation when typing starts a new request while one in flight
* more careful listening to change events from the provider
* high debounce rate (1.25sec) when typing

**Comment by IanMatthewHuff** [comment]
Verified. Looks good to me now.
![SmoothInlay](https://user-images.githubusercontent.com/812783/151227233-e689e96e-e62a-4b3f-bb0d-55ee5bf169d6.gif)

**Comment by IanMatthewHuff** [comment]
Sorry I had the process off and had removed verification-needed added it back in along with verified.
