### ISSUE TITLE
Open File and Folder dialog not work

### ISSUE THREAD

**Issue by tipu07** [microsoft/vscode#133788]
![Capture](https://user-images.githubusercontent.com/30400782/134756678-0d641063-0302-47a1-aaac-8f6e29860aa2.JPG)
When i click File>Open File or Open Folder a dialog like path or url type show, its not showing a popup like choose file or folder. can you please fix this issue. thank you

**Comment by sbatten** [comment]
@tipu07 are you either:

1) Connected to a remote machine? or
2) `files.simpleDialog.enable` having this setting enabled?

**Comment by tipu07** [comment]
Ya thank you it works :)
