### ISSUE TITLE
Ctrl+Alt+ keybindings should not be used by default under Windows.

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#133724]
* run `scripts\code.bat`
![image](https://user-images.githubusercontent.com/5047891/134658975-f3b29e37-9b69-4699-bc59-5942d99ee047.png)

On many keyboard layouts, `Ctrl+Alt+[alphanum]` are used for typing. It has to do with how `AltGr+` works. We should therefore not ship by default any keybindings like that which might prohibit folks from typing on Windows.

Introduced via https://github.com/microsoft/vscode/commit/075664387464693a578454e80a3ad726d47d1dec

**Comment by sbatten** [comment]
removed the shortcut for now
