### ISSUE TITLE
Allow editor tab to be placed in panel

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#133783]
Now that I've been using the side panel, combining this with the live preview extension causes several "columns" to appaer. I would love to move an editor tab into a panel, much like terminal tabs can be moved to the editor.

## Current
![image](https://user-images.githubusercontent.com/35271042/134747932-0431ac6b-c34f-4477-8e93-7a9d33f3a356.png)

## Request
![image](https://user-images.githubusercontent.com/35271042/134747926-de745a6f-23a2-40a5-ba57-0112ad3d68be.png)

**Comment by bpasero** [comment]
I am not sure this is a good idea, what exactly can you not do today with grid layout that you need the panel for? Wouldn't that space in the panel be very limiting and frustrating to use?
