### ISSUE TITLE
terminal steals alt+z from editor area

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#133750]
in a terminal with a wrapped line, press alt+z or option+z to fit the width to content size. in the editor area, press that keybinding. it toggles the terminal's wrapping state

**Comment by rzhao271** [comment]
What is the expected result?
It seems that that keybinding toggles wrapping state, still, while changing the cursor to the select one.

**Comment by meganrogge** [comment]
before this fix, the repro was:
press alt+z in the terminal -> toggles wrapping of the terminal
press alt+z in the editor -> toggles wrapping of the terminal instead of the editor 🐛
