### ISSUE TITLE
Can no longer connect via SSH

### ISSUE THREAD

**Issue by SleeplessByte** [microsoft/vscode#133737]
Issue Type: <b>Bug</b>

Using the official SSH extensions, since the last update of insiders, anything I try to connect to shows:

> Bad owner or permissions on C:\\Users\\Derk-Jan/.ssh/config
> The process tried to write to a nonexistent pipe.
> 

The configuration file can be opened when the connection fails (Open SSH Configuration File) and there the path shows correctly as `C:\Users\Derk-Jan\.ssh\config`. It is also openable, without permission issues.

VS Code version: Code - Insiders 1.61.0-insider (8d30d4d922dda917d22f05a81f2ab4fad7349779, 2021-09-24T09:00:59.405Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'SSH' failed.
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (17.84GB free)|
|Process Argv|--crash-reporter-id b89f360b-5a82-470c-9730-8c9124c84a81|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by SleeplessByte** [comment]
I have some more information.

As a default, when this happens, I try to reproduce in non-insiders. I was able to reproduce the _exact_ same issue in non-insiders.

- I've reinstalled VSCode (non-insiders)
- I've reinstalled the Remote SSH extension
- I've reinstalled the Windows OpenSSH Client

I was able to reproduce the issue (connect to a host you've connected to before) and get the same issue.

I was also able to confirm that `ssh-add -l` shows it's running the agent with the correct identity.
I was also able to confirm that a blank call to `ssh -T ... -D ...` does actually work.

## Workaround

Go into `C:\Users\Derk-Jan\.ssh\` and rename `config` to `config.bak`. Now everything works as expected. As soon as I create a config again (through VS Code), everything breaks, even connecting to a host _NOT_ in the config.

**Comment by roblourens** [comment]
closing in favor of the remote-release issue
