### ISSUE TITLE
Smoketest: `app.reload` did timeout

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133732]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=136306&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6e7e74bd-a473-53b1-acea-ad5f8c1f1ec9

**Comment by bpasero** [comment]
```
1) VSCode Smoke Tests (Electron)
       Dataloss
         verifies that 'hot exit' works for dirty files:
     Error: Timeout: get window ids after 20 seconds.
```

That sounds as if the application itself could not start.

**Comment by joaomoreno** [comment]
Not sure what happened. Logs don't say much unfortunately. Relying on Playwright to iron these out: https://github.com/microsoft/vscode/issues/128479
