### ISSUE TITLE
Allow WAI ARIA attr and roles for other langues

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#133766]
Hi, Im using Latte template system (very similar to Twig).
Latte using own macros together with HTML.

I would like to use bult in ARIA attributes & roles autocompletion  in Latte, but it not works.

See short video https://bit.ly/3CKeHy8 (In HTML works fine, in Latte nope.

What can i do for it? Change some settings or .some hack or ... ?

Thx for help.

**Comment by aeschli** [comment]
Sorry, the HTML support only works with HTML syntax. We have no built-in support for the Latte language (or other templating languages). This support has to come from extensions
