### ISSUE TITLE
Inlay hints are not baseline algined

### ISSUE THREAD

**Issue by Cyberbeni** [microsoft/vscode#133738]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.10
- OS Version: macOS 11.5.2

Steps to Reproduce:

1. enable inlay hints
2. inlay hints are not aligned with the text around them

![Screen Shot 2021-09-24 at 16 05 45](https://user-images.githubusercontent.com/8356175/134688095-15397365-2917-474e-9ffe-fcf94540f0cb.png)

As far as I can tell, this is the only value that needs to be changed to `baseline`: https://github.com/microsoft/vscode/blob/ce7c00f4fb536e7dbcd74726dadf0e761b755e45/src/vs/editor/contrib/inlayHints/inlayHintsController.ts#L199

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by Cyberbeni** [comment]
It seems to be correctly aligned in the insider version.

<img width="231" alt="Screen Shot 2021-09-24 at 17 12 35" src="https://user-images.githubusercontent.com/8356175/134699352-4c4cfc1d-408a-46b2-9203-322eca8f954e.png">

**Comment by jrieken** [comment]
Ok, closing as fixed (we did a lot of inlay hint polish this milestone). Thanks for reporting back!
