### ISSUE TITLE
Notebook gets stuck after deleting and undoing a cell while running

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#133782]
Does this issue occur when all extensions are disabled?: No

- Version: 1.61.0-insider (user setup)
- Commit: 8d30d4d922dda917d22f05a81f2ab4fad7349779
- Date: 2021-09-24T09:00:59.405Z
- Electron: 13.4.0
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Run a cell
2. Delete it while its running
3. press ctrl+z
4. when the cell comes back, it thinks its still running and it can't be interrupted, even if the extension restarts or interrupts the kernel
![proof](https://user-images.githubusercontent.com/20347396/134747290-986f7a8d-04d4-49f2-aea5-d9f0be1e9e49.gif)

**Comment by roblourens** [comment]
Were you working on this last week @DavidKutu, is there anything we want to do for September?

**Comment by DavidKutu** [comment]
I just handled the debug session on the extension, but this still happens with the editor on VS Code's side.

**Comment by roblourens** [comment]
This is part of #125668 basically

**Comment by roblourens** [comment]
Is now fixed in #125668

**Comment by IanMatthewHuff** [comment]
Looks good to me. In the log I can see an error when the cell is deleted but it's an error for a cancelled future when waiting for replies which seems appropriate for this situation.

After cmd+z the cell is back in a ready to execute state and the cell can be run.
