### ISSUE TITLE
Test: Settings editor extension settings categorization

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#133775]
Refs: https://github.com/microsoft/vscode/issues/126089

- [x] anyOS @sandy081
- [x] anyOS @DavidKutu

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133775%0A%0A&assignees=rzhao271)

---

The Settings editor now displays categories for extension settings more clearly in both the table of contents as well as the settings list itself. Extensions can opt into this feature by using an array in the configures/contribution part of the `package.json` file.

It turns out the CSS Language Features extension already makes use of this feature because its schema already uses an array for the contributes configuration section (https://github.com/microsoft/vscode/blob/main/extensions/css-language-features/package.json#L36).

1. Open the (GUI) Settings editor.
2. Check the extensions table of contents and verify that the labels make sense. Currently, we use the extension display names, and only fall back to the plain extension name if no display name is provided.
3. Verify that the table of contents entries for the CSS Language Features make sense. They should be using the title entry in the schema linked above for the heading names in the Settings editor.
4. Verify that the settings list itself is displayed properly for the CSS Language Features settings, as well as for the settings before and after those settings.
5. Verify that searching for a setting within the CSS Language Features extension works.

**Comment by DavidKutu** [comment]
Looks like this fixes searching. If I search for `css lint compatible vendor prefixes` on this, I get the one setting that matches. While in stable we get the same setting for less and scss, along with `vendor prefix` for all 3 for some reason.

This looks better
