### ISSUE TITLE
Walkthroughs not allowing clicks in detail pane

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#133755]
Open any walkthrough that has click actions in the detail pane (theme switching, extensions, video, etc.) and nothing appears to work. There are some errors in dev tools when clicking the video link:

<img width="1024" alt="CleanShot 2021-09-24 at 09 40 58@2x" src="https://user-images.githubusercontent.com/35271042/134710906-8983a949-8c55-434e-8cfa-3e9e91ae19ea.png">

**Comment by JacksonKearl** [comment]
A number of new issues have come up with that webview this iteration despite no changes on my end:
- https://github.com/microsoft/vscode/issues/133309
- https://github.com/microsoft/vscode/issues/131809

cc @mjbvz was there a change to webviews that would cause these?

**Comment by mjbvz** [comment]
@JacksonKearl Are you using VS Code's markdown rendering? We now pass the output through dompurify

**Comment by JacksonKearl** [comment]
\closedWith 8e35bdb33bfff18881cd6dc68945d0a59d979361
