### ISSUE TITLE
Command to make activityBar, menuBar, and statusbar visible (or invisible), or determine their current state, not just toggle

### ISSUE THREAD

**Issue by dmalan** [microsoft/vscode#133787]
For educational use cases, we're hoping to configure students' workspaces (via Remote settings in Codespaces) to have a standard UI and also provide students with a command and button (via our own extension) via which they can restore their workspace's UI to that default state if they accidentally disable various UI elements while experimenting. At the moment, though, it seems that the visibility of the activityBar, menuBar, and statusbar can only be toggled, not explicitly set to visible or invisible. And there doesn't seem to be a way to inspect their current state, so as to know programmatically (when resetting the UI to a default state) whether or not to toggle them.

Might it be possible to supplement the commands below with commands like `workbench.action.enable{ActivityBar,Statusbar,MenuBar}` and `workbench.action.disable{ActivityBar,Statusbar,MenuBar}`?

* `workbench.action.toggleActivityBarVisibility`
* `workbench.action.toggleStatusbarVisibility`
* `workbench.action.toggleMenuBar`

Thank you!

CC @rongxin-liu

**Comment by yume-chan** [comment]
Those built-in commands just flip the corresponding settings:

* `workbench.activityBar.visible`
* `workbench.statusBar.visible`
* `window.menuBarVisibility`

You can read/write these setting keys in your extension directly.

**Comment by sbatten** [comment]
@yume-chan is correct that this can already be done in an extension via the settings

**Comment by rongxin-liu** [comment]
Thank you! @yume-chan and @sbatten.

Is "window.menuBarVisbility" available currently? I'm currently getting this prompt when trying to use this setting:
<img width="399" alt="Screen Shot 2021-09-27 at 14 55 31" src="https://user-images.githubusercontent.com/10591665/134968381-fdbc022b-2557-4368-9b9b-245786fec8b6.png">

**Comment by sbatten** [comment]
@rongxin-liu are you on macos?

**Comment by sbatten** [comment]
@rongxin-liu it is only available as a user setting, not a workspace setting

**Comment by dmalan** [comment]
Ah, thanks very much, @yume-chan, @sbatten.  Just proposed `window.menuBarVisbility` as a potential Remote setting, too, in fact, https://github.com/microsoft/vscode/issues/133786. Thank you!

**Comment by sana-ajani** [comment]
Would it be possible to programmatically toggle specific views or items inside the activity bar, status bar, terminal? For instance, in the education use case, @dmalan has mentioned that they'd like to only show the Explorer view in the activity bar, or only show the Terminal view and hide the Problems, Output, etc. 

So instead of just showing and hiding the whole bar, could we provide more control from the settings? Something like: 
```
  "workbench.acivityBar.visible": {
      "fileExplorerView": true,
      "searchView": false,
      "extensionsView": false,
      "debugView": false,
      "sourceControlView": false,
  }
```

**Comment by isidorn** [comment]
Closing this as there are already some solutions proposed in this issue, and we plan to introduce Profiles soon that will cover the remaining asks. Here's the issue tracking profiles https://github.com/microsoft/vscode/issues/116740
