### ISSUE TITLE
Can not run a task when the task command contains & option in Linux

### ISSUE THREAD

**Issue by WildScientist** [microsoft/vscode#133709]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.1
- OS Version:Linux

Steps to Reproduce:

1.create a task in tasks.json
2.put a command that contains & in this task, nohup ... &,for example.
3.the task wouldn't run correctly!

**Comment by alexr00** [comment]
Can you please provide a tasks.json file with a task that reproduces this issue?

**Comment by WildScientist** [comment]
> 
> 
> Can you please provide a tasks.json file with a task that reproduces this issue?

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "copy background",
            "type": "shell",
            "command": "cp -R a.txt b.txt &",
            "group": "test"
        }
    ]
}

**Comment by alexr00** [comment]
Thanks, I can see the behavior you describe!

**Comment by rubi-rastko** [comment]
I have success with `nohup`, but then the task ignores `"cwd"`.
