### ISSUE TITLE
TS formatter cannot move `else` to nextline if placing open brace on NewLine

### ISSUE THREAD

**Issue by OzelotVanilla** [microsoft/vscode#133789]
There isn't such option like `"typescript.format.placeOpenBraceOnNewLineForControlBlocks": true` to put the trailing `else` (or something like the trailing `else`) to next line. Code will be like this:

![image](https://user-images.githubusercontent.com/59910575/134757396-705d211b-a70a-4f48-8f4f-e14664dc345e.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
