### ISSUE TITLE
Test platform specific extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#133868]
Ref #23251

- [x] Mac @kimadeline
- [x] Mac @kieferrm  (arm64)
- [x] windows @karrtikr
- [x] windows @sbatten (arm64)
- [x] linux @karthiknadig
- [x] linux @bpasero (arm64)
- [x] linux @chrmarti (Alpine)

Complexity: 5

Authors: @sandy081, @joaomoreno, @isidorn 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133868%0A%0A&assignees=sandy081,joaomoreno,isidorn)

---

## Prerequisite

Install latest `vsce` and make sure you can publish extensions to Marketplace - https://code.visualstudio.com/api/working-with-extensions/publishing-extension

## Testing

We now support platform specific extensions, that is, extension authors can now package an extension per platform with platform depending binaries and publish to Marketplace. 

Please refer to [Platform Specific Extensions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions) guide for publishing a platform specific extension. There is also an [example extension](https://github.com/microsoft/vscode-platform-specific-sample) for reference. Currently following target platforms are supported:

- `darwin-x64`
- `darwin-arm64`
- `win32-x64`
- `win32-ia32`
- `win32-arm64`
- `linux-x64`
- `linux-arm64`
- `linux-armhf`
- `alpine-x64`
- `alpine-arm64`

We would like you to test this feature end to end: 

- Publish a platform specific extension using `vsce` for your platform
- Install your extension from VS Code.
- Publish a new version of you extension. Make sure your extension gets updated in VS Code as expected.
- Publish a platform specific extension not targeted to your platform and make sure this extension is not installable from VS Code on your platform (**Please use fresh extension to test this**)
- Review the platform specific extensions guide

**Comment by isidorn** [comment]
We have assigned some of you from last milestone because you already know the context and thus for you it takes the least amount of time to test this item. If somebody does not feel like testing platform specific extensions again feel free to unassign yourself. Thanks!
