### ISSUE TITLE
Make the command 'extension.open' asynchronized

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#133808]
Currently we can use the command `extension.open` to view the extension page inside VS Code.

This command will [do a query first](https://github.com/microsoft/vscode/blob/d4c222488de817d491f7c5686cf1161e9cceb7d4/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L246) then open the extension page. When the user's network environment is not stable, this will make the UI delayed to respond the users action.

Can we for example, open the extension view and meanwhile do the query? At least making some simple UI response to let the user know that something is working right now.

**Comment by sandy081** [comment]
I do not think the command is meant to do that and might not be wanted for other callers.
