### ISSUE TITLE
Test: Alpine ARM64 container

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#133893]
Refs: https://github.com/microsoft/vscode-remote-release/issues/4462

- [x] macOS: @deepak1556 (test arm)
- [x] macOS: @sandy081 (test arm)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133893%0A%0A&assignees=TylerLeonhardt)

---

This iteration we released a vscode server version for Apline ARM64! This TPI really just asks that you run through a manual smoke test of this server build to make sure it's working as expected.

It looks like Windows isn't quite there yet to run ARM containers so I'm adding two macOS ARM folks. This should be enough since we also had confirmation it was working as expected by an external user.

Steps:
* clone https://github.com/TylerLeonhardt/vscode-test-alpine-arm
* Open in Remote Containers
* run `uname -m` it should be something "ARM-y" like `aarch64`
* Run through a manual smoke test

**Comment by deepak1556** [comment]
Provided repo `mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}` only pulls x64 image.

Tested on:

```
Version: 1.61.0-insider
Commit: 5991e3c4b97eca5568069bf3e0910ab693ad3549
Date: 2021-09-27T05:24:51.119Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
```

```sh
% docker run -it mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.14
Unable to find image 'mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.14' locally
0-alpine-3.14: Pulling from vscode/devcontainers/base
29291e31a76a: Pull complete 
86d8552a4a8e: Pull complete 
ae00e684a894: Pull complete 
Digest: sha256:1fbb76bb365f04596d8ab70b39e479856321889c1949cdc7f25e3c652088665e
Status: Downloaded newer image for mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.14
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/ # uname -a
Linux f5a6bda16d76 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 x86_64 GNU/Linux
```

```bash
$ file ~/.vscode-server-insiders/bin/5991e3c4b97eca5568069bf3e0910ab693ad3549-insider/node
/home/vscode/.vscode-server-insiders/bin/5991e3c4b97eca5568069bf3e0910ab693ad3549-insider/node: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
```

**Comment by jrieken** [comment]
> so I'm adding two macOS ARM folks

I am on Intel macOS, the ARM is my private machine which I don't use for work (except for sanity testing). I'll find someone to swap with

**Comment by sandy081** [comment]
Yeah provided repo pulls `x64` image and observed the same as @deepak1556. 
I changed the `DockerFile` to use following image

```
FROM alpine:3.14
```

It pulled arm64 image and vscode alpine arm64 server

```
92814bd6d9b5:/workspaces/vscode-test-alpine-arm# uname -a
Linux 92814bd6d9b5 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 Linux
92814bd6d9b5:/workspaces/vscode-test-alpine-arm# file ~/.vscode-server-insiders/bin/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/
node
/root/.vscode-server-insiders/bin/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, with debug_info, not stripped
92814bd6d9b5:/workspaces/vscode-test-alpine-arm# 
```

Manually smoke tested the server and it seems File quick open and Search are not working - https://github.com/microsoft/vscode/issues/133993

**Comment by TylerLeonhardt** [comment]
Ah my bad, all. I don't have an ARM machine so was guessing there. I guess I assumed that since `mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT}` uses `FROM alpine:3.14` that it would give ARM64.

**Comment by roblourens** [comment]
I made that change but it failed to start

```
[6157 ms] Shell server terminated (code: 126, signal: null)
unable to find user vscode: no matching entries in passwd file
```

so I guess there is something else missing from the microsoft image

**Comment by deepak1556** [comment]
@roblourens there is no `vscode` user in the base alpine image, you need to comment out https://github.com/TylerLeonhardt/vscode-test-alpine-arm/blob/6a8b6675f105c703245e8f03d6203799a1aae9dc/.devcontainer/devcontainer.json#L29

**Comment by TylerLeonhardt** [comment]
@roblourens I updated my example repo with the new image and commented out `vscode` user.
