### ISSUE TITLE
VSCode Web: the editor.action.clipboardPasteAction command takes some time for the pasted text to be really inserted to the editor text

### ISSUE THREAD

**Issue by whitphx** [microsoft/vscode#133816]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.61.0-insider (automatically downloaded by vscode-test-web)
- OS Version: macOS BigSur 11.5.2
  - The same problem occurs on Ubuntu, a CI env for another repo, FYI

Steps to Reproduce:

1. Clone [this repo](https://github.com/whitphx/vscode-web-extension-clipboard-bug-example)
   ```sh
   $ git clone https://github.com/whitphx/vscode-web-extension-clipboard-bug-example.git
   $ cd vscode-web-extension-clipboard-bug-example
   $ yarn
   ```
2. Run tests
   ```sh
   $ yarn test
   ```

Then, the test fails like
```sh
  Web Extension Test Suite
    1) Clipboard test
  0 passing (183ms)
  1 failing
  1) Web Extension Test Suite
       Clipboard test:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

'' !== 'foo'

      + expected - actual

      +foo

        at eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:30915:16)
        at Generator.next (<anonymous>)
        at fulfilled (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:30894:58)

Error: 1 tests failed.
```

After that, if you comment-in this line
https://github.com/whitphx/vscode-web-extension-clipboard-bug-example/blob/b5f48de52beaf9cc78698ecf565737bfb46e522f/src/web/test/suite/extension.test.ts#L18
,
the test will be successful.

This means that it takes some time for the text pasted by the `editor.action.clipboardPasteAction` command to be really inserted into the editor text, like 100ms in this example.

This problem does not occur with the desktop version.

**Comment by alexdima** [comment]
@aeschli I think this is exactly what you mentioned in today's standup.

**Comment by aeschli** [comment]
@alexdima Not sure. This is already the next step. On request of @whitphx I added the `--permission` options which the sample uses: https://github.com/whitphx/vscode-web-extension-clipboard-bug-example/blob/b5f48de52beaf9cc78698ecf565737bfb46e522f/package.json#L25

That's why the tests no longer are blocked.

But it seems our paste command returns before the text document has been updated.
