### ISSUE TITLE
How to set node env variable NODE_EXTRA_CA_CERTS in my extension ?

### ISSUE THREAD

**Issue by aniketnitrr** [microsoft/vscode#133863]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56.2
- OS Version: macOS 10.15.7

Hello,
I am developing an extension where i take path to certificate.pem file from user. I have to assign this path to node env variable NODE_EXTRA_CA_CERTS. Doing process.env.NODE_EXTRA_CA_CERTS = '' doesn't work. Please suggest me an alternative way to set the node env variables in my extension.

**Comment by weinand** [comment]
Setting an env var via `process.env.NAME` should work. If it doesn't this is not a VS Code problem.

**Comment by aniketnitrr** [comment]
Hi Andre,
Generally, I set NODE_EXTRA_CA_CERT before running my script i.e i do - 
-> export NODE_EXTRA_CA_CERT='path-to-cert'
-> node myFile.js

The same code that myFile.js has, i have placed in extension.js file in my vs code extension. But, i am unable to set NODE_EXTRA_CA_CERT. I tried setting it in launch.json but it didn't work. I wonder if there is any was to set this variable during runtime through extension then maybe reload the vscode window to make it effective ?

**Comment by weinand** [comment]
@aniketnitrr how did you try to set the env var in launch.json?

**Comment by aniketnitrr** [comment]
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"osx": {
				"env": {
					"NODE_EXTRA_CA_CERTS":"/Users/abewal/work/aniket.pem"
				}
			},
			"preLaunchTask": "${defaultBuildTask}"
		}
	]
}

**Comment by aniketnitrr** [comment]
I used env and osx: { env: ""} of launch.json

**Comment by weinand** [comment]
You are setting the env only when running extension tests. Is that your intention?

Please try to set the env in the "Run Extension" launch config and verify inside the extension, that the env var has the correct value..

**Comment by aniketnitrr** [comment]
Sorry i send the wrong example of launch.json. I did added it to 'Run Extension' config and it actually sets the variable i.e if i do console.log(process.env.NODE_EXTRA_CA_CERT) i get my value. But, it is not picked by my database when i try to make the connection. 
The [node.js](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) documentation says this environment variable is ignored when node runs as setuid root or has Linux file capabilities set. The NODE_EXTRA_CA_CERTS environment variable is only read when the Node.js process is first launched. Changing the value at runtime using process.env.NODE_EXTRA_CA_CERTS has no effect on the current process.

I wonder i am setting this variable after the process is started thus its has no effect. Thus, i need help to figure out when the extension process starts ? and if we do a reload does it stops and restart the vs code process ?

**Comment by weinand** [comment]
Is your database running inside your extension as part of the node.js extension process or is your database a separate process launched from your extension? Only in those cases will your database be able to pickup the env var.

**Comment by aniketnitrr** [comment]
its running inside as part of node.js extension process

**Comment by weinand** [comment]
But if `console.log(process.env.NODE_EXTRA_CA_CERT)` shows the correct value and the DB is started after your `console.log` then the DB should be able to see the correct value.

**Comment by aniketnitrr** [comment]
Yeah, but it isn't taking it up. I think the value is assigned after the vscode process started, thats why its ignored.

**Comment by weinand** [comment]
@aniketnitrr what do you mean by "the vscode process"?
A single VS Code window is backed by at least 10 processes:

<img width="880" alt="2021-10-06_11-22-31" src="https://user-images.githubusercontent.com/1898161/136176192-c53a2b47-ac61-4775-8da1-1d7b184d098e.png">

(you can easily see them via "Help" > "Open Process Explorer")
