### ISSUE TITLE
Terminal dangling characters after deleting prompt input

### ISSUE THREAD

**Issue by kuhar** [microsoft/vscode#133885]
Issue Type: <b>Bug</b>

Often when I delete characters in the terminal prompt, I'm left with leftover dangling characters past or before the cursor position. This makes it difficult to tell what the state of the prompt is, as there may be some leftover characters that didn't render, or leftover characters that are being rendered but are not really in the prompt.

I'm using zsh with autosuggestions enabled and connecting over ssh.

I attach a video that should make it clearer.

https://user-images.githubusercontent.com/4612584/134958003-aa2b7948-4422-4455-9f0b-ef8be019bf2d.mp4

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.10.46-4<snip>-amd64
Restricted Mode: No
Remote OS version: Linux x64 5.10.40-1<snip>-amd64
Remote OS version: Linux x64 5.10.40-1<snip>-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (1.10GB free)|
|Process Argv|--unity-launch --crash-reporter-id 90c19cb4-a172-4c82-8fea-75f98d94555e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: <snip>|
|OS|Linux x64 5.10.40-<snip>-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (72 x 1200)|
|Memory (System)|187.52GB (39.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: <snip>|
|OS|Linux x64 5.10.40-<snip>-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (72 x 1200)|
|Memory (System)|187.52GB (39.96GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.30.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vim|vsc|1.21.7
vscode-bazel|Baz|0.4.1
gitlens|eam|11.6.0
vscode-pull-request-github|Git|0.30.0
vscode-clangd|llv|0.1.13
vscode-docker|ms-|1.17.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
trailing-spaces|sha|0.3.1
code-spell-checker|str|2.0.7
cmake|twx|0.0.17
docker|vsc|1.0.0
yaml|vsc|1.0.0
debug|web|0.25.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792

```

</details>

**Comment by kuhar** [comment]
I tried changing the rendering type to no GPU acceleration or to canvas, with a vscode restart after each change, but this did not solve the issue.

**Comment by IllusionMH** [comment]
Is it reproducible with latest stable version which is 1.60.2 (and had few terminal related fixes) or Insiders builds? https://code.visualstudio.com/insiders/

**Comment by meganrogge** [comment]
this looks like a local echo issue to me. can you try setting `terminal.integrated.localEchoLatencyThreshold` to -1?

**Comment by kuhar** [comment]
> this looks like a local echo issue to me. can you try setting `terminal.integrated.localEchoLatencyThreshold` to -1?

After switching to -1, I could not reproduce it anymore despite a couple of minutes of aggressive `backspace`ing. Thanks a lot, @meganrogge!
