### ISSUE TITLE
Test task presentation close API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#133862]
Refs: https://github.com/microsoft/vscode/issues/131125

- [x] anyOS @daviddossett
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133862%0A%0A&assignees=alexr00)

---

The existing task presentation option `close` is now available in the tasks API. 

https://github.com/microsoft/vscode/blob/55c726b53e6ebcc04553fe095fcd0ac01c095e02/src/vs/vscode.proposed.d.ts#L1077-L1080

To try out the API:
1. Start with an existing task provider (I recommend the built in npm task provider for this).
2. Add `presentationOptions` to your task. For example, in the npm task provider you can add this:
```ts
	task.presentationOptions = {
		close: true
	};
```
here:

https://github.com/microsoft/vscode/blob/f38f90dfe16405b35249b0580b6f0e12e16ee168/extensions/npm/src/tasks.ts#L350-L351

3. Run your extension and run one of your tasks. Verify that the presentation option is respected.
4. Verify that the documentation for `close` makes sense.

**Comment by hediet** [comment]
Documentation is clear and presentationOptions are respected!
