### ISSUE TITLE
can't open web browser after npm install

### ISSUE THREAD

**Issue by Valerie-24** [microsoft/vscode#133865]
Issue Type: <b>Performance Issue</b>

HI, after I intalled npm with chai & mocha, I was attempting to test in VS Code, performed a test.html and after saving all index.js the 'open in web browser' is not available on the test.html tab.  The menu is not event he same & it is the same for my older index.html tab that worked before the install.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx   (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.91GB (2.47GB free)|
|Process Argv|--crash-reporter-id 6ffe8440-8151-421b-934b-f702cd2a2f15|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	 10580	code main
    0	    83	  1916	   shared-process
    0	    65	  3124	     ptyHost
    0	    24	  1920	   crashpad-handler
    0	    36	  3848	   utility
    0	   124	  4796	   gpu-process
    0	   104	  4980	   window (Welcome - Visual Studio Code)
    0	   101	  7992	     extensionHost
    0	   157	 10568	   window (test.html - Hello World! - Visual Studio Code)
    0	   106	  8608	     extensionHost
    0	   111	  1372	       electron_node tsserver.js 
    2	    88	 12116	         electron_node typingsInstaller.js typesMap.js 
    0	   111	 11412	       "C:\Users\valer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\valer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=8608
    0	   108	 12060	       electron_node tsserver.js 
    0	    12	  9040	     watcherService 
    0	    10	 10576	       console-window-host (Windows internal process)
    0	    71	 11652	     searchService
    0	    74	 12284	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.html - Hello World! - Visual Studio Code)
|    Folder (Hello World!): 11 files
|      File types: js(8) html(2) json(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791

```

</details>

**Comment by aeschli** [comment]
VS Code does not have `open in web browser` command. This must come from an extension. You need to find and install that extension.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server is such an extension (but there are others).

**Comment by Valerie-24** [comment]
Thank you, that was lost somehow during the npm install.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
