### ISSUE TITLE
Expose TestItemCollection @@iterator publicly

### ISSUE THREAD

**Issue by nerdondon** [microsoft/vscode#133847]
The [TestItemCollectionImpl](https://github.com/microsoft/vscode/blob/0040f1577d0918b001ccbf6562d864abb4d6976b/src/vs/workbench/api/common/extHostTestingPrivateApi.ts#L257-L259) has an `@@iterator`. It would be nice to be able to use this and be able to break out of a loop early instead of only being able to use `.forEach`.

**Comment by connor4312** [comment]
While I definitely agree with you that this would be nice to have, this is an intentional decision. We don't expose ES6 constructs in our API yet.
