### ISSUE TITLE
tip is false

### ISSUE THREAD

**Issue by zld406504302** [Microsoft/vscode#13381]
- VSCode Version:1.5.3 
- OS Version: 10.11.5 

The content of the tip is wrong
![tip](https://cloud.githubusercontent.com/assets/3940707/19214100/dabb6a12-8dae-11e6-84b9-24ed1fa86fc1.png)

I want to look "SayHello"  method ,not  others.
give me a help

**Comment by gregvanl** [comment]
VS Code by default includes word based completions (suggestions). So in the example above "console", "log", etc are displayed as text completions (displayed with a text icon). 
If you don't want word based completions displayed, you can disable it with the [setting](https://code.visualstudio.com/docs/customization/userandworkspace) "editor.wordBasedSuggestions": false

**Comment by zld406504302** [comment]
Thanks lot

**Comment by zld406504302** [comment]
![image](https://cloud.githubusercontent.com/assets/3940707/19961178/1959441e-a1ec-11e6-99f8-658d016f79e0.png)

![image](https://cloud.githubusercontent.com/assets/3940707/19961188/29237748-a1ec-11e6-9c92-2091ab22e64d.png)


why have not  hint "toString" method ,hope give me a help
