### ISSUE TITLE
Setting Sync cannot synchronize Vetur user scaffold snippet

### ISSUE THREAD

**Issue by richex-cn** [microsoft/vscode#133809]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Install [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) extension.
2. [Turning on Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync#_turning-on-settings-sync) and Sign in.
3. Press ctrl+shift+p run command **Vetur: Open user scaffold snippet folder**.
4. Create a snippet file in the open workspace, for example `style/less-module.vue`:
    ```
    <style lang="less" module>
    .wrap {
      ${0}
    }
    </style>
    ```
5. Run command **Settings Sync: Sync Now** and wait for synchronization to complete.

After following the above steps, the segment about Vetur I configured was not synchronized. 

I did not find any related issues in Google and Github Issues, so is this a bug? Or should it be regarded as a new feature?

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #113774

**Comment by richex-cn** [comment]
@gjsjohnmurray Thank you for your help. I will close this issue and track #113774
