### ISSUE TITLE
Please provide an action to toggle indent guides

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#13385]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Perhaps `editor.action.toggleRenderIndentGuides`.

**Comment by rebornix** [comment]
It's a good extension candidate and you can follow https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955 to get your preferred extension to archive that.

**Comment by mjbvz** [comment]
Closing this can be provided by an extension
