### ISSUE TITLE
Emmet 

### ISSUE THREAD

**Issue by govindkm07** [microsoft/vscode#133825]
Issue Type: <b>Feature Request</b>

Hello Sir,
Whenever I type "class" or "id" or "type" "style". Vs code doesnt show any kind of options as emmets. I am not able to doing my work. Please help me out. This thing wasted my 3 days.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
What language mode is the file set to? Look at the right-hand end of the status bar.

**Comment by rzhao271** [comment]
\gifPlease
