### ISSUE TITLE
Improve file not found message - "The editor could not be opened due to an unavailable resource"

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#133829]
Issue Type: <b>Bug</b>

1. Open a file
2. Outside of vscode, delete the file
3. Restart vscode (because of an upgrade)

Actual results:

https://github.com/microsoft/vscode/blob/66a1a51a07a299dbe00583030aa74b7718fb0683/src/vs/workbench/browser/parts/editor/editorPlaceholder.ts#L225
(With a `Try Again` link -- which doesn't work.)

The error makes it sound like there wasn't enough memory to open the file (and given my computer, that isn't an unreasonable possibility).

A "File not found" message & the path of the file would be more helpful than the current text.

Note that activating the tab also triggers a box `Error: Unable to resolve non-existing file` (n.b. it should say `nonexistent`) in the bottom right of vscode that gives the path w/ a `create file` button.

I'd personally, rather that text and that button be merged into the editor pane, instead of the current flying window.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
quitcontrol-vscode|art|4.0.0
vscode-bazel|Baz|0.4.1
LinkCheckMD|bla|0.3.1
open-in-macdown|Cod|1.0.0
vscode-zonefile|Com|0.0.4
vscode-markdownlint|Dav|0.44.1
vscode-eslint|dba|2.1.25
dhall-lang|dha|0.0.4
vscode-dhall-lsp-server|dha|0.0.4
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.15
docs-build|doc|0.3.6
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.99
docs-metadata|doc|1.0.7
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.11
docs-visual-areas|doc|0.2.1
docs-yaml|doc|0.2.7
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.0.0
kotlin|fwc|0.2.23
go|gol|0.28.1
terraform|has|2.15.0
haskell|has|1.7.1
hive-sql|jos|0.0.4
language-haskell|jus|3.4.0
haml|kar|1.3.1
restructuredtext|lex|166.0.0
vscode-sbt-scala|lig|0.2.4
autoconf|mae|0.1.0
hg|mrc|1.7.1
language-gettext|mro|0.2.0
vscode-docker|ms-|1.17.0
csharp|ms-|1.23.15
vscode-kubernetes-tools|ms-|1.3.3
vscode-postgresql|ms-|0.3.0
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
cmake-tools|ms-|1.8.1
cpptools|ms-|1.6.0
powershell|ms-|2021.9.0
vscode-typescript-tslint-plugin|ms-|1.3.3
gradle-language|nac|0.2.3
vscode-dhall-lsp-server|pan|0.0.4
fabric8-analytics|red|0.3.3
java|red|0.82.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
vscode-gradle-extension-pack|ric|0.0.4
scala|sca|0.5.4
metals|sca|1.10.11
preview-vscode|sea|2.2.5
code-spell-checker|str|2.0.7
sass-indented|syl|1.8.18
html-preview-vscode|tht|0.2.5
simple-rst|tro|1.5.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.14
vscode-gradle|vsc|3.7.1
vscode-java-debug|vsc|0.36.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.5
vscode-maven|vsc|0.34.0
markdown-all-in-one|yzh|3.4.0
grammarly|znc|0.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by bpasero** [comment]
But the file name and path are available as before from the editor tab, no?

![image](https://user-images.githubusercontent.com/900690/134938425-8fd7b964-e6b0-4075-be28-32307f6ab548.png)

We can tweak the wording a bit.

**Comment by jsoref** [comment]
Yes, hovering over the tab shows the path, and the open editors pane shows the file +`(deleted)` and hovering there also shows the path +`(deleted)`.

Notably: it's odd that the editors pane shows `(deleted)` and the editor tab does not.

![image](https://user-images.githubusercontent.com/2119212/134941368-4fb0dc2e-203e-4bed-a9a3-6d88d238a220.png)
![image](https://user-images.githubusercontent.com/2119212/134941404-e4f7f109-c4e0-4548-9671-8f323a0166c1.png)

**Comment by bpasero** [comment]
The indication changes this month, see https://github.com/microsoft/vscode/issues/133743. You can see that in action when using our insiders build: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
I changed the wording as you suggested, also to rename `non-existing` to `nonexistent`:

![image](https://user-images.githubusercontent.com/900690/135036227-396cf38a-d4a2-4b1a-b639-46f9d4f13a7b.png)

Adding the file path into the editor itself is not really in reach and I think the tab conveys this information sufficient enough.
