### ISSUE TITLE
The window has crashed (reason: 'crashed', code: '-1073741795')

### ISSUE THREAD

**Issue by weloytty** [microsoft/vscode#133864]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2.0
- OS Version: Win10 x64 18368.1734

Steps to Reproduce:

1. Start Code, either code --crash-reporter-directory c:\hold\codedump\ or code --disable-extensions
2. Feel sad because it crashed.

![image](https://user-images.githubusercontent.com/3042440/134921707-2dd10953-dffe-4041-8d12-c1a522f47858.png)

[codeerr.zip](https://github.com/microsoft/vscode/files/7236706/codeerr.zip)

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/133864#issuecomment-929035988
