### ISSUE TITLE
Remote SSH extension - Recommend frequently used paths in "Open Folder"

### ISSUE THREAD

**Issue by OmarOdaini** [microsoft/vscode#133894]
I use remote ssh frequently, but I have to type the path to my repo every time. It'll be nice to have "frequently used" paths suggested.

![image](https://user-images.githubusercontent.com/26101260/134975503-8c8bbeb6-d35a-4c8c-91cd-e98bbfe0062f.png)

**Comment by roblourens** [comment]
There is a separate command for recently opened folders, "Open Recent". You should see it under the File menu. Also, the SSH explorer should show the recent folders by host.
