### ISSUE TITLE
Search'n'replace in CSV miss consecutive occurences

### ISSUE THREAD

**Issue by SomwareHR** [microsoft/vscode#133836]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.2 (system setup)
- OS Version: Windows 10 Pro 21H1 19043

Version: 1.60.2 (system setup)
Date: 2021-09-22T12:00:31.514Z (4 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create .CSV file:

![image](https://user-images.githubusercontent.com/45540611/134816024-171afe51-c55e-4559-96fa-a22bfb3a123c.png)

|CSV file|
|--------|
|1;qwe;wer;2;3;ert|
|2;asd;sdf;4;5;dfg|
|3;asd;sdf;4;4;dfg|
|4;yxc;xcv;5;6;cvb|

2. Have same numbers consecutive

See line 3: "`;4;4;`"

3. Open Search & replace 

4. Type "`;4;`" as an item to be replaced with ";0000;"

5. VSCode will miss second ";4;"

Selection before action "Replace all":
![image](https://user-images.githubusercontent.com/45540611/134816116-29a994d3-4fea-4974-a226-c2cb91753546.png)

6. After "Replace all" action second ";4;" is still there:
![image](https://user-images.githubusercontent.com/45540611/134816175-a2197d94-7827-4ddb-a138-c68e26e6e4ee.png)

**Comment by roblourens** [comment]
I think this is by design - there is only one match there, find doesn't show overlapping matches. You can use a regex with lookahead if you want that behavior.
