### ISSUE TITLE
`"workbench.experimental.sidePanel.enabled": true` is disabled.

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/vscode#133831]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: Windows 7

Steps to Reproduce:

1. Type `"workbench.experimental.sidePanel.enabled": true`
2. You see the following error:

![image](https://user-images.githubusercontent.com/89698728/134812501-2f60a00f-e74d-420a-876c-5d6ba5b94b91.png)

the following command is disabled! :cry:

**Comment by gjsjohnmurray** [comment]
Are you using [Insiders](https://code.visualstudio.com/insiders)? AFAIK it's only available there at the moment.

**Comment by sbatten** [comment]
Yes, this feature is not yet ready for a stable release and the setting is not exposed in stable currently.

**Comment by TarunavBA** [comment]
> Yes, this feature is not yet ready for a stable release and the setting is not exposed in stable currently.

Friend @sbatten when will this feature be available in the `stable` release?

**Comment by TarunavBA** [comment]
> Are you using [Insiders](https://code.visualstudio.com/insiders)? AFAIK it's only available there at the moment.

No @gjsjohnmurray I am not using the `insiders` version.

**Comment by sbatten** [comment]
@TarunavBA as it is in early stages, I cannot say for certain. However, I can say it will NOT be available in the next version stable. If you would like to test this feature and provide feedback, you are welcome to do so in the insiders version. The reason it is behind an experimental flag is that it is early and some things are known to be broken.
