### ISSUE TITLE
Cannot change cell type to markdown

### ISSUE THREAD

**Issue by aparente-nurix** [microsoft/vscode#133875]
Issue Type: <b>Bug</b>

Having transient issues with cell rendering, predominantly between python and markdown. 

All cells are python by default, and when I try to change a cell to markdown it lets me select "Markdown" but nothing happens and the cell continues to render as python. 

Sometimes converting to raw will work, but then if I try to change it back to python it wont (but only sometimes!). I also can't change from raw to markdown. 

If I open the same notebook in VScode (not Insiders), I can change the cell rendering as normal. 

Extension version: 2021.9.1001240917
VS Code version: Code - Insiders 1.61.0-insider (f66a3e06bcb9f000e5dc0ad0040ff9b32fc75c78, 2021-09-14T05:15:56.612Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.24.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.94GB free)|
|Process Argv|--crash-reporter-id 3ab5d30a-e57d-4c95-ad43-4ab531c2c975|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aparente-t7820|
|OS|Linux x64 3.10.0-1160.24.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz (48 x 3599)|
|Memory (System)|125.35GB (75.39GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by DonJayamanne** [comment]
@rebornix @roblourens I can confirm this is a regression in VS Code insiders (works as expected in stable)
