### ISSUE TITLE
Can't get tip from require module

### ISSUE THREAD

**Issue by zld406504302** [Microsoft/vscode#13383]
- VSCode Version:1.5.3
- OS Version:10.11.5

I export user and require user in  Student.js ,but i can't get  tip about user method "SayHello".

![tip1](https://cloud.githubusercontent.com/assets/3940707/19214379/7a4a606a-8db4-11e6-8002-e75830b3a7d2.png)
![tip2](https://cloud.githubusercontent.com/assets/3940707/19214380/7f54fb24-8db4-11e6-9d48-753daebeaa2c.png)

Give me some advice,Thanks .

**Comment by waderyan** [comment]
@zld406504302 thank you for opening this issue. Can you share what your workspace (possibly via GitHub)? This is commonly a jsconfig.json issue. See docs here for help setting this up. 

Also, this may not matter, but change `require("user")` to `require("./user")` to indicate that the file is local.

**Comment by mjbvz** [comment]
@waderyan I believe you are correct. We get intellisense just fine when the proper `require('./user')` is used:

![nov-18-2016 15-38-10](https://cloud.githubusercontent.com/assets/12821956/20450389/054192e6-ada5-11e6-8332-ba9236ee1b13.gif)

@zld406504302 Please try updating the code and let me know if you notice any further issues. 

Thanks.
