### ISSUE TITLE
VSCode icon will disappear from dock once restart the mac

### ISSUE THREAD

**Issue by bjmin** [Microsoft/vscode#13389]
- VSCode Version: Insider 1.6.0 (2016-10-07T18:57:32.707Z) & Stable 1.5.3
- OS Version: 10.12

Steps to Reproduce:

1. Drag any version of vscode into docker.
2. Restart.
3. You will see the app icon becomes a question mark, and also you cannot open the app through clicking those icons. Also the insiders version icon remains, but it is not functional!!

<img width="815" alt="screen shot 2016-10-09 at 11 45 20" src="https://cloud.githubusercontent.com/assets/5073227/19217769/dfb041b6-8e15-11e6-84dd-66bd4ad5ac80.png">

<img width="892" alt="screen shot 2016-10-09 at 11 47 41" src="https://cloud.githubusercontent.com/assets/5073227/19217779/39c24316-8e16-11e6-9240-420f1ae9aea2.png">

**Comment by joaomoreno** [comment]
Where is the Application installed?

**Comment by bjmin** [comment]
@joaomoreno under `/Applications`

**Comment by joaomoreno** [comment]
Can you find anything interesting in the Console application, specific to VS Code?

**Comment by bjmin** [comment]
@joaomoreno Sorry, I dont know how..~ could u please tell me what am I going to do

**Comment by freeformz** [comment]
I can't get the vscode icon into the dock, nor does the icon show up when I alt-tab between open applications. This started happening after I upgraded to vscode 1.6

**Comment by freeformz** [comment]
FWIW: I am still on El Capitan

**Comment by joaomoreno** [comment]
cc @bpasero Could be related to Electron update

**Comment by joaomoreno** [comment]
@bjmin @freeformz Does it work if you completely remove Code and download a fresh build from our website?

**Comment by bjmin** [comment]
@joaomoreno sorry, i've tried many times, it doesnt work

**Comment by freeformz** [comment]
Ditto. No luck.

On Thu, Oct 13, 2016 at 08:25 Benjamin Huang <notifications@github.com>
wrote:

@joaomoreno <https://github.com/joaomoreno> sorry, i've tried many times,
it doesnt work

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/13389#issuecomment-253546730>,
or mute the thread

**Comment by Dafrok** [comment]
The same issue.:+1:

**Comment by freeformz** [comment]
This is fixed for me after upgrading to 1.6.1

**Comment by joaomoreno** [comment]
@bjmin @Dafrok you?

**Comment by bjmin** [comment]
Yes, fixed!.. but i wanna know what cause this exactly

**Comment by joaomoreno** [comment]
Yeah me too 👍

**Comment by Dafrok** [comment]
@joaomoreno It works, good job 👍

**Comment by LeonineKing1199** [comment]
This is still an issue for me. I'm using a new MacBook Pro with VSCode version 1.14.2. 

Admit it, this is just so people will start using this IDE on Windows ;)

**Comment by normrankin** [comment]
Still an issue for me, too.

- VSCode v1.14.2
- macOS Sierra v10.12.6

Every time I shut down VSCode and go to relaunch from the Dock, a question mark appears over the icon and nothing else happens. If I remove the 'corrupted' icon, relaunch VSCode, secondary click the icon and select "Keep in Dock", the same thing happens on the next launch.

**Comment by normrankin** [comment]
Okay, so one of two different things worked for me. I'm not 100% sure which one did it, but I've got it working now and I don't want to end up breaking it by testing further. So I recommend doing both for good measure:

- Use the macOS default unarchiving app, "Archive Utility" (when I was having this issue, I was extracting the VSCode app using a 3rd-party utility called "Dr. Unarchiver"
- Do not extract the app straight into the Applications directory; extract it into the Downloads folder, then drag and drop it into the Applications directory

Doing these two things worked for me. I even rebooted as a final test, and the dock icon still launched VSCode with no problem.

**Comment by oller** [comment]
I believe this to be a broader electron issue, it's occuring for me as described by OP with vscode, atom and flowdock.

See https://github.com/electron/electron/issues/9293, https://github.com/atom/atom/issues/13695

**Comment by MarqueIV** [comment]
I think I found the issue.  It has to do with apps downloaded from the internet.  In the case of normal installers, it prompts you at the point of install.  But VS Code is an application you get from a zip file, so you actually have access to the app file itself before you've verified it's safe.  So, if you unzip, then drag it to your dock (doesn't matter where it is... downloads, applications, etc.) you'll have the issue.  However, if before you drag it to the dock you open the app, it will go through the verify step, prompting you about it being downloaded.  Let it open, *then* you can drag it from the Applications folder (or wherever it is) to the dock.

To be sure this was the issue, I deleted it from my dock, then from Applications, then using the exact same ZIP file I already had downloaded, I again extracted the app, moved it to Applications, then added it to the dock, *then* launched it, and sure enough, it was back to the double-icon/icon disappearing behavior.  Again, deleted everything, this time after I unzipped it but before I added it to the dock (I did this twice... one running it right from 'Downloads' before moving it to 'Applications', and a second time where I moved it to 'Applications' then ran it, but again, in both cases *before* I added it to the dock), and all worked as expected.

TLDR version, it's not a VS Code issue, it's not an Electron issue.  It's not an Archive Utility vs Dr. Archiver or anything else issue.  It's a 'You added it to the dock before you verified it was safe!' issue.

Hope this helps!

**Comment by stevenreddie** [comment]
For anyone having this issue, see my root cause and workaround that I just posted at https://github.com/electron/electron/issues/9293#issuecomment-331422359

**Comment by mehedi-sharif** [comment]
I am having the same issue . I am using mac os high sierra .
