### ISSUE TITLE
Test: Proposed `keepScrollPosition: boolean` in quickpick API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#133891]
Refs: #132068

- [x] anyOS @isidorn
- [x] anyOS @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133891%0A%0A&assignees=TylerLeonhardt)

---

This iteration we added a new property on the `QuickPick` object that allows you to control whether or not the scroll position (`cursorTop`) in the quickpick moves back to the top of the list.

* Create a new extension
* Allow it to use the proposed API: `npx vscode-dts dev`
* using the `QuickPick` object you get back from the `window.createQuickPick()` API, play with the new `keepScrollPosition: boolean`

Usecases:
* Implementing a "remove this item from the list" [using the also proposed `QuickPickItemButton`s](https://github.com/microsoft/vscode/pull/130519) (think, Ctrl/Cmd + P `x` QuickPickItemButton)
* Implementing a "toggle this item in someway" [using the also proposed `QuickPickItemButton`s](https://github.com/microsoft/vscode/pull/130519) (think, "Insert Snippet" command)
* Asynchronously loading items in the quickpick (like `setInterval` adding an item to the list by reassigning the `.items` property... scroll shouldn't jump to the top)

**Comment by isidorn** [comment]
For reference here's my tester extension for this. Might help as a starting point @luabud 

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	let disposable = vscode.commands.registerCommand('sep-ext.helloWorld', async () => {
		const pick = await vscode.window.createQuickPick();
		pick.keepScrollPosition = true;
		const items = [{ label: 'january' }, { label: 'february' }, { label: 'march' }, { label: 'april' }, { label: 'may' }, { label: 'june' }, { label: 'july' }, { label: 'august' }, { label: 'september' }, { label: 'october' }, { label: 'november' }, { label: 'december' }];;
		pick.items = items;
		pick.show();

		let i = 0;
		setInterval(() => {
			items.push({ label: String(i++) })
			pick.items = items;
		}, 500);
	});
	context.subscriptions.push(disposable);
}

export function deactivate() { }
```

**Comment by luabud** [comment]
@isidorn thanks a lot for the example, it was super helpful! 🤩
