### ISSUE TITLE
Test tunnels via shared process

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#133889]
- [x] anyOS @DonJayamanne
- [x] anyOS @aeschli

Complexity: 4

Authors: @alexr00 @alexdima 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133889%0A%0A&assignees=alexdima,alexr00)

---

The first assignee please test using remote containers.
The second assignee please test using remote SSH.

* Connect to a remote and launch there a server.
* Use `Forward a Port` or any of the auto gestures (ctrl+click, etc) to get a tunnel going
* Access the tunnel in a browser and check that you can reach your remote server
* Go to the Ports view and remove the forwarded port
* Check that you can no longer reach the remote server
* Forward the port again
* Close the window
* Check that you can no longer reach the remote server
* (only for SSH) forward a port, simulate a disconnection by disabling network connectivity, wait for the disconnection dialog, re-enable the network, wait for reconnection to succeed, check that the tunnel still works.

**Comment by DonJayamanne** [comment]
I've test this with desktop vscode insiders & Github Codespaces & it works as expected.

**Comment by aeschli** [comment]
Tested with Linux and MacOS servers and Win/MacOS/Ubuntu UI.
