### ISSUE TITLE
`Help > Welcome` is missing and we seem to have `Help:&& Get Started`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#133882]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Insiders
- OS Version: Mac

Up until last week I've been using `Help > Welcome` to get to the welcome page in VS Code
Seems to be missing, or replaced with `Help > Get Started`

Steps to Reproduce:

* Look for `Help > Welcome` in command palette, its missing
	* Renaming this is a bug, i'm used to looking for `welcome` in the command palette, and took me a while to find that, I think users who're used to that might have similar issues as well (muscle memory)
* The text `Help: && Get Started` isn't right (notice the `&&`)

**Comment by gjsjohnmurray** [comment]
First item: see #132158 - pininging @digitarald 
Second item: see #133873 (already fixed)

**Comment by digitarald** [comment]
@DonJayamanne I did check numbers and few users opened Welcome page from commands, so renamed the command as well. I'd be curious to learn your use case for opening the Welcome page via command?

**Comment by DonJayamanne** [comment]
> curious to learn your use case for opening the Welcome page via command?

I use the welcome page to go to my recently opened folders, i find that the easiest way to toggle between multiple repos.
E.g. if i'm working on jupyter extension & want to switch to VSCode repo in the same instance of code, then I open the welcoem page & click the `vscode` folder.
If i want to open another instance, then I open a terminal, go to that folder & then open vscode in that folder (i probably could always use the terminal, but the command is easier, less typing, even though i need to use the trackpad)

I.e. it just comes down to muscle memory.
