### ISSUE TITLE
Python doesn't debug with breakpoints

### ISSUE THREAD

**Issue by user-mw** [Microsoft/vscode#13384]
- VSCode Version:
1.5.3.
- OS Version:
Windows 7.

Hello to everybody. I have installed last version of VS Code from official site. I created simple code that just printing "Works" 4 times and when I set breakpoint on the second line I got 4 string "Works".  Why it doesn't react on breakpoints?
![for vscode](https://cloud.githubusercontent.com/assets/20878377/19214700/fc883578-8d89-11e6-9a62-65162d371eae.png)

**Comment by tonka3000** [comment]
Do you have the python extension installed?

**Comment by user-mw** [comment]
Scripts are running from cmd. Thank you for answer, but it is not a decision.

**Comment by isidorn** [comment]
Please file this issue with the python extension here https://github.com/DonJayamanne/pythonVSCode

**Comment by user-mw** [comment]
What I must do with it? 
"Install the extension"? How must I do it?
And I have the same extension that I've installed within VS Code with the same author. But versions are different, of course.
