### ISSUE TITLE
error and warning

### ISSUE THREAD

**Issue by Mitul2003** [microsoft/vscode#133802]
Issue Type: <b>Feature Request</b>

vs code not work proparly and not show error and warning when code was typing.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by CodeCrazy-ywt** [comment]
Screenshot?
