### ISSUE TITLE
Support moving views into editor tabs

### ISSUE THREAD

**Issue by Password-Classified** [microsoft/vscode#133801]
Now you can move a terminal into an editor area, would it be possible to move the problems panel into the editor? I think it'd really improve my productivity, and, no doubt, that of others. It'd be helpful if you want to have it split vertically with an editor like this...

Layout

| Main file| Extra file|
|-|-|
|Main file |Problems panel |

**Comment by ardunster** [comment]
This is a duplicate of my request: https://github.com/microsoft/vscode/issues/132567  Hopefully we can get enough upvotes on one of them!
