### ISSUE TITLE
suggestion screen cheese

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1338]
* do JS
* trigger so that <no suggestion> appears
* type
* ~> a weird shadow follows me

![screen shot 2015-12-15 at 16 10 50](https://cloud.githubusercontent.com/assets/1794099/11814358/95b09378-a346-11e5-894d-27eaf2ee4ef8.png)

**Comment by joaomoreno** [comment]
Great catch!

**Comment by jrieken** [comment]
I know :blush:
