### ISSUE TITLE
Website certs expired

### ISSUE THREAD

**Issue by im-coder-lg** [microsoft/vscode#133800]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:
Those aren't applicable right now.
Steps to Reproduce:

1.
2.
No steps to reproduce

Hey, I wanted to download VS Code so I wanted to head to the official website([code.visualstudio.com](https://code.visualstudio.com/)) but I discovered that the certificates for the website has expired. Can any Microsoft people look onto it when they are free? This might be a security vulnerability in the website, so I am informing this here.

**Comment by im-coder-lg** [comment]
Also, sorry that I posted it _here_, I needed to inform this.

**Comment by gjsjohnmurray** [comment]
Seems OK for me:

![image](https://user-images.githubusercontent.com/6726799/134773713-c33d827b-3fba-460f-961d-ad98f4c35ccb.png)

**Comment by im-coder-lg** [comment]
Check from your browser, my Vivaldi showed that the site is insecure(as of now). I can't reach my laptop since I am outside but I will try sending a screenshot via phone.

**Comment by im-coder-lg** [comment]
I think I have certs error on my PC. Will check and report back :+1:

**Comment by im-coder-lg** [comment]
Yup, looks like certs error in my PC. Sorry for the issue. I think only my PC has this, so I am closing it.
