### ISSUE TITLE
Custom Syntax Highlighter doesn't match newlines

### ISSUE THREAD

**Issue by Anatoly03** [microsoft/vscode#133838]
Issue Type: <b>Bug</b>

What I am trying to match a certain regex containing newlines, but it cannot be matched as both 'begin', 'match' and 'end' do not support newlines.

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id fbb8cc59-ddf3-407c-bad4-37c2fd6f8e21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|12.2.0
angular-schematics|cyr|5.0.0
vscode-eslint|dba|2.1.25
tslint|eg2|1.0.47
prettier-vscode|esb|8.1.0
copilot|Git|1.4.2782
go|gol|0.28.1
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
discord-vscode|icr|5.7.0
docthis|joe|0.7.1
dotnet-core-essentials|Kis|0.0.8
dotenv|mik|1.0.1
csharp|ms-|1.23.15
cpptools|ms-|1.6.0
vsliveshare|ms-|1.0.4836
angular-console|nrw|17.11.0
vetur|oct|0.34.1
rust|rus|0.7.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vshan820:30294714
vstes263cf:30335440
pythonvsuse255:30340121
vscod805cf:30301675
binariesv615:30325510
vsccppwt:30364497
bridge0708:30335490
pygetstartedt2:30371810
bridge0723:30353136
javagetstartedt:30364666
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by alexdima** [comment]
TM grammars operate on a single line at a time. It is possible to match newlines and keep track of them using states (begin/end). There are multiple websites that document TextMate grammars.
