### ISSUE TITLE
Blank preview, blank issue reporter, blank process explorer ...

### ISSUE THREAD

**Issue by texjoachim** [microsoft/vscode#133883]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 1.60.2
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Open VSCode.
2. Open any file that can be previewed. (html, markdown, ...)
3. Open preview or Open preview to the side.
4. Preview stays blank.

I also noticed that any window that would normally let me view something will be blank:
Release notes: blank.
Issue reporter: blank.
Process explorer: blank.

I've tried a completely fresh profile, but everything by the editor part is still blank.

**Comment by texjoachim** [comment]
Here is a screenshot:

![Bildschirmfoto von 2021-09-27 19-08-45](https://user-images.githubusercontent.com/6815932/134954615-2a80b38a-cd74-49f6-a998-a09bc3e00618.png)

**Comment by TylerLeonhardt** [comment]
it seems like it could be electron related. Added @deepak1556 and @rzhao271

**Comment by texjoachim** [comment]
Sure, here it is:
[code-verbose.txt](https://github.com/microsoft/vscode/files/7244928/code-verbose.txt)

**Comment by deepak1556** [comment]
Thanks for the log, you are hitting https://github.com/intel/libva/issues/278. Try the workarounds mentioned in that issue by setting the driver name or path via `LIBVA_DRIVER_NAME` or `LIBVA_DRIVER_PATH` based on the drivers installed https://github.com/intel/libva/blob/master/va/drm/va_drm_utils.c#L39-L49.

You can also try to disable hardware acceleration with `--disable-gpu` or use the software renderer via `--use-gl=swiftshader`

**Comment by texjoachim** [comment]
--disable-gpu and --use-gl=swiftshader make Visual Studio Code crash on start.

Setting LIBVA_DRIVERS_PATH=/usr/lib64/dri/ and LIBVA_DRIVER_NAME=i965 (those are present on my system) doesn't help either.

**Comment by deepak1556** [comment]
Can you attach the crash report following the steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports with above flags included. For ex:

```
code --disable-gpu --crash-reporter-directory /tmp/vscode-gpu-crash
```

**Comment by texjoachim** [comment]
Here are the two crash reports:
[crash-reports.zip](https://github.com/microsoft/vscode/files/7260820/crash-reports.zip)

**Comment by dlichtenberger** [comment]
I also encounter this issue on openSUSE Tumbleweed, but with an AMD graphics card and using KDE. 

VS Code releases prior to 1.60 also have the issue, they worked correctly until recently - so I suspect this is related to a Tumbleweed update (the last big update was for glibc 2.34 a couple of weeks ago, not sure how this could be related though).

**Comment by texjoachim** [comment]
Yes, it works indeed!
![Bildschirmfoto von 2021-10-08 15-14-32](https://user-images.githubusercontent.com/6815932/136563624-a29a00df-cb8a-445b-a5f4-84ab48f0192e.png)
