### ISSUE TITLE
`Shift+Alt+R` for `Reveal in File Explorer` doesn't work when focus is in `text editor

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#133805]
CC @isidorn -- `Shift+Alt+R`, the key stroke for `Reveal in File Explorer` doesn't work when focus is in `text editor` on Windows. Could you please check this issue?

Version: 1.60.2 (system setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by IllusionMH** [comment]
This action has `"when": "!editorFocus"` therefore it won't work from editor.
Implemented in https://github.com/microsoft/vscode/issues/47947#issuecomment-383929389

**Comment by isidorn** [comment]
@IllusionMH thanks for answering!
@jooyoungseo does that recommendation work for you? Since we can not use that keybinding when in editor since the Find Widget already uses it?
