### ISSUE TITLE
confuse shortcut for split cell in notebook

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#133817]
版本: 1.61.0-insider (system setup)
提交: 8d30d4d922dda917d22f05a81f2ab4fad7349779
日期: 2021-09-24T09:00:59.405Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
<kbd>ctrl+k ctrl+shft+\\<kbd>

1. 
![image](https://user-images.githubusercontent.com/1876302/134797057-2d778f3a-b6d4-4d84-b3fe-c32c99c4924d.png)

<kbd>ctrl+shft+-<kbd>

2. 
![image](https://user-images.githubusercontent.com/1876302/134797059-905f840a-84df-48bf-8c36-20ee90635658.png)

**Comment by roblourens** [comment]
One of these is contributed by the Jupyter keybindings extension. But, I'm not sure why they show differently between these two menus.

**Comment by rebornix** [comment]
It seems we don't have these actions in menu anymore.
