### ISSUE TITLE
Smart Commit Dialogue stopped working after installing newest update

### ISSUE THREAD

**Issue by neuronflow** [microsoft/vscode#133859]
- VS Code Version: 1.60.2
- OS Version: OSX 11.6

Steps to Reproduce:
With the last VS Code update, the smart commit dialogue box stopped working for me. It is not shown anymore. I checked and unchecked the settings and set:
```
"git.enableSmartCommit": true
```

Also restarting VS code does not work. Thanks for your help!

**Comment by neuronflow** [comment]
Before I always, had a dialogue like:
"There are no staged files, would you like to stage all changes?"
It seems to be gone now. I highly enjoyed it...

Now sometimes I have to manually remove 50+ staged files, or keep the setting off.

**Comment by lszomoru** [comment]
> Now sometimes I have to manually remove 50+ staged files, or keep the setting off.

@neuronflow, could you please provide the exact steps to reproduce this issue? Thank you!
