### ISSUE TITLE
Bug of vscode built-in bracket hightlight

### ISSUE THREAD

**Issue by SecYJ** [microsoft/vscode#133878]
I have tested that vscode built-in bracket highlight will cause .vue files html template punctuation definition tag color not working 
![vscode issue](https://user-images.githubusercontent.com/79868091/134947032-9ce0022f-9506-4bfc-9d79-cb2ba30bb9e7.png)

**Comment by IllusionMH** [comment]
VS Code removed highlight for `<`/`>` so shouldn't be a problem. Is it what you expect from fix?
Do you see this issues in Insiders?

**Comment by hediet** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/132476.
