### ISSUE TITLE
Enlarging by dragging: Background not in accordance to OS theme

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/vscode#133820]
Issue Type: <b>Bug</b>

### Steps to Reproduce:
1. Use OS day theme
2. Start VS Code
3. Switch to OS night theme
4. Enlarge VS Code window size by dragging

### Problem:
When enlarging the window has a white (day theme) background

### Expected:
When enlarging the window would have a dark (night theme) background

### Visual demonstration:

https://user-images.githubusercontent.com/24418160/134799483-12edb4a0-a17b-47d7-ab22-a15438390ad4.mp4

### System information:

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 66972b6f-696c-4473-810b-c0357cc17a00|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

**Comment by jrieken** [comment]
Unrelated to splash screen, likely theme caching

**Comment by bpasero** [comment]
I know this used to work at one point but maybe broke. Relevant code seems to be:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/theme/electron-main/themeMainService.ts#L77-L84

**Comment by bpasero** [comment]
Debugging this locally, I can confirm that we call `window.setBackgroundColor` with the right values dynamically when the theme changes. As such I conclude that this is a Electron bug where the background color is applied differently when creating  a window vs. when calling `setBackgroundColor`.

**Comment by bpasero** [comment]
Upstream: https://github.com/electron/electron/issues/26842
