### ISSUE TITLE
The following menu items cannot customize the shortcut keys. How can I customize the shortcut keys?

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#133806]
Issue Type: <b>Bug</b>

The following menu items cannot customize the shortcut keys. How can I customize the shortcut keys?
![无法自定义快捷键](https://user-images.githubusercontent.com/54253524/134788097-30b1e78b-d85c-42ff-8822-e0e993c1a279.png)

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by zhouxinghong** [comment]
> https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor and search for these commands

Peek Call Hierarchy
Peek Type Definition
Go to Type Definition

Hello! The above three commands cannot find the results, can you try? ? ?

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/135135286-7aa8ce7d-5e9a-4bec-b2f4-57d0afa6abdf.png)

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/135135456-649041ae-c3e7-4d41-8b8f-e1344d32f582.png)

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/135135504-ad5a2953-4060-49cc-be67-bc85a3efafcc.png)

**Comment by zhouxinghong** [comment]
Hello! Thank you for your careful help!
  "Peek Type Definition"
  "Go to Type Definition"
Can be searched, but "Peek Call Hierarchy" cannot be searched? ? ? Where can I find it and add shortcut keys?

**Comment by zhouxinghong** [comment]
> > https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor and search for these commands
> 
> Peek Call Hierarchy Peek Type Definition Go to Type Definition
> 
> Hello! The above three commands cannot find the results, can you try? ? ?

Hello! Thank you for your careful help!
  "Peek Type Definition"
  "Go to Type Definition"
Can be searched, but "Peek Call Hierarchy" cannot be searched? ? ? Where can I find it and add shortcut keys?

**Comment by zhouxinghong** [comment]
> https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor and search for these commands
Hello! Thank you for your careful help!
  "Peek Type Definition"
  "Go to Type Definition"
Can be searched, but "Peek Call Hierarchy" cannot be searched? ? ? Where can I find it and add shortcut keys?

**Comment by sbatten** [comment]
@zhouxinghong I believe it is `editor.showCallHierarchy`

**Comment by zhouxinghong** [comment]
> @zhouxinghong I believe it is `editor.showCallHierarchy`
The default shortcut key (shift+alt+h) you mentioned is not the same command as the "Peek Call Hierarchy" I mentioned? If you don’t believe me, you can try it?

**Comment by sbatten** [comment]
@jrieken it looks like Peek Call Hierarchy does not have a bindable command id in the keybindings editor. is this intentional?

**Comment by zhouxinghong** [comment]
> @jrieken it looks like Peek Call Hierarchy does not have a bindable command id in the keybindings editor. is this intentional?

Have you confirmed that my point of view is correct?

**Comment by zhouxinghong** [comment]
> @jrieken it looks like Peek Call Hierarchy does not have a bindable command id in the keybindings editor. is this intentional?

Will you reopen this problem to fix it?

**Comment by jrieken** [comment]
The concept of unbindable command ids does not exist, I also don't see what you a reporting. I can bind any keybinding to the peek command. 

<img width="553" alt="Screen Shot 2021-10-04 at 09 41 52" src="https://user-images.githubusercontent.com/1794099/135812308-09f850b1-02e1-45ce-abe3-9266618b6501.png">

*Note* that you need to unbind the keybinding for the "Show Call Hierarchy" when you are planning to use the same short cut. This is my config

```
	{
		"key": "shift+alt+h",
		"command": "editor.showCallHierarchy",
		"when": "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor"
	},
	{
		"key": "shift+alt+h",
		"command": "-references-view.showCallHierarchy",
		"when": "editorHasCallHierarchyProvider"
	}
```

**Comment by zhouxinghong** [comment]
> The concept of unbindable command ids does not exist, I also don't see what you a reporting. I can bind any keybinding to the peek command.
> 
> <img alt="Screen Shot 2021-10-04 at 09 41 52" width="553" src="https://user-images.githubusercontent.com/1794099/135812308-09f850b1-02e1-45ce-abe3-9266618b6501.png">
> 
> _Note_ that you need to unbind the keybinding for the "Show Call Hierarchy" when you are planning to use the same short cut. This is my config
> 
> ```
> 	{
> 		"key": "shift+alt+h",
> 		"command": "editor.showCallHierarchy",
> 		"when": "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor"
> 	},
> 	{
> 		"key": "shift+alt+h",
> 		"command": "-references-view.showCallHierarchy",
> 		"when": "editorHasCallHierarchyProvider"
> 	}
> ```
Hello! Can you tell me the key binding command of vscode IDE "Peek Call Hierarchy" in windows10 operating system? thank you very much!
