### ISSUE TITLE
enable (or simplify) jupyter notebook raw view 

### ISSUE THREAD

**Issue by xvdp** [microsoft/vscode#133877]
I use vscode for coding, merging, debugging but not to evaluate jupyter or colab notebooks: that I keep in the browsers. And yet often - due to issues with portability between colab + jupyter + github on forked projects - I need to edit the notebook raw json code. It would be useful to have an easily accessible global switch to not start a server for jupyter. 

This is probably possible, but it isn't obvious how to set that up. A simple setting, or documentation thereof, would be useful workflow addition.

**Comment by misolori** [comment]
Have you tried re-opening a notebook with a different editor? You can right-click on any file and select "Open With..." and select "Text Editor" to open the json:

<img width="429" alt="CleanShot 2021-09-27 at 11 31 09@2x" src="https://user-images.githubusercontent.com/35271042/134965470-f5d531de-d00a-4bac-a66d-0475b28a13e3.png">

<img width="363" alt="CleanShot 2021-09-27 at 11 31 43@2x" src="https://user-images.githubusercontent.com/35271042/134965511-0e7088e7-b672-49bf-ba5c-c78c1cc0a104.png">

<img width="682" alt="CleanShot 2021-09-27 at 11 32 04@2x" src="https://user-images.githubusercontent.com/35271042/134965533-179e01d3-26bb-44d3-bbf7-7829871846a4.png">

You can also right-click on the tab and re-open from there:

<img width="373" alt="CleanShot 2021-09-27 at 11 32 18@2x" src="https://user-images.githubusercontent.com/35271042/134965593-a9aa2883-6619-4609-b3b0-40e1328cf488.png">

**Comment by rebornix** [comment]
@xvdp does Miguel's suggestion work for you?

**Comment by xvdp** [comment]
t
