### ISSUE TITLE
Keyboard short for duplicating selection

### ISSUE THREAD

**Issue by achshar** [Microsoft/vscode#13387]
- VSCode Version: 1.5.3
- OS Version: Windows 10

It would be nice to have a keyboard shortcut for duplicating selection, which is equal to ctrl+c, ctrl+v. It's equivalant in sublime is ctrl+shift+d. There is a copyLineDown right now which are nice but doesn't copy the selection, just entire line.

There's also another issue that tracks a bunch of shortcuts, including this one but only for mac. There's a plugin for the duplication as well but it seems to be a visual studio plugin. I guess there must be a way to have those run for vs code but I didn't look it up.

**Comment by isidorn** [comment]
This would be best done with an extension. Please check if there is already an extension which provides this functionlity if not consider writing one :)

**Comment by delk0** [comment]
You don't need an extension for this, it's just a different shortcut. Try shift + alt + up or down key.

**Comment by delk0** [comment]
I thought that command had the same behavior as sublime, weird, hope it can be bult-in someday :/ Anyway seems like someone already made an extension that works as you say, haven't tried it myself but you may give it a go: [https://marketplace.visualstudio.com/items?itemName=rivenvirus.duplicatetext](url)

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try [this extension](https://marketplace.visualstudio.com/items?itemName=rivenvirus.duplicatetext) or some of the other ones in the marketplace
