### ISSUE TITLE
top level menu hotKey ALT + Ф on RUS localization, broken

### ISSUE THREAD

**Issue by yogggoy** [Microsoft/vscode#13386]
- VSCode Version: 1.5.3
- OS Version: win10 x64 home

on Russian localization doesn't work hotKey for top level menu (File, Edit, View, ..) alt+f

Steps to Reproduce:
1. open locale.json ("configure language" in F1 palette)
2. set: "locale":"ru"
3. push ALT+F, ALT+Ф, ALT+f, ALT+ф

GIF:
![2016-10-09_00-24-24](https://cloud.githubusercontent.com/assets/15965289/19216042/3cf7ea2c-8db7-11e6-86d5-37ebabeb6fb5.gif)

ps:why did not like a ja,ch,ko - 
![code_2016-10-09_00-31-22](https://cloud.githubusercontent.com/assets/15965289/19216068/e5fa4106-8db7-11e6-8ace-267fe340f58c.png)
![code_2016-10-09_00-31-49](https://cloud.githubusercontent.com/assets/15965289/19216070/ef855ae4-8db7-11e6-958f-dc84eda17458.png)

**Comment by dbaeumer** [comment]
@johnliu2016 can you please comment. Do we need to add the (F) or Russian as well?

**Comment by johnliu2016** [comment]
@dbaeumer @yogggoy as far as I know, hotkey translation style for Russian follows western languages @lukaschal, can you check this please?

**Comment by yogggoy** [comment]
add the (F), please.
I think use RUS hotkeys is a bad way for programmers writing code on [Latin script](https://en.wikipedia.org/wiki/Latin_script).
We have to constantly switch between EN and RU layout keyboard for use 'Ф' instead 'F'.

**Comment by lukaschal** [comment]
All hotkeys are localized by this way. Same on visual studio for example. Maybe we can move this HK to some other letter for better functionality.

![rus](https://cloud.githubusercontent.com/assets/18324331/19276772/c759b8cc-8fd7-11e6-9f2c-12bd9d560e03.png)

**Comment by lukaschal** [comment]
@johnliu2016  @dbaeumer  So should we move HK to another letter ?

**Comment by dbaeumer** [comment]
@lukaschal  actually I don't know. Do you know what other tools do here. Looks like VS are like us. But Office ?

**Comment by lukaschal** [comment]
@johnliu2016 Do we have any idea how to deal with this ?

**Comment by johnliu2016** [comment]
@yogggoy retaining English hotkey is not the usual way of handling hotkey loc to Russian, if to apply, it will require product wide hotkey change to everywhere hotkey exists. @janbaltus, can you share your idea?

**Comment by janbaltus** [comment]
Russian version of SW use Russian characters for shortcuts as we presume user use Russian keyboard.
This also go agains MS styleguide.
If you have case users are asking for ENU shortcuts it should be fixed on Code side and enable ENU shortcuts together with Localized ones.

**Comment by yogggoy** [comment]
Thank you for a deep analysis of the problem,
Yes, most of the programs used russian characters hot keys,
@johnliu2016, @janbaltus rights.

now it is necessary to solve an bug, I remind:
hot keys top level menu doesn't work,
when press Alt - occurs only highlighting the menu,
but when combined with any of the characters (Ф, И, П, П, С), nothing happens.
Error occurs on any layout, EN,RU.

**Comment by johnliu2016** [comment]
@dbaeumer  seems some functional issue with hotkey combination on Russian VSCode

**Comment by dbaeumer** [comment]
@johnliu2016 I think there are two different issues. Keyboard shortcuts and Russian keyboard layout. @alexandrudima can you explain what we do here.

Top level Alt hot keys. This hot keys are usually deboted in the translatation using & characters and if we want to change them this has to happen in the corresponding translations.

**Comment by alexandrudima** [comment]
I'm sorry this issue is talking about localization, OS menu accelerators (Alt+F), etc. I am not sure what you'd want me to explain @dbaeumer

**Comment by dbaeumer** [comment]
@alexandrudima I was referring to this:
>Russian version of SW use Russian characters for shortcuts as we presume user use Russian keyboard.

All our short cuts are with latin characters. Is there anything we can do to make these locale specific.

**Comment by lukaschal** [comment]
Is there anything we can do on localization side with this issue ?

**Comment by dbaeumer** [comment]
Alt+F works for me on an English locale.

@yogggoy just to double check. Pressing Alt+Ф when in Russian locale with a Russian keyboard does nothing. Right?

**Comment by yogggoy** [comment]
@dbaeumer yes, in RUS locale DOESN'T work alt+Ф (and any other combinations), in ENG locale all correct.

@alexandrudima write 
> I'm sorry this issue is talking about localization, OS menu accelerators (Alt+F), etc.

it should be understood as a problem on the side of the OS? can i close issue?

**Comment by dbaeumer** [comment]
@lukaschal I think translation is off the hook.

@bpasero this sounds like a Electron problem then since we don't control this. Does this ring any bell?

**Comment by yogggoy** [comment]
add: on virtual ubuntu 16.04 VSCode also does not work alt+Ф
@dbaeumer 
> this sounds like a Electron problem

It seems this is the case.
