### ISSUE TITLE
Keep Auto Complie

### ISSUE THREAD

**Issue by yangyann** [microsoft/vscode#133846]
Issue Type: <b>Bug</b>

VS Code keep auto compile even I didnt save the file. Hope can fix this issue.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.62GB free)|
|Process Argv|--crash-reporter-id a680f4fc-5c04-451d-9639-7bfeb0ea526f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|12.2.0
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.7.1
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.25
prettier-vscode|esb|9.0.0
sublime-keybindings|ms-|4.0.10
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824:30361777
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What do you mean under "auto compile"? Please provide more details about how to reproduce this issue.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
