### ISSUE TITLE
Test Colored Line Scopes

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#133906]
Refs: https://github.com/microsoft/vscode/issues/131001

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133906%0A%0A&assignees=hediet)

---

# Preparation

* Enable colored line scopes: `"editor.guides.bracketPairs": true,`.

# Tasks

* Verify line scopes are rendered correctly
* Verify that line scopes have the same color as bracket pairs when bracket pair colorization is enabled (`"editor.bracketPairColorization.enabled": true,`)
* Verify that colors can be customized and new colors can be added (up to 6):
    ```json5
    "workbench.colorCustomizations": {
        "editorBracketHighlight.foreground1": "#FFD700",
        "editorBracketHighlight.foreground2": "#DA70D6",
        "editorBracketHighlight.foreground3": "#87CEFA",
        // ...
    },
    ```
* Verify that this feature works nicely with indent guides (`"editor.guides.indentation": true,`)

**Comment by alexr00** [comment]
@hediet is the guide showing in the middle of words still expected: 
![image](https://user-images.githubusercontent.com/38270282/135066793-c37a8058-7626-4f9f-932d-05e22f962dfb.png)

**Comment by paulacamargo25** [comment]
Works as expected, nice job!
<img width="292" alt="Screen Shot 2021-09-28 at 11 23 45 AM" src="https://user-images.githubusercontent.com/17892325/135144312-c489071a-8763-4ef7-a355-70ee01e241d6.png">
