### ISSUE TITLE
Code lens font seems to have been broken/changes in the latest insiders 

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#133912]
It seems to be monospace in the screenshot, and it used to not be.
![image](https://user-images.githubusercontent.com/641685/135000959-6d78fbc0-d76f-48ac-8b90-3c34d1a5af6d.png)

**Comment by yume-chan** [comment]
#119406

**Comment by eamodio** [comment]
Hrm, I fell that #119406 is a bad change, not only does it change the code lens font for everyone, it IMO looks ugly because a monospace font doesn't feel good for this UI. Also with this change it because much harder to configure the code lens font properly across machines. Before #119406 the code lens font would follow the system font, which now gets harder to do. While changing the `editor.codeLensFontFamily` setting to the editor font feels easier because I would venture that more people are already customizing the editor font and use that same font across machines.

**Comment by jrieken** [comment]
Yeah, makes sense. I'll go ahead and revert the change for code lens. This was overeager alignment with inlay hint which, contrary to lenses, show source code. Lenses are UI controls, not source code

**Comment by jrieken** [comment]
closed with https://github.com/microsoft/vscode/commit/6995719840aa97ef9b8100b8dbde1ea9e61e0e96
