### ISSUE TITLE
Java script code did not run...

### ISSUE THREAD

**Issue by MasteR-XXX** [microsoft/vscode#133991]
We have writ
Issue Type: <b>Bug</b>

nodejs : The term 'nodejs' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ nodejs "c:\Users\Suraj\abcde.js"
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (nodejs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.47GB free)|
|Process Argv|--crash-reporter-id d91c097c-798c-4d8f-90fc-7501bca42675|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
js-quick-console|Aha|0.0.3
code-runner|for|0.11.5
cpptools|ms-|1.6.0
js-debug-nightly|ms-|2021.9.2017
open-in-browser|tec|2.0.0
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791

```

</details>

ten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify how VS Code editor itself related to issue with missing `nodejs` executable (in usually install as `node` in `PATH` not sure where you get `nodejs`). And relevant configurations if any.
