### ISSUE TITLE
Open workspace from vscode:// url

### ISSUE THREAD

**Issue by rsargent** [microsoft/vscode#133976]
I can open a workspace by specifying a .workspace file from the commandline:

    code /path/to/my.workspace

I'd like to be able to open a workspace from a vscode: url like so:

    vscode://file/path/to/my.workspace

Thanks for considering.

**Comment by bpasero** [comment]
Looks like a bug to me that we never supported that. Something must have broken here given my comment.

//cc @joaomoreno on the fix

**Comment by TylerLeonhardt** [comment]
Am I doing something wrong?

```sh
# works
code-insiders /Users/tyleonha/Code/Misc/multi-root-test/workspace.code-workspace

# doesn't work
code-insiders vscode://Users/tyleonha/Code/Misc/multi-root-test/workspace.code-workspace
code-insiders vscode:///Users/tyleonha/Code/Misc/multi-root-test/workspace.code-workspace
```

**Comment by bpasero** [comment]
Yes, this is about link handlers, not CLI.

**Comment by bpasero** [comment]
@rsargent could you verify in insiders?

**Comment by rsargent** [comment]
Confirmed! I installed

    Version: 1.61.0-insider (Universal)
    Commit: 83b7d33abba1fbc9ba6dbf25b53b47821086b22f
    Date: 2021-09-30T18:59:55.207Z (14 hrs ago)
    Electron: 13.5.0
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Darwin x64 19.6.0

and successfully opened a workspace with the vscode-insiders:// url variant by typing

    vscode-insiders://file/path/to/my.workspace

into my web browser.

Thanks so very much for responding so incredibly quickly to the original report.
