### ISSUE TITLE
extra guide lines on large file

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#133916]
Testing #133906

set `"editor.guides.bracketPairs": true`
clone the typescript repo https://github.com/microsoft/TypeScript and open `src/compiler/checker.ts` (this is simply a large file, not sure if that has anything to do with this).

result: additional vertical guidelines as seen here: 

![image](https://user-images.githubusercontent.com/1487073/135002918-01de0570-9bbf-4f2e-8026-5cc86a8b8a0c.png)

If you click around they guides will be highlighted and eventually disappear...

**Comment by hediet** [comment]
This has the same reason as #133921 - when opening checker.ts initially, bracket pairs are not very accurate - in particular not, when a lot of brackets appear in strings and comments, as in checker.ts.

I think the solution here would be to consider the minimum indentation when rendering these bracket guides.
