### ISSUE TITLE
SCM action command handlers are passed invalid context

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#133938]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61-insider
- OS Version: Windows 10

Steps to Reproduce:
1. Install Remote Repositories extension
1. Set `"scm.alwaysShowRepositories": false`
2. Invoke 'Create a Pull Request' command from SCM view
![image](https://user-images.githubusercontent.com/30305945/135025870-a3d837c6-4329-431c-8a6f-8e2116854b20.png)
3. Nothing happens. This is because the command is unexpectedly passed a context object of type `{ preserveFocus: boolean }` and the command handler doesn't handle it well. We're fixing this in the Remote Repositories extension but VS Code should not be passing this context object.

**Comment by eamodio** [comment]
This looks like we are not passing the correct repository context (SourceControl object) when there is 1 repository and `scm.alwaysShowRepositories` is `false`.

**Comment by lszomoru** [comment]
@joyceerhl, I am unable to repro this with the latest VS Code and Github Repositories extension. Please feel free to reopen if you still have a repro. Thanks!
