### ISSUE TITLE
Alpine ARM64 - Search and file quick pick is broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#133993]
Testing #133893

![image](https://user-images.githubusercontent.com/10746682/135083508-244f6059-e185-41e2-9757-38d4bb285336.png)

**Comment by deepak1556** [comment]
The binary is indeed available in the server folder but the libc library it is linked with does not exist on the image.

```
> file rg
rg: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=9aeeefc40f268f2df9b99c2549fddbd3f9fe0171, stripped

> pwd
/vscode/vscode-server-insiders/bin/alpine-arm64/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node_modules/vscode-ripgrep/bin

> /vscode/vscode-server-insiders/bin/alpine-arm64/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node_modules/vscode-ripgrep/bin/rg
/bin/ash: /vscode/vscode-server-insiders/bin/alpine-arm64/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node_modules/vscode-ripgrep/bin/rg: not found

> ldd /vscode/vscode-server-insiders/bin/alpine-arm64/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node_modules/vscode-ripgrep/bin/rg

/lib/ld-linux-aarch64.so.1 (0xffff9741d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffff96fd9000)
        libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffff9741d000)
        libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffff9741d000)
        libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffff9741d000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by ./node_modules/vscode-ripgrep/bin/rg)

> ldd /vscode/vscode-server-insiders/bin/alpine-arm64/214ac689ca9874a8a4be386f73d5cb60e15af25e-insider/node

/lib/ld-musl-aarch64.so.1 (0xffff9b3e3000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffff973b2000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffff9738d000)
        libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffff9b3e3000)
```

**Comment by deepak1556** [comment]
Ripgrep should also build for `aarch64-unknown-linux-musl` rust target in https://github.com/microsoft/ripgrep-prebuilt/blob/main/build/main.yml to support alpine images.

**Comment by roblourens** [comment]
I can add that, thanks

**Comment by roblourens** [comment]
Ripgrep couldn't build under that target.

https://github.com/BurntSushi/ripgrep/blob/df83b8b44426b3f2179abe632eb183e8c8270524/crates/core/main.rs#L29 My understanding is… when building with musl, it uses jemalloc, jemalloc uses background_threads_runtime_support, and that doesn’t support our target.

If we can figure out how to un set that flag on jemalloc that might work around it but i don’t know what consequences that would have https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/README.md#cargo-features

**Comment by deepak1556** [comment]
@roblourens from https://github.com/gnzlbg/jemallocator/issues/124 it is not sure whether the bug is in jemalloc config or cargo, but the immediate working solution is to build the crate with `cross` https://github.com/BurntSushi/ripgrep/commit/5ce2d7351dba9c113318f4e43c041be7c25eaee4. I will see if that works.

**Comment by sandy081** [comment]
May I know if there is some workaround for this bug for users? If not, I do not think its good to ship Alpine ARM 64 builds with broken experience.

**Comment by deepak1556** [comment]
It will require users to install [libc6-compat](https://pkgs.alpinelinux.org/package/edge/main/aarch64/libc6-compat) package that will include the required libraries for the executable built using glibc.

```
apk add libc6-compat
```

**Comment by roblourens** [comment]
Not with your PR, right @deepak1556? Thanks for the PR btw

**Comment by deepak1556** [comment]
Yup https://github.com/microsoft/vscode/issues/133993#issuecomment-931193148 is not needed with the musl binary produced from the PR.

**Comment by deepak1556** [comment]
I didn't put up a PR to adjust https://github.com/microsoft/vscode-ripgrep/blob/main/lib/postinstall.js to download `aarch64-unknown-linux-musl` for alpine. Can you take care of it ? Thanks!
