### ISSUE TITLE
What minimal  depends vscode need? About port vscode to riscv64

### ISSUE THREAD

**Issue by luyahan** [microsoft/vscode#133951]
Hi all
I am maintaining v8 and nodejs on riscv64. So i want to know how to port vscode into riscv64.
What Minimal  depends vscode need other than nodejs?

**Comment by IllusionMH** [comment]
It's built on top of Electron so it's Chromium (in addition to Node.js) at least.

**Comment by luyahan** [comment]
> It's built on top of Electron so it's Chromium (in addition to Node.js) at least.

chrom can build successly by opensuse
https://github.com/riscv-collab/v8/issues/509#issuecomment-928903282
we run it on D1 by openeulr

**Comment by luyahan** [comment]
```
error /home/luyahan/vscode/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /home/luyahan/vscode/node_modules/vscode-ripgrep
Output:
Finding release for v13.0.0-1
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-1
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 403
    at ClientRequest.<anonymous> (/home/luyahan/vscode/node_modules/vscode-ripgrep/lib/download.js:143:24)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:394:28)
```
Absencing vscode-ripgrep riscv64,  so we can skip it or can i manually build?

**Comment by joaomoreno** [comment]
Ripgrep is only used for search, so feel free to skip it for now. I suggest you focus on porting Electron first. That's going to be your main fish.
