### ISSUE TITLE
Terminals don't use full width of panel

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133967]
Testing #133550

* have an output channel with scrollbar -> the scrollbar is all the right of its container
* have a terminal with scrollbar -> there is a gap between the scrollbar and its container

| gap | perfect alignment|
|---|---|
| <img width="629" alt="Screen Shot 2021-09-28 at 10 58 02" src="https://user-images.githubusercontent.com/1794099/135056896-e5cd6992-2a30-4a51-bd6c-eec791429de8.png"> |<img width="617" alt="Screen Shot 2021-09-28 at 10 57 55" src="https://user-images.githubusercontent.com/1794099/135056936-6754c03a-8cb4-4bb3-9a46-74cce239ca34.png"> |

**Comment by meganrogge** [comment]
Looks fixed to me

<img width="1392" alt="Screenshot 2023-11-10 at 10 59 14 AM" src="https://github.com/microsoft/vscode/assets/29464607/aa737470-4134-41bc-806b-6178cdc24b30">
