### ISSUE TITLE
No preselection in this case

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133978]
Testing #133907

* ~~have `"editor.suggestSelection": "first"`~~ (doesnt make a difference)
* use https://marketplace.visualstudio.com/items?itemName=ipatalas.vscode-postfix-ts
* type `console.`
* :confused: notice how 'cast' is selected, not 'error'

<img width="886" alt="Screen Shot 2021-09-28 at 12 10 26" src="https://user-images.githubusercontent.com/1794099/135067890-6dd012c9-470b-42c2-aa91-382e44d76be4.png">

**Comment by kimadeline** [comment]
Verified using VS Code 1.61.0-insider (commit c9e8266), don't mind `log` being highlighted that's just where my cursor was:


https://user-images.githubusercontent.com/51720070/135689728-c304631a-a022-45a4-8a3c-ff6e5bec1a68.mp4
