### ISSUE TITLE
List the possible targets

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133954]
Testing #133868

On https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions I see no list of the targets other than Windows.

**Comment by isidorn** [comment]
We have this section.
Would you prefer if it was a bulleted list to make it more prominent?

![Screenshot 2021-09-28 at 10 28 34](https://user-images.githubusercontent.com/1926584/135051882-8a96fce7-7f24-4e84-a4a4-2abd5a971c8b.png)

**Comment by bpasero** [comment]
Oh I see, I wasn't reading that part but focused on the `--target` example.

**Comment by isidorn** [comment]
Ok, not plan to change. If more people provide the same feedback I am open to make it a bulleted list. Thanks!
