### ISSUE TITLE
Notebooks - Outputs in Diff View Disappearing

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#133928]
- VS Code Version: 1.61.-insider
- OS Version: Windows

When looking at a diff view, out of nowhere two outputs (tables) disappeared from the view.

**Comment by rebornix** [comment]
@claudiaregio any detailed reproduce steps?

**Comment by claudiaregio** [comment]
Unfortunately no :( Was just scrolling through notebook and then poof outputs gone :'(

**Comment by claudiaregio** [comment]
For clarity, it wasn't all outputs it was one output I was looking at

**Comment by greazer** [comment]
I'm seeing this exact problem with today's insiders build (11/10/2021).

**Comment by greazer** [comment]
Marking as important as the diff blocks are literally made blank. I know you need a repro, but it seems like just something related to timing.
