### ISSUE TITLE
context menu to toggle fixed width not displayed for single terminal tab

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#133988]
Testing #133550

When the terminal is in the panel, the context menu to toggle fixed width is not displayed:
![image](https://user-images.githubusercontent.com/1704059/135081457-c06c2bbb-9d5e-42e7-9f04-0175e7683070.png)

The keyboard shortcut Alt-Z works though (sometimes anyway).

Once I move the terminal into the editor area, the context menu command is displayed:

![image](https://user-images.githubusercontent.com/1704059/135081603-941b6ccf-fa7c-4ab3-a608-5445f7f8a37d.png)

**Comment by meganrogge** [comment]
good catch - missed that in the single terminal tab context menu. you'll see it in the tab context menu if you have more than one terminal
