### ISSUE TITLE
compare can't show file as GB2312

### ISSUE THREAD

**Issue by eelyaj** [Microsoft/vscode#13390]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. add user setting "files.encoding": "GB2312", then open C file
2. modify C file
3. in GIT tab, It shows 1 change, click the item
4. the left windows does not open as GB2312

**Comment by joaomoreno** [comment]
#16071
