### ISSUE TITLE
Search is not showing the top entries

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#133946]
Testing #133775

- Start searching by typing `css lint`
🐛 Top entries are not revealed. Last entries are shown by default

![recording](https://user-images.githubusercontent.com/10746682/135041443-d7562652-877c-4947-b53b-16e38eb81c58.gif)

**Comment by rzhao271** [comment]
I can't repro the issue on Windows or Mac (Big Sur). Does the problem persist after a reload?

**Comment by DavidKutu** [comment]
I can repro this on windows

**Comment by DavidKutu** [comment]
reloading fixes it temporarily, it comes back if I search for something else and then search for `css lint` again

**Comment by rzhao271** [comment]
I can repro the issue if I scroll down a bit first
