### ISSUE TITLE
Shorten file path of files with same name

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#13398]
- VSCode Version: 1.5.3
- OS Version: Windows 10

Hi,

Steps to Reproduce:

1. For example I have 2 files with same name but in different folders:
  - C:\Users\a\foo\test\a.txt
  - C:\Users\a\bar\test\a.txt
2. Open them.
3. ![vsc](https://cloud.githubusercontent.com/assets/21136418/19220673/12d3c35a-8e5d-11e6-9fa4-6a7f66b22b7e.png)

So I have 2 suggestions:

1. Would you please add option to shorten file paths so that they will be shown like this?

  - foo\test
  - bar\test

2. Would you add option to shorten file path if it's too long, like 300 pixels? For example, you can use the ellipsize character `…`.

It would help a lot, since my project is located in a deep sub folder. Showing full paths will take a lot of space.

Thank you,

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12040
