### ISSUE TITLE
Editor inputs marked as deleted for virtual resources

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#133947]
When starting VS Code web on a folder on a contributed file system provider, there seems to be a timing issue.

- The dev console says as the first thing:
` WARN Ignoring the error while validating workspace folder vscode-test-web://mount/ - No file system provider found for resource 'vscode-test-web://mount/'
`
- the explorer first shows a missing root
- opening an editor from a a `*` activated extension first fails as well.
- later the explorer refreshes, but shows the resource that was opened as editor as missing
![image](https://user-images.githubusercontent.com/6461412/135046360-609b450f-c276-4011-a62e-e94036e7ce1f.png)

![image](https://user-images.githubusercontent.com/6461412/135046334-0e357172-854e-46c2-ae7e-8acf6be6d5c8.png)

To reproduce:
- clone https://github.com/aeschli/ext-web-issue-133947
- `npm i` && `npm run run-in-browser`
- in the browser that opens, no editor is opened, and `extension.ts` has a strikethrough.
- check the dev tools to see the errors as described above
 
`ext-web-issue-133947` is a new web extension created with `yo code` with the following changes
   - activates on '*'
   - opens an editor on `extension.ts`
- the `run-in-browser` script opens VS Code in the web on the `src/web` folder. Internally it adds an fsprovider extension that provides a file system service at `vscode-test-web` where it serves the contents from `src/web`.
Code for the fsprovider can be found here: https://github.com/microsoft/vscode-test-web/tree/main/fs-provider

**Comment by bpasero** [comment]
The problem here is that I report the decoration happily but forgot to clear it up when the model is disposed 👍

**Comment by aeschli** [comment]
Verified that the deleted annotation is no longer showing.

The editor doesn't open as the fs provider doesn't seem to be found yet. I'll file a new issue for that.
