### ISSUE TITLE
The window does not respond every few minutes

### ISSUE THREAD

**Issue by w567675** [Microsoft/vscode#13392]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide additonal information. What extensions do you have installed. Check out other issues which have similar sympotms and see if your issue is a duplicate.

**Comment by isidorn** [comment]
Closing this issue until more data is provided.
Thank you for the understanding
