### ISSUE TITLE
Terminal context menu does not display consistently

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#133992]
Testing #133550

When I create a new terminal and right click inside the terminal when it has focus, I do not see a context menu.

If I then right click on the terminal tab, I see a context menu. Then if I right click inside the terminal I now see a context menu.

But then if the terminal loses focus I do not see the context menu again unless I right click on the terminal tab once again.

**Comment by meganrogge** [comment]
This is as designed - we display this option in the tab menu, not the instance menu
