### ISSUE TITLE
Test: Run By Line in Jupyter notebooks

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#133903]
Refs: https://github.com/microsoft/vscode-jupyter/issues/5607

- [x] macOS @isidorn
- [x] linux @gregvanl
- [x] windows @bamurtaugh

Complexity: 3

Authors: @roblourens, @DavidKutu

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F133903&assignees=roblourens,DavidKutu)

---
### Setup

- Use VS Code Insiders and the latest jupyter and python extensions
- Make sure that you have python 3.7 or greater installed and on your path as python3 or python
- Set up a python virtualenv:

```
mkdir jupyter-dbg
cd jupyter-dbg
python3 -m venv ipykernel-env
```
- Activate the virtual environment

Mac/Linux:
```
source ipykernel-env/bin/activate
```

Windows:
```
ipykernel-env\Scripts\activate.bat
```

- Install the latest version of ipykernel in the virtual environment, which has debugging support
```
pip install ipykernel
python3 -m ipykernel install --user
```
- Open a .ipynb notebook file (You can use [this one](https://github.com/claudiaregio/data-science/blob/main/Titanic.ipynb) if you need one)
- Pick the kernel from your virtual env
- Set `"jupyter.logging.level": "verbose"`

### Testing

- Click the RBL button
![image](https://user-images.githubusercontent.com/20347396/134989595-06f89243-aff4-4d1e-8e46-888cc0bcff53.png)
- It should stop execution on the first code line, the RBL button should change to `Run Next Line`, and another button called `Continue Execution` should appear next to it
![image](https://user-images.githubusercontent.com/20347396/134989346-28d770f8-8a96-4670-a34e-86106b58ca1f.png)
- Clicking `Run Next Line` should step into the next line, stepping into functions defined in the same cell, but not stepping into anything else (functions in other cells, other python files, other python packages, etc.)
- Clicking `Continue Execution` should stop RBL, and continue executing the cell where it left off
- Interrupting or Restarting the kernel should also stop RBL

### More Testing

- Use the cell toolbar on both positions, check that the Run by Line button doesn't move when you press it
- Check on the panel, that `Jupyter: Variables` comes up and that your variables get updated after each step
- Try using it only with the key bindings (each button shows how to do it)

### Filing issues
File issues on the jupyter repo using the link above. **Include the log from the Jupyter output channel**

### Known Issues

- Pop up appears after clicking RBL immediately after `Run All` (https://github.com/microsoft/vscode-jupyter/issues/7638). If you repro, please add logs, environment and repro steps (if they are different)
- Can't check for ipykernel 6 on remote (https://github.com/microsoft/vscode-jupyter/issues/7576)
- If you delete a cell (and then bring it back with `ctrl + z`) while its running, it thinks its still running

**Comment by bamurtaugh** [comment]
Any ideas why I get this prompt when I click the RBL button?

![image](https://user-images.githubusercontent.com/25310137/135133079-5b11c75c-b392-4560-8e93-2b5b747e6cb2.png)

I followed the setup described here and got confirmation `Installed kernelspec python3 in < User directory >` after running `python -m ipykernel install --user`. 

Selected the Python 3.9.7 kernel:

![image](https://user-images.githubusercontent.com/25310137/135134267-df7a710d-8950-40fb-b3c0-ba1213acce3e.png)

Attached Jupyter logs in case they're useful, otherwise wondering if I'm selecting an incorrect option or missing a common step? [Jupyter9-28.txt](https://github.com/microsoft/vscode/files/7246155/Jupyter9-28.txt)

**Comment by roblourens** [comment]
Do you have the python extension installed?

**Comment by bamurtaugh** [comment]
Yes - `v2021.9.1246542782`.

**Comment by roblourens** [comment]
Can you check that you got the latest version of the jupyter extension and don't have a reload pending, and give me a call if so?

**Comment by DavidKutu** [comment]
what version of ipykernel comes up if you run `pip show ipykernel`?

**Comment by bamurtaugh** [comment]
> Can you check that you got the latest version of the jupyter extension

I have Jupyter extension `v2021.9.1001281857` - I actually reinstalled it and reloaded before starting this TPI to make sure I would have the latest.

> what version of ipykernel comes up if you run pip show ipykernel?

Version: 5.5.5 shows up. Seems like that's likely the issue based on the [troubleshooting](https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks#troubleshooting): `Ensure that ipykernel version 6.0 or greater is installed in the environment you're using for your notebook.`

Any thoughts why I'd have the wrong version even after following the steps above?

**Comment by bamurtaugh** [comment]
Although I previously ran `pip install -U ipykernel` based on the troubleshooting guide, I ran `pip3 install -U ipykernel` since I figured maybe it was a pip versus pip3 issue, reloaded, and now I have Version: 6.4.1 and it seems to be working. Thanks for the help!

**Comment by gregvanl** [comment]
Seeing the same error as Brigit when I try to use Run By Line "Ipykernel setup required for this feature".
I got past that by doing a Run All, which prompted me to install ipykernel and something else (forgot what it was).
Now I'm hitting "ModuleNotFoundError" on `import pandas as pd`.
Is there another step to install or point to the import dependencies?

**Comment by roblourens** [comment]
If you are using that Titanic.ipynb, you can install deps from the yml like `conda env create -f golden_scenario_env.yml`. If you have issues with that you could write some cells that don't have deps (`a=123`, `print(a)` etc)
