### ISSUE TITLE
bracket pair colorization slow to start, fast once it is running

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#133921]
```
Version: 1.61.0-insider (user setup)
Commit: 5991e3c4b97eca5568069bf3e0910ab693ad3549
Date: 2021-09-27T05:16:11.989Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

open a really big file, i use TypeScript's `src/compiler/checker.ts`
right click on the checker.ts editor tab, choose `Split in Group` so you have two views onto the file
Scroll to the bottom on one of them so you can see the closing bracket

Now, change/edit the opening bracket on line 2

expect that the closing bracket at end of file will immediately change, but it doesn't. 

![image](https://user-images.githubusercontent.com/1487073/135005276-7317e427-d80c-4072-9b19-628b298166a8.png)

If i keep making edits, it doesn't change color. 

If i then leave it alone for a few seconds (not sure how long), then the colorization starts to work. Once it starts, its instant, its just the first time.

**Comment by hediet** [comment]
Bracket pair colorization is always fast ;) Try inserting `{{{` (or more) to see that it updates immediately, even in the first couple of seconds.

The thing is that there are no token information available during the first couple of seconds (on my machine up to 15 seconds).
The bracket pair colorization feature does its best and just interprets every bracket-character as bracket (even in strings and comments).

Unfortunately, in checker.ts, there are some unpaired `"("`, `")"` and `"}"`.
Thus, the initial pair tree is unbalanced and probably overclosed (until it reprocesses the document when all token information are available).

When adding `{` to the beginning of the file, it (most likely; the file is too large for me to do bracket counting myself) closes some unopened `"}"` - thus, the change is not reflected at the end.
