### ISSUE TITLE
Test Autocomplete Preselection Powered By Inline Suggestions

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#133907]
Refs: https://github.com/microsoft/vscode/issues/131940

- [x] anyOS @TylerLeonhardt
- [x] anyOS @jrieken

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133907%0A%0A&assignees=hediet)

---

# Preparation

* Enable suggest preview: `"editor.suggest.preview": true,`.
* Install Copilot

# Tasks

* Create a TypeScript file and write `// Write an error to the console` followed by a new line and `console` to prompt copilot.
* Type `.` to trigger autocomplete.
* Verify that autocomplete shows, but the inline suggestion stays and the non-autocomplete part becomes non-italic
* Verify that an autocomplete item is preselected that is a prefix of the inline suggestion
* Verify that the selected autocomplete item is shown in italic font.

**Comment by TylerLeonhardt** [comment]
I really like the improvements in this space :) it's really looking nice!
