### ISSUE TITLE
unable to open `filename.js`: Model is disposed!

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#133923]
```
Version: 1.61.0-insider (user setup)
Commit: 5991e3c4b97eca5568069bf3e0910ab693ad3549
Date: 2021-09-27T05:16:11.989Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

I have inlayHints turned on for TypeScript, as well as bracket pair and guide colorization.

I was searching through a number of files, clicking on each one pretty quickly, and then at some point I started getting an error `Unable to open file `<filename>`: Model is disposed!`.   

clone the TypeScript repository
set the following settings:

``` json
    "editor.bracketPairColorization.enabled": true,
    "editor.guides.bracketPairs": true,
    "editor.inlayHints.enabled": true,
    "typescript.inlayHints.variableTypes.enabled": true,
    "typescript.inlayHints.enumMemberValues.enabled": true,
    "typescript.inlayHints.parameterTypes.enabled": true,
    "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
```

In the Search View, look for `const enum` (this is the exact query i was using)
Now pretty rapidly start clicking on files in the search results pane
Eventually (after clicking on like 15 to 20 files), especially after opening something large like `tsc.js`, you'll get the Model is disposed error.

![image](https://user-images.githubusercontent.com/1487073/135006625-ff697b38-47ec-4ab2-b101-8207dd4f9d39.png)

When I checked the console for errors, I found this stack trace that referenced `bracketMatching.ts` a few times, so I'm not sure if its related or coincidence.

![image](https://user-images.githubusercontent.com/1487073/135005942-d98c0e7d-4910-4972-a240-7f154c1d4907.png)

also saw this call stack

![image](https://user-images.githubusercontent.com/1487073/135006784-0188a911-136c-48e9-be98-acad7445e9fa.png)

**Comment by alexdima** [comment]
@hediet I can reproduce. I think the root cause is the `Maximum call stack size exceeded` error. I can reproduce with the above settings when trying to open https://github.com/microsoft/TypeScript/blob/main/lib/fr/diagnosticMessages.generated.json
