### ISSUE TITLE
vscode.executeDefinitionProvider and vscode.executeDocumentSymbolProvider not working without hacks

### ISSUE THREAD

**Issue by DarkTrick** [microsoft/vscode#133952]
Issue Type: <b>Bug</b>

- create a python file with the following content: `def foo():\n  return 5;`
- create a test case with the following content:
```
// make sure python parsers are available
let ext = vscode.extensions.getExtension("ms-python.python");
assert.notStrictEqual (ext, undefined);
await ext?.activate ();
ext = vscode.extensions.getExtension("ms-python.vscode-pylance");
assert.notStrictEqual (ext, undefined);
await ext?.activate ();

let doc = await vscode.workspace.openTextDocument(<PATH_TO_A_PYTHON_FILE>);
let pos = new vscode.Position(0, 5);
let documentSymbols = await vscode.commands.executeCommand<vscode.DocumentSymbol[]> (
          "vscode.executeDocumentSymbolProvider", doc.uri);
// alternatively run `vscode.executeDefinitionProvider` with a similar outcome.
```

- The `documentSymbols` at the end of the code will be undefined, because the parsers seem to not be loaded - even though, `activate()` is being called with `await`. 

The only workaround I've found was to add a `sleep(10000)` into `index.ts` and hope 10 seconds are long enough to actually activate the parsers.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.11.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1035)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|11.55GB (1.56GB free)|
|Process Argv|./ --crash-reporter-id cd2e28cc-66bd-460b-8ef3-8b6fb5f3c8bb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|6.0.1
vscode-eslint|dba|2.1.25
githistory|don|0.6.18
gitlens|eam|11.6.0
php-intellisense|fel|2.3.14
git-graph|mhu|1.30.0
mssql|ms-|1.10.1
python|ms-|2021.9.1246542782
vscode-pylance|ms-|2021.9.3
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
cpptools|ms-|1.6.0
debugger-for-chrome|msj|4.13.0
vscode-code-outline|pat|0.2.1
partial-diff|ryu|1.4.3
crs-al-language-extension|wal|1.4.11
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgst2:30361792

```

</details>

**Comment by jrieken** [comment]
There is no guarantee that activating an extension also registers all its language supports

**Comment by DarkTrick** [comment]
> /extPython

I wouldn't say this is specific to Python. Yes, the described case  is about Python, but the problem is global. If Python is able to not activate everything on `activate`, then any other extension can do the same. I'd say there should be a guaranteed way of fully activating extension *or* a way for a test suite to determine when the environment is fully loaded and ready.

> There is no guarantee that activating an extension also registers all its language supports

Perhaps it should? That leaves a developer no way of auto testing their dependent extensions (besides adding `sleep`s and hope for the best).
