### ISSUE TITLE
SCM - action button row selection

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#133983]
Testing #133913

Notice how the row that contains the action button gets selected. I do not believe that row should ever be selected.

![recording](https://user-images.githubusercontent.com/3372902/135077652-03e87073-6fcd-456f-907e-f58aeb9d3347.gif)

**Comment by eamodio** [comment]
@joaomoreno isn't the selection just the normal behavior of the tree/list? If that row has focus, then it displays that way -- same for the input box.

@joaomoreno How did you get that to happen?

**Comment by joaomoreno** [comment]
> @joaomoreno isn't the selection just the normal behavior of the tree/list? If that row has focus, then it displays that way -- same for the input box.

Definitely not the same for the input box. Not matter how hard you try, [you can't select the list element of the input box](https://github.com/microsoft/vscode/blob/8dae395177c5bb13bf5653950cbfee981b7a76d4/src/vs/workbench/contrib/scm/browser/scmViewPane.ts/#L2196-L2201).

> @joaomoreno How did you get that to happen?

1. Click on the empty space
2. 2x <kbd>Down Arrow</kbd>
3. <kbd>Spacebar</kbd>

**Comment by TarunavBA** [comment]
> Testing #133913
> 
> Notice how the row that contains the action button gets selected. I do not believe that row should ever be selected.
> 
> ![recording](https://user-images.githubusercontent.com/3372902/135077652-03e87073-6fcd-456f-907e-f58aeb9d3347.gif)

@lszomoru can u list ur extensions?

**Comment by lszomoru** [comment]
This has been fixed as part of polishing the action button.

**Comment by joyceerhl** [comment]
This is fixed but the left border outline for the action button is missing:

![image](https://user-images.githubusercontent.com/30305945/144500590-6880ce08-628d-401c-8e96-c0d7d739e85d.png)

**Comment by lszomoru** [comment]
@joyceerhl, I am unable to reproduce the issue :(

**Comment by joyceerhl** [comment]
🤔 seems fixed in latest insiders (all I did to encounter that bug yesterday was set my cursor to the scm input box, then hit tab to select the action button 
![image](https://user-images.githubusercontent.com/30305945/144639249-7122dd18-fa83-48a5-be4a-00866eb04c81.png)
