### ISSUE TITLE
Cannot install platform specific extension remotely

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#133989]
Testing #133868

Installing with the server startup works, but installing from the Extensions viewlet fails:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/9205389/135081541-4da2cdfb-161e-4890-bc65-db34ed65eba6.png">

The package.json does not contain a "kind". Repo: https://github.com/chrmarti/test-platform-specific-extensions

**Comment by chrmarti** [comment]
I should mention: This is on darwin x64 with an Alpine x64 container and the extension is published for alpine-x64.

**Comment by chrmarti** [comment]
Related: An extension without "kind" published for darwin-x64 installs locally and then stays disabled saying it is meant to run as a workspace extension. It does offer to "Install in dev container". Should the UI in this case refuse to install locally?
<img width="841" alt="image" src="https://user-images.githubusercontent.com/9205389/135086389-e2fa266b-093a-4a79-b500-1d234a1545e8.png">

**Comment by sandy081** [comment]
@chrmarti It works for me 

```
[2021-09-28 13:02:42.185] [remoteagent] [info] Installing extension: chrmarti.test-platform-specific-extensions
[2021-09-28 13:02:42.283] [remoteagent] [info] Downloaded extension: chrmarti.test-platform-specific-extensions /home/node/.vscode-server-insiders/extensionsCache/chrmarti.test-platform-specific-extensions-0.0.3-alpine-x64
[2021-09-28 13:02:42.299] [remoteagent] [info] Removed the extension from uninstalled list: chrmarti.test-platform-specific-extensions
[2021-09-28 13:02:42.301] [remoteagent] [info] Extension installed successfully: chrmarti.test-platform-specific-extensions
```

I am on darwin x64 with an Alpine x64 container. 

Do I miss any additional steps ?

**Comment by chrmarti** [comment]
@sandy081 I have rolled the extension back to the earlier state. Please try again. It still reproduces for me. I now also realize that it actually installed remotely, but there is also an error notification in the UI and an error in the renderer's log.

**Comment by chrmarti** [comment]
The error notification:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9205389/135094827-00d9bc8d-d97c-4d07-a514-546e5774076f.png">

**Comment by sandy081** [comment]
Ok, do you have settings sync on? Does it work when you disable settings sync or just install the extension without sync action?
