### ISSUE TITLE
An extra underline in js auto-complete

### ISSUE THREAD

**Issue by WWCong** [Microsoft/vscode#13397]
- VSCode Version: 1.5.3
- OS Version: win 10

Steps to Reproduce:

1. Create a new js file
2. Input "abc.__def" in first line
3. Input "__" (2 underlines) in the second line, the first one in auto-complete list will be "___def" (3 underlines)

**Comment by mrmlnc** [comment]
Also related to #4680.

**Comment by waderyan** [comment]
@WWCong thank you for opening this issue. Can you try with v1.6? This is fixed on my end for v1.6. Closing unless I hear from you it doesn't work. 

![image](https://cloud.githubusercontent.com/assets/2449568/19280114/35b962d4-8f99-11e6-9d05-802bf41f7531.png)
