### ISSUE TITLE
Terminal tab title default value/behaviour

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#133999]
Testing #133549

The default value of the setting is `${process}` but I have noticed that as I change the `cwd`, it is also being added to the title. Is that expected behaviour? I would have expected to see the `cwd` in the title only if the setting contains `${cwd}`.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/3372902/135086512-fd5782cc-dbd9-49d7-a3f3-08819a3ed738.png">

**Comment by meganrogge** [comment]
the single tab view shows title - description and by default, that's process - cwd
