### ISSUE TITLE
how to manually provide github token

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#133948]
There used to be a fallback if github auth redirect URI does not work to manually paste token using the status bar. But now it does not seem to work anymore.

It seem to be removed here: https://github.com/microsoft/vscode/commit/520fa49e68f111c95ee546417d707186668ba9ab#diff-0110ca081691d183b866f6d246ecad2fe43a906bf21e56d472597f16456a6e1aL206-L210

cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
Yes this was intentionally removed because Settings Sync no longer supports using GitHub PATs for logging in and it would be confusing if you could still specify a PAT but it didn't work with Settings Sync.

Do you have an issue on why github auth redirect isn't working for you?

**Comment by akosyakov** [comment]
ok, thanks for the explanation. 

Code was a bit confusing. I think the manual token event emitter still there but it does not look it is used anymore. Was not sure whether it was an overlook.

**Comment by TylerLeonhardt** [comment]
This is because it's still used in certain cases when running out of sources but it still has that limitation of being able unable to use Settings Sync with it.
