### ISSUE TITLE
Order of panels

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133959]
I think the "Terminal" was always last, no? With a fresh install I see "Terminal" only being second last:

![image](https://user-images.githubusercontent.com/900690/135055154-0bfe8fa8-5752-45c6-8bc8-624592bc150c.png)

//cc @Tyriar

**Comment by sbatten** [comment]
This does not look like a regression as I can repro in stable. In fact, it looks like the order for debug console was removed way back here https://github.com/microsoft/vscode/commit/570f46ddf20435e894e5cbd485caadd34c6d3b13 ... I believe we can safely re-add it @sandy081 ?

**Comment by sandy081** [comment]
Yes we can add it back - I think that was unintentional and got slipped some how. Please feel free to add it back.

**Comment by sbatten** [comment]
To Verify: 

1. run `code-insiders --user-data-dir <path-to-new-folder>`
2. Verify panel tab order: **Problems, Output, Debug Console, Terminal**
