### ISSUE TITLE
View port wrong

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133962]
Testing #133550

~~Sorry, no good steps yet but after toggling content width a couple I time I ended up with frozen view port dimensions, esp vertically~~

* open a terminal
* type `ls -la`
* toggle wrapping a few times and repeat the `ls -la` command
* :bug: size goes off

https://user-images.githubusercontent.com/1794099/135058934-5ff6a37a-d843-4e66-923a-130c3ace85fc.mov

**Comment by meganrogge** [comment]
not sure what you're showing there. toggling back and forth works fine for me

**Comment by meganrogge** [comment]
oh I see what's happening - it's scooting upward - think I know what's going on here

**Comment by jrieken** [comment]
I still see this or something very similar. I toggle fixed size twice the terminal jumps up a bit. Also, there is no more vertical scrollbar and the horizontal scrollbar is super wide (should only allow to scroll for a few pixels)

https://user-images.githubusercontent.com/1794099/135458536-b73288a3-1364-42af-affa-2c5f7fd9c72b.mov

**Comment by jrieken** [comment]
still seeing this
