### ISSUE TITLE
Aggressive collapsing in TOC

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#133945]
Testing #133775

- Select CSS section from TOC
- Scroll up a bit
- Extensions entry in TOC is collapsed

![recording (1)](https://user-images.githubusercontent.com/10746682/135040916-335b4953-55df-44b3-8d84-906d5c0cc6a9.gif)

**Comment by rzhao271** [comment]
I notice there's the same behaviour in Stable. It'll be more noticeable now due to extensions having their own categories.

**Comment by rzhao271** [comment]
Marking as out of scope for now
