### ISSUE TITLE
Notebooks - Diff view has different indicators based on mimetype selected

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#133931]
- VS Code Version: 1.61.0-insider
- OS Version: Windows

Steps to Reproduce:

1. Open diff view 
2. Find table output - no diff indicated
3. Change left side mimetype to text - diff indicated
4. Change right side mimetype to text - diff indicated

I was not expecting changing the mimetype in step 3 would have changed the visual indicators...after some thought I could maybe understand it? However after both mimetypes are changed (step 4), I thought the visual indicators would go away and match the original but they remained. 

![image](https://user-images.githubusercontent.com/19276747/135017156-9ea5b214-7fbb-477e-98e2-7b401973a5d6.png)
![image](https://user-images.githubusercontent.com/19276747/135017171-ad428794-6419-441c-a0bf-000467d7e5ac.png)
![image](https://user-images.githubusercontent.com/19276747/135017188-f2caa3b6-0635-4dfc-838e-4aaa8cddb824.png)

**Comment by rebornix** [comment]
@claudiaregio can you please share the modified document which you always reproduce the bug?

**Comment by rebornix** [comment]
Fixed via 6f9e39711d663877986bd8050500333b00a82f20
