### ISSUE TITLE
Terminal revive: bad contrast for restore message

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#133966]
Testing #133516

Using Default Light theme:

![image](https://user-images.githubusercontent.com/900690/135056666-ad649573-9fd5-4586-a7e2-27b18da474ae.png)

I doubt this matches our contrast ratio.

//cc @misolori

**Comment by misolori** [comment]
This actually does pass the color contrast ratio:

<img width="402" alt="CleanShot 2021-09-28 at 14 49 42@2x" src="https://user-images.githubusercontent.com/35271042/135170541-ef1ce683-1642-4605-9248-b1c4890f775e.png">

But I think it does feel a bit heavy so going with a lighter bg could be beneficial here. @meganrogge can we use [252](https://github.com/microsoft/vscode/issues/133496#issuecomment-923890191) for the bg?

![image](https://user-images.githubusercontent.com/35271042/135171671-0e4534b7-e3f7-4f11-a5bb-f25978d50cc0.png)
