### ISSUE TITLE
Bad wording/casing of command title

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#133960]
Testing #133550

Without reading the TPI I would have not understood what this means: "Toggle size to content width". Do I toggle the size or what? How about "Fixed Content Width" and a check mark that represents on/off. IMO a check mark will help a lot since there is no immediate effect when toggling the mode (e.g existing lines don't get re-rendered)

<img width="424" alt="Screen Shot 2021-09-28 at 10 43 55" src="https://user-images.githubusercontent.com/1794099/135054538-36a48c95-af87-4d05-9fbe-240c519c1cb4.png">

**Comment by meganrogge** [comment]
@jrieken we tried using the `toggled` property and couldn't get it to show up in the context menu

**Comment by jrieken** [comment]
> @jrieken we tried using the toggled property and couldn't get it to show up in the context menu.

Details? This is working well in many other places

**Comment by TarunavBA** [comment]
> Testing #133550
> 
> Without reading the TPI I would have not understood what this means: "Toggle size to content width". Do I toggle the size or what? How about "Fixed Content Width" and a check mark that represents on/off. IMO a check mark will help a lot since there is no immediate effect when toggling the mode (e.g existing lines don't get re-rendered)
> 
> <img alt="Screen Shot 2021-09-28 at 10 43 55" width="424" src="https://user-images.githubusercontent.com/1794099/135054538-36a48c95-af87-4d05-9fbe-240c519c1cb4.png">

@jrieken what theme do u use ? Can you provide the name or json?

**Comment by jrieken** [comment]
It's Github Light Default at version 4.x (I didn't like the 5.x changes they made)

**Comment by TarunavBA** [comment]
> It's Github Light Default at version 4.x (I didn't like the 5.x changes they made). Also these tweaks
> 
> ```
> 	"workbench.colorCustomizations": {
> 		"sash.hoverBorder": "#5a505042",
> 		"statusBarItem.remoteBackground": "#00000000",
> 		"statusBarItem.remoteForeground": "#55810e",
> 		"list.focusOutline": "#00000000",
> 		"editorWhitespace.foreground": "#a8929256"
> 	},
> ```

@jrieken Thanks! I'll surely check it out! 🎉

**Comment by meganrogge** [comment]
@jrieken the checkmark doesn't show up
![recording (76)](https://user-images.githubusercontent.com/29464607/135279582-6a8c9274-bfb2-45d2-993b-5ea2bf6ccb78.gif)
ue

**Comment by jrieken** [comment]
I cannot help you, when you show me gifs :-) Do you already use `toggled`? Do you update the right context key service? Do you know how to debug these things? Do you know F1 > Inspect Context keys?

**Comment by meganrogge** [comment]
you'll see the code responsible for it in the window 

```
registerAction2(class extends Action2 {
		constructor() {
			super({
				id: TerminalCommandId.SizeToContentWidthInstance,
				title: terminalStrings.toggleSizeToContentWidth,
				f1: false,
				category,
				toggled: TerminalContextKeys.terminalHasFixedWidth,
				precondition: ContextKeyExpr.and(TerminalContextKeys.processSupported, TerminalContextKeys.focus)
			});
		}
		async run(accessor: ServicesAccessor) {
			return getSelectedInstances(accessor)?.[0].toggleSizeToContentWidth();
		}
	});
```

**Comment by meganrogge** [comment]
When I inspect that context key, it's value is correctly updating. I don't think this kind of menu supports the checkmark

**Comment by jrieken** [comment]
The menu does support it. I suspect that the `TerminalContextKeys.processSupported` is broken because from time to time I also see `Cmd+K` not clearing the terminal (and that command uses the same context key)

**Comment by jrieken** [comment]
Yeah, sorry hint. The precondition is never used for the check mark. It's only the toggled-condition, e.g `terminalHasFixedWidth`, and the context key inspector tells me its false no matter how often I toggle

**Comment by meganrogge** [comment]
in the run action when I log the value of that context key, it's correct. not sure why the value is false when you inspect it. 

https://github.com/microsoft/vscode/blob/246c663214aee34f0da6032d461b013381ba22c1/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1881-L1883

I know the context key is updating correctly because otherwise toggling wouldn't happen as you'll see here https://github.com/microsoft/vscode/blob/75e3411fd3a8197060db895d05cacace14768e4f/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1923-L1949

**Comment by meganrogge** [comment]
Also if I use a different context key - notFindVisible for instance - even when find isn't visible the checkmark isn't appearing.

**Comment by meganrogge** [comment]
reverting as it's more complicated than just using that context key since that is shared between instances. for now, we'll just keep toggle. I'll work on this next iteration.

**Comment by meganrogge** [comment]
started work on merogge/checkmark
