### ISSUE TITLE
SCM - sync changes button

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#133974]
Testing #133913

* Buttons contains unicode character

<img width="582" alt="image" src="https://user-images.githubusercontent.com/3372902/135061146-9e8b138f-11f1-4481-8d1e-22e8a1df05b5.png">

**Comment by aditya-giri** [comment]
I dropped a comment [here](https://github.com/microsoft/vscode/commit/51bd88d8f2b8b66869fe9d2698602008d1eec909#commitcomment-57169868) because I wasn't sure whether to create an issue.
