### ISSUE TITLE
Notebooks - Hard to see where one table starts/ends in diff view

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#133925]
- VS Code Version: 1.61.0-insider
- OS Version: Windows

When you open up a diff view and look at an output that is a table, it is a bit hard to see where one table ends and another starts. It is especially difficult if the horizontal scroll is out of sight on the screen

![image](https://user-images.githubusercontent.com/19276747/135011774-ce4bcaae-5da4-4676-a0dc-705628b0d1da.png)

I would hope to see the separation below a bit more clearly 

![image](https://user-images.githubusercontent.com/19276747/135011947-a6fffdc1-9bd3-4df6-a705-b68f37d2fc67.png)

**Comment by rebornix** [comment]
This is what you would see with tomorrow's Insiders

![image](https://user-images.githubusercontent.com/876920/136294476-d7398896-551a-4098-a52d-c6678b66ea64.png)
