### ISSUE TITLE
PHP TEXT multiple line syntax error

### ISSUE THREAD

**Issue by amnatn** [microsoft/vscode#133934]
Visual Code is not understand '<<<' in PHP language

<?php

$sql = <<<TEXT
SELECT $select
  FROM $table
  WHERE $where
  ORDER BY 1
TEXT; 

// syntax error : unexpected end of file
?>

![2021-09-28_11-23-15](https://user-images.githubusercontent.com/46020432/135023082-673c266d-471b-40cc-a7be-a32b091485d3.png)

**Comment by roblourens** [comment]
Are you using a PHP extension? If so please file on that extension. or is this coming from the builtin PHP support?

**Comment by amnatn** [comment]
PHP linter as following
[](url)https://code.visualstudio.com/Docs/languages/php

![2021-09-30_20-32-55](https://user-images.githubusercontent.com/46020432/135466690-1cc93312-9bf0-413a-a802-5812c81c87e9.png)


> Are you using a PHP extension? If so please file on that extension. or is this coming from the builtin PHP support?

**Comment by roblourens** [comment]
I can't repro. Can you try to narrow it down by checking different cases? Can you try starting vscode with the `--disable-extensions` flag?
