### ISSUE TITLE
Configured debug type 'extensionHost' is not supported.

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#13394]
- VSCode Version: code-oss-dev 1.7.0 (Commit unknown, Date unknown)
- OS Version: Darwin x64 16.1.0
- Extensions: 

As title described

**Comment by isidorn** [comment]
This is as designed, when you run vscode out of source the node debug is not packaged as an extension - it only gets packaged once you build the full vscode.
What you need to do is copy the node-debug from your vscode stable installation folder inside your user .vscode-oss-dev/extensions folder. That way the out of source vscode will pick up the built in node debug extension

**Comment by leaxoy** [comment]
oh thanks!!

**Comment by pflannery** [comment]
I have the same issue. 
The closest I find to a node-debug extension in the vscode stable installation folder is

```
<app path>\resources\app\extensions\ms-vscode.node-debug
<app path>\resources\app\extensions\ms-vscode.node-debug2
```

I coped these folders in to my `~/.vscode-oss-dev/extensions` folder and it removes the error but now I see this when trying to debug my extension

![image](https://cloud.githubusercontent.com/assets/1727302/20649970/7772480e-b4c3-11e6-953d-4098241c6ea1.png)

**Comment by pflannery** [comment]
just to add

```json
  windows 10 64 bit
  npm: 4.0.2,
  http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' 
```

**Comment by isidorn** [comment]
@pflannery in the 'launch.json' under `'args'` as the first argument of the array you should add a path to your vscode repository.
As to why this is exactly needed @weinand can clarify

![screen shot 2016-11-28 at 10 18 24](https://cloud.githubusercontent.com/assets/1926584/20662538/1276ef5e-b554-11e6-803e-a07af5d430f9.png)

**Comment by JonasT** [comment]
> This is as designed, when you run vscode out of source the node debug is not packaged as an extension - it only gets packaged once you build the full vscode.

So why can't there be some sort of better install script that actually installs node debug for the dev version too?

Also, if by stable version you happen to mean the one on the website, that one isn't free software (see #17996 ) which means being required to copy from it would imply the "Code - OSS Dev" free version actually doesn't properly work without copying from a proprietary software which is *somewhat suboptimal*.

**Comment by weinand** [comment]
@JonasT just checkout vscode-node-debug, do an `npm install` and a `gulp package`. Then side-load the resulting vsix into Code - OSS Dev.

**Comment by JonasT** [comment]
https://github.com/Microsoft/vscode-go/wiki/sideload Is this the sideload procedure I need to use? Ok, let me try whether that works..

As a note: from #12570 it sounds like this is no longer supposed to be necessary, or did I misunderstand that ticket? It would be neat if at some point an install script would automatically address this.

**Comment by JonasT** [comment]
Ok that worked, and after editing the launch args as in https://github.com/Microsoft/vscode/issues/13394#issuecomment-263220546 it launches VSCode for debugging - however, apparently not with the extension loaded which I want to debug :confused: (it's not listed in extensions in the inner instance - shouldn't it be?)

Also this whole process seems a bit complicated.. e.g. why do I need to edit the launch args, and does everyone else who wants to test it need to do it too? Should I remove the `.vscode/launch.json` from the repository so everyone can edit it without conflicts? I still don't really understand the intended workflow

**Comment by JonasT** [comment]
I run Code - OSS Dev because I'd rather have a free piece of software I can freely tinker with than this abomination of a license: https://code.visualstudio.com/License/ (pretty standard for proprietary software I'm aware, but that doesn't make it much better)

Why is debugging an extension not directly support from the free software of VS Code?

**Comment by weinand** [comment]
Because in the 'free' version of VS Code you are 'free' to decide what extensions you want to use. We do not want to force anybody to use the node debug extension (and we believe that the "Install from VSIX..." action makes it painless to include any extension you want to use).

**Comment by JonasT** [comment]
That does actually kind of make sense. Would I have needed to manually locate, download & build node-debug though? It would make sense to at least make that process a little easier since I imagine it's a common extension. (for example, by adding a list of commonly downloaded extensions right into VS Code where you can just click the name and it gets downloaded & installed)

Unless of course that's already inside and I was just needlessly taking the route with more effort :smile:

**Comment by weinand** [comment]
We are assuming that if you want to build 'Code - OSS Dev' yourself, then you probably want to build 'node-debug' yourself too.
If you need an easier route, just use the stable or Insider versions, they include the node debugger extension automatically.
