### ISSUE TITLE
Debug console completions sometimes do not work with debugging Jupyter cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#133930]
- Start debugging a notebook cell
- Type in the debug console
- Sometimes, completions do not appear

The debug console is sometimes not registering completion provider support here

https://github.com/microsoft/vscode/blob/16ab8be08ea224b26fe3eee6cd57b88aaa1fae31/src/vs/workbench/contrib/debug/browser/repl.ts#L153

although the flag on the session is set and everything else happens as expected

**Comment by roblourens** [comment]
Alternate non-notebook steps:

- Set `"debug.internalConsoleOptions": "neverOpen"`
- Reload the window and make sure the debug console has not yet been opened
- Start debugging javascript
- Type in debug console, get no completions

**Comment by sbatten** [comment]
This should not have changed recently to my knowledge.
