### ISSUE TITLE
Native Notebooks - Moving non-consecutive cells only moves the second

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#133915]
VS Code Version: 1.61.0 - insider
OS Version: Windows

Steps to Reproduce:

1. Open Notebook
2. Multiselect two cells that are not consecutive
3. Drag and drop cells 
4. Only the second gets moved

*Special Note: This issue does not occur if you multiselect cells that are consecutive

**Comment by roblourens** [comment]
This seems to be by design. That makes sense to me, it feels weird to move a non-consecutive multiselection and have those cells put next to each other. I don't think I would actually do that. But moving a chunk of cells next to each other makes more sense to me. Can revisit if you disagree.

**Comment by roblourens** [comment]
Actually, it might feel more weird that I have some cell selected that aren't affected by the drag. You can do this kind of thing in windows explorer, although it's different when order matters.

**Comment by roblourens** [comment]
Working on this, but the math is hard
