### ISSUE TITLE
Terminal writes over itself

### ISSUE THREAD

**Issue by SandPoot** [microsoft/vscode#133909]
Issue Type: <b>Bug</b>

The terminal is writing overitself.

VS Code version: Code - Insiders 1.61.0-insider (5991e3c4b97eca5568069bf3e0910ab693ad3549, 2021-09-27T05:16:11.989Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3503)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (15.95GB free)|
|Process Argv|-n C:\\Users\\enric\\AppData\\Local\\Temp\\vsliveshare\\tmp-EE78E504A877BCA208CCC7EC15CB56523A3F\\Visual Studio Live Share.code-workspace --crash-reporter-id 2b4ad6d6-399b-4305-8da9-96f879712950|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-markdownlint|Dav|0.44.3
vscode-tgstation-test-adapter|Don|1.1.1
gitlens|eam|11.6.0
byond-dm-language-support|gba|1.0.1
copilot|Git|1.4.2795
vscode-pull-request-github|Git|0.30.0
vscode-test-explorer|hbe|2.21.1
discord-vscode|icr|5.7.0
auto-comment-blocks|kev|1.0.1
vscode-gutter-preview|kis|0.27.1
git-graph|mhu|1.30.0
vscode-language-pack-pt-BR|MS-|1.61.0
jupyter|ms-|2021.9.1001277548
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.2
powershell-preview|ms-|2021.9.1
test-adapter-converter|ms-|0.1.2
vsliveshare|ms-|1.0.4836
indent-rainbow|ode|8.1.0
dm-langclient|pla|0.1.11
byond|ss1|1.1.0
auto-comment-blocks|sty|1.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedc:30350118
pythonvspyt187:30365360
pydsgst2:30361790

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

/gifPlease
