### ISSUE TITLE
能不能加上总是在前面的功能

### ISSUE THREAD

**Issue by qinfangge** [Microsoft/vscode#13393]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T08:50:42.185Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
2.

**Comment by octref** [comment]
This is an OS specific functionality that you can achieve with other programs. For example, [Helium](https://itunes.apple.com/us/app/helium/id1054607607?mt=12) for macOS.
