### ISSUE TITLE
Test: Drag and Drop across GitHub remote repositories

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#133922]
Refs: #133116

- [x] macOS @sana-ajani
- [x] windows @dbaeumer
- [x] linux @JacksonKearl

Complexity: 2

Authors: @sbatten, @bpasero 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23133922%0A%0A&assignees=sbatten,bpasero)

---

Known limitations to this experience:
1) It applies to drag and drop from explorer to explorer
2) The dropped version of the file will not have changes that are not checked in (no uncommitted changes will be imported on drop)

To improve drag and drop across different clients using remote repositories, we've opened up the ability to drag and drop files across windows which have the same virtual file system provider (and access).

This enables users to drag files between to github.dev windows or the desktop client if the remote repositories extension is installed and available.

To test, open various web and desktop clients signed in to github and drag and drop files between them.

**Comment by dbaeumer** [comment]
Works for me only in the following scenarios:

- desktop -> desktop
- web -> desktop

Doesn't work if the target is web

**Comment by JacksonKearl** [comment]
Works fine across desktop applications opening remotehub workspaces, but cant drag if Firefox is involved.
