### ISSUE TITLE
Missing release script

### ISSUE THREAD

**Issue by vicentedealencar** [Microsoft/vscode#134]
I was looking for your release script for reference, but all there is is a devDependency for [atom-shell-installer-assets](https://github.com/joaomoreno/atom-shell-installer-assets). You probably have a script using squirrel, that I was interested on.

Maybe you wont open source it, but why?

**Comment by bpasero** [comment]
@chrisdias please chime in

**Comment by joaomoreno** [comment]
Actually, thanks for this. We no longer use that package, since we moved to Inno Setup.

**Comment by timfish** [comment]
+1 for open sourcing the packaging scripts for all platforms.

Open sourcing the code for incremental build and debug of a Typescript Electron apps is awesome. It would be equally great to see which way you decided to do release builds!

**Comment by ironcladlou** [comment]
Maybe this was made clear somewhere I just failed to find in my searching, but how do I build the OS X app/distribution from source? All I can figure out how to do from the docs is launch a generic Electron instance using `scripts/code.sh`.

Semi related, I see a lot of references to an alpha version of the app. Is that public? Where can I find more details about it?

cc @lukehoban

**Comment by ironcladlou** [comment]
Just found https://github.com/Microsoft/vscode/issues/3793

**Comment by joaomoreno** [comment]
@chrisdias ping

**Comment by Tyriar** [comment]
I play on writing up on packaging in vscode in June, closing in favor of https://github.com/Microsoft/vscode/issues/6893
