### ISSUE TITLE
Unpublished branch could have better sync label than "Publish Changes"

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#134052]
Testing #133913

<img src=https://user-images.githubusercontent.com/8599/135154848-b639e826-c80b-4efe-b24d-384577183d46.png width=350>

In case of a freshly created unpublished branch "Publish Changes" doesn't make sense, but rather "Publish Branch"
 or sth similar.

**Comment by eamodio** [comment]
Instead of `Publish Changes` and `Sync Changes` what do you think of changing it to `Publish to <branch-name>` and `Sync ⟲ 5↓ 2↑ to <branch-name> `?

**Comment by lszomoru** [comment]
@misolori, any thoughts on this?

**Comment by misolori** [comment]
If we can change the title to "Publish Branch" for this specific state, that would be my preference as adding more text to the button would make it busier. GitHub Desktop does the same thing:

<img width="263" alt="CleanShot 2021-11-15 at 09 06 25@2x" src="https://user-images.githubusercontent.com/35271042/141823911-2d529b3d-f816-4de3-aa8a-fb78895d3e13.png">

**Comment by lszomoru** [comment]
I have updated the label/tooltip for the button the the status bar item - 56681eda57ae62cb3e90a06a7e7441ad3f1e3d23
 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/3372902/141996094-78163c57-fc27-468a-a99f-607e4672b10c.png">
