### ISSUE TITLE
Whenever I do any type of git operation I lose typescript intellisense

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/vscode#1340]
Visual Studio Code 0.10.3
Whenever I do any type of git operation I lose type script suggestions. 

It used to only happen when i move branches, but now even a commit makes me lose intellisense. Fiddling with the tsconfig.json brings it back sometimes. Other times the tsconfig.json is locked by VSCode. I know its VSCode because when I close the application the file becomes unlocked.

Also, tsconfig randomly gets deleted.

Reload window does not help. Restarting VSCode does not help. Restarting my pc does not help. Reinstalling the tsd does not help. Reinstalling code does not help.

My repository is here: https://github.com/tonyeung/angular-typescript-seed

**Comment by tonyeung** [comment]
https://github.com/Microsoft/vscode/issues/1342

**Comment by tonyeung** [comment]
@louy @gileze33 can you guys post your tsconfig? I think I know the cause.

**Comment by louy** [comment]
Hmm yeah.

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by tonyeung** [comment]
@louy  I cannot replicate the issue with your tsconfig.json. Do you have a link to your repository? Are you using tsd? if you are, did you keep the default settings? I was able to fix my issue when i stripped the tsconfig.json.compilerOptions down to just "target": "ES5"
```
{
	"compilerOptions": {
		"target": "ES5"
	},
	"exclude": [
		"node_modules",
		"bower_components"
	]
}
```

**Comment by louy** [comment]
hmm well. `"module": "commonjs",` is a must for us. I'll check if I have a public repo in which I can reproduce the issue. You might want to look at [opool](https://github.com/urbanmassage/opool) for now.

**Comment by tonyeung** [comment]
@louy sorry, I wasn't being clear. I meant you should try stripping it down to target:ES5 and see if it fixes it for you. It should help with narrowing down the issue.

**Comment by tonyeung** [comment]
I also tried the opool and the suggestions worked fine

**Comment by louy** [comment]
I'll try it tomorrow and let you know. Though my point was that if I remove `module: commonjs` the project won't work. Meaning that I can't publish it as an npm module.

**Comment by tonyeung** [comment]
@louy  yea, I understand. Hopefully stripping it down will narrow the problem so the devs can fix it. In the meantime, a work around might be to only add it when you need to compile, or pass your build tool a separate "tsconfig.json". Personally, I'd rather do that than see red squigglies everywhere

**Comment by gileze33** [comment]
(same team as @louy so same tsconfig)

I tend to see this the most when I have 2+ VSCode windows open with different projects

**Comment by tonyeung** [comment]
@gileze33  I see. Well, if you're encountering it now, you can try my workaround till we hear something from the devs.

**Comment by tonyeung** [comment]
seeing as how the other issue has dev involvement, i'm closing this issue.
