### ISSUE TITLE
When I want to enable https proxy, VSCode always pops up an error window

### ISSUE THREAD

**Issue by renfengyue** [microsoft/vscode#134082]
I have configured the https proxy in the setting window of VSCode, I then tried to enable the proxy by clicking the button at the bottom right corner of VSCode, and VSCode always pops up an error windows with the information "Running the contributed command:'extension.toggleProxy' fail."

**Comment by chrmarti** [comment]
'extension.toggleProxy' is not a built-in command. This must be caused by an extension, please file an issue for that.
