### ISSUE TITLE
Slow git with multiple repos makes startup very slow (or terminal is too slow?)

### ISSUE THREAD

**Issue by yajo** [microsoft/vscode#134096]
Here I'm attaching a performance report, although I guess the debug information won't be of much help because its output was produced before the actual problem happens.

The real problem is that, once vscode opens, it starts inspecting git repos one by one. If I have a lot of git repos, then the whole experience gets very slow. For example, look at how long it takes for the terminal to be usable:

https://user-images.githubusercontent.com/973709/135234272-330070ea-06e2-4fa4-98ab-88f13244986b.mp4

15 seconds until I can issue a command!

Seeing the video, my initial guess is that git extension is too slow to load repos info and thus makes everything else wait. When I have other extensions installed (video is recorded with `--disable-extensions`), this is even worse.

I think that the git extension should cache its results somewhere. When I switch workspace (which I do very often), it is always this slow. But the info that the extension will get from git is gonna be almost always the same, so why not cache it somewhere and start with the cached info, and then defer the cache updating until all UI is fully responsive?

## System Info

* Code: 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e)
* OS: linux(5.13.19-200.fc34.x86_64)
* CPUs: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz(12 x 3715)
* Memory(System): 15.46 GB(1.57GB free)
* Memory(Process): 286.00 MB working set(180.87MB private, 8.54MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 69       | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 58       | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 75       | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 0        | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 31       | [main]                    | initial startup: true, state: 0ms, widget: 28ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 182      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 149      | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 602      | [renderer]                | cached data: NO, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 28687    | [renderer]                | -                                                          |
| init workspace service                                          | 124      | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 1618     | [renderer]                | -                                                          |
| restore viewlet                                                 | 38       | [renderer]                | workbench.view.explorer                                    |
| restore panel                                                   | 25       | [renderer]                | terminal                                                   |
| restore & resolve visible editors                               | 477      | [renderer]                | 1: workbench.editors.files.fileEditorInput                 |
| overall workbench load                                          | 701      | [renderer]                | -                                                          |
| workbench ready                                                 | 30413    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 30020    | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 31784    | [renderer]                | -                                                          |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1632904726991	0	0
code/didStartMain	1632904727115	124	124
code/willStartCrashReporter	1632904727127	12	136
code/didStartCrashReporter	1632904727127	0	136
code/willGenerateNls	1632904727128	1	137
code/mainAppReady	1632904727184	56	193
code/didGenerateNls	1632904727186	2	195
code/willLoadMainBundle	1632904727186	0	195
code/fork/willLoadCode	1632904727197	11	206
code/registerFilesystem/file	1632904727258	61	267
code/didLoadMainBundle	1632904727261	3	270
code/willStartMainServer	1632904727269	8	278
code/didStartMainServer	1632904727271	2	280
code/willCreateCodeWindow	1632904727330	59	339
code/willRestoreCodeWindowState	1632904727331	1	340
code/didRestoreCodeWindowState	1632904727331	0	340
code/willCreateCodeBrowserWindow	1632904727332	1	341
code/didCreateCodeBrowserWindow	1632904727360	28	369
code/didCreateCodeWindow	1632904727361	1	370
code/willOpenNewWindow	1632904727366	5	375
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1632904727367	0	0
code/didStartRenderer	1632904727508	141	141
code/willWaitForWindowConfig	1632904727508	0	141
code/didWaitForWindowConfig	1632904727508	0	141
code/willShowPartsSplash	1632904727508	0	141
code/didShowPartsSplash	1632904727509	1	142
code/willLoadWorkbenchMain	1632904727515	6	148
code/didLoadWorkbenchMain	1632904728117	602	750
code/registerFilesystem/file	1632904728120	3	753
code/registerFilesystem/vscode-userdata	1632904728120	0	753
code/willInitWorkspaceService	1632904728125	5	758
code/willInitStorage	1632904728126	1	759
code/didInitWorkspaceService	1632904728249	123	882
code/didInitStorage	1632904756813	28564	29446
code/willStartWorkbench	1632904756827	14	29460
code/LifecyclePhase/Ready	1632904756829	2	29462
code/registerFilesystem/trustedDomains	1632904756909	80	29542
code/willRestoreEditors	1632904757051	142	29684
code/willRestoreViewlet	1632904757058	7	29691
code/willRestorePanel	1632904757072	14	29705
code/didRestoreViewlet	1632904757096	24	29729
code/didRestorePanel	1632904757097	1	29730
code/willResolveExplorer	1632904757204	107	29837
code/willLoadExtensions	1632904757281	77	29914
code/didRestoreEditors	1632904757528	247	30161
code/LifecyclePhase/Restored	1632904757528	0	30161
code/didStartWorkbench	1632904757528	0	30161
code/didRemovePartsSplash	1632904757529	1	30162
code/willConnectSharedProcess	1632904757629	100	30262
code/willHandleExtensionPoints	1632904758679	1050	31312
code/didHandleExtensionPoints	1632904758895	216	31528
code/didLoadExtensions	1632904758899	4	31532
```

### cached data created (lazy, might need refreshes)

---
[prof-1e32.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/7250291/prof-1e32.main.cpuprofile.txt)
[prof-1e32.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/7250294/prof-1e32.renderer.cpuprofile.txt)

**Comment by eamodio** [comment]
@Tyriar Do you have any idea while the terminal would be so impacted here?

**Comment by Yajo** [comment]
FTR the problem isn't just the terminal. There are many operations that are slowed down. The terminal is like the most obvious one, because it's where I go when vscode gets slow.

I was wondering if a normal project with just 1 git repo would make terminal get that slow. Well, not *that* slow, but still slow:

```
❯ time code --disable-extensions --wait

________________________________________________________
Executed in    9,05 secs    fish           external
   usr time    9,85 secs  205,00 micros    9,85 secs
   sys time    5,88 secs   31,00 micros    5,88 secs
```

https://user-images.githubusercontent.com/973709/135402692-937663ff-abd9-4254-89d5-709f9b04c0ff.mp4

Before you ask, I tested switching to bash and the timings are equivalent.

**Comment by lszomoru** [comment]
@yajo, apologies for not getting back to you on this until now. Are you still able to reproduce this issue? Thanks!

**Comment by yajo** [comment]
No, the terminal is faster now, even when loading workspaces with many git repos. I don't know when it got fixed. Thanks anyway!
