### ISSUE TITLE
函数提示功能没了

### ISSUE THREAD

**Issue by julice** [microsoft/vscode#134092]
Issue Type: <b>Bug</b>

之前有函数提示的，现在没有了，就很奇怪。

VS Code version: Code 1.60.2 (Universal) (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id b6d64d43-a0db-48b3-b411-547ea8ca2718|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.4.0
simple-react-snippets|bur|1.2.4
wechat-snippet|Cha|0.4.11
npm-intellisense|chr|1.4.0
path-intellisense|chr|2.4.0
vscode-wxml|cod|0.1.9
jshint|dba|0.11.0
vscode-eslint|dba|2.1.25
app-migrator|deb|0.0.6
react-redux-react-router-snippets|dis|0.4.29
githistory|don|0.6.18
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.6.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.22
we-app-vscode|eme|0.8.0
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.0.0
auto-close-tag|for|0.5.12
code-runner|for|0.11.5
leek-fund|gis|1.9.9
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.5.0
react-component|jer|1.0.4
sftp|lix|1.12.9
vscode-language-babel|mgm|0.0.35
vscode-language-pack-zh-hans|MS-|1.60.4
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
vscode-typescript-next|ms-|4.5.20210928
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.7.0
vetur|oct|0.34.1
vuehelper|oys|0.1.0
vscode-css-peek|pra|4.2.0
minapp-vscode|qiu|2.3.4
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
rocketseatreactnative|roc|3.0.1
vue-helper|she|2.4.7
js-jsx-snippets|sky|10.2.0
react-redux-es6-snippets|tim|2.1.0
vscode-icons|vsc|11.6.0
full-react-snippets|wal|1.4.2
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthrucf:30370837
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vssbtest:30374703

```

</details>

**Comment by CodeCrazy-ywt** [comment]
> 
> Issue Type: <b>Bug</b>
> 
> 之前有函数提示的，现在没有了，就很奇怪。
> 
> VS Code version: Code 1.60.2 (Universal) (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T11:59:27.195Z)
> OS version: Darwin x64 20.6.0
> Restricted Mode: No
> 
> <details>
> <summary>System Info</summary>
> 
> |Item|Value|
> |---|---|
> |CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
> |GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
> |Load (avg)|4, 4, 4|
> |Memory (System)|16.00GB (0.12GB free)|
> |Process Argv|--crash-reporter-id b6d64d43-a0db-48b3-b411-547ea8ca2718|
> |Screen Reader|no|
> |VM|0%|
> </details><details><summary>Extensions (50)</summary>
> 
> Extension|Author (truncated)|Version
> ---|---|---
> project-manager|ale|12.4.0
> simple-react-snippets|bur|1.2.4
> wechat-snippet|Cha|0.4.11
> npm-intellisense|chr|1.4.0
> path-intellisense|chr|2.4.0
> vscode-wxml|cod|0.1.9
> jshint|dba|0.11.0
> vscode-eslint|dba|2.1.25
> app-migrator|deb|0.0.6
> react-redux-react-router-snippets|dis|0.4.29
> githistory|don|0.6.18
> es7-react-js-snippets|dsz|3.1.1
> gitlens|eam|11.6.0
> EditorConfig|Edi|0.16.4
> vscode-npm-script|eg2|0.3.22
> we-app-vscode|eme|0.8.0
> react-native-react-redux|EQu|2.0.6
> prettier-vscode|esb|9.0.0
> auto-close-tag|for|0.5.12
> code-runner|for|0.11.5
> leek-fund|gis|1.9.9
> beautify|Hoo|1.5.0
> vscode-react-typescript|inf|1.3.1
> search-node-modules|jas|1.3.0
> react-vscode-extension-pack|jaw|0.5.0
> react-component|jer|1.0.4
> sftp|lix|1.12.9
> vscode-language-babel|mgm|0.0.35
> vscode-language-pack-zh-hans|MS-|1.60.4
> remote-ssh|ms-|0.65.8
> remote-ssh-edit|ms-|0.65.8
> vscode-typescript-next|ms-|4.5.20210928
> vscode-typescript-tslint-plugin|ms-|1.3.3
> debugger-for-chrome|msj|4.13.0
> vscode-react-native|msj|1.7.0
> vetur|oct|0.34.1
> vuehelper|oys|0.1.0
> vscode-css-peek|pra|4.2.0
> minapp-vscode|qiu|2.3.4
> typescript-hero|rbb|3.0.0
> LiveServer|rit|5.6.1
> rocketseatreactnative|roc|3.0.1
> vue-helper|she|2.4.7
> js-jsx-snippets|sky|10.2.0
> react-redux-es6-snippets|tim|2.1.0
> vscode-icons|vsc|11.6.0
> full-react-snippets|wal|1.4.2
> vscode-js-console-utils|wht|0.7.0
> JavaScriptSnippets|xab|1.8.0
> ReactSnippets|xab|2.4.0
> 
> 
> </details><details>
> <summary>A/B Experiments</summary>
> 
> ```
> vsliv368cf:30146710
> vsreu685:30147344
> python383:30185418
> pythonvspyt602:30300191
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> vstes627:30244334
> pythonvspyt639:30300192
> pythontb:30283811
> pythonvspyt551cf:30345471
> pythonptprofiler:30281270
> vshan820:30294714
> vstes263cf:30335440
> pythondataviewer:30285071
> pythonvsuse255:30340121
> vscod805:30301674
> pythonvspyt200:30340761
> binariesv615:30325510
> vsccppwt:30364497
> pythonvssor306:30344512
> bridge0708:30335490
> pygetstartedt2:30371810
> dockerwalkthrucf:30370837
> bridge0723:30353136
> pythonrunftest32:30373476
> pythonf5test824:30373475
> javagetstartedc:30364665
> pythonvspyt187:30373474
> pydsgst2:30361792
> vssbtest:30374703
> 
> ```
> 
> </details>
> 
> 

哪个语言？

**Comment by alexdima** [comment]
I'm sorry, we do not understand this language.

**Comment by CodeCrazy-ywt** [comment]
No, I'm asking this user whether he/she can provide the language he using and a screenshot. Sorry for not providing English 😂
