### ISSUE TITLE
Welcome page opens in Codespaces even when workbench.startupEditor is set to "none" in Remote settings

### ISSUE THREAD

**Issue by dmalan** [microsoft/vscode#134073]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.60.2, via Codespaces
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Create a Codespace from a repo containing a `.devcontainer.json` with `"workbench.startupEditor": "none"`.
2. Welcome page still opens within a tab, per screenshot below.

Per https://github.com/microsoft/vscode/issues/124689#issuecomment-856956918, it sounds like `"none"` should work as a Workspace setting, though? And the Welcome page does not appear if one sets `"workbench.startupEditor": "none"` in VS Code locally with Settings Sync enabled and then creates a codespace. Per @jkeech, might the startup editor be opening before Remote settings have fully loaded? Thank you!

<img width="1201" alt="Screen Shot 2021-09-28 at 8 27 00 PM" src="https://user-images.githubusercontent.com/788678/135183172-e9afd0e3-b58e-4879-9f64-927daae1652c.png">

CC @rongxin-liu

**Comment by jkeech** [comment]
I actually wonder if this is related to https://github.com/microsoft/vscode/pull/134169. It looks like there was an issue which forced the Welcome page to always open in the web which was fixed in that PR.

**Comment by JacksonKearl** [comment]
Yes this should be resolved by #134169.

**Comment by dmalan** [comment]
Hi @JacksonKearl, just switched over to Insider (a4342f3addc29f405a5cb4aab359b0b98223411e, a slightly newer commit), and the **Welcome** tab is indeed gone, but it looks like there's now a **Getting Started** tab that opens by default in new Codespaces, even with

```json
"workbench.startupEditor": "none"
```

in our `.devcontainer.json`, per the screenshot below. (I gather from https://github.com/microsoft/vscode/pull/133651 that **Get Started** might just be the new title for what was previously the **Welcome** tab.) Should the setting above be suppressing the **Get Started** tab, though? Many thanks!

![image](https://user-images.githubusercontent.com/788678/135954420-43dde918-11fd-42f1-b7a3-d1fabf7744e7.png)

**Comment by JacksonKearl** [comment]
@dmalan what platform are you using to access codespaces? i.e. Desktop Insiders or the online codespace URL?

I see in the telemetry notice at the bottom of the editor there's `Code - Insiders collects usage data...`, hinting that this may be Desktop, in which case we do expect that notice to show.
