### ISSUE TITLE
Expect to see Code cells in Jupyter Outline/ToC

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#134055]
Testing #133901

I expected to see Code cells in the ToC/Outline, like I do when I bring up the outline through the command palette.

To bring up the Outline via the command palette, press `F1` then type in `@`.  Note the differences in the content with the Outline view.

![image](https://user-images.githubusercontent.com/1487073/135157140-222b2a8e-8211-4d50-9604-e19aa53a3211.png)

Part of the confusion for me was that initially I didn't have any markdown (despite the instructions to test... who reads the manual ??) , just code and output, then the Outline view is empty and looks broken.

**Comment by IanMatthewHuff** [comment]
@chrisdias It's funny, I had the same reaction as you. So the view that I think you (and I expected) to see would be the view if you change this setting from the default:
![image](https://user-images.githubusercontent.com/812783/135172957-c549e461-52d3-4bd1-bb90-17e6afaaa56b.png)
With this setting on you get code cells in the outline as well.
![image](https://user-images.githubusercontent.com/812783/135173032-704af6a7-c78d-4284-8870-95a9b2c18929.png)

I feel like this might be a conflict between VS Code users expectations and Jupyter users expectations as the classic Jupyter ToC extension and Jupyterlab ToC extension work with headings. But VS Code users might expect what you and I were looking for. I'll bring this up at the next notebook standup, might be worth discussing.
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html
https://jupyterlab.readthedocs.io/en/stable/user/toc.html

**Comment by chrisdias** [comment]
I really want to see the outline within the code blocks too rather than each line (if there is one).

**Comment by jrieken** [comment]
I started this just like @chrisdias wants it to be but got feedback that code-cell in outline are to noisy. I am fine changing it either way. We could also experiment with retrieving the "real" symbol-based outline and add that into the tree

**Comment by chrisdias** [comment]
+1 on seeing what the "real" symbol-based outline would look like.

**Comment by jrieken** [comment]
Problem with "real" symbols is that notebook code cells are often just variables and expressions and those traditionally don't show in outlines

**Comment by IanMatthewHuff** [comment]
We talked about this briefly in notebook standup, and I took a look more at what JupyterLab does. They default to headings, but then allow for either markdown or code cells to be added:
Default:
![image](https://user-images.githubusercontent.com/812783/135354338-77c9f69f-ff3d-4620-a5fb-a4327e7cca3c.png)
Markdown:
![image](https://user-images.githubusercontent.com/812783/135354374-2a0b074a-d318-475e-be63-2c34380ba826.png)
Code cells:
![image](https://user-images.githubusercontent.com/812783/135354442-487c2ca2-2633-443b-963a-4d15b17bd5fe.png)

Looks much nicer with font and weighting versus how our current implementation looks when code cells are added. My vote at least with the current implementation would be to keep the setting as is (code cells off) just to keep the noise down.

**Comment by rchiodo** [comment]
+1 on code outline. It does look messy with the code, but maybe there's a way to detect language too? Then use the language's icon for the code?

**Comment by IanMatthewHuff** [comment]
Another point of interest. The default for jupyter is headings. Code shows all markdown cells, that contributes to a bit of the default noise here as well:
![image](https://user-images.githubusercontent.com/812783/135356374-2bc00a11-1156-4c18-8024-14c1fbfe160a.png)

With code cells off:
![image](https://user-images.githubusercontent.com/812783/135356438-6b811eda-c14c-4909-9e27-25687c9c2175.png)

If you break up code cells with explanatory markdown cells (without headings) things can look busy and confusing really quick, even in the default settings.

**Comment by DonJayamanne** [comment]
I'm for just markdowns, when going through a TOC for a document/article/book, i don't expect to see code, i haven't seen that.
Its the heading that i want to see, e.g. I would expect to see a markdown cell such as `Http Request Sample` or `Image Classification Model` & then have a code cell that follows that.

See here below for an example (seeing the code will make little to no sense to me, the related heading is what's important & not the code)
If anything the code would add noise (at least for me)
![Screen Shot 2021-09-29 at 15 30 50](https://user-images.githubusercontent.com/1948812/135357568-20867b5b-a870-43ee-b126-878ca208c9fa.png)

**Comment by misolori** [comment]
The problem I see is there are many places where we can show code cells: breadcrumbs, symbol viewer, and outline. If we decide to not show code cells then we should think about whether it makes sense to not show it in those other areas.

**Comment by DonJayamanne** [comment]
> would leverage those other features.

Agreed, I don't use breadcrumbs in nbs at all, but use it in regular code files

> Would also love for an outline filter option from the view (similar to our other filters).

Sounds like a great idea

**Comment by greazer** [comment]
If we're trying to decide whether to keep code-cells off in the outline view by default, then I think the answer *right now* is yes. I mean, the code-cell visualizations in breadcrumbs, symbol viewer and outline feel "messy" and not particularly useful.

Breadcrumb
![image](https://user-images.githubusercontent.com/11685408/135364968-d5649f7b-28ab-4559-9bb6-e2adc827588f.png)

Symbols
![image](https://user-images.githubusercontent.com/11685408/135365037-1e930537-9761-497c-84b2-30639f85e5fb.png)

Outline
![image](https://user-images.githubusercontent.com/11685408/135365135-027cc1c7-8af0-4d47-a17c-41205ff5ebca.png)

Breadcrumbs, Symbols, and Outline view were designed to show where symbols are first defined in a source file. That's not how we're using it here. In addition, I wish I could navigate my source file via the markdown comments in the Interactive Experience. As it stands now, those comment sections are just ignored in that scenario.

I feel like we're mixing use-cases here and that's what's causing the hangups. In other words, it seems like we need to gracefully incorporate "comment-based navigation" to the Outline View and Breadcrumbs. Symbols should stay only symbols, imo. 

In general, code files are typically structured around the code itself. Notebooks are structured around a task that isn't necessarily logically codified than by anything other than comments that break the task into conceptual pieces defined by the author. 
  
I'm not sure I'm making much sense here, but I think there's a thread that needs to be pulled a bit more. So I'm going to commit this comment and wait so see what people think. :)

**Comment by jglwiz** [comment]
Could the outline panel or symbol panel provide the code cell info? 

As a user using screen reader,  it is hard to navigate between cells, especially the code cells. The reader only provide cell index info. For example, it reports " cell 19, code cell ...".  Could it provides the abstract info such as the first comment line in outline or symbol panel.

In previous version, it provides the function in symbol panel. The symbol panel shows all the first line of each cell as bellow.
![image](https://github.com/microsoft/vscode/assets/4366011/d396c644-aaa7-45ba-8b0a-18f10d4493f0)
 
When update to new version (jupyter 2024.02), the function is removed. The defination is shown. The info of cells containing function call is missing.
![image](https://github.com/microsoft/vscode/assets/4366011/2e118cae-dcd6-4c65-ad25-6d0e4224338b)

Could the cell abstraction info is provided in outline?

**Comment by Yoyokrazy** [comment]
@jglwiz Currently the first line of a code cell is the label for code cell entries within the outline view. If you aren't seeing code cells in the outline view, enabling the setting `notebook.outline.showCodeCells` should fix that.

**Comment by Yoyokrazy** [comment]
Going to close this as completed as it looks like over time a lot of this has been addressed. The current state of things are as follows:
- Code cells can be enabled or disabled in both breadcrumbs and outline via `notebook.outline.showCodeCells` and `notebook.breadcrumbs.showCodeCells`. Default for outline is turned off, and breadcrumbs is turned on.
- Code cells in both the outline and breadcrumbs only show the first line of code in the cell. Users appear to be putting a one line comment to give themselves relevant navigable information (see the comment above)

There is also current work going on to let users control whether or not they will see standard markdown cells in the outline, or if only header information should be shown. That progress along with other nb outline view polish can be tracked via #206308
