### ISSUE TITLE
Terminal tab description - how was default determined

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#134029]
Testing #133549

I see the default is `${task}${separator}${local}${separator}${cwdFolder}`, and for the terminals I was using, no description was initially appearing, so I was confused where I was supposed to see one and if I was looking in the wrong spot. Upon a search of this issue I realized [what the description was](https://github.com/microsoft/vscode/issues/29816) and where I should be seeing it and was then able to play around and start seeing changes. 

Was `${task}${separator}${local}${separator}${cwdFolder}` deemed a universal enough basis for folks who will take advantage of this setting? It seems like such a long contrast in comparison to the `${process}` default for title.

**Comment by meganrogge** [comment]
We want to keep info/clutter to a minimum. We decided upon that as the default description because descriptions should only be shown when they're important. On Windows, as you state, that happens less frequently, since we don't currently have cwdDetection enabled.
