### ISSUE TITLE
Terminal tab title flashes on reload

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134021]
Testing #133549
1. Have a terminal tab title setting such as `${cwd}${separator}${process}`
2. Create a couple of terminals
3. Rename one to "foo"
4. Reload the window
5. 🐛 You briefly see the default title flash in before the custom title is resolved

**Comment by meganrogge** [comment]
This happens bc the title gets set by the process and then again if there's a custom config.

**Comment by lramos15** [comment]
It's quite ugly though, is there no way to allow the title to be blank until you have the config value and then choose one? I feel like it's a bad precedent to say flashing is by design if it's possible to avoid it

**Comment by meganrogge** [comment]
we don't want to wait for the config value to be resolved for every terminal because that would look really laggy
