### ISSUE TITLE
`Learn More` in marketplace points to the wrong URL if a platform specific extension not targeted to your platform

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#134070]
Testing #133868

![image](https://user-images.githubusercontent.com/13199757/135179445-e9a6dee9-b4ac-4350-8ac3-c69f8f184fcd.png)

It should point to
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions
instead of
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platform-specific-extensions

Notice the extra `-` in `platform-specific-extensions`.

Either this, or URL itself needs to be corrected to include `-`.

**Comment by karrtikr** [comment]
Sorry, why was this closed, was this fixed?

**Comment by sandy081** [comment]
Yes, fixed the link in aka.ms
