### ISSUE TITLE
Direct Acces to Terminal

### ISSUE THREAD

**Issue by Yester668** [Microsoft/vscode#13400]
- VSCode Version:
- OS Version:

Si alguien puede traducirlo lo agradecería mucho.

Tenemos abajo una barra con mucho espacio en la que se podrían poner accesos directos... por ejemplo al termina.

**Comment by kube** [comment]
So the translated version would be that there's a lot of space at the bottom of the app, where could be inserted direct accesses, to terminal for example.

**Comment by Tyriar** [comment]
VS Code has an integrated terminal already, you can toggle it through the menu or ctrl+`
