### ISSUE TITLE
Source control "More Actions" closes after a few seconds regardless mouse button

### ISSUE THREAD

**Issue by hanak** [microsoft/vscode#134093]
Issue Type: <b>Bug</b>

1) Create a folder "A"
2) Start Visual Studio Code.
3) Open the folder "A"
4) Initialize the folder "A" as a GIT.
5) Open "Source Control" tab.
6) Click "..." next to the refresh icon in the section "Source Control". This opens a menu containing commit-related actions. Move cursor over any item in the menu. The menu disappears after a few seconds regardless whether the cursor has highlighted an item or a submenu has been expanded.

Further observation:
* The issue does not seem to appear if there are submodules.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (24.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
mermaid-markdown-syntax-highlighting|bpr|1.2.2
gitlens|eam|11.6.0
vscode-docker|ms-|1.17.0
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
vscode-epics|nsd|1.1.0
vscode-yaml|red|0.22.0

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen after you run the Command Palette command to reload with all extensions disabled?

**Comment by joaomoreno** [comment]
This happens when context keys change and actions bars actions get replaced.

**Comment by lszomoru** [comment]
Tried to repro this on both Windows and macOS without any luck. As this has been reported on an old version of VS Code, I will optimistically close this issue as many changes have occurred in this space. @hanak, please feel free to reopen the issues in case you are still able to reproduce the problem. Thanks!
