### ISSUE TITLE
Drag files across remote windows with timeline information

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#134050]
Testing #133922

I think one of the use cases for this feature of dragging across remote windows is to quickly duplicate or scaffold files in other repos (like a Readme.md, a Security.md file, etc). 

Do you think there is a use case where devs might want to keep the timeline information of the file from the original window/folder it's a part of? Currently, when you drag and drop a file, the timeline history is empty in the new window.

**Comment by sbatten** [comment]
That would be some cool magic but that history belongs to git, I would think the amount of work to enable something like that is quite high.

cc @eamodio in case I'm wrong

**Comment by eamodio** [comment]
Yeah, I can't really think of any way of preserving that (other than starting with the file contents of the first commit and then committing each diff on top of the last to build up the history). Which while technically feasible, I don't think that would be what you want (actual commits anyway). But what could be interesting is to convert the revision history of the file into a sort of local file history. But we don't have a local file history at this point 😁
