### ISSUE TITLE
allow resetting custom named terminal to use default terminal name

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#134020]
Testing #133549
1. Have a terminal tab title setting
2. Rename your terminal to "foo"
3. Try to set the name to blank string 
4. Unable to, but I would expect it to just use my default from 1.

**Comment by meganrogge** [comment]
We discussed this and want to require a title.

**Comment by lramos15** [comment]
I don't mean that blank titles should be required. I more meant how do I get back to the default I set in settings after I renamed the terminal, I feel I would expect it to let me delete my custom name and then it would use the default

**Comment by meganrogge** [comment]
You can reset the setting - is that what you mean?

**Comment by lramos15** [comment]
No I meant is there a way to reset the terminal title to be the value of my setting instead of my custom named one?

**Comment by meganrogge** [comment]
We currently don't support going backward like that. I'll appropriately rename this issue for more discussion in October because I also wondered about this and discussed it with @Tyriar.

**Comment by lramos15** [comment]
Thanks sorry if I wasn't clear 👍 . My suggested UX would just be to have that be the default if you were attempt to have a blank name

**Comment by meganrogge** [comment]
oh - yes Brigit caught that case and I fixed. so if it's blank, it'll now show the process name

**Comment by lramos15** [comment]
But shouldn't it show whatever my setting states the default is rather than just the process name?

**Comment by lramos15** [comment]
Sorry, the difference between our issues is she is talking about the setting I'm talking about the terminal title itself and not the setting. I want a blank rename of a terminal to reset to the value of my setting

**Comment by meganrogge** [comment]
I thought your setting was set to ''

**Comment by meganrogge** [comment]
confused - you can't set it to blank. we don't allow that

**Comment by meganrogge** [comment]
![recording (75)](https://user-images.githubusercontent.com/29464607/135161826-4285aaef-ad34-4427-8b53-686905f02858.gif)

**Comment by lramos15** [comment]
So my request is if my setting is `${cwd}${separator}${process}` and I name a terminal "foo". How do I reset "foo" back to the value of `${cwd}${separator}${process}`. My suggestion was that if you attempted to submit a blank name that would automatically reset to the value of your setting.

**Comment by meganrogge** [comment]
yep the name of this issue now reflects that. we'll see what @Tyriar says about that.

**Comment by meganrogge** [comment]
@Tyriar and I discussed it and it makes sense to do this
