### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by Daemach** [microsoft/vscode#134022]
We have written the needed data into 
Issue Type: <b>Bug</b>

open VSCode.

Wait for error.

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (24.17GB free)|
|Process Argv|C:\\dev\\Veriti\\admin\\frontend --crash-reporter-id b24c52c0-2b49-41a8-a55e-80f683f2988d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sql-formatter|adp|1.4.4
stackoverflow-search|Ale|1.2.0
turbo-console-log|Cha|2.1.7
vscode-eslint|dba|2.1.25
xml|Dot|2.5.1
gitlens|eam|11.6.0
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|9.0.0
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.12
vscode-edit-csv|jan|0.6.2
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.17.0
mssql|ms-|1.10.1
remote-containers|ms-|0.194.0
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.6.0
powershell|ms-|2021.9.0
cordova-tools|msj|2.3.0
vetur|oct|0.34.1
indent-rainbow|ode|8.1.0
vscode-coldbox|ort|1.0.3
vscode-commandbox|ort|1.0.2
platformio-ide|pla|2.3.3
toggle-case|Pra|0.1.2
sass-indented|syl|1.8.18
shell-launcher|Tyr|0.4.1
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140:30363603
vssur157:30367808

```

</details>

your clipboard because it was too large to send. Please paste.

**Comment by CodeCrazy-ywt** [comment]
What kind of error? Screenshot?
