### ISSUE TITLE
Test platform specific extensions - Marketplace only lists last published platform

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#134067]
Testing #133868

1. Scaffold an extension following the docs or clone https://github.com/microsoft/vscode-platform-specific-sample
2. Run `vsce publish --target darwin-x64`
3. Make some changes in the extension, bump up the version number
4. Run `vsce publish --target linux-x64`
5. Check the extension page on the Marketplace, the detail of the "Works with" label on the right side only contains the platform that was last published (Linux x64)

**Comment by sandy081** [comment]
@isidorn This seems to be a request to MP.

Not sure if MP wants to show the latest version per target platform but I think we would like to show always the latest version available and it is the author's responsible to have the latest version available for all platforms.

**Comment by joaomoreno** [comment]
We decided this. The sidebar should only show the platforms of the highest version.

**Comment by isidorn** [comment]
@kimadeline thanks a lot for testing though 👏
