### ISSUE TITLE
Test: Run by Line and Debug Cell with a remote kernel

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#134038]
Refs: https://github.com/microsoft/vscode-jupyter/issues/1652

- [x] macOS @misolori
- [x] linux @connor4312 
- [x] windows @rchiodo

Complexity: 3

Authors: @roblourens, @DavidKutu

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F133905&assignees=roblourens,DavidKutu)

---
### Setup

- Use VS Code Insiders and the latest jupyter and python extensions
- Make sure that you have python 3.7 or greater installed and on your path as python3 or python
- Set up a python virtualenv:

```
mkdir jupyter-dbg
cd jupyter-dbg
python3 -m venv ipykernel-env
```
- Activate the virtual environment

Mac/Linux:
```
source ipykernel-env/bin/activate
```

Windows:
```
ipykernel-env\Scripts\activate.bat
```

- Install the latest version of ipykernel in the virtual environment, which has debugging support
```
pip install ipykernel --pre
python3 -m ipykernel install --user
```

- Install the latest version of jupyter in the virtual environment
```
pip install jupyter
python3 -m jupyter
```

- Start a Jupyter Server from your virtual environment with `python -m notebook`
![image](https://user-images.githubusercontent.com/20347396/135137404-b6b8cfb5-ddda-4876-a88f-1e116940820f.png)
- Open a .ipynb notebook file (You can use [this one](https://github.com/claudiaregio/data-science/blob/main/Titanic.ipynb) if you need one)
- Run the command `Specify local or remote Jupyter server for connections`, then click on `existing`, then paste the url from the server you started, and finally the extension will ask you to restart
![image](https://user-images.githubusercontent.com/20347396/135138215-47bb9c74-5cb0-4574-a5b2-d1f4052072ec.png)
- Set `"jupyter.logging.level": "verbose"`

### Testing

- Test the same scenarios as https://github.com/microsoft/vscode/issues/133903 and https://github.com/microsoft/vscode/issues/133905

### Filing issues
File issues on the jupyter repo using the link above. **Include the log from the Jupyter output channel**

**Comment by misolori** [comment]
@DavidKutu i'm stuck when trying to launch the notebook via `python -m notebook`:

<img width="796" alt="CleanShot 2021-09-28 at 11 48 10@2x" src="https://user-images.githubusercontent.com/35271042/135147572-692cbdad-c85d-405a-81aa-52beea19a26a.png">

**Comment by roblourens** [comment]
You probably also have to install jupyter in that venv, `pip install jupyter`, is that right @DavidKutu?

**Comment by DavidKutu** [comment]
yes! sorry for the confusion

**Comment by misolori** [comment]
ah that was it, thanks!
