### ISSUE TITLE
Terminal title/description differentiation

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#134004]
Testing #133549

Have we considered using the UI pattern available in the tree view in which the name and the description are visually differentiated? Given that both the title and the description can be fully customised using settings, I think that it would be helpful to make it visually clear which is the title and which is the description. 

Now that I think of it, is there value in having two different settings for title/description instead of just one?

**Comment by meganrogge** [comment]
in the tabs list and in the editor tabs they appear different (description is dimmed)

we considered adding custom CSS for the single tab view so they are different, but considered that out of scope/unnecessary given the amount of work it would require

**Comment by meganrogge** [comment]
regarding the different two settings, Kai mentioned that as well. The reason we went with this is it aligns with the editor and how that works.
